### ISSUE TITLE
`None` in the fetching list

### ISSUE THREAD

**Issue by xlnwel** [ray-project/ray#10153]
Hi, I participate in [this challenge](https://www.aicrowd.com/challenges/neurips-2020-procgen-competition), which requires using `ray[rllib]==0.8.6`. 

I've implemented an algorithm and it works without any issue locally. However, when evaluating at the server, I get an error message as follows
 
>ERROR tf_run_builder.py:47 -- Error fetching: [None, {'learner_stats': {'max_rewar
d': <tf.Tensor 'default_policy/Max:0' shape=() dtype=float32>, 'discount': <tf.Tensor 'default_policy/Mean_12:0' shape=() dtype=float32>, 'gamma': <tf.Tensor 'default_policy/Cons
t_14:0' shape=() dtype=float32>, 'max_prob': <tf.Tensor 'default_policy/Mean_13:0' shape=() dtype=float32>, 'max_q': <tf.Tensor 'default_policy/Mean_14:0' shape=() dtype=float32>
, 'q': <tf.Tensor 'default_policy/Mean_15:0' shape=() dtype=float32>, 'next_q': <tf.Tensor 'default_policy/Mean_16:0' shape=() dtype=float32>, 'next_value': <tf.Tensor 'default_p
olicy/Mean_17:0' shape=() dtype=float32>, 'next_entropy': <tf.Tensor 'default_policy/Mean_18:0' shape=() dtype=float32>, 'td_error': <tf.Tensor 'default_policy/Mean_19:0' shape=(
) dtype=float32>, 'actor_loss': <tf.Tensor 'default_policy/Neg_4:0' shape=() dtype=float32>, 'critic_loss': <tf.Tensor 'default_policy/truediv_5:0' shape=() dtype=float32>, 'temp
_loss': <tf.Tensor 'default_policy/Neg_5:0' shape=() dtype=float32>, 'temp_value': <tf.Tensor 'default_policy/Exp_1:0' shape=() dtype=float32>, 'entropy': <tf.Tensor 'default_pol
icy/Mean_20:0' shape=() dtype=float32>, 'target_entropy': <tf.Tensor 'default_policy/Const_23:0' shape=() dtype=float64>, 'entropy_diff': <tf.Tensor 'default_policy/Mean_21:0' sh
ape=() dtype=float32>, 'model': {}, 'actor_norm': 0, 'critic_norm': 0, 'temp_norm': 0}, 'td_error': <tf.Tensor 'default_policy/truediv_4:0' shape=(?,) dtype=float32>}], feed_dict
={<tf.Tensor 'default_policy/observation:0' shape=(?, 64, 64, 12) dtype=float32>:...

I know that the second element in the fetching list, a `dict`, comes from my custom `stats_fn`(something like [this code](https://github.com/ray-project/ray/blob/edd783bc327760a4892ab89222ee551e42df15b9/rllib/agents/sac/sac_tf_policy.py#L454)), but I have no idea where the first `None` comes from. The logs provided by the server is relatively limited(see below. It basically says there is None in the fetching list), and not related to any code I write

>2020-08-15 14:16:29 | (pid=103)
-- | --
  | 2020-08-15 14:16:29 | (pid=103) TypeError: Fetch argument None has invalid type <class 'NoneType'>
  | 2020-08-15 14:16:29 | (pid=103)     (fetch, type(fetch)))
  | 2020-08-15 14:16:29 | (pid=103)   File "/home/aicrowd/.conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 263, in for_fetch
  | 2020-08-15 14:16:29 | (pid=103)     self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  | 2020-08-15 14:16:29 | (pid=103)   File "/home/aicrowd/.conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 378, in <listcomp>
  | 2020-08-15 14:16:29 | (pid=103)     self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  | 2020-08-15 14:16:29 | (pid=103)   File "/home/aicrowd/.conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 378, in __init__
  | 2020-08-15 14:16:29 | (pid=103)     return _ListFetchMapper(fetch)
  | 2020-08-15 14:16:29 | (pid=103)   File "/home/aicrowd/.conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 266, in for_fetch
  | 2020-08-15 14:16:29 | (pid=103)     self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  | 2020-08-15 14:16:29 | (pid=103)   File "/home/aicrowd/.conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 477, in __init__
  | 2020-08-15 14:16:29 | (pid=103)     self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  | 2020-08-15 14:16:29 | (pid=103)   File "/home/aicrowd/.conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1166, in _run
  | 2020-08-15 14:16:29 | (pid=103)     run_metadata_ptr)
  | 2020-08-15 14:16:29 | (pid=103)   File "/home/aicrowd/.conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 958, in run
  | 2020-08-15 14:16:29 | (pid=103)     fetches = sess.run(ops, feed_dict=feed_dict)
  | 2020-08-15 14:16:29 | (pid=103)   File "/home/aicrowd/.conda/lib/python3.7/site-packages/ray/rllib/utils/tf_run_builder.py", line 89, in run_timeline
  | 2020-08-15 14:16:29 | (pid=103)     self.feed_dict, os.environ.get("TF_TIMELINE_DIR"))
  | 2020-08-15 14:16:29 | (pid=103)   File "/home/aicrowd/.conda/lib/python3.7/site-packages/ray/rllib/utils/tf_run_builder.py", line 44, in get
  | 2020-08-15 14:16:29 | (pid=103)     raise e
  | 2020-08-15 14:16:29 | (pid=103)   File "/home/aicrowd/.conda/lib/python3.7/site-packages/ray/rllib/utils/tf_run_builder.py", line 48, in get
  | 2020-08-15 14:16:29 | (pid=103)     info_out.update({k: builder.get(v) for k, v in to_fetch.items()})
  | 2020-08-15 14:16:29 | (pid=103)   File "/home/aicrowd/.conda/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 714, in <dictcomp>
  | 2020-08-15 14:16:29 | (pid=103)     info_out.update({k: builder.get(v) for k, v in to_fetch.items()})
  | 2020-08-15 14:16:29 | (pid=103)   File "/home/aicrowd/.conda/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 714, in learn_on_batch
  | 2020-08-15 14:16:29 | (pid=103)     grad_out = self.local_worker.learn_on_batch(replay)
  | 2020-08-15 14:16:29 | (pid=103)   File "/home/aicrowd/.conda/lib/python3.7/site-packages/ray/rllib/agents/dqn/learner_thread.py", line 46, in step
  | 2020-08-15 14:16:29 | (pid=103)     self.step()
  | 2020-08-15 14:16:29 | (pid=103)   File "/home/aicrowd/.conda/lib/python3.7/site-packages/ray/rllib/agents/dqn/learner_thread.py", line 37, in run
  | 2020-08-15 14:16:29 | (pid=103)     self.run()
  | 2020-08-15 14:16:29 | (pid=103)   File "/home/aicrowd/.conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
  | 2020-08-15 14:16:29 | (pid=103) Traceback (most recent call last):
  | 2020-08-15 14:16:29 | (pid=103) Exception in thread Thread-1:
  | 2020-08-15 14:16:29 | (pid=103) TypeError: Fetch argument None has invalid type <class 'NoneType'>

Where should I look at or how can I fix it?

Ps. I'm also confused about why there is a fetching list at all as I use TF2.2 which uses `tf.function` instead of `sess` to run the graph.

**Comment by rkooo567** [comment]
cc @sven1977

**Comment by xlnwel** [comment]
I finally realized that I have to specify `TF` version and all other settings in the `yaml` file. Before I specified them in `DEFUALT_CONFIG`
