### ISSUE TITLE
[rllib] Evaluation workers can't access model which is being trained on a GPU

### ISSUE THREAD

**Issue by iamhatesz** [ray-project/ray#10175]
### What is the problem?

When training a model on a GPU, evaluation workers cannot restore it, as they don't have access to a GPU. Maybe a missing `map_location` handling in `torch.load`?

```
Traceback (most recent call last):
  File "/home/twrona/.cache/pypoetry/virtualenvs/a-DqWBqM4X-py3.7/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 471, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/twrona/.cache/pypoetry/virtualenvs/a-DqWBqM4X-py3.7/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 430, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/twrona/.cache/pypoetry/virtualenvs/a-DqWBqM4X-py3.7/lib/python3.7/site-packages/ray/worker.py", line 1538, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::PPO.train() (pid=304440, ip=10.8.37.145)
  File "python/ray/_raylet.pyx", line 479, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/home/twrona/.cache/pypoetry/virtualenvs/a-DqWBqM4X-py3.7/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 534, in train
    evaluation_metrics = self._evaluate()
  File "/home/twrona/.cache/pypoetry/virtualenvs/a-DqWBqM4X-py3.7/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 734, in _evaluate
    lambda w: w.restore(ray.get(weights)))
  File "/home/twrona/.cache/pypoetry/virtualenvs/a-DqWBqM4X-py3.7/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 126, in foreach_worker
    [w.apply.remote(func) for w in self.remote_workers()])
ray.exceptions.RayTaskError(RuntimeError): ray::RolloutWorker.apply() (pid=304444, ip=10.8.37.145)
  File "python/ray/_raylet.pyx", line 479, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/home/twrona/.cache/pypoetry/virtualenvs/a-DqWBqM4X-py3.7/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 947, in apply
    return func(self, *args)
  File "/home/twrona/.cache/pypoetry/virtualenvs/a-DqWBqM4X-py3.7/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 734, in <lambda>
    lambda w: w.restore(ray.get(weights)))
  File "/home/twrona/.cache/pypoetry/virtualenvs/a-DqWBqM4X-py3.7/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 894, in restore
    objs = pickle.loads(objs)
  File "/home/twrona/.cache/pypoetry/virtualenvs/a-DqWBqM4X-py3.7/lib/python3.7/site-packages/torch/storage.py", line 142, in _load_from_bytes
    return torch.load(io.BytesIO(b))
  File "/home/twrona/.cache/pypoetry/virtualenvs/a-DqWBqM4X-py3.7/lib/python3.7/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/twrona/.cache/pypoetry/virtualenvs/a-DqWBqM4X-py3.7/lib/python3.7/site-packages/torch/serialization.py", line 765, in _legacy_load
    result = unpickler.load()
  File "/home/twrona/.cache/pypoetry/virtualenvs/a-DqWBqM4X-py3.7/lib/python3.7/site-packages/torch/serialization.py", line 721, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/twrona/.cache/pypoetry/virtualenvs/a-DqWBqM4X-py3.7/lib/python3.7/site-packages/torch/serialization.py", line 174, in default_restore_location
    result = fn(storage, location)
  File "/home/twrona/.cache/pypoetry/virtualenvs/a-DqWBqM4X-py3.7/lib/python3.7/site-packages/torch/serialization.py", line 150, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/twrona/.cache/pypoetry/virtualenvs/a-DqWBqM4X-py3.7/lib/python3.7/site-packages/torch/serialization.py", line 134, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

*Ray version and other system information (Python version, TensorFlow version, OS):* 0.8.6, 0.8.7, PyTorch 1.6

### Reproduction (REQUIRED)

Doesn't work:

```python
import ray
from ray import tune

if __name__ == '__main__':
    ray.init()
    tune.run(
        "PPO",
        config={
            "env": "CartPole-v1",
            "framework": "torch",
            "num_gpus": 1,
            "num_workers": 4,
            "num_gpus_per_worker": 0,
            "evaluation_num_workers": 1,
            "evaluation_interval": 1,
        }
    )
```

Works:

```python
import ray
from ray import tune

if __name__ == '__main__':
    ray.init()
    tune.run(
        "PPO",
        config={
            "env": "CartPole-v1",
            "framework": "torch",
            "num_gpus": 0.5,
            "num_workers": 4,
            "num_gpus_per_worker": 0.1,
            "evaluation_num_workers": 1,
            "evaluation_interval": 1,
        }
    )
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ericl** [comment]
Hmm this is unfortunate, it's too bad PyTorch doesn't auto-convert tensors in such situations. @sven1977 I wonder if we can solve this by not serializing the tensors directly (perhaps they should be converted into numpy arrays as we do for get/set_weights()?)

**Comment by lasagnaphil** [comment]
There was a bugfix for something similar to this issue recently (#11208), can you try with the latest builds?

**Comment by iamhatesz** [comment]
@lasagnaphil I've just retested and I can confirm that with today's latest wheels the script works. Thanks!
