### ISSUE TITLE
Defunct jupyter notebooks in jenkins tests.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1020]
It turns out this is fairly easy to reproduce.

If you build the Ray docker image with

```
cd ray
./build-docker.sh
```

Then start a container

```
docker run -t -i ray-project/deploy:latest /bin/bash
```

First check to see if there are any notebook processes.

```
ps aux | grep jupyter
```

Then run the following in Python.

```python
import subprocess
subprocess.Popen(['jupyter-notebook'])
```

This will fail with a message like

```
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/opt/conda/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/traitlets/config/application.py", line 652, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/notebook/notebookapp.py", line 1071, in initialize
    self.init_webapp()
  File "/opt/conda/lib/python2.7/site-packages/notebook/notebookapp.py", line 919, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/opt/conda/lib/python2.7/site-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/opt/conda/lib/python2.7/site-packages/tornado/netutil.py", line 194, in bind_sockets
    sock.bind(sockaddr)
  File "/opt/conda/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
```

If you attach to the container in another terminal window (filling in the appropriate value of `CONTAINER_ID`), e.g.,

```
docker exec -t -i CONTAINER_ID /bin/bash
```

and check for jupyter notebooks, you'll see `ps aux | grep jupyter` prints something like

```
root        56  1.8  0.0      0     0 pts/0    Z+   23:36   0:00 [jupyter-noteboo] <defunct>
```

Exiting from the original python process will get rid of the defunct jupyter notebook.

It's possible that in our jenkins tests the python process that starts the jupyter notebook is not exiting properly or something.

cc @shaneknapp

**Comment by robertnishihara** [comment]
As of #1021, there should no longer by any defunct jupyter notebook processes (because we aren't starting any jupyter notebook processes in Jenkins. There may still be defunct processes of other types..
