### ISSUE TITLE
[Autoscaler] Silent failure when "Arn" is not in the name.

### ISSUE THREAD

**Issue by hammacktony** [ray-project/ray#10243]
### What is the problem?

When running the `ray up` command, I  get the following error:

```
[Container] 2020/08/21 13:22:12 Running command ray up -y deployment/$ENV/deploy.yaml
2020-08-21 13:22:14,812 INFO cli_logger.py:388 -- _configure_security_group: SecurityGroupIds not specified for head node, using ray-autoscaler-demo-kinesis-video-labeller (sg-0a3a968f19302896a)
2020-08-21 13:22:14,812 INFO cli_logger.py:388 -- _configure_security_group: SecurityGroupIds not specified for workers, using ray-autoscaler-demo-kinesis-video-labeller (sg-0a3a968f19302896a)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1237, in main
    return cli()
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 717, in up
    create_or_update_cluster(cluster_config_file, min_workers, max_workers,
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/ray/autoscaler/commands.py", line 176, in create_or_update_cluster
    try_logging_config(config)
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/ray/autoscaler/node_provider.py", line 103, in try_logging_config
    log_to_cli(config)
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/ray/autoscaler/aws/config.py", line 159, in log_to_cli
    _arn_to_name(config["head_node"]["IamInstanceProfile"]["Arn"]),
KeyError: 'Arn'
```

This happens due to not finding "Arn" in the config yaml. However, the error should have happened sooner. Here is the relevant part of my config:

```json
head_node:
    InstanceType: m5.large
    ImageId: ami-**********
    SubnetIds: 
      - subnet-*****
    KeyName: ray-autoscaler_us-west-2
    IamInstanceProfile:
      Name: my-app
```

Since `IamInstanceProfile` is defined, the config object gets returned immediately in [config.py](https://github.com/ray-project/ray/blob/e968b52cb7de4e6c2fcc6e7d5ccb98d984745715/python/ray/autoscaler/aws/config.py#L207), even if the "Arn" field is not set. This was a bit of a hassle to debug because on my local box, I had 0.8.4 and things were fine. But, there is something with newer versions that is not working.

I would suggest more validation of the config file in either the `_parse_config` or `_validate_config` options or better documentation saying one needs to have "Arn" field present if you have "IamInstanceProfile" defined.

*Does not happen on 0.8.4, Happened when pulling newer versions from PyPi*

### Reproduction (REQUIRED)
Here is the config file for ray cluster. All AWS values have been anonymized.

```json
# An unique identifier for the head node and workers of this cluster.
cluster_name: demo-app

# The minimum number of workers nodes to launch in addition to the head
# node. This number should be >= 0.
min_workers: 0

# The maximum number of workers nodes to launch in addition to the head
# node. This takes precedence over min_workers.
max_workers: 2kvl

# The initial number of worker nodes to launch in addition to the head
# node. When the cluster is first brought up (or when it is refreshed with a
# subsequent `ray up`) this number of nodes will be started.
initial_workers: 0

# Whether or not to autoscale aggressively. If this is enabled, if at any point
#   we would start more workers, we start at least enough to bring us to
#   initial_workers.
autoscaling_mode: default

# This executes all commands on all nodes in the docker container,
# and opens all the necessary ports to support the Ray cluster.
# Empty string means disabled.
#docker:
#    image: "" # e.g., tensorflow/tensorflow:1.5.0-py3
#    container_name: "" # e.g. ray_docker
    # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
    # if no cached version is present.
#    pull_before_run: True
#    run_options: []  # Extra options to pass into "docker run"

    # Example of running a GPU head with CPU workers
    # head_image: "tensorflow/tensorflow:1.13.1-py3"
    # head_run_options:
    #     - --runtime=nvidia

    # worker_image: "ubuntu:18.04"
    # worker_run_options: []

# The autoscaler will scale up the cluster to this target fraction of resource
# usage. For example, if a cluster of 10 nodes is 100% busy and
# target_utilization is 0.8, it would resize the cluster to 13. This fraction
# can be decreased to increase the aggressiveness of upscaling.
# This value must be less than 1.0 for scaling to happen.
target_utilization_fraction: 0.8

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 5

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2
    # Availability zone(s), comma-separated, that nodes may be launched in.
    # Nodes are currently spread between zones by a round-robin approach,
    # however this implementation detail should not be relied upon.
    availability_zone: us-west-2a,us-west-2b

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
    ssh_private_key: ~/.ssh/ray-autoscaler_us-west-2.pem

# Provider-specific config for the head node, e.g. instance type. By default
# Ray will auto-configure unspecified fields such as SubnetId and KeyName.
# For more documentation on available fields, see:
# http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances
head_node:
    InstanceType: m5.large
    ImageId: ami-jkjlngeo09043kooier
    SubnetIds: 
      - subnet-fdfd9043s
    KeyName: ray-autoscaler_us-west-2
    IamInstanceProfile:
      Name: demo-app

    # You can provision additional disk space with a conf as follows
    BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
              VolumeSize: 20

    # Additional options in the boto docs.

# Provider-specific config for worker nodes, e.g. instance type. By default
# Ray will auto-configure unspecified fields such as SubnetId and KeyName.
# For more documentation on available fields, see:
# http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances
worker_nodes:
    InstanceType: m5.large
    ImageId: ami-jkjlngeo09043kooier
    SubnetIds:
      - subnet-fdfd9043s
    KeyName: ray-autoscaler_us-west-2
    IamInstanceProfile:
        - Name: demo-app

    # Run workers on spot by default. Comment this out to use on-demand.
    InstanceMarketOptions:
        MarketType: spot
        # Additional options can be found in the boto docs, e.g.
        #   SpotOptions:
        #       MaxPrice: MAX_HOURLY_PRICE

    # Additional options in the boto docs.

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {
    "/home/ubuntu/demo-app/demo-app": "demo-app",
    "/home/ubuntu/demo-app/requirements.txt": "requirements.txt",
    "/home/ubuntu/demo-app/env": "deployment/demo/ENV",
    "/home/ubuntu/demo-app/data": "data"
}

# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
initialization_commands: []

# List of shell commands to run to set up nodes.
setup_commands:
    - sudo pkill -9 apt-get || true
    - sudo pkill -9 dpkg || true
    - sudo apt-get update
    - sudo apt-get install -y python3-pip libsm6 libxext6 libxrender-dev
    - sudo ln -s /usr/bin/pip3 /usr/bin/pip || true
    - pip3 install virtualenv || true
    - virtualenv venv || true
    - venv/bin/pip3 install -r /home/ubuntu/demo-app/requirements.txt || true

# Custom commands that will be run on the head node after common setup.
#head_setup_commands:
#    - sudo pkill screen || true
#    - PYTHONPATH=/home/ubuntu/kinesis_video_labeller screen -dm  sh -c 'python3 -m kinesis_video_labeller'
# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - kvl/bin/ray stop
    - ulimit -n 65536; kvl/bin/ray start --head --redis-port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - kvl/bin/ray stop
    - ulimit -n 65536; kvl/bin/ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076

```

- [*] I have verified my script runs in a clean environment and reproduces the issue.
- [*] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
@ijrsvt Do you mind taking this issue?
