### ISSUE TITLE
[rllib] Weights & Biases integration doesn't work for RLlib

### ISSUE THREAD

**Issue by janblumenkamp** [ray-project/ray#10338]
### What is the problem?

If I try to integrate Weights & Biases according to the [relevant tune docs page](https://docs.ray.io/en/releases-0.8.7/tune/tutorials/tune-wandb.html) with RLlib, it crashes saying "Unknown config parameter `wandb`".

```
2020-08-26 11:31:51,029 ERROR trial_runner.py:523 -- Trial PPO_CartPole-v0_58d06_00000: Error processing event.
Traceback (most recent call last):           
  File "[...]/ray/tune/trial_runner.py", line 471, in _process_trial
    result = self.trial_executor.fetch_result(trial)             
  File "[...]/ray/tune/ray_trial_executor.py", line 430, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)                
  File "[...]/ray/worker.py", line 1538, in get
    raise value.as_instanceof_cause()                                     
ray.exceptions.RayTaskError: ray::PPO.train() (pid=32088, ip=128.232.69.20)
  File "python/ray/_raylet.pyx", line 439, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 474, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 478, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 479, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "[...]/ray/rllib/agents/trainer_template.py", line 88, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "[...]/ray/rllib/agents/trainer.py", line 479, in __init__
    super().__init__(config, logger_creator)
  File "[...]/ray/tune/trainable.py", line 245, in __init__
    self.setup(copy.deepcopy(self.config))
  File "[...]/ray/rllib/agents/trainer.py", line 580, in setup
    config)
  File "[...]/ray/rllib/agents/trainer.py", line 1067, in merge_trainer_configs
    cls._override_all_subkeys_if_type_changes)
  File "[...]/ray/tune/utils/util.py", line 181, in deep_update
    raise Exception("Unknown config parameter `{}` ".format(k))
Exception: Unknown config parameter `wandb`
```

- Ray 0.8.7
- Ubuntu 18.04
- Python 3.7

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
from ray import tune
from ray.rllib.agents.ppo import PPOTrainer
from ray.tune.logger import DEFAULT_LOGGERS
from ray.tune.integration.wandb import WandbLogger

tune.run(
    PPOTrainer,
    checkpoint_freq=1,
    config={
        "framework": "torch",
        "num_workers": 8,
        "num_gpus": 1,
        "env": "CartPole-v0",
        "wandb": {
            "project": "test",
            "api_key_file": "./wandb_api_key_file",
        }
    },
    stop={
        "training_iteration":1
    },
    loggers=DEFAULT_LOGGERS + (WandbLogger, )
)
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by amogkam** [comment]
cc @krfricke @richardliaw

**Comment by krfricke** [comment]
Hi @janblumenkamp, we addressed this issue recently in #10252

Basically, you'll have to wrap the wandb config in a `logger_config` key:

```
tune.run(
    PPOTrainer,
    checkpoint_freq=1,
    config={
        "framework": "torch",
        "num_workers": 8,
        "num_gpus": 1,
        "env": "CartPole-v0",
        "logger_config" : {
            "wandb": {
                "project": "test",
                "api_key_file": "./wandb_api_key_file",
            }
        }
    },
    stop={
        "training_iteration":1
    },
    loggers=DEFAULT_LOGGERS + (WandbLogger, )
)
```

We'll make sure to add documentation for this integration soon.

**Comment by krfricke** [comment]
Addendum: It is actually documented [here in the latest master docs](https://docs.ray.io/en/master/tune/tutorials/tune-wandb.html). You'll have to install [Ray nightly](https://docs.ray.io/en/latest/installation.html#latest-snapshots-nightlies) to make it work.

Let me know if you have further questions.

**Comment by janblumenkamp** [comment]
Ah, thanks a lot, I overlooked it in the master docs!

**Comment by hnekoeiq** [comment]
Hi @krfricke, 

I followed your instruction (https://github.com/ray-project/ray/issues/10338#issuecomment-680999888) to wrap the wandb config in a logger_config key and now I get this: 

```
til.py", line 181, in deep_update
    raise Exception("Unknown config parameter `{}` ".format(k))
Exception: Unknown config parameter `logger_config`

```
What I'm missing?

**Comment by krfricke** [comment]
Hi @hnekoeiq 

the example above does work for me - which version are you on?

Anyway, in the latest master we refactored the loggers. You can now pass fully configured callbacks to `tune.run()`;

[Here are the docs for the wandb logger.](https://docs.ray.io/en/master/tune/api_docs/integration.html#weights-and-biases-tune-integration-wandb):

```
from ray.tune.integration.wandb import WandbLoggerCallback

tune.run(
    PPOTrainer,
    checkpoint_freq=1,
    config={
        "framework": "torch",
        "num_workers": 8,
        "num_gpus": 1,
        "env": "CartPole-v0"
    },
    stop={
        "training_iteration":1
    },
    callbacks=[WandbLoggerCallback(project="test", api_key_file="~/.wandb_api+key")]
)

```

Please notice that this only works on the current master (or the nightly wheels) but not in the latest release. It will be included in the next release (1.2.0).

**Comment by drozzy** [comment]
Just spend 30 mins on this too before I found this issue. Would be nice to put something in the docs saying this doesn't work right now...
Any eta on when 1.2.0 comes?

**Comment by dHonerkamp** [comment]
Unfortunately the above does not seem to allow me to use the wandb_mixin approach:
- If I specify a 'wandb' key I receive the above described error of `Unknown config parameter`.
- If I wrap it into `logger_config`, i.e.
```
        "logger_config" : {
            "wandb": {
                "project": "test",
                "api_key_file": "./wandb_api_key_file",
            }
        }
```
 this does not happen, but the mixin then fails as follows:
```
Traceback (most recent call last):
  File "/home/daniel/anaconda3/envs/modulation_rl/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 697, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/daniel/anaconda3/envs/modulation_rl/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 678, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/daniel/anaconda3/envs/modulation_rl/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/daniel/anaconda3/envs/modulation_rl/lib/python3.7/site-packages/ray/worker.py", line 1428, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::ImplicitFunc.train_buffered() (pid=8723, ip=192.168.1.122)
  File "/home/daniel/anaconda3/envs/modulation_rl/lib/python3.7/site-packages/ray/tune/integration/wandb.py", line 516, in __init__
    wandb_config = _config.pop("wandb").copy()
KeyError: 'wandb'
During handling of the above exception, another exception occurred:
ray::ImplicitFunc.train_buffered() (pid=8723, ip=192.168.1.122)
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 487, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 497, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 444, in ray._raylet.execute_task.function_executor
  File "/home/daniel/anaconda3/envs/modulation_rl/lib/python3.7/site-packages/ray/tune/integration/wandb.py", line 519, in __init__
    "Wandb mixin specified but no configuration has been passed. "
ValueError: Wandb mixin specified but no configuration has been passed. Make sure to include a `wandb` key in your `config` dict containing at least a `project` specification.
``` 

I am using a nightly build from last week: `Version: 2.0.0.dev0`.

Is there a way to get around this to get the mixin to work?

**Comment by matteobettini** [comment]
I have the same issue.At the current state wandb mixin integration is not working. 

The documentation at:
- https://docs.wandb.ai/guides/integrations/other/ray-tune
- https://docs.ray.io/en/latest/tune/examples/tune-wandb.html#ray.tune.integration.wandb.wandb_mixin

Are both wrong. The "wandb" config parameter for the trainer is even rejected as unknown, but even after  removing this check, the mixin does not work.
