### ISSUE TITLE
[autoscaler] resource_load_by_shape error

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#10383]
### What is the problem?

I didn't do anything special; just started ray on a 2 node cluster.

Saw this log in my logs:

```
Error in monitor loop
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 313, in run
    self._run()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 271, in _run
    self.process_messages()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 222, in process_messages
    message_handler(channel, data)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 133, in xray_heartbeat_batch_handler
    self.parse_resource_demands(message.resource_load_by_shape)
TypeError: cannot unpack non-iterable NoneType object
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 920, in custom_excepthook
    worker_id = global_worker.worker_id
AttributeError: 'Worker' object has no attribute 'worker_id'

Original exception was:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 368, in <module>
    monitor.run()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 313, in run
    self._run()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 271, in _run
    self.process_messages()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 222, in process_messages
    message_handler(channel, data)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 133, in xray_heartbeat_batch_handler
    self.parse_resource_demands(message.resource_load_by_shape)
TypeError: cannot unpack non-iterable NoneType object
```

cc @ray-project/ray-core

**Comment by ericl** [comment]
@wuisawesome is this fixed with your latest patch?

**Comment by wuisawesome** [comment]
yeah it should be @richardliaw is it still failing for you?

**Comment by richardliaw** [comment]
Well, I'm just using the latest wheel. The wheel is probably just yet to update.
