### ISSUE TITLE
[autoscaler] Monitor.py may have typing/failure handling issue

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#10424]
### What is the problem?

I was unable to repro this issue but I saw this stacktrace in my error logs:

```

==> /tmp/ray/session_2020-08-30_00-44-37_852643_74182/logs/monitor.err <==
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0830 00:44:39.043476 74935 74935 global_state_accessor.cc:25] Redis server address = 172.31.16.95:39317, is test flag = 0
I0830 00:44:39.045035 74935 74935 redis_client.cc:146] RedisClient connected.
I0830 00:44:39.067162 74935 74935 redis_gcs_client.cc:84] RedisGcsClient Connected.
I0830 00:44:39.068747 74935 74935 service_based_gcs_client.cc:195] Reconnected to GCS server: 172.31.16.95:34237
I0830 00:44:39.069160 74935 74935 service_based_accessor.cc:92] Reestablishing subscription for job info.
I0830 00:44:39.069180 74935 74935 service_based_accessor.cc:422] Reestablishing subscription for actor info.
I0830 00:44:39.069190 74935 74935 service_based_accessor.cc:808] Reestablishing subscription for node info.
I0830 00:44:39.069205 74935 74935 service_based_accessor.cc:1084] Reestablishing subscription for task info.
I0830 00:44:39.069214 74935 74935 service_based_accessor.cc:1259] Reestablishing subscription for object locations.
I0830 00:44:39.069224 74935 74935 service_based_accessor.cc:1370] Reestablishing subscription for worker failures.
I0830 00:44:39.069245 74935 74935 service_based_gcs_client.cc:86] ServiceBasedGcsClient Connected.
Error in monitor loop
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 313, in run
    self._run()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 271, in _run
    self.process_messages()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 222, in process_messages
    message_handler(channel, data)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 133, in xray_heartbeat_batch_handler
    self.parse_resource_demands(message.resource_load_by_shape)
TypeError: cannot unpack non-iterable NoneType object
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 921, in custom_excepthook
    worker_id = global_worker.worker_id
AttributeError: 'Worker' object has no attribute 'worker_id'

Original exception was:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 368, in <module>
    monitor.run()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 313, in run
    self._run()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 271, in _run
    self.process_messages()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 222, in process_messages
    message_handler(channel, data)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 133, in xray_heartbeat_batch_handler
    self.parse_resource_demands(message.resource_load_by_shape)
TypeError: cannot unpack non-iterable NoneType object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 380, in <module>
    redis_client, ray_constants.MONITOR_DIED_ERROR, message)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/utils.py", line 121, in push_error_to_driver_through_redis
    pubsub_msg.id = job_id.hex()
TypeError: 'ffff' has type str, but expected one of: bytes
```

**Comment by rkooo567** [comment]
cc @wuisawesome

**Comment by wuisawesome** [comment]
I think this was #10380. Can you reopen this if you were able to reproduce it with a newer wheel than that commit?
