### ISSUE TITLE
--system-config option to ray start doesn't work

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#10515]
### What is the problem?

Passing a valid json dict to --system-config threw the following error because we json.loads'ed it twice:

```
code/ray % ray start --head --system-config="{\"1\": \"2\"}"                                                   
Traceback (most recent call last):                                                                             
  File "/Users/eoakes/anaconda3/bin/ray", line 11, in <module>                                                 
    load_entry_point('ray', 'console_scripts', 'ray')()                                                        
  File "/Users/eoakes/code/ray/python/ray/scripts/scripts.py", line 1599, in main                              
    return cli()                                                                                               
  File "/Users/eoakes/anaconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__              
    return self.main(*args, **kwargs)                                                                          
  File "/Users/eoakes/anaconda3/lib/python3.6/site-packages/click/core.py", line 717, in main                  
    rv = self.invoke(ctx)                                                                                      
  File "/Users/eoakes/anaconda3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke               
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                    
  File "/Users/eoakes/anaconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke                
    return ctx.invoke(self.callback, **ctx.params)                                                             
  File "/Users/eoakes/anaconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke                
    return callback(*args, **kwargs)                                                                           
  File "/Users/eoakes/code/ray/python/ray/scripts/scripts.py", line 510, in start
    if system_config else system_config,
  File "/Users/eoakes/anaconda3/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by edoakes** [comment]
P0 for 1.0 release.
