### ISSUE TITLE
[rllib] Non-RNN inputs into attention_net(RecurrentNetwork) gets 'seq_lens': np.ndarray((1,), where can I specify seq_lens?

### ISSUE THREAD

**Issue by forhonourlx** [ray-project/ray#10532]
Hi Ray Team,

I am trying to insert some Non-RNN inputs and conv layers before fc layers to join attention_net(RecurrentNetwork).
In debug mode, I only get a batchsize of 1 state, and seq_lens of np.ndarray((1,), 
Could someone kindly tell me where to specify seq_lens?
Thanks in advance.
```
  'initial_states': [ np.ndarray((1, 192, 416), dtype=float32, min=0.0, max=0.0, mean=0.0),
                      np.ndarray((1, 192, 120), dtype=float32, min=0.0, max=0.0, mean=0.0),
                      np.ndarray((1, 192, 120), dtype=float32, min=0.0, max=0.0, mean=0.0)],
  'max_seq_len': 192,
  'seq_lens': np.ndarray((1,), dtype=int32, min=125.0, max=125.0, mean=125.0)}
```
And attention_net example get:
```
  'initial_states': [ np.ndarray((100, 50, 2), dtype=float32, min=0.0, max=1.0, mean=0.238),
                      np.ndarray((100, 50, 64), dtype=float32, min=-0.294, max=0.297, mean=-0.009)],
  'max_seq_len': 50,
  'seq_lens': np.ndarray((100,), dtype=int32, min=2.0, max=50.0, mean=40.0)}
```

```
class TestGTrXLNetwork(RecurrentNetwork):
    def __init__(self,):
        
        ......

    @override(RecurrentNetwork)
    def forward(self, input_dict, state, seq_lens):
        assert seq_lens is not None
        logits, new_state = self.forward_rnn(input_dict, state, seq_lens)
        return tf.reshape(logits, [-1, self.num_outputs]), new_state

    @override(RecurrentNetwork)
    def forward_rnn(self, input_dict, state, seq_lens):
        input_list = self.input_dict_to_list(input_dict)
        hist_tr_inputs = state[0]
        memory = state[1:]

        all_out = self.trxl_model([hist_tr_inputs] + input_list + memory)##
        logits, self._value_out = all_out[0], all_out[1]
        new_tr_inputs = all_out[2]##
        curr_tr_input = all_out[3]##
        memory_outs = all_out[4:]

        # If memory_tau > max_seq_len -> overlap w/ previous `memory` input.
        if self.memory_tau > self.max_seq_len:
            memory_outs = [tf.concat([memory[i][:, -(self.memory_tau - self.max_seq_len):], m], axis=1) 
                for i, m in enumerate(memory_outs)]
        else:
            memory_outs = [m[:, -self.memory_tau:] for m in memory_outs]
        
        T = tf.shape(add_time_dimension(curr_tr_input, seq_lens, framework="tf"))[1]
        logits = logits[:, -T:]
        self._value_out = self._value_out[:, -T:]

        return logits, [new_tr_inputs] + memory_outs
```

**Comment by forhonourlx** [comment]
Sorry to bother you @ericl @sven1977 ...
Thank you very much!

**Comment by lyzyn** [comment]
Hello, when customizing LSTM in RAY, everything was fine during the training phase, but the same seq occurred during the predict phase_ Len problem, I don't know how to define it. Here is my error message. Have you resolved it? Thank you! Looking forward to your reply!
**Traceback (most recent call last):
  File "C:\Users\zyn\Desktop\agent_three\examples\marl\rllib\heterogeneous\load_and_predict.py", line 178, in <module>
    action_step[iter_pred][agent_id] = predictor.compute_single_action(agent_obs, policy_id=policy_id,full_fetch=True)
  File "C:\Users\zyn\anaconda3\envs\PGW_RAY2\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\zyn\anaconda3\envs\PGW_RAY2\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 1595, in compute_single_action
    action, state, extra = policy.compute_single_action(
  File "C:\Users\zyn\anaconda3\envs\PGW_RAY2\lib\site-packages\ray\rllib\policy\policy.py", line 545, in compute_single_action
    out = self.compute_actions_from_input_dict(
  File "C:\Users\zyn\anaconda3\envs\PGW_RAY2\lib\site-packages\ray\rllib\policy\torch_policy_v2.py", line 522, in compute_actions_from_input_dict
    return self._compute_action_helper(
  File "C:\Users\zyn\anaconda3\envs\PGW_RAY2\lib\site-packages\ray\rllib\utils\threading.py", line 24, in wrapper
    return func(self, *a, **k)
  File "C:\Users\zyn\anaconda3\envs\PGW_RAY2\lib\site-packages\ray\rllib\policy\torch_policy_v2.py", line 1141, in _compute_action_helper
    dist_inputs, state_out = self.model(input_dict, state_batches, seq_lens)
  File "C:\Users\zyn\anaconda3\envs\PGW_RAY2\lib\site-packages\ray\rllib\models\modelv2.py", line 259, in __call__
    res = self.forward(restored, state or [], seq_lens)
  File "C:\Users\zyn\anaconda3\envs\PGW_RAY2\lib\site-packages\ray\rllib\models\torch\recurrent_net.py", line 207, in forward
    assert seq_lens is not None**

**Comment by lyzyn** [comment]
Hello, when customizing LSTM in RAY, everything was fine during the training phase, but the same seq occurred during the predict phase_ Len problem, I don't know how to define it. Here is my error message. Have you resolved it? Thank you! Looking forward to your reply!
```
Traceback (most recent call last):
  File "C:\Users\zyn\Desktop\agent_three\examples\marl\rllib\heterogeneous\load_and_predict.py", line 178, in <module>
    action_step[iter_pred][agent_id] = predictor.compute_single_action(agent_obs, policy_id=policy_id,full_fetch=True)
  File "C:\Users\zyn\anaconda3\envs\PGW_RAY2\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\zyn\anaconda3\envs\PGW_RAY2\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 1595, in compute_single_action
    action, state, extra = policy.compute_single_action(
  File "C:\Users\zyn\anaconda3\envs\PGW_RAY2\lib\site-packages\ray\rllib\policy\policy.py", line 545, in compute_single_action
    out = self.compute_actions_from_input_dict(
  File "C:\Users\zyn\anaconda3\envs\PGW_RAY2\lib\site-packages\ray\rllib\policy\torch_policy_v2.py", line 522, in compute_actions_from_input_dict
    return self._compute_action_helper(
  File "C:\Users\zyn\anaconda3\envs\PGW_RAY2\lib\site-packages\ray\rllib\utils\threading.py", line 24, in wrapper
    return func(self, *a, **k)
  File "C:\Users\zyn\anaconda3\envs\PGW_RAY2\lib\site-packages\ray\rllib\policy\torch_policy_v2.py", line 1141, in _compute_action_helper
    dist_inputs, state_out = self.model(input_dict, state_batches, seq_lens)
  File "C:\Users\zyn\anaconda3\envs\PGW_RAY2\lib\site-packages\ray\rllib\models\modelv2.py", line 259, in __call__
    res = self.forward(restored, state or [], seq_lens)
  File "C:\Users\zyn\anaconda3\envs\PGW_RAY2\lib\site-packages\ray\rllib\models\torch\recurrent_net.py", line 207, in forward
    assert seq_lens is not None
```
