### ISSUE TITLE
ray.init() throws List Index Out of Range error

### ISSUE THREAD

**Issue by gokhanceyhan** [ray-project/ray#10565]
### What is your question?

*Ray version and other system information (Python version, TensorFlow version, OS):*
I am using version 0.8.6. with Python 3.7.5 on rhel07 machine. The error occurs in the connect function in `worker.py` when ray.init() was run. I was able to trace the error and it occurs in the below part.
```
if mode == SCRIPT_MODE:
        # Add the directory containing the script that is running to the Python
        # paths of the workers. Also add the current directory. Note that this
        # assumes that the directory structures on the machines in the clusters
        # are the same.
        script_directory = os.path.abspath(os.path.dirname(sys.argv[0]))
        current_directory = os.path.abspath(os.path.curdir)
        worker.run_function_on_all_workers(
            lambda worker_info: sys.path.insert(1, script_directory))
        worker.run_function_on_all_workers(
            lambda worker_info: sys.path.insert(1, current_directory))
        # TODO(rkn): Here we first export functions to run, then remote
        # functions. The order matters. For example, one of the functions to
        # run may set the Python path, which is needed to import a module used
        # to define a remote function. We may want to change the order to
        # simply be the order in which the exports were defined on the driver.
        # In addition, we will need to retain the ability to decide what the
        # first few exports are (mostly to set the Python path). Additionally,
        # note that the first exports to be defined on the driver will be the
        # ones defined in separate modules that are imported by the driver.
        # Export cached functions_to_run.
        for function in worker.cached_functions_to_run:
            worker.run_function_on_all_workers(function)
    worker.cached_functions_to_run = None
```
Line `script_directory = os.path.abspath(os.path.dirname(sys.argv[0]))` assumes that `sys.argv` has to be non-empty, but in my case it is empty. I disabled copying the `script_directory` to workers and it seemed to be working just fine. What should be the correct way to proceed?

Unfortunately, I am not able to provide you a script to reproduce the issue since I am running ray inside our in-house stream-processing infrastructure.

**Comment by richardliaw** [comment]
Can you provide a full stacktrace?

**Comment by gokhanceyhan** [comment]
Here you are:
```
2020-09-07 09:06:36,059	INFO resource_spec.py:212 -- Starting Ray with 4.15 GiB memory available for workers and up to 2.08 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-09-07 09:06:36,166	WARNING services.py:923 -- Redis failed to start, retrying now.
2020-09-07 09:06:36,393	WARNING services.py:923 -- Redis failed to start, retrying now.
2020-09-07 09:06:36,585	INFO services.py:1165 -- View the Ray dashboard at localhost:8265
09-07 09:06:37.693760|0x00007fa018aee700|error|PyUtilities.cpp:104|Traceback (most recent call last):
  File "/home/gceyhan/work/stash/uaw/src/python/src/unscrambl/oxygen/composer/base.py", line 901, in _instantiate_and_set_up_operator
    oper.set_up()
  File "/home/gceyhan/work/stash/uaw/src/python/src/unscrambl/foresee/analytics/next_best_offer/operators.py", line 40, in set_up
    ray.init()
  File "/home/gceyhan/unscrambl/drive/2.2.0/ub18/build/pyenv-3.7.5/lib/python3.7/site-packages/ray/worker.py", line 793, in init
    job_id=job_id)
  File "/home/gceyhan/unscrambl/drive/2.2.0/ub18/build/pyenv-3.7.5/lib/python3.7/site-packages/ray/worker.py", line 1275, in connect
    script_directory = os.path.abspath(os.path.dirname(sys.argv[0]))
IndexError: list index out of range

occurred at:
	At /home/gceyhan/work/stash/uaw/src/cxx/src/oxygen/PyUtilities.cpp:101
	In /home/gceyhan/work/stash/uaw/bld/ub18/install/acme/drive/lib/libunscrambl_oxygen.so[0x7fa01bbc8b9d] unscrambl::oxygen::extractAndLogPyException[abi:cxx11]()
	At /home/gceyhan/work/stash/uaw/src/cxx/src/oxygen/EmbeddedPythonInterpreter.cpp:538
	In /home/gceyhan/work/stash/uaw/bld/ub18/install/acme/drive/lib/libunscrambl_oxygen.so[0x7fa01b9cb737] unscrambl::oxygen::EmbeddedPythonInterpreter::processReturnResult(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unscrambl::oxygen::PyObjectHandle const&, boost::variant<boost::blank, bool, double, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, _object*>&)
	At /home/gceyhan/work/stash/uaw/src/cxx/include/unscrambl/oxygen/EmbeddedPythonInterpreter.h:209
```

**Comment by rkooo567** [comment]
Can you elaborate why `sys.argv` has to be empty in your case?

**Comment by gokhanceyhan** [comment]
I believe the reason is that the method that runs the Python script triggering ray is Python code embedded in C++ code.

**Comment by wuisawesome** [comment]
> the method that runs the Python script triggering ray is Python code embedded in C++ code.

Can you elaborate on what this means? Are you using `#include <Python.h>`?

**Comment by gokhanceyhan** [comment]
Yes, we are using `#include <Python.h>`.

**Comment by rkooo567** [comment]
Which method are you using to trigger ray? Also I think this is not a common scenario for using ray, so I am not sure what’s the best solution. Your solutions seem to be fine if it works.

**Comment by gokhanceyhan** [comment]
I initialize as follows: 
```sys.argv.append("")

        try:
            # initialize ray
            ray.init(
                memory=gigabytes_to_bytes(memory_limit_in_gigabytes),
                object_store_memory=gigabytes_to_bytes(object_store_memory_limit_in_gigabytes),
                include_webui=False)
        except BaseException as e:
            raise RuntimeError(f"could not initialize 'ray', details: {str(e)}")```

So, I append an empty string to `sys.argv` to prevent the error.
