### ISSUE TITLE
Metric agent fails in certain condition

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#10634]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

The report logs output the following and prometheus endpoint return 500
```
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/root/anaconda3/lib/python3.7/site-packages/prometheus_client/exposition.py", line 52, in prometheus_app
    status, header, output = _bake_output(registry, accept_header, params)
  File "/root/anaconda3/lib/python3.7/site-packages/prometheus_client/exposition.py", line 40, in _bake_output
    output = encoder(registry)
  File "/root/anaconda3/lib/python3.7/site-packages/prometheus_client/openmetrics/exposition.py", line 14, in generate_latest
    for metric in registry.collect():
  File "/root/anaconda3/lib/python3.7/site-packages/prometheus_client/registry.py", line 82, in collect
    for metric in collector.collect():
  File "/root/anaconda3/lib/python3.7/site-packages/ray/prometheus_exporter.py", line 234, in collect
    metric = self.to_metric(desc, tag_values, agg_data)
  File "/root/anaconda3/lib/python3.7/site-packages/ray/prometheus_exporter.py", line 159, in to_metric
    assert (len(tag_values) == len(label_keys))
AssertionError
```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

I didn't get to find the exactly reproducible case but it involves adding and removing serve cluster, and adding and killing named actors, all attached to existing Ray cluster. I will spend more time to figure it out

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by simon-mo** [comment]
cc @rkooo567

**Comment by rkooo567** [comment]
@yiranwang52 also reported this bug.
