### ISSUE TITLE
[rllib] WandbLogger gives pickle error with custom policy

### ISSUE THREAD

**Issue by 0luhancheng0** [ray-project/ray#10631]
### What is the problem?

WandbLogger seems to cause unpickle error with custom policy is created using policy template

sys info:
* Ray: 0.9.0.dev0
* python: 3.7.6
* tf: 2.3.0
* os: macos

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)

```python
        from ray.tune.logger import DEFAULT_LOGGERS
        from ray.tune.integration.wandb import WandbLogger
        from ray.rllib.agents.trainer_template import build_trainer
        from ray.rllib.policy.tf_policy_template import build_tf_policy
        from ray.rllib.agents.pg import pg_tf_loss
        from ray.rllib.agents.pg.pg_tf_policy import pg_tf_loss, post_process_advantages
        from gym.spaces import Discrete
        from ray import tune
        from ray.rllib.examples.env.rock_paper_scissors import RockPaperScissors
        # import gym
        loss_fn = pg_tf_loss
        from ray.tune import register_env
        register_env('RPC', lambda config : RockPaperScissors(config))
        class policy_selection:
            def __init__(self):
                pass
            def __call__(self, agent_id):
                if agent_id == "player1":
                    return "learned1"
                else:
                    return "learned2"
            def __str__(self):
                return 'policy selection'
        pg = build_trainer('another_pg', default_policy=build_tf_policy('another_pg_policy', loss_fn=loss_fn, postprocess_fn=post_process_advantages))
        config = {
            'env': 'RPC',
            'logger_config': {
                'wandb': {
                    "project": "honours-project",
                    "api_key_file": "~/.wandb_api_key",
                    "log_config": True,
                    'sync_tensorboard': True,
                }
            },
            'multiagent': {
                "policies_to_train": ["learned1", "learned2"],
                "policies": {
                    "learned1": (None, Discrete(3), Discrete(3), {}),
                    "learned2": (None, Discrete(3), Discrete(3), {}),
                },
                "policy_mapping_fn": policy_selection(),
            },
        }
        tune.run(pg, config=config, loggers=DEFAULT_LOGGERS + (WandbLogger, ))
```

- [ x ] I have verified my script runs in a clean environment and reproduces the issue.
- [  ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
This should be closed by #10654. @0luhancheng0 can you try master and let me know if this works?

**Comment by richardliaw** [comment]
(Feel free to reopen if not).

**Comment by 0luhancheng0** [comment]
@richardliaw  

the error seems to persist with your pull request.

running with the example above gives 
```
Traceback (most recent call last):
  File "/Users/ChengLuhan/anaconda3/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/Users/ChengLuhan/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'ray.rllib.policy.tf_policy_template.another_pg_policy'>: attribute lookup another_pg_policy on ray.rllib.policy.tf_policy_template failed
```

**Comment by richardliaw** [comment]
Hmm, are you sure you updated Ray correctly? 

I ran the Ray example you posted exactly and was able to run it successfully after the changes.

**Comment by 0luhancheng0** [comment]
Hi richard, i reinstalled the latest wheel and it works! Looks like there was an issue with my previous update. Thank you very much!
