### ISSUE TITLE
A lot of Ray commands fail in nightly build

### ISSUE THREAD

**Issue by suquark** [ray-project/ray#10668]
### What is the problem?

This is because they keep passing the deleted `redis_password` keyword.

For example, 

```
$ ray memory
2020-09-09 05:24:50,248 INFO scripts.py:1474 -- Connecting to Ray instance at 172.31.56.46:6379.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/scripts/scripts.py", line 1602, in main
    return cli()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/scripts/scripts.py", line 1475, in memory
    ray.init(address=address, redis_password=redis_password)
TypeError: init() got an unexpected keyword argument 'redis_password'
```

Also I feel confused about many prompts and docs still mentioning `redis_password` while it no longer exists in `ray.init`

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by wuisawesome** [comment]
Thanks for the heads up!
