### ISSUE TITLE
RLlib AirSim support?

### ISSUE THREAD

**Issue by elgalu** [ray-project/ray#10676]
Is it also possible to use https://github.com/microsoft/AirSim with RLlib? (in addition to OpenAI/Gym or CARLA)

**Comment by sven1977** [comment]
Unfortunately, we have not integrated with UE4 so far (but are considering it). We do have a Unity3D adapter, an example usage of which you can find here: https://github.com/ray-project/ray/blob/master/rllib/examples/unity3d_env_local.py

**Comment by alexvaca0** [comment]
Hi, I'd also like ray to support AirSim, as I'm trying to teach drones how to fly with it, but can only use stable_baselines3 for the moment, as ray, which has better algorithmic support, doesn't work correctly, my error message is:

```
Traceback (most recent call last):
  File "/home/alejandro.vaca/miniconda/envs/petra_drones_p36/lib/python3.6/site-packages/ray/serialization.py", line 254, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/alejandro.vaca/miniconda/envs/petra_drones_p36/lib/python3.6/site-packages/ray/serialization.py", line 219, in _deserialize_object
    data, metadata_fields)
  File "/home/alejandro.vaca/miniconda/envs/petra_drones_p36/lib/python3.6/site-packages/ray/serialization.py", line 180, in _deserialize_msgpack_data
    raise DeserializationError()
ray.serialization.DeserializationError
(pid=8881) 2021-09-06 15:07:22,250	ERROR serialization.py:256 -- 
(pid=8881) Traceback (most recent call last):
(pid=8881)   File "/home/alejandro.vaca/miniconda/envs/petra_drones_p36/lib/python3.6/site-packages/ray/serialization.py", line 178, in _deserialize_msgpack_data
(pid=8881)     _python_deserializer)
(pid=8881)   File "python/ray/includes/serialization.pxi", line 179, in ray._raylet.MessagePackSerializer.loads
(pid=8881)   File "msgpack/_unpacker.pyx", line 161, in msgpack._unpacker.unpackb
(pid=8881) TypeError: unpackb() got an unexpected keyword argument 'strict_map_key'
(pid=8881) 
(pid=8881) During handling of the above exception, another exception occurred:
(pid=8881) 
(pid=8881) Traceback (most recent call last):
(pid=8881)   File "/home/alejandro.vaca/miniconda/envs/petra_drones_p36/lib/python3.6/site-packages/ray/serialization.py", line 254, in deserialize_objects
(pid=8881)     obj = self._deserialize_object(data, metadata, object_ref)
(pid=8881)   File "/home/alejandro.vaca/miniconda/envs/petra_drones_p36/lib/python3.6/site-packages/ray/serialization.py", line 190, in _deserialize_object
(pid=8881)     return self._deserialize_msgpack_data(data, metadata_fields)
(pid=8881)   File "/home/alejandro.vaca/miniconda/envs/petra_drones_p36/lib/python3.6/site-packages/ray/serialization.py", line 180, in _deserialize_msgpack_data
(pid=8881)     raise DeserializationError()
(pid=8881) ray.serialization.DeserializationError
(pid=8881) 2021-09-06 15:07:22,251	ERROR serialization.py:256 -- 
(pid=8881) Traceback (most recent call last):
(pid=8881)   File "/home/alejandro.vaca/miniconda/envs/petra_drones_p36/lib/python3.6/site-packages/ray/serialization.py", line 178, in _deserialize_msgpack_data
(pid=8881)     _python_deserializer)
(pid=8881)   File "python/ray/includes/serialization.pxi", line 179, in ray._raylet.MessagePackSerializer.loads
(pid=8881)   File "msgpack/_unpacker.pyx", line 161, in msgpack._unpacker.unpackb
(pid=8881) TypeError: unpackb() got an unexpected keyword argument 'strict_map_key'
(pid=8881) 
(pid=8881) During handling of the above exception, another exception occurred:
(pid=8881) 
(pid=8881) Traceback (most recent call last):
(pid=8881)   File "/home/alejandro.vaca/miniconda/envs/petra_drones_p36/lib/python3.6/site-packages/ray/serialization.py", line 254, in deserialize_objects
(pid=8881)     obj = self._deserialize_object(data, metadata, object_ref)
(pid=8881)   File "/home/alejandro.vaca/miniconda/envs/petra_drones_p36/lib/python3.6/site-packages/ray/serialization.py", line 190, in _deserialize_object
(pid=8881)     return self._deserialize_msgpack_data(data, metadata_fields)
(pid=8881)   File "/home/alejandro.vaca/miniconda/envs/petra_drones_p36/lib/python3.6/site-packages/ray/serialization.py", line 180, in _deserialize_msgpack_data
(pid=8881)     raise DeserializationError()
(pid=8881) ray.serialization.DeserializationError
```

**Comment by chenfei8888** [comment]
Is there any news about the RLlib AirSim integration ?
