### ISSUE TITLE
Allow Redis shards to be started on all nodes in the cluster.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1069]
Currently all of the Redis shards are started on the "head node". However, the non-primary Redis shards could live anywhere. Scattering them around can help with balancing network traffic.

See https://github.com/ray-project/ray/compare/master...robertnishihara:startredisshardsremotely for an example implementation.

**Comment by arank** [comment]
Hey @robertnishihara . Merging this example onto the current version of Ray doesn't seem to work very well. Would you happen to know what additional steps would be needed to make sharding Redis across nodes in a cluster work in Ray-0.4.0? Thanks!

**Comment by robertnishihara** [comment]
I suspect that the branch you're linking to just needs to be rebased on the current master.

Is this important for some use case that you're working on (if so what is the scenario)? I've needed to do this in the past to increase network throughput to the Redis shards, but it has rarely been needed.

**Comment by arank** [comment]
Thanks for the quick response! I will definitely try to rebase and attempt the merge of this branch again.

For context: I have had long running, memory intensive jobs that have been failing with errors that indicate a problem with network pressure on the redis server. For example:

INFO:root:Driver 96d4e1f4f28df75955e8fe66fbc673ab40b6adf9 has been removed.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ray/monitor.py", line 597, in <module>
    monitor.run()
  File "/usr/local/lib/python2.7/dist-packages/ray/monitor.py", line 534, in run
    self.process_messages()
  File "/usr/local/lib/python2.7/dist-packages/ray/monitor.py", line 480, in process_messages
    message_handler(channel, data)
  File "/usr/local/lib/python2.7/dist-packages/ray/monitor.py", line 431, in driver_removed_handler
    self._clean_up_entries_for_driver(driver_id)
  File "/usr/local/lib/python2.7/dist-packages/ray/monitor.py", line 390, in _clean_up_entries_for_driver
    self._entries_for_driver_in_shard(driver_id, shard_index)
  File "/usr/local/lib/python2.7/dist-packages/ray/monitor.py", line 313, in _entries_for_driver_in_shard
    entry = redis.hgetall(key)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1967, in hgetall
    return self.execute_command('HGETALL', name)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 674, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 284, in read_response
    response = self._buffer.readline()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 216, in readline
    self._read_from_socket()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 191, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')

My assumption from what I have read is that this is likely to be alleviated by sharding though this could also be caused by another issue, with a simpler fix (I would appreciate any guidance you could give here). Thanks again!

**Comment by robertnishihara** [comment]
It could also be an out-of-memory error killing the Redis server (in which case there are workarounds).

Can you also check the logs under `/tmp/raylogs/` (e.g., on the head machine) to see if there is any information about why the redis servers died? Sometimes there are messages about "dropping subscribers/clients for overcoming output buffer limits".

Also, could you monitor `top` and see if any process is using too much memory as the application progresses?
