### ISSUE TITLE
Worker crached with traces sometimes but i don't how to fix it

### ISSUE THREAD

**Issue by schukerzheng** [ray-project/ray#10708]
I'm using pytest and ray framework to test something. 
test code:
```
# conftest.py
import pytest
import ray

@pytest.fixture(scope="module")
def ray_fix():
    ray.init(
        address='auto', 
        log_to_driver=False,
        redirect_output=False,
    )
    yield 
    ray.shutdown() 

# test_script.py
import logging
import sys
from logging.handlers import SocketHandler
import ray

class Logger():
    
    def __init__(self):
        self.logger = RemoteLogger.remote()
        
    def error(self, msg):
        self.logger.error.remote(msg)

@ray.remote(resources={'logger': 1})
class RemoteLogger:
    
    def __init__(self):
        self.logger = logging.getLogger()
    
    def error(self, msg):
        self.logger.error(msg)
        
        
@ray.remote(resources={'mixer': 1})
def rm_func():
    logger = RemoteLogger.remote()
    logger.error.remote('=====test in rm func')
    import socket
    return socket.gethostname()

def test_rm_func(ray_fix, caplog):
    logger = RemoteLogger.remote()
    logger.error.remote('start test')
    f = rm_func.remote()
    r = ray.get(f)
    logger.error.remote(r)
    logger.error.remote('finish test')
```
resources mixer and logger are customal resources, which are defined on different host,  the available resources count are both 1.
When I ran the pytest command, such as `pytest test_script.py`,  on 'logger' host,  sometimes works are nomal, but logs won't be show on terminal. Sometimes workers will crashed with traces below and ray processes  are gone:
2020-09-10 14:25:49,606 ERROR worker.py:371 -- SystemExit was raised from the worker
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 547, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 361, in ray._raylet.execute_task
  File "/data/home/username/.cache/pypoetry/virtualenvs/ray-test-RMrG2Ngp-py3.6/lib/python3.6/site-packages/ray/worker.py", line 375, in get_gpu_ids
    def get_gpu_ids():
  File "/data/home/username/.cache/pypoetry/virtualenvs/ray-test-RMrG2Ngp-py3.6/lib/python3.6/site-packages/ray/worker.py", line 368, in sigterm_handler
    sys.exit(1)
SystemExit: 1

**Comment by richardliaw** [comment]
What version of Ray are you using? If you're on master, could you try running `pytest test_script.py -s`?

**Comment by schukerzheng** [comment]
ray version is: 0.8.7
I think some bugs cause task not executing correctly, so logs can't be shown on termial.
I've tried several times, another trace below is shown in "logger" worker logs file:
```
2020-09-10 17:31:24,810 ERROR worker.py:371 -- SystemExit was raised from the worker
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 547, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 434, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 474, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 478, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 479, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/data/home/airbozheng/.cache/pypoetry/virtualenvs/distributed-testing-lPmAUf-2-py3.6/lib/python3.6/site-packages/ray/function_manager.py", line 574, in actor_method_executor
    if isinstance(actor, ray.actor.Checkpointable):
  File "/data/home/username/.pyenv/versions/3.6.5/lib/python3.6/abc.py", line 193, in __instancecheck__
    return cls.__subclasscheck__(subclass)
  File "/data/home/username/.pyenv/versions/3.6.5/lib/python3.6/abc.py", line 210, in __subclasscheck__
    if ok is not NotImplemented:
  File "/data/home/username/.cache/pypoetry/virtualenvs/distributed-testing-lPmAUf-2-py3.6/lib/python3.6/site-packages/ray/worker.py", line 368, in sigterm_handler
    sys.exit(1)
SystemExit: 1
```

**Comment by schukerzheng** [comment]
pytest -s console output:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0910 17:33:39.890420 12153 12153 global_state_accessor.cc:25] Redis server address = 9.134.7.112:34567, is test flag = 0
I0910 17:33:39.892351 12153 12153 redis_client.cc:146] RedisClient connected.
I0910 17:33:39.901245 12153 12153 redis_gcs_client.cc:89] RedisGcsClient Connected.
I0910 17:33:39.903204 12153 12153 service_based_gcs_client.cc:193] Reconnected to GCS server: 9.134.7.112:57713
I0910 17:33:39.903645 12153 12153 service_based_accessor.cc:92] Reestablishing subscription for job info.
I0910 17:33:39.903733 12153 12153 service_based_accessor.cc:422] Reestablishing subscription for actor info.
I0910 17:33:39.903793 12153 12153 service_based_accessor.cc:797] Reestablishing subscription for node info.
I0910 17:33:39.903856 12153 12153 service_based_accessor.cc:1073] Reestablishing subscription for task info.
I0910 17:33:39.903913 12153 12153 service_based_accessor.cc:1248] Reestablishing subscription for object locations.
I0910 17:33:39.903981 12153 12153 service_based_accessor.cc:1368] Reestablishing subscription for worker failures.
I0910 17:33:39.904037 12153 12153 service_based_gcs_client.cc:86] ServiceBasedGcsClient Connected.
========================================================================== test session starts ===========================================================================
platform linux -- Python 3.6.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /data/home/username/py3/test_proj/ray_test, configfile: pytest.ini
collected 1 item                                                                                                                                                         

test_remote_log.py::test_rm_func 
----------------------------------------------------------------------------- live log call ------------------------------------------------------------------------------
2020-09-10 17:33:39 [    INFO] start test (test_remote_log.py:47)
2020-09-10 17:33:39 [    INFO] VM_7_112_centos (test_remote_log.py:50)
2020-09-10 17:33:39 [    INFO] finish test (test_remote_log.py:51)
PASSED

=========================================================================== 1 passed in 0.18s ============================================================================
```

**Comment by schukerzheng** [comment]
Finally i found why, thanks a lot.
1. there is a personal proxy between hosts, I turned it off;
2. ray.shutdown() must not be called at pytest_sessionfinish.
