### ISSUE TITLE
[rllib][k8s]: ModuleNotFoundError: No module named 'game' 

### ISSUE THREAD

**Issue by Glaucus-2G** [ray-project/ray#10804]
### **When I run my rode in a ray cluster, it shows ModuleNotFoundError: No module named 'game'**
I have a  game simulator and register it  in gym.  
The evironment's name is "Ucav-v0" and the simple code structure in `/conda/lib/python3.7/site-packages/gym/envs `  is :
> code
>    - integrator
>         - ucav.py    
>    - game
>         - GameManager.py
In ` ucav.py `, it will use some functions in GameManager.py

When I run  `gym_ppo.py` in my computer, it works properly. The  code in `gym_ppo.py` is this:

    import ray
    from ray.rllib.agents.ppo import PPOTrainer
    from ray.tune.registry import register_env
    import gym
    from ray import tune
      
    class MyEnv(gym.Env):
        def __init__(self, env_config):
            self.env = gym.make('Ucav-v0')
            self.action_space = self.env.action_space
            self.observation_space = self.env.observation_space

       def reset(self):
            obs = self.env.reset()
            return obs

       def step(self, action):
            action = self.action_space.sample()
            obs, reward, done, info = self.env.step(action)
            return obs, reward, done, info

    register_env("myenv", lambda config: MyEnv(config))

    def main():
        #ray.init(address="127.0.0.1:6379")    # use this in a ray cluster
        ray.init()
        config = {
            'num_workers': 5,
            'use_pytorch': False,
            # 'num_envs_per_worker': 1,    # use this in a ray cluster
        }
        trainer = PPOTrainer(env="myenv", config=config)

        max_training_episodes = 100000
        for i in range(max_training_episodes):
            print("iteration: " + str(i))
            trainer.train()

        trainer.stop()

    if __name__ == '__main__':
        main()

Now I have a ray cluster which is **deployed in kubernetes.** It has one  ray-head node and five ray-worker nodes.
All nodes use the same image, so whether it's in ray-head node or in ray-worker nodes, I have register my environment.

In my opinion, I only need to modify `ray.init()` to `ray.int("127.0.0.1:6379")` in `gym_ppo.py`, then I can run it properly in the ray cluster. However, it reports the mistake:
```
2020-09-15 11:34:38,333	WARNING worker.py:792 -- When connecting to an existing cluster, _internal_config must match the cluster's _internal_config.
2020-09-15 11:34:38,413	INFO trainer.py:428 -- Tip: set 'eager': true or the --eager flag to enable TensorFlow eager execution
2020-09-15 11:34:38,482	INFO trainer.py:585 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
2020-09-15 11:34:51,706	INFO trainable.py:180 -- _setup took 13.225 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2020-09-15 11:34:51,706	INFO trainable.py:217 -- Getting current IP.
2020-09-15 11:34:51,709	WARNING util.py:37 -- Install gputil for GPU system monitoring.
iteration: 0
Traceback (most recent call last):
  File "gym_ppo.py", line 59, in <module>
    main()
  File "gym_ppo.py", line 54, in main
    trainer.train()
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 502, in train
    raise e
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 491, in train
    result = Trainable.train(self)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 150, in _train
    fetches = self.optimizer.step()
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 139, in step
    self.train_batch_size)
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/optimizers/rollout.py", line 25, in collect_samples
    next_sample = ray_get_and_free(fut_sample)
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/utils/memory.py", line 29, in ray_get_and_free
    result = ray.get(object_ids)
  File "/opt/conda/lib/python3.7/site-packages/ray/worker.py", line 1513, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ModuleNotFoundError): ray::RolloutWorker.__init__() (pid=60, ip=10.11.0.5)
  File "python/ray/_raylet.pyx", line 414, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 414, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 414, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 450, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 287, in __init__
    self.env = _validate_env(env_creator(env_context))
  File "gym_ppo.py", line 28, in <lambda>
    register_env("myenv", lambda config: MyEnv(config))
  File "gym_ppo.py", line 14, in __init__
    self.env = gym.make('Ucav-v0')
  File "/opt/conda/lib/python3.7/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/gym/envs/registration.py", line 59, in make
    cls = load(self.entry_point)
  File "/opt/conda/lib/python3.7/site-packages/gym/envs/registration.py", line 18, in load
    mod = importlib.import_module(mod_name)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.7/site-packages/gym/envs/code/integrator/__init__.py", line 1, in <module>
    from ucav import UcavEnv
  File "/home/code/integrator/ucav.py", line 8, in <module>
    from game.GameManager import GameManager,planeNameMap
ModuleNotFoundError: No module named 'game'
```

I have follow issues but still don't know how to solve it, could you give me some examples.
May I need to use autoscaler to solve it？

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.8.4
Python 3.7.6
Pytorch 1.3.1
TensorFlow: 2.3.0
OS linux

**Comment by sumanthratna** [comment]
hey @Glaucus-2G! can you try adding an empty `__init__.py` file to the `game/` directory?

if that doesn't work, try `from ..game.GameManager import GameManager, planeNameMap` in `ucav.py`

let me know if that helps!

**Comment by Glaucus-2G** [comment]
> hey @Glaucus-2G! can you try adding an empty `__init__.py` file to the `game/` directory?
> 
> if that doesn't work, try `from ..game.GameManager import GameManager, planeNameMap` in `ucav.py`
> 
> let me know if that helps!

Thank you for you help!

I have already created  `__init__.py` in the game/ directory. In fact, I have written empty  `__init__.py` in each subdirectory.
I have try `from ..game.GameManager import GameManager, planeNameMap` in `ucav.py`, and it reports like this:

```
root@ray-head-0-5:/home/code/integrator# python gym_ppo.py 
Traceback (most recent call last):
  File "gym_ppo.py", line 10, in <module>
    env = gym.make('Ucav-v0')
  File "/opt/conda/lib/python3.7/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/gym/envs/registration.py", line 59, in make
    cls = load(self.entry_point)
  File "/opt/conda/lib/python3.7/site-packages/gym/envs/registration.py", line 18, in load
    mod = importlib.import_module(mod_name)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.7/site-packages/gym/envs/code/integrator/__init__.py", line 1, in <module>
    from ucav import UcavEnv
  File "/home/code/integrator/ucav.py", line 8, in <module>
    from ..game.GameManager import GameManager,planeNameMap
ImportError: attempted relative import with no known parent package
```
I also try to use absolute paths such as `sys.path.append("/opt/conda/lib/python3.7/site-pacakges/gym/envs/code/game")` in `ucav.py`.  Maybe my environment is  complicated, it doesn't work.

**Comment by sumanthratna** [comment]
> I have written empty` __init__.py` in each subdirectory.

Hmmm...do you also have an `__init__.py` in the `code/` directory? If you're writing a Python package, maybe write your appropriate `setup.py`, run `python -m pip install -e .`, and then import via `from code.game.GameManager import GameManager`.

I would also recommend you upgrade to Ray 0.8.7, which will let you do the following:
```python
ray.init(address="auto")
```
if you don't want to update, try the following:
```python
ray_head_service_host = os.getenv("RAY_HEAD_SERVICE_HOST", default="127.0.0.1")
ray_head_service_port_redis_primary = os.getenv("RAY_HEAD_SERVICE_PORT_REDIS_PRIMARY", default="6379")
ray_address = f"{ray_head_service_host}:{ray_head_service_port_redis_primary}"
print(f'Initializing Ray on cluster at address ray_address')
ray.init(address=ray_address)
```

side note: in `gym_ppo.py` you can use `register_env("myenv", MyEnv)` instead of `register_env("myenv", lambda config: MyEnv(config))`

---

once again, let me know if any of this helps!

**Comment by Glaucus-2G** [comment]
> Hmmm...do you also have an `__init__.py` in the `code/` directory? 
I create an `__init__.py` in `code/` directory and add absolute paths to some files. Luckily, it works.

Although there are still problems (as show below)，I think I'm close to success. The biggest possibility of this problem is that the format of my path is not standard.

> I would also recommend you upgrade to Ray 0.8.7.
>
> side note: in `gym_ppo.py` you can use `register_env("myenv", MyEnv)` instead of `register_env("myenv", lambda config: MyEnv(config))`

I didn't use Ray 0.8.7 before because it would output a lot of such information:
```
Level 1:tensorflow:Gradient for 'default_policy_1/tower_1/functional_1_1/fc_2/BiasAdd/ReadVariableOp'
Level 1:tensorflow:  in  --> default_policy_1/tower_1/gradients_1/default_policy_1/tower_1/functional_1_1/fc_2/BiasAdd_grad/tuple/control_dependency_1:0
Level 1:tensorflow:  out --> default_policy_1/tower_1/gradients_1/default_policy_1/tower_1/functional_1_1/fc_2/BiasAdd_grad/tuple/control_dependency_1:0
Level 1:tensorflow:Gradient for 'default_policy_1/tower_1/functional_1_1/fc_1/Tanh'
Level 1:tensorflow:  in  --> default_policy_1/tower_1/gradients_1/default_policy_1/tower_1/functional_1_1/fc_2/MatMul_grad/tuple/control_dependency:0
Level 1:tensorflow:  out --> default_policy_1/tower_1/gradients_1/default_policy_1/tower_1/functional_1_1/fc_1/Tanh_grad/TanhGrad:0
Level 1:tensorflow:Gradient for 'default_policy_1/tower_1/functional_1_1/fc_2/MatMul/ReadVariableOp'
```
However, after I follow your site note, such information will not be displayed.

Thank you again for your help.

**Comment by sumanthratna** [comment]
> However, after I follow your site note, such information will not be displayed.

hmmm—so when you switched from the lambda to just passing in the class, it worked? that's strange. I added that side note without looking at any of gym's documentation; I assumed the lambda and class were equivalent.

In any case, I think your script works, so I'm closing this issue. Feel free to ask for a reopen if the issue hasn't really been solved.

> Thank you again for your help.

of course; I hope I helped :)

**Comment by sumanthratna** [comment]
oh I think I misunderstood your comment. your script still doesn't work, but the TF warnings disappear after using a class instead of a lambda?

can you send your `../integrator/configs/planes.config`? 

reopening, but this might be better suited for a support ticket in gym

**Comment by Glaucus-2G** [comment]
Yes, in Ray 0.8.7,  the TF warnings disappear after using a class instead of a lambda.

Part of the code in `../integrator/configs/planes.config`  is as follows:

```
[common]
logDir = logs/
accLevel = 4
logOn = True
initState = F16Test
viewDir = logs/
```

Today I see some codes of more complex environments which are registered in gym. And I find that my code path obviously doesn't meet the specification of gym.  So I think that there is a long way to go that migrate code from a single machine to cluster.

**Comment by sumanthratna** [comment]
Hi @Glaucus-2G, sorry for the late reply. Unfortunately, I'm not sure if there's a way of using relative imports in Ray. For now, try copying your entire source code directory to all of your worker nodes. #2327
