### ISSUE TITLE
[autoscaler] Crash with custom node types

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#10868]
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 124, in update
    self._update()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 159, in _update
    self.log_info_string(nodes, target_workers)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 525, in log_info_string
    self.load_metrics.get_resource_utilization())
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ray/autoscaler/resource_demand_scheduler.py", line 124, in debug_string
    nodes, pending_nodes, usage_by_ip)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ray/autoscaler/resource_demand_scheduler.py", line 111, in calculate_node_resources
    add_node(node_type, resources)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ray/autoscaler/resource_demand_scheduler.py", line 100, in add_node
    available[resource] -= used
KeyError: 'memory'
```

I think this happens if you don't specify autodetected resources in the YAML. cc @wuisawesome

**Comment by ericl** [comment]
This seems to be fixed in master (will be in next rc1 for 1.0)

**Comment by wuisawesome** [comment]
Somewhat concerned that maybe this wasn't picked in the 1.0 branch? 

@barakmich when were the last commits for rc0 picked? 

@ericl i'll reopen this and mark as needs-repro until we verify that there is no bug in the wheel

**Comment by ericl** [comment]
It seems to me this fixes it https://github.com/ray-project/ray/pull/10728/files fixes it (which is picked).

**Comment by wuisawesome** [comment]
i would've thought that made it into rc0 though...

**Comment by rkooo567** [comment]
Any progress on this?

**Comment by wuisawesome** [comment]
i think we're good
