### ISSUE TITLE
Actors should be destroyed if their constructor fails

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1093]
Currently remote actors are kept even if their constructor fails. This leads to confusing error messages such as 

```
Remote function f failed with:

Traceback (most recent call last):
  File "/home/eric/Desktop/ray-private/python/ray/worker.py", line 727, in _process_task
    self.actors[task.actor_id().id()], *arguments)
  File "crash.py", line 10, in f
    assert self.initialized
AttributeError: 'MyActor' object has no attribute 'initialized'
```

in the following example

```
import ray

@ray.remote
class MyActor(object):
    def __init__(self):
        assert False, "oops the constructor crashed"
        self.initialized = True

    def f(self):
        assert self.initialized

ray.init()
a = MyActor.remote()
ray.get(a.f.remote())
```

It would probably be better to re-raise the initial exception.

**Comment by robertnishihara** [comment]
Good point! I've seen this a lot and it can be really confusing.

**Comment by robertnishihara** [comment]
Given #2843, I think this may no longer be necessary, though please reopen if you disagree.
