### ISSUE TITLE
[rllib] Checkpoint failing

### ISSUE THREAD

**Issue by saffronh** [ray-project/ray#11020]
I'm running rllib on a SLURM cluster, and am finding it very difficult to debug this error. In my config, I've set `--local-dir=~/ray_results` and turned all checkpointing flags (that I'm aware of) off. (`checkpoint_at_end=False` etc)

But it seems that this checkpointing in `step()` isn't of that variety - so I'm just wondering what else is the problem here. 

```
Traceback (most recent call last):
  File "/n/home02/sshuang/.local/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 347, in step
    self.checkpoint()
  File "/n/home02/sshuang/.local/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 279, in checkpoint
    os.replace(tmp_file_name, self.checkpoint_file)
FileNotFoundError: [Errno 2] No such file or directory: '/n/home02/sshuang/ray_results/asm_no_planner/.tmp_checkpoint' -> '/n/home02/sshuang/ray_results/asm_no_planner/experiment_state-2020-09-24_19-09-29.json'
2020-09-24 19:09:51,308 ERROR trial_runner.py:349 -- Trial Runner checkpointing failed.
```

Ray version I'm using is 0.8.7 and Python version is 3.7.7, TensorFlow version is 2.3.0.

**Comment by richardliaw** [comment]
Maybe try:
1. global_checkpoint_freq=100000
2. upgrading to newest Ray? (`pip install -U ray --pre`)

**Comment by saffronh** [comment]
Looks like `global_checkpoint_freq` / `global_checkpoint_period` is deprecated but I changed the TUNE_GLOBAL_CHECKPOINT_S environment variable and updated to newest Ray -- still, getting the same error! 

It's odd because this seems to work when I run locally on MacOSX but just doesn't work on the SLURM cluster. Is there something OS-related I need to change?

Extended traceback below:

```
2020-09-25 02:41:26,759	INFO services.py:1166 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
2020-09-25 02:41:26,758	INFO services.py:1166 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
2020-09-25 02:41:26,766	INFO services.py:1166 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
2020-09-25 02:41:30,816	INFO trial.py:137 -- Creating a new dirname PPO_asm_env_24879_00000_0_2020-09-25_02-41-30_b381 because trial dirname 'PPO_asm_env_24879_00000_0_2020-09-25_02-41-30' already exists.
2020-09-25 02:41:30,918	INFO trial.py:137 -- Creating a new dirname PPO_asm_env_24879_00000_0_2020-09-25_02-41-30_20bb because trial dirname 'PPO_asm_env_24879_00000_0_2020-09-25_02-41-30' already exists.
2020-09-25 02:41:31,227	INFO trial.py:137 -- Creating a new dirname PPO_asm_env_24879_00000_0_2020-09-25_02-41-30_c411 because trial dirname 'PPO_asm_env_24879_00000_0_2020-09-25_02-41-30' already exists.
2020-09-25 02:41:31,227	INFO trial.py:137 -- Creating a new dirname PPO_asm_env_24879_00000_0_2020-09-25_02-41-30_a465 because trial dirname 'PPO_asm_env_24879_00000_0_2020-09-25_02-41-30' already exists.
2020-09-25 02:41:53,630	WARNING util.py:139 -- The `start_trial` operation took 23.08646035194397 seconds to complete, which may be a performance bottleneck.
2020-09-25 02:41:53,631	WARNING util.py:139 -- The `start_trial` operation took 23.07629632949829 seconds to complete, which may be a performance bottleneck.
2020-09-25 02:41:53,631	WARNING util.py:139 -- The `start_trial` operation took 23.093544721603394 seconds to complete, which may be a performance bottleneck.
2020-09-25 02:41:53,631	WARNING util.py:139 -- The `start_trial` operation took 23.073604822158813 seconds to complete, which may be a performance bottleneck.
2020-09-25 02:41:53,632	WARNING util.py:139 -- The `start_trial` operation took 23.06533193588257 seconds to complete, which may be a performance bottleneck.
2020-09-25 02:41:53,632	WARNING util.py:139 -- The `start_trial` operation took 23.081575393676758 seconds to complete, which may be a performance bottleneck.
2020-09-25 02:41:53,636	WARNING util.py:139 -- The `start_trial` operation took 23.08871841430664 seconds to complete, which may be a performance bottleneck.
2020-09-25 02:41:53,772	WARNING util.py:139 -- The `start_trial` operation took 23.229443073272705 seconds to complete, which may be a performance bottleneck.
2020-09-25 02:41:54,756	WARNING util.py:139 -- The `experiment_checkpoint` operation took 1.124769926071167 seconds to complete, which may be a performance bottleneck.
2020-09-25 02:41:54,821	WARNING util.py:139 -- The `experiment_checkpoint` operation took 1.1884868144989014 seconds to complete, which may be a performance bottleneck.
2020-09-25 02:41:54,821	WARNING trial_runner.py:385 -- Trial Runner checkpointing failed: [Errno 2] No such file or directory: '/n/home02/sshuang/ray_results/asm_no_planner/.tmp_checkpoint' -> '/n/home02/sshuang/ray_results/asm_no_planner/experiment_state-2020-09-25_02-41-30.json'
2020-09-25 02:41:54,821	WARNING util.py:139 -- The `experiment_checkpoint` operation took 1.1893348693847656 seconds to complete, which may be a performance bottleneck.
2020-09-25 02:41:54,821	WARNING util.py:139 -- The `experiment_checkpoint` operation took 1.1901533603668213 seconds to complete, which may be a performance bottleneck.
2020-09-25 02:41:54,821	WARNING trial_runner.py:385 -- Trial Runner checkpointing failed: [Errno 2] No such file or directory: '/n/home02/sshuang/ray_results/asm_no_planner/.tmp_checkpoint' -> '/n/home02/sshuang/ray_results/asm_no_planner/experiment_state-2020-09-25_02-41-30.json'
2020-09-25 02:41:54,821	WARNING util.py:139 -- The `experiment_checkpoint` operation took 1.1899917125701904 seconds to complete, which may be a performance bottleneck.
2020-09-25 02:41:54,821	WARNING trial_runner.py:385 -- Trial Runner checkpointing failed: [Errno 2] No such file or directory: '/n/home02/sshuang/ray_results/asm_no_planner/.tmp_checkpoint' -> '/n/home02/sshuang/ray_results/asm_no_planner/experiment_state-2020-09-25_02-41-30.json'
2020-09-25 02:41:54,821	WARNING trial_runner.py:385 -- Trial Runner checkpointing failed: [Errno 2] No such file or directory: '/n/home02/sshuang/ray_results/asm_no_planner/.tmp_checkpoint' -> '/n/home02/sshuang/ray_results/asm_no_planner/experiment_state-2020-09-25_02-41-30.json'
2020-09-25 02:41:54,887	WARNING util.py:139 -- The `experiment_checkpoint` operation took 1.2501327991485596 seconds to complete, which may be a performance bottleneck.
2020-09-25 02:41:54,887	WARNING trial_runner.py:385 -- Trial Runner checkpointing failed: [Errno 2] No such file or directory: '/n/home02/sshuang/ray_results/asm_no_planner/.tmp_checkpoint' -> '/n/home02/sshuang/ray_results/asm_no_planner/experiment_state-2020-09-25_02-41-30.json'
2020-09-25 02:41:54,895	WARNING util.py:139 -- The `experiment_checkpoint` operation took 1.2618310451507568 seconds to complete, which may be a performance bottleneck.
2020-09-25 02:41:54,895	WARNING trial_runner.py:385 -- Trial Runner checkpointing failed: [Errno 2] No such file or directory: '/n/home02/sshuang/ray_results/asm_no_planner/.tmp_checkpoint' -> '/n/home02/sshuang/ray_results/asm_no_planner/experiment_state-2020-09-25_02-41-30.json'
2020-09-25 02:41:54,934	WARNING util.py:139 -- The `experiment_checkpoint` operation took 1.162341594696045 seconds to complete, which may be a performance bottleneck.
2020-09-25 02:41:54,935	WARNING trial_runner.py:385 -- Trial Runner checkpointing failed: [Errno 2] No such file or directory: '/n/home02/sshuang/ray_results/asm_no_planner/.tmp_checkpoint' -> '/n/home02/sshuang/ray_results/asm_no_planner/experiment_state-2020-09-25_02-41-30.json'
2020-09-25 02:41:57,662	WARNING worker.py:1072 -- The actor or task with ID ffffffffffffffffdf5a1a8201000000 is pending and cannot currently be scheduled. It requires {GPU: 1.000000}, {CPU: 4.000000} for execution and {GPU: 1.000000}, {CPU: 4.000000} for placement, but this node only has remaining {node:10.31.131.93: 1.000000}, {object_store_memory: 17.529297 GiB}, {accelerator_type:K40: 1.000000}, {CPU: 48.000000}, {memory: 50.927734 GiB}, {GPU: 1.000000}. In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale.
2020-09-25 02:41:57,664	WARNING worker.py:1072 -- The actor or task with ID ffffffffffffffffdf5a1a8201000000 is pending and cannot currently be scheduled. It requires {GPU: 1.000000}, {CPU: 4.000000} for execution and {GPU: 1.000000}, {CPU: 4.000000} for placement, but this node only has remaining {node:10.31.131.93: 1.000000}, {object_store_memory: 17.529297 GiB}, {accelerator_type:K40: 1.000000}, {CPU: 48.000000}, {memory: 50.927734 GiB}, {GPU: 1.000000}. In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale.
2020-09-25 02:41:57,667	WARNING worker.py:1072 -- The actor or task with ID ffffffffffffffffdf5a1a8201000000 is pending and cannot currently be scheduled. It requires {GPU: 1.000000}, {CPU: 4.000000} for execution and {GPU: 1.000000}, {CPU: 4.000000} for placement, but this node only has remaining {node:10.31.131.93: 1.000000}, {object_store_memory: 17.529297 GiB}, {accelerator_type:K40: 1.000000}, {CPU: 48.000000}, {memory: 50.927734 GiB}, {GPU: 1.000000}. In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale.
2020-09-25 02:41:57,670	WARNING worker.py:1072 -- The actor or task with ID ffffffffffffffffdf5a1a8201000000 is pending and cannot currently be scheduled. It requires {CPU: 4.000000}, {GPU: 1.000000} for execution and {CPU: 4.000000}, {GPU: 1.000000} for placement, but this node only has remaining {node:10.31.131.93: 1.000000}, {object_store_memory: 17.529297 GiB}, {accelerator_type:K40: 1.000000}, {CPU: 48.000000}, {memory: 50.927734 GiB}, {GPU: 1.000000}. In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale.
2020-09-25 02:41:57,833	WARNING worker.py:1072 -- The actor or task with ID ffffffffffffffffdf5a1a8201000000 is pending and cannot currently be scheduled. It requires {GPU: 1.000000}, {CPU: 4.000000} for execution and {GPU: 1.000000}, {CPU: 4.000000} for placement, but this node only has remaining {node:10.31.131.93: 1.000000}, {object_store_memory: 17.529297 GiB}, {accelerator_type:K40: 1.000000}, {CPU: 48.000000}, {memory: 50.927734 GiB}, {GPU: 1.000000}. In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale.
2020-09-25 02:41:57,901	WARNING worker.py:1072 -- The actor or task with ID ffffffffffffffffdf5a1a8201000000 is pending and cannot currently be scheduled. It requires {GPU: 1.000000}, {CPU: 4.000000} for execution and {GPU: 1.000000}, {CPU: 4.000000} for placement, but this node only has remaining {node:10.31.131.93: 1.000000}, {object_store_memory: 17.529297 GiB}, {accelerator_type:K40: 1.000000}, {CPU: 48.000000}, {memory: 50.927734 GiB}, {GPU: 1.000000}. In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale.
2020-09-25 02:41:57,914	WARNING worker.py:1072 -- The actor or task with ID ffffffffffffffffdf5a1a8201000000 is pending and cannot currently be scheduled. It requires {GPU: 1.000000}, {CPU: 4.000000} for execution and {GPU: 1.000000}, {CPU: 4.000000} for placement, but this node only has remaining {node:10.31.131.93: 1.000000}, {object_store_memory: 17.529297 GiB}, {accelerator_type:K40: 1.000000}, {CPU: 48.000000}, {memory: 50.927734 GiB}, {GPU: 1.000000}. In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale.
2020-09-25 02:41:57,933	WARNING worker.py:1072 -- The actor or task with ID ffffffffffffffffdf5a1a8201000000 is pending and cannot currently be scheduled. It requires {GPU: 1.000000}, {CPU: 4.000000} for execution and {GPU: 1.000000}, {CPU: 4.000000} for placement, but this node only has remaining {node:10.31.131.93: 1.000000}, {object_store_memory: 17.529297 GiB}, {accelerator_type:K40: 1.000000}, {CPU: 48.000000}, {memory: 50.927734 GiB}, {GPU: 1.000000}. In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale.
2020-09-25 02:41:58,170	INFO (unknown file):0 -- gc.collect() freed 33 refs in 0.40532482601702213 seconds
2020-09-25 02:41:58,188	INFO (unknown file):0 -- gc.collect() freed 33 refs in 0.42568741273134947 seconds
slurmstepd: error: Detected 2050 oom-kill event(s) in step 3211105.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: holyseasgpu01: task 5: Out Of Memory
2020-09-25 02:42:58,834	ERROR worker.py:1074 -- listen_error_messages_raylet: Connection closed by server.
2020-09-25 02:42:59,312	ERROR worker.py:981 -- print_logs: Connection closed by server.
2020-09-25 02:43:16,407	ERROR worker.py:1074 -- listen_error_messages_raylet: Connection closed by server.
2020-09-25 02:43:29,143	ERROR import_thread.py:89 -- ImportThread: Connection closed by server.
2020-09-25 02:43:29,192	ERROR worker.py:1074 -- listen_error_messages_raylet: Connection closed by server.
2020-09-25 02:43:29,677	ERROR worker.py:981 -- print_logs: Connection closed by server.
F0925 02:43:30.330130 28688 29768 service_based_gcs_client.cc:207] Couldn't reconnect to GCS server. The last attempted GCS server address was :0
slurmstepd: error: Detected 10136 oom-kill event(s) in step 3211105.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
```

**Comment by saffronh** [comment]
Still failing - any idea what else I can check?
