### ISSUE TITLE
Running DQN on PongDeterministic-v4

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#1113]
Running

```
python train.py --env PongDeterministic-v4 --alg DQN
```

crashes with

```
Traceback (most recent call last):
  File "train.py", line 68, in <module>
    env_name, config, upload_dir=args.upload_dir)
  File "/Users/pcmoritz/ray/python/ray/rllib/common.py", line 179, in __init__
    self._init()
  File "/Users/pcmoritz/ray/python/ray/rllib/dqn/dqn.py", line 250, in _init
    self.actor = Actor(self.env_creator, self.config, self.logdir)
  File "/Users/pcmoritz/ray/python/ray/rllib/dqn/dqn.py", line 118, in __init__
    self.dqn_graph = models.DQNGraph(env, config)
  File "/Users/pcmoritz/ray/python/ray/rllib/dqn/models.py", line 115, in __init__
    self.cur_observations, num_actions, config)
  File "/Users/pcmoritz/ray/python/ray/rllib/dqn/models.py", line 14, in _build_q_network
    frontend = ModelCatalog.get_model(inputs, 1, config["model"])
  File "/Users/pcmoritz/ray/python/ray/rllib/models/catalog.py", line 79, in get_model
    return VisionNetwork(inputs, num_outputs, options)
  File "/Users/pcmoritz/ray/python/ray/rllib/models/model.py", line 38, in __init__
    inputs, num_outputs, options)
  File "/Users/pcmoritz/ray/python/ray/rllib/models/visionnet.py", line 30, in _init
    return tf.squeeze(fc2, [1, 2]), tf.squeeze(fc1, [1, 2])
  File "/Users/pcmoritz/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 2281, in squeeze
    return gen_array_ops._squeeze(input, axis, name)
  File "/Users/pcmoritz/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3329, in _squeeze
    squeeze_dims=squeeze_dims, name=name)
  File "/Users/pcmoritz/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/Users/pcmoritz/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "/Users/pcmoritz/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/Users/pcmoritz/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/Users/pcmoritz/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/Users/pcmoritz/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Can not squeeze dim[1], expected a dimension of 1, got 18 for 'q_func/vision_net/Squeeze' (op: 'Squeeze') with input shapes: [?,18,11,1].
```

cc @ericl

**Comment by ericl** [comment]
This is a rather embarassing bug where DQN only supports atari environments that include "NoFrameskip" in their name.

The fix is to use the common RLlib code for detecting atari envs, I'll try to make a PR for that.

**Comment by ericl** [comment]
Fixed in https://github.com/ray-project/ray/pull/1124
