### ISSUE TITLE
pip install ray  broken for centos python 3.6.9

### ISSUE THREAD

**Issue by manishagarwal23** [ray-project/ray#11228]
i ran pip install ray on centos 
CentOS Linux release 7.8.2003 (Core) 

(app-root) bash-4.2# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)
(app-root) bash-4.2# python --version
Python 3.6.9
(app-root) bash-4.2#

pip install ray  

<lots of logs>

    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -I/opt/rh/rh-python36/root/usr/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/opt/rh/rh-python36/root/usr/include/python3.6m -c /tmp/tmp6sxpgubl/a.c -o None/tmp/tmp6sxpgubl/a.o
    Traceback (most recent call last):
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/unixccompiler.py", line 128, in _compile
        extra_postargs)
      File "/tmp/pip-build-1_ml838l/grpcio/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
        _classic_spawn(self, command)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-build-1_ml838l/grpcio/src/python/grpcio/commands.py", line 264, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/tmp/pip-build-1_ml838l/grpcio/src/python/grpcio/_parallel_compile_patch.py", line 59, in _parallel_compile
        _compile_single_file, objects)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
        return self._map_async(func, iterable, mapstar, chunksize).get()
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
        raise self._value
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
        result = (True, func(*args, **kwds))
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
        return list(map(*args))
      File "/tmp/pip-build-1_ml838l/grpcio/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/tmp/pip-build-1_ml838l/grpcio/src/python/grpcio/commands.py", line 248, in new_compile
        pp_opts)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/unixccompiler.py", line 130, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1_ml838l/grpcio/setup.py", line 465, in <module>
        cmdclass=COMMAND_CLASS,
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-build-1_ml838l/grpcio/src/python/grpcio/commands.py", line 269, in build_extensions
        "Failed `build_ext` step:\n{}".format(formatted_exception))
    commands.CommandError: Failed `build_ext` step:
    Traceback (most recent call last):
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/unixccompiler.py", line 128, in _compile
        extra_postargs)
      File "/tmp/pip-build-1_ml838l/grpcio/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
        _classic_spawn(self, command)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-build-1_ml838l/grpcio/src/python/grpcio/commands.py", line 264, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/opt/app-root/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/tmp/pip-build-1_ml838l/grpcio/src/python/grpcio/_parallel_compile_patch.py", line 59, in _parallel_compile
        _compile_single_file, objects)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
        return self._map_async(func, iterable, mapstar, chunksize).get()
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
        raise self._value
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
        result = (True, func(*args, **kwds))
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
        return list(map(*args))
      File "/tmp/pip-build-1_ml838l/grpcio/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/tmp/pip-build-1_ml838l/grpcio/src/python/grpcio/commands.py", line 248, in new_compile
        pp_opts)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/unixccompiler.py", line 130, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/opt/app-root/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1_ml838l/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-vs0ozs8q-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/app-root/include/site/python3.6/grpcio" failed with error code 1 in /tmp/pip-build-1_ml838l/grpcio/
You are using pip version 9.0.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(app-root) bash-4.2#
(app-root) bash-4.2#

**Comment by sumanthratna** [comment]
Hi @manishagarwal23! That's a problem with installing grpcio, not exactly ray; I'm not sure if we have a fix for it yet. grpcio doesn't install on macOS Big Sur either. For now, try cloning ray and commenting out the grpcio dependency in `python/setup.py`. Then run `cd python && pip install .`. Let me know if that works for you!

**Comment by manishagarwal23** [comment]
But that comes when I do pip install ray . I am not doing any custom steps . How else can I get a valid ray 1.0.0 binaries and dependencies

**Comment by sumanthratna** [comment]
Since grpcio hasn't published wheels for centOS, you'll need to do some custom steps. Unfortunately, I don't think there's anything we can do about this on the Ray end right now. I recommend you follow the workaround I mentioned earlier:
```sh
# activate your virtual environment (e.g., source venv/bin/activate, poetry shell, pipenv shell)
git clone https://github.com/ray-project/ray.git --depth 5 --branch ray-1.0.0
cd ray/python/
nano setup.py  # remove grpcio; you might need to remove py-spy also
python3.6 -m pip install .
# at this point, ray should be installed in your venv
```
alternatively, look into using docker

**Comment by manishagarwal23** [comment]
without grpcio how will ray communicate with remote machines . will it be able to communicate ?

**Comment by sumanthratna** [comment]
> without grpcio how will ray communicate with remote machines

I don't know the details of Ray's gRPC usage but I believe it's used to communicate between raylets and the GCS/plasma store. This will probably break some important communications, but for local development with tune I've found that ray without grpcio works okay. 

If you're using CentOS on your cluster, try:
- building grpcio from source (see https://github.com/grpc/grpc/tree/master/src/python/grpcio#installing-from-source)
- using docker or kubernetes so that you can use a better-supported linux container

**Comment by manishagarwal23** [comment]
Can u please share the docker file which I can utilize for communication a Ross machines

**Comment by sumanthratna** [comment]
Sure! 

> Can you please share the docker file which I can utilize for communication across machines
You can start a Ray container with `docker run --shm-size=2GB -v host_src_dir:/container_src_dir -t -i ray-project/ray` (see https://docs.ray.io/en/master/installation.html?highlight=docker#docker-source-images).

You can also try using the cluster launcher with autoscaling, which has docker support (see https://docs.ray.io/en/master/cluster/autoscaling.html?highlight=docker#docker-support and https://docs.ray.io/en/master/cluster/cloud.html?highlight=docker#common-cluster-configurations)

> also if not centos what is that you propose .

Try using the [`rayproject/ray`](https://hub.docker.com/r/rayproject/ray) image.

**Comment by manishagarwal23** [comment]
Unfortunately I have found that we cannot leave centos as that is what we wish to deploy ray on our cluster . Can you please guide if we can replace grpc with some other component .

**Comment by manishagarwal23** [comment]
The link you shared is the image can you please share the docker file as well please. . it will help me understand better

**Comment by sumanthratna** [comment]
> Unfortunately I have found that we cannot leave centos as that is what we wish to deploy ray on our cluster . Can you please guide if we can replace grpc with some other component .

Hmmm okay I think your last option is to build grpcio from source.

Can you follow the steps here? https://github.com/grpc/grpc/tree/master/src/python/grpcio#installing-from-source

> can you please share the docker file as well please

completely untested:
```dockerfile
FROM rayproject/ray
COPY src/ /project
WORKDIR /project
RUN python3 -m pip install -r requirements.txt
```
the `rayproject/ray`image should contain all the dependencies you need. You can put your project dependencies in `src/requirements.txt`. I hope this helps!

**Comment by manishagarwal23** [comment]
I see that in stack above I see lots of GCC . It  means ray installations checjed and tried to compile grpc .is it so ?

**Comment by sumanthratna** [comment]
When you got the error you sent above, this is roughly what happened:
1. `pip` checked PyPI to see if there were any [wheels for grpcio](https://pypi.org/project/grpcio/#files)
2. there weren't any wheels compatible with centos, so pip downloaded the source archive (grpcio-version.tar.gz)
3. pip tried to install from source
4. the installation failed, maybe because of issues with gcc versioning

Is there any other error output (probably a big block of red text)?

**Comment by manishagarwal23** [comment]
i will share that soon . I  wanted ti understand why i cant download ray docker  image 
PS D:\bugs\Features\ray\dockerWork\Dockerfilesdir> docker run --shm-size=2GB -v host_src_dir:/container_src_dir -t -i ray-project/ray
Unable to find image 'ray-project/ray:latest' locally
C:\Program Files\Docker\docker.exe: Error response from daemon: pull access denied for ray-project/ray, repository does not exist or may require 'docker login'.
See 'C:\Program Files\Docker\docker.exe run --help'.
PS D:\bugs\Features\ray\dockerWork\Dockerfilesdir>

So i searched on docker hub . I couldn even find the image there . Please note that login message is wrong

**Comment by sumanthratna** [comment]
It looks like we might have a typo in the docs—the docker image is at `rayproject/ray`, not `ray-project/ray`. I'll push a fix for this soon. Thanks for the catch! Let me know if it works.

**Comment by manishagarwal23** [comment]
@sumanthretna . on firing a rebuild ray did started with grpc built . I got into another issue which i just posed here https://github.com/ray-project/ray/issues/11211  . can you also please see that
