### ISSUE TITLE
[tune]ray.tune.run() returns 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by yutaizhou** [ray-project/ray#11315]
### What is the problem?
I pass in a list of rllib experiments to run but get the error in title. Closest issue I found was #5042. I installed all tf related packages but the error persists. 
@richardliaw 

*Ray version and other system information (Python version, TensorFlow version, OS):*
python 3.8
ray 1.0.0
pytorch 1.6

### Reproduction (REQUIRED)
I cannot share the code due to my work :( 

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
@yutaizhou can you post a full stacktrace?

**Comment by yutaizhou** [comment]
```
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
2020-10-09 13:30:35,974 INFO services.py:1164 -- View the Ray dashboard at http://127.0.0.1:8265
Traceback (most recent call last):
  File "kaz_v2_runner.py", line 149, in <module>
    results = ray.tune.run(experiment_list, verbose=1)
  File "/home/yutaizhou/miniconda3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/tune/tune.py", line 405, in run
    runner.step()
  File "/home/yutaizhou/miniconda3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 370, in step
    next_trial = self._get_next_trial()  # blocking
  File "/home/yutaizhou/miniconda3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 457, in _get_next_trial
    self._update_trial_queue(blocking=wait_for_trial)
  File "/home/yutaizhou/miniconda3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 737, in _update_trial_queue
    trials = self._search_alg.next_trials()
  File "/home/yutaizhou/miniconda3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/tune/suggest/basic_variant.py", line 83, in next_trials
    trials = list(self._trial_generator)
  File "/home/yutaizhou/miniconda3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/tune/suggest/basic_variant.py", line 110, in _generate_trials
    yield create_trial_from_spec(
  File "/home/yutaizhou/miniconda3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/tune/config_parser.py", line 173, in create_trial_from_spec
    return Trial(
  File "/home/yutaizhou/miniconda3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/tune/trial.py", line 213, in __init__
    default_resources = trainable_cls.default_resource_request(
  File "/home/yutaizhou/miniconda3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 483, in default_resource_request
    Trainer._validate_config(cf)
  File "/home/yutaizhou/miniconda3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1057, in _validate_config
    config.get("model", {}).get("_time_major"):
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by yutaizhou** [comment]
Ahhh turns out I had a model parameter in my yaml config that I did not comment out after commenting out conv_filter. That fixed the issue :)

**Comment by yutaizhou** [comment]
Sorry, I was using vscode debugger and somehow that prevented the full stack trace to be shown. Seeing the config.get("model" part made it click for me
