### ISSUE TITLE
[rllib] Cannot save multiagent trainer with custom policy without weights

### ISSUE THREAD

**Issue by DoxakisCh** [ray-project/ray#11454]
Hi!

I am trying to train different algorithms from your library against a player that takes random actions on a poker environment. For this reason I modified the random policy file that you provide in your examples. The trainning is being performed without any problem but when I try to save the trainer, I get the following error:

Traceback (most recent call last):
  File "C:/Users/doxak/PycharmProjects/poker_env/rllib/test.py", line 62, in <module>
    pg_trainer.save()
  File "C:\Users\doxak\anaconda3\envs\poker_env\lib\site-packages\ray\tune\trainable.py", line 422, in save
    checkpoint = self.save_checkpoint(checkpoint_dir)
  File "C:\Users\doxak\anaconda3\envs\poker_env\lib\site-packages\ray\rllib\agents\trainer.py", line 678, in save_checkpoint
    pickle.dump(self.__getstate__(), open(checkpoint_path, "wb"))
  File "C:\Users\doxak\anaconda3\envs\poker_env\lib\site-packages\ray\rllib\agents\trainer_template.py", line 119, in __getstate__
    state = Trainer.__getstate__(self)
  File "C:\Users\doxak\anaconda3\envs\poker_env\lib\site-packages\ray\rllib\agents\trainer.py", line 1177, in __getstate__
    state["worker"] = self.workers.local_worker().save()
  File "C:\Users\doxak\anaconda3\envs\poker_env\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 888, in save
    for pid in self.policy_map
  File "C:\Users\doxak\anaconda3\envs\poker_env\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 888, in <dictcomp>
    for pid in self.policy_map
  File "C:\Users\doxak\anaconda3\envs\poker_env\lib\site-packages\ray\rllib\policy\policy.py", line 431, in get_state
    return self.get_weights()
  File "C:\Users\doxak\anaconda3\envs\poker_env\lib\site-packages\ray\rllib\policy\policy.py", line 373, in get_weights
    raise NotImplementedError
NotImplementedError

Apparently this happens because there are no weights for this policy.  Is there a way to save these trainers as long as I train only the other policies?

Thank you.

**Comment by madScientist10** [comment]
I am having a similar issue. Does anyone have a workaround for this issue?
