### ISSUE TITLE
[rllib]MADDPG in two_steo_game.py cannot run

### ISSUE THREAD

**Issue by nosugerhcc** [ray-project/ray#11528]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
    python=3.7 tensorflow=2.0.0 window10
### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
>python.exe D:/anaconda/envs/tfto1/Lib/site-packages/ray/rllib/examples/two_step_game.py --run "contrib/MADDPG"

If we cannot run your script, we cannot fix your issue.
Failure # 1 (occurred at 2020-10-21_22-20-03)
Traceback (most recent call last):
  File "D:\anaconda\envs\tfto1\lib\site-packages\ray\tune\trial_runner.py", line 515, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "D:\anaconda\envs\tfto1\lib\site-packages\ray\tune\ray_trial_executor.py", line 488, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "D:\anaconda\envs\tfto1\lib\site-packages\ray\worker.py", line 1428, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): [36mray::MADDPG.train()[39m (pid=16176, ip=10.112.10.23)
  File "python\ray\_raylet.pyx", line 445, in ray._raylet.execute_task
  File "D:\anaconda\envs\tfto1\lib\site-packages\ray\worker.py", line 174, in reraise_actor_init_error
    raise self.actor_init_error
  File "python\ray\_raylet.pyx", line 479, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 483, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 484, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 438, in ray._raylet.execute_task.function_executor
  File "D:\anaconda\envs\tfto1\lib\site-packages\ray\function_manager.py", line 553, in actor_method_executor
    return method(actor, *args, **kwargs)
  File "D:\anaconda\envs\tfto1\lib\site-packages\ray\rllib\agents\trainer_template.py", line 101, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "D:\anaconda\envs\tfto1\lib\site-packages\ray\rllib\agents\trainer.py", line 476, in __init__
    super().__init__(config, logger_creator)
  File "D:\anaconda\envs\tfto1\lib\site-packages\ray\tune\trainable.py", line 249, in __init__
    self.setup(copy.deepcopy(self.config))
  File "D:\anaconda\envs\tfto1\lib\site-packages\ray\rllib\agents\trainer.py", line 629, in setup
    self._init(self.config, self.env_creator)
  File "D:\anaconda\envs\tfto1\lib\site-packages\ray\rllib\agents\trainer_template.py", line 125, in _init
    self.config["num_workers"])
  File "D:\anaconda\envs\tfto1\lib\site-packages\ray\rllib\agents\trainer.py", line 699, in _make_workers
    logdir=self.logdir)
  File "D:\anaconda\envs\tfto1\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 74, in __init__
    self._local_config)
  File "D:\anaconda\envs\tfto1\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 305, in _make_worker
    extra_python_environs=extra_python_environs)
  File "D:\anaconda\envs\tfto1\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 416, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "D:\anaconda\envs\tfto1\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1008, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "D:\anaconda\envs\tfto1\lib\site-packages\ray\rllib\contrib\maddpg\maddpg_policy.py", line 157, in __init__
    scope="actor"))
  File "D:\anaconda\envs\tfto1\lib\site-packages\ray\rllib\contrib\maddpg\maddpg_policy.py", line 375, in _build_actor_network
    sampler = tfp.distributions.RelaxedOneHotCategorical(
AttributeError: 'NoneType' object has no attribute 'distributions'
- [] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by young-chao** [comment]
I also encountered the same problem.

**Comment by mvindiola1** [comment]
This is likely because the user does not have the tensorflow-probability package installed. The fix for me was: `pip install tensorflow-probability`
