### ISSUE TITLE
[rllib] tuned_examples/dreamer not work: No module named 'ray.rllib.models.torch.modules.reshape'

### ISSUE THREAD

**Issue by Liu-SD** [ray-project/ray#11521]
python: 3.7.7
pytorch: 1.6.0
ray: 1.1.0dev0
I used the setup-dev.py script to link master to ray binary installation.

when I run
`rllib train -f dreamer-deepmind-control.yaml`
error occurs as follow:

> Failure # 1 (occurred at 2020-10-21_15-22-52)
Traceback (most recent call last):
  File "/home/liu/miniconda3/envs/pt/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 726, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/liu/miniconda3/envs/pt/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 489, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/liu/miniconda3/envs/pt/lib/python3.7/site-packages/ray/worker.py", line 1450, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ImportError): ray::_AgentImportFailed.train() (pid=8964, ip=10.200.43.251)
  File "python/ray/_raylet.pyx", line 443, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 477, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 481, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 482, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 436, in ray._raylet.execute_task.function_executor
  File "/home/liu/miniconda3/envs/pt/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 477, in __init__
    super().__init__(config, logger_creator)
  File "/home/liu/miniconda3/envs/pt/lib/python3.7/site-packages/ray/tune/trainable.py", line 249, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/liu/miniconda3/envs/pt/lib/python3.7/site-packages/ray/rllib/agents/mock.py", line 129, in setup
    raise ImportError(trace)
ImportError: Traceback (most recent call last):
  File "/home/liu/miniconda3/envs/pt/lib/python3.7/site-packages/ray/rllib/agents/registry.py", line 148, in get_agent_class
    return _get_agent_class(alg)
  File "/home/liu/miniconda3/envs/pt/lib/python3.7/site-packages/ray/rllib/agents/registry.py", line 156, in _get_agent_class
    return ALGORITHMS[alg]()
  File "/home/liu/miniconda3/envs/pt/lib/python3.7/site-packages/ray/rllib/agents/registry.py", line 59, in _import_dreamer
    from ray.rllib.agents import dreamer
  File "/home/liu/miniconda3/envs/pt/lib/python3.7/site-packages/ray/rllib/agents/dreamer/__init__.py", line 1, in <module>
    from ray.rllib.agents.dreamer.dreamer import DREAMERTrainer, DEFAULT_CONFIG
  File "/home/liu/miniconda3/envs/pt/lib/python3.7/site-packages/ray/rllib/agents/dreamer/dreamer.py", line 14, in <module>
    from ray.rllib.agents.dreamer.dreamer_model import DreamerModel
  File "/home/liu/miniconda3/envs/pt/lib/python3.7/site-packages/ray/rllib/agents/dreamer/dreamer_model.py", line 3, in <module>
    from ray.rllib.models.torch.modules.reshape import Reshape
ModuleNotFoundError: No module named 'ray.rllib.models.torch.modules.reshape'

**Comment by GittiHab** [comment]
Hi, so what's the solution? Since there is a [blog post](https://medium.com/distributed-computing-with-ray/model-based-reinforcement-learning-with-ray-rllib-73f47df33839) showing off the Dreamer example, I would assume that Dreamer once worked, right?

I get the same error when trying to run Dreamer using the tuned file or with:

`rllib train --run DREAMER --env CartPole-v0 --stop '{"time_total_s": 300, "training_iteration": 50000}' --torch`

**Comment by GittiHab** [comment]
I just checked the history and it seems like the import was added with branch #11231 ([this commit](https://github.com/ray-project/ray/commit/d3bc20b727b1e4c58644a5be303b8f9be0510549#diff-409088c11b69f5b4f861412062ed19ee1343790fecbb0cdeff876511e7062be4)). So the solution is to install the most recent ray version without this commit (1.0.0). Also it is important to install `dm-control` (e.g. by `pip install git+git://github.com/deepmind/dm_control.git`)

Generally, I wonder how come a module is used that does not exist (in a released version)? And maybe this would be a good time to test whether agents can be successfully initialized ;).

**Comment by EloyAnguiano** [comment]
@GittiHab why do you say that it is important to install dm-control? When I try to install `dm_control` its setup file searches some MuJoCo installation that I dont need as I am trying to use Dreamer on a custom environment. I think that rllib should remove this installation for using dreamer algorithm as MoJoCo is not free.

Is there any stable version for using Dreamer without this import error and without needing to install MuJoCo? Can someone giva a Dockerfile for executing this? It seems impossible.

**Comment by GittiHab** [comment]
Hey @EloyAnguiano, I don't remember why I wrote that `dm_control` should be required. I assume that I got an error when trying to run without. However, in my initial message, the environment `CartPole-v0` sounds like it is from the `gym` package so it might work without `dm_control`.

Did you try running without `dm_control`? Otherwise, just try following the installation instructions from [`dm_control`](https://github.com/deepmind/dm_control#requirements-and-installation).

It could be though that MuJoCo is just required by the CartPole environment in general (which I don't think). In this case either use a [gym environment](https://github.com/openai/mujoco-py) that doesn't require MuJoCo or look at [mujoco-py](https://github.com/openai/mujoco-py). Whenever using MuJoCo, however, you will need a license, as you said. The MuJoCo website (linked by all the installation instructions) offers a free trial for 30 days which you could use to get things running.

I have dropped ray/rllib though, so I am afraid I cannot really help you any further.
