### ISSUE TITLE
[cloudpickle] Too much override for cloudpickle, breaks scikit-learn usage

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#11547]
### What is the problem?

```python
import ray
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
from sklearn.datasets import make_classification
import numpy as np

X, y = make_classification(
    n_samples=11000,
    n_features=1000,
    n_informative=50,
    n_redundant=0,
    n_classes=10,
    class_sep=2.5)
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=1000)

# Example parameters to tune from SGDClassifier
parameter_grid = {"alpha": [1e-4, 1e-1, 1], "epsilon": [0.01, 0.1]}
from sklearn.model_selection import GridSearchCV
# n_jobs=-1 enables use of all cores like Tune does
sklearn_search = GridSearchCV(SGDClassifier(), parameter_grid, n_jobs=-1)
sklearn_search.fit(x_train, y_train)
```

Introduces:

```
--------------------------------------------------------------------------------
LokyProcess-10 failed with traceback:
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rliaw/miniconda3/envs/test/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 197, in <module>
    prep_data = pickle.load(from_parent)
ValueError: unsupported pickle protocol: 5


--------------------------------------------------------------------------------
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {EXIT(1)}
```

This is because it uses `Joblib`, a library for parallel computation. Joblib is for multiprocessing, so has a IPC where they use cloudpickle on the client side to transfer data to child processes. I think these clients access some ray cloudpickle attributes on accident, causing deserialization to break down. 

Can we avoid the ray cloudpickle port from affecting 3rdparty libs?

cc @suquark 

```python
if sys.platform != "win32":
    from ._posix_reduction import _mk_inheritable  # noqa: F401
else:
    from . import _win_reduction  # noqa: F401

# global variable to change the pickler behavior
try:
    from joblib.externals import cloudpickle  # noqa: F401
    DEFAULT_ENV = "cloudpickle"
except ImportError:
    # If cloudpickle is not present, fallback to pickle
    DEFAULT_ENV = "pickle"

ENV_LOKY_PICKLER = os.environ.get("LOKY_PICKLER", DEFAULT_ENV)
_LokyPickler = None
_loky_pickler_name = None
```

**Comment by richardliaw** [comment]
For reference, the fix is to import sklearn modules before Ray:
```
# Keep this here for https://github.com/ray-project/ray/issues/11547
from sklearn.model_selection import GridSearchCV

from ray.tune.sklearn import TuneGridSearchCV
```

**Comment by xianyinxin** [comment]
Any update on this issue? We encountered the same problem but we didn't use ray.tune. Importing ray after sklearn after GridSearchCV did not work.

**Comment by richardliaw** [comment]
Another fix I've found is to disable joblib usage - i.e., `n_jobs=1`. @xianyinxin as mentioned on slack, I'd love to know more about what your workload is (how you're using Ray + sklearn)

**Comment by xianyinxin** [comment]
Update: @richardliaw I just use ray as a massive parallel engine where i run a GridSearchCV task in each actor. I tried your suggestion and it works. Thanks!

**Comment by richardliaw** [comment]
This is now showing up again for Horovod-Ray. Generally, anything that uses `cloudpickle` in a library out of band from Ray will break. 

@suquark is it possible to avoid affecting the regular `cloudpickle` path?

**Comment by suquark** [comment]
@richardliaw I cannot reproduce the error with the given code. What python and joblib version you are using?

**Comment by richardliaw** [comment]
@suquark let me get another repro for this, as i think it is out of date.

**Comment by richardliaw** [comment]
Hi @suquark thanks for looking into this! I've updated the above script and can repro this on the latest sklearn ( 0.23.2) and joblib (1.0.0).

**Comment by suquark** [comment]
@richardliaw I can see the error message now with `joblib==1.0.0`, I'll dig into the bug.

**Comment by suquark** [comment]
Here's a minimal reproducible script:

```python
import ray
from math import sqrt
from joblib import Parallel, delayed
Parallel(n_jobs=2)(delayed(sqrt)(i ** 2) for i in range(10))
```

The bug is caused by

```
>>> import pickle5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pickle5'
>>> import ray
>>> import pickle5
```

and the root cause is:

```python
####### python/ray/__init__.py
# Add the directory containing pickle5 to the Python path so that we find the
# pickle5 version packaged with ray and not a pre-existing pickle5.
pickle5_path = os.path.join(
    os.path.abspath(os.path.dirname(__file__)), "pickle5_files")
sys.path.insert(0, pickle5_path)
```

We may fix this issue by isolating the pickle5 path of ray from a default pickle5.

**Comment by pcmoritz** [comment]
So maybe we need to help the upstream pickle5 package to build wheels and remove the hack and depend on the upstream version directly? That would be the preferred solution. If that's too much work, we could install the pickle5_path in our vendored cloudpickle (ugh).

**Comment by suquark** [comment]
I also agree with the upstream solution.

**Comment by suquark** [comment]
@richardliaw @pcmoritz I create an issue for the upstream: https://github.com/pitrou/pickle5-backport/issues/23. However, we should not expect this could be addressed soon (). If you think this problem is critical, I can come with a temporary fix first.

**Comment by suquark** [comment]
It looks like the maintainer of pickle5 would just freeze the code now, since python3.8/3.9 has enabled pickle protocol 5 support any way. We have to build wheels by ourselves.

**Comment by richardliaw** [comment]
Yeah, a temporary fix sounds great!

**Comment by suquark** [comment]
I just find a temporary fix like changing the path of our pickle5 build crashes numpy:

```
ImportError: Using pickle protocol 5 requires the pickle5 module for Python >=3.6 and <3.8
```

This is because numpy cares about pickle5 path...

so I think the only solution would be building and hosting pickle5 wheels by ourselves.

**Comment by richardliaw** [comment]
Hmmm, what if we just vendor our own copy of the files within Ray?

**Comment by suquark** [comment]
we are doing this now and 

1. if the vendor provides a global import name `pickle5`, this fails any thirdparty libraries using cloudpickle. (the current issue)
2. if the vendor does not provide a global import name, this fails numpy (a temporary fix)
3. if we do not vendor it, users without a proper compilation environment would fail installing ray.

**Comment by richardliaw** [comment]
Hmm, why/where does numpy care about pickle5 path? I checked the source
just now but I couldn't find any pickle5 references.

**Comment by suquark** [comment]
in `numpy/core/src/multiarray/methods.c`:

```C
pickle_module = PyImport_ImportModule("pickle5");
```

**Comment by suquark** [comment]
a hacky temporary solution would be:

1. vendor `pickle5` and hide it to prevent it been imported by joblib
2. during initializing ray, we temporarily add it to the python path, and we import numpy and serialize a temporary numpy array with pickle protocol 5, so numpy now could import pickle5. and we just hope whenever numpy tried to import pickle5 later, python interpreter would reuse the preimported cache
3. we remove the vendored pickle5 from the python path, so joblib/cloudpickle could not import it later
4. we modify cloudpickle and provide the private path to our vendored pickle5, so our own cloudpickle can make use of our own copy

**Comment by suquark** [comment]
@pcmoritz @richardliaw I successfully build pickle5 wheels for all platforms: https://github.com/suquark/pickle5-backport/actions/runs/439212375. Do you have any ideas about how to install these wheels when users installing ray? I am currently thinking of creating a new pypi package (e.g. `pickle5-wheels`) and install pickle5 for users. This is like pillow for PIL. Do you think this is a good idea?

**Comment by richardliaw** [comment]
I am not sure. Will there be any impact to users?

**Comment by suquark** [comment]
after some efforts, the best solution still seems to be releasing a pickle5 upstream wheel. however, we need to convince the author: pitrou/pickle5-backport#23.
another way is to release a new pypi package by ourselves

**Comment by Chethan-Babu-stack** [comment]
Has this issue been solved?

**Comment by richardliaw** [comment]
@Chethan-Babu-stack the solution for me usually is to disable joblib (or set workers to 0 or 1) within the Ray process/worker.

**Comment by Chethan-Babu-stack** [comment]
Thanks for the quick reply Richard. I don't understand what you meant. Can you please explain a bit more?

**Comment by richardliaw** [comment]
I only see this error for scikitlearn usage with Ray. can you tell me whats your context for running into this?

**Comment by Chethan-Babu-stack** [comment]
I'm parallelizing the 10 Fold cross validation as "folds_val_test = Parallel(n_jobs=10)(delayed(train)(fold) for fold in range(n_folds)) " which uses scikit learn inside each fold. 

Issue:
LokyProcess-10 failed with traceback:
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home//my-kernel/lib/python3.6/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 197, in <module>
    prep_data = pickle.load(from_parent)
ValueError: unsupported pickle protocol: 5

[0m Trial 0 failed because of the following error: TerminatedWorkerError('A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.\n\nThe exit codes of the workers are {EXIT(1), EXIT(1), EXIT(1), EXIT(1), EXIT(1), EXIT(1), EXIT(1), EXIT(1), EXIT(1), EXIT(1)}',)
Traceback (most recent call last):
  File "/home/chve882b/chethan-kernel/my-kernel/lib/python3.6/site-packages/optuna/_optimize.py", line 217, in _run_trial
    value_or_values = func(trial)
  File "/home/chve882b/thesis/OPC_Full/OPC_Full_Dataset/EV_GCN-master/train_eval_evgcn.py", line 140, in objective
    folds_val_test = Parallel(n_jobs=10)(delayed(train)(fold) for fold in range(n_folds))
  File "/home/chve882b/chethan-kernel/my-kernel/lib/python3.6/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/chve882b/chethan-kernel/my-kernel/lib/python3.6/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/chve882b/chethan-kernel/my-kernel/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/chve882b/chethan-kernel/my-kernel/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/chve882b/chethan-kernel/my-kernel/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
