### ISSUE TITLE
ray install-nightly fail

### ISSUE THREAD

**Issue by viotemp1** [ray-project/ray#11589]
Hello,

Nightly link is broken fot python 3.8 package

ray install-nightly
Running: /home/xyz/anaconda3/envs/tf2_n1/bin/python3.8 -m pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp38-cp38-manylinux1_x86_64.whl.
Collecting ray==1.0.0
  ERROR: HTTP error 404 while getting https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp38-cp38-manylinux1_x86_64.whl
ERROR: Could not install requirement ray==1.0.0 from https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp38-cp38-manylinux1_x86_64.whl because of HTTP error 404 Client Error: Not Found for url: https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp38-cp38-manylinux1_x86_64.whl for URL https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp38-cp38-manylinux1_x86_64.whl
Traceback (most recent call last):
  File "/home/xyz/anaconda3/envs/tf2_n1/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/xyz/anaconda3/envs/tf2_n1/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1445, in main
    return cli()
  File "/home/xyz/anaconda3/envs/tf2_n1/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/xyz/anaconda3/envs/tf2_n1/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/xyz/anaconda3/envs/tf2_n1/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xyz/anaconda3/envs/tf2_n1/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xyz/anaconda3/envs/tf2_n1/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/xyz/anaconda3/envs/tf2_n1/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1404, in install_nightly
    subprocess.check_call(cmd)
  File "/home/xyz/anaconda3/envs/tf2_n1/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/xyz/anaconda3/envs/tf2_n1/bin/python3.8', '-m', 'pip', 'install', '-U', 'https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp38-cp38-manylinux1_x86_64.whl']' returned non-zero exit status 1.

**Comment by rkooo567** [comment]
Hi, there was an error in the command `install-nightly` on Ray 1.0. Please download it from the link here https://docs.ray.io/en/master/installation.html#latest-snapshots-nightlies (Use the link to download). This will be fixed in the next release (1.0.1 in a few weeks).

**Comment by viotemp1** [comment]
Yep. Download link from https://docs.ray.io/en/master/installation.html#latest-snapshots-nightlies works.
Thanks!
