### ISSUE TITLE
PicklingError in ray serve

### ISSUE THREAD

**Issue by kumarvc** [ray-project/ray#11648]
### What is the problem?
I have started exploring ray serve for model deployment and tried few ray serve examples but all are failing due to the below error.

PicklingError: Can't pickle <cyfunction _process_class.<locals>._pydantic_post_init at 0x7fc08b644ad0>: attribute lookup _pydantic_post_init on pydantic.dataclasses failed

I am using Ray version : 1.1.0 and tried running on both Linux and windows.

Request you to please suggest a way forward to resolve this issue.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

I have followed the ray serve scikit-learn example from the ray documentation
https://docs.ray.io/en/master/serve/deployment.html

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by architkulkarni** [comment]
Hi, sorry you ran into this--this should be fixed in the master branch.  Alternatively, you can also try running `pip install -U pydantic<1.7`.  Does that help?

**Comment by vivek4march** [comment]
Thanks a lot. It worked for me.

**Comment by kumarvc** [comment]
Thanks a lot. It worked for me.

**Comment by jxz542189** [comment]
don't work for me

**Comment by jxz542189** [comment]
pip install -U pydantic==1.6,but the same question

**Comment by architkulkarni** [comment]
Hi @jxz542189, did that command not fix it for you?  Are you still seeing the issue on the latest master?  It should have been fixed by https://github.com/ray-project/ray/pull/11622.

**Comment by Menniti** [comment]
Hey

Using Ray 1.0.0 I have the same issue,



```
Env: 
pydantic==1.7.1 
ray==1.0.0

Linux 16.04


import ray
from ray import serve

def printAnything():
    print("anything")

server_client = serve.start()
server_client.create_backend("iris:v1", printAnything)
```

The error is: 
```
`Traceback (most recent call last):
  File "main.py", line 53, in <module>
    server_client.create_backend("iris:v1", printAnything)
  File "/home/semantix/anaconda3/envs/arbibot/lib/python3.7/site-packages/ray/serve/api.py", line 29, in check
    return f(self, *args, **kwargs)
  File "/home/semantix/anaconda3/envs/arbibot/lib/python3.7/site-packages/ray/serve/api.py", line 246, in create_backend
    replica_config))
  File "/home/semantix/anaconda3/envs/arbibot/lib/python3.7/site-packages/ray/actor.py", line 101, in remote
    return self._remote(args, kwargs)
  File "/home/semantix/anaconda3/envs/arbibot/lib/python3.7/site-packages/ray/actor.py", line 142, in _remote
    return invocation(args, kwargs)
  File "/home/semantix/anaconda3/envs/arbibot/lib/python3.7/site-packages/ray/actor.py", line 136, in invocation
    num_returns=num_returns)
  File "/home/semantix/anaconda3/envs/arbibot/lib/python3.7/site-packages/ray/actor.py", line 793, in _actor_method_call
    list_args, name, num_returns, self._ray_actor_method_cpus)
  File "python/ray/_raylet.pyx", line 1132, in ray._raylet.CoreWorker.submit_actor_task
  File "python/ray/_raylet.pyx", line 1138, in ray._raylet.CoreWorker.submit_actor_task
  File "python/ray/_raylet.pyx", line 295, in ray._raylet.prepare_args
  File "/home/semantix/anaconda3/envs/arbibot/lib/python3.7/site-packages/ray/serialization.py", line 404, in serialize
    return self._serialize_to_msgpack(value)
  File "/home/semantix/anaconda3/envs/arbibot/lib/python3.7/site-packages/ray/serialization.py", line 384, in _serialize_to_msgpack
    self._serialize_to_pickle5(metadata, python_objects)
  File "/home/semantix/anaconda3/envs/arbibot/lib/python3.7/site-packages/ray/serialization.py", line 344, in _serialize_to_pickle5
    raise e
  File "/home/semantix/anaconda3/envs/arbibot/lib/python3.7/site-packages/ray/serialization.py", line 341, in _serialize_to_pickle5
    value, protocol=5, buffer_callback=writer.buffer_callback)
  File "/home/semantix/anaconda3/envs/arbibot/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 70, in dumps
    cp.dump(obj)
  File "/home/semantix/anaconda3/envs/arbibot/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 656, in dump
    return Pickler.dump(self, obj)
_pickle.PicklingError: Can't pickle <cyfunction _process_class.<locals>._pydantic_post_init at 0x7fb3ce585bb0>: attribute lookup _pydantic_post_init on pydantic.dataclasses failed`


```

Thanks

**Comment by Menniti** [comment]
pip install -U pydantic==1.6

Workes for me !

Thanks

**Comment by rkooo567** [comment]
@simon-mo will handle this issue alongside https://github.com/ray-project/ray/issues/11773.
