### ISSUE TITLE
[tune] Error in 'run' and not in 'debug'

### ISSUE THREAD

**Issue by erezinman** [ray-project/ray#11728]
Using Ray Tune, I get the weirdest error while training. 
This error occurs during 'run' mode, but not in 'debug'.

A MWE:
```python
from typing import Dict, Any

import pandas as pd
import ray
from ray import tune


class ModelTrainer(tune.Trainable):

    def func(self, arg: Dict[str, Any]) -> None:
        pass

ray.init()
tune.run(ModelTrainer, config={'a': 1})
```

If I either remove the annotation from `arg` or remove the `pandas` import statement, it works just fine (well, in this case it will obviously raise an error, but that's excpected). If I run the code like this in `run` mode, I get the following error:

>Traceback (most recent call last):
  File "~/optimize.py", line 14, in <module>
    tune.run(ModelTrainer, config={'a': 1})
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/tune.py", line 326, in run
    restore=restore)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/experiment.py", line 171, in __init__
    _raise_on_durable(self._run_identifier, sync_to_driver, upload_dir)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/experiment.py", line 36, in _raise_on_durable
    trainable_cls = get_trainable_cls(trainable_name)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/registry.py", line 30, in get_trainable_cls
    return _global_registry.get(TRAINABLE_CLASS, trainable_name)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/registry.py", line 140, in get
    return pickle.loads(value)
  File "/usr/local/lib/python3.6/dist-packages/ray/cloudpickle/cloudpickle_fast.py", line 434, in _class_setstate
    setattr(obj, attrname, attr)
TypeError: can't set attributes of built-in/extension type 'weakref'

I use python 3.6.9 on Ubuntu, I have `ray` v1.0.0, and pandas v0.25.3.

- [ ] I have verified my script runs in a clean environment and reproduces the issue. 
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
This is very odd... what if you move the pandas import to after you import ray?

cc @suquark

**Comment by volodymyrPivoshenko** [comment]
@erezinman Hi👋 I had a similar issue, to solve it reinstall `ray` and then run:

```shell
pip install -U ray[tune]
pip install -U ray[debug]
```

I have Python 3.6.5 and Windows 10 (Mac OS Big Sur), `ray 1.1.0`
