### ISSUE TITLE
[Rllib] Expected all tensors to be on same device. Found cuda:0 and cpu! While running ddpg with tune

### ISSUE THREAD

**Issue by gladisor** [ray-project/ray#11807]
### What is the problem?
Hi,

This is my first issue. If I am missing any information please let me know and I will add it. I am trying to test the ddpg algorithm with a simple benchmark environment CartPole-v0. If I run with config['num_gpus'] set to 0 there is no problem. However If I set it to 1 then I get the following error.

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray==1.0.0
torch==1.7.0
python 3.8.5
Ubuntu 20.04.1 LTS

### Reproduction (REQUIRED)
```
from ray import tune
from ray.rllib.agents import ddpg
config = ddpg.DEFAULT_CONFIG.copy()
config['num_workers'] = 4
config['num_gpus'] = 1
config['framework'] = 'torch'
config['env'] = "Pendulum-v0"
tune.run(
    ddpg.DDPGTrainer,
    config=config)
```

```
(pid=1189791) 2020-11-04 14:31:25,534	INFO trainer.py:616 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=1189794) /home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/rllib/utils/torch_ops.py:65: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729062494/work/torch/csrc/utils/tensor_numpy.cpp:141.)
(pid=1189794)   tensor = torch.from_numpy(np.asarray(item))
(pid=1191536) /home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/rllib/utils/torch_ops.py:65: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729062494/work/torch/csrc/utils/tensor_numpy.cpp:141.)
(pid=1191536)   tensor = torch.from_numpy(np.asarray(item))
(pid=1191538) /home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/rllib/utils/torch_ops.py:65: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729062494/work/torch/csrc/utils/tensor_numpy.cpp:141.)
(pid=1191538)   tensor = torch.from_numpy(np.asarray(item))
(pid=1191537) /home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/rllib/utils/torch_ops.py:65: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729062494/work/torch/csrc/utils/tensor_numpy.cpp:141.)
(pid=1191537)   tensor = torch.from_numpy(np.asarray(item))
2020-11-04 14:31:30,465	ERROR trial_runner.py:567 -- Trial DDPG_Pendulum-v0_535f9_00000: Error processing event.
Traceback (most recent call last):
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 515, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 488, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/worker.py", line 1428, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::DDPG.train() (pid=1189791, ip=10.0.0.12)
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 438, in ray._raylet.execute_task.function_executor
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 519, in train
    raise e
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 505, in train
    result = Trainable.train(self)
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/tune/trainable.py", line 336, in train
    result = self.step()
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 134, in step
    res = next(self.train_exec_impl)
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/util/iter.py", line 1075, in build_union
    item = next(it)
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/util/iter.py", line 791, in apply_foreach
    result = fn(item)
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/rllib/execution/train_ops.py", line 69, in __call__
    info = self.workers.local_worker().learn_on_batch(batch)
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 768, in learn_on_batch
    info_out[pid] = policy.learn_on_batch(batch)
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/rllib/policy/torch_policy.py", line 347, in learn_on_batch
    self._loss(self, self.model, self.dist_class, train_batch))
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/rllib/agents/ddpg/ddpg_torch_policy.py", line 54, in ddpg_actor_critic_loss
    policy_t = model.get_policy_output(model_out_t)
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/rllib/agents/ddpg/ddpg_torch_model.py", line 178, in get_policy_output
    return self.policy_model(model_out)
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tristan/anaconda3/envs/TSCSProject/lib/python3.8/site-packages/ray/rllib/agents/ddpg/ddpg_torch_model.py", line 93, in forward
    squashed = self.action_range * sigmoid_out + self.low_action
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by sven1977** [comment]
This DDPG specific bug should be fixed in the current master.
Could you try it out and let us know, if this is still a problem?

**Comment by sven1977** [comment]
@gladisor ^

**Comment by klm122** [comment]
Hi,

I still struggle to make ddpg work. I get the following error:
(pid=338865) ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=338880, ip=172.16.1.17)
(pid=338865) TypeError: get_distribution_inputs_and_class() missing 1 required positional argument: 'obs_batch'
(pid=338865)
(pid=338865) During handling of the above exception, another exception occurred:
(pid=338865)
(pid=338865) ray::RolloutWorker.__init__() (pid=338880, ip=172.16.1.17)
(pid=338865)   File "python/ray/_raylet.pyx", line 489, in ray._raylet.execute_task
(pid=338865)   File "python/ray/_raylet.pyx", line 496, in ray._raylet.execute_task
(pid=338865)   File "python/ray/_raylet.pyx", line 500, in ray._raylet.execute_task
(pid=338865)   File "python/ray/_raylet.pyx", line 450, in ray._raylet.execute_task.function_executor
(pid=338865)   File "/home/akoulali/.conda/envs/ray/lib/python3.7/site-packages/ray/_private/function_manager.py", line 566, in actor_method_executor
(pid=338865)     return method(__ray_actor, *args, **kwargs)
(pid=338865)   File "/home/akoulali/.conda/envs/ray/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 537, in __init__
(pid=338865)     policy_dict, policy_config)
(pid=338865)   File "/home/akoulali/.conda/envs/ray/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1196, in _build_policy_map
(pid=338865)     policy_map[name] = cls(obs_space, act_space, merged_conf)

(pid=338865)   File "/home/akoulali/.conda/envs/ray/lib/python3.7/site-packages/ray/rllib/policy/policy_template.py", line 281, in __init__
(pid=338865)     stats_fn=stats_fn,
(pid=338865)   File "/home/akoulali/.conda/envs/ray/lib/python3.7/site-packages/ray/rllib/policy/policy.py", line 623, in _initialize_loss_from_dummy_batch
(pid=338865)     self._dummy_batch, explore=False)
(pid=338865)   File "/home/akoulali/.conda/envs/ray/lib/python3.7/site-packages/ray/rllib/policy/torch_policy.py", line 262, in compute_actions_from_input_dict
(pid=338865)     seq_lens, explore, timestep)
(pid=338865)   File "/home/akoulali/.conda/envs/ray/lib/python3.7/site-packages/ray/rllib/utils/threading.py", line 21, in wrapper
(pid=338865)     return func(self, *a, **k)
(pid=338865)   File "/home/akoulali/.conda/envs/ray/lib/python3.7/site-packages/ray/rllib/policy/torch_policy.py", line 320, in _compute_action_helper
(pid=338865)     is_training=False)
(pid=338865)   File "/home/akoulali/.conda/envs/ray/lib/python3.7/site-packages/ray/rllib/agents/ddpg/ddpg_tf_policy.py", line 104, in get_distribution_inputs_and_class
(pid=338865)     dist_inputs = model.get_policy_output(model_out)
(pid=338865)   File "/home/akoulali/.conda/envs/ray/lib/python3.7/site-packages/ray/rllib/agents/ddpg/ddpg_torch_model.py", line 192, in get_policy_output
(pid=338865)     return self.policy_model(model_out)
(pid=338865)   File "/home/akoulali/.conda/envs/ray/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
(pid=338865)     result = self.forward(*input, **kwargs)
(pid=338865)   File "/home/akoulali/.conda/envs/ray/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
(pid=338865)     input = module(input)
(pid=338865)   File "/home/akoulali/.conda/envs/ray/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
(pid=338865)     result = self.forward(*input, **kwargs)
(pid=338865)   File "/home/akoulali/.conda/envs/ray/lib/python3.7/site-packages/ray/rllib/agents/ddpg/ddpg_torch_model.py", line 105, in forward
(pid=338865)     squashed = self.action_range * sigmoid_out + self.low_action
(pid=338865) RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Traceback (most recent call last):
  File "caching20.py", line 298, in <module>
    checkpoint_path, results, lr, fc_hid, fc_act = exper.train(args.run)
  File "caching20.py", line 167, in train
    checkpoint_at_end=True)
  File "/home/akoulali/.conda/envs/ray/lib/python3.7/site-packages/ray/tune/tune.py", line 543, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [DDPG_caching-v020_aeeda_00000, DDPG_caching-v020_aeeda_00001, DDPG_caching-v020_aeeda_00002, DDPG_caching-v020_aeeda_00003, DDPG_caching-v020_aeeda_00004, DDPG_caching-v020_aeeda_00005, DDPG_caching-v020_aeeda_00006, DDPG_caching-v020_aeeda_00007])

**Comment by kevduong1** [comment]
@klm122 Did you ever figure out the issue? I am also running into the same issue using a custom policy with the custom action_distribution_fn. I'm using the procgen environment and for some reason ray.tune isn't passing in my observation to this function.

  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_gpu/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 890, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_gpu/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 788, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_gpu/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_gpu/lib/python3.8/site-packages/ray/worker.py", line 1627, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::Hyperbolic_DQN.__init__() (pid=5265, ip=192.168.1.75)
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_gpu/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 137, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_gpu/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 623, in __init__
    super().__init__(config, logger_creator)
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_gpu/lib/python3.8/site-packages/ray/tune/trainable.py", line 107, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_gpu/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 147, in setup
    super().setup(config)
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_gpu/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 776, in setup
    self._init(self.config, self.env_creator)
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_gpu/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 171, in _init
    self.workers = self._make_workers(
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_gpu/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 858, in _make_workers
    return WorkerSet(
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_gpu/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 87, in __init__
    remote_spaces = ray.get(self.remote_workers(
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=5266, ip=192.168.1.75)
TypeError: custom_get_distribution_inputs_and_class() missing 1 required positional argument: 'obs_batch'

**Comment by klm122** [comment]
Hi,

Unfortnetly, I gave up and switched to another implementation of ddpg.

Best regards

**Comment by alexvaca0** [comment]
Hi, I'm running into a similar issue when trying to use PPO, ray 2.0.0.dev0 and python 3.8, on a windows 10 machine...

**Comment by awarebayes** [comment]
> Hi, I'm running into a similar issue when trying to use PPO, ray 2.0.0.dev0 and python 3.8, on a windows 10 machine...

Same thing...

**Comment by evo11x** [comment]
same error here with ray 1.10, windows 11, python 3.9
it works with tf, but with tf2 it uses 5 times more memory and the computer is blocking

**Comment by NicoleRichards1998** [comment]
Did anyone find a solution to this problem? I'm running into the same error with the DDPG trainer. I need to use tf2 for my LSTM network to work, so I definitely cannot change to tf2. The code I'm using works perfectly with the PPO trainer as well as the A2C trainer.
