### ISSUE TITLE
_fill_function() missing 1 required positional argument: 'closure_values'

### ISSUE THREAD

**Issue by lopsided** [ray-project/ray#1181]
Hi, 

When I try to run the example on the bottom of this page: http://ray.readthedocs.io/en/latest/using-ray-on-a-cluster.html to check my cluster is running I keep getting loads of errors. 

I'm using 2 machines which are connected by a lan switch box. Both machines running fedora 26 and Python 3.6. I've built ray from source on both machines and the tests seem to pass on both fine. When I run without trying to connect to the cluster it works fine (ie, just with `ray.init()`). I've tested starting each box as the head, tested running the driver script from both sides and I've entirely disabled the firewall on both machines. Nothing seems to work.

````
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1553, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
TypeError: _fill_function() takes 5 positional arguments but 6 were given


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1553, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
TypeError: _fill_function() takes 5 positional arguments but 6 were given


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1553, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
TypeError: _fill_function() takes 5 positional arguments but 6 were given


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1553, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
TypeError: _fill_function() takes 5 positional arguments but 6 were given


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1553, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
TypeError: _fill_function() takes 5 positional arguments but 6 were given


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1553, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
TypeError: _fill_function() takes 5 positional arguments but 6 were given


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1553, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
TypeError: _fill_function() takes 5 positional arguments but 6 were given


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1553, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
TypeError: _fill_function() takes 5 positional arguments but 6 were given


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1523, in fetch_and_register_remote_function
    function = pickle.loads(serialized_function)
TypeError: _fill_function() takes 5 positional arguments but 6 were given


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Remote function __main__.f failed with:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1515, in <lambda>
    remote_f_placeholder = remote(function_id=function_id)(lambda *xs: f())
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1514, in f
    raise Exception("This function was not imported properly.")
Exception: This function was not imported properly.


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1553, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
TypeError: _fill_function() missing 1 required positional argument: 'closure_values'


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1553, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
TypeError: _fill_function() missing 1 required positional argument: 'closure_values'


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1553, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
TypeError: _fill_function() missing 1 required positional argument: 'closure_values'


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1553, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
TypeError: _fill_function() missing 1 required positional argument: 'closure_values'


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1553, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
TypeError: _fill_function() missing 1 required positional argument: 'closure_values'


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1553, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
TypeError: _fill_function() missing 1 required positional argument: 'closure_values'


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1553, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
TypeError: _fill_function() missing 1 required positional argument: 'closure_values'


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1553, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
TypeError: _fill_function() missing 1 required positional argument: 'closure_values'


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1553, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
TypeError: _fill_function() missing 1 required positional argument: 'closure_values'


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.33.101:6379")
  
Traceback (most recent call last):
  File "/var/projects/ray-tests/1_ray_test.py", line 15, in <module>
    print(set(ray.get([f.remote() for _ in range(10)])))
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 2137, in get
    raise RayGetError(object_ids[i], value)
ray.worker.RayGetError: Could not get objectid ObjectID(5ea673890c439d59dec057cd8cfae0030854c6d8). It was created by remote function __main__.f which failed with:

Remote function __main__.f failed with:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1515, in <lambda>
    remote_f_placeholder = remote(function_id=function_id)(lambda *xs: f())
  File "/usr/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 1514, in f
    raise Exception("This function was not imported properly.")
Exception: This function was not imported properly.


Process finished with exit code 1
````

I've been through the docs a bunch of times but can't figure it out. Apologies if this is actually a support request but I thought it might be a py3.6 compatibility issue?

**Comment by robertnishihara** [comment]
What versions of cloudpickle are running on the two machines?

**Comment by robertnishihara** [comment]
Is there any chance the workers are using different versions of cloudpickle (or of Python)? Can you check?

**Comment by lopsided** [comment]
It seems cloudpickle was the problem! I was running 0.4.0 on one and 0.4.1 on the other. When I upgraded both to 0.4.1 it seems to work - at least with the test script. 

Thanks for your suggestion!

**Comment by lopsided** [comment]
(Both machines are running python 3.6.2 too btw)

**Comment by robertnishihara** [comment]
Ok great! In principle we could check for this automatically and print a warning.. (also if different Python versions or different Ray version are being used). Tracking that at #1183.
