### ISSUE TITLE
[Tune] PermissionError: [Errno 13] Permission denied: '/home/labuser' when running a cluster 

### ISSUE THREAD

**Issue by TommasoBendinelli** [ray-project/ray#11836]
I am trying to run a cluster of two nodes. Separetely they work fine, but if I am starting them together I am getting this error on both computers.

I am using ray 1.0.0 on Python 3.8.5 on both machines. Seems related to this #4326, but I am using an updated version

2020-11-05 18:07:24,485 ERROR trial_runner.py:567 -- Trial DEFAULT_5eddadab: Error processing event.
Traceback (most recent call last):
  File "/home/labuser/.pyenv/versions/env/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 515, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/labuser/.pyenv/versions/env/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 488, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/labuser/.pyenv/versions/env/lib/python3.8/site-packages/ray/worker.py", line 1428, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(PermissionError): ray::ImplicitFunc.train() (pid=127521, ip=138.131.217.158)
  File "python/ray/_raylet.pyx", line 445, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 479, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 483, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 438, in ray._raylet.execute_task.function_executor
  File "/home/tommaso/repos/gemintelligence/env/lib/python3.8/site-packages/ray/tune/trainable.py", line 228, in __init__
    self._create_logger(self.config, logger_creator)
  File "/home/tommaso/repos/gemintelligence/env/lib/python3.8/site-packages/ray/tune/trainable.py", line 579, in _create_logger
    self._result_logger = logger_creator(config)
  File "/home/tommaso/repos/gemintelligence/env/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 128, in noop_logger_creator
    os.makedirs(logdir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/labuser'

**Comment by rkooo567** [comment]
cc @richardliaw

**Comment by richardliaw** [comment]
Can you make sure `/home/labuser` is an accessible folder on all machines?

**Comment by TommasoBendinelli** [comment]
Thank you for the answer, how can ensure that? Do I need to change the folder permission?

**Comment by richardliaw** [comment]
I think you could try something like `touch /home/labuser/marker.log` on each machine?

**Comment by TommasoBendinelli** [comment]
So I tried `touch /home/labuser/marker.log` on one machine and `touch /home/tommaso/marker.log` on the other. I tried to start to run again the cluster. Note that on the two computer the users name are different

**Comment by richardliaw** [comment]
Could you get the same absolute path for both machines?

**Comment by TommasoBendinelli** [comment]
Okey, a news from my side. on the labuser computer I created folder called tommaso in the home filesystem. Now I can bypass the error. So I guess that each node must have the same user and same paths

**Comment by TommasoBendinelli** [comment]
The thing, is that I am not an admin on a computer, so in general I am forced to use different users

**Comment by richardliaw** [comment]
Hmm, do you have a /work or /tmp that you can access?

**Comment by TommasoBendinelli** [comment]
I have a personal computer with one GPU, where I have a user called tommaso, and then I can access to this computer where I have access to the path /home/labuser. I cannot really do anything that is outside this labuser folder or sudo related

**Comment by TommasoBendinelli** [comment]
I have access to tmp/, so I can place everything there. Actually I think the best would be having an NFS server accessible from all nodes and configure the logging path there

**Comment by richardliaw** [comment]
Yeah, that sounds good. I'll close this issue for now, as I think this is resolved.

**Comment by mickelliu** [comment]
Hi @richardliaw, I encountered a similar while I was configuring my local cluster. As per the user rules of my lab, I was not given `sudo` permission for the machines that I am using. Therefore, this solution (of creating specific folders) would not work for me. I don't think #4326 had worked for me either, unfortunately...

**Comment by mickelliu** [comment]
I used the `run_experiment` API by the way, it seems to me that the address for `local_dir` is set fixed when the `Experiment` object is generated and then pass to remote workers (within the same cluster but different machines).
