### ISSUE TITLE
[autoscaler] Ray cluster start / re-start fails under certain conditions

### ISSUE THREAD

**Issue by waldroje** [ray-project/ray#11833]
### What is the problem?
When restarting a cluster, and -` ray stop; ray start` are executed, it seems to create a race condition and often fails indicating ray is already running... rectified for now by putting - sleep 5 in between, but maybe better way to handle that.
```
Traceback (most recent call last):
  File "/home/svc-tai-dev/virt/algo_37/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/svc-tai-dev/virt/algo_37/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1470, in main
    return cli()
  File "/home/svc-tai-dev/virt/algo_37/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/svc-tai-dev/virt/algo_37/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/svc-tai-dev/virt/algo_37/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/svc-tai-dev/virt/algo_37/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/svc-tai-dev/virt/algo_37/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/svc-tai-dev/virt/algo_37/lib/python3.7/site-packages/ray/scripts/scripts.py", line 521, in start
    f"Ray is already running at {default_address}. "
ConnectionError: Ray is already running at xx.xx.xx.xx:6379. Please specify a different port using the `--port` command to `ray start`.
Shared connection to 127.0.0.1 closed.
2020-11-04 15:10:31,107 INFO node_provider.py:93 -- ClusterState: Writing cluster state: ['localhost']
  New status: update-failed
  !!!
  SSH command failed.
  !!!
  Failed to setup head node.
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray latest .whl, Python 3.7, TF 2.3, RHEL 7.8

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
@waldroje This must've been resolved in the nightly. Can you try? https://github.com/ray-project/ray/pull/11735
