### ISSUE TITLE
[cli] Bad Error if `ray start` on worker before the head node is up

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#11843]
We get this terrible non-descript error message:

```
Traceback (most recent call last):
  File "/usr/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/ray/scripts/scripts.py", line 1445, in main
    return cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/ray/scripts/scripts.py", line 579, in start
    ray_params, head=False, shutdown_at_exit=block, spawn_reaper=block)
  File "/usr/lib/python3.6/site-packages/ray/node.py", line 142, in __init__
    redis_client.get("session_name"))
  File "/usr/lib/python3.6/site-packages/ray/utils.py", line 221, in decode
    raise ValueError(f"The argument {byte_str} must be a bytes object.")
ValueError: The argument None must be a bytes object.
```

cc @tgaddair @rkooo567

**Comment by richardliaw** [comment]
Actually, on `master`, I get the following error when trying to connect on an unready head:

```
ubuntu@ip-172-31-58-131:~$ ray start --address='172.31.48.39:6379' --redis-password='5241590000000000' --block
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1470, in main
    return cli()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 595, in start
    redis_address_ip, redis_address_port, password=redis_password)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 566, in wait_for_redis_to_start
    raise RuntimeError("Unable to connect to Redis. If the Redis instance "
RuntimeError: Unable to connect to Redis. If the Redis instance is on a different machine, check that your firewall is configured properly.
```

**Comment by richardliaw** [comment]
Actually, this is a duplicate of #5119 .

**Comment by zhaoyaqia** [comment]
> Actually, on `master`, I get the following error when trying to connect on an unready head:
> 
> ```
> ubuntu@ip-172-31-58-131:~$ ray start --address='172.31.48.39:6379' --redis-password='5241590000000000' --block
> Traceback (most recent call last):
>   File "/home/ubuntu/anaconda3/bin/ray", line 8, in <module>
>     sys.exit(main())
>   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1470, in main
>     return cli()
>   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 595, in start
>     redis_address_ip, redis_address_port, password=redis_password)
>   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 566, in wait_for_redis_to_start
>     raise RuntimeError("Unable to connect to Redis. If the Redis instance "
> RuntimeError: Unable to connect to Redis. If the Redis instance is on a different machine, check that your firewall is configured properly.
> ```

Hello,I have this problem too.
How did you solve it?
