### ISSUE TITLE
[autoscaler] Error: no such option: --webui-host

### ISSUE THREAD

**Issue by lisawhite137** [ray-project/ray#11851]
When I used this [example](https://docs.ray.io/en/latest/cluster/launcher.html#launching-a-cluster-ray-up), the following error occurred.

```
2020-11-04 15:21:19,091	INFO command_runner.py:242 -- NodeUpdater: ray-head-2k2px: Running kubectl -n ray exec -it ray-head-2k2px -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (ulimit -n 65536; ray start --head --num-cpus=$MY_CPU_REQUEST --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --webui-host 0.0.0.0)'
Usage: ray start [OPTIONS]
Try 'ray start --help' for help.

Error: no such option: --webui-host
command terminated with exit code 2
2020-11-04 15:21:20,219	INFO log_timer.py:27 -- NodeUpdater: ray-head-2k2px: Ray start commands failed [LogTimer=2234ms]
2020-11-04 15:21:20,220	INFO log_timer.py:27 -- NodeUpdater: ray-head-2k2px: Applied config 9218e59bf570d9c673732a8396c5888871bec064  [LogTimer=8874ms]
2020-11-04 15:21:20,235	ERROR updater.py:125 -- NodeUpdater: ray-head-2k2px: Error executing: (Exit Status 2) k u b e c t l   - n   r a y   e x e c   - i t   r a y - h e a d - 2 k 2 p x   - -   b a s h   - - l o g i n   - c   - i   ' t r u e   & &   s o u r c e   ~ / . b a s h r c   & &   e x p o r t   O M P _ N U M _ T H R E A D S = 1   P Y T H O N W A R N I N G S = i g n o r e   & &   ( u l i m i t   - n   6 5 5 3 6 ;   r a y   s t a r t   - - h e a d   - - n u m - c p u s = $ M Y _ C P U _ R E Q U E S T   - - p o r t = 6 3 7 9   - - o b j e c t - m a n a g e r - p o r t = 8 0 7 6   - - a u t o s c a l i n g - c o n f i g = ~ / r a y _ b o o t s t r a p _ c o n f i g . y a m l   - - w e b u i - h o s t   0 . 0 . 0 . 0 ) '
```

Origin log as follow:
```
Cluster: ray-dev
2020-11-04 15:21:09,678	INFO commands.py:206 -- Using cached config at /tmp/ray-config-2468ff383a49c013bb6765cb1d01ca88f0da9fdf
This will create a new cluster [y/N]: y
2020-11-04 15:21:11,325	INFO commands.py:580 -- get_or_create_head_node: Launching new head node...
2020-11-04 15:21:11,325	INFO node_provider.py:87 -- KubernetesNodeProvider: calling create_namespaced_pod (count=1).
2020-11-04 15:21:11,344	INFO commands.py:619 -- get_or_create_head_node: Updating files on head node...
2020-11-04 15:21:11,346	INFO updater.py:98 -- NodeUpdater: ray-head-2k2px: Updating to 9218e59bf570d9c673732a8396c5888871bec064
2020-11-04 15:21:11,359	INFO updater.py:222 -- NodeUpdater: ray-head-2k2px: Waiting for remote shell...
2020-11-04 15:21:11,366	INFO command_runner.py:242 -- NodeUpdater: ray-head-2k2px: Running kubectl -n ray exec -it ray-head-2k2px -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
2020-11-04 15:21:16,593	INFO command_runner.py:242 -- NodeUpdater: ray-head-2k2px: Running kubectl -n ray exec -it ray-head-2k2px -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
 07:21:17 up 21 days, 18:53,  0 users,  load average: 1.28, 1.53, 1.53
2020-11-04 15:21:17,124	INFO log_timer.py:27 -- NodeUpdater: ray-head-2k2px: Got remote shell  [LogTimer=5765ms]
2020-11-04 15:21:17,154	INFO command_runner.py:242 -- NodeUpdater: ray-head-2k2px: Running kubectl -n ray exec -it ray-head-2k2px -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (mkdir -p ~)'
2020-11-04 15:21:17,563	INFO updater.py:420 -- NodeUpdater: ray-head-2k2px: Syncing /tmp/ray-bootstrap-w04yzgs1 to ~/ray_bootstrap_config.yaml...
sending incremental file list
ray-bootstrap-w04yzgs1

sent 1,254 bytes  received 35 bytes  2,578.00 bytes/sec
total size is 3,729  speedup is 2.89
2020-11-04 15:21:17,948	INFO log_timer.py:27 -- NodeUpdater: ray-head-2k2px: Synced /tmp/ray-bootstrap-w04yzgs1 to ~/ray_bootstrap_config.yaml  [LogTimer=794ms]
2020-11-04 15:21:17,985	INFO command_runner.py:242 -- NodeUpdater: ray-head-2k2px: Running kubectl -n ray exec -it ray-head-2k2px -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (ray stop)'
Did not find any active Ray processes.
2020-11-04 15:21:19,091	INFO command_runner.py:242 -- NodeUpdater: ray-head-2k2px: Running kubectl -n ray exec -it ray-head-2k2px -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (ulimit -n 65536; ray start --head --num-cpus=$MY_CPU_REQUEST --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --webui-host 0.0.0.0)'
Usage: ray start [OPTIONS]
Try 'ray start --help' for help.

Error: no such option: --webui-host
command terminated with exit code 2
2020-11-04 15:21:20,219	INFO log_timer.py:27 -- NodeUpdater: ray-head-2k2px: Ray start commands failed [LogTimer=2234ms]
2020-11-04 15:21:20,220	INFO log_timer.py:27 -- NodeUpdater: ray-head-2k2px: Applied config 9218e59bf570d9c673732a8396c5888871bec064  [LogTimer=8874ms]
2020-11-04 15:21:20,235	ERROR updater.py:125 -- NodeUpdater: ray-head-2k2px: Error executing: (Exit Status 2) k u b e c t l   - n   r a y   e x e c   - i t   r a y - h e a d - 2 k 2 p x   - -   b a s h   - - l o g i n   - c   - i   ' t r u e   & &   s o u r c e   ~ / . b a s h r c   & &   e x p o r t   O M P _ N U M _ T H R E A D S = 1   P Y T H O N W A R N I N G S = i g n o r e   & &   ( u l i m i t   - n   6 5 5 3 6 ;   r a y   s t a r t   - - h e a d   - - n u m - c p u s = $ M Y _ C P U _ R E Q U E S T   - - p o r t = 6 3 7 9   - - o b j e c t - m a n a g e r - p o r t = 8 0 7 6   - - a u t o s c a l i n g - c o n f i g = ~ / r a y _ b o o t s t r a p _ c o n f i g . y a m l   - - w e b u i - h o s t   0 . 0 . 0 . 0 ) '

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/nfs/users/ting.wu/py36-venv/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 113, in run
    self.do_update()
  File "/nfs/users/ting.wu/py36-venv/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 409, in do_update
    run_env="auto")
  File "/nfs/users/ting.wu/py36-venv/lib/python3.6/site-packages/ray/autoscaler/command_runner.py", line 248, in run
    self.process_runner.check_call(final_cmd, shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'kubectl -n ray exec -it ray-head-2k2px -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (ulimit -n 65536; ray start --head --num-cpus=$MY_CPU_REQUEST --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --webui-host 0.

0.0.0)'' returned non-zero exit status 2.

2020-11-04 15:21:20,256	ERROR commands.py:701 -- get_or_create_head_node: Updating 20.xxx.3.48 failed
```

Ray version: 1.0.0
Kubectl version: 1.19.3

### Reproduction (REQUIRED)
```bash
ray up ray/python/ray/autoscaler/kubernetes/example-full.yaml
```

- [☑️] I have verified my script runs in a clean environment and reproduces the issue.
- [☑️] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by lisawhite137** [comment]
some one already fixed it before 24days.
