### ISSUE TITLE
[Autoscaler] Worker Node Type's `max_workers` is not validated

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#11900]
### What is the problem?
Ray 1.0.1

I forgot to fill out the `max_workers` for my worker node type. The yaml passed validation and cluster launched. But autoscaler crashed when i'm trying to scale up the cluster.

```2020-11-09 18:52:07,384	WARNING worker.py:1091 -- The monitor failed with the following error:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 389, in <module>
    monitor.run()
  File "/root/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 334, in run
    self._run()
  File "/root/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 289, in _run
    self.autoscaler.update()
  File "/root/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 139, in update
    raise e
  File "/root/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 128, in update
    self._update()
  File "/root/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 221, in _update
    pending_placement_groups)
  File "/root/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/resource_demand_scheduler.py", line 100, in get_nodes_to_launch
    self.node_types, node_type_counts, max_to_add, unfulfilled)
  File "/root/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/resource_demand_scheduler.py", line 377, in get_nodes_for
    node_type, 0) >= node_types[node_type]["max_workers"]):
KeyError: 'max_workers'
```

**Comment by simon-mo** [comment]
cc @ray-project/ray-autoscaler

**Comment by AmeerHajAli** [comment]
can you please provide the yaml you used?
This should he been auto filed by the defaults.yaml.

**Comment by simon-mo** [comment]
Hi @AmeerHajAli, same yaml here: https://github.com/ray-project/ray/pull/11905#issuecomment-724461100

**Comment by AmeerHajAli** [comment]
should be fixed here:
https://github.com/ray-project/ray/pull/11802
