### ISSUE TITLE
[tune] tune fails with deeply-nested configs due to `unflatten_dict`

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#11947]
### What is the problem?
Tune fails when using >2 levels deep configs.

*Ray version and other system information (Python version, TensorFlow version, OS):* 543f7809a6e8

### Reproduction (REQUIRED)
Add deeply-nested value, such as `"a": {"b": {"c": {"d": tune.choice([1, 2])}}}` to the BOHB config here:: https://github.com/ray-project/ray/blob/396ae0b7c2af310cffdd078570893fc87173eb93/python/ray/tune/examples/bohb_example.py#L53

Then run `python ./python/ray/tune/examples/bohb_example.py`. It fails with:

```
$ python ./python/ray/tune/examples/bohb_example.py
File descriptor limit 256 is too low for production servers and may result in connection errors. At least 8192 is recommended. --- Fix with 'ulimit -n 8192'
2020-11-11 20:38:44,944 INFO services.py:1110 -- View the Ray dashboard at http://127.0.0.1:8265
Traceback (most recent call last):
  File "./python/ray/tune/examples/bohb_example.py", line 87, in <module>
    stop={"training_iteration": 100})
  File "/Users/hartikainen/github/ray-project/ray/python/ray/tune/tune.py", line 416, in run
    runner.step()
  File "/Users/hartikainen/github/ray-project/ray/python/ray/tune/trial_runner.py", line 380, in step
    next_trial = self._get_next_trial()  # blocking
  File "/Users/hartikainen/github/ray-project/ray/python/ray/tune/trial_runner.py", line 479, in _get_next_trial
    self._update_trial_queue(blocking=wait_for_trial)
  File "/Users/hartikainen/github/ray-project/ray/python/ray/tune/trial_runner.py", line 855, in _update_trial_queue
    trial = self._search_alg.next_trial()
  File "/Users/hartikainen/github/ray-project/ray/python/ray/tune/suggest/search_generator.py", line 114, in next_trial
    self._experiment.dir_name)
  File "/Users/hartikainen/github/ray-project/ray/python/ray/tune/suggest/search_generator.py", line 121, in create_trial_if_possible
    suggested_config = self.searcher.suggest(trial_id)
  File "/Users/hartikainen/github/ray-project/ray/python/ray/tune/suggest/bohb.py", line 175, in suggest
    return unflatten_dict(config)
  File "/Users/hartikainen/github/ray-project/ray/python/ray/tune/utils/util.py", line 276, in unflatten_dict
    item = item[k]
KeyError: 'b'
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment]
Thanks for this issue, I'll look into this tomorrow.

**Comment by krfricke** [comment]
Awesome, thanks for the PR. We'll merge it once the tests pass
