### ISSUE TITLE
[rllib] Out of (GPU) memory when trying to initialise a PPOTrainer

### ISSUE THREAD

**Issue by zawaki** [ray-project/ray#11969]
I am unable to run the simple cart-pole demo:

```python
import ray
import ray.rllib.agents.ppo as ppo

config = ppo.DEFAULT_CONFIG.copy()

trainer = ppo.PPOTrainer(config=config, env="CartPole-v0")
```

However, I am able to use PPO in the context of tune - i.e. the following code runs fine:

```python
import ray
from ray.rllib.agents.ppo import PPOTrainer

ray.tune.run(PPOTrainer, config={"env": "CartPole-v0"})
```

The first instance crashes with the following output:

```
Traceback (most recent call last):
  File "checkpoint_load_test.py", line 8, in <module>
    trainer = ppo.PPOTrainer(config=config, env="CartPole-v0")
  File "/home/uceezs0/.conda/envs/dgl_5/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 88, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/uceezs0/.conda/envs/dgl_5/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 479, in __init__
    super().__init__(config, logger_creator)
  File "/home/uceezs0/.conda/envs/dgl_5/lib/python3.6/site-packages/ray/tune/trainable.py", line 245, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/uceezs0/.conda/envs/dgl_5/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 643, in setup
    self._init(self.config, self.env_creator)
  File "/home/uceezs0/.conda/envs/dgl_5/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 102, in _init
    env_creator, self._policy, config, self.config["num_workers"])
  File "/home/uceezs0/.conda/envs/dgl_5/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 713, in _make_workers
    logdir=self.logdir)
  File "/home/uceezs0/.conda/envs/dgl_5/lib/python3.6/site-packages/ray/rllib/evaluation/worker_set.py", line 67, in __init__
    RolloutWorker, env_creator, policy, 0, self._local_config)
  File "/home/uceezs0/.conda/envs/dgl_5/lib/python3.6/site-packages/ray/rllib/evaluation/worker_set.py", line 296, in _make_worker
    extra_python_environs=extra_python_environs)
  File "/home/uceezs0/.conda/envs/dgl_5/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 393, in __init__
    self.tf_sess = tf_session_creator()
  File "/home/uceezs0/.conda/envs/dgl_5/lib/python3.6/site-packages/ray/rllib/evaluation/worker_set.py", line 206, in session_creator
    config=tf1.ConfigProto(**config["tf_session_args"]))
  File "/home/uceezs0/.conda/envs/dgl_5/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1586, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/uceezs0/.conda/envs/dgl_5/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 701, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: out of memory
```

For reference, the context of this problem is that I would like to load a checkpoint from a custom custom environment trained using a custom TF model (which can be trained without error using ```tune.run```). However I am currently not able to do this due to PPOTrainer instantiation crashing, which does not appear to be specific to me custom model since it happens with ```CartPole-v0```.

**Comment by michaelzhiluo** [comment]
This is an issue mostly likely to do with your machine. Check your CUDA and Cudnn versions.
