### ISSUE TITLE
[CLI] restart-only Fails to start head-node

### ISSUE THREAD

**Issue by richardrl** [ray-project/ray#12007]
I run this command, applied to an already-started cluster:
`(ray1.1.dev0) richard@richard-desktop:~$ ray up --restart-only /home/richard/code/ray_config/aws_spot_cluster_gpu_ray1.1dev0.yaml
`

and get this output:
```
Shared connection to 3.236.155.241 closed.
  [4/6] No setup commands to run.
  [6/6] Starting the Ray runtime
Stopped all 10 Ray processes.
Shared connection to 3.236.155.241 closed.
Did not find any active Ray processes.
Shared connection to 3.236.155.241 closed.
Local node IP: 10.0.0.72
Traceback (most recent call last):
  File "/opt/conda/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1470, in main
    return cli()
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ray/scripts/scripts.py", line 521, in start
    f"Ray is already running at {default_address}. "
ConnectionError: Ray is already running at 10.0.0.72:6379. Please specify a different port using the `--port` command to `ray start`.
Shared connection to 3.236.155.241 closed.
  New status: update-failed
  !!!
  SSH command failed.
  !!!
  
  Failed to setup head node.
```

I don't think this should fail just because Ray is already running/

**Comment by richardrl** [comment]
It seems to work after waiting for a while and trying the command again.

**Comment by rkooo567** [comment]
I feel like restart-only command is currently not so stable. We should probably add some tests there. cc @richardliaw @wuisawesome

**Comment by richardliaw** [comment]
I think it might actually be `ray stop` is not so stable.
