### ISSUE TITLE
Verbose messages about new dashboard

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#12049]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 1.1dev, installed from source

Anaconda Python 3.6.10, Ubuntu 18.04

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

Whenever I run Ray, I see this output like this repeatedly on stdout:
```
(pid=raylet) Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x7fc9c53df648>>
(pid=raylet) Traceback (most recent call last):
(pid=raylet)   File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/site-packages/aiohttp-4.0.0a1-py3.6-linux-x86_64.egg/aiohttp/client.py", line 269, in __del__
(pid=raylet)     if not self.closed:
(pid=raylet)   File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/site-packages/aiohttp-4.0.0a1-py3.6-linux-x86_64.egg/aiohttp/client.py", line 894, in closed
(pid=raylet)     return self._connector is None or self._connector.closed
(pid=raylet) AttributeError: _connector
(pid=raylet) Traceback (most recent call last):
(pid=raylet)   File "/home/swang/ray/python/ray/new_dashboard/agent.py", line 308, in <module>
(pid=raylet)     raise e
(pid=raylet)   File "/home/swang/ray/python/ray/new_dashboard/agent.py", line 298, in <module>
(pid=raylet)     loop.run_until_complete(agent.run())
(pid=raylet)   File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
(pid=raylet)     return future.result()
(pid=raylet)   File "/home/swang/ray/python/ray/new_dashboard/agent.py", line 118, in run
(pid=raylet)     loop=asyncio.get_event_loop())
(pid=raylet) TypeError: __init__() got an unexpected keyword argument 'loop'
2020-11-16 16:39:46,626 WARNING worker.py:1112 -- The agent on node swang-X1-Carbon failed with the following error:
Traceback (most recent call last):
  File "/home/swang/ray/python/ray/new_dashboard/agent.py", line 298, in <module>
    loop.run_until_complete(agent.run())
  File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/home/swang/ray/python/ray/new_dashboard/agent.py", line 118, in run
    loop=asyncio.get_event_loop())
TypeError: __init__() got an unexpected keyword argument 'loop'
```

**Comment by stephanie-wang** [comment]
Looks like this was because I had aiohttp==4.0.0a1. I no longer saw the messages after pinning to aiohttp==3.6.
