### ISSUE TITLE
Example cluster yaml configuration is broken.

### ISSUE THREAD

**Issue by aced125** [ray-project/ray#12077]
https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/aws/example-full.yaml#L16

`ray up example-full.yaml` yields

```
Traceback (most recent call last):
  File "/home/laksh/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/laksh/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1468, in main
    return cli()
  File "/home/laksh/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/laksh/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/laksh/anaconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/laksh/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/laksh/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/laksh/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 861, in up
    use_login_shells=use_login_shells)
  File "/home/laksh/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 211, in create_or_update_cluster
    config = _bootstrap_config(config, no_config_cache=no_config_cache)
  File "/home/laksh/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 262, in _bootstrap_config
    validate_config(config)
  File "/home/laksh/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/util.py", line 63, in validate_config
    raise e from None
  File "/home/laksh/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/util.py", line 61, in validate_config
    jsonschema.validate(config, schema)
  File "/home/laksh/anaconda3/lib/python3.7/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('upscaling_speed' was unexpected)
```

Deleting line 16 fixes everything.

**Comment by richardliaw** [comment]
Can you try upgrading your ray to the latest nightly version?

**Comment by aced125** [comment]
How do I do that? Also shouldn't the docs be stable?

**Comment by ericl** [comment]
To see the stable docs, click the version tab on readthedocs to select the version.

(note that github links always point to master, you'll have to see the release branch).
