### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by kocmurat93** [ray-project/ray#12112]
Hi , 
I installed ray on Python 3.7.5 . ı imported ray , when i runned the code ı got error that i wrote below. How can i solve this error ? 
```
Traceback (most recent call last):
  File "C:/Users/user2/Desktop/Projects/DF_PoC_Dev/src/test_ray.py", line 1, in <module>
    import ray
  File "C:\Users\user2\.conda\envs\demand_forecasting\lib\site-packages\ray\__init__.py", line 61, in <module>
    CDLL(so_path, ctypes.RTLD_GLOBAL)
  File "C:\Users\user2\.conda\envs\demand_forecasting\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```
I have been working on Windows Server 2016.

**Comment by kocmurat93** [comment]
++++

**Comment by amogkam** [comment]
cc @mehrdadn

**Comment by mehrdadn** [comment]
@amogkam Sounds like a shared library dependency of the raylet isn't being found. I'm not sure what it might be though... someone will have to debug it.

**Comment by 4ever-Rain** [comment]
got the same error with Python3.7.9 on Windows10

**Comment by mehrdadn** [comment]
Oh yes!! If you haven't [installed the VC++ runtime](hhttps://docs.ray.io/en/latest/installation.html#windows-support) then that might very well be it. I just assumed that was already done, but if not, please do try that @kocmurat93.

**Comment by sheganinans** [comment]
I'm getting this error even with the VC runtime installed.

I heard there is a way to get this installed with Anaconda than the terminal, would that be recommended?

**Comment by mehrdadn** [comment]
@sheganinans Does it run fine on any non-Anaconda Python on the same machine? What version of Ray and Python are you running?

**Comment by sheganinans** [comment]
@mehrdadn No it does not, currently I'm trying: 

`pip3.7.exe install .\Downloads\ray-2.0.0.dev0-cp37-cp37m-win_amd64.whl`


Here's the error:

```
PS C:\Users\Ace> python3.7.exe
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 16:30:00) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> import ray.rllib.agents.ppo as ppo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Ace\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\ray\rllib\__init__.py", line 9, in <module>
    from ray.rllib.evaluation.rollout_worker import RolloutWorker
  File "C:\Users\Ace\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\ray\rllib\evaluation\__init__.py", line 6, in <module>
    from ray.rllib.evaluation.postprocessing import compute_advantages
  File "C:\Users\Ace\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\ray\rllib\evaluation\postprocessing.py", line 2, in <module>
    import scipy.signal
  File "C:\Users\Ace\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\__init__.py", line 130, in <module>
    from . import _distributor_init
  File "C:\Users\Ace\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
>>>
```

**Comment by mehrdadn** [comment]
@sheganinans It looks like you're hitting [this SciPy issue](https://stackoverflow.com/a/62575950).

**Comment by sheganinans** [comment]
@mehrdadn Sweet, that solved that problem, but now a new problem :)

```
>>> import ray.rllib.agents.ppo as ppo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Ace\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\ray\rllib\__init__.py", line 9, in <module>
    from ray.rllib.evaluation.rollout_worker import RolloutWorker
  File "C:\Users\Ace\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\ray\rllib\evaluation\__init__.py", line 6, in <module>
    from ray.rllib.evaluation.postprocessing import compute_advantages
  File "C:\Users\Ace\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\ray\rllib\evaluation\postprocessing.py", line 2, in <module>
    import scipy.signal
  File "C:\Users\Ace\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\signal\__init__.py", line 291, in <module>
    from . import sigtools, windows
  File "C:\Users\Ace\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\signal\windows\__init__.py", line 41, in <module>
    from .windows import *
  File "C:\Users\Ace\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\signal\windows\windows.py", line 9, in <module>
    from scipy import linalg, special, fft as sp_fft
  File "C:\Users\Ace\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\__init__.py", line 195, in <module>
    from .misc import *
  File "C:\Users\Ace\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "C:\Users\Ace\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\blas.py", line 215, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: The specified module could not be found.
```

I'm assuming I don't have the proper BLAS dependencies installed?

**Comment by mehrdadn** [comment]
@sheganinans Looks like it. Might be [this issue](/scipy/scipy/issues/10171). Not sure what the solution is but you can try instead installing SciPy etc. from here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy

**Comment by sheganinans** [comment]
@mehrdadn ok thanks for the direction. i think i may just try wiping python and then starting from scratch with these pointers. ill post again if i get it working or with more errors. thanks!

**Comment by mehrdadn** [comment]
@sheganinans Sounds good! You might want to try [plain Win32 Python](https://www.python.org/downloads/windows/) by the way, instead of the Microsoft Store one. While there shouldn't be a difference, there still might be, and the team doesn't test with the latter.

**Comment by sheganinans** [comment]
@mehrdadn Ok, I'll work with win32 since that's what upstream is testing. Thats fine, since im planning on keeping this an isolated rllib component inside a larger windows app, so I don't have any prior python dependencies currenetly.

Otherwise I'll likely be following the latest release or possible master, since I'll likely want to use the bleeding-edge features, what would be recommended do you think?

**Comment by mehrdadn** [comment]
@sheganinans If you want bleeding edge features, I think you'll want to follow master, though it's more likely to break at random points. Releases do happen fairly regularly though, so I don't think you'll be too far behind if you stay with the releases.

**Comment by sheganinans** [comment]
Ok, I'll stay with the current releases then, thanks

**Comment by sheganinans** [comment]
Ok, removed all the python installations. installed win32 py3.8, getting this error:

```
pip3.8.exe install C:\Users\Ace\Downloads\ray-2.0.0.dev0-cp38-cp38-win_amd64.whl
ERROR: ray-2.0.0.dev0-cp38-cp38-win_amd64.whl is not a supported wheel on this platform.
```

@mehrdadn

**Comment by mehrdadn** [comment]
@sheganinans: I think you might've installed 32-bit Python instead of 64-bit? Sorry if "Win32" was confusing—it's the name of the Windows subsystem that I was referring to, not the architecture. If you installed 32-bit you'll want to uninstall this and install the 64-bit version, e.g. [this one](https://www.python.org/ftp/python/3.8.7/python-3.8.7-amd64.exe).

**Comment by sheganinans** [comment]
Ok, ok. Yes. I was confused as to what you meant. I haven't used Python much in many years, let alone on Windows, so I'm pretty rusty.

Now it's working, my steps to reproduce:

*Uninstall everything, lol*

Install this: https://www.python.org/ftp/python/3.8.7/python-3.8.7-amd64.exe
Grab this: https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp38-cp38-win_amd64.whl

```
pip3.8.exe install C:\Users\Ace\Downloads\ray-2.0.0.dev0-cp38-cp38-win_amd64.whl
pip3.8.exe install "ray[rllib]"
rllib train --run PPO --env CartPole-v0
```

Now it works, thanks for the help! @mehrdadn
