### ISSUE TITLE
[serve] Bad error message when passing in a function that takes no args

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#12178]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
```
import ray
from ray import serve

def f():
    pass

client = serve.start()
client.create_backend("backend", f)
client.create_endpoint("endpoint", backend="backend")

ray.get(client.get_handle("endpoint").remote())
```

Output:
```
(venv) (base) doc/dev % python test.py 
2020-11-19 16:54:27,499 INFO services.py:1090 -- View the Ray dashboard at http://127.0.0.1:8265
(pid=9291) 2020-11-19 16:54:29,320      INFO controller.py:191 -- Starting router with name 'yUuJVb:SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:192.168.0.124-0' on node 'node:192.168.0.124-0' listening on '127.0.0.1:8000'
(pid=9293) 2020-11-19 16:54:29,450      WARNING worker.py:1428 -- Using blocking ray.get inside async actor. This blocks the event loop. Please use `await` on object ref with asyncio.gather if you want to yield execution to the event loop instead.
(pid=9293) INFO:     Started server process [9293]
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    ray.get(client.get_handle("endpoint").remote())
  File "/Users/eoakes/code/ray/doc/dev/bin/venv/lib/python3.8/site-packages/ray/worker.py", line 1452, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::RayServeWorker_f.handle_request() (pid=9289, ip=192.168.0.124)
  File "/Users/eoakes/code/ray/doc/dev/bin/venv/lib/python3.8/site-packages/ray/serve/backend_worker.py", line 132, in wrap_to_ray_error
    raise exception
  File "/Users/eoakes/code/ray/doc/dev/bin/venv/lib/python3.8/site-packages/ray/serve/backend_worker.py", line 244, in invoke_single
    result = await method_to_call(arg)
  File "/Users/eoakes/code/ray/doc/dev/bin/venv/lib/python3.8/site-packages/ray/async_compat.py", line 29, in wrapper
    return func(*args, **kwargs)
TypeError: f() takes 0 positional arguments but 1 was given
(pid=9291) 2020-11-19 16:54:31,369      INFO controller.py:702 -- Registering route 'endpoint' to endpoint 'endpoint' with methods '['GET']'.
2020-11-19 16:54:33,205 INFO api.py:57 -- Shutting down Ray Serve because client went out of scope. To prevent this, either keep a reference to the client object or use serve.start(detached=True).
```

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment]
@architkulkarni mind taking a look? We should probably either support taking no args (preferred) or have a better error message than this.
