### ISSUE TITLE
[core] Restarting a task after crash raises RayActorErrors in follow-up tasks

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#12205]
### What is the problem?

After starting a distributed training task which exited ungracefully, starting it the next time raises `RayActorError`s (from the old non-cleaned up run?), leading to failures. Only the second restart seems to work.

The error message is `ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.`.

Please note that the distributed training was finished when the original error occurred (however, the Actors were not cleaned up, yet).

Cluster config: https://github.com/ray-project/xgboost_ray/blob/master/xgboost_ray/tests/release/cpu_large_scale.yaml
Script: https://github.com/ray-project/xgboost_ray/blob/master/xgboost_ray/tests/release/benchmark_cpu_gpu.py

Output (with comments marked by `###`)
```

(base) root@ip-172-31-30-231:/release_tests# python benchmark_cpu_gpu.py 10 10 10
2020-11-20 04:20:43,733 INFO worker.py:651 -- Connecting to existing Ray cluster at address: 172.31.30.231:6379
2020-11-20 04:20:55,611 INFO main.py:315 -- [RayXGBoost] Created 10 remote actors.
2020-11-20 04:21:10,462 INFO main.py:324 -- [RayXGBoost] Starting XGBoost training.
2020-11-20 04:21:13,587 INFO main.py:368 -- [RayXGBoost] Finished XGBoost training on training data with total N=1,500,000.
TRAIN TIME TAKEN: 18.04 seconds
Final training error: 0.4895
TOTAL TIME TAKEN: 29.83 seconds (0.03 for init)
Traceback (most recent call last):
  File "benchmark_cpu_gpu.py", line 90, in <module>
    args.method, num_workers, num_files,
AttributeError: 'Namespace' object has no attribute 'method'
### This is the original error

### Start same script again (after fixing error)
(base) root@ip-172-31-30-231:/release_tests# python benchmark_cpu_gpu.py 10 10 10
2020-11-20 04:22:46,008 INFO worker.py:651 -- Connecting to existing Ray cluster at address: 172.31.30.231:6379
2020-11-20 04:22:46,905 INFO main.py:315 -- [RayXGBoost] Created 10 remote actors.
2020-11-20 04:22:48,496 INFO main.py:324 -- [RayXGBoost] Starting XGBoost training.
E1120 04:22:49.360246  1417  1473 task_manager.cc:323] Task failed: IOError: 14: Socket closed: Type=ACTOR_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=PythonFunctionDescriptor, module_name=xgboost_ray.main, class_name=RayXGBoostActor, function_name=train, function_hash=}, task_id=e875dddf188b65fd9c8c377d05000000, task_name=RayXGBoostActor.train(), job_id=05000000, num_args=10, num_returns=2, actor_task_spec={actor_id=9c8c377d05000000, actor_caller_id=ffffffffffffffffffffffff05000000, actor_counter=2}
E1120 04:22:49.380141  1417  1473 task_manager.cc:323] Task failed: IOError: 14: Socket closed: Type=ACTOR_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=PythonFunctionDescriptor, module_name=xgboost_ray.main, class_name=RayXGBoostActor, function_name=train, function_hash=}, task_id=24ace04e4cabadbc83f9092105000000, task_name=RayXGBoostActor.train(), job_id=05000000, num_args=10, num_returns=2, actor_task_spec={actor_id=83f9092105000000, actor_caller_id=ffffffffffffffffffffffff05000000, actor_counter=2}
E1120 04:22:49.424024  1417  1473 task_manager.cc:323] Task failed: IOError: cancelling all pending tasks of dead actor: Type=ACTOR_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, module_name=ray.util.queue, class_name=_QueueActor, function_name=empty, function_hash=}, task_id=22488d7ec097f120e31f6f6105000000, task_name=_QueueActor.empty(), job_id=05000000, num_args=0, num_returns=2, actor_task_spec={actor_id=e31f6f6105000000, actor_caller_id=ffffffffffffffffffffffff05000000, actor_counter=99}
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 341, in _train
    while not queue.empty():
  File "/root/anaconda3/lib/python3.7/site-packages/ray/util/queue.py", line 37, in empty
    return ray.get(self.actor.empty.remote())
  File "/root/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1454, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.

### Ignore this error:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "benchmark_cpu_gpu.py", line 81, in <module>
    train_taken = train_ray(num_workers, num_boost_rounds, num_files, use_gpu)
  File "benchmark_cpu_gpu.py", line 49, in train_ray
    evals=[(dtrain, "train")])
  File "/root/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 463, in train
    **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 352, in _train
    ray.kill(actor)
  File "/root/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1627, in kill
    "Got: {}.".format(type(actor)))
ValueError: ray.kill() only supported for actors. Got: <class 'tuple'>.
E1120 04:22:49.430277  1417  1473 task_manager.cc:323] Task failed: IOError: 14: Socket closed: Type=ACTOR_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=PythonFunctionDescriptor, module_name=xgboost_ray.main, class_name=RayXGBoostActor, function_name=train, function_hash=}, task_id=2d7e21d253a26d3a757d041a05000000, task_name=RayXGBoostActor.train(), job_id=05000000, num_args=10, num_returns=2, actor_task_spec={actor_id=757d041a05000000, actor_caller_id=ffffffffffffffffffffffff05000000, actor_counter=2}
E1120 04:22:49.458235  1417  1473 task_manager.cc:323] Task failed: IOError: 14: Socket closed: Type=ACTOR_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=PythonFunctionDescriptor, module_name=xgboost_ray.main, class_name=RayXGBoostActor, function_name=train, function_hash=}, task_id=731ac28eb0ddfdbb0ab9f46605000000, task_name=RayXGBoostActor.train(), job_id=05000000, num_args=10, num_returns=2, actor_task_spec={actor_id=0ab9f46605000000, actor_caller_id=ffffffffffffffffffffffff05000000, actor_counter=2}
E1120 04:22:49.488397  1417  1473 task_manager.cc:323] Task failed: IOError: 14: Socket closed: Type=ACTOR_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=PythonFunctionDescriptor, module_name=xgboost_ray.main, class_name=RayXGBoostActor, function_name=train, function_hash=}, task_id=b2b40d9fa86100f0fe3bb7ea05000000, task_name=RayXGBoostActor.train(), job_id=05000000, num_args=10, num_returns=2, actor_task_spec={actor_id=fe3bb7ea05000000, actor_caller_id=ffffffffffffffffffffffff05000000, actor_counter=2}
E1120 04:22:49.501596  1417  1473 task_manager.cc:323] Task failed: IOError: 14: Socket closed: Type=ACTOR_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=PythonFunctionDescriptor, module_name=xgboost_ray.main, class_name=RayXGBoostActor, function_name=train, function_hash=}, task_id=5de42239883a8cff37e2e42405000000, task_name=RayXGBoostActor.train(), job_id=05000000, num_args=10, num_returns=2, actor_task_spec={actor_id=37e2e42405000000, actor_caller_id=ffffffffffffffffffffffff05000000, actor_counter=2}
E1120 04:22:49.532593  1417  1473 task_manager.cc:323] Task failed: IOError: 14: Socket closed: Type=ACTOR_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=PythonFunctionDescriptor, module_name=xgboost_ray.main, class_name=RayXGBoostActor, function_name=train, function_hash=}, task_id=b2e113ef3825e1e785907a4a05000000, task_name=RayXGBoostActor.train(), job_id=05000000, num_args=10, num_returns=2, actor_task_spec={actor_id=85907a4a05000000, actor_caller_id=ffffffffffffffffffffffff05000000, actor_counter=2}
E1120 04:22:49.553022  1417  1473 task_manager.cc:323] Task failed: IOError: 14: Socket closed: Type=ACTOR_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=PythonFunctionDescriptor, module_name=xgboost_ray.main, class_name=RayXGBoostActor, function_name=train, function_hash=}, task_id=eb64762abc7128edd035c66a05000000, task_name=RayXGBoostActor.train(), job_id=05000000, num_args=10, num_returns=2, actor_task_spec={actor_id=d035c66a05000000, actor_caller_id=ffffffffffffffffffffffff05000000, actor_counter=2}
E1120 04:22:49.560072  1417  1473 task_manager.cc:323] Task failed: IOError: 14: Socket closed: Type=ACTOR_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=PythonFunctionDescriptor, module_name=xgboost_ray.main, class_name=RayXGBoostActor, function_name=train, function_hash=}, task_id=019a046c5f3991bd2bcc137d05000000, task_name=RayXGBoostActor.train(), job_id=05000000, num_args=10, num_returns=2, actor_task_spec={actor_id=2bcc137d05000000, actor_caller_id=ffffffffffffffffffffffff05000000, actor_counter=2}
E1120 04:22:49.607770  1417  1473 task_manager.cc:323] Task failed: IOError: 14: Socket closed: Type=ACTOR_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=PythonFunctionDescriptor, module_name=xgboost_ray.main, class_name=RayXGBoostActor, function_name=train, function_hash=}, task_id=ca9e06a104d19e45f991a5e505000000, task_name=RayXGBoostActor.train(), job_id=05000000, num_args=10, num_returns=2, actor_task_spec={actor_id=f991a5e505000000, actor_caller_id=ffffffffffffffffffffffff05000000, actor_counter=2}
(base) root@ip-172-31-30-231:/release_tests# 

### Starting another time works
(base) root@ip-172-31-30-231:/release_tests# python benchmark_cpu_gpu.py 10 10 10
2020-11-20 04:23:21,260 INFO worker.py:651 -- Connecting to existing Ray cluster at address: 172.31.30.231:6379
2020-11-20 04:23:22,027 INFO main.py:315 -- [RayXGBoost] Created 10 remote actors.
2020-11-20 04:23:23,454 INFO main.py:324 -- [RayXGBoost] Starting XGBoost training.
2020-11-20 04:23:26,405 INFO main.py:368 -- [RayXGBoost] Finished XGBoost training on training data with total N=1,500,000.
TRAIN TIME TAKEN: 4.42 seconds
Final training error: 0.4903
TOTAL TIME TAKEN: 5.12 seconds (0.03 for init)
```

Ray 1.0.1post1

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
cc @ericl @rkooo567

**Comment by rkooo567** [comment]
Does it happen in 1.0.1?

**Comment by rkooo567** [comment]
Is your queue detached actor?

**Comment by krfricke** [comment]
I'm not using the `detached` keyword at all - is this what you're asking? (Nor really familiar with detached actors)

**Comment by rkooo567** [comment]
I see. All the actors should be cleaned up when you re-run your job. This looks like a bug in this case

**Comment by krfricke** [comment]
So I can reproduce this error now using this cluster config (adjust to 10 workers): https://github.com/ray-project/xgboost_ray/blob/master/xgboost_ray/tests/release/cpu_large_scale.yaml.

1. Start cluster, attach to head node
2. `cd /release_tests`
3. `python benchmark.py 10 30 10`
4. Right after finishing (like within 10 seconds): Start again `python benchmark.py 10 30 10`
5. Always leads to errors.

If I wait long enough between starting the scripts, the errors do not come up.

On a worker node, these are the logs I get:

```
cat plasma_store.err 
*** Aborted at 1606214367 (unix time) try "date -d @1606214367" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGTERM (@0x3f47) received by PID 15924 (TID 0x7f3c5a1bc740) from PID 16199; stack trace: ***
    @     0x7f3c5a3e33c0 (unknown)
    @     0x7f3c5a2a1334 clock_nanosleep
    @     0x7f3c5a2a7047 nanosleep
    @     0x55fa47ee866a main
    @     0x7f3c5a1e80b3 __libc_start_main
    @     0x55fa47eeb081 (unknown)
```

(plasma store/raylet are restarted after the task failed)

```
cat raylet.out 
I1124 02:38:54.233021 15925 15925 io_service_pool.cc:36] IOServicePool is running with 1 io_service.
I1124 02:38:54.233251 15925 15925 store_runner.cc:30] Allowing the Plasma store to use up to 4.76856GB of memory.
I1124 02:38:54.233284 15925 15925 store_runner.cc:44] Starting object store with directory /tmp and huge page support disabled
I1124 02:38:55.234416 15925 15925 grpc_server.cc:74] ObjectManager server started, listening on port 8076.
I1124 02:38:55.236477 15925 15925 node_manager.cc:178] Initializing NodeManager with ID b09696850e3355ea3c60ddff9bfd5d1d55158edd
I1124 02:38:55.236658 15925 15925 grpc_server.cc:74] NodeManager server started, listening on port 59846.
I1124 02:38:55.238708 15925 15925 agent_manager.cc:40] Not starting agent, the agent command is empty.
I1124 02:38:55.239697 15925 15925 service_based_accessor.cc:775] Received notification for node id = b09696850e3355ea3c60ddff9bfd5d1d55158edd, IsAlive = 1
I1124 02:38:55.239914 15925 15925 service_based_accessor.cc:775] Received notification for node id = 75de49db960f2969cdfb7a1e1aa92df2b6c0e217, IsAlive = 1
I1124 02:38:55.239980 15925 15925 service_based_accessor.cc:775] Received notification for node id = 9650c3bdb817358a561f96422d0eab298bff00e5, IsAlive = 1
I1124 02:38:55.240034 15925 15925 service_based_accessor.cc:775] Received notification for node id = e1059f9b27b62534b09b3ebbb58ef05d05f85b91, IsAlive = 1
I1124 02:38:55.240083 15925 15925 service_based_accessor.cc:775] Received notification for node id = 832c1aac689749b5495219296e5660151ccb6953, IsAlive = 1
I1124 02:38:55.240131 15925 15925 service_based_accessor.cc:775] Received notification for node id = df2dc15cf20e4f79694710c18d725d5e6a14ffd4, IsAlive = 1
I1124 02:38:55.240208 15925 15925 service_based_accessor.cc:775] Received notification for node id = 0dacfc8eec54a0e19a515fccb5d89549313dffa8, IsAlive = 1
I1124 02:38:55.240268 15925 15925 service_based_accessor.cc:775] Received notification for node id = df2b9538740518f5323b7e6ad9591802ecf9f0a2, IsAlive = 1
I1124 02:38:55.240340 15925 15925 service_based_accessor.cc:775] Received notification for node id = b09696850e3355ea3c60ddff9bfd5d1d55158edd, IsAlive = 1
I1124 02:38:55.240353 15925 15925 service_based_accessor.cc:775] Received notification for node id = 20488c5cd59edf9e684951190d96f5715952c02a, IsAlive = 1
I1124 02:38:55.373673 15925 15925 service_based_accessor.cc:775] Received notification for node id = 8a5bb492f06176041abbafe02cd4d1ceb9190eb5, IsAlive = 1
I1124 02:38:55.419138 15925 15925 service_based_accessor.cc:775] Received notification for node id = fc4a11897c22d13816c2dd589d9c1d1667cf1769, IsAlive = 1
I1124 02:39:13.468302 15925 15925 worker.cc:123] Assigned worker 66ef2da167ad56c54cbc28c21f0bd660da9b9b68 to job 07000000
I1124 02:39:13.623826 15925 15925 worker.cc:123] Assigned worker e515360edb8f92ad6210ec0e2865876c014e8eaa to job 07000000
I1124 02:39:13.731494 15925 15925 worker.cc:123] Assigned worker 713788d6f591def7050e64040cb4c002b7f903ad to job 07000000
I1124 02:39:13.829911 15925 15925 worker.cc:123] Assigned worker 451effdcc5978b4aec59288b216e5f810ffbf8ca to job 07000000
W1124 02:39:21.127002 15925 15925 node_manager.cc:3172] Worker 66ef2da167ad56c54cbc28c21f0bd660da9b9b68 failed. Unpinning object 1e507db1bc3fb7fded4846a60700000003000000
W1124 02:39:21.127084 15925 15925 node_manager.cc:3172] Worker 66ef2da167ad56c54cbc28c21f0bd660da9b9b68 failed. Unpinning object 1e507db1bc3fb7fded4846a60700000004000000
I1124 02:39:26.909539 15925 15925 worker.cc:123] Assigned worker 0b4dca4c35486624c6f5efd2e55866f7257721e2 to job 0a000000
I1124 02:39:27.054471 15925 15925 worker.cc:123] Assigned worker 3c04e2e8d5cc8ce60cafc1e0f724133028ae7913 to job 0a000000
I1124 02:39:27.160796 15925 15925 worker.cc:123] Assigned worker 2c1eccbfb6ef7960cebad1e08e5d1187a9928d3e to job 0a000000
I1124 02:39:27.364305 15925 15925 worker.cc:123] Assigned worker bd1bb973b1a670768cae3eb1cea7b4d942d96e2d to job 0a000000
I1124 02:39:27.509696 15925 15925 service_based_accessor.cc:775] Received notification for node id = 0dacfc8eec54a0e19a515fccb5d89549313dffa8, IsAlive = 0
I1124 02:39:27.553110 15925 15925 service_based_accessor.cc:775] Received notification for node id = 8a5bb492f06176041abbafe02cd4d1ceb9190eb5, IsAlive = 0
I1124 02:39:27.567040 15925 15925 service_based_accessor.cc:775] Received notification for node id = df2dc15cf20e4f79694710c18d725d5e6a14ffd4, IsAlive = 0
I1124 02:39:27.574868 15925 15925 main.cc:276] Raylet received SIGTERM, shutting down...
I1124 02:39:27.574919 15925 15925 service_based_accessor.cc:452] Unregistering node info, node id = b09696850e3355ea3c60ddff9bfd5d1d55158edd
I1124 02:39:27.575176 15925 15925 io_service_pool.cc:48] IOServicePool is stopped.
```

Worker error logs:

```cat worker-0b1d304767e7b29b0da20e56dcd27be91c50777d-16167.err 
Ray worker pid: 16167
2020-11-24 02:39:27,581 ERROR worker.py:384 -- SystemExit was raised from the worker
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 551, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 369, in ray._raylet.execute_task
  File "/root/anaconda3/lib/python3.7/site-packages/ray/function_manager.py", line 397, in load_actor_class
    job_id, actor_creation_function_descriptor)
  File "/root/anaconda3/lib/python3.7/site-packages/ray/function_manager.py", line 493, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
  File "/root/anaconda3/lib/python3.7/site-packages/xgboost_ray/__init__.py", line 1, in <module>
    from xgboost_ray.main import train, predict
  File "/root/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 25, in <module>
    import xgboost as xgb
  File "/root/anaconda3/lib/python3.7/site-packages/xgboost/__init__.py", line 9, in <module>
    from .core import DMatrix, DeviceQuantileDMatrix, Booster
  File "/root/anaconda3/lib/python3.7/site-packages/xgboost/core.py", line 19, in <module>
    from .compat import (
  File "/root/anaconda3/lib/python3.7/site-packages/xgboost/compat.py", line 169, in <module>
    import dask
  File "/root/anaconda3/lib/python3.7/site-packages/dask/__init__.py", line 6, in <module>
    from .delayed import delayed
  File "/root/anaconda3/lib/python3.7/site-packages/dask/delayed.py", line 7, in <module>
    from tlz import curry, concat, unique, merge
  File "/root/anaconda3/lib/python3.7/site-packages/tlz/__init__.py", line 9, in <module>
    from . import _build_tlz
  File "/root/anaconda3/lib/python3.7/site-packages/tlz/_build_tlz.py", line 3, in <module>
    import toolz
  File "/root/anaconda3/lib/python3.7/site-packages/toolz/__init__.py", line 22, in <module>
    functoolz._sigs.create_signature_registry()
  File "/root/anaconda3/lib/python3.7/site-packages/toolz/_signatures.py", line 665, in create_signature_registry
    new_sigs = tuple(expand_sig(sig) for sig in sigs)
  File "/root/anaconda3/lib/python3.7/site-packages/toolz/_signatures.py", line 665, in <genexpr>
    new_sigs = tuple(expand_sig(sig) for sig in sigs)
  File "/root/anaconda3/lib/python3.7/site-packages/toolz/_signatures.py", line 649, in expand_sig
    sigspec = signature_or_spec(func)
  File "/root/anaconda3/lib/python3.7/site-packages/toolz/_signatures.py", line 616, in signature_or_spec
    try:
  File "/root/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 381, in sigterm_handler
    sys.exit(1)
SystemExit: 1
```

Note that the worker error logs seem unrelated to the actual issue. I think they just print the traceback wherever the task was killed (?). This is from another try:

```
Ray worker pid: 18166
2020-11-24 02:49:01,936 ERROR worker.py:384 -- SystemExit was raised from the worker
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 551, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 369, in ray._raylet.execute_task
  File "/root/anaconda3/lib/python3.7/site-packages/ray/function_manager.py", line 397, in load_actor_class
    job_id, actor_creation_function_descriptor)
  File "/root/anaconda3/lib/python3.7/site-packages/ray/function_manager.py", line 493, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
  File "/root/anaconda3/lib/python3.7/site-packages/xgboost_ray/__init__.py", line 1, in <module>
    from xgboost_ray.main import train, predict
  File "/root/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 25, in <module>
    import xgboost as xgb
  File "/root/anaconda3/lib/python3.7/site-packages/xgboost/__init__.py", line 9, in <module>
    from .core import DMatrix, DeviceQuantileDMatrix, Booster
  File "/root/anaconda3/lib/python3.7/site-packages/xgboost/core.py", line 17, in <module>
    import scipy.sparse
  File "/root/anaconda3/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .base import *
  File "/root/anaconda3/lib/python3.7/site-packages/scipy/sparse/base.py", line 7, in <module>
    from scipy._lib._numpy_compat import broadcast_to
  File "/root/anaconda3/lib/python3.7/site-packages/scipy/_lib/_numpy_compat.py", line 16, in <module>
    _assert_warns = np.testing.assert_warns
  File "/root/anaconda3/lib/python3.7/site-packages/numpy/__init__.py", line 208, in __getattr__
    import numpy.testing as testing
  File "/root/anaconda3/lib/python3.7/site-packages/numpy/testing/__init__.py", line 8, in <module>
    from unittest import TestCase
  File "/root/anaconda3/lib/python3.7/unittest/__init__.py", line 62, in <module>
    from .loader import (TestLoader, defaultTestLoader, makeSuite, getTestCaseNames,
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/root/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 381, in sigterm_handler
    sys.exit(1)
SystemExit: 1
```

**Comment by ericl** [comment]
We can raise the priority of this to P0 if you can reproduce with a simple code snippet (no xgboost).

**Comment by AlonMKovrr** [comment]
I am experiencing something very similar, any news?

**Comment by krfricke** [comment]
I'm working on providing a minimal reproducible script for this (hopefully early next year). Can you elaborate where you encountered these issues @AlonMKovrr?

**Comment by AlonMKovrr** [comment]
Well we actually changed a lot of our code since then,
I think something similar happened also when i had pods crashing when they were out of memory
