### ISSUE TITLE
`ray.get_gpu_ids()` doesn't work with local_mode

### ISSUE THREAD

**Issue by rshin** [ray-project/ray#1221]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.2.1
- **Python version**: 2.7.12
- **Exact command to reproduce**:

### Describe the problem
`ray.get_gpu_ids()` crashes when `ray.init` was called with `PYTHON_MODE`.

**Comment by robertnishihara** [comment]
Thanks for reporting this!

**Comment by robertnishihara** [comment]
Hi, `ray.get_gpu_ids()` doesn't return all of the GPUs on the machine. It is intended to be used within a task and returns the GPU IDs that are reserved for that task. Instead, try

```
import ray

ray.init(num_gpus=2)

@ray.remote(num_gpus=1)
def f():
    print(ray.get_gpu_ids())
```

That said, you probably don't need to actually call this method because Ray will automatically set the `CUDA_VISIBLE_DEVICES` environment variable.

**Comment by kirk86** [comment]
Hi @robertnishihara thanks for the clarification, it makes things a bit more clear.
If you don't mind me asking, I'm facing another problem. I am trying to run the following example from the tutorials. 
[ray_example.zip](https://github.com/ray-project/ray/files/2396322/ray_example.zip)
The goal is to have that simple example parallelize across both my gpus on my local pc, but I keep getting the following error:
```
WARNING: Serializing objects of type <class 'tensorflow.contrib.learn.python.learn.datasets.base.Datasets'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
2018-09-19 10:05:19.118840: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2018-09-19 10:05:19.356415: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:17:00.0
totalMemory: 10.92GiB freeMemory: 10.56GiB
2018-09-19 10:05:19.356444: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-09-19 10:05:20.263083: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-19 10:05:20.263122: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2018-09-19 10:05:20.263128: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2018-09-19 10:05:20.263598: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10215 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:17:00.0, compute capability: 6.1)
Accuracy is 0.8903999924659729.
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0919 10:05:21.059509  4924 local_scheduler.cc:177] Killed worker pid 5344 which hadn't started yet.
```
Any ideas on why is that happening?

**Comment by robertnishihara** [comment]
It looks like the application is completing successfully since it prints `Accuracy is 0.8903999924659729.`. I suspect the error message is an error that happens accidentally when Ray is shutting down, which we should probably fix.

**Comment by kirk86** [comment]
@robertnishihara 
Oh cool! 
thank you for your input. Could you please help me clarify if the following Ray notation utilizes both gpus i.e. parallel training?

> import ray
ray.init(num_gpus=2)
 @ray.remote(num_gpus=1) 
def f(): print(ray.get_gpu_ids())

Or should we instead use:
> import ray
ray.init(num_gpus=2)
 @ray.remote(num_gpus=2) 
def f(): print(ray.get_gpu_ids())

for parallel training on both gpus?

One last remark is that I tried to modify the `train` method in the above example that I had attached in order to print the accuracy after every step:

from this:
```
def train(self, num_steps):
        for step in range(num_steps):
            batch_xs, batch_ys = self.mnist.train.next_batch(100)
            self.sess.run(
                self.train_step, feed_dict={self.x: batch_xs, self.y_: batch_ys}
            )
```

to this one:
```
def train(self, num_steps):
        for step in range(num_steps):
            batch_xs, batch_ys = self.mnist.train.next_batch(100)
            self.sess.run(
                self.train_step, feed_dict={self.x: batch_xs, self.y_: batch_ys}
            )
            print("Step: {}, Accuracy is {}:".format(
              step, ray.get(self.get_accuracy.remote())
              )
            )
```

But it doesn't print anything, am I using the wrong notation regarding Ray?

**Comment by GoingMyWay** [comment]
When `local_mode=False`, the error happens for `ray==1.4.1` with pytorch.

```python
import os
import tempfile
import datetime

import ray
import tqdm
import ray.rllib.agents.ppo as ppo

from ray.tune.logger import Logger, UnifiedLogger



def custom_log_creator(custom_path, custom_str):

    timestr = datetime.date.today().strftime("%Y-%m-%d_%H-%M-%S")
    logdir_prefix = "{}_{}".format(custom_str, timestr)

    def logger_creator(config):

        if not os.path.exists(custom_path):
            os.makedirs(custom_path)
        logdir = tempfile.mkdtemp(prefix=logdir_prefix, dir=custom_path)
        return UnifiedLogger(config, logdir, loggers=None)

    return logger_creator


config={
'framework': 'torch',
'num_gpus': 1, 
'num_workers': 4,
'model': {'use_lstm': True}, 
}

ray.init(num_gpus=config['num_gpus'], local_mode=False)
trainer = ppo.PPOTrainer(config=config, env="CartPole-v0", logger_creator=custom_log_creator(os.path.expanduser("/home/docker/app/examples/rllib/ray_results"), 'custom_dir'))

for i in tqdm.tqdm(range(10)):
   trainer.train()

ray.shutdown()

```

and the error

```
2022-02-23 11:07:01,750	INFO services.py:1274 -- View the Ray dashboard at http://127.0.0.1:8265
2022-02-23 11:07:03,398	INFO trainer.py:698 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
Traceback (most recent call last):
  File "test.py", line 39, in <module>
    trainer = ppo.PPOTrainer(config=config, env="CartPole-v0", logger_creator=custom_log_creator(os.path.expanduser("/home/docker/app/examples/rllib/ray_results"), 'custom_dir'))
  File "/home/docker/miniconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 123, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/docker/miniconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 548, in __init__
    super().__init__(config, logger_creator)
  File "/home/docker/miniconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/docker/miniconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 709, in setup
    self._init(self.config, self.env_creator)
  File "/home/docker/miniconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 155, in _init
    num_workers=self.config["num_workers"])
  File "/home/docker/miniconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 797, in _make_workers
    logdir=self.logdir)
  File "/home/docker/miniconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 100, in __init__
    spaces=spaces,
  File "/home/docker/miniconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 407, in _make_worker
    spaces=spaces,
  File "/home/docker/miniconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 537, in __init__
    policy_dict, policy_config)
  File "/home/docker/miniconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1196, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/home/docker/miniconda3/lib/python3.7/site-packages/ray/rllib/policy/policy_template.py", line 267, in __init__
    get_batch_divisibility_req=get_batch_divisibility_req,
  File "/home/docker/miniconda3/lib/python3.7/site-packages/ray/rllib/policy/torch_policy.py", line 155, in __init__
    self.device = self.devices[0]
IndexError: list index out of range
```

Actually, there is a GPU on my machine. I guess `ray.get_gpu_ids()` failed to get the GPU ids.
