### ISSUE TITLE
[Serve] client.shutdown() is not complete

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#12214]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

@crypdick found this issue.

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.
```python
from ray import serve

client = serve.start(detached=True)
client.shutdown()
client = serve.start(detached=True)
```

```
File descriptor limit 256 is too low for production servers and may result in connection errors. At least 8192 is recommended. --- Fix with 'ulimit -n 8192'
2020-11-20 10:38:27,065	INFO services.py:1173 -- View the Ray dashboard at http://127.0.0.1:8265
(pid=raylet) 2020-11-20 10:38:29,628	INFO controller.py:313 -- Starting router with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:192.168.31.141-0' on node 'node:192.168.31.141-0' listening on '127.0.0.1:8000'
(pid=32847) INFO:     Started server process [32847]
Traceback (most recent call last):
  File "detached.py", line 5, in <module>
    client = serve.start(detached=True)
  File "/Users/simonmo/Desktop/ray/ray/python/ray/serve/api.py", line 414, in start
    raise RayServeException("Called serve.start(detached=True) but a "
ray.serve.exceptions.RayServeException: Called serve.start(detached=True) but a detached instance is already running. Please use serve.connect() to connect to the running instance instead.
```

I think this is because we didn't delete the entry in named actor registry.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
This is actually a race condition in ray core:
```python
import ray
import time
ray.init()

@ray.remote
class A:
    pass
a = A.options(lifetime="detached", name="a").remote()
ray.kill(a)
ray.get_actor("a") # You can still get the actor!
time.sleep(2)
ray.get_actor("a") # Now you can't.
```
