### ISSUE TITLE
Deploy Ray on PBS cluster:  redis.exceptions.AuthenticationError: invalid password

### ISSUE THREAD

**Issue by Lewisracing** [ray-project/ray#12216]
Hi,

I'm having difficulty in starting ray on a multi-node cluster.
I'm trying to modify a PBS job submission script to initialize Ray.
```
NODES=`cat $PBS_NODEFILE`
echo $NODES

ip_prefix=`hostname -i`
suffix=':6379'
ip_head=$ip_prefix$suffix
redis_password='912716'

echo parameters: $ip_head 
module load PyTorch
ray start --head --port=6379 --redis-password="912716"
sleep 3

for NODE in $NODES; do
  ssh -tt $NODE &
  module load PyTorch &
  ray start --address=$ip_head --redis-password="912716"

done
#############
module load PyTorch
python < Main.py
```

I'm given the error of

 [s262332@dcn081 ~]$ 2020-11-20 19:09:59,359	INFO scripts.py:468 -- Using IP address 10.0.1.77 for this node.
2020-11-20 19:09:59,364	INFO resource_spec.py:212 -- Starting Ray with 71.78 GiB memory available for workers and up to 30.78 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-11-20 19:09:59,406	INFO scripts.py:477 -- 
Started Ray on this node. If you wish to terminate the processes that have been started, run

 ray stop
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/apps/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/ray/worker.py", line 785, in init
    connect_only=True)
  File "/apps/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/ray/node.py", line 122, in __init__
    redis_client.get("session_name"))
  File "/apps/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/redis/client.py", line 1579, in get
    return self.execute_command('GET', name)
  File "/apps/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/redis/client.py", line 875, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/apps/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/redis/connection.py", line 1185, in get_connection
    connection.connect()
  File "/apps/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/redis/connection.py", line 561, in connect
    self.on_connect()
  File "/apps/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/redis/connection.py", line 637, in on_connect
    auth_response = self.read_response()
  File "/apps/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/redis/connection.py", line 734, in read_response
    response = self._parser.read_response()
  File "/apps/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/redis/connection.py", line 333, in read_response
    raise error
redis.exceptions.AuthenticationError: invalid password

I think I'm very close to a success but couldn't figure our what's wrong with my script... Any ideas?

Many thanks

**Comment by richardliaw** [comment]
Does it work if you don't start any worker?

**Comment by Lewisracing** [comment]
> Does it work if you don't start any worker?

If I comment the workers as below:

'''
from Lewis_functions import *
import torch.multiprocessing

torch.multiprocessing.set_sharing_strategy('file_system')
import ray

ray.init(address="auto")
#ray.init()
if __name__ == '__main__':
    cfg = PPO_config()
    i=0
    while i<200:
        print(i)
        i+=1

    #learner = [Learner.remote(cfg)]
    #workers = [Worker.remote(i, cfg) for i in range(cfg.number_of_workers)]
    #all_actors = learner + workers
    #ray.wait([actor.start_working.remote() for actor in all_actors])
'''
It's hard to tell if it works. No error is reported but got some idle processes shown in the following pic
![image](https://user-images.githubusercontent.com/48195265/99846069-98ce0400-2b6d-11eb-9be9-70c126bb6aea.png)

**Comment by Lewisracing** [comment]
> Does it work if you don't start any worker?

No, still the same error

**Comment by Lewisracing** [comment]
Problem solved.... should not use the password from yourself

**Comment by richardliaw** [comment]
@Lewisracing can you post more about what you did to fix it?

It was hard for me to help because I didn't quite understand the error -- I'd love to learn more about what you did/what the issue was so that I can help others in the future!

**Comment by Lewisracing** [comment]
It's a bit odd for me as well. When I manually initialize Ray on the allocated nodes(by ssh log on then ray start**), I can assign the password anyway I like. But if I want to use the PBS shell script to submit the job, I have to use the default password given by redis which is a long one. Otherwise it will throw the invalid password.
