### ISSUE TITLE
[tune] attaching resources in the middle of hyper parameter search

### ISSUE THREAD

**Issue by vlad17** [ray-project/ray#1233]
### System information
- Ubuntu 16.04
- pip install ray==0.2.2
- 3.5.2 and 3.5.4
- Ubuntu 16.04

### Recreation

1. Start ray in cluster mode
2. Run a large grid search via the trial runner
3. Attach a new machine in the middle of the grid search. The new machine was using docker.

I didn't follow the instructions [here](https://github.com/ray-project/ray/blob/1a682e28072e32c73a12a44defac40448a67fc34/doc/source/using-ray-and-docker-on-a-cluster.md), so that probably caused the problem. I'm just submitting this because the part of ray that was working fine (the non-docker machine running the sweep) was killed due to the following error:

	Traceback (most recent call last):
	  File "mpc_bootstrap/tune.py", line 152, in <module>
	    _main(_args)
	  File "mpc_bootstrap/tune.py", line 147, in _main
	    _search_hypers(hypers, args.tune)
	  File "mpc_bootstrap/tune.py", line 138, in _search_hypers
	    runner.step()
	  File "/data/vladf/anaconda3/envs/gpu-py3.5/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 59, in step
	    if self._can_launch_more():
	  File "/data/vladf/anaconda3/envs/gpu-py3.5/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 119, in _can_launch_more
	    trial = self._get_runnable()
	  File "/data/vladf/anaconda3/envs/gpu-py3.5/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 173, in _get_runnable
	    return self._scheduler_alg.choose_trial_to_run(self)
	  File "/data/vladf/anaconda3/envs/gpu-py3.5/lib/python3.5/site-packages/ray/tune/trial_scheduler.py", line 41, in choose_trial_to_run
	    trial_runner.has_resources(trial.resources)):
	  File "/data/vladf/anaconda3/envs/gpu-py3.5/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 114, in has_resources
	    assert cpu_avail >= 0 and gpu_avail >= 0
	AssertionError

**Comment by ericl** [comment]
Hm, I was unable to reproduce this on my (AWS instance) cluster, however reading over the code it seems possible `avail_resources` is out of date when the cluster size is scaling. It probably makes sense to remove the assert to handle this eventual consistency: https://github.com/ray-project/ray/pull/1237
