### ISSUE TITLE
[Asyncio] await RayActorError throw the wrong error

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#12384]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
```python
import ray
import asyncio

ray.init()
@ray.remote
class A:
    def hi(self): return "hi"

a = A.remote()
async def main():
    await a.hi.remote()
    ray.kill(a)
    await a.hi.remote()

asyncio.get_event_loop().run_until_complete(main())
```

You will see
```
Exception in callback async_set_result.<locals>.set_future()
handle: <Handle async_set_result.<locals>.set_future()>
Traceback (most recent call last):
  File "/Users/simonmo/miniconda3/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "python/ray/_raylet.pyx", line 1530, in ray._raylet.async_set_result.set_future
AttributeError: 'RayActorError' object has no attribute 'as_instanceof_cause'

```
### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
The fix should be return `as_instanceof_cause` when it's RayTaskError and just the error otherwise.
