### ISSUE TITLE
[RLlib] When restoring Trainer (which didn't have eval-workers) with a config containing eval-workers>0, these workers are not created.

### ISSUE THREAD

**Issue by sven1977** [ray-project/ray#12458]
Andrew R. posted this issue on the discuss.ray.io forum:

-------
Imagine you’ve spent a long time training a RL model. You have a checkpoint from that training, and want to run various metrics and analyses (which you’ll keep iterating on) on the behaviour of that saved model.

You could do rollouts using an approach like in rollout.py, but to get parallelism it might be nice to use evaluation workers, maybe via something like this:

```
import os
import pickle

import ray
from ray.rllib.agents import ppo


def my_custom_eval(trainer, eval_workers):
    # do some cool evaluation metrics here                                                                                                                                                                          
    print('Evaluating')

# previously trained model, can use something like this to generate
# rllib train --run=PPO --env=CartPole-v0  --config="{\"num_workers\": 10, \"train_batch_size\": 1000}" --checkpoint-freq=10
checkpoint_path = os.path.expanduser('~/ray_results/default/PPO_CartPole-v0_bf91c_00000_0_2020-11-25_10-34-08/checkpoint_100/checkpoint-100')

ray.init()

run_base_dir = os.path.dirname(os.path.dirname(checkpoint_path))
config_path = os.path.join(run_base_dir, 'params.pkl')
with open(config_path, 'rb') as f:
    config = pickle.load(f)

# convert all the training workers to evaluation workers                                                                                                                                                           
config['evaluation_num_workers'] = config['num_workers']
config['num_workers'] = 0
# hook in your callback
config['custom_eval_function'] = my_custom_eval

trainer = ppo.PPOTrainer(config=config)
trainer.restore(checkpoint_path)
trainer._evaluate()
You will get an error like:

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/andrew/miniconda3/envs/ray_nightly_tf_2.2/lib/python3.8/site-packages/ray/worker.py", line 856, in custom_excepthook
    ray.state.state.add_worker(worker_id, worker_type, worker_info)
  File "/home/andrew/miniconda3/envs/ray_nightly_tf_2.2/lib/python3.8/site-packages/ray/state.py", line 733, in add_worker
    return self.global_state_accessor.add_worker_info(
AttributeError: 'NoneType' object has no attribute 'add_worker_info'

Original exception was:
Traceback (most recent call last):
  File "ray_eval_after_training.py", line 28, in <module>
    trainer._evaluate()
  File "/home/andrew/miniconda3/envs/ray_nightly_tf_2.2/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 713, in _evaluate
    self._sync_weights_to_workers(worker_set=self.evaluation_workers)
AttributeError: 'PPO' object has no attribute 'evaluation_workers'
```

**Comment by sven1977** [comment]
The original Trainer, which we saved, does not contain these eval workers (they were not originally configured). So even if we have the config correct right before restoring, the restored Trainer object will not have these workers in place.

Two workarounds:

- You create the original Trainer already with eval workers (not great, b/c maybe you don’t need them during training and you also don’t know up front how many you need).
- We do a hot-fix for this particular scenario, where we do create these eval workers after restoring.

**Comment by sven1977** [comment]
Actually, this is not a bug per se (just an unintuitive setup rule for eval workers, where you also need to set `evaluation_interval > 0`).

The following slightly modified script works just fine:
```
import os
import pickle

import ray
from ray.rllib.agents import ppo


def my_custom_eval(trainer, eval_workers):
    # do some cool evaluation metrics here
    print('Evaluating')
    return {
        "a": 1.0,
    }

# previously trained model, can use something like this to generate
# rllib train --run=PPO --env=CartPole-v0  --config="{\"num_workers\": 10, \"train_batch_size\": 1000}" --checkpoint-freq=10
checkpoint_path = os.path.expanduser('~/ray_results/default/PPO_CartPole-v0_c2ec3_00000_0_2020-12-11_15-18-38/checkpoint_9/checkpoint-9')

ray.init()

run_base_dir = os.path.dirname(os.path.dirname(checkpoint_path))
config_path = os.path.join(run_base_dir, 'params.pkl')
with open(config_path, 'rb') as f:
    config = pickle.load(f)

# convert all the training workers to evaluation workers
config['evaluation_num_workers'] = 3
config['evaluation_interval'] = 1
config['num_workers'] = 0
# hook in your callback
config['custom_eval_function'] = my_custom_eval

trainer = ppo.PPOTrainer(config=config)
trainer.restore(checkpoint_path)
trainer._evaluate()
```

**Comment by sven1977** [comment]
Closing this issue now.
