### ISSUE TITLE
[Metrics] Invalid metric name issue

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#12553]
### What is the problem?
Running ray.init when connecting to a cluster will keep printing these.

```
(pid=raylet) Traceback (most recent call last):
(pid=raylet)   File "/root/anaconda3/lib/python3.7/wsgiref/handlers.py", line 137, in run
(pid=raylet)     self.result = application(self.environ, self.start_response)
(pid=raylet)   File "/root/anaconda3/lib/python3.7/site-packages/prometheus_client/exposition.py", line 53, in prometheus_app
(pid=raylet)     status, header, output = _bake_output(registry, accept_header, params)
(pid=raylet)   File "/root/anaconda3/lib/python3.7/site-packages/prometheus_client/exposition.py", line 41, in _bake_output
(pid=raylet)     output = encoder(registry)
(pid=raylet)   File "/root/anaconda3/lib/python3.7/site-packages/prometheus_client/openmetrics/exposition.py", line 14, in generate_latest
(pid=raylet)     for metric in registry.collect():
(pid=raylet)   File "/root/anaconda3/lib/python3.7/site-packages/prometheus_client/registry.py", line 83, in collect
(pid=raylet)     for metric in collector.collect():
(pid=raylet)   File "/root/anaconda3/lib/python3.7/site-packages/ray/prometheus_exporter.py", line 234, in collect
(pid=raylet)     metric = self.to_metric(desc, tag_values, agg_data)
(pid=raylet)   File "/root/anaconda3/lib/python3.7/site-packages/ray/prometheus_exporter.py", line 170, in to_metric
(pid=raylet)     labels=label_keys)
(pid=raylet)   File "/root/anaconda3/lib/python3.7/site-packages/prometheus_client/metrics_core.py", line 100, in __init__
(pid=raylet)     Metric.__init__(self, name, documentation, 'counter', unit)
(pid=raylet)   File "/root/anaconda3/lib/python3.7/site-packages/prometheus_client/metrics_core.py", line 27, in __init__
(pid=raylet)     raise ValueError('Invalid metric name: ' + name)
(pid=raylet) ValueError: Invalid metric name: ray_node_failure_node_failures.
```
*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

On commit f596113fc78483cfd9bd30d781df7bb324e6f024

**Comment by simon-mo** [comment]
@rkooo567 seems like the extra period in the end might be the culprit

**Comment by rkooo567** [comment]
Hmm weird. How does that named metrics registerd?

**Comment by rkooo567** [comment]
CAn you give me the reproduciton script?

**Comment by rkooo567** [comment]
I could reproduce it from stress tests. Btw, how is it possible we have that weird name metrics?

**Comment by rkooo567** [comment]
Fixed by https://github.com/ray-project/ray/pull/12595
