### ISSUE TITLE
Version mismatches on cluster can lead to silent failures.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1263]
To reproduce the problem, take two machines with different cloudpickle versions.

Start Ray on Machine 1.

```
ray start --head --redis-port=6379
```

Start Ray on Machine 2.

```
ray start --redis-address=<machine-1-ip>:6379
```

The second command appears to succeed. However, none of the workers on that machine are alive. Checking `/tmp/raylogs`, the local scheduler log has a lot of errors of the form

```
Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/workers/default_worker.py", line 81, in <module>
    ray.worker.connect(info, mode=ray.WORKER_MODE, actor_id=actor_id)
  File "/home/ubuntu/ray/python/ray/worker.py", line 1719, in connect
    ray.services.check_version_info(worker.redis_client)
  File "/home/ubuntu/ray/python/ray/services.py", line 325, in check_version_info
    "    Cloudpickle: " + version_info[3])
Exception: Version mismatch: The cluster was started with:
    Ray: 0.2.2
    Ray location: /home/ubuntu/ray/python/ray/__init__.py
    Python: 3.5.2
    Cloudpickle: 0.5.2
This process on node 172.31.4.51 was started with:
    Ray: 0.2.2
    Ray location: /home/ubuntu/ray/python/ray/__init__.py
    Python: 3.5.2
    Cloudpickle: 0.2.2
```

It would be simpler to just have the `ray start` command raise that exception.

**Comment by robertnishihara** [comment]
Should have been fixed by #1264.
