### ISSUE TITLE
[Dashboard]Profile Actor Button Not Working

### ISSUE THREAD

**Issue by mfitton** [ray-project/ray#12668]
### What is the problem?
The launch profiling button doesn't work because of a change to a backend grpc payload that led to nodeId no longer being present in actor objects in the front-end. The symptom is that when the profiling button is clicked (any duration), the front-end crashes to a blank page.
*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.
Create an actor and run profiling in the logical view in the nightly build.
- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [x ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by anuragkanungo** [comment]
I am not sure if this is the same issue but trying to profile via dashboard, it's not doing anything and looks like in the chrome console, this following error gets raised.

```
api.ts:24 Uncaught (in promise) Error: Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/ray/new_dashboard/utils.py", line 132, in _handler_route
    return await handler(bind_info.instance, req)
  File "/opt/conda/lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_head.py", line 49, in launch_profiling
    ip = req.query["ip"]
KeyError: 'ip'

    at api.ts:24
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at l (asyncToGenerator.js:25)
```

**Comment by nollied** [comment]
> ot sure if this is the same issue but trying to profile via dashboard, it's not doing any

yeah, same

**Comment by scottsun94** [comment]
@nollied @anuragkanungo 
In Ray 2.0, we changed the experimental dashboard to be the default dashboard. We plan to deprecate the old dashboard in the future. In the new dashboard, we currently don't support profiling the actor.

For better feature planning for the new dashboard, I have some questions:
- Could you help us understand what you want to achieve with "profiling actor" feature? How much value would it bring?
- Other related features you want?

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
