### ISSUE TITLE
[core] The ports being used in ray is too messy...

### ISSUE THREAD

**Issue by DonYum** [ray-project/ray#12665]
## version
1.1.0.dev, 1.0.1.post1, 1.0.1, 1.0.0

## background:
I'm debugging ranning ray cluster with docker. For some reasons, I can't use host network mode. So I have to find all ports that ray used and export to external. 
And then, I found it's a big dirty work. So much so that I'm not done yet.

I have find the ports under is necessary:
- HEAD(10.12.0.125): 
export ports: 6379 8265  8075   8076  8077 
cmd: `ray start --head --port=6379 --dashboard-host='0.0.0.0' --dashboard-port=8265 --gcs-server-port=8075 --object-manager-port=8076 --node-manager-port=8077 `
- WORKER(10.12.0.128):
export ports:  8076  8077  6666
cmd:  `ray start --address=10.12.0.125:6379 --object-manager-port=8076 --node-manager-port=8077 --metrics-export-port=6666`

But I still can't succeed.

Is there Anyone can help?
Or, whether this is a problem? Why not make these ports explicit?
Or, whether my method to use ray with docker is wrong?

Any advice will be appreciated!

Thx a lot!

**Comment by rkooo567** [comment]
You should also expose `--min-worker-port` and `--max-worker-port`https://docs.ray.io/en/latest/configure.html#ports-configurations

**Comment by DonYum** [comment]
@rkooo567  I tried `--worker-port-list=10000,10001,10002` and export `10000,10001,10002`. However, it's not help. I think it's the same effort as `--min-worker-port` and `--max-worker-port`.
Am I right?

**Comment by rkooo567** [comment]
3 are not enough. You should open at least as many as `num_cpus`, and it is recommended to open more to avoid port conflict or worker startup failures (because of address already in use).

**Comment by DonYum** [comment]
OK, I'll try now.
Another question is: what is '--node-ip-address' for? is that necessary?
BRs.

**Comment by rkooo567** [comment]
That' used when you want to specify the IP address on your own. Otherwise, the IP address is resolved automatically by Ray (it is probably resolved to be the docker internal IP address if you don't specify anything).

**Comment by DonYum** [comment]
@rkooo567 When I use `--node-ip-address` to specify IP to host IP, it lanch ok but runs `ray memory` fail:
```log
(base) root@a9198e5f925e:/# ray memory
2020-12-08 03:20:47,077 INFO scripts.py:1340 -- Connecting to Ray instance at 10.12.0.125:6379.
2020-12-08 03:20:47,077 INFO worker.py:651 -- Connecting to existing Ray cluster at address: 10.12.0.125:6379
2020-12-08 03:20:47,087 WARNING services.py:202 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2020-12-08 03:20:48,096 WARNING services.py:202 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2020-12-08 03:20:49,104 WARNING services.py:202 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2020-12-08 03:20:50,112 WARNING services.py:202 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2020-12-08 03:20:51,120 WARNING services.py:202 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
Traceback (most recent call last):
  File "/root/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1468, in main
    return cli()
  File "/root/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/anaconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1341, in memory
    ray.init(address=address, _redis_password=redis_password)
  File "/root/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 759, in init
    connect_only=True)
  File "/root/anaconda3/lib/python3.7/site-packages/ray/node.py", line 163, in __init__
    redis_password=self.redis_password))
  File "/root/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 195, in get_address_info_from_redis
    redis_address, node_ip_address, redis_password=redis_password)
  File "/root/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 178, in get_address_info_from_redis_helper
    "Redis has started but no raylets have registered yet.")
RuntimeError: Redis has started but no raylets have registered yet.
```

**Comment by DonYum** [comment]
@rkooo567  Another problem about ports is: when I export a bundle of ports, docker will hang for a long time(about 30s). The cmd is like this:
`docker run -it -p 6379:6379 -p 8265:8265 -p 8075:8075 -p 8076:8076 -p 8077:8077  -p 6666:6666  -p 6667:6667 -p 10000-10022:10000-10022 --shm-size=4g rayproject/ray bash`

**Comment by dHannasch** [comment]
@DonYum Are you using the latest wheel from https://docs.ray.io/en/master/installation.html? There should be a more informative error message for "Redis has started but no raylets have registered yet." now.
