### ISSUE TITLE
Avoid global state access during cleanup

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#12690]
```python
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Users/rliaw/miniconda3/envs/horovod/lib/python3.7/site-packages/ray/worker.py", line 836, in custom_excepthook
    ray.state.state.add_worker(worker_id, worker_type, worker_info)
  File "/Users/rliaw/miniconda3/envs/horovod/lib/python3.7/site-packages/ray/state.py", line 733, in add_worker
    return self.global_state_accessor.add_worker_info(
AttributeError: 'NoneType' object has no attribute 'add_worker_info'
```

I'll often see weird issue like this. It'll be nice to avoid this stacktrace, as it is misleading (looks like a bug when actually the cleanup is OK).

**Comment by ericl** [comment]
This seems like a P0 regression

**Comment by ericl** [comment]
@richardliaw can you provide a simple repro? This seems like a regression.

**Comment by ericl** [comment]
Actually, seems this causes the problem
```
import ray

ray.init()

@ray.remote
def f(self):
    raise ValueError

ray.get(f.remote())
```

**Comment by rkooo567** [comment]
I think this is fixed by https://github.com/ray-project/ray/pull/12655/files?
