### ISSUE TITLE
[serve] Backends can no longer take no arguments as input

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#12885]
### What is the problem?

This should work:
```python
import ray
from ray import serve
client = serve.start()

def f(): pass

client.create_backend("backend", f)
client.create_endpoint("endpoint", backend="backend")

ray.get(client.get_handle("endpoint").remote())
```

Traceback:
```
2020-12-15 12:16:50,541 INFO router.py:226 -- Endpoint endpoint doesn't exist, waiting for registration.
Traceback (most recent call last):
  File "t.py", line 10, in <module>
    ray.get(client.get_handle("endpoint").remote())
  File "/Users/eoakes/code/ray/python/ray/worker.py", line 1375, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::RayServeReplica_f.handle_request() (pid=22609, ip=192.168.0.124)
  File "/Users/eoakes/code/ray/python/ray/serve/backend_worker.py", line 139, in wrap_to_ray_error
    raise exception
  File "/Users/eoakes/code/ray/python/ray/serve/backend_worker.py", line 259, in invoke_single
    result = await method_to_call(arg)
  File "/Users/eoakes/code/ray/python/ray/async_compat.py", line 29, in wrapper
    return func(*args, **kwargs)
TypeError: f() takes 0 positional arguments but 1 was given
```

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment]
Supported in deployments API
