### ISSUE TITLE
Improve dashboard not found exception

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#12955]
### What is the problem?

This exception can be scary for users:
```
2020-12-16 18:17:37,561	WARNING dashboard.py:208 -- The dashboard on node ILHERLNCN2QWDVF failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/new_dashboard/dashboard.py", line 192, in <module>
    log_dir=args.log_dir)
  File "/usr/local/lib/python3.6/dist-packages/ray/new_dashboard/dashboard.py", line 81, in __init__
    build_dir = setup_static_dir()
  File "/usr/local/lib/python3.6/dist-packages/ray/new_dashboard/dashboard.py", line 45, in setup_static_dir
    "&& npm run build)", build_dir)
FileNotFoundError: [Errno 2] Dashboard build directory not found. If installing from source, please follow the additional steps required to build the dashboard(cd python/ray/new_dashboard/client && npm install && npm ci && npm run build): '/usr/local/lib/python3.6/dist-packages/ray/new_dashboard/client/build'
```

We should just log an error or warning instead.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
