### ISSUE TITLE
[core] TypeError in log_monitor.py

### ISSUE THREAD

**Issue by DonYum** [ray-project/ray#13181]
Ray: 1.1.0
Python: 3.7.6
CentOS 7

I'm using ActorPool to test perf on a cluster. When I delete a node, I accidentally make the following error:

```
2021-01-05 12:58:36,818 WARNING worker.py:1034 -- The log monitor on node iZuf64b8khdekbm1028jv8Z failed with the following error:
Traceback (most recent call last):
  File "/home/yunfeng/miniconda3/envs/gaia/lib/python3.7/site-packages/ray/log_monitor.py", line 354, in <module>
    log_monitor.run()
  File "/home/yunfeng/miniconda3/envs/gaia/lib/python3.7/site-packages/ray/log_monitor.py", line 275, in run
    self.open_closed_files()
  File "/home/yunfeng/miniconda3/envs/gaia/lib/python3.7/site-packages/ray/log_monitor.py", line 164, in open_closed_files
    self.close_all_files()
  File "/home/yunfeng/miniconda3/envs/gaia/lib/python3.7/site-packages/ray/log_monitor.py", line 102, in close_all_files
    os.kill(file_info.worker_pid, 0)
TypeError: an integer is required (got type NoneType)
```

Then the log on this node can not be collected to head node.

Is it necessary to add an error check for `TypeError`?

**Comment by rkooo567** [comment]
I think this indicates there's something wrong elsewhere, so I don't think adding TypeError is a right solution. 

But as I mentioned in other issues; it is really hard for us to troubleshoot the issue if we cannot reproduce the issue or at least know a way to reproduce it.

**Comment by rkooo567** [comment]
Also, can you explain more details about "when I delete a node"? What does it mean by you delete a node?

**Comment by DonYum** [comment]
@rkooo567  Just `ray stop` on that node.

**Comment by Deathn0t** [comment]
I also have this error, I am executing functions on multi-gpus nodes, the functions are well executed during some time and then this error appears, the execution and the cluster crash and I am not finding any logs about what happened:
```
2021-03-24 14:16:53,800	WARNING worker.py:1107 -- The log monitor on node thetagpu21 failed with the following error:
Traceback (most recent call last):
  File “/lus/theta-fs0/projects/datascience/regele/thetagpu/testdh/dhgpu/lib/python3.8/site-packages/ray/log_monitor.py”, line 359, in <module>
    log_monitor.run()
  File “/lus/theta-fs0/projects/datascience/regele/thetagpu/testdh/dhgpu/lib/python3.8/site-packages/ray/log_monitor.py”, line 280, in run
    self.open_closed_files()
  File “/lus/theta-fs0/projects/datascience/regele/thetagpu/testdh/dhgpu/lib/python3.8/site-packages/ray/log_monitor.py”, line 167, in open_closed_files
    self.close_all_files()
  File “/lus/theta-fs0/projects/datascience/regele/thetagpu/testdh/dhgpu/lib/python3.8/site-packages/ray/log_monitor.py”, line 102, in close_all_files
    os.kill(file_info.worker_pid, 0)
TypeError: an integer is required (got type str)


Some Ray subprcesses exited unexpectedly:
  log_monitor [exit code=1]

Remaining processes will be killed.
2021-03-24 14:16:55,384	ERROR worker.py:1109 -- listen_error_messages_raylet: Connection closed by server.
2021-03-24 14:16:55,384	ERROR worker.py:919 -- print_logs: Connection closed by server.
2021-03-24 14:16:55,385	ERROR import_thread.py:89 -- ImportThread: Connection closed by server.
Connection to 10.230.2.209 closed.
Aborted (core dumped)
```

**Comment by Deathn0t** [comment]
I am using Ray 1.2.0 and here are the logs:
[session_logs.tar.gz](https://github.com/ray-project/ray/files/6198036/session_logs.tar.gz)

**Comment by TanjaBayer** [comment]
Seeing the same error on a single node cluster, using also ray 1.2.0, there is no error before, everything works fine. With lower load we did not see this error, but now that we have some more load I see the error appear more often.
```
2021-03-31 11:42:01,869 ray.worker                     WARNING  The log monitor on node 0f974a7f-40f4-46bf-851e-e18d1c2b857f failed with the following error:
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/ray/log_monitor.py", line 359, in <module>
    log_monitor.run()
  File "/root/.local/lib/python3.7/site-packages/ray/log_monitor.py", line 280, in run
    self.open_closed_files()
  File "/root/.local/lib/python3.7/site-packages/ray/log_monitor.py", line 167, in open_closed_files
    self.close_all_files()
  File "/root/.local/lib/python3.7/site-packages/ray/log_monitor.py", line 102, in close_all_files
    os.kill(file_info.worker_pid, 0)
TypeError: an integer is required (got type str)

```

**Comment by Deathn0t** [comment]
This workaround did the trick for me @TanjaBayer , in your `.local/lib/python3.7/site-packages/ray/log_monitor.py` line 102, replace

```python
if (file_info.worker_pid != "raylet" and file_info.worker_pid != "gcs_server"):
    os.kill(file_info.worker_pid, 0)
```

with 

```python
if type(file_info.worker_pid) is int:
    os.kill(file_info.worker_pid, 0)
```

**Comment by TanjaBayer** [comment]
> This workaround did the trick for me @TanjaBayer , in your `.local/lib/python3.7/site-packages/ray/log_monitor.py` line 102, replace

That's not really a possible solution for automatic deployment, we are automatically building our dockers so we would need to include a script which overwrites the log_monitor.py. I mean that is possible, but wold be a bit hacky :smile: 

But this is happening now really often, has there been any changes on the 1.2.0 packages?

**Comment by TanjaBayer** [comment]
An interesting information might also be it for us it only happens after several hours (20+h), it did not yet see it appearing earlier.

**Comment by rkooo567** [comment]
@TanjaBayer There was a bit of change in `log_monitor`. I think we can have a quick patch PR.
