### ISSUE TITLE
test_client failed in Windows CI Failure

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#13202]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
```
2021-01-05T06:49:39.6523832Z [32mINFO: [0mFrom Testing //python/ray/tests:test_client:
2021-01-05T06:49:39.6524734Z ==================== Test output for //python/ray/tests:test_client:
2021-01-05T06:49:39.6525487Z ============================= test session starts =============================
2021-01-05T06:49:39.6527005Z platform win32 -- Python 3.7.9, pytest-5.4.3, py-1.10.0, pluggy-0.13.1 -- C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe
2021-01-05T06:49:39.6528117Z cachedir: .pytest_cache
2021-01-05T06:49:39.6529164Z rootdir: C:\Users\runneradmin\AppData\Local\Temp\Bazel.runfiles_qcqnjxzu\runfiles\com_github_ray_project_ray
2021-01-05T06:49:39.6531081Z plugins: asyncio-0.14.0, rerunfailures-9.1.1, sugar-0.9.4, timeout-1.4.2
2021-01-05T06:49:39.6532100Z collecting ... collected 12 items
2021-01-05T06:49:39.6532594Z 
2021-01-05T06:49:39.6533374Z ::test_real_ray_fallback PASSED                                          [  8%]
2021-01-05T06:49:39.6534413Z ::test_nested_function PASSED                                            [ 16%]
2021-01-05T06:49:39.6535369Z ::test_put_get PASSED                                                    [ 25%]
2021-01-05T06:49:39.6536170Z ::test_wait PASSED                                                       [ 33%]
2021-01-05T06:49:39.6537559Z ::test_remote_functions PASSED                                           [ 41%]
2021-01-05T06:49:39.6543322Z ::test_function_calling_function PASSED                                  [ 50%]
2021-01-05T06:49:39.6544272Z ::test_basic_actor PASSED                                                [ 58%]
2021-01-05T06:49:39.6545207Z ::test_pass_handles PASSED                                               [ 66%]
2021-01-05T06:49:39.6548278Z ::test_basic_log_stream PASSED                                           [ 75%]
2021-01-05T06:49:39.6555764Z ::test_stdout_log_stream FAILED                                          [ 83%]
2021-01-05T06:49:39.6561858Z ::test_create_remote_before_start PASSED                                 [ 91%]
2021-01-05T06:49:39.6562843Z ::test_basic_named_actor PASSED                                          [100%]
2021-01-05T06:49:39.6563373Z 
2021-01-05T06:49:39.6563986Z ================================== FAILURES ===================================
2021-01-05T06:49:39.6564700Z ___________________________ test_stdout_log_stream ____________________________
2021-01-05T06:49:39.6565181Z 
2021-01-05T06:49:39.6566857Z ray_start_regular_shared = {'metrics_export_port': 65486, 'node_id': 'f5e201fd08fc12e50fca77e20347dbe51baae7da32d6c36cde0590e0', 'node_ip_address': '10.1.0.4', 'object_store_address': 'tcp://127.0.0.1:65375', ...}
2021-01-05T06:49:39.6568279Z 
2021-01-05T06:49:39.6568980Z     def test_stdout_log_stream(ray_start_regular_shared):
2021-01-05T06:49:39.6569783Z         with ray_start_client_server() as ray:
2021-01-05T06:49:39.6571155Z             log_msgs = []
2021-01-05T06:49:39.6572080Z     
2021-01-05T06:49:39.6572662Z             def test_log(level, msg):
2021-01-05T06:49:39.6573338Z                 log_msgs.append(msg)
2021-01-05T06:49:39.6573942Z     
2021-01-05T06:49:39.6574640Z             ray.worker.log_client.stdstream = test_log
2021-01-05T06:49:39.6575340Z     
2021-01-05T06:49:39.6575888Z             @ray.remote
2021-01-05T06:49:39.6576558Z             def print_on_stderr_and_stdout(s):
2021-01-05T06:49:39.6583321Z                 print(s)
2021-01-05T06:49:39.6584070Z                 print(s, file=sys.stderr)
2021-01-05T06:49:39.6585255Z     
2021-01-05T06:49:39.6586134Z             time.sleep(1)
2021-01-05T06:49:39.6587031Z             print_on_stderr_and_stdout.remote("Hello world")
2021-01-05T06:49:39.6587736Z             time.sleep(1)
2021-01-05T06:49:39.6588260Z >           assert len(log_msgs) == 2
2021-01-05T06:49:39.6588721Z E           assert 4 == 2
2021-01-05T06:49:39.6589163Z E             +4
2021-01-05T06:49:39.6589591Z E             -2
2021-01-05T06:49:39.6590010Z 
2021-01-05T06:49:39.6592094Z \\?\C:\Users\RUNNER~1\AppData\Local\Temp\Bazel.runfiles_qcqnjxzu\runfiles\com_github_ray_project_ray\python\ray\tests\test_client.py:262: AssertionError
2021-01-05T06:49:39.6593334Z ---------------------------- Captured stdout call -----------------------------
2021-01-05T06:49:39.6593985Z [2m[36m(pid=4660)[0m Hello world
2021-01-05T06:49:39.6594319Z 
2021-01-05T06:49:39.6594944Z ---------------------------- Captured stderr call -----------------------------
2021-01-05T06:49:39.6596064Z 2021-01-05 06:48:29,352	INFO dataservicer.py:25 -- New data connection from client 1c4eaadc8cfd42a0aa1b4e91b4490254
2021-01-05T06:49:39.6597240Z 2021-01-05 06:48:29,354	INFO logservicer.py:85 -- New logs connection
2021-01-05T06:49:39.6598525Z 2021-01-05 06:48:29,670	WARNING worker.py:1044 -- The agent on node fv-az68-689 failed with the following error:
2021-01-05T06:49:39.6599297Z Traceback (most recent call last):
2021-01-05T06:49:39.6600055Z   File "d:\a\ray\ray\python\ray\new_dashboard/agent.py", line 311, in <module>
2021-01-05T06:49:39.6600995Z     loop.run_until_complete(agent.run())
2021-01-05T06:49:39.6602087Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\asyncio\base_events.py", line 587, in run_until_complete
2021-01-05T06:49:39.6603243Z     return future.result()
2021-01-05T06:49:39.6603973Z   File "d:\a\ray\ray\python\ray\new_dashboard/agent.py", line 187, in run
2021-01-05T06:49:39.6604716Z     await asyncio.gather(check_parent_task,
2021-01-05T06:49:39.6605640Z UnboundLocalError: local variable 'check_parent_task' referenced before assignment
2021-01-05T06:49:39.6606253Z 
2021-01-05T06:49:39.6606916Z The agent on node fv-az68-689 failed with the following error:
2021-01-05T06:49:39.6607613Z Traceback (most recent call last):
2021-01-05T06:49:39.6608359Z   File "d:\a\ray\ray\python\ray\new_dashboard/agent.py", line 311, in <module>
2021-01-05T06:49:39.6609084Z     loop.run_until_complete(agent.run())
2021-01-05T06:49:39.6610026Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\asyncio\base_events.py", line 587, in run_until_complete
2021-01-05T06:49:39.6611145Z     return future.result()
2021-01-05T06:49:39.6611863Z   File "d:\a\ray\ray\python\ray\new_dashboard/agent.py", line 187, in run
2021-01-05T06:49:39.6612636Z     await asyncio.gather(check_parent_task,
2021-01-05T06:49:39.6613698Z UnboundLocalError: local variable 'check_parent_task' referenced before assignment
2021-01-05T06:49:39.6614307Z 
2021-01-05T06:49:39.6614856Z [2m[36m(pid=None)[0m Traceback (most recent call last):
2021-01-05T06:49:39.6615268Z 
2021-01-05T06:49:39.6615900Z [2m[36m(pid=None)[0m   File "d:\a\ray\ray\python\ray\new_dashboard/agent.py", line 322, in <module>
2021-01-05T06:49:39.6616444Z 
2021-01-05T06:49:39.6616962Z [2m[36m(pid=None)[0m     raise e
2021-01-05T06:49:39.6617294Z 
2021-01-05T06:49:39.6617961Z [2m[36m(pid=None)[0m   File "d:\a\ray\ray\python\ray\new_dashboard/agent.py", line 311, in <module>
2021-01-05T06:49:39.6618646Z 
2021-01-05T06:49:39.6619218Z [2m[36m(pid=None)[0m     loop.run_until_complete(agent.run())
2021-01-05T06:49:39.6619657Z 
2021-01-05T06:49:39.6620555Z [2m[36m(pid=None)[0m   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\asyncio\base_events.py", line 587, in run_until_complete
2021-01-05T06:49:39.6621246Z 
2021-01-05T06:49:39.6621820Z [2m[36m(pid=None)[0m     return future.result()
2021-01-05T06:49:39.6622222Z 
2021-01-05T06:49:39.6622876Z [2m[36m(pid=None)[0m   File "d:\a\ray\ray\python\ray\new_dashboard/agent.py", line 187, in run
2021-01-05T06:49:39.6623396Z 
2021-01-05T06:49:39.6624003Z [2m[36m(pid=None)[0m     await asyncio.gather(check_parent_task,
2021-01-05T06:49:39.6624468Z 
2021-01-05T06:49:39.6625265Z [2m[36m(pid=None)[0m UnboundLocalError: local variable 'check_parent_task' referenced before assignment
2021-01-05T06:49:39.6625874Z 
2021-01-05T06:49:39.6626378Z [2m[36m(pid=None)[0m --- Logging error ---
2021-01-05T06:49:39.6626941Z 
2021-01-05T06:49:39.6627505Z [2m[36m(pid=None)[0m Traceback (most recent call last):
2021-01-05T06:49:39.6627918Z 
2021-01-05T06:49:39.6628795Z [2m[36m(pid=None)[0m   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\logging\handlers.py", line 69, in emit
2021-01-05T06:49:39.6629429Z 
2021-01-05T06:49:39.6630031Z [2m[36m(pid=None)[0m     if self.shouldRollover(record):
2021-01-05T06:49:39.6630495Z 
2021-01-05T06:49:39.6631291Z [2m[36m(pid=None)[0m   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\logging\handlers.py", line 183, in shouldRollover
2021-01-05T06:49:39.6631980Z 
2021-01-05T06:49:39.6632508Z [2m[36m(pid=None)[0m     self.stream = self._open()
2021-01-05T06:49:39.6632909Z 
2021-01-05T06:49:39.6633654Z [2m[36m(pid=None)[0m   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\logging\__init__.py", line 1116, in _open
2021-01-05T06:49:39.6634251Z 
2021-01-05T06:49:39.6635011Z [2m[36m(pid=None)[0m     return open(self.baseFilename, self.mode, encoding=self.encoding)
2021-01-05T06:49:39.6635646Z 
2021-01-05T06:49:39.6636162Z [2m[36m(pid=None)[0m NameError: name 'open' is not defined
2021-01-05T06:49:39.6636643Z 
2021-01-05T06:49:39.6637105Z [2m[36m(pid=None)[0m Call stack:
2021-01-05T06:49:39.6637439Z 
2021-01-05T06:49:39.6638276Z [2m[36m(pid=None)[0m   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\aiohttp\client.py", line 320, in __del__
2021-01-05T06:49:39.6638963Z 
2021-01-05T06:49:39.6640087Z [2m[36m(pid=None)[0m     self._loop.call_exception_handler(context)
2021-01-05T06:49:39.6640598Z 
2021-01-05T06:49:39.6641433Z [2m[36m(pid=None)[0m   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\asyncio\base_events.py", line 1645, in call_exception_handler
2021-01-05T06:49:39.6642157Z 
2021-01-05T06:49:39.6642775Z [2m[36m(pid=None)[0m     self.default_exception_handler(context)
2021-01-05T06:49:39.6643249Z 
2021-01-05T06:49:39.6644132Z [2m[36m(pid=None)[0m   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\asyncio\base_events.py", line 1619, in default_exception_handler
2021-01-05T06:49:39.6644883Z 
2021-01-05T06:49:39.6646107Z [2m[36m(pid=None)[0m     logger.error('\n'.join(log_lines), exc_info=exc_info)
2021-01-05T06:49:39.6646594Z 
2021-01-05T06:49:39.6647599Z [2m[36m(pid=None)[0m Message: 'Unclosed client session\nclient_session: <aiohttp.client.ClientSession object at 0x000002322D46AD08>'
2021-01-05T06:49:39.6648414Z 
2021-01-05T06:49:39.6648847Z [2m[36m(pid=None)[0m Arguments: ()
2021-01-05T06:49:39.6649194Z 
2021-01-05T06:49:39.6649646Z [2m[36m(pid=4660)[0m Hello world
2021-01-05T06:49:39.6649970Z 
2021-01-05T06:49:39.6650869Z 2021-01-05 06:48:31,363	INFO dataservicer.py:53 -- Lost data connection from client 1c4eaadc8cfd42a0aa1b4e91b4490254
2021-01-05T06:49:39.6651879Z =========================== short test summary info ===========================
2021-01-05T06:49:39.6652541Z FAILED ::test_stdout_log_stream - assert 4 == 2
2021-01-05T06:49:39.6654235Z ======================== 1 failed, 11 passed in 30.95s ========================
```

https://github.com/ray-project/ray/runs/1647962851
### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by amogkam** [comment]
This has gotten worse- now a bunch of different tests in this suite are failing (https://github.com/ray-project/ray/runs/1689819726?check_suite_focus=true):

```
::test_real_ray_fallback FAILED                                          [ 14%]
::test_nested_function The agent on node fv-az177-498 failed with the following error:
Traceback (most recent call last):
  File "d:\a\ray\ray\python\ray\new_dashboard/agent.py", line 311, in <module>
    loop.run_until_complete(agent.run())
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "d:\a\ray\ray\python\ray\new_dashboard/agent.py", line 187, in run
    await asyncio.gather(check_parent_task,
UnboundLocalError: local variable 'check_parent_task' referenced before assignment

FAILED                                            [ 21%]
::test_put_get FAILED                                                    [ 28%]
::test_wait FAILED                                                       [ 35%]
::test_remote_functions FAILED                                           [ 42%]
::test_function_calling_function FAILED                                  [ 50%]
::test_basic_actor FAILED                                                [ 57%]
::test_pass_handles FAILED                                               [ 64%]
::test_basic_log_stream FAILED                                           [ 71%]
::test_stdout_log_stream FAILED                                          [ 78%]
::test_create_remote_before_start FAILED                                 [ 85%]
::test_basic_named_actor FAILED                                          [ 92%]
::test_internal_kv FAILED                                                [100%]
```

**Comment by amogkam** [comment]
@ericl @pcmoritz I believe this regression is caused by https://github.com/ray-project/ray/pull/13326.

Can you guys either:
1. Revert it (I can't do it due to conflicts)
2. Temporarily skip `test_client` on Windows, raise a new issue to re-enable it, and make a note on the documentation that it is experimental on Windows.

Thanks!

**Comment by ericl** [comment]
@barakmich please take a quick look, otherwise we can disable it on Windows

**Comment by barakmich** [comment]
This looks like there's more at play here than just client. The error above (and in the logs) mostly has to do with an exception coming from inside `new_dashboard` -- now, granted, this is happening underneath the call to ```with ray_start_client_server() as ray:``` in the client tests.

Not to mention a bunch of the failures happening in tests that are neither in a RAY_CLIENT_MODE=1 enabled test or in a test_client test, such as the error 
```   ray.exceptions.ObjectStoreFullError: Failed to put object ffffffffffffffffffffffffffffffffffffffff0100000042000000 in object store because it is full. Object size is 41943287 bytes.
E   The local object store is full of objects that are still in scope and cannot be evicted. Tip: Use the `ray memory` command to list active objects in the cluster.
``` 
from `test_return_object_ref` in `test_reference_counting_2.py`

So as it regards client, starting something in ray in the different way we do for client tests is causing an issue -- which I've been wanting to fix in our tests anyway -- but I think client is exposing the underlying bug instead of causing it.

If you must, disable on Windows, but I'd also get someone else from dashboard to take a quick look too.
