### ISSUE TITLE
PolicyServerInput with num_workers equal more than 1 will result that "Address already in use" problem

### ISSUE THREAD

**Issue by herunyu** [ray-project/ray#13226]
### What is the problem?
PolicyServerInput with num_workers equal more than 1 will result that "Address already in use" problem
*Ray version and other system information (Python version, TensorFlow version, OS):*
* ray: 1.1.0
* python: 3.8.5
* tensorflow:  2.3.1
* OS: macOS 11.1 or Ubuntu 20.04.1 LTS
### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```python
env = "CartPole-v0"
    connector_config = {
        # Use the connector server to generate experiences.
        "input": (
            lambda ioctx: PolicyServerInput(ioctx, SERVER_ADDRESS, SERVER_PORT)
        ),
        # Use a single worker process to run the server.
        "num_workers": 2,
        # Disable OPE, since the rollouts are coming from online clients.
        "input_evaluation": [],
    }

trainer = PPOTrainer(
            env=env,
            config=dict(
                connector_config, **{
                    "rollout_fragment_length": 1000,
                    "train_batch_size": 4000,
                    "framework": args.framework,
                }))

checkpoint_path = CHECKPOINT_FILE.format(args.run)

    # Attempt to restore from checkpoint if possible.
    if os.path.exists(checkpoint_path):
        checkpoint_path = open(checkpoint_path).read()
        print("Restoring from checkpoint path", checkpoint_path)
        trainer.restore(checkpoint_path)

    # Serving and training loop
    while True:
        print(pretty_print(trainer.train()))
        checkpoint = trainer.save()
        print("Last checkpoint", checkpoint)
        with open(checkpoint_path, "w") as f:
            f.write(checkpoint)
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

I am trying to use more rollout workers for training but when I use num_workers > 1 it will get the following error:

---

python cartpole_server.py
WARNING:tensorflow:From /Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2021-01-06 11:56:45,532 INFO services.py:1171 -- View the Ray dashboard at http://127.0.0.1:8265
2021-01-06 11:56:47,585 INFO trainer.py:591 -- Tip: set framework=tfe or the --eager flag to enable TensorFlow eager execution
2021-01-06 11:56:47,586 INFO trainer.py:616 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=47224) WARNING:tensorflow:From /Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=47224) Instructions for updating:
(pid=47224) non-resource variables are not supported in the long term
(pid=47228) WARNING:tensorflow:From /Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=47228) Instructions for updating:
(pid=47228) non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "cartpole_server.py", line 54, in <module>
    trainer = PPOTrainer(
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 106, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 465, in __init__
    super().__init__(config, logger_creator)
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/tune/trainable.py", line 96, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 629, in setup
    self._init(self.config, self.env_creator)
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 133, in _init
    self.workers = self._make_workers(
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 700, in _make_workers
    return WorkerSet(
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 79, in __init__
    remote_spaces = ray.get(self.remote_workers(
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/worker.py", line 1379, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(OSError): ray::RolloutWorker.foreach_policy() (pid=47224, ip=10.11.241.166)
  File "python/ray/_raylet.pyx", line 422, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 456, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 415, in ray._raylet.execute_task.function_executor
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 607, in __init__
    self.input_reader: InputReader = input_creator(self.io_context)
  File "cartpole_server.py", line 34, in <lambda>
    lambda ioctx: PolicyServerInput(ioctx, SERVER_ADDRESS, SERVER_PORT)
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/env/policy_server_input.py", line 88, in __init__
    HTTPServer.__init__(self, (address, port), handler)
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use

---

It looks like when creating multiple servers, it uses the same port. Does ray support multiple rollout workers for policy server and policy client?

**Comment by ericl** [comment]
This is expected --- you should use num_workers 0 or 1 for policy server input. There is not generally the need for multiple policy servers, if you do need that then you can customize the ports manually.

**Comment by herunyu** [comment]
Thanks for replying. @ericl So if I customize the ports for multiple policy servers, is it going to train multiple models? Can I make them training the same model?

**Comment by ericl** [comment]
RLlib will sync the model params internally, similar to when using multiple
workers normally.

**Comment by herunyu** [comment]
So for example I can first launch one server and train it and store the parameters. Then I can launch like 5 more servers and restore the same parameters and then continue to train? RLlib will sync the params? Am I understand it correctly?

**Comment by herunyu** [comment]
Also, when num_workers is 1, I cannot train as well, would you mind take a look at this issue? @ericl  #13227

**Comment by ericl** [comment]
Yes. I would recommend only using 1 server (and num workers zero). It is
unlikely you can saturate the throughput of one server unless you have
hundreds of clients.

**Comment by herunyu** [comment]
Well, we actually trying to use the ability of parallelism from ray to train the model. So if can speed up the training process, we may turn on hundreds clients though. So is there any references for us to check on how to use multiple servers and utilize all cpu cores and gpus to train the model?
