### ISSUE TITLE
Tenant ID, application ID, principal ID, and scope are not allowed to be updated.

### ISSUE THREAD

**Issue by GiovanniGatti** [ray-project/ray#13259]
Hello, while following instructions presented at [Launching Cloud Clusters >> Azure](https://docs.ray.io/en/master/cluster/cloud.html?highlight=azure#aws-gcp-azure), deployment is falling with the following message:

```
$ ray --version
ray, version 1.1.0

$ ray up ~/shared/example-full.yaml 
Cluster: default

Checking Azure environment settings
2021-01-07 10:27:41,768	INFO config.py:39 -- Using subscription id: <hidden>
2021-01-07 10:27:41,768	INFO config.py:53 -- Creating/Updating Resource Group: <hidden>
Traceback (most recent call last):
  File "/home/giovanni/.virtualenvs/azure-2/lib/python3.7/site-packages/msrestazure/polling/arm_polling.py", line 390, in run
    self._poll()
  File "/home/giovanni/.virtualenvs/azure-2/lib/python3.7/site-packages/msrestazure/polling/arm_polling.py", line 418, in _poll
    raise OperationFailed("Operation failed or cancelled")
msrestazure.polling.arm_polling.OperationFailed: Operation failed or cancelled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/giovanni/.virtualenvs/azure-2/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/giovanni/.virtualenvs/azure-2/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1504, in main
    return cli()
  File "/home/giovanni/.virtualenvs/azure-2/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/giovanni/.virtualenvs/azure-2/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/giovanni/.virtualenvs/azure-2/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/giovanni/.virtualenvs/azure-2/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/giovanni/.virtualenvs/azure-2/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/giovanni/.virtualenvs/azure-2/lib/python3.7/site-packages/ray/scripts/scripts.py", line 893, in up
    use_login_shells=use_login_shells)
  File "/home/giovanni/.virtualenvs/azure-2/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 213, in create_or_update_cluster
    config = _bootstrap_config(config, no_config_cache=no_config_cache)
  File "/home/giovanni/.virtualenvs/azure-2/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 287, in _bootstrap_config
    resolved_config = provider_cls.bootstrap_config(config)
  File "/home/giovanni/.virtualenvs/azure-2/lib/python3.7/site-packages/ray/autoscaler/_private/azure/node_provider.py", line 298, in bootstrap_config
    return bootstrap_azure(cluster_config)
  File "/home/giovanni/.virtualenvs/azure-2/lib/python3.7/site-packages/ray/autoscaler/_private/azure/config.py", line 21, in bootstrap_azure
    config = _configure_resource_group(config)
  File "/home/giovanni/.virtualenvs/azure-2/lib/python3.7/site-packages/ray/autoscaler/_private/azure/config.py", line 82, in _configure_resource_group
    parameters=parameters).wait()
  File "/home/giovanni/.virtualenvs/azure-2/lib/python3.7/site-packages/msrest/polling/poller.py", line 201, in wait
    raise self._exception  # type: ignore
  File "/home/giovanni/.virtualenvs/azure-2/lib/python3.7/site-packages/msrest/polling/poller.py", line 152, in _start
    self._polling_method.run()
  File "/home/giovanni/.virtualenvs/azure-2/lib/python3.7/site-packages/msrestazure/polling/arm_polling.py", line 400, in run
    raise CloudError(self._response)
msrestazure.azure_exceptions.CloudError: Azure Error: DeploymentFailed
Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.
Exception Details:
	Error Code: BadRequest
	Message: {'error': {'code': 'RoleAssignmentUpdateNotPermitted', 'message': 'Tenant ID, application ID, principal ID, and scope are not allowed to be updated.'}}
```

I have owner privileges and I was able to deploy Ray using the "Deploy" button.

Could you please clarify what it is going on? Should I rather check with Azure community?

Thanks,
Giovanni.

**Comment by rkooo567** [comment]
cc @AmeerHajAli

**Comment by GiovanniGatti** [comment]
I finally got it to work!
The hint fix came from: [Azure DevOps pipeline error: Tenant ID, application ID, principal ID, and scope are not allowed to be updated](https://stackoverflow.com/questions/61637124/azure-devops-pipeline-error-tenant-id-application-id-principal-id-and-scope).

I'm not exactly an expert on the subject, but on my first try ray cluster failed to initialize. Unfortunately it left behind a stale state.

Essentially it will create roles and assign them to resources (e.g. ray-msi-user-identity). After (manually) deleting the mess it created during the first try, those role identities were not properly deleted, blocking them to instantiate a new cluster.

To clean it up, go to "Access Control IAM" >> "Role assignments"

![image](https://user-images.githubusercontent.com/1745450/105200131-cb7d8400-5b3f-11eb-8e07-d47d735a206f.png)

You will probably see some roles with "unknown identities". They are very likely the stale identities blocking ray. Delete them by hand and you should be fine.
