### ISSUE TITLE
Launch

### ISSUE THREAD

**Issue by jtm101-code** [ray-project/ray#13340]
The problem I have is that ray will not distribute over my workers
I collectively I have 16 cores if i user 1 worker (head 8, worker 8), as I have 8cpus on each ec2 aws instance of ubuntu.
However when I launch my ray cluster, and submit my python script it only distributes over 8 cores as only 8 pids are showing to be utilized.

its also noteworthy than im unable to access the ray dashboard on the EC2 instance, I only have this information by printing the pids being used.

How do I get my script to be utlized by all 16 cpus and therefore show 16pids being used to execute the script?

Also why does it not launch the workers on aws ec2--> instances dashboard in aws console . There are no workers to be found. Please can someone advise why it does not launch workers, but only the head?

    $ ray submit cluster.yaml ray_test.py --start

This is the updated config:

    cluster_name: ray_cluster
    
    min_workers: 3
    max_workers: 3
    
    # Cloud-provider specific configuration.
    provider:
        type: aws
        region: eu-west-2
        # availability_zone: us-west-2b
    
    auth:
        ssh_user: ubuntu
    
    head_node:
        InstanceType: c5.2xlarge
        ImageId: latest_dlami  # Default Ubuntu 16.04 AMI.
    
    worker_nodes:
        InstanceType: c5.2xlarge
        ImageId: latest_dlami  # Default Ubuntu 16.04 AMI.
    
    
    # List of shell commands to run to set up nodes.
    setup_commands:
        # Consider uncommenting these if you run into dpkg locking issues
    #    - sudo pkill -9 apt-get || true
    #    - sudo pkill -9 dpkg || true
    #    - sudo dpkg --configure -a
        # Install basics.
        - sudo apt-get update
        - sudo apt-get install -y build-essential
        - sudo apt-get install curl
        - sudo apt-get install unzip
        # Install Node.js in order to build the dashboard.
        - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash
        - sudo apt-get install -y nodejs
        # Install Anaconda.
        - wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh || true
        - bash Anaconda3-5.0.1-Linux-x86_64.sh -b -p $HOME/anaconda3 || true
        - echo 'export PATH="$HOME/anaconda3/bin:$PATH"' >> ~/.bashrc
        # Build  env
    
        - conda create --name ray_env
        - conda activate ray_env
        - conda install --name ray_env pip
        - pip install --upgrade pip
        - pip install ray[all]
        - conda install -c conda-forge xgboost
    
    
    # Custom commands that will be run on the head node after common setup.
    head_setup_commands:
        - source activate ray_env
    
    # Custom commands that will be run on worker nodes after common setup.
    worker_setup_commands:
        - source activate ray_env
    
    # Command to start ray on the head node. You don't need to change this.
    head_start_ray_commands:
        - ray stop
        - ulimit -n 65536; ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml
    
    # Command to start ray on worker nodes. You don't need to change this.
    worker_start_ray_commands:
        - ray stop
        - ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379
    
    
    # If a node is idle for this many minutes, it will be removed.
    idle_timeout_minutes: 5

This is the updated ray_test.py:
    
    #This imports successfully with config and conda env
    import ray
    import time
    import xgboost
    
    
    
    
    def printer():
        print("INSIDE WORKER " + str(time.time()) +"  PID  :    "+  str(os.getpid()))
    
    
    # decorators allow for futures to be created for parallelization
    @ray.remote        
    def func_1():
        count = 0
        for i in range(100000000):
            count += 1
        printer()
        return count
            
            
    @ray.remote        
    def func_2():
        count = 0
        for i in range(100000000):
            count += 1
        printer()
        return count
    
        
    @ray.remote
    def func_3():
        count = 0
        for i in range(100000000):
            count += 1
        printer()
        return count
    
    def main():
        start = time.time()
        results = []
        
        ray.init(address='auto')
        #append fuction futures
        for i in range(1000):
            results.append(func_1.remote())
            results.append(func_2.remote())
            results.append(func_3.remote())
            
        #run in parrallel and get aggregated list
        a = ray.get(results)
        b = 0
        
        #add all values in list together
        for j in range(len(a)):
            b += a[j]
        print(b)
        
        #time to complete
        end = time.time()
        print(end - start)
        
        
    if __name__ == '__main__':
        main()

**Comment by krfricke** [comment]
Hm, is there any specific reason why you're not using docker containers?

Can you post the output of `/tmp/ray/session_latest/logs/monitor.log` and `monitor.err`?

Also cc @rkooo567

**Comment by jtm101-code** [comment]
Hi krfricke, thank you for replying. 

Essentially, the problem i’m looking to solve is that I have a large code base, where within the pipeline of this code base I wish to multiprocess some functions that are currently just running in a for loop, (takes 50 hours to complete!). 

My first attempt was to try it with a docker container, however for the life of me, I could not get it to work. What I have found is that ray handles docker images very differently. For example I create a simple docker image, push it to docker hub, and pull it to another machine, and the image will execute fine. With ray it will not. I have had numerous variable errors. 

What I want to do is run my docker file of my pipeline on a ray cluster. But it will not work, due to a bootstrap permissions error. 

So I started simple and wanted to execute a basic script in a docker image on ray. This link on stack was my issue. It did not work. So I gave up with docker, and seeked to do this by pulling my codebase from github into the cluster, and install all my dependencies with a yaml onto a conda env. And run it within that as a compromise. However now I have these worker issues.  

https://stackoverflow.com/questions/65570374/launching-a-simple-python-script-on-an-aws-ray-cluster-with-docker


So this was my original error I got from the set up I previously posted. There is an worker_ID issue.
```



(base) xxx@xxxxxxxxx:~/RAY_AWS_HUB$ ray exec /home/xxx/RAY_AWS_HUB/3dml-pipeline/ray-aws/working_examples/basic_yaml_install/cluster.yaml 'tail -n 100 -f /tmp/ray/session_latest/logs/monitor*'
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.

Fetched IP: xxxxx.xx.xx.xxx

==> /tmp/ray/session_latest/logs/monitor.err <==
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 854, in custom_excepthook
    worker_id = global_worker.worker_id
AttributeError: 'Worker' object has no attribute 'worker_id'

Original exception was:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 390, in <module>
    redis_password=args.redis_password)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 111, in __init__
    self.load_metrics)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 76, in __init__
    self.reset(errors_fatal=True)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 490, in reset
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 452, in reset
    self.available_node_types = self.config["available_node_types"]
KeyError: 'available_node_types'

==> /tmp/ray/session_latest/logs/monitor.log <==

==> /tmp/ray/session_latest/logs/monitor.out <==



I then solved this by changing the ray version to ray==1.0

Eg. - conda create --name ray_env
- conda activate ray_env
- conda install --name ray_env pip
- pip install --upgrade pip
- pip install ray==1.0
- conda install -c conda-forge xgboost


```

But then the workers still did not launch, but the logs changed:

```

(base) xxxx@xxxx-xxxxxx~/RAY_AWS_HUB$ ray exec /home/xxxx/RAY_AWS_HUB/3dml-pipeline/ray-aws/working_examples/basic_yaml_install/cluster.yaml 'tail -n 100 -f /tmp/ray/session_latest/logs/monitor*'
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.

Fetched IP: xxxx.xxx
Warning: Permanently added 'xxxx.xxx' (ECDSA) to the list of known hosts.

==> /tmp/ray/session_latest/logs/monitor.err <==
     'file_mounts': {},
     'file_mounts_sync_continuously': False,
     'head_node': {'IamInstanceProfile': {'Arn': 'arn:aws:iam::959016931546:instance-profile/ray-autoscaler-v1'},
                   'ImageId': 'ami-0755b39fd4dab7cbe',
                   'InstanceType': 'c5.2xlarge',
                   'KeyName': 'ray-autoscaler_1_eu-west-2',
                   'SecurityGroupIds': ['sg-068ba3768a04fbe71'],
                   'SubnetIds': ['subnet-c5bdd5ac',
                                 'subnet-ca52a986',
                                 'subnet-f9a31783']},
     'head_setup_commands': ['sudo apt-get update',
                             'sudo apt-get install -y build-essential',
                             'sudo apt-get install curl',
                             'sudo apt-get install unzip',
                             'curl -sL '
                             'https://deb.nodesource.com/setup_12.x | sudo '
                             '-E bash',
                             'sudo apt-get install -y nodejs',
                             'wget '
                             'https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh '
                             '|| true',
                             'bash Anaconda3-5.0.1-Linux-x86_64.sh -b -p '
                             '$HOME/anaconda3 || true',
                             "echo 'export "
                             'PATH="$HOME/anaconda3/bin:$PATH"\' >> '
                             '~/.bashrc',
                             'conda create --name ray_env',
                             'conda activate ray_env',
                             'conda install --name ray_env pip',
                             'pip install --upgrade pip',
                             'pip install ray==1.0',
                             'conda install -c conda-forge xgboost',
                             'source activate ray_env'],
     'head_start_ray_commands': ['ray stop',
                                 'ulimit -n 65536; ray start --head '
                                 '--port=6379 '
                                 '--autoscaling-config=~/ray_bootstrap_config.yaml'],
     'idle_timeout_minutes': 5,
     'initial_workers': 0,
     'initialization_commands': [],
     'max_workers': 3,
     'min_workers': 3,
     'no_restart': False,
     'provider': {'region': 'eu-west-2', 'type': 'aws'},
     'rsync_exclude': [],
     'rsync_filter': [],
     'setup_commands': ['sudo apt-get update',
                        'sudo apt-get install -y build-essential',
                        'sudo apt-get install curl',
                        'sudo apt-get install unzip',
                        'curl -sL https://deb.nodesource.com/setup_12.x | '
                        'sudo -E bash',
                        'sudo apt-get install -y nodejs',
                        'wget '
                        'https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh '
                        '|| true',
                        'bash Anaconda3-5.0.1-Linux-x86_64.sh -b -p '
                        '$HOME/anaconda3 || true',
                        'echo \'export PATH="$HOME/anaconda3/bin:$PATH"\' '
                        '>> ~/.bashrc',
                        'conda create --name ray_env',
                        'conda activate ray_env',
                        'conda install --name ray_env pip',
                        'pip install --upgrade pip',
                        'pip install ray==1.0',
                        'conda install -c conda-forge xgboost'],
     'target_utilization_fraction': 0.8,
     'worker_nodes': {'ImageId': 'ami-0755b39fd4dab7cbe',
                      'InstanceType': 'c5.2xlarge',
                      'KeyName': 'ray-autoscaler_1_eu-west-2',
                      'SecurityGroupIds': ['xxxx768a04fbe71'],
                      'SubnetIds': ['subnet-c5bdd5ac',
                                    'subnet-xxx986',
                                    'subnet-fxxxx783']},
     'worker_setup_commands': ['sudo apt-get update',
                               'sudo apt-get install -y build-essential',
                               'sudo apt-get install curl',
                               'sudo apt-get install unzip',
                               'curl -sL '
                               'https://deb.nodesource.com/setup_12.x | '
                               'sudo -E bash',
                               'sudo apt-get install -y nodejs',
                               'wget '
                               'https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh '
                               '|| true',
                               'bash Anaconda3-5.0.1-Linux-x86_64.sh -b -p '
                               '$HOME/anaconda3 || true',
                               "echo 'export "
                               'PATH="$HOME/anaconda3/bin:$PATH"\' >> '
                               '~/.bashrc',
                               'conda create --name ray_env',
                               'conda activate ray_env',
                               'conda install --name ray_env pip',
                               'pip install --upgrade pip',
                               'pip install ray==1.0',
                               'conda install -c conda-forge xgboost',
                               'source activate ray_env'],
     'worker_start_ray_commands': ['ray stop',
                                   'ulimit -n 65536; ray start '
                                   '--address=$RAY_HEAD_IP:6379']}

==> /tmp/ray/session_latest/logs/monitor.out <==


```
If I was to run it with a docker image, I would significantly prefer to do that, but I am yet to find a simple example/template that works. Eg running a simple python script on a docker image on a ray cluster, that also launches the workers. The rayproject example yamls are not what i'm looking for.

**Comment by rodalbuyeh** [comment]
Hi there @jtm101-code. not sure if you're still having this problem as years have passed -- but I will share in case this helps anyone else. You need to: 
1. make sure you install ray[default] on whatever instance/environment is running the ray up command. installing without the [default] declaration is a minimal installation that does not include everything needed for the cluster launcher.
2. in your `setup_commands`, you will also need to pip install ray[default]. 

One additional recommendation is to not leave this dependency unpinned or implicit on the setup_commands as it (at least as of version 2.9.3) will install an unstable nightly release of ray.
