### ISSUE TITLE
[ray client] Nasty error message when connecting to an invalid port

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#13347]
### What is the problem?

`ray start --ray-client-server-port=60123`

```python
ray.util.connect(60124)
```

```
(base) ray/serve % python test.py
Got Error from logger channel -- shutting down: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1610403864.288674000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4166,"referenced_errors":[{"created":"@1610403864.288656000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}"
>
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/eoakes/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/eoakes/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/eoakes/code/ray/python/ray/util/client/logsclient.py", line 51, in _log_main
    raise e
  File "/Users/eoakes/code/ray/python/ray/util/client/logsclient.py", line 42, in _log_main
    for record in log_stream:
  File "/Users/eoakes/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/Users/eoakes/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 803, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1610403864.288674000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4166,"referenced_errors":[{"created":"@1610403864.288656000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}"
```

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by barakmich** [comment]
Improved with the retry logic #13478
