### ISSUE TITLE
[core/win] Re-enable test_actor_resources::test_actor_multiple_gpus_from_multiple_tasks on Windows CI

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#13380]
### What is the problem?
https://github.com/ray-project/ray/runs/1689819726?check_suite_focus=true
```
================================== FAILURES ===================================
________________ test_actor_multiple_gpus_from_multiple_tasks _________________

ray_start_cluster = <ray.cluster_utils.Cluster object at 0x0000019AE2FA2FC8>

    def test_actor_multiple_gpus_from_multiple_tasks(ray_start_cluster):
        cluster = ray_start_cluster
        num_nodes = 5
        num_gpus_per_raylet = 5
        for i in range(num_nodes):
            cluster.add_node(
                num_cpus=10 * num_gpus_per_raylet,
                num_gpus=num_gpus_per_raylet,
                _system_config={"num_heartbeats_timeout": 1000} if i == 0 else {})
        ray.init(address=cluster.address)
    
        @ray.remote
        def create_actors(i, n):
            @ray.remote(num_gpus=1)
            class Actor:
                def __init__(self, i, j):
                    self.gpu_ids = ray.get_gpu_ids()
    
                def get_location_and_ids(self):
                    return ((ray.worker.global_worker.node.unique_id),
                            tuple(self.gpu_ids))
    
                def sleep(self):
                    time.sleep(100)
    
            # Create n actors.
            actors = []
            for j in range(n):
                actors.append(Actor.remote(i, j))
    
            locations = ray.get(
                [actor.get_location_and_ids.remote() for actor in actors])
    
            # Put each actor to sleep for a long time to prevent them from getting
            # terminated.
            for actor in actors:
                actor.sleep.remote()
    
            return locations
    
        all_locations = ray.get([
>           create_actors.remote(i, num_gpus_per_raylet) for i in range(num_nodes)
        ])

\\?\C:\Users\RUNNER~1\AppData\Local\Temp\Bazel.runfiles_my88lp6_\runfiles\com_github_ray_project_ray\python\ray\tests\test_actor_resources.py:273: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
d:\a\ray\ray\python\ray\_private\client_mode_hook.py:47: in wrapper
    return func(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

object_refs = [ObjectRef(764f8475f05bf001ffffffffffffffffffffffff0100000001000000), ObjectRef(2638cdc57fda8d43ffffffffffffffffffffff...e8c24317ffffffffffffffffffffffff0100000001000000), ObjectRef(b9c64831282591f9ffffffffffffffffffffffff0100000001000000)]

    @client_mode_hook
    def get(object_refs, *, timeout=None):
        """Get a remote object or a list of remote objects from the object store.
    
        This method blocks until the object corresponding to the object ref is
        available in the local object store. If this object is not in the local
        object store, it will be shipped from an object store that has it (once the
        object has been created). If object_refs is a list, then the objects
        corresponding to each object in the list will be returned.
    
        This method will issue a warning if it's running inside async context,
        you can use ``await object_ref`` instead of ``ray.get(object_ref)``. For
        a list of object refs, you can use ``await asyncio.gather(*object_refs)``.
    
        Args:
            object_refs: Object ref of the object to get or a list of object refs
                to get.
            timeout (Optional[float]): The maximum amount of time in seconds to
                wait before returning.
    
        Returns:
            A Python object or a list of Python objects.
    
        Raises:
            GetTimeoutError: A GetTimeoutError is raised if a timeout is set and
                the get takes longer than timeout to return.
            Exception: An exception is raised if the task that created the object
                or that created one of the objects raised an exception.
        """
        worker = global_worker
        worker.check_connected()
    
        if hasattr(
                worker,
                "core_worker") and worker.core_worker.current_actor_is_asyncio():
            global blocking_get_inside_async_warned
            if not blocking_get_inside_async_warned:
                logger.warning("Using blocking ray.get inside async actor. "
                               "This blocks the event loop. Please use `await` "
                               "on object ref with asyncio.gather if you want to "
                               "yield execution to the event loop instead.")
                blocking_get_inside_async_warned = True
    
        with profiling.profile("ray.get"):
            is_individual_id = isinstance(object_refs, ray.ObjectRef)
            if is_individual_id:
                object_refs = [object_refs]
    
            if not isinstance(object_refs, list):
                raise ValueError("'object_refs' must either be an object ref "
                                 "or a list of object refs.")
    
            global last_task_error_raise_time
            # TODO(ujvl): Consider how to allow user to retrieve the ready objects.
            values, debugger_breakpoint = worker.get_objects(
                object_refs, timeout=timeout)
            for i, value in enumerate(values):
                if isinstance(value, RayError):
                    last_task_error_raise_time = time.time()
                    if isinstance(value, ray.exceptions.ObjectLostError):
                        worker.core_worker.dump_object_store_memory_usage()
                    if isinstance(value, RayTaskError):
>                       raise value.as_instanceof_cause()
E                       ray.exceptions.RayTaskError: ray::create_actors() (pid=7460, ip=10.1.0.4)
E                         File "python\ray\_raylet.pyx", line 480, in ray._raylet.execute_task
E                         File "\\?\C:\Users\RUNNER~1\AppData\Local\Temp\Bazel.runfiles_my88lp6_\runfiles\com_github_ray_project_ray\python\ray\tests\test_actor_resources.py", line 263, in create_actors
E                           [actor.get_location_and_ids.remote() for actor in actors])
E                         File "d:\a\ray\ray\python\ray\_private\client_mode_hook.py", line 47, in wrapper
E                           return func(*args, **kwargs)
E                         File "d:\a\ray\ray\python\ray\worker.py", line 1390, in get
E                           raise value
E                       ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task. Check python-core-worker-*.log files for more information.

d:\a\ray\ray\python\ray\worker.py:1388: RayTaskError
---------------------------- Captured stderr call -----------------------------
2021-01-12 18:30:45,006	INFO services.py:1171 -- View the Ray dashboard at http://127.0.0.1:8265
2021-01-12 18:30:51,859	INFO worker.py:655 -- Connecting to existing Ray cluster at address: 10.1.0.4:6379
2021-01-12 18:30:54,689	WARNING worker.py:1039 -- The agent on node fv-az177-498 failed with the following error:
Traceback (most recent call last):
  File "d:\a\ray\ray\python\ray\new_dashboard/agent.py", line 311, in <module>
    loop.run_until_complete(agent.run())
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "d:\a\ray\ray\python\ray\new_dashboard/agent.py", line 187, in run
    await asyncio.gather(check_parent_task,
UnboundLocalError: local variable 'check_parent_task' referenced before assignment

2021-01-12 18:30:55,473	WARNING worker.py:1039 -- The agent on node fv-az177-498 failed with the following error:
Traceback (most recent call last):
  File "d:\a\ray\ray\python\ray\new_dashboard/agent.py", line 311, in <module>
    loop.run_until_complete(agent.run())
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "d:\a\ray\ray\python\ray\new_dashboard/agent.py", line 187, in run
    await asyncio.gather(check_parent_task,
UnboundLocalError: local variable 'check_parent_task' referenced before assignment

(pid=None) Traceback (most recent call last):

(pid=None)   File "d:\a\ray\ray\python\ray\new_dashboard/agent.py", line 322, in <module>

(pid=None)     raise e

(pid=None)   File "d:\a\ray\ray\python\ray\new_dashboard/agent.py", line 311, in <module>

(pid=None)     loop.run_until_complete(agent.run())

(pid=None)   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\asyncio\base_events.py", line 587, in run_until_complete

(pid=None)     return future.result()

(pid=None)   File "d:\a\ray\ray\python\ray\new_dashboard/agent.py", line 187, in run

(pid=None)     await asyncio.gather(check_parent_task,

(pid=None) UnboundLocalError: local variable 'check_parent_task' referenced before assignment
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by amogkam** [comment]
This test has been skipped for now (#13495), but it might needs to be re-enabled again.
