### ISSUE TITLE
[tune] Missing handle in pytorch lightning integration

### ISSUE THREAD

**Issue by george-gca** [ray-project/ray#13404]
### What is the problem?

Tune can't find `ptl/val_loss` even though it exists, when using logger `agg_and_log_metrics`.

```
(pid=309) Traceback (most recent call last):
(pid=309)   File "/opt/conda/lib/python3.8/site-packages/ray/tune/function_runner.py", line 248, in run
(pid=309)     self._entrypoint()
(pid=309)   File "/opt/conda/lib/python3.8/site-packages/ray/tune/function_runner.py", line 315, in entrypoint
(pid=309)     return self._trainable_func(self.config, self._status_reporter,
(pid=309)   File "/opt/conda/lib/python3.8/site-packages/ray/tune/function_runner.py", line 575, in _trainable_func
(pid=309)     output = fn()
(pid=309)   File "/opt/conda/lib/python3.8/site-packages/ray/tune/function_runner.py", line 650, in _inner
(pid=309)     inner(config, checkpoint_dir=None)
(pid=309)   File "/opt/conda/lib/python3.8/site-packages/ray/tune/function_runner.py", line 644, in inner
(pid=309)     fn(config, **fn_kwargs)
(pid=309)   File "pl_tune_example.py", line 149, in train_mnist_tune
(pid=309)     trainer.fit(model)
(pid=309)   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 472, in fit
(pid=309)     results = self.accelerator_backend.train()
(pid=309)   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/cpu_accelerator.py", line 62, in train
(pid=309)     results = self.train_or_test()
(pid=309)   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 69, in train_or_test
(pid=309)     results = self.trainer.train()
(pid=309)   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 523, in train
(pid=309)     self.train_loop.run_training_epoch()
(pid=309)   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 601, in run_training_epoch
(pid=309)     self.trainer.run_evaluation(test_mode=False)
(pid=309)   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 630, in run_evaluation
(pid=309)     self.evaluation_loop.on_evaluation_end()
(pid=309)   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 111, in on_evaluation_end
(pid=309)     self.trainer.call_hook('on_validation_end', *args, **kwargs)
(pid=309)   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 889, in call_hook
(pid=309)     trainer_hook(*args, **kwargs)
(pid=309)   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py", line 177, in on_validation_end
(pid=309)     callback.on_validation_end(self, self.get_model())
(pid=309)   File "/opt/conda/lib/python3.8/site-packages/ray/tune/integration/pytorch_lightning.py", line 115, in on_validation_end
(pid=309)     self._handle(trainer, pl_module)
(pid=309)   File "/opt/conda/lib/python3.8/site-packages/ray/tune/integration/pytorch_lightning.py", line 188, in _handle
(pid=309)     report_dict[key] = trainer.callback_metrics[metric].item()
(pid=309) KeyError: 'ptl/val_loss'
```

Ray: 1.1.0
Python: 3.8.3
Pytorch: 1.7.0
Pytorch Lightning: 1.1.3
OS: Ubuntu 16.04

### Reproduction (REQUIRED)
Same code as given in the [example](https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mnist_pytorch_lightning.py), only changed the `validation_epoch_end` function:
```python
# flake8: noqa
# yapf: disable

# __import_lightning_begin__
import torch
import pytorch_lightning as pl
from torch.utils.data import DataLoader, random_split
from torch.nn import functional as F
from torchvision.datasets import MNIST
from torchvision import transforms
import os
# __import_lightning_end__

# __import_tune_begin__
import shutil
import tempfile
from pytorch_lightning.loggers import TensorBoardLogger
from pytorch_lightning.utilities.cloud_io import load as pl_load
from ray import tune
from ray.tune import CLIReporter
from ray.tune.schedulers import ASHAScheduler, PopulationBasedTraining
from ray.tune.integration.pytorch_lightning import TuneReportCallback, \
    TuneReportCheckpointCallback
# __import_tune_end__


# __lightning_begin__
class LightningMNISTClassifier(pl.LightningModule):
    """
    This has been adapted from
    https://towardsdatascience.com/from-pytorch-to-pytorch-lightning-a-gentle-introduction-b371b7caaf09
    """

    def __init__(self, config, data_dir=None):
        super(LightningMNISTClassifier, self).__init__()

        self.data_dir = data_dir or os.getcwd()

        self.layer_1_size = config["layer_1_size"]
        self.layer_2_size = config["layer_2_size"]
        self.lr = config["lr"]
        self.batch_size = config["batch_size"]

        # mnist images are (1, 28, 28) (channels, width, height)
        self.layer_1 = torch.nn.Linear(28 * 28, self.layer_1_size)
        self.layer_2 = torch.nn.Linear(self.layer_1_size, self.layer_2_size)
        self.layer_3 = torch.nn.Linear(self.layer_2_size, 10)

    def forward(self, x):
        batch_size, channels, width, height = x.size()
        x = x.view(batch_size, -1)

        x = self.layer_1(x)
        x = torch.relu(x)

        x = self.layer_2(x)
        x = torch.relu(x)

        x = self.layer_3(x)
        x = torch.log_softmax(x, dim=1)

        return x

    def cross_entropy_loss(self, logits, labels):
        return F.nll_loss(logits, labels)

    def accuracy(self, logits, labels):
        _, predicted = torch.max(logits.data, 1)
        correct = (predicted == labels).sum().item()
        accuracy = correct / len(labels)
        return torch.tensor(accuracy)

    def training_step(self, train_batch, batch_idx):
        x, y = train_batch
        logits = self.forward(x)
        loss = self.cross_entropy_loss(logits, y)
        accuracy = self.accuracy(logits, y)

        self.log("ptl/train_loss", loss)
        self.log("ptl/train_accuracy", accuracy)
        return loss

    def validation_step(self, val_batch, batch_idx):
        x, y = val_batch
        logits = self.forward(x)
        loss = self.cross_entropy_loss(logits, y)
        accuracy = self.accuracy(logits, y)
        return {"val_loss": loss, "val_accuracy": accuracy}

    def validation_epoch_end(self, outputs):
        # avg_loss = torch.stack([x["val_loss"] for x in outputs]).mean()
        # avg_acc = torch.stack([x["val_accuracy"] for x in outputs]).mean()
        # self.log("ptl/val_loss", avg_loss)
        # self.log("ptl/val_accuracy", avg_acc)
        for dataset_result in outputs:
            self.logger.agg_and_log_metrics(
                dataset_result, step=self.current_epoch)

    @staticmethod
    def download_data(data_dir):
        transform = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.1307, ), (0.3081, ))
        ])
        return MNIST(data_dir, train=True, download=True, transform=transform)

    def prepare_data(self):
        mnist_train = self.download_data(self.data_dir)

        self.mnist_train, self.mnist_val = random_split(
            mnist_train, [55000, 5000])

    def train_dataloader(self):
        return DataLoader(self.mnist_train, batch_size=int(self.batch_size))

    def val_dataloader(self):
        return DataLoader(self.mnist_val, batch_size=int(self.batch_size))

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=self.lr)
        return optimizer


def train_mnist(config):
    model = LightningMNISTClassifier(config)
    trainer = pl.Trainer(max_epochs=10, show_progress_bar=False)

    trainer.fit(model)
# __lightning_end__


# __tune_train_begin__
def train_mnist_tune(config, data_dir=None, num_epochs=10, num_gpus=0):
    model = LightningMNISTClassifier(config, data_dir)
    trainer = pl.Trainer(
        max_epochs=num_epochs,
        gpus=num_gpus,
        logger=TensorBoardLogger(
            save_dir=tune.get_trial_dir(), name="", version="."),
        progress_bar_refresh_rate=0,
        callbacks=[
            TuneReportCallback(
                {
                    "loss": "ptl/val_loss",
                    "mean_accuracy": "ptl/val_accuracy"
                },
                on="validation_end")
        ])
    trainer.fit(model)
# __tune_train_end__


# __tune_train_checkpoint_begin__
def train_mnist_tune_checkpoint(config,
                                checkpoint_dir=None,
                                data_dir=None,
                                num_epochs=10,
                                num_gpus=0):
    trainer = pl.Trainer(
        max_epochs=num_epochs,
        gpus=num_gpus,
        logger=TensorBoardLogger(
            save_dir=tune.get_trial_dir(), name="", version="."),
        progress_bar_refresh_rate=0,
        callbacks=[
            TuneReportCheckpointCallback(
                metrics={
                    "loss": "ptl/val_loss",
                    "mean_accuracy": "ptl/val_accuracy"
                },
                filename="checkpoint",
                on="validation_end")
        ])
    if checkpoint_dir:
        # Currently, this leads to errors:
        # model = LightningMNISTClassifier.load_from_checkpoint(
        #     os.path.join(checkpoint, "checkpoint"))
        # Workaround:
        ckpt = pl_load(
            os.path.join(checkpoint_dir, "checkpoint"),
            map_location=lambda storage, loc: storage)
        model = LightningMNISTClassifier._load_model_state(
            ckpt, config=config, data_dir=data_dir)
        trainer.current_epoch = ckpt["epoch"]
    else:
        model = LightningMNISTClassifier(config=config, data_dir=data_dir)

    trainer.fit(model)
# __tune_train_checkpoint_end__


# __tune_asha_begin__
def tune_mnist_asha(num_samples=10, num_epochs=10, gpus_per_trial=0):
    data_dir = os.path.join(tempfile.gettempdir(), "mnist_data_")
    LightningMNISTClassifier.download_data(data_dir)

    config = {
        "layer_1_size": tune.choice([32, 64, 128]),
        "layer_2_size": tune.choice([64, 128, 256]),
        "lr": tune.loguniform(1e-4, 1e-1),
        "batch_size": tune.choice([32, 64, 128]),
    }

    scheduler = ASHAScheduler(
        max_t=num_epochs,
        grace_period=1,
        reduction_factor=2)

    reporter = CLIReporter(
        parameter_columns=["layer_1_size", "layer_2_size", "lr", "batch_size"],
        metric_columns=["loss", "mean_accuracy", "training_iteration"])

    analysis = tune.run(
        tune.with_parameters(
            train_mnist_tune,
            data_dir=data_dir,
            num_epochs=num_epochs,
            num_gpus=gpus_per_trial),
        resources_per_trial={
            "cpu": 1,
            "gpu": gpus_per_trial
        },
        metric="loss",
        mode="min",
        local_dir=f'./ray_results',
        config=config,
        num_samples=num_samples,
        scheduler=scheduler,
        progress_reporter=reporter,
        name="tune_mnist_asha")

    print("Best hyperparameters found were: ", analysis.best_config)

    shutil.rmtree(data_dir)
# __tune_asha_end__


# __tune_pbt_begin__
def tune_mnist_pbt(num_samples=10, num_epochs=10, gpus_per_trial=0):
    data_dir = os.path.join(tempfile.gettempdir(), "mnist_data_")
    LightningMNISTClassifier.download_data(data_dir)

    config = {
        "layer_1_size": tune.choice([32, 64, 128]),
        "layer_2_size": tune.choice([64, 128, 256]),
        "lr": 1e-3,
        "batch_size": 64,
    }

    scheduler = PopulationBasedTraining(
        perturbation_interval=4,
        hyperparam_mutations={
            "lr": tune.loguniform(1e-4, 1e-1),
            "batch_size": [32, 64, 128]
        })

    reporter = CLIReporter(
        parameter_columns=["layer_1_size", "layer_2_size", "lr", "batch_size"],
        metric_columns=["loss", "mean_accuracy", "training_iteration"])

    analysis = tune.run(
        tune.with_parameters(
            train_mnist_tune_checkpoint,
            data_dir=data_dir,
            num_epochs=num_epochs,
            num_gpus=gpus_per_trial),
        resources_per_trial={
            "cpu": 1,
            "gpu": gpus_per_trial
        },
        metric="loss",
        mode="min",
        config=config,
        num_samples=num_samples,
        scheduler=scheduler,
        progress_reporter=reporter,
        name="tune_mnist_pbt")

    print("Best hyperparameters found were: ", analysis.best_config)

    shutil.rmtree(data_dir)
# __tune_pbt_end__


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--smoke-test", action="store_true", help="Finish quickly for testing")
    args, _ = parser.parse_known_args()

    if args.smoke_test:
        tune_mnist_asha(num_samples=1, num_epochs=6, gpus_per_trial=0)
        tune_mnist_pbt(num_samples=1, num_epochs=6, gpus_per_trial=0)
    else:
        # ASHA scheduler
        tune_mnist_asha(num_samples=10, num_epochs=10, gpus_per_trial=0)
        # Population based training
        tune_mnist_pbt(num_samples=10, num_epochs=10, gpus_per_trial=0)

```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### Possible Solution
Add [on_validation_epoch_end](https://pytorch-lightning.readthedocs.io/en/latest/callbacks.html#on-validation-epoch-end) hook to [pytorch lightning integration code](https://github.com/ray-project/ray/blob/master/python/ray/tune/integration/pytorch_lightning.py):
```python
    def on_validation_epoch_end(self, trainer: Trainer, pl_module: LightningModule):
        if "validation_epoch_end" in self._on:
            self._handle(trainer, pl_module)
```

**Comment by george-gca** [comment]
Just realized after opening the bug that `agg_and_log_metrics` is specific to the logger, so it probably doesn't update the [trainer.callback_metrics](https://pytorch-lightning.readthedocs.io/en/latest/trainer.html#callback-metrics) that is used inside the [_handle](https://github.com/ray-project/ray/blob/4853aa96cbbea76e69c3e48802ce7408f08669ee/python/ray/tune/integration/pytorch_lightning.py#L172) method. In this case, do I need to also manually aggregate the metrics so they could be used in tune?

**Comment by krfricke** [comment]
Hi @george-gca, yes, that seems to be the case - the pytorch lightning logger does not update the callback metrics, so you'll have to do the aggregation yourself.

A hacky way would be to just call `self.logger._aggregate_metrics` to do this without you having to implement it youself: https://github.com/PyTorchLightning/PyTorch-Lightning/blob/0.7.2/pytorch_lightning/loggers/base.py#L82 (it's hacky because it calls an internal method). You'll then need to update the callback metrics.

**Comment by george-gca** [comment]
@krfricke I ended up calling `self.log_dict(dataset_result, prog_bar=False, logger=False)` along with the `self.logger.agg_and_log_metrics`. Not a very nice solution, but did the trick. Thanks. Closing the issue since it is not a real bug.

**Comment by Svito-zar** [comment]
I am having the same issue now. I guess nothing changed since this issue was closed ...

**Comment by krfricke** [comment]
@Svito-zar which version of PTL and Ray are you using? Can you share a script? 

Please feel free to open another issue and we'll take a look

**Comment by Svito-zar** [comment]
The same solution as @george-gca suggested actually worked for me as well.

I have PTL 1.6 and Ray 2.2. Do you still want to see my script?
