### ISSUE TITLE
[ray_client] Error in background thread during teardown when using ray.connect

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#13418]
### What is the problem?
Running this simple script:

```python
import ray
ray.util.connect("localhost:61234")
@ray.remote
def f():
    pass
ray.get(f.remote())
print(ray.nodes())
#import time
#time.sleep(2)
```

If the sleeps are commented out, I get some nasty exception from a gRPC thread:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/eoakes/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/eoakes/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "src/python/grpcio/grpc/_cython/_cygrpc/thread.pyx.pxi", line 53, in grpc._cython.cygrpc._run_with_context._run
  File "/Users/eoakes/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 1379, in _poll_connectivity
    connectivity = channel.check_connectivity_state(try_to_connect)
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 503, in grpc._cython.cygrpc.Channel.check_connectivity_state
```

Reverting 0b22341bc9a693ef94da06fd274f8a7454d9f94b fixes the issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by barakmich** [comment]
Doesn't affect Linux, repros on macOS

**Comment by barakmich** [comment]
can also get a (different but related) crash with Linux
