### ISSUE TITLE
test_basic::test_many_fractional_resources failing on Linux Wheel Build

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#13439]
### What is the problem?
test_basic::test_many_fractional_resources is sometimes failing on Linux Wheel Build
```
python/ray/tests/test_basic.py::test_many_fractional_resources /home/travis/build/ray-project/ray/ci/travis/../../ci/travis/test-wheels.sh: line 28: 15474 Aborted                 (core dumped) "$@"
+'[' 2 -lt 3 ']'
+(( n++ ))
+echo 'Command failed. Attempt 3/3:'
Command failed. Attempt 3/3:
+true
+/home/travis/miniconda3/bin/python /home/travis/build/ray-project/ray/python/ray/tests/test_basic.py
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-5.4.3, py-1.10.0, pluggy-0.13.1 -- /home/travis/miniconda3/bin/python
cachedir: .pytest_cache
rootdir: /home/travis/build/ray-project/ray/python
collecting ... collected 35 items
python/ray/tests/test_basic.py::test_ignore_http_proxy PASSED            [  2%]
python/ray/tests/test_basic.py::test_grpc_message_size PASSED            [  5%]
python/ray/tests/test_basic.py::test_omp_threads_set PASSED              [  8%]
python/ray/tests/test_basic.py::test_submit_api PASSED                   [ 11%]
python/ray/tests/test_basic.py::test_invalid_arguments PASSED            [ 14%]
python/ray/tests/test_basic.py::test_many_fractional_resources /home/travis/build/ray-project/ray/ci/travis/../../ci/travis/test-wheels.sh: line 28: 16355 Aborted                 (core dumped) "$@"
+'[' 3 -lt 3 ']'
+echo 'The command has failed after 3 attempts.'
The command has failed after 3 attempts.
+exit 1
+++result=1
+++flush_logs=1
+++'[' 0 -ne 1 ']'
+++cat -- /tmp/ray/session_latest/logs/dashboard_agent.log /tmp/ray/session_latest/logs/dashboard.log /tmp/ray/session_latest/logs/gcs_server.err /tmp/ray/session_latest/logs/gcs_server.out /tmp/ray/session_latest/logs/log_monitor.log /tmp/ray/session_latest/logs/monitor.err /tmp/ray/session_latest/logs/monitor.log /tmp/ray/session_latest/logs/monitor.out /tmp/ray/session_latest/logs/old /tmp/ray/session_latest/logs/plasma_store.err /tmp/ray/session_latest/logs/plasma_store.out /tmp/ray/session_latest/logs/python-core-driver-01000000ffffffffffffffffffffffffffffffffffffffffffffffff_16355.log /tmp/ray/session_latest/logs/python-core-worker-468ad050a2bb9c1896f8d59806df01a2d52013d4ccbb2cdfc711e409_17155.log /tmp/ray/session_latest/logs/python-core-worker-b3b931a77d87fc191020d9b0547f5c09ef64853964693db4bda7cdfd_17130.log /tmp/ray/session_latest/logs/python-core-worker-b8be91e4f9e2320b73dbf77acd022cff0ceab5517f6e3e9c9eec6a59_17168.log /tmp/ray/session_latest/logs/python-core-worker-d6a0b41ec39ef7d2bb33e7c5ee51d8a9f64107e6746e4f876e27516e_17088.log /tmp/ray/session_latest/logs/python-core-worker-eb27130ded0a9dc995582a98ca2c731b2a5fbfd983daa6d0434f7100_17131.log /tmp/ray/session_latest/logs/python-core-worker-ee3152842644995738c616d71fa2d98b8aeb6ef2921d75bb719f1cb7_17089.log /tmp/ray/session_latest/logs/raylet.err /tmp/ray/session_latest/logs/raylet.out /tmp/ray/session_latest/logs/redis.err /tmp/ray/session_latest/logs/redis.out /tmp/ray/session_latest/logs/redis-shard_0.err /tmp/ray/session_latest/logs/redis-shard_0.out /tmp/ray/session_latest/logs/worker-064e7e0dbfc8b94fa8d9df37ed91b0110ad3303e5dd3249ca12a35a8-01000000-17131.err /tmp/ray/session_latest/logs/worker-064e7e0dbfc8b94fa8d9df37ed91b0110ad3303e5dd3249ca12a35a8-01000000-17131.out /tmp/ray/session_latest/logs/worker-1c8f5ef2c86ffd957b2ce8e47a9653a88d857d756796ca2defb04986-01000000-17089.err /tmp/ray/session_latest/logs/worker-1c8f5ef2c86ffd957b2ce8e47a9653a88d857d756796ca2defb04986-01000000-17089.out /tmp/ray/session_latest/logs/worker-5a77e5e33c3cb167abedf3185e4e50b76a77048dbb7f856859e43171-01000000-17088.err /tmp/ray/session_latest/logs/worker-5a77e5e33c3cb167abedf3185e4e50b76a77048dbb7f856859e43171-01000000-17088.out /tmp/ray/session_latest/logs/worker-a195c8a6c919ec3c668c3319ff54905c6b798701745cfd26b19f2715-01000000-17130.err /tmp/ray/session_latest/logs/worker-a195c8a6c919ec3c668c3319ff54905c6b798701745cfd26b19f2715-01000000-17130.out
2021-01-14 01:55:49,364	INFO agent.py:71 -- Parent pid is 17027
2021-01-14 01:55:49,365	INFO agent.py:76 -- Dashboard agent grpc address: 10.30.0.176:63691
2021-01-14 01:55:49,367	INFO utils.py:201 -- Get all modules by type: DashboardAgentModule
2021-01-14 01:55:49,525	INFO agent.py:89 -- Loading DashboardAgentModule: <class 'ray.new_dashboard.modules.log.log_agent.LogAgent'>
2021-01-14 01:55:49,526	INFO agent.py:89 -- Loading DashboardAgentModule: <class 'ray.new_dashboard.modules.reporter.reporter_agent.ReporterAgent'>
2021-01-14 01:55:49,528	INFO agent.py:93 -- Loaded 2 modules.
2021-01-14 01:55:49,530	INFO agent.py:162 -- Dashboard agent http address: 10.30.0.176:46879
2021-01-14 01:55:49,530	INFO agent.py:169 -- <ResourceRoute [GET] <StaticResource  /logs -> PosixPath('/tmp/ray/session_2021-01-14_01-55-47_461135_16355/logs')> -> <bound method StaticResource._handle of <StaticResource  /logs -> PosixPath('/tmp/ray/session_2021-01-14_01-55-47_461135_16355/logs')>>
2021-01-14 01:55:49,530	INFO agent.py:169 -- <ResourceRoute [OPTIONS] <StaticResource  /logs -> PosixPath('/tmp/ray/session_2021-01-14_01-55-47_461135_16355/logs')> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7f3b1c7d74a8>>
2021-01-14 01:55:49,530	INFO agent.py:170 -- Registered 2 routes.
2021-01-14 01:55:49,561	ERROR agent.py:321 -- The agent on node travis-job-0fdcc35e-3d74-4899-90a6-5d1bb70e4e2c failed with the following error:
Traceback (most recent call last):
  File "/home/travis/miniconda3/lib/python3.6/site-packages/ray/new_dashboard/agent.py", line 311, in <module>
    loop.run_until_complete(agent.run())
  File "/home/travis/miniconda3/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/travis/miniconda3/lib/python3.6/site-packages/ray/new_dashboard/agent.py", line 185, in run
    agent_ip_address=self.ip))
  File "/home/travis/miniconda3/lib/python3.6/site-packages/grpc/aio/_call.py", line 286, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1610589349.557584486","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4142,"referenced_errors":[{"created":"@1610589349.557579740","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>
Traceback (most recent call last):
  File "/home/travis/miniconda3/lib/python3.6/site-packages/ray/new_dashboard/agent.py", line 311, in <module>
    loop.run_until_complete(agent.run())
  File "/home/travis/miniconda3/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/travis/miniconda3/lib/python3.6/site-packages/ray/new_dashboard/agent.py", line 185, in run
    agent_ip_address=self.ip))
  File "/home/travis/miniconda3/lib/python3.6/site-packages/grpc/aio/_call.py", line 286, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1610589349.557584486","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4142,"referenced_errors":[{"created":"@1610589349.557579740","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>
2021-01-14 01:55:52,560	INFO agent.py:71 -- Parent pid is 17027
2021-01-14 01:55:52,562	INFO agent.py:76 -- Dashboard agent grpc address: 10.30.0.176:63691
2021-01-14 01:55:52,572	INFO utils.py:201 -- Get all modules by type: DashboardAgentModule
2021-01-14 01:55:48,813	INFO head.py:49 -- Dashboard head grpc address: 10.30.0.176:34517
2021-01-14 01:55:48,814	INFO head.py:51 -- Dashboard head http address: 127.0.0.1:8265
2021-01-14 01:55:48,814	INFO dashboard.py:82 -- Setup static dir for dashboard: /home/travis/miniconda3/lib/python3.6/site-packages/ray/new_dashboard/client/build
2021-01-14 01:55:48,818	INFO head.py:161 -- Connect to GCS at b'10.30.0.176:41979'
2021-01-14 01:55:48,821	INFO utils.py:201 -- Get all modules by type: DashboardHeadModule
2021-01-14 01:55:48,884	INFO head.py:130 -- Loading DashboardHeadModule: <class 'ray.new_dashboard.modules.job.job_head.JobHead'>
2021-01-14 01:55:48,884	INFO head.py:130 -- Loading DashboardHeadModule: <class 'ray.new_dashboard.modules.log.log_head.LogHead'>
2021-01-14 01:55:48,884	INFO head.py:130 -- Loading DashboardHeadModule: <class 'ray.new_dashboard.modules.logical_view.logical_view_head.LogicalViewHead'>
2021-01-14 01:55:48,884	INFO head.py:130 -- Loading DashboardHeadModule: <class 'ray.new_dashboard.modules.reporter.reporter_head.ReportHead'>
2021-01-14 01:55:48,884	INFO head.py:130 -- Loading DashboardHeadModule: <class 'ray.new_dashboard.modules.stats_collector.stats_collector_head.StatsCollector'>
2021-01-14 01:55:48,885	INFO head.py:130 -- Loading DashboardHeadModule: <class 'ray.new_dashboard.modules.tune.tune_head.TuneController'>
2021-01-14 01:55:48,885	INFO head.py:134 -- Loaded 6 modules.
2021-01-14 01:55:48,887	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /> -> <function Dashboard.get_index at 0x7f8a1379c8c8>
2021-01-14 01:55:48,887	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /favicon.ico> -> <function Dashboard.get_favicon at 0x7f8a1379c9d8>
2021-01-14 01:55:48,887	INFO head.py:207 -- <ResourceRoute [GET] <StaticResource  /static -> PosixPath('/home/travis/miniconda3/lib/python3.6/site-packages/ray/new_dashboard/client/build/static')> -> <bound method StaticResource._handle of <StaticResource  /static -> PosixPath('/home/travis/miniconda3/lib/python3.6/site-packages/ray/new_dashboard/client/build/static')>>
2021-01-14 01:55:48,887	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /jobs> -> <function JobHead.get_all_jobs[cache ttl=2, max_size=128] at 0x7f8a1073c488>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <DynamicResource  /jobs/{job_id}> -> <function JobHead.get_job[cache ttl=2, max_size=128] at 0x7f8a1073c6a8>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /log_index> -> <function LogHead.get_log_index at 0x7f8a10748158>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /log_proxy> -> <function LogHead.get_log_from_proxy at 0x7f8a10748268>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /logical/actor_groups> -> <function LogicalViewHead.get_actor_groups at 0x7f8a10759158>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /logical/actors> -> <function LogicalViewHead.get_all_actors[cache ttl=2, max_size=128] at 0x7f8a107592f0>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /logical/kill_actor> -> <function LogicalViewHead.kill_actor at 0x7f8a10759488>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /api/launch_profiling> -> <function ReportHead.launch_profiling at 0x7f8a10476d90>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /api/ray_config> -> <function ReportHead.get_ray_config at 0x7f8a10476ea0>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /api/cluster_status> -> <function ReportHead.get_cluster_status at 0x7f8a10478048>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /nodes> -> <function StatsCollector.get_all_nodes[cache ttl=2, max_size=128] at 0x7f8a10487048>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <DynamicResource  /nodes/{node_id}> -> <function StatsCollector.get_node[cache ttl=2, max_size=128] at 0x7f8a10487268>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /memory/memory_table> -> <function StatsCollector.get_memory_table at 0x7f8a10487400>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /memory/set_fetch> -> <function StatsCollector.set_fetch_memory_info at 0x7f8a10487510>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /node_logs> -> <function StatsCollector.get_logs at 0x7f8a10487620>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /node_errors> -> <function StatsCollector.get_errors at 0x7f8a10487730>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /tune/info> -> <function TuneController.tune_info at 0x7f8a10418510>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /tune/availability> -> <function TuneController.get_availability at 0x7f8a103dc2f0>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /tune/set_experiment> -> <function TuneController.set_tune_experiment at 0x7f8a103dc730>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <PlainResource  /tune/enable_tensorboard> -> <function TuneController.enable_tensorboard at 0x7f8a103dc510>
2021-01-14 01:55:48,888	INFO head.py:207 -- <ResourceRoute [GET] <StaticResource  /logs -> PosixPath('/tmp/ray/session_2021-01-14_01-55-47_461135_16355/logs')> -> <bound method StaticResource._handle of <StaticResource  /logs -> PosixPath('/tmp/ray/session_2021-01-14_01-55-47_461135_16355/logs')>>
2021-01-14 01:55:48,888	INFO head.py:208 -- Registered 24 routes.
2021-01-14 01:55:48,890	INFO datacenter.py:65 -- Purge data.
2021-01-14 01:55:48,891	INFO reporter_head.py:139 -- Subscribed to RAY_REPORTER:*
2021-01-14 01:55:48,892	INFO job_head.py:73 -- Subscribed to JOB:*
2021-01-14 01:55:48,892	INFO job_head.py:78 -- Getting all job info from GCS.
2021-01-14 01:55:48,892	INFO stats_collector_head.py:293 -- Subscribed to b'ERROR_INFO:*'
2021-01-14 01:55:48,894	INFO stats_collector_head.py:270 -- Subscribed to <_Sender name:b'RAY_LOG_CHANNEL', is_pattern:False, receiver:<Receiver is_active:True, senders:1, qsize:0>>
2021-01-14 01:55:48,895	INFO stats_collector_head.py:175 -- Subscribed to ACTOR:*
2021-01-14 01:55:48,895	INFO stats_collector_head.py:185 -- Getting all actor info from GCS.
2021-01-14 01:55:48,918	ERROR stats_collector_head.py:216 -- Error Getting all actor info from GCS.
Traceback (most recent call last):
  File "/home/travis/miniconda3/lib/python3.6/site-packages/ray/new_dashboard/modules/stats_collector/stats_collector_head.py", line 188, in _update_actors
    request, timeout=5)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/grpc/aio/_call.py", line 286, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1610589348.918390186","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4142,"referenced_errors":[{"created":"@1610589348.918383724","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>
2021-01-14 01:55:48,920	ERROR job_head.py:95 -- Error Getting all job info from GCS.
Traceback (most recent call last):
  File "/home/travis/miniconda3/lib/python3.6/site-packages/ray/new_dashboard/modules/job/job_head.py", line 81, in _update_jobs
    request, timeout=5)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/grpc/aio/_call.py", line 286, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1610589348.918394342","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4142,"referenced_errors":[{"created":"@1610589348.918383724","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>
2021-01-14 01:55:48,920	ERROR head.py:108 -- Got AioRpcError when updating nodes.
Traceback (most recent call last):
  File "/home/travis/miniconda3/lib/python3.6/site-packages/ray/new_dashboard/head.py", line 74, in _update_nodes
    nodes = await self._get_nodes()
  File "/home/travis/miniconda3/lib/python3.6/site-packages/ray/new_dashboard/head.py", line 61, in _get_nodes
    request, timeout=2)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/grpc/aio/_call.py", line 286, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1610589348.918396809","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4142,"referenced_errors":[{"created":"@1610589348.918383724","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
```
https://travis-ci.com/github/ray-project/ray/jobs/471522293
https://travis-ci.com/github/ray-project/ray/jobs/471519722

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by amogkam** [comment]
@ericl I am assigning this to you, but please delegate it to whoever can take a look.
