### ISSUE TITLE
test_autoscaling_policy.py prints out huge pile of JsonErrors

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#13433]
### What is the problem?

The emulated autoscaling policy tests is impossible to use due to

```
Exception in thread Thread-2568:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/eric/Desktop/ray/python/ray/autoscaler/_private/updater.py", line 124, in run
    self.do_update()
  File "/home/eric/Desktop/ray/python/ray/autoscaler/_private/updater.py", line 379, in do_update
    sync_run_yet=True)
  File "/home/eric/Desktop/ray/python/ray/autoscaler/_private/command_runner.py", line 805, in run_init
    for env_var in json.loads(image_env):
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The test should be fixed to use a mock command runner. cc @AmeerHajAli @wuisawesome

**Comment by satrya-sabeni** [comment]
What does it mean? I get this error trying to start a Ray cluster on AWS.

**Comment by satrya-sabeni** [comment]
> What does it mean? I get this error trying to start a Ray cluster on AWS.

I was able to fix problem. Just in case someone else bumps into this, I had the problem launching a cluster on AWS from a MacOS laptop. To solve it I had to put these vars in my `user/.bash_profile`:
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
Without it, somewhere in the code the warning would get mixed up into the json casing the json error.

**Comment by orcahmlee** [comment]
I also hit this error, when I tried to launch Ray cluster on GCP.

launch command:
```sh
ray up config.yaml
```

`config.yaml`
```yaml
cluster_name: andrew-py37-cluster

max_workers: 2

docker:
  image:
    "rayproject/ray:latest-cpu" # use this one if you don't need ML dependencies, it's faster to pull
  container_name: "ray_container"
  # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
  # if no cached version is present.
  pull_before_run: True
  run_options: # Extra options to pass into "docker run"
    - --ulimit nofile=65536:65536

# Cloud-provider specific configuration.
provider:
  type: gcp
  region: asia-east1
  availability_zone: asia-east1-a
  project_id: ******

# List of shell commands to run to set up nodes.
setup_commands:
  []
```

The error message after running `ray up`
```sh
......
  New status: setting-up
  [4/7] No initialization commands to run.
  [5/7] Initalizing command runner
Shared connection to **.**.**.** closed.
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
latest-cpu: Pulling from rayproject/ray
ea362f368469: Pull complete
1225d5801c62: Pull complete
edf7c0709b7c: Pull complete
75b09d590bd2: Pull complete
34249622b800: Pull complete
545d5c84ae7c: Pull complete
728c35648956: Pull complete
f1bd0ad6cbb5: Pull complete
fc4467a163ca: Pull complete
Digest: sha256:b317815ebff65d2d02074a2fb7a92fdb375c767a7028b89f65a8085dc6280aa9
Status: Downloaded newer image for rayproject/ray:latest-cpu
docker.io/rayproject/ray:latest-cpu
Shared connection to **.**.**.** closed.
Shared connection to **.**.**.** closed.
Shared connection to **.**.**.** closed.
2022-02-21 15:35:39,140	INFO node.py:295 -- wait_for_compute_zone_operation: Waiting for operation operation-1645428938585-5d882476336cc-2636af33-e51cc252 to finish...
2022-02-21 15:35:44,804	INFO node.py:307 -- wait_for_compute_zone_operation: Operation operation-1645428938585-5d882476
336cc-2636af33-e51cc252 finished.
  New status: update-failed
  !!!
  Expecting value: line 1 column 1 (char 0)
  !!!

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/andrew/miniconda3/envs/ray/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/andrew/miniconda3/envs/ray/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 134, in run
    self.do_update()
  File "/Users/andrew/miniconda3/envs/ray/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 405, in do_update
    sync_run_yet=True)
  File "/Users/andrew/miniconda3/envs/ray/lib/python3.7/site-packages/ray/autoscaler/_private/command_runner.py", line 850, in run_init
    for env_var in json.loads(image_env):
  File "/Users/andrew/miniconda3/envs/ray/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/andrew/miniconda3/envs/ray/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/andrew/miniconda3/envs/ray/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

  Failed to setup head node.
```

I also check the `LC_ALL` and `LANG` my Mac(thanks @satrya-sabeni ). Although the settings of `LC_ALL` and `LANG` are both `en_US.UTF-8`, seems these settings do not send to the GCE instances. Since the above error message shows 

```sh
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

**Comment by orcahmlee** [comment]
I wanna share my solution. After I modified the `ssh_config` on my Mac, I was able to create the Ray cluster(using docker image) on GCE.

```sh
sudo vim /etc/ssh/ssh_config
```
then comment out the `SendEnv LANG LC_*`
```sh
 Host *
#   SendEnv LANG LC_*
```

**Comment by wuisawesome** [comment]
@orcahmlee can you file a new issues for this? It's almost certainly a different issue (this one is purely about noisy output in a unit test which doesn't use a real node provider).

**Comment by orcahmlee** [comment]
> @orcahmlee can you file a new issues for this? It's almost certainly a different issue (this one is purely about noisy output in a unit test which doesn't use a real node provider).

Done. https://github.com/ray-project/ray/issues/22535
Thanks for your advice. @wuisawesome

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
