### ISSUE TITLE
[Kubernetes][Operator][Autoscaler] Operator fails to autoscale when running on OpenShift Kubernetes

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#13569]
### What is the problem?

`commands.get_or_create_head_node` is on the K8s operator's code path.
This method tries to copy a cluster config to the Ray head node, which is unnecessary for the operator.
The copy fails when running the operator on OpenShift which prevents the operator from working.
See https://github.com/ray-project/ray/pull/13567#issuecomment-763169617.

The solution is to modify `commands.get_or_create_head_node` to allow the operator to circumvent the violating rsync command. 

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by dmatch01** [comment]
Referenced Error:
```
$ kubectl logs ray-operator-pod 
example-cluster:2021-01-19 13:51:48,200	DEBUG config.py:83 -- Updating the resources of node type head-node to include {'CPU': 1, 'GPU': 0}.
example-cluster:2021-01-19 13:51:48,201	DEBUG config.py:83 -- Updating the resources of node type worker-nodes to include {'CPU': 1, 'GPU': 0}.
example-cluster:2021-01-19 13:51:48,240	WARNING config.py:164 -- KubernetesNodeProvider: not checking if namespace 'ray' exists
example-cluster:2021-01-19 13:51:48,240	INFO config.py:184 -- KubernetesNodeProvider: no autoscaler_service_account config provided, must already exist
example-cluster:2021-01-19 13:51:48,240	INFO config.py:210 -- KubernetesNodeProvider: no autoscaler_role config provided, must already exist
example-cluster:2021-01-19 13:51:48,240	INFO config.py:236 -- KubernetesNodeProvider: no autoscaler_role_binding config provided, must already exist
example-cluster:2021-01-19 13:51:48,240	INFO config.py:269 -- KubernetesNodeProvider: no services config provided, must already exist
example-cluster:2021-01-19 13:51:48,399	INFO command_runner.py:171 -- NodeUpdater: example-cluster-ray-head-5b6xs: Running kubectl -n ray exec -it example-cluster-ray-head-5b6xs -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
Unable to use a TTY - input is not a terminal or the right kind of file
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
 13:51:49 up 61 days, 35 min,  0 users,  load average: 0.51, 0.91, 1.12
example-cluster:2021-01-19 13:51:49,860	DEBUG updater.py:290 -- Node tags: {'ray-cluster-name': 'example-cluster', 'ray-launch-config': '98667bd93919c3750dd13f541b8a03e8f4642496', 'ray-node-name': 'ray-example-cluster-head', 'ray-node-status': 'waiting-for-ssh', 'ray-node-type': 'head', 'ray-node-uuid': 'add167be-4195-479a-9cdf-7ad34b45269c', 'ray-user-node-type': 'head-node'}
example-cluster:2021-01-19 13:51:49,997	INFO command_runner.py:171 -- NodeUpdater: example-cluster-ray-head-5b6xs: Running kubectl -n ray exec -it example-cluster-ray-head-5b6xs -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (mkdir -p ~)'
Unable to use a TTY - input is not a terminal or the right kind of file
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
Unable to use a TTY - input is not a terminal or the right kind of file
rsync: mkstemp "/home/ray/.ray_bootstrap_config.yaml.zOQSSg" failed: Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
tar: ray_bootstrap_config.yaml: Cannot open: Permission denied
tar: Exiting with failure status due to previous errors
command terminated with exit code 2
2021-01-19 13:51:48,163	INFO commands.py:221 -- Cluster: example-cluster
2021-01-19 13:51:48,200	INFO commands.py:283 -- Checking Kubernetes environment settings
2021-01-19 13:51:48,266	INFO commands.py:555 -- Updating cluster configuration and running full setup.
2021-01-19 13:51:48,266	INFO commands.py:559 -- Cluster Ray runtime will be restarted. Confirm [y/N]: y [automatic, due to --yes]
2021-01-19 13:51:48,291	INFO commands.py:622 -- <1/1> Setting up head node
2021-01-19 13:51:48,292	INFO commands.py:666 -- Prepared bootstrap config
2021-01-19 13:51:48,292	WARN commands.py:501 -- The head node will not launch any workers because `ray start` does not have `--autoscaling-config` set.
Potential fix: add `--autoscaling-config=~/ray_bootstrap_config.yaml` to the `ray start` command under `head_start_ray_commands`.
2021-01-19 13:51:48,378	INFO updater.py:282 -- New status: waiting-for-ssh
2021-01-19 13:51:48,379	INFO updater.py:230 -- [1/7] Waiting for SSH to become available
2021-01-19 13:51:48,379	INFO updater.py:233 -- Running `uptime` as a test.
2021-01-19 13:51:49,833	SUCC updater.py:241 -- Success.
2021-01-19 13:51:49,833	INFO log_timer.py:27 -- NodeUpdater: example-cluster-ray-head-5b6xs: Got remote shell  [LogTimer=1455ms]
2021-01-19 13:51:49,861	INFO updater.py:318 -- Updating cluster configuration. [hash=6e9b1031a12a117b2dbdcaa1ccc5065b94dba980]
2021-01-19 13:51:49,997	INFO updater.py:322 -- New status: syncing-files
2021-01-19 13:51:49,997	INFO updater.py:208 -- [2/7] Processing file mounts
2021-01-19 13:51:52,616	INFO log_timer.py:27 -- NodeUpdater: example-cluster-ray-head-5b6xs: Synced /tmp/ray-bootstrap-v5fw6z3w to ~/ray_bootstrap_config.yaml  [LogTimer=2619ms]
2021-01-19 13:51:52,617	INFO log_timer.py:27 -- NodeUpdater: example-cluster-ray-head-5b6xs: Applied config 6e9b1031a12a117b2dbdcaa1ccc5065b94dba980  [LogTimer=4324ms]
2021-01-19 13:51:52,692	ERR updater.py:128 -- New status: update-failed
2021-01-19 13:51:52,692	ERR updater.py:130 -- !!!
2021-01-19 13:51:52,692	ERR updater.py:134 -- Setup command `['kubectl', '-n', 'ray', 'cp', '/tmp/ray-bootstrap-v5fw6z3w', 'ray/example-cluster-ray-head-5b6xs:/home/ray/ray_bootstrap_config.yaml']` failed with exit code 2. stderr:
2021-01-19 13:51:52,692	ERR updater.py:140 -- !!!
2021-01-19 13:51:52,716	PANIC commands.py:709 -- Failed to setup head node.
/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/command_runner.py:213: UserWarning: NodeUpdater: example-cluster-ray-head-5b6xs: rsync failed: 'Command '['/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kubernetes/kubectl-rsync.sh', '-aqz', '/tmp/ray-bootstrap-v5fw6z3w', 'example-cluster-ray-head-5b6xs@ray:/home/ray/ray_bootstrap_config.yaml']' returned non-zero exit status 23.'. Falling back to 'kubectl cp'
  UserWarning)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/command_runner.py", line 207, in run_rsync_up
    "{}@{}:{}".format(self.node_id, self.namespace, target),
  File "/home/ray/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kubernetes/kubectl-rsync.sh', '-aqz', '/tmp/ray-bootstrap-v5fw6z3w', 'example-cluster-ray-head-5b6xs@ray:/home/ray/ray_bootstrap_config.yaml']' returned non-zero exit status 23.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 124, in run
    self.do_update()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 324, in do_update
    self.rsync_up, step_numbers=(1, NUM_SETUP_STEPS))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 210, in sync_file_mounts
    do_sync(remote_path, local_path)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 198, in do_sync
    local_path, remote_path, docker_mount_if_possible=True)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 459, in rsync_up
    self.cmd_runner.run_rsync_up(source, target, options=options)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/command_runner.py", line 219, in run_rsync_up
    target)
  File "/home/ray/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['kubectl', '-n', 'ray', 'cp', '/tmp/ray-bootstrap-v5fw6z3w', 'ray/example-cluster-ray-head-5b6xs:/home/ray/ray_bootstrap_config.yaml']' returned non-zero exit status 2.

Process example-cluster:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/ray/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/operator/operator.py", line 48, in _create_or_update
    self.start_head()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/operator/operator.py", line 60, in start_head
    no_config_cache=True)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 228, in create_or_update_cluster
    override_cluster_name)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 709, in get_or_create_head_node
    cli_logger.abort("Failed to setup head node.")
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py", line 585, in abort
    raise exc_cls("Exiting due to cli_logger.abort()")
click.exceptions.ClickException: Exiting due to cli_logger.abort()
$
```

**Comment by DmitriGekhtman** [comment]
KubeRay works fine on OpenShift.
