### ISSUE TITLE
[docker] Restarting container needs to re-run setup commands

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#13587]
### What is the problem?

If you modify the file mounts, the container restarts. However, the setup commands don't get re-run (with `ray start --restart-only`). As a result, this can break workflows.

We need to run the setup commands always when the container restarts.

```
setup_commands:
    # - echo "hi"
    - pip install boto3 tqdm
    - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.2.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
    - pip install ray[tune]
```

```
Shared connection to 44.233.116.28 closed.
    This Docker Container is already running. Restarting the Docker container on this node to pick up the following file_mounts {'usr/local/lib/python3.7/dist-packages/horovod/ray/elastic.py'}
ray_docker
Shared connection to 44.233.116.28 closed.
Shared connection to 44.233.116.28 closed.
Shared connection to 44.233.116.28 closed.
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

Shared connection to 44.233.116.28 closed.
2021-01-20 11:21:26,183	WARNING command_runner.py:853 -- Nvidia Container Runtime is present, but no GPUs found.
Shared connection to 44.233.116.28 closed.
c9b79902d5299b3124278e05e6acd19b5cd366b6bf6ca54cc9b77080014f21a4
Shared connection to 44.233.116.28 closed.
Shared connection to 44.233.116.28 closed.
Shared connection to 44.233.116.28 closed.
Shared connection to 44.233.116.28 closed.
  [6/7] No setup commands to run.
  [7/7] Starting the Ray runtime
Did not find any active Ray processes.
Shared connection to 44.233.116.28 closed.
Local node IP: 172.31.41.244
2021-01-20 19:21:30,515	INFO services.py:1173 -- View the Ray dashboard at http://localhost:8265

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='172.31.41.244:6379' --redis-password='5241590000000000'

  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='5241590000000000')

  If connection fails, check your firewall settings and network configuration.

  To terminate the Ray runtime, run
    ray stop
Shared connection to 44.233.116.28 closed.
  New status: up-to-date

Useful commands
  Monitor autoscaling with
    ray exec /Users/rliaw/dev/horovod/_ray_horovod.yaml 'tail -n 100 -f /tmp/ray/session_latest/logs/monitor*'
  Connect to a terminal on the cluster head:
    ray attach /Users/rliaw/dev/horovod/_ray_horovod.yaml
  Get a remote shell to the cluster manually:
    ssh -tt -o IdentitiesOnly=yes -i ~/dev/cfgs/richard-anyscale.pem ubuntu@44.233.116.28 docker exec -it ray_docker /bin/bash
(base) ➜  horovod git:(master) ✗ ray monitor _ray_horovod.yaml
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
Fetched IP: 44.233.116.28
Warning: Permanently added '44.233.116.28' (ECDSA) to the list of known hosts.
==> /tmp/ray/session_latest/logs/monitor.err <==
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ray/worker.py", line 854, in custom_excepthook
    worker_id = global_worker.worker_id
AttributeError: 'Worker' object has no attribute 'worker_id'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ray/monitor.py", line 390, in <module>
    redis_password=args.redis_password)
  File "/usr/local/lib/python3.7/dist-packages/ray/monitor.py", line 111, in __init__
    self.load_metrics)
  File "/usr/local/lib/python3.7/dist-packages/ray/autoscaler/_private/autoscaler.py", line 76, in __init__
    self.reset(errors_fatal=True)
  File "/usr/local/lib/python3.7/dist-packages/ray/autoscaler/_private/autoscaler.py", line 490, in reset
    raise e
  File "/usr/local/lib/python3.7/dist-packages/ray/autoscaler/_private/autoscaler.py", line 450, in reset
    self.config["cluster_name"])
  File "/usr/local/lib/python3.7/dist-packages/ray/autoscaler/_private/providers.py", line 174, in _get_node_provider
    provider_cls = _get_node_provider_cls(provider_config)
  File "/usr/local/lib/python3.7/dist-packages/ray/autoscaler/_private/providers.py", line 150, in _get_node_provider_cls
    return importer(provider_config)
  File "/usr/local/lib/python3.7/dist-packages/ray/autoscaler/_private/providers.py", line 16, in _import_aws
    from ray.autoscaler._private.aws.node_provider import AWSNodeProvider
  File "/usr/local/lib/python3.7/dist-packages/ray/autoscaler/_private/aws/node_provider.py", line 9, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'

```

**Comment by ericl** [comment]
cc @AmeerHajAli @ijrsvt seems this means update flow doesn't work with docker (iiuc, pretty bad regression from bare metal)

**Comment by ijrsvt** [comment]
@richardliaw This is only a problem if you specify `--restart-only`. If you just run `ray up <YAML>` after adding a file_mount the following happens:
```
Shared connection to 54.193.113.177 closed.
    This Docker Container is already running. Restarting the Docker container on this node to pick up the following file_mounts {'home/ray/abc'}
ray_container
Shared connection to 54.193.113.177 closed.
Shared connection to 54.193.113.177 closed.
Shared connection to 54.193.113.177 closed.
Shared connection to 54.193.113.177 closed.
2d57f161d1ca3b004a25413de786f8a8d4b2b7ad19f19d770570351dfd19b1a4
Shared connection to 54.193.113.177 closed.
Shared connection to 54.193.113.177 closed.
Shared connection to 54.193.113.177 closed.
Shared connection to 54.193.113.177 closed.
  [6/7] Running setup commands
    (0/1) printf "HELLO\n\n\n"
HELLO

```
 I can still fix this, but just wanted to surface a very simple workaround.
