### ISSUE TITLE
[rllib]Action masking with tuple action space

### ISSUE THREAD

**Issue by herunyu** [ray-project/ray#13592]
### What is the problem?
Action masking works with only discrete action space, but return shape errors when using tuple action space

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray: 1.1.0
tensorflow: 2.4.0
pytorch: 1.6.0

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

I've made a simple car game environment that we want the car go to the target location.
All other files are simply copy-paste from parametric_actions_cartpole.py and a customized ParametricActionsModel following from the official ray website. I've attached the files in the zip file and below is the error. You can just run 
`python Car2D_server.py` to start the policy server and see the error

```bash
Traceback (most recent call last):
  File "Car2D_server.py", line 64, in <module>
    trainer = PPOTrainer(
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 106, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 465, in __init__
    super().__init__(config, logger_creator)
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/tune/trainable.py", line 96, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 629, in setup
    self._init(self.config, self.env_creator)
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 133, in _init
    self.workers = self._make_workers(
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 700, in _make_workers
    return WorkerSet(
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 87, in __init__
    self._local_worker = self._make_worker(
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 315, in _make_worker
    worker = cls(
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 460, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1076, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/policy/tf_policy_template.py", line 217, in __init__
    DynamicTFPolicy.__init__(
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/policy/dynamic_tf_policy.py", line 282, in __init__
    dist_inputs, self._state_out = self.model(
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/models/modelv2.py", line 225, in __call__
    raise ValueError(
ValueError: Expected output shape of [None, 8], got (?, 6)
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x]I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

[car2d.zip](https://github.com/ray-project/ray/files/5846626/car2d.zip)

**Comment by edbeeching** [comment]
I have a similar issue with a custom env with the Dict action space, that contains both discrete and continous action spaces. I wish to perform action masking on the discrete actions.

Thanks for all your great work with ray rllib!

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
