### ISSUE TITLE
ray ignores TMPDIR variable -> Spawning ray fails

### ISSUE THREAD

**Issue by Hoeze** [ray-project/ray#13606]
We have set `$TMPDIR` to `/scratch/tmp/$USER` on our system since we have fast SSD scratch space on our nodes available.
However, when calling `ray.init()` we always get `/tmp/ray` back:
```python
{'node_ip_address': ...,
 'raylet_ip_address': ...,
 'redis_address': ...,
 'object_store_address': '/tmp/ray/session_2021-01-21_16-22-54_796050_43968/sockets/plasma_store',
 'raylet_socket_name': '/tmp/ray/session_2021-01-21_16-22-54_796050_43968/sockets/raylet',
 'webui_url': '127.0.0.1:8265',
 'session_dir': '/tmp/ray/session_2021-01-21_16-22-54_796050_43968',
 'metrics_export_port': 65081,
 'node_id': ...}
```

This also causes Ray to fail spawning the dashboard:
```python
#> cat /tmp/ray/session_2021-01-21_16-22-54_796050_43968/logs/dashboard.err 
Traceback (most recent call last):
  File "/opt/modules/anaconda/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 975, in <module>
    raise e
  File "/opt/modules/anaconda/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 962, in <module>
    dashboard.run()
  File "/opt/modules/anaconda/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 572, in run
    self.log_dashboard_url()
  File "/opt/modules/anaconda/envs/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 567, in log_dashboard_url
    with open(os.path.join(self.temp_dir, "dashboard_url"), "w") as f:
PermissionError: [Errno 13] Permission denied: '/tmp/ray/dashboard_url'
```

**Comment by ck37** [comment]
I've also noticed this. I have TMPDIR set to be $HOME/tmp, but Ray still writes to /tmp/me :(

**Comment by ericl** [comment]
Apparently TMPDIR is set to some absurdly long directory on some Mac machines, so we can't do this by default.

We could support an alternative env var like RAY_TMPDIR though.
