### ISSUE TITLE
[tune] ray.tune.utils.util got an unexpected keyword argument 'reporter' while running PBT with Huggingface

### ISSUE THREAD

**Issue by hasansalimkanmaz** [ray-project/ray#13600]
### What is the problem?

When I run ray tune with huggingface, it logs `ray.tune.utils.util got an unexpected keyword argument 'reporter'` and stops.

### Reproduction (REQUIRED)

```    
scheduler = PopulationBasedTraining(
        time_attr="training_iteration",
        # mode="max",
        # metric="eval_f1",
        perturbation_interval=10,
        hyperparam_mutations={
            "learning_rate": [1e-5, 2e-5, 5e-5, 1e-4],  # 4 values
            "warmup_steps": [100, 300, 500],  # 3 values
            "gradient_accumulation_steps": [1, 2, 4],  # 3 values
        },
    )

from ray.tune import CLIReporter

reporter = CLIReporter(
        parameter_columns={
            "learning_rate": "lr",
            "warmup_steps": "warmup_steps",
            "gradient_accumulation_steps": "gradient_accumulation_steps",
        },
        metric_columns=["eval_acc", "eval_loss", "epoch", "eval_f1"],
    )

os.environ["RAY_PICKLE_VERBOSE_DEBUG"] = "1"

best_trial = trainer.hyperparameter_search(
        direction="maximize",
        backend="ray",
        n_trials=36,
        scheduler=scheduler,
        progress_reporter=reporter,
        keep_checkpoints_num=1,
        checkpoint_score_attr="training_iteration",
        local_dir=output_model_dir,
        name="tune_layoutlm_pbt",
        log_to_file=True,
        n_jobs=2,
    )
```

Error Traceback:

```
2021-01-21 10:58:45 INFO     ray.tune.ray_trial_executor Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2021-01-21 10:58:45 DEBUG    ray.worker Automatically increasing RLIMIT_NOFILE to max value of 9223372036854775807
2021-01-21 10:58:45 DEBUG    ray.node   Process STDOUT and STDERR is being redirected to /tmp/ray/session_2021-01-21_10-58-45_759178_2946/logs.
2021-01-21 10:58:45 DEBUG    ray._private.services Waiting for redis server at 127.0.0.1:6379 to respond...
2021-01-21 10:58:46 DEBUG    ray._private.services Waiting for redis server at 127.0.0.1:26049 to respond...
2021-01-21 10:58:46 DEBUG    ray._private.services Starting Redis shard with 0.76 GB max memory.
2021-01-21 10:58:46 INFO     ray._private.services View the Ray dashboard at http://127.0.0.1:8265
2021-01-21 10:58:46 DEBUG    ray.node   Process STDOUT and STDERR is being redirected to /tmp/ray/session_2021-01-21_10-58-45_759178_2946/logs.
2021-01-21 10:58:46 DEBUG    ray._private.services Determine to start the Plasma object store with 2.28 GB memory using /tmp.
2021-01-21 10:58:48 DEBUG    ray.tune.ray_trial_executor Checking Ray cluster resources.
2021-01-21 10:58:48 DEBUG    ray.tune.registry Detected function for trainable.
2021-01-21 10:58:48 DEBUG    ray.tune.utils.util got an unexpected keyword argument 'reporter'
2021-01-21 10:58:48 ERROR    common_utils.message_utils Error during pipeline: logger cannot be pickled Other options: 
-Try reproducing the issue by calling `pickle.dumps(trainable)`. 
-If the error is typing-related, try removing the type annotations and try again.
2021-01-21 10:58:48 DEBUG    common_utils.message_utils Sending exception to Kafka...
2021-01-21 10:58:48 ERROR    root       While processing message got an error: logger cannot be pickled Other options: 
-Try reproducing the issue by calling `pickle.dumps(trainable)`. 
-If the error is typing-related, try removing the type annotations and try again..
Traceback (most recent call last):
  File "/Users/common_utils/kubeflow_utils.py", line 209, in run_step
    step_callback(
  File "/Users/nlp_ner_layoutlm/train_pipeline/training_step/layoutlm_train_model.py", line 58, in train_and_save_layoutLM_model
    train_model(
  File "/Users/nlp_ner_layoutlm/layoutlm/utils_train.py", line 270, in train_model
    best_trial = trainer.hyperparameter_search(
  File "/Users/environments/ner_layoutlm/lib/python3.8/site-packages/transformers/trainer.py", line 1077, in hyperparameter_search
    best_run = run_hp_search(self, n_trials, direction, **kwargs)
  File "/Users/environments/ner_layoutlm/lib/python3.8/site-packages/transformers/integrations.py", line 252, in run_hp_search_ray
    analysis = ray.tune.run(_objective, config=trainer.hp_space(None), num_samples=n_trials, **kwargs)
  File "/Users/environments/ner_layoutlm/lib/python3.8/site-packages/ray/tune/tune.py", line 304, in run
    experiments[i] = Experiment(
  File "/Users/environments/ner_layoutlm/lib/python3.8/site-packages/ray/tune/experiment.py", line 149, in __init__
    self._run_identifier = Experiment.register_if_needed(run)
  File "/Users/environments/ner_layoutlm/lib/python3.8/site-packages/ray/tune/experiment.py", line 294, in register_if_needed
    raise type(e)(str(e) + " " + extra_msg) from None
_pickle.PicklingError: logger cannot be pickled Other options: 
-Try reproducing the issue by calling `pickle.dumps(trainable)`. 
-If the error is typing-related, try removing the type annotations and try again.
```

**Comment by krfricke** [comment]
Hi @hasansalimkanmaz, the cited message is just a debug message that comes up during detection of trainable function arguments:

```
def detect_reporter(func):
    """Use reporter if any arg has "reporter" and args = 2"""
    func_sig = inspect.signature(func)
    use_reporter = True
    try:
        func_sig.bind({}, reporter=None)
    except Exception as e:
        logger.debug(str(e))
        use_reporter = False
    return use_reporter
```

So this is expected behavior and not the reason your code fails.

The reason seems to be rather that the training function cannot be pickled, specifically the (global?) `logger` object. This is definitely unexpected, but I couldn't reproduce this error.

Can you share which Ray version and which huggingface version you are using, and the rest of your script? We need a fully reproducible script including all imports to work on an issue. You can (and should) change parts of your script, e.g. remove unnecessary bits and simplify it, as long as it is fully runnable and reproduces the issue.
