### ISSUE TITLE
[serve/windows] Exception when using ray-serve example on WSL2

### ISSUE THREAD

**Issue by aaronabebe** [ray-project/ray#13652]
### What is the problem?
Hello! I'm currently trying to get ray-serve up and running on my windows machine using WSL2 with Ubuntu20.04. When starting the backend I'm getting the following stacktrace:

```
2021-01-23 15:06:49,267 INFO services.py:1171 -- View the Ray dashboard at http://127.0.0.1:8265
(pid=632) 2021-01-23 15:06:51,006       INFO controller.py:344 -- Starting router with name 'sjgcVe:SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:192.168.142.22-0' on node 'node:192.168.142.22-0' listening on '127.0.0.1:8000'
(pid=630) INFO:     Started server process [630]
Traceback (most recent call last):
  File "raytest.py", line 19, in <module>
    client.create_backend("my_backend", Counter)
  File "/home/aaron/development/zackplan/ai/venv/lib/python3.8/site-packages/ray/serve/api.py", line 31, in check
    return f(self, *args, **kwargs)
  File "/home/aaron/development/zackplan/ai/venv/lib/python3.8/site-packages/ray/serve/api.py", line 293, in create_backend
    ray.get(
  File "/home/aaron/development/zackplan/ai/venv/lib/python3.8/site-packages/ray/worker.py", line 1379, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::ServeController.create_backend() (pid=632, ip=192.168.142.22)
  File "python/ray/_raylet.pyx", line 425, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 439, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1501, in ray._raylet.CoreWorker.run_async_func_in_event_loop
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "python/ray/_raylet.pyx", line 437, in deserialize_args
  File "/home/aaron/development/zackplan/ai/venv/lib/python3.8/site-packages/ray/serialization.py", line 310, in deserialize_objects
    self._deserialize_object(data, metadata, object_ref))
  File "/home/aaron/development/zackplan/ai/venv/lib/python3.8/site-packages/ray/serialization.py", line 248, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "/home/aaron/development/zackplan/ai/venv/lib/python3.8/site-packages/ray/serialization.py", line 226, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "/home/aaron/development/zackplan/ai/venv/lib/python3.8/site-packages/ray/serialization.py", line 216, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
AttributeError: Can't get attribute '_Pydantic_BackendMetadata_25640496' on <module 'pydantic.dataclasses' from '/home/aaron/development/zackplan/ai/venv/lib/python3.8/site-packages/pydantic/dataclasses.cpython-38-x86_64-linux-gnu.so'>
2021-01-23 15:06:55,702 INFO api.py:65 -- Shutting down Ray Serve because client went out of scope. To prevent this, either keep a reference to the client object or use serve.start(detached=True).
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
python==3.8.5
ray==1.1.0
WSL2 with Ubuntu20.04 

EDIT:
pydantic==1.6.1

### Reproduction (REQUIRED)

I'm currently trying to implement the counter example from https://docs.ray.io/en/master/serve/.
```python
import ray
from ray import serve
import requests

ray.init(num_cpus=4)
client = serve.start()


class Counter:
    def __init__(self):
        self.count = 0

    def __call__(self, request):
        self.count += 1
        return {"count": self.count}


# Form a backend from our class and connect it to an endpoint.
client.create_backend("my_backend", Counter)
client.create_endpoint("my_endpoint", backend="my_backend", route="/counter")
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
Hey! Thanks for trying out Serve. What's your `pydantic` version? `pip freeze | grep pydantic`. Ray Serve only works with `pydantic<1.7`.

**Comment by aaronabebe** [comment]
Hi! Thanks for your reply.
My current version, acccording to the command you posted is: `pydantic==1.6.1`.

**Comment by simon-mo** [comment]
Can you try `pip install -U pydantic<1.7` to update it to latest version that satisfy the constraint?

**Comment by aaronabebe** [comment]
When I run `pip install -U pydantic<1.7` pip installs `pydantic==1.6.1`. I also tried running it with `pydantic==1.5.1`, which results in the same errors.

**Comment by aaronabebe** [comment]
I misread the error message. Installing via `pip install -U pydantic<1.7` indeed did the trick for me. Thanks for the help!

**Comment by magedhelmy1** [comment]
I had to do `pip install -U "pydantic<1.7"` or else it returned `bash: 1.7: No such file or directory` with `pip install -U pydantic<1.7`

Otherwise, thank you both!
