### ISSUE TITLE
win10 and linux Cluster

### ISSUE THREAD

**Issue by jack2nb** [ray-project/ray#13676]
----------------------machine （a） 
OS:     Microsoft Windows  10.0.19042 
user:   jack
python: 3.7.7
ray:  1.1.0
cmd: ray start --head --port=6379 --redis-shard-ports=6380 --node-manager-port=12345 --object-manager-port=12346   --dashboard-host=0.0.0.0 --num-cpus=2
--------------------------------------
C:\Users\jack>ray start --head --port=6379 --redis-shard-ports=6380 --node-manager-port=12345 --object-manager-port=12346   --dashboard-host=0.0.0.0 --num-cpus=2
Local node IP: 192.168.2.19
2021-01-25 15:22:55,221 INFO services.py:1173 -- View the Ray dashboard at http://192.168.2.19:8265

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='192.168.2.19:6379' --redis-password='5241590000000000'

  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='5241590000000000')

  If connection fails, check your firewall settings and network configuration.

  To terminate the Ray runtime, run
    ray stop

==========================================================
----------------------machine （b） 
OS:    Ubuntu 20.04.1 LTS 
user:   ray
python: 3.7.7
ray:        1.1.0
cmd： ray start  --address=192.168.2.19:6379 --node-manager-port=12345 --object-manager-port=12346  --num-cpus=1
--------------------------------------

docker exec -it  ray  bash
(base) ray@ut2-VirtualBox:/$ ps aux|grep ray
ray            1  0.0  0.0   6000  3844 pts/0    Ss+  23:35   0:00 /bin/bash
ray           20  0.1  0.0   6000  3852 pts/1    Ss   23:36   0:00 bash
ray           38  0.0  0.0   7656  3120 pts/1    R+   23:36   0:00 ps aux
ray           39  0.0  0.0   5196   656 pts/1    S+   23:36   0:00 grep --color=auto ray
(base) ray@ut2-VirtualBox:/$ ray start  --address=192.168.2.19:6379 --node-manager-port=12345 --object-manager-port=12346  --num-cpus=1
Local node IP: 192.168.2.25
Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1504, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 651, in start
    ray_params, head=False, shutdown_at_exit=block, spawn_reaper=block)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 161, in __init__
    self._init_temp(redis_client)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 252, in _init_temp
    try_to_create_directory(self._temp_dir)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/utils.py", line 766, in try_to_create_directory
    os.makedirs(directory_path, exist_ok=True)
  File "/home/ray/anaconda3/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\jack\\AppData\\Local\\Temp\\ray'
(base) ray@ut2-VirtualBox:/$

**Comment by jack2nb** [comment]
PermissionError: [Errno 13] Permission denied: 'C:\Users\jack\AppData\Local\Temp\ray'

why？ why？

**Comment by iuming** [comment]
I also want to do the same attempt. Is this resolved?

**Comment by jack2nb** [comment]
no
