### ISSUE TITLE
[RLlib] Error when calling `rllib/models/catalog.py::get_action_shape()` and tf is not installed when action space is Dict()

### ISSUE THREAD

**Issue by stanislav-chekmenev** [ray-project/ray#13761]
It's a continuation of this issue [13330](https://github.com/ray-project/ray/issues/13330)

When a custom environment is created with an  `self.action_space = gym.spaces.Dict({})` a similar error to the above issue happens again. In particular, when framework=torch and rllib/models/catalog.py::get_action_shape() is called from, for instance,
Policy::_get_dummy_batch_from_view_requirements(), rllib crashes. **This doesn't happen for gym.spaces.Box()**, for example.

Ray: 2.0.0.dev0, Python: 3.8.6, torch: 1.7.1, Ubuntu: 18.04

That's the code to run 

```python
import gym, ray
from ray.rllib.agents import ppo

class MyEnv(gym.Env):
    def __init__(self, env_config):
        self.action_space = gym.spaces.Dict({'test': gym.spaces.Box(0, 1, shape=(1, ))})
        self.observation_space = gym.spaces.Box(0, 2, shape=(2, ))
    def reset(self):
        return [0, 0]
    def step(self, action):
        return [0, 0], 1.0, False, {}

ray.init()
trainer = ppo.PPOTrainer(env=MyEnv, config={
    "env_config": {},
    "framework": 'torch',
    "log_level": 'DEBUG'
})

while True:
    print(trainer.train())
```
- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

Error message:

Traceback (most recent call last):
  File "/home/stas/PycharmProjects/test/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 654, in setup
    self._init(self.config, self.env_creator)
  File "/home/stas/PycharmProjects/test/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 134, in _init
    self.workers = self._make_workers(
  File "/home/stas/PycharmProjects/test/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 725, in _make_workers
    return WorkerSet(
  File "/home/stas/PycharmProjects/test/venv/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 79, in __init__
    remote_spaces = ray.get(self.remote_workers(
  File "/home/stas/PycharmProjects/test/venv/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/stas/PycharmProjects/test/venv/lib/python3.8/site-packages/ray/worker.py", line 1458, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::RolloutWorker.foreach_policy() (pid=13859, ip=172.20.10.11)
  File "python/ray/_raylet.pyx", line 439, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 473, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 476, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/home/stas/PycharmProjects/test/venv/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 479, in __init__
    self.policy_map, self.preprocessors = self._build_policy_map(
  File "/home/stas/PycharmProjects/test/venv/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1111, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/home/stas/PycharmProjects/test/venv/lib/python3.8/site-packages/ray/rllib/policy/policy_template.py", line 266, in __init__
    self._initialize_loss_from_dummy_batch(
  File "/home/stas/PycharmProjects/test/venv/lib/python3.8/site-packages/ray/rllib/policy/policy.py", line 618, in _initialize_loss_from_dummy_batch
    self._dummy_batch = self._get_dummy_batch_from_view_requirements(
  File "/home/stas/PycharmProjects/test/venv/lib/python3.8/site-packages/ray/rllib/policy/policy.py", line 712, in _get_dummy_batch_from_view_requirements
    _, shape = ModelCatalog.get_action_shape(view_req.space)
  File "/home/stas/PycharmProjects/test/venv/lib/python3.8/site-packages/ray/rllib/models/catalog.py", line 297, in get_action_shape
    return dl_lib.int64 if all_discrete else dl_lib.float32, \
AttributeError: 'NoneType' object has no attribute 'float32'

**Comment by stanislav-chekmenev** [comment]
I think, that this change in ray/rllib/policy/policy.py in line 712 should fix it

`_, shape = ModelCatalog.get_action_shape(view_req.space, framework=self.config['framework'])`
