### ISSUE TITLE
1.2.0 long running release tests fail

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#13809]
### What is the problem?

The long running distributed release tests fail due the following error. Seems like a test/deprecation error. 

```
(pid=391, ip=172.31.22.10) Files already downloaded and verified                                        
2021-01-29 14:51:49,057 ERROR trial_runner.py:616 -- Trial NoFaultToleranceTrainable_72ce7_00000: Error processing event.
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 586, in _process_trial
    results = self.trial_executor.fetch_result(trial)                                                    
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 609, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)                                       
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)                                                                        
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1456, in get                
    raise value.as_instanceof_cause()            
ray.exceptions.RayTaskError(DeprecationWarning): ray::NoFaultToleranceTrainable.train_buffered() (pid=314, ip=172.31.22.10)
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task                                   
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor                 
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 167, in train_buffered
    result = self.train()                           
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 226, in train      
    result = self.step()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/torch_trainer.py", line 664, in step
    return super(TorchTrainable, self).step()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/torch_trainer.py", line 719, in step
    "Trainable._train is deprecated and will be "                                                       
DeprecationWarning: Trainable._train is deprecated and will be removed in a future version of Ray. Override Trainable.step instead.
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by wuisawesome** [comment]
The script also hangs afterwards:

```
Number of errored trials: 1
+---------------------------------------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| Trial name                            |   # failures | error file                                                                                                                                       |
|---------------------------------------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------|
| NoFaultToleranceTrainable_72ce7_00000 |            1 | /home/ray/ray_results/NoFaultToleranceTrainable_2021-01-29_14-50-56/NoFaultToleranceTrainable_72ce7_00000_0_lr=0.1_2021-01-29_14-50-56/error.txt |
+---------------------------------------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------+

(pid=314, ip=172.31.22.10) 2021-01-29 14:51:49,050      INFO trainable.py:103 -- Trainable.setup took 51.018 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
170500096it [00:46, 3652042.28it/s]                                
(pid=359, ip=172.31.24.199) 2021-01-29 14:51:49,930     INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://172.31.24.199:42327 [rank=0]
(pid=354, ip=172.31.22.10) 2021-01-29 14:51:49,931      INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://172.31.24.199:42327 [rank=2]
(pid=1339) 2021-01-29 14:51:49,931      INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://172.31.24.199:42327 [rank=1]
```

**Comment by richardliaw** [comment]
Should be fixed with @amogkam 's changes.
