### ISSUE TITLE
[Autoscaler] AWS autoscaler not automatically filling in ImageId

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#13800]
### What is the problem?

If no ImageId is specified, we used to have a default image, but now it errors.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

Example yaml: https://github.com/ray-project/ray/blob/master/release/long_running_distributed_tests/cluster.yaml

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/ray", line 11, in <module>
    load_entry_point('ray', 'console_scripts', 'ray')()
  File "/home/ubuntu/ray/python/ray/scripts/scripts.py", line 1519, in main
    return cli()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/ray/python/ray/scripts/scripts.py", line 1171, in submit
    create_or_update_cluster(
  File "/home/ubuntu/ray/python/ray/autoscaler/_private/commands.py", line 226, in create_or_update_cluster
    try_logging_config(config)
  File "/home/ubuntu/ray/python/ray/autoscaler/_private/commands.py", line 73, in try_logging_config
    log_to_cli(config)
  File "/home/ubuntu/ray/python/ray/autoscaler/_private/aws/config.py", line 179, in log_to_cli
    print_info(
  File "/home/ubuntu/ray/python/ray/autoscaler/_private/aws/config.py", line 129, in print_info
    head_value_str = config["head_node"][key]
KeyError: 'ImageId'
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ijrsvt** [comment]
@wuisawesome This behavior is not new. The 'filling in AMI' applies to when there is no configuration provided. 
```
defaults = {"head_node" : {"InstanceType": "m5.large", "ImageId" : "ami-xxxxx"}} #Default YAML
config = {"head_node" : {"InstanceType": "gpu.xlarge"}} # What the user provides
defaults.update(config)
return defaults
# defaults now has InstanceType: gpuxlarge and no ami
```
That being said, we can default to adding this to the `head_node` and `worker_nodes`!

**Comment by wuisawesome** [comment]
I see... strange that the release test yaml just never worked... I suppose in that case this is a feature request.

**Comment by ijrsvt** [comment]
@wuisawesome Welp, it was an easy fix!
