### ISSUE TITLE
Fail to build master branch - 'No such file or directory: 'ray/streaming/generated'

### ISSUE THREAD

**Issue by gilv** [ray-project/ray#13826]
Trying to build current master branch, fails with exception

````
    $TEST_TMPDIR defined: output root default is '/tmp/bazel' and max_idle_secs default is '15'.
    Starting local Bazel server and connecting to it...
    Loading:
    Loading: 0 packages loaded
    DEBUG: /Users/me/Dev/ray/bazel/ray_deps_setup.bzl:63:14: No implicit mirrors used because urls were explicitly provided
    Analyzing: target //:ray_pkg (1 packages loaded, 0 targets configured)
    Analyzing: target //:ray_pkg (26 packages loaded, 1192 targets configured)
    Analyzing: target //:ray_pkg (26 packages loaded, 1192 targets configured)
    Analyzing: target //:ray_pkg (71 packages loaded, 4122 targets configured)
    INFO: Analyzed target //:ray_pkg (83 packages loaded, 14068 targets configured).
    INFO: Found 1 target...
    INFO: Deleting stale sandbox base /private/tmp/bazel/_bazel_me/c2320a57dc3987c02665247104ca1447/sandbox
    [0 / 797] [Prepa] BazelWorkspaceStatusAction stable-status.txt
    [2,799 / 3,163] checking cached actions
    Target //:ray_pkg up-to-date:
      bazel-bin/ray_pkg.out
    INFO: Elapsed time: 15.424s, Critical Path: 1.25s
    INFO: 0 processes.
    INFO: Build completed successfully, 1 total action
    INFO: Build completed successfully, 1 total action
    error: [Errno 2] No such file or directory: 'ray/streaming/generated'
ERROR: Command errored out with exit status 1: /Users/me/.pyenv/versions/3.8.5/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/me/Dev/ray/python/setup.py'"'"'; __file__='"'"'/Users/me/Dev/ray/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 391, in run
    installed = install_given_reqs(
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 80, in install_given_reqs
    requirement.install(
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 764, in install
    install_editable_legacy(
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pip/_internal/operations/install/editable_legacy.py", line 49, in install_editable
    call_subprocess(
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 258, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /Users/me/.pyenv/versions/3.8.5/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/me/Dev/ray/python/setup.py'"'"'; __file__='"'"'/Users/me/Dev/ray/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Removed build tracker: '/private/var/folders/nw/kg5kt9150nj48738r5wz9ly80000gn/T/pip-req-tracker-mpril85v'
```

**Comment by gilv** [comment]
`rm -R -f /tmp/bazel` did the trick...

**Comment by AlexanderKoch-Koch** [comment]
I have the same problem. However, your fix doesn't work for me. /tmp/bazel doesn't exist on my machine (MacOS with M1).

**Comment by richardliaw** [comment]
I just ran into this problem 

@AlexanderKoch-Koch you might not be able to build on m1.

cc @wuisawesome has previously mentioned:

> I did bazel clean --expunge uninstalled binutils then rebuilt via bazel clean --expnge then redid pip install -e . --verbose and it worked

**Comment by jon-chuang** [comment]
For posterity, I managed to fix a similar error by running the relevant manual bazel rule. 
e.g.
```python
copy_to_workspace(
    name = "cp_serve_py_proto",
    srcs = [":serve_py_proto"],
    dstdir = "python/ray/serve/generated",
)
```

```
bazel build cp_serve_py_proto
```

I was building from source in a local repo, however.
