### ISSUE TITLE
[RLlib] Enabling observation compression with muliagent PPO crashes with nonsensical error

### ISSUE THREAD

**Issue by justinkterry** [ray-project/ray#13824]
### What is the problem?

I have multi-agent RLlib code using parameter shared PPO that otherwise works just fine. I needed to do a hyperparameter search, so I tried to start a run with observation compression and no other changes to see if it would save resources.

Simple code to reproduce is here: https://github.com/justinkterry/all_pistonball/tree/de8a5d4bdb52faf2650cc87ef12d804c4d20eb78

run_rllib.py works, run_rlllib2.py (only difference is setting "compress_observations": True) crashes with this nonsensical traceback error:

```
Traceback (most recent call last):
  File "/home/justinkterry/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 519, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 497, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/ray/worker.py", line 1379, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::PPO.train() (pid=50904, ip=129.2.189.150)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 415, in ray._raylet.execute_task.function_executor
  File "/home/justinkterry/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 508, in train
    raise e
  File "/home/justinkterry/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 494, in train
    result = Trainable.train(self)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 183, in train
    result = self.step()
  File "/home/justinkterry/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 147, in step
    res = next(self.train_exec_impl)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/justinkterry/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/justinkterry/.local/lib/python3.6/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/justinkterry/.local/lib/python3.6/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/justinkterry/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/justinkterry/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/justinkterry/.local/lib/python3.6/site-packages/ray/util/iter.py", line 791, in apply_foreach
    result = fn(item)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/ray/rllib/execution/train_ops.py", line 191, in __call__
    [tuples[k] for k in state_keys]))
  File "/home/justinkterry/.local/lib/python3.6/site-packages/ray/rllib/execution/multi_gpu_impl.py", line 218, in load_data
    sess.run([t.init_op for t in self._towers], feed_dict=feed_dict)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1142, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: 'BCJNGGhAv0cAAAAAAAA71wUAAGGABZW0RwABAPMZjBJudW1weS5jb3JlLm51bWVyaWOUjAtfZnJvbWJ1ZmZlcpSTlCiWQC8ATwAAgD8EAP///////////////////////7u/jpNnPxXgcz+cPX/IEjIx4N1dBAB/QGxlP+DKe1QALgBMAAQEAH9+LGI/Rnx9VAAqBEwABQgAL6lqUAAqOeHdXQQAf9QcRz/SPnVUACb/CNgYWj/0OTo/FXIRP267Dz+4oiY/vgVuUAAmsXaAEz9aXzM/OSdcmAEA+AAv7+5QACcAQAAMBAA/1LlwoAAmCDwBBAwAP6kteVAAJgycAD/OZGNMACYA2BUIUAB/I8BeP/YheFAAKgTkAH9Tw14/m3FyTAAStRDyfj+/aGY/62VjBADxCKqHYz9zSng/57RaP288TT8VSlw/LiljBAB/wjJmP1DuflwABuKGTlQ/uqsDP6mYtT6KiwQA8QTfgdg+CT8yP8McMT+IO90+zzy1BAD5BK8gtT5mRAE/nj9UP4SYbj9x7GIEAAAUAPEAHKt+P6WfWT9qWUI/o4g/BADxBL/LTT+shHQ/5Sp3P0/iTj+f2T8EAPEI1qxCP8yPVj/9tXA/U5AZP6rsuz4U7rQEALGZsLc+0TMZPxzxcbwANTqOY7QCMahPehQAAJQBAAwABEgBACQAABQA8QB4+n8/x4loP5uwSD+bKkAEAHFCsUg/P0hlHAAAJAAALAAEOAAARAAAFAAPBAD///////////////////////+/r8GFaD/j7XI/NnvwEwcP5BIZBPAUdaxzYT/wdnZ0Ew9EABkILAAEUAAACABvfApeP2BLHBcnAFgAAEgACAQAfx0VYD+1g3yoACYEEBQICAAvCkYgFy//ANBTVj+14jU/TAQSP3O0IqAAJvEEOEYRP2+7Dz9+RRc/mbY3PwOVWxQVAAwBDwQAISYXUwgYBEgBP5O2XqAAJgg4AQQMAD+CTmZQACYElAAICAAvK3soFxMPEAEBCEgAAAwAb3BNZD+w+iwDJwTkAAAIAG9pgGE/OhXkGisAlAAABABvC/FpPywD3BoT4rtVaT/fSSk/3UsXP/xSBADwBd8MHj9Ep1E/rZQ6P6oOAj87bvI+BAC//F/yPq7jET+0uF+UAQbi95VoP4uhGj/sPO8+biAEAPEESaUCP0N5TT+sL18/1WcgP27EDwQA8QhQrBA/RiMsP6c8az9KYTs/AQsXP8iKFgQAAAwAABQA8QCJAnk/tMh/P3xgYz+Ctl0EAGJrCHo/ou2IFwB8FwBAAQAEAACUFwC4AfEACul4P1VRNT9FGPY+oBXwBABxhN3xPkqzMRwAACQAACwAADQAAAQAAEQAABQADwQA////////////////////////b2+Z13U/l4FAFCcMsBIAzBJ/BZxfP+wyboQvMgBMFAQEAACELy86SKwAKwRMAAQIAC9JFzAvKwRIAAgIACLtuuATDBwBDxAAEQBAAQQEAL94J1o/r5E6P0klP+wUBg9UAA0EtBcAfC+v13ETP58HMz/hyHAXJwi0FwT0AADIFA+IAA0PIAAFBEQACAgAP2gIafAAJgQ8AQgIAD9MfXNQACYImAAADABvm3JiP3/3hAInAEQABAQAAIAvLygUHDAnAFQBBOgAAJgAL/gQTAArAFAA/wxEbU0/R6ouP1HyMz/ACjU/6AM1PyhPQD+nuHJEAQYAnC8ApC8EsC8ACADxBGRLYz+8OHg/VoNBP2Vu7D7JEssEAL/5A8s+WoIIPyo6X1AABqKeP1Q/kqMDP05KtC8AvC/xBJJT2D6jKzI/SWZ/P/tQbz+9slcEAHGEalw/cTV1pBcArBcAtBcMwBe1TMB3P8rdWT9lrUK4L3H7G04/yql0hAAAfBcESAEEzAIApBcPwBchMZSMBXBH8RaUjAVkdHlwZZSTlIwCZjSUiYiHlFKUKEsDjAE8lE5OTkr/////BQDwBEsAdJRiTdARhZSMAUOUdJRSlC4AAAAA'
Result for PPO_pistonball_v3_f4d39_00000:
  {}

```

**Comment by sven1977** [comment]
Thanks for posting this issue @justinkterry ! Great catch: It seems like compression is not working at all for any algorithms that do NOT use a replay buffer.

**Comment by sven1977** [comment]
Simpler repro script:

```
from ray import tune
import ray

ray.init(local_mode=True)

tune.run(
    "PPO",
    name="PPO",
    stop={"episodes_total": 60000},
    config={
        "env": "CartPole-v0",
        "num_gpus": 0,
        "num_workers": 0,
        "num_envs_per_worker": 1,
        "compress_observations": True,
        "simple_optimizer": True,#TODO
    },
)
```

**Comment by sven1977** [comment]
PR that fixes this problem:
https://github.com/ray-project/ray/pull/14034
