### ISSUE TITLE
[rllib] CQL throws Torch error "RuntimeError: All input tensors must be on the same device. Received cuda:0 and cpu"

### ISSUE THREAD

**Issue by fercook** [ray-project/ray#13823]
### What is the problem?

A simple test of the CQL agent throws this Torch error:
`RuntimeError: All input tensors must be on the same device. Received cuda:0 and cpu
`

*Ray version and other system information (Python version, TensorFlow version, OS):*

Ray: 1.2.0
Python: 3.7.4
torch.__version__ == 1.5.0a0+4ff3872
tensorflow.__version__ == 2.3.0
OS: Linux

### Reproduction (REQUIRED)
```
import ray
from ray.rllib.agents import cql
ray.init()

config = {}
config['num_workers'] = 1
config['num_gpus'] = 1
config['framework'] = 'torch'
config['input']='./demo-out/'

trainer = cql.CQLTrainer(config=config, env="Pendulum-v0")
for _ in range(100):
    trainer.train()
```

Data in folder demo-out was generated using the [example from the documentation](https://docs.ray.io/en/master/rllib-offline.html)

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

Full error message:
```
$ python testcql.py 
WARNING:tensorflow:From /apps/PYTHON/3.7.4_ML/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2021-01-30 20:59:26,955	INFO services.py:1174 -- View the Ray dashboard at http://127.0.0.1:8265
2021-01-30 20:59:45,834	INFO trainer.py:643 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=98180) WARNING:tensorflow:From /apps/PYTHON/3.7.4_ML/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=98180) Instructions for updating:
(pid=98180) non-resource variables are not supported in the long term
(pid=98180) 2021-01-30 20:59:50,081	WARNING sac_tf_policy.py:66 -- When not using a state-preprocessor with SAC, `fcnet_hiddens` will be set to an empty list! Any hidden layer sizes are defined via `policy_model.fcnet_hiddens` and `Q_model.fcnet_hiddens`.
(pid=98180) 2021-01-30 20:59:50,081	WARNING deprecation.py:34 -- DeprecationWarning: `framestack` has been deprecated. Use `num_framestacks (int)` instead. This will raise an error in the future!
(pid=98180) 2021-01-30 20:59:50,088	WARNING deprecation.py:34 -- DeprecationWarning: `framestack` has been deprecated. Use `num_framestacks (int)` instead. This will raise an error in the future!
(pid=98180) 0
2021-01-30 20:59:50,272	WARNING sac_tf_policy.py:66 -- When not using a state-preprocessor with SAC, `fcnet_hiddens` will be set to an empty list! Any hidden layer sizes are defined via `policy_model.fcnet_hiddens` and `Q_model.fcnet_hiddens`.
2021-01-30 20:59:50,272	WARNING deprecation.py:34 -- DeprecationWarning: `framestack` has been deprecated. Use `num_framestacks (int)` instead. This will raise an error in the future!
2021-01-30 20:59:50,280	WARNING deprecation.py:34 -- DeprecationWarning: `framestack` has been deprecated. Use `num_framestacks (int)` instead. This will raise an error in the future!
(pid=98180) 2021-01-30 20:59:50,264	WARNING json_reader.py:55 -- Treating input directory as glob pattern: /gpfs/projects/bsc21/WORK-FERNANDO/OAS/demo-out/*.json
0
Traceback (most recent call last):
  File "testcql.py", line 12, in <module>
    trainer = cql.CQLTrainer(config=config, env="Pendulum-v0")
  File "/apps/RAY/1.2.0/lib/python3.7/site-packages/ray-1.2.0-py3.7-linux-ppc64le.egg/ray/rllib/agents/trainer_template.py", line 107, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/apps/RAY/1.2.0/lib/python3.7/site-packages/ray-1.2.0-py3.7-linux-ppc64le.egg/ray/rllib/agents/trainer.py", line 486, in __init__
    super().__init__(config, logger_creator)
  File "/apps/RAY/1.2.0/lib/python3.7/site-packages/ray-1.2.0-py3.7-linux-ppc64le.egg/ray/tune/trainable.py", line 97, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/apps/RAY/1.2.0/lib/python3.7/site-packages/ray-1.2.0-py3.7-linux-ppc64le.egg/ray/rllib/agents/trainer.py", line 654, in setup
    self._init(self.config, self.env_creator)
  File "/apps/RAY/1.2.0/lib/python3.7/site-packages/ray-1.2.0-py3.7-linux-ppc64le.egg/ray/rllib/agents/trainer_template.py", line 139, in _init
    num_workers=self.config["num_workers"])
  File "/apps/RAY/1.2.0/lib/python3.7/site-packages/ray-1.2.0-py3.7-linux-ppc64le.egg/ray/rllib/agents/trainer.py", line 731, in _make_workers
    logdir=self.logdir)
  File "/apps/RAY/1.2.0/lib/python3.7/site-packages/ray-1.2.0-py3.7-linux-ppc64le.egg/ray/rllib/evaluation/worker_set.py", line 98, in __init__
    spaces=spaces,
  File "/apps/RAY/1.2.0/lib/python3.7/site-packages/ray-1.2.0-py3.7-linux-ppc64le.egg/ray/rllib/evaluation/worker_set.py", line 362, in _make_worker
    _use_trajectory_view_api=config["_use_trajectory_view_api"],
  File "/apps/RAY/1.2.0/lib/python3.7/site-packages/ray-1.2.0-py3.7-linux-ppc64le.egg/ray/rllib/evaluation/rollout_worker.py", line 480, in __init__
    policy_dict, policy_config)
  File "/apps/RAY/1.2.0/lib/python3.7/site-packages/ray-1.2.0-py3.7-linux-ppc64le.egg/ray/rllib/evaluation/rollout_worker.py", line 1111, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/apps/RAY/1.2.0/lib/python3.7/site-packages/ray-1.2.0-py3.7-linux-ppc64le.egg/ray/rllib/policy/policy_template.py", line 268, in __init__
    stats_fn=stats_fn,
  File "/apps/RAY/1.2.0/lib/python3.7/site-packages/ray-1.2.0-py3.7-linux-ppc64le.egg/ray/rllib/policy/policy.py", line 655, in _initialize_loss_from_dummy_batch
    self._loss(self, self.model, self.dist_class, train_batch)
  File "/apps/RAY/1.2.0/lib/python3.7/site-packages/ray-1.2.0-py3.7-linux-ppc64le.egg/ray/rllib/agents/cql/cql_torch_policy.py", line 173, in cql_loss
    q1_rand = q_values_repeat(model, model_out_t, rand_actions)
  File "/apps/RAY/1.2.0/lib/python3.7/site-packages/ray-1.2.0-py3.7-linux-ppc64le.egg/ray/rllib/agents/cql/cql_torch_policy.py", line 52, in q_values_repeat
    preds = model.get_twin_q_values(obs_temp, actions)
  File "/apps/RAY/1.2.0/lib/python3.7/site-packages/ray-1.2.0-py3.7-linux-ppc64le.egg/ray/rllib/agents/sac/sac_torch_model.py", line 204, in get_twin_q_values
    return self.twin_q_net(torch.cat([model_out, actions], -1))
RuntimeError: All input tensors must be on the same device. Received cuda:0 and cpu
```

**Comment by sven1977** [comment]
@michaelzhiluo ^

**Comment by michaelzhiluo** [comment]
A fix for this will be included in a future PR (i'll ref this) where there will be CQL benchmarks.

**Comment by sven1977** [comment]
Thanks for filing this @fercook! Could you try this on the latest master? I'm sure this was fixed already:
In particular:
rllib/agents/sac/sac_torch_policy.py::setup_late_mixins, where we make sure the target model is moved to the GPU.

I just confirmed on a single GPU machine using your script and did not see this error (running all fine).

Closing this issue now.
