### ISSUE TITLE
Certain types of errors aren't deserialized properly in Ray client

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#13842]
```
@ray.remote
class Actor:
    def __init__(self):
        with open("/dev/asdf", "w") as f:
            f.write("HI")

    def f(self):
        return 0

@ray.remote
def g():
    with open("/dev/asdf", "w") as f:
        f.write("HI")

# grpc error
ray.get(g.remote())

# grpc error
a = Actor.remote()
ray.get(a.f.remote())
```

The following gives:

```
Failed to deserialize b'\x80\x05\x95\xb4\x04\x00\x00\x00\x00\x00\x00\x8c\x1bray.cloudpickle.cloudpickle\x94\x8c\x14_make_skeleton_class\x94\x93\x94(\x8c\x08builtins\x94\x8c\x04type\x94\x93\x94\x8c\x1dRayTaskError(PermissionError)\x94\x8c\x0eray.exceptions\x94\x8c\x0cRayTaskError\x94\x93\x94h\x03\x8c\x0fPermissionError\x94\x93\x94\x86\x94}\x94\x8c 12f6bfd0e99e4172ba69f5c1445129c8\x94Nt\x94R\x94\x8c ray.cloudpickle.cloudpickle_fast\x94\x8c\x0f_class_setstate\x94\x93\x94h\x10}\x94(\x8c\x08__init__\x94h\x00\x8c\r_builtin_type\x94\x93\x94\x8c\nLambdaType\x94\x85\x94R\x94(h\x17\x8c\x08CodeType\x94\x85\x94R\x94(K\x07K\x00K\x07K\tKSC\x1at\x00\xa0\x01|\x00|\x01|\x02|\x03|\x04|\x05|\x06\xa1\x07\x01\x00d\x00S\x00\x94N\x85\x94h\x08h\x15\x86\x94(\x8c\x04self\x94\x8c\rfunction_name\x94\x8c\rtraceback_str\x94\x8c\tcause_cls\x94\x8c\tproctitle\x94\x8c\x03pid\x94\x8c\x02ip\x94t\x94\x8cA/home/ray/anaconda3/lib/python3.7/site-packages/ray/exceptions.py\x94h\x15KmC\x04\x00\x02\n\x01\x94))t\x94R\x94}\x94(\x8c\x0b__package__\x94\x8c\x03ray\x94\x8c\x08__name__\x94h\x07\x8c\x08__file__\x94\x8cA/home/ray/anaconda3/lib/python3.7/site-packages/ray/exceptions.py\x94uNNNt\x94R\x94h\x11\x8c\x12_function_setstate\x94\x93\x94h4}\x94}\x94(h0h\x15\x8c\x0c__qualname__\x94\x8c6RayTaskError.as_instanceof_cause.<locals>.cls.__init__\x94\x8c\x0f__annotations__\x94}\x94\x8c\x0e__kwdefaults__\x94N\x8c\x0c__defaults__\x94N\x8c\n__module__\x94h\x07\x8c\x07__doc__\x94N\x8c\x0b__closure__\x94N\x8c\x17_cloudpickle_submodules\x94]\x94\x8c\x0b__globals__\x94}\x94h\x08h\tsu\x86\x94\x86R0h@Nu}\x94\x86\x94\x86R0)R\x94}\x94(h%\x8c\x08ray::g()\x94h&M\x88\x0bh\'\x8c\r172.31.26.200\x94h"\x8c\n__main__.g\x94h#\x8c\xc6Traceback (most recent call last):\n  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task\n  File "actor.py", line 16, in g\nPermissionError: [Errno 13] Permission denied: \'/dev/asdf\'\n\x94h$h\x0bub.'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 176, in _get
    err = cloudpickle.loads(data.error)
TypeError: __init__() missing 6 required positional arguments: 'function_name', 'traceback_str', 'cause_cls', 'proctitle', 'pid', and 'ip'
Traceback (most recent call last):
  File "actor.py", line 20, in <module>
    ray.get(g.remote())
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 46, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/util/client/api.py", line 33, in get
    return self.worker.get(vals, timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 163, in get
    out = [self._get(x, timeout) for x in to_get]
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 163, in <listcomp>
    out = [self._get(x, timeout) for x in to_get]
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 176, in _get
    err = cloudpickle.loads(data.error)
TypeError: __init__() missing 6 required positional arguments: 'function_name', 'traceback_str', 'cause_cls', 'proctitle', 'pid', and 'ip'

```

**Comment by barakmich** [comment]
This smells like another Python version mismatch to me -- the unpickling of the exception which doesn't have the same arguments. Can we confirm?

**Comment by ericl** [comment]
Other exceptions work fine. I think it's to do with the type of exception: PermissionError.

**Comment by barakmich** [comment]
Moving tracking to #14161
