### ISSUE TITLE
[autoscaler][kubernetes] Unexpected nodeType required

### ISSUE THREAD

**Issue by holdenk** [ray-project/ray#13876]
### What is the problem?

Ray version: a3796b3ed536194a6226a0a844a1249d067f7dd5

### Reproduction (REQUIRED)

Follow the directions at https://docs.ray.io/en/master/cluster/k8s-operator.html, get the following error:

(base) holden@hkdesktop:~/repos/ray$ kubectl logs -n ray ray-operator-pod
example-cluster:2021-02-02 21:36:20,772	DEBUG config.py:74 -- Updating the resources of node type head-node to include {'CPU': 1, 'GPU': 0}.
example-cluster:2021-02-02 21:36:20,773	DEBUG config.py:74 -- Updating the resources of node type worker-nodes to include {'CPU': 1, 'GPU': 0}.
Process example-cluster:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ray/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/operator/operator.py", line 68, in _create_or_update
    self.start_head()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/operator/operator.py", line 73, in start_head
    self.config = commands.create_or_update_cluster(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 213, in create_or_update_cluster
    config = _bootstrap_config(config, no_config_cache=no_config_cache)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 286, in _bootstrap_config
    validate_config(config)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/util.py", line 86, in validate_config
    raise ValueError("You must specify `worker_default_node_type` if "
ValueError: You must specify `worker_default_node_type` if `available_node_types is set.
2021-02-02 21:36:20,575	INFO commands.py:210 -- Cluster: example-cluster
2021-02-02 21:36:20,769	INFO commands.py:271 -- Checking Kubernetes environment settings

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html). (N/A: No ARM wheels)

**Comment by holdenk** [comment]
I suspect this may be related to 4d6817c6832f64ae7340fb62989eb28b7c1ff3d1 by @AmeerHajAli

**Comment by AmeerHajAli** [comment]
CC @DmitriGekhtman 
This is fixed in the latest nightly.
