### ISSUE TITLE
[core] --redis-password not working

### ISSUE THREAD

**Issue by stoep** [ray-project/ray#13879]
### What is the problem?

It seems like `--redis-password` is not working properly. When I supply `--redis-password` I can't connect from the same machine or remote machines. Without supplying `--redis-password` I am able to connect from the same machine and/or remote machines. I tried using `--redis-password="1234"`, `--redis-password='1234'`  and `--redis-password=1234`. 

OS: Ubuntu 20.04
Ray version: 1.1.0
Python: 3.8.5 

### Reproduction
On remote host: 

```
(venv ) $ ray stop && ray start --head --redis-password=1234
Stopped all 12 Ray processes.
Local node IP: <MYIP>
2021-02-03 09:30:16,094 INFO services.py:1171 -- View the Ray dashboard at http://localhost:8265

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='<MYIP>:6379' --redis-password='1234'

  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='1234')

  If connection fails, check your firewall settings and network configuration.

  To terminate the Ray runtime, run
    ray stop
(venv) $
```

On other remote host:

```
(venv) $ ray start --address='<MYIP>:6379' --redis-password='1234'
Local node IP: <MYOTHERIP>

--------------------
Ray runtime started.
--------------------

To terminate the Ray runtime, run
  ray stop
(venv) $ ray status
2021-02-03 00:32:41,464 INFO scripts.py:1390 -- Connecting to Ray instance at <MYIP>:6379.
2021-02-03 00:32:41,467 INFO worker.py:656 -- Connecting to existing Ray cluster at address: <MYIP>:6379
Traceback (most recent call last):
  File "/data/script/venv/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/data/script/venv/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1504, in main
    return cli()
  File "/data/script/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/script/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/script/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/script/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/script/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/script/venv/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1391, in status
    ray.init(address=address)
  File "/data/script/venv/lib/python3.8/site-packages/ray/worker.py", line 759, in init
    _global_node = ray.node.Node(
  File "/data/script/venv/lib/python3.8/site-packages/ray/node.py", line 158, in __init__
    session_name = _get_with_retry(redis_client, "session_name")
  File "/data/script/venv/lib/python3.8/site-packages/ray/node.py", line 36, in _get_with_retry
    result = redis_client.get(key)
  File "/data/script/venv/lib/python3.8/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/data/script/venv/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/data/script/venv/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/data/script/venv/lib/python3.8/site-packages/redis/connection.py", line 567, in connect
    self.on_connect()
  File "/data/script/venv/lib/python3.8/site-packages/redis/connection.py", line 643, in on_connect
    auth_response = self.read_response()
  File "/data/script/venv/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: WRONGPASS invalid username-password pair    
```

Note: I get the same stacktrace if I run `ray status` on the first server when I executed `ray start --head --redis-password=1234`

**Comment by seraphzl** [comment]
I have the same problem as you. Does anybody know how to solve this issue?

### Reproduction (REQUIRED)

On remote server:

```javascript
$ ray start --head --port=6379 --redis-password='ray'
Local node IP: 172.31.3.13
2021-07-07 10:06:55,142	INFO services.py:1275 -- View the Ray dashboard at http://127.0.0.1:8265

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='172.31.3.13:6379' --redis-password='ray'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='ray')
  
  If connection fails, check your firewall settings and network configuration.
  
  To terminate the Ray runtime, run
    ray stop
```

On the same server as above:

```javascript
$ ray timeline
2021-07-07 10:07:06,424	INFO scripts.py:1361 -- Connecting to Ray instance at 172.31.3.13:6379.
2021-07-07 10:07:06,425	INFO worker.py:736 -- Connecting to existing Ray cluster at address: 172.31.3.13:6379
Traceback (most recent call last):
  File "/home/xxx/.local/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/xxx/.local/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1808, in main
    return cli()
  File "/home/xxx/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/xxx/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xxx/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxx/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1362, in timeline
    ray.init(address=address)
  File "/home/xxx/.local/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.7/site-packages/ray/worker.py", line 844, in init
    connect_only=True)
  File "/home/xxx/.local/lib/python3.7/site-packages/ray/node.py", line 163, in __init__
    session_name = _get_with_retry(redis_client, "session_name")
  File "/home/xxx/.local/lib/python3.7/site-packages/ray/node.py", line 41, in _get_with_retry
    result = redis_client.get(key)
  File "/home/xxx/.local/lib/python3.7/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/home/xxx/.local/lib/python3.7/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/xxx/.local/lib/python3.7/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/xxx/.local/lib/python3.7/site-packages/redis/connection.py", line 567, in connect
    self.on_connect()
  File "/home/xxx/.local/lib/python3.7/site-packages/redis/connection.py", line 643, in on_connect
    auth_response = self.read_response()
  File "/home/xxx/.local/lib/python3.7/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: WRONGPASS invalid username-password pair

```
