### ISSUE TITLE
Serialization error on Ray 2.0rc with pandas DataFrames

### ISSUE THREAD

**Issue by devin-petersohn** [ray-project/ray#13882]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 2.0rc

Serialization fails on putting a pandas DataFrame in Client mode.

Logs:

```
Got Error from data channel -- shutting down: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating responses: 'DataFrame' object has no attribute '_data'"
	debug_error_string = "{"created":"@1612307207.723737628","description":"Error received from peer ipv4:52.43.158.36:51005","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception iterating responses: 'DataFrame' object has no attribute '_data'","grpc_status":2}"
>
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/ray-env-v200/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ec2-user/anaconda3/envs/ray-env-v200/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/anaconda3/envs/ray-env-v200/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 87, in _data_main
    raise e
  File "/home/ec2-user/anaconda3/envs/ray-env-v200/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 62, in _data_main
    for response in resp_stream:
  File "/home/ec2-user/anaconda3/envs/ray-env-v200/lib/python3.7/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/home/ec2-user/anaconda3/envs/ray-env-v200/lib/python3.7/site-packages/grpc/_channel.py", line 803, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating responses: 'DataFrame' object has no attribute '_data'"
	debug_error_string = "{"created":"@1612307207.723737628","description":"Error received from peer ipv4:52.43.158.36:51005","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception iterating responses: 'DataFrame' object has no attribute '_data'","grpc_status":2}"
>

---------------------------------------------------------------------------
ConnectionError                           Traceback (most recent call last)
<ipython-input-4-db5f700c182c> in <module>
      6 
      7 
----> 8 x = ray.put(pandas.DataFrame(np.random.randint(0, 100, size=(2**4, 2**4))))
      9 
     10 

~/anaconda3/envs/ray-env-v200/lib/python3.7/site-packages/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
     44         global _client_hook_enabled
     45         if client_mode_enabled and _client_hook_enabled:
---> 46             return getattr(ray, func.__name__)(*args, **kwargs)
     47         return func(*args, **kwargs)
     48 

~/anaconda3/envs/ray-env-v200/lib/python3.7/site-packages/ray/util/client/api.py in put(self, *args, **kwargs)
     41             kwargs: opaque keyword arguments
     42         """
---> 43         return self.worker.put(*args, **kwargs)
     44 
     45     def wait(self, *args, **kwargs):

~/anaconda3/envs/ray-env-v200/lib/python3.7/site-packages/ray/util/client/worker.py in put(self, vals)
    191             to_put.append(vals)
    192 
--> 193         out = [self._put(x) for x in to_put]
    194         if single:
    195             out = out[0]

~/anaconda3/envs/ray-env-v200/lib/python3.7/site-packages/ray/util/client/worker.py in <listcomp>(.0)
    191             to_put.append(vals)
    192 
--> 193         out = [self._put(x) for x in to_put]
    194         if single:
    195             out = out[0]

~/anaconda3/envs/ray-env-v200/lib/python3.7/site-packages/ray/util/client/worker.py in _put(self, val)
    206         data = dumps_from_client(val, self._client_id)
    207         req = ray_client_pb2.PutRequest(data=data)
--> 208         resp = self.data_client.PutObject(req)
    209         return ClientObjectRef(resp.id)
    210 

~/anaconda3/envs/ray-env-v200/lib/python3.7/site-packages/ray/util/client/dataclient.py in PutObject(self, request, context)
    125                   context=None) -> ray_client_pb2.PutResponse:
    126         datareq = ray_client_pb2.DataRequest(put=request, )
--> 127         resp = self._blocking_send(datareq)
    128         return resp.put
    129 

~/anaconda3/envs/ray-env-v200/lib/python3.7/site-packages/ray/util/client/dataclient.py in _blocking_send(self, req)
    104             if self._in_shutdown:
    105                 raise ConnectionError(
--> 106                     f"cannot send request {req}: data channel shutting down")
    107             data = self.ready_data[req_id]
    108             del self.ready_data[req_id]

ConnectionError: cannot send request req_id: 2
put {
```

Originally reported here: https://discuss.modin.org/t/unable-to-connect-to-external-ray-cluster/175/9

Related to: https://discuss.ray.io/t/error-in-rpc-call-in-client-mode/703

### Reproduction (REQUIRED)

```
import ray
import ray.util
ray.util.connect('<HOST>:<PORT>')

import modin.pandas as pd
import pandas
import numpy as np

x = ray.put(pandas.DataFrame(np.random.randint(0, 100, size=(2**4, 2**4)))
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
Cc @barakmich

**Comment by barakmich** [comment]
Two quick notes as I'm triaging

1) I can get a repro without modin just the version of pandas it uses
2) pandas 1.0.5 worked no problem. pandas 1.1.5 shows the error

**Comment by barakmich** [comment]
Aha, I got that repro with version skew. If both ends are pandas 1.1.5, no problem. If both are 1.0.5, no problem. But if it's 1.0.5 on the server, and 1.1.5 in the client (as would a client with modin, and, say, a server in a container) then it's easy to cause.

That's why the error as reported is telling the truth: 
```	details = "Exception iterating responses: 'DataFrame' object has no attribute '_data'"```
Because the `_data` attribute exists in 1.1.5 but not in 1.0.5 -- so when it unpickles on the server side it doesn't know how to construct it.

If you could check the versions to confirm, that'd be a big help.

/cc @ericl as this is growing out of the direct issue scope

**Comment by devin-petersohn** [comment]
I think we can bypass the need to serialize across pandas versions. Modin relies on 1.1.5 currently (1.2 soon) and there will be issues if the server side has the wrong version of pandas. 

Is it possible to install or update dependencies on the server side after the cluster is created?

**Comment by ericl** [comment]
Right now you need to restart the cluster after dependencies are updated (due to python import caching in Ray workers).

**Comment by devin-petersohn** [comment]
Ok, so it seems like the best fix will be a documentation page and maybe slightly better error messages.

Should we provide a Modin example on the Ray Client documentation page for how to install dependencies?

**Comment by richardliaw** [comment]
yep, that'd be great :)

**Comment by richardliaw** [comment]
Closing this for now since it should be largely resolved
