### ISSUE TITLE
[release][xgboost] GPU test fails to run 

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#13954]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
The XGBoost tests fail to run due to the following error: 

```
2021-02-05 18:42:48,591	INFO worker.py:655 -- Connecting to existing Ray cluster at address: 172.31.22.51:6379
2021-02-05 18:42:49,199	INFO main.py:729 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-02-05 18:42:51,115	INFO main.py:766 -- [RayXGBoost] Starting XGBoost training.
[2m[36m(pid=2594, ip=172.31.24.248)[0m [18:42:50] task [xgboost.ray]:140322082287120 got new rank 1
[2m[36m(pid=2594, ip=172.31.24.248)[0m [18:42:50] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[2m[36m(pid=2629, ip=172.31.29.35)[0m [18:42:51] task [xgboost.ray]:140356585345168 got new rank 2
[2m[36m(pid=2629, ip=172.31.29.35)[0m [18:42:51] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[2m[36m(pid=2607, ip=172.31.31.86)[0m [18:42:51] task [xgboost.ray]:140299452812752 got new rank 3
[2m[36m(pid=2607, ip=172.31.31.86)[0m [18:42:51] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[2m[36m(pid=2592, ip=172.31.23.39)[0m [18:42:51] task [xgboost.ray]:139782849355920 got new rank 0
[2m[36m(pid=2592, ip=172.31.23.39)[0m [18:42:51] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
2021-02-05 18:42:51,236	INFO elastic.py:155 -- Actor status: 4 alive, 0 dead (4 total)
2021-02-05 18:42:51,236	WARNING main.py:1089 -- A Ray actor died during training. Trying to restart and continue training from last checkpoint (restart 1 of 2). This will use 4 existing actors and start 0 new actors. Sleeping for 10 seconds for cleanup.
2021-02-05 18:43:01,253	INFO main.py:729 -- [RayXGBoost] Created 0 new actors (4 total actors). Waiting until actors are ready for training.
2021-02-05 18:43:01,360	INFO main.py:766 -- [RayXGBoost] Starting XGBoost training.
[2m[36m(pid=2629, ip=172.31.29.35)[0m [18:43:01] task [xgboost.ray]:140356585345168 got new rank 2
[2m[36m(pid=2629, ip=172.31.29.35)[0m [18:43:01] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[2m[36m(pid=2592, ip=172.31.23.39)[0m [18:43:01] task [xgboost.ray]:139782849355920 got new rank 0
[2m[36m(pid=2592, ip=172.31.23.39)[0m [18:43:01] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[2m[36m(pid=2594, ip=172.31.24.248)[0m [18:43:01] task [xgboost.ray]:140322082287120 got new rank 1
[2m[36m(pid=2594, ip=172.31.24.248)[0m [18:43:01] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[2m[36m(pid=2607, ip=172.31.31.86)[0m [18:43:01] task [xgboost.ray]:140299452812752 got new rank 3
[2m[36m(pid=2607, ip=172.31.31.86)[0m [18:43:01] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
2021-02-05 18:43:02,145	INFO elastic.py:155 -- Actor status: 4 alive, 0 dead (4 total)
2021-02-05 18:43:02,145	WARNING main.py:1089 -- A Ray actor died during training. Trying to restart and continue training from last checkpoint (restart 2 of 2). This will use 4 existing actors and start 0 new actors. Sleeping for 10 seconds for cleanup.
2021-02-05 18:43:12,163	INFO main.py:729 -- [RayXGBoost] Created 0 new actors (4 total actors). Waiting until actors are ready for training.
2021-02-05 18:43:12,281	INFO main.py:766 -- [RayXGBoost] Starting XGBoost training.
[2m[36m(pid=2594, ip=172.31.24.248)[0m [18:43:11] task [xgboost.ray]:140322082287120 got new rank 1
[2m[36m(pid=2592, ip=172.31.23.39)[0m [18:43:12] task [xgboost.ray]:139782849355920 got new rank 0
[2m[36m(pid=2629, ip=172.31.29.35)[0m [18:43:12] task [xgboost.ray]:140356585345168 got new rank 2
[2m[36m(pid=2607, ip=172.31.31.86)[0m [18:43:12] task [xgboost.ray]:140299452812752 got new rank 3
[2m[36m(pid=2607, ip=172.31.31.86)[0m [18:43:12] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[2m[36m(pid=2594, ip=172.31.24.248)[0m [18:43:11] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[2m[36m(pid=2592, ip=172.31.23.39)[0m [18:43:12] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[2m[36m(pid=2629, ip=172.31.29.35)[0m [18:43:12] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
2021-02-05 18:43:13,596	INFO elastic.py:155 -- Actor status: 4 alive, 0 dead (4 total)
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 838, in _train
    ray.get(ready)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RayXGBoostTrainingError): [36mray::RayXGBoostActor.train()[39m (pid=2629, ip=172.31.29.35)
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 470, in train
    raise RayXGBoostTrainingError("Training failed.")
xgboost_ray.main.RayXGBoostTrainingError: Training failed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 1049, in train
    **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 864, in _train
    raise RayActorError from exc
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task. Check python-core-worker-*.log files for more information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ray/release-automation-xgboost_tests/workloads/train_gpu.py", line 45, in <module>
    xgboost_params=None,
  File "/home/ray/release-automation-xgboost_tests/workloads/_train.py", line 87, in train_ray
    **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 1107, in train
    ) from exc
RuntimeError: A Ray actor died during training and the maximum number of retries (2) is exhausted.
```

note that ray does detect and create 4 gpus resources (and does detect that they are K80 gpus). 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

`ray submit --start oss_cluster_gpu_small.yaml workloads/train_gpu.py`

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment]
@wuisawesome this seems like a docker container issue.

The underlying AMI has nvidia drivers installed (`nvidia-smi` shows GPUs), this is why Ray detects the K80 GPUs. The container however does not have access: `nvidia-smi` is not found, drivers are not provided, and e.g. torch doesn't find the GPUs:

```
>>> torch.cuda.device_count()
/home/ray/anaconda3/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
```

We usually use the `ray:latest-gpu` or `ray:nightly-gpu` images for GPU testing, could you create a `ray:1.2.0-gpu` image for these tests? I'd also think that this problemwill show up e.g. in the rllib gpu tests?

**Comment by krfricke** [comment]
Actually, `rayproject/ray:1.2.0-gpu` exists. I'll update the cluster config

**Comment by krfricke** [comment]
Confirmed it does work:

```
(base) ray@ip-172-31-23-179:~/release-automation-xgboost_tests$ python workloads/train_gpu.py 
2021-02-08 05:58:43,257 INFO worker.py:655 -- Connecting to existing Ray cluster at address: 172.31.23.179:6379
2021-02-08 05:58:43,853 INFO main.py:729 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-02-08 05:58:45,376 INFO main.py:766 -- [RayXGBoost] Starting XGBoost training.
(pid=1241, ip=172.31.17.125) [05:58:45] task [xgboost.ray]:140483479684304 got new rank 1
(pid=1239, ip=172.31.24.124) [05:58:45] task [xgboost.ray]:139940030242576 got new rank 3
(pid=1238, ip=172.31.17.120) [05:58:45] task [xgboost.ray]:140479463878352 got new rank 0
(pid=1237, ip=172.31.24.108) [05:58:45] task [xgboost.ray]:139978570080016 got new rank 2
[05:58:55] WARNING: ../src/gbm/gbtree.cc:350: Loading from a raw memory buffer on CPU only machine.  Changing tree_method to hist.
[05:58:55] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[05:58:55] WARNING: ../src/gbm/gbtree.cc:350: Loading from a raw memory buffer on CPU only machine.  Changing tree_method to hist.
[05:58:55] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[05:58:55] WARNING: ../src/gbm/gbtree.cc:350: Loading from a raw memory buffer on CPU only machine.  Changing tree_method to hist.
[05:58:55] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[05:58:55] WARNING: ../src/gbm/gbtree.cc:350: Loading from a raw memory buffer on CPU only machine.  Changing tree_method to hist.
[05:58:55] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[05:58:55] WARNING: ../src/gbm/gbtree.cc:350: Loading from a raw memory buffer on CPU only machine.  Changing tree_method to hist.
[05:58:55] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[05:58:55] WARNING: ../src/gbm/gbtree.cc:350: Loading from a raw memory buffer on CPU only machine.  Changing tree_method to hist.
[05:58:55] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[05:58:55] WARNING: ../src/gbm/gbtree.cc:350: Loading from a raw memory buffer on CPU only machine.  Changing tree_method to hist.
[05:58:55] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[05:58:55] WARNING: ../src/gbm/gbtree.cc:350: Loading from a raw memory buffer on CPU only machine.  Changing tree_method to hist.
[05:58:55] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[05:58:55] WARNING: ../src/gbm/gbtree.cc:350: Loading from a raw memory buffer on CPU only machine.  Changing tree_method to hist.
[05:58:55] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[05:58:55] WARNING: ../src/gbm/gbtree.cc:350: Loading from a raw memory buffer on CPU only machine.  Changing tree_method to hist.
[05:58:55] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[05:58:55] WARNING: ../src/gbm/gbtree.cc:350: Loading from a raw memory buffer on CPU only machine.  Changing tree_method to hist.
[05:58:55] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
[05:58:55] WARNING: ../src/gbm/gbtree.cc:350: Loading from a raw memory buffer on CPU only machine.  Changing tree_method to hist.
[05:58:55] WARNING: ../src/learner.cc:222: No visible GPU is found, setting `gpu_id` to -1
2021-02-08 05:58:55,949 INFO main.py:886 -- [RayXGBoost] Finished XGBoost training on training data with total N=250,000.
TRAIN TIME TAKEN: 12.67 seconds
Final training error: 0.3309
```

**Comment by wuisawesome** [comment]
ahhh can't believe i didn't notice that. thanks for the catch. i think this means we're all good on xgboost tests for the release now.

**Comment by csaparna** [comment]
Why does the xgboost_ray still warn that it is a "CPU only machine" and  "No visible GPU is found, setting `gpu_id` to -1"?

**Comment by sebtac** [comment]
As "csaparna" asked, does it mean that the training used GPU or NOT? I aj heaving the same warning.
