### ISSUE TITLE
[release][tune] pytorch pbt failure frozen

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#13953]
### What is the problem?

When running the pytorch pbt release test, the test froze after < 5hrs and has now been frozen for over 5 hrs. This presumably fails the "ensure that it is printing new iterations" requirement. 

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by amogkam** [comment]
@wuisawesome could you paste some of the most recent stdout?

**Comment by wuisawesome** [comment]
```
(pid=33682, ip=172.31.17.218) 2021-02-05 19:52:28,021   INFO trainable.py:372 -- Restored on 172.31.17.218 from checkpoint: /home/ubuntu/ray_results/TorchTrainable_2021-02-05_19-47-
39/TorchTrainable_015a9_00000_0_lr=0.001_2021-02-05_19-47-40/tmpvc_moc7nrestore_from_object/trainer.checkpoint                                                                       
(pid=33682, ip=172.31.17.218) 2021-02-05 19:52:28,021   INFO trainable.py:379 -- Current state after restoring: {'_iteration': 1, '_timesteps_total': None, '_time_total': 28.5334279
53720093, '_episodes_total': None}                                                                                                                                                   
(pid=33682, ip=172.31.17.218) 2021-02-05 19:52:29,000   INFO trainable.py:72 -- Checkpoint size is 89459923 bytes                                                                    
(pid=33683, ip=172.31.17.218) 2021-02-05 19:51:23,803   INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://172.31.16.60:46865 [rank=1]
(pid=33657, ip=172.31.17.218) 2021-02-05 19:53:51,320   ERROR worker.py:390 -- SystemExit was raised from the worker
(pid=33657, ip=172.31.17.218) Traceback (most recent call last):
(pid=33657, ip=172.31.17.218)   File "python/ray/_raylet.pyx", line 570, in ray._raylet.task_execution_handler
(pid=33657, ip=172.31.17.218)   File "python/ray/_raylet.pyx", line 434, in ray._raylet.execute_task
(pid=33657, ip=172.31.17.218)   File "python/ray/_raylet.pyx", line 473, in ray._raylet.execute_task
(pid=33657, ip=172.31.17.218)   File "python/ray/_raylet.pyx", line 476, in ray._raylet.execute_task
(pid=33657, ip=172.31.17.218)   File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
(pid=33657, ip=172.31.17.218)   File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
(pid=33657, ip=172.31.17.218)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/function_manager.py", line 556, in actor_method_executor
(pid=33657, ip=172.31.17.218)     return method(__ray_actor, *args, **kwargs)
(pid=33657, ip=172.31.17.218)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 97, in __init__
(pid=33657, ip=172.31.17.218)     self.setup(copy.deepcopy(self.config))
(pid=33657, ip=172.31.17.218)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/torch_trainer.py", line 713, in setup
(pid=33657, ip=172.31.17.218)     self._trainer = self._create_trainer(config)
(pid=33657, ip=172.31.17.218)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/torch_trainer.py", line 671, in _create_trainer
(pid=33657, ip=172.31.17.218)     trainer = TorchTrainer(*args, **kwargs)
(pid=33657, ip=172.31.17.218)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/torch_trainer.py", line 266, in __init__
(pid=33657, ip=172.31.17.218)     self._start_workers(self.max_replicas)
(pid=33657, ip=172.31.17.218)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/torch_trainer.py", line 326, in _start_workers
(pid=33657, ip=172.31.17.218)     self.worker_group.start_workers(num_workers)
(pid=33657, ip=172.31.17.218)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/worker_group.py", line 231, in start_workers
(pid=33657, ip=172.31.17.218)     ray.get(self._setup_operator())
(pid=33657, ip=172.31.17.218)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
(pid=33657, ip=172.31.17.218)     return func(*args, **kwargs)
(pid=33657, ip=172.31.17.218)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1449, in get
(pid=33657, ip=172.31.17.218)     object_refs, timeout=timeout)
(pid=33657, ip=172.31.17.218)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 310, in get_objects
(pid=33657, ip=172.31.17.218)     object_refs, self.current_task_id, timeout_ms)
(pid=33657, ip=172.31.17.218)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 387, in sigterm_handler
(pid=33657, ip=172.31.17.218)     sys.exit(1)
(pid=33657, ip=172.31.17.218) SystemExit: 1
(pid=33611, ip=172.31.17.218) 2021-02-05 19:50:30,187   INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://172.31.16.60:36439 [rank=2]
170500096it [00:47, 3587590.45it/s]                                 
(pid=33668, ip=172.31.17.218) 2021-02-05 19:52:30,474   INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://172.31.16.60:45405 [rank=1]
(pid=33667, ip=172.31.17.218) Files already downloaded and verified
(pid=33659, ip=172.31.17.218) 2021-02-05 19:52:30,474   INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://172.31.16.60:45405 [rank=2]
(pid=33666, ip=172.31.17.218) 2021-02-05 19:52:21,112   INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://172.31.17.218:58465 [rank=0]
(pid=89261, ip=172.31.17.218) 2021-02-05 19:53:49,451   INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://172.31.17.218:39231 [rank=1]
(pid=89260, ip=172.31.17.218) 2021-02-05 19:53:49,450   INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://172.31.17.218:39231 [rank=0]
(pid=33681, ip=172.31.17.218) Files already downloaded and verified
(pid=33659, ip=172.31.17.218) Files already downloaded and verified
(pid=33668, ip=172.31.17.218) Files already downloaded and verified
(pid=89261, ip=172.31.17.218) Files already downloaded and verified
(pid=33667, ip=172.31.17.218) 2021-02-05 19:52:21,113   INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://172.31.17.218:58465 [rank=1]
```

this is the same error that's consistently repeated throughout the test it seems.

**Comment by krfricke** [comment]
I'll be using this issue for tracking progress on resolving problems in this test.

Running into NCCL errors on latest master:

```
Failure # 1 (occurred at 2021-02-22_08-53-47)
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 682, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 597, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1419, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::TorchTrainable.train_buffered() (pid=881, ip=172.31.1.180)
  File "python/ray/_raylet.pyx", line 450, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 483, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 486, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 496, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 443, in ray._raylet.execute_task.function_executor
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 97, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/torch_trainer.py", line 713, in setup
    self._trainer = self._create_trainer(config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/torch_trainer.py", line 671, in _create_trainer
    trainer = TorchTrainer(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/torch_trainer.py", line 266, in __init__
    self._start_workers(self.max_replicas)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/torch_trainer.py", line 326, in _start_workers
    self.worker_group.start_workers(num_workers)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/worker_group.py", line 227, in start_workers
    address=address, world_size=num_workers))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
ray.exceptions.RayTaskError(RuntimeError): ray::DistributedTorchRunner.setup_process_group() (pid=902, ip=172.31.10.237)
  File "python/ray/_raylet.pyx", line 496, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 443, in ray._raylet.execute_task.function_executor
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/distributed_torch_runner.py", line 61, in setup_process_group
    url, world_rank, world_size, timeout, backend=self.backend)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/utils.py", line 43, in setup_process_group
    timeout=timeout)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8
```

**Comment by krfricke** [comment]
More detailed debug message:

```

(pid=754, ip=172.31.10.221) ip-172-31-10-221:754:754 [0] NCCL INFO Bootstrap : Using [0]ens3:172.31.10.221<0> [1]veth804f9b9:fe80::f4f3:4bff:fee6:7ee%veth804f9b9<0>
(pid=754, ip=172.31.10.221) ip-172-31-10-221:754:754 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
(pid=754, ip=172.31.10.221)
(pid=754, ip=172.31.10.221) ip-172-31-10-221:754:754 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
(pid=754, ip=172.31.10.221) ip-172-31-10-221:754:754 [0] NCCL INFO NET/Socket : Using [0]ens3:172.31.10.221<0> [1]veth804f9b9:fe80::f4f3:4bff:fee6:7ee%veth804f9b9<0>
(pid=754, ip=172.31.10.221) ip-172-31-10-221:754:754 [0] NCCL INFO Using network Socket
(pid=754, ip=172.31.10.221)
(pid=754, ip=172.31.10.221) ip-172-31-10-221:754:882 [0] init.cc:573 NCCL WARN Duplicate GPU detected : rank 1 and rank 0 both on CUDA device 1d0
(pid=754, ip=172.31.10.221) ip-172-31-10-221:754:882 [0] NCCL INFO init.cc:840 -> 5
(pid=754, ip=172.31.10.221) ip-172-31-10-221:754:882 [0] NCCL INFO group.cc:73 -> 5 [Async thread]
(pid=757, ip=172.31.10.221) ip-172-31-10-221:757:757 [0] NCCL INFO Bootstrap : Using [0]ens3:172.31.10.221<0> [1]veth804f9b9:fe80::f4f3:4bff:fee6:7ee%veth804f9b9<0>
(pid=757, ip=172.31.10.221) ip-172-31-10-221:757:757 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
(pid=757, ip=172.31.10.221)
(pid=757, ip=172.31.10.221) ip-172-31-10-221:757:757 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
(pid=757, ip=172.31.10.221) ip-172-31-10-221:757:757 [0] NCCL INFO NET/Socket : Using [0]ens3:172.31.10.221<0> [1]veth804f9b9:fe80::f4f3:4bff:fee6:7ee%veth804f9b9<0>
(pid=757, ip=172.31.10.221) ip-172-31-10-221:757:757 [0] NCCL INFO Using network Socket
(pid=757, ip=172.31.10.221) NCCL version 2.7.8+cuda10.2
(pid=757, ip=172.31.10.221)
(pid=757, ip=172.31.10.221) ip-172-31-10-221:757:881 [0] init.cc:573 NCCL WARN Duplicate GPU detected : rank 0 and rank 1 both on CUDA device 1d0
(pid=757, ip=172.31.10.221) ip-172-31-10-221:757:881 [0] NCCL INFO init.cc:840 -> 5
(pid=757, ip=172.31.10.221) ip-172-31-10-221:757:881 [0] NCCL INFO group.cc:73 -> 5 [Async thread]
(pid=760, ip=172.31.10.221) 2021-03-22 06:20:53,952     ERROR worker.py:395 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::TorchTrainable.__init__() (pid=760, ip=172.31.10.221)
(pid=760, ip=172.31.10.221)   File "python/ray/_raylet.pyx", line 502, in ray._raylet.execute_task
(pid=760, ip=172.31.10.221)   File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task.function_executor
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=760, ip=172.31.10.221)     return method(__ray_actor, *args, **kwargs)
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 98, in __init__
(pid=760, ip=172.31.10.221)     self.setup(copy.deepcopy(self.config))
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/torch_trainer.py", line 723, in setup
(pid=760, ip=172.31.10.221)     self._trainer = self._create_trainer(config)
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/torch_trainer.py", line 682, in _create_trainer
(pid=760, ip=172.31.10.221)     return trainer
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/torch_trainer.py", line 266, in __init__
(pid=760, ip=172.31.10.221)     startup_success = self._start_workers(self.max_replicas)
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/torch_trainer.py", line 330, in _start_workers
(pid=760, ip=172.31.10.221)     return self.worker_group.start_workers(num_workers)
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/worker_group.py", line 229, in start_workers
(pid=760, ip=172.31.10.221)     address=address, world_size=num_workers))
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
(pid=760, ip=172.31.10.221)     return func(*args, **kwargs)
(pid=760, ip=172.31.10.221) ray.exceptions.RayTaskError(RuntimeError): ray::DistributedTorchRunner.setup_process_group() (pid=757, ip=172.31.10.221)
(pid=760, ip=172.31.10.221)   File "python/ray/_raylet.pyx", line 502, in ray._raylet.execute_task
(pid=760, ip=172.31.10.221)   File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task.function_executor
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=760, ip=172.31.10.221)     return method(__ray_actor, *args, **kwargs)
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/distributed_torch_runner.py", line 61, in setup_process_group
(pid=760, ip=172.31.10.221)     url, world_rank, world_size, timeout, backend=self.backend)
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/utils.py", line 43, in setup_process_group
(pid=760, ip=172.31.10.221)     timeout=timeout)
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
(pid=760, ip=172.31.10.221)     barrier()
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
(pid=760, ip=172.31.10.221)     work = _default_pg.barrier()
(pid=760, ip=172.31.10.221) RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
(pid=760, ip=172.31.10.221) 2021-03-22 06:20:53,953     ERROR worker.py:78 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::DistributedTorchRunner.setup_process_group() (pid=754, ip=172.31.10.221)
(pid=760, ip=172.31.10.221)   File "python/ray/_raylet.pyx", line 502, in ray._raylet.execute_task
(pid=760, ip=172.31.10.221)   File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task.function_executor
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=760, ip=172.31.10.221)     return method(__ray_actor, *args, **kwargs)
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/distributed_torch_runner.py", line 61, in setup_process_group
(pid=760, ip=172.31.10.221)     url, world_rank, world_size, timeout, backend=self.backend)
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/sgd/torch/utils.py", line 43, in setup_process_group
(pid=760, ip=172.31.10.221)     timeout=timeout)
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
(pid=760, ip=172.31.10.221)     barrier()
(pid=760, ip=172.31.10.221)   File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
(pid=760, ip=172.31.10.221)     work = _default_pg.barrier()
(pid=760, ip=172.31.10.221) RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
```

Seems to be related to #14759
