### ISSUE TITLE
[UX] Allow passing CPU and GPU to actor and task resources.

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#13996]
I want to create one placement group per actor in Serve. To do this, I need to pass the same resources into the placement group and actor constructors. However, I can't pass around the same resources dict because Ray complains when `CPU` and `GPU` are in the `resources` dict:

```python
import ray
ray.init()

@ray.remote
class A:
    pass

actor_resources = {"CPU": 1}
pg = ray.util.placement_group([actor_resources])

# Doesn't work, fails because "CPU" in resource dict.
a = A.options(resources=actor_resources).remote()

# Works, but messy.
a = A.options(num_cpus=actor_resources.pop("CPU", 0), num_gpus=actor_resources.pop("GPU", 0), resources=actor_resources).remote()
```

The first version gives the following error:
```
2021-02-08 15:19:42,065 INFO services.py:1193 -- View the Ray dashboard at http://127.0.0.1:8265               
Traceback (most recent call last):                                                                             
  File "test.py", line 10, in <module>                                                                         
    a = A.options(resources=actor_resources).remote()
  File "/Users/eoakes/code/ray/python/ray/actor.py", line 454, in remote
    return actor_cls._remote(
  File "/Users/eoakes/code/ray/python/ray/actor.py", line 670, in _remote
    resources = ray.utils.resources_from_resource_arguments(
  File "/Users/eoakes/code/ray/python/ray/utils.py", line 308, in resources_from_resource_arguments
    raise ValueError("The resources dictionary must not "
ValueError: The resources dictionary must not contain the key 'CPU' or 'GPU'
```

**Comment by edoakes** [comment]
@ericl @pcmoritz  I remember there being some reason for why we didn't allow passing CPU or GPU in the resources dict. It sort of makes sense to not allow it in the decorator because there are also kwargs for it, but is there a reason to ban it from`.options()`?

**Comment by ericl** [comment]
Options is internally calling the decorator, so that's probably the reason. Note a similar ambiguity arises even in options, since you have num_cpus and num_gpus available as args as well in addition to resources.

**Comment by edoakes** [comment]
@ericl the best solution I can think of is allow CPU/GPU in resources, but throw an error if either is passed both there and to `num_cpus` and `num_gpus`. Alternatively we could have one take precedence over the other but it isn't clear to me which should be higher precendence.

**Comment by ericl** [comment]
Raising an error only in case of conflict seems fine to me as well, though it could cause other unintuitive edge cases.

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
