### ISSUE TITLE
Ray.tune Travis test failure in TrainableFunctionApiTest.testRewriteEnv.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1404]
Encountered this test failure in https://github.com/ray-project/ray/pull/1403#issuecomment-355846709. The failing test is

```
python test/trial_runner_test.py
```

```
======================================================================
ERROR: testRewriteEnv (__main__.TrainableFunctionApiTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/trial_runner_test.py", line 53, in testRewriteEnv
    "env": "CartPole-v0",
  File "/home/travis/.local/lib/python3.6/site-packages/ray-0.3.0-py3.6-linux-x86_64.egg/ray/tune/tune.py", line 77, in run_experiments
    runner.step()
  File "/home/travis/.local/lib/python3.6/site-packages/ray-0.3.0-py3.6-linux-x86_64.egg/ray/tune/trial_runner.py", line 78, in step
    self._process_events()
  File "/home/travis/.local/lib/python3.6/site-packages/ray-0.3.0-py3.6-linux-x86_64.egg/ray/tune/trial_runner.py", line 160, in _process_events
    [result_id], _ = ray.wait(list(self._running.keys()))
ValueError: not enough values to unpack (expected 1, got 0)
```

This makes me think that `list(self._running.keys())` is the empty list or something like that. Can that be? cc @richardliaw @ericl

**Comment by ericl** [comment]
Hm I don't think, so, we only ever call `_process_events` if running is non-empty:
```
        elif self._running:
            self._process_events()
```

**Comment by richardliaw** [comment]
Has this shown up recently? Otherwise we can close this until further notice.

**Comment by RodgerLuo** [comment]
I got this issue recently:

```
Traceback (most recent call last):
  File "train_robots.py", line 128, in <module>
    run(args, parser)
  File "train_robots.py", line 120, in run
    queue_trials=args.queue_trials)
  File "/anaconda3/envs/autodesk/lib/python3.6/site-packages/ray/tune/tune.py", line 105, in run_experiments
    runner.step()
  File "/anaconda3/envs/autodesk/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 116, in step
    self._process_events()
  File "/anaconda3/envs/autodesk/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 237, in _process_events
    trial = self.trial_executor.get_next_available_trial()
  File "/anaconda3/envs/autodesk/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 188, in get_next_available_trial
    [result_id], _ = ray.wait(list(self._running))
ValueError: not enough values to unpack (expected 1, got 0)
```

That happened after 1036 iterations (35229 seconds). Before the training was interrupted, I kept got the warnings like `I0115 01:30:34.147289 438068672 local_scheduler_algorithm.cc:444] A task that has already been executed has been resubmitted, so we are ignoring it. This should only happen during reconstruction.`

Below is the full log of the error:

```
F0115 01:30:34.148392 438068672 local_scheduler.cc:1327] The last heartbeat was sent 33120 milliseconds ago.
*** Check failure stack trace: ***
    @        0x10d4350aa  google::LogMessage::Fail()
    @        0x10d432ece  google::LogMessage::SendToLog()
    @        0x10d433d4f  google::LogMessage::Flush()
    @        0x10d433b89  google::LogMessage::~LogMessage()
    @        0x10d433e45  google::LogMessage::~LogMessage()
    @        0x10d41e8dd  ray::RayLog::~RayLog()
    @        0x10d3cb413  heartbeat_handler()
    @        0x10d3fa50b  aeProcessEvents
    @        0x10d3fa67b  aeMain
    @        0x10d3cb857  start_server()
    @        0x10d3cc3bf  main
Traceback (most recent call last):
  File "train_robots.py", line 128, in <module>
    run(args, parser)
  File "train_robots.py", line 120, in run
    queue_trials=args.queue_trials)
  File "/anaconda3/envs/autodesk/lib/python3.6/site-packages/ray/tune/tune.py", line 105, in run_experiments
    runner.step()
  File "/anaconda3/envs/autodesk/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 116, in step
    self._process_events()
  File "/anaconda3/envs/autodesk/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 237, in _process_events
    trial = self.trial_executor.get_next_available_trial()
  File "/anaconda3/envs/autodesk/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 188, in get_next_available_trial
    [result_id], _ = ray.wait(list(self._running))
ValueError: not enough values to unpack (expected 1, got 0)
Remote function train failed with:

Traceback (most recent call last):
  File "/anaconda3/envs/autodesk/lib/python3.6/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/anaconda3/envs/autodesk/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/Users/t_luor/Desktop/Distributed_RL_Robotics/agents/agent.py", line 181, in train
    return Trainable.train(self)
  File "/anaconda3/envs/autodesk/lib/python3.6/site-packages/ray/tune/trainable.py", line 143, in train
    result = self._train()
  File "/Users/t_luor/Desktop/Distributed_RL_Robotics/agents/dqn/dqn.py", line 198, in _train
    self.optimizer.step()
  File "/Users/t_luor/Desktop/Distributed_RL_Robotics/optimizers/async_replay_optimizer.py", line 278, in step
    sample_timesteps, train_timesteps = self._step()
  File "/Users/t_luor/Desktop/Distributed_RL_Robotics/optimizers/async_replay_optimizer.py", line 322, in _step
    for ra, replay in self.replay_tasks.completed():
  File "/Users/t_luor/Desktop/Distributed_RL_Robotics/utils/actors.py", line 28, in completed
    ready, _ = ray.wait(pending, num_returns=len(pending), timeout=10)
  File "/anaconda3/envs/autodesk/lib/python3.6/site-packages/ray/worker.py", line 2622, in wait
    object_id_strs, timeout, num_returns)
  File "/anaconda3/envs/autodesk/lib/python3.6/site-packages/ray/utils.py", line 387, in _wrapper
    return orig_attr(*args, **kwargs)
  File "pyarrow/_plasma.pyx", line 630, in pyarrow._plasma.PlasmaClient.wait
  File "pyarrow/error.pxi", line 83, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Encountered unexpected EOF
```
