### ISSUE TITLE
Fail to run Mars example on ray 2.0dev

### ISSUE THREAD

**Issue by photoszzt** [ray-project/ray#14041]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version: 2.0dev, Mars: 0.7.0a5

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".
```python
from mars.session import new_session
ray_session = new_session(backend='ray').as_default()

import mars.dataframe as md
import mars.tensor as mt

t = mt.random.rand(100, 4, chunk_size=30)
df = md.DataFrame(t, columns=list('abcd'))
print(df.describe().execute())
```

Output:
```
2021-02-10 11:31:59,845	INFO services.py:1193 -- View the Ray dashboard at http://127.0.0.1:8265
Traceback (most recent call last):
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/site-packages/mars/ray/core.py", line 76, in _register_ray_serializer
    ray.register_custom_serializer(
AttributeError: module 'ray' has no attribute 'register_custom_serializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dataframe.py", line 9, in <module>
    print(df.describe().execute())
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/site-packages/mars/core.py", line 646, in execute
    return run()
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/site-packages/mars/core.py", line 642, in run
    self.data.execute(session, **kw)
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/site-packages/mars/core.py", line 379, in execute
    return run()
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/site-packages/mars/core.py", line 374, in run
    session.run(self, **kw)
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/site-packages/mars/session.py", line 505, in run
    result = self._sess.run(*tileables, **kw)
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/site-packages/mars/ray/core.py", line 247, in run
    return self._executor.execute_tileables(tileables, **kw)
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/site-packages/mars/utils.py", line 458, in _inner
    return func(*args, **kwargs)
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/site-packages/mars/executor.py", line 883, in execute_tileables
    self.execute_graph(chunk_graph, list(temp_result_keys),
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/site-packages/mars/executor.py", line 698, in execute_graph
    res = graph_execution.execute(retval)
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/site-packages/mars/executor.py", line 579, in execute
    future.result()
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/site-packages/mars/utils.py", line 458, in _inner
    return func(*args, **kwargs)
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/site-packages/mars/executor.py", line 446, in _execute_operand
    self.handle_op(first_op, results, self._mock)
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/site-packages/mars/ray/core.py", line 91, in handle_op
    return RayExecutor.handle(*args, **kw)
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/site-packages/mars/ray/core.py", line 185, in handle
    _register_ray_serializer(op)
  File "/mnt/data/miniconda3/envs/ray/lib/python3.8/site-packages/mars/ray/core.py", line 84, in _register_ray_serializer
    context.register_custom_serializer(
AttributeError: 'SerializationContext' object has no attribute 'register_custom_serializer'

```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
cc @stephanie-wang Is it the same issue you found?

**Comment by stephanie-wang** [comment]
Yes, Mars is currently only supported with Ray 1.0. I opened an issue on Mars to add the dependency [here](https://github.com/mars-project/mars/issues/1985), but if you're looking to use later versions of Ray with Mars, I suggest opening another issue on the Mars GitHub to request a migration.
