### ISSUE TITLE
[autoscaler] Error when availability zone is not specified.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1407]
I just ran

```
ray create_or_update ~/Workspace/ray/python/ray/autoscaler/aws/development-example.yaml
```

and ran into the following error. Most likely introduced in #1393.

```
Traceback (most recent call last):
  File "/Users/rkn/anaconda3/bin/ray", line 11, in <module>
    load_entry_point('ray', 'console_scripts', 'ray')()
  File "/Users/rkn/Workspace/ray/python/ray/scripts/scripts.py", line 276, in main
    return cli()
  File "/Users/rkn/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rkn/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/rkn/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rkn/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rkn/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/rkn/Workspace/ray/python/ray/scripts/scripts.py", line 260, in create_or_update
    cluster_config_file, min_workers, max_workers, no_restart)
  File "/Users/rkn/Workspace/ray/python/ray/autoscaler/commands.py", line 27, in create_or_update_cluster
    validate_config(config)
  File "/Users/rkn/Workspace/ray/python/ray/autoscaler/autoscaler.py", line 479, in validate_config
    validate_config(config[k], schema[k])
  File "/Users/rkn/Workspace/ray/python/ray/autoscaler/autoscaler.py", line 472, in validate_config
    k, v.__name__))
ValueError: Missing required config key `availability_zone` of type str
```

cc @pschafhalter @ericl

**Comment by robertnishihara** [comment]
@pschafhalter has this been fixed?

**Comment by robertnishihara** [comment]
Just checked and this problem is still present. Let's fix this before 0.3.1.

**Comment by ericl** [comment]
I think the intent is to make this parameter mandatory...

**Comment by robertnishihara** [comment]
@ericl I see, why is that?

**Comment by ericl** [comment]
So far, all the parameters have been mandatory -- this would actually be the first optional one (that isn't opaquely passed to AWS).

This seems fine since in the example we provide a default, so you would have to delete it to break the script. We will probably have to revisit this when kubernetes integration lands (though that might be a bigger change).

**Comment by robertnishihara** [comment]
Ok, closing this issue because the field is required. The issue should no longer occur in the development example due to #1509.
