### ISSUE TITLE
[tune] Error when spilling objects: buf_len = len(buf) - ‘NoneType’ has no len()

### ISSUE THREAD

**Issue by mr-mcox** [ray-project/ray#14079]
### What is the problem?

Ray 2.0.0.dev nightly, Python 3.8, running on AWS EC2 Ubuntu AMI

When running `tune.run` I get the following error the first time an object is spilled:

    2021-02-12 17:48:30,412	WARNING worker.py:1109 -- Traceback (most recent call last):
      File "python/ray/_raylet.pyx", line 637, in ray._raylet.spill_objects_handler
      File "python/ray/_raylet.pyx", line 640, in ray._raylet.spill_objects_handler
      File "/opt/conda/lib/python3.8/site-packages/ray/external_storage.py", line 432, in spill_objects
        return _external_storage.spill_objects(object_refs, owner_addresses)
      File "/opt/conda/lib/python3.8/site-packages/ray/external_storage.py", line 244, in spill_objects
        return self._write_multiple_objects(f, object_refs,
      File "/opt/conda/lib/python3.8/site-packages/ray/external_storage.py", line 124, in _write_multiple_objects
        buf_len = len(buf)
    TypeError: object of type 'NoneType' has no len()
    An unexpected internal error occurred while the IO worker was spilling objects.
    (raylet) [2021-02-12 17:48:30,402 E 371 371] logging.cc:435: *** Aborted at 1613152110 (unix time) try "date -d @1613152110" if you are using GNU date ***
    (raylet) [2021-02-12 17:48:30,403 E 371 371] logging.cc:435: PC: @                0x0 (unknown)
    (raylet) [2021-02-12 17:48:30,403 E 371 371] logging.cc:435: *** SIGSEGV (@0x8) received by PID 371 (TID 0x7fccaa19d800) from PID 8; stack trace: ***
    (raylet) [2021-02-12 17:48:30,403 E 371 371] logging.cc:435:     @     0x55e8c6e8643f google::(anonymous namespace)::FailureSignalHandler()
    (raylet) [2021-02-12 17:48:30,403 E 371 371] logging.cc:435:     @     0x7fcca9d74980 (unknown)
    (raylet) [2021-02-12 17:48:30,404 E 371 371] logging.cc:435:     @     0x55e8c71e9e27 google::protobuf::RepeatedPtrField<>::Get()
    (raylet) [2021-02-12 17:48:30,405 E 371 371] logging.cc:435:     @     0x55e8c6ab38f5 ray::raylet::LocalObjectManager::AddSpilledUrls()
    (raylet) [2021-02-12 17:48:30,405 E 371 371] logging.cc:435:     @     0x55e8c6ab50ee _ZNSt17_Function_handlerIFvRKN3ray6StatusERKNS0_3rpc17SpillObjectsReplyEEZZNS0_6raylet18LocalObjectManager20SpillObjectsInternalERKSt6vectorINS0_8ObjectIDESaISC_EESt8functionIFvS3_EEENKUlSt10shared_ptrINS9_15WorkerInterfaceEEE_clESM_EUlS3_S7_E_E9_M_invokeERKSt9_Any_dataS3_S7_
    (raylet) [2021-02-12 17:48:30,405 E 371 371] logging.cc:435:     @     0x55e8c6abd1f2 ray::rpc::ClientCallImpl<>::OnReplyReceived()
    (raylet) [2021-02-12 17:48:30,406 E 371 371] logging.cc:435:     @     0x55e8c6acf072 _ZN5boost4asio6detail18completion_handlerIZN3ray3rpc17ClientCallManager29PollEventsFromCompletionQueueEiEUlvE_E11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm
    (raylet) [2021-02-12 17:48:30,408 E 371 371] logging.cc:435:     @     0x55e8c71fc381 boost::asio::detail::scheduler::do_run_one()
    (raylet) [2021-02-12 17:48:30,409 E 371 371] logging.cc:435:     @     0x55e8c71fda29 boost::asio::detail::scheduler::run()
    (raylet) [2021-02-12 17:48:30,410 E 371 371] logging.cc:435:     @     0x55e8c71fff17 boost::asio::io_context::run()
    (raylet) [2021-02-12 17:48:30,410 E 371 371] logging.cc:435:     @     0x55e8c6a2a2a2 main
    (raylet) [2021-02-12 17:48:30,411 E 371 371] logging.cc:435:     @     0x7fcca8e4bbf7 __libc_start_main
    (raylet) [2021-02-12 17:48:30,412 E 371 371] logging.cc:435:     @     0x55e8c6a3f395 (unknown)

Tail from `logs/raylet.out`:

    [2021-02-12 17:48:14,667 I 371 381] store.cc:230: Object store current usage 18.8078 / 19.2431 GB.
    [2021-02-12 17:48:25,900 I 371 371] node_manager.cc:503: Sending Python GC request to 2 local workers to clean up Python cyclic references.
    [2021-02-12 17:48:27,381 I 371 371] local_object_manager.cc:170: Spilled 1379 MiB, 1 objects, write throughput 891 MiB/s
    [2021-02-12 17:48:28,934 I 371 371] local_object_manager.cc:170: Spilled 2759 MiB, 2 objects, write throughput 890 MiB/s
    [2021-02-12 17:48:30,401 I 371 371] local_object_manager.cc:170: Spilled 4139 MiB, 3 objects, write throughput 906 MiB/s
    [2021-02-12 17:48:30,402 E 371 371] logging.cc:435: *** Aborted at 1613152110 (unix time) try "date -d @1613152110" if you are using GNU date ***
    [2021-02-12 17:48:30,403 E 371 371] logging.cc:435: PC: @                0x0 (unknown)
    [2021-02-12 17:48:30,403 E 371 371] logging.cc:435: *** SIGSEGV (@0x8) received by PID 371 (TID 0x7fccaa19d800) from PID 8; stack trace: ***
    [2021-02-12 17:48:30,403 E 371 371] logging.cc:435:     @     0x55e8c6e8643f google::(anonymous namespace)::FailureSignalHandler()
    [2021-02-12 17:48:30,403 E 371 371] logging.cc:435:     @     0x7fcca9d74980 (unknown)
    [2021-02-12 17:48:30,404 E 371 371] logging.cc:435:     @     0x55e8c71e9e27 google::protobuf::RepeatedPtrField<>::Get()
    [2021-02-12 17:48:30,405 E 371 371] logging.cc:435:     @     0x55e8c6ab38f5 ray::raylet::LocalObjectManager::AddSpilledUrls()
    [2021-02-12 17:48:30,405 E 371 371] logging.cc:435:     @     0x55e8c6ab50ee _ZNSt17_Function_handlerIFvRKN3ray6StatusERKNS0_3rpc17SpillObjectsReplyEEZZNS0_6raylet18LocalObjectManager20SpillObjectsInternalERKSt6vectorINS0_8ObjectIDES
    aISC_EESt8functionIFvS3_EEENKUlSt10shared_ptrINS9_15WorkerInterfaceEEE_clESM_EUlS3_S7_E_E9_M_invokeERKSt9_Any_dataS3_S7_
    [2021-02-12 17:48:30,405 E 371 371] logging.cc:435:     @     0x55e8c6abd1f2 ray::rpc::ClientCallImpl<>::OnReplyReceived()
    [2021-02-12 17:48:30,406 E 371 371] logging.cc:435:     @     0x55e8c6acf072 _ZN5boost4asio6detail18completion_handlerIZN3ray3rpc17ClientCallManager29PollEventsFromCompletionQueueEiEUlvE_E11do_completeEPvPNS1_19scheduler_operationERK
    NS_6system10error_codeEm
    [2021-02-12 17:48:30,408 E 371 371] logging.cc:435:     @     0x55e8c71fc381 boost::asio::detail::scheduler::do_run_one()
    [2021-02-12 17:48:30,409 E 371 371] logging.cc:435:     @     0x55e8c71fda29 boost::asio::detail::scheduler::run()
    [2021-02-12 17:48:30,410 E 371 371] logging.cc:435:     @     0x55e8c71fff17 boost::asio::io_context::run()
    [2021-02-12 17:48:30,410 E 371 371] logging.cc:435:     @     0x55e8c6a2a2a2 main
    [2021-02-12 17:48:30,411 E 371 371] logging.cc:435:     @     0x7fcca8e4bbf7 __libc_start_main
    [2021-02-12 17:48:30,412 E 371 371] logging.cc:435:     @     0x55e8c6a3f395 (unknown)

And looking at the ray spilled objects directory:

    root@ip-172-31-79-202:/tmp/ray/session_latest# ls -l ray_spilled_objects/
    total 4238568
    -rw-r--r-- 1 root root          0 Feb 12 17:48 0fb939667ee64409419d38867099fbd841ba16210100000001000000-multi-8
    -rw-r--r-- 1 root root 1446757125 Feb 12 17:48 11ac9524461283ce753565f917242c119e81ccf70100000001000000-multi-1
    -rw-r--r-- 1 root root 1446757125 Feb 12 17:48 59f3350af995668a764f8475f05bf001226e22c30100000001000000-multi-1
    -rw-r--r-- 1 root root          0 Feb 12 17:48 59f76feddb5a7dbcd3ec2e91753e434062462c210100000001000000-multi-5
    -rw-r--r-- 1 root root 1446757189 Feb 12 17:48 609d7f556b6757ad480a853c2c4c6f276de42d010100000001000000-multi-1

This issue was originally surfaced in https://discuss.ray.io/t/error-when-spilling-objects-buf-len-len-buf-nonetype-has-no-len/865

**Comment by rkooo567** [comment]
Is there any way to provide a reproduction script that we can run without external dependencies? If possible, that'll be the easiest to solve the problem in a short time.

**Comment by rkooo567** [comment]
Btw, the segfault is due to this; https://github.com/ray-project/ray/issues/14081

Unknown why we have None object for buffer length, but it definitely looks like a bug.

**Comment by stephanie-wang** [comment]
@rkooo567, could the `None` value mean that the object wasn't available in the object store?

**Comment by rkooo567** [comment]
@stephanie-wang I am not quite sure... But it should be guaranteed that the object exists in the store when get is called? Do you think it is some sort of race condition?

**Comment by rkooo567** [comment]
@mr-mcox Just to remind you one more time, we'd like to fix this asap, but it is difficult to do that unless we have a way to reproduce the issue (the only possible way, in this case, is to find this reproduction on our end coincidentally, but that is really difficult and uncommon). So, it will be really great if you can give us a script that can consistently reproduce this issue! https://github.com/ray-project/ray/issues/14079#issuecomment-778503445

**Comment by mr-mcox** [comment]
Understood @rkooo567 . Any advice on how to pare down to a reproducible script? I'm running a large model across multiple nodes on GPUs when this happens - if I create a script that can reproduce the failure under those conditions, does that suffice, or do you need something that can be run locally?

**Comment by rkooo567** [comment]
As long as you can provide a script that I can run without 
1. GPUs
2. external dependencies. Meaning if it requires data, it'll be great if they are mocked out.
3. Also, if you can provide a cluster.yaml, that's also great.

It is okay to take long time to reproduce. Just by the fact that we know how to reproduce the issue, it'll be a tone of help. (Once we reach to that point, I can figure out how to narrow down the issue and make a smaller scoped scripts).

**Comment by mr-mcox** [comment]
That's helpful advice - thank you! I'll work on creating that reproducible script over the next few days. It will take some work because I want to incrementally verify that I'm simplifying while still reproducing the original issue.

**Comment by mr-mcox** [comment]
After spending a few hours struggling to get my minimal script to fail when it reproduced the conditions of my original code, I went back to retry my original code and am no longer experiencing this issue. In the conditions where Ray was throwing errors when spilling objects, it is now acting as expected. I suspect that some change in recent nightlies (perhaps unrelated?) resolved my issue. I will close this issue!

**Comment by rkooo567** [comment]
Oh that’s awesome. We keep adding fixes now, so yeah it is possible some other fix happened to resolve ur problem. 

I remember you are using this to avoid memory issue while using Tune right? I’d love to hear ur use case of object spilling and experience! Is it working well now without a bug then?

**Comment by mr-mcox** [comment]
@rkooo567 You are correct that I was trying to avoid a memory issue while using Tune. My use case is that I have a model that has about 4.5GB worth of parameters and for some reason, whenever a trial is paused, the trial is saved in the object store, and is never removed. I had a head node with about 60GB of memory that would run out of memory after about 12 trials were paused. This seems to avoid that issue. Happy to recap and discuss further in a new https://discuss.ray.io thread if you'd like!

**Comment by rkooo567** [comment]
Yeah it'll be great to write how this worked in the discuss.ray.io!! I will appreciate that :)!

Btw, @richardliaw is this an expected behavior? (that the trial is saved to the plasma store and never removed)
