### ISSUE TITLE
[rllib] Occasional Thread Error from RLlib

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#1409]
### System information
- Linux Ubuntu 16.04
- Ray installed via Binary
- Python 3.6.3
- on branch `https://github.com/richardliaw/ray/tree/shard_autoscale`
- `git checkout 6b993974265 && cd [rllib_dir] && python train.py -f shard/pong-shard.yaml`

### Describe the problem
I get this error occasionally when running a custom agent.

### Source code / logs
```
Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/worker.py", line 1625, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/home/ubuntu/ray/python/ray/tune/__init__.py", line 6, in <module>
    from ray.tune.tune import run_experiments
  File "/home/ubuntu/ray/python/ray/tune/tune.py", line 88, in <module>
    from ray.rllib.shard.shardedagent import ShardedAgent
  File "/home/ubuntu/ray/python/ray/rllib/__init__.py", line 18, in <module>
    _register_all()
  File "/home/ubuntu/ray/python/ray/rllib/__init__.py", line 13, in _register_all
    register_trainable(key, get_agent_class(key))
  File "/home/ubuntu/ray/python/ray/rllib/agent.py", line 368, in get_agent_class
    from ray.rllib import es
  File "/home/ubuntu/ray/python/ray/rllib/es/__init__.py", line 1, in <module>
    from ray.rllib.es.es import (ESAgent, DEFAULT_CONFIG)
  File "/home/ubuntu/ray/python/ray/rllib/es/es.py", line 43, in <module>
    @ray.remote
  File "/home/ubuntu/ray/python/ray/worker.py", line 2579, in remote
    max_calls, checkpoint_interval)(args[0])
  File "/home/ubuntu/ray/python/ray/worker.py", line 2482, in remote_decorator
    function_properties)
  File "/home/ubuntu/ray/python/ray/worker.py", line 2541, in remote_function_decorator
    func_invoker, function_properties)
  File "/home/ubuntu/ray/python/ray/worker.py", line 2380, in export_remote_function
    check_main_thread()
  File "/home/ubuntu/ray/python/ray/worker.py", line 959, in check_main_thread
    .format(threading.current_thread().getName()))
Exception: The Ray methods are not thread safe and must be called from the main thread. This method was called from thread Thread-4.

```

**Comment by ericl** [comment]
I've also seen this before at high scales, it seems a module import may happen off the main thread. The workaround was just to remove that check. Cc @pcmoritz if you know if this is safe in the general case

**Comment by robertnishihara** [comment]
I've been looking into this more, and I think there may be a couple of ways that this issue can arise.

1. If there are two jobs sharing the same cluster, an export from one job gets imported by the driver for the second job and causes this exception in the driver for the second job. The solution here is to have separate export queues for different jobs.

2. If a worker defines a custom serializer (or some other export), which somehow closes over a module that defines a remote function, such that when the custom serializer is unpickled by the driver, the driver imports the module and attempts to export the remote function. This is probably the issue that's happening above. I'll come up with some simpler ways of reproducing this problem and propose a fix.

**Comment by robertnishihara** [comment]
Another approach would be to just get rid of the import thread entirely (see #951). I may give this a try.

**Comment by ericl** [comment]
Flow lab is seeing this in their multiagent runs:
```
Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/worker.py", line 1624, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/home/ubuntu/ray/python/ray/rllib/__init__.py", line 20, in <module>
    _register_all()
  File "/home/ubuntu/ray/python/ray/rllib/__init__.py", line 15, in _register_all
    register_trainable(key, get_agent_class(key))
  File "/home/ubuntu/ray/python/ray/rllib/agent.py", line 219, in get_agent_class
    from ray.rllib import es
  File "/home/ubuntu/ray/python/ray/rllib/es/__init__.py", line 1, in <module>
    from ray.rllib.es.es import (ESAgent, DEFAULT_CONFIG)
  File "/home/ubuntu/ray/python/ray/rllib/es/es.py", line 45, in <module>
    @ray.remote
  File "/home/ubuntu/ray/python/ray/worker.py", line 2576, in remote
    max_calls, checkpoint_interval)(args[0])
  File "/home/ubuntu/ray/python/ray/worker.py", line 2479, in remote_decorator
    function_properties)
  File "/home/ubuntu/ray/python/ray/worker.py", line 2538, in remote_function_decorator
    func_invoker, function_properties)
  File "/home/ubuntu/ray/python/ray/worker.py", line 2377, in export_remote_function
    check_main_thread()
  File "/home/ubuntu/ray/python/ray/worker.py", line 955, in check_main_thread
    .format(threading.current_thread().getName()))
Exception: The Ray methods are not thread safe and must be called from the main thread. This method was called from thread Thread-4.
```

Should we just merge the workaround? This actually seems a pretty common issue.

**Comment by robertnishihara** [comment]
Oh, was this fixed by #1441? That's good, though there are likely some remaining ways this error could occur.

**Comment by alexbao** [comment]
Encounter the error with actor today,  the call is invoked from a thread instead of the main thread. Do we want to remove this check?

**Comment by robertnishihara** [comment]
We do want to remove the check, but it will need to be accompanied by making the Ray API thread safe, e.g., something like #2034, however that implementation is buggy and I haven't had a chance to fix it up yet.
