### ISSUE TITLE
port address conflict causing head node enters into an broken state and not usable

### ISSUE THREAD

**Issue by yuduber** [ray-project/ray#14098]
ray core
### What is the problem?
`ray start --head ...` with a group of specified ports will run and appeared to be successful.  But then `ray status` will fail with "ConnectionError: Could not find any running Ray instance. Please specify the one to connect to by setting address.".  Logs in /tmp/ray/session_latest/logs/raylet.err shows "Address already in use" error like below:

```
[root@/tmp/ray/session_latest/logs #]cat raylet.err 
E0215 01:53:44.582325479    2825 server_chttp2.cc:40]        {"created":"@1613354024.582257191","description":"No address added out of total 1 resolved","file":"external/com_github_grpc_grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":394,"referenced_errors":[{"created":"@1613354024.582255389","description":"Failed to add any wildcard listeners","file":"external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_server_posix.cc","file_line":340,"referenced_errors":[{"created":"@1613354024.582244433","description":"Unable to configure socket","fd":32,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":207,"referenced_errors":[{"created":"@1613354024.582234203","description":"Address already in use","errno":98,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":181,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1613354024.582254497","description":"Unable to configure socket","fd":32,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":207,"referenced_errors":[{"created":"@1613354024.582251910","description":"Address already in use","errno":98,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":181,"os_error":"Address already in use","syscall":"bind"}]}]}]}
[2021-02-15 01:53:44,582 E 2825 2825] logging.cc:435: *** Aborted at 1613354024 (unix time) try "date -d @1613354024" if you are using GNU date ***
[2021-02-15 01:53:44,582 E 2825 2825] logging.cc:435: PC: @                0x0 (unknown)
[2021-02-15 01:53:44,582 E 2825 2825] logging.cc:435: *** SIGSEGV (@0x58) received by PID 2825 (TID 0x7ffa56db57c0) from PID 88; stack trace: ***
[2021-02-15 01:53:44,582 E 2825 2825] logging.cc:435:     @     0x555562d3743f google::(anonymous
... 
```
 
*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray2.0.0.dev0 has this issue.  Ray1.0.0 appears to be ok.

### Reproduction (REQUIRED)
reproducible either on Debian GNU/Linux 9 (stretch) or MacOS Catalina 10.15.7 (19H512) under python 3.6.9
command that will fail:
`ray start --head --dashboard-port=31003 --port=31001 --object-manager-port=31002 --min-worker-port=31005 --max-worker-port=31011 --num-cpus=5 --dashboard-host="0.0.0.0"`

run `ray status` after this will show error.  ray head node enters into an unhealthy / not usable state.
run `ray stop` to clear any unhealthy ray process, then try again with a good command that only set --object-manager-port to a value that's far way from 3100x, the command will succeed and `ray status` repot correct status:
command that will succeed:
`ray start --head --dashboard-port=31003 --port=31001 --object-manager-port=31099 --min-worker-port=31005 --max-worker-port=31011 --num-cpus=5 --dashboard-host="0.0.0.0"`

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
Can you also set `--node-manager-port` and see if it still happens? Also, how often does it happen? (Is it consistent)?

**Comment by yuduber** [comment]
very consistent and very reproducible.  I will try with --node-manager-port when I had time.

**Comment by rkooo567** [comment]
Also, before you run the first ray start, can you make sure both object-manager-port and --node-manager-port is free? You can try something like `lsof -i :31002`

**Comment by yuduber** [comment]
I have verified with lsof -i :ports and the ports are all available.

```
yud@yud-C02DL7XHMD6R ml-code % lsof -i :31000                                                                                                                                                          
yud@yud-C02DL7XHMD6R ml-code % lsof -i :31001
yud@yud-C02DL7XHMD6R ml-code % lsof -i :31002
yud@yud-C02DL7XHMD6R ml-code % lsof -i :31003
yud@yud-C02DL7XHMD6R ml-code % lsof -i :31004
yud@yud-C02DL7XHMD6R ml-code % lsof -i :31005
yud@yud-C02DL7XHMD6R ml-code % lsof -i :31006
yud@yud-C02DL7XHMD6R ml-code % lsof -i :31007
yud@yud-C02DL7XHMD6R ml-code % lsof -i :31008
yud@yud-C02DL7XHMD6R ml-code % lsof -i :31009
yud@yud-C02DL7XHMD6R ml-code % lsof -i :31010
yud@yud-C02DL7XHMD6R ml-code % lsof -i :31011
yud@yud-C02DL7XHMD6R ml-code % lsof -i :10001
yud@yud-C02DL7XHMD6R ml-code % 
yud@yud-C02DL7XHMD6R ml-code % ray stop
Did not find any active Ray processes.
yud@yud-C02DL7XHMD6R ml-code % ray start --head --dashboard-port=31003 --port=31001 --object-manager-port=31002 --min-worker-port=31005 --max-worker-port=31011 --num-cpus=5 --dashboard-host="0.0.0.0"
Local node IP: 192.168.4.60
2021-02-16 11:38:12,110 INFO services.py:1195 -- View the Ray dashboard at http://192.168.4.60:31003

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='192.168.4.60:31001' --redis-password='5241590000000000'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='5241590000000000')
  
  If connection fails, check your firewall settings and network configuration.
  
  To terminate the Ray runtime, run
    ray stop
yud@yud-C02DL7XHMD6R ml-code % ray status
Traceback (most recent call last):
  File "/Users/yud/repo/ml-code/env/py369/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/ray/scripts/scripts.py", line 1526, in main
    return cli()
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/ray/scripts/scripts.py", line 1409, in status
    address = services.get_ray_address_to_use_or_die()
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/ray/_private/services.py", line 221, in get_ray_address_to_use_or_die
    return find_redis_address_or_die()
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/ray/_private/services.py", line 234, in find_redis_address_or_die
    "Could not find any running Ray instance. "
ConnectionError: Could not find any running Ray instance. Please specify the one to connect to by setting `address`.
yud@yud-C02DL7XHMD6R ml-code % 
yud@yud-C02DL7XHMD6R ml-code % lsof -i :10001                                                                                                                                                          
COMMAND     PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
python3.6 39745  yud    4u  IPv6 0x1c77fce7554a3fa1      0t0  TCP *:scp-config (LISTEN)
yud@yud-C02DL7XHMD6R ml-code % ray stop   
Stopped only 8 out of 9 Ray processes. Set `-v` to see more details.
Try running the command again, or use `--force`.
yud@yud-C02DL7XHMD6R ml-code % ray stop
Did not find any active Ray processes.
yud@yud-C02DL7XHMD6R ml-code % lsof -i :10001
yud@yud-C02DL7XHMD6R ml-code % ray start --head --dashboard-port=31003 --port=31001 --object-manager-port=41002 --min-worker-port=31005 --max-worker-port=31011 --num-cpus=5 --dashboard-host="0.0.0.0"
Local node IP: 192.168.4.60
2021-02-16 11:40:22,146 INFO services.py:1195 -- View the Ray dashboard at http://192.168.4.60:31003

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='192.168.4.60:31001' --redis-password='5241590000000000'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='5241590000000000')
  
  If connection fails, check your firewall settings and network configuration.
  
  To terminate the Ray runtime, run
    ray stop
yud@yud-C02DL7XHMD6R ml-code % ray satus
Usage: ray [OPTIONS] COMMAND [ARGS]...
Try 'ray --help' for help.

Error: No such command 'satus'.
yud@yud-C02DL7XHMD6R ml-code % ray status
======== Cluster status: 2021-02-16 11:40:37.948714 ========
Node status
------------------------------------------------------------
 1 node(s) with resources: {'node:192.168.4.60': 1.0, 'CPU': 5.0, 'object_store_memory': 68.0, 'memory': 197.0}

Resources
------------------------------------------------------------
Usage:
 0.0/5.0 CPU
 0.00/9.619 GiB memory
 0.00/3.320 GiB object_store_memory

Demands:
 (no resource demands)
yud@yud-C02DL7XHMD6R ml-code % lsof -i :10001                                                                                                                                                          
COMMAND     PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
python3.6 39931  yud    4u  IPv6 0x1c77fce7327b4c41      0t0  TCP *:scp-config (LISTEN)
yud@yud-C02DL7XHMD6R ml-code % lsof -i :31001                                                                                                                                                          
COMMAND     PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
redis-ser 39924  yud    6u  IPv6 0x1c77fce742719fa1      0t0  TCP *:31001 (LISTEN)
redis-ser 39924  yud    7u  IPv4 0x1c77fce760fb8791      0t0  TCP *:31001 (LISTEN)
redis-ser 39924  yud    8u  IPv4 0x1c77fce760fb73d1      0t0  TCP 192.168.4.60:31001->192.168.4.60:52885 (ESTABLISHED)
redis-ser 39924  yud    9u  IPv4 0x1c77fce75fcbc3d1      0t0  TCP 192.168.4.60:31001->192.168.4.60:52886 (ESTABLISHED)
redis-ser 39924  yud   10u  IPv4 0x1c77fce75fcbcdb1      0t0  TCP 192.168.4.60:31001->192.168.4.60:52887 (ESTABLISHED)
redis-ser 39924  yud   11u  IPv4 0x1c77fce76a6f0b51      0t0  TCP 192.168.4.60:31001->192.168.4.60:52895 (ESTABLISHED)
redis-ser 39924  yud   12u  IPv4 0x1c77fce761c90791      0t0  TCP 192.168.4.60:31001->192.168.4.60:52896 (ESTABLISHED)
redis-ser 39924  yud   13u  IPv4 0x1c77fce76a70a3d1      0t0  TCP 192.168.4.60:31001->192.168.4.60:52897 (ESTABLISHED)
redis-ser 39924  yud   14u  IPv4 0x1c77fce761eb2db1      0t0  TCP 192.168.4.60:31001->192.168.4.60:52906 (ESTABLISHED)
redis-ser 39924  yud   15u  IPv4 0x1c77fce741bb6171      0t0  TCP 192.168.4.60:31001->192.168.4.60:52907 (ESTABLISHED)
redis-ser 39924  yud   16u  IPv4 0x1c77fce77226c531      0t0  TCP 192.168.4.60:31001->192.168.4.60:52908 (ESTABLISHED)
redis-ser 39924  yud   17u  IPv4 0x1c77fce741bb39f1      0t0  TCP 192.168.4.60:31001->192.168.4.60:52913 (ESTABLISHED)
redis-ser 39924  yud   18u  IPv4 0x1c77fce76a6ef791      0t0  TCP 192.168.4.60:31001->192.168.4.60:52914 (ESTABLISHED)
redis-ser 39924  yud   19u  IPv4 0x1c77fce761c91b51      0t0  TCP 192.168.4.60:31001->192.168.4.60:52915 (ESTABLISHED)
redis-ser 39924  yud   20u  IPv4 0x1c77fce76a70df11      0t0  TCP 192.168.4.60:31001->192.168.4.60:52920 (ESTABLISHED)
redis-ser 39924  yud   21u  IPv4 0x1c77fce74178c171      0t0  TCP 192.168.4.60:31001->192.168.4.60:52921 (ESTABLISHED)
redis-ser 39924  yud   22u  IPv4 0x1c77fce77226a791      0t0  TCP 192.168.4.60:31001->192.168.4.60:52924 (ESTABLISHED)
redis-ser 39924  yud   23u  IPv4 0x1c77fce760fb69f1      0t0  TCP 192.168.4.60:31001->192.168.4.60:52926 (ESTABLISHED)
redis-ser 39924  yud   24u  IPv4 0x1c77fce7646b69f1      0t0  TCP 192.168.4.60:31001->192.168.4.60:52929 (ESTABLISHED)
redis-ser 39924  yud   25u  IPv4 0x1c77fce74178cb51      0t0  TCP 192.168.4.60:31001->192.168.4.60:52930 (ESTABLISHED)
redis-ser 39924  yud   26u  IPv4 0x1c77fce772033f11      0t0  TCP 192.168.4.60:31001->192.168.4.60:52931 (ESTABLISHED)
redis-ser 39924  yud   27u  IPv4 0x1c77fce741bb5791      0t0  TCP 192.168.4.60:31001->192.168.4.60:52932 (ESTABLISHED)
redis-ser 39924  yud   28u  IPv4 0x1c77fce76a6ed9f1      0t0  TCP 192.168.4.60:31001->192.168.4.60:52937 (ESTABLISHED)
redis-ser 39924  yud   29u  IPv4 0x1c77fce76a6eedb1      0t0  TCP 192.168.4.60:31001->192.168.4.60:52941 (ESTABLISHED)
redis-ser 39924  yud   30u  IPv4 0x1c77fce771fac531      0t0  TCP 192.168.4.60:31001->192.168.4.60:52944 (ESTABLISHED)
gcs_serve 39928  yud   12u  IPv4 0x1c77fce760fb7db1      0t0  TCP 192.168.4.60:52885->192.168.4.60:31001 (ESTABLISHED)
gcs_serve 39928  yud   13u  IPv4 0x1c77fce74178df11      0t0  TCP 192.168.4.60:52886->192.168.4.60:31001 (ESTABLISHED)
gcs_serve 39928  yud   14u  IPv4 0x1c77fce741bb7f11      0t0  TCP 192.168.4.60:52887->192.168.4.60:31001 (ESTABLISHED)
gcs_serve 39928  yud   20u  IPv4 0x1c77fce74178df11      0t0  TCP 192.168.4.60:52886->192.168.4.60:31001 (ESTABLISHED)
gcs_serve 39928  yud   21u  IPv4 0x1c77fce741bb7f11      0t0  TCP 192.168.4.60:52887->192.168.4.60:31001 (ESTABLISHED)
python3.6 39929  yud    5u  IPv4 0x1c77fce761eb4171      0t0  TCP 192.168.4.60:52906->192.168.4.60:31001 (ESTABLISHED)
python3.6 39929  yud    6u  IPv4 0x1c77fce741bb4db1      0t0  TCP 192.168.4.60:52907->192.168.4.60:31001 (ESTABLISHED)
python3.6 39929  yud    7u  IPv4 0x1c77fce77225d531      0t0  TCP 192.168.4.60:52908->192.168.4.60:31001 (ESTABLISHED)
python3.6 39929  yud   16u  IPv4 0x1c77fce741bb4db1      0t0  TCP 192.168.4.60:52907->192.168.4.60:31001 (ESTABLISHED)
python3.6 39929  yud   17u  IPv4 0x1c77fce77225d531      0t0  TCP 192.168.4.60:52908->192.168.4.60:31001 (ESTABLISHED)
python3.6 39929  yud   20u  IPv4 0x1c77fce74178d531      0t0  TCP 192.168.4.60:52913->192.168.4.60:31001 (ESTABLISHED)
python3.6 39929  yud   21u  IPv4 0x1c77fce761659db1      0t0  TCP 192.168.4.60:52914->192.168.4.60:31001 (ESTABLISHED)
python3.6 39929  yud   22u  IPv4 0x1c77fce761c92531      0t0  TCP 192.168.4.60:52915->192.168.4.60:31001 (ESTABLISHED)
python3.6 39929  yud   31u  IPv4 0x1c77fce761659db1      0t0  TCP 192.168.4.60:52914->192.168.4.60:31001 (ESTABLISHED)
python3.6 39929  yud   32u  IPv4 0x1c77fce761c92531      0t0  TCP 192.168.4.60:52915->192.168.4.60:31001 (ESTABLISHED)
python3.6 39929  yud   35u  IPv4 0x1c77fce762895791      0t0  TCP 192.168.4.60:52921->192.168.4.60:31001 (ESTABLISHED)
python3.6 39929  yud   37u  IPv4 0x1c77fce742762b51      0t0  TCP 192.168.4.60:52924->192.168.4.60:31001 (ESTABLISHED)
python3.6 39938  yud   14u  IPv4 0x1c77fce7724cbdb1      0t0  TCP 192.168.4.60:52929->192.168.4.60:31001 (ESTABLISHED)
python3.6 39938  yud   15u  IPv4 0x1c77fce7722c83d1      0t0  TCP 192.168.4.60:52930->192.168.4.60:31001 (ESTABLISHED)
python3.6 39938  yud   16u  IPv4 0x1c77fce75fcbe171      0t0  TCP 192.168.4.60:52931->192.168.4.60:31001 (ESTABLISHED)
python3.6 39938  yud   17u  IPv4 0x1c77fce772030db1      0t0  TCP 192.168.4.60:52932->192.168.4.60:31001 (ESTABLISHED)
python3.6 39938  yud   26u  IPv4 0x1c77fce75fcbe171      0t0  TCP 192.168.4.60:52931->192.168.4.60:31001 (ESTABLISHED)
python3.6 39938  yud   27u  IPv4 0x1c77fce772030db1      0t0  TCP 192.168.4.60:52932->192.168.4.60:31001 (ESTABLISHED)
python3.6 39938  yud   31u  IPv4 0x1c77fce77225b791      0t0  TCP 192.168.4.60:52937->192.168.4.60:31001 (ESTABLISHED)
python3.6 39938  yud   33u  IPv4 0x1c77fce76a6f0171      0t0  TCP 192.168.4.60:52941->192.168.4.60:31001 (ESTABLISHED)
raylet    39940  yud    3u  IPv4 0x1c77fce76165cf11      0t0  TCP 192.168.4.60:52895->192.168.4.60:31001 (ESTABLISHED)
raylet    39940  yud    4u  IPv4 0x1c77fce761c91171      0t0  TCP 192.168.4.60:52896->192.168.4.60:31001 (ESTABLISHED)
raylet    39940  yud    5u  IPv4 0x1c77fce76a7099f1      0t0  TCP 192.168.4.60:52897->192.168.4.60:31001 (ESTABLISHED)
raylet    39940  yud   14u  IPv4 0x1c77fce761c91171      0t0  TCP 192.168.4.60:52896->192.168.4.60:31001 (ESTABLISHED)
raylet    39940  yud   15u  IPv4 0x1c77fce76a7099f1      0t0  TCP 192.168.4.60:52897->192.168.4.60:31001 (ESTABLISHED)
python3.6 39941  yud    6u  IPv4 0x1c77fce762c8d791      0t0  TCP 192.168.4.60:52920->192.168.4.60:31001 (ESTABLISHED)
python3.6 39945  yud    3u  IPv4 0x1c77fce76165cf11      0t0  TCP 192.168.4.60:52895->192.168.4.60:31001 (ESTABLISHED)
python3.6 39945  yud    4u  IPv4 0x1c77fce761c91171      0t0  TCP 192.168.4.60:52896->192.168.4.60:31001 (ESTABLISHED)
python3.6 39945  yud    5u  IPv4 0x1c77fce76a7099f1      0t0  TCP 192.168.4.60:52897->192.168.4.60:31001 (ESTABLISHED)
python3.6 39945  yud   14u  IPv4 0x1c77fce761c91171      0t0  TCP 192.168.4.60:52896->192.168.4.60:31001 (ESTABLISHED)
python3.6 39945  yud   15u  IPv4 0x1c77fce76a7099f1      0t0  TCP 192.168.4.60:52897->192.168.4.60:31001 (ESTABLISHED)
python3.6 39945  yud   29u  IPv4 0x1c77fce761eb23d1      0t0  TCP 192.168.4.60:52926->192.168.4.60:31001 (ESTABLISHED)
python3.6 39945  yud   49u  IPv4 0x1c77fce771fab171      0t0  TCP 192.168.4.60:52944->192.168.4.60:31001 (ESTABLISHED)
yud@yud-C02DL7XHMD6R ml-code % 
```

**Comment by yuduber** [comment]
> Can you also set `--node-manager-port` and see if it still happens? Also, how often does it happen? (Is it consistent)?

tried specify `--node-manager-port` and behave the same, see below output from my laptop:

```
yud@yud-C02DL7XHMD6R ml-code % ray stop
Stopped only 13 out of 14 Ray processes. Set `-v` to see more details.
Try running the command again, or use `--force`.
yud@yud-C02DL7XHMD6R ml-code % ray stop
Stopped all 1 Ray processes.
yud@yud-C02DL7XHMD6R ml-code % ray stop
Did not find any active Ray processes.
yud@yud-C02DL7XHMD6R ml-code % ray start --head --dashboard-port=31003 --port=31001 --object-manager-port=41002 --node-manager-port=31012 --min-worker-port=31005 --max-worker-port=31011 --num-cpus=5 --dashboard-host="0.0.0.0"
Local node IP: 192.168.4.60
2021-02-16 11:47:21,016 INFO services.py:1195 -- View the Ray dashboard at http://192.168.4.60:31003

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='192.168.4.60:31001' --redis-password='5241590000000000'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='5241590000000000')
  
  If connection fails, check your firewall settings and network configuration.
  
  To terminate the Ray runtime, run
    ray stop
yud@yud-C02DL7XHMD6R ml-code % ray status
======== Cluster status: 2021-02-16 11:47:26.308436 ========
Node status
------------------------------------------------------------
 1 node(s) with resources: {'object_store_memory': 68.0, 'node:192.168.4.60': 1.0, 'memory': 199.0, 'CPU': 5.0}

Resources
------------------------------------------------------------
Usage:
 0.0/5.0 CPU
 0.00/9.717 GiB memory
 0.00/3.320 GiB object_store_memory

Demands:
 (no resource demands)
yud@yud-C02DL7XHMD6R ml-code % ray stop                                                                                                                                                                                          
Stopped only 12 out of 14 Ray processes. Set `-v` to see more details.
Try running the command again, or use `--force`.
yud@yud-C02DL7XHMD6R ml-code % ray stop
Did not find any active Ray processes.
yud@yud-C02DL7XHMD6R ml-code % ray start --head --dashboard-port=31003 --port=31001 --object-manager-port=31002 --node-manager-port=31012 --min-worker-port=31005 --max-worker-port=31011 --num-cpus=5 --dashboard-host="0.0.0.0"
Local node IP: 192.168.4.60
2021-02-16 11:47:50,206 INFO services.py:1195 -- View the Ray dashboard at http://192.168.4.60:31003

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='192.168.4.60:31001' --redis-password='5241590000000000'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='5241590000000000')
  
  If connection fails, check your firewall settings and network configuration.
  
  To terminate the Ray runtime, run
    ray stop
yud@yud-C02DL7XHMD6R ml-code % ray status
Traceback (most recent call last):
  File "/Users/yud/repo/ml-code/env/py369/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/ray/scripts/scripts.py", line 1526, in main
    return cli()
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/ray/scripts/scripts.py", line 1409, in status
    address = services.get_ray_address_to_use_or_die()
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/ray/_private/services.py", line 221, in get_ray_address_to_use_or_die
    return find_redis_address_or_die()
  File "/Users/yud/repo/ml-code/env/py369/lib/python3.6/site-packages/ray/_private/services.py", line 234, in find_redis_address_or_die
    "Could not find any running Ray instance. "
ConnectionError: Could not find any running Ray instance. Please specify the one to connect to by setting `address`.
yud@yud-C02DL7XHMD6R ml-code % 
```

**Comment by yuduber** [comment]
I found the issue here.

In /ray/python/ray/_private/services.py start_redis(), after the primary redis started at port defined by command arg `--port=31001`, the start_redis() goes on to start the shards at incremented values of port, which means:
    if we have one shard (by default), the new redis shard will be using 31002;
    if we have two shards, the new redis shards will be using 31002, 31003;
    and so on...
but since our command don't know we should avoid these ports, in my case I tried to run object_manager on 31002, which conflicts with the redis shard server, then the object manager could not start correctly due to port conflict and cause the ray cluster fail to start properly.

the logic is shown below from original services.py:
```
...
    # Attempt to start the other Redis shards port range right after the
    # primary Redis shard port.
    last_shard_port = port
    for i in range(num_redis_shards):
       ...
        redis_shard_port = redis_shard_ports[i]
        # If no shard port is given, try to start this shard's Redis instance
        # on the port right after the last shard's port.
        if redis_shard_port is None:
            redis_shard_port = last_shard_port + 1
         ...
        last_shard_port = redis_shard_port
```

need to change logic here to avoid taking ports that potentially will conflict with other ports specified by the command.  I can help with the fixing.

**Comment by rkooo567** [comment]
Btw, what ports need to be specified for you guys? We might have other components that choose a random port (e.g., --gcs-server-port).

**Comment by rkooo567** [comment]
Also, @clarkzinzow made a quick fix to resolve this issue. I will merge this by tonight.

**Comment by rkooo567** [comment]
So, to avoid the issue, what you can immediately do is to assign higher port for `port` arguments than `object_manager_port`, `node_manager_port`, and `gcs_server_port`, and `min&max_worker_port`. 

The quick fix just randomizes the Redis shard ports, but I wonder if this is fundamentally fixes you guys' issues.

**Comment by yuduber** [comment]
In a cloud production environment, just assign higher port for `port` still might not work.  Because even tho it will be higher than all these `object_manager_port`, `node_manager_port`, and `gcs_server_port`, and `min&max_worker_port` in your current ray node.  It might still be conflicting with other docker container that happened to be running on the same host.  In a could environment, on one single physical machine, we will have multiple containers running in it.  Each container is independent os, libraries, applications, but they may have to share from a single set of ports.  Those other containers are a completely different run time environment, and we have no control what port they used.

So again, we have to have a fix that's 100% honor ports specified in the ray start ... command and 100% avoid conflict for the ports that's not specified in the command.

**Comment by rkooo567** [comment]
If you guys specify all the ports number manually, would that solve the issue? For example, 
```
# head node
ray start --head --port=30001 --redis-shard-ports=30002 --node-manager-port=30003 --object-manager-port=30004 --dashboard-port=30005 --gcs-server-port=30007 --min-worker-port=30008 --max-worker-port=30013 
```

If you use any randomized solution, that will always have the risk of conflicting with other ports right? I don't think we will have other components that could have port assignments other than these, but I can double check. 

The port specification is here; https://docs.ray.io/en/latest/configure.html#head-node

**Comment by rkooo567** [comment]
Or is it allowed to use randomized ports as long as it won't conflict with other ones?

**Comment by yuduber** [comment]
yesh, that's what I proposed in the RC analysis.  When you need to pick port for any service, first look at the `ray start ...` command, if that was specified, use it.  If not, pick a random port that is not used at the moment.  Continue this iteration util all ports are assigned.

**Comment by richardliaw** [comment]
Hmm let's keep this open so that we actually fix the underlying issue

**Comment by rkooo567** [comment]
hey @yuduber after the quick fix, do you still see the same issue?

**Comment by yuduber** [comment]
sorry being busy yesterday.  Where is the fix?  Can I take a look of the fix?

**Comment by yuduber** [comment]
I see the fix now, which is just use random.randint(10000, 65535) for the new port number for the shard.  This still leave certain probability of picking a used or already allocated port and create conflict later on.  Can't you just keep track of the allocated ports, and when you need to pick a new port, you find a random one and check to make sure it's not in the allocated ports and not used at the moment?

**Comment by rkooo567** [comment]
@yuduber Yeah that's the fundamental fix we've been thinking about too (blacklisting user-selected ports), but we are a little bit overloaded this and next week, so we merged the quick fix first! (to unblock you quickly). If this fix is very urgent, I can spend some time maybe this weekends to push the fix asap.

**Comment by yuduber** [comment]
I see.  Thanks for letting me know.  The fix is kinda critical to unblock some of our work here at uber.  If it will be available sometime next week, that will be greatly appreciated.

**Comment by rkooo567** [comment]
Sure. Let me try pushing a fix by this weekend! Thanks for the clarification :)!

**Comment by rkooo567** [comment]
Okay @clarkzinzow will take care of it asap. Hey @clarkzinzow can you tell him your implementation plan and get confirmation if this can satisfy all of requirements?

**Comment by richardliaw** [comment]
Marking as P0 since this is blocking much of our other integration work.

**Comment by rkooo567** [comment]
cc @yuduber Just a reminder the PR is the proposed fix I discussed with you yesterday.

**Comment by rkooo567** [comment]
@yuduber The proposed solution is merged. Please create other issues if you see other port-related issues! I'd love to take a look :)

**Comment by yuduber** [comment]
Thanks for the fix.  I just had time to take a look at the fix.

I have a question regarding the fix.  In the new_port(lower_bound=10000, upper_bound=65535, blacklist=None) function,  I didn't see you check if the randomly generated port conflicting with any existing port or not.  If this happen, the port will not be usable right?  I am talking about not only the ports used by gcs, object_manager etc.  For these you have already captured in self.reserved_ports.  I am talking about any other unrelated process that's running in the same host.  For example, in a production environment, you might have to open some ssh channel for remote control, or chief channel for host software updating etc.  These processes are totally not related to our ray cluster and could take any port numbers.  We don't want to conflict with these either otherwise ray cluster startup will fail randomly since now in ray startup we pick ports randomly.

Can you add in a port open check as well?  something like [this](https://stackoverflow.com/questions/19196105/how-to-check-if-a-network-port-is-open-on-linux) , so that we only pick ports that are open at the moment.

```
import socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
result = sock.connect_ex(('127.0.0.1',80))
if result == 0:
   print "Port is open"
else:
   print "Port is not open"
sock.close()
```

**Comment by rkooo567** [comment]
Ah, the new_port is used to allocate redis ports, and the retry happens within `start_redis_instance`. (it basically keeps calling new port until it succeeds to start on that port). 

For other processes, they already have the mechanism to retry on different ports if the port is not available. There are 3 components that could be problematic though. --metrics-export-port, --metrics-agent-port and --min&max-worker-port. Adding the mechanism to retry for these ports require some big refactoring to our initialization path, so I recommend you to just bind them to specific ports.

**Comment by yuduber** [comment]
All right I see.  If you have retry at higher level, it will probably fine as well.  I will try this latest code to see if things works fine.  Thanks.

**Comment by rkooo567** [comment]
Sounds great! Please ping me again if you have any other issue. I'd love to discuss the solution and help you unblocked :)

**Comment by lalalapotter** [comment]
I encountered a similar problem during use. I checked the PR #14435, and the relevant code has been removed in the latest branch. Did you retry in the higher-level code?
