### ISSUE TITLE
Failure in monitor.py when recovering from node failures.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1410]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.3.0
- **Python version**: 3.6
- **Exact command to reproduce**: I was running the evolution strategies example on 200 nodes (m4.10xlarge) with command

```
python ray/python/ray/rllib/train.py --redis-address 172.31.22.218:6379 --env=Pong-v0 --run=ES --config='{"num_workers": 3600, "episodes_per_batch": 10000, "timesteps_per_batch": 100000}'
```

Several spot instances were killed. After a while I noticed that the logs from `monitor.py` contained the error

```
Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/monitor.py", line 676, in <module>
    monitor.run()
  File "/home/ubuntu/ray/python/ray/monitor.py", line 614, in run
    self.process_messages()
  File "/home/ubuntu/ray/python/ray/monitor.py", line 570, in process_messages
    message_handler(channel, data)
  File "/home/ubuntu/ray/python/ray/monitor.py", line 273, in db_client_notification_handler
    GetRootAsSubscribeToDBClientTableReply(data, 0))
  File "/home/ubuntu/ray/python/ray/core/generated/SubscribeToDBClientTableReply.py", line 12, in GetRootAsSubscribeToDBClientTableReply
    n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flatbuffers-2015.12.22.1-py3.6.egg/flatbuffers/encode.py", line 24, in Get
TypeError: memoryview: a bytes-like object is required, not 'int'
```

**Comment by robertnishihara** [comment]
I'm seeing a related error when stress testing on a 200 node cluster (also in `monitor.py`)

```
Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/monitor.py", line 587, in <module>
    monitor.run()
  File "/home/ubuntu/ray/python/ray/monitor.py", line 526, in run
    self.process_messages()
  File "/home/ubuntu/ray/python/ray/monitor.py", line 483, in process_messages
    message_handler(channel, data)
  File "/home/ubuntu/ray/python/ray/monitor.py", line 295, in plasma_manager_heartbeat_handler
    db_client_id = data[:DB_CLIENT_ID_SIZE]
TypeError: 'int' object is not subscriptable
```

This is preceded by the following output from the primary Redis shard.

```
$ cat redis-2018-03-26_23-08-07-05519.out
39355:M 26 Mar 23:08:07.464 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
39355:M 26 Mar 23:08:07.465 # Server started, Redis version 3.9.102
39355:M 26 Mar 23:08:07.465 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
39355:M 26 Mar 23:11:46.708 # Client id=42 addr=172.31.7.72:33174 fd=26 name= age=217 idle=203 flags=N db=0 sub=4 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=16282 oll=8217 omem=134217728 events=rw cmd=subscribe scheduled to be closed ASAP for overcoming of output buffer limits.
```

So the issue may be that the monitor can't keep up with heartbeats from the primary Redis shard (or something like that) and it's pubsub connection is being closed, which leads to errors like this.

**Comment by robertnishihara** [comment]
I haven't seen this in a while.
