### ISSUE TITLE
[rllib] Error raised reading from queue - ray 2.0.0.dev0

### ISSUE THREAD

**Issue by Jogima-cyber** [ray-project/ray#14105]
### What is the problem?
Ray version : 2.0.0.dev0 (latest wheel)
Python version : 3.7
OS : debian 10
Torch version : 1.7.0
Cuda version : 10.2
24 CPU and 1 nvidia T4 GPU

After a several runs I got this error :
```
Failure # 1 (occurred at 2021-02-15_08-25-30)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 678, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 597, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/opt/conda/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ray/worker.py", line 1417, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::APEX.train_buffered()[39m (pid=5627, ip=172.17.0.2)
  File "python/ray/_raylet.pyx", line 486, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trainable.py", line 167, in train_buffered
    result = self.train()
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 538, in train
    raise e
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 524, in train
    result = Trainable.train(self)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trainable.py", line 226, in train
    result = self.step()
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 148, in step
    res = next(self.train_exec_impl)
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 1075, in build_union
    item = next(it)
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/execution/concurrency_ops.py", line 135, in base_iterator
    raise RuntimeError("Error raised reading from queue")
RuntimeError: Error raised reading from queue
```
### Reproduction (REQUIRED)
```
import ray
ray.init(log_to_driver=False)

from gym.spaces import Discrete, Box
from ray.rllib.env import MultiAgentEnv
import copy
import numpy as np

import copy

FAKE_OBS = [{'action': 'NORTH','reward': 0,'info': {},'observation': {'remainingOverageTime': 60,'step': 0,'geese': [[54], [51], [57], [63]],'food': [17, 70],'index': 0},'status': 'ACTIVE'},{'action': 'NORTH','reward': 0,'info': {},'observation': {'remainingOverageTime': 60, 'index': 1},'status': 'ACTIVE'},{'action': 'NORTH','reward': 0,'info': {},'observation': {'remainingOverageTime': 60, 'index': 2},'status': 'ACTIVE'},{'action': 'NORTH','reward': 0,'info': {},'observation': {'remainingOverageTime': 60, 'index': 3},'status':'ACTIVE'}]

class GeeseEnv(MultiAgentEnv):
    def __init__(self, env_config):
        self.num_agents = 4
        self.previous_obs = None
        self.current_obs = None
    
    def observation(self, obs, player=None):
        if player is None:
            player = 0

        b = np.zeros((self.num_agents * 4 + 1, 7 * 11), dtype=np.float32)
        obs = obs[0]["observation"]

        for p, geese in enumerate(obs['geese']):
            # head position
            for pos in geese[:1]:
                b[0 + (p - player) % self.num_agents, pos] = 1
            # tip position
            for pos in geese[-1:]:
                b[4 + (p - player) % self.num_agents, pos] = 1
            # whole position
            for pos in geese:
                b[8 + (p - player) % self.num_agents, pos] = 1

        # previous head position
        if self.previous_obs is not None:
            obs_prev = self.previous_obs[0]['observation']
            for p, geese in enumerate(obs_prev['geese']):
                for pos in geese[:1]:
                    b[12 + (p - player) % self.num_agents, pos] = 1

        # food
        for pos in obs['food']:
            b[16, pos] = 1

        return b.reshape(-1, 7*11)
    
    def get_boards(self, obs, ):
        return {"agent_"+str(player):self.observation(obs,player) for player in [0,1,2,3]}
    
    def reset(self):
        obs = FAKE_OBS
        self.previous_obs = None
        self.current_obs = copy.deepcopy(obs)
        self.get_rewards(obs)
        return self.get_boards(obs)
    
    def _map_missing_actions(self,action_dict):
        choices = ['NORTH', 'SOUTH', 'WEST', 'EAST']
        actions = [0,0,0,0]
        for agent in action_dict:
            action_idx = int(agent[6])
            actions[action_idx] = action_dict[agent]
        
        return [choices[value] for value in actions]
    
    def _demap_missing_actions(self, agents, obs,rewards,dones):
        dones_demapped = {agent:dones[agent] for agent in agents}
        dones_demapped['__all__'] = dones['__all__']
        return {agent:obs[agent] for agent in agents},\
                {agent:rewards[agent] for agent in agents},\
                dones, {}
        
    def get_rewards(self,obs):
        return {"agent_"+str(value):np.random.randint(4) for value in range(len(obs))}
    
    def step(self, action_dict):
        agents = list(action_dict.keys())
        
        str_actions = self._map_missing_actions(action_dict)
        # TODO : mask the actions
        self.previous_obs = copy.deepcopy(self.current_obs)
        obs = FAKE_OBS
        self.current_obs = copy.deepcopy(obs)
        
        rewards = self.get_rewards(obs)
        dones = {"agent_"+str(value):False if obs[value]["status"] == "ACTIVE" else True for value in range(len(obs))}
        dones["__all__"] = True
        for value in range(len(obs)):
            if not dones["agent_"+str(value)]:
                dones["__all__"] = False

        return self._demap_missing_actions(agents,self.get_boards(obs), rewards, dones)

from ray import tune
from ray.rllib.agents.dqn.apex import ApexTrainer

analysis = tune.run(
    ApexTrainer,
    stop={"episodes_total": 200000},
    local_dir="./ray_results",
    checkpoint_at_end=True,
    config={
        "env": GeeseEnv,
        "log_level": "WARN",
        "hiddens": [1024,1024,1024,1024,1024,1024],
        "framework": "torch",
        "num_atoms": 51,
        "num_gpus": 1,
        "num_workers": 23,
        "model": {
            "fcnet_hiddens": [1024,1024,1024,1024,1024],
        },
        "multiagent": {
            "policies": {
                # the first tuple value is None -> uses default policy
                "pol1": (None, Box(low=0, high=1, shape=(17,7*11), dtype=np.int8), Discrete(4), {"gamma": 0.997})
            },
            "policy_mapping_fn":
                lambda agent_id:
                    "pol1"
        },
    },
)
```
- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by Jogima-cyber** [comment]
Plus there are tones of warnings regarding torch deprecated functions. I wonder if there is not a problem with inplace operations somewhere in the code (like using torch.nn.functional.relu_) causing this issue here.

**Comment by Jogima-cyber** [comment]
To reproduce you may have to let it run a bit (it happens randomly, I managed to reproduce it on the 11 iteration and another time on the 21 iteration).
When setting log_to_driver to true, I manage to gather more information about the error (but I'm flooded by deprecation warnings as well)
```
(pid=24018) Exception in thread Thread-1:
(pid=24018) Traceback (most recent call last):
(pid=24018)   File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
(pid=24018)     self.run()
(pid=24018)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/dqn/learner_thread.py", line 43, in run
(pid=24018)     self.step()
(pid=24018)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/dqn/learner_thread.py", line 52, in step
(pid=24018)     grad_out = self.local_worker.learn_on_batch(replay)
(pid=24018)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 871, in learn_on_batch
(pid=24018)     info_out[pid] = policy.learn_on_batch(batch)
(pid=24018)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/utils/threading.py", line 21, in wrapper
(pid=24018)     return func(self, *a, **k)
(pid=24018)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/torch_policy.py", line 356, in learn_on_batch
(pid=24018)     grads, fetches = self.compute_gradients(postprocessed_batch)
(pid=24018)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/utils/threading.py", line 21, in wrapper
(pid=24018)     return func(self, *a, **k)
(pid=24018)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/torch_policy.py", line 414, in compute_gradients
(pid=24018)     loss_out[i].backward(retain_graph=(i < len(self._optimizers) - 1))
(pid=24018)   File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
(pid=24018)     torch.autograd.backward(self, gradient, retain_graph, create_graph)
(pid=24018)   File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
(pid=24018)     allow_unreachable=True)  # allow_unreachable flag
(pid=24018) RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1024, 1]], which is output 0 of TBackward, is at version 6; expected version 5 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
(pid=24018) 
2021-02-15 11:46:32,424	ERROR trial_runner.py:708 -- Trial APEX_GeeseEnv_ecba0_00000: Error processing event.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 678, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 597, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/opt/conda/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ray/worker.py", line 1417, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::APEX.train_buffered() (pid=24018, ip=172.17.0.2)
  File "python/ray/_raylet.pyx", line 486, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trainable.py", line 167, in train_buffered
    result = self.train()
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 538, in train
    raise e
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 524, in train
    result = Trainable.train(self)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trainable.py", line 226, in train
    result = self.step()
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 148, in step
    res = next(self.train_exec_impl)
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 1075, in build_union
    item = next(it)
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/execution/concurrency_ops.py", line 135, in base_iterator
    raise RuntimeError("Error raised reading from queue")
RuntimeError: Error raised reading from queue
```

**Comment by VIPTankz** [comment]
Hello, 
I also got this problem when running IMPALA using the following config on top of the default.

DEFAULT_CONFIG["framework"] = "torch"
DEFAULT_CONFIG["gamma"] = 0.999
DEFAULT_CONFIG["num_workers"] = 16
DEFAULT_CONFIG["num_gpus"] = 1
DEFAULT_CONFIG["num_envs_per_worker"] = 2
DEFAULT_CONFIG["evaluation_num_workers"] = 1
DEFAULT_CONFIG["evaluation_interval"] = 25
DEFAULT_CONFIG["evaluation_duration"] = 1
DEFAULT_CONFIG["evaluation_config"] = {
        "render_env": True,
    }

Has this issue been solved?
