### ISSUE TITLE
[dask on ray issues]: errors running dask matmul

### ISSUE THREAD

**Issue by photoszzt** [ray-project/ray#14121]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray: 2.0.0.dev0
dask==2021.1.1

When enable the object spilling on a ray cluster(by passing --system-config='{"automatic_object_spilling_enabled":true,"max_io_workers":2,"object_spilling_config":"{\"type\":\"filesystem\",\"params\":{\"directory_path\":\"/tmp/spill\"}}"}' to the head node configuration), the program aborts with bus error. 

Error output:
```
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
Fetched IP: 3.238.219.129
Shared connection to 3.238.219.129 closed.
Shared connection to 3.238.219.129 closed.
Fetched IP: 3.238.219.129
Shared connection to 3.238.219.129 closed.
2021-02-15 14:26:48,908 INFO worker.py:655 -- Connecting to existing Ray cluster at address: 172.31.7.112:6379
(autoscaler +26s) Tip: use `ray status` to view detailed autoscaling status. To disable autoscaler event messages, you can set AUTOSCALER_EVENTS=0.
(autoscaler +26s) Adding 2 nodes of type ray-legacy-worker-node-type.
(autoscaler +32s) Adding 3 nodes of type ray-legacy-worker-node-type.
(autoscaler +57s) Resized to 12 CPUs.
(autoscaler +57s) Adding 1 nodes of type ray-legacy-worker-node-type.
(autoscaler +1m4s) Resized to 24 CPUs.
(autoscaler +1m4s) Adding 3 nodes of type ray-legacy-worker-node-type.
(autoscaler +1m10s) Resized to 28 CPUs.
(autoscaler +1m29s) Resized to 32 CPUs.
(autoscaler +1m35s) Resized to 36 CPUs.
(autoscaler +1m41s) Resized to 44 CPUs.
Bus error (core dumped)
Shared connection to 3.238.219.129 closed.
Error: Command failed:

  ssh -tt -i /home/zhitingz/.ssh/ray-autoscaler_us-east-1.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_4dcb4daf68/c21f969b5f/%C -o ControlPersist=10s -o ConnectTimeout=120s ubuntu@3.238.219.129 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (docker exec -it  ray_container /bin/bash -c '"'"'bash --login -c -i '"'"'"'"'"'"'"'"'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (python /home/ray/gemm.py --download 25000 25000 uint16)'"'"'"'"'"'"'"'"''"'"' )'


```

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
```python
from timeit import default_timer as dtimer
import ray
from ray.util.dask import ray_dask_get
import dask
import dask.array as da
import numpy as np


def main():
    _ = ray.init(address="auto")
    dask.config.set(scheduler=ray_dask_get)
    chunks=(1000, 1000)
    x = da.random.randint(0, 65_535, size=(25000, 25000),
                          dtype=np.uint16, chunks=chunks)
    y = da.random.randint(0, 65_535, size=(25000, 25000),
                          dtype=np.uint16, chunks=chunks)
    start = dtimer()
    z = da.matmul(x, y)
    # print(z)
    # z.visualize(filename=f'gemm_{rows}x{cols}_{tp}_{chunks}.svg')

    z_val = z.compute()
    end = dtimer()
    print(z_val)
    print(f"time: {end-start} s")


if __name__ == "__main__":
    main()
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
Thanks for posting the issue! Can you also provide us your ray start command? It'll be also great if you can provide the output of `ray.cluster_resources()`

**Comment by rkooo567** [comment]
Also, can you show us logs inside `/tmp/ray/session_latest/logs/raylet.err`?

**Comment by photoszzt** [comment]
I setup a cluster using ray up with a config like this:
```
cluster_name: default

min_workers: 1

max_workers: 10

upscaling_speed: 1.0

docker:
    image: rayproject/ray:nightly-cpu # with dask
    container_name: "ray_container"
    # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
    # if no cached version is present.
    pull_before_run: True
    run_options: []  # Extra options to pass into "docker run"

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 5

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-east-1
    # Availability zone(s), comma-separated, that nodes may be launched in.
    # Nodes are currently spread between zones by a round-robin approach,
    # however this implementation detail should not be relied upon.
    availability_zone: us-east-1a,us-east-1b
    # Whether to allow node reuse. If set to False, nodes will be terminated
    # instead of stopped.
    cache_stopped_nodes: True # If not present, the default is True.

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
# By default Ray creates a new private keypair, but you can also use your own.
# If you do so, make sure to also set "KeyName" in the head and worker node
# configurations below.
#    ssh_private_key: /path/to/your/key.pem

# Provider-specific config for the head node, e.g. instance type. By default
# Ray will auto-configure unspecified fields such as SubnetId and KeyName.
# For more documentation on available fields, see:
# http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances
head_node:
    InstanceType: m5a.xlarge
    ImageId: ami-03d315ad33b9d49c4 # ubuntu 20.04 lts with docker
    IamInstanceProfile:
        Arn: arn:aws:iam::${acc_num}:instance-profile/ray-autoscaler-v1

    # You can provision additional disk space with a conf as follows
    BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
              VolumeSize: 20

    # Additional options in the boto docs.

# Provider-specific config for worker nodes, e.g. instance type. By default
# Ray will auto-configure unspecified fields such as SubnetId and KeyName.
# For more documentation on available fields, see:
# http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances
worker_nodes:
    InstanceType: m5a.xlarge
    ImageId: ami-03d315ad33b9d49c4 # ubuntu 20.04 lts with docker
    IamInstanceProfile:
        Arn: arn:aws:iam::${acc_num}:instance-profile/ray-autoscaler-v1

    # Run workers on spot by default. Comment this out to use on-demand.
    InstanceMarketOptions:
        MarketType: spot
        # SpotOptions:
        #     SpotInstanceType: persistent
        #     InstanceInterruptionBehavior: stop
        # Additional options can be found in the boto docs, e.g.
        #   SpotOptions:
        #       MaxPrice: MAX_HOURLY_PRICE

    # Additional options in the boto docs.

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {
#    "/path1/on/remote/machine": "/path1/on/local/machine",
#    "/path2/on/remote/machine": "/path2/on/local/machine",
}

# Files or directories to copy from the head node to the worker nodes. The format is a
# list of paths. The same path on the head node will be copied to the worker node.
# This behavior is a subset of the file_mounts behavior. In the vast majority of cases
# you should just use file_mounts. Only use this if you know what you're doing!
cluster_synced_files: []

# Whether changes to directories in file_mounts or cluster_synced_files in the head node
# should sync to the worker node continuously
file_mounts_sync_continuously: False

# Patterns for files to exclude when running rsync up or rsync down
rsync_exclude:
    - "**/.git"
    - "**/.git/**"

# Pattern files to use for filtering out files when running rsync up or rsync down. The file is searched for
# in the source directory and recursively through all subdirectories. For example, if .gitignore is provided
# as a value, the behavior will match git's behavior for finding and using .gitignore files.
rsync_filter:
    - ".gitignore"

# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
initialization_commands:
    - curl -fsSL https://get.docker.com -o get-docker.sh
    - sudo sh get-docker.sh
    - sudo usermod -aG docker $USER
    - sudo systemctl restart docker -frch)

# List of shell commands to run to set up nodes.
setup_commands:
    # Note: if you're developing Ray, you probably want to create a Docker image that
    # has your Ray repo pre-cloned. Then, you can replace the pip installs
    # below with a git checkout <your_sha> (and possibly a recompile).
    # Uncomment the following line if you want to run the nightly version of ray (as opposed to the latest)
    # - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
    - pip install -U dask==2021.1.1

# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - ulimit -n 65536; ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --system-config='{"automatic_object_spilling_enabled":true,"max_io_workers":2,"object_spilling_config":"{\"type\":\"filesystem\",\"params\":{\"directory_path\":\"/tmp/spill\"}}"}'

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076

```

**Comment by rkooo567** [comment]
oh also, the bus error happens when you use too much of shared memory. You can also veruft this by calling `df -a /dev/shm`. Can you also check the output of this when the application crashes?

**Comment by photoszzt** [comment]
The raylet.err outputs this:
```
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
Fetched IP: 3.238.219.129
Warning: Permanently added '3.238.219.129' (ECDSA) to the list of known hosts.
[2021-02-15 15:19:50,617 C 39361 39361] local_object_manager.cc:340:  Check failed: spilled_objects_url_.count(object_id) > 0
[2021-02-15 15:19:50,617 E 39361 39361] logging.cc:435: *** Aborted at 1613431190 (unix time) try "date -d @1613431190" if you are using GNU date ***
[2021-02-15 15:19:50,618 E 39361 39361] logging.cc:435: PC: @                0x0 (unknown)
[2021-02-15 15:19:50,623 E 39361 39361] logging.cc:435: *** SIGABRT (@0x3e8000099c1) received by PID 39361 (TID 0x7f837aeab800) from PID 39361; stack trace: ***
[2021-02-15 15:19:50,624 E 39361 39361] logging.cc:435:     @     0x561d996eacef google::(anonymous namespace)::FailureSignalHandler()
[2021-02-15 15:19:50,624 E 39361 39361] logging.cc:435:     @     0x7f837b40d3c0 (unknown)
[2021-02-15 15:19:50,625 E 39361 39361] logging.cc:435:     @     0x7f837aef618b gsignal
[2021-02-15 15:19:50,625 E 39361 39361] logging.cc:435:     @     0x7f837aed5859 abort
[2021-02-15 15:19:50,627 E 39361 39361] logging.cc:435:     @     0x561d996dc0c5 ray::SpdLogMessage::Flush()
[2021-02-15 15:19:50,628 E 39361 39361] logging.cc:435:     @     0x561d996dc0fd ray::RayLog::~RayLog()
[2021-02-15 15:19:50,629 E 39361 39361] logging.cc:435:     @     0x561d99329e07 ray::raylet::LocalObjectManager::AsyncRestoreSpilledObject()
[2021-02-15 15:19:50,629 E 39361 39361] logging.cc:435:     @     0x561d992ca0cc _ZNSt17_Function_handlerIFvRKN3ray8ObjectIDERKSsRKNS0_6NodeIDESt8functionIFvRKNS0_6StatusEEEEZNS0_6raylet6RayletC4ERN5boost4asio10io_contextES5_S5_S5_iS5_RKNSG_17NodeManagerConfigERKNS0_19ObjectManagerConfigESt10shared_ptrINS0_3gcs9GcsClientEEiEUlS3_S5_S8_SE_E_E9_M_invokeERKSt9_Any_dataS3_S5_S8_OSE_
[2021-02-15 15:19:50,631 E 39361 39361] logging.cc:435:     @     0x561d993e053a ray::PullManager::TryToMakeObjectLocal()
[2021-02-15 15:19:50,633 E 39361 39361] logging.cc:435:     @     0x561d993e0bcb ray::PullManager::UpdatePullsBasedOnAvailableMemory()
[2021-02-15 15:19:50,635 E 39361 39361] logging.cc:435:     @     0x561d993e1c20 ray::PullManager::OnLocationChange()
[2021-02-15 15:19:50,636 E 39361 39361] logging.cc:435:     @     0x561d993b9b48 _ZNSt17_Function_handlerIFvRKN3ray8ObjectIDERKSt6vectorINS0_3rpc20ObjectLocationChangeESaIS6_EEEZNS0_15ObjectDirectory24SubscribeObjectLocationsERKNS0_8UniqueIDES3_RKNS5_7AddressERKSt8functionIFvS3_RKSt13unordered_setINS0_6NodeIDESt4hashISL_ESt8equal_toISL_ESaISL_EERKSsRKSL_mEEEUlS3_SA_E_E9_M_invokeERKSt9_Any_dataS3_SA_
[2021-02-15 15:19:50,637 E 39361 39361] logging.cc:435:     @     0x561d9947e713 _ZNSt17_Function_handlerIFvN3ray6StatusERKN5boost8optionalINS0_3rpc18ObjectLocationInfoEEEEZZNS0_3gcs30ServiceBasedObjectInfoAccessor25AsyncSubscribeToLocationsERKNS0_8ObjectIDERKSt8functionIFvSE_RKSt6vectorINS4_20ObjectLocationChangeESaISH_EEEERKSF_IFvS1_EEENKUlST_E_clEST_EUlRKS1_S8_E_E9_M_invokeERKSt9_Any_dataOS1_S8_
[2021-02-15 15:19:50,637 E 39361 39361] logging.cc:435:     @     0x561d99485a30 _ZNSt17_Function_handlerIFvRKN3ray6StatusERKNS0_3rpc23GetObjectLocationsReplyEEZNS0_3gcs30ServiceBasedObjectInfoAccessor17AsyncGetLocationsERKNS0_8ObjectIDERKSt8functionIFvS1_RKN5boost8optionalINS4_18ObjectLocationInfoEEEEEEUlS3_S7_E_E9_M_invokeERKSt9_Any_dataS3_S7_
[2021-02-15 15:19:50,639 E 39361 39361] logging.cc:435:     @     0x561d994542d1 _ZNSt17_Function_handlerIFvRKN3ray6StatusERKNS0_3rpc23GetObjectLocationsReplyEEZNS4_12GcsRpcClient18GetObjectLocationsERKNS4_25GetObjectLocationsRequestERKSt8functionIS8_EEUlS3_S7_E_E9_M_invokeERKSt9_Any_dataS3_S7_
[2021-02-15 15:19:50,640 E 39361 39361] logging.cc:435:     @     0x561d9945702f ray::rpc::ClientCallImpl<>::OnReplyReceived()
[2021-02-15 15:19:50,641 E 39361 39361] logging.cc:435:     @     0x561d99345472 _ZN5boost4asio6detail18completion_handlerIZN3ray3rpc17ClientCallManager29PollEventsFromCompletionQueueEiEUlvE_E11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm
[2021-02-15 15:19:50,643 E 39361 39361] logging.cc:435:     @     0x561d99a59901 boost::asio::detail::scheduler::do_run_one()
[2021-02-15 15:19:50,645 E 39361 39361] logging.cc:435:     @     0x561d99a5afa9 boost::asio::detail::scheduler::run()
[2021-02-15 15:19:50,645 E 39361 39361] logging.cc:435:     @     0x561d99a5d497 boost::asio::io_context::run()
[2021-02-15 15:19:50,646 E 39361 39361] logging.cc:435:     @     0x561d992a2072 main
[2021-02-15 15:19:50,647 E 39361 39361] logging.cc:435:     @     0x7f837aed70b3 __libc_start_main
[2021-02-15 15:19:50,649 E 39361 39361] logging.cc:435:     @     0x561d992b7165 (unknown)

```

For shm, I cat on the head node:
```
Filesystem     1K-blocks    Used Available Use% Mounted on
shm              5101024 4589952    511072  90% /dev/shm
```

Is there any command to execute commands on all nodes?

**Comment by photoszzt** [comment]
I change the chunk size to 5000 to make the issue easier to reproduce:
```
from timeit import default_timer as dtimer
import ray
from ray.util.dask import ray_dask_get
import dask
import dask.array as da
import numpy as np


def main():
    _ = ray.init(address="auto")
    dask.config.set(scheduler=ray_dask_get)
    chunks=(5000, 5000)
    x = da.random.randint(0, 65_535, size=(25000, 25000),
                          dtype=np.uint16, chunks=chunks)
    y = da.random.randint(0, 65_535, size=(25000, 25000),
                          dtype=np.uint16, chunks=chunks)
    start = dtimer()
    z = da.matmul(x, y)
    # print(z)
    # z.visualize(filename=f'gemm_{rows}x{cols}_{tp}_{chunks}.svg')

    z_val = z.compute()
    end = dtimer()
    print(z_val)
    print(f"time: {end-start} s")


if __name__ == "__main__":
    main()
```

**Comment by rkooo567** [comment]
While I will look into the issue, can you actually try one thing? 

-> Set `--object-store-memory` to be lower than `5101024 KB`. You can do sth like `ray start --head --object-store-memory= 3758096384` => 3.5 GB of object store memory.

**Comment by photoszzt** [comment]
When storing the matrix in npy(no compression) file, it's 1.2 GB.

**Comment by photoszzt** [comment]
When looking at the autoscaler log:
```
Usage:
 44.0/44.0 CPU
 0.00/26.318 GiB object_store_memory
 0.00/126.025 GiB memory
```
Is there any reason the object store memory and memory are zero? When logging into the node, the memory usage is not zero.

**Comment by photoszzt** [comment]
I change the object store memory to 3.5 GB. It fails with a different error:
```
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
Fetched IP: 3.238.219.129
Shared connection to 3.238.219.129 closed.
Shared connection to 3.238.219.129 closed.
Fetched IP: 3.238.219.129
Shared connection to 3.238.219.129 closed.
2021-02-15 16:21:56,939 INFO worker.py:655 -- Connecting to existing Ray cluster at address: 172.31.7.112:6379
(autoscaler +23s) Tip: use `ray status` to view detailed autoscaling status. To disable autoscaler event messages, you can set AUTOSCALER_EVENTS=0.
(autoscaler +23s) Adding 1 nodes of type ray-legacy-worker-node-type.
(autoscaler +35s) Adding 1 nodes of type ray-legacy-worker-node-type.
(autoscaler +43s) Adding 1 nodes of type ray-legacy-worker-node-type.
(autoscaler +54s) Adding 1 nodes of type ray-legacy-worker-node-type.
(autoscaler +1m0s) Resized to 12 CPUs.
(autoscaler +1m0s) Adding 2 nodes of type ray-legacy-worker-node-type.
(raylet) [2021-02-15 16:23:06,322 E 39997 39997] object_manager.cc:397: Failed to establish connection for Push with remote object manager.
(raylet) [2021-02-15 16:23:06,324 E 39997 39997] object_manager.cc:397: Failed to establish connection for Push with remote object manager.
(raylet) [2021-02-15 16:23:06,324 E 39997 39997] object_manager.cc:397: Failed to establish connection for Push with remote object manager.
(autoscaler +1m13s) Resized to 20 CPUs.
(autoscaler +1m26s) Resized to 24 CPUs.
(autoscaler +1m26s) Adding 1 nodes of type ray-legacy-worker-node-type.
(autoscaler +1m33s) Resized to 28 CPUs.
(autoscaler +1m33s) Adding 1 nodes of type ray-legacy-worker-node-type.
(autoscaler +1m41s) Resized to 32 CPUs.
(autoscaler +1m41s) Adding 1 nodes of type ray-legacy-worker-node-type.
(autoscaler +2m10s) Resized to 40 CPUs.
(autoscaler +2m15s) Resized to 44 CPUs.
2021-02-15 16:55:25,329 WARNING worker.py:1109 -- WARNING: 12 PYTHON workers have been started. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (see https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.
2021-02-15 17:25:29,339 WARNING worker.py:1109 -- WARNING: 12 PYTHON workers have been started. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (see https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.
(autoscaler +1h25m27s) Removing 1 nodes of type ray-legacy-worker-node-type (idle).
(autoscaler +1h25m33s) Removing 1 nodes of type ray-legacy-worker-node-type (idle).
2021-02-15 17:47:54,102 WARNING worker.py:1109 -- The node with node id e91ebfb1020a95155a7bad59715ebbfdffc63f977cf11a84e082da55 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.
(autoscaler +1h26m3s) Resized to 40 CPUs.
2021-02-15 17:48:00,209 WARNING worker.py:1109 -- The node with node id 0c9e29ed40cd74eb9fe432bc35db31f32bab46f84f456a4426504f63 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.
(autoscaler +1h26m8s) Resized to 36 CPUs.
Traceback (most recent call last):
  File "/home/ray/gemm.py", line 90, in <module>
    main()
  File "/home/ray/gemm.py", line 83, in main
    z_val = z.compute()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/dask/base.py", line 279, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/dask/base.py", line 561, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 118, in ray_dask_get
    result = ray_get_unpack(object_refs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 359, in ray_get_unpack
    computed_result = ray.get(object_refs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1458, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::dask:('sum-aggregate-reshape-9304a38b121b44a9914b0d97d811d126', 3, 0) (pid=8368, ip=172.31.6.235)
  File "python/ray/_raylet.pyx", line 442, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 464, in ray._raylet.execute_task
ray.exceptions.ObjectLostError: Object ee694d8564355461ffffffffffffffffffffffff0200000001000000 is lost due to node failure.
Shared connection to 3.238.219.129 closed.
Error: Command failed:

  ssh -tt -i /home/zhitingz/.ssh/ray-autoscaler_us-east-1.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_4dcb4daf68/c21f969b5f/%C -o ControlPersist=10s -o ConnectTimeout=120s ubuntu@3.238.219.129 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (docker exec -it  ray_container /bin/bash -c '"'"'bash --login -c -i '"'"'"'"'"'"'"'"'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (python /home/ray/gemm.py --download 25000 25000 uint16)'"'"'"'"'"'"'"'"''"'"' )'

```

**Comment by rkooo567** [comment]
@photoszzt they are allocated only when you specify resources in @remote method. By default, it is 0. But the real resources are actually used (you can check the dashboard to see the memory & object store memory usage).

The error indicates one of your nodes failed. I think we should take a look at the issue in order to figure out the exact root cause. Thanks for the report!!

**Comment by ericl** [comment]
I think this could be related to object ownership... if you disable autoscaling, does the workload run? cc @stephanie-wang

**Comment by ericl** [comment]
You can set min_workers = max_workers in the cluster config.

**Comment by ericl** [comment]
Btw, is the bus error fixed? We should track that in a separate issue if Ray isn't autodetecting the right shared memory size (cc @rkooo567 )

**Comment by rkooo567** [comment]
@ericl Bus error doesn't appear after setting lower plasma store memory size. I think it definitely doesn't autodetect the max shared memory size (I've actually seen this issue before too). I can create a new issue for this. 

His new particular issue just seems to be related to some race condition? `Check failed: spilled_objects_url_.count(object_id) > 0`. Also I ran this yesterday in my cluster, and I could see the same issue.

**Comment by ericl** [comment]
Is it because the node was removed due to autoscaling? It seems to be an incorrect check in that case then.

**Comment by stephanie-wang** [comment]
Just took a quick look at the code and it seems like it may just be a race condition with multinode spilling to disk.

We add the URL to the map [here](https://github.com/ray-project/ray/blob/master/src/ray/raylet/local_object_manager.cc#L294), but this gets called in a callback after adding the spilled location to the object directory. So there is a window where the location could be in the directory for others to read but the node doesn't have it in its local `spilled_objects_url_` map yet.

Seems like a simple fix; just add the URL to the spilled_objects_url_ map before adding it to the global directory. We should also change the assertion to a warning and force the client to retry.

**Comment by rkooo567** [comment]
> Seems like a simple fix; just add the URL to the spilled_objects_url_ map before adding it to the global directory. 
If we do this, is it necessary to change the assertion? In this case, doesn't the object URL should always exist?

**Comment by rkooo567** [comment]
^ Talked to Stephanie, and I will make a PR To address both parts she mentioned.

**Comment by photoszzt** [comment]
I try disable the autoscaler. It seems it's hitting a deadlock somewhere. There's no output and the cpus are idle.

**Comment by rkooo567** [comment]
@photoszzt I am fixing the issue rn. Can you try again in a few days? Btw, I verified this worked when I used a larger memory machine (like 10GB object store per node)

**Comment by rkooo567** [comment]
^ PR to fix the check failure you are seeing.

**Comment by rkooo567** [comment]
^ This issue should've been fixed. I will also try verifying it in a few days.

**Comment by rkooo567** [comment]
Hey @photoszzt can you try running it again, and if you face the issue again can you create a new issue and tag me there?
