### ISSUE TITLE
Function checkpointing is disabled. This may result in unexpected behavior when using checkpointing features or certain schedulers. To enable, set the train function arguments to be `func(config, checkpoint_dir=None)`.

### ISSUE THREAD

**Issue by ali3assi** [ray-project/ray#14159]
Hi, I am new to ray so i am facing some difficulties.
When i run my code i get the following before I can see the training progress.
```
Function checkpointing is disabled. This may result in unexpected behavior when using checkpointing features or certain schedulers. To enable, set the train function arguments to be `func(config, checkpoint_dir=None)`.
[I 2021-02-17 12:59:56,330] A new study created in memory with name: optuna
Warning: The actor ImplicitFunc has size 25927174 when pickled. It will be stored in Redis, which could cause memory issues. This may mean that its definition uses a large array or other object.
Log sync requires rsync to be installed.
== Status ==
Memory usage on this node: 13.8/15.7 GiB
Using AsyncHyperBand: num_stopped=0
Bracket: Iter 40.000: None | Iter 10.000: None
Resources requested: 6/8 CPUs, 0/0 GPUs, 0.0/1.56 GiB heap, 0.0/0.54 GiB objects
Result logdir: C:\Users\ali\ray_results\optuna_search
Number of trials: 1/2 (1 RUNNING)
```
Then after i get an exception:
```
Trial train_f191a516: Error processing event.
Traceback (most recent call last):
  File "C:\Users\ali\miniconda3\envs\test\lib\site-packages\ray\tune\trial_runner.py", line 594, in _process_trial
    decision = self._process_trial_result(trial, result)
  File "C:\Users\ali\miniconda3\envs\test\lib\site-packages\ray\tune\trial_runner.py", line 631, in _process_trial_result
    self._validate_result_metrics(result)
  File "C:\Users\ali\miniconda3\envs\test\lib\site-packages\ray\tune\trial_runner.py", line 742, in _validate_result_metrics
    raise ValueError(
ValueError: Trial returned a result which did not include the specified metric(s) `val_loss` that `AsyncHyperBandScheduler` expects. Make sure your calls to `tune.report()` include the metric, or set the TUNE_DISABLE_STRICT_METRIC_CHECKING environment variable to 1. Result: {'_metric': 0.43542274832725525, 'time_this_iter_s': 15.500993490219116, 'done': False, 'timesteps_total': None, 'episodes_total': None, 'training_iteration': 1, 'experiment_id': '1d8daf5631974694a1e8f4abc90c08bf', 'date': '2021-02-17_13-00-16', 'timestamp': 1613584816, 'time_total_s': 15.500993490219116, 'pid': 7940, 'hostname': 'LAPTOP-6O4H5M9S', 'node_ip': '192.168.0.100', 'config': {'batch_size': 32, 'drop_out': 0.4, 'num_filters': 16, 'kernel_size': 2, 'strides': 1, 'dense_nodes_divisor': 2, 'num_dense_nodes': 128, 'kernel_regularize': 1e-10, 'bias_regularizer': 1e-05, 'num_epochs': 2}, 'time_since_restore': 15.500993490219116, 'timesteps_since_restore': 0, 'iterations_since_restore': 1, 'trial_id': 'f191a516'}
(pid=7940) 
(pid=7940) 11/11 [==============================] - 6s 525ms/step - loss: 0.6650 - accuracy: 0.7391 - val_loss: 0.4354 - val_accuracy: 0.8000
(pid=7940) validation_loss=0.43542274832725525
Traceback (most recent call last):
  File "C:\Users\ali\miniconda3\envs\test\lib\site-packages\ray\tune\trial_runner.py", line 594, in _process_trial
    decision = self._process_trial_result(trial, result)
  File "C:\Users\ali\miniconda3\envs\test\lib\site-packages\ray\tune\trial_runner.py", line 631, in _process_trial_result
    self._validate_result_metrics(result)
  File "C:\Users\ali\miniconda3\envs\test\lib\site-packages\ray\tune\trial_runner.py", line 742, in _validate_result_metrics
    raise ValueError(
ValueError: Trial returned a result which did not include the specified metric(s) `val_loss` that `AsyncHyperBandScheduler` expects. Make sure your calls to `tune.report()` include the metric, or set the TUNE_DISABLE_STRICT_METRIC_CHECKING environment variable to 1. Result: {'_metric': 0.43542274832725525, 'time_this_iter_s': 15.500993490219116, 'done': False, 'timesteps_total': None, 'episodes_total': None, 'training_iteration': 1, 'experiment_id': '1d8daf5631974694a1e8f4abc90c08bf', 'date': '2021-02-17_13-00-16', 'timestamp': 1613584816, 'time_total_s': 15.500993490219116, 'pid': 7940, 'hostname': 'LAPTOP-6O4H5M9S', 'node_ip': '192.168.0.100', 'config': {'batch_size': 32, 'drop_out': 0.4, 'num_filters': 16, 'kernel_size': 2, 'strides': 1, 'dense_nodes_divisor': 2, 'num_dense_nodes': 128, 'kernel_regularize': 1e-10, 'bias_regularizer': 1e-05, 'num_epochs': 2}, 'time_since_restore': 15.500993490219116, 'timesteps_since_restore': 0, 'iterations_since_restore': 1, 'trial_id': 'f191a516'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/ali/OneDrive/Desktop/pythonProjects/Deep-learning-algo-master/src/myfile.py", line 279, in <module>
    main()
  File "c:/Users/ali/OneDrive/Desktop/pythonProjects/Deep-learning-algo-master/src/myfile.py", line 249, in main
    analysis = tune.run(trainer.train,
  File "C:\Users\ali\miniconda3\envs\test\lib\site-packages\ray\tune\tune.py", line 421, in run
    runner.step()
  File "C:\Users\ali\miniconda3\envs\test\lib\site-packages\ray\tune\trial_runner.py", line 402, in step
    self._process_events(timeout=timeout)  # blocking
  File "C:\Users\ali\miniconda3\envs\test\lib\site-packages\ray\tune\trial_runner.py", line 560, in _process_events
    self._process_trial(trial)
  File "C:\Users\ali\miniconda3\envs\test\lib\site-packages\ray\tune\trial_runner.py", line 617, in _process_trial
    self._process_trial_failure(trial, traceback.format_exc())
  File "C:\Users\ali\miniconda3\envs\test\lib\site-packages\ray\tune\trial_runner.py", line 826, in _process_trial_failure
    self._search_alg.on_trial_complete(trial.trial_id, error=True)
  File "C:\Users\ali\miniconda3\envs\test\lib\site-packages\ray\tune\suggest\search_generator.py", line 129, in on_trial_complete
    self.searcher.on_trial_complete(
  File "C:\Users\ali\miniconda3\envs\test\lib\site-packages\ray\tune\suggest\suggestion.py", line 382, in on_trial_complete
    self.searcher.on_trial_complete(
  File "C:\Users\ali\miniconda3\envs\test\lib\site-packages\ray\tune\suggest\optuna.py", line 222, in on_trial_complete
    val = result.get(self.metric, None)
AttributeError: 'NoneType' object has no attribute 'get'
```
### Describe your feature request

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by richardliaw** [comment]
Here is the error that you are seeing:
```
ValueError: Trial returned a result which did not include the specified metric(s) `val_loss` that `AsyncHyperBandScheduler` expects. Make sure your calls to `tune.report()` include the metric, or set the TUNE_DISABLE_STRICT_METRIC_CHECKING environment variable to 1. 

Result: {'_metric': 0.43542274832725525, 'time_this_iter_s': 15.500993490219116, 'done': False, 'timesteps_total': None, 'episodes_total': None, 'training_iteration': 1, 'experiment_id': '1d8daf5631974694a1e8f4abc90c08bf', 'date': '2021-02-17_13-00-16', 'timestamp': 1613584816, 'time_total_s': 15.500993490219116, 'pid': 7940, 'hostname': 'LAPTOP-6O4H5M9S', 'node_ip': '192.168.0.100', 'config': {'batch_size': 32, 'drop_out': 0.4, 'num_filters': 16, 'kernel_size': 2, 'strides': 1, 'dense_nodes_divisor': 2, 'num_dense_nodes': 128, 'kernel_regularize': 1e-10, 'bias_regularizer': 1e-05, 'num_epochs': 2}, 'time_since_restore': 15.500993490219116, 'timesteps_since_restore': 0, 'iterations_since_restore': 1, 'trial_id': 'f191a516'}
```

I'm guessing that you don't always pass `val_loss` every time. Consider just setting the environment variable to avoid this error? 

Also, in the future, could you please post on discuss.ray.io? Thanks!

**Comment by ali3assi** [comment]
@Thanks i Will do for next time, but now please how:
1- how can pass always the val_loss and where?
2- how to setpup tthe environment variable?
