### ISSUE TITLE
[rllib] Torch gtrxl crashes on iterable types

### ISSUE THREAD

**Issue by smorad** [ray-project/ray#14195]
The torch version of gtrxl expects `obs` to be a non-iterable `gym.space` (e.g. `Box`, not `Dict` or `Tuple`) and crashes.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Nightly linux wheel installed just now `2.0.0.dev0`

### Reproduction (REQUIRED)
Simply run this slightly modified `ray/rllib/examples/attention_net.py` using the nested repeat after me environment:
`python3 ray/rllib/examples/attention_net.py --torch --env NestedRepeatAfterMeEnv`

```
import argparse
import os

import ray
from ray import tune
from ray.rllib.examples.env.look_and_push import LookAndPush, OneHot
from ray.rllib.examples.env.repeat_after_me_env import RepeatAfterMeEnv
from ray.rllib.examples.env.nested_space_repeat_after_me_env import NestedSpaceRepeatAfterMeEnv
from ray.rllib.examples.env.repeat_initial_obs_env import RepeatInitialObsEnv
from ray.rllib.examples.env.stateless_cartpole import StatelessCartPole
from ray.rllib.utils.framework import try_import_tf
from ray.rllib.utils.test_utils import check_learning_achieved
from ray.tune import registry

tf1, tf, tfv = try_import_tf()

parser = argparse.ArgumentParser()
parser.add_argument("--run", type=str, default="PPO")
parser.add_argument("--env", type=str, default="RepeatAfterMeEnv")
parser.add_argument("--num-cpus", type=int, default=0)
parser.add_argument("--torch", action="store_true")
parser.add_argument("--as-test", action="store_true")
parser.add_argument("--stop-iters", type=int, default=200)
parser.add_argument("--stop-timesteps", type=int, default=500000)
parser.add_argument("--stop-reward", type=float, default=80)

if __name__ == "__main__":
    args = parser.parse_args()

    ray.init(num_cpus=args.num_cpus or None)

    registry.register_env("RepeatAfterMeEnv", lambda c: RepeatAfterMeEnv(c))
    registry.register_env("NestedRepeatAfterMeEnv", lambda c: NestedSpaceRepeatAfterMeEnv(c))
    registry.register_env("RepeatInitialObsEnv",
                          lambda _: RepeatInitialObsEnv())
    registry.register_env("LookAndPush", lambda _: OneHot(LookAndPush()))
    registry.register_env("StatelessCartPole", lambda _: StatelessCartPole())

    config = {
        "env": args.env,
        # This env_config is only used for the RepeatAfterMeEnv env.
        "env_config": {
            "repeat_delay": 2,
        },
        "gamma": 0.99,
        # Use GPUs iff `RLLIB_NUM_GPUS` env var set to > 0.
        "num_gpus": int(os.environ.get("RLLIB_NUM_GPUS", 0)),
        "num_workers": 0,
        "num_envs_per_worker": 20,
                "num_workers": 0,
        "num_envs_per_worker": 20,
        "entropy_coeff": 0.001,
        "num_sgd_iter": 10,
        "vf_loss_coeff": 1e-5,
        "model": {
            "use_attention": True,
            "max_seq_len": 50,
            "attention_num_transformer_units": 1,
            "attention_dim": 64,
            "attention_memory_inference": 100,
            "attention_memory_training": 50,
            "attention_num_heads": 2,
            "attention_head_dim": 32,
            "attention_position_wise_mlp_dim": 32,
        },
        "framework": "torch" if args.torch else "tf",
    }

    stop = {
        "training_iteration": args.stop_iters,
        "timesteps_total": args.stop_timesteps,
        "episode_reward_mean": args.stop_reward,
    }

    results = tune.run(args.run, config=config, stop=stop, verbose=2)

    if args.as_test:
        check_learning_achieved(results, args.stop_reward)
    ray.shutdown()
```                                            

Output:
```
2021-02-18 20:39:45,526 ERROR trial_runner.py:708 -- Trial PPO_NestedRepeatAfterMeEnv_6ebda_00000: Error processing event.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/trial_runner.py", line 678, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/ray_trial_executor.py", line 597, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/worker.py", line 1460, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::PPO.train_buffered() (pid=31259, ip=172.17.0.2)
  File "/usr/local/lib/python3.8/dist-packages/ray/rllib/utils/threading.py", line 21, in wrapper
    return func(self, *a, **k)
  File "/usr/local/lib/python3.8/dist-packages/ray/rllib/policy/torch_policy.py", line 245, in _compute_action_helper
    dist_inputs, state_out = self.model(input_dict, state_batches,
  File "/usr/local/lib/python3.8/dist-packages/ray/rllib/models/modelv2.py", line 215, in __call__
    res = self.forward(restored, state or [], seq_lens)
  File "/usr/local/lib/python3.8/dist-packages/ray/rllib/models/torch/attention_net.py", line 314, in forward
    self._features, memory_outs = self.gtrxl(input_dict, state, seq_lens)
  File "/usr/local/lib/python3.8/dist-packages/ray/rllib/models/modelv2.py", line 204, in __call__
    restored["obs"] = restore_original_dimensions(
  File "/usr/local/lib/python3.8/dist-packages/ray/rllib/models/modelv2.py", line 424, in restore_original_dimensions
    return _unpack_obs(obs, original_space, tensorlib=tensorlib)
  File "/usr/local/lib/python3.8/dist-packages/ray/rllib/models/modelv2.py", line 452, in _unpack_obs
    if len(obs.shape) < 2 or obs.shape[-1] != prep.shape[0]:
AttributeError: 'list' object has no attribute 'shape'
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by smorad** [comment]
I've narrowed this down to the `forward` call in `attention_net.py:304`. `input_dict['obs']` is a list, not `TensorType`. My understanding is that `input_dict['obs']` should always be `TensorType`.

**Comment by smorad** [comment]
I think this bug is __not__ specific to grtxls, and has to do with how rllib unpacks observations. `AttentionWrapper.forward` is passed *the wrong type* before any attention stuff happens, so it's possible this may cause trouble elsewhere. This is on latest master 8cedd16f4440f5baf8c68d5012896512466c9f6a.

**Comment by signalprime** [comment]
Can confirm it also happens with dictionary observations

**Comment by smorad** [comment]
Fixed in https://github.com/ray-project/ray/pull/14569, thanks Sven :)
