### ISSUE TITLE
autoscaler: SSH should support retries for new nodes

### ISSUE THREAD

**Issue by yaroslavvb** [ray-project/ray#1420]
`ray create_or_update` fails for new nodes with message like this.
Timeout is 60 seconds, but it takes more than 60 seconds for head instance to come up for the first time

```
Successfully installed attrs-17.4.0 cloudpickle-0.5.2 flatbuffers-2015.12.22.1 funcsigs-1.0.2 numpy-1.14.0 pluggy-0.6.0 psutil-5.4.3 py-1.5.2 pytest-3.3.2 ray-0.3.0 redis-2.10.6 setuptools-38.4.0
NodeUpdater: running pip install boto3==1.4.8 on 52.207.221.167...
ssh: connect to host 52.207.221.167 port 22: Operation timed out
NodeUpdater: Error updating Command '['ssh', '-o', 'ConnectTimeout=60s', '-o', 'StrictHostKeyChecking=no', '-i', '/Users/yaroslav/.ssh/ray-autoscaler_2.pem', 'ubuntu@52.207.221.167', "bash --login -c 'set -i && source ~/.bashrc && pip install boto3==1.4.8'"]' returned non-zero exit status 255., see (console) for remote logs
Process NodeUpdaterProcess-1:
Traceback (most recent call last):
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 68, in run
    raise e
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 55, in run
    self.do_update()
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 147, in do_update
    self.ssh_cmd(cmd, verbose=True)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 162, in ssh_cmd
    ], stdout=redirect or self.stdout, stderr=redirect or self.stderr)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh', '-o', 'ConnectTimeout=60s', '-o', 'StrictHostKeyChecking=no', '-i', '/Users/yaroslav/.ssh/ray-autoscaler_2.pem', 'ubuntu@52.207.221.167', "bash --login -c 'set -i && source ~/.bashrc && pip install boto3==1.4.8'"]' returned non-zero exit status 255.
Error: updating 52.207.221.167 failed
```

**Comment by ericl** [comment]
Hmm, it looks like the earlier SSH command did complete (and the autoscaling does wait for a dummy SSH command to return ok before attempting to run actual commands). Wondering how reproducible this is.

Either way we could probably increase the timeout or add a retry.
