### ISSUE TITLE
Failed to load actor due to dependencies not being pickled

### ISSUE THREAD

**Issue by javi-redondo** [ray-project/ray#14284]
### What is the problem?

Seems like dependencies are not getting pickled and then they can't be used within the actor:

```
2021-02-23 18:45:18,104	WARNING worker.py:1034 -- Failed to unpickle actor class 'MyConsumer' for actor ID df5a1a8201000000. Traceback:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ray/function_manager.py", line 496, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
AttributeError: type object 'Consumer' has no attribute 'subscribe'

(pid=128946) 2021-02-23 18:45:18,098	ERROR function_manager.py:498 -- Failed to load actor class MyConsumer.
(pid=128946) Traceback (most recent call last):
(pid=128946)   File "/home/ubuntu/.local/lib/python3.8/site-packages/ray/function_manager.py", line 496, in _load_actor_class_from_gcs
(pid=128946)     actor_class = pickle.loads(pickled_class)
(pid=128946) AttributeError: type object 'Consumer' has no attribute 'subscribe'
2021-02-23 18:45:18,592	ERROR worker.py:980 -- Possible unhandled error from worker: ray::MyConsumer.__init__() (pid=128946, ip=172.31.36.11)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 415, in ray._raylet.execute_task.function_executor
RuntimeError: The actor with name MyConsumer failed to be imported, and so cannot execute this method.
```
Running Ubuntu 20.04, Python 3.8, Ray 1.1.

### Reproduction (REQUIRED)

The code looks as follows:

```python
import ray
from confluent_kafka import Consumer

ray.init()

@ray.remote
class MyConsumer(object):
  def __init__(self, config, source):
    self.c = Consumer(config)
    self.c.subscribe([source])

n = 6
config = {...} # Configs to connect
consumers = [MyConsumer.remote(config, 'my-topic') for _ in range(n)]
```

Moving `from confluent_kafka import Consumer` to `__init__` is a workaround but I believe this should work with the module global import?

**Comment by poutyface** [comment]
I met same issue.
```python
# pickle.load error (global import)
from confluent_kafka import Consumer
consumer = Consumer(..)

# It work (global import)
import confluent_kafka 
consumer = confluent_kafka.Consumer(...)

```

**Comment by vonJJ** [comment]
After move module to __init__, I met another problem:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/function_manager.py", line 493, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
AttributeError: type object 'PyCFuncPtrType' has no attribute '__mul__'

**Comment by rkooo567** [comment]
> AttributeError: type object 'PyCFuncPtrType' has no attribute 'mul'

Hmm, can you show me the code snippet I can run that this is reproducible?

**Comment by vonJJ** [comment]
> > AttributeError: type object 'PyCFuncPtrType' has no attribute 'mul'
> 
> Hmm, can you show me the code snippet I can run that this is reproducible?

Thank you and the issue was solved! It's due to our incorrectly way of importing. We change "from ctypes import *" to "from ctypes import xx ,xxx,..." and it worked. But when testing without ray both ways worked .

**Comment by rkooo567** [comment]
Hmm interesting... cc @suquark do you have any clue? If we add import to `__init__`, isn't import supposed to happen on runtime, so it shouldn't have any difference from importing it from the driver?

**Comment by chris-aeviator** [comment]
I'm always using this form to get around this
```

@ray.remote()
def my_thing:
    import my_dep

job = my_thing.remote()
ray.get(job)
```

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
