### ISSUE TITLE
summary printing fails for missing tags

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#14283]
The logs printing should not cause an error because of tags:

```
2021-02-22 20:29:40,067	INFO monitor.py:118 -- Monitor: Started
2021-02-22 20:29:40,335	INFO autoscaler.py:699 -- StandardAutoscaler: Queue 1 new nodes for launch
2021-02-22 20:29:40,336	INFO node_launcher.py:78 -- NodeLauncher0: Got 1 nodes to launch.
2021-02-22 20:29:40,363	INFO node_launcher.py:78 -- NodeLauncher0: Launching 1 nodes, type default.worker.node.
2021-02-22 20:29:40,381	INFO node_provider.py:435 -- Configuration bypasses Rapid Start; launching node normally.
2021-02-22 20:29:40,410	ERROR autoscaler.py:139 -- StandardAutoscaler: Error during autoscaling.
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 137, in update
    self._update()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 305, in _update
    logger.info(self.info_string())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 791, in info_string
    autoscaler_summary = self.summary()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 761, in summary
    status = node_tags[TAG_RAY_NODE_STATUS]
KeyError: 'ray-node-status'
2021-02-22 20:29:40,458	ERROR monitor.py:271 -- Error in monitor loop
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 269, in run
    self._run()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 204, in _run
    "autoscaler_report"] = self.autoscaler.summary()._asdict()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 761, in summary
    status = node_tags[TAG_RAY_NODE_STATUS]
KeyError: 'ray-node-status'
2021-02-22 20:29:40,459	ERROR autoscaler.py:724 -- StandardAutoscaler: kill_workers triggered
2021-02-22 20:29:40,471	ERROR autoscaler.py:729 -- StandardAutoscaler: terminated 0 node(s)
2021-02-22 20:29:40,472	INFO monitor.py:250 -- Monitor: Exception caught. Taking down workers...
2021-02-22 20:44:46,682	WARNING node_provider.py:509 -- No room in pool; node will not be added to pool.

```
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by wuisawesome** [comment]
I'll call this an enhancement since we've always just expected node providers to have read-after-write consistency :p
