### ISSUE TITLE
[autoscaler] InstanceMarketOptions not passing parameter validation

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#1431]
### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: Source
- **Ray version**: .. 
- **Python version**: 3.6.3
- **Exact command to reproduce**:

### Describe the problem
I tried using the below YAML but I was given the following error:

```
Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/monitor.py", line 676, in <module>
    monitor.run()
  File "/home/ubuntu/ray/python/ray/monitor.py", line 608, in run
    self.autoscaler.update()
  File "/home/ubuntu/ray/python/ray/autoscaler/autoscaler.py", line 333, in update
    raise e
  File "/home/ubuntu/ray/python/ray/autoscaler/autoscaler.py", line 325, in update
    self._update()
  File "/home/ubuntu/ray/python/ray/autoscaler/autoscaler.py", line 387, in _update
    min(self.max_concurrent_launches, target_num - len(nodes)))
  File "/home/ubuntu/ray/python/ray/autoscaler/autoscaler.py", line 534, in launch_new_node
    count)
  File "/home/ubuntu/ray/python/ray/autoscaler/aws/node_provider.py", line 109, in create_node
    self.ec2.create_instances(**conf)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/botocore/client.py", line 579, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/botocore/client.py", line 634, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "InstanceMarketOptions", must be one of: BlockDeviceMappings, ImageId, InstanceType, Ipv6AddressCount, Ipv6Addresses, KernelId, KeyName, MaxCount, MinCount, Monitoring, Placement, RamdiskId, SecurityGroupIds, SecurityGroups, SubnetId, UserData, AdditionalInfo, ClientToken, DisableApiTermination, DryRun, EbsOptimized, IamInstanceProfile, InstanceInitiatedShutdownBehavior, NetworkInterfaces, PrivateIpAddress, ElasticGpuSpecification, TagSpecifications
```

### Source code / logs

```
# An unique identifier for the head node and workers of this cluster.
cluster_name: default

# The minimum number of workers nodes to launch in addition to the head
# node. This number should be >= 0.
min_workers: 10

# The maximum number of workers nodes to launch in addition to the head
# node. This takes precedence over min_workers.
max_workers: 10

# The autoscaler will scale up the cluster to this target fraction of resource
# usage. For example, if a cluster of 10 nodes is 100% busy and
# target_utilization is 0.8, it would resize the cluster to 13. This fraction
# can be decreased to increase the aggressiveness of upscaling.
target_utilization_fraction: 0.8

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 5

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-east-2
    availability_zone: us-east-2a

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
# By default Ray creates a new private keypair, but you can also use your own.
# If you do so, make sure to also set "KeyName" in the head and worker node
# configurations below.
    # ssh_private_key: ~/Research/ec2/BA.pem

# Provider-specific config for the head node, e.g. instance type. By default
# Ray will auto-configure unspecified fields such as SubnetId and KeyName.
# For more documentation on available fields, see:
# http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances
head_node:
    InstanceType: m4.2xlarge
    ImageId: ami-5b371d3e
    # KeyName: BA

    # Additional options in the boto docs.

# Provider-specific config for worker nodes, e.g. instance type. By default
# Ray will auto-configure unspecified fields such as SubnetId and KeyName.
# For more documentation on available fields, see:
# http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances
worker_nodes:
    InstanceType: m4.xlarge
    ImageId: ami-5b371d3e
    # KeyName: BA

    # Run workers on spot by default. Comment this out to use on-demand.
    InstanceMarketOptions:
        MarketType: spot
        # Additional options can be found in the boto docs, e.g.
        #   SpotOptions:
        #       MaxPrice: MAX_HOURLY_PRICE

    # Additional options in the boto docs.

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {
#    "/path1/on/remote/machine": "/path1/on/local/machine",
#    "/path2/on/remote/machine": "/path2/on/local/machine",
}

# List of shell commands to run to set up nodes.
setup_commands: []
    # # Install basics.
    # - sudo apt-get update
    # - sudo apt-get install -y cmake pkg-config build-essential autoconf curl libtool unzip python
    # # Install Anaconda.
    # - wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh || true
    # - bash Anaconda3-5.0.1-Linux-x86_64.sh -b -p $HOME/anaconda3 || true
    # - echo 'export PATH="$HOME/anaconda3/bin:$PATH"' >> ~/.bashrc
    # # Build Ray.
    # - git clone https://github.com/ray-project/ray || true
    # - pip install -U cloudpickle boto3==1.4.8
    # - cd ray/python; python setup.py develop

# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - ray start --head --redis-port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - ray start --redis-address=$RAY_HEAD_IP:6379
```

cc: @ericl

**Comment by ericl** [comment]
You need to upgrade your boto. There's already a or that adds that check

**Comment by richardliaw** [comment]
I see - would be nice to mark that as a required setup command.
