### ISSUE TITLE
[autoscaler][dashboard] Ray up aws/defaults.yaml fails due to dashboard error

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#14363]
### What is the problem?
Running
`ray up aws/defaults.yaml` leads to the following error
```
  [7/7] Starting the Ray runtime
Did not find any active Ray processes.
Shared connection to 52.12.95.126 closed.
bash: ulimit: open files: cannot modify limit: Operation not permitted
Local node IP: 172.31.30.248
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/scripts/scripts.py", line 1690, in main
    return cli()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/scripts/scripts.py", line 563, in start
    ray_params, head=True, shutdown_at_exit=block, spawn_reaper=block)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/node.py", line 235, in __init__
    self.start_head_processes()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/node.py", line 874, in start_head_processes
    self.start_dashboard(require_dashboard=False)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/node.py", line 710, in start_dashboard
    port=self._ray_params.dashboard_port)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/_private/services.py", line 1221, in start_dashboard
    raise Exception("Failed to start the dashboard"
Exception: Failed to start the dashboard, return code 1.
Shared connection to 52.12.95.126 closed.
  New status: update-failed
  !!!
  SSH command failed.
  !!!

  Failed to setup head node.
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
Using current master Ray locally.
Version of Ray installed on head node is nightly build at 4:30 PM Pacific 2/25/2021

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
I was able to reproduce this. Investigating

**Comment by simon-mo** [comment]
Dashboard process failed to start because:
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/new_dashboard/dashboard.py", line 26, in <module>
    from ray.metrics_agent import PrometheusServiceDiscoveryWriter
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/metrics_agent.py", line 25, in <module>
    from ray import prometheus_exporter
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/prometheus_exporter.py", line 18, in <module>
    from opencensus.common.transports import sync
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/opencensus/common/transports/sync.py", line 16, in <module>
    from opencensus.trace import execution_context
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/opencensus/trace/__init__.py", line 15, in <module>
    from opencensus.trace.span import Span
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/opencensus/trace/span.py", line 32, in <module>
    from opencensus.trace import status as status_module
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/opencensus/trace/status.py", line 15, in <module>
    from google.rpc import code_pb2
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/google/rpc/code_pb2.py", line 36, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

I have to set the stdout_file and stderr_file not to subprocess.DEVNULL to reveal this error. @rkooo567 I think this reveal a weakness of the ray logging stack because ray process startup error is silently swallowed. 
https://github.com/ray-project/ray/blob/34a9714dda012241cdf035c8bbad2ebd60882aad/python/ray/node.py#L704-L705

**Comment by simon-mo** [comment]
It's the environment issue, please update the the protobuf:
```
ubuntu@ip-172-31-51-86:~$ python -m pip install -U protobuf
Collecting protobuf
  Downloading protobuf-3.15.3-cp36-cp36m-manylinux1_x86_64.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 7.8 MB/s
Requirement already satisfied, skipping upgrade: six>=1.9 in ./anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages (from protobuf) (1.14.0)
ERROR: tensorflow-serving-api 1.15.0 requires tensorflow~=1.15.0, which is not installed.
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.12.2
    Uninstalling protobuf-3.12.2:
      Successfully uninstalled protobuf-3.12.2
Successfully installed protobuf-3.15.3
```
After the protobuf is updated (make sure you are using the right conda environment by `source ~/.bashrc` or `conda activate tensorflow_p36`), `ray start --head` will work.
