### ISSUE TITLE
slurmstepd: error: Detected 8 oom-kill event(s) in step 59137890.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

### ISSUE THREAD

**Issue by StaminaTang** [ray-project/ray#14394]
### What is the problem?

  File "/home/user/.local/lib/python3.6/site-packages/ray/tune/tune.py", line 330, in run_experiments
    raise_on_failed_trial=raise_on_failed_trial)
  File "/home/user/.local/lib/python3.6/site-packages/ray/tune/tune.py", line 272, in run
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [seed:5591])
slurmstepd: error: Detected 8 oom-kill event(s) in step 59137890.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

The error
 File "/home/user/.local/lib/python3.6/site-packages/ray/worker.py", line 2189, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray =0.7.1(I have tried to update, but it says sth should be trainable, so I degrade to the version that the paper author used)
python=3.6.5
tensorflow-estimator     1.14.0
tensorflow-gpu           1.14.0
tensorflow-probability   0.7.0

### Reproduction (REQUIRED)
I have run the algorithm on gpu for around a whole night. When I got up I saw it raises the time-limit problem... But when I try to submit it again, this problem appears and I tried a whole day without making progress. So acturally I don't even know why this happend. 

I tried the sbatch with or without --mem, but this problem still remains.
I have checked the disk and still around 80G left.

**Comment by StaminaTang** [comment]
2021-02-27 03:01:56,997	ERROR trial_runner.py:487 -- Error processing event.
Traceback (most recent call last):
  File "/home/usr/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 436, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/usr/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 323, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/usr/.local/lib/python3.6/site-packages/ray/worker.py", line 2189, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
2021-02-27 03:01:57,003	INFO ray_trial_executor.py:187 -- Destroying actor for trial seed:9815. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2021-02-27 03:01:57,004	ERROR worker.py:1668 -- A worker died or was killed while executing task 580930454afb9f584603b8386bb19fe5.
2021-02-27 03:01:57,006	INFO trial_runner.py:524 -- Attempting to recover trial state from last checkpoint.
2021-02-27 03:03:16,107	ERROR worker.py:1668 -- A worker died or was killed while executing task e973c284d605eecd20acf88928230413.
2021-02-27 03:03:16,108	ERROR trial_runner.py:487 -- Error processing event.
Traceback (most recent call last):
  File "/home/usr/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 436, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/usr/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 323, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/usr/.local/lib/python3.6/site-packages/ray/worker.py", line 2189, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
2021-02-27 03:03:16,113	INFO ray_trial_executor.py:187 -- Destroying actor for trial seed:9815. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2021-02-27 03:03:16,115	INFO trial_runner.py:524 -- Attempting to recover trial state from last checkpoint.

**Comment by StaminaTang** [comment]
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init()
2021-02-27 03:09:44,371 INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2021-02-27_03-09-44_371497_24314/logs.
2021-02-27 03:09:44,480 INFO services.py:409 -- Waiting for redis server at 127.0.0.1:23409 to respond...
2021-02-27 03:09:44,605 INFO services.py:409 -- Waiting for redis server at 127.0.0.1:10664 to respond...
2021-02-27 03:09:44,607 INFO services.py:806 -- Starting Redis shard with 10.0 GB max memory.
2021-02-27 03:09:44,638 INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2021-02-27_03-09-44_371497_24314/logs.
2021-02-27 03:09:44,639 WARNING services.py:1294 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
2021-02-27 03:09:44,639 INFO services.py:1442 -- Starting the Plasma object store with 20.0 GB memory using /dev/shm.
{'node_ip_address': '10.10.100.4', 'redis_address': '10.10.100.4:23409', 'object_store_address': '/tmp/ray/session_2021-02-27_03-09-44_371497_24314/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2021-02-27_03-09-44_371497_24314/sockets/raylet', 'webui_url': None, 'session_dir': '/tmp/ray/session_2021-02-27_03-09-44_371497_24314'}
>>> _ = ray.get([ray.put(str(i)) for i in range(1000)])
>>>

**Comment by StaminaTang** [comment]
/.local/lib/python3.6/site-packages/ray/tune/tune.py", line 272, in run
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [seed:6462])

**Comment by richardliaw** [comment]
Do you have a good idea as to how to reproduce this issue?

**Comment by BUGLI27** [comment]
Set `--mem-per-cpu=<more memory>` could help
