### ISSUE TITLE
RLlib default example doesn't work with tensorflow 2.4.1 and numpy 1.20.1

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#14410]
Taking the example from https://ray.io/ and running it, it appears to fail with 

```
(pid=518) NotImplementedError: Cannot convert a symbolic Tensor (default_policy/cond/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
```

This is with

```
In [1]: import tensorflow as tf                                                 
tf.__
In [2]: import numpy as np                                                      

In [3]: tf.__version__                                                          
Out[3]: '2.4.1'

In [4]: np.__version__                                                          
Out[4]: '1.20.1'
```

Note that I also tried with `tf=='2.1.0'` and `np=='1.18.2'` and that succeeded.

**Script for reproduction**

```python
import gym
from gym.spaces import Discrete, Box
from ray import tune
class SimpleCorridor(gym.Env):
    def __init__(self, config):
        self.end_pos = config["corridor_length"]
        self.cur_pos = 0
        self.action_space = Discrete(2)
        self.observation_space = Box(0.0, self.end_pos, shape=(1, ))
    def reset(self):
        self.cur_pos = 0
        return [self.cur_pos]
    def step(self, action):
        if action == 0 and self.cur_pos > 0:
            self.cur_pos -= 1
        elif action == 1:
            self.cur_pos += 1
        done = self.cur_pos >= self.end_pos
        return [self.cur_pos], 1 if done else 0, done, {}
tune.run(
    "PPO",
    config={
        "env": SimpleCorridor,
        "num_workers": 4,
        "env_config": {"corridor_length": 5}})
```

**Full output below.**

```
(base) rkn@Roberts-MBP ~ % ipython
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

   ...: from gym.spaces import Discrete, Box 
   ...: from ray import tune 
   ...: class SimpleCorridor(gym.Env): 
   ...:     def __init__(self, config): 
   ...:         self.end_pos = config["corridor_length"] 
   ...:         self.cur_pos = 0 
   ...:         self.action_space = Discrete(2) 
   ...:         self.observation_space = Box(0.0, self.end_pos, shape=(1, )) 
   ...:     def reset(self): 
   ...:         self.cur_pos = 0 
   ...:         return [self.cur_pos] 
   ...:     def step(self, action): 
   ...:         if action == 0 and self.cur_pos > 0: 
   ...:             self.cur_pos -= 1 
   ...:         elif action == 1: 
   ...:             self.cur_pos += 1 
   ...:         done = self.cur_pos >= self.end_pos 
   ...:         return [self.cur_pos], 1 if done else 0, done, {} 
   ...: tune.run( 
   ...:     "PPO", 
   ...:     config={ 
   ...:         "env": SimpleCorridor, 
   ...:         "num_workers": 4, 
   ...:         "env_config": {"corridor_length": 5}})                          
2021-02-28 17:48:39,088	INFO services.py:1228 -- View the Ray dashboard at http://127.0.0.1:8265
WARNING:tensorflow:From /Users/rkn/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2021-02-28 17:48:53,608	WARNING trial.py:335 -- Passing `extra_*` resource requirements to `resources_per_trial` is deprecated. Please use a `PlacementGroupFactory` object to define your resource requirements instead.
== Status ==
Memory usage on this node: 14.1/64.0 GiB
Using FIFO scheduling algorithm.
Resources requested: 5/16 CPUs, 0/0 GPUs, 0.0/30.52 GiB heap, 0.0/10.5 GiB objects
Result logdir: /Users/rkn/ray_results/PPO
Number of trials: 1/1 (1 RUNNING)
+--------------------------------+----------+-------+
| Trial name                     | status   | loc   |
|--------------------------------+----------+-------|
| PPO_SimpleCorridor_47296_00000 | RUNNING  |       |
+--------------------------------+----------+-------+


(pid=2894) WARNING:tensorflow:From /Users/rkn/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=2894) Instructions for updating:
(pid=2894) non-resource variables are not supported in the long term
(pid=2894) 2021-02-28 17:48:56,101	INFO trainer.py:620 -- Tip: set framework=tfe or the --eager flag to enable TensorFlow eager execution
(pid=2894) 2021-02-28 17:48:56,101	INFO trainer.py:647 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=2892) WARNING:tensorflow:From /Users/rkn/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=2892) Instructions for updating:
(pid=2892) non-resource variables are not supported in the long term
(pid=2902) WARNING:tensorflow:From /Users/rkn/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=2902) Instructions for updating:
(pid=2902) non-resource variables are not supported in the long term
(pid=2901) WARNING:tensorflow:From /Users/rkn/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=2901) Instructions for updating:
(pid=2901) non-resource variables are not supported in the long term
(pid=2897) WARNING:tensorflow:From /Users/rkn/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=2897) Instructions for updating:
(pid=2897) non-resource variables are not supported in the long term
2021-02-28 17:48:58,893	ERROR trial_runner.py:727 -- Trial PPO_SimpleCorridor_47296_00000: Error processing event.
Traceback (most recent call last):
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 697, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 678, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1428, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(NotImplementedError): ray::PPO.train_buffered() (pid=2894, ip=192.168.1.104)
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 487, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 497, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 444, in ray._raylet.execute_task.function_executor
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 107, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 490, in __init__
    super().__init__(config, logger_creator)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 97, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 658, in setup
    self._init(self.config, self.env_creator)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 139, in _init
    num_workers=self.config["num_workers"])
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 734, in _make_workers
    logdir=self.logdir)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 81, in __init__
    lambda p, pid: (pid, p.observation_space, p.action_space)))
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
ray.exceptions.RayTaskError(NotImplementedError): ray::RolloutWorker.foreach_policy() (pid=2902, ip=192.168.1.104)
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 487, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 497, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 444, in ray._raylet.execute_task.function_executor
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 484, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1126, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/policy/tf_policy_template.py", line 238, in __init__
    obs_include_prev_action_reward=obs_include_prev_action_reward)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/policy/dynamic_tf_policy.py", line 316, in __init__
    explore=explore)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/exploration/stochastic_sampling.py", line 73, in get_exploration_action
    timestep, explore)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/exploration/stochastic_sampling.py", line 84, in _get_tf_exploration_action_op
    false_fn=lambda: action_dist.sample(),
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1396, in cond_for_tf_v2
    return cond(pred, true_fn=true_fn, false_fn=false_fn, strict=True, name=name)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 538, in new_func
    return func(*args, **kwargs)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1230, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1066, in BuildCondBranch
    original_result = fn()
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/exploration/stochastic_sampling.py", line 83, in <lambda>
    explore=True)[0]),
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/exploration/random.py", line 126, in get_tf_exploration_action_op
    logp = tf.zeros(shape=(batch_size, ), dtype=tf.float32)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2819, in wrapped
    tensor = fun(*args, **kwargs)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2868, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2804, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 6, in prod
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3031, in prod
    keepdims=keepdims, initial=initial, where=where)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 855, in __array__
    " a NumPy call, which is not supported".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (default_policy/cond/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
Result for PPO_SimpleCorridor_47296_00000:
  {}
  
== Status ==
Memory usage on this node: 14.4/64.0 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/16 CPUs, 0/0 GPUs, 0.0/30.52 GiB heap, 0.0/10.5 GiB objects
Result logdir: /Users/rkn/ray_results/PPO
Number of trials: 1/1 (1 ERROR)
+--------------------------------+----------+-------+
| Trial name                     | status   | loc   |
|--------------------------------+----------+-------|
| PPO_SimpleCorridor_47296_00000 | ERROR    |       |
+--------------------------------+----------+-------+
Number of errored trials: 1
+--------------------------------+--------------+-------------------------------------------------------------------------------------------+
| Trial name                     |   # failures | error file                                                                                |
|--------------------------------+--------------+-------------------------------------------------------------------------------------------|
| PPO_SimpleCorridor_47296_00000 |            1 | /Users/rkn/ray_results/PPO/PPO_SimpleCorridor_47296_00000_0_2021-02-28_17-48-53/error.txt |
+--------------------------------+--------------+-------------------------------------------------------------------------------------------+

== Status ==
Memory usage on this node: 14.4/64.0 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/16 CPUs, 0/0 GPUs, 0.0/30.52 GiB heap, 0.0/10.5 GiB objects
Result logdir: /Users/rkn/ray_results/PPO
Number of trials: 1/1 (1 ERROR)
+--------------------------------+----------+-------+
| Trial name                     | status   | loc   |
|--------------------------------+----------+-------|
| PPO_SimpleCorridor_47296_00000 | ERROR    |       |
+--------------------------------+----------+-------+
Number of errored trials: 1
+--------------------------------+--------------+-------------------------------------------------------------------------------------------+
| Trial name                     |   # failures | error file                                                                                |
|--------------------------------+--------------+-------------------------------------------------------------------------------------------|
| PPO_SimpleCorridor_47296_00000 |            1 | /Users/rkn/ray_results/PPO/PPO_SimpleCorridor_47296_00000_0_2021-02-28_17-48-53/error.txt |
+--------------------------------+--------------+-------------------------------------------------------------------------------------------+

---------------------------------------------------------------------------
TuneError                                 Traceback (most recent call last)
<ipython-input-1-5232069b1640> in <module>
     23         "env": SimpleCorridor,
     24         "num_workers": 4,
---> 25         "env_config": {"corridor_length": 5}})

~/opt/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py in run(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial, callbacks, loggers, ray_auto_init, run_errored_only, global_checkpoint_period, with_server, upload_dir, sync_to_cloud, sync_to_driver, sync_on_checkpoint, _remote)
    541     if incomplete_trials:
    542         if raise_on_failed_trial and not state[signal.SIGINT]:
--> 543             raise TuneError("Trials did not complete", incomplete_trials)
    544         else:
    545             logger.error("Trials did not complete: %s", incomplete_trials)

TuneError: ('Trials did not complete', [PPO_SimpleCorridor_47296_00000])
```

@sven1977

**Comment by sven1977** [comment]
Working on:
tf==2.0.4 + numpy==1.19.5
tf==2.4.1 + numpy==1.19.5

Tf is also saying:
`tensorflow 2.4.1 has requirement numpy~=1.19.2, but you'll have numpy 1.20.1 which is incompatible.`
