### ISSUE TITLE
[autoscaler] Error message not being cleared when autoscaler recovers

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#14494]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

Sometimes the autoscaler runs into exceptions that are not serious (for example race conditions on startup). We intentionally put all exceptions into `DEBUG_AUTOSCALING_ERROR`. 

The issue is that many of these exceptions are temporary, but the field isn't cleared afterwards which is very misleading.

For example, there seems to be a race condition on startup with the first grpc request, which results in this error message:

```
======== Autoscaler status: 2021-03-04 19:52:06.095258 ========
Node status
---------------------------------------------------------------
Healthy:
 1 head_node
 64 worker
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------

Usage:
 0.0/2400.0 CPU
 0.00/3600.586 GiB memory
 0.00/1492.480 GiB object_store_memory

Demands:
 (no resource demands)
The autoscaler failed with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 274, in run
    self._run()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 167, in _run
    self.update_load_metrics()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 132, in update_load_metrics
    request, timeout=4)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1614887161.311939784","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5396,"referenced_errors":[{"created":"@1614887161.311937249","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>

[0mLoaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
Fetched IP: 34.218.236.185
```

In this state, it looks like the autoscaler is broken, but in reality it functions completely fine. 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
Isn't this fixed in nightlies (it is only written on monitor death) cc @clarkzinzow

**Comment by clarkzinzow** [comment]
It should be cleared in current master, I'll check it that out.

**Comment by wuisawesome** [comment]
when was this fixed? i've run into it on pretty recent nightlies (or branches that aren't too stale)

**Comment by clarkzinzow** [comment]
@wuisawesome `DEBUG_AUTOSCALING_ERROR` _should_ be unset when the monitor restarts via [this commit](https://github.com/ray-project/ray/commit/708fb6b06150bf8b881924c52c1a68e969dc59b0#diff-f53bc0455e31fe9f401c121cd42fed36aca0ca3f862c8b88588b6a133da9dc64R267-R269), merged 12 days ago.

**Comment by AmeerHajAli** [comment]
@clarkzinzow @wuisawesome should we close this?

**Comment by wuisawesome** [comment]
I think I still see this sometimes when I restart the head node on a cluster. I don't have a reliable reproduction though. 

Maybe we can leave it open as a p2?

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
