### ISSUE TITLE
RLLib - AttributeError: module 'ray' has no attribute 'worker'

### ISSUE THREAD

**Issue by XavierGeerinck** [ray-project/ray#14493]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

* Ray 2.0.0.dev0 Linux (through WSL 2)
* Ray 1.2.0 Linux (through WSL 2)
* Ray 1.2.0 Windows

After installing Ray I am not able to run it on Linux or Windows on both latest and 1.2.0 release. The error as shown below keeps popping up.

**Error:**

```bash
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from ray import tune
  File "/home/xavier/.pyenv/versions/3.8.6/lib/python3.8/site-packages/ray/tune/__init__.py", line 2, in <module>
    from ray.tune.tune import run_experiments, run
  File "/home/xavier/.pyenv/versions/3.8.6/lib/python3.8/site-packages/ray/tune/tune.py", line 12, in <module>
    from ray.tune.analysis import ExperimentAnalysis
  File "/home/xavier/.pyenv/versions/3.8.6/lib/python3.8/site-packages/ray/tune/analysis/__init__.py", line 1, in <module>
    from ray.tune.analysis.experiment_analysis import ExperimentAnalysis, Analysis
  File "/home/xavier/.pyenv/versions/3.8.6/lib/python3.8/site-packages/ray/tune/analysis/experiment_analysis.py", line 21, in <module>
    from ray.tune.trial import Trial
  File "/home/xavier/.pyenv/versions/3.8.6/lib/python3.8/site-packages/ray/tune/trial.py", line 20, in <module>
    from ray.tune.registry import get_trainable_cls, validate_trainable
  File "/home/xavier/.pyenv/versions/3.8.6/lib/python3.8/site-packages/ray/tune/registry.py", line 151, in <module>
    ray.worker._post_init_hooks.append(_global_registry.flush_values)
AttributeError: module 'ray' has no attribute 'worker'
```

### Reproduction (REQUIRED)

```bash
pip install tensorflow

# ray 1.2.0
pip install ray

# ray 2.0.0.dev0
pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by mattip** [comment]
This seems like it may be due to a circular import somewhere. I see this happens in `from ray import tune`. What is in `test.py` before that? Do you have any environment variables that may be pre-loading other packages (i.e. what does `> set PYTHON` print out on windows)?

Can you try again with the recent release of 1.9.1?
