### ISSUE TITLE
Saving checkpoints while using a cluster?

### ISSUE THREAD

**Issue by Carterbouley** [ray-project/ray#14506]
I am trying to save ray checkpoints while spinning up a cluster in Azure.

I am getting the following error, and no checkpoints are being saved:
```
2021-03-05 14:43:08,637	ERROR trial_runner.py:539 -- Trial PPO_Battery_00000: Error handling checkpoint /mnt/batch/tasks/shared/LS_root/jobs/rl_test/azureml/battery-multi-node-day2-3_1614954444_cde584fe_head/mounts/workspaceblobstore/azureml/battery-multi-node-day2-3_1614954444_cde584fe_head/local_dir/PPO/PPO_Battery_0_2021-03-05_14-36-29vg7l7j5a/checkpoint_131/checkpoint-131
Traceback (most recent call last):
  File "/azureml-envs/azureml_167f4dd4c85f61389bb53e00383dafbe/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 535, in _process_trial_save
    trial.on_checkpoint(trial.saving_to)
  File "/azureml-envs/azureml_167f4dd4c85f61389bb53e00383dafbe/lib/python3.6/site-packages/ray/tune/trial.py", line 440, in on_checkpoint
    self, checkpoint.value))
ray.tune.error.TuneError: Trial PPO_Battery_00000: Checkpoint path /mnt/batch/tasks/shared/LS_root/jobs/rl_test/azureml/battery-multi-node-day2-3_1614954444_cde584fe_head/mounts/workspaceblobstore/azureml/battery-multi-node-day2-3_1614954444_cde584fe_head/local_dir/PPO/PPO_Battery_0_2021-03-05_14-36-29vg7l7j5a/checkpoint_131/checkpoint-131 not found after successful sync down.
```

Does anyone know how I can save checkpoints while on a remote machine?

**Comment by richardliaw** [comment]
Is this a shared mount across all nodes? You may want to consider disabling syncing in that case.
