### ISSUE TITLE
Ray Kubernetes Cluster Launcher failing with upscaling_speed?

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#14539]
With the default Ray Kubernetes autoscaler yaml, https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/kubernetes/example-full.yaml, we're seeing this error:

```
Original exception was:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 365, in <module>
    redis_password=args.redis_password)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 53, in __init__
    self.load_metrics)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/autoscaler.py", line 71, in __init__
    self.reset(errors_fatal=True)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/autoscaler.py", line 322, in reset
    raise e
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/autoscaler.py", line 293, in reset
    validate_config(new_config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/util.py", line 59, in validate_config
    raise e from None
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/util.py", line 57, in validate_config
    jsonschema.validate(config, schema)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('upscaling_speed' was unexpected)
```

cc @DmitriGekhtman @tgaddair

**Comment by DmitriGekhtman** [comment]
It looks like the version of Ray on the head node is old (it doesn't know what `upscaling_speed` is )
Make sure that the `rayproject/ray:nightly` image is getting freshly pulled.

**Comment by DmitriGekhtman** [comment]
If the issues persist, could you provide version info?
I'm not able to replicate with current master installed locally and freshly pulled nightly image on head node.

**Comment by tgaddair** [comment]
Thanks @DmitriGekhtman, it was indeed old. For some reason the version of Ray in the nightly image I had read as 1.0.0. Thanks!
