### ISSUE TITLE
Ray client fails to connect localy on 2.0.0.dev0 on kubernetes cluster both with ray cluster launcher and kubernetes operator

### ISSUE THREAD

**Issue by ddominet** [ray-project/ray#14543]
******Hi i'm currently testing deployment of ray framework in kubernetes enviroment. I have tested from local node, while port forwarding. I have tried both operator and launcher without any progress.
Python version is 3.7.7 on both head and kubernetes node. Ray works fine while running scripts on head and via ray submit. Could you please help out ?******

//error below=>
```
The autoscaler failed with the following error:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f645614fa90>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 274, in run
    self._run()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/monitor.py", line 179, in _run
    "autoscaler_report"] = self.autoscaler.summary()._asdict()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 737, in summary
    all_node_ids = self.provider.non_terminated_nodes(tag_filters={})
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kubernetes/node_provider.py", line 51, in non_terminated_nodes
    label_selector=label_selector)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 15302, in list_namespaced_pod
    return self.list_namespaced_pod_with_http_info(namespace, **kwargs)  # noqa: E501
  File "/home/ray/anaconda3/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 15427, in list_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 377, in request
    headers=headers)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/kubernetes/client/rest.py", line 243, in GET
    query_params=query_params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/kubernetes/client/rest.py", line 216, in request
    headers=headers)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/request.py", line 76, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 767, in urlopen
    **response_kw
  File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 767, in urlopen
    **response_kw
  File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 767, in urlopen
    **response_kw
  File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.43.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/ray/pods?fieldSelector=status.phase%21%3DFailed%2Cstatus.phase%21%3DUnknown%2Cstatus.phase%21%3DSucceeded%2Cstatus.phase%21%3DTerminating&labelSelector=ray-cluster-name%3Dexample-cluster (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f645614fa90>: Failed to establish a new connection: [Errno 111] Connection refused'))

{'num_clients': 1, 'python_version': '3.7.7', 'ray_version': '2.0.0.dev0', 'ray_commit': '2da58bb0214644177c3f9a9c59d03cc5fa0d1c47', 'protocol_version': '2020-02-22'}

```

**Comment by zhe-thoughts** [comment]
Most likely this is no longer valid. But @AmeerHajAli is it OK to assign to you to validate (you can delegate). Thanks

**Comment by DmitriGekhtman** [comment]
We've transitioned to a new recommended deployment stack for Ray on Kubernetes.
You can read about it here: https://docs.ray.io/en/latest/cluster/kubernetes/index.html
Let us know if you still encounter issues.
