### ISSUE TITLE
[tune] tune does not work with imported functions on Ray client

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#14573]
Latest master.

Given two files:

`a.py`
```
import ray

ray.util.connect("localhost:10001")

from b import run_train

run_train()
```

`b.py`
```
from ray import tune

def b_func(config):
    return 4

def run_train():
    return tune.run(
        b_func)
```

Start cluster with `ray start --head`.

Output:

```
Traceback (most recent call last):
  File "/Users/kai/coding/sandbox/tune-modules/a.py", line 9, in <module>
    run_train()
  File "/Users/kai/coding/sandbox/tune-modules/b.py", line 8, in run_train
    tune.with_parameters(b_func, val=4))
  File "/Users/kai/coding/ray/python/ray/tune/tune.py", line 345, in run
    _remote=False))
  File "/Users/kai/coding/ray/python/ray/remote_function.py", line 103, in _remote_proxy
    return self._remote(args=args, kwargs=kwargs)
  File "/Users/kai/coding/ray/python/ray/remote_function.py", line 204, in _remote
    name=name)
  File "/Users/kai/coding/ray/python/ray/_private/client_mode_hook.py", line 72, in client_mode_convert_function
    return client_func._remote(in_args, in_kwargs, **kwargs)
  File "/Users/kai/coding/ray/python/ray/util/client/common.py", line 102, in _remote
    return self.options(**option_args).remote(*args, **kwargs)
  File "/Users/kai/coding/ray/python/ray/util/client/common.py", line 279, in remote
    return return_refs(ray.call_remote(self, *args, **kwargs))
  File "/Users/kai/coding/ray/python/ray/util/client/api.py", line 96, in call_remote
    return self.worker.call_remote(instance, *args, **kwargs)
  File "/Users/kai/coding/ray/python/ray/util/client/worker.py", line 293, in call_remote
    return self._call_schedule_for_task(task)
  File "/Users/kai/coding/ray/python/ray/util/client/worker.py", line 305, in _call_schedule_for_task
    raise cloudpickle.loads(ticket.error)
ModuleNotFoundError: No module named 'b'
```

The above code works when using `ray.init(address="auto")` instead of the ray client

**Comment by krfricke** [comment]
cc @ericl

**Comment by krfricke** [comment]
Ah great, would be great to get an update once this is fixed (this is a blocker for progress on the platform prototype)

**Comment by richardliaw** [comment]
Would it be possible to just bake everything into the same file?

**Comment by ericl** [comment]
You have to upload that code with `file_mounts` or other way to the cluster at the moment (this is just the way Python serialization works).

The work we have will not change this, just add a slightly easier mechanism.

**Comment by krfricke** [comment]
Hm, it is weird though that it does work without the Ray client (the trainable is still serialized and sent to the cluster, right?)

Unfortunately we're using the Ray Kubernetes operator, so not sure how to best go about this. I guess for demo purposes I might be able to push the local code to the container image we're using.
