### ISSUE TITLE
[rllib] Assertion error when using SAC

### ISSUE THREAD

**Issue by astronauti** [ray-project/ray#14602]
### What is the problem?
Assertion error when using SAC-Agent instead of PPO-Agent. Script is working on Windows, but not on Cent OS 7. Tensorflow probability is installed

`Traceback (most recent call last):
  File "script.py", line 74, in <module>
    Reinforcement.startTraining(disableOutput=disableOutput)
  File "/libs/Reinforcement.py", line 73, in startTraining
    self.initTrainer() #trainer initialisieren mit neuer config
  File "/libs/Reinforcement.py", line 44, in initTrainer
    self.agent = sac.SACTrainer(env=self.envTrainer, config=self.config)
  File "/opt/ohpc/pub/apps/conda/envs/env/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 107, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/opt/ohpc/pub/apps/conda/envs/env/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 486, in __init__
    super().__init__(config, logger_creator)
  File "/opt/ohpc/pub/apps/conda/envs/env/lib/python3.8/site-packages/ray/tune/trainable.py", line 97, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/opt/ohpc/pub/apps/conda/envs/env/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 654, in setup
    self._init(self.config, self.env_creator)
  File "/opt/ohpc/pub/apps/conda/envs/env/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 134, in _init
    self.workers = self._make_workers(
  File "/opt/ohpc/pub/apps/conda/envs/env/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 725, in _make_workers
    return WorkerSet(
  File "/opt/ohpc/pub/apps/conda/envs/env/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 79, in __init__
    remote_spaces = ray.get(self.remote_workers(
  File "/opt/ohpc/pub/apps/conda/envs/env/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/opt/ohpc/pub/apps/conda/envs/env/lib/python3.8/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): [36mray::RolloutWorker.foreach_policy()[39m (pid=356653, ip=192.168.1.31)
  File "python/ray/_raylet.pyx", line 439, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 473, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 476, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor

  File "/opt/ohpc/pub/apps/conda/envs/env/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 477, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/opt/ohpc/pub/apps/conda/envs/env/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1108, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/opt/ohpc/pub/apps/conda/envs/env/lib/python3.8/site-packages/ray/rllib/policy/tf_policy_template.py", line 214, in __init__
    DynamicTFPolicy.__init__(
  File "/opt/ohpc/pub/apps/conda/envs/env/lib/python3.8/site-packages/ray/rllib/policy/dynamic_tf_policy.py", line 286, in __init__
    action_dist = dist_class(dist_inputs, self.model)
  File "/opt/ohpc/pub/apps/conda/envs/env/lib/python3.8/site-packages/ray/rllib/models/tf/tf_action_dist.py", line 301, in __init__
    assert tfp is not None
AssertionError
`

System: 
Cent OS 7
ray                       1.2.0                    pypi_0    pypi
tensorboard               2.4.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorboardx              2.1                      pypi_0    pypi
tensorflow                2.4.1                    pypi_0    pypi
tensorflow-base           2.3.0           mkl_py38hac35e67_0  
tensorflow-estimator      2.4.0                    pypi_0    pypi
tensorflow-probability    0.12.1             pyhd8ed1ab_0    conda-forge

### Reproduction (REQUIRED)
`
import ray
from ray.rllib.agents import sac
agent = sac.SACTrainer(env=*env with tf package*, config=config)
ray.init()
`
When using an environment with an import of tensorflow this error occurs. This does not happen with the PPO-Agent or with the Cartpole environment

**Comment by mvindiola1** [comment]
Try pip install tensorflow-probability

**Comment by astronauti** [comment]
Problem is that the conda-forge package is broken. It installs tensorflow-base 2.3. Even though i have tensorflow 2.4 installed, when i run import tensorflow as tf it import tf from the tensorflow-base package. I had to remove the conda package. 

Implementing an error message, when the import of tf-agents fails would be great.
