### ISSUE TITLE
[client] Named actors are destroyed after client disconnects; other actor ref count issues

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#14618]
### What is the problem?

In workflow orchestrators, you might have many different processes trying to access the same ray cluster simultaneously. They use the same 'ray client' interface/port, this can often induce hangs or odd behaviors.

*Ray version and other system information (Python version, TensorFlow version, OS):* Master, OSX/Linux

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

You may need to run this a couple times to get the effect (naturally, as it seems to be a race condition).

```python
import ray
from multiprocessing import Pool

KEY_NAME = "test_actor"

@ray.remote
class _KvStoreActor:
    def ping(self):
        return 1

def get_actor(identifier=KEY_NAME):
    try:
        print(f"trying to get this actor {identifier} here")
        ret = ray.get_actor(identifier)
        for i in range(10):
            try:
                ray.get(ret.ping.remote(), timeout=1)
                break
            except Exception as e:
                sleep(1)
        return ret
    except ValueError as e:
        print(e)
        return _KvStoreActor.options(
            name=identifier, lifetime="detached").remote()

def f(x):
    import ray
    ray.util.connect("localhost:10001")
    actor = get_actor()
    ray.get(actor.ping.remote())
    print("Done!")

if __name__ == '__main__':
    import ray
    ray.util.connect("localhost:10001")
    actor = get_actor()
    ray.get(actor.ping.remote())
    ray.util.disconnect()
    with Pool(7) as p:
        print(p.map(f, [1, 2, 3, 4, 5, 6, 7]))

```

cc @AmeerHajAli @ericl

**Comment by ericl** [comment]
So I'm not able to even get a named actor after disconnecting from a single client. Maybe the "detached" lifetime isn't working for Ray client?

Btw, the above example is a bit suspicious since there are race conditions with getting actors and creating multiple of them at the same time.

**Comment by richardliaw** [comment]
@ericl I've adjusted the repro script to synchronously create the named actor and ensure creation before calling the multiprocessing code.

Same behavior occurs.

**Comment by ericl** [comment]
I think multiprocessing is doing something weird here, and also it's swallowing exceptions. If I remove the use of multiprocessing, you can see that get_actor is not working properly:

```
import ray
import time

KEY_NAME = "test_actor"

@ray.remote
class _KvStoreActor:
    def ping(self):
        return 1

def get_actor(identifier=KEY_NAME):
    try:
        print(f"trying to get this actor {identifier} here")
        ret = ray.get_actor(identifier)
        for i in range(10):
            try:
                ray.get(ret.ping.remote(), timeout=1)
                break
            except Exception as e:
                sleep(1)
        return ret
    except ValueError as e:
        print(e)
        return _KvStoreActor.options(
            name=identifier, lifetime="detached").remote()

if __name__ == '__main__':
    import ray
    ray.util.connect("localhost:50051")
    actor = get_actor()
    print(ray.get(actor.ping.remote()))
```

```
eric@eric-thinkpad-t490s:~/Desktop$ python test.py
trying to get this actor test_actor here
Failed to look up actor with name 'test_actor'. You are either trying to look up a named actor you didn't create, the named actor died, or the actor hasn't been created because named actor creation is asynchronous.
1
eric@eric-thinkpad-t490s:~/Desktop$ python test.py
trying to get this actor test_actor here
Failed to look up actor with name 'test_actor'. You are either trying to look up a named actor you didn't create, the named actor died, or the actor hasn't been created because named actor creation is asynchronous.
1
```

So that's at least one bug.

If you run with xargs for concurrency you can see other kinds of errors (if you hold the actor open with a persistent client):
`seq 1 10 | xargs -n 1 -P 10 python client.py`

```
trying to get this actor test_actor here
trying to get this actor test_actor here
trying to get this actor test_actor here
1
1
trying to get this actor test_actor here
1
trying to get this actor test_actor here
trying to get this actor test_actor here
trying to get this actor test_actor here
Traceback (most recent call last):
  File "client.py", line 30, in <module>
    print(ray.get(actor.ping.remote()))
  File "/home/eric/Desktop/ray/python/ray/util/client/common.py", line 249, in remote
    return return_refs(ray.call_remote(self, *args, **kwargs))
  File "/home/eric/Desktop/ray/python/ray/util/client/api.py", line 96, in call_remote
    return self.worker.call_remote(instance, *args, **kwargs)
  File "/home/eric/Desktop/ray/python/ray/util/client/worker.py", line 293, in call_remote
    return self._call_schedule_for_task(task)
  File "/home/eric/Desktop/ray/python/ray/util/client/worker.py", line 305, in _call_schedule_for_task
    raise cloudpickle.loads(ticket.error)
Exception: Can't run an actor the server doesn't have a handle for
trying to get this actor test_actor here
1
trying to get this actor test_actor here
trying to get this actor test_actor here
Traceback (most recent call last):
  File "client.py", line 30, in <module>
    print(ray.get(actor.ping.remote()))
  File "/home/eric/Desktop/ray/python/ray/util/client/common.py", line 249, in remote
    return return_refs(ray.call_remote(self, *args, **kwargs))
  File "/home/eric/Desktop/ray/python/ray/util/client/api.py", line 96, in call_remote
    return self.worker.call_remote(instance, *args, **kwargs)
  File "/home/eric/Desktop/ray/python/ray/util/client/worker.py", line 293, in call_remote
    return self._call_schedule_for_task(task)
  File "/home/eric/Desktop/ray/python/ray/util/client/worker.py", line 305, in _call_schedule_for_task
    raise cloudpickle.loads(ticket.error)
Exception: Can't run an actor the server doesn't have a handle for
```

**Comment by ericl** [comment]
I did a bit of digging and I think besides the above, the only other concurrency issue is that we `del self.actor_refs[id]` too early, even if multiple clients are referencing the same actor.

**Comment by ericl** [comment]
Ah, another issue is 
```
    server = grpc.server(
        futures.ThreadPoolExecutor(max_workers=10),
        options=[
            ("grpc.max_send_message_length", GRPC_MAX_MESSAGE_SIZE),
            ("grpc.max_receive_message_length", GRPC_MAX_MESSAGE_SIZE),
        ])
```

The max_workers is set to a pretty low value. There may be hangs if that number of connections is exceeded (we should probably drop additional connections, and make the worker pool size configurable).

**Comment by mrrobby** [comment]
It's possible another system could start up several clients concurrently. So if there was a timeout so any clients exceeding the limit could retry, that seems it would help, right? Then allowing to set a pool connection limit dynamically would allow for that to scale smoothly and minimize the amount of retry loops occuring.
