### ISSUE TITLE
EOFError: Ran out of input on Kubernetes Cluster 

### ISSUE THREAD

**Issue by XavierGeerinck** [ray-project/ray#14666]
### What is the problem?

I deployed a Kubernetes setup with Ray through the documentation at https://docs.ray.io/en/master/cluster/kubernetes.html#interacting-with-a-ray-cluster when I then submit a job through `ray submit my-cluster.yaml myscript.py` it returns `EOFError: Ran out of input`

* Ray Version: Latest as defined in nightly builds at https://hub.docker.com/r/rayproject/ray

### Stacktrace

```bash
2021-03-13 13:06:46,093 INFO command_runner.py:171 -- NodeUpdater: example-cluster-ray-head-mtw85: Running kubectl -n ray exec -it example-cluster-ray-head-mtw85 -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (python ~/cartpole2.py)'
Traceback (most recent call last):
  File "/home/ray/cartpole2.py", line 20, in <module>
    agent = ppo.PPOTrainer(config, env=SELECT_ENV)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 121, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 513, in __init__
    super().__init__(config, logger_creator)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 607, in setup
    self.env_creator = _global_registry.get(ENV_CREATOR, env)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/registry.py", line 140, in get
    return pickle.loads(value)
EOFError: Ran out of input
command terminated with exit code 1
```

### Reproduction (REQUIRED)

```python
import ray
import ray.rllib.agents.ppo as ppo
import os
import shutil

ray.util.connect("127.0.0.1:10001")

CHECKPOINT_ROOT = "tmp/ppo/cart"
shutil.rmtree(CHECKPOINT_ROOT, ignore_errors=True, onerror=None)

ray_results = os.getenv("HOME") + "/ray_results/"
shutil.rmtree(ray_results, ignore_errors=True, onerror=None)

SELECT_ENV = "CartPole-v0"

config = ppo.DEFAULT_CONFIG.copy()
config["log_level"] = "WARN"

agent = ppo.PPOTrainer(config, env=SELECT_ENV)

N_ITER = 40
s = "{:3d} reward {:6.2f}/{:6.2f}/{:6.2f} len {:6.2f} saved {}"

for n in range(N_ITER):
  result = agent.train()
  file_name = agent.save(CHECKPOINT_ROOT)

  print(s.format(
    n + 1,
    result["episode_reward_min"],
    result["episode_reward_mean"],
    result["episode_reward_max"],
    result["episode_len_mean"],
    file_name
   ))
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by DmitriGekhtman** [comment]
@sven1977 @richardliaw -- any sense of what's happening here?

**Comment by XavierGeerinck** [comment]
Hi @richardliaw / @sven1977 any update on this? :)

**Comment by AmeerHajAli** [comment]
CC @richardliaw / @sven1977

**Comment by richardliaw** [comment]
I think rllib doesn't work with ray client like that out of the box?

**Comment by XavierGeerinck** [comment]
Hi @richardliaw what would I be missing then? :)

**Comment by ericl** [comment]
It seems like some pickle compatibility issue here, or perhaps a ray client issue. You can try this:

Remove the Ray client connect call `ray.util.connect("127.0.0.1:10001")`. Replace it with the normal `ray.init("auto")` call.

**Comment by richardliaw** [comment]
@XavierGeerinck can you try the latest master? We recently merged some better support for ray client.

**Comment by richardliaw** [comment]
Also assigning this to serverless team

**Comment by AmeerHajAli** [comment]
@DmitriGekhtman can you please follow up on this when you are back in office?

**Comment by DmitriGekhtman** [comment]
We should make sure this works with ray client (which will be preferred over ray submit in the future). Will look into that.

In the meantime, I'd recommend trying with ray.init as suggested by Eric. Ray Submit copies the script to the head node and executes it there -- that's a reasonable enough way to submit the script from your laptop for remote execution.

**Comment by DmitriGekhtman** [comment]
Also you typically shouldn't mix ray.util.connect with ray submit -- ray.util.connect allows you to execute your script locally, with ray tasks and actors sent to the remote cluster.
You can check out the ray/k8s docs for how to set up a ray client connection (this part should work with either cluster launcher or helm/operator.)

**Comment by DmitriGekhtman** [comment]
That said, the script should ideally work anyway.

**Comment by amogkam** [comment]
Hey @XavierGeerinck, just following up here- are you still running into issues with this on the most recent versions of Ray? I'm going to close this issue for now, but please feel free to re-open if this is still not working for you.

**Comment by peterhaddad3121** [comment]
Hi @amogkam, I am running into this issue as well. I created a new issue here. https://github.com/ray-project/ray/issues/24307
