### ISSUE TITLE
[tune] Fail to resume searcher

### ISSUE THREAD

**Issue by RaphaelCS** [ray-project/ray#14667]
### What is the problem?

I can't resume a searcher when I use BOHB (I'm not sure whether this happen when using other search_alg).

I got these messages when resuming:
```
2021-03-13 22:03:33,691 WARNING trial_runner.py:422 -- Attempting to resume experiment from /home/LAB/chensi/workspace/dp/tests/bohb_test. This will ignore any new changes to the specification.
2021-03-13 22:04:29,208 ERROR trial_runner.py:279 -- Searcher unable to find checkpoint in /home/LAB/chensi/workspace/dp/tests/bohb_test
2021-03-13 22:04:35,390 ERROR trial_runner.py:280 -- Runner restore failed.
Traceback (most recent call last):
  File "/home/LAB/chensi/anaconda3/envs/ray2devpy38/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 275, in __init__
    self.resume(run_errored_only=errored_only)
  File "/home/LAB/chensi/anaconda3/envs/ray2devpy38/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 430, in resume
    self._search_alg.restore_from_dir(self._local_checkpoint_dir)
  File "/home/LAB/chensi/anaconda3/envs/ray2devpy38/lib/python3.8/site-packages/ray/tune/suggest/search_generator.py", line 213, in restore_from_dir
    base_searcher.restore_from_dir(dirpath)
  File "/home/LAB/chensi/anaconda3/envs/ray2devpy38/lib/python3.8/site-packages/ray/tune/suggest/suggestion.py", line 297, in restore_from_dir
    raise RuntimeError(
RuntimeError: Searcher unable to find checkpoint in /home/LAB/chensi/workspace/dp/tests/bohb_test
2021-03-13 22:05:03,962 INFO trial_runner.py:283 -- Restarting experiment.
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
**ray**: 2.0.0.dev0

### Reproduction (REQUIRED)

_Run this script and interrupt it before it finishes. Then, re-run it after uncommenting `resume=True`._

```python
#!/usr/bin/env python

import json
import time
import os

import numpy as np

import ray
from ray import tune
from ray.tune import Trainable
from ray.tune.schedulers.hb_bohb import HyperBandForBOHB
from ray.tune.suggest.bohb import TuneBOHB


class MyTrainableClass(Trainable):
    """Example agent whose learning curve is a random sigmoid.

    The dummy hyperparameters "width" and "height" determine the slope and
    maximum reward value reached.
    """

    def setup(self, config):
        self.timestep = 0

    def step(self):
        self.timestep += 1
        v = np.tanh(float(self.timestep) / self.config.get("width", 1))
        v *= self.config.get("height", 1)
        time.sleep(0.1)
        # Here we use `episode_reward_mean`, but you can also report other
        # objectives such as loss or accuracy.
        return {"episode_reward_mean": v}

    def save_checkpoint(self, checkpoint_dir):
        path = os.path.join(checkpoint_dir, "checkpoint")
        with open(path, "w") as f:
            f.write(json.dumps({"timestep": self.timestep}))
        return path

    def load_checkpoint(self, checkpoint_path):
        with open(checkpoint_path) as f:
            self.timestep = json.loads(f.read())["timestep"]


if __name__ == "__main__":
    import ConfigSpace as CS  # noqa: F401
    ray.init(num_cpus=2)

    config = {
        "iterations": 100,
        "width": tune.uniform(0, 20),
        "height": tune.uniform(-100, 100),
        "activation": tune.choice(["relu", "tanh"])
    }

    bohb_hyperband = HyperBandForBOHB(
        time_attr="training_iteration",
        max_t=100,
        reduction_factor=4,
        stop_last_trials=False)

    bohb_search = TuneBOHB(
        # space=config_space,  # If you want to set the space manually
        max_concurrent=4)

    analysis = tune.run(
        MyTrainableClass,
        name="bohb_test",
        config=config,
        scheduler=bohb_hyperband,
        search_alg=bohb_search,
        num_samples=10,
        stop={"training_iteration": 100},
        metric="episode_reward_mean",
        mode="max",
        local_dir=".",
        # resume=True
    )

    print("Best hyperparameters found were: ", analysis.best_config)

```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by Mr-Pepe** [comment]
I am having the same problem using Ax. My experiment finished regularly after 20 trials, but I would like to continue tuning without rerunning those 20 configurations that were tested already.

**Comment by DmitriGekhtman** [comment]
cc @amogkam @richardliaw @krfricke

**Comment by richardliaw** [comment]
hey @Mr-Pepe and @RaphaelCS , thanks for raising these issues. I've open up a feature request for these, and will try to get to them soon.

**Comment by RaphaelCS** [comment]
Thanks a lot!
