### ISSUE TITLE
Ray K8s Operator broken in nightly

### ISSUE THREAD

**Issue by tgaddair** [ray-project/ray#14708]
Ray Operator that was working yesterday using the default cluster config now fails when upgrading with the following pod logs:

```
local-cluster:2021-03-16 06:36:04,068	ERROR commands.py:301 -- Failed to autodetect node resources.
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 298, in _bootstrap_config
    config = provider_cls.fillout_available_node_types_resources(config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kubernetes/node_provider.py", line 184, in fillout_available_node_types_resources
    return fillout_resources_kubernetes(cluster_config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kubernetes/config.py", line 93, in fillout_resources_kubernetes
    autodetected_resources = get_autodetected_resources(container_data)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kubernetes/config.py", line 127, in get_autodetected_resources
    (1 - ray_constants.DEFAULT_OBJECT_STORE_MEMORY_PROPORTION))
OverflowError: cannot convert float infinity to integer
2021-03-16 06:36:04,038	INFO commands.py:234 -- Cluster: local-cluster
2021-03-16 06:36:04,068	INFO commands.py:296 -- Checking Kubernetes environment settings
Process local-cluster:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/ray/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/ray_operator/operator.py", line 53, in _create_or_update
    self.start_head()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/ray_operator/operator.py", line 66, in start_head
    no_monitor_on_head=True)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 237, in create_or_update_cluster
    config = _bootstrap_config(config, no_config_cache=no_config_cache)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 311, in _bootstrap_config
    validate_config(config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/util.py", line 67, in validate_config
    raise e from None
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/util.py", line 65, in validate_config
    jsonschema.validate(config, schema)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: 'resources' is a required property
```

Rolling the operator back to image `rayproject/ray:ef5adc` resolves the issue.

**Comment by DmitriGekhtman** [comment]
Will fix shortly.

**Comment by DmitriGekhtman** [comment]
Actually, I'm not currently able to replicate with the default configs.

@tgaddair 
Do you specify memory limits in your pod specs?

**Comment by tgaddair** [comment]
Hey @DmitriGekhtman, yeah I was using the config in the Ray repo at `ray/python/ray/autoscaler/kubernetes/operator_configs/example_cluster.yaml`. It specifies resource limits:

```
- name: ray-node
          imagePullPolicy: Always
          image: rayproject/ray:nightly
          # Do not change this command - it keeps the pod alive until it is
          # explicitly killed.
          command: ["/bin/bash", "-c", "--"]
          args: ['trap : TERM INT; sleep infinity & wait;']
          ports:
          - containerPort: 6379  # Redis port
          - containerPort: 10001  # Used by Ray Client
          - containerPort: 8265  # Used by Ray Dashboard

          # This volume allocates shared memory for Ray to use for its plasma
          # object store. If you do not provide this, Ray will fall back to
          # /tmp which cause slowdowns if is not a shared memory volume.
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          resources:
            requests:
              cpu: 1000m
              memory: 512Mi
            limits:
              # The maximum memory that this pod is allowed to use. The
              # limit will be detected by ray and split to use 10% for
              # redis, 30% for the shared memory object store, and the
              # rest for application memory. If this limit is not set and
              # the object store size is not set manually, ray will
              # allocate a very large object store in each pod that may
              # cause problems for other pods.
              memory: 512Mi
```

**Comment by DmitriGekhtman** [comment]
will try again to replicate

**Comment by DmitriGekhtman** [comment]
This should fix the issue though -- https://github.com/ray-project/ray/pull/14712

**Comment by DmitriGekhtman** [comment]
I'm not able to replicate with the nightly image, which right now is the same as `rayproject/ray:bd641a`.
I checked that the memory resource that seemed to be causing the issue was filled correctly..
Could you try again (maybe with `rayproject/ray:bd641a` specified in `operator.yaml`) to check if you still see the problem?

**Comment by AmeerHajAli** [comment]
@tgaddair, Can you please checkout what Dmitri wrote above and confirm this solves your issue so we can close this?

**Comment by tgaddair** [comment]
Sorry for the delay. Just tested this locally with the latest image, looks like everything is working again. Thanks @DmitriGekhtman!
