### ISSUE TITLE
[rllib] LocalReplayBuffer when replay_sequence_length > 1

### ISSUE THREAD

**Issue by perara** [ray-project/ray#14710]
### What is the problem?
When setting `replay_sequence_length` > 1 for the `LocalReplayBuffer` the assertion `AssertionError: Cannot timeslice along `seq_lens` when `seq_lens` is empty or None!`is thrown. `timeslice_along_seq_lens_with_overlap`does not pass seq_lens and seq_lens are None in the SampleBatch

Goal: To retrieve (and store) samples from the buffer in the format [batch, seq, features]

Stacktrace:
```
Traceback (most recent call last):
  File "ray_main_4.py", line 119, in <module>
    results = trainer.train()
  File "lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 573, in train
    raise e
  File "lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 559, in train
    result = Trainable.train(self)
  File "lib/python3.8/site-packages/ray/tune/trainable.py", line 232, in train
    result = self.step()
  File "lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 162, in step
    res = next(self.train_exec_impl)
  File "lib/python3.8/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "lib/python3.8/site-packages/ray/util/iter.py", line 1075, in build_union
    item = next(it)
  File "lib/python3.8/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "lib/python3.8/site-packages/ray/util/iter.py", line 791, in apply_foreach
    result = fn(item)
  File "lib/python3.8/site-packages/ray/rllib/execution/replay_ops.py", line 48, in __call__
    self.local_actor.add_batch(batch)
  File "lib/python3.8/site-packages/ray/rllib/execution/replay_buffer.py", line 390, in add_batch
    timeslices = timeslice_along_seq_lens_with_overlap(
  File "lib/python3.8/site-packages/ray/rllib/policy/rnn_sequencing.py", line 358, in timeslice_along_seq_lens_with_overlap
    assert seq_lens is not None and seq_lens != [], \
AssertionError: Cannot timeslice along `seq_lens` when `seq_lens` is empty or None!

Process finished with exit code 1
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
Tensorflow 2.4.1
Python 3.8
Linux (Arch)
Latest Ray version (nightly wheel)

### Reproduction (REQUIRED)
```python
import gym
from ray.rllib import Policy
from ray.rllib.agents import with_common_config

from ray.rllib.agents.trainer_template import build_trainer
from ray.rllib.evaluation.worker_set import WorkerSet
from ray.rllib.execution import ParallelRollouts, Replay, StoreToReplayBuffer, TrainOneStep, \
    Concurrently, StandardMetricsReporting
from ray.rllib.execution.replay_buffer import LocalReplayBuffer
from ray.rllib.models import ModelV2
from ray.rllib.models.tf import TFModelV2
from ray.rllib.models.tf.tf_action_dist import Categorical
from ray.rllib.policy.tf_policy_template import build_tf_policy
from ray.rllib.utils import override
from ray.rllib.utils.framework import try_import_tf
from ray.rllib.utils.typing import TrainerConfigDict, TensorType
from typing import Dict, List


tf1, tf, tfv = try_import_tf()

DEFAULT_CONFIG = with_common_config({
    "buffer_size": 50000,
    "learning_starts": 1000,
    "replay_sequence_length": 2,
    "train_batch_size": 32,
    "batch_mode": "complete_episodes",
    "model": {},

})


class MyModel(TFModelV2):

    def __init__(self, obs_space, action_space, num_outputs, model_config, name):
        super().__init__(obs_space, action_space, num_outputs, model_config, name)

    @override(ModelV2)
    def forward(self,
                input_dict: Dict[str, TensorType],
                state: List[TensorType],
                seq_lens: TensorType
                ) -> (TensorType, List[TensorType]):
        return "?? what is this", []


def policy_gradient_loss(policy, model, dist_class, train_batch):
    return tf.cast(0, tf.float32)


def action_distribution_fn(*args, **kwargs):
    actions = tf.zeros((1, 3))
    return actions, Categorical, []


def build_model(policy: Policy, obs_space: gym.spaces.Space, action_space: gym.spaces.Space,
                config: TrainerConfigDict) -> ModelV2:
    model = MyModel(
        obs_space=obs_space,
        action_space=action_space,
        num_outputs=1,
        model_config=DEFAULT_CONFIG,  # TODO
        name="MyModel",
    )
    policy.model = model
    return model


def execution_plan(workers: WorkerSet, config: TrainerConfigDict):
    local_replay_buffer = LocalReplayBuffer(
        num_shards=1,
        learning_starts=config["learning_starts"],
        buffer_size=config["buffer_size"],
        replay_batch_size=config["train_batch_size"],
        replay_mode=config["multiagent"]["replay_mode"],
        replay_sequence_length=config["replay_sequence_length"])

    rollouts = ParallelRollouts(workers, mode="bulk_sync")

    # (1) Generate rollouts and store them in our local replay buffer.
    store_op = rollouts.for_each(
        StoreToReplayBuffer(local_buffer=local_replay_buffer))

    train_step_op = TrainOneStep(workers)

    replay_op = Replay(local_buffer=local_replay_buffer) \
        .for_each(train_step_op)

    train_op = Concurrently(
        [store_op, replay_op], mode="round_robin", output_indexes=[1])

    return StandardMetricsReporting(train_op, workers, config)


MyTFPolicy = build_tf_policy(
    name="MyTFPolicy",
    loss_fn=policy_gradient_loss,
    make_model=build_model,
    action_distribution_fn=action_distribution_fn,
    # obs_include_prev_action_reward=True
)

MyTrainer = build_trainer(
    name="MyCustomTrainer",
    default_policy=MyTFPolicy,
    default_config=DEFAULT_CONFIG,
    execution_plan=execution_plan
)

if __name__ == "__main__":
    config = {
        "env": "CarRacing-v0",
        "num_gpus": 1,
        "num_workers": 0,
        "framework": "tf2",
    }
    trainer = MyTrainer(config=config)
    for i in range(1000):
        results = trainer.train()
        print(results)

```
- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by DmitriGekhtman** [comment]
cc @sven1977

**Comment by ArturNiederfahrenhorst** [comment]
Hey perara! Thanks for reporting this.

First of all: 1.12 does not include build_trainer anymore and LocalReplayBuffer has also been deprecated.

I know this issue is stable, but I have written a runnable version of your script.
Be aware that this is based on the current nightly:

```
import gym
from ray.rllib import Policy

from ray.rllib.evaluation.worker_set import WorkerSet
from ray.rllib.execution import ParallelRollouts, Replay, StoreToReplayBuffer, TrainOneStep, \
    Concurrently, StandardMetricsReporting
from ray.rllib.agents.dqn import SimpleQTrainer
from ray.rllib.utils.replay_buffers import MultiAgentReplayBuffer
from ray.rllib.models import ModelV2
from ray.rllib.models.tf import TFModelV2
from ray.rllib.models.tf.tf_action_dist import Categorical
from ray.rllib.policy.tf_policy_template import build_tf_policy
from ray.rllib.utils import override
from ray.rllib.utils.framework import try_import_tf
from ray.rllib.utils.typing import TrainerConfigDict, TensorType
from typing import Dict, List
from ray.rllib.policy.rnn_sequencing import pad_batch_to_sequences_of_same_size


tf1, tf, tfv = try_import_tf()

DEFAULT_CONFIG = SimpleQTrainer.merge_trainer_configs(
    SimpleQTrainer.get_default_config(), {
    "train_batch_size": 32,
    "batch_mode": "complete_episodes",
    "model": {},
    "_disable_execution_plan_api": False,
    "replay_buffer_config": {
        "no_local_replay_buffer": True,
        "capacity": 50000,
        "learning_starts": 1000,
        "replay_sequence_length": 2,
    }
})


class MyModel(TFModelV2):

    def __init__(self, obs_space, action_space, num_outputs, model_config, name):
        super().__init__(obs_space, action_space, num_outputs, model_config, name)

    @override(ModelV2)
    def forward(self,
                input_dict: Dict[str, TensorType],
                state: List[TensorType],
                seq_lens: TensorType
                ) -> (TensorType, List[TensorType]):
        return "?? what is this", []


def policy_gradient_loss(policy, model, dist_class, train_batch):
    return tf.cast(0, tf.float32)


def action_distribution_fn(*args, **kwargs):
    actions = tf.zeros((1, 2))
    return actions, Categorical, []


def build_model(policy: Policy, obs_space: gym.spaces.Space, action_space: gym.spaces.Space,
                config: TrainerConfigDict) -> ModelV2:
    model = MyModel(
        obs_space=obs_space,
        action_space=action_space,
        num_outputs=1,
        model_config=DEFAULT_CONFIG,  # TODO
        name="MyModel",
    )
    policy.model = model
    return model


def execution_plan(_trainer, workers: WorkerSet, config: TrainerConfigDict, **kwargs):
    local_replay_buffer = MultiAgentReplayBuffer(
        num_shards=1,
        learning_starts=config["replay_buffer_config"]["learning_starts"],
        buffer_size=config["replay_buffer_config"]["capacity"],
        replay_batch_size=config["replay_buffer_config"]["replay_batch_size"],
        replay_mode=config["multiagent"]["replay_mode"],
        replay_sequence_length=config["replay_buffer_config"]["replay_sequence_length"])

    rollouts = ParallelRollouts(workers, mode="bulk_sync")

    # (1) Generate rollouts and store them in our local replay buffer.
    store_op = rollouts.for_each(lambda x:
                                 pad_batch_to_sequences_of_same_size(x, max_seq_len=config["replay_buffer_config"]["replay_sequence_length"])).for_each(
        StoreToReplayBuffer(local_buffer=local_replay_buffer))

    train_step_op = TrainOneStep(workers)

    replay_op = Replay(local_buffer=local_replay_buffer) \
        .for_each(train_step_op)

    train_op = Concurrently(
        [store_op, replay_op], mode="round_robin", output_indexes=[1])

    return StandardMetricsReporting(train_op, workers, config)


MyTFPolicy = build_tf_policy(
    name="MyTFPolicy",
    loss_fn=policy_gradient_loss,
    make_model=build_model,
    action_distribution_fn=action_distribution_fn,
    # obs_include_prev_action_reward=True
)

class MyTrainer(SimpleQTrainer):
    @override(SimpleQTrainer)
    def get_default_config(cls) -> TrainerConfigDict:
        return DEFAULT_CONFIG

    def get_default_policy_class(self, config: TrainerConfigDict):
        return MyTFPolicy

MyTrainer.execution_plan=execution_plan

if __name__ == "__main__":
    config = {
        "env": "CartPole-v1",
        "num_gpus": 1,
        "num_workers": 0,
        "framework": "tf2",
    }
    trainer = MyTrainer(config=config)

    for i in range(10):
        results = trainer.train()
        print(results)
```

This script runs and learns.

I will create a PR that automates the step that you missed (`.for_each(lambda x:
                                 pad_batch_to_sequences_of_same_size(x, max_seq_len=config["replay_buffer_config"]["replay_sequence_length"]))`).
                                 
Again, thanks for writing the issue! Although not a bug, this is still something that we can potentially automate!
