### ISSUE TITLE
[rllib] Offline Learning Bug with SAC

### ISSUE THREAD

**Issue by SebastianBodza** [ray-project/ray#14736]
I am getting the following error: 

```
Traceback (most recent call last):
  File "F:/02_Projekte/00_Reinforcement-Learning/04_Ray_HPC/04_OfflineLearning.py", line 85, in <module>
    Reinforcement.startTraining(disableOutput=disableOutput, resumeTraining=resumeTraining)
  File "F:\02_Projekte\00_Reinforcement-Learning\04_Ray_HPC\libs\Reinforcement.py", line 111, in startTraining
    self.result = self.agent.train()
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\rllib\agents\trainer.py", line 529, in train
    raise e
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\rllib\agents\trainer.py", line 515, in train
    result = Trainable.train(self)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\tune\trainable.py", line 226, in train
    result = self.step()
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\rllib\agents\trainer_template.py", line 148, in step
    res = next(self.train_exec_impl)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\util\iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\util\iter.py", line 843, in apply_filter
    for item in it:
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\util\iter.py", line 843, in apply_filter
    for item in it:
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\util\iter.py", line 843, in apply_filter
    for item in it:
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\util\iter.py", line 1075, in build_union
    item = next(it)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\util\iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\util\iter.py", line 791, in apply_foreach
    result = fn(item)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\rllib\execution\train_ops.py", line 69, in __call__
    info = self.workers.local_worker().learn_on_batch(batch)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 855, in learn_on_batch
    info_out[pid] = policy.learn_on_batch(batch)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\rllib\utils\threading.py", line 21, in wrapper
    return func(self, *a, **k)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\rllib\policy\eager_tf_policy.py", line 334, in learn_on_batch
    return self._learn_on_batch_eager(postprocessed_batch)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\rllib\policy\eager_tf_policy.py", line 71, in _func
    return func(*args, **kwargs)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\rllib\policy\eager_tf_policy.py", line 79, in _func
    out = func(*args, **kwargs)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\rllib\policy\eager_tf_policy.py", line 340, in _learn_on_batch_eager
    grads_and_vars, stats = self._compute_gradients(samples)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\rllib\utils\threading.py", line 21, in wrapper
    return func(self, *a, **k)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\rllib\policy\eager_tf_policy.py", line 613, in _compute_gradients
    loss = loss_fn(self, self.model, self.dist_class, samples)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\ray\rllib\agents\sac\sac_tf_policy.py", line 331, in sac_actor_critic_loss
    train_batch[SampleBatch.REWARDS] +
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1164, in binary_op_wrapper
    return func(x, y, name=name)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1486, in _add_dispatch
    return gen_math_ops.add_v2(x, y, name=name)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 471, in add_v2
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\.conda\envs\ReinfLearnNew\lib\site-packages\tensorflow\python\framework\ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:AddV2]

Process finished with exit code 1
```

my environment looks like this: 

  ```
class environment(gym.Env):
      metadata = {'render.modes': ['console']}  # console

      def __init__(self, env_config):
          super(environment, self).__init__()  # Define action and observation space
          self.action_space = spaces.Box(low=-5.4, high=1.0, shape=(1,), dtype=np.float32)
          self.observation_space = spaces.Box(low=0, high=255, shape=(8,), dtype=np.float32)
  ...
```

The same happens for the PPO-Agent

**Comment by astronauti** [comment]
the worker.json is the following: 
```
{"type": "SampleBatch", "obs": [[5.4070000648498535, 1.25, 4.119999885559082, 3.7799999713897705, 4.150000095367432, 3.200000047683716, 13.859999656677246, 1.899999976158142]], "new_obs": [[5.4070000648498535, 1.25, 4.119999885559082, 3.7799999713897705, 4.150000095367432, 3.200000047683716, 13.859999656677246, 1.899999976158142]], "actions": [[-0.9929156303405762]], "rewards": [0.8452949523925781], "dones": [true], "agent_index": [0], "eps_id": [731519022], "unroll_id": [0], "weights": [1.0]}
{"type": "SampleBatch", "obs": [[5.855000019073486, 1.399999976158142, 4.28000020980835, 4.489999771118164, 4.940000057220459, 3.009999990463257, 9.220000267028809, 1.0]], "new_obs": [[5.855000019073486, 1.399999976158142, 4.28000020980835, 4.489999771118164, 4.940000057220459, 3.009999990463257, 9.220000267028809, 1.0]], "actions": [[-0.9474118947982788]], "rewards": [0.8566779494285583], "dones": [true], "agent_index": [0], "eps_id": [661969235], "unroll_id": [1], "weights": [1.0]}
{"type": "SampleBatch", "obs": [[1.8639999628067017, 1.5, 4.630000114440918, 4.949999809265137, 6.260000228881836, 3.190000057220459, 3.940000057220459, 0.6000000238418579]], "new_obs": [[1.8639999628067017, 1.5, 4.630000114440918, 4.949999809265137, 6.260000228881836, 3.190000057220459, 3.940000057220459, 0.6000000238418579]], "actions": [[-0.3510427474975586]], "rewards": [0.9163463711738586], "dones": [true], "agent_index": [0], "eps_id": [923067034], "unroll_id": [2], "weights": [1.0]}
{"type": "SampleBatch", "obs": [[4.381999969482422, 1.059999942779541, 5.110000133514404, 4.539999961853027, 5.070000171661377, 3.200000047683716, 7.78000020980835, 1.600000023841858]], "new_obs": [[4.381999969482422, 1.059999942779541, 5.110000133514404, 4.539999961853027, 5.070000171661377, 3.200000047683716, 7.78000020980835, 1.600000023841858]], "actions": [[-0.7769691348075867]], "rewards": [0.8349964618682861], "dones": [true], "agent_index": [0], "eps_id": [390260347], "unroll_id": [3], "weights": [1.0]}
{"type": "SampleBatch", "obs": [[1.062000036239624, 1.2699999809265137, 4.179999828338623, 4.579999923706055, 5.269999980926514, 3.4700000286102295, 3.119999885559082, 1.2999999523162842]], "new_obs": [[1.062000036239624, 1.2699999809265137, 4.179999828338623, 4.579999923706055, 5.269999980926514, 3.4700000286102295, 3.119999885559082, 1.2999999523162842]], "actions": [[-0.71920245885849]], "rewards": [0.7785173058509827], "dones": [true], "agent_index": [0], "eps_id": [1742593959], "unroll_id": [4], "weights": [1.0]}
{"type": "SampleBatch", "obs": [[1.4390000104904175, 1.1399999856948853, 4.739999771118164, 5.139999866485596, 4.5, 3.4000000953674316, 6.78000020980835, 1.7000000476837158]], "new_obs": [[1.4390000104904175, 1.1399999856948853, 4.739999771118164, 5.139999866485596, 4.5, 3.4000000953674316, 6.78000020980835, 1.7000000476837158]], "actions": [[-0.9302924275398254]], "rewards": [0.7586911916732788], "dones": [true], "agent_index": [0], "eps_id": [205967214], "unroll_id": [5], "weights": [1.0]}
{"type": "SampleBatch", "obs": [[3.0450000762939453, 1.7799999713897705, 4.659999847412109, 5.190000057220459, 4.349999904632568, 3.319999933242798, 3.2699999809265137, 0.699999988079071]], "new_obs": [[3.0450000762939453, 1.7799999713897705, 4.659999847412109, 5.190000057220459, 4.349999904632568, 3.319999933242798, 3.2699999809265137, 0.699999988079071]], "actions": [[-0.7373325824737549]], "rewards": [0.9095959663391113], "dones": [true], "agent_index": [0], "eps_id": [1707721381], "unroll_id": [6], "weights": [1.0]}
{"type": "SampleBatch", "obs": [[5.625, 0.9700000286102295, 5.5, 4.760000228881836, 5.510000228881836, 3.2200000286102295, 12.210000038146973, 0.8999999761581421]], "new_obs": [[5.625, 0.9700000286102295, 5.5, 4.760000228881836, 5.510000228881836, 3.2200000286102295, 12.210000038146973, 0.8999999761581421]], "actions": [[-0.6634224057197571]], "rewards": [0.8276100158691406], "dones": [true], "agent_index": [0], "eps_id": [8976243], "unroll_id": [7], "weights": [1.0]}
{"type": "SampleBatch", "obs": [[6.447999954223633, 0.7699999809265137, 4.0, 4.28000020980835, 4.840000152587891, 3.180000066757202, 12.40999984741211, 0.0]], "new_obs": [[6.447999954223633, 0.7699999809265137, 4.0, 4.28000020980835, 4.840000152587891, 3.180000066757202, 12.40999984741211, 0.0]], "actions": [[-0.9993886351585388]], "rewards": [0.7857086658477783], "dones": [true], "agent_index": [0], "eps_id": [1183344689], "unroll_id": [8], "weights": [1.0]}
{"type": "SampleBatch", "obs": [[6.15500020980835, 1.5800000429153442, 4.949999809265137, 4.300000190734863, 6.039999961853027, 3.3299999237060547, 7.610000133514404, 1.600000023841858]], "new_obs": [[6.15500020980835, 1.5800000429153442, 4.949999809265137, 4.300000190734863, 6.039999961853027, 3.3299999237060547, 7.610000133514404, 1.600000023841858]], "actions": [[-0.7868087291717529]], "rewards": [0.9512985944747925], "dones": [true], "agent_index": [0], "eps_id": [1459097772], "unroll_id": [9], "weights": [1.0]}
{"type": "SampleBatch", "obs": [[4.709000110626221, 0.9200000166893005, 4.460000038146973, 5.0, 6.119999885559082, 3.2300000190734863, 12.5, 0.699999988079071]], "new_obs": [[4.709000110626221, 0.9200000166893005, 4.460000038146973, 5.0, 6.119999885559082, 3.2300000190734863, 12.5, 0.699999988079071]], "actions": [[-0.8383892774581909]], "rewards": [0.7720898985862732], "dones": [true], "agent_index": [0], "eps_id": [774093767], "unroll_id": [10], "weights": [1.0]}
{"type": "SampleBatch", "obs": [[5.466000080108643, 1.0399999618530273, 4.829999923706055, 4.679999828338623, 5.96999979019165, 3.009999990463257, 8.319999694824219, 0.5]], "new_obs": [[5.466000080108643, 1.0399999618530273, 4.829999923706055, 4.679999828338623, 5.96999979019165, 3.009999990463257, 8.319999694824219, 0.5]], "actions": [[-0.971929669380188]], "rewards": [0.7799631953239441], "dones": [true], "agent_index": [0], "eps_id": [1014870795], "unroll_id": [11], "weights": [1.0]}
{"type": "SampleBatch", "obs": [[2.6110000610351562, 0.8399999737739563, 5.420000076293945, 4.050000190734863, 5.710000038146973, 3.180000066757202, 10.329999923706055, 0.800000011920929]], "new_obs": [[2.6110000610351562, 0.8399999737739563, 5.420000076293945, 4.050000190734863, 5.710000038146973, 3.180000066757202, 10.329999923706055, 0.800000011920929]], "actions": [[0.9415280818939209]], "rewards": [0.40934035181999207], "dones": [true], "agent_index": [0], "eps_id": [590554086], "unroll_id": [12], "weights": [1.0]}
{"type": "SampleBatch", "obs": [[1.2970000505447388, 1.0800000429153442, 5.380000114440918, 4.329999923706055, 6.099999904632568, 3.0299999713897705, 5.139999866485596, 1.0]], "new_obs": [[1.2970000505447388, 1.0800000429153442, 5.380000114440918, 4.329999923706055, 6.099999904632568, 3.0299999713897705, 5.139999866485596, 1.0]], "actions": [[0.882270336151123]], "rewards": [0.5151240825653076], "dones": [true], "agent_index": [0], "eps_id": [963200710], "unroll_id": [13], "weights": [1.0]}
{"type": "SampleBatch", "obs": [[6.533999919891357, 1.7000000476837158, 4.659999847412109, 5.090000152587891, 6.789999961853027, 3.130000114440918, 6.53000020980835, 0.8999999761581421]], "new_obs": [[6.533999919891357, 1.7000000476837158, 4.659999847412109, 5.090000152587891, 6.789999961853027, 3.130000114440918, 6.53000020980835, 0.8999999761581421]], "actions": [[0.9979910850524902]], "rewards": [0.3204305171966553], "dones": [true], "agent_index": [0], "eps_id": [867431172], "unroll_id": [14], "weights": [1.0]}
```

**Comment by astronauti** [comment]
Update: With the framewor set to 'tf' instead of 'tf2' it is working. However my environment uses tf2, so i can not train offline and do online evaluation.

**Comment by DmitriGekhtman** [comment]
cc @sven1977 @richardliaw

**Comment by sven1977** [comment]
@astronauti , would you be able to provide a short, self-sufficient reproduction script. I see you posted the data, so I won't need that, just a quick script that shows this error. Then I can debug.

Thanks!

**Comment by astronauti** [comment]
Short example added here: https://github.com/astronauti/Rllibbug.git

Thanks 👍

**Comment by astronauti** [comment]
Changing: 
```
    q_t_selected_target = tf.stop_gradient(
        ttrain_batch[SampleBatch.REWARDS],  +
        policy.config["gamma"]*policy.config["n_step"] * q_tp1_best_masked)
```

to: 
```

    q_t_selected_target = tf.stop_gradient(
        tf.cast(train_batch[SampleBatch.REWARDS], tf.float32) +
        policy.config["gamma"]*policy.config["n_step"] * q_tp1_best_masked)
```

fixes the error
