### ISSUE TITLE
Ray Azure example from manual does not work on Windows 10

### ISSUE THREAD

**Issue by ilyakochik** [ray-project/ray#14771]
### What is the problem?
When attempting to create an Azure cluster with CLI and YAML provided in the 1.2.0 manual the `ray up` script terminates with an error.

Microsoft Windows `10.0.18363.959`
Python `3.8.8` under Conda env
Ray `1.2.0`

### Reproduction (REQUIRED)
1. Create `azure.yaml` from https://github.com/ray-project/ray/blob/releases/1.2.0/python/ray/autoscaler/azure/example-full.yaml
2. Install libs
```
> pip install azure-cli azure-core
```
3. Login and set account
```
> az login
The default web browser has been opened at https://login.microsoftonline.com/common/oauth2/author
ize. Please continue the login in the web browser. If no web browser is available or if the web b
rowser fails to open, use device code flow with `az login --use-device-code`.
You have logged in. Now let us find all the subscriptions to which you have access...
...
```
```
> az account set -s xxxxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxxxxxxx
```
4. Launch cluster
```
> ray up -y azure.yaml
Cluster: default

Checking Azure environment settings
2021-03-18 14:58:09,412 INFO config.py:39 -- Using subscription id: xxxxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxxxxxxx
2021-03-18 14:58:09,412 INFO config.py:53 -- Creating/Updating Resource Group: ray-cluster
Traceback (most recent call last):
  File "c:\programdata\miniconda3\envs\elegant3d\lib\site-packages\msrestazure\polling\arm_pollin
g.py", line 390, in run
    self._poll()
  File "c:\programdata\miniconda3\envs\elegant3d\lib\site-packages\msrestazure\polling\arm_pollin
g.py", line 418, in _poll
    raise OperationFailed("Operation failed or cancelled")
msrestazure.polling.arm_polling.OperationFailed: Operation failed or cancelled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\miniconda3\envs\elegant3d\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\miniconda3\envs\elegant3d\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\envs\elegant3d\Scripts\ray.exe\__main__.py", line 7, in <module
>
  File "c:\programdata\miniconda3\envs\elegant3d\lib\site-packages\ray\scripts\scripts.py", line
1519, in main
    return cli()
  File "c:\programdata\miniconda3\envs\elegant3d\lib\site-packages\click\core.py", line 829, in _
_call__
    return self.main(*args, **kwargs)
  File "c:\programdata\miniconda3\envs\elegant3d\lib\site-packages\click\core.py", line 782, in m
ain
    rv = self.invoke(ctx)
  File "c:\programdata\miniconda3\envs\elegant3d\lib\site-packages\click\core.py", line 1259, in
invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\miniconda3\envs\elegant3d\lib\site-packages\click\core.py", line 1066, in
invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\miniconda3\envs\elegant3d\lib\site-packages\click\core.py", line 610, in i
nvoke
    return callback(*args, **kwargs)
  File "c:\programdata\miniconda3\envs\elegant3d\lib\site-packages\ray\scripts\scripts.py", line
887, in up
    create_or_update_cluster(
  File "c:\programdata\miniconda3\envs\elegant3d\lib\site-packages\ray\autoscaler\_private\comman
ds.py", line 224, in create_or_update_cluster
    config = _bootstrap_config(config, no_config_cache=no_config_cache)
  File "c:\programdata\miniconda3\envs\elegant3d\lib\site-packages\ray\autoscaler\_private\comman
ds.py", line 299, in _bootstrap_config
    resolved_config = provider_cls.bootstrap_config(config)
  File "c:\programdata\miniconda3\envs\elegant3d\lib\site-packages\ray\autoscaler\_private\azure\
node_provider.py", line 298, in bootstrap_config
    return bootstrap_azure(cluster_config)
  File "c:\programdata\miniconda3\envs\elegant3d\lib\site-packages\ray\autoscaler\_private\azure\
config.py", line 21, in bootstrap_azure
    config = _configure_resource_group(config)
  File "c:\programdata\miniconda3\envs\elegant3d\lib\site-packages\ray\autoscaler\_private\azure\
config.py", line 79, in _configure_resource_group
    resource_client.deployments.create_or_update(
  File "c:\programdata\miniconda3\envs\elegant3d\lib\site-packages\msrest\polling\poller.py", lin
e 201, in wait
    raise self._exception  # type: ignore
  File "c:\programdata\miniconda3\envs\elegant3d\lib\site-packages\msrest\polling\poller.py", lin
e 152, in _start
    self._polling_method.run()
  File "c:\programdata\miniconda3\envs\elegant3d\lib\site-packages\msrestazure\polling\arm_pollin
g.py", line 400, in run
    raise CloudError(self._response)
msrestazure.azure_exceptions.CloudError: Azure Error: DeploymentFailed
Message: At least one resource deployment operation failed. Please list deployment operations for
 details. Please see https://aka.ms/DeployOperations for usage details.
Exception Details:
        Error Code: BadRequest
        Message: {'error': {'code': 'RoleAssignmentUpdateNotPermitted', 'message': 'Tenant ID, ap
plication ID, principal ID, and scope are not allowed to be updated.'}}
```

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by DmitriGekhtman** [comment]
Launching clusters on Azure probably won't work until this is merged
https://github.com/ray-project/ray/pull/14750
and these are addressed
https://github.com/ray-project/ray/issues/14778
https://github.com/ray-project/ray/issues/14780

**Comment by ilyakochik** [comment]
Sorry, would not be able to check in the foreseeable future.

**Comment by mattip** [comment]
Ok, I will close this for now, and if needed please reopen or open a new issue
