### ISSUE TITLE
AttributeError: 'VirtualMachinesOperations' object has no attribute 'update'

### ISSUE THREAD

**Issue by XavierGeerinck** [ray-project/ray#14778]
Ray RLLib
Version 2.0.0.dev0

When running `ray up` for an Azure deployment, the following occurs:

```bash
Traceback (most recent call last):
  File "/home/xanrin/.pyenv/versions/3.8.6/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/xanrin/.pyenv/versions/3.8.6/lib/python3.8/site-packages/ray/autoscaler/_private/updater.py", line 129, in run
    self.provider.set_node_tags(
  File "/home/xanrin/.pyenv/versions/3.8.6/lib/python3.8/site-packages/ray/autoscaler/_private/azure/node_provider.py", line 29, in wrapper
    return f(self, *args, **kwargs)
  File "/home/xanrin/.pyenv/versions/3.8.6/lib/python3.8/site-packages/ray/autoscaler/_private/azure/node_provider.py", line 226, in set_node_tags
    self.compute_client.virtual_machines.update(
AttributeError: 'VirtualMachinesOperations' object has no attribute 'update'
  Failed to setup head node.
```

**Comment by XavierGeerinck** [comment]
Pinging @ijrsvt but can't assign :)

**Comment by ijrsvt** [comment]
@gramhagen should we be using `virtual_machines.begin_update` instead of `virtual_machines.update`?

**Comment by gramhagen** [comment]
yes, that's the right command for newer versions of the azure sdk.

**Comment by XavierGeerinck** [comment]
@gramhagen that's it! It's trying to spin up! Stuck at another error now though 😅

Made a new issue for this and am looking into it already https://github.com/ray-project/ray/issues/14780
