### ISSUE TITLE
[tune] error when trying to resume tune.run calls that use skopt search

### ISSUE THREAD

**Issue by ANarayan** [ray-project/ray#14814]
I am am trying to resume a terminated `tune.run` call that uses the `skopt` search algorithm. I am resuming the experiment by setting `resume=True`.  The original experiment was terminated by a sigkill command (`ctrl + c`).

This is the error that I am seeing:
```
Traceback (most recent call last):
  File "/u/nlp/anaconda/main/anaconda3/envs/py37-an-lb/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 705, in _process_trial
    decision = self._process_trial_result(trial, result)
  File "/u/nlp/anaconda/main/anaconda3/envs/py37-an-lb/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 754, in _process_trial_result
    trial.trial_id, result=flat_result)
  File "/u/nlp/anaconda/main/anaconda3/envs/py37-an-lb/lib/python3.7/site-packages/ray/tune/suggest/search_generator.py", line 130, in on_trial_complete
    trial_id=trial_id, result=result, error=error)
  File "/u/nlp/anaconda/main/anaconda3/envs/py37-an-lb/lib/python3.7/site-packages/ray/tune/suggest/skopt.py", line 273, in on_trial_complete
    self._process_result(trial_id, result)
  File "/u/nlp/anaconda/main/anaconda3/envs/py37-an-lb/lib/python3.7/site-packages/ray/tune/suggest/skopt.py", line 277, in _process_result
    skopt_trial_info = self._live_trial_mapping[trial_id]
KeyError: '977090b3'
```
The contents of the searcher-state pickle file (which is accessed when restore() is called ) is the following:
`([], skopt.optimizer.optimizer.Optimizer object at 0x7f2ecc072e80>)`

cc: @richardliaw

**Comment by richardliaw** [comment]
I think this should be fixed -- closing for now
