### ISSUE TITLE
Error: redis.exceptions.ResponseError: wrong number of arguments for 'RAY.TASK_TABLE_ADD' command

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#1487]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: mac 10.13.2
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.3.0
- **Python version**: 3.6
- **Exact command to reproduce**: running python/ray/rllib/examples/multiagent_mountaincar.py

### Describe the problem

Running the example files

### Source code / logs

python multiagent_mountaincar.py
/Users/eugenevinitsky/anaconda2/envs/Ray/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Waiting for redis server at 127.0.0.1:30760 to respond...
Waiting for redis server at 127.0.0.1:61562 to respond...
Starting local scheduler with the following resources: {'CPU': 4, 'GPU': 0}.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui58738.ipynb?token=c1e4deb3a25f43622e8380ffe61ef730d2a67f501a71107d
======================================================================

Traceback (most recent call last):
  File "multiagent_mountaincar.py", line 41, in <module>
    ray.init(num_cpus=num_cpus, redirect_output=True)
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/flow_ray/python/ray/worker.py", line 1453, in init
    include_webui=include_webui)
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/flow_ray/python/ray/worker.py", line 1380, in _init
    mode=driver_mode, worker=global_worker, actor_id=NIL_ACTOR_ID)
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/flow_ray/python/ray/worker.py", line 1909, in connect
    ray.local_scheduler.task_to_string(driver_task))
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/flow_ray/python/ray/experimental/state.py", line 154, in _execute_command
    return client.execute_command(*args)
  File "/Users/eugenevinitsky/anaconda2/envs/Ray/lib/python3.6/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/eugenevinitsky/anaconda2/envs/Ray/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/Users/eugenevinitsky/anaconda2/envs/Ray/lib/python3.6/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: wrong number of arguments for 'RAY.TASK_TABLE_ADD' command

**Comment by robertnishihara** [comment]
This is most likely caused by some parts of the codebase being updated and others not being updated. Could you try getting rid of Ray `pip uninstall ray` (potentially multiple times) as well as `git clean -f -f -x -d -e .whl` in the ray directory, and rebuilding?

**Comment by eugenevinitsky** [comment]
Worked, thank you!
