### ISSUE TITLE
Object spilling to S3 crashes

### ISSUE THREAD

**Issue by franklsf95** [ray-project/ray#14948]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

- Ray: 2.0.0 nightly
- Python 3.8.5
- OS: Ubuntu 18.04
- AWS EC2 instance

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

Repro script:

```
import numpy as np
import ray

MAPPER_PART_SIZE = 2 * 1024 * 1024 * 1024
M = 4
R = 4


@ray.remote(resources={"worker": 1})
def mapper(mapper_id):
    print("Mapper", mapper_id)
    part_size = int(MAPPER_PART_SIZE / R)
    ret = [b"0" * part_size for _ in range(R)]
    return ret


@ray.remote(resources={"worker": 1})
def reducer(reducer_id, *chunks):
    print("Reducer", reducer_id)
    print([len(c) for c in chunks])
    return 0


ray.init(address="auto")

mapper_results = np.empty((M, R), dtype=object)

for m in range(M):
    mapper_results[m, :] = mapper.options(num_returns=R).remote(m)

reducer_results = []
for r in range(R):
    chunks = mapper_results[:, r].tolist()
    ret = reducer.remote(r, *chunks)
    reducer_results.append(ret)

ray.get(reducer_results)
print("OK")
```

Launch Ray with: `ray stop && ray start --head --system-config='{"automatic_object_spilling_enabled":true,"max_io_workers":4,"min_spilling_size":104857600,"object_spilling_config":"{\"type\":\"smart_open\",\"params\":{\"uri\":\"s3://raysort-debug/spill\"}}"}' --resources='{"worker":1}' --object-store-memory 6400000000`

Run log:

```
2021-03-25 16:18:05,386 INFO worker.py:654 -- Connecting to existing Ray cluster at address: 172.31.61.153:6379
(pid=23362) Mapper 0
(pid=23362) Mapper 1
(pid=23362) Mapper 2
(pid=23362) Mapper 3
(pid=23362) Reducer 0
(pid=23362) [536870912, 536870912, 536870912, 536870912]
(raylet) [2021-03-25 16:33:25,392 C 22852 22852] local_object_manager.cc:316:  Check failed: objects_pending_restore_.emplace(object_id).second Object dedupe wasn't done properly. Please report if you see this issue.
(raylet) [2021-03-25 16:33:25,392 E 22852 22852] logging.cc:415: *** Aborted at 1616715205 (unix time) try "date -d @1616715205" if you are using GNU date ***
(raylet) [2021-03-25 16:33:25,393 E 22852 22852] logging.cc:415: PC: @                0x0 (unknown)
(raylet) [2021-03-25 16:33:25,393 E 22852 22852] logging.cc:415: *** SIGABRT (@0x3e800005944) received by PID 22852 (TID 0x7ff72be9d800) from PID 22852; stack trace: ***
(raylet) [2021-03-25 16:33:25,393 E 22852 22852] logging.cc:415:     @     0x5623a84145df google::(anonymous namespace)::FailureSignalHandler()
(raylet) [2021-03-25 16:33:25,393 E 22852 22852] logging.cc:415:     @     0x7ff72ba7b980 (unknown)
(raylet) [2021-03-25 16:33:25,393 E 22852 22852] logging.cc:415:     @     0x7ff72ab24fb7 gsignal
(raylet) [2021-03-25 16:33:25,393 E 22852 22852] logging.cc:415:     @     0x7ff72ab26921 abort
(raylet) [2021-03-25 16:33:25,394 E 22852 22852] logging.cc:415:     @     0x5623a7fca3a6 _ZN3ray6RayLogD2Ev.cold
(raylet) [2021-03-25 16:33:25,394 E 22852 22852] logging.cc:415:     @     0x5623a806d673 _ZZN3ray6raylet18LocalObjectManager25AsyncRestoreSpilledObjectERKNS_8ObjectIDERKSsSt8functionIFvRKNS_6StatusEEEENKUlSt10shared_ptrINS0_15WorkerInterfaceEEE_clESF_
(raylet) [2021-03-25 16:33:25,394 E 22852 22852] logging.cc:415:     @     0x5623a806d9b5 _ZNSt17_Function_handlerIFvSt10shared_ptrIN3ray6raylet15WorkerInterfaceEEEZNS2_18LocalObjectManager25AsyncRestoreSpilledObjectERKNS1_8ObjectIDERKSsSt8functionIFvRKNS1_6StatusEEEEUlS4_E_E9_M_invokeERKSt9_Any_dataOS4_
(raylet) [2021-03-25 16:33:25,394 E 22852 22852] logging.cc:415:     @     0x5623a804b3bd ray::raylet::WorkerPool::PushIOWorkerInternal()
(raylet) [2021-03-25 16:33:25,394 E 22852 22852] logging.cc:415:     @     0x5623a804b5a8 ray::raylet::WorkerPool::PushRestoreWorker()
(raylet) [2021-03-25 16:33:25,395 E 22852 22852] logging.cc:415:     @     0x5623a80698fb _ZNSt17_Function_handlerIFvRKN3ray6StatusERKNS0_3rpc26RestoreSpilledObjectsReplyEEZZNS0_6raylet18LocalObjectManager25AsyncRestoreSpilledObjectERKNS0_8ObjectIDERKSsSt8functionIFvS3_EEENKUlSt10shared_ptrINS9_15WorkerInterfaceEEE_clESL_EUlS3_S7_E_E9_M_invokeERKSt9_Any_dataS3_S7_
(raylet) [2021-03-25 16:33:25,395 E 22852 22852] logging.cc:415:     @     0x5623a807374f ray::rpc::ClientCallImpl<>::OnReplyReceived()
(raylet) [2021-03-25 16:33:25,395 E 22852 22852] logging.cc:415:     @     0x5623a8084c82 _ZN5boost4asio6detail18completion_handlerIZN3ray3rpc17ClientCallManager29PollEventsFromCompletionQueueEiEUlvE_E11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm
(raylet) [2021-03-25 16:33:25,396 E 22852 22852] logging.cc:415:     @     0x5623a8781aa1 boost::asio::detail::scheduler::do_run_one()
(raylet) [2021-03-25 16:33:25,398 E 22852 22852] logging.cc:415:     @     0x5623a8783149 boost::asio::detail::scheduler::run()
(raylet) [2021-03-25 16:33:25,398 E 22852 22852] logging.cc:415:     @     0x5623a8785637 boost::asio::io_context::run()
(raylet) [2021-03-25 16:33:25,398 E 22852 22852] logging.cc:415:     @     0x5623a7fe6182 main
(raylet) [2021-03-25 16:33:25,398 E 22852 22852] logging.cc:415:     @     0x7ff72ab07bf7 __libc_start_main
(raylet) [2021-03-25 16:33:25,400 E 22852 22852] logging.cc:415:     @     0x5623a7ffab55 (unknown)
[1]    23199 abort (core dumped)  python -u repro.py
```

This consistently happens with spilling to S3. When spilling to local disk (`/tmp/spill`), this config works fine; but heavier configs (e.g. 4GB partition size) sometimes also yield this error.

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by franklsf95** [comment]
cc @rkooo567 @stephanie-wang

**Comment by rkooo567** [comment]
Can you try again in the latest master? I suspect it is the same issue as https://github.com/ray-project/ray/issues/14788, and the PR that Eric mentioned in that PR is now merged.

**Comment by franklsf95** [comment]
@rkooo567 got a different error this time:

```
2021-03-30 20:57:48,627 INFO worker.py:653 -- Connecting to existing Ray cluster at address: 172.31.61.153:6379
(pid=30416) Mapper 0
(pid=30416) Mapper 1
(pid=30416) Mapper 2
(pid=30416) Mapper 3
(pid=30416) Reducer 2
(pid=30416) [536870912, 536870912, 536870912, 536870912]
2021-03-30 20:58:03,147 WARNING worker.py:1083 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 713, in ray._raylet.restore_spilled_objects_handler
  File "python/ray/_raylet.pyx", line 716, in ray._raylet.restore_spilled_objects_handler
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/external_storage.py", line 487, in restore_spilled_objects
    return _external_storage.restore_spilled_objects(object_refs,
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/external_storage.py", line 421, in restore_spilled_objects
    self._size_check(metadata_len, buf_len, parsed_result.size)
TypeError: _size_check() missing 1 required positional argument: 'obtained_data_size'
An unexpected internal error occurred while the IO worker was restoring spilled objects.
2021-03-30 20:58:03,157 WARNING worker.py:1083 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 713, in ray._raylet.restore_spilled_objects_handler
  File "python/ray/_raylet.pyx", line 716, in ray._raylet.restore_spilled_objects_handler
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/external_storage.py", line 487, in restore_spilled_objects
    return _external_storage.restore_spilled_objects(object_refs,
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/external_storage.py", line 421, in restore_spilled_objects
    self._size_check(metadata_len, buf_len, parsed_result.size)
```

**Comment by franklsf95** [comment]
I just tried again and got this error repeatedly:

```
2021-04-06 16:41:50,728	INFO worker.py:653 -- Connecting to existing Ray cluster at address: 172.31.61.153:6379
2021-04-06 16:41:50,758	WARNING worker.py:1056 -- The autoscaler failed with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/_private/monitor.py", line 276, in run
    self._run()
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/_private/monitor.py", line 167, in _run
    self.update_load_metrics()
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/_private/monitor.py", line 131, in update_load_metrics
    response = self.gcs_node_resources_stub.GetAllResourceUsage(
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1617752477.825151556","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5390,"referenced_errors":[{"created":"@1617752477.825149033","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>

[[ObjectRef(a67dc375e60ddd1affffffffffffffffffffffff0100000001000000)
  ObjectRef(a67dc375e60ddd1affffffffffffffffffffffff0100000002000000)
  ObjectRef(a67dc375e60ddd1affffffffffffffffffffffff0100000003000000)
  ObjectRef(a67dc375e60ddd1affffffffffffffffffffffff0100000004000000)]
 [ObjectRef(63964fa4841d4a2effffffffffffffffffffffff0100000001000000)
  ObjectRef(63964fa4841d4a2effffffffffffffffffffffff0100000002000000)
  ObjectRef(63964fa4841d4a2effffffffffffffffffffffff0100000003000000)
  ObjectRef(63964fa4841d4a2effffffffffffffffffffffff0100000004000000)]
 [ObjectRef(69a6825d641b4613ffffffffffffffffffffffff0100000001000000)
  ObjectRef(69a6825d641b4613ffffffffffffffffffffffff0100000002000000)
  ObjectRef(69a6825d641b4613ffffffffffffffffffffffff0100000003000000)
  ObjectRef(69a6825d641b4613ffffffffffffffffffffffff0100000004000000)]
 [ObjectRef(ee4e90da584ab0ebffffffffffffffffffffffff0100000001000000)
  ObjectRef(ee4e90da584ab0ebffffffffffffffffffffffff0100000002000000)
  ObjectRef(ee4e90da584ab0ebffffffffffffffffffffffff0100000003000000)
  ObjectRef(ee4e90da584ab0ebffffffffffffffffffffffff0100000004000000)]]
[2m[36m(pid=17040)[0m Mapper 0
[2m[36m(pid=17062)[0m Mapper 1
[2m[36m(pid=17040)[0m Mapper 2
[2m[36m(pid=17069)[0m Mapper 3
2021-04-06 16:42:39,893	WARNING worker.py:1083 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 713, in ray._raylet.restore_spilled_objects_handler
  File "python/ray/_raylet.pyx", line 716, in ray._raylet.restore_spilled_objects_handler
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/external_storage.py", line 487, in restore_spilled_objects
    return _external_storage.restore_spilled_objects(object_refs,
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/external_storage.py", line 421, in restore_spilled_objects
    self._size_check(metadata_len, buf_len, parsed_result.size)
TypeError: _size_check() missing 1 required positional argument: 'obtained_data_size'
An unexpected internal error occurred while the IO worker was restoring spilled objects.
2021-04-06 16:42:39,913	WARNING worker.py:1083 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 713, in ray._raylet.restore_spilled_objects_handler
  File "python/ray/_raylet.pyx", line 716, in ray._raylet.restore_spilled_objects_handler
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/external_storage.py", line 487, in restore_spilled_objects
    return _external_storage.restore_spilled_objects(object_refs,
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/external_storage.py", line 421, in restore_spilled_objects
    self._size_check(metadata_len, buf_len, parsed_result.size)
TypeError: _size_check() missing 1 required positional argument: 'obtained_data_size'
An unexpected internal error occurred while the IO worker was restoring spilled objects.
2021-04-06 16:42:39,923	WARNING worker.py:1083 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 713, in ray._raylet.restore_spilled_objects_handler
  File "python/ray/_raylet.pyx", line 716, in ray._raylet.restore_spilled_objects_handler
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/external_storage.py", line 487, in restore_spilled_objects
    return _external_storage.restore_spilled_objects(object_refs,
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/external_storage.py", line 421, in restore_spilled_objects
    self._size_check(metadata_len, buf_len, parsed_result.size)
TypeError: _size_check() missing 1 required positional argument: 'obtained_data_size'
An unexpected internal error occurred while the IO worker was restoring spilled objects.
2021-04-06 16:42:53,409	WARNING worker.py:1083 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 713, in ray._raylet.restore_spilled_objects_handler
  File "python/ray/_raylet.pyx", line 716, in ray._raylet.restore_spilled_objects_handler
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/external_storage.py", line 487, in restore_spilled_objects
    return _external_storage.restore_spilled_objects(object_refs,
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/external_storage.py", line 421, in restore_spilled_objects
    self._size_check(metadata_len, buf_len, parsed_result.size)
TypeError: _size_check() missing 1 required positional argument: 'obtained_data_size'
An unexpected internal error occurred while the IO worker was restoring spilled objects.
2021-04-06 16:42:53,409	WARNING worker.py:1083 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 713, in ray._raylet.restore_spilled_objects_handler
  File "python/ray/_raylet.pyx", line 716, in ray._raylet.restore_spilled_objects_handler
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/external_storage.py", line 487, in restore_spilled_objects
    return _external_storage.restore_spilled_objects(object_refs,
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/external_storage.py", line 421, in restore_spilled_objects
    self._size_check(metadata_len, buf_len, parsed_result.size)
TypeError: _size_check() missing 1 required positional argument: 'obtained_data_size'
```

Checking S3, the objects are spilled as expected, but it seems the restoration failed.

**Comment by franklsf95** [comment]
This works now with #15757.
