### ISSUE TITLE
[tune][client] document how to use MLflow + Ray Client

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#14945]
### What is the problem?
Both the `MLflowLoggerCallback` and the `mlflow_mixin` do not work when used with Ray Client.

For the `MLflowLoggerCallback` we have to make sure that the tracking URI and experiment are set on the server side and not on the client side.

For the `mlflow_mixin` even when the tracking uri and experiment creation are wrapped in a remote function, the Tune trials are failing with the following error
```
(pid=10422) Traceback (most recent call last):
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 702, in _process_trial
(pid=10422)     results = self.trial_executor.fetch_result(trial)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 682, in fetch_result
(pid=10422)     result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
(pid=10422)     return func(*args, **kwargs)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/worker.py", line 1436, in get
(pid=10422)     raise value
(pid=10422) ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::ImplicitFunc.__init__() (pid=10426, ip=172.31.10.106)
(pid=10422)   File "python/ray/_raylet.pyx", line 502, in ray._raylet.execute_task
(pid=10422)   File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task.function_executor
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/_private/function_manager.py", line 566, in actor_method_executor
(pid=10422)     return method(__ray_actor, *args, **kwargs)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/tune/integration/mlflow.py", line 357, in __init__
(pid=10422)     experiment = self._mlflow.get_experiment_by_name(experiment_name)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 795, in get_experiment_by_name
(pid=10422)     return MlflowClient().get_experiment_by_name(name)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/mlflow/tracking/client.py", line 62, in __init__
(pid=10422)     self._tracking_client = TrackingServiceClient(final_tracking_uri)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 37, in __init__
(pid=10422)     self.store = utils._get_store(self.tracking_uri)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/utils.py", line 155, in _get_store
(pid=10422)     return _tracking_store_registry.get_store(store_uri, artifact_uri)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/registry.py", line 38, in get_store
(pid=10422)     return builder(store_uri=store_uri, artifact_uri=artifact_uri)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/utils.py", line 109, in _get_file_store
(pid=10422)     return FileStore(store_uri, store_uri)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 135, in __init__
(pid=10422)     mkdir(self.root_directory)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 113, in mkdir
(pid=10422)     raise e
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 110, in mkdir
(pid=10422)     os.makedirs(target)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/os.py", line 213, in makedirs
(pid=10422)     makedirs(head, exist_ok=exist_ok)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/os.py", line 213, in makedirs
(pid=10422)     makedirs(head, exist_ok=exist_ok)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/os.py", line 213, in makedirs
(pid=10422)     makedirs(head, exist_ok=exist_ok)
(pid=10422)   [Previous line repeated 5 more times]
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/os.py", line 223, in makedirs
(pid=10422)     mkdir(name, mode)
(pid=10422) PermissionError: [Errno 13] Permission denied: '/Users'
(pid=10422) 2021-03-25 22:28:01,232	ERROR trial_runner.py:732 -- Trial decorated_easy_objective_5b87c_00004: Error processing event.
(pid=10422) Traceback (most recent call last):
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 702, in _process_trial
(pid=10422)     results = self.trial_executor.fetch_result(trial)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 682, in fetch_result
(pid=10422)     result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
(pid=10422)     return func(*args, **kwargs)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/worker.py", line 1436, in get
(pid=10422)     raise value
(pid=10422) ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::ImplicitFunc.__init__() (pid=10421, ip=172.31.10.106)
(pid=10422)   File "python/ray/_raylet.pyx", line 502, in ray._raylet.execute_task
(pid=10422)   File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task.function_executor
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/_private/function_manager.py", line 566, in actor_method_executor
(pid=10422)     return method(__ray_actor, *args, **kwargs)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/tune/integration/mlflow.py", line 357, in __init__
(pid=10422)     experiment = self._mlflow.get_experiment_by_name(experiment_name)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 795, in get_experiment_by_name
(pid=10422)     return MlflowClient().get_experiment_by_name(name)
(pid=10422)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/mlflow/tracking/client.py", line 62, in __init__
```

**Comment by richardliaw** [comment]
This is only a problem if you use a local tracking server.
