### ISSUE TITLE
[Tune] [Ray Client] tune_cifar10_gluon example fails with Ray Client

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#14946]
### What is the problem?
Running the example with client on laptop and server on a p3.2xlarge instance results in the following error:
```
(pid=26371) 2021-03-25 20:20:54,842	ERROR trial_runner.py:732 -- Trial train_cifar10_957a8_00000: Error processing event.
(pid=26371) Traceback (most recent call last):
(pid=26371)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 702, in _process_trial
(pid=26371)     results = self.trial_executor.fetch_result(trial)
(pid=26371)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 682, in fetch_result
(pid=26371)     result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
(pid=26371)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
(pid=26371)     return func(*args, **kwargs)
(pid=26371)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/worker.py", line 1434, in get
(pid=26371)     raise value.as_instanceof_cause()
(pid=26371) ray.exceptions.RayTaskError(TuneError): ray::ImplicitFunc.train_buffered() (pid=26368, ip=172.31.10.106)
(pid=26371)   File "python/ray/_raylet.pyx", line 502, in ray._raylet.execute_task
(pid=26371)   File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task.function_executor
(pid=26371)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/_private/function_manager.py", line 566, in actor_method_executor
(pid=26371)     return method(__ray_actor, *args, **kwargs)
(pid=26371)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/tune/trainable.py", line 173, in train_buffered
(pid=26371)     result = self.train()
(pid=26371)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/tune/trainable.py", line 232, in train
(pid=26371)     result = self.step()
(pid=26371)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/tune/function_runner.py", line 366, in step
(pid=26371)     self._report_thread_runner_error(block=True)
(pid=26371)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/tune/function_runner.py", line 512, in _report_thread_runner_error
(pid=26371)     raise TuneError(
(pid=26371) ray.tune.error.TuneError: Trial raised an exception. Traceback:
(pid=26371) ray::ImplicitFunc.train_buffered() (pid=26368, ip=172.31.10.106)
(pid=26371)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/tune/function_runner.py", line 248, in run
(pid=26371)     self._entrypoint()
(pid=26371)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/tune/function_runner.py", line 315, in entrypoint
(pid=26371)     return self._trainable_func(self.config, self._status_reporter,
(pid=26371)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/tune/function_runner.py", line 580, in _trainable_func
(pid=26371)     output = fn()
(pid=26371)   File "tune_cifar10_gluon.py", line 119, in train_cifar10
(pid=26371)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/mxnet/gluon/data/dataloader.py", line 617, in __init__
(pid=26371)     original_sigint_handler = signal.signal(signal.SIGINT, signal.SIG_IGN)
(pid=26371)   File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/signal.py", line 47, in signal
(pid=26371)     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
(pid=26371) ValueError: signal only works in main thread
```

Looks like gluoncv's data loading does not work when run in a remote process.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
