### ISSUE TITLE
instability issues in cluster launcher

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#14997]
download the [data](https://drive.google.com/drive/folders/19GGSD_DvdM4Gi_UoVyCwbFVVGqgEWN2D?usp=sharing) (make sure you are logged in to anyscale account) and run:
- `ray up -y example-full.yaml`
- `ray attach example-full.yaml`
- `cd ~/data; python palettes.py`

it generates the errors shown below (1). If you wait 5 minutes and then rerun `python palettes.py` it generated below (2)
(1)
```
2021-03-29 10:08:55,570 INFO worker.py:655 -- Connecting to existing Ray cluster at address: 172.31.27.76:6379                                   [9/1866]
  1%|▊                                                                                                              | 940/134000 [00:08<58:42, 37.77it/s]
  2%|█▉                                                                                                           | 2380/134000 [00:42<18:04, 121.33it/s]
(autoscaler +1m0s) Tip: use `ray status` to view detailed autoscaling status. To disable autoscaler event messages, you can set AUTOSCALER_EVENTS=0.     
(autoscaler +1m0s) Resized to 160 CPUs.                                                                                                                  
(autoscaler +1m0s) Adding 28 nodes of type ray.worker.default.                                                                                           
  3%|███                                                                                                          | 3720/134000 [00:52<14:59, 144.84it/s]
(autoscaler +1m9s) Resized to 192 CPUs.                                                                                                                  
(autoscaler +1m9s) Adding 3 nodes of type ray.worker.default.                                                                                            
  4%|███▊                                                                                                         | 4700/134000 [00:59<15:36, 138.07it/s]
(autoscaler +1m16s) Adding 1 nodes of type ray.worker.default.
 16%|█████████████████▏                                                                                          | 21340/134000 [03:05<09:48, 191.48it/s]
(autoscaler +3m23s) Resized to 256 CPUs.
 17%|██████████████████▍                                                                                         | 22850/134000 [03:13<09:48, 188.72it/s]
(autoscaler +3m30s) Resized to 864 CPUs.
(autoscaler +3m30s) Adding 1 nodes of type ray.worker.default.
 18%|███████████████████▍                                                                                        | 24160/134000 [03:20<12:09, 150.60it/s]
(autoscaler +3m37s) Resized to 1184 CPUs.
 19%|████████████████████▌                                                                                       | 25520/134000 [03:27<09:21, 193.22it/s]
(autoscaler +3m44s) Resized to 1216 CPUs.
 25%|███████████████████████████▍                                                                                | 34080/134000 [04:13<09:01, 184.51it/s]
(autoscaler +4m30s) Removing 1 nodes of type ray.worker.default (idle).
 38%|█████████████████████████████████████████                                                                   | 51010/134000 [05:15<03:10, 436.67it/s]
(autoscaler +5m33s) Resized to 1248 CPUs.
 46%|██████████████████████████████████████████████████                                                          | 62070/134000 [05:39<02:18, 518.51it/s]
(autoscaler +5m57s) Removing 1 nodes of type ray.worker.default (idle).
 49%|████████████████████████████████████████████████████▋                                                       | 65310/134000 [05:46<02:08, 536.08it/s]
(autoscaler +6m3s) Removing 3 nodes of type ray.worker.default (idle).
 52%|███████████████████████████████████████████████████████▊                                                    | 69300/134000 [05:53<01:55, 561.48it/s]
(autoscaler +6m10s) Removing 28 nodes of type ray.worker.default (idle).
 55%|███████████████████████████████████████████████████████████▏                                                | 73430/134000 [05:59<01:28, 680.90it/s]
(autoscaler +6m17s) Removing 4 nodes of type ray.worker.default (idle).
 63%|███████████████████████████████████████████████████████████████████▉                                        | 84260/134000 [06:14<01:07, 739.24it/s]
2021-03-29 10:15:27,188 WARNING worker.py:1107 -- The node with node id 06c9f6941bafd537c595cd60bdc87367a120906a0ca5b90bb5c3b13d has been marked dead bec
ause the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.
 65%|█████████████████████████████████████████████████████████████████████▋                                      | 86510/134000 [06:16<01:06, 719.33it/s]
(autoscaler +6m34s) Resized to 1216 CPUs.
(autoscaler +6m34s) Removing 1 nodes of type ray.worker.default (idle).
```
(2)
```
 37%|████████████████████████████████████████▎                                                                   | 50000/134000 [02:56<03:39, 381.92it/s](autoscaler +3m13s) Restarting 3 nodes of type ray.worker.default (lost contact with raylet).
 41%|████████████████████████████████████████████▍                                                               | 55200/134000 [03:08<03:20, 393.50it/s](autoscaler +3m25s) Restarting 1 nodes of type ray.worker.default (lost contact with raylet).
 48%|███████████████████████████████████████████████████▍                                                        | 63860/134000 [03:26<02:21, 496.36it/s](autoscaler +3m43s) Removing 1 nodes of type ray.worker.default (launch failed).
 50%|██████████████████████████████████████████████████████▏                                                     | 67220/134000 [03:33<02:05, 530.40it/s](autoscaler +3m50s) Resized to 128 CPUs.
(autoscaler +3m50s) Removing 1 nodes of type ray.worker.default (idle).
(autoscaler +3m50s) Removing 1 nodes of type ray.worker.default (launch failed).
 53%|████████████████████████████████████████████████████████▉                                                   | 70700/134000 [03:39<01:55, 546.48it/s](autoscaler +3m57s) Resized to 160 CPUs.
(autoscaler +3m57s) Removing 2 nodes of type ray.worker.default (launch failed).
 55%|███████████████████████████████████████████████████████████▊                                                | 74180/134000 [03:46<01:44, 571.46it/s](autoscaler +4m3s) Resized to 192 CPUs.
(autoscaler +4m3s) Removing 3 nodes of type ray.worker.default (launch failed).
 64%|████████████████████████████████████████████████████████████████████▋                                       | 85180/134000 [04:02<01:04, 752.67it/s]2021-03-29 11:56:33,348 WARNING worker.py:1107 -- The node with node id 982af9fb3524a995361645dfb220d97f64a4c864ede40457f206e8c8 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.
 64%|█████████████████████████████████████████████████████████████████████▌                                      | 86330/134000 [04:03<01:00, 782.41it/s](autoscaler +4m20s) Resized to 160 CPUs.
 85%|█████████████████████████████████████████████████████████████████████████████████████████▊                | 113540/134000 [04:32<00:16, 1238.87it/s](autoscaler +4m49s) Removing 2 nodes of type ray.worker.default (idle).
 86%|██████████████████████████████████████████████████████████████████████████████████████████▋               | 114590/134000 [04:33<00:11, 1666.62it/s] 86%|██████████████████████████████████████████████████████████████████████████████████████████▊               | 114780/134000 [04:33<00:11, 1723.50it/s]100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 134000/134000 [04:38<00:00, 480.73it/s]
Traceback (most recent call last):
  File "palettes.py", line 42, in <module>
    palettes = ray.get(progress_bar(palettes))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::get_palette() (pid=126, ip=172.31.31.160)
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
RuntimeError: This function was not imported properly.
```

**Comment by AmeerHajAli** [comment]
CC @wuisawesome

**Comment by rkooo567** [comment]
@wuisawesome Isn't it just that none of tasks are scheduled on a newly started node because we are saturating nodes one by one?

**Comment by AmeerHajAli** [comment]
@rkooo567, It seems like if we have say 1M tasks that finish in a short period of time, the scheduling becomes a little bit unstable (the resources requested from GCS jump from 1k CPUs - 100k CPUs) and the newly launched nodes sometimes get some tasks and sometimes don't. It seems like having a very aggressive upscaling and downscaling can be problematic for such workloads. I think you are right that "none of tasks are scheduled on a newly started node because we are saturating nodes one by one".
It seems like if we let autoscaler be purely "serverless" with unbounded max_workers (and high upscaling speed) this issue will happen very frequently. If we limit the max workers here to 10 nodes, it becomes more stable.

**Comment by ericl** [comment]
So is it a scheduling speed problem? We have a fix proposed for q2.

One way of testing this is to try longer running tasks. If the issue goes
away, then that indicates it's scheduling speed that is the issue.

**Comment by AmeerHajAli** [comment]
I tested the following code to verify it is a scheduling issue:
```
import ray
ray.init(address="auto")
import time
@ray.remote
def f():
    time.sleep(0.0001)
ray.get([f.remote() for _ in range(1000000000)])
```

output:
```
(autoscaler +1m30s) Adding 5 nodes of type ray.worker.default.
(autoscaler +3m31s) Resized to 96 CPUs.
(autoscaler +3m37s) Resized to 160 CPUs.
(autoscaler +3m43s) Resized to 192 CPUs.
(autoscaler +8m35s) Removing 1 nodes of type ray.worker.default (idle).
2021-03-31 06:31:37,378 WARNING worker.py:1107 -- The node with node id 89ca57001f90101e5505af9c34ba319ad08a2956cedfdd5c2c454d45 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.
(autoscaler +9m38s) Resized to 160 CPUs.
(autoscaler +19m31s) Removing 1 nodes of type ray.worker.default (idle).
2021-03-31 06:42:05,287 WARNING worker.py:1107 -- The node with node id 13bb817540ad80aee4b0561be6ea2f26ff18f01a043e4ea2718a1732 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.
(autoscaler +20m9s) Resized to 128 CPUs.
```

```

**Comment by ericl** [comment]
Glad to have it confirmed, seems like a pretty concrete target to improve
then. This will be prioritized in q2, there's quite a few options like
increasing the worker leasing parallelism.

**Comment by ericl** [comment]
cc @scv119 this might also be causing skew issues in ML ingest

**Comment by ericl** [comment]
I think a good strategy here would be to, instead of keeping "at most 1 outstanding lease request per category", keep "at most 1 outstanding lease request per category per node".

For example, suppose the home raylet told us to lease from node 1, then we would issue a lease request to node 1, but if there are remaining tasks, we can concurrently ask the home raylet for another lease. So even if node 1 was blocked starting workers for a long time, we could still get other lease requests out to other nodes in parallel.
