### ISSUE TITLE
[Kubernetes][autoscaler] More problems during scale down

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#14996]
### What is the problem?

We're still experiencing concurrency issues during scale down on K8s.
Logs: https://controlc.com/e40990dd

Will use comments on this issue to log investigation.

Discussion context: 
https://discuss.ray.io/t/stuck-trying-to-take-down-workers/1309/21

Previous issue:
https://github.com/ray-project/ray/issues/14812

Previous PR:
https://github.com/ray-project/ray/pull/14976

*Ray version and other system information (Python version, TensorFlow version, OS):*

Autoscaler using recent master.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by DmitriGekhtman** [comment]
First, a heartbeat is missed from a worker pod and the autoscaler runs a NodeUpdater thread to try to recover it  
```2021-03-29 03:17:17,632	WARNING autoscaler.py:571 -- StandardAutoscaler: ray-worker-cpu-hcrtn: No recent heartbeat, restarting Ray to recover...
2021-03-29 03:17:17,706	INFO command_runner.py:172 -- NodeUpdater: ray-worker-cpu-hcrtn: Running kubectl -n ray exec -it ray-worker-cpu-hcrtn -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
```

Then the pod is marked idle and deleted (maybe while the above recovery NodeUpdater is running?)
```
2021-03-29 03:17:47,014	INFO autoscaler.py:198 -- StandardAutoscaler: ray-worker-cpu-hcrtn: Terminating idle node.
2021-03-29 03:17:47,058	INFO node_provider.py:154 -- KubernetesNodeProvider: calling delete_namespaced_podn
```

The update fails and the autoscaler tries to terminate the pod, in the process attempting to read from its metadata.labels, even though the pod is gone. That leads to a 404 error. 
```
2021-03-29 03:19:37,511	ERROR autoscaler.py:270 -- StandardAutoscaler: ray-worker-cpu-hcrtn: Terminating failed to setup/initialize node.
2021-03-29 03:19:37,514	ERROR autoscaler.py:142 -- StandardAutoscaler: Error during autoscaling.
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/autoscaler.py", line 140, in update
    self._update()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/autoscaler.py", line 274, in _update
    self._get_node_type(node_id) + " (launch failed).",
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/autoscaler.py", line 601, in _get_node_type
    node_tags = self.provider.node_tags(node_id)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/kubernetes/node_provider.py", line 70, in node_tags
    pod = core_api().read_namespaced_pod(node_id, self.namespace)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 22785, in read_namespaced_pod
    return self.read_namespaced_pod_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 22880, in read_namespaced_pod_with_http_info
    return self.api_client.call_api(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/rest.py", line 239, in GET
    return self.request("GET", url,
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/rest.py", line 233, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'e57dfa1c-23ec-4a71-b0d9-3fb090332e44', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Mon, 29 Mar 2021 10:19:37 GMT', 'Content-Length': '208'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"ray-worker-cpu-hcrtn\" not found","reason":"NotFound","details":{"name":"ray-worker-cpu-hcrtn","kind":"pods"},"code":404}
```

Autoscaler update fails and retries four more times, each time getting the same error, then the autoscaler gives up and stops.

**Comment by DmitriGekhtman** [comment]
Summarizing what probably happened:
For whatever reason, a worker pod's heartbeat was missed and a thread was started to recover the pod.
While that update was running, the pod passed the idle timeout and was terminated.
As a result, the update failed and the autoscaler tried to terminate the node again, which led to an error.

The error restarted the autoscaler update iteration, which then hit the same problem again because the termination logic loops over node_ids with completed updates rather than ids of non_terminated_nodes.

**Comment by DmitriGekhtman** [comment]
A possible fix is to intersect the list of nodes with failed updates with the list of active nodes before passing the list to provider.terminate_nodes.

**Comment by ijrsvt** [comment]
@DmitriGekhtman I don't think #15019 actually solves the exact bug here. The bug here is coming from the call to `_get_node_type` (which is for the autoscaler to pass info to the `EventSummarizer`).
