### ISSUE TITLE
[release/core] data_processing_tests/streaming_shuffle.py fails trying to split `redis_address`

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#15013]
Running the release test as described in the release test readme gives the following output:

```
Test streaming shuffle with a single node.
Shuffle size: 93.13225746154785GB
start map
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [04:44<00:00,  1.42s/it]
start shuffle.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 199/200 [10:30<00:00,  1.12it/s]
Shuffled 99500000000 bytes in 916.1025545597076 seconds in a single node.

Traceback (most recent call last):
  File "workloads/streaming_shuffle.py", line 176, in <module>
    run_single_node()
  File "workloads/streaming_shuffle.py", line 147, in run_single_node
    display_spilling_info(address["redis_address"])
  File "workloads/streaming_shuffle.py", line 40, in display_spilling_info
    raylet["NodeManagerAddress"], raylet["NodeManagerPort"])
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/internal/internal_api.py", line 32, in memory_summary
    return (memory_summary(state, group_by, sort_by, line_wrap) +
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/new_dashboard/memory_utils.py", line 345, in memory_summary
    for raylet in state.node_table():
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/state.py", line 305, in node_table
    self._check_connected()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/state.py", line 55, in _check_connected
    self._really_init_global_state()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/state.py", line 92, in _really_init_global_state
    self.redis_address, self.redis_password)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 444, in create_redis_client
    redis_ip_address, redis_port = redis_address.split(":")
ValueError: not enough values to unpack (expected 2, got 1)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████
```

We're unsetting `RAY_ADDRESS`, does this have to do with the error?

cc @rkooo567

**Comment by rkooo567** [comment]
@krfricke lmk if you'd like to run this together.

**Comment by krfricke** [comment]
Original streaming_shuffle.py now:

```
(tensorflow_p36) ubuntu@ip-172-31-57-67:~/data_processing_tests$ unset RAY_ADDRESS; python workloads/streaming_shuffle.py
Redis address 172.31.57.67:6379
2021-04-01 13:41:34,246 INFO services.py:1270 -- View the Ray dashboard at http://127.0.0.1:8265
Redis address 172.31.57.67:6379
Redis address 172.31.57.67:6379
Redis address 172.31.57.67:6379
Redis address 172.31.57.67:61812
Redis address 172.31.57.67:6379
Redis address 172.31.57.67:61812
Redis address 172.31.57.67:6379


Test streaming shuffle with a single node.
Shuffle size: 93.13225746154785GB
start map
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [02:40<00:00,  1.24it/s]
start shuffle.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 199/200 [10:28<00:01,  1.21s/it]
Shuffled 99500000000 bytes in 790.3211300373077 seconds in a single node.

Redis address 172.31.57.67:6379
Redis address 172.31.57.67:61812
Redis address 172.31.57.67:41331
Aborted (core dumped)

```

after adjusting this line:
```
    memory_summary = ray.internal.internal_api.memory_summary(
        f"{raylet['NodeManagerAddress']}:{raylet['NodeManagerPort']}")
 ```
 Running the module tests now

**Comment by krfricke** [comment]
```
(tensorflow_p36) ubuntu@ip-172-31-57-67:~/data_processing_tests$ python -m ray.experimental.shuffle --num-cpus=32 --num-partitions=200 --partition-size=500e6 --object-store-memory=20e9
Start a new cluster...
Redis address 172.31.57.67:6379
2021-04-01 14:02:15,570 INFO services.py:1270 -- View the Ray dashboard at http://127.0.0.1:8265
Redis address 172.31.57.67:6379
Redis address 172.31.57.67:6379
Redis address 172.31.57.67:6379
Redis address 172.31.57.67:57875
Redis address 172.31.57.67:6379
Redis address 172.31.57.67:57875
Redis address 172.31.57.67:6379
Map Progress.: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [03:22<00:00,  1.01s/it]
Reduce Progress.: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [03:22<00:00,  1.01s/it]

Redis address 172.31.57.67:6379
Redis address 172.31.57.67:57875
--- Aggregate object store stats across all nodes ---
Plasma memory usage 14661 MiB, 6149 objects, 76.87% full
Spilled 80367 MiB, 33705 objects, avg write throughput 399 MiB/s
Restored 79267 MiB, 33244 objects, avg read throughput 5319 MiB/s
Objects consumed by Ray tasks: 95377 MiB.

Shuffled 95367 MiB in 205.0442304611206 seconds
2021-04-01 14:05:59,134 ERROR external_storage.py:327 -- Error cleaning up spill files
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/external_storage.py", line 321, in _destroy_external_storage
    shutil.rmtree(directory_path)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/shutil.py", line 490, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/shutil.py", line 488, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/ray/session_2021-04-01_14-02-14_118883_29352/ray_spilled_objects'
```

```
(tensorflow_p36) ubuntu@ip-172-31-57-67:~/data_processing_tests$ python -m ray.experimental.shuffle --num-cpus=8 --num-partitions=200 --partition-size=500e6 --object-store-memory=5e9 --num-nodes=4                                                                                    
Emulating a cluster...                                                                                                                                                                                                                                                                  
Num nodes: 4                                                                                                                                                                                                                                                                            
Num CPU per node: 8                                        
Object store memory per node: 5000000000.0                 
Redis address 172.31.57.67:6379                                                                                                                                                                                                                                                         
Redis address 172.31.57.67:6379                                                                                          
Redis address 172.31.57.67:6379
Redis address 172.31.57.67:6379                                                                 
Redis address 172.31.57.67:29413
Redis address 172.31.57.67:6379
Redis address 172.31.57.67:29413
Redis address 172.31.57.67:6379 
Redis address 172.31.57.67:29413
Redis address 172.31.57.67:6379 
Redis address 172.31.57.67:6379
Redis address 172.31.57.67:29413
Redis address 172.31.57.67:6379
Redis address 172.31.57.67:6379           
Redis address 172.31.57.67:29413 
Redis address 172.31.57.67:6379
Redis address 172.31.57.67:6379                                                                                                                                                                                                                                                         
Redis address 172.31.57.67:29413
2021-04-01 14:08:56,716 INFO worker.py:654 -- Connecting to existing Ray cluster at address: 172.31.57.67:6379                                                                                                                                                                          
Redis address 172.31.57.67:6379                                          
Redis address 172.31.57.67:6379
Redis address 172.31.57.67:29413
Redis address 172.31.57.67:6379 
Map Progress.: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [03:52<00:00,  1.16s/it$
Reduce Progress.: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [03:52<00:00,  1.16s/it$
                                                                                                                                                                                        
Redis address 172.31.57.67:6379
Redis address 172.31.57.67:29413
--- Aggregate object store stats across all nodes ---                                           
Plasma memory usage 7513 MiB, 3151 objects, 39.39% full
Spilled 87394 MiB, 36652 objects, avg write throughput 378 MiB/s
Restored 85314 MiB, 35780 objects, avg read throughput 4450 MiB/s
Objects consumed by Ray tasks: 95377 MiB.
                               
Shuffled 95367 MiB in 234.53933811187744 seconds
2021-04-01 14:13:01,234 ERROR worker.py:1085 -- listen_error_messages_raylet: Connection closed by server.
2021-04-01 14:13:01,237 ERROR worker.py:926 -- print_logs: Connection closed by server.
2021-04-01 14:13:01,241 ERROR import_thread.py:88 -- ImportThread: Connection closed by server.
```

Do these logs seem ok?

**Comment by rkooo567** [comment]
This seems to be fine now. We might need to update some stuff, but I can do that from the next release. 

```
2021-04-01 14:05:59,134 ERROR external_storage.py:327 -- Error cleaning up spill files
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/external_storage.py", line 321, in _destroy_external_storage
    shutil.rmtree(directory_path)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/shutil.py", line 490, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/shutil.py", line 488, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/ray/session_2021-04-01_14-02-14_118883_29352/ray_spilled_objects'
```

Also, does it happen consistently?

**Comment by krfricke** [comment]
Only ran each command once. I'll run this test again with the final RC and will let you know. Thanks for looking into this!
