### ISSUE TITLE
[autoscaler] KeyError on Ray Azure autoscaler example 

### ISSUE THREAD

**Issue by richardlin047** [ray-project/ray#15078]
### What is the problem?
Tried following the autoscaler Azure example here: https://docs.ray.io/en/releases-1.2.0/cluster/cloud.html?highlight=azure#aws-gcp-azure
Calling `ray up ray/python/ray/autoscaler/azure/example-full.yaml` results in error:
```
% ray up ray/python/ray/autoscaler/azure/example-full.yaml
Cluster: default

Checking Azure environment settings
Traceback (most recent call last):
  File "/Users/richard/.pyenv/versions/data-shuffle/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/Users/richard/.pyenv/versions/3.8.5/envs/data-shuffle/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1519, in main
    return cli()
  File "/Users/richard/.pyenv/versions/3.8.5/envs/data-shuffle/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/richard/.pyenv/versions/3.8.5/envs/data-shuffle/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/richard/.pyenv/versions/3.8.5/envs/data-shuffle/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/richard/.pyenv/versions/3.8.5/envs/data-shuffle/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/richard/.pyenv/versions/3.8.5/envs/data-shuffle/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/richard/.pyenv/versions/3.8.5/envs/data-shuffle/lib/python3.8/site-packages/ray/scripts/scripts.py", line 887, in up
    create_or_update_cluster(
  File "/Users/richard/.pyenv/versions/3.8.5/envs/data-shuffle/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 224, in create_or_update_cluster
    config = _bootstrap_config(config, no_config_cache=no_config_cache)
  File "/Users/richard/.pyenv/versions/3.8.5/envs/data-shuffle/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 299, in _bootstrap_config
    resolved_config = provider_cls.bootstrap_config(config)
  File "/Users/richard/.pyenv/versions/3.8.5/envs/data-shuffle/lib/python3.8/site-packages/ray/autoscaler/_private/azure/node_provider.py", line 298, in bootstrap_config
    return bootstrap_azure(cluster_config)
  File "/Users/richard/.pyenv/versions/3.8.5/envs/data-shuffle/lib/python3.8/site-packages/ray/autoscaler/_private/azure/config.py", line 20, in bootstrap_azure
    config = _configure_key_pair(config)
  File "/Users/richard/.pyenv/versions/3.8.5/envs/data-shuffle/lib/python3.8/site-packages/ray/autoscaler/_private/azure/config.py", line 107, in _configure_key_pair
    config[node_type]["azure_arm_parameters"]["adminUsername"] = ssh_user
KeyError: 'azure_arm_parameters'
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 1.2.0
Python 3.8.5
MacOSX 10.15.7

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
1. Git clone Ray
2. Run `ray up ray/python/ray/autoscaler/azure/example-full.yaml`

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by raz4** [comment]
Upgrading to Ray 1.3.0 resolved this issue for me.

`pip install ray==1.3.0`
