### ISSUE TITLE
ConnectionResetError: [Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by Nishanthml** [ray-project/ray#15131]
**command**: ray start --head --port=6379
**OS version** : macOS Catalina 10.15.7
**Python version**: 3.7
**Ray version**: 1.2.0

I am trying to start the ray in my local system inside anaconda environment. I am facing the below error, could you please help me out.

`Traceback (most recent call last):
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/redis/connection.py", line 427, in read_from_socket
    bufflen = recv_into(self._sock, self._buffer)
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/redis/_compat.py", line 75, in recv_into
    return sock.recv_into(*args, **kwargs)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nisml/anaconda3/envs/raytest/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1519, in main
    return cli()
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/ray/scripts/scripts.py", line 558, in start
    ray_params, head=True, shutdown_at_exit=block, spawn_reaper=block)
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/ray/node.py", line 220, in __init__
    self.start_head_processes()
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/ray/node.py", line 827, in start_head_processes
    self.start_redis()
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/ray/node.py", line 642, in start_redis
    fate_share=self.kernel_fate_share)
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/ray/_private/services.py", line 852, in start_redis
    primary_redis_client.set("NumRedisShards", str(num_redis_shards))
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/redis/client.py", line 1801, in set
    return self.execute_command('SET', *pieces)
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/redis/connection.py", line 567, in connect
    self.on_connect()
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/redis/connection.py", line 643, in on_connect
    auth_response = self.read_response()
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/Users/nisml/anaconda3/envs/raytest/lib/python3.7/site-packages/redis/connection.py", line 453, in read_from_socket
    (ex.args,))
redis.exceptions.ConnectionError: Error while reading from socket: (54, 'Connection reset by peer')`

**Comment by Nishanthml** [comment]
The above issue is due to VPN, I was able to solve it by adding `_node_ip_address="0.0.0.0"` as parameter in ray.init() command.
