### ISSUE TITLE
Monitor crashes when attempting to recreate actors which require unavailable GPUs.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1514]
Right now when we try to create an actor, if there aren't enough GPUs available, we raise an exception (in Python). However, when machines are lost, the monitor attempts to recreate the actors that were on those machines, and if there are not enough GPU resources to do so (e.g., because GPU machines were lost) then an exception will be raised that kills the monitor. This is undesirable. For now it should push an error to the user, and later the actor creation task should probably be queued in the global scheduler or something like that.

To reproduce the problem you need two machines.

1. On machine 1, run
```
ray start --head --redis-port=6379
```

2. On machine 2, run
```
ray start --redis-address=<head-node-ip>:6379 --num-gpus=1
```

3. On machine 1, run the following in Python
```python
import ray

ray.init(redis_address="<head-node-ip>:6379")

@ray.remote(num_gpus=1)
class Foo(object):
    pass

f = Foo.remote()
```

4. On machine 2, run `ray stop`.

5. Look at the monitor logs in `/tmp/raylogs`. I see 

```
WARNING:root:Removed b'plasma_manager', client ID e0a1c05a0a739567e7d1df4e37a030986e74a406
WARNING:root:Removed b'local_scheduler', client ID 5d2c70744cabeaa2c08fd8b625a5fe9c3b708c91
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/ray/monitor.py", line 677, in <module>
    monitor.run()
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/ray/monitor.py", line 620, in run
    self.cleanup_actors()
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/ray/monitor.py", line 132, in cleanup_actors
    self.redis)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/ray/utils.py", line 301, in select_local_scheduler
    "information is {}.".format(local_schedulers))
Exception: Could not find a node with enough GPUs or other resources to create this actor. The local scheduler information is [{'CPU': 4.0, 'Deleted': False, 'LocalSchedulerSocketName': '/tmp/scheduler86951894', 'DBClientID': '70eee6f0a9e16adca6f13dd3edd523ddf8a24a45', 'AuxAddress': '172.31.21.156:32315', 'GPU': 0.0, 'ClientType': 'local_scheduler'}].
```

**Comment by robertnishihara** [comment]
This error is no longer relevant since that code in `monitor.py` was removed in #1668. The monitor should have nothing to do with GPUs.
