### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#1517]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.13.12
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.3.0
- **Python version**: 3.6.3
- **Exact command to reproduce**: Running custom environment 

### Describe the problem
I ran a multi-agent experiment with batch size 6000 (30 rollouts) on a node w/ 16 CPUs, after 1 iteration I get a MemoryError (logged below). If it helps, there were 40 agents in the system w/ a state space of size 300. Are the resultant samples just too large to process? 

### Source code / logs
Remote function sample failed with:
Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/worker.py", line 767, in _process_task
    *arguments)
  File "/home/ubuntu/ray/python/ray/actor.py", line 162, in actor_method_executor
    return method(actor, *args)
  File "/home/ubuntu/ray/python/ray/rllib/ppo/ppo_evaluator.py", line 198, in sample
    return SampleBatch.concat_samples(all_samples)
  File "/home/ubuntu/ray/python/ray/rllib/optimizers/sample_batch.py", line 30, in concat_samples
    return reduce(lambda a, b: a.concat(b), samples)
  File "/home/ubuntu/ray/python/ray/rllib/optimizers/sample_batch.py", line 30, in <lambda>
    return reduce(lambda a, b: a.concat(b), samples)
  File "/home/ubuntu/ray/python/ray/rllib/optimizers/sample_batch.py", line 45, in concat
    out[k] = np.concatenate([self.data[k], other.data[k]])
MemoryError

**Comment by robertnishihara** [comment]
How much memory is on the machine? And what is the size of the rollouts being generated?

**Comment by eugenevinitsky** [comment]
Resolved by #1529, thanks!
