### ISSUE TITLE
[Client] Cannot `ray.put` pandas DataFrame 

### ISSUE THREAD

**Issue by ijrsvt** [ray-project/ray#15183]
### What is the problem?
* I cannot `ray.put` a pandas DataFrame object when using Ray client

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
1. Setup ray client
2. Run the following script:
```
import pandas as pd
df = pd.DataFrame()
ray.put(df) #7802 
```
Error here:
```
Got Error from data channel -- shutting down: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating responses: 'DataFrame' object has no attribute '_data'"
        debug_error_string = "{"created":"@1617837783.938287929","description":"Error received from peer ipv4:IP_ADDR:8081","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception iterating responses: 'DataFrame' object has no attribute '_data'","grpc_status":2}"
>
Exception in thread Thread-32:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/anyscale/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/envs/anyscale/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/envs/anyscale/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 90, in _data_main
    raise e
  File "/home/ubuntu/anaconda3/envs/anyscale/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 64, in _data_main
    for response in resp_stream:
  File "/home/ubuntu/anaconda3/envs/anyscale/lib/python3.7/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/home/ubuntu/anaconda3/envs/anyscale/lib/python3.7/site-packages/grpc/_channel.py", line 803, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating responses: 'DataFrame' object has no attribute '_data'"
        debug_error_string = "{"created":"@1617837783.938287929","description":"Error received from peer ipv4:IP_ADDR:8081","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception iterating responses: 'DataFrame' object has no attribute '_data'","grpc_status":2}"
>
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ijrsvt** [comment]
cc @AmeerHajAli @DmitriGekhtman 
This is what I got when trying to use Modin!

**Comment by AmeerHajAli** [comment]
Cc @devin-petersohn

**Comment by ijrsvt** [comment]
Ugh, this is actually fine. The error was that my local Ray client was using pandas==`1.2.3` and the Server was using `pandas==1.0.5`. The old version of `DataFrame` did not have the property `_data`, while the new one does. 😢
