### ISSUE TITLE
Bad error message when missing `self` arg in methods in FastAPI class-based view

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#15191]
```python
from fastapi import FastAPI

import ray
from ray import serve

app = FastAPI()

@serve.ingress(app)
class Test:
    @app.get("/")
    def f():
        return "Hello 1"
```

```
Traceback (most recent call last):
  File "repro.py", line 9, in <module>
    class Test:
  File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 973, in decorator
    make_fastapi_class_based_view(app, cls)
  File "/Users/eoakes/code/ray/python/ray/serve/utils.py", line 428, in make_fastapi_class_based_view
    old_self_parameter = old_parameters[0]
IndexError: list index out of range
```

**Comment by edoakes** [comment]
Fixed by @simon-mo at some point.
