### ISSUE TITLE
[rllib] IMPALA: Actor died unexpectedly before finishing this task.

### ISSUE THREAD

**Issue by mochangheng** [ray-project/ray#15206]
### What is the problem?

When running the IMPALA algorithm with multi-agent environments, the program crashes after training for about 2 hours with the error message `The actor died unexpectedly before finishing this task`.

Specifically, I was able to reproduce the error by running a modified version of the `multi_agent_custom_policy.py` example to use IMPALA instead of PG. The program crashed after training for about 26M steps.

Traceback:
```
== Status ==
Memory usage on this node: 9.7/15.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 9.0/16 CPUs, 1.0/1 GPUs, 0.0/7.44 GiB heap, 0.0/3.72 GiB objects (0.0/1.0 accelerator_type:X)
Result logdir: /home/mch0717/ray_results/IMPALA
Number of trials: 1/1 (1 RUNNING)


2021-04-08 17:21:45,525	ERROR trial_runner.py:732 -- Trial IMPALA_multi_agent_cartpole_e6e95_00000: Error processing event.
Traceback (most recent call last):
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 702, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 682, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 48, in wrapper
    return func(*args, **kwargs)
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/worker.py", line 1438, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::IMPALA.train_buffered() (pid=11764, ip=192.168.50.76)
  File "python/ray/_raylet.pyx", line 502, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task.function_executor
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/_private/function_manager.py", line 566, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/tune/trainable.py", line 173, in train_buffered
    result = self.train()
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 573, in train
    raise e
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 562, in train
    result = Trainable.train(self)
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/tune/trainable.py", line 232, in train
    result = self.step()
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 162, in step
    res = next(self.train_exec_impl)
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 1075, in build_union
    item = next(it)
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 876, in apply_flatten
    for item in it:
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 828, in add_wait_hooks
    item = next(it)
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 876, in apply_flatten
    for item in it:
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 551, in base_iterator
    batch = ray.get(obj_ref)
  File "/home/mch0717/anaconda3/envs/rl/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 48, in wrapper
    return func(*args, **kwargs)
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
```

Ray version: 2.0.0.dev0
Python version: 3.8
Pytorch version: 1.8.1
OS: Ubuntu 18.04

### Reproduction (REQUIRED)
The script I used to reproduce the issue is a modified version of `multi_agent_custom_policy.py`. Here is the full script:
```python3
"""Example of running a custom hand-coded policy alongside trainable policies.

This example has two policies:
    (1) a simple PG policy
    (2) a hand-coded policy that acts at random in the env (doesn't learn)

In the console output, you can see the PG policy does much better than random:
Result for PG_multi_cartpole_0:
  ...
  policy_reward_mean:
    pg_policy: 185.23
    random: 21.255
  ...
"""

import argparse
import gym
import os

import ray
from ray import tune
from ray.tune.registry import register_env
from ray.rllib.examples.env.multi_agent import MultiAgentCartPole
from ray.rllib.examples.policy.random_policy import RandomPolicy
from ray.rllib.utils.test_utils import check_learning_achieved

parser = argparse.ArgumentParser()
parser.add_argument("--torch", action="store_true")
parser.add_argument("--as-test", action="store_true")
parser.add_argument("--stop-iters", type=int, default=20)
parser.add_argument("--stop-reward", type=float, default=150)
parser.add_argument("--stop-timesteps", type=int, default=100000)

if __name__ == "__main__":
    args = parser.parse_args()
    ray.init()

    # Simple environment with 4 independent cartpole entities
    register_env("multi_agent_cartpole",
                 lambda _: MultiAgentCartPole({"num_agents": 4}))
    single_env = gym.make("CartPole-v0")
    obs_space = single_env.observation_space
    act_space = single_env.action_space

    stop = {
        "training_iteration": args.stop_iters,
        "episode_reward_mean": args.stop_reward,
        "timesteps_total": args.stop_timesteps,
    }

    config = {
        "env": "multi_agent_cartpole",
        "multiagent": {
            "policies": {
                "pg_policy": (None, obs_space, act_space, {
                    "framework": "torch" if args.torch else "tf",
                }),
                "random": (RandomPolicy, obs_space, act_space, {}),
            },
            "policy_mapping_fn": (
                lambda agent_id: ["pg_policy", "random"][agent_id % 2]),
        },
        "framework": "torch" if args.torch else "tf",
        # Use GPUs iff `RLLIB_NUM_GPUS` env var set to > 0.
        "num_gpus": 1,
	"num_workers": 8,
    }

    results = tune.run("IMPALA", config=config, stop=stop, verbose=1)

    if args.as_test:
        check_learning_achieved(results, args.stop_reward)

    ray.shutdown()
```

The command I used to run the script: `python example.py --torch --stop-iters 50000 --stop-reward 1000 --stop-timesteps 150000000`

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by robot-xyh** [comment]
I ran into the same problem
