### ISSUE TITLE
[release/rllib] rllib regression test on tensorflow fails

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#15217]
```
(pid=1694) 2021-04-09 07:28:59,649      ERROR worker.py:395 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::IMPALA.__init__() (pid=1694, ip=172.31.19.81)
(pid=1694)   File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
(pid=1694)   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
(pid=1694)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=1694)     return method(__ray_actor, *args, **kwargs)
(pid=1694)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 121, in __init__
(pid=1694)     Trainer.__init__(self, config, env, logger_creator)
(pid=1694)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 516, in __init__
(pid=1694)     super().__init__(config, logger_creator)
(pid=1694)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 98, in __init__
(pid=1694)     self.setup(copy.deepcopy(self.config))
(pid=1694)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 707, in setup
(pid=1694)     self._init(self.config, self.env_creator)
(pid=1694)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 153, in _init
(pid=1694)     num_workers=self.config["num_workers"])
(pid=1694)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 789, in _make_workers
(pid=1694)     logdir=self.logdir)
(pid=1694)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 98, in __init__
(pid=1694)     spaces=spaces,
(pid=1694)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 357, in _make_worker
(pid=1694)     spaces=spaces,
(pid=1694)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 543, in __init__
(pid=1694)     policy_config["framework"]))
(pid=1694) RuntimeError: GPUs were assigned to this worker by Ray, but your DL framework (tf) reports GPU acceleration is disabled. This could be due to a bad CUDA- or tf installation.
Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/rllib", line 8, in <module>
    sys.exit(cli())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/scripts.py", line 34, in cli
    train.run(options, train_parser)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/train.py", line 228, in run
    concurrent=True)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 637, in run_experiments
    callbacks=callbacks).trials
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 543, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [A2C_BreakoutNoFrameskip-v4_d6891_00000, A2C_BreakoutNoFrameskip-v4_d6891_00001, APEX_BreakoutNoFrameskip-v4_d6891_00002, APEX_BreakoutNoFrameskip-v4_d6891_00003, DQN_BreakoutNoFrameskip-v4_d6891_00004, DQN_BreakoutNoFrameskip-v4_d6891_00005, IMPALA_BreakoutNoFrameskip-v4_d6891_00006, IMPALA_BreakoutNoFrameskip-v4_d6891_00007, PPO_BreakoutNoFrameskip-v4_d6891_00008, PPO_BreakoutNoFrameskip-v4_d6891_00009, SAC_HalfCheetahBulletEnv-v0_d6891_00010, SAC_HalfCheetahBulletEnv-v0_d6891_00011])
```

cc @sven1977

**Comment by ijrsvt** [comment]
I have very little context on the details of the failure here, but between this release and the previous release I think the bundled CUDA version was bumped from 10.1 -> 11

**Comment by sven1977** [comment]
This is a tf version vs CUDA version mismatch causing tf to not find the GPU.
If you do a `tf.config.list_physical_devices()` on the machine, you'll probably only see the CPU(s).

**Comment by krfricke** [comment]
On `anyscale/ray-ml:nightly-gpu`:

```
$ ls -alp /usr/local/cuda
lrwxrwxrwx 1 root root 9 Dec 14 15:31 /usr/local/cuda -> cuda-10.1/
```

```
(base) ray@ip-172-31-4-177:/$ sudo apt list --installed | grep cuda

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

cuda-compat-10-1/unknown,unknown,now 418.181.07-1 amd64 [installed]
cuda-cudart-10-1/unknown,now 10.1.243-1 amd64 [installed]
cuda-cufft-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-curand-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-cusolver-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-cusparse-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-libraries-10-1/unknown,now 10.1.243-1 amd64 [installed]
cuda-license-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-npp-10-1/unknown,now 10.1.243-1 amd64 [installed]
cuda-nvgraph-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nvjpeg-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nvrtc-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nvtx-10-1/unknown,now 10.1.243-1 amd64 [installed]
libcudnn7/unknown,now 7.6.5.32-1+cuda10.1 amd64 [installed,upgradable to: 7.6.5.32-1+cuda10.2]
libcudnn7-dev/unknown,now 7.6.5.32-1+cuda10.1 amd64 [installed,upgradable to: 7.6.5.32-1+cuda10.2]
libnccl2/unknown,now 2.8.3-1+cuda10.1 amd64 [installed,upgradable to: 2.8.4-1+cuda11.2]
```

Does this mean the packaged version in `anyscale/ray-ml:nightly-gpu` is outdated?

**Comment by ijrsvt** [comment]
@krfricke Yes, you are right. I think the `anyscale/ray-ml:nightly-gpu` image is outdated, but the `ray/ray-ml:nightly-gpu` image is not.

**Comment by sven1977** [comment]
@ijrsvt , this has been a common problem for a few months at least with any of our "ml" + "gpu" containers in the product (nightly or not). Doing the following simply does not work:
```
$ python
>>> import tensorflow as tf
>>> tf.config.list_physical_devices()
```
The above does not include the GPU(s), even though they can be seen via e.g. `nvidia-smi`.

**Comment by ijrsvt** [comment]
@sven1977 I'm not 100% sure what the best way forward is here. The issue is that Tensorflow has an extremely [narrow window of GPU support](https://www.tensorflow.org/install/source#gpu). 

<img width="860" alt="Screen Shot 2021-04-13 at 8 17 38 AM" src="https://user-images.githubusercontent.com/21353794/114577260-b725c080-9c30-11eb-8271-239fdfe66b1c.png">



The product is currently using CUDA 10.1, which is compatible with Ray 1.2 (which requires TF 2.3). 
Nightly OSS docker images use CUDA 11, which is what TF 2.4 needs and what nightly Ray has pinned in `requirements.txt`

**Comment by krfricke** [comment]
A first good step would be to document this somewhere. I assumed that `rayproject/ray-ml` and `anyscale/ray-ml` and all their tags are equivalent except for additional dependencies installed in `anyscale`, and I'd expect people working with OSS and switching to the product would do the same. For `latest` this is expected, but `nightly` in `anyscale` seems to refer to the nightly _product_ build, not the nightly ray build. That wasn't clear to me.

For this release we can install `tensorflow_gpu==2.3.0` to run the tests.

**Comment by krfricke** [comment]
Closing this since the run succeeded with tf 2.3.0

**Comment by sven1977** [comment]
Got it, thanks for clarifying @ijrsvt and @krfricke !
The container should have tf==2.3 pinned then. If not, we have to change the CUDA version AND also make sure that torch is working properly with that same CUDA version.

**Comment by ijrsvt** [comment]
I can double test that Torch works with this.

@krfricke Yeah, the `nightly` story with ray vs anyscale is a bit hazy.
