### ISSUE TITLE
[release/stress test] tead_dead_actors fails

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#15230]
The test throws various errors, see attached output:

[command_scd_xIGx58xF2ojXQbk7jdhdy.log](https://github.com/ray-project/ray/files/6288285/command_scd_xIGx58xF2ojXQbk7jdhdy.log)

tail:

```
2021-04-09 12:48:56,386 WARNING worker.py:1085 -- A worker died or was killed while executing task ffffffffffffffff8dd681efcd748ad90ca47fd101000000.
2021-04-09 12:48:56,386 WARNING worker.py:1085 -- A worker died or was killed while executing task ffffffffffffffffa7120ec55bb188f9f82a933e01000000.
(pid=2314, ip=172.31.2.253) 2021-04-09 12:48:56,374     ERROR worker.py:395 -- SystemExit was raised from the worker
(pid=2314, ip=172.31.2.253) Traceback (most recent call last):
(pid=2314, ip=172.31.2.253)   File "python/ray/_raylet.pyx", line 599, in ray._raylet.task_execution_handler
(pid=2314, ip=172.31.2.253)   File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task
(pid=2314, ip=172.31.2.253)   File "python/ray/_raylet.pyx", line 488, in ray._raylet.execute_task
(pid=2314, ip=172.31.2.253)   File "python/ray/_raylet.pyx", line 495, in ray._raylet.execute_task
(pid=2314, ip=172.31.2.253)   File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
(pid=2314, ip=172.31.2.253)   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
(pid=2314, ip=172.31.2.253)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=2314, ip=172.31.2.253)     return method(__ray_actor, *args, **kwargs)
(pid=2314, ip=172.31.2.253)   File "workloads/test_dead_actors.py", line 43, in ping
(pid=2314, ip=172.31.2.253)     sys.exit(-1)
(pid=2314, ip=172.31.2.253) SystemExit: -1
(pid=2398, ip=172.31.28.183) 2021-04-09 12:48:56,382    ERROR worker.py:395 -- SystemExit was raised from the worker
(pid=2398, ip=172.31.28.183) Traceback (most recent call last):
(pid=2398, ip=172.31.28.183)   File "python/ray/_raylet.pyx", line 599, in ray._raylet.task_execution_handler
(pid=2398, ip=172.31.28.183)   File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task
(pid=2398, ip=172.31.28.183)   File "python/ray/_raylet.pyx", line 488, in ray._raylet.execute_task
(pid=2398, ip=172.31.28.183)   File "python/ray/_raylet.pyx", line 495, in ray._raylet.execute_task
(pid=2398, ip=172.31.28.183)   File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
(pid=2398, ip=172.31.28.183)   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
(pid=2398, ip=172.31.28.183)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=2398, ip=172.31.28.183)     return method(__ray_actor, *args, **kwargs)
(pid=2398, ip=172.31.28.183)   File "workloads/test_dead_actors.py", line 43, in ping
(pid=2398, ip=172.31.28.183)     sys.exit(-1)
(pid=2398, ip=172.31.28.183) SystemExit: -1
2021-04-09 12:48:56,467 WARNING worker.py:1085 -- A worker died or was killed while executing task ffffffffffffffff12636911e61dd11884fc510901000000.
2021-04-09 12:48:56,497 WARNING worker.py:1085 -- A worker died or was killed while executing task ffffffffffffffffdada481bd3f86c7ce5fb554301000000.
(pid=2636, ip=172.31.23.193) 2021-04-09 12:48:56,487    ERROR worker.py:395 -- SystemExit was raised from the worker
(pid=2636, ip=172.31.23.193) Traceback (most recent call last):
(pid=2636, ip=172.31.23.193)   File "python/ray/_raylet.pyx", line 599, in ray._raylet.task_execution_handler
(pid=2636, ip=172.31.23.193)   File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task
(pid=2636, ip=172.31.23.193)   File "python/ray/_raylet.pyx", line 488, in ray._raylet.execute_task
(pid=2636, ip=172.31.23.193)   File "python/ray/_raylet.pyx", line 495, in ray._raylet.execute_task
(pid=2636, ip=172.31.23.193)   File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
(pid=2636, ip=172.31.23.193)   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
(pid=2636, ip=172.31.23.193)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=2636, ip=172.31.23.193)     return method(__ray_actor, *args, **kwargs)
(pid=2636, ip=172.31.23.193)   File "workloads/test_dead_actors.py", line 43, in ping
(pid=2636, ip=172.31.23.193)     sys.exit(-1)
(pid=2636, ip=172.31.23.193) SystemExit: -1
(pid=2643, ip=172.31.23.193) 2021-04-09 12:48:56,456    ERROR worker.py:395 -- SystemExit was raised from the worker
(pid=2643, ip=172.31.23.193) Traceback (most recent call last):
(pid=2643, ip=172.31.23.193)   File "python/ray/_raylet.pyx", line 599, in ray._raylet.task_execution_handler
(pid=2643, ip=172.31.23.193)   File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task
(pid=2643, ip=172.31.23.193)   File "python/ray/_raylet.pyx", line 488, in ray._raylet.execute_task
(pid=2643, ip=172.31.23.193)   File "python/ray/_raylet.pyx", line 495, in ray._raylet.execute_task
(pid=2643, ip=172.31.23.193)   File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
(pid=2643, ip=172.31.23.193)   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
(pid=2643, ip=172.31.23.193)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=2643, ip=172.31.23.193)     return method(__ray_actor, *args, **kwargs)
(pid=2643, ip=172.31.23.193)   File "workloads/test_dead_actors.py", line 43, in ping
(pid=2643, ip=172.31.23.193)     sys.exit(-1)
(pid=2643, ip=172.31.23.193) SystemExit: -1
2021-04-09 12:48:56,518 WARNING worker.py:1085 -- A worker died or was killed while executing task ffffffffffffffffe213ef18197b1e5dd8addfde01000000.
2021-04-09 12:48:56,538 WARNING worker.py:1085 -- A worker died or was killed while executing task ffffffffffffffff0c3d234de0de4a84a9bfaa0e01000000.
(pid=2157, ip=172.31.5.129) 2021-04-09 12:48:56,504     ERROR worker.py:395 -- SystemExit was raised from the worker
(pid=2157, ip=172.31.5.129) Traceback (most recent call last):
(pid=2157, ip=172.31.5.129)   File "python/ray/_raylet.pyx", line 599, in ray._raylet.task_execution_handler
(pid=2157, ip=172.31.5.129)   File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task
(pid=2157, ip=172.31.5.129)   File "python/ray/_raylet.pyx", line 488, in ray._raylet.execute_task
(pid=2157, ip=172.31.5.129)   File "python/ray/_raylet.pyx", line 495, in ray._raylet.execute_task
(pid=2157, ip=172.31.5.129)   File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
(pid=2157, ip=172.31.5.129)   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
(pid=2157, ip=172.31.5.129)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=2157, ip=172.31.5.129)     return method(__ray_actor, *args, **kwargs)
(pid=2157, ip=172.31.5.129)   File "workloads/test_dead_actors.py", line 43, in ping
(pid=2157, ip=172.31.5.129)     sys.exit(-1)
(pid=2157, ip=172.31.5.129) SystemExit: -1
2021-04-09 12:48:56,549 WARNING worker.py:1085 -- A worker died or was killed while executing task fffffffffffffffffa878023a5b71451ae16536d01000000.
(pid=2708, ip=172.31.30.111) 2021-04-09 12:48:56,528    ERROR worker.py:395 -- SystemExit was raised from the worker
(pid=2708, ip=172.31.30.111) Traceback (most recent call last):
(pid=2708, ip=172.31.30.111)   File "python/ray/_raylet.pyx", line 599, in ray._raylet.task_execution_handler
(pid=2708, ip=172.31.30.111)   File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task
(pid=2708, ip=172.31.30.111)   File "python/ray/_raylet.pyx", line 488, in ray._raylet.execute_task
(pid=2708, ip=172.31.30.111)   File "python/ray/_raylet.pyx", line 495, in ray._raylet.execute_task
(pid=2708, ip=172.31.30.111)   File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
(pid=2708, ip=172.31.30.111)   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
(pid=2708, ip=172.31.30.111)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=2708, ip=172.31.30.111)     return method(__ray_actor, *args, **kwargs)
(pid=2708, ip=172.31.30.111)   File "workloads/test_dead_actors.py", line 43, in ping
(pid=2708, ip=172.31.30.111)     sys.exit(-1)
(pid=2708, ip=172.31.30.111) SystemExit: -1
(pid=2408, ip=172.31.2.43) 2021-04-09 12:48:56,544      ERROR worker.py:395 -- SystemExit was raised from the worker
(pid=2408, ip=172.31.2.43) Traceback (most recent call last):
(pid=2408, ip=172.31.2.43)   File "python/ray/_raylet.pyx", line 599, in ray._raylet.task_execution_handler
(pid=2408, ip=172.31.2.43)   File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task
(pid=2408, ip=172.31.2.43)   File "python/ray/_raylet.pyx", line 488, in ray._raylet.execute_task
(pid=2408, ip=172.31.2.43)   File "python/ray/_raylet.pyx", line 495, in ray._raylet.execute_task
(pid=2408, ip=172.31.2.43)   File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
(pid=2408, ip=172.31.2.43)   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
(pid=2408, ip=172.31.2.43)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=2408, ip=172.31.2.43)     return method(__ray_actor, *args, **kwargs)
(pid=2408, ip=172.31.2.43)   File "workloads/test_dead_actors.py", line 43, in ping
(pid=2408, ip=172.31.2.43)     sys.exit(-1)
(pid=2408, ip=172.31.2.43) SystemExit: -1
2021-04-09 12:48:56,609 WARNING worker.py:1085 -- A worker died or was killed while executing task ffffffffffffffffb1657d9a57aaf936f994bcd101000000.
(pid=2397, ip=172.31.16.253) 2021-04-09 12:48:56,604    ERROR worker.py:395 -- SystemExit was raised from the worker
(pid=2397, ip=172.31.16.253) Traceback (most recent call last):
(pid=2397, ip=172.31.16.253)   File "python/ray/_raylet.pyx", line 599, in ray._raylet.task_execution_handler
(pid=2397, ip=172.31.16.253)   File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task
(pid=2397, ip=172.31.16.253)   File "python/ray/_raylet.pyx", line 488, in ray._raylet.execute_task
(pid=2397, ip=172.31.16.253)   File "python/ray/_raylet.pyx", line 495, in ray._raylet.execute_task
(pid=2397, ip=172.31.16.253)   File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
(pid=2397, ip=172.31.16.253)   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
(pid=2397, ip=172.31.16.253)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=2397, ip=172.31.16.253)     return method(__ray_actor, *args, **kwargs)
(pid=2397, ip=172.31.16.253)   File "workloads/test_dead_actors.py", line 43, in ping
(pid=2397, ip=172.31.16.253)     sys.exit(-1)
(pid=2397, ip=172.31.16.253) SystemExit: -1
2021-04-09 12:48:56,630 WARNING worker.py:1085 -- A worker died or was killed while executing task ffffffffffffffff3e65defc2bbb4372b7523c4601000000.
(pid=2429, ip=172.31.19.8) 2021-04-09 12:48:56,621      ERROR worker.py:395 -- SystemExit was raised from the worker
(pid=2429, ip=172.31.19.8) Traceback (most recent call last):
(pid=2429, ip=172.31.19.8)   File "python/ray/_raylet.pyx", line 599, in ray._raylet.task_execution_handler
(pid=2429, ip=172.31.19.8)   File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task
(pid=2429, ip=172.31.19.8)   File "python/ray/_raylet.pyx", line 488, in ray._raylet.execute_task
(pid=2429, ip=172.31.19.8)   File "python/ray/_raylet.pyx", line 495, in ray._raylet.execute_task
(pid=2429, ip=172.31.19.8)   File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
(pid=2429, ip=172.31.19.8)   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
(pid=2429, ip=172.31.19.8)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=2429, ip=172.31.19.8)     return method(__ray_actor, *args, **kwargs)
(pid=2429, ip=172.31.19.8)   File "workloads/test_dead_actors.py", line 43, in ping
(pid=2429, ip=172.31.19.8)     sys.exit(-1)
(pid=2429, ip=172.31.19.8) SystemExit: -1

Script done on 2021-04-09 12:48:56-07:00 [COMMAND_EXIT_CODE="0"]
```

cc @rkooo567 @wuisawesome not sure who to tag for this

**Comment by rkooo567** [comment]
Is the error log this? 
```
Script done on 2021-04-09 12:48:56-07:00 [COMMAND_EXIT_CODE="0"]
```

**Comment by krfricke** [comment]
That's just the script return code. I'm not familiar with this release test, so if the output is expected and correct, please let me know and I'll mark the test as passed.

**Comment by wuisawesome** [comment]
This looks like correct output (confusing because the test is meant to generate tons of failures), but yeah the script returned 0 so this should be considered a pass. 

(buried in the log) 

```
Finished in: 62.34827518463135s
Average iteration time: 0.6234804892539978s
Max iteration time: 2.0002951622009277s
Min iteration time: 0.09386014938354492s
```
