### ISSUE TITLE
[rllib] summarize with dict action space and random policy fails becuase bad previous action

### ISSUE THREAD

**Issue by rusu24edward** [ray-project/ray#15252]
### What is the problem?
[ray.rllib.utlis.debug.summarize](https://github.com/ray-project/ray/blob/master/rllib/utils/debug.py#L10) fails when I'm using a multiagent environment with Dict action space and the [RandomPolicy](https://github.com/ray-project/ray/blob/master/rllib/examples/policy/random_policy.py). 

When I attempt to train, I get the following error:
```
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/utils/debug.py", line 46, in _summarize
    obj.shape, obj.dtype, _summarize(obj[0])))
IndexError: too many indices for array
```

So I dug into this a little by adding a bunch of print statements, and here's the recursion that we're seeing with my test environment (see reproducible below):

`obj` starts as a `Mapping`:
```
{'agent0': SampleBatch({'obs': array([[0]]), 'new_obs': array([[0]]), 'actions': array([array([0.65636134, 0.4058499 ], dtype=float32)], dtype=object), 'prev_actions': array([array(0, dtype=object)], dtype=object), 'rewards': array([1.], dtype=float32), 'prev_rewards': array([0.], dtype=float32), 'dones': array([0.], dtype=float32), 'infos': array([{}], dtype=object), 'agent_index': array([0]), 't': array([0]), 'eps_id': array([574626435]), 'unroll_id': array([0])}), 'agent1': SampleBatch({'obs': array([[0]]), 'actions': array([[ 0.49994144, -2.3867602 ]], dtype=float32), 'rewards': array([-1]), 'dones': array([False]), 'agent_index': array([1]), 'eps_id': array([574626435]), 'unroll_id': array([1]), 'advantages': array([-1.], dtype=float32), 'value_targets': array([0.], dtype=float32)})}
```
Then the next level down looks at `agent0`, which is a `SampleBatch`:
```
SampleBatch({'obs': array([[0]]), 'new_obs': array([[0]]), 'actions': array([array([0.65636134, 0.4058499 ], dtype=float32)], dtype=object), 'prev_actions': array([array(0, dtype=object)], dtype=object), 'rewards': array([1.], dtype=float32), 'prev_rewards': array([0.], dtype=float32), 'dones': array([0.], dtype=float32), 'infos': array([{}], dtype=object), 'agent_index': array([0]), 't': array([0]), 'eps_id': array([574626435]), 'unroll_id': array([0])})
```
Then we loop over the elements of this sample batch, starting with `obs`, then `new_obs`, then `actions`, all of which recurse just fine. Then, we run into an issue with `prev_action`:
```
array(0, dtype=object)
```
[_summarize](https://github.com/ray-project/ray/blob/master/rllib/utils/debug.py#L32) will flag this as an `np.ndarray`, so the recursion will attempt to grab the 0th element, but this is a 0-element array, which generates the error. Uh oh!

I tried to debug when the policies are being trained to see what might be causing the difference, and it looks like `prev_action` is either None or a `tf.Tensor` object, so it's not running into the same issue.

Here's the full traceback:
```
2021-04-12 11:06:56,740 ERROR trial_runner.py:616 -- Trial PG_InfluenceValue_dad82_00000: Error processing event.
Traceback (most recent call last):
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 586, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 609, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(IndexError): ray::PG.train_buffered() (pid=48333, ip=128.15.166.180)
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/tune/trainable.py", line 167, in train_buffered
    result = self.train()
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 526, in train
    raise e
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 515, in train
    result = Trainable.train(self)
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/tune/trainable.py", line 226, in train
    result = self.step()
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 148, in step
    res = next(self.train_exec_impl)
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/util/iter.py", line 876, in apply_flatten
    for item in it:
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/util/iter.py", line 828, in add_wait_hooks
    item = next(it)
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/util/iter.py", line 471, in base_iterator
    yield ray.get(futures, timeout=timeout)
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
ray.exceptions.RayTaskError(IndexError): ray::RolloutWorker.par_iter_next() (pid=48334, ip=128.15.166.180)
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/util/iter.py", line 1152, in par_iter_next
    return next(self.local_it)
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 327, in gen_rollouts
    yield self.sample()
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 662, in sample
    batches = [self.input_reader.next()]
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 95, in next
    batches = [self.get_data()]
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 224, in get_data
    item = next(self.rollout_provider)
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 620, in _env_runner
    sample_collector=sample_collector,
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 1209, in _process_observations_w_trajectory_view_api
    sample_collector.try_build_truncated_episode_multi_agent_batch()
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/evaluation/collectors/simple_list_collector.py", line 760, in try_build_truncated_episode_multi_agent_batch
    self.postprocess_episode(episode, is_done=False)
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/evaluation/collectors/simple_list_collector.py", line 678, in postprocess_episode
    format(summarize(post_batches)))
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/utils/debug.py", line 17, in summarize
    return _printer.pformat(_summarize(obj))
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/utils/debug.py", line 26, in _summarize
    return {k: _summarize(v) for k, v in obj.items()}
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/utils/debug.py", line 26, in <dictcomp>
    return {k: _summarize(v) for k, v in obj.items()}
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/utils/debug.py", line 65, in _summarize
    for k, v in obj.items()},
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/utils/debug.py", line 65, in <dictcomp>
    for k, v in obj.items()},
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/utils/debug.py", line 46, in _summarize
    obj.shape, obj.dtype, _summarize(obj[0])))
  File "/Users/rusu1/.virtual_envs/admiral/lib/python3.7/site-packages/ray/rllib/utils/debug.py", line 46, in _summarize
    obj.shape, obj.dtype, _summarize(obj[0])))
IndexError: too many indices for array
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
* python 3.7.7
* ray: 1.2.0
* tf: 2.3.1
* os: 10.14.6

### Reproduction (REQUIRED)

```python
from gym.spaces import Box, Dict
import numpy as np
from ray.rllib import MultiAgentEnv
class MyEnv(MultiAgentEnv): # Dummy MA env used for testing
    def __init__(self, config=None):
        self.num_agents = 2
        self.action_space = Dict({'vector': Box(-1, 1, (2,))})
        self.observation_space = Box(-np.inf, np.inf, (1,))
    
    def reset(self):
        self.value = 0
        return {
            'agent0': np.array([0]),
            'agent1': np.array([0]),
        }
    
    def step(self, action_dict): # I believe we can safely ignore these details
        for agent, action in action_dict.items():
            action = action['vector']
            self.value += action[0] - 2 * action[1]
        
        if self.value > 0:
            obs = {'agent0': np.array([0]), 'agent1': np.array([0])}
            reward = {'agent0': 1, 'agent1': -1}
        else:
            obs = {'agent0': np.array([1]), 'agent1': np.array([1])}
            reward = {'agent0': -1, 'agent1': 1}
        
        if self.value >= 3 or self.value <= -3:
            done = {'agent0': True, 'agent1': True, '__all__': True}
        else: 
            done = {'agent0': False, 'agent1': False, '__all__': False}
        
        return obs, reward, done, {}

env = MyEnv()

from ray.tune.registry import register_env
env_name = "InfluenceValue"
register_env(env_name, lambda env_config: env)


from ray.rllib.examples.policy.random_policy import RandomPolicy
policies = {
    'agent0': (RandomPolicy, env.observation_space, env.action_space, {}),
    'agent1': (None, env.observation_space, env.action_space, {}),
}
def policy_mapping_fn(agent_id):
    return agent_id


params = {
    'experiment': {
        'title': '{}'.format('InfluenceValue'),
    },
    'ray_tune': {
        'run_or_experiment': "PG",
        'checkpoint_freq': 50,
        'checkpoint_at_end': True,
        'stop': {
            'episodes_total': 20,
        },
        'verbose': 2,
        'config': {
            # --- Environment ---
            'env': "InfluenceValue",
            'horizon': 200,
            # 'env_config': {},
            # --- Multiagent ---
            'multiagent': {
                'policies': policies,
                'policy_mapping_fn': policy_mapping_fn,
            },
            "num_workers": 1,
            "num_envs_per_worker": 1, # This must be 1 because we are not "threadsafe"
            "rollout_fragment_length": 1, # Just doing 1 to isolate the problem
        },
    }
}
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rusu24edward** [comment]
This case is not captured by the [0 size check](https://github.com/ray-project/ray/blob/master/rllib/utils/debug.py#L33) because, unfortunately, the prev_actions array is created using `np.array(0, dtype=object)`, rather than `np.empty`, so its size is actually 1, even though you cannot index it.

**Comment by Leonardo767** [comment]
I've encountered the same issue.
