### ISSUE TITLE
[release/serve] long running serve failure fails with 'Client' object has no attribute 'delete_deployment'

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#15270]
```
2021-04-13 02:38:24,664 WARNING worker.py:1085 -- A worker died or was killed while executing task ffffffffffffffff639fd236f0f618963aec003601000000.
2021-04-13 02:38:25,711 WARNING worker.py:1085 -- A worker died or was killed while executing task ffffffffffffffff76eaaedc5b33b3c6144f1aae01000000.
2021-04-13 02:38:26,748 WARNING worker.py:1085 -- A worker died or was killed while executing task ffffffffffffffff5ed0139e710ba4d113c40a3601000000.
2021-04-13 02:38:27,779 WARNING worker.py:1085 -- A worker died or was killed while executing task ffffffffffffffff5ed0139e710ba4d113c40a3601000000.
Traceback (most recent call last):
  File "./workloads/serve_failure.py", line 119, in <module>
    RandomTest(max_deployments=num_nodes * cpus_per_node).run()
  File "./workloads/serve_failure.py", line 104, in run
    random.choices(actions, weights=weights)[0]()
  File "./workloads/serve_failure.py", line 73, in create_deployment
    self.client.delete_deployment(deployment_to_delete)
AttributeError: 'Client' object has no attribute 'delete_deployment'
2021-04-13 02:38:28,415 WARNING worker.py:1085 -- WARNING: 16 PYTHON workers have been started on a node of the id: 85d09e4ad36e102dcbd9a44acb11bac3869afce9945f850ae56ff81d and address: 172.31.2.46. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (see https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.
2021-04-13 02:38:28,618 WARNING worker.py:1085 -- WARNING: 16 PYTHON workers have been started on a node of the id: 574b389b42ce1c3ace7662afdc710ddc81ccb0c68cc6673a64d5200e and address: 172.31.2.46. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (see https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.
2021-04-13 02:38:28,649 WARNING worker.py:1085 -- WARNING: 16 PYTHON workers have been started on a node of the id: 043611d70aa965cb1b1ebda1a3de070ba33f57dfacc5e830cffb9489 and address: 172.31.2.46. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (see https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.
2021-04-13 02:38:28,660 WARNING worker.py:1085 -- A worker died or was killed while executing task ffffffffffffffff8d0099900497a6a06bb3392601000000.
2021-04-13 02:38:28,682 WARNING worker.py:1085 -- A worker died or was killed while executing task ffffffffffffffff5363353d59fdce2423950de201000000.
2021-04-13 02:38:28,775 WARNING worker.py:1085 -- A worker died or was killed while executing task ffffffffffffffff4afba9475fba28518217aaf801000000.
2021-04-13 02:38:28,775 WARNING worker.py:1085 -- A worker died or was killed while executing task ffffffffffffffff45caaa76ef6fea5bf9c9412d01000000.
2021-04-13 02:38:28,776 WARNING worker.py:1085 -- A worker died or was killed while executing task ffffffffffffffff69085349fd372212e72d0f5f01000000.
2021-04-13 02:38:29,758 ERROR worker.py:1087 -- listen_error_messages_raylet: Connection closed by server.
2021-04-13 02:38:29,763 ERROR import_thread.py:88 -- ImportThread: Connection closed by server.
```

cc @simon-mo @edoakes

**Comment by edoakes** [comment]
@krfricke huh I'm actually a bit confused about this -- this update was relatively recent (after the release branch cut), shouldn't the release testing be running on an older version? Anyways, I'll make a fix but for now you can run using the version in 01dcb993c72e867b4121553b391dddea08ad9dd6

**Comment by krfricke** [comment]
Ah, since I'm modifying the release tests to work with the most recent version of the product I'm running them straight out of master. I can check out old versions for the serve tests though

**Comment by krfricke** [comment]
Ok, I am now running the serve tests back from the release branch versions. We can probably revert #15276 then. Sorry, this was my bad.

**Comment by edoakes** [comment]
The fix is still valid, I just wasn't sure why the issue was coming up :)
