### ISSUE TITLE
Ray client crashes on connecting

### ISSUE THREAD

**Issue by franklsf95** [ray-project/ray#15289]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

- Ray: https://s3-us-west-2.amazonaws.com/ray-wheels/master/0ad0839265750b9ee4d142b623e92a38fa72631d/ray-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl  # ray[debug]
- Python 3.8.5
- Linux ip-172-31-61-153 5.4.0-1043-aws #45~18.04.1-Ubuntu SMP Fri Apr 9 23:32:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

First I use the autoscaler to launch a Ray cluster on AWS. The cluster launches normally.

After I ran `ray attach` to the head node, I can run `ray.util.connect` normally:

```
In [1]: import ray; ray.util.connect("172.31.63.116:10001")
Out[1]:
{'num_clients': 1,
 'python_version': '3.8.3',
 'ray_version': '2.0.0.dev0',
 'ray_commit': '0ad0839265750b9ee4d142b623e92a38fa72631d',
 'protocol_version': '2021-04-09'}
```

However on my driver node when I try to connect to the head node, I get the following crash:

```
In [1]: import ray; ray.util.connect("172.31.63.116:10001")
Got Error from data channel -- shutting down: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating responses: "
        debug_error_string = "{"created":"@1618375973.798187357","description":"Error received from peer ipv4:172.31.63.116:10001","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception iterating responses: ","gr
pc_status":2}"
>
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/util/client/dataclient.py", line 90, in _data_main
    raise e
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/util/client/dataclient.py", line 64, in _data_main
    for response in resp_stream:
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/home/ubuntu/miniconda3/envs/raysort/lib/python3.8/site-packages/grpc/_channel.py", line 803, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating responses: "
        debug_error_string = "{"created":"@1618375973.798187357","description":"Error received from peer ipv4:172.31.63.116:10001","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception iterating responses: ","g$pc_status":2}"
>
---------------------------------------------------------------------------
ConnectionError                           Traceback (most recent call last)
<ipython-input-1-5167e9c28fed> in <module>
----> 1 import ray; ray.util.connect("172.31.63.116:10001")

~/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/util/client_connect.py in connect(conn_str, secure, metadata, connection_retries, ignore_version)
     25     # for supporting things like cert_path, ca_path, etc and creating
     26     # the correct metadata
---> 27     return ray.connect(
     28         conn_str,
     29         secure=secure,

~/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/util/client/__init__.py in connect(self, conn_str, secure, metadata, connection_retries, ignore_version)
     68                 connection_retries=connection_retries)
     69             self.api.worker = self.client_worker
---> 70             conn_info = self.client_worker.connection_info()
     71             self._check_versions(conn_info, ignore_version)
     72             return conn_info

~/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/util/client/worker.py in connection_info(self)
    154     def connection_info(self):
    155         try:
--> 156             data = self.data_client.ConnectionInfo()
    157         except grpc.RpcError as e:
    158             raise decode_exception(e.details())

~/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/util/client/dataclient.py in ConnectionInfo(self, context)
    122         datareq = ray_client_pb2.DataRequest(
    123             connection_info=ray_client_pb2.ConnectionInfoRequest())
--> 124         resp = self._blocking_send(datareq)
    125         return resp.connection_info
    126

~/miniconda3/envs/raysort/lib/python3.8/site-packages/ray/util/client/dataclient.py in _blocking_send(self, req)
    106                 lambda: req_id in self.ready_data or self._in_shutdown)
    107             if self._in_shutdown:
--> 108                 raise ConnectionError(
    109                     "Cannot send request due to data channel "
    110                     f"shutting down. Request: {req}")

ConnectionError: Cannot send request due to data channel shutting down. Request: req_id: 1
connection_info {
}

```

I tried `telnet 172.31.63.116 100011 and it works, so it does not seem like a connectivity issue.

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by franklsf95** [comment]
Seems to be fixed in the 1.3 release.
