### ISSUE TITLE
[Release] test_placement_group stress test fails

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#15307]
Running `test_placement_group` workload fails with the following error:

```
Script started on 2021-04-14 11:44:03-07:00 [TERM="screen" TTY="/dev/pts/11" COLUMNS="80" LINES="24"]
--ray-version=1.3.0
--commit=db0b6a6a9526a1c2b2516376c9f8030bb72464dc
--ray-branch=releases/1.3.0
--workload=test_placement_group
version: 1.3.0
commit: db0b6a6a9526a1c2b2516376c9f8030bb72464dc
branch: releases/1.3.0
workload: test_placement_group
Failed to start the dashboard: Failed to bind to 127.0.0.1:8265 because it's already occupied. You can use `ray start --dashboard-port ...` or `ray.init(dashboard_port=...)` to select a different port.
2021-04-14 11:44:06,190 INFO worker.py:654 -- Connecting to existing Ray cluster at address: 172.31.4.156:27831
Traceback (most recent call last):
  File "workloads/test_placement_group.py", line 147, in <module>
    ray.get(pg_launchers)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1440, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::pg_launcher() (pid=1298, ip=172.31.4.156)
  File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
  File "workloads/test_placement_group.py", line 97, in pg_launcher
    placement_group(bundles, strategy="STRICT_SPREAD", name=str(i)))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/placement_group.py", line 195, in placement_group
    name, bundles, strategy, detached)
  File "python/ray/_raylet.pyx", line 1320, in ray._raylet.CoreWorker.create_placement_group
  File "python/ray/_raylet.pyx", line 159, in ray._raylet.check_status
ray.exceptions.RaySystemError: System error: Failed to create placement group 'd08dc84ddad445f8d0d8900dee80f17b' because name '3' already exists.
2021-04-14 11:45:01,025 ERROR import_thread.py:88 -- ImportThread: Connection closed by server.
2021-04-14 11:45:01,026 ERROR worker.py:928 -- print_logs: Connection closed by server.
2021-04-14 11:45:01,026 ERROR worker.py:1087 -- listen_error_messages_raylet: Connection closed by server.

Script done on 2021-04-14 11:45:02-07:00 [COMMAND_EXIT_CODE="1"]
```

**Comment by richardliaw** [comment]
Still failing? otherwise I'll close this issue

**Comment by amogkam** [comment]
Nope this is passing
