### ISSUE TITLE
[Release] Long running Horovod Test fails due to Network connection

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#15300]
The Long running Horovod Test does not run for a full 24 hours and fails after a few hundred iterations due to a network connectivity issue.

Full Stack Trace:
```
== Status ==
Memory usage on this node: 9.2/239.9 GiB
PopulationBasedTraining: 849 checkpoints, 998 perturbs
Resources requested: 4/128 CPUs, 4/8 GPUs, 0.0/660.56 GiB heap, 0.0/287.09 GiB objects (0.0/4.0 accelerator_type:M60)
Current best trial: d5f83_00005 with loss=2.3262739181518555 and parameters={'lr': 0.07752809637684588, 'batch_size': 64, 'data': ObjectRef(ffffffffffffffffffffffffffffffffffffff
ff0100000001000000)}
Result logdir: /home/ubuntu/ray_results/WrappedHorovodTrainable_2021-04-14_07-55-52
Number of trials: 9/9 (8 PAUSED, 1 RUNNING)
+-------------------------------------+----------+-------+-----------+--------+------------------+---------+
| Trial name                          | status   | loc   |        lr |   iter |   total time (s) |    loss |
|-------------------------------------+----------+-------+-----------+--------+------------------+---------|
| WrappedHorovodTrainable_d5f83_00003 | RUNNING  |       | 0.0255805 |    280 |          1245.48 | 2.42772 |
| WrappedHorovodTrainable_d5f83_00000 | PAUSED   |       | 0.0995481 |    281 |          1249.24 | 2.37639 |
| WrappedHorovodTrainable_d5f83_00001 | PAUSED   |       | 0.0930337 |    281 |          1249.91 | 2.36732 |
| WrappedHorovodTrainable_d5f83_00002 | PAUSED   |       | 0.0602548 |    280 |          1245.81 | 2.36008 |
| WrappedHorovodTrainable_d5f83_00004 | PAUSED   |       | 0.0319757 |    281 |          1249.35 | 2.42386 |
| WrappedHorovodTrainable_d5f83_00005 | PAUSED   |       | 0.0775281 |    280 |          1245.3  | 2.32627 |
| WrappedHorovodTrainable_d5f83_00006 | PAUSED   |       | 0.0632417 |    281 |          1248.98 | 2.3914  |
| WrappedHorovodTrainable_d5f83_00007 | PAUSED   |       | 0.0694136 |    281 |          1249.73 | 2.36294 |
| WrappedHorovodTrainable_d5f83_00008 | PAUSED   |       | 0.0213171 |    281 |          1248.79 | 2.3719  |
+-------------------------------------+----------+-------+-----------+--------+------------------+---------+


(pid=23323, ip=172.31.19.90) 2021-04-14 11:24:54,370    ERROR worker.py:78 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::NodeColocator.execute() (pid=215
38, ip=172.31.23.186)
(pid=23323, ip=172.31.19.90)   File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
(pid=23323, ip=172.31.19.90)   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=23323, ip=172.31.19.90)     return method(__ray_actor, *args, **kwargs)
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/ray/runner.py", line 173, in execute
(pid=23323, ip=172.31.19.90)     return func(self)
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/ray/driver_service.py", line 11, in execute_task_fn
(pid=23323, ip=172.31.19.90)     _task_fn(index, num_hosts, driver_addresses, settings)
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/runner/task_fn.py", line 31, in _task_fn
(pid=23323, ip=172.31.19.90)     task.wait_for_initial_registration(settings.start_timeout)
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/runner/common/service/task_service.py", line 253, in wait_for_initial_registration
(pid=23323, ip=172.31.19.90)     timeout.check_time_out_for('tasks to start')
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/runner/common/util/timeout.py", line 37, in check_time_out_for
(pid=23323, ip=172.31.19.90)     self._timeout
(pid=23323, ip=172.31.19.90) Exception: Timed out waiting for tasks to start. Please check connectivity between servers. You may need to increase the --start-timeout parameter if
 you have too many servers. Timeout after 30 seconds.
(pid=23323, ip=172.31.19.90) 2021-04-14 11:24:54,373    ERROR worker.py:395 -- Exception raised in creation task: The actor died because of an error raised in its creation task,
ray::WrappedHorovodTrainable.__init__() (pid=23323, ip=172.31.19.90)
(pid=23323, ip=172.31.19.90)   File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
(pid=23323, ip=172.31.19.90)   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=23323, ip=172.31.19.90)     return method(__ray_actor, *args, **kwargs)
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 98, in __init__
(pid=23323, ip=172.31.19.90)     self.setup(copy.deepcopy(self.config))
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/tune/integration/horovod.py", line 128, in setup
(pid=23323, ip=172.31.19.90)     "logger_creator": lambda cfg: logger_creator(cfg, logdir_)
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/ray/runner.py", line 397, in start
(pid=23323, ip=172.31.19.90)     node_workers=self.colocators)
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/ray/utils.py", line 72, in detect_nics
(pid=23323, ip=172.31.19.90)     settings)
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/ray/driver_service.py", line 59, in _driver_fn
(pid=23323, ip=172.31.19.90)     return _run_probe(driver, settings, num_hosts)
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/runner/driver/driver_service.py", line 126, in _run_probe
(pid=23323, ip=172.31.19.90)     driver.wait_for_initial_registration(settings.start_timeout)
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/runner/common/service/driver_service.py", line 166, in wait_for_initial_registrati
on
(pid=23323, ip=172.31.19.90)     timeout.check_time_out_for('tasks to start')
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/runner/common/util/timeout.py", line 37, in check_time_out_for
(pid=23323, ip=172.31.19.90)     self._timeout
(pid=23323, ip=172.31.19.90) Exception: Timed out waiting for tasks to start. Please check connectivity between servers. You may need to increase the --start-timeout parameter if
 you have too many servers. Timeout after 30 seconds.
(pid=22106, ip=172.31.19.90) 2021-04-14 11:25:23,717    INFO trainable.py:378 -- Restored on 172.31.19.90 from checkpoint: /home/ubuntu/ray_results/WrappedHorovodTrainable_2021-0
4-14_07-55-52/WrappedHorovodTrainable_d5f83_00003_3_lr=0.4_2021-04-14_07-56-03/tmp39x9tdznrestore_from_object/./
(pid=22106, ip=172.31.19.90) 2021-04-14 11:25:23,717    INFO trainable.py:385 -- Current state after restoring: {'_iteration': 280, '_timesteps_total': None, '_time_total': 1244.
988074541092, '_episodes_total': None}
(pid=30458, ip=172.31.31.86) 2021-04-14 11:25:23,725    INFO trainable.py:378 -- Restored on 172.31.31.86 from checkpoint: /home/ubuntu/ray_results/WrappedHorovodTrainable_2021-0
4-14_07-55-52/WrappedHorovodTrainable_d5f83_00003_3_lr=0.4_2021-04-14_07-56-03/worker_2/checkpoint_tmp456317/./
(pid=30458, ip=172.31.31.86) 2021-04-14 11:25:23,726    INFO trainable.py:385 -- Current state after restoring: {'_iteration': 280, '_timesteps_total': None, '_time_total': 1244.
988074541092, '_episodes_total': None}
(pid=30456, ip=172.31.31.86) 2021-04-14 11:25:23,726    INFO trainable.py:378 -- Restored on 172.31.31.86 from checkpoint: /home/ubuntu/ray_results/WrappedHorovodTrainable_2021-0
4-14_07-55-52/WrappedHorovodTrainable_d5f83_00003_3_lr=0.4_2021-04-14_07-56-03/worker_3/checkpoint_tmp9fc092/./
(pid=30456, ip=172.31.31.86) 2021-04-14 11:25:23,726    INFO trainable.py:385 -- Current state after restoring: {'_iteration': 280, '_timesteps_total': None, '_time_total': 1244.
988074541092, '_episodes_total': None}
2021-04-14 11:25:24,417 ERROR trial_runner.py:732 -- Trial WrappedHorovodTrainable_d5f83_00005: Error processing event.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 702, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 686, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1442, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::WrappedHorovodTrainable.__init__() (pid=23323, ip=172.31.19.90)
  File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/tune/integration/horovod.py", line 128, in setup
    "logger_creator": lambda cfg: logger_creator(cfg, logdir_)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/ray/runner.py", line 397, in start
    node_workers=self.colocators)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/ray/utils.py", line 72, in detect_nics
    settings)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/ray/driver_service.py", line 59, in _driver_fn
    return _run_probe(driver, settings, num_hosts)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/runner/driver/driver_service.py", line 126, in _run_probe
    driver.wait_for_initial_registration(settings.start_timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/runner/common/service/driver_service.py", line 166, in wait_for_initial_registration
    timeout.check_time_out_for('tasks to start')
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/runner/common/util/timeout.py", line 37, in check_time_out_for
    self._timeout
Exception: Timed out waiting for tasks to start. Please check connectivity between servers. You may need to increase the --start-timeout parameter if you have too many servers. 
Timeout after 30 seconds.
Result for WrappedHorovodTrainable_d5f83_00005:
  date: 2021-04-14_11-23-08
  done: false
  experiment_id: 3e855eb779fb4d89952f76bc8caf1926
  experiment_tag: 5_lr=0.6@perturbed[lr=0.077528]
  hostname: ip-172-31-25-121
  iterations_since_restore: 1
  loss: 2.3262739181518555
  node_ip: 172.31.25.121
  pid: 22129
  time_since_restore: 4.413449287414551
  time_this_iter_s: 4.413449287414551
  time_total_s: 1245.2958271503448
  timestamp: 1618399388
  timesteps_since_restore: 0
  training_iteration: 280
  trial_id: d5f83_00005

== Status ==
Memory usage on this node: 4.9/239.9 GiB
PopulationBasedTraining: 849 checkpoints, 998 perturbs
Resources requested: 0/128 CPUs, 0/8 GPUs, 0.0/660.56 GiB heap, 0.0/287.09 GiB objects (0.0/4.0 accelerator_type:M60)
Current best trial: d5f83_00005 with loss=2.3262739181518555 and parameters={'lr': 0.07752809637684588, 'batch_size': 64, 'data': ObjectRef(ffffffffffffffffffffffffffffffffffffff
ff0100000001000000)}
Result logdir: /home/ubuntu/ray_results/WrappedHorovodTrainable_2021-04-14_07-55-52
Number of trials: 9/9 (1 ERROR, 8 TERMINATED)
+-------------------------------------+------------+-------+-----------+--------+------------------+---------+
| Trial name                          | status     | loc   |        lr |   iter |   total time (s) |    loss |
|-------------------------------------+------------+-------+-----------+--------+------------------+---------|
| WrappedHorovodTrainable_d5f83_00000 | TERMINATED |       | 0.0995481 |    281 |          1249.24 | 2.37639 |
| WrappedHorovodTrainable_d5f83_00001 | TERMINATED |       | 0.0930337 |    281 |          1249.91 | 2.36732 |
| WrappedHorovodTrainable_d5f83_00002 | TERMINATED |       | 0.0602548 |    280 |          1245.81 | 2.36008 |
| WrappedHorovodTrainable_d5f83_00003 | TERMINATED |       | 0.0255805 |    280 |          1245.48 | 2.42772 |
| WrappedHorovodTrainable_d5f83_00004 | TERMINATED |       | 0.0319757 |    281 |          1249.35 | 2.42386 |
| WrappedHorovodTrainable_d5f83_00006 | TERMINATED |       | 0.0632417 |    281 |          1248.98 | 2.3914  |
| WrappedHorovodTrainable_d5f83_00007 | TERMINATED |       | 0.0694136 |    281 |          1249.73 | 2.36294 |
| WrappedHorovodTrainable_d5f83_00008 | TERMINATED |       | 0.0213171 |    281 |          1248.79 | 2.3719  |
| WrappedHorovodTrainable_d5f83_00005 | ERROR      |       | 0.0775281 |    280 |          1245.3  | 2.32627 |
+-------------------------------------+------------+-------+-----------+--------+------------------+---------+
Number of errored trials: 1
+-------------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------
---------------------+
| Trial name                          |   # failures | error file
                     |
|-------------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------
---------------------|
| WrappedHorovodTrainable_d5f83_00005 |            1 | /home/ubuntu/ray_results/WrappedHorovodTrainable_2021-04-14_07-55-52/WrappedHorovodTrainable_d5f83_00005_5_lr=0.6_2021-04-1
4_07-56-10/error.txt |
+-------------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------
---------------------+

== Status ==
Memory usage on this node: 4.9/239.9 GiB
PopulationBasedTraining: 849 checkpoints, 998 perturbs
Resources requested: 0/128 CPUs, 0/8 GPUs, 0.0/660.56 GiB heap, 0.0/287.09 GiB objects (0.0/4.0 accelerator_type:M60)
Current best trial: d5f83_00005 with loss=2.3262739181518555 and parameters={'lr': 0.07752809637684588, 'batch_size': 64, 'data': ObjectRef(ffffffffffffffffffffffffffffffffffffff
ff0100000001000000)}
Result logdir: /home/ubuntu/ray_results/WrappedHorovodTrainable_2021-04-14_07-55-52
Number of trials: 9/9 (1 ERROR, 8 TERMINATED)
+-------------------------------------+------------+-------+-----------+--------+------------------+---------+
| Trial name                          | status     | loc   |        lr |   iter |   total time (s) |    loss |
|-------------------------------------+------------+-------+-----------+--------+------------------+---------|
| WrappedHorovodTrainable_d5f83_00000 | TERMINATED |       | 0.0995481 |    281 |          1249.24 | 2.37639 |
| WrappedHorovodTrainable_d5f83_00001 | TERMINATED |       | 0.0930337 |    281 |          1249.91 | 2.36732 |
| WrappedHorovodTrainable_d5f83_00002 | TERMINATED |       | 0.0602548 |    280 |          1245.81 | 2.36008 |
| WrappedHorovodTrainable_d5f83_00003 | TERMINATED |       | 0.0255805 |    280 |          1245.48 | 2.42772 |
| WrappedHorovodTrainable_d5f83_00004 | TERMINATED |       | 0.0319757 |    281 |          1249.35 | 2.42386 |
| WrappedHorovodTrainable_d5f83_00006 | TERMINATED |       | 0.0632417 |    281 |          1248.98 | 2.3914  |
| WrappedHorovodTrainable_d5f83_00007 | TERMINATED |       | 0.0694136 |    281 |          1249.73 | 2.36294 |
| WrappedHorovodTrainable_d5f83_00008 | TERMINATED |       | 0.0213171 |    281 |          1248.79 | 2.3719  |
| WrappedHorovodTrainable_d5f83_00005 | ERROR      |       | 0.0775281 |    280 |          1245.3  | 2.32627 |
+-------------------------------------+------------+-------+-----------+--------+------------------+---------+
Number of errored trials: 1
+-------------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------
---------------------+
| Trial name                          |   # failures | error file
                     |
|-------------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------
---------------------|
| WrappedHorovodTrainable_d5f83_00005 |            1 | /home/ubuntu/ray_results/WrappedHorovodTrainable_2021-04-14_07-55-52/WrappedHorovodTrainable_d5f83_00005_5_lr=0.6_2021-04-1
4_07-56-10/error.txt |
+-------------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------
---------------------+

(pid=23323, ip=172.31.19.90) 2021-04-14 11:25:24,402    ERROR worker.py:78 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::NodeColocator.execute() (pid=262
20, ip=172.31.25.121)
(pid=23323, ip=172.31.19.90)   File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
(pid=23323, ip=172.31.19.90)   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=23323, ip=172.31.19.90)     return method(__ray_actor, *args, **kwargs)
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/ray/runner.py", line 173, in execute
(pid=23323, ip=172.31.19.90)     return func(self)
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/ray/driver_service.py", line 11, in execute_task_fn
(pid=23323, ip=172.31.19.90)     _task_fn(index, num_hosts, driver_addresses, settings)
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/runner/task_fn.py", line 30, in _task_fn
(pid=23323, ip=172.31.19.90)     host_hash.host_hash())
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/runner/common/service/driver_service.py", line 205, in register_task
(pid=23323, ip=172.31.19.90)     self._send(RegisterTaskRequest(index, task_addresses, host_hash))
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/runner/common/util/network.py", line 303, in _send
(pid=23323, ip=172.31.19.90)     return self._send_one(addr, req, stream)
(pid=23323, ip=172.31.19.90)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/horovod/runner/common/util/network.py", line 274, in _send_one
(pid=23323, ip=172.31.19.90)     sock.connect(addr)
(pid=23323, ip=172.31.19.90) ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/ubuntu/horovod_test.py", line 140, in <module>
    fail_fast=True)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 543, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [WrappedHorovodTrainable_d5f83_00005])
```

cc @richardliaw

**Comment by richardliaw** [comment]
Nice! How long did this actually take? 

Do you know if this test was run in the last release?

**Comment by krfricke** [comment]
Seems to be around 20 minutes, right? Based on the last total time in seconds

**Comment by amogkam** [comment]
Yeah around 3 hours since only 1 is running at a time. I asked Alex whether this was run last release and I'll get back to you.

**Comment by richardliaw** [comment]
Anyways, I would be OK with not blocking the release on this test.

**Comment by amogkam** [comment]
OK looks like this was not run last release. I'm trying on Ray 1.2 right now just to make sure that this isn't a regression.

**Comment by amogkam** [comment]
This also fails with the same error after a few hours on 1.2

**Comment by richardliaw** [comment]
OK I am ok with removing the release blocker and moving this to P1

**Comment by davidxiaozhi** [comment]
https://github.com/ray-project/ray/blob/master/python/ray/tune/ray_trial_executor.py
Whether the default configuration for [DEFAULT_GET_TIMEOUT = 60.0  # seconds]  can be modified externally,
Timeouts can occur when some tasks are trained for too long
