### ISSUE TITLE
[rllib] I couldn't train atari-apex task in my enviroment

### ISSUE THREAD

**Issue by craftsliu** [ray-project/ray#15333]
### What is the problem?
I couldn't train atari-apex task in my enviroment 
`2021-04-15 18:04:49,558 ERROR trial_runner.py:616 -- Trial APEX_BreakoutNoFrameskip-v4_c1440_00000: Error processing event.
Traceback (most recent call last):
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 586, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 609, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::APEX.train_buffered() (pid=59351, ip=9.73.149.0)
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/tune/trainable.py", line 167, in train_buffered
    result = self.train()
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 529, in train
    raise e
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 515, in train
    result = Trainable.train(self)
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/tune/trainable.py", line 226, in train
    result = self.step()
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 148, in step
    res = next(self.train_exec_impl)
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/util/iter.py", line 1075, in build_union
    item = next(it)
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/util/iter.py", line 791, in apply_foreach
    result = fn(item)
  File "/root/miniconda3/envs/ray1.0/lib/python3.7/site-packages/ray/rllib/execution/train_ops.py", line 386, in __call__
    if cur_ts - last_update > self.target_update_freq:
TypeError: '>' not supported between instances of 'int' and 'str'`
*Ray version and other system information (Python version, TensorFlow version, OS):*
ray 1.2.0
python 3.7.10
TensorFlow 2.1.0
OS：Linux

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
cd ray/rllib/tuned_examples/dqn
rllib train -f atari-apex.yaml
`# Runs on a single g3.16xl AWS machine
apex:
    env:
        grid_search:
            - BreakoutNoFrameskip-v4
            - BeamRiderNoFrameskip-v4
            - QbertNoFrameskip-v4
            - SpaceInvadersNoFrameskip-v4
    run: APEX
    config:
        # Works for both torch and tf.
        framework: tf
        double_q: false
        dueling: false
        num_atoms: 1
        noisy: false
        n_step: 3
        lr: .0001
        adam_epsilon: .00015
        hiddens: [512]
        buffer_size: 1000000
        exploration_config:
          final_epsilon: 0.01
          epsilon_timesteps: 200000
        prioritized_replay_alpha: 0.5
        final_prioritized_replay_beta: 1.0
        prioritized_replay_beta_annealing_timesteps: 2000000

        num_gpus: 0

        # APEX
        num_workers: 3
        num_envs_per_worker: 1
        rollout_fragment_length: 20
        train_batch_size: 512
        target_network_update_freq: 50000ls
        timesteps_per_iteration: 25000
`

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by craftsliu** [comment]
target_network_update_freq: 50000ls
    timesteps_per_iteration: 25000
