### ISSUE TITLE
[Release] Long running APEX test fails

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#15339]
Long running Apex test fails on the releases/1.3.0 branch with the following error:
```
2021-04-15 11:18:19,381 INFO services.py:1269 -- View the Ray dashboard at http://127.0.0.1:8265
/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/ray/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ray/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ray/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ray/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ray/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ray/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From /home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:61: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "./workloads/apex.py", line 46, in <module>
    "timesteps_per_iteration": 10,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 637, in run_experiments
    callbacks=callbacks).trials
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 520, in run
    runner.step()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 481, in step
    next_trial = self._get_next_trial()  # blocking
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 617, in _get_next_trial
    self._update_trial_queue(blocking=wait_for_trial)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 1074, in _update_trial_queue
    trial = self._search_alg.next_trial()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/suggest/basic_variant.py", line 298, in next_trial
    return next(self._trial_iter)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/suggest/basic_variant.py", line 146, in __next__
    return self.create_trial(resolved_vars, spec)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/suggest/basic_variant.py", line 108, in create_trial
    experiment_tag=experiment_tag)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/config_parser.py", line 218, in create_trial_from_spec
    **trial_kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial.py", line 226, in __init__
    self.config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/dqn/apex.py", line 79, in default_resource_request
    Trainer._validate_config(cf)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 1223, in _validate_config
    config["evaluation_parallel_to_training"]:
KeyError: 'evaluation_parallel_to_training'
```

I modified the test to use local ray.init() instead of the Cluster util as suggested by @sven1977 
```
ray.init()

# Run the workload.

run_experiments({
    "apex": {
        "run": "APEX",
        "env": "Pong-v0",
        "config": {
            "num_workers": 8,
            "num_gpus": 0,
            "buffer_size": 10000,
            "learning_starts": 0,
            "rollout_fragment_length": 1,
            "train_batch_size": 1,
            "min_iter_time_s": 10,
            "timesteps_per_iteration": 10,
        },
    }
})
```

**Comment by amogkam** [comment]
After the including this hotfix (https://github.com/ray-project/ray/commit/8ed3de051147b559f296b8f697eb6839145f6e38) I'm not getting this error anymore.

However, I had to change the test to use less workers since I believe #15295 introduces CPU reservation for replay buffer shards. So on a 8 CPU machine it's using 1 CPU for driver + 4 for replay buffer shards + 3 workers.

The full code for the test I am running looks like this:
```
ray.init()

# Run the workload.

run_experiments({
    "apex": {
        "run": "APEX",
        "env": "Pong-v0",
        "config": {
            "num_workers": 3,
            "num_gpus": 0,
            "buffer_size": 10000,
            "learning_starts": 0,
            "rollout_fragment_length": 1,
            "train_batch_size": 1,
            "min_iter_time_s": 10,
            "timesteps_per_iteration": 10,
        },
    }
})
```
It's running fine now, but I'm going to leave this issue open until the test is fully successful. @sven1977

**Comment by amogkam** [comment]
This runs for 24 hours with the above changes.
