### ISSUE TITLE
dqn_trainer.set_weights reports errors when running the rllib example multi_agent_two_trainers.py based on torch

### ISSUE THREAD

**Issue by imxuemei** [ray-project/ray#15398]
My environment is as follows:
os: win10
python: 3.8
torch: 1.6.0

The errors are:

> Traceback (most recent call last):
  File "E:/workspace-python/offload-rl-v1/test_rays/multi_agent_two_trainers.py", line 126, in <module>
    dqn_trainer.set_weights(ppo_trainer.get_weights(["ppo_policy"]))
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\ray\rllib\agents\trainer.py", line 985, in set_weights
    self.workers.local_worker().set_weights(weights)
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 745, in set_weights
    self.policy_map[pid].set_weights(w)
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\ray\rllib\policy\torch_policy.py", line 476, in set_weights
    self.model.load_state_dict(weights)
  File "E:\ProgramData\Anaconda3\envs\python38\lib\site-packages\torch\nn\modules\module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for FullyConnectedNetwork:
	Unexpected key(s) in state_dict: "_value_branch_separate.0._model.0.weight", "_value_branch_separate.0._model.0.bias", "_value_branch_separate.1._model.0.weight", "_value_branch_separate.1._model.0.bias".

**Comment by mvindiola1** [comment]
Hi @imxuemei,

Your issue is that there is a differs t default option for the model parameter ` "vf_share_layers.`. For dqn it is True and for ppo it is false. You should be able to fix it like this:  `config["model"][ "vf_share_layers"] = False`.

**Comment by imxuemei** [comment]
@mvindiola1  Thanks. It works!
