### ISSUE TITLE
AssertionError when using pyinstaller with ray

### ISSUE THREAD

**Issue by maxjr82** [ray-project/ray#15396]
### Problem: ray is raising an assertion error after using pyinstaller to build single-binary

I am trying to build a binary file for my program using pyinstaller, and I am using the ray library (as required by modin.pandas) in some of my modules. Although the binary is created without any error message, when I try to execute the program I am getting an assertion error as shown below:

```
Traceback (most recent call last):
  File "run_analysis.py", line 12, in <module>
  File "ray/_private/client_mode_hook.py", line 47, in wrapper
  File "ray/worker.py", line 714, in init
  File "ray/node.py", line 220, in __init__
  File "ray/node.py", line 827, in start_head_processes
  File "ray/node.py", line 632, in start_redis
  File "ray/_private/services.py", line 833, in start_redis
  File "ray/_private/services.py", line 942, in _start_redis_instance
AssertionError
[21376] Failed to execute script run_analysis
```

The program works perfectly well in a pure python environment, and it only crashes with the AssertionError message when I execute the binary version of the program. In the main program I included the ray.init() statement right below the import ray command. I am quite new with ray library, so I could not identify the source of the error described above. I am wondering if ray can be used in conjunction with pyinstaller for building binary files. If someone here may have experience with this, I would like to ask for some tips on how to build a binary for a python program that uses ray.

*Ray version 1.2.0, Python 3.8-dev, and Ubuntu 16 (kernel 4.15.0-123-generic)*

Thanks in advance.

**Comment by richardliaw** [comment]
Hmm, haven't used pyinstaller before. Can you use pip instead?

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
