### ISSUE TITLE
[serve] Can't pass general-purpose ASGI apps

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#15406]
```python
from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.routing import Route


async def homepage(request):
    return JSONResponse({'hello': 'world'})


app = Starlette(debug=True, routes=[
    Route('/', homepage),
])

from ray import serve

serve.start()

@serve.deployment
@serve.ingress(app)
class MyApp:
    pass

MyApp.deploy()

while True:
    import time
    time.sleep(100000)
```

```
(base) ray/serve % python test.py 
2021-04-19 14:49:29,426 INFO services.py:1262 -- View the Ray dashboard at http://127.0.0.1:8265
(pid=23961) 2021-04-19 14:49:31,281     INFO http_state.py:68 -- Starting HTTP proxy with name 'lvgfOp:SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:192.168.0.124-0' on node 'node:192.168.0.124-0' listening on '127.0.0.1:8000'
(pid=23963) INFO:     Started server process [23963]
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    class MyApp:
  File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 998, in decorator
    make_fastapi_class_based_view(app, cls)
  File "/Users/eoakes/code/ray/python/ray/serve/utils.py", line 399, in make_fastapi_class_based_view
    fastapi_app.include_router(new_router)
AttributeError: 'Starlette' object has no attribute 'include_router'
```

**Comment by simon-mo** [comment]
note to self, would Django app work as well?? https://docs.djangoproject.com/en/3.2/howto/deployment/asgi/uvicorn/
