### ISSUE TITLE
Issue when trying to use Serve on K8

### ISSUE THREAD

**Issue by vecorro** [ray-project/ray#15419]
Hi, 

I'm trying to run Serve on a k8 cluster. The connection to the cluster succeed but when I want to start Serve I get the error 

> AtributeError: Can't get attribute 'EndpointInfo' on <module 'ray.serve.common'

Here my code. Thanks in advance for your help.
```

from ray import serve

import pickle

import json

import numpy as np

import requests

import os

import tempfile

import ray

​

from sklearn.datasets import load_iris

from sklearn.ensemble import GradientBoostingClassifier

from sklearn.metrics import mean_squared_error

# Load data

iris_dataset = load_iris()

data, target, target_names = iris_dataset["data"], iris_dataset[

    "target"], iris_dataset["target_names"]

​

# Instantiate model

model = GradientBoostingClassifier()

​

# Training and validation split

np.random.shuffle(data), np.random.shuffle(target)

train_x, train_y = data[:100], target[:100]

val_x, val_y = data[100:], target[100:]

​

# Train and evaluate models

model.fit(train_x, train_y,)

print("MSE:", mean_squared_error(model.predict(val_x), val_y))

​

# Save the model and label to file

MODEL_PATH = os.path.join(tempfile.gettempdir(),

                          "iris_model_logistic_regression.pkl")

LABEL_PATH = os.path.join(tempfile.gettempdir(), "iris_labels.json")

​

with open(MODEL_PATH, "wb") as f:

    pickle.dump(model, f)

with open(LABEL_PATH, "w") as f:

    json.dump(target_names.tolist(), f)

​

MSE: 1.4

class BoostingModel:

    def __init__(self):

        with open(MODEL_PATH, "rb") as f:

            self.model = pickle.load(f)

        with open(LABEL_PATH) as f:

            self.label_list = json.load(f)

​

    async def __call__(self, starlette_request):

        payload = await starlette_request.json()

        print("Worker: received starlette request with data", payload)

​

        input_vector = [

            payload["sepal length"],

            payload["sepal width"],

            payload["petal length"],

            payload["petal width"],

        ]

        prediction = self.model.predict([input_vector])[0]

        human_name = self.label_list[prediction]

        return {"result": human_name}

# Connect to the running Ray cluster.

ray.util.connect("localhost:10001")

{'num_clients': 1,
 'python_version': '3.7.7',
 'ray_version': '2.0.0.dev0',
 'ray_commit': 'b0a813baad0a4a187f0cc25e11498843aff899c6',
 'protocol_version': '2021-04-09'}

# Bind on 0.0.0.0 to expose the HTTP server on external IPs.

serve.start(detached=True, http_options={"host": "0.0.0.0"})

serve.create_backend("lr:v1", BoostingModel)

serve.create_endpoint("iris_classifier", backend="lr:v1", route="/regressor")

Put failed:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-055c13229d7d> in <module>
      1 # Bind on 0.0.0.0 to expose the HTTP server on external IPs.
----> 2 serve.start(detached=True, http_options={"host": "0.0.0.0"})
      3 serve.create_backend("lr:v1", BoostingModel)
      4 serve.create_endpoint("iris_classifier", backend="lr:v1", route="/regressor")

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/serve/api.py in start(detached, http_host, http_port, http_middlewares, http_options, dedicated_cpu)
    648         controller_name,
    649         http_options,
--> 650         detached=detached,
    651     )
    652 

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/actor.py in remote(self, *args, **kwargs)
    474                     runtime_env=runtime_env,
    475                     override_environment_variables=(
--> 476                         override_environment_variables))
    477 
    478         return ActorOptionWrapper()

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/actor.py in _remote(self, args, kwargs, num_cpus, num_gpus, memory, object_store_memory, resources, accelerator_type, max_concurrency, max_restarts, max_task_retries, name, lifetime, placement_group, placement_group_bundle_index, placement_group_capture_child_tasks, runtime_env, override_environment_variables)
    585                 runtime_env=runtime_env,
    586                 override_environment_variables=(
--> 587                     override_environment_variables))
    588 
    589         worker = ray.worker.global_worker

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/_private/client_mode_hook.py in client_mode_convert_actor(actor_cls, in_args, in_kwargs, **kwargs)
    103         setattr(actor_cls, RAY_CLIENT_MODE_ATTR, key)
    104     client_actor = ray._get_converted(key)
--> 105     return client_actor._remote(in_args, in_kwargs, **kwargs)

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/util/client/common.py in _remote(self, args, kwargs, **option_args)
    184         if kwargs is None:
    185             kwargs = {}
--> 186         return self.options(**option_args).remote(*args, **kwargs)
    187 
    188     def __repr__(self):

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/util/client/common.py in remote(self, *args, **kwargs)
    297 class ActorOptionWrapper(OptionWrapper):
    298     def remote(self, *args, **kwargs):
--> 299         ref_ids = ray.call_remote(self, *args, **kwargs)
    300         assert len(ref_ids) == 1
    301         return ClientActorHandle(ClientActorRef(ref_ids[0]))

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/util/client/api.py in call_remote(self, instance, *args, **kwargs)
     94             kwargs: opaque keyword arguments
     95         """
---> 96         return self.worker.call_remote(instance, *args, **kwargs)
     97 
     98     def call_release(self, id: bytes) -> None:

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/util/client/worker.py in call_remote(self, instance, *args, **kwargs)
    293 
    294     def call_remote(self, instance, *args, **kwargs) -> List[bytes]:
--> 295         task = instance._prepare_client_task()
    296         for arg in args:
    297             pb_arg = convert_to_arg(arg, self._client_id)

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/util/client/common.py in _prepare_client_task(self)
    290 
    291     def _prepare_client_task(self):
--> 292         task = self.remote_stub._prepare_client_task()
    293         set_task_options(task, self.options)
    294         return task

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/util/client/common.py in _prepare_client_task(self)
    195 
    196     def _prepare_client_task(self) -> ray_client_pb2.ClientTask:
--> 197         self._ensure_ref()
    198         task = ray_client_pb2.ClientTask()
    199         task.type = ray_client_pb2.ClientTask.ACTOR

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/util/client/common.py in _ensure_ref(self)
    168                 self._ref = InProgressSentinel()
    169                 self._ref = ray.put(
--> 170                     self.actor_cls, client_ref_id=self._client_side_ref.id)
    171 
    172     def remote(self, *args, **kwargs) -> "ClientActorHandle":

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/util/client/api.py in put(self, *args, **kwargs)
     43             kwargs: opaque keyword arguments
     44         """
---> 45         return self.worker.put(*args, **kwargs)
     46 
     47     def wait(self, *args, **kwargs):

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/util/client/worker.py in put(self, vals, client_ref_id)
    231             to_put.append(vals)
    232 
--> 233         out = [self._put(x, client_ref_id=client_ref_id) for x in to_put]
    234         if single:
    235             out = out[0]

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/util/client/worker.py in <listcomp>(.0)
    231             to_put.append(vals)
    232 
--> 233         out = [self._put(x, client_ref_id=client_ref_id) for x in to_put]
    234         if single:
    235             out = out[0]

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/util/client/worker.py in _put(self, val, client_ref_id)
    251         if not resp.valid:
    252             try:
--> 253                 raise cloudpickle.loads(resp.error)
    254             except pickle.UnpicklingError:
    255                 logger.exception("Failed to deserialize {}".format(resp.error))

AttributeError: Can't get attribute 'EndpointInfo' on <module 'ray.serve.common' from '/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/common.py'>
```

**Comment by simon-mo** [comment]
Hi, can you make sure the version for Ray is consistent across your local machine and K8s? Namely, what's the:
```
ray.__version__
ray.__commit__
```

**Comment by vecorro** [comment]
Thanks, here my setup. Versions match but commits don't. I wonder if it would be possible to make the Ray commit running on my laptop match the one running on K8. 

```

ray.util.connect("127.0.0.1:10001") # replace with the appropriate IP and port numbers

{'num_clients': 1,
 'python_version': '3.7.7',
 'ray_version': '2.0.0.dev0',
 'ray_commit': 'b0a813baad0a4a187f0cc25e11498843aff899c6',
 'protocol_version': '2021-04-09'}

ray.__version__

'2.0.0.dev0'

ray.__commit__

'fbe510cd47ad00320edaae296b4011a6f02e325f'
```

**Comment by vecorro** [comment]
ok, I made the versions match but now I got another error:


```
ray.util.connect("127.0.0.1:10001")

{'num_clients': 2,
 'python_version': '3.7.7',
 'ray_version': '2.0.0.dev0',
 'ray_commit': 'b0a813baad0a4a187f0cc25e11498843aff899c6',
 'protocol_version': '2021-04-09'}

ray.__version__

'2.0.0.dev0'

ray.__commit__

'b0a813baad0a4a187f0cc25e11498843aff899c6'

```

> 
> The 'context' argument is not supported using ray. Please refer to the documentation for how to control ray initialization.
> 
> Fitting 5 folds for each of 300 candidates, totalling 1500 fits
> 
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-5-d6d9ebf39f97> in <module>
>       3 register_ray()
>       4 with joblib.parallel_backend('ray'):
> ----> 5     search.fit(digits.data, digits.target)
> 
> ~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
>      61             extra_args = len(args) - len(all_args)
>      62             if extra_args <= 0:
> ---> 63                 return f(*args, **kwargs)
>      64 
>      65             # extra_args > 0
> 
> ~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/sklearn/model_selection/_search.py in fit(self, X, y, groups, **fit_params)
>     839                 return results
>     840 
> --> 841             self._run_search(evaluate_candidates)
>     842 
>     843             # multimetric is determined here because in the case of a callable
> 
> ~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/sklearn/model_selection/_search.py in _run_search(self, evaluate_candidates)
>    1619         evaluate_candidates(ParameterSampler(
>    1620             self.param_distributions, self.n_iter,
> -> 1621             random_state=self.random_state))
> 
> ~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/sklearn/model_selection/_search.py in evaluate_candidates(candidate_params, cv, more_results)
>     807                                    (split_idx, (train, test)) in product(
>     808                                    enumerate(candidate_params),
> --> 809                                    enumerate(cv.split(X, y, groups))))
>     810 
>     811                 if len(out) < 1:
> 
> ~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/joblib/parallel.py in __call__(self, iterable)
>    1039             # remaining jobs.
>    1040             self._iterating = False
> -> 1041             if self.dispatch_one_batch(iterator):
>    1042                 self._iterating = self._original_iterator is not None
>    1043 
> 
> ~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/joblib/parallel.py in dispatch_one_batch(self, iterator)
>     857                 return False
>     858             else:
> --> 859                 self._dispatch(tasks)
>     860                 return True
>     861 
> 
> ~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/joblib/parallel.py in _dispatch(self, batch)
>     775         with self._lock:
>     776             job_idx = len(self._jobs)
> --> 777             job = self._backend.apply_async(batch, callback=cb)
>     778             # A job can complete so quickly than its callback is
>     779             # called before we get here, causing self._jobs to
> 
> ~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/joblib/_parallel_backends.py in apply_async(self, func, callback)
>     251         """Schedule a func to be run"""
>     252         return self._get_pool().apply_async(
> --> 253             SafeFunction(func), callback=callback)
>     254 
>     255     def abort_everything(self, ensure_ready=True):
> 
> ~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/util/multiprocessing/pool.py in apply_async(self, func, args, kwargs, callback, error_callback)
>     462         self._check_running()
>     463         object_ref = self._run_batch(self._random_actor_index(), func,
> --> 464                                      [(args, kwargs)])
>     465         return AsyncResult(
>     466             [object_ref], callback, error_callback, single_result=True)
> 
> ~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/util/multiprocessing/pool.py in _run_batch(self, actor_index, func, batch)
>     413     def _run_batch(self, actor_index, func, batch):
>     414         actor, count = self._actor_pool[actor_index]
> --> 415         object_ref = actor.run_batch.remote(func, batch)
>     416         count += 1
>     417         assert self._maxtasksperchild == -1 or count <= self._maxtasksperchild
> 
> ~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/util/client/common.py in remote(self, *args, **kwargs)
>     254 
>     255     def remote(self, *args, **kwargs):
> --> 256         return return_refs(ray.call_remote(self, *args, **kwargs))
>     257 
>     258     def __repr__(self):
> 
> ~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/util/client/api.py in call_remote(self, instance, *args, **kwargs)
>      94             kwargs: opaque keyword arguments
>      95         """
> ---> 96         return self.worker.call_remote(instance, *args, **kwargs)
>      97 
>      98     def call_release(self, id: bytes) -> None:
> 
> ~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/util/client/worker.py in call_remote(self, instance, *args, **kwargs)
>     299         for k, v in kwargs.items():
>     300             task.kwargs[k].CopyFrom(convert_to_arg(v, self._client_id))
> --> 301         return self._call_schedule_for_task(task)
>     302 
>     303     def _call_schedule_for_task(
> 
> ~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/util/client/worker.py in _call_schedule_for_task(self, task)
>     312         if not ticket.valid:
>     313             try:
> --> 314                 raise cloudpickle.loads(ticket.error)
>     315             except pickle.UnpicklingError:
>     316                 logger.exception("Failed to deserialize {}".format(
> 
> AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from '/home/ray/anaconda3/lib/python3.7/site-packages/sklearn/utils/fixes.py'>
>

**Comment by simon-mo** [comment]
Looking through the traceback it seems like you are using Ray's joblib backend for sklearn?
```
AttributeError Traceback (most recent call last)
in
3 register_ray()
4 with joblib.parallel_backend('ray'):
```

**Comment by vecorro** [comment]
Sorry Simon, I deleted the last update because I had in there an error from another script using joblib I have not reported yet. Coming back to Serve, here the update. Now both versions and commit numbers match and got a different error message.

```
from ray import serve

import pickle

import json

import numpy as np

import requests

import os

import tempfile

import ray

from sklearn.datasets import load_iris

from sklearn.ensemble import GradientBoostingClassifier

from sklearn.metrics import mean_squared_error

# Load data

iris_dataset = load_iris()

data, target, target_names = iris_dataset["data"], iris_dataset[

    "target"], iris_dataset["target_names"]


# Instantiate model

model = GradientBoostingClassifier()


# Training and validation split

np.random.shuffle(data), np.random.shuffle(target)

train_x, train_y = data[:100], target[:100]

val_x, val_y = data[100:], target[100:]

​

# Train and evaluate models

model.fit(train_x, train_y,)

print("MSE:", mean_squared_error(model.predict(val_x), val_y))



# Save the model and label to file

MODEL_PATH = os.path.join(tempfile.gettempdir(),

                          "iris_model_logistic_regression.pkl")

LABEL_PATH = os.path.join(tempfile.gettempdir(), "iris_labels.json")

​

with open(MODEL_PATH, "wb") as f:

    pickle.dump(model, f)

with open(LABEL_PATH, "w") as f:

    json.dump(target_names.tolist(), f)

​

MSE: 1.54

class BoostingModel:

    def __init__(self):

        with open(MODEL_PATH, "rb") as f:

            self.model = pickle.load(f)

        with open(LABEL_PATH) as f:

            self.label_list = json.load(f)

​

    async def __call__(self, starlette_request):

        payload = await starlette_request.json()

        print("Worker: received starlette request with data", payload)

​

        input_vector = [

            payload["sepal length"],

            payload["sepal width"],

            payload["petal length"],

            payload["petal width"],

        ]

        prediction = self.model.predict([input_vector])[0]

        human_name = self.label_list[prediction]

        return {"result": human_name}

# Connect to the running Ray cluster.

ray.util.connect("localhost:10001")

{'num_clients': 1,
 'python_version': '3.7.7',
 'ray_version': '2.0.0.dev0',
 'ray_commit': 'b0a813baad0a4a187f0cc25e11498843aff899c6',
 'protocol_version': '2021-04-09'}

ray.__version__

'2.0.0.dev0'

ray.__commit__

'b0a813baad0a4a187f0cc25e11498843aff899c6'

# Bind on 0.0.0.0 to expose the HTTP server on external IPs.

serve.start(detached=True, http_options={"host": "0.0.0.0"})

serve.create_backend("lr:v1", BoostingModel)

serve.create_endpoint("iris_classifier", backend="lr:v1", route="/regressor")

The actor 'RayServeWrappedReplica' has been exported 100 times. It's possible that this warning is accidental, but this may indicate that the same remote function is being defined repeatedly from within many tasks and exported to all of the workers. This can be a performance issue and can be resolved by defining the remote function on the driver instead. See https://github.com/ray-project/ray/issues/6240 for more discussion.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-055c13229d7d> in <module>
      1 # Bind on 0.0.0.0 to expose the HTTP server on external IPs.
      2 serve.start(detached=True, http_options={"host": "0.0.0.0"})
----> 3 serve.create_backend("lr:v1", BoostingModel)
      4 serve.create_endpoint("iris_classifier", backend="lr:v1", route="/regressor")

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/serve/api.py in create_backend(backend_tag, backend_def, ray_actor_options, config, *init_args)
    829         ray_actor_options=ray_actor_options,
    830         config=config,
--> 831         _internal=True)
    832 
    833 

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/serve/api.py in check(self, _internal, *args, **kwargs)
     76                 "all instances of `client.api_call()` with "
     77                 "`serve.api_call()`.")
---> 78         return f(self, *args, **kwargs)
     79 
     80     return check

~/opt/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/ray/serve/api.py in create_backend(self, backend_tag, backend_def, ray_actor_options, config, *init_args)
    309             raise ValueError(
    310                 "Cannot create backend. "
--> 311                 "Backend '{}' is already registered.".format(backend_tag))
    312 
    313         if config is None:

ValueError: Cannot create backend. Backend 'lr:v1' is already registered.
```

**Comment by vecorro** [comment]
In addition, if I reset the K8 cluster, now I get the following

```
(pid=650) 2021-04-20 11:03:41,252	INFO http_state.py:71 -- Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:10.1.0.103-0' on node 'node:10.1.0.103-0' listening on '0.0.0.0:8000'
(pid=691) INFO:     Started server process [691]
(pid=650) 2021-04-20 11:03:41,784	INFO backend_state.py:746 -- Adding 1 replicas to backend 'lr:v1'.
(pid=150, ip=10.1.0.104) 2021-04-20 11:03:42,337	ERROR worker.py:395 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SERVE_CONTROLLER_ACTOR:lr:v1#KsenaR:RayServeWrappedReplica.__init__ (pid=150, ip=10.1.0.104)
(pid=150, ip=10.1.0.104)   File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
(pid=150, ip=10.1.0.104)   File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task.function_executor
(pid=150, ip=10.1.0.104)   File "python/ray/_raylet.pyx", line 1651, in ray._raylet.CoreWorker.run_async_func_in_event_loop
(pid=150, ip=10.1.0.104)   File "/home/ray/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
(pid=150, ip=10.1.0.104)     return self.__get_result()
(pid=150, ip=10.1.0.104)   File "/home/ray/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
(pid=150, ip=10.1.0.104)     raise self._exception
(pid=150, ip=10.1.0.104)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/backend_worker.py", line 69, in __init__
(pid=150, ip=10.1.0.104)     _callable = backend(*init_args)
(pid=150, ip=10.1.0.104)   File "<ipython-input-3-7d8045d59116>", line 3, in __init__
(pid=150, ip=10.1.0.104) FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/b1/cqdxbbvx3dgcj0s1phwqxtlm0000gn/T/iris_model_logistic_regression.pkl'
(pid=650) 2021-04-20 11:03:42,445	ERROR controller.py:123 -- Exception updating backend state: Failed to look up actor with name 'SERVE_CONTROLLER_ACTOR:lr:v1#KsenaR'. You are either trying to look up a named actor you didn't create, the named actor died, or the actor hasn't been created because named actor creation is asynchronous.

```

**Comment by simon-mo** [comment]
This error does seem relevant
```
(pid=150, ip=10.1.0.104) FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/b1/cqdxbbvx3dgcj0s1phwqxtlm0000gn/T/iris_model_logistic_regression.pkl'
```

The model files are stored locally but not synched to the K8s cluster.

**Comment by simon-mo** [comment]
Not exactly sure about your use case, if you just want to make it working, you can put the training code in the init method of the backend class. In production scenario, either mounting NFS to K8s volume or downloading the files from object store works.

**Comment by vecorro** [comment]
Thanks. Is there any documentation about how to download the files from the data store? It looks like it'd be more practical is NFS volumes are not available to the K8 cluster.
