### ISSUE TITLE
[release/core/rllib/tune] many ppo fails

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#15428]
```
Traceback (most recent call last):
  File "./workloads/many_ppo.py", line 46, in <module>
    "timesteps_total": 1,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 637, in run_experiments
    callbacks=callbacks).trials
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 520, in run
    runner.step()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 494, in step
    self.trial_executor.stage_and_update_status(self._trials)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 235, in stage_and_update_status
    self._pg_manager.update_status()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/utils/placement_groups.py", line 361, in update_status
    self.cleanup()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/utils/placement_groups.py", line 286, in cleanup
    remove_placement_group(pg)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/placement_group.py", line 210, in remove_placement_group
    worker.core_worker.remove_placement_group(placement_group.id)
  File "python/ray/_raylet.pyx", line 1324, in ray._raylet.CoreWorker.remove_placement_group
  File "python/ray/_raylet.pyx", line 155, in ray._raylet.check_status
ray.exceptions.GetTimeoutError: There was timeout in removing the placement group of id dc61ec2d0efdc7f5dee0693ed366964d. It is probably because GCS server is dead or there's a high load there.
(pid=832301) 2021-04-19 11:09:39,163    INFO trainer.py:669 -- Tip: set framework=tfe or the --eager flag to enable TensorFlow eager execution
(pid=832301) 2021-04-19 11:09:39,163    INFO trainer.py:696 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
2021-04-19 11:09:40,700 WARNING worker.py:1115 -- A worker died or was killed while executing task ffffffffffffffffa2f6e0fc12d770f77f491b1801000000.
run.sh: line 63: 10728 Aborted                 (core dumped) python "./workloads/$workload.py"

Script done on 2021-04-19 11:09:41-07:00 [COMMAND_EXIT_CODE="134"]
```

Last status

```
== Status ==
Memory usage on this node: 12.8/30.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 54.0/60 CPUs, 0/0 GPUs, 0.0/85.29 GiB heap, 0.0/2.79 GiB objects (0.0/2.0 1, 0.0/2.0 2, 0.0/2.0 0)
Result logdir: /home/ray/ray_results/ppo
Number of trials: 3254/10000 (999 PENDING, 6 RUNNING, 2249 TERMINATED)
+-----------------------------+------------+-------+--------+------------------+------+----------+----------------------+----------------------+--------------------+
| Trial name                  | status     | loc   |   iter |   total time (s) |   ts |   reward |   episode_reward_max |   episode_reward_min |   episode_len_mean |
|-----------------------------+------------+-------+--------+------------------+------+----------+----------------------+----------------------+--------------------|
| PPO_CartPole-v0_e3791_01192 | RUNNING    |       |        |                  |      |          |                      |                      |                    |
| PPO_CartPole-v0_e3791_02250 | RUNNING    |       |        |                  |      |          |                      |                      |                    |
| PPO_CartPole-v0_e3791_02251 | RUNNING    |       |        |                  |      |          |                      |                      |                    |
| PPO_CartPole-v0_e3791_02252 | RUNNING    |       |        |                  |      |          |                      |                      |                    |
| PPO_CartPole-v0_e3791_02253 | RUNNING    |       |        |                  |      |          |                      |                      |                    |
| PPO_CartPole-v0_e3791_02254 | RUNNING    |       |        |                  |      |          |                      |                      |                    |
| PPO_CartPole-v0_e3791_02255 | PENDING    |       |        |                  |      |          |                      |                      |                    |
| PPO_CartPole-v0_e3791_02256 | PENDING    |       |        |                  |      |          |                      |                      |                    |
| PPO_CartPole-v0_e3791_02257 | PENDING    |       |        |                  |      |          |                      |                      |                    |
| PPO_CartPole-v0_e3791_02258 | PENDING    |       |        |                  |      |          |                      |                      |                    |
| PPO_CartPole-v0_e3791_02259 | PENDING    |       |        |                  |      |          |                      |                      |                    |
| PPO_CartPole-v0_e3791_02260 | PENDING    |       |        |                  |      |          |                      |                      |                    |
| PPO_CartPole-v0_e3791_02261 | PENDING    |       |        |                  |      |          |                      |                      |                    |
| PPO_CartPole-v0_e3791_00000 | TERMINATED |       |      1 |          5.06453 | 4800 |  23.4975 |                   69 |                    9 |            23.4975 |
| PPO_CartPole-v0_e3791_00001 | TERMINATED |       |      1 |          7.43717 | 4800 |  21.788  |                   69 |                    8 |            21.788  |
| PPO_CartPole-v0_e3791_00002 | TERMINATED |       |      1 |          8.71541 | 4800 |  20.9027 |                   76 |                    8 |            20.9027 |
| PPO_CartPole-v0_e3791_00003 | TERMINATED |       |      1 |         12.8926  | 4800 |  21.0955 |                   62 |                    8 |            21.0955 |
| PPO_CartPole-v0_e3791_00004 | TERMINATED |       |      1 |          7.35694 | 4800 |  22.4354 |                   84 |                    8 |            22.4354 |
| PPO_CartPole-v0_e3791_00005 | TERMINATED |       |      1 |         12.2151  | 4800 |  23.8446 |                   88 |                    9 |            23.8446 |
| PPO_CartPole-v0_e3791_00006 | TERMINATED |       |      1 |          6.93871 | 4800 |  21.8967 |                   84 |                    8 |            21.8967 |
+-----------------------------+------------+-------+--------+------------------+------+----------+----------------------+----------------------+--------------------+
... 3234 more trials not shown (992 PENDING, 2242 TERMINATED)
```

```
2021-04-19 11:09:06,418 WARNING util.py:162 -- The `on_step_end` operation took 0.513 s, which may be a performance bottleneck.
...
2021-04-19 11:09:09,962 WARNING util.py:162 -- The `on_step_begin` operation took 3.487 s, which may be a performance bottleneck.
...
2021-04-19 11:09:13,273 WARNING util.py:162 -- The `start_trial` operation took 1.957 s, which may be a performance bottleneck.
...
2021-04-19 11:09:19,784 WARNING util.py:162 -- The `get_next_failed_trial` operation took 1.015 s, which may be a performance bottleneck.
...
2021-04-19 11:09:30,036 WARNING util.py:162 -- The `start_trial` operation took 1.896 s, which may be a performance bottleneck.
...
2021-04-19 11:09:23,887 WARNING util.py:162 -- The `on_step_begin` operation took 2.110 s, which may be a performance bottleneck.
```

I'll look into this right now.

**Comment by krfricke** [comment]
```
The `on_step_begin` operation took 3.487 s, which may be a performance bottleneck.
```

This is fishy because the on_step_begin only updates the cluster resources:

```
        with warn_if_slow("on_step_begin"):
            self.trial_executor.on_step_begin(self)
            
```

-->

```
    def on_step_begin(self, trial_runner):
        """Before step() called, update the available resources."""
        self._update_avail_resources()
        self._trial_just_finished_before = self._trial_just_finished
        self._trial_just_finished = False
 ```
 
 -->
 
 the bottleneck is probably in one of these lines:
 
```
                 resources = ray.cluster_resources()
```

```
                resources = ResourceSpec().resolve(True).to_resource_dict()
```

The former is IMO more probable. This would mean that checking the cluster resources takes a long time. It's not clear to me why that should be the case exactly. Maybe we create too many placement groups, or maybe we overload the GCS server some other way. This would explain this message:

```
ray.exceptions.GetTimeoutError: There was timeout in removing the placement group of id dc61ec2d0efdc7f5dee0693ed366964d. It is probably because GCS server is dead or there's a high load there.
```

**Comment by krfricke** [comment]
I'm running on a real three node cluster now, and this error comes up:

```
2021-04-20 15:49:51,150 ERROR trial_runner.py:732 -- Trial PPO_CartPole-v0_7dee7_00000: Error processing event.
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 702, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 686, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1483, in get
    raise value
  File "python/ray/_raylet.pyx", line 599, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 562, in ray._raylet.execute_task
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::PPO.__init__() (pid=605, ip=172.31.22.20)
  File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 121, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 516, in __init__
    super().__init__(config, logger_creator)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 707, in setup
    self._init(self.config, self.env_creator)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 153, in _init
    num_workers=self.config["num_workers"])
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 789, in _make_workers
    logdir=self.logdir)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 81, in __init__
    lambda p, pid: (pid, p.observation_space, p.action_space)))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "python/ray/_raylet.pyx", line 599, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 562, in ray._raylet.execute_task
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=597, ip=172.31.22.20)
  File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 514, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1155, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/policy/tf_policy_template.py", line 237, in __init__
    get_batch_divisibility_req=get_batch_divisibility_req,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/policy/dynamic_tf_policy.py", line 303, in __init__
    explore=explore)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/exploration/stochastic_sampling.py", line 73, in get_exploration_action
    timestep, explore)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/exploration/stochastic_sampling.py", line 84, in _get_tf_exploration_action_op
    false_fn=lambda: action_dist.sample(),
  File "/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1396, in cond_for_tf_v2
    return cond(pred, true_fn=true_fn, false_fn=false_fn, strict=True, name=name)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 538, in new_func
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1230, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1066, in BuildCondBranch
    original_result = fn()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/exploration/stochastic_sampling.py", line 83, in <lambda>
    explore=True)[0]),
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/exploration/random.py", line 126, in get_tf_exploration_action_op
    logp = tf.zeros(shape=(batch_size, ), dtype=tf.float32)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2819, in wrapped
    tensor = fun(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2868, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2804, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 6, in prod
  File "/home/ray/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3031, in prod
    keepdims=keepdims, initial=initial, where=where)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 855, in __array__
    " a NumPy call, which is not supported".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (default_policy/cond/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
```

cc @sven1977

**Comment by krfricke** [comment]
It might be a tensorflow version mismatch. I might be able to confirm tomorrow.

**Comment by edoakes** [comment]
@krfricke should this be closed?

**Comment by krfricke** [comment]
Yep! Thanks

**Comment by chrisn-pik** [comment]
I get similar error messages. My code actually works for several hours well, but it crashes after roughly 24 hours. However, I do not really know when the first problems occur.

This shows the end of my error logs:
```
2021-11-13 15:24:11,007 WARNING ray_trial_executor.py:747 -- Over the last 60 seconds, the Tune event loop has been backlogged processing new results. Consider increasing your period of result reporting to improve performance.
2021-11-13 15:24:22,279 WARNING util.py:165 -- The `on_step_begin` operation took 3.139 s, which may be a performance bottleneck.
2021-11-13 15:24:24,778 WARNING util.py:165 -- The `get_next_failed_trial` operation took 2.498 s, which may be a performance bottleneck.
2021-11-13 15:24:35,877 WARNING util.py:165 -- The `on_step_begin` operation took 2.986 s, which may be a performance bottleneck.
2021-11-13 15:24:38,321 WARNING util.py:165 -- The `get_next_failed_trial` operation took 2.444 s, which may be a performance bottleneck.
2021-11-13 15:24:43,029 WARNING util.py:165 -- The `start_trial` operation took 4.619 s, which may be a performance bottleneck.
2021-11-13 15:24:48,029 WARNING util.py:165 -- The `on_step_end` operation took 5.000 s, which may be a performance bottleneck.
Traceback (most recent call last):
  File "start_ray.py", line 106, in <module>
    analysis = tune.run(
  File "/home/nauck/.conda/envs/py38ptg/lib/python3.8/site-packages/ray/tune/tune.py", line 588, in run
    runner.step()
  File "/home/nauck/.conda/envs/py38ptg/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 646, in step
    self._run_and_catch(self.trial_executor.on_step_end)
  File "/home/nauck/.conda/envs/py38ptg/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 396, in _run_and_catch
    func(self.get_trials())
  File "/home/nauck/.conda/envs/py38ptg/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 988, in on_step_end
    self._pg_manager.cleanup()
  File "/home/nauck/.conda/envs/py38ptg/lib/python3.8/site-packages/ray/tune/utils/placement_groups.py", line 302, in cleanup
    remove_placement_group(pg)
  File "/home/nauck/.conda/envs/py38ptg/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 122, in wrapper
    return func(*args, **kwargs)
  File "/home/nauck/.conda/envs/py38ptg/lib/python3.8/site-packages/ray/util/placement_group.py", line 237, in remove_placement_group
    worker.core_worker.remove_placement_group(placement_group.id)
  File "python/ray/_raylet.pyx", line 1490, in ray._raylet.CoreWorker.remove_placement_group
  File "python/ray/_raylet.pyx", line 158, in ray._raylet.check_status
ray.exceptions.GetTimeoutError: There was timeout in removing the placement group of id b9b9793d87af7cd715835d75918dedfc. It is probably because GCS server is dead or there's a high load there.
```

> It might be a tensorflow version mismatch. I might be able to confirm tomorrow.

I am using Pytorch.

What should I do? I read [#10842](https://github.com/ray-project/ray/issues/10842), but do not understand how this is applicable to me.

I am running the job on a cluster and allocating 8cpus and 1 GPU and this is how I start ray:
```python
    analysis = tune.run(
        NN_tune_trainable,
        name=name,
        stop=tune_stop,
        config=cfg,
        num_samples=num_samples,
        local_dir=result_path,
        checkpoint_freq=checkpoint_freq,
        checkpoint_at_end=True,
        resources_per_trial={'cpu': 4,'gpu': .5},
    )
```
