### ISSUE TITLE
Async actor method hang

### ISSUE THREAD

**Issue by chaokunyang** [ray-project/ray#15437]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
* ray: 1.2.0
* os: mac 10.13.6 (17G2112)
### Reproduction (REQUIRED)
```python
import sys
import ray

@ray.remote
class A:
    def f1(self):
        sys.exit(0)

    def f2(self):
        return 1


ray.init()
a = A.remote()
a.f1.remote()
ray.get(a.f2.remote())

```
```
2021-04-21 19:22:41,314 INFO services.py:1172 -- View the Ray dashboard at http://127.0.0.1:8265
2021-04-21 19:22:43,241 WARNING worker.py:1107 -- A worker died or was killed while executing task ffffffffffffffffa67dc375e60ddd1a23bd3bb901000000.
(pid=51169) 2021-04-21 19:22:43,229     ERROR worker.py:390 -- SystemExit was raised from the worker
(pid=51169) Traceback (most recent call last):
(pid=51169)   File "python/ray/_raylet.pyx", line 570, in ray._raylet.task_execution_handler
(pid=51169)   File "python/ray/_raylet.pyx", line 434, in ray._raylet.execute_task
(pid=51169)   File "python/ray/_raylet.pyx", line 473, in ray._raylet.execute_task
(pid=51169)   File "python/ray/_raylet.pyx", line 476, in ray._raylet.execute_task
(pid=51169)   File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
(pid=51169)   File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
(pid=51169)   File "/Users/chaokunyang/.pyenv/versions/3.8.1/envs/mars-py3.8-dev/lib/python3.8/site-packages/ray/function_manager.py", line 556, in actor_method_executor
(pid=51169)     return method(__ray_actor, *args, **kwargs)
(pid=51169)   File "a.py", line 7, in f1
(pid=51169)     sys.exit(0)
(pid=51169) SystemExit: 0
```

When using async actors:
```python
import sys
import ray

@ray.remote
class A:
    async def f1(self):
        sys.exit(0)

    async def f2(self):
        return 1


ray.init()
a = A.remote()
a.f1.remote()
ray.get(a.f2.remote())
```
The execution will hang forever.
- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by fyrestone** [comment]
> Since exit() ultimately “only” raises an exception, it will only exit the process when called from the main thread, and the exception is not intercepted.
Please refer to the Python doc: https://docs.python.org/3/library/sys.html#sys.exit

Ray runs the async actor in another thread (not the main thread). So, `a.f1.remote()` will make the asyncio thread exit, and the actor process hangs.

This is the minimal example to reproduce this problem:
```python
import sys
import asyncio
import threading


async def foo():
    sys.exit(0)  # hangs, the asyncio thread is exit.
    # return 1  # OK.


loop = asyncio.new_event_loop()
thrd = threading.Thread(
        target=lambda: loop.run_forever(),
        name="AsyncIO Thread"
)
thrd.daemon = True
thrd.start()

future = asyncio.run_coroutine_threadsafe(foo(), loop)
print(future.result())
```

There are many ways to fix this issue:
1. Run the async actor in main thread.
2. Wrap the coroutine to translate the `SystemExit` exception to an internal exception (e.g. RaySystemExit), then Ray reraise the `SystemExit` exception in main thread if got the RaySystemExit exception.

The first solution is better, it avoid many main thread issues, for example, we can't register a signal handler in async actor call.

**Comment by rkooo567** [comment]
cc @simon-mo 

Agree the first solution is better, but I am not sure it's even possible. IIRC, using a main thread was fundamentally not possible without big refactoring, but I might be wrong. Maybe the second solution seems to be more feasible unless we have a good idea about the first one.

**Comment by simon-mo** [comment]
We do properly handle the exit behavior if using `ray.exit_actor()` instead of `sys.exit`. 
https://github.com/ray-project/ray/pull/12693

**Comment by simon-mo** [comment]
Also this issue might be relevant: https://github.com/ray-project/ray/issues/13049

**Comment by edoakes** [comment]
It's definitely feasible to have asyncio actors run tasks on the main loop, but it'd be a pretty significant refactor. This would be a welcome change though -- we could also remove the hacky boost::fiber solution we have right now.

**Comment by jjyao** [comment]
We can no longer run asyncio actors on the main thread with the introduction of concurrency group since we may have multiple threads running async actor methods.

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
