### ISSUE TITLE
Issue on page /tune/examples/pbt_transformers.html

### ISSUE THREAD

**Issue by valiantljk** [ray-project/ray#15439]
Run into error:
```

Traceback (most recent call last):
  File "tune_face.py", line 164, in <module>
    tune_transformer(
  File "tune_face.py", line 123, in tune_transformer
    trainer.hyperparameter_search(
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1459, in hyperparameter_search
    best_run = run_hp_search(self, n_trials, direction, **kwargs)
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/transformers/integrations.py", line 232, in run_hp_search_ray
    ray.tune.with_parameters(_objective, local_trainer=trainer),
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/tune/function_runner.py", line 628, in with_parameters
    parameter_registry.put(prefix + k, v)

...
TypeError: cannot pickle '_thread.RLock' object
```

**Comment by valiantljk** [comment]
Looks like it fails during this function:

/ray/tune/function_runner.py, line 627, at func 'with_parameters'
```
    for k, v in kwargs.items():
            parameter_registry.put(prefix + k, v)       
```

And the object it tries to put into object store is 
```
<transformers.trainer.Trainer object
```

**Comment by tommasodelorenzo** [comment]
I am having the same issue, both with the mentioned page example, and with a custom dataset and model.

**Comment by richardliaw** [comment]
Hmm, OK thanks for reporting this. What's the tranformers version and Ray version that you are using?

**Comment by valiantljk** [comment]
ray: 1.2.0
transformer: 4.5.1

**Comment by richardliaw** [comment]
We currently pin to `transformers==4.3.2`. Could you try that instead?

**Comment by tommasodelorenzo** [comment]
Right after I wrote my comment I remembered having ran the /tune/examples/pbt_transformers on my other laptop.
There it indeed works with
ray: 1.2.0
transformers: 4.4.2

**Comment by valiantljk** [comment]
I changed transformers to 4.3.2, but run into another issue: https://github.com/lanpa/tensorboardX/issues/623

**Comment by richardliaw** [comment]
I wonder if you can just disable that? what is the full stacktrace?

**Comment by valiantljk** [comment]
```
2021-04-21 15:08:16,149	INFO services.py:1172 -- View the Ray dashboard at http://127.0.0.1:8265
Downloading and caching Tokenizer
Downloading and caching pre-trained model
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Downloading dataset.
Data already exists. Using downloaded data for task rte from /Users/dr6jl/Documents/rayflow/examples/huggingface/data
/Users/dr6jl/anaconda3/lib/python3.8/site-packages/transformers/data/datasets/glue.py:87: FutureWarning: This dataset will be removed from the library soon, preprocessing should be handled with the 🤗 Datasets library. You can have a look at this example script for pointers: https://github.com/huggingface/transformers/blob/master/examples/text-classification/run_glue.py
  warnings.warn(
/Users/dr6jl/anaconda3/lib/python3.8/site-packages/transformers/data/processors/glue.py:521: FutureWarning: This processor will be removed from the library soon, preprocessing should be handled with the 🤗 Datasets library. You can have a look at this example script for pointers: https://github.com/huggingface/transformers/blob/master/examples/text-classification/run_glue.py
  warnings.warn(DEPRECATION_WARNING.format("processor"), FutureWarning)
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/Users/dr6jl/anaconda3/lib/python3.8/site-packages/torch/storage.py:34: FutureWarning: pickle support for Storage will be removed in 1.5. Use `torch.save` instead
  warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)
2021-04-21 15:08:27,072	WARNING function_runner.py:540 -- Function checkpointing is disabled. This may result in unexpected behavior when using checkpointing features or certain schedulers. To enable, set the train function arguments to be `func(config, checkpoint_dir=None)`.
Traceback (most recent call last):
  File "/Users/dr6jl/.local/lib/python3.8/site-packages/crc32c/__init__.py", line 25, in <module>
    from crc32c import cffi as _crc32c
  File "/Users/dr6jl/.local/lib/python3.8/site-packages/crc32c/cffi.py", line 20, in <module>
    import crc32c._crc32c_cffi
ModuleNotFoundError: No module named 'crc32c._crc32c_cffi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tune_face.py", line 164, in <module>
    tune_transformer(
  File "tune_face.py", line 123, in tune_transformer
    trainer.hyperparameter_search(
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1382, in hyperparameter_search
    best_run = run_hp_search(self, n_trials, direction, **kwargs)
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/transformers/integrations.py", line 233, in run_hp_search_ray
    analysis = ray.tune.run(
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/tune/tune.py", line 363, in run
    callbacks = create_default_callbacks(
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/tune/utils/callback.py", line 112, in create_default_callbacks
    callbacks.append(TBXLoggerCallback())
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/tune/logger.py", line 591, in __init__
    from tensorboardX import SummaryWriter
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/tensorboardX/__init__.py", line 4, in <module>
    from .record_writer import RecordWriter
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/tensorboardX/record_writer.py", line 23, in <module>
    from .crc32c import crc32c
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/tensorboardX/crc32c.py", line 8, in <module>
    from crc32c import crc32 as _crc32c_native
  File "/Users/dr6jl/.local/lib/python3.8/site-packages/crc32c/__init__.py", line 29, in <module>
    warnings.warn(RuntimeWarning, "_SLOW_CRC32C_WARNING",)
TypeError: category must be a Warning subclass, not 'str'
```

**Comment by valiantljk** [comment]
I I just run 
```
from tensorboardX import SummaryWriter
```

It can also reproduce the error.

**Comment by richardliaw** [comment]
can you do pip uninstall tensorboardX for now?

**Comment by valiantljk** [comment]
It will then complain of module missing:

```

2021-04-21 16:05:25,848	INFO logger.py:595 -- pip install 'ray[tune]' to see TensorBoard files.
Traceback (most recent call last):
  File "tune_face.py", line 164, in <module>
    tune_transformer(
  File "tune_face.py", line 123, in tune_transformer
    trainer.hyperparameter_search(
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1382, in hyperparameter_search
    best_run = run_hp_search(self, n_trials, direction, **kwargs)
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/transformers/integrations.py", line 233, in run_hp_search_ray
    analysis = ray.tune.run(
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/tune/tune.py", line 363, in run
    callbacks = create_default_callbacks(
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/tune/utils/callback.py", line 112, in create_default_callbacks
    callbacks.append(TBXLoggerCallback())
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/tune/logger.py", line 591, in __init__
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
```

**Comment by richardliaw** [comment]
Could you try `TUNE_DISABLE_AUTO_CALLBACK_LOGGERS=1` for now?

**Comment by valiantljk** [comment]
Thanks, That works.

**Comment by richardliaw** [comment]
Let's keep this open because it seems like we need to check for stability with newest hf transformers

**Comment by valiantljk** [comment]
As closed in https://github.com/lanpa/tensorboardX/issues/623, with google-crc32c==1.1.2, the issue is gone.

**Comment by amogkam** [comment]
If you disable the memory tracker (pass in `skip_memory_metrics=True` into your `TrainingArguments`) then you will no longer get the pickling error.

In the next transformers release, `skip_memory_metrics` will default to True, and even if it is explicitly set to False, it will automatically be disabled if you are using Ray Tune for HPO.
