### ISSUE TITLE
Java API in Ray 1.3

### ISSUE THREAD

**Issue by guykhazma** [ray-project/ray#15496]
### What is the problem?

I am using ray-ml latest image (installed today) and trying to use the java API.
When creating an actor using `ActorCreator` and calling:
```
creator.setJvmOptions(Arrays.asList(javaOpts.split(" ")));
```
it fails to find the new method which receives a `List` instead of `String` raising the error:
```
xception in thread "dispatcher-event-loop-1" java.lang.NoSuchMethodError: io.ray.api.call.ActorCreator.setJvmOptions(Ljava/util/List;)Lio/ray/api/call/ActorCreator;
	at org.apache.spark.raydp.AppMasterJavaUtils.createExecutorActor(AppMasterJavaUtils.java:47)
	at org.apache.spark.deploy.raydp.RayAppMaster$RayAppMasterEndpoint.org$apache$spark$deploy$raydp$RayAppMaster$RayAppMasterEndpoint$$requestNewExecutor(RayAppMaster.scala:190)
	at org.apache.spark.deploy.raydp.RayAppMaster$RayAppMasterEndpoint.$anonfun$schedule$1(RayAppMaster.scala:177)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
	at org.apache.spark.deploy.raydp.RayAppMaster$RayAppMasterEndpoint.org$apache$spark$deploy$raydp$RayAppMaster$RayAppMasterEndpoint$$schedule(RayAppMaster.scala:176)
	at org.apache.spark.deploy.raydp.RayAppMaster$RayAppMasterEndpoint$$anonfun$receive$1.applyOrElse(RayAppMaster.scala:104)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:115)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The API was changed in this [PR](https://github.com/ray-project/ray/pull/14931)

I have verified the jar that is included in the image (`ray_dist.jar`) and it doesn't include the new API.

Also, it seems that 1.3 was not released for Java.

*Ray version and other system information (Python version, TensorFlow version, OS):* 1.3

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by jovany-wang** [comment]
It's not ready yet. https://github.com/ray-project/ray/pull/15471

**Comment by jovany-wang** [comment]
@guykhazma 
Just FYI that 1.1.3 was deployed to maven central repo.

**Comment by jovany-wang** [comment]
Feel free to let me know if your problem get solved.

**Comment by jovany-wang** [comment]
Close this since it's done.

**Comment by guykhazma** [comment]
@jovany-wang sorry I didn't get to check that yet. 
but as you said it should work fine.
thanks!
