### ISSUE TITLE
DeprecationWarning raised while starting ray with --no-redirect-output

### ISSUE THREAD

**Issue by adamasstokhorst** [ray-project/ray#15501]
### What is the problem?
Package references mentions a flag to disable STDOUT redirection ( https://docs.ray.io/en/master/package-ref.html#the-ray-command-line-api ), however attempting to use it raises a `DeprecationWarning: The redirect_output argument is deprecated.`
*Ray version and other system information (Python version, TensorFlow version, OS):* was Ray 1.3.0 -- still happening on Ray 2.0.0.dev0, Python 3.8.5, Windows 10.

### Reproduction (REQUIRED)
`ray start --no-redirect-output` on terminal.

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by anyscalesam** [comment]
latest ray has "--redirect-output-deprecated"
`Successfully installed ray-2.8.1
(base) sam@Samuels-MacBook-Pro-16 ~ % ray start --no-redirect-output
Traceback (most recent call last):
  File "/Users/sam/miniforge3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/Users/sam/miniforge3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 2498, in main
    return cli()
  File "/Users/sam/miniforge3/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sam/miniforge3/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/sam/miniforge3/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sam/miniforge3/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sam/miniforge3/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sam/miniforge3/lib/python3.8/site-packages/ray/autoscaler/_private/cli_logger.py", line 856, in wrapper
    return f(*args, **kwargs)
  File "/Users/sam/miniforge3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 644, in start
    ray_params = ray._private.parameter.RayParams(
  File "/Users/sam/miniforge3/lib/python3.8/site-packages/ray/_private/parameter.py", line 256, in __init__
    self._check_usage()
  File "/Users/sam/miniforge3/lib/python3.8/site-packages/ray/_private/parameter.py", line 448, in _check_usage
    raise DeprecationWarning("The redirect_output argument is deprecated.")
DeprecationWarning: The redirect_output argument is deprecated.
`
