### ISSUE TITLE
[serve] Max recursion depth exceeded when serializing fastapi app

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#15511]
```python
from typing import Dict
from fastapi import FastAPI

import ray
from ray import serve

ray.init(address="auto")

app = FastAPI()

@serve.deployment(name="custom_service")
@serve.ingress(app)
class CustomService:
    def deduplicate(self, data):
        data.drop_duplicates(inplace=True)
        return data

    @app.post("/deduplicate")
    def _deduplicate(self, request: Dict):
        data = request["data"]
        columns = request["columns"]
        import pandas as pd
        data = pd.DataFrame(data, columns=columns)
        data.drop_duplicates(inplace=True)
        return data.values.tolist()

CustomService.deploy()
```

```
(base) ray/serve % python repro.py
2021-04-26 11:22:36,000 INFO worker.py:654 -- Connecting to existing Ray cluster at address: 192.168.0.124:6379
Traceback (most recent call last):
  File "repro.py", line 13, in <module>
    class CustomService:
  File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 971, in decorator
    frozen_app = cloudpickle.loads(cloudpickle.dumps(app))
  File "/Users/eoakes/anaconda3/lib/python3.8/site-packages/starlette/datastructures.py", line 669, in __getattr__
    return self._state[key]
  File "/Users/eoakes/anaconda3/lib/python3.8/site-packages/starlette/datastructures.py", line 669, in __getattr__
    return self._state[key]
  File "/Users/eoakes/anaconda3/lib/python3.8/site-packages/starlette/datastructures.py", line 669, in __getattr__
    return self._state[key]
  [Previous line repeated 994 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by edoakes** [comment]
@simon-mo could you take a look at this? I believe it was introduced recently, the user who reported it said they didn't see the issue a few days ago.

**Comment by simon-mo** [comment]
I can't repro this with your script but i can repro it the issue without `ray.init`

**Comment by simon-mo** [comment]
PR: https://github.com/ray-project/ray/pull/15546
