### ISSUE TITLE
[rllib] DQN with learning rate schedule throws exception

### ISSUE THREAD

**Issue by antoine-galataud** [ray-project/ray#15554]
### What is the problem?

`lr_schedule` option throws an exception when used with `DQNTrainer` (or any trainer inheriting from its policy definition like APEX).

minimal reproduction example:

```python
import ray
from ray.rllib import agents

ray.init()
config = {'gamma': 0.9,
          'lr_schedule': [
                [0, 0.0001],
                [10000000, 6.25e-5],
          ],
          'num_workers': 2,
          'train_batch_size': 1000,
          'model': {
              'fcnet_hiddens': [128, 128]
          }}
trainer = agents.dqn.DQNTrainer(env='CartPole-v0', config=config)
results = trainer.train()
```

Output:

```
WARNING:tensorflow:From /usr/local/lib/python3.8/dist-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2021-04-28 11:43:47,115	INFO services.py:1267 -- View the Ray dashboard at http://127.0.0.1:8267
2021-04-28 11:43:48,902	INFO trainer.py:669 -- Tip: set framework=tfe or the --eager flag to enable TensorFlow eager execution
2021-04-28 11:43:48,902	INFO trainer.py:694 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=42197) WARNING:tensorflow:From /usr/local/lib/python3.8/dist-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=42197) Instructions for updating:
(pid=42197) non-resource variables are not supported in the long term
(pid=42194) WARNING:tensorflow:From /usr/local/lib/python3.8/dist-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=42194) Instructions for updating:
(pid=42194) non-resource variables are not supported in the long term
(pid=42197) 2021-04-28 11:43:51,560	ERROR worker.py:382 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=42197, ip=192.168.0.85)
(pid=42197)   File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
(pid=42197)   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
(pid=42197)   File "/home/antoine/.local/lib/python3.8/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=42197)     return method(__ray_actor, *args, **kwargs)
(pid=42197)   File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 514, in __init__
(pid=42197)     self._build_policy_map(policy_dict, policy_config)
(pid=42197)   File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1155, in _build_policy_map
(pid=42197)     policy_map[name] = cls(obs_space, act_space, merged_conf)
(pid=42197)   File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/policy/tf_policy_template.py", line 211, in __init__
(pid=42197)     before_init(self, obs_space, action_space, config)
(pid=42197)   File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/agents/dqn/dqn_tf_policy.py", line 322, in setup_early_mixins
(pid=42197)     LearningRateSchedule.__init__(policy, config["lr"], config["lr_schedule"])
(pid=42197)   File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/policy/tf_policy.py", line 936, in __init__
(pid=42197)     if self.framework == "tf":
(pid=42197) AttributeError: 'DQNTFPolicy' object has no attribute 'framework'
(pid=42194) 2021-04-28 11:43:51,560	ERROR worker.py:382 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=42194, ip=192.168.0.85)
(pid=42194)   File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
(pid=42194)   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
(pid=42194)   File "/home/antoine/.local/lib/python3.8/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=42194)     return method(__ray_actor, *args, **kwargs)
(pid=42194)   File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 514, in __init__
(pid=42194)     self._build_policy_map(policy_dict, policy_config)
(pid=42194)   File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1155, in _build_policy_map
(pid=42194)     policy_map[name] = cls(obs_space, act_space, merged_conf)
(pid=42194)   File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/policy/tf_policy_template.py", line 211, in __init__
(pid=42194)     before_init(self, obs_space, action_space, config)
(pid=42194)   File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/agents/dqn/dqn_tf_policy.py", line 322, in setup_early_mixins
(pid=42194)     LearningRateSchedule.__init__(policy, config["lr"], config["lr_schedule"])
(pid=42194)   File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/policy/tf_policy.py", line 936, in __init__
(pid=42194)     if self.framework == "tf":
(pid=42194) AttributeError: 'DQNTFPolicy' object has no attribute 'framework'
Traceback (most recent call last):
  File "dqn.py", line 15, in <module>
    trainer = agents.dqn.DQNTrainer(env='CartPole-v0', config=config)
  File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 121, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 516, in __init__
    super().__init__(config, logger_creator)
  File "/home/antoine/.local/lib/python3.8/site-packages/ray/tune/trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 707, in setup
    self._init(self.config, self.env_creator)
  File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 148, in _init
    self.workers = self._make_workers(
  File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 783, in _make_workers
    return WorkerSet(
  File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 79, in __init__
    remote_spaces = ray.get(self.remote_workers(
  File "/home/antoine/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/antoine/.local/lib/python3.8/site-packages/ray/worker.py", line 1483, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=42194, ip=192.168.0.85)
  File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
  File "/home/antoine/.local/lib/python3.8/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 514, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1155, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/policy/tf_policy_template.py", line 211, in __init__
    before_init(self, obs_space, action_space, config)
  File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/agents/dqn/dqn_tf_policy.py", line 322, in setup_early_mixins
    LearningRateSchedule.__init__(policy, config["lr"], config["lr_schedule"])
  File "/home/antoine/.local/lib/python3.8/site-packages/ray/rllib/policy/tf_policy.py", line 936, in __init__
    if self.framework == "tf":
AttributeError: 'DQNTFPolicy' object has no attribute 'framework'
```

Is it necessary to test this since we're in `tf_policy`?

*Ray version and other system information (Python version, TensorFlow version, OS):*

- Ray: 1.3.0
- TensorFlow: 2.3.1

### Reproduction (REQUIRED)

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by mvindiola1** [comment]
@antoine-galataud,

Yes it needs the check in order to distinguish between tensorflow 1 and tensorflow 2. It has to do different things depending on the version.


The issue is coming from the fact that tf_policy_template sets up:
1. early mixins <- this is where LearningRateSchedule is instantiated
2. instantiates the  DynamicTFPolicy <- this is where self.framework is set
3. late mixins <- this is where *I think* we actually want to instantiate LearningRateSchedule

I have not tested this but I think if you make these changes in ray/rllib/agents/dqn/dqn_torch_policy.py it will work for you.
1. Move this line: 
https://github.com/ray-project/ray/blob/f93f096fc92c67011477790650783d2db04ff705/rllib/agents/dqn/dqn_torch_policy.py#L317

into here: 
https://github.com/ray-project/ray/blob/f93f096fc92c67011477790650783d2db04ff705/rllib/agents/dqn/dqn_torch_policy.py#L323-L325


2. Remove the `setup_early_mixins` function entirely
https://github.com/ray-project/ray/blob/f93f096fc92c67011477790650783d2db04ff705/rllib/agents/dqn/dqn_torch_policy.py#L315-L318

3. Remove this line:
https://github.com/ray-project/ray/blob/f93f096fc92c67011477790650783d2db04ff705/rllib/agents/dqn/dqn_torch_policy.py#L400

Let us know how it goes for you.

Cheers,
Manny

**Comment by antoine-galataud** [comment]
@mvindiola1 thanks, this was the way to go.
