### ISSUE TITLE
[tune] tune run OptunaSearch: AttributeError: 'Study' object has no attribute 'ask'

### ISSUE THREAD

**Issue by Eleven1Liu** [ray-project/ray#15627]
### What is the problem?
When running `OptunaSearch`, there's an error `AttributeError: 'Study' object has no attribute 'ask'`. It seems that `ask` not used for a newer version of Optuna. Should I downgrade my optuna version to an older one? Thanks!

#### Versions
```
python: 3.6
optuna: 2.3.0
ray: 2.0.0.dev0
```

#### Command
```
tune.run(
        training_function,
        search_alg=OptunaSearch(metric='P@8', mode='max'),
        metric='P@8'
        mode='max',
        num_samples=50,
        config=model_config)
```

#### Error
```
Traceback (most recent call last):
  File "search_params.py", line 116, in <module>
    main()
  File "search_params.py", line 111, in main
    config=model_config)
  File "/home/<MASK>/venv/lib/python3.6/site-packages/ray/tune/tune.py", line 520, in run
    runner.step()
  File "/home/<MASK>/venv/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 481, in step
    next_trial = self._get_next_trial()  # blocking
  File "/home/<MASK>/venv/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 617, in _get_next_trial
    self._update_trial_queue(blocking=wait_for_trial)
  File "/home/<MASK>/venv/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 1074, in _update_trial_queue
    trial = self._search_alg.next_trial()
  File "/home/<MASK>/venv/lib/python3.6/site-packages/ray/tune/suggest/search_generator.py", line 88, in next_trial
    self._experiment.dir_name)
  File "/home/<MASK>/venv/lib/python3.6/site-packages/ray/tune/suggest/search_generator.py", line 95, in create_trial_if_possible
    suggested_config = self.searcher.suggest(trial_id)
  File "/home/<MASK>/venv/lib/python3.6/site-packages/ray/tune/suggest/optuna.py", line 238, in suggest
    self._ot_trials[trial_id] = self._ot_study.ask(
AttributeError: 'Study' object has no attribute 'ask'
```

**Comment by amogkam** [comment]
Hi @Eleven1Liu can you actually **upgrade** your Optuna version to 2.6.0? Alternatively, you could downgrade your Ray version to 1.2.0 and I believe that should work with your current Optuna version.

**Comment by Eleven1Liu** [comment]
Hi @amogkam, upgrading Optuna to 2.6.0 works. Thanks for help!!
