### ISSUE TITLE
DD-PPO not working on Win10 [rrlib]

### ISSUE THREAD

**Issue by DenysAshikhin** [ray-project/ray#15623]
### What is the problem?

DD-PPO does not work on win10. I have tried running it in administrator mode both in CMD and pycharm.

Full Stack Trace:
```
2021-05-03 19:00:01,026	INFO services.py:1267 -- View the Ray dashboard at http://127.0.0.1:8265
running on: 192.168.0.11:55555
2021-05-03 19:00:05,474	INFO trainer.py:694 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=2848) WARNING:tensorflow:From C:\Python38\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=2848) Instructions for updating:
(pid=2848) non-resource variables are not supported in the long term
(pid=2848) 2021-05-03 19:00:12,466	ERROR worker.py:382 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=2848, ip=192.168.0.11)
(pid=2848)   File "C:\Python38\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 780, in cmdline
(pid=2848)     ret = cext.proc_cmdline(self.pid, use_peb=True)
(pid=2848) PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'
(pid=2848) 
(pid=2848) During handling of the above exception, another exception occurred:
(pid=2848) 
(pid=2848) ray::RolloutWorker.__init__() (pid=2848, ip=192.168.0.11)
(pid=2848)   File "C:\Python38\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 679, in wrapper
(pid=2848)     return fun(self, *args, **kwargs)
(pid=2848)   File "C:\Python38\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 695, in wrapper
(pid=2848)     return fun(self, *args, **kwargs)
(pid=2848)   File "C:\Python38\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 783, in cmdline
(pid=2848)     ret = cext.proc_cmdline(self.pid, use_peb=False)
(pid=2848) PermissionError: [Errno 13] assume access denied (originated from NtQueryInformationProcess(ProcessBasicInformation) -> STATUS_NOT_FOUND)
(pid=2848) 
(pid=2848) During handling of the above exception, another exception occurred:
(pid=2848) 
(pid=2848) ray::RolloutWorker.__init__() (pid=2848, ip=192.168.0.11)
(pid=2848)   File "python\ray\_raylet.pyx", line 456, in ray._raylet.execute_task
(pid=2848)   File "C:\Python38\lib\site-packages\ray\_private\memory_monitor.py", line 134, in raise_if_low_memory
(pid=2848)     RayOutOfMemoryError.get_message(used_gb, total_gb,
(pid=2848)   File "C:\Python38\lib\site-packages\ray\_private\memory_monitor.py", line 43, in get_message
(pid=2848)     proc.cmdline()))
(pid=2848)   File "C:\Python38\lib\site-packages\ray\thirdparty_files\psutil\__init__.py", line 677, in cmdline
(pid=2848)     return self._proc.cmdline()
(pid=2848)   File "C:\Python38\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 681, in wrapper
(pid=2848)     raise convert_oserror(err, pid=self.pid, name=self._name)
(pid=2848) psutil.AccessDenied: psutil.AccessDenied (pid=72)
Traceback (most recent call last):
  File "C:/Users/denys/Documents/GitHub/Underlords/code/policy_server.py", line 173, in <module>
    trainer = DDPPOTrainer(config=DEFAULT_CONFIG)
  File "C:\Python38\lib\site-packages\ray\rllib\agents\trainer_template.py", line 121, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "C:\Python38\lib\site-packages\ray\rllib\agents\trainer.py", line 516, in __init__
    super().__init__(config, logger_creator)
  File "C:\Python38\lib\site-packages\ray\tune\trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\Python38\lib\site-packages\ray\rllib\agents\trainer.py", line 707, in setup
    self._init(self.config, self.env_creator)
  File "C:\Python38\lib\site-packages\ray\rllib\agents\trainer_template.py", line 148, in _init
    self.workers = self._make_workers(
  File "C:\Python38\lib\site-packages\ray\rllib\agents\trainer.py", line 783, in _make_workers
    return WorkerSet(
  File "C:\Python38\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 79, in __init__
    remote_spaces = ray.get(self.remote_workers(
  File "C:\Python38\lib\site-packages\ray\_private\client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "C:\Python38\lib\site-packages\ray\worker.py", line 1483, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=2848, ip=192.168.0.11)
  File "C:\Python38\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 780, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=True)
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

ray::RolloutWorker.__init__() (pid=2848, ip=192.168.0.11)
  File "C:\Python38\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Python38\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 695, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Python38\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 783, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=False)
PermissionError: [Errno 13] assume access denied (originated from NtQueryInformationProcess(ProcessBasicInformation) -> STATUS_NOT_FOUND)

During handling of the above exception, another exception occurred:

ray::RolloutWorker.__init__() (pid=2848, ip=192.168.0.11)
  File "python\ray\_raylet.pyx", line 456, in ray._raylet.execute_task
  File "C:\Python38\lib\site-packages\ray\_private\memory_monitor.py", line 134, in raise_if_low_memory
    RayOutOfMemoryError.get_message(used_gb, total_gb,
  File "C:\Python38\lib\site-packages\ray\_private\memory_monitor.py", line 43, in get_message
    proc.cmdline()))
  File "C:\Python38\lib\site-packages\ray\thirdparty_files\psutil\__init__.py", line 677, in cmdline
    return self._proc.cmdline()
  File "C:\Python38\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=72)

Process finished with exit code 1

```

### Reproduction (REQUIRED)

Pastebin of *pip list*: https://pastebin.com/3XKt911M

Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
parser = argparse.ArgumentParser(description='Optional app description')
parser.add_argument('-ip', type=str, help='IP of this device')

parser.add_argument('-checkpoint', type=str, help='location of checkpoint to restore from')


args = parser.parse_args()

DEFAULT_CONFIG = ppo.PPOTrainer.merge_trainer_configs(
    ppo.DEFAULT_CONFIG,
    {
        # During the sampling phase, each rollout worker will collect a batch
        # `rollout_fragment_length * num_envs_per_worker` steps in size.
        "rollout_fragment_length": 100,
        # Vectorize the env (should enable by default since each worker has
        # a GPU).
        "num_envs_per_worker": 1,
        # During the SGD phase, workers iterate over minibatches of this size.
        # The effective minibatch size will be:
        # `sgd_minibatch_size * num_workers`.
        "sgd_minibatch_size": 50,
        # Number of SGD epochs per optimization round.
        "num_sgd_iter": 25,
        # Download weights between each training step. This adds a bit of
        # overhead but allows the user to access the weights from the trainer.
        # "keep_local_weights_in_sync": True,

        # *** WARNING: configs below are DDPPO overrides over PPO; you
        #     shouldn't need to adjust them. ***
        # DDPPO requires PyTorch distributed.
        "framework": "torch",
        # The communication backend for PyTorch distributed.
        "torch_distributed_backend": "gloo",
        # Learning is no longer done on the driver process, so
        # giving GPUs to the driver does not make sense!
        "num_gpus": 0,
        # Each rollout worker gets a GPU.
        "num_gpus_per_worker": 0,
        # Require evenly sized batches. Otherwise,
        # collective allreduce could fail.
        "truncate_episodes": True,
        # This is auto set based on sample batch size.
        "train_batch_size": -1,
        # Use the connector server to generate experiences.
        "input": (
            lambda ioctx: PolicyServerInput(ioctx, args.ip, 55555)
        ),
        # Use a single worker process to run the server.
        "num_workers": 1,
        # Disable OPE, since the rollouts are coming from online clients.
        "input_evaluation": [],
        "callbacks": MyCallbacks,
        "env_config": {"sleep": True},
        'env': "CartPole-v0"
    },
    _allow_unknown_configs=True,
)

ray.init()

print(f"running on: {args.ip}:55555")

trainer = DDPPOTrainer(config=DEFAULT_CONFIG)

while True:
    print(pretty_print(trainer.train()))
    print(f"Finished train run #{i + 1}")
    i += 1
    checkpoint = trainer.save(checkpoint_path)
    print("Last checkpoint", checkpoint)
```

- [Yes] I have verified my script runs in a clean environment and reproduces the issue.
- [Latest wheel fails to install saying it is unsupported on my system] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by DenysAshikhin** [comment]
So I further tested with a different .py file (same code) but I removed unused import statements and get the following error:

```
2021-05-04 03:18:21,905	INFO logservicer.py:102 -- New logs connection established. Total clients: 1
Traceback (most recent call last):
  File "C:/Users/denys/Documents/GitHub/Underlords/code/a.py", line 73, in <module>
    trainer = DDPPOTrainer(config=DEFAULT_CONFIG)
  File "C:\Python38\lib\site-packages\ray\rllib\agents\trainer_template.py", line 121, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "C:\Python38\lib\site-packages\ray\rllib\agents\trainer.py", line 516, in __init__
    super().__init__(config, logger_creator)
  File "C:\Python38\lib\site-packages\ray\tune\trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\Python38\lib\site-packages\ray\rllib\agents\trainer.py", line 610, in setup
    self.env_creator = _global_registry.get(ENV_CREATOR, env)
  File "C:\Python38\lib\site-packages\ray\tune\registry.py", line 140, in get
    return pickle.loads(value)
EOFError: Ran out of input
```

I also forgot to mention this in my initial post, but the reason I ran into this bug is I tried to setup DD-PPO for my own external Env, except I would run into: 

```
  File "C:/Users/denys/Documents/GitHub/Underlords/code/a.py", line 73, in <module>
    trainer = DDPPOTrainer(config=DEFAULT_CONFIG)
  File "C:\Python38\lib\site-packages\ray\rllib\agents\trainer_template.py", line 121, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "C:\Python38\lib\site-packages\ray\rllib\agents\trainer.py", line 516, in __init__
    super().__init__(config, logger_creator)
  File "C:\Python38\lib\site-packages\ray\tune\trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\Python38\lib\site-packages\ray\rllib\agents\trainer.py", line 707, in setup
    self._init(self.config, self.env_creator)
  File "C:\Python38\lib\site-packages\ray\rllib\agents\trainer_template.py", line 148, in _init
    self.workers = self._make_workers(
  File "C:\Python38\lib\site-packages\ray\rllib\agents\trainer.py", line 783, in _make_workers
    return WorkerSet(
  File "C:\Python38\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 90, in __init__
    self._local_worker = self._make_worker(
  File "C:\Python38\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 317, in _make_worker
    worker = cls(
  File "C:\Python38\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 675, in __init__
    self.input_reader: InputReader = input_creator(self.io_context)
  File "C:/Users/denys/Documents/GitHub/Underlords/code/a.py", line 56, in <lambda>
    lambda ioctx: PolicyServerInput(ioctx, args.ip, 55555)
  File "C:\Python38\lib\site-packages\ray\rllib\env\policy_server_input.py", line 83, in __init__
    self.rollout_worker.sampler.get_metrics = get_metrics
AttributeError: 'NoneType' object has no attribute 'get_metrics'
```
The only thing I change to get the different errors, is the `env: "CartPole-v0"` or `env: "MyExternalEnv"`. I am 99% certain it isn't my env because if I instead use the PPO trainer (and the appropriate config variables) then it successfully trains while sample from multiple workers from both inside and outside my LAN.

**Comment by DenysAshikhin** [comment]
@sven1977 Has mentioned that this is a compatibility issue with Windows 10, so don't try DD-PPO without being on Unix...
