### ISSUE TITLE
[serve] Issue with serialization using FastAPI w/ `ray start`

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#15637]
```python
2021-05-03 17:59:49,002	INFO worker.py:664 -- Connecting to existing Ray cluster at address: 100.96.7.32:6379
(raylet, ip=100.96.7.33) Traceback (most recent call last):
(raylet, ip=100.96.7.33)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/workers/setup_worker.py", line 16, in <module>
(raylet, ip=100.96.7.33)     setup = import_attr(args.worker_setup_hook)
(raylet, ip=100.96.7.33)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/utils.py", line 1004, in import_attr
(raylet, ip=100.96.7.33)     module = importlib.import_module(module_name)
(raylet, ip=100.96.7.33)   File "/home/ray/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
(raylet, ip=100.96.7.33)     return _bootstrap._gcd_import(name[level:], package, level)
(raylet, ip=100.96.7.33)   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
(raylet, ip=100.96.7.33)   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
(raylet, ip=100.96.7.33)   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
(raylet, ip=100.96.7.33) ModuleNotFoundError: No module named 'Non'
```

**Comment by edoakes** [comment]
@architkulkarni can you try to reproduce this locally?
