### ISSUE TITLE
[dashboard] Dashboard completely empty

### ISSUE THREAD

**Issue by johann-petrak** [ray-project/ray#15650]
Ray version: 1.3.0, installed with `pip install -U ray[default]`
Python: 3.8 in a conda environment
OS: Ubuntu 18.04

No matter how I start ray, either with
* `ray start --head` from the command line
* or `ray.init()` from Python

When I visit http://127.0.0.1:8265 afterwards, I get a completely blank screen, in Firefox and Chrome.

In order to make sure this is not because of any installed add-on I did:

```
mkdir tmpff
firefox -profile tmpff -no-remote http://127.0.0.1:8265
```

This shows the dashboard for a very short time (from a fraction of a second to about a second) after which the page goes completely blank and stays that way. 

When adding arbitrary path elements to the URL, sometimes the left-hand pane with the NODES/JOBS/.. menu appears and stays. Clicking one of NODES, JOBS, ACTORS, LOGS, shows the screen OK and the screen stays.
However, clicking "BACK TO EXISTING DASHBOARD" shows a completely blank screen again.

When looking at the JS console of the page I get:
```
TypeError: e is undefined      react-dom.production.min.js:209:194
```

No idea if the following is unrelated or not, but the dashboard_agent.log contains many errors line this one:
```
2021-05-05 19:08:34,252	ERROR reporter_agent.py:531 -- Error publishing node physical stats.
13Traceback (most recent call last):
14  File "/home/johann/software/anaconda/envs/ray/lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 526, in _perform_iteration
15    records_reported = self._record_stats(stats, formatted_status)
16  File "/home/johann/software/anaconda/envs/ray/lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 415, in _record_stats
17    gpus_utilization += gpu["utilization_gpu"]
18TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
192021-05-05 19:08:36,772	ERROR reporter_agent.py:531 -- Error publishing node physical stats.
20Traceback (most recent call last):
21  File "/home/johann/software/anaconda/envs/ray/lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 526, in _perform_iteration
22    records_reported = self._record_stats(stats, formatted_status)
23  File "/home/johann/software/anaconda/envs/ray/lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 415, in _record_stats
24    gpus_utilization += gpu["utilization_gpu"]
25TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

**Comment by simon-mo** [comment]
Does the machine has any GPUs? If so what type? Thanks!

**Comment by johann-petrak** [comment]
Yes - it does have an old GF108 [GeForce GT 630] and it uses the NVIDIA driver 390

**Comment by johann-petrak** [comment]
BTW I did this:
* installed ray in exactly the same way on my laptop: dashboard works fine there
* started ray on the original machine so that the dashboard host is 0.0.0.0
* tried to view the dashboard from the original machine remotely on the laptop: this also fails

**Comment by devinsaini** [comment]
I'm getting the same issue with Ray 1.4.0. Running on Ubuntu 20.04 over Windows WSL2. My laptop has GeForce GTX 1650 Ti.
The dashboard shows up momentarily and then disappears. I checked Chrome developer tools and see a Javascript error

```
react-dom.production.min.js:209 TypeError: Cannot read property 'length' of undefined
    at NodeInfo.tsx:211
    at Array.filter (<anonymous>)
    at Gn (NodeInfo.tsx:211)
    at Qi (react-dom.production.min.js:153)
    at _a (react-dom.production.min.js:175)
    at vl (react-dom.production.min.js:263)
    at cu (react-dom.production.min.js:246)
```

**Comment by devinsaini** [comment]
I'm also seeing this error in dashboard_agent.log:

`2021-06-25 13:55:12,704 ERROR reporter_agent.py:539 -- Error publishing node physical stats.
Traceback (most recent call last):
  File "/home/devin/anaconda3/envs/phx/lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 534, in _perform_iteration
    records_reported = self._record_stats(stats, formatted_status)
  File "/home/devin/anaconda3/envs/phx/lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 423, in _record_stats
    gpus_utilization += gpu["utilization_gpu"]
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'`

**Comment by munro** [comment]
I'm having the same issue, it looks like the issue for me is `gpustat` is failing to import on Windows.
```
In [1]: import gpustat
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-6fad16bef0db> in <module>
----> 1 import gpustat

c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\gpustat\__init__.py in <module>
      5 __version__ = '0.6.0'
      6
----> 7 from .core import GPUStat, GPUStatCollection
      8 from .core import new_query
      9 from .__main__ import print_gpustat, main

c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\gpustat\core.py in <module>
     23 import psutil
     24 import pynvml as N
---> 25 from blessings import Terminal
     26
     27 NOT_SUPPORTED = 'Not Supported'

c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\blessings\__init__.py in <module>
      3
      4 from contextlib import contextmanager
----> 5 import curses
      6 from curses import setupterm, tigetnum, tigetstr, tparm
      7 from fcntl import ioctl

c:\users\USER\appdata\local\programs\python\python38\lib\curses\__init__.py in <module>
     11 """
     12
---> 13 from _curses import *
     14 import os as _os
     15 import sys as _sys

ModuleNotFoundError: No module named '_curses'
```
