### ISSUE TITLE
ArrowIOError during training

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1565]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: master
- **Python version**: 2.7
- **Exact command to reproduce**: start apex training with 4 concurrent experiments; wait ~10 hours. Note that this doesn't seem to happen with 1 concurrent experiment.

### Describe the problem
I've seen this happen a few times after several hours at high load (near 10Gbps network usage by plasma manager)

### Source code / logs
```
Traceback (most recent call last):
  File "./train.py", line 83, in <module>
    run_experiments(experiments, scheduler=_make_scheduler(args))
  File "/home/ubuntu/ray/python/ray/tune/tune.py", line 54, in run_experiments
    runner.step()
  File "/home/ubuntu/ray/python/ray/tune/trial_runner.py", line 91, in step
    self._process_events()
  File "/home/ubuntu/ray/python/ray/tune/trial_runner.py", line 213, in _process_events
    [result_id], _ = ray.wait(list(self._running))
  File "/home/ubuntu/ray/python/ray/worker.py", line 2337, in wait
    num_returns)
  File "plasma.pyx", line 595, in pyarrow.plasma.PlasmaClient.wait
  File "error.pxi", line 79, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Encountered unexpected EOF
Remote function train failed with:

Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/worker.py", line 762, in _process_task
    *arguments)
  File "/home/ubuntu/ray/python/ray/actor.py", line 209, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/ubuntu/ray/python/ray/tune/trainable.py", line 107, in train
    result = self._train()
  File "/home/ubuntu/ray/python/ray/rllib/dqn/dqn.py", line 205, in _train
    self.global_timestep += self.optimizer.step()
  File "/home/ubuntu/ray/python/ray/rllib/optimizers/apex_optimizer.py", line 224, in step
    sample_timesteps, train_timesteps = self._step()
  File "/home/ubuntu/ray/python/ray/rllib/optimizers/apex_optimizer.py", line 244, in _step
    for ev, sample_batch in self.sample_tasks.completed():
  File "/home/ubuntu/ray/python/ray/rllib/optimizers/apex_optimizer.py", line 36, in completed
    ready, _ = ray.wait(pending, num_returns=len(pending), timeout=10)
  File "/home/ubuntu/ray/python/ray/worker.py", line 2337, in wait
    num_returns)
  File "plasma.pyx", line 595, in pyarrow.plasma.PlasmaClient.wait
  File "error.pxi", line 79, in pyarrow.lib.check_status
ArrowIOError: Broken pipe
```

**Comment by ericl** [comment]
FATAL error in logs:
```
local_scheduler_0-2018-02-19_07-25-18-05909.err:[FATAL] (/home/ubuntu/ray/src/local_scheduler/local_scheduler_algorithm.cc:573: errno: Bad file descriptor) Lost connection to the plasma manager, local scheduler is exiting. Error: IOError: Broken pipe
```

**Comment by valldabo2** [comment]
+1 getting the same error but with python 3.6 and custom environment

**Comment by arank** [comment]
+1 getting the same error triggered with Python 2.7 & Ubuntu 16.04 with a high memory usage job:

  File "pyarrow/error.pxi", line 83, in pyarrow.lib.check_status
    raise ArrowIOError(message)
ArrowIOError: Broken pipe

  This error is unexpected and should not have happened. Somehow a worker
  crashed in an unanticipated way causing the main_loop to throw an exception,
  which is being caught in "python/ray/workers/default_worker.py".

**Comment by ericl** [comment]
Closing stale issue -- possibly fixed in new xray backend.

**Comment by whikwon** [comment]
I got the same issue during training. 
![pyarrow_error](https://user-images.githubusercontent.com/30768596/44962506-9b2bef80-af5c-11e8-95a9-a989409c25a7.png)

**Comment by ericl** [comment]
@whikwon perhaps try RAY_USE_XRAY=1 and see if that fixes it? Unfortunately we are in the middle of deprecating the old backend, so it makes more sense to try to move to the new x-ray backend rather than trace down bugs in the old one.

**Comment by ericl** [comment]
Btw, ArrowIOError often means something else crashed (it is a misleading error message). I would check the usual: memory usage, `dmesg` output, and logs in /tmp/raylogs.

**Comment by whikwon** [comment]
Use when executing script like `RAY_USE_XRAY=1 python ppo.py` or before starting ray? `RAY_USE_XRAY=1 ray start --head --redis-port=8787, python ppo.py`

**Comment by ericl** [comment]
I would make sure to set it for all commands. Otherwise, weird things could
happen.

**Comment by whikwon** [comment]
OK, thank you @ericl
