### ISSUE TITLE
[k8s] ray.init() can not connect to the port-forwarded cluster

### ISSUE THREAD

**Issue by ebr** [ray-project/ray#15653]
### What is the problem?

- Ray nightly build (`ray-2.0.0.dev0-cp38`)
- cluster deployed using Ray Operator
- `kubectl port-forward <head-node pod> 10001` is working; I am also port-forwarding the dashboard and able to see it.

I am trying the [Streaming MapReduce](https://docs.ray.io/en/master/auto_examples/plot_streaming.html) example, but this likely applies to any example. 

To summarize: `ray.init(address="127.0.0.1:10001")` is unable to connect to the port-forwarded head node of cluster, but `ray.util.connect("127.0.0.1:10001")` works as expected.

### Reproduction (REQUIRED)

```
# port forwarding
kubectl port-forward <head-node pod> 10001

# set the environment variable, which is ultimately the desired behaviour
export RAY_ADDRESS="127.0.0.1:10001"

# (also tested by modifying the arguments like `ray.init(address="127.0.0.1:10001")`, with the same effect)

# run the script
python ray/doc/examples/streaming/streaming.py

2021-05-05 18:45:35,937 INFO worker.py:663 -- Connecting to existing Ray cluster at address: 192.168.200.119:10001
Traceback (most recent call last):
  File "/home/eugene/.cache/pypoetry/virtualenvs/ray-play-Watq55vL-py3.8/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/eugene/.cache/pypoetry/virtualenvs/ray-play-Watq55vL-py3.8/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/eugene/.cache/pypoetry/virtualenvs/ray-play-Watq55vL-py3.8/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "streaming.py", line 76, in <module>
    ray.init()
  File "/home/eugene/.cache/pypoetry/virtualenvs/ray-play-Watq55vL-py3.8/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/eugene/.cache/pypoetry/virtualenvs/ray-play-Watq55vL-py3.8/lib/python3.8/site-packages/ray/worker.py", line 767, in init
    _global_node = ray.node.Node(
  File "/home/eugene/.cache/pypoetry/virtualenvs/ray-play-Watq55vL-py3.8/lib/python3.8/site-packages/ray/node.py", line 163, in __init__
    session_name = _get_with_retry(redis_client, "session_name")
  File "/home/eugene/.cache/pypoetry/virtualenvs/ray-play-Watq55vL-py3.8/lib/python3.8/site-packages/ray/node.py", line 41, in _get_with_retry
    result = redis_client.get(key)
  File "/home/eugene/.cache/pypoetry/virtualenvs/ray-play-Watq55vL-py3.8/lib/python3.8/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/home/eugene/.cache/pypoetry/virtualenvs/ray-play-Watq55vL-py3.8/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/eugene/.cache/pypoetry/virtualenvs/ray-play-Watq55vL-py3.8/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/eugene/.cache/pypoetry/virtualenvs/ray-play-Watq55vL-py3.8/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 192.168.200.119:10001. Connection refused.
```

Note that the loopback address (`127.0.0.1`) is replaced by my private IP (`192.168.200.119`),  which is my wlan interface.

Further, I noticed that the exception being raised by `redis`, so forwarded port `6379` as well, but without success (same exception).

However, if I try to use `ray.util.connect()`:

```diff
-   ray.init(address="127.0.0.1:10001")
+   ray.util.connect("127.0.0.1:10001")
```

The connection succeeds and uses the loopback interface. This leads me to believe the issue is within Ray, and while I could probably work around it somehow in my local networking stack or the environment, that would not be the right way to go about it. It's possible I might be missing something in the documentation?

The goal is to make any script portable between running on ad-hoc local clusters and remote K8s-managed clusters by only setting the `RAY_ADDRESS` environment variable, or otherwise avoiding any modifications to the script.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
@DmitriGekhtman can you take a look?

**Comment by DmitriGekhtman** [comment]
`ray.init` with address specified only works when executed on a node of the cluster.
`ray.util.connect` uses the Ray client-server connection and works remotely  

The distinction between the `ray.init` and `ray.util.connect` APIs is confusing and it's on our mind to unify these in the future.

The more immediate action item is to add more context to this page of documentation...

**Comment by ebr** [comment]
Thank you @DmitriGekhtman - makes sense. So in our own scripts, we'll have to distinguish between running inside and outside of the cluster, by e.g. checking for the `KUBERNETES_SERVICE_HOST` env var. But the examples will not work out of the box, which is acceptable at this point. Thanks for clarifying.

**Comment by DmitriGekhtman** [comment]
Looks like the provided script uses `ray.init()`, which starts Ray on the local machine.

It's also possible to use `ray.util.connect` to connect from a pod in the same K8s cluster but outside the Ray cluster.
https://docs.ray.io/en/master/cluster/kubernetes.html#using-ray-client-to-connect-from-within-the-kubernetes-cluster
