### ISSUE TITLE
Ray duplicate data from GPU to CPU when placing an actor on GPU

### ISSUE THREAD

**Issue by valiantljk** [ray-project/ray#15692]
### What is the problem?
I first copied data onto GPU, and then submitted one actor task, got this error:

```
2021-05-08 09:11:05,366	WARNING worker.py:1115 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 684, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 687, in ray._raylet.spill_objects_handler
  File "/data00/jialin.liu/.local/lib/python3.7/site-packages/ray/external_storage.py", line 474, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/data00/jialin.liu/.local/lib/python3.7/site-packages/ray/external_storage.py", line 277, in spill_objects
    owner_addresses, url)
  File "/data00/jialin.liu/.local/lib/python3.7/site-packages/ray/external_storage.py", line 134, in _write_multiple_objects
    f.write(memoryview(buf))
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects.
2021-05-08 09:11:35,342	WARNING worker.py:1115 -- The node with node id: 0f3338258b620558e674aef4f02d8aa483e3a962a0fb391ee02bfb9a and ip: 10.206.77.137 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.
^Z
```
It looks like the dependency resolving in Ray will first copy the data from GPU and to somewhere that Ray thinks is local or optimal. 

What is expected, is that since the actor will be placed on the GPU 0, and data is already on GPU 0, there shouldn't be any data movement. 

*Ray version and other system information (Python version, TensorFlow version, OS):*
* Ray 1.3.0
* Python 3.7.3
* Tesla V100
### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
import ray
import time
import torch
import numpy as np

ray.init(num_cpus=1, num_gpus=1)

@ray.remote(num_gpus=1)
def matp_gpu(t1, t2):
	start = time.time()
	torch.mm(t1,t2)
	end = time.time()
	print("time:%f"%(end-start))

t1=np.random.rand(10000,100000)
t2=np.random.rand(100000,10000)
tt1 = torch.tensor(t1, device = torch.device('cuda:0'))
tt2 = torch.tensor(t2, device = torch.device('cuda:0'))

ray.get([matp_gpu.remote(tt1, tt2) for _ in range(2)])
```

Reducing the data size can avoid the error. 

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
