### ISSUE TITLE
[rllib] Error while using "count_steps_by": "agent_steps" and misleading documentation

### ISSUE THREAD

**Issue by Rohanjames1997** [ray-project/ray#15708]
### What is the problem?
**Problem 1:**
While running the MultiAgentCartPole environment, the training script crashed when I set the` "count_steps_by"` config to `"agent_steps" `. Received an `AttributeError: 'SampleBatch' object has no attribute 'agent_steps'` (Whole stacktrace below)

**Problem 2**
In the [RLlib Sample Collection and Trajectory View docs](https://docs.ray.io/en/master/rllib-sample-collection.html?highlight=complete_episodes#the-samplecollector-class-is-used-to-store-and-retrieve-temporary-data), it says that 

> If batch_mode is “complete_episodes”, rollout_fragment_length is ignored
 
While in reality, it does not seem to be ignored.

The following script demonstrates both these problems

**Using python 3.7.7, ray==1.3.0**

### Reproduction (REQUIRED)
For **Problem 1**
```
import ray
from ray.rllib.agents import ppo, trainer
from ray.tune.logger import pretty_print
from ray.rllib.examples.env.multi_agent import MultiAgentCartPole

if __name__ == "__main__":
    ray.init()
    trainer = ppo.PPOTrainer(env=MultiAgentCartPole, config={
        "num_workers": 4,
        "batch_mode": "complete_episodes",
        "framework": "torch",
        "train_batch_size": 2560,
        "horizon":8,
        "sgd_minibatch_size": 3,
        "num_sgd_iter": 2,
        "env_config":{
            "num_agents":4
        },
        "multiagent": {
            "count_steps_by": "agent_steps"
        },

    })
    print(pretty_print(trainer.train()))
```

This script (with agent_steps) gave me the following error:
```
2021-05-09 13:36:58,063 INFO services.py:1269 -- View the Ray dashboard at http://127.0.0.1:8265
2021-05-09 13:37:09,724 INFO trainer.py:696 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=23448) C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\gym\logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
(pid=23448)   warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
(pid=24000) C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\gym\logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
(pid=24000)   warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
(pid=13572) C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\gym\logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
(pid=13572)   warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
(pid=23468) C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\gym\logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
(pid=23468)   warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\gym\logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
2021-05-09 13:37:19,190 WARNING util.py:53 -- Install gputil for GPU system monitoring.
Traceback (most recent call last):
  File ".\test.py", line 24, in <module>
    print(pretty_print(trainer.train()))
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\rllib\agents\trainer.py", line 573, in train
    raise e
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\rllib\agents\trainer.py", line 562, in train
    result = Trainable.train(self)
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\tune\trainable.py", line 232, in train
    result = self.step()
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\rllib\agents\trainer_template.py", line 162, in step
    res = next(self.train_exec_impl)
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\util\iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\util\iter.py", line 843, in apply_filter
    for item in it:
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\util\iter.py", line 843, in apply_filter
    for item in it:
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\util\iter.py", line 876, in apply_flatten
    for item in it:
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\util\iter.py", line 828, in add_wait_hooks
    item = next(it)
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\util\iter.py", line 471, in base_iterator
    yield ray.get(futures, timeout=timeout)
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\_private\client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\worker.py", line 1481, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::RolloutWorker.par_iter_next() (pid=24000, ip=192.168.0.170)
  File "python\ray\_raylet.pyx", line 505, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\_private\function_manager.py", line 556, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\util\iter.py", line 1152, in par_iter_next
    return next(self.local_it)
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 332, in gen_rollouts
    yield self.sample()
  File "C:\Users\Rohan\anaconda3\envs\dgl\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 709, in sample
    batches[0].agent_steps()
AttributeError: 'SampleBatch' object has no attribute 'agent_steps'
```

For **Problem 2**, the same script can be used, but with the following config:
```
trainer = ppo.PPOTrainer(env=MultiAgentCartPole, config={
        "num_workers": 4,
        "batch_mode": "complete_episodes",
        "framework": "torch",
        "train_batch_size": 2560,
        "rollout_fragment_length": 500, #vary this
        "horizon":8,
        "sgd_minibatch_size": 3,
        "num_sgd_iter": 2,
        "env_config":{
            "num_agents":4
        },
        "multiagent": {
            "count_steps_by": "env_steps"
        },

    })
```

With "rollout_fragment_length": 500, the number of **episodes per iteration is 128**, while with "rollout_fragment_length": 100, the number of **episodes per iteration is 80**. 
According to the [documentation](https://docs.ray.io/en/master/rllib-sample-collection.html?highlight=complete_episodes#the-samplecollector-class-is-used-to-store-and-retrieve-temporary-data), if `batch_mode is “complete_episodes”, rollout_fragment_length is ignored`. This experiment seems to contradict that.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
