### ISSUE TITLE
Basic Python API Example Error (rllib)

### ISSUE THREAD

**Issue by ahalev** [ray-project/ray#15724]
I am attempting to run the [Basic Python API example](https://docs.ray.io/en/master/rllib-training.html#basic-python-api) and am getting the following error: 

``` python
Traceback (most recent call last):
  File "/home/ahalev/.pycharm_helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/ahalev/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/ahalev/mgrid/halev_dev/algos/hpc_runs/comparison_algos/dqn_rllib.py", line 10, in <module>
    trainer = ppo.PPOTrainer(config=config, env="CartPole-v0")
  File "/home/ahalev/.conda/envs/remote_env/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 122, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/ahalev/.conda/envs/remote_env/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 543, in __init__
    super().__init__(config, logger_creator)
  File "/home/ahalev/.conda/envs/remote_env/lib/python3.6/site-packages/ray/tune/trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/ahalev/.conda/envs/remote_env/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 653, in setup
    config)
  File "/home/ahalev/.conda/envs/remote_env/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 1140, in merge_trainer_configs
    cls._override_all_subkeys_if_type_changes)
  File "/home/ahalev/.conda/envs/remote_env/lib/python3.6/site-packages/ray/tune/utils/util.py", line 228, in deep_update
    raise Exception("Unknown config parameter `{}` ".format(k))
Exception: Unknown config parameter `eager`
```

When I remove the line `config["eager"] = False` it appears to work. 

I am using ray-2.0.0.dev0. Thanks!

**Comment by sven1977** [comment]
Thanks for raising this @ahalev , great catch! Will fix this.
Background: The `eager` config key is no longer recognized. Use `framework=[tf|tfe|tf2]` instead (tf=static-graph, tfe=tf1.x-eager, tf2=tf2.x-eager).

**Comment by sven1977** [comment]
https://github.com/ray-project/ray/pull/15736
