### ISSUE TITLE
ValueError: attempted relative import beyond top-level package

### ISSUE THREAD

**Issue by valiantljk** [ray-project/ray#15825]
### What is the problem?
I was using Ray to run a python module, e.g., python -m folder/subfolder/my_module 
Run into this problem: (without ray, I can run successfully)
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tiger/runner/runner_lite/op/bench_test.py", line 535, in <module>
    ray.get(actor.__call__.remote())
  File "/data00/jialin.liu/.local/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/data00/jialin.liu/.local/lib/python3.7/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::ModelTrainer.__call__() (pid=31103, ip=10.206.77.137)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/tiger/runner/runner_lite/op/ptx_v1/__init__.py", line 1, in <module>
    import ptx
  File "/opt/tiger/runner/runner_lite/op/ptx/__init__.py", line 13, in <module>
    from ...compat.ptx import *
ValueError: attempted relative import beyond top-level package

During handling of the above exception, another exception occurred:

ray::ModelTrainer.__call__() (pid=31103, ip=10.206.77.137)
  File "python/ray/_raylet.pyx", line 473, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 476, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/opt/tiger/runner/runner_lite/op/base.py", line 292, in __call__
    res = self.run(*args, **kwargs)
  File "/opt/tiger/runner/runner_lite/op/bench_test.py", line 400, in run
    'eval_batch_size': self.getc('evaluate.batch_size'),
  File "/opt/tiger/runner/runner_lite/op/bench_test.py", line 245, in run_train_purely
    model_train_result = ModelTrainerRunner()
  File "/opt/tiger/runner/runner_lite/op/base.py", line 292, in __call__
    res = self.run(*args, **kwargs)
  File "/opt/tiger/runner/runner_lite/op/train_model_simply.py", line 200, in run
    ModelTrainer = RegisterGet(self.getc('train.runner'))
  File "/opt/tiger/runner/runner_lite/register.py", line 7, in RegisterGet
    return import_sth_from_path(runner_mapping.get(p, p))
  File "/opt/tiger/runner/runner_lite/helper/module.py", line 19, in import_sth_from_path
    t = importlib.import_module(mod_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/tiger/runner/runner_lite/op/ptx_v1/__init__.py", line 1, in <module>
    import ptx
  File "/opt/tiger/runner/runner_lite/op/ptx/__init__.py", line 13, in <module>
    from ...compat.ptx import *
ValueError: attempted relative import beyond top-level package
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

- Ray 1.2.0 or 1.3.0
- Python 3.7
- OS: Linux
- Run in a docker container. 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

The codebase is quite complex, I haven't had time to prepare a minimal code. 
Using ray to wrap the existing codebase so far only adds a few lines, 
e.g., 
instead of 
A.fun()
I converted the class into an actor:
@ray.remote
class A

then run it as A.fun.remote()

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by valiantljk** [comment]
Close this, as it turns out not Ray's issue.

**Comment by valiantljk** [comment]
reopen this, after a few tests, I can confirm, even adding one line: ray.init(), the existing working code will raise the importing error
```
ValueError: attempted relative import beyond top-level package
```

**Comment by simon-mo** [comment]
This error typically happens because Ray starts in a different path that cannot run ` from ...compat.ptx import *`. maybe consider running `ray start` or `ray.init` in `/opt/tiger/runner/runner_lite`? but i think the real issue is that relative import with Ray just doesn't work well because it's hard to pin exactly where to find the package files. 

One common solution is to make all the import global import. So 
```
from ...compat.ptx import *
```
becomes
```
from runner_lite.compat.ptx import *
```

Where you can write a `setup.py` file to create `runner_lite` package, and use `python setup.py develop` to link the local directory with global package directory. 
See https://flamy.ca/blog/2017-01-02-installing-python-packages-in-development-mode.html

**Comment by valiantljk** [comment]
Thanks, I think this can be closed for now. 
Fyi, I re-structured the code, so the relative path import becomes global import. and each required package are installed locally, with 
```
pip install . 
```
