### ISSUE TITLE
[rllib/tune] SystemExit was raised from the worker

### ISSUE THREAD

**Issue by abe2122** [ray-project/ray#15862]
When running the following command 

`rllib train --run=PPO --env=CartPole-v0 --torch --stop '{"episode_reward_max":200}'`

I encounter the following error.

```
(pid=13200) 2021-05-17 19:30:42,950	ERROR worker.py:382 -- SystemExit was raised from the worker
(pid=13200) Traceback (most recent call last):
(pid=13200)   File "python/ray/_raylet.pyx", line 495, in ray._raylet.execute_task
(pid=13200)   File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
(pid=13200)   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
(pid=13200)   File "/home/user/.local/lib/python3.8/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
(pid=13200)     return method(__ray_actor, *args, **kwargs)
(pid=13200)   File "/home/user/.local/lib/python3.8/site-packages/ray/actor.py", line 1001, in __ray_terminate__
(pid=13200)     ray.actor.exit_actor()
(pid=13200)   File "/home/user/.local/lib/python3.8/site-packages/ray/actor.py", line 1077, in exit_actor
(pid=13200)     raise exit
(pid=13200) SystemExit: 0
(pid=13200) 
(pid=13200) During handling of the above exception, another exception occurred:
(pid=13200) 
(pid=13200) Traceback (most recent call last):
(pid=13200)   File "python/ray/_raylet.pyx", line 599, in ray._raylet.task_execution_handler
(pid=13200)   File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task
(pid=13200)   File "python/ray/_raylet.pyx", line 488, in ray._raylet.execute_task
(pid=13200)   File "python/ray/includes/libcoreworker.pxi", line 33, in ray._raylet.ProfileEvent.__exit__
(pid=13200)   File "/usr/local/lib/python3.8/traceback.py", line 167, in format_exc
(pid=13200)     return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
(pid=13200)   File "/usr/local/lib/python3.8/traceback.py", line 120, in format_exception
(pid=13200)     return list(TracebackException(
(pid=13200)   File "/usr/local/lib/python3.8/traceback.py", line 506, in __init__
(pid=13200)     self.__suppress_context__ = \
(pid=13200)   File "/home/user/.local/lib/python3.8/site-packages/ray/worker.py", line 379, in sigterm_handler
(pid=13200)     sys.exit(1)
(pid=13200) SystemExit: 1
2021-05-17 19:30:43,050	INFO tune.py:549 -- Total run time: 10.06 seconds (9.25 seconds for the tuning loop).
```

using,
```
ray=1.3.0
Python=3.8.0
TensorFlow=2.5.0
CentOS 8
```

It looks like this only occurs after the training process finishes though. Also looks very similar to #15685, so wondering if there's a fix for this? If not, is this something to be concerned about? Or is it possible to catch this error and continue on?

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
@abe2122 can you check if this is still happening on 1.4?

**Comment by abe2122** [comment]
@richard4912 looks like everything is good now. Thanks!
