### ISSUE TITLE
Error downloading Redis when building Linux wheels.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1587]
Recently I've been seeing the following error when building wheels in Travis, but I can reproduce it with 

```
docker run --rm -w /ray -v `pwd`:/ray -ti quay.io/xhochy/arrow_manylinux1_x86_64_base:latest /ray/python/build-wheel-manylinux1.sh
```

The error is 
```
+++ dirname ../build.sh
++ cd ..
++ pwd
+ ROOT_DIR=/ray
+ [[ -z /opt/python/cp27-cp27mu/bin/python ]]
+ PYTHON_EXECUTABLE=/opt/python/cp27-cp27mu/bin/python
+ echo 'Using Python executable /opt/python/cp27-cp27mu/bin/python.'
Using Python executable /opt/python/cp27-cp27mu/bin/python.
++ uname
+ unamestr=Linux
+ [[ Linux == \L\i\n\u\x ]]
++ nproc
+ PARALLEL=10
+ pushd /ray/src/common/thirdparty/
/ray/src/common/thirdparty /ray/python
+ bash build-redis.sh
--2018-02-23 00:06:17--  https://github.com/antirez/redis/archive/4.0-rc2.tar.gz
Resolving github.com... 192.30.255.113, 192.30.255.112
Connecting to github.com|192.30.255.113|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error exit delayed from previous errors
Traceback (most recent call last):
  File "setup.py", line 125, in <module>
    license="Apache 2.0")
  File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python/cp27-cp27mu/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/python/cp27-cp27mu/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/python/cp27-cp27mu/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 204, in run
    self.run_command('build')
  File "/opt/python/cp27-cp27mu/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/python/cp27-cp27mu/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/python/cp27-cp27mu/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/opt/python/cp27-cp27mu/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/python/cp27-cp27mu/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 54, in run
    subprocess.check_call(["../build.sh", sys.executable])
  File "/opt/python/cp27-cp27mu/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../build.sh', '/opt/python/cp27-cp27mu/bin/python']' returned non-zero exit status 2
```

**Comment by robertnishihara** [comment]
See discussion in https://issues.apache.org/jira/browse/ARROW-2204 and https://github.com/pypa/manylinux/pull/159.
