### ISSUE TITLE
Huge pages crashes with object sizes >= 100MB

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1592]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: master
- **Python version**: 2.7
- **Exact command to reproduce**: python ray_ps_benchmark.py  --dim=25000000

### Describe the problem
The following script will crash if a large dim value is passed in as an arg
```
Traceback (most recent call last):
  File "plasma.pyx", line 472, in pyarrow.plasma.PlasmaClient.release
  File "error.pxi", line 79, in pyarrow.lib.check_status
pyarrow.libOK
.ArrowIOError: Error during munmap
Exception pyarrow.lib.ArrowIOError: ArrowIOError('Error during munmap',) in 'pyarrow.plasma.PlasmaBuffer.__dealloc__' ignored
```

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import argparse
import numpy as np
import ray

parser = argparse.ArgumentParser(description="Run the synchronous parameter "
                                             "server example.")
parser.add_argument("--dim", default=25*1000*1000, type=int,
                    help="The number of parameters.")
args = parser.parse_args()

class CNN(object):
    def __init__(self, dim):
        self.dim = dim
        self.grads = np.ones(self.dim, dtype=np.float32)
        
    def get_gradients(self, params):
        return self.grads

@ray.remote
class Worker(object):
    def __init__(self, dim):
        self.net = CNN(dim)

    def compute_gradient(self, params):
        return self.net.get_gradients(params)

def main():
  # initial parameter value
  params = np.zeros(args.dim, dtype=np.float32)

  ray.init(huge_pages=True, plasma_directory="/mnt/hugepages")
  worker = Worker.remote(args.dim)

  net = CNN(args.dim)

  grads = worker.compute_gradient.remote(params)
  ray.wait([grads])


if __name__ == "__main__":
  main()
```

### Source code / logs
python ray_ps_benchmark.py --dim=2500  # OK
python ray_ps_benchmark.py --dim=25000000  # PyArrow error

**Comment by ericl** [comment]
@atum

**Comment by ericl** [comment]
Actually, it also seems to crash with smaller objects, but takes longer (run it in a loop).

**Comment by pcmoritz** [comment]
The errno is:
```
EINVAL      22  /* Invalid argument */
```

**Comment by pcmoritz** [comment]
Still haven't figures this one out, but I made sure that the address and size we are passing into munmap is the same as the one we are passing into mmap. So it's very strange that we get this error code. For example

```
mmap: size = 1073741832, addr = 140012270125056
munmap: size = 1073741832, addr = 140012270125056``
