### ISSUE TITLE
[ray] System error: Broken pipe

### ISSUE THREAD

**Issue by TannedCung** [ray-project/ray#15960]
### What is the problem?

*Ray version and other system information:
Ray 1.2 and 1.3
OS: Linux (in docker container)

### Reproduction (REQUIRED)
This is my class task
```python
@ray.remote
class Task(object):
    def __init__(self):
        self.milvus = Milvus(MILVUS_HOST, MILVUS_PORT)
        self.producer = KafkaProducer(bootstrap_servers=BOOTSTRAP_SERVER,
                                    key_serializer=lambda key: str(key).encode(),
                                    value_serializer=lambda value: json.dumps(value).encode()) 

    def process(self, metadata, embedding, track_ids, face_imgs):
        ...
        
```
the main function will create a `task_dict` which is `{core_id: Task()}` and push a new Task whenever needed
```python
  t = self.task_dict.get(core_id, None)
  if t is None:
      t = Task.remote()
      self.task_dict[core_id] = t
  task_id = core_id
  core_id = (core_id+1) % num_cpus
```
and finally run process in Tasks:
```python
self.task_dict[task_id].process.remote(data, embedding, track_ids, face_imgs)
```

This is what happens (after a few days of running):
```bash
  File "/usr/local/lib/python3.7/site-packages/ray/actor.py", line 112, in remote
    return self._remote(args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/ray/actor.py", line 153, in _remote
    return invocation(args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/ray/actor.py", line 147, in invocation
    num_returns=num_returns)
  File "/usr/local/lib/python3.7/site-packages/ray/actor.py", line 147, in _actor_method_call
    list_args, name, num_returns, self._ray_actor_method_cpus)
  File "python/ray/_raylet.pyx", line 1359, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 1364, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 337, in ray._raylet.prepare_args
  File "python/ray/_raylet.pyx", line 1093, in ray._raylet.CoreWorker.put_serialized_object
  File "python/ray/_raylet.pyx", line 1010, in ray._raylet.CoreWorker._create_put_buffer
  File "python/ray/_raylet.pyx", line 159, in ray._raylet.check_status
ray.exceptions.RaySystemError: System error: Broken pipe 
```

whenever it got this error, program seem not to work anymore

- [ x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
This error means the raylet is broken usually. Can you show me logs from raylet.out/err?

**Comment by TannedCung** [comment]
@rkooo567  thank you for your quick repply, here are my logs:
- raylet.out
```
[2021-05-21 13:51:57,704 I 24 24] io_service_pool.cc:35: IOServicePool is running with 1 io_service.
[2021-05-21 13:51:57,718 I 24 24] store_runner.cc:29: Allowing the Plasma store to use up to 3.74445GB of memory.
[2021-05-21 13:51:57,718 I 24 24] store_runner.cc:42: Starting object store with directory /tmp and huge page support disabled
[2021-05-21 13:51:57,864 I 24 24] grpc_server.cc:71: ObjectManager server started, listening on port 41097.
[2021-05-21 13:51:57,871 I 24 24] node_manager.cc:230: Initializing NodeManager with ID 2e7aa2255e7e3e91b92b9b634186a1f560f76ee48828237c69395c6e
[2021-05-21 13:51:57,872 I 24 24] grpc_server.cc:71: NodeManager server started, listening on port 39241.
[2021-05-21 13:51:57,887 I 24 64] agent_manager.cc:76: Monitor agent process with pid 63, register timeout 30000ms.
[2021-05-21 13:51:57,895 I 24 24] raylet.cc:146: Raylet of id, 2e7aa2255e7e3e91b92b9b634186a1f560f76ee48828237c69395c6e started. Raylet consists of node_manager and object_manager. node_manager address: 10.244.232.115:39241 object_manager address: 10.244.232.115:41097 hostname: 10.244.232.115
[2021-05-21 13:51:57,906 I 24 24] service_based_accessor.cc:579: Received notification for node id = 2e7aa2255e7e3e91b92b9b634186a1f560f76ee48828237c69395c6e, IsAlive = 1
[2021-05-21 13:51:59,503 I 24 24] worker_pool.cc:289: Started worker process of 1 worker(s) with pid 88
[2021-05-21 13:51:59,514 I 24 24] worker_pool.cc:289: Started worker process of 1 worker(s) with pid 89
[2021-05-21 13:51:59,522 I 24 24] worker_pool.cc:289: Started worker process of 1 worker(s) with pid 90
[2021-05-21 13:51:59,524 I 24 24] worker_pool.cc:289: Started worker process of 1 worker(s) with pid 91
[2021-05-21 13:51:59,528 I 24 24] worker_pool.cc:289: Started worker process of 1 worker(s) with pid 92
[2021-05-21 13:52:04,754 I 24 54] store.cc:230: Object store current usage 8e-09 / 3.74445 GB.
[2021-05-21 13:52:07,604 I 24 24] agent_manager.cc:32: HandleRegisterAgent, ip: 10.244.232.115, port: 53862, pid: 63
[2021-05-21 13:52:08,544 W 24 24] node_manager.cc:508: Last resource report was sent 739 ms ago. There might be resource pressure on this node. If resource reports keep lagging, scheduling decisions of other nodes may become stale
[2021-05-21 14:00:10,449 W 24 24] node_manager.cc:508: Last resource report was sent 6079 ms ago. There might be resource pressure on this node. If resource reports keep lagging, scheduling decisions of other nodes may become stale
[2021-05-21 14:00:10,449 W 24 65] node_manager.cc:151: Last heartbeat was sent 570 ms ago. There might be resource pressure on this node. If heartbeat keeps lagging, this node can be marked as dead mistakenly.
[2021-05-21 14:06:55,386 W 24 65] node_manager.cc:151: Last heartbeat was sent 411871 ms ago. There might be resource pressure on this node. If heartbeat keeps lagging, this node can be marked as dead mistakenly.
[2021-05-21 14:06:55,488 C 24 24] node_manager.cc:164: This node has beem marked as dead.
[2021-05-21 14:06:55,489 E 24 24] logging.cc:435: *** Aborted at 1621580815 (unix time) try "date -d @1621580815" if you are using GNU date ***
[2021-05-21 14:06:55,571 E 24 24] logging.cc:435: PC: @                0x0 (unknown)
[2021-05-21 14:06:55,787 E 24 24] logging.cc:435: *** SIGABRT (@0x18) received by PID 24 (TID 0x7f3712d11800) from PID 24; stack trace: ***
[2021-05-21 14:06:55,998 E 24 24] logging.cc:435:     @     0x557cf0f98aaf google::(anonymous namespace)::FailureSignalHandler()
[2021-05-21 14:06:56,000 E 24 24] logging.cc:435:     @     0x7f3713214730 (unknown)
[2021-05-21 14:06:56,063 E 24 24] logging.cc:435:     @     0x7f3712d4d7bb gsignal
[2021-05-21 14:06:56,067 E 24 24] logging.cc:435:     @     0x7f3712d38535 abort
[2021-05-21 14:06:56,181 E 24 24] logging.cc:435:     @     0x557cf0f84de5 ray::SpdLogMessage::Flush()
[2021-05-21 14:06:56,187 E 24 24] logging.cc:435:     @     0x557cf0f84e1d ray::RayLog::~RayLog()
[2021-05-21 14:06:56,218 E 24 24] logging.cc:435:     @     0x557cf0bc6480 _ZNSt17_Function_handlerIFvN3ray6StatusEEZNS0_6raylet15HeartbeatSender9HeartbeatEvEUlS1_E_E9_M_invokeERKSt9_Any_dataOS1_
[2021-05-21 14:06:56,227 E 24 24] logging.cc:435:     @     0x557cf0cb4f94 _ZNSt17_Function_handlerIFvRKN3ray6StatusERKNS0_3rpc20ReportHeartbeatReplyEEZNS0_3gcs28ServiceBasedNodeInfoAccessor20AsyncReportHeartbeatERKSt10shared_ptrINS4_18HeartbeatTableDataEERKSt8functionIFvS1_EEEUlS3_S7_E_E9_M_invokeERKSt9_Any_dataS3_S7_
[2021-05-21 14:06:56,274 E 24 24] logging.cc:435:     @     0x557cf0cb5091 _ZNSt17_Function_handlerIFvRKN3ray6StatusERKNS0_3rpc20ReportHeartbeatReplyEEZNS4_12GcsRpcClient15ReportHeartbeatERKNS4_22ReportHeartbeatRequestERKSt8functionIS8_EEUlS3_S7_E_E9_M_invokeERKSt9_Any_dataS3_S7_
[2021-05-21 14:06:56,277 E 24 24] logging.cc:435:     @     0x557cf0cbaeaf ray::rpc::ClientCallImpl<>::OnReplyReceived()
[2021-05-21 14:06:56,278 E 24 24] logging.cc:435:     @     0x557cf0b9c09b _ZNSt17_Function_handlerIFvvEZN3ray3rpc17ClientCallManager29PollEventsFromCompletionQueueEiEUlvE_E9_M_invokeERKSt9_Any_data
[2021-05-21 14:06:56,298 E 24 24] logging.cc:435:     @     0x557cf0f3a8c8 boost::asio::detail::completion_handler<>::do_complete()
[2021-05-21 14:06:56,310 E 24 24] logging.cc:435:     @     0x557cf13163c1 boost::asio::detail::scheduler::do_run_one()
[2021-05-21 14:06:56,325 E 24 24] logging.cc:435:     @     0x557cf13164f1 boost::asio::detail::scheduler::run()
[2021-05-21 14:06:56,328 E 24 24] logging.cc:435:     @     0x557cf13186f0 boost::asio::io_context::run()
[2021-05-21 14:06:56,335 E 24 24] logging.cc:435:     @     0x557cf0b049b0 main
[2021-05-21 14:06:56,336 E 24 24] logging.cc:435:     @     0x7f3712d3a09b __libc_start_main
[2021-05-21 14:06:56,339 E 24 24] logging.cc:435:     @     0x557cf0b17405 (unknown)
```
- monitor.log
```
2021-05-21 13:52:04,206	INFO monitor.py:361 -- Starting monitor using ray installation: /usr/local/lib/python3.7/site-packages/ray/__init__.py
2021-05-21 13:52:04,207	INFO monitor.py:362 -- Ray version: 1.3.0
2021-05-21 13:52:04,207	INFO monitor.py:363 -- Ray commit: 9f45548488c4fa288f3cecb556801f97958eae8b
2021-05-21 13:52:04,207	INFO monitor.py:364 -- Monitor started with command: ['/usr/local/lib/python3.7/site-packages/ray/_private/monitor.py', '--logs-dir=/tmp/ray/session_2021-05-21_13-51-55_546302_1/logs', '--redis-address=10.244.232.115:6379', '--logging-rotate-bytes=536870912', '--logging-rotate-backup-count=5', '--redis-password=5241590000000000']
2021-05-21 13:52:04,554	INFO monitor.py:122 -- Monitor: Started
2021-05-21 14:06:55,505	ERROR monitor.py:253 -- Error in monitor loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ray/_private/monitor.py", line 284, in run
    self._run()
  File "/usr/local/lib/python3.7/site-packages/ray/_private/monitor.py", line 175, in _run
    self.update_load_metrics()
  File "/usr/local/lib/python3.7/site-packages/ray/_private/monitor.py", line 140, in update_load_metrics
    request, timeout=4)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1621580457.826859743","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
>
```
- redis.out
```
11:C 21 May 2021 13:51:55.641 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
11:C 21 May 2021 13:51:55.641 # Redis version=6.0.10, bits=64, commit=00000000, modified=0, pid=11, just started
11:C 21 May 2021 13:51:55.641 # Configuration loaded
11:M 21 May 2021 13:51:55.646 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
11:M 21 May 2021 13:51:55.646 # Server initialized
11:signal-handler (1621580956) Received SIGTERM scheduling shutdown...
11:M 21 May 2021 14:09:16.395 # User requested shutdown...
11:M 21 May 2021 14:09:16.395 # Redis is now ready to exit, bye bye...
```

**Comment by rkooo567** [comment]
```
[2021-05-21 14:06:55,386 W 24 65] node_manager.cc:151: Last heartbeat was sent 411871 ms ago. There might be resource pressure on this node. If heartbeat keeps lagging, this node can be marked as dead mistakenly.
```

This seems to be the issue. Do you see the same logs from 1.3? If so, we might need the full repro script to debug the issue.

**Comment by TannedCung** [comment]
These logs actually comes from ray 1.3.0. I cannot provide the full repo but will try to have an short repro script soon. i think i should mention that on a i7 CPU it survived 3 days continuously without any problems, but the thing happens when i run on a xeon x5 v3. i wonder if CPU could be the problem???

**Comment by kouhinn** [comment]
+1 Same problem on  Xeon E7

**Comment by TannedCung** [comment]
Hi @kouhinn, in which scenario does this happen to you?? I'm trying to reproduce this issue with a short script but having no clue.

**Comment by rkooo567** [comment]
Will work on it if repro is available.
