### ISSUE TITLE
[tune] Cannot directly install ray/tune by requirements.txt

### ISSUE THREAD

**Issue by Eleven1Liu** [ray-project/ray#15969]
### What is the problem?
I cannot pip install ray/tune directly by requirements.txt. Is there any suggestion? or we should always re-run `pip install ray[tune]`.
Thanks!

#### requirements.txt
```
ray[tune]
```
#### Command
```
pip install -r requirement.txt
```
#### Error
```
Traceback (most recent call last):
  File "search_params.py", line 9, in <module>
    from ray import tune
  File "/home/eleven/test/LibMultiLabel/venv/lib/python3.6/site-packages/ray/tune/__init__.py", line 2, in <module>
    from ray.tune.tune import run_experiments, run
  File "/home/eleven/test/LibMultiLabel/venv/lib/python3.6/site-packages/ray/tune/tune.py", line 17, in <module>
    from ray.tune.progress_reporter import CLIReporter, JupyterNotebookReporter, \
  File "/home/eleven/test/LibMultiLabel/venv/lib/python3.6/site-packages/ray/tune/progress_reporter.py", line 28, in <module>
    raise ImportError("ray.tune in ray > 0.7.5 requires 'tabulate'. "
ImportError: ray.tune in ray > 0.7.5 requires 'tabulate'. Please re-run 'pip install ray[tune]' or 'pip install ray[rllib]'.
```

**Comment by krfricke** [comment]
I could not reproduce this issue in a fresh environment.

Can you try `pip install -Ur requirements.txt` to make sure all packages are updated?

Are you running this in a fresh environment or do you install on top of existing packages?

**Comment by Eleven1Liu** [comment]
Hi @krfricke,

I started a new venv, `pip install -Ur requirements.txt` works for me.
Thanks a lot!
