### ISSUE TITLE
missing dependencies in default worker in runtime envs

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#16008]
getting this when running the summit demo:
```
(pid=2728) 2021-05-22 19:42:59,898	INFO main.py:887 -- Waiting until actors are ready (30 seconds passed).
(raylet, ip=172.31.76.24) Traceback (most recent call last):
(raylet, ip=172.31.76.24)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 8, in <module>
(raylet, ip=172.31.76.24)     import ray
(raylet, ip=172.31.76.24)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/__init__.py", line 72, in <module>
(raylet, ip=172.31.76.24)     import ray._raylet  # noqa: E402
(raylet, ip=172.31.76.24)   File "python/ray/_raylet.pyx", line 9, in init ray._raylet
(raylet, ip=172.31.76.24)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/asyncio/__init__.py", line 8, in <module>
(raylet, ip=172.31.76.24)     from .base_events import *
(raylet, ip=172.31.76.24) ModuleNotFoundError: No module named 'asyncio.base_events'
(raylet, ip=172.31.76.24) Traceback (most recent call last):
(raylet, ip=172.31.76.24)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 8, in <module>
(raylet, ip=172.31.76.24)     import ray
(raylet, ip=172.31.76.24)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/__init__.py", line 72, in <module>
(raylet, ip=172.31.76.24)     import ray._raylet  # noqa: E402
(raylet, ip=172.31.76.24)   File "python/ray/_raylet.pyx", line 102, in init ray._raylet
(raylet, ip=172.31.76.24) ImportError: cannot import name external_storage
```

**Comment by AmeerHajAli** [comment]
another time I run this I get stumbled into this error:
```
(raylet, ip=172.31.51.139) Traceback (most recent call last):
(raylet, ip=172.31.51.139)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 8, in <module>
(raylet, ip=172.31.51.139)     import ray
(raylet, ip=172.31.51.139)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/__init__.py", line 72, in <module>
(raylet, ip=172.31.51.139)     import ray._raylet  # noqa: E402
(raylet, ip=172.31.51.139)   File "python/ray/_raylet.pyx", line 9, in init ray._raylet
(raylet, ip=172.31.51.139)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/asyncio/__init__.py", line 42, in <module>
(raylet, ip=172.31.51.139)     from .unix_events import *  # pragma: no cover
(raylet, ip=172.31.51.139)   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
(raylet, ip=172.31.51.139)   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
(raylet, ip=172.31.51.139)   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
(raylet, ip=172.31.51.139)   File "<frozen importlib._bootstrap_external>", line 724, in exec_module
(raylet, ip=172.31.51.139)   File "<frozen importlib._bootstrap_external>", line 859, in get_code
(raylet, ip=172.31.51.139)   File "<frozen importlib._bootstrap_external>", line 916, in get_data
(raylet, ip=172.31.51.139) FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/asyncio/unix_events.py'
Failed to unpickle the remote function 'xgboost_ray.main._wrapped' with function ID 55b2c7a5effc18b8fbe7e6e081972a6fc58e0bc821e0874342e6ebdc. Traceback:
Traceback (most recent call last):
  File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/_private/function_manager.py", line 180, in fetch_and_register_remote_function
    function = pickle.loads(serialized_function)
  File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/xgboost_ray/__init__.py", line 1, in <module>
    from xgboost_ray.main import RayParams, train, predict
  File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/xgboost_ray/main.py", line 13, in <module>
    import xgboost as xgb
  File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/xgboost/__init__.py", line 9, in <module>
    from .core import DMatrix, DeviceQuantileDMatrix, Booster
  File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/xgboost/core.py", line 21, in <module>
    import scipy.sparse
  File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/scipy/__init__.py", line 130, in <module>
    from . import _distributor_init
ImportError: cannot import name '_distributor_init' from 'scipy' (/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/scipy/__init__.py)
```

**Comment by AmeerHajAli** [comment]
annother blob:
```
/Users/ameerhajali/anaconda3/lib/python3.7/site-packages/texthero/preprocessing.py:72: FutureWarning: The default value of regex will change from True to False in a future version.
  return input.str.replace(pattern, symbols)
/Users/ameerhajali/anaconda3/lib/python3.7/site-packages/texthero/preprocessing.py:131: FutureWarning: The default value of regex will change from True to False in a future version.
  return input.str.replace(rf"([{string.punctuation}])+", symbol)
(raylet) Traceback (most recent call last):
(raylet)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 8, in <module>
(raylet)     import ray
(raylet)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/__init__.py", line 72, in <module>
(raylet)     import ray._raylet  # noqa: E402
(raylet)   File "python/ray/_raylet.pyx", line 108, in init ray._raylet
(raylet)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/exceptions.py", line 6, in <module>
(raylet)     import ray.cloudpickle as pickle
(raylet)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/cloudpickle/__init__.py", line 7, in <module>
(raylet)     from ray.cloudpickle.cloudpickle_fast import CloudPickler, dumps, dump  # noqa
(raylet)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 487, in <module>
(raylet)     class CloudPickler(Pickler):
(raylet)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 514, in CloudPickler
(raylet)     import numpy.core
(raylet)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/numpy/__init__.py", line 151, in <module>
(raylet)     from . import random
(raylet)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/numpy/random/__init__.py", line 179, in <module>
(raylet)     from . import _pickle
(raylet)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/numpy/random/_pickle.py", line 1, in <module>
(raylet)     from .mtrand import RandomState
(raylet)   File "mtrand.pyx", line 1, in init numpy.random.mtrand
(raylet)   File "bit_generator.pyx", line 1, in init numpy.random.bit_generator
(raylet) ImportError: /tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/numpy/random/_common.cpython-37m-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory
```

**Comment by AmeerHajAli** [comment]
another blob:
```
Failed to unpickle the remote function 'xgboost_ray.main._wrapped' with function ID 2809a841d9ee6012ccff6b2ae67934fcb49b21675786f9a3eb81a38e. Traceback:
Traceback (most recent call last):
  File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/_private/function_manager.py", line 180, in fetch_and_register_remote_function
    function = pickle.loads(serialized_function)
  File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/xgboost_ray/__init__.py", line 1, in <module>
    from xgboost_ray.main import RayParams, train, predict
  File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/xgboost_ray/main.py", line 11, in <module>
    import pandas as pd
  File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/pandas/__init__.py", line 179, in <module>
    import pandas.testing
  File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/pandas/testing.py", line 5, in <module>
    from pandas._testing import (
  File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/pandas/_testing.py", line 3054, in <module>
    cython_table = pd.core.base.SelectionMixin._cython_table.items()
AttributeError: module 'pandas' has no attribute 'core'

```

**Comment by AmeerHajAli** [comment]
another blob:
```
(pid=2376) 2021-05-22 20:58:36,089	INFO main.py:1358 -- [RayXGBoost] Finished XGBoost training on training data with total N=1,795 in 10.53 seconds (2.53 pure XGBoost training time).
(raylet, ip=172.31.103.113) Traceback (most recent call last):
(raylet, ip=172.31.103.113)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 8, in <module>
(raylet, ip=172.31.103.113)     import ray
(raylet, ip=172.31.103.113)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/__init__.py", line 72, in <module>
(raylet, ip=172.31.103.113)     import ray._raylet  # noqa: E402
(raylet, ip=172.31.103.113)   File "python/ray/_raylet.pyx", line 108, in init ray._raylet
(raylet, ip=172.31.103.113)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/exceptions.py", line 6, in <module>
(raylet, ip=172.31.103.113)     import ray.cloudpickle as pickle
(raylet, ip=172.31.103.113)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/cloudpickle/__init__.py", line 7, in <module>
(raylet, ip=172.31.103.113)     from ray.cloudpickle.cloudpickle_fast import CloudPickler, dumps, dump  # noqa
(raylet, ip=172.31.103.113)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 487, in <module>
(raylet, ip=172.31.103.113)     class CloudPickler(Pickler):
(raylet, ip=172.31.103.113)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 514, in CloudPickler
(raylet, ip=172.31.103.113)     import numpy.core
(raylet, ip=172.31.103.113)   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
(raylet, ip=172.31.103.113)   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
(raylet, ip=172.31.103.113)   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
(raylet, ip=172.31.103.113)   File "<frozen importlib._bootstrap_external>", line 724, in exec_module
(raylet, ip=172.31.103.113)   File "<frozen importlib._bootstrap_external>", line 859, in get_code
(raylet, ip=172.31.103.113)   File "<frozen importlib._bootstrap_external>", line 916, in get_data
(raylet, ip=172.31.103.113) FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/numpy/__init__.py'
```

Everytime I run the demo I get another error.

**Comment by AmeerHajAli** [comment]
another blob:
```
(raylet, ip=172.31.1.233) bash: /tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/bin/python: No such file or directory
(pid=462) 2021-05-22 21:14:46,953	INFO main.py:887 -- Waiting until actors are ready (30 seconds passed).
(raylet, ip=172.31.55.12) Traceback (most recent call last):
(raylet, ip=172.31.55.12)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 8, in <module>
(raylet, ip=172.31.55.12)     import ray
(raylet, ip=172.31.55.12)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/__init__.py", line 81, in <module>
(raylet, ip=172.31.55.12)     from ray.state import (  # noqa: E402
(raylet, ip=172.31.55.12)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/state.py", line 769, in <module>
(raylet, ip=172.31.55.12)     @client_mode_hook
(raylet, ip=172.31.55.12)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 56, in client_mode_hook
(raylet, ip=172.31.55.12)     from ray.util.client import ray
(raylet, ip=172.31.55.12)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/util/__init__.py", line 10, in <module>
(raylet, ip=172.31.55.12)     from ray.util import rpdb as pdb
(raylet, ip=172.31.55.12)   File "/tmp/ray/session_latest/runtime_resources/conda_resource_dir_f6d80b9f576bbef16a37475bed99470d/lib/python3.7/site-packages/ray/util/rpdb.py", line 15, in <module>
(raylet, ip=172.31.55.12)     from pdb import Pdb
(raylet, ip=172.31.55.12) ModuleNotFoundError: No module named 'pdb'
(pid=462) 2021-05-22 21:14:52,877	INFO main.py:898 -- [RayXGBoost] Starting XGBoost training
```

**Comment by iycheng** [comment]
This might be related to requirement.txt not converted to list/dict for actor/task with option. Waiting for @architkulkarni pull request to fix this in OSS first.
