### ISSUE TITLE
[core] Failed to get the system config from Raylet: IOError: 14: failed to connect to all addresses

### ISSUE THREAD

**Issue by auderson** [ray-project/ray#16009]
Hi,

I'm using ray 1.3.0 and I can't connect to a remote ray server. However if I downgrade ray version to 1.2.0, it will work fine.

```
[2021-05-23 17:06:12,083 I 541046 541046] core_worker.cc:136: Constructing CoreWorkerProcess. pid: 541046
[2021-05-23 17:06:21,087 C 541046 541153] core_worker.cc:219: Failed to get the system config from Raylet: IOError: 14: failed to connect to all addresses
[2021-05-23 17:06:21,087 E 541046 541153] logging.cc:435: *** Aborted at 1621760781 (unix time) try "date -d @1621760781" if you are using GNU date ***
[2021-05-23 17:06:21,090 E 541046 541153] logging.cc:435: PC: @                0x0 (unknown)
[2021-05-23 17:06:21,091 E 541046 541153] logging.cc:435: *** SIGABRT (@0x3f000084176) received by PID 541046 (TID 0x7fd73375b700) from PID 541046; stack trace: ***
[2021-05-23 17:06:21,092 E 541046 541153] logging.cc:435:     @     0x7fd7660be20f google::(anonymous namespace)::FailureSignalHandler()
[2021-05-23 17:06:21,095 E 541046 541153] logging.cc:435:     @     0x7fd7a5ced980 (unknown)
[2021-05-23 17:06:21,098 E 541046 541153] logging.cc:435:     @     0x7fd7a5928fb7 gsignal
[2021-05-23 17:06:21,101 E 541046 541153] logging.cc:435:     @     0x7fd7a592a921 abort
[2021-05-23 17:06:21,102 E 541046 541153] logging.cc:435:     @     0x7fd7660adb05 ray::SpdLogMessage::Flush()
[2021-05-23 17:06:21,103 E 541046 541153] logging.cc:435:     @     0x7fd7660adb3d ray::RayLog::~RayLog()
[2021-05-23 17:06:21,104 E 541046 541153] logging.cc:435:     @     0x7fd765c89f89 _ZNSt17_Function_handlerIFvRKN3ray6StatusERKNS0_3rpc20GetSystemConfigReplyEEZZZNS0_17CoreWorkerProcess22InitializeSystemConfigEvENKUlvE_clEvENKUllE_clElEUlS3_S7_E_E9_M_invokeERKSt9_Any_dataS3_S7_
[2021-05-23 17:06:21,105 E 541046 541153] logging.cc:435:     @     0x7fd765d1540f ray::rpc::ClientCallImpl<>::OnReplyReceived()
[2021-05-23 17:06:21,106 E 541046 541153] logging.cc:435:     @     0x7fd765c1facb _ZNSt17_Function_handlerIFvvEZN3ray3rpc17ClientCallManager29PollEventsFromCompletionQueueEiEUlvE_E9_M_invokeERKSt9_Any_data
[2021-05-23 17:06:21,107 E 541046 541153] logging.cc:435:     @     0x7fd76605ca08 boost::asio::detail::completion_handler<>::do_complete()
[2021-05-23 17:06:21,108 E 541046 541153] logging.cc:435:     @     0x7fd7661629a1 boost::asio::detail::scheduler::do_run_one()
[2021-05-23 17:06:21,109 E 541046 541153] logging.cc:435:     @     0x7fd766162ad1 boost::asio::detail::scheduler::run()
[2021-05-23 17:06:21,110 E 541046 541153] logging.cc:435:     @     0x7fd7661645d0 boost::asio::io_context::run()
[2021-05-23 17:06:21,111 E 541046 541153] logging.cc:435:     @     0x7fd765c4e1b4 _ZZN3ray17CoreWorkerProcess22InitializeSystemConfigEvENKUlvE_clEv.isra.0
[2021-05-23 17:06:21,112 E 541046 541153] logging.cc:435:     @     0x7fd766407d10 execute_native_thread_routine
[2021-05-23 17:06:21,113 E 541046 541153] logging.cc:435:     @     0x7fd7a5ce26db start_thread
[2021-05-23 17:06:21,114 E 541046 541153] logging.cc:435:     @     0x7fd7a5a0b71f clone

```

on another machine which has already started the ray service and connected to the head node
```python
import ray
ray.init(address='auto', _redis_password='5241590000000000')
```
```
2021-05-23 17:06:12,070	INFO worker.py:640 -- Connecting to existing Ray cluster at address: ******
Process finished with exit code 134
```

**Comment by krfricke** [comment]
Can you share a bit more about your setup? Cluster type, machines, etc? Are you using docker or installing Ray on the OS directly? Are these homogeneous nodes/machines?

**Comment by ConeyLiu** [comment]
Hi @auderson , are you connect the ray cluster from the node except the head node? If that, I think you could take a try with this: https://github.com/ray-project/ray/pull/16045.

**Comment by auderson** [comment]
@krfricke @ConeyLiu 
 I'm running on ubuntu 18.04, in my conda environment. I have 2 local machines in the same network for this test. the machines are same. The problem is version 1.2.0 doesn't cause this problem.
I can't connect to the head node except from the head node.
And at the head node, ray outputs:
```python
2021-05-26 17:18:13,526	INFO worker.py:640 -- Connecting to existing Ray cluster at address: ******
Out[3]: 2021-05-26 17:18:13,570	WARNING worker.py:1089 -- The autoscaler failed with the following error:
Traceback (most recent call last):
  File "/home/auderson/miniconda3/lib/python3.8/site-packages/ray/_private/monitor.py", line 284, in run
    self._run()
  File "/home/auderson/miniconda3/lib/python3.8/site-packages/ray/_private/monitor.py", line 175, in _run
    self.update_load_metrics()
  File "/home/auderson/miniconda3/lib/python3.8/site-packages/ray/_private/monitor.py", line 139, in update_load_metrics
    response = self.gcs_node_resources_stub.GetAllResourceUsage(
  File "/home/auderson/miniconda3/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/auderson/miniconda3/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1622019047.164816092","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
>
{'node_ip_address': '****',
 'raylet_ip_address': '*****',
 'redis_address': '******',
 'object_store_address': '/tmp/ray/session_2021-05-26_16-33-10_413339_522283/sockets/plasma_store',
 'raylet_socket_name': '/tmp/ray/session_2021-05-26_16-33-10_413339_522283/sockets/raylet',
 'webui_url': '127.0.0.1:8265',
 'session_dir': '/tmp/ray/session_2021-05-26_16-33-10_413339_522283',
 'metrics_export_port': 58400,
 'node_id': 'bc7f3547eadc99fced0ed3412ebdd666e65a76ccde68c13145df31b4'}
```

**Comment by auderson** [comment]
I'll test #16045 later

**Comment by auderson** [comment]
@krfricke @ConeyLiu
#16045 this works
I just changed the codes in `services.py` manually and the error is gone.

**Comment by krfricke** [comment]
Great to hear that - I'll close this for now. Let me know if any other errors come up.

**Comment by ConeyLiu** [comment]
thanks for the feedback.

**Comment by bavaria95** [comment]
Hi! I'm having a similar problem. Trying to have a setup of two docker containers (in the same network):
- (1) is a ray server (started with `ray start --head --block`)
- (2) just vanilla container from which I'm trying to connect

Then, I'm entering container (2), starting python REPL and running:

```python
import ray
ray.init(address='192.168.0.3:6379', _redis_password='5241590000000000')  # 192.168.0.3 is IP of the container (1)
```

Which writes one line:
`2021-06-07 05:07:01,783	INFO worker.py:726 -- Connecting to existing Ray cluster at address: 172.31.0.3:6379`
and then either hangs or aborts the process. 
In case of process abort, in the logs I can see `python-core-driver-01000000ffffffffffffffffffffffffffffffffffffffffffffffff_695.log` file with:
```
[2021-06-07 05:49:28,807 I 695 695] core_worker.cc:139: Constructing CoreWorkerProcess. pid: 695
[2021-06-07 05:49:37,816 C 695 703] core_worker.cc:223: Failed to get the system config from Raylet: IOError: 14: failed to connect to all addresses
[2021-06-07 05:49:37,816 E 695 703] logging.cc:441: *** Aborted at 1623070177 (unix time) try "date -d @1623070177" if you are using GNU date ***
[2021-06-07 05:49:37,818 E 695 703] logging.cc:441: PC: @                0x0 (unknown)
[2021-06-07 05:49:37,818 E 695 703] logging.cc:441: *** SIGABRT (@0x3e8000002b7) received by PID 695 (TID 0x7fb0ba7fc700) from PID 695; stack trace: ***
[2021-06-07 05:49:37,819 E 695 703] logging.cc:441:     @     0x7fb0c965b42f google::(anonymous namespace)::FailureSignalHandler()
[2021-06-07 05:49:37,820 E 695 703] logging.cc:441:     @     0x7fb0ca51f3c0 (unknown)
[2021-06-07 05:49:37,821 E 695 703] logging.cc:441:     @     0x7fb0ca35e18b gsignal
[2021-06-07 05:49:37,822 E 695 703] logging.cc:441:     @     0x7fb0ca33d859 abort
[2021-06-07 05:49:37,825 E 695 703] logging.cc:441:     @     0x7fb0c964ab6e ray::SpdLogMessage::Flush()
[2021-06-07 05:49:37,828 E 695 703] logging.cc:441:     @     0x7fb0c964ac3d ray::RayLog::~RayLog()
[2021-06-07 05:49:37,828 E 695 703] logging.cc:441:     @     0x7fb0c9217bd9 _ZNSt17_Function_handlerIFvRKN3ray6StatusERKNS0_3rpc20GetSystemConfigReplyEEZZZNS0_17CoreWorkerProcess22InitializeSystemConfigEvENKUlvE_clEvENKUllE_clElEUlS3_S7_E_E9_M_invokeERKSt9_Any_dataS3_S7_
[2021-06-07 05:49:37,829 E 695 703] logging.cc:441:     @     0x7fb0c92a818f ray::rpc::ClientCallImpl<>::OnReplyReceived()
[2021-06-07 05:49:37,830 E 695 703] logging.cc:441:     @     0x7fb0c91a6fab _ZNSt17_Function_handlerIFvvEZN3ray3rpc17ClientCallManager29PollEventsFromCompletionQueueEiEUlvE_E9_M_invokeERKSt9_Any_data
[2021-06-07 05:49:37,832 E 695 703] logging.cc:441:     @     0x7fb0c95f68d8 boost::asio::detail::completion_handler<>::do_complete()
[2021-06-07 05:49:37,833 E 695 703] logging.cc:441:     @     0x7fb0c96f4291 boost::asio::detail::scheduler::do_run_one()
[2021-06-07 05:49:37,834 E 695 703] logging.cc:441:     @     0x7fb0c96f43c1 boost::asio::detail::scheduler::run()
[2021-06-07 05:49:37,835 E 695 703] logging.cc:441:     @     0x7fb0c96f5ec0 boost::asio::io_context::run()
[2021-06-07 05:49:37,836 E 695 703] logging.cc:441:     @     0x7fb0c91d73b4 _ZZN3ray17CoreWorkerProcess22InitializeSystemConfigEvENKUlvE_clEv.isra.0
[2021-06-07 05:49:37,837 E 695 703] logging.cc:441:     @     0x7fb0c9995100 execute_native_thread_routine
[2021-06-07 05:49:37,838 E 695 703] logging.cc:441:     @     0x7fb0ca513609 start_thread
[2021-06-07 05:49:37,839 E 695 703] logging.cc:441:     @     0x7fb0ca43a293 clone
```

Connecting from container (1) works totally fine. Ports `6379` and `8265` are exposed in (1)

I'm using the freshest docker image both on (1) and (2): `rayproject/ray:1.4.0-py38`

Besides that, I tried patching the files with a diff from https://github.com/ray-project/ray/pull/16045 but without any success.

Any ideas what can be wrong, @ConeyLiu ?

**Comment by ConeyLiu** [comment]
Hi @bavaria95, I think the problem comes from the following:
```
2021-06-07 05:07:01,783 INFO worker.py:726 -- Connecting to existing Ray cluster at address: 172.31.0.3:6379
```

I think you could  specify the node ip address with the following:
```python
ray start --head --block --node_ip_address="Your container ip"
```

```python
import ray
ray.init(address='Your container ip:6379', _redis_password='5241590000000000', _node_ip_address="Your container ip") 
```

**Comment by bavaria95** [comment]
Thanks for the prompt response, @ConeyLiu 

Seems that I copy-pasted outputs from different runs (when container IP changed).

Tried starting server with `ray start --head --node-ip-address="192.168.0.3" --block` and connecting as `ray.init(address='192.168.0.3:6379', _redis_password='5241590000000000')` - but still nothing (just writes `Aborted` and exits the process, after debug line `2021-06-07 06:55:35,881	INFO worker.py:726 -- Connecting to existing Ray cluster at address: 192.168.0.3:6379`)

**Comment by ConeyLiu** [comment]
I note that the (2) is not added into (1) cluster. So you have two choices:
1. add (2) to (1) cluster with `ray start ...`, then you could connect the (1) with `ray.init(...)`
2.  Use ray client to connected to the cluster (1).

**Comment by bavaria95** [comment]
Tried approach a):
in the container (1) started ray head:
```
ray start --node-ip-address=172.23.0.4 --dashboard-host=0.0.0.0 --head -vvv --block
Local node IP: 172.23.0.4
2021-06-08 03:33:42,089	INFO services.py:1272 -- View the Ray dashboard at http://172.23.0.4:8265
2021-06-08 03:33:42,092	WARNING services.py:1730 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=3.28gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='172.23.0.4:6379' --redis-password='5241590000000000'

  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='5241590000000000')

  If connection fails, check your firewall settings and network configuration.
...
```

in container (2) connected to ray:
```
ray start --address=172.23.0.4:6379 --block
Local node IP: 172.23.0.2
2021-06-08 03:35:10,160	WARNING services.py:1730 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=3.28gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.

--------------------
Ray runtime started.
--------------------

...
```

Inside the Ray dashboards now I can see both containers as available Nodes

Then trying to do `ray.init('172.23.0.2:6379', _redis_password='5241590000000000')` inside (2) gets:
```
2021-06-08 03:39:12,504	INFO worker.py:726 -- Connecting to existing Ray cluster at address: 172.23.0.2:6379
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/ray/anaconda3/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused`
```

which makes sense, since we don't have Redis in the container (2). And then trying with autodiscovery:
`ray.init('auto', _redis_password='5241590000000000')` produces:
```
2021-06-08 03:39:28,658	INFO worker.py:726 -- Connecting to existing Ray cluster at address: 172.23.0.4:6379
Aborted
```

and yields error file in logs:
```
[2021-06-08 03:39:28,669 I 85 85] core_worker.cc:139: Constructing CoreWorkerProcess. pid: 85
[2021-06-08 03:39:37,677 C 85 94] core_worker.cc:223: Failed to get the system config from Raylet: IOError: 14: failed to connect to all addresses
[2021-06-08 03:39:37,677 E 85 94] logging.cc:441: *** Aborted at 1623148777 (unix time) try "date -d @1623148777" if you are using GNU date ***
[2021-06-08 03:39:37,680 E 85 94] logging.cc:441: PC: @                0x0 (unknown)
[2021-06-08 03:39:37,684 E 85 94] logging.cc:441: *** SIGABRT (@0x3e800000055) received by PID 85 (TID 0x7f74daffd700) from PID 85; stack trace: ***
[2021-06-08 03:39:37,685 E 85 94] logging.cc:441:     @     0x7f74e9d7142f google::(anonymous namespace)::FailureSignalHandler()
[2021-06-08 03:39:37,686 E 85 94] logging.cc:441:     @     0x7f74eac353c0 (unknown)
[2021-06-08 03:39:37,686 E 85 94] logging.cc:441:     @     0x7f74eaa7418b gsignal
[2021-06-08 03:39:37,687 E 85 94] logging.cc:441:     @     0x7f74eaa53859 abort
[2021-06-08 03:39:37,688 E 85 94] logging.cc:441:     @     0x7f74e9d60b6e ray::SpdLogMessage::Flush()
[2021-06-08 03:39:37,690 E 85 94] logging.cc:441:     @     0x7f74e9d60c3d ray::RayLog::~RayLog()
[2021-06-08 03:39:37,690 E 85 94] logging.cc:441:     @     0x7f74e992dbd9 _ZNSt17_Function_handlerIFvRKN3ray6StatusERKNS0_3rpc20GetSystemConfigReplyEEZZZNS0_17CoreWorkerProcess22InitializeSystemConfigEvENKUlvE_clEvENKUllE_clElEUlS3_S7_E_E9_M_invokeERKSt9_Any_dataS3_S7_
[2021-06-08 03:39:37,691 E 85 94] logging.cc:441:     @     0x7f74e99be18f ray::rpc::ClientCallImpl<>::OnReplyReceived()
[2021-06-08 03:39:37,693 E 85 94] logging.cc:441:     @     0x7f74e98bcfab _ZNSt17_Function_handlerIFvvEZN3ray3rpc17ClientCallManager29PollEventsFromCompletionQueueEiEUlvE_E9_M_invokeERKSt9_Any_data
[2021-06-08 03:39:37,694 E 85 94] logging.cc:441:     @     0x7f74e9d0c8d8 boost::asio::detail::completion_handler<>::do_complete()
[2021-06-08 03:39:37,695 E 85 94] logging.cc:441:     @     0x7f74e9e0a291 boost::asio::detail::scheduler::do_run_one()
[2021-06-08 03:39:37,696 E 85 94] logging.cc:441:     @     0x7f74e9e0a3c1 boost::asio::detail::scheduler::run()
[2021-06-08 03:39:37,697 E 85 94] logging.cc:441:     @     0x7f74e9e0bec0 boost::asio::io_context::run()
[2021-06-08 03:39:37,698 E 85 94] logging.cc:441:     @     0x7f74e98ed3b4 _ZZN3ray17CoreWorkerProcess22InitializeSystemConfigEvENKUlvE_clEv.isra.0
[2021-06-08 03:39:37,699 E 85 94] logging.cc:441:     @     0x7f74ea0ab100 execute_native_thread_routine
[2021-06-08 03:39:37,700 E 85 94] logging.cc:441:     @     0x7f74eac29609 start_thread
[2021-06-08 03:39:37,701 E 85 94] logging.cc:441:     @     0x7f74eab50293 clone
```

**Comment by bavaria95** [comment]
Although tried using Ray Client. Connecting seemed to work well. Now will be testing if Ray serve would work well in this combination. Many thanks!

**Comment by MarkProjectRepo** [comment]
Are there any updates on this? I'm having the same issues as @bavaria95 , exact same log outputs. My use case is 2 vms inside a GCP VPC only using internal IPs

**Comment by bavaria95** [comment]
Made it work with Ray Client, works just as expected!

**Comment by MarkProjectRepo** [comment]
Ray serve doesn't seem to want to connect when using Ray Client; I get the following errors one after the other when I do try:

>\> serve.start()
Put failed:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mark/.local/lib/python3.6/site-packages/ray/serve/api.py", line 696, in start
    detached=detached,
  File "/home/mark/.local/lib/python3.6/site-packages/ray/actor.py", line 481, in remote
    override_environment_variables))
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/tracing/tracing_helper.py", line 367, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/home/mark/.local/lib/python3.6/site-packages/ray/actor.py", line 593, in _remote
    override_environment_variables))
  File "/home/mark/.local/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 134, in client_mode_convert_actor
    return client_actor._remote(in_args, in_kwargs, **kwargs)
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/client/common.py", line 254, in _remote
    return self.options(**option_args).remote(*args, **kwargs)
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/client/common.py", line 367, in remote
    ref_ids = ray.call_remote(self, *args, **kwargs)
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/client/api.py", line 103, in call_remote
    return self.worker.call_remote(instance, *args, **kwargs)
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/client/worker.py", line 299, in call_remote
    task = instance._prepare_client_task()
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/client/common.py", line 360, in _prepare_client_task
    task = self.remote_stub._prepare_client_task()
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/client/common.py", line 265, in _prepare_client_task
    self._ensure_ref()
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/client/common.py", line 238, in _ensure_ref
    self.actor_cls, client_ref_id=self._client_side_ref.id)
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/client/api.py", line 52, in put
    return self.worker.put(*args, **kwargs)
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/client/worker.py", line 237, in put
    out = [self._put(x, client_ref_id=client_ref_id) for x in to_put]
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/client/worker.py", line 237, in <listcomp>
    out = [self._put(x, client_ref_id=client_ref_id) for x in to_put]
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/client/worker.py", line 257, in _put
    raise cloudpickle.loads(resp.error)
TypeError: 'NoneType' object is not callable
\> serve.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mark/.local/lib/python3.6/site-packages/ray/serve/api.py", line 696, in start
    detached=detached,
  File "/home/mark/.local/lib/python3.6/site-packages/ray/actor.py", line 481, in remote
    override_environment_variables))
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/tracing/tracing_helper.py", line 367, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/home/mark/.local/lib/python3.6/site-packages/ray/actor.py", line 593, in _remote
    override_environment_variables))
  File "/home/mark/.local/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 134, in client_mode_convert_actor
    return client_actor._remote(in_args, in_kwargs, **kwargs)
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/client/common.py", line 254, in _remote
    return self.options(**option_args).remote(*args, **kwargs)
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/client/common.py", line 367, in remote
    ref_ids = ray.call_remote(self, *args, **kwargs)
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/client/api.py", line 103, in call_remote
    return self.worker.call_remote(instance, *args, **kwargs)
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/client/worker.py", line 299, in call_remote
    task = instance._prepare_client_task()
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/client/common.py", line 360, in _prepare_client_task
    task = self.remote_stub._prepare_client_task()
  File "/home/mark/.local/lib/python3.6/site-packages/ray/util/client/common.py", line 269, in _prepare_client_task
    task.payload_id = self._ref.id
AttributeError: 'InProgressSentinel' object has no attribute 'id'

Had you encountered anything similar?

**Comment by bavaria95** [comment]
@MarkProjectRepo nope, didn't have this one.
Which Ray version do you use?

I just run it with:
```
ray.client('ray-server:10001').connect()  # pay attention to the port (this one by default)
    serve.start(
        http_options={
            'host': '0.0.0.0',
            'port': 8000,
        }
    )
```

Using some nightly build (aka 2.0.0.dev0) of Ray

**Comment by sidazhou** [comment]
Not exact same problem, but maybe related. I was trying to access ray cluster from external ip, and found out by that:

```python
# didnt work
ray.init("<head_node_host>:10001")
# works
ray.init("ray://<head_node_host>:10001")
# works
ray.client("<head_node_host>:10001").connect()
```

https://docs.ray.io/en/latest/cluster/ray-client.html
