### ISSUE TITLE
[tune] raises RuntimeError about non-training futures

### ISSUE THREAD

**Issue by howardlau1999** [ray-project/ray#16013]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* Ray 1.3.0 Python 3.8 Ubuntu Server 18.04 PyTorch 1.7.1

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

I tried to run the script named `mnist.py`:

```python
import argparse
import os
import torch
import torch.optim as optim

import ray
from ray import tune
from ray.tune.schedulers import ASHAScheduler
from ray.tune.examples.mnist_pytorch import (train, test, get_data_loaders,
                                             ConvNet)

# Change these values if you want the training to run quicker or slower.
EPOCH_SIZE = 512
TEST_SIZE = 256

# Training settings
parser = argparse.ArgumentParser(description="PyTorch MNIST Example")
parser.add_argument("--use-gpu", action="store_true", default=True, help="enables CUDA training")
parser.add_argument("--ray-address", type=str, help="The Redis address of the cluster.")
parser.add_argument("--smoke-test", action="store_true", help="Finish quickly for testing")

# Below comments are for documentation purposes only.
# yapf: disable
# __trainable_example_begin__
class TrainMNIST(tune.Trainable):
  def setup(self, config):
    use_cuda = config.get("use_gpu") and torch.cuda.is_available()
    self.device = torch.device("cuda" if use_cuda else "cpu")
    self.train_loader, self.test_loader = get_data_loaders()
    self.model = ConvNet().to(self.device)
    self.optimizer = optim.SGD(
        self.model.parameters(),
        lr=config.get("lr", 0.01),
        momentum=config.get("momentum", 0.9))

  def step(self):
    train(self.model, self.optimizer, self.train_loader, device=self.device)
    acc = test(self.model, self.test_loader, self.device)
    return {"mean_accuracy": acc}

  def save_checkpoint(self, checkpoint_dir):
    checkpoint_path = os.path.join(checkpoint_dir, "model.pth")
    torch.save(self.model.state_dict(), checkpoint_path)
    return checkpoint_path

  def load_checkpoint(self, checkpoint_path):
    self.model.load_state_dict(torch.load(checkpoint_path))

  # this is currently needed to handle Cori GPU multiple interfaces
  def current_ip(self):
    import socket
    hostname = socket.getfqdn(socket.gethostname())
    self._local_ip = socket.gethostbyname(hostname)
    return self._local_ip 


if __name__ == "__main__":
  # ip_head and redis_passwords are set by ray cluster shell scripts
  print(os.environ["ip_head"], os.environ["redis_password"])
  ray.init(address=os.environ["ip_head"], _redis_password=os.environ["redis_password"])
  sched = ASHAScheduler(metric="mean_accuracy", mode="max")
  analysis = tune.run(TrainMNIST,
                      scheduler=sched,
                      stop={"mean_accuracy": 0.99,
                            "training_iteration": 100},
                      resources_per_trial={"cpu":10, "gpu": 1},
                      num_samples=128,
                      checkpoint_at_end=True,
                      config={"lr": tune.uniform(0.001, 1.0),
                              "momentum": tune.uniform(0.1, 0.9),
                             "use_gpu": True})
  print("Best config is:", analysis.get_best_config(metric="mean_accuracy", mode="max"))
```

Then I started ray on two GPU servers by the following commands:

```bash
# On the first server
ray start --head --node-ip-address=172.18.167.77 --redis-password=123 --dashboard-host=0.0.0.0
# On the second server
ray start --node-ip-address 172.18.167.72 --address 172.18.167.77:6379 --redis-password=123
```

Then, on the first server, I ran the following command to start tuning:

```bash
ip_head=172.18.167.77:6379 port=6379 redis_password=123 python mnist.py 
```
A few seconds later, a RuntimeError was raised:

```
Result for TrainMNIST_f8f19_00003:
  date: 2021-05-24_15-59-41
  done: true
  experiment_id: d6b12886023e4faba557a5eb683f9724
  hostname: amax
  iterations_since_restore: 4
  mean_accuracy: 0.0875
  node_ip: 172.18.167.77
  pid: 15999
  time_since_restore: 1.495924949645996
  time_this_iter_s: 0.2805964946746826
  time_total_s: 1.495924949645996
  timestamp: 1621843181
  timesteps_since_restore: 0
  training_iteration: 4
  trial_id: f8f19_00003
  
2021-05-24 15:59:41,683 ERROR trial_runner.py:732 -- Trial TrainMNIST_f8f19_00003: Error processing event.
Traceback (most recent call last):
  File "/home/lyh/miniconda3/envs/ray/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 716, in _process_trial
    raise RuntimeError(
RuntimeError: Trial TrainMNIST_f8f19_00003 has a non-training future scheduled but 2 results left to process. This should never happen - please file an issue at https://github.com/ray-project/ray/issues
Result for TrainMNIST_f8f19_00003:
  date: 2021-05-24_15-59-41
  done: true
  experiment_id: d6b12886023e4faba557a5eb683f9724
  experiment_tag: 3_lr=0.35202,momentum=0.6942
  hostname: amax
  iterations_since_restore: 4
  mean_accuracy: 0.0875
  node_ip: 172.18.167.77
  pid: 15999
  time_since_restore: 1.495924949645996
  time_this_iter_s: 0.2805964946746826
  time_total_s: 1.495924949645996
  timestamp: 1621843181
  timesteps_since_restore: 0
  training_iteration: 4
  trial_id: f8f19_00003
  
Traceback (most recent call last):
  File "mnist.py", line 58, in <module>
    analysis = tune.run(TrainMNIST,
  File "/home/lyh/miniconda3/envs/ray/lib/python3.8/site-packages/ray/tune/tune.py", line 520, in run
    runner.step()
  File "/home/lyh/miniconda3/envs/ray/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 525, in step
    self._process_events(timeout=timeout)  # blocking
  File "/home/lyh/miniconda3/envs/ray/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 683, in _process_events
    self._execute_action(trial, final_decision)
  File "/home/lyh/miniconda3/envs/ray/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 974, in _execute_action
    self.trial_executor.continue_training(trial)
  File "/home/lyh/miniconda3/envs/ray/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 558, in continue_training
    self._train(trial)
  File "/home/lyh/miniconda3/envs/ray/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 380, in _train
    assert trial.status == Trial.RUNNING, trial.status
AssertionError: ERROR
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by howardlau1999** [comment]
I found that if I set `checkpoint_at_end=False`, then the scripts finished with no errors. And I guessed that manually starting nodes caused this problem. 
But I don't have permission to install docker on these servers so I can't use ray cluster launcher. I don't have a NFS setup either. Any ideas on how to solve this problem?

**Comment by krfricke** [comment]
Oh, I'll look into this more closely, sometime this week

**Comment by howardlau1999** [comment]
I manually started ray and ran this script on a 2-node cluster both attached to the same NFS. The home directory is also on the same NFS and mounted on the same path. All trials terminated without error.

**Comment by howardlau1999** [comment]
@krfricke Hi, any updates on this?

**Comment by krfricke** [comment]
Ah sorry, I've been away last week. I just bumped this up on my todo list, sorry for the delay

**Comment by krfricke** [comment]
I looked into it. An immediate fix for your problems should be setting the `TUNE_RESULT_BUFFER_MAX_TIME_S` environment variable to `0.0`:

```
export TUNE_RESULT_BUFFER_MAX_TIME_S=0.0
```

I'll work on a fix and provide more context soon.

**Comment by krfricke** [comment]
I created a PR in https://github.com/ray-project/ray/pull/16504 that fixes the issue. The PR description provides some more context.

In a nutshell, the error was due to the combination of custom/early stopping and requesting a checkpoint, while still using buffered training. The PR will raise a warning instead and use non-buffered training when `checkpoint_at_end` is passed.

**Comment by howardlau1999** [comment]
Thanks very much! @krfricke
