### ISSUE TITLE
[Client] Better Error Messages

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#16059]
One important aspect to increasing adoption of Ray Client is making sure we have very good and actionable error messages. 

Currently, I'm running into obscure error messages like this from the client:
```
Got Error from data channel -- shutting down: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating responses: Unreachable code: Request type None not handled in Datapath"
	debug_error_string = "{"created":"@1621955035.576000000","description":"Error received from peer ipv6:[::1]:50051","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Exception iterating responses: Unreachable code: Request type None not handled in Datapath","grpc_status":2}"
>
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/amog/dev/ray/lib/python3.8/site-packages/ray/util/client/dataclient.py", line 90, in _data_main
    raise e
  File "/Users/amog/dev/ray/lib/python3.8/site-packages/ray/util/client/dataclient.py", line 64, in _data_main
    for response in resp_stream:
  File "/Users/amog/dev/ray/lib/python3.8/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/Users/amog/dev/ray/lib/python3.8/site-packages/grpc/_channel.py", line 706, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating responses: Unreachable code: Request type None not handled in Datapath"
	debug_error_string = "{"created":"@1621955035.576000000","description":"Error received from peer ipv6:[::1]:50051","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Exception iterating responses: Unreachable code: Request type None not handled in Datapath","grpc_status":2}"
>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/amog/dev/ray/lib/python3.8/site-packages/ray/util/client_connect.py", line 28, in connect
    return ray.connect(
  File "/Users/amog/dev/ray/lib/python3.8/site-packages/ray/util/client/__init__.py", line 72, in connect
    self.client_worker._server_init(job_config)
  File "/Users/amog/dev/ray/lib/python3.8/site-packages/ray/util/client/worker.py", line 446, in _server_init
    self.data_client.Init(init_req)
  File "/Users/amog/dev/ray/lib/python3.8/site-packages/ray/util/client/dataclient.py", line 123, in Init
    resp = self._blocking_send(datareq)
  File "/Users/amog/dev/ray/lib/python3.8/site-packages/ray/util/client/dataclient.py", line 108, in _blocking_send
    raise ConnectionError(
ConnectionError: Cannot send request due to data channel shutting down. Request: req_id: 1
init {
}
```

and this from the server:
```
ERROR:grpc._server:Exception iterating responses: Unreachable code: Request type None not handled in Datapath
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/grpc/_server.py", line 462, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "/home/ubuntu/anaconda3/envs/3.8/lib/python3.8/site-packages/ray/util/client/server/dataservicer.py", line 86, in Datapath
    raise Exception(f"Unreachable code: Request type "
Exception: Unreachable code: Request type None not handled in Datapath
```

It turns out that this was due to a mismatch in Ray versions, but I never would have guessed that from these error messages.

@ijrsvt @AmeerHajAli

**Comment by AmeerHajAli** [comment]
@ijrsvt , can you please triage this?

**Comment by richardliaw** [comment]
Relevant: https://github.com/ray-project/ray/issues/16067

**Comment by ijrsvt** [comment]
@amogkam Was there anything else in the Serve logs?

**Comment by amogkam** [comment]
@ijrsvt there was no other output from the server side.

**Comment by amogkam** [comment]
Another error message that I'm getting right now which I'm not sure how to interpret 

```
$ python test_sgd.py --use-gpu --num-workers 2
(anyscale +0.2s) Using project dir /Users/amog/dev/test_project_3/
(anyscale +7.1s) Connected to cluster-4, see: https://beta.anyscale.com/projects/prj_RxD8FKnqwF1zVNXMrjte1bLw/clusters/ses_UhJC2VZcG1Ls7wdqDP4R8nAH
(anyscale +7.1s) URL for head node of cluster: https://session-uhjc2vzcg1ls7wdqdp4r8nah.i.anyscaleuserdata.com
Got Error from data channel -- shutting down: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating responses: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "keepalive watchdog timeout"
	debug_error_string = "{"created":"@1624492907.475530859","description":"Error received from peer ipv6:[::1]:23002","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"
>"
	debug_error_string = "{"created":"@1624492907.511561000","description":"Error received from peer ipv4:54.200.19.61:8081","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception iterating responses: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "keepalive watchdog timeout"\n\tdebug_error_string = "{"created":"@1624492907.475530859","description":"Error received from peer ipv6:[::1]:23002","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"\n>","grpc_status":2}"
>
Exception in thread Thread-6:
Traceback (most recent call last):
Traceback (most recent call last):
Got Error from logger channel -- shutting down: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating responses: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "keepalive watchdog timeout"
	debug_error_string = "{"created":"@1624492907.475553871","description":"Error received from peer ipv6:[::1]:23002","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"
>"
	debug_error_string = "{"created":"@1624492907.511589000","description":"Error received from peer ipv4:54.200.19.61:8081","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception iterating responses: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "keepalive watchdog timeout"\n\tdebug_error_string = "{"created":"@1624492907.475553871","description":"Error received from peer ipv6:[::1]:23002","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"\n>","grpc_status":2}"
>
  File "test_sgd.py", line 135, in <module>
Exception in thread Thread-7:
  File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    train_example(num_workers=args.num_workers, use_gpu=args.use_gpu)
  File "test_sgd.py", line 66, in train_example
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    trainer1 = TorchTrainer(
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/sgd/torch/torch_trainer.py", line 265, in __init__
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/client/logsclient.py", line 62, in _log_main
  File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    startup_success = self._start_workers(self.max_replicas)
    raise e
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/sgd/torch/torch_trainer.py", line 329, in _start_workers
    self._target(*self._args, **self._kwargs)
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/client/logsclient.py", line 42, in _log_main
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/client/dataclient.py", line 102, in _data_main
    return self.worker_group.start_workers(num_workers)
    for record in log_stream:
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/sgd/torch/worker_group.py", line 218, in start_workers
  File "/Users/amog/dev/product/lib/python3.8/site-packages/grpc/_channel.py", line 426, in __next__
    raise e
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/client/dataclient.py", line 69, in _data_main
    self._init_dist_workers(num_workers)
    return self._next()
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/sgd/torch/worker_group.py", line 146, in _init_dist_workers
  File "/Users/amog/dev/product/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _next
    for response in resp_stream:
  File "/Users/amog/dev/product/lib/python3.8/site-packages/grpc/_channel.py", line 426, in __next__
    self.remote_workers = [
    raise self
    return self._next()
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating responses: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "keepalive watchdog timeout"
	debug_error_string = "{"created":"@1624492907.475553871","description":"Error received from peer ipv6:[::1]:23002","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"
>"
	debug_error_string = "{"created":"@1624492907.511589000","description":"Error received from peer ipv4:54.200.19.61:8081","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception iterating responses: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "keepalive watchdog timeout"\n\tdebug_error_string = "{"created":"@1624492907.475553871","description":"Error received from peer ipv6:[::1]:23002","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"\n>","grpc_status":2}"
>
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/sgd/torch/worker_group.py", line 147, in <listcomp>
  File "/Users/amog/dev/product/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _next
    RemoteRunner.remote(**{
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/actor.py", line 418, in remote
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating responses: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "keepalive watchdog timeout"
	debug_error_string = "{"created":"@1624492907.475530859","description":"Error received from peer ipv6:[::1]:23002","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"
>"
	debug_error_string = "{"created":"@1624492907.511561000","description":"Error received from peer ipv4:54.200.19.61:8081","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception iterating responses: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "keepalive watchdog timeout"\n\tdebug_error_string = "{"created":"@1624492907.475530859","description":"Error received from peer ipv6:[::1]:23002","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"\n>","grpc_status":2}"
>
    return self._remote(args=args, kwargs=kwargs)
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 367, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/actor.py", line 572, in _remote
    return client_mode_convert_actor(
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 134, in client_mode_convert_actor
    return client_actor._remote(in_args, in_kwargs, **kwargs)
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/client/common.py", line 254, in _remote
    return self.options(**option_args).remote(*args, **kwargs)
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/client/common.py", line 367, in remote
    ref_ids = ray.call_remote(self, *args, **kwargs)
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/client/api.py", line 103, in call_remote
    return self.worker.call_remote(instance, *args, **kwargs)
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/client/worker.py", line 299, in call_remote
    task = instance._prepare_client_task()
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/client/common.py", line 360, in _prepare_client_task
    task = self.remote_stub._prepare_client_task()
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/client/common.py", line 265, in _prepare_client_task
    self._ensure_ref()
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/client/common.py", line 237, in _ensure_ref
    self._ref = ray.put(
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/client/api.py", line 52, in put
    return self.worker.put(*args, **kwargs)
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/client/worker.py", line 237, in put
    out = [self._put(x, client_ref_id=client_ref_id) for x in to_put]
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/client/worker.py", line 237, in <listcomp>
    out = [self._put(x, client_ref_id=client_ref_id) for x in to_put]
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/client/worker.py", line 254, in _put
    resp = self.data_client.PutObject(req)
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/client/dataclient.py", line 172, in PutObject
    resp = self._blocking_send(datareq)
  File "/Users/amog/dev/product/lib/python3.8/site-packages/ray/util/client/dataclient.py", line 120, in _blocking_send
    raise ConnectionError(
```

**Comment by amogkam** [comment]
Another common one:

```
  File "/Users/khamlin/.pyenv/versions/3.8.8/lib/python3.8/site-packages/ray/util/client/worker.py", line 237, in <listcomp>
    out = [self._put(x, client_ref_id=client_ref_id) for x in to_put]
           │         │                │                  └ [ClientObjectRef(f868e4b01803be2affffffffffffffffffffffff0700000001000000)]
           │         │                └ None
           │         └ [ClientObjectRef(f868e4b01803be2affffffffffffffffffffffff0700000001000000)]
           └ <ray.util.client.worker.Worker object at 0x1329bdb50>
  File "/Users/khamlin/.pyenv/versions/3.8.8/lib/python3.8/site-packages/ray/util/client/worker.py", line 257, in _put
    raise cloudpickle.loads(resp.error)
          │                 └ error: "\200\005\225Y\000\000\000\000\000\000\000\214\010builtins\224\214\023ModuleNotFoundError\224\223\224\214\031No module na...
          └ <module 'ray.cloudpickle' from '/Users/khamlin/.pyenv/versions/3.8.8/lib/python3.8/site-packages/ray/cloudpickle/__init__.py'>
ModuleNotFoundError: No module named 'pyspark'
```

Is there a better error message we can show here? Perhaps more information about the object that is being unpickled?

**Comment by wuisawesome** [comment]
Many of these have been improved already, bumping the remaining parts to p2

**Comment by AmeerHajAli** [comment]
@ckw017 / @wuisawesome , do we have version mismatch check in OSS?

**Comment by wuisawesome** [comment]
yeah there's a check for ray version mismatches

**Comment by AmeerHajAli** [comment]
Then why not close the issue?

**Comment by ckw017** [comment]
Sounds reasonable.
