### ISSUE TITLE
[client] Ray client 'dataclient cannot send request due to a data channel shutting down'

### ISSUE THREAD

**Issue by PeadarOhAodha** [ray-project/ray#16067]
### What is the problem?
Running a local test of ray client, it fails when attempting to connect with the error below using the latest nightly build.

### System information 
- Mac OS
- Python 3.7
- Using latest ray build version: https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-macosx_10_13_intel.whl

### Steps to reproduce
Start ray locally:
`ray start --head --port=6379`

Execute python script (using default address): 
```
import ray.util

ray.util.connect("192.168.0.19:10001")
```

### Error Output
```
Got Error from data channel -- shutting down: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.ABORTED
	details = ""
	debug_error_string = "{"created":"@1621981055.882012000","description":"Error received from peer ipv4:192.168.0.19:10001","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"","grpc_status":10}"
>
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/anaconda3/envs/ml/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/anaconda3/envs/ml/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 102, in _data_main
    raise e
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 69, in _data_main
    for response in resp_stream:
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/grpc/_channel.py", line 803, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.ABORTED
	details = ""
	debug_error_string = "{"created":"@1621981055.882012000","description":"Error received from peer ipv4:192.168.0.19:10001","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"","grpc_status":10}"
>

Got Error from logger channel -- shutting down: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = ""
	debug_error_string = "{"created":"@1621981073.901443000","description":"Error received from peer ipv4:192.168.0.19:10001","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"","grpc_status":5}"
>
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/anaconda3/envs/ml/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/anaconda3/envs/ml/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/ray/util/client/logsclient.py", line 62, in _log_main
    raise e
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/ray/util/client/logsclient.py", line 42, in _log_main
    for record in log_stream:
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/grpc/_channel.py", line 803, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = ""
	debug_error_string = "{"created":"@1621981073.901443000","description":"Error received from peer ipv4:192.168.0.19:10001","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"","grpc_status":5}"
>

Traceback (most recent call last):
  File "ray_client_test.py", line 3, 
    ray.util.connect("192.168.0.19:10001")
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/ray/util/client_connect.py", line 36, in connect
    ignore_version=ignore_version)
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/ray/util/client/__init__.py", line 77, in connect
    self.client_worker._server_init(job_config)
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/ray/util/client/worker.py", line 455, in _server_init
    self.data_client.Init(init_req)
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 139, in Init
    resp = self._blocking_send(datareq)
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 121, in _blocking_send
    "Cannot send request due to data channel "
ConnectionError: Cannot send request due to data channel shutting down. Request: req_id: 1
init {
}
```

**Comment by ijrsvt** [comment]
Oh yikes! Thanks so much for catching this!!!

**Comment by ijrsvt** [comment]
@PeadarOhAodha Just to make sure this is the bug that I reproduced locally, could you send the logs in `/tmp/ray/session_xxxx/logs/ray_client_server.err`?
