### ISSUE TITLE
[autoscaler] No longer possible to create an Azure cluster

### ISSUE THREAD

**Issue by philippeboyd** [ray-project/ray#16091]
### What is the problem?

It is no longer possible to create an Azure cluster.

```
❯ ray up -y example-full.yaml
Cluster: default

Checking Azure environment settings
Traceback (most recent call last):
  File "/private/tmp/azure-test/venv/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/private/tmp/azure-test/venv/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1706, in main
    return cli()
  File "/private/tmp/azure-test/venv/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/private/tmp/azure-test/venv/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/private/tmp/azure-test/venv/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/private/tmp/azure-test/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/private/tmp/azure-test/venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/private/tmp/azure-test/venv/lib/python3.8/site-packages/ray/scripts/scripts.py", line 868, in up
    create_or_update_cluster(
  File "/private/tmp/azure-test/venv/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 239, in create_or_update_cluster
    config = _bootstrap_config(config, no_config_cache=no_config_cache)
  File "/private/tmp/azure-test/venv/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 315, in _bootstrap_config
    resolved_config = provider_cls.bootstrap_config(config)
  File "/private/tmp/azure-test/venv/lib/python3.8/site-packages/ray/autoscaler/_private/azure/node_provider.py", line 305, in bootstrap_config
    return bootstrap_azure(cluster_config)
  File "/private/tmp/azure-test/venv/lib/python3.8/site-packages/ray/autoscaler/_private/azure/config.py", line 21, in bootstrap_azure
    config = _configure_resource_group(config)
  File "/private/tmp/azure-test/venv/lib/python3.8/site-packages/ray/autoscaler/_private/azure/config.py", line 38, in _configure_resource_group
    subscription_id = resource_client.config.subscription_id
AttributeError: 'ResourceManagementClient' object has no attribute 'config'
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

- OSX
- Python 3.8
- Ray 1.3.0 and 2.0.0.dev0
- Azure-cli 2.24.0

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

- Download the [Azure Cluster example file](https://raw.githubusercontent.com/ray-project/ray/master/python/ray/autoscaler/azure/example-full.yaml)
- Adjust `subscription_id`
- Install deps `pip install azure-cli-core azure-mgmt-compute azure-mgmt-msi azure-mgmt-network azure-mgmt-resource ray[default]`
- Execute `ray up -y example-full.yaml`

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment]
cc @AmeerHajAli can you help with this?

**Comment by arsenvlad** [comment]
Review of history of the Azure Python SDK _resource_management_client.py to understand when breaking change took place:
* ._config September 18, 2020 https://github.com/Azure/azure-sdk-for-python/blob/27e4203818e227ba2604ff52dcf55ce2293c4c37/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/_resource_management_client.py#L69
* ._config July 12, 2020 https://github.com/Azure/azure-sdk-for-python/blob/17b78a9a8508069ff166ca992b1c8508de2e7537/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/_resource_management_client.py#L69
* .config February 3, 2020 https://github.com/Azure/azure-sdk-for-python/blob/e9fc48d30361dd5639dc9956aa0ffbeeb186019a/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/_resource_management_client.py#L59
* .config June 13, 2019 https://github.com/Azure/azure-sdk-for-python/blob/15dc31f9e835ebd48a1e5b48b0563bb9c46a5227/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/_resource_management_client.py#L59

Change Log is describing breaking changes in June 2020
* Starting with version 15.0.0b1 (2020-06-17)
* The config attribute no longer exists on a client, configuration should be passed as kwarg. 

So looks like currently ray-project is based on Azure Python SDK version 10.0.0. 

@gramhagen could you confirm?

**Comment by gramhagen** [comment]
yeah, similar to issue #13599 we need to pin azure-mgmt sdk versions to <= 14.0.0

**Comment by andrijazz** [comment]
any updates on this issue? Pinning `azure-mgmt-compute==14.0.0` doesn't seem to help

**Comment by AmeerHajAli** [comment]
@gramhagen , can you please make a PR for fixing this?

**Comment by gramhagen** [comment]
yeah, looking now. I think there are a few things that need updating, will add a pr to address them as soon as I'm done testing
