### ISSUE TITLE
UnicodeDecodeError when building Ray from source

### ISSUE THREAD

**Issue by qyccc** [ray-project/ray#1611]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **Ray installed from (source or binary)**:source
- **Ray version**:latest
- **Python version**:2.7
- **Exact command to reproduce**:python setup.py install 

### Source code / logs
<!-
-->
Traceback (most recent call last):
  File "/home/qyc/文档/ray/src/thirdparty/catapult/tracing/bin/vulcanize_trace_viewer", line 14, in <module>
    sys.exit(vulcanize_trace_viewer.Main(sys.argv))
  File "/home/qyc/文档/ray/src/thirdparty/catapult/tracing/tracing_build/vulcanize_trace_viewer.py", line 67, in Main
    extra_search_paths=args.extra_search_paths)
  File "/home/qyc/文档/ray/src/thirdparty/catapult/tracing/tracing_build/vulcanize_trace_viewer.py", line 99, in WriteTraceViewer
    module_names)
  File "/home/qyc/文档/ray/src/thirdparty/catapult/third_party/py_vulcanize/py_vulcanize/project.py", line 138, in CalcLoadSequenceForModuleNames
    name in module_names]
  File "/home/qyc/文档/ray/src/thirdparty/catapult/third_party/py_vulcanize/py_vulcanize/resource_loader.py", line 140, in LoadModule
    m.Parse()
  File "/home/qyc/文档/ray/src/thirdparty/catapult/third_party/py_vulcanize/py_vulcanize/html_module.py", line 35, in Parse
    parser_results)
  File "/home/qyc/文档/ray/src/thirdparty/catapult/third_party/py_vulcanize/py_vulcanize/html_module.py", line 130, in Parse
    tag_for_err_msg='<link rel="import" href="%s">' % href)
  File "/home/qyc/文档/ray/src/thirdparty/catapult/third_party/py_vulcanize/py_vulcanize/html_module.py", line 90, in _HRefToResource
    os.path.normpath(href[1:]))
  File "/home/qyc/文档/ray/src/thirdparty/catapult/third_party/py_vulcanize/py_vulcanize/resource_loader.py", line 70, in FindResourceGivenRelativePath
    absolute_path = os.path.join(script_path, relative_path)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 10: ordinal not in range(128)
Traceback (most recent call last):
  File "setup.py", line 125, in <module>
    license="Apache 2.0")
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 170, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 156, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 54, in run
    subprocess.check_call(["../build.sh", sys.executable])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../build.sh', '/usr/bin/python']' returned non-zero exit status 1

**Comment by robertnishihara** [comment]
Thanks for reporting this issue! I can reproduce it with

```
mkdir 文档
cd 文档
git clone https://github.com/ray-project/ray
cd ray/python
pip install -e . --verbose
```

**Comment by robertnishihara** [comment]
The above error can be worked around by adding `INCLUDE_UI=0` in front of the `pip install` and using the change in #1618. The next error I run into is

```
    + echo 'installing pyarrow'
    installing pyarrow
    + cd /home/ubuntu/文档/ray/src/thirdparty/arrow/python
    + PKG_CONFIG_PATH=/home/ubuntu/文档/ray/src/thirdparty/arrow/cpp/build/cpp-install/lib/pkgconfig
    + PYARROW_WITH_PLASMA=1
    + PYARROW_BUNDLE_ARROW_CPP=1
    + /home/ubuntu/anaconda3/bin/python setup.py build
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/filesystem.py -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/orc.py -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/types.py -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/ipc.py -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/parquet.py -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/hdfs.py -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/serialization.py -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/feather.py -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/util.py -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/compat.py -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/formatting.py -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/pandas_compat.py -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/__init__.py -> build/lib.linux-x86_64-3.6/pyarrow
    creating build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_array.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_schema.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_misc.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_serialization.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_deprecations.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/deserialize_buffer.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_plasma.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_table.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_io.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/util.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_convert_pandas.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_ipc.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/pandas_examples.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_parquet.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_hdfs.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_cython.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_types.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/__init__.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_convert_builtin.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_scalars.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/conftest.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_feather.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    copying pyarrow/tests/test_tensor.py -> build/lib.linux-x86_64-3.6/pyarrow/tests
    running egg_info
    creating pyarrow.egg-info
    writing pyarrow.egg-info/PKG-INFO
    writing dependency_links to pyarrow.egg-info/dependency_links.txt
    writing entry points to pyarrow.egg-info/entry_points.txt
    writing requirements to pyarrow.egg-info/requires.txt
    writing top-level names to pyarrow.egg-info/top_level.txt
    writing manifest file 'pyarrow.egg-info/SOURCES.txt'
    reading manifest file 'pyarrow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '#*' found anywhere in distribution
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    writing manifest file 'pyarrow.egg-info/SOURCES.txt'
    copying pyarrow/__init__.pxd -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/_config.pyx -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/_orc.pxd -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/_orc.pyx -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/_parquet.pxd -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/_parquet.pyx -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/array.pxi -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/error.pxi -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/feather.pxi -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/io-hdfs.pxi -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/io.pxi -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/ipc.pxi -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/lib.pxd -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/lib.pyx -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/memory.pxi -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/plasma.pyx -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/public-api.pxi -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/scalar.pxi -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/serialization.pxi -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/table.pxi -> build/lib.linux-x86_64-3.6/pyarrow
    copying pyarrow/types.pxi -> build/lib.linux-x86_64-3.6/pyarrow
    creating build/lib.linux-x86_64-3.6/pyarrow/includes
    copying pyarrow/includes/__init__.pxd -> build/lib.linux-x86_64-3.6/pyarrow/includes
    copying pyarrow/includes/common.pxd -> build/lib.linux-x86_64-3.6/pyarrow/includes
    copying pyarrow/includes/libarrow.pxd -> build/lib.linux-x86_64-3.6/pyarrow/includes
    copying pyarrow/tests/pyarrow_cython_example.pyx -> build/lib.linux-x86_64-3.6/pyarrow/tests
    creating build/lib.linux-x86_64-3.6/pyarrow/tests/data
    copying pyarrow/tests/data/v0.7.1.all-named-index.parquet -> build/lib.linux-x86_64-3.6/pyarrow/tests/data
    copying pyarrow/tests/data/v0.7.1.column-metadata-handling.parquet -> build/lib.linux-x86_64-3.6/pyarrow/tests/data
    copying pyarrow/tests/data/v0.7.1.parquet -> build/lib.linux-x86_64-3.6/pyarrow/tests/data
    copying pyarrow/tests/data/v0.7.1.some-named-index.parquet -> build/lib.linux-x86_64-3.6/pyarrow/tests/data
    running build_ext
    creating build/temp.linux-x86_64-3.6
    -- Runnning cmake for pyarrow
    cmake -DPYTHON_EXECUTABLE=/home/ubuntu/anaconda3/bin/python  -DPYARROW_BUILD_PLASMA=on -DPYARROW_BUNDLE_ARROW_CPP=ON -DCMAKE_BUILD_TYPE=debug /home/ubuntu/文档/ray/src/thirdparty/arrow/python
    -- The C compiler identification is GNU 5.4.0
    -- The CXX compiler identification is GNU 5.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    INFOCompiler command: /usr/bin/c++
    INFOCompiler version: Using built-in specs.
    COLLECT_GCC=/usr/bin/c++
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
    Target: x86_64-linux-gnu
    Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.9' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
    Thread model: posix
    gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)

    INFOCompiler id: GNU
    Selected compiler gcc 5.4.0
    -- Performing Test CXX_SUPPORTS_SSE3
    -- Performing Test CXX_SUPPORTS_SSE3 - Success
    -- Performing Test CXX_SUPPORTS_ALTIVEC
    -- Performing Test CXX_SUPPORTS_ALTIVEC - Failed
    Configured for DEBUG build (set with cmake -DCMAKE_BUILD_TYPE={release,debug,...})
    -- Build Type: DEBUG
    -- Build output directory: /home/ubuntu/文档/ray/src/thirdparty/arrow/python/build/temp.linux-x86_64-3.6/debug/
    -- Found PythonInterp: /home/ubuntu/anaconda3/bin/python (found version "3.6.4")
    -- Searching for Python libs in /home/ubuntu/anaconda3/lib64;/home/ubuntu/anaconda3/lib;/home/ubuntu/anaconda3/lib/python3.6/config-3.6m-x86_64-linux-gnu
    -- Looking for python3.6m
    -- Found Python lib /home/ubuntu/anaconda3/lib/libpython3.6m.so
    -- Found PythonLibs: /home/ubuntu/anaconda3/lib/libpython3.6m.so
    -- Found NumPy: version "1.14.0" /home/ubuntu/anaconda3/lib/python3.6/site-packages/numpy/core/include
    -- Searching for Python libs in /home/ubuntu/anaconda3/lib64;/home/ubuntu/anaconda3/lib;/home/ubuntu/anaconda3/lib/python3.6/config-3.6m-x86_64-linux-gnu
    -- Looking for python3.6m
    -- Found Python lib /home/ubuntu/anaconda3/lib/libpython3.6m.so
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
    -- Checking for module 'arrow'
    --   Found arrow, version 0.9.0-SNAPSHOT
    CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:67 (set):
      Syntax error in cmake code at

        /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:67

      when parsing string

Cleaning up...
```

**Comment by qyccc** [comment]
when pip install -e . --verbose ,the UnicodeDecodeError seems still exist.
```
    HEAD 目前位于 18cd334... Allow timeline scroll-to-zoom without holding ALT
    + popd
    ~/文档/文档/ray/python
    + [[ ! -f /home/qyc/文档/文档/ray/src/thirdparty/../../python/ray/core/src/catapult_files/index.html ]]
    + python2 /home/qyc/文档/文档/ray/src/thirdparty/catapult/tracing/bin/vulcanize_trace_viewer --config chrome --output /home/qyc/文档/文档/ray/src/thirdparty/../../python/ray/core/src/catapult_files/trace_viewer_full.html
    Writing output to /home/qyc/文档/文档/ray/src/thirdparty/../../python/ray/core/src/catapult_files/trace_viewer_full.html
    Traceback (most recent call last):
      File "/home/qyc/文档/文档/ray/src/thirdparty/catapult/tracing/bin/vulcanize_trace_viewer", line 14, in <module>
        sys.exit(vulcanize_trace_viewer.Main(sys.argv))
      File "/home/qyc/文档/文档/ray/src/thirdparty/catapult/tracing/tracing_build/vulcanize_trace_viewer.py", line 67, in Main
        extra_search_paths=args.extra_search_paths)
      File "/home/qyc/文档/文档/ray/src/thirdparty/catapult/tracing/tracing_build/vulcanize_trace_viewer.py", line 99, in WriteTraceViewer
        module_names)
      File "/home/qyc/文档/文档/ray/src/thirdparty/catapult/third_party/py_vulcanize/py_vulcanize/project.py", line 138, in CalcLoadSequenceForModuleNames
        name in module_names]
      File "/home/qyc/文档/文档/ray/src/thirdparty/catapult/third_party/py_vulcanize/py_vulcanize/resource_loader.py", line 140, in LoadModule
        m.Parse()
      File "/home/qyc/文档/文档/ray/src/thirdparty/catapult/third_party/py_vulcanize/py_vulcanize/html_module.py", line 35, in Parse
        parser_results)
      File "/home/qyc/文档/文档/ray/src/thirdparty/catapult/third_party/py_vulcanize/py_vulcanize/html_module.py", line 130, in Parse
        tag_for_err_msg='<link rel="import" href="%s">' % href)
      File "/home/qyc/文档/文档/ray/src/thirdparty/catapult/third_party/py_vulcanize/py_vulcanize/html_module.py", line 90, in _HRefToResource
        os.path.normpath(href[1:]))
      File "/home/qyc/文档/文档/ray/src/thirdparty/catapult/third_party/py_vulcanize/py_vulcanize/resource_loader.py", line 70, in FindResourceGivenRelativePath
        absolute_path = os.path.join(script_path, relative_path)
      File "/usr/lib/python2.7/posixpath.py", line 73, in join
        path += '/' + b
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 10: ordinal not in range(128)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/qyc/文档/文档/ray/python/setup.py", line 125, in <module>
        license="Apache 2.0")
      File "/home/qyc/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
```
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/qyc/.local/lib/python2.7/site-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/home/qyc/.local/lib/python2.7/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/qyc/文档/文档/ray/python/setup.py", line 54, in run
        subprocess.check_call(["../build.sh", sys.executable])
      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '/usr/bin/python']' returned non-zero exit status 1
Cleaning up...
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/home/qyc/\xe6\x96\x87\xe6\xa1\xa3/\xe6\x96\x87\xe6\xa1\xa3/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/qyc/文档/文档/ray/python/
Exception information:
Traceback (most recent call last):
  File "/home/qyc/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/qyc/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/qyc/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/qyc/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 845, in install
    install_options, global_options, prefix=prefix)
  File "/home/qyc/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1007, in install_editable
    show_stdout=False)
  File "/home/qyc/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/home/qyc/\xe6\x96\x87\xe6\xa1\xa3/\xe6\x96\x87\xe6\xa1\xa3/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/qyc/文档/文档/ray/python/

**Comment by robertnishihara** [comment]
Try `INCLUDE_UI=0 pip install -e . --verbose`, you should get a different error.

**Comment by qyccc** [comment]
I set the system default encoding as utf-8 at the start of the file "/usr/lib/python2.7/posixpath.py", then I reproduce the new error.

```
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```


```
INFOCompiler id: GNU
    Selected compiler gcc 5.4.0
    Configured for DEBUG build (set with cmake -DCMAKE_BUILD_TYPE={release,debug,...})
    -- Build Type: DEBUG
    -- Build output directory: /home/qyc/文档/未命名文件夹/ray/src/thirdparty/arrow/python/build/temp.linux-x86_64-2.7/debug/
    -- Searching for Python libs in /usr/lib64;/usr/lib;/usr/lib/python2.7/config-x86_64-linux-gnu
    -- Looking for python2.7
    -- Found Python lib /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so
    -- Searching for Python libs in /usr/lib64;/usr/lib;/usr/lib/python2.7/config-x86_64-linux-gnu
    -- Looking for python2.7
    -- Found Python lib /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so
    -- Checking for module 'arrow'
    --   Found arrow, version 0.9.0-SNAPSHOT
    CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:67 (set):
      Syntax error in cmake code at

        /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:67

      when parsing string

        ;/home/qyc/\�\�\�\�\�\�/\�\�\�\�\�\�\�\�\�\�\�\�\�\�\�\�\�\�/ray/src/thirdparty/arrow/cpp/build/cpp-install/lib

      Invalid escape sequence \�
    Call Stack (most recent call first):
      /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:94 (_pkgconfig_set)
      /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:121 (_pkgconfig_invoke)
      /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:400 (_pkgconfig_invoke_dyn)
      /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
      cmake_modules/FindArrow.cmake:30 (pkg_check_modules)
      CMakeLists.txt:194 (find_package)


    -- Configuring incomplete, errors occurred!
    See also "/home/qyc/文档/未命名文件夹/ray/src/thirdparty/arrow/python/build/temp.linux-x86_64-2.7/CMakeFiles/CMakeOutput.log".
    See also "/home/qyc/文档/未命名文件夹/ray/src/thirdparty/arrow/python/build/temp.linux-x86_64-2.7/CMakeFiles/CMakeError.log".
    error: command 'cmake' failed with exit status 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/qyc/文档/未命名文件夹/ray/python/setup.py", line 125, in <module>
        license="Apache 2.0")
      File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/qyc/文档/未命名文件夹/ray/python/setup.py", line 54, in run
        subprocess.check_call(["../build.sh", sys.executable])
      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '/usr/bin/python']' returned non-zero exit status 1

```

**Comment by robertnishihara** [comment]
Sounds good.
