### ISSUE TITLE
[core] Dashboard failure spamming stdout

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#16207]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 2.0dev, nightly wheels

`ray start` prints a dashboard error. Then, after running `ray.init`, the driver repeatedly spams the same message in stdout.

```
2021-06-02 23:53:44,746 ERROR dashboard.py:237 -- The dashboard on node ip-172-30-0-192 failed with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/dask-38/lib/python3.8/site-packages/ray/new_dashboard/dashboard.py", line 222, in <module>
    loop.run_until_complete(dashboard.run())
  File "/home/ubuntu/anaconda3/envs/dask-38/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ubuntu/anaconda3/envs/dask-38/lib/python3.8/site-packages/ray/new_dashboard/dashboard.py", line 118, in run
    await self.dashboard_head.run()
  File "/home/ubuntu/anaconda3/envs/dask-38/lib/python3.8/site-packages/ray/new_dashboard/head.py", line 191, in run
    modules = self._load_modules()
  File "/home/ubuntu/anaconda3/envs/dask-38/lib/python3.8/site-packages/ray/new_dashboard/head.py", line 128, in _load_modules
    head_cls_list = dashboard_utils.get_all_modules(
  File "/home/ubuntu/anaconda3/envs/dask-38/lib/python3.8/site-packages/ray/new_dashboard/utils.py", line 208, in get_all_modules
    importlib.import_module(name)
  File "/home/ubuntu/anaconda3/envs/dask-38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/envs/dask-38/lib/python3.8/site-packages/ray/new_dashboard/modules/logical_view/logical_view_head.py", line 17, in <module>
    class LogicalViewHead(dashboard_utils.DashboardHeadModule):
  File "/home/ubuntu/anaconda3/envs/dask-38/lib/python3.8/site-packages/ray/new_dashboard/modules/logical_view/logical_view_head.py", line 19, in LogicalViewHead
    async def get_actor_groups(self, req) -> aiohttp.web.Response:
  File "/home/ubuntu/anaconda3/envs/dask-38/lib/python3.8/site-packages/ray/new_dashboard/utils.py", line 117, in _wrapper
    raise Exception(f"Duplicated route path: {path}, "
Exception: Duplicated route path: /logical/actor_groups, previous one registered at /home/ubuntu/anaconda3/envs/dask-38/lib/python3.8/site-packages/ray/new_dashboard/modules/actor/actor_head
.py:152
```

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

`ray start`.

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by stephanie-wang** [comment]
@fyrestone @wuisawesome might be caused by #16170, can you look into this?

**Comment by fyrestone** [comment]
The logical_view module has been removed. Please check: https://github.com/ray-project/ray/tree/master/dashboard/modules  I think this problem is cause by unclean directory. Can you try `git clean -xdf`, then `pip install -e . --verbose`? Or just remove the directory `/home/ubuntu/anaconda3/envs/dask-38/lib/python3.8/site-packages/ray/new_dashboard/modules/logical_view` manually?

**Comment by fyrestone** [comment]
An improvement we can do,

1. Add a config for dashboard modules.
2. Load dashboard modules from config.

Pro:
  - Avoid similar problems.
  - Disable module in config instead of removing module.

Con:
  - We need to add config for every module.

**Comment by stephanie-wang** [comment]
Thanks removing the files manually worked for me!

**Comment by scottsun94** [comment]
Is the root issues resolved now? @fyrestone

**Comment by fyrestone** [comment]
> Is the root issues resolved now? @fyrestone

Yes.

**Comment by scottsun94** [comment]
Closing it then.
