### ISSUE TITLE
[tune] KeyError during BOHB for multiple, quick reports on objective function 

### ISSUE THREAD

**Issue by maxshaps** [ray-project/ray#16230]
### What is the problem?

When the objective function does multiple reports for BOHB scheduler, KeyError is raised.  The KeyError corresponds to an attempt to remove a trial from `TuneBOHB.running` (i.e., the set of running trials) which does not exist in `TuneBOHB.running`.

```
2021-06-03 21:15:16,738 ERROR trial_runner.py:748 -- Trial objective_func_ca0bb8c8: Error processing event.
Traceback (most recent call last):
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 726, in _process_trial
    decision = self._process_trial_result(trial, result)
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 793, in _process_trial_result
    self, trial, flat_result)
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/schedulers/hb_bohb.py", line 96, in on_trial_result
    trial_runner._search_alg.searcher.on_pause(trial.trial_id)
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/suggest/bohb.py", line 236, in on_pause
    self.running.remove(trial_id)
KeyError: 'ca0bb8c8'
Traceback (most recent call last):
  File "toy.py", line 31, in <module>
    mode="max"
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/tune.py", line 526, in run
    runner.step()
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 541, in step
    self._process_events(timeout=timeout)  # blocking
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 699, in _process_events
    self._execute_action(trial, final_decision)
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 992, in _execute_action
    self.trial_executor.pause_trial(trial)
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 571, in pause_trial
    super(RayTrialExecutor, self).pause_trial(trial)
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/trial_executor.py", line 121, in pause_trial
    assert trial.status == Trial.RUNNING, trial.status
AssertionError: ERROR
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

- Ray 2.0.0.dev0
- Python 3.6.8
- CentOS Linux release 7.9.2009 (Core)

### Reproduction (REQUIRED)

```
#!/usr/bin/env python
import time
import ray
from ray import tune
from ray.tune.schedulers.hb_bohb import HyperBandForBOHB
from ray.tune.suggest.bohb import TuneBOHB

def objective_func(config):
    for step in range(config["steps"]):
        time.sleep(0.1)
        score = step**2/(config["x"]**2 + 1)
        tune.report(training_iteration=step, score=score)

if __name__ == "__main__":
    config = {"steps": 50, "x": tune.uniform(0, 1)}
    bohb_hyperband = HyperBandForBOHB(time_attr="training_iteration", max_t=50)
    bohb_search = TuneBOHB()
    
    analysis = tune.run(
        objective_func,
        config=config,
        scheduler=bohb_hyperband,
        search_alg=bohb_search,
        num_samples=50,
        metric="score",
        mode="max"
    )
    print("Best hyperparameters found were: ", analysis.best_config)
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by maxshaps** [comment]
Made an initial attempt to resolve the issue by including a check in the `on_pause` and `on_unpause` methods in `ray/tune/suggest/bohb.py` to ensure that key was only removed from `TuneBOHB.running` if that key existed in the dictionary.

```
def on_pause(self, trial_id: str):
    self.paused.add(trial_id)
    if trial_id in self.running:
        self.running.remove(trial_id)

def on_unpause(self, trial_id: str):
    if trial_id in self.paused:
        self.paused.remove(trial_id)
    self.running.add(trial_id)
```

However, could not resolve subsequent errors that arose:

```
2021-06-03 21:40:36,717 ERROR trial_runner.py:748 -- Trial objective_func_4ebb2876: Error processing event.
Traceback (most recent call last):
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 726, in _process_trial
    decision = self._process_trial_result(trial, result)
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 793, in _process_trial_result
    self, trial, flat_result)
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/schedulers/hb_bohb.py", line 98, in on_trial_result
    action = self._process_bracket(trial_runner, bracket)
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/schedulers/hyperband.py", line 262, in _process_bracket
    raise TuneError(f"Trial with unexpected bad status "
ray.tune.error.TuneError: Trial with unexpected bad status encountered: TERMINATED
Traceback (most recent call last):
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 726, in _process_trial
    decision = self._process_trial_result(trial, result)
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 793, in _process_trial_result
    self, trial, flat_result)
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/schedulers/hb_bohb.py", line 98, in on_trial_result
    action = self._process_bracket(trial_runner, bracket)
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/schedulers/hyperband.py", line 262, in _process_bracket
    raise TuneError(f"Trial with unexpected bad status "
ray.tune.error.TuneError: Trial with unexpected bad status encountered: TERMINATED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "toy.py", line 31, in <module>
    mode="max"
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/tune.py", line 526, in run
    runner.step()
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 541, in step
    self._process_events(timeout=timeout)  # blocking
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 691, in _process_events
    self._process_trial(trial)
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 749, in _process_trial
    self._process_trial_failure(trial, traceback.format_exc())
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 958, in _process_trial_failure
    self._scheduler_alg.on_trial_error(self, trial)
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/schedulers/hyperband.py", line 296, in on_trial_error
    self.on_trial_remove(trial_runner, trial)
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/schedulers/hyperband.py", line 284, in on_trial_remove
    bracket.cleanup_trial(trial)
  File "/nfs/software/miniconda3/envs/my_env/lib/python3.6/site-packages/ray/tune/schedulers/hyperband.py", line 475, in cleanup_trial
    assert trial in self._live_trials
AssertionError
```

**Comment by richardliaw** [comment]
Hey @maxshaps sorry for the slow reply! @amogkam will be taking a closer look at this this week.
