### ISSUE TITLE
Autoscaler failed error

### ISSUE THREAD

**Issue by Dee718** [ray-project/ray#16339]
Hey,

I am running ray on a HPC system where I keep getting a warning message about the autoscaler failing. The program still runs fine however this error message keeps popping up and I don't know if its having an impact on the performance in any way. 

Here is the error message:
```
Traceback (most recent call last):
  File "/rds/general/user/dt718/home/anaconda3/envs/fenics_smt_3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 317, in run
    self._run()
  File "/rds/general/user/dt718/home/anaconda3/envs/fenics_smt_3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 207, in _run
    self.update_load_metrics()
  File "/rds/general/user/dt718/home/anaconda3/envs/fenics_smt_3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 170, in update_load_metrics
    request, timeout=4)
  File "/rds/general/user/dt718/home/anaconda3/envs/fenics_smt_3/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/rds/general/user/dt718/home/anaconda3/envs/fenics_smt_3/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1623184923.350097639","description":"Error received from peer ipv4:192.0.0.1:43929","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"Deadline Exceeded","grpc_status":4}"
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version: `1.4.0` (installed using pip within anaconda environment)
Python Version: `3.7.10`
OS: `Linux version 3.10.0-1127.19.1.el7.x86_64`

### Reproduction (REQUIRED)
As I am running ray within a large optimization framework it is hard for me to include a code snippet without including 100's lines of code but I will try to include pseudocode below to give a better idea of what is going on.

First ray is initialised within the job submission script:

```
#!/bin/sh
#PBS -N script_name
#PBS -l walltime=72:00:00
#PBS -l select=2:ncpus=32:mem=124gb:avx2=true
#PBS -j oe
#PBS -o out.log

module load anaconda3/personal
source activate conda_env

ln -s $PWD $PBS_O_WORKDIR/$PBS_JOBID
cd $PBS_O_WORKDIR
echo $PBS_O_WORKDIR

jobnodes=`uniq -c ${PBS_NODEFILE} | awk -F. '{print $1 }' | awk '{print $2}' | paste -s -d " "`

thishost=`uname -n | awk -F. '{print $1.}'`
thishostip=`hostname -i`
thishostNport="${thishostip}:${rayport}"
echo "Allocate Nodes = <$jobnodes>"
echo "NODE PORT = <$thishostNport>"

echo "set up ray cluster..."
for n in `echo ${jobnodes}`
do
  	if [[ ${n} == "${thishost}" ]]
        then
            	echo "first allocate node - use as headnode ..."
                module load anaconda3/personal
                source activate conda_env
                ray start --head --port=6378 --num-cpus 32 --temp-dir="local_tmp_path"
                sleep 5
        else
            	module load anaconda3/personal
                source activate conda_env
                echo "Allocating other node....."
                ray start --address='192.0.0.1:6378' --redis-password='5241590000000000' --num-cpus 32
                echo "DONE--------------------"
        fi
done

python main.py > out.txt

ray stop --force

exit
```

Within `main.py` an optimization is started where in each iteration I use ray to evaluate some functions in parallel. Due to constraints on external libraries I have to call the script containing the ray commands using `subprocess.run(["python3 script.py"])`. The `script.py` file contains the ray commands:

```
import numpy as np
import ray
ray.init(address='192.0.0.1:6378') #Connects to ray workers started in job submission file as shown above

@ray.remote
def function_to_call(args):
    #calls external functions and save output
    output = some_function(args)
    # save output

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('num_sims')  
    arguments = parser.parse_args()

    num_sims = int(arguments.num_sims) #Number of times to call function
    arg0 = 2 #dummy argument
        
    args = [(i, arg0) for i in range(num_sims)]
    ray.get([function_to_call.remote(x) for x in args])
```
 
`script.py` is called each optimisation iteration (around 200-300 times in total). The optimisation seems to run fine most of the time, however I keep getting the error message so I don't know if I am doing something wrong here. Any help would be appreciated. 

Thanks,
D

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by DmitriGekhtman** [comment]
You can add the flag `--no-monitor` to the head ray start command to skip running the autoscaler (which it looks like you're not using here.)

Note this flag is hidden (technically not a public API).

That will get rid of the error messages, but we should figure out what's causing these timeouts -- one of my colleagues observed the same error recently.

**Comment by Dee718** [comment]
Thanks, I've added the flag - I'll let you know if I get the error again.

I've also noticed that I am also getting the following error: 

```
set up ray cluster...
first allocate node - use as headnode ...
2021-06-15 09:25:02,913 INFO services.py:1274 -- View the Ray dashboard at ^[[1m^[[32mhttp://127.0.0.1:8265^[[39m^[[22m
2021-06-15 09:25:00,451 INFO scripts.py:560 -- Local node IP: 192.0.0.1
Traceback (most recent call last):
  File "/rds/general/user/dt718/home/anaconda3/envs/fenics_smt_3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/rds/general/user/dt718/home/anaconda3/envs/fenics_smt_3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1808, in main
    return cli()
  File "/rds/general/user/dt718/home/anaconda3/envs/fenics_smt_3/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/rds/general/user/dt718/home/anaconda3/envs/fenics_smt_3/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/rds/general/user/dt718/home/anaconda3/envs/fenics_smt_3/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/rds/general/user/dt718/home/anaconda3/envs/fenics_smt_3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/rds/general/user/dt718/home/anaconda3/envs/fenics_smt_3/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/rds/general/user/dt718/home/anaconda3/envs/fenics_smt_3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 585, in start
    "ray_current_cluster"), "w") as f:
PermissionError: [Errno 13] Permission denied: '/tmp/ray_current_cluster'
```


This is despite adding flag `--temp-dir` as shown below:

```
for n in `echo ${jobnodes}`
do
  	if [[ ${n} == "${thishost}" ]]
        then
            	echo "first allocate node - use as headnode ..."
                module load anaconda3/personal
                source activate fenics_smt_3
                ray start --head --port=6375 --num-cpus 32 --temp-dir="local_path/ray_tmp" --no-monitor
                sleep 5
        else
            	module load anaconda3/personal
                source activate fenics_smt_3
                echo "Allocating other node....."
                ray start --address='192.0.0.1:6375' --redis-password='5241590000000000' --num-cpus 32 --temp-dir="local_path/ray_tmp"
                echo "DONE--------------------"
        fi
done
```

Do you know if there is a flag that I am missing that can fix this issue?

**Comment by richardliaw** [comment]
This seems like a bug; user tempdir should be parametrized by the parameter given. @DmitriGekhtman is this something you can look into?

**Comment by DmitriGekhtman** [comment]
Precise problem identified above.
