### ISSUE TITLE
Error Building Ray from Source

### ISSUE THREAD

**Issue by elibol** [ray-project/ray#1645]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: Source.
- **Ray version**: 6685d4c4463b5d8b479b8840b2f283ec2c4fe1ac
- **Python version**: 3.6.1
- **Exact command to reproduce**: `python setup.py develop`

### Describe the problem

Ray fails to build from source.

### Source code / logs

```
copying pyarrow/ipc.pxi -> build/lib.linux-x86_64-3.6/pyarrow
copying pyarrow/lib.pxd -> build/lib.linux-x86_64-3.6/pyarrow
copying pyarrow/lib.pyx -> build/lib.linux-x86_64-3.6/pyarrow
copying pyarrow/memory.pxi -> build/lib.linux-x86_64-3.6/pyarrow
copying pyarrow/plasma.pyx -> build/lib.linux-x86_64-3.6/pyarrow
copying pyarrow/public-api.pxi -> build/lib.linux-x86_64-3.6/pyarrow
copying pyarrow/scalar.pxi -> build/lib.linux-x86_64-3.6/pyarrow
copying pyarrow/serialization.pxi -> build/lib.linux-x86_64-3.6/pyarrow
copying pyarrow/table.pxi -> build/lib.linux-x86_64-3.6/pyarrow
copying pyarrow/types.pxi -> build/lib.linux-x86_64-3.6/pyarrow
creating build/lib.linux-x86_64-3.6/pyarrow/includes
copying pyarrow/includes/__init__.pxd -> build/lib.linux-x86_64-3.6/pyarrow/includes
copying pyarrow/includes/common.pxd -> build/lib.linux-x86_64-3.6/pyarrow/includes
copying pyarrow/includes/libarrow.pxd -> build/lib.linux-x86_64-3.6/pyarrow/includes
copying pyarrow/tests/pyarrow_cython_example.pyx -> build/lib.linux-x86_64-3.6/pyarrow/tests
creating build/lib.linux-x86_64-3.6/pyarrow/tests/data
copying pyarrow/tests/data/v0.7.1.all-named-index.parquet -> build/lib.linux-x86_64-3.6/pyarrow/tests/data
copying pyarrow/tests/data/v0.7.1.column-metadata-handling.parquet -> build/lib.linux-x86_64-3.6/pyarrow/tests/data
copying pyarrow/tests/data/v0.7.1.parquet -> build/lib.linux-x86_64-3.6/pyarrow/tests/data
copying pyarrow/tests/data/v0.7.1.some-named-index.parquet -> build/lib.linux-x86_64-3.6/pyarrow/tests/data
running build_ext
creating build/temp.linux-x86_64-3.6
-- Runnning cmake for pyarrow
cmake -DPYTHON_EXECUTABLE=/home/elibol/anaconda3/envs/ray/bin/python  -DPYARROW_BUILD_PLASMA=on -DPYARROW_BUNDLE_ARROW_CPP=ON -DCMAKE_BUILD_TYPE=debug /home/elibol/dev/ray/thirdparty/build/arrow/python
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
INFOCompiler command: /usr/bin/c++
INFOCompiler version: Using built-in specs.
COLLECT_GCC=/usr/bin/c++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.9' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 
INFOCompiler id: GNU
Selected compiler gcc 5.4.0
-- Performing Test CXX_SUPPORTS_SSE3
-- Performing Test CXX_SUPPORTS_SSE3 - Success
-- Performing Test CXX_SUPPORTS_ALTIVEC
-- Performing Test CXX_SUPPORTS_ALTIVEC - Failed
Configured for DEBUG build (set with cmake -DCMAKE_BUILD_TYPE={release,debug,...})
-- Build Type: DEBUG
-- Build output directory: /home/elibol/dev/ray/thirdparty/build/arrow/python/build/temp.linux-x86_64-3.6/debug/
-- Found PythonInterp: /home/elibol/anaconda3/envs/ray/bin/python (found version "3.6.2") 
-- Searching for Python libs in /home/elibol/anaconda3/envs/ray/lib64;/home/elibol/anaconda3/envs/ray/lib;/home/elibol/anaconda3/envs/ray/lib/python3.6/config-3.6m-x86_64-linux-gnu
-- Looking for python3.6m
-- Found Python lib /home/elibol/anaconda3/envs/ray/lib/libpython3.6m.so
-- Found PythonLibs: /home/elibol/anaconda3/envs/ray/lib/libpython3.6m.so
-- Found NumPy: version "1.13.1" /home/elibol/anaconda3/envs/ray/lib/python3.6/site-packages/numpy/core/include
-- Searching for Python libs in /home/elibol/anaconda3/envs/ray/lib64;/home/elibol/anaconda3/envs/ray/lib;/home/elibol/anaconda3/envs/ray/lib/python3.6/config-3.6m-x86_64-linux-gnu
-- Looking for python3.6m
-- Found Python lib /home/elibol/anaconda3/envs/ray/lib/libpython3.6m.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'arrow'
--   Found arrow, version 0.9.0-SNAPSHOT
-- Arrow ABI version: 0.0.0
-- Arrow SO version: 0
-- Found the Arrow core library: /home/elibol/dev/ray/thirdparty/pkg/arrow/cpp/build/cpp-install/lib/libarrow.so
-- Found the Arrow Python library: /home/elibol/dev/ray/thirdparty/pkg/arrow/cpp/build/cpp-install/lib/libarrow_python.so
Added shared library dependency arrow: /home/elibol/dev/ray/thirdparty/pkg/arrow/cpp/build/cpp-install/lib/libarrow.so
Added shared library dependency arrow_python: /home/elibol/dev/ray/thirdparty/pkg/arrow/cpp/build/cpp-install/lib/libarrow_python.so
-- Checking for module 'plasma'
--   Found plasma, version 
-- Plasma ABI version: 0.0.0
-- Plasma SO version: 0
-- Found the Plasma core library: /home/elibol/dev/ray/thirdparty/pkg/arrow/cpp/build/cpp-install/lib/libplasma.so
-- Found Plasma executable: /home/elibol/dev/ray/thirdparty/pkg/arrow/cpp/build/cpp-install/bin/plasma_store
Added shared library dependency libplasma: /home/elibol/dev/ray/thirdparty/pkg/arrow/cpp/build/cpp-install/lib/libplasma.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/elibol/dev/ray/thirdparty/build/arrow/python/build/temp.linux-x86_64-3.6
-- Finished cmake for pyarrow
-- Running cmake --build for pyarrow
make
Scanning dependencies of target plasma_pyx
[ 16%] Compiling Cython CXX source for plasma...
Traceback (most recent call last):
  File "/home/elibol/anaconda3/envs/ray/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/elibol/anaconda3/envs/ray/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/elibol/anaconda3/envs/ray/lib/python3.6/site-packages/cython.py", line 16, in <module>
    from Cython.Compiler.Main import main
  File "/home/elibol/anaconda3/envs/ray/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 8, in <module>
    import re
  File "/home/elibol/anaconda3/envs/ray/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
CMakeFiles/plasma_pyx.dir/build.make:57: recipe for target 'CMakeFiles/plasma_pyx' failed
make[2]: *** [CMakeFiles/plasma_pyx] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/plasma_pyx.dir/all' failed
make[1]: *** [CMakeFiles/plasma_pyx.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
error: command 'make' failed with exit status 2
Traceback (most recent call last):
  File "setup.py", line 125, in <module>
    license="Apache 2.0")
  File "/home/elibol/anaconda3/envs/ray/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/elibol/anaconda3/envs/ray/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/elibol/anaconda3/envs/ray/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/elibol/anaconda3/envs/ray/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/elibol/anaconda3/envs/ray/lib/python3.6/site-packages/setuptools/command/develop.py", line 36, in run
    self.install_for_development()
  File "/home/elibol/anaconda3/envs/ray/lib/python3.6/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/home/elibol/anaconda3/envs/ray/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/elibol/anaconda3/envs/ray/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 54, in run
    subprocess.check_call(["../build.sh", sys.executable])
  File "/home/elibol/anaconda3/envs/ray/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../build.sh', '/home/elibol/anaconda3/envs/ray/bin/python']' returned non-zero exit status 1.
```

**Comment by elibol** [comment]
Workaround:
1. `pip uninstall enum34`
2. Retry building from source.

**Comment by robertnishihara** [comment]
Thanks @elibol for reporting this! Do you think this was newly introduced? E.g., by #1630? I don't quite see how, but I don't remember seeing this error before.

**Comment by adithyabsk** [comment]
Having the same issue here (coming from the blog post about pandas dataframe integration)

**Comment by robertnishihara** [comment]
@adithyabsk, can you try

`pip uninstall enum34`

Then reclone the entire Ray repository (cmake caches some files during the build process), and rebuild from source. Does that work?

**Comment by adithyabsk** [comment]
@robertnishihara That works for the install, thanks!

**Comment by richardliaw** [comment]
@elibol can we close this?

**Comment by robertnishihara** [comment]
We can though it would be good to fix the underlying problem at some point so it works even if `enum34` is installed.

**Comment by elibol** [comment]
+1 @robertnishihara, what we have right now is a workaround. Would be nice if we at least had a reason for why the install fails with `enum34`.

**Comment by elibol** [comment]
Issue persists after reverting https://github.com/ray-project/ray/pull/1630
