### ISSUE TITLE
[rllib] (upgrade to 1.4.0) Devices, IndexError: list index out of range

### ISSUE THREAD

**Issue by cola-nicolas** [ray-project/ray#16459]
### What is the problem?

After training with `tune`, I'm loading my agent. I need to do inference on GPU. But when I create the Trainer (with same config as training), I'm meeting the following error :

>Traceback (most recent call last):
  File "test.py", line 10, in <module>
    "num_gpus": 1,
  File "/home/me/miniconda3/envs/rllib/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 123, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/me/miniconda3/envs/rllib/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 548, in __init__
    super().__init__(config, logger_creator)
  File "/home/me/miniconda3/envs/rllib/lib/python3.6/site-packages/ray/tune/trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/me/miniconda3/envs/rllib/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 709, in setup
    self._init(self.config, self.env_creator)
  File "/home/me/miniconda3/envs/rllib/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 155, in _init
    num_workers=self.config["num_workers"])
  File "/home/me/miniconda3/envs/rllib/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 797, in _make_workers
    logdir=self.logdir)
  File "/home/me/miniconda3/envs/rllib/lib/python3.6/site-packages/ray/rllib/evaluation/worker_set.py", line 100, in __init__
    spaces=spaces,
  File "/home/me/miniconda3/envs/rllib/lib/python3.6/site-packages/ray/rllib/evaluation/worker_set.py", line 407, in _make_worker
    spaces=spaces,
  File "/home/me/miniconda3/envs/rllib/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 537, in __init__
    policy_dict, policy_config)
  File "/home/me/miniconda3/envs/rllib/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1196, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/home/me/miniconda3/envs/rllib/lib/python3.6/site-packages/ray/rllib/policy/policy_template.py", line 267, in __init__
    get_batch_divisibility_req=get_batch_divisibility_req,
  File "/home/me/miniconda3/envs/rllib/lib/python3.6/site-packages/ray/rllib/policy/torch_policy.py", line 155, in __init__
   **self.device = self.devices[0]**
**IndexError: list index out of range**

### Reproduction (REQUIRED)

This script :

```python
import ray
import ray.rllib.agents.ppo as ppo


if __name__ == "__main__":
    ray.init(num_cpus=8, num_gpus=1)
    ppo.PPOTrainer(config={
        "env": "CartPole-v0",
        "framework": "torch",
        "num_gpus": 1,
    })
```

runs fine in `1.3.0` but not in `1.4.0`.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by cola-nicolas** [comment]
Workaround : remove `num_gpus` from the configuration seems to fix the issue.

**Comment by cola-nicolas** [comment]
I'm meeting the exact same problem with `impala.ImpalaTrainer`, except this time removing "num_gpus" from the configuration does not solve it.

Any help would be appreciated.

**Comment by zseymour** [comment]
I am also seeing this error, which seems to prevent rollouts/inference on GPU. Any insight?

@sven1977

**Comment by sven1977** [comment]
@cola-nicolas , instead of just removing `num_gpus` from the config, could you explicitly set it to 0?

So, only when you restore the agent, make sure you create the new agent with `num_gpus=0` explicitly.
Reason: IMPALA has `num_gpus=1` by default, so just removing it from your dict won't work.

**Comment by zseymour** [comment]
@sven1977 As with the PPO example in the first post, I feel like this doesn't solve the underlying issue with doing inference on the GPU. Doesn't removing `num_gpus` from the config or setting `num_gpus=0` force all inference to occur on the CPU? Is there some other parameter missing here for GPU inference/rollout?

**Comment by zseymour** [comment]
Of note:

This does **not** work:
```python
import ray
import ray.rllib.agents.ppo as ppo


if __name__ == "__main__":
    ray.init(num_cpus=8, num_gpus=1)
    ppo.PPOTrainer(
        config={"env": "CartPole-v0", "framework": "torch", "num_gpus": 1,}
    )
```

This **does** work:
```python
import ray
from ray import tune


if __name__ == "__main__":
    ray.init(num_cpus=8, num_gpus=1)
    tune.run("PPO", config={"env": "CartPole-v0", "framework": "torch", "num_gpus": 1,})
```
