### ISSUE TITLE
Cannot build Ray from source on MacOS

### ISSUE THREAD

**Issue by audreyccheng** [ray-project/ray#16494]
### What is the problem?
I am unable to build Ray from source on my Mac.
After following the instructions here (https://docs.ray.io/en/master/development.html), I get the error below when running ```pip install -e . --verbose```.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version is commit 3fa9f2e5d628c271c06b3fd9636ce0c952f64b42
Python 3.8.10
MacOS Catalina 10.15.6

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
brew update
brew install wget

pip install cython==0.29.0 pytest

git clone https://github.com/ray-project/ray.git

ray/ci/travis/install-bazel.sh

pushd ray/dashboard/client
npm install
npm run build
popd

cd ray/python
pip install -e . --verbose
```

```
INFO: Analyzed target //:ray_pkg (82 packages loaded, 13968 targets configured).
    INFO: Found 1 target...
    INFO: Deleting stale sandbox base /private/var/tmp/_bazel_accheng/bc8709575b48fe8f9b47910b76332f7e/sandbox
    [0 / 286] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (2 actions, 0 running)
    INFO: From Executing genrule //:python/ray/streaming/_streaming.pyx_cython_translation:
    warning: python/ray/streaming/includes/transfer.pxi:63:50: Not all members given for struct 'CChannelCreationParameter'
    warning: python/ray/streaming/includes/transfer.pxi:63:50: Not all members given for struct 'CChannelCreationParameter'
    ERROR: /private/var/tmp/_bazel_accheng/bc8709575b48fe8f9b47910b76332f7e/external/com_google_protobuf/BUILD:129:11: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1): cc_wrapper.sh failed: error executing command
      (cd /private/var/tmp/_bazel_accheng/bc8709575b48fe8f9b47910b76332f7e/sandbox/darwin-sandbox/50/execroot/com_github_ray_project_ray && \
      exec env - \
        PATH=/opt/anaconda3/envs/exactly-once-new/bin:/opt/anaconda3/condabin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/accheng/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin \
        PWD=/proc/self/cwd \
      external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/strtod.d '-frandom-seed=bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/strtod.o' -iquote external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -isystem external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -g0 -g0 -DHAVE_PTHREAD -DHAVE_ZLIB -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-write-strings -Wno-deprecated-declarations -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/io/strtod.cc -o bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/strtod.o)
    Execution platform: @local_config_platform//:host

    Use --sandbox_debug to see verbose messages from the sandbox cc_wrapper.sh failed: error executing command
      (cd /private/var/tmp/_bazel_accheng/bc8709575b48fe8f9b47910b76332f7e/sandbox/darwin-sandbox/50/execroot/com_github_ray_project_ray && \
      exec env - \
        PATH=/opt/anaconda3/envs/exactly-once-new/bin:/opt/anaconda3/condabin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/accheng/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin \
        PWD=/proc/self/cwd \
      external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/strtod.d '-frandom-seed=bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/strtod.o' -iquote external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -isystem external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -g0 -g0 -DHAVE_PTHREAD -DHAVE_ZLIB -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-write-strings -Wno-deprecated-declarations -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/io/strtod.cc -o bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/strtod.o)
    Execution platform: @local_config_platform//:host

    Use --sandbox_debug to see verbose messages from the sandbox
    external/com_google_protobuf/src/google/protobuf/io/strtod.cc:77:10: error: no member named 'NoLocaleStrtod' in namespace 'google::protobuf::internal'; did you mean simply 'NoLocaleStrtod'?
      return google::protobuf::internal::NoLocaleStrtod(str, endptr);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             NoLocaleStrtod
    external/com_google_protobuf/src/google/protobuf/io/strtod.cc:76:8: note: 'NoLocaleStrtod' declared here
    double NoLocaleStrtod(const char* str, char** endptr) {
           ^
    1 error generated.
    Target //:ray_pkg failed to build
    INFO: Elapsed time: 91.095s, Critical Path: 10.68s
    INFO: 41 processes: 41 darwin-sandbox.
    FAILED: Build did NOT complete successfully
    FAILED: Build did NOT complete successfully
    /opt/anaconda3/envs/exactly-once-new/lib/python3.8/site-packages/setuptools/dist.py:692: UserWarning: Module Cython was already imported from /opt/anaconda3/envs/exactly-once-new/lib/python3.8/site-packages/Cython/__init__.py, but /Users/accheng/ray/python/.eggs/Cython-0.29.23-py3.8-macosx-10.9-x86_64.egg is being added to sys.path
      pkg_resources.working_set.add(dist, replace=True)
    /opt/anaconda3/envs/exactly-once-new/lib/python3.8/site-packages/setuptools/dist.py:692: UserWarning: Module cython was already imported from /opt/anaconda3/envs/exactly-once-new/lib/python3.8/site-packages/cython.py, but /Users/accheng/ray/python/.eggs/Cython-0.29.23-py3.8-macosx-10.9-x86_64.egg is being added to sys.path
      pkg_resources.working_set.add(dist, replace=True)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/accheng/ray/python/setup.py", line 432, in <module>
        setuptools.setup(
      File "/opt/anaconda3/envs/exactly-once-new/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/anaconda3/envs/exactly-once-new/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/anaconda3/envs/exactly-once-new/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/anaconda3/envs/exactly-once-new/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/anaconda3/envs/exactly-once-new/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/opt/anaconda3/envs/exactly-once-new/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/opt/anaconda3/envs/exactly-once-new/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/anaconda3/envs/exactly-once-new/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/accheng/ray/python/setup.py", line 425, in run
        return pip_run(self)
      File "/Users/accheng/ray/python/setup.py", line 339, in pip_run
        build(True, BUILD_JAVA)
      File "/Users/accheng/ray/python/setup.py", line 294, in build
        return bazel_invoke(
      File "/Users/accheng/ray/python/setup.py", line 180, in bazel_invoke
        result = invoker([cmd] + cmdline, *args, **kwargs)
      File "/opt/anaconda3/envs/exactly-once-new/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/Users/accheng/.bazel/bin/bazel', 'build', '--verbose_failures', '--', '//:ray_pkg']' returned non-zero exit status 1.
ERROR: Command errored out with exit status 1: /opt/anaconda3/envs/exactly-once-new/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/accheng/ray/python/setup.py'"'"'; __file__='"'"'/Users/accheng/ray/python/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/exactly-once-new/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/opt/anaconda3/envs/exactly-once-new/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/opt/anaconda3/envs/exactly-once-new/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 393, in run
    installed = install_given_reqs(
  File "/opt/anaconda3/envs/exactly-once-new/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 77, in install_given_reqs
    requirement.install(
  File "/opt/anaconda3/envs/exactly-once-new/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 777, in install
    install_editable_legacy(
  File "/opt/anaconda3/envs/exactly-once-new/lib/python3.8/site-packages/pip/_internal/operations/install/editable_legacy.py", line 44, in install_editable
    call_subprocess(
  File "/opt/anaconda3/envs/exactly-once-new/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 244, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /opt/anaconda3/envs/exactly-once-new/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/accheng/ray/python/setup.py'"'"'; __file__='"'"'/Users/accheng/ray/python/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Removed build tracker: '/private/var/folders/bx/mczsxsyj31zdlz04kvrh_2580000gp/T/pip-req-tracker-xmj43oah'
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
Is this one a M1 mac?

**Comment by audreyccheng** [comment]
No, it isn't. This is on a 2019 Macbook Pro with an Intel Core i9.

**Comment by simon-mo** [comment]
can you run `bazel clean --expunge` in the ray directory and try again?

**Comment by audreyccheng** [comment]
I've tried this but I still get the same bug.

**Comment by simon-mo** [comment]
hmm i can't repro it with a fresh clone. maybe try a new conda env?

**Comment by audreyccheng** [comment]
I've tried that as well. Do you think any existing installs could be causing this issue? The error seems to be related to the protobuf package which I've tried uninstalling and reinstalling.

**Comment by simon-mo** [comment]
bazel should pull the right version of protobuf and compiles from scratch

**Comment by richardliaw** [comment]
@audreyccheng did you resolve this?

**Comment by audreyccheng** [comment]
I still am unable to build from source on my Mac so I'm going to try using Docker.

**Comment by richardliaw** [comment]
closing issue for now since there's a couple duplicates
