### ISSUE TITLE
[tracing] Cross language call failed even when tracing is not enabled

### ISSUE THREAD

**Issue by kira-lin** [ray-project/ray#16606]
### What is the problem?

When using cross language call, loading function from local fails because wrapping in tracing changes the remote functions module to tracing_helper.

*Ray version and other system information (Python version, TensorFlow version, OS):* ray-nightly

### Reproduction (REQUIRED)
```python
import ray, os
@ray.remote
def foo():
    return 1
if __name__ == '__main__':
    ray.init(address="auto",
         job_config=ray.job_config.JobConfig(code_search_path=[os.path.dirname(__file__)]))
    print(ray.get(foo.remote()))
    ray.shutdown()
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ConeyLiu** [comment]
Just want to take a try to verify the `code_search_path` works or not and got the following errors:

```python
In [1]: import ray

In [2]: ray.__version__
Out[2]: '1.4.0'

In [3]: import os

In [4]: ray.init(job_config=ray.job_config.JobConfig(code_search_path=[os.path.dirname(".")]))
2021-06-30 16:40:39,573 INFO services.py:1274 -- View the Ray dashboard at http://127.0.0.1:8265
Out[4]:
{'node_ip_address': '10.239.158.148',
 'raylet_ip_address': '10.239.158.148',
 'redis_address': '10.239.158.148:6379',
 'object_store_address': '/tmp/ray/session_2021-06-30_16-40-38_351183_17667/sockets/plasma_store',
 'raylet_socket_name': '/tmp/ray/session_2021-06-30_16-40-38_351183_17667/sockets/raylet',
 'webui_url': '127.0.0.1:8265',
 'session_dir': '/tmp/ray/session_2021-06-30_16-40-38_351183_17667',
 'metrics_export_port': 50294,
 'node_id': '2dc51ce0a4e56b31b0f41946f07ee0cae49af9dd625039351ea42ee3'}

In [5]: @ray.remote
   ...: def f():
   ...:     return 1
   ...:

In [6]: ray.get(f.remote())
2021-06-30 16:40:51,123 WARNING worker.py:1114 -- Traceback (most recent call last):
  File "/home/lxy/miniconda3/envs/ray/lib/python3.7/site-packages/ray/_private/function_manager.py", line 267, in _load_function_from_local
    module = importlib.import_module(module_name)
  File "/home/lxy/miniconda3/envs/ray/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tracing_helper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 595, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 400, in ray._raylet.execute_task
  File "/home/lxy/miniconda3/envs/ray/lib/python3.7/site-packages/ray/_private/function_manager.py", line 236, in get_execution_info
    self._load_function_from_local(job_id, function_descriptor)
  File "/home/lxy/miniconda3/envs/ray/lib/python3.7/site-packages/ray/_private/function_manager.py", line 281, in _load_function_from_local
    raise RuntimeError(f"Function {function_descriptor} failed "
RuntimeError: Function {type=PythonFunctionDescriptor, module_name=tracing_helper, class_name=, function_name=f, function_hash=dde91ea76b251560b7b495fcc2c3d3ad605474317f4b366798ec1ceb} failed to be loaded from local code.
```
