### ISSUE TITLE
rllib torch_policy.py", line 357, in _compute_action_helper   torch.exp(logp.float()) AttributeError: 'list' object has no attribute 'float'

### ISSUE THREAD

**Issue by deepdad** [ray-project/ray#16661]
### What is the problem?

```
ray from pip install -U ray
pip install ray[default]
ubuntu20_04
python3.8



(venv) username@pool1:/home/ray/rllib$ rllib train -f tuned_examples/dreamer/dreamer-deepmind-control.yaml 
lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
/home/venv/lib/python3.8/site-packages/glfw/__init__.py:834: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)
2021-06-24 20:18:17,036	INFO services.py:1272 -- View the Ray dashboard at http://127.0.0.1:8265
== Status ==
Memory usage on this node: 1.8/7.7 GiB
Using FIFO scheduling algorithm.
Resources requested: 1.0/8 CPUs, 1.0/1 GPUs, 0.0/4.03 GiB heap, 0.0/2.01 GiB objects (0.0/1.0 accelerator_type:GTX)
Result logdir: /home/username/ray_results/dmc-dreamer
Number of trials: 3/3 (2 PENDING, 1 RUNNING)
+-------------------------------------------------------------------------+----------+-------+-----------------------------------------------------+
| Trial name                                                              | status   | loc   | env                                                 |
|-------------------------------------------------------------------------+----------+-------+-----------------------------------------------------|
| DREAMER_ray.rllib.examples.env.dm_control_suite.walker_walk_8d203_00000 | RUNNING  |       | ray.rllib.examples.env.dm_control_suite.walker_walk |
| DREAMER_ray.rllib.examples.env.dm_control_suite.cheetah_run_8d203_00001 | PENDING  |       | ray.rllib.examples.env.dm_control_suite.cheetah_run |
| DREAMER_ray.rllib.examples.env.dm_control_suite.hopper_hop_8d203_00002  | PENDING  |       | ray.rllib.examples.env.dm_control_suite.hopper_hop  |
+-------------------------------------------------------------------------+----------+-------+-----------------------------------------------------+


(pid=41169) 2021-06-24 20:18:20,900	WARNING compression.py:16 -- lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
(pid=41169) /home/venv/lib/python3.8/site-packages/glfw/__init__.py:834: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
(pid=41169)   warnings.warn(message, GLFWError)
(pid=41169) 2021-06-24 20:18:21,606	INFO trainer.py:696 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=41169) /home/venv/lib/python3.8/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
(pid=41169)   warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
2021-06-24 20:18:24,170	ERROR trial_runner.py:748 -- Trial DREAMER_ray.rllib.examples.env.dm_control_suite.walker_walk_8d203_00000: Error processing event.
Traceback (most recent call last):
  File "/home/venv/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 718, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/venv/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 688, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/venv/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/venv/lib/python3.8/site-packages/ray/worker.py", line 1496, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::Dreamer.__init__() (pid=41169, ip=132.230.151.199)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/home/venv/lib/python3.8/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 123, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 548, in __init__
    super().__init__(config, logger_creator)
  File "/home/venv/lib/python3.8/site-packages/ray/tune/trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 709, in setup
    self._init(self.config, self.env_creator)
  File "/home/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 150, in _init
    self.workers = self._make_workers(
  File "/home/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 791, in _make_workers
    return WorkerSet(
  File "/home/venv/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 92, in __init__
    self._local_worker = self._make_worker(
  File "/home/venv/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 367, in _make_worker
    worker = cls(
  File "/home/venv/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 536, in __init__
    self.policy_map, self.preprocessors = self._build_policy_map(
  File "/home/venv/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1196, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/home/venv/lib/python3.8/site-packages/ray/rllib/policy/policy_template.py", line 279, in __init__
    self._initialize_loss_from_dummy_batch(
  File "/home/venv/lib/python3.8/site-packages/ray/rllib/policy/policy.py", line 622, in _initialize_loss_from_dummy_batch
    self.compute_actions_from_input_dict(
  File "/home/venv/lib/python3.8/site-packages/ray/rllib/policy/torch_policy.py", line 261, in compute_actions_from_input_dict
    return self._compute_action_helper(input_dict, state_batches,
  File "/home/venv/lib/python3.8/site-packages/ray/rllib/utils/threading.py", line 28, in wrapper
    raise e
  File "/home/venv/lib/python3.8/site-packages/ray/rllib/utils/threading.py", line 21, in wrapper
    return func(self, *a, **k)
  File "/home/venv/lib/python3.8/site-packages/ray/rllib/policy/torch_policy.py", line 357, in _compute_action_helper
    torch.exp(logp.float())
AttributeError: 'list' object has no attribute 'float'
(pid=41169) 2021-06-24 20:18:24,164	ERROR worker.py:409 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::Dreamer.__init__() (pid=41169, ip=132.230.151.199)
(pid=41169)   File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
(pid=41169)   File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
(pid=41169)   File "/home/venv/lib/python3.8/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
(pid=41169)     return method(__ray_actor, *args, **kwargs)
(pid=41169)   File "/home/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 123, in __init__
(pid=41169)     Trainer.__init__(self, config, env, logger_creator)
(pid=41169)   File "/home/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 548, in __init__
(pid=41169)     super().__init__(config, logger_creator)
(pid=41169)   File "/home/venv/lib/python3.8/site-packages/ray/tune/trainable.py", line 98, in __init__
(pid=41169)     self.setup(copy.deepcopy(self.config))
(pid=41169)   File "/home/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 709, in setup
(pid=41169)     self._init(self.config, self.env_creator)
(pid=41169)   File "/home/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 150, in _init
(pid=41169)     self.workers = self._make_workers(
(pid=41169)   File "/home/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 791, in _make_workers
(pid=41169)     return WorkerSet(
(pid=41169)   File "/home/venv/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 92, in __init__
(pid=41169)     self._local_worker = self._make_worker(
(pid=41169)   File "/home/venv/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 367, in _make_worker
(pid=41169)     worker = cls(
(pid=41169)   File "/home/venv/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 536, in __init__
(pid=41169)     self.policy_map, self.preprocessors = self._build_policy_map(
(pid=41169)   File "/home/venv/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1196, in _build_policy_map
(pid=41169)     policy_map[name] = cls(obs_space, act_space, merged_conf)
(pid=41169)   File "/home/venv/lib/python3.8/site-packages/ray/rllib/policy/policy_template.py", line 279, in __init__
(pid=41169)     self._initialize_loss_from_dummy_batch(
(pid=41169)   File "/home/venv/lib/python3.8/site-packages/ray/rllib/policy/policy.py", line 622, in _initialize_loss_from_dummy_batch
(pid=41169)     self.compute_actions_from_input_dict(
(pid=41169)   File "/home/venv/lib/python3.8/site-packages/ray/rllib/policy/torch_policy.py", line 261, in compute_actions_from_input_dict
(pid=41169)     return self._compute_action_helper(input_dict, state_batches,
(pid=41169)   File "/home/venv/lib/python3.8/site-packages/ray/rllib/utils/threading.py", line 28, in wrapper
(pid=41169)     raise e
(pid=41169)   File "/home/venv/lib/python3.8/site-packages/ray/rllib/utils/threading.py", line 21, in wrapper
(pid=41169)     return func(self, *a, **k)
(pid=41169)   File "/home/venv/lib/python3.8/site-packages/ray/rllib/policy/torch_policy.py", line 357, in _compute_action_helper
(pid=41169)     torch.exp(logp.float())
(pid=41169) AttributeError: 'list' object has no attribute 'float'
== Status ==
Memory usage on this node: 3.8/7.7 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/8 CPUs, 0/1 GPUs, 0.0/4.03 GiB heap, 0.0/2.01 GiB objects (0.0/1.0 accelerator_type:GTX)
Result logdir: /home/username/ray_results/dmc-dreamer
Number of trials: 3/3 (1 ERROR, 2 PENDING)
+-------------------------------------------------------------------------+----------+-------+-----------------------------------------------------+
| Trial name                                                              | status   | loc   | env                                                 |
|-------------------------------------------------------------------------+----------+-------+-----------------------------------------------------|
| DREAMER_ray.rllib.examples.env.dm_control_suite.cheetah_run_8d203_00001 | PENDING  |       | ray.rllib.examples.env.dm_control_suite.cheetah_run |
| DREAMER_ray.rllib.examples.env.dm_control_suite.hopper_hop_8d203_00002  | PENDING  |       | ray.rllib.examples.env.dm_control_suite.hopper_hop  |
| DREAMER_ray.rllib.examples.env.dm_control_suite.walker_walk_8d203_00000 | ERROR    |       | ray.rllib.examples.env.dm_control_suite.walker_walk |
+-------------------------------------------------------------------------+----------+-------+-----------------------------------------------------+
Number of errored trials: 1
+-------------------------------------------------------------------------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Trial name                                                              |   # failures | error file                                                                                                                                                                                             |
|-------------------------------------------------------------------------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| DREAMER_ray.rllib.examples.env.dm_control_suite.walker_walk_8d203_00000 |            1 | /home/username/ray_results/dmc-dreamer/DREAMER_ray.rllib.examples.env.dm_control_suite.walker_walk_8d203_00000_0_env=ray.rllib.examples.env.dm_control_suite.walker_walk_2021-06-24_20-18-19/error.txt |
+-------------------------------------------------------------------------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### Reproduction (REQUIRED)
`rllib train -f rllib/tuned_examples/dreamer/dreamer-deepmind-control.yaml`

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment]
Should be fixed by https://github.com/ray-project/ray/pull/17821
