### ISSUE TITLE
[tune] Ray Tune requires torch installed when using tensorboardX==2.3

### ISSUE THREAD

**Issue by tgaddair** [ray-project/ray#16692]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* ray==1.4

`tensorboardX` is listed as a requirement when installing with `ray[tune]`. Even though `tensorboardX` is designed for PyTorch specifically, this isn't typically an issue because `tensorboardX` does not list `torch` as a requirement.

However, with the most recent 2.3 release (June 25, 2021), some critical code paths used by Ray Tune import `torch` directly. Hitting these code paths is unavoidable when using Ray Tune unless the user explicitly sets the environment variable  `TUNE_DISABLE_AUTO_CALLBACK_LOGGERS`, and Ray Tune will by default always add a `TBXLoggerCallback` here:

https://github.com/ray-project/ray/blob/master/python/ray/tune/utils/callback.py#L112

The result is that users are now required the user to have `torch` installed, even if they only wish to use TensorFlow.

Here's a stack trace illustrating the issue:

```
Traceback (most recent call last):
  File "/home/runner/work/ludwig/ludwig/tests/integration_tests/utils.py", line 435, in _subproc_wrapper
    results = fn(*args, **kwargs)
  File "/home/runner/work/ludwig/ludwig/tests/integration_tests/test_hyperopt_ray.py", line 168, in run_hyperopt_executor
    backend='local',
  File "/home/runner/work/ludwig/ludwig/ludwig/hyperopt/execution.py", line 938, in execute
    callbacks=tune_callbacks,
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ray/tune/tune.py", line 447, in run
    callbacks, sync_config, metric=metric, loggers=loggers)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ray/tune/utils/callback.py", line 112, in create_default_callbacks
    callbacks.append(TBXLoggerCallback())
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ray/tune/logger.py", line 592, in __init__
    from tensorboardX import SummaryWriter
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from .torchvis import TorchVis
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/tensorboardX/torchvis.py", line 11, in <module>
    from .writer import SummaryWriter
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/tensorboardX/writer.py", line 17, in <module>
    from .comet_utils import CometLogger
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/tensorboardX/comet_utils.py", line 13, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

It seems at a glance that there are at least a few options here:

1. Do not automatically add the TBX logger
2. Check that `torch` is available (via a try-except import or similar) before adding it
3. Raise this issue to the `tensorboardX` team and have them revert the behavior

I would probably lean towards option (2), but wanted to run this by the Ray team before submitting a PR.

cc @richardliaw 

### Reproduction (REQUIRED)
Run `tune.run` without having installed `torch` and having `tensorboardX==2.3`

**Comment by richardliaw** [comment]
2 sounds good to me!
