### ISSUE TITLE
Dask on Ray - Too many open files

### ISSUE THREAD

**Issue by tkram01** [ray-project/ray#16820]
When I run the following code with 100 workers it works fine. If I increase the worker count to 800 I get errors about running out of open file descriptors. I am using the Kubernetes operator which sets the ulimit to 65k which 800 workers should not exceed.

```
(raylet, ip=10.0.202.24) E0630 20:40:52.155332683    5284 server_chttp2.cc:49]        {"created":"@1625110852.155244150","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":872,"referenced_errors":[{"created":"@1625110852.155232460","description":"Failed to add any wildcard listeners","file":"src/core/lib/iomgr/tcp_server_posix.cc","file_line":340,"referenced_errors":[{"created":"@1625110852.155216463","description":"Unable to configure socket","fd":19,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":216,"referenced_errors":[{"created":"@1625110852.155212124","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1625110852.155231412","description":"Unable to configure socket","fd":19,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":216,"referenced_errors":[{"created":"@1625110852.155228306","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]}]}]}
(raylet, ip=10.0.202.24) Traceback (most recent call last):
(raylet, ip=10.0.202.24)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 338, in <module>
(raylet, ip=10.0.202.24)     raise e
(raylet, ip=10.0.202.24)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 323, in <module>
(raylet, ip=10.0.202.24)     raylet_name=args.raylet_name)
(raylet, ip=10.0.202.24)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 75, in __init__
(raylet, ip=10.0.202.24)     f"[::]:{self.dashboard_agent_port}")
(raylet, ip=10.0.202.24)   File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/aio/_server.py", line 84, in add_insecure_port
(raylet, ip=10.0.202.24)     address, self._server.add_insecure_port(_common.encode(address)))
(raylet, ip=10.0.202.24)   File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_common.py", line 166, in validate_port_binding_result
(raylet, ip=10.0.202.24)     raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
(raylet, ip=10.0.202.24) RuntimeError: Failed to bind to address [::]:42848; set GRPC_VERBOSITY=debug environment variable to see detailed error message.
(raylet, ip=10.0.203.112) E0630 20:40:52.972852140     138 tcp_server_posix.cc:213]    Failed accept4: Too many open files
(raylet, ip=10.0.193.62) E0630 20:40:53.827097287     123 tcp_server_posix.cc:213]    Failed accept4: Too many open files
(raylet, ip=10.0.192.176) E0630 20:40:54.163172204     126 tcp_server_posix.cc:213]    Failed accept4: Too many open files
```

```
from mhfp.encoder import MHFPEncoder
from molvs import standardize_smiles
from rdkit import Chem


def parse_smiles(row):
    try:
        return standardize_smiles(row['SMILES'])
    except:
        return None


def encode_mol(row):
    return MHFPEncoder().encode_mol(Chem.MolFromSmiles(row['smiles'])).tolist()


def main():
    import dask
    import dask.dataframe as dd
    from ray.util.dask import ray_dask_get_sync, dataframe_optimize

    with dask.config.set(scheduler=ray_dask_get_sync, dataframe_optimize=dataframe_optimize):
        df = dd.read_csv('s3://trevor-public/OTAVA_Tangible_Screening_Compounds.csv',
                         dtype={'SMILES': 'str', 'TITLE': 'str', 'code': 'str'},
                         blocksize='1 MiB').drop(['code', 'TITLE'], axis=1).persist()

        df['smiles'] = df.apply(parse_smiles, axis=1, meta=('smiles', str))
        df = df.drop('SMILES', axis=1).dropna(subset=['smiles'])
        df['fp'] = df.apply(encode_mol, axis=1, meta=('fp', object))
        df.to_json('s3://trevor-public/OTAVA/ray/', compression='gzip')


if __name__ == '__main__':
    import ray

    ray.client('127.0.0.1:10001').connect()
    main()
```

here is the Conda yaml

```
name: ray-test

channels:
  - conda-forge

dependencies:
  - python=3.7.7
  - rdkit
  - pip
  - mhfp
  - molvs
  - pip:
      - ray
      - dask[dataframe]==2021.6.0
      - s3fs==2021.6.0
```

@rkooo567

**Comment by rkooo567** [comment]
Can you also share the cluster.yaml?

**Comment by tkram01** [comment]
This is the yaml I am passing to the helm chart `helm install ray -f custom_values.yaml ./ray`

```
podTypes:
  rayHeadType:
    memory: 2048Mi
    rayResources: { "CPU": 0 }
  rayWorkerType:
    minWorkers: 1
    maxWorkers: 800
    memory: 16384Mi
    CPU: 1
```

**Comment by rkooo567** [comment]
Leaving it as a triage state until reproduction & further investigation

**Comment by tkram01** [comment]
Here is the docker file we are using

```
FROM rayproject/ray:latest

RUN $HOME/anaconda3/bin/pip --no-cache-dir install 'dask[dataframe]==2021.6.0' 's3fs==2021.6.0'
RUN $HOME/anaconda3/bin/conda install -c conda-forge rdkit mhfp molvs
```
