### ISSUE TITLE
Provide ray wheels in us-east-1?

### ISSUE THREAD

**Issue by yaroslavvb** [ray-project/ray#1682]
us-east-1 is the biggest region, it makes sense to copy wheels there

I recently found my `pip install https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.3.1-cp36-cp36m-manylinux1_x86_64.whl` in us-east-1 failing as follows

```
Cloud-init v. 17.1 running 'modules:config' at Thu, 08 Mar 2018 18:38:42 +0000. Up 28.79 seconds.
Collecting ray==0.3.1 from https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.3.1-cp36-cp36m-manylinux1_x86_64.whl
  Downloading https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.3.1-cp36-cp36m-manylinux1_x86_64.whl (49.2MB)
Exception:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 232, in _error_catcher
    yield
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 314, in read
    data = self._fp.read(amt)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 60, in read
    data = self.__fp.read(amt)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
```

Internets suggest to do `pip install --default-timeout=100 `

**Comment by yaroslavvb** [comment]
Actually the slowness is probably due to AWS instance warming up, since it took <10 seconds to install on second try....`default-timeout` should be the solution
