### ISSUE TITLE
ModuleNotFoundError: No module named 'joblib'

### ISSUE THREAD

**Issue by hamedhsn** [ray-project/ray#16875]
### What is the problem?
I have deployed a ray cluster in kubernetes and I wanted to test simple sklearn but I am getting `ModuleNotFoundError: No module named 'joblib'`
I am running ray job as Kubernetes job. 
```
cat job_sklearn-dist.yml
# Job to submit a Ray program from a pod outside a running Ray cluster.
apiVersion: batch/v1
kind: Job
metadata:
  name: ray-test-job-sklearn-dist
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: hsaljoog-general
      containers:
        - name: ray
          image: rayproject/ray:latest
          volumeMounts:
          - name: task-pv-storage
            mountPath: /efs
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args:
            -  "python /efs/ray_test/sklearn-dist.py"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
```

this is the trace:
```
python sklearn-dist.py
The 'context' argument is not supported using ray. Please refer to the documentation for how to control ray initialization.
Fitting 5 folds for each of 4000 candidates, totalling 20000 fits
Traceback (most recent call last):
  File "sklearn-dist.py", line 26, in <module>
    search.fit(digits.data, digits.target)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 841, in fit
    self._run_search(evaluate_candidates)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 1296, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 809, in evaluate_candidates
    enumerate(cv.split(X, y, groups))))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 253, in apply_async
    SafeFunction(func), callback=callback)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/multiprocessing/pool.py", line 464, in apply_async
    [(args, kwargs)])
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/multiprocessing/pool.py", line 415, in _run_batch
    object_ref = actor.run_batch.remote(func, batch)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/common.py", line 325, in remote
    return return_refs(ray.call_remote(self, *args, **kwargs))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/api.py", line 103, in call_remote
    return self.worker.call_remote(instance, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 328, in call_remote
    return self._call_schedule_for_task(task)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 341, in _call_schedule_for_task
    raise cloudpickle.loads(ticket.error)
ModuleNotFoundError: No module named 'joblib'
```

this is the code:
```
cat sklearn-dist.py
import numpy as np
from joblib import parallel_backend
from sklearn.datasets import load_digits
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC


import ray
ray.client("ray-cluster-ray-head:10001").connect()
from ray.util.joblib import register_ray
register_ray()

param_space = {
    'C': np.logspace(-6, 6, 10),
    'gamma': np.logspace(-8, 8, 5),
    'tol': np.logspace(-4, -1, 10),
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
    'class_weight': [None, 'balanced'],
}

model = SVC(kernel='rbf')
search = GridSearchCV(model, param_space, cv=5, verbose=1)
digits = load_digits()

with parallel_backend('ray'):
    search.fit(digits.data, digits.target)
```
*Ray version and other system information (Python version, TensorFlow version, OS):*
ray, `version 1.4.1`

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by hamedhsn** [comment]
Noticed that joblib was not present in the worker nodes. installing it fixed the issue.
