### ISSUE TITLE
[tune] Resuming errored trials does not work

### ISSUE THREAD

**Issue by smorad** [ray-project/ray#16891]
### What is the problem?
`tune.run(..., resume='ERRORED_ONLY')` is supposed to reset and rerun failed experiments. It does not do so.

Verified using ray nightly wheel installed 7 July
### Reproduction (REQUIRED)
```
import gym
import ray
from ray import tune
import numpy as np


class TestEnv(gym.Env):
    def __init__(self, cfg={}):
        self.observation_space = gym.spaces.Discrete(1)
        self.action_space = gym.spaces.Discrete(1)

    def reset(self):
        return 0

    def step(self, act):
        raise Exception()

try:
    tune.run("PPO", config={"env": TestEnv, "framework": "torch"})
except:
    pass
tune.run("PPO", config={"env": TestEnv, "framework": "torch"}, resume="ERRORED_ONLY")
```

Truncated output:
```
...
2021-07-06 17:16:09,555 INFO trial_runner.py:308 -- Restarting experiment.
== Status ==
Memory usage on this node: 20.5/187.6 GiB                                                                                                                                                                        Using FIFO scheduling algorithm.
Resources requested: 0/96 CPUs, 0/4 GPUs, 0.0/132.82 GiB heap, 0.0/31.83 GiB objects (0.0/1.0 accelerator_type:RTX)



2021-07-06 17:16:09,660 INFO tune.py:545 -- Total run time: 0.12 seconds (0.00 seconds for the tuning loop).
2021-07-06 17:16:09,661 WARNING experiment_analysis.py:719 -- No `self.trials`. Drawing logdirs from checkpoint file. This may result in some information that is out of sync, as checkpointing is periodic.
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    tune.run("PPO", config={"env": TestEnv, "framework": "torch"}, resume="ERRORED_ONLY")
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/tune.py", line 555, in run
    return ExperimentAnalysis(
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/analysis/experiment_analysis.py", line 425, in __init__
    super(ExperimentAnalysis, self).__init__(
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/analysis/experiment_analysis.py", line 77, in __init__
    self.fetch_trial_dataframes()
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/analysis/experiment_analysis.py", line 201, in fetch_trial_dataframes
    for path in self._get_trial_paths():
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/analysis/experiment_analysis.py", line 726, in _get_trial_paths
    raise TuneError("No trials found.")
ray.tune.error.TuneError: No trials found.
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
@matthewdeng maybe you can take a look into this?

cc @krfricke @amogkam
