### ISSUE TITLE
[cli] Support redis password for all ray commands

### ISSUE THREAD

**Issue by seraphzl** [ray-project/ray#16921]
### What is the problem?
When using customized redis password, redis reported response error: WRONGPASS invalid username-password pair

Ray version: 1.4.1
Python version: 3.7.10
OS: CentOS 7.9
Redis version: 3.5.3

### Reproduction (REQUIRED)

On remote host:

```javascript
$ ray start --head --port=6379 --redis-password='ray'
Local node IP: 172.31.3.13
2021-07-07 10:06:55,142	INFO services.py:1275 -- View the Ray dashboard at http://127.0.0.1:8265

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='172.31.3.13:6379' --redis-password='ray'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='ray')
  
  If connection fails, check your firewall settings and network configuration.
  
  To terminate the Ray runtime, run
    ray stop
```

On the same host as above:

```javascript
$ ray timeline
2021-07-07 10:07:06,424	INFO scripts.py:1361 -- Connecting to Ray instance at 172.31.3.13:6379.
2021-07-07 10:07:06,425	INFO worker.py:736 -- Connecting to existing Ray cluster at address: 172.31.3.13:6379
Traceback (most recent call last):
  File "/home/xxx/.local/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/xxx/.local/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1808, in main
    return cli()
  File "/home/xxx/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/xxx/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xxx/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxx/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1362, in timeline
    ray.init(address=address)
  File "/home/xxx/.local/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.7/site-packages/ray/worker.py", line 844, in init
    connect_only=True)
  File "/home/xxx/.local/lib/python3.7/site-packages/ray/node.py", line 163, in __init__
    session_name = _get_with_retry(redis_client, "session_name")
  File "/home/xxx/.local/lib/python3.7/site-packages/ray/node.py", line 41, in _get_with_retry
    result = redis_client.get(key)
  File "/home/xxx/.local/lib/python3.7/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/home/xxx/.local/lib/python3.7/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/xxx/.local/lib/python3.7/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/xxx/.local/lib/python3.7/site-packages/redis/connection.py", line 567, in connect
    self.on_connect()
  File "/home/xxx/.local/lib/python3.7/site-packages/redis/connection.py", line 643, in on_connect
    auth_response = self.read_response()
  File "/home/xxx/.local/lib/python3.7/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: WRONGPASS invalid username-password pair

```

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
