### ISSUE TITLE
Check failed: data_size == static_cast<uint64_t>(object_buffer.data->Size() + object_buffer.metadata->Size()) 

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#16923]
object_buffer_pool.cc:74:  Check failed: data_size == static_cast<uint64_t>(object_buffer.data->Size() + object_buffer.metadata->Size()) 

I (very rarely) see the above when running https://github.com/ray-project/ray/issues/16342. It seems to occur at most a couple times per hundred runs.

This is a very strange, it seems to indicate that nodes are disagreeing about the size of an object.

**Comment by ericl** [comment]
```
(pid=188, ip=172.31.72.195) 2021-07-07 09:29:39,314	ERROR serialization.py:253 -- Can't deserialize object: ObjectRef(86460fb9629b4b8effffffffffffffffffffffff0100000010000000), metadata: b'\x00\x00\x00\x00@o'
(pid=188, ip=172.31.72.195) Traceback (most recent call last):
(pid=188, ip=172.31.72.195)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 202, in _deserialize_object
(pid=188, ip=172.31.72.195)     error_type = int(metadata_fields[0])
(pid=188, ip=172.31.72.195) ValueError: invalid literal for int() with base 10: b'\x00\x00\x00\x00@o'
(pid=188, ip=172.31.72.195) 
(pid=188, ip=172.31.72.195) During handling of the above exception, another exception occurred:
(pid=188, ip=172.31.72.195) 
(pid=188, ip=172.31.72.195) Traceback (most recent call last):
(pid=188, ip=172.31.72.195)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 251, in deserialize_objects
(pid=188, ip=172.31.72.195)     obj = self._deserialize_object(data, metadata, object_ref)
(pid=188, ip=172.31.72.195)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 204, in _deserialize_object
(pid=188, ip=172.31.72.195)     raise Exception(f"Can't deserialize object: {object_ref}, "
(pid=188, ip=172.31.72.195) Exception: Can't deserialize object: ObjectRef(86460fb9629b4b8effffffffffffffffffffffff0100000010000000), metadata: b'\x00\x00\x00\x00@o'
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,004 E 91 118] logging.cc:440: *** Aborted at 1625675380 (unix time) try "date -d @1625675380" if you are using GNU date ***
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,004 E 91 118] logging.cc:440: PC: @                0x0 (unknown)
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,004 E 91 118] logging.cc:440: *** SIGABRT (@0x3e80000005b) received by PID 91 (TID 0x7faf72ffd700) from PID 91; stack trace: ***
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,005 E 91 118] logging.cc:440:     @     0x55b71d58a17f google::(anonymous namespace)::FailureSignalHandler()
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,005 E 91 118] logging.cc:440:     @     0x7faf8cb503c0 (unknown)
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,005 E 91 118] logging.cc:440:     @     0x7faf8c63918b gsignal
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,005 E 91 118] logging.cc:440:     @     0x7faf8c618859 abort
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,005 E 91 118] logging.cc:440:     @     0x55b71d0ae2aa dlfree.cold
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,006 E 91 118] logging.cc:440:     @     0x55b71d26dc72 plasma::PlasmaAllocator::Free()
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,006 E 91 118] logging.cc:440:     @     0x55b71d278c44 plasma::PlasmaStore::EraseFromObjectTable()
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,007 E 91 118] logging.cc:440:     @     0x55b71d278da1 plasma::PlasmaStore::DeleteObject()
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,008 E 91 118] logging.cc:440:     @     0x55b71d27e90d plasma::PlasmaStore::ProcessMessage()
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,008 E 91 118] logging.cc:440:     @     0x55b71d26f5ef std::_Function_handler<>::_M_invoke()
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,008 E 91 118] logging.cc:440:     @     0x55b71d294326 _ZNSt17_Function_handlerIFvSt10shared_ptrIN3ray16ClientConnectionEElRKSt6vectorIhSaIhEEEZN6plasma6Client6CreateESt8functionIFNS1_6StatusES0_ISB_ENSA_7flatbuf11MessageTypeES8_EEON5boost4asio19basic_stream_socketINSK_7generic15stream_protocolENSK_8executorEEEEUlS3_lS8_E_E9_M_invokeERKSt9_Any_dataOS3_OlS8_
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,009 E 91 118] logging.cc:440:     @     0x55b71d524af2 ray::ClientConnection::ProcessMessage()
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,010 E 91 118] logging.cc:440:     @     0x55b71d521678 boost::asio::detail::read_op<>::operator()()
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,012 E 91 118] logging.cc:440:     @     0x55b71d521a2b boost::asio::detail::executor_function<>::do_complete()
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,012 E 91 118] logging.cc:440:     @     0x55b71d111bb0 boost::asio::io_context::executor_type::dispatch<>()
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,013 E 91 118] logging.cc:440:     @     0x55b71d522373 boost::asio::executor::dispatch<>()
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,014 E 91 118] logging.cc:440:     @     0x55b71d522568 boost::asio::detail::reactive_socket_recv_op<>::do_complete()
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,016 E 91 118] logging.cc:440:     @     0x55b71d943511 boost::asio::detail::scheduler::do_run_one()
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,018 E 91 118] logging.cc:440:     @     0x55b71d943641 boost::asio::detail::scheduler::run()
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,018 E 91 118] logging.cc:440:     @     0x55b71d945840 boost::asio::io_context::run()
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,019 E 91 118] logging.cc:440:     @     0x55b71d26e6fb plasma::PlasmaStoreRunner::Start()
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,020 E 91 118] logging.cc:440:     @     0x55b71d1fe527 std::thread::_State_impl<>::_M_run()
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,020 E 91 118] logging.cc:440:     @     0x55b71d97fdf0 execute_native_thread_routine
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,021 E 91 118] logging.cc:440:     @     0x7faf8cb44609 start_thread
(raylet, ip=172.31.72.195) [2021-07-07 09:29:40,021 E 91 118] logging.cc:440:     @     0x7faf8c715293 clone
```

**Comment by ericl** [comment]
```
(raylet, ip=172.31.55.62) [2021-07-07 09:30:54,678 C 91 123] object_buffer_pool.cc:74:  Check failed: data_size == static_cast<uint64_t>(object_buffer.data->Size() + object_buffer.metadata->Size()) Total size: 1159309, data size: 0, metadata size: 1
```

Based on the above two stack traces, it looks like data corruption (perhaps another thread-safety issue). cc @scv119

**Comment by scv119** [comment]
while I trying to reproduce this by setting up two nodes on the same machine, I notices a lot of object lost errors which may or maynot related to this bug. Here is one of the interesting log trace:
https://gist.github.com/scv119/049cc18d3d77f668d03e2146f9f8ddc7

**Comment by scv119** [comment]
```
3162773:[2021-07-10 05:47:52,765 D 24664 24664] ownership_based_object_directory.cc:214: Pushing location updates to subscribers for object 32193fcb6229fca4ffffffffffffffffffffffff0100000020000000: 0 locations, spilled_url: , spilled node ID: NIL_ID, object size: 0, lookup failed: 1
```
this error message looks very suspicious actually. If i understand correctly it will lead to pull manager pulling the object with 0 object size:
```
3162781:[2021-07-10 05:47:52,785 W 24664 24664] pull_manager.cc:447: Size of object 32193fcb6229fca4ffffffffffffffffffffffff0100000020000000 stored in object store is zero. This may be a bug since objects in the object store should be large, and can result in too many objects being fetched to this node
```

**Comment by scv119** [comment]
```
[2021-07-10 21:48:25,505 D 78097 78097] ownership_based_object_directory.cc:179: Worker 6b4d76cb58a1b1cbab8e91e4f94cca4e35cdc0fbe716ba5dfca7d0a5 failed to remove the location 56f6599e308c939f8a0594f5d527a3b64c39f9221add024c0a568cd5 for d0eb427dc015db85ffffffffffffffffffffffff010000002b000000, the object has most likely been freed: IOError: 2: Object d0eb427dc015db85ffffffffffffffffffffffff010000002b000000 not found
[2021-07-10 21:48:26,352 D 78097 78097] node_manager.cc:1781: Mark the object id d0eb427dc015db85ffffffffffffffffffffffff010000002b000000 as failed due to 2
[2021-07-10 21:48:26,353 D 78097 78116] store.cc:827: Received request to create object d0eb427dc015db85ffffffffffffffffffffffff010000002b000000 immediately
[2021-07-10 21:48:26,353 D 78097 78116] store.cc:334: attempting to create object d0eb427dc015db85ffffffffffffffffffffffff010000002b000000 size 0
[2021-07-10 21:48:26,353 D 78097 78116] store.cc:361: create object d0eb427dc015db85ffffffffffffffffffffffff010000002b000000 succeeded
[2021-07-10 21:48:26,353 D 78097 78116] store.cc:199: Object d0eb427dc015db85ffffffffffffffffffffffff010000002b000000 in use by client, num bytes in use is now 3780632562
[2021-07-10 21:48:26,353 D 78097 78116] store.cc:662: sealing object d0eb427dc015db85ffffffffffffffffffffffff010000002b000000
[2021-07-10 21:48:26,773 D 78097 78097] object_manager.cc:171: Object added d0eb427dc015db85ffffffffffffffffffffffff010000002b000000
[2021-07-10 21:48:26,773 D 78097 78097] ownership_based_object_directory.cc:121: Object d0eb427dc015db85ffffffffffffffffffffffff010000002b000000 does not have owner. ReportObjectAdded becomes a no-op.This should only happen for Plasma store warmup objects.
[2021-07-10 21:48:26,773 D 78097 78097] node_manager.cc:1938: Object local d0eb427dc015db85ffffffffffffffffffffffff010000002b000000,  on 56f6599e308c939f8a0594f5d527a3b64c39f9221add024c0a568cd5, 0 tasks ready
[2021-07-10 21:48:38,037 D 78097 78097] push_manager.cc:64: Sending chunk 1 of 1 for push 443f5d5a9d54227a4e91929118309509d28db1bc83f18daedd9b3ad4, d0eb427dc015db85ffffffffffffffffffffffff010000002b000000, chunks in flight 409 / 409 max, remaining chunks: 1432
[2021-07-10 21:48:39,631 D 78097 78116] store.cc:199: Object d0eb427dc015db85ffffffffffffffffffffffff010000002b000000 in use by client, num bytes in use is now 3472791428
[2021-07-10 21:48:39,631 D 78097 78116] protocol.cc:560: Sending object info, id: d0eb427dc015db85ffffffffffffffffffffffff010000002b000000 data_size: 0 metadata_size: 1
[2021-07-10 21:48:39,631 C 78097 78119] object_buffer_pool.cc:75:  Check failed: data_size == static_cast<uint64_t>(object_buffer.data->Size() + object_buffer.metadata->Size()) Object id:d0eb427dc015db85ffffffffffffffffffffffff010000002b000000Total size: 329227, data size: 0, metadata size: 1
```

**Comment by rkooo567** [comment]
Hmm interesting. Wonder if I did a mistake in conversion from the previous logic or it was like that from before… but it seems like we should handle thid

**Comment by scv119** [comment]
my take is this is happens under some condition between push manager and object GC, under load.

**Comment by ericl** [comment]
Yea sounds like some race condition fetching an object that was already
deleted, which is failing in the wrong way due to metadata handling bug.
