### ISSUE TITLE
TuneError: Trials did not complete", incomplete_trials

### ISSUE THREAD

**Issue by subasah** [ray-project/ray#16926]
### What is the problem?
Training ends with the following error: 
 raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [SAC_MountainCarCountinuous-v0_5ad25_00000])

*Ray version and other system information (Python version, TensorFlow version, OS):*

**Ray version: 1.4.0
Python Version: 3.7.10
Tensorflow version: 1.14.0
OS: Fedora 34**
 
### Reproduction
```
import logging
import gym
import ray
from ray import tune
from ray.rllib.agents.sac import SACTrainer
from ray.tune.registry import register_env

# ray.shutdown()
ray.init(local_mode=True, include_dashboard= False, logging_level=logging.DEBUG)
# ray.init(include_webui= False)

ENV = 'MountainCarCountinuous-v0'
# ENV = 'Acrobot-v1'
def make_env(env_config):
    env = gym.make(ENV)
    return env
register_env(ENV, make_env)
TARGET_REWARD = 6000
TRAINER = SACTrainer
tune.run(
    TRAINER,
    stop={"episode_reward_mean": TARGET_REWARD},
    config={
        "env": ENV,
        "num_workers": 11,
        "num_gpus": 0,
        # "monitor": True,
        "evaluation_num_episodes": 50,
        "optimization": {
            "actor_learning_rate": 1e-3,
            "critic_learning_rate": 1e-3,
            "entropy_learning_rate": 3e-4,
        },
        "train_batch_size": 128,
        "target_network_update_freq": 1,
        "learning_starts": 100,
        "buffer_size": 1_000_000,
        # "observation_filter": "MeanStdFilter",
    }
    # resume=True
)
```

When you select **Acrobot-v1** environment then it runs fine but it breaks as soon as I use the **MountainCarCountinuous-v0** environment. 
[Error log is here](https://drive.google.com/file/d/1w7i6ypSYKdF_26drpuFG8R4CqLME8kI9/view?usp=sharing)

- [x] I have verified my script runs in a clean environment and reproduces the issue

**Comment by richardliaw** [comment]
Can you try doing `tune.run(fail_fast="raise")`?

**Comment by subasah** [comment]
```
tune.run(
    TRAINER,
    stop={"episode_reward_mean": TARGET_REWARD},
    config={
        "env": ENV,
        "num_workers": 11,
        "num_gpus": 0,
        # "monitor": True,
        "evaluation_num_episodes": 50,
        "optimization": {
            "actor_learning_rate": 1e-3,
            "critic_learning_rate": 1e-3,
            "entropy_learning_rate": 3e-4,
        },
        "train_batch_size": 128,
        "target_network_update_freq": 1,
        "learning_starts": 100,
        "buffer_size": 1_000_000,
        # "observation_filter": "MeanStdFilter",
    },
    # resume=True
    fail_fast="raise"
)
```
Output:
 
 res = next(self.train_exec_impl)
AttributeError: 'SAC' object has no attribute 'train_exec_impl'
@richardliaw  Please let me know if you need any more details.

**Comment by subasah** [comment]
```
#!/usr/bin/env python
# encoding: utf-8
from NR_IES.envs.NR_IES_env import NR_IES_v0
from ray.tune.registry import register_env
import gym
import os
import ray
import ray.rllib.agents.ppo as ppo # here we can use DDPG
import ray.rllib.agents.ddpg as ddpg
from ray.rllib.agents.sac.sac import SACTrainer, DEFAULT_CONFIG

import shutil
from ray import tune

import logging


def main ():
    # initiate directory and save checkpoints
    chkpt_root = "td3_training/NR_IES"
    shutil.rmtree(chkpt_root, ignore_errors=True, onerror=None)

    ray.init(local_mode=True, include_dashboard= False, logging_level=logging.DEBUG)

    # custom environment registration
    select_env = "NR_IES-v0"
    register_env(select_env, lambda config: NR_IES_v0())

    # create agent and environment configuration
    config = DEFAULT_CONFIG.copy()
    config["simple_optimizer"] = True

    # print(config)
    agent = SACTrainer(config, env=select_env)
    
    status = "{:2d} reward {:6.2f}/{:6.2f}/{:6.2f} len {:4.2f} saved {}"
    n_iter = 1222000

    for n in range(n_iter):
        result = agent.train()
        chkpt_file = agent.save(chkpt_root)
        print(status.format(
                n + 1,
                result["episode_reward_min"],
                result["episode_reward_mean"],
                result["episode_reward_max"],
                result["episode_len_mean"],
                chkpt_file
                ))

if __name__ == "__main__":
    main()

```
Also tried running for my custom environment in both the ways, one above and this but unfortunately had no luck. 
Error log: 
Traceback (most recent call last):
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ssah3@UTAD/.vscode/extensions/ms-python.python-2021.6.944021595/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/ssah3@UTAD/.vscode/extensions/ms-python.python-2021.6.944021595/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/ssah3@UTAD/.vscode/extensions/ms-python.python-2021.6.944021595/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ssah3@UTAD/Desktop/NR_IES/sac-train.py", line 58, in <module>
    main()
  File "/home/ssah3@UTAD/Desktop/NR_IES/sac-train.py", line 40, in main
    agent = SACTrainer(config, env=select_env)
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 123, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 548, in __init__
    super().__init__(config, logger_creator)
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/site-packages/ray/tune/trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 709, in setup
    self._init(self.config, self.env_creator)
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 155, in _init
    num_workers=self.config["num_workers"])
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 797, in _make_workers
    logdir=self.logdir)
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 100, in __init__
    spaces=spaces,
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 407, in _make_worker
    spaces=spaces,
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 534, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1193, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/policy/tf_policy_template.py", line 251, in __init__
    get_batch_divisibility_req=get_batch_divisibility_req,
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/policy/dynamic_tf_policy.py", line 305, in __init__
    action_dist = dist_class(dist_inputs, self.model)
  File "/home/ssah3@UTAD/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/models/tf/tf_action_dist.py", line 328, in __init__
    assert tfp is not None
AssertionError

**Comment by subasah** [comment]
I had to install the tensorflow_probability and then use the tensorflow >=1.15.0 and then downgrade my numpy to 1.19. Doing this resolved resolved the issue:  [message you can see from here:](https://docs.google.com/document/d/1bgzOsiCT80bOnf8sA27zqrVQbGG-0xz1Grq-Dy98sZI/edit?usp=sharing) 

References: 
https://github.com/tensorflow/models/issues/9706#issuecomment-782841778

**Comment by richardliaw** [comment]
Awesome!

**Comment by hiepbk** [comment]
I have some problems like this.
For me, I need downgrade tensorflow==1.14.0 and gym==0.19.0
And then find the compatibility version of tensorflow_probability==0.7.0. You can refer [tensorflow_probability reslease](https://github.com/tensorflow/probability/releases?page=4)
