### ISSUE TITLE
TPU error: ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task

### ISSUE THREAD

**Issue by paramjeet2021** [ray-project/ray#16931]
0

I am GCP user and creaed a VM in the US region. I have cloned the https://github.com/kingoflolz/mesh-transformer-jax and running train.py

Internally it creates a TPU and pass complex computations to the TPU. It also creates a radis server in between. When the code hit the line 39 in mesh-transformer-jax/mesh_transformer/TPU_cluster.py

elf.param_count = ray.get(params)[0]

It generates following error

cluster TPU setup start (pid=6093, ip=10.128.0.47) 2021-07-07 10:52:52.676541: F external/org_tensorflow/tensorflow/core/tpu/tpu_executor_init_fns.inc:110] TpuTransferManager_ReadDynamicShapes not available in this library.

[[A2021-07-07 11:04:20,579 WARNING worker.py:1107 -- A worker died or was killed while executing task ffffffffffffffffcd0102814274b3f83c2a1f1c01000000.
Traceback (most recent call last):
  File "train.py", line 75, in <module>
    t = build_model(params, tpu_name, region, preemptible, version=args.version)
  File "/home/param_jeet/content-intelligence/Mesh-Transformer/mesh_transformer/build_model.py", line 64, in build_model
    t = TPUCluster((tpu_size // cores_per_replica, cores_per_replica), len(conns), model_fn)
  File "/home/param_jeet/.local/lib/python3.8/site-packages/func_timeout/dafunc.py", line 185, in <lambda>
    return wraps(func)(lambda *args, **kwargs : func_timeout(defaultTimeout, func, args=args, kwargs=kwargs))
  File "/home/param_jeet/.local/lib/python3.8/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/home/param_jeet/.local/lib/python3.8/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/home/param_jeet/content-intelligence/Mesh-Transformer/mesh_transformer/TPU_cluster.py", line 51, in __init__
    self.param_count = ray.get(params)[0]
  File "/home/param_jeet/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/param_jeet/.local/lib/python3.8/site-packages/ray/worker.py", line 1458, in get
    raise value

ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task. Check python-core-worker-*.log files for more information.

I am not able to detect the possible cause of this. Can anyone here help me with the possible cause and how to get rid of this error. I have log files as well with me. I can share log files as well if you would like to see.

**Comment by ericl** [comment]
Seems this was a fatal error:
```
cluster TPU setup start (pid=6093, ip=10.128.0.47) 2021-07-07 10:52:52.676541: F external/org_tensorflow/tensorflow/core/tpu/tpu_executor_init_fns.inc:110] TpuTransferManager_ReadDynamicShapes not available in this library.

```

**Comment by paramjeet2021** [comment]
I am not able to find anything on google to overcome this. Can you suggest me, what could be the possible reason for this? 

Is this some library versioning issue or something else? I have not made any change in the code under  https://github.com/kingoflolz/mesh-transformer-jax so I think this is not code issue.

**Comment by paramjeet2021** [comment]
Another point, program halts approx 10 minutes after the code displays this message on the screen. If it is major concern then shouldn't it halts the code immediately?

**Comment by paramjeet2021** [comment]
**gcs_server.out**

021-07-07 10:52:10,648 I 10067 10067] io_service_pool.cc:36: IOServicePool is running with 1 io_service.
[2021-07-07 10:52:10,651 I 10067 10067] **gcs_redis_failure_detector.cc:30: Starting redis failure detector.**
[2021-07-07 10:52:10,651 I 10067 10067] gcs_init_data.cc:44: Loading job table data.
[2021-07-07 10:52:10,651 I 10067 10067] gcs_init_data.cc:56: Loading node table data.
[2021-07-07 10:52:10,651 I 10067 10067] gcs_init_data.cc:68: Loading object table data.
[2021-07-07 10:52:10,651 I 10067 10067] gcs_init_data.cc:81: Loading cluster resources table data.
[2021-07-07 10:52:10,651 I 10067 10067] gcs_init_data.cc:108: Loading actor table data.
[2021-07-07 10:52:10,651 I 10067 10067] gcs_init_data.cc:94: Loading placement group table data.
[2021-07-07 10:52:10,652 I 10067 10067] gcs_init_data.cc:48: Finished loading job table data, size = 0
[2021-07-07 10:52:10,652 I 10067 10067] gcs_init_data.cc:60: Finished loading node table data, size = 0
[2021-07-07 10:52:10,652 I 10067 10067] gcs_init_data.cc:73: Finished loading object table data, size = 0
[2021-07-07 10:52:10,652 I 10067 10067] gcs_init_data.cc:85: Finished loading cluster resources table data, size = 0
[2021-07-07 10:52:10,652 I 10067 10067] gcs_init_data.cc:112: Finished loading actor table data, size = 0
[2021-07-07 10:52:10,652 I 10067 10067] gcs_init_data.cc:99: Finished loading placement group table data, size = 0
[2021-07-07 10:52:10,674 I 10067 10067] grpc_server.cc:75: GcsServer server started, listening on port 45131.
[2021-07-07 10:52:10,682 I 10067 10067] gcs_server.cc:267: Gcs server address = 10.128.0.27:45131
[2021-07-07 10:52:10,682 I 10067 10067] gcs_server.cc:271: Finished setting gcs server address: 10.128.0.27:45131
[2021-07-07 10:52:10,682 I 10067 10067] gcs_server.cc:357: GcsNodeManager: {RegisterNode request count: 0, UnregisterNode request count: 0, GetAllNodeInfo request count: 0, SetIntern
alConfig request count: 0, GetInternalConfig request count: 0}

2nd line in this log file shows gcs_radis_failur which occured at 10:52:10 whereas if we see the time stamp of fatal error that occured at 10:52:52.676541, 42 sec after the gcs_radis_failure. Does gcs_radis_failure cause this fatal error and overall death of the worker?

**Comment by ericl** [comment]
I don't think that's related, it seems pretty clear the error is raised
from the TPU library. Maybe try running it without Ray?

**Comment by paramjeet2021** [comment]
I have cloned the code from https://github.com/kingoflolz/mesh-transformer-jax report and I think executing it without ray would require complete code change. 

Could the TPU premptible == Yes or lower TPU configuration (used V3-8, Recommended V3-256) caused this error?

**Comment by paramjeet2021** [comment]
I reinstalled JAX using below commands and the fatal error goes away.  

````lang-python
pip install --upgrade pip

pip install "jax[tpu]>=0.2.16" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html

````
