### ISSUE TITLE
xgboost prediction - AttributeError: 'str' object has no attribute 'id'

### ISSUE THREAD

**Issue by hamedhsn** [ray-project/ray#16930]
### What is the problem?
trying to run xgboost code on my ray cluster in kuberntes and getting this error 
```
python xgboost-dist.py
/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/sklearn.py:632: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
(pid=None) 2021-07-07 04:38:03,925	INFO main.py:892 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
(pid=None) 2021-07-07 04:38:06,418	INFO main.py:937 -- [RayXGBoost] Starting XGBoost training.
(pid=None) [04:38:06] task [xgboost.ray]:140175821128720 got new rank 0
(pid=None, ip=10.234.227.150) [04:38:06] task [xgboost.ray]:140295425351760 got new rank 1
(pid=None, ip=10.234.227.75) [04:38:06] task [xgboost.ray]:140429864747408 got new rank 2
(pid=None, ip=10.234.231.91) [04:38:06] task [xgboost.ray]:139914279695568 got new rank 3
(pid=None, ip=10.234.231.91) [04:38:06] WARNING: ../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=None) [04:38:06] WARNING: ../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=None, ip=10.234.227.150) [04:38:06] WARNING: ../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=None, ip=10.234.227.75) [04:38:06] WARNING: ../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=None) 2021-07-07 04:38:16,660	INFO main.py:1411 -- [RayXGBoost] Finished XGBoost training on training data with total N=142 in 14.13 seconds (10.24 pure XGBoost training time).
Traceback (most recent call last):
  File "xgboost-dist.py", line 27, in <module>
    pred_ray = clf.predict(X_test)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/sklearn.py", line 660, in predict
    _remote=_remote,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/sklearn.py", line 275, in _ray_predict
    **compat_predict_kwargs,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 1520, in predict
    model, data, ray_params, _remote=False, **kwargs))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 61, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/api.py", line 42, in get
    return self.worker.get(vals, timeout=timeout)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 225, in get
    res = self._get(obj_ref, op_timeout)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 248, in _get
    raise err
types.RayTaskError(AttributeError): ray::predict() (pid=18863, ip=10.234.226.150)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py", line 330, in _function_with_tracing
    return function(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py", line 330, in _function_with_tracing
    return function(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 1540, in predict
    return _predict(model, data, ray_params=ray_params, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 1446, in _predict
    for i in range(ray_params.num_actors)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 1446, in <listcomp>
    for i in range(ray_params.num_actors)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 679, in _create_actor
    distributed_callbacks=distributed_callbacks)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 481, in remote
    override_environment_variables))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py", line 367, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 642, in _remote
    placement_group_bundle_index)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/placement_group.py", line 370, in check_placement_group_index
    if placement_group.id.is_nil():
AttributeError: 'str' object has no attribute 'id'
```
The xgboost code is here:
```
from xgboost_ray import RayXGBClassifier, RayParams
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

import ray
ray.client("ray-cluster-ray-head:10001").connect()

seed = 42

X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=0.25, random_state=42
)

clf = RayXGBClassifier(
    n_jobs=4,  # In XGBoost-Ray, n_jobs sets the number of actors
    random_state=seed
)

# scikit-learn API will automatically conver the data
# to RayDMatrix format as needed.
# You can also pass X as a RayDMatrix, in which case
# y will be ignored.

clf.fit(X_train, y_train)

pred_ray = clf.predict(X_test)
print(pred_ray)

pred_proba_ray = clf.predict_proba(X_test)
print(pred_proba_ray)

```

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
@hamedhsn what version of ray are you on?

**Comment by hamedhsn** [comment]
@richardliaw am using the `rayproject/ray:latest` image which is using 1.4.1 version

**Comment by krfricke** [comment]
Hi @hamedhsn, this was fixed in the latest xgboost-ray master (https://github.com/ray-project/xgboost_ray/pull/130/files)

Can you install xgboost-ray from that version?

`pip install -U git+https://github.com/ray-project/xgboost_ray#xgboost_ray`

We will release a new version of XGBoost-Ray soon that includes this fix.

**Comment by krfricke** [comment]
We just release a new XGBoost-Ray version that includes the fix.

```
pip install -U xgboost_ray
```

should solve all your problems. Let me know if it doesn't!
