### ISSUE TITLE
[core]logmonitor error when training distributed across a multinode setup.

### ISSUE THREAD

**Issue by oriolaranda** [ray-project/ray#16933]
### What is the problem?
We start a slurm cluster involving 2 nodes (each with 4 GPU) and we run 32 distributed training sequentially each one with a different set of hyperparameters. We use ray.init() to connect to the server and ray.shutdown() to disconnect in each of the trainings. At some point (the 24th iteration), we got these errors:
stdout:
```
2021-07-01 12:51:58,869	ERR scripts.py:676 -- Some Ray subprcesses exited unexpectedly:
2021-07-01 12:51:58,870	ERR scripts.py:683 -- log_monitor [exit code=1]
2021-07-01 12:51:58,870	ERR scripts.py:687 -- Remaining processes will be killed.
```
sderr:
```
Traceback (most recent call last):
  File "/apps/RAY/1.1.0/lib/python3.7/site-packages/ray-1.1.0-py3.7-linux-ppc64le.egg/ray/log_monitor.py", line 354, in <module>
    log_monitor.run()
  File "/apps/RAY/1.1.0/lib/python3.7/site-packages/ray-1.1.0-py3.7-linux-ppc64le.egg/ray/log_monitor.py", line 275, in run
    self.open_closed_files()
  File "/apps/RAY/1.1.0/lib/python3.7/site-packages/ray-1.1.0-py3.7-linux-ppc64le.egg/ray/log_monitor.py", line 164, in open_closed_files
    self.close_all_files()
  File "/apps/RAY/1.1.0/lib/python3.7/site-packages/ray-1.1.0-py3.7-linux-ppc64le.egg/ray/log_monitor.py", line 102, in close_all_files
    os.kill(file_info.worker_pid, 0)
TypeError: an integer is required (got type NoneType)
2021-07-01 12:51:59,315	ERROR import_thread.py:89 -- ImportThread: Connection closed by server.
2021-07-01 12:51:59,315	ERROR worker.py:1036 -- listen_error_messages_raylet: Connection closed by server.
2021-07-01 12:51:59,315	ERROR worker.py:942 -- print_logs: Connection closed by server.
srun: error: p9r2n10: task 0: Exited with exit code 1
```
Any idea where the problem can be?

Libraries version used in a Power-9 cluster with slurm:
Ray 1.1.0
Python 3.7.4
Tensorflow 2.3.0

### Reproduction (REQUIRED)
```

def multi_node_training(config):
    print("Initializing ray multi-node...")
    ray.init(address='auto', _node_ip_address=os.environ["ip_head"].split(":")[0],
             _redis_password=os.environ["redis_password"])
    assert ray.is_initialized(), "ERROR: Ray is not initialized!"
    print('''This cluster consists of
                            {} nodes in total
                            {} CPU resources in total
                            {} GPU resources in total
                        '''.format(len(ray.nodes()), ray.cluster_resources()['CPU'], ray.cluster_resources()['GPU']))

    trainer = TFTrainer(
        model_creator=model_creator,
        data_creator=data_creator,
        num_replicas=config['num_replicas'],
        use_gpu=True,
        verbose=True,
        config=create_config(config)
    )

    trainer.train()  # train with train_config
    eval_stats = trainer.validate()  # validate with validate_config

    ray.shutdown()  # Shutdown ray to prevent an error on ports
    assert not ray.is_initialized(), "ERROR: Ray is still running!"

    return tuple(eval_stats.values())

# main function
for _ in range(32):
    res = multi_node_training(config)
```

**Comment by richardliaw** [comment]
@wuisawesome the logmonitor is nuking the rest of the Ray cluster; can you take a look?

**Comment by richardliaw** [comment]
@oriolaranda is it possible to update Ray to the latest version?

**Comment by wuisawesome** [comment]
I think this might be #12565 which was fixed after 1.1.0.

**Comment by oriolaranda** [comment]
@richardliaw @wuisawesome Thank you for your quick response!! I've already launched 2 jobs loading the module ray 1.2.0 (the latest version we have installed), I will update as soon as I get results.

**Comment by wuisawesome** [comment]
@oriolaranda I think the patch came with the 1.3 release. Any chance you can use that, or ideally even 1.4.1?

**Comment by oriolaranda** [comment]
@wuisawesome Yes! The systems team is currently trying to update to 1.4.1. I'll test and update the info afterwards. Thanks!!

**Comment by oriolaranda** [comment]
Sorry for the delay, the systems team struggled to upgrade to 1.4.1! Finally we managed to run the above script with any problem! Thanks a lot!

**Comment by eriksf** [comment]
@oriolaranda Any tips from your system team on building ray for Power9 (ppc64le)? I'm struggling with that right now.
