### ISSUE TITLE
Passing lists of actors to remote function fails

### ISSUE THREAD

**Issue by yaroslavvb** [ray-project/ray#1695]
The following code fails with obscure message. The solution is to replace `pss` with `*pss` 
```
pss = [ParameterServer.remote(args_dim // args.ps)
                       for _ in range(args.ps)]
Worker.remote(args_dim, pss)
```
error
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ray/actor.py", line 693, in __del__
    self._ray_actor_handle_id.id() == ray.worker.NIL_ACTOR_ID):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ray/actor.py", line 679, in __getattribute__
    return object.__getattribute__(self, attr)
AttributeError: 'ActorHandle' object has no attribute '_ray_actor_handle_id'
WARNING: Serializing objects of type <class 'ray.actor.actor_handle_from_class.<locals>.ActorHandle'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
Remote function train failed with:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ray/worker.py", line 762, in _process_task
    *arguments)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ray/actor.py", line 209, in actor_method_executor
    method_returns = method(actor, *args)
  File "ray_adder_async.py", line 142, in train
    push_ids.append(ray.get(ps_shard.push.remote(grad_shard)))
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ray/actor.py", line 473, in remote
    dependency=self._actor._ray_actor_cursor)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ray/actor.py", line 643, in _actor_method_call
    execution_dependencies=execution_dependencies)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ray/worker.py", line 534, in submit_task
    self.task_driver_id.id()][function_id.id()]
KeyError: b'\r\xbd\xedG\xd1&\xf5Mb\xe8n\xb3\xaa\xb1\xfc?\xaez\xf2t'
```

**Comment by makdoudN** [comment]
Any update on this issue ?

**Comment by robertnishihara** [comment]
@makdoudN no updates yet, for now it's possible to work around this by using a variable number of arguments in Python, e.g.,

```python
import ray

@ray.remote
class ParameterServer(object):
    pass

@ray.remote
class Worker(object):
    def __init__(self, *parameter_servers):
        self.parameter_servers = parameter_servers

ray.init()

parameter_servers = [ParameterServer.remote() for _ in range(4)]

worker = Worker.remote(*parameter_servers)
```

**Comment by edoakes** [comment]
Stale - please open new issue if still relevant
