### ISSUE TITLE
[Ray debugger] Clean up debugging state after job finishes

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#17040]
### What is the problem?

Currently the active breakpoints in the debugger are not cleaned up after the job that set the breakpoints exists. We should clean them up.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment]
@pcmoritz do you have a reproduction script for this & the relevant symptom?

**Comment by edoakes** [comment]
I think I might have found the issue:

`ray start --head`

```python
import ray
ray.init(address="auto")

@ray.remote
def f():
    ray.util.rpdb.set_trace()

f.remote()
# exit...
```

After the above runs, `ray debug` still shows the breakpoint:
```
Active breakpoints:
index | timestamp           | Ray task | filename:lineno                 
0     | 2021-07-14 23:08:55 | ray::f() | <ipython-input-3-e4b24f4fd682>:3
```

Trying to attach to it errors and it still hangs around:
```
Traceback (most recent call last):
  File "/Users/eoakes/anaconda3/bin/ray", line 33, in <module>
    sys.exit(load_entry_point('ray', 'console_scripts', 'ray')())
  File "/Users/eoakes/code/ray/python/ray/scripts/scripts.py", line 1946, in main
    return cli()
  File "/Users/eoakes/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/eoakes/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/eoakes/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/eoakes/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/eoakes/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/eoakes/code/ray/python/ray/scripts/scripts.py", line 255, in debug
    ray.util.rpdb.connect_pdb_client(host, int(port))
  File "/Users/eoakes/code/ray/python/ray/util/rpdb.py", line 248, in connect_pdb_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 61] Connection refused
```

**Comment by pcmoritz** [comment]
Yeah, that's exactly right!

The fix should be to include the job_id in the `RAY_PDB_` keys in the internal kv store and clean them up when the job exits. Happy to chat more about it if that helps!

**Comment by pcmoritz** [comment]
The relevant code is here: https://github.com/ray-project/ray/blob/master/python/ray/util/rpdb.py#L218
