### ISSUE TITLE
An unexpected internal error occurred while the IO worker was spilling objects

### ISSUE THREAD

**Issue by franklsf95** [ray-project/ray#17048]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

* Ray master

When object store is operating close to memory limit, I see this error coming from all workers before one of them dies and objects become lost:

```
2021-07-13 19:12:23,943 WARNING worker.py:1127 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 715, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 718, in ray._raylet.spill_objects_handler
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/ray/external_storage.py", line 522, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/ray/external_storage.py", line 277, in spill_objects
    return self._write_multiple_objects(f, object_refs,
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/ray/external_storage.py", line 128, in _write_multiple_objects
    buf_len = len(buf)
TypeError: object of type 'NoneType' has no len()
An unexpected internal error occurred while the IO worker was spilling objects: object of type 'NoneType' has no len()
```

Will try to repro this on a single node.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
@franklsf95 is working on the repro. If he cannot find the repro I think we should do some session to find a repro together cc @scv119 since we are aiming for 0 bug here.

**Comment by rkooo567** [comment]
Leaving it as a triage for now.

**Comment by franklsf95** [comment]
Related: I also see these error lines:

```
(raylet, ip=172.31.55.2) [2021-07-14 00:13:21,599 E 3311 3336] object_manager.cc:444: Read chunk 0 of object 4473684d08cd4804ffffffffffffffffffffffff0800000011000000 failed.  It may have been evicted.
(raylet, ip=172.31.55.2) [2021-07-14 00:13:21,604 E 3311 3336] object_manager.cc:444: Read chunk 1 of object 4473684d08cd4804ffffffffffffffffffffffff0800000011000000 failed.  It may have been evicted.
(raylet, ip=172.31.55.2) [2021-07-14 00:13:21,608 E 3311 3336] object_manager.cc:444: Read chunk 2 of object 4473684d08cd4804ffffffffffffffffffffffff0800000011000000 failed.  It may have been evicted.
(raylet, ip=172.31.55.2) [2021-07-14 00:13:21,612 E 3311 3336] object_manager.cc:444: Read chunk 3 of object 4473684d08cd4804ffffffffffffffffffffffff0800000011000000 failed.  It may have been evicted.
(raylet, ip=172.31.55.2) [2021-07-14 00:13:21,616 E 3311 3336] object_manager.cc:444: Read chunk 4 of object 4473684d08cd4804ffffffffffffffffffffffff0800000011000000 failed.  It may have been evicted.
(raylet, ip=172.31.55.2) [2021-07-14 00:13:21,621 E 3311 3336] object_manager.cc:444: Read chunk 5 of object 4473684d08cd4804ffffffffffffffffffffffff0800000011000000 failed.  It may have been evicted.
(raylet, ip=172.31.55.2) [2021-07-14 00:13:21,623 E 3311 3335] object_manager.cc:444: Read chunk 6 of object 4473684d08cd4804ffffffffffffffffffffffff0800000011000000 failed.  It may have been evicted.
(raylet, ip=172.31.55.2) [2021-07-14 00:13:21,628 E 3311 3336] object_manager.cc:444: Read chunk 7 of object 4473684d08cd4804ffffffffffffffffffffffff0800000011000000 failed.  It may have been evicted.
(raylet, ip=172.31.55.2) [2021-07-14 00:13:21,630 E 3311 3335] object_manager.cc:444: Read chunk 8 of object 4473684d08cd4804ffffffffffffffffffffffff0800000011000000 failed.  It may have been evicted.
(raylet, ip=172.31.55.2) [2021-07-14 00:13:21,632 E 3311 3336] object_manager.cc:444: Read chunk 9 of object 4473684d08cd4804ffffffffffffffffffffffff0800000011000000 failed.  It may have been evicted.
(raylet, ip=172.31.55.2) [2021-07-14 00:13:21,646 E 3311 3335] object_manager.cc:444: Read chunk 11 of object 4473684d08cd4804ffffffffffffffffffffffff0800000011000000 failed.  It may have been evicted.
```

**Comment by ericl** [comment]
Those aren't errors (can happen during normal course of operation). We should downgrade to DEBUG / clarify those.
