### ISSUE TITLE
RuntimeError: all elements of input should be between 0 and 1

### ISSUE THREAD

**Issue by liergou99** [ray-project/ray#17117]
ray : 1.4.1
python: 3.8.10
torch: 1.9.0

code:

```
import torch
import torch.nn as nn
from torch.utils.data import DataLoader

from ray.util.sgd.torch import TrainingOperator
from ray.util.sgd.torch.examples.train_example import LinearDataset

class MyTrainingOperator(TrainingOperator):
    def setup(self, config):

        train_dataset, val_dataset = LinearDataset(2, 5), LinearDataset(2,
                                                                        5)
        train_loader = DataLoader(train_dataset,
                                  batch_size=config["batch_size"])
        val_loader = DataLoader(val_dataset,
                                batch_size=config["batch_size"])

        model = nn.Linear(1, 1)

        optimizer = torch.optim.SGD(model.parameters(), lr=config.get("lr", 1e-4))

        criterion = torch.nn.BCELoss()

        scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.9)


        self.model, self.optimizer, self.criterion, self.scheduler = \
            self.register(models=model, optimizers=optimizer,
                          criterion=criterion,
                          schedulers=scheduler)
        self.register_data(train_loader=train_loader, validation_loader=val_loader)



import ray

ray.init()

from ray.util.sgd import TorchTrainer

trainer = TorchTrainer(
    training_operator_cls=MyTrainingOperator,
    scheduler_step_freq="epoch",  # if scheduler is used
    use_local=True,
    config={"lr": 0.001, "batch_size": 64})

from ray.tune.logger import pretty_print
print(pretty_print(trainer.train(profile=True)))
trainer.shutdown()
```
error

```
Traceback (most recent call last):
  File "test.py", line 60, in <module>
    print(pretty_print(trainer.train(profile=True)))
  File "/opt/anaconda3/envs/ray/lib/python3.8/site-packages/ray/util/sgd/torch/torch_trainer.py", line 423, in train
    success, worker_stats = self.worker_group.train(
  File "/opt/anaconda3/envs/ray/lib/python3.8/site-packages/ray/util/sgd/torch/worker_group.py", line 567, in train
    raise err
  File "/opt/anaconda3/envs/ray/lib/python3.8/site-packages/ray/util/sgd/torch/worker_group.py", line 555, in train
    local_worker_stats = self.local_worker.train_epoch(**params)
  File "/opt/anaconda3/envs/ray/lib/python3.8/site-packages/ray/util/sgd/torch/torch_runner.py", line 140, in train_epoch
    train_stats = self.training_operator.train_epoch(iterator, info)
  File "/opt/anaconda3/envs/ray/lib/python3.8/site-packages/ray/util/sgd/torch/training_operator.py", line 510, in train_epoch
    metrics = self.train_batch(batch, batch_info=batch_info)
  File "/opt/anaconda3/envs/ray/lib/python3.8/site-packages/ray/util/sgd/torch/training_operator.py", line 588, in train_batch
    loss = criterion(output, target)
  File "/opt/anaconda3/envs/ray/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/envs/ray/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 612, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/opt/anaconda3/envs/ray/lib/python3.8/site-packages/torch/nn/functional.py", line 2893, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)
RuntimeError: all elements of input should be between 0 and 1
```

**Comment by mvindiola1** [comment]
Hi @liergou99,

You either mood to add a sigmoid activation function (or other squashing function with a range [0,1] or keep the model as is and use the `BCEWithLogitsLoss` loss function.
