### ISSUE TITLE
Compilation in Travis failing with some Cython error.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1717]
The relevant part of the error seems to be

```
-- Running cmake --build for pyarrow
make
[ 11%] [34m[1mCompiling Cython CXX source for plasma...[0m
[ 11%] Built target plasma_pyx
[35m[1mScanning dependencies of target plasma[0m
[ 22%] [32mBuilding CXX object CMakeFiles/plasma.dir/plasma.cxx.o[0m
[ 33%] [32m[1mLinking CXX shared module debug/plasma.so[0m
[ 33%] Built target plasma
[35m[1mScanning dependencies of target _parquet_pyx[0m
[ 44%] [34m[1mCompiling Cython CXX source for _parquet...[0m

Error compiling Cython file:
------------------------------------------------------------
...
        cdef:
            shared_ptr[CSchema] sp_arrow_schema

        with nogil:
            check_status(FromParquetSchema(
                self.schema, self.parent._metadata.key_value_metadata(),
                                                                    ^
------------------------------------------------------------

/home/travis/build/ray-project/ray/thirdparty/build/arrow/python/pyarrow/_parquet.pyx:438:69: Cannot assign type 'shared_ptr[const CKeyValueMetadata]' to 'const shared_ptr[const CKeyValueMetadata]'
make[2]: *** [CMakeFiles/_parquet_pyx] Error 1
make[1]: *** [CMakeFiles/_parquet_pyx.dir/all] Error 2
make: *** [all] Error 2
error: command 'make' failed with exit status 2
Traceback (most recent call last):
  File "setup.py", line 138, in <module>
    license="Apache 2.0")
  File "/home/travis/miniconda/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/travis/miniconda/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/travis/miniconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/travis/miniconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/travis/miniconda/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/travis/miniconda/lib/python2.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/travis/miniconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/travis/miniconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/travis/miniconda/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 170, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/travis/miniconda/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 156, in call_command
    self.run_command(cmdname)
  File "/home/travis/miniconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/travis/miniconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/travis/miniconda/lib/python2.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/travis/miniconda/lib/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/home/travis/miniconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/travis/miniconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 67, in run
    subprocess.check_call(["../build.sh", sys.executable])
  File "/home/travis/miniconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../build.sh', '/home/travis/miniconda/bin/python']' returned non-zero exit status 1

travis_time:end:01f6a634:start=1520988596690956981,finish=1520989173301435664,duration=576610478683
[0K
[31;1mThe command "./.travis/install-ray.sh" failed and exited with 1 during .[0m
```

Possibly related to https://issues.apache.org/jira/browse/ARROW-2305 but probably not.

Note that Cython just updated their wheels today https://pypi.python.org/pypi/Cython/.

We can probably get around this by pinning to a specific Cython version.

**Comment by robertnishihara** [comment]
The test failure is fixed by #1718, but the issue will probably occur for anyone using Cython 0.28.
