### ISSUE TITLE
Error when running Ray datasets example from documentation

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#17172]
Environment
- MacOS 
- Python 3.7
- nightly Ray (using commit 2a53d22438c61b74538609b5b16adb3356bbaba0)

Running this

```python
import ray.experimental.data
import pandas as pd

pdf = pd.DataFrame({"one": [1, 2, 3], "two": ["a", "b", "c"]})
ds = ray.data.from_pandas([ray.put(pdf)])
```

fails with

```
2021-07-17 14:48:31,299	INFO services.py:1247 -- View the Ray dashboard at http://127.0.0.1:8265
---------------------------------------------------------------------------
RayTaskError(ArrowTypeError)              Traceback (most recent call last)
<ipython-input-1-23f5f3fcdb13> in <module>
      3 
      4 pdf = pd.DataFrame({"one": [1, 2, 3], "two": ["a", "b", "c"]})
----> 5 ds = ray.data.from_pandas([ray.put(pdf)])

~/opt/anaconda3/lib/python3.7/site-packages/ray/experimental/data/read_api.py in from_pandas(dfs, parallelism)
    398     res = [df_to_block.remote(df) for df in dfs]
    399     blocks, metadata = zip(*res)
--> 400     return Dataset(BlockList(blocks, ray.get(list(metadata))))
    401 
    402 

~/opt/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
     80         if client_mode_should_convert():
     81             return getattr(ray, func.__name__)(*args, **kwargs)
---> 82         return func(*args, **kwargs)
     83 
     84     return wrapper

~/opt/anaconda3/lib/python3.7/site-packages/ray/worker.py in get(object_refs, timeout)
   1565                     worker.core_worker.dump_object_store_memory_usage()
   1566                 if isinstance(value, RayTaskError):
-> 1567                     raise value.as_instanceof_cause()
   1568                 else:
   1569                     raise value

RayTaskError(ArrowTypeError): ray::df_to_block() (pid=77517, ip=192.168.10.58)
  File "python/ray/_raylet.pyx", line 534, in ray._raylet.execute_task
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py", line 330, in _function_with_tracing
    return function(*args, **kwargs)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/experimental/data/read_api.py", line 395, in df_to_block
    block = ArrowBlock(pa.table(df))
  File "pyarrow/table.pxi", line 2090, in pyarrow.lib.table
  File "pyarrow/table.pxi", line 1451, in pyarrow.lib.Table.from_pandas
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 575, in dataframe_to_arrays
    for c, f in zip(columns_to_convert, convert_fields)]
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 575, in <listcomp>
    for c, f in zip(columns_to_convert, convert_fields)]
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 566, in convert_column
    raise e
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 560, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 265, in pyarrow.lib.array
  File "pyarrow/types.pxi", line 76, in pyarrow.lib._datatype_to_pep3118
  File "pyarrow/array.pxi", line 64, in pyarrow.lib._ndarray_to_type
  File "pyarrow/error.pxi", line 108, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Did not pass numpy.dtype object', 'Conversion failed for column one with type int64')
```

The error also appears in the background from one of the workers.

**Comment by robertnishihara** [comment]
Ok, upgrading `pyarrow` fixed the issue.

**Comment by clarkzinzow** [comment]
Tracking the `pyarrow` version check in [this issue](https://github.com/ray-project/ray/issues/17759), closing this one.
