### ISSUE TITLE
[Core] Ray Actor abnormal exit problem  &&  Reproduction

### ISSUE THREAD

**Issue by allwefantasy** [ray-project/ray#17198]
### What is the problem?

```python
# get an existing worker pool
udfMaster = ray.get_actor("model_predict")

# get a worker from worker pool, the worker is also a actor
worker = ray.get(udfMaster.get.remote())

# return the worker back to the pool
udfMaster.give_back.remote(worker)

```
The last sentence will raise an error in a special environment (pyjava) , causing the worker actor to exit abnormally.

### Reproduction (REQUIRED)

First of all, make sure we use conda to manager our python environment  and  ray 1.3.0 or the latest dev version is installed.
Next, execute the following script to register several actors:

```python

import ray

ray.util.connect("127.0.0.1:10001", namespace="default")


@ray.remote
class UDFMaster(object):
    def __init__(self, num, conf):
        # model_servers = RayContext.parse_servers(conf["modelServers"])
        # items = RayContext.collect_from(model_servers)
        # model_refs = [ray.put(item) for item in items]
        self._idle_actors = [UDFWorker.remote(None, conf) for _ in range(num)]

    def get(self):
        return self._idle_actors.pop()

    def give_back(self, v):
        self._idle_actors.append(v)

    def shutdown(self):
        [ray.kill(worker) for worker in self._idle_actors]
        return ""


@ray.remote
class UDFWorker(object):
    def __init__(self, model_refs, conf):
        print("worker init")
        # from tensorflow.keras import models
        # self.model_path = "./tmp/model/{}".format(str(uuid.uuid4()))
        # streaming_tar.save_rows_as_file((ray.get(ref) for ref in model_refs), self.model_path)
        # models.load_model(self.model_path)

    def apply(self, v):
        return {"value": [[1.0, 2.0]]}

    def shutdown(self):
        pass


try:
    udfMaster = ray.get_actor("model_predict")
    ray.get(udfMaster.shutdown.remote())
    ray.get(ray.kill(udfMaster))
except Exception as inst:
    pass

UDFMaster.options(name="model_predict", lifetime="detached").remote(3, {})
```

Here we start an actor pool, three actor workers.
Next, download the pyjava project:

```
git clone https://github.com/allwefantasy/pyjava.git
```

Go to the project's python directory and run./install.sh to install pyjava package.
Enter the project, import using the IDE. Find `tech.mlsql.test. JavaApp1Spec`, and modify

```scala
def condaEnv = "source /Users/allwefantasy/opt/anaconda3/bin/activate ray-dev"
```

for your own conda environment, that is, the python env that  includes ray 1.3.0 or ray dev version, and also includes pyjava.

Now run the example,  the following error will be raised:

```
The actor died unexpectedly before finishing this task.
(b'\x80\x05\x95"\x00\x00\x00\x00\x00\x00\x00\x8c\x08builtins\x94\x8c\x0eAsse'
 b'rtionError\x94\x93\x94)R\x94.')
AssertionError()


Traceback (most recent call last):
  File "/Users/allwefantasy/opt/anaconda3/envs/ray-dev/lib/python3.6/site-packages/pyjava/worker.py", line 155, in main
    process()
  File "/Users/allwefantasy/opt/anaconda3/envs/ray-dev/lib/python3.6/site-packages/pyjava/worker.py", line 132, in process
    exec(code, n_local, n_local)
  File "<string>", line 15, in <module>
  File "/Users/allwefantasy/projects/ray/python/ray/util/client/common.py", line 266, in remote
    return return_refs(ray.call_remote(self, *args, **kwargs))
  File "/Users/allwefantasy/projects/ray/python/ray/util/client/api.py", line 103, in call_remote
    return self.worker.call_remote(instance, *args, **kwargs)
  File "/Users/allwefantasy/projects/ray/python/ray/util/client/worker.py", line 328, in call_remote
    return self._call_schedule_for_task(task)
  File "/Users/allwefantasy/projects/ray/python/ray/util/client/worker.py", line 345, in _call_schedule_for_task
    raise cloudpickle.loads(ticket.error)
AssertionError
```

The main problem lies in this line of code:

```python
udfMaster.give_back.remote(worker)
```
If the above sample code is taken out and executed in a python file, there will be no problem.

**Comment by zhe-thoughts** [comment]
Marking as P1 for now. But I'm talking to @allwefantasy to verify

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
