### ISSUE TITLE
[Windows][Durable] Can't sync with S3 on Windows using durable trainer

### ISSUE THREAD

**Issue by sietseromijn** [ray-project/ray#17264]
### What is the problem?

Ray fails to sync to S3 on Windows, because the CommandBasedClient in tune.sync_client uses shlex to create the command to execute and that leads to an invalid argument in the aws-cli. 

Relevant discussion about shlex on windows: https://stackoverflow.com/questions/33560364/python-windows-parsing-command-lines-with-shlex.

```
final_cmd = sync_template.format(
      source=shlex.quote(source), target=shlex.quote(target))
```

```
2021-07-22 15:58:16,203	ERROR trial_runner.py:924 -- Trial TFTrainable_d4dca_00000: Error processing result.
Traceback (most recent call last):
  File "C:\Users\sierom\AppData\Roaming\Python\Python38\site-packages\ray\tune\trial_runner.py", line 921, in _process_trial_save
    results = self.trial_executor.fetch_result(trial)
  File "C:\Users\sierom\AppData\Roaming\Python\Python38\site-packages\ray\tune\ray_trial_executor.py", line 712, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "C:\Users\sierom\AppData\Roaming\Python\Python38\site-packages\ray\_private\client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\sierom\AppData\Roaming\Python\Python38\site-packages\ray\worker.py", line 1504, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): ray::_WrappedDurableTrainable.save() (pid=11716, ip=10.130.9.146)
  File "python\ray\_raylet.pyx", line 534, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 484, in ray._raylet.execute_task.function_executor
  File "C:\Users\sierom\AppData\Roaming\Python\Python38\site-packages\ray\_private\function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\sierom\AppData\Roaming\Python\Python38\site-packages\ray\tune\durable_trainable.py", line 75, in save
    self.storage_client.wait()
  File "C:\Users\sierom\AppData\Roaming\Python\Python38\site-packages\ray\tune\sync_client.py", line 235, in wait
    raise TuneError("Sync error. Ran command: {}\n"
ray.tune.error.TuneError: Sync error. Ran command: aws s3 sync 'C:\Users\sierom\ray_results\TFTrainable_2021-07-22_15-58-02\TFTrainable_d4dca_00000_0_2021-07-22_15-58-03\' 's3://tune-trials/TFTrainable_2021-07-22_15-58-02\TFTrainable_d4dca_00000_0_2021-07-22_15-58-03' --only-show-errors
Error message (252): 
usage: aws s3 sync <LocalPath> <S3Uri> or <S3Uri> <LocalPath> or <S3Uri> <S3Uri>
Error: Invalid argument type
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
Windows ray nightly build. Python 3.8.8. aws-cli 2.2.21

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

- First install aws-cli 

```
import ray
import tensorflow as tf
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from ray.cluster_utils import Cluster
from ray import tune
from ray.util.sgd.tf.tf_trainer import TFTrainable

cluster = Cluster(initialize_head=True,
                  head_node_args={
                      'num_cpus': 10
                  })
ray.init(address=cluster.address, local_mode=True)

NUM_TRAIN_SAMPLES = 1000
NUM_TEST_SAMPLES = 400


def create_config(batch_size):
    return {
        "batch_size": batch_size,
        "fit_config": {
            "steps_per_epoch": NUM_TRAIN_SAMPLES // batch_size
        },
        "evaluate_config": {
            "steps": NUM_TEST_SAMPLES // batch_size,
        }
    }


def linear_dataset(a=2, size=1000):
    x = np.random.rand(size)
    y = x / 2

    x = x.reshape((-1, 1))
    y = y.reshape((-1, 1))

    return x, y


def simple_dataset(config):
    batch_size = config["batch_size"]
    x_train, y_train = linear_dataset(size=NUM_TRAIN_SAMPLES)
    x_test, y_test = linear_dataset(size=NUM_TEST_SAMPLES)

    train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
    test_dataset = tf.data.Dataset.from_tensor_slices((x_test, y_test))
    train_dataset = train_dataset.shuffle(NUM_TRAIN_SAMPLES).repeat().batch(
        batch_size)
    test_dataset = test_dataset.repeat().batch(batch_size)

    return train_dataset, test_dataset


def simple_model(config):
    model = Sequential([Dense(10, input_shape=(1,)), Dense(1)])

    model.compile(
        optimizer="sgd",
        loss="mean_squared_error",
        metrics=["mean_squared_error"])

    return model


def tune_example(num_replicas=1, use_gpu=False):
    config = {
        "model_creator": simple_model,
        "data_creator": simple_dataset,
        "num_replicas": num_replicas,
        "use_gpu": use_gpu,
        "trainer_config": create_config(batch_size=128)
    }
    sync_config = tune.SyncConfig(
        sync_to_driver=False,
        upload_dir='s3://tune-trials/',
        sync_to_cloud='aws s3 sync {source} {target} --only-show-errors'
    )

    analysis = tune.run(
        tune.durable(TFTrainable),
        sync_config=sync_config,
        checkpoint_freq=1,
        num_samples=1,
        config=config,
        stop={"training_iteration": 1},
        verbose=1)

    return analysis.get_best_config(metric="validation_loss", mode="min")


if __name__ == '__main__':
    tune_example(num_replicas=1, use_gpu=False)
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

Is this relevant for #9114?

**Comment by krfricke** [comment]
We've centralized on pyarrow starting in Ray 2.0, so this problem shouldn't come up anymore.
