### ISSUE TITLE
[workflow] Unexpected test error related to ray actor

### ISSUE THREAD

**Issue by suquark** [ray-project/ray#17280]
### What is the problem?

The issue does not seems like coming from the workflow.

It can be reproduced locally (macos) with current upstream:

```
# inside workflow directory
pytest . --maxfail=1 -svvv -k init_twice
```

```
tests/test_basic_workflows_2.py::test_init_twice_2 2021-07-22 18:31:45,268      INFO worker.py:809 -- Connecting to existing Ray cluster at address: 192.168.0.237:51841
(pid=gcs_server) [2021-07-22 18:31:45,401 C 15647 4437208] gcs_actor_manager.cc:247:  Check failed: iter != registered_actors_.end() 
(pid=gcs_server) *** StackTrace Information ***
(pid=gcs_server)     ray::GetCallTrace()
(pid=gcs_server)     ray::SpdLogMessage::Flush()
(pid=gcs_server)     ray::RayLog::~RayLog()
(pid=gcs_server)     ray::gcs::GcsActorManager::HandleGetNamedActorInfo()
(pid=gcs_server)     ray::rpc::ServerCallImpl<>::HandleRequestImpl()
(pid=gcs_server)     boost::asio::detail::completion_handler<>::do_complete()
(pid=gcs_server)     boost::asio::detail::scheduler::do_run_one()
(pid=gcs_server)     boost::asio::detail::scheduler::run()
(pid=gcs_server)     boost::asio::io_context::run()
(pid=gcs_server)     main
(pid=gcs_server)     start
(pid=gcs_server)     0x0
(pid=gcs_server) 
2021-07-22 18:31:48,281 WARNING worker.py:1198 -- The autoscaler failed with the following error:
Traceback (most recent call last):
  File "/Users/s.z/Code/ray/python/ray/autoscaler/_private/monitor.py", line 317, in run
    self._run()
  File "/Users/s.z/Code/ray/python/ray/autoscaler/_private/monitor.py", line 207, in _run
    self.update_load_metrics()
  File "/Users/s.z/Code/ray/python/ray/autoscaler/_private/monitor.py", line 170, in update_load_metrics
    request, timeout=4)
  File "/Users/s.z/.pyenv/versions/3.7.10/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/s.z/.pyenv/versions/3.7.10/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1627003908.274325000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5420,"referenced_errors":[{"created":"@1627003908.274323000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}"
>

FAILED

# hang forever, rejecting SIGINT (Ctrl+C). SIGABRT (Ctrl+\) works.
```

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by suquark** [comment]
Close this issue, because it is outdated
