### ISSUE TITLE
Installation failing on MacOS 

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#1731]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Sierra 
- **Ray installed from (source or binary)**: source
- **Ray version**: current master (e3685fca5e8) merged onto barrachi:autoscaler 
- **Python version**: 3.6.3
- **Exact command to reproduce**: pip install -e .

### Describe the problem
Errored build.
[error.txt](https://github.com/ray-project/ray/files/1822197/error.txt)

### Source code / logs

Tail:
```
   [ 44%] Building C object src/common/CMakeFiles/common.dir/thirdparty/ae/ae.c.o
    [ 44%] Building C object src/common/CMakeFiles/common.dir/thirdparty/sha256.c.o
    [ 45%] Linking CXX static library libcommon.a
    [ 45%] Built target common
    [ 46%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/mock_gcs_client.cc.o
    /Users/rliaw/research/ray_directory/ray/src/ray/object_manager/object_manager.cc:302:67: error: cannot initialize a parameter of type 'std::shared_ptr<MutableBuffer> *' with an rvalue of type 'std::shared_ptr<Buffer> *'
          object_id.to_plasma_id(), object_size, NULL, metadata_size, &data);
                                                                      ^~~~~
    /Users/rliaw/research/ray_directory/ray/src/thirdparty/arrow/cpp/build/cpp-install/include/plasma/client.h:119:72: note: passing argument to parameter 'data' here
                    int64_t metadata_size, std::shared_ptr<MutableBuffer>* data);
                                                                           ^
    [ 46%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/task.cc.o
    1 error generated.
    [ 47%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/task_execution_spec.cc.o
    make[2]: *** [src/ray/CMakeFiles/ray_objlib.dir/object_manager/object_manager.cc.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    make[1]: *** [src/ray/CMakeFiles/ray_objlib.dir/all] Error 2
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/rliaw/research/ray_directory/ray/python/setup.py", line 138, in <module>
        license="Apache 2.0")
      File "/Users/rliaw/miniconda2/envs/ray/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/rliaw/miniconda2/envs/ray/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Users/rliaw/miniconda2/envs/ray/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/rliaw/miniconda2/envs/ray/lib/python3.6/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/Users/rliaw/miniconda2/envs/ray/lib/python3.6/site-packages/setuptools/command/develop.py", line 119, in install_for_development
        self.run_command('build_ext')
      File "/Users/rliaw/miniconda2/envs/ray/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/rliaw/miniconda2/envs/ray/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/rliaw/research/ray_directory/ray/python/setup.py", line 67, in run
        subprocess.check_call(["../build.sh", sys.executable])
      File "/Users/rliaw/miniconda2/envs/ray/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '/Users/rliaw/miniconda2/envs/ray/bin/python']' returned non-zero exit status 2.

    ----------------------------------------
```

**Comment by robertnishihara** [comment]
Can you do `cd thirdparty/build/arrow` and share the output of `git log`?

**Comment by robertnishihara** [comment]
Closing because this has probably been fixed. Feel free to reopen if it's still an issue.
