### ISSUE TITLE
Cluster failed to shutdown when # of nodes is large

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#17386]
Repo, start a cluster with more than 1000 nodes.
```
(anyscale) yic@ip-172-31-38-60:~/ray-w2/python (debug-info) $ ray down ~/check-config.yaml
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
Destroying cluster. Confirm [y/N]: y
Fetched IP: 54.202.153.35
Warning: Permanently added '54.202.153.35' (ECDSA) to the list of known hosts.
Did not find any active Ray processes.
Shared connection to 54.202.153.35 closed.
1050
Traceback (most recent call last):
  File "/mnt/yic/.local/anaconda3/envs/anyscale/bin/ray", line 33, in <module>
    sys.exit(load_entry_point('ray', 'console_scripts', 'ray')())
  File "/mnt/yic/ray-w2/python/ray/scripts/scripts.py", line 1944, in main
    return cli()
  File "/mnt/yic/.local/anaconda3/envs/anyscale/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/yic/.local/anaconda3/envs/anyscale/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/mnt/yic/.local/anaconda3/envs/anyscale/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/yic/.local/anaconda3/envs/anyscale/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/yic/.local/anaconda3/envs/anyscale/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/mnt/yic/ray-w2/python/ray/scripts/scripts.py", line 996, in down
    keep_min_workers)
  File "/mnt/yic/ray-w2/python/ray/autoscaler/_private/commands.py", line 450, in teardown_cluster
    provider.terminate_nodes(A)
  File "/mnt/yic/ray-w2/python/ray/autoscaler/_private/aws/node_provider.py", line 473, in terminate_nodes
    self.ec2.meta.client.terminate_instances(InstanceIds=node_ids)
  File "/mnt/yic/.local/anaconda3/envs/anyscale/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/mnt/yic/.local/anaconda3/envs/anyscale/lib/python3.7/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ResourceCountExceeded) when calling the TerminateInstances operation: You have exceeded the number of resources allowed in a single call of this type
```

**Comment by AmeerHajAli** [comment]
Thanks for filing this bug Yi.
Reassigning to @mwtian to triage.

**Comment by mwtian** [comment]
Looks like AWS throttling. Maybe we can add backoff + retry here.

**Comment by iycheng** [comment]
@mwtian Here I'm trying to stop a cluster with 1050 nodes. I think if it's less than 1000 it's fine. Maybe we should split all the nodes to shutdown into slices and shutdown them one by one. Basically: splitting + send request + [when failed backoff + retry]

**Comment by AmeerHajAli** [comment]
I think @ijrsvt might be familiar with this.

**Comment by ijrsvt** [comment]
So this is not actually throttling (as in the number of API calls is too high. This is just that `terminate_instances` can only handle up to 1000 nodes. We should probably just loop over chunks of up to 1000.

So change:
```
self.ec2.meta.client.stop_instances(InstanceIds=on_demand_ids)
```
to
```
for start in range(0,len(on_demand_ids, 1000):
   self.ec2.meta.client.stop_instances(InstanceIds=on_demand_ids[start, start+1000])
```

<img width="825" alt="Screen Shot 2021-07-28 at 8 53 54 PM" src="https://user-images.githubusercontent.com/21353794/127428989-244836a3-1a0b-4264-933e-0032e5344505.png">
[Docs link](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html?highlight=terminate_instances#EC2.Client.terminate_instances)
