### ISSUE TITLE
Can't resume from checkpoint.

### ISSUE THREAD

**Issue by souravraha** [ray-project/ray#17424]
https://github.com/ray-project/ray/blob/47cd0758299b430483ae41fd70e809d0330978a9/python/ray/tune/examples/mnist_pytorch_lightning.py#L186

When trying to resume from a interrupted trial, one gets the following attribute error:

> 2021-07-29 02:01:04,447	ERROR trial_runner.py:773 -- Trial train_mnist_tune_checkpoint_8eef9_00000: Error processing event.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trial_runner.py", line 739, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/ray_trial_executor.py", line 729, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/usr/local/lib/python3.7/dist-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ray/worker.py", line 1564, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): ray::ImplicitFunc.train_buffered() (pid=991, ip=172.28.0.2)
  File "python/ray/_raylet.pyx", line 534, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task.function_executor
  File "/usr/local/lib/python3.7/dist-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trainable.py", line 178, in train_buffered
    result = self.train()
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trainable.py", line 237, in train
    result = self.step()
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 366, in step
    self._report_thread_runner_error(block=True)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 513, in _report_thread_runner_error
    ("Trial raised an exception. Traceback:\n{}".format(err_tb_str)
ray.tune.error.TuneError: Trial raised an exception. Traceback:
ray::ImplicitFunc.train_buffered() (pid=991, ip=172.28.0.2)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 316, in entrypoint
    self._status_reporter.get_checkpoint())
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 580, in _trainable_func
    output = fn()
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/utils/trainable.py", line 339, in inner
    trainable(config, **fn_kwargs)
  File "<ipython-input-3-83ee6f83de0d>", line 185, in train_mnist_tune_checkpoint
AttributeError: can't set attribute

To reproduce, 
1. comment out line 289, 
2. start an experiment (on Colab),
3. interrupt runtime mid-experiment,
3. add 'resume='PROMPT'' option in line 270,
4. rerun, type 'y' when prompted.

I did some debugging: the problem seems to be that the 'current_epoch' attribute of a trainer object can't be assigned a value explicitly. I can say that this issue wasn't present even 5 days back. I could happily resume from checkpoints of incomplete experiments. Now I have to comment out line 186 before rerunning the experiment. The experiment does resume, but there is an expected mismatch between the 'training_iteration' in the summary table and the epoch number on the progress bar.

Can someone dig out how to reconcile the two going forward?

**Comment by RocketRider** [comment]
I am facing also restore issues in 1.5.0. But it looks a little different... So try 1.4.1 to see if it is an issue of the new version

**Comment by souravraha** [comment]
I shall try that out sometime. For now, I replaced lines 160-188 with the following snippet:
```    
    kwargs={
        'max_epochs' : num_epochs,
        # If fractional GPUs passed in, convert to int.
        'gpus' : math.ceil(num_gpus),
        'logger' : TensorBoardLogger(
            save_dir=tune.get_trial_dir(), name="", version="."),
        'progress_bar_refresh_rate' : 0,
        'callbacks' : [
            TuneReportCheckpointCallback(
                metrics={
                    "loss": "ptl/val_loss",
                    "mean_accuracy": "ptl/val_accuracy"
                },
                filename="checkpoint",
                on="validation_end")
        ]
    }

    if checkpoint_dir:
        kwargs['resume_from_checkpoint'] = os.path.join(checkpoint_dir, 'checkpoint')
    
    model = LightningMNISTClassifier(config=config, data_dir=data_dir)
    trainer = pl.Trainer(**kwargs)
```
According to [https://pytorch-lightning.readthedocs.io/en/stable/common/weights_loading.html#restoring-training-state](url), this should take care of loading checkpoints. However, there are two problems:

1. I am not sure if the model parameters are actually getting restored (since we aren't using model.load_from_checkpoint() explicitly).
2. Today as I ran this code, I can't seem to be able to restore CPU checkpoints on a GPU. Preliminary debugging indicates that tune.run() isn't passing 'resources_per_trial' correctly to the training function. (e.g. torch.cuda.device_count() gives 1 outside tune.run() and 0 when invoked from inside train_mnist_tune_checkpoint())
