### ISSUE TITLE
1.5.0 can't restore APPO TF checkpoint (1.4.1 works fine)

### ISSUE THREAD

**Issue by RocketRider** [ray-project/ray#17432]
I upgraded from 1.4.1 to 1.5.0 and can't restore my checkpoints. The checkpoint was created with 1.4.1.
I am using APPO and TF 2.4.2.

```
Traceback (most recent call last):
  File "test_rllib.py", line 143, in <module>
    agent.restore(checkpoint_file)
  File "C:\Users\Admin\anaconda3\envs\ray_tf2\lib\site-packages\ray\tune\trainable.py", line 377, in restore
    self.load_checkpoint(checkpoint_path)
  File "C:\Users\Admin\anaconda3\envs\ray_tf2\lib\site-packages\ray\rllib\agents\trainer.py", line 785, in load_checkpoint
    self.__setstate__(extra_data)
  File "C:\Users\Admin\anaconda3\envs\ray_tf2\lib\site-packages\ray\rllib\agents\trainer_template.py", line 235, in __setstate__
    Trainer.__setstate__(self, state)
  File "C:\Users\Admin\anaconda3\envs\ray_tf2\lib\site-packages\ray\rllib\agents\trainer.py", line 1545, in __setstate__
    self.workers.local_worker().restore(state["worker"])
  File "C:\Users\Admin\anaconda3\envs\ray_tf2\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1242, in restore
    self.policy_map[pid].set_state(state)
  File "C:\Users\Admin\anaconda3\envs\ray_tf2\lib\site-packages\ray\rllib\policy\tf_policy.py", line 532, in set_state
    super().set_state(state)
  File "C:\Users\Admin\anaconda3\envs\ray_tf2\lib\site-packages\ray\rllib\policy\policy.py", line 516, in set_state
    self.set_weights(state["weights"])
KeyError: 'weights'
```

**Comment by krfricke** [comment]
Hi @RocketRider, unfortunately we cannot guarantee checkpoint compatibility across releases. I would have to look into the code more closer to see what actually changed, but you might have to convert your checkpoint in some way to make it compatible with Ray 1.5.0 (or retrain, or continue using 1.4.1).

cc @sven1977

**Comment by RocketRider** [comment]
I think they should be converted automatically. 
What is the easiest way for me to convert them?
