### ISSUE TITLE
UnicodeEncodeError at cyrillic exception text

### ISSUE THREAD

**Issue by Akkarine** [ray-project/ray#17438]
### What is the problem?

looks like Ray can't serialize cyrillic exception text

Ray 1.5.0 installed on clean docker image `python:3.9.6-buster` with `pip install ray[default]`

```text
---------------------------------------------------------------------------
RayTaskError                              Traceback (most recent call last)
/tmp/ipykernel_46/1670236595.py in <module>
      4 
      5 futures = [your_function.remote(i) for i in range(2)]
----> 6 print(ray.get(futures))

/usr/local/lib/python3.9/site-packages/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
     80         if client_mode_should_convert():
     81             return getattr(ray, func.__name__)(*args, **kwargs)
---> 82         return func(*args, **kwargs)
     83 
     84     return wrapper

/usr/local/lib/python3.9/site-packages/ray/worker.py in get(object_refs, timeout)
   1562                     worker.core_worker.dump_object_store_memory_usage()
   1563                 if isinstance(value, RayTaskError):
-> 1564                     raise value.as_instanceof_cause()
   1565                 else:
   1566                     raise value

RayTaskError: ray::your_function() (pid=236, ip=172.17.0.2)
  File "python/ray/_raylet.pyx", line 534, in ray._raylet.execute_task
  File "/usr/local/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 330, in _function_with_tracing
    return function(*args, **kwargs)
  File "/tmp/ipykernel_46/1670236595.py", line 3, in your_function
Exception: Сообщение об ошибке
(pid=214) Traceback (most recent call last):
(pid=214)   File "python/ray/_raylet.pyx", line 523, in ray._raylet.execute_task
(pid=214)   File "python/ray/_raylet.pyx", line 530, in ray._raylet.execute_task
(pid=214)   File "python/ray/_raylet.pyx", line 534, in ray._raylet.execute_task
(pid=214)   File "/usr/local/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 330, in _function_with_tracing
(pid=214)     return function(*args, **kwargs)
(pid=214)   File "/tmp/ipykernel_46/1670236595.py", line 3, in your_function
(pid=214) Exception: Сообщение об ошибке
(pid=214) 
(pid=214) During handling of the above exception, another exception occurred:
(pid=214) 
(pid=214) Traceback (most recent call last):
(pid=214)   File "python/ray/_raylet.pyx", line 632, in ray._raylet.task_execution_handler
(pid=214)   File "python/ray/_raylet.pyx", line 486, in ray._raylet.execute_task
(pid=214)   File "python/ray/_raylet.pyx", line 590, in ray._raylet.execute_task
(pid=214)   File "/usr/local/lib/python3.9/site-packages/ray/_private/utils.py", line 103, in push_error_to_driver
(pid=214)     worker.core_worker.push_error(job_id, error_type, message, time.time())
(pid=214)   File "python/ray/_raylet.pyx", line 1776, in ray._raylet.CoreWorker.push_error
(pid=214) UnicodeEncodeError: 'ascii' codec can't encode characters in position 362-370: ordinal not in range(128)
(pid=214) 
(pid=214) During handling of the above exception, another exception occurred:
(pid=214) 
(pid=214) Traceback (most recent call last):
(pid=214)   File "python/ray/_raylet.pyx", line 653, in ray._raylet.task_execution_handler
(pid=214)   File "/usr/local/lib/python3.9/site-packages/ray/_private/utils.py", line 103, in push_error_to_driver
(pid=214)     worker.core_worker.push_error(job_id, error_type, message, time.time())
(pid=214)   File "python/ray/_raylet.pyx", line 1776, in ray._raylet.CoreWorker.push_error
(pid=214) UnicodeEncodeError: 'ascii' codec can't encode characters in position 483-491: ordinal not in range(128)
(pid=214) Exception ignored in: 'ray._raylet.task_execution_handler'
(pid=214) Traceback (most recent call last):
(pid=214)   File "python/ray/_raylet.pyx", line 653, in ray._raylet.task_execution_handler
(pid=214)   File "/usr/local/lib/python3.9/site-packages/ray/_private/utils.py", line 103, in push_error_to_driver
(pid=214)     worker.core_worker.push_error(job_id, error_type, message, time.time())
(pid=214)   File "python/ray/_raylet.pyx", line 1776, in ray._raylet.CoreWorker.push_error
(pid=214) UnicodeEncodeError: 'ascii' codec can't encode characters in position 483-491: ordinal not in range(128)
(pid=236) Traceback (most recent call last):
(pid=236)   File "python/ray/_raylet.pyx", line 523, in ray._raylet.execute_task
(pid=236)   File "python/ray/_raylet.pyx", line 530, in ray._raylet.execute_task
(pid=236)   File "python/ray/_raylet.pyx", line 534, in ray._raylet.execute_task
(pid=236)   File "/usr/local/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 330, in _function_with_tracing
(pid=236)     return function(*args, **kwargs)
(pid=236)   File "/tmp/ipykernel_46/1670236595.py", line 3, in your_function
(pid=236) Exception: Сообщение об ошибке
(pid=236) 
(pid=236) During handling of the above exception, another exception occurred:
(pid=236) 
(pid=236) Traceback (most recent call last):
(pid=236)   File "python/ray/_raylet.pyx", line 632, in ray._raylet.task_execution_handler
(pid=236)   File "python/ray/_raylet.pyx", line 486, in ray._raylet.execute_task
(pid=236)   File "python/ray/_raylet.pyx", line 590, in ray._raylet.execute_task
(pid=236)   File "/usr/local/lib/python3.9/site-packages/ray/_private/utils.py", line 103, in push_error_to_driver
(pid=236)     worker.core_worker.push_error(job_id, error_type, message, time.time())
(pid=236)   File "python/ray/_raylet.pyx", line 1776, in ray._raylet.CoreWorker.push_error
(pid=236) UnicodeEncodeError: 'ascii' codec can't encode characters in position 362-370: ordinal not in range(128)
(pid=236) 
(pid=236) During handling of the above exception, another exception occurred:
(pid=236) 
(pid=236) Traceback (most recent call last):
(pid=236)   File "python/ray/_raylet.pyx", line 653, in ray._raylet.task_execution_handler
(pid=236)   File "/usr/local/lib/python3.9/site-packages/ray/_private/utils.py", line 103, in push_error_to_driver
(pid=236)     worker.core_worker.push_error(job_id, error_type, message, time.time())
(pid=236)   File "python/ray/_raylet.pyx", line 1776, in ray._raylet.CoreWorker.push_error
(pid=236) UnicodeEncodeError: 'ascii' codec can't encode characters in position 483-491: ordinal not in range(128)
(pid=236) Exception ignored in: 'ray._raylet.task_execution_handler'
(pid=236) Traceback (most recent call last):
(pid=236)   File "python/ray/_raylet.pyx", line 653, in ray._raylet.task_execution_handler
(pid=236)   File "/usr/local/lib/python3.9/site-packages/ray/_private/utils.py", line 103, in push_error_to_driver
(pid=236)     worker.core_worker.push_error(job_id, error_type, message, time.time())
(pid=236)   File "python/ray/_raylet.pyx", line 1776, in ray._raylet.CoreWorker.push_error
(pid=236) UnicodeEncodeError: 'ascii' codec can't encode characters in position 483-491: ordinal not in range(128)
2021-07-29 21:17:19,570	ERROR worker.py:78 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::your_function() (pid=214, ip=172.17.0.2)
  File "python/ray/_raylet.pyx", line 534, in ray._raylet.execute_task
  File "/usr/local/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 330, in _function_with_tracing
    return function(*args, **kwargs)
  File "/tmp/ipykernel_46/1670236595.py", line 3, in your_function
Exception: Сообщение об ошибке
```

### Reproduction (REQUIRED)

```python
@ray.remote
def your_function(argument):
    raise Exception('Сообщение об ошибке')

futures = [your_function.remote(i) for i in range(2)]
print(ray.get(futures))
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by Akkarine** [comment]
Unstale
