### ISSUE TITLE
AttributeError: module 'aioredis' has no attribute 'create_redis_pool'

### ISSUE THREAD

**Issue by phosseini** [ray-project/ray#17475]
### What is the problem?

I'm using the following command to install Ray for hyperparametr tuning on a Google Colab:

`! pip install "ray[tune]"`

In particular, I'm using the Hugging Face's `hyperparameter_search` method in Trainer. So far I had no issue until the last time that I re-installed Ray. And now I'm getting the following error:

```
2021-07-30 19:41:49,014	ERROR services.py:1254 -- Failed to start the dashboard: Failed to start the dashboard, return code 1. The last 10 lines of /tmp/ray/session_2021-07-30_19-41-47_222866_75/logs/dashboard.log:
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/dashboard.py", line 118, in run
    await self.dashboard_head.run()
  File "/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/head.py", line 64, in run
    dashboard_consts.RETRY_REDIS_CONNECTION_TIMES)
  File "/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/utils.py", line 662, in get_aioredis_client
    return await aioredis.create_redis_pool(
AttributeError: module 'aioredis' has no attribute 'create_redis_pool'
2021-07-30 19:41:52,007	WARNING worker.py:1189 -- The agent on node 01151c700d47 failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py", line 354, in <module>
    loop.run_until_complete(agent.run())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py", line 130, in run
    dashboard_consts.RETRY_REDIS_CONNECTION_TIMES)
  File "/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/utils.py", line 662, in get_aioredis_client
    return await aioredis.create_redis_pool(
AttributeError: module 'aioredis' has no attribute 'create_redis_pool'

``` 

I wonder if this issue is related to `aioredis` or Ray? Let me know if I need to provide a code since the reproducible code is more than 50 lines.

**Comment by amogkam** [comment]
Hey @phosseini, `aioredis` just released a new version today which completely borks Ray. If you downgrade the `aioredis` version to less than 2 then this should work fine.

We just pinned the version today https://github.com/ray-project/ray/pull/17465, so you could also install Ray from the latest wheels.
