### ISSUE TITLE
Redis WRONGTYPE issue with GET with cross-arch Ray clusters

### ISSUE THREAD

**Issue by reisub0** [ray-project/ray#17480]
### What is the problem?
Hello, I am trying to get a cross-architectural Ray cluster working on Kubernetes using nodes of both arm64 as well as aarch64 types. 

I understand that there's a lot of work to be done for Ray and that the support for such use cases might not be given high priority.

Since there is no currently existing "supported" way of building Ray wheels for the Raspberry Pi, and correspondingly, no official ray-project/ray arm64 image, I had to build my own with Python 3.8.10. 

If interested, you can check out the images I built for both amd64 and aarch64 at [this link](https://hub.docker.com/r/reisub0/ray/tags?page=1&ordering=last_updated).

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python version: 3.8.10
Ray-version: 2.0.0.dev0
OS: ubuntu (From python:3.8.10 docker image)

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
```
# On an amd64 machine
$ docker run -p6379:6379 -it  reisub0/ray:amd64 bash
root@34a2e631296a:/# ray start --head
Local node IP: 172.17.0.3
2021-07-31 14:47:44,216	INFO services.py:1254 -- View the Ray dashboard at http://127.0.0.1:8265
2021-07-31 14:47:44,218	WARNING services.py:1721 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=5.14gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='172.17.0.3:6379' --redis-password='5241590000000000'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='5241590000000000')
  
  If connection fails, check your firewall settings and network configuration.
  
  To terminate the Ray runtime, run
    ray stop

```
```
# On the arm64 machine (on the same network, of course)
$ docker run -it reisub0/ray:aarch64 bash
root@7c66d1a0060f:/# ray start --address="$RAY_HEAD:6379" --redis-password='5241590000000000'
Local node IP: 172.17.0.3
Traceback (most recent call last):
  File "/usr/local/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1526, in main
    return cli()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/scripts/scripts.py", line 651, in start
    node = ray.node.Node(
  File "/usr/local/lib/python3.8/site-packages/ray/node.py", line 170, in __init__
    self._init_temp(redis_client)
  File "/usr/local/lib/python3.8/site-packages/ray/node.py", line 280, in _init_temp
    session_dir = _get_with_retry(redis_client, "session_dir")
  File "/usr/local/lib/python3.8/site-packages/ray/node.py", line 40, in _get_with_retry
    result = redis_client.get(key)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
```

This error seems to appears **if and only if** the head node and the worker node are of different archs. If both are of the same arch, they are able to communicate fine.

If the head node is arm64 instead, a slightly different error with `HGET` appears instead
```
Traceback (most recent call last):
  File "/usr/local/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1959, in main
    return cli()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/scripts/scripts.py", line 736, in start
    node = ray.node.Node(
  File "/usr/local/lib/python3.8/site-packages/ray/node.py", line 184, in __init__
    self._init_temp(redis_client)
  File "/usr/local/lib/python3.8/site-packages/ray/node.py", line 309, in _init_temp
    session_dir = _hget_with_retry(redis_client, "session_dir",
  File "/usr/local/lib/python3.8/site-packages/ray/node.py", line 59, in _hget_with_retry
    result = redis_client.hget(key, field)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3010, in hget
    return self.execute_command('HGET', name, key)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
```

It's quite a strange issue and please let me know if anything is not clear or need further information

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
@wuisawesome any hint?
