### ISSUE TITLE
new dashboard agent port conflict issues

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#17498]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 3.7

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

Users are getting a few different error messages, this is one that’s spamming me a lot:
```
(pid=4670) (raylet, ip=...) E0802 07:40:46.542383278   63998 server_chttp2.cc:49]        {"created":"@1627890046.542339446","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":872,"referenced_errors":[{"created":"@1627890046.542335288","description":"Failed to add any wildcard listeners","file":"src/core/lib/iomgr/tcp_server_posix.cc","file_line":340,"referenced_errors":[{"created":"@1627890046.542316804","description":"Address family not supported by protocol","errno":97,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":446,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::]:59332"},{"created":"@1627890046.542334837","description":"Unable to configure socket","fd":19,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":216,"referenced_errors":[{"created":"@1627890046.542332583","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]}]}]}
(pid=4670) (raylet, ip=...) Traceback (most recent call last):
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 381, in <module>
(pid=4670) (raylet, ip=...)     raise e
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 366, in <module>
(pid=4670) (raylet, ip=...)     logging_params=logging_params)
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 94, in __init__
(pid=4670) (raylet, ip=...)     f"[::]:{self.dashboard_agent_port}")
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/grpc/aio/_server.py", line 84, in add_insecure_port
(pid=4670) (raylet, ip=...)     address, self._server.add_insecure_port(_common.encode(address)))
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/grpc/_common.py", line 166, in validate_port_binding_result
(pid=4670) (raylet, ip=...)     raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
```

Also, --include-dashboard=False does not flag this off.

cc @fyrestone @rkooo567

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
