### ISSUE TITLE
Travis test failure in MultiNodeTest.testDriverExitingQuickly.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1750]
Not sure exactly what the issue is, but this was probably introduced in #1668.

```
======================================================================
ERROR: testDriverExitingQuickly (__main__.MultiNodeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/multi_node_test.py", line 192, in testDriverExitingQuickly
    out = run_string_as_driver(driver_script2)
  File "test/multi_node_test.py", line 29, in run_string_as_driver
    f.name]).decode("ascii")
  File "/home/travis/miniconda/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/travis/miniconda/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/travis/miniconda/bin/python', '/tmp/tmp7o59d0ht']' returned non-zero exit status 1.
```

**Comment by pcmoritz** [comment]
Something similar seems to be happening more frequently recently, see for example https://api.travis-ci.org/v3/job/382036306/log.txt

======================================================================
ERROR: testDriverExitingQuickly (__main__.MultiNodeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/multi_node_test.py", line 194, in testDriverExitingQuickly
    out = run_string_as_driver(driver_script2)
  File "test/multi_node_test.py", line 29, in run_string_as_driver
    out = subprocess.check_output([sys.executable, f.name]).decode("ascii")
  File "/home/travis/miniconda/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['/home/travis/miniconda/bin/python', '/tmp/tmpxEf8ub']' returned non-zero exit status -6
