### ISSUE TITLE
Streaming shuffle script is broken locally

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#17514]
### What is the problem?

On 1.5.0 or newer

### Reproduction (REQUIRED)
```
❯ python -m ray.experimental.shuffle --num-cpus=32 --num-partitions=200 --partition-size=500e6 --object-store-memory=20e9
Start a new cluster...
2021-08-02 11:09:42,860	INFO services.py:1245 -- View the Ray dashboard at http://127.0.0.1:8265
Traceback (most recent call last):
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jiaodong/Workspace/ray/python/ray/experimental/shuffle.py", line 318, in <module>
    main()
  File "/Users/jiaodong/Workspace/ray/python/ray/experimental/shuffle.py", line 258, in main
    tracker = _StatusTracker.remote()
  File "/Users/jiaodong/Workspace/ray/python/ray/actor.py", line 423, in remote
    return self._remote(args=args, kwargs=kwargs)
  File "/Users/jiaodong/Workspace/ray/python/ray/util/tracing/tracing_helper.py", line 367, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/Users/jiaodong/Workspace/ray/python/ray/actor.py", line 726, in _remote
    actor_id = worker.core_worker.create_actor(
  File "python/ray/_raylet.pyx", line 1320, in ray._raylet.CoreWorker.create_actor
TypeError: create_actor() takes exactly 18 positional arguments (14 given)
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
This test is not needed anymore
