### ISSUE TITLE
[autoscaler] setup command failure bricks cluster

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#17525]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* master

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

Whenever I fail to update my cluster, the cluster becomes "unfindable/unreachable" for Ray commands. For example, `ray attach` and `ray exec` become broken.

Rather, the expected behavior is that `ray attach` and `ray exec` should work even if the setup commands didn't work properly.

cc @DmitriGekhtman @ijrsvt 

```
  New status: update-failed
  !!!
  SSH command failed.
  !!!

  Failed to setup head node.
(horovod) ➜  horovod git:(main) ✗ ray submit richard.yaml  mini_shuffle_s3.py -- --address=auto
Converting legacy cluster config to a multi node type cluster config. Multi-node-type cluster configs are the recommended format for configuring Ray clusters. See the docs for more information:
https://docs.ray.io/en/master/cluster/config.html#full-configuration
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
Head node (i-0c371fe1903227c86) is in state update-failed.
Traceback (most recent call last):
  File "/Users/rliaw/miniconda3/envs/horovod/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/Users/rliaw/miniconda3/envs/horovod/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1959, in main
    return cli()
  File "/Users/rliaw/miniconda3/envs/horovod/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rliaw/miniconda3/envs/horovod/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/rliaw/miniconda3/envs/horovod/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rliaw/miniconda3/envs/horovod/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rliaw/miniconda3/envs/horovod/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/rliaw/miniconda3/envs/horovod/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1258, in submit
    down=False)
  File "/Users/rliaw/miniconda3/envs/horovod/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 1127, in rsync
    config, config_file, override_cluster_name, create_if_needed=False)
  File "/Users/rliaw/miniconda3/envs/horovod/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 1228, in _get_running_head_node
    config["cluster_name"]))
RuntimeError: Head node of cluster (shuffling-data-loader-horovod) not found!
(horovod) ➜  horovod git:(main) ✗
```

**Comment by ijrsvt** [comment]
I think this just requires changing the signature of `_get_running_head_node` to allow getting an uninitialized node.
