### ISSUE TITLE
azure authentication problem in autoscaler

### ISSUE THREAD

**Issue by sofglide** [ray-project/ray#17548]
### What is the problem?
posting here after discussing with @richardliaw on Slack
*Ray 1.5.0, Python 3.8
When creating a cluster on Azure, the head node complains about missing credentials.

This disappears if I attach to the head and run `az login` from there but when the token expires, it will happen again
### Reproduction (REQUIRED)
run
```
ray login
az account set -s xxx-xxx-xxx-xxx
ray up ray-azure-cluster.yaml  --no-config-cache
```
where `ray-azure-cluster.yaml` is:
```

# An unique identifier for the head node and workers of this cluster.
cluster_name: test-cluster

# The maximum number of workers nodes to launch in addition to the head
# node.
max_workers: 4

# The autoscaler will scale up the cluster faster with higher upscaling speed.
# E.g., if the task requires adding more nodes then autoscaler will gradually
# scale up the cluster in chunks of upscaling_speed*currently_running_nodes.
# This number should be > 0.
upscaling_speed: 1.0

# This executes all commands on all nodes in the docker container,
# and opens all the necessary ports to support the Ray cluster.
# Empty object means disabled.
docker:
    image: "rayproject/ray-ml:1.5.0-py38-gpu" # You can change this to latest-cpu if you don't need GPU support and want a faster startup
    # image: rayproject/ray:latest-gpu   # use this one if you don't need ML dependencies, it's faster to pull
    container_name: "ray_container"
    # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
    # if no cached version is present.
    pull_before_run: True
    run_options:   # Extra options to pass into "docker run"
        - --ulimit nofile=65536:65536

    # Example of running a GPU head with CPU workers
    # head_image: "rayproject/ray-ml:latest-gpu"
    # Allow Ray to automatically detect GPUs

    # worker_image: "rayproject/ray-ml:latest-cpu"
    # worker_run_options: []

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 1

# Cloud-provider specific configuration.
provider:
    type: azure
    # https://azure.microsoft.com/en-us/global-infrastructure/locations
    location: westeurope
    resource_group: ai-ray-cluster
    # set subscription id otherwise the default from az cli will be used
    # subscription_id: xxxx-xxxx-xxxx-xxxx

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
    # you must specify paths to matching private and public key pair files
    # use `ssh-keygen -t rsa -b 4096` to generate a new ssh key pair
    ssh_private_key: ~/.ssh/id_rsa
    # changes to this should match what is specified in file_mounts
    ssh_public_key: ~/.ssh/id_rsa.pub

# More specific customization to node configurations can be made using the ARM template azure-vm-template.json file
# See documentation here: https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2019-03-01/virtualmachines
# Changes to the local file will be used during deployment of the head node, however worker nodes deployment occurs
# on the head node, so changes to the template must be included in the wheel file used in setup_commands section below

# Tell the autoscaler the allowed node types and the resources they provide.
# The key is the name of the node type, which is just for debugging purposes.
# The node config specifies the launch config and physical instance type.
available_node_types:
    ray.head.default:
        # The minimum number of worker nodes of this type to launch.
        # This number should be >= 0.
        min_workers: 0
        # The maximum number of worker nodes of this type to launch.
        # This takes precedence over min_workers.
        max_workers: 0
        # The resources provided by this node type.
        resources: {"CPU": 2}
        # Provider-specific config, e.g. instance type.
        node_config:
            azure_arm_parameters:
                vmSize: Standard_D2s_v3
                # List images https://docs.microsoft.com/en-us/azure/virtual-machines/linux/cli-ps-findimage
                imagePublisher: microsoft-dsvm
                imageOffer: ubuntu-1804
                imageSku: 1804-gen2
                imageVersion: 21.07.12

    ray.worker.default:
        # The minimum number of worker nodes of this type to launch.
        # This number should be >= 0.
        min_workers: 0
        # The maximum number of worker nodes of this type to launch.
        # This takes precedence over min_workers.
        max_workers: 2
        # The resources provided by this node type.
        resources: {"CPU": 2}
        # Provider-specific config, e.g. instance type.
        node_config:
            azure_arm_parameters:
                vmSize: Standard_D2s_v3
                # List images https://docs.microsoft.com/en-us/azure/virtual-machines/linux/cli-ps-findimage
                imagePublisher: microsoft-dsvm
                imageOffer: ubuntu-1804
                imageSku: 1804-gen2
                imageVersion: 21.07.12
                # optionally set priority to use Spot instances
                # priority: Spot
                # set a maximum price for spot instances if desired
                # billingProfile:
                #     maxPrice: -1

# Specify the node type of the head node (as configured above).
head_node_type: ray.head.default

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {
#    "/path1/on/remote/machine": "/path1/on/local/machine",
     "~/.ssh/id_rsa.pub": "~/.ssh/id_rsa.pub"
}

# Files or directories to copy from the head node to the worker nodes. The format is a
# list of paths. The same path on the head node will be copied to the worker node.
# This behavior is a subset of the file_mounts behavior. In the vast majority of cases
# you should just use file_mounts. Only use this if you know what you're doing!
cluster_synced_files: []

# Whether changes to directories in file_mounts or cluster_synhttps://www.youtube.com/watch?v=GajbZY0l7oYchttps://www.youtube.com/watch?v=GajbZY0l7oYed_files in the head node
# should sync to the worker node continuously
file_mounts_sync_continuously: False

# Patterns for files to exclude when running rsync up or rsync down
rsync_exclude:
    - "**/.git"
    - "**/.git/**"
    - ".venv"
    - ".venv/**"

# Pattern files to use for filtering out files when running rsync up or rsync down. The file is searched for
# in the source directory and recursively through all subdirectories. For example, if .gitignore is provided
# as a value, the behavior will match git's behavior for finding and using .gitignore files.
rsync_filter:
    - ".gitignore"

# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
initialization_commands:
    # enable docker setup
    - sudo usermod -aG docker $USER || true
    - sleep 10  # delay to avoid docker permission denied errors
    # get rid of annoying Ubuntu message
    - touch ~/.sudo_as_admin_successful

# List of shell commands to run to set up nodes.
# NOTE: rayproject/ray-ml:latest has ray latest bundled
setup_commands:
    - pip install -U azure-cli==2.27.0  azure-mgmt-resource==18.0.0
    # Note: if you're developing Ray, you probably want to create a Docker image that
    # has your Ray repo pre-cloned. Then, you can replace the pip installs
    # below with a git checkout <your_sha> (and possibly a recompile).
    # To run the nightly version of ray (as opposed to the latest), either use a rayproject docker image
    # that has the "nightly" (e.g. "rayproject/ray-ml:nightly-gpu") or uncomment the following line:
    # - pip install -U "ray[default] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl"

# Custom commands that will be run on the head node after common setup.
# NOTE: rayproject/ray-ml:latest has azure packages bundled
head_setup_commands: []
    # - pip install -U azure-cli-core==2.22.0 azure-mgmt-compute==14.0.0 azure-mgmt-msi==1.0.0 azure-mgmt-network==10.2.0 azure-mgmt-resource==13.0.0

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076

head_node: {}
worker_nodes: {}

```
then run
```
ray exec ray-azure-cluster.yaml 'tail -n 100 -f /tmp/ray/session_latest/logs/monitor.log'
```
the error is:
```
2021-08-03 12:14:37,062 INFO monitor.py:402 -- Ray commit: ddad6a2458bded21035797ec84ba67b8a8c15ca5
2021-08-03 12:14:37,062 INFO monitor.py:403 -- Monitor started with command: ['/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py', '--logs-dir=/tmp/ray/sessi
on_2021-08-03_12-14-35_070853_2090/logs', '--redis-address=10.244.0.4:6379', '--logging-rotate-bytes=536870912', '--logging-rotate-backup-count=5', '--autoscaling-config=/home/ray/ray_bootst
rap_config.yaml', '--redis-password=5241590000000000', '--monitor-ip=10.244.0.4']
2021-08-03 12:14:37,099 INFO monitor.py:141 -- Starting autoscaler metrics server on port 44217
2021-08-03 12:14:37,145 INFO monitor.py:151 -- Monitor: Started
2021-08-03 12:14:49,829 INFO _session.py:58 -- Failed to load or parse file /home/ray/.azure/azureProfile.json. It will be overridden by default settings.
2021-08-03 12:14:49,830 INFO _session.py:58 -- Failed to load or parse file /home/ray/.azure/az.json. It will be overridden by default settings.
2021-08-03 12:14:49,830 INFO _session.py:58 -- Failed to load or parse file /home/ray/.azure/az.sess. It will be overridden by default settings.
2021-08-03 12:14:49,830 INFO _session.py:58 -- Failed to load or parse file /home/ray/.azure/commandIndex.json. It will be overridden by default settings.
2021-08-03 12:14:49,830 INFO _session.py:58 -- Failed to load or parse file /home/ray/.azure/versionCheck.json. It will be overridden by default settings.
2021-08-03 12:14:49,950 INFO node_provider.py:64 -- CLI profile authentication failed. Trying MSI
2021-08-03 12:14:50,444 ERROR monitor.py:285 -- Error in monitor loop
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/_azure/node_provider.py", line 54, in __init__
    self.compute_client = get_client_from_cli_profile(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/azure/common/client_factory.py", line 83, in get_client_from_cli_profile
    credentials, subscription_id, tenant_id = get_azure_cli_credentials(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/azure/common/credentials.py", line 98, in get_azure_cli_credentials
    cred, subscription_id, tenant_id = profile.get_login_credentials(resource=resource)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 553, in get_login_credentials
    account = self.get_subscription(subscription_id)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 512, in get_subscription
    raise CLIError(_AZ_LOGIN_MESSAGE)
knack.util.CLIError: Please run 'az login' to setup account.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 316, in run
    self._initialize_autoscaler()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 158, in _initialize_autoscaler
    self.autoscaler = StandardAutoscaler(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/autoscaler.py", line 95, in __init__
    self.reset(errors_fatal=True)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/autoscaler.py", line 586, in reset
    raise e                                    
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/autoscaler.py", line 537, in reset
    self.provider = _get_node_provider(self.config["provider"],
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/providers.py", line 201, in _get_node_provider
    new_provider = provider_cls(provider_config, cluster_name)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/_azure/node_provider.py", line 67, in __init__
    self.compute_client = ComputeManagementClient(
TypeError: __init__() missing 1 required positional argument: 'credential'
```

The problem is fixed if we attach to head and run `az login`:
```
ray attach ray-azure-cluster.yaml
az login
```

But the problems comes back at the token expiry.

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
@eisber could you take a look at this?

**Comment by eisber** [comment]
@yugangw-msft we're using azure cli context for authentication (see [here](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/_private/_azure/node_provider.py#L54)). Is there a method we can call (or a background process) that can refresh the AAD token?

**Comment by eisber** [comment]
FYI @gramhagen

**Comment by gramhagen** [comment]
Looks like the fallback to msi credential is failing because the sdk changed the name of the input variable. Might be better to replace this section of the nice provider with DefaultAzureCredential resolver from azure-identity.

**Comment by sofglide** [comment]
It seems that I fixed this issue with the following lines in ray-azure-cluster.yaml
```
setup_commands:
    - pip install -U azure-cli-core==2.22.0 azure-mgmt-compute==14.0.0 azure-mgmt-msi==1.0.0 azure-mgmt-network==10.2.0 azure-mgmt-resource==13.0.0
```
No login errors with this

Is it possible to have these packages in the docker image or the requirements documented somewhere?
