### ISSUE TITLE
[rllib] CQL GPU error when num_gpus=1

### ISSUE THREAD

**Issue by juliusfrost** [ray-project/ray#17667]
### What is the problem?

I'm getting the following error when I try running CQL. It just started happening this week while I was on the nightly wheels.

```
Traceback (most recent call last):
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\tune\trial_runner.py", line 739, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\tune\ray_trial_executor.py", line 746, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\_private\client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\worker.py", line 1621, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::CQL.__init__()[39m (pid=6792, ip=192.168.50.5)
  File "python\ray\_raylet.pyx", line 536, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 486, in ray._raylet.execute_task.function_executor
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\_private\function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\agents\trainer_template.py", line 136, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\agents\trainer.py", line 592, in __init__
    super().__init__(config, logger_creator)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\tune\trainable.py", line 103, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\agents\trainer_template.py", line 146, in setup
    super().setup(config)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\agents\trainer.py", line 739, in setup
    self._init(self.config, self.env_creator)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\agents\trainer_template.py", line 170, in _init
    self.workers = self._make_workers(
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\agents\trainer.py", line 821, in _make_workers
    return WorkerSet(
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 103, in __init__
    self._local_worker = self._make_worker(
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 399, in _make_worker
    worker = cls(
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 580, in __init__
    self._build_policy_map(
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1375, in _build_policy_map
    self.policy_map.create_policy(name, orig_cls, obs_space, act_space,
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\policy\policy_map.py", line 136, in create_policy
    self[policy_id] = class_(observation_space, action_space,
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\policy\policy_template.py", line 279, in __init__
    self._initialize_loss_from_dummy_batch(
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\policy\policy.py", line 793, in _initialize_loss_from_dummy_batch
    self._loss(self, self.model, self.dist_class, train_batch)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\agents\cql\cql_torch_policy.py", line 159, in cql_loss
    q_tp1 = policy.target_model.get_q_values(target_model_out_tp1, policy_tp1)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\agents\sac\sac_torch_model.py", line 215, in get_q_values
    return self._get_q_value(model_out, actions, self.q_net)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\agents\sac\sac_torch_model.py", line 260, in _get_q_value
    out, _ = net(input_dict, [], None)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\models\modelv2.py", line 230, in __call__
    res = self.forward(restored, state or [], seq_lens)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\models\torch\fcnet.py", line 124, in forward
    self._features = self._hidden_layers(self._last_flat_in)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\ray\rllib\models\torch\misc.py", line 160, in forward
    return self._model(x)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\torch\nn\modules\linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\Julius\Anaconda3\envs\ray-dev\lib\site-packages\torch\nn\functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument mat1 in method wrapper_addmm)
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
rllib train --run=CQL --env=Pendulum-v0 --config="{""num_gpus"":1, ""framework"":""torch""}"
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by sven1977** [comment]
This PR here fixes the problem:
https://github.com/ray-project/ray/pull/17742

@juliusfrost
