### ISSUE TITLE
cancelling a task causes grpc._channel._InactiveRpcError

### ISSUE THREAD

**Issue by auderson** [ray-project/ray#17673]
Hi, I'm running a ray cluster on k8s. Both the server and my client's version is 1.5.1.
```python
ray.__version__
'1.5.1'
```

### Reproduction (REQUIRED)

```python
import ray
import time

# connect to a cluster via client mode
ray.init('ray://####:10001')


@ray.remote
class Actor:
    def __init__(self):
        self.records = {}

    def read_record(self, key, wait=False):
        if wait:  # will loop forever if wait is True
            while key not in self.records:
                time.sleep(0.1)
        return self.records[key]


actor = Actor.options(name='test').remote()
```
First I start an actor that stores records in a dict, and now I want to read the record.

```python
ref = actor.read_record.remote('a')
ray.get(ref)
```
This will correctly raise a `KeyError`

```python
ref = actor.read_record.remote('a', wait=True)
ray.get(ref, timeout=1)
```
This will correctly raise a `GetTimeoutError`

Now note that the actor is running in the while loop forever because I specified `wait=True`, and I wan't to stop it with `ray.cancel`:

```python
ray.cancel(ref)
```

This throws the following error:
```
>>> ray.cancel(ref)
Traceback (most recent call last):
  File "/home/auderson/miniconda3/lib/python3.8/site-packages/ray/util/client/worker.py", line 440, in terminate_task
    self.server.Terminate(term, metadata=self.metadata)
  File "/home/auderson/miniconda3/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/auderson/miniconda3/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Failed to serialize response!"
	debug_error_string = "{"created":"@1628503752.472660555","description":"Error received from peer ipv4:####:10001","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Failed to serialize response!","grpc_status":13}"
>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/auderson/miniconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-6c9d78c1a68b>", line 1, in <module>
    ray.cancel(ref)
  File "/home/auderson/miniconda3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 81, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/home/auderson/miniconda3/lib/python3.8/site-packages/ray/util/client/api.py", line 170, in cancel
    return self.worker.terminate_task(obj, force, recursive)
  File "/home/auderson/miniconda3/lib/python3.8/site-packages/ray/util/client/worker.py", line 442, in terminate_task
    raise decode_exception(e.details())
  File "/home/auderson/miniconda3/lib/python3.8/site-packages/ray/util/client/worker.py", line 585, in decode_exception
    data = base64.standard_b64decode(data)
  File "/home/auderson/miniconda3/lib/python3.8/base64.py", line 105, in standard_b64decode
    return b64decode(s)
  File "/home/auderson/miniconda3/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (25) cannot be 1 more than a multiple of 4
```
Then the actor is seemly dead, any call to it will be blocked.

I notice the doc from `ray.cancel` says 'Only non-actor tasks can be canceled'. Is that the reason for this? How can I stop a method that's running forever in a loop?

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
Yeah ray.cancel() is basically causing interrupt to the process, so it shouldn't be used for actors. It can easily corrupt the actor states.

For your case, there's no known support, but you can actually just implement it in this way I believe.

Also note that running a loop inside an actor can be problematic because actors are running in a single thread (it will basically not be able to process any more request after running a loop). To get around this you can use an async actor.

```python3
@ray.remote
class Actor:
    def __init__(self):
        self.records = {}
        self.reading = True

    async def read_record(self, key, wait=False):
        if wait:  # will loop forever if wait is True
            self.reading = True
            while key not in self.records and self.reading:
                await asyncio.sleep(0.1) # if you do this, actors can still receive tasks while running loop because it can do context switching using event loops
        return self.records[key]

    async def stop_read(self):
        self.reading = False # After this, self.reading will be False, and after the context is switched back to `read_record`'s loop, that will stop because self.reading = False
```

**Comment by auderson** [comment]
@rkooo567 I see, thanks for your advice
