### ISSUE TITLE
[rllib] Assertion error caused by rollout_fragment_length in simple_list_collector.py

### ISSUE THREAD

**Issue by quao627** [ray-project/ray#17695]
Hi, I have been training a custom environment with the PPO policy using a custom model for around 30 iterations and then I got interrupted by an assertion error caused by rollout_fragment_length in simple_list_collector.py. 
Currently, I set sgd_minibatch_size as "128", timesteps_per_iteration as "600", and "num_sgd_iter" as 80. Other parameters are set to default. I am not sure if the error is caused by this particular setting. Do you have any advice? Thank you very much in advance!

The full trackback is attached here: 
Traceback (most recent call last):
  File "PPO+embedding_ray.py", line 482, in <module>
    result = trainer.train()
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 605, in train
    raise e
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 594, in train
    result = Trainable.train(self)
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 232, in train
    result = self.step()
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 173, in step
    res = next(self.train_exec_impl)
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 876, in apply_flatten
    for item in it:
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 828, in add_wait_hooks
    item = next(it)
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 471, in base_iterator
    yield ray.get(futures, timeout=timeout)
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1495, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): ray::RolloutWorker.par_iter_next() (pid=80731, ip=192.168.86.24)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 1151, in par_iter_next
    return next(self.local_it)
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 333, in gen_rollouts
    yield self.sample()
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 726, in sample
    batches = [self.input_reader.next()]
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 99, in next
    batches = [self.get_data()]
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 226, in get_data
    item = next(self.rollout_provider)
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 616, in _env_runner
    sample_collector=sample_collector,
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 964, in _process_observations
    sample_collector.try_build_truncated_episode_multi_agent_batch()
  File "/Users/aoqu/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/collectors/simple_list_collector.py", line 748, in try_build_truncated_episode_multi_agent_batch
    self.rollout_fragment_length
AssertionError

**Comment by sven1977** [comment]
Hey @quao627 , could you post a simple reproduction script here that we can use to debug this? Thanks.
