### ISSUE TITLE
CalledProcessError when install ray from source on OS X

### ISSUE THREAD

**Issue by nickyongzhang** [ray-project/ray#1776]
### System information
- **OS Platform and Distribution**: OS X 10.12.6
- **Ray installed from (source or binary)**: source master
- **Ray version**: --
- **Python version**: 3.6
- **Exact command to reproduce**: pip install -e . --verbose

### Describe the problem

When installing ray from source on my Mac, I came across with the following errors. I was following the  [documentation](http://ray.readthedocs.io/en/latest/installation.html).

### Source code / logs

pip install -e . --verbose

```
[ 33%] Built target flatbuffers_ep
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/yong.zhang/ray/python/setup.py", line 138, in <module>
        license="Apache 2.0")
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/yong.zhang/ray/python/setup.py", line 67, in run
        subprocess.check_call(["../build.sh", sys.executable])
      File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '/usr/local/opt/python/bin/python3.6']' returned non-zero exit status 2.
Cleaning up...
Command "/usr/local/opt/python/bin/python3.6 -c "import setuptools, tokenize;__file__='/Users/yong.zhang/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/yong.zhang/ray/python/
```

**Comment by robertnishihara** [comment]
I think something went wrong earlier on in installation. Can you share the
full output?

**Comment by nickyongzhang** [comment]
Thank you the reply @robertnishihara 
Below is the full log of installation.

[install_log.txt](https://github.com/ray-project/ray/files/1844978/install_log.txt)

**Comment by pcmoritz** [comment]
The error is here:
```
CMake Error at /Users/yong.zhang/ray/thirdparty/build/arrow/cpp/build/snappy_ep-prefix/src/snappy_ep-stamp/snappy_ep-configure-RELEASE.cmake:16 (message):
      Command failed: 77

       './configure' '--with-pic' '--prefix=/Users/yong.zhang/ray/thirdparty/build/arrow/cpp/build/snappy_ep/src/snappy_ep-install'

      See also

        /Users/yong.zhang/ray/thirdparty/build/arrow/cpp/build/snappy_ep-prefix/src/snappy_ep-stamp/snappy_ep-configure-*.log
```

So snappy failed to compile. Can you share the content of the files `/Users/yong.zhang/ray/thirdparty/build/arrow/cpp/build/snappy_ep-prefix/src/snappy_ep-stamp/snappy_ep-configure-*.log`?

**Comment by nickyongzhang** [comment]
I have looked into the log and found that the C compiler fails to work, but I lost myself again and need help. Please check the related log files
[snappy_ep-configure-out.log](https://github.com/ray-project/ray/files/1845315/snappy_ep-configure-out.log)
[snappy_ep-configure-err.log](https://github.com/ray-project/ray/files/1845316/snappy_ep-configure-err.log)
[config.log](https://github.com/ray-project/ray/files/1845320/config.log)

**Comment by nickyongzhang** [comment]
I happen to come across another similar C compiler fail issue and l find that it is caused by Xcode 9.
Reseting the command line solves the problem
`$sudo xcode-select -s /Library/Developer/CommandLineTools`
As the problem is solved, I will close the issue.
