### ISSUE TITLE
[rllib] PPO does not work, it raises a TypeError unexpected keyword argument 'dtype'.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1780]
Running

```
python ray/python/ray/rllib/train.py --env=CartPole-v0 --run=PPO --config='{"num_workers": 1}'
```

both on Ubuntu and Mac (on the current master), fails with

```
Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/worker.py", line 821, in _process_task
    *arguments)
  File "/home/ubuntu/ray/python/ray/actor.py", line 212, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/ubuntu/ray/python/ray/rllib/agent.py", line 84, in __init__
    Trainable.__init__(self, config, registry, logger_creator)
  File "/home/ubuntu/ray/python/ray/tune/trainable.py", line 89, in __init__
    self._setup()
  File "/home/ubuntu/ray/python/ray/rllib/agent.py", line 107, in _setup
    self._init()
  File "/home/ubuntu/ray/python/ray/rllib/ppo/ppo.py", line 100, in _init
    self.registry, self.env_creator, self.config, self.logdir, False)
  File "/home/ubuntu/ray/python/ray/rllib/ppo/ppo_evaluator.py", line 45, in __init__
    registry, env_creator(config["env_config"]), config["model"])
  File "/home/ubuntu/ray/python/ray/rllib/models/catalog.py", line 231, in get_preprocessor_as_wrapper
    return _RLlibPreprocessorWrapper(env, preprocessor)
  File "/home/ubuntu/ray/python/ray/rllib/models/catalog.py", line 270, in __init__
    -1.0, 1.0, preprocessor.shape, dtype=np.float32)
TypeError: __init__() got an unexpected keyword argument 'dtype'
```

Full output

```
$ python ray/python/ray/rllib/train.py --env=CartPole-v0 --run=PPO --config='{"num_workers": 1}'
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:28427 to respond...
Waiting for redis server at 127.0.0.1:54032 to respond...
Starting local scheduler with the following resources: {'CPU': 64, 'GPU': 0}.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui29231.ipynb?token=2a96200a9b730d350e7bdfa3fb5dad7eaf7587ef034f60a6
======================================================================

WARNING: python-snappy not available, disabling sample compression
== Status ==
Using FIFO scheduling algorithm.
Result logdir: /home/ubuntu/ray_results/default
PENDING trials:
 - PPO_CartPole-v0_0:	PENDING

Created LogSyncer for /home/ubuntu/ray_results/default/PPO_CartPole-v0_0_2018-03-26_20-46-47zgup8jyx -> 
WARNING: Serializing objects of type <class 'ray.tune.registry._Registry'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
== Status ==
Using FIFO scheduling algorithm.
Resources used: 1/64 CPUs, 0/0 GPUs
Result logdir: /home/ubuntu/ray_results/default
RUNNING trials:
 - PPO_CartPole-v0_0:	RUNNING

WARNING: python-snappy not available, disabling sample compression
[2018-03-26 20:46:50,027] Making new env: CartPole-v0
Observation shape is (4,)
Not using any observation preprocessor.
Remote function __init__ failed with:

Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/worker.py", line 821, in _process_task
    *arguments)
  File "/home/ubuntu/ray/python/ray/actor.py", line 212, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/ubuntu/ray/python/ray/rllib/agent.py", line 84, in __init__
    Trainable.__init__(self, config, registry, logger_creator)
  File "/home/ubuntu/ray/python/ray/tune/trainable.py", line 89, in __init__
    self._setup()
  File "/home/ubuntu/ray/python/ray/rllib/agent.py", line 107, in _setup
    self._init()
  File "/home/ubuntu/ray/python/ray/rllib/ppo/ppo.py", line 100, in _init
    self.registry, self.env_creator, self.config, self.logdir, False)
  File "/home/ubuntu/ray/python/ray/rllib/ppo/ppo_evaluator.py", line 45, in __init__
    registry, env_creator(config["env_config"]), config["model"])
  File "/home/ubuntu/ray/python/ray/rllib/models/catalog.py", line 231, in get_preprocessor_as_wrapper
    return _RLlibPreprocessorWrapper(env, preprocessor)
  File "/home/ubuntu/ray/python/ray/rllib/models/catalog.py", line 270, in __init__
    -1.0, 1.0, preprocessor.shape, dtype=np.float32)
TypeError: __init__() got an unexpected keyword argument 'dtype'


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:28427")
  
Remote function train failed with:

Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/worker.py", line 821, in _process_task
    *arguments)
  File "/home/ubuntu/ray/python/ray/actor.py", line 212, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/ubuntu/ray/python/ray/tune/trainable.py", line 106, in train
    "Trainable initialization failed, see previous errors")
ValueError: Trainable initialization failed, see previous errors


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:28427")
  Error processing event: Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/tune/trial_runner.py", line 218, in _process_events
    result = ray.get(result_id)
  File "/home/ubuntu/ray/python/ray/worker.py", line 2320, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(8d3fa548d995e09b9a99bc20af77193238a55026). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/worker.py", line 821, in _process_task
    *arguments)
  File "/home/ubuntu/ray/python/ray/actor.py", line 212, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/ubuntu/ray/python/ray/tune/trainable.py", line 106, in train
    "Trainable initialization failed, see previous errors")
ValueError: Trainable initialization failed, see previous errors



Worker ip unknown, skipping log sync for /home/ubuntu/ray_results/default/PPO_CartPole-v0_0_2018-03-26_20-46-47zgup8jyx
== Status ==
Using FIFO scheduling algorithm.
Resources used: 0/64 CPUs, 0/0 GPUs
Result logdir: /home/ubuntu/ray_results/default
ERROR trials:
 - PPO_CartPole-v0_0:	ERROR, 1 failures: /home/ubuntu/ray_results/default/PPO_CartPole-v0_0_2018-03-26_20-46-47zgup8jyx/error_2018-03-26_20-46-50.txt

Traceback (most recent call last):
  File "ray/python/ray/rllib/train.py", line 83, in <module>
    run_experiments(experiments, scheduler=_make_scheduler(args))
  File "/home/ubuntu/ray/python/ray/tune/tune.py", line 91, in run_experiments
    raise TuneError("Trial did not complete", trial)
ray.tune.error.TuneError: ('Trial did not complete', PPO_CartPole-v0_0)
```

cc @richardliaw @ericl

**Comment by robertnishihara** [comment]
I see the same error with A3C and DQN.

**Comment by richardliaw** [comment]
seems like a Gym old version issue?

**Comment by robertnishihara** [comment]
Ok, I think that's the issue, thanks! What gym version do we require?

**Comment by richardliaw** [comment]
I do believe it should be >=0.10.3? #1601
