### ISSUE TITLE
many_tasks release test is failing

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#17877]
### What is the problem?

We should see if this is related to the async worker pool pop PR. 

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by wuisawesome** [comment]
The failure is: 

```
Traceback (most recent call last):
  File "distributed/test_many_tasks.py", line 79, in <module>
    test()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "distributed/test_many_tasks.py", line 58, in test
    test_max_running_tasks(num_tasks)
  File "distributed/test_many_tasks.py", line 39, in test_max_running_tasks
    assert max_cpus - min_cpus_available > threshold, err_str
AssertionError: Only 288.25/4096.0 cpus used.
```

**Comment by stephanie-wang** [comment]
How many tasks was this run with? I'm a bit confused reading the test code; shouldn't 1000 tasks -> threshold = 1000 * 0.25 * 0.75 = 187.5? So I thought 288.25 CPUs used should be sufficient. Actually it seems too high?
