### ISSUE TITLE
[k8s][autoscaler] Ray cluster autoscaler dies after some time running

### ISSUE THREAD

**Issue by Luis-Victor** [ray-project/ray#17904]
### What is the problem?
After deployment of a Ray cluster on AKS, it runs well, but after some time (1~7 days), the cluster's autoscaler dies and doesn't restart.

Autoscale failure log:
```
example,dev:2021-08-16 23:01:09,643	ERROR autoscaler.py:151 -- StandardAutoscaler: Error during autoscaling.
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f9f712702b0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/autoscaler.py", line 148, in update
    self._update()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/autoscaler.py", line 255, in _update
    to_launch = self.resource_demand_scheduler.get_nodes_to_launch(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/resource_demand_scheduler.py", line 157, in get_nodes_to_launch
    node_resources, node_type_counts = self.calculate_node_resources(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/resource_demand_scheduler.py", line 488, in calculate_node_resources
    ip = self.provider.internal_ip(node_id)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/_kubernetes/node_provider.py", line 88, in internal_ip
    pod = core_api().read_namespaced_pod(node_id, self.namespace)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 22785, in read_namespaced_pod
    return self.read_namespaced_pod_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 22880, in read_namespaced_pod_with_http_info
    return self.api_client.call_api(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/rest.py", line 239, in GET
    return self.request("GET", url,
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/rest.py", line 212, in request
    r = self.pool_manager.request(method, url,
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.0.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/dev/pods/example-ray-head-type-nwxw4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f712702b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
example,dev:2021-08-16 23:01:09,662	ERROR monitor.py:285 -- Error in monitor loop
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f9f7019fac0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 317, in run
    self._run()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 221, in _run
    "autoscaler_report"] = self.autoscaler.summary()._asdict()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/autoscaler.py", line 828, in summary
    all_node_ids = self.provider.non_terminated_nodes(tag_filters={})
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/_kubernetes/node_provider.py", line 60, in non_terminated_nodes
    pod_list = core_api().list_namespaced_pod(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 15302, in list_namespaced_pod
    return self.list_namespaced_pod_with_http_info(namespace, **kwargs)  # noqa: E501
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 15413, in list_namespaced_pod_with_http_info
    return self.api_client.call_api(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/rest.py", line 239, in GET
    return self.request("GET", url,
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/rest.py", line 212, in request
    r = self.pool_manager.request(method, url,
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.0.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/dev/pods?fieldSelector=status.phase%21%3DFailed%2Cstatus.phase%21%3DUnknown%2Cstatus.phase%21%3DSucceeded%2Cstatus.phase%21%3DTerminating&labelSelector=ray-cluster-name%3Dexample (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f7019fac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Process example,dev:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f9f7019fac0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ray/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/ray_operator/operator.py", line 77, in _create_or_update
    self.start_monitor()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/ray_operator/operator.py", line 117, in start_monitor
    mtr.run()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 317, in run
    self._run()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 221, in _run
    "autoscaler_report"] = self.autoscaler.summary()._asdict()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/autoscaler.py", line 828, in summary
    all_node_ids = self.provider.non_terminated_nodes(tag_filters={})
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/_kubernetes/node_provider.py", line 60, in non_terminated_nodes
    pod_list = core_api().list_namespaced_pod(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 15302, in list_namespaced_pod
    return self.list_namespaced_pod_with_http_info(namespace, **kwargs)  # noqa: E501
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 15413, in list_namespaced_pod_with_http_info
    return self.api_client.call_api(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/rest.py", line 239, in GET
    return self.request("GET", url,
  File "/home/ray/anaconda3/lib/python3.8/site-packages/kubernetes/client/rest.py", line 212, in request
    r = self.pool_manager.request(method, url,
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.0.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/dev/pods?fieldSelector=status.phase%21%3DFailed%2Cstatus.phase%21%3DUnknown%2Cstatus.phase%21%3DSucceeded%2Cstatus.phase%21%3DTerminating&labelSelector=ray-cluster-name%3Dexample (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f7019fac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray version == 1.5.2
aks version == 1.18.14

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

- Deployment by helm
- values.yalm:
```
image: rayproject/ray:1.5.2-py38-gpu
headPodType: rayHeadType
podTypes:
  rayHeadType:
    minWorkers: 0
    maxWorkers: 0
    CPU: 1
    memory: 4Gi
    GPU: 0
    rayResources: {}
  rayWorkerType:
    memory: 48Gi
    CPU: 5
    GPU: 1
    rayResources: {}

operatorOnly: false
clusterOnly: false
namespacedOperator: false
operatorNamespace: dev
operatorImage: rayproject/ray:1.5.2-py38-gpu
```
- Ray operator:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-operator
  namespace: {{ .Values.operatorNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.ray.io/component: operator
  template:
    metadata:
      labels:
        cluster.ray.io/component: operator
    spec:
      serviceAccountName: ray-operator-serviceaccount
      containers:
      - name: ray
        imagePullPolicy: Always
        image: {{ .Values.operatorImage }}
        command: ["ray-operator"]
        env:
        - name: AUTOSCALER_MAX_NUM_FAILURES
          value: "inf"
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            memory: 2Gi
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by Luis-Victor** [comment]
Seemingly, updating the k8s version solves the problem.
