### ISSUE TITLE
[Object Spilling] Objects are lost when spilling

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#17901]
### What is the problem?
It looks like in a rare occasion, our spilling fails to get the object from the object store. This was discovered from 1000 partitions autoscaling shuffle.

```python
ValueError: object ref 92d4c064f994815effffffffffffffffffffffff0100000061000000 does not exist.
An unexpected internal error occurred while the IO worker was spilling objects: object ref 92d4c064f994815effffffffffffffffffffffff0100000061000000 does not exist.
2021-08-16 06:19:11,360 WARNING worker.py:1215 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 730, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 733, in ray._raylet.spill_objects_handler
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/external_storage.py", line 524, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/external_storage.py", line 280, in spill_objects
    owner_addresses, url)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/external_storage.py", line 129, in _write_multiple_objects
    raise ValueError(f"object ref {ref.hex()} does not exist.")
ValueError: object ref 68ecb7b4eb086e6affffffffffffffffffffffff0100000067020000 does not exist.
An unexpected internal error occurred while the IO worker was spilling objects: object ref 68ecb7b4eb086e6affffffffffffffffffffffff0100000067020000 does not exist.
```

The root cause is unknown, but we should fix the issue. 

Logs;
https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_tdyFfiAe2qYBsD8dMswUCGXa?command-history-section=command_history

https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_keNRLtVhcNSrsY7cBSbqCepL?command-history-section=command_history

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
Related; https://github.com/ray-project/ray/issues/17048

Highly likely we fails to pin the object before spilling in some scenarios.
