### ISSUE TITLE
Dask on Ray: Unable to set Dask scheduler from local client

### ISSUE THREAD

**Issue by gracedu0213** [ray-project/ray#17927]
### What is the problem?
*Ray version and other system information (Python version, TensorFlow version, OS):*
ray==1.5.2
dask==2021.7.0
Python==3.7.9

I'm trying to load data from GCS using Dask on Ray, and then train a sklearn randomforest model on Ray remotely in a kubernetes cluster. The job is submitted through a local client. 

I have setup Dask scheduler `dask.config.set(scheduler=ray_dask_get)` when I first connect to Ray from my local machine, before calling the remote function. I was able to call `df.compute()` in a Ray remote task, but when I got an error *when trying to fit the model using joblib*: `TypeError: float() argument must be a string or a number, not 'ray._raylet.ObjectRef'`.

I was able to get around this issue by configuring the dask scheduler in the remote function directly. This configures the schedulers on the remote machine that actually runs the function, but I would expect when the `dask.config.set()` was called with the ray client, it would configure on the remote machine. 

Full traceback:
```
Traceback (most recent call last):
  File "train_v2.py", line 157, in <module>
    main(*argument_parser().parse_known_args())
  File "train_v2.py", line 145, in main
    task_config['run_option']['n_workers']))
  File "/Users/gracedu/.pyenv/virtualenvs/ray-prototype/3.7.10/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 61, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/Users/gracedu/.pyenv/virtualenvs/ray-prototype/3.7.10/lib/python3.7/site-packages/ray/util/client/api.py", line 42, in get
    return self.worker.get(vals, timeout=timeout)
  File "/Users/gracedu/.pyenv/virtualenvs/ray-prototype/3.7.10/lib/python3.7/site-packages/ray/util/client/worker.py", line 225, in get
    res = self._get(obj_ref, op_timeout)
  File "/Users/gracedu/.pyenv/virtualenvs/ray-prototype/3.7.10/lib/python3.7/site-packages/ray/util/client/worker.py", line 248, in _get
    raise err
types.RayTaskError(TypeError): ray::train() (pid=111, ip=10.6.9.134)
  File "python/ray/_raylet.pyx", line 534, in ray._raylet.execute_task
  File "/usr/local/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py", line 330, in _function_with_tracing
    return function(*args, **kwargs)
  File "/Users/gracedu/.pyenv/virtualenvs/ray-prototype/3.7.10/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py", line 330, in _function_with_tracing
  File "train_v2.py", line 125, in train
  File "/usr/local/lib/python3.7/site-packages/sklearn/ensemble/_forest.py", line 305, in fit
    accept_sparse="csc", dtype=DTYPE)
  File "/usr/local/lib/python3.7/site-packages/sklearn/base.py", line 433, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 878, in check_X_y
    estimator=estimator)
  File "/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 673, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
  File "/usr/local/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/series.py", line 857, in __array__
    return np.asarray(self._values, dtype)
  File "/usr/local/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number, not 'ray._raylet.ObjectRef'
```

### Reproduction (REQUIRED)
NOTE: Need to provide gcs path and target variable name
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

```
from importlib import import_module

import dask
import dask.dataframe as dd
import joblib
import ray
from ray.util.dask import ray_dask_get
from ray.util.joblib import register_ray


@ray.remote
def compute(model, features, targets):
    features = features.compute()
    targets = targets.compute()
    register_ray()
    print('starting training model with joblib parallelization')
    with joblib.parallel_backend('ray', 16):
        model.fit(features, targets)


def load(path):
    df = dd.read_parquet(path)
    # Todo: need to change the target column nam
    target_ref = df['target'].persist()
    feature_df = df.drop('target', axis=1).persist()
    return feature_df, target_ref


def init_model(path):
    module, class_name = path.rsplit(".", maxsplit=1)
    model_class = getattr(import_module(module), class_name)
    return model_class(None)


def main():
    ray.util.connect("localhost:10001")
    dask.config.set(scheduler=ray_dask_get)
    # Todo: need to change to a gcs path
    feature_ref, target_ref = load('<GCS_PATH>')

    model = init_model('sklearn.ensemble.RandomForestRegressor')
    ray.get(compute.remote(model, feature_ref, target_ref))

    ray.shutdown()


if __name__ == '__main__':
    main()

```

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
@amogkam assigning to you first, feel free to pull in appropriate folks to assist (like Clark or Alex or Sang).

**Comment by amogkam** [comment]
I believe this should be a subset of #17943 since if we have a mechanism to propagate the scheduler to all nodes on a cluster, it should work for client to server as well.

@clarkzinzow @rkooo567 can data processing team look into this as part of #17943?

As for testing, this is only an issue for a multi-node cluster, and we have the testing in place for this with the golden notebooks (tracked by #16743) cc @matthewdeng

**Comment by amogkam** [comment]
Closing this as a subset of #17943.

@gracedu0213 I believe the workaround of setting the scheduler directly in the task is working for you, but please feel free to reopen this issue or ping us if this is still not working for you.
