### ISSUE TITLE
[rllib][gcs] inconsistencies in resource demands

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#18003]
When I run rllib:
1) the resource demands stay even after the application finishes, for example, I still see the following resource demands (for a few minutes) from the scheduler even after the job prints `(pid=191) 2021-08-22 10:45:21,492	INFO tune.py:550 -- Total run time: 1095.71 seconds (1094.69 seconds for the tuning loop).
`:
```
Demands:
 {'CPU_group_8eb7d5e8a4ed413432db93d0b79b3e67': 1.0}: 96+ pending tasks/actors
 {'GPU_group_16cd93bbf7607454e10fb4e3334f5da6': 0.001, 'GPU_group_0_16cd93bbf7607454e10fb4e3334f5da6': 0.001}: 1+ pending tasks/actors
 {'GPU_group_1431a0326b37900afe3595513b2e1818': 0.001, 'GPU_group_0_1431a0326b37900afe3595513b2e1818': 0.001}: 1+ pending tasks/actors
 {'CPU': 1.0, 'GPU': 1.0} * 1, {'CPU': 1.0} * 128 (PACK): 1+ pending placement groups
```

2) RLLIB prints a lot of verbose resources:
```
(pid=191) == Status ==
(pid=191) Memory usage on this node: 6.1/31.4 GiB
(pid=191) Using FIFO scheduling algorithm.
(pid=191) Resources requested: 0/296 CPUs, 0/8 GPUs, 0.0/787.44 GiB heap, 0.0/338.81 GiB objects (0.0/1.0 CPU_group_15_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_2_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_0_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_4_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_6_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 GPU_group_0_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 GPU_group_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_12_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_13_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_10_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_1_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_7_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_9_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_3_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_11_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_8_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_14_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_5_8c84f56bef40324a35f6e63418c2a54d, 0.0/129.0 CPU_group_8c84f56bef40324a35f6e63418c2a54d, 0.0/8.0 accelerator_type:T4, 0.0/1.0 CPU_group_116_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_127_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_117_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_119_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_121_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_113_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_124_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_123_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_118_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_115_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_126_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_120_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_114_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_125_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_122_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_112_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_128_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_83_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_85_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_94_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_87_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_90_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_84_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_88_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_82_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_89_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_91_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_92_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_86_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_80_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_93_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_81_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_95_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_100_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_97_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_103_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_108_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_98_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_104_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_111_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_102_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_96_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_99_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_110_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_101_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_106_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_109_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_105_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_107_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_43_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_33_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_36_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_32_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_34_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_35_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_37_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_40_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_39_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_42_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_45_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_44_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_41_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_46_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_47_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_38_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_21_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_18_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_28_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_16_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_19_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_25_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_20_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_27_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_17_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_24_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_22_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_26_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_23_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_30_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_31_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_29_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_71_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_72_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_76_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_68_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_79_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_78_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_70_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_69_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_67_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_65_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_64_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_75_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_66_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_74_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_73_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_77_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_52_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_48_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_63_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_56_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_54_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_62_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_55_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_59_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_51_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_53_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_57_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_58_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_50_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_49_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_61_8c84f56bef40324a35f6e63418c2a54d, 0.0/1.0 CPU_group_60_8c84f56bef40324a35f6e63418c2a54d)
```
CC @wuisawesome 

### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment]
Thank you so much for discovering these. I'll investigate further and might create child issues to track these individually after finding out the cause.

**Comment by AmeerHajAli** [comment]
@krfricke , after running compact-regression-test.yaml,  I am also getting:
```
Traceback (most recent call last):
  File "/Users/ameerhajali/anaconda3/envs/ray/bin/rllib", line 8, in <module>
    sys.exit(cli())
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/scripts.py", line 34, in cli
    train.run(options, train_parser)
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/train.py", line 255, in run
    concurrent=True)
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/tune/tune.py", line 624, in run_experiments
    _remote=False))
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 81, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/util/client/api.py", line 42, in get
    return self.worker.get(vals, timeout=timeout)
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/util/client/worker.py", line 225, in get
    res = self._get(obj_ref, op_timeout)
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/util/client/worker.py", line 244, in _get
    err = cloudpickle.loads(data.error)
ModuleNotFoundError: No module named 'tblib'
```

**Comment by rkooo567** [comment]
I believe this should be fixed int he master. Please reopen if you see the issue again
