### ISSUE TITLE
rllib train -f compact-regression-test.yaml ERROR on APEX_BreakoutNoFrameskip and DQN_BreakoutNoFrameskip

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#18007]
Is the following dump expected when running ray 1.5.2 with tf=2.5.0 and tf-gpu=2.5.0?
CC @amogkam @sven1977 @richardliaw 
```
== Status ==
Memory usage on this node: 4.1/58.9 GiB
Using FIFO scheduling algorithm.
Resources requested: 62.0/128 CPUs, 7.0/8 GPUs, 0.0/323.52 GiB heap, 0.0/141.17 GiB objects (0.0/1.0 CPU_group_10_8c53b838f12138f3fadd8b17f852e4a4, 0.0/1.0 CPU_group_4_8c53b838f12138f3fadd8b17f852e4a4, 0.0/1.0 CPU_group_8_8c53b838f12138f3fadd8b17f852e4a4, 0.0/1.0 CPU_group_9_8c53b838f12138f3fadd8b17f852e4a4, 0.0/1.0 CPU_group_7_8c53b838f12138f3fadd8b17f852e4a4, 0.0/1.0 CPU_group_2_8c53b838f12138f3fadd8b17f852e4a4, 0.0/1.0 CPU_group_1_8c53b838f12138f3fadd8b17f852e4a4, 0.0/8.0 accelerator_type:T4, 0.0/1.0 GPU_group_8c53b838f12138f3fadd8b17f852e4a4, 0.0/1.0 CPU_group_5_8c53b838f12138f3fadd8b17f852e4a4, 0.0/1.0 GPU_group_0_8c53b838f12138f3fadd8b17f852e4a4, 0.0/1.0 CPU_group_0_8c53b838f12138f3fadd8b17f852e4a4, 0.0/11.0 CPU_group_8c53b838f12138f3fadd8b17f852e4a4, 0.0/1.0 CPU_group_3_8c53b838f12138f3fadd8b17f852e4a4, 0.0/1.0 CPU_group_6_8c53b838f12138f3fadd8b17f852e4a4, 0.0/1.0 CPU_group_0_98aec57c6e1dd57a41c824e4eba28755, 0.0/1.0 CPU_group_9_98aec57c6e1dd57a41c824e4eba28755, 0.0/1.0 CPU_group_4_98aec57c6e1dd57a41c824e4eba28755, 0.0/1.0 GPU_group_98aec57c6e1dd57a41c824e4eba28755, 0.0/1.0 CPU_group_3_98aec57c6e1dd57a41c824e4eba28755, 0.0/1.0 CPU_group_7_98aec57c6e1dd57a41c824e4eba28755, 0.0/1.0 CPU_group_2_98aec57c6e1dd57a41c824e4eba28755, 0.0/1.0 CPU_group_5_98aec57c6e1dd57a41c824e4eba28755, 0.0/1.0 CPU_group_6_98aec57c6e1dd57a41c824e4eba28755, 0.0/1.0 CPU_group_10_98aec57c6e1dd57a41c824e4eba28755, 0.0/11.0 CPU_group_98aec57c6e1dd57a41c824e4eba28755, 0.0/1.0 GPU_group_0_98aec57c6e1dd57a41c824e4eba28755, 0.0/1.0 CPU_group_8_98aec57c6e1dd57a41c824e4eba28755, 0.0/1.0 CPU_group_1_98aec57c6e1dd57a41c824e4eba28755, 0.0/1.0 CPU_group_2_236921fdfbf972dccba2643e75f65645, 0.0/1.0 GPU_group_0_236921fdfbf972dccba2643e75f65645, 0.0/1.0 CPU_group_4_236921fdfbf972dccba2643e75f65645, 0.0/1.0 CPU_group_0_236921fdfbf972dccba2643e75f65645, 0.0/1.0 CPU_group_5_236921fdfbf972dccba2643e75f65645, 0.0/1.0 GPU_group_236921fdfbf972dccba2643e75f65645, 0.0/1.0 CPU_group_1_236921fdfbf972dccba2643e75f65645, 0.0/1.0 CPU_group_3_236921fdfbf972dccba2643e75f65645, 0.0/6.0 CPU_group_236921fdfbf972dccba2643e75f65645, 0.0/6.0 CPU_group_fe71b1e5def4ef7cc4258c9468a9ba2c, 0.0/1.0 CPU_group_5_fe71b1e5def4ef7cc4258c9468a9ba2c, 0.0/1.0 CPU_group_2_fe71b1e5def4ef7cc4258c9468a9ba2c, 0.0/1.0 CPU_group_4_fe71b1e5def4ef7cc4258c9468a9ba2c, 0.0/1.0 GPU_group_fe71b1e5def4ef7cc4258c9468a9ba2c, 0.0/1.0 GPU_group_0_fe71b1e5def4ef7cc4258c9468a9ba2c, 0.0/1.0 CPU_group_0_fe71b1e5def4ef7cc4258c9468a9ba2c, 0.0/1.0 CPU_group_1_fe71b1e5def4ef7cc4258c9468a9ba2c, 0.0/1.0 CPU_group_3_fe71b1e5def4ef7cc4258c9468a9ba2c, 0.0/1.0 GPU_group_0bcc573809cb3c2bb478d4050a07668f, 0.0/1.0 CPU_group_10_0bcc573809cb3c2bb478d4050a07668f, 0.0/1.0 CPU_group_2_0bcc573809cb3c2bb478d4050a07668f, 0.0/1.0 CPU_group_1_0bcc573809cb3c2bb478d4050a07668f, 0.0/1.0 CPU_group_8_0bcc573809cb3c2bb478d4050a07668f, 0.0/1.0 CPU_group_3_0bcc573809cb3c2bb478d4050a07668f, 0.0/1.0 CPU_group_4_0bcc573809cb3c2bb478d4050a07668f, 0.0/1.0 CPU_group_5_0bcc573809cb3c2bb478d4050a07668f, 0.0/11.0 CPU_group_0bcc573809cb3c2bb478d4050a07668f, 0.0/1.0 CPU_group_9_0bcc573809cb3c2bb478d4050a07668f, 0.0/1.0 CPU_group_0_0bcc573809cb3c2bb478d4050a07668f, 0.0/1.0 GPU_group_0_0bcc573809cb3c2bb478d4050a07668f, 0.0/1.0 CPU_group_6_0bcc573809cb3c2bb478d4050a07668f, 0.0/1.0 CPU_group_7_0bcc573809cb3c2bb478d4050a07668f, 0.0/1.0 CPU_group_2_22e10f19e3e68fdebbd2c57975deb822, 0.0/1.0 CPU_group_3_22e10f19e3e68fdebbd2c57975deb822, 0.0/1.0 CPU_group_5_22e10f19e3e68fdebbd2c57975deb822, 0.0/1.0 CPU_group_4_22e10f19e3e68fdebbd2c57975deb822, 0.0/1.0 GPU_group_22e10f19e3e68fdebbd2c57975deb822, 0.0/6.0 CPU_group_22e10f19e3e68fdebbd2c57975deb822, 0.0/1.0 CPU_group_1_22e10f19e3e68fdebbd2c57975deb822, 0.0/1.0 GPU_group_0_22e10f19e3e68fdebbd2c57975deb822, 0.0/1.0 CPU_group_0_22e10f19e3e68fdebbd2c57975deb822, 0.0/1.0 GPU_group_aa8d25e2c483c7ae568df84bce73b855, 0.0/1.0 CPU_group_6_aa8d25e2c483c7ae568df84bce73b855, 0.0/11.0 CPU_group_aa8d25e2c483c7ae568df84bce73b855, 0.0/1.0 CPU_group_3_aa8d25e2c483c7ae568df84bce73b855, 0.0/1.0 CPU_group_1_aa8d25e2c483c7ae568df84bce73b855, 0.0/1.0 CPU_group_9_aa8d25e2c483c7ae568df84bce73b855, 0.0/1.0 CPU_group_5_aa8d25e2c483c7ae568df84bce73b855, 0.0/1.0 CPU_group_0_aa8d25e2c483c7ae568df84bce73b855, 0.0/1.0 CPU_group_8_aa8d25e2c483c7ae568df84bce73b855, 0.0/1.0 CPU_group_7_aa8d25e2c483c7ae568df84bce73b855, 0.0/1.0 CPU_group_10_aa8d25e2c483c7ae568df84bce73b855, 0.0/1.0 CPU_group_2_aa8d25e2c483c7ae568df84bce73b855, 0.0/1.0 GPU_group_0_aa8d25e2c483c7ae568df84bce73b855, 0.0/1.0 CPU_group_4_aa8d25e2c483c7ae568df84bce73b855)
Result logdir: /home/ray/ray_results/apex
Result logdir: /home/ray/ray_results/atari-a2c
Result logdir: /home/ray/ray_results/atari-basic-dqn
Result logdir: /home/ray/ray_results/atari-impala
Result logdir: /home/ray/ray_results/atari-ppo-tf
Result logdir: /home/ray/ray_results/atari-ppo-torch
Number of trials: 24/24 (8 ERROR, 7 RUNNING, 9 TERMINATED)
+-------------------------------------------+------------+---------------------+--------+------------------+----------+-----------+----------------------+----------------------+--------------------+
| Trial name                                | status     | loc                 |   iter |   total time (s) |       ts |    reward |   episode_reward_max |   episode_reward_min |   episode_len_mean |
|-------------------------------------------+------------+---------------------+--------+------------------+----------+-----------+----------------------+----------------------+--------------------|
| PPO_BreakoutNoFrameskip-v4_64743_00008    | RUNNING    | 192.168.72.3:88129  |    160 |         3390.94  |   800000 |   1.98    |                    9 |                    0 |            771.74  |
| PPO_BreakoutNoFrameskip-v4_64743_00009    | RUNNING    | 192.168.86.3:424549 |    147 |         3132.08  |   735000 |  18.05    |                  229 |                    3 |           1828.72  |
| PPO_BreakoutNoFrameskip-v4_64743_00010    | RUNNING    | 192.168.92.3:55847  |    150 |         3132.49  |   750000 |  10.98    |                   28 |                    0 |           1938.89  |
| PPO_BreakoutNoFrameskip-v4_64743_00011    | RUNNING    | 192.168.85.3:486125 |    100 |         2119.62  |   500000 |   6.68    |                   35 |                    0 |           1352.42  |
| A2C_BreakoutNoFrameskip-v4_64743_00016    | RUNNING    | 192.168.76.4:68     |    178 |         1796.36  |  2893000 |   1.5     |                    5 |                    0 |            796.8   |
| A2C_BreakoutNoFrameskip-v4_64743_00017    | RUNNING    | 192.168.78.5:120    |    144 |         1452.65  |  2268000 |   2.4     |                   11 |                    0 |            652.591 |
| A2C_BreakoutNoFrameskip-v4_64743_00019    | RUNNING    | 192.168.75.6:91     |     74 |          741.496 |  1207000 |   2.55357 |                   11 |                    0 |            661.473 |
| IMPALA_BreakoutNoFrameskip-v4_64743_00000 | TERMINATED |                     |    355 |         3609.17  | 11706500 | 361.86    |                  431 |                   15 |           8202.21  |
| IMPALA_BreakoutNoFrameskip-v4_64743_00001 | TERMINATED |                     |    357 |         3609.16  | 13093000 | 407.58    |                  820 |                  147 |          11542.9   |
| IMPALA_BreakoutNoFrameskip-v4_64743_00002 | TERMINATED |                     |    357 |         3600.9   | 12733000 | 406.83    |                  784 |                  249 |          10847     |
| IMPALA_BreakoutNoFrameskip-v4_64743_00003 | TERMINATED |                     |    358 |         3603.68  | 12738000 | 389.61    |                  445 |                   38 |          10630.2   |
| PPO_BreakoutNoFrameskip-v4_64743_00004    | TERMINATED |                     |    893 |         3602.84  |  4465000 |  17.08    |                   33 |                    5 |           2184.17  |
| PPO_BreakoutNoFrameskip-v4_64743_00005    | TERMINATED |                     |    944 |         3602.96  |  4720000 |  52.93    |                  353 |                    7 |           3125     |
| PPO_BreakoutNoFrameskip-v4_64743_00006    | TERMINATED |                     |    924 |         3600.57  |  4620000 |  30.81    |                   64 |                   11 |           3521.53  |
| APEX_BreakoutNoFrameskip-v4_64743_00012   | ERROR      |                     |        |                  |          |           |                      |                      |                    |
| APEX_BreakoutNoFrameskip-v4_64743_00013   | ERROR      |                     |     10 |          398.863 |   727840 |   5.78    |                   14 |                    1 |           1216.72  |
| APEX_BreakoutNoFrameskip-v4_64743_00014   | ERROR      |                     |     10 |          393.234 |   722720 |   5.95    |                   20 |                    0 |           1260.04  |
| APEX_BreakoutNoFrameskip-v4_64743_00015   | ERROR      |                     |     10 |          405.066 |   724480 |   5.32353 |                   15 |                    1 |           1192.84  |
| DQN_BreakoutNoFrameskip-v4_64743_00020    | ERROR      |                     |     16 |         1371.5   |   170000 |   2.29    |                   13 |                    0 |            874.5   |
| DQN_BreakoutNoFrameskip-v4_64743_00021    | ERROR      |                     |     16 |         1370.3   |   170000 |   3.79    |                   19 |                    0 |           1057.59  |
| DQN_BreakoutNoFrameskip-v4_64743_00022    | ERROR      |                     |     16 |         1374.14  |   170000 |   1.78    |                   11 |                    0 |            758.03  |
+-------------------------------------------+------------+---------------------+--------+------------------+----------+-----------+----------------------+----------------------+--------------------+
... 4 more trials not shown (2 TERMINATED, 1 ERROR)
Number of errored trials: 8
+-----------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------+
| Trial name                              |   # failures | error file                                                                                                    |
|-----------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------|
| APEX_BreakoutNoFrameskip-v4_64743_00012 |            1 | /home/ray/ray_results/apex/APEX_BreakoutNoFrameskip-v4_64743_00012_12_2021-08-22_15-02-12/error.txt           |
| APEX_BreakoutNoFrameskip-v4_64743_00013 |            1 | /home/ray/ray_results/apex/APEX_BreakoutNoFrameskip-v4_64743_00013_13_2021-08-22_14-58-57/error.txt           |
| APEX_BreakoutNoFrameskip-v4_64743_00014 |            1 | /home/ray/ray_results/apex/APEX_BreakoutNoFrameskip-v4_64743_00014_14_2021-08-22_14-54-42/error.txt           |
| APEX_BreakoutNoFrameskip-v4_64743_00015 |            1 | /home/ray/ray_results/apex/APEX_BreakoutNoFrameskip-v4_64743_00015_15_2021-08-22_15-02-45/error.txt           |
| DQN_BreakoutNoFrameskip-v4_64743_00020  |            1 | /home/ray/ray_results/atari-basic-dqn/DQN_BreakoutNoFrameskip-v4_64743_00020_20_2021-08-22_15-02-22/error.txt |
| DQN_BreakoutNoFrameskip-v4_64743_00021  |            1 | /home/ray/ray_results/atari-basic-dqn/DQN_BreakoutNoFrameskip-v4_64743_00021_21_2021-08-22_15-02-22/error.txt |
| DQN_BreakoutNoFrameskip-v4_64743_00022  |            1 | /home/ray/ray_results/atari-basic-dqn/DQN_BreakoutNoFrameskip-v4_64743_00022_22_2021-08-22_15-02-22/error.txt |
| DQN_BreakoutNoFrameskip-v4_64743_00023  |            1 | /home/ray/ray_results/atari-basic-dqn/DQN_BreakoutNoFrameskip-v4_64743_00023_23_2021-08-22_15-02-22/error.txt |
+-----------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------+
```

### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by AmeerHajAli** [comment]
All error files show:
```
Failure # 1 (occurred at 2021-08-22_15-26-21)
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 739, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 729, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1566, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
```

**Comment by amogkam** [comment]
Hey @AmeerHajAli is there no other information in the stdout or in the error.txt files? Are you using spot instances?

**Comment by AmeerHajAli** [comment]
no, not using spot instances.
It is easy to repro, run ray/rllib/tuned_examples/compact-regression-test.yaml on the product

**Comment by sven1977** [comment]
Trying to reproduce now ...

**Comment by sven1977** [comment]
Tried a shortened 10min-each-trial run on a 8GPU machine using the same tf and ray versions you mentioned above. Not seeing any problems. Will run now for 1h each trial (original `rllib train -f compact-regression-test.yaml` experiment).

**Comment by sven1977** [comment]
```
Number of trials: 24/24 (24 TERMINATED)
+-------------------------------------------+------------+-------+--------+------------------+---------+----------+----------------------+----------------------+--------------------+
| Trial name                                | status     | loc   |   iter |   total time (s) |      ts |   reward |   episode_reward_max |   episode_reward_min |   episode_len_mean |
|-------------------------------------------+------------+-------+--------+------------------+---------+----------+----------------------+----------------------+--------------------|
| IMPALA_BreakoutNoFrameskip-v4_fb14e_00000 | TERMINATED |       |     59 |          601.379 | 1723500 | 24.93    |                   56 |                    9 |            2790.24 |
| IMPALA_BreakoutNoFrameskip-v4_fb14e_00001 | TERMINATED |       |     59 |          601.658 | 1757250 | 25.62    |                   64 |                    8 |            2878.66 |
| IMPALA_BreakoutNoFrameskip-v4_fb14e_00002 | TERMINATED |       |     59 |          601.151 | 1718500 | 25.81    |                   52 |                   14 |            3140.81 |
| IMPALA_BreakoutNoFrameskip-v4_fb14e_00003 | TERMINATED |       |     59 |          600.954 | 1704500 | 12.2     |                   28 |                    6 |            1971.27 |
| PPO_BreakoutNoFrameskip-v4_fb14e_00004    | TERMINATED |       |    129 |          603.52  |  645000 |  4.35    |                   11 |                    0 |            1020.72 |
| PPO_BreakoutNoFrameskip-v4_fb14e_00005    | TERMINATED |       |    134 |          603.124 |  670000 | 11.72    |                   30 |                    6 |            2001.3  |
| PPO_BreakoutNoFrameskip-v4_fb14e_00006    | TERMINATED |       |    131 |          603.748 |  655000 |  7.63    |                   18 |                    0 |            1604.64 |
| PPO_BreakoutNoFrameskip-v4_fb14e_00007    | TERMINATED |       |    133 |          601.499 |  665000 |  2.7     |                    9 |                    0 |             861.67 |
| PPO_BreakoutNoFrameskip-v4_fb14e_00008    | TERMINATED |       |     28 |          619.839 |  140000 |  0.87    |                    8 |                    0 |             599.44 |
| PPO_BreakoutNoFrameskip-v4_fb14e_00009    | TERMINATED |       |     28 |          621.689 |  140000 |  1.1     |                    5 |                    0 |             724.1  |
| PPO_BreakoutNoFrameskip-v4_fb14e_00010    | TERMINATED |       |     28 |          614.827 |  140000 |  2       |                    2 |                    2 |             803.91 |
| PPO_BreakoutNoFrameskip-v4_fb14e_00011    | TERMINATED |       |     28 |          621.88  |  140000 |  2.2     |                   11 |                    0 |             642.25 |
| APEX_BreakoutNoFrameskip-v4_fb14e_00012   | TERMINATED |       |     19 |          617.702 | 1406400 |  5.27    |                   14 |                    1 |            1263    |
| APEX_BreakoutNoFrameskip-v4_fb14e_00013   | TERMINATED |       |     17 |          605.463 | 1254080 |  5.92308 |                   14 |                    1 |            1210.72 |
| APEX_BreakoutNoFrameskip-v4_fb14e_00014   | TERMINATED |       |     19 |          620.377 | 1400320 |  5.08    |                   13 |                    0 |            1196.9  |
| APEX_BreakoutNoFrameskip-v4_fb14e_00015   | TERMINATED |       |     19 |          616.863 | 1404640 |  5.25    |                   16 |                    0 |            1224.93 |
| A2C_BreakoutNoFrameskip-v4_fb14e_00016    | TERMINATED |       |     59 |          603.941 |  640000 |  1.98    |                   11 |                    0 |             630.41 |
| A2C_BreakoutNoFrameskip-v4_fb14e_00017    | TERMINATED |       |     59 |          601.463 |  620000 |  2.31    |                   11 |                    0 |             648.45 |
| A2C_BreakoutNoFrameskip-v4_fb14e_00018    | TERMINATED |       |     60 |          601.451 |  698500 |  2.75    |                   11 |                    0 |             671.91 |
| A2C_BreakoutNoFrameskip-v4_fb14e_00019    | TERMINATED |       |     60 |          602.226 |  705500 |  8.22    |                   17 |                    1 |            1469.62 |
| DQN_BreakoutNoFrameskip-v4_fb14e_00020    | TERMINATED |       |      6 |          677.213 |   70000 |  1.24    |                    5 |                    0 |             714.6  |
| DQN_BreakoutNoFrameskip-v4_fb14e_00021    | TERMINATED |       |      6 |          664.714 |   70000 |  1.56    |                    7 |                    0 |             779.76 |
| DQN_BreakoutNoFrameskip-v4_fb14e_00022    | TERMINATED |       |      5 |          604.004 |   60000 |  1.76    |                   13 |                    0 |             793.26 |
| DQN_BreakoutNoFrameskip-v4_fb14e_00023    | TERMINATED |       |      6 |          668.445 |   70000 |  1.21    |                    5 |                    0 |             711.38 |
+-------------------------------------------+------------+-------+--------+------------------+---------+----------+----------------------+----------------------+--------------------+


2021-08-24 03:26:04,705 INFO tune.py:550 -- Total run time: 2021.76 seconds (2020.62 seconds for the tuning loop).
```

**Comment by sven1977** [comment]
Will run now for 1h each trial (original `rllib train -f compact-regression-test.yaml` experiment). ...

**Comment by sven1977** [comment]
@AmeerHajAli ^

**Comment by AmeerHajAli** [comment]
@sven1977 , thanks for doing that. I was using the default compute template. The issues arise after it runs for much than 10 minutes, I'd say around 40 minutes for sure.

**Comment by sven1977** [comment]
Ok, cool. So far the 1h run looks ok (>1h running). I'll keep you posted.
I'm on a g4dn.metal with container anyscale/ray-ml:1.5.2-py38-gpu
I only updated tensorflow to 2.5.0 and then ran `rllib train -f [yaml file]`.

**Comment by AmeerHajAli** [comment]
Would it be helpful if I run it and share the cluster with you?

**Comment by sven1977** [comment]
Yes, would like to take a look.

**Comment by sven1977** [comment]
Looks ok on my cluster.

g4dn.metal
anyscale/ray-ml:1.5.2-py38-gpu
tf=2.5.0
ray=1.5.2

`rllib train -f rllib/tuned_examples/compact-regression-test.yaml`

```
Number of trials: 24/24 (24 TERMINATED)
+-------------------------------------------+------------+-------+--------+------------------+----------+----------+----------------------+----------------------+--------------------+
| Trial name                                | status     | loc   |   iter |   total time (s) |       ts |   reward |   episode_reward_max |   episode_reward_min |   episode_len_mean |
|-------------------------------------------+------------+-------+--------+------------------+----------+----------+----------------------+----------------------+--------------------|
| IMPALA_BreakoutNoFrameskip-v4_c7400_00000 | TERMINATED |       |    358 |          3601.29 | 10904250 |   406.53 |                  825 |                  169 |           10947.6  |
| IMPALA_BreakoutNoFrameskip-v4_c7400_00001 | TERMINATED |       |    359 |          3600.61 | 10571000 |   374.38 |                  479 |                   17 |            8886.84 |
| IMPALA_BreakoutNoFrameskip-v4_c7400_00002 | TERMINATED |       |    359 |          3606.91 | 10666250 |   389.84 |                  755 |                  191 |            9756.33 |
| IMPALA_BreakoutNoFrameskip-v4_c7400_00003 | TERMINATED |       |    359 |          3603.21 | 10546500 |   388.19 |                  527 |                  166 |           10138.1  |
| PPO_BreakoutNoFrameskip-v4_c7400_00004    | TERMINATED |       |    780 |          3600.91 |  3900000 |    31.81 |                  253 |                    3 |            2528.55 |
| PPO_BreakoutNoFrameskip-v4_c7400_00005    | TERMINATED |       |    768 |          3602.57 |  3840000 |    27.07 |                   51 |                    5 |            3161.73 |
| PPO_BreakoutNoFrameskip-v4_c7400_00006    | TERMINATED |       |    817 |          3600.66 |  4085000 |    27.87 |                  230 |                    6 |            2724.53 |
| PPO_BreakoutNoFrameskip-v4_c7400_00007    | TERMINATED |       |    824 |          3602.64 |  4120000 |    56.52 |                  282 |                   12 |            3011.74 |
| PPO_BreakoutNoFrameskip-v4_c7400_00008    | TERMINATED |       |    163 |          3600.8  |   815000 |    20.2  |                  416 |                    4 |            1956.23 |
| PPO_BreakoutNoFrameskip-v4_c7400_00009    | TERMINATED |       |    158 |          3620.34 |   790000 |    13.07 |                   31 |                    5 |            2004.48 |
| PPO_BreakoutNoFrameskip-v4_c7400_00010    | TERMINATED |       |    159 |          3611.65 |   795000 |    24.28 |                  234 |                    6 |            1971.35 |
| PPO_BreakoutNoFrameskip-v4_c7400_00011    | TERMINATED |       |    163 |          3607.32 |   815000 |    11.39 |                   47 |                    0 |            1620.01 |
| APEX_BreakoutNoFrameskip-v4_c7400_00012   | TERMINATED |       |    101 |          3625.21 |  7596160 |    13.24 |                   28 |                    3 |            2055.36 |
| APEX_BreakoutNoFrameskip-v4_c7400_00013   | TERMINATED |       |    114 |          3629.29 |  8581120 |    13.98 |                   31 |                    3 |            1973.19 |
| APEX_BreakoutNoFrameskip-v4_c7400_00014   | TERMINATED |       |    114 |          3612.85 |  8575200 |    16.13 |                   34 |                    4 |            2367.24 |
| APEX_BreakoutNoFrameskip-v4_c7400_00015   | TERMINATED |       |    112 |          3615.87 |  8424480 |    14.23 |                   40 |                    4 |            2142.49 |
| A2C_BreakoutNoFrameskip-v4_c7400_00016    | TERMINATED |       |    355 |          3605.02 |  3710500 |     2.34 |                    9 |                    0 |             813.87 |
| A2C_BreakoutNoFrameskip-v4_c7400_00017    | TERMINATED |       |    355 |          3604.55 |  4136000 |     2.86 |                   11 |                    0 |             676.12 |
| A2C_BreakoutNoFrameskip-v4_c7400_00018    | TERMINATED |       |    354 |          3604.41 |  4091500 |     1.54 |                   11 |                    0 |             606.84 |
| A2C_BreakoutNoFrameskip-v4_c7400_00019    | TERMINATED |       |    356 |          3606.73 |  3786000 |     2.52 |                    9 |                    0 |             837.64 |
| DQN_BreakoutNoFrameskip-v4_c7400_00020    | TERMINATED |       |     30 |          3647.92 |   310000 |    14.38 |                   35 |                    3 |            1981.64 |
| DQN_BreakoutNoFrameskip-v4_c7400_00021    | TERMINATED |       |     30 |          3658.57 |   310000 |    17.21 |                   36 |                    6 |            2195.96 |
| DQN_BreakoutNoFrameskip-v4_c7400_00022    | TERMINATED |       |     30 |          3667.62 |   310000 |    20.01 |                   42 |                    8 |            2446.61 |
| DQN_BreakoutNoFrameskip-v4_c7400_00023    | TERMINATED |       |     30 |          3678.46 |   310000 |    16.22 |                   33 |                    6 |            2085.68 |
+-------------------------------------------+------------+-------+--------+------------------+----------+----------+----------------------+----------------------+--------------------+


2021-08-24 06:36:18,467 INFO tune.py:550 -- Total run time: 10945.07 seconds (10944.27 seconds for the tuning loop).
```

**Comment by AmeerHajAli** [comment]
@sven1977 checkout this one:
https://beta.anyscale.com/o/anyscale-internal/projects/prj_MyVW7bByg2bLbXNU6mupEDiL/clusters/ses_Zs3sW7dQQUKqi8bfA5tPBfUY

**Comment by zhe-thoughts** [comment]
@sven1977 @AmeerHajAli Did this turn out to be a reproducible issue? Thanks
