### ISSUE TITLE
[tune] Multi-Objective Samplers Like NSGA-II found in Optuna

### ISSUE THREAD

**Issue by CMobley7** [ray-project/ray#18027]
I'm using Optuna's NSGA-II multi-objective sampler in order to optimize over multiple performance metrics. However, one of the libraries I'm using is single-threaded; so, when I run the analysis with just Optuna, only 1 thread of my CPU is utilized. In an effort to maximize my CPU usage, as well as allow the possibility to expand the analysis to multiple servers I decided to use Ray. Awesome library by the way! Unfortunately, when looking through Ray Tune I didn't see any multi-objective samplers. So, I tried both to use Optuna with Ray by following Optuna's example, https://github.com/optuna/optuna-examples/blob/main/ray/ray_joblib.py, and Ray Tune's Optuna integration by following your example, https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/optuna_example.py.

When following Optuna's Ray example, only 1 thread was used and all workers were idle. When following your example with the code below, I received the following error, `ValueError: Invalid return or yield value. Either return/yield a single number or a dictionary object in your trainable function.` and if I make the objective function return a dictionary of objectives, I get a KeyError.

```
def objective(config):
    ...
    return (objective_1, objective_2, objective_3, objective_4, objective_5)

def run_optuna_tune():
    algo = OptunaSearch(
        mode=[
            "maximize",
            "maximize",
            "maximize",
            "minimize",
            "minimize",
        ],
        sampler=optuna.samplers.NSGAIISampler(),
    )
    algo = ConcurrencyLimiter(algo, max_concurrent=4)
    config = ...
    analysis = tune.run(
        objective,
        config=config,
        search_alg=algo,
        num_samples=N_TRIALS,
    )

if __name__ == "__main__":
    # Get a URL for the Ray dashboard.
    try:
        ray.init(address="auto")
    except ConnectionError:
        ray.init()
    # Disable the warning to suppress the log.
    # TODO(HideakiImamura): enable warning after https://github.com/ray-project/ray/pull/13865 is
    # released.
    ray.init(logging_level=logging.ERROR, ignore_reinit_error=True)

    run_optuna_tune()
```
Am I doing something wrong? Is there a better way to achieve my goals? Does Ray Tune have any Multi-objective sampler like NSGA-II? If no, no, and Ray Tune doesn't have any Multi-objective sampler like NSGA-II, can Ray Tune's integration of Optuna be changed to allow them and/or can Multi-objective samplers be added to Ray Tune?

**Comment by amogkam** [comment]
Hey @CMobley7 instead of returning inside your `objective` function, can you use `tune.report` instead like in the optuna example https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/optuna_example.py#L29. Let me know if that works for you.

**Comment by CMobley7** [comment]
@amogkam, thank you for the quick response. I really appreciate it. My apologies for not noticing that discrepancy in my code earlier. I fixed that as shown below, as well as updated my init of ray when using Optuna's example. However, I get the following error now.

```
def objective(config):
    ...
    tune.report(objective_1, objective_2, objective_3, objective_4, objective_5)

def run_optuna_tune():
    algo = OptunaSearch(
        mode=[
            "maximize",
            "maximize",
            "maximize",
            "minimize",
            "minimize",
        ],
        sampler=optuna.samplers.NSGAIISampler(),
    )
    algo = ConcurrencyLimiter(algo, max_concurrent=4)
    config = ...
    analysis = tune.run(
        objective,
        config=config,
        search_alg=algo,
        num_samples=N_TRIALS,
    )

if __name__ == "__main__":
    # Get a URL for the Ray dashboard.
    try:
        ray.init(address="auto")
    except ConnectionError:
        ray.init()
    # Disable the warning to suppress the log.
    # TODO(HideakiImamura): enable warning after https://github.com/ray-project/ray/pull/13865 is
    # released.
    ray.init(logging_level=logging.ERROR, ignore_reinit_error=True)

    run_optuna_tune()
```
```
(pid=175773) 2021-08-23 21:00:08,682    ERROR function_runner.py:254 -- Runner Thread raised error.
(pid=175773) Traceback (most recent call last):
(pid=175773)   File "/home/cmobley/Documents/project/cf/lib/python3.8/site-packages/numba/core/caching.py", line 479, in save
(pid=175773)     data_name = overloads[key]
(pid=175773) KeyError: ((UniTuple(int64 x 2), array(float64, 2d, C), array(int64, 1d, C), readonly array(float64, 1d, C), array(int64, 2d, C), array(bool, 1d, C), array(bool, 1d, C), array(float64, 0d, C), array(float64, 0d, C), array(int64, 0d, C), array(int64, 0d, C), array(float64, 0d, C), array(float64, 0d, C), array(float64, 0d, C), array(float64, 0d, C), array(float64, 0d, C), array(float64, 0d, C), array(bool, 0d, C), array(bool, 0d, C), array(bool, 0d, C), array(bool, 0d, C), array(bool, 0d, C), array(int64, 0d, C), array(bool, 0d, C), array(float64, 0d, C), array(float64, 1d, C), array(float64, 1d, C), array(float64, 1d, C), array(float64, 0d, C), array(float64, 0d, C), array(float64, 0d, C), array(int64, 0d, C), array(int64, 0d, C), array(int64, 0d, C), array(int64, 0d, C), array(int64, 0d, C), type(CPUDispatcher(<function no_adjust_sl_func_nb at 0x7f9993055550>)), Tuple(), type(CPUDispatcher(<function no_adjust_tp_func_nb at 0x7f9993055f70>)), Tuple(), bool, bool, bool, bool, int64, int64, bool), ('x86_64-unknown-linux-gnu', 'haswell', '+64bit,-adx,+aes,-amx-bf16,-amx-int8,-amx-tile,+avx,+avx2,-avx512bf16,-avx512bitalg,-avx512bw,-avx512cd,-avx512dq,-avx512er,-avx512f,-avx512ifma,-avx512pf,-avx512vbmi,-avx512vbmi2,-avx512vl,-avx512vnni,-avx512vp2intersect,-avx512vpopcntdq,+bmi,+bmi2,-cldemote,-clflushopt,-clwb,-clzero,+cmov,+cx16,+cx8,-enqcmd,+f16c,+fma,-fma4,+fsgsbase,+fxsr,-gfni,+invpcid,-lwp,+lzcnt,+mmx,+movbe,-movdir64b,-movdiri,-mwaitx,+pclmul,-pconfig,-pku,+popcnt,-prefetchwt1,-prfchw,-ptwrite,-rdpid,+rdrnd,-rdseed,-rtm,+sahf,-serialize,-sgx,-sha,-shstk,+sse,+sse2,+sse3,+sse4.1,+sse4.2,-sse4a,+ssse3,-tbm,-tsxldtrk,-vaes,-vpclmulqdq,-waitpkg,-wbnoinvd,-xop,+xsave,-xsavec,+xsaveopt,-xsaves'), ('d4c1ba789548592687d4e88ea45fa16fe9a234f5030a93441ad4939390eb0f2f', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'))
(pid=175773) 
(pid=175773) During handling of the above exception, another exception occurred:
(pid=175773) 
(pid=175773) Traceback (most recent call last):
(pid=175773)   File "/home/cmobley/Documents/project/cf/lib/python3.8/site-packages/ray/tune/function_runner.py", line 248, in run
(pid=175773)     self._entrypoint()
(pid=175773)   File "/home/cmobley/Documents/project/cf/lib/python3.8/site-packages/ray/tune/function_runner.py", line 315, in entrypoint
(pid=175773)     return self._trainable_func(self.config, self._status_reporter,
(pid=175773)   File "/home/cmobley/Documents/project/cf/lib/python3.8/site-packages/ray/tune/function_runner.py", line 580, in _trainable_func
(pid=175773)     output = fn()
(pid=175773)   File "ground_truth_hyperparameter_search.py", line 210, in objective
(pid=175773)     stats = generate_stats(
(pid=175773)   File "ground_truth_hyperparameter_search.py", line 165, in generate_stats
(pid=175773)     portfolio = vbt.Portfolio.from_signals(
(pid=175773)   File "/home/cmobley/Documents/project/cf/lib/python3.8/site-packages/vectorbt/portfolio/base.py", line 1996, in from_signals
(pid=175773)     order_records, log_records = nb.simulate_from_signals_nb(
(pid=175773)   File "/home/cmobley/Documents/project/cf/lib/python3.8/site-packages/numba/core/dispatcher.py", line 501, in _compile_for_args
(pid=175773)     raise e
(pid=175773)   File "/home/cmobley/Documents/project/cf/lib/python3.8/site-packages/numba/core/dispatcher.py", line 434, in _compile_for_args
(pid=175773)     return_val = self.compile(tuple(argtypes))
(pid=175773)   File "/home/cmobley/Documents/project/cf/lib/python3.8/site-packages/numba/core/dispatcher.py", line 986, in compile
(pid=175773)     self._cache.save_overload(sig, cres)
(pid=175773)   File "/home/cmobley/Documents/project/cf/lib/python3.8/site-packages/numba/core/caching.py", line 661, in save_overload
(pid=175773)     self._save_overload(sig, data)
(pid=175773)   File "/home/cmobley/Documents/project/cf/lib/python3.8/site-packages/numba/core/caching.py", line 671, in _save_overload
(pid=175773)     self._cache_file.save(key, data)
(pid=175773)   File "/home/cmobley/Documents/project/cf/lib/python3.8/site-packages/numba/core/caching.py", line 488, in save
(pid=175773)     self._save_index(overloads)
(pid=175773)   File "/home/cmobley/Documents/project/cf/lib/python3.8/site-packages/numba/core/caching.py", line 532, in _save_index
(pid=175773)     data = self._dump(data)
(pid=175773)   File "/home/cmobley/Documents/project/cf/lib/python3.8/site-packages/numba/core/caching.py", line 560, in _dump
(pid=175773)     return pickle.dumps(obj, protocol=-1)
(pid=175773)   File "/home/cmobley/Documents/project/cf/lib/python3.8/site-packages/numba/core/types/functions.py", line 500, in __getnewargs__
(pid=175773)     raise ReferenceError("underlying object has vanished")
(pid=175773) ReferenceError: underlying object has vanished
```

**Comment by amogkam** [comment]
Hey @CMobley7, thanks for the followup. It don't look like the `OptunaSearcher` supports multi-objective samplers currently (cc @krfricke and @Yard1 to confirm), though we can definitely look into adding support for this.

What's interesting though is that the `KeyError` looks to be something unrelated to Ray Tune though. From the stack trace it looks to be coming from the `generate_stats` call inside your `objective` function.

**Comment by CMobley7** [comment]
@amogkam , thanks for looking into this and being open to updating `OptunaSearcher`. I really appreciate it. In regards to the error, it looks like it's originating from `vectorbt`. I'll investigate more and open a ticket there of necessary. Thanks again

**Comment by xwjiang2010** [comment]
cc @Yard1

**Comment by Yard1** [comment]
@CMobley7 unfortunately it looks like the Optuna API we are using doesn't support multi-objective optimization just yet. I have opened an issue for that in the Optuna repo - https://github.com/optuna/optuna/issues/3100. I will be looking into Dragonfly soon.

**Comment by Yard1** [comment]
@CMobley7 Good news! We will be able to support multi-objective optimization for Optuna after all. https://github.com/ray-project/ray/pull/20489
