### ISSUE TITLE
[tune] Remote Nodes nan logging fails

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#1812]
### Describe the problem
There is a reported by where remote workers with reporters that are passed in `nan` values fail upon pretty printing.

### Source code / logs
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 228, in _process_events
    result, terminate=(decision == TrialScheduler.STOP))
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/tune/trial.py", line 335, in update_last_result
    print("  {}".format(pretty_print(result).replace("\n", "\n  ")))
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/tune/logger.py", line 190, in pretty_print
    return yaml.safe_dump(json.loads(cleaned), default_flow_style=False)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1430 (char 1429)
```

@vlad17

**Comment by vlad17** [comment]
@richardliaw maybe close for now; if I can consistently replicate I'll make an issue?

**Comment by richardliaw** [comment]
Sounds good.
