### ISSUE TITLE
cpu only tune job is outputting `get_gpu_ids()` warning

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#18268]
### What is the problem?

Pretty recent master.
I was actually trying to do some performance benchmark against Optuna and ran into this.

```
import time

import ray
from ray import tune
import threading
import logging
l = threading.Lock()


def train(config):
    l.acquire()
    l.release()
    result = (config["x"] - 2) ** 2
    tune.report(result)


start = time.time()
ray.init(local_mode=True)
print(f"ray.init() takes {time.time() - start:.2f} seconds to finish.")

tune.run(train, config={"x": tune.uniform(-10, 10)}, num_samples=2000) #, log_to_file="/tmp/log.txt")

print(f"Took {time.time() - start:.2f} seconds to run.")
```

Sample output
```
+-------------------+----------+-------+---------+
| Trial name        | status   | loc   |       x |
|-------------------+----------+-------+---------|
| train_51c9b_00000 | RUNNING  |       | 3.65523 |
+-------------------+----------+-------+---------+


2021-08-31 20:54:35,079	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,088	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,098	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,106	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,113	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,121	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,129	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,138	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,154	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,164	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,172	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,179	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,189	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,203	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,215	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,230	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,244	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,254	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,262	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,270	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,277	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,285	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,298	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,308	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,317	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,325	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,333	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,347	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,356	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,366	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,373	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,380	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,415	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,424	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,433	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,446	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,455	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,463	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,472	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,479	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,489	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,502	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,511	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,519	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,528	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,538	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,551	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,561	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,569	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,576	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,585	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,598	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,606	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,613	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,621	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,629	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,640	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,651	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,659	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,667	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,675	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,682	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,697	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,706	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,713	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,722	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,730	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,745	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,755	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,765	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,773	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,781	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,795	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,805	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,814	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,823	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,832	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,846	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,856	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,865	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,874	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,881	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,894	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,904	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
2021-08-31 20:54:35,912	WARNING worker.py:498 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
```
and on and on.

The log is confusing and very spammy. Is it expected?

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by xwjiang2010** [comment]
@richardliaw Am I missing something? Taking out all console print helps reduce our latency of a sample job from 32s to 24s. This one is particularly confusing to me.

**Comment by richardliaw** [comment]
Seems really spammy; maybe we should use `ray.util.debug.log_once` to gate it?

**Comment by xwjiang2010** [comment]
Yes, I am going to send out a PR to gate it.
On top of it, I want to understand why this function is even invoked to understand any additional overhead. Raised an Exception like @amogkam suggested.

The following is the stacktrace:
```
2021-09-01 11:45:55,340	ERROR remote_function.py:309 -- SystemExit was raised from the worker
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 648, in ray._raylet.task_execution_handler
    execute_task(task_type, task_name, ray_function, c_resources,
  File "python/ray/_raylet.pyx", line 419, in ray._raylet.execute_task
    ray._private.utils.set_cuda_visible_devices(ray.get_gpu_ids())
  File "/Users/xwjiang/ray/python/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/Users/xwjiang/ray/python/ray/worker.py", line 497, in get_gpu_ids
    raise Exception
```
Note, my train function in this case is not even put as a remote task. 
Seems like we have quite some overhead associated with trials running in single process mode. We need to understand those to analyze the headroom we have against Optuna in a similar setup.

**Comment by xwjiang2010** [comment]
btw, seems in my setup, using `log_once` == turning off the entire logging, as `_disabled` == False in my setup. I will leave it to Core team to see if this is acceptable.

**Comment by xwjiang2010** [comment]
```
(Pdb) w
  /Users/matt/workspace/scratch/tune/gpu.py(18)<module>()
-> tune.run(train, config={"x": tune.uniform(-10, 10)}, num_samples=2000) #, log_to_file="/tmp/log.txt")
  /Users/matt/workspace/ray/python/ray/tune/tune.py(585)run()
-> runner.step()
  /Users/matt/workspace/ray/python/ray/tune/trial_runner.py(594)step()
-> self.trial_executor.stage_and_update_status(self._live_trials)
  /Users/matt/workspace/ray/python/ray/tune/ray_trial_executor.py(242)stage_and_update_status()
-> if not self._pg_manager.stage_trial_pg(trial):
  /Users/matt/workspace/ray/python/ray/tune/utils/placement_groups.py(347)stage_trial_pg()
-> return self._stage_pgf_pg(pgf)
  /Users/matt/workspace/ray/python/ray/tune/utils/placement_groups.py(355)_stage_pgf_pg()
-> self._staging_futures[pg.ready()] = (pgf, pg)
  /Users/matt/workspace/ray/python/ray/util/placement_group.py(73)ready()
-> return bundle_reservation_check.options(
  /Users/matt/workspace/ray/python/ray/remote_function.py(160)remote()
-> return func_cls._remote(
  /Users/matt/workspace/ray/python/ray/util/tracing/tracing_helper.py(292)_invocation_remote_span()
-> return method(self, args, kwargs, *_args, **_kwargs)
  /Users/matt/workspace/ray/python/ray/remote_function.py(335)_remote()
-> return invocation(args, kwargs)
  /Users/matt/workspace/ray/python/ray/remote_function.py(309)invocation()
-> object_refs = worker.core_worker.submit_task(
  /Users/matt/workspace/ray/python/ray/_private/client_mode_hook.py(89)wrapper()
-> return func(*args, **kwargs)
> /Users/matt/workspace/ray/python/ray/worker.py(498)get_gpu_ids()
-> if worker.mode != WORKER_MODE:```
```

**Comment by xwjiang2010** [comment]
Maybe I should look into why placement group logic is still there for local mode...

**Comment by richardliaw** [comment]
We should try not to special case local mode execution
