### ISSUE TITLE
[rllib] A3C error: AttributeError: 'RolloutWorker' object has no attribute 'tf_sess'

### ISSUE THREAD

**Issue by yarik1988** [ray-project/ray#18280]
OS: Windows 10
Tensorflow version: 2.6.0 (tensorflow-gpu)
Python version: 3.9.7
Ray version:1.6.0 (installed from pip)

A3C agent gives error on train() when I try to train multi-agent toy example

```
import ray
from ray.rllib.agents.a3c import A3CTrainer
from ray.rllib.policy.policy import PolicySpec
from ray.rllib.examples.env.multi_agent import MultiAgentCartPole
ray.init()
policies = {
    "policy_0": PolicySpec(config={"gamma": 0.99}),
    "policy_1": PolicySpec(config={"gamma": 0.95}),
}
policy_ids = list(policies.keys())


def policy_mapping_fn(agent_id, episode, **kwargs):
    pol_id = policy_ids[agent_id]
    return pol_id


trainer = A3CTrainer(env=MultiAgentCartPole, config={
    "multiagent": {"policies": policies,  "policy_mapping_fn": policy_mapping_fn}})
trainer.train()
```

Meanwhile, A2CTrainer works just fine. Here is error log
```
Traceback (most recent call last):
  File "C:\GITHUB\RLlib_projects\PredatorVictim\test.py", line 20, in <module>
    trainer.train()
  File "C:\Program Files\Python39\lib\site-packages\ray\rllib\agents\trainer.py", line 648, in train
    raise e
  File "C:\Program Files\Python39\lib\site-packages\ray\rllib\agents\trainer.py", line 637, in train
    result = Trainable.train(self)
  File "C:\Program Files\Python39\lib\site-packages\ray\tune\trainable.py", line 237, in train
    result = self.step()
  File "C:\Program Files\Python39\lib\site-packages\ray\rllib\agents\trainer_template.py", line 193, in step
    res = next(self.train_exec_impl)
  File "C:\Program Files\Python39\lib\site-packages\ray\util\iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "C:\Program Files\Python39\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Program Files\Python39\lib\site-packages\ray\util\iter.py", line 843, in apply_filter
    for item in it:
  File "C:\Program Files\Python39\lib\site-packages\ray\util\iter.py", line 843, in apply_filter
    for item in it:
  File "C:\Program Files\Python39\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Program Files\Python39\lib\site-packages\ray\util\iter.py", line 828, in add_wait_hooks
    item = next(it)
  File "C:\Program Files\Python39\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Program Files\Python39\lib\site-packages\ray\util\iter.py", line 551, in base_iterator
    batch = ray.get(obj_ref)
  File "C:\Program Files\Python39\lib\site-packages\ray\_private\client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\ray\worker.py", line 1621, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::RolloutWorker.par_iter_next_batch() (pid=7472, ip=192.168.0.138, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001C2F00E63D0>)
  File "python\ray\_raylet.pyx", line 536, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 486, in ray._raylet.execute_task.function_executor
  File "C:\Program Files\Python39\lib\site-packages\ray\_private\function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\ray\util\iter.py", line 1157, in par_iter_next_batch
    batch.append(self.par_iter_next())
  File "C:\Program Files\Python39\lib\site-packages\ray\util\iter.py", line 1151, in par_iter_next
    return next(self.local_it)
  File "C:\Program Files\Python39\lib\site-packages\ray\util\iter.py", line 791, in apply_foreach
    result = fn(item)
  File "C:\Program Files\Python39\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 122, in samples_to_grads
    return get_global_worker().compute_gradients(samples), samples.count
  File "C:\Program Files\Python39\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 856, in compute_gradients
    if self.tf_sess is not None:
AttributeError: 'RolloutWorker' object has no attribute 'tf_sess'
```

**Comment by sven1977** [comment]
Hey @yarik1988 , thanks for filing this issue! Here is the PR that fixes the problem:
https://github.com/ray-project/ray/pull/19100
