### ISSUE TITLE
Travis test failure in xray_test.py.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1828]
I've seen the following error.

```
$ python -m pytest test/xray_test.py

[1m============================= test session starts ==============================[0m

platform darwin -- Python 3.6.4, pytest-3.5.0, py-1.5.3, pluggy-0.6.0

rootdir: /Users/travis/build/ray-project/ray, inifile:

[1m
collecting 0 items                                                             [0m[1m
collecting 1 item                                                              [0m[1m
collected 1 item                                                               [0m



test/xray_test.py E[36m                                                      [100%][0m



==================================== ERRORS ====================================

____________________ ERROR at setup of test_basic_task_api _____________________



self = Connection<host=10.182.9.118,port=32049,db=0>



[1m    def connect(self):[0m

[1m        "Connects to the Redis server if not already connected"[0m

[1m        if self._sock:[0m

[1m            return[0m

[1m        try:[0m

[1m>           sock = self._connect()[0m



[1m[31m../../../.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py[0m:484: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 



self = Connection<host=10.182.9.118,port=32049,db=0>



[1m    def _connect(self):[0m

[1m        "Create a TCP socket connection"[0m

[1m        # we want to mimic what socket.create_connection does to support[0m

[1m        # ipv4/ipv6, but we want to set options prior to calling[0m

[1m        # socket.connect()[0m

[1m        err = None[0m

[1m        for res in socket.getaddrinfo(self.host, self.port, 0,[0m

[1m                                      socket.SOCK_STREAM):[0m

[1m            family, socktype, proto, canonname, socket_address = res[0m

[1m            sock = None[0m

[1m            try:[0m

[1m                sock = socket.socket(family, socktype, proto)[0m

[1m                # TCP_NODELAY[0m

[1m                sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)[0m

[1m    [0m

[1m                # TCP_KEEPALIVE[0m

[1m                if self.socket_keepalive:[0m

[1m                    sock.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)[0m

[1m                    for k, v in iteritems(self.socket_keepalive_options):[0m

[1m                        sock.setsockopt(socket.SOL_TCP, k, v)[0m

[1m    [0m

[1m                # set the socket_connect_timeout before we connect[0m

[1m                sock.settimeout(self.socket_connect_timeout)[0m

[1m    [0m

[1m                # connect[0m

[1m                sock.connect(socket_address)[0m

[1m    [0m

[1m                # set the socket_timeout now that we're connected[0m

[1m                sock.settimeout(self.socket_timeout)[0m

[1m                return sock[0m

[1m    [0m

[1m            except socket.error as _:[0m

[1m                err = _[0m

[1m                if sock is not None:[0m

[1m                    sock.close()[0m

[1m    [0m

[1m        if err is not None:[0m

[1m>           raise err[0m



[1m[31m../../../.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py[0m:541: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 



self = Connection<host=10.182.9.118,port=32049,db=0>



[1m    def _connect(self):[0m

[1m        "Create a TCP socket connection"[0m

[1m        # we want to mimic what socket.create_connection does to support[0m

[1m        # ipv4/ipv6, but we want to set options prior to calling[0m

[1m        # socket.connect()[0m

[1m        err = None[0m

[1m        for res in socket.getaddrinfo(self.host, self.port, 0,[0m

[1m                                      socket.SOCK_STREAM):[0m

[1m            family, socktype, proto, canonname, socket_address = res[0m

[1m            sock = None[0m

[1m            try:[0m

[1m                sock = socket.socket(family, socktype, proto)[0m

[1m                # TCP_NODELAY[0m

[1m                sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)[0m

[1m    [0m

[1m                # TCP_KEEPALIVE[0m

[1m                if self.socket_keepalive:[0m

[1m                    sock.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)[0m

[1m                    for k, v in iteritems(self.socket_keepalive_options):[0m

[1m                        sock.setsockopt(socket.SOL_TCP, k, v)[0m

[1m    [0m

[1m                # set the socket_connect_timeout before we connect[0m

[1m                sock.settimeout(self.socket_connect_timeout)[0m

[1m    [0m

[1m                # connect[0m

[1m>               sock.connect(socket_address)[0m

[1m[31mE               OSError: [Errno 51] Network is unreachable[0m



[1m[31m../../../.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py[0m:529: OSError



[33mDuring handling of the above exception, another exception occurred:[0m



self = StrictRedis<ConnectionPool<Connection<host=10.182.9.118,port=32049,db=0>>>

args = ('GET', 'VERSION_INFO'), options = {}

pool = ConnectionPool<Connection<host=10.182.9.118,port=32049,db=0>>

command_name = 'GET', connection = Connection<host=10.182.9.118,port=32049,db=0>



[1m    def execute_command(self, *args, **options):[0m

[1m        "Execute a command and return a parsed response"[0m

[1m        pool = self.connection_pool[0m

[1m        command_name = args[0][0m

[1m        connection = pool.get_connection(command_name, **options)[0m

[1m        try:[0m

[1m>           connection.send_command(*args)[0m



[1m[31m../../../.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/client.py[0m:667: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 



self = Connection<host=10.182.9.118,port=32049,db=0>

args = ('GET', 'VERSION_INFO')



[1m    def send_command(self, *args):[0m

[1m        "Pack and send a command to the Redis server"[0m

[1m>       self.send_packed_command(self.pack_command(*args))[0m



[1m[31m../../../.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py[0m:610: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 



self = Connection<host=10.182.9.118,port=32049,db=0>

command = [b'*2\r\n$3\r\nGET\r\n$12\r\nVERSION_INFO\r\n']



[1m    def send_packed_command(self, command):[0m

[1m        "Send an already packed command to the Redis server"[0m

[1m        if not self._sock:[0m

[1m>           self.connect()[0m



[1m[31m../../../.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py[0m:585: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 



self = Connection<host=10.182.9.118,port=32049,db=0>



[1m    def connect(self):[0m

[1m        "Connects to the Redis server if not already connected"[0m

[1m        if self._sock:[0m

[1m            return[0m

[1m        try:[0m

[1m            sock = self._connect()[0m

[1m        except socket.timeout:[0m

[1m            raise TimeoutError("Timeout connecting to server")[0m

[1m        except socket.error:[0m

[1m            e = sys.exc_info()[1][0m

[1m>           raise ConnectionError(self._error_message(e))[0m

[1m[31mE           redis.exceptions.ConnectionError: Error 51 connecting to 10.182.9.118:32049. Network is unreachable.[0m



[1m[31m../../../.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py[0m:489: ConnectionError



[33mDuring handling of the above exception, another exception occurred:[0m



self = Connection<host=10.182.9.118,port=32049,db=0>



[1m    def connect(self):[0m

[1m        "Connects to the Redis server if not already connected"[0m

[1m        if self._sock:[0m

[1m            return[0m

[1m        try:[0m

[1m>           sock = self._connect()[0m



[1m[31m../../../.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py[0m:484: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 



self = Connection<host=10.182.9.118,port=32049,db=0>



[1m    def _connect(self):[0m

[1m        "Create a TCP socket connection"[0m

[1m        # we want to mimic what socket.create_connection does to support[0m

[1m        # ipv4/ipv6, but we want to set options prior to calling[0m

[1m        # socket.connect()[0m

[1m        err = None[0m

[1m        for res in socket.getaddrinfo(self.host, self.port, 0,[0m

[1m                                      socket.SOCK_STREAM):[0m

[1m            family, socktype, proto, canonname, socket_address = res[0m

[1m            sock = None[0m

[1m            try:[0m

[1m                sock = socket.socket(family, socktype, proto)[0m

[1m                # TCP_NODELAY[0m

[1m                sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)[0m

[1m    [0m

[1m                # TCP_KEEPALIVE[0m

[1m                if self.socket_keepalive:[0m

[1m                    sock.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)[0m

[1m                    for k, v in iteritems(self.socket_keepalive_options):[0m

[1m                        sock.setsockopt(socket.SOL_TCP, k, v)[0m

[1m    [0m

[1m                # set the socket_connect_timeout before we connect[0m

[1m                sock.settimeout(self.socket_connect_timeout)[0m

[1m    [0m

[1m                # connect[0m

[1m                sock.connect(socket_address)[0m

[1m    [0m

[1m                # set the socket_timeout now that we're connected[0m

[1m                sock.settimeout(self.socket_timeout)[0m

[1m                return sock[0m

[1m    [0m

[1m            except socket.error as _:[0m

[1m                err = _[0m

[1m                if sock is not None:[0m

[1m                    sock.close()[0m

[1m    [0m

[1m        if err is not None:[0m

[1m>           raise err[0m



[1m[31m../../../.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py[0m:541: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 



self = Connection<host=10.182.9.118,port=32049,db=0>



[1m    def _connect(self):[0m

[1m        "Create a TCP socket connection"[0m

[1m        # we want to mimic what socket.create_connection does to support[0m

[1m        # ipv4/ipv6, but we want to set options prior to calling[0m

[1m        # socket.connect()[0m

[1m        err = None[0m

[1m        for res in socket.getaddrinfo(self.host, self.port, 0,[0m

[1m                                      socket.SOCK_STREAM):[0m

[1m            family, socktype, proto, canonname, socket_address = res[0m

[1m            sock = None[0m

[1m            try:[0m

[1m                sock = socket.socket(family, socktype, proto)[0m

[1m                # TCP_NODELAY[0m

[1m                sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)[0m

[1m    [0m

[1m                # TCP_KEEPALIVE[0m

[1m                if self.socket_keepalive:[0m

[1m                    sock.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)[0m

[1m                    for k, v in iteritems(self.socket_keepalive_options):[0m

[1m                        sock.setsockopt(socket.SOL_TCP, k, v)[0m

[1m    [0m

[1m                # set the socket_connect_timeout before we connect[0m

[1m                sock.settimeout(self.socket_connect_timeout)[0m

[1m    [0m

[1m                # connect[0m

[1m>               sock.connect(socket_address)[0m

[1m[31mE               OSError: [Errno 51] Network is unreachable[0m



[1m[31m../../../.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py[0m:529: OSError



[33mDuring handling of the above exception, another exception occurred:[0m



[1m    @pytest.fixture[0m

[1m    def ray_start():[0m

[1m        # Start the Ray processes.[0m

[1m>       ray.init(num_cpus=1, use_raylet=True)[0m



[1m[31mtest/xray_test.py[0m:12: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

[1m[31m../../../.local/lib/python3.6/site-packages/ray-0.4.0-py3.6-macosx-10.7-x86_64.egg/ray/worker.py[0m:1604: in init

[1m    use_raylet=use_raylet)[0m

[1m[31m../../../.local/lib/python3.6/site-packages/ray-0.4.0-py3.6-macosx-10.7-x86_64.egg/ray/worker.py[0m:1519: in _init

[1m    mode=driver_mode, worker=global_worker, use_raylet=use_raylet)[0m

[1m[31m../../../.local/lib/python3.6/site-packages/ray-0.4.0-py3.6-macosx-10.7-x86_64.egg/ray/worker.py[0m:1935: in connect

[1m    raise e[0m

[1m[31m../../../.local/lib/python3.6/site-packages/ray-0.4.0-py3.6-macosx-10.7-x86_64.egg/ray/worker.py[0m:1932: in connect

[1m    ray.services.check_version_info(worker.redis_client)[0m

[1m[31m../../../.local/lib/python3.6/site-packages/ray-0.4.0-py3.6-macosx-10.7-x86_64.egg/ray/services.py[0m:371: in check_version_info

[1m    redis_reply = redis_client.get("VERSION_INFO")[0m

[1m[31m../../../.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/client.py[0m:976: in get

[1m    return self.execute_command('GET', name)[0m

[1m[31m../../../.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/client.py[0m:673: in execute_command

[1m    connection.send_command(*args)[0m

[1m[31m../../../.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py[0m:610: in send_command

[1m    self.send_packed_command(self.pack_command(*args))[0m

[1m[31m../../../.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py[0m:585: in send_packed_command

[1m    self.connect()[0m

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 



self = Connection<host=10.182.9.118,port=32049,db=0>



[1m    def connect(self):[0m

[1m        "Connects to the Redis server if not already connected"[0m

[1m        if self._sock:[0m

[1m            return[0m

[1m        try:[0m

[1m            sock = self._connect()[0m

[1m        except socket.timeout:[0m

[1m            raise TimeoutError("Timeout connecting to server")[0m

[1m        except socket.error:[0m

[1m            e = sys.exc_info()[1][0m

[1m>           raise ConnectionError(self._error_message(e))[0m

[1m[31mE           redis.exceptions.ConnectionError: Error 51 connecting to 10.182.9.118:32049. Network is unreachable.[0m



[1m[31m../../../.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py[0m:489: ConnectionError

---------------------------- Captured stdout setup -----------------------------

Process STDOUT and STDERR is being redirected to /tmp/raylogs/.

Waiting for redis server at 127.0.0.1:32049 to respond...

Waiting for redis server at 127.0.0.1:59718 to respond...

Failed to start the UI, you may need to run 'pip install jupyter'.

---------------------------- Captured stderr setup -----------------------------

/Users/travis/build/ray-project/ray/src/ray/raylet/main.cc:41: Initializing GCS client d5c79f669770c12aa77e08f718f4f31efcf966ed

/Users/travis/build/ray-project/ray/src/ray/gcs/redis_context.cc:150: Failed to connect to Redis, retrying.

[31m[1m=========================== 1 error in 2.08 seconds ============================[0m

Error in atexit._run_exitfuncs:

Traceback (most recent call last):

  File "/Users/travis/.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 484, in connect

    sock = self._connect()

  File "/Users/travis/.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 541, in _connect

    raise err

  File "/Users/travis/.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 529, in _connect

    sock.connect(socket_address)

OSError: [Errno 51] Network is unreachable



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/Users/travis/.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/client.py", line 667, in execute_command

    connection.send_command(*args)

  File "/Users/travis/.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 610, in send_command

    self.send_packed_command(self.pack_command(*args))

  File "/Users/travis/.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 585, in send_packed_command

    self.connect()

  File "/Users/travis/.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 489, in connect

    raise ConnectionError(self._error_message(e))

redis.exceptions.ConnectionError: Error 51 connecting to 10.182.9.118:32049. Network is unreachable.



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/Users/travis/.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 484, in connect

    sock = self._connect()

  File "/Users/travis/.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 541, in _connect

    raise err

  File "/Users/travis/.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 529, in _connect

    sock.connect(socket_address)

OSError: [Errno 51] Network is unreachable



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/Users/travis/.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/client.py", line 673, in execute_command

    connection.send_command(*args)

  File "/Users/travis/.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 610, in send_command

    self.send_packed_command(self.pack_command(*args))

  File "/Users/travis/.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 585, in send_packed_command

    self.connect()

  File "/Users/travis/.local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 489, in connect

    raise ConnectionError(self._error_message(e))

redis.exceptions.ConnectionError: Error 51 connecting to 10.182.9.118:32049. Network is unreachable.



travis_time:end:2917c632:start=1522832076099636000,finish=1522832078845487000,duration=2745851000
[0K

[31;1mThe command "python -m pytest test/xray_test.py" exited with 1.
```

**Comment by stephanie-wang** [comment]
Looks like it might be that workers are still alive when Redis is taken down. Maybe change the issue description to something like "clean up worker processes when node manager exits"?

**Comment by robertnishihara** [comment]
Closing because I haven't seen this in a while.
