### ISSUE TITLE
[tune] atari-impala-large.yaml does not finish gracefully

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#18325]
while all the trials terminated, there seems to be a sys exit from the worker for some reason. 
CC @sven1977 @richardliaw 
```
(run_experiments pid=260) == Status ==
(run_experiments pid=260) Memory usage on this node: 19.7/58.9 GiB
(run_experiments pid=260) Using FIFO scheduling algorithm.
(run_experiments pid=260) Resources requested: 0/144 CPUs, 0/1 GPUs, 0.0/386.68 GiB heap, 0.0/168.24 GiB objects (0.0/1.0 accelerator_type:T4)
(run_experiments pid=260) Result logdir: /home/ray/ray_results/atari-impala
(run_experiments pid=260) Number of trials: 4/4 (4 TERMINATED)
(run_experiments pid=260) +------------------------------------------------+------------+-------+-----------------------------+--------+------------------+---------+----------+----------------------+----------------------+--------------------+
(run_experiments pid=260) | Trial name                                     | status     | loc   | env                         |   iter |   total time (s) |      ts |   reward |   episode_reward_max |   episode_reward_min |   episode_len_mean |
(run_experiments pid=260) |------------------------------------------------+------------+-------+-----------------------------+--------+------------------+---------+----------+----------------------+----------------------+--------------------|
(run_experiments pid=260) | IMPALA_BreakoutNoFrameskip-v4_aab1f_00000      | TERMINATED |       | BreakoutNoFrameskip-v4      |     26 |          256.486 | 3114000 |  31.8742 |                  235 |                   13 |            3062.35 |
(run_experiments pid=260) | IMPALA_BeamRiderNoFrameskip-v4_aab1f_00001     | TERMINATED |       | BeamRiderNoFrameskip-v4     |     26 |          255.359 | 3053500 | 477.68   |                  996 |                  132 |            5487.68 |
(run_experiments pid=260) | IMPALA_QbertNoFrameskip-v4_aab1f_00002         | TERMINATED |       | QbertNoFrameskip-v4         |     26 |          256.11  | 3058500 | 398.786  |                 1250 |                  125 |            1738.21 |
(run_experiments pid=260) | IMPALA_SpaceInvadersNoFrameskip-v4_aab1f_00003 | TERMINATED |       | SpaceInvadersNoFrameskip-v4 |     26 |          255.919 | 3061500 | 318.769  |                  830 |                  120 |            2595.36 |
(run_experiments pid=260) +------------------------------------------------+------------+-------+-----------------------------+--------+------------------+---------+----------+----------------------+----------------------+--------------------+
(run_experiments pid=260) 
(run_experiments pid=260) 
(pid=29669, ip=10.20.7.131) 2021-09-02 20:44:49,284	ERROR worker.py:429 -- SystemExit was raised from the worker
(pid=29669, ip=10.20.7.131) Traceback (most recent call last):
(pid=29669, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 679, in ray._raylet.task_execution_handler
(pid=29669, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 524, in ray._raylet.execute_task
(pid=29669, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 561, in ray._raylet.execute_task
(pid=29669, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 568, in ray._raylet.execute_task
(pid=29669, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 572, in ray._raylet.execute_task
(pid=29669, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 522, in ray._raylet.execute_task.function_executor
(pid=29669, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 577, in actor_method_executor
(pid=29669, ip=10.20.7.131)     return method(__ray_actor, *args, **kwargs)
(pid=29669, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 1041, in __ray_terminate__
(pid=29669, ip=10.20.7.131)     ray.actor.exit_actor()
(pid=29669, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 1103, in exit_actor
(pid=29669, ip=10.20.7.131)     ray.worker.disconnect()
(pid=29669, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1490, in disconnect
(pid=29669, ip=10.20.7.131)     worker.import_thread.join_import_thread()
(pid=29669, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/import_thread.py", line 50, in join_import_thread
(pid=29669, ip=10.20.7.131)     self.t.join()
(pid=29669, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/threading.py", line 1044, in join
(pid=29669, ip=10.20.7.131)     self._wait_for_tstate_lock()
(pid=29669, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
(pid=29669, ip=10.20.7.131)     elif lock.acquire(block, timeout):
(pid=29669, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 426, in sigterm_handler
(pid=29669, ip=10.20.7.131)     sys.exit(1)
(pid=29669, ip=10.20.7.131) SystemExit: 1
(pid=29673, ip=10.20.7.131) 2021-09-02 20:44:49,277	ERROR worker.py:429 -- SystemExit was raised from the worker
(pid=29673, ip=10.20.7.131) Traceback (most recent call last):
(pid=29673, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 568, in ray._raylet.execute_task
(pid=29673, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 572, in ray._raylet.execute_task
(pid=29673, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 522, in ray._raylet.execute_task.function_executor
(pid=29673, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 577, in actor_method_executor
(pid=29673, ip=10.20.7.131)     return method(__ray_actor, *args, **kwargs)
(pid=29673, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 1041, in __ray_terminate__
(pid=29673, ip=10.20.7.131)     ray.actor.exit_actor()
(pid=29673, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 1117, in exit_actor
(pid=29673, ip=10.20.7.131)     raise exit
(pid=29673, ip=10.20.7.131) SystemExit: 0
(pid=29673, ip=10.20.7.131) 
(pid=29673, ip=10.20.7.131) During handling of the above exception, another exception occurred:
(pid=29673, ip=10.20.7.131) 
(pid=29673, ip=10.20.7.131) Traceback (most recent call last):
(pid=29673, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 679, in ray._raylet.task_execution_handler
(pid=29673, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 524, in ray._raylet.execute_task
(pid=29673, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 561, in ray._raylet.execute_task
(pid=29673, ip=10.20.7.131)   File "python/ray/includes/libcoreworker.pxi", line 33, in ray._raylet.ProfileEvent.__exit__
(pid=29673, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 167, in format_exc
(pid=29673, ip=10.20.7.131)     return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
(pid=29673, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 121, in format_exception
(pid=29673, ip=10.20.7.131)     type(value), value, tb, limit=limit).format(chain=chain))
(pid=29673, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 508, in __init__
(pid=29673, ip=10.20.7.131)     capture_locals=capture_locals)
(pid=29673, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 363, in extract
(pid=29673, ip=10.20.7.131)     f.line
(pid=29673, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 285, in line
(pid=29673, ip=10.20.7.131)     self._line = linecache.getline(self.filename, self.lineno).strip()
(pid=29673, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/linecache.py", line 16, in getline
(pid=29673, ip=10.20.7.131)     lines = getlines(filename, module_globals)
(pid=29673, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/linecache.py", line 47, in getlines
(pid=29673, ip=10.20.7.131)     return updatecache(filename, module_globals)
(pid=29673, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/linecache.py", line 137, in updatecache
(pid=29673, ip=10.20.7.131)     lines = fp.readlines()
(pid=29673, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/codecs.py", line 319, in decode
(pid=29673, ip=10.20.7.131)     def decode(self, input, final=False):
(pid=29673, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 426, in sigterm_handler
(pid=29673, ip=10.20.7.131)     sys.exit(1)
(pid=29673, ip=10.20.7.131) SystemExit: 1
(pid=29686, ip=10.20.7.131) 2021-09-02 20:44:49,277	ERROR worker.py:429 -- SystemExit was raised from the worker
(pid=29686, ip=10.20.7.131) Traceback (most recent call last):
(pid=29686, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 568, in ray._raylet.execute_task
(pid=29686, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 572, in ray._raylet.execute_task
(pid=29686, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 522, in ray._raylet.execute_task.function_executor
(pid=29686, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 577, in actor_method_executor
(pid=29686, ip=10.20.7.131)     return method(__ray_actor, *args, **kwargs)
(pid=29686, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 1041, in __ray_terminate__
(pid=29686, ip=10.20.7.131)     ray.actor.exit_actor()
(pid=29686, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 1117, in exit_actor
(pid=29686, ip=10.20.7.131)     raise exit
(pid=29686, ip=10.20.7.131) SystemExit: 0
(pid=29686, ip=10.20.7.131) 
(pid=29686, ip=10.20.7.131) During handling of the above exception, another exception occurred:
(pid=29686, ip=10.20.7.131) 
(pid=29686, ip=10.20.7.131) Traceback (most recent call last):
(pid=29686, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 679, in ray._raylet.task_execution_handler
(pid=29686, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 524, in ray._raylet.execute_task
(pid=29686, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 561, in ray._raylet.execute_task
(pid=29686, ip=10.20.7.131)   File "python/ray/includes/libcoreworker.pxi", line 33, in ray._raylet.ProfileEvent.__exit__
(pid=29686, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 167, in format_exc
(pid=29686, ip=10.20.7.131)     return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
(pid=29686, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 121, in format_exception
(pid=29686, ip=10.20.7.131)     type(value), value, tb, limit=limit).format(chain=chain))
(pid=29686, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 508, in __init__
(pid=29686, ip=10.20.7.131)     capture_locals=capture_locals)
(pid=29686, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 363, in extract
(pid=29686, ip=10.20.7.131)     f.line
(pid=29686, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 285, in line
(pid=29686, ip=10.20.7.131)     self._line = linecache.getline(self.filename, self.lineno).strip()
(pid=29686, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/linecache.py", line 16, in getline
(pid=29686, ip=10.20.7.131)     lines = getlines(filename, module_globals)
(pid=29686, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/linecache.py", line 47, in getlines
(pid=29686, ip=10.20.7.131)     return updatecache(filename, module_globals)
(pid=29686, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/linecache.py", line 137, in updatecache
(pid=29686, ip=10.20.7.131)     lines = fp.readlines()
(pid=29686, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/codecs.py", line 322, in decode
(pid=29686, ip=10.20.7.131)     (result, consumed) = self._buffer_decode(data, self.errors, final)
(pid=29686, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 426, in sigterm_handler
(pid=29686, ip=10.20.7.131)     sys.exit(1)
(pid=29686, ip=10.20.7.131) SystemExit: 1
(pid=29676, ip=10.20.7.131) 2021-09-02 20:44:49,277	ERROR worker.py:429 -- SystemExit was raised from the worker
(pid=29676, ip=10.20.7.131) Traceback (most recent call last):
(pid=29676, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 568, in ray._raylet.execute_task
(pid=29676, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 572, in ray._raylet.execute_task
(pid=29676, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 522, in ray._raylet.execute_task.function_executor
(pid=29676, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 577, in actor_method_executor
(pid=29676, ip=10.20.7.131)     return method(__ray_actor, *args, **kwargs)
(pid=29676, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 1041, in __ray_terminate__
(pid=29676, ip=10.20.7.131)     ray.actor.exit_actor()
(pid=29676, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 1117, in exit_actor
(pid=29676, ip=10.20.7.131)     raise exit
(pid=29676, ip=10.20.7.131) SystemExit: 0
(pid=29676, ip=10.20.7.131) 
(pid=29676, ip=10.20.7.131) During handling of the above exception, another exception occurred:
(pid=29676, ip=10.20.7.131) 
(pid=29676, ip=10.20.7.131) Traceback (most recent call last):
(pid=29676, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 679, in ray._raylet.task_execution_handler
(pid=29676, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 524, in ray._raylet.execute_task
(pid=29676, ip=10.20.7.131)   File "python/ray/_raylet.pyx", line 561, in ray._raylet.execute_task
(pid=29676, ip=10.20.7.131)   File "python/ray/includes/libcoreworker.pxi", line 33, in ray._raylet.ProfileEvent.__exit__
(pid=29676, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 167, in format_exc
(pid=29676, ip=10.20.7.131)     return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
(pid=29676, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 121, in format_exception
(pid=29676, ip=10.20.7.131)     type(value), value, tb, limit=limit).format(chain=chain))
(pid=29676, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 508, in __init__
(pid=29676, ip=10.20.7.131)     capture_locals=capture_locals)
(pid=29676, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 363, in extract
(pid=29676, ip=10.20.7.131)     f.line
(pid=29676, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 285, in line
(pid=29676, ip=10.20.7.131)     self._line = linecache.getline(self.filename, self.lineno).strip()
(pid=29676, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/linecache.py", line 16, in getline
(pid=29676, ip=10.20.7.131)     lines = getlines(filename, module_globals)
(pid=29676, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/linecache.py", line 47, in getlines
(pid=29676, ip=10.20.7.131)     return updatecache(filename, module_globals)
(pid=29676, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/linecache.py", line 137, in updatecache
(pid=29676, ip=10.20.7.131)     lines = fp.readlines()
(pid=29676, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/codecs.py", line 319, in decode
(pid=29676, ip=10.20.7.131)     def decode(self, input, final=False):
(pid=29676, ip=10.20.7.131)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 426, in sigterm_handler
(pid=29676, ip=10.20.7.131)     sys.exit(1)
(pid=29676, ip=10.20.7.131) SystemExit: 1
(pid=29730, ip=10.20.7.3) 2021-09-02 20:44:49,281	ERROR worker.py:429 -- SystemExit was raised from the worker
(pid=29730, ip=10.20.7.3) Traceback (most recent call last):
(pid=29730, ip=10.20.7.3)   File "python/ray/_raylet.pyx", line 679, in ray._raylet.task_execution_handler
(pid=29730, ip=10.20.7.3)   File "python/ray/_raylet.pyx", line 524, in ray._raylet.execute_task
(pid=29730, ip=10.20.7.3)   File "python/ray/_raylet.pyx", line 561, in ray._raylet.execute_task
(pid=29730, ip=10.20.7.3)   File "python/ray/_raylet.pyx", line 568, in ray._raylet.execute_task
(pid=29730, ip=10.20.7.3)   File "python/ray/_raylet.pyx", line 572, in ray._raylet.execute_task
(pid=29730, ip=10.20.7.3)   File "python/ray/_raylet.pyx", line 522, in ray._raylet.execute_task.function_executor
(pid=29730, ip=10.20.7.3)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 577, in actor_method_executor
(pid=29730, ip=10.20.7.3)     return method(__ray_actor, *args, **kwargs)
(pid=29730, ip=10.20.7.3)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 1041, in __ray_terminate__
(pid=29730, ip=10.20.7.3)     ray.actor.exit_actor()
(pid=29730, ip=10.20.7.3)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 1103, in exit_actor
(pid=29730, ip=10.20.7.3)     ray.worker.disconnect()
(pid=29730, ip=10.20.7.3)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1490, in disconnect
(pid=29730, ip=10.20.7.3)     worker.import_thread.join_import_thread()
(pid=29730, ip=10.20.7.3)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/import_thread.py", line 50, in join_import_thread
(pid=29730, ip=10.20.7.3)     self.t.join()
(pid=29730, ip=10.20.7.3)   File "/home/ray/anaconda3/lib/python3.7/threading.py", line 1044, in join
(pid=29730, ip=10.20.7.3)     self._wait_for_tstate_lock()
(pid=29730, ip=10.20.7.3)   File "/home/ray/anaconda3/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
(pid=29730, ip=10.20.7.3)     elif lock.acquire(block, timeout):
(pid=29730, ip=10.20.7.3)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 426, in sigterm_handler
(pid=29730, ip=10.20.7.3)     sys.exit(1)
(pid=29730, ip=10.20.7.3) SystemExit: 1
(pid=29658, ip=10.20.8.130) 2021-09-02 20:44:49,277	ERROR worker.py:429 -- SystemExit was raised from the worker
(pid=29658, ip=10.20.8.130) Traceback (most recent call last):
(pid=29658, ip=10.20.8.130)   File "python/ray/_raylet.pyx", line 561, in ray._raylet.execute_task
(pid=29658, ip=10.20.8.130)   File "python/ray/_raylet.pyx", line 568, in ray._raylet.execute_task
(pid=29658, ip=10.20.8.130)   File "python/ray/_raylet.pyx", line 572, in ray._raylet.execute_task
(pid=29658, ip=10.20.8.130)   File "python/ray/_raylet.pyx", line 522, in ray._raylet.execute_task.function_executor
(pid=29658, ip=10.20.8.130)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 577, in actor_method_executor
(pid=29658, ip=10.20.8.130)     return method(__ray_actor, *args, **kwargs)
(pid=29658, ip=10.20.8.130)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 1041, in __ray_terminate__
(pid=29658, ip=10.20.8.130)     ray.actor.exit_actor()
(pid=29658, ip=10.20.8.130)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 1117, in exit_actor
(pid=29658, ip=10.20.8.130)     raise exit
(pid=29658, ip=10.20.8.130) SystemExit: 0
(pid=29658, ip=10.20.8.130) 
(pid=29658, ip=10.20.8.130) During handling of the above exception, another exception occurred:
(pid=29658, ip=10.20.8.130) 
(pid=29658, ip=10.20.8.130) Traceback (most recent call last):
(pid=29658, ip=10.20.8.130)   File "python/ray/_raylet.pyx", line 679, in ray._raylet.task_execution_handler
(pid=29658, ip=10.20.8.130)   File "python/ray/_raylet.pyx", line 524, in ray._raylet.execute_task
(pid=29658, ip=10.20.8.130)   File "python/ray/includes/libcoreworker.pxi", line 42, in ray._raylet.ProfileEvent.__exit__
(pid=29658, ip=10.20.8.130)   File "/home/ray/anaconda3/lib/python3.7/json/__init__.py", line 231, in dumps
(pid=29658, ip=10.20.8.130)     return _default_encoder.encode(obj)
(pid=29658, ip=10.20.8.130)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 426, in sigterm_handler
(pid=29658, ip=10.20.8.130)     sys.exit(1)
(pid=29658, ip=10.20.8.130) SystemExit: 1
(pid=29664, ip=10.20.8.130) 2021-09-02 20:44:49,278	ERROR worker.py:429 -- SystemExit was raised from the worker
(pid=29664, ip=10.20.8.130) Traceback (most recent call last):
(pid=29664, ip=10.20.8.130)   File "python/ray/_raylet.pyx", line 568, in ray._raylet.execute_task
(pid=29664, ip=10.20.8.130)   File "python/ray/_raylet.pyx", line 572, in ray._raylet.execute_task
(pid=29664, ip=10.20.8.130)   File "python/ray/_raylet.pyx", line 522, in ray._raylet.execute_task.function_executor
(pid=29664, ip=10.20.8.130)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 577, in actor_method_executor
(pid=29664, ip=10.20.8.130)     return method(__ray_actor, *args, **kwargs)
(pid=29664, ip=10.20.8.130)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 1041, in __ray_terminate__
(pid=29664, ip=10.20.8.130)     ray.actor.exit_actor()
(pid=29664, ip=10.20.8.130)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 1117, in exit_actor
(pid=29664, ip=10.20.8.130)     raise exit
(pid=29664, ip=10.20.8.130) SystemExit: 0
(pid=29664, ip=10.20.8.130) 
(pid=29664, ip=10.20.8.130) During handling of the above exception, another exception occurred:
(pid=29664, ip=10.20.8.130) 
(pid=29664, ip=10.20.8.130) Traceback (most recent call last):
(pid=29664, ip=10.20.8.130)   File "python/ray/_raylet.pyx", line 679, in ray._raylet.task_execution_handler
(pid=29664, ip=10.20.8.130)   File "python/ray/_raylet.pyx", line 524, in ray._raylet.execute_task
(pid=29664, ip=10.20.8.130)   File "python/ray/_raylet.pyx", line 561, in ray._raylet.execute_task
(pid=29664, ip=10.20.8.130)   File "python/ray/includes/libcoreworker.pxi", line 33, in ray._raylet.ProfileEvent.__exit__
(pid=29664, ip=10.20.8.130)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 167, in format_exc
(pid=29664, ip=10.20.8.130)     return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
(pid=29664, ip=10.20.8.130)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 121, in format_exception
(pid=29664, ip=10.20.8.130)     type(value), value, tb, limit=limit).format(chain=chain))
(pid=29664, ip=10.20.8.130)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 508, in __init__
(pid=29664, ip=10.20.8.130)     capture_locals=capture_locals)
(pid=29664, ip=10.20.8.130)   File "/home/ray/anaconda3/lib/python3.7/traceback.py", line 350, in extract
(pid=29664, ip=10.20.8.130)     linecache.lazycache(filename, f.f_globals)
(pid=29664, ip=10.20.8.130)   File "/home/ray/anaconda3/lib/python3.7/linecache.py", line 174, in lazycache
(pid=29664, ip=10.20.8.130)     get_lines = functools.partial(get_source, name)
(pid=29664, ip=10.20.8.130)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 426, in sigterm_handler
(pid=29664, ip=10.20.8.130)     sys.exit(1)
(pid=29664, ip=10.20.8.130) SystemExit: 1
(pid=260) 2021-09-02 20:44:49,426	INFO tune.py:614 -- Total run time: 1555.79 seconds (1555.03 seconds for the tuning loop).
```

### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
This is a core issue. @rkooo567 @scv119 - @AmeerHajAli if possible can you provide repro?

**Comment by rkooo567** [comment]
+1 for repro. Also, what's the version of Ray?

**Comment by rkooo567** [comment]
Keep it triage until there's logs or repro

**Comment by AmeerHajAli** [comment]
I will try to repro. I was able to get to this state by simply running:
`RAY_ADDRESS=anyscale://mycluster?cluster_env=my_cluster_env rllib train -f atari-impala-large.yaml`
I can try to repro in a simpler form...
my_cluster_env should have the following dependencies with the nightly wheels:
<img width="1167" alt="Screen Shot 2021-09-03 at 7 36 11 PM" src="https://user-images.githubusercontent.com/18361764/132039411-404350b4-0c6a-4b2c-a673-81291511f4d8.png">

**Comment by rkooo567** [comment]
There are 2 issues.

1. When the job finishes, the system error shouldn't be raised. 
2. After Ctrl + C and re-run it hangs.

These two shouldn't happen. 

Repro: https://beta.anyscale.com/o/anyscale-internal/projects/prj_MyVW7bByg2bLbXNU6mupEDiL/clusters/ses_F51AUrc4MTZ5xpHn3yYytLSr

command
```
rllib train -f atari-impala-large.yaml
```

**Comment by rkooo567** [comment]
I could reproduce it. It seems like there are some node failures due to heartbeat missing, but I am not 100% sure if this happens due to ray issue since logs were not accessible (alternatively, they could've been killed by autoscaler). We'll do additional investigation next week ). cc @ericl

**Comment by ericl** [comment]
Can you guys narrow down the reproduction to something small? For example, it would be great to know:
- Does this occur in OSS?
- Does it occur without Ray client?
- Does it happen without such a complex training job (e.g., what about a tiny job like `rllib train --run=IMPALA --env=CartPole-v0 --stop='{"time_total_s": 1}'`)

These are things that just take a few minutes once you have the original repro, but is pretty time consuming for someone without the context. If we have a minimal repro, it becomes much more efficient to fix these kind of issues.

Until the repro is narrowed, I'm going to keep the repro tag on and keep at P2

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
