### ISSUE TITLE
[serve] FastAPI deployment shutdown logic isn't called on `Deployment.delete()`

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#18349]
`__del__` nor shutdown events are called:

```python
from ray import serve
from fastapi import FastAPI


serve.start()
app = FastAPI()


@serve.deployment(route_prefix="/")
@serve.ingress(app)
class MyDeployment:
    def __init__(self):
        print("I was called in init!")

    @app.on_event("startup")
    async def startup_event():
        print("I was called in startup!")

    @app.on_event("shutdown")
    async def shutdown_event():
        print("I was not called")

    def __del__(self):
        print("Neither was I")

    @app.get("/")
    async def root(self):
        return f"Hello, world!"


MyDeployment.deploy()
MyDeployment.deploy()
MyDeployment.delete()
```

**Comment by edoakes** [comment]
@simon-mo could you take a look at this please? Context: https://discuss.ray.io/t/cleanup-of-fastapi-deployments/3434

I tried running it locally and observed the same reported behavior (including a sleep at the end of the script to make sure we weren't just swallowing logs).

**Comment by simon-mo** [comment]
@edoakes I think this is because dels are not invoked on ray.kill https://github.com/ray-project/ray/issues/18351. Should we change the semantics there or should we just call del in Serve during graceful shutdown?

**Comment by amiasato** [comment]
2cents here, `kill` semantics usually refer to forced shutdowns, so IMO this behaviour shouldn't be changed in the `Actor` class. The ideal scenario would be to have a single obvious way to cleanup deployment resources, which should also have a configurable timeout for a force kill. Some things to be aware of:

- FastAPI's `startup` and `shutdown` events have no access to `self`, so they are finicky to work with when you want a certain resource to live as an attribute of the deployment.
- `__init__` and `__del__` (and most magic methods) aren't designed to work with async, so waiting for a deletion (in the timeout scenario) will probably be non-trivial.
- The best-of-both-worlds would be using context managers. They are the proper pythonic way of cleaning up resources anyway.

[This SO thread](https://stackoverflow.com/questions/54770360/how-can-i-wait-for-an-objects-del-to-finish-before-the-async-loop-closes) may also help.

**Comment by edoakes** [comment]
@simon-mo I agree with @amiasato that the existing semantics for `kill` make sense to me; we should handle this in the Serve layer.

**Comment by simon-mo** [comment]
Sounds good. I'll proceed with a fix in the Serve layer in this week.

**Comment by amiasato** [comment]
Hello everyone, thanks for the update! However, the example snippet is still not working in the current nightly wheel. The issue was indeed fixed for regular deployments (without FastAPI integration). However, I don't know if this is occurring by this particular PR or any other changes, but in the nightly wheel any FastAPI deployment raises this exception upon exit (without calling the `__del__` method if defined):

```
(pid=25435) 2021-09-27 11:46:54,390     INFO backend_state.py:914 -- Removing 1 replicas from deployment 'MyDeployment'. component=serve deployment=MyDeployment
(pid=25438) 2021-09-27 11:46:56,397     ERROR backend_worker.py:364 -- Exception during graceful shutdown of replica. component=serve deployment=MyDeployment replica=MyDeployment#ChWZrk
(pid=25438) Traceback (most recent call last):
(pid=25438)   File ".../lib/python3.8/site-packages/ray/serve/backend_worker.py", line 362, in prepare_for_shutdown
(pid=25438)     self.callable.__del__()
(pid=25438)   File ".../lib/python3.8/site-packages/ray/serve/api.py", line 604, in __del__
(pid=25438)     asyncio.get_event_loop().run_until_complete(
(pid=25438)   File ".../lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
(pid=25438)     self._check_running()
(pid=25438)   File ".../lib/python3.8/asyncio/base_events.py", line 552, in _check_running
(pid=25438)     raise RuntimeError('This event loop is already running')
(pid=25438) RuntimeError: This event loop is already running
(pid=25438) .../lib/python3.8/site-packages/ray/serve/backend_worker.py:364: RuntimeWarning: coroutine 'LifespanOn.shutdown' was never awaited
(pid=25438)   logger.exception("Exception during graceful shutdown of replica.")
(pid=25438) RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by simon-mo** [comment]
@amiasato do you have a simple repro by any chance? The following test case currently passes so any repro you might have will really help us to fix it.
```
def test_fastapi_shutdown_hook(serve_instance):
    # https://github.com/ray-project/ray/issues/18349
    signal = SignalActor.remote()

    app = FastAPI()

    @app.on_event("shutdown")
    def call_signal():
        signal.send.remote()

    @serve.deployment
    @serve.ingress(app)
    class A:
        pass

    A.deploy()
    A.delete()
    ray.get(signal.wait.remote(), timeout=20)
```

**Comment by amiasato** [comment]
I ran the exact same snippet from the beginning. I also ran the referred test as a standalone script. I wondered if it could be a problem with my env, but with a new conda environemnt, the exception still shows up. I ran the following commands to set up a new env:

```
conda create -n freshenv python=3.9
conda activate freshenv
pip install 'ray[all] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp39-cp39-manylinux2014_x86_64.whl'  # The 'serve' extras misses some dependencies, btw
```

I am using conda-forge as the main channel with a mamba-forge installation, just for the record and in case you think this may have anything to do with the issue.
