### ISSUE TITLE
[core] debugging: The actor died unexpectedly before finishing this task.

### ISSUE THREAD

**Issue by vonHartz** [ray-project/ray#18377]
### What is the problem?
I try to run a simple single-trial tune-run using DQN in a custom environment. For certain configurations I get the infamous `The actor died unexpectedly before finishing this task.` error.

As it happens with a custom environment, I cannot provide a code snippet without external dependencies (I still provided a snippet below anyways.).

However, the issue I want to point out is rather about the **debugging process** anyways.

Ray prints the following logs:
```
2021-09-05 13:40:52,522 WARNING worker.py:1215 -- A worker died or was killed while executing a task by an unexpecte
d system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffa2df291
2c7097e9dde04bb4d01000000 Worker ID: 425d3bf8f1180b2cf6f646b40bf70cde4c13fe99fbce1097f427a5bc Node ID: 447cc8d4f83eb
2e2f86dc7846ffe02f50767e4cfa06b6cc607bbadf8 Worker IP address: XXXX Worker port: 40679 Worker PID: 83296
2021-09-05 13:40:52,708 ERROR trial_runner.py:773 -- Trial DQN_GymEnvWrapper-Atari_f6fb9_00000: Error processing event.
Traceback (most recent call last):
  File "XXX/miniconda3/envs/hiwinr/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 7
39, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "XXX/miniconda3/envs/hiwinr/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py",
line 746, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "XXX/miniconda3/envs/hiwinr/lib/python3.6/site-packages/ray/_private/client_mode_hook.py"
, line 82, in wrapper
    return func(*args, **kwargs)
  File "XXX/miniconda3/envs/hiwinr/lib/python3.6/site-packages/ray/worker.py", line 1623, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
```
Which leads to  `ray.tune.error.TuneError: ('Trials did not complete', [DQN_GymEnvWrapper-Atari_f6fb9_00000])`, fine.

However, when I look into the worker logs, I cannot find anything relevant:

<details>
 <summary>session_2021-09-04_04-57-44_936693_82873/logs/python-core-worker-425d3bf8f1180b2cf6f646b40bf70cde4c13fe99fbce1097f427a5bc_83296.log
</summary>

```
[2021-09-04 04:58:21,665 I 83296 83296] core_worker.cc:152: Constructing CoreWorkerProcess. pid: 83296
[2021-09-04 04:58:21,683 I 83296 83296] grpc_server.cc:71: worker server started, listening on port 40679.
[2021-09-04 04:58:21,689 I 83296 83296] core_worker.cc:438: Initializing worker at address: XXX worker ID 425d3bf8f1180b2cf6f646b40bf70cde4c13fe99fbce1097f427a5bc, raylet 447cc8d4f83eb2e2f86dc7846ffe02f50767e4cfa06b6cc607bbadf8
[2021-09-04 04:58:21,813 I 83296 83296] io_service_pool.cc:35: IOServicePool is running with 1 io_service.
[2021-09-04 04:58:21,813 I 83296 86345] service_based_accessor.cc:610: Received notification for node id = 447cc8d4f83eb2e2f86dc7846ffe02f50767e4cfa06b6cc607bbadf8, IsAlive = 1
[2021-09-04 04:58:22,963 I 83296 83296] core_worker.cc:2332: Finished executing task a67dc375e60ddd1affffffffffffffffffffffff01000000, status=OK
[2021-09-04 04:58:23,037 I 83296 83296] direct_actor_transport.cc:179: Connecting to actor a2df2912c7097e9dde04bb4d01000000 at worker 425d3bf8f1180b2cf6f646b40bf70cde4c13fe99fbce1097f427a5bc
[2021-09-04 04:58:23,038 I 83296 83296] core_worker.cc:2274: Creating actor: a2df2912c7097e9dde04bb4d01000000
[2021-09-04 04:58:38,330 I 83296 83296] core_worker.cc:2332: Finished executing task ffffffffffffffffa2df2912c7097e9dde04bb4d01000000, status=OK
[2021-09-04 04:58:38,331 I 83296 83296] direct_actor_transport.cc:525: Actor creation task finished, task_id: ffffffffffffffffa2df2912c7097e9dde04bb4d01000000, actor_id: a2df2912c7097e9dde04bb4d01000000
[2021-09-04 04:58:47,021 I 83296 83296] core_worker.cc:2332: Finished executing task 69a6825d641b4613a2df2912c7097e9dde04bb4d01000000, status=OK
```
</details>

<details>
 <summary>session_2021-09-04_04-57-44_936693_82873/logs/worker-425d3bf8f1180b2cf6f646b40bf70cde4c13fe99fbce1097f427a5bc-01000000-83296.err
</summary>

```2021-09-04 04:58:35,009 INFO trainer.py:714 -- Tip: set framework=tfe or the --eager flag to enable TensorFlow eager execution
2021-09-04 04:58:35,011 INFO dqn.py:188 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
2021-09-04 04:58:35,013 WARNING deprecation.py:39 -- DeprecationWarning: `callbacks dict interface` has been deprecated. Use `a class extending rllib.agents.callbacks.DefaultCallbacks` instead. This will raise an error in the future!
2021-09-04 04:58:35,015 INFO trainer.py:728 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
2021-09-04 04:58:35,021 WARNING deprecation.py:39 -- DeprecationWarning: `callbacks dict interface` has been deprecated. Use `a class extending rllib.agents.callbacks.DefaultCallbacks` instead. This will raise an error in the future!
2021-09-04 04:58:35,120 WARNING deprecation.py:39 -- DeprecationWarning: `ray.rllib.env.atari_wrappers....` has been deprecated. Use `ray.rllib.env.wrappers.atari_wrappers....` instead. This will raise an error in the future!
2021-09-04 04:58:35.475934: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-09-04 04:58:36,055 WARNING deprecation.py:39 -- DeprecationWarning: `callbacks dict interface` has been deprecated. Use `a class extending rllib.agents.callbacks.DefaultCallbacks` instead. This will raise an error in the future!
2021-09-04 04:58:36,921 WARNING deprecation.py:39 -- DeprecationWarning: `simple_optimizer` has been deprecated. This will raise an error in the future!
2021-09-04 04:58:36,924 WARNING deprecation.py:39 -- DeprecationWarning: `callbacks dict interface` has been deprecated. Use `a class extending rllib.agents.callbacks.DefaultCallbacks` instead. This will raise an error in the future!
2021-09-04 04:58:37,715 WARNING deprecation.py:39 -- DeprecationWarning: `callbacks dict interface` has been deprecated. Use `a class extending rllib.agents.callbacks.DefaultCallbacks` instead. This will raise an error in the future!
2021-09-04 04:58:38,329 WARNING util.py:55 -- Install gputil for GPU system monitoring.
WARNING:tensorflow:From /home/fr/fr_fr/fr_jh565/miniconda3/envs/hiwinr/lib/python3.6/site-packages/ray/rllib/utils/exploration/epsilon_greedy.py:212: Variable.load (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer Variable.assign which has equivalent behavior in 2.X.
```
</details>

Also, Ray is far from using all the resources available on the node, so this does not seem to be the problem either.

Where can one find more information on why the worker died?

### Reproduction
- OS: CentOS 7
- Python: 3.6.13
- Ray: 1.6
- Tensorflow: 2.5.0

```
from ray import tune

analysis = tune.run(
   'DQN',
    stop={
        "timesteps_total": 10000000,
    },
    config=tune_config,
    checkpoint_at_end=True)
```
<details>
 <summary>The TUNE config</summary>

```
{   'callbacks': {   'on_episode_end': <function setup_ray_callbacks.<locals>.on_episode_end at 0x7f65a53186a8>,
                     'on_train_result': <function setup_ray_callbacks.<locals>.on_train_result at 0x7f65a4dd7840>},
    'env': 'GymEnvWrapper-Atari',
    'env_config': {   'AtariEnv': {'game': 'breakout'},
                      'action_space_type': 'discrete',
                      'delay': 0,
                      'dummy_seed': 0,
                      'reward_noise': 0,
                      'state_space_type': 'discrete'},
    'evaluation_config': {   'env_config': {   'action_loss_weight': 0.0,
                                               'dummy_eval': True,
                                               'reward_noise': <function <lambda> at 0x7f65a52f8d90>,
                                               'transition_noise': 0}},
    'evaluation_interval': 1,
    'model': {},
    'timesteps_total': 10000000}
```
</details>

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
Do you happened to have the full driver logs?

**Comment by vonHartz** [comment]
> Do you happened to have the full driver logs?

Sure!

```
2021-09-04 04:58:22,004	WARNING sample.py:403 -- DeprecationWarning: wrapping <function setup_ray_callbacks.<locals>.on_episode_end at 0x7f65a53186a8> with tune.function() is no longer needed
2021-09-04 04:58:22,004	WARNING sample.py:403 -- DeprecationWarning: wrapping <function setup_ray_callbacks.<locals>.on_train_result at 0x7f65a4dd7840> with tune.function() is no longer needed
2021-09-04 04:58:22,580	WARNING trial_runner.py:230 -- The maximum number of pending trials has been automatically set to the number of available cluster CPUs, which is high (140 CPUs/pending trials). If you're running an experiment with a large number of trials, this could lead to scheduling overhead. In this case, consider setting the `TUNE_MAX_PENDING_TRIALS_PG` environment variable to the desired maximum number of concurrent trials.
[2m[36m(pid=83296)[0m 2021-09-04 04:58:35,009	INFO trainer.py:714 -- Tip: set framework=tfe or the --eager flag to enable TensorFlow eager execution
[2m[36m(pid=83296)[0m 2021-09-04 04:58:35,011	INFO dqn.py:188 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
[2m[36m(pid=83296)[0m 2021-09-04 04:58:35,013	WARNING deprecation.py:39 -- DeprecationWarning: `callbacks dict interface` has been deprecated. Use `a class extending rllib.agents.callbacks.DefaultCallbacks` instead. This will raise an error in the future!
[2m[36m(pid=83296)[0m 2021-09-04 04:58:35,015	INFO trainer.py:728 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
[2m[36m(pid=83296)[0m 2021-09-04 04:58:35,021	WARNING deprecation.py:39 -- DeprecationWarning: `callbacks dict interface` has been deprecated. Use `a class extending rllib.agents.callbacks.DefaultCallbacks` instead. This will raise an error in the future!
[2m[36m(pid=83296)[0m 2021-09-04 04:58:35,120	WARNING deprecation.py:39 -- DeprecationWarning: `ray.rllib.env.atari_wrappers....` has been deprecated. Use `ray.rllib.env.wrappers.atari_wrappers....` instead. This will raise an error in the future!
[2m[36m(pid=83296)[0m 2021-09-04 04:58:35.475934: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
[2m[36m(pid=83296)[0m 2021-09-04 04:58:36,055	WARNING deprecation.py:39 -- DeprecationWarning: `callbacks dict interface` has been deprecated. Use `a class extending rllib.agents.callbacks.DefaultCallbacks` instead. This will raise an error in the future!
[2m[36m(pid=83296)[0m 2021-09-04 04:58:36,921	WARNING deprecation.py:39 -- DeprecationWarning: `simple_optimizer` has been deprecated. This will raise an error in the future!
[2m[36m(pid=83296)[0m 2021-09-04 04:58:36,924	WARNING deprecation.py:39 -- DeprecationWarning: `callbacks dict interface` has been deprecated. Use `a class extending rllib.agents.callbacks.DefaultCallbacks` instead. This will raise an error in the future!
[2m[36m(pid=83296)[0m 2021-09-04 04:58:37,715	WARNING deprecation.py:39 -- DeprecationWarning: `callbacks dict interface` has been deprecated. Use `a class extending rllib.agents.callbacks.DefaultCallbacks` instead. This will raise an error in the future!
[2m[36m(pid=83296)[0m 2021-09-04 04:58:38,329	WARNING util.py:55 -- Install gputil for GPU system monitoring.
[2m[36m(pid=83296)[0m WARNING:tensorflow:From /home/fr/fr_fr/fr_jh565/miniconda3/envs/hiwinr/lib/python3.6/site-packages/ray/rllib/utils/exploration/epsilon_greedy.py:212: Variable.load (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
[2m[36m(pid=83296)[0m Instructions for updating:
[2m[36m(pid=83296)[0m Prefer Variable.assign which has equivalent behavior in 2.X.
2021-09-05 13:40:52,522	WARNING worker.py:1215 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffa2df2912c7097e9dde04bb4d01000000 Worker ID: 425d3bf8f1180b2cf6f646b40bf70cde4c13fe99fbce1097f427a5bc Node ID: 447cc8d4f83eb2e2f86dc7846ffe02f50767e4cfa06b6cc607bbadf8 Worker IP address: 10.16.46.69 Worker port: 40679 Worker PID: 83296
2021-09-05 13:40:52,708	ERROR trial_runner.py:773 -- Trial DQN_GymEnvWrapper-Atari_f6fb9_00000: Error processing event.
Traceback (most recent call last):
  File "XXX/miniconda3/envs/hiwinr/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 739, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "XXX/miniconda3/envs/hiwinr/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 746, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "XXX/miniconda3/envs/hiwinr/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "XXX/miniconda3/envs/hiwinr/lib/python3.6/site-packages/ray/worker.py", line 1623, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
2021-09-05 13:40:53,183	WARNING util.py:164 -- The `process_trial` operation took 0.641 s, which may be a performance bottleneck.
Traceback (most recent call last):
[...]
  File "/home/fr/fr_fr/fr_jh565/miniconda3/envs/hiwinr/lib/python3.6/site-packages/ray/tune/tune.py", line 555, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [DQN_GymEnvWrapper-Atari_f6fb9_00000])

Encountered error in training. Model cannot be stored.
```
