### ISSUE TITLE
pyarrow.lib.ArrowIOError: Encountered unexpected EOF

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#1838]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: Source
- **Ray version**: 4.0
- **Python version**: 3.6 
- **Exact command to reproduce**: N/A

### Describe the problem
Following error obtained when running a custom env on a head node w/ two workers and the following config: 
config = ppo.DEFAULT_CONFIG.copy()
    horizon = HORIZON
    n_rollouts = 100
    parallel_rollouts = 40
    # ray.init(redirect_output=True)
    ray.init(redis_address="172.31.92.24:6379", redirect_output=False)

    config["num_workers"] = parallel_rollouts
    config["timesteps_per_batch"] = horizon * n_rollouts
    config["gamma"] = 0.999  # discount rate
    config["model"].update({"fcnet_hiddens": [16, 16]})
    config["use_gae"] = True
    config["lambda"] = 0.97
    config["sgd_batchsize"] = min(16 * 1024, config["timesteps_per_batch"])
    config["kl_target"] = 0.02
    config["num_sgd_iter"] = 10
    config["horizon"] = horizon

    flow_env_name = "WaveAttenuationPOEnv"
    exp_tag = "stabilizing_the_ring_example"  # experiment prefix

    flow_params['flowenv'] = flow_env_name
    flow_params['exp_tag'] = exp_tag
    flow_params['module'] = os.path.basename(__file__)[:-3]  # filename without '.py'

    create_env, env_name = make_create_env(flow_env_name, flow_params, version=0,
                                           exp_tag=exp_tag)

    # Register as rllib env
    register_rllib_env(env_name, create_env)

    logger_creator = rllib_logger_creator(results_dir,
                                          flow_env_name,
                                          UnifiedLogger)

    alg = ppo.PPOAgent(env=env_name, registry=get_registry(),
                       config=config, logger_creator=logger_creator)

    # Logging out flow_params to ray's experiment result folder
    json_out_file = alg.logdir + '/flow_params.json'
    with open(json_out_file, 'w') as outfile:
        json.dump(flow_params, outfile, cls=NameEncoder, sort_keys=True, indent=4)

    trials = run_experiments({
        "ring_stabilize": {
            "run": "PPO",
            "env": "WaveAttenuationPOEnv-v0",
            "config": {
                **config
            },
            "checkpoint_freq": 20,
            "max_failures": 999,
            "stop": {"training_iteration": 200},
            "repeat": 3,
            "trial_resources": {"cpu": 1, "gpu": 0,
                                "extra_cpu": parallel_rollouts - 1}
        },
    })

### Source code / logs

Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/worker.py", line 821, in _process_task
    *arguments)
  File "/home/ubuntu/ray/python/ray/actor.py", line 212, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/ubuntu/ray/python/ray/tune/trainable.py", line 109, in train
    result = self._train()
  File "/home/ubuntu/ray/python/ray/rllib/ppo/ppo.py", line 134, in _train
    samples = collect_samples(agents, config, self.local_evaluator)
  File "/home/ubuntu/ray/python/ray/rllib/ppo/rollout.py", line 25, in collect_samples
    [fut_sample], _ = ray.wait(list(agent_dict))
  File "/home/ubuntu/ray/python/ray/worker.py", line 2406, in wait
    num_returns)
  File "plasma.pyx", line 595, in pyarrow.plasma.PlasmaClient.wait
  File "error.pxi", line 79, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Encountered unexpected EOF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/workers/default_worker.py", line 48, in <module>
    ray.worker.global_worker.main_loop()
  File "/home/ubuntu/ray/python/ray/worker.py", line 968, in main_loop
    self._wait_for_and_process_task(task)
  File "/home/ubuntu/ray/python/ray/worker.py", line 924, in _wait_for_and_process_task
    self._process_task(task)
  File "/home/ubuntu/ray/python/ray/worker.py", line 829, in _process_task
    e, traceback_str)
  File "/home/ubuntu/ray/python/ray/worker.py", line 854, in _handle_process_task_failure
    self._store_outputs_in_objstore(return_object_ids, failure_objects)
  File "/home/ubuntu/ray/python/ray/worker.py", line 768, in _store_outputs_in_objstore
    self.put_object(object_ids[i], outputs[i])
  File "/home/ubuntu/ray/python/ray/worker.py", line 372, in put_object
    self.store_and_register(object_id, value)
  File "/home/ubuntu/ray/python/ray/worker.py", line 302, in store_and_register
    serialization_context=self.serialization_context)
  File "plasma.pyx", line 401, in pyarrow.plasma.PlasmaClient.put
  File "plasma.pyx", line 302, in pyarrow.plasma.PlasmaClient.create
  File "error.pxi", line 79, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Broken pipe

  This error is unexpected and should not have happened. Somehow a worker
  crashed in an unanticipated way causing the main_loop to throw an exception,
  which is being caught in "python/ray/workers/default_worker.py".

**Comment by eugenevinitsky** [comment]
Figured it was worth keeping track of this error. I have a machine that anyone can log into if that suffices for reproducibility.

**Comment by G-ram** [comment]
I have also run into this error. Is there a workaround?

**Comment by G-ram** [comment]
Yes,
Ubuntu 16.04
Intel 7800K
3 1070Ti's
Ray: 0.4.0
Tensorflow: 1.81
Python: 2.7.2

I use Ray Tune to choose hyperparameters for a network. I search between 1000-5000 different configurations for the network using the Median Stopping Rule Scheduler.

**Comment by richardliaw** [comment]
Just one machine right?

**Comment by G-ram** [comment]
Yes with 16gb of RAM.

**Comment by richardliaw** [comment]
Do you have a script we can use to reproduce/examine? It would be very
helpful.

**Comment by ericl** [comment]
Closing stale issue -- feel free to re-open if you're still seeing this.

**Comment by devin-petersohn** [comment]
A user has reported this in Modin: https://github.com/modin-project/modin/issues/733
