### ISSUE TITLE
[rllib] unable to restore old checkpoint with Ray 1.6

### ISSUE THREAD

**Issue by antoine-galataud** [ray-project/ray#18392]
### What is the problem?

Ray version: 1.6.0
Tensorflow version: 2.4
Python version: 3.8.10

I'm unable to reload a checkpoint saved with Ray 0.8.6 -> 1.3 with Ray 1.6

### Reproduction (REQUIRED)

Steps to reproduce:

- train an agent with Ray version < 1.6 and checkpoint
- reload checkpoint with Ray 1.6

You get following exception:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/antoine/data/git/sab_policy_server/sab_policy_server/serve/policy_serv.py", line 392, in start_server
    agent.restore(args.checkpoint_file)
  File "/home/antoine/.cache/pypoetry/virtualenvs/sab-policy-server-5zZOFICQ-py3.8/lib/python3.8/site-packages/ray/tune/trainable.py", line 377, in restore
    self.load_checkpoint(checkpoint_path)
  File "/home/antoine/.cache/pypoetry/virtualenvs/sab-policy-server-5zZOFICQ-py3.8/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 793, in load_checkpoint
    self.__setstate__(extra_data)
  File "/home/antoine/.cache/pypoetry/virtualenvs/sab-policy-server-5zZOFICQ-py3.8/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 258, in __setstate__
    Trainer.__setstate__(self, state)
  File "/home/antoine/.cache/pypoetry/virtualenvs/sab-policy-server-5zZOFICQ-py3.8/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1614, in __setstate__
    self.workers.local_worker().restore(state["worker"])
  File "/home/antoine/.cache/pypoetry/virtualenvs/sab-policy-server-5zZOFICQ-py3.8/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1280, in restore
    self.policy_map[pid].set_state(state)
  File "/home/antoine/.cache/pypoetry/virtualenvs/sab-policy-server-5zZOFICQ-py3.8/lib/python3.8/site-packages/ray/rllib/policy/tf_policy.py", line 572, in set_state
    super().set_state(state)
  File "/home/antoine/.cache/pypoetry/virtualenvs/sab-policy-server-5zZOFICQ-py3.8/lib/python3.8/site-packages/ray/rllib/policy/policy.py", line 605, in set_state
    self.set_weights(state["weights"])
KeyError: 'weights'
```
`state` is now expected to be a dictionary with `weights` and `_optimizer_state` keys. The latter wasn't saved with checkpoint prior to recent change, and `state` was simply a an `OrderedDict` of weights.
So a possible solution would be to "update" old `state` by setting `state['weights'] = state`, and initialize `_optimizer_state` with defaults. Not sure if it makes sense in all cases though.

**Comment by avnishn** [comment]
Hi @antoine-galataud!

Is your old checkpoint also created with a TF 2.4 backend? 

If not, it may be possible that your checkpoint is unable to be opened with Ray 1.6, and you will need to use your checkpoint with ray 0.8.6.

Thanks,
@avnishn

**Comment by avnishn** [comment]
I suspect that there is a difference in the tensorflow version that you are using now (2.4) and the version that you trained your ray 0.8.6 policy with -- I was able to start restoring a checkpoint trained with tf 2.5 on ray 0.8.6 on ray 1.6, however there were differences in the parameters in the optimizers that are used between ray 1.6 and ray 0.8.6. This was the same as well with pytorch pretrained policies

**Comment by antoine-galataud** [comment]
Hi @avnishn thx for your answer. I’m able to restore the same checkpoint created with ray 0.8.6 on ray 1.4.0 and different tensorflow versions.

**Comment by avnishn** [comment]
Hi @antoine-galataud,

I'm apologize for the late response.

After talking with @sven1977 we decided that we will be supporting backwards compatibility of policies, just from Ray 1.7 onwards. It would be too difficult for us to support this type of backwards compatibility back till ray 0.8 and earlier. 

 In the meantime please keep using Ray 1.4. Thank you again from bringing this issue to our attention: we have elevated this issue to a P0 for our next quarter, and hope to solve it soon!

Thanks and let me know if you have any questions :) I'll keep this issue open for now so that we can keep track of it.
@avnishn

**Comment by ericl** [comment]
@avnishn I'm downgrading this to a P1 since features are not P0s. P0 priority is reserved for high-priority regressions.

**Comment by avnishn** [comment]
Thanks for correcting me @ericl

**Comment by ReedZyd** [comment]
Hello, I wonder if it is possible to load the checkpoint trained with 0.8.5 into a model created with 2.6.0 now?
