### ISSUE TITLE
ValueError: Message ray.rpc.DataRequest exceeds maximum protobuf size of 2GB

### ISSUE THREAD

**Issue by juyunsang** [ray-project/ray#18396]
Hello
Training with large size data(2GB) results in the following error.
There is no problem with small size of learning data

```
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2021-09-06 17:15:49,920 [ERROR] Exception serializing message!
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/grpc/_common.py", line 86, in _transform
    return transformer(message)
ValueError: Message ray.rpc.DataRequest exceeds maximum protobuf size of 2GB: 2339503268
2021-09-06 17:15:49,925 [ERROR] Got Error from data channel -- shutting down:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/ray/util/client/dataclient.py", line 69, in _data_main
    for response in resp_stream:
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Exception serializing request!"
        debug_error_string = "None"
>
```

**Comment by juyunsang** [comment]
@amogkam 
Thank you for reply
inside the trainset object, 2GB of learning data is placed in memory and used.
If i reduce the number of trainset data, train well in ray cluster.
The size of the train set is over 2GB. Is this a problem?
Is it impossible for ray clusters to put over 2GB of training data in memory and use?

- dataset.py
```python
from torch.utils.data import Dataset
import json
class Trainset(Dataset):
      def __init__(self):
          self.total_data = []
          with open('trainset.json', 'r') as f:
                  for line in f:
                        self.total_data.append(self._preprocess_trainset(line))
      def __getitem__(self, idx):
          return self.total_data[idx]

      def __len__(self):
          return len(self.total_data)

     
   

```

- train.py
```python
    ray_cluster_connection = f'ray host'
    ray.client(ray_cluster_connection).namespace('test').connect()
    print(ray.available_resources())

    train_loader = DataLoader(trainset,
                        batch_size=cfg.batch_size,
                        num_workers=cfg.num_workers)
    valid_loader = DataLoader(validset,
                        batch_size=cfg.batch_size,
                        num_workers=cfg.num_workers)

    plugin = RayShardedPlugin(num_workers=2, num_cpus_per_worker=1, use_gpu=True)

    logging.info("training start")
    trainer = pl.Trainer(
        logger=[tb_logger],
        gpus=1,
        max_steps=cfg.max_steps,
        val_check_interval=cfg.val_check_interval,
        log_every_n_steps=cfg.log_interval,
        precision=16 if cfg.train.use_fp16 else 32,
        flush_logs_every_n_steps=cfg.flush_logs_every_n_steps,
        progress_bar_refresh_rate=cfg.progress_bar_refresh_rate,
        plugins=[plugin]
    )
    trainer.fit(model, train_loader, valid_loader)
```

**Comment by amogkam** [comment]
Got it, this is really helpful! Also want to check, is this running on Kubernetes?

**Comment by juyunsang** [comment]
@amogkam 
Yes!
out ray cluster running on kubernetes cluster

**Comment by juyunsang** [comment]
@amogkam 
Hello
is there any suggestion to solve this problem?

**Comment by amogkam** [comment]
Hey @juyunsang, this is the same issue as https://github.com/ray-project/ray/issues/18378, correct? Let's consolidate this onto the other issue. And it looks like that is being addressed. I am going to close this one for now.
