### ISSUE TITLE
[Datasets] `Unrecognized filesystem type in URI` when using Ray data `write_parquet()` with Google cloud storage (gcs) paths `gs://`

### ISSUE THREAD

**Issue by isaac-vidas** [ray-project/ray#18393]
### What is the problem?

When using Ray dataset `write_parquet()` with Google cloud storage (gcs) paths `gs://`, the result is the following error: `Unrecognized filesystem type in URI`

*Ray version and other system information (Python version, TensorFlow version, OS):*

```
ray==1.6.0
pyarrow==5.0.0
gcsfs==2021.8.1
fsspec==2021.8.1
google-api-core==1.31.2
google-auth==1.35.0
google-auth-oauthlib==0.4.6
google-cloud-core==2.0.0
google-cloud-storage==1.42.0
```

### Reproduction (REQUIRED)

The issue can be reproduced with the following code:

```
import ray
from gcsfs import GCSFileSystem

ray.init()
fs = GCSFileSystem()
ray.data.range(1000).write_parquet("gs://path/results", filesystem=fs)
```

Result will be the following error:

```
---------------------------------------------------------------------------
RayTaskError(ArrowInvalid)                Traceback (most recent call last)
/var/folders/k5/x1sv5gcj2z9f9n6khswpp59c0000gn/T/ipykernel_22072/3309229740.py in <module>
----> 1 ray.data.range(1000).write_parquet("gs://ml-adhoc/user/isaacvidas/product_classification/results", filesystem=fs)

~/.pyenv/versions/3.7.7/envs/pc_batch_inference/lib/python3.7/site-packages/ray/data/dataset.py in write_parquet(self, path, filesystem)
    763 
    764         # Block until writing is done.
--> 765         ray.get(refs)
    766 
    767     def write_json(

~/.pyenv/versions/3.7.7/envs/pc_batch_inference/lib/python3.7/site-packages/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
     79     def wrapper(*args, **kwargs):
     80         if client_mode_should_convert():
---> 81             return getattr(ray, func.__name__)(*args, **kwargs)
     82         return func(*args, **kwargs)
     83 

~/.pyenv/versions/3.7.7/envs/pc_batch_inference/lib/python3.7/site-packages/ray/util/client/api.py in get(self, vals, timeout)
     40             timeout: Optional timeout in milliseconds
     41         """
---> 42         return self.worker.get(vals, timeout=timeout)
     43 
     44     def put(self, *args, **kwargs):

~/.pyenv/versions/3.7.7/envs/pc_batch_inference/lib/python3.7/site-packages/ray/util/client/worker.py in get(self, vals, timeout)
    223                     else:
    224                         op_timeout = MAX_BLOCKING_OPERATION_TIME_S
--> 225                     res = self._get(obj_ref, op_timeout)
    226                     break
    227                 except GetTimeoutError:

~/.pyenv/versions/3.7.7/envs/pc_batch_inference/lib/python3.7/site-packages/ray/util/client/worker.py in _get(self, ref, timeout)
    246                 logger.exception("Failed to deserialize {}".format(data.error))
    247                 raise
--> 248             raise err
    249         return loads_from_server(data.data)
    250 

RayTaskError(ArrowInvalid): ray::parquet_write() (pid=3178, ip=10.6.1.160)
  File "/Users/ividas/.pyenv/versions/3.7.7/envs/pc_batch_inference/lib/python3.7/site-packages/ray/data/dataset.py", line 755, in parquet_write
  File "/tmp/ray/session_2021-09-04_21-29-31_118901_117/runtime_resources/conda/ray-99452683d28855b85eba3175951906d17552be9f/lib/python3.7/site-packages/pyarrow/parquet.py", line 638, in __init__
    where, filesystem, allow_legacy_filesystem=True
  File "/tmp/ray/session_2021-09-04_21-29-31_118901_117/runtime_resources/conda/ray-99452683d28855b85eba3175951906d17552be9f/lib/python3.7/site-packages/pyarrow/fs.py", line 174, in _resolve_filesystem_and_path
    filesystem, path = FileSystem.from_uri(path)
  File "pyarrow/_fs.pyx", line 347, in pyarrow._fs.FileSystem.from_uri
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Unrecognized filesystem type in URI: gs://path/results/a329cb261fd448e885fe2ddd5f93ec5e_000000.parquet
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by clarkzinzow** [comment]
Ah we still need to add fsspec support to the write path in Datasets! That should be very easy to add.

**Comment by clarkzinzow** [comment]
@isaac-vidas I'm fairly certain that support for fsspec was added in [this PR](https://github.com/ray-project/ray/pull/18135), which ported the write side of the Datasets IO layer to our datasource abstraction. I'm writing up test coverage to be sure, but in the meantime, could you try running this workload on a nightly Ray wheel?

**Comment by clarkzinzow** [comment]
@isaac-vidas I've confirmed that writing to fsspec filesystems (such as the `gcsfs` filesystem) works on current master, and I've submitted a [PR](https://github.com/ray-project/ray/pull/18394) adding test coverage. Please let me know if it works for you on the latest nightly wheel and I'll close this issue.
