### ISSUE TITLE
[datasets] unable to read from S3 path with space in name

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#18414]
### What is the problem?

Calling `read_csv` on an S3 path that has a space in its name causes a `pyarrow.lib.ArrowInvalid: Cannot parse URI` exception.

*Ray version and other system information (Python version, TensorFlow version, OS):*

**Ray:** 2.0.0.dev0
**Python:** 3.8.10

### Reproduction (REQUIRED)

**Example:** [This file](https://s3.console.aws.amazon.com/s3/object/nyc-tlc?prefix=trip+data/green_tripdata_2020-12.csv) is in a `trip data` directory.

```python
import ray
ray.data.read_csv("s3://nyc-tlc/trip data/green_tripdata_2020-12.csv")
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matt/workspace/ray/python/ray/data/read_api.py", line 292, in read_csv
    return read_datasource(
  File "/Users/matt/workspace/ray/python/ray/data/read_api.py", line 151, in read_datasource
    read_tasks = datasource.prepare_read(parallelism, **read_args)
  File "/Users/matt/workspace/ray/python/ray/data/datasource/file_based_datasource.py", line 46, in prepare_read
    paths, filesystem = _resolve_paths_and_filesystem(paths, filesystem)
  File "/Users/matt/workspace/ray/python/ray/data/datasource/file_based_datasource.py", line 209, in _resolve_paths_and_filesystem
    resolved_filesystem, resolved_path = _resolve_filesystem_and_path(
  File "/Users/matt/anaconda3/envs/ray/lib/python3.8/site-packages/pyarrow/fs.py", line 174, in _resolve_filesystem_and_path
    filesystem, path = FileSystem.from_uri(path)
  File "pyarrow/_fs.pyx", line 347, in pyarrow._fs.FileSystem.from_uri
  File "pyarrow/error.pxi", line 141, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 97, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Cannot parse URI: 's3://nyc-tlc/trip data/green_tripdata_2020-12.csv'
```

1. Encoding the space as + causes `FileNotFoundError: nyc-tlc/trip+data/green_tripdata_2020-12.csv`.
2. The same URI can successfully be loaded with pandas:
```python
import pandas
pandas.read_csv("s3://nyc-tlc/trip data/green_tripdata_2020-12.csv")
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
Is this actually an error (does S3 just require urlencoded URIs?)

**Comment by matthewdeng** [comment]
Encoding the entire URI or just the path on the user side run into the following issues:

```python
import ray
ray.data.read_csv("s3%3A//nyc-tlc/trip%20data/green_tripdata_2020-12.csv")
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matt/workspace/ray/python/ray/data/read_api.py", line 326, in read_csv
    return read_datasource(
  File "/Users/matt/workspace/ray/python/ray/data/read_api.py", line 151, in read_datasource
    read_tasks = datasource.prepare_read(parallelism, **read_args)
  File "/Users/matt/workspace/ray/python/ray/data/datasource/file_based_datasource.py", line 48, in prepare_read
    paths, file_infos = _expand_paths(paths, filesystem)
  File "/Users/matt/workspace/ray/python/ray/data/datasource/file_based_datasource.py", line 255, in _expand_paths
    raise FileNotFoundError(path)
FileNotFoundError: s3%3A//nyc-tlc/trip%20data/green_tripdata_2020-12.csv
```
```python
import ray
ray.data.read_csv("s3://nyc-tlc/trip%20data/green_tripdata_2020-12.csv")
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matt/workspace/ray/python/ray/data/read_api.py", line 326, in read_csv
    return read_datasource(
  File "/Users/matt/workspace/ray/python/ray/data/read_api.py", line 151, in read_datasource
    read_tasks = datasource.prepare_read(parallelism, **read_args)
  File "/Users/matt/workspace/ray/python/ray/data/datasource/file_based_datasource.py", line 48, in prepare_read
    paths, file_infos = _expand_paths(paths, filesystem)
  File "/Users/matt/workspace/ray/python/ray/data/datasource/file_based_datasource.py", line 246, in _expand_paths
    file_info = filesystem.get_file_info(path)
  File "pyarrow/_fs.pyx", line 438, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 141, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
OSError: When getting information for key 'trip%20data/green_tripdata_2020-12.csv' in bucket 'nyc-tlc': AWS Error [code 100]: No response body.
```

**Comment by clarkzinzow** [comment]
@ericl so we could either handle URL-encoded paths in our [`_unwrap_protocol` helper](https://github.com/ray-project/ray/blob/c91e0eb0658283234d2b280ec87b0dd192a49669/python/ray/data/datasource/file_based_datasource.py#L295-L300), or we could natively support URL-encoding paths ourselves. I'd vote for the latter, I think.

**Comment by matthewdeng** [comment]
Hey @clarkzinzow I think I'm still running into the same issue even after pulling in #18440. 

**Reproduction Steps:**
```bash
conda create -n ray-wheel python=3.8 -y && \
conda activate ray-wheel && \
pip install --no-cache-dir https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp38-cp38-macosx_10_15_x86_64.whl && \
pip install pyarrow fsspec && \
python -c "import ray; print(ray.__commit__); ray.data.read_csv('s3://nyc-tlc/trip data/green_tripdata_2020-12.csv')" 
```

**Output:**
```bash
6479a5fcfc3256cca22c8ecddd06e6e4a48038d7
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/matt/anaconda3/envs/ray-wheel/lib/python3.8/site-packages/ray/data/read_api.py", line 332, in read_csv
    return read_datasource(
  File "/Users/matt/anaconda3/envs/ray-wheel/lib/python3.8/site-packages/ray/data/read_api.py", line 151, in read_datasource
    read_tasks = datasource.prepare_read(parallelism, **read_args)
  File "/Users/matt/anaconda3/envs/ray-wheel/lib/python3.8/site-packages/ray/data/datasource/file_based_datasource.py", line 62, in prepare_read
    paths, filesystem = _resolve_paths_and_filesystem(paths, filesystem)
  File "/Users/matt/anaconda3/envs/ray-wheel/lib/python3.8/site-packages/ray/data/datasource/file_based_datasource.py", line 234, in _resolve_paths_and_filesystem
    resolved_filesystem, resolved_path = _resolve_filesystem_and_path(
  File "/Users/matt/anaconda3/envs/ray-wheel/lib/python3.8/site-packages/pyarrow/fs.py", line 174, in _resolve_filesystem_and_path
    filesystem, path = FileSystem.from_uri(path)
  File "pyarrow/_fs.pyx", line 347, in pyarrow._fs.FileSystem.from_uri
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Cannot parse URI: 's3://nyc-tlc/trip data/green_tripdata_2020-12.csv'
```

---------

On a bit of a tangent - is it expected that we need to manually install `pyarrow`/`fsspec` when using Ray Datasets?

**Comment by clarkzinzow** [comment]
@matthewdeng Ah our tests manually specify a filesystem for our S3 test coverage, since we need to point to a mock S3 server, so the case of an unspecified filesystem isn't covered in our S3 URL encoding tests. I'll submit a PR that fixes this case tomorrow!
