### ISSUE TITLE
Dashboard error

### ISSUE THREAD

**Issue by evo11x** [ray-project/ray#18413]
I am trying some examples with rllib, python 3.9, pytorch, Windows 10, and all of them starts without any error
2021-09-08 02:48:17,754 INFO services.py:1245 -- View the Ray dashboard at http://127.0.0.1:8265

And when I try to view the dashboard in browser I get this error

![image](https://user-images.githubusercontent.com/32666929/132424537-bd3be515-90f4-456a-9cd0-d842340faae2.png)

**Comment by scv119** [comment]
@evo11x which ray version are you running? Unfortunately, we have experimental support for Windows at the moment; the good news is we are actively improving it.

**Comment by evo11x** [comment]
I have ray version ray, version 1.6.0, using venv to avoid package conflicts

**Comment by zacps** [comment]
Same issue here, at least in my case this is caused by:

```python-traceback
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Zac\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\REDACTED\\lib\\site-packages\\ray\\new_dashboard\\client\\build\\index.html'
2021-09-15 17:55:01,553	ERROR web_protocol.py:393 -- Unhandled exception
Traceback (most recent call last):
  File "C:\Users\Zac\AppData\Local\pypoetry\Cache\virtualenvs\REDACTED\lib\site-packages\aiohttp\web_protocol.py", line 485, in start
    resp, reset = await task
  File "C:\Users\Zac\AppData\Local\pypoetry\Cache\virtualenvs\REDACTED\lib\site-packages\aiohttp\web_protocol.py", line 440, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "C:\Users\Zac\AppData\Local\pypoetry\Cache\virtualenvs\REDACTED\lib\site-packages\aiohttp\web_protocol.py", line 591, in finish_response
    await prepare_meth(request)
  File "C:\Users\Zac\AppData\Local\pypoetry\Cache\virtualenvs\REDACTED\lib\site-packages\aiohttp\web_fileresponse.py", line 115, in prepare
    st = await loop.run_in_executor(None, filepath.stat)
  File "c:\users\zac\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\zac\appdata\local\programs\python\python38\lib\pathlib.py", line 1194, in stat
    return self._accessor.stat(self)
```

`new_dashboard` does not have a client folder.

**Comment by scheung38** [comment]
also not found 2021-09-18 03:14:30,674 INFO services.py:1263 -- View the Ray dashboard at http://127.0.0.1:8265

![Screenshot 2021-09-18 at 03 18 50](https://user-images.githubusercontent.com/1273014/133869098-4ca7ec6d-a789-4170-838e-5dee466da7dc.png)

Mac Big Sur 11.5.2
Chrome / Safari

**Comment by scv119** [comment]
@evo11x @zacps unfortunately there is a known issue with Windows dashboard. We are working on improving the Window experience in the next quarter. cc @wuisawesome for Windows issue prioritization.

**Comment by evo11x** [comment]
Is there a way to run another instance of ray in a virtual linux machine to have the dashboard?

**Comment by wuisawesome** [comment]
@evo11x yeah you can use a linux vm or use WSL.

**Comment by wuisawesome** [comment]
Btw there's an issue here to track fixing the dashboard for windows: #14026

I think the fact that our warning message is being swallowed is a separate issue of its own though.

**Comment by evo11x** [comment]
> @evo11x yeah you can use a linux vm or use WSL.

The problem with vm is that the GPU is not available in vm and in WSL the GPU requests are routed with performance loss. I was thinking if it is possible to run a RAY learning in Windows and in VM or WSL to get the logging from the Windows, if it is possible?

**Comment by mattip** [comment]
Once I installed all the dependencies, I could see the dashboard for about a minute. Then it dies, in the `dashboard.log` file I see 
>Dashboard exiting because it received too many GCS RPC errors count: 11, threshold is 10.

This happens even if I do not browse to the page, so it is something internal. I do not see any other obvious errors in the logs.

**Comment by mattip** [comment]
I also turned off the windows firewall
