### ISSUE TITLE
[core] first call to ray.init() fails

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#18454]
### What is the problem?

When running `ray.init()` for the first time on a clean environment, an exception is raised by redis:
```
redis.exceptions.ResponseError: Invalid argument '65504' for CONFIG SET 'maxclients' - The operating system is not able to handle the specified number of clients, try with 10000
```
Subsequent calls will succeed so it's not a blocker.

Related Issue: https://github.com/ray-project/ray/issues/12059

*Ray version and other system information (Python version, TensorFlow version, OS):*

**OS:** Big Sur 11.2.3
**Python:** 3.7.11
**Ray:** nightly wheel

### Reproduction (REQUIRED)
```bash
conda create -n ray_wheels python=3.7 -y && \
conda activate ray_wheels && \
pip install https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-macosx_10_15_intel.whl && \
python -c "import ray; print(ray.__commit__); ray.init()"
```
```
50cdf551ced8506a1d7b5469aea1d8f205fd7920
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/matt/anaconda3/envs/ray_wheels/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/Users/matt/anaconda3/envs/ray_wheels/lib/python3.7/site-packages/ray/worker.py", line 898, in init
    ray_params=ray_params)
  File "/Users/matt/anaconda3/envs/ray_wheels/lib/python3.7/site-packages/ray/node.py", line 249, in __init__
    self.start_head_processes()
  File "/Users/matt/anaconda3/envs/ray_wheels/lib/python3.7/site-packages/ray/node.py", line 896, in start_head_processes
    self.start_redis()
  File "/Users/matt/anaconda3/envs/ray_wheels/lib/python3.7/site-packages/ray/node.py", line 716, in start_redis
    port_denylist=self._ray_params.reserved_ports)
  File "/Users/matt/anaconda3/envs/ray_wheels/lib/python3.7/site-packages/ray/_private/services.py", line 869, in start_redis
    port_denylist=port_denylist)
  File "/Users/matt/anaconda3/envs/ray_wheels/lib/python3.7/site-packages/ray/_private/services.py", line 1053, in _start_redis_instance
    ulimit_n - redis_client_buffer)
  File "/Users/matt/anaconda3/envs/ray_wheels/lib/python3.7/site-packages/redis/client.py", line 1243, in config_set
    return self.execute_command('CONFIG SET', name, value)
  File "/Users/matt/anaconda3/envs/ray_wheels/lib/python3.7/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/Users/matt/anaconda3/envs/ray_wheels/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/Users/matt/anaconda3/envs/ray_wheels/lib/python3.7/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Invalid argument '65504' for CONFIG SET 'maxclients' - The operating system is not able to handle the specified number of clients, try with 10000
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
This means the number of file descriptors are too low. You can try something like this to increase it.
```
$ ulimit -Sn 65504
```

**Comment by matthewdeng** [comment]
@simon-mo if that's the case, do you know why subsequent calls to `ray.init()` will succeed?

**Comment by gjoliver** [comment]
Another data point. I am seeing the same thing on M1, with fresh env and wheel installation, python 3.9.
I think this used to print a warning message, not sure why it's an exception now.

**Comment by rkooo567** [comment]
@wuisawesome do we automatically increase the ulimit in the first run?
