### ISSUE TITLE
[release] many_ppo failing: "There was timeout in removing the placement group "

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#18541]
### What is the problem?

Weekly long running tests:

```
2021-09-12 04:13:06,836 INFO log_timer.py:27 -- NodeUpdater: ins_UBpk1QT7cF9Xpx681xfUQFYV: Got IP  [LogTimer=63ms]
Traceback (most recent call last):
  File "workloads/many_ppo.py", line 41, in <module>
    callbacks=[ProgressCallback()])
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 711, in run_experiments
    callbacks=callbacks).trials
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 588, in run
    runner.step()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 646, in step
    self._run_and_catch(self.trial_executor.on_step_end)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 396, in _run_and_catch
    func(self.get_trials())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 988, in on_step_end
    self._pg_manager.cleanup()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/utils/placement_groups.py", line 296, in cleanup
    remove_placement_group(pg)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 122, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/placement_group.py", line 253, in remove_placement_group
    worker.core_worker.remove_placement_group(placement_group.id)
  File "python/ray/_raylet.pyx", line 1488, in ray._raylet.CoreWorker.remove_placement_group
  File "python/ray/_raylet.pyx", line 158, in ray._raylet.check_status
ray.exceptions.GetTimeoutError: There was timeout in removing the placement group of id eb068a103a8de03cd6ec0544849331b4. It is probably because GCS server is dead or there's a high load there.
(pid=44646, ip=172.31.89.10) 2021-09-12 04:14:16,933    WARNING trainer_template.py:186 -- `execution_plan` functions should accept `trainer`, `workers`, and `config` as args!
(pid=44646, ip=172.31.89.10) 2021-09-12 04:14:16,933    INFO trainable.py:111 -- Trainable.setup took 73.185 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
(pid=44646, ip=172.31.89.10) 2021-09-12 04:14:16,934    WARNING util.py:57 -- Install gputil for GPU system monitoring.
```

Failing after 1 hour (we see this sometimes in the nightly tests, too):

https://buildkite.com/ray-project/periodic-ci/builds/963#532e36d2-7d77-42a1-aa67-b6837f5a64f6
https://buildkite.com/ray-project/periodic-ci/builds/967#49b3cc43-6c31-4eed-9922-55744fe03ddb

cc @rkooo567 @ericl 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
So, this happens as it is explained in the error message; 

```
ray.exceptions.GetTimeoutError: There was timeout in removing the placement group of id eb068a103a8de03cd6ec0544849331b4. It is probably because GCS server is dead or there's a high load there.
```

I observed the gcs server load is very high (100% cpu whole time), which causes the remove placement group to take more than 5 seconds. I will start profiling why this happens

**Comment by rkooo567** [comment]
Solutions; https://github.com/ray-project/ray/issues/18651

**Comment by rkooo567** [comment]
Btw, this https://github.com/ray-project/ray/pull/18650 will make this test pass, but we should still handle the pg issue. Maybe not a release blocker though

**Comment by jjyao** [comment]
Still happening with the latest weekly release test: https://buildkite.com/ray-project/periodic-ci/builds/1112#28cb72cd-1454-481c-af15-28bc4159fe90

**Comment by rkooo567** [comment]
Seems like we should merge this as well; https://github.com/ray-project/ray/issues/18651 Let me focus on fixing tests

**Comment by rkooo567** [comment]
After cherry-picking placement group fixes, it seems to crash by the memory leak. 

```python3
ray.exceptions.RayTaskError(RayOutOfMemoryError): [36mray::PPO.get_current_ip()[39m (pid=540673, ip=172.31.31.203, repr=PPO)
ray._private.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node ip-172-31-31-203 is used (29.38 / 30.91 GB). The top 10 memory consumers are:
```

```python3
1083	8.64GiB	python workloads/many_ppo.py
155	5.71GiB	/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.8/site-packages/ray/dashboard/dash
141	4.46GiB	/home/ray/anaconda3/lib/python3.8/site-packages/ray/core/src/ray/gcs/gcs_server --redis_address=172.
136	3.29GiB	/home/ray/anaconda3/lib/python3.8/site-packages/ray/core/src/ray/thirdparty/redis/src/redis-server *
131	0.77GiB	/home/ray/anaconda3/lib/python3.8/site-packages/ray/core/src/ray/thirdparty/redis/src/redis-server *
540673	0.51GiB	ray::PPO
540789	0.48GiB	ray::RolloutWorker
540784	0.48GiB	ray::RolloutWorker
540792	0.48GiB	ray::RolloutWorker
540793	0.48GiB	ray::RolloutWorker
```

cc @richardliaw @krfricke  can you confirm if the memory usage increase is abnormal or expected (also have you seen this before)? 

The next TODO is to memory profiling high memory components (driver + GCS + Redis + dashboard) and decide if we should fix issues. Note that the dashboard memory issue is a well known issue, which happens because we never remove log messages from the backend.

**Comment by richardliaw** [comment]
So it looks like the memory on the driver was increasing rapidly. The worker memory usage looks safe.

**Comment by rkooo567** [comment]
@richardliaw can you guys verify real quick if the memory usage increase is due to the application code? I will also do it do figure out if it is the core issue next sprint, but knowing this would help us a lot for debugging

**Comment by richardliaw** [comment]
@sven1977 or @gjoliver can one of you take this action item?

**Comment by gjoliver** [comment]
@rkooo567, I can take a look. is many_ppo the only long running rllib test that exhibits this problem?
we also have apex and impala there, for example.

**Comment by rkooo567** [comment]
I am not sure. I don’t think we currently track this. I found the issue because the long running test failed with the memory error. I think we should start tracking this

**Comment by rkooo567** [comment]
@gjoliver let me know how the investigation goes!

**Comment by gjoliver** [comment]
œqqsorry about the delay Sangbin. there were a lot of fires to put out lately.
I took a look at the test, the application code is extremely simple. it basically creates a trainer and 7 workers, run one training iteration, and tears everything down. It then does this 10000 times.

The testing script doesn't have a leak, but the real application code here is the entire Tune and RLlib codebase.
That becomes pretty hard to judge.
We recently had a report RLlib will crash after maybe 12 hours of running, and we are wondering if there is a memory leak problem.

I can keep you updated.

**Comment by ericl** [comment]
Downgrading since this seems like an app-level leak now.

**Comment by rkooo567** [comment]
Open for the memory issue

**Comment by rkooo567** [comment]
Closing it and start tracking it from https://github.com/ray-project/ray/issues/19309
