### ISSUE TITLE
Running ray stop gives json.decoder.JSONDecodeError.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1855]
Running `ray stop` gives an error.

### System information
- **OS Platform and Distribution**: MacOS
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.4.0
- **Python version**: Python 3.6.0 :: Anaconda 4.3.0 (x86_64)

```
$ ray stop
No matching processes belonging to you were found
Traceback (most recent call last):
  File "/Users/rkn/anaconda3/bin/ray", line 11, in <module>
    load_entry_point('ray', 'console_scripts', 'ray')()
  File "/Users/rkn/Workspace/ray/python/ray/scripts/scripts.py", line 323, in main
    return cli()
  File "/Users/rkn/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rkn/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/rkn/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rkn/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rkn/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/rkn/Workspace/ray/python/ray/scripts/scripts.py", line 271, in stop
    pids = [str(server["pid"]) for server in list_running_servers()
  File "/Users/rkn/Workspace/ray/python/ray/scripts/scripts.py", line 271, in <listcomp>
    pids = [str(server["pid"]) for server in list_running_servers()
  File "/Users/rkn/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1667, in list_running_servers
    info = json.load(f)
  File "/Users/rkn/anaconda3/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Users/rkn/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/rkn/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/rkn/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by robertnishihara** [comment]
Ok, I think the issue was that `json.loads` was being called on an empty string.

This was resolved by doing

```
rm /Users/rkn/Library/Jupyter/runtime/*
```

where that directory was given by `jupyter_runtime_dir()`.
