### ISSUE TITLE
[workflow] Better error message when passing virtual actor into step function

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#18575]
```
import ray
ray.workflow.init()


@ray.workflow.virtual_actor
class Actor:
    def __init__(self):
        self.x = 10
    def xmethod(self):
        return 10

@ray.workflow.step
def f(x):
    return x.xmethod.run()


a = Actor.get_or_create("ABC")
f.step(a).run()
```

And the output:
```
    raise value
ray.exceptions.RaySystemError: System error: maximum recursion depth exceeded
traceback: Traceback (most recent call last):
  File "/home/yic/ray/python/ray/serialization.py", line 255, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/yic/ray/python/ray/serialization.py", line 190, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "/home/yic/ray/python/ray/serialization.py", line 168, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "/home/yic/ray/python/ray/serialization.py", line 158, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
  File "/home/yic/ray/python/ray/experimental/workflow/virtual_actor_class.py", line 457, in __getattr__
    if item in self._metadata.signatures:
  File "/home/yic/ray/python/ray/experimental/workflow/virtual_actor_class.py", line 457, in __getattr__
    if item in self._metadata.signatures:
  File "/home/yic/ray/python/ray/experimental/workflow/virtual_actor_class.py", line 457, in __getattr__
    if item in self._metadata.signatures:
  [Previous line repeated 974 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by wuisawesome** [comment]
Alternatively, it seems like we can just support this functionality

**Comment by iycheng** [comment]
Yes, I think that's a good way to go. We need to fix the serialization and deserialization problems for virtual actor.
