### ISSUE TITLE
[Bug] Ray Client ray.tune.run fails on remote workers with max_concurrent_trials TypeError

### ISSUE THREAD

**Issue by max0x7ba** [ray-project/ray#18655]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

My `ray.tune.run` succeeds on a local workstation. 

In a gcp cluster `ray.tune.run` fails with the following error:

```
2021-09-15 21:01:56.201 INFO ray.worker Using address ray://10.128.0.36:10001 set in the environment variable RAY_ADDRESS
Traceback (most recent call last):
  File "/home/max/anaconda3/envs/torch/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/max/anaconda3/envs/torch/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/max/src/research/es/tune4.py", line 339, in <module>
    main()
  File "/home/max/src/research/es/tune4.py", line 335, in main
    fn(symbol, options)
  File "/home/max/src/research/es/tune4.py", line 189, in tune
    analysis = ray.tune.run(
  File "/home/max/anaconda3/envs/torch/lib/python3.8/site-packages/ray/tune/tune.py", line 317, in run
    return ray.get(
  File "/home/max/anaconda3/envs/torch/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 88, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/home/max/anaconda3/envs/torch/lib/python3.8/site-packages/ray/util/client/api.py", line 42, in get
    return self.worker.get(vals, timeout=timeout)
  File "/home/max/anaconda3/envs/torch/lib/python3.8/site-packages/ray/util/client/worker.py", line 238, in get
    res = self._get(to_get, op_timeout)
  File "/home/max/anaconda3/envs/torch/lib/python3.8/site-packages/ray/util/client/worker.py", line 265, in _get
    raise err
types.RayTaskError(TypeError): ray::run() (pid=3578, ip=10.128.0.36)
  File "/home/max/anaconda3/envs/torch/lib/python3.8/site-packages/ray/tune/tune.py", line 475, in run
    if max_concurrent_trials < 1:
TypeError: '<' not supported between instances of 'list' and 'int'
```

My code doesn't specify `max_concurrent_trials` when calling `ray.tune.run`:
```
analysis = ray.tune.run(
    ray.tune.with_parameters(train, inputs=(...)),
    metric=..., mode=...,
    config=config,
    scheduler=MedianStoppingRule(),
    search_alg=HyperOptSearch(),
    num_samples=10,
)
```

Where does that `max_concurrent_trials` of type `list` come from?

Software versions:
* Ray: https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl fetched on 2021-09-15 20:30 UTC.
* Python: 3.8.10
* Ubuntu 20.04.3 LTS

### Reproduction script

TBD

### Anything else

This error doesn't happen when `ray.tune.run` is invoked with no head node, or on a head node with `RAY_ADDRESS=auto`.

This error only happens with Ray Client use case https://docs.ray.io/en/master/cluster/ray-client.html when I set `RAY_ADDRESS=ray://10.128.0.36:10001` and run my script from elsewhere.

It suggests that IPC between a remote cluster Ray Client and the head node may be broken.

@richardliaw 

### Are you willing to submit a PR?

I would if I had a clue.

- [ ] Yes I am willing to submit a PR!

**Comment by max0x7ba** [comment]
It was my mistake to invoke `ray.init` not on a head node.

**Comment by xwjiang2010** [comment]
Thanks for reporting the issue. From what you described, it seems to be related to how ray client does SER/DESER. @AmeerHajAli can you help triage?

**Comment by ckw017** [comment]
Currently a guess, but I think what's happening here is that this call https://github.com/ray-project/ray/blob/master/python/ray/tune/tune.py#L318 is getting triggered, but max_concurrent_trials isn't specified here, and so the call is passing in "loggers" for the value of "max_concurrent_trials" (loggers is the next thing in the list).

**Comment by mwtian** [comment]
It seems `remote_run` calls `run()` underneath, so `remote_run` should indeed pass in the `max_concurrent_trials` parameter. Assigning to authors of #17905 for further investigations. cc @Yard1 @krfricke

**Comment by AmeerHajAli** [comment]
Nice catch.
@richardliaw , should we make these calls as arg=val to avoid such bugs?

**Comment by AmeerHajAli** [comment]
@Yard1 @krfricke , can you please make sure this bug has a test?

**Comment by Yard1** [comment]
Thanks, will get a PR out ASAP

**Comment by Yard1** [comment]
Fixed in https://github.com/ray-project/ray/pull/18733, thanks for reporting!

**Comment by xwjiang2010** [comment]
Thanks folks for investigating!
