### ISSUE TITLE
[Bug] can not the Unity3D  serving example

### ISSUE THREAD

**Issue by xieshaocong-ethan** [ray-project/ray#18668]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

Try to run  `unity3d_server.py` and `unity3d_client.py` in local,but some errors occur.

`unity3d_server.py` 
> 2021-09-16 17:54:28,283	INFO services.py:1250 -- View the Ray dashboard at http://127.0.0.1:8265
2021-09-16 17:54:38,233	INFO trainer.py:736 -- Tip: set framework=tfe or the --eager flag to enable TensorFlow eager execution
2021-09-16 17:54:38,233	WARNING ppo.py:141 -- `train_batch_size` (256) cannot be achieved with your other settings (num_workers=0 num_envs_per_worker=1 rollout_fragment_length=20)! Auto-adjusting `rollout_fragment_length` to 256.
2021-09-16 17:54:38,233	INFO ppo.py:164 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
2021-09-16 17:54:38,233	INFO trainer.py:753 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
2021-09-16 17:54:41,195	WARNING trainer_template.py:185 -- `execution_plan` functions should accept `trainer`, `workers`, and `config` as args!
127.0.0.1 - - [16/Sep/2021 17:55:13] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2021 17:55:53] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2021 17:56:00] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2021 17:56:12] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2021 17:56:22] "POST / HTTP/1.1" 200 -
Traceback (most recent call last):
  File "C:/mlagent/ray-master/rllib/examples/serving/unity3d_server.py", line 120, in <module>
    print(trainer.train())
  File "C:\ProgramData\Anaconda3\envs\ml_agents\lib\site-packages\ray\rllib\agents\trainer.py", line 665, in train
    raise e
  File "C:\ProgramData\Anaconda3\envs\ml_agents\lib\site-packages\ray\rllib\agents\trainer.py", line 651, in train
    result = Trainable.train(self)
  File "C:\ProgramData\Anaconda3\envs\ml_agents\lib\site-packages\ray\tune\trainable.py", line 239, in train
    result = self.step()
  File "C:\ProgramData\Anaconda3\envs\ml_agents\lib\site-packages\ray\rllib\agents\trainer_template.py", line 206, in step
    step_results = next(self.train_exec_impl)
  File "C:\ProgramData\Anaconda3\envs\ml_agents\lib\site-packages\ray\util\iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "C:\ProgramData\Anaconda3\envs\ml_agents\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\ProgramData\Anaconda3\envs\ml_agents\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\ProgramData\Anaconda3\envs\ml_agents\lib\site-packages\ray\util\iter.py", line 843, in apply_filter
    for item in it:
  File "C:\ProgramData\Anaconda3\envs\ml_agents\lib\site-packages\ray\util\iter.py", line 843, in apply_filter
    for item in it:
  File "C:\ProgramData\Anaconda3\envs\ml_agents\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\ProgramData\Anaconda3\envs\ml_agents\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\ProgramData\Anaconda3\envs\ml_agents\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "C:\ProgramData\Anaconda3\envs\ml_agents\lib\site-packages\ray\util\iter.py", line 876, in apply_flatten
    for item in it:
  File "C:\ProgramData\Anaconda3\envs\ml_agents\lib\site-packages\ray\util\iter.py", line 791, in apply_foreach
    result = fn(item)
  File "C:\ProgramData\Anaconda3\envs\ml_agents\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 182, in __call__
    out = SampleBatch.concat_samples(self.buffer)
  File "C:\ProgramData\Anaconda3\envs\ml_agents\lib\site-packages\ray\rllib\policy\sample_batch.py", line 195, in concat_samples
    assert s.zero_padded == zero_padded
AttributeError: 'MultiAgentBatch' object has no attribute 'zero_padded'
127.0.0.1 - - [16/Sep/2021 17:56:25] "POST / HTTP/1.1" 200 -

`unity3d_client.py`
> Created UnityEnvironment for port 5005
C:\ProgramData\Anaconda3\envs\ml_agents\lib\site-packages\ray\rllib\utils\spaces\space_utils.py:253: RuntimeWarning: invalid value encountered in add
  a = s.low + (a + 1.0) * (s.high - s.low) / 2.0

### Reproduction script

.\rllib\examples\serving\unity3d_server.py
 .\rllib\examples\serving\unity3d_client.py

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by sven1977** [comment]
Here is a PR that fixes the issue and adds a dummy Unity3D client/server test to our CI suite.

The problem was the multi-agent external env setup of the Unity example (as opposed to the CartPole example).

https://github.com/ray-project/ray/pull/18942
