### ISSUE TITLE
[Bug] RLLib intro example doesn't work out of the box

### ISSUE THREAD

**Issue by worldveil** [ray-project/ray#18726]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

I tried running the example in a couple of ways found here
https://docs.ray.io/en/latest/rllib.html

And it did not work. Details below.

### Reproduction script

```
% cat requirements.txt 
ray[rllib]
gym
gputil
% python --version
Python 3.7.7
% pip freeze | grep ray
ray==1.6.0
% pip install -r requirements.txt
```

## Issue 1: rllib pip install doesn't set paths correctly
Then I ran `rllib train --run=PPO --env=CartPole-v0`, this ended up referencing a path that wasn't in the virtualenv

```
% rllib train --run=PPO --env=CartPole-v0          
Traceback (most recent call last):
  File "/usr/local/bin/rllib", line 33, in <module>
    sys.exit(load_entry_point('ray', 'console_scripts', 'rllib')())
  File "/usr/local/bin/rllib", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/__init__.py", line 5, in <module>
    from ray.rllib.env.base_env import BaseEnv
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/env/__init__.py", line 3, in <module>
    from ray.rllib.env.base_env import BaseEnv
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/env/base_env.py", line 1, in <module>
    from ray.rllib.env.external_env import ExternalEnv
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/env/external_env.py", line 5, in <module>
    from ray.rllib.utils.annotations import PublicAPI
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/utils/__init__.py", line 18, in <module>
    from ray.tune.utils import merge_dicts, deep_update
  File "/usr/local/lib/python3.8/site-packages/ray/tune/__init__.py", line 2, in <module>
    from ray.tune.tune import run_experiments, run
  File "/usr/local/lib/python3.8/site-packages/ray/tune/tune.py", line 5, in <module>
    from ray.tune.analysis import ExperimentAnalysis
  File "/usr/local/lib/python3.8/site-packages/ray/tune/analysis/__init__.py", line 1, in <module>
    from ray.tune.analysis.experiment_analysis import ExperimentAnalysis, Analysis
  File "/usr/local/lib/python3.8/site-packages/ray/tune/analysis/experiment_analysis.py", line 13, in <module>
    from ray.tune.trial import Trial
  File "/usr/local/lib/python3.8/site-packages/ray/tune/trial.py", line 15, in <module>
    from ray.tune.durable_trainable import DurableTrainable
  File "/usr/local/lib/python3.8/site-packages/ray/tune/durable_trainable.py", line 4, in <module>
    from ray.tune.trainable import Trainable, TrainableUtil
  File "/usr/local/lib/python3.8/site-packages/ray/tune/trainable.py", line 10, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

## Issue 2: Intro Rllib task requires `ray[default]`

I tried with the correct path:

```
% /Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/bin/rllib train --run=PPO --env=CartPole-v0
Traceback (most recent call last):
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/bin/rllib", line 8, in <module>
    sys.exit(cli())
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/scripts.py", line 34, in cli
    train.run(options, train_parser)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/train.py", line 240, in run
    local_mode=args.local_mode)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/worker.py", line 896, in init
    ray_params=ray_params)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/node.py", line 248, in __init__
    self.start_head_processes()
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/node.py", line 905, in start_head_processes
    self.start_dashboard(require_dashboard=True)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/node.py", line 756, in start_dashboard
    port=self._ray_params.dashboard_port)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/_private/services.py", line 1270, in start_dashboard
    raise e from e
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/_private/services.py", line 1196, in start_dashboard
    raise ImportError(DASHBOARD_DEPENDENCY_ERROR_MESSAGE)
ImportError: Not all Ray Dashboard dependencies were found. To use the dashboard please install Ray using `pip install ray[default]`.
zsh: terminated  /Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/bin/rllib train 
```

## Issue 3: fails without GPUs

```
% /Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/bin/rllib train --run=PPO --env=CartPole-v0 
2021-09-17 15:42:22,367 INFO services.py:1265 -- View the Ray dashboard at http://127.0.0.1:8265
== Status ==
Memory usage on this node: 11.6/16.0 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/16 CPUs, 0/0 GPUs, 0.0/4.12 GiB heap, 0.0/2.06 GiB objects
Result logdir: /Users/will/ray_results/default
Number of trials: 1/1 (1 PENDING)
+-----------------------------+----------+-------+
| Trial name                  | status   | loc   |
|-----------------------------+----------+-------|
| PPO_CartPole-v0_87027_00000 | PENDING  |       |
+-----------------------------+----------+-------+


(pid=39902) 2021-09-17 15:42:26,653     INFO ppo.py:159 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
(pid=39902) 2021-09-17 15:42:26,654     INFO trainer.py:728 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
2021-09-17 15:42:28,072 ERROR trial_runner.py:773 -- Trial PPO_CartPole-v0_87027_00000: Error processing event.
Traceback (most recent call last):
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 739, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 746, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/worker.py", line 1623, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::PPO.__init__() (pid=39902, ip=192.168.86.112)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 136, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 592, in __init__
    super().__init__(config, logger_creator)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/tune/trainable.py", line 103, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 146, in setup
    super().setup(config)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 739, in setup
    self._init(self.config, self.env_creator)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 175, in _init
    num_workers=self.config["num_workers"])
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 827, in _make_workers
    logdir=self.logdir)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 85, in __init__
    lambda p, pid: (pid, p.observation_space, p.action_space)))
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=39898, ip=192.168.86.112)
AttributeError: 'NoneType' object has no attribute 'config'

During handling of the above exception, another exception occurred:

ray::RolloutWorker.__init__() (pid=39898, ip=192.168.86.112)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 560, in __init__
    if len(get_tf_gpu_devices()) < num_gpus:
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/utils/tf_ops.py", line 52, in get_gpu_devices
    devices = tf.config.experimental.list_physical_devices()
AttributeError: 'NoneType' object has no attribute 'config'
== Status ==
Memory usage on this node: 11.7/16.0 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/16 CPUs, 0/0 GPUs, 0.0/4.12 GiB heap, 0.0/2.06 GiB objects
Result logdir: /Users/will/ray_results/default
Number of trials: 1/1 (1 ERROR)
+-----------------------------+----------+-------+
| Trial name                  | status   | loc   |
|-----------------------------+----------+-------|
| PPO_CartPole-v0_87027_00000 | ERROR    |       |
+-----------------------------+----------+-------+
Number of errored trials: 1
+-----------------------------+--------------+---------------------------------------------------------------------------------------------+
| Trial name                  |   # failures | error file                                                                                  |
|-----------------------------+--------------+---------------------------------------------------------------------------------------------|
| PPO_CartPole-v0_87027_00000 |            1 | /Users/will/ray_results/default/PPO_CartPole-v0_87027_00000_0_2021-09-17_15-42-24/error.txt |
+-----------------------------+--------------+---------------------------------------------------------------------------------------------+

(pid=39902) 2021-09-17 15:42:28,069     ERROR worker.py:428 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::PPO.__init__() (pid=39902, ip=192.168.86.112)
(pid=39902)   File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 136, in __init__
(pid=39902)     Trainer.__init__(self, config, env, logger_creator)
(pid=39902)   File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 592, in __init__
(pid=39902)     super().__init__(config, logger_creator)
(pid=39902)   File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/tune/trainable.py", line 103, in __init__
(pid=39902)     self.setup(copy.deepcopy(self.config))
(pid=39902)   File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 146, in setup
(pid=39902)     super().setup(config)
(pid=39902)   File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 739, in setup
(pid=39902)     self._init(self.config, self.env_creator)
(pid=39902)   File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 175, in _init
(pid=39902)     num_workers=self.config["num_workers"])
(pid=39902)   File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 827, in _make_workers
(pid=39902)     logdir=self.logdir)
(pid=39902)   File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 85, in __init__
(pid=39902)     lambda p, pid: (pid, p.observation_space, p.action_space)))
(pid=39902) ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=39898, ip=192.168.86.112)
(pid=39902) AttributeError: 'NoneType' object has no attribute 'config'
(pid=39902) 
(pid=39902) During handling of the above exception, another exception occurred:
(pid=39902) 
(pid=39902) ray::RolloutWorker.__init__() (pid=39898, ip=192.168.86.112)
(pid=39902)   File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 560, in __init__
(pid=39902)     if len(get_tf_gpu_devices()) < num_gpus:
(pid=39902)   File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/utils/tf_ops.py", line 52, in get_gpu_devices
(pid=39902)     devices = tf.config.experimental.list_physical_devices()
(pid=39902) AttributeError: 'NoneType' object has no attribute 'config'
(pid=39898) 2021-09-17 15:42:28,056     ERROR worker.py:428 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=39898, ip=192.168.86.112)
(pid=39898) AttributeError: 'NoneType' object has no attribute 'config'
(pid=39898) 
(pid=39898) During handling of the above exception, another exception occurred:
(pid=39898) 
(pid=39898) ray::RolloutWorker.__init__() (pid=39898, ip=192.168.86.112)
(pid=39898)   File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 560, in __init__
(pid=39898)     if len(get_tf_gpu_devices()) < num_gpus:
(pid=39898)   File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/utils/tf_ops.py", line 52, in get_gpu_devices
(pid=39898)     devices = tf.config.experimental.list_physical_devices()
(pid=39898) AttributeError: 'NoneType' object has no attribute 'config'
(pid=39899) 2021-09-17 15:42:28,058     ERROR worker.py:428 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=39899, ip=192.168.86.112)
(pid=39899) AttributeError: 'NoneType' object has no attribute 'config'
(pid=39899) 
(pid=39899) During handling of the above exception, another exception occurred:
(pid=39899) 
(pid=39899) ray::RolloutWorker.__init__() (pid=39899, ip=192.168.86.112)
(pid=39899)   File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 560, in __init__
(pid=39899)     if len(get_tf_gpu_devices()) < num_gpus:
(pid=39899)   File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/utils/tf_ops.py", line 52, in get_gpu_devices
(pid=39899)     devices = tf.config.experimental.list_physical_devices()
(pid=39899) AttributeError: 'NoneType' object has no attribute 'config'
Traceback (most recent call last):
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/bin/rllib", line 8, in <module>
    sys.exit(cli())
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/scripts.py", line 34, in cli
    train.run(options, train_parser)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/rllib/train.py", line 255, in run
    concurrent=True)
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/tune/tune.py", line 654, in run_experiments
    callbacks=callbacks).trials
  File "/Users/will/opt/anaconda3/envs/entrypoint_tune_anyscale/lib/python3.7/site-packages/ray/tune/tune.py", line 555, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_CartPole-v0_87027_00000])
```

## Issue 4: example runs forever / doesn't have terminating criteria?

This does seem to run, and I get output:

```
from ray import tune
from ray.rllib.agents.ppo import PPOTrainer

tune.run(PPOTrainer, config={
   "env": "CartPole-v0",
   "log_level": "INFO",
   "framework": "torch", # for PyTorch
   "simple_optimizer": True,
})
```

With `simple_optimizer` setting. So we should update the docs to show that workaround.

But it keeps running forever? Should we have some kind of exit criteria?

```
Result for PPO_CartPole-v0_1f214_00000:
  agent_timesteps_total: 1580000
  custom_metrics: {}
  date: 2021-09-17_16-29-50
  done: false
  episode_len_mean: 200.0
  episode_media: {}
  episode_reward_max: 200.0
  episode_reward_mean: 200.0
  episode_reward_min: 200.0
  episodes_this_iter: 20
  episodes_total: 8179
  experiment_id: 3f9bb82abc4c44c8a6b301c88653500d
  hostname: wills-mbp.lan
  info:
    learner:
      default_policy:
        custom_metrics: {}
        learner_stats:
          allreduce_latency: 0.0
          cur_kl_coeff: 1.9959186750038202e-111
          cur_lr: 5.0000000000000016e-05
          entropy: 0.14825084895128385
          entropy_coeff: 0.0
          kl: 0.00235856177582384
          policy_loss: -0.0005798731246613898
          total_loss: 211.445995926857
          vf_explained_var: 0.5923879742622375
          vf_loss: 211.44657498200735
        model: {}
    num_agent_steps_sampled: 1580000
    num_steps_sampled: 1580000
    num_steps_trained: 1580000
  iterations_since_restore: 395
  node_ip: 192.168.86.112
  num_healthy_workers: 2
  off_policy_estimator: {}
  perf:
    cpu_util_percent: 12.944444444444445
    ram_util_percent: 69.42222222222223
  pid: 40374
  policy_reward_max: {}
  policy_reward_mean: {}
  policy_reward_min: {}
  sampler_perf:
    mean_action_processing_ms: 0.03695895955371893
    mean_env_render_ms: 0.0
    mean_env_wait_ms: 0.045445817351471865
    mean_inference_ms: 0.7063202555416325
    mean_raw_obs_processing_ms: 0.053378559897418805
  time_since_restore: 2577.3544540405273
  time_this_iter_s: 6.370443105697632
  time_total_s: 2577.3544540405273
  timers:
    learn_throughput: 810.487
    learn_time_ms: 4935.304
    sample_throughput: 2346.585
    sample_time_ms: 1704.605
    update_time_ms: 1.793
  timestamp: 1631921390
  timesteps_since_restore: 0
  timesteps_total: 1580000
  training_iteration: 395
  trial_id: 1f214_00000
  
== Status ==
Memory usage on this node: 11.2/16.0 GiB
Using FIFO scheduling algorithm.
Resources requested: 3.0/16 CPUs, 0/0 GPUs, 0.0/4.26 GiB heap, 0.0/2.13 GiB objects
Result logdir: /Users/will/ray_results/PPO_2021-09-17_15-46-39
Number of trials: 1/1 (1 RUNNING)
+-----------------------------+----------+----------------------+--------+------------------+---------+----------+----------------------+----------------------+--------------------+
| Trial name                  | status   | loc                  |   iter |   total time (s) |      ts |   reward |   episode_reward_max |   episode_reward_min |   episode_len_mean |
|-----------------------------+----------+----------------------+--------+------------------+---------+----------+----------------------+----------------------+--------------------|
| PPO_CartPole-v0_1f214_00000 | RUNNING  | 192.168.86.112:40374 |    395 |          2577.35 | 1580000 |      200 |                  200 |                  200 |                200 |
+-----------------------------+----------+----------------------+--------+------------------+---------+----------+----------------------+----------------------+--------------------+
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sven1977** [comment]
I cannot confirm 1) or 3).

2) Has been fixed by this PR here: https://github.com/ray-project/ray/pull/18705

To reproduce, I did on my Mac (no GPU machine):
```
conda create -n rllib_test python=3.7
conda activate rllib_test
pip install ray[rllib]
# cd into ray directory (e.g. from a cloned ray repo).
cd ray
pip install -r python/requirements/ml/requirements_rllib.txt
rllib train --run PPO --env CartPole-v0
```

Removing P0 and "release blocker" tags and downgrading to P2.

TODO:
- Mention in the example that for <= 1.6, the flag `--no-ray-ui` must be set on the `rllib train` command line.
- Add stoping criterium to example (e.g. reward=180.0).

**Comment by sven1977** [comment]
There is also a PR that addresses the dashboard error and enhances the documentation to add a stopping criterium:
https://github.com/ray-project/ray/pull/18759
