### ISSUE TITLE
[Bug] Connecting with old version of ray client to nightly version of server raises unclear error

### ISSUE THREAD

**Issue by ckw017** [ray-project/ray#18721]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

Connecting with a 1.6 client to a nightly server gives this error:

```
  File "/Users/cwong/anaconda3/envs/anyscale/lib/python3.7/site-packages/ray/util/client/__init__.py", line 83, in connect
    self.client_worker._server_init(job_config)
  File "/Users/cwong/anaconda3/envs/anyscale/lib/python3.7/site-packages/ray/util/client/worker.py", line 532, in _server_init
    self._call_init(init_req)
  File "/Users/cwong/anaconda3/envs/anyscale/lib/python3.7/site-packages/ray/util/client/worker.py", line 513, in _call_init
    f"Init Failure From Server:\n{init_resp.msg}")
ConnectionAbortedError: Init Failure From Server:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/server/proxier.py", line 613, in Datapath
    client_id, job_config):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/server/proxier.py", line 271, in start_specific_server
    specific_server=specific_server,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/server/proxier.py", line 226, in _create_runtime_env
    "Failed to create runtime_env for Ray client "
RuntimeError: Failed to create runtime_env for Ray client server: Fetch uri failed
```

Expected behavior would be to display a version mismatch message (either protocol version, or ray version).

### Reproduction script

1. Start a client server with with a nightly wheel
2. Run a script on ray 1.6 (or lower) that connects to the client server

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jakub-valenta** [comment]
Same error appeared while connecting 1.8 client to 1.8 server:

```
Traceback (most recent call last):
 File "/usr/local/lib/python3.9/dist-packages/ray/util/client/__init__.py", line 221, in connect
 conn = self.get_context().connect(*args, **kw_args)
 File "/usr/local/lib/python3.9/dist-packages/ray/util/client/__init__.py", line 81, in connect
 self.client_worker._server_init(job_config, ray_init_kwargs)
 File "/usr/local/lib/python3.9/dist-packages/ray/util/client/worker.py", line 698, in _server_init
 raise ConnectionAbortedError(
ConnectionAbortedError: Initialization failure from server:
Traceback (most recent call last):
 File "/usr/local/lib/python3.9/dist-packages/ray/util/client/server/proxier.py", line 621, in Datapath
 if not self.proxy_manager.start_specific_server(
 File "/usr/local/lib/python3.9/dist-packages/ray/util/client/server/proxier.py", line 278, in start_specific_server
 serialized_runtime_env_context = self._create_runtime_env(
 File "/usr/local/lib/python3.9/dist-packages/ray/util/client/server/proxier.py", line 232, in _create_runtime_env
 raise RuntimeError(
RuntimeError: Failed to create runtime_env for Ray client server: Fetch uri failed
```

After process restart it started to work again. It was probably caused by some network problem.
