### ISSUE TITLE
[weekly release test] horovod_test is failing 

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#18764]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_BVErzhbqnKrRCihMLPU9pyEc?command-history-section=command_history&job-section=jobs

Specifically there is an error/warning in atuoscaler logic and worker.py

2021-09-19 13:27:42,478	WARNING worker.py:1227 -- The autoscaler failed with the following error:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 317, in run
    self._run()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 219, in _run
    self.autoscaler.update()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 163, in update
    raise e
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 148, in update
    self._update()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 262, in _update
    ensure_min_cluster_size=self.load_metrics.get_resource_requests())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/resource_demand_scheduler.py", line 197, in get_nodes_to_launch
    strict_spreads, node_resources, node_type_counts)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/resource_demand_scheduler.py", line 542, in reserve_and_allocate_spread
    assert not unfulfilled
AssertionError

2021-09-19 13:28:40,892	WARNING worker.py:1227 -- This worker was asked to execute a function that it does not have registered. You may have to restart Ray.

### Reproduction script

weekly release test

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwjiang2010** [comment]
@krfricke Is this the same as what you said about "infra error"? - database error storing results.

**Comment by amogkam** [comment]
Yeah the error is not coming from the test itself:

```
Traceback (most recent call last):
--
  | File "release/e2e.py", line 1937, in <module>
  | app_config_id_override=args.app_config_id_override,
  | File "release/e2e.py", line 1840, in run_test
  | report_result(**report_kwargs)
  | File "release/e2e.py", line 537, in report_result
  | sql=sql,
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 386, in _api_call
  | return self._make_api_call(operation_name, kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
  | raise error_class(parsed_response, operation_name)
```

**Comment by xwjiang2010** [comment]
Got it!
Do we have a process on how to solve/improve on infra errors?
