### ISSUE TITLE
[Bug] Compute_action for Trajectory view API

### ISSUE THREAD

**Issue by kapilPython** [ray-project/ray#18777]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

Want to Evaluate the frame-stacking model with trajectory view API and the compute_single_action does not work beacause of the custom view_requirements added during training. 

### Reproduction script

import argparse
import gym
import numpy as np

import ray
from ray import tune
from ray.rllib.examples.env.stateless_cartpole import StatelessCartPole
from ray.rllib.examples.models.trajectory_view_utilizing_models import \
    FrameStackingCartPoleModel, TorchFrameStackingCartPoleModel
from ray.rllib.models.catalog import ModelCatalog
from ray.rllib.utils.framework import try_import_tf
from ray.rllib.utils.test_utils import check_learning_achieved
from ray.rllib import agents

tf1, tf, tfv = try_import_tf()

parser = argparse.ArgumentParser()
parser.add_argument(
    "--run",
    type=str,
    default="PPO",
    help="The RLlib-registered algorithm to use.")
parser.add_argument(
    "--framework",
    choices=["tf", "tf2", "tfe", "torch"],
    default="tf",
    help="The DL framework specifier.")
parser.add_argument(
    "--as-test",
    action="store_true",
    help="Whether this script should be run as a test: --stop-reward must "
    "be achieved within --stop-timesteps AND --stop-iters.")
parser.add_argument(
    "--stop-iters",
    type=int,
    default=5,
    help="Number of iterations to train.")
parser.add_argument(
    "--stop-timesteps",
    type=int,
    default=200000,
    help="Number of timesteps to train.")
parser.add_argument(
    "--stop-reward",
    type=float,
    default=150.0,
    help="Reward at which we stop training.")

if __name__ == "__main__":
    args = parser.parse_args()
    ray.init(num_cpus=3)

    ModelCatalog.register_custom_model(
        "frame_stack_model", FrameStackingCartPoleModel
        if args.framework != "torch" else TorchFrameStackingCartPoleModel)
    tune.register_env("stateless_cartpole", lambda c: StatelessCartPole())

    config = {
        "env": "stateless_cartpole",
        "model": {
            "vf_share_layers": True,
            "custom_model": "frame_stack_model",
            "custom_model_config": {
                "num_frames": 16,
            },

            # To compare against a simple LSTM:
            # "use_lstm": True,
            # "lstm_use_prev_action": True,
            # "lstm_use_prev_reward": True,

            # To compare against a simple attention net:
            # "use_attention": True,
            # "attention_use_n_prev_actions": 1,
            # "attention_use_n_prev_rewards": 1,
        },
        "num_sgd_iter": 5,
        "vf_loss_coeff": 0.0001,
        "framework": args.framework,
    }

    stop = {
        "training_iteration": args.stop_iters,
        "timesteps_total": args.stop_timesteps,
        "episode_reward_mean": args.stop_reward,
    }

    results = tune.run(args.run,
        config=config,
        stop=stop,
        checkpoint_freq = 200,
        local_dir = 'attnet_trajectory',
        checkpoint_at_end = True,
        verbose=2)

    checkpoints = results.get_trial_checkpoints_paths(trial=results.get_best_trial('episode_reward_mean', mode='max'),
                                                                                    metric='episode_reward_mean')

    checkpoint_path = checkpoints[0][0]
    agent = agents.ppo.PPOTrainer(config, env="stateless_cartpole")
    agent.restore(checkpoint_path)

    env = StatelessCartPole()

    # run until episode ends
    for _ in range(10):
        episode_reward = 0
        reward = 0.
        action = 0
        done = False
        obs = env.reset()
        while not done:
            action, state, logits = agent.compute_single_action(obs) 
            obs, reward, done, info = env.step(action)
            episode_reward += reward

        print("reward: {}".format(episode_reward))

    if args.as_test:
        check_learning_achieved(results, args.stop_reward)
    `ray.shutdown()```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kapilPython** [comment]
The error produced by the above script:

C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\gym\logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
2021-09-21 12:18:32,676 ERROR tf_run_builder.py:46 -- Error fetching: [<tf.Tensor 'default_policy/cond_1/Merge:0' shape=(?,) dtype=int64>, {'action_prob': <tf.Tensor 'default_policy/Exp:0' shape=(?,) dtype=float32>, 'action_logp': <tf.Tensor 'default_policy/cond_2/Merge:0' shape=(?,) dtype=float32>, 'action_dist_inputs': <tf.Tensor 'default_policy/model/dense_2/BiasAdd:0' shape=(?, 2) dtype=float32>, 'vf_preds': <tf.Tensor 'default_policy/Squeeze_2:0' shape=(?,) dtype=float32>}], feed_dict={<tf.Tensor 'default_policy/obs:0' shape=(?, 2) dtype=float32>: [array([ 0.0123411 , -0.02023288])], <tf.Tensor 'default_policy/is_training:0' shape=() dtype=bool>: False, <tf.Tensor 'default_policy/is_exploring:0' shape=() dtype=bool>: True, <tf.Tensor 'default_policy/timestep:0' shape=() dtype=int64>: 20000}
Traceback (most recent call last):
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\client\session.py", line 1359, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\client\session.py", line 1451, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'default_policy/prev_n_obs' with dtype float and shape [?,?,2]
         [[{{node default_policy/prev_n_obs}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\utils\tf_run_builder.py", line 42, in get
    self._executed = run_timeline(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\utils\tf_run_builder.py", line 89, in run_timeline
    fetches = sess.run(ops, feed_dict=feed_dict)
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\client\session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\client\session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\client\session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'default_policy/prev_n_obs' with dtype float and shape [?,?,2]
         [[node default_policy/prev_n_obs (defined at C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\utils\tf_ops.py:64) ]]

Original stack trace for 'default_policy/prev_n_obs':
  File "c:\Users\kdeshp\test\eval-test-simple-fs.py", line 100, in <module>
    agent = agents.ppo.PPOTrainer(config, env="stateless_cartpole")
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\agents\trainer_template.py", line 136, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\agents\trainer.py", line 592, in __init__
    super().__init__(config, logger_creator)
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\tune\trainable.py", line 103, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\agents\trainer_template.py", line 146, in setup
    super().setup(config)
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\agents\trainer.py", line 739, in setup
    self._init(self.config, self.env_creator)
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\agents\trainer_template.py", line 170, in _init
    self.workers = self._make_workers(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\agents\trainer.py", line 821, in _make_workers
    return WorkerSet(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 103, in __init__
    self._local_worker = self._make_worker(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 399, in _make_worker
    worker = cls(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 580, in __init__
    self._build_policy_map(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1375, in _build_policy_map
    self.policy_map.create_policy(name, orig_cls, obs_space, act_space,
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\policy\policy_map.py", line 126, in create_policy
    self[policy_id] = class_(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\policy\tf_policy_template.py", line 237, in __init__
    DynamicTFPolicy.__init__(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\policy\dynamic_tf_policy.py", line 232, in __init__
    self._get_input_dict_and_dummy_batch(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\policy\dynamic_tf_policy.py", line 553, in _get_input_dict_and_dummy_batch
    input_dict[view_col] = get_placeholder(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\utils\tf_ops.py", line 64, in get_placeholder
    return tf1.placeholder(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\ops\array_ops.py", line 3285, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 6727, in placeholder
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\framework\ops.py", line 3561, in _create_op_internal
    ret = Operation(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\framework\ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

Traceback (most recent call last):
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\client\session.py", line 1359, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\client\session.py", line 1451, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'default_policy/prev_n_obs' with dtype float and shape [?,?,2]
         [[{{node default_policy/prev_n_obs}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\kdeshp\test\eval-test-simple-fs.py", line 113, in <module>
    action, state, logits = agent.compute_single_action(obs)
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\agents\trainer.py", line 1009, in compute_single_action
    result = policy.compute_single_action(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\policy\policy.py", line 254, in compute_single_action
    out = self.compute_actions(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\policy\tf_policy.py", line 400, in compute_actions
    fetched = builder.get(to_fetch)
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\utils\tf_run_builder.py", line 48, in get
    raise e
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\utils\tf_run_builder.py", line 42, in get
    self._executed = run_timeline(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\utils\tf_run_builder.py", line 89, in run_timeline
    fetches = sess.run(ops, feed_dict=feed_dict)
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\client\session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\client\session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\client\session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'default_policy/prev_n_obs' with dtype float and shape [?,?,2]
         [[node default_policy/prev_n_obs (defined at C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\utils\tf_ops.py:64) ]]

Original stack trace for 'default_policy/prev_n_obs':
  File "c:\Users\kdeshp\test\eval-test-simple-fs.py", line 100, in <module>
    agent = agents.ppo.PPOTrainer(config, env="stateless_cartpole")
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\agents\trainer_template.py", line 136, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\agents\trainer.py", line 592, in __init__
    super().__init__(config, logger_creator)
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\tune\trainable.py", line 103, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\agents\trainer_template.py", line 146, in setup
    super().setup(config)
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\agents\trainer.py", line 739, in setup
    self._init(self.config, self.env_creator)
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\agents\trainer_template.py", line 170, in _init
    self.workers = self._make_workers(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\agents\trainer.py", line 821, in _make_workers
    return WorkerSet(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 103, in __init__
    self._local_worker = self._make_worker(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 399, in _make_worker
    worker = cls(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 580, in __init__
    self._build_policy_map(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1375, in _build_policy_map
    self.policy_map.create_policy(name, orig_cls, obs_space, act_space,
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\policy\policy_map.py", line 126, in create_policy
    self[policy_id] = class_(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\policy\tf_policy_template.py", line 237, in __init__
    DynamicTFPolicy.__init__(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\policy\dynamic_tf_policy.py", line 232, in __init__
    self._get_input_dict_and_dummy_batch(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\policy\dynamic_tf_policy.py", line 553, in _get_input_dict_and_dummy_batch
    input_dict[view_col] = get_placeholder(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\ray\rllib\utils\tf_ops.py", line 64, in get_placeholder
    return tf1.placeholder(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\ops\array_ops.py", line 3285, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 6727, in placeholder
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\framework\ops.py", line 3561, in _create_op_internal
    ret = Operation(
  File "C:\Users\kdeshp\Anaconda3\envs\resinet_env\lib\site-packages\tensorflow\python\framework\ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

**Comment by mg64ve** [comment]
I am also interested in this since I haven't find any solution. Thanks

**Comment by sven1977** [comment]
Hey @mg64ve , @kapilPython , great catch! This is actually not covered well yet by the Trainer.compute_action/compute_single_action API.

I'll provide a PR for this.

As a (hacky) workaround - for now - you could try something like:
```
agent.get_policy().compute_actions_from_input_dict({"obs": np.array([obs]), "prev_n_obs": np.expand_dims(np.stack([obs for _ in range(16)]), axis=0), "prev_n_actions": np.expand_dims(np.stack([0 for _ in range(16)]), axis=0), "prev_n_rewards": np.expand_dims(np.stack([1.0 for _ in range(16)]), axis=0)})
```

I just tried the above on your example script and it works fine. You just have to extract the action again from the returned tuple (0th element + unbatch to get the single action).
Also, of course, you have to fill in the correct values for prev_n_obs, prev_n_rewards, prev_n_actions (I used dummy values of 0, 1.0, and obs).

**Comment by kapilPython** [comment]
@sven1977 Thanks for your reply the hack really works, I also tried to accomplish this how rllib uses the trajectory view API while training. With SimpleListCollector class I tried to use get_inference_input_dict() funtion to generate an input_dict and then using compute_actions_from_input_dict() function to get the action, but since the SimpleListCollector did not have initial data it kept on failing. I hope this experiment could be useful for fixing the issue.

**Comment by sven1977** [comment]
Hey @kapilPython , the PR that fixes this has been merged into master. If you take a look at the changed example script below, you can see how you can now simply use `Trainer.compute_single_action(input_dict=...)`. Your input dict must contain your custom defined traj. view API keys, of course, like: `prev_n_obs`, etc...

https://github.com/ray-project/ray/blob/master/rllib/examples/trajectory_view_api.py

**Comment by elahehsabziyan** [comment]
Hello all, I have a question. I am using DQN algorithm for a custom multi agent environment. After training, I want to test the performance of the model, then I need to use .compute_actions(obs,policy_id = DQNTFPolicy). Because the observation is a dictionary, I need to give it the policy. But when I run the code, I receive this error:
'tuple' object has no attribute 'items'
I don't know where this error comes from. Here is my setting 


    ray.init(local_mode=True)

    def env_creator(_):
        return AAM_Dispatch()
                
    single_env = AAM_Dispatch()
    env_name = "AAM_Dispatch"
    register_env(env_name, env_creator)

    obs_space = single_env.observation_space
    act_space = single_env.action_space
    num_agents = single_env.num_agents

    def gen_policy():
        return (DQNTFPolicy)

    policy_graphs = {
                "dqn_policy": (
                    gen_policy(),
                    obs_space,
                    act_space,
                    {},
                    ),
    }


    def policy_mapping_fn(agent_id, episode, worker, **kwargs):
        return "dqn_policy"


    dqn_config = (
        DQNConfig()
        .environment("AAM_Dispatch")
        .framework("tf")
        .rollouts(observation_filter="MeanStdFilter")
        .training(
            model={"vf_share_layers": True},
            n_step=3,
            gamma=0.99
        )
        .multi_agent(
            policies=policy_graphs,
            policy_mapping_fn=policy_mapping_fn,
            policies_to_train=["dqn_policy"],
        )

        .resources(num_gpus=int(os.environ.get("RLLIB_NUM_GPUS", "0")))
    )

    dqn = dqn_config.build()
    
    for i in range(2):
        result_dqn = dqn.train()
        print(pretty_print(result_dqn))
        if (result_dqn["episode_reward_mean"] > 48):
            print("ّFinish Training")
            quit(0)
