### ISSUE TITLE
[Bug] 404 when installing a Mac OS wheel

### ISSUE THREAD

**Issue by sijieamoy** [ray-project/ray#18838]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

My local and remote Ray versions mismatched:
```
...
(anyscale +0.2s) Using project dir /Users/sijie/Git/mnist-pytorch/
The 'pip' or 'conda' field was specified in the runtime env, so it may take some time to install the environment before Ray connects.
(anyscale +2m20.0s) Connection Failed! Attempting to get Debug Information!
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mnist/lib/python3.7/site-packages/anyscale/connect.py", line 1835, in _acquire_session_lock
    self._dynamic_check(info)
  File "/opt/miniconda3/envs/mnist/lib/python3.7/site-packages/anyscale/connect.py", line 2249, in _dynamic_check
    info["ray_commit"],
  File "/opt/miniconda3/envs/mnist/lib/python3.7/site-packages/anyscale/connect.py", line 2242, in _check_required_ray_version
    raise ValueError(msg)
ValueError: The local ray installation has commit d9b1662, but 8dd3057 is required.
Please install the required Ray version by running:
	`pip uninstall ray -y && pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/master/8dd30576442e5bdcfcd3b37f690a5eb87af9862b/ray-2.0.0.dev0-cp37-cp37m-macosx_10_13_intel.whl`
To unsafely ignore this check, set IGNORE_VERSION_CHECK=1.
```

Following the instruction, I tried to install the required wheel but got a 404:
```
(mnist) sijie@Sijies-MacBook-Pro-16-inch-2019 mnist-pytorch % pip uninstall ray -y && pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/master/8dd30576442e5bdcfcd3b37f690a5eb87af9862b/ray-2.0.0.dev0-cp37-cp37m-macosx_10_13_intel.whl
Found existing installation: ray 2.0.0.dev0
Uninstalling ray-2.0.0.dev0:
  Successfully uninstalled ray-2.0.0.dev0
Collecting ray==2.0.0.dev0
  ERROR: HTTP error 404 while getting https://s3-us-west-2.amazonaws.com/ray-wheels/master/8dd30576442e5bdcfcd3b37f690a5eb87af9862b/ray-2.0.0.dev0-cp37-cp37m-macosx_10_13_intel.whl
ERROR: Could not install requirement ray==2.0.0.dev0 from https://s3-us-west-2.amazonaws.com/ray-wheels/master/8dd30576442e5bdcfcd3b37f690a5eb87af9862b/ray-2.0.0.dev0-cp37-cp37m-macosx_10_13_intel.whl because of HTTP error 404 Client Error: Not Found for url: https://s3-us-west-2.amazonaws.com/ray-wheels/master/8dd30576442e5bdcfcd3b37f690a5eb87af9862b/ray-2.0.0.dev0-cp37-cp37m-macosx_10_13_intel.whl for URL https://s3-us-west-2.amazonaws.com/ray-wheels/master/8dd30576442e5bdcfcd3b37f690a5eb87af9862b/ray-2.0.0.dev0-cp37-cp37m-macosx_10_13_intel.whl
```

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by amogkam** [comment]
@sijieamoy the wheel URL link got updated. Can you use the most recent one from the docs?

**Comment by architkulkarni** [comment]
That's right, let me fix the URL in this error message.  We now have functions `get_master_wheel_url` and `get_release_wheel_url` that are tested in the nightlies, so we should be using those.

**Comment by architkulkarni** [comment]
This message isn't coming from OSS Ray, I've opened an issue here to track it https://github.com/anyscale/product/issues/7085
