### ISSUE TITLE
[Bug] Missing positional argument 'res' in serialization.py

### ISSUE THREAD

**Issue by jmugan** [ray-project/ray#18856]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

Running RLlib in tune randomly crashes with this stack trace

> 2021-09-23 07:39:58,514	ERROR serialization.py:256 -- __init__() missing 1 required positional argument: 'res'
Traceback (most recent call last):
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/ray/serialization.py", line 254, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/ray/serialization.py", line 213, in _deserialize_object
    return RayError.from_bytes(obj)
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/ray/exceptions.py", line 28, in from_bytes
    return pickle.loads(ray_exception.serialized_exception)
TypeError: __init__() missing 1 required positional argument: 'res'
2021-09-23 07:39:58,518	ERROR trial_runner.py:810 -- Trial PPO_RealGame_4568d_00000: Error processing event.
Traceback (most recent call last):
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 776, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 759, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/ray/worker.py", line 1626, in get
    raise value
ray.exceptions.RaySystemError: System error: __init__() missing 1 required positional argument: 'res'
traceback: Traceback (most recent call last):
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/ray/serialization.py", line 254, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/ray/serialization.py", line 213, in _deserialize_object
    return RayError.from_bytes(obj)
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/ray/exceptions.py", line 28, in from_bytes
    return pickle.loads(ray_exception.serialized_exception)
TypeError: __init__() missing 1 required positional argument: 'res'

### Reproduction script

I can't produce it on demand. I think what happens is the environment I'm using crashes in some situations, which seems to trigger this stack trace, which hides the reason for the crash.

### Anything else

I'm using the 2.0 from https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
@richardliaw have you ever seen this error before from Tune?

**Comment by sven1977** [comment]
Hey @jmugan , just a thought: Could you try running your script with `num_workers=0` such that the main learner would die if your env dies? This way, tune or RLlib would not try to recover the crashed worker and we would have a better chance at seeing the actual stack trace.

Also, what's your setting for the `ignore_worker_failures` config?
Could you post your entire config here?

**Comment by jmugan** [comment]
For the config, I just have `"ignore_worker_failures": True`

I'll run with num_workers=0 and see if I can get it to happen again.

**Comment by jmugan** [comment]
Here's the crash report 

> 2021-10-08 21:19:51,701	WARNING ray_trial_executor.py:743 -- Over the last 60 seconds, the Tune event loop has been backlogged processing new results. Consider increasing your period of result reporting to improve performance.
2021-10-08 21:19:51,703	ERROR trial_runner.py:810 -- Trial PPO_LoganRealGame_2bcf1_00000: Error processing event.
Traceback (most recent call last):
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 776, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 759, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/ray/worker.py", line 1624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ConnectionError): ray::PPO.train_buffered() (pid=35451, ip=10.0.10.31, repr=PPO)
  File "/home/jmugan/predictor/predictor/pysc2/lib/protocol.py", line 183, in _read
    response_str = self._sock.recv()
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/websocket/_core.py", line 313, in recv
    opcode, data = self.recv_data()
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/websocket/_core.py", line 330, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/websocket/_core.py", line 343, in recv_data_frame
    frame = self.recv_frame()
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/websocket/_core.py", line 377, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/websocket/_core.py", line 452, in _recv
    return recv(self.sock, bufsize)
  File "/home/jmugan/anaconda3/envs/3point7/lib/python3.7/site-packages/websocket/_socket.py", line 115, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
