### ISSUE TITLE
[Serve] [runtime env] [Bug] Serve does not work with runtime env

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#18865]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

Hangs with error:

```python-traceback
Traceback (most recent call last):
  File "/Users/archit/ray/python/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 141, in CreateRuntimeEnv
    serialized_env)
  File "/Users/archit/ray/python/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 104, in _setup_runtime_env
    return await loop.run_in_executor(None, run_setup_with_logger)
  File "/Users/archit/anaconda3/envs/ray-py36/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/archit/ray/python/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 97, in run_setup_with_logger
    for uri in runtime_env.get("uris", []):
TypeError: 'NoneType' object is not iterable
```

### Reproduction script

```python
import requests
from ray import serve
import requests

serve.start()


@serve.deployment
def requests_version(request):
    return requests.__version__


requests_version.options(
    ray_actor_options={
        "runtime_env": {
            "pip": ["ray[serve]", "requests==2.25.1"]
        }
    }).deploy()

print (requests.get("http://127.0.0.1:8000/requests_version").text)
```
### Anything else

Happens on master and 1.7.0rc0, but works fine on 1.6.0

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment]
cc @simon-mo @edoakes should we cherry pick a fix for this?

**Comment by simon-mo** [comment]
Looks like this can error with just generic runtime env with uris=None?
