### ISSUE TITLE
fail to run custom_env.py

### ISSUE THREAD

**Issue by Emily0219** [ray-project/ray#1886]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **Ray installed from (source or binary)**: pip install ray
- **Ray version**: 0.3.1
- **Python version**: 2.7.12
- **Exact command to reproduce**: 

### Describe the problem

I just ran the custom_env.py which describes the simple corridor but there was a bug as follows. I don't know how to solve it. I hope for your help. Thank you very much!
### Source code / logs

Traceback (most recent call last):
  File "/home/h/ray-master/examples/custom_env/custom_env.py", line 54, in <module>
    "corridor_length": 5,
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/tune/tune.py", line 63, in run_experiments
    raise TuneError("Trial did not complete", trial)
ray.tune.error.TuneError: ('Trial did not complete', PPO_corridor_0)

**Comment by ericl** [comment]
Could you include the full error printed earlier in the console?

**Comment by Emily0219** [comment]
I'm sorry about my layout and I am a novice at github. There is the whole information in the console as follows. Thank you.


/home/h/.virtualenvs/ros_gazebo/bin/python2.7 /home/h/ray/examples/custom_env/custom_env.py
Waiting for redis server at 127.0.0.1:36916 to respond...
Waiting for redis server at 127.0.0.1:38375 to respond...
Allowing the Plasma store to use up to 1.73105GB of memory.
Starting object store with directory /dev/shm and huge page support disabled
Starting local scheduler with the following resources: {'GPU': 0, 'CPU': 4}.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui29254.ipynb?token=f69e1ba8ee32de6ee7da3ce60b8264f6c70ec9be29b4056d
======================================================================

== Status ==
Using FIFO scheduling algorithm.
Result logdir: /home/h/ray_results/demo
PENDING trials:
 - PPO_corridor_0:	PENDING

WARNING: Serializing objects of type <class 'ray.tune.registry._Registry'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
== Status ==
Using FIFO scheduling algorithm.
Resources used: 1/4 CPUs, 0/0 GPUs
Result logdir: /home/h/ray_results/demo
RUNNING trials:
 - PPO_corridor_0:	RUNNING

Observation shape is (1,)
Not using any observation preprocessor.
WARN: gym.spaces.Box autodetected dtype as <type 'numpy.float32'>. Please provide explicit dtype.
Constructing fcnet [256, 256] <function tanh at 0x7f24cb241d70>
Constructing fcnet [256, 256] <function tanh at 0x7f24cb241d70>
WARNING:tensorflow:From /home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/models/action_dist.py:54: calling reduce_max (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/models/action_dist.py:59: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Constructing fcnet [256, 256] <function tanh at 0x7f24cb241d70>
Constructing fcnet [256, 256] <function tanh at 0x7f24cb241d70>
Constructing fcnet [256, 256] <function tanh at 0x7f24cb241d70>
Constructing fcnet [256, 256] <function tanh at 0x7f24cb241d70>
Constructing fcnet [256, 256] <function tanh at 0x7f24cb241d70>
Constructing fcnet [256, 256] <function tanh at 0x7f24cb241d70>
Constructing fcnet [256, 256] <function tanh at 0x7f24cb241d70>
Constructing fcnet [256, 256] <function tanh at 0x7f24cb241d70>
===> iteration 0
Observation shape is (1,)
Not using any observation preprocessor.
WARN: gym.spaces.Box autodetected dtype as <type 'numpy.float32'>. Please provide explicit dtype.
Constructing fcnet [256, 256] <function tanh at 0x7fde5db4f8c0>
Observation shape is (1,)
Not using any observation preprocessor.
WARN: gym.spaces.Box autodetected dtype as <type 'numpy.float32'>. Please provide explicit dtype.
Constructing fcnet [256, 256] <function tanh at 0x7f4656fe98c0>
Constructing fcnet [256, 256] <function tanh at 0x7fde5db4f8c0>
Constructing fcnet [256, 256] <function tanh at 0x7f4656fe98c0>
Observation shape is (1,)
Not using any observation preprocessor.
WARN: gym.spaces.Box autodetected dtype as <type 'numpy.float32'>. Please provide explicit dtype.
Constructing fcnet [256, 256] <function tanh at 0x7f3b78c8f8c0>
Constructing fcnet [256, 256] <function tanh at 0x7f3b78c8f8c0>
WARNING:tensorflow:From /home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/models/action_dist.py:54: calling reduce_max (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/models/action_dist.py:59: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/models/action_dist.py:54: calling reduce_max (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/models/action_dist.py:59: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Constructing fcnet [256, 256] <function tanh at 0x7fde5db4f8c0>
Constructing fcnet [256, 256] <function tanh at 0x7f4656fe98c0>
Constructing fcnet [256, 256] <function tanh at 0x7fde5db4f8c0>
Constructing fcnet [256, 256] <function tanh at 0x7f4656fe98c0>
WARNING:tensorflow:From /home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/models/action_dist.py:54: calling reduce_max (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/models/action_dist.py:59: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Constructing fcnet [256, 256] <function tanh at 0x7f3b78c8f8c0>
Constructing fcnet [256, 256] <function tanh at 0x7f3b78c8f8c0>
Observation shape is (1,)
Not using any observation preprocessor.
WARN: gym.spaces.Box autodetected dtype as <type 'numpy.float32'>. Please provide explicit dtype.
Constructing fcnet [256, 256] <function tanh at 0x7f1f15c908c0>
Constructing fcnet [256, 256] <function tanh at 0x7f1f15c908c0>
```
Remote function sample failed with:

Traceback (most recent call last):
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/worker.py", line 770, in _process_task
    *arguments)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/actor.py", line 162, in actor_method_executor
    return method(actor, *args)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/ppo/ppo_evaluator.py", line 192, in sample
    rollout = self.sampler.get_data()
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/utils/sampler.py", line 88, in get_data
    item = next(self.rollout_provider)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/utils/sampler.py", line 197, in _env_runner
    last_observation = obs_filter(env.reset())
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/gym/core.py", line 317, in reset
    observation = self.env.reset(**kwargs)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/gym/core.py", line 71, in reset
    raise NotImplementedError
NotImplementedError

```

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:36916")
  
Observation shape is (1,)
Not using any observation preprocessor.
WARN: gym.spaces.Box autodetected dtype as <type 'numpy.float32'>. Please provide explicit dtype.
Constructing fcnet [256, 256] <function tanh at 0x7f23e9ee08c0>
Remote function sample failed with:

Traceback (most recent call last):
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/worker.py", line 770, in _process_task
    *arguments)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/actor.py", line 162, in actor_method_executor
    return method(actor, *args)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/ppo/ppo_evaluator.py", line 192, in sample
    rollout = self.sampler.get_data()
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/utils/sampler.py", line 88, in get_data
    item = next(self.rollout_provider)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/utils/sampler.py", line 197, in _env_runner
    last_observation = obs_filter(env.reset())
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/gym/core.py", line 317, in reset
    observation = self.env.reset(**kwargs)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/gym/core.py", line 71, in reset
    raise NotImplementedError
NotImplementedError


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:36916")
  
Remote function sample failed with:

Traceback (most recent call last):
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/worker.py", line 770, in _process_task
    *arguments)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/actor.py", line 162, in actor_method_executor
    return method(actor, *args)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/ppo/ppo_evaluator.py", line 192, in sample
    rollout = self.sampler.get_data()
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/utils/sampler.py", line 88, in get_data
    item = next(self.rollout_provider)
StopIteration


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:36916")
  
Error processing event: Traceback (most recent call last):
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/tune/trial_runner.py", line 216, in _process_events
    result = ray.get(result_id)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/worker.py", line 2253, in get
    raise RayGetError(object_ids, value)
RayGetError: Could not get objectid ObjectID(ff089df674e93055ae731e6102c7f58a95d12a83). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/worker.py", line 770, in _process_task
    *arguments)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/actor.py", line 162, in actor_method_executor
    return method(actor, *args)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/tune/trainable.py", line 107, in train
    result = self._train()
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/ppo/ppo.py", line 124, in _train
    samples = collect_samples(agents, config, self.local_evaluator)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/ppo/rollout.py", line 31, in collect_samples
    next_sample = ray.get(fut_sample)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/worker.py", line 2253, in get
    raise RayGetError(object_ids, value)
RayGetError: Could not get objectid ObjectID(8f1dc3a70eae3c21321dba4b1ea4ece5ca4c1078). It was created by remote function sample which failed with:

Remote function sample failed with:

Traceback (most recent call last):
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/worker.py", line 770, in _process_task
    *arguments)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/actor.py", line 162, in actor_method_executor
    return method(actor, *args)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/ppo/ppo_evaluator.py", line 192, in sample
    rollout = self.sampler.get_data()
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/utils/sampler.py", line 88, in get_data
    item = next(self.rollout_provider)
StopIteration



Remote function train failed with:

Traceback (most recent call last):
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/worker.py", line 770, in _process_task
    *arguments)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/actor.py", line 162, in actor_method_executor
    return method(actor, *args)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/tune/trainable.py", line 107, in train
    result = self._train()
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/ppo/ppo.py", line 124, in _train
    samples = collect_samples(agents, config, self.local_evaluator)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/ppo/rollout.py", line 31, in collect_samples
    next_sample = ray.get(fut_sample)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/worker.py", line 2253, in get
    raise RayGetError(object_ids, value)
RayGetError: Could not get objectid ObjectID(8f1dc3a70eae3c21321dba4b1ea4ece5ca4c1078). It was created by remote function sample which failed with:

Remote function sample failed with:

Traceback (most recent call last):
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/worker.py", line 770, in _process_task
    *arguments)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/actor.py", line 162, in actor_method_executor
    return method(actor, *args)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/ppo/ppo_evaluator.py", line 192, in sample
    rollout = self.sampler.get_data()
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/utils/sampler.py", line 88, in get_data
    item = next(self.rollout_provider)
StopIteration



  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:36916")
  
Disconnecting client on fd 17
Constructing fcnet [256, 256] <function tanh at 0x7f23e9ee08c0>
Remote function sample failed with:

Traceback (most recent call last):
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/worker.py", line 770, in _process_task
    *arguments)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/actor.py", line 162, in actor_method_executor
    return method(actor, *args)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/ppo/ppo_evaluator.py", line 192, in sample
    rollout = self.sampler.get_data()
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/utils/sampler.py", line 88, in get_data
    item = next(self.rollout_provider)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/utils/sampler.py", line 197, in _env_runner
    last_observation = obs_filter(env.reset())
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/gym/core.py", line 317, in reset
    observation = self.env.reset(**kwargs)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/gym/core.py", line 71, in reset
    raise NotImplementedError
NotImplementedError


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:36916")
  
```
WARNING:tensorflow:From /home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/models/action_dist.py:54: calling reduce_max (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "/home/h/ray/examples/custom_env/custom_env.py", line 54, in <module>
    "corridor_length": 5,
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/tune/tune.py", line 63, in run_experiments
    raise TuneError("Trial did not complete", trial)
ray.tune.error.TuneError: ('Trial did not complete', PPO_corridor_0)
Disconnecting client on fd 11
INFO:root:message-handler: driver_removed_handler
INFO:root:Driver 5db77bd760470f3558b058545d0fd09645cb2733 has been removed.
```
== Status ==
Using FIFO scheduling algorithm.
Resources used: 0/4 CPUs, 0/0 GPUs
Result logdir: /home/h/ray_results/demo
ERROR trials:
 - PPO_corridor_0:	ERROR => /home/h/ray_results/demo/PPO_corridor_0_2018-04-13_13-36-02Mh_4tv/error_2018-04-13_13-36-10.txt

== Status ==
Using FIFO scheduling algorithm.
Resources used: 0/4 CPUs, 0/0 GPUs
Result logdir: /home/h/ray_results/demo
ERROR trials:
 - PPO_corridor_0:	ERROR => /home/h/ray_results/demo/PPO_corridor_0_2018-04-13_13-36-02Mh_4tv/error_2018-04-13_13-36-10.txt

```
WARNING:tensorflow:From /home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/rllib/models/action_dist.py:59: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Disconnecting client on fd 21
Disconnecting client on fd 22
Disconnecting client on fd 15
Disconnecting client on fd 14
Disconnecting client on fd 13
Disconnecting client on fd 12
[WARN] (/ray/src/local_scheduler/local_scheduler_client.cc:119) Exiting because local scheduler closed connection.
[WARN] (/ray/src/local_scheduler/local_scheduler_client.cc:119) Exiting because local scheduler closed connection.
[WARN] (/ray/src/local_scheduler/local_scheduler_client.cc:119) Exiting because local scheduler closed connection.
[WARN] (/ray/src/global_scheduler/global_scheduler.cc:412) Missed too many heartbeats from local scheduler, marking as dead.
Disconnecting client on fd 7
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/h/.virtualenvs/ros_gazebo/local/lib/python2.7/site-packages/ray/worker.py", line 1736, in import_thread
    except redis.ConnectionError:
AttributeError: 'NoneType' object has no attribute 'ConnectionError'

```

Process finished with exit code 1

**Comment by ericl** [comment]
@Emily0219 this should be fixed in https://github.com/ray-project/ray/pull/1896
