### ISSUE TITLE
[runtime env] [Bug] Pickle error when using local dev mode flag

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#18875]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

When using the pip/conda field of runtime environments, the current Ray wheel is downloaded into an isolated conda environment for the worker.  But when developing and building from source, it's inconvenient to build a Ray wheel each time you want to test.  The flag `RAY_RUNTIME_ENV_LOCAL_DEV_MODE=1` was developed to allow for testing runtime_env in this case, by magically linking to the Python site for the currently running Ray installation.  This flag seems to have stopped working on master, raising a pickle protocol error:

```
(pid=71769) 2021-09-23 22:44:42,572     ERROR serialization.py:270 -- unsupported pickle protocol: 5
(pid=71769) Traceback (most recent call last):
(pid=71769)   File "/Users/archit/ray/python/ray/serialization.py", line 268, in deserialize_objects
(pid=71769)     obj = self._deserialize_object(data, metadata, object_ref)
(pid=71769)   File "/Users/archit/ray/python/ray/serialization.py", line 191, in _deserialize_object
(pid=71769)     return self._deserialize_msgpack_data(data, metadata_fields)
(pid=71769)   File "/Users/archit/ray/python/ray/serialization.py", line 169, in _deserialize_msgpack_data
(pid=71769)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(pid=71769)   File "/Users/archit/ray/python/ray/serialization.py", line 159, in _deserialize_pickle5_data
(pid=71769)     obj = pickle.loads(in_band)
(pid=71769) ValueError: unsupported pickle protocol: 5
```

### Reproduction script

```shell
RAY_RUNTIME_ENV_LOCAL_DEV_MODE=1 python repro.py
```

```python
# repro.py
import requests
import ray

ray.init()

@ray.remote
def f():
    return requests.__version__

print(ray.get(f.options(runtime_env={"pip": ["requests==2.25.1"]}).remote()))
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment]
cc @simon-mo anything jump out at you with this error message?  Could it just be something wrong with my environment?

**Comment by architkulkarni** [comment]
Seems to be fixed by creating a new conda env with Python 3.8.

**Comment by architkulkarni** [comment]
I'll check with a new conda env with Python 3.6 and open an enhancement request if it doesn't work with 3.6
