### ISSUE TITLE
[Bug] [tune] Tune hangs (Tune event loop has been backlogged processing new results)

### ISSUE THREAD

**Issue by jmakov** [ray-project/ray#18903]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

Tune hangs (about 2 CPUs are utilized on the cluster of 52 CPUs). ray monitor reports all CPUs are in use. 

```shell
2021-09-26 23:12:54,064 WARNING ray_trial_executor.py:730 -- Over the last 60 seconds, the Tune event loop has been backlogged processing new results. Consider increasing your period of result reporting to improve performance.
```

### Reproduction script

```python
import ray
from ray import tune
from ray.tune.suggest import optuna


def evaluation_fn(step, width, height):
    return (0.1 + width * step / 100)**(-1) + height * 0.1


def easy_objective(config):
    width, height = config["width"], config["height"]

    for step in range(config["steps"]):
        # Iterative training function - can be any arbitrary training procedure
        intermediate_score = evaluation_fn(step, width, height)
        # Feed the score back back to Tune.
        tune.report(iterations=step, mean_loss=intermediate_score)


if __name__ == "__main__":
    ray.init(address='auto', _redis_password='5241590000000000')  # connect to head node in cluster
    
    analysis = tune.run(
        easy_objective,
        name="test",
        metric="mean_loss",
        mode="min",
        num_samples=-1,
        verbose=1,
        time_budget_s=3600*24*30,
        fail_fast=True,
        reuse_actors=True,
        config={
            "steps": 100,
            "width": tune.uniform(0, 20000),
            "height": tune.uniform(-100, 100000)
        }
    )
```

### Anything else

The script above runs _really_ slow considering how fast `easy_objective` is calculated: about 20 trials per 20s on a 52 CPU cluster.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by krfricke** [comment]
Which version of Ray are you using?

On my laptop (16 vCPU) the script above runs about 5 samples/second.

You can speed this up drastically if you disable logging (~50samples/second on my laptop):

```
    os.environ["TUNE_DISABLE_AUTO_CALLBACK_LOGGERS"] = "1"
```

on your cluster you might want to disable syncing as well:

```
    os.environ["TUNE_DISABLE_AUTO_CALLBACK_SYNCER"] = "1"
```

**Comment by jmakov** [comment]
ray 1.6.0. Thanks, will try that out.

**Comment by jmakov** [comment]
The warning is still there, ray monitor still shows 52/52 CPUs in use whereas only 8 CPUs are used on the whole cluster.

**Comment by jmakov** [comment]
@krfricke after running with 4-8CPUs on the cluster my script exits with:
```python
2021-09-27 19:54:40,066 ERROR trial_runner.py:773 -- Trial trainable_c64c9714: Error processing event.
Traceback (most recent call last):
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 747, in _process_trial
    decision = self._process_trial_result(trial, result)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 800, in _process_trial_result
    trial.trial_id, result=flat_result)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/ray/tune/suggest/search_generator.py", line 130, in on_trial_complete
    trial_id=trial_id, result=result, error=error)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/ray/tune/suggest/optuna.py", line 385, in on_trial_complete
    self._ot_study.tell(ot_trial, val, state=ot_trial_state)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/optuna/study/study.py", line 662, in tell
    self._storage.set_trial_values(trial_id, values)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/optuna/storages/_in_memory.py", line 330, in set_trial_values
    self.check_trial_is_updatable(trial_id, trial.state)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/optuna/storages/_base.py", line 723, in check_trial_is_updatable
    "Trial#{} has already finished and can not be updated.".format(trial.number)
RuntimeError: Trial#23202 has already finished and can not be updated.
Traceback (most recent call last):
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 747, in _process_trial
    decision = self._process_trial_result(trial, result)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 800, in _process_trial_result
    trial.trial_id, result=flat_result)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/ray/tune/suggest/search_generator.py", line 130, in on_trial_complete
    trial_id=trial_id, result=result, error=error)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/ray/tune/suggest/optuna.py", line 385, in on_trial_complete
    self._ot_study.tell(ot_trial, val, state=ot_trial_state)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/optuna/study/study.py", line 662, in tell
    self._storage.set_trial_values(trial_id, values)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/optuna/storages/_in_memory.py", line 330, in set_trial_values
    self.check_trial_is_updatable(trial_id, trial.state)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/optuna/storages/_base.py", line 723, in check_trial_is_updatable
    "Trial#{} has already finished and can not be updated.".format(trial.number)
RuntimeError: Trial#23202 has already finished and can not be updated.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "notebooks/factor/price_prediction.py", line 163, in <module>
    reuse_actors=True
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/ray/tune/tune.py", line 532, in run
    runner.step()
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 554, in step
    self._process_events(timeout=timeout)  # blocking
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 712, in _process_events
    self._process_trial(trial)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 774, in _process_trial
    self._process_trial_failure(trial, traceback.format_exc())
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 985, in _process_trial_failure
    self._search_alg.on_trial_complete(trial.trial_id, error=True)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/ray/tune/suggest/search_generator.py", line 130, in on_trial_complete
    trial_id=trial_id, result=result, error=error)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/ray/tune/suggest/optuna.py", line 385, in on_trial_complete
    self._ot_study.tell(ot_trial, val, state=ot_trial_state)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/optuna/study/study.py", line 664, in tell
    self._storage.set_trial_state(trial_id, state)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/optuna/storages/_in_memory.py", line 223, in set_trial_state
    self.check_trial_is_updatable(trial_id, trial.state)
  File "/home/toaster/PROGS/miniconda3/envs/puma-lab/lib/python3.7/site-packages/optuna/storages/_base.py", line 723, in check_trial_is_updatable
    "Trial#{} has already finished and can not be updated.".format(trial.number)
RuntimeError: Trial#23202 has already finished and can not be updated.
```
I assume this is a connected, not separate issue.

**Comment by jmakov** [comment]
@krfricke @Yard1 do you need any other info from me?

**Comment by Yard1** [comment]
This is due to Optuna itself being backlogged by the number of results. Unfortunately, this is not something we can influence. With such a large number of trials, the underlying model requires a non-trivial amount of time to suggest new points. I'd consider using simple random search through Tune's `BasicVariantGenerator` as that will return a new suggestion in a constant time, no matter the amount of trials.

Let me know if this helps! Feel free to reopen the issue in case of more questions.
