### ISSUE TITLE
[Core] [Bug] head noded exited because of monitor process exited

### ISSUE THREAD

**Issue by sjxAndy** [ray-project/ray#18918]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

when i'm using `ray start` command to start ray head node on a slurm partition, after a while it will report that a subprocess called monitor failed. 

Here is the command I used:

```
srun -p pat_scorpio ray start --head --port=0 --block -v --include-dashboard false --ray-client-server-port=46015
```

and i get ouput:
```
2021-09-27 17:35:47,339 INFO cli.py:595 -- Local node IP: 10.198.6.86
2021-09-27 17:35:52,390 SUCC cli.py:623 -- --------------------
2021-09-27 17:35:52,390 SUCC cli.py:624 -- Ray runtime started.
2021-09-27 17:35:52,390 SUCC cli.py:625 -- --------------------
2021-09-27 17:35:52,390 INFO cli.py:627 -- Next steps
2021-09-27 17:35:52,390 INFO cli.py:629 -- To connect to this Ray runtime from another node, run
2021-09-27 17:35:52,390 INFO cli.py:635 --   ray start --address='10.198.6.86:47277' --redis-password='5241590000000000'
2021-09-27 17:35:52,390 INFO cli.py:637 -- Alternatively, use the following Python code:
2021-09-27 17:35:52,391 INFO cli.py:640 -- import ray
2021-09-27 17:35:52,391 INFO cli.py:647 -- ray.init(address='auto', _redis_password='5241590000000000')
2021-09-27 17:35:52,391 INFO cli.py:650 -- If connection fails, check your firewall settings and network configuration.
2021-09-27 17:35:52,391 INFO cli.py:654 -- To terminate the Ray runtime, run
2021-09-27 17:35:52,391 INFO cli.py:655 --   ray stop
2021-09-27 17:35:52,391 INFO cli.py:724 -- --block
2021-09-27 17:35:52,391 INFO cli.py:726 -- This command will now block until terminated by a signal.
2021-09-27 17:35:52,391 INFO cli.py:728 -- Running subprocesses are monitored and a message will be printed if any of them terminate unexpectedly.
2021-09-27 17:42:12,342 ERR cli.py:804 -- Some Ray subprcesses exited unexpectedly:
2021-09-27 17:42:12,343 ERR cli.py:811 -- monitor [exit code=1]
2021-09-27 17:42:12,343 ERR cli.py:815 -- Remaining processes will be killed.
srun: error: SH-IDC1-10-198-6-86: task 0: Exited with exit code 1
```
I also looked at the log in monitor.err:
```
Traceback (most recent call last):
  File "/mnt/lustre/sunjixiang/.local.pat20210923/lib/python3.6/site-packages/ray/autoscaler/_private/monitor.py", line 416, in <module>
    monitor.run()
  File "/mnt/lustre/sunjixiang/.local.pat20210923/lib/python3.6/site-packages/ray/autoscaler/_private/monitor.py", line 317, in run
    self._run()
  File "/mnt/lustre/sunjixiang/.local.pat20210923/lib/python3.6/site-packages/ray/autoscaler/_private/monitor.py", line 207, in _run
    self.update_load_metrics()
  File "/mnt/lustre/sunjixiang/.local.pat20210923/lib/python3.6/site-packages/ray/autoscaler/_private/monitor.py", line 170, in update_load_metrics
    request, timeout=4)
  File "/mnt/lustre/share/platform/env/miniconda3.6_86/envs/pat20210923/lib/python3.6/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/mnt/lustre/share/platform/env/miniconda3.6_86/envs/pat20210923/lib/python3.6/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1632735728.009627562","description":"Error received from peer ipv4:10.198.6.86:40219","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
Exception ignored in: <bound method Monitor.__del__ of <__main__.Monitor object at 0x7f47360104a8>>
Traceback (most recent call last):
  File "/mnt/lustre/sunjixiang/.local.pat20210923/lib/python3.6/site-packages/ray/autoscaler/_private/monitor.py", line 154, in __del__
TypeError: 'NoneType' object is not callable
```

### Reproduction script

I used the following command to run on a slurm partition, and got the error above.
```
srun -p pat_scorpio ray start --head --port=0 --block -v --include-dashboard false --ray-client-server-port=46015
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by JakkuSakura** [comment]
Is it fixed? I tried running ray in containers but it failed like this
