### ISSUE TITLE
AttributeError: module 'ray.tune' has no attribute 'with_parameters'

### ISSUE THREAD

**Issue by pratikchhapolika** [ray-project/ray#18912]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

I am using `ray` with `pytorch-lightning ` to sarch for parameters over my search space. 
I get the error as :

`AttributeError: module 'ray.tune' has no attribute 'with_parameters'`

I have pasted the code below:

### Reproduction script

```
def train_SR_tune(num_epochs=5, num_gpus=1):
    
    
    trainer = pl.Trainer(logger=logger,
          callbacks=[TuneReportCallback(
                {
                    "loss": "ptl/val_loss",
                    "mean_accuracy": "ptl/val_accuracy"
                },
                on="validation_end"),
              early_stopping_callback],
          max_epochs=num_epochs,
          gpus=num_gpus,
         progress_bar_refresh_rate=200,
         amp_level='O3'

  )
    
    
    trainer.fit(model)

def tune_SR_asha(num_samples=10, num_epochs=5, gpus_per_trial=1):
    config = {
        
        "lr": tune.loguniform(1e-4, 1e-1),
        "batch_size": tune.choice([8,10,12,16]),
    }

    scheduler = ASHAScheduler(max_t=num_epochs,grace_period=1,reduction_factor=2)

    reporter = CLIReporter(
        parameter_columns=[ "lr", "batch_size"],
        metric_columns=["loss", "mean_accuracy", "training_iteration"])

    analysis = tune.run(tune.with_parameters(train_SR_tune,num_epochs=num_epochs,num_gpus=gpus_per_trial),
        resources_per_trial={
            "cpu": 1,
            "gpu": gpus_per_trial
        },
        metric="loss",
        mode="min",
        config=config,
        num_samples=num_samples,
        scheduler=scheduler,
        progress_reporter=reporter,
        name="tune_mnist_asha")

    print("Best hyperparameters found were: ", analysis.best_config)
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by krfricke** [comment]
Which version of Ray are you using? (`ray --version`)

The import works fine for me, so it's likely that you either a) have an outdated Ray version installed or b) have a file called `tune.py` or so that might interfere with the imports.

**Comment by pratikchhapolika** [comment]
> Which version of Ray are you using? (`ray --version`)
> 
> The import works fine for me, so it's likely that you either a) have an outdated Ray version installed or b) have a file called `tune.py` or so that might interfere with the imports.

@krfricke I don't have any file named as `tune.py` `ray version: 1.0.0`

**Comment by pratikchhapolika** [comment]
Done. It was version error. 

However after running the loops keeps running and I get these error:



```
2021-09-27 01:55:43,993	INFO services.py:1265 -- View the Ray dashboard at http://127.0.0.1:8265
2021-09-27 01:55:43,996	WARNING services.py:1759 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2021-09-27 01:55:45,592	WARNING function_runner.py:559 -- Function checkpointing is disabled. This may result in unexpected behavior when using checkpointing features or certain schedulers. To enable, set the train function arguments to be `func(config, checkpoint_dir=None)`.
2021-09-27 01:56:34,872	ERROR ray_trial_executor.py:581 -- Trial train_SR_tune_b6859_00000: Unexpected error starting runner.
Traceback (most recent call last):
  File "/home/pc/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 571, in start_trial
    return self._start_trial(trial, checkpoint, train=train)
  File "/home/pc/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 450, in _start_trial
    runner = self._setup_remote_runner(trial)
  File "/home/pc/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 367, in _setup_remote_runner
    return full_actor_class.remote(**kwargs)
  File "/home/pc/.local/lib/python3.6/site-packages/ray/actor.py", line 488, in remote
    override_environment_variables))
  File "/home/pc/.local/lib/python3.6/site-packages/ray/util/tracing/tracing_helper.py", line 366, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/home/pc/.local/lib/python3.6/site-packages/ray/actor.py", line 705, in _remote
    meta.method_meta.methods.keys())
  File "/home/pc/.local/lib/python3.6/site-packages/ray/_private/function_manager.py", line 372, in export_actor_class
    self._worker)
  File "/home/pc/.local/lib/python3.6/site-packages/ray/_private/utils.py", line 635, in check_oversized_function
    raise ValueError(error)
ValueError: The actor ImplicitFunc is too large (418 MiB > FUNCTION_SIZE_ERROR_THRESHOLD=95 MiB). Check that its definition is not implicitly capturing a large array or other object in scope. Tip: use ray.put() to put large objects in the Ray object store.
2021-09-27 01:56:36,944	WARNING util.py:164 -- The `start_trial` operation took 7.611 s, which may be a performance bottleneck.
== Status ==
Memory usage on this node: 124.6/1007.3 GiB
Using AsyncHyperBand: num_stopped=0
Bracket: Iter 2.000: None | Iter 1.000: None
Resources requested: 1.0/1 CPUs, 1.0/2 GPUs, 0.0/984.99 GiB heap, 0.0/9.31 GiB objects (0.0/1.0 accelerator_type:V100)
Result logdir: /home/pc/ray_results/tune_mnist_asha
Number of trials: 10/10 (1 ERROR, 9 PENDING)
+---------------------------+----------+-------+-------------+--------------+
| Trial name                | status   | loc   |          lr |   batch_size |
|---------------------------+----------+-------+-------------+--------------|
| train_SR_tune_b6859_00001 | PENDING  |       | 0.000128041 |           12 |
| train_SR_tune_b6859_00002 | PENDING  |       | 0.00882142  |           10 |
| train_SR_tune_b6859_00003 | PENDING  |       | 0.0533976   |           12 |
| train_SR_tune_b6859_00004 | PENDING  |       | 0.00238659  |           16 |
| train_SR_tune_b6859_00005 | PENDING  |       | 0.00692817  |           12 |
| train_SR_tune_b6859_00006 | PENDING  |       | 0.0922029   |           10 |
| train_SR_tune_b6859_00007 | PENDING  |       | 0.0336535   |            8 |
| train_SR_tune_b6859_00008 | PENDING  |       | 0.000112247 |           16 |
| train_SR_tune_b6859_00009 | PENDING  |       | 0.0107285   |           12 |
| train_SR_tune_b6859_00000 | ERROR    |       | 0.00647855  |            8 |
+---------------------------+----------+-------+-------------+--------------+
Number of errored trials: 1
+---------------------------+--------------+-----------------------------------------------------------------------------------------------------------------------------------+
| Trial name                |   # failures | error file                                                                                                                        |
|---------------------------+--------------+-----------------------------------------------------------------------------------------------------------------------------------|
| train_SR_tune_b6859_00000 |            1 | /home/pc/ray_results/tune_mnist_asha/train_SR_tune_b6859_00000_0_batch_size=8,lr=0.0064785_2021-09-27_01-56-29/error.txt |
+---------------------------+--------------+-----------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by krfricke** [comment]
It seems you defined your `model` outside the training function.

If that's the case, you might want to pass it to the `tune.with_parameters` arguments as well and accept it as an argument in the training function.

To elaborate on this, if you catch `model` from the outer scope, it will be pickled with the training function and might exceed the function size. If you pass it to `tune.with_parameter` it will be pickled once, but passed as an argument (and can be re-used by the other trials) - thus the function itself will be a thin wrapper and the model object is managed by the object store instead.

**Comment by pratikchhapolika** [comment]
> It seems you defined your `model` outside the training function.
> 
> If that's the case, you might want to pass it to the `tune.with_parameters` arguments as well and accept it as an argument in the training function.
> 
> To elaborate on this, if you catch `model` from the outer scope, it will be pickled with the training function and might exceed the function size. If you pass it to `tune.with_parameter` it will be pickled once, but passed as an argument (and can be re-used by the other trials) - thus the function itself will be a thin wrapper and the model object is managed by the object store instead.

@krfricke  **I have pasted the model above** Can you suggest me now what to change.,

**Comment by pratikchhapolika** [comment]
@krfricke Any help?

**Comment by krfricke** [comment]
Your trainable function has to accept a `config` parameter:

```
def train_SR_tune(config, num_epochs=2, num_gpus=1):
```

(and you should probably use those config values somewhere)
