### ISSUE TITLE
[Tune] tune not runnable outside of main thread

### ISSUE THREAD

**Issue by import-antigravity** [ray-project/ray#18920]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

I need to run Ray Tune jobs as threads, but it seems that an exception is thrown whenever `tune.run()` is called outside the main thread:

```
Traceback (most recent call last):
  File ".../lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "test_tune.py", line 134, in run
    tune_mnist(num_samples=100, num_epochs=100)
  File "test_tune.py", line 120, in tune_mnist
    analysis = tune.run(
  File ".../lib/python3.8/site-packages/ray/tune/tune.py", line 528, in run
    signal.signal(signal.SIGINT, sigint_handler)
  File ".../lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

### Reproduction script

```python
# test_tune.py

import logging
import os
from threading import Thread

import pytorch_lightning as pl
import ray
import torch
import torchvision
from pytorch_lightning import LightningDataModule
from ray import tune
from ray_lightning import RayPlugin
from ray_lightning.tune import get_tune_ddp_resources, TuneReportCallback
from torch.nn import functional as F
from torchvision import transforms

DATA_DIR = os.path.abspath('data')

GPU = False
if torch.cuda.is_available():
    GPU = True

print('GPU', GPU)

NUM_WORKERS = 1


def disable_slurm():
    os.environ["SLURM_JOB_NAME"] = "bash"


def mnist(root: str, normalize: bool = False):
    tlist = [transforms.ToTensor()]

    if normalize:
        tlist.append(transforms.Normalize((0.5,), (0.5,)))

    transform = transforms.Compose(tlist)

    trainset = torchvision.datasets.MNIST(root=root, train=True, download=True, transform=transform)
    testset = torchvision.datasets.MNIST(root=root, train=False, download=True, transform=transform)
    return trainset, testset


def mnist_datamodule(data_path: str, batch_size: int, num_workers: int) -> LightningDataModule:
    train, val = mnist(data_path, normalize=True)
    return LightningDataModule.from_datasets(train, val, None, batch_size=batch_size, num_workers=num_workers)


class LightningMNISTClassifier(pl.LightningModule):
    def __init__(self, config, data_dir=None):
        super(LightningMNISTClassifier, self).__init__()

        self.data_dir = data_dir or os.getcwd()
        self.lr = config["lr"]
        layer_1, layer_2 = config["layer_1"], config["layer_2"]
        self.batch_size = config["batch_size"]

        # mnist images are (1, 28, 28) (channels, width, height)
        self.layer_1 = torch.nn.Linear(28 * 28, layer_1)
        self.layer_2 = torch.nn.Linear(layer_1, layer_2)
        self.layer_3 = torch.nn.Linear(layer_2, 10)
        self.accuracy = pl.metrics.Accuracy()

    def forward(self, x):
        batch_size, channels, width, height = x.size()
        x = x.view(batch_size, -1)
        x = self.layer_1(x)
        x = torch.relu(x)
        x = self.layer_2(x)
        x = torch.relu(x)
        x = self.layer_3(x)
        x = torch.log_softmax(x, dim=1)
        return x

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=self.lr)

    def training_step(self, train_batch, batch_idx):
        x, y = train_batch
        logits = self.forward(x)
        loss = F.nll_loss(logits, y)
        return loss

    def validation_step(self, val_batch, batch_idx):
        x, y = val_batch
        logits = self.forward(x)
        loss = F.nll_loss(logits, y)
        acc = self.accuracy(logits, y)
        return {"val_loss": loss, "val_accuracy": acc}

    def validation_epoch_end(self, outputs):
        avg_loss = torch.stack([x["val_loss"] for x in outputs]).mean()
        avg_acc = torch.stack([x["val_accuracy"] for x in outputs]).mean()
        self.log("ptl/val_loss", avg_loss)
        self.log("ptl/val_accuracy", avg_acc)


def train_mnist_tune(config, num_epochs=10):
    dm = mnist_datamodule(DATA_DIR, config['batch_size'], 1)
    model = LightningMNISTClassifier(config, '.')
    plugin = RayPlugin(num_workers=NUM_WORKERS, use_gpu=GPU, init_hook=disable_slurm)
    trainer = pl.Trainer(
        max_epochs=num_epochs,
        progress_bar_refresh_rate=0,
        callbacks=[TuneReportCallback(on="epoch_end")],
        plugins=[plugin])
    trainer.fit(model, dm)


def tune_mnist(num_samples, num_epochs):
    config = {
        "layer_1": tune.choice([32, 64, 128]),
        "layer_2": tune.choice([64, 128, 256]),
        "lr": tune.loguniform(1e-4, 1e-1),
        "batch_size": tune.choice([32, 64, 128]),
    }

    trainable = tune.with_parameters(
        train_mnist_tune, num_epochs=num_epochs)
    analysis = tune.run(
        trainable,
        resources_per_trial=get_tune_ddp_resources(num_workers=NUM_WORKERS, use_gpu=GPU),
        metric="ptl/val_loss",
        mode="min",
        config=config,
        num_samples=num_samples,
        name="tune_mnist")

    print("Best hyperparameters found were: ", analysis.best_config)


class TuneThread(Thread):
    def run(self) -> None:
        tune_mnist(num_samples=100, num_epochs=100)


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    os.environ['RAY_BACKEND_LOG_LEVEL'] = 'debug'
    os.environ['TUNE_DISABLE_AUTO_CALLBACK_LOGGERS'] = '1'
    os.environ['SLURM_JOB_NAME'] = 'bash'

    try:
        ray.init(address='auto')
    except ConnectionError:
        pass

    TuneThread().start()
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by amogkam** [comment]
Can you also set `os.environ['SLURM_JOB_NAME'] = 'bash'` in the thread? Also I would recommend not running Tune in a thread if possible. What's the use case for this?

**Comment by import-antigravity** [comment]
> Can you also set `os.environ['SLURM_JOB_NAME'] = 'bash'` in the thread? Also I would recommend not running Tune in a thread if possible. What's the use case for this?

The use case is trying to run the tuning job as an RLLib ExternalEnv, which subclasses `Thread`

**Comment by xwjiang2010** [comment]
Hmmm, I am not sure I quite understand the use case here and why Tune needs to support this. 
Can RLlib folks take a look here first about "running tuning job as an RLlib ExternalEnv"?

**Comment by import-antigravity** [comment]
> Hmmm, I am not sure I quite understand the use case here and why Tune needs to support this.
> Can RLlib folks take a look here first about "running tuning job as an RLlib ExternalEnv"?

Yeah I think the problem here is probably on the RLLib side. Thus I'm going to close this
