### ISSUE TITLE
[Ray Client][Bug] Ray conflicts with PySpark on namedtuple customization

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#19032]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

Our customer has code depends on pyspark, which monkey patches the namedtuple class's serialization.  When Ray client serialize a ClientObjectRef, it will try to create a PickleStub which extendes namedtuple class.  While pyspark serialized it, Ray is not able to recognize it, and causing failure.
```
    return ray.get(driver_func.remote(*args, **kwargs))
  File "/usr/lib/python3.6/site-packages/ray/util/client/common.py", line 345, in remote
    return return_refs(ray.call_remote(self, *args, **kwargs))
  File "/usr/lib/python3.6/site-packages/ray/util/client/api.py", line 102, in call_remote
    return self.worker.call_remote(instance, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/ray/util/client/worker.py", line 460, in call_remote
    return self._call_schedule_for_task(task, instance._num_returns())
  File "/usr/lib/python3.6/site-packages/ray/util/client/worker.py", line 477, in _call_schedule_for_task
    raise cloudpickle.loads(ticket.error)
AssertionError
```

The workaround is adding a bypass in the pyspark serializers file like below, in our driver node, make this manual change: in pyspark/serializers.py
```
def _hack_namedtuple(cls):
    """ Make class generated by namedtuple picklable """
    name = cls.__name__
    fields = cls._fields

    def __reduce__(self):
        # Ray PickleStub will use its original pickler, do not hack other namedtuple subclasses
        if 'PickleStub(' in self.__doc__:
            return super(cls, self).__reduce__()
        return (_restore, (name, fields, tuple(self)))
    cls.__reduce__ = __reduce__
    cls._is_namedtuple_ = True
    return cls 
```

### Reproduction script

Repro like below:
```
ray start --head
```
ray client connect to the ray
in python run code below:
```
from pyspark.sql import DataFrame

from typing import Any, List
import ray
import os
import ray.util
ray_client_connection_str = 'str.to.cluster'
connection_output = ray.util.connect(ray_client_connection_str)

import time
from pyarrow import fs
train_dir = '/path/to/train_data'
normal nodes.
batch_size = 100
batch_size = batch_size
num_workers = 2
ray_pipeline = ray.data.read_parquet(train_dir)

total_rows = ray_pipeline.count()
split_idx = total_rows // num_workers

# this will fail with cloudpickle error
splits = ray_pipeline.split_at_indices([split_idx * i + 10 for i in range(1, num_workers)])
```
remove the first from pyspark.sal import ...  will not trigger the error and splits will work just fine.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by krfricke** [comment]
Simple self-contained repro script:

```
# only for the purpose of introduce the bug
from pyspark.sql import DataFrame
import ray.util

connection_output = ray.util.connect("127.0.0.1:10001")

batch_size = 100
batch_size = batch_size
num_workers = 2
ray_pipeline = ray.data.from_items(list(range(1_000)))
total_rows = ray_pipeline.count()
split_idx = total_rows // num_workers

# this will fail with cloudpickle error
splits = ray_pipeline.split_at_indices([split_idx * i + 10 for i in range(1, num_workers)])
print(splits)
ray.get([split.to_numpy() for split in splits][0][0])

print("PASSED")
```

Results in the following error:

```
Traceback (most recent call last):
  File "repro.py", line 17, in <module>
    ray.get([split.to_numpy() for split in splits][0][0])
  File "/Users/kai/coding/ray/python/ray/_private/client_mode_hook.py", line 88, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/Users/kai/coding/ray/python/ray/util/client/api.py", line 42, in get
    return self.worker.get(vals, timeout=timeout)
  File "/Users/kai/coding/ray/python/ray/util/client/worker.py", line 346, in get
    res = self._get(to_get, op_timeout)
  File "/Users/kai/coding/ray/python/ray/util/client/worker.py", line 362, in _get
    ids=[r.id for r in ref], timeout=timeout)
  File "/Users/kai/coding/ray/python/ray/util/client/worker.py", line 362, in <listcomp>
    ids=[r.id for r in ref], timeout=timeout)
  File "python/ray/includes/object_ref.pxi", line 210, in ray._raylet.ClientObjectRef.id.__get__
  File "python/ray/includes/object_ref.pxi", line 189, in ray._raylet.ClientObjectRef.binary
  File "python/ray/includes/object_ref.pxi", line 261, in ray._raylet.ClientObjectRef._wait_for_id
  File "python/ray/includes/object_ref.pxi", line 263, in ray._raylet.ClientObjectRef._wait_for_id
  File "/Users/kai/.pyenv/versions/3.7.7/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/Users/kai/.pyenv/versions/3.7.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
AssertionError
```

**Comment by krfricke** [comment]
See also https://issues.apache.org/jira/browse/SPARK-22674
