### ISSUE TITLE
[Bug] grpc_status:13 error when initializing ray with TLS credentials

### ISSUE THREAD

**Issue by vtao2** [ray-project/ray#19117]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

When calling `ray.init()` using SSL credentials for mTLS, for example:
```
grpc.ssl_channel_credentials(private_key=key, certificate_chain=cert)
ray.init(workspace_uri, _credentials=credentials, **ray_init_kwargs)
```

We see a GRPC error after 5 or so minutes:

```
Got Error from logger channel -- shutting down: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Received RST_STREAM with error code 1"
	debug_error_string = "{"created":"@1632932230.284700000","description":"Error received from peer ipv4:34.132.183.221:443","file":"src/core/lib/surface/call.cc","file_line":1070,"grpc_message":"Received RST_STREAM with error code 1","grpc_status":13}"
>
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/clv/lib/python3.8/site-packages/ray/util/client/logsclient.py", line 42, in _log_main
    for record in log_stream:
  File "/usr/local/Caskroom/miniconda/base/envs/clv/lib/python3.8/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/usr/local/Caskroom/miniconda/base/envs/clv/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Received RST_STREAM with error code 1"
	debug_error_string = "{"created":"@1632932230.284700000","description":"Error received from peer ipv4:34.132.183.221:443","file":"src/core/lib/surface/call.cc","file_line":1070,"grpc_message":"Received RST_STREAM with error code 1","grpc_status":13}"
>
```

This error gets logged, however, the *code continues to run and work as expected*. 

This could be caused by going through nginx though, and could be not related to credentials. 🤷‍♀️ 

### Reproduction script

```
ray.init(workspace_uri, _credentials=credentials, **ray_init_kwargs)
```

### Anything else

This problem occurs basically every time after a few minutes. Again, it doesn't actually break anything. The code runs as expected. It just affects the UX -- :) 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by AmeerHajAli** [comment]
what ray/python version is this? did you try a nightly version?

**Comment by AmeerHajAli** [comment]
Please reopen if this does not resolve your issue.
