### ISSUE TITLE
[Bug] KeyError while resuming ray tune with SkOptSearch as the optimizer

### ISSUE THREAD

**Issue by xiangdal** [ray-project/ray#19113]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

1. I resumed training from a previous checkpoint.
2. The previous training results loaded successfully.
3. When the first new trial completes with SkOptSearch as the optimizer, I encountered `KeyError: '8717c4de'` from this [statement](https://github.com/ray-project/ray/blob/master/python/ray/tune/suggest/skopt.py#L286) with the following error message:
```
2021-10-05 10:39:36,091 ERROR trial_runner.py:773 -- Trial train_and_validate_hparam_8717c4de: Error processing event.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/dg/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 747, in _process_trial
    decision = self._process_trial_result(trial, result)
  File "/home/ubuntu/miniconda3/envs/dg/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 800, in _process_trial_result
    trial.trial_id, result=flat_result)
  File "/home/ubuntu/miniconda3/envs/dg/lib/python3.6/site-packages/ray/tune/suggest/search_generator.py", line 130, in on_trial_complete
    trial_id=trial_id, result=result, error=error)
  File "/home/ubuntu/miniconda3/envs/dg/lib/python3.6/site-packages/ray/tune/suggest/skopt.py", line 283, in on_trial_complete
    self._process_result(trial_id, result)
  File "/home/ubuntu/miniconda3/envs/dg/lib/python3.6/site-packages/ray/tune/suggest/skopt.py", line 287, in _process_result
    skopt_trial_info = self._live_trial_mapping[trial_id]
KeyError: '8717c4de'
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/dg/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 747, in _process_trial
    decision = self._process_trial_result(trial, result)
  File "/home/ubuntu/miniconda3/envs/dg/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 800, in _process_trial_result
    trial.trial_id, result=flat_result)
  File "/home/ubuntu/miniconda3/envs/dg/lib/python3.6/site-packages/ray/tune/suggest/search_generator.py", line 130, in on_trial_complete
    trial_id=trial_id, result=result, error=error)
  File "/home/ubuntu/miniconda3/envs/dg/lib/python3.6/site-packages/ray/tune/suggest/skopt.py", line 283, in on_trial_complete
    self._process_result(trial_id, result)
  File "/home/ubuntu/miniconda3/envs/dg/lib/python3.6/site-packages/ray/tune/suggest/skopt.py", line 287, in _process_result
    skopt_trial_info = self._live_trial_mapping[trial_id]
KeyError: '8717c4de'
```

### Reproduction script

I do not have a reproducible script.

### Anything else

related closed [issue](https://github.com/ray-project/ray/issues/8312)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by xiangdal** [comment]
fyi, both 1.6.0 and 1.5.2 have this issue, but the nightly is working for me. Is the nightly going to be released as 1.7.0 or 2.0.0?

**Comment by krfricke** [comment]
It will probably be in 1.8.0 (later this month)

**Comment by xiangdal** [comment]
I'm not able to reproduce this issue on a toy example, but it persists in my own repo. Do you have a hunch about what might be causing this issue given this `KeyError `?
