### ISSUE TITLE
[tune] Test failure in Jenkins "Unknown trainable: DDPG"

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1913]
I've seen this test failure a number of times now. E.g., https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/4869/console.

```
+ docker run --rm --shm-size=10G --memory=10G bf861e97ff02bbc38f1ef169468df3f982543d7126a2d56d1e68bc0b74f2a3e5 python /ray/python/ray/rllib/train.py --env Pendulum-v0 --run DDPG --stop '{"training_iteration": 2}' --config '{"num_workers": 1}'
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:22113 to respond...
Waiting for redis server at 127.0.0.1:10916 to respond...
Warning: Reducing object store memory because /dev/shm has only 10737418240 bytes available. You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
Starting local scheduler with the following resources: {'GPU': 0, 'CPU': 48}.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui44359.ipynb?token=a4d9c3a34447e0c26f47293ba36e0198120f25de00ff675b
======================================================================

WARNING: lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
Traceback (most recent call last):
  File "/ray/python/ray/rllib/train.py", line 83, in <module>
    run_experiments(experiments, scheduler=_make_scheduler(args))
  File "/ray/python/ray/tune/tune.py", line 69, in run_experiments
    scheduler.add_experiment(experiment, runner)
  File "/ray/python/ray/tune/trial_scheduler.py", line 62, in add_experiment
    trial_runner.add_trial(next(generator))
  File "/ray/python/ray/tune/variant_generator.py", line 66, in generate_trials
    max_failures=args.max_failures)
  File "/ray/python/ray/tune/trial.py", line 95, in __init__
    raise TuneError("Unknown trainable: " + trainable_name)
ray.tune.error.TuneError: Unknown trainable: DDPG
```

cc @richardliaw @ericl

**Comment by ericl** [comment]
Is it possible jenkins doesn't have a clean checkout or something? I can't think of any other reason why this would happen. There don't seem to be any import errors in the build log.

**Comment by ericl** [comment]
I think this is resolved.

**Comment by robertnishihara** [comment]
Ok, out of curiosity do we know what the issue was? Or do we think the original error was not a real problem?

**Comment by canercak** [comment]
I get this in google colab. It works in local. 
```

2019-05-02 08:46:30,032	INFO services.py:407 -- Waiting for redis server at 127.0.0.1:11505 to respond...
2019-05-02 08:46:30,175	INFO services.py:407 -- Waiting for redis server at 127.0.0.1:64150 to respond...
2019-05-02 08:46:30,179	INFO services.py:804 -- Starting Redis shard with 2.58 GB max memory.
2019-05-02 08:46:30,243	INFO node.py:483 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-05-02_08-46-29_139/logs.
2019-05-02 08:46:30,246	INFO services.py:1427 -- Starting the Plasma object store with 3.87 GB memory using /dev/shm.
2019-05-02 08:46:30,402	INFO tune.py:64 -- Did not find checkpoint file in /root/ray_results/Projectlife-v1-IOTABTC-15m-RAINBOW-close-sma20.
2019-05-02 08:46:30,404	INFO tune.py:211 -- Starting a new experiment.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/2 CPUs, 0/0 GPUs
Memory usage on this node: 1.0/13.7 GB

---------------------------------------------------------------------------
TuneError                                 Traceback (most recent call last)
<ipython-input-42-871fa383cba9> in <module>()
    302 ray.shutdown()
    303 ray.init()
--> 304 run_experiments({experiment: get_params("PPO")})
    305 

9 frames
/usr/local/lib/python3.6/dist-packages/ray/tune/trial.py in _registration_check(cls, trainable_name)
    338             from ray import rllib  # noqa: F401
    339             if not has_trainable(trainable_name):
--> 340                 raise TuneError("Unknown trainable: " + trainable_name)
    341 
    342     @classmethod
```

**Comment by guyue5** [comment]
How to solve this problem, i got the same problem
~/anaconda3/envs/TensorFlow-1.8/lib/python3.6/site-packages/ray/tune/trial.py in _registration_check(cls, trainable_name)
    338             from ray import rllib  # noqa: F401
    339             if not has_trainable(trainable_name):
--> 340                 raise TuneError("Unknown trainable: " + trainable_name)
    341 
    342     @classmethod

TuneError: Unknown trainable: PG
