### ISSUE TITLE
[ray sgd v2] retrieving model from `Trainer.run()`

### ISSUE THREAD

**Issue by davidegraff** [ray-project/ray#19161]
I recently ported my code from ray sgd v1 to ray sgd v2 but am not clear on how to retrieve the fitted model. For example, when I run code that looks like the following
```python
            print(list(model.parameters())[1])
            trainer = Trainer("torch", num_workers, use_gpu, {"CPU": ncpu})
            trainer.start()
            results = trainer.run(train_func, config)
            trainer.shutdown()

            print(list(model.parameters())[1])
```
the two print statements are the same. I have some basic print statements inside `train_func` and I can see that my model is being fitted. In the above example, the output of `train_func` is `None` (i.e., it just `return`s). When I change train_func to model like so:
```python
def train_func(config: Dict):
    model = config["model"]
    device = torch.device(
        f"cuda:{sgd.local_rank()}" if torch.cuda.is_available() else "cpu"
    )
    if torch.cuda.is_available():
        torch.cuda.set_device(device)

    model = model.to(device)
    model = DistributedDataParallel(
        model, device_ids=[sgd.local_rank()] if torch.cuda.is_available() else None
    )
    [ training code goes here ]

    return model
```
I run into this error:
```
2021-10-06 16:21:27,679	ERROR serialization.py:270 -- Default process group has not been initialized, please make sure to call init_process_group.
Traceback (most recent call last):
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/ray/serialization.py", line 268, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/ray/serialization.py", line 191, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/ray/serialization.py", line 169, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/ray/serialization.py", line 159, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 576, in __setstate__
    self.process_group = _get_default_group()
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 358, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
Traceback (most recent call last):
  File "run.py", line 73, in <module>
    main()
  File "run.py", line 55, in main
    explorer.run()
  File "/home/degraff/molpal/molpal/explorer.py", line 326, in run
    self.explore_batch()
  File "/home/degraff/molpal/molpal/explorer.py", line 396, in explore_batch
    self._update_model()
  File "/home/degraff/molpal/molpal/explorer.py", line 730, in _update_model
    self.model.train(
  File "/home/degraff/molpal/molpal/models/mpnmodels.py", line 424, in train
    return self.model.train(xs, ys)
  File "/home/degraff/molpal/molpal/models/mpnmodels.py", line 171, in train
    results = trainer.run(mpnn.sgd.train_func, self.train_config)
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/ray/util/sgd/v2/trainer.py", line 240, in run
    for intermediate_result in iterator:
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/ray/util/sgd/v2/trainer.py", line 567, in __next__
    self._run_with_error_handling(
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/ray/util/sgd/v2/trainer.py", line 537, in _run_with_error_handling
    return func()
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/ray/util/sgd/v2/backends/backend.py", line 600, in finish_training
    results = self.get_with_failure_handling(futures)
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/ray/util/sgd/v2/backends/backend.py", line 619, in get_with_failure_handling
    success, failed_worker_indexes = check_for_failure(remote_values)
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/ray/util/sgd/v2/utils.py", line 34, in check_for_failure
    ray.get(object_ref)
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/ray/worker.py", line 1624, in get
    raise value
ray.exceptions.RaySystemError: System error: Default process group has not been initialized, please make sure to call init_process_group.
traceback: Traceback (most recent call last):
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/ray/serialization.py", line 268, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/ray/serialization.py", line 191, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/ray/serialization.py", line 169, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/ray/serialization.py", line 159, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 576, in __setstate__
    self.process_group = _get_default_group()
  File "/home/degraff/.conda/envs/ibm_doe/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 358, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

Can anyone help me figure out what's going on?

**Comment by davidegraff** [comment]
Yeah sure!. The specifics of how training is being done is, essentially, there is one `ModelWrapper` class that itself has a `model` attribute which is the actual pytorch model that is being trained. At a high level, it looks something like this:
```python
class ModelWrapper:
    def __init__(self, ...):
        self.model = Model(....)
        ....
        self.train_config = {...} # training options like number of epochs, learning rate, etc.
        self.trainer = Trainer("torch", num_workers, use_gpu, {"CPU": ncpu})

    def train(self, xs, ys):
        train_data, val_data = make_datasets(xs, ys)
        self.train_config["train_data"] = train_data
        self.train_config["val_data"] = val_data
        self.trainer.start()
        results = self.trainer.run(mpnn.sgd.train_func, self.train_config)
        self.trainer.shutdown()
```
The specifics of where the model is trained can be found [here](https://github.com/coleygroup/molpal/blob/refactor/ray-sgd-v2/molpal/models/mpnmodels.py#L153) and the definition of the training function is [here](https://github.com/coleygroup/molpal/blob/refactor/ray-sgd-v2/molpal/models/mpnn/sgd.py#L19). The main problem is that first and last `print` statements output the same model weights. E.g.,
```
Parameter containing:
tensor([[-0.0064,  0.0383, -0.0143,  ..., -0.1262,  0.0140, -0.0845],
        [ 0.0499, -0.0577, -0.0667,  ...,  0.0942,  0.0683,  0.0546],
        [ 0.0228,  0.0975,  0.0073,  ...,  0.0392,  0.0075,  0.0124],
        ...,
        [ 0.0928, -0.0060,  0.1545,  ..., -0.0585, -0.0664,  0.0421],
        [ 0.0129,  0.0545,  0.1363,  ..., -0.0699,  0.0823,  0.0398],
        [-0.0249,  0.0254, -0.0722,  ...,  0.0683,  0.0016, -0.0224]],
       requires_grad=True)
Parameter containing:
tensor([[-0.0064,  0.0383, -0.0143,  ..., -0.1262,  0.0140, -0.0845],
        [ 0.0499, -0.0577, -0.0667,  ...,  0.0942,  0.0683,  0.0546],
        [ 0.0228,  0.0975,  0.0073,  ...,  0.0392,  0.0075,  0.0124],
        ...,
        [ 0.0928, -0.0060,  0.1545,  ..., -0.0585, -0.0664,  0.0421],
        [ 0.0129,  0.0545,  0.1363,  ..., -0.0699,  0.0823,  0.0398],
        [-0.0249,  0.0254, -0.0722,  ...,  0.0683,  0.0016, -0.0224]],
       requires_grad=True)
```

thanks again for the help!

**Comment by amogkam** [comment]
Hey @davidegraff, thanks for the update and the pointer to your code. I tried replicating this behavior matching the code and environment as much as possible to yours, but I'm still seeing the model parameters are being updated for me even after returning `model.module`. Can you double check that your model is actually training? 

For reference, here is the code that I am using. It's a modification of the `train_linear_example`.

```python
import numpy as np
import torch
import torch.nn as nn
import ray.util.sgd.v2 as sgd
from ray.util.sgd.v2 import Trainer, TorchConfig
from torch.nn.parallel import DistributedDataParallel
from torch.utils.data import DistributedSampler


class LinearDataset(torch.utils.data.Dataset):
    """y = a * x + b"""

    def __init__(self, a, b, size=1000):
        x = np.arange(0, 10, 10 / size, dtype=np.float32)
        self.x = torch.from_numpy(x)
        self.y = torch.from_numpy(a * x + b)

    def __getitem__(self, index):
        return self.x[index, None], self.y[index, None]

    def __len__(self):
        return len(self.x)


def train(dataloader, model, loss_fn, optimizer, device):
    for X, y in dataloader:
        X, y = X.to(device), y.to(device)
        # Compute prediction error
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()


def train_func(config):
    device = torch.device(
        f"cuda:{sgd.local_rank()}" if torch.cuda.is_available() else "cpu"
    )
    if torch.cuda.is_available():
        torch.cuda.set_device(device)

    data_size = config.get("data_size", 1000)
    val_size = config.get("val_size", 400)
    batch_size = config.get("batch_size", 32)
    lr = config.get("lr", 1e-2)
    epochs = config.get("epochs", 3)

    train_dataset = LinearDataset(2, 5, size=data_size)
    train_loader = torch.utils.data.DataLoader(
        train_dataset,
        batch_size=batch_size,
        sampler=DistributedSampler(train_dataset))

    model = config["model"]
    model = model.to(device)
    model = DistributedDataParallel(model, device_ids=[sgd.local_rank()] if torch.cuda.is_available() else None)

    loss_fn = nn.MSELoss()

    optimizer = torch.optim.Adam(model.parameters(), lr,
                                 weight_decay=0)

    for _ in range(epochs):
        train(train_loader, model, loss_fn, optimizer, device=device)

    return model.module.to("cpu")


def train_linear(num_workers=2):
    model = nn.Linear(1, 1)
    print(list(model.parameters())[1])
    trainer = Trainer(TorchConfig(backend="gloo"), num_workers=num_workers)
    config = {"lr": 1e-2, "hidden_size": 1, "batch_size": 4, "epochs": 3,
              "model": model}
    trainer.start()
    results = trainer.run(
        train_func,
        config)
    trainer.shutdown()

    print(list(results[0].parameters())[1])
    return results


train_linear()
```

I am running this on 2 GPUs and the output that I am seeing is 

```
Parameter containing:
tensor([0.6457], requires_grad=True)
2021-10-08 23:46:36,266	INFO trainer.py:150 -- Run results will be logged in: /home/ubuntu/ray_results/sgd_2021-10-08_23-46-32/run_001
(pid=7290) 2021-10-08 23:46:36,242	INFO torch.py:69 -- Setting up process group for: env:// [rank=1, world_size=2]
(pid=7329) 2021-10-08 23:46:36,242	INFO torch.py:69 -- Setting up process group for: env:// [rank=0, world_size=2]
Parameter containing:
tensor([3.0727], requires_grad=True)
```
so the model parameters are being updated.

Can you try out this example and see if you are getting the same behavior? Thanks!
