### ISSUE TITLE
[Core][Bug] Gcs crashed and cluster hangs 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#19172]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

```
(pid=gcs_server, ip=XX) [2021-10-06 23:59:31,998 C 1900 1900] gcs_job_manager.cc:176:  Check failed: it != ray_namespaces_.end() Couldn't find job with id: 26b30000
(pid=gcs_server, ip=XX) *** StackTrace Information ***
(pid=gcs_server, ip=XX)     ray::SpdLogMessage::Flush()
(pid=gcs_server, ip=XX)     ray::RayLog::~RayLog()
(pid=gcs_server, ip=XX)     ray::gcs::GcsJobManager::GetRayNamespace()
(pid=gcs_server, ip=XX)     std::_Function_handler<>::_M_invoke()
(pid=gcs_server, ip=XX)     ray::gcs::GcsActorManager::RegisterActor()
(pid=gcs_server, ip=XX)     ray::gcs::GcsActorManager::HandleRegisterActor()
(pid=gcs_server, ip=XX)     std::_Function_handler<>::_M_invoke()
(pid=gcs_server, ip=XX)     boost::asio::detail::completion_handler<>::do_complete()
(pid=gcs_server, ip=XX)     boost::asio::detail::scheduler::do_run_one()
(pid=gcs_server, ip=XX)     boost::asio::detail::scheduler::run()
(pid=gcs_server, ip=XX)     boost::asio::io_context::run()
(pid=gcs_server, ip=XX)     main
(pid=gcs_server, ip=XX)     __libc_start_main


2021-10-06 23:59:36,466	WARNING worker.py:1231 -- The autoscaler failed with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 419, in run
    self._run()
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 307, in _run
    self.update_load_metrics()
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 227, in update_load_metrics
    request, timeout=4)
  File "/opt/conda/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/conda/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Broken pipe"
	debug_error_string = "{"created":"@1633564776.437866949","description":"Error received from peer ipv4:XX:36477","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Broken pipe","grpc_status":14}"
```

### Reproduction script

n/a

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by iycheng** [comment]
This case is because:
1. actor creation submitted 
2. job terminated
3. gcs handle job termination first
4. gcs handle actor creation then
