### ISSUE TITLE
Ray Tune gets errors running with PPO and "MountainCarContinuous-v0"

### ISSUE THREAD

**Issue by RuofanKong** [ray-project/ray#1921]
### System information
- **OS Platform: Mac Sierra 10.12.6 **:
- **Ray version: 0.4.0 **:
- **Python version: 3.5.2 **:

I am running the example for the Ray Tune using PPO. Specifically, I run `pbt_ppo_example.py` in the dir `ray/python/ray/tune/examples`, but with Open AI Gym env "MountainCarContinuous-v0". So I made some change locally for the env name inside `pbt_ppo_example.py`:

```
#!/usr/bin/env python
"""Example of using PBT with RLlib.

Note that this requires a cluster with at least 8 GPUs in order for all trials
to run concurrently, otherwise PBT will round-robin train the trials which
is less efficient (or you can set {"gpu": 0} to use CPUs for SGD instead).
"""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import random

import ray
from ray.tune import run_experiments
from ray.tune.pbt import PopulationBasedTraining

if __name__ == "__main__":

    # Postprocess the perturbed config to ensure it's still valid
    def explore(config):
        # ensure we collect enough timesteps to do sgd
        if config["timesteps_per_batch"] < config["sgd_batchsize"] * 2:
            config["timesteps_per_batch"] = config["sgd_batchsize"] * 2
        # ensure we run at least one sgd iter
        if config["num_sgd_iter"] < 1:
            config["num_sgd_iter"] = 1
        return config

    pbt = PopulationBasedTraining(
        time_attr="time_total_s",
        reward_attr="episode_reward_mean",
        perturbation_interval=120,
        resample_probability=0.25,
        # Specifies the mutations of these hyperparams
        hyperparam_mutations={
            "lambda": lambda: random.uniform(0.9, 1.0),
            "clip_param": lambda: random.uniform(0.01, 0.5),
            "sgd_stepsize": [1e-3, 5e-4, 1e-4, 5e-5, 1e-5],
            "num_sgd_iter": lambda: random.randint(1, 30),
            "sgd_batchsize": lambda: random.randint(128, 16384),
            "timesteps_per_batch": lambda: random.randint(2000, 160000),
        },
        custom_explore_fn=explore)

    ray.init()
    run_experiments(
        {
            "pbt_humanoid_test": {
                "run": "PPO",
                "env": "MountainCarContinuous-v0",  # ""Humanoid-v1",
                "repeat": 8,
                "trial_resources": {
                    "cpu": 4,
                    "gpu": 0  # 1
                },
                "config": {
                    "kl_coeff":
                    1.0,
                    "num_workers":
                    8,
                    "devices": ["/gpu:0"],
                    "model": {
                        "free_log_std": True
                    },
                    # These params are tuned from a fixed starting value.
                    "lambda":
                    0.95,
                    "clip_param":
                    0.2,
                    "sgd_stepsize":
                    1e-4,
                    # These params start off randomly drawn from a set.
                    "num_sgd_iter":
                    lambda spec: random.choice([10, 20, 30]),
                    "sgd_batchsize":
                    lambda spec: random.choice([128, 512, 2048]),
                    "timesteps_per_batch":
                    lambda spec: random.choice([10000, 20000, 40000])
                },
            },
        },
        scheduler=pbt)
```
But I got the error when I run the above code:
```
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:15914 to respond...
Waiting for redis server at 127.0.0.1:22006 to respond...
Starting local scheduler with the following resources: {'GPU': 0, 'CPU': 8}.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui34252.ipynb?token=9baa9266356be761976d9d59ca13949982f064c2e9b84e4c
======================================================================

WARNING: python-snappy not available, disabling sample compression
== Status ==
PopulationBasedTraining: 0 checkpoints, 0 perturbs
Result logdir: /Users/ruofankong/ray_results/pbt_humanoid_test
PENDING trials:
 - PPO_MountainCarContinuous-v0_0_num_sgd_iter=10,sgd_batchsize=128,timesteps_per_batch=20000:	PENDING
 - PPO_MountainCarContinuous-v0_1_num_sgd_iter=20,sgd_batchsize=128,timesteps_per_batch=10000:	PENDING
 - PPO_MountainCarContinuous-v0_2_num_sgd_iter=10,sgd_batchsize=2048,timesteps_per_batch=20000:	PENDING
 - PPO_MountainCarContinuous-v0_3_num_sgd_iter=10,sgd_batchsize=128,timesteps_per_batch=10000:	PENDING
 - PPO_MountainCarContinuous-v0_4_num_sgd_iter=30,sgd_batchsize=128,timesteps_per_batch=10000:	PENDING
 - PPO_MountainCarContinuous-v0_5_num_sgd_iter=10,sgd_batchsize=512,timesteps_per_batch=10000:	PENDING
 - PPO_MountainCarContinuous-v0_6_num_sgd_iter=10,sgd_batchsize=2048,timesteps_per_batch=10000:	PENDING
 - PPO_MountainCarContinuous-v0_7_num_sgd_iter=30,sgd_batchsize=2048,timesteps_per_batch=40000:	PENDING

Created LogSyncer for /Users/ruofankong/ray_results/pbt_humanoid_test/PPO_MountainCarContinuous-v0_0_num_sgd_iter=10,sgd_batchsize=128,timesteps_per_batch=20000_2018-04-17_16-43-18wbvlazmf -> 
WARNING: Serializing objects of type <class 'ray.tune.registry._Registry'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
== Status ==
PopulationBasedTraining: 0 checkpoints, 0 perturbs
Resources used: 4/8 CPUs, 0/0 GPUs
Result logdir: /Users/ruofankong/ray_results/pbt_humanoid_test
PENDING trials:
 - PPO_MountainCarContinuous-v0_1_num_sgd_iter=20,sgd_batchsize=128,timesteps_per_batch=10000:	PENDING
 - PPO_MountainCarContinuous-v0_2_num_sgd_iter=10,sgd_batchsize=2048,timesteps_per_batch=20000:	PENDING
 - PPO_MountainCarContinuous-v0_3_num_sgd_iter=10,sgd_batchsize=128,timesteps_per_batch=10000:	PENDING
 - PPO_MountainCarContinuous-v0_4_num_sgd_iter=30,sgd_batchsize=128,timesteps_per_batch=10000:	PENDING
 - PPO_MountainCarContinuous-v0_5_num_sgd_iter=10,sgd_batchsize=512,timesteps_per_batch=10000:	PENDING
 - PPO_MountainCarContinuous-v0_6_num_sgd_iter=10,sgd_batchsize=2048,timesteps_per_batch=10000:	PENDING
 - PPO_MountainCarContinuous-v0_7_num_sgd_iter=30,sgd_batchsize=2048,timesteps_per_batch=40000:	PENDING
RUNNING trials:
 - PPO_MountainCarContinuous-v0_0_num_sgd_iter=10,sgd_batchsize=128,timesteps_per_batch=20000:	RUNNING

Created LogSyncer for /Users/ruofankong/ray_results/pbt_humanoid_test/PPO_MountainCarContinuous-v0_1_num_sgd_iter=20,sgd_batchsize=128,timesteps_per_batch=10000_2018-04-17_16-43-186fbqigq1 -> 
WARNING: python-snappy not available, disabling sample compression
WARNING: python-snappy not available, disabling sample compression
[2018-04-17 16:43:31,571] Making new env: MountainCarContinuous-v0
Observation shape is (2,)
Not using any observation preprocessor.
Remote function __init__ failed with:

Traceback (most recent call last):
  File "/Users/ruofankong/virtual_py3/lib/python3.5/site-packages/ray/worker.py", line 821, in _process_task
    *arguments)
  File "/Users/ruofankong/virtual_py3/lib/python3.5/site-packages/ray/actor.py", line 212, in actor_method_executor
    method_returns = method(actor, *args)
  File "/Users/ruofankong/virtual_py3/lib/python3.5/site-packages/ray/rllib/agent.py", line 84, in __init__
    Trainable.__init__(self, config, registry, logger_creator)
  File "/Users/ruofankong/virtual_py3/lib/python3.5/site-packages/ray/tune/trainable.py", line 89, in __init__
    self._setup()
  File "/Users/ruofankong/virtual_py3/lib/python3.5/site-packages/ray/rllib/agent.py", line 107, in _setup
    self._init()
  File "/Users/ruofankong/virtual_py3/lib/python3.5/site-packages/ray/rllib/ppo/ppo.py", line 100, in _init
    self.registry, self.env_creator, self.config, self.logdir, False)
  File "/Users/ruofankong/virtual_py3/lib/python3.5/site-packages/ray/rllib/ppo/ppo_evaluator.py", line 45, in __init__
    registry, env_creator(config["env_config"]), config["model"])
  File "/Users/ruofankong/virtual_py3/lib/python3.5/site-packages/ray/rllib/models/catalog.py", line 231, in get_preprocessor_as_wrapper
    return _RLlibPreprocessorWrapper(env, preprocessor)
  File "/Users/ruofankong/virtual_py3/lib/python3.5/site-packages/ray/rllib/models/catalog.py", line 270, in __init__
    -1.0, 1.0, preprocessor.shape, dtype=np.float32)
TypeError: __init__() got an unexpected keyword argument 'dtype'


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:15914")
  
Error processing event: Traceback (most recent call last):
  File "/Users/ruofankong/virtual_py3/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 218, in _process_events
    result = ray.get(result_id)
  File "/Users/ruofankong/virtual_py3/lib/python3.5/site-packages/ray/worker.py", line 2321, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(b11cbe41fe0a7fea3cb9f3fcb8f9e8c57415fcf9). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/Users/ruofankong/virtual_py3/lib/python3.5/site-packages/ray/worker.py", line 821, in _process_task
    *arguments)
  File "/Users/ruofankong/virtual_py3/lib/python3.5/site-packages/ray/actor.py", line 212, in actor_method_executor
    method_returns = method(actor, *args)
  File "/Users/ruofankong/virtual_py3/lib/python3.5/site-packages/ray/tune/trainable.py", line 106, in train
    "Trainable initialization failed, see previous errors")
ValueError: Trainable initialization failed, see previous errors


Remote function train failed with:

Traceback (most recent call last):
  File "/Users/ruofankong/virtual_py3/lib/python3.5/site-packages/ray/worker.py", line 821, in _process_task
    *arguments)
  File "/Users/ruofankong/virtual_py3/lib/python3.5/site-packages/ray/actor.py", line 212, in actor_method_executor
    method_returns = method(actor, *args)
  File "/Users/ruofankong/virtual_py3/lib/python3.5/site-packages/ray/tune/trainable.py", line 106, in train
    "Trainable initialization failed, see previous errors")
ValueError: Trainable initialization failed, see previous errors


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:15914")
```
The error could be reproduced by running `$ python pbt_ppo_example.py`, and I wonder if there're issues or I did something wrong. Thanks!

**Comment by richardliaw** [comment]
What is your current Gym version? Updating to >0.10 should fix this.

**Comment by RuofanKong** [comment]
@richardliaw thanks for your comment! Yes, the above problem is solved by upgrading my Gym to 0.10. But now I got a different error about resources:

```
The actor with ID a507b3b64fad94e7f002f2d482da6756de6ecc59 is taking a while to be created. It is possible that the cluster does not have enough resources to place this actor. Try reducing the number of actors created or increasing the number of slots available by using the --num-cpus, --num-gpus, and --resources flags.

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:55111")
  
The actor with ID c6f5c8016bca0f92a4e0665b937dcf4a7edba3eb is taking a while to be created. It is possible that the cluster does not have enough resources to place this actor. Try reducing the number of actors created or increasing the number of slots available by using the --num-cpus, --num-gpus, and --resources flags.

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:55111")
  
The actor with ID d8930a1e93fa90e9d40a7b6fad199752df647008 is taking a while to be created. It is possible that the cluster does not have enough resources to place this actor. Try reducing the number of actors created or increasing the number of slots available by using the --num-cpus, --num-gpus, and --resources flags.

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:55111")
  
The actor with ID e935b42c3feb7b6cb2fe740b192bd4a69de62960 is taking a while to be created. It is possible that the cluster does not have enough resources to place this actor. Try reducing the number of actors created or increasing the number of slots available by using the --num-cpus, --num-gpus, and --resources flags.

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:55111")
  
The actor with ID 859a422762f8a32adbe910fd82c480575d60baa7 is taking a while to be created. It is possible that the cluster does not have enough resources to place this actor. Try reducing the number of actors created or increasing the number of slots available by using the --num-cpus, --num-gpus, and --resources flags.

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:55111")
  
The actor with ID 729b926d7365bc64422c5a3bdb74e89617685cb9 is taking a while to be created. It is possible that the cluster does not have enough resources to place this actor. Try reducing the number of actors created or increasing the number of slots available by using the --num-cpus, --num-gpus, and --resources flags.

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:55111")
  
The actor with ID 4b425c7efb44e3e4b3bf5e88c6663a44f042ec4b is taking a while to be created. It is possible that the cluster does not have enough resources to place this actor. Try reducing the number of actors created or increasing the number of slots available by using the --num-cpus, --num-gpus, and --resources flags.

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:55111")
  
The actor with ID 5dd7d9c15187c44d6f814fb7cd81eab3cf1d9140 is taking a while to be created. It is possible that the cluster does not have enough resources to place this actor. Try reducing the number of actors created or increasing the number of slots available by using the --num-cpus, --num-gpus, and --resources flags.

...
```
Following the above error message, it looks like there's no enough resources for ray actors. So I wonder if Ray could dynamically adjust the resources usage such as sharing the resources across different actors if resources are limited.

**Comment by ericl** [comment]
@RuofanKong the issue seems to be that the `trial_resources` block in the example is not set correctly. In the master branch RLlib autoconfigures the resource requirements to avoid this problem (so that trial_resources is not needed).

**Comment by richardliaw** [comment]
Closing this now, as Eric's comment seems to resolve the issue.
