### ISSUE TITLE
[Bug] cloudpickle fails on modelCatalog with 1.7.0

### ISSUE THREAD

**Issue by dHonerkamp** [ray-project/ray#19218]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

I updated to 1.7.0 with `pip install ray[default,rllib]==1.7.0`.

I then run `from ray.rllib.models.catalog import ModelCatalog` and get the following error:
```
Traceback (most recent call last):
  File "/home/honerkam/miniconda3/envs/modulation_rl/lib/python3.6/site-packages/ray/cloudpickle/__init__.py", line 39, in dumps_debug
    return dumps(obj, *args, **kwargs)
  File "/home/honerkam/miniconda3/envs/modulation_rl/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/home/honerkam/miniconda3/envs/modulation_rl/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 580, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle _thread.RLock objects
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/honerkam/miniconda3/envs/modulation_rl/lib/python3.6/site-packages/ray/rllib/__init__.py", line 58, in <module>
    _register_all()
  File "/home/honerkam/miniconda3/envs/modulation_rl/lib/python3.6/site-packages/ray/rllib/__init__.py", line 35, in _register_all
    register_trainable(key, get_trainer_class(key))
  File "/home/honerkam/miniconda3/envs/modulation_rl/lib/python3.6/site-packages/ray/tune/registry.py", line 73, in register_trainable
    _global_registry.register(TRAINABLE_CLASS, name, trainable)
  File "/home/honerkam/miniconda3/envs/modulation_rl/lib/python3.6/site-packages/ray/tune/registry.py", line 145, in register
    self._to_flush[(category, key)] = pickle.dumps_debug(value)
  File "/home/honerkam/miniconda3/envs/modulation_rl/lib/python3.6/site-packages/ray/cloudpickle/__init__.py", line 47, in dumps_debug
    raise type(exc)(msg)
TypeError: ray.cloudpickle.dumps(<class 'ray.rllib.agents.trainer_template.A2C'>) failed.
To check which non-serializable variables are captured in scope, re-run the ray script with 'RAY_PICKLE_VERBOSE_DEBUG=1'.
python-BaseException
```

### Reproduction script

`from ray.rllib.models.catalog import ModelCatalog`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by simsimiSION** [comment]
Hi, I have the same problem, when evaluating the algorithm in ray[1.8.0]. Have you solved the problem? ^-^

**Comment by dHonerkamp** [comment]
I haven't tried it again. I chose to downgrade to the previous version until there is a fix
