### ISSUE TITLE
ray.init with huge_pages=True should raise an exception if the plasma_directory does not exist.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1922]
Currently

```
ray.init(huge_pages=True, plasma_directory="/mnt/hugepages")
```

will succeed even if `/mnt/hugepages` does not exist.

**Comment by kishansagathiya** [comment]
Looks like this issue has been fixed, close it?
```
>>> import ray
>>> ray.init(huge_pages=True, plasma_directory="/mnt/hugepages")
2020-08-28 17:11:47,248	INFO resource_spec.py:245 -- Starting Ray with 7.23 GiB memory available for workers and up to 3.62 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-08-28 17:11:47,871	INFO services.py:1215 -- View the Ray dashboard at 127.0.0.1:8265
2020-08-28 17:11:47,873	WARNING services.py:1674 -- WARNING: object_store_memory is not verified when plasma_directory is set.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kishan/code/ray/python/ray/worker.py", line 755, in init
    _global_node = ray.node.Node(
  File "/home/kishan/code/ray/python/ray/node.py", line 207, in __init__
    self.start_ray_processes()
  File "/home/kishan/code/ray/python/ray/node.py", line 801, in start_ray_processes
    self.start_plasma_store()
  File "/home/kishan/code/ray/python/ray/node.py", line 645, in start_plasma_store
    process_info = ray.services.start_plasma_store(
  File "/home/kishan/code/ray/python/ray/services.py", line 1733, in start_plasma_store
    plasma_directory, object_store_memory = determine_plasma_store_config(
  File "/home/kishan/code/ray/python/ray/services.py", line 1678, in determine_plasma_store_config
    raise ValueError(f"The file {plasma_directory} does not "
ValueError: The file /mnt/hugepages does not exist or is not a directory.
```
