### ISSUE TITLE
[Release Tests] Session does not terminate if startup times out

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#19226]
## Issue
When the session **startup** times out, the `e2e` script does not properly shutdown the session. The session will sit idle until the Anyscale auto-suspension kicks in (after 2 hours).

### Logs
```
[ERROR 2021-10-07 11:39:43,381] e2e.py: 1514  Process timed out while starting a session.
  | Traceback (most recent call last):
  | File "release/e2e.py", line 1394, in _run
  | File "release/e2e.py", line 881, in create_and_wait_for_session
  | File "release/e2e.py", line 445, in _check_stop
  | SessionTimeoutError: Process timed out while starting a session.
```

## Examples
| Test  | Session |
| ------------- | ------------- |
| [xgboost_sweep](https://buildkite.com/ray-project/periodic-ci/builds/1194#89af8e31-a90d-4b94-98b1-6e16770f24e6)  | [xgboost_sweep_1633630180](https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_LStkyxWz2xtQy2bsYPEhUWhR)  |

**Comment by matthewdeng** [comment]
One potential solution is to just reduce the auto-suspension time.
