### ISSUE TITLE
[autoscaler] aws node not ssh'ing

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#19268]
Hi folks I came in from this issue https://github.com/ray-project/ray/issues/18755 and wanted to confirm that I'm seeing this for AWS

Repro steps is https://docs.ray.io/en/latest/cluster/quickstart.html#ref-cluster-quick-start until `ray up -y config.yaml`

A machine was indeed created in my console but I kept getting this error even though I've enabled all ingoing and outgoing traffic. I also confirmed that aws credentials were correctlly stored in `.aws/credentials`

Also tested on my local macbook same issue

```

ubuntu@ip-172-31-12-140:~$ ray up -y config.yaml
Cluster: minimal

2021-10-08 23:57:32,857 INFO util.py:282 -- setting max workers for head node type to 0
2021-10-08 23:57:32,857 INFO util.py:286 -- setting max workers for ray.worker.default to 2
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
AWS config
  IAM Profile: ray-autoscaler-v1 [default]
  EC2 Key pair (all available node types): ray-autoscaler_2_us-west-2 [default]
  VPC Subnets (all available node types): subnet-00b909d3664ca1927, subnet-0f73c4179776b1b44, subnet-0954508b8c04c4190 [default]
  EC2 Security groups (all available node types): sg-0115e4342d6d47c84 [default]
  EC2 AMI (all available node types): ami-0a2363a9cff180a64

Updating cluster configuration and running full setup.
Cluster Ray runtime will be restarted. Confirm [y/N]: y [automatic, due to --yes]

<1/1> Setting up head node
  Prepared bootstrap config
  New status: waiting-for-ssh
  [1/7] Waiting for SSH to become available
    Running `uptime` as a test.
    Fetched IP: 34.209.103.80
ssh: connect to host 34.209.103.80 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 34.209.103.80 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 34.209.103.80 port 22: Connection timed out
```

_Originally posted by @msaroufim in https://github.com/ray-project/ray/issues/18774#issuecomment-939185317_

**Comment by richardliaw** [comment]
@msaroufim can you describe the behavior here? The node will first be available on the console, but SSh can take a while to enable.

**Comment by msaroufim** [comment]
Oh interesting, what do you mean by a while? I waited about 5 min.

Behavior was basically machine gets created and I see it on AWS console, it has the correct IP but ssh keeps failing over and over again for at least 5 min (maybe more) - I can try doing the same thing but just wait longer

**Comment by msaroufim** [comment]
Just wanted to confirm that actual error I got 

```
(ray) ubuntu@ip-172-31-12-140:~$ ray up -y config.yaml
Cluster: minimal

2021-10-11 22:05:15,842 INFO util.py:282 -- setting max workers for head node type to 0
2021-10-11 22:05:15,842 INFO util.py:286 -- setting max workers for ray.worker.default to 2
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
AWS config
  IAM Profile: ray-autoscaler-v1 [default]
  EC2 Key pair (all available node types): ray-autoscaler_2_us-west-2 [default]
  VPC Subnets (all available node types): subnet-00b909d3664ca1927, subnet-0f73c4179776b1b44, subnet-0954508b8c04c4190 [default]
  EC2 Security groups (all available node types): sg-0115e4342d6d47c84 [default]
  EC2 AMI (all available node types): ami-0a2363a9cff180a64

No head node found. Launching a new cluster. Confirm [y/N]: y [automatic, due to --yes]

Acquiring an up-to-date head node
  Launched 1 nodes [subnet_id=subnet-0f73c4179776b1b44]
    Launched instance i-0c977031522158db3 [state=pending, info=pending]
  Launched a new head node
  Fetching the new head node
  
<1/1> Setting up head node
  Prepared bootstrap config
  New status: waiting-for-ssh
  [1/7] Waiting for SSH to become available
    Running `uptime` as a test.
    Fetched IP: 35.164.1.178
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 35.164.1.178 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
  New status: update-failed
  !!!
  wait_ready timeout exceeded.
  !!!
  
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/ray/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/ray/autoscaler/_private/updater.py", line 134, in run
    self.do_update()
  File "/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/ray/autoscaler/_private/updater.py", line 299, in do_update
    self.wait_ready(deadline)
  File "/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/ray/autoscaler/_private/updater.py", line 248, in wait_ready
    raise Exception("wait_ready timeout exceeded.")
Exception: wait_ready timeout exceeded.
  Failed to setup head node.
```

**Comment by richardliaw** [comment]
@sasha-s can you provide some assistance here?

@msaroufim one other thing that would be helpful is to run this with `ray up -vvv` (increase to maximal verbosity).

If that still doesn't provide a good diagnostic, consider taking the ssh command that is printed out from the verbose mode and running it yourself, that usually helps uncover errors.

**Comment by sasha-s** [comment]
@msaroufim you mentioned the instance is available in AWS. can you connect to it using AWS console?
Also, does the issue go away, if you retry (as you described in #18755)?
Can you ssh to this any other aws instance manually?
