### ISSUE TITLE
[Rllib] AttributeError: 'NoneType' object has no attribute 'dtype' in state space

### ISSUE THREAD

**Issue by Jaimmmin** [ray-project/ray#19344]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

I try to customize an environment with state space,but when I set the state space with box, it comes up an error of "Nonetype"

### Versions / Dependencies

os: ubuntu16.04
python: 3.8
ray: 1.7.0
tensorflow: 2.6.0

### Reproduction script

Here is my init of the environment
>     def __init__(self,env_config):
>         self.b = 10
>         dimension = 2*self.b+1
>         self.action_space = gym.spaces.MultiDiscrete([2, 40])
>         observation_array_min = np.append([6.0 for i in range(self.b)],[0.0 for i in range(self.b)])
>         observation_array_min = np.append(observation_array_min,[0.0])
>         observation_array_max = np.append([28.5 for i in range(self.b)],[1.0 for i in range(self.b)])
>         observation_array_max = np.append(observation_array_max,[10.0])
>         self.observation_space = gym.spaces.box.Box(observation_array_min,observation_array_max,dtype=np.float)
>         self.reset()

### Anything else

Here is the error log:
> (pid=3791) 2021-10-13 14:07:14,126	ERROR worker.py:428 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::DQN.__init__() (pid=3791, ip=192.168.1.10)
> (pid=3791)   File "/home/jaimin/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 137, in __init__
> (pid=3791)     Trainer.__init__(self, config, env, logger_creator)
> (pid=3791)   File "/home/jaimin/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 611, in __init__
> (pid=3791)     super().__init__(config, logger_creator)
> (pid=3791)   File "/home/jaimin/anaconda3/envs/ray/lib/python3.8/site-packages/ray/tune/trainable.py", line 106, in __init__
> (pid=3791)     self.setup(copy.deepcopy(self.config))
> (pid=3791)   File "/home/jaimin/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 147, in setup
> (pid=3791)     super().setup(config)
> (pid=3791)   File "/home/jaimin/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 764, in setup
> (pid=3791)     self._init(self.config, self.env_creator)
> (pid=3791)   File "/home/jaimin/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 171, in _init
> (pid=3791)     self.workers = self._make_workers(
> (pid=3791)   File "/home/jaimin/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 846, in _make_workers
> (pid=3791)     return WorkerSet(
> (pid=3791)   File "/home/jaimin/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 103, in __init__
> (pid=3791)     self._local_worker = self._make_worker(
> (pid=3791)   File "/home/jaimin/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 399, in _make_worker
> (pid=3791)     worker = cls(
> (pid=3791)   File "/home/jaimin/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 459, in __init__
> (pid=3791)     _validate_env(self.env, env_context=self.env_context)
> (pid=3791)   File "/home/jaimin/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1529, in _validate_env
> (pid=3791)     env.observation_space.dtype != dummy_obs.dtype:
> (pid=3791) AttributeError: 'NoneType' object has no attribute 'dtype'
> Traceback (most recent call last):
>   File "/home/jaimin/PycharmProjects/VEC/VEC/trainMyEnv.py", line 6, in <module>
>     t = tune.run(
>   File "/home/jaimin/anaconda3/envs/ray/lib/python3.8/site-packages/ray/tune/tune.py", line 611, in run
>     raise TuneError("Trials did not complete", incomplete_trials)
> ray.tune.error.TuneError: ('Trials did not complete', [DQN_VECEnv_cdf31_00000])
> (DQN pid=3791) 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Jaimmmin** [comment]
I find in my reset function,  I don't return observation! After I return this attribute, the error disappeard.

>     def reset(self):
>         '''
>         reset the state of the environment
>         @return: state
>         '''
>         self.base_station = BaseStation(self.b)
>         self.observation = np.concatenate([self.base_station.Gb,self.base_station.reliability,self.base_station.Ntr])
>         self.done = False
>         self.step_num = 0
>         return self.observation
