### ISSUE TITLE
[Bug] Simple Ray Workflow on K8s cluster fails with: There is no context for resolving workflow outputs.

### ISSUE THREAD

**Issue by wdapalmazapata** [ray-project/ray#19397]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

I tried to run a sample Ray Workflow in a Ray Cluster running on K8s (via Ray Cluster Operator).
In order to do that, I used the following settings:

* used `kubectl` to expose the head node to my local driver.
`kubectl -n ray port-forward service/example-cluster-ray-head 10001:10001`

* used `ray.init(address="ray://127.0.0.1:10001")` first, to establish the connection with the head node.

* used a s3 bucket as storage for workflows:
`workflow.init(storage=f"s3://workflows-bucket/wfroot?endpoint_url={minio}&aws_access_key_id={access}&aws_secret_access_key={secret}")`

* attempted to run the sample workflow from the documentation
```
data = read_data.step(10)
preprocessed_data = preprocessing.step(data)
output = aggregate.step(preprocessed_data)
print(output.run("wf1"))
```

### Observed behavior:
The driver connects successfully to the cluster's head node.
The workflow storage is initialized with the S3 bucket.
The driver aborts execution while attempting to execute retrieve the workflow result.

```
% python workflow_example.py
2021-10-12 15:59:36,117	INFO services.py:1252 -- View the Ray dashboard at http://127.0.0.1:8265
2021-10-12 15:59:36,379	WARNING worker.py:1201 --
2021-10-12 15:59:36,698	INFO execution.py:35 -- Workflow job created. [id="wf1", storage_url="s3://workflows-bucket/wfroot?endpoint_url=..."].
Put failed:
Traceback (most recent call last):
  File "workflow_example.py", line 44, in <module>
    print(output.run("wf1"))
  File "venv-377/lib/python3.7/site-packages/ray/workflow/common.py", line 313, in run
    return ray.get(self.run_async(workflow_id))
  File "venv-377/lib/python3.7/site-packages/ray/workflow/common.py", line 347, in run_async
    return run(self, workflow_id)
  File "venv-377/lib/python3.7/site-packages/ray/workflow/execution.py", line 53, in run
    if entry_workflow.data.step_type != StepType.FUNCTION or not wf_exists:
  File "venv-377/lib/python3.7/site-packages/ray/workflow/common.py", line 274, in data
    self._data.inputs = self._prepare_inputs()
  File "venv-377/lib/python3.7/site-packages/ray/workflow/step_function.py", line 41, in prepare_inputs
    flattened_args)
  File "venv-377/lib/python3.7/site-packages/ray/workflow/serialization_context.py", line 215, in make_workflow_inputs
    input_placeholder: ray.ObjectRef = ray.put(args_list)
  File "venv-377/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 88, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "venv-377/lib/python3.7/site-packages/ray/util/client/api.py", line 51, in put
    return self.worker.put(*args, **kwargs)
  File "venv-377/lib/python3.7/site-packages/ray/util/client/worker.py", line 389, in put
    out = [self._put(x, client_ref_id=client_ref_id) for x in to_put]
  File "venv-377/lib/python3.7/site-packages/ray/util/client/worker.py", line 389, in <listcomp>
    out = [self._put(x, client_ref_id=client_ref_id) for x in to_put]
  File "venv-377/lib/python3.7/site-packages/ray/util/client/worker.py", line 403, in _put
    return self._put_pickled(data, client_ref_id)
  File "venv-377/lib/python3.7/site-packages/ray/util/client/worker.py", line 412, in _put_pickled
    raise cloudpickle.loads(resp.error)
ValueError: There is no context for resolving workflow outputs.
2021-10-12 15:59:37,102	INFO dataclient.py:110 -- Shutting down data channel
libc++abi: terminating
zsh: abort      python workflow_example.py
```

### Additional information
* the same test works when not running against the Ray cluster (using `ray.init()` to start an embedded single node)
* to validate the problem wasn't about connectivity from within the head node Pod and the S3 endpoint, I monitored the S3 requests showing the cluster is able to query the storage.

### Driver machine:
MacOS Intel
Python 3.7.7
Ray 1.7.0

### Ray Cluster
Local KinD cluster on MacOS
Ray Operator using default helm setting: `rayproject/ray:latest` @ 1.7.0 release

### Reproduction script

```
import ray, time
from ray import workflow
from typing import List

@workflow.step
def read_data(num: int):
    return [i for i in range(num)]

@workflow.step
def preprocessing(data: List[float]) -> List[float]:
    return [d**2 for d in data]

@workflow.step
def aggregate(data: List[float]) -> float:
    return sum(data)

# initialize ray with required modules (needed to run S3 workflow storage manager)
environment = { "pip": ["aioboto3"] }
ray.init(address="ray://127.0.0.1:10001", runtime_env=environment)

minio="http://mys3endpoint"
access="<user>"
secret="<secret>"

# Initialize workflow storage.
storage=f"s3://workflows-bucket/wfroot?endpoint_url={minio}&aws_access_key_id={access}&aws_secret_access_key={secret}"
workflow.init(storage=storage)

# Setup the workflow.
data = read_data.step(10)
preprocessed_data = preprocessing.step(data)
output = aggregate.step(preprocessed_data)

# Execute the workflow and print the result.
print(output.run("wf2"))

time.sleep(5)
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Therealchainman** [comment]
I had the same error message for a simple ray workflow as well using s3 storage.  Any progress on this bug?

**Comment by iycheng** [comment]
Close this one and use https://github.com/ray-project/ray/issues/21595 to track
