### ISSUE TITLE
Problems in java tests due to space in `launcher manifest.xml` file name

### ISSUE THREAD

**Issue by czgdp1807** [ray-project/ray#19457]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

On my Linux system, I get the following error message,

```java
+ popd
~/ray_project/ray
+ pushd /home/czgdp1807ssd/ray_project/ray/java/..
~/ray_project/ray ~/ray_project/ray
+ echo 'Build java maven deps.'
Build java maven deps.
+ bazel build //java:gen_maven_deps
DEBUG: /home/czgdp1807ssd/ray_project/ray/bazel/ray_deps_setup.bzl:66:14: No implicit mirrors used because urls were explicitly provided
INFO: Analyzed target //java:gen_maven_deps (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //java:gen_maven_deps up-to-date:
  bazel-bin/java/gen_maven_deps.out
INFO: Elapsed time: 1.002s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
+ echo 'Build test jar.'
Build test jar.
+ bazel build //java:all_tests_deploy.jar
DEBUG: /home/czgdp1807ssd/ray_project/ray/bazel/ray_deps_setup.bzl:66:14: No implicit mirrors used because urls were explicitly provided
INFO: Analyzed target //java:all_tests_deploy.jar (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/czgdp1807ssd/ray_project/ray/java/BUILD.bazel:167:12: Creating runfiles tree bazel-out/k8-opt/bin/java/all_tests.runfiles failed due to build-runfiles failed: error executing command 
  (cd /home/czgdp1807ssd/.cache/bazel/_bazel_czgdp1807ssd/cd3a5639cb96d6d56c34ea90982067b8/execroot/com_github_ray_project_ray && \
  exec env - \
    LANG=en_IN \
    LD_LIBRARY_PATH=:/usr/local/cuda-10.2/lib64:/home/czgdp1807ssd/lfortran_project/deps/build-zlib/lib:/home/czgdp1807ssd/lfortran_project/deps/build-binutils-2.36/lib:/home/czgdp1807ssd/lfortran_project/lfortran/src/runtime/liblfortran_runtime.so \
    PATH=/home/czgdp1807ssd/anaconda3/envs/ray_dev/bin:/home/czgdp1807ssd/anaconda3/condabin:/home/czgdp1807ssd/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda-10.2/bin:/usr/local/go/bin:/home/czgdp1807ssd/lfortran_project/deps/build-zlib/include:/home/czgdp1807ssd/Setups/cmake-3.19.4/bin/bin:/home/czgdp1807ssd/lfortran_project/deps/build-llvm/bin:/home/czgdp1807ssd/lfortran_project/deps/build-m4/bin:/home/czgdp1807ssd/lfortran_project/deps/build-bison-3.5/bin:/home/czgdp1807ssd/lfortran_project/deps/build-binutils-2.31.90/include:/home/czgdp1807ssd/lfortran_project/deps/build-re2c/bin:/home/czgdp1807ssd/lfortran_project/lfortran/src/bin:/usr/share/doc/git/contrib/diff-highlight/diff-highlight:/home/czgdp1807ssd/hugo_project \
  /home/czgdp1807ssd/.cache/bazel/_bazel_czgdp1807ssd/install/44512fe3341b8e62758dd7507a4e7ad1/build-runfiles bazel-out/k8-opt/bin/java/all_tests.runfiles_manifest bazel-out/k8-opt/bin/java/all_tests.runfiles): Process exited with status 1: Process exited with status 1
com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1
	at com.google.devtools.build.lib.shell.FutureCommandResult.get(FutureCommandResult.java:97)
	at com.google.devtools.build.lib.shell.Command.execute(Command.java:260)
	at com.google.devtools.build.lib.exec.SymlinkTreeHelper.createSymlinksUsingCommand(SymlinkTreeHelper.java:163)
	at com.google.devtools.build.lib.exec.SymlinkTreeStrategy.createSymlinks(SymlinkTreeStrategy.java:132)
	at com.google.devtools.build.lib.analysis.actions.SymlinkTreeAction.execute(SymlinkTreeAction.java:214)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:859)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1019)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:978)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:129)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:81)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:469)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:845)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:314)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
/home/czgdp1807ssd/.cache/bazel/_bazel_czgdp1807ssd/install/44512fe3341b8e62758dd7507a4e7ad1/build-runfiles (args bazel-out/k8-opt/bin/java/all_tests.runfiles_manifest bazel-out/k8-opt/bin/java/all_tests.runfiles): link or target filename contains space on line 7508: 'com_github_ray_project_ray/external/local_jdk/lib/python3.8/site-packages/setuptools/command/launcher manifest.xml /home/czgdp1807ssd/.cache/bazel/_bazel_czgdp1807ssd/cd3a5639cb96d6d56c34ea90982067b8/external/local_jdk/lib/python3.8/site-packages/setuptools/command/launcher manifest.xml'

Target //java:all_tests_deploy.jar failed to build
INFO: Elapsed time: 1.383s, Critical Path: 0.08s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully
```

I am using maven 3.6.3 and bazel 4.2.1 (though fails with 3.6.0 as well with same message). I expected the tests to start execution.

### Versions / Dependencies

Ray - Development version
Python - 3.8 from Anaconda
Bazel - 4.2.1 and 3.6.0
OS - Ubuntu 18.04
OpenJDK - 11.0.x

### Reproduction script

Under project root, execute,

`./java/test.sh`

Anaconda environment with Python 3.8 and latest OpenJDK available in `conda-forge` for Linux systems.

### Anything else

Every time I execute the above command. However on deleting the files with space in their name and then re-executing the command, the problem goes away. A hackish work around.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jovany-wang** [comment]
Did you use JDK11?

**Comment by czgdp1807** [comment]
> Did you use JDK11?

I used OpenJDK 11.0.x.

**Comment by jovany-wang** [comment]
Unfortunately we have not supported JDK11 right now.
