### ISSUE TITLE
Calling a remote function that creates tensorflow variables crashes in some cases 

### ISSUE THREAD

**Issue by avaziri** [ray-project/ray#1952]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.3 LTS
- **Ray installed from (source or binary)**: pip install
- **Ray version**: 0.4.0
- **Gym version**: 0.9.5
- **Python version**: 3.5.4
- **Exact command to reproduce**: see source code

### Describe the problem
There is seemingly inconsistent behavior in how tensorflow and remote tasks interact. When creating multiple tensor-flow graphs from the model catalog on the same device, there is a name conflict which causes a crash. I tried a variety of setups and got the following results:

- If you create multiple graphs with each one in a different actor everything is fine
- If you create multiple graphs in the same actor it causes a crash
- If you create multiple graphs with each one in a different remote function everything is fine with a small number of remote functions
- **Bug**: If you create multiple graphs with each one in a different remote function with a large number of remote functions then it causes a crash
- If you create a graph within an agent, then use a member function to create a second graph within that agent it causes a crash. 
- **Bug**: If you create a graph within an agent, then a member function of that agent calls a remote function that create a graph it causes a crash. This is unexpected to me, I thought the behavior of a remote function launched from the driver should be the same as a remote function launched from an actor.

### Source code 
```
mport ray
import gym
from ray.rllib.dqn import models
from ray.rllib.dqn import dqn

@ray.remote
def example_remote_function():
    env = gym.make("CartPole-v0")
    config = dqn.DEFAULT_CONFIG
    dqn_graph = models.DQNGraph(registry=None, env=env, config=config, logdir=None)   
    
@ray.remote
class ExampleActor:
    def __init__(self):
        env = gym.make("CartPole-v0")
        config = dqn.DEFAULT_CONFIG
        dqn_graph = models.DQNGraph(registry=None, env=env, config=config, logdir=None)
    def foo(self):
        env = gym.make("CartPole-v0")
        config = dqn.DEFAULT_CONFIG
        dqn_graph = models.DQNGraph(registry=None, env=env, config=config, logdir=None)
    def bar(self):
        return ray.get(example_remote_function.remote())  
        
ray.init()
actors = []
for x in range(2):
    actors.append(ExampleActor.remote())
print("Actors are :", actors)

remote_ids = []
# for x in range(40):
for x in range(2):
    remote_ids.append(example_remote_function.remote())
print("Object IDs returned from remote function are :", remote_ids)
ray.get(remote_ids)

remote_ids = []
for x in range(2):
    # remote_ids.append(actors[0].foo.remote())
    remote_ids.append(actors[0].bar.remote())
print("Object IDs returned from member function which uses remote function are :", remote_ids)
ray.get(remote_ids)
```
### Error
```
Remote function bar failed with:

Traceback (most recent call last):
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/ray/worker.py", line 821, in _process_task
    *arguments)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/ray/actor.py", line 212, in actor_method_executor
    method_returns = method(actor, *args)
  File "<ipython-input-1-4976ac708107>", line 23, in bar
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/ray/worker.py", line 2321, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(ccc85ed2efb62c11ae442a8d91b07a0f1ee7ffb0). It was created by remote function __main__.example_remote_function which failed with:

Remote function __main__.example_remote_function failed with:

Traceback (most recent call last):
  File "<ipython-input-1-4976ac708107>", line 10, in example_remote_function
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/ray/rllib/dqn/models.py", line 169, in __init__
    registry, self.cur_observations, num_actions, config)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/ray/rllib/dqn/models.py", line 17, in _build_q_network
    frontend = ModelCatalog.get_model(registry, inputs, 1, config["model"])
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/ray/rllib/models/catalog.py", line 156, in get_model
    return FullyConnectedNetwork(inputs, num_outputs, options)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/ray/rllib/models/model.py", line 38, in __init__
    inputs, num_outputs, options)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/ray/rllib/models/fcnet.py", line 33, in _init
    scope=label)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1639, in fully_connected
    outputs = layer.apply(inputs)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 671, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 559, in __call__
    self.build(input_shapes[0])
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/python/layers/core.py", line 137, in build
    trainable=True)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 458, in add_variable
    trainable=trainable and self.trainable)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1203, in get_variable
    constraint=constraint)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1092, in get_variable
    constraint=constraint)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 417, in get_variable
    return custom_getter(**custom_getter_kwargs)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1539, in layer_variable_getter
    return _model_variable_getter(getter, *args, **kwargs)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1531, in _model_variable_getter
    custom_getter=getter, use_resource=use_resource)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 262, in model_variable
    use_resource=use_resource)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 217, in variable
    use_resource=use_resource)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 742, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable tower/q_func/fc1/weights already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 217, in variable
    use_resource=use_resource)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/vaziri/.pyenv/versions/3.5.4/envs/3.5.4-venv/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 262, in model_variable
    use_resource=use_resource)

```

**Comment by robertnishihara** [comment]
I can reproduce the error more simply without actors, e.g., just

```python
import ray
import gym
from ray.rllib.dqn import models
from ray.rllib.dqn import dqn

@ray.remote
def example_remote_function():
    env = gym.make("CartPole-v0")
    config = dqn.DEFAULT_CONFIG
    dqn_graph = models.DQNGraph(registry=None, env=env, config=config, logdir=None)

ray.init(num_cpus=1)

ray.get(example_remote_function.remote())

ray.get(example_remote_function.remote())  # The second one will fail.
```

Note that I'm using `num_cpus=1` so that the two remote function calls get executed by the same worker.

The key issue is that TensorFlow leaves some "state" on the worker process that then causes problem for the second function execution. This can be addressed in two ways.

1. Specify that the worker should exit after executing `example_remote_function` so that state doesn't leak between the tasks. This can be done by changing the remote decorator to `@ray.remote(max_calls=1)`.

2. You can also create the model inside of a new TensorFlow graph to avoid pollution of the TensorFlow global variables. E.g., change the remote function implementation to do something like

    ```python
    import tensorflow as tf
    with tf.Graph().as_default():
        dqn_graph = models.DQNGraph(registry=None, env=env, config=config, logdir=None)
    ```

**Comment by avaziri** [comment]
Thanks, this seems to have worked. Is there a reason this is not the default behavior?
