### ISSUE TITLE
Evaluate fails for DQN with Atari Pong Env with '--video-dir' parameter

### ISSUE THREAD

**Issue by pfaeffli** [ray-project/ray#19581]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

**Goal**: I want to produce a video of a trained agent during evaluation.

**Behaviour**
`rllib evaluate` fails for Atari environment `PongNoFrameskip-v4` if parameter `--video-dir` is set.

**Correct behavior**
Video is created during evaluation in directory `--video-dir` and evaluation is performed.

**Error:**
```
Traceback (most recent call last):
  File "/usr/local/bin/rllib", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/scripts.py", line 38, in cli
    evaluate.run(options, evaluate_parser)
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/evaluate.py", line 353, in run
    rollout(agent, args.env, num_steps, num_episodes, saver,
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/evaluate.py", line 402, in rollout
    eval_result = agent.evaluate()["evaluation"]
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 946, in evaluate
    self.evaluation_workers.local_worker().sample()
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 752, in sample
    batches = [self.input_reader.next()]
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 103, in next
    batches = [self.get_data()]
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 233, in get_data
    item = next(self._env_runner)
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 586, in _env_runner
    base_env.poll()
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/env/base_env.py", line 417, in poll
    obs[i], rewards[i], dones[i], infos[i] = env_state.poll()
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/env/base_env.py", line 493, in poll
    for ag in observations.keys():
AttributeError: 'numpy.ndarray' object has no attribute 'keys'
```

### Versions / Dependencies

* ray: 1.7.0
* Python: 3.8
* Debian
* Gym: 0.21.0
* AutoROM: 0.4.2
* tensorflow: 2.6.0

Dockerfile:
```
FROM python:3.8.12-buster
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Zurich

RUN chmod -R 777 /tmp

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git gedit \
    build-essential libgl1-mesa-dev mesa-utils libgl1-mesa-glx libosmesa6-dev \
    python-opengl python3-opengl python3-gst-1.0 \
    ffmpeg xvfb vlc python3-tk --fix-missing && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN sed -i.bak 's/buster[^ ]* main$/& contrib non-free/g' /etc/apt/sources.list && \
    apt update && apt install -y unrar unzip && \
    curl -o /tmp/Roms.rar http://www.atarimania.com/roms/Roms.rar
RUN ls -al /tmp && \
    cd /tmp && \
    unrar x ./Roms.rar ./ && \
    find ./ -type f -name \*.zip -exec unzip {} \; && \
    find ./ -type d -name \*ROMS -exec python -m atari_py.import_roms {} \;

# Install tensorflow
RUN pip install pip --upgrade
RUN pip install tensorflow>=2.6.0

# RUN git clone https://github.com/openai/gym
# RUN cd gym && pip install -e .

# Add pip packages
RUN pip install imageio==2.4.0 PILLOW pyglet pyvirtualdisplay gym['atari, accept-rom-license'] ray[rllib] autorom
```

### Reproduction script

Run training
```
rllib train --run=DQN --env=PongNoFrameskip-v4 -v --checkpoint-freq 1 --config='{\"train_batch_size\": 2}'
```
Abort after 5 episodes. Run evaluate:
```
rllib evaluate ~/ray_results/default/DQN_PongNoFrameskip-v4_<Date>/checkpoint_000005/checkpoint-5 --run=DQN --env=PongNoFrameskip-v4 --episodes 10  --video-dir ~/data/video
```
Will fail with error mentioned above.

### Anything else

Debugging led me to the following file: `ray/rllib/env/base_env.py, line 493`
```
class _MultiAgentEnvState:
    ...

    def poll(
            self
    ) -> Tuple[MultiAgentDict, MultiAgentDict, MultiAgentDict, MultiAgentDict]:
        ...

        observations = self.last_obs
        rewards = {}
        dones = {"__all__": self.last_dones["__all__"]}
        infos = {}

        # If episode is done, release everything we have.
        if dones["__all__"]:
             ...
        else:
            for ag in observations.keys():
                ....
```
Variable `observations` is expected to be a `dict` but is a `numpy.ndarray: (84, 84, 4)`.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by axelahmer** [comment]
I am having the exact same problem. Ray 1.6 is running, but 1.7+ is failing.
