### ISSUE TITLE
Run Ray Java code Error!

### ISSUE THREAD

**Issue by wangzy0327** [ray-project/ray#19689]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

When I package java jar with Ray code,I get errors as below:

java -jar ray-java-demo-1.0-SNAPSHOT-jar-with-dependencies.jar --port=6380

Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library '/tmp/ray/1635143478305/libcore_worker_library_java.so':
/lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/ray/1635143478305/libcore_worker_library_java.so)
/lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/ray/1635143478305/libcore_worker_library_java.so)
Native library (tmp/ray/1635143478305/libcore_worker_library_java.so) not found in resource path ([file:/home/wzy/ray-java-demo/target/ray-java-demo-1.0-SNAPSHOT-jar-with-dependencies.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:397)
	at io.ray.runtime.util.JniUtils.loadLibrary(JniUtils.java:72)
	at io.ray.runtime.RayNativeRuntime.start(RayNativeRuntime.java:71)
	at io.ray.runtime.DefaultRayRuntimeFactory.createRayRuntime(DefaultRayRuntimeFactory.java:39)
	at io.ray.api.Ray.init(Ray.java:39)
	at io.ray.api.Ray.init(Ray.java:26)
	at com.test.ray.MyRayApp.main(MyRayApp.java:8)
	Suppressed: java.lang.UnsatisfiedLinkError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/ray/1635143478305/libcore_worker_library_java.so)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 8 more
	Suppressed: java.lang.UnsatisfiedLinkError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/ray/1635143478305/libcore_worker_library_java.so)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 8 more
	Suppressed: java.io.IOException: Native library (tmp/ray/1635143478305/libcore_worker_library_java.so) not found in resource path ([file:/home/wzy/ray-java-demo/target/ray-java-demo-1.0-SNAPSHOT-jar-with-dependencies.jar])
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
		... 8 more

### Use case

java -jar ray-java-demo-1.0-SNAPSHOT-jar-with-dependencies.jar --port=6380

### Related issues

2021-10-25 02:31:18,300 INFO RunManager [main]: Ray runtime started @ 172.17.0.1.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library '/tmp/ray/1635143478305/libcore_worker_library_java.so':
/lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/ray/1635143478305/libcore_worker_library_java.so)
/lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/ray/1635143478305/libcore_worker_library_java.so)
Native library (tmp/ray/1635143478305/libcore_worker_library_java.so) not found in resource path ([file:/home/wzy/ray-java-demo/target/ray-java-demo-1.0-SNAPSHOT-jar-with-dependencies.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:397)
	at io.ray.runtime.util.JniUtils.loadLibrary(JniUtils.java:72)
	at io.ray.runtime.RayNativeRuntime.start(RayNativeRuntime.java:71)
	at io.ray.runtime.DefaultRayRuntimeFactory.createRayRuntime(DefaultRayRuntimeFactory.java:39)
	at io.ray.api.Ray.init(Ray.java:39)
	at io.ray.api.Ray.init(Ray.java:26)
	at com.test.ray.MyRayApp.main(MyRayApp.java:8)
	Suppressed: java.lang.UnsatisfiedLinkError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/ray/1635143478305/libcore_worker_library_java.so)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 8 more
	Suppressed: java.lang.UnsatisfiedLinkError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/ray/1635143478305/libcore_worker_library_java.so)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 8 more
	Suppressed: java.io.IOException: Native library (tmp/ray/1635143478305/libcore_worker_library_java.so) not found in resource path ([file:/home/wzy/ray-java-demo/target/ray-java-demo-1.0-SNAPSHOT-jar-with-dependencies.jar])
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
		... 8 more

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by jovany-wang** [comment]
Feel free reopen this once there still be issue.
