### ISSUE TITLE
[Bug] Tune training throws a ValueError: The parameter logits has invalid values In tower 0 on device cuda:0

### ISSUE THREAD

**Issue by Hsgngr** [ray-project/ray#19696]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

This is the error that I'm getting while I try to use tune.run():
```
Failure # 1 (occurred at 2021-10-25_12-10-18)
Traceback (most recent call last):
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 812, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 767, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/worker.py", line 1621, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): [36mray::PPO.train()[39m (pid=22781, ip=10.128.0.11, repr=PPO)
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/rllib/agents/ppo/ppo_torch_policy.py", line 46, in ppo_surrogate_loss
    curr_action_dist = dist_class(logits, model)
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/rllib/models/torch/torch_action_dist.py", line 100, in __init__
    self.cats = [
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/rllib/models/torch/torch_action_dist.py", line 101, in <listcomp>
    torch.distributions.categorical.Categorical(logits=input_)
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/torch/distributions/categorical.py", line 64, in __init__
    super(Categorical, self).__init__(batch_shape, validate_args=validate_args)
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/torch/distributions/distribution.py", line 53, in __init__
    raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter logits has invalid values

The above exception was the direct cause of the following exception:

[36mray::PPO.train()[39m (pid=22781, ip=10.128.0.11, repr=PPO)
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 670, in train
    raise e
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 656, in train
    result = Trainable.train(self)
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/tune/trainable.py", line 248, in train
    result = self.step()
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 206, in step
    step_results = next(self.train_exec_impl)
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/util/iter.py", line 791, in apply_foreach
    result = fn(item)
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/rllib/execution/train_ops.py", line 191, in __call__
    batch_fetches = policy.learn_on_loaded_batch(
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/rllib/policy/torch_policy.py", line 624, in learn_on_loaded_batch
    tower_outputs = self._multi_gpu_parallel_grad_calc(device_batches)
  File "/opt/conda/envs/rl/lib/python3.8/site-packages/ray/rllib/policy/torch_policy.py", line 1021, in _multi_gpu_parallel_grad_calc
    raise last_result[0] from last_result[1]
ValueError: The parameter logits has invalid values
In tower 0 on device cuda:0

```

This is the code I run:
```
analysis = tune.run(ppo.PPOTrainer,
                                config=self.config,
                                scheduler= pbt,
                                local_dir=self.save_dir,
                                stop=stop_criteria,
                                checkpoint_at_end=True,
                                num_samples=7
                                checkpoint_freq=10

                            )
```

This is the console:
```
== Status ==
Memory usage on this node: 23.9/59.0 GiB
PopulationBasedTraining: 72 checkpoints, 62 perturbs
Resources requested: 12.0/15 CPUs, 0.857142857142857/1 GPUs, 0.0/33.34 GiB heap, 0.0/16.67 GiB objects (0.0/1.0 accelerator_type:T4)
Result logdir: /home/ege/SENTIMENTGYM/training_model_checkpoint/PPO_2021-10-25_11-17-45
Number of trials: 7/7 (1 ERROR, 6 RUNNING)
+---------------------------+----------+-------------------+--------------+----------+----------------+--------+------------------+--------+-----------+----------------------+----------------------+--------------------+
| Trial name                | status   | loc               |   clip_param |   lambda |   num_sgd_iter |   iter |   total time (s) |     ts |    reward |   episode_reward_max |   episode_reward_min |   episode_len_mean |
|---------------------------+----------+-------------------+--------------+----------+----------------+--------+------------------+--------+-----------+----------------------+----------------------+--------------------|
| PPO_stock_gym_2d8f4_00000 | RUNNING  | 10.128.0.11:30233 |     0.344196 | 0.930654 |             26 |     85 |          4505.73 | 340000 |   8.8455  |              32.5411 |            -37.0172  |               2880 |
| PPO_stock_gym_2d8f4_00001 | RUNNING  | 10.128.0.11:17865 |     0.430245 | 0.775545 |             22 |     88 |          4646.37 | 352000 |  18.2872  |              81.6896 |             -8.47571 |               2880 |
| PPO_stock_gym_2d8f4_00002 | RUNNING  | 10.128.0.11:30601 |     0.274802 | 0.914129 |             31 |     88 |          4680.86 | 352000 |  23.0065  |              82.0458 |             -6.55258 |               2880 |
| PPO_stock_gym_2d8f4_00003 | RUNNING  | 10.128.0.11:17578 |     0.413035 | 0.744524 |             20 |     86 |          4654.51 | 344000 |   5.21519 |              25.3225 |            -38.6317  |               2880 |
| PPO_stock_gym_2d8f4_00005 | RUNNING  | 10.128.0.11:2736  |     0.219842 | 1.09696  |             18 |     87 |          4601.44 | 348000 |  14.0045  |              20.5376 |              7.47136 |               2880 |
| PPO_stock_gym_2d8f4_00006 | RUNNING  | 10.128.0.11:3436  |     0.413035 | 1.11679  |             18 |     84 |          4437.69 | 336000 | -50.0697  |             -50.0697 |            -50.0697  |               2880 |
| PPO_stock_gym_2d8f4_00004 | ERROR    |                   |     0.575288 | 1.58814  |             24 |     43 |          2413.3  | 172000 |  16.3407  |              79.8176 |            -25.671   |               2880 |
+---------------------------+----------+-------------------+--------------+----------+----------------+--------+------------------+--------+-----------+----------------------+----------------------+--------------------+
Number of errored trials: 1
+---------------------------+--------------+------------------------------------------------------------------------------------------------------------------------------------+
| Trial name                |   # failures | error file                                                                                                                         |
|---------------------------+--------------+------------------------------------------------------------------------------------------------------------------------------------|
| PPO_stock_gym_2d8f4_00004 |            1 | /home/ege/SENTIMENTGYM/training_model_checkpoint/PPO_2021-10-25_11-17-45/PPO_stock_gym_2d8f4_00004_4_2021-10-25_11-17-45/error.txt |
+---------------------------+--------------+------------------------------------------------------------------------------------------------------------------------------------+
```

### Versions / Dependencies

I'm using GCP, conda and torch for my training and intergation with tune. 16 cpu an 1 GPU 

```
# Name                    Version                   Build  Channel
torch                     1.9.0                    pypi_0    pypi
ray                       1.7.0                    pypi_0    pypi
```
```
Mon Oct 25 12:44:03 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   77C    P0    46W /  70W |   6641MiB / 15109MiB |     12%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     17578      C   ray::PPO.train()                 1107MiB |
|    0   N/A  N/A     17865      C   ray::PPO.train()                 1107MiB |
|    0   N/A  N/A     21200      C   ray::PPO.train()                 1107MiB |
|    0   N/A  N/A     26873      C   ray::PPO.train()                 1107MiB |
|    0   N/A  N/A     30233      C   ray::PPO.train()                 1105MiB |
|    0   N/A  N/A     30601      C   ray::PPO.train()                 1105MiB |
+-----------------------------------------------------------------------------+
```

### Reproduction script

```
 rl_config = {
            "env": 'stock_gym',
            "env_config": env_config, 
            "num_gpus":1/7,
            "num_workers":1,
            "num_cpus_per_worker":1,
            "framework": "torch",
            "callbacks": MyCallbacks,
            "model": {
                "use_lstm": True,
                "lstm_cell_size": 16,
                "fcnet_hiddens": [8192 , 8192],
                "fcnet_activation" : "relu",
                "conv_filters":None,
            },
            "lr": 5e-5,
                    
        }
    mutations = {
    "lambda": lambda: random.uniform(0.95, 1.0),
    "clip_param": lambda: random.uniform(0.01, 0.5),
    "lr": tune.choice([1e-4, 5e-5, 1e-5]),
    "num_sgd_iter": lambda: random.randint(10, 30),
    #"train_batch_size": lambda: random.randint(2000,16000)
    }

    pbt = PopulationBasedTraining(
        time_attr="time_total_s",
        perturbation_interval=120,
        metric="episode_reward_min",
        mode="max",
        #resample_probability=0.25,
        hyperparam_mutations=mutations
        #custom_explore_fn=explore
        )

analysis = tune.run(ppo.PPOTrainer,
                                config=self.config,
                                scheduler= pbt,
                                local_dir=self.save_dir,
                                stop=stop_criteria,
                                checkpoint_at_end=True,
                                num_samples=NUM_SAMPLES,
                                checkpoint_freq=10

                            )
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Hsgngr** [comment]
Have you find a solution for this problem ? @Athe-kunal
