### ISSUE TITLE
Error in Ray + TensorFlow documentation.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#197]
Running the example code under **Complete Example** on this page https://github.com/ray-project/ray/blob/master/doc/using-ray-with-tensorflow.md works for me.

However, if I run the first box of code beforehand (pasted below)

```python
import tensorflow as tf
import numpy as np

x_data = tf.placeholder(tf.float32, shape=[100])
y_data = tf.placeholder(tf.float32, shape=[100])

w = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.zeros([1]))
y = w * x_data + b

loss = tf.reduce_mean(tf.square(y - y_data))
optimizer = tf.train.GradientDescentOptimizer(0.5)
train = optimizer.minimize(loss)

init = tf.initialize_all_variables()
sess = tf.Session()
```

then the example fails with errors like

```python
Remote function __main__.step failed with:

Traceback (most recent call last):
  File "<ipython-input-2-bbe208aec82f>", line 45, in step
  File "/Users/rkn/Workspace/ray/lib/python/ray/experimental/tfutils.py", line 78, in set_weights
    self.sess.run(self.assignment_nodes, feed_dict={self.assignment_placeholders[name]: value for (name, value) in new_weights.items()})
  File "/Users/rkn/Workspace/ray/lib/python/ray/experimental/tfutils.py", line 78, in <dictcomp>
    self.sess.run(self.assignment_nodes, feed_dict={self.assignment_placeholders[name]: value for (name, value) in new_weights.items()})
KeyError: 'Variable_2'


You can inspect errors by running

    ray.error_info()

If this driver is hanging, start a new one with

    ray.init(redis_address="127.0.0.1:39461")
```

The problem seems to be that we are using the default TensorFlow variable names, which are out of sync on the driver and the workers because we have run some additional TensorFlow code on the driver.

**Comment by robertnishihara** [comment]
This was addressed by #199.
