### ISSUE TITLE
[Serve] `@serve.deployments(ray_actor_options={"num_cpus": 0})` doesn't work

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#19771]
```
(ServeController pid=12680) 2021-10-26 19:03:28,704     INFO backend_state.py:911 -- Adding 1 replicas to deployment 'hello'. component=serve deployment=hello
(ServeController pid=12680) 2021-10-26 19:03:28,704     ERROR controller.py:193 -- Exception updating backend state.
(ServeController pid=12680) Traceback (most recent call last):
(ServeController pid=12680)   File "/Users/simonmo/Desktop/ray/ray/python/ray/serve/controller.py", line 191, in run_control_loop
(ServeController pid=12680)     self.backend_state_manager.update()
(ServeController pid=12680)   File "/Users/simonmo/Desktop/ray/ray/python/ray/serve/backend_state.py", line 1355, in update
(ServeController pid=12680)     deleted = backend_state.update()
(ServeController pid=12680)   File "/Users/simonmo/Desktop/ray/ray/python/ray/serve/backend_state.py", line 1114, in update
(ServeController pid=12680)     running_replicas_changed = self._scale_backend_replicas()
(ServeController pid=12680)   File "/Users/simonmo/Desktop/ray/ray/python/ray/serve/backend_state.py", line 921, in _scale_backend_replicas
(ServeController pid=12680)     self._target_version)
(ServeController pid=12680)   File "/Users/simonmo/Desktop/ray/ray/python/ray/serve/backend_state.py", line 374, in start
(ServeController pid=12680)     self._actor.start(backend_info, version)
(ServeController pid=12680)   File "/Users/simonmo/Desktop/ray/ray/python/ray/serve/backend_state.py", line 164, in start
(ServeController pid=12680)     self._placement_group_name, self._actor_resources)
(ServeController pid=12680)   File "/Users/simonmo/Desktop/ray/ray/python/ray/serve/backend_state.py", line 138, in create_placement_group
(ServeController pid=12680)     name=placement_group_name)
(ServeController pid=12680)   File "/Users/simonmo/Desktop/ray/ray/python/ray/_private/client_mode_hook.py", line 150, in wrapper
(ServeController pid=12680)     return func(*args, **kwargs)
(ServeController pid=12680)   File "/Users/simonmo/Desktop/ray/ray/python/ray/util/placement_group.py", line 203, in placement_group
(ServeController pid=12680)     "Bundles cannot be an empty dictionary or "
(ServeController pid=12680) ValueError: Bundles cannot be an empty dictionary or resources with only 0 values. Bundles: [{'CPU': 0, 'GPU': 0, 'memory': 0, 'object_store_memory': 0}]

```

```python
    @serve.deployment(ray_actor_options={"num_cpus": 0})
    def hello(_):
        return "hello"
```

**Comment by iasoon** [comment]
What would expected behaviour here? As the error states, this results from trying to create a placement group with no resources associated. To resolve this issue we would either need to allow this in ray core, or not associate a placement group with a replica in this instance. I'm not sure whether it's fine to do the latter - I think this would result in different behaviour compared to deployments that do have resources allocated.

**Comment by simon-mo** [comment]
I would suggest either:
- not associate a placement group with a replica in this instance (as you said) (preferred)
- or completely disallow this behavior in serve validation path.

@edoakes thoughts?

**Comment by edoakes** [comment]
Prefer to not associate it with a placement group for now, but we should probably in parallel add support for a placement group with no resources (I'm sure others will run into this too). Let me file an issue but let's go ahead with the hackier solution for now.
