### ISSUE TITLE
[runtime_env] Client connection fails with `TimeoutError: CreateRuntimeEnv request failed after 5 attempts.` when using working dir with different file system on head node

### ISSUE THREAD

**Issue by ckw017** [ray-project/ray#19792]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

The following script fails when connecting to a cluster with a different file system than the client:

```python
# test.py
import ray

# Replace this with a valid dir on your machine
d = "REPLACEME"
j = ray.job_config.JobConfig(runtime_env={"working_dir": d})
ray.util.connect("localhost:10001", job_config=j)
print("Done!")
```

on my machine, hangs for ~30 secs then:
```
Traceback (most recent call last):
  File "test2.py", line 4, in <module>
    ray.util.connect("localhost:10001", job_config=j)
  File "/Users/cwong/anaconda3/envs/ray38/lib/python3.8/site-packages/ray/util/client_connect.py", line 33, in connect
    conn = ray.connect(
  File "/Users/cwong/anaconda3/envs/ray38/lib/python3.8/site-packages/ray/util/client/__init__.py", line 221, in connect
    conn = self.get_context().connect(*args, **kw_args)
  File "/Users/cwong/anaconda3/envs/ray38/lib/python3.8/site-packages/ray/util/client/__init__.py", line 81, in connect
    self.client_worker._server_init(job_config, ray_init_kwargs)
  File "/Users/cwong/anaconda3/envs/ray38/lib/python3.8/site-packages/ray/util/client/worker.py", line 705, in _server_init
    raise ConnectionAbortedError(
ConnectionAbortedError: Initialization failure from server:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ray/util/client/server/proxier.py", line 622, in Datapath
    if not self.proxy_manager.start_specific_server(
  File "/usr/local/lib/python3.8/dist-packages/ray/util/client/server/proxier.py", line 279, in start_specific_server
    serialized_runtime_env_context = self._create_runtime_env(
  File "/usr/local/lib/python3.8/dist-packages/ray/util/client/server/proxier.py", line 258, in _create_runtime_env
    raise TimeoutError(
TimeoutError: CreateRuntimeEnv request failed after 5 attempts.
```

### Versions / Dependencies

Python 3.8
Ray commit 99a00882337e85589a8fbc193b8ec77846a4dd6a
MacOS client, Ubuntu head node

### Reproduction script

Repro is done by running the head node in docker and connecting client from host machine

### docker setup
```
docker pull ubuntu
docker run -p 10001:10001 -it ubuntu
```

### Inside the container
```
apt-get -y update
apt-get -y install python3
apt-get -y install python3-pip
apt-get -y install wget
wget https://ray-wheels.s3.us-west-2.amazonaws.com/master/99a00882337e85589a8fbc193b8ec77846a4dd6a/ray-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl
pip install ./ray-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl[default]
ray start --head 
```

### In host shell
```
pip install https://ray-wheels.s3.us-west-2.amazonaws.com/master/99a00882337e85589a8fbc193b8ec77846a4dd6a/ray-2.0.0.dev0-cp38-cp38-macosx_10_15_x86_64.whl
python test.py 
```

### sanity check
inside docker:
```
pip install 'ray[default]==1.7.1'
ray stop
ray start --head
```

on local machine:
```
pip install 'ray[default]==1.7.1'
python test.py
```

This works, (prints "Done!")

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wjrforcyber** [comment]
> @architkulkarni Sorry to piggyback on this issue but the repro is 95% the same:
> 
> After doing the original setup in docker, and then:
> 
> ```
> ray stop
> pip install pydantic
> pip install ./ray-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl[default,serve]
> ray start --head
> ```
> 
> `python test.py` works the first time
> 
> After a second run of `python test.py`:
> 
> ```
> l^CTraceback (most recent call last):
>   File "/Users/cwong/anaconda3/envs/timeouttest/lib/python3.8/site-packages/ray/util/client/__init__.py", line 81, in connect
>     self.client_worker._server_init(job_config, ray_init_kwargs)
>   File "/Users/cwong/anaconda3/envs/timeouttest/lib/python3.8/site-packages/ray/util/client/worker.py", line 705, in _server_init
>     raise ConnectionAbortedError(
> ConnectionAbortedError: Initialization failure from server:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/ray/util/client/server/proxier.py", line 627, in Datapath
>     raise RuntimeError(
> RuntimeError: Starting Ray client server failed. See ray_client_server_23001.err for detailed logs.
> ```
> 
> ray_client_server_23001.err:
> 
> ```
> bash: line 0: cd: /tmp/ray/session_2021-10-27_21-36-58_923820_4931/runtime_resources/_ray_pkg_d9: No such file or directory
> ```

I am still seeing this issue on macOS 
macOs Monterey, version 12.5
chip Apple M2
Memory 24 GB
ray 1.13.0
My error message:

```
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/venv/lib/python3.9/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/venv/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/opt/homebrew/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/venv/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/venv/lib/python3.9/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/venv/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/opt/homebrew/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/./eda_design_flow/main.py", line 17, in <module>
    init_ray()
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/./eda_design_flow/utils.py", line 6, in init_ray
    return ray.init(address='ray://localhost:10001',dashboard_host='0.0.0.0',dashboard_port=8265)
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/venv/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/venv/lib/python3.9/site-packages/ray/worker.py", line 887, in init
    return builder.connect()
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/venv/lib/python3.9/site-packages/ray/client_builder.py", line 160, in connect
    client_info_dict = ray.util.client_connect.connect(
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/venv/lib/python3.9/site-packages/ray/util/client_connect.py", line 36, in connect
    conn = ray.connect(
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/venv/lib/python3.9/site-packages/ray/util/client/__init__.py", line 243, in connect
    conn = self.get_context().connect(*args, **kw_args)
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/venv/lib/python3.9/site-packages/ray/util/client/__init__.py", line 94, in connect
    self.client_worker._server_init(job_config, ray_init_kwargs)
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/venv/lib/python3.9/site-packages/ray/util/client/worker.py", line 811, in _server_init
    raise ConnectionAbortedError(
ConnectionAbortedError: Initialization failure from server:
Traceback (most recent call last):
  File "/opt/eda-venv/lib/python3.8/site-packages/ray/util/client/server/proxier.py", line 664, in Datapath
    raise RuntimeError(
RuntimeError: Starting Ray client server failed. See ray_client_server_23000.err for detailed logs.
```

**Comment by architkulkarni** [comment]
Hi @wjrforcyber, do you have any more details about your workload?  Are there any relevant logs in `/tmp/ray/session_latest/logs/ray_client_server_23000.err`?

**Comment by wjrforcyber** [comment]
> Hi @wjrforcyber, do you have any more details about your workload? Are there any relevant logs in `/tmp/ray/session_latest/logs/ray_client_server_23000.err`?

I found another issue with the [exact same log here](https://github.com/ray-project/ray/issues/18876) but no more discuss and bot had the issue closed. I think it's still a M2 chip issue.

**Comment by architkulkarni** [comment]
@wjrforcyber got it, let's keep this issue for the `runtime_env` dependency error, and move this discussion to the other issue.

**Comment by aleeve** [comment]
Hi! Thanks for the great software!

Sorry if this is the wrong issue for this. I'm hitting 
`RuntimeError: Starting Ray client server failed. See ray_client_server_23004.err for detailed logs.
`
in different ways when passing in py_modules as the runtime_env. One time I accidentally tried to load a numpy version different from that on the node causing openblas mixup, and another time a subpackage of jedi  called subprocess got imported as a toplevel package which created a circular dependency.

 I wanted to pass the full env to a "blank" worker which was perhaps not super. Do you think you will add more extensive import guards or is the docker image runtime my best bet?
