### ISSUE TITLE
RLlib example w/ gym import doesn't work

### ISSUE THREAD

**Issue by worldveil** [ray-project/ray#20002]
From [this example](https://docs.ray.io/en/latest/rllib-training.html#accessing-model-state):

```python
>>> import gym
>>> env = gym.make("Pong-v0")
Traceback (most recent call last):
  File "/Users/will/opt/anaconda3/envs/ray-docs/lib/python3.7/site-packages/gym/envs/registration.py", line 158, in spec
    return self.env_specs[id]
KeyError: 'Pong-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/will/opt/anaconda3/envs/ray-docs/lib/python3.7/site-packages/gym/envs/registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "/Users/will/opt/anaconda3/envs/ray-docs/lib/python3.7/site-packages/gym/envs/registration.py", line 128, in make
    spec = self.spec(path)
  File "/Users/will/opt/anaconda3/envs/ray-docs/lib/python3.7/site-packages/gym/envs/registration.py", line 203, in spec
    raise error.UnregisteredEnv("No registered env with id: {}".format(id))
gym.error.UnregisteredEnv: No registered env with id: Pong-v0
```

**Comment by sven1977** [comment]
This is due to a recent gym upgrade (to 0.21, I believe).
The solution is to pip install these up front:

```
pip install "gym[atari]" "gym[accept-rom-license]" atari_py
```

**Comment by sven1977** [comment]
The following is working now in a completely fresh env:
```
$ conda create -n rllib python=3.8
$ conda activate rllib
$ pip install "ray[rllib]" tensorflow torch
```

```
from ray.rllib.agents.ppo import PPOTrainer

trainer = PPOTrainer(env="Taxi-v3")

for _ in range(3):
    print(trainer.train())
```

**Comment by worldveil** [comment]
Created PR to fix this
https://github.com/ray-project/ray/pull/20225
