### ISSUE TITLE
[Bug] [ray client] ray.util.client.ray.get will change the type of exception

### ISSUE THREAD

**Issue by Catch-Bull** [ray-project/ray#20103]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

I use MLDataset with Ray Client, I got an exception as follower when I try to get whole shard data:
```  bash
---------------------------------------------------------------------------
RayTaskError(StopIteration)               Traceback (most recent call last)
RayTaskError(StopIteration): ray::ParallelIteratorWorker.par_iter_next_batch() (pid=400794, ip=11.72.5.236)
  File "python/ray/_raylet.pyx", line 515, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 447, in ray._raylet.execute_task.function_executor
  File "/home/admin/.local/lib/python3.7/site-packages/ray/util/iter.py", line 1158, in par_iter_next_batch
    batch.append(self.par_iter_next())
  File "/home/admin/.local/lib/python3.7/site-packages/ray/util/iter.py", line 1152, in par_iter_next
    return next(self.local_it)
StopIteration

~/miniconda3/lib/python3.7/site-packages/mars/dataframe/datasource/read_raydataset.py in read_ray_mldataset(mldataset, **kwargs)
     96     df_record: pd.DataFrame = not_empty_dfs[0]
     97     columns = df_record.columns.names
---> 98     nrows = sum(mldataset.for_each(lambda df: len(df)).gather_async())
     99 
    100     op = DataFrameReadMLDataset(mldataset=mldataset, columns=columns, nrows=nrows)

~/miniconda3/lib/python3.7/site-packages/ray/util/iter.py in base_iterator(timeout)
    549                     try:
    550                         local_iter.shared_metrics.get().current_actor = actor
--> 551                         batch = ray.get(obj_ref)
    552                         futures[actor.par_iter_next_batch.remote(
    553                             batch_ms)] = actor

~/miniconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
     44     def wrapper(*args, **kwargs):
     45         if client_mode_should_convert():
---> 46             return getattr(ray, func.__name__)(*args, **kwargs)
     47         return func(*args, **kwargs)
     48 

~/miniconda3/lib/python3.7/site-packages/ray/util/client/api.py in get(self, vals, timeout)
     33             timeout: Optional timeout in milliseconds
     34         """
---> 35         return self.worker.get(vals, timeout=timeout)
     36 
     37     def put(self, *args, **kwargs):

~/miniconda3/lib/python3.7/site-packages/ray/util/client/worker.py in get(self, vals, timeout)
    172         if timeout is None:
    173             timeout = 0
--> 174         out = [self._get(x, timeout) for x in to_get]
    175         if single:
    176             out = out[0]

~/miniconda3/lib/python3.7/site-packages/ray/util/client/worker.py in <listcomp>(.0)
    172         if timeout is None:
    173             timeout = 0
--> 174         out = [self._get(x, timeout) for x in to_get]
    175         if single:
    176             out = out[0]

~/miniconda3/lib/python3.7/site-packages/ray/util/client/worker.py in _get(self, ref, timeout)
    190                 raise
    191             logger.error(err)
--> 192             raise err
    193         return loads_from_server(data.data)
    194 

/home/admin/.local/lib/python3.7/site-packages/ray/util/client/server/server.py in _get_object()

/usr/local/python3/lib/python3.7/contextlib.py in __exit__()

RuntimeError: generator raised StopIteration
```
I expected no error will be reported (Mldataset get StopIteration), but I get RuntimeError

### Versions / Dependencies

```bash
python 3.7.9
ray 1.7.1
```

### Reproduction script

``` python
from ray.util.client import ray
ray.init()
@ray.remote
def test():
    raise StopIteration
ray.get(test.remote())
```
Traceback:
``` python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-9ce49d69e440> in <module>
      4 def test():
      5     raise StopIteration
----> 6 ray.get(test.remote())

~/.pyenv/versions/3.7.8/envs/mars-378/lib/python3.7/site-packages/ray/util/client/api.py in get(self, vals, timeout)
     39             timeout: Optional timeout in milliseconds
     40         """
---> 41         return self.worker.get(vals, timeout=timeout)
     42 
     43     def put(self, *args, **kwargs):

~/.pyenv/versions/3.7.8/envs/mars-378/lib/python3.7/site-packages/ray/util/client/worker.py in get(self, vals, timeout)
    348                 op_timeout = MAX_BLOCKING_OPERATION_TIME_S
    349             try:
--> 350                 res = self._get(to_get, op_timeout)
    351                 break
    352             except GetTimeoutError:

~/.pyenv/versions/3.7.8/envs/mars-378/lib/python3.7/site-packages/ray/util/client/worker.py in _get(self, ref, timeout)
    375                 logger.exception("Failed to deserialize {}".format(data.error))
    376                 raise
--> 377             raise err
    378         return loads_from_server(data.data)
    379 

RuntimeError: generator raised StopIteration
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by fyrestone** [comment]
> PEP 479 is enabled for all code in Python 3.7, meaning that StopIteration exceptions raised directly or indirectly in coroutines and generators are transformed into RuntimeError exceptions. (Contributed by Yury Selivanov in bpo-32670.)

from https://docs.python.org/3/whatsnew/3.7.html#changes-in-python-behavior
