### ISSUE TITLE
mismatch of Ray versions causes redis error on starting Ray

### ISSUE THREAD

**Issue by worldveil** [ray-project/ray#20166]
Same as this issue: https://github.com/ray-project/ray/issues/18443

Repro:

```bash
% git clone git@github.com:anyscale/cuj-rl-in-production.git ./repro
% cd repro
% source env.sh error_repro
% ray stop
% ray start --head
% python cuj.py  --as-test
Running with following CLI options: Namespace(as_test=True, cluster_compute_id='cpt_qtS7N1d5tdXvKhemXhGVUaGX', cluster_env_id='bld_LQZSjdJhvFhzCsujCkP4gH1Y', cluster_name='', local_mode=False, num_samples=10, project_id='', stop_iters=50, stop_reward=0.2, stop_timesteps=100000)
2021-11-08 11:05:26,923 INFO worker.py:827 -- Connecting to existing Ray cluster at address: 192.168.86.185:6379
Traceback (most recent call last):
  File "cuj.py", line 51, in <module>
    cuj(args)
  File "cuj.py", line 31, in cuj
    ray.init(address="auto")
  File "/Users/will/opt/anaconda3/envs/cuj_rl_production/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/Users/will/opt/anaconda3/envs/cuj_rl_production/lib/python3.7/site-packages/ray/worker.py", line 935, in init
    connect_only=True)
  File "/Users/will/opt/anaconda3/envs/cuj_rl_production/lib/python3.7/site-packages/ray/node.py", line 184, in __init__
    self._init_temp(redis_client)
  File "/Users/will/opt/anaconda3/envs/cuj_rl_production/lib/python3.7/site-packages/ray/node.py", line 310, in _init_temp
    "value")
  File "/Users/will/opt/anaconda3/envs/cuj_rl_production/lib/python3.7/site-packages/ray/node.py", line 59, in _hget_with_retry
    result = redis_client.hget(key, field)
  File "/Users/will/opt/anaconda3/envs/cuj_rl_production/lib/python3.7/site-packages/redis/client.py", line 3010, in hget
    return self.execute_command('HGET', name, key)
  File "/Users/will/opt/anaconda3/envs/cuj_rl_production/lib/python3.7/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/Users/will/opt/anaconda3/envs/cuj_rl_production/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/Users/will/opt/anaconda3/envs/cuj_rl_production/lib/python3.7/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
```

This consistently works, even on a clean conda environment on my machine. Not an M1.

Environment

```bash
% pip freeze | grep redis
aioredis==1.3.1
hiredis==2.0.0
redis==3.5.3
% pip install -U redis
Requirement already satisfied: redis in /Users/will/opt/anaconda3/envs/cuj_rl_production/lib/python3.7/site-packages (3.5.3)
% pip freeze | grep ray
ray==1.7.0
```

Have also tried with `ray==1.8.0`, I see same issue.

More details:

```
% python
Python 3.7.7 (default, May  6 2020, 04:59:01) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init()
[2021-11-08 18:33:29,919 C 7043 40213109] service_based_gcs_client.cc:74:  Check failed: GetGcsServerAddressFromRedis( redis_client_->GetPrimaryContext()->sync_context(), &current_gcs_server_address_, RayConfig::instance().gcs_service_connect_retries()) Failed to get gcs server address when init gcs client.
*** StackTrace Information ***
    ray::GetCallTrace()
    ray::SpdLogMessage::Flush()
    ray::SpdLogMessage::~SpdLogMessage()
    ray::RayLog::~RayLog()
    ray::gcs::ServiceBasedGcsClient::Connect()
    ray::gcs::GlobalStateAccessor::Connect()
    __pyx_pw_3ray_7_raylet_19GlobalStateAccessor_3connect()
    _PyMethodDef_RawFastCallKeywords
    _PyMethodDescr_FastCallKeywords
    call_function
    _PyEval_EvalFrameDefault
    _PyEval_EvalCodeWithName
    _PyFunction_FastCallKeywords
    call_function
    _PyEval_EvalFrameDefault
    function_code_fastcall
    call_function
    _PyEval_EvalFrameDefault
    function_code_fastcall
    call_function
    _PyEval_EvalFrameDefault
    _PyEval_EvalCodeWithName
    _PyFunction_FastCallKeywords
    call_function
    _PyEval_EvalFrameDefault
    _PyEval_EvalCodeWithName
    _PyFunction_FastCallDict
    slot_tp_init
    type_call
    _PyObject_FastCallKeywords
    call_function
    _PyEval_EvalFrameDefault
    _PyEval_EvalCodeWithName
    _PyFunction_FastCallDict
    _PyEval_EvalFrameDefault
    _PyEval_EvalCodeWithName
    _PyFunction_FastCallKeywords
    call_function
    _PyEval_EvalFrameDefault
    _PyEval_EvalCodeWithName
    PyRun_InteractiveOneObjectEx
    PyRun_InteractiveLoopFlags
    PyRun_AnyFileExFlags
    pymain_main
    main
    start
```

And logs:

```bash
% cat /tmp/ray/session_latest/logs/gcs_server.err
% cat /tmp/ray/session_latest/logs/gcs_server.out
% python cuj.py --as-test                        
Running with following CLI options: Namespace(as_test=True, cluster_compute_id='cpt_qtS7N1d5tdXvKhemXhGVUaGX', cluster_env_id='bld_LQZSjdJhvFhzCsujCkP4gH1Y', cluster_name='', local_mode=False, num_samples=10, project_id='', stop_iters=50, stop_reward=0.2, stop_timesteps=100000)
2021-11-08 18:40:17,776 INFO worker.py:823 -- Connecting to existing Ray cluster at address: 192.168.86.185:6379
Traceback (most recent call last):
  File "cuj.py", line 51, in <module>
    cuj(args)
  File "cuj.py", line 31, in cuj
    ray.init(address="auto")
  File "/Users/will/opt/anaconda3/envs/test_cuj/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/will/opt/anaconda3/envs/test_cuj/lib/python3.7/site-packages/ray/worker.py", line 929, in init
    connect_only=True)
  File "/Users/will/opt/anaconda3/envs/test_cuj/lib/python3.7/site-packages/ray/node.py", line 184, in __init__
    self._init_temp(redis_client)
  File "/Users/will/opt/anaconda3/envs/test_cuj/lib/python3.7/site-packages/ray/node.py", line 310, in _init_temp
    "value")
  File "/Users/will/opt/anaconda3/envs/test_cuj/lib/python3.7/site-packages/ray/node.py", line 59, in _hget_with_retry
    result = redis_client.hget(key, field)
  File "/Users/will/opt/anaconda3/envs/test_cuj/lib/python3.7/site-packages/redis/client.py", line 3010, in hget
    return self.execute_command('HGET', name, key)
  File "/Users/will/opt/anaconda3/envs/test_cuj/lib/python3.7/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/Users/will/opt/anaconda3/envs/test_cuj/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/Users/will/opt/anaconda3/envs/test_cuj/lib/python3.7/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
(test_cuj) will@wills-mbp cuj-rl-production % cat /tmp/ray/session_latest/logs/gcs_server.err
(test_cuj) will@wills-mbp cuj-rl-production % cat /tmp/ray/session_latest/logs/gcs_server.out
[2021-11-08 18:40:04,649 I 7813 40222436] io_service_pool.cc:35: IOServicePool is running with 1 io_service.
[2021-11-08 18:40:04,653 I 7813 40222436] gcs_redis_failure_detector.cc:30: Starting redis failure detector.
[2021-11-08 18:40:04,653 I 7813 40222436] gcs_init_data.cc:44: Loading job table data.
[2021-11-08 18:40:04,653 I 7813 40222436] gcs_init_data.cc:56: Loading node table data.
[2021-11-08 18:40:04,653 I 7813 40222436] gcs_init_data.cc:68: Loading object table data.
[2021-11-08 18:40:04,653 I 7813 40222436] gcs_init_data.cc:81: Loading cluster resources table data.
[2021-11-08 18:40:04,653 I 7813 40222436] gcs_init_data.cc:108: Loading actor table data.
[2021-11-08 18:40:04,653 I 7813 40222436] gcs_init_data.cc:94: Loading placement group table data.
[2021-11-08 18:40:04,653 I 7813 40222436] gcs_init_data.cc:48: Finished loading job table data, size = 0
[2021-11-08 18:40:04,654 I 7813 40222436] gcs_init_data.cc:60: Finished loading node table data, size = 0
[2021-11-08 18:40:04,654 I 7813 40222436] gcs_init_data.cc:73: Finished loading object table data, size = 0
[2021-11-08 18:40:04,654 I 7813 40222436] gcs_init_data.cc:85: Finished loading cluster resources table data, size = 0
[2021-11-08 18:40:04,654 I 7813 40222436] gcs_init_data.cc:112: Finished loading actor table data, size = 0
[2021-11-08 18:40:04,654 I 7813 40222436] gcs_init_data.cc:99: Finished loading placement group table data, size = 0
[2021-11-08 18:40:04,654 I 7813 40222436] gcs_heartbeat_manager.cc:30: GcsHeartbeatManager start, num_heartbeats_timeout=30
[2021-11-08 18:40:04,665 I 7813 40222436] grpc_server.cc:95: GcsServer server started, listening on port 60453.
[2021-11-08 18:40:04,682 I 7813 40222436] gcs_server.cc:339: Gcs server address = 127.0.0.1:60453
[2021-11-08 18:40:04,682 I 7813 40222436] gcs_server.cc:343: Finished setting gcs server address: 127.0.0.1:60453
[2021-11-08 18:40:04,682 I 7813 40222436] gcs_server.cc:516: GcsNodeManager: {RegisterNode request count: 0, UnregisterNode request count: 0, GetAllNodeInfo request count: 0, GetInternalConfig request count: 0}
GcsActorManager: {RegisterActor request count: 0, CreateActor request count: 0, GetActorInfo request count: 0, GetNamedActorInfo request count: 0, GetAllActorInfo request count: 0, KillActor request count: 0, ListNamedActors request count: 0, Registered actors count: 0, Destroyed actors count: 0, Named actors count: 0, Unresolved actors count: 0, Pending actors count: 0, Created actors count: 0}
GcsObjectManager: {GetObjectLocations request count: 0, GetAllObjectLocations request count: 0, AddObjectLocation request count: 0, RemoveObjectLocation request count: 0, Object count: 0}
GcsPlacementGroupManager: {CreatePlacementGroup request count: 0, RemovePlacementGroup request count: 0, GetPlacementGroup request count: 0, GetAllPlacementGroup request count: 0, WaitPlacementGroupUntilReady request count: 0, GetNamedPlacementGroup request count: 0, Scheduling pending placement group count: 0, Registered placement groups count: 0, Named placement group count: 0, Pending placement groups count: 0}
GcsPubSub:
- num channels subscribed to: 0
- total commands queued: 0
DefaultTaskInfoHandler: {AddTask request count: 0, GetTask request count: 0, AddTaskLease request count: 0, GetTaskLease request count: 0, AttemptTaskReconstruction request count: 0}
[2021-11-08 18:40:05,811 I 7813 40222436] gcs_node_manager.cc:36: Registering node info, node id = 183031bef8d15a391efbbddb8cc11c6f0a7a636406d9b9a72c4c0ddd, address = 127.0.0.1
[2021-11-08 18:40:05,811 I 7813 40222436] gcs_node_manager.cc:41: Finished registering node info, node id = 183031bef8d15a391efbbddb8cc11c6f0a7a636406d9b9a72c4c0ddd, address = 127.0.0.1
[2021-11-08 18:40:05,811 I 7813 40222436] gcs_placement_group_manager.cc:639: A new node: 183031bef8d15a391efbbddb8cc11c6f0a7a636406d9b9a72c4c0ddd registered, will try to reschedule all the infeasible placement groups.
[2021-11-08 18:40:05,812 I 7813 40222436] gcs_resource_manager.cc:61: Updating resources, node id = 183031bef8d15a391efbbddb8cc11c6f0a7a636406d9b9a72c4c0ddd
[2021-11-08 18:40:05,818 I 7813 40222436] gcs_job_manager.cc:143: Getting all job info.
[2021-11-08 18:40:05,819 I 7813 40222436] gcs_job_manager.cc:149: Finished getting all job info.
[2021-11-08 18:40:07,102 I 7813 40222436] gcs_job_manager.cc:40: Adding job, job id = 01000000, driver pid = 7712
[2021-11-08 18:40:07,102 I 7813 40222436] gcs_job_manager.cc:56: Finished adding job, job id = 01000000, driver pid = 7712
[2021-11-08 18:40:11,612 I 7813 40222436] gcs_worker_manager.cc:35: Reporting worker failure, worker id = 01000000ffffffffffffffffffffffffffffffffffffffffffffffff, node id = 183031bef8d15a391efbbddb8cc11c6f0a7a636406d9b9a72c4c0ddd, address = 127.0.0.1, exit_type = INTENDED_EXIT, has creation task exception = 0
....
[2021-11-08 18:40:11,653 I 7813 40222436] gcs_actor_manager.cc:717: Worker 8d7be6bf1db28760f26e86b65ad498931d9b0a47ac31dc7c22cb348f on node 183031bef8d15a391efbbddb8cc11c6f0a7a636406d9b9a72c4c0ddd exited, type=SYSTEM_ERROR_EXIT, has creation_task_exception = 0
[2021-11-08 18:40:11,653 W 7813 40222436] gcs_worker_manager.cc:37: Reporting worker failure, worker id = 57874e32b5c3c973c2d9d4edd8d3d164a7518f4a5918af36505b53bf, node id = 183031bef8d15a391efbbddb8cc11c6f0a7a636406d9b9a72c4c0ddd, address = 127.0.0.1, exit_type = SYSTEM_ERROR_EXIT, has creation task exception = 0. Unintentional worker failures have been reported. If there are lots of this logs, that might indicate there are unexpected failures in the cluster.
[2021-11-08 18:40:11,653 I 7813 40222436] gcs_actor_manager.cc:717: Worker 57874e32b5c3c973c2d9d4edd8d3d164a7518f4a5918af36505b53bf on node 183031bef8d15a391efbbddb8cc11c6f0a7a636406d9b9a72c4c0ddd exited, type=SYSTEM_ERROR_EXIT, has creation_task_exception = 0
[2021-11-08 18:40:11,654 W 7813 40222436] gcs_worker_manager.cc:37: Reporting worker failure, worker id = f0306361f66c41d9c7ff5e421d44835c5605cfb96559807b2a7de74c, node id = 183031bef8d15a391efbbddb8cc11c6f0a7a636406d9b9a72c4c0ddd, address = 127.0.0.1, exit_type = SYSTEM_ERROR_EXIT, has creation task exception = 0. Unintentional worker failures have been reported. If there are lots of this logs, that might indicate there are unexpected failures in the cluster.
[2021-11-08 18:40:11,654 I 7813 40222436] gcs_actor_manager.cc:717: Worker f0306361f66c41d9c7ff5e421d44835c5605cfb96559807b2a7de74c on node 183031bef8d15a391efbbddb8cc11c6f0a7a636406d9b9a72c4c0ddd exited, type=SYSTEM_ERROR_EXIT, has creation_task_exception = 0
[2021-11-08 18:40:11,655 W 7813 40222436] gcs_worker_manager.cc:37: Reporting worker failure, worker id = 545af75baea27d348b412c36a8b487e70744853f3bc01f84ab83509a, node id = 183031bef8d15a391efbbddb8cc11c6f0a7a636406d9b9a72c4c0ddd, address = 127.0.0.1, exit_type = SYSTEM_ERROR_EXIT, has creation task exception = 0. Unintentional worker failures have been reported. If there are lots of this logs, that might indicate there are unexpected failures in the cluster.
[2021-11-08 18:40:11,655 I 7813 40222436] gcs_actor_manager.cc:717: Worker 545af75baea27d348b412c36a8b487e70744853f3bc01f84ab83509a on node 183031bef8d15a391efbbddb8cc11c6f0a7a636406d9b9a72c4c0ddd exited, type=SYSTEM_ERROR_EXIT, has creation_task_exception = 0
[2021-11-08 18:40:11,752 I 7813 40222436] gcs_node_manager.cc:57: Unregistering node info, node id = 183031bef8d15a391efbbddb8cc11c6f0a7a636406d9b9a72c4c0ddd
[2021-11-08 18:40:11,752 I 7813 40222436] gcs_node_manager.cc:142: Removing node, node id = 183031bef8d15a391efbbddb8cc11c6f0a7a636406d9b9a72c4c0ddd
[2021-11-08 18:40:11,752 I 7813 40222436] gcs_placement_group_manager.cc:616: Node 183031bef8d15a391efbbddb8cc11c6f0a7a636406d9b9a72c4c0ddd failed, rescheduling the placement groups on the dead node.
[2021-11-08 18:40:11,752 I 7813 40222436] gcs_actor_manager.cc:774: Node 183031bef8d15a391efbbddb8cc11c6f0a7a636406d9b9a72c4c0ddd failed, reconstructing actors.
[2021-11-08 18:40:11,752 I 7813 40222436] gcs_node_manager.cc:74: Finished unregistering node info, node id = 183031bef8d15a391efbbddb8cc11c6f0a7a636406d9b9a72c4c0ddd
[2021-11-08 18:40:12,078 I 7813 40222436] gcs_server_main.cc:125: GCS server received SIGTERM, shutting down...
[2021-11-08 18:40:12,078 I 7813 40222436] gcs_server.cc:158: Stopping GCS server.
[2021-11-08 18:40:12,103 I 7813 40222436] gcs_server.cc:176: GCS server stopped.
[2021-11-08 18:40:12,103 I 7813 40222436] io_service_pool.cc:47: IOServicePool is stopped.
```

**Comment by rkooo567** [comment]
TODO; Raise an exception when Ray version mismatches when ray.init() is called

**Comment by rkooo567** [comment]
@worldveil can you comment how you fixed the issue?

**Comment by worldveil** [comment]
There was a mismatch between Ray versions of a) code, and b) local cluster. 

Solved with using the correct version via the conda path for binaries:

```
% which ray                                                      
/usr/local/bin/ray
% /Users/will/opt/anaconda3/envs/cuj_rl_new2/bin/ray stop        
% /Users/will/opt/anaconda3/envs/cuj_rl_new2/bin/ray start --head
% python cuj.py --as-test
```

**Comment by rkooo567** [comment]
I will keep tracking of this issue and work with Yi to properly resolve the problem once we use Internal KV for initialization.

**Comment by scv119** [comment]
@mwtian @iycheng do you know the status of this one?

**Comment by jjyao** [comment]
We removed redis by default already.
