### ISSUE TITLE
[Bug]  Training-on-previously-saved-experiences, KeyError: 'new_obs'

### ISSUE THREAD

**Issue by lorepieri8** [ray-project/ray#20269]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

Running the tutorial: https://docs.ray.io/en/latest/rllib-offline.html#example-training-on-previously-saved-experiences 
I'm not able to train from an existing output, as in the tutorial.

```(pid=449) 2021-11-11 23:11:40,071	WARNING json_reader.py:61 -- Treating input directory as glob patterns: ['/tmp/cartpole-out/*.json', '/tmp/cartpole-out/*.zip']
(pid=449) 2021-11-11 23:11:40,072	WARNING deprecation.py:39 -- DeprecationWarning: `ReplayBuffer(size)` has been deprecated. Use `ReplayBuffer(capacity)` instead. This will raise an error in the future!
(pid=449) 2021-11-11 23:11:40,073	WARNING util.py:57 -- Install gputil for GPU system monitoring.
2021-11-11 23:11:40,725	ERROR trial_runner.py:924 -- Trial DQN_CartPole-v0_b5837_00000: Error processing event.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trial_runner.py", line 890, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/ray_trial_executor.py", line 788, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/usr/local/lib/python3.7/dist-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ray/worker.py", line 1625, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(KeyError): ray::DQN.train_buffered() (pid=449, ip=172.28.0.2, repr=DQN)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trainable.py", line 224, in train_buffered
    result = self.train()
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer.py", line 682, in train
    raise e
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer.py", line 668, in train
    result = Trainable.train(self)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trainable.py", line 283, in train
    result = self.step()
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer_template.py", line 206, in step
    step_results = next(self.train_exec_impl)
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 1075, in build_union
    item = next(it)
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 791, in apply_foreach
    result = fn(item)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/execution/train_ops.py", line 200, in __call__
    buffer_index=0)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/policy/dynamic_tf_policy.py", line 515, in learn_on_loaded_batch
    return self.learn_on_batch(sliced_batch)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/policy/tf_policy.py", line 545, in learn_on_batch
    fetches = self._build_learn_on_batch(builder, postprocessed_batch)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/policy/tf_policy.py", line 1082, in _build_learn_on_batch
    self._get_loss_inputs_dict(postprocessed_batch, shuffle=False))
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/policy/tf_policy.py", line 1134, in _get_loss_inputs_dict
    train_batch[key],
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/policy/sample_batch.py", line 706, in __getitem__
    value = dict.__getitem__(self, key)
KeyError: 'new_obs'
== Status ==
Current time: 2021-11-11 23:11:40 (running for 00:00:08.31)
Memory usage on this node: 2.6/12.7 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/2 CPUs, 0/0 GPUs, 0.0/7.36 GiB heap, 0.0/3.68 GiB objects
Result logdir: /root/ray_results/default
Number of trials: 1/1 (1 ERROR)
+-----------------------------+----------+----------------+
| Trial name                  | status   | loc            |
|-----------------------------+----------+----------------|
| DQN_CartPole-v0_b5837_00000 | ERROR    | 172.28.0.2:449 |
+-----------------------------+----------+----------------+
Number of errored trials: 1
+-----------------------------+--------------+---------------------------------------------------------------------------------------+
| Trial name                  |   # failures | error file                                                                            |
|-----------------------------+--------------+---------------------------------------------------------------------------------------|
| DQN_CartPole-v0_b5837_00000 |            1 | /root/ray_results/default/DQN_CartPole-v0_b5837_00000_0_2021-11-11_23-11-32/error.txt |
+-----------------------------+--------------+---------------------------------------------------------------------------------------+

== Status ==
Current time: 2021-11-11 23:11:40 (running for 00:00:08.31)
Memory usage on this node: 2.6/12.7 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/2 CPUs, 0/0 GPUs, 0.0/7.36 GiB heap, 0.0/3.68 GiB objects
Result logdir: /root/ray_results/default
Number of trials: 1/1 (1 ERROR)
+-----------------------------+----------+----------------+
| Trial name                  | status   | loc            |
|-----------------------------+----------+----------------|
| DQN_CartPole-v0_b5837_00000 | ERROR    | 172.28.0.2:449 |
+-----------------------------+----------+----------------+
Number of errored trials: 1
+-----------------------------+--------------+---------------------------------------------------------------------------------------+
| Trial name                  |   # failures | error file                                                                            |
|-----------------------------+--------------+---------------------------------------------------------------------------------------|
| DQN_CartPole-v0_b5837_00000 |            1 | /root/ray_results/default/DQN_CartPole-v0_b5837_00000_0_2021-11-11_23-11-32/error.txt |
+-----------------------------+--------------+---------------------------------------------------------------------------------------+

(pid=449) [2021-11-11 23:11:40,781 E 449 493] raylet_client.cc:159: IOError: Broken pipe [RayletClient] Failed to disconnect from raylet.
Traceback (most recent call last):
  File "/usr/local/bin/rllib", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/scripts.py", line 36, in cli
    train.run(options, train_parser)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/train.py", line 273, in run
    concurrent=True)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/tune.py", line 724, in run_experiments
    callbacks=callbacks).trials
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/tune.py", line 624, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [DQN_CartPole-v0_b5837_00000])```

### Versions / Dependencies

Colab defaults.

### Reproduction script

https://colab.research.google.com/drive/16Jn-YO6K_MoCqFttmVntmvU_L1MPGA0R?usp=sharing

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by waltmayfield** [comment]
Using ray 2.2.0 this issue reoccurs when using the 'tf' framework. Switching to the 'torch' framework resolved it for me.
