### ISSUE TITLE
[Bug] sgd.save_checkpoint raise an error

### ISSUE THREAD

**Issue by Junphy-Jan** [ray-project/ray#20278]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Train

### What happened + What you expected to happen

When I use sgd.save_checkpoint to save a DistributedDataParallel model, it raise an error about process group has not been initialized error. But before that the process group had been initialized.
Here is the error:
`2021-11-12 15:46:07,837 INFO trainer.py:150 -- Run results will be logged in: /root/ray_results/sgd_2021-11-12_15-46-05/run_001
(pid=9468) 2021-11-12 15:46:07,814      INFO torch.py:69 -- Setting up process group for: env:// [rank=1, world_size=2]
(pid=11016) 2021-11-12 15:47:58,551     INFO torch.py:69 -- Setting up process group for: env:// [rank=0, world_size=2]
(pid=9468) DEBUG:test.log:loss: 1.004661  [ 3984/16000]
(pid=9471) DEBUG:test.log:loss: 1.157834  [ 3984/16000]
2021-11-12 15:46:09,038 ERROR serialization.py:270 -- Default process group has not been initialized, please make sure to call init_process_group.
Traceback (most recent call last):
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/ray/serialization.py", line 268, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/ray/serialization.py", line 191, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/ray/serialization.py", line 169, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/ray/serialization.py", line 159, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 673, in __setstate__
    self.process_group = _get_default_group()
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 411, in _get_default_group
    "Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
Traceback (most recent call last):
  File "../test_ray.py", line 209, in <module>
    test_distributed_train()
  File "../test_ray.py", line 47, in wrapped_function
    return func(*args, **kwargs)
  File "../test_ray.py", line 113, in test_distributed_train
    learning_rate=0.08, **fit_args)
  File "../test_ray.py", line 469, in fit
    **kwargs)
  File "../test_ray.py", line 792, in _fit4distributed
    checkpoint_strategy=checkpoint_strategy    
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/ray/util/sgd/v2/trainer.py", line 240, in run
    for intermediate_result in iterator:
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/ray/util/sgd/v2/trainer.py", line 563, in __next__
    self._executor.fetch_next_result)
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/ray/util/sgd/v2/trainer.py", line 537, in _run_with_error_handling
    return func()
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/ray/util/sgd/v2/backends/backend.py", line 519, in fetch_next_result
    results = self._get_next_results()
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/ray/util/sgd/v2/backends/backend.py", line 482, in _get_next_results
    results = self.get_with_failure_handling(futures)
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/ray/util/sgd/v2/backends/backend.py", line 619, in get_with_failure_handling
    success, failed_worker_indexes = check_for_failure(remote_values)
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/ray/util/sgd/v2/utils.py", line 34, in check_for_failure
    ray.get(object_ref)
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/ray/worker.py", line 1623, in get
    raise value
ray.exceptions.RaySystemError: System error: Default process group has not been initialized, please make sure to call init_process_group.
traceback: Traceback (most recent call last):
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/ray/serialization.py", line 268, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/ray/serialization.py", line 191, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/ray/serialization.py", line 169, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/ray/serialization.py", line 159, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 673, in __setstate__
    self.process_group = _get_default_group()
  File "/opt/miniconda3/envs/env_name/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 411, in _get_default_group
    "Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.`

### Versions / Dependencies

Ray 1.7
Red hat 4.8.5
Python 7.3
Torch: 1.10

### Reproduction script

For some reason here is a pseudo code:
`class xxx:
	def demo(self, ...):

		trainer = Trainer(backend="torch", num_workers=self.num_workers, resources_per_worker=resources_per_worker, 
									  max_retries=max_failures, logdir=local_dir,
									  use_gpu=self.use_gpu)
		trainer.start()
		result = trainer.run(
					train_func=self.train_func,
					config={
						"lr": learning_rate,
						"batch_size": batch_size,
						"epochs": epochs,
					},
					callbacks=callback_list,
					checkpoint=checkpoint,
					checkpoint_strategy=checkpoint_strategy    
				)
	
	def train_func(self, config):
		
		...
		
		if distributed:
			model = DistributedDataParallel(
                self.model,
                device_ids=[device.index] if torch.cuda.is_available() else None
			)
		else:
            device = torch.device("cuda" if self.use_gpu and torch.cuda.is_available() else "cpu")
            model = self.model.to(device)
		
		for epoch in range(epochs):
            train_ret = self._train(model, loss_fn, optimizer, train_dataloader, device)
            ...
            if distributed:
                sgd.save_checkpoint(epoch=epoch, model=model)
                # sgd.save_checkpoint(epoch=epoch, model=model.module)
                sgd.report(**train_ret)
            if (not distributed) and tuning:
                tune.report(**train_ret)
`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by JanJF** [comment]
*Python:3.7

**Comment by amogkam** [comment]
Hey @JanJF- ah this is because when you save a checkpoint, the values get serialized and sent to the driver. Even though the workers have the process group initialized, the driver does not hence why this is failing.

The fix should just be saving `model.module` instead of the DDP wrapped `model` directly. I see you have this line commented out in the code snippet. Did that not work for you?

**Comment by JanJF** [comment]
Yeah, if use the model.module it works. But isn't the driver a special worker? If I have one head node and one worker node, how the process group initialized?
