### ISSUE TITLE
[Bug] [Tune]  Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks'

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#20336]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

I ran the example from https://docs.ray.io/en/latest/train/examples/tune_cifar_pytorch_pbt_example.html, when it finished I got the following error:
```
(pid=6844) 2021-11-13 22:47:05,479	INFO tune.py:630 -- Total run time: 320.91 seconds (320.75 seconds for the tuning loop).
Traceback (most recent call last):
  File "tune_cifar_pytorch_pbt_example.py", line 196, in <module>
    scheduler=pbt_scheduler)
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/tune/tune.py", line 360, in run
    return ray.get(remote_future)
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/util/client/api.py", line 42, in get
    return self.worker.get(vals, timeout=timeout)
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/util/client/worker.py", line 349, in get
    res = self._get(to_get, op_timeout)
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/util/client/worker.py", line 377, in _get
    return loads_from_server(resp.data)
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/util/client/client_pickler.py", line 173, in loads_from_server
    errors=errors).load()
AttributeError: Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks' from '/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/pandas/core/internals/blocks.py'>
```

### Versions / Dependencies

ray-ml 1.8 + python 3.7

### Reproduction script

`RAY_ADDRESS=anyscale://mycluster ANYSCALE_CLUSTER_ENV=<cluster env with ray-ml base, python 3.7, ray 1.8> python tune_cifar_pytorch_pbt_example.py --use-gpu`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by AmeerHajAli** [comment]
installing pandas 1.3.4 on both cluster + laptop solved the problem.
this is a duplicate of https://github.com/ray-project/ray/issues/15407
