### ISSUE TITLE
[release][weekly] `horovod_test` failed

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#20382]
https://buildkite.com/ray-project/periodic-ci/builds/1621#e0f6cc54-9425-4d8a-979f-4c41d0253799

It looks like config is wrong:
```




[INFO 2021-11-13 22:05:27,476] e2e.py: 428  Latest 10 commits for branch master: ['07add6f7f20fa17af8b539a57131cc97ebb8bbf8', '6cc493079b3edc57d82473c829f336e48088781c', 'e22632dabc045d07edd477bbdd1d413fffc32043', '9e2bd508d7dcd372609b6bf9d3ecd06d1209a6c9', 'e5ead6a4b0b9f6e04cfcc40080aaec5765ea52cb', 'df8042c576958ec7c453b3918c65e8f9f39c645e', '96de740cd236f56b2299031cbab541f56e02a2ec', '65a17da2ecc84f5214ee556b9cac2fd9d00cf6de', '4396419a64b6309e86bc1f67244c570a6dcf3dc6', 'f13c2a5350262edaebf85b303362f2ea8b2f6222']
  | [INFO 2021-11-13 22:05:27,515] e2e.py: 435  Found wheels URL for Ray 2.0.0.dev0, branch master: https://s3-us-west-2.amazonaws.com/ray-wheels/master/07add6f7f20fa17af8b539a57131cc97ebb8bbf8/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
  | Traceback (most recent call last):
  | File "release/e2e.py", line 2146, in <module>
  | app_config_id_override=args.app_config_id_override,
  | File "release/e2e.py", line 1972, in run_test
  | app_config_id_override=app_config_id_override)
  | File "release/e2e.py", line 1293, in run_test_config
  | app_config = _load_config(local_dir, app_config_rel_path)
  | File "release/e2e.py", line 491, in _load_config
  | with open(config_path, "rt") as f:
  | FileNotFoundError: [Errno 2] No such file or directory: '/home/ray/ray/release/horovod_tests/app_config_master.yaml'
 

<br class="Apple-interchange-newline">
```

**Comment by amogkam** [comment]
Thanks! Will address this ASAP and re-run.
