### ISSUE TITLE
[release][weekly] `serve_failure` failed

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#20384]
https://buildkite.com/ray-project/periodic-ci/builds/1621#cb1e72c7-b235-4c37-b97d-304d62aa4ea9

The build timeout
```




[INFO 2021-11-14 22:12:28,372] e2e.py: 1030  ... still waiting for command to finish (86310 seconds) ...
  | [INFO 2021-11-14 22:12:59,486] e2e.py: 1030  ... still waiting for command to finish (86341 seconds) ...
  | [INFO 2021-11-14 22:13:29,198] e2e.py: 1030  ... still waiting for command to finish (86370 seconds) ...
  | [WARNING 2021-11-14 22:13:57,410] e2e.py: 1835  Process timed out.
  | [INFO 2021-11-14 22:13:57,411] e2e.py: 1843  Process is long running. Give 2 minutes to fetch result and terminate.
  | [ERROR 2021-11-14 22:13:57,781] e2e.py: 1623  Process timed out while running a command.
  | Traceback (most recent call last):
  | File "release/e2e.py", line 1608, in _run
  | File "release/e2e.py", line 1024, in wait_for_session_command_to_complete
  | File "release/e2e.py", line 459, in _check_stop
  | CommandTimeoutError: Process timed out while running a command.
  | [INFO 2021-11-14 22:14:06,316] e2e.py: 1344  Command finished successfully.
  | (anyscale +24h8m42.8s) Warning: `anyscale pull` has been deprecated and will be removed in the future.
 

<br class="Apple-interchange-newline">
```

**Comment by simon-mo** [comment]
```
(ServeController pid=1448671) 2021-11-14 22:14:30,351   ERROR controller.py:201 -- Exception updating deployment state.
(ServeController pid=1448671) Traceback (most recent call last):
(ServeController pid=1448671)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/controller.py", line 199, in run_control_loop
(ServeController pid=1448671)     self.deployment_state_manager.update()
(ServeController pid=1448671)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/deployment_state.py", line 1388, in update
(ServeController pid=1448671)     deleted = deployment_state.update()
(ServeController pid=1448671)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/deployment_state.py", line 1144, in update
(ServeController pid=1448671)     running_replicas_changed |= self._check_and_update_replicas()
(ServeController pid=1448671)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/deployment_state.py", line 1105, in _check_and_update_replicas
(ServeController pid=1448671)     0].resource_requirements()
(ServeController pid=1448671)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/deployment_state.py", line 485, in resource_requirements
(ServeController pid=1448671)     for k, v in self._actor.actor_resources.items() if v > 0
(ServeController pid=1448671) AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by simon-mo** [comment]
hmm i'm not sure why would this happen. @edoakes @jiaodong can you help here? 

looking at the stack, it looks like `actor_resources` are accessed before they are set during `start()`. But the codepath shows that this is only called when actors are in STARTING state.

**Comment by simon-mo** [comment]
here's the full 200M log file https://drive.google.com/file/d/1D9pCDV9F8Lkm7A_v14Oyl7TzSUr-zjDi/view?usp=sharing
