### ISSUE TITLE
build-docker.sh hang on this, why????

### ISSUE THREAD

**Issue by cklsoft** [ray-project/ray#2055]
### System information
- **Mac OSX 10.11.6**:
- **Ray installed from source**:
- **Ray version: master**:
- **Python version: 2.7.14=**:
- **Exact command to reproduce**:

### Describe the problem

$ ./build-docker.sh
+ [[ 0 -gt 0 ]]
+ '[' ']'
+ docker build -t ray-project/base-deps docker/base-deps
Sending build context to Docker daemon   2.56kB
Step 1/3 : FROM ubuntu:xenial
 ---> 0b1edfbffd27
Step 2/3 : RUN apt-get update     && apt-get install -y         git         wget         cmake         pkg-config         build-essential         autoconf         curl         libtool         unzip         flex         bison     && apt-get clean     && echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh     && wget         --quiet 'https://repo.continuum.io/archive/Anaconda2-4.2.0-Linux-x86_64.sh'         -O /tmp/anaconda.sh     && /bin/bash /tmp/anaconda.sh -b -p /opt/conda     && rm /tmp/anaconda.sh     && /opt/conda/bin/conda install -y         libgcc     && /opt/conda/bin/conda clean -y --all     && /opt/conda/bin/pip install         flatbuffers -i  https://pypi.doubanio.com/simple         cython==0.27.3
 ---> Using cache
 ---> d3e1ba621b87
Step 3/3 : ENV PATH "/opt/conda/bin:$PATH"
 ---> Using cache
 ---> 7cf9a2dbd876
Successfully built 7cf9a2dbd876
Successfully tagged ray-project/base-deps:latest
+ git rev-parse HEAD
++ git rev-parse HEAD
+ git archive -o ./docker/deploy/ray.tar 52b0f3734ad42793cc5b8486a0f893637fee2226
+ '[' ']'
+ docker build --no-cache -t ray-project/deploy docker/deploy
Sending build context to Docker daemon  6.946MB
Step 1/6 : FROM ray-project/base-deps
 ---> 7cf9a2dbd876
Step 2/6 : ADD ray.tar /ray
 ---> f163ebb0295a
Step 3/6 : ADD git-rev /ray/git-rev
 ---> 9f95d7a3d2a6
Step 4/6 : WORKDIR /ray/python
Removing intermediate container 9ca74d3b2812
 ---> 8a8121caa047
Step 5/6 : RUN pip install -e . -i  https://pypi.doubanio.com/simple
 ---> Running in fe2ce26db1b6
Obtaining file:///ray/python
Requirement already satisfied (use --upgrade to upgrade): numpy in /opt/conda/lib/python2.7/site-packages (from ray==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): funcsigs in /opt/conda/lib/python2.7/site-packages (from ray==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): click in /opt/conda/lib/python2.7/site-packages (from ray==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): colorama in /opt/conda/lib/python2.7/site-packages (from ray==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): psutil in /opt/conda/lib/python2.7/site-packages (from ray==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): pytest in /opt/conda/lib/python2.7/site-packages (from ray==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /opt/conda/lib/python2.7/site-packages (from ray==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): redis in /opt/conda/lib/python2.7/site-packages (from ray==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.0.0 in /opt/conda/lib/python2.7/site-packages (from ray==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): flatbuffers in /opt/conda/lib/python2.7/site-packages (from ray==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.29 in /opt/conda/lib/python2.7/site-packages (from pytest->ray==0.4.0)
Installing collected packages: ray
  Running setup.py develop for ray

**Comment by knightXun** [comment]
@cklsoft  because of great-wall firewall

**Comment by cklsoft** [comment]
@robertnishihara   I fix the hang, but I fail run build-docker.sh when docker build docker/deploy/Dockerfile. In setuptools, Cert only allow the source hosts defined but not the one (https://pypi.douban.com/simple) I provided. How can I fix it.:

`+ PKG_CONFIG_PATH=/ray/thirdparty/scripts/..//pkg/arrow/cpp/build/cpp-install/lib/pkgconfig
    + PYARROW_WITH_PLASMA=1
    + PYARROW_BUNDLE_ARROW_CPP=1
    + /opt/conda/bin/python setup.py build -i https://pypi.douban.com/simple
    Download error on https://pypi.douban.com/simple/setuptools_scm/: hostname 'pypi.doubanio.com' doesn't match either of 'img.ucdl.pp.uc.cn', 'alissl.ucdl.pp.uc.cn', 'oss.ucdl.pp.uc.cn', 'iscsi.ucdl.pp.uc.cn', 'slient.ucdl.pp.uc.cn', 'cdn.osupdateservice.yunos.com' -- Some packages may not be found!
    Download error on https://pypi.douban.com/simple/setuptools-scm/: hostname 'pypi.doubanio.com' doesn't match either of 'img.ucdl.pp.uc.cn', 'alissl.ucdl.pp.uc.cn', 'oss.ucdl.pp.uc.cn', 'iscsi.ucdl.pp.uc.cn', 'slient.ucdl.pp.uc.cn', 'cdn.osupdateservice.yunos.com' -- Some packages may not be found!
    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
    Download error on https://pypi.douban.com/simple/: hostname 'pypi.doubanio.com' doesn't match either of 'img.ucdl.pp.uc.cn', 'alissl.ucdl.pp.uc.cn', 'oss.ucdl.pp.uc.cn', 'iscsi.ucdl.pp.uc.cn', 'slient.ucdl.pp.uc.cn', 'cdn.osupdateservice.yunos.com' -- Some packages may not be found!
    No local packages or working download links found for setuptools_scm
    Traceback (most recent call last):
      File "setup.py", line 511, in <module>
        url="https://arrow.apache.org/"
      File "/opt/conda/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/conda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py", line 315, in __init__
      File "/opt/conda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py", line 361, in fetch_build_eggs
      File "/opt/conda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 851, in resolve
      File "/opt/conda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1123, in best_match
      File "/opt/conda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1135, in obtain
      File "/opt/conda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py", line 428, in fetch_build_egg
      File "/opt/conda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 658, in easy_install
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/ray/python/setup.py", line 141, in <module>
        license="Apache 2.0")
      File "/opt/conda/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/opt/conda/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/opt/conda/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/develop.py", line 34, in run
      File "/opt/conda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/develop.py", line 119, in install_for_development
      File "/opt/conda/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/ray/python/setup.py", line 66, in run
        subprocess.check_call(["../build.sh", sys.executable])
      File "/opt/conda/lib/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '/opt/conda/bin/python']' returned non-zero exit status 1
Cleaning up...
Command "/opt/conda/bin/python -c "import setuptools, tokenize;__file__='/ray/python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /ray/python/
Exception information:
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/conda/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/opt/conda/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/opt/conda/lib/python2.7/site-packages/pip/req/req_install.py", line 825, in install
    install_options, global_options, prefix=prefix)
  File "/opt/conda/lib/python2.7/site-packages/pip/req/req_install.py", line 981, in install_editable
    show_stdout=False)
  File "/opt/conda/lib/python2.7/site-packages/pip/utils/__init__.py", line 718, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/opt/conda/bin/python -c "import setuptools, tokenize;__file__='/ray/python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /ray/python/
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/pip/utils/outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "/opt/conda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/pip/download.py", line 378, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/opt/conda/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /pypi/pip/json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=5)",))
The command '/bin/sh -c pip install -e . --verbose' returned a non-zero code: 1
+ rm ./docker/deploy/ray.tar ./docker/deploy/git-rev
+ '[' '!' ']'
+ '[' ']'
+ docker build --no-cache -t ray-project/examples docker/examples
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM ray-project/deploy
pull access denied for ray-project/deploy, repository does not exist or may require 'docker login'
+ '[' ']'`

**Comment by robertnishihara** [comment]
I'm not totally sure what the solution is here. Maybe someone else who has seen this error can chime in.

**Comment by robertnishihara** [comment]
@cklsoft, great! Can you say what the fix was so that other people who encounter this issue can see it?

**Comment by harshita-kaushal** [comment]
what was the resolution to this? 


```
Step 1/3 : FROM ray-project/deploy
pull access denied for ray-project/deploy, repository does not exist or may require 'docker login'
```


I get the same error here. I am trying to build a docker image for Ray, and I'm unsure how to approach it as there seems to be no documentation for the solution to this. [My proxifier is running in the background]

**Comment by robertnishihara** [comment]
@harshita-kaushal what command did you run to get that error?

It seems to be trying to pull `ray-project/deploy` from dockerhub or something like that, but actually `./build-docker.sh` should build `ray-project/deploy`.

**Comment by christinebuckler** [comment]
I am also having this issue when running `./build-docker.sh` . Do I need to try something different?

**Comment by robertnishihara** [comment]
Compiling Ray can take a while depending on how many cores are being used (e.g., 30 min). So it's possible that the line `Running setup.py develop for ray is just taking a while and not actually hanging. We should probably change that line to be more verbose..

How long does it appear to be hanging for?

Depending on what you're trying to do, it may make sense to make a simpler Dockerfile that just does `pip install ray` instead of building it from source.

Also, if it actually is hanging, one possibility is that it needs more disk space than is available.

**Comment by christinebuckler** [comment]
currently hanging at this step:  
<img width="692" alt="screen shot 2018-11-03 at 2 44 33 pm" src="https://user-images.githubusercontent.com/26417824/47957652-64cc1a00-df77-11e8-8d5a-1c019eb91865.png">

I was hoping to use the image with the examples.

**Comment by robertnishihara** [comment]
I ran `./build-docker.sh` and uploaded `ray-project/examples` to https://hub.docker.com/r/robertnishihara/ray-examples/, so you may be able to try that out.

I ran into some issues trying it out at https://github.com/ray-project/ray/issues/3223, so you may need to call `ray.init()` and pass in a smaller value of `object_store_memory` if you run into that issue.

**Comment by christinebuckler** [comment]
@robertnishihara thank you very much! I was able to download your docker image and run the example.

**Comment by nisarkhanatwork** [comment]
pip install from the sources hangs
----------------------------------------------
Requirement already satisfied: more-itertools>=4.0.0 in /home/nisar/anaconda3/lib/python3.6/site-packages (from pytest->ray==0.6.0) (4.1.0)
Requirement already satisfied: pluggy<0.7,>=0.5 in /home/nisar/anaconda3/lib/python3.6/site-packages (from pytest->ray==0.6.0) (0.6.0)
Installing collected packages: ray
  Running setup.py develop for ray

------------------------------
and strace shows the following call being blocked
sudo strace -p 19302
strace: Process 19302 attached
read(7, 
------------------
Your help is appreciated...
Thanks
