### ISSUE TITLE
[Bug][rllib] Tune PyTorch Lightning example fails

### ISSUE THREAD

**Issue by franklsf95** [ray-project/ray#20601]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

I'm running this example https://docs.ray.io/en/latest/tune/examples/mnist_ptl_mini.html and got the following error:

```
(pid=19099) 2021-11-20 00:18:18,460	ERROR trial_runner.py:846 -- Trial train_mnist_tune_58bf2_00000: Error processing event.
(pid=19099) Traceback (most recent call last):
(pid=19099)   File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 812, in _process_trial
(pid=19099)     results = self.trial_executor.fetch_result(trial)
(pid=19099)   File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 767, in fetch_result
(pid=19099)     result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
(pid=19099)   File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 89, in wrapper
(pid=19099)     return func(*args, **kwargs)
(pid=19099)   File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/worker.py", line 1621, in get
(pid=19099)     raise value.as_instanceof_cause()
(pid=19099) ray.exceptions.RayTaskError(TuneError): ray::ImplicitFunc.train_buffered() (pid=2360, ip=172.31.1.224, repr=<types.ImplicitFunc object at 0x7fbdaeb3dc50>)
(pid=19099)   File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 189, in train_buffered
(pid=19099)     result = self.train()
(pid=19099)   File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 248, in train
(pid=19099)     result = self.step()
(pid=19099)   File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 379, in step
(pid=19099)     self._report_thread_runner_error(block=True)
(pid=19099)   File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 527, in _report_thread_runner_error
(pid=19099)     ("Trial raised an exception. Traceback:\n{}".format(err_tb_str)
(pid=19099) ray.tune.error.TuneError: Trial raised an exception. Traceback:
(pid=19099) ray::ImplicitFunc.train_buffered() (pid=2360, ip=172.31.1.224, repr=<types.ImplicitFunc object at 0x7fbdaeb3dc50>)
(pid=19099)   File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 260, in run
(pid=19099)     self._entrypoint()
(pid=19099)   File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 329, in entrypoint
(pid=19099)     self._status_reporter.get_checkpoint())
(pid=19099)   File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 594, in _trainable_func
(pid=19099)     output = fn()
(pid=19099)   File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/tune/utils/trainable.py", line 353, in _inner
(pid=19099)     inner(config, checkpoint_dir=None)
(pid=19099)   File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/tune/utils/trainable.py", line 344, in inner
(pid=19099)     trainable(config, **fn_kwargs)
(pid=19099)   File "tune_ptl_example.py", line 70, in train_mnist_tune
(pid=19099)     model = LightningMNISTClassifier(config, data_dir)
(pid=19099)   File "tune_ptl_example.py", line 29, in __init__
(pid=19099)     self.accuracy = pl.metrics.Accuracy()
(pid=19099) AttributeError: module 'pytorch_lightning' has no attribute 'metrics'
```

### Versions / Dependencies

Ray 1.8.0
Python 3.6 from AWS Deep Learning AWI
`pip3 install ray[tune] pytorch-lightning lightning-bolts torchmetrics`

### Reproduction script

https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mnist_ptl_mini.py

### Anything else

I'm finding a fix rn. Probably just package API change.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by amogkam** [comment]
Hey @franklsf95 can you try with PTL 1.4? It seems like 1.5 has some changes that break the Tune integration.

**Comment by franklsf95** [comment]
@amogkam yea looks like that is the problem. I guess more generally is there a `requirements.txt` file for these examples? Would be very helpful.

**Comment by amogkam** [comment]
Yeah the versions we use for CI are in `ray/python/requirements/ml/requirements_tune.txt`. But that's a good point, we should do a better job of documenting what versions all of our examples run against.

**Comment by franklsf95** [comment]
Thanks. Yes that would be helpful in the future. Feel free to close this now.
