### ISSUE TITLE
[serve] Serve swallows errors

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#20610]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

I was not able to understand why my deployment was failing:

```
(corridor pid=3218, ip=10.0.40.87) starting checkpoint sync
(corridor pid=3218, ip=10.0.40.87) got ts 20211120-0152
Traceback (most recent call last):
  File "deploy.py", line 206, in <module>
    serve_url = deploy(args.ckpt_path, local=(args.mode == "local"), bucket=args.bucket)
  File "deploy.py", line 103, in deploy
    Corridor.deploy(ckpt_path, local=local, bucket=bucket)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/api.py", line 800, in deploy
    _blocking=_blocking)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/api.py", line 93, in check
    return f(self, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/api.py", line 248, in deploy
    self._wait_for_goal(goal_id)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/api.py", line 184, in _wait_for_goal
    raise async_goal_exception
RuntimeError: Deployment 'corridor' failed, deleting it asynchronously.
```

My code was:

```python
@serve.deployment(name="corridor", num_replicas=2)
class Corridor(object):
    def __init__(self, ckpt_path, local, bucket):
        print("Deployment initializing.", locals())
        config = ppo.DEFAULT_CONFIG.copy()
        config.update(train.TRAINER_CFG)
        config['num_workers'] = 0

        if local:
            model_path = ckpt_path
        else:
            assert bucket, "Bucket must be provided if not local."
            os.path.join(...)
```

Turns out the problem was that I didn't import os. However, the exception was not thrown to me, so it was very hard to debug.

### Versions / Dependencies

master

### Reproduction script

see above

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by iasoon** [comment]
A more minimal reproduction:

```
from ray import serve

serve.start()

@serve.deployment
class D:
    def __init__(self):
        0/0

D.deploy()
```

In addition to logging the error, would it be desirable to bring the exception back to the `deploy` call site when possible (such as in #20617)?
