### ISSUE TITLE
[Bug] Cannot start cluster if other user is already running one

### ISSUE THREAD

**Issue by hpaantee** [ray-project/ray#20634]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

I tired to start a cluster via `ray up cluster.yaml` on a multi-user system. However, I receive the error that ray cannot create the temporary directory `/tmp/ray_current_cluster`, as this has already been created by another user. 

Instead of aborting, I would have expected that ray is creating a temporary directory with a unique id. 

### Versions / Dependencies

Ray version 1.8.0

### Reproduction script

cluster_name: dhaeupl_ray_cluster

provider:
    type: local
    head_ip: 10.64.132.11
    worker_ips: [10.64.132.12, 10.64.132.13]

auth:
    ssh_user: hpaantee
    ssh_private_key: ~/.ssh/id_rsa

setup_commands:
        - conda activate ray_env

head_start_ray_commands:
    - conda activate ray_env && ray stop
    - conda activate ray_env && ulimit -c unlimited && ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml

worker_start_ray_commands:
    - conda activate ray_env && ray stop
    - conda activate ray_env && ray start --address=$RAY_HEAD_IP:6379

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wubdub** [comment]
I am also hitting this exact issue on ray 1.8.0 and ray 1.9.0rc1 and is crippling productively using Ray amongst a number of people on a shared cluster

It it hard for the user to fix because even with group write permissions, it appears another user can't rm ```/tmp/ray_current_cluster``` for another user because it is in ```/tmp```

**Comment by wubdub** [comment]
Bump on this, continuing to see this on Ray 1.9.0rc1

**Comment by wuisawesome** [comment]
@wubdub do you mind sharing the error message you get from `ray up --verbose cluster.yaml`

**Comment by wubdub** [comment]
Hey @wuisawesome, for my case I am just using ```ray init ...``` but this fails because another user has created and left the ```/tmp/ray_current_cluster``` file on the node, even though their Ray sessions is finished

**Comment by wuisawesome** [comment]
hmmm a few things:

1. what arguments are you passing into `ray.init()`? 
2. what do you mean by "finished"? 
3. what error message are you seeing?

**Comment by djakubiec** [comment]
I am seeing this as well.  I am started a new head node directly on a machine where a different user had previously started one:

```
(started as user djakubiec)
⇒  ray start --head --node-ip-address=10.0.1.1 --port=0 --include-dashboard=false --num-cpus=24 --num-gpus=0 --block

Local node IP: 10.0.1.1
Traceback (most recent call last):
  File "/ceph/var/users/djakubiec/anaconda3/envs/ray06/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/ceph/var/users/djakubiec/anaconda3/envs/ray06/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1969, in main
    return cli()
  File "/ceph/var/users/djakubiec/anaconda3/envs/ray06/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/ceph/var/users/djakubiec/anaconda3/envs/ray06/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/ceph/var/users/djakubiec/anaconda3/envs/ray06/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/ceph/var/users/djakubiec/anaconda3/envs/ray06/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/ceph/var/users/djakubiec/anaconda3/envs/ray06/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/ceph/var/users/djakubiec/anaconda3/envs/ray06/lib/python3.8/site-packages/ray/scripts/scripts.py", line 637, in start
    with open(current_cluster_path, "w") as f:
PermissionError: [Errno 13] Permission denied: '/tmp/ray_current_cluster'

(sfigueroa previously ran a head node here)
⇒  ls -ld /tmp/ray*                                                                                                                                                                                        drwxrwxrwx 35 sfigueroa sfigueroa 4096 Apr 29 13:23 /tmp/ray
-rw-rw-r--  1 sfigueroa sfigueroa   15 Apr 29 13:06 /tmp/ray_current_cluster
```

**Comment by SoleIdol** [comment]
I had the same problem. After STARTING the RAY cluster once with user A, I run the RAY cluster with another user B. The following error is reported:


`Traceback (most recent call last):
  File "/opt/intel/oneapi/intelpython/latest/envs/modin/bin/ray", line 33, in <module>
    sys.exit(load_entry_point('ray==1.9.2', 'console_scripts', 'ray')())
  File "/opt/intel/oneapi/modin/0.13.3/lib/python3.9/site-packages/ray/scripts/scripts.py", line 1989, in main
    return cli()
  File "/opt/intel/oneapi/modin/0.13.3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/intel/oneapi/modin/0.13.3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/intel/oneapi/modin/0.13.3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/intel/oneapi/modin/0.13.3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/intel/oneapi/modin/0.13.3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/intel/oneapi/modin/0.13.3/lib/python3.9/site-packages/ray/scripts/scripts.py", line 644, in start
    with open(current_cluster_path, "w") as f:
PermissionError: [Errno 13] Permission denied: '/tmp/ray_current_cluster'`


After you view the file, you find that other users do not have the write permission for the file:
`[root@c1 ~]#  ll /tmp/ray_current_cluster
-rw-r--r-- 1 hpcadmin hpcadmin 21 May 30 14:08 /tmp/ray_current_cluster`

This caused me a puzzle, I do not know when to enable multiple users to use the normal

**Comment by xbinglzh** [comment]
This caused me a puzzle, I do not know when to enable multiple users to use the normal

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
