### ISSUE TITLE
[release][ml-nightly] torch_tune_serve is failing due to checkpointing issue

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#20685]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

https://buildkite.com/ray-project/periodic-ci/builds/1758#d15ac8ca-46e7-4ed6-86fe-d77b6e3a4d5e

```




(run pid=716) == Status ==
  | (run pid=716) Current time: 2021-11-23 10:28:24 (running for 00:05:53.92)
  | (run pid=716) Memory usage on this node: 2.6/61.4 GiB
  | (run pid=716) Using FIFO scheduling algorithm.
  | (run pid=716) Resources requested: 0/112 CPUs, 0/6 GPUs, 0.0/549.08 GiB heap, 0.0/233.9 GiB objects (0.0/3.0 accelerator_type:M60)
  | (run pid=716) Current best trial: 51c6e_00001 with val_loss=0.053586996829509737 and parameters={'lr': 0.001}
  | (run pid=716) Result logdir: /home/ray/ray_results/TorchTrainable_2021-11-23_10-22-30
  | (run pid=716) Number of trials: 2/2 (2 TERMINATED)
  | (run pid=716)
  | (run pid=716)
  | Retrieving best model.
  | Traceback (most recent call last):
  | File "workloads/torch_tune_serve_test.py", line 214, in <module>
  | model_id = get_remote_model(best_checkpoint)
  | File "workloads/torch_tune_serve_test.py", line 93, in get_remote_model
  | return ray.get(remote_load.remote(remote_model_checkpoint_path))
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
  | return getattr(ray, func.__name__)(*args, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/api.py", line 42, in get
  | return self.worker.get(vals, timeout=timeout)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 359, in get
  | res = self._get(to_get, op_timeout)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 386, in _get
  | raise err
  | types.RayTaskError(AttributeError): ray::get_model() (pid=716, ip=172.31.127.231)
  | AttributeError: 'TrialCheckpoint' object has no attribute 'seek'
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | ray::get_model() (pid=716, ip=172.31.127.231)
  | File "workloads/torch_tune_serve_test.py", line 101, in get_model
  | model_state = torch.load(model_checkpoint_path)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
  | with _open_file_like(f, 'rb') as opened_file:
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 235, in _open_file_like
  | return _open_buffer_reader(name_or_buffer)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 220, in __init__
  | _check_seekable(buffer)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 311, in _check_seekable
  | raise_err_msg(["seek", "tell"], e)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 304, in raise_err_msg
  | raise type(e)(msg)
  | AttributeError: 'TrialCheckpoint' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.

```

### Versions / Dependencies

nightly test failure for Tuesday 11/23

### Reproduction script

Nightly tests

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment]
Failed again here: https://buildkite.com/ray-project/periodic-ci/builds/1874#9a59617e-ff9a-4f8c-96b1-0cc10a0e6a47

**Comment by ericl** [comment]
Ping on this? Is this still broken or just flaky?

**Comment by architkulkarni** [comment]
Turns out this one is also flaky.  @ericl I would guess that flaky tests shouldn't be marked as release-blocker since the release manager can just rerun them.  But should it be P0 or P1?

**Comment by ericl** [comment]
If it's not being fixed urgently, it's not a P0.
