### ISSUE TITLE
[docker][on-premise clusters][local] work node can't start successfully

### ISSUE THREAD

**Issue by bing1zhi2** [ray-project/ray#20711]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

I run a cluster using a config file. The head node starts successfully,
```
Local node IP: 192.168.3.23
2021-11-24 03:24:13,426	INFO services.py:1272 -- View the Ray dashboard at http://127.0.0.1:8265
2021-11-24 03:24:13,428	WARNING services.py:1758 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 8589934592 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='192.168.3.23:63799' --redis-password='5241590000000000'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='5241590000000000')
  
  To connect to this Ray runtime from outside of the cluster, for example to
  connect to a remote cluster from your laptop directly, use the following
  Python code:
    import ray
    ray.init(address='ray://<head_node_ip_address>:10001')
  
  If connection fails, check your firewall settings and network configuration.
  
  To terminate the Ray runtime, run
    ray stop
Shared connection to 192.168.3.23 closed.
2021-11-24 19:24:14,881	INFO node_provider.py:103 -- ClusterState: Writing cluster state: ['192.168.3.24', '192.168.3.23']
  New status: up-to-date

Useful commands
  Monitor autoscaling with
    ray exec /data/xxx/develop/ait_service_feature_picquerypic/example-minimal-manual_docker.yaml 'tail -n 100 -f /tmp/ray/session_latest/logs/monitor*'
  Connect to a terminal on the cluster head:
    ray attach /data/xxx/develop/ait_service_feature_picquerypic/example-minimal-manual_docker.yaml
  Get a remote shell to the cluster manually:
    ssh -tt -o IdentitiesOnly=yes -i ~/.ssh/id_rsa xxx@192.168.3.23 docker exec -it ray_ait_docker_try /bin/bash

```
 but when monitoring autoscaling status using the given command, it shows some errors  says:
```
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
2021-11-24 19:24:23,107	INFO node_provider.py:43 -- ClusterState: Loaded cluster state: ['192.168.3.24', '192.168.3.23']
Fetched IP: 192.168.3.23
==> /tmp/ray/session_latest/logs/monitor.err <==
Warning: Permanently added '192.168.3.24' (ECDSA) to the list of known hosts.
Shared connection to 192.168.3.24 closed.

==> /tmp/ray/session_latest/logs/monitor.log <==
2021-11-24 03:24:12,540	INFO monitor.py:506 -- Starting monitor using ray installation: /home/ray/anaconda3/lib/python3.7/site-packages/ray/__init__.py
2021-11-24 03:24:12,540	INFO monitor.py:507 -- Ray version: 1.8.0
2021-11-24 03:24:12,540	INFO monitor.py:508 -- Ray commit: 72fdf3be605e4aadfd9a8c3f01dd7843c01cb8fd
2021-11-24 03:24:12,540	INFO monitor.py:509 -- Monitor started with command: ['/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py', '--logs-dir=/tmp/ray/session_2021-11-24_03-24-11_688537_185/logs', '--redis-address=192.168.3.23:63799', '--logging-rotate-bytes=536870912', '--logging-rotate-backup-count=5', '--autoscaling-config=/home/ray/ray_bootstrap_config.yaml', '--redis-password=5241590000000000', '--monitor-ip=192.168.3.23']
2021-11-24 03:24:12,549	INFO monitor.py:191 -- Starting autoscaler metrics server on port 44217
2021-11-24 03:24:12,550	INFO monitor.py:202 -- Monitor: Started
2021-11-24 03:24:12,625	INFO node_provider.py:43 -- ClusterState: Loaded cluster state: []
2021-11-24 03:24:12,626	INFO node_provider.py:103 -- ClusterState: Writing cluster state: ['192.168.3.24', '192.168.3.23']
2021-11-24 03:24:12,627	INFO autoscaler.py:204 -- StandardAutoscaler: {'cluster_name': 'docker_try', 'auth': {'ssh_user': 'xxx', 'ssh_private_key': '~/ray_bootstrap_key.pem'}, 'upscaling_speed': 1.0, 'idle_timeout_minutes': 5, 'docker': {'image': 'rayproject/ray:latest-cpu', 'container_name': 'ray_ait_docker_try', 'pull_before_run': False, 'run_options': ['--ulimit nofile=65536:65536', '--shm-size=8gb']}, 'initialization_commands': [], 'setup_commands': [], 'head_setup_commands': [], 'worker_setup_commands': [], 'head_start_ray_commands': ['ray stop', 'ulimit -c 0 && ray start --head  --port=63799 --autoscaling-config=~/ray_bootstrap_config.yaml'], 'worker_start_ray_commands': ['ray stop', 'ray start --address=$RAY_HEAD_IP:63799'], 'file_mounts': {}, 'cluster_synced_files': [], 'file_mounts_sync_continuously': False, 'rsync_exclude': [], 'rsync_filter': [], 'provider': {'type': 'local', 'head_ip': '192.168.3.23', 'worker_ips': ['192.168.3.24']}, 'available_node_types': {'local.cluster.node': {'node_config': {}, 'resources': {}, 'min_workers': 1, 'max_workers': 1}}, 'head_node_type': 'local.cluster.node', 'max_workers': 1, 'no_restart': False}
2021-11-24 03:24:12,638	INFO autoscaler.py:991 -- StandardAutoscaler: Queue 1 new nodes for launch
2021-11-24 03:24:12,638	INFO node_launcher.py:99 -- NodeLauncher0: Got 1 nodes to launch.
2021-11-24 03:24:12,639	INFO node_launcher.py:99 -- NodeLauncher0: Launching 1 nodes, type local.cluster.node.
2021-11-24 03:24:12,639	INFO autoscaler.py:267 -- 
======== Autoscaler status: 2021-11-24 03:24:12.639897 ========
Node status
---------------------------------------------------------------
Healthy:

Pending:
 local.cluster.node, 1 launching
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:


Demands:
 (no resource demands)
2021-11-24 03:24:12,640	INFO node_provider.py:103 -- ClusterState: Writing cluster state: ['192.168.3.24', '192.168.3.23']
2021-11-24 03:24:12,641	INFO monitor.py:329 -- :event_summary:Resized to 0 CPUs.
2021-11-24 03:24:12,641	INFO monitor.py:329 -- :event_summary:Adding 1 nodes of type local.cluster.node.
2021-11-24 03:24:17,668	INFO autoscaler.py:942 -- Creating new (spawn_updater) updater thread for node 192.168.3.24.
2021-11-24 03:24:17,671	INFO node_provider.py:103 -- ClusterState: Writing cluster state: ['192.168.3.24', '192.168.3.23']
2021-11-24 03:24:17,673	INFO autoscaler.py:267 -- 
======== Autoscaler status: 2021-11-24 03:24:17.673631 ========
Node status
---------------------------------------------------------------
Healthy:
 1 local.cluster.node
Pending:
 192.168.3.24: local.cluster.node, uninitialized
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/64.0 CPU
 0.0/2.0 GPU
 0.0/1.0 accelerator_type:T4
 0.00/106.706 GiB memory
 0.00/9.313 GiB object_store_memory

Demands:
 (no resource demands)
2021-11-24 03:24:17,684	INFO monitor.py:329 -- :event_summary:Resized to 64 CPUs, 2 GPUs.
2021-11-24 03:24:22,714	INFO autoscaler.py:267 -- 
======== Autoscaler status: 2021-11-24 03:24:22.714724 ========
Node status
---------------------------------------------------------------
Healthy:
 1 local.cluster.node
Pending:
 192.168.3.24: local.cluster.node, waiting-for-ssh
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/64.0 CPU
 0.0/2.0 GPU
 0.0/1.0 accelerator_type:T4
 0.00/106.706 GiB memory
 0.00/9.313 GiB object_store_memory

Demands:
 (no resource demands)
2021-11-24 03:24:24,279	INFO node_provider.py:103 -- ClusterState: Writing cluster state: ['192.168.3.24', '192.168.3.23']
2021-11-24 03:24:24,280	INFO node_provider.py:103 -- ClusterState: Writing cluster state: ['192.168.3.24', '192.168.3.23']

==> /tmp/ray/session_latest/logs/monitor.out <==
2021-11-24 03:24:17,672	INFO updater.py:296 -- New status: waiting-for-ssh
2021-11-24 03:24:17,672	INFO updater.py:241 -- [1/7] Waiting for SSH to become available
2021-11-24 03:24:17,673	INFO updater.py:244 -- Running `uptime` as a test.
2021-11-24 03:24:17,675	INFO command_runner.py:357 -- Fetched IP: 192.168.3.24
2021-11-24 03:24:17,675	INFO log_timer.py:27 -- NodeUpdater: 192.168.3.24: Got IP  [LogTimer=0ms]
2021-11-24 03:24:17,676	VINFO command_runner.py:509 -- Running `uptime`
2021-11-24 03:24:17,676	VVINFO command_runner.py:512 -- Full command is `ssh -tt -i ~/ray_bootstrap_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_070dd72385/814006f184/%C -o ControlPersist=10s -o ConnectTimeout=5s xxx@192.168.3.24 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'`
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
 19:24:24 up 105 days,  5:08, 16 users,  load average: 87.45, 87.09, 88.12
2021-11-24 03:24:24,278	SUCC updater.py:257 -- Success.
2021-11-24 03:24:24,278	INFO log_timer.py:27 -- NodeUpdater: 192.168.3.24: Got remote shell  [LogTimer=6605ms]
2021-11-24 03:24:24,278	INFO updater.py:337 -- Updating cluster configuration. [hash=659517a62e24f0e614aab2c240342bfe0f308fd3]
2021-11-24 03:24:24,279	INFO updater.py:341 -- New status: syncing-files
2021-11-24 03:24:24,279	INFO updater.py:219 -- [2/7] Processing file mounts
2021-11-24 03:24:24,280	INFO updater.py:236 -- [3/7] No worker file mounts to sync
2021-11-24 03:24:24,280	INFO updater.py:352 -- New status: setting-up
2021-11-24 03:24:24,280	INFO updater.py:390 -- [4/7] No initialization commands to run.
2021-11-24 03:24:24,281	INFO updater.py:394 -- [5/7] Initalizing command runner
2021-11-24 03:24:24,281	VINFO command_runner.py:509 -- Running `command -v docker || echo 'NoExist'`
2021-11-24 03:24:24,281	VVINFO command_runner.py:512 -- Full command is `ssh -tt -i ~/ray_bootstrap_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_070dd72385/814006f184/%C -o ControlPersist=10s -o ConnectTimeout=120s xxx@192.168.3.24 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (command -v docker || echo '"'"'NoExist'"'"')'`

==> /tmp/ray/session_latest/logs/monitor.err <==
Shared connection to 192.168.3.24 closed.

==> /tmp/ray/session_latest/logs/monitor.out <==
2021-11-24 03:24:25,207	VINFO command_runner.py:509 -- Running `docker image inspect rayproject/ray:latest-cpu 1> /dev/null  2>&1 || docker pull rayproject/ray:latest-cpu`
2021-11-24 03:24:25,207	VVINFO command_runner.py:512 -- Full command is `ssh -tt -i ~/ray_bootstrap_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_070dd72385/814006f184/%C -o ControlPersist=10s -o ConnectTimeout=120s xxx@192.168.3.24 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (docker image inspect rayproject/ray:latest-cpu 1> /dev/null  2>&1 || docker pull rayproject/ray:latest-cpu)'`
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)

==> /tmp/ray/session_latest/logs/monitor.err <==
Shared connection to 192.168.3.24 closed.

==> /tmp/ray/session_latest/logs/monitor.out <==
2021-11-24 03:24:26,252	VINFO command_runner.py:509 -- Running `docker inspect -f '{{.State.Running}}' ray_ait_docker_try || true`
2021-11-24 03:24:26,252	VVINFO command_runner.py:512 -- Full command is `ssh -tt -i ~/ray_bootstrap_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_070dd72385/814006f184/%C -o ControlPersist=10s -o ConnectTimeout=120s xxx@192.168.3.24 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (docker inspect -f '"'"'{{.State.Running}}'"'"' ray_ait_docker_try || true)'`

==> /tmp/ray/session_latest/logs/monitor.err <==
Shared connection to 192.168.3.24 closed.

==> /tmp/ray/session_latest/logs/monitor.log <==
2021-11-24 03:24:27,736	INFO autoscaler.py:267 -- 
======== Autoscaler status: 2021-11-24 03:24:27.736335 ========
Node status
---------------------------------------------------------------
Healthy:
 1 local.cluster.node
Pending:
 192.168.3.24: local.cluster.node, setting-up
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/64.0 CPU
 0.0/2.0 GPU
 0.0/1.0 accelerator_type:T4
 0.00/106.706 GiB memory
 0.00/9.313 GiB object_store_memory

Demands:
 (no resource demands)

==> /tmp/ray/session_latest/logs/monitor.out <==
2021-11-24 03:24:27,307	VINFO command_runner.py:509 -- Running `docker inspect -f '{{json .Config.Env}}' rayproject/ray:latest-cpu`
2021-11-24 03:24:27,308	VVINFO command_runner.py:512 -- Full command is `ssh -tt -i ~/ray_bootstrap_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_070dd72385/814006f184/%C -o ControlPersist=10s -o ConnectTimeout=120s xxx@192.168.3.24 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (docker inspect -f '"'"'{{json .Config.Env}}'"'"' rayproject/ray:latest-cpu)'`

==> /tmp/ray/session_latest/logs/monitor.err <==
Shared connection to 192.168.3.24 closed.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 134, in run
    self.do_update()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 398, in do_update
    sync_run_yet=True)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/command_runner.py", line 850, in run_init
    for env_var in json.loads(image_env):
  File "/home/ray/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/ray/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ray/anaconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

When I try `docker inspect -f '{{json .Config.Env}}' rayproject/ray:latest-cpu` in worker node, it seems no problem, but the container didn't start up.So I use `docker run --rm --name ray_ait_docker_try -d -it  -e LC_ALL=C.UTF-8 -e LANG=C.UTF-8 --ulimit nofile=65536:65536 --shm-size=8gb --runtime=nvidia --net=host rayproject/ray:latest-cpu bash` to manually start up docker image and restart the cluster using 'ray up ', everything works fun. Why can't I use 'ray up' to automatically start all nodes?

### Versions / Dependencies

Ray 1.8.0
rayproject/ray:latest-cpu  (ray 1.8.0)

### Reproduction script

```
ray up example-minimal-manual_docker.yaml -v
```
```
cluster_name: docker_try

docker:
  image: "rayproject/ray:latest-cpu" # use this one if you don't need ML dependencies, it's faster to pull
  container_name: "ray_ait_docker_try"
  pull_before_run: False
  run_options: # Extra options to pass into "docker run"
    - --ulimit nofile=65536:65536
    - --shm-size=8gb


provider:
  type: local
  head_ip: "192.168.3.23"
  worker_ips: ["192.168.3.24"]

# How Ray will authenticate with newly launched nodes.
auth:
  ssh_user: xxx
  # Optional if an ssh private key is necessary to ssh to the cluster.
  ssh_private_key: ~/.ssh/id_rsa

head_start_ray_commands:
  - ray stop
  - ulimit -c unlimited && ray start --head  --port=63799 --node-ip-address=192.168.3.23 --dashboard-host=192.168.3.23 --resources='{"readers": 20,"result_geters":14 }'

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
  - ray stop
  - ray start --address=$RAY_HEAD_IP:63799
```

### Anything else

every time

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by chuckhope** [comment]
same problem, ray up yaml cannot connect to the worker node without error info

**Comment by chuckhope** [comment]
Update: I have faced the issues since "Only head node provisioned, worker nodes untouched", the worker is remaining as 'waiting-for-ssh' and I am sure both my head and worker have the same ssh username for connection. Commenting out the ssh_private_key: ~/.ssh/id_rsa is not helpful, Do you have any ideas, thank you @richardliaw

**Comment by bing1zhi2** [comment]
Update: I solved my problem by adding "min_workers" and max_workers" options in the config file. In my case, I set value 1 for them. Everything is fun.

**Comment by bing1zhi2** [comment]
> Update: I solved my problem by adding "min_workers" and max_workers" options in the config file. In my case, I set value 1 for them. Everything is fun.
 
I was set 2 in this field before I realized that I actually only have 1 work node.

**Comment by bing1zhi2** [comment]
> Update: I have faced the issues since "Only head node provisioned, worker nodes untouched", the worker is remaining as 'waiting-for-ssh' and I am sure both my head and worker have the same ssh username for connection. Commenting out the ssh_private_key: ~/.ssh/id_rsa is not helpful, Do you have any ideas, thank you @richardliaw

Have you checked your firewall?

**Comment by chuckhope** [comment]
@bing1zhi2 hi, do u have any idea what should I check for my worker and head's firewall, e.g. port or anything else, thank you

**Comment by bing1zhi2** [comment]
@chuckhope I just shut down the firewall, and most problems have gone. Or you could read the official document to find out which port is used. For example, https://docs.ray.io/en/master/configure.html#ports-configurations. Hope it will be helpful.

**Comment by chuckhope** [comment]
@bing1zhi2 Thank u, I have figured out that my problem exists in an incomplete log and user's privilege.
