### ISSUE TITLE
[Bug] Ray not passing keyword argument properly when propagating exceptions from task

### ISSUE THREAD

**Issue by yifeif** [ray-project/ray#20830]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Seeing the following error when trying to initialize the exception from a ray task by passing in keyword argument, but it works as a positional argument.
```
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/Users/yifei/Code/.env/lib/python3.7/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "test.py", line 21, in do_work_remotely_outer
    ray.get(do_work_remotely.remote())
  File "/Users/yifei/Code/.env/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
ray.exceptions.RaySystemError: System error: __init__() missing 1 required positional argument: 'status_code'
traceback: Traceback (most recent call last):
  File "/Users/yifei/Code/.env/lib/python3.7/site-packages/ray/serialization.py", line 248, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/Users/yifei/Code/.env/lib/python3.7/site-packages/ray/serialization.py", line 213, in _deserialize_object
    return RayError.from_bytes(obj)
  File "/Users/yifei/Code/.env/lib/python3.7/site-packages/ray/exceptions.py", line 29, in from_bytes
    return pickle.loads(ray_exception.serialized_exception)
TypeError: __init__() missing 1 required positional argument: 'status_code'
```

### Versions / Dependencies

latest, any python version, any OS version

### Reproduction script

```
import ray


class HTTPException(Exception):
    def __init__(self, status_code: int):
        self.status_code = status_code


def do_work():
    raise HTTPException(status_code=404)


@ray.remote
def do_work_remotely():
    do_work()


if __name__ == "__main__":
    ray.init()
    
    try:
        ray.get(do_work_remotely.remote())
    except HTTPException as e:
        assert e.status_code == 404, "Incorrect status code"
```
It works if `status_code=` is removed from `raise HTTPException(status_code=404)`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
turned out to be not a ray issue, the following code throws the same exception without ray.


```
import pickle

class HTTPException(Exception):
    def __init__(self, status_code: int):
        self.status_code = status_code


b = HTTPException(status_code=404)
pickle.loads(pickle.dumps(b))
```

probably you need to follow this to make the exception picklable.

https://stackoverflow.com/questions/16244923/how-to-make-a-custom-exception-class-with-multiple-init-args-pickleable

**Comment by scv119** [comment]
cc @yifeif
