### ISSUE TITLE
[Bug] tune.run uses methods that are not in ProgressReporter, again

### ISSUE THREAD

**Issue by andrew-rosenfeld-ts** [ray-project/ray#20902]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

This is basically the same issue as I reported in #13153, except it has happened again in a new way.

"While the docs say you can write your own custom ProgressReporter, tune.run() calls methods that are not in ProgressReporter."

When I run the repro script below, I get 

```python
Traceback (most recent call last):
  File "/home/andrew/tmp/ray_progress_reporter_repro.py", line 28, in <module>
    tune.run(
  File "/home/andrew/miniconda3/envs/ray_1.9_progress_reporter_repro/lib/python3.9/site-packages/ray/tune/tune.py", line 595, in run
    progress_reporter.set_start_time(tune_start)
AttributeError: 'CustomReporter' object has no attribute 'set_start_time'
```

It looks like https://github.com/ray-project/ray/pull/19139 is what broke it.

Can unit tests on `ProgressReporter` please be added? If it's actually `PublicAPI`, I think at least one unit test that instantiates it and puts it in a tune run (as in my demo script) should be part of the testing suite. That would have caught both this issue and #13153. 

As for the fix: I would also note that it seems like implementation details are finding themselves into the ProgressReporter API. Sure, people can implement no-ops, but it's a bit ugly. `should_report` and `report` seem like base functionality, but I doubt `set_search_properties`, `set_total_samples` belong there, and not sure about this new `set_start_time`. I think it would be cleaner for users if usage of these methods was hidden inside tune somehow. (could conditionally test for these methods before calling them, could instead do some sort of double dispatch kind of mechanism, etc)

### Versions / Dependencies

Ray 1.9.0 
(other libraries aren't relevant)

### Reproduction script

```
from ray import tune
from ray.tune import ProgressReporter


class CustomReporter(ProgressReporter):

    def should_report(self, trials, done=False):
        return True

    def report(self, trials, done, *sys_info):
        pass


def objective(step, alpha, beta):
    return (0.1 + alpha * step / 100)**(-1) + beta * 0.1


def training_function(config):
    # Hyperparameters                                                                                                                                                                                              
    alpha, beta = config["alpha"], config["beta"]
    for step in range(10):
        # Iterative training function - can be any arbitrary training procedure.                                                                                                                                   
        intermediate_score = objective(step, alpha, beta)
        # Feed the score back back to Tune.                                                                                                                                                                        
        tune.report(mean_loss=intermediate_score)


tune.run(
    training_function,
    config={
        "alpha": tune.grid_search([0.001, 0.01, 0.1]),
        "beta": tune.choice([1, 2, 3])
    },
    progress_reporter=CustomReporter())

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by andrew-rosenfeld-ts** [comment]
Still an issue in 1.11.0.

**Comment by andrew-rosenfeld-ts** [comment]
Yes, this is much better. I definitely appreciate the unit test that should prevent this from happening again. Thanks!
