### ISSUE TITLE
ValueError: `hyperparam_bounds` values must either be a list or tuple of size 2, but got <ray.tune.sample.Float object at 0x7f66710b4490> instead

### ISSUE THREAD

**Issue by etetteh** [ray-project/ray#20923]
Something is broken, and I can't seem to understand why...
My code looks as follows:
```
def main(cfg):
    data_dir = os.path.abspath(cfg.data_dir)
    
    config = {}
    if cfg.lr_optim:
        config["lr"] = tune.qloguniform(1e-4, 1e-1, 1e-5)
        config["lr_warmup_decay"] = tune.qloguniform(1e-5, 1e-3, 1e-6)
        config["lr_warmup_epochs"] = tune.qrandint(3, 15, 3)
        config["batch_size"] = tune.grid_search([16, 32, 64, 128])

    if cfg.pb2:
        scheduler = pb2.PB2(
            time_attr="training_iteration",
            metric="accuracy",
            mode="max",
            perturbation_interval=300.0,
            hyperparam_bounds=config
        )

    reporter = CLIReporter(
        metric_columns=["loss", "accuracy", "training_iteration"])
        
    result = tune.run(
        partial(train, data_dir=data_dir),
        name=cfg.name,
        resources_per_trial={"cpu": cfg.cpus_per_trial, "gpu": cfg.gpus_per_trial},
        config=config,
        num_samples=cfg.num_samples,
        scheduler=scheduler,
        stop={"accuracy": 0.99},
        resume="AUTO",
        progress_reporter=reporter
    )
    ...
```

I am getting the following error
```
ython tunedtrain.py --name deit_tiny_hymenoptera --bce --lr_optim --pb2
{'lr': <ray.tune.sample.Float object at 0x7f66710b4490>, 'lr_warmup_decay': <ray.tune.sample.Float object at 0x7f66710b4460>, 'lr_warmup_epochs': <ray.tune.sample.Integer object at 0x7f66710b4400>, 'batch_size': {'grid_search': [16, 32, 64, 128]}, 'interpolation': <ray.tune.sample.Categorical object at 0x7f66710b4790>}
Traceback (most recent call last):
  File "/home/enoch/Documents/vision/classification/tunedtrain.py", line 517, in <module>
    result = main(cfg)
  File "/home/enoch/Documents/vision/classification/tunedtrain.py", line 401, in main
    scheduler = pb2.PB2(
  File "/home/enoch/miniforge3/lib/python3.9/site-packages/ray/tune/schedulers/pb2.py", line 288, in __init__
    raise ValueError("`hyperparam_bounds` values must either be "
ValueError: `hyperparam_bounds` values must either be a list or tuple of size 2, but got <ray.tune.sample.Float object at 0x7f66710b4490> instead
```

**Comment by scv119** [comment]
cc @richardliaw

**Comment by scv119** [comment]
also cc @krfricke

**Comment by etetteh** [comment]
Please, any update?

**Comment by krfricke** [comment]
Hi @etetteh, for the `hyperparam_bounds`, you should specify a dict of value bounds:

```
 if cfg.pb2:
        scheduler = pb2.PB2(
            time_attr="training_iteration",
            metric="accuracy",
            mode="max",
            perturbation_interval=300.0,
            hyperparam_bounds={
                "lr": [1e-4, 1e-1],
                "lr_warmup_decay": [1e-5, 1e-3],
                "lr_warmup_epochs": [3, 15],
            }
        )

```

See also the documentation here: https://docs.ray.io/en/master/tune/api_docs/schedulers.html#population-based-bandits-pb2-tune-schedulers-pb2-pb2

**Comment by krfricke** [comment]
Maybe for a bit more detail: PB2 uses Bayesian optimization to sample new hyperparameters. BO only works with bounds, not with specific sampling methods. This is also the reason why you can't use any categorical hyperparameters here.

**Comment by etetteh** [comment]
Thanks. I solved the problem yesterday. I changed the code to set the
bounds, instead of the sampling method.
We may close the issue.
