### ISSUE TITLE
tune runtime error

### ISSUE THREAD

**Issue by dustingan** [ray-project/ray#20932]
when I use ray.tune, there are a error about runtime.  how do I pass the queue in a way that works? I can't find an example, and I've tried several alternatives that failed in various ways. Help please?

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\行者生产环境\tune_hyperhyperparameters.py", line 105, in <module>
    analysis = tune.run(training_function, config={
  File "D:\强化学习\FinRL-master\venv\lib\site-packages\ray\tune\tune.py", line 425, in run
    experiments[i] = Experiment(
  File "D:\强化学习\FinRL-master\venv\lib\site-packages\ray\tune\experiment.py", line 113, in __init__
    self._run_identifier = Experiment.register_if_needed(run)
  File "D:\强化学习\FinRL-master\venv\lib\site-packages\ray\tune\experiment.py", line 258, in register_if_needed
    register_trainable(name, run_object)
  File "D:\强化学习\FinRL-master\venv\lib\site-packages\ray\tune\registry.py", line 76, in register_trainable
    _global_registry.register(TRAINABLE_CLASS, name, trainable)
  File "D:\强化学习\FinRL-master\venv\lib\site-packages\ray\tune\registry.py", line 150, in register
    self._to_flush[(category, key)] = pickle.dumps_debug(value)
  File "D:\强化学习\FinRL-master\venv\lib\site-packages\ray\cloudpickle\__init__.py", line 39, in dumps_debug
    return dumps(obj, *args, **kwargs)
  File "D:\强化学习\FinRL-master\venv\lib\site-packages\ray\cloudpickle\cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "D:\强化学习\FinRL-master\venv\lib\site-packages\ray\cloudpickle\cloudpickle_fast.py", line 620, in dump
    return Pickler.dump(self, obj)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\queues.py", line 58, in __getstate__
    context.assert_spawning(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 359, in assert_spawning
    raise RuntimeError(
RuntimeError: Queue objects should only be shared between processes through inheritance

Process finished with exit code 1

**Comment by scv119** [comment]
hi dustingan could you share a bit more code snippet for reproducing this issue?

**Comment by krfricke** [comment]
Generally `multiprocessing.Queue` objects should be avoided - you can use `ray.util.queue.Queue` instead. Generally this seems like an antipattern though. If you can share some code we might be able to help.
