### ISSUE TITLE
[Bug] [Train] Horovod trainer error in multiple nodes cluster

### ISSUE THREAD

**Issue by kira-lin** [ray-project/ray#20956]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Train

### What happened + What you expected to happen

I ran the example [here](https://docs.ray.io/en/master/train/examples/horovod/horovod_example.html) with default args, but it fails as following:
```
2021-12-08 10:39:50,622 INFO services.py:1338 -- View the Ray dashboard at http://127.0.0.1:8266
2021-12-08 10:39:51,863 INFO trainer.py:172 -- Trainer logs will be logged in: /home/lzhi/ray_results/train_2021-12-08_10-39-51
Traceback (most recent call last):
  File "demo_horovod.py", line 262, in <module>
    main(num_workers=args.num_workers, use_gpu=use_cuda, kwargs=kwargs)
  File "demo_horovod.py", line 147, in main
    trainer.start()
  File "/home/lzhi/miniconda3/envs/raydp/lib/python3.8/site-packages/ray/train/trainer.py", line 213, in start
    ray.get(self._backend_executor_actor.start.remote(initialization_hook))
  File "/home/lzhi/miniconda3/envs/raydp/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/lzhi/miniconda3/envs/raydp/lib/python3.8/site-packages/ray/worker.py", line 1713, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::BackendExecutor.start() (pid=344854, ip=10.112.228.4, repr=<ray.train.backend.BackendExecutor object at 0x7f0665ae6c10>)
  File "/home/lzhi/miniconda3/envs/raydp/lib/python3.8/site-packages/ray/train/backend.py", line 177, in start
    self._backend.on_start(self.worker_group, self._backend_config)
  File "/home/lzhi/miniconda3/envs/raydp/lib/python3.8/site-packages/ray/train/horovod.py", line 143, in on_start
    nics = detect_nics(
  File "/home/lzhi/miniconda3/envs/raydp/lib/python3.8/site-packages/horovod/ray/utils.py", line 71, in detect_nics
    nics = _driver_fn(workers, all_host_names, local_host_names,
  File "/home/lzhi/miniconda3/envs/raydp/lib/python3.8/site-packages/horovod/ray/driver_service.py", line 47, in _driver_fn
    raise ValueError(f"Number of node actors ({len(node_actors)}) "
ValueError: Number of node actors (2) must match num_hosts (1).
```

### Versions / Dependencies

ray 1.9.0, horovod 0.23.0

### Reproduction script

The [hotovod_example](https://docs.ray.io/en/master/train/examples/horovod/horovod_example.html) in doc.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kira-lin** [comment]
I have multiple workers on one node. The number of node actors is the same as the config for `num_workers`, but num_hosts is the number of distinct hosts. Why are they equal? How to solve it?

**Comment by vijayi1** [comment]
Has this issue been resolved? 
I got it to work with the following patch (but I'm not sure that its the right fix).

diff --git a/horovod/ray/driver_service.py b/horovod/ray/driver_service.py
index b3c9d72..58f242a 100644
--- a/horovod/ray/driver_service.py
+++ b/horovod/ray/driver_service.py
@@ -38,18 +38,14 @@ def _driver_fn(node_actors, all_host_names, local_host_names, settings):
     :rtype: list[string]
     """
     # Launch a TCP server called driver service on the host running horovod
-    num_hosts = len(all_host_names)
+    num_hosts = len(node_actors)
     driver = HorovodRunDriverService(num_hosts, settings.key, settings.nics)
     if settings.verbose >= 2:
         print('Launched horovod server.')
     # Have all the workers register themselves with the service service.
-    if len(node_actors) != num_hosts:
-        raise ValueError(f"Number of node actors ({len(node_actors)}) "
-                         f"must match num_hosts ({num_hosts}).")
-
     _actor_launch_task_servers(
         node_actors=node_actors,
-        num_hosts=len(all_host_names),
+        num_hosts=num_hosts,
         driver_addresses=driver.addresses(),
         settings=settings)
