### ISSUE TITLE
[Bug] argparser

### ISSUE THREAD

**Issue by keyboardAnt** [ray-project/ray#21037]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I implemented an argparser and call it. Unfortunately, it makes Ray fail. I couldn't find a minimal example that reproduces it.
Thought you might wanna know.
Tnx.

```
(pid=14730) usage: default_worker.py [-h] [--depth DEPTH] [--label_dim LABEL_DIM]
(pid=14730)                          [--loss_fn {mse,sum_of_exp}]
(pid=14730)                          [--num_of_simulators NUM_OF_SIMULATORS]
(pid=14730)                          [--max_epochs MAX_EPOCHS]
(pid=14730)                          [--weight_decay WEIGHT_DECAY]
(pid=14730)                          [--random_seed_offset RANDOM_SEED_OFFSET]
(pid=14730) default_worker.py: error: unrecognized arguments: --node-ip-address=127.0.0.1 --node-manager-port=58137 --object-store-name=/tmp/ray/session_2021-12-11_16-46-36_864794_14705/sockets/plasma_store --raylet-name=/tmp/ray/session_2021-12-11_16-46-36_864794_14705/sockets/raylet --redis-address=127.0.0.1:14950 --temp-dir=/tmp/ray --metrics-agent-port=64401 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --redis-password=5241590000000000 --startup-token=6
(pid=14726) usage: default_worker.py [-h] [--depth DEPTH] [--label_dim LABEL_DIM]
(pid=14726)                          [--loss_fn {mse,sum_of_exp}]
(pid=14726)                          [--num_of_simulators NUM_OF_SIMULATORS]
(pid=14726)                          [--max_epochs MAX_EPOCHS]
(pid=14726)                          [--weight_decay WEIGHT_DECAY]
(pid=14726)                          [--random_seed_offset RANDOM_SEED_OFFSET]
(pid=14726) default_worker.py: error: unrecognized arguments: --node-ip-address=127.0.0.1 --node-manager-port=58137 --object-store-name=/tmp/ray/session_2021-12-11_16-46-36_864794_14705/sockets/plasma_store --raylet-name=/tmp/ray/session_2021-12-11_16-46-36_864794_14705/sockets/raylet --redis-address=127.0.0.1:14950 --temp-dir=/tmp/ray --metrics-agent-port=64401 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --redis-password=5241590000000000 --startup-token=2
(pid=14729) usage: default_worker.py [-h] [--depth DEPTH] [--label_dim LABEL_DIM]
(pid=14729)                          [--loss_fn {mse,sum_of_exp}]
(pid=14729)                          [--num_of_simulators NUM_OF_SIMULATORS]
(pid=14729)                          [--max_epochs MAX_EPOCHS]
(pid=14729)                          [--weight_decay WEIGHT_DECAY]
(pid=14729)                          [--random_seed_offset RANDOM_SEED_OFFSET]
(pid=14729) default_worker.py: error: unrecognized arguments: --node-ip-address=127.0.0.1 --node-manager-port=58137 --object-store-name=/tmp/ray/session_2021-12-11_16-46-36_864794_14705/sockets/plasma_store --raylet-name=/tmp/ray/session_2021-12-11_16-46-36_864794_14705/sockets/raylet --redis-address=127.0.0.1:14950 --temp-dir=/tmp/ray --metrics-agent-port=64401 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --redis-password=5241590000000000 --startup-token=5
(pid=14724) usage: default_worker.py [-h] [--depth DEPTH] [--label_dim LABEL_DIM]
(pid=14724)                          [--loss_fn {mse,sum_of_exp}]
(pid=14724)                          [--num_of_simulators NUM_OF_SIMULATORS]
(pid=14724)                          [--max_epochs MAX_EPOCHS]
(pid=14724)                          [--weight_decay WEIGHT_DECAY]
(pid=14724)                          [--random_seed_offset RANDOM_SEED_OFFSET]
(pid=14724) default_worker.py: error: unrecognized arguments: --node-ip-address=127.0.0.1 --node-manager-port=58137 --object-store-name=/tmp/ray/session_2021-12-11_16-46-36_864794_14705/sockets/plasma_store --raylet-name=/tmp/ray/session_2021-12-11_16-46-36_864794_14705/sockets/raylet --redis-address=127.0.0.1:14950 --temp-dir=/tmp/ray --metrics-agent-port=64401 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --redis-password=5241590000000000 --startup-token=0
(pid=14727) usage: default_worker.py [-h] [--depth DEPTH] [--label_dim LABEL_DIM]
(pid=14727)                          [--loss_fn {mse,sum_of_exp}]
(pid=14727)                          [--num_of_simulators NUM_OF_SIMULATORS]
(pid=14727)                          [--max_epochs MAX_EPOCHS]
(pid=14727)                          [--weight_decay WEIGHT_DECAY]
(pid=14727)                          [--random_seed_offset RANDOM_SEED_OFFSET]
(pid=14727) default_worker.py: error: unrecognized arguments: --node-ip-address=127.0.0.1 --node-manager-port=58137 --object-store-name=/tmp/ray/session_2021-12-11_16-46-36_864794_14705/sockets/plasma_store --raylet-name=/tmp/ray/session_2021-12-11_16-46-36_864794_14705/sockets/raylet --redis-address=127.0.0.1:14950 --temp-dir=/tmp/ray --metrics-agent-port=64401 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --redis-password=5241590000000000 --startup-token=3
(pid=14731) usage: default_worker.py [-h] [--depth DEPTH] [--label_dim LABEL_DIM]
(pid=14731)                          [--loss_fn {mse,sum_of_exp}]
(pid=14731)                          [--num_of_simulators NUM_OF_SIMULATORS]
(pid=14731)                          [--max_epochs MAX_EPOCHS]
(pid=14731)                          [--weight_decay WEIGHT_DECAY]
(pid=14731)                          [--random_seed_offset RANDOM_SEED_OFFSET]
(pid=14731) default_worker.py: error: unrecognized arguments: --node-ip-address=127.0.0.1 --node-manager-port=58137 --object-store-name=/tmp/ray/session_2021-12-11_16-46-36_864794_14705/sockets/plasma_store --raylet-name=/tmp/ray/session_2021-12-11_16-46-36_864794_14705/sockets/raylet --redis-address=127.0.0.1:14950 --temp-dir=/tmp/ray --metrics-agent-port=64401 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --redis-password=5241590000000000 --startup-token=7
(pid=14728) usage: default_worker.py [-h] [--depth DEPTH] [--label_dim LABEL_DIM]
(pid=14728)                          [--loss_fn {mse,sum_of_exp}]
(pid=14728)                          [--num_of_simulators NUM_OF_SIMULATORS]
(pid=14728)                          [--max_epochs MAX_EPOCHS]
(pid=14728)                          [--weight_decay WEIGHT_DECAY]
(pid=14728)                          [--random_seed_offset RANDOM_SEED_OFFSET]
(pid=14728) default_worker.py: error: unrecognized arguments: --node-ip-address=127.0.0.1 --node-manager-port=58137 --object-store-name=/tmp/ray/session_2021-12-11_16-46-36_864794_14705/sockets/plasma_store --raylet-name=/tmp/ray/session_2021-12-11_16-46-36_864794_14705/sockets/raylet --redis-address=127.0.0.1:14950 --temp-dir=/tmp/ray --metrics-agent-port=64401 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --redis-password=5241590000000000 --startup-token=4
(pid=14725) usage: default_worker.py [-h] [--depth DEPTH] [--label_dim LABEL_DIM]
(pid=14725)                          [--loss_fn {mse,sum_of_exp}]
(pid=14725)                          [--num_of_simulators NUM_OF_SIMULATORS]
(pid=14725)                          [--max_epochs MAX_EPOCHS]
(pid=14725)                          [--weight_decay WEIGHT_DECAY]
(pid=14725)                          [--random_seed_offset RANDOM_SEED_OFFSET]
(pid=14725) default_worker.py: error: unrecognized arguments: --node-ip-address=127.0.0.1 --node-manager-port=58137 --object-store-name=/tmp/ray/session_2021-12-11_16-46-36_864794_14705/sockets/plasma_store --raylet-name=/tmp/ray/session_2021-12-11_16-46-36_864794_14705/sockets/raylet --redis-address=127.0.0.1:14950 --temp-dir=/tmp/ray --metrics-agent-port=64401 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --redis-password=5241590000000000 --startup-token=1
2021-12-11 16:46:50,338	WARNING worker.py:1245 -- This worker was asked to execute a function that it does not have registered. You may have to restart Ray.
2021-12-11 16:46:50,339	WARNING worker.py:1245 -- This worker was asked to execute a function that it does not have registered. You may have to restart Ray.
2021-12-11 16:46:50,339	WARNING worker.py:1245 -- This worker was asked to execute a function that it does not have registered. You may have to restart Ray.
2021-12-11 16:46:50,339	WARNING worker.py:1245 -- This worker was asked to execute a function that it does not have registered. You may have to restart Ray.
2021-12-11 16:46:50,340	WARNING worker.py:1245 -- This worker was asked to execute a function that it does not have registered. You may have to restart Ray.
2021-12-11 16:46:50,340	WARNING worker.py:1245 -- This worker was asked to execute a function that it does not have registered. You may have to restart Ray.
2021-12-11 16:46:50,340	WARNING worker.py:1245 -- This worker was asked to execute a function that it does not have registered. You may have to restart Ray.
2021-12-11 16:46:50,340	WARNING worker.py:1245 -- This worker was asked to execute a function that it does not have registered. You may have to restart Ray.
```

### Versions / Dependencies

Versions:
python = 3.8
ray = 1.9.0

### Reproduction script

TBD.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by keyboardAnt** [comment]
There's no exception when initiating Ray with the `local_mode=True` flag (i.e., calling `ray.init(local_mode=True)`).

**Comment by keyboardAnt** [comment]
By changing the implementation from using a remote worker function to using an actor class with an empty `__init__`, I received the following traceback:
```
(pid=22987) usage: default_worker.py [-h] [--depth DEPTH] [--label_dim LABEL_DIM]
(pid=22987)                          [--loss_fn {mse,sum_of_exp}]
(pid=22987)                          [--num_of_simulators NUM_OF_SIMULATORS]
(pid=22987)                          [--max_epochs MAX_EPOCHS]
(pid=22987)                          [--weight_decay WEIGHT_DECAY]
(pid=22987)                          [--random_seed_offset RANDOM_SEED_OFFSET]
(pid=22987) default_worker.py: error: unrecognized arguments: --node-ip-address=127.0.0.1 --node-manager-port=57768 --object-store-name=/tmp/ray/session_2021-12-12_17-51-04_282496_22971/sockets/plasma_store --raylet-name=/tmp/ray/session_2021-12-12_17-51-04_282496_22971/sockets/raylet --redis-address=127.0.0.1:48060 --temp-dir=/tmp/ray --metrics-agent-port=58706 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --redis-password=5241590000000000 --startup-token=4
(pid=22987) 2021-12-12 17:51:13,371	ERROR worker.py:431 -- SystemExit was raised from the worker
(pid=22987) Traceback (most recent call last):
(pid=22987)   File "python/ray/_raylet.pyx", line 759, in ray._raylet.task_execution_handler
(pid=22987)   File "python/ray/_raylet.pyx", line 492, in ray._raylet.execute_task
(pid=22987)   File "/Users/timor/source_codes/github/ir-erank-2021/venv/lib/python3.8/site-packages/ray/_private/function_manager.py", line 451, in load_actor_class
(pid=22987)     actor_class = self._load_actor_class_from_gcs(
(pid=22987)   File "/Users/timor/source_codes/github/ir-erank-2021/venv/lib/python3.8/site-packages/ray/_private/function_manager.py", line 564, in _load_actor_class_from_gcs
(pid=22987)     actor_class = pickle.loads(pickled_class)
(pid=22987)   File "/Users/timor/source_codes/github/ir-erank-2021/ir/modules/simulator.py", line 12, in <module>
(pid=22987)     from ir.config.hyperparams import hyperparams
(pid=22987)   File "/Users/timor/source_codes/github/ir-erank-2021/ir/config/hyperparams.py", line 90, in <module>
(pid=22987)     hyperparams = Hyperparams()
(pid=22987)   File "/Users/timor/source_codes/github/ir-erank-2021/ir/config/hyperparams.py", line 81, in __init__
(pid=22987)     self._args: Namespace = HyperparamsParser().parse_args()
(pid=22987)   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/argparse.py", line 1771, in parse_args
(pid=22987)     self.error(msg % ' '.join(argv))
(pid=22987)   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/argparse.py", line 2521, in error
(pid=22987)     self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
(pid=22987)   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/argparse.py", line 2508, in exit
(pid=22987)     _sys.exit(status)
(pid=22987) SystemExit: 2
2021-12-12 17:51:13,397	WARNING worker.py:1245 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff6bd89f5b5792b36261f66aef01000000 Worker ID: 74acc9f4f4096d6ba59460dc5d41567b940c37d0786395ce7b922f02 Node ID: a96e6a942936f45402e277becc49de4f164176b4912d075c40638c79 Worker IP address: 127.0.0.1 Worker port: 57808 Worker PID: 22987
2021-12-12 17:51:13,556	WARNING worker.py:1245 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffccc4c65c7c5292d7e583c43801000000 Worker ID: 51be1defa170ab84bb3353ea3028662e0435f30e82bfc82b951ee52d Node ID: a96e6a942936f45402e277becc49de4f164176b4912d075c40638c79 Worker IP address: 127.0.0.1 Worker port: 57794 Worker PID: 22983
2021-12-12 17:51:13,580	WARNING worker.py:1245 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff096eab453de535f440fa726901000000 Worker ID: b37b8ff074999e02e54f4dddc774ca7284aa824510bd3fff37033027 Node ID: a96e6a942936f45402e277becc49de4f164176b4912d075c40638c79 Worker IP address: 127.0.0.1 Worker port: 57835 Worker PID: 22989
```

**Comment by MattSkiff** [comment]
Was there a resolution to this issue? I am facing the same problem.
