### ISSUE TITLE
[Bug] NoneType has no attribute _hash

### ISSUE THREAD

**Issue by spolcyn** [ray-project/ray#21054]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

In a long-running job, the ServeController eventually went down. When it tried to restore the deployments, it ran into an error:
```
2021-12-13 19:02:56,454	INFO backend_state.py:647 -- Recovering target state for deployment placeholder-name from checkpoint..
--
  | 2021-12-13 19:02:56,455	INFO backend_state.py:672 -- Recovering current state for deployment placeholder-name from 1 actors in current ray cluster..
  | 2021-12-13 19:03:01,495	ERROR controller.py:194 -- Exception updating backend state.
  | Traceback (most recent call last):
  | File "/venv/lib/python3.7/site-packages/ray/serve/controller.py", line 192, in run_control_loop
  | self.backend_state_manager.update()
  | File "/venv/lib/python3.7/site-packages/ray/serve/backend_state.py", line 1354, in update
  | deleted = backend_state.update()
  | File "/venv/lib/python3.7/site-packages/ray/serve/backend_state.py", line 1116, in update
  | running_replicas_changed \|= self._check_and_update_replicas()
  | File "/venv/lib/python3.7/site-packages/ray/serve/backend_state.py", line 1088, in _check_and_update_replicas
  | 0].resource_requirements()
  | File "/venv/lib/python3.7/site-packages/ray/serve/backend_state.py", line 467, in resource_requirements
  | for k, v in self._actor.actor_resources.items() if v > 0
  | AttributeError: 'NoneType' object has no attribute 'items'
  | 2021-12-13 19:03:01,663	ERROR controller.py:194 -- Exception updating backend state.
  | Traceback (most recent call last):
  | File "/venv/lib/python3.7/site-packages/ray/serve/controller.py", line 192, in run_control_loop
  | self.backend_state_manager.update()
  | File "/venv/lib/python3.7/site-packages/ray/serve/backend_state.py", line 1354, in update
  | deleted = backend_state.update()
  | File "/venv/lib/python3.7/site-packages/ray/serve/backend_state.py", line 1113, in update
  | running_replicas_changed = self._scale_backend_replicas()
  | File "/venv/lib/python3.7/site-packages/ray/serve/backend_state.py", line 890, in _scale_backend_replicas
  | replicas_stopped = self._stop_wrong_version_replicas()
  | File "/venv/lib/python3.7/site-packages/ray/serve/backend_state.py", line 817, in _stop_wrong_version_replicas
  | states=[ReplicaState.STOPPING])
  | File "/venv/lib/python3.7/site-packages/ray/serve/backend_state.py", line 587, in count
  | self._replicas[state]))) for state in states)
  | File "/venv/lib/python3.7/site-packages/ray/serve/backend_state.py", line 587, in <genexpr>
  | self._replicas[state]))) for state in states)
  | File "/venv/lib/python3.7/site-packages/ray/serve/backend_state.py", line 586, in <lambda>
  | filter(lambda r: r.version != exclude_version,
  | File "/venv/lib/python3.7/site-packages/ray/serve/version.py", line 33, in __eq__
  | return self._hash == other._hash
  | AttributeError: 'NoneType' object has no attribute '_hash'
```

The last few lines of the log in the previous ServeController is:
```
2021-12-13 19:02:20,248 INFO backend_state.py:910 -- Adding 1 replicas to deployment 'placeholder-name'. component=serve deployment=placeholder-name
[2021-12-13 19:02:22,423 C 269 3691] reference_count.cc:912:  Check failed: inserted
*** StackTrace Information ***
    ray::SpdLogMessage::Flush()
    ray::RayLog::~RayLog()
    ray::core::ReferenceCounter::AddNestedObjectIdsInternal()
    ray::core::ReferenceCounter::AddNestedObjectIds()
    ray::core::CoreWorker::AllocateReturnObject()
    __pyx_f_3ray_7_raylet_10CoreWorker_store_task_outputs()
    __pyx_f_3ray_7_raylet_task_execution_handler()
    std::_Function_handler<>::_M_invoke()
    ray::core::CoreWorker::ExecuteTask()
    std::_Function_handler<>::_M_invoke()
    ray::core::CoreWorkerDirectTaskReceiver::HandleTask()::{lambda()#1}::operator()()
    std::_Function_handler<>::_M_invoke()
    std::_Function_handler<>::_M_invoke()
    std::_Function_handler<>::_M_invoke()
    boost::fibers::worker_context<>::run_()
    boost::context::detail::fiber_entry<>()
    make_fcontext
```

### Versions / Dependencies

Ray 1.8, Python 3.7.12, Ubuntu 20.04

### Reproduction script

Job was long-running, unclear how to repro. 

### Anything else

Has only occurred once for us so far, ServeController was up for about 3 hours.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by edoakes** [comment]
@spolcyn what version of Ray are you running? We recently fixed a similar-looking issue in our long-running failure tests, it is included in Ray 1.9.

**Comment by spolcyn** [comment]
@edoakes We're running 1.8 while working through #20971.

**Comment by edoakes** [comment]
@spolcyn is it possible for you to test out 1.9 to see if this issue persists? Otherwise I will close this and we are prioritizing your other issue as a P0.

**Comment by spolcyn** [comment]
@edoakes We can't test on 1.9 at the moment in our main workloads, so we can close this for now and re-open if we encounter it again after the next release.

**Comment by spolcyn** [comment]
@edoakes Do you have the PR number/commit hash for the fix to this?

**Comment by edoakes** [comment]
@spolcyn https://github.com/ray-project/ray/pull/20268 -- you can try patching it in
