### ISSUE TITLE
[1.9.1 Release] `aws_ssh_sync` failed twice on release branch

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#21084]
First failure: https://buildkite.com/ray-project/periodic-ci/builds/1946#6d8b90b0-37df-4dbc-8cea-4e91f7f2f5c6/138-392

```
Running cloud test variant: ssh_sync
--
  | This test will *not* use Ray client.
  | Running test variant `ssh_sync` on node 172.31.42.212 with 2 CPUs per trial.
  | Running command: python workloads/_tune_script.py --experiment-name cloud_ssh_sync --indicator-file /tmp/cloud_ssh_sync_indicator
  | Waiting up to 30 seconds until trials have been started (indicated by existence of `/tmp/cloud_ssh_sync_indicator`)
  | Process started, trials are running
  | Waiting 55 seconds until sending signal 2 to process 1505
  | Sending signal 2 to process 1505
  | Waiting up to 45 seconds until process 1505 terminates
  | Process 1505 terminated gracefully.
  | Between experiments: Invoking callback
  | Traceback (most recent call last):
  | File "workloads/run_cloud_test.py", line 1130, in <module>
  | args.cpus_per_trial)
  | File "workloads/run_cloud_test.py", line 1116, in _run_test
  | test_ssh_sync()
  | File "workloads/run_cloud_test.py", line 933, in test_ssh_sync
  | after_experiments_callback=after_experiments)
  | File "workloads/run_cloud_test.py", line 360, in run_resume_flow
  | between_experiments_callback()
  | File "workloads/run_cloud_test.py", line 874, in between_experiments
  | ) = get_experiment_and_trial_data(experiment_name=experiment_name)
  | File "workloads/run_cloud_test.py", line 647, in get_experiment_and_trial_data
  | experiment_state.trials, experiment_dir)
  | File "workloads/run_cloud_test.py", line 553, in load_experiment_checkpoint_from_dir
  | full_path, node_trial=trial_stub)
  | File "workloads/run_cloud_test.py", line 595, in load_trial_checkpoint_data
  | if checkpoint_num > node_trial.last_result["internal_iter"]:
  | KeyError: 'internal_iter'
```

Second failure: https://buildkite.com/ray-project/periodic-ci/builds/1946#b5455517-114a-4adb-be20-74bf2f9eb752/138-380
```
Traceback (most recent call last):
--
  | File "workloads/run_cloud_test.py", line 1130, in <module>
  | args.cpus_per_trial)
  | File "workloads/run_cloud_test.py", line 1116, in _run_test
  | test_ssh_sync()
  | File "workloads/run_cloud_test.py", line 933, in test_ssh_sync
  | after_experiments_callback=after_experiments)
  | File "workloads/run_cloud_test.py", line 360, in run_resume_flow
  | between_experiments_callback()
  | File "workloads/run_cloud_test.py", line 889, in between_experiments
  | driver_dir_cp, for_driver_trial=2, for_worker_trial=2)
  | File "workloads/run_cloud_test.py", line 725, in assert_checkpoint_count
  | f"Trial {trial.trial_id} was not on the driver, "
  | AssertionError: Trial e96d6_00000 was not on the driver, but did not observe the expected amount of checkpoints (1 != 2).
```

**Comment by architkulkarni** [comment]
Duplicate of https://github.com/ray-project/ray/issues/20686
