### ISSUE TITLE
[Bug] [Serve] Constructor failure is no longer logged

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#21094]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

```python
from ray import serve


serve.start()

@serve.deployment
class Inner:
    def __init__(self, ident: int):
        self.ident = ident

# pass no arg
Inner.deploy()

```

in ray 1.9.0:
```
(ServeController pid=61102) 2021-12-14 15:51:29,379	INFO checkpoint_path.py:16 -- Using RayInternalKVStore for controller checkpoint and recovery.
(ServeController pid=61102) 2021-12-14 15:51:29,382	INFO http_state.py:101 -- Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:WOqWeY:SERVE_PROXY_ACTOR-node:127.0.0.1-0' on node 'node:127.0.0.1-0' listening on '127.0.0.1:8000'
2021-12-14 15:51:29,753	INFO api.py:463 -- Started Serve instance in namespace 'serve'.
2021-12-14 15:51:29,756	INFO api.py:242 -- Updating deployment 'Inner'. component=serve deployment=Inner
(HTTPProxyActor pid=61100) INFO:     Started server process [61100]
(ServeController pid=61102) 2021-12-14 15:51:29,821	INFO deployment_state.py:912 -- Adding 1 replicas to deployment 'Inner'. component=serve deployment=Inner
(ServeController pid=61102) 2021-12-14 15:51:30,482	INFO deployment_state.py:912 -- Adding 1 replicas to deployment 'Inner'. component=serve deployment=Inner
(ServeController pid=61102) 2021-12-14 15:51:31,130	INFO deployment_state.py:912 -- Adding 1 replicas to deployment 'Inner'. component=serve deployment=Inner
Traceback (most recent call last):
  File "repro.py", line 12, in <module>
    Inner.deploy()
  File "/Users/simonmo/miniconda3/envs/anyscale/lib/python3.7/site-packages/ray/serve/api.py", line 800, in deploy
    _blocking=_blocking)
  File "/Users/simonmo/miniconda3/envs/anyscale/lib/python3.7/site-packages/ray/serve/api.py", line 93, in check
    return f(self, *args, **kwargs)
  File "/Users/simonmo/miniconda3/envs/anyscale/lib/python3.7/site-packages/ray/serve/api.py", line 248, in deploy
    self._wait_for_goal(goal_id)
  File "/Users/simonmo/miniconda3/envs/anyscale/lib/python3.7/site-packages/ray/serve/api.py", line 184, in _wait_for_goal
    raise async_goal_exception
RuntimeError: Deployment 'Inner' failed, deleting it asynchronously.
```

notice that the constructor error wasn't logged here. in 1.8, the following show up
```
(pid=61257) 2021-12-14 15:52:06,862	ERROR worker.py:425 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::Inner#mtNgAf:RayServeWrappedReplica.__init__ (pid=61257, ip=127.0.0.1)
(pid=61257)   File "/Users/simonmo/miniconda3/envs/anyscale/lib/python3.7/concurrent/futures/_base.py", line 428, in result
(pid=61257)     return self.__get_result()
(pid=61257)   File "/Users/simonmo/miniconda3/envs/anyscale/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
(pid=61257)     raise self._exception
(pid=61257)   File "/Users/simonmo/miniconda3/envs/anyscale/lib/python3.7/site-packages/ray/serve/replica.py", line 75, in __init__
(pid=61257)     **init_kwargs)
(pid=61257) TypeError: __init__() missing 1 required positional argument: 'ident'
```

### Versions / Dependencies

good in 1.8
broken in 1.9

### Reproduction script

see above

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by edoakes** [comment]
@simon-mo this is a very bad regression, let's P0 it and make sure there's a test to avoid regressions

**Comment by edoakes** [comment]
Assigning to you to not lose track, feel free to reassign.

**Comment by simon-mo** [comment]
Ah fixed in https://github.com/ray-project/ray/pull/20620

**Comment by edoakes** [comment]
Wow, great turnaround time!
