### ISSUE TITLE
[Bug] Autoscaler crashes with 404 when scaling down

### ISSUE THREAD

**Issue by ollieglass** [ray-project/ray#21151]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I ran a job using `ray serve`. The job scaled up the cluster and completed successfully. The autoscaler crashed with this error while scaling down:

```
2021-12-17 00:18:13,036 WARNING worker.py:1245 -- The autoscaler failed with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 439, in run
    self._run()
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 330, in _run
    self.autoscaler.update()
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 234, in update
    raise e
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 219, in update
    self._update()
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 252, in _update
    self.terminate_nodes_to_enforce_config_constraints(now)
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 369, in terminate_nodes_to_enforce_config_constraints
    self.terminate_scheduled_nodes()
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 394, in terminate_scheduled_nodes
    self.drain_nodes_via_gcs(self.nodes_to_terminate)
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 420, in drain_nodes_via_gcs
    for provider_node_id in provider_node_ids_to_drain
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 420, in <setcomp>
    for provider_node_id in provider_node_ids_to_drain
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/gcp/node_provider.py", line 140, in internal_ip
    node = self._get_cached_node(node_id)
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/gcp/node_provider.py", line 183, in _get_cached_node
    return self._get_node(node_id)
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/gcp/node_provider.py", line 36, in method_with_retries
    return method(self, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/gcp/node_provider.py", line 175, in _get_node
    instance = resource.get_instance(node_id=node_id)
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/gcp/node.py", line 360, in get_instance
    instance=node_id,
  File "/opt/conda/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/googleapiclient/http.py", line 851, in execute 
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://compute.googleapis.com/compute/v1/projects/.../zones/us-central1-f/instances/ray-datascience-full-worke
r-cde042e1-compute?alt=json returned "The resource 'projects/.../zones/us-central1-f/instances/ray-datascience-full-worker-cde042e1-compute' was not found">
```

There are several VMs remaining in my Google Cloud account. The `ray serve` command is still running but does not seem to be doing anything.

### Versions / Dependencies

Ray 1.8.0

### Reproduction script

Sorry, I don't have a minimal script to reproduce this

### Anything else

This has only occurred once

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
cc @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
This should fix the proximal cause:
https://github.com/ray-project/ray/pull/21204

What I'd still like to understand is why the node goes 404 missing between the time its termination is scheduled and the time the autoscaler tries to terminate it.

If you have access to autoscaler logs from failed sessions, that would be helpful too.
