### ISSUE TITLE
[Bug]  Ray server over internet

### ISSUE THREAD

**Issue by irani74** [ray-project/ray#21205]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

Hi
I have a problem with connect a client node to the server node
both of them be in the internet and behind the NAT. (not in local network)
I was forwarded port of the ray server on the nat (for example 6379 is default port we used)

when i run the "ray start --address=‘1.2.3.4:6379’ --redis-password=‘5241590000000000’ "
an error are occurring as below: (ip address just example of my real ip address)

2021-12-13 19:44:18,772 ERROR gcs_utils.py:136 – Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:
status = StatusCode.UNAVAILABLE
details = “failed to connect to all addresses”
debug_error_string = “{“created”:”@1639412058.771008400",“description”:“Failed to pick subchannel”,“file”:“src/core/ext/filters/client_channel/client_channel.cc”,“file_line”:3158,“referenced_errors”:[{“created”:"@1639412058.771003900",“description”:“failed to connect to all addresses”,“file”:“src/core/lib/transport/error_utils.cc”,“file_line”:147,“grpc_status”:14}]}"

### Versions / Dependencies

Ubuntu 20.04
Python 3.8
ray 1.8 / 1.9

### Reproduction script

ray start --address=‘1.2.3.4:6379’ --redis-password=‘5241590000000000’ 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by iphysresearch** [comment]
I got the almost exact same issue here...

```bash
2021-12-21 16:52:11,225 ERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with: ?it/s]
        status = StatusCode.UNAVAILABLE
        details = "Broken pipe"
        debug_error_string = "{"created":"@1640076731.224696840","description":"Error received from peer ipv4:192.168.202.149:39751","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Broken pipe","grpc_status":14}"
>
Traceback (most recent call last):
  File "pretrain_gw.py", line 185, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/workspace/zhouy/megatron-gw/megatron/training.py", line 141, in pretrain
    iteration = train(forward_step_func,
  File "/workspace/zhouy/megatron-gw/megatron/training.py", line 642, in train
    train_step(forward_step_func,
  File "/workspace/zhouy/megatron-gw/megatron/training.py", line 367, in train_step
    losses_reduced = forward_backward_func(
  File "/workspace/zhouy/megatron-gw/megatron/schedules.py", line 136, in forward_backward_no_pipelining
    output_tensor = forward_step(forward_step_func, data_iterator, model,
  File "/workspace/zhouy/megatron-gw/megatron/schedules.py", line 60, in forward_step
    output_tensor, loss_func = forward_step_func(data_iterator, model)
  File "pretrain_gw.py", line 138, in forward_step
    noisy_signal, clean_signal, params = get_batch(data_iterator)
  File "pretrain_gw.py", line 69, in get_batch
    data_a = next(data_iterator)
  File "/opt/conda/lib/python3.8/site-packages/ray/data/impl/torch_iterable_dataset.py", line 10, in __iter__
    yield from it
  File "/workspace/zhouy/megatron-gw/GWToolkit/gwtoolkit/gw/ray/dataset.py", line 604, in make_generator
    for batch in pipe.iter_batches(
  File "/opt/conda/lib/python3.8/site-packages/ray/data/dataset_pipeline.py", line 102, in gen_batches
    for ds in self.iter_datasets():
  File "/opt/conda/lib/python3.8/site-packages/ray/data/impl/pipeline_executor.py", line 73, in __next__
    result = ray.get(self._stages[i])
  File "/opt/conda/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ray/worker.py", line 1713, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::pipeline_stage() (pid=14059, ip=192.168.202.149)
  File "/opt/conda/lib/python3.8/site-packages/ray/data/impl/pipeline_executor.py", line 20, in pipeline_stage
    return fn()
  File "/opt/conda/lib/python3.8/site-packages/ray/data/impl/pipeline_executor.py", line 82, in <lambda>
    lambda: fn(result), DatasetContext.get_current())
  File "/workspace/zhouy/megatron-gw/GWToolkit/gwtoolkit/gw/ray/dataset.py", line 591, in <lambda>
    pipe = ds.repeat(num_repeat).foreach_window(lambda x: x.map(self.shulffle_geocent_time))  # .random_shuffle_each_window()
  File "/opt/conda/lib/python3.8/site-packages/ray/data/dataset.py", line 139, in map
    compute.apply(transform, ray_remote_args, self._blocks),
  File "/opt/conda/lib/python3.8/site-packages/ray/data/impl/compute.py", line 69, in apply
    raise e from None
  File "/opt/conda/lib/python3.8/site-packages/ray/data/impl/compute.py", line 55, in apply
    new_metadata = map_bar.fetch_until_complete(new_metadata)
  File "/opt/conda/lib/python3.8/site-packages/ray/data/impl/progress_bar.py", line 58, in fetch_until_complete
    for ref, result in zip(done, ray.get(done)):
ray.exceptions.RayTaskError: ray::_map_block() (pid=14103, ip=192.168.202.149)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.OwnerDiedError: Failed to retrieve object 5e6923b1e3e29ec4ffffffffffffffffffffffff0100000001000000. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.

The object's owner has exited. This is the Python worker that first created the ObjectRef via `.remote()` or `ray.put()`. Check cluster logs (`/tmp/ray/session_latest/logs/*f3c28721cb97db6249834a42bbcf9dcad6555555dd8c78cc7c2d7dda*` at IP address 192.168.202.149) for more information about the Python worker failure.
```
