### ISSUE TITLE
Remove run_dir from ray.train.backend.BackendExecutor.start_training (Ray 1.9.0 and above)

### ISSUE THREAD

**Issue by sidward14** [ray-project/ray#21228]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

The `run_dir` argument in `ray.train.backend.BackendExecutor.start_training` isn't used but is causing the following error: if your host computer and job cluster use different OS, then you get a `pathlib` error because, for e.g., you can't instantiate a `pathlib.WindowsPath` in a Linux system.

I had to subclass a lot to circumvent this issue.

Simple fix: remove the `run_dir` argument since it isn't used anyway.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by amogkam** [comment]
Ah great catch @sidward14! We initially had the `run_dir` in the `BackendExecutor`, but have since done some refactoring, so you're right the `run_dir` isn't needed in the `BackendExecutor` anymore and we can remove it. Would you mind making a PR for this? We'd be happy to get this merged in!

**Comment by amogkam** [comment]
Also out of curiosity, what was the stack trace that you were seeing with `start_training`?

**Comment by sidward14** [comment]
Traceback (most recent call last):
  File "3e.torch_example_new_1.9.0.py", line 210, in <module>
    results = trainer.run(train_func_distributed, config=config_loaders)
  File "3e.torch_example_new_1.9.0.py", line 142, in run
    callbacks = [] if callbacks is None else callbacks
  File "C:\Python\Python385\lib\site-packages\ray\train\trainer.py", line 584, in __init__
    self._start_training(
  File "C:\Python\Python385\lib\site-packages\ray\train\trainer.py", line 609, in _start_training
    self._run_with_error_handling(
  File "C:\Python\Python385\lib\site-packages\ray\train\trainer.py", line 620, in _run_with_error_handling
    return func()
  File "C:\Python\Python385\lib\site-packages\ray\train\trainer.py", line 610, in <lambda>
    lambda: ray.get(self._backend_executor_actor.start_training.remote(
  File "C:\Python\Python385\lib\site-packages\ray\_private\client_mode_hook.py", line 104, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "C:\Python\Python385\lib\site-packages\ray\util\client\api.py", line 42, in get
    return self.worker.get(vals, timeout=timeout)
  File "C:\Python\Python385\lib\site-packages\ray\util\client\worker.py", line 359, in get
    res = self._get(to_get, op_timeout)
  File "C:\Python\Python385\lib\site-packages\ray\util\client\worker.py", line 375, in _get
    ids=[r.id for r in ref], timeout=timeout)
  File "C:\Python\Python385\lib\site-packages\ray\util\client\worker.py", line 375, in <listcomp>
    ids=[r.id for r in ref], timeout=timeout)
  File "python\ray\includes/object_ref.pxi", line 213, in ray._raylet.ClientObjectRef.id.__get__
  File "python\ray\includes/object_ref.pxi", line 192, in ray._raylet.ClientObjectRef.binary
  File "python\ray\includes/object_ref.pxi", line 264, in ray._raylet.ClientObjectRef._wait_for_id
  File "python\ray\includes/object_ref.pxi", line 266, in ray._raylet.ClientObjectRef._wait_for_id
  File "C:\Python\Python385\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Python\Python385\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
NotImplementedError: cannot instantiate 'WindowsPath' on your system

Thanks, I'll get on the PR now.

**Comment by sidward14** [comment]
Hey @amogkam, I've submitted the PR!

**Comment by amogkam** [comment]
Awesome, thanks!
