### ISSUE TITLE
[CI][Java] NamespaceTest is flaky

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#21305]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

RETRIED: testIsolationInTheSameNamespaces
--
  | java.util.NoSuchElementException: No value present
  | at java.util.Optional.get(Optional.java:135)
  | at io.ray.test.NamespaceTest.lambda$testIsolationInTheSameNamespaces$2(NamespaceTest.java:40)
  | at io.ray.test.NamespaceTest.testIsolation(NamespaceTest.java:117)
  | at io.ray.test.NamespaceTest.testIsolationInTheSameNamespaces(NamespaceTest.java:37)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  | at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
  | at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
  | at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  | at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
  | at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
  | at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  | at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  | at java.util.ArrayList.forEach(ArrayList.java:1259)
  | at org.testng.TestRunner.privateRun(TestRunner.java:764)
  | at org.testng.TestRunner.run(TestRunner.java:585)
  | at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
  | at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
  | at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
  | at org.testng.SuiteRunner.run(SuiteRunner.java:286)
  | at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  | at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  | at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
  | at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
  | at org.testng.TestNG.runSuites(TestNG.java:1069)
  | at org.testng.TestNG.run(TestNG.java:1037)
  | at org.testng.TestNG.privateMain(TestNG.java:1371)
  | at org.testng.TestNG.main(TestNG.java:1335)

### Versions / Dependencies

None

### Reproduction script

None

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jovany-wang** [comment]
Closed by #21370
