### ISSUE TITLE
[Core] [Bug] ray.init gives me "has no attribute 'from_redis_address'"

### ISSUE THREAD

**Issue by mg64ve** [ray-project/ray#21325]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I have just pulled the last master repo and if I use:
`
python3 -c 'import ray; ray.init(); ray.shutdown()'`

or

`python3 -c 'import ray; ray.init(local_mode=True); ray.shutdown()'`

I am getting:

```
(env) [marco@dellg5 RNN]$ python3 -c 'import ray; ray.init(local_mode=True); ray.shutdown()' 
2022-01-01 11:56:44,657	ERROR services.py:1331 -- Failed to start the dashboard: Failed to start the dashboard, return code 1. The last 10 lines of /tmp/ray/session_2022-01-01_11-56-43_142995_27938/logs/dashboard.log:
2022-01-01 11:56:44,595	INFO dashboard.py:95 -- Setup static dir for dashboard: /home/marco/repos/RL/ray/python/ray/dashboard/client/build
2022-01-01 11:56:44,598	ERROR dashboard.py:253 -- The dashboard on node dellg5 failed with the following error:
Traceback (most recent call last):
  File "/home/marco/repos/RL/ray/python/ray/dashboard/dashboard.py", line 236, in <module>
    service_discovery = PrometheusServiceDiscoveryWriter(
  File "/home/marco/repos/RL/ray/python/ray/_private/metrics_agent.py", line 196, in __init__
    ray._raylet.GcsClientOptions.from_redis_address(
AttributeError: type object 'ray._raylet.GcsClientOptions' has no attribute 'from_redis_address'


```

### Versions / Dependencies

last master branch

### Reproduction script

python3 -c 'import ray; ray.init(local_mode=True); ray.shutdown()'

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mwtian** [comment]
Looks like Ray logic in Python is out of sync with Ray cython artifact. Did you rebuild the cython / C++ part of Ray after pulling from master? https://docs.ray.io/en/latest/development.html#building-ray-on-linux-macos-full

**Comment by mwtian** [comment]
cc @iycheng

**Comment by mg64ve** [comment]
You are right @mwtian I haven't rebuilt yet. But now I have just made a new git clone and tried to rebuild. The process fails at 'npm install' with the following error:

```
17298 verbose get saving parse-json to /home/condauser/.npm/registry.npmjs.org/parse-json/.cache.json
17299 verbose stack Error: Missing required argument #1
17299 verbose stack     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
17299 verbose stack     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
17299 verbose stack     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
17299 verbose stack     at /usr/share/npm/lib/install/deps.js:457:7
17299 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
17299 verbose stack     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
17299 verbose stack     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
17299 verbose stack     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
17299 verbose stack     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
17299 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
17300 verbose cwd /srv/repos/tmp/ray/dashboard/client
17301 error Linux 5.15.12-1-MANJARO
17302 error argv "/usr/bin/node" "/usr/bin/npm" "install"
17303 error node v8.10.0
17304 error npm  v3.5.2
17305 error code EMISSINGARG
17306 error typeerror Error: Missing required argument #1
17306 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
17306 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
17306 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
17306 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
17306 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
17306 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
17306 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
17306 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
17306 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
17306 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
17307 error typeerror This is an error with npm itself. Please report this error at:
17307 error typeerror     <http://github.com/npm/npm/issues>
17308 verbose exit [ 1, true ]
```

these are some details of my docker container:

![image](https://user-images.githubusercontent.com/22278227/148038489-f9123530-ffcd-4688-9e17-d91103ee4861.png)

![image](https://user-images.githubusercontent.com/22278227/148038689-89103db9-d777-4800-81c9-44b1c532c19a.png)
