### ISSUE TITLE
RLLib does not support configs that contain lists nested inside of dictionaries.

### ISSUE THREAD

**Issue by nikhilkhanna** [ray-project/ray#2135]
### System information
- **Ray version**: 4.0
- **Python version**: 2.7
- **Exact command to reproduce**: Have a nested dictionary with lists in the config for a rllib agent

### Describe the problem
When giving a config parameter that looks like 
{'x': {'y': {'z': ['a', 'b', 'c']}}} an AttributeError gets thrown when the agent.py class attempts to _deep_update the merged config in _setup(). This case should be handled as wellso that all valid python dictionaries / list combionations w/ nesting are able to be parsed properly

### Source code / logs
Remote function __init__ failed with:

Traceback (most recent call last):
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/worker.py", line 836, in _process_task
    *arguments)
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/actor.py", line 244, in actor_method_executor
    method_returns = method(actor, *args)
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/rllib/agent.py", line 93, in __init__
    Trainable.__init__(self, config, registry, logger_creator)
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/tune/trainable.py", line 90, in __init__
    self._setup()
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/rllib/agent.py", line 111, in _setup
    self._allow_unknown_subkeys)
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/rllib/agent.py", line 43, in _deep_update
    _deep_update(original[k], value, new_keys_allowed, [])
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/rllib/agent.py", line 43, in _deep_update
    _deep_update(original[k], value, new_keys_allowed, [])
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/rllib/agent.py", line 34, in _deep_update
    for k, value in new_dict.items():
AttributeError: 'list' object has no attribute 'items'

**Comment by ericl** [comment]
@nikhilkhanna do you have an example of a failing configuration? The only one I could come up with is:
```
a = {"A": {}}
b = {"A": [1,2]}
_deep_update(a, b, False, [])
print(x)
```

Which is actually invalid, since it is attempting to change the type of the "A" value from a dict to a list (though the error message here isn't great, it should say "expected value of field `A` to be dict" or something).

**Comment by ericl** [comment]
Closing stale issue -- feel free to re-open if you're still seeing this.
