### ISSUE TITLE
cloud pickle cannot pickle closed files error when trying to use ray get_registry().

### ISSUE THREAD

**Issue by nikhilkhanna** [ray-project/ray#2140]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.12.16
- **Ray installed from (source or binary)**: pip install ray
- **Ray version**: 0.4
- **Python version**: 2.7
- **Exact command to reproduce**: get_registry() after a ray.init()

### Describe the problem
When attempting to simply get_registry() after calling ray.init() (for the purposes of initializing an agent) an error will get thrown by cloudpickle when the default registry tries to flush its values to the object store regarding the fact that it cannot pickle a closed file.

### Source code / logs
Traceback (most recent call last):
  File "cortex/agents/my_agent/my_agent.py", line 253, in <module>
    registry = get_registry()
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/tune/registry.py", line 57, in get_registry
    _default_registry.flush_values_to_object_store()
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/tune/registry.py", line 104, in flush_values_to_object_store
    obj = ray.put(_to_pinnable(v))
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/worker.py", line 2501, in put
    worker.put_object(object_id, value)
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/worker.py", line 363, in put_object
    self.store_and_register(object_id, value)
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/worker.py", line 298, in store_and_register
    serialization_context=self.serialization_context)
  File "pyarrow/_plasma.pyx", line 391, in pyarrow._plasma.PlasmaClient.put
  File "pyarrow/serialization.pxi", line 338, in pyarrow.lib.serialize
  File "pyarrow/serialization.pxi", line 144, in pyarrow.lib.SerializationContext._serialize_callback
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/cloudpickle/cloudpickle.py", line 881, in dumps
    cp.dump(obj)
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/cloudpickle/cloudpickle.py", line 268, in dump
    return Pickler.dump(self, obj)
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/cloudpickle/cloudpickle.py", line 636, in save_global
    return self.save_dynamic_class(obj)
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/cloudpickle/cloudpickle.py", line 495, in save_dynamic_class
    save(clsdict)
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/nikhilkhanna/anaconda/lib/python2.7/site-packages/ray/cloudpickle/cloudpickle.py", line 777, in save_file
    raise pickle.PicklingError("Cannot pickle closed files")
pickle.PicklingError: Cannot pickle closed files

**Comment by robertnishihara** [comment]
Can you provide a code example that reproduces this issue?

Some class is getting pickled, and if that class uses a file then you'll run into problems since file handles can't be pickled (because they wouldn't make any sense when unpickled somewhere else, e.g., on a different machine).

**Comment by nikhilkhanna** [comment]
Yup had a file handler hiding in a class that was getting pickled thanks!
