### ISSUE TITLE
[Core] [Bug] When the created .remote() list is greater than 110, an error will occur when executing ray.get()

### ISSUE THREAD

**Issue by Wang-zhechao** [ray-project/ray#21415]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

1.range(100)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "I:\Program Files\Python379\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "I:\Program Files\Python379\lib\site-packages\ray\worker.py", line 1021, in shutdown
    global_worker.core_worker.shutdown()
KeyboardInterrupt

2.range(200)
Traceback (most recent call last):
  File "F:/王浙超/RewriteCode/test.py", line 19, in <module>
    get_data = ray.get(futures1)
  File "I:\Program Files\Python379\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "I:\Program Files\Python379\lib\site-packages\ray\worker.py", line 1707, in get
    object_refs, timeout=timeout)
  File "I:\Program Files\Python379\lib\site-packages\ray\worker.py", line 354, in get_objects
    object_refs, self.current_task_id, timeout_ms)
  File "python\ray\_raylet.pyx", line 1163, in ray._raylet.CoreWorker.get_objects
  File "python\ray\_raylet.pyx", line 154, in ray._raylet.check_status
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "I:\Program Files\Python379\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "I:\Program Files\Python379\lib\site-packages\ray\worker.py", line 1021, in shutdown
    global_worker.core_worker.shutdown()
KeyboardInterrupt

### Versions / Dependencies

python 3.7
ray 1.9.1
windows 10

### Reproduction script

    import ray
    ray.init()
  
    @ray.remote
    class Counter(object):
        def __init__(self):
             self.n = 0

        def increment(self):
            self.n += 1

      def read(self):
          return self.n
  
    counters1 = [Counter.remote() for i in range(200)]
    [c.increment.remote() for c in counters1]
    futures1 = [c.read.remote() for c in counters1]
    
    get_data = ray.get(futures1)
    print(get_data)
    print(len(get_data))

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment]
@Wang-zhechao This works for me on Linux, so this may be a Windows-specific issue.

**Comment by Wang-zhechao** [comment]
@clarkzinzow  thanks Clark, I will try it on Docker and I will reply to you later

**Comment by Wang-zhechao** [comment]
@clarkzinzow Thanks clarkzinzow. This problem is indeed a Windows unique problem. I have no problems with this code and 115 tensorflow actions on Ubuntu20, but I want to know what does not run on Windows, so how to solve it?

**Comment by czgdp1807** [comment]
In the OP, I can see `KeyboardInterrupt`. So, can I assume that the reproduction script was taking too long so you pressed `Ctrl + C` to stop it? Please let me know.

The second part. On my machine, I get the following copies of these messages (the process IDs vary though),

```
(pid=None) [2022-01-07 11:44:08,792 E 3004 12172] worker_pool.cc:481: Some workers of the worker process(10736) have not registered within the timeout. The process is dead, probably it crashed during start.
(pid=None) [2022-01-07 11:44:11,307 E 3004 12172] worker_pool.cc:481: Some workers of the worker process(11772) have not registered within the timeout. The process is dead, probably it crashed during start.
```

A couple of points to be noted here,

1. Windows take much longer time (as compared to Linux) to start processes. Now launching 200 remote calls means a minimum of 200 processes (please confirm) (which is huge for Windows).
2. The above error message suggests that processes took too long to register themselves. The following is the code which is reponsible for the above messages. Since we have `The process is dead, probably it crashed during start.` in the end, this means the processes never started most probably because Windows was overwhelmed with these many requests to start new processes. I will verify this by analysing how many requests for new processes actually get fulfilled. 

https://github.com/ray-project/ray/blob/83955a9407928c6106889d0277e0130b18a4b3c1/src/ray/raylet/worker_pool.cc#L469-L490

**Comment by Wang-zhechao** [comment]
@czgdp1807 Thanks for your answer.


**In the OP, I can see KeyboardInterrupt. So, can I assume that the reproduction script was taking too long so you pressed Ctrl + C to stop it? Please let me know.**
I didn't pressed Ctrl + C to stop it


This is probably because I did not set .remote() in num_cpus. After setting, there will be no keyboardinterrupt interrupt and it will become ，I didn't pressed Ctrl + C to stop it ：



  2022-01-07 20:46:47,847	WARNING worker.py:1245 -- WARNING: 32 PYTHON worker processes have been started on node: ab4b4694f16840eee2f351f8958b2a87581c1e851a6d5f7f2d544e23 with address: 127.0.0.1. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).
  2022-01-07 20:46:54,240	WARNING worker.py:1245 -- WARNING: 40 PYTHON worker processes have been started on node: ab4b4694f16840eee2f351f8958b2a87581c1e851a6d5f7f2d544e23 with address: 127.0.0.1. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).
  2022-01-07 20:47:00,429	WARNING worker.py:1245 -- WARNING: 48 PYTHON worker processes have been started on node: ab4b4694f16840eee2f351f8958b2a87581c1e851a6d5f7f2d544e23 with address: 127.0.0.1. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).
  2022-01-07 20:47:06,513	WARNING worker.py:1245 -- WARNING: 56 PYTHON worker processes have been started on node: ab4b4694f16840eee2f351f8958b2a87581c1e851a6d5f7f2d544e23 with address: 127.0.0.1. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).
  2022-01-07 20:47:12,525	WARNING worker.py:1245 -- WARNING: 64 PYTHON worker processes have been started on node: ab4b4694f16840eee2f351f8958b2a87581c1e851a6d5f7f2d544e23 with address: 127.0.0.1. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).
  2022-01-07 20:47:18,397	WARNING worker.py:1245 -- WARNING: 72 PYTHON worker processes have been started on node: ab4b4694f16840eee2f351f8958b2a87581c1e851a6d5f7f2d544e23 with address: 127.0.0.1. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).
  2022-01-07 20:47:24,018	WARNING worker.py:1245 -- WARNING: 80 PYTHON worker processes have been started on node: ab4b4694f16840eee2f351f8958b2a87581c1e851a6d5f7f2d544e23 with address: 127.0.0.1. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).
  2022-01-07 20:47:30,952	WARNING worker.py:1245 -- WARNING: 88 PYTHON worker processes have been started on node: ab4b4694f16840eee2f351f8958b2a87581c1e851a6d5f7f2d544e23 with address: 127.0.0.1. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).
  2022-01-07 20:47:37,774	WARNING worker.py:1245 -- WARNING: 96 PYTHON worker processes have been started on node: ab4b4694f16840eee2f351f8958b2a87581c1e851a6d5f7f2d544e23 with address: 127.0.0.1. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).
  2022-01-07 20:47:46,119	WARNING worker.py:1245 -- WARNING: 104 PYTHON worker processes have been started on node: ab4b4694f16840eee2f351f8958b2a87581c1e851a6d5f7f2d544e23 with address: 127.0.0.1. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).
  Traceback (most recent call last):
    File "E:/硕士毕业论文/大论文/论文程序/RewriteCode/test.py", line 19, in <module>
      get_data = ray.get(futures1)
    File "D:\Miniconda3\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
      return func(*args, **kwargs)
    File "D:\Miniconda3\lib\site-packages\ray\worker.py", line 1706, in get
      values, debugger_breakpoint = worker.get_objects(
    File "D:\Miniconda3\lib\site-packages\ray\worker.py", line 353, in get_objects
      data_metadata_pairs = self.core_worker.get_objects(
    File "python\ray\_raylet.pyx", line 1163, in ray._raylet.CoreWorker.get_objects
  
  Error in atexit._run_exitfuncs:
  Traceback (most recent call last):
    File "D:\Miniconda3\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
      return func(*args, **kwargs)
    File "D:\Miniconda3\lib\site-packages\ray\worker.py", line 1008, in shutdown
      time.sleep(0.5)
  KeyboardInterrupt
  Error in atexit._run_exitfuncs:
  
  进程已结束,退出代码-1073741819 (0xC0000005)

**Comment by czgdp1807** [comment]
So, I modified your code with running a batch of tasks concurrently and then the next batch and so on. It worked fine.

```python
import ray
ray.init()

@ray.remote
class Counter(object):
    def __init__(self):
         self.n = 0

    def increment(self):
        self.n += 1

    def read(self):
        return self.n

for _ in range(8):
    counters1 = [Counter.remote() for i in range(25)]
    [c.increment.remote() for c in counters1]
    futures1 = [c.read.remote() for c in counters1]

    get_data = ray.get(futures1)
    print(len(get_data))
```

If launching 200 tasks is allowed in Ubuntu (i.e., it works without issues) but not on Windows then I think it won't be wrong to say that Windows is unable to launch several processes at once. Meanwhile I verify my hypothesis, you can try the above trick. #3644 is in fact very much relevant to this issue because starting too many workers is a problem on Windows (even in case of completely independent tasks).
