### ISSUE TITLE
(Core] [bug][gcs] worker nodes starts failed in redis removal mode

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#21473]
running with RAY_gcs_grpc_based_pubsub=1 RAY_gcs_storage=memory RAY_bootstrap_with_gcs=1 it'll fail in our test platform.
it's working with ec2.

from the log:
```
Logs are currently unavailable. Traceback from log retrieval follows.
Traceback (most recent call last):
  File "./backend/server/api/product/routers/sessions_router.py", line 1417, in get_monitor_logs
    logs_params.extension,
ray.exceptions.RaySystemError: System error: __init__() missing 2 required positional arguments: 'returncode' and 'cmd'
traceback: Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 248, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 213, in _deserialize_object
    return RayError.from_bytes(obj)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/exceptions.py", line 29, in from_bytes
    return pickle.loads(ray_exception.serialized_exception)
TypeError: __init__() missing 2 required positional arguments: 'returncode' and 'cmd'

```
It seems autoscaler is not working well right now.

**Comment by iycheng** [comment]
```
2022-01-07 14:43:56,305 INFO monitor.py:414 -- Starting monitor using ray installation: /home/ray/anaconda3/lib/python3.7/site-packages/ray/__init__.py
2022-01-07 14:43:56,305 INFO monitor.py:415 -- Ray version: 1.7.0
2022-01-07 14:43:56,305 INFO monitor.py:416 -- Ray commit: 2367a2cb9033913b68b1230316496ae273c25b54
2022-01-07 14:43:56,305 INFO monitor.py:417 -- Monitor started with command: ['/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py', '--monitor-ip=172.31.87.175', '--redis-address=172.31.87.175:6379', '--logs-dir', '/tmp/ray/session_latest/logs/', '--redis-password=5241590000000000', '--autoscaling-config=/home/ray/autoscaler_mounts/~/ray_bootstrap_config.yaml']
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 428, in <module>
    monitor_ip=args.monitor_ip)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 111, in __init__
    f"{monitor_ip}:{AUTOSCALER_METRIC_PORT}")
  File "/home/ray/anaconda3/lib/python3.7/site-packages/redis/commands/core.py", line 1453, in set
    return self.execute_command('SET', *pieces, **options)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/redis/client.py", line 1068, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 1173, in get_connection
    connection.connect()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 575, in connect
    self.on_connect()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 653, in on_connect
    auth_response = self.read_response()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 748, in read_response
    response = self._parser.read_response()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 465, in read_response
    response = self._reader.gets()
redis.exceptions.InvalidResponse: Protocol error, got "\x00" as reply type byte
Exception ignored in: <function Monitor.__del__ at 0x7fdd39a6e5f0>
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 161, in __del__
    disconnect_from_gcs(self.gcs_client)
AttributeError: 'Monitor' object has no attribute 'gcs_client'
cat: /tmp/ray/session_latest/logs/old: Is a directory
```
It seems like a version mismatch issue.
