### ISSUE TITLE
[Bug] [Xlang] Overloaded Java Class can't be called via xlang

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#21477]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

Given the following Java interface and class
```java
public interface ExampleInterface {
  default String echo(String inp) {
    return inp;
  }
}
```

```java
public class ExampleImpl implements ExampleInterface {
  @Override
  public String echo(String inp) {
    return inp + " echo";
  }
}
```

and calling it via Python (use own package of course):
```python
import ray
ray.init(job_config=ray.job_config.JobConfig(code_search_path=["."]))
cls = ray.java_actor_class("io.ray.serve.util.ExampleImpl")
handle = cls.remote()
print(ray.get(handle.echo.remote("hi")))
```

I get the following error:
```
In [6]: ray.get(handle.echo.remote("hi"))                                                                    
---------------------------------------------------------------------------
CrossLanguageError                        Traceback (most recent call last)
<ipython-input-6-eb72b94dc879> in <module>
----> 1 ray.get(handle.echo.remote("hi"))

~/Desktop/ray/ray/python/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
    103             if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104                 return getattr(ray, func.__name__)(*args, **kwargs)
--> 105         return func(*args, **kwargs)
    106 
    107     return wrapper

~/Desktop/ray/ray/python/ray/worker.py in get(object_refs, timeout)
   1742                     raise value.as_instanceof_cause()
   1743                 else:
-> 1744                     raise value
   1745 
   1746         if is_individual_id:

CrossLanguageError: An exception raised from JAVA:
io.ray.runtime.exception.RayTaskException: (pid=68724, ip=192.168.1.69) Error executing task 63964fa4841d4a2eeb3d013876f4f3c8c527dbba01000000
        at io.ray.runtime.task.TaskExecutor.execute(TaskExecutor.java:188)
        at io.ray.runtime.RayNativeRuntime.nativeRunTaskExecutor(Native Method)
        at io.ray.runtime.RayNativeRuntime.run(RayNativeRuntime.java:251)
        at io.ray.runtime.runner.worker.DefaultWorker.main(DefaultWorker.java:15)
Caused by: java.lang.RuntimeException: RayFunction io.ray.serve.util.ExampleImpl.echo is overloaded, the signature can't be empty.
        at io.ray.runtime.functionmanager.FunctionManager$JobFunctionTable.getFunction(FunctionManager.java:183)
        at io.ray.runtime.functionmanager.FunctionManager.getFunction(FunctionManager.java:108)
        at io.ray.runtime.task.TaskExecutor.getRayFunction(TaskExecutor.java:69)
        at io.ray.runtime.task.TaskExecutor.execute(TaskExecutor.java:121)
        ... 3 more
```

Note that if I can make the method not overloaded, then it's passes. 
```
  default String echo(String inp) {
```
to
```
  String echo(String inp);
```

### Versions / Dependencies

master

### Reproduction script

see above

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jovany-wang** [comment]
I can make sure this is a bug indeed.

The root cause is we add `default` method as overloaded and the method signature is not passed in xlang . https://github.com/ray-project/ray/blob/master/java/runtime/src/main/java/io/ray/runtime/functionmanager/FunctionManager.java#L215

One easy fix is : if the `default` method is not overrided, we use the `default` method, and if it's overrided, we shouldn't collect it. (This is the exact semantics of `default` keyword.)
@fyrestone @chaokunyang @kfstorm CC

**Comment by jovany-wang** [comment]
@simon-mo The fix was merged on master. Feel free to close this once your issue get addressed.

**Comment by simon-mo** [comment]
@jovany-wang thanks for the quick turnaround!
