### ISSUE TITLE
Python - ConnectionResetError after ray.init(); ray.shutdown(); ray.init() 

### ISSUE THREAD

**Issue by CopyOfA** [ray-project/ray#21586]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I have a script that calls ray a couple of times for different tasks. When ray is first initialized and used, everything runs fine, but when I try to initialize a second time, I get an error: `ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host`. The  way this is set up, I have a function that executes some machine learning tasks on each column of a pandas dataframe. I pass a parameter that determines whether or not we use `ray`; that `if` block is this:
```python
key = "primary_key"

df.sort_values(by = [key,'collection_date'], inplace = True)
        
# All unique keys in the dataframe
keys, loc = np.unique(df[key],return_index = True)
loc = np.append(loc,len(df)) # For getting subsets

context_cols = [c for c in df.columns if c not in columns]

if parallel:
    ray.shutdown() # Shutting down in case one already running
    while not ray.is_initialized():
        try:
            ray.init(_enable_object_reconstruction=True) # Initiallizing parallelization object
        except Exception as e:
            print(e)
    
    result_ids = []
        
    # For each series, running the detection algorithms
    for i in np.arange(len(keys)):
        result_ids.append(detect_parallel.remote(
            df.iloc[loc[i]:loc[i+1]],
            columns,
            [c for c in df.columns if c not in columns],
             univariate,
             multivariate,
             filter_component
        ))
        
    results = ray.get(result_ids)
    # Building DataFrame from results
    df_results = results[0]
    for df in results[1:]:
        df_results = df_results.append(df,ignore_index = True)
    
    ray.shutdown()
```
Anyway, most of this does not matter, because if I call this block of code two or more times, I get an error: `[WinError 10054] An existing connection was forcibly closed by the remote host`. Essentially, I've been able to reproduce the error with the following code (full output included here):
```python
In [1]: import ray

In [2]: ray.init()
Out[2]: 
{'node_ip_address': '127.0.0.1',
 'raylet_ip_address': '127.0.0.1',
 'redis_address': '127.0.0.1:6379',
 'object_store_address': 'tcp://127.0.0.1:64970',
 'raylet_socket_name': 'tcp://127.0.0.1:65475',
 'webui_url': None,
 'session_dir': 'C:\\Users\\jamesnj1\\AppData\\Local\\Temp\\ray\\session_2022-01-13_16-11-13_612307_7200',
 'metrics_export_port': 61809,
 'node_id': 'b810f07e7fd9e814651f326122c320608f1b896894a21942dbdc5cd8'}

In [3]: ray.shutdown()

In [4]: ray.init()
Exception in thread ray_print_logs:
Traceback (most recent call last):
  File "~\Anaconda3\envs\anomaly_detect_env\lib\threading.py", line 932, in _bootstrap_inner
Out[4]: 
{'node_ip_address': '127.0.0.1',
 'raylet_ip_address': '127.0.0.1',
 'redis_address': '127.0.0.1:6379',
 'object_store_address': 'tcp://127.0.0.1:59852',
 'raylet_socket_name': 'tcp://127.0.0.1:61467',
 'webui_url': None,
 'session_dir': '~\\AppData\\Local\\Temp\\ray\\session_2022-01-13_16-12-01_344971_7200',
 'metrics_export_port': 64824,
 'node_id': '3879cc3a478fc4de5433cf60bbf693647c38ea7ca0db1d365aec5c02'}    self.run()
  File "~\Anaconda3\envs\anomaly_detect_env\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "~\Anaconda3\envs\anomaly_detect_env\lib\site-packages\ray\worker.py", line 439, in print_logs
    pubsub_client.subscribe(gcs_utils.LOG_FILE_CHANNEL)
  File "~\Anaconda3\envs\anomaly_detect_env\lib\site-packages\redis\client.py", line 1377, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *new_channels.keys())
  File "~\Anaconda3\envs\anomaly_detect_env\lib\site-packages\redis\client.py", line 1253, in execute_command
    self.connection = self.connection_pool.get_connection(
  File "~\Anaconda3\envs\anomaly_detect_env\lib\site-packages\redis\connection.py", line 1179, in get_connection
    if connection.can_read():
  File "~\Anaconda3\envs\anomaly_detect_env\lib\site-packages\redis\connection.py", line 743, in can_read
    return self._parser.can_read(timeout)
  File "~\Anaconda3\envs\anomaly_detect_env\lib\site-packages\redis\connection.py", line 315, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "~\Anaconda3\envs\anomaly_detect_env\lib\site-packages\redis\connection.py", line 224, in can_read
    self._read_from_socket(timeout=timeout,
  File "~\Anaconda3\envs\anomaly_detect_env\lib\site-packages\redis\connection.py", line 192, in _read_from_socket
    data = self._sock.recv(socket_read_size)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

I expected that since I'd shutdown ray after using it, that the next time I initialize it, it would start up without error.

### Versions / Dependencies

I'm running a Windows 10 virtual machine, with anaconda base (anaconda-client 1.9.0, anaconda-project 0.10.2). My virtual environment is a full Anaconda install with Python 3.8.12. I'm using Ray 1.9.2 (installed via `pip` in my anaconda virtual environment).

### Reproduction script

```python
import ray
ray.init()
ray.shutdown()
ray.init()
```

### Anything else

This has occurred every time I've tried the code in the "Reproduction script" section.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by czgdp1807** [comment]
With [`cea80b1a5b56cb68defd8a60fa89`](https://github.com/ray-project/ray/commit/cea80b1a5b56cb68defd8a60fa898e248d2b2a7d) commit of ray on Windows, I built from source and executed, your reproduction script works fine without any connection errors.

With Ray 1.9.2, I receive the same exact some connection error which you received.

So, between Ray 1.9.2 and the above commit the issue got fixed.

**Comment by CopyOfA** [comment]
Thanks, that sounds like progress. When will this fix be made available for public use?

**Comment by czgdp1807** [comment]
> When will this fix be made available for public use?

cc: @pcmoritz
