### ISSUE TITLE
[Bug] Jobs CLI with `ray.init()` fails on master with `AssertionError: Module: http does not have ClientBuilder.`

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#21592]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Dashboard, Others

### What happened + What you expected to happen

```
| your_working_directory ("./")
| ├── script.py
```

```
# script.py
import ray
ray.init()
```

Then run
```
ray start --head
export RAY_ADDRESS=http://127.0.0.1:8265
ray job submit --working-dir="./" -- python script.py
```
as in the docs.  

We get the following output:

```
ray start --head
export RAY_ADDRESS=http://127.0.0.1:8265
ray job submit --working-dir="./" -- python script.py
Local node IP: 127.0.0.1
2022-01-13 18:39:01,675 INFO services.py:1382 -- View the Ray dashboard at http://127.0.0.1:8265

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='127.0.0.1:6379' --redis-password='5241590000000000'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='5241590000000000')
  
  To connect to this Ray runtime from outside of the cluster, for example to
  connect to a remote cluster from your laptop directly, use the following
  Python code:
    import ray
    ray.init(address='ray://<head_node_ip_address>:10001')
  
  If connection fails, check your firewall settings and network configuration.
  
  To terminate the Ray runtime, run
    ray stop
Job submission server address: http://127.0.0.1:8265
2022-01-13 18:39:03,348 INFO sdk.py:189 -- Uploading package gcs://_ray_pkg_867dc877fe33e555.zip.
2022-01-13 18:39:03,349 INFO packaging.py:362 -- Creating a file package for local directory './'.

-------------------------------------------------------
Job 'raysubmit_jx9F57bhMiqZP9UN' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_jx9F57bhMiqZP9UN
  Query the status of the job:
    ray job status raysubmit_jx9F57bhMiqZP9UN
  Request the job to be stopped:
    ray job stop raysubmit_jx9F57bhMiqZP9UN

Tailing logs until the job exits (disable with --no-wait):
Traceback (most recent call last):
  File "script.py", line 2, in <module>
    ray.init()
  File "/Users/archit/ray/python/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/archit/ray/python/ray/worker.py", line 767, in init
    builder = ray.client(address, _deprecation_warn_enabled=False)
  File "/Users/archit/ray/python/ray/client_builder.py", line 347, in client
    builder = _get_builder_from_address(address)
  File "/Users/archit/ray/python/ray/client_builder.py", line 318, in _get_builder_from_address
    assert "ClientBuilder" in dir(module), (f"Module: {module_string} does "
AssertionError: Module: http does not have ClientBuilder.

---------------------------------------
Job 'raysubmit_jx9F57bhMiqZP9UN' failed
---------------------------------------

Traceback (most recent call last):
  File "/Users/archit/anaconda3/envs/ray-py38/bin/ray", line 11, in <module>
    load_entry_point('ray', 'console_scripts', 'ray')()
  File "/Users/archit/ray/python/ray/scripts/scripts.py", line 1952, in main
    return cli()
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/archit/ray/python/ray/autoscaler/_private/cli_logger.py", line 808, in wrapper
    return f(*args, **kwargs)
  File "/Users/archit/ray/python/ray/dashboard/modules/job/cli.py", line 177, in job_submit
    asyncio.get_event_loop().run_until_complete(
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/archit/ray/python/ray/dashboard/modules/job/cli.py", line 68, in _tail_logs
    _log_job_status(client, job_id)
  File "/Users/archit/ray/python/ray/dashboard/modules/job/cli.py", line 56, in _log_job_status
    cli_logger.print(f"Status message: {status.message}")
  File "/Users/archit/ray/python/ray/autoscaler/_private/cli_logger.py", line 589, in print
    self._print(_format_msg(msg, *args, **kwargs), _level_str=_level_str)
  File "/Users/archit/ray/python/ray/autoscaler/_private/cli_logger.py", line 238, in _format_msg
    return numbering_str + msg.format(*args, **kwargs) + tags_str
KeyError: 'module_string'
```

### Versions / Dependencies

Ray master branch, macOS (non-M1), Python 3.8

### Reproduction script

Listed above

### Anything else

This happens *nearly* every time, but I haven't noticed a pattern for when it succeeds and I unfortunately don't remember what, if anything, I had tweaked anything to make it succeed. I'll keep trying.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment]
Possibly related to https://github.com/ray-project/ray/issues/20684

**Comment by architkulkarni** [comment]
It looks like this can be fixed by opening a new terminal window, but once it fails, it fails every time in that terminal.  Still not sure what causes it to fail the first time

**Comment by jiaodong** [comment]
Observed behaviors:
1) In new terminal, upon executing `ray stop --force && ray start --head` for the first time, then set address by `export RAY_ADDRESS=http://127.0.0.1:8265`, everything works repeatedly via ` ray job submit --working-dir="./" -- python script.py`

2) Repeat the same flow by re-starting ray cluster `ray stop --force && ray start --head`, RAY_ADDRESS didn't change but now we will hit ray client error.

3) Re-doing step 1) in new terminal resolves the issue.

**Comment by jiaodong** [comment]
In other words, we want to always ensure we use redis address "127.0.0.1:8265" for inner script's ray.int(), rather than passing an address with "http" in it.

**Comment by grechaw** [comment]
A related issue is that ray job CLI does not work with anyscale urls.  I wish it did... should I make a Ray project issue for this or a Anyscale one?

**Comment by jiaodong** [comment]
> A related issue is that ray job CLI does not work with anyscale urls. I wish it did... should I make a Ray project issue for this or a Anyscale one?

do you have repro steps in detail ? Given that it mentioned product I think it's better to have details on an anyscale issue as usually we don't expose the term or details on ray oss repo :)

**Comment by vedantroy** [comment]
I am running into this issue:

```
(base) ray@19a5959f6930:/app$ env LOCAL=true ./dev_scripts/job_run.bash video_tar2ray
+ [[ -z http://100.106.30.207:8265 ]]
+ [[ ! -z true ]]
+ echo 'Running job locally'
Running job locally
+ ray start --head
Usage stats collection is enabled. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.

Local node IP: 192.168.32.2

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='192.168.32.2:6379'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto')
  
  To connect to this Ray runtime from outside of the cluster, for example to
  connect to a remote cluster from your laptop directly, use the following
  Python code:
    import ray
    ray.init(address='ray://<head_node_ip_address>:10001')
  
  If connection fails, check your firewall settings and network configuration.
  
  To terminate the Ray runtime, run
    ray stop
+ RAY_ADDRESS=http://127.0.0.1:8265
+ job_file=cluster_scripts/video_tar2ray.py
+ [[ ! -f cluster_scripts/video_tar2ray.py ]]
++ cat .job.env.json
++ jq
+ ray job submit --working-dir . '--runtime-env-json={"env_vars": {
  "S3_SOURCE_URL": "s3://data",
  "S3_DEST_URL": "ray-datasets/150gb",
  "ITEMS_PER_SHARD": "10000",
  "AWS_BUCKET_NAME": "data"
}}' -- bash -c 'pip install -e . && python cluster_scripts/video_tar2ray.py'
Job submission server address: http://127.0.0.1:8265
2022-10-11 07:42:09,615 INFO dashboard_sdk.py:307 -- Uploading package gcs://_ray_pkg_052a1f30b6bc71fa.zip.
2022-10-11 07:42:09,616 INFO packaging.py:499 -- Creating a file package for local directory '.'.

-------------------------------------------------------
Job 'raysubmit_E69iaUjxvKrtEmVc' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_E69iaUjxvKrtEmVc
  Query the status of the job:
    ray job status raysubmit_E69iaUjxvKrtEmVc
  Request the job to be stopped:
    ray job stop raysubmit_E69iaUjxvKrtEmVc

Tailing logs until the job exits (disable with --no-wait):
Obtaining file:///tmp/ray/session_2022-10-11_07-42-06_017828_62027/runtime_resources/working_dir_files/_ray_pkg_052a1f30b6bc71fa
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Installing collected packages: distributed-ml
  Attempting uninstall: distributed-ml
    Found existing installation: distributed-ml 0.0.0
    Uninstalling distributed-ml-0.0.0:
      Successfully uninstalled distributed-ml-0.0.0
  Running setup.py develop for distributed-ml
Successfully installed distributed-ml-0.0.0
2022-10-11 07:42:14,347 INFO worker.py:1223 -- Using address http://100.106.30.207:8265 set in the environment variable RAY_ADDRESS
Traceback (most recent call last):
  File "cluster_scripts/video_tar2ray.py", line 16, in <module>
    ray.init(address="auto")
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/worker.py", line 1230, in init
    builder = ray.client(address, _deprecation_warn_enabled=False)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/client_builder.py", line 382, in client
    builder = _get_builder_from_address(address)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/client_builder.py", line 350, in _get_builder_from_address
    assert "ClientBuilder" in dir(
AssertionError: Module: http does not have ClientBuilder.

---------------------------------------
Job 'raysubmit_E69iaUjxvKrtEmVc' failed
---------------------------------------

Status message: Job failed due to an application error, last available logs (truncated to 20,000 chars):
    ray.init(address="auto")
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/worker.py", line 1230, in init
    builder = ray.client(address, _deprecation_warn_enabled=False)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/client_builder.py", line 382, in client
    builder = _get_builder_from_address(address)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/client_builder.py", line 350, in _get_builder_from_address
    assert "ClientBuilder" in dir(
AssertionError: Module: http does not have ClientBuilder.

+ [[ ! -z true ]]
+ echo 'Shutting down local cluster ...'
Shutting down local cluster ...
+ ray stop
```

using my job submission script:
```
#! /bin/bash
set -euxo pipefail

if [[ -z "${RAY_ADDRESS}" ]]; then
	echo "RAY_ADDRESS is not defined"
	exit 1
fi

if [[ ! -z "${LOCAL}" ]]; then
       echo "Running job locally"
       ray start --head
       RAY_ADDRESS="http://127.0.0.1:8265"
fi

job_file="cluster_scripts/${1}.py"
if [[ ! -f "${job_file}" ]]; then
	echo "${job_file} not found"
	exit 1
fi

ray job submit \
	--working-dir . \
	--runtime-env-json="{\"env_vars\": $(cat .job.env.json | jq)}" \
	-- bash -c "pip install -e . && python ${job_file}"

if [[ ! -z "${LOCAL}" ]]; then
       echo "Shutting down local cluster ..."
       ray stop
fi
```

**Comment by architkulkarni** [comment]
Hi @vedantroy, sorry you're running into this, we believe the issue should be fixed, do you mind sharing which Ray version you're using?

**Comment by vedantroy** [comment]
@architkulkarni I'm using ray version 2.0.1rc.

I can reproduce this by using the Python SDK to submit a job to a local cluster.
Script:

```
#! /usr/bin/env python3
from pathlib import Path
import os
import sys

from ray.job_submission import JobSubmissionClient


job_file = f"cluster_jobs/{sys.argv[1]}.py"
if not Path(job_file).is_file():
    print(f"job file not found: {job_file}")
    sys.exit(1)

RAY_ADDRESS = os.getenv("RAY_ADDRESS")
if not RAY_ADDRESS:
    print(f"RAY_ADDRESS not set, assuming local cluster exists...")
    RAY_ADDRESS = "http://127.0.0.1:8265"

client = JobSubmissionClient(RAY_ADDRESS)
job_id = client.submit_job(
    runtime_env=dict(
        working_dir=".",
    ),
    entrypoint=f"pip install . && python {job_file}",
)
print(f"Job submitted: {job_id}")
```

**Comment by architkulkarni** [comment]
@vedantroy Thanks for the details, I'll take a look.  By the way, do you mean version `2.0.0rc0`? Or are you using some version that isn't listed here? https://pypi.org/project/ray/#history

**Comment by architkulkarni** [comment]
I actually can't reproduce this on Ray 2.0.0 or on master.  Here's a minimal reproduction I used (since I don't have `job_file`), and I tried it both with `RAY_ADDRESS` environment variable set and without:
```python
#! /usr/bin/env python3
from pathlib import Path
import os
import sys

from ray.job_submission import JobSubmissionClient


# job_file = f"cluster_jobs/{sys.argv[1]}.py"
# if not Path(job_file).is_file():
#     print(f"job file not found: {job_file}")
#     sys.exit(1)

RAY_ADDRESS = os.getenv("RAY_ADDRESS")
print("RAY_ADDRESS: ", RAY_ADDRESS)
if not RAY_ADDRESS:
    print(f"RAY_ADDRESS not set, assuming local cluster exists...")
    RAY_ADDRESS = "http://127.0.0.1:8265"

client = JobSubmissionClient(RAY_ADDRESS)
job_id = client.submit_job(
    runtime_env=dict(
        working_dir=".",
    ),
    entrypoint= "python -c 'import ray; ray.init(address=\"auto\"); print(ray.get(ray.put(1)))'",
)
print(f"Job submitted: {job_id}")
```

Do you mind double checking what `ray --version` returns?  

Also, inside your `job_file` or in the `entrypoint` script, can you print `os.environ.get("RAY_ADDRESS")` and `ray.__version__`?  For example: `entrypoint="python -c 'import ray; ray.init(address=\"auto\"); print(ray.__version__); import os; print(os.environ.get(\"RAY_ADDRESS\"));'"`

**Comment by vedantroy** [comment]
@architkulkarni Ahhh! For some reason; the issue has vanished -- even though I spent at least an hour dealing with it last night. If it happens again, I'll upload an asciinema recording so you know I'm going insane heh.

**Comment by architkulkarni** [comment]
Ah I see, thanks for following up!  I'll close the issue for now.

**Comment by starpit** [comment]
btw, we ran into this because we were setting, in a ray worker process, the `RAY_ADDRESS` env var to an `http:` address when running in-cluster.  by removing that env var from the kube pod, this particular error went away.

**Comment by babu111** [comment]
ran into the same problem
redacting RAY_ADDRESS solved it!

**Comment by caican00** [comment]
> ran into the same problem redacting RAY_ADDRESS solved it!

Hi @babu111 May i ask how you fix the issue?

**Comment by caican00** [comment]
> > ran into the same problem redacting RAY_ADDRESS solved it!遇到同样的问题，编辑 RAY_ADDRESS 解决了！
> 
> Hi @babu111 May i ask how you fix the issue?您好，请问您如何解决该问题？

i solved this issue when i updated the value of `RAY_ADDRESS` from `dashbaord_url` to `client_server_url`
