### ISSUE TITLE
[Bug]  Only CONFIG GET is allowed during loading

### ISSUE THREAD

**Issue by valiantljk** [ray-project/ray#21604]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I tried to start Ray on my mac, but occasionally,  I got an error related to redis. I tried to clean everything, e.g., shutting down ray and kill idle redis process. But still not able to start ray head. 

```
dr6jl$ ray start --head
Local node IP: 127.0.0.1
Traceback (most recent call last):
  File "/opt/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1989, in main
    return cli()
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 632, in start
    node = ray.node.Node(
  File "/opt/anaconda3/lib/python3.8/site-packages/ray/node.py", line 215, in __init__
    self.start_head_processes()
  File "/opt/anaconda3/lib/python3.8/site-packages/ray/node.py", line 902, in start_head_processes
    self.start_redis()
  File "/opt/anaconda3/lib/python3.8/site-packages/ray/node.py", line 705, in start_redis
    process_infos) = ray._private.services.start_redis(
  File "/opt/anaconda3/lib/python3.8/site-packages/ray/_private/services.py", line 929, in start_redis
    port, p = _start_redis_instance(
  File "/opt/anaconda3/lib/python3.8/site-packages/ray/_private/services.py", line 1087, in _start_redis_instance
    raise RuntimeError("Couldn't start Redis. "
RuntimeError: Couldn't start Redis. Check log files: /tmp/ray/session_2022-01-14_11-05-06_165201_54819/logs/redis.out /tmp/ray/session_2022-01-14_11-05-06_165201_54819/logs/redis.err
dr6jl$ ray stop
Stopped all 1 Ray processes.
dr6jl$ ray start --head
Local node IP: 127.0.0.1
Traceback (most recent call last):
  File "/opt/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1989, in main
    return cli()
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 632, in start
    node = ray.node.Node(
  File "/opt/anaconda3/lib/python3.8/site-packages/ray/node.py", line 215, in __init__
    self.start_head_processes()
  File "/opt/anaconda3/lib/python3.8/site-packages/ray/node.py", line 902, in start_head_processes
    self.start_redis()
  File "/opt/anaconda3/lib/python3.8/site-packages/ray/node.py", line 705, in start_redis
    process_infos) = ray._private.services.start_redis(
  File "/opt/anaconda3/lib/python3.8/site-packages/ray/_private/services.py", line 929, in start_redis
    port, p = _start_redis_instance(
  File "/opt/anaconda3/lib/python3.8/site-packages/ray/_private/services.py", line 1100, in _start_redis_instance
    redis_client.config_set("notify-keyspace-events", "Kl")
  File "/opt/anaconda3/lib/python3.8/site-packages/redis/commands/core.py", line 671, in config_set
    return self.execute_command("CONFIG SET", name, value, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/redis/client.py", line 1173, in execute_command
    return conn.retry.call_with_retry(
  File "/opt/anaconda3/lib/python3.8/site-packages/redis/retry.py", line 41, in call_with_retry
    return do()
  File "/opt/anaconda3/lib/python3.8/site-packages/redis/client.py", line 1174, in <lambda>
    lambda: self._send_command_parse_response(
  File "/opt/anaconda3/lib/python3.8/site-packages/redis/client.py", line 1150, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/opt/anaconda3/lib/python3.8/site-packages/redis/client.py", line 1189, in parse_response
    response = connection.read_response()
  File "/opt/anaconda3/lib/python3.8/site-packages/redis/connection.py", line 817, in read_response
    raise response
redis.exceptions.ResponseError: Only CONFIG GET is allowed during loading
```

### Versions / Dependencies

Ray: 1.9.2 (other versions not working too)
Python: 3.8/3.9/3.7
Os: Darwin

### Reproduction script

ray start --head

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
Is it working if you try ray stop --force and ray start again?
