### ISSUE TITLE
Using the Monitor wrapper from gym leads to an exception in `poll()` [Bug] 

### ISSUE THREAD

**Issue by simonsays1980** [ray-project/ray#21629]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

# Bug
I used the `Simple_Q` agent on the `Breakout-v1` environment and used recording by setting 

```
"record_env": "the/path/to/my/videos"
```
Using this setting ends in an exception coming from the `poll()` function of the `_MultiAgentEnvState` class (the one in the `base_env.py`) at exactly this line: 
```
for ag in observations.keys():
``` 
The reason is that the observations are not a `dict`, but a `numpy.ndarray`. 

# Expected behavior
I expected the trainer to record videos of the agent interacting with the environment in the path I provided in my config.

# Useful information
Here are the logs I got (using `"log_level": "DEBUG"`): 
```
2022-01-16 11:04:24,500 INFO services.py:1338 -- View the Ray dashboard at http://127.0.0.1:8265
2022-01-16 11:04:25,733 WARNING worker.py:502 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
:task_name:bundle_reservation_check_func
:task_name:bundle_reservation_check_func
:actor_name:SimpleQTrainer
:actor_name:SimpleQTrainer
2022-01-16 11:04:26,526 INFO trainer.py:722 -- Your framework setting is 'tf', meaning you are using static-graph mode. Set framework='tf2' to enable eager execution with tf2.x. You may also want to then set `eager_tracing=True` in order to reach similar execution speed as with static-graph mode.
Backend TkAgg is interactive backend. Turning interactive mode on.
A.L.E: Arcade Learning Environment (version +978d2ce)
[Powered by Stella]
2022-01-16 11:04:36,472 INFO rollout_worker.py:1705 -- Validating sub-env at vector index=0 ... (ok)
Setting the path for recording to /home/simon/git-projects-ray-experiments/videos
2022-01-16 11:04:38,838 DEBUG rollout_worker.py:1534 -- Creating policy for default_policy
2022-01-16 11:04:38,843 DEBUG worker_set.py:364 -- Creating TF session {'intra_op_parallelism_threads': 8, 'inter_op_parallelism_threads': 8, 'gpu_options': {'allow_growth': True}, 'log_device_placement': False, 'device_count': {'CPU': 1}, 'allow_soft_placement': True}
2022-01-16 11:04:40,441 INFO tf_policy.py:160 -- TFPolicy (worker=local) running on CPU.
2022-01-16 11:04:40,562 INFO dynamic_tf_policy.py:595 -- Testing `compute_actions` w/ dummy batch.
2022-01-16 11:04:40,563 WARNING deprecation.py:45 -- DeprecationWarning: `SampleBatch['is_training']` has been deprecated. Use `SampleBatch.is_training` instead. This will raise an error in the future!
2022-01-16 11:04:40,567 INFO tf_run_builder.py:89 -- Executing TF run without tracing. To dump TF timeline traces to disk, set the TF_TIMELINE_DIR environment variable.
2022-01-16 11:04:40,644 INFO dynamic_tf_policy.py:603 -- Adding extra-action-fetch `action_prob` to view-reqs.
2022-01-16 11:04:40,647 INFO dynamic_tf_policy.py:603 -- Adding extra-action-fetch `action_logp` to view-reqs.
2022-01-16 11:04:40,651 INFO dynamic_tf_policy.py:603 -- Adding extra-action-fetch `action_dist_inputs` to view-reqs.
2022-01-16 11:04:40,653 INFO dynamic_tf_policy.py:603 -- Adding extra-action-fetch `q_values` to view-reqs.
2022-01-16 11:04:40,653 INFO dynamic_tf_policy.py:612 -- Testing `postprocess_trajectory` w/ dummy batch.
2022-01-16 11:04:40,657 DEBUG dynamic_tf_policy.py:645 -- Initializing loss function with dummy input:

{ 'action_dist_inputs': <tf.Tensor 'default_policy/action_dist_inputs:0' shape=(?, 4) dtype=float32>,
  'action_logp': <tf.Tensor 'default_policy/action_logp:0' shape=(?,) dtype=float32>,
  'action_prob': <tf.Tensor 'default_policy/action_prob:0' shape=(?,) dtype=float32>,
  'actions': <tf.Tensor 'default_policy/action:0' shape=(?,) dtype=int64>,
  'agent_index': <tf.Tensor 'default_policy/agent_index:0' shape=(?,) dtype=float32>,
  'dones': <tf.Tensor 'default_policy/dones:0' shape=(?,) dtype=float32>,
  'eps_id': <tf.Tensor 'default_policy/eps_id:0' shape=(?,) dtype=float32>,
  'new_obs': <tf.Tensor 'default_policy/new_obs:0' shape=(?, 84, 84, 4) dtype=uint8>,
  'obs': <tf.Tensor 'default_policy/obs:0' shape=(?, 84, 84, 4) dtype=uint8>,
  'prev_actions': <tf.Tensor 'default_policy/prev_actions:0' shape=(?,) dtype=int64>,
  'prev_rewards': <tf.Tensor 'default_policy/prev_rewards:0' shape=(?,) dtype=float32>,
  'q_values': <tf.Tensor 'default_policy/q_values:0' shape=(?, 4) dtype=float32>,
  'rewards': <tf.Tensor 'default_policy/rewards:0' shape=(?,) dtype=float32>,
  't': <tf.Tensor 'default_policy/t:0' shape=(?,) dtype=float32>,
  'unroll_id': <tf.Tensor 'default_policy/unroll_id:0' shape=(?,) dtype=float32>}

2022-01-16 11:04:42,339 DEBUG tf_policy.py:695 -- These tensors were used in the loss functions:
{ 'action_dist_inputs': <tf.Tensor 'default_policy/action_dist_inputs:0' shape=(?, 4) dtype=float32>,
  'action_logp': <tf.Tensor 'default_policy/action_logp:0' shape=(?,) dtype=float32>,
  'action_prob': <tf.Tensor 'default_policy/action_prob:0' shape=(?,) dtype=float32>,
  'actions': <tf.Tensor 'default_policy/action:0' shape=(?,) dtype=int64>,
  'dones': <tf.Tensor 'default_policy/dones:0' shape=(?,) dtype=float32>,
  'new_obs': <tf.Tensor 'default_policy/new_obs:0' shape=(?, 84, 84, 4) dtype=uint8>,
  'obs': <tf.Tensor 'default_policy/obs:0' shape=(?, 84, 84, 4) dtype=uint8>,
  'q_values': <tf.Tensor 'default_policy/q_values:0' shape=(?, 4) dtype=float32>,
  'rewards': <tf.Tensor 'default_policy/rewards:0' shape=(?,) dtype=float32>}

2022-01-16 11:04:42,834 INFO rollout_worker.py:1555 -- Built policy map: {}
2022-01-16 11:04:42,834 INFO rollout_worker.py:1556 -- Built preprocessor map: {'default_policy': None}
2022-01-16 11:04:42,835 INFO rollout_worker.py:618 -- Built filter map: {'default_policy': <ray.rllib.utils.filter.NoFilter object at 0x7f113008fd00>}
2022-01-16 11:04:42,836 DEBUG rollout_worker.py:728 -- Created rollout worker with env <ray.rllib.env.base_env._MultiAgentEnvToBaseEnv object at 0x7f1054400580> (<new_base<FrameStack<WarpFrame<FireResetEnv<EpisodicLifeEnv<NoopResetEnv<MonitorEnv<TimeLimit<AtariEnv<Breakout-v0>>>>>>>>>>), policies {}
2022-01-16 11:04:42,839 INFO trainable.py:124 -- Trainable.setup took 16.321 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2022-01-16 11:04:42,840 WARNING util.py:57 -- Install gputil for GPU system monitoring.
:actor_name:SimpleQTrainer
:actor_name:SimpleQTrainer
2022-01-16 11:04:42,852 INFO rollout_worker.py:754 -- Generating sample batch of size 1
2022-01-16 11:04:42,853 DEBUG sampler.py:562 -- No episode horizon specified, setting it to Env's limit (10000).
[2022-01-16 11:20:44,582 E 173033 173033] core_worker.cc:1611: Pushed Error with JobID: 01000000 of type: task with message: ray::SimpleQTrainer.train_buffered() (pid=173033, ip=192.168.0.104, repr=SimpleQTrainer)
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/tune/trainable.py", line 255, in train_buffered
    result = self.train()
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/tune/trainable.py", line 314, in train
    result = self.step()
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 885, in step
    raise e
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 867, in step
    result = self.step_attempt()
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 920, in step_attempt
    step_results = next(self.train_exec_impl)
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 1075, in build_union
    item = next(it)
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/execution/rollout_ops.py", line 76, in sampler
    yield workers.local_worker().sample()
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 757, in sample
    batches = [self.input_reader.next()]
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 103, in next
    batches = [self.get_data()]
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 265, in get_data
    item = next(self._env_runner)
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 620, in _env_runner
    base_env.poll()
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/env/base_env.py", line 476, in poll
    obs[i], rewards[i], dones[i], infos[i] = env_state.poll()
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/env/base_env.py", line 552, in poll
    for ag in observations.keys():
AttributeError: 'numpy.ndarray' object has no attribute 'keys' at time: 1.64233e+09
2022-01-16 11:20:44,611 WARNING util.py:165 -- The `start_trial` operation took 978.872 s, which may be a performance bottleneck.
== Status ==
Current time: 2022-01-16 11:20:44 (running for 00:16:19.05)
Memory usage on this node: 21.3/30.8 GiB
Using FIFO scheduling algorithm.
Resources requested: 1.0/4 CPUs, 0/0 GPUs, 0.0/6.63 GiB heap, 0.0/3.32 GiB objects
Result logdir: /home/simon/git-projects/ray-experiments/deepmind_output_tune/SimpleQTrainer_2022-01-16_11-04-25
Number of trials: 1/1 (1 RUNNING)
+----------------------------------------+----------+----------------------+
| Trial name                             | status   | loc                  |
|----------------------------------------+----------+----------------------|
| SimpleQTrainer_Breakout-v0_af5d1_00000 | RUNNING  | 192.168.0.104:173033 |
+----------------------------------------+----------+----------------------+


2022-01-16 11:20:44,659 WARNING ray_trial_executor.py:767 -- Over the last 60 seconds, the Tune event loop has been backlogged processing new results. Consider increasing your period of result reporting to improve performance.
2022-01-16 11:20:44,662 ERROR trial_runner.py:958 -- Trial SimpleQTrainer_Breakout-v0_af5d1_00000: Error processing event.
Traceback (most recent call last):
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/tune/trial_runner.py", line 924, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py", line 787, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/worker.py", line 1713, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::SimpleQTrainer.train_buffered() (pid=173033, ip=192.168.0.104, repr=SimpleQTrainer)
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/tune/trainable.py", line 255, in train_buffered
    result = self.train()
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/tune/trainable.py", line 314, in train
    result = self.step()
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 885, in step
    raise e
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 867, in step
    result = self.step_attempt()
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 920, in step_attempt
    step_results = next(self.train_exec_impl)
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 1075, in build_union
    item = next(it)
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/execution/rollout_ops.py", line 76, in sampler
    yield workers.local_worker().sample()
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 757, in sample
    batches = [self.input_reader.next()]
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 103, in next
    batches = [self.get_data()]
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 265, in get_data
    item = next(self._env_runner)
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 620, in _env_runner
    base_env.poll()
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/env/base_env.py", line 476, in poll
    obs[i], rewards[i], dones[i], infos[i] = env_state.poll()
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/env/base_env.py", line 552, in poll
    for ag in observations.keys():
AttributeError: 'numpy.ndarray' object has no attribute 'keys'
Result for SimpleQTrainer_Breakout-v0_af5d1_00000:
  date: 2022-01-16_11-04-42
  experiment_id: 231bdc90d9a64302ab873d21fb81685f
  hostname: localhost.localdomain
  node_ip: 192.168.0.104
  pid: 173033
  timestamp: 1642327482
  trial_id: af5d1_00000
  
== Status ==
Current time: 2022-01-16 11:20:44 (running for 00:16:19.25)
Memory usage on this node: 21.2/30.8 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/4 CPUs, 0/0 GPUs, 0.0/6.63 GiB heap, 0.0/3.32 GiB objects
Result logdir: /home/simon/git-projects/ray-experiments/deepmind_output_tune/SimpleQTrainer_2022-01-16_11-04-25
Number of trials: 1/1 (1 ERROR)
+----------------------------------------+----------+----------------------+
| Trial name                             | status   | loc                  |
|----------------------------------------+----------+----------------------|
| SimpleQTrainer_Breakout-v0_af5d1_00000 | ERROR    | 192.168.0.104:173033 |
+----------------------------------------+----------+----------------------+
Number of errored trials: 1
+----------------------------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Trial name                             |   # failures | error file                                                                                                                                                              |
|----------------------------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| SimpleQTrainer_Breakout-v0_af5d1_00000 |            1 | /home/simon/git-projects/ray-experiments/deepmind_output_tune/SimpleQTrainer_2022-01-16_11-04-25/SimpleQTrainer_Breakout-v0_af5d1_00000_0_2022-01-16_11-04-25/error.txt |
+----------------------------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Traceback (most recent call last):
  File "/home/simon/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/simon/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/simon/.vscode/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/simon/.vscode/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/simon/.vscode/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/simon/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/simon/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/simon/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/simon/git-projects/ray-experiments/dqn/Minh-et-al-2015/simple_dqn_deepmind_local.py", line 98, in <module>
    tune.run(    
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/tune/tune.py", line 620, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [SimpleQTrainer_Breakout-v0_af5d1_00000])
```

### Versions / Dependencies

OS: Fedora Linux 35
Python: 3.9.0
Ray: 1.9.1
Gym: 0.21.0
atari_py: 0.2.9

Here is a list of my `pip freeze`:

```
absl-py==1.0.0
aiohttp==3.8.1
aiohttp-cors==0.7.0
aioredis==1.3.1
aiosignal==1.2.0
ale-py==0.7.3
astunparse==1.6.3
async-timeout==4.0.2
atari-py==0.2.9
attrs==21.4.0
backcall==0.2.0
blessed==1.19.0
cachetools==4.2.4
certifi==2021.10.8
charset-normalizer==2.0.10
click==8.0.3
cloudpickle==2.0.0
colorful==0.5.4
cycler==0.11.0
debugpy==1.5.1
decorator==5.1.1
Deprecated==1.2.13
dm-tree==0.1.6
entrypoints==0.3
filelock==3.4.2
flatbuffers==2.0
fonttools==4.28.5
frozenlist==1.2.0
gast==0.4.0
google-api-core==2.3.2
google-auth==2.3.3
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
googleapis-common-protos==1.54.0
gpustat==1.0.0b1
grpcio==1.43.0
gym==0.21.0
h5py==3.6.0
hiredis==2.0.0
idna==3.3
imageio==2.13.5
importlib-metadata==4.10.0
importlib-resources==5.4.0
ipykernel==6.6.1
ipython==7.31.0
jedi==0.18.1
jsonschema==4.3.3
jupyter-client==7.1.0
jupyter-core==4.9.1
keras==2.7.0
Keras-Preprocessing==1.1.2
kiwisolver==1.3.2
libclang==12.0.0
lz4==3.1.10
Markdown==3.3.6
matplotlib==3.5.1
matplotlib-inline==0.1.3
msgpack==1.0.3
multidict==5.2.0
nest-asyncio==1.5.4
networkx==2.6.3
numpy==1.22.0
nvidia-ml-py3==7.352.0
oauthlib==3.1.1
opencensus==0.8.0
opencensus-context==0.1.2
opt-einsum==3.3.0
packaging==21.3
pandas==1.3.5
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.0.0
prometheus-client==0.12.0
prompt-toolkit==3.0.24
protobuf==3.19.1
psutil==5.9.0
ptyprocess==0.7.0
py-spy==0.3.11
pyasn1==0.4.8
pyasn1-modules==0.2.8
Pygments==2.11.2
pyparsing==3.0.6
pyrsistent==0.18.0
python-dateutil==2.8.2
pytz==2021.3
PyWavelets==1.2.0
PyYAML==6.0
pyzmq==22.3.0
ray==1.9.1
redis==4.1.0
requests==2.27.1
requests-oauthlib==1.3.0
rsa==4.8
scikit-image==0.19.1
scipy==1.7.3
six==1.16.0
smart-open==5.2.1
svgwrite==1.4.1
tabulate==0.8.9
tensorboard==2.7.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorboardX==2.4.1
tensorflow==2.7.0
tensorflow-estimator==2.7.0
tensorflow-io-gcs-filesystem==0.23.1
termcolor==1.1.0
tifffile==2021.11.2
tornado==6.1
traitlets==5.1.1
typing_extensions==4.0.1
urllib3==1.26.7
wcwidth==0.2.5
Werkzeug==2.0.2
wrapt==1.13.3
yarl==1.7.2
zipp==3.7.0
```

### Reproduction script

Here is a minimal script that reproduces the error: 

```
import ray
from ray import tune
import ray.rllib.agents.dqn as dqn

CONFIG = dqn.SIMPLE_Q_DEFAULT_CONFIG.copy()

# Environment #
###############
CONFIG['env'] = "Breakout-v0"
#CONFIG['render_env'] = True
CONFIG['record_env'] = "/home/simon/git-projects-ray-experiments/videos"

# Resources #
#############
CONFIG['log_level'] = 'DEBUG'
CONFIG['num_workers'] = 0
CONFIG['num_gpus'] = 0

# Start the ray cluster.
ray.init(local_mode=True)

# NOTE: Ensure that you installed next to 'ray[default]'
# also 'ray[tune]'. Otherwise, tune cannot write out the
# TensorBoard event files.
tune.run(    
    dqn.SimpleQTrainer,
    config=CONFIG,
    local_dir="output_tune",
    keep_checkpoints_num=3,
    stop={"training_iteration": 4},
    fail_fast=True,
    checkpoint_freq=1
)
```

### Anything else

This problem occurs everytime the example code gets executed. 

I already tried to change the last wrapping environment in the `record_env_wrapper()` function (`env/utils.py`) from `[MuliAgentEnv]` to `[VectorEnv]`, but his did not work. I also tried to change the `reset()` function of the `_MultiAgentEnvState` class by setting `self.last_obs = {0: self.env.reset()}` but as the `poll()` function of the `_MultiAgentEnvState` class gets called by the `poll()` method of the `_MultiAgentEnvToBaseEnv` class the result is a `MutliAgentDict` in a `MultiAgentDict` when the `poll()` function of the latter class got called (sth. like `{0: {0: np.array(...)}}`).  

I am willing to set up a PR, however I have to few knowledge about the environments and where specific functionalities are used. So, I would need here your guidance to understand at which location which screws have to be turned. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by sven1977** [comment]
I can reproduce the issue. Happens also with CartPole (seems not Atari related). I'll debug ...

**Comment by sven1977** [comment]
Hey @simonsays1980 , here is a PR that hopefully fixes your issue. The repro script is working on this PR. I also enhanced the existing test case to actually check for mp4 files to be created in both the single-agent case (sub-class gym.Env) and the multi-agent case (sub-class our MultiAgentEnv).

**Comment by sven1977** [comment]
https://github.com/ray-project/ray/pull/21670
