### ISSUE TITLE
[Bug] RLLib custom model metrics `policy.model.metrics()` are not logged when training with GPUs

### ISSUE THREAD

**Issue by XuehaiPan** [ray-project/ray#21671]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

I'm trying to train RL policies with custom models and additional custom losses.

I implement method `model.metrics()` to log my custom loss to the TensorBoard. Same as the example `rllib/examples/models/custom_loss_model.py` do:

https://github.com/ray-project/ray/blob/ef593fe5d3c864836b80ae77be32635cef42b537/rllib/examples/models/custom_loss_model.py#L153-L157

I ran the example `rllib/examples/custom_model_loss_and_metrics.py`:

```bash
cd /path/to/ray/git/repo
python3 -m ray.rllib.examples.custom_model_loss_and_metrics --run PPO --framework torch --input-files "${PWD}/rllib/tests/data/cartpole/small.json" --stop-iters 1
```

The entries `info/learner/default_policy/model/policy_loss` and `info/learner/default_policy/model/imitation_loss_loss` can be logged to the TensorBoard successfully.

However, in `rllib/examples/custom_model_loss_and_metrics.py`:

https://github.com/ray-project/ray/blob/ef593fe5d3c864836b80ae77be32635cef42b537/rllib/examples/custom_model_loss_and_metrics.py#L64-L76

`num_gpus` is `0` by default, it is training with only a local worker on CPU.

When I set `RLLIB_NUM_GPUS=1`, the keys `info/learner/default_policy/model/*` disappear in logs.

### Versions / Dependencies

Ray 1.9.2

### Reproduction script

```bash
cd /path/to/ray/git/repo
RLLIB_NUM_GPUS=1 python3 -m ray.rllib.examples.custom_model_loss_and_metrics \
    --run PPO \
    --framework torch \
    --input-files "${PWD}/rllib/tests/data/cartpole/small.json" \
    --stop-iters 1
```

------

```console
$ cd /path/to/ray/git/repo

$ RLLIB_NUM_GPUS=0 python3 -m ray.rllib.examples.custom_model_loss_and_metrics --run PPO --framework torch --input-files "${PWD}/rllib/tests/data/cartpole/small.json" --stop-iters 1
2022-01-18 22:40:11,425 INFO services.py:1338 -- View the Ray dashboard at http://127.0.0.1:8265
(PPO pid=1292332) 2022-01-18 22:40:13,781       INFO ppo.py:166 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
(PPO pid=1292332) 2022-01-18 22:40:13,781       INFO trainer.py:743 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(PPO pid=1292332) 2022-01-18 22:40:13,800       WARNING util.py:57 -- Install gputil for GPU system monitoring.
...

$ echo $?
0

$ RLLIB_NUM_GPUS=1 python3 -m ray.rllib.examples.custom_model_loss_and_metrics --run PPO --framework torch --input-files "${PWD}/rllib/tests/data/cartpole/small.json" --stop-iters 1
2022-01-18 22:55:15,036 INFO services.py:1338 -- View the Ray dashboard at http://127.0.0.1:8265
(PPO pid=1314579) 2022-01-18 22:55:17,420       INFO ppo.py:166 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
(PPO pid=1314579) 2022-01-18 22:55:17,420       INFO trainer.py:743 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
== Status ==
Current time: 2022-01-18 22:55:21 (running for 00:00:05.61)
Memory usage on this node: 18.1/31.2 GiB
Using FIFO scheduling algorithm.
Resources requested: 3.0/12 CPUs, 1.0/1 GPUs, 0.0/11.45 GiB heap, 0.0/5.72 GiB objects (0.0/1.0 accelerator_type:G)
Result logdir: /home/PanXuehai/ray_results/PPO
Number of trials: 1/1 (1 RUNNING)


(PPO pid=1314579) 2022-01-18 22:55:21,655       WARNING util.py:57 -- Install gputil for GPU system monitoring.
== Status ==
Current time: 2022-01-18 22:55:22 (running for 00:00:06.61)
Memory usage on this node: 18.1/31.2 GiB
Using FIFO scheduling algorithm.
Resources requested: 3.0/12 CPUs, 1.0/1 GPUs, 0.0/11.45 GiB heap, 0.0/5.72 GiB objects (0.0/1.0 accelerator_type:G)
Result logdir: /home/PanXuehai/ray_results/PPO
Number of trials: 1/1 (1 RUNNING)


== Status ==
Current time: 2022-01-18 22:55:27 (running for 00:00:11.62)
Memory usage on this node: 18.2/31.2 GiB
Using FIFO scheduling algorithm.
Resources requested: 3.0/12 CPUs, 1.0/1 GPUs, 0.0/11.45 GiB heap, 0.0/5.72 GiB objects (0.0/1.0 accelerator_type:G)
Result logdir: /home/PanXuehai/ray_results/PPO
Number of trials: 1/1 (1 RUNNING)


== Status ==
Current time: 2022-01-18 22:55:30 (running for 00:00:14.87)
Memory usage on this node: 18.2/31.2 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/12 CPUs, 0/1 GPUs, 0.0/11.45 GiB heap, 0.0/5.72 GiB objects (0.0/1.0 accelerator_type:G)
Result logdir: /home/PanXuehai/ray_results/PPO
Number of trials: 1/1 (1 TERMINATED)


(RolloutWorker pid=1314575) 2022-01-18 22:55:31,476     ERROR worker.py:431 -- SystemExit was raised from the worker
(RolloutWorker pid=1314575) Traceback (most recent call last):
(RolloutWorker pid=1314575)   File "python/ray/_raylet.pyx", line 618, in ray._raylet.execute_task
(RolloutWorker pid=1314575)     raise_if_dependency_failed(arg)
(RolloutWorker pid=1314575)   File "python/ray/_raylet.pyx", line 625, in ray._raylet.execute_task
(RolloutWorker pid=1314575)     core_worker.set_actor_title(actor_title.encode("utf-8"))
(RolloutWorker pid=1314575)   File "python/ray/_raylet.pyx", line 629, in ray._raylet.execute_task
(RolloutWorker pid=1314575)     try:
(RolloutWorker pid=1314575)   File "python/ray/_raylet.pyx", line 578, in ray._raylet.execute_task.function_executor
(RolloutWorker pid=1314575)     if function.name.startswith("__ray"):
(RolloutWorker pid=1314575)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/site-packages/ray/_private/function_manager.py", line 609, in actor_method_executor
(RolloutWorker pid=1314575)     return method(__ray_actor, *args, **kwargs)
(RolloutWorker pid=1314575)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 451, in _resume_span
(RolloutWorker pid=1314575)     return method(self, *_args, **_kwargs)
(RolloutWorker pid=1314575)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/site-packages/ray/actor.py", line 1081, in __ray_terminate__
(RolloutWorker pid=1314575)     ray.actor.exit_actor()
(RolloutWorker pid=1314575)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/site-packages/ray/actor.py", line 1160, in exit_actor
(RolloutWorker pid=1314575)     raise exit
(RolloutWorker pid=1314575) SystemExit: 0
(RolloutWorker pid=1314575) 
(RolloutWorker pid=1314575) During handling of the above exception, another exception occurred:
(RolloutWorker pid=1314575) 
(RolloutWorker pid=1314575) Traceback (most recent call last):
(RolloutWorker pid=1314575)   File "python/ray/_raylet.pyx", line 759, in ray._raylet.task_execution_handler
(RolloutWorker pid=1314575)     shared_ptr[LocalMemoryBuffer] &creation_task_exception_pb_bytes,
(RolloutWorker pid=1314575)   File "python/ray/_raylet.pyx", line 580, in ray._raylet.execute_task
(RolloutWorker pid=1314575)     async_function = sync_to_async(function)
(RolloutWorker pid=1314575)   File "python/ray/includes/libcoreworker.pxi", line 33, in ray._raylet.ProfileEvent.__exit__
(RolloutWorker pid=1314575)     "traceback": str(traceback.format_exc()),
(RolloutWorker pid=1314575)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/traceback.py", line 167, in format_exc
(RolloutWorker pid=1314575)     return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
(RolloutWorker pid=1314575)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/traceback.py", line 120, in format_exception
(RolloutWorker pid=1314575)     return list(TracebackException(
(RolloutWorker pid=1314575)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/traceback.py", line 616, in format
(RolloutWorker pid=1314575)     yield from self.stack.format()
(RolloutWorker pid=1314575)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/traceback.py", line 424, in format
(RolloutWorker pid=1314575)     frame.filename, frame.lineno, frame.name))
(RolloutWorker pid=1314575)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/site-packages/ray/worker.py", line 428, in sigterm_handler
(RolloutWorker pid=1314575)     sys.exit(1)
(RolloutWorker pid=1314575) SystemExit: 1
(RolloutWorker pid=1314580) 2022-01-18 22:55:31,476     ERROR worker.py:431 -- SystemExit was raised from the worker
(RolloutWorker pid=1314580) Traceback (most recent call last):
(RolloutWorker pid=1314580)   File "python/ray/_raylet.pyx", line 618, in ray._raylet.execute_task
(RolloutWorker pid=1314580)     raise_if_dependency_failed(arg)
(RolloutWorker pid=1314580)   File "python/ray/_raylet.pyx", line 625, in ray._raylet.execute_task
(RolloutWorker pid=1314580)     core_worker.set_actor_title(actor_title.encode("utf-8"))
(RolloutWorker pid=1314580)   File "python/ray/_raylet.pyx", line 629, in ray._raylet.execute_task
(RolloutWorker pid=1314580)     try:
(RolloutWorker pid=1314580)   File "python/ray/_raylet.pyx", line 578, in ray._raylet.execute_task.function_executor
(RolloutWorker pid=1314580)     if function.name.startswith("__ray"):
(RolloutWorker pid=1314580)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/site-packages/ray/_private/function_manager.py", line 609, in actor_method_executor
(RolloutWorker pid=1314580)     return method(__ray_actor, *args, **kwargs)
(RolloutWorker pid=1314580)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 451, in _resume_span
(RolloutWorker pid=1314580)     return method(self, *_args, **_kwargs)
(RolloutWorker pid=1314580)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/site-packages/ray/actor.py", line 1081, in __ray_terminate__
(RolloutWorker pid=1314580)     ray.actor.exit_actor()
(RolloutWorker pid=1314580)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/site-packages/ray/actor.py", line 1160, in exit_actor
(RolloutWorker pid=1314580)     raise exit
(RolloutWorker pid=1314580) SystemExit: 0
(RolloutWorker pid=1314580) 
(RolloutWorker pid=1314580) During handling of the above exception, another exception occurred:
(RolloutWorker pid=1314580) 
(RolloutWorker pid=1314580) Traceback (most recent call last):
(RolloutWorker pid=1314580)   File "python/ray/_raylet.pyx", line 759, in ray._raylet.task_execution_handler
(RolloutWorker pid=1314580)     shared_ptr[LocalMemoryBuffer] &creation_task_exception_pb_bytes,
(RolloutWorker pid=1314580)   File "python/ray/_raylet.pyx", line 580, in ray._raylet.execute_task
(RolloutWorker pid=1314580)     async_function = sync_to_async(function)
(RolloutWorker pid=1314580)   File "python/ray/includes/libcoreworker.pxi", line 33, in ray._raylet.ProfileEvent.__exit__
(RolloutWorker pid=1314580)     "traceback": str(traceback.format_exc()),
(RolloutWorker pid=1314580)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/traceback.py", line 167, in format_exc
(RolloutWorker pid=1314580)     return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
(RolloutWorker pid=1314580)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/traceback.py", line 120, in format_exception
(RolloutWorker pid=1314580)     return list(TracebackException(
(RolloutWorker pid=1314580)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/traceback.py", line 508, in __init__
(RolloutWorker pid=1314580)     self.stack = StackSummary.extract(
(RolloutWorker pid=1314580)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/traceback.py", line 366, in extract
(RolloutWorker pid=1314580)     f.line
(RolloutWorker pid=1314580)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/traceback.py", line 288, in line
(RolloutWorker pid=1314580)     self._line = linecache.getline(self.filename, self.lineno).strip()
(RolloutWorker pid=1314580)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/linecache.py", line 16, in getline
(RolloutWorker pid=1314580)     lines = getlines(filename, module_globals)
(RolloutWorker pid=1314580)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/linecache.py", line 41, in getlines
(RolloutWorker pid=1314580)     if filename in cache:
(RolloutWorker pid=1314580)   File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/site-packages/ray/worker.py", line 428, in sigterm_handler
(RolloutWorker pid=1314580)     sys.exit(1)
(RolloutWorker pid=1314580) SystemExit: 1
2022-01-18 22:55:31,582 INFO tune.py:626 -- Total run time: 15.57 seconds (14.86 seconds for the tuning loop).
Traceback (most recent call last):
  File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/PanXuehai/Miniconda3/envs/active-pose/lib/python3.8/site-packages/ray/rllib/examples/custom_model_loss_and_metrics.py", line 87, in <module>
    assert "model" in info[LEARNER_INFO][DEFAULT_POLICY_ID]
AssertionError
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by XuehaiPan** [comment]
I created a PR #21671 to fix `TorchPolicy` training with multi-GPU optimizer (`multi_gpu_train_one_step` or `MultiGPUTrainOneStep`). Not so sure for `TFPolicy`.
