### ISSUE TITLE
[Bug] Dask on ray 1tb sort failing due to input file not found error

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#21682]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

https://buildkite.com/ray-project/periodic-ci/builds/2414#7b967590-572d-458a-97b5-24efdd10b4af
https://buildkite.com/ray-project/periodic-ci/builds/2405#75fbbe3c-58d3-4d90-8c74-e60a7b3c02b8

```


Traceback (most recent call last):
--
  | File "dask_on_ray/dask_on_ray_sort.py", line 193, in <module>
  | file_path=args.file_path))
  | File "dask_on_ray/dask_on_ray_sort.py", line 108, in trial
  | df = load_dataset(client, data_dir, s3_bucket, nbytes, n_partitions)
  | File "dask_on_ray/dask_on_ray_sort.py", line 55, in load_dataset
  | df = dd.read_parquet(filenames)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 338, in read_parquet
  | **kwargs,
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/dask/dataframe/io/parquet/arrow.py", line 342, in read_metadata
  | **kwargs.get("dataset", {}),
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/dask/dataframe/io/parquet/arrow.py", line 866, in _collect_dataset_info
  | **partitioning.get("kwargs", {}),
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/pyarrow/dataset.py", line 683, in dataset
  | return _filesystem_dataset(source, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/pyarrow/dataset.py", line 435, in _filesystem_dataset
  | return factory.finish(schema)
  | File "pyarrow/_dataset.pyx", line 2473, in pyarrow._dataset.DatasetFactory.finish
  | File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  | File "pyarrow/_fs.pyx", line 1161, in pyarrow._fs._cb_open_input_file
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/pyarrow/fs.py", line 393, in open_input_file
  | raise FileNotFoundError(path)
  | FileNotFoundError: core-nightly-test/df-100-0.parquet.gzip


```

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
The files still seem to be in the bucket. At a high level, it seems that somehow Dataset is now interpreting the URI as a local path, perhaps due to an unknown upstream dependency change. @clarkzinzow since you're most familiar with this code could you take a look?

**Comment by rkooo567** [comment]
Confirmed it is fixed in the master magically. Maybe there was some infra failures.
