### ISSUE TITLE
[Bug] `actor_deaths` long running test starts failing.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#21699]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

https://buildkite.com/ray-project/periodic-ci/builds/2415#4df29c1c-19e3-4c04-a8a3-086b6597f1ed

seems to fail. It failed last week due to infra failures. 

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mwtian** [comment]
This looks like infra failure / job submission flakiness. Logs from [a failed run](https://buildkite.com/ray-project/periodic-ci/builds/2415#5dd794ed-22c5-4594-96f4-45212991be03/113-458):
```
[INFO 2022-01-19 10:47:48,182] e2e.py: 398  Executing pip install -q awscli && aws s3 cp /tmp/release_test_out.json s3://ray-release-automation-results/tmp/uewsmoqikx --acl bucket-owner-full-control with {} via ray job submit
--
  | Job submission server address: anyscale://actor_deaths_1642613973
  | Authenticating
  | Loaded Anyscale authentication token from ANYSCALE_CLI_TOKEN.
  |  
  | (anyscale +0.1s) Attempting to access cluster actor_deaths_1642613973 to interact with jobs ...
  | Output
  | (anyscale +0.6s) .anyscale.yaml found in project_dir. Directory is attached to a project.
  | (anyscale +0.9s) Using project (name: e2e-tests, project_dir: /home/ray/ray/release/long_running_tests, id: prj_2xR6uT6t7jJuu1aCwWMsle).
  | (anyscale +2.8s) cluster actor_deaths_1642613973 is currently running, the cluster will not be restarted.
  | Traceback (most recent call last):
  | File "/home/ray/anaconda3/bin/ray", line 8, in <module>
  | sys.exit(main())
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1960, in main
  | return cli()
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
  | return self.main(*args, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1053, in main
  | rv = self.invoke(ctx)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
  | return _process_result(sub_ctx.command.invoke(sub_ctx))
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
  | return _process_result(sub_ctx.command.invoke(sub_ctx))
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 754, in invoke
  | return __callback(*args, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py", line 808, in wrapper
  | return f(*args, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/cli.py", line 130, in job_submit
  | client = _get_sdk_client(address, create_cluster_if_needed=True)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/cli.py", line 28, in _get_sdk_client
  | return JobSubmissionClient(address, create_cluster_if_needed)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/sdk.py", line 130, in __init__
  | self._check_connection_and_version()
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/sdk.py", line 141, in _check_connection_and_version
  | r.raise_for_status()
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://session-7d1enii9hckvs9ena47mby6l.i.anyscaleuserdata.com/api/version
  | Process Process-1:
  | Traceback (most recent call last):
  | File "e2e.py", line 1798, in _run
  | state_str="CMD_RUN")
  | File "e2e.py", line 1182, in wait_for_session_command_to_complete
  | _check_stop(stop_event, "command")
  | File "e2e.py", line 617, in _check_stop
  | "Process timed out while running a command.")
  | CommandTimeoutError: Process timed out while running a command.
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/home/ray/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
  | self.run()
  | File "/home/ray/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
  | self._target(*self._args, **self._kwargs)
  | File "e2e.py", line 1828, in _run
  | session_controller=session_controller, scd_id=scd_id)
  | File "e2e.py", line 1511, in _process_finished_command
  | session_controller=session_controller,
  | File "e2e.py", line 1234, in get_remote_json_content
  | target=local_target_file)
  | File "e2e.py", line 445, in pull
  | Filename=target,
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/boto3/s3/inject.py", line 173, in download_file
  | extra_args=ExtraArgs, callback=Callback)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/boto3/s3/transfer.py", line 315, in download_file
  | future.result()
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/s3transfer/futures.py", line 106, in result
  | return self._coordinator.result()
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/s3transfer/futures.py", line 265, in result
  | raise self._exception
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/s3transfer/tasks.py", line 255, in _main
  | self._submit(transfer_future=transfer_future, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/s3transfer/download.py", line 343, in _submit
  | **transfer_future.meta.call_args.extra_args
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 391, in _api_call
  | return self._make_api_call(operation_name, kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 719, in _make_api_call
  | raise error_class(parsed_response, operation_name)
  | botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```
Logs from [a successful run](https://buildkite.com/ray-project/periodic-ci/builds/2415#58c629e9-0182-4936-88de-5c53ce1bb12f/81-414) of `actor_deaths` on retry:
```
[INFO 2022-01-19 12:25:16,228] e2e.py: 398  Executing pip install -q awscli && aws s3 cp /tmp/release_test_out.json s3://ray-release-automation-results/tmp/gmxgwavqbj --acl bucket-owner-full-control with {} via ray job submit
  | Job submission server address: anyscale://actor_deaths_1642619767
  | Authenticating
  | Loaded Anyscale authentication token from ANYSCALE_CLI_TOKEN.
  |  
  | (anyscale +0.2s) Attempting to access cluster actor_deaths_1642619767 to interact with jobs ...
  | Output
  | (anyscale +0.3s) .anyscale.yaml found in project_dir. Directory is attached to a project.
  | (anyscale +0.3s) Using project (name: e2e-tests, project_dir: /home/ray/ray/release/long_running_tests, id: prj_2xR6uT6t7jJuu1aCwWMsle).
  | (anyscale +1.4s) cluster actor_deaths_1642619767 is currently running, the cluster will not be restarted.
  |  
  | -------------------------------------------------------
  | Job 'raysubmit_WLpiNhxutq9freFQ' submitted successfully
  | -------------------------------------------------------
  |  
  | Next steps
  | Query the logs of the job:
  | ray job logs raysubmit_WLpiNhxutq9freFQ
  | Query the status of the job:
  | ray job status raysubmit_WLpiNhxutq9freFQ
  | Request the job to be stopped:
  | ray job stop raysubmit_WLpiNhxutq9freFQ
  |  
  | Tailing logs until the job exits (disable with --no-wait):
  | Completed 164 Bytes/164 Bytes (787 Bytes/s) with 1 file(s) remaining
  | upload: ../../../tmp/release_test_out.json to s3://ray-release-automation-results/tmp/gmxgwavqbj
  |  
  | ------------------------------------------
  | Job 'raysubmit_WLpiNhxutq9freFQ' succeeded
  | ------------------------------------------
```
The change to use job submission may be recent (#21626) cc @krfricke

**Comment by mwtian** [comment]
The infra failure from last week also looks like related to the step of using a job to upload result. The issue might not have been fixed completely.

**Comment by mwtian** [comment]
Just for notes, the performance of the actor death test does not look too different before and after enabling GCS pubsub. [Before](https://buildkite.com/ray-project/periodic-ci/builds/2328#249a5616-58f0-413e-a56b-eb20c5b3237c/139-491):
```
iteration = 902
--
  | iteration_time = 3.727541923522949
  | absolute_time = 1641928331.5093417
  | elapsed_time = 3604.168808221817
  | last_update = 1641928331.509364
  | last_update_diff = 1.4896841049194336
  | smoke_test = True
  | _runtime = None
  | _session_url = None
  | _commit_url = None
  | _stable = True
```
[After](https://buildkite.com/ray-project/periodic-ci/builds/2415#58c629e9-0182-4936-88de-5c53ce1bb12f/81-449):
```
iteration = 956
--
  | iteration_time = 3.3697659969329834
  | absolute_time = 1642623951.8020906
  | elapsed_time = 3604.1222450733185
  | last_update = 1642623951.8021111
  | last_update_diff = 18.199464082717896
  | smoke_test = True
  | _runtime = None
  | _session_url = None
  | _commit_url = None
  | _stable = True
```

**Comment by mwtian** [comment]
Reassigning to @simon-mo who seems to have the most context on job submission and e2e tests.

**Comment by mwtian** [comment]
As @simon-mo pointed out off thread, `requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://session-7d1enii9hckvs9ena47mby6l.i.anyscaleuserdata.com/api/version` during job submission is likely from dashboard being unresponsive. We should double check if dashboard is healthy during the test.

**Comment by mwtian** [comment]
I found one instance where `dashboard` exited due to transient error from the GCS aio subscriber to error info. Sent https://github.com/ray-project/ray/pull/21712 to fix.

**Comment by mwtian** [comment]
After #21712 was merged, dashboard stayed alive throughout the tests. But there are still failures during the job submission step to access `session-{id}.i.anyscaleuserdata.com/api/version`, when the job submission takes more than 2min. I have not observed accessing the endpoint taking more than 2 min, but it regularly takes 10s ~ 30s. The stack from dashboard regularly contains synchronous operation against GCS KV, e.g.
```
Thread 3200 (idle): "MainThread"
    _blocking (grpc/_channel.py:933)
    __call__ (grpc/_channel.py:945)
    internal_kv_keys (ray/_private/gcs_utils.py:284)
    wrapper (ray/_private/gcs_utils.py:144)
    _internal_kv_list (ray/experimental/internal_kv.py:112)
    wrapper (ray/_private/client_mode_hook.py:105)
    get_serve_info (ray/dashboard/modules/snapshot/snapshot_head.py:165)
    get_actor_info (ray/dashboard/modules/snapshot/snapshot_head.py:136)
    snapshot (ray/dashboard/modules/snapshot/snapshot_head.py:56)
    _handler_route (ray/dashboard/utils.py:130)
    _handle (aiohttp/web_app.py:499)
    _handle_request (aiohttp/web_protocol.py:422)
    _run (asyncio/events.py:88)
    _run_once (asyncio/base_events.py:1786)
    run_forever (asyncio/base_events.py:541)
    run_until_complete (asyncio/base_events.py:574)
    <module> (ray/dashboard/dashboard.py:243)
```
cc @iycheng

**Comment by mwtian** [comment]
Still working on the fix (https://github.com/ray-project/ray/pull/21762).

**Comment by mwtian** [comment]
The `actor_deaths` test is passing consistently now. No other failure has the same problem of job submission unavailability / timeout. Closing this issue.

**Comment by rkooo567** [comment]
Thanks for handling this @mwtian !!
