### ISSUE TITLE
[Bug][kubernetes][core] `ray memory` fails with certain Ray on K8s set-ups 

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#22021]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

Deploying with the config described here
https://github.com/ray-project/ray/issues/21870#issuecomment-1023785346
and running `ray memory` on the Ray head node leads to the following rpc error
```
(base) ray@example-cluster-ray-head-hrz6z:/ludwig$ ray memory
Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1989, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1505, in memory
    units, no_format, stats_only, num_entries)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/internal/internal_api.py", line 39, in memory_summary
    num_entries) + get_store_stats(state))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/memory_utils.py", line 369, in memory_summary
    raylet["NodeManagerPort"]))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/internal/internal_api.py", line 103, in node_stats
    timeout=30.0)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1643673168.681880455","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3008,"referenced_errors":[{"created":"@1643673168.681877165","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>
```

### Versions / Dependencies

1.9.2 Ray on K8s with Ray repo's operator

### Reproduction script

Run `ray memory` as described above.

### Anything else

Was not able to reproduce with default helm chart.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
Moved to https://github.com/ray-project/kuberay/issues/710.
