### ISSUE TITLE
[Bug] Multi-node Dask on Ray cluster fails to write to tmp folder 

### ISSUE THREAD

**Issue by toza-mimoza** [ray-project/ray#22031]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

1. Ray cluster with one node works fine and sees the tmp folder, but adding multiple nodes files are not written/found in the tmp folder. I am trying to run Rasa training code in parallel on multiple nodes, so far the single node Ray cluster does work and Dask graph components are executed in parallel on one machine.
2. Expected: Multi-node Ray sees tmp folder files. 
3. Logs:

**The training run output:**

```
$ NUMEXPR_MAX_THREADS=16 RASA_MAX_CACHE_SIZE=0 rasa train

(dask:schema_validator pid=7201) 2022-02-01 12:10:21.409600: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(dask:schema_validator pid=7201) 2022-02-01 12:10:21.409644: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
(dask:schema_validator pid=7201) /home/azureuser/bot/Raysa-Rasa/rasa/shared/core/slot_mappings.py:217: UserWarning: Slot auto-fill has been removed in 3.0 and replaced with a new explicit mechanism to set slots. Please refer to https://rasa.com/docs/rasa/domain#slots to learn more.
(dask:schema_validator pid=7201)   UserWarning,
(dask:schema_validator pid=7201) 
Processed story blocks: 100%|██████████| 3/3 [00:00<00:00, 1873.29it/s, # trackers=1]
Processed story blocks: 100%|██████████| 3/3 [00:00<00:00, 901.29it/s, # trackers=3]
Processed story blocks:   0%|          | 0/3 [00:00<?, ?it/s, # trackers=12]
Processed story blocks: 100%|██████████| 3/3 [00:00<00:00, 198.16it/s, # trackers=12]
Processed story blocks: 100%|██████████| 3/3 [00:00<00:00, 47.87it/s, # trackers=39]
Processed rules: 100%|██████████| 2/2 [00:00<00:00, 3002.37it/s, # trackers=1]
(dask:run_WhitespaceTokenizer0 pid=7200) 2022-02-01 12:10:24.982439: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(dask:run_WhitespaceTokenizer0 pid=7200) 2022-02-01 12:10:24.982482: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
(dask:train_MemoizationPolicy0 pid=3110, ip=10.2.0.5) 2022-02-01 12:10:25.410660: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(dask:train_MemoizationPolicy0 pid=3110, ip=10.2.0.5) 2022-02-01 12:10:25.410690: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
(dask:train_RulePolicy1 pid=3109, ip=10.2.0.5) 2022-02-01 12:10:25.410471: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(dask:train_RulePolicy1 pid=3109, ip=10.2.0.5) 2022-02-01 12:10:25.410509: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
(dask:train_TEDPolicy3 pid=2942, ip=10.2.0.6) 2022-02-01 12:10:26.230292: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(dask:train_TEDPolicy3 pid=2942, ip=10.2.0.6) 2022-02-01 12:10:26.230338: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
(dask:train_UnexpecTEDIntentPolicy2 pid=2990, ip=10.2.0.6) 2022-02-01 12:10:27.070685: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(dask:train_UnexpecTEDIntentPolicy2 pid=2990, ip=10.2.0.6) 2022-02-01 12:10:27.070749: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
File "/home/azureuser/miniconda3/envs/raysa_env/bin/rasa", line 5, in <module>
main()
File "/home/azureuser/bot/Raysa-Rasa/rasa/__main__.py", line 119, in main
cmdline_arguments.func(cmdline_arguments)
File "/home/azureuser/bot/Raysa-Rasa/rasa/cli/train.py", line 60, in <lambda>
train_parser.set_defaults(func=lambda args: run_training(args, can_exit=True))
File "/home/azureuser/bot/Raysa-Rasa/rasa/cli/train.py", line 127, in run_training
finetuning_epoch_fraction=args.epoch_fraction,
File "/home/azureuser/bot/Raysa-Rasa/rasa/api.py", line 118, in train_dist
finetuning_epoch_fraction=finetuning_epoch_fraction,
File "/home/azureuser/bot/Raysa-Rasa/rasa/model_training.py", line 175, in train_dist
**(nlu_additional_arguments or {}),
File "/home/azureuser/bot/Raysa-Rasa/rasa/model_training.py", line 241, in _train_graph_dist
is_finetuning=is_finetuning,
File "/home/azureuser/bot/Raysa-Rasa/rasa/engine/training/graph_trainer.py", line 174, in train_dist
graph_runner.run(inputs={PLACEHOLDER_IMPORTER: importer})
File "/home/azureuser/bot/Raysa-Rasa/rasa/engine/runner/dask_on_ray.py", line 132, in run
dask_result = ray_dask_get(run_graph, run_targets)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 127, in ray_dask_get
result = ray_get_unpack(object_refs, progress_bar_actor=pb_actor)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 423, in ray_get_unpack
return get_result(object_refs)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 408, in get_result
return ray.get(object_refs)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
return func(*args, **kwargs)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/ray/worker.py", line 1713, in get
raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(GraphComponentException): ray::dask:train_RulePolicy1 (pid=3109, ip=10.2.0.5)
File "/home/azureuser/bot/Raysa-Rasa/rasa/core/policies/rule_policy.py", line 813, in train
self.persist()
File "/home/azureuser/bot/Raysa-Rasa/rasa/core/policies/rule_policy.py", line 1227, in persist
super().persist()
File "/home/azureuser/bot/Raysa-Rasa/rasa/core/policies/memoization.py", line 269, in persist
with self._model_storage.write_to(self._resource) as path:
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/contextlib.py", line 112, in __enter__
return next(self.gen)
File "/home/azureuser/bot/Raysa-Rasa/rasa/engine/storage/local_model_storage.py", line 121, in write_to
directory.mkdir()
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/pathlib.py", line 1273, in mkdir
self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpu7urph5j/train_RulePolicy1'

The above exception was the direct cause of the following exception:

ray::dask:train_RulePolicy1 (pid=3109, ip=10.2.0.5)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 350, in dask_task_wrapper
result = func(*actual_args)
File "/home/azureuser/bot/Raysa-Rasa/rasa/engine/graph.py", line 516, in __call__
) from e
rasa.engine.exceptions.GraphComponentException: Error running graph component for node train_RulePolicy1.
Processed trackers: 100%|██████████| 2/2 [00:00<00:00, 3535.02it/s, # action=5]
Processed actions: 5it [00:00, 14716.86it/s, # examples=4]
Processed trackers: 100%|██████████| 3/3 [00:00<00:00, 2752.77it/s, # action=12]
Processed trackers: 100%|██████████| 2/2 [00:00<00:00, 1933.30it/s]
Processed trackers: 100%|██████████| 5/5 [00:00<00:00, 1468.49it/s]
Processed trackers: 100%|██████████| 3/3 [00:00<00:00, 2149.46it/s, # action=12]
Processed actions: 12it [00:00, 11554.56it/s, # examples=12]
```

**The worker logs:** 
```
$ cat /tmp/ray/session_latest/logs/worker-89c39c5522a62c8d578fbe6b9b62d17693c053f97fc2cd4a10ef3d12-05000000-6942.err

:task_name:dask:schema_validator
2022-02-01 12:04:17.308126: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-02-01 12:04:17.308172: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/azureuser/bot/Raysa-Rasa/rasa/shared/core/slot_mappings.py:217: UserWarning: Slot auto-fill has been removed in 3.0 and replaced with a new explicit mechanism to set slots. Please refer to https://rasa.com/docs/rasa/domain#slots to learn more.
UserWarning,
:task_name:dask:finetuning_validator
:task_name:dask:story_graph_provider
:task_name:dask:domain_provider
:task_name:dask:nlu_training_data_provider
:task_name:dask:domain_for_core_training_provider
:task_name:dask:training_tracker_provider
Processed story blocks: 100%|██████████| 3/3 [00:00<00:00, 1999.51it/s, # trackers=1]
Processed story blocks: 100%|██████████| 3/3 [00:00<00:00, 799.12it/s, # trackers=3]
Processed story blocks: 100%|██████████| 3/3 [00:00<00:00, 172.96it/s, # trackers=12]
Processed story blocks: 100%|██████████| 3/3 [00:00<00:00, 42.01it/s, # trackers=39]
Processed rules: 100%|██████████| 2/2 [00:00<00:00, 2304.56it/s, # trackers=1]
:task_name:dask:train_UnexpecTEDIntentPolicy2
Processed trackers: 100%|██████████| 120/120 [00:00<00:00, 2254.79it/s, # intent=12]
/home/azureuser/bot/Raysa-Rasa/rasa/utils/tensorflow/model_data_utils.py:384: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creatingthe ndarray
np.array(values), number_of_dimensions=4
/home/azureuser/bot/Raysa-Rasa/rasa/utils/tensorflow/model_data_utils.py:400: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creatingthe ndarray
MASK: [FeatureArray(np.array(attribute_masks), number_of_dimensions=3)]
2022-02-01 12:04:21.643372: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-02-01 12:04:21.643402: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-02-01 12:04:21.643427: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (masterVM): /proc/driver/nvidia/version does not exist
2022-02-01 12:04:21.643698: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Epochs:   0%|          | 0/100 [00:00<?, ?it/s]2022-02-01 12:04:22.018147: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/framework/indexed_slices.py:449: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradients/cond_grad/Identity_1:0", shape=(None,), dtype=int64), values=Tensor("gradients/cond_grad/Identity:0", shape=(None,), dtype=float32), dense_shape=Tensor("gradients/cond_grad/Identity_2:0", shape=(1,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
"shape. This may consume a large amount of memory." % value)
2022-02-01 12:04:24,490 ERROR worker.py:431 -- SystemExit was raised from the worker
Traceback (most recent call last):
File "python/ray/_raylet.pyx", line 759, in ray._raylet.task_execution_handler
File "python/ray/_raylet.pyx", line 580, in ray._raylet.execute_task
File "python/ray/_raylet.pyx", line 618, in ray._raylet.execute_task
File "python/ray/_raylet.pyx", line 625, in ray._raylet.execute_task
File "python/ray/_raylet.pyx", line 629, in ray._raylet.execute_task
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 350, in dask_task_wrapper
result = func(*actual_args)
File "/home/azureuser/bot/Raysa-Rasa/rasa/engine/graph.py", line 507, in __call__
output = self._fn(self._component, **run_kwargs)
File "/home/azureuser/bot/Raysa-Rasa/rasa/core/policies/ted_policy.py", line 714, in train
self.run_training(model_data, label_ids)
File "/home/azureuser/bot/Raysa-Rasa/rasa/core/policies/unexpected_intent_policy.py", line 484, in run_training
super().run_training(model_data, label_ids)
File "/home/azureuser/bot/Raysa-Rasa/rasa/core/policies/ted_policy.py", line 676, in run_training
shuffle=False,  # we use custom shuffle inside data generator
File "/home/azureuser/bot/Raysa-Rasa/rasa/utils/tensorflow/temp_keras_modules.py", line 181, in fit
tmp_logs = train_function(iterator)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
result = self._call(*args, **kwds)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
self._initialize(args, kwds, add_initializers_to=initializers)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 760, in _initialize
*args, **kwds))
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3066, in _get_concrete_function_internal_garbage_collected
graph_function, _ = self._maybe_define_function(args, kwargs)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3463, in _maybe_define_function
graph_function = self._create_graph_function(args, kwargs)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3308, in _create_graph_function
capture_by_value=self._capture_by_value),
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
func_outputs = python_func(*func_args, **func_kwargs)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 668, in wrapped_fn
out = weak_wrapped_fn().__wrapped__(*args, **kwds)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 990, in wrapper
user_requested=True,
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 444, in converted_call
result = converted_f(*effective_args, **kwargs)
File "/tmp/tmpnnfsk_80.py", line 15, in tf__train_function
retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 382, in converted_call
return _call_unconverted(f, args, kwargs, options)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 464, in _call_unconverted
return f(*args)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/keras/engine/training.py", line 842, in step_function
outputs = model.distribute_strategy.run(run_step, args=(data,))
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1286, in run
return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2849, in call_for_each_replica
return self._call_for_each_replica(fn, args, kwargs)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3632, in _call_for_each_replica
return fn(*args, **kwargs)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 692, in wrapper
return converted_call(f, args, kwargs, options=options)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 382, in converted_call
return _call_unconverted(f, args, kwargs, options)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 463, in _call_unconverted
return f(*args, **kwargs)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/keras/engine/training.py", line 835, in run_step
outputs = model.train_step(data)
File "/home/azureuser/bot/Raysa-Rasa/rasa/utils/tensorflow/models.py", line 143, in train_step
prediction_loss = self.batch_loss(batch_in)
File "/home/azureuser/bot/Raysa-Rasa/rasa/core/policies/ted_policy.py", line 1952, in batch_loss
tf_batch_data
File "/home/azureuser/bot/Raysa-Rasa/rasa/core/policies/ted_policy.py", line 1751, in _process_batch_data
) = self._encode_features_per_attribute(tf_batch_data, attribute)
File "/home/azureuser/bot/Raysa-Rasa/rasa/core/policies/ted_policy.py", line 1445, in _encode_features_per_attribute
lambda: self._encode_fake_features_per_attribute(tf_batch_data, attribute),
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
return target(*args, **kwargs)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1438, in cond_for_tf_v2
return cond(pred, true_fn=true_fn, false_fn=false_fn, strict=True, name=name)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
return target(*args, **kwargs)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 549, in new_func
return func(*args, **kwargs)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1254, in cond
return cond_v2.cond_v2(pred, true_fn, false_fn, name)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/ops/cond_v2.py", line 88, in cond_v2
op_return_value=pred)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
func_outputs = python_func(*func_args, **func_kwargs)
File "/home/azureuser/bot/Raysa-Rasa/rasa/core/policies/ted_policy.py", line 1444, in <lambda>
lambda: self._encode_real_features_per_attribute(tf_batch_data, attribute),
File "/home/azureuser/bot/Raysa-Rasa/rasa/core/policies/ted_policy.py", line 1655, in _encode_real_features_per_attribute
attribute_features, tf_batch_data, attribute
File "/home/azureuser/bot/Raysa-Rasa/rasa/core/policies/ted_policy.py", line 1716, in _convert_to_original_shape
attribute_mask, tf.sequence_mask(dialogue_lengths, dtype=tf.int32)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
return target(*args, **kwargs)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 4422, in sequence_mask
constant(0, maxlen.dtype), maxlen, constant(1, maxlen.dtype))
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 7370, in _range
"Range", start=start, limit=limit, delta=delta, name=name)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 377, in _apply_op_helper
with g.as_default(), ops.name_scope(name) as scope:
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/contextlib.py", line 112, in __enter__
return next(self.gen)
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 396, in inner_cm
(device_stack_has_callable(graph._device_function_stack) or
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1079, in device_stack_has_callable
for spec in device_stack.peek_objs())
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1078, in <genexpr>
return any(callable(spec._device_name_or_function)  # pylint: disable=protected-access
File "/home/azureuser/miniconda3/envs/raysa_env/lib/python3.7/site-packages/ray/worker.py", line 428, in sigterm_handler
sys.exit(1)
SystemExit: 1
Epochs:   0%|          | 0/100 [00:02<?, ?it/s]
```

### Versions / Dependencies

Ray 1.92 
Python 3.7.11
Ubuntu 20.04
rasa 3.05 (custom forked repository that includes Ray: [Raysa-Rasa](https://github.com/toza-mimoza/Raysa-Rasa/tree/RAYSA-2-ray-rasa-backend-features)

### Reproduction script

On the head node:
$ git clone https://github.com/toza-mimoza/Raysa-Rasa/tree/RAYSA-2-ray-rasa-backend-features
$ poetry build 
$ rasa init (in for example 'bot' folder in the repository)
$ cd bot/
$ ray start --head (outputs for example address 10.2.0.4:6379)

On each worker node: 
$ ray start --address='10.2.0.4:6379' --redis-password='5241590000000000'

On the head node again:
$ NUMEXPR_MAX_THREADS=16 RASA_MAX_CACHE_SIZE=0 rasa train

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by toza-mimoza** [comment]
Never mind, this was not Ray problem.
