### ISSUE TITLE
[Bug] Support cgroup2 in agent.py

### ISSUE THREAD

**Issue by chenk008** [ray-project/ray#22051]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Dashboard

### What happened + What you expected to happen

I deploy raycluster in a K8s cluster with cgroup2, the raylet.err show this error message:
```
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/logging/handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "/home/ray/anaconda3/lib/python3.7/logging/handlers.py", line 185, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/home/ray/anaconda3/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/home/ray/anaconda3/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/home/ray/anaconda3/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/agent.py", line 376, in <module>
    loop.run_until_complete(agent.run())
  File "/home/ray/anaconda3/lib/python3.7/asyncio/base_events.py", line 574, in run_until_complete
    self.run_forever()
  File "/home/ray/anaconda3/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/home/ray/anaconda3/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
    handle._run()
  File "/home/ray/anaconda3/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 554, in run
    await self._perform_iteration(aioredis_client)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 539, in _perform_iteration
    stats = self._get_all_stats()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 334, in _get_all_stats
    "cpu": self._get_cpu_percent(),
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 193, in _get_cpu_percent
    return k8s_utils.cpu_percent()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/k8s_utils.py", line 57, in cpu_percent
    logger.exception("Error computing CPU usage of Ray Kubernetes pod.", e)
Message: 'Error computing CPU usage of Ray Kubernetes pod.'
Arguments: (FileNotFoundError(2, 'No such file or directory'),)
```

### Versions / Dependencies

docker.io/rayproject/ray:latest

### Reproduction script

Use helm in kuberay:
```
helm install my-release . --values values.yaml --namespace ray-system --create-namespace
```

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by wilsonwang371** [comment]
I can also observe this in ray cluster created in kuberay deployed in Kind environment.

**Comment by wilsonwang371** [comment]
Is this related to kernel config? @chenk008  CONFIG_CGROUP_CPUACCT

**Comment by mimoralea** [comment]
Good read on cgroup v2 adoption: https://medium.com/nttlabs/cgroup-v2-596d035be4d7.

Also, this seems resolved in master: https://github.com/ray-project/ray/blob/master/dashboard/k8s_utils.py#L7-L8

However, using the `latest` container "The most recent Ray release" as of today is not enough: https://github.com/ray-project/ray/tree/master/docker/ray

A workaround:
1. Update the pods to use the nightly image:
```
helm -n ray upgrade --install example-cluster --create-namespace ./ray --set image=rayproject/ray:nightly
```
2. Update your local installation:
```
pip uninstall -y ray
pip install -U 'ray[default] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl'
```
3. Run your script again:
```
python ray/doc/kubernetes/example_scripts/run_local_example.py
```
