### ISSUE TITLE
[Bug] Python: --extra-index-url does not work in requirements file anymore

### ISSUE THREAD

**Issue by iconix** [ray-project/ray#22056]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Up until Ray 1.9.0, I could provide a call to `ray.init(address=head_address, runtime_env={'pip': requirements_file})` with a `requirements_file` that preprended the line `--extra-index-url INDEX` within the file to provide an alternative index (see https://stackoverflow.com/a/2477610)

Starting with Ray 1.10.0, I am now getting an error:
```
Traceback (most recent call last):
  File "/opt/launch_summit", line 56, in <module>
    ray.init(address=head_address, runtime_env={'pip': req_path})
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/worker.py", line 977, in init
    connect(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/worker.py", line 1523, in connect
    serialized_job_config = job_config.serialize()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/job_config.py", line 51, in serialize
    return self.get_proto_job_config().SerializeToString()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/job_config.py", line 108, in get_proto_job_config
    parsed_env, eager_install = self._validate_runtime_env()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/job_config.py", line 92, in _validate_runtime_env
    return ParsedRuntimeEnv(self.runtime_env), eager_install
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/runtime_env/validation.py", line 345, in __init__
    validated_option_val = validate_fn(option_val)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/runtime_env/validation.py", line 179, in parse_and_validate_pip
    result = _rewrite_pip_list_ray_libraries(pip_list)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/runtime_env/validation.py", line 115, in _rewrite_pip_list_ray_libraries
    requirement = Requirement.parse(specifier)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3139, in parse
    req, = parse_requirements(s)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3084, in parse_requirements
    yield Requirement(line)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3094, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 100, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'--extra-'": Expected W:(abcd...) 
```

Any ideas on what has changed and how I can get this behavior back on the latest Ray?

### Versions / Dependencies

Python 3.8.6
Ray 1.10.0 or higher
Ubuntu 18.04.5 LTS

### Reproduction script

requirements.txt:
```
--extra-index-url PRIVATE_PACKAGE_INDEX
private-package==1.0.0
```

script.py
```
import ray
ray.init(runtime_env={'pip': 'requirements.txt'})
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment]
@iconix Thanks for making the issue and for including the reproduction!  As a workaround before the fix is merged, you can still use `--extra-index-url` in the `conda` field of runtime_env.

E.g.
```
pip_list = [
            "--extra-index-url https://pypi.org/simple",
            "pip-install-test==0.5",
        ]
conda_dict = {"dependencies": ["pip", {"pip": pip_list}]}
runtime_env = {"conda": conda_dict}
```
This also works if you save the `conda_dict` as an `environment.yml` file as in https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually
