### ISSUE TITLE
How to use external class in Actor?

### ISSUE THREAD

**Issue by cklsoft** [ray-project/ray#2212]
### Describe the problem
I code a actor A which depend module B , but the code of B (B.py) is only located in the machine where the driver running. When I run the actor A, some exceptions raising for not found module B.
Dispatch all the depend resources of A to all machines may solve the problem? Any other solutions?
Any examples for this solutions in the ray source code?

Below is a example:
### Source code / logs

1. test1.py:

import ray
@ray.remote
def add(a,b):
	return a+b

2. test2.py

import ray
import test1

@ray.remote
def add2(a,b):
	return test1.add.remote(a,b)+b

if __name__ == '__main__':
	ray.init(redis_address='...:8001')
	print ray.get(add2.remote(1,3))

3. error log

Traceback (most recent call last):
  File "test2.py", line 10, in <module>
    print ray.get(add2.remote(1,3))
  File "/home/yiguang.wyg/tools/anaconda2/lib/python2.7/site-packages/ray/worker.py", line 2321, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(f2c311c32129093568d347f0b20dbd08797bd45f). It was created by remote function __main__.add2 which failed with:

Remote function __main__.add2 failed with:

Traceback (most recent call last):
  File "test2.py", line 6, in add2
    return test1.add.remote(a,b)+b
TypeError: unsupported operand type(s) for +: 'common.ObjectID' and 'int'

Traceback (most recent call last):
  File "/home/yiguang.wyg/tools/anaconda2/lib/python2.7/site-packages/ray/worker.py", line 1686, in fetch_and_register_remote_function
    function = pickle.loads(serialized_function)
  File "/home/yiguang.wyg/tools/anaconda2/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/home/yiguang.wyg/tools/anaconda2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/yiguang.wyg/tools/anaconda2/lib/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
  File "/home/yiguang.wyg/tools/anaconda2/lib/python2.7/site-packages/ray/cloudpickle/cloudpickle.py", line 894, in subimport
    __import__(name)
ImportError: No module named test1

**Comment by robertnishihara** [comment]
In this case, you need the files `test1.py` and `test2.py` to be on all of the machines. You can often avoid this if you just have a single file instead of two files.

**Comment by cklsoft** [comment]
@robertnishihara  Auto import the relate resources will be elegance : )

**Comment by DuaneNielsen** [comment]
Realize this is closed but...

I do hope "put all your project into a single file" is not the final solution to this problem.  In any non-trivial project you do kinda need to run stuff in more than one file.

**Comment by robertnishihara** [comment]
@DuaneNielsen right, using one file is just a quick workaround. Non-trivial projects should be Python modules that are installed on all of the machines so that the code is already available.

**Comment by hkvision** [comment]
Wondering if there any more elegant solution for this issue?
