### ISSUE TITLE
No module named 'ray.core.src.local_scheduler.liblocal_scheduler_library_python'

### ISSUE THREAD

**Issue by nskplta** [ray-project/ray#2216]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 17.10 (Google Colaboratory)
- **Ray installed from (source or binary)**: apt-get install 'ray[rllib]'
- **Ray version**: 
- **Python version**: 3.6
- **Exact command to reproduce**:

### Describe the problem
When running `train.py` error message arises: `ModuleNotFoundError: No module named 'ray.core.src.local_scheduler.liblocal_scheduler_library_python'`. Cannot find this module in the github repo. Also tried with the wheel but installed 0.4.0 version. How can I solve it? Thanks!

**Comment by richardliaw** [comment]
Thanks for posting! Can you post an error log? Would be nice to see where this shows up. I couldn't get `rllib` to install on Colab, but Ray worked (the ALE failed to build).

**Comment by robertnishihara** [comment]
Can you try to install Ray with `pip install ray[rllib]`? Or even just `pip install ray`?

**Comment by nskplta** [comment]
Hi @robertnishihara , tried both `pip install ray `and building ray from source, with `cd ray/python; pip install -e . --verbose` and `ModuleNotFoundError: No module named 'ray.core.src.local_scheduler.liblocal_scheduler_library_python'` still remains

**Comment by richardliaw** [comment]
Can you do the following:

1. repeat `pip uninstall ray` and `apt-get uninstall ray` until `which -a
ray` doesn't return anything
2. Then try ONLY `cd ray/python; pip install -e . --verbose`?

Let me know what happens.

**Comment by nskplta** [comment]
Hi @richardliaw , installation shows error:
```
[...]
+ pushd /content/ray/thirdparty/scripts/..//pkg/redis
    ~/ray/thirdparty/pkg/redis ~/ray/python
    + make
    cd src && make all
    make[1]: Entering directory '/content/ray/thirdparty/pkg/redis/src'
        CC adlist.o
    In file included from adlist.c:34:0:
    zmalloc.h:50:10: fatal error: jemalloc/jemalloc.h: No such file or directory
     #include <jemalloc/jemalloc.h>
              ^~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    Makefile:213: recipe for target 'adlist.o' failed
    make[1]: *** [adlist.o] Error 1
    make[1]: Leaving directory '/content/ray/thirdparty/pkg/redis/src'
    Makefile:6: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/content/ray/python/setup.py", line 155, in <module>
        license="Apache 2.0")
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/content/ray/python/setup.py", line 80, in run
        subprocess.check_call(["../build.sh", "-p", sys.executable])
      File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '-p', '/usr/bin/python3']' returned non-zero exit status 2.
Cleaning up...
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/content/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /content/ray/python/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 738, in install
    install_options, global_options, prefix=prefix,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 900, in install_editable
    show_stdout=False,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/content/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /content/ray/python/
```
With `!pip install ray` installation succeeds but `ModuleNotFoundError: No module named 'ray.core.src.local_scheduler.liblocal_scheduler_library_python'` remains.

Thanks

**Comment by robertnishihara** [comment]
As Richard mentioned, fully remove all traces of the version of Ray that you installed from source (e.g., do `pip uninstall ray` multiple times, and `rm -rf` the `ray/` directory.

Then try `pip install ray` and it should work.
