### ISSUE TITLE
[Bug] [RLLIB] APEX-DDPG crashes if using multiple gpus

### ISSUE THREAD

**Issue by Mathieu-Prouveur** [ray-project/ray#22179]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

I tried out the torch implementation of APEX-DDPG with multiple gpus but it crashes.

### Versions / Dependencies

ray 1.10.0

### Reproduction script

I tried running the following config (same as the one in tuned examples but with torch and 2 gpus) using `rllib train -f xxx.yaml` : 

```yaml
mountaincarcontinuous-apex-ddpg:
    env: MountainCarContinuous-v0
    run: APEX_DDPG
    stop:
        episode_reward_mean: 90
    config:
        # Works for both torch and tf.
        framework: torch
        clip_rewards: False
        num_gpus: 2
        num_workers: 16
        exploration_config:
            ou_base_scale: 1.0
        n_step: 3
        target_network_update_freq: 50000
        tau: 1.0
        evaluation_interval: 5
        evaluation_num_episodes: 10
```

### Anything else

The error below is systematic. I can run the Impala multi-gpu config just fine (https://github.com/ray-project/ray/blob/master/rllib/tuned_examples/impala/atari-impala-multi-gpu.yaml), so that shouldn't be hardware related.

Here is the error : 

```python
2022-02-07 17:10:29,203 ERROR trial_runner.py:927 -- Trial APEX_DDPG_MountainCarContinuous-v0_7075d_00000: Error processing event.
Traceback (most recent call last):
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 893, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 707, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/worker.py", line 1733, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::ApexDDPGTrainer.train() (pid=941158, ip=192.168.251.123, repr=ApexDDPGTrainer)
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/tune/trainable.py", line 315, in train
    result = self.step()
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 982, in step
    raise e
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 963, in step
    step_attempt_results = self.step_attempt()
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 1042, in step_attempt
    step_results = self._exec_plan_or_training_iteration_fn()
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 1962, in _exec_plan_or_training_iteration_fn
    results = next(self.train_exec_impl)
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/util/iter.py", line 1075, in build_union
    item = next(it)
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/rllib/execution/concurrency_ops.py", line 135, in base_iterator
    raise RuntimeError("Dequeue `check()` returned False! "
RuntimeError: Dequeue `check()` returned False! Exiting with Exception from Dequeue iterator.
== Status ==
Current time: 2022-02-07 17:10:29 (running for 00:00:12.37)
Memory usage on this node: 43.3/125.7 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/64 CPUs, 0/2 GPUs, 0.0/56.88 GiB heap, 0.0/28.37 GiB objects (0.0/1.0 accelerator_type:G)
Result logdir: /home/delfox/ray_results/mountaincarcontinuous-apex-ddpg
Number of trials: 1/1 (1 ERROR)
+------------------------------------------------+----------+------------------------+
| Trial name                                     | status   | loc                    |
|------------------------------------------------+----------+------------------------|
| APEX_DDPG_MountainCarContinuous-v0_7075d_00000 | ERROR    | 192.168.251.123:941158 |
+------------------------------------------------+----------+------------------------+
Number of errored trials: 1
+------------------------------------------------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| Trial name                                     |   # failures | error file                                                                                                                              |
|------------------------------------------------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------|
| APEX_DDPG_MountainCarContinuous-v0_7075d_00000 |            1 | /home/delfox/ray_results/mountaincarcontinuous-apex-ddpg/APEX_DDPG_MountainCarContinuous-v0_7075d_00000_0_2022-02-07_17-10-16/error.txt |
+------------------------------------------------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------+

Traceback (most recent call last):
  File "/home/delfox/.opt/miniconda3/envs/swarm/bin/rllib", line 8, in <module>
    sys.exit(cli())
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/rllib/scripts.py", line 36, in cli
    train.run(options, train_parser)
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/rllib/train.py", line 267, in run
    concurrent=True)
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/tune/tune.py", line 739, in run_experiments
    callbacks=callbacks).trials
  File "/home/delfox/.opt/miniconda3/envs/swarm/lib/python3.7/site-packages/ray/tune/tune.py", line 630, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [APEX_DDPG_MountainCarContinuous-v0_7075d_00000])
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sven1977** [comment]
Hey @Mathieu-Prouveur , yeah, I think our APEX algos (DQN and DDPG) do NOT support multi-GPUs yet. Let me take a look ...
