### ISSUE TITLE
Resnet example with redis-address raise ImportError, without redis-address is ok

### ISSUE THREAD

**Issue by 0freeday** [ray-project/ray#2217]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu14.04
- **Ray installed from (source or binary)**:
- **Ray version**:0.4.0
- **Python version**:2.7.12
- **Exact command to reproduce**:

### Describe the problem

If I run the Resnet example without redis-address it works, but when I add the redis-address 
,it raise exception like follows. I have try to add sys.path at the top of the script, but it doesn't work.

m1@m1:~/resnet$ **python resnet_main.py --redis-address=10.31.22.111:12300**
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 1686, in fetch_and_register_remote_function
    function = pickle.loads(serialized_function)
  File "/usr/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/ray/cloudpickle/cloudpickle.py", line 894, in subimport
    __import__(name)
**ImportError: No module named cifar_input**

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="10.31.22.111:12300")

Remote function __main__.get_data failed with:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 1678, in <lambda>
    remote_f_placeholder = remote(function_id=function_id)(lambda *xs: f())
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 1677, in f
    raise Exception("This function was not imported properly.")
Exception: This function was not imported properly.

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="10.31.22.111:12300")

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ray/actor.py", line 284, in fetch_and_register_actor
    unpickled_class = pickle.loads(pickled_class)
  File "/usr/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/ray/cloudpickle/cloudpickle.py", line 894, in subimport
    __import__(name)
**ImportError: No module named resnet_model**

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="10.31.22.111:12300")

Remote function __init__ failed with:

Failed to get objectid ObjectID(eeb4a72f9f911a6e3b4163229b9a3720478a2f43) as argument 0 for remote function __init__. It was created by remote function __main__.get_data which failed with:
Remote function __main__.get_data failed with:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 1678, in <lambda>
    remote_f_placeholder = remote(function_id=function_id)(lambda *xs: f())
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 1677, in f
    raise Exception("This function was not imported properly.")
Exception: This function was not imported properly.

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="10.31.22.111:12300")

Remote function get_ip_addr failed with:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 821, in _process_task
    *arguments)
  File "/usr/local/lib/python2.7/dist-packages/ray/actor.py", line 212, in actor_method_executor
    method_returns = method(actor, *args)
  File "/usr/local/lib/python2.7/dist-packages/ray/actor.py", line 267, in temporary_actor_method
    "cannot execute this method".format(actor_name))
Exception: The actor with name ResNetTestActor failed to be imported, and so cannot execute this method

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="10.31.22.111:12300")

Traceback (most recent call last):
  File "resnet_main.py", line 244, in <module>
    train()
  File "resnet_main.py", line 215, in train
    .format(ray.get(test_actor.get_ip_addr.remote())))
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 2321, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(f792bc942e55e4ec82f0d00c1dba6258dc8628b2). It was created by remote function get_ip_addr which failed with:

Remote function get_ip_addr failed with:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 821, in _process_task
    *arguments)
  File "/usr/local/lib/python2.7/dist-packages/ray/actor.py", line 212, in actor_method_executor
    method_returns = method(actor, *args)
  File "/usr/local/lib/python2.7/dist-packages/ray/actor.py", line 267, in temporary_actor_method
    "cannot execute this method".format(actor_name))
Exception: The actor with name ResNetTestActor failed to be imported, and so cannot execute this method

**Comment by DoraYh** [comment]
I also meet this problem，how do you deal with it？
