### ISSUE TITLE
[Datasets] [Bug] Casting boolean tensor columns fails.

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#22190]
Casting boolean tensor columns fails.

## Reproduction

```python
import pandas as pd
import ray
from ray.data.extensions import TensorDtype

ray.init()

df = pd.DataFrame({"test": [[False, True, True], [True, False, True], [False, False, True]]})
data = ray.data.from_pandas(df)


def to_tensors(df: pd.DataFrame) -> pd.DataFrame:
    for c in df.columns:
        df[c] = df[c].astype(TensorDtype())
    return df


def batch_predict(df: pd.DataFrame) -> pd.DataFrame:
    return df
    

dask_dataset = (
    data
    .map_batches(to_tensors, batch_format="pandas")
    .map_batches(
        batch_predict, batch_size=32, compute="actors", batch_format="pandas", num_gpus=0
    )
    .to_dask()
)
```

```
Traceback (most recent call last):
  File "/home/runner/work/ludwig/ludwig/tests/integration_tests/utils.py", line 388, in _subproc_wrapper
    results = fn(*args, **kwargs)
  File "/home/runner/work/ludwig/ludwig/tests/integration_tests/test_ray.py", line 163, in run_test_parquet
    run_fn(config, data_parquet=dataset_parquet)
  File "/home/runner/work/ludwig/ludwig/tests/integration_tests/test_ray.py", line 90, in run_api_experiment
    model = train_with_backend(RAY_BACKEND_CONFIG, config, dataset=data_parquet, evaluate=False)
  File "/home/runner/work/ludwig/ludwig/tests/integration_tests/utils.py", line 584, in train_with_backend
    preds, _ = model.predict(dataset=dataset)
  File "/home/runner/work/ludwig/ludwig/ludwig/api.py", line 733, in predict
    dataset,
  File "/home/runner/work/ludwig/ludwig/ludwig/backend/ray.py", line 372, in batch_predict
    batch_predictor, batch_size=self.batch_size, compute="actors", batch_format="pandas", num_gpus=num_gpus
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/ray/data/dataset.py", line 2102, in to_dask
    [block_to_df(block) for block in self._blocks.get_blocks()])
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/dask/dataframe/io/io.py", line 603, in from_delayed
    meta = delayed(make_meta)(dfs[0]).compute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/dask/base.py", line 288, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/dask/base.py", line 571, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 182, in ray_dask_get
    result = ray_get_unpack(object_refs, progress_bar_actor=pb_actor)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 475, in ray_get_unpack
    computed_result = get_result(object_refs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 463, in get_result
    return ray.get(object_refs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/ray/worker.py", line 1733, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::dask:make_meta-8995e377-1477-486f-ad23-d540195fed5f (pid=9584, ip=10.1.0.58)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::dask:block_to_df-a28301f2-a543-41fc-8755-ad04e9e205bc (pid=9584, ip=10.1.0.58)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::BlockWorker.map_block_nosplit() (pid=9764, ip=10.1.0.58, repr=<ray.data.impl.compute.BlockWorker object at 0x7f20dcd2c390>)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/ray/data/impl/compute.py", line 138, in map_block_nosplit
    return _map_block_nosplit(block, fn, input_files)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/ray/data/impl/compute.py", line 46, in _map_block_nosplit
    for new_block in fn(block):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/ray/data/dataset.py", line 224, in transform
    view = BlockAccessor.for_block(view).to_pandas()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/ray/data/impl/arrow_block.py", line 90, in to_pandas
    return self._table.to_pandas()
  File "pyarrow/array.pxi", line 767, in pyarrow.lib._PandasConvertible.to_pandas
  File "pyarrow/table.pxi", line 1996, in pyarrow.lib.Table._to_pandas
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 789, in table_to_blockmanager
    blocks = _table_to_blocks(options, table, categories, ext_columns_dtypes)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 1138, in _table_to_blocks
    for item in result]
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 1138, in <listcomp>
for item in result]
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 749, in _reconstruct_block
    pd_ext_arr = pandas_dtype.__from_arrow__(arr)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/ray/data/extensions/tensor_extension.py", line 262, in __from_arrow__
    values = array.chunk(0).to_numpy()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/ray/data/extensions/tensor_extension.py", line 1331, in to_numpy
    return self._to_numpy(zero_copy_only=zero_copy_only)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/ray/data/extensions/tensor_extension.py", line 1315, in _to_numpy
    shape, dtype=ext_dtype, buffer=data_buffer, offset=offset)
TypeError: buffer is too small for requested array
```

**Comment by clarkzinzow** [comment]
@tgaddair Just checked, I'm able to reproduce on `ray==1.10.0`, but the latest Ray nightly wheel appears to handle this correctly.
```
ubuntu@ip-172-31-46-244:(ws)/ray $ ipython
Python 3.7.10 (default, Feb 20 2021, 21:15:28)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pandas as pd
   ...: import ray
   ...: from ray.data.extensions import TensorDtype
   ...: from ray.util.dask import ray_dask_get
   ...:
   ...: ray.init()
   ...:
   ...: df = pd.DataFrame({"test": [[False, True, True], [True, False, True], [False, False, True]]})
   ...: data = ray.data.from_pandas(df)
   ...:
   ...:
   ...: def to_tensors(df: pd.DataFrame) -> pd.DataFrame:
   ...:     for c in df.columns:
   ...:         df[c] = df[c].astype(TensorDtype())
   ...:     return df
   ...:
   ...:
   ...: def batch_predict(df: pd.DataFrame) -> pd.DataFrame:
   ...:     return df
   ...:
   ...:
   ...: dask_dataset = (
   ...:     data
   ...:     .map_batches(to_tensors, batch_format="pandas")
   ...:     .map_batches(
   ...:         batch_predict, batch_size=32, compute="actors", batch_format="pandas", num_gpus=0
   ...:     )
   ...:     .to_dask()
   ...: )
Map Progress: 100%|█████| 1/1 [00:00<00:00, 43.57it/s]
Map Progress: 100%|█████| 1/1 [00:00<00:00, 29.01it/s]

In [2]: dask_dataset.compute(scheduler=ray_dask_get)
Out[2]:
                   test
0   [False, True, True]
1   [True, False, True]
2  [False, False, True]
```

Could you try the latest nightly wheel?

**Comment by tgaddair** [comment]
Yep, looks good. Any chance y'all can create a 1.10.1 patch release?

**Comment by clarkzinzow** [comment]
Hey @tgaddair, it looks like we'll be able to get this into the 1.11 release, which should have a release candidate package out later today that you can try out, with the 1.11 release itself coming out early this week!
