### ISSUE TITLE
Error message in TensorFlow tests.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#222]
The following message is printed at the end of the tensorflow tests. It also comes up in other places (as in the LBFGS example). In the past, I have seen this come up when using tensorflow in situations where two Python modules mutually import each other.

```
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x111829358>>
Traceback (most recent call last):
  File "/Users/rkn/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 581, in __del__
UnboundLocalError: local variable 'status' referenced before assignment
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x111911048>>
Traceback (most recent call last):
  File "/Users/rkn/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 581, in __del__
UnboundLocalError: local variable 'status' referenced before assignment
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x111867358>>
Traceback (most recent call last):
  File "/Users/rkn/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 581, in __del__
UnboundLocalError: local variable 'status' referenced before assignment
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x111852278>>
Traceback (most recent call last):
  File "/Users/rkn/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 581, in __del__
UnboundLocalError: local variable 'status' referenced before assignment
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x111881c50>>
Traceback (most recent call last):
  File "/Users/rkn/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 581, in __del__
UnboundLocalError: local variable 'status' referenced before assignment
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x111956e48>>
Traceback (most recent call last):
  File "/Users/rkn/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 581, in __del__
UnboundLocalError: local variable 'status' referenced before assignment
```

**Comment by robertnishihara** [comment]
Closing because I don't see this anymore.
