### ISSUE TITLE
[Bug] InvalidAMIID.NotFound when no AMI specified in non us-west-2 AZs

### ISSUE THREAD

**Issue by ckw017** [ray-project/ray#22262]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

Looks like trying we're trying to use the us-west-2 deep learning AMI (`ami-0a2363a9cff180a64`) by default, even in different availability zones.

It looks like we do have the default AMI's for other AZs here https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/_private/aws/config.py#L39-L50

### Versions / Dependencies

ray 1.10, python 3.8.12

### Reproduction script

config.yaml:
```yaml
# An unique identifier for the head node and workers of this cluster.
cluster_name: minimal

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-1
```

`ray cluster up -y config.yaml`

```
Cluster: minimal

2022-02-09 15:37:31,566	INFO util.py:282 -- setting max workers for head node type to 0
2022-02-09 15:37:31,566	INFO util.py:286 -- setting max workers for ray.worker.default to 2
Checking AWS environment settings
AWS config
  IAM Profile: ray-autoscaler-v1 [default]
  EC2 Key pair (all available node types): ray-autoscaler_us-west-1 [default]
  VPC Subnets (all available node types): subnet-8610b9e0, subnet-9435f0ce [default]
  EC2 Security groups (all available node types): sg-085ac69229ef344eb [default]
  EC2 AMI (all available node types): ami-0a2363a9cff180a64

No head node found. Launching a new cluster. Confirm [y/N]: y [automatic, due to --yes]

Acquiring an up-to-date head node
  create_instances: Attempt failed with An error occurred (InvalidAMIID.NotFound) when calling the RunInstances operation: The image id '[ami-0a2363a9cff180a64]' does not exist, retrying.
  create_instances: Attempt failed with An error occurred (InvalidAMIID.NotFound) when calling the RunInstances operation: The image id '[ami-0a2363a9cff180a64]' does not exist, retrying.
  create_instances: Attempt failed with An error occurred (InvalidAMIID.NotFound) when calling the RunInstances operation: The image id '[ami-0a2363a9cff180a64]' does not exist, retrying.
  create_instances: Attempt failed with An error occurred (InvalidAMIID.NotFound) when calling the RunInstances operation: The image id '[ami-0a2363a9cff180a64]' does not exist, retrying.
  Failed to launch instances. Max attempts exceeded.
Traceback (most recent call last):
  File "/Users/cwong/anaconda3/envs/ray110/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1938, in main
    return cli()
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/ray/autoscaler/_private/cli_logger.py", line 808, in wrapper
    return f(*args, **kwargs)
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/ray/scripts/scripts.py", line 941, in up
    create_or_update_cluster(
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 236, in create_or_update_cluster
    get_or_create_head_node(config, config_file, no_restart, restart_only, yes,
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 635, in get_or_create_head_node
    provider.create_node(head_node_config, head_node_tags, 1)
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/ray/autoscaler/_private/aws/node_provider.py", line 310, in create_node
    created_nodes_dict = self._create_node(node_config, tags, count)
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/ray/autoscaler/_private/aws/node_provider.py", line 437, in _create_node
    cli_logger.abort(
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/ray/autoscaler/_private/cli_logger.py", line 605, in abort
    raise exc
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/ray/autoscaler/_private/aws/node_provider.py", line 408, in _create_node
    created = self.ec2_fail_fast.create_instances(**conf)
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/cwong/anaconda3/envs/ray110/lib/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAMIID.NotFound) when calling the RunInstances operation: The image id '[ami-0a2363a9cff180a64]' does not exist
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ckw017** [comment]
@DmitriGekhtman feel free to reassign if you don't have the bandwidth. I'm guessing this is a regression since we have the AMIs for other regions already, in which case I can look into instead (suspect this might be related to when we shifted to available_node_types)

**Comment by DmitriGekhtman** [comment]
I can look into it next week.

**Comment by DmitriGekhtman** [comment]
Or rather, one of 
me, you, @wuisawesome 
can claim it for doing in the next two-week cycle.

**Comment by worldveil** [comment]
Hey, just to add onto this issue, the same problem arises for defaults in other places. 

Both

- provider.availiability_zone
- available_node_types.ray.worker.default.node_config.ImageId

Also default to things in us-west-2. 

For example, if do something like this:

```yaml
provider:
    type: aws
    region: us-east-2
    cache_stopped_nodes: True # If not present, the default is True.
```

the `availability_zone` will also default to `us-west-2`!

**Comment by worldveil** [comment]
Just checking back here, can we fix this?

**Comment by ckw017** [comment]
Taking a look, shouldn't be too bad to fix

**Comment by ckw017** [comment]
@worldveil ImageId should be fixed with #22506, what are the symptoms you're spotting with availability zones? Looks like those don't get populated from defaults

**Comment by ckw017** [comment]
Closing this since original bug is fixed, feel free to open a new issue if it seems separate
