### ISSUE TITLE
[serve] Error calling serve.start(detached=True) on a local ray cluster

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#22265]
Repro:
`ray start --head`

Then run:
```python
import ray
ray.init(address='auto')

from ray import serve

serve.start(detached=True)

@serve.deployment(route_prefix="/hi")
def f(): pass

f.deploy()
```

Spits out errors:
```
(HTTPProxyActor pid=39296) INFO:     Started server process [39296]
(HTTPProxyActor pid=39296) Exception in callback <function LongPollClient._process_update.<locals>.chained at 0x7fc7f62e0670>
(HTTPProxyActor pid=39296) handle: <Handle LongPollClient._process_update.<locals>.chained>
(HTTPProxyActor pid=39296) Traceback (most recent call last):
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 682, in _connect
(HTTPProxyActor pid=39296)     controller = ray.get_actor(controller_name, namespace=controller_namespace)
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/_private/client_mode_hook.py", line 105, in wrapper
(HTTPProxyActor pid=39296)     return func(*args, **kwargs)
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/worker.py", line 2152, in get_actor
(HTTPProxyActor pid=39296)     return worker.core_worker.get_named_actor_handle(name, namespace or "")
(HTTPProxyActor pid=39296)   File "python/ray/_raylet.pyx", line 1877, in ray._raylet.CoreWorker.get_named_actor_handle
(HTTPProxyActor pid=39296)     check_status(named_actor_handle_pair.second)
(HTTPProxyActor pid=39296)   File "python/ray/_raylet.pyx", line 173, in ray._raylet.check_status
(HTTPProxyActor pid=39296)     raise ValueError(message)
(HTTPProxyActor pid=39296) ValueError: Failed to look up actor with name 'SERVE_CONTROLLER_ACTOR'. This could because 1. You are trying to look up a named actor you didn't create. 2. The named actor died. 3. You did not use a namespace matching the namespace of the actor.
(HTTPProxyActor pid=39296)
(HTTPProxyActor pid=39296) During handling of the above exception, another exception occurred:
(HTTPProxyActor pid=39296)
(HTTPProxyActor pid=39296) Traceback (most recent call last):
(HTTPProxyActor pid=39296)   File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/serve/long_poll.py", line 158, in chained
(HTTPProxyActor pid=39296)     callback(arg)
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/serve/http_proxy.py", line 237, in _update_routes
(HTTPProxyActor pid=39296)     self.prefix_router.update_routes(endpoints)
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/serve/http_proxy.py", line 133, in update_routes
(HTTPProxyActor pid=39296)     self.handles[endpoint] = self._get_handle(endpoint)
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/serve/http_proxy.py", line 196, in get_handle
(HTTPProxyActor pid=39296)     return serve.api._get_global_client().get_handle(
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 75, in _get_global_client
(HTTPProxyActor pid=39296)     return _connect()
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 684, in _connect
(HTTPProxyActor pid=39296)     raise RayServeException(
(HTTPProxyActor pid=39296) ray.serve.exceptions.RayServeException: There is no instance running on this Ray cluster. Please call `serve.start(detached=True) to start one.
```

Calling the HTTP endpoint also fails.

**Comment by edoakes** [comment]
@architkulkarni could you please try repro'ing on your setup? This one is so bad that it seems like I must be missing something. If you can repro, it's a P0 (I can take it)

**Comment by shrekris-anyscale** [comment]
This works on my end if you do `ray.init(address="auto")` after doing the `from ray import serve`.

**Comment by architkulkarni** [comment]
@edoakes I also repro'd this on the latest master

**Comment by simon-mo** [comment]
can repro it on 1.10

**Comment by simon-mo** [comment]
ah i think this relates to namespace issue
