### ISSUE TITLE
[nightly] node_failures failed

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#22319]
It's related to redisless flag being turned on. 

```
Iteration 999:
  - Iteration time: 2.418158531188965.
  - Absolute time: 1644570204.7196364.
  - Total elapsed time: 8090.201013803482.
2022-02-11 09:03:42,300 ERROR utils.py:1208 -- Internal KV Get failed
Traceback (most recent call last):
  File "/mnt/yic/ray/python/ray/_private/utils.py", line 1206, in internal_kv_get_with_retry
    result = gcs_client.internal_kv_get(key, namespace)
  File "/mnt/yic/ray/python/ray/_private/gcs_utils.py", line 146, in wrapper
    return f(self, *args, **kwargs)
  File "/mnt/yic/ray/python/ray/_private/gcs_utils.py", line 230, in internal_kv_get
    reply = self._kv_stub.InternalKVGet(req)
  File "/mnt/yic/miniconda3/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/mnt/yic/miniconda3/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1644570222.300159531","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3093,"referenced_errors":[{"created":"@1644570222.300158761","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
```

**Comment by iycheng** [comment]
```
terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call
*** SIGABRT received at time=1644570206 on cpu 12 ***
PC: @     0x7f8d2f3dffb7  (unknown)  raise
    @     0x7f8d3036f980  (unknown)  (unknown)
[2022-02-11 09:03:26,427 E 30905 30905] (gcs_server) logging.cc:321: *** SIGABRT received at time=1644570206 on cpu 12 ***
[2022-02-11 09:03:26,427 E 30905 30905] (gcs_server) logging.cc:321: PC: @     0x7f8d2f3dffb7  (unknown)  raise
[2022-02-11 09:03:26,427 E 30905 30905] (gcs_server) logging.cc:321:     @     0x7f8d3036f980  (unknown)  (unknown)
```

It seems like a race condition in gcs.

**Comment by wjrforcyber** [comment]
I am still seeing this with python 3.9.1 and ray 1.13.0, btw:
macOs Monterey, version 12.5
chip Apple M2
Memory 24 GB
My error message:
```
2022-10-20 15:17:22,458 ERROR utils.py:1249 -- Internal KV Get failed
Traceback (most recent call last):
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/venv/lib/python3.9/site-packages/ray/_private/utils.py", line 1236, in internal_kv_get_with_retry
    result = gcs_client.internal_kv_get(key, namespace)
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/venv/lib/python3.9/site-packages/ray/_private/gcs_utils.py", line 137, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/venv/lib/python3.9/site-packages/ray/_private/gcs_utils.py", line 209, in internal_kv_get
    reply = self._kv_stub.InternalKVGet(req)
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/venv/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/jingrenwang/Github/EDA/Project/eda-flow-python/venv/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "Method not found!"
        debug_error_string = "{"created":"@1666250242.458824000","description":"Error received from peer ipv4:127.0.0.1:10001","file":"src/core/lib/surface/call.cc","file_line":1075,"grpc_message":"Method not found!","grpc_status":12}"
>
```

**Comment by darwinharianto** [comment]
Seeing the same thing
python 3.7.13 and ray 2.1.0
macOS Ventura 13.0
intel chip

```
>
2022-11-18 15:11:01,559	ERROR utils.py:1353 -- Internal KV Get failed
Traceback (most recent call last):
  File "/Users/darwinharianto/anaconda3/envs/py-3.7.13/lib/python3.7/site-packages/ray/_private/utils.py", line 1340, in internal_kv_get_with_retry
    result = gcs_client.internal_kv_get(key, namespace)
  File "/Users/darwinharianto/anaconda3/envs/py-3.7.13/lib/python3.7/site-packages/ray/_private/gcs_utils.py", line 177, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/darwinharianto/anaconda3/envs/py-3.7.13/lib/python3.7/site-packages/ray/_private/gcs_utils.py", line 269, in internal_kv_get
    reply = self._kv_stub.InternalKVGet(req, timeout=timeout)
  File "/Users/darwinharianto/anaconda3/envs/py-3.7.13/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/darwinharianto/anaconda3/envs/py-3.7.13/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "Method not found!"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:172.21.36.145:10001 {created_time:"2022-11-18T15:11:01.559798+09:00", grpc_status:12, grpc_message:"Method not found!"}"
```
