### ISSUE TITLE
[Bug] Dashboard can't start with TLS on

### ISSUE THREAD

**Issue by peterhaddad3121** [ray-project/ray#22466]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, Ray Clusters, Monitoring & Debugging, Dashboard

### What happened + What you expected to happen

When deploying a Ray Operator + Ray Cluster utilizing the [following helm chart](https://github.com/ray-project/ray/tree/master/deploy/charts/ray), everything seems to work fine.

When enabling TLS on the head node I start to receive multiple errors when the operator tries to spin up the new head:

```
ray-base,project:	INFO monitor.py:206 -- Monitor: Started
ray-base,project:	DEBUG gcs_utils.py:258 -- internal_kv_del b'__autoscaling_error' None
E0217 05:57:22.475672451      20 ssl_transport_security.cc:1506] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
ray-base,project: 	ERROR gcs_utils.py:137 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:
```

Additionally, I enabled TLS on the Operator and no longer receive SSL errors. When the new cluster it is spinning up, it I receive logs that state the `dashboard` is accessible at `IP`; however, then I receive the following errors.

```
Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1938, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py", line 808, in wrapper
    return f(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 611, in start
    ray_params, head=True, shutdown_at_exit=block, spawn_reaper=block)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 215, in __init__
    self.start_head_processes()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 913, in start_head_processes
    self.start_gcs_server()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 799, in start_gcs_server
    self.get_gcs_client()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 473, in get_gcs_client
    self._gcs_client)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/experimental/internal_kv.py", line 24, in _initialize_internal_kv
    assert gcs_client is not None
AssertionError

ray-base,project:2022-02-17 ERROR gcs_utils.py:137 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1645106242.475769274","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1231","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"

File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 152, in __init__
    gcs_address = self.redis.get("GcsServerAddress").decode("utf-8")
AttributeError: 'NoneType' object has no attribute 'decode'
```

Going directly to the head node and scraping the logs:
/tmp/ray/session_latest/logs/dashboard.logs
```
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 231, in <module>
    loop.run_until_complete(dashboard.run())
  File "/home/ray/anaconda3/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 118, in run
    await self.dashboard_head.run()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/head.py", line 264, in run
    namespace=ray_constants.KV_NAMESPACE_DASHBOARD)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/experimental/internal_kv.py", line 79, in _internal_kv_put
    namespace) == 0
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/gcs_utils.py", line 135, in wrapper
    return f(self, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/gcs_utils.py", line 257, in internal_kv_put
    reply = self._kv_stub.InternalKVPut(req)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1645107943.749460756","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1645107943.749459894","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
```

As a note: when TLS is disabled RAY_USE_TLS: '0', everything works fine.

### Versions / Dependencies

ray:latest images

### Reproduction script

Deploying a Ray cluster using the above helm chart, and enabling TLS.

### Anything else

I am utilizing the following guide to enable TLS on the head node: https://docs.ray.io/en/latest/configure.html#tls-authentication

After doing testing on the head node, I also enabled it on the operator node following the same instructions.

Additionally, I have performed testing by adding these certs to the root chain of the image and rebuilding (as additional testing). I am experiencing the same behavior.

[This issue](https://github.com/ray-project/ray/issues/21031) seems to be the most relevant of what I could find. This does not occur when the TLS environment variables are disabled.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by peterhaddad3121** [comment]
I think the issue is that Ray converts hostnames to IP addresses meaning if you aren't using a self-signed cert, then it will throw an error. The ability to set --address to a hostname that way Common Names (CNs) can be properly generated and used would be helpful.

**Comment by wuisawesome** [comment]
@iycheng @mwtian can y'all take a look? looks like it could be related to migrating internal kv?

**Comment by rkooo567** [comment]
To be clear, you are trying to enable TLS to expose the dashboard endpoint to outside the cluster right?

**Comment by vaibhavnaikprojects** [comment]
I see this issue is closed but did not see a PR attached to this issue. Does ray dashboard server support TLS connection?

**Comment by jjyao** [comment]
Reopen it since it's not supported yet I think.
