### ISSUE TITLE
[serve] `serve_failure` failing with alerts raised

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#22512]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

`serve_failure` is currently failing in the [1.11 release branch](https://buildkite.com/ray-project/periodic-ci/builds/2788#f9a584f1-4c98-418d-9a76-444dc9e0a6ac/139-3338) and the [master branch](https://buildkite.com/ray-project/periodic-ci/builds/2813#0eb6284c-5589-4b2d-9bcc-d7ebaf6cd06b).

### Versions / Dependencies

N/A

### Reproduction script

See `serve_failure` in release/long_running_tests/workloads/serve_failure.py.

### Anything else

`serve_failure` kills random actors (deployment replicas, HTTP proxies, and the Serve controller), and then pings deployments. We noticed two potential causes for the error:

1. As the deployments recover, they call [get_metadata()](https://github.com/ray-project/ray/blob/6e77b3945daeaecad6b8e83544ff7963c2c06775/python/ray/serve/deployment_state.py#L238) (which makes requests to the replica actor) sometimes before the recovering replica's actor is initialized.

2. The test triggers an alert because of late updates. See #22501. Logs reveal that at some point a request issued via `verify_deployment` likely hangs because the `print(f"Executing {action_chosen}")` stop executing before 20 iterations. For example, in #22501, after iteration 251, only 12 print statements are logged.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment]
The smoke test is failing too:
[command_scd_aGuFeMtmYL5nQxcEFQ5jmBSW.log](https://github.com/ray-project/ray/files/8180884/command_scd_aGuFeMtmYL5nQxcEFQ5jmBSW.log)
```
Traceback (most recent call last):
  File "workloads/serve_failure.py", line 163, in <module>
    tester.run()
  File "workloads/serve_failure.py", line 134, in run
    action_chosen()
  File "workloads/serve_failure.py", line 111, in create_deployment
    handler.deploy()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/api.py", line 1062, in deploy
    _blocking=_blocking,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/api.py", line 120, in check
    return f(self, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/api.py", line 316, in deploy
    self._wait_for_deployment_healthy(name)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/api.py", line 250, in _wait_for_deployment_healthy
    raise RuntimeError(f"Deployment {name} is UNHEALTHY: {status.message}")
```
