### ISSUE TITLE
[Bug] AttributeError: 'NoneType' object has no attribute 'all_node_ids' in  autoscaler 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#22515]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Autoscale crashed with following errors:
```
2022-02-18 19:29:47,998	ERROR autoscaler.py:267 -- StandardAutoscaler: Error during autoscaling.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray/autoscaler/_private/autoscaler.py", line 264, in update
    self._update()
  File "/usr/lib/python3.6/site-packages/ray/autoscaler/_private/autoscaler.py", line 291, in _update
    self.non_terminated_nodes = NonTerminatedNodes(self.provider)
  File "/usr/lib/python3.6/site-packages/ray/autoscaler/_private/autoscaler.py", line 86, in __init__
    node_kind = provider.node_tags(node)[TAG_RAY_NODE_KIND]
KeyError: 'ray-node-type'
2022-02-18 19:29:47,999	ERROR monitor.py:394 -- Error in monitor loop
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ray/autoscaler/_private/monitor.py", line 435, in run
    self._run()
  File "/usr/lib/python3.6/site-packages/ray/autoscaler/_private/monitor.py", line 325, in _run
    status["autoscaler_report"] = asdict(self.autoscaler.summary())
  File "/usr/lib/python3.6/site-packages/ray/autoscaler/_private/autoscaler.py", line 1195, in summary
    for node_id in self.non_terminated_nodes.all_node_ids:
AttributeError: 'NoneType' object has no attribute 'all_node_ids'
```

### Versions / Dependencies

Ray 1.10.0 python 3.6

### Reproduction script

N/A

### Anything else

N/A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
Cc @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
Will push a fix soon. 

This happens when the first autoscaler iteration fails. 

Autoscaler logs should have more details on why the first autoscaler iteration failed.

**Comment by DmitriGekhtman** [comment]
The key error is more problematic than the none type issue.

**Comment by DmitriGekhtman** [comment]
The fix to the confusing NoneType-error is linked above.
It appears the underlying issue has to do with the node provider in use.
