### ISSUE TITLE
[Bug] `TimeoutError` with empty train function

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#22527]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Train

### What happened + What you expected to happen

I expected that my minimal training script with an empty train function would run without any errors.

Instead, I received a `TimeoutError`.

```
ubuntu@ip-10-0-2-163:~$ python train.py 
E0221 05:01:04.840153072    4713 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0221 05:01:04.853159958    4713 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0221 05:01:04.860186399    4713 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    trainer.start()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/train/trainer.py", line 231, in start
    ray.get(self._backend_executor_actor.start.remote(initialization_hook))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1733, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TimeoutError): ray::BackendExecutor.start() (pid=4797, ip=10.0.2.163, repr=<ray.train.backend.BackendExecutor object at 0x7f9401fc3f10>)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/train/backend.py", line 153, in start
    self._create_placement_group()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/train/backend.py", line 231, in _create_placement_group
    placement_group.bundle_specs))
TimeoutError: Placement group creation timed out. Make sure your cluster either has enough resources or use an autoscaling cluster. Current resources available: {'accelerator_type:V100': 1.0, 'memory': 38090416128.0, 'object_store_memory': 19045208064.0, 'CPU': 8.0, 'GPU': 1.0, 'node:10.0.2.163': 1.0}, resources requested by the placement group: [{'GPU': 1.0, 'CPU': 1.0}, {'CPU': 1.0, 'GPU': 1.0}, {'CPU': 1.0, 'GPU': 1.0}, {'GPU': 1.0, 'CPU': 1.0}]
```

Here's what `ray status` returned at the time of the error.

```
======== Autoscaler status: 2022-02-21 05:08:20.006104 ========
Node status
---------------------------------------------------------------
Healthy:
 1 ray.head.default
 2 ray.worker.default
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/136.0 CPU
 0.0/17.0 GPU
 0.0/3.0 accelerator_type:V100
 0.00/718.879 GiB memory
 0.00/305.389 GiB object_store_memory

Demands:
 (no resource demands)
```

I also received this error when I bumped the timeout to five minutes.

### Versions / Dependencies

**Cluster**
Ray: 1.10.0
Python: 3.7.7
OS: Ubuntu 18.04.4 LTS

**Laptop**
Ray: 1.10.0
Python: 3.8.12
OS: macOS Big Sur 11.5.2

### Reproduction script

**train.py**
```
from ray import train


def train_func():
    return


trainer = train.Trainer(backend="torch", num_workers=4, use_gpu=True)
trainer.start()
trainer.run(train_func)
trainer.shutdown()
```

**config.yaml**
```
cluster_name: balajis-cluster

min_workers: 2
max_workers: 2

provider:
    type: aws
    region: us-west-2

auth:
    ssh_user: ubuntu
    ssh_private_key: ~/.ssh/id

available_node_types:
    ray.head.default:
        node_config:
            KeyName: balajis-key-pair
            InstanceType: p3.2xlarge
            ImageId: latest_dlami
    ray.worker.default:
        min_workers: 2
        node_config:
            KeyName: balajis-key-pair
            InstanceType: p3.16xlarge
            ImageId: latest_dlami

head_node_type: ray.head.default

setup_commands:
    - pip install ray torch torchvision
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by bveeramani** [comment]
Closing because I didn't include `ray.init("auto")`
