### ISSUE TITLE
[Bug] Launch Ray cluster on GCP via macOS hit the issue of cannot change locale

### ISSUE THREAD

**Issue by orcahmlee** [ray-project/ray#22535]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

I was trying to launch a Ray cluster on GCP via my macOS. When I disabled the `docker` field and used the `setup_commands` field to set up the new node, everything went well. However, when I tried to use `docker` field instead of `setup_commands`, the launching process was failed during the `ray up`. The following info are the minimal config yaml and the error messages.

launch command:
```sh
ray up config.yaml
```

`config.yaml`
```yaml
cluster_name: andrew-py37-cluster

max_workers: 2

docker:
  image:
    "rayproject/ray:latest-cpu" # use this one if you don't need ML dependencies, it's faster to pull
  container_name: "ray_container"
  # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
  # if no cached version is present.
  pull_before_run: True
  run_options: # Extra options to pass into "docker run"
    - --ulimit nofile=65536:65536

# Cloud-provider specific configuration.
provider:
  type: gcp
  region: asia-east1
  availability_zone: asia-east1-a
  project_id: ******

# List of shell commands to run to set up nodes.
setup_commands:
  []
```

The error message after running `ray up`
```sh
......
  New status: setting-up
  [4/7] No initialization commands to run.
  [5/7] Initalizing command runner
Shared connection to **.**.**.** closed.
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
latest-cpu: Pulling from rayproject/ray
ea362f368469: Pull complete
1225d5801c62: Pull complete
edf7c0709b7c: Pull complete
75b09d590bd2: Pull complete
34249622b800: Pull complete
545d5c84ae7c: Pull complete
728c35648956: Pull complete
f1bd0ad6cbb5: Pull complete
fc4467a163ca: Pull complete
Digest: sha256:b317815ebff65d2d02074a2fb7a92fdb375c767a7028b89f65a8085dc6280aa9
Status: Downloaded newer image for rayproject/ray:latest-cpu
docker.io/rayproject/ray:latest-cpu
Shared connection to **.**.**.** closed.
Shared connection to **.**.**.** closed.
Shared connection to **.**.**.** closed.
2022-02-21 15:35:39,140	INFO node.py:295 -- wait_for_compute_zone_operation: Waiting for operation operation-1645428938585-5d882476336cc-2636af33-e51cc252 to finish...
2022-02-21 15:35:44,804	INFO node.py:307 -- wait_for_compute_zone_operation: Operation operation-1645428938585-5d882476
336cc-2636af33-e51cc252 finished.
  New status: update-failed
  !!!
  Expecting value: line 1 column 1 (char 0)
  !!!

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/andrew/miniconda3/envs/ray/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/andrew/miniconda3/envs/ray/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 134, in run
    self.do_update()
  File "/Users/andrew/miniconda3/envs/ray/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 405, in do_update
    sync_run_yet=True)
  File "/Users/andrew/miniconda3/envs/ray/lib/python3.7/site-packages/ray/autoscaler/_private/command_runner.py", line 850, in run_init
    for env_var in json.loads(image_env):
  File "/Users/andrew/miniconda3/envs/ray/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/andrew/miniconda3/envs/ray/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/andrew/miniconda3/envs/ray/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

  Failed to setup head node.
```

I also check the `LC_ALL` and `LANG` my macOS. Although the settings of `LC_ALL` and `LANG` are both `en_US.UTF-8`, seems these settings can not be set on the GCE instances. Since the above error message shows 

```sh
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

Is it possible to make the error message provide more details?

### Versions / Dependencies

```sh
macOS Monterey 12.2.1
Python 3.7.12
ray 1.10.0
```

### Reproduction script

launch command:
```sh
ray up config.yaml
```

`config.yaml`
```yaml
cluster_name: andrew-py37-cluster

max_workers: 2

docker:
  image:
    "rayproject/ray:latest-cpu" # use this one if you don't need ML dependencies, it's faster to pull
  container_name: "ray_container"
  # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
  # if no cached version is present.
  pull_before_run: True
  run_options: # Extra options to pass into "docker run"
    - --ulimit nofile=65536:65536

# Cloud-provider specific configuration.
provider:
  type: gcp
  region: asia-east1
  availability_zone: asia-east1-a
  project_id: ******

# List of shell commands to run to set up nodes.
setup_commands:
  []
```

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by orcahmlee** [comment]
I'm not sure this issue is related to either Ray or my macOS ssh config settings.

I wanna share my solution. After I modified the `ssh_config` on my Mac, I was able to create the Ray cluster(using docker image) on GCE.

```sh
sudo vim /etc/ssh/ssh_config
```
then comment out the `SendEnv LANG LC_*`
```sh
 Host *
#   SendEnv LANG LC_*
```

However, is it possible to make the error message provide more details?

**Comment by wuisawesome** [comment]
Thanks for investigating and finding the root cause. Ideally we will be able to either provide a better error message or just handle locales more robustly.
