### ISSUE TITLE
[Bug] rllib example cannot run

### ISSUE THREAD

**Issue by hellofinch** [ray-project/ray#22589]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune, RLlib

### What happened + What you expected to happen

I run a rllib demo ```multi_agent_two_trainers.py``` but it does work. There are outputs.
It seems that the environment is not a subclass of BaseEnv, MultiAgentEnv, ActorHandle, or ExternalMultiAgentEnv. But I import environment from the rllib.
```
/home/xzk/anaconda3/envs/pettingzoo_tf/lib/python3.8/site-packages/gym/envs/registration.py:505: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1` with the environment ID `CartPole-v1`.
  logger.warn(
2022-02-23 18:57:32,431 INFO trainer.py:2054 -- Your framework setting is 'tf', meaning you are using static-graph mode. Set framework='tf2' to enable eager execution with tf2.x. You may also then want to set eager_tracing=True in order to reach similar execution speed as with static-graph mode.
2022-02-23 18:57:32,434 INFO ppo.py:249 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
2022-02-23 18:57:32,435 INFO trainer.py:790 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=31662)
(pid=31667)
(RolloutWorker pid=31662) 2022-02-23 18:57:37,624       WARNING rollout_worker.py:1674 -- Validating sub-env at vector index=0 ... (warning; invalid env-type=<class 'types.MultiEnv'>)
(RolloutWorker pid=31667) 2022-02-23 18:57:37,954       WARNING rollout_worker.py:1674 -- Validating sub-env at vector index=0 ... (warning; invalid env-type=<class 'types.MultiEnv'>)
(RolloutWorker pid=31662) 2022-02-23 18:57:40,124       ERROR worker.py:432 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=31662, ip=223.193.8.206)
(RolloutWorker pid=31662)   File "/home/xzk/anaconda3/envs/pettingzoo_tf/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 608, in __init__
(RolloutWorker pid=31662)     raise ValueError(
(RolloutWorker pid=31662) ValueError: Have multiple policies {}, but the env <types.MultiEnv object at 0x7fb2bd585370> is not a subclass of BaseEnv, MultiAgentEnv, ActorHandle, or ExternalMultiAgentEnv!
Traceback (most recent call last):
  File "/home/xzk/anaconda3/envs/pettingzoo_tf/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 811, in setup
    self._init(self.config, self.env_creator)
  File "/home/xzk/anaconda3/envs/pettingzoo_tf/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 923, in _init
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2train.py", line 82, in <module>
    ppo_trainer = PPOTrainer(
  File "/home/xzk/anaconda3/envs/pettingzoo_tf/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 728, in __init__
    super().__init__(config, logger_creator, remote_checkpoint_dir,
  File "/home/xzk/anaconda3/envs/pettingzoo_tf/lib/python3.8/site-packages/ray/tune/trainable.py", line 122, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/xzk/anaconda3/envs/pettingzoo_tf/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 826, in setup
    self.workers = self._make_workers(
  File "/home/xzk/anaconda3/envs/pettingzoo_tf/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1925, in _make_workers
    return WorkerSet(
  File "/home/xzk/anaconda3/envs/pettingzoo_tf/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 100, in __init__
    remote_spaces = ray.get(self.remote_workers(
  File "/home/xzk/anaconda3/envs/pettingzoo_tf/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/xzk/anaconda3/envs/pettingzoo_tf/lib/python3.8/site-packages/ray/worker.py", line 1735, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=31667, ip=223.193.8.206)
  File "/home/xzk/anaconda3/envs/pettingzoo_tf/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 608, in __init__
    raise ValueError(
ValueError: Have multiple policies {}, but the env <types.MultiEnv object at 0x7f63ee3da280> is not a subclass of BaseEnv, MultiAgentEnv, ActorHandle, or ExternalMultiAgentEnv!
(RolloutWorker pid=31667) 2022-02-23 18:57:40,448       ERROR worker.py:432 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=31667, ip=223.193.8.206)
(RolloutWorker pid=31667)   File "/home/xzk/anaconda3/envs/pettingzoo_tf/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 608, in __init__
(RolloutWorker pid=31667)     raise ValueError(
(RolloutWorker pid=31667) ValueError: Have multiple policies {}, but the env <types.MultiEnv object at 0x7f63ee3da280> is not a subclass of BaseEnv, MultiAgentEnv, ActorHandle, or ExternalMultiAgentEnv
```

### Versions / Dependencies

ray 1.10.0
torch 1.10.2
cudatoolkit 10.1
tensorflow-gpu 2.4.1

### Reproduction script

python multi_agent_two_trainers.py

### Anything else
I hope you can provide a script to tell how to use the amazing rllib. The scripts all you provide are a little bit hard to learn the rllib.
_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by NastiyaM** [comment]
Hi! Did you solve the problems?

**Comment by hellofinch** [comment]
> Hi! Did you solve the problems? Previously I worked in azure on ubuntu 18.04 Standard E2as v4, but now I get a similar error.

Nope, I haven't solved the problems.

**Comment by gjoliver** [comment]
should be fixed with https://github.com/ray-project/ray/commit/e391b624f0bcc57b3df7f050d59a9f6b8764000e
let us know if it's still an issue.
