### ISSUE TITLE
[Error]: 'InProgressSentinel' object has no attribute 'id'

### ISSUE THREAD

**Issue by ramesh-shah75551** [ray-project/ray#22585]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 376, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 211, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/workspaces/AnyML_mlteam/src/prediction/api_service.py", line 116, in counterfactualpredict
    counterService.try_to_predict.remote(counterService,
  File "/usr/local/lib/python3.8/site-packages/ray/remote_function.py", line 139, in _remote_proxy
    return self._remote(args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 295, in _invocation_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/remote_function.py", line 245, in _remote
    return client_mode_convert_function(
  File "/usr/local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 173, in client_mode_convert_function
    return client_func._remote(in_args, in_kwargs, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/util/client/common.py", line 130, in _remote
    return self.options(**option_args).remote(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/util/client/common.py", line 380, in remote
    return return_refs(ray.call_remote(self, *args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/ray/util/client/api.py", line 106, in call_remote
    return self.worker.call_remote(instance, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/util/client/worker.py", line 449, in call_remote
    task = instance._prepare_client_task()
  File "/usr/local/lib/python3.8/site-packages/ray/util/client/common.py", line 386, in _prepare_client_task
    task = self._remote_stub._prepare_client_task()
  File "/usr/local/lib/python3.8/site-packages/ray/util/client/common.py", line 160, in _prepare_client_task
    task.payload_id = self._ref.id
AttributeError: 'InProgressSentinel' object has no attribute 'id'

**Comment by rkooo567** [comment]
Can you talk a bit more about your setup? Are you using the ray client?

**Comment by crptcusco** [comment]
I think you are using or calling two times te the ray.init(). Im using a jupyter notebook, y restart the jupyter and all its rigth

**Comment by itsmemuthu** [comment]
Any updates on this issue.

I am also facing the same issue.

**Setup details:**
```
**Ray Remote cluster:**
  Python 3.8.5
  ray docker base image - rayproject/ray:nightly-py38-cpu
Ray remote cluster is deployed in Kubernetes with 1 head node and 4 worker nodes.

**Ray client:**
  Python 3.8.10
  ray 3.0.0.dev0
```

Developed a FastAPI application, initialized ray client and defined a remote function.

On invoking this function for the first time, receiving **ModuleNotFoundError**
```
  File "/usr/local/lib/python3.8/dist-packages/ray/remote_function.py", line 121, in _remote_proxy
    return self._remote(args=args, kwargs=kwargs, **self._default_options)
  File "/usr/local/lib/python3.8/dist-packages/ray/util/tracing/tracing_helper.py", line 307, in _invocation_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/remote_function.py", line 188, in _remote
    return client_mode_convert_function(self, args, kwargs, **task_options)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/client_mode_hook.py", line 178, in client_mode_convert_function
    return client_func._remote(in_args, in_kwargs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/util/client/common.py", line 298, in _remote
    return self.options(**option_args).remote(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/util/client/common.py", line 572, in remote
    return return_refs(ray.call_remote(self, *args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/ray/util/client/api.py", line 100, in call_remote
    return self.worker.call_remote(instance, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/util/client/worker.py", line 545, in call_remote
    task = instance._prepare_client_task()
  File "/usr/local/lib/python3.8/dist-packages/ray/util/client/common.py", line 578, in _prepare_client_task
    task = self._remote_stub._prepare_client_task()
  File "/usr/local/lib/python3.8/dist-packages/ray/util/client/common.py", line 324, in _prepare_client_task
    self._ensure_ref()
  File "/usr/local/lib/python3.8/dist-packages/ray/util/client/common.py", line 319, in _ensure_ref
    self._ref = ray.worker._put_pickled(
  File "/usr/local/lib/python3.8/dist-packages/ray/util/client/worker.py", line 499, in _put_pickled
    raise cloudpickle.loads(resp.error)
ModuleNotFoundError: No module named 'app'
```
'app' is a local module that I have in my application.

On making the next API requests after the first call, I am getting **AttributeError: 'InProgressSentinel' object has no attribute 'id'**

```
  File "/usr/local/lib/python3.8/dist-packages/ray/remote_function.py", line 121, in _remote_proxy
    return self._remote(args=args, kwargs=kwargs, **self._default_options)
  File "/usr/local/lib/python3.8/dist-packages/ray/util/tracing/tracing_helper.py", line 307, in _invocation_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/remote_function.py", line 188, in _remote
    return client_mode_convert_function(self, args, kwargs, **task_options)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/client_mode_hook.py", line 178, in client_mode_convert_function
    return client_func._remote(in_args, in_kwargs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/util/client/common.py", line 298, in _remote
    return self.options(**option_args).remote(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/util/client/common.py", line 572, in remote
    return return_refs(ray.call_remote(self, *args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/ray/util/client/api.py", line 100, in call_remote
    return self.worker.call_remote(instance, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/util/client/worker.py", line 545, in call_remote
    task = instance._prepare_client_task()
  File "/usr/local/lib/python3.8/dist-packages/ray/util/client/common.py", line 578, in _prepare_client_task
    task = self._remote_stub._prepare_client_task()
  File "/usr/local/lib/python3.8/dist-packages/ray/util/client/common.py", line 328, in _prepare_client_task
    task.payload_id = self._ref.id
AttributeError: 'InProgressSentinel' object has no attribute 'id'

```
Can someone please help me resolve this issue.

**Comment by itsmemuthu** [comment]
The issue is resolved.

I am posting the solution for other's reference.
1. The project or application codebase has to be present in the remote ray cluster (both head and worker) container also
2. Set appropriate environment path (if any) in Kubernetes YAML file to get the module recognized (In my case, I set PYTHONPATH to the root directory)

This solved the issue.

**Comment by rkooo567** [comment]
Hey @ckw017 can you verify if both fixes were expected (if so, is it documented)? It seems to be a pretty bad usability issue
