### ISSUE TITLE
[Bug] "Discrete" space sampling breaks on gym >= 0.22.0

### ISSUE THREAD

**Issue by ThomasCassimon** [ray-project/ray#22593]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib, Others

### What happened + What you expected to happen

When "gym==0.22.0" is installed, sampling certain observation spaces throws an AttributeError. Using the same code with "gym==0.21.0" works.

The expected behaviour is for the training cycle to finish without any errors.

The actual behaviour involves tune crashing during the training process with the following stack trace:
```
RAY VERSION: 1.10.0
NUMPY VERSION: 1.22.2
GYM VERSION: 0.22.0
2022-02-23 15:31:07,147 INFO services.py:1374 -- View the Ray dashboard at http://127.0.0.1:8266
== Status ==
Current time: 2022-02-23 15:31:08 (running for 00:00:00.31)
Memory usage on this node: 4.5/49.0 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/11 CPUs, 0/0 GPUs, 0.0/27.59 GiB heap, 0.0/13.79 GiB objects
Result logdir: /home/user/ray_results/PPO
Number of trials: 1/1 (1 PENDING)
+--------------------------+----------+-------+
| Trial name               | status   | loc   |
|--------------------------+----------+-------|
| PPO_test_env_3d902_00000 | PENDING  |       |
+--------------------------+----------+-------+


(bundle_reservation_check_func pid=137585) 
(PPOTrainer pid=137585) 2022-02-23 15:31:10,939 INFO ppo.py:249 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
(PPOTrainer pid=137585) 2022-02-23 15:31:10,939 INFO trainer.py:790 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=137579) 
(pid=137583) 
2022-02-23 15:31:13,308 ERROR trial_runner.py:927 -- Trial PPO_test_env_3d902_00000: Error processing event.
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 893, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/user/.local/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 707, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/user/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/ray/worker.py", line 1735, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::PPOTrainer.__init__() (pid=137585, ip=10.0.10.42)
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 923, in _init
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

ray::PPOTrainer.__init__() (pid=137585, ip=10.0.10.42)
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 728, in __init__
    super().__init__(config, logger_creator, remote_checkpoint_dir,
  File "/home/user/.local/lib/python3.8/site-packages/ray/tune/trainable.py", line 122, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 826, in setup
    self.workers = self._make_workers(
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1925, in _make_workers
    return WorkerSet(
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 123, in __init__
    self._local_worker = self._make_worker(
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 497, in _make_worker
    worker = cls(
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 588, in __init__
    self._build_policy_map(
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1547, in _build_policy_map
    preprocessor = ModelCatalog.get_preprocessor_for_space(
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/models/catalog.py", line 703, in get_preprocessor_for_space
    prep = cls(observation_space, options)
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/models/preprocessors.py", line 43, in __init__
    self._obs_for_type_matching = self._obs_space.sample()
  File "/home/user/.local/lib/python3.8/site-packages/gym/spaces/discrete.py", line 28, in sample
    return self.start + self.np_random.randint(self.n)
AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'
Result for PPO_test_env_3d902_00000:
  trial_id: 3d902_00000
  
== Status ==
Current time: 2022-02-23 15:31:13 (running for 00:00:04.84)
Memory usage on this node: 4.8/49.0 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/11 CPUs, 0/0 GPUs, 0.0/27.59 GiB heap, 0.0/13.79 GiB objects
Result logdir: /home/user/ray_results/PPO
Number of trials: 1/1 (1 ERROR)
+--------------------------+----------+-------+
| Trial name               | status   | loc   |
|--------------------------+----------+-------|
| PPO_test_env_3d902_00000 | ERROR    |       |
+--------------------------+----------+-------+
Number of errored trials: 1
+--------------------------+--------------+--------------------------------------------------------------------------------------+
| Trial name               |   # failures | error file                                                                           |
|--------------------------+--------------+--------------------------------------------------------------------------------------|
| PPO_test_env_3d902_00000 |            1 | /home/user/ray_results/PPO/PPO_test_env_3d902_00000_0_2022-02-23_15-31-08/error.txt |
+--------------------------+--------------+--------------------------------------------------------------------------------------+

(PPOTrainer pid=137585) 2022-02-23 15:31:13,304 ERROR worker.py:432 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::PPOTrainer.__init__() (pid=137585, ip=10.0.10.42)
(PPOTrainer pid=137585)   File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 923, in _init
(PPOTrainer pid=137585)     raise NotImplementedError
(PPOTrainer pid=137585) NotImplementedError
(PPOTrainer pid=137585) 
(PPOTrainer pid=137585) During handling of the above exception, another exception occurred:
(PPOTrainer pid=137585) 
(PPOTrainer pid=137585) ray::PPOTrainer.__init__() (pid=137585, ip=10.0.10.42)
(PPOTrainer pid=137585)   File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 728, in __init__
(PPOTrainer pid=137585)     super().__init__(config, logger_creator, remote_checkpoint_dir,
(PPOTrainer pid=137585)   File "/home/user/.local/lib/python3.8/site-packages/ray/tune/trainable.py", line 122, in __init__
(PPOTrainer pid=137585)     self.setup(copy.deepcopy(self.config))
(PPOTrainer pid=137585)   File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 826, in setup
(PPOTrainer pid=137585)     self.workers = self._make_workers(
(PPOTrainer pid=137585)   File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1925, in _make_workers
(PPOTrainer pid=137585)     return WorkerSet(
(PPOTrainer pid=137585)   File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 123, in __init__
(PPOTrainer pid=137585)     self._local_worker = self._make_worker(
(PPOTrainer pid=137585)   File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 497, in _make_worker
(PPOTrainer pid=137585)     worker = cls(
(PPOTrainer pid=137585)   File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 588, in __init__
(PPOTrainer pid=137585)     self._build_policy_map(
(PPOTrainer pid=137585)   File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1547, in _build_policy_map
(PPOTrainer pid=137585)     preprocessor = ModelCatalog.get_preprocessor_for_space(
(PPOTrainer pid=137585)   File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/models/catalog.py", line 703, in get_preprocessor_for_space
(PPOTrainer pid=137585)     prep = cls(observation_space, options)
(PPOTrainer pid=137585)   File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/models/preprocessors.py", line 43, in __init__
(PPOTrainer pid=137585)     self._obs_for_type_matching = self._obs_space.sample()
(PPOTrainer pid=137585)   File "/home/user/.local/lib/python3.8/site-packages/gym/spaces/discrete.py", line 28, in sample
(PPOTrainer pid=137585)     return self.start + self.np_random.randint(self.n)
(PPOTrainer pid=137585) AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'
(RolloutWorker pid=137579) 2022-02-23 15:31:13,274  WARNING rollout_worker.py:1674 -- Validating sub-env at vector index=0 ... (warning; invalid env-type=<class '__main__.TestEnv'>)
(RolloutWorker pid=137579) 2022-02-23 15:31:13,288  WARNING deprecation.py:45 -- DeprecationWarning: `rllib.env.remote_vector_env.RemoteVectorEnv` has been deprecated. Use `ray.rllib.env.remote_base_env.RemoteBaseEnv` instead. This will raise an error in the future!
(RolloutWorker pid=137583) 2022-02-23 15:31:13,283  WARNING rollout_worker.py:1674 -- Validating sub-env at vector index=0 ... (warning; invalid env-type=<class '__main__.TestEnv'>)
(RolloutWorker pid=137583) 2022-02-23 15:31:13,297  WARNING deprecation.py:45 -- DeprecationWarning: `rllib.env.remote_vector_env.RemoteVectorEnv` has been deprecated. Use `ray.rllib.env.remote_base_env.RemoteBaseEnv` instead. This will raise an error in the future!
Traceback (most recent call last):
  File "/home/user/PycharmProjects/rllib-bug-report/rllib_bug_report.py", line 109, in <module>
    exit(main())
  File "/home/user/PycharmProjects/rllib-bug-report/rllib_bug_report.py", line 97, in main
    tune.run(
  File "/home/user/.local/lib/python3.8/site-packages/ray/tune/tune.py", line 630, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_test_env_3d902_00000])
(PPOTrainer pid=137585) 

Process finished with exit code 1
```

### Versions / Dependencies

Ray version: 1.10.0
Python version: 3.8.10
OS: Linux 5.4.0-92-generic #103-Ubuntu

gym: 0.21.0 works, 0.22.0 crashes
numpy: 1.22.2 and 1.21.2 both result in the same issue.

### Reproduction script
```
import gym
import ray

from ray import tune
from typing import Any, Dict


class TestEnv(gym.Env):
	def __init__(self):
		super(TestEnv, self).__init__()

		self.observation_space = gym.spaces.Discrete(n=1)
		self.action_space = gym.spaces.Discrete(n=1)

	def __observe(self) -> int:
		return 0

	def step(self, action):
		# Ignore actions, just return some observations
		return self.__observe(), 1, True, {}

	def reset(self):
		return self.__observe()


def main() -> int:
	print(f"RAY VERSION: {ray.__version__}")	# Ray 1.10.0
	print(f"GYM VERSION: {gym.__version__}")	# gym 0.22.0 breaks, 0.21.0 works

	policy: str = "PPO"

	ray.tune.register_env("test_env", lambda _: TestEnv())

	tune_config = {
		"env": "test_env",
		"env_config": {}
	}

	tune.run(
		policy,
		stop={"episodes_total": 1},
		config=tune_config,
		mode="max",
		metric="episode_reward_mean"
	)

	return 0


if __name__ == "__main__":
	exit(main())
```

### Anything else

The crash occurs every time the reproduction script is ran.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ThomasCassimon** [comment]
Seems like the issue I ran into is likely one of the issues discussed in https://github.com/ray-project/ray/pull/22510, closing for now, since the workaround is scheduled to be merged in 1.11.
