### ISSUE TITLE
Installation fails after installing PyTorch dependencies.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#226]
Prior to all of this, I installed Anaconda 3.5 and did

```
sudo apt-get update
sudo apt-get install -y cmake build-essential autoconf curl libtool libboost-all-dev unzip
```

Following instructions from https://github.com/pytorch/pytorch#installation on Linux, I did

```
export CMAKE_PREFIX_PATH=[anaconda root directory]
conda install numpy mkl setuptools cmake gcc cffi
conda install -c soumith magma-cuda75
```

Then cloning Ray and doing `python setup.py install` from `ray/python` failed with

```
ubuntu@ip-172-31-34-198:~/ray/python$ python setup.py install
running install
~/ray/src/common/thirdparty ~/ray/python
~/ray/python
+ set -e
+++ dirname /home/ubuntu/ray/src/numbuf/thirdparty/download_thirdparty.sh
++ cd /home/ubuntu/ray/src/numbuf/thirdparty
++ pwd
+ TP_DIR=/home/ubuntu/ray/src/numbuf/thirdparty
+ '[' '!' -d /home/ubuntu/ray/src/numbuf/thirdparty/arrow ']'
+ cd /home/ubuntu/ray/src/numbuf/thirdparty/arrow
+ git checkout c88bd70c13cf16c07b840623cb466aa98d535be0
HEAD is now at c88bd70... Build arrow_io and arrow_ipc as static libraries.
+ set -e
+++ dirname /home/ubuntu/ray/src/numbuf/thirdparty/build_thirdparty.sh
++ cd /home/ubuntu/ray/src/numbuf/thirdparty
++ pwd
+ TP_DIR=/home/ubuntu/ray/src/numbuf/thirdparty
+ PREFIX=/home/ubuntu/ray/src/numbuf/thirdparty/installed
++ uname
+ unamestr=Linux
+ [[ Linux == \L\i\n\u\x ]]
++ nproc
+ PARALLEL=64
+ echo 'building arrow'
building arrow
+ cd /home/ubuntu/ray/src/numbuf/thirdparty/arrow/cpp
+ mkdir -p /home/ubuntu/ray/src/numbuf/thirdparty/arrow/cpp/build
+ cd /home/ubuntu/ray/src/numbuf/thirdparty/arrow/cpp/build
+ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS=-g -DCMAKE_CXX_FLAGS=-g -DARROW_BUILD_TESTS=OFF ..
clang-tidy not found
clang-format not found
Configured for RELEASE build (set with cmake -DCMAKE_BUILD_TYPE={release,debug,...})
-- Build Type: RELEASE
INFO Reading specs from /home/ubuntu/anaconda3/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.8.5/specs
COLLECT_GCC=/home/ubuntu/anaconda3/bin/c++
COLLECT_LTO_WRAPPER=/home/ubuntu/anaconda3/bin/../libexec/gcc/x86_64-unknown-linux-gnu/4.8.5/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ./configure --prefix=/home/ray/mc-x64-2.7/conda-bld/gcc_1479223211463/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold --with-gxx-include-dir=/home/ray/mc-x64-2.7/conda-bld/gcc_1479223211463/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/gcc/include/c++ --bindir=/home/ray/mc-x64-2.7/conda-bld/gcc_1479223211463/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin --datarootdir=/home/ray/mc-x64-2.7/conda-bld/gcc_1479223211463/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/share --libdir=/home/ray/mc-x64-2.7/conda-bld/gcc_1479223211463/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib --with-gmp=/home/ray/mc-x64-2.7/conda-bld/gcc_1479223211463/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold --with-mpfr=/home/ray/mc-x64-2.7/conda-bld/gcc_1479223211463/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold --with-mpc=/home/ray/mc-x64-2.7/conda-bld/gcc_1479223211463/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold --with-isl=/home/ray/mc-x64-2.7/conda-bld/gcc_1479223211463/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold --with-cloog=/home/ray/mc-x64-2.7/conda-bld/gcc_1479223211463/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold --enable-checking=release --with-tune=generic --disable-multilib
Thread model: posix
gcc version 4.8.5 (GCC) 

Selected compiler gcc 4.8.5
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:946 ] _boost_TEST_VERSIONS = 1.61.0;1.61;1.60.0;1.60;1.59.0;1.59;1.58.0;1.58;1.57.0;1.57;1.56.0;1.56;1.55.0;1.55;1.54.0;1.54;1.53.0;1.53;1.52.0;1.52;1.51.0;1.51;1.50.0;1.50;1.49.0;1.49;1.48.0;1.48;1.47.0;1.47;1.46.1;1.46.0;1.46;1.45.0;1.45;1.44.0;1.44;1.43.0;1.43;1.42.0;1.42;1.41.0;1.41;1.40.0;1.40;1.39.0;1.39;1.38.0;1.38;1.37.0;1.37;1.36.1;1.36.0;1.36;1.35.1;1.35.0;1.35;1.34.1;1.34.0;1.34;1.33.1;1.33.0;1.33
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:948 ] Boost_USE_MULTITHREADED = ON
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:950 ] Boost_USE_STATIC_LIBS = ON
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:952 ] Boost_USE_STATIC_RUNTIME = 
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:954 ] Boost_ADDITIONAL_VERSIONS = 
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:956 ] Boost_NO_SYSTEM_PATHS = 
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1024 ] Declared as CMake or Environmental Variables:
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1026 ]   BOOST_ROOT = 
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1028 ]   BOOST_INCLUDEDIR = 
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1030 ]   BOOST_LIBRARYDIR = 
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1032 ] _boost_TEST_VERSIONS = 1.61.0;1.61;1.60.0;1.60;1.59.0;1.59;1.58.0;1.58;1.57.0;1.57;1.56.0;1.56;1.55.0;1.55;1.54.0;1.54;1.53.0;1.53;1.52.0;1.52;1.51.0;1.51;1.50.0;1.50;1.49.0;1.49;1.48.0;1.48;1.47.0;1.47;1.46.1;1.46.0;1.46;1.45.0;1.45;1.44.0;1.44;1.43.0;1.43;1.42.0;1.42;1.41.0;1.41;1.40.0;1.40;1.39.0;1.39;1.38.0;1.38;1.37.0;1.37;1.36.1;1.36.0;1.36;1.35.1;1.35.0;1.35;1.34.1;1.34.0;1.34;1.33.1;1.33.0;1.33
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1125 ] location of version.hpp: /usr/include/boost/version.hpp
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1149 ] version.hpp reveals boost 1.58.0
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1235 ] guessed _boost_COMPILER = -gcc48
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1245 ] _boost_MULTITHREADED = -mt
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1288 ] _boost_RELEASE_ABI_TAG = -
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1290 ] _boost_DEBUG_ABI_TAG = -d
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1344 ] _boost_LIBRARY_SEARCH_DIRS_RELEASE = /usr/include/lib;/usr/include/../lib;/usr/include/stage/lib;PATHS;C:/boost/lib;C:/boost;/sw/local/lib_boost_LIBRARY_SEARCH_DIRS_DEBUG   = /usr/include/lib;/usr/include/../lib;/usr/include/stage/lib;PATHS;C:/boost/lib;C:/boost;/sw/local/lib
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1483 ] Searching for SYSTEM_LIBRARY_RELEASE: boost_system-gcc48-mt-1_58;boost_system-gcc48-mt;boost_system-mt-1_58;boost_system-mt;boost_system
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1525 ] Searching for SYSTEM_LIBRARY_DEBUG: boost_system-gcc48-mt-d-1_58;boost_system-gcc48-mt-d;boost_system-mt-d-1_58;boost_system-mt-d;boost_system-mt;boost_system
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1483 ] Searching for FILESYSTEM_LIBRARY_RELEASE: boost_filesystem-gcc48-mt-1_58;boost_filesystem-gcc48-mt;boost_filesystem-mt-1_58;boost_filesystem-mt;boost_filesystem
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1525 ] Searching for FILESYSTEM_LIBRARY_DEBUG: boost_filesystem-gcc48-mt-d-1_58;boost_filesystem-gcc48-mt-d;boost_filesystem-mt-d-1_58;boost_filesystem-mt-d;boost_filesystem-mt;boost_filesystem
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1595 ] Boost_FOUND = 1
CMake Error at /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1753 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /usr/include

  Could not find the following static Boost libraries:

          boost_system
          boost_filesystem

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:437 (find_package)


-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:946 ] _boost_TEST_VERSIONS = 1.61.0;1.61;1.60.0;1.60;1.59.0;1.59;1.58.0;1.58;1.57.0;1.57;1.56.0;1.56;1.55.0;1.55;1.54.0;1.54;1.53.0;1.53;1.52.0;1.52;1.51.0;1.51;1.50.0;1.50;1.49.0;1.49;1.48.0;1.48;1.47.0;1.47;1.46.1;1.46.0;1.46;1.45.0;1.45;1.44.0;1.44;1.43.0;1.43;1.42.0;1.42;1.41.0;1.41;1.40.0;1.40;1.39.0;1.39;1.38.0;1.38;1.37.0;1.37;1.36.1;1.36.0;1.36;1.35.1;1.35.0;1.35;1.34.1;1.34.0;1.34;1.33.1;1.33.0;1.33
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:948 ] Boost_USE_MULTITHREADED = ON
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:950 ] Boost_USE_STATIC_LIBS = OFF
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:952 ] Boost_USE_STATIC_RUNTIME = 
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:954 ] Boost_ADDITIONAL_VERSIONS = 
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:956 ] Boost_NO_SYSTEM_PATHS = 
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1024 ] Declared as CMake or Environmental Variables:
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1026 ]   BOOST_ROOT = 
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1028 ]   BOOST_INCLUDEDIR = 
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1030 ]   BOOST_LIBRARYDIR = 
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1032 ] _boost_TEST_VERSIONS = 1.61.0;1.61;1.60.0;1.60;1.59.0;1.59;1.58.0;1.58;1.57.0;1.57;1.56.0;1.56;1.55.0;1.55;1.54.0;1.54;1.53.0;1.53;1.52.0;1.52;1.51.0;1.51;1.50.0;1.50;1.49.0;1.49;1.48.0;1.48;1.47.0;1.47;1.46.1;1.46.0;1.46;1.45.0;1.45;1.44.0;1.44;1.43.0;1.43;1.42.0;1.42;1.41.0;1.41;1.40.0;1.40;1.39.0;1.39;1.38.0;1.38;1.37.0;1.37;1.36.1;1.36.0;1.36;1.35.1;1.35.0;1.35;1.34.1;1.34.0;1.34;1.33.1;1.33.0;1.33
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1125 ] location of version.hpp: /usr/include/boost/version.hpp
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1149 ] version.hpp reveals boost 1.58.0
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1235 ] guessed _boost_COMPILER = -gcc48
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1245 ] _boost_MULTITHREADED = -mt
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1288 ] _boost_RELEASE_ABI_TAG = -
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1290 ] _boost_DEBUG_ABI_TAG = -d
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1344 ] _boost_LIBRARY_SEARCH_DIRS_RELEASE = /usr/include/lib;/usr/include/../lib;/usr/include/stage/lib;PATHS;C:/boost/lib;C:/boost;/sw/local/lib_boost_LIBRARY_SEARCH_DIRS_DEBUG   = /usr/include/lib;/usr/include/../lib;/usr/include/stage/lib;PATHS;C:/boost/lib;C:/boost;/sw/local/lib
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1483 ] Searching for SYSTEM_LIBRARY_RELEASE: boost_system-gcc48-mt-1_58;boost_system-gcc48-mt;boost_system-mt-1_58;boost_system-mt;boost_system
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1525 ] Searching for SYSTEM_LIBRARY_DEBUG: boost_system-gcc48-mt-d-1_58;boost_system-gcc48-mt-d;boost_system-mt-d-1_58;boost_system-mt-d;boost_system-mt;boost_system
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1483 ] Searching for FILESYSTEM_LIBRARY_RELEASE: boost_filesystem-gcc48-mt-1_58;boost_filesystem-gcc48-mt;boost_filesystem-mt-1_58;boost_filesystem-mt;boost_filesystem
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1525 ] Searching for FILESYSTEM_LIBRARY_DEBUG: boost_filesystem-gcc48-mt-d-1_58;boost_filesystem-gcc48-mt-d;boost_filesystem-mt-d-1_58;boost_filesystem-mt-d;boost_filesystem-mt;boost_filesystem
-- [ /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1595 ] Boost_FOUND = 1
CMake Error at /home/ubuntu/anaconda3/share/cmake-3.6/Modules/FindBoost.cmake:1753 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_system
          boost_filesystem

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:444 (find_package)


CMake Error at CMakeLists.txt:447 (list):
  list sub-command SORT requires list to be present.


-- Boost include dir: /usr/include
-- Boost libraries: 
CMake Error at CMakeLists.txt:421 (message):
  No static or shared library provided for NOTFOUND
Call Stack (most recent call first):
  CMakeLists.txt:462 (ADD_THIRDPARTY_LIB)


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/ray/src/numbuf/thirdparty/arrow/cpp/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/ray/src/numbuf/thirdparty/arrow/cpp/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 41, in <module>
    license="Apache 2.0")
  File "/home/ubuntu/anaconda3/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/ubuntu/anaconda3/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/ubuntu/anaconda3/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 13, in run
    subprocess.check_call(["../build.sh"])
  File "/home/ubuntu/anaconda3/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../build.sh']' returned non-zero exit status 1
```

**Comment by robertnishihara** [comment]
I just tried again, this time installing PyTorch via pip using the instructions here http://pytorch.org/. It worked fine this time.
