### ISSUE TITLE
[Bug] RLlib slate_q example causing GCS to be non-responsive

### ISSUE THREAD

**Issue by ZhijieWang** [ray-project/ray#22607]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, RLlib, Ray Clusters

### What happened + What you expected to happen

I'm attempting to run the rllib example recommender_system_with_recsim_and_slateq.py on anyscale, but I'm getting the error:
[specific-server] Failed to put health check on None
<InactiveRpcError of RPC that terminated with:
status = StatusCode.UNAVAILABLE
details = "failed to connect to all addresses"
debug_error_string = "{"created":"@1645577073.258403759","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1645577073.258402994","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
The example runs fine on my local machine. I have made sure that the ray version between my machine and the anyscale cluster is exactly the same. I also tried running the example directly from the cluster terminal rather than using ray.init('anyscale_address') from my laptop and I got the following traceback:
Traceback (most recent call last):
File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/utils.py", line 1206, in internal_kv_get_with_retry
result = gcs_client.internal_kv_get(key, namespace)
File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/gcs_utils.py", line 146, in wrapper
return f(self, *args, **kwargs)
File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/gcs_utils.py", line 230, in internal_kv_get
reply = self._kv_stub.InternalKVGet(req)
File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call_
return _end_unary_response_blocking(state, call, False, None)
File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
raise _InactiveRpcError(state)
Do you have any ideas on how I can fix this? (edited)

### Versions / Dependencies

1.10

### Reproduction script

recommender_system_with_recsim_and_slateq.py

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ZhijieWang** [comment]
working on repro, more info should come

**Comment by ZhijieWang** [comment]
closing, mitigated.
