### ISSUE TITLE
[Bug] Custom model with R2D2

### ISSUE THREAD

**Issue by motokiomura** [ray-project/ray#22747]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

I'm getting the following bug when using custom models in r2d2.

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/models/catalog.py", line 636, in get_model_v2
    **customized_model_kwargs,
TypeError: __init__() got an unexpected keyword argument 'q_hiddens'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rllib_r2d2_test.py", line 59, in <module>
    trainer = R2D2Trainer(config=config)
  File "/opt/anaconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 828, in __init__
    config, logger_creator, remote_checkpoint_dir, sync_function_tpl
  File "/opt/anaconda3/envs/rl/lib/python3.7/site-packages/ray/tune/trainable.py", line 142, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/opt/anaconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 915, in setup
    logdir=self.logdir,
  File "/opt/anaconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 169, in __init__
    spaces=spaces,
  File "/opt/anaconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 593, in _make_worker
    spaces=spaces,
  File "/opt/anaconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 619, in __init__
    seed=seed,
  File "/opt/anaconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1714, in _build_policy_map
    name, orig_cls, obs_space, act_space, conf, merged_conf
  File "/opt/anaconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/policy/policy_map.py", line 152, in create_policy
    self[policy_id] = class_(observation_space, action_space, merged_config)
  File "/opt/anaconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/policy/policy_template.py", line 279, in __init__
    self, obs_space, action_space, config
  File "/opt/anaconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/agents/dqn/r2d2_torch_policy.py", line 60, in build_r2d2_model_and_distribution
    policy, obs_space, action_space, config
  File "/opt/anaconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/agents/dqn/dqn_torch_policy.py", line 197, in build_q_model_and_distribution
    add_layer_norm=add_layer_norm,
  File "/opt/anaconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/models/catalog.py", line 647, in get_model_v2
    **model_kwargs,
TypeError: __init__() got an unexpected keyword argument 'q_hiddens'
```

I believe this is due to the wrong order of model wrapping.  I checked the model classes in 
https://github.com/ray-project/ray/blob/5a0b7a7ee06c0874be94dee7efcfd3dd84c89512/rllib/models/catalog.py#L595-L600 

If you don't use a custom model, the model class is
 `<class 'ray.rllib.models.catalog.FullyConnectedNetwork_as_LSTMWrapper_as_DQNTorchModel'>` , 
but if you use FullyConnectedNetwork as a custom model, the model class is 
`<class 'ray.rllib.models.catalog.FullyConnectedNetwork_as_DQNTorchModel_as_LSTMWrapper'>`.
Reproduction script is written below.

I made sure that it works correctly by moving `https://github.com/ray-project/ray/blob/5a0b7a7ee06c0874be94dee7efcfd3dd84c89512/rllib/models/catalog.py#L475` to the back of the lstm wrapping.

### Versions / Dependencies

ray==2.0.0.dev0
python==3.7
torch==1.5.1

### Reproduction script

```.py
from ray.rllib.agents.dqn import R2D2Trainer
from ray.rllib.models.torch.fcnet import FullyConnectedNetwork as TorchFC
from ray.rllib.models import ModelCatalog


ModelCatalog.register_custom_model(
        "custom_model",
        TorchFC
)

config = {
        'framework': 'torch',
        'env': 'ray.rllib.examples.env.stateless_cartpole.StatelessCartPole',
        'num_workers': 0,
        'burn_in': 20,
        'zero_init_states': True,
        'model':
            {
                'use_lstm': True,
                'lstm_cell_size': 64,
                'max_seq_len': 20,
                "custom_model": "custom_model",   # To make it work correctly, comment out this line
                "custom_model_config": {},
             },
}

trainer = R2D2Trainer(config=config)
policy = trainer.get_policy()
trainer.train()
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by renos** [comment]
This could help https://github.com/ray-project/ray/issues/9870

**Comment by Howuhh** [comment]
I encountered the same error when using the custom model and R2D2. How should this be solved? To be honest, issue https://github.com/ray-project/ray/issues/9870 doesn't say anything about how to solve this particular problem.

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
