### ISSUE TITLE
build from source - flatbuffers(?) error

### ISSUE THREAD

**Issue by Scitator** [ray-project/ray#2290]
Hi, 

after suggestion (https://github.com/ray-project/ray/issues/2159#issuecomment-399262267) to build from source, I am here :).

I was trying to build Ray from source on ArchLinux, but something went wrong. I think, some dependencies mismatch? Could you please provide necessary gcc (and other usual-ubuntu-stuff) versions?

build logs:
```
Created temporary directory: /tmp/pip-ephem-wheel-cache-zpsrk8ch
Created temporary directory: /tmp/pip-install-1nhlweh0
Obtaining file:///home/scitator/Documents/git/ray/python
  Running setup.py (path:/home/scitator/Documents/git/ray/python/setup.py) egg_info for package from file:///home/scitator/Documents/git/ray/python
    Running command python setup.py egg_info
    running egg_info
    writing ray.egg-info/PKG-INFO
    writing dependency_links to ray.egg-info/dependency_links.txt
    writing entry points to ray.egg-info/entry_points.txt
    writing requirements to ray.egg-info/requires.txt
    writing top-level names to ray.egg-info/top_level.txt
    reading manifest file 'ray.egg-info/SOURCES.txt'
    writing manifest file 'ray.egg-info/SOURCES.txt'
  Source in /home/scitator/Documents/git/ray/python has version 0.4.0, which satisfies requirement ray==0.4.0 from file:///home/scitator/Documents/git/ray/python
Requirement already satisfied: numpy in /home/scitator/.conda/envs/py36/lib/python3.6/site-packages (from ray==0.4.0) (1.14.3)
Requirement already satisfied: funcsigs in /home/scitator/.conda/envs/py36/lib/python3.6/site-packages (from ray==0.4.0) (1.0.2)
Requirement already satisfied: click in /home/scitator/.conda/envs/py36/lib/python3.6/site-packages (from ray==0.4.0) (6.7)
Requirement already satisfied: colorama in /home/scitator/.conda/envs/py36/lib/python3.6/site-packages (from ray==0.4.0) (0.3.9)
Requirement already satisfied: psutil in /home/scitator/.conda/envs/py36/lib/python3.6/site-packages (from ray==0.4.0) (5.4.5)
Requirement already satisfied: pytest in /home/scitator/.conda/envs/py36/lib/python3.6/site-packages (from ray==0.4.0) (3.5.1)
Requirement already satisfied: pyyaml in /home/scitator/.conda/envs/py36/lib/python3.6/site-packages (from ray==0.4.0) (3.12)
Requirement already satisfied: redis in /home/scitator/.conda/envs/py36/lib/python3.6/site-packages (from ray==0.4.0) (2.10.6)
Requirement already satisfied: six>=1.0.0 in /home/scitator/.conda/envs/py36/lib/python3.6/site-packages (from ray==0.4.0) (1.11.0)
Requirement already satisfied: flatbuffers in /home/scitator/.conda/envs/py36/lib/python3.6/site-packages (from ray==0.4.0) (2015.12.22.1)
Requirement already satisfied: py>=1.5.0 in /home/scitator/.conda/envs/py36/lib/python3.6/site-packages (from pytest->ray==0.4.0) (1.5.3)
Requirement already satisfied: setuptools in /home/scitator/.conda/envs/py36/lib/python3.6/site-packages (from pytest->ray==0.4.0) (39.1.0)
Requirement already satisfied: attrs>=17.4.0 in /home/scitator/.conda/envs/py36/lib/python3.6/site-packages (from pytest->ray==0.4.0) (18.1.0)
Requirement already satisfied: more-itertools>=4.0.0 in /home/scitator/.conda/envs/py36/lib/python3.6/site-packages (from pytest->ray==0.4.0) (4.1.0)
Requirement already satisfied: pluggy<0.7,>=0.5 in /home/scitator/.conda/envs/py36/lib/python3.6/site-packages (from pytest->ray==0.4.0) (0.6.0)
Installing collected packages: ray
  Running setup.py develop for ray
    Running command /home/scitator/.conda/envs/py36/bin/python -c "import setuptools, tokenize;__file__='/home/scitator/Documents/git/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps
    running develop
    running egg_info
    writing ray.egg-info/PKG-INFO
    writing dependency_links to ray.egg-info/dependency_links.txt
    writing entry points to ray.egg-info/entry_points.txt
    writing requirements to ray.egg-info/requires.txt
    writing top-level names to ray.egg-info/top_level.txt
    reading manifest file 'ray.egg-info/SOURCES.txt'
    writing manifest file 'ray.egg-info/SOURCES.txt'
    running build_ext
    + set -e
    +++ dirname ../build.sh
    ++ cd ..
    ++ pwd
    + ROOT_DIR=/home/scitator/Documents/git/ray
    ++ uname
    + unamestr=Linux
    + [[ Linux == \L\i\n\u\x ]]
    ++ nproc
    + PARALLEL=40
    + LANGUAGE=python
    + PYTHON_EXECUTABLE=
    + BUILD_DIR=
    + '[' '' = 1 ']'
    + CBUILD_TYPE=RelWithDebInfo
    + [[ 2 > 0 ]]
    + key=-p
    + case $key in
    + PYTHON_EXECUTABLE=/home/scitator/.conda/envs/py36/bin/python
    + shift
    + shift
    + [[ 0 > 0 ]]
    + [[ -z /home/scitator/.conda/envs/py36/bin/python ]]
    + echo 'Using Python executable /home/scitator/.conda/envs/py36/bin/python.'
    Using Python executable /home/scitator/.conda/envs/py36/bin/python.
    + bash /home/scitator/Documents/git/ray/setup_thirdparty.sh /home/scitator/.conda/envs/py36/bin/python python
    + set -e
    +++ dirname /home/scitator/Documents/git/ray/setup_thirdparty.sh
    ++ cd /home/scitator/Documents/git/ray
    ++ pwd
    + TP_DIR=/home/scitator/Documents/git/ray
    + [[ -z /home/scitator/.conda/envs/py36/bin/python ]]
    + PYTHON_EXECUTABLE=/home/scitator/.conda/envs/py36/bin/python
    + echo 'Using Python executable /home/scitator/.conda/envs/py36/bin/python.'
    Using Python executable /home/scitator/.conda/envs/py36/bin/python.
    + LANGUAGE=python
    + [[ -n python ]]
    + LANGUAGE=python
    + /home/scitator/Documents/git/ray/thirdparty/scripts/setup.sh /home/scitator/.conda/envs/py36/bin/python python
    + set -e
    +++ dirname /home/scitator/Documents/git/ray/thirdparty/scripts/setup.sh
    ++ cd /home/scitator/Documents/git/ray/thirdparty/scripts
    ++ pwd
    + TP_SCRIPT_DIR=/home/scitator/Documents/git/ray/thirdparty/scripts
    + TP_DIR=/home/scitator/Documents/git/ray/thirdparty/scripts/..
    + mkdir -p /home/scitator/Documents/git/ray/thirdparty/scripts/../build
    + mkdir -p /home/scitator/Documents/git/ray/thirdparty/scripts/../pkg
    + [[ -z /home/scitator/.conda/envs/py36/bin/python ]]
    + PYTHON_EXECUTABLE=/home/scitator/.conda/envs/py36/bin/python
    + echo 'Using Python executable /home/scitator/.conda/envs/py36/bin/python.'
    Using Python executable /home/scitator/.conda/envs/py36/bin/python.
    + LANGUAGE=python
    + [[ -n python ]]
    + LANGUAGE=python
    + echo 'Build language is python.'
    Build language is python.
    ++ uname
    + unamestr=Linux
    + bash /home/scitator/Documents/git/ray/thirdparty/scripts/build_boost.sh
    + set -e
    +++ dirname /home/scitator/Documents/git/ray/thirdparty/scripts/build_boost.sh
    ++ cd /home/scitator/Documents/git/ray/thirdparty/scripts
    ++ pwd
    + TP_DIR=/home/scitator/Documents/git/ray/thirdparty/scripts/../
    + BOOST_VERSION=1.65.1
    + BOOST_VERSION_UNDERSCORE=1_65_1
    + [[ ! -d /home/scitator/Documents/git/ray/thirdparty/scripts/..//pkg/boost ]]
    + bash /home/scitator/Documents/git/ray/thirdparty/scripts/build_redis.sh
    + set -e
    +++ dirname /home/scitator/Documents/git/ray/thirdparty/scripts/build_redis.sh
    ++ cd /home/scitator/Documents/git/ray/thirdparty/scripts
    ++ pwd
    + TP_DIR=/home/scitator/Documents/git/ray/thirdparty/scripts/../
    + '[' '!' -f /home/scitator/Documents/git/ray/thirdparty/scripts/..//pkg/redis/src/redis-server ']'
    + bash /home/scitator/Documents/git/ray/thirdparty/scripts/build_credis.sh
    + set -e
    +++ dirname /home/scitator/Documents/git/ray/thirdparty/scripts/build_credis.sh
    ++ cd /home/scitator/Documents/git/ray/thirdparty/scripts
    ++ pwd
    + TP_DIR=/home/scitator/Documents/git/ray/thirdparty/scripts/../
    + ROOT_DIR=/home/scitator/Documents/git/ray/thirdparty/scripts/..//..
    ++ uname
    + '[' Linux == Darwin ']'
    + BUILD_LEVELDB_CONFIG=-DBUILD_SHARED_LIBS=on
    + [[ '' = \o\n ]]
    + [[ Linux == \L\i\n\u\x ]]
    + echo 'building flatbuffers'
    building flatbuffers
    + bash /home/scitator/Documents/git/ray/thirdparty/scripts/build_flatbuffers.sh
    + set -e
    +++ dirname /home/scitator/Documents/git/ray/thirdparty/scripts/build_flatbuffers.sh
    ++ cd /home/scitator/Documents/git/ray/thirdparty/scripts
    ++ pwd
    + TP_DIR=/home/scitator/Documents/git/ray/thirdparty/scripts/../
    + FLATBUFFERS_VERSION=1.9.0
    + '[' '!' -d /home/scitator/Documents/git/ray/thirdparty/scripts/..//pkg/flatbuffers ']'
    + echo 'building flatbuffers'
    building flatbuffers
    + pushd /home/scitator/Documents/git/ray/thirdparty/scripts/..//build
    ~/Documents/git/ray/thirdparty/build ~/Documents/git/ray/python
    + curl -sL https://github.com/google/flatbuffers/archive/v1.9.0.tar.gz -o flatbuffers-1.9.0.tar.gz
    + tar xf flatbuffers-1.9.0.tar.gz
    + rm -rf flatbuffers-1.9.0.tar.gz
    + pushd flatbuffers-1.9.0
    ~/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0 ~/Documents/git/ray/thirdparty/build ~/Documents/git/ray/python
    + cmake -DCMAKE_CXX_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/home/scitator/Documents/git/ray/thirdparty/scripts/..//pkg/flatbuffers -DFLATBUFFERS_BUILD_TESTS=OFF
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0
    + make -j5
    [  3%] Building CXX object CMakeFiles/flatbuffers.dir/src/code_generators.cpp.o
    [  7%] Building CXX object CMakeFiles/flatbuffers.dir/src/idl_gen_text.cpp.o
    [ 10%] Building CXX object CMakeFiles/flatbuffers.dir/src/idl_parser.cpp.o
    [ 14%] Building CXX object CMakeFiles/flatc.dir/src/code_generators.cpp.o
    [ 21%] Built target flathash
    [ 25%] Building CXX object CMakeFiles/flatbuffers.dir/src/reflection.cpp.o
    In file included from /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/flexbuffers.h:24,
                     from /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/src/idl_gen_text.cpp:20:
    /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/util.h: In function ‘int flatbuffers::FromUTF8(const char**)’:
    /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/util.h:324:45: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
       if ((static_cast<const unsigned char>(**in) << len) & 0x80) return -1;  // Bit after leading 1's must be 0.
                                                 ^
    In file included from /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/flexbuffers.h:24,
                     from /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/idl.h:26,
                     from /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/code_generators.h:22,
                     from /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/src/code_generators.cpp:17:
    /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/util.h: In function ‘int flatbuffers::FromUTF8(const char**)’:
    /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/util.h:324:45: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
       if ((static_cast<const unsigned char>(**in) << len) & 0x80) return -1;  // Bit after leading 1's must be 0.
                                                 ^
    In file included from /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/flexbuffers.h:24,
                     from /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/idl.h:26,
                     from /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/code_generators.h:22,
                     from /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/src/code_generators.cpp:17:
    /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/util.h: In function ‘int flatbuffers::FromUTF8(const char**)’:
    /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/util.h:324:45: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
       if ((static_cast<const unsigned char>(**in) << len) & 0x80) return -1;  // Bit after leading 1's must be 0.
                                                 ^
    In file included from /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/src/reflection.cpp:18:
    /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/util.h: In function ‘int flatbuffers::FromUTF8(const char**)’:
    /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/util.h:324:45: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
       if ((static_cast<const unsigned char>(**in) << len) & 0x80) return -1;  // Bit after leading 1's must be 0.
                                                 ^
    In file included from /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/flexbuffers.h:24,
                     from /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/idl.h:26,
                     from /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/src/idl_parser.cpp:23:
    /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/util.h: In function ‘int flatbuffers::FromUTF8(const char**)’:
    /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/util.h:324:45: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
       if ((static_cast<const unsigned char>(**in) << len) & 0x80) return -1;  // Bit after leading 1's must be 0.
                                                 ^
    cc1plus: all warnings being treated as errors
    make[2]: *** [CMakeFiles/flatbuffers.dir/build.make:63: CMakeFiles/flatbuffers.dir/src/code_generators.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    [ 28%] Building CXX object CMakeFiles/flatc.dir/src/idl_parser.cpp.o
    cc1plus: all warnings being treated as errors
    make[2]: *** [CMakeFiles/flatc.dir/build.make:63: CMakeFiles/flatc.dir/src/code_generators.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    In file included from /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/flexbuffers.h:24,
                     from /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/idl.h:26,
                     from /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/src/idl_parser.cpp:23:
    /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/util.h: In function ‘int flatbuffers::FromUTF8(const char**)’:
    /home/scitator/Documents/git/ray/thirdparty/build/flatbuffers-1.9.0/include/flatbuffers/util.h:324:45: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
       if ((static_cast<const unsigned char>(**in) << len) & 0x80) return -1;  // Bit after leading 1's must be 0.
                                                 ^
    cc1plus: all warnings being treated as errors
    make[2]: *** [CMakeFiles/flatbuffers.dir/build.make:89: CMakeFiles/flatbuffers.dir/src/idl_gen_text.cpp.o] Error 1
    cc1plus: all warnings being treated as errors
    make[2]: *** [CMakeFiles/flatbuffers.dir/build.make:102: CMakeFiles/flatbuffers.dir/src/reflection.cpp.o] Error 1
    cc1plus: all warnings being treated as errors
    make[2]: *** [CMakeFiles/flatbuffers.dir/build.make:76: CMakeFiles/flatbuffers.dir/src/idl_parser.cpp.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:142: CMakeFiles/flatbuffers.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    cc1plus: all warnings being treated as errors
    make[2]: *** [CMakeFiles/flatc.dir/build.make:76: CMakeFiles/flatc.dir/src/idl_parser.cpp.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/flatc.dir/all] Error 2
    make: *** [Makefile:130: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/scitator/Documents/git/ray/python/setup.py", line 151, in <module>
        license="Apache 2.0")
      File "/home/scitator/.conda/envs/py36/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/home/scitator/.conda/envs/py36/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/scitator/.conda/envs/py36/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/scitator/.conda/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/scitator/.conda/envs/py36/lib/python3.6/site-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/home/scitator/.conda/envs/py36/lib/python3.6/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/home/scitator/.conda/envs/py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/scitator/.conda/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/scitator/Documents/git/ray/python/setup.py", line 76, in run
        subprocess.check_call(["../build.sh", "-p", sys.executable])
      File "/home/scitator/.conda/envs/py36/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '-p', '/home/scitator/.conda/envs/py36/bin/python']' returned non-zero exit status 2.
Cleaning up...
Exception information:
Traceback (most recent call last):
  File "/home/scitator/.conda/envs/py36/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/home/scitator/.conda/envs/py36/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/home/scitator/.conda/envs/py36/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/home/scitator/.conda/envs/py36/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 738, in install
    install_options, global_options, prefix=prefix,
  File "/home/scitator/.conda/envs/py36/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 900, in install_editable
    show_stdout=False,
  File "/home/scitator/.conda/envs/py36/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/home/scitator/.conda/envs/py36/bin/python -c "import setuptools, tokenize;__file__='/home/scitator/Documents/git/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/scitator/Documents/git/ray/python/
```

Thanks!

**Comment by raulchen** [comment]
in my docker container, gcc version is 5.4. I think any relatively new gcc version should work.

**Comment by Scitator** [comment]
closing this issue, cause with clear ubuntu 16.04 all works perfectly!

**Comment by TBastiani** [comment]
@Scitator You can work around this issue by building with `cmake -DCMAKE_CXX_FLAGS="-Wno-ignored-qualifiers" ...`

This happens because flatbuffers is built with `-Werror` and `-Wextra -pedantic` so every time someone adds a new compiler warning it can break.

http://blog.schmorp.de/2016-02-27-tidbits-for-the-love-of-god-dont-use-werror.html
