### ISSUE TITLE
[rllib] Clipping Error for PPO

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#2296]
### Describe the problem
On master, `python train.py -f tuned_examples/pendulum-ppo.yaml` fails with below error.

```
Remote function sample failed with:

Traceback (most recent call last):
  File "/data/rliaw/minconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/data/rliaw/minconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/data/rliaw/minconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: clip_value_min and clip_value_max must be either of the same shape as input, or a scalar. input shape: [1,1]clip_value_min shape: [1]clip_value_max shape: [1]
	 [[Node: clip_by_value = ClipByValue[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](add_2, add_1/x, clip_by_value/clip_value_max)]]
```

**Comment by ericl** [comment]
This seems to work for me now -- perhaps it was fixed with the latest push?

**Comment by richardliaw** [comment]
Ran this on py2 and got the same thing on master; can investigate later...

**Comment by ericl** [comment]
Haven't seen this on recent builds
