### ISSUE TITLE
[Bug] `register_serialization` not working

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#22984]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

```
import ray
import threading

class A:
    def __init__(self, x):
        self.x = x
        self.lock = threading.Lock()  # could not be serialized!

# ray.get(ray.put(A(1)))  # fail!

def custom_serializer(a):
    return a.x

def custom_deserializer(b):
    return A(b)

# Register serializer and deserializer for class A:
ray.util.register_serializer(
  A, serializer=custom_serializer, deserializer=custom_deserializer)
ray.get(ray.put(A(1)))  # success!
```

This is the example code displayed in https://docs.ray.io/en/master/ray-core/serialization.html#customized-serialization

It is supposed to succeed, but it seems like it still fails with this error

```
#error:
Traceback (most recent call last):
  File "shitty.py", line 19, in <module>
    A, serializer=custom_serializer, deserializer=custom_deserializer)
  File "/opt/conda/envs/gym-fish/lib/python3.6/site-packages/ray/util/serialization.py", line 18, in register_serializer
    context = ray.worker.global_worker.get_serialization_context()
  File "/opt/conda/envs/gym-fish/lib/python3.6/site-packages/ray/worker.py", line 217, in get_serialization_context
    with self.lock:
AttributeError: 'Worker' object has no attribute 'lock'
```

Basicallay the issue is `worker.py` requires `with self.lock`, but there's no lock attribute in a worker class. 

### Versions / Dependencies

Master

### Reproduction script

```python3
import ray
import threading

class A:
    def __init__(self, x):
        self.x = x
        self.lock = threading.Lock()  # could not be serialized!

# ray.get(ray.put(A(1)))  # fail!

def custom_serializer(a):
    return a.x

def custom_deserializer(b):
    return A(b)

# Register serializer and deserializer for class A:
ray.util.register_serializer(
  A, serializer=custom_serializer, deserializer=custom_deserializer)
ray.get(ray.put(A(1)))  # success!
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
cc @suquark can you take a look at this?

**Comment by suquark** [comment]
@rkooo567  This is because Ray is not initialized. We can either raise a more user-friendly error, or maybe we can initialize the lock in the worker early, so users can use the serializer before `ray.init()`
