### ISSUE TITLE
[autoscaler][Bug] Autoscaler randomly fails on potential race condition.

### ISSUE THREAD

**Issue by dirkweissenborn** [ray-project/ray#22999]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

We are running jobs on preemptible VMs and the autoscaler eventually fails with the following error:
```
2022-03-09 16:05:17,289 ERROR autoscaler.py:267 -- StandardAutoscaler: Error during autoscaling.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 264, in update
    self._update()
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 298, in _update
    self.load_metrics.prune_active_ips(active_ips=[
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 299, in <listcomp>
    self.provider.internal_ip(node_id)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node_provider.py", line 144, in internal_ip
    node = self._get_node(node_id)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node_provider.py", line 36, in method_with_retries
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node_provider.py", line 175, in _get_node
    instance = resource.get_instance(node_id=node_id)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node.py", line 551, in get_instance
    instance = self.resource.projects().locations().nodes().get(
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://tpu.googleapis.com/v2alpha1/projects/******/locations/europe-west4-a/nodes/ray-o
scar-ray-debug-worker-fb721449-tpu?alt=json returned "Resource 'projects/********/locations/europe-west4-a/nodes/ray-********-worker-fb721449-tpu' w
as not found". Details: "[{'@type': 'type.googleapis.com/google.rpc.ResourceInfo', 'resourceName': 'projects/********/locations/europe-west4-a/nodes/ray-********-worker-fb721449-tpu'}]">
```

I think this whole thing might be a race condition. The workers get updated here:
https://github.com/ray-project/ray/blob/ray-1.10.0/python/ray/autoscaler/_private/autoscaler.py#L291

 and then the individual instances are queried again later:
```
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 299, in <listcomp>
    self.provider.internal_ip(node_id)
```

 If a VM gets deleted in between the error occurs .

There is also something very strange that I don't understand:

The autoscaler catches the error and logs the following message:

https://github.com/ray-project/ray/blob/ray-1.10.0/python/ray/autoscaler/_private/autoscaler.py#L267

The stack trace after that indicates that we hit autoscaler max errors (=5 by default). However, I don't find any other error messages in monitor log (there should be 5, right?).  Furthermore, if the stack trace appears there should be a message: "StandardAutoscaler: Too many errors, abort." which it isn't. So where does the stack trace come from and why is the autoscaler down?

### Versions / Dependencies

1.10

### Reproduction script

None, sorry.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wuisawesome** [comment]
@dirkweissenborn let us know if you still run into the issue with ray 1.11 or master. If so, can you provide a reproduction (including the autoscaler config)

**Comment by dirkweissenborn** [comment]
This is not really fixed. Now the errors just appear in a loop. 

```
2022-03-11 14:35:33,302	ERROR autoscaler.py:267 -- StandardAutoscaler: Error during autoscaling.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 264, in update
    self._update()
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 308, in _update
    self.terminate_nodes_to_enforce_config_constraints(now)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 428, in terminate_nodes_to_enforce_config_constraints
    self.terminate_scheduled_nodes()
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 457, in terminate_scheduled_nodes
    self.provider.terminate_nodes(self.nodes_to_terminate)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/node_provider.py", line 160, in terminate_nodes
    self.terminate_node(node_id)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node_provider.py", line 36, in method_with_retries
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node_provider.py", line 163, in terminate_node
    result = resource.delete_instance(node_id=node_id, )
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node.py", line 619, in delete_instance
    operation = self.resource.projects().locations().nodes().delete(
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://tpu.googleapis.com/v2alpha1/projects/inceptive-compute/locations/europe-west4-a/nodes/ray-oscar-ray-debug2-worker-418c85e3-tpu?alt=json returned "Resource 'projects/inceptive-compute/locations/europe-west4-a/nodes/ray-oscar-ray-debug2-worker-418c85e3-tpu' was not found". Details: "[{'@type': 'type.googleapis.com/google.rpc.ResourceInfo', 'resourceName': 'projects/inceptive-compute/locations/europe-west4-a/nodes/ray-oscar-ray-debug2-worker-418c85e3-tpu'}]">
2022-03-11 14:35:33,302	CRITICAL autoscaler.py:277 -- StandardAutoscaler: Too many errors, abort.
2022-03-11 14:35:33,303	ERROR monitor.py:374 -- Monitor: Execution exception. Trying again...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/monitor.py", line 353, in _run
    self.autoscaler.update()
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 279, in update
    raise e
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 264, in update
    self._update()
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 308, in _update
    self.terminate_nodes_to_enforce_config_constraints(now)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 428, in terminate_nodes_to_enforce_config_constraints
    self.terminate_scheduled_nodes()
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 457, in terminate_scheduled_nodes
    self.provider.terminate_nodes(self.nodes_to_terminate)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/node_provider.py", line 160, in terminate_nodes
    self.terminate_node(node_id)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node_provider.py", line 36, in method_with_retries
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node_provider.py", line 163, in terminate_node
    result = resource.delete_instance(node_id=node_id, )
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node.py", line 619, in delete_instance
    operation = self.resource.projects().locations().nodes().delete(
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://tpu.googleapis.com/v2alpha1/projects/inceptive-compute/locations/europe-west4-a/nodes/ray-oscar-ray-debug2-worker-418c85e3-tpu?alt=json returned "Resource 'projects/inceptive-compute/locations/europe-west4-a/nodes/ray-oscar-ray-debug2-worker-418c85e3-tpu' was not found". Details: "[{'@type': 'type.googleapis.com/google.rpc.ResourceInfo', 'resourceName': 'projects/inceptive-compute/locations/europe-west4-a/nodes/ray-oscar-ray-debug2-worker-418c85e3-tpu'}]">
```

The issue is that some nodes get lost (are deleted) while the autoscaler still has a node-id cached that's pending some operation (here it is `terminate_scheduled_nodes`). The autoscaler still tries to apply operations on those missing nodes which leads to the 404 on request. I think this can easily be caught (properly) and node-ids should just be deleted from wherever they are cached if this happens.

**Comment by dirkweissenborn** [comment]
It seems that:
self.nodes_to_terminate is never cleaned up if there is an error here: 
```
 File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 457, in terminate_scheduled_nodes
    self.provider.terminate_nodes(self.nodes_to_terminate)
```

As a general remark, I think keeping state around in the autoscaler is really dangerous and bug prone. It would be cleaner to pass state instead. I am wondering why there is a state for self.nodes_to_terminate at all.

**Comment by DmitriGekhtman** [comment]
We should catch the 404 in the GCP Node Provider. As you've pointed out, it doesn't matter if the nodes are gone already.

You make an excellent point about cleaning up nodes_to_terminate in the event of a failure. I will push a PR to fix that.

**Comment by dirkweissenborn** [comment]
> We should catch the 404 in the GCP Node Provider. As you've pointed out, it doesn't matter if the nodes are gone already.
> 
> You make an excellent point about cleaning up nodes_to_terminate in the event of a failure. I will push a PR to fix that.

Thanks!

**Comment by dirkweissenborn** [comment]
#23182 is very similar only on another function.
