### ISSUE TITLE
Bad error message when trying to define application from local python class

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#23012]
```python
from ray import serve
from ray.serve.application import Application

class Echo:
    def __init__(self, name="world"):
        self._name = name

    def __call__(self, request):
        return f"Hello {self._name}!"

if __name__ == "__main__":
    app = Application()
    app.add_deployment(serve.deployment(Echo).options(num_replicas=2, route_prefix="/"))
    app.to_yaml("test.yaml")
```

```
(base) C02X23BRJHD3:serve eoakes$ python my_file.py
Traceback (most recent call last):
  File "my_file.py", line 14, in <module>
    app.to_yaml("test.yaml")
  File "/Users/eoakes/code/ray/python/ray/serve/application.py", line 196, in to_yaml
    deployment_dict = serve_application_to_schema(self._deployments.values()).dict()
  File "/Users/eoakes/code/ray/python/ray/serve/schema.py", line 365, in serve_application_to_schema
    schemas = [deployment_to_schema(d) for d in deployments]
  File "/Users/eoakes/code/ray/python/ray/serve/schema.py", line 365, in <listcomp>
    schemas = [deployment_to_schema(d) for d in deployments]
  File "/Users/eoakes/code/ray/python/ray/serve/schema.py", line 322, in deployment_to_schema
    return DeploymentSchema(
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for DeploymentSchema
import_path
  str type expected (type=type_error.str)
__root__
  A path to the application's class or function must be specified. (type=value_error)
```

**Comment by edoakes** [comment]
Also, looks like I can't usefully export a class to config file at all:
```python
from ray import serve
from ray.serve.application import Application

from my_file import Echo

app = Application()
app.add_deployment(serve.deployment(Echo).options(num_replicas=2, route_prefix="/"))
app.to_yaml("test.yaml")
```
