### ISSUE TITLE
Shouldn't require `PipelineInputNode` to build a pipeline DAG

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#23037]
We should probably allow building a serve dag w/o importing `PipelineInputNode` (just pass the starlette request directly through)

```python
(base) C02X23BRJHD3:serve eoakes$ python test_dag.py
2022-03-10 16:04:04,637 INFO services.py:1477 -- View the Ray dashboard at http://127.0.0.1:8266
(ServeController pid=5266) 2022-03-10 16:04:08,806      INFO checkpoint_path.py:15 -- Using RayInternalKVStore for controller checkpoint and recovery.
(ServeController pid=5266) 2022-03-10 16:04:08,910      INFO http_state.py:102 -- Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:127.0.0.1-0' on node 'node:127.0.0.1-0' listening on '127.0.0.1:8000'
2022-03-10 16:04:10,148 INFO api.py:719 -- Started detached Serve instance in namespace 'serve'.
Traceback (most recent call last):
  File "test_dag.py", line 23, in <module>
    app = build(my_dag)
  File "/Users/eoakes/code/ray/python/ray/serve/pipeline/api.py", line 68, in build
    pipeline_input_node = get_pipeline_input_node(serve_root_dag)
  File "/Users/eoakes/code/ray/python/ray/serve/pipeline/generate.py", line 165, in get_pipeline_input_node
    serve_dag_root_node.apply_recursive(extractor)
  File "/Users/eoakes/code/ray/python/ray/experimental/dag/dag_node.py", line 205, in apply_recursive
    self._apply_and_replace_all_child_nodes(
  File "/Users/eoakes/code/ray/python/ray/experimental/dag/dag_node.py", line 161, in _apply_and_replace_all_child_nodes
    replace_table[node] = fn(node)
  File "/Users/eoakes/code/ray/python/ray/experimental/dag/dag_node.py", line 206, in <lambda>
    lambda node: node.apply_recursive(fn)
  File "/Users/eoakes/code/ray/python/ray/experimental/dag/dag_node.py", line 204, in apply_recursive
    return fn(
  File "/Users/eoakes/code/ray/python/ray/experimental/dag/dag_node.py", line 191, in __call__
    self.cache[node._stable_uuid] = self.fn(node)
  File "/Users/eoakes/code/ray/python/ray/serve/pipeline/generate.py", line 159, in extractor
    raise ValueError(
ValueError: Please change Ray DAG InputNode to PipelineInputNode in order to build serve application. See docstring of PipelineInputNode for examples.
(HTTPProxyActor pid=5271) INFO:     Started server process [5271]
```

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
