### ISSUE TITLE
[pipeline] build() step looks for a running serve instance

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#23036]
```python
import ray
from ray.experimental.dag import InputNode

from ray.serve import pipeline
from ray.serve.pipeline.api import build

@ray.remote
def f():
    return "hi"

@ray.remote
class A:
    def forward(self, inp):
        return inp

with InputNode() as inp:
    a = A.bind()
    my_dag = a.forward.bind(inp)

app = build(my_dag)
```

```python
Traceback (most recent call last):
  File "test_dag.py", line 20, in <module>
    app = build(my_dag)
  File "/Users/eoakes/code/ray/python/ray/serve/pipeline/api.py", line 66, in build
    serve_root_dag = ray_dag_root_node.apply_recursive(transform_ray_dag_to_serve_dag)
  File "/Users/eoakes/code/ray/python/ray/experimental/dag/dag_node.py", line 205, in apply_recursive
    self._apply_and_replace_all_child_nodes(
  File "/Users/eoakes/code/ray/python/ray/experimental/dag/dag_node.py", line 161, in _apply_and_replace_all_child_nodes
    replace_table[node] = fn(node)
  File "/Users/eoakes/code/ray/python/ray/experimental/dag/dag_node.py", line 206, in <lambda>
    lambda node: node.apply_recursive(fn)
  File "/Users/eoakes/code/ray/python/ray/experimental/dag/dag_node.py", line 204, in apply_recursive
    return fn(
  File "/Users/eoakes/code/ray/python/ray/experimental/dag/dag_node.py", line 191, in __call__
    self.cache[node._stable_uuid] = self.fn(node)
  File "/Users/eoakes/code/ray/python/ray/serve/pipeline/generate.py", line 86, in transform_ray_dag_to_serve_dag
    return DeploymentNode(
  File "/Users/eoakes/code/ray/python/ray/serve/pipeline/deployment_node.py", line 74, in __init__
    ] = self._get_serve_deployment_handle(self._deployment, other_args_to_resolve)
  File "/Users/eoakes/code/ray/python/ray/serve/pipeline/deployment_node.py", line 119, in _get_serve_deployment_handle
    return deployment.get_handle(sync=True)
  File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 1096, in get_handle
    return internal_get_global_client().get_handle(
  File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 94, in internal_get_global_client
    return _connect()
  File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 754, in _connect
    raise RayServeException(
ray.serve.exceptions.RayServeException: There is no instance running on this Ray cluster. Please call `serve.start(detached=True) to start one.
```

**Comment by edoakes** [comment]
fixed
