### ISSUE TITLE
Not able to set deployment name or options via .options()

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#23040]
```python
import ray
from ray.experimental.dag import InputNode

from ray import serve
from ray.serve import pipeline
from ray.serve.application import Application
from ray.serve.pipeline.api import build
from ray.serve.pipeline.pipeline_input_node import PipelineInputNode

from mod import Model, get_num, combine

serve.start(detached=True)

with PipelineInputNode(get_num) as inp:
    a = Model.options(name="multiply_by_2").bind(2)
    b = Model.options(name="multiply_by_4").bind(4)
    output = combine.bind(a.forward.bind(inp), b.forward.bind(inp))

app = Application(build(output))
app.run()
```

```python
(ServeController pid=8227) 2022-03-10 16:25:11,624      INFO http_state.py:102 -- Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:127.0.0.1-0' on node 'node:127.0.0.1-0' listening on '127.0.0.1:8000'
2022-03-10 16:25:12,913 INFO api.py:719 -- Started detached Serve instance in namespace 'serve'.
2022-03-10 16:25:12,922 INFO api.py:668 -- Connecting to existing Serve instance in namespace 'serve'.
Traceback (most recent call last):
  File "test_dag.py", line 20, in <module>
    app.run()
  File "/Users/eoakes/code/ray/python/ray/serve/application.py", line 125, in run
    self.deploy()
  File "/Users/eoakes/code/ray/python/ray/serve/application.py", line 105, in deploy
    return internal_get_global_client().deploy_group(
  File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 131, in check
    return f(self, *args, **kwargs)
  File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 335, in deploy_group
    self.get_deploy_args(
  File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 131, in check
    return f(self, *args, **kwargs)
  File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 505, in get_deploy_args
    replica_config = ReplicaConfig(
  File "/Users/eoakes/code/ray/python/ray/serve/config.py", line 214, in __init__
    self._validate()
  File "/Users/eoakes/code/ray/python/ray/serve/config.py", line 238, in _validate
    raise ValueError(
ValueError: Specifying name in ray_actor_options is not allowed.
```

**Comment by edoakes** [comment]
duplicate
