### ISSUE TITLE
[core] init error on Windows 

### ISSUE THREAD

**Issue by wqh17101** [ray-project/ray#23046]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

1. on my windows `ray.init()` can not work.
2. work on windows
3. i run the script `ray.init()`
and get 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wqh\anaconda3\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\wqh\anaconda3\lib\site-packages\ray\worker.py", line 918, in init
    _global_node = ray.node.Node(
  File "C:\Users\wqh\anaconda3\lib\site-packages\ray\node.py", line 215, in __init__
    self.start_head_processes()
  File "C:\Users\wqh\anaconda3\lib\site-packages\ray\node.py", line 911, in start_head_processes
    self.start_redis()
  File "C:\Users\wqh\anaconda3\lib\site-packages\ray\node.py", line 715, in start_redis
    self.get_resource_spec(),
  File "C:\Users\wqh\anaconda3\lib\site-packages\ray\node.py", line 344, in get_resource_spec
    self._resource_spec = ResourceSpec(
  File "C:\Users\wqh\anaconda3\lib\site-packages\ray\_private\resource_spec.py", line 149, in resolve
    num_gpus = _autodetect_num_gpus()
  File "C:\Users\wqh\anaconda3\lib\site-packages\ray\_private\resource_spec.py", line 241, in _autodetect_num_gpus
    lines = subprocess.check_output(cmdargs).splitlines()[1:]
  File "C:\Users\wqh\anaconda3\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\wqh\anaconda3\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\wqh\anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\wqh\anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件
```
Then i check the func code where it raised exceptions.
`C:\Users\wqh\anaconda3\Lib\site-packages\ray_private\resource_spec.py`
```
def _autodetect_num_gpus():
    """Attempt to detect the number of GPUs on this machine.

    TODO(rkn): This currently assumes NVIDIA GPUs on Linux.
    TODO(mehrdadn): This currently does not work on macOS.
    TODO(mehrdadn): Use a better mechanism for Windows.

    Possibly useful: tensorflow.config.list_physical_devices()

    Returns:
        The number of GPUs if any were detected, otherwise 0.
    """
    result = 0
    if sys.platform.startswith("linux"):
        proc_gpus_path = "/proc/driver/nvidia/gpus"
        if os.path.isdir(proc_gpus_path):
            result = len(os.listdir(proc_gpus_path))
    elif sys.platform == "win32":
        props = "AdapterCompatibility"
        cmdargs = ["WMIC", "PATH", "Win32_VideoController", "GET", props]
        lines = subprocess.check_output(cmdargs).splitlines()[1:]
        result = len([x.rstrip() for x in lines if x.startswith(b"NVIDIA")])
    return result
```

It seems like it want to run some cmd, i run it in command line and get
`WMIC is not a command in my system`
so is there anything i need to install first?

Also i find that it will count the number of gpus by `os.environ.get("CUDA_VISIBLE_DEVICES", None)`, i think `nvidia-smi` is the righter way instead of a environ var.

### Versions / Dependencies

Ray 1.10.0
Python 3.8.8
OS Win11
Nvidia 3090
### Reproduction script

```
import ray
ray.init()
```

### Anything else

For the security , i think you should catch this exception.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by wqh17101** [comment]
keep it

**Comment by wqh17101** [comment]
fixed！. related https://github.com/fsspec/filesystem_spec/issues/928 https://github.com/modin-project/modin/issues/4298
