### ISSUE TITLE
Bad validation error message

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#23052]
```
deployments:
  - name: hello-eoakes
    import_path: models.SayHello
    route_prefix: "/eoakes"
    init_kwargs:
      name: "eoakes"
    num_replicas: 2
    ray_actor_options:
      num_cpus: 0
  - name: hello-tanmay
    import_path: models.SayHello
    route_prefix: "/tanmay"
    init_kwargs:
      name: "tanmay"
    num_replicas: 3
    ray_actor_options:
      num_cpus: 0
```

```
(base) C02X23BRJHD3:pipeline-testing eoakes$ serve run test.yaml
2022-03-10 18:30:23,098	INFO scripts.py:396 -- Deploying application in config file at test.yaml.
Traceback (most recent call last):
  File "/Users/eoakes/anaconda3/bin/serve", line 11, in <module>
    load_entry_point('ray', 'console_scripts', 'serve')()
  File "/Users/eoakes/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/eoakes/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/eoakes/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/eoakes/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/eoakes/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/eoakes/code/ray/python/ray/serve/scripts.py", line 418, in run
    _configure_runtime_env(deployment, runtime_env_updates)
  File "/Users/eoakes/code/ray/python/ray/serve/scripts.py", line 98, in _configure_runtime_env
    updates.update(current_env)
TypeError: 'NoneType' object is not iterable
```

**Comment by edoakes** [comment]
Slightly different error with serve deploy:
```
RuntimeError: Request failed with status code 500: Traceback (most recent call last):
  File "/Users/eoakes/code/ray/python/ray/dashboard/optional_utils.py", line 287, in decorator
    return await f(self, *args, **kwargs)
  File "/Users/eoakes/code/ray/python/ray/dashboard/modules/serve/serve_head.py", line 56, in put_all_deployments
    app.deploy(blocking=False)
  File "/Users/eoakes/code/ray/python/ray/serve/application.py", line 105, in deploy
    return internal_get_global_client().deploy_group(
  File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 131, in check
    return f(self, *args, **kwargs)
  File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 335, in deploy_group
    self.get_deploy_args(
  File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 131, in check
    return f(self, *args, **kwargs)
  File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 499, in get_deploy_args
    ray_actor_options["runtime_env"].setdefault(
AttributeError: 'NoneType' object has no attribute 'setdefault'
```
