### ISSUE TITLE
[Bug] Workflow docs have few typos and type issue

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/ray#23113]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

I am learning Ray workflow APIs and usage and found a few issues in master branch.  

1. typo
https://docs.ray.io/en/master/workflows/basics.html#composing-workflow-steps
```
Traceback (most recent call last):
  File "workflow.py", line 15, in <module>
    ret = add.step(get_val1.step(), 20)
NameError: name 'get_val1' is not defined
```

2. typo
https://docs.ray.io/en/master/workflows/management.html#single-workflow-management-apis
```
  File "workflow2.py", line 13
    print(workflow.resume(workflow_id="workflow_id")))
                                                     ^
SyntaxError: invalid syntax
``` 

3. type 
https://docs.ray.io/en/latest/workflows/concepts.html#steps

```
Traceback (most recent call last):
  File "workflow3.py", line 11, in <module>
    output: Workflow[int] = add.step(100, one.step())
NameError: name 'Workflow' is not defined
```

4. type
https://docs.ray.io/en/latest/workflows/concepts.html#objects
```
Traceback (most recent call last):
  File "p.py", line 10, in <module>
    def words() -> List[ray.ObjectRef]:
NameError: name 'List' is not defined
```

`import ray; from typing import List` is not imported earlier and this cell. 

### Versions / Dependencies

doc :https://docs.ray.io/en/master/workflows/package-ref.html
env:  rayproject/ray:nightly

### Reproduction script

Just follow links above and run it.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
