### ISSUE TITLE
[Dataset] Unable to read scientific notation such as '1E+05' in CSV. 

### ISSUE THREAD

**Issue by tsaoyu** [ray-project/ray#23133]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

```
import pandas as pd
from pyarrow.csv import read_csv
from ray import data


pd.read_csv("/mnt/d/Projects/fusion-platform/example/creditcard.csv")

pa = read_csv("/mnt/d/Projects/fusion-platform/example/creditcard.csv")

ds = data.read_csv("/mnt/d/Projects/fusion-platform/example/creditcard.csv")
```

Ray Dataset seems failed to read from the famous credit card fraud detection dataset. https://www.kaggle.com/mlg-ulb/creditcardfraud

While for Pandas and PyArrow (of which Ray dataset relies), the dataset can be load without any problem. 

### Versions / Dependencies

1.10.0

### Reproduction script

Download CSV from https://www.kaggle.com/mlg-ulb/creditcardfraud

Run 
```
import pandas as pd
from pyarrow.csv import read_csv
from ray import data


pd.read_csv("/mnt/d/Projects/fusion-platform/example/creditcard.csv")

pa = read_csv("/mnt/d/Projects/fusion-platform/example/creditcard.csv")

ds = data.read_csv("/mnt/d/Projects/fusion-platform/example/creditcard.csv")
```

Ray data set part will complain

```
(remote_read pid=25419) pyarrow.lib.ArrowInvalid: In CSV column #0: Row #153760: CSV conversion error to int64: invalid value '1e+05'
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
@naijoaix delegate to you to decide the priority.

**Comment by jianoaix** [comment]
We should investigate and fix this. I added it to Dataset GA list.

**Comment by jianoaix** [comment]
It looks the Dataset has no issue to read scientific notion to me. @tsaoyu 

(raycp38) jian@Jians-MacBook-Pro-16 ray % cat scinotion.csv
ID,rating,price
1,3,4
5,6,7
2,8,1e+05

>>> ray.data.read_csv("scinotion.csv").take_all()
[{'ID': 1, 'rating': 3, 'price': 4.0}, {'ID': 5, 'rating': 6, 'price': 7.0}, {'ID': 2, 'rating': 8, 'price': 100000.0}]

>>> pd.read_csv("scinotion.csv")
   ID  rating     price
0   1       3       4.0
1   5       6       7.0
2   2       8  100000.0

>>> read_csv("scinotion.csv")
pyarrow.Table
ID: int64
rating: int64
price: double
----
ID: [[1,5,2]]
rating: [[3,6,8]]
price: [[4,7,100000]]

**Comment by tsaoyu** [comment]
Your mock example does works. But I don't think it is strong enough and still fails on credit card csv as mentioned in dogfood issue https://github.com/ray-project/ray/issues/23448 . I noticed that such notation (1e+05) appears only once in the index column "Time", is there any chance that the logic to recognise the schema of the whole CSV is from the only chunk of the data? Attached error message:

```
2022-04-20 09:07:26,897 INFO services.py:1412 -- View the Ray dashboard at http://127.0.0.1:8265
(remote_read pid=5257) 2022-04-20 09:07:29,462  INFO worker.py:430 -- Task failed with retryable exception: TaskID(e0dc174c83599034ffffffffffffffffffffffff01000000).
(remote_read pid=5257) Traceback (most recent call last):
(remote_read pid=5257)   File "python/ray/_raylet.pyx", line 640, in ray._raylet.execute_task
(remote_read pid=5257)   File "python/ray/_raylet.pyx", line 644, in ray._raylet.execute_task
(remote_read pid=5257)   File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/read_api.py", line 178, in remote_read
(remote_read pid=5257)     block = task()
(remote_read pid=5257)   File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/datasource/datasource.py", line 142, in __call__
(remote_read pid=5257)     for block in result:
(remote_read pid=5257)   File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/datasource/file_based_datasource.py", line 150, in read_files
(remote_read pid=5257)     for data in read_stream(f, read_path, **reader_args):
(remote_read pid=5257)   File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/datasource/csv_datasource.py", line 31, in _read_stream
(remote_read pid=5257)     batch = reader.read_next_batch()
(remote_read pid=5257)   File "pyarrow/ipc.pxi", line 596, in pyarrow.lib.RecordBatchReader.read_next_batch
(remote_read pid=5257)   File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
(remote_read pid=5257) pyarrow.lib.ArrowInvalid: In CSV column #0: Row #153760: CSV conversion error to int64: invalid value '1e+05'
(remote_read pid=5257) 2022-04-20 09:07:30,162  INFO worker.py:430 -- Task failed with retryable exception: TaskID(e0dc174c83599034ffffffffffffffffffffffff01000000).
(remote_read pid=5257) Traceback (most recent call last):
(remote_read pid=5257)   File "python/ray/_raylet.pyx", line 640, in ray._raylet.execute_task
(remote_read pid=5257)   File "python/ray/_raylet.pyx", line 644, in ray._raylet.execute_task
(remote_read pid=5257)   File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/read_api.py", line 178, in remote_read
(remote_read pid=5257)     block = task()
(remote_read pid=5257)   File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/datasource/datasource.py", line 142, in __call__
(remote_read pid=5257)     for block in result:
(remote_read pid=5257)   File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/datasource/file_based_datasource.py", line 150, in read_files
(remote_read pid=5257)     for data in read_stream(f, read_path, **reader_args):
(remote_read pid=5257)   File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/datasource/csv_datasource.py", line 31, in _read_stream
(remote_read pid=5257)     batch = reader.read_next_batch()
(remote_read pid=5257)   File "pyarrow/ipc.pxi", line 596, in pyarrow.lib.RecordBatchReader.read_next_batch
(remote_read pid=5257)   File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
(remote_read pid=5257) pyarrow.lib.ArrowInvalid: In CSV column #0: Row #153760: CSV conversion error to int64: invalid value '1e+05'
(remote_read pid=5257) 2022-04-20 09:07:31,156  INFO worker.py:430 -- Task failed with retryable exception: TaskID(e0dc174c83599034ffffffffffffffffffffffff01000000).
(remote_read pid=5257) Traceback (most recent call last):
(remote_read pid=5257)   File "python/ray/_raylet.pyx", line 640, in ray._raylet.execute_task
(remote_read pid=5257)   File "python/ray/_raylet.pyx", line 644, in ray._raylet.execute_task
(remote_read pid=5257)   File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/read_api.py", line 178, in remote_read
(remote_read pid=5257)     block = task()
(remote_read pid=5257)   File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/datasource/datasource.py", line 142, in __call__
(remote_read pid=5257)     for block in result:
(remote_read pid=5257)   File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/datasource/file_based_datasource.py", line 150, in read_files
(remote_read pid=5257)     for data in read_stream(f, read_path, **reader_args):
(remote_read pid=5257)   File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/datasource/csv_datasource.py", line 31, in _read_stream
(remote_read pid=5257)     batch = reader.read_next_batch()
(remote_read pid=5257)   File "pyarrow/ipc.pxi", line 596, in pyarrow.lib.RecordBatchReader.read_next_batch
(remote_read pid=5257)   File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
(remote_read pid=5257) pyarrow.lib.ArrowInvalid: In CSV column #0: Row #153760: CSV conversion error to int64: invalid value '1e+05'
Traceback (most recent call last):
  File "fusion_read_csv.py", line 3, in <module>
    ds = data.read_csv("/mnt/d/Projects/fusion-platform/example/creditcard.csv")
  File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/read_api.py", line 387, in read_csv
    return read_datasource(
  File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/read_api.py", line 225, in read_datasource
    block_list.ensure_schema_for_first_block()
  File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/impl/block_list.py", line 156, in ensure_schema_for_first_block
    schema = ray.get(get_schema.remote(block))
  File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/worker.py", line 1763, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ArrowInvalid): ray::_get_schema() (pid=5257, ip=172.23.246.164)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::remote_read() (pid=5257, ip=172.23.246.164)
  File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/read_api.py", line 178, in remote_read
    block = task()
  File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/datasource/datasource.py", line 142, in __call__
    for block in result:
  File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/datasource/file_based_datasource.py", line 150, in read_files
    for data in read_stream(f, read_path, **reader_args):
  File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/datasource/csv_datasource.py", line 31, in _read_stream
    batch = reader.read_next_batch()
  File "pyarrow/ipc.pxi", line 596, in pyarrow.lib.RecordBatchReader.read_next_batch
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: In CSV column #0: Row #153760: CSV conversion error to int64: invalid value '1e+05'
(remote_read pid=5257) 2022-04-20 09:07:32,157  INFO worker.py:430 -- Task failed with retryable exception: TaskID(e0dc174c83599034ffffffffffffffffffffffff01000000).
(remote_read pid=5257) Traceback (most recent call last):
(remote_read pid=5257)   File "python/ray/_raylet.pyx", line 640, in ray._raylet.execute_task
(remote_read pid=5257)   File "python/ray/_raylet.pyx", line 644, in ray._raylet.execute_task
(remote_read pid=5257)   File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/read_api.py", line 178, in remote_read
(remote_read pid=5257)     block = task()
(remote_read pid=5257)   File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/datasource/datasource.py", line 142, in __call__
(remote_read pid=5257)     for block in result:
(remote_read pid=5257)   File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/datasource/file_based_datasource.py", line 150, in read_files
(remote_read pid=5257)     for data in read_stream(f, read_path, **reader_args):
(remote_read pid=5257)   File "/home/yu/anaconda3/envs/dev/lib/python3.8/site-packages/ray/data/datasource/csv_datasource.py", line 31, in _read_stream
(remote_read pid=5257)     batch = reader.read_next_batch()
(remote_read pid=5257)   File "pyarrow/ipc.pxi", line 596, in pyarrow.lib.RecordBatchReader.read_next_batch
(remote_read pid=5257)   File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
(remote_read pid=5257) pyarrow.lib.ArrowInvalid: In CSV column #0: Row #153760: CSV conversion error to int64: invalid value '1e+05
```

**Comment by jianoaix** [comment]
For dataset, although we take its schema from one block, here it has just a single block given this is only one file. So I think the issue is in pyarrow where it process the reading in batches.
This can actually be confirmed this way: for example, for the [UCI_Credit_Card.csv](https://github.com/ray-project/ray/files/8338068/UCI_Credit_Card.csv), if scientific notation for a column is in the first 11,108 rows (size of the first batch), it will not have this issue; otherwise it has this error.

**Comment by tsaoyu** [comment]
This explanation make sense to me. 
Another point I want to bring is that if there is a data corruption (in between CSV batches) what will happend? CSV is in the wild and it is harder to deal with compared to Parquet and ORC.

**Comment by jianoaix** [comment]
The batch reading should not corrupt data. If data in CSV is already corrupted, I think it'd be similar to this error, i.e. it cannot parse it to the type it expects.

**Comment by jianoaix** [comment]
To summarize
- Issue: The batch reading of PyArrow infers the types of each column in the first batch and uses that as the schema to read/parse following batches. Scientific notation is inferred as double while the normal notation is as int64. When all numbers in first batch are normal notation and then followed by scientific notation in batches later, it will use int64 (instead of double) to parse scientific notation, so erroring out.
- Mitigations: 
  1) set the [ReadOptions.block_size](https://arrow.apache.org/docs/python/generated/pyarrow.csv.ReadOptions.html#pyarrow.csv.ReadOptions.block_size) large enough so it can see all formats in first batch;
  2) set [ConvertOptions.column_types](https://arrow.apache.org/docs/python/generated/pyarrow.csv.ConvertOptions.html#pyarrow.csv.ConvertOptions.column_types) to explicitly specify the type of a column (PyArrow then won't try to infer the type).
