### ISSUE TITLE
[runtime_env][Bug] Runtime envs `py_modules` doesn't support local Python modules

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#23151]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

If I create a Python module `module.py` and specify that module in my runtime environment, I receive an error. My workaround is to use `working_dir` instead (even though I only needed one module). 

See "Reproduction script" for tracebacks. 

### Versions / Dependencies

**Python**: Python 3.7.7
**Ray**: 1.11
**OS**: Ubuntu 18.04

### Reproduction script

Create an empty module `module.py`.

### Issue 1
```
import ray
 
ray.init("auto", runtime_env=dict(py_modules=["module"]))
```

```
Traceback (most recent call last):
  File "repro.py", line 4, in <module>
    ray.init("auto", runtime_env=dict(py_modules=["module.py"]))
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/ray/worker.py", line 1110, in init
    job_config=job_config,
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/ray/worker.py", line 1662, in connect
    runtime_env, scratch_dir, logger=logger
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/ray/_private/runtime_env/py_modules.py", line 84, in upload_py_modules_if_needed
    module_uri = get_uri_for_directory(module_path, excludes=excludes)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/ray/_private/runtime_env/packaging.py", line 334, in get_uri_for_directory
    raise ValueError(f"directory {directory} must be an existing" " directory")
ValueError: directory /home/ubuntu/module.py must be an existing directory
```

### Issue 2 
```
import ray
 
import module
 
ray.init("auto", runtime_env=dict(py_modules=[module]))
```

```
Traceback (most recent call last):
  File "repro.py", line 6, in <module>
    ray.init("auto", runtime_env=dict(py_modules=[module]))
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/ray/worker.py", line 1110, in init
    job_config=job_config,
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/ray/worker.py", line 1662, in connect
    runtime_env, scratch_dir, logger=logger
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/ray/_private/runtime_env/py_modules.py", line 68, in upload_py_modules_if_needed
    if len(module.__path__) > 1:
AttributeError: module 'module' has no attribute '__path__'
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by tbabej** [comment]
I can confirm we are also hitting this issue (the second case, supporting first one is not something I would expect).

**Comment by goswamig** [comment]
hitting this same issue with [Using Ray Client to connect from outside the Kubernetes cluster](https://docs.ray.io/en/latest/cluster/kubernetes.html#using-ray-client-to-connect-from-outside-the-kubernetes-cluster)

**Comment by damdaepark** [comment]
hitting the same issue

**Comment by albenoit** [comment]
Hi, 
**if** your "module" is actually a custom script placed in a given folder 'module_path'. For instance, say that "module" is actually the script _module.py_ that is located in the current working directory that you can retreive with something like this.
```
import os
module_path=os.getcwd()
```
Then, a basic workaround is to consider the code of issue 2 but add a __path__ behavior to the _module_ : 
```
import ray
 
import module

import os
module_path=os.getcwd()

module.__path__=module_path
ray.init("auto", runtime_env=dict(py_modules=[module]))

```
This worked on my test case... however,not really happy with the method, improvements welcome !

**Comment by rynewang** [comment]
So about this issue:

Python modules can have 0, 1 or more __path__ entries.

- 0 __path__: it's a single file module, like `my_module.py`
- 1 __path__: it's a normal directory module, a dir with `__init__.py` and other subdirs and files. `py_modules` already supports this.
- multiple __path__: this is [python namespace package](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/), which is not normal and we should not support this (unless an explicit ask).

So TODO: support single file modules.

Now, in [py_modules.py](https://github.com/ray-project/ray/blob/f8dec041056e1366e7bf788066abb74473a0b2b6/python/ray/_private/runtime_env/py_modules.py#L78), we only support `1 __path__` case. We should support the `0 __path__` code:

```
if module is ModuleType:
    if module has attr __path__:
        expect len(path) is 1 or raise
        prepare the dir to upload...
    else:
        expect module has attr __file__ or (raise, should not have such case)
        prepare the file __file__ to upload...
```
        
@MortalHappiness please take a look at this and try to solve this
