### ISSUE TITLE
[Train] Print actionable error message when CUDA object returned from training function

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#23159]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Provide a clear and actionable error message when the user returns an object on CUDA from the training function

### Use case

If you return an object on CUDA from your training function, you receive a lengthy and unactionable error message.

```
E                       ray.exceptions.RayTaskError: ray::BackendExecutor.finish_training() (pid=102685, ip=10.0.2.157, repr=<ray.train.backend.BackendExecutor object at 0x7fdcade14890>)
E                         File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/train/backend.py", line 537, in finish_training
E                           results = self.get_with_failure_handling(futures)
E                         File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/train/backend.py", line 556, in get_with_failure_handling
E                           success, failed_worker_indexes = check_for_failure(remote_values)
E                         File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/train/utils.py", line 40, in check_for_failure
E                           ray.get(object_ref)
E                       ray.exceptions.RaySystemError: System error: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
E                       traceback: Traceback (most recent call last):
E                         File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 332, in deserialize_objects
E                           obj = self._deserialize_object(data, metadata, object_ref)
E                         File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 235, in _deserialize_object
E                           return self._deserialize_msgpack_data(data, metadata_fields)
E                         File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 190, in _deserialize_msgpack_data
E                           python_objects = self._deserialize_pickle5_data(pickle5_data)
E                         File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 180, in _deserialize_pickle5_data
E                           obj = pickle.loads(in_band)
E                         File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/storage.py", line 181, in _load_from_bytes
E                           return torch.load(io.BytesIO(b))
E                         File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 713, in load
E                           return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
E                         File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 930, in _legacy_load
E                           result = unpickler.load()
E                         File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 876, in persistent_load
E                           wrap_storage=restore_location(obj, location),
E                         File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 176, in default_restore_location
E                           result = fn(storage, location)
E                         File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 152, in _cuda_deserialize
E                           device = validate_cuda_device(location)
E                         File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 136, in validate_cuda_device
E                           raise RuntimeError('Attempting to deserialize object on a CUDA '
E                       RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

../anaconda3/lib/python3.7/site-packages/ray/worker.py:1917: RayTaskError
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by bveeramani** [comment]
To implement this, you could call [`TorchBackend.decode_data`](https://github.com/ray-project/ray/blob/ray-1.11.0/python/ray/train/torch.py#L166) on the function output in [`session.finish`](https://github.com/ray-project/ray/blob/ray-1.11.0/python/ray/train/session.py#L93). 

There was discussion about implementing this functionality in https://github.com/ray-project/ray/pull/20333#issue-1052801079.

**Comment by bveeramani** [comment]
Closing because you don't return values from training functions anymore
