### ISSUE TITLE
[updater][Bug] update fails on preempted node and autoscaler stops scheduling

### ISSUE THREAD

**Issue by oscartackstrom** [ray-project/ray#23182]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

1. I'm running a parallel ML training workflow with preemptible TPUs on GCP. It looks like one of the workers is preempted during the update stage. An exception is logged multiple times and eventually all workers are down and the autoscaler stops rescheduling them. I believe the issue is that NodeUpdater.run assumes that the worker will be up for the duration of the update and fails when this assumption does not hold.
2. I expect the ray autoscaler to cope with workers dying or being preempted at any time and just try to acquire new resources when this happens.
3. Below is a stack trace from monitor.log:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/updater.py", line 166,
 in run
    self.provider.set_node_tags(self.node_id, tags_to_set)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node_provider.py",
 line 36, in method_with_retries
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node_provider.py",
 line 123, in set_node_tags
    result = resource.set_labels(node=node, labels=labels)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node.py", line 74,
 in wrapper
    ret = try_catch_exc()
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node.py", line 70,
 in try_catch_exc
    raise e
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node.py", line 65,
 in try_catch_exc
    value = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node.py", line 568
, in set_labels
    operation = self.resource.projects().locations().nodes().patch(
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/_helpers.py", line 131, in pos
itional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://tpu.googleapis.com/v
2alpha1/projects/*******/locations/europe-west4-a/nodes/ray-*******-worker
-2209d0a2-tpu?updateMask=labels&alt=json returned "Cloud TPU received a bad request. update i
s not supported while in state PREEMPTED [EID: 0xe30ce60fc44aafc3]". Details: "Cloud TPU rece
ived a bad request. update is not supported while in state PREEMPTED [EID: 0xe30ce60fc44aafc3
]">
```

### Versions / Dependencies

Ray 1.11, Python 3.8, Ubuntu

### Reproduction script

n/a but any script that triggers update on a worker that is being preempted should work

### Anything else

This occurs whenever workers are preempted during the update phase, which is common when running large training sweeps.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by oscartackstrom** [comment]
I believe the underlying issue is related to https://github.com/ray-project/ray/issues/22999

**Comment by oscartackstrom** [comment]
FYI, we tried patching ray to catch this error and move on, but then we get these errors instead:
```
==> /tmp/ray/session_latest/logs/monitor.err <==
Exception in thread Thread-69:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/updater.py", line 134, in run
    self.do_update()
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/updater.py", line 299, in do_update
    self.wait_ready(deadline)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/updater.py", line 250, in wait_ready
    raise Exception("wait_ready aborting because node "
Exception: wait_ready aborting because node detected as terminated.
2022-03-16 11:10:31,646	WARNING node_provider.py:126 -- Couldn't set labels for node: projects/inceptive-compute/locations/europe-west4-a/nodes/ray-oscar-bert-sweep-worker-bf94b7ce-tpu. Continuing.
2022-03-16 11:10:31,647	ERR updater.py:138 -- New status: update-failed
2022-03-16 11:10:31,647	ERR updater.py:140 -- !!!
2022-03-16 11:10:31,647	VERR updater.py:146 -- {}
2022-03-16 11:10:31,647	ERR updater.py:148 -- wait_ready aborting because node detected as terminated.
2022-03-16 11:10:31,647	ERR updater.py:150 -- !!!
```
and
```
Exception in thread Thread-56:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/updater.py", line 134, in run
    self.do_update()
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/updater.py", line 299, in do_update
    self.wait_ready(deadline)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/updater.py", line 248, in wait_ready
    raise Exception("wait_ready timeout exceeded.")
Exception: wait_ready timeout exceeded.
...
2022-03-16 11:13:07,685	ERR updater.py:138 -- New status: update-failed
2022-03-16 11:13:07,686	ERR updater.py:140 -- !!!
2022-03-16 11:13:07,686	VERR updater.py:146 -- {}
2022-03-16 11:13:07,686	ERR updater.py:148 -- wait_ready timeout exceeded.
2022-03-16 11:13:07,686	ERR updater.py:150 -- !!!
```
and again it never tries to reschedule the tasks that was running on these failed nodes.

**Comment by dirkweissenborn** [comment]
It seems that this happens when attempting to recover a preempted node. Upon recovery attempt the updater thread should just ignore exceptions and move on.

**Comment by dirkweissenborn** [comment]
On a more general note: Looking through all the code it seems to me that fault tolerance of the autoscaler should be reworked. Error handling in general is very intransparent and inconsistent. There are also loads of side-effects which makes it very hard to reason about the code. I think that should be reduced to a bare minimum if possible.

**Comment by DmitriGekhtman** [comment]
Is it possible that there was no spot availability at all at the time that this happened?
All of these failures are from NodeUpdater child threads, so it seems unlikely (but possible) that the main autoscaler thread was interrupted.
We'd expect spot instance preemption to cause a traceback in one of these threads.
I agree that the error handling is opaque.

**Comment by dirkweissenborn** [comment]
Typically you would see a clear message when availability is the issue.
That wasn't the case here.

**Comment by DmitriGekhtman** [comment]
I agree.
For the first stack trace, the "PREEMPTED" from the cloud provider at least eventually came out.
However, it was entirely unclear from the stack trace that the error was non-fatal.

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
