### ISSUE TITLE
[ml][Improvement] serve dependency should not leak into dashboard and leak into other ray libraries.

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#23309]

**Comment by amogkam** [comment]
Stack trace when starting up Ray cluster

```
2022-03-21 18:34:44,937	ERROR services.py:1474 -- Failed to start the dashboard: Failed to start the dashboard, return code 1
 The last 10 lines of /tmp/ray/session_2022-03-21_18-34-43_072051_5093/logs/dashboard.log:
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/dashboard/optional_utils.py", line 21, in <module>
    from ray import serve
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/serve/__init__.py", line 20, in <module>
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/serve/__init__.py", line 2, in <module>
    from ray.serve.api import (
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/serve/api.py", line 28, in <module>
    from fastapi import APIRouter, FastAPI
ModuleNotFoundError: No module named 'fastapi'. You can run `pip install "ray[serve]"` to install all Ray Serve dependencies.
2022-03-21 18:34:44,938	ERROR services.py:1475 -- Failed to start the dashboard, return code 1
 The last 10 lines of /tmp/ray/session_2022-03-21_18-34-43_072051_5093/logs/dashboard.log:
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/dashboard/optional_utils.py", line 21, in <module>
    from ray import serve
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/serve/__init__.py", line 20, in <module>
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/serve/__init__.py", line 2, in <module>
    from ray.serve.api import (
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/serve/api.py", line 28, in <module>
    from fastapi import APIRouter, FastAPI
ModuleNotFoundError: No module named 'fastapi'. You can run `pip install "ray[serve]"` to install all Ray Serve dependencies.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 1451, in start_dashboard
    raise Exception(err_msg + last_log_str)
Exception: Failed to start the dashboard, return code 1
 The last 10 lines of /tmp/ray/session_2022-03-21_18-34-43_072051_5093/logs/dashboard.log:
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/dashboard/optional_utils.py", line 21, in <module>
    from ray import serve
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/serve/__init__.py", line 20, in <module>
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/serve/__init__.py", line 2, in <module>
    from ray.serve.api import (
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/serve/api.py", line 28, in <module>
    from fastapi import APIRouter, FastAPI
ModuleNotFoundError: No module named 'fastapi'. You can run `pip install "ray[serve]"` to install all Ray Serve dependencies.
```

**Comment by amogkam** [comment]
Full dashboard logs 

```
2022-03-21 18:34:44,637	INFO head.py:122 -- Dashboard head grpc address: 0.0.0.0:43433
2022-03-21 18:34:44,640	INFO utils.py:99 -- Get all modules by type: DashboardHeadModule
2022-03-21 18:34:44,728	INFO utils.py:111 -- Module ray.dashboard.modules.actor.actor_head cannot be loaded because we cannot import all dependencies. Download `pip install ray[default]` for the full dashboard functionality. Error: No module named 'fastapi'. You can run `pip install "ray[serve]"` to install all Ray Serve dependencies.
2022-03-21 18:34:44,729	INFO utils.py:118 -- Although `pip install ray[default] is downloaded, module couldn't be imported`
2022-03-21 18:34:44,849	ERROR dashboard.py:189 -- The dashboard on node ip-10-0-2-64 failed with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 178, in <module>
    loop.run_until_complete(dashboard.run())
  File "/home/ubuntu/anaconda3/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 61, in run
    await self.dashboard_head.run()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/dashboard/head.py", line 221, in run
    modules = self._load_modules()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/dashboard/head.py", line 180, in _load_modules
    dashboard_utils.DashboardHeadModule
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/dashboard/utils.py", line 121, in get_all_modules
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/dashboard/utils.py", line 108, in get_all_modules
    importlib.import_module(name)
  File "/home/ubuntu/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/actor/actor_head.py", line 14, in <module>
    import ray.dashboard.optional_utils as dashboard_optional_utils
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/dashboard/optional_utils.py", line 21, in <module>
    from ray import serve
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/serve/__init__.py", line 20, in <module>
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/serve/__init__.py", line 2, in <module>
    from ray.serve.api import (
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/serve/api.py", line 28, in <module>
    from fastapi import APIRouter, FastAPI
ModuleNotFoundError: No module named 'fastapi'. You can run `pip install "ray[serve]"` to install all Ray Serve dependencies.
```

**Comment by amogkam** [comment]
You can repro by starting a cluster with these setup commands

```
- pip install -U ray==1.10.0
- ray install-nightly
- pip install ray[default]
```

**Comment by richardliaw** [comment]
@ray-project/ray-serve can you take a look ?

**Comment by richardliaw** [comment]
Also @amogkam does this happen on master?

**Comment by amogkam** [comment]
Yep this is on master (using `ray install-nightly`).

**Comment by amogkam** [comment]
I think we might want to make this a 1.12 release blocker @edoakes?

**Comment by edoakes** [comment]
Yes we should make it a 1.12 release blocker.

@shrekris-anyscale can you please take this? I think we just need to do some delayed/optional imports and error in the endpoints if serve isn't installed.

I think @rkooo567 can provide context on it if you're stuck.

**Comment by edoakes** [comment]
We should also have a test for this in CI

**Comment by shrekris-anyscale** [comment]
Yep, I can look into this.

**Comment by simon-mo** [comment]
@shrekris-anyscale the issue seems to be that serve is rethrowing `ModuleNotFoundError` while `optional_utils` is expecting `ImportError`. A low risk change would be just change the ModuleNotFoundError to ImportError and change corresponding test

**Comment by amogkam** [comment]
wait @simon-mo doesn't `ModuleNotFoundError` subclass `ImportError`? So it should still be caught in any `ImportError` except block?

**Comment by zhe-thoughts** [comment]
@richardliaw @edoakes This is P0 right?

**Comment by zhe-thoughts** [comment]
@simon-mo : by closing the issue, do you mean the PR has been picked to the rc1 branch? Thanks

I think the bottom line is we should always have an open issue/PR with `release-blocker` label for something that is a blocker

**Comment by simon-mo** [comment]
No sorry this is automatically closed as part of closing PRs. @edoakes will proceed with TL approval tomorrow.

**Comment by zhe-thoughts** [comment]
Actually in cases like this we can either keep the original issue open, or create a separate cherry-pick issue/PR. @simon-mo curious about your feedback: which way is better?

**Comment by simon-mo** [comment]
Definitely separate PRs because they are targeting different branches. For issues either works but if there is already a PR there doesn't need to be a matching issue (seems duplicated).

**Comment by edoakes** [comment]
@zhe-thoughts @jianoaix we should cherry-pick https://github.com/ray-project/ray/pull/23389 to the release branch. I can make a cherry-pick PR if you'd like (I tried just now but GitHub appears to be having an outage 😢 )

**Comment by jianoaix** [comment]
Ok, please add this cherry pick to release tracker: https://docs.google.com/spreadsheets/d/1fkOvrLGuaKLDuBwgsArwzjV0zuWpjS6DEs9HiKsWZ3Q/edit#gid=0

**Comment by zhe-thoughts** [comment]
@jianoaix @edoakes Do you know the necessary fix has already been picked into rc1? Do we need to keep this issue open? Thanks

**Comment by jianoaix** [comment]
Yes, this PR is cherry picked: https://github.com/ray-project/ray/pull/23389

**Comment by zhe-thoughts** [comment]
SG, closing this issue. @edoakes Please reopen if you think it's still needed
