### ISSUE TITLE
[Bug] `MLfLowLoggerCallback` is not possible to deepcopy

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#23330]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

`MLflowLoggerCallback` uses `MLflowLoggerUtil`, which has `mlflow` module as an attribute. This makes it unserializable, causing it to fail with AIR Tuner.

```python
class MLflowLoggerUtil:
    """Util class for setting up and logging to MLflow.

    Use this util for any library that needs MLflow logging/tracking logic
    such as Ray Tune or Ray Train.
    """

    def __init__(self):
        import mlflow

        self._mlflow = mlflow
        self.experiment_id = None
```

```
2022-03-18 14:35:22,925 ERROR ray_trial_executor.py:102 -- An exception occurred when trying to stop the Ray actor:Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/tune/ray_trial_executor.py", line 93, in post_stop_cleanup
    ray.get(future, timeout=0)
  File "/home/ubuntu/ray/python/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/ray/python/ray/worker.py", line 1801, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::TrainTrainable.__init__() (pid=1064351, ip=172.31.43.110, repr=train_func)
  File "/home/ubuntu/ray/python/ray/ml/trainer.py", line 292, in __init__
    self._merged_config = merge_dicts(base_config, self.config)
  File "/home/ubuntu/ray/python/ray/util/ml_utils/dict.py", line 18, in merge_dicts
    merged = copy.deepcopy(d1)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'module' object
```

The solution would be to just import the module at the top of the file, or make it a dynamic property if it has to be an attribute (not sure why it should, though.)

### Versions / Dependencies

3836333aac09bb238ea848bd2d9d29314aaf383d

### Reproduction script

https://gist.github.com/Yard1/83384428948356f4c316c07818f8249b

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Yard1** [comment]
@amogkam tagging you as the author of the file

**Comment by amogkam** [comment]
Ah yes this is a good point! I don’t think we need to enforce that callbacks be serializable, after all they are just needed on the driver anyways. I think the solution we want here is to automatically remove the run config from param space? We can also override __reduce__ method of callbacks to raise a better error message, like we did for Predictors. cc @krfricke @xwjiang2010 @matthewdeng

**Comment by amogkam** [comment]
For ray client, shouldn’t callbacks be run on the laptop (and not on the head node)?

**Comment by Yard1** [comment]
If you take a look at either the Tuner or tune.run, all the kwargs are passed to a remote function running the Tuner/tune.run, including callbacks. I just tried it and doesn't seem to cause issues with `MLFlowLoggerCallback`, so it could be a deepcopy only thing. Still, no reason not to fix it :) I can make a PR for this

**Comment by amogkam** [comment]
I understand that’s how it works, but I don’t think that’s the behavior we want.

**Comment by Yard1** [comment]
I feel like this is a separate discussion to be had. I do agree that's how it should work. But in the meantime, this is an easy fix that will unblock using MLFlow with AIR in the meantime.
