### ISSUE TITLE
Cannot prescribe object_store_memory in ray.init()

### ISSUE THREAD

**Issue by chunweiyuan** [ray-project/ray#2333]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  MacBook Pro with macOS High Sierra (10.13.5).  3.1 GHz Intel Core i5 with 8G memory.
- **Ray installed from (source or binary)**:  `pip install ray`
- **Ray version**:  0.4.0
- **Python version**:  3.6.5
- **Exact command to reproduce**:
import ray
ray.init(object_store_memory=2e9)

### Describe the problem

Trying to figure out how to run ray on my laptop.  If I call `ray.init()` without any argument, there doesn't seem to be any problem:

```
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:44:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init()
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:49217 to respond...
Waiting for redis server at 127.0.0.1:10947 to respond...
Starting local scheduler with the following resources: {'CPU': 4, 'GPU': 0}.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui66737.ipynb?token=2401488f6bb085b730afb2d5d0158109f69968796230fed6
======================================================================

{'node_ip_address': '127.0.0.1', 'redis_address': '127.0.0.1:49217', 'object_store_addresses': [ObjectStoreAddress(name='/tmp/plasma_store98068210', manager_name='/tmp/plasma_manager61028623', manager_port=60612)], 'local_scheduler_socket_names': ['/tmp/scheduler45062309'], 'webui_url': 'http://localhost:8888/notebooks/ray_ui66737.ipynb?token=2401488f6bb085b730afb2d5d0158109f69968796230fed6'}
```

However, if I want to limit the amount of memory to be used, I get the following:
```
>>> import ray
>>> ray.init(object_store_memory=2e9)
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:64084 to respond...
Waiting for redis server at 127.0.0.1:30678 to respond...
Starting local scheduler with the following resources: {'CPU': 4, 'GPU': 0}.
Connection to IPC socket failed for pathname /tmp/plasma_store63511860, retrying 50 more times
Connection to IPC socket failed for pathname /tmp/plasma_store63511860, retrying 49 more times
Connection to IPC socket failed for pathname /tmp/plasma_store63511860, retrying 48 more times

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui56797.ipynb?token=b808226edac04553f12e99e7955fce4b6a93f9cd807c990c
======================================================================

Connection to IPC socket failed for pathname /tmp/plasma_store63511860, retrying 50 more times
.
.
.
Connection to IPC socket failed for pathname /tmp/plasma_store63511860, retrying 5 more times
Connection to IPC socket failed for pathname /tmp/plasma_store63511860, retrying 2 more times
Connection to IPC socket failed for pathname /tmp/plasma_store63511860, retrying 4 more times
Connection to IPC socket failed for pathname /tmp/plasma_store63511860, retrying 1 more times
Connection to IPC socket failed for pathname /tmp/plasma_store63511860, retrying 3 more times
/Users/rkn/Workspace/ray/src/local_scheduler/local_scheduler.cc:374 Check failed: _s.ok() Bad status: IOError: Could not connect to socket /tmp/plasma_store63511860
Connection to IPC socket failed for pathname /tmp/plasma_store63511860, retrying 2 more times
Connection to IPC socket failed for pathname /tmp/plasma_store63511860, retrying 1 more times
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cwyuan/anaconda/envs/venv/lib/python3.6/site-packages/ray/worker.py", line 1543, in init
    object_store_memory=object_store_memory)
  File "/Users/cwyuan/anaconda/envs/venv/lib/python3.6/site-packages/ray/worker.py", line 1463, in _init
    mode=driver_mode, worker=global_worker)
  File "/Users/cwyuan/anaconda/envs/venv/lib/python3.6/site-packages/ray/worker.py", line 1939, in connect
    64)
  File "plasma.pyx", line 678, in pyarrow.plasma.connect
  File "error.pxi", line 79, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Could not connect to socket /tmp/plasma_store63511860
```

### Source code / logs

Aside from the above error trace, I also get this in my  plasma_store_0-2018-07-01_11-04-00-05157.err:
```
/Users/rkn/Workspace/ray/thirdparty/build/arrow/cpp/src/plasma/store.cc:860 Check failed: scanned == 1
```
If I just call `ray.init(num_cpu=4)`, there won't be any problem.  The problem occurs every time I add the `object_store_memory` kwarg, no matter the value.

**Comment by guoyuhong** [comment]
Hi @chunweiyuan , the problem here is that 2e9 is a float number and there is a bug in Plasma store when we start it with a float number. Please use `ray.init(object_store_memory=2000000000)` instead. I will send PR soon to fix this.

**Comment by robertnishihara** [comment]
@chunweiyuan thanks for filing the issue, and @guoyuhong thanks for the fix!

**Comment by chunweiyuan** [comment]
Thanks everyone.
