### ISSUE TITLE
[Rllib][Bug] Custom Multi-agent Environment Observation Space Error

### ISSUE THREAD

**Issue by ZKBig** [ray-project/ray#23368]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

In my project, I am supposed to first train a single automatic vehicle to drive in a custom traffic network, and then applying this trained policy for multiple automatic vehicles. According to the documentation of rllib multi-agent, I need to modify the environment for single agent to an updated environment for multi-agent to achieve this function. In the meantime, each vehicle should be assigned with an isolated policy. 

Because my environment for single vehicle is based on the gym class, then according to the documentation of rllib, the following contents are changed for obtaining a multi-agent environment:
**1. For the 'step()' function:**
The returned observation is modified to contain all the rl vehicles, and each rl vehicle is assigned with a particular observation value with the help of 'dict' in python.
Note that the returned values of  reward and done should also be extended to meet multi-agent demand in virtu of 'dict' in python.

**2. The input attribute 'actions' of 'step()' function:**
After modifying, the input actions contains all the actions for the rl vehicles, then assign the action to each rl vehicle according to the name of rl vehicles in 'actions'.

**3. The modified multi-agent environment class inherits the 'MultiAgentEnv' in rllib as well.**

It is important to point out that the observation space and the action space is not changed, which remains the same as the single vehicle following the documents. 

The above is all the changes of my custom environment class.  When making the preparation for training the multi-agent, I added the configuration for multi-agent as well, which is shown as follows:
<img width="579" alt="code1" src="https://user-images.githubusercontent.com/71830568/159216912-39f016f0-0c99-4bd4-9af1-3b3654b26298.png">

Then, I use tune.run(...) to train my own model; however, an unexpected error occurred, which is shown as follows:
`Failure # 1 (occurred at 2022-03-16_15-18-49)
Traceback (most recent call last):
  File "/Users/XXXXX/opt/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 924, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/Users/XXXXX/opt/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 787, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/Users/XXXXX/opt/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/XXXXX/opt/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/worker.py", line 1715, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::PPO.__init__()[39m (pid=1511, ip=127.0.0.1)
  File "/Users/XXXXX/opt/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 102, in __init__
    Trainer.__init__(self, config, env, logger_creator,
  File "/Users/XXXXX/opt/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 661, in __init__
    super().__init__(config, logger_creator, remote_checkpoint_dir,
  File "/Users/XXXXX/opt/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/tune/trainable.py", line 121, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/Users/XXXXX/opt/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 113, in setup
    super().setup(config)
  File "/Users/XXXXX/opt/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 764, in setup
    self._init(self.config, self.env_creator)
  File "/Users/XXXXX/opt/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 136, in _init
    self.workers = self._make_workers(
  File "/Users/XXXXX/opt/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1727, in _make_workers
    return WorkerSet(
  File "/Users/XXXXX/opt/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 87, in __init__
    remote_spaces = ray.get(self.remote_workers(
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::RolloutWorker.__init__()[39m (pid=1513, ip=127.0.0.1)
  File "/Users/XXXXX/opt/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 463, in __init__
    _validate_env(self.env, env_context=self.env_context)
  File "/Users/XXXXX/opt/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1700, in _validate_env
    raise EnvError(
ray.rllib.utils.error.EnvError: Env's `observation_space` Dict(action_mask:Box([0. 0. 0. 0.], [1. 1. 1. 1.], (4,), float32), position:Box([[-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]], [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]], (38, 1), float32), real_observation:Box([[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]], [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], (38, 5), float32)) does not contain returned observation after a reset ({'rl0': {'real_observation': array([[0.        , 0.        , 0.03572819, 0.34533966, 1.        ],
       [0.        , 0.        , 0.0067462 , 0.34533966, 0.        ],
       [0.        , 0.        , 0.04358931, 0.6188486 , 0.        ],
       [0.        , 0.        , 0.17568235, 0.6188486 , 0.        ],
       [0.        , 0.        , 0.05400503, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.30195004, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.3528907 , 0.63266224, 0.        ],
       [0.        , 0.        , 0.20100671, 0.63266224, 0.        ],
       [0.        , 0.        , 0.34633353, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.19366628, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.3083996 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.35600442, 0.6188486 , 0.        ],
       [0.        , 0.        , 0.3648858 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.4674277 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.46439698, 0.9780019 , 0.        ],
       [0.        , 0.        , 0.3666407 , 0.9780019 , 0.        ],
       [0.        , 0.        , 0.32016182, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.57191485, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.59129936, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.3743161 , 0.9641883 , 0.        ],
       [0.        , 0.        , 0.5748492 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.6044079 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.6679318 , 0.9641883 , 0.        ],
       [0.        , 0.        , 0.48739564, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.6068588 , 0.6188141 , 0.        ],
       [0.        , 0.        , 0.67606044, 0.6188141 , 0.        ],
       [0.        , 0.        , 0.5922788 , 1.        , 0.        ],
       [0.        , 0.        , 0.8389112 , 1.        , 0.        ],
       [0.        , 0.        , 0.8550952 , 0.98950166, 0.        ],
       [0.        , 0.        , 0.62028337, 0.98950166, 0.        ],
       [0.        , 0.        , 0.9088409 , 0.9887074 , 0.        ],
       [0.        , 0.        , 0.6943932 , 0.9887074 , 0.        ],
       [0.        , 0.        , 0.8472192 , 0.6343544 , 0.        ],
       [0.        , 0.        , 0.8698804 , 0.6343544 , 0.        ],
       [0.        , 0.        , 0.8703939 , 0.6165694 , 0.        ],
       [0.        , 0.        , 0.9204792 , 0.6165694 , 0.        ],
       [0.        , 0.        , 1.        , 0.32057878, 0.        ],
       [0.        , 0.        , 0.93785423, 0.32057878, 0.        ]],
      dtype=float32), 'position': array([[0.06163448],
       [0.06495931],
       [0.18669344],
       [0.1899465 ],
       [0.29732072],
       [0.29967514],
       [0.35336545],
       [0.35480976],
       [0.386706  ],
       [0.3927177 ],
       [0.40525863],
       [0.4100809 ],
       [0.4891037 ],
       [0.4921863 ],
       [0.5323883 ],
       [0.53808206],
       [0.5624943 ],
       [0.56471974],
       [0.5975516 ],
       [0.60240877],
       [0.65928924],
       [0.664609  ],
       [0.6909546 ],
       [0.69610846],
       [0.7109397 ],
       [0.7154712 ],
       [0.8341697 ],
       [0.8350319 ],
       [0.8551079 ],
       [0.85537493],
       [0.9175007 ],
       [0.9190277 ],
       [0.9268189 ],
       [0.93248606],
       [0.96099406],
       [0.9667964 ],
       [0.9978848 ],
       [1.        ]], dtype=float32), 'action_mask': [1, 1, 0, 0]}, 'rl1': {'real_observation': array([[0.        , 0.        , 0.03572819, 0.34533966, 1.        ],
       [0.        , 0.        , 0.0067462 , 0.34533966, 0.        ],
       [0.        , 0.        , 0.04358931, 0.6188486 , 0.        ],
       [0.        , 0.        , 0.17568235, 0.6188486 , 0.        ],
       [0.        , 0.        , 0.05400503, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.30195004, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.3528907 , 0.63266224, 0.        ],
       [0.        , 0.        , 0.20100671, 0.63266224, 0.        ],
       [0.        , 0.        , 0.34633353, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.19366628, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.3083996 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.35600442, 0.6188486 , 0.        ],
       [0.        , 0.        , 0.3648858 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.4674277 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.46439698, 0.9780019 , 0.        ],
       [0.        , 0.        , 0.3666407 , 0.9780019 , 0.        ],
       [0.        , 0.        , 0.32016182, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.57191485, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.59129936, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.3743161 , 0.9641883 , 0.        ],
       [0.        , 0.        , 0.5748492 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.6044079 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.6679318 , 0.9641883 , 0.        ],
       [0.        , 0.        , 0.48739564, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.6068588 , 0.6188141 , 0.        ],
       [0.        , 0.        , 0.67606044, 0.6188141 , 0.        ],
       [0.        , 0.        , 0.5922788 , 1.        , 0.        ],
       [0.        , 0.        , 0.8389112 , 1.        , 0.        ],
       [0.        , 0.        , 0.8550952 , 0.98950166, 0.        ],
       [0.        , 0.        , 0.62028337, 0.98950166, 0.        ],
       [0.        , 0.        , 0.9088409 , 0.9887074 , 0.        ],
       [0.        , 0.        , 0.6943932 , 0.9887074 , 0.        ],
       [0.        , 0.        , 0.8472192 , 0.6343544 , 0.        ],
       [0.        , 0.        , 0.8698804 , 0.6343544 , 0.        ],
       [0.        , 0.        , 0.8703939 , 0.6165694 , 0.        ],
       [0.        , 0.        , 0.9204792 , 0.6165694 , 0.        ],
       [0.        , 0.        , 1.        , 0.32057878, 0.        ],
       [0.        , 0.        , 0.93785423, 0.32057878, 0.        ]],
      dtype=float32), 'position': array([[0.06163448],
       [0.06495931],
       [0.18669344],
       [0.1899465 ],
       [0.29732072],
       [0.29967514],
       [0.35336545],
       [0.35480976],
       [0.386706  ],
       [0.3927177 ],
       [0.40525863],
       [0.4100809 ],
       [0.4891037 ],
       [0.4921863 ],
       [0.5323883 ],
       [0.53808206],
       [0.5624943 ],
       [0.56471974],
       [0.5975516 ],
       [0.60240877],
       [0.65928924],
       [0.664609  ],
       [0.6909546 ],
       [0.69610846],
       [0.7109397 ],
       [0.7154712 ],
       [0.8341697 ],
       [0.8350319 ],
       [0.8551079 ],
       [0.85537493],
       [0.9175007 ],
       [0.9190277 ],
       [0.9268189 ],
       [0.93248606],
       [0.96099406],
       [0.9667964 ],
       [0.9978848 ],
       [1.        ]], dtype=float32), 'action_mask': [1, 1, 0, 0]}, 'rl2': {'real_observation': array([[0.        , 0.        , 0.03572819, 0.34533966, 1.        ],
       [0.        , 0.        , 0.0067462 , 0.34533966, 0.        ],
       [0.        , 0.        , 0.04358931, 0.6188486 , 0.        ],
       [0.        , 0.        , 0.17568235, 0.6188486 , 0.        ],
       [0.        , 0.        , 0.05400503, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.30195004, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.3528907 , 0.63266224, 0.        ],
       [0.        , 0.        , 0.20100671, 0.63266224, 0.        ],
       [0.        , 0.        , 0.34633353, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.19366628, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.3083996 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.35600442, 0.6188486 , 0.        ],
       [0.        , 0.        , 0.3648858 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.4674277 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.46439698, 0.9780019 , 0.        ],
       [0.        , 0.        , 0.3666407 , 0.9780019 , 0.        ],
       [0.        , 0.        , 0.32016182, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.57191485, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.59129936, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.3743161 , 0.9641883 , 0.        ],
       [0.        , 0.        , 0.5748492 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.6044079 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.6679318 , 0.9641883 , 0.        ],
       [0.        , 0.        , 0.48739564, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.6068588 , 0.6188141 , 0.        ],
       [0.        , 0.        , 0.67606044, 0.6188141 , 0.        ],
       [0.        , 0.        , 0.5922788 , 1.        , 0.        ],
       [0.        , 0.        , 0.8389112 , 1.        , 0.        ],
       [0.        , 0.        , 0.8550952 , 0.98950166, 0.        ],
       [0.        , 0.        , 0.62028337, 0.98950166, 0.        ],
       [0.        , 0.        , 0.9088409 , 0.9887074 , 0.        ],
       [0.        , 0.        , 0.6943932 , 0.9887074 , 0.        ],
       [0.        , 0.        , 0.8472192 , 0.6343544 , 0.        ],
       [0.        , 0.        , 0.8698804 , 0.6343544 , 0.        ],
       [0.        , 0.        , 0.8703939 , 0.6165694 , 0.        ],
       [0.        , 0.        , 0.9204792 , 0.6165694 , 0.        ],
       [0.        , 0.        , 1.        , 0.32057878, 0.        ],
       [0.        , 0.        , 0.93785423, 0.32057878, 0.        ]],
      dtype=float32), 'position': array([[0.06163448],
       [0.06495931],
       [0.18669344],
       [0.1899465 ],
       [0.29732072],
       [0.29967514],
       [0.35336545],
       [0.35480976],
       [0.386706  ],
       [0.3927177 ],
       [0.40525863],
       [0.4100809 ],
       [0.4891037 ],
       [0.4921863 ],
       [0.5323883 ],
       [0.53808206],
       [0.5624943 ],
       [0.56471974],
       [0.5975516 ],
       [0.60240877],
       [0.65928924],
       [0.664609  ],
       [0.6909546 ],
       [0.69610846],
       [0.7109397 ],
       [0.7154712 ],
       [0.8341697 ],
       [0.8350319 ],
       [0.8551079 ],
       [0.85537493],
       [0.9175007 ],
       [0.9190277 ],
       [0.9268189 ],
       [0.93248606],
       [0.96099406],
       [0.9667964 ],
       [0.9978848 ],
       [1.        ]], dtype=float32), 'action_mask': [1, 1, 0, 0]}, 'rl3': {'real_observation': array([[0.        , 0.        , 0.03572819, 0.34533966, 1.        ],
       [0.        , 0.        , 0.0067462 , 0.34533966, 0.        ],
       [0.        , 0.        , 0.04358931, 0.6188486 , 0.        ],
       [0.        , 0.        , 0.17568235, 0.6188486 , 0.        ],
       [0.        , 0.        , 0.05400503, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.30195004, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.3528907 , 0.63266224, 0.        ],
       [0.        , 0.        , 0.20100671, 0.63266224, 0.        ],
       [0.        , 0.        , 0.34633353, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.19366628, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.3083996 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.35600442, 0.6188486 , 0.        ],
       [0.        , 0.        , 0.3648858 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.4674277 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.46439698, 0.9780019 , 0.        ],
       [0.        , 0.        , 0.3666407 , 0.9780019 , 0.        ],
       [0.        , 0.        , 0.32016182, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.57191485, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.59129936, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.3743161 , 0.9641883 , 0.        ],
       [0.        , 0.        , 0.5748492 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.6044079 , 0.6188486 , 0.        ],
       [0.        , 0.        , 0.6679318 , 0.9641883 , 0.        ],
       [0.        , 0.        , 0.48739564, 0.9641883 , 0.        ],
       [0.        , 0.        , 0.6068588 , 0.6188141 , 0.        ],
       [0.        , 0.        , 0.67606044, 0.6188141 , 0.        ],
       [0.        , 0.        , 0.5922788 , 1.        , 0.        ],
       [0.        , 0.        , 0.8389112 , 1.        , 0.        ],
       [0.        , 0.        , 0.8550952 , 0.98950166, 0.        ],
       [0.        , 0.        , 0.62028337, 0.98950166, 0.        ],
       [0.        , 0.        , 0.9088409 , 0.9887074 , 0.        ],
       [0.        , 0.        , 0.6943932 , 0.9887074 , 0.        ],
       [0.        , 0.        , 0.8472192 , 0.6343544 , 0.        ],
       [0.        , 0.        , 0.8698804 , 0.6343544 , 0.        ],
       [0.        , 0.        , 0.8703939 , 0.6165694 , 0.        ],
       [0.        , 0.        , 0.9204792 , 0.6165694 , 0.        ],
       [0.        , 0.        , 1.        , 0.32057878, 0.        ],
       [0.        , 0.        , 0.93785423, 0.32057878, 0.        ]],
      dtype=float32), 'position': array([[0.06163448],
       [0.06495931],
       [0.18669344],
       [0.1899465 ],
       [0.29732072],
       [0.29967514],
       [0.35336545],
       [0.35480976],
       [0.386706  ],
       [0.3927177 ],
       [0.40525863],
       [0.4100809 ],
       [0.4891037 ],
       [0.4921863 ],
       [0.5323883 ],
       [0.53808206],
       [0.5624943 ],
       [0.56471974],
       [0.5975516 ],
       [0.60240877],
       [0.65928924],
       [0.664609  ],
       [0.6909546 ],
       [0.69610846],
       [0.7109397 ],
       [0.7154712 ],
       [0.8341697 ],
       [0.8350319 ],
       [0.8551079 ],
       [0.85537493],
       [0.9175007 ],
       [0.9190277 ],
       [0.9268189 ],
       [0.93248606],
       [0.96099406],
       [0.9667964 ],
       [0.9978848 ],
       [1.        ]], dtype=float32), 'action_mask': [1, 1, 0, 0]}})!

`
Note that the observation space defined in my environment is already a dictionary, which has 'action_mask', 'real_observation', 'position' three keys. However, this unexpected error happened when the environment was changed to multi-agent, and it seemed that it has the following two possible reasons:
a) Some changes converted from single-agent to multi-agent of the environment are neglected;
b) The corresponding multi-agent configuration has problem.
However, I cannot figure out what wrong it is though I have tried my best.

The Expected Results:
The model can be successfully trained in my multi-agent environment without any error.

### Versions / Dependencies

ray version: 1.11.0
MacOS version: Monterey 12.2.1

### Reproduction script

The codes are related to the external environment library; therefore, it is hard to attach the corresponding scripts. However, if it is necessary for solution, I will attach it as soon as possible. Thx!

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ZKBig** [comment]
cc @sven1977  Please check this question, thank you.

**Comment by ZKBig** [comment]
@avnishn , Could you please check this bug? Thank you!

**Comment by avnishn** [comment]
The config parameter is called :

"disable_env_checking"

And you would need to set it to true in your config dict. 

You can find it on line ~650 ray/rllib/agents/trainer.py

It's been available for a few releases (>=1.9?)

**Comment by ZKBig** [comment]
@avnishn  Hi, do you need more information about my question?

**Comment by gjoliver** [comment]
can you provide a minimum reproduce script so we can test things on our side?
thanks.

**Comment by ZKBig** [comment]
> can you provide a minimum reproduce script so we can test things on our side? thanks.

I have solve this question, thank you. However, another problem is that I want to apply a trained policy obtained from a single agent scenario to a multi-agent scenario, and every agent should use this same trained policy. Could you please give some tips to implement this function in rllib, thank you!

**Comment by gjoliver** [comment]
you should be able to use compute_single_action() for all the agents in your env once the policy is trained??
