### ISSUE TITLE
[air] If you kill train via control C, a bunch of random error messages show up next time you run Train.

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#23431]
```
(TrainTrainable pid=1236) RuntimeError: Training has failed even after 1 attempts. You can change the number of max failure attempts by setting the `max_retries` arg in your `Trainer`.
(TrainTrainable pid=1236) Exception in thread Thread-3:
(TrainTrainable pid=1236) Traceback (most recent call last):
(TrainTrainable pid=1236)   File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
(TrainTrainable pid=1236)     self.run()
(TrainTrainable pid=1236)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 298, in run
(TrainTrainable pid=1236)     raise e
(TrainTrainable pid=1236)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 272, in run
(TrainTrainable pid=1236)     self._entrypoint()
(TrainTrainable pid=1236)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 351, in entrypoint
(TrainTrainable pid=1236)     self._status_reporter.get_checkpoint(),
(TrainTrainable pid=1236)   File "/usr/local/lib/python3.7/dist-packages/ray/util/tracing/tracing_helper.py", line 462, in _resume_span
(TrainTrainable pid=1236)     return method(self, *_args, **_kwargs)
(TrainTrainable pid=1236)   File "/usr/local/lib/python3.7/dist-packages/ray/ml/trainer.py", line 295, in _trainable_func
(TrainTrainable pid=1236)     super()._trainable_func(self._merged_config, reporter, checkpoint_dir)
(TrainTrainable pid=1236)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 640, in _trainable_func
(TrainTrainable pid=1236)     output = fn()
(TrainTrainable pid=1236)   File "/usr/local/lib/python3.7/dist-packages/ray/ml/trainer.py", line 279, in train_func
(TrainTrainable pid=1236)     trainer.training_loop()
(TrainTrainable pid=1236)   File "/usr/local/lib/python3.7/dist-packages/ray/ml/train/data_parallel_trainer.py", line 298, in training_loop
(TrainTrainable pid=1236)     for results in training_iterator:
(TrainTrainable pid=1236)   File "/usr/local/lib/python3.7/dist-packages/ray/train/trainer.py", line 716, in __next__
(TrainTrainable pid=1236)     next_results = self._run_with_error_handling(self._fetch_next_result)
(TrainTrainable pid=1236)   File "/usr/local/lib/python3.7/dist-packages/ray/train/trainer.py", line 687, in _run_with_error_handling
(TrainTrainable pid=1236)     return func()
(TrainTrainable pid=1236)   File "/usr/local/lib/python3.7/dist-packages/ray/train/trainer.py", line 742, in _fetch_next_result
(TrainTrainable pid=1236)     results = self._backend_executor.get_next_results()
(TrainTrainable pid=1236)   File "/usr/local/lib/python3.7/dist-packages/ray/train/backend.py", line 477, in get_next_results
(TrainTrainable pid=1236)     results = self.get_with_failure_handling(futures)
(TrainTrainable pid=1236)   File "/usr/local/lib/python3.7/dist-packages/ray/train/backend.py", line 567, in get_with_failure_handling
(TrainTrainable pid=1236)     self._increment_failures()
(TrainTrainable pid=1236)   File "/usr/local/lib/python3.7/dist-packages/ray/train/backend.py", line 618, in _increment_failures
(TrainTrainable pid=1236)     ) from None
(TrainTrainable pid=1236) RuntimeError: Training has failed even after 1 attempts. You can change the number of max failure attempts by setting the `max_retries` arg in your `Trainer`.
(TrainTrainable pid=1236) 
```

not blocking
not easy to work around
is persistent

**Comment by amogkam** [comment]
Can you provide a repro script please?

**Comment by richardliaw** [comment]
https://colab.research.google.com/drive/1ejz98xbvf1Dral8w4vltUEvQ_eZ0vVRA#scrollTo=2xtOoomcVcIS&uniqifier=1

**Comment by richardliaw** [comment]
5 line repro ^

**Comment by amogkam** [comment]
Yeah this is super odd...looks like this is behavior with Tune though.

I can repro with this code, without using Trainer

```
import time 
from ray import tune

def train_func(config):
  for i in range(100):
    time.sleep(100)
    print(i)

tune.run(train_func)
```

**Comment by amogkam** [comment]
cc @xwjiang2010 @krfricke @Yard1

**Comment by amogkam** [comment]
Actually nvm, not able to repro anymore...

**Comment by amogkam** [comment]
Ok I am able to reproduce with this now 

```
import time 
from ray import tune
from ray.tune import PlacementGroupFactory

def train_func(config):
  @ray.remote
  class Actor:
    def run(self):
      for i in range(100):
        time.sleep(100)
        print(i)
  a = Actor.remote()
  ray.get(a.run.remote())
  

tune.run(train_func, resources_per_trial=PlacementGroupFactory([{"CPU": 1}, {"CPU": 1}]))
```

```
(train_func pid=4099) 2022-03-23 23:54:08,805	ERROR function_runner.py:281 -- Runner Thread raised error.
(train_func pid=4099) Traceback (most recent call last):
(train_func pid=4099)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 272, in run
(train_func pid=4099)     self._entrypoint()
(train_func pid=4099)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 351, in entrypoint
(train_func pid=4099)     self._status_reporter.get_checkpoint(),
(train_func pid=4099)   File "/usr/local/lib/python3.7/dist-packages/ray/util/tracing/tracing_helper.py", line 462, in _resume_span
(train_func pid=4099)     return method(self, *_args, **_kwargs)
(train_func pid=4099)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 640, in _trainable_func
(train_func pid=4099)     output = fn()
(train_func pid=4099)   File "<ipython-input-4-64ef03064a57>", line 13, in train_func
(train_func pid=4099)   File "/usr/local/lib/python3.7/dist-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
(train_func pid=4099)     return func(*args, **kwargs)
(train_func pid=4099)   File "/usr/local/lib/python3.7/dist-packages/ray/worker.py", line 1811, in get
(train_func pid=4099)     raise value
(train_func pid=4099) ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
(train_func pid=4099) 	class_name: train_func.<locals>.Actor
(train_func pid=4099) 	actor_id: 9de350440f1c97a31d46295901000000
(train_func pid=4099) 	pid: 4139
(train_func pid=4099) 	namespace: c155f8f5-d945-4cd3-a586-2976fb9da1df
(train_func pid=4099) 	ip: 172.28.0.2
(train_func pid=4099) The actor is dead because its worker process has died. Worker exit type: PLACEMENT_GROUP_REMOVED
(train_func pid=4099) Exception in thread Thread-3:
(train_func pid=4099) Traceback (most recent call last):
(train_func pid=4099)   File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
(train_func pid=4099)     self.run()
(train_func pid=4099)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 298, in run
(train_func pid=4099)     raise e
(train_func pid=4099)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 272, in run
(train_func pid=4099)     self._entrypoint()
(train_func pid=4099)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 351, in entrypoint
(train_func pid=4099)     self._status_reporter.get_checkpoint(),
(train_func pid=4099)   File "/usr/local/lib/python3.7/dist-packages/ray/util/tracing/tracing_helper.py", line 462, in _resume_span
(train_func pid=4099)     return method(self, *_args, **_kwargs)
(train_func pid=4099)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 640, in _trainable_func
(train_func pid=4099)     output = fn()
(train_func pid=4099)   File "<ipython-input-4-64ef03064a57>", line 13, in train_func
(train_func pid=4099)   File "/usr/local/lib/python3.7/dist-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
(train_func pid=4099)     return func(*args, **kwargs)
(train_func pid=4099)   File "/usr/local/lib/python3.7/dist-packages/ray/worker.py", line 1811, in get
(train_func pid=4099)     raise value
(train_func pid=4099) ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
(train_func pid=4099) 	class_name: train_func.<locals>.Actor
(train_func pid=4099) 	actor_id: 9de350440f1c97a31d46295901000000
(train_func pid=4099) 	pid: 4139
(train_func pid=4099) 	namespace: c155f8f5-d945-4cd3-a586-2976fb9da1df
(train_func pid=4099) 	ip: 172.28.0.2
(train_func pid=4099) The actor is dead because its worker process has died. Worker exit type: PLACEMENT_GROUP_REMOVED
(train_func pid=4099)
```

**Comment by amogkam** [comment]
Looks like this might be a problem with Ray core. Actors don't get cleaned up- you can try playing around with this example https://colab.research.google.com/drive/1gNbLWHktfXY6b8G6mafx4_B-w9suW1PW#scrollTo=GuVHg6JcP0_S

**Comment by amogkam** [comment]
Blocked on https://github.com/ray-project/ray/issues/23443

**Comment by amogkam** [comment]
Since this happens only in interactive environments, I would say it should be fine to downgrade this to P2.

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
