### ISSUE TITLE
[core] Ray actor continues running after `KeyboardInterrupt` in interactive environment

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#23443]
As the title says, doing ^C does not kill Ray actor execution in interactive environments (python interactive mode, ipython, colab notebooks).

```
>>> import ray
>>> import time
>>> @ray.remote
class Actor:
  def run(self):
    for i in range(100):
      time.sleep(1)
      print(i)
...
>>> o = Actor.remote()
2022-03-23 17:35:14,843	INFO services.py:1456 -- View the Ray dashboard at http://127.0.0.1:8265
>>> ray.get(o.run.remote())
(Actor pid=11132) 0
(Actor pid=11132) 1
(Actor pid=11132) 2
(Actor pid=11132) 3
(Actor pid=11132) 4
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/amog/dev/ray/python/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/amog/dev/ray/python/ray/worker.py", line 1803, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/Users/amog/dev/ray/python/ray/worker.py", line 362, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 1198, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 167, in ray._raylet.check_status
KeyboardInterrupt
>>> (Actor pid=11132) 5
(Actor pid=11132) 6
(Actor pid=11132) 7
(Actor pid=11132) 8
(Actor pid=11132) 9

KeyboardInterrupt
>>> (Actor pid=11132) 10
(Actor pid=11132) 11
(Actor pid=11132) 12
(Actor pid=11132) 13
(Actor pid=11132) 14
(Actor pid=11132) 15
(Actor pid=11132) 16
(Actor pid=11132) 17
```

Try this notebook for a simple repro https://colab.research.google.com/drive/1gNbLWHktfXY6b8G6mafx4_B-w9suW1PW#scrollTo=GuVHg6JcP0_S

**Comment by amogkam** [comment]
cc @stephanie-wang

**Comment by stephanie-wang** [comment]
I think this behavior is expected because KeyboardInterrupt only interrupts the `ray.get` call, not the actor task.

**Comment by czgdp1807** [comment]
It happens with a python script as well that is copying your code and launching it as a script using `python` command. I think @stephanie-wang is right, the `check_status` raises `KeyboardInterrupt` after receiving a signal from `CoreWorker.Get`.

May be `CoreWorker.Get` isn't killing/stopping the tasks once KeyboardInterrupt is received (makes sense?) ?
