### ISSUE TITLE
[Feature] .bind() on function does not take pre-bind value from upstream DAGNode

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#23511]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

```
In [1]: from ray import serve

In [2]: @serve.deployment
   ...: def func(a, b, c):
   ...:     return a + b + c
   ...:

In [3]: from ray.experimental.dag.input_node import InputNode

In [4]: with InputNode() as user_input:
   ...:     dag = func.bind(1, 2, user_input)
   ...:

In [5]: import ray

In [6]: ray.get(dag.execute(3))
2022-04-21 19:12:24,424	INFO services.py:1467 -- View the Ray dashboard at http://127.0.0.1:8266
Out[6]: 6

In [7]: handle = serve.run(dag)
(ServeController pid=75078) INFO 2022-04-21 19:12:36,961 controller 75078 checkpoint_path.py:17 - Using RayInternalKVStore for controller checkpoint and recovery.
(ServeController pid=75078) INFO 2022-04-21 19:12:37,068 controller 75078 http_state.py:115 - Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:127.0.0.1-0' on node 'node:127.0.0.1-0' listening on '127.0.0.1:8000'
(HTTPProxyActor pid=75092) INFO:     Started server process [75092]
>>>>> func_args: (1, 2, <ray.experimental.dag.input_node.InputNode object at 0x7f9f90853be0>)
>>>>> func_args: (1, 2, <ray.experimental.dag.input_node.InputNode object at 0x7f9f90853e80>)
(ServeController pid=75078) INFO 2022-04-21 19:12:38,250 controller 75078 deployment_state.py:1217 - Adding 1 replicas to deployment 'func'.

In [8]: ray.get(handle.remote(3))
(func pid=75106) ERROR 2022-04-21 19:12:50,491 func func#iHUsfC replica.py:433 - Request failed due to TypeError:
(func pid=75106) Traceback (most recent call last):
(func pid=75106)   File "/Users/jiaodong/Workspace/ray/python/ray/serve/replica.py", line 415, in invoke_single
(func pid=75106)     result = await method_to_call(*args, **kwargs)
(func pid=75106)   File "/Users/jiaodong/Workspace/ray/python/ray/_private/async_compat.py", line 43, in wrapper
(func pid=75106)     return func(*args, **kwargs)
(func pid=75106) TypeError: func() missing 2 required positional arguments: 'b' and 'c'
(func pid=75106) INFO 2022-04-21 19:12:50,492 func func#iHUsfC replica.py:482 - HANDLE __call__ ERROR 1.3ms
---------------------------------------------------------------------------
RayTaskError(TypeError)                   Traceback (most recent call last)
<ipython-input-8-ecaf2853228f> in <module>
----> 1 ray.get(handle.remote(3))

~/Workspace/ray/python/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
    103             if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104                 return getattr(ray, func.__name__)(*args, **kwargs)
--> 105         return func(*args, **kwargs)
    106
    107     return wrapper

~/Workspace/ray/python/ray/worker.py in get(object_refs, timeout)
   1823                     worker.core_worker.dump_object_store_memory_usage()
   1824                 if isinstance(value, RayTaskError):
-> 1825                     raise value.as_instanceof_cause()
   1826                 else:
   1827                     raise value

RayTaskError(TypeError): ray::RayServeWrappedReplica.handle_request() (pid=75106, ip=127.0.0.1)
  File "/Users/jiaodong/Workspace/ray/python/ray/serve/utils.py", line 218, in wrap_to_ray_error
    raise exception
  File "/Users/jiaodong/Workspace/ray/python/ray/serve/replica.py", line 415, in invoke_single
    result = await method_to_call(*args, **kwargs)
TypeError: func() missing 2 required positional arguments: 'b' and 'c'
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by jiaodong** [comment]
The high level question here is ideally we need a resolution story for deployment function to deal with something like 

```
a = func.bind(1, 2, user_input)
```

Where 1 and 2 are pre-bind values, and `user_input` comes from `.remote`

**Comment by jiaodong** [comment]
So given in serve we always want user to bring a DAGDriver class and DAG body executes fine with single function, this doesn't break core / serve dag layering or semantics, we can revisit later if we want single function node to be the root .. that is unlikely.

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
