### ISSUE TITLE
[jobs] [Feature] Support streaming job logs to stdout/stderr

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#23564]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Right now job logs are streamed directly to log files, but we should support an option to stream the logs to stdout/stderr.  Should be configurable here: https://github.com/ray-project/ray/blob/77090144a22b89b6dda83840adace1fdf2407191/dashboard/modules/job/job_manager.py#L140-L146

Probably the best interface is to use the existing `RAY_LOG_TO_STDERR` API and make it work with jobs: https://docs.ray.io/en/latest/ray-observability/ray-logging.html#redirecting-ray-logs-to-stderr

### Use case

Streaming logs to STDOUT or STDERR allows for automatic integrations with external tools such as Splunk.  It avoids workarounds such as `['trap : TERM INT; touch /tmp/raylogs; tail -f /tmp/raylogs; sleep infinity & wait;']`

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by mkotsalainen** [comment]
FYI @architkulkarni After getting the ray serve deployments working with custom dependencies (https://github.com/ray-project/ray/issues/23772) by running latest Ray code (thanks for tip!) -  I tried adding the RAY_LOG_TO_STDERR env variable to the pods so that I can use centralised logging. This breaks deployments. 

```
2022-04-08 14:26:39,867     WARNING dataclient.py:363 -- Encountered connection issues in the data channel. Attempting to reconnect.
2022-04-08 14:26:45,526 ERROR dataclient.py:289 -- Unrecoverable error in data channel.
Traceback (most recent call last):
  File "mlflow_run_model.py", line 12, in <module>
    ray.init("ray:/xxxxxxxxxx", namespace="serve")
  File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/worker.py", line 882, in init
    return builder.connect()
  File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/client_builder.py", line 164, in connect
    ray_init_kwargs=self._remote_init_kwargs,
  File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/util/client_connect.py", line 45, in connect
    ray_init_kwargs=ray_init_kwargs,
  File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/util/client/__init__.py", line 243, in connect
    conn = self.get_context().connect(*args, **kw_args)
  File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/util/client/__init__.py", line 94, in connect
    self.client_worker._server_init(job_config, ray_init_kwargs)
  File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/util/client/worker.py", line 799, in _server_init
    reconnect_grace_period=self._reconnect_grace_period,
  File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 473, in Init
    resp = self._blocking_send(datareq)
  File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 412, in _blocking_send
    self._check_shutdown()
  File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 465, in _check_shutdown
    raise ConnectionError(msg)
ConnectionError: Request can't be sent because the Ray client has already been disconnected due to an error. Last exception: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.NOT_FOUND
        details = "Attempted to reconnect a session that has already been cleaned up"
        debug_error_string = "{"created":"@1649424405.525772000","description":"Error received from peer ipv4:52.49.202.219:80","file":"src/core/lib/surface/call.cc","file_line":1075,"grpc_message":"Attempted to reconnect a session that has already been cleaned up","grpc_status":5}"
>
```

**Comment by architkulkarni** [comment]
@mkotsalainen Thanks, and sorry you're running into this--it seems like a separate issue, would you mind filing another bug report? https://github.com/ray-project/ray/issues/new?assignees=&labels=bug%2Ctriage&template=bug-report.yml&title=%5B%3CRay+component%3A+Core%7CRLlib%7Cetc...%3E%5D+

**Comment by scottsun94** [comment]
@architkulkarni Is this fixed now since we are moving towards job submission GA.

**Comment by architkulkarni** [comment]
@scottsun94 This issue is still open.  I think it can be added after GA.

**Comment by zhedasuiyuan** [comment]
> FYI @architkulkarni After getting the ray serve deployments working with custom dependencies (#23772) by running latest Ray code (thanks for tip!) - I tried adding the RAY_LOG_TO_STDERR env variable to the pods so that I can use centralised logging. This breaks deployments.
> 
> ```
> 2022-04-08 14:26:39,867     WARNING dataclient.py:363 -- Encountered connection issues in the data channel. Attempting to reconnect.
> 2022-04-08 14:26:45,526 ERROR dataclient.py:289 -- Unrecoverable error in data channel.
> Traceback (most recent call last):
>   File "mlflow_run_model.py", line 12, in <module>
>     ray.init("ray:/xxxxxxxxxx", namespace="serve")
>   File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
>     return func(*args, **kwargs)
>   File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/worker.py", line 882, in init
>     return builder.connect()
>   File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/client_builder.py", line 164, in connect
>     ray_init_kwargs=self._remote_init_kwargs,
>   File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/util/client_connect.py", line 45, in connect
>     ray_init_kwargs=ray_init_kwargs,
>   File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/util/client/__init__.py", line 243, in connect
>     conn = self.get_context().connect(*args, **kw_args)
>   File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/util/client/__init__.py", line 94, in connect
>     self.client_worker._server_init(job_config, ray_init_kwargs)
>   File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/util/client/worker.py", line 799, in _server_init
>     reconnect_grace_period=self._reconnect_grace_period,
>   File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 473, in Init
>     resp = self._blocking_send(datareq)
>   File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 412, in _blocking_send
>     self._check_shutdown()
>   File "/Users/matti/.virtualenvs/ray/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 465, in _check_shutdown
>     raise ConnectionError(msg)
> ConnectionError: Request can't be sent because the Ray client has already been disconnected due to an error. Last exception: <_MultiThreadedRendezvous of RPC that terminated with:
>         status = StatusCode.NOT_FOUND
>         details = "Attempted to reconnect a session that has already been cleaned up"
>         debug_error_string = "{"created":"@1649424405.525772000","description":"Error received from peer ipv4:52.49.202.219:80","file":"src/core/lib/surface/call.cc","file_line":1075,"grpc_message":"Attempted to reconnect a session that has already been cleaned up","grpc_status":5}"
> >
> ```

Hello, I got exactly the same error after adding RAY_LOG_TO_STDERR when starting the head node. It works smoothly without this variable. Did you find any solutions? Thanks!

**Comment by kanwang** [comment]
Hey, I see this feature request has been open for 2 years. Any update here? This will greatly help with integration with other observability tools.

**Comment by scottsun94** [comment]
cc: @alanwguo @anyscalesam

**Comment by lsb** [comment]
Why is this preferable to setting a custom log file of "stdout" in the "/dev" directory via ray.init()
