### ISSUE TITLE
[Bug] [Serve] [Tests] long_running_tests failed

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#23575]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

https://buildkite.com/ray-project/release-tests-branch/builds/277#b83f0a62-1ba7-4e2f-8b3f-783e99307dd2

### Versions / Dependencies

master

### Reproduction script

```


[INFO 2022-03-27 15:16:50,202] job_manager.py: 42  Executing pip install -q awscli && aws s3 cp /tmp/release_test_out.json s3://ray-release-automation-results/tmp/tkwmcqosne --acl bucket-owner-full-control with {} via ray job submit
--
  | [ERROR 2022-03-27 15:16:54,628] glue.py: 237  Could not fetch results for test command
  | [ERROR 2022-03-27 15:16:54,628] glue.py: 238  Could not fetch results from session:
  | Traceback (most recent call last):
  | File "/tmp/release-Z8bdl8Ea16/release/ray_release/command_runner/sdk_runner.py", line 164, in fetch_results
  | self.file_manager.download(self.result_output_json, tmpfile)
  | File "/tmp/release-Z8bdl8Ea16/release/ray_release/file_manager/job_file_manager.py", line 58, in download
  | {},
  | File "/tmp/release-Z8bdl8Ea16/release/ray_release/file_manager/job_file_manager.py", line 33, in _run_with_retry
  | assert callable(f)
  | AssertionError
  |  
  | The above exception was the direct cause of the following exception:
  |  
  | Traceback (most recent call last):
  | File "/tmp/release-Z8bdl8Ea16/release/ray_release/glue.py", line 235, in run_release_test
  | command_results = command_runner.fetch_results()
  | File "/tmp/release-Z8bdl8Ea16/release/ray_release/command_runner/sdk_runner.py", line 172, in fetch_results
  | raise ResultsError(f"Could not fetch results from session: {e}") from e
  | ray_release.exception.ResultsError: Could not fetch results from session:
  | [INFO 2022-03-27 15:16:58,064] handle.py: 28  Checking results for test long_running_serve using alerting suite long_running_tests
  | [INFO 2022-03-27 15:16:58,064] log.py: 11  Test long_running_serve finished after 0.00 seconds. Last logs:
  |  
  |  
  |  
  | Running 5m test @ http://127.0.0.1:8000/echo
  | 2 threads and 84 connections
  | Thread Stats   Avg      Stdev     Max   +/- Stdev
  | Latency    74.02ms   23.95ms 181.79ms   64.28%
  | Req/Sec   569.97     48.97   750.00     72.42%
  | 340477 requests in 5.00m, 50.01MB read
  | Requests/sec:   1134.73
  | Transfer/sec:    170.66KB
  |  
  |  
  | [INFO 2022-03-27 15:16:58,064] log.py: 17  Got the following metadata:
  | name:    long_running_serve
  | status:  error
  | runtime: 0.00
  | stable:  True


```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by hora-anyscale** [comment]
Per Triage Sync: Closing out
