### ISSUE TITLE
[Nightly-test][Bug]   scheduling_test_many_0s_tasks_many_nodes failing

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#23591]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

scheduling_test_many_0s_tasks_many_nodes starts failing since 62414525f98e2eaeccdefa5d82a1a112e0c9f24a. Two consecutive failed runs ([[1](https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_qJXkkvBvxR4EXUyXVx25Dzu9)], [[2](https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_qJXkkvBvxR4EXUyXVx25Dzu9)])

The latest success run is on commit 6b1b25168f5524b2ba60f674a8c05d41d193da26.

Both failed runs starts failing with following errors:  `This worker was asked to execute a function that has not been registered`

```
[2m[36m(pid=497, ip=172.31.82.9)[0m 2022-03-28 18:42:30,907	ERROR worker.py:444 -- SystemExit was raised from the worker.
[2m[36m(pid=497, ip=172.31.82.9)[0m Traceback (most recent call last):
[2m[36m(pid=497, ip=172.31.82.9)[0m   File "python/ray/_raylet.pyx", line 797, in ray._raylet.task_execution_handler
[2m[36m(pid=497, ip=172.31.82.9)[0m   File "python/ray/_raylet.pyx", line 552, in ray._raylet.execute_task
[2m[36m(pid=497, ip=172.31.82.9)[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 343, in get_execution_info
[2m[36m(pid=497, ip=172.31.82.9)[0m     self._wait_for_function(function_descriptor, job_id)
[2m[36m(pid=497, ip=172.31.82.9)[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 424, in _wait_for_function
[2m[36m(pid=497, ip=172.31.82.9)[0m     raise RuntimeError(warning_message)
[2m[36m(pid=497, ip=172.31.82.9)[0m RuntimeError: This worker was asked to execute a function that has not been registered ({type=PythonFunctionDescriptor, module_name=test_scheduling, class_name=, function_name=simple_task, function_hash=3f931937b14d445a862c848fa683c4bb}, node=172.31.82.9, worker_id=e3471589f3c80ec3289941da1cb26b056fe9337bf7b68cb71e3ab911, pid=497). You may have to restart Ray or this job.
[2m[36m(pid=497, ip=172.31.82.9)[0m 
[2m[36m(pid=497, ip=172.31.82.9)[0m During handling of the above exception, another exception occurred:
[2m[36m(pid=497, ip=172.31.82.9)[0m 
[2m[36m(pid=497, ip=172.31.82.9)[0m Traceback (most recent call last):
[2m[36m(pid=497, ip=172.31.82.9)[0m   File "python/ray/_raylet.pyx", line 826, in ray._raylet.task_execution_handler
[2m[36m(pid=497, ip=172.31.82.9)[0m SystemExit
2022-03-28 18:42:31,223	WARNING worker.py:1377 -- This worker was asked to execute a function that has not been registered ({type=PythonFunctionDescriptor, module_name=test_scheduling, class_name=, function_name=simple_task, function_hash=3f931937b14d445a862c848fa683c4bb}, node=172.31.82.9, worker_id=e3471589f3c80ec3289941da1cb26b056fe9337bf7b68cb71e3ab911, pid=497). You may have to restart Ray or this job.
2022-03-28 18:42:31,225	WARNING worker.py:1377 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 797, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 552, in ray._raylet.execute_task
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 343, in get_execution_info
    self._wait_for_function(function_descriptor, job_id)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 424, in _wait_for_function
    raise RuntimeError(warning_message)
RuntimeError: This worker was asked to execute a function that has not been registered ({type=PythonFunctionDescriptor, module_name=test_scheduling, class_name=, function_name=simple_task, function_hash=3f931937b14d445a862c848fa683c4bb}, node=172.31.82.9, worker_id=e3471589f3c80ec3289941da1cb26b056fe9337bf7b68cb71e3ab911, pid=497). You may have to restart Ray or this job.
An unexpected internal error occurred while the worker was executing a task.
2022-03-28 18:42:31,225	WARNING worker.py:1377 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: f7d2d4778127592cdcf71e10c99f5193f8b6a4ed02000000 Worker ID: e3471589f3c80ec3289941da1cb26b056fe9337bf7b68cb71e3ab911 Node ID: 64d69a57f1f9233996c4f8b0aee25c67a44091b753236b04be7b8812 Worker IP address: 172.31.82.9 Worker port: 10014 Worker PID: 497
[2m[36m(pid=436, ip=172.31.88.13)[0m 2022-03-28 18:42:38,666	ERROR worker.py:444 -- SystemExit was raised from the worker.
```

### Versions / Dependencies

latest master

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
Looks very likely caused by https://github.com/ray-project/ray/commit/d1ef498638298a700b3224909c7c862a449cfa89
