### ISSUE TITLE
[Bug] `gsutil` cannot use wildcards - some hyperparameters are problematic

### ISSUE THREAD

**Issue by simonsays1980** [ray-project/ray#23670]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

# What happened
I wanted to run some experiments with RLlib where my hyperparameters are the `fcnet_hiddens`. These layer sizes are usually provided in form of Python `list` objects: 

```
config["model"]["fcnet_hiddens"] = tune.grid_search([[32, 32], [64, 64], [128, 128]])
```
I use the autoscaler for GCP to run experiments. When I run experiments I get after the first minutes a repeating error from the syncing operation of tune: 

```
2022-04-02 03:33:10,507	ERROR trial_runner.py:1050 -- Trial DQN_mini-grid_33777_00000: Error processing result.
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 1047, in _process_trial_save
    results = self.trial_executor.fetch_result(trial)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 675, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1763, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): ray::DQNTrainer.save() (pid=977, ip=10.138.15.224, repr=DQNTrainer)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 416, in save
    self._maybe_save_to_cloud(checkpoint_dir)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 425, in _maybe_save_to_cloud
    self.storage_client.wait()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/sync_client.py", line 295, in wait
    args, code, error_msg))
ray.tune.error.TuneError: Sync error. Ran command: gsutil rsync -r  '/home/ray/ray_results/DQN/DQN_mini-grid_33777_00000_0_fcnet_hiddens=[7]_2022-04-02_03-32-31/checkpoint_000005' 'gs://ray_results/MiniGrid-Experiments/MiniGrid-Empty-Random-6x6-v0/DQN/DQN_mini-grid_33777_00000_0_fcnet_hiddens=[7]_2022-04-02_03-32-31/checkpoint_000005'
Error message (1): CommandException: Destination (/home/ray/ray_results/DQN/DQN_mini-grid_33777_00000_0_fcnet_hiddens=[7]_2022-04-02_03-32-31/checkpoint_000005) must match exactly 1 URL
```
As a result, no files are synced with GCS.

# What I expected to happen
I expected that syncing runs smoothly with default settings in `tune.run()`.

### Versions / Dependencies

Linux Fedora 35
Python 3.9.0
ray 1.11.0

### Reproduction script

First I set up a GCS bucket in the cloud console and then a GCP cluster with the autoscaler script: 
```
# An unique identifier for the head node and workers of this cluster.
cluster_name: gpu-docker

# The maximum number of workers nodes to launch in addition to the head
# node.
max_workers: 10

# The autoscaler will scale up the cluster faster with higher upscaling speed.
# E.g., if the task requires adding more nodes then autoscaler will gradually
# scale up the cluster in chunks of upscaling_speed*currently_running_nodes.
# This number should be > 0.
upscaling_speed: 1.0

# This executes all commands on all nodes in the docker container,
# and opens all the necessary ports to support the Ray cluster.
# Empty string means disabled.
docker:
    #image: "rayproject/ray-ml:latest-gpu"
    # image: rayproject/ray:latest-gpu   # use this one if you don't need ML dependencies, it's faster to pull
    container_name: "ray_nvidia_docker" # e.g. ray_docker

    # # Example of running a GPU head with CPU workers
    head_image: "rayproject/ray-ml:latest-gpu"


    worker_image: "rayproject/ray-ml:latest"

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 5

# Cloud-provider specific configuration.
provider:
    type: gcp
    region: us-west1
    availability_zone: us-west1-b
    project_id: <PROJECT_ID> # Globally unique project id

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
# By default Ray creates a new private keypair, but you can also use your own.
# If you do so, make sure to also set "KeyName" in the head and worker node
# configurations below. This requires that you have added the key into the
# project wide meta-data.
#    ssh_private_key: /path/to/your/key.pem

# Tell the autoscaler the allowed node types and the resources they provide.
# The key is the name of the node type, which is just for debugging purposes.
# The node config specifies the launch config and physical instance type.
available_node_types:
    ray_head_gpu:
        # The resources provided by this node type.
        resources: {"CPU": 6, "GPU": 1}
        # Provider-specific config for the head node, e.g. instance type. By default
        # Ray will auto-configure unspecified fields such as subnets and ssh-keys.
        # For more documentation on available fields, see:
        # https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert
        node_config:
            machineType: custom-6-32768
            disks:
              - boot: true
                autoDelete: true
                type: PERSISTENT
                initializeParams:
                  diskSizeGb: 100
                  # See https://cloud.google.com/compute/docs/images for more images
                  sourceImage: projects/deeplearning-platform-release/global/images/family/common-cu110
            # Make sure to set scheduling->onHostMaintenance to TERMINATE when GPUs are present
            guestAccelerators:
              - acceleratorType: nvidia-tesla-k80
                acceleratorCount: 1
            metadata:
              items:
                - key: install-nvidia-driver
                  value: "True"
            scheduling:
              - onHostMaintenance: TERMINATE
            serviceAccounts:
            - email: ray-autoscaler-sa-v1@<PROJECT_ID>.iam.gserviceaccount.com
              scopes:
              - https://www.googleapis.com/auth/cloud-platform

    ray_worker_gpu:
        # The minimum number of nodes of this type to launch.
        # This number should be >= 0.
        min_workers: 0
        # The maximum number of workers nodes of this type to launch.
        # This takes precedence over min_workers.
        max_workers: 2
        # The resources provided by this node type.
        resources: {"CPU": 2, "GPU": 1}
        # Provider-specific config for the head node, e.g. instance type. By default
        # Ray will auto-configure unspecified fields such as subnets and ssh-keys.
        # For more documentation on available fields, see:
        # https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert
        node_config:
            machineType: n1-standard-2
            disks:
              - boot: true
                autoDelete: true
                type: PERSISTENT
                initializeParams:
                  diskSizeGb: 100
                  # See https://cloud.google.com/compute/docs/images for more images
                  sourceImage: projects/deeplearning-platform-release/global/images/family/common-cu110
            # Make sure to set scheduling->onHostMaintenance to TERMINATE when GPUs are present
            guestAccelerators:
              - acceleratorType: nvidia-tesla-k80
                acceleratorCount: 1
            metadata:
              items:
                - key: install-nvidia-driver
                  value: "True"
            # Run workers on preemptible instance by default.
            # Comment this out to use on-demand.
            scheduling:
              - preemptible: true
              - onHostMaintenance: TERMINATE
            serviceAccounts:
            - email: ray-autoscaler-sa-v1@<PROJECT_ID>.iam.gserviceaccount.com
              scopes:
              - https://www.googleapis.com/auth/cloud-platform
    
    ray_worker_small:
        # The minimum number of worker nodes of this type to launch.
        # This number should be >= 0.
        min_workers: 0
        # The maximum number of worker nodes of this type to launch.
        # This takes precedence over min_workers.
        max_workers: 10
        # The resources provided by this node type.
        resources: {"CPU": 2}
        # Provider-specific config for the head node, e.g. instance type. By default
        # Ray will auto-configure unspecified fields such as subnets and ssh-keys.
        # For more documentation on available fields, see:
        # https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert
        node_config:
            machineType: n1-standard-2
            disks:
              - boot: true
                autoDelete: true
                type: PERSISTENT
                initializeParams:
                  diskSizeGb: 50
                  # See https://cloud.google.com/compute/docs/images for more images
                  sourceImage: projects/deeplearning-platform-release/global/images/family/common-cpu
            # Run workers on preemtible instance by default.
            # Comment this out to use on-demand.
            scheduling:
              - preemptible: true
            # Un-Comment this to launch workers with the Service Account of the Head Node
            serviceAccounts:
            - email: ray-autoscaler-sa-v1@<PROJECT_ID>.iam.gserviceaccount.com
              scopes:
              - https://www.googleapis.com/auth/cloud-platform

# Specify the node type of the head node (as configured above).
head_node_type: ray_head_gpu

# Specify the node type of the worker node (as configured above). 
worker_default_node_type: ray_worker_small

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {
#    "/path1/on/remote/machine": "/path1/on/local/machine",
#    "/path2/on/remote/machine": "/path2/on/local/machine",
}

initialization_commands:
    # Wait until nvidia drivers are installed
    - >-
      timeout 300 bash -c "
          command -v nvidia-smi && nvidia-smi
          until [ \$? -eq 0 ]; do
              command -v nvidia-smi && nvidia-smi
          done"

# List of shell commands to run to set up nodes.
# NOTE: rayproject/ray-ml:latest has ray latest bundled
setup_commands: 
  - pip install gsutil
  - pip install gym_minigrid
    # - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp36-cp36m-manylinux2014_x86_64.whl
    # - pip install -U "ray[default] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl"

# Custom commands that will be run on the head node after common setup.
head_setup_commands:
  - pip install google-api-python-client==1.7.8

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - >-
      ulimit -n 65536;
      ray start
      --head
      --port=6379
      --object-manager-port=8076
      --autoscaling-config=~/ray_bootstrap_config.yaml

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - >-
      ulimit -n 65536;
      ray start
      --address=$RAY_HEAD_IP:6379
      --object-manager-port=8076
```
Then I set up the cluster:
```
ray up -y cloud-example-full.yaml
```
Afterwards I go on the driver and run `gsutil config` to enable access from the cluster to the GCS buckets.

Then I run the following script on the cluster 
```
import numpy as np
import ray
from ray import tune
from ray.rllib.agents import dqn
from ray.tune import register_env
import gym
from gym_minigrid.wrappers import FlatObsWrapper

def env_maker(config):
    name = config.get("name", "MiniGrid-Empty-5x5-v0")
    env = gym.make(name)
    # Flatten observations for usage in FC-nets.
    env = FlatObsWrapper(env)

    return env

register_env("mini-grid", env_maker)

ray.init(address="auto", local_mode=False, include_dashboard=True)

env = "MiniGrid-Empty-Random-6x6-v0"
config = dqn.DEFAULT_CONFIG.copy()
config["env"] = "mini-grid"
config["env_config"] = {
    "name": env,
}
layer_grid=[[32, 32], [64, 64], [128, 128]]
config["model"]["fcnet_hiddens"] = tune.grid_search(layer_grid)

results = tune.run(        
        "DQN",             
        config=config, 
        stop=stop, 
        verbose=1, 
        checkpoint_freq=5, 
        checkpoint_at_end=True,
        sync_config=tune.SyncConfig(
            sync_to_driver=False,
            upload_dir="gs://<BUCKET>/MiniGrid-Experiments/" + env + "/",
        )
)
```

### Anything else

Following the [issue here](https://github.com/GoogleCloudPlatform/gsutil/issues/290) for `rsync` brackets `[` and  `]` are interpreted as wildcards. I see that the default paths that are created for the trials of the different `fcnet_hiddens` sizes contain square brackets and this creates the issue. 

I use a hack now by defining via `trial_dirname_creator` my own trial names without brackets and that works. However, I would appreciate to use the default of `tune.run()` and I gues it is difficult for users to detect the cause of the error. 

Mayb we can change this into something less error-prone for `rsync`? Maybe just leaving away the brackets or using som other separators? 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by krfricke** [comment]
Thanks for raising this. We will be addressing this issue by going away from gsutil in the future. But I agree, we should make sure that the directory names are valid to use on any platform.

**Comment by simonsays1980** [comment]
@krfricke In relation to this: After running my experiment with 160 trials, it aborted due to `no space left on device`. 

It is in my opinion not easy to calculate up front the amount of space needed. That is why I chose to use a GCS bucket. I was not aware that the copies on the head node disk are kept. 

*Is it maybe possible to keep only the data in the GCS bucket instead of having it both on GCS and head node disk? Or maybe it needs not all data in the disk for `tune` to run?*

Also: I will use now `resume="AUTO"` in `tune.run()` to start from where it stopped. *How is it with the random generator in the environments? Is the state also kept somewhere?*

**Comment by krfricke** [comment]
I've opened a new issue to track this here: https://github.com/ray-project/ray/issues/23688
