### ISSUE TITLE
[RLlib] [Bug] IMPALA causes an OOM after a long running.

### ISSUE THREAD

**Issue by ZaberKo** [ray-project/ray#23769]
### What happened + What you expected to happen

When I train IMPALA, the program gets out of memory after a very lengthy period of time-steps (after 10000 iterations). The first error is like:
```
(ImpalaTrainer pid=850615) Exception in thread Thread-7:
(ImpalaTrainer pid=850615) Traceback (most recent call last):
(ImpalaTrainer pid=850615)   File "/home/zaber/mambaforge/envs/ray/lib/python3.9/threading.py", line 973, in _bootstrap_inner
(ImpalaTrainer pid=850615)     self.run()
(ImpalaTrainer pid=850615)   File "/home/zaber/mambaforge/envs/ray/lib/python3.9/site-packages/ray/rllib/execution/learner_thread.py", line 69, in run
(ImpalaTrainer pid=850615)     self.step()
(ImpalaTrainer pid=850615)   File "/home/zaber/mambaforge/envs/ray/lib/python3.9/site-packages/ray/rllib/execution/multi_gpu_learner_thread.py", line 143, in step
(ImpalaTrainer pid=850615)     buffer_idx, released = self.ready_tower_stacks_buffer.get()
(ImpalaTrainer pid=850615)   File "/home/zaber/mambaforge/envs/ray/lib/python3.9/site-packages/ray/rllib/execution/buffers/minibatch_buffer.py", line 46, in get
(ImpalaTrainer pid=850615)     self.buffers[self.idx] = self.inqueue.get(timeout=self.timeout)
(ImpalaTrainer pid=850615)   File "/home/zaber/mambaforge/envs/ray/lib/python3.9/queue.py", line 179, in get
(ImpalaTrainer pid=850615)     raise Empty
(ImpalaTrainer pid=850615) _queue.Empty
```
, then the memory increases until the process is killed by OOM (confirmed in netdata chart and `dmesg`). I also test it on two different machines, both of them will cause the OOM. I think the issue is around `MultiGPULearnerThread`.

### Versions / Dependencies

Python: 3.9.10
Ray: tested on 1.10.0 & 1.11.0
OS: Ubuntu 20.04

3rd Lib: None

### Reproduction script

The issue happens with `tune.run()` or manually training.

```python
# %%
from ray.rllib.agents.impala import ImpalaTrainer, DEFAULT_CONFIG
import ray
from ray import tune
ray.init(
    # include_dashboard=True,
    num_cpus=32,num_gpus=1)
# %%

config = DEFAULT_CONFIG.copy()
config.update({
    "framework": "torch",
    "num_gpus": 1,
    "num_workers": 16,
    "num_envs_per_worker": 5,
    "clip_rewards": True,
    "evaluation_num_workers": 4,
    "evaluation_interval": 100,
    "evaluation_duration": 20,
    "evaluation_config": {
        # "num_gpus_per_worker": 0.01,
        "explore": False
    },
    "env": "BreakoutNoFrameskip-v4",
    "rollout_fragment_length": 50,
    "train_batch_size": 500,

    "lr_schedule": [
        [0, 0.0005],
        [20000000, 0.000000000001]],
    "min_time_s_per_reporting":0,
    "timesteps_per_iteration":0,
    # "log_level": "DEBUG"
})


#%%
stop = {
    "training_iteration": 100000,
}

tune.run(ImpalaTrainer,config=config,stop=stop)


# %%
# or training manually
trainer = ImpalaTrainer(config=config)
for i in range(100000):
    res = trainer.train()
```

**Comment by gjoliver** [comment]
thanks for the report. we are aware of a potential memory leak in the framework.
we will update when we understand better about the problem.
one bandaid is that we are introducing recovery functionality after a worker fails, which should bring the crashed worker back automatically.

**Comment by ZaberKo** [comment]
Update: After test different config parameters, I found when the I stop using evaluation (by setting `evaluation_interval` to a large number), no OOM happens any more. Therefore, Is there something wrong with the "sync_weight" function from "workers" and "evaluation_workers"? I am aware that code here is a little bit tricky by overwriting the unwritable numpy arrays to pytorch tensors during syncing.

**Comment by ZaberKo** [comment]
By viewing the memory change in netdata and the logs in rllib output, I find that the `_queue.Empty` error happens first, then the memory starts blowing. So I guess some code raises an error, which leads to the death of some worker, then results in the OOM.

**Comment by gjoliver** [comment]
that's interesting.
does the old reproduce script still work? any chance you can help update the repro script, and we'd really love to take a look.
thanks for all the debugging so far.

**Comment by ZaberKo** [comment]
> that's interesting. does the old reproduce script still work? any chance you can help update the repro script, and we'd really love to take a look. thanks for all the debugging so far.

Yes, the script still work.

**Comment by gjoliver** [comment]
why not just limit the horizon of the episodes to a reasonable length?

**Comment by ZaberKo** [comment]
> why not just limit the horizon of the episodes to a reasonable length?

Yeah, I think currently that is enough. Although it is still not suitable for machine with low memory size(eg: 32GB memory is not enough for horizion=3000). For original horizon(400,000), I test on a machine with 512GB memory still results in an OOM. Besides, I thinks additional "tip" for setting a reasonable horizon should be added to the document.

**Comment by gjoliver** [comment]
I see. completely agree! thanks for all the detective work :)

**Comment by ZaberKo** [comment]
Any new updates for solving this issue?

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
