### ISSUE TITLE
[Clusters] - Connecting to AWS cluster via client throws Can't get attribute 'ParsedRuntimeEnv' on <module 'ray._private.runtime_env.validation'

### ISSUE THREAD

**Issue by jaidisido** [ray-project/ray#23773]
### What happened + What you expected to happen

I am following the instructions [here](https://docs.ray.io/en/latest/cluster/ray-client.html) to connect a client to my cluster on AWS.

I am able to:
- successfully setup the cluster
- connect to it via SSH

When I attempt to run this code:
```
import ray

ray.init("ray://localhost:10001")

ds = ray.data.read_csv("s3://nyc-tlc/trip data/fhv_tripdata_2015-01.csv")

print(ds.limit(100).to_pandas())
```

I receive this error which is a server side error complaining about tensorflow:
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    ray.init("ray://localhost:10001")
  File "/Users/jaidi/Documents/Sandbox/ray_datasets/.venv/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/jaidi/Documents/Sandbox/ray_datasets/.venv/lib/python3.8/site-packages/ray/worker.py", line 800, in init
    return builder.connect()
  File "/Users/jaidi/Documents/Sandbox/ray_datasets/.venv/lib/python3.8/site-packages/ray/client_builder.py", line 151, in connect
    client_info_dict = ray.util.client_connect.connect(
  File "/Users/jaidi/Documents/Sandbox/ray_datasets/.venv/lib/python3.8/site-packages/ray/util/client_connect.py", line 33, in connect
    conn = ray.connect(
  File "/Users/jaidi/Documents/Sandbox/ray_datasets/.venv/lib/python3.8/site-packages/ray/util/client/__init__.py", line 228, in connect
    conn = self.get_context().connect(*args, **kw_args)
  File "/Users/jaidi/Documents/Sandbox/ray_datasets/.venv/lib/python3.8/site-packages/ray/util/client/__init__.py", line 88, in connect
    self.client_worker._server_init(job_config, ray_init_kwargs)
  File "/Users/jaidi/Documents/Sandbox/ray_datasets/.venv/lib/python3.8/site-packages/ray/util/client/worker.py", line 697, in _server_init
    raise ConnectionAbortedError(
ConnectionAbortedError: Initialization failure from server:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/ray/util/client/server/proxier.py", line 656, in Datapath
    modified_init_req, job_config = prepare_runtime_init_req(init_req)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/ray/util/client/server/proxier.py", line 578, in prepare_runtime_init_req
    job_config = pickle.loads(req.job_config)
AttributeError: Can't get attribute 'ParsedRuntimeEnv' on <module 'ray._private.runtime_env.validation' from '/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/ray/_private/runtime_env/validation.py'>
```

The same error is raised whether using `<head_node_host>` or SSH port forwarding

I can run the same code on my local machine (i.e. without the cluster) and from within the cluster (i.e. after ssh into it). It's only when using the client that this fails.

I noticed that during the cluster setup, these errors were raised:
```
ERROR: tensorflow-serving-api 2.1.0 requires tensorflow~=2.1.0, which is not installed.
ERROR: tensorboard 2.2.2 has requirement google-auth<2,>=1.6.3, but you'll have google-auth 2.6.2 which is incompatible.
ERROR: virtualenv 20.14.0 has requirement filelock<4,>=3.2, but you'll have filelock 3.0.12 which is incompatible.
```
which might indicate that there is an issue with how tensorflow is installed on the underlying AMI

### Versions / Dependencies

```
Package             Version
------------------- --------
async-timeout       4.0.2
attrs               21.4.0
boto3               1.21.35
botocore            1.24.35
click               8.1.2
Deprecated          1.2.13
filelock            3.6.0
fsspec              2022.3.0
grpcio              1.43.0
importlib-resources 5.6.0
jmespath            1.0.0
jsonschema          4.4.0
msgpack             1.0.3
numpy               1.22.3
packaging           21.3
pandas              1.4.2
pip                 22.0.4
protobuf            3.20.0
pyarrow             6.0.1
pyparsing           3.0.7
pyrsistent          0.18.1
python-dateutil     2.8.2
pytz                2022.1
PyYAML              6.0
ray                 1.11.0
redis               4.2.2
s3transfer          0.5.2
setuptools          62.0.0
six                 1.16.0
urllib3             1.26.9
wheel               0.37.1
wrapt               1.14.0
zipp                3.8.0
```

Mac OS Catalina but the cluster is on AWS so I imagine uses an AWS AMI or ubuntu
Python 3.8 locally, but 3.7 I assume on the cluster

### Reproduction script

See above

**Comment by architkulkarni** [comment]
Hi @jaidisido , sorry you're running into this.  Can you check that the Ray versions used on the client and the cluster are the same?

**Comment by architkulkarni** [comment]
You can check this with `ray --version` or by `python -c "import ray; print(ray.__commit__); print(ray.__version__)"`

**Comment by architkulkarni** [comment]
I see, thanks for checking!  We unfortunately don't support different Ray versions on the client and on the cluster.  Feel free to reopen this if the issue persists when using the same version.
