### ISSUE TITLE
If an application exits with an exception, tons of error messages are printed.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#2383]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.13.5
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5.0
- **Python version**: Python 3.6.4 :: Anaconda, Inc.
- **Exact command to reproduce**: Run the following in a script (not interactively).

```python
import ray
ray.init()
raise Exception("HIHIHI")
```

This outputs

```
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:37009 to respond...
Waiting for redis server at 127.0.0.1:13754 to respond...
Starting local scheduler with the following resources: {'CPU': 8, 'GPU': 0}.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui30907.ipynb?token=f6ea550ebee5264243883e758e296d1066bc05879b43a5ed
======================================================================

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    raise Exception("HIHIHI")
Exception: HIHIHI
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 128.32.44.14:37009. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rkn/Workspace/ray/python/ray/worker.py", line 2081, in import_thread
    export_keys = worker.redis_client.lrange("Exports", 0, -1)
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 1347, in lrange
    return self.execute_command('LRANGE', name, start, end)
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 128.32.44.14:37009. Connection refused.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 128.32.44.14:37009. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rkn/Workspace/ray/python/ray/worker.py", line 2081, in import_thread
    export_keys = worker.redis_client.lrange("Exports", 0, -1)
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 1347, in lrange
    return self.execute_command('LRANGE', name, start, end)
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 128.32.44.14:37009. Connection refused.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 128.32.44.14:37009. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rkn/Workspace/ray/python/ray/worker.py", line 2081, in import_thread
    export_keys = worker.redis_client.lrange("Exports", 0, -1)
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 1347, in lrange
    return self.execute_command('LRANGE', name, start, end)
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 128.32.44.14:37009. Connection refused.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 128.32.44.14:37009. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rkn/Workspace/ray/python/ray/worker.py", line 2081, in import_thread
    export_keys = worker.redis_client.lrange("Exports", 0, -1)
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 1347, in lrange
    return self.execute_command('LRANGE', name, start, end)
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 128.32.44.14:37009. Connection refused.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 128.32.44.14:37009. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rkn/Workspace/ray/python/ray/worker.py", line 2081, in import_thread
    export_keys = worker.redis_client.lrange("Exports", 0, -1)
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 1347, in lrange
    return self.execute_command('LRANGE', name, start, end)
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 128.32.44.14:37009. Connection refused.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 128.32.44.14:37009. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rkn/Workspace/ray/python/ray/worker.py", line 2081, in import_thread
    export_keys = worker.redis_client.lrange("Exports", 0, -1)
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 1347, in lrange
    return self.execute_command('LRANGE', name, start, end)
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 128.32.44.14:37009. Connection refused.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 128.32.44.14:37009. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rkn/Workspace/ray/python/ray/worker.py", line 2081, in import_thread
    export_keys = worker.redis_client.lrange("Exports", 0, -1)
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 1347, in lrange
    return self.execute_command('LRANGE', name, start, end)
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 128.32.44.14:37009. Connection refused.
```

cc @joschu

**Comment by robertnishihara** [comment]
No longer an issue.
