### ISSUE TITLE
[RLlib] Actions are passed by reference and are vulnerable to user manipulations

### ISSUE THREAD

**Issue by simonsays1980** [ray-project/ray#23890]
### What happened + What you expected to happen

# What happened
I needed for my problem setting a `MultiDiscrete` action space (actually it was a `Tuple`  with a `MultiDiscrete`  part in it) that contains positive and negative values. What I did then in my environment's `step()` function was to set my acttion values appropriately: 
```
action[0][action[0] == 2] = -1
```
I then got a repeating error by the `PPO` algorithm: 
```
Traceback (most recent call last):
  File "/home/simon/git-projects/ray/.venv/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1377, in _do_call
    return fn(*args)
  File "/home/simon/git-projects/ray/.venv/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1360, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/home/simon/git-projects/ray/.venv/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Received a label value of -1 which is outside the valid range of [0, 3).  Label values: 1 0 0 1 0 1 0 0 -1 -1 1 -1 0 1 0 -1 -1 -1 -1 -1 -1 -1 0 0 1 -1 1 0 -1 1 -1 -1 -1 -1 1 -1 1 0 1 -1 -1 1 1 1 0 -1 -1 1 -1 0 1 -1 1 -1 -1 -1 -1 1 0 0 1 -1 -1 0 0 0 1 0 -1 1 -1 0 1 -1 0 1 -1 1 0 0 0 -1 1 -1 0 0 -1 0 1 -1 1 1 0 0 1 1 1 -1 0 0 -1 -1 1 0 0 1 1 -1 -1 -1 0 0 -1 1 1 0 -1 1 -1 0 1 1 0 -1 1 0 -1 1
         [[{{node default_policy/SparseSoftmaxCrossEntropyWithLogits_45/SparseSoftmaxCrossEntropyWithLogits}}]]
```
I debugged through the source code and traced back the actions towards the `_set_last_action()` function of the `Episode` class and everywhere the action values were inside the allowed range. I couldn't find a single line of code that somehow would change this. 

The error happens in the `ppo_tf_policy.py` at this line: 
```
logp_ratio = tf.exp(
        curr_action_dist.logp(train_batch[SampleBatch.ACTIONS])
        - train_batch[SampleBatch.ACTION_LOGP]
)
```
In there the actions in the sample batch are already in an invalid range. These are the actions that get packed into the sample batch via the `_set_lat_action()` method of the `Episode` class. This was at first not explainable to me. 

## The reason for the observed behavior
Then I figured out that the `action` is passed by a reference to the `step()` function of the environment and as soon as it is changed inside of the latter function it changes also inside the `SampleBatch` in the core of `RLlib`. 

# What I expected to happen
I expected that inside the user provided part of code (the environment, the user's problem setting) I could manipulate objects as needed without any danger of algorithms breaking.

### Versions / Dependencies

Linux Fedora 35
Python 3.9.0
ray 1.11.0

### Reproduction script

```
import ray
import gym
import numpy as np

from ray.rllib.agents.ppo import ppo
from ray import tune

class NonTupleAcionEnv(gym.Env): 
    
    def __init__(self, env_config=None):
        config = env_config or {}
        super().__init__()
        
        self.observation_space = gym.spaces.Box(low=-np.inf, high=np.inf, shape=(5,), dtype=np.float32)
        self.action_space = gym.spaces.MultiDiscrete([3]*5)
        self.episode_len = config.get('episode_len', 10)
        self.timesteps = 0
        
    def reset(self):
        self.timesteps = 0        
        return self.observation_space.sample()
    
    def step(self, action):
        self.timesteps += 1
        # Comment this out and the code runs without an error.
        action[action == 2] = -1
        if self.timesteps == self.episode_len:
            done = True
        else:
            done = False
        
        rn = self.observation_space.sample()
        rn2 = np.random.random(size=(5,)) * action[1] + action[0]
        
        if np.all(rn2 - rn) <= .01:
            reward = 1
        else: 
            reward = -1
            
        return rn, reward, done, {}

tune.registry.register_env("non_tuple_action_env", lambda config: NonTupleAcionEnv(config))

config = ppo.DEFAULT_CONFIG.copy()
config["num_workers"] = 0
config["env"] = "non_tuple_action_env"

ray.init(local_mode=True)
tune.run("PPO", config=config, stop={"episodes_total": 10})
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by simonsays1980** [comment]
@sven1977 @gjoliver @avnishn 
My suggestion is to pass the action via a copy (I will provide a PR) such that the user can manipulate on his part of the code objects as needed to get the best representation of his/her problem setting and at the same time does not need to fear a break in the RL algorithm.

This becomes possibly obsolete when the `Connectors` are available and therein actions can be transformed via a copy. 

Right now I have made a fix in the `sample.py` in the `_env_runner()` function at 
``` 
base_env.send_actions(deepcopy(actions_to_send))
```
which fixes the error, but I have the feeling that everything becomes slower. Open for suggestions.

**Comment by ArturNiederfahrenhorst** [comment]
Mhhhh deepcopy is not the cheapest op although I see it at some points in RLlib. If we consider this, we should definitely time it since sending actions is super frequent.

**Comment by simonsays1980** [comment]
> Mhhhh deepcopy is not the cheapest op although I see it at some points in RLlib. If we consider this, we should definitely time it since sending actions is super frequent.

It looks better though now where I have restarted the appropriate environment. Dropped from 15s to 9s.

**Comment by simonsays1980** [comment]
> this would be much easier once we have action connectors. I also share Arthur's concerns that we probably don't want to do this by default for all envs. you can write an env wrapper for your specific use case?

@gjoliver Thanks for the hint to the Env Wrapper. I can write an env wrapper for this. Also, because I am now  aware of it. I share your concerns in regard to deep copies especially when actions become larger. But on the other hand, the user does not know about this behavior and even later on with connectors it will not be the default that `action` is an object on its own manipulable at will of the user. So, I expect such behavior to occur more often with new users.

**Comment by gjoliver** [comment]
ah I see. actually action connectors are designed to transform actions computed, things like convert_to_numpy, clip_action etc.
so it will be a pretty obvious place to do this if necessary. and we won't need to have this behavior on by default for everyone.
does that sound good to you?

**Comment by simonsays1980** [comment]
@gjoliver Technically, your idea is a very good solution. I like this solution as it keeps my environment clean and does so with the algorithm.

**Comment by gjoliver** [comment]
100% agree!! if this is any other language, we will simply mark the actions as constants when we send them. and any modification will have to be done on a copy.
sometimes I am really like 🤷 about Python.

**Comment by sven1977** [comment]
Great catch @simonsays1980 , I agree w/ @gjoliver here, this should be set on a per-use-case basis somewhere (connectors), where the user can fully control this.
After all, the env is also under the users control and probably should not alter incoming actions. I also don't feel save about deepcopying actions per-se (normally, yes, actions are very small (ints?), but this is not always the case). Btw, isn't there a way to make numpy arrays non-writable? :)
https://stackoverflow.com/questions/5541324/immutable-numpy-array

**Comment by simonsays1980** [comment]
@sven1977 Perfect solution, I am with you guys that making deep copies could harm the overall performance and is in most use cases not necessary. 
The main use cases (use case is actually not even the right meaning here) where altering actions are needed are some where the environment is coded for a custom policy that sends actions in with maybe negative numbers. Imagine for example a market environment where a policy can buy or sell. The sign of the action might then be used in the environment for calculations. Plugging in now an RLlib algorithm that learns a policy and sends only positive valued actions (discrete action spaces) needs a special handling then. 
I have never used this, but is probably action masking a way to deal also with such problems? 

Concluding, I think that setting the flags to non-writable is a good solution. It prevents tough-traceable errors for the users (less frustration) and maintains performance. We could provide a note in the docs that helps users to alter actions if needed. I could prepare a PR with this - maybe you could point me to the best point where to make actions unwritable (would choose the `_env_runner`).

**Comment by gjoliver** [comment]
sounds great, in _env_runner right before we send_action may be the best.

**Comment by simonsays1980** [comment]
During implementation and testing I found out that the actions get deep-copied anyway as at some point they were not anymore immutable. I traced it back to the [`postprocess_episode()`](https://github.com/ray-project/ray/blob/f7be4094629a149c583e9d5bd1bb77fe883cd505/rllib/evaluation/sampler.py#L1002) method of the `SimpleListCollector`. 

Anyway, my implementation will use the `_env_runner()` as the position where to make actions immutable as the main goal here is to avoid any mutation inside the `env.step()` function that could be triggred by the user.

**Comment by simonsays1980** [comment]
I close this issue as the discussion here is clear and the solution from the PR #24262 gives the user direction.
