### ISSUE TITLE
[tune] No supported kernel for GPU devices is available.

### ISSUE THREAD

**Issue by tickpeach** [ray-project/ray#2392]
### System information
- **OS Platform and Distribution ** : Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5.0
- **Python version**: 3.5.2
- **Exact command to reproduce**: 

### Describe the problem
Can not run ray example with GPU.

#### Code
```
"""Example of a custom gym environment. Run this for a demo."""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import gym
from gym.spaces import Discrete, Box
from gym.envs.registration import EnvSpec

import ray
from ray.tune import run_experiments
from ray.tune.registry import register_env


class SimpleCorridor(gym.Env):
    """Example of a custom env in which you have to walk down a corridor.
    You can configure the length of the corridor via the env config."""

    def __init__(self, config):
        self.end_pos = config["corridor_length"]
        self.cur_pos = 0
        self.action_space = Discrete(2)
        self.observation_space = Box(
            0.0, self.end_pos, shape=(1,), dtype=np.float32)
        self._spec = EnvSpec("SimpleCorridor-{}-v0".format(self.end_pos))

    def reset(self):
        self.cur_pos = 0
        return [self.cur_pos]

    def step(self, action):
        assert action in [0, 1]
        if action == 0 and self.cur_pos > 0:
            self.cur_pos -= 1
        elif action == 1:
            self.cur_pos += 1
        done = self.cur_pos >= self.end_pos
        return [self.cur_pos], 1 if done else 0, done, {}


if __name__ == "__main__":
    env_creator_name = "corridor"
    register_env(env_creator_name, lambda config: SimpleCorridor(config))
    ray.init()
    run_experiments({
        "demo": {
            "run": "PPO",
            "env": "corridor",
            "config": {
                "env_config": {
                    "corridor_length": 5,
                },
                'num_gpus': 2,
            },
        },
    })
```

#### Error log
```
Starting local scheduler with the following resources: {'GPU': 2, 'CPU': 16}.
...
LocalMultiGPUOptimizer devices ['/gpu:0', '/gpu:1']
LocalMultiGPUOptimizer batch size 128
Remote function __init__ failed with:
...

File "/home/me/.virtualenvs/test/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'default_1/tower_1/Slice_3': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='CPU'; T in [DT_QINT32]
  device='CPU'; T in [DT_QUINT8]
  device='CPU'; T in [DT_QINT8]
  device='CPU'; T in [DT_STRING]
  device='CPU'; T in [DT_BOOL]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_INT8]
  device='CPU'; T in [DT_UINT8]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_UINT16]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_INT64]
  device='GPU'; T in [DT_INT32]; Index in [DT_INT32]
  device='GPU'; T in [DT_BFLOAT16]; Index in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX128]; Index in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX64]; Index in [DT_INT32]
  device='GPU'; T in [DT_DOUBLE]; Index in [DT_INT32]
  device='GPU'; T in [DT_FLOAT]; Index in [DT_INT32]
  device='GPU'; T in [DT_HALF]; Index in [DT_INT32]

	 [[Node: default_1/tower_1/Slice_3 = Slice[Index=DT_INT32, T=DT_INT64, _device="/device:GPU:0"](default_1/tower_1/Variable_3/read, default_1/tower_1/Slice_3/begin, default_1/tower_1/Slice_3/size)]]

```

**Comment by richardliaw** [comment]
To specify GPU/resource usage, you'll have to include `trial_resources` like follows:

```
    run_experiments({
        "demo": {
            "run": "PPO",
            "env": "corridor",
            "config": {
                "env_config": {
                    "corridor_length": 5,
                }
            },
            "trial_resources": { 
                'num_gpus': 2,
            },
        },
    })
```
Let me know if this works, and if it does, let me know if you have any suggestions to the documentation to make this clearer!

**Comment by tickpeach** [comment]
Please see the error log in the following:
```
Traceback (most recent call last):
  File "main.py", line 74, in <module>
    'num_gpus': 2,
  File "/home/me/.virtualenvs/test/lib/python3.5/site-packages/ray/tune/tune.py", line 83, in run_experiments
    scheduler.add_experiment(experiment, runner)
  File "/home/me/.virtualenvs/test/lib/python3.5/site-packages/ray/tune/trial_scheduler.py", line 62, in add_experiment
    trial_runner.add_trial(next(generator))
  File "/home/me/.virtualenvs/test/lib/python3.5/site-packages/ray/tune/variant_generator.py", line 53, in generate_trials
    args = parser.parse_args(to_argv(spec))
  File "/usr/lib/python3.5/argparse.py", line 1735, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.5/argparse.py", line 1767, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.5/argparse.py", line 1973, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.5/argparse.py", line 1913, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.5/argparse.py", line 1825, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.5/argparse.py", line 2266, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.5/argparse.py", line 2295, in _get_value
    result = type_func(arg_string)
  File "/home/me/.virtualenvs/test/lib/python3.5/site-packages/ray/tune/config_parser.py", line 26, in json_to_resources
    k, Resources._fields))
ray.tune.error.TuneError: Unknown resource type num_gpus, must be one of ('cpu', 'gpu', 'extra_cpu', 'extra_gpu')
/ray/src/local_scheduler/local_scheduler.cc:177: Killed worker pid 5442 which hadn't started yet.
/ray/src/local_scheduler/local_scheduler.cc:177: Killed worker pid 5443 which hadn't started yet.
/ray/src/local_scheduler/local_scheduler.cc:177: Killed worker pid 5444 which hadn't started yet.
/ray/src/local_scheduler/local_scheduler.cc:177: Killed worker pid 5445 which hadn't started yet.
/ray/src/local_scheduler/local_scheduler.cc:177: Killed worker pid 5446 which hadn't started yet.
/ray/src/local_scheduler/local_scheduler.cc:177: Killed worker pid 5447 which hadn't started yet.
/ray/src/local_scheduler/local_scheduler.cc:177: Killed worker pid 5448 which hadn't started yet.
/ray/src/local_scheduler/local_scheduler.cc:177: Killed worker pid 5449 which hadn't started yet.
/ray/src/local_scheduler/local_scheduler.cc:177: Killed worker pid 5450 which hadn't started yet.
/ray/src/local_scheduler/local_scheduler.cc:177: Killed worker pid 5451 which hadn't started yet.
/ray/src/local_scheduler/local_scheduler.cc:177: Killed worker pid 5452 which hadn't started yet.
/ray/src/local_scheduler/local_scheduler.cc:177: Killed worker pid 5453 which hadn't started yet.
```

**Comment by ericl** [comment]
Ah, this is because `slice` is a CPU-only op. Normally this is fine, but it seems we lost the `allow_soft_placement` TensorFlow session option during recent refactoring.

Should be fixed by https://github.com/ray-project/ray/pull/2395/files

**Comment by tickpeach** [comment]
Solved by [.](https://github.com/ray-project/ray/pull/2395/files) Thanks!
