### ISSUE TITLE
[Datasets] ray.data.read_datasource(source, n=10, num_columns=2).take() leaded to "TypeError: __init__() missing 1 required keyword-only argument: 'exec_stats'" on Ray 1.12.0

### ISSUE THREAD

**Issue by Kuroakira** [ray-project/ray#23966]
### What happened + What you expected to happen

Hi It's my first issue post. 
I started to use ray a few weeks ago and I'm trying to run the codes of the examples in the documents. 
I have a problem in [Example: Large-scale ML Ingest](https://docs.ray.io/en/latest/data/examples/big_data_ingestion.html). 
When I run the code below, I got a error message, which is "TypeError: __init__() missing 1 required keyword-only argument: 'exec_stats'". 

```
   def generate_example_files(size_bytes: int) -> str:
        tmpdir = tempfile.mkdtemp()
        ray.data.read_datasource(
            RandomIntRowDatasource(),
            n=size_bytes // 8 // NUM_COLUMNS,
            num_columns=NUM_COLUMNS,
        ).write_parquet(tmpdir)
        return tmpdir

    example_files_dir = generate_example_files(SIZE_100MiB)
```

The error occured was below.

```
---------------------------------------------------------------------------
RayTaskError(TypeError)                   Traceback (most recent call last)
/tmp/ipykernel_290/57431372.py in <module>
      1 source = RandomIntRowDatasource()
----> 2 ray.data.read_datasource(source, n=10, num_columns=2).take()

/usr/local/lib/python3.7/site-packages/ray/data/read_api.py in read_datasource(datasource, parallelism, ray_remote_args, **read_args)
    234                 ctx,
    235                 parallelism,
--> 236                 _wrap_arrow_serialization_workaround(read_args),
    237             )
    238         )

/usr/local/lib/python3.7/site-packages/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
    102             # we only convert init function if RAY_CLIENT_MODE=1
    103             if func.__name__ != "init" or is_client_mode_enabled_by_default:
--> 104                 return getattr(ray, func.__name__)(*args, **kwargs)
    105         return func(*args, **kwargs)
    106 

/usr/local/lib/python3.7/site-packages/ray/util/client/api.py in get(self, vals, timeout)
     41             timeout: Optional timeout in milliseconds
     42         """
---> 43         return self.worker.get(vals, timeout=timeout)
     44 
     45     def put(self, *args, **kwargs):

/usr/local/lib/python3.7/site-packages/ray/util/client/worker.py in get(self, vals, timeout)
    431                 op_timeout = MAX_BLOCKING_OPERATION_TIME_S
    432             try:
--> 433                 res = self._get(to_get, op_timeout)
    434                 break
    435             except GetTimeoutError:

/usr/local/lib/python3.7/site-packages/ray/util/client/worker.py in _get(self, ref, timeout)
    459                         logger.exception("Failed to deserialize {}".format(chunk.error))
    460                         raise
--> 461                     raise err
    462                 if chunk.total_size > OBJECT_TRANSFER_WARNING_SIZE and log_once(
    463                     "client_object_transfer_size_warning"

RayTaskError(TypeError): ray::_prepare_read() (pid=2228, ip=10.76.2.18)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/read_api.py", line 902, in _prepare_read
    return ds.prepare_read(parallelism, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/datasource/datasource.py", line 331, in prepare_read
    input_files=None,
TypeError: __init__() missing 1 required keyword-only argument: 'exec_stats'
```

I used python3.7.7 and ray 1.12.0 then.
And I used a jupyterlab kernel on the k8s which accessed to the ray-head built by Helm.

Is the error related to the environment or just a bug or ray? 
Please help me

### Versions / Dependencies

- python:3.7.7
- ray:1.12.0

### Reproduction script

import ray
from ray.data.dataset_pipeline import DatasetPipeline
from ray.data.datasource.datasource import RandomIntRowDatasource

ray.init("ray://example-cluster-ray-head.ray:10001")

source = RandomIntRowDatasource()
ray.data.read_datasource(source, n=10, num_columns=2).take()

**Comment by matthewdeng** [comment]
@Kuroakira can you verify that you've upgraded to ray 1.12.0 on both your cluster and your jupyter environment? This looks like a dependency mismatch!

**Comment by Kuroakira** [comment]
@matthewdeng 
Thanks for your replying. I've checked the installed ray on each environment(jupyter, header, worker)
All of the versions were 1.12.0... 
Was the way to check the versions wrong??

The version check logs are below.

```
hogehoge@cloudshell:~$ kubectl get pod -n ray
NAME                                    READY   STATUS    RESTARTS   AGE
example-cluster-ray-head-type-x6tzm     1/1     Running   0          78m
example-cluster-ray-worker-type-sxlwz   1/1     Running   0          78m
hogehoge@cloudshell:~$ kubectl -n ray exec -it example-cluster-ray-head-type-x6tzm -- bash
(base) ray@example-cluster-ray-head-type-x6tzm:~$ python
Python 3.7.7 (default, May  7 2020, 21:25:33)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.__version__
'1.12.0'
>>> exit()
(base) ray@example-cluster-ray-head-type-x6tzm:~$ exit
exit
hogehoge@cloudshell:~$ kubectl -n ray exec -it example-cluster-ray-worker-type-sxlwz -- bash
(base) ray@example-cluster-ray-worker-type-sxlwz:~$ python
Python 3.7.7 (default, May  7 2020, 21:25:33)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.__version__
'1.12.0'
>>> exit()
(base) ray@example-cluster-ray-worker-type-sxlwz:~$ exit
akira_shirahama@cloudshell:~$ kubectl get pod -n jlab
NAME      READY   STATUS    RESTARTS   AGE
jlab-pd   1/1     Running   0          103m
hogehoge@cloudshell:~$ kubectl -n jlab exec -it jlab-pd -- bash
Defaulted container "jlab" out of: jlab, initial-setting (init)
root@jlab-pd:/# python
Python 3.7.7 (default, Jun  9 2020, 17:58:51)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.__version__
'1.12.0'
>>>
```

**Comment by Kuroakira** [comment]
To identify the problem, I've installed jupyter notebook on the ray-head and run the same code. But I got the same error.

```
RayTaskError(TypeError)                   Traceback (most recent call last)
/tmp/ipykernel_2423/1031406170.py in <module>
     18         return tmpdir
     19 
---> 20     example_files_dir = generate_example_files(SIZE_100MiB)
     21 
     22     splits = create_shuffle_pipeline(

/tmp/ipykernel_2423/1031406170.py in generate_example_files(size_bytes)
     14             RandomIntRowDatasource(),
     15             n=size_bytes // 8 // NUM_COLUMNS,
---> 16             num_columns=NUM_COLUMNS,
     17         ).write_parquet(tmpdir)
     18         return tmpdir

~/anaconda3/lib/python3.7/site-packages/ray/data/read_api.py in read_datasource(datasource, parallelism, ray_remote_args, **read_args)
    234                 ctx,
    235                 parallelism,
--> 236                 _wrap_arrow_serialization_workaround(read_args),
    237             )
    238         )

~/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
    103             if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104                 return getattr(ray, func.__name__)(*args, **kwargs)
--> 105         return func(*args, **kwargs)
    106 
    107     return wrapper

~/anaconda3/lib/python3.7/site-packages/ray/worker.py in get(object_refs, timeout)
   1807                     worker.core_worker.dump_object_store_memory_usage()
   1808                 if isinstance(value, RayTaskError):
-> 1809                     raise value.as_instanceof_cause()
   1810                 else:
   1811                     raise value

RayTaskError(TypeError): ray::_prepare_read() (pid=2567, ip=10.76.2.18)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/read_api.py", line 902, in _prepare_read
    return ds.prepare_read(parallelism, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/datasource/datasource.py", line 331, in prepare_read
    input_files=None,
TypeError: __init__() missing 1 required keyword-only argument: 'exec_stats'
```
