### ISSUE TITLE
[rllib] 

### ISSUE THREAD

**Issue by RenardDesNeiges** [ray-project/ray#23970]
### What happened + What you expected to happen

I'm generating training data for behavioral cloning using PPO and the default MLP model of RLLIB in cartpole-v1. And I'm encountering seemingly random crashes. In training, the error is always of the form:

**traceback from ray tune**

```
Traceback (most recent call last):
  File "tune_expert_train.py", line 60, in <module>
    tune.run(PPOTrainer, config=config)
  File "/Users/renard/miniconda3/envs/torchLTC/lib/python3.8/site-packages/ray/tune/tune.py", line 695, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPOTrainer_CartPole-v1_47830_00000])
```

**error report (from the logs)**
```
Failure # 1 (occurred at 2022-04-18_14-19-53)
Traceback (most recent call last):
  File "/Users/renard/miniconda3/envs/torchLTC/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 901, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/Users/renard/miniconda3/envs/torchLTC/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/renard/miniconda3/envs/torchLTC/lib/python3.8/site-packages/ray/worker.py", line 1809, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): [36mray::PPOTrainer.train()[39m (pid=15807, ip=127.0.0.1, repr=PPOTrainer)
  File "/Users/renard/miniconda3/envs/torchLTC/lib/python3.8/site-packages/ray/tune/trainable.py", line 349, in train
    result = self.step()
  File "/Users/renard/miniconda3/envs/torchLTC/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1093, in step
    raise e
  File "/Users/renard/miniconda3/envs/torchLTC/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1074, in step
    step_attempt_results = self.step_attempt()
  File "/Users/renard/miniconda3/envs/torchLTC/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1189, in step_attempt
    step_results.update(self.evaluate())
  File "/Users/renard/miniconda3/envs/torchLTC/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1260, in evaluate
    self._sync_filters_if_needed(self.evaluation_workers)
  File "/Users/renard/miniconda3/envs/torchLTC/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 2147, in _sync_filters_if_needed
    workers.local_worker().filters,
AttributeError: 'NoneType' object has no attribute 'filters'
```

I'm running ray 1.12.0 with python 3.8.12 and gym 0.21.0. The error is reproducible across different gym environments (I tested pendulum, mountain-car and acrobot) and I encountered it both on my macOS Catalina laptop and on my lab's Ubuntu 18.04's machines. Any idea of what's going on there / of a fix?

### Versions / Dependencies

Ray 1.12.0 (note that I upgraded in an attempt to fix the bug but I also encountered it in 1.11.0)
OpenAI gym 0.21.0
Python 3.8.12

### Reproduction script

import ray
from ray import tune
from ray.rllib.agents.ppo import PPOTrainer
from ray.rllib.models import ModelCatalog

#where to save the generated trajectory
output_directory = "~/ray_results/perceptron_baseline"

NUM_CPUS = 8 # changed based on PC / cluster
num_samples_each_worker = int(16384 / NUM_CPUS)

# environment config (PPO tune baselines)
config = {
    "num_envs_per_worker": 1, 
    "use_critic": True,
    # If true, use the Generalized Advantage Estimator (GAE)
    # with a value function, see https://arxiv.org/pdf/1506.02438.pdf.
    "use_gae": True,
    "lr": 1e-4,
    "ignore_worker_failures": True,
    "env": "CartPole-v1", # Environment
    "num_workers": NUM_CPUS, # number of worker envs
    "train_batch_size": NUM_CPUS*num_samples_each_worker, 
    "num_sgd_iter": 10,
    "rollout_fragment_length": num_samples_each_worker,
    # Either "adam" or "rmsprop".
    "vf_loss_coeff": 0.5,
    "lambda":0.95, 
    "grad_clip": 0.5, 
    #"use_kl_loss": False,
    # "kl_coeff": 0.0, 
    # "kl_target": 0.01,
    "entropy_coeff": 0.0,
    "observation_filter": "MeanStdFilter", # normalize observation space (very important)
    "clip_actions": True,
    "num_sgd_iter": 10,
    "clip_param": 0.2,
    "vf_clip_param": 40, # may need to increase depending on your reward scaling
    "sgd_minibatch_size": 256,
    "framework": "torch", # we run pytorch, not tensorflow
    "evaluation_interval": 20,
    "evaluation_num_workers": 1,
    # Only for evaluation runs, render the env.
    "output": output_directory,
    "evaluation_config": {
        "render_env": False,
    }
}

print("Training a baseline PPO net and saving (s,a) to {}".format(output_directory))

# ray code
ray.init(local_mode=False)
# Instanciate the PPO trainer object
tune.run(PPOTrainer, config=config)

### Issue Severity

High: It blocks me from completing my task.

**Comment by sven1977** [comment]
Hey @RenardDesNeiges , thanks for filing this. Definitely a bug! It's happening b/c evaluation worker sets now do not contain a local worker by default anymore (only if `evaluation_num_workers==0`).
Will provide a fix.

**Comment by RenardDesNeiges** [comment]
Oh, alright that gives me an easy fix thanks a lot!
