### ISSUE TITLE
[Core][Bug] `release/nightly_tests/dataset/sort.py` fails with 2000 partitions

### ISSUE THREAD

**Issue by mwtian** [ray-project/ray#24021]
### What happened + What you expected to happen

Running the sort benchmark with 2000 partitions (`RAY_max_direct_call_object_size=128 TEST_OUTPUT_JSON=/tmp/release_test_out.json python release/nightly_tests/dataset/sort.py --num-partitions=2000 --partition-size=1e7 --shuffle`) currently fails on latest `master`:
```
Dataset size: 2000 partitions, 0.01GB partition size, 20.0GB total
2022-04-19 18:56:10,621 INFO services.py:1460 -- View the Ray dashboard at http://127.0.0.1:8265
Shuffle Map:   4%|███████▋                                                                                                                                                                                                  | 76/2000 [01:09<19:28,  1.65it/s]
Shuffle Map:  17%|██████████████████████████████████                                                                                                                                                                       | 339/2000 [03:46<18:36,  1.49it/s]
(map pid=2343895) Traceback (most recent call last):
(map pid=2343895)   File "python/ray/_raylet.pyx", line 728, in ray._raylet.execute_task
(map pid=2343895)     with core_worker.profile_event(b"task:store_outputs"):
(map pid=2343895)   File "python/ray/_raylet.pyx", line 729, in ray._raylet.execute_task
(map pid=2343895)     core_worker.store_task_outputs(
(map pid=2343895)   File "python/ray/_raylet.pyx", line 2043, in ray._raylet.CoreWorker.store_task_outputs
(map pid=2343895)     if not self.store_task_output(
(map pid=2343895)   File "python/ray/_raylet.pyx", line 1981, in ray._raylet.CoreWorker.store_task_output
(map pid=2343895)     check_status(
(map pid=2343895)   File "python/ray/_raylet.pyx", line 175, in ray._raylet.check_status
(map pid=2343895)     raise RaySystemError(message)
(map pid=2343895) ray.exceptions.RaySystemError: System error: Connection reset by peer
(map pid=2343895)
(map pid=2343895) During handling of the above exception, another exception occurred:
(map pid=2343895)
(map pid=2343895) Traceback (most recent call last):
(map pid=2343895)   File "python/ray/_raylet.pyx", line 799, in ray._raylet.task_execution_handler
(map pid=2343895)     execute_task(task_type, task_name, ray_function, c_resources,
(map pid=2343895)   File "python/ray/_raylet.pyx", line 618, in ray._raylet.execute_task
(map pid=2343895)     with core_worker.profile_event(b"task::" + name, extra_data=extra_data):
(map pid=2343895)   File "python/ray/_raylet.pyx", line 754, in ray._raylet.execute_task
(map pid=2343895)     core_worker.store_task_outputs(
(map pid=2343895)   File "python/ray/_raylet.pyx", line 2043, in ray._raylet.CoreWorker.store_task_outputs
(map pid=2343895)     if not self.store_task_output(
(map pid=2343895)   File "python/ray/_raylet.pyx", line 1981, in ray._raylet.CoreWorker.store_task_output
(map pid=2343895)     check_status(
(map pid=2343895)   File "python/ray/_raylet.pyx", line 175, in ray._raylet.check_status
(map pid=2343895)     raise RaySystemError(message)
(map pid=2343895) ray.exceptions.RaySystemError: System error: Broken pipe
(map pid=2343895)
(map pid=2343895) During handling of the above exception, another exception occurred:
............
2022-04-19 19:00:31,289 WARNING worker.py:1392 -- The node with node id: f01e8bdfa28dbc83c75c6fa815602cc719f7dc41b0ae8de6b8cfc2a0 and address: 172.31.44.134 and node name: 172.31.44.134 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.
[2022-04-19 19:00:31,300 E 2342488 2343619] core_worker.cc:1069: Failed to release ObjectID (00ffffffffffffffffffffffffffffffffffffff01000000940d0000), might cause a leak in plasma.
[2022-04-19 19:00:31,300 E 2342488 2343619] core_worker.cc:1069: Failed to release ObjectID (00ffffffffffffffffffffffffffffffffffffff01000000950d0000), might cause a leak in plasma.
[2022-04-19 19:00:31,300 E 2342488 2343619] core_worker.cc:1069: Failed to release ObjectID (00ffffffffffffffffffffffffffffffffffffff01000000960d0000), might cause a leak in plasma.
[2022-04-19 19:00:31,300 E 2342488 2343619] core_worker.cc:1069: Failed to release ObjectID (00ffffffffffffffffffffffffffffffffffffff01000000970d0000), might cause a leak in plasma.
............
```

### Versions / Dependencies

Ray latest master, Python 3.8.12, Ubuntu 20.04, m5.8xlarge

### Reproduction script
```
RAY_max_direct_call_object_size=128 TEST_OUTPUT_JSON=/tmp/release_test_out.json python release/nightly_tests/dataset/sort.py --num-partitions=2000 --partition-size=1e7 --shuffle
```

**Comment by mwtian** [comment]
cc @stephanie-wang @jjyao

**Comment by mwtian** [comment]
After preliminary investigations, the issue is probably due to raylet missing heartbeat to GCS. Raylet's GCS client uses the raylet's main event loop, which becomes very busy when there are >= 2.8M object refs. We can look into using separate event loop for reporting heartbeat. Optimizing the communication pattern when a raylet owns a large number of object refs should be helpful in other areas too.

**Comment by stephanie-wang** [comment]
Hmm I see! I wonder if this will be a problem in a larger cluster setting, though, when hopefully the object ref overhead will be spread across all the raylets.

**Comment by mwtian** [comment]
The busiest handlers on the raylet are `ObjectManager.ObjectAdded` and `NodeManagerService.grpc_server.PinObjectIDs`. If they are associated not with the object owners, but with task workers, then the overhead will definitely be less when there are more raylets.

**Comment by stephanie-wang** [comment]
Nice, yeah, those would be called whenever a task returns an object. So it sounds like this issue is okay for now, although we should fix the heartbeat issue like you said. Do you want to open an issue for this on the Ray core backlog? I think it's been a known problem for a while but I don't see a definitive issue for it.

**Comment by mwtian** [comment]
Sounds good. Let me try a quick fix for the heartbeat problem and close this issue with it. If a quick fix is hard, I will open a separate issue.

**Comment by stephanie-wang** [comment]
@mwtian, do you know if #24928 fixes this issue?
