### ISSUE TITLE
[RLlib, Tune] [Bug] Segmentation Fault when running PPO, issue disappears after downgrading to 1.11.0

### ISSUE THREAD

**Issue by gutfeeling** [ray-project/ray#24028]
### What happened + What you expected to happen

I was using PPO on `BipedalWalker-v3` using `tune.run()`. This works fine on version 1.9.1 and 1.11.0. But on 1.12.0, I immediately get segmentation faults. 

```
2022-04-20 00:11:05,473	INFO trial_runner.py:803 -- starting PPO_BipedalWalker-v3_9a5ba_00000
(PPOTrainer pid=11661) 2022-04-20 00:11:08,187	INFO trainer.py:2295 -- Your framework setting is 'tf', meaning you are using static-graph mode. Set framework='tf2' to enable eager execution with tf2.x. You may also then want to set eager_tracing=True in order to reach similar execution speed as with static-graph mode.
(PPOTrainer pid=11661) 2022-04-20 00:11:08,187	WARNING deprecation.py:46 -- DeprecationWarning: `evaluation_num_episodes` has been deprecated. Use ``evaluation_duration` and `evaluation_duration_unit=episodes`` instead. This will raise an error in the future!
(PPOTrainer pid=11661) 2022-04-20 00:11:08,187	WARNING ppo.py:240 -- `train_batch_size` (4000) cannot be achieved with your other settings (num_workers=6 num_envs_per_worker=1 rollout_fragment_length=200)! Auto-adjusting `rollout_fragment_length` to 666.
(PPOTrainer pid=11661) 2022-04-20 00:11:08,187	INFO ppo.py:268 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
(PPOTrainer pid=11661) 2022-04-20 00:11:08,187	INFO trainer.py:864 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
2022-04-20 00:11:08,250	WARNING worker.py:1382 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff91d395621f7b794e332c916101000000 Worker ID: aa2568c476d5e84edfee377408f144b559b5d1545dcda9c0394744a5 Node ID: f9b6abeba12e96a259bc2ad31a3ee0d96ddafa942dadfd344d03dd64 Worker IP address: 192.168.0.90 Worker port: 38763 Worker PID: 11661

2022-04-20 00:11:08,258	ERROR trial_runner.py:876 -- Trial PPO_BipedalWalker-v3_9a5ba_00000: Error processing event.
NoneType: None

Result for PPO_BipedalWalker-v3_9a5ba_00000:
  trial_id: 9a5ba_00000
  

2022-04-20 00:11:08,267	ERROR ray_trial_executor.py:102 -- An exception occurred when trying to stop the Ray actor:Traceback (most recent call last):
  File "/home/dibya/miniconda3/envs/debsankha_bw_ts_1/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 93, in post_stop_cleanup
    ray.get(future, timeout=0)
  File "/home/dibya/miniconda3/envs/debsankha_bw_ts_1/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/dibya/miniconda3/envs/debsankha_bw_ts_1/lib/python3.8/site-packages/ray/worker.py", line 1811, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: PPOTrainer
	actor_id: 91d395621f7b794e332c916101000000
	pid: 11661
	namespace: 1689122e-dee8-4111-b4dd-99504210068a
	ip: 192.168.0.90
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR_EXIT

(PPOTrainer pid=11661) *** SIGSEGV received at time=1650406268 on cpu 11 ***
(PPOTrainer pid=11661) PC: @     0x7f046b02cc78  (unknown)  (unknown)
(PPOTrainer pid=11661)     @     0x7f046a66e980       3568  (unknown)
(PPOTrainer pid=11661)     @     0x7f046b03525d        192  (unknown)
(PPOTrainer pid=11661)     @     0x7f046a3d216f  (unknown)  _dl_catch_exception
(PPOTrainer pid=11661) [2022-04-20 00:11:08,220 E 11661 11689] logging.cc:325: *** SIGSEGV received at time=1650406268 on cpu 11 ***
(PPOTrainer pid=11661) [2022-04-20 00:11:08,220 E 11661 11689] logging.cc:325: PC: @     0x7f046b02cc78  (unknown)  (unknown)
(PPOTrainer pid=11661) [2022-04-20 00:11:08,220 E 11661 11689] logging.cc:325:     @     0x7f046a66e980       3568  (unknown)
(PPOTrainer pid=11661) [2022-04-20 00:11:08,220 E 11661 11689] logging.cc:325:     @     0x7f046b03525d        192  (unknown)
(PPOTrainer pid=11661) [2022-04-20 00:11:08,220 E 11661 11689] logging.cc:325:     @     0x7f046a3d216f  (unknown)  _dl_catch_exception
(PPOTrainer pid=11661) Fatal Python error: Segmentation fault
(PPOTrainer pid=11661) 

---------------------------------------------------------------------------
TuneError Traceback (most recent call last)
Input In [2], in <cell line: 3>() 1 from ray import tune ----> 3 tune.run("PPO", 4 config={"env": "BipedalWalker-v3", 5 "evaluation_interval": 100, 6 "evaluation_num_episodes": 100, 7 "num_workers": 6, 8 }, 9 local_dir="bipedal_walker", 10 checkpoint_freq=100 11 )
File ~/miniconda3/envs/debsankha_bw_ts_1/lib/python3.8/site-packages/ray/tune/tune.py:695, in run(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, reuse_actors, trial_executor, raise_on_failed_trial, callbacks, max_concurrent_trials, _experiment_checkpoint_dir, queue_trials, loggers, _remote) 693 if incomplete_trials: 694 if raise_on_failed_trial and not state[signal.SIGINT]: --> 695 raise TuneError("Trials did not complete", incomplete_trials) 696 else: 697 logger.error("Trials did not complete: %s", incomplete_trials)
TuneError: ('Trials did not complete', [PPO_BipedalWalker-v3_9a5ba_00000])

```

### Versions / Dependencies

# Ray 
1.12.0

# Python 
3.8.13

# OS 
elementary OS 5.1.7 Hera
Built on Ubuntu 18.04.6 LTS
Linux 5.4.0-107-generic

# Tensorflow
2.7.1
2.8

### Reproduction script

```python
import ray
ray.init()

from ray import tune

tune.run("PPO",
              config={"env": "BipedalWalker-v3",
                          "evaluation_interval": 100,
                          "evaluation_duration": 100,
                          },
              local_dir="bipedal_walker",
              checkpoint_freq=100
             )
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by gutfeeling** [comment]
I tried the same code with Ray version 1.12.0 and Python 3.9. 

With Python 3.9, the segmentation fault is gone but the agent doesn't learn anything. 

![image](https://user-images.githubusercontent.com/6130491/164115351-5e0bfaf9-1156-4aba-acb1-00d492688ad5.png)

Whereas, with Ray 1.11.0 and Ray 1.9.1, the agent learns quite well on the same environment.

![image](https://user-images.githubusercontent.com/6130491/164115517-db0276ab-780c-43ff-aa0f-97e6c41c2364.png)

A friend of mine also independently verified that the agent doesn't learn on Ray 1.12.0 in this environment. He tried 8M time steps.

We are both using the same `gym` version `0.21` for all our trials.

**Comment by xwjiang2010** [comment]
Actually I think this is RLlib issue. @sven1977 mind taking a look?

**Comment by gutfeeling** [comment]
The Segmentation Fault is happening on my computer, but my friend couldn't reproduce it on his computer. So this may be a  computer-specific issue and not very interesting.

However, the deterioration of the PPO performance for `BipedalWalker-v3` is reproducible on every computer we have tried so far.

**Comment by richardliaw** [comment]
Can you try upgrading to 1.13 or 2.0? We should open a separate issue about any performance degradations.
