### ISSUE TITLE
[RLlib] AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint' in ".../ray/rllib/env/wrappers/atari_wrappers.py"

### ISSUE THREAD

**Issue by piojanu** [ray-project/ray#24133]
### What happened + What you expected to happen

I've installed `ray[rllib]` and try to run [this](https://github.com/ray-project/ray/blob/master/rllib/tuned_examples/impala/pong-impala.yaml) IMPALA example config through: `rllib train -f pong-impala.yaml`. I'm expecting training to start, but instead I get this error:

```
Failure # 1 (occurred at 2022-04-23_08-15-55)
Traceback (most recent call last):
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 901, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/worker.py", line 1809, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): [36mray::ImpalaTrainer.train()[39m (pid=55686, ip=172.20.1.222, repr=ImpalaTrainer)
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/tune/trainable.py", line 349, in train
    result = self.step()
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1088, in step
    raise e
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1074, in step
    step_attempt_results = self.step_attempt()
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1155, in step_attempt
    step_results = self._exec_plan_or_training_iteration_fn()
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 2174, in _exec_plan_or_training_iteration_fn
    results = next(self.train_exec_impl)
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 779, in __next__
    return next(self.built_iterator)
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 807, in apply_foreach
    for item in it:
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 807, in apply_foreach
    for item in it:
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 869, in apply_filter
    for item in it:
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 869, in apply_filter
    for item in it:
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 807, in apply_foreach
    for item in it:
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 869, in apply_filter
    for item in it:
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 1108, in build_union
    item = next(it)
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 779, in __next__
    return next(self.built_iterator)
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 807, in apply_foreach
    for item in it:
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 807, in apply_foreach
    for item in it:
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 807, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 904, in apply_flatten
    for item in it:
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 807, in apply_foreach
    for item in it:
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 904, in apply_flatten
    for item in it:
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 807, in apply_foreach
    for item in it:
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 807, in apply_foreach
    for item in it:
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 807, in apply_foreach
    for item in it:
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 572, in base_iterator
    batch = ray.get(obj_ref)
ray.exceptions.RayTaskError(AttributeError): [36mray::RolloutWorker.par_iter_next_batch()[39m (pid=55821, ip=172.20.1.222, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fe83b20ed00>)
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 1192, in par_iter_next_batch
    batch.append(self.par_iter_next())
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/util/iter.py", line 1186, in par_iter_next
    return next(self.local_it)
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 404, in gen_rollouts
    yield self.sample()
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 815, in sample
    batches = [self.input_reader.next()]
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 116, in next
    batches = [self.get_data()]
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 289, in get_data
    item = next(self._env_runner)
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 668, in _env_runner
    unfiltered_obs, rewards, dones, infos, off_policy_actions = base_env.poll()
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/env/vector_env.py", line 291, in poll
    self.new_obs = self.vector_env.vector_reset()
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/env/vector_env.py", line 227, in vector_reset
    return [e.reset() for e in self.envs]
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/env/vector_env.py", line 227, in <listcomp>
    return [e.reset() for e in self.envs]
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/env/wrappers/atari_wrappers.py", line 243, in reset
    ob = self.env.reset()
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/gym/core.py", line 319, in reset
    observation = self.env.reset(**kwargs)
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/env/wrappers/atari_wrappers.py", line 130, in reset
    self.env.reset(**kwargs)
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/env/wrappers/atari_wrappers.py", line 172, in reset
    obs = self.env.reset(**kwargs)
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/env/wrappers/atari_wrappers.py", line 208, in reset
    return self.env.reset(**kwargs)
  File "/home/pjanuszewski/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/env/wrappers/atari_wrappers.py", line 98, in reset
    noops = self.unwrapped.np_random.randint(1, self.noop_max + 1)
AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'
```

_Note this is run with only one worker, but I get this error also with 16, 32, etc. workers._

### Versions / Dependencies

OS is Ubuntu 18.04.5 LTS (Bionic Beaver)
Python is 3.8.13

gym==0.21.0 (tried 0.20.0)
numpy==1.22.3 (tried 1.21.5 and 1.19.5 too)
ray==1.12.0 (tried 1.11.0 and 1.10.0 too)
tensorflow==2.8.0

### Reproduction script

```
conda create -n rllib python=3.8
conda activate rllib
pip install tensorflow
pip install gym[atari,accept-rom-license]==0.21.0
pip install -U ray[rllib]
# Possibly change number of workers in the config (it's 128 by default)
wget https://raw.githubusercontent.com/ray-project/ray/master/rllib/tuned_examples/impala/pong-impala.yaml
rllib train -f pong-impala.yaml
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by piojanu** [comment]
Note that I've read [these](https://github.com/ray-project/ray/issues/22622) [two](https://github.com/ray-project/ray/issues/22593) issues and still couldn't resolve this issue.

**Comment by trnhattan** [comment]
The document for `randint` function says it will be removed in the future, and use `rng.integers(low, [high, size, dtype])` instead. You can find this at `venv\Lib\site-packages\gym\utils\seeding.py`. 
Because of this, I changed ```noops = self.unwrapped.np_random.randint(1, self.noop_max + 1)``` to 
```python
noops = self.unwrapped.np_random.integers(1, self.noop_max + 1)
```
and it worked for me.

**Comment by xwjiang2010** [comment]
@avnishn

**Comment by vakker** [comment]
This should already be fixed on the latest master, see [here](https://github.com/ray-project/ray/blob/master/rllib/env/wrappers/atari_wrappers.py#L100). Try to install a daily release (see [here](https://docs.ray.io/en/latest/ray-overview/installation.html#daily-releases-nightlies)), that should fix it.
