### ISSUE TITLE
[Ray Client] Util Client logsclient.py

### ISSUE THREAD

**Issue by yogeveran** [ray-project/ray#24163]
### What happened + What you expected to happen

During a run with pytorch lightning 1.5.7
python/ray/util/client/logsclient.py threw an ascii exception.

Options that might solve (not tested yet)
https://gankrin.org/fix-unicodeencodeerror-ascii-codec-cant-encode-character/

Also, here they suggest to use byte str to stay safe:
https://pythonhosted.org/kitchen/unicode-frustrations.html

Error message:

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ray/util/client/logsclient.py", line 44, in _log_main
    self.stdstream(level=record.level, msg=record.msg)
  File "/usr/local/lib/python3.6/dist-packages/ray/util/client/logsclient.py", line 82, in stdstream
    print(msg, file=print_file, end="")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 71-80: ordinal not in range(128)

### Versions / Dependencies

pytorch lightning 1.5.7
ray 1.6.0

### Reproduction script

pytorch lightning training on a remote node in a k8s ray cluster

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ray/util/client/logsclient.py", line 44, in _log_main
    self.stdstream(level=record.level, msg=record.msg)
  File "/usr/local/lib/python3.6/dist-packages/ray/util/client/logsclient.py", line 82, in stdstream
    print(msg, file=print_file, end="")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 71-80: ordinal not in range(128)

Unfortunately I don't know of a small example that reproduces this issue.

**Comment by jjyao** [comment]
Assigning to @ckw017 for triage.

**Comment by ckw017** [comment]
Sorry for the late response! After digging around, it looks like `print` by default will use the [encoding configured in your local machine's LANG env var](https://stackoverflow.com/questions/54512406/unicodeencodeerror-ascii-codec-cant-encode-character-in-print-function). For example, this script will repro the issue depending on how LANG is set:

```python
import ray

@ray.remote
def print_chess():
    print("♟♟♟♟♟")

ray.init("ray://localhost:10001")
print_chess.remote()
import time
time.sleep(3) # Give time for remote print to propogate
```

This will error:
```
LANG=en_US.ASCII python script.py
```

This won't:
```
LANG=en_US.UTF-8 python script.py
```

If you want to avoid modifying your LANG env, then you can also do `PYTHONIOENCODING=UTF-8` to force python to use UTF-8 (I'm guessing something in your training is generating unicode output).
