### ISSUE TITLE
[rllib] replay buffer – lz4 decompress error

### ISSUE THREAD

**Issue by Scitator** [ray-project/ray#2418]
Hi, after updating to the last ray version (current master), I have a error during Apex DDPG training:

```
pus_per_worker': 0, 'num_cpus_per_worker': 1, 'optimizer_class': 'AsyncSamplesOptimizer', 'per_worker_exploration': True, 'worker_side_prioritization': True, 'max_weight_sync_delay': 250)
Remote function replay failed with:

Traceback (most recent call last):
  File "/home/scitator/Documents/git/ray/python/ray/worker.py", line 890, in _process_task
    *arguments)
  File "/home/scitator/Documents/git/ray/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/scitator/Documents/git/ray/python/ray/rllib/optimizers/async_samples_optimizer.py", line 75, in replay
    beta=self.prioritized_replay_beta)
  File "/home/scitator/Documents/git/ray/python/ray/rllib/optimizers/replay_buffer.py", line 212, in sample
    encoded_sample = self._encode_sample(idxes)
  File "/home/scitator/Documents/git/ray/python/ray/rllib/optimizers/replay_buffer.py", line 62, in _encode_sample
    obses_t.append(np.array(unpack(obs_t), copy=False))
  File "/home/scitator/Documents/git/ray/python/ray/rllib/utils/compression.py", line 40, in unpack
    data = lz4.frame.decompress(data)
RuntimeError: LZ4F_getFrameInfo failed with code: ERROR_frameHeader_incomplete

Remote function replay failed with:

Traceback (most recent call last):
  File "/home/scitator/Documents/git/ray/python/ray/worker.py", line 890, in _process_task
    *arguments)
  File "/home/scitator/Documents/git/ray/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/scitator/Documents/git/ray/python/ray/rllib/optimizers/async_samples_optimizer.py", line 75, in replay
    beta=self.prioritized_replay_beta)
  File "/home/scitator/Documents/git/ray/python/ray/rllib/optimizers/replay_buffer.py", line 212, in sample
    encoded_sample = self._encode_sample(idxes)
  File "/home/scitator/Documents/git/ray/python/ray/rllib/optimizers/replay_buffer.py", line 62, in _encode_sample
    obses_t.append(np.array(unpack(obs_t), copy=False))
  File "/home/scitator/Documents/git/ray/python/ray/rllib/utils/compression.py", line 40, in unpack
    data = lz4.frame.decompress(data)
RuntimeError: LZ4F_getFrameInfo failed with code: ERROR_frameType_unknown

Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.
```

After that training stops :( . What can cause such type of errors?
Thanks!

**Comment by ericl** [comment]
Try setting compress_observations: True in the DDPG config. I think it's trying to decompress uncompressed observations which of course doesn't work.

**Comment by Scitator** [comment]
@ericl with u suggestions all works pretty well. thanks!

PS. will close the issue tomorrow - need more time for test.

**Comment by alok** [comment]
Is there any change this could make it into a bugfix release (`0.5.1`)? This is a blocker for a planned presentation that shows off Ray's nice, pre-implemented priority experience replay.

**Comment by richardliaw** [comment]
For now, you can install from latest wheels (http://ray.readthedocs.io/en/latest/installation.html), and we should have a subsequent bugfix release soon.
