### ISSUE TITLE
[Datasets] Raise descriptive error when missing AWS credentials

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#24184]
### Description

If the user hasn't authenticated with AWS and tries reading from S3, raise an error with a descriptive message.

### Use case

I've uploaded some files to an S3 bucket. 

When I run the code snippet below without configuring my AWS credentials, I get an unhelpful error message.

```
❯ cat reproduction.py 
import ray.data

bucket = "s3://balajis-tiny-imagenet/train"
ds = ray.data.read_binary_files(bucket)
```

```
❯ python reproduction.py 
Traceback (most recent call last):
  File "reproduction.py", line 4, in <module>
    ds = ray.data.read_binary_files(bucket)
  File "/Users/balaji/Documents/image-folder/venv/lib/python3.8/site-packages/ray/data/read_api.py", line 622, in read_binary_files
    return read_datasource(
  File "/Users/balaji/Documents/image-folder/venv/lib/python3.8/site-packages/ray/data/read_api.py", line 231, in read_datasource
    read_tasks = ray.get(
  File "/Users/balaji/Documents/image-folder/venv/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/balaji/Documents/image-folder/venv/lib/python3.8/site-packages/ray/worker.py", line 1809, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(OSError): ray::_prepare_read() (pid=10829, ip=127.0.0.1)
  File "/Users/balaji/Documents/image-folder/venv/lib/python3.8/site-packages/ray/data/read_api.py", line 902, in _prepare_read
    return ds.prepare_read(parallelism, **kwargs)
  File "/Users/balaji/Documents/image-folder/venv/lib/python3.8/site-packages/ray/data/datasource/file_based_datasource.py", line 266, in prepare_read
    paths, file_sizes = meta_provider.expand_paths(paths, filesystem)
  File "/Users/balaji/Documents/image-folder/venv/lib/python3.8/site-packages/ray/data/datasource/file_based_datasource.py", line 223, in expand_paths
    file_info = filesystem.get_file_info(path)
  File "pyarrow/_fs.pyx", line 439, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 114, in pyarrow.lib.check_status
OSError: When getting information for key 'train' in bucket 'balajis-tiny-imagenet': AWS Error [code 15]: No response body.
```

**Comment by matthewdeng** [comment]
This has been fixed!

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matt/anaconda3/envs/ray20rc0/lib/python3.7/site-packages/ray/data/read_api.py", line 773, in read_binary_files
    partition_filter=partition_filter,
  File "/Users/matt/anaconda3/envs/ray20rc0/lib/python3.7/site-packages/ray/data/read_api.py", line 274, in read_datasource
    _wrap_and_register_arrow_serialization_workaround(read_args),
  File "/Users/matt/anaconda3/envs/ray20rc0/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/matt/anaconda3/envs/ray20rc0/lib/python3.7/site-packages/ray/_private/worker.py", line 2245, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(OSError): ray::_get_read_tasks() (pid=96278, ip=127.0.0.1)
  File "pyarrow/_fs.pyx", line 439, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 114, in pyarrow.lib.check_status
OSError: When getting information for key 'train' in bucket 'balajis-tiny-imagenet': AWS Error [code 15]: No response body.

During handling of the above exception, another exception occurred:

ray::_get_read_tasks() (pid=96278, ip=127.0.0.1)
  File "/Users/matt/anaconda3/envs/ray20rc0/lib/python3.7/site-packages/ray/data/read_api.py", line 1136, in _get_read_tasks
    reader = ds.create_reader(**kwargs)
  File "/Users/matt/anaconda3/envs/ray20rc0/lib/python3.7/site-packages/ray/data/datasource/file_based_datasource.py", line 212, in create_reader
    return _FileBasedDatasourceReader(self, **kwargs)
  File "/Users/matt/anaconda3/envs/ray20rc0/lib/python3.7/site-packages/ray/data/datasource/file_based_datasource.py", line 351, in __init__
    paths, self._filesystem
  File "/Users/matt/anaconda3/envs/ray20rc0/lib/python3.7/site-packages/ray/data/datasource/file_meta_provider.py", line 174, in expand_paths
    _handle_read_os_error(e, path)
  File "/Users/matt/anaconda3/envs/ray20rc0/lib/python3.7/site-packages/ray/data/datasource/file_meta_provider.py", line 347, in _handle_read_os_error
    f"Failing to read AWS S3 file(s): {paths}. "
OSError: Failing to read AWS S3 file(s): "balajis-tiny-imagenet/train". Please check that file exists and has properly configured access. You can also run AWS CLI command to get more detailed error message (e.g., aws s3 ls <file-name>). See https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/index.html and https://docs.ray.io/en/latest/data/creating-datasets.html#reading-from-remote-storage for more information.
```
