### ISSUE TITLE
StopIteration Error

### ISSUE THREAD

**Issue by gwisaacs2** [ray-project/ray#24182]
Hello,

I'm getting a StopIteration Error at exactly 40,000 steps. I try restarting the tune and it stops at exactly 40,000 steps every single time. It'll stop earlier or later depending on what my training batch sizes are like (included tune config at the bottom). I have no Stopper implemented and no scheduler. I tried adding an ASHA scheduler to override the default FIFO, but that didn't help either. Any help will be appreciated!

System Description:
1. RHEL 7.8
2. Python 3.6
3. Ray 1.6.0
4. TF 1.14

Error:
```
Got obs & rewards. Step finished!     # print statement showing that my environment finished the step function

2022-04-25 18:28:07,917 ERROR trial_runner.py:773 -- Trial PPO_MultiAgent-v0_dbbda_00000: Error processing event.
Traceback (most recent call last):
  File "venv/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 739, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "venv/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 746, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "venv/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "venv/lib/python3.6/site-packages/ray/worker.py", line 1621, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(StopIteration): ray::PPO.train_buffered() (pid=15729, ip=<my_ip>, repr=PPO)
  File "venv/lib/python3.6/site-packages/ray/tune/trainable.py", line 178, in train_buffered
    result = self.train()
  File "venv/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 651, in train
    raise e
  File "venv/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 637, in train
    result = Trainable.train(self)
  File "venv/lib/python3.6/site-packages/ray/tune/trainable.py", line 237, in train
    result = self.step()
  File "venv/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 193, in step
    res = next(self.train_exec_impl)
  File "venv/lib/python3.6/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
StopIteration
```

Agent Results
```
Result for PPO_MultiAgent-v0_dbbda_00000:                                                                                                                                                                                          [146/1805]  agent_timesteps_total: 40000
  custom_metrics: {}
  date: 2022-04-25_18-25-58
  done: false
  episode_len_mean: 900.0
  episode_media: {}
  episode_reward_max: -1625.1106328219214
  episode_reward_mean: -4172.167582496596
  episode_reward_min: -4704.648008439424
  episodes_this_iter: 9
  episodes_total: 44
  experiment_id: b46cff49896b452ba6b45f23ddeb947b
  experiment_tag: '0'
  hostname: <my_ip>
  info:
    learner:
      my_agent:
        learner_stats:
          cur_kl_coeff: 0.20000000298023224
          cur_lr: 4.999999873689376e-05
          entropy: 3.1700663566589355
          entropy_coeff: 0.0
          kl: 0.020199783146381378
          model: {}
          policy_loss: -0.0231464933604002
          total_loss: 149926.3125
          vf_explained_var: -5.387971668824321e-07
          vf_loss: 149926.328125
        train: null
    num_agent_steps_sampled: 40000
    num_agent_steps_trained: 40000
    num_steps_sampled: 40000
    num_steps_trained: 40000
  iterations_since_restore: 5
  node_ip: <my_ip>
  num_healthy_workers: 1
  off_policy_estimator: {}
  perf:
    cpu_util_percent: 4.009685863874346
    ram_util_percent: 4.830104712041884
  pid: 15729
  policy_reward_max:
    my_agent: -1625.1106328219214
  policy_reward_mean:
    my_agent: -4172.167582496596
  policy_reward_min:
    my_agent: -4704.648008439424
  sampler_perf:
    mean_action_processing_ms: 0.1100556500844407
    mean_env_render_ms: 0.0
    mean_env_wait_ms: 18.297870069539997
    mean_inference_ms: 5.388641374200106
    mean_raw_obs_processing_ms: 2.308496691465675
  time_since_restore: 1329.6671888828278
  time_this_iter_s: 268.4683835506439
  time_total_s: 1329.6671888828278
  timers:
    learn_throughput: 144.091
    learn_time_ms: 55520.605
    load_throughput: 13985.938
    load_time_ms: 572.003
    sample_throughput: 38.135
    sample_time_ms: 209781.27
    update_time_ms: 18.497
  timestamp: 1650911158
  timesteps_since_restore: 0
  timesteps_total: 40000
  training_iteration: 5
  trial_id: dbbda_00000

== Status ==
Memory usage on this node: 23.3/480.1 GiB
Using AsyncHyperBand: num_stopped=0
Bracket: Iter 18000000.000: None | Iter 6000000.000: None | Iter 2000000.000: None
Resources requested: 0/10 CPUs, 0/4 GPUs, 0.0/325.05 GiB heap, 0.0/143.3 GiB objects (0.0/1.0 accelerator_type:K80)
Result logdir: my_dir
Number of trials: 1/1 (1 ERROR)
+-------------------------------+----------+-------+--------+------------------+-------+----------+----------------------+----------------------+--------------------+
| Trial name                    | status   | loc   |   iter |   total time (s) |    ts |   reward |   episode_reward_max |   episode_reward_min |   episode_len_mean |
|-------------------------------+----------+-------+--------+------------------+-------+----------+----------------------+----------------------+--------------------|
| PPO_MultiAgent-v0_dbbda_00000 | ERROR    |       |      5 |          1329.67 | 40000 | -4172.17 |             -1625.11 |             -4704.65 |                900 |
+-------------------------------+----------+-------+--------+------------------+-------+----------+----------------------+----------------------+--------------------+
Number of errored trials: 1
+-------------------------------+--------------+------------------------------------------------------------------------------------------------------------+
| Trial name                    |   # failures | error file                                                                                                 |
|-------------------------------+--------------+------------------------------------------------------------------------------------------------------------|
| PPO_MultiAgent-v0_dbbda_00000 |            1 | my_error.txt |
+-------------------------------+--------------+------------------------------------------------------------------------------------------------------------+
```

Tune Config:
```
PPO
num_workers = 1
log_level = DEBUG
framework = tf
rollout_fragment_length = 512
sgd_minibatch_size = 256
train_batch_size = 8_000
```

**Comment by gwisaacs2** [comment]
RESOLVED!!! My environment contains an Iterator object. We save it as `self._run_iterator` but we have a typo and accidentally reset it with `self.runiterator`... major typo. 

This definitely should be marked as a bug though, because the error logs make it seem like the error originates in Ray. Ray is somehow picking up the StopIteration error that's thrown in my environment

**Comment by gwisaacs2** [comment]
Created bug issue for my discovery #24243
