### ISSUE TITLE
[Tune] Tune Catches StopIteration Error from Gym Environment

### ISSUE THREAD

**Issue by gwisaacs2** [ray-project/ray#24243]
### What happened + What you expected to happen

My custom Gym Environment has an Iterator object. If the iterator throws a StopIteration Error, Ray picks it up and assumes a stop iteration was called in the Ray Tune process. As you can see in the traceback below, there is no indication that the StopIteration error is coming from my environment. Rather, Ray catches it and assumes the StopIteration error is happening inside of Ray.

The error from Tune was the following
```
2022-04-25 18:28:07,917 ERROR trial_runner.py:773 -- Trial PPO_MultiAgent-v0_dbbda_00000: Error processing event.
Traceback (most recent call last):
  File "venv/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 739, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "venv/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 746, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "venv/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "venv/lib/python3.6/site-packages/ray/worker.py", line 1621, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(StopIteration): ray::PPO.train_buffered() (pid=15729, ip=<my_ip>, repr=PPO)
  File "venv/lib/python3.6/site-packages/ray/tune/trainable.py", line 178, in train_buffered
    result = self.train()
  File "venv/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 651, in train
    raise e
  File "venv/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 637, in train
    result = Trainable.train(self)
  File "venv/lib/python3.6/site-packages/ray/tune/trainable.py", line 237, in train
    result = self.step()
  File "venv/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 193, in step
    res = next(self.train_exec_impl)
  File "venv/lib/python3.6/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
StopIteration
```

### Versions / Dependencies

RHEL 7.8
Ray 1.6
Python 3.6

### Reproduction script

Literally just throw in a `raise StopIteration` in the first line of your step function. Works for both tf and torch.

### Issue Severity

Low: It annoys or frustrates me.

**Comment by gwisaacs2** [comment]
Spawned from issue #24182

**Comment by xwjiang2010** [comment]
@gwisaacs2 
I tried to repro the issue you described with the following setup (ray 1.6 + python 3.6)

```
from ray import tune

from ray.rllib.agents.ppo import PPOTrainer

class MyPPOTrainer(PPOTrainer):
	def step(self):
		raise StopIteration

tune.run(MyPPOTrainer, config={"env": "CartPole-v0",})
```

Output:
```
2022-04-27 15:54:30,404	ERROR trial_runner.py:773 -- Trial PPO_CartPole-v0_f9003_00000: Error processing event.
Traceback (most recent call last):
  File "/Users/xwjiang/anaconda3/envs/ray6/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 739, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/Users/xwjiang/anaconda3/envs/ray6/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 746, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/Users/xwjiang/anaconda3/envs/ray6/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/Users/xwjiang/anaconda3/envs/ray6/lib/python3.6/site-packages/ray/worker.py", line 1621, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(StopIteration): ray::MyPPOTrainer.train_buffered() (pid=81446, ip=10.0.0.142, repr=PPO)
  File "/Users/xwjiang/anaconda3/envs/ray6/lib/python3.6/site-packages/ray/tune/trainable.py", line 178, in train_buffered
    result = self.train()
  File "/Users/xwjiang/anaconda3/envs/ray6/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 651, in train
    raise e
  File "/Users/xwjiang/anaconda3/envs/ray6/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 637, in train
    result = Trainable.train(self)
  File "/Users/xwjiang/anaconda3/envs/ray6/lib/python3.6/site-packages/ray/tune/trainable.py", line 237, in train
    result = self.step()
  File "tryout_rllib.py", line 7, in step
    raise StopIteration
StopIteration
```

The output seems pretty clear to me where the StopIteration thing is raised.

Could you let me know where the gap is, and maybe we could improve ray's documentation accordingly. Thanks!

**Comment by gwisaacs2** [comment]
@xwjiang2010 Thanks for the speedy response. One difference is that I was using a multi agent custom Environment (inheriting from `ray.rllib.env.multi_agent_env.MultiAgentEnv`). Let me see if I can put together a quick example

**Comment by gwisaacs2** [comment]
Hey @xwjiang2010 I have a presentation tomorrow. I'll try to get you reproduceable code by the end of the day... I created a very generic multi agent Gym Environment that just returns `np.zeros()` for the action space and obs space, but I was having issues registering the gym environment I think. I'll give you an update tomorrow
