### ISSUE TITLE
[Dashboard] Too many logs causes API requests (e.g. `job submit`, `job stop`) to fail

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#24272]
### What happened + What you expected to happen

Start Ray and run the following script on the head node to produce a lot of logs:

```python
import ray

ray.init(address="auto")

@ray.remote
def f():
    print("Print from task")

while True:
    print("Print from driver")
    ray.get(f.remote())
```

This causes Dashboard API requests to fail.  For example, submitting a job with Ray Job Submission:

```
❯ ray job submit -- sleep 30s
[...]
Traceback (most recent call last):
  File "/Users/archit/anaconda3/envs/test39/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/Users/archit/anaconda3/envs/test39/lib/python3.9/site-packages/ray/scripts/scripts.py", line 2269, in main
    return cli()
  File "/Users/archit/anaconda3/envs/test39/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/archit/anaconda3/envs/test39/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/archit/anaconda3/envs/test39/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/archit/anaconda3/envs/test39/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/archit/anaconda3/envs/test39/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/archit/anaconda3/envs/test39/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/archit/anaconda3/envs/test39/lib/python3.9/site-packages/ray/autoscaler/_private/cli_logger.py", line 808, in wrapper
    return f(*args, **kwargs)
  File "/Users/archit/anaconda3/envs/test39/lib/python3.9/site-packages/ray/dashboard/modules/job/cli.py", line 152, in submit
    job_id = client.submit_job(
  File "/Users/archit/anaconda3/envs/test39/lib/python3.9/site-packages/ray/dashboard/modules/job/sdk.py", line 142, in submit_job
    self._raise_error(r)
  File "/Users/archit/anaconda3/envs/test39/lib/python3.9/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 217, in _raise_error
    raise RuntimeError(
RuntimeError: Request failed with status code 504: upstream request timeout.
```

### Versions / Dependencies

Verified on Ray 1.10 Linux and Ray 1.12 Linux, Python 3.7 and 3.9

### Reproduction script

Given above.  Here is the py-spy trace indicating the problematic part of the code:

This overloads the dashboard, giving a py-spy trace like the following: 

<img width="903" alt="Screen Shot 2022-04-27 at 12 56 08 PM" src="https://user-images.githubusercontent.com/5459654/165620600-ccc08646-b888-49d9-854e-e866912aa6f3.png">

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rkooo567** [comment]
@simon-mo 

> According to Simon, this is a known issue and is easily fixed

Can you tell me more about what's the solution you are thinking?

Since we are not able to support `ray logs` API, I am thinking to just fetch logs on demand instead of always caching them in memory which is a bad design

**Comment by simon-mo** [comment]
Currently it is "fixed" by a custom wheel that disabled the log subscriber loop. This is an optional part that can be disabled by env var. 

You are correct that the proper fix should be fix log on demand.

**Comment by rkooo567** [comment]
I think this is unnecessary to be fixed for the old dashboard since we are migrating to the new dashboard. New dashboard wouldn't require this feature (and it is query logs on demand by default), so we can simply remove all code. 

cc @alanwguo for awareness (this is a part of stability work).
