### ISSUE TITLE
[release] "ml_user_tune_rllib_connect_test" failing due to "module anyscale does not exist"

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#24326]
### What happened + What you expected to happen

https://buildkite.com/ray-project/release-tests-branch/builds/443#36e155d1-e488-489f-8f5c-aefabd7c46e6

module "anyscale" does not exist...

### Versions / Dependencies

Nightly

### Reproduction script

NA

**Comment by xwjiang2010** [comment]
```
[INFO 2022-04-28 16:14:06,998] client_runner.py: 123  Running command using Ray client on cluster ml_user_tune_rllib_connect_test_1651186388: python tune_rllib/run_connect_tests.py
--
  | Traceback (most recent call last):
  | File "tune_rllib/run_connect_tests.py", line 17, in <module>
  | ray.init(address=addr, job_name=job_name)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
  | return func(*args, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 870, in init
  | builder = ray.client(address, _deprecation_warn_enabled=False)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/client_builder.py", line 367, in client
  | builder = _get_builder_from_address(address)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/client_builder.py", line 334, in _get_builder_from_address
  | ) from None
  | RuntimeError: Module: anyscale does not exist.
  | This module was parsed from Address: anyscale://e2e-tests/ml_user_tune_rllib_connect_test_1651186388
  | [ERROR 2022-04-28 16:14:11,636] glue.py: 264  Command returned non-success status: 1
  | Traceback (most recent call last):
  | File "/tmp/release-Coy79mGWq1/release/ray_release/glue.py", line 235, in run_release_test
  | command, env=command_env, timeout=command_timeout
  | File "/tmp/release-Coy79mGWq1/release/ray_release/command_runner/client_runner.py", line 189, in run_command
  | raise CommandError(f"Command returned non-success status: {return_code}")
  | ray_release.exception.CommandError: Command returned non-success status: 1
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/tmp/release-Coy79mGWq1/release/ray_release/glue.py", line 238, in run_release_test
  | raise TestCommandError(e)
  | ray_release.exception.TestCommandError: Command returned non-success status: 1
  | [INFO 2022-04-28 16:14:11,767] log.py: 11  Test ml_user_tune_rllib_connect_test finished after 0.00 seconds. Last logs:
  |  
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
  |  
  | return func(*args, **kwargs)
  |  
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 870, in init
  |  
  | builder = ray.client(address, _deprecation_warn_enabled=False)
  |  
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/client_builder.py", line 367, in client
  |  
  | builder = _get_builder_from_address(address)
  |  
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/client_builder.py", line 334, in _get_builder_from_address
  |  
  | ) from None
  |  
  | RuntimeError: Module: anyscale does not exist.
  |  
  | This module was parsed from Address: anyscale://e2e-tests/ml_user_tune_rllib_connect_test_1651186388


```

@ckw017 wondering if you have any idea here? This is a release test running ray client mode. Is this a real error message or just masking something else?

**Comment by ckw017** [comment]
Likely that something is getting masked there (error gets thrown if anything fails while trying to import anyscale). Is there a way to run this test off laptop?

**Comment by ckw017** [comment]
^basically I just want to find out what packages are being installed in buildkite, I'm guessing either anyscale isn't being installed for some reason, or somethings overwriting anyscale's dependencies that's causing it to fail on import

**Comment by xwjiang2010** [comment]
Thanks @ckw017. That makes sense!

Consolidate @krfricke's investigation here as well (along the same line):
https://buildkite.com/ray-project/release-tests-pr/builds/1841#dfe2029d-fdec-4a78-aa11-0234f21d5a10 - prints out the exact error during "import anyscale"

which is 
```
cannot import name 'ParamSpec' from 'typing_extensions' (/home/ray/anaconda3/lib/python3.7/site-packages/typing_extensions.py)
```

The [fix](https://github.com/ray-project/ray/pull/24346/files) is now tried out at [here](https://buildkite.com/ray-project/release-tests-pr/builds/1852#dd2bbaec-22d0-4347-81a6-a2fd38f56189)
