### ISSUE TITLE
Core: GCS has started but no raylets have registered yet

### ISSUE THREAD

**Issue by tekumara** [ray-project/ray#24366]
### What happened + What you expected to happen

```
$ python -c 'import ray; ray.init(f"ray://127.0.0.1:10001")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tekumara/code/ray-example/.venv/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/tekumara/code/ray-example/.venv/lib/python3.7/site-packages/ray/worker.py", line 882, in init
    return builder.connect()
  File "/Users/tekumara/code/ray-example/.venv/lib/python3.7/site-packages/ray/client_builder.py", line 164, in connect
    ray_init_kwargs=self._remote_init_kwargs,
  File "/Users/tekumara/code/ray-example/.venv/lib/python3.7/site-packages/ray/util/client_connect.py", line 45, in connect
    ray_init_kwargs=ray_init_kwargs,
  File "/Users/tekumara/code/ray-example/.venv/lib/python3.7/site-packages/ray/util/client/__init__.py", line 243, in connect
    conn = self.get_context().connect(*args, **kw_args)
  File "/Users/tekumara/code/ray-example/.venv/lib/python3.7/site-packages/ray/util/client/__init__.py", line 94, in connect
    self.client_worker._server_init(job_config, ray_init_kwargs)
  File "/Users/tekumara/code/ray-example/.venv/lib/python3.7/site-packages/ray/util/client/worker.py", line 804, in _server_init
    f"Initialization failure from server:\n{response.msg}"
ConnectionAbortedError: Initialization failure from server:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/server/proxier.py", line 651, in Datapath
    client_id, job_config
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/server/proxier.py", line 285, in start_specific_server
    output, error = self.node.get_log_file_handles(
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/server/proxier.py", line 192, in node
    connect_only=True,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 229, in __init__
    redis_password=self.redis_password,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 402, in get_node_to_connect_for_driver
    return global_state.get_node_to_connect_for_driver(node_ip_address)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/state.py", line 745, in get_node_to_connect_for_driver
    node_ip_address
  File "python/ray/includes/global_state_accessor.pxi", line 162, in ray._raylet.GlobalStateAccessor.get_node_to_connect_for_driver
RuntimeError: b'GCS has started but no raylets have registered yet.'
```

### Versions / Dependencies

ray 1.12.0 python 3.7.7
deployed on Kubernetes using the helm chart

### Reproduction script

```
helm -n ray upgrade --install example-cluster deploy/charts/ray --create-namespace --wait
# forward server to http://localhost:10001
kubectl -n ray port-forward service/example-cluster-ray-head 10001:10001 &
python -c 'import ray; ray.init(f"ray://127.0.0.1:10001")'
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by tekumara** [comment]
Looks like my cluster has no workers, just a head node:
```
$ kubectl get pods -n ray                   
NAME                                  READY   STATUS    RESTARTS   AGE
example-cluster-ray-head-type-zrsr2   1/1     Running   0          72m
```

**Comment by tekumara** [comment]
I've resolved this by restarting the cluster and applying the change in https://github.com/ray-project/ray/pull/23414
