### ISSUE TITLE
[Serve] Code snippet on ray.io/ray-serve fails

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#24422]
### What happened + What you expected to happen

I'm running the code snippet from https://www.ray.io/ray-serve (copied below)

```python
import pickle
import requests

from sklearn.datasets import load_iris
from sklearn.ensemble import GradientBoostingClassifier

from ray import serve

serve.start()

# Train model.
iris_dataset = load_iris()
model = GradientBoostingClassifier()
model.fit(iris_dataset["data"], iris_dataset["target"])

@serve.deployment(route_prefix="/iris")
class BoostingModel:
    def __init__(self, model):
        self.model = model
        self.label_list = iris_dataset["target_names"].tolist()

    async def __call__(self, request):
        payload = await request.json()["vector"]
        print(f"Received flask request with data {payload}")

        prediction = self.model.predict([payload])[0]
        human_name = self.label_list[prediction]
        return {"result": human_name}


# Deploy model.
BoostingModel.deploy(model)

# Query it!
sample_request_input = {"vector": [1.2, 1.0, 1.1, 0.9]}
response = requests.get("http://localhost:8000/iris", json=sample_request_input)
print(response.text)
# Result:
# {
#  "result": "versicolor"
# }
```

It fails with

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-e57c1b75ca46> in <module>
     30 
     31 # Deploy model.
---> 32 BoostingModel.deploy(model)
     33 
     34 # Query it!

~/opt/anaconda3/lib/python3.7/site-packages/ray/serve/api.py in deploy(self, _blocking, *init_args, **init_kwargs)
   1276             route_prefix=self.route_prefix,
   1277             url=self.url,
-> 1278             _blocking=_blocking,
   1279         )
   1280 

~/opt/anaconda3/lib/python3.7/site-packages/ray/serve/api.py in check(self, *args, **kwargs)
    180         if self._shutdown:
    181             raise RayServeException("Client has already been shut down.")
--> 182         return f(self, *args, **kwargs)
    183 
    184     return check

~/opt/anaconda3/lib/python3.7/site-packages/ray/serve/api.py in deploy(self, name, deployment_def, init_args, init_kwargs, ray_actor_options, config, version, prev_version, route_prefix, url, _blocking)
    384 
    385         if _blocking:
--> 386             self._wait_for_deployment_healthy(name)
    387             self.log_deployment_ready(name, version, url, tag)
    388 

~/opt/anaconda3/lib/python3.7/site-packages/ray/serve/api.py in _wait_for_deployment_healthy(self, name, timeout_s)
    318                 break
    319             elif status.status == DeploymentStatus.UNHEALTHY:
--> 320                 raise RuntimeError(f"Deployment {name} is UNHEALTHY: {status.message}")
    321             else:
    322                 # Guard against new unhandled statuses being added.

RuntimeError: Deployment BoostingModel is UNHEALTHY: Failed to update deployment:
No module named 'aiorwlock'.
```

Running `pip install aiorwlock` solves the issue.

The next issue I run into is that `print(response.text)` prints out

```
Task Error. Traceback: ray::RayServeWrappedReplica.handle_request() (pid=4798, ip=127.0.0.1)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/serve/utils.py", line 243, in wrap_to_ray_error
    raise exception
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/serve/replica.py", line 396, in invoke_single
    result = await method_to_call(*args, **kwargs)
  File "<ipython-input-1-e57c1b75ca46>", line 23, in __call__
TypeError: 'coroutine' object is not subscriptable.
```

### Versions / Dependencies

Ray 1.12.0
MacOS

### Reproduction script

Included above

### Issue Severity

Low: It annoys or frustrates me.

**Comment by edoakes** [comment]
@robertnishihara did you do `pip install ray[serve]` prior to the first error?

**Comment by edoakes** [comment]
Looks like the second issue is in the `payload = await request.json()["vector"]` call. Updated version that works here (also removed unused `pickle` import):

```python
import requests

from sklearn.datasets import load_iris
from sklearn.ensemble import GradientBoostingClassifier

from ray import serve

serve.start()

# Train model.
iris_dataset = load_iris()
model = GradientBoostingClassifier()
model.fit(iris_dataset["data"], iris_dataset["target"])


@serve.deployment(route_prefix="/iris")
class BoostingModel:
    def __init__(self, model):
        self.model = model
        self.label_list = iris_dataset["target_names"].tolist()

    async def __call__(self, request):
        payload = await request.json()
        print(f"Received flask request with data {payload}")

        prediction = self.model.predict([payload["vector"]])[0]
        human_name = self.label_list[prediction]
        return {"result": human_name}


# Deploy model.
BoostingModel.deploy(model)

# Query it!
sample_request_input = {"vector": [1.2, 1.0, 1.1, 0.9]}
response = requests.get("http://localhost:8000/iris", json=sample_request_input)
print(response.text)
```

@robertnishihara do you know where this code lives / how we can update it?

**Comment by robertnishihara** [comment]
> @robertnishihara did you do `pip install ray[serve]` prior to the first error?

I didn't do that. I already had Ray installed so it didn't occur to me.

**Comment by edoakes** [comment]
Snippet updated and confirmed working 👍
