### ISSUE TITLE
[Autoscaler] Autoscaler throws error when trying to run an RLlib workload with 120 rollout workers and 0.3 GPUs on each.

### ISSUE THREAD

**Issue by sven1977** [ray-project/ray#24428]
### What happened + What you expected to happen

When trying to run an RLlib IMPALA workload (repro see below) on the Anyscale Product with autoscaling, an error is logged in the Cluster's autoscaler logs:

ERROR message:
```
======== Autoscaler status: 2022-05-03 03:15:05.066658 ========
Node status
---------------------------------------------------------------
Healthy:
 8 worker-node-type-0
 1 head-node-type
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/576.0 CPU
 0.0/36.0 GPU
 0.0/9.0 accelerator_type:M60
 0.00/3059.243 GiB memory
 0.00/1295.270 GiB object_store_memory

Demands:
 {'GPU': 4.0, 'CPU': 45.0} * 1, {'CPU': 1.0, 'GPU': 0.3} * 120 (PACK): 1+ pending placement groups
2022-05-03 03:15:12,221	INFO autoscaler.py:1219 -- StandardAutoscaler: Queue 2 new nodes for launch
2022-05-03 03:15:12,223	INFO node_launcher.py:123 -- NodeLauncher1: Got 2 nodes to launch.
2022-05-03 03:15:12,223	INFO node_launcher.py:123 -- NodeLauncher1: Launching 2 nodes, type worker-node-type-0.
2022-05-03 03:15:12,268	INFO node_provider.py:494 -- Configuration bypasses Rapid Start; launching node normally.
2022-05-03 03:15:13,074	INFO monitor.py:369 -- :event_summary:Failed to launch 2 nodes of type worker-node-type-0.
2022-05-03 03:15:13,074	INFO monitor.py:369 -- :event_summary:Adding 2 nodes of type worker-node-type-0.
2022-05-03 03:15:15,519	ERROR node_launcher.py:116 -- Launch failed
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/api.py", line 136, in call_api
    _host,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/client/openapi_client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/client/openapi_client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/client/openapi_client/api_client.py", line 397, in request
    body=body)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/client/openapi_client/rest.py", line 276, in POST
    body=body)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/client/openapi_client/rest.py", line 229, in request
    raise ApiException(http_resp=r)
openapi_client.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 03 May 2022 10:15:15 GMT', 'Content-Type': 'application/json', 'Content-Length': '1143', 'Connection': 'keep-alive', 'Set-Cookie': 'AWSALB=HekEyIvsMf/UutqdE6xUfgQULxlPCwTNlTsErkjLLP3zlee9MduqXC0J85iBWiCDrFVmuUg41cLZTWdc/P5TS7YAGXpSmCENjTOu4Y2YSz8pzU8ND8xVjOYPagvO; Expires=Tue, 10 May 2022 10:15:12 GMT; Path=/, AWSALBCORS=HekEyIvsMf/UutqdE6xUfgQULxlPCwTNlTsErkjLLP3zlee9MduqXC0J85iBWiCDrFVmuUg41cLZTWdc/P5TS7YAGXpSmCENjTOu4Y2YSz8pzU8ND8xVjOYPagvO; Expires=Tue, 10 May 2022 10:15:12 GMT; Path=/; SameSite=None; Secure', 'Server': 'nginx/1.18.0 (Ubuntu)', 'x-trace-id': '0cd9f17edb1f9b296ac3c5e4984cbd'})
HTTP response body: {"error":{"detail":"gAWVPQMAAAAAAACME2JvdG9jb3JlLmV4Y2VwdGlvbnOUjAtDbGllbnRFcnJvcpSTlH2UKIwFRXJyb3KUfZQojARDb2RllIwRVmNwdUxpbWl0RXhjZWVkZWSUjAdNZXNzYWdllIz4WW91IGhhdmUgcmVxdWVzdGVkIG1vcmUgdkNQVSBjYXBhY2l0eSB0aGFuIHlvdXIgY3VycmVudCB2Q1BVIGxpbWl0IG9mIDE2MDAgYWxsb3dzIGZvciB0aGUgaW5zdGFuY2UgYnVja2V0IHRoYXQgdGhlIHNwZWNpZmllZCBpbnN0YW5jZSB0eXBlIGJlbG9uZ3MgdG8uIFBsZWFzZSB2aXNpdCBodHRwOi8vYXdzLmFtYXpvbi5jb20vY29udGFjdC11cy9lYzItcmVxdWVzdCB0byByZXF1ZXN0IGFuIGFkanVzdG1lbnQgdG8gdGhpcyBsaW1pdC6UdYwQUmVzcG9uc2VNZXRhZGF0YZR9lCiMCVJlcXVlc3RJZJSMJDQ2ODI5ZWIzLTNhZmMtNGI1Yi1iZWI0LWVkN2E0OTU2NmEyZpSMDkhUVFBTdGF0dXNDb2RllE2QAYwLSFRUUEhlYWRlcnOUfZQojBB4LWFtem4tcmVxdWVzdGlklIwkNDY4MjllYjMtM2FmYy00YjViLWJlYjQtZWQ3YTQ5NTY2YTJmlIwNY2FjaGUtY29udHJvbJSMEm5vLWNhY2hlLCBuby1zdG9yZZSMGXN0cmljdC10cmFuc3BvcnQtc2VjdXJpdHmUjCNtYXgtYWdlPTMxNTM2MDAwOyBpbmNsdWRlU3ViRG9tYWluc5SMBHZhcnmUjA9hY2NlcHQtZW5jb2RpbmeUjAxjb250ZW50LXR5cGWUjBZ0ZXh0L3htbDtjaGFyc2V0PVVURi04lIwRdHJhbnNmZXItZW5jb2RpbmeUjAdjaHVua2VklIwEZGF0ZZSMHVR1ZSwgMDMgTWF5IDIwMjIgMTA6MTU6MTUgR01UlIwKY29ubmVjdGlvbpSMBWNsb3NllIwGc2VydmVylIwJQW1hem9uRUMylHWMDVJldHJ5QXR0ZW1wdHOUSwB1dYwMUnVuSW5zdGFuY2VzlIaUUpQu"}}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/node_launcher.py", line 98, in run
    self._launch_node(config, count, node_type)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/node_launcher.py", line 82, in _launch_node
    node_config, node_tags, count, resources
  File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/autoscaler/node_provider.py", line 236, in create_node_with_resources
    self.create_node(node_config, tags, count)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/autoscaler/node_provider.py", line 495, in create_node
    super().create_node(node_config, tags, count)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/autoscaler/node_provider.py", line 255, in create_node
    self.api_client.create_nodes_api_v2_instances_post(create_node_request)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/autoscaler/node_provider.py", line 78, in retrier
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/client/openapi_client/api/default_api.py", line 2380, in create_nodes_api_v2_instances_post
    return self.create_nodes_api_v2_instances_post_with_http_info(create_nodes_options, **kwargs)  # noqa: E501
  File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/client/openapi_client/api/default_api.py", line 2472, in create_nodes_api_v2_instances_post_with_http_info
    collection_formats=collection_formats)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/api.py", line 140, in call_api
    e, method, resource_path, self.raise_structured_exception
  File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/api.py", line 80, in format_api_exception
    f"API Exception ({e.status}) from {method} {resource_path} \n"
click.exceptions.ClickException: API Exception (500) from POST /api/v2/instances/ 
Reason: Internal Server Error
HTTP response body: {"error":{"detail":"gAWVPQMAAAAAAACME2JvdG9jb3JlLmV4Y2VwdGlvbnOUjAtDbGllbnRFcnJvcpSTlH2UKIwFRXJyb3KUfZQojARDb2RllIwRVmNwdUxpbWl0RXhjZWVkZWSUjAdNZXNzYWdllIz4WW91IGhhdmUgcmVxdWVzdGVkIG1vcmUgdkNQVSBjYXBhY2l0eSB0aGFuIHlvdXIgY3VycmVudCB2Q1BVIGxpbWl0IG9mIDE2MDAgYWxsb3dzIGZvciB0aGUgaW5zdGFuY2UgYnVja2V0IHRoYXQgdGhlIHNwZWNpZmllZCBpbnN0YW5jZSB0eXBlIGJlbG9uZ3MgdG8uIFBsZWFzZSB2aXNpdCBodHRwOi8vYXdzLmFtYXpvbi5jb20vY29udGFjdC11cy9lYzItcmVxdWVzdCB0byByZXF1ZXN0IGFuIGFkanVzdG1lbnQgdG8gdGhpcyBsaW1pdC6UdYwQUmVzcG9uc2VNZXRhZGF0YZR9lCiMCVJlcXVlc3RJZJSMJDQ2ODI5ZWIzLTNhZmMtNGI1Yi1iZWI0LWVkN2E0OTU2NmEyZpSMDkhUVFBTdGF0dXNDb2RllE2QAYwLSFRUUEhlYWRlcnOUfZQojBB4LWFtem4tcmVxdWVzdGlklIwkNDY4MjllYjMtM2FmYy00YjViLWJlYjQtZWQ3YTQ5NTY2YTJmlIwNY2FjaGUtY29udHJvbJSMEm5vLWNhY2hlLCBuby1zdG9yZZSMGXN0cmljdC10cmFuc3BvcnQtc2VjdXJpdHmUjCNtYXgtYWdlPTMxNTM2MDAwOyBpbmNsdWRlU3ViRG9tYWluc5SMBHZhcnmUjA9hY2NlcHQtZW5jb2RpbmeUjAxjb250ZW50LXR5cGWUjBZ0ZXh0L3htbDtjaGFyc2V0PVVURi04lIwRdHJhbnNmZXItZW5jb2RpbmeUjAdjaHVua2VklIwEZGF0ZZSMHVR1ZSwgMDMgTWF5IDIwMjIgMTA6MTU6MTUgR01UlIwKY29ubmVjdGlvbpSMBWNsb3NllIwGc2VydmVylIwJQW1hem9uRUMylHWMDVJldHJ5QXR0ZW1wdHOUSwB1dYwMUnVuSW5zdGFuY2VzlIaUUpQu"}}
Trace ID: ['x-trace-id', '0cd9f17edb1f9b296ac3c5e4984cbd']
2022-05-03 03:15:19,705	INFO autoscaler.py:330 -- 

```

### Versions / Dependencies

Ray 1.12

### Reproduction script

Create a cluster on the Anyscale product using the Ray 1.12 Py3.8 ML image and the following compute config:

```
Cloud name
anyscale_default_cloud
Region us-west-2

Head node type
g3.16xlarge

Worker node 0
g3.16xlarge (max: 10)
```

Create a RLlib config file and call it test.yaml:
```
pong-impala:
    env: PongNoFrameskip-v4
    run: IMPALA
    config:
        num_workers: 120
        num_aggregation_workers: 5
        num_cpus_for_driver: 40
        num_gpus: 4
        num_gpus_per_worker: 0.3
        num_cpus_per_worker: 1
        num_envs_per_worker: 1
        max_sample_requests_in_flight_per_worker: 4
        num_multi_gpu_tower_stacks: 8
        remote_worker_envs: False
        rollout_fragment_length: 128
        train_batch_size: 512
        num_sgd_iter : 1
        lr: 0.0001
        vf_loss_coeff: 0.5
        create_env_on_driver: False
        learner_queue_size: 128
        learner_queue_timeout: 600
        no_done_at_end: False
        soft_horizon: False
```

Then, in a console, run the following command:
```
$ rllib train -f [the above test.yaml file]
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by hora-anyscale** [comment]
Per Triage Sync: @sven1977 is this still an issue, are you able to repro?
