### ISSUE TITLE
Ray fails to start due to "Ray agent failed"

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#24485]
### What happened + What you expected to happen

I cannot start Ray because the dashboard_agent.py fails to start.

Dashboard agent logs:
```
2022-05-04 17:21:42,075 INFO agent.py:83 -- Parent pid is 441695
2022-05-04 17:21:42,076 INFO agent.py:109 -- Dashboard agent grpc address: 0.0.0.0:63741
2022-05-04 17:21:42,079 INFO utils.py:99 -- Get all modules by type: DashboardAgentModule
2022-05-04 17:21:43,303 INFO utils.py:132 -- Available modules: [<class 'ray.dashboard.modules.event.event_agent.EventAgent'>, <class 'ray.dashboard.modules.job.job_agent.JobAgent'>, <class 'ray.dashboard.modules.log.log_agent.LogAgent'>, <class 'ray.dashboard.modules.reporter.reporter_agent.ReporterAgent'>, <class 'ray.dashboard.modules.runtime_env.runtime_env_agent.RuntimeEnvAgent'>]
2022-05-04 17:21:43,303 INFO agent.py:130 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.event.event_agent.EventAgent'>
2022-05-04 17:21:43,303 INFO event_agent.py:28 -- Event agent cache buffer size: 10240
2022-05-04 17:21:43,304 INFO agent.py:130 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.job.job_agent.JobAgent'>
2022-05-04 17:21:43,304 ERROR agent.py:385 -- Agent is working abnormally. It will exit immediately.
Traceback (most recent call last):
  File "/home/swang/anaconda3/envs/ray-wheel/lib/python3.7/site-packages/ray/dashboard/agent.py", line 383, in <module>
    loop.run_until_complete(agent.run())
  File "/home/swang/anaconda3/envs/ray-wheel/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/swang/anaconda3/envs/ray-wheel/lib/python3.7/site-packages/ray/dashboard/agent.py", line 167, in run
    modules = self._load_modules()
  File "/home/swang/anaconda3/envs/ray-wheel/lib/python3.7/site-packages/ray/dashboard/agent.py", line 132, in _load_modules
    c = cls(self)
TypeError: Can't instantiate abstract class JobAgent with abstract methods is_minimal_module
```

### Versions / Dependencies

2.0dev (commit fccf9fd642573b5992affd3b1b387777099f840f)
python 3.7.9 (using conda env)
Ubuntu

### Reproduction script

ray.init()

```
(ray-wheel) swang@swang-X1-Carbon:~$ ipython
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import ray

In [2]: ray.__commit__
Out[2]: 'fccf9fd642573b5992affd3b1b387777099f840f'

In [3]: ray.init()
2022-05-04 17:21:41,033	INFO services.py:1466 -- View the Ray dashboard at http://127.0.0.1:8265
Out[3]: RayContext(dashboard_url='127.0.0.1:8265', python_version='3.7.6', ray_version='2.0.0.dev0', ray_commit='fccf9fd642573b5992affd3b1b387777099f840f', address_info={'node_ip_address': '192.168.4.22', 'raylet_ip_address': '192.168.4.22', 'redis_address': None, 'object_store_address': '/tmp/ray/session_2022-05-04_17-21-38_192230_441629/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2022-05-04_17-21-38_192230_441629/sockets/raylet', 'webui_url': '127.0.0.1:8265', 'session_dir': '/tmp/ray/session_2022-05-04_17-21-38_192230_441629', 'metrics_export_port': 55383, 'gcs_address': '192.168.4.22:55189', 'address': '192.168.4.22:55189', 'node_id': 'e3fcdf34fe882a2eb6c3593c03f95209a0b23f21802ce5e46bc66634'})

(raylet) [2022-05-04 17:21:43,521 E 441695 441738] (raylet) agent_manager.cc:107: The raylet exited immediately because the Ray agent failed. The raylet fate shares with the agent. This can happen because the Ray agent was unexpectedly killed or failed. See `dashboard_agent.log` for the root cause.
In [4]: 2022-05-04 17:22:12,320	WARNING worker.py:1383 -- The node with node id: e3fcdf34fe882a2eb6c3593c03f95209a0b23f21802ce5e46bc66634 and ip: 192.168.4.22 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by stephanie-wang** [comment]
I think there is something left over from a previous Ray install; how do I fix it? Installing on a clean conda env works.

**Comment by stephanie-wang** [comment]
Hmm I'm going to close this since I'm not sure if it's reproducible.
