### ISSUE TITLE
Travis test failure in runtest.py testFlushAPI.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#2449]
This seems to have been introduced in #2422, though it's not clear to me what the issue is. @raulchen any ideas about this? This is causing the MacOS Python 2 Travis job to consistently fail.

```
testFlushAPI (__main__.GlobalStateAPI) ... Process STDOUT and STDERR is being redirected to /tmp/raylogs/.

Waiting for redis server at 127.0.0.1:49423 to respond...

Waiting for redis server at 127.0.0.1:32870 to respond...

Traceback (most recent call last):

  File "/Users/travis/.local/lib/python2.7/site-packages/ray-0.5.0-py2.7-macosx-10.6-x86_64.egg/ray/workers/default_worker.py", line 55, in <module>

    info, mode=ray.WORKER_MODE, use_raylet=(args.raylet_name is not None))

  File "/Users/travis/.local/lib/python2.7/site-packages/ray-0.5.0-py2.7-macosx-10.6-x86_64.egg/ray/worker.py", line 2036, in connect

    driver_id=None)

  File "/Users/travis/.local/lib/python2.7/site-packages/ray-0.5.0-py2.7-macosx-10.6-x86_64.egg/ray/utils.py", line 119, in push_error_to_driver_through_redis

    "data": data

  File "/Users/travis/.local/lib/python2.7/site-packages/ray-0.5.0-py2.7-macosx-10.6-x86_64.egg/ray/utils.py", line 332, in _wrapper

    return orig_attr(*args, **kwargs)

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/client.py", line 2011, in hmset

    return self.execute_command('HMSET', name, *items)

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/client.py", line 673, in execute_command

    connection.send_command(*args)

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/connection.py", line 610, in send_command

    self.send_packed_command(self.pack_command(*args))

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/connection.py", line 585, in send_packed_command

    self.connect()

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/connection.py", line 489, in connect

Traceback (most recent call last):

  File "/Users/travis/.local/lib/python2.7/site-packages/ray-0.5.0-py2.7-macosx-10.6-x86_64.egg/ray/workers/default_worker.py", line 55, in <module>

    info, mode=ray.WORKER_MODE, use_raylet=(args.raylet_name is not None))

  File "/Users/travis/.local/lib/python2.7/site-packages/ray-0.5.0-py2.7-macosx-10.6-x86_64.egg/ray/worker.py", line 2036, in connect

    raise ConnectionError(self._error_message(e))

redis.exceptions.ConnectionError: Error 61 connecting to 10.182.41.178:16289. Connection refused.

    driver_id=None)

  File "/Users/travis/.local/lib/python2.7/site-packages/ray-0.5.0-py2.7-macosx-10.6-x86_64.egg/ray/utils.py", line 119, in push_error_to_driver_through_redis

    "data": data

  File "/Users/travis/.local/lib/python2.7/site-packages/ray-0.5.0-py2.7-macosx-10.6-x86_64.egg/ray/utils.py", line 332, in _wrapper

    return orig_attr(*args, **kwargs)

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/client.py", line 2011, in hmset

    return self.execute_command('HMSET', name, *items)

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/client.py", line 673, in execute_command

    connection.send_command(*args)

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/connection.py", line 610, in send_command

    self.send_packed_command(self.pack_command(*args))

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/connection.py", line 585, in send_packed_command

    self.connect()

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/connection.py", line 489, in connect

    raise ConnectionError(self._error_message(e))

redis.exceptions.ConnectionError: Error 61 connecting to 10.182.41.178:16289. Connection refused.

Traceback (most recent call last):

  File "/Users/travis/.local/lib/python2.7/site-packages/ray-0.5.0-py2.7-macosx-10.6-x86_64.egg/ray/workers/default_worker.py", line 55, in <module>

    info, mode=ray.WORKER_MODE, use_raylet=(args.raylet_name is not None))

  File "/Users/travis/.local/lib/python2.7/site-packages/ray-0.5.0-py2.7-macosx-10.6-x86_64.egg/ray/worker.py", line 2036, in connect

    driver_id=None)

  File "/Users/travis/.local/lib/python2.7/site-packages/ray-0.5.0-py2.7-macosx-10.6-x86_64.egg/ray/utils.py", line 119, in push_error_to_driver_through_redis

    "data": data

  File "/Users/travis/.local/lib/python2.7/site-packages/ray-0.5.0-py2.7-macosx-10.6-x86_64.egg/ray/utils.py", line 332, in _wrapper

    return orig_attr(*args, **kwargs)

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/client.py", line 2011, in hmset

    return self.execute_command('HMSET', name, *items)

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/client.py", line 673, in execute_command

    connection.send_command(*args)

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/connection.py", line 610, in send_command

    self.send_packed_command(self.pack_command(*args))

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/connection.py", line 585, in send_packed_command

    self.connect()

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/connection.py", line 489, in connect

    raise ConnectionError(self._error_message(e))

redis.exceptions.ConnectionError: Error 61 connecting to 10.182.41.178:16289. Connection refused.

Traceback (most recent call last):

  File "/Users/travis/.local/lib/python2.7/site-packages/ray-0.5.0-py2.7-macosx-10.6-x86_64.egg/ray/workers/default_worker.py", line 55, in <module>

    info, mode=ray.WORKER_MODE, use_raylet=(args.raylet_name is not None))

  File "/Users/travis/.local/lib/python2.7/site-packages/ray-0.5.0-py2.7-macosx-10.6-x86_64.egg/ray/worker.py", line 2036, in connect

    driver_id=None)

  File "/Users/travis/.local/lib/python2.7/site-packages/ray-0.5.0-py2.7-macosx-10.6-x86_64.egg/ray/utils.py", line 119, in push_error_to_driver_through_redis

    "data": data

  File "/Users/travis/.local/lib/python2.7/site-packages/ray-0.5.0-py2.7-macosx-10.6-x86_64.egg/ray/utils.py", line 332, in _wrapper

    return orig_attr(*args, **kwargs)

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/client.py", line 2011, in hmset

    return self.execute_command('HMSET', name, *items)

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/client.py", line 673, in execute_command

    connection.send_command(*args)

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/connection.py", line 610, in send_command

    self.send_packed_command(self.pack_command(*args))

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/connection.py", line 585, in send_packed_command

    self.connect()

  File "/Users/travis/.local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/connection.py", line 489, in connect

    raise ConnectionError(self._error_message(e))

redis.exceptions.ConnectionError: Error 61 connecting to 10.182.41.178:16289. Connection refused.

Starting local scheduler with the following resources: {'GPU': 0, 'CPU': 1}.

Failed to start the UI, you may need to run 'pip install jupyter'.

Deleted 0 log files from Redis.

Deleted 1 event logs from Redis.

Deleted 11 task keys from Redis.

Deleted 20 object info keys from Redis.

Deleted 20 object location keys from Redis.

Deleted 9 finished tasks from Redis shard.

Deleted 1 finished tasks from Redis shard.

Deleted 0 finished tasks from Redis shard.

Deleted 0 finished tasks from Redis shard.

Deleted 0 finished tasks from Redis shard.

Deleted 0 finished tasks from Redis shard.

Deleted 0 finished tasks from Redis shard.

Deleted 0 finished tasks from Redis shard.

Deleted 0 finished tasks from Redis shard.

Deleted 0 finished tasks from Redis shard.

Deleted 0 finished tasks from Redis shard.

Deleted 0 finished tasks from Redis shard.

/Users/travis/build/ray-project/ray/src/local_scheduler/local_scheduler.cc:800: No task information found for object during reconstruction (no object entry yet)

/Users/travis/build/ray-project/ray/src/local_scheduler/local_scheduler.cc:800: No task information found for object during reconstruction (no object entry yet)

/Users/travis/build/ray-project/ray/src/local_scheduler/local_scheduler.cc:800: No task information found for object during reconstruction (no object entry yet)

/Users/travis/build/ray-project/ray/src/local_scheduler/local_scheduler.cc:800: No task information found for object during reconstruction (no object entry yet)

/Users/travis/build/ray-project/ray/src/local_scheduler/local_scheduler.cc:800: No task information found for object during reconstruction (no object entry yet)

Deleted 0 finished tasks from Redis shard.

Deleted 0 finished tasks from Redis shard.

Deleted 0 finished tasks from Redis shard.
```

**Comment by raulchen** [comment]
I don't have any clue from these error messages. I'll do some research tomorrow.

**Comment by raulchen** [comment]
hi @robertnishihara, I tested this test case on my Mac with Python 2. It consistently passes.
I also checked a few latest builds on Travis, and didn't find related failures. 
Could you help confirm if this is still an issue?

**Comment by robertnishihara** [comment]
Thanks @raulchen! It still seems to be happening, e.g., in https://travis-ci.com/ray-project/ray/builds/79802303 which is currently running.

I haven't been able to reproduce the issue locally, so it may be difficult to debug.

**Comment by raulchen** [comment]
I checked >10 more recent builds, it seems that https://travis-ci.com/ray-project/ray/builds/79802303 is the only one that has this issue. Note that some builds have this `ConnectionError` as well, but the the tests passed. While in this case, the test was stuck in a infinite loop and keeps printing `Deleted 0 finished tasks from Redis shard`.

It seems that this is because sometimes the worker cannot connect to redis, not very likely to be caused by the multi-thread change. Let's wait and see if this will become more frequent.
