### ISSUE TITLE
[Core] test_many_tasks failed with under utilization error

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#24526]
### What happened + What you expected to happen

```
Traceback (most recent call last):
  File "distributed/test_many_tasks.py", line 107, in <module>
    test()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "distributed/test_many_tasks.py", line 70, in test
    test_max_running_tasks(num_tasks)
  File "distributed/test_many_tasks.py", line 44, in test_max_running_tasks
    assert max_cpus - min_cpus_available > threshold, err_str
AssertionError: Only 1859.25/4096.0 cpus used.
```

This test hasn't failed for a long time. https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_qHXpABvkkjZJEba83czBnDYU?command-history-section=command_history

### Versions / Dependencies

master

### Reproduction script

nightly tests

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment]
cc @scv119 @jianoaix we might need to see the trend a bit

**Comment by jianoaix** [comment]
It's a bit unclear to me what this is trying to test. IIUC, this was to ensure there is a moment that it had >75% tasks up and running; is it about task launching speed, since tasks themselves are just sleep not burning cpus?
