### ISSUE TITLE
Installing ray in OSX fails: issue building pyarrow

### ISSUE THREAD

**Issue by jleni** [ray-project/ray#2465]
### System information
- **OS Platform and Distribution**: OSX 10.13.6
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5.0 - master
- **Python version**: 3.6.5
- **Exact command to reproduce**:
Following the instructions here:
http://ray.readthedocs.io/en/latest/installation.html#install-ray

### Describe the problem
It is not possible to install ray from source in OSX

### Source code / logs

```
+ echo 'installing pyarrow'
installing pyarrow
+ cd /Users/lenij/phd/ray/thirdparty/scripts/..//build/arrow/python
+ PKG_CONFIG_PATH=/Users/lenij/phd/ray/thirdparty/scripts/..//pkg/arrow/cpp/build/cpp-install/lib/pkgconfig
+ PYARROW_WITH_PLASMA=1
+ PYARROW_WITH_TENSORFLOW=1
+ PYARROW_BUNDLE_ARROW_CPP=1
+ /Users/lenij/phd/phdenv/bin/python setup.py build
/Users/lenij/phd/ray/thirdparty/build/arrow/python/.eggs/setuptools_scm-3.0.1-py3.6.egg/setuptools_scm/version.py:92: UserWarning: tag 'apache-arrow-0.9.0' no version found
  warnings.warn("tag %r no version found" % (tag,))
Traceback (most recent call last):
  File "setup.py", line 545, in <module>
    url="https://arrow.apache.org/"
  File "/Users/lenij/phd/phdenv/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Users/lenij/phd/phdenv/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
    k: v for k, v in attrs.items()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/Users/lenij/phd/phdenv/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options
    ep.load()(self, ep.name, value)
  File "/Users/lenij/phd/ray/thirdparty/build/arrow/python/.eggs/setuptools_scm-3.0.1-py3.6.egg/setuptools_scm/integration.py", line 23, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/Users/lenij/phd/ray/thirdparty/build/arrow/python/.eggs/setuptools_scm-3.0.1-py3.6.egg/setuptools_scm/__init__.py", line 128, in get_version
    parsed_version = _do_parse(config)
  File "/Users/lenij/phd/ray/thirdparty/build/arrow/python/.eggs/setuptools_scm-3.0.1-py3.6.egg/setuptools_scm/__init__.py", line 73, in _do_parse
    parse_result = _call_entrypoint_fn(config, config.parse)
  File "/Users/lenij/phd/ray/thirdparty/build/arrow/python/.eggs/setuptools_scm-3.0.1-py3.6.egg/setuptools_scm/__init__.py", line 36, in _call_entrypoint_fn
    return fn(config.absolute_root)
  File "setup.py", line 496, in parse_version
    version = setuptools_scm.git.parse(root, describe)
  File "/Users/lenij/phd/ray/thirdparty/build/arrow/python/.eggs/setuptools_scm-3.0.1-py3.6.egg/setuptools_scm/git.py", line 131, in parse
    branch=branch,
  File "/Users/lenij/phd/ray/thirdparty/build/arrow/python/.eggs/setuptools_scm-3.0.1-py3.6.egg/setuptools_scm/version.py", line 184, in meta
    assert parsed_version is not None, "cant parse version %s" % tag
AssertionError: cant parse version apache-arrow-0.9.0

```

**Comment by guoyuhong** [comment]
It looks like that your machine does not have `setuptools_scm` and while building the pyarrow package, the downloading process failed due to unstable connection. I recently found that the pip server seems not stable. It needs several retry to have the installation complete.
 
You can try to first install `setuptools_scm` by `pip install setuptools_scm`. After successfully installing `setuptools_scm`, then you can try to build this project again.

**Comment by robertnishihara** [comment]
Closing since the build system has changed a bit since then.
