### ISSUE TITLE
[<Ray matplotlib] plot issue  

### ISSUE THREAD

**Issue by JiahaoYao** [ray-project/ray#24654]
### What happened + What you expected to happen

Run the following code to generate the plots using ray remote. I already use `matplotlib.use('Agg')` to control the display issue. I am able to generate the plots using the plain `for-loop`. But it fails with the ray parallel. 

```python
import ray 
import matplotlib
# no display: agg
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np

@ray.remote
def main(): 
    x = np.linspace(0, 1, 100)
    y = np.sin(2*np.pi*x) + np.random.randn(100) 
    plt.plot(x, y)
    plt.savefig('test.png')

if __name__ == '__main__':
    ray.init()
    ray.get([main.remote() for i in range(4)])
```

The error message is 
```python
2022-05-10 10:07:32,501 INFO services.py:1462 -- View the Ray dashboard at http://127.0.0.1:8265
Traceback (most recent call last):
  File "scr_0510.py", line 17, in <module>
    ray.get([main.remote() for i in range(4)])
  File "/home/jimmy/anaconda3/envs/dl/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/jimmy/anaconda3/envs/dl/lib/python3.6/site-packages/ray/worker.py", line 1809, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TclError): ray::main() (pid=29150, ip=10.0.0.193)
  File "scr_0510.py", line 12, in main
    plt.plot(x, y)
  File "/home/jimmy/anaconda3/envs/dl/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3347, in plot
    ax = gca()
  File "/home/jimmy/anaconda3/envs/dl/lib/python3.6/site-packages/matplotlib/pyplot.py", line 984, in gca
    return gcf().gca(**kwargs)
  File "/home/jimmy/anaconda3/envs/dl/lib/python3.6/site-packages/matplotlib/pyplot.py", line 601, in gcf
    return figure()
  File "/home/jimmy/anaconda3/envs/dl/lib/python3.6/site-packages/matplotlib/pyplot.py", line 548, in figure
    **kwargs)
  File "/home/jimmy/anaconda3/envs/dl/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/jimmy/anaconda3/envs/dl/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 1044, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/home/jimmy/anaconda3/envs/dl/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
(raylet) INFO:ray.dashboard.utils:Available modules: [<class 'ray.dashboard.modules.event.event_agent.EventAgent'>, <class 'ray.dashboard.modules.log.log_agent.LogAgent'>, <class 'ray.dashboard.modules.reporter.reporter_agent.ReporterAgent'>, <class 'ray.dashboard.modules.runtime_env.runtime_env_agent.RuntimeEnvAgent'>]
(raylet) INFO:__main__:Loading DashboardAgentModule: <class 'ray.dashboard.modules.event.event_agent.EventAgent'>
(raylet) INFO:ray.dashboard.modules.event.event_agent:Event agent cache buffer size: 10240
(raylet) INFO:__main__:Loading DashboardAgentModule: <class 'ray.dashboard.modules.log.log_agent.LogAgent'>
(raylet) INFO:__main__:Loading DashboardAgentModule: <class 'ray.dashboard.modules.reporter.reporter_agent.ReporterAgent'>
(raylet) INFO:__main__:Loading DashboardAgentModule: <class 'ray.dashboard.modules.runtime_env.runtime_env_agent.RuntimeEnvAgent'>
(raylet) INFO:__main__:Loaded 4 modules.
(raylet) INFO:ray.dashboard.http_server_agent:Dashboard agent http address: 0.0.0.0:43565
(raylet) INFO:ray.dashboard.http_server_agent:<ResourceRoute [GET] <StaticResource  /logs -> PosixPath('/tmp/ray/session_2022-05-10_10-07-29_226780_28973/logs')> -> <bound method StaticResource._handle of <StaticResource  /logs -> PosixPath('/tmp/ray/session_2022-05-10_10-07-29_226780_28973/logs')>>
(raylet) INFO:ray.dashboard.http_server_agent:<ResourceRoute [OPTIONS] <StaticResource  /logs -> PosixPath('/tmp/ray/session_2022-05-10_10-07-29_226780_28973/logs')> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7f662ae803c8>>
(raylet) INFO:ray.dashboard.http_server_agent:Registered 2 routes.
(raylet) INFO:ray.dashboard.modules.event.event_agent:Report events to b'10.0.0.193:38435'
(raylet) INFO:ray.dashboard.modules.event.event_utils:Monitor events logs modified after 1652200655.1801198 on /tmp/ray/session_2022-05-10_10-07-29_226780_28973/logs/events, the source types are ['COMMON', 'CORE_WORKER', 'RAYLET'].
```

### Versions / Dependencies

system info
```bash
-------------------------------System Information----------------------------
Serial Number:
Machine Type:		Physical
Operating System:	Ubuntu 18.04.5 LTS
Kernel:			5.4.0-91-generic
Architecture:		x86_64
Processor Name:		Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

Python                    3.6.8
Ray                       1.12.0
```

### Reproduction script
This script is supposed to run on the remote machine, like `ec2`. 
```python
import ray 
import matplotlib
# no display: agg
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np

@ray.remote
def main(): 
    x = np.linspace(0, 1, 100)
    y = np.sin(2*np.pi*x) + np.random.randn(100) 
    plt.plot(x, y)
    plt.savefig('test.png')

if __name__ == '__main__':
    ray.init()
    ray.get([main.remote() for i in range(4)])
```

**Comment by JiahaoYao** [comment]
Thanks @dynamicwebpaige for the prompt response!
