### ISSUE TITLE
[serve] FastAPI integration does not support encapsulating `response_model` with `List`

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#24710]
### What happened + What you expected to happen

This script raises an error:

```python
from typing import List, Optional

from fastapi import FastAPI
from pydantic import BaseModel

from ray import serve

app = FastAPI()

class Item(BaseModel):
    name: str
    description: Optional[str] = None
    price: float
    tax: Optional[float] = None
    tags: List[str] = []

@serve.deployment
@serve.ingress(app)
class ItemCreator:

    @app.post("/items/", response_model=List[Item])
    async def create_item(items: List[Item]):
        return items
```

```
% python fastapi_bug.py
Traceback (most recent call last):
  File "fastapi_bug.py", line 20, in <module>
    class ItemCreator:
  File "/Users/shrekris/miniforge3/envs/apply-conf/lib/python3.8/site-packages/ray/serve/api.py", line 920, in decorator
    make_fastapi_class_based_view(app, cls)
  File "/Users/shrekris/miniforge3/envs/apply-conf/lib/python3.8/site-packages/ray/serve/http_util.py", line 235, in make_fastapi_class_based_view
    original_resp_fields = route.response_field.outer_type_.__fields__
  File "/Users/shrekris/miniforge3/envs/apply-conf/lib/python3.8/typing.py", line 760, in __getattr__
    raise AttributeError(attr)
AttributeError: __fields__
```

However, the pure FastAPI equivalent runs fine:

```python
from typing import List, Optional

from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()


class Item(BaseModel):
    name: str
    description: Optional[str] = None
    price: float
    tax: Optional[float] = None
    tags: List[str] = []


@app.post("/items/", response_model=List[Item])
async def create_item(items: List[Item]):
    return items
```

The issue seems to occur when encapsulating the `response_model` with a `List` type. However, [the FastAPI documentation mentions that this is allowed](https://fastapi.tiangolo.com/tutorial/response-model/#response-model):

> It [the `response_model`] receives the same type you would declare for a Pydantic model attribute, so, it can be a Pydantic model, but it can also be, e.g. a `list` of Pydantic models, like `List[Item]`.

### Versions / Dependencies

Ray 1.12.0, Python 3.8.13, MacOS 11.4 (M1).

### Reproduction script

```python
from typing import List, Optional

from fastapi import FastAPI
from pydantic import BaseModel

from ray import serve

app = FastAPI()

class Item(BaseModel):
    name: str
    description: Optional[str] = None
    price: float
    tax: Optional[float] = None
    tags: List[str] = []

@serve.deployment
@serve.ingress(app)
class ItemCreator:

    @app.post("/items/", response_model=List[Item])
    async def create_item(items: List[Item]):
        return items
```

```
% python fastapi_bug.py
Traceback (most recent call last):
  File "fastapi_bug.py", line 20, in <module>
    class ItemCreator:
  File "/Users/shrekris/miniforge3/envs/apply-conf/lib/python3.8/site-packages/ray/serve/api.py", line 920, in decorator
    make_fastapi_class_based_view(app, cls)
  File "/Users/shrekris/miniforge3/envs/apply-conf/lib/python3.8/site-packages/ray/serve/http_util.py", line 235, in make_fastapi_class_based_view
    original_resp_fields = route.response_field.outer_type_.__fields__
  File "/Users/shrekris/miniforge3/envs/apply-conf/lib/python3.8/typing.py", line 760, in __getattr__
    raise AttributeError(attr)
AttributeError: __fields__
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by shrekris-anyscale** [comment]
In case others run into this issue, one workaround is to make a separate Pydantic model that encapsulates the inner Pydantic model. For example:

```python
from typing import List, Optional

from fastapi import FastAPI
from pydantic import BaseModel

from ray import serve

app = FastAPI()

class Item(BaseModel):
    name: str
    description: Optional[str] = None
    price: float
    tax: Optional[float] = None
    tags: List[str] = []

class ItemList(BaseModel):
    items: List[Item]

@serve.deployment
@serve.ingress(app)
class ItemCreator:

    @app.post("/items/", response_model=ItemList)
    async def create_item(items: List[Item]):
        return items
```

This runs fine. The `ItemList` is acting like `List[Item]` did in the reproduction script.

You can also use [Pydantic's custom root types](https://pydantic-docs.helpmanual.io/usage/models/#custom-root-types) to create Pydantic models that act as Lists, Dictionaries, or other types.

**Comment by edoakes** [comment]
Maybe @sihanwang41 can take this to build familiarity with a new part of the code?

**Comment by sihanwang41** [comment]
yeah, I will take a look

**Comment by shrekris-anyscale** [comment]
@edoakes @sihanwang41 Yeah, that sounds good. I chatted with @simon-mo offline, and it sounds like this could be due to some workarounds used for serialization over the wire with CloudPickle. @simon-mo could you provide additional context here if there is any?
