### ISSUE TITLE
Ray component: Core: PoolActor processes hanging

### ISSUE THREAD

**Issue by frigobar93** [ray-project/ray#24784]
### What happened + What you expected to happen

I'm attempting to use a hybrid solution of ray.util.multiprocessing.Pool and multiprocessing.Pool. It works exactly as I'd hope for about 19 of every 20 jobs, but on the 1 job where it doesn't our Python script hangs at the Ray pool.map step. When I look at running processes I can see that, along with my hung Python script, there is what appears to be one or more hung Ray PoolActors. 

It's worth mentioning that my script runs thousands of processes which each complete within less than a second. I split those processes into batches (one per node) and then use Ray to send those batches to the nodes. On the nodes I use multiprocessing.Pool to actually run the processes. I found that using ray.util.multiprocessing.Pool to manage all of the processes across the nodes was slower than just using multiprocessing.Pool on a single node.

### Versions / Dependencies

Ray Version: 1.12.0
Python Version: 3.6.8
OS: Oracle Linux 7.6

### Reproduction script

To run correctly, it requires two files. The logging helps me identify hung jobs (shorter log file).

**File 1**

```python
import logging
import datetime
import ray
from ray.util.multiprocessing import Pool
from import_file import batch_function
ray.init(address="auto")

logging.basicConfig(level=logging.INFO)

def setup_rootlogger(dir, name):
    root_logger = logging.getLogger()
    root_logger.setLevel(logging.INFO)
    fh = logging.FileHandler('{}/{}.{}.log'.format(dir, name, datetime.datetime.now().strftime('%Y-%m-%d_%H%M')))
    fh.setLevel(logging.INFO)
    fh.setFormatter(logging.Formatter('%(asctime)s %(levelname)s %(name)s [%(filename)s:%(lineno)d] %(message)s'))
    root_logger.addHandler(fh)
   
def batches(l, n):
    return_l = []
    for i in range(0, n):
        return_l.append(l[i::n])
    return return_l

setup_rootlogger('/home/ray_experiment/logs', 'monitor')
processes = range(6074)   
cpus = int(ray.cluster_resources()['CPU'])  
processes = batches(processes, cpus)
logging.info('###### Multiprocessing start ######')

with Pool(cpus) as pool:
    results = pool.map(batch_function, [p for p in processes])

logging.info('###### Multiprocessing complete ######')
```

**File 2 (Referred to as import_file in File 1)**

```python
from time import sleep
from multiprocessing import Pool

def lower_function(args):
    sleep(.04)
    sleep(.42)
    return f'Result: {args}'

def batch_function(batch):
    with Pool(40) as pool:
        results = pool.map(lower_function, [p for p in batch])
    return results
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by czgdp1807** [comment]
I tried to reproduce and got the following logs,

```
.
.
.
(PoolActor pid=10696)     return _bootstrap._gcd_import(name[level:], package, level)
(PoolActor pid=10696)   File "C:\ProgramData\Anaconda3\envs\ray_dev\lib\site-packages\opentelemetry\trace\__init__.py", line 87, in <module>
(PoolActor pid=10696)     from opentelemetry.trace.propagation import (
(PoolActor pid=10696)   File "C:\ProgramData\Anaconda3\envs\ray_dev\lib\site-packages\opentelemetry\trace\propagation\__init__.py", line 18, in <module>
(PoolActor pid=10696)     from opentelemetry.trace.span import INVALID_SPAN, Span
(PoolActor pid=10696)   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
(PoolActor pid=10696)   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
(PoolActor pid=10696)   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
(PoolActor pid=10696)   File "<frozen importlib._bootstrap_external>", line 839, in exec_module
(PoolActor pid=10696)   File "<frozen importlib._bootstrap_external>", line 934, in get_code
(PoolActor pid=10696)   File "<frozen importlib._bootstrap_external>", line 1033, in get_data
(PoolActor pid=10696) MemoryError
(PoolActor pid=10696) Exception ignored in: <module 'collections.abc' from 'C:\\ProgramData\\Anaconda3\\envs\\ray_dev\\lib\\collections\\abc.py'>
(PoolActor pid=10696) Traceback (most recent call last):
(PoolActor pid=10696)   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
(PoolActor pid=10696) MemoryError:
. # hangs forever
```

**Comment by czgdp1807** [comment]
I changed `with Pool(40) as pool:` to `with Pool(8) as pool:` and added a debug print `print(processes)` after `processes = batches(processes, cpus)` and I got the following output,

```python
2022-05-19 07:54:57,623 INFO services.py:1478 -- View the Ray dashboard at http://127.0.0.1:8265
processes:  [range(0, 6074, 8), range(1, 6074, 8), range(2, 6074, 8), range(3, 6074, 8), range(4, 6074, 8), range(5, 6074, 8), range(6, 6074, 8), range(7, 6074, 8)] 8
INFO:root:###### Multiprocessing start ######
INFO:root:###### Multiprocessing complete ######
```

The code didn't hang.

**Comment by czgdp1807** [comment]
I did some calculations. So, you are launching a pool first with 8 processes in the beginning. I am referring to `with Pool(cpus) as pool:`. Now in the `import_file`, you launch another pool in each of these 8 pools. Kind of nested pooling. So, each of these nested pool now start 40 processes. I am referring to `with Pool(40) as pool:`. So, overall total number of processes started is 40 * 8 = 320. If that's the case then I am not surprised if the script hangs, especially on Windows. In addition, when 320 processes are there then average load process is 6074/320 ~ 19. If we replace `with Pool(40) as pool:` with `with Pool(8) as pool:` then total number of processes comes down to 64 and average load per process increases to 6074/64 ~ 95. So, may be try to increase the average load per processes so that we need lesser number of processes to be launched to get the job down.

P.S. Please feel free to let me know if I made a mistake in analysing your problem.

**Comment by frigobar93** [comment]
Thanks, I appreciate your insight. I'm using three Linux nodes, not Windows, and I restrict Ray to be able to use one CPU per node. 

ray start -v --head --port=6379 --num-cpus=1 --include-dashboard=false
ray start -v --address=$RAY_HEAD_IP:6379 --num-cpus=1

Being so, the math for my tests don't line up with what you've shown, but I will play with those settings and see if I can eliminate the hung processes.

Something to consider. I ran my script for about five days with a cronjob kicking it off once every five minutes. I only saw two memory errors in the logs even though the job failed many times. In addition, my script runs successfully more than 90% of the time. It's just the occasional script that hangs.

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
