### ISSUE TITLE
Ray init fails on AWS Lambda

### ISSUE THREAD

**Issue by nb-themes** [ray-project/ray#24826]
### What happened + What you expected to happen

When initializing ray on a 10GB lambda (6 CPUs) with a amazon/aws-lambda-python:3.8 Docker container I get the following error when trying to initialize with 3 CPUs:

```

[ERROR] SubprocessError: Exception occurred in preexec_fn.Traceback (most recent call last):  File "/var/lang/lib/python3.8/imp.py", line 234, in load_module    return load_source(name, filename, file)  File "/var/lang/lib/python3.8/imp.py", line 171, in load_source    module = _load(spec)  File "<frozen importlib._bootstrap>", line 702, in _load  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked  File "<frozen importlib._bootstrap_external>", line 843, in exec_module  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed  File "/var/task/app.py", line 25, in <module>    ray.init(num_cpus=num_cpus, ignore_reinit_error=True)  File "/var/lang/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper    return func(*args, **kwargs)  File "/var/lang/lib/python3.8/site-packages/ray/worker.py", line 933, in init    _global_node = ray.node.Node(  File "/var/lang/lib/python3.8/site-packages/ray/node.py", line 254, in __init__    self.start_head_processes()  File "/var/lang/lib/python3.8/site-packages/ray/node.py", line 1068, in start_head_processes    self.start_gcs_server()  File "/var/lang/lib/python3.8/site-packages/ray/node.py", line 910, in start_gcs_server    process_info = ray._private.services.start_gcs_server(  File "/var/lang/lib/python3.8/site-packages/ray/_private/services.py", line 1470, in start_gcs_server    process_info = start_ray_process(  File "/var/lang/lib/python3.8/site-packages/ray/_private/services.py", line 743, in start_ray_process    process = ConsolePopen(  File "/var/lang/lib/python3.8/subprocess.py", line 858, in __init__    self._execute_child(args, executable, preexec_fn, close_fds,  File "/var/lang/lib/python3.8/subprocess.py", line 1705, in _execute_child    raise child_exception_type(err_msg) | [ERROR] SubprocessError: Exception occurred in preexec_fn. Traceback (most recent call last):   File "/var/lang/lib/python3.8/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/lib/python3.8/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 702, in _load   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 843, in exec_module   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed   File "/var/task/app.py", line 25, in <module>     ray.init(num_cpus=num_cpus, ignore_reinit_error=True)   File "/var/lang/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper     return func(*args, **kwargs)   File "/var/lang/lib/python3.8/site-packages/ray/worker.py", line 933, in init     _global_node = ray.node.Node(   File "/var/lang/lib/python3.8/site-packages/ray/node.py", line 254, in __init__     self.start_head_processes()   File "/var/lang/lib/python3.8/site-packages/ray/node.py", line 1068, in start_head_processes     self.start_gcs_server()   File "/var/lang/lib/python3.8/site-packages/ray/node.py", line 910, in start_gcs_server     process_info = ray._private.services.start_gcs_server(   File "/var/lang/lib/python3.8/site-packages/ray/_private/services.py", line 1470, in start_gcs_server     process_info = start_ray_process(   File "/var/lang/lib/python3.8/site-packages/ray/_private/services.py", line 743, in start_ray_process     process = ConsolePopen(   File "/var/lang/lib/python3.8/subprocess.py", line 858, in __init__     self._execute_child(args, executable, preexec_fn, close_fds,   File "/var/lang/lib/python3.8/subprocess.py", line 1705, in _execute_child     raise child_exception_type(err_msg)
-- | --



```

### Versions / Dependencies

1.11.1

### Reproduction script

import ray
import psutil

num_cpus = psutil.cpu_count(logical=True)
print("Number of available CPUs:", num_cpus)
num_cpus = num_cpus // 2
# Start Ray cluster
ray.init(num_cpus=num_cpus, num_gpus=0, ignore_reinit_error=True)

### Issue Severity

High: It blocks me from completing my task.

**Comment by nb-themes** [comment]
Lambda unfortunately doesn't support multiprocess pools, only pipes and so ray won't work there.

```The multiprocessing module that comes with Python 2.7 lets you run multiple processes in parallel. Due to the Lambda execution environment not having /dev/shm (shared memory for processes) support, you can’t use multiprocessing.Queue or multiprocessing.Pool.
```
https://aws.amazon.com/blogs/compute/parallel-processing-in-python-with-aws-lambda/
