### ISSUE TITLE
inconsistent error messages

### ISSUE THREAD

**Issue by vlad17** [ray-project/ray#2492]
Ray suggests a pattern that it says is deprecated in an error message:

I mistakenly decorated a function with `ray.remote(gpus=3)`. Then I saw:
```
(lbs-env) ubuntu@ip-10-0-0-7:~/lbs$ python lbs/main/evaluate.py --experiment_directory logs/6f9fcd1ad0b13bd3d7fd23be3e18db8e 
Traceback (most recent call last):
  File "lbs/main/evaluate.py", line 9, in <module>
    from lbs.evaluate import single_experiment_result
  File "/home/ubuntu/lbs/lbs/__init__.py", line 4, in <module>
    from . import evaluate
  File "/home/ubuntu/lbs/lbs/evaluate.py", line 241, in <module>
    @ray.remote(gpus=1)
  File "/home/ubuntu/conda/envs/lbs-env/lib/python3.5/site-packages/ray/worker.py", line 2688, in remote
    "checkpoint_interval"], error_string
AssertionError: The @ray.remote decorator must be applied either with no arguments and no parentheses, for example '@ray.remote', or it must be applied using some of the arguments 'num_return_vals', 'resources', or 'max_calls', like '@ray.remote(num_return_vals=2, resources={"GPU": 1})'.
```

After switching it to `ray.remote(resources={"GPU": 1})`, I hit:
```
(lbs-env) ubuntu@ip-10-0-0-7:~/lbs$ python lbs/main/evaluate.py --experiment_directory logs/6f9fcd1ad0b13bd3d7fd23be3e18db8e 
Traceback (most recent call last):
  File "lbs/main/evaluate.py", line 9, in <module>
    from lbs.evaluate import single_experiment_result
  File "/home/ubuntu/lbs/lbs/__init__.py", line 4, in <module>
    from . import evaluate
  File "/home/ubuntu/lbs/lbs/evaluate.py", line 241, in <module>
    @ray.remote(resources={'GPU': 1})
  File "/home/ubuntu/conda/envs/lbs-env/lib/python3.5/site-packages/ray/worker.py", line 2654, in remote
    assert "GPU" not in resources, "Use the 'num_gpus' argument."
AssertionError: Use the 'num_gpus' argument.
```

Where of course using `num_gpus` works fine.

**Comment by richardliaw** [comment]
Are you on 0.4? Seems like this was fixed.

**Comment by vlad17** [comment]
Ah, yeah, my dep file uses  0.5 but I forgot I switched back because of #2447. Sorry.
