### ISSUE TITLE
[Core] driver occasionally hangs after node is preempted

### ISSUE THREAD

**Issue by dirkweissenborn** [ray-project/ray#24969]
### What happened + What you expected to happen

We are running jobs on preemptible GCP TPU VMs using autoscaling. On preemption the remote jobs (using ray.remote) do not restart even though we set max_failures to -1. The driver script seems to hang after that happens and the monitor doesn't show any resource requests.

My suspicion is that when preemption happens, the driver for some reason doesn't realize that the worker is gone and thinks the job is still running, waiting for it to finish (hence it hangs). 

Is there anyway I can verify this easily? Is there a way to inspect what jobs the driver script thinks it is running?

### Versions / Dependencies

ray 1.11

### Reproduction script

It is almost impossible to reproduce this easily as preemption happens sporadically. Just manually forcing a shutdown of the VM doesn't result in the same problem.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by mwtian** [comment]
When the driver hangs, can you use `py-spy` to dump the stack trace? Just want to confirm that the driver is indeed waiting on some results that are not being computed.

I have also seen in nightly tests where after many workers crashed (e.g. OOM killed), the driver hangs on `ray.get()` cc @stephanie-wang @jjyao

**Comment by stephanie-wang** [comment]
Another thing to try is to check `ray memory` ([docs](https://docs.ray.io/en/latest/ray-core/objects/memory-management.html#debugging-using-ray-memory)), which should tell you which objects the driver still thinks are pending.

**Comment by dirkweissenborn** [comment]
This is the pyspy dump of the idling driver script:

```
Process 4918: python3 python/***/train.py 
Python v3.8.10 (/opt/conda/envs/ray/bin/python3.8)

Thread 4918 (idle): "MainThread"
    get_objects (ray/worker.py:352)
    get (ray/worker.py:1756)
    wrapper (ray/_private/client_mode_hook.py:105)
...
Thread 4965 (idle): "ray_import_thread"
    wait (threading.py:306)
    _wait_once (grpc/_common.py:106)
    wait (grpc/_common.py:148)
    result (grpc/_channel.py:733)
    _poll_locked (ray/_private/gcs_pubsub.py:270)
    poll (ray/_private/gcs_pubsub.py:409)
    _run (ray/_private/import_thread.py:71)
    run (threading.py:870)
    _bootstrap_inner (threading.py:932)
    _bootstrap (threading.py:890)
Thread 4966 (idle): "ray_listen_error_messages"
    wait (threading.py:306)
    _wait_once (grpc/_common.py:106)
    wait (grpc/_common.py:148)
    result (grpc/_channel.py:733)
    _poll_locked (ray/_private/gcs_pubsub.py:270)
    poll (ray/_private/gcs_pubsub.py:340)
    listen_error_messages_from_gcs (ray/worker.py:1311)
    run (threading.py:870)
    _bootstrap_inner (threading.py:932)
    _bootstrap (threading.py:890)
Thread 4968 (idle): "ray_print_logs"
    wait (threading.py:306)
    _wait_once (grpc/_common.py:106)
    wait (grpc/_common.py:148)
    result (grpc/_channel.py:733)
    _poll_locked (ray/_private/gcs_pubsub.py:270)
    poll (ray/_private/gcs_pubsub.py:374)
    print_logs (ray/worker.py:464)
    run (threading.py:870)
    _bootstrap_inner (threading.py:932)
    _bootstrap (threading.py:890)
Thread 13119 (idle): "Thread-13088"
    channel_spin (grpc/_channel.py:1258)
    run (threading.py:870)
    _bootstrap_inner (threading.py:932)
    _bootstrap (threading.py:890)
Thread 13186 (idle): "Thread-13095"
    channel_spin (grpc/_channel.py:1258)
    run (threading.py:870)
    _bootstrap_inner (threading.py:932)
    _bootstrap (threading.py:890)
Thread 13208 (idle): "Thread-13100"
    channel_spin (grpc/_channel.py:1258)
    run (threading.py:870)
    _bootstrap_inner (threading.py:932)
    _bootstrap (threading.py:890)
```

**Comment by dirkweissenborn** [comment]
ray memory is not working for me. ray is running though, I can for instance run ray status.

```
ray memory
Traceback (most recent call last):
  File "/opt/conda/envs/ray/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/ray/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1958, in main
    return cli()
  File "/opt/conda/envs/ray/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/ray/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/ray/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/ray/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/ray/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/ray/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1475, in memory
    mem_stats = memory_summary(address, redis_password, group_by, sort_by,
  File "/opt/conda/envs/ray/lib/python3.8/site-packages/ray/internal/internal_api.py", line 41, in memory_summary
    return (memory_summary(state, group_by, sort_by, line_wrap, units,
  File "/opt/conda/envs/ray/lib/python3.8/site-packages/ray/dashboard/memory_utils.py", line 372, in memory_summary
    node_stats(raylet["NodeManagerAddress"],
  File "/opt/conda/envs/ray/lib/python3.8/site-packages/ray/internal/internal_api.py", line 103, in node_stats
    node_stats = stub.GetNodeStats(
  File "/opt/conda/envs/ray/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/conda/envs/ray/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1653034026.414809974","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1653034026.414808883","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
```

**Comment by jjyao** [comment]
Based on the stack, it indeed hangs on `ray.get()`. We can use chaos test (randomly kill node to mimic preemption) to reproduce it.  @mwtian Do you remember which release test hanged before, we can add a chaos test for it

**Comment by mwtian** [comment]
I have seen `dataset_shuffle_push_based_random_shuffle_1tb` hangs after many workers are OOM killed, without any Raylet crash. Adding a shuffle test with randomly crashing workers will be great!

**Comment by merrysailor** [comment]
Hi,

I get this very consistently, i.e., after a GCP node preemption, the ray.get call on the driver "hangs", in the sense that ray memory reports that the relevant tasks are SCHEDULED, but no task actually runs on the cluster. This is for ray 1.12.1 and 1.13.0. Is there anything I could try to provide more information? I am attaching some logs from gcs_server.out

`
[2022-08-16 12:47:47,774 I 1678 1678] (gcs_server) gcs_node_manager.cc:42: Registering node info, node id = f2ae9432a536dd27657ec1a063b1fc85d3697490869a28a6422e37be, address = 10.128.0.112, node name = 10.128.0.112
[2022-08-16 12:47:47,774 I 1678 1678] (gcs_server) gcs_node_manager.cc:48: Finished registering node info, node id = f2ae9432a536dd27657ec1a063b1fc85d3697490869a28a6422e37be, address = 10.128.0.112, node name = 10.128.0.112
[2022-08-16 12:47:47,776 I 1678 1678] (gcs_server) gcs_placement_group_manager.cc:720: A new node: f2ae9432a536dd27657ec1a063b1fc85d3697490869a28a6422e37be registered, will try to reschedule all the infeasible placement groups.
[2022-08-16 13:02:15,608 W 1678 1692] (gcs_server) gcs_heartbeat_manager.cc:106: Node timed out: f2ae9432a536dd27657ec1a063b1fc85d3697490869a28a6422e37be
[2022-08-16 13:02:15,608 I 1678 1678] (gcs_server) gcs_node_manager.cc:199: Removing node, node id = f2ae9432a536dd27657ec1a063b1fc85d3697490869a28a6422e37be, node name = 10.128.0.112
[2022-08-16 13:02:15,608 W 1678 1678] (gcs_server) gcs_node_manager.cc:221: The node with node id: f2ae9432a536dd27657ec1a063b1fc85d3697490869a28a6422e37be and address: 10.128.0.112 and node name: 10.128.0.112 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.
[2022-08-16 13:02:15,609 I 1678 1678] (gcs_server) gcs_placement_group_manager.cc:695: Node f2ae9432a536dd27657ec1a063b1fc85d3697490869a28a6422e37be failed, rescheduling the placement groups on the dead node.
[2022-08-16 13:02:15,609 I 1678 1678] (gcs_server) gcs_actor_manager.cc:920: Node f2ae9432a536dd27657ec1a063b1fc85d3697490869a28a6422e37be failed, reconstructing actors.
[2022-08-16 13:17:25,014 I 1678 1678] (gcs_server) gcs_resource_report_poller.cc:143: Couldn't get resource request from raylet f2ae9432a536dd27657ec1a063b1fc85d3697490869a28a6422e37be: GrpcUnavailable: RPC Error message: Connection timed out; RPC Error details:
`

The log above looks normal to me except perhaps the last line. Note that there are 3 groups of timestamps: when the node comes up, when it goes down and then the last line. At that time I realized what happened and started issueing some 'ray memory' calls. The question is why does GCS still have a reference to the dead node at that point?

Please let me know if I can provide more information.

Thank you.

**Comment by jjyao** [comment]
Hi @merrysailor,

Glad to hear that you can reproduce it consistently. Do you mind posting a single repro script with the cluster setup, so I can try to reproduce it on my side as well. Also could you try the nightly wheel (https://docs.ray.io/en/latest/ray-overview/installation.html#daily-releases-nightlies) to see if the issue still exists on master? Thanks!

**Comment by merrysailor** [comment]
Hi,

A quick update. While I get this very consistently in the presence of GCP preemptions, I still haven't been able to replicate it otherwise: I have tried killing various ray 'worker' processes in different ways, but none seems to trigger the issue so far. So, still trying to work out what makes preemptions unique. I have been using Ray 2.0.0 released today. Something to note is that the 'hang' tasks now appear in state WAITING_FOR_EXECUTION indefintely.

**Comment by jjyao** [comment]
@merrysailor thanks for the update! A reproduction with GCP preemptions is also helpful, we can try to set up the same GCP cluster and debug from there.

**Comment by iycheng** [comment]
Got it reproduced:
```
ray start --head --num-cpus=1
ray start --num-cpus=4 --address=localhost:6379
```

And then
```
import ray
ray.init()
@ray.remote(num_cpus=4)
def f():
  print("???")
  import time
  time.sleep(10000)


ray.get(f.remote())
```

Then kill raylet 1

**Comment by zhe-thoughts** [comment]
Bumping to P0 based a recently reported incident.

**Comment by iycheng** [comment]
The script is not the right way to reproduce, it hangs because of the sleep.
Checked the code, if the gRPC disconnected due to server, it should return an error, but somehow it hangs.

**Comment by scv119** [comment]
Also it's fascinating the failure only happens when node preempted. I wonder if it's specific to the behavior of node abruptly shutdown around http2.0

**Comment by scv119** [comment]
https://groups.google.com/g/grpc-io/c/YPjQiElDhN0 FWIW

**Comment by scv119** [comment]
https://www.google.com/search?q=grpc+invoke+hang+site:github.com&rlz=1C5CHFA_enUS955US955&sa=X&ved=2ahUKEwjKheOX8L78AhVUrIkEHZXqAUAQrQIoBHoECBgQBQ&biw=1792&bih=984&dpr=2  :/

**Comment by scv119** [comment]
confirmed it's a grpc issue where the worker node (server) is dead but the grpc client failed to detect server failure.
