### ISSUE TITLE
[Datasets/AIR] Fix unsqueezing semantics for `ds.to_torch()` and `TorchPredictor`

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#24973]
### What happened + What you expected to happen

From @bveeramani:

The semantics for tensor unsqueezing for data ingest to training (`ds.to_torch()`), and for inference (`TorchPredictor.predict()`) is unintuitive and does not always work.

For example,
```
>>> import pandas as pd
>>> import ray
>>> df = pd.DataFrame({"X1": [1, 2, 3], "X2": [4, 5, 6], "X3": [7, 8, 9]})
>>> ds = ray.data.from_pandas(df)
>>> dataset = ds.to_torch(feature_columns=["X1", "X2"], unsqueeze_feature_tensors=False, batch_size=2)
>>> next(iter(dataset))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/amog/dev/ray/python/ray/data/impl/torch_iterable_dataset.py", line 10, in __iter__
    yield from it
  File "/Users/amog/dev/ray/python/ray/data/dataset.py", line 2397, in make_generator
    features_tensor = convert_pandas_to_torch_tensor(
  File "/Users/amog/dev/ray/python/ray/ml/utils/torch_utils.py", line 101, in convert_pandas_to_torch_tensor
    return get_tensor_for_columns(columns=columns, dtype=column_dtypes)
  File "/Users/amog/dev/ray/python/ray/ml/utils/torch_utils.py", line 88, in get_tensor_for_columns
    feature_tensor = torch.cat(feature_tensors, dim=1)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

Or when working with tensor data with unsqueeze set to True, the extra dimension is added right after the batch dimension, instead of as the last dimension.
```
>>> df = pd.DataFrame({"image": list(np.ones((2, 2, 4)))})
>>> df["image"][0].shape
(2, 4)
>>> next(iter(ds.to_torch(unsqueeze_feature_tensors=True, batch_size=2)))[0].shape
torch.Size([2, 1, 2, 4])
>>> next(iter(ds.to_torch(unsqueeze_feature_tensors=False, batch_size=2)))[0].shape
torch.Size([2, 2, 4])
```

It's the same thing even if you use the `TensorArray` extension
```
>>> from ray.data.extensions import TensorArray
>>> df = pd.DataFrame({"image": TensorArray(np.ones((2, 2, 4)))})
>>> ds = ray.data.from_pandas(df)
>>> next(iter(ds.to_torch(unsqueeze_feature_tensors=True, batch_size=2)))[0].shape
torch.Size([2, 1, 2, 4])
>>> next(iter(ds.to_torch(unsqueeze_feature_tensors=True, batch_size=2)))[0].shape
torch.Size([2, 1, 2, 4])
```

We should make the squeezing semantics very clear, and reconsider whether we actually need this customization at all so that users don't shoot themselves in the foot.

### Versions / Dependencies

Ray master

### Reproduction script

See above

**Comment by clarkzinzow** [comment]
Strongly agreed with this! I was actually going to try to fix this as a driveby before Datasets GA but didn't have time.

**Comment by ericl** [comment]
Downgrading priority since to_torch/to_tf will be experimental in 2.0 (we should make sure to mark them as so).
