### ISSUE TITLE
ray.init("auto") not finding instance 

### ISSUE THREAD

**Issue by Joshuaalbert** [ray-project/ray#24983]
### What happened + What you expected to happen

I start a ray head node, and then try to connect in a python script to deploy a backend. The python script raises error that there is no instance running, and asks to use `serve.start(detached=True)`. I'd like to be able to use the detached instance version so that I can update deployments.

### Versions / Dependencies

```
ray, version 1.12.1
Redis server v=6.0.15 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=d583da279d383435
```

### Reproduction script

Run in shell
```bash
ray start --head
```

Run the following python script
```python
from ray import serve
import ray

@serve.deployment(route_prefix="/hello", version="v1")
class A:
    async def __call__(self, request):
        payload = await request.json()
        print(f"Received flask request with data {payload}")

if __name__ == '__main__':
    ray.init(address='auto')
    A.deploy()
```

Observe:
```bash
  File "/home/albert/miniconda3/envs/tf_py/lib/python3.8/site-packages/ray/serve/api.py", line 834, in _connect
    controller = ray.get_actor(controller_name, namespace=controller_namespace)
  File "/home/albert/miniconda3/envs/tf_py/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/albert/miniconda3/envs/tf_py/lib/python3.8/site-packages/ray/worker.py", line 2031, in get_actor
    return worker.core_worker.get_named_actor_handle(name, namespace or "")
  File "python/ray/_raylet.pyx", line 1875, in ray._raylet.CoreWorker.get_named_actor_handle
  File "python/ray/_raylet.pyx", line 171, in ray._raylet.check_status
ValueError: Failed to look up actor with name 'SERVE_CONTROLLER_ACTOR'. This could because 1. You are trying to look up a named actor you didn't create. 2. The named actor died. 3. You did not use a namespace matching the namespace of the actor.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/albert/git/THA-Oracle/scripts/deploy.py", line 12, in <module>
    A.deploy()
  File "/home/albert/miniconda3/envs/tf_py/lib/python3.8/site-packages/ray/serve/api.py", line 1267, in deploy
    return internal_get_global_client().deploy(
  File "/home/albert/miniconda3/envs/tf_py/lib/python3.8/site-packages/ray/serve/api.py", line 145, in internal_get_global_client
    return _connect(_override_controller_namespace=_override_controller_namespace)
  File "/home/albert/miniconda3/envs/tf_py/lib/python3.8/site-packages/ray/serve/api.py", line 836, in _connect
    raise RayServeException(
ray.serve.exceptions.RayServeException: There is no instance running on this Ray cluster. Please call `serve.start(detached=True) to start one.
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by Joshuaalbert** [comment]
Resolved: I didn't realise you also need to add `serve.start(detached=True)` after `ray.init(address='auto')`. Documentation is not super clear.
