### ISSUE TITLE
[Train] Repeat assignments for preprocessor results nested recursive calling in Callback

### ISSUE THREAD

**Issue by valtab** [ray-project/ray#25005]
### Search before asking ###

- [x] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### The issue: ###

`callback.results_preprocessor` property is initialized in `callback._preprocess_results()` method as below, 

```python
system_preprocessor = ExcludedKeysResultsPreprocessor(results_to_exclude)
if self.results_preprocessor:
    self.results_preprocessor = SequentialResultsPreprocessor(
        [system_preprocessor, self.results_preprocessor]
    )
else:
    self.results_preprocessor = system_preprocessor
```

however,`callback. _preprocess_results()` method was called **every time** `train.report()` is called (in `callback.process_results()` method), this results nested recursive calling for chained `SequentialResultsPreprocessor`s, and will finally raise RecursionError, as below,

```shell
Traceback (most recent call last):
  File "/home/ray/python/callback_nested_recusive.py", line 15, in <module>
    trainer.run(train_func, callbacks=[PrintCallback()])
  File "/root/.cache/pypoetry/virtualenvs/ray-kTUtPfas-py3.9/lib/python3.9/site-packages/ray/train/trainer.py", line 336, in run
    callback.process_results(intermediate_result)
  File "/root/.cache/pypoetry/virtualenvs/ray-kTUtPfas-py3.9/lib/python3.9/site-packages/ray/train/callbacks/callback.py", line 56, in process_results
    results = self._preprocess_results(results)
  File "/root/.cache/pypoetry/virtualenvs/ray-kTUtPfas-py3.9/lib/python3.9/site-packages/ray/train/callbacks/callback.py", line 86, in _preprocess_results
    results = self.results_preprocessor.preprocess(results)
  File "/root/.cache/pypoetry/virtualenvs/ray-kTUtPfas-py3.9/lib/python3.9/site-packages/ray/train/callbacks/results_preprocessors/preprocessor.py", line 48, in preprocess
    results = preprocessor.preprocess(results)
  File "/root/.cache/pypoetry/virtualenvs/ray-kTUtPfas-py3.9/lib/python3.9/site-packages/ray/train/callbacks/results_preprocessors/preprocessor.py", line 48, in preprocess
    results = preprocessor.preprocess(results)
  File "/root/.cache/pypoetry/virtualenvs/ray-kTUtPfas-py3.9/lib/python3.9/site-packages/ray/train/callbacks/results_preprocessors/preprocessor.py", line 48, in preprocess
    results = preprocessor.preprocess(results)
  [Previous line repeated 991 more times]
  File "/root/.cache/pypoetry/virtualenvs/ray-kTUtPfas-py3.9/lib/python3.9/site-packages/ray/train/callbacks/results_preprocessors/keys.py", line 26, in preprocess
    new_results = [
  File "/root/.cache/pypoetry/virtualenvs/ray-kTUtPfas-py3.9/lib/python3.9/site-packages/ray/train/callbacks/results_preprocessors/keys.py", line 29, in <listcomp>
    for key, value in result.items()
RecursionError: maximum recursion depth exceeded while calling a Python object
```

`callback.results_preprocessor ` property value as below,

![image](https://user-images.githubusercontent.com/43571741/169445936-6cc75025-fd08-48aa-a98e-8d6267ec18ae.png)

### The fix: ###

Move ` callback.results_preprocessor ` initialization to `callback.start_training()` method which is called once on training start

### Are you willing to submit a PR? ###

- [x]  Yes I am willing to submit a PR!

### Versions / Dependencies

Ray: 1.12.0
Python: 3.9.5
OS: CentOS 7.4

### Reproduction script

```python
from ray import train
from ray.train import Trainer
from ray.train.callbacks import PrintCallback


def train_func():
    # default limits in python
    num_iterates = 1000
    for idx in range(num_iterates):
        train.report(iterate=idx + 1)


if __name__ == '__main__':
    trainer = Trainer("torch", num_workers=1)
    trainer.start()
    trainer.run(train_func, callbacks=[PrintCallback()])
    trainer.shutdown()

```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by Nithanaroy** [comment]
I still see a similar error with ray 2.0.1
```
2022-11-23 22:58:19,893	INFO trainer.py:253 -- Run results will be logged in: /home/jobuser/ray_results/train_2022-11-23_22-58-16/run_001
(BackendExecutor pid=103, ip=100.96.205.71) 2022-11-23 22:58:20.020095: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
(BackendExecutor pid=103, ip=100.96.205.71) 2022-11-23 22:58:22,111	ERROR serialization.py:354 -- maximum recursion depth exceeded while calling a Python object
(BackendExecutor pid=103, ip=100.96.205.71) Traceback (most recent call last):
(BackendExecutor pid=103, ip=100.96.205.71)   File "/home/jobuser/.local/lib/python3.7/site-packages/ray/_private/serialization.py", line 352, in deserialize_objects
(BackendExecutor pid=103, ip=100.96.205.71)     obj = self._deserialize_object(data, metadata, object_ref)
(BackendExecutor pid=103, ip=100.96.205.71)   File "/home/jobuser/.local/lib/python3.7/site-packages/ray/_private/serialization.py", line 241, in _deserialize_object
(BackendExecutor pid=103, ip=100.96.205.71)     return self._deserialize_msgpack_data(data, metadata_fields)
(BackendExecutor pid=103, ip=100.96.205.71)   File "/home/jobuser/.local/lib/python3.7/site-packages/ray/_private/serialization.py", line 196, in _deserialize_msgpack_data
(BackendExecutor pid=103, ip=100.96.205.71)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(BackendExecutor pid=103, ip=100.96.205.71)   File "/home/jobuser/.local/lib/python3.7/site-packages/ray/_private/serialization.py", line 186, in _deserialize_pickle5_data
(BackendExecutor pid=103, ip=100.96.205.71)     obj = pickle.loads(in_band)
(BackendExecutor pid=103, ip=100.96.205.71)   File "/home/jobuser/.local/lib/python3.7/site-packages/ray/train/_internal/utils.py", line 184, in __getattr__
(BackendExecutor pid=103, ip=100.96.205.71)     actor_method = getattr(self.actor, item)
(BackendExecutor pid=103, ip=100.96.205.71)   File "/home/jobuser/.local/lib/python3.7/site-packages/ray/train/_internal/utils.py", line 184, in __getattr__
(BackendExecutor pid=103, ip=100.96.205.71)     actor_method = getattr(self.actor, item)
(BackendExecutor pid=103, ip=100.96.205.71)   File "/home/jobuser/.local/lib/python3.7/site-packages/ray/train/_internal/utils.py", line 184, in __getattr__
(BackendExecutor pid=103, ip=100.96.205.71)     actor_method = getattr(self.actor, item)
(BackendExecutor pid=103, ip=100.96.205.71)   [Previous line repeated 492 more times]
(BackendExecutor pid=103, ip=100.96.205.71) RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by amogkam** [comment]
@Nithanaroy from the stack trace this looks like a different issue. Can you post a new Github issue with your full code and tag me, and I can take a look? Thanks!

**Comment by Nithanaroy** [comment]
Hi @amogkam 
I posted more details in https://discuss.ray.io/t/recursionerror-maximum-recursion-depth-exceeded-while-calling-a-python-object/5834

But unfortunately, I cant think of any simple reproducible script. We could either try a debug session or I can share any more logs with you.
