### ISSUE TITLE
[Core | Python 3.10] Actor cannot be created when Ray is used within ipython  

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#25026]
### What happened + What you expected to happen

When Ray is used within Ipython or Python shell, the following error occurs.

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/sangbincho/work/ray/python/ray/worker.py", line 2276, in remote
    return _make_remote(args[0], {})
  File "/Users/sangbincho/work/ray/python/ray/worker.py", line 2147, in _make_remote
    return ray.actor.make_actor(function_or_class, options)
  File "/Users/sangbincho/work/ray/python/ray/actor.py", line 1261, in make_actor
    return ActorClass._ray_from_modified_class(
  File "/Users/sangbincho/work/ray/python/ray/actor.py", line 473, in _ray_from_modified_class
    actor_creation_function_descriptor = PythonFunctionDescriptor.from_class(
  File "python/ray/includes/function_descriptor.pxi", line 209, in ray._raylet.PythonFunctionDescriptor.from_class
    module_name = cls._get_module_name(target_class)
  File "python/ray/includes/function_descriptor.pxi", line 308, in ray._raylet.PythonFunctionDescriptor._get_module_name
    file_path = inspect.getfile(object)
  File "/Users/sangbincho/anaconda3/envs/py310/lib/python3.10/inspect.py", line 785, in getfile
    raise OSError('source code not available')
OSError: source code not available
```

It doesn't happen when Ray is used outside the shell (but as a regular script). 

### Versions / Dependencies

Ray with python 3.10

### Reproduction script

```
import ray
ray.init()
@ray.remote
class A:
    pass
```

inside ipython

**Comment by rkooo567** [comment]
@scv119 Set P0 since this is a huge blocker for Python 3.10 use case, and I believe we are planning to make Python 3.10 available asap

**Comment by rkooo567** [comment]
Hmm actually I've seen this issue when I ran `test_output.py`. Maybe we should fix this before making an alpha wheel?

**Comment by rkooo567** [comment]
Oh this has been added to Python 3.10 https://github.com/python/cpython/blob/4d363d8989bf79f091bf674701e6066908af788d/Lib/inspect.py#L784

**Comment by rkooo567** [comment]
It was added from this PR https://github.com/python/cpython/pull/27171/files
