### ISSUE TITLE
[Ray Air] `to_tf` not works for the image

### ISSUE THREAD

**Issue by JiahaoYao** [ray-project/ray#25055]
### What happened + What you expected to happen

When I use the `ray.data` for the CV tasks, the `to_tf` raise some shape error. 

Here are the examples I have test 

```python
import ray
import tensorflow as tf 
import tensorflow_datasets as tfds
import pandas as pd
from ray.data.datasource import SimpleTensorFlowDatasource
import numpy as np

def train_dataset_factory():
    return tfds.load("mnist", split=["train"], as_supervised=True)[0].take(10)

def test_dataset_factory():
    return tfds.load("mnist", split=["test"], as_supervised=True)[0].take(10)

train_dataset = ray.data.read_datasource(  
    SimpleTensorFlowDatasource(), dataset_factory=train_dataset_factory
)
test_dataset = ray.data.read_datasource(SimpleTensorFlowDatasource(), dataset_factory=test_dataset_factory)



def convert_batch_to_pandas(batch):

    images = [image for image, _ in batch]

    df = pd.DataFrame({"image": images, "label": images})
    return df
    
train_dataset = train_dataset.map_batches(convert_batch_to_pandas)
test_dataset = test_dataset.map_batches(convert_batch_to_pandas)


mydata = train_dataset.to_tf(
            feature_columns=["image"],
            label_column="label",
            output_signature=(
                tf.TensorSpec(shape=(None, 784), dtype=tf.float32),
                tf.TensorSpec(shape=(None, 784), dtype=tf.float32),
            ),
            batch_size=2,
        )

print(mydata)

print(mydata.__iter__().get_next()[0].shape)
print(mydata.__iter__().get_next()[1].shape)
```

Here are the results
```python
2022-05-21 01:07:22,939 INFO services.py:1478 -- View the Ray dashboard at http://127.0.0.1:8265
(_prepare_read pid=46142) 2022-05-21 01:07:26,400       WARNING tensorflow_datasource.py:53 -- `SimpleTensorFlowDatasource` doesn't support parallel reads. The `parallelism` argument will be ignored.
2022-05-21 01:07:26,405 WARNING read_api.py:252 -- The number of blocks in this dataset (1) limits its parallelism to 1 concurrent tasks. This is much less than the number of available CPU slots in the cluster. Use `.repartition(n)` to increase the number of dataset blocks.
(_execute_read_task pid=46142) 2022-05-21 01:07:26.585040: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-05-21 01:07:26,837 WARNING read_api.py:252 -- The number of blocks in this dataset (1) limits its parallelism to 1 concurrent tasks. This is much less than the number of available CPU slots in the cluster. Use `.repartition(n)` to increase the number of dataset blocks.
Read->Map_Batches:   0%|                                                                                                   | 0/1 [00:00<?, ?it/s](_prepare_read pid=46142) 2022-05-21 01:07:26,834       WARNING tensorflow_datasource.py:53 -- `SimpleTensorFlowDatasource` doesn't support parallel reads. The `parallelism` argument will be ignored.
Read->Map_Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.58it/s]
Read->Map_Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.58it/s]
Map_Batches: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 92.37it/s]
Map_Batches: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 121.01it/s]
<FlatMapDataset element_spec=(TensorSpec(shape=(None, 784), dtype=tf.float32, name=None), TensorSpec(shape=(None, 784), dtype=tf.float32, name=None))>
(2, 784) (2,)
Traceback (most recent call last):
  File "ray_dataset_issue.py", line 270, in <module>
    print(mydata.__iter__().get_next()[0].shape)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 819, in get_next
    return self._next_internal()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 749, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3017, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 7164, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.UnknownError: SystemExit: None
Traceback (most recent call last):

  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 270, in __call__
    ret = func(*args)

  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1030, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/data/dataset.py", line 2779, in make_generator
    exit()

  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)

SystemExit: None


         [[{{node PyFunc}}]] [Op:IteratorGetNext]
```

The reason of causing this are two-fold: 1) the "image" entry in the `pd.dataframe` is an image not a scalar; 2) the "label" entry in the `pd.dataframe` is an image not a scalar.

The issue is related to  https://github.com/ray-project/ray/blob/master/python/ray/data/dataset.py#L2581-L2582 and https://github.com/ray-project/ray/blob/master/python/ray/data/dataset.py#L2574-L2575. 

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by JiahaoYao** [comment]
@amogkam

**Comment by JiahaoYao** [comment]
using the new release, I still encounter the shape issue 


```python
import ray
import tensorflow as tf 
import tensorflow_datasets as tfds
import pandas as pd
from ray.data.datasource import SimpleTensorFlowDatasource
import numpy as np
from typing import (
    List,
    Any,
    Callable,
    Iterator,
    Iterable,
    Generic,
    Dict,
    Optional,
    Union,
    TYPE_CHECKING,
    Tuple,
)
TensorflowFeatureTypeSpec = Union[
    "tf.TypeSpec", List["tf.TypeSpec"], Dict[str, "tf.TypeSpec"]
]

from ray.data.extensions import TensorArray


def train_dataset_factory():
    return tfds.load("mnist", split=["train"], as_supervised=True)[0].take(10)

def test_dataset_factory():
    return tfds.load("mnist", split=["test"], as_supervised=True)[0].take(10)

train_dataset = ray.data.read_datasource(  
    SimpleTensorFlowDatasource(), dataset_factory=train_dataset_factory
)
test_dataset = ray.data.read_datasource(SimpleTensorFlowDatasource(), dataset_factory=test_dataset_factory)


def convert_batch_to_pandas(batch):
    images = TensorArray([tf.reshape(image, (-1)) for image, _ in batch])
    df = pd.DataFrame({"image": images, "label": images})
    return df
    
train_dataset = train_dataset.map_batches(convert_batch_to_pandas)
test_dataset = test_dataset.map_batches(convert_batch_to_pandas)


mydata = train_dataset.to_tf(
            feature_columns=["image"],
            label_column="label",
            output_signature=(
                tf.TensorSpec(shape=(None, 784), dtype=tf.float32),
                tf.TensorSpec(shape=(None, 784), dtype=tf.float32),
            ),
            batch_size=2,
        )

print(mydata)

print(mydata.__iter__().get_next()[0].shape)
print(mydata.__iter__().get_next()[1].shape)
```

the output are 

```python
2022-05-30 20:07:03,886 INFO services.py:1478 -- View the Ray dashboard at http://127.0.0.1:8266
2022-05-30 20:07:07,322 WARNING read_api.py:252 -- The number of blocks in this dataset (1) limits its parallelism to 1 concurrent tasks. This is much less than the number of available CPU slots in the cluster. Use `.repartition(n)` to increase the number of dataset blocks.
(_prepare_read pid=44484) 2022-05-30 20:07:07,318       WARNING tensorflow_datasource.py:53 -- `SimpleTensorFlowDatasource` doesn't support parallel reads. The `parallelism` argument will be ignored.
(_execute_read_task pid=44484) 2022-05-30 20:07:07.490737: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-05-30 20:07:07,743 WARNING read_api.py:252 -- The number of blocks in this dataset (1) limits its parallelism to 1 concurrent tasks. This is much less than the number of available CPU slots in the cluster. Use `.repartition(n)` to increase the number of dataset blocks.
Read->Map_Batches:   0%|                                                                                                                                              | 0/1 [00:00<?, ?it/s](_prepare_read pid=44484) 2022-05-30 20:07:07,740       WARNING tensorflow_datasource.py:53 -- `SimpleTensorFlowDatasource` doesn't support parallel reads. The `parallelism` argument will be ignored.
Read->Map_Batches: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.53it/s]
Read->Map_Batches: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.03it/s]
<FlatMapDataset element_spec=(TensorSpec(shape=(None, 784), dtype=tf.float32, name=None), TensorSpec(shape=(None, 784), dtype=tf.float32, name=None))>
(2, 1, 784) (2,)
Traceback (most recent call last):
  File "temp_test.py", line 252, in <module>
    print(mydata.__iter__().get_next()[0].shape)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 819, in get_next
    return self._next_internal()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 749, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3017, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 7164, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.UnknownError: SystemExit: None
Traceback (most recent call last):

  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 270, in __call__
    ret = func(*args)

  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1030, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/data/dataset.py", line 2555, in make_generator
    exit()

  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)

SystemExit: None


         [[{{node PyFunc}}]] [Op:IteratorGetNext]
```

**Comment by JiahaoYao** [comment]
If I hard code the `to_tf` method, I can get the right shape


```python
import ray
import tensorflow as tf 
import tensorflow_datasets as tfds
import pandas as pd
from ray.data.datasource import SimpleTensorFlowDatasource
import numpy as np
from typing import (
    List,
    Any,
    Callable,
    Iterator,
    Iterable,
    Generic,
    Dict,
    Optional,
    Union,
    TYPE_CHECKING,
    Tuple,
)
TensorflowFeatureTypeSpec = Union[
    "tf.TypeSpec", List["tf.TypeSpec"], Dict[str, "tf.TypeSpec"]
]

def _to_tf(
    self,
    *,
    output_signature: Union[
        TensorflowFeatureTypeSpec, Tuple[TensorflowFeatureTypeSpec, "tf.TypeSpec"]
    ],
    label_column: Optional[str] = None,
    feature_columns: Optional[
        Union[List[str], List[List[str]], Dict[str, List[str]]]
    ] = None,
    prefetch_blocks: int = 0,
    batch_size: int = 1,
    unsqueeze_label_tensor=True,
    drop_last: bool = False,
) -> "tf.data.Dataset":
    """Return a TF Dataset over this dataset.

    The TF Dataset will be created from the generator returned by the
    ``iter_batches`` method. ``prefetch_blocks`` and ``batch_size``
    arguments will be passed to that method.

    For the features tensor (N is the ``batch_size`` and n1, ..., nk
    are the number of features per tensor):

    * If ``feature_columns`` is a ``List[str]``, the features will be
        a tensor of shape (N, n), with columns corresponding to
        ``feature_columns``

    * If ``feature_columns`` is a ``List[List[str]]``, the features will be
        a list of tensors of shape [(N, n1),...,(N, nk)], with columns of each
        tensor corresponding to the elements of ``feature_columns``

    * If ``feature_columns`` is a ``Dict[str, List[str]]``, the features
        will be a dict of key-tensor pairs of shape
        {key1: (N, n1),..., keyN: (N, nk)}, with columns of each
        tensor corresponding to the value of ``feature_columns`` under the
        key.

    This is only supported for datasets convertible to Arrow records.

    Requires all datasets to have the same columns.

    It is recommended to call ``.split()`` on this dataset if
    there are to be multiple TensorFlow workers consuming the data.

    The elements generated must be compatible with the given
    ``output_signature`` argument (same as in
    ``tf.data.Dataset.from_generator``).

    Time complexity: O(1)

    Args:
        output_signature (Union[TensorflowFeatureTypeSpec, \
Tuple[TensorflowFeatureTypeSpec, "tf.TypeSpec"]]): If ``label_column`` is specified,
            a two-element tuple containing a ``FeatureTypeSpec`` and
            ``tf.TypeSpec`` object corresponding to (features, label). Otherwise, a
            single ``TensorflowFeatureTypeSpec`` corresponding to features tensor.
            A ``TensorflowFeatureTypeSpec`` is a ``tf.TypeSpec``,
            ``List["tf.TypeSpec"]``, or ``Dict[str, "tf.TypeSpec"]``.
        label_column (Optional[str]): The name of the column used as the label
            (second element of the output tuple). If not specified, output
            will be just one tensor instead of a tuple.
        feature_columns (Optional[Union[List[str], List[List[str]], Dict[str, \
List[str]]]): The names of the columns to use as the features. Can be a list of lists
            or a dict of string-list pairs for multi-tensor output. If None, then
            use all columns except the label columns as the features.
        prefetch_blocks: The number of blocks to prefetch ahead of the
            current block during the scan.
        batch_size: Record batch size. Defaults to 1.
        drop_last (bool): Set to True to drop the last incomplete batch,
            if the dataset size is not divisible by the batch size. If
            False and the size of dataset is not divisible by the batch
            size, then the last batch will be smaller. Defaults to False.

    Returns:
        A tf.data.Dataset.
    """

    # argument exception checking is done in from_generator

    try:
        import tensorflow as tf
    except ImportError:
        raise ValueError("tensorflow must be installed!")

    # `output_signature` can be a tuple but not a list. See
    # https://stackoverflow.com/questions/59092423/what-is-a-nested-structure-in-tensorflow.
    if isinstance(output_signature, list):
        output_signature = tuple(output_signature)

    def get_df_values(df: "pandas.DataFrame") -> np.ndarray:
        # TODO(Clark): Support unsqueezing column dimension API, similar to
        # to_torch().
        # values = df.values

        # print(values, values.shape)
        # exit()
        # print(values2, values2.shape)
        # import ipdb; ipdb.set_trace()
        try:
            
            values = df.values
            
            values = np.stack(values)

        #     print(values, values.shape)
        except ValueError as e:
            import pandas as pd

            # Pandas DataFrame.values doesn't support extension arrays in all
            # supported Pandas versions, so we check to see if this DataFrame
            # contains any extensions arrays and do a manual conversion if so.
            # See https://github.com/pandas-dev/pandas/pull/43160.
            if any(
                isinstance(dtype, pd.api.extensions.ExtensionDtype)
                for dtype in df.dtypes
            ):
                values = np.stack([col.to_numpy() for _, col in df.items()], axis=1)
                # print('ah ha')
                # print(values, values.shape)
            else:
                raise e from None
        return values

    def make_generator():
        for batch in self.iter_batches(
            prefetch_blocks=prefetch_blocks,
            batch_size=batch_size,
            batch_format="pandas",
            drop_last=drop_last,
        ):
            # print(batch)
            # exit()
            if label_column:
                # targets = batch.pop(label_column).values
                targets = get_df_values(batch[label_column])

            features = None
            if feature_columns is None:
                features = get_df_values(batch)
    

            elif isinstance(feature_columns, list):
                if all(isinstance(column, str) for column in feature_columns):
                    # print(batch)
                    # import ipdb; ipdb.set_trace()
                    # print('catch u')
                    # exit()
                    # print(feature_columns)
                    if len(feature_columns) == 1: 
                        features = get_df_values(batch[feature_columns[0]])
                    else: 
                        features = get_df_values(batch[feature_columns])
                    # print(features, features.shape, features[0][0].shape)
                    # print('hello')
                    # exit()
                elif all(isinstance(columns, list) for columns in feature_columns):
                    features = tuple(
                        get_df_values(batch[columns]) for columns in feature_columns
                    )
                else:
                    raise ValueError(
                        "Expected `feature_columns` to be a list of strings or a "
                        "list of lists."
                    )
    
            elif isinstance(feature_columns, dict):
                features = {
                    key: get_df_values(batch[columns])
                    for key, columns in feature_columns.items()
                }
            else:
                raise ValueError(
                    "Expected `feature_columns` to be a list or a dictionary, "
                    f"but got a `{type(feature_columns).__name__}` instead."
                )

            if label_column:
                yield features, targets
            else:
                yield features

    dataset = tf.data.Dataset.from_generator(
        make_generator, output_signature=output_signature
    )

    return dataset

    #     return dataset

ray.data.Dataset.to_tf = _to_tf

from ray.data.extensions import TensorArray


def train_dataset_factory():
    return tfds.load("mnist", split=["train"], as_supervised=True)[0].take(10)

def test_dataset_factory():
    return tfds.load("mnist", split=["test"], as_supervised=True)[0].take(10)

train_dataset = ray.data.read_datasource(  
    SimpleTensorFlowDatasource(), dataset_factory=train_dataset_factory
)
test_dataset = ray.data.read_datasource(SimpleTensorFlowDatasource(), dataset_factory=test_dataset_factory)


def convert_batch_to_pandas(batch):
    images = TensorArray([tf.reshape(image, (-1)) for image, _ in batch])
    df = pd.DataFrame({"image": images, "label": images})
    return df
    
train_dataset = train_dataset.map_batches(convert_batch_to_pandas)
test_dataset = test_dataset.map_batches(convert_batch_to_pandas)


mydata = train_dataset.to_tf(
            feature_columns=["image"],
            label_column="label",
            output_signature=(
                tf.TensorSpec(shape=(None, 784), dtype=tf.float32),
                tf.TensorSpec(shape=(None, 784), dtype=tf.float32),
            ),
            batch_size=2,
        )

print(mydata)

print(mydata.__iter__().get_next()[0].shape)
print(mydata.__iter__().get_next()[1].shape)
```


the outputs are 

```python
Read->Map_Batches: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.42it/s]
Read->Map_Batches: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.17it/s]
<FlatMapDataset element_spec=(TensorSpec(shape=(None, 784), dtype=tf.float32, name=None), TensorSpec(shape=(None, 784), dtype=tf.float32, name=None))>
(2, 784)
(2, 784)
```

**Comment by JiahaoYao** [comment]
In summary, my previous issue is that
1. the input is `(#batch, 1, 784)` which could be `(#batch, 784)`. 

_solution_ may be
- when the feature lists is of length one, input the `feature_list[0]` instead of `feature_list`. Also, stack the items in order to form a `ndarray`. 

2. the output is treated as the scalars, so that the shape was `(#batch, )`. However, in order to support the `ndarray` for the output, we might also need to use some procedure of input process for the output. 

@amogkam @bveeramani @xwjiang2010

**Comment by bveeramani** [comment]
@JiahaoYao is this related to #25135?

**Comment by JiahaoYao** [comment]
This will be closed once https://github.com/ray-project/ray/pull/25563 get approved.

**Comment by clarkzinzow** [comment]
@JiahaoYao Is this still waiting for #25563? If so, can we not close it until that's merged?
