### ISSUE TITLE
question about carla example documentation

### ISSUE THREAD

**Issue by scotthuang1989** [ray-project/ray#2507]
In readme.md of carla example, on of the setup steps requires carla source code:

> Note that currently you also need to clone the Python code from `carla/benchmark_branch` which includes the Carla planner.

What does `carla/benchmark_branch` mean? I check the carla repo, I don't find benchmark branch, the closest one is `benchmark_upgrades`, because I am having trouble running the example, So I am checking every step of setup.

**Comment by ericl** [comment]
I believe that branch is merged into master now, so you don't need that branch.

**Comment by scotthuang1989** [comment]
so, I should use the latest version of carla: 0.8.4?

the step should be like this: 

    $ pkill -9 Carla
    $ export CARLA_SERVER=/PATH/TO/CARLA_0.7.0/CarlaUE4.sh
    $ python env.py

**Comment by scotthuang1989** [comment]
0.8.4 is working. although I don't see the policy is improving, I suppose that will take some time.

**Comment by ericl** [comment]
Yeah, it takes a few hundred k timesteps, and I've only seen it learn
reasonably when using the discretized action space.

**Comment by Deepak3994** [comment]
> 0.8.4 is working. although I don't see the policy is improving, I suppose that will take some time.

@scotthuang1989 

I have setup the ray cluster by running "ray up" for aws. But when i run the train_ppo.py example for carla, i am getting the below error,

**WARNING:** Not monitoring node memory since `psutil` is not installed. Install this with `pip install psutil` (or ray[debug]) to enable debugging of memory-related crashes.
172.31.47.162:6379
2019-02-13 08:51:29,859	WARNING worker.py:1354 -- WARNING: Not updating worker name since `setproctitle` is not installed. Install this with `pip install setproctitle` (or ray[debug]) to enable monitoring of worker processes.
2019-02-13 08:51:29,875	INFO tune.py:135 -- Tip: to resume incomplete experiments, pass resume='prompt' or resume=True to run_experiments()
2019-02-13 08:51:29,875	INFO tune.py:145 -- Starting a new experiment.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/20 CPUs, 0/5 GPUs
Unknown memory usage. Please run `pip install psutil` (or ray[debug]) to resolve)

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 5/20 CPUs, 4/5 GPUs
Unknown memory usage. Please run `pip install psutil` (or ray[debug]) to resolve)
Result logdir: /home/ubuntu/ray_results/carla-a3c
PENDING trials:
 - A3C_CarlaEnv_1_reward_function=corl2017,squash_action_logits=False:	PENDING
 - A3C_CarlaEnv_2_reward_function=custom,squash_action_logits=True:	PENDING
 - A3C_CarlaEnv_3_reward_function=corl2017,squash_action_logits=True:	PENDING
RUNNING trials:
 - A3C_CarlaEnv_0_reward_function=custom,squash_action_logits=False:	RUNNING

2019-02-13 08:51:34,985	ERROR trial_runner.py:413 -- Error processing event.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 378, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 228, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/worker.py", line 2132, in get
    raise value
**ray.worker.RayTaskError: ray_worker (pid=4731, host=ip-172-31-34-62)**
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/utils.py", line 452, in _wrapper
    return orig_attr(*args, **kwargs)
  File "pyarrow/_plasma.pyx", line 531, in pyarrow._plasma.PlasmaClient.get
  File "pyarrow/serialization.pxi", line 448, in pyarrow.lib.deserialize
  File "pyarrow/serialization.pxi", line 411, in pyarrow.lib.deserialize_from
  File "pyarrow/serialization.pxi", line 262, in pyarrow.lib.SerializedPyObject.deserialize
  File "pyarrow/serialization.pxi", line 171, in pyarrow.lib.SerializationContext._deserialize_callback
**ModuleNotFoundError: No module named 'env'**

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/20 CPUs, 0/5 GPUs
Unknown memory usage. Please run `pip install psutil` (or ray[debug]) to resolve)
Result logdir: /home/ubuntu/ray_results/carla-a3c
ERROR trials:
 - A3C_CarlaEnv_0_reward_function=custom,squash_action_logits=False:	ERROR, 1 failures: /home/ubuntu/ray_results/carla-a3c/A3C_CarlaEnv_0_reward_function=custom,squash_action_logits=False_2019-02-13_08-51-29rw2wkz1g/error_2019-02-13_08-51-34.txt
PENDING trials:
 - A3C_CarlaEnv_1_reward_function=corl2017,squash_action_logits=False:	PENDING
 - A3C_CarlaEnv_2_reward_function=custom,squash_action_logits=True:	PENDING
 - A3C_CarlaEnv_3_reward_function=corl2017,squash_action_logits=True:	PENDING

2019-02-13 08:51:40,090	ERROR trial_runner.py:413 -- Error processing event.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 378, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 228, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/worker.py", line 2132, in get
    raise value
**ray.worker.RayTaskError: ray_worker (pid=3071, host=ip-172-31-37-224)**
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/utils.py", line 452, in _wrapper
    return orig_attr(*args, **kwargs)
  File "pyarrow/_plasma.pyx", line 531, in pyarrow._plasma.PlasmaClient.get
  File "pyarrow/serialization.pxi", line 448, in pyarrow.lib.deserialize
  File "pyarrow/serialization.pxi", line 411, in pyarrow.lib.deserialize_from
  File "pyarrow/serialization.pxi", line 262, in pyarrow.lib.SerializedPyObject.deserialize
  File "pyarrow/serialization.pxi", line 171, in pyarrow.lib.SerializationContext._deserialize_callback
**ModuleNotFoundError: No module named 'env'**

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/20 CPUs, 0/5 GPUs
Unknown memory usage. Please run `pip install psutil` (or ray[debug]) to resolve)
Result logdir: /home/ubuntu/ray_results/carla-a3c
ERROR trials:
 - A3C_CarlaEnv_0_reward_function=custom,squash_action_logits=False:	ERROR, 1 failures: /home/ubuntu/ray_results/carla-a3c/A3C_CarlaEnv_0_reward_function=custom,squash_action_logits=False_2019-02-13_08-51-29rw2wkz1g/error_2019-02-13_08-51-34.txt
 - A3C_CarlaEnv_1_reward_function=corl2017,squash_action_logits=False:	ERROR, 1 failures: /home/ubuntu/ray_results/carla-a3c/A3C_CarlaEnv_1_reward_function=corl2017,squash_action_logits=False_2019-02-13_08-51-35a8env_s3/error_2019-02-13_08-51-40.txt
PENDING trials:
 - A3C_CarlaEnv_2_reward_function=custom,squash_action_logits=True:	PENDING
 - A3C_CarlaEnv_3_reward_function=corl2017,squash_action_logits=True:	PENDING

2019-02-13 08:51:45,133	ERROR trial_runner.py:413 -- Error processing event.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 378, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 228, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/worker.py", line 2132, in get
    raise value
**ray.worker.RayTaskError: ray_worker (pid=3302, host=ip-172-31-45-85)**
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ray/utils.py", line 452, in _wrapper
    return orig_attr(*args, **kwargs)
  File "pyarrow/_plasma.pyx", line 531, in pyarrow._plasma.PlasmaClient.get
  File "pyarrow/serialization.pxi", line 448, in pyarrow.lib.deserialize
  File "pyarrow/serialization.pxi", line 411, in pyarrow.lib.deserialize_from
  File "pyarrow/serialization.pxi", line 262, in pyarrow.lib.SerializedPyObject.deserialize
  File "pyarrow/serialization.pxi", line 171, in pyarrow.lib.SerializationContext._deserialize_callback
**ModuleNotFoundError: No module named 'env'**

**"ModuleNotFoundError: No module named 'env'"** this ModuleNotFoundError i am getting from worker nodes and in the head node it is running fine.

I wanted to know like the exact procedures to setup the ray cluster, how head and node communicates and why i am getting this error only on worker nodes.

I am using carla 0.8.4, is there any changes we need to do for it, to go running?

Kindly help..
