### ISSUE TITLE
[rllib] MultiAgentBatch bug

### ISSUE THREAD

**Issue by Scitator** [ray-project/ray#2510]
Hi,

Looks like, something strange happens with AsyncSampleOptimizer after [this commit](https://github.com/ray-project/ray/commit/24649726dcbad87b4f72e6dd665fd5916f69fd26):
```
Remote function add_batch failed with:

Traceback (most recent call last):
  File "/home/scitator/Documents/git/ray/python/ray/worker.py", line 935, in _process_task
    *arguments)
  File "/home/scitator/Documents/git/ray/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/scitator/Documents/git/ray/python/ray/rllib/optimizers/async_samples_optimizer.py", line 61, in add_batch
    PolicyOptimizer._check_not_multiagent(batch)
  File "/home/scitator/Documents/git/ray/python/ray/rllib/optimizers/policy_optimizer.py", line 128, in _check_not_multiagent
    "This optimizer does not support multi-agent yet.")
NotImplementedError: This optimizer does not support multi-agent yet.
```
and many
```
Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.
```
after that.

Nevertheless, I use typical ApexDDPG without any MultiAgents. And looks like training continues.

**Comment by ericl** [comment]
Do you have a simple example to reproduce? This doesn't happen for me for

```
./train.py \
    --env Pendulum-v0 \
    --run APEX_DDPG \
    --ray-num-cpus 8 \
    --stop '{"training_iteration": 2}' \
    --config '{"num_workers": 2, "optimizer": {"num_replay_buffer_shards": 1}, "learning_starts": 100}'
```
