### ISSUE TITLE
Ray core, ray client occasional deadlock

### ISSUE THREAD

**Issue by marsupialtail** [ray-project/ray#25115]
### What happened + What you expected to happen

Ray client sometimes deadlocks and hangs. Unfortunately I cannot give a self-consistent example to reproduce as it's too complicated. However a stack trace when I call ^C can be shown here:
^CException ignored in: <function ClientObjectRef.__del__ at 0x7feabcbf4700>
Traceback (most recent call last):
  File "/home/ziheng/.local/lib/python3.8/site-packages/ray/util/client/common.py", line 110, in __del__
    self._worker.call_release(self.id)
  File "/home/ziheng/.local/lib/python3.8/site-packages/ray/util/client/worker.py", line 622, in call_release
    self._release_server(id)
  File "/home/ziheng/.local/lib/python3.8/site-packages/ray/util/client/worker.py", line 628, in _release_server
    self.data_client.ReleaseObject(ray_client_pb2.ReleaseRequest(ids=[id]))
  File "/home/ziheng/.local/lib/python3.8/site-packages/ray/util/client/dataclient.py", line 531, in ReleaseObject
    self._async_send(datareq)
  File "/home/ziheng/.local/lib/python3.8/site-packages/ray/util/client/dataclient.py", line 426, in _async_send
    with self.lock:

What makes me think it's a problem with Ray client deadlock is that this problem only occurs sometimes, and quite infrequently. 

### Versions / Dependencies

Ray 1.12.0

### Reproduction script

Sorry can't provide one

### Issue Severity

High: It blocks me from completing my task.

**Comment by mwtian** [comment]
Hi @marsupialtail, what is the version of Python you are using?

**Comment by marsupialtail** [comment]
3.8
