### ISSUE TITLE
[AIR] [Datasets] `Dataset.to_tf` adds extra axis to data

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#25135]
### What happened + What you expected to happen

```
Traceback (most recent call last):

  File "/Users/balaji/GitHub/ray/.venv/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 270, in __call__
    ret = func(*args)

  File "/Users/balaji/GitHub/ray/.venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/Users/balaji/GitHub/ray/.venv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1073, in generator_py_func
    raise TypeError(

TypeError: `generator` yielded an element of shape (2, 1, 32, 32, 3) where an element of shape (None, 32, 32, 3) was expected.


Traceback (most recent call last):
  File "python/ray/ml/predictors/integrations/tensorflow/temp.py", line 39, in <module>
    next(iter(tensorflow_dataset))
  File "/Users/balaji/GitHub/ray/.venv/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 766, in __next__
    return self._next_internal()
  File "/Users/balaji/GitHub/ray/.venv/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 749, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/Users/balaji/GitHub/ray/.venv/lib/python3.8/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3017, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/Users/balaji/GitHub/ray/.venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 7164, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: TypeError: `generator` yielded an element of shape (2, 1, 32, 32, 3) where an element of shape (None, 32, 32, 3) was expected.
Traceback (most recent call last):

  File "/Users/balaji/GitHub/ray/.venv/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 270, in __call__
    ret = func(*args)

  File "/Users/balaji/GitHub/ray/.venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/Users/balaji/GitHub/ray/.venv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1073, in generator_py_func
    raise TypeError(

TypeError: `generator` yielded an element of shape (2, 1, 32, 32, 3) where an element of shape (None, 32, 32, 3) was expected.


         [[{{node PyFunc}}]] [Op:IteratorGetNext]
2022-05-24 01:52:20.334883: W tensorflow/core/kernels/data/generator_dataset_op.cc:108] Error occurred when finalizing GeneratorDataset iterator: FAILED_PRECONDITION: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]
```

### Versions / Dependencies

**Ray**: da5cf93d976ae03d6090a4d4249adf46818d30eb
**Python**: 3.8.12
**OS**: MacOS

### Reproduction script

```
import ray
from ray.data.datasource import SimpleTensorFlowDatasource
import tensorflow as tf
import tensorflow_datasets as tfds


def tensorflow_dataset_factory():
    return tfds.load("cifar10", split=["train"], as_supervised=True)[0]


ray_dataset = ray.data.read_datasource(
    SimpleTensorFlowDatasource(), dataset_factory=tensorflow_dataset_factory
)


import pandas as pd
from ray.data.extensions import TensorArray


def convert_batch_to_pandas(batch):
    images = TensorArray([image.numpy() for image, _ in batch])
    labels = [label.numpy() for _, label in batch]
    df = pd.DataFrame({"image": images, "label": labels})
    return df


ray_dataset = ray_dataset.map_batches(convert_batch_to_pandas)

tensorflow_dataset = ray_dataset.to_tf(
    feature_columns=["image"],
    label_column="label",
    output_signature=(
        tf.TensorSpec(shape=(None, 32, 32, 3), dtype=tf.float32),
        tf.TensorSpec(shape=(None), dtype=tf.uint8),
    ),
    batch_size=2,
)

next(iter(tensorflow_dataset))
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by clarkzinzow** [comment]
IMO we should "unsqueeze" the column dimension by default, removing redundant column axes for the single-column case.

**Comment by clarkzinzow** [comment]
It's the example you gave in this issue: a single column of one or more `(32, 32, 3)` tensor element batches is expected, but when yielding a 2-element batch, a `(2, 1, 32, 32, 3)` tensor is yielded instead of `(2, 32, 32, 3)`, as expected, since `.to_tf()` is adding a redundant column dimension. I'm saying that this column dimension should be squeezed (i.e. removed) by default in the single-column case, since that should better match the user's expectation.

**Comment by bveeramani** [comment]
> It's the example you gave in this issue: a single column of one or more `(32, 32, 3)` tensor element batches is desired, but when yielding a 2-element batch, a `(2, 1, 32, 32, 3)` tensor is yielded instead of the expected `(2, 32, 32, 3)`, since `.to_tf()` is adding a redundant column dimension. I'm saying that this column dimension should be squeezed (i.e. removed) by default in the single-column case, since that should better match the user's expectation.

Oh, yeah. 100% agree. Although, it's not so much that we're squeezing the tensor but rather we're not unsqueezing it.
