### ISSUE TITLE
[AIR] `[Error 9] Bad file descriptor` after running `TensorflowTrainer.fit`

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#25142]
### What happened + What you expected to happen

I'm training a TensorFlow image classifier. After `fit` is done, I get an unusual error:

```
(BaseWorkerMixin pid=9064) Exception ignored in: <function Pool.__del__ at 0x1be0200d0>
(BaseWorkerMixin pid=9064) Traceback (most recent call last):
(BaseWorkerMixin pid=9064)   File "/Users/balaji/.pyenv/versions/3.8.12/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
(BaseWorkerMixin pid=9064)     self._change_notifier.put(None)
(BaseWorkerMixin pid=9064)   File "/Users/balaji/.pyenv/versions/3.8.12/lib/python3.8/multiprocessing/queues.py", line 368, in put
(BaseWorkerMixin pid=9064)     self._writer.send_bytes(obj)
(BaseWorkerMixin pid=9064)   File "/Users/balaji/.pyenv/versions/3.8.12/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
(BaseWorkerMixin pid=9064)     self._send_bytes(m[offset:offset + size])
(BaseWorkerMixin pid=9064)   File "/Users/balaji/.pyenv/versions/3.8.12/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
(BaseWorkerMixin pid=9064)     self._send(header + buf)
(BaseWorkerMixin pid=9064)   File "/Users/balaji/.pyenv/versions/3.8.12/lib/python3.8/multiprocessing/connection.py", line 368, in _send
(BaseWorkerMixin pid=9064)     n = write(self._handle, buf)
(BaseWorkerMixin pid=9064) OSError: [Errno 9] Bad file descriptor
(BaseWorkerMixin pid=9064) Exception ignored in: <function Pool.__del__ at 0x1be0200d0>
(BaseWorkerMixin pid=9064) Traceback (most recent call last):
(BaseWorkerMixin pid=9064)   File "/Users/balaji/.pyenv/versions/3.8.12/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
(BaseWorkerMixin pid=9064)     self._change_notifier.put(None)
(BaseWorkerMixin pid=9064)   File "/Users/balaji/.pyenv/versions/3.8.12/lib/python3.8/multiprocessing/queues.py", line 368, in put
(BaseWorkerMixin pid=9064)     self._writer.send_bytes(obj)
(BaseWorkerMixin pid=9064)   File "/Users/balaji/.pyenv/versions/3.8.12/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
(BaseWorkerMixin pid=9064)     self._send_bytes(m[offset:offset + size])
(BaseWorkerMixin pid=9064)   File "/Users/balaji/.pyenv/versions/3.8.12/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
(BaseWorkerMixin pid=9064)     self._send(header + buf)
(BaseWorkerMixin pid=9064)   File "/Users/balaji/.pyenv/versions/3.8.12/lib/python3.8/multiprocessing/connection.py", line 368, in _send
...
(BaseWorkerMixin pid=9065)     self._send(header + buf)
(BaseWorkerMixin pid=9065)   File "/Users/balaji/.pyenv/versions/3.8.12/lib/python3.8/multiprocessing/connection.py", line 368, in _send
(BaseWorkerMixin pid=9065)     n = write(self._handle, buf)
(BaseWorkerMixin pid=9065) OSError: [Errno 9] Bad file descriptor
```

I'm using a Jupyter notebook. Not sure if that's at all related.

Note that this doesn't actually impact the training. The checkpoint still works correctly (I think).

### Versions / Dependencies

**TensorFlow**: 2.9.1
**Ray**: https://github.com/ray-project/ray/commit/5e4225237e0806e3300381b4f8f39494c67e2906
**Jupyter**:
```
IPython          : 7.30.1
ipykernel        : 6.6.0
ipywidgets       : 7.6.5
jupyter_client   : 7.1.0
jupyter_core     : 4.9.1
jupyter_server   : not installed
jupyterlab       : not installed
nbclient         : 0.5.9
nbconvert        : 6.3.0
nbformat         : 5.1.3
notebook         : 6.4.6
qtconsole        : 5.2.2
traitlets        : 5.1.1
```
**OS**: MacOS

### Reproduction script

Run the example in #24633.

### Issue Severity

Low: It annoys or frustrates me.

**Comment by nakamasato** [comment]
I also encountered the same issue.

versions:
- Python: 3.9.0
- Ray: 1.13.0

script:

```python
import argparse
import json
import os

import numpy as np
import ray
import tensorflow as tf
from ray import train
from ray.train import Trainer
from tensorflow.keras.callbacks import Callback


class TrainReportCallback(Callback):
    def on_epoch_end(self, epoch, logs=None):
        train.report(**logs)


def mnist_dataset(batch_size):
    (x_train, y_train), _ = tf.keras.datasets.mnist.load_data()
    # The `x` arrays are in uint8 and have values in the [0, 255] range.
    # You need to convert them to float32 with values in the [0, 1] range.
    x_train = x_train / np.float32(255)
    y_train = y_train.astype(np.int64)
    train_dataset = tf.data.Dataset.from_tensor_slices(
        (x_train, y_train)).shuffle(60000).repeat().batch(batch_size)
    return train_dataset


def build_and_compile_cnn_model(config):
    learning_rate = config.get("lr", 0.001)
    model = tf.keras.Sequential([
        tf.keras.layers.InputLayer(input_shape=(28, 28)),
        tf.keras.layers.Reshape(target_shape=(28, 28, 1)),
        tf.keras.layers.Conv2D(32, 3, activation='relu'),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(10)
    ])
    model.compile(
        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        optimizer=tf.keras.optimizers.SGD(learning_rate=learning_rate),
        metrics=['accuracy'])
    return model


def train_func(config):

    per_worker_batch_size = config.get("batch_size", 64)
    epochs = config.get("epochs", 3)
    steps_per_epoch = config.get("steps_per_epoch", 70)

    tf_config = json.loads(os.environ["TF_CONFIG"])
    num_workers = len(tf_config["cluster"]["worker"])

    strategy = tf.distribute.MultiWorkerMirroredStrategy()

    global_batch_size = per_worker_batch_size * num_workers
    multi_worker_dataset = mnist_dataset(global_batch_size)

    with strategy.scope():
        multi_worker_model = build_and_compile_cnn_model(config)

    history = multi_worker_model.fit(
        multi_worker_dataset,
        epochs=epochs,
        steps_per_epoch=steps_per_epoch,
        callbacks=[TrainReportCallback()],
    )
    results = history.history
    return results


def train_tensorflow_mnist(num_workers=2, use_gpu=False, epochs=4):
    trainer = Trainer(backend="tensorflow", num_workers=num_workers, use_gpu=use_gpu)

    trainer.start()  # set up resources
    results = trainer.run(
        train_func=train_func,
        config={"lr": 1e-3, "batch_size": 64, "epochs": epochs}
    )
    trainer.shutdown()  # clean up resources
    print(f"Results: {results[0]}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--address", required=False, default="auto", type=str, help="the address to use for Ray"
    )
    parser.add_argument(
        "--num-workers",
        "-n",
        type=int,
        default=2,
        help="Sets number of workers for training.",
    )
    parser.add_argument(
        "--use-gpu", action="store_true", default=False, help="Enables GPU training"
    )
    parser.add_argument(
        "--epochs", type=int, default=3, help="Number of epochs to train for."
    )
    parser.add_argument(
        "--smoke-test",
        action="store_true",
        default=False,
        help="Finish quickly for testing.",
    )

    args, _ = parser.parse_known_args()

    if args.smoke_test:
        ray.init(num_cpus=2)
        train_tensorflow_mnist()
    else:
        ray.init(address=args.address)
        train_tensorflow_mnist(
            num_workers=args.num_workers, use_gpu=args.use_gpu, epochs=args.epochs
        )
```

command:
```
python tensorflow_example.py --smoke-test
```

error:

```
...
68/70 [============================>.] - ETA: 0s - loss: 2.0349 - accuracy: 0.6606
69/70 [============================>.] - ETA: 0s - loss: 2.0338 - accuracy: 0.6613
69/70 [============================>.] - ETA: 0s - loss: 2.0338 - accuracy: 0.6613
70/70 [==============================] - 13s 180ms/step - loss: 2.0332 - accuracy: 0.6622
70/70 [==============================] - 13s 180ms/step - loss: 2.0332 - accuracy: 0.6622
Results: {'loss': [2.2794315814971924, 2.208983898162842, 2.12907075881958, 2.033207416534424], 'accuracy': [0.16718749701976776, 0.3973214328289032, 0.5854910612106323, 0.6621651649475098]}
(BaseWorkerMixin pid=15402) /Users/nakamasato/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 4 leaked semaphore objects to clean up at shutdown
(BaseWorkerMixin pid=15402)   warnings.warn('resource_tracker: There appear to be %d '
(BaseWorkerMixin pid=15403) Exception ignored in: <function Pool.__del__ at 0x19806d820>
(BaseWorkerMixin pid=15403) Traceback (most recent call last):
(BaseWorkerMixin pid=15403)   File "/Users/nakamasato/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/pool.py", line 268, in __del__
(BaseWorkerMixin pid=15403)     self._change_notifier.put(None)
(BaseWorkerMixin pid=15403)   File "/Users/nakamasato/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/queues.py", line 378, in put
(BaseWorkerMixin pid=15403)     self._writer.send_bytes(obj)
(BaseWorkerMixin pid=15403)   File "/Users/nakamasato/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
(BaseWorkerMixin pid=15403)     self._send_bytes(m[offset:offset + size])
(BaseWorkerMixin pid=15403)   File "/Users/nakamasato/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
(BaseWorkerMixin pid=15403)     self._send(header + buf)
(BaseWorkerMixin pid=15403)   File "/Users/nakamasato/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/connection.py", line 373, in _send
(BaseWorkerMixin pid=15403)     n = write(self._handle, buf)
(BaseWorkerMixin pid=15403) OSError: [Errno 9] Bad file descriptor
(BaseWorkerMixin pid=15403) Exception ignored in: <function Pool.__del__ at 0x19806d820>
(BaseWorkerMixin pid=15403) Traceback (most recent call last):
(BaseWorkerMixin pid=15403)   File "/Users/nakamasato/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/pool.py", line 268, in __del__
(BaseWorkerMixin pid=15403)     self._change_notifier.put(None)
(BaseWorkerMixin pid=15403)   File "/Users/nakamasato/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/queues.py", line 378, in put
(BaseWorkerMixin pid=15403)     self._writer.send_bytes(obj)
(BaseWorkerMixin pid=15403)   File "/Users/nakamasato/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
(BaseWorkerMixin pid=15403)     self._send_bytes(m[offset:offset + size])
(BaseWorkerMixin pid=15403)   File "/Users/nakamasato/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
(BaseWorkerMixin pid=15403)     self._send(header + buf)
(BaseWorkerMixin pid=15403)   File "/Users/nakamasato/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/connection.py", line 373, in _send
(BaseWorkerMixin pid=15403)     n = write(self._handle, buf)
(BaseWorkerMixin pid=15403) OSError: [Errno 9] Bad file descriptor
```

this seems to be related to https://github.com/tensorflow/tensorflow/issues/50487

**Comment by mattip** [comment]
The upstream issue will be fixed in the 2.10 release of tensorflow.

**Comment by davidxia** [comment]
2.10 is available now. Just curious if any plans to upgrade tensorflow to ≥2.10?

**Comment by xwjiang2010** [comment]
Still happening in ray air  get started example (tensorflow) from @scottsun94

**Comment by scottsun94** [comment]
Yeah. I ran the AIR get started example with tf 2.9 and encountered this. It works fine on 2.10 and 2.11.

**Comment by davidxia** [comment]
Looks like the following container images have tensorflow 2.11.0 as of the 2.4.0 release. Wonder if this issue is now fixed on recent images?

```
docker run -it --entrypoint bash rayproject/ray-ml:2.4.0-py38-gpu
ray@8b91ce24127d:~$ pip freeze | grep tensorflow
tensorflow==2.11.0

docker run -it --entrypoint bash rayproject/ray-ml:2.4.0-py39-gpu
ray@c4b9293d7b11:~$ pip freeze | grep tensorflow
tensorflow==2.11.0
```
