### ISSUE TITLE
Non-deterministic module imports

### ISSUE THREAD

**Issue by ICGog** [ray-project/ray#2515]
### System information
- **OS Platform and Distribution**: Ubuntu 16.04
- **Ray installed from (source or binary)**: master branch
- **Ray version**: 0.5.0
- **Python version**: 2.7.12

### Describe the problem
Ray runs with different sys.path on workers. I have a python script which updates sys.path before it inits Ray. However, the updated sys.path is not correctly passed to ray workers, and thus pickle fails with no module named.

```
Traceback (most recent call last):
  File "/home/icg27/code/ray/python/ray/import_thread.py", line 173, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/usr/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1130, in find_class
    __import__(module)
ImportError: No module named sos.ros.ros_publisher_op
```
I instrumented import_thread.py to print sys.path, and noticed that sometimes sys.path includes the paths I've added, and sometimes it doesn't (see below). Do you know what might be the cause of this issue?

### Source code / logs
```
Sys.path ['/home/icg27/code/ray/python/ray/pyarrow_files', '/home/icg27/Dropbox/phd/SOS/examples', '/home/icg27/Dropbox/phd/SOS/examples', '/home/icg27/Dropbox/phd/SOS/examples', '/home/icg27/Dropbox/phd/SOS/examples', '/opt/ros/kinetic/lib/python2.7/dist-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/icg27/.local/lib/python2.7/site-packages', '/home/icg27/code/ray/python', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/python2.7/dist-packages/wx-3.0-gtk2', '/home/icg27/Dropbox/phd/SOS']
```
```
Sys.path ['/home/icg27/code/ray/python/ray/pyarrow_files', '/home/icg27/code/ray/python/ray/workers', '/opt/ros/kinetic/lib/python2.7/dist-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/icg27/.local/lib/python2.7/site-packages', '/home/icg27/code/ray/python', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/python2.7/dist-packages/wx-3.0-gtk2']
```

**Comment by raulchen** [comment]
Ray doesn't carry the whole `sys.path` to workers. It only inserts 2 paths (current path and path of the script) to `sys.path` of workers, see https://github.com/ray-project/ray/blob/fe65f9fbbc1e2a59dd2d11cf3fe17e3384ab746e/python/ray/worker.py#L2264-L2269.

Does this help debug your problem? If not, could you provide a minimal script to reproduce this problem?

**Comment by ICGog** [comment]
@raulchen thanks for your reply. Yes, that helped. I'm going to close the issue now.
