### ISSUE TITLE
problem with running ray.data.read_csv

### ISSUE THREAD

**Issue by sh2022515** [ray-project/ray#25179]
### What happened + What you expected to happen

Hi Ray community,

I am learning to use Ray for parallel data processing. I am running into a problem at the very first stage.
My code is:

```
import ray
ray.init(address="10.203.81.23:6379")
df2 = ray.data.read_csv('./transactions_202111.csv')
```

However, I was unable to read the data successfully.
I do not know why it says " FileNotFoundError: [Errno 2] Failed to open local file './transactions_202111.csv'. Detail: [errno 2] No such file or directory", because if I use pandas, there is no problem such error, but since the file is a bit too big, there is not enough memory to read it in full. That is why I am using Ray and I am connecting two nodes in order to read the file.
The error message is posted below. I would appreciate if you can help me!

### Versions / Dependencies

Python 3.9.7
ray 1.11.0
ray-core 1.6.0

### Reproduction script

```

(remote_read pid=487201) 2022-05-25 11:01:21,290	INFO worker.py:430 -- Task failed with retryable exception: TaskID(359ec6ce30d3ca2dffffffffffffffffffffffff01000000).
(remote_read pid=487201) Traceback (most recent call last):
(remote_read pid=487201)   File "python/ray/_raylet.pyx", line 640, in ray._raylet.execute_task
(remote_read pid=487201)   File "python/ray/_raylet.pyx", line 644, in ray._raylet.execute_task
(remote_read pid=487201)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/read_api.py", line 178, in remote_read
(remote_read pid=487201)     block = task()
(remote_read pid=487201)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/datasource.py", line 142, in __call__
(remote_read pid=487201)     for block in result:
(remote_read pid=487201)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 149, in read_files
(remote_read pid=487201)     with fs.open_input_stream(read_path, **open_stream_args) as f:
(remote_read pid=487201)   File "pyarrow/_fs.pyx", line 621, in pyarrow._fs.FileSystem.open_input_stream
(remote_read pid=487201)   File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
(remote_read pid=487201)   File "pyarrow/error.pxi", line 97, in pyarrow.lib.check_status
(remote_read pid=487201) FileNotFoundError: [Errno 2] Failed to open local file './transactions_202111.csv'. Detail: [errno 2] No such file or directory
(remote_read pid=487201) 2022-05-25 11:01:21,859	INFO worker.py:430 -- Task failed with retryable exception: TaskID(359ec6ce30d3ca2dffffffffffffffffffffffff01000000).
(remote_read pid=487201) Traceback (most recent call last):
(remote_read pid=487201)   File "python/ray/_raylet.pyx", line 640, in ray._raylet.execute_task
(remote_read pid=487201)   File "python/ray/_raylet.pyx", line 644, in ray._raylet.execute_task
(remote_read pid=487201)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/read_api.py", line 178, in remote_read
(remote_read pid=487201)     block = task()
(remote_read pid=487201)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/datasource.py", line 142, in __call__
(remote_read pid=487201)     for block in result:
(remote_read pid=487201)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 149, in read_files
(remote_read pid=487201)     with fs.open_input_stream(read_path, **open_stream_args) as f:
(remote_read pid=487201)   File "pyarrow/_fs.pyx", line 621, in pyarrow._fs.FileSystem.open_input_stream
(remote_read pid=487201)   File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
(remote_read pid=487201)   File "pyarrow/error.pxi", line 97, in pyarrow.lib.check_status
(remote_read pid=487201) FileNotFoundError: [Errno 2] Failed to open local file './transactions_202111.csv'. Detail: [errno 2] No such file or directory
(remote_read pid=487201) 2022-05-25 11:01:22,860	INFO worker.py:430 -- Task failed with retryable exception: TaskID(359ec6ce30d3ca2dffffffffffffffffffffffff01000000).
(remote_read pid=487201) Traceback (most recent call last):
(remote_read pid=487201)   File "python/ray/_raylet.pyx", line 640, in ray._raylet.execute_task
(remote_read pid=487201)   File "python/ray/_raylet.pyx", line 644, in ray._raylet.execute_task
(remote_read pid=487201)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/read_api.py", line 178, in remote_read
(remote_read pid=487201)     block = task()
(remote_read pid=487201)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/datasource.py", line 142, in __call__
(remote_read pid=487201)     for block in result:
(remote_read pid=487201)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 149, in read_files
(remote_read pid=487201)     with fs.open_input_stream(read_path, **open_stream_args) as f:
(remote_read pid=487201)   File "pyarrow/_fs.pyx", line 621, in pyarrow._fs.FileSystem.open_input_stream
(remote_read pid=487201)   File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
(remote_read pid=487201)   File "pyarrow/error.pxi", line 97, in pyarrow.lib.check_status
(remote_read pid=487201) FileNotFoundError: [Errno 2] Failed to open local file './transactions_202111.csv'. Detail: [errno 2] No such file or directory
```

```
RayTaskError(FileNotFoundError)           Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/read_api.py in read_csv(paths, filesystem, parallelism, ray_remote_args, arrow_open_stream_args, **arrow_csv_args)
    385         Dataset holding Arrow records read from the specified paths.
    386     """
--> 387     return read_datasource(
    388         CSVDatasource(),
    389         parallelism=parallelism,

~/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/read_api.py in read_datasource(datasource, parallelism, ray_remote_args, _spread_resource_prefix, **read_args)
    223     # Get the schema from the first block synchronously.
    224     if metadata and metadata[0].schema is None:
--> 225         block_list.ensure_schema_for_first_block()
    226 
    227     return Dataset(

~/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/impl/block_list.py in ensure_schema_for_first_block(self)
    154             # Dataset is empty (no blocks) or was manually cleared.
    155             return None
--> 156         schema = ray.get(get_schema.remote(block))
    157         # Set the schema.
    158         self._metadata[0].schema = schema

~/anaconda3/envs/ray/lib/python3.9/site-packages/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
    103             if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104                 return getattr(ray, func.__name__)(*args, **kwargs)
--> 105         return func(*args, **kwargs)
    106 
    107     return wrapper

~/anaconda3/envs/ray/lib/python3.9/site-packages/ray/worker.py in get(object_refs, timeout)
   1761                     worker.core_worker.dump_object_store_memory_usage()
   1762                 if isinstance(value, RayTaskError):
-> 1763                     raise value.as_instanceof_cause()
   1764                 else:
   1765                     raise value

RayTaskError(FileNotFoundError): ray::_get_schema() (pid=487201, ip=10.203.81.23)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::remote_read() (pid=487201, ip=10.203.81.23)
  File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/read_api.py", line 178, in remote_read
    block = task()
  File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/datasource.py", line 142, in __call__
    for block in result:
  File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 149, in read_files
    with fs.open_input_stream(read_path, **open_stream_args) as f:
  File "pyarrow/_fs.pyx", line 621, in pyarrow._fs.FileSystem.open_input_stream
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 97, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file './transactions_202111.csv'. Detail: [errno 2] No such file or directory
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by xiurobert** [comment]
Hi, it looks like your error isn't formatted properly. This makes it rather hard to read. Could I please trouble you to reformat your errors? Thanks!
By the way, you can format them with a giant code block as such:
```
```
<your error logs>
```
```

**Comment by zhe-thoughts** [comment]
Thanks for helping here @xiurobert !

**Comment by sh2022515** [comment]
> Hi, it looks like your error isn't formatted properly. This makes it rather hard to read. Could I please trouble you to reformat your errors? Thanks! By the way, you can format them with a giant code block as such:
> 
> ```
> ```
> your error logs go here
> ```
> ```

I just updated it. Thank you!

**Comment by xiurobert** [comment]
Does the error occur if you pass in an absolute path?

```python
import ray
import os
ray.init(address="10.203.81.23:6379")
df2 = ray.data.read_csv(os.path.abspath('./transactions_202111.csv'))
```

**Comment by clarkzinzow** [comment]
Hi @sh2022515, thanks for trying out Ray Datasets!

> but since the file is a bit too big, there is not enough memory to read it in full.

Note that Datasets will still read the entire file into memory on a single node; Datasets does not yet support streaming reads or reading chunks of a single file onto different nodes.

> That is why I am using Ray and I am connecting two nodes in order to read the file.

When reading a file from local disk, the Ray node that ends up reading the file will need to have the file local on that node. Does the file exist on each Ray node?

You have a few simple options here:
1. Copy the file onto each Ray node so any Ray node can read it.
2. Put the file onto a single Ray node and force the Datasets read tasks to be scheduled onto that Ray node via the `NodeAffinitySchedulingStrategy`: `ray.data.read_csv(..., ray_remote_args=dict(ray.util.scheduling_strategies.NodeAffinitySchedulingStrategy(node_id, soft=False)))`
3. Put the file into cloud storage (S3, GCS, Azure Blob Storage) so any Ray node can read it.

Most users opt for (3) as their data scales.

**Comment by sh2022515** [comment]
> 2\. ra

Thank you for your reply @clarkzinzow , 

I tried first two options you have mentioned:
1. I have the same file on both nodes, and the versions of Python and Ray are the same.
2. I shut down one node, and changed the code to what you suggested:
```
df2 = ray.data.read_csv('./transactions_202111.csv', ray_remote_args=dict(scheduling_strategy=ray.util.scheduling_strategies.NodeAffinitySchedulingStrategy('35556e033487f68180d903202652cd99028d81beda8eb1ed504b00d3', soft=False)))
```
The error appears:
```
AttributeError                            Traceback (most recent call last)
<timed exec> in <module>

AttributeError: module 'ray.util.scheduling_strategies' has no attribute 'NodeAffinitySchedulingStrategy'
```

3.  I do not have access to any cloud storage, because I am using the university facility for my project.

I also tried to use absolute path, the error code appears to be:

```
(remote_read pid=825125) 2022-05-25 20:14:30,166	INFO worker.py:430 -- Task failed with retryable exception: TaskID(e0dc174c83599034ffffffffffffffffffffffff01000000).
(remote_read pid=825125) Traceback (most recent call last):
(remote_read pid=825125)   File "python/ray/_raylet.pyx", line 640, in ray._raylet.execute_task
(remote_read pid=825125)   File "python/ray/_raylet.pyx", line 644, in ray._raylet.execute_task
(remote_read pid=825125)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/read_api.py", line 178, in remote_read
(remote_read pid=825125)     block = task()
(remote_read pid=825125)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/datasource.py", line 142, in __call__
(remote_read pid=825125)     for block in result:
(remote_read pid=825125)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 150, in read_files
(remote_read pid=825125)     for data in read_stream(f, read_path, **reader_args):
(remote_read pid=825125)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/csv_datasource.py", line 31, in _read_stream
(remote_read pid=825125)     batch = reader.read_next_batch()
(remote_read pid=825125)   File "pyarrow/ipc.pxi", line 531, in pyarrow.lib.RecordBatchReader.read_next_batch
(remote_read pid=825125)   File "pyarrow/error.pxi", line 84, in pyarrow.lib.check_status
(remote_read pid=825125) pyarrow.lib.ArrowInvalid: In CSV column #11: CSV conversion error to null: invalid value '0x40a6602cbf4a517e03f4b906232b892c5e55cd57'
(remote_read pid=825125) 2022-05-25 20:14:30,727	INFO worker.py:430 -- Task failed with retryable exception: TaskID(e0dc174c83599034ffffffffffffffffffffffff01000000).
(remote_read pid=825125) Traceback (most recent call last):
(remote_read pid=825125)   File "python/ray/_raylet.pyx", line 640, in ray._raylet.execute_task
(remote_read pid=825125)   File "python/ray/_raylet.pyx", line 644, in ray._raylet.execute_task
(remote_read pid=825125)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/read_api.py", line 178, in remote_read
(remote_read pid=825125)     block = task()
(remote_read pid=825125)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/datasource.py", line 142, in __call__
(remote_read pid=825125)     for block in result:
(remote_read pid=825125)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 150, in read_files
(remote_read pid=825125)     for data in read_stream(f, read_path, **reader_args):
(remote_read pid=825125)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/csv_datasource.py", line 31, in _read_stream
(remote_read pid=825125)     batch = reader.read_next_batch()
(remote_read pid=825125)   File "pyarrow/ipc.pxi", line 531, in pyarrow.lib.RecordBatchReader.read_next_batch
(remote_read pid=825125)   File "pyarrow/error.pxi", line 84, in pyarrow.lib.check_status
(remote_read pid=825125) pyarrow.lib.ArrowInvalid: In CSV column #11: CSV conversion error to null: invalid value '0x40a6602cbf4a517e03f4b906232b892c5e55cd57'
(remote_read pid=825125) 2022-05-25 20:14:31,730	INFO worker.py:430 -- Task failed with retryable exception: TaskID(e0dc174c83599034ffffffffffffffffffffffff01000000).
(remote_read pid=825125) Traceback (most recent call last):
(remote_read pid=825125)   File "python/ray/_raylet.pyx", line 640, in ray._raylet.execute_task
(remote_read pid=825125)   File "python/ray/_raylet.pyx", line 644, in ray._raylet.execute_task
(remote_read pid=825125)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/read_api.py", line 178, in remote_read
(remote_read pid=825125)     block = task()
(remote_read pid=825125)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/datasource.py", line 142, in __call__
(remote_read pid=825125)     for block in result:
(remote_read pid=825125)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 150, in read_files
(remote_read pid=825125)     for data in read_stream(f, read_path, **reader_args):
(remote_read pid=825125)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/csv_datasource.py", line 31, in _read_stream
(remote_read pid=825125)     batch = reader.read_next_batch()
(remote_read pid=825125)   File "pyarrow/ipc.pxi", line 531, in pyarrow.lib.RecordBatchReader.read_next_batch
(remote_read pid=825125)   File "pyarrow/error.pxi", line 84, in pyarrow.lib.check_status
(remote_read pid=825125) pyarrow.lib.ArrowInvalid: In CSV column #11: CSV conversion error to null: invalid value '0x40a6602cbf4a517e03f4b906232b892c5e55cd57'
(remote_read pid=825125) 2022-05-25 20:14:32,730	INFO worker.py:430 -- Task failed with retryable exception: TaskID(e0dc174c83599034ffffffffffffffffffffffff01000000).
(remote_read pid=825125) Traceback (most recent call last):
(remote_read pid=825125)   File "python/ray/_raylet.pyx", line 640, in ray._raylet.execute_task
(remote_read pid=825125)   File "python/ray/_raylet.pyx", line 644, in ray._raylet.execute_task
(remote_read pid=825125)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/read_api.py", line 178, in remote_read
(remote_read pid=825125)     block = task()
(remote_read pid=825125)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/datasource.py", line 142, in __call__
(remote_read pid=825125)     for block in result:
(remote_read pid=825125)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 150, in read_files
(remote_read pid=825125)     for data in read_stream(f, read_path, **reader_args):
(remote_read pid=825125)   File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/csv_datasource.py", line 31, in _read_stream
(remote_read pid=825125)     batch = reader.read_next_batch()
(remote_read pid=825125)   File "pyarrow/ipc.pxi", line 531, in pyarrow.lib.RecordBatchReader.read_next_batch
(remote_read pid=825125)   File "pyarrow/error.pxi", line 84, in pyarrow.lib.check_status
(remote_read pid=825125) pyarrow.lib.ArrowInvalid: In CSV column #11: CSV conversion error to null: invalid value '0x40a6602cbf4a517e03f4b906232b892c5e55cd57'
```
```
RayTaskError(ArrowInvalid)                Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/read_api.py in read_csv(paths, filesystem, parallelism, ray_remote_args, arrow_open_stream_args, **arrow_csv_args)
    385         Dataset holding Arrow records read from the specified paths.
    386     """
--> 387     return read_datasource(
    388         CSVDatasource(),
    389         parallelism=parallelism,

~/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/read_api.py in read_datasource(datasource, parallelism, ray_remote_args, _spread_resource_prefix, **read_args)
    223     # Get the schema from the first block synchronously.
    224     if metadata and metadata[0].schema is None:
--> 225         block_list.ensure_schema_for_first_block()
    226 
    227     return Dataset(

~/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/impl/block_list.py in ensure_schema_for_first_block(self)
    154             # Dataset is empty (no blocks) or was manually cleared.
    155             return None
--> 156         schema = ray.get(get_schema.remote(block))
    157         # Set the schema.
    158         self._metadata[0].schema = schema

~/anaconda3/envs/ray/lib/python3.9/site-packages/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
    103             if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104                 return getattr(ray, func.__name__)(*args, **kwargs)
--> 105         return func(*args, **kwargs)
    106 
    107     return wrapper

~/anaconda3/envs/ray/lib/python3.9/site-packages/ray/worker.py in get(object_refs, timeout)
   1761                     worker.core_worker.dump_object_store_memory_usage()
   1762                 if isinstance(value, RayTaskError):
-> 1763                     raise value.as_instanceof_cause()
   1764                 else:
   1765                     raise value

RayTaskError(ArrowInvalid): ray::_get_schema() (pid=825125, ip=10.203.81.23)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::remote_read() (pid=825125, ip=10.203.81.23)
  File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/read_api.py", line 178, in remote_read
    block = task()
  File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/datasource.py", line 142, in __call__
    for block in result:
  File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 150, in read_files
    for data in read_stream(f, read_path, **reader_args):
  File "/home/cs201503/anaconda3/envs/ray/lib/python3.9/site-packages/ray/data/datasource/csv_datasource.py", line 31, in _read_stream
    batch = reader.read_next_batch()
  File "pyarrow/ipc.pxi", line 531, in pyarrow.lib.RecordBatchReader.read_next_batch
  File "pyarrow/error.pxi", line 84, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: In CSV column #11: CSV conversion error to null: invalid value '0x40a6602cbf4a517e03f4b906232b892c5e55cd57'

```

**Comment by sh2022515** [comment]
Thank you for your help @clarkzinzow .
I researched a bit, I used Modin Ray to read the files, it works fine and the time has shortened significantly.
I just have one last question, what is the difference between using "modin Ray" and "ray.data.read_csv" ?
As far as I understand, "modin Ray" is a substitute for pandas in the Ray framework, and "ray.data.read_csv" is for reading datasets in Ray framework?
