### ISSUE TITLE
[<Ray component: Core>]  Generated protos are out of date with Google's latest release

### ISSUE THREAD

**Issue by RehanSD** [ray-project/ray#25205]
### What happened + What you expected to happen

Google released a new major version of protobuf that has some breaking changes from older versions. When running sphinx with the new protobuf version, we receive the following error.
```
Traceback (most recent call last):
[11](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:12)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
[12](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:13)
    exec(code, namespace)
[13](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:14)
  File "/home/runner/work/modin/modin/docs/conf.py", line 14, in <module>
[14](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:15)
    import ray
[15](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:16)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/ray/__init__.py", line 108, in <module>
[16](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:17)
    import ray._raylet  # noqa: E402
[17](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:18)
  File "python/ray/_raylet.pyx", line 115, in init ray._raylet
[18](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:19)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/ray/exceptions.py", line 7, in <module>
[19](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:20)
    from ray.core.generated.common_pb2 import RayException, Language, PYTHON
[20](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:21)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/ray/core/generated/common_pb2.py", line 15, in <module>
[21](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:22)
    from . import runtime_env_common_pb2 as src_dot_ray_dot_protobuf_dot_runtime__env__common__pb2
[22](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:23)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/ray/core/generated/runtime_env_common_pb2.py", line 36, in <module>
[23](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:24)
    _descriptor.FieldDescriptor(
[24](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:25)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 560, in __new__
[25](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:26)
    _message.Message._CheckCalledFromGeneratedFile()
[26](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:27)
TypeError: Descriptors cannot not be created directly.
[27](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:28)
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
[28](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:29)
If you cannot immediately regenerate your protos, some other possible workarounds are:
[29](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:30)
 1. Downgrade the protobuf package to 3.20.x or lower.
[30](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:31)
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
[31](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:32)

[32](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:33)
More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
[33](https://github.com/modin-project/modin/runs/6603561510?check_suite_focus=true#step:5:34)
```

### Versions / Dependencies

ray 1.12.1
protobuf 4.21.0

### Reproduction script

Create a file titled `conf.py` with the following line:
```python
import ray
```
Then, in the same directory as `conf.py`, run
```sh
sphinx-build -T -E -W -b html . build
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by RehanSD** [comment]
I believe this should be resolved by regenerating the protos with the newest version of protobuf.

**Comment by Samreay** [comment]
To try and increase the priority of this, with the proto update, ray will no longer even initialise:

```
    import ray
  File "/opt/venv/lib/python3.9/site-packages/ray/__init__.py", line 108, in <module>
    import ray._raylet  # noqa: E402
  File "python/ray/_raylet.pyx", line 115, in init ray._raylet
  File "/opt/venv/lib/python3.9/site-packages/ray/exceptions.py", line 7, in <module>
    from ray.core.generated.common_pb2 import RayException, Language, PYTHON
  File "/opt/venv/lib/python3.9/site-packages/ray/core/generated/common_pb2.py", line 15, in <module>
    from . import runtime_env_common_pb2 as src_dot_ray_dot_protobuf_dot_runtime__env__common__pb2
  File "/opt/venv/lib/python3.9/site-packages/ray/core/generated/runtime_env_common_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/opt/venv/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
 ```

**Comment by devin-petersohn** [comment]
protobuf > 4 was yanked from pypi so I think this can be closed (for now 😄 ).

Link: https://pypi.org/project/protobuf/#history

**Comment by YarShev** [comment]
Isn't it worth adding a pin for the range of correct versions of protobuf to exclude any side effect with the bug version?

**Comment by mwtian** [comment]
Ray has pinned `protobuf` to `<= 4` on `master` branch / nightly: https://github.com/ray-project/ray/commit/7fcea8a8ae0f3ebac0539e35bd6555a15f861e19

Since Python protobuf 4.21 has been yanked, there is probably not enough reason to patch previous releases for now.
