### ISSUE TITLE
[RLlib] Experiment Is Slower When Using GPU

### ISSUE THREAD

**Issue by fridary** [ray-project/ray#25277]
### What happened + What you expected to happen

This is weird thing my GPU Nvidia Tesla K80 is not detected on `tune.run()`, but on `agent.train()` does. Any ideas what's wrong?

### Versions / Dependencies

OS: Ubuntu 20.04
Python: 3.8.13
Ray: 1.12.1
GPU: NVidia Tesla K80
CPU: 2x Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz

### Reproduction script

```python
import ray
import ray.rllib.agents.ppo as ppo

ray.init()
trainer = ppo.PPOTrainer(config={
    "framework": 'tf',
    "num_gpus": 1,
}, env="CartPole-v1")

for _ in range(5):
    trainer.train()
```
Results:
```
2022-05-28 12:03:22,563	INFO services.py:1456 -- View the Ray dashboard at http://127.0.0.1:8265
2022-05-28 12:03:24,821	INFO trainer.py:2295 -- Your framework setting is 'tf', meaning you are using static-graph mode. Set framework='tf2' to enable eager execution with tf2.x. You may also then want to set eager_tracing=True in order to reach similar execution speed as with static-graph mode.
2022-05-28 12:03:24,822	INFO ppo.py:268 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
2022-05-28 12:03:24,822	INFO trainer.py:864 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=48833) 
(pid=48832) 
(RolloutWorker pid=48833) 2022-05-28 12:03:29,312	WARNING rollout_worker.py:498 -- We've added a module for checking environments that are used in experiments. It will cause your environment to fail if your environment is not set upcorrectly. You can disable check env by setting `disable_env_checking` to True in your experiment config dictionary. You can run the environment checking module standalone by calling ray.rllib.utils.check_env(env).
(RolloutWorker pid=48832) 2022-05-28 12:03:29,330	WARNING rollout_worker.py:498 -- We've added a module for checking environments that are used in experiments. It will cause your environment to fail if your environment is not set upcorrectly. You can disable check env by setting `disable_env_checking` to True in your experiment config dictionary. You can run the environment checking module standalone by calling ray.rllib.utils.check_env(env).
2022-05-28 12:03:36,040	INFO trainable.py:152 -- Trainable.setup took 11.221 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2022-05-28 12:03:36,041	WARNING util.py:60 -- Install gputil for GPU system monitoring.
```

So, everything is fine. Now, if I set `"num_gpus": 2`, I get error as it must be:

<img width="924" alt="Снимок экрана 2022-05-28 в 12 06 09" src="https://user-images.githubusercontent.com/3791864/170818816-cc51af85-062a-4143-8cca-c6612ca4cbd0.png">

We can see there is 1 GPU found. Now let's tune:
```python
ray.init()
tune.run(
    run_or_experiment="PPO",
    stop={"training_iteration": 5},
    config={
        "env": "CartPole-v1",
        "framework": 'tf',
        "num_gpus": 1,
        "lr": tune.choice([0.0005, 0.00001]),
    },
    num_samples=5,
)
```
And I get error `RuntimeError: Found 0 GPUs on your machine (GPU devices found: [])!`:

```
2022-05-28 12:08:18,987	INFO services.py:1456 -- View the Ray dashboard at http://127.0.0.1:8265
2022-05-28 12:08:21,607	INFO trial_runner.py:803 -- starting PPO_CartPole-v1_b8898_00000
(pid=56430) 
(PPOTrainer pid=56430) 2022-05-28 12:08:26,505	INFO trainer.py:2295 -- Your framework setting is 'tf', meaning you are using static-graph mode. Set framework='tf2' to enable eager execution with tf2.x. You may also then want to set eager_tracing=True in order to reach similar execution speed as with static-graph mode.
(PPOTrainer pid=56430) 2022-05-28 12:08:26,506	INFO ppo.py:268 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
(PPOTrainer pid=56430) 2022-05-28 12:08:26,506	INFO trainer.py:864 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=56549) 
(pid=56548) 
(RolloutWorker pid=56549) 2022-05-28 12:08:31,860	WARNING rollout_worker.py:498 -- We've added a module for checking environments that are used in experiments. It will cause your environment to fail if your environment is not set upcorrectly. You can disable check env by setting `disable_env_checking` to True in your experiment config dictionary. You can run the environment checking module standalone by calling ray.rllib.utils.check_env(env).
(RolloutWorker pid=56548) 2022-05-28 12:08:31,950	WARNING rollout_worker.py:498 -- We've added a module for checking environments that are used in experiments. It will cause your environment to fail if your environment is not set upcorrectly. You can disable check env by setting `disable_env_checking` to True in your experiment config dictionary. You can run the environment checking module standalone by calling ray.rllib.utils.check_env(env).
== Status ==
Current time: 2022-05-28 12:08:39 (running for 00:00:17.83)
Memory usage on this node: 7.9/62.8 GiB
Using FIFO scheduling algorithm.
Resources requested: 3.0/72 CPUs, 1.0/2 GPUs, 0.0/36.31 GiB heap, 0.0/18.15 GiB objects (0.0/1.0 accelerator_type:K80)
Result logdir: /home/sirjay/python/rl/ray_results_temp_v2/PPO
Number of trials: 5/5 (4 PENDING, 1 RUNNING)
+-----------------------------+----------+--------------------+--------+
| Trial name                  | status   | loc                |     lr |
|-----------------------------+----------+--------------------+--------|
| PPO_CartPole-v1_b8898_00000 | RUNNING  | 91.242.32.44:56430 | 0.0005 |
| PPO_CartPole-v1_b8898_00001 | PENDING  |                    | 1e-05  |
| PPO_CartPole-v1_b8898_00002 | PENDING  |                    | 0.0005 |
| PPO_CartPole-v1_b8898_00003 | PENDING  |                    | 1e-05  |
| PPO_CartPole-v1_b8898_00004 | PENDING  |                    | 1e-05  |
+-----------------------------+----------+--------------------+--------+


2022-05-28 12:08:39,036	INFO trial_runner.py:803 -- starting PPO_CartPole-v1_b8898_00001
(PPOTrainer pid=56430) 2022-05-28 12:08:39,002	INFO trainable.py:152 -- Trainable.setup took 12.497 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
(PPOTrainer pid=56430) 2022-05-28 12:08:39,004	WARNING util.py:60 -- Install gputil for GPU system monitoring.
(pid=56667) 
(PPOTrainer pid=56667) 2022-05-28 12:08:44,046	INFO trainer.py:2295 -- Your framework setting is 'tf', meaning you are using static-graph mode. Set framework='tf2' to enable eager execution with tf2.x. You may also then want to set eager_tracing=True in order to reach similar execution speed as with static-graph mode.
(PPOTrainer pid=56667) 2022-05-28 12:08:44,047	INFO ppo.py:268 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
(PPOTrainer pid=56667) 2022-05-28 12:08:44,047	INFO trainer.py:864 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=56786) 
(pid=56785) 
(RolloutWorker pid=56786) 2022-05-28 12:08:49,186	WARNING rollout_worker.py:498 -- We've added a module for checking environments that are used in experiments. It will cause your environment to fail if your environment is not set upcorrectly. You can disable check env by setting `disable_env_checking` to True in your experiment config dictionary. You can run the environment checking module standalone by calling ray.rllib.utils.check_env(env).
(RolloutWorker pid=56785) 2022-05-28 12:08:49,723	WARNING rollout_worker.py:498 -- We've added a module for checking environments that are used in experiments. It will cause your environment to fail if your environment is not set upcorrectly. You can disable check env by setting `disable_env_checking` to True in your experiment config dictionary. You can run the environment checking module standalone by calling ray.rllib.utils.check_env(env).
(PPOTrainer pid=56667) 2022-05-28 12:08:53,518	ERROR worker.py:449 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::PPOTrainer.__init__() (pid=56667, ip=91.242.32.44, repr=PPOTrainer)
(PPOTrainer pid=56667)   File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1035, in _init
(PPOTrainer pid=56667)     raise NotImplementedError
(PPOTrainer pid=56667) NotImplementedError
(PPOTrainer pid=56667) 
(PPOTrainer pid=56667) During handling of the above exception, another exception occurred:
(PPOTrainer pid=56667) 
(PPOTrainer pid=56667) ray::PPOTrainer.__init__() (pid=56667, ip=91.242.32.44, repr=PPOTrainer)
(PPOTrainer pid=56667)   File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 830, in __init__
(PPOTrainer pid=56667)     super().__init__(
(PPOTrainer pid=56667)   File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ray/tune/trainable.py", line 149, in __init__
(PPOTrainer pid=56667)     self.setup(copy.deepcopy(self.config))
(PPOTrainer pid=56667)   File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 911, in setup
(PPOTrainer pid=56667)     self.workers = WorkerSet(
(PPOTrainer pid=56667)   File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 162, in __init__
(PPOTrainer pid=56667)     self._local_worker = self._make_worker(
(PPOTrainer pid=56667)   File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 567, in _make_worker
(PPOTrainer pid=56667)     worker = cls(
(PPOTrainer pid=56667)   File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 608, in __init__
(PPOTrainer pid=56667)     raise RuntimeError(
(PPOTrainer pid=56667) RuntimeError: Found 0 GPUs on your machine (GPU devices found: [])! If your machine
(PPOTrainer pid=56667)     does not have any GPUs, you should set the config keys `num_gpus` and
(PPOTrainer pid=56667)     `num_gpus_per_worker` to 0 (they may be set to 1 by default for your
(PPOTrainer pid=56667)     particular RL algorithm).
(PPOTrainer pid=56667) To change the config for the `rllib train|rollout` command, use
(PPOTrainer pid=56667)   `--config={'[key]': '[value]'}` on the command line.
(PPOTrainer pid=56667) To change the config for `tune.run()` in a script: Modify the python dict
(PPOTrainer pid=56667)   passed to `tune.run(config=[...])`.
== Status ==
Current time: 2022-05-28 12:08:53 (running for 00:00:32.33)
Memory usage on this node: 8.6/62.8 GiB
Using FIFO scheduling algorithm.
Resources requested: 6.0/72 CPUs, 2.0/2 GPUs, 0.0/36.31 GiB heap, 0.0/18.15 GiB objects (0.0/1.0 accelerator_type:K80)
Result logdir: /home/sirjay/python/rl/ray_results_temp_v2/PPO
Number of trials: 5/5 (3 PENDING, 2 RUNNING)
+-----------------------------+----------+--------------------+--------+
| Trial name                  | status   | loc                |     lr |
|-----------------------------+----------+--------------------+--------|
| PPO_CartPole-v1_b8898_00000 | RUNNING  | 91.242.32.44:56430 | 0.0005 |
| PPO_CartPole-v1_b8898_00001 | RUNNING  |                    | 1e-05  |
| PPO_CartPole-v1_b8898_00002 | PENDING  |                    | 0.0005 |
| PPO_CartPole-v1_b8898_00003 | PENDING  |                    | 1e-05  |
| PPO_CartPole-v1_b8898_00004 | PENDING  |                    | 1e-05  |
+-----------------------------+----------+--------------------+--------+

```

Some info:
```
$ nvidia-smi
Sat May 28 12:11:17 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:86:00.0 Off |                  Off |
| N/A   58C    P8    28W / 149W |      4MiB / 12206MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1529      G   /usr/lib/xorg/Xorg                  3MiB |
+-----------------------------------------------------------------------------+
```

And tensorflow+ray log
```python
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

import ray
import os
ray.init(num_gpus=1)
print(int(os.environ.get("RLLIB_NUM_GPUS", "0")))
print("ray.get_gpu_ids(): {}".format(ray.get_gpu_ids()))
print("CUDA_VISIBLE_DEVICES: {}".format(os.environ["CUDA_VISIBLE_DEVICES"]))
```
returns
```
2022-05-28 12:12:51.872226: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-05-28 12:12:53.199023: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-05-28 12:12:53.204755: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-05-28 12:12:53.205957: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2022-05-28 12:12:54.066293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:86:00.0 name: Tesla K80 computeCapability: 3.7
coreClock: 0.562GHz coreCount: 13 deviceMemorySize: 11.92GiB deviceMemoryBandwidth: 223.96GiB/s
2022-05-28 12:12:54.066323: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-05-28 12:12:54.068442: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2022-05-28 12:12:54.068483: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2022-05-28 12:12:54.070680: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2022-05-28 12:12:54.071006: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2022-05-28 12:12:54.073269: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2022-05-28 12:12:54.074497: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2022-05-28 12:12:54.079057: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2022-05-28 12:12:54.080487: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2022-05-28 12:12:54.080529: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-05-28 12:12:54.592625: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-05-28 12:12:54.592719: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2022-05-28 12:12:54.592729: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2022-05-28 12:12:54.595394: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/device:GPU:0 with 11339 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:86:00.0, compute capability: 3.7)
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 8322640958984099911
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 11890773184
locality {
  bus_id: 2
  numa_node: 1
  links {
  }
}
incarnation: 13398944408975680963
physical_device_desc: "device: 0, name: Tesla K80, pci bus id: 0000:86:00.0, compute capability: 3.7"
]
2022-05-28 12:12:56,961	INFO services.py:1456 -- View the Ray dashboard at http://127.0.0.1:8265
0
2022-05-28 12:12:59,198	WARNING worker.py:523 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
ray.get_gpu_ids(): []
Traceback (most recent call last):
  File "test2.py", line 29, in <module>
    print("CUDA_VISIBLE_DEVICES: {}".format(os.environ["CUDA_VISIBLE_DEVICES"]))
  File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'CUDA_VISIBLE_DEVICES'
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by fridary** [comment]
Problem solved if I use `ray.init(num_gpus=1)`

**Comment by fridary** [comment]
Hm, I figured out with gpu inited execution is x5 slower! How that could be?

```
num_workers=1, num_gpus=1, 131.5m (7887.2 seconds)
num_workers=2, num_gpus=1, 103.1m (6186.3 seconds)
num_workers=4, num_gpus=1, 86.7m (5201.9 seconds)
num_workers=8, num_gpus=1, 81.2m (4873.4 seconds)
num_workers=16, num_gpus=1, 82.6m (4957.5 seconds)
num_workers=24, num_gpus=1, 150.9m (9054.3 seconds)
num_workers=32, num_gpus=1, 155.4m (9325.6 seconds)
num_workers=50, num_gpus=1, 106.5m (6389.0 seconds)
num_workers=70, num_gpus=1, 184.7m (11083.5 seconds)
num_workers=1, num_gpus=0, 18.9m (1132.4 seconds)
num_workers=2, num_gpus=0, 17.8m (1068.3 seconds)
num_workers=4, num_gpus=0, 16.0m (960.0 seconds)
num_workers=8, num_gpus=0, 19.8m (1186.5 seconds)
num_workers=16, num_gpus=0, 32.6m (1956.8 seconds)
num_workers=24, num_gpus=0, 79.5m (4770.8 seconds)
num_workers=32, num_gpus=0, 87.3m (5240.6 seconds)
num_workers=50, num_gpus=0, 113.9m (6834.8 seconds)
...
```

```python
# server 36 cores, 72 threads
ray.init(num_cpus=72, num_gpus=1)
for num_gpus in [1, 0]:
    for num_workers in [1, 2, 4, 8, 16, 24, 32, 50, 70]:
        start_time = time.time()
        analysis = tune.run(
            run_or_experiment="PPO",
            metric='episode_reward_mean',
            mode='max',
            stop={"training_iteration": 50},
            config={
                "env": MyEnv,
                "framework": 'tf',
                "num_gpus": num_gpus,
                "num_workers": num_workers,
            },
        )
        end_time = time.time() - start_time
        execu = "%.1fm (%.1f seconds)" % (end_time / 60, end_time)
        print(f'num_workers={num_workers}, num_gpus={num_gpus}, {execu}\n')
```

**Comment by fridary** [comment]
@avnishn here is minimal code, but it seems it will hard to check

```python
import os
import ray
import ray.rllib.agents.ppo as ppo
from ray import tune
from ray.tune import ExperimentAnalysis
from ray.tune.registry import register_env
from ray.tune.suggest.bayesopt import BayesOptSearch
import shutil
import gym
from gym.spaces import Box, Dict, Discrete
from gym.utils import seeding
from enum import Enum
import pandas as pd
import numpy as np
from pprint import pprint
import matplotlib.pyplot as plt
import time
import sys
import json
import random
import ray.rllib.agents.ppo as ppo
from ray.tune.registry import register_env
from ray.rllib.utils.spaces.space_utils import flatten_space
import gym
from gym.spaces import Box, Dict, Discrete, Tuple
from gym.spaces.utils import flatten_space, flatten
from gym.utils import seeding
from enum import Enum
import pandas as pd
import numpy as np
import random

class ActionTimer(Enum):
    HOLD = 0
    BUY = 1
    SELL = 2
    SKIP = 3

class TradingEnvTimer(gym.Env):
    def __init__(self, config):
        super(TradingEnvTimer, self).__init__()
        self.action_space = Discrete(len(ActionTimer))
        self.observation_space = Dict({
            "action_mask": Box(0, 1, shape=(len(ActionTimer),)),
            "actual_obs": Box(low=-np.inf,high=np.inf,shape=(10, 10),dtype=np.float32)
        })

    def reset(self):
        self.current_step = 1
        return self._next_observation()
    
    def _next_observation(self):
        return {
            "action_mask": np.array([random.randint(0, 1)] * len(ActionTimer)),
            "actual_obs": np.random.randn(10, 10)
        }
    
    def step(self, action):
        self.current_step += 1
        reward = random.uniform(0, 1) / 10000
        obs = self._next_observation()
        done = self.current_step == 10000
        return obs, reward, done, {}

def main ():
    with open('timer_results.txt', 'a+') as f:
        f.write('---\n')
    for num_gpus in [0, 1]:
        ray.init(num_cpus=72, num_gpus=num_gpus)
        for num_workers in [1, 2, 4, 8, 16, 24, 32, 50, 70]:
            start_time = time.time()
            shutil.rmtree("ray_results_temp", ignore_errors=True, onerror=None)
            analysis = tune.run(
                run_or_experiment="PPO",
                name="TradingEnvExp1",
                metric='episode_reward_mean',
                mode='max',
                stop={"training_iteration": 50},
                config={
                    "env": TradingEnvTimer,
                    "framework": 'tf',

                    "num_gpus": num_gpus,
                    "num_workers": num_workers,
                    "num_cpus_for_driver": 1,
                    "num_cpus_per_worker": 1,

                    "model": {"fcnet_hiddens": tune.grid_search([[256, 256], [1024], [128, 64, 32], [512, 512, 512]]),},
                    "lr": tune.grid_search([0.0005, 0.00001]),
                    "gamma": tune.grid_search([0.99, 0.60]),
                    "sgd_minibatch_size": tune.grid_search([128, 256]),
                    
                    'rollout_fragment_length': 200,
                    'train_batch_size': 2000,
                },
            )

            end_time = time.time() - start_time
            print(f'num_workers={num_workers}, num_gpus={num_gpus} done!')
            print("%.1fm total execution (%.1f seconds)" % (end_time / 60, end_time))

            execu = "%.1fm (%.1f seconds)" % (end_time / 60, end_time)
            with open('timer_results.txt', 'a+') as f:
                f.write(f'num_workers={num_workers}, num_gpus={num_gpus} {execu}\n')

        ray.shutdown()

if __name__ == "__main__":
    main()
```

**Comment by krfricke** [comment]
@fridary GPU training sometimes suffers if batch sizes are too small. This is because data has to be shipped from memory to GPU and back often. Can you try increasing the batch size dramatically and compare that?

**Comment by ArturNiederfahrenhorst** [comment]
Difference for standard batch size: Quick ones are without GPU
<img width="345" alt="Screen Shot 2023-01-11 at 1 02 23 PM" src="https://user-images.githubusercontent.com/9356806/211917118-2fdbe6c7-6f0a-4458-89df-c33a3fc54edf.png">

Difference for train batch size of 5k, mini sgd batch size of 1k:
<img width="361" alt="Screen Shot 2023-01-11 at 1 15 03 PM" src="https://user-images.githubusercontent.com/9356806/211919209-a6f7b902-24e6-47ad-b90c-d86e881fb11a.png">

I tested this on a G3 instance and as Kai said, this appears natural.
Generally, most of our experiments profit from GPUs alot.

Additionally, here's the difference in throughput in the learner for train batch size of 5k, mini sgd batch size of 1k _vs_ train batch size of 20k and sgd batch size of 5k:
<img width="361" alt="Screen Shot 2023-01-11 at 1 18 17 PM" src="https://user-images.githubusercontent.com/9356806/211919842-f251f60c-7bda-467a-8331-0386052904bb.png">
