### ISSUE TITLE
[Ray Air] `resources_per_worker` not available

### ISSUE THREAD

**Issue by JiahaoYao** [ray-project/ray#25328]
### Description

I am setting the `scaling config` to AIR trainer by 

```python
    scaling_config = dict(num_workers=num_workers, use_gpu=use_gpu, resources_per_worker={'GPU': 4})
```

I got the following error, does that mean `resources_per_worker` is not available for current AIR trainer? 
```python
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/tuner.py", line 191, in fit
    return self._local_tuner.fit()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/impl/tuner_internal.py", line 158, in fit
    analysis = self._fit_internal(trainable, param_space)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/impl/tuner_internal.py", line 166, in _fit_internal
    analysis = run(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/tune.py", line 723, in run
    runner.step()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 774, in step
    next_trial = self._update_trial_queue_and_get_next_trial()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 710, in _update_trial_queue_and_get_next_trial
    if not self._update_trial_queue(blocking=wait_for_trial):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 1295, in _update_trial_queue
    trial = self._search_alg.next_trial()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/suggest/basic_variant.py", line 362, in next_trial
    trial = next(self._trial_iter)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/suggest/basic_variant.py", line 179, in __next__
    return self.create_trial(resolved_vars, spec)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/suggest/basic_variant.py", line 124, in create_trial
    return create_trial_from_spec(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/config_parser.py", line 225, in create_trial_from_spec
    return Trial(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/trial.py", line 292, in __init__
    default_resources = trainable_cls.default_resource_request(self.config)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/ml/trainer.py", line 387, in default_resource_request
    trainer_cls._validate_and_get_scaling_config_data_class(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/ml/trainer.py", line 224, in _validate_and_get_scaling_config_data_class
    ensure_only_allowed_dict_keys_set(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/ml/utils/config.py", line 21, in ensure_only_allowed_dict_keys_set
    raise ValueError(
ValueError: Key(s) ['resources_per_worker'] are not allowed to be set in the current context. Remove them from the dict.
```

**Comment by JiahaoYao** [comment]
This is related to https://github.com/ray-project/ray/blob/master/python/ray/ml/train/data_parallel_trainer.py#L227-L233 and the validation function here: https://github.com/ray-project/ray/blob/master/python/ray/ml/trainer.py#L218-L235. 

Here is a minimal example to show the error here
```python 
import ray
from ray.data import Dataset
from ray.ml.train.integrations.torch import TorchTrainer


def get_datasets(a=5, b=10, size=1000, split=0.8):
    def get_dataset(a, b, size) -> Dataset:
        items = [i / size for i in range(size)]
        dataset = ray.data.from_items([{"x": x, "y": a * x + b} for x in items])
        return dataset

    dataset = get_dataset(a, b, size)
    return dataset

dataset = get_datasets()


trainer = TorchTrainer(
    train_loop_per_worker=lambda : None,
    train_loop_config={"batch_size": 2},
    datasets={"train": dataset},
    scaling_config={"num_workers": 2, "use_gpu": True, "resources_per_worker": {'GPU': 4}}
)

trainer.fit()
```

This is the output
```python
2022-06-01 00:00:05,185 INFO services.py:1478 -- View the Ray dashboard at http://127.0.0.1:8266
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/tuner.py", line 191, in fit
    return self._local_tuner.fit()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/impl/tuner_internal.py", line 158, in fit
    analysis = self._fit_internal(trainable, param_space)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/impl/tuner_internal.py", line 166, in _fit_internal
    analysis = run(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/tune.py", line 723, in run
    runner.step()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 774, in step
    next_trial = self._update_trial_queue_and_get_next_trial()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 710, in _update_trial_queue_and_get_next_trial
    if not self._update_trial_queue(blocking=wait_for_trial):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 1295, in _update_trial_queue
    trial = self._search_alg.next_trial()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/suggest/basic_variant.py", line 362, in next_trial
    trial = next(self._trial_iter)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/suggest/basic_variant.py", line 179, in __next__
    return self.create_trial(resolved_vars, spec)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/suggest/basic_variant.py", line 124, in create_trial
    return create_trial_from_spec(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/config_parser.py", line 225, in create_trial_from_spec
    return Trial(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/trial.py", line 292, in __init__
    default_resources = trainable_cls.default_resource_request(self.config)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/ml/trainer.py", line 387, in default_resource_request
    trainer_cls._validate_and_get_scaling_config_data_class(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/ml/trainer.py", line 224, in _validate_and_get_scaling_config_data_class
    ensure_only_allowed_dict_keys_set(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/ml/utils/config.py", line 21, in ensure_only_allowed_dict_keys_set
    raise ValueError(
ValueError: Key(s) ['resources_per_worker'] are not allowed to be set in the current context. Remove them from the dict.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "issue_#25328.py", line 26, in <module>
    trainer.fit()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/ml/trainer.py", line 327, in fit
    result_grid = tuner.fit()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/tuner.py", line 193, in fit
    raise TuneError(
ray.tune.error.TuneError: Tune run failed. Please use tuner = Tuner.restore("/home/ubuntu/ray_results/TorchTrainer_2022-06-01_00-00-06") to resume.
```

If i do this 
replace 

```python
 "resources_per_worker": {'GPU': 4}
```

with 

```python
 "num_gpus_per_worker": 4
```



```python
trainer = TorchTrainer(
    train_loop_per_worker=lambda : None,
    train_loop_config={"batch_size": 2},
    datasets={"train": dataset},
    scaling_config={"num_workers": 2, "use_gpu": True, "num_gpus_per_worker": 4}
)

trainer.fit()
```

the output is 

```python
2022-06-01 00:01:57,280 INFO services.py:1478 -- View the Ray dashboard at http://127.0.0.1:8266
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/tuner.py", line 191, in fit
    return self._local_tuner.fit()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/impl/tuner_internal.py", line 158, in fit
    analysis = self._fit_internal(trainable, param_space)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/impl/tuner_internal.py", line 166, in _fit_internal
    analysis = run(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/tune.py", line 723, in run
    runner.step()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 774, in step
    next_trial = self._update_trial_queue_and_get_next_trial()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 710, in _update_trial_queue_and_get_next_trial
    if not self._update_trial_queue(blocking=wait_for_trial):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 1295, in _update_trial_queue
    trial = self._search_alg.next_trial()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/suggest/basic_variant.py", line 362, in next_trial
    trial = next(self._trial_iter)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/suggest/basic_variant.py", line 179, in __next__
    return self.create_trial(resolved_vars, spec)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/suggest/basic_variant.py", line 124, in create_trial
    return create_trial_from_spec(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/config_parser.py", line 225, in create_trial_from_spec
    return Trial(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/trial.py", line 292, in __init__
    default_resources = trainable_cls.default_resource_request(self.config)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/ml/trainer.py", line 387, in default_resource_request
    trainer_cls._validate_and_get_scaling_config_data_class(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/ml/trainer.py", line 227, in _validate_and_get_scaling_config_data_class
    scaling_config_dataclass = ScalingConfigDataClass(**dataclass_or_dict)
TypeError: __init__() got an unexpected keyword argument 'num_gpus_per_worker'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "issue_#25328.py", line 35, in <module>
    trainer.fit()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/ml/trainer.py", line 327, in fit
    result_grid = tuner.fit()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/tuner.py", line 193, in fit
    raise TuneError(
ray.tune.error.TuneError: Tune run failed. Please use tuner = Tuner.restore("/home/ubuntu/ray_results/TorchTrainer_2022-06-01_00-01-58") to resume.
```


@Yard1 @krfricke @matthewdeng
