### ISSUE TITLE
[Core]  Fresh ray install throws `No such file or directory: '/tmp/ray/cluster-default.lock'` on `ray up cluster.yaml`

### ISSUE THREAD

**Issue by jmakov** [ray-project/ray#25326]
### What happened + What you expected to happen

Fresh install of `ray` has problems with `ray up`. If I create manually an empty file '/tmp/ray/cluster-default.lock', it works.

```bash
$ ray up --no-config-cache examples/ray_cluster.yaml  -y

Usage stats collection will be enabled by default in the next release. See https://github.com/ray-project/ray/issues/20857 for more details.
Cluster: default

Checking Local environment settings
Traceback (most recent call last):
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/ray/scripts/scripts.py", line 2269, in main
    return cli()
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/ray/autoscaler/_private/cli_logger.py", line 808, in wrapper
    return f(*args, **kwargs)
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1158, in up
    create_or_update_cluster(
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 276, in create_or_update_cluster
    get_or_create_head_node(
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 633, in get_or_create_head_node
    provider = _provider or _get_node_provider(
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/ray/autoscaler/_private/providers.py", line 242, in _get_node_provider
    new_provider = provider_cls(provider_config, cluster_name)
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/ray/autoscaler/_private/local/node_provider.py", line 185, in __init__
    self.state = ClusterState(
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/ray/autoscaler/_private/local/node_provider.py", line 36, in __init__
    with self.file_lock:
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/filelock/_api.py", line 220, in __enter__
    self.acquire()
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/filelock/_api.py", line 173, in acquire
    self._acquire()
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/filelock/_unix.py", line 35, in _acquire
    fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/cluster-default.lock'
```

### Versions / Dependencies

```yaml
name: puma-lab
channels:
  - intel
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hb9a14ef_9
  - ca-certificates=2022.3.18=h06a4308_0
  - certifi=2021.10.8=py38h06a4308_2
  - intelpython=2022.1.0=0
  - libffi=3.3=14
  - libgcc-ng=9.3.0=hdf63c60_101
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1n=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - python=3.8.12=h70b2ee3_6
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py38h06a4308_0
  - sqlite=3.38.0=hc218d9a_0
  - tk=8.6.10=h8e2d9d6_3
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h74280d8_2
  - zlib=1.2.11.1=h1e99aa7_5
  - pip:
    - aiohttp==3.8.1
    - aiohttp-cors==0.7.0
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - attrs==21.4.0
    - blessed==1.19.1
    - cachetools==5.2.0
    - charset-normalizer==2.0.12
    - click==8.1.3
    - colorful==0.5.4
    - distlib==0.3.4
    - filelock==3.7.1
    - frozenlist==1.3.0
    - google-api-core==2.8.1
    - google-auth==2.6.6
    - googleapis-common-protos==1.56.2
    - gpustat==1.0.0b1
    - grpcio==1.43.0
    - idna==3.3
    - importlib-resources==5.7.1
    - jsonschema==4.5.1
    - msgpack==1.0.3
    - multidict==6.0.2
    - numpy==1.22.4
    - nvidia-ml-py3==7.352.0
    - opencensus==0.9.0
    - opencensus-context==0.1.2
    - platformdirs==2.5.2
    - prometheus-client==0.13.1
    - protobuf==3.20.1
    - py-spy==0.3.12
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyrsistent==0.18.1
    - pyyaml==6.0
    - ray==1.12.1
    - requests==2.27.1
    - rsa==4.8
    - six==1.16.0
    - smart-open==6.0.0
    - urllib3==1.26.9
    - virtualenv==20.14.1
    - wcwidth==0.2.5
    - yarl==1.7.2
    - zipp==3.8.0
```

### Reproduction script

```bash
conda create -n puma-lab python=3.8 -y
conda activate puma-lab
pip install ray[default]
conda env export > env.yaml
ray up --no-config-cache examples/ray_cluster.yaml  -y
Usage stats collection will be enabled by default in the next release. See https://github.com/ray-project/ray/issues/20857 for more details.
Cluster: default

Checking Local environment settings
Traceback (most recent call last):
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/ray/scripts/scripts.py", line 2269, in main
    return cli()
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/ray/autoscaler/_private/cli_logger.py", line 808, in wrapper
    return f(*args, **kwargs)
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1158, in up
    create_or_update_cluster(
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 276, in create_or_update_cluster
    get_or_create_head_node(
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 633, in get_or_create_head_node
    provider = _provider or _get_node_provider(
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/ray/autoscaler/_private/providers.py", line 242, in _get_node_provider
    new_provider = provider_cls(provider_config, cluster_name)
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/ray/autoscaler/_private/local/node_provider.py", line 185, in __init__
    self.state = ClusterState(
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/ray/autoscaler/_private/local/node_provider.py", line 36, in __init__
    with self.file_lock:
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/filelock/_api.py", line 220, in __enter__
    self.acquire()
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/filelock/_api.py", line 173, in acquire
    self._acquire()
  File "/home/toaster/mambaforge-pypy3/envs/puma-lab/lib/python3.8/site-packages/filelock/_unix.py", line 35, in _acquire
    fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/cluster-default.lock'
```

### Issue Severity

Medium

**Comment by flanaman** [comment]
I see the same issue, Note that `mkdir /tmp/ray` is another workaround.
