### ISSUE TITLE
[Ray Dataset] JaxTrainer Dataset 

### ISSUE THREAD

**Issue by JiahaoYao** [ray-project/ray#25382]
### What happened + What you expected to happen

One issue happens during the jax dataset implementation. 

If I add these lines between https://github.com/ray-project/ray/blob/master/python/ray/_private/function_manager.py#L626-L627

```python 
import jax 
import jax.numpy as jnp
```

the code works, otherwise the error reports 

```python
(raylet, ip=10.0.2.157) 2022-06-01 23:01:45,177 INFO context.py:70 -- Exec'ing worker with command: exec /home/ubuntu/anaconda3/envs/tensorflow2_p38/bin/python /home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/workers/default_worker.py --node-ip-address=10.0.2.157 --node-manager-port=45359 --object-store-name=/tmp/ray/session_2022-06-01_22-25-45_946104_10171/sockets/plasma_store --raylet-name=/tmp/ray/session_2022-06-01_22-25-45_946104_10171/sockets/raylet --redis-address=None --storage=None --temp-dir=/tmp/ray --metrics-agent-port=49747 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.0.2.140:6379 --redis-password=5241590000000000 --startup-token=13 --runtime-env-hash=-674568276
2022-06-01 23:01:45,925 WARNING worker.py:1416 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 658, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 699, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 665, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 669, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 616, in ray._raylet.execute_task.function_executor
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/function_manager.py", line 681, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/function_manager.py", line 589, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name TrainTrainable failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/function_manager.py", line 634, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'ray.ml.train.integrations.jax'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 799, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 618, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 740, in ray._raylet.execute_task
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/function_manager.py", line 589, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name TrainTrainable failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/function_manager.py", line 634, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'ray.ml.train.integrations.jax'

An unexpected internal error occurred while the worker was executing a task.
(TemporaryActor pid=16544, ip=10.0.2.157) 2022-06-01 23:01:45,922       ERROR worker.py:451 -- SystemExit was raised from the worker.
(TemporaryActor pid=16544, ip=10.0.2.157) Traceback (most recent call last):
(TemporaryActor pid=16544, ip=10.0.2.157)   File "python/ray/_raylet.pyx", line 658, in ray._raylet.execute_task
(TemporaryActor pid=16544, ip=10.0.2.157)   File "python/ray/_raylet.pyx", line 699, in ray._raylet.execute_task
(TemporaryActor pid=16544, ip=10.0.2.157)   File "python/ray/_raylet.pyx", line 665, in ray._raylet.execute_task
(TemporaryActor pid=16544, ip=10.0.2.157)   File "python/ray/_raylet.pyx", line 669, in ray._raylet.execute_task
(TemporaryActor pid=16544, ip=10.0.2.157)   File "python/ray/_raylet.pyx", line 616, in ray._raylet.execute_task.function_executor
(TemporaryActor pid=16544, ip=10.0.2.157)   File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/function_manager.py", line 681, in actor_method_executor
(TemporaryActor pid=16544, ip=10.0.2.157)     return method(__ray_actor, *args, **kwargs)
(TemporaryActor pid=16544, ip=10.0.2.157)   File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/function_manager.py", line 589, in temporary_actor_method
(TemporaryActor pid=16544, ip=10.0.2.157)     raise RuntimeError(
(TemporaryActor pid=16544, ip=10.0.2.157) RuntimeError: The actor with name TrainTrainable failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:
(TemporaryActor pid=16544, ip=10.0.2.157) 
(TemporaryActor pid=16544, ip=10.0.2.157) Traceback (most recent call last):
(TemporaryActor pid=16544, ip=10.0.2.157)   File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/function_manager.py", line 634, in _load_actor_class_from_gcs
(TemporaryActor pid=16544, ip=10.0.2.157)     actor_class = pickle.loads(pickled_class)
(TemporaryActor pid=16544, ip=10.0.2.157) ModuleNotFoundError: No module named 'ray.ml.train.integrations.jax'
(TemporaryActor pid=16544, ip=10.0.2.157) 
(TemporaryActor pid=16544, ip=10.0.2.157) 
(TemporaryActor pid=16544, ip=10.0.2.157) During handling of the above exception, another exception occurred:
(TemporaryActor pid=16544, ip=10.0.2.157) 
(TemporaryActor pid=16544, ip=10.0.2.157) Traceback (most recent call last):
(TemporaryActor pid=16544, ip=10.0.2.157)   File "python/ray/_raylet.pyx", line 799, in ray._raylet.task_execution_handler
(TemporaryActor pid=16544, ip=10.0.2.157)   File "python/ray/_raylet.pyx", line 618, in ray._raylet.execute_task
(TemporaryActor pid=16544, ip=10.0.2.157)   File "python/ray/_raylet.pyx", line 740, in ray._raylet.execute_task
(TemporaryActor pid=16544, ip=10.0.2.157)   File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/function_manager.py", line 589, in temporary_actor_method
(TemporaryActor pid=16544, ip=10.0.2.157)     raise RuntimeError(
(TemporaryActor pid=16544, ip=10.0.2.157) RuntimeError: The actor with name TrainTrainable failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:
(TemporaryActor pid=16544, ip=10.0.2.157) 
(TemporaryActor pid=16544, ip=10.0.2.157) Traceback (most recent call last):
(TemporaryActor pid=16544, ip=10.0.2.157)   File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/function_manager.py", line 634, in _load_actor_class_from_gcs
(TemporaryActor pid=16544, ip=10.0.2.157)     actor_class = pickle.loads(pickled_class)
(TemporaryActor pid=16544, ip=10.0.2.157) ModuleNotFoundError: No module named 'ray.ml.train.integrations.jax'
(TemporaryActor pid=16544, ip=10.0.2.157) 
(TemporaryActor pid=16544, ip=10.0.2.157) 
(TemporaryActor pid=16544, ip=10.0.2.157) During handling of the above exception, another exception occurred:
(TemporaryActor pid=16544, ip=10.0.2.157) 
(TemporaryActor pid=16544, ip=10.0.2.157) Traceback (most recent call last):
(TemporaryActor pid=16544, ip=10.0.2.157)   File "python/ray/_raylet.pyx", line 828, in ray._raylet.task_execution_handler
(TemporaryActor pid=16544, ip=10.0.2.157) SystemExit
2022-06-01 23:01:46,110 WARNING worker.py:1416 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff9cf25e383ee3a96e65e6b6bf0c000000 Worker ID: 877bd3cdce23193c0945d09f67047c95d1a2bae03ab31e99d1ae653b Node ID: 63a1897b4df5f00add191a8cb20adfb9bdcec073b1f1893d688c7791 Worker IP address: 10.0.2.157 Worker port: 10015 Worker PID: 16544
== Status ==
Current time: 2022-06-01 23:01:46 (running for 00:00:02.05)
Memory usage on this node: 1.6/15.3 GiB
Using FIFO scheduling algorithm.
Resources requested: 2.0/16 CPUs, 1.0/4 GPUs, 0.0/42.45 GiB heap, 0.0/17.88 GiB objects (0.0/4.0 accelerator_type:T4)
Result logdir: /home/ubuntu/ray_results/JaxTrainer_2022-06-01_23-01-43
Number of trials: 1/1 (1 RUNNING)
+------------------------+----------+-------+
| Trial name             | status   | loc   |
|------------------------+----------+-------|
| JaxTrainer_cdf62_00000 | RUNNING  |       |
+------------------------+----------+-------+


2022-06-01 23:01:46,114 ERROR trial_runner.py:886 -- Trial JaxTrainer_cdf62_00000: Error processing event.
NoneType: None
Result for JaxTrainer_cdf62_00000:
  trial_id: cdf62_00000
  
== Status ==
Current time: 2022-06-01 23:01:46 (running for 00:00:02.05)
Memory usage on this node: 1.6/15.3 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/16 CPUs, 0/4 GPUs, 0.0/42.45 GiB heap, 0.0/17.88 GiB objects (0.0/4.0 accelerator_type:T4)
Result logdir: /home/ubuntu/ray_results/JaxTrainer_2022-06-01_23-01-43
Number of trials: 1/1 (1 ERROR)
+------------------------+----------+-------+
| Trial name             | status   | loc   |
|------------------------+----------+-------|
| JaxTrainer_cdf62_00000 | ERROR    |       |
+------------------------+----------+-------+
Number of errored trials: 1
+------------------------+--------------+----------------------------------------------------------------------------------------------------------------+
| Trial name             |   # failures | error file                                                                                                     |
|------------------------+--------------+----------------------------------------------------------------------------------------------------------------|
| JaxTrainer_cdf62_00000 |            1 | /home/ubuntu/ray_results/JaxTrainer_2022-06-01_23-01-43/JaxTrainer_cdf62_00000_0_2022-06-01_23-01-44/error.txt |
+------------------------+--------------+----------------------------------------------------------------------------------------------------------------+

2022-06-01 23:01:46,118 ERROR ray_trial_executor.py:107 -- An exception occurred when trying to stop the Ray actor:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 98, in post_stop_cleanup
    ray.get(future, timeout=0)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/worker.py", line 1845, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
        class_name: Trainer.as_trainable.<locals>.TrainTrainable
        actor_id: 9cf25e383ee3a96e65e6b6bf0c000000
        pid: 16544
        namespace: 84ae81a0-cfab-4657-a648-f9d0cd76cd35
        ip: 10.0.2.157
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR_EXIT

2022-06-01 23:01:46,221 ERROR tune.py:748 -- Trials did not complete: [JaxTrainer_cdf62_00000]
2022-06-01 23:01:46,221 INFO tune.py:752 -- Total run time: 2.74 seconds (2.05 seconds for the tuning loop).
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/ml/trainer.py", line 332, in fit
    raise result.error
ray.tune.error.TuneError: Failure # 1 (occurred at 2022-06-01_23-01-46)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 934, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/worker.py", line 1845, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
        class_name: Trainer.as_trainable.<locals>.TrainTrainable
        actor_id: 9cf25e383ee3a96e65e6b6bf0c000000
        pid: 16544
        namespace: 84ae81a0-cfab-4657-a648-f9d0cd76cd35
        ip: 10.0.2.157
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR_EXIT



The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/jaxtrainer/test_trainer/test_ray_dataset_remote_jax_ttexample.py", line 56, in <module>
    result = trainer.fit()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/ml/trainer.py", line 334, in fit
    raise TrainingFailedError from e
ray.ml.trainer.TrainingFailedError
```

### Versions / Dependencies

Jax

### Reproduction script

reproduce code

```python
import ray
import tensorflow as tf
import tensorflow_datasets as tfds

ray.init("auto")

tf.config.experimental.set_visible_devices([], "GPU")


import jax
import jax.numpy as jnp
import numpy as np
import ray.data

a = 5
b = 10
size = 1000
items = [i / size for i in range(size)]
dataset = ray.data.from_items([{"x": x, "y": a * x + b} for x in items])


from ray import train
from ray.train.tensorflow import prepare_dataset_shard


def worker(config):
    # not sure how to use the dataset here
    dataset_shard = train.get_dataset_shard("train")
    dataset_shard = dataset_shard.to_jax(
        feature_columns=["x"],
        label_column="y",
        batch_size=config["batch_size"],
        unsqueeze_feature_tensors=False,
        unsqueeze_label_tensor=False,
    )

    dataset_shard = list(dataset_shard)
    print(len(dataset_shard))
    print(len(dataset_shard[0][0]))

from ray.ml.train.integrations.jax import JaxTrainer

trainer = JaxTrainer(
    train_loop_per_worker=worker,
    train_loop_config={"batch_size": 5},
    datasets={"train": dataset},
    scaling_config={"num_workers": 1, "use_gpu": True},
)


result = trainer.fit()

```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by dynamicwebpaige** [comment]
That's a very gnarly error message... 😅

**Comment by clarkzinzow** [comment]
cc @suquark looks like another spooky pickle issue. Does Jax package pickle5 or something weird?
