### ISSUE TITLE
[Ray Serve] Batching with json data

### ISSUE THREAD

**Issue by litttl** [ray-project/ray#25398]
### What happened + What you expected to happen

I want to use batching in ray serve. My data is json-format
When I use the data as following, I got some error. ex: `a = ({"res": (request.json())['data']})`
While I use the await before data, There is no error but no batching. ex: `a = ({"res": await (request.json())['data']})`
How can I use batching in ray serve with json?

### Versions / Dependencies

python3.7/python3.8
ubuntu
ray1.12.1

### Reproduction script

codes:
```python
@serve.deployment(route_prefix="/test", num_replicas=2)
class Detector():
    @serve.batch(max_batch_size=16, batch_wait_timeout_s=10)
    async def handle_batch(self, requests: List):
        results = []
        for request in requests:
            a = ({"res": (request.json())['data']})
            results.append(a)
        return results
    async def __call__(self, request):
        return await self.handle_batch(request)

if __name__ == "__main__":
    ray.init(address="auto", namespace="serve")
    serve.start(detached=True, http_options={"host":'0.0.0.0', "port": 9982})
    Detector.deploy()

```

error:
```python-traceback
Traceback (most recent call last):
  File "test_client.py", line 54, in <module>
    main()
  File "test_client.py", line 48, in main
    print(response.json())
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] Task Error. Traceback: ray::Detector (pid=34287, ip=172.17.0.2)
  File "/usr/local/lib/python3.8/dist-packages/ray/serve/utils.py", line 243, in wrap_to_ray_error
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/ray/serve/replica.py", line 396, in invoke_single
    result = await method_to_call(*args, **kwargs)
  File "test_batch_serve.py", line 39, in __call__
    return await self.handle_batch(request)
  File "/usr/local/lib/python3.8/dist-packages/ray/serve/batching.py", line 296, in batch_wrapper
    return await future
  File "/usr/local/lib/python3.8/dist-packages/ray/serve/batching.py", line 141, in _handle_batches
    results = await func(self_arg, *args, **kwargs)
  File "test_batch_serve.py", line 31, in handle_batch
    a = ({"res": (request.json())['data']})
```

**Comment by shrekris-anyscale** [comment]
I did some digging– here are some observations:

* You do need to `await` the `request.json()` in the deployment. `request.json()` returns a coroutine object that needs to be awaited to get json data that can be sent back over the wire. The syntax for that line (note the parentheses) should be:

```python
a = ({"res": (await request.json())['data']})
```

* I was able to observe batching happening even with the `await`. Here's my modified repro:

```python
from typing import List

import ray
from ray import serve

@serve.deployment(route_prefix="/test")
class Detector():
    @serve.batch(max_batch_size=16, batch_wait_timeout_s=4)
    async def handle_batch(self, requests: List):
        results = []
        for request in requests:
            a = {"res": (await request.json())['data'], "len": len(requests)}
            results.append(a)
        return results
    async def __call__(self, request):
        return await self.handle_batch(request)

if __name__ == "__main__":
    ray.init(address="auto", namespace="serve")
    serve.start(detached=True, http_options={"host":'0.0.0.0', "port": 9982})
    Detector.deploy()
```

The `"len"` key in the return value indicates the batch size. Note that I reduced the `num_replicas` to 1 to make it easier to check for batching. With `num_replicas=2`, I believe that requests may get routed either replica, making it harder to detect batching.

Then, I set up two separate Python interpreters. In the first one, I ran:

```python
r = requests.post("http://localhost:9982/test", json={"data": 3})
```

and in the second I ran:

```python
r = requests.post("http://localhost:9982/test", json={"data": 5})
```

I ran these lines in quick succession repeatedly, and I observed the following output. In the first interpreter:

```powershell
>>> r = requests.post("http://localhost:9982/test", json={"data": 3})
>>> r.json()
{'res': 3, 'len': 2}
```

and in the second interpreter:

```powershell
>>> r = requests.post("http://localhost:9982/test", json={"data": 5})
>>> r.json()
{'res': 5, 'len': 2}
```

Since `"len"` is 2, we know that batching is happening.
