### ISSUE TITLE
[runtime env] Exception raised when `.sock` files are in working_dir

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#25411]
```
$ ray job submit --runtime-env-json='{"working_dir": "./", "pip": ["requests==2.26.0"]}' -- "python script.py"
Job submission server address: http://127.0.0.1:8265
2022-06-02 00:34:53,279    ERROR packaging.py:84 -- Issue with path: /Users/gauta/.docker/run/docker-cli-api.sock
Traceback (most recent call last):
  File "/usr/local/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/ray/scripts/scripts.py", line 1958, in main
    return cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ray/autoscaler/_private/cli_logger.py", line 808, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ray/dashboard/modules/job/cli.py", line 151, in job_submit
    job_id = client.submit_job(
  File "/usr/local/lib/python3.9/site-packages/ray/dashboard/modules/job/sdk.py", line 255, in submit_job
    self._upload_working_dir_if_needed(runtime_env)
  File "/usr/local/lib/python3.9/site-packages/ray/dashboard/modules/job/sdk.py", line 232, in _upload_working_dir_if_needed
    package_uri = self._upload_package_if_needed(
  File "/usr/local/lib/python3.9/site-packages/ray/dashboard/modules/job/sdk.py", line 211, in _upload_package_if_needed
    package_uri = get_uri_for_directory(package_path, excludes=excludes)
  File "/usr/local/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 333, in get_uri_for_directory
    hash_val = _hash_directory(directory, directory,
  File "/usr/local/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 121, in _hash_directory
    _dir_travel(root, excludes, handler, logger=logger)
  File "/usr/local/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 88, in _dir_travel
    _dir_travel(sub_path, excludes, handler, logger=logger)
  File "/usr/local/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 88, in _dir_travel
    _dir_travel(sub_path, excludes, handler, logger=logger)
  File "/usr/local/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 88, in _dir_travel
    _dir_travel(sub_path, excludes, handler, logger=logger)
  File "/usr/local/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 85, in _dir_travel
    raise e
  File "/usr/local/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 82, in _dir_travel
    handler(path)
  File "/usr/local/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 112, in handler
    with path.open("rb") as f:
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
OSError: [Errno 102] Operation not supported on socket: '/Users/gauta/.docker/run/docker-cli-api.sock'
```
Thanks for finding the root cause, this is an interesting edge case... We `.open()` the files so that we can read the contents and hash them.  We use the hash to prevent reuploading the working_dir when it's already been uploaded.

I think you're right that the solution is to skip over files that raise an exception when `.open()` is called.

_Originally posted by @architkulkarni in https://github.com/ray-project/kuberay/issues/283#issuecomment-1145277065_

**Comment by architkulkarni** [comment]
Skipping over unopenable files has the downside that the user might change their working_dir by adding/removing unopenable files, but the hash will be the same so the old working_dir will remain on the cluster without being replaced.  

But I'm not sure how common this situation is...  And if the files can't be opened, there probably isn't any need for them to be uploaded as part of the `working_dir` (how would they be used on the cluster?)
