### ISSUE TITLE
[Dashboard] Error during render node with gpu and 4 hdds 

### ISSUE THREAD

**Issue by gawsoftpl** [ray-project/ray#25437]
### What happened + What you expected to happen

After add new worker with 4 hdds and one GPU I received error in React dashboard:

TypeError: Cannot read properties of undefined (reading '/')
    at NodeInfo.tsx:220:42
    at Array.filter (<anonymous>)
    at _n (NodeInfo.tsx:220:26)
    at Xi (react-dom.production.min.js:153:146)
    at Go (react-dom.production.min.js:175:309)
    at ys (react-dom.production.min.js:263:406)
    at El (react-dom.production.min.js:246:265)
    at fl (react-dom.production.min.js:246:194)
    at sl (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115

source: NodeInfo.tsx:220:42
  // Don't show disk on Kubernetes. K8s node disk usage should be monitored
  // elsewhere.
  // If a Ray node is running in a K8s pod, it marks available disk as 1 byte.
  // (See ReporterAgent._get_disk_usage() in reporter_agent.py)
  // Check if there are any nodes with realistic disk total:
  const showDisk = nodes.filter((n) => n.disk["/"].total > 10).length !== 0;

### Versions / Dependencies

Ray 1.12.1
Python 3.9.5

### Reproduction script

On head machine:
ray start --head --port=6379 --node-ip-address=192.168.1.8 --dashboard-host=0.0.0.0

On worker machine:
ray start --address='192.168.1.8:6379'

**Comment by scottsun94** [comment]
@gawsoftpl In ray 2.0, we made the previous experimental dashboard the default dashboard. Are you still running into this issue if you switch to ray 2.0?

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
