### ISSUE TITLE
[Ray Dataset] `to_tf` squeeze error when the tensor can not squeeze

### ISSUE THREAD

**Issue by JiahaoYao** [ray-project/ray#25554]
### What happened + What you expected to happen

https://github.com/ray-project/ray/blob/3876fcdbe80dca18138d0812c2d3aef0cea510b5/python/ray/data/dataset.py#L2547-L2550

when the targets tensor can not squeeze the `axis=1` dimension, there is an error

```python 
*** tensorflow.python.framework.errors_impl.InvalidArgumentError: Can not squeeze dim[1], expected a dimension of 1, got 784 [Op:Squeeze]
```

https://github.com/ray-project/ray/blob/3fdcfc9f123c8a44dd0414658e6909222a0dcaaa/python/ray/air/_internal/tensorflow_utils.py#L31-L42

Here is a small MWE for this 
```python
import pandas as pd
from ray.air._internal.tensorflow_utils  import convert_pandas_to_tf_tensor
from ray.data.extensions import TensorArray
import tensorflow as tf
import numpy as np

df = pd.DataFrame({"image": TensorArray(np.zeros((4, 3, 32, 32)))})
targets = convert_pandas_to_tf_tensor(df)
targets = tf.squeeze(targets, axis=1) 
```

the outputs are 
```python
Traceback (most recent call last):
  File "test_tf_tensor.py", line 12, in <module>
    targets = tf.squeeze(targets, axis=1) 
  File "/home/ray/anaconda3/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ray/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 7164, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Can not squeeze dim[1], expected a dimension of 1, got 3 [Op:Squeeze]
```

@bveeramani 

### Versions / Dependencies

N?A

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by bveeramani** [comment]
Currently, `to_tf` assumes that labels are integers, but labels in the auto-encoder example are multi-dimensional tensors.

https://github.com/ray-project/ray/blob/5edf0d446686a7ba3de37b9c34be4eb2e5b6c8e3/python/ray/air/examples/tf/tensorflow_autoencoder_example.py#L55-L57

I'm okay with adding the proposed code snippet to unblock the example. Once we figure out unsqueezing semantics, I'm sure we can come up with a robust solution.

```python
                if label_column:
                    targets = convert_pandas_to_tf_tensor(batch[[label_column]])
                    if targets.ndim == 2 and targets.shape[1] == 1: 
                        targets = tf.squeeze(targets, axis=1)
                    batch.pop(label_column)
```

@clarkzinzow what do you think?

**Comment by JiahaoYao** [comment]
@clarkzinzow can i just make a PR for this?

**Comment by clarkzinzow** [comment]
Sorry for missing the mention, yes this seems like a great fix!

This is fixed by this PR that I just merged, right? https://github.com/ray-project/ray/pull/25553

**Comment by JiahaoYao** [comment]
Yes, thank you @clarkzinzow
