### ISSUE TITLE
Ray install

### ISSUE THREAD

**Issue by microprediction** [ray-project/ray#25552]
### What happened + What you expected to happen

Install Ray on Big Sur 11.6

        pip install -U ray
        python3
        >> import ray

        
        Traceback (most recent call last):
          File "<stdin>", line 1, in <module>
          File "/Users/petercotton/virtual-envs/snow/lib/python3.8/site-packages/ray/__init__.py", line 108, in <module>
            import ray._raylet  # noqa: E402
          File "python/ray/_raylet.pyx", line 16, in init ray._raylet
        ImportError: dlopen(/Users/petercotton/virtual-envs/snow/lib/python3.8/site-packages/ray/thirdparty_files/setproctitle.cpython-38-darwin.so, 2): Symbol not found: _Py_GetArgcArgv
          Referenced from: /Users/petercotton/virtual-envs/snow/lib/python3.8/site-packages/ray/thirdparty_files/setproctitle.cpython-38-darwin.so
          Expected in: flat namespace
         in /Users/petercotton/virtual-envs/snow/lib/python3.8/site-packages/ray/thirdparty_files/setproctitle.cpython-38-darwin.so

    

### Versions / Dependencies

ray==1.12.1
Python 3.8.2

### Reproduction script

import ray

**Comment by microprediction** [comment]
Similar. 

              >>> import ray
              Traceback (most recent call last):
                File "<stdin>", line 1, in <module>
                File "/Users/petercotton/virtual-envs/ray/lib/python3.9/site-packages/ray/__init__.py", line 108, in <module>
                  import ray._raylet  # noqa: E402
                File "python/ray/_raylet.pyx", line 115, in init ray._raylet
                File "/Users/petercotton/virtual-envs/ray/lib/python3.9/site-packages/ray/exceptions.py", line 7, in <module>
                  from ray.core.generated.common_pb2 import RayException, Language, PYTHON
                File "/Users/petercotton/virtual-envs/ray/lib/python3.9/site-packages/ray/core/generated/common_pb2.py", line 15, in <module>
                  from . import runtime_env_common_pb2 as src_dot_ray_dot_protobuf_dot_runtime__env__common__pb2
                File "/Users/petercotton/virtual-envs/ray/lib/python3.9/site-packages/ray/core/generated/runtime_env_common_pb2.py", line 36, in <module>
                  _descriptor.FieldDescriptor(
                File "/Users/petercotton/virtual-envs/ray/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
                  _message.Message._CheckCalledFromGeneratedFile()
              TypeError: Descriptors cannot not be created directly.
              If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
              If you cannot immediately regenerate your protos, some other possible workarounds are:
               1. Downgrade the protobuf package to 3.20.x or lower.
               2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
              
              More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by Yard1** [comment]
@microprediction Try `pip install -U "protobuf<4" ray`. This should be fixed in the upcoming 1.13 release.

**Comment by microprediction** [comment]
Thank you. Works fine. Not the first time I'd tripped on the protobuf release.
