### ISSUE TITLE
[Ray Dataset] Add the attributes of `dtype` to TensorArray

### ISSUE THREAD

**Issue by JiahaoYao** [ray-project/ray#25556]
### Description

Currently for a TensorArray datatensor
```python
ipdb> p type(df['label'][0])
<class 'ray.data.extensions.tensor_extension.TensorArray'>
ipdb> p df['label'][0].dtype
<ray.data.extensions.tensor_extension.TensorDtype object at 0x7fdabc75e760>
```

The dtype is `object`, thus when are doing 

```python 
import pandas as pd
from ray.data.extensions import TensorArray
import tensorflow as tf
import numpy as np

df = pd.DataFrame({"image": TensorArray(np.zeros((4, 3, 32, 32)))})
print(df.dtypes)
```

The output is 
```python
image    TensorDtype
dtype: object
```

Ideally, we want this to gives the `dtypes` of `np.float32`. 

The issue of the `object` is in the following code, the `common_dtype` is set to be `object`. Then, it report error when `tf.convert_to_tensor(series, dtype=object)`. However, it will pass when `tf.convert_to_tensor(series, dtype=np.float32)`

https://github.com/ray-project/ray/blob/3fdcfc9f123c8a44dd0414658e6909222a0dcaaa/python/ray/air/_internal/tensorflow_utils.py#L44-L59

@bveeramani @clarkzinzow

**Comment by JiahaoYao** [comment]
The MWE is 

```python
import pandas as pd
from ray.data.extensions import TensorArray
import tensorflow as tf
import numpy as np
from typing import Optional

import numpy as np
import pandas as pd
import tensorflow as tf


def convert_pandas_to_tf_tensor(
    df: pd.DataFrame, dtype: Optional[tf.dtypes.DType] = None
) -> tf.Tensor:
    """Convert a pandas dataframe to a TensorFlow tensor.

    This function works in two steps:
    1. Convert each dataframe column to a tensor.
    2. Concatenate the resulting tensors along the last axis.

    Arguments:
        df: The dataframe to convert to a TensorFlow tensor. Columns must be of
            a numeric dtype, ``TensorDtype``, or object dtype. If a column has
            an object dtype, the column must contain ``ndarray`` objects.
        dtype: Optional data type for the returned tensor. If a dtype isn't
            provided, the dtype is inferred from ``df``.

    Returns:
        A tensor constructed from the dataframe.

    Examples:
        >>> import pandas as pd
        >>> from ray.air.utils.tensorflow_utils improt convert_pandas_to_tf_tensor
        >>>
        >>> df = pd.DataFrame({"X1": [1, 2, 3], "X2": [4, 5, 6]})
        >>> convert_pandas_to_tf_tensor(df[["X1"]]).shape
        TensorShape([3, 1])
        >>> convert_pandas_to_tf_tensor(df[["X1", "X2"]]).shape
        TensorShape([3, 2])

        >>> from ray.data.extensions import TensorArray
        >>>
        >>> df = pd.DataFrame({"image": TensorArray(np.zeros((4, 3, 32, 32)))})
        >>> convert_pandas_to_tf_tensor(df).shape
        TensorShape([4, 3, 32, 32])
    """
    if dtype is None:
        try:
            # We need to cast the tensors to a common type so that we can concatenate
            # them. If the columns contain different types (for example, `float32`s
            # and `int32`s), then `tf.concat` raises an error.
            dtype: np.dtype = np.find_common_type(df.dtypes, [])
        except TypeError:
            # `find_common_type` fails if a series has `TensorDtype`. In this case,
            # don't cast any of the series and continue.
            pass

    def tensorize(series):
        try:
            return tf.convert_to_tensor(series, dtype)
        except:
            return tf.stack([tensorize(element) for element in series])

    tensors = []
    for column in df.columns:
        series = df[column]
        tensor = tensorize(series)
        tensors.append(tensor)

    if len(tensors) > 1:
        tensors = [tf.expand_dims(tensor, axis=1) for tensor in tensors]

    concatenated_tensor = tf.concat(tensors, axis=1)

    if concatenated_tensor.ndim == 1:
        return tf.expand_dims(concatenated_tensor, axis=1)

    return concatenated_tensor


image = np.zeros((5,))
df = pd.DataFrame({"image": [TensorArray(image), TensorArray(image)]})
targets = convert_pandas_to_tf_tensor(df)
print(targets)
```


```python
Traceback (most recent call last):
  File "tensor_pd_tensorArray.py.py", line 60, in tensorize
    return tf.convert_to_tensor(series, dtype)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ray/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 102, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensor_pd_tensorArray.py.py", line 83, in <module>
    targets = convert_pandas_to_tf_tensor(df)
  File "tensor_pd_tensorArray.py.py", line 67, in convert_pandas_to_tf_tensor
    tensor = tensorize(series)
  File "tensor_pd_tensorArray.py.py", line 62, in tensorize
    return tf.stack([tensorize(element) for element in series])
  File "tensor_pd_tensorArray.py.py", line 62, in <listcomp>
    return tf.stack([tensorize(element) for element in series])
  File "tensor_pd_tensorArray.py.py", line 62, in tensorize
    return tf.stack([tensorize(element) for element in series])
  File "tensor_pd_tensorArray.py.py", line 62, in <listcomp>
    return tf.stack([tensorize(element) for element in series])
  File "tensor_pd_tensorArray.py.py", line 62, in tensorize
    return tf.stack([tensorize(element) for element in series])
TypeError: 'numpy.float64' object is not iterable
```


```python
import pandas as pd
from ray.data.extensions import TensorArray
import tensorflow as tf
import numpy as np
from typing import Optional

import numpy as np
import pandas as pd
import tensorflow as tf


def convert_pandas_to_tf_tensor(
    df: pd.DataFrame, dtype: Optional[tf.dtypes.DType] = None
) -> tf.Tensor:
    """Convert a pandas dataframe to a TensorFlow tensor.

    This function works in two steps:
    1. Convert each dataframe column to a tensor.
    2. Concatenate the resulting tensors along the last axis.

    Arguments:
        df: The dataframe to convert to a TensorFlow tensor. Columns must be of
            a numeric dtype, ``TensorDtype``, or object dtype. If a column has
            an object dtype, the column must contain ``ndarray`` objects.
        dtype: Optional data type for the returned tensor. If a dtype isn't
            provided, the dtype is inferred from ``df``.

    Returns:
        A tensor constructed from the dataframe.

    Examples:
        >>> import pandas as pd
        >>> from ray.air.utils.tensorflow_utils improt convert_pandas_to_tf_tensor
        >>>
        >>> df = pd.DataFrame({"X1": [1, 2, 3], "X2": [4, 5, 6]})
        >>> convert_pandas_to_tf_tensor(df[["X1"]]).shape
        TensorShape([3, 1])
        >>> convert_pandas_to_tf_tensor(df[["X1", "X2"]]).shape
        TensorShape([3, 2])

        >>> from ray.data.extensions import TensorArray
        >>>
        >>> df = pd.DataFrame({"image": TensorArray(np.zeros((4, 3, 32, 32)))})
        >>> convert_pandas_to_tf_tensor(df).shape
        TensorShape([4, 3, 32, 32])
    """
    if dtype is None:
        try:
            # We need to cast the tensors to a common type so that we can concatenate
            # them. If the columns contain different types (for example, `float32`s
            # and `int32`s), then `tf.concat` raises an error.
            dtype: np.dtype = np.find_common_type(df.dtypes, [])
        except TypeError:
            # `find_common_type` fails if a series has `TensorDtype`. In this case,
            # don't cast any of the series and continue.
            pass

    def tensorize(series):
        try:
            return tf.convert_to_tensor(series)
        except:
            return tf.stack([tensorize(element) for element in series])

    tensors = []
    for column in df.columns:
        series = df[column]
        tensor = tensorize(series)
        tensors.append(tensor)

    if len(tensors) > 1:
        tensors = [tf.expand_dims(tensor, axis=1) for tensor in tensors]

    concatenated_tensor = tf.concat(tensors, axis=1)

    if concatenated_tensor.ndim == 1:
        return tf.expand_dims(concatenated_tensor, axis=1)

    return concatenated_tensor


image = np.zeros((5,))
df = pd.DataFrame({"image": [TensorArray(image), TensorArray(image)]})
targets = convert_pandas_to_tf_tensor(df)
print(targets)
```

the output is 

```python
tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(2, 5), dtype=float64)
```

The change is 
from 
```python
    def tensorize(series):
        try:
            return tf.convert_to_tensor(series, dtype)
        except:
            return tf.stack([tensorize(element) for element in series])

```

to 

```python
            return tf.convert_to_tensor(series, dtype=np.float64)
```

or 

```python
            return tf.convert_to_tensor(series)
```

The issue is due to `dtype=object` from the inference.

**Comment by clarkzinzow** [comment]
We can't set the `dtype` of `TensorArray` to the underlying scalar element dtype, since that would break the extension type. I don't think that there's a way to get the tensor extensions to work well with NumPy's `np.find_common_dtype()` since NumPy's dtype system is unaware of extension types; I think instead we just need to have explicit logic checking for extension types.

**Comment by clarkzinzow** [comment]
Closing this since this should be solved at a higher level.
