### ISSUE TITLE
[Docs][Serve][KubeRay] Failure following instructions to deploy on Kubernetes (ValueError: Attempting to cap object store memory usage)

### ISSUE THREAD

**Issue by tdoublep** [ray-project/ray#25595]
### What happened + What you expected to happen

I am trying to deploy Ray Serve on top of Kubernetes following the instructions [here](https://docs.ray.io/en/latest/serve/deployment.html#deploying-on-kubernetes). 

- I create a new K8s cluster on Azure comprising 3 nodes (each node has 2 CPUs and 8GB memory). 
- I create a clean Anaconda env with latest ray from pip
- When I try to create the cluster using `ray up` and the [example yaml](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/kubernetes/example-full.yaml) unchanged, it fails.

These are the logs:
```bash
$ ray up example-full.yaml --no-config-cache
Usage stats collection will be enabled by default in the next release. See https://github.com/ray-project/ray/issues/20857 for more details.
Cluster: example-cluster

2022-06-08 20:31:28,146 INFO util.py:335 -- setting max workers for head node type to 0
Checking Kubernetes environment settings
2022-06-08 20:31:28,779 INFO config.py:223 -- KubernetesNodeProvider: namespace 'ray' not found, attempting to create it
2022-06-08 20:31:28,814 INFO config.py:226 -- KubernetesNodeProvider: successfully created namespace 'ray'
2022-06-08 20:31:28,843 INFO config.py:352 -- KubernetesNodeProvider: service 'example-cluster-ray-head' not found, attempting to create it
2022-06-08 20:31:28,885 INFO config.py:354 -- KubernetesNodeProvider: successfully created service 'example-cluster-ray-head'
2022-06-08 20:31:28,914 INFO config.py:254 -- KubernetesNodeProvider: autoscaler_service_account 'autoscaler' not found, attempting to create it
2022-06-08 20:31:28,946 INFO config.py:256 -- KubernetesNodeProvider: successfully created autoscaler_service_account 'autoscaler'
2022-06-08 20:31:29,055 INFO config.py:281 -- KubernetesNodeProvider: autoscaler_role 'autoscaler' not found, attempting to create it
2022-06-08 20:31:29,082 INFO config.py:283 -- KubernetesNodeProvider: successfully created autoscaler_role 'autoscaler'
2022-06-08 20:31:29,107 INFO config.py:317 -- KubernetesNodeProvider: autoscaler_role_binding 'autoscaler' not found, attempting to create it
2022-06-08 20:31:29,136 INFO config.py:319 -- KubernetesNodeProvider: successfully created autoscaler_role_binding 'autoscaler'
No head node found. Launching a new cluster. Confirm [y/N]: y

Acquiring an up-to-date head node
2022-06-08 20:31:31,039 INFO node_provider.py:144 -- KubernetesNodeProvider: calling create_namespaced_pod (count=1).
  Launched a new head node
  Fetching the new head node
  
<1/1> Setting up head node
  Prepared bootstrap config
  New status: waiting-for-ssh
  [1/7] Waiting for SSH to become available
    Running `uptime` as a test.
2022-06-08 20:31:31,222 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
    SSH still not available (Exit Status 1): kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)', retrying in 5 seconds.
2022-06-08 20:31:36,695 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
    SSH still not available (Exit Status 1): kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)', retrying in 5 seconds.
2022-06-08 20:31:42,161 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
    SSH still not available (Exit Status 1): kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)', retrying in 5 seconds.
2022-06-08 20:31:47,635 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
    SSH still not available (Exit Status 1): kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)', retrying in 5 seconds.
2022-06-08 20:31:53,092 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
    SSH still not available (Exit Status 1): kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)', retrying in 5 seconds.
2022-06-08 20:31:58,549 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
    SSH still not available (Exit Status 1): kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)', retrying in 5 seconds.
2022-06-08 20:32:04,003 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
    SSH still not available (Exit Status 1): kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)', retrying in 5 seconds.
2022-06-08 20:32:09,429 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
    SSH still not available (Exit Status 1): kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)', retrying in 5 seconds.
2022-06-08 20:32:14,817 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
    SSH still not available (Exit Status 1): kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)', retrying in 5 seconds.
2022-06-08 20:32:20,209 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
    SSH still not available (Exit Status 1): kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)', retrying in 5 seconds.
2022-06-08 20:32:25,633 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
    SSH still not available (Exit Status 1): kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)', retrying in 5 seconds.
2022-06-08 20:32:31,109 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
    SSH still not available (Exit Status 1): kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)', retrying in 5 seconds.
2022-06-08 20:32:36,533 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
    SSH still not available (Exit Status 1): kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)', retrying in 5 seconds.
2022-06-08 20:32:41,918 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
    SSH still not available (Exit Status 1): kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)', retrying in 5 seconds.
2022-06-08 20:32:47,313 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
    SSH still not available (Exit Status 1): kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)', retrying in 5 seconds.
2022-06-08 20:32:52,712 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
    SSH still not available (Exit Status 1): kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)', retrying in 5 seconds.
2022-06-08 20:32:58,093 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
error: unable to upgrade connection: container not found ("ray-node")
    SSH still not available (Exit Status 1): kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)', retrying in 5 seconds.
2022-06-08 20:33:03,517 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
 11:33:05 up 9 min,  0 users,  load average: 2.29, 1.23, 0.63
    Success.
  Updating cluster configuration. [hash=ca1ff770521fa3c971015ce81d8b50ff48a53487]
  New status: syncing-files
  [2/7] Processing file mounts
2022-06-08 20:33:05,547 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (mkdir -p ~)'
  [3/7] No worker file mounts to sync
  New status: setting-up
  [4/7] No initialization commands to run.
  [5/7] Initalizing command runner
  [6/7] No setup commands to run.
  [7/7] Starting the Ray runtime
2022-06-08 20:33:09,083 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (export RAY_OVERRIDE_RESOURCES='"'"'{"CPU":1,"GPU":0,"memory":375809638}'"'"';ray stop)'
Did not find any active Ray processes.
2022-06-08 20:33:12,197 INFO command_runner.py:179 -- NodeUpdater: example-cluster-ray-head-gsstg: Running kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (export RAY_OVERRIDE_RESOURCES='"'"'{"CPU":1,"GPU":0,"memory":375809638}'"'"';ulimit -n 65536; ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml --dashboard-host 0.0.0.0)'
Usage stats collection will be enabled by default in the next release. See https://github.com/ray-project/ray/issues/20857 for more details.
Local node IP: 10.244.1.2
2022-06-08 11:33:19,092 INFO services.py:1462 -- View the Ray dashboard at http://10.244.1.2:8265
Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 2269, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py", line 808, in wrapper
    return f(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 720, in start
    ray_params, head=True, shutdown_at_exit=block, spawn_reaper=block
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 301, in __init__
    self.start_ray_processes()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 1137, in start_ray_processes
    huge_pages=self._ray_params.huge_pages,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 2025, in determine_plasma_store_config
    object_store_memory, ray_constants.OBJECT_STORE_MINIMUM_MEMORY_BYTES
ValueError: Attempting to cap object store memory usage at 49158144 bytes, but the minimum allowed is 78643200 bytes.
command terminated with exit code 1
  New status: update-failed
  !!!
  Setup command `kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (export RAY_OVERRIDE_RESOURCES='"'"'{"CPU":1,"GPU":0,"memory":375809638}'"'"';ulimit -n 65536; ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml --dashboard-host 0.0.0.0)'` failed with exit code 1. stderr:
  !!!
  
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/ray-env/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/xxx/anaconda3/envs/ray-env/lib/python3.9/site-packages/ray/autoscaler/_private/updater.py", line 152, in run
    self.do_update()
  File "/home/xxx/anaconda3/envs/ray-env/lib/python3.9/site-packages/ray/autoscaler/_private/updater.py", line 508, in do_update
    self.cmd_runner.run(
  File "/home/xxx/anaconda3/envs/ray-env/lib/python3.9/site-packages/ray/autoscaler/_private/command_runner.py", line 184, in run
    self.process_runner.check_call(final_cmd, shell=True)
  File "/home/xxx/anaconda3/envs/ray-env/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'kubectl -n ray exec -it example-cluster-ray-head-gsstg -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (export RAY_OVERRIDE_RESOURCES='"'"'{"CPU":1,"GPU":0,"memory":375809638}'"'"';ulimit -n 65536; ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml --dashboard-host 0.0.0.0)'' returned non-zero exit status 1.
  Failed to setup head node.
  ```
I have read issues that seem related (e.g. #5811) which seems to indicate there is not enough memory, but each node in the cluster has 8GB which I was I understood to be the minimum requirement. 

Any help much appreciated! 

### Versions / Dependencies

Python: 3.9
OS: Ubuntu 18.04
Python libraries:
```
$ pip freeze
aiohttp==3.8.1
aiohttp-cors==0.7.0
aiorwlock==1.3.0
aiosignal==1.2.0
anyio==3.6.1
asgiref==3.5.2
async-timeout==4.0.2
attrs==21.4.0
blessed==1.19.1
cachetools==5.2.0
certifi==2022.5.18.1
charset-normalizer==2.0.12
click==8.1.3
colorful==0.5.4
distlib==0.3.4
fastapi==0.78.0
filelock==3.7.1
frozenlist==1.3.0
google-api-core==2.8.1
google-auth==2.7.0
googleapis-common-protos==1.56.2
gpustat==1.0.0b1
grpcio==1.43.0
h11==0.13.0
idna==3.3
jsonschema==4.6.0
kubernetes==23.6.0
msgpack==1.0.4
multidict==6.0.2
numpy==1.22.4
nvidia-ml-py3==7.352.0
oauthlib==3.2.0
opencensus==0.9.0
opencensus-context==0.1.2
platformdirs==2.5.2
prometheus-client==0.13.1
protobuf==3.20.1
psutil==5.9.1
py-spy==0.3.12
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydantic==1.9.1
pyrsistent==0.18.1
python-dateutil==2.8.2
PyYAML==6.0
ray==1.12.1
requests==2.27.1
requests-oauthlib==1.3.1
rsa==4.8
six==1.16.0
smart-open==6.0.0
sniffio==1.2.0
starlette==0.19.1
typing_extensions==4.2.0
urllib3==1.26.9
uvicorn==0.16.0
virtualenv==20.14.1
wcwidth==0.2.5
websocket-client==1.3.2
yarl==1.7.2
```
Kuberentes version:
```
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"07959215dd83b4ae6317b33c824f845abd578642", GitTreeState:"clean", BuildDate:"2022-03-30T18:28:25Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

### Reproduction script

Create K8s cluster on Azure:
```
az group create \
        --name=mygroup \
        --location=uksouth
```
```
az aks create \
        --name mycluster \
        --resource-group mygroup \
        --node-vm-size  Standard_D2_v3 \
        --node-count 3 \
        --generate-ssh-keys
```

Create Python environment:
```
conda create -n ray-env python=3.9
conda activate ray-env
pip install -U "ray[default]"
pip install -U "ray[serve]"
pip install kubernetes
```

Try to create ray cluster:
```
ray up ray/python/ray/autoscaler/kubernetes/example-full.yaml --no-config-cache
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by DmitriGekhtman** [comment]
Hi there, it looks like the portion of the docs that explains how to launch a cluster is outdated.
Please refer to the KubeRay docs instead for that part https://ray-project.github.io/kuberay/
We'll make sure to update the docs.

**Comment by DmitriGekhtman** [comment]
The docs have been updated.
