### ISSUE TITLE
[tune] Function Runner Runner Thread Error Message unrendered

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#2563]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Jenkins
- **Ray installed from (source or binary)**: Source
- **Ray version**: 
- **Python version**: 2.7
- **Exact command to reproduce**:
`python /ray/python/ray/tune/examples/hyperopt_example.py --smoke-test`
on 

### Describe the problem

Somehow, in Docker, error messages are swallowed, specifically when using Python multithreading. Specifically, the Runner thread error message is never shown.

### Source code / logs

```
+ docker run --rm --shm-size=10G --memory=10G bb427850711415df5de4ac39c92eb1b5ceb7037792c3b03e4a2c94681be0e61e python /ray/python/ray/tune/examples/hyperopt_example.py --smoke-test
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:12282 to respond...
Waiting for redis server at 127.0.0.1:14066 to respond...
Warning: Reducing object store memory because /dev/shm has only 10737418240 bytes available. You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
Starting local scheduler with the following resources: {'GPU': 0, 'CPU': 32}.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui95319.ipynb?token=f5e35e76ccedeed9f50da43fe84f434e09eea1762f8c48b5
======================================================================

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/ray/python/ray/tune/function_runner.py", line 75, in run
    raise e
AssertionError
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/ray/python/ray/tune/function_runner.py", line 75, in run
    raise e
AssertionError
...

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/ray/python/ray/tune/function_runner.py", line 75, in run
    raise e
AssertionError

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/ray/python/ray/tune/function_runner.py", line 75, in run
    raise e
AssertionError

Suppressing duplicate error message.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/ray/python/ray/tune/function_runner.py", line 75, in run
    raise e
AssertionError

method(actor, *args)
  File "/ray/python/ray/tune/trainable.py", line 117, in train
    result = self._train()
  File "/ray/python/ray/tune/function_runner.py", line 110, in _train
    result = self._status_reporter._get_and_clear_status()
  File "/ray/python/ray/tune/function_runner.py", line 39, in _get_and_clear_status
    raise TuneError("Error running trial: " + str(self._error))
TuneError: Error running trial: 


Worker ip unknown, skipping log sync for /root/ray_results/my_exp/exp_2018-08-04_03-57-23Xhw8pR
Created LogSyncer for /root/ray_results/my_exp/exp_2018-08-04_03-57-26dVRpSv -> 
Error processing event: Traceback (most recent call last):
  File "/ray/python/ray/tune/trial_runner.py", line 264, in _process_events
    result = ray.get(result_id)
  File "/ray/python/ray/worker.py", line 2493, in get
    raise RayGetError(object_ids, value)
RayGetError: Could not get objectid ObjectID(0a98eb5612c272b8bb6cee15f4b193368df19372). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/ray/python/ray/worker.py", line 934, in _process_task
    *arguments)
  File "/ray/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/ray/python/ray/tune/trainable.py", line 117, in train
    result = self._train()
  File "/ray/python/ray/tune/function_runner.py", line 110, in _train
    result = self._status_reporter._get_and_clear_status()
  File "/ray/python/ray/tune/function_runner.py", line 39, in _get_and_clear_status
    raise TuneError("Error running trial: " + str(self._error))
TuneError: Error running trial: 


Worker ip unknown, skipping log sync for /root/ray_results/my_exp/exp_2018-08-04_03-57-23fd9R8B
Created LogSyncer for /root/ray_results/my_exp/exp_2018-08-04_03-57-27GdZtsX -> 
Error processing event: Traceback (most recent call last):
  File "/ray/python/ray/tune/trial_runner.py", line 264, in _process_events
    result = ray.get(result_id)
  File "/ray/python/ray/worker.py", line 2493, in get
    raise RayGetError(object_ids, value)
RayGetError: Could not get objectid ObjectID(6954d9f23c03cdb93201223bfa3c1119b3526685). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/ray/python/ray/worker.py", line 934, in _process_task
    *arguments)
  File "/ray/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/ray/python/ray/tune/trainable.py", line 117, in train
    result = self._train()
  File "/ray/python/ray/tune/function_runner.py", line 110, in _train
    result = self._status_reporter._get_and_clear_status()
  File "/ray/python/ray/tune/function_runner.py", line 39, in _get_and_clear_status
    raise TuneError("Error running trial: " + str(self._error))
TuneError: Error running trial: 
```

Locally, the error message looks a lot better:

```

Runner thread raised: Traceback (most recent call last):
  File "/Users/rliaw/Research/riselab/ray/python/ray/tune/function_runner.py", line 71, in run
    self._entrypoint(*self._entrypoint_args)
  File "examples/hyperopt_example.py", line 18, in easy_objective
    assert type(config["activation"]) == str
AssertionError

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Users/rliaw/miniconda3/envs/py2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/rliaw/Research/riselab/ray/python/ray/tune/function_runner.py", line 75, in run
    raise e
AssertionError

Suppressing duplicate error message.
Error processing event: Traceback (most recent call last):
  File "/Users/rliaw/Research/riselab/ray/python/ray/tune/trial_runner.py", line 264, in _process_events
    result = ray.get(result_id)
  File "/Users/rliaw/Research/riselab/ray/python/ray/worker.py", line 2489, in get
    raise RayGetError(object_ids, value)
RayGetError: Could not get objectid ObjectID(01000000c81d076e4d726ce6af8f7bd9740df8b0). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/Users/rliaw/Research/riselab/ray/python/ray/worker.py", line 936, in _process_task
    *arguments)
  File "/Users/rliaw/Research/riselab/ray/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/Users/rliaw/Research/riselab/ray/python/ray/tune/trainable.py", line 117, in train
    result = self._train()
  File "/Users/rliaw/Research/riselab/ray/python/ray/tune/function_runner.py", line 110, in _train
    result = self._status_reporter._get_and_clear_status()
  File "/Users/rliaw/Research/riselab/ray/python/ray/tune/function_runner.py", line 39, in _get_and_clear_status
    raise TuneError("Error running trial: " + str(self._error))
TuneError: Error running trial:
```

**Comment by richardliaw** [comment]
Think this is really not an issue (closing for now)
