### ISSUE TITLE
[data] fully_executed does not work correctly with read_parquet

### ISSUE THREAD

**Issue by tgaddair** [ray-project/ray#25643]
### What happened + What you expected to happen

Prior to v1.13, it was possible to call `read_parquet().fully_executed().repeat()` to preload the parquet file into cluster memory. This sequence of functions is no longer working, and raises the following exception:

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    ds = read_parquet("df.parquet").fully_executed().repeat()
  File "/Users/tgaddair/.venv/ludwig/py38/lib/python3.8/site-packages/ray/data/dataset.py", line 2809, in repeat
    blocks, outer_stats, read_stage = _rewrite_read_stage(blocks)
  File "/Users/tgaddair/.venv/ludwig/py38/lib/python3.8/site-packages/ray/data/impl/plan.py", line 530, in _rewrite_read_stage
    remote_args = in_blocks._remote_args
AttributeError: 'BlockList' object has no attribute '_remote_args'
```

### Versions / Dependencies

Ray 1.13

### Reproduction script

```import pandas as pd
import ray
from ray.data import read_parquet

ray.init()

df = pd.DataFrame({"a": [1, 2, 3]})
df.to_parquet("df.parquet")

ds = read_parquet("df.parquet").fully_executed().repeat()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by clarkzinzow** [comment]
Hmm this succeeds for me on latest master, could you try this out on a [nightly wheel](https://docs.ray.io/en/master/ray-overview/installation.html#daily-releases-nightlies)?

**Comment by clarkzinzow** [comment]
Confirmed that this breaks on 1.13.0.

**Comment by clarkzinzow** [comment]
Yep @ericl fixed this in master 10 days ago, but it didn't make it in to the 1.13.0 release: https://github.com/ray-project/ray/pull/25265

**Comment by tgaddair** [comment]
Thanks @clarkzinzow. Are there plans to release a 1.13.1 soon?

**Comment by clarkzinzow** [comment]
@tgaddair I'll ping the appropriate internal folks about the prospect of a 1.13.1 release!

Is this a hard blocker, i.e. is calling `.fully_executed()` directly after the read a hard requirement? One workaround would be adding an identity map right after the read, e.g. `ray.data.read_parquet().map_batches(lambda x: x, batch_size=None).repeat()`; with automatic stage fusion, this identity map should add minimal overhead.

**Comment by tgaddair** [comment]
Thanks @clarkzinzow, I can try adding this as a workaround for now.

**Comment by clarkzinzow** [comment]
Closing this for now, will track the fix for picking onto the 1.13.1 release via tagging that PR!
