### ISSUE TITLE
[Serve] Deployment fails if name contains slashes

### ISSUE THREAD

**Issue by mihajenko** [ray-project/ray#25714]
### What happened + What you expected to happen

Decorating a class with `@deployment(name='api/v1')` caused the instantiation of the Deployment replica to fail. It looks like the logging expects a file path in the ray session logs folder based on this name. Removing the slash from the name works around the issue.

```
INFO 2022-06-12 22:44:29,647 controller 12825 checkpoint_path.py:17 - Using RayInternalKVStore for controller checkpoint and recovery.
INFO 2022-06-12 22:44:29,756 controller 12825 deployment_state.py:958 - Recovering target state for deployment api/v1 from checkpoint..
INFO 2022-06-12 22:44:29,760 controller 12825 deployment_state.py:1216 - Adding 1 replicas to deployment 'api/v1'.
ERROR 2022-06-12 22:44:31,517 controller 12825 deployment_state.py:422 - Exception in deployment 'api/v1'
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/serve/deployment_state.py", line 413, in check_ready
    deployment_config, version = ray.get(self._ready_obj_ref)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/worker.py", line 1833, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::SERVE_REPLICA::api/v1#caOacE:RayServeWrappedReplica.__init__[39m (pid=12858, ip=10.83.6.37, repr=<ray.serve.replica.api/v1 object at 0x7fe2c80744f0>)
  File "/home/ray/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/ray/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/serve/replica.py", line 75, in __init__
    configure_component_logger(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/serve/logging_utils.py", line 57, in configure_component_logger
    file_handler = logging.FileHandler(os.path.join(logs_dir, log_file_name))
  File "/home/ray/anaconda3/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/ray/anaconda3/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-06-12_22-33-04_336937_157/logs/serve/deployment_api/v1_api/v1#caOacE.log'
[2022-06-12 22:44:31,717 C 12825 12847] reference_count.cc:434:  Check failed: it->second.submitted_task_ref_count > 0 
*** StackTrace Information ***
    ray::SpdLogMessage::Flush()
    ray::RayLog::~RayLog()
    ray::core::ReferenceCounter::RemoveSubmittedTaskReferences()
    ray::core::ReferenceCounter::UpdateSubmittedTaskReferences()
    ray::core::TaskManager::OnTaskDependenciesInlined()
    std::_Function_handler<>::_M_invoke()
    ray::core::CoreWorkerMemoryStore::Put()
    ray::core::TaskManager::MarkTaskReturnObjectsFailed()
    ray::core::TaskManager::FailPendingTask()
    ray::core::TaskManager::FailOrRetryPendingTask()
    std::_Function_handler<>::_M_invoke()
    ray::core::CoreWorkerDirectActorTaskSubmitter::FailInflightTasks()
    ray::core::CoreWorkerDirectActorTaskSubmitter::DisconnectActor()
    EventTracker::RecordExecution()
    std::_Function_handler<>::_M_invoke()
    boost::asio::detail::completion_handler<>::do_complete()
    boost::asio::detail::scheduler::do_run_one()
    boost::asio::detail::scheduler::run()
    boost::asio::io_context::run()
    ray::core::CoreWorker::RunIOService()
    execute_native_thread_routine
```

This issue was not present in `1.12.x`, I assume the directory structure of the logging changed.

### Versions / Dependencies

* ray, version 1.13.0
* Python 3.8.12
* OS: Ubuntu based (images and development laptop)

### Reproduction script

```Python
from ray import serve
from ray.serve import deployment
from ray.util.client import ray


ray.init(namespace='serve')


@deployment(name='api/v1')
class MyApi:
    def __call__(self, *args, **kwargs):
        return 0


serve.start(detached=True)
MyApi.deploy()
```

Should produce something like this:
```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-06-13_08-01-22_980593_91931/logs/serve/deployment_api/v1_api/v1#sXfuyL.log'
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
