### ISSUE TITLE
Plasma Op: Error message when running

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#2575]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **Ray installed from (source or binary)**: Source
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

SGD seems to run but I get this message (which is unclear if is benevolent or not):
```
Remote function __init__ failed with:

Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/worker.py", line 934, in _process_task
    *arguments)
  File "/home/ubuntu/ray/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "./resnet101-ray-sgd.py", line 172, in __init__
    plasma.build_plasma_tensorflow_op()
  File "/home/ubuntu/ray/python/ray/pyarrow_files/pyarrow/plasma.py", line 56, in build_plasma_tensorflow_op
    subprocess.check_call(["bash", script_path])
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['bash', '/home/ubuntu/ray/python/ray/pyarrow_files/pyarrow/tensorflow/build.sh']' returned non-zero exit status 1
```

**Comment by pcmoritz** [comment]
Did you make sure that on each of the worker nodes, the `/home/ubuntu/ray/python/ray/pyarrow_files/pyarrow/tensorflow/build.sh` script finished successfully once before?
