### ISSUE TITLE
RLlib  Dequeue check() returned False

### ISSUE THREAD

**Issue by evo11x** [ray-project/ray#25783]
### What happened + What you expected to happen

The error appears after about 100k episodes

[nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan]], device='cuda:0', grad_fn=<SplitBackward0>)

In tower 0 on device cuda:0
Traceback (most recent call last):
  File "/home/usr1/Proj/ray_test.py", line 57, in <module>
    result = agent.train()        
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/tune/trainable.py", line 360, in train
    result = self.step()
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 1136, in step
    raise e
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 1112, in step
    step_attempt_results = self.step_attempt()
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 1214, in step_attempt
    step_results = self._exec_plan_or_training_iteration_fn()
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 2211, in _exec_plan_or_training_iteration_fn
    results = next(self.train_exec_impl)
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/util/iter.py", line 779, in __next__
    return next(self.built_iterator)
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/util/iter.py", line 807, in apply_foreach
    for item in it:
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/util/iter.py", line 807, in apply_foreach
    for item in it:
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/util/iter.py", line 869, in apply_filter
    for item in it:
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/util/iter.py", line 869, in apply_filter
    for item in it:
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/util/iter.py", line 807, in apply_foreach
    for item in it:
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/util/iter.py", line 869, in apply_filter
    for item in it:
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/util/iter.py", line 1108, in build_union
    item = next(it)
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/util/iter.py", line 779, in __next__
    return next(self.built_iterator)
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/util/iter.py", line 807, in apply_foreach
    for item in it:
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/util/iter.py", line 807, in apply_foreach
    for item in it:
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/rllib/execution/concurrency_ops.py", line 143, in base_iterator
    raise RuntimeError(
RuntimeError: Dequeue `check()` returned False! Exiting with Exception from Dequeue iterator.
Exception ignored in: <function RolloutWorker.__del__ at 0x7f5ba552c3a0>
Traceback (most recent call last):
  File "/home/usr1/Proj/.env/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 461, in _resume_span
TypeError: 'NoneType' object is not callable

### Versions / Dependencies

Python 3.9, Ubuntu 20 and Windows 11
ray 1.13.0 installed with ray[all]
gym 0.21.0

Hardware: AMD 16-core, 128GB RAM, RTX3060 12GB, Cuda 11.7

### Reproduction script

[ray_test.txt](https://github.com/ray-project/ray/files/8904382/ray_test.txt)

### Issue Severity

High: It blocks me from completing my task.

**Comment by evo11x** [comment]
I have lowered the ray version to 1.11.0 and lowered the observation to 7000, 1 worker and 1 env/worker and I managed to get around 12mil steps until it crashed again.

After trying to restore it runs a few steps then it crashes again, even with 0 workers and with num_gpus 0 ! So it is not a problem with cuda.
I really don’t know what is going on

![image](https://user-images.githubusercontent.com/32666929/175905687-e5a03bd8-a4da-4562-b0b3-99e83f91aa30.png)

I got this error running only on CPU!

`[nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan]], grad_fn=<SplitBackward0>)
 tracebackTraceback (most recent call last):
tracebackTraceback (most recent call last):
  File "d:\proj\.env\lib\site-packages\ray\rllib\policy\torch_policy.py", line 1012, in _worker
self._loss(self, model, self.dist_class, sample_batch))
  File "d:\proj\.env\lib\site-packages\ray\rllib\agents\impala\vtrace_torch_policy.py", line 117, in build_vtrace_loss
    action_dist = dist_class(model_out, model)
`

**Comment by dan-1d** [comment]
I have had similar issues, with similar error message. No conclusion to draw here, just additional information for the Collective.

TAKEAWAYS:

- Time-to-crash seems correlated to learning rate
- Value network loss approaches zero at time of crash
- Very challenging to go backwards from the crash to figure out what happened and why.


SETUP:

- A3C: NaN appears when sampling the policy. I tried to debug further, but have lots to learn about the inner workings of tune+rllib+ray
- IMPALA: See error below. I suspect it's the same root cause (NaN somewhere). 
- Single worker
- occurs with both CPU and GPU operation
```
  File "$MYPATH/anaconda_envs/py3.9/lib/python3.9/site-packages/ray/util/iter.py", line 807, in apply_foreach
    for item in it:
  File "$MYPATH/anaconda_envs/py3.9/lib/python3.9/site-packages/ray/rllib/execution/concurrency_ops.py", line 143, in base_iterator
    raise RuntimeError(
RuntimeError: Dequeue `check()` returned False! Exiting with Exception from Dequeue iterator.
```

Upon some experimentation, lowering the learning rate seems to help tremendously. Conversely, if the learning rate is raised, this issue appears much sooner.
- In my case, with IMPALA, this config option was used to get up to ~80k steps ```"lr": 0.00005```

I suspected the underlying problem is that the policy or value networks see a flat gradient during backprop, which perhaps is manifest as a NaN (??). However, policy loss is dropping at the time of the crash; however, **value loss is near zero**. Perhaps someone else can read these tea leaves better.

The plot below is of the value function loss, under experiments of various learning rates, where smaller rates yield longer training before crashing. The highest learning rates (orange and sky blue) very quickly drop to 0 or very near 0.

![Screenshot from 2022-08-11 09-59-56](https://user-images.githubusercontent.com/4029020/184191453-c1f63306-5657-4c04-8215-8f8bd63681ef.png)

**Comment by andraxin** [comment]
The same symptom can be observed in a failed CI build:
 https://buildkite.com/ray-project/ray-builders-pr/builds/44593#01834ab7-eb3f-4754-930f-a4fe5228ccff/13-3427

**Comment by tanmaychimurkar** [comment]
Hello everyone, 

I am also currently facing the same issue with IMPALA. Is there any workaround for this?

I was not able to find a workaround for this. Thanks for the help.

**Comment by tanmaychimurkar** [comment]
Hello everyone, 

I am also currently facing the same issue with IMPALA about `check()`. Is there any workaround for this?

My pipeline works with A2CTrainer, but I wanted to use decaying-epsilon greedy like IMPALA, but not able to run so far.

Thanks for the help.
