### ISSUE TITLE
[Core/Data] dataset_shuffle_push_based_sort_1tb failed with `ValueError: The keyword 'num_returns' only accepts None, 0 or a positive integer.` 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#25863]
### What happened + What you expected to happen

The dataset_shuffle_push_based_sort_1tb nighly test failed on 14th with following error

```
Traceback (most recent call last):
  File "dataset/sort.py", line 158, in <module>
    raise exc
  File "dataset/sort.py", line 112, in <module>
    ds = ds.sort(key="c_0")
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 1698, in sort
    return Dataset(plan, self._epoch, self._lazy)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 177, in __init__
    self._plan.execute(allow_clear_input_blocks=False)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/plan.py", line 257, in execute
    blocks, stage_info = stage(blocks, clear_input_blocks)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/plan.py", line 497, in __call__
    blocks, clear_input_blocks, self.block_udf, self.ray_remote_args
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 1695, in do_sort
    return sort_impl(blocks, clear_input_blocks, key, descending)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/sort.py", line 149, in sort_impl
    clear_input_blocks,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/push_based_shuffle.py", line 255, in execute
    merge_args,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/push_based_shuffle.py", line 454, in _execute_pipelined_stage
    metadata_ref, data_output = stage_fn(arg)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/push_based_shuffle.py", line 194, in submit_merge_task
    **stage.get_merge_task_options(merge_idx),
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/remote_function.py", line 153, in options
    ray_option_utils.validate_task_options(updated_options, in_options=True)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/ray_option_utils.py", line 191, in validate_task_options
    task_options[k].validate(k, v)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/ray_option_utils.py", line 33, in validate
    raise ValueError(self.error_message_for_value_constraint)
ValueError: The keyword 'num_returns' only accepts None, 0 or a positive integer.
```

See test run [here](https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_wNetm8SuMapic7qBdMZvRTQ4?command-history-section=command_history).

@stephanie-wang is this something you already fixed?

### Versions / Dependencies

lastest master

### Reproduction script

https://sourcegraph.com/github.com/ray-project/ray/-/blob/release/release_tests.yaml?L3509

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by scv119** [comment]
mark it P1 as it's pushed based shuffle related.
