### ISSUE TITLE
[RLlib] KeyError: simple_list_collector.py, line 950, in postprocess_episode 

### ISSUE THREAD

**Issue by phipag** [ray-project/ray#25938]
### What happened + What you expected to happen

I use ExternalEnv in combination with PolicyClient and PolicyServer similar to the [cartpole example](https://github.com/ray-project/ray/tree/master/rllib/examples/serving).

My external simulator starts an episode, gets an action and logs the returns multiple times before getting a new action and eventually ends the episode.

In edge cases the simulator might start an episode and end it again immediately before getting a new action. This causes the Inference Thread to crash with the following error:
```
Traceback (most recent call last):
  File "/powertac/broker/rl/venv/lib/python3.8/site-packages/ray/rllib/env/policy_client.py", line 299, in run
    samples = self.rollout_worker.sample()
  File "/powertac/broker/rl/venv/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 815, in sample
    batches = [self.input_reader.next()]
  File "/powertac/broker/rl/venv/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 116, in next
    batches = [self.get_data()]
  File "/powertac/broker/rl/venv/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 289, in get_data
    item = next(self._env_runner)
  File "/powertac/broker/rl/venv/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 679, in _env_runner
    active_envs, to_eval, outputs = _process_observations(
  File "/powertac/broker/rl/venv/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 1010, in _process_observations
    ma_sample_batch = sample_collector.postprocess_episode(
  File "/powertac/broker/rl/venv/lib/python3.8/site-packages/ray/rllib/evaluation/collectors/simple_list_collector.py", line 950, in postprocess_episode
    del self.episode_steps[episode_id]
KeyError: 30361635
```

While I agree that this behavior is not sensible I think it should not crash the Inference Thread but instead log a warning.

### Versions / Dependencies

Ray v1.12.1
Python 3.8
Ubuntu 18.04.1

### Reproduction script

Reproduction:

Start the [cartpole_server.py](https://github.com/ray-project/ray/blob/master/rllib/examples/serving/cartpole_server.py).

Create a dummy client.
```
client = PolicyClient(
    f"http://localhost:{args.port}", inference_mode=args.inference_mode
)
env = gym.make("CartPole-v0")
dummy_obs = env.reset()
```

Call start_episode and end_episode without getting an action in between.
```
eid = client.start_episode(training_enabled=True)
client.end_episode(eid, dummy_obs)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by phipag** [comment]
This might be related to https://github.com/ray-project/ray/issues/14653.

**Comment by robfitzgerald** [comment]
this also happens for me, leaving a note here for anyone else digging for answers. 

while PR #14653 exposes similar errors that led to a fix in PR #14765, it appears that PR did not address line 950. however, the current state of things on master shows a more thorough refactor of the simple_list_collector which includes a [friendly error message](https://github.com/ray-project/ray/blob/acf2bf9b2fa9f6cac8c599ec1eea6a9d5249905f/rllib/evaluation/collectors/simple_list_collector.py#L562) for what was previously line 950.

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
