### ISSUE TITLE
Ray Core: Running a lot of tasks crashes 'ray list' cli

### ISSUE THREAD

**Issue by waleedkadous** [ray-project/ray#25984]
### What happened + What you expected to happen

I ran the demo code at https://docs.ray.io/en/master/ray-core/examples/highly_parallel.html 

This generated ~100,000 tasks. 

I then ran a simple command -- `ray list tasks`

It fails with the following error (which clearly indicates we're not paginating correctly): 

```
$ ray list tasks
Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 2494, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/experimental/state/state_cli.py", line 168, in list
    data = client.list(resource, options=options, _explain=_should_explain(format))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/experimental/state/api.py", line 137, in list
    raise RayStateApiException(
ray.experimental.state.exception.RayStateApiException: API server internal error. See dashboard.log file for more details. Error: Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/dashboard/optional_utils.py", line 94, in _handler_route
    return await handler(bind_info.instance, req)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/dashboard/modules/state/state_head.py", line 153, in list_tasks
    return await self._handle_list_api(self._state_api.list_tasks, req)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/dashboard/modules/state/state_head.py", line 110, in _handle_list_api
    result = await list_api_fn(option=self._options_from_req(req))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/dashboard/state_aggregator.py", line 300, in list_tasks
    raise reply
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/experimental/state/state_manager.py", line 86, in api_with_network_error_handler
    raise e
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/experimental/state/state_manager.py", line 74, in api_with_network_error_handler
    return await func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/experimental/state/state_manager.py", line 273, in get_task_info
    reply = await stub.GetTasksInfo(GetTasksInfoRequest(), timeout=timeout)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/aio/_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "Received message larger than max (26381468 vs. 4194304)"
        debug_error_string = "{"created":"@1655857947.995675297","description":"Received message larger than max (26381468 vs. 4194304)","file":"src/core/ext/filters/message_size/message_size_filter.cc","file_line":205,"grpc_status":8}"
```

### Versions / Dependencies

Running in a nightly workspace, vanilla, nothing at all funky. 

### Reproduction script

```
# Approximate pi using random sampling. Generate x and y randomly between 0 and 1. 
#  if x^2 + y^2 < 1 it's inside the quarter circle. x 4 to get pi. 
import ray
from random import random

# Let's start Ray
ray.init()

SAMPLES = 1000000; 
# By adding the `@ray.remote` decorator, a regular Python function
# becomes a Ray remote function.
@ray.remote
def pi4_sample():
    in_count = 0
    for _ in range(SAMPLES):
        x, y = random(), random()
        if x*x + y*y <= 1:
            in_count += 1
    return in_count

# To invoke this remote function, use the `remote` method.
# This will immediately return an object ref (a future) and then create
# a task that will be executed on a worker process. Get retreives the result. 
future = pi4_sample.remote()
pi = ray.get(future) * 4.0 / SAMPLES
print(f'{pi} is an approximation of pi') 

# Now let's do this 100,000 times. 
# With regular python this would take 11 hours
# Ray on a modern laptop, roughly 2 hours
# On a 10-node Ray cluster, roughly 10 minutes 
BATCHES = 100000
results = [] 
for _ in range(BATCHES):
    results.append(pi4_sample.remote())
output = ray.get(results)
pi = sum(output) * 4.0 / BATCHES / SAMPLES
print(f'{pi} is a way better approximation of pi') 
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rkooo567** [comment]
Hey, @waleedkadous thanks for the report! This will be resolved by this task https://github.com/ray-project/ray/issues/25718. 
(btw, in the alpha API, we will truncate the data instead of paginating them).

**Comment by rkooo567** [comment]
Hey @waleedkadous is it possible to share the cluster config? I'd like to verify if the tagged PR will fix the issue.

**Comment by waleedkadous** [comment]
It was the Anyscale standard cluster config (1 head node, 0 min nodes with
autoscaling up to 10 worker nodes).

**Comment by rkooo567** [comment]
Will close it after confirmation

**Comment by rkooo567** [comment]
Verified it truncates data properly. We will shortly work on improving experience at such scenarios (that could be better than truncation)
