### ISSUE TITLE
[Java] Tests fail when redis server is already started.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#2604]
After building Ray for Java, the following succeeds for me.

```
cd java
mvn test
```

However, the following fails

```
cd java
../build/src/common/thirdparty/redis/src/redis-server --port 34111 &
mvn test
```

In case anyone else is googling this error message, it fails with

```
~/ray/java$ mvn test
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.ray:ray-api:jar:1.0
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.github.davidmoten:flatbuffers-java:jar -> version 1.9.0.1 vs 1.7.0.1 @ org.ray.parent:ray-superpom:1.0, /home/ubuntu/ray/java/pom.xml, line 134, column 25
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.beust:jcommander:jar -> duplicate declaration of version 1.72 @ org.ray.parent:ray-superpom:1.0, /home/ubuntu/ray/java/pom.xml, line 141, column 25
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.ray:ray-common:jar:1.0
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.github.davidmoten:flatbuffers-java:jar -> version 1.9.0.1 vs 1.7.0.1 @ org.ray.parent:ray-superpom:1.0, /home/ubuntu/ray/java/pom.xml, line 134, column 25
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.beust:jcommander:jar -> duplicate declaration of version 1.72 @ org.ray.parent:ray-superpom:1.0, /home/ubuntu/ray/java/pom.xml, line 141, column 25
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.ray:ray-runtime-common:jar:1.0
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.github.davidmoten:flatbuffers-java:jar -> version 1.9.0.1 vs 1.7.0.1 @ org.ray.parent:ray-superpom:1.0, /home/ubuntu/ray/java/pom.xml, line 134, column 25
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.beust:jcommander:jar -> duplicate declaration of version 1.72 @ org.ray.parent:ray-superpom:1.0, /home/ubuntu/ray/java/pom.xml, line 141, column 25
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.ray:ray-runtime-native:jar:1.0
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.github.davidmoten:flatbuffers-java:jar -> version 1.9.0.1 vs 1.7.0.1 @ org.ray.parent:ray-superpom:1.0, /home/ubuntu/ray/java/pom.xml, line 134, column 25
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.beust:jcommander:jar -> duplicate declaration of version 1.72 @ org.ray.parent:ray-superpom:1.0, /home/ubuntu/ray/java/pom.xml, line 141, column 25
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.ray:ray-runtime-dev:jar:1.0
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.github.davidmoten:flatbuffers-java:jar -> version 1.9.0.1 vs 1.7.0.1 @ org.ray.parent:ray-superpom:1.0, /home/ubuntu/ray/java/pom.xml, line 134, column 25
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.beust:jcommander:jar -> duplicate declaration of version 1.72 @ org.ray.parent:ray-superpom:1.0, /home/ubuntu/ray/java/pom.xml, line 141, column 25
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.ray:ray-cli:jar:1.0
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.github.davidmoten:flatbuffers-java:jar -> version 1.9.0.1 vs 1.7.0.1 @ org.ray.parent:ray-superpom:1.0, /home/ubuntu/ray/java/pom.xml, line 134, column 25
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.beust:jcommander:jar -> duplicate declaration of version 1.72 @ org.ray.parent:ray-superpom:1.0, /home/ubuntu/ray/java/pom.xml, line 141, column 25
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.ray:ray-test:jar:1.0
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.github.davidmoten:flatbuffers-java:jar -> version 1.9.0.1 vs 1.7.0.1 @ org.ray.parent:ray-superpom:1.0, /home/ubuntu/ray/java/pom.xml, line 134, column 25
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.beust:jcommander:jar -> duplicate declaration of version 1.72 @ org.ray.parent:ray-superpom:1.0, /home/ubuntu/ray/java/pom.xml, line 141, column 25
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.ray:ray-tutorial:jar:1.0
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.github.davidmoten:flatbuffers-java:jar -> version 1.9.0.1 vs 1.7.0.1 @ org.ray.parent:ray-superpom:1.0, /home/ubuntu/ray/java/pom.xml, line 134, column 25
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.beust:jcommander:jar -> duplicate declaration of version 1.72 @ org.ray.parent:ray-superpom:1.0, /home/ubuntu/ray/java/pom.xml, line 141, column 25
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.ray.parent:ray-superpom:pom:1.0
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.github.davidmoten:flatbuffers-java:jar -> version 1.9.0.1 vs 1.7.0.1 @ line 134, column 25
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.beust:jcommander:jar -> duplicate declaration of version 1.72 @ line 141, column 25
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] ray-superpom
[INFO] java common and util for ray
[INFO] java api for ray
[INFO] runtime common
[INFO] native runtime for ray
[INFO] runtime-dev
[INFO] java cli for ray
[INFO] java test cases for ray
[INFO] java tutorial
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ray-superpom 1.0
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building java common and util for ray 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ray-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ ray-common ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ray-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ubuntu/ray/java/common/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ ray-common ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ ray-common ---
[INFO] No tests to run.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building java api for ray 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ray-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ubuntu/ray/java/api/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ ray-api ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ray-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ubuntu/ray/java/api/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ ray-api ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ ray-api ---
[INFO] No tests to run.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building runtime common 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ray-runtime-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ubuntu/ray/java/runtime-common/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ ray-runtime-common ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ray-runtime-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ubuntu/ray/java/runtime-common/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ ray-runtime-common ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ ray-runtime-common ---
[INFO] No tests to run.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building native runtime for ray 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ray-runtime-native ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ubuntu/ray/java/runtime-native/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ ray-runtime-native ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ray-runtime-native ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ubuntu/ray/java/runtime-native/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ ray-runtime-native ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ ray-runtime-native ---
[INFO] No tests to run.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building runtime-dev 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ray-runtime-dev ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ubuntu/ray/java/runtime-dev/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ ray-runtime-dev ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ray-runtime-dev ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ubuntu/ray/java/runtime-dev/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ ray-runtime-dev ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ ray-runtime-dev ---
[INFO] No tests to run.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building java cli for ray 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ray-cli ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ubuntu/ray/java/cli/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ ray-cli ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ray-cli ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ubuntu/ray/java/cli/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ ray-cli ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ ray-cli ---
[INFO] No tests to run.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building java test cases for ray 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ray-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ubuntu/ray/java/test/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ ray-test ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ray-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ubuntu/ray/java/test/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ ray-test ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.21.0:test (default-test) @ ray-test ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.ray.api.benchmark.SingleLatencyTest
Build ConfigReader, the file path /home/ubuntu/ray/java/test/../ray.config.ini ,the update config str null
Current working directory is /home/ubuntu/ray/java/test
2018-08-08 06:26:26 INFO core [main]: Start org.ray.core.impl.RayNativeRuntime with SINGLE_BOX
2018-08-08 06:26:26 INFO core [main]: start ray processes @ 172.31.35.67 ...
2018-08-08 06:26:26 INFO core [main]: Start process 1914572623 OK, cmd = [/home/ubuntu/ray/java/test/../../build/src/common/thirdparty/redis/src/redis-server  --protected-mode  no  --port  34111  --loglevel  warning  --loadmodule  /home/ubuntu/ray/java/test/../../build/src/common/redis_module/libray_redis_module.so], working dir = '/home/ubuntu/ray/java/test/../run/redis34111', redirect
RayRuntime start failed:DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
redis.clients.jedis.exceptions.JedisDataException: DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
	at redis.clients.jedis.Protocol.processError(Protocol.java:117)
	at redis.clients.jedis.Protocol.process(Protocol.java:151)
	at redis.clients.jedis.Protocol.read(Protocol.java:205)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:196)
	at redis.clients.jedis.Jedis.configSet(Jedis.java:2612)
	at org.ray.runner.RunManager.startRedisInstance(RunManager.java:567)
	at org.ray.runner.RunManager.startRedis(RunManager.java:515)
	at org.ray.runner.RunManager.startRayProcesses(RunManager.java:278)
	at org.ray.runner.RunManager.startRayHead(RunManager.java:90)
	at org.ray.core.impl.RayNativeRuntime.startOnebox(RayNativeRuntime.java:177)
	at org.ray.core.impl.RayNativeRuntime.start(RayNativeRuntime.java:65)
	at org.ray.core.RayRuntime.instantiate(RayRuntime.java:162)
	at org.ray.core.RayRuntime.init(RayRuntime.java:86)
	at org.ray.core.RayRuntime.init(RayRuntime.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ray.api.internal.RayConnector.run(RayConnector.java:18)
	at org.ray.api.Ray.init(Ray.java:20)
	at org.ray.api.test.TestListener.testRunStarted(TestListener.java:13)
	at org.junit.runner.notification.RunNotifier$1.notifyListener(RunNotifier.java:81)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:61)
	at org.junit.runner.notification.RunNotifier.fireTestRunStarted(RunNotifier.java:78)
	at org.ray.api.test.MyRunner.run(MyRunner.java:16)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
2018-08-08 06:26:27 ERROR core [main]: RayRuntime start failed
redis.clients.jedis.exceptions.JedisDataException: DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
	at redis.clients.jedis.Protocol.processError(Protocol.java:117)
	at redis.clients.jedis.Protocol.process(Protocol.java:151)
	at redis.clients.jedis.Protocol.read(Protocol.java:205)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:196)
	at redis.clients.jedis.Jedis.configSet(Jedis.java:2612)
	at org.ray.runner.RunManager.startRedisInstance(RunManager.java:567)
	at org.ray.runner.RunManager.startRedis(RunManager.java:515)
	at org.ray.runner.RunManager.startRayProcesses(RunManager.java:278)
	at org.ray.runner.RunManager.startRayHead(RunManager.java:90)
	at org.ray.core.impl.RayNativeRuntime.startOnebox(RayNativeRuntime.java:177)
	at org.ray.core.impl.RayNativeRuntime.start(RayNativeRuntime.java:65)
	at org.ray.core.RayRuntime.instantiate(RayRuntime.java:162)
	at org.ray.core.RayRuntime.init(RayRuntime.java:86)
	at org.ray.core.RayRuntime.init(RayRuntime.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ray.api.internal.RayConnector.run(RayConnector.java:18)
	at org.ray.api.Ray.init(Ray.java:20)
	at org.ray.api.test.TestListener.testRunStarted(TestListener.java:13)
	at org.junit.runner.notification.RunNotifier$1.notifyListener(RunNotifier.java:81)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:61)
	at org.junit.runner.notification.RunNotifier.fireTestRunStarted(RunNotifier.java:78)
	at org.ray.api.test.MyRunner.run(MyRunner.java:16)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ray-superpom ....................................... SUCCESS [  0.001 s]
[INFO] java common and util for ray ....................... SUCCESS [  0.632 s]
[INFO] java api for ray ................................... SUCCESS [  0.053 s]
[INFO] runtime common ..................................... SUCCESS [  0.027 s]
[INFO] native runtime for ray ............................. SUCCESS [  0.018 s]
[INFO] runtime-dev ........................................ SUCCESS [  0.013 s]
[INFO] java cli for ray ................................... SUCCESS [  0.015 s]
[INFO] java test cases for ray ............................ FAILURE [  1.703 s]
[INFO] java tutorial ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.624 s
[INFO] Finished at: 2018-08-08T06:26:27+00:00
[INFO] Final Memory: 22M/1562M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project ray-test: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/ubuntu/ray/java/test/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/ubuntu/ray/java/test && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -ea -Djava.library.path=/home/ubuntu/ray/java/test/../../build/src/plasma:/home/ubuntu/ray/java/test/../../build/src/local_scheduler -noverify -DlogOutput=console -jar /home/ubuntu/ray/java/test/target/surefire/surefirebooter5399959981280463063.jar /home/ubuntu/ray/java/test/target/surefire 2018-08-08T06-26-25_923-jvmRun1 surefire1614775648418066309tmp surefire_0362639801607151159tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 255
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/ubuntu/ray/java/test && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -ea -Djava.library.path=/home/ubuntu/ray/java/test/../../build/src/plasma:/home/ubuntu/ray/java/test/../../build/src/local_scheduler -noverify -DlogOutput=console -jar /home/ubuntu/ray/java/test/target/surefire/surefirebooter5399959981280463063.jar /home/ubuntu/ray/java/test/target/surefire 2018-08-08T06-26-25_923-jvmRun1 surefire1614775648418066309tmp surefire_0362639801607151159tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 255
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:978)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:854)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ray-test
```

**Comment by kingchin1218** [comment]
Thanks @robertnishihara .
Did this happen in raylet mode or non raylet mode?
And which branch/commit did u test?

**Comment by kingchin1218** [comment]
Could u plz tell me what's the purpose of starting a redis server？

**Comment by kingchin1218** [comment]
@robertnishihara Could u plz tell me the purpose of starting a redis server before `mvn test`？

**Comment by robertnishihara** [comment]
I think this happens on the current master branch.

The issue is that I ran `mvn test`, which starts a bunch of Ray processes and then it failed (because I was on some development branch), so the test exited but some Ray processes (like the redis server) were left running. And then I tried rerunning `mvn test` again in order to reproduce the bug. However, the second time `mvn test` failed because it failed to start the Redis server. Does the problem make sense?

One approach could be to randomize the ports and socket names used in the tests. Another approach could be to make sure that the Ray processes are killed if the tests fail. Do either of these sound feasible?

**Comment by kingchin1218** [comment]
The root cause of this issue is that `mvn test` fails and rerun `mvn test` fails again because of unclosed redis-server-listening ports, right?

if it's, this issue has always existed.

Randomizing the ports and socket files is not a wonderful approach in my view.
Maybe we should do some `cleanup` when `mvn test` fails. 
@robertnishihara  What do you think？

**Comment by robertnishihara** [comment]
Yes, that is the issue.

Is there a natural way to do cleanups when `mvn test` fails?

For example, in the Python tests, we define these `tearDown` functions which always run and stop the Ray processes if the test raises an exception.

https://github.com/ray-project/ray/blob/8ae82180b4e1e5eddfb44ff8b96837fdd539d869/test/runtest.py#L291-L293

**Comment by kingchin1218** [comment]
Certainly yes.

**Comment by jovany-wang** [comment]
I think PR [3577](https://github.com/ray-project/ray/pull/3577)  have fixed this issue.
This issue could be closed.

**Comment by robertnishihara** [comment]
Great, thanks!
