### ISSUE TITLE
[Core][Nightly-test] chaos_dask_on_ray_large_scale_test_no_spilling becomes flaky

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#26139]
### What happened + What you expected to happen

Error cluster:

https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_s1v4e5VBMBpWFTGZDx8C1ir8?command-history-section=command_history

comments: should we wait for node joining before starting the tests?

### Versions / Dependencies

latest ray

### Reproduction script

run chaos_dask_on_ray_large_scale_test_no_spilling

**Comment by zhe-thoughts** [comment]
Thanks @scv119 . Is this a release blocker for 2.0.0beta?

**Comment by stephanie-wang** [comment]
This looks like it's an Anyscale-related issue; I don't think it's a release blocker.

```
(scheduler +1m58s) Traceback (most recent call last):
(scheduler +1m58s)   File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/api.py", line 136, in call_api
(scheduler +1m58s)     _host,
(scheduler +1m58s)   File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/client/openapi_client/api_client.py", line 353, in call_api
(scheduler +1m58s)     _preload_content, _request_timeout, _host)
(scheduler +1m58s)   File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/client/openapi_client/api_client.py", line 184, in __call_api
(scheduler +1m58s)     _request_timeout=_request_timeout)
(scheduler +1m58s)   File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/client/openapi_client/api_client.py", line 397, in request
(scheduler +1m58s)     body=body)
(scheduler +1m58s)   File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/client/openapi_client/rest.py", line 276, in POST
(scheduler +1m58s)     body=body)
(scheduler +1m58s)   File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/client/openapi_client/rest.py", line 229, in request
(scheduler +1m58s)     raise ApiException(http_resp=r)
(scheduler +1m58s) openapi_client.exceptions.ApiException: (500)
(scheduler +1m58s) Reason: Internal Server Error
(scheduler +1m58s) HTTP response headers: HTTPHeaderDict({'Date': 'Fri, 24 Jun 2022 22:44:22 GMT', 'Content-Type': 'application/json', 'Content-Length': '939', 'Connection': 'keep-alive', 'Set-Cookie': 'AWSALB=nMeSKhJ1COsDrxLjFeYSm7M+8MVHyMC4VjjkqWhwrNClBFiSu7aQlgN8OQCRIe2qR5OgxUpXLX4TWsu0BCsW3NvwNn5Qs6+O0/cNkFV6J8BBVgXExFRqE4mMCvUR; Expires=Fri, 01 Jul 2022 22:44:18 GMT; Path=/, AWSALBCORS=nMeSKhJ1COsDrxLjFeYSm7M+8MVHyMC4VjjkqWhwrNClBFiSu7aQlgN8OQCRIe2qR5OgxUpXLX4TWsu0BCsW3NvwNn5Qs6+O0/cNkFV6J8BBVgXExFRqE4mMCvUR; Expires=Fri, 01 Jul 2022 22:44:18 GMT; Path=/; SameSite=None; Secure', 'Server': 'nginx/1.18.0 (Ubuntu)', 'x-trace-id': 'e9197c436e8e5544f72ede1dd117c2'})
(scheduler +1m58s) HTTP response body: {"error":{"detail":"gAWVpAIAAAAAAACME2JvdG9jb3JlLmV4Y2VwdGlvbnOUjAtDbGllbnRFcnJvcpSTlH2UKIwFRXJyb3KUfZQojARDb2RllIwcSW5zdWZmaWNpZW50SW5zdGFuY2VDYXBhY2l0eZSMB01lc3NhZ2WUjD5UaGVyZSBpcyBubyBTcG90IGNhcGFjaXR5IGF2YWlsYWJsZSB0aGF0IG1hdGNoZXMgeW91ciByZXF1ZXN0LpR1jBBSZXNwb25zZU1ldGFkYXRhlH2UKIwJUmVxdWVzdElklIwkYTFkZjE5M2MtMmM4YS00MTkxLTliNzctYTA0MzliMTE5OTYwlIwOSFRUUFN0YXR1c0NvZGWUTfQBjAtIVFRQSGVhZGVyc5R9lCiMEHgtYW16bi1yZXF1ZXN0aWSUjCRhMWRmMTkzYy0yYzhhLTQxOTEtOWI3Ny1hMDQzOWIxMTk5NjCUjA1jYWNoZS1jb250cm9slIwSbm8tY2FjaGUsIG5vLXN0b3JllIwZc3RyaWN0LXRyYW5zcG9ydC1zZWN1cml0eZSMI21heC1hZ2U9MzE1MzYwMDA7IGluY2x1ZGVTdWJEb21haW5zlIwEdmFyeZSMD2FjY2VwdC1lbmNvZGluZ5SMDGNvbnRlbnQtdHlwZZSMFnRleHQveG1sO2NoYXJzZXQ9VVRGLTiUjBF0cmFuc2Zlci1lbmNvZGluZ5SMB2NodW5rZWSUjARkYXRllIwdRnJpLCAyNCBKdW4gMjAyMiAyMjo0NDoyMSBHTVSUjApjb25uZWN0aW9ulIwFY2xvc2WUjAZzZXJ2ZXKUjAlBbWF6b25FQzKUdYwSTWF4QXR0ZW1wdHNSZWFjaGVklIiMDVJldHJ5QXR0ZW1wdHOUSwB1dYwMUnVuSW5zdGFuY2VzlIaUUpQu"}}
(scheduler +1m58s) 
(scheduler +1m58s) 
(scheduler +1m58s) During handling of the above exception, another exception occurred:
(scheduler +1m58s) 
(scheduler +1m58s) Traceback (most recent call last):
(scheduler +1m58s)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/node_launcher.py", line 98, in run
(scheduler +1m58s)     self._launch_node(config, count, node_type)
(scheduler +1m58s)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/node_launcher.py", line 82, in _launch_node
(scheduler +1m58s)     node_config, node_tags, count, resources
(scheduler +1m58s)   File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/autoscaler/node_provider.py", line 236, in create_node_with_resources
(scheduler +1m58s)     self.create_node(node_config, tags, count)
(scheduler +1m58s)   File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/autoscaler/node_provider.py", line 495, in create_node
(scheduler +1m58s)     super().create_node(node_config, tags, count)
(scheduler +1m58s)   File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/autoscaler/node_provider.py", line 255, in create_node
(scheduler +1m58s)     self.api_client.create_nodes_api_v2_instances_post(create_node_request)
(scheduler +1m58s)   File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/autoscaler/node_provider.py", line 78, in retrier
(scheduler +1m58s)     return func(*args, **kwargs)
(scheduler +1m58s)   File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/client/openapi_client/api/default_api.py", line 2380, in create_nodes_api_v2_instances_post
(scheduler +1m58s)     return self.create_nodes_api_v2_instances_post_with_http_info(create_nodes_options, **kwargs)  # noqa: E501
(scheduler +1m58s)   File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/client/openapi_client/api/default_api.py", line 2472, in create_nodes_api_v2_instances_post_with_http_info
(scheduler +1m58s)     collection_formats=collection_formats)
(scheduler +1m58s)   File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/api.py", line 140, in call_api
(scheduler +1m58s)     e, method, resource_path, self.raise_structured_exception
(scheduler +1m58s)   File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/api.py", line 80, in format_api_exception
(scheduler +1m58s)     f"API Exception ({e.status}) from {method} {resource_path} \n"
(scheduler +1m58s) click.exceptions.ClickException: API Exception (500) from POST /api/v2/instances/ 
(scheduler +1m58s) Reason: Internal Server Error
(scheduler +1m58s) HTTP response body: {"error":{"detail":"gAWVpAIAAAAAAACME2JvdG9jb3JlLmV4Y2VwdGlvbnOUjAtDbGllbnRFcnJvcpSTlH2UKIwFRXJyb3KUfZQojARDb2RllIwcSW5zdWZmaWNpZW50SW5zdGFuY2VDYXBhY2l0eZSMB01lc3NhZ2WUjD5UaGVyZSBpcyBubyBTcG90IGNhcGFjaXR5IGF2YWlsYWJsZSB0aGF0IG1hdGNoZXMgeW91ciByZXF1ZXN0LpR1jBBSZXNwb25zZU1ldGFkYXRhlH2UKIwJUmVxdWVzdElklIwkYTFkZjE5M2MtMmM4YS00MTkxLTliNzctYTA0MzliMTE5OTYwlIwOSFRUUFN0YXR1c0NvZGWUTfQBjAtIVFRQSGVhZGVyc5R9lCiMEHgtYW16bi1yZXF1ZXN0aWSUjCRhMWRmMTkzYy0yYzhhLTQxOTEtOWI3Ny1hMDQzOWIxMTk5NjCUjA1jYWNoZS1jb250cm9slIwSbm8tY2FjaGUsIG5vLXN0b3JllIwZc3RyaWN0LXRyYW5zcG9ydC1zZWN1cml0eZSMI21heC1hZ2U9MzE1MzYwMDA7IGluY2x1ZGVTdWJEb21haW5zlIwEdmFyeZSMD2FjY2VwdC1lbmNvZGluZ5SMDGNvbnRlbnQtdHlwZZSMFnRleHQveG1sO2NoYXJzZXQ9VVRGLTiUjBF0cmFuc2Zlci1lbmNvZGluZ5SMB2NodW5rZWSUjARkYXRllIwdRnJpLCAyNCBKdW4gMjAyMiAyMjo0NDoyMSBHTVSUjApjb25uZWN0aW9ulIwFY2xvc2WUjAZzZXJ2ZXKUjAlBbWF6b25FQzKUdYwSTWF4QXR0ZW1wdHNSZWFjaGVklIiMDVJldHJ5QXR0ZW1wdHOUSwB1dYwMUnVuSW5zdGFuY2VzlIaUUpQu"}}
(scheduler +1m58s) Trace ID: ['x-trace-id', 'e9197c436e8e5544f72ede1dd117c2']
(scheduler +1m58s) 
(scheduler +1m58s) Failed to launch 10 nodes of type worker_node.
```

**Comment by jjyao** [comment]
It passed for the past 10 runs.
