### ISSUE TITLE
Need documentation for running RLlib with Ray Cluster [<Ray component: RLlib>] 

### ISSUE THREAD

**Issue by spacegoing** [ray-project/ray#26172]
### Description

A quick question. Am I understanding it correctly that in order to run `RLlib` examples in a `Ray Cluster`,  we simply need to run:

`ray exec ray-ml.yaml "rllib -f example.py"`

and the cluster will auto-scale rllib applications? Or will it just run on the `head` without `workers` spinning up?

Is there any example about submitting RLLib jobs to Ray Clusters?

----

I'm following this https://docs.ray.io/en/latest/cluster/commands.html#cluster-commands to set up ray clusters and everything works smoothly. The team did a really good job on providing examples. However, I searched through internet and barely find useful information/examples for running "Tune" and "RLlib" with "Ray Cluster".

**Comment by stephanie-wang** [comment]
Yes, you should be able to run the same script on your cluster and it should work. As long as you configured your cluster to include worker nodes, your script will scale out to use multiple workers.

**Comment by spacegoing** [comment]
@stephanie-wang Hi Stephanie, many thanks for your reply! I'd love to know is there an example running RLlib on a ray cluster (as well as the configuration file)? Many thanks :D

**Comment by spacegoing** [comment]
Hi @stephanie-wang ,

Sorry to disturb you again. But my `rllib` does not seem to autoscale my `ray cluster`.

----
To start with:
- my ray cluster yaml: [gpu.yaml](https://github.com/spacegoing/ray_test/blob/master/gpu.yaml)
- rllib (algo: DDPPO) yaml: [rllib_test.yaml](https://github.com/spacegoing/ray_test/blob/master/rllib_test.yaml)

And I run the whole framework by executing following lines in order:

```bash
ray rsync_up gpu.yaml './rllib_test.yaml' '~/rllib_test.yaml'
ray exec gpu.yaml "rllib train -f rllib_test.yaml"
```
----
Problem:

As you may see, in [gpu.yaml](https://github.com/spacegoing/ray_test/blob/master/gpu.yaml) I configured ray cluster to use p2.xlarge (it has 1 GPU / instance). and in  [rllib_test.yaml](https://github.com/spacegoing/ray_test/blob/master/rllib_test.yaml) I configure to run `4 workers`, each worker with `1 GPU`. Therefore, ideally autoscaler should create `4 p2.xlarge ` in total.

However, my after `ray exec`, the `rllib` task is forever pending and get "insufficient_resources_manager" warning:
![Screen Shot 2022-07-03 at 01 29 57](https://user-images.githubusercontent.com/5180020/177010504-b60c525d-ee8b-4ebc-8594-833b5df51587.png)

And there is only 1 worker created.
![Screen Shot 2022-07-03 at 01 20 30](https://user-images.githubusercontent.com/5180020/177010266-90865df8-d67b-4efa-b45d-d970f3e8d094.png)

So I suspect I submitted the RLlib job in the wrong way. Would u please help me with this. Many thanks!

**Comment by pang-wu** [comment]
Can you show the output of `ray monitor gpu.yaml`?

**Comment by spacegoing** [comment]
```
2022-07-05 03:31:10,124	INFO util.py:335 -- setting max workers for head node type to 0
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
Fetched IP: 34.221.94.218
==> /tmp/ray/session_latest/logs/monitor.err <==

==> /tmp/ray/session_latest/logs/monitor.log <==

Resources
---------------------------------------------------------------
Usage:
 0.0/4.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:K80
 0.00/35.141 GiB memory
 0.00/17.571 GiB object_store_memory

Demands:
 {'CPU': 1.0} * 1, {'GPU': 1.0, 'CPU': 1.0} * 4 (PACK): 1+ pending placement groups
2022-07-04 20:30:56,644	INFO autoscaler.py:330 -- 
======== Autoscaler status: 2022-07-04 20:30:56.644292 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_beb6e0fe157ce9e1fc5a79c46f8e5c1adde17949813e962c7f681bdf
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

... several minutes later
Demands:
 {'CPU': 1.0} * 1, {'GPU': 1.0, 'CPU': 1.0} * 4 (PACK): 1+ pending placement groups
2022-07-04 20:32:56,850	INFO autoscaler.py:330 -- 
======== Autoscaler status: 2022-07-04 20:32:56.849912 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_beb6e0fe157ce9e1fc5a79c46f8e5c1adde17949813e962c7f681bdf
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/4.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:K80
 0.00/35.141 GiB memory
 0.00/17.571 GiB object_store_memory


```

**Comment by stephanie-wang** [comment]
Looks like it may be a bug, ccing @DmitriGekhtman to help you further.

**Comment by DmitriGekhtman** [comment]
Redirecting non-K8s-related autoscaler issues to @wuisawesome @cadedaniel

**Comment by ArturNiederfahrenhorst** [comment]
I've reproduced and played a little with resources on the RLlib side to see if the placement groups / resource demands in the monitor change accordingly. This does not seem to be RLlib related to me.

**Comment by wuisawesome** [comment]
@spacegoing can you share your `gpu.yaml`?

**Comment by spacegoing** [comment]
Many Thanks Alex. Links are in this post. https://github.com/ray-project/ray/issues/26172#issuecomment-117293298. Sorry I'm on my phone now.

**Comment by wuisawesome** [comment]
@spacegoing on your worker node can you set `max_workers: 3` in your `ray.worker.default` configuration?

**Comment by spacegoing** [comment]
@wuisawesome Hi Alex, I did a quick test and it didn't work. Here are screenshots FYI:
Yaml:
<img width="689" alt="Screen Shot 2022-07-09 at 09 21 35" src="https://user-images.githubusercontent.com/5180020/178086369-3cfb929b-5fb2-479c-a484-c46d138f7987.png">

`ray exec gpu.yaml "rllib train -f rllib_test.yaml"` output:
<img width="1352" alt="Screen Shot 2022-07-09 at 09 25 42" src="https://user-images.githubusercontent.com/5180020/178086472-18ca9c01-cb8a-4283-9afc-b035e6135f81.png">

`ray monitor gpu.yaml` output:
<img width="947" alt="Screen Shot 2022-07-09 at 09 25 02" src="https://user-images.githubusercontent.com/5180020/178086475-4de59251-368e-45e0-910a-a8cd0ede167d.png">

**Comment by wuisawesome** [comment]
Ah actually, I'm realizing right now that your job is starting its own separate ray "cluster", not connecting to the real one. Can you do `RAY_ADDRESS=auto ray exec gpu.yaml "rllib train -f rllib_test.yaml"`?

**Comment by spacegoing** [comment]
@wuisawesome many thanks for your reply. I tried `RAY_ADDRESS=auto ray exec gpu.yaml "rllib train -f rllib_test.yaml"` in terminal but it seems not making much differences. Here are screenshots:

![Screen Shot 2022-07-12 at 06 19 07](https://user-images.githubusercontent.com/5180020/178368462-a8b66217-98cc-452a-a711-2636139f8e47.png)

![Screen Shot 2022-07-12 at 06 19 29](https://user-images.githubusercontent.com/5180020/178368455-a9f915ba-8bfe-48d2-872f-498612625c58.png)

**Comment by wuisawesome** [comment]
Can you run `ray exec gpu.yaml "ray status"`? without running your script? (and then run it from a separate terminal with the script running?)

**Comment by spacegoing** [comment]
Am I using `ray exec gpu.yaml "ray status"` correctly? In my case this command returns immediately after executing. Below are outputs:

1. `ray status` before running script:
![Screen Shot 2022-07-12 at 07 43 58](https://user-images.githubusercontent.com/5180020/178376844-d3c67de2-f6b1-4ae0-bfc9-68b205476002.png)
2. `ray status` after running `RAY_ADDRESS=auto ray exec gpu.yaml "rllib train -f rllib_test.yaml"`:
```
(aws_neuron_pytorch_p36) ubuntu@ip-172-31-3-39:~/rtest$ ray exec gpu.yaml "ray status"
2022-07-11 23:48:22,962 INFO util.py:335 -- setting max workers for head node type to
0                     
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.                                                                        Fetched IP: 35.165.116.115                                                            Traceback (most recent call last):                                                      File "/home/ray/anaconda3/bin/ray", line 8, in <module>                                 sys.exit(main())                                                                    File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 2339, in main                         
    return cli()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1053, in
main                                                                           
    rv = self.invoke(ctx)                                      
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1659, in
invoke                                                         
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1395, in
invoke  
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 754, in invoke         
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line
1833, in status                                                
    address = services.canonicalize_bootstrap_address(address)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 451, in canonicalize_bootstrap_address
    addr = get_ray_address_from_environment()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 358, in get_ray_address_from_environment
    addr = _find_gcs_address_or_die()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 334, in _find_gcs_address_or_die
    f"Found multiple active Ray instances: {gcs_addresses}. "
ConnectionError: Found multiple active Ray instances: {'172.31.26.9:6379', '172.31.26.9:60361'}. Please specify the one to connect to by setting `--address` flag or `RAY_ADDRESS` environment variable.                                                          
Shared connection to 35.165.116.115 closed.                                          
Error: Command failed:
                                    
  ssh -tt -i ./aws_ray_pt_head.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_1d41c853af/4315291b87/%C -o ControlPersist=10s -o ConnectTimeout=120s ubuntu@35.165.116.115 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (docker exec -it  ray_nvidia_docker /bin/bash -c '"'"'bash --login -c -i '"'"'"'"'"'"'"'"'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (ray status)'"'"'"'"'"'"'"'"''"'"' )'
                
```

**Comment by wuisawesome** [comment]
k 2 things

1. I confused the order of the env var, can you run `ray exec gpu.yaml "RAY_ADDRESS=auto rllib train -f rllib_test.yaml"`
2. It seems that you have multiple head nodes started on the same machine now. Can you rerun `ray down -y gpu.yaml; ray up -y gpu.yaml` to do this on a fresh cluster?

**Comment by spacegoing** [comment]
@wuisawesome Hi Wu, good news. With `ray exec gpu.yaml "RAY_ADDRESS=auto rllib train -f rllib_test.yaml"`, the autoscaler is working now! I see workers are spinning up now.

However, a new problem: the algo is still pending and never run. Workers are kept removed because of ideling. Here are screenshots FYI:
<img width="1344" alt="Screen Shot 2022-07-12 at 09 25 29" src="https://user-images.githubusercontent.com/5180020/178388609-41b36bdb-a13e-4409-95f8-c10cb8737246.png">

`RAY_ADDRESS=auto  rllib train -f rllib_test.yaml` outputs, nodes are kept adding and removing because of ideling

<img width="995" alt="Screen Shot 2022-07-12 at 09 26 08" src="https://user-images.githubusercontent.com/5180020/178388618-c8111a9e-932d-46d1-bece-f4608dc52e1d.png">
<img width="994" alt="Screen Shot 2022-07-12 at 09 26 20" src="https://user-images.githubusercontent.com/5180020/178388768-8320311f-58ac-4a5b-a34d-98df9a631539.png">

`ray monitor gpu.yaml` output:
<img width="997" alt="Screen Shot 2022-07-12 at 09 26 49" src="https://user-images.githubusercontent.com/5180020/178388797-f11fe3f5-82da-4ede-9304-86183299b9df.png">

**Comment by spacegoing** [comment]
@wuisawesome yes we can LoL. It works now!!!

Didn't expect the answer is so easy. Many thanks for your help!
