### ISSUE TITLE
[Core] [Quality] Live handle raises unnecessary exception when script ends

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#26198]
### What happened + What you expected to happen

If a Ray actor handle is still alive when a script ends, an unclear error message is logged:

```
Exception ignored in: <function ActorHandle.__del__ at 0x1090428b0>
Traceback (most recent call last):
  File "/Users/shrekris/Desktop/ray/python/ray/actor.py", line 1028, in __del__
AttributeError: 'NoneType' object has no attribute 'worker'
```

I would expect nothing to be logged since nothing went wrong.

### Versions / Dependencies

Ray on the latest master, Python 3.8, MacOS 11.4 (M1)

### Reproduction script

Repro script:

```python
# File name: error.py
import ray

ray.init()

@ray.remote
class A: pass

handle = A.remote()
```

Error message:

```console
(ae) shrekris@Shreyas-MacBook-Pro manual % python error.py 
2022-06-29 11:33:24,833	INFO services.py:1477 -- View the Ray dashboard at http://127.0.0.1:8266
Exception ignored in: <function ActorHandle.__del__ at 0x1090428b0>
Traceback (most recent call last):
  File "/Users/shrekris/Desktop/ray/python/ray/actor.py", line 1028, in __del__
AttributeError: 'NoneType' object has no attribute 'worker'
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by shrekris-anyscale** [comment]
I don't think I've seen it recently. This was back in June. I'm okay with closing this issue for now.

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
