### ISSUE TITLE
[RLlib] Error with Python3.9 ('NoneType' object has no attribute 'worker')

### ISSUE THREAD

**Issue by jerry99s** [ray-project/ray#26250]
### What happened + What you expected to happen

After finishing all epochs, it report the following error:

```
Exception ignored in: <function RolloutWorker.__del__ at 0x7f4ad4351430>
Traceback (most recent call last):
  File "/home/songxujie/anaconda3/envs/torch3d/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 465, in _resume_span
TypeError: 'NoneType' object is not callable
Exception ignored in: <function ActorHandle.__del__ at 0x7f4bcb977a60>
Traceback (most recent call last):
  File "/home/songxujie/anaconda3/envs/torch3d/lib/python3.9/site-packages/ray/actor.py", line 1028, in __del__
AttributeError: 'NoneType' object has no attribute 'worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7f4bcb977a60>
Traceback (most recent call last):
  File "/home/songxujie/anaconda3/envs/torch3d/lib/python3.9/site-packages/ray/actor.py", line 1028, in __del__
AttributeError: 'NoneType' object has no attribute 'worker'
```

The bug is very similar to #8003, #16947 and #16955, unless my environment is Python3.9 .

### Versions / Dependencies

Ray 3.0.0.dev0 (Daily Releases)
Python 3.9.7
Torch 1.10.0
Ubuntu 20.04

### Reproduction script

1. train.py:

```
import yaml

import ray
import ray.rllib.algorithms.ddppo as ddppo
from ray.tune.logger import pretty_print

with open('pendulum-ddppo.yaml', 'r', encoding='utf-8') as f:
    config = f.read()
    config = yaml.load(config)
    config = config['pendulum-ddppo']

ray.init()
algo = ddppo.DDPPO(env=config['env'] ,config=config['config'])

for i in range(3):
   result = algo.train()
   print(pretty_print(result))

   if i % 1 == 0:
       checkpoint = algo.save()
       print("checkpoint saved at", checkpoint)

print("here is ok.")
```

2. pendulum-ddppo.yaml

```
pendulum-ddppo:
    env: Pendulum-v1
    run: DDPPO
    stop:
        episode_reward_mean: -300
        timesteps_total: 1500000
    config:
        framework: torch
        rollout_fragment_length: 250
        num_gpus_per_worker: 0
        num_workers: 2
        num_envs_per_worker: 10
        observation_filter: MeanStdFilter
        gamma: 0.95
        sgd_minibatch_size: 50
        num_sgd_iter: 5
        clip_param: 0.3
        vf_clip_param: 10.0
        lambda: 0.1
        lr: 0.00015
```
Then, run with 'python train.py'

### Issue Severity

High: It blocks me from completing my task.

**Comment by tupui** [comment]
Hi @jerry99s, thanks for reporting. I am looking into it. It's a strange issue indeed. You are running a nightly from this week? I am surprised that `ray._private.worker` is evaluated to None here. Did you try any debugging of the underlying code?

**Comment by P90-RushB** [comment]
I also encountered the same error，even run the official cartpole example.
Ray 3.0.0.dev0 (Daily Releases)
Python 3.8.13
Torch 1.12.0
Ubuntu 20.04(wsl)

**Comment by justinxia6dot5** [comment]
I also encountered this error, which was similar to the OP's, except that at the end the "NoneType" is not complaining about not having the attribute "worker", but the variable was assigned a None value and could not proceed with whatever class method that was designed for it.
```
Exception ignored in: <function RolloutWorker.__del__ at 0x00000149E3379D30>
Traceback (most recent call last):
  File "C:\Users\justi\Anaconda3\envs\rllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 461, in _resume_span
TypeError: 'NoneType' object is not callable
Exception ignored in: <function RolloutWorker.__del__ at 0x00000149E3261E50>
Traceback (most recent call last):
  File "C:\Users\justi\Anaconda3\envs\rllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 461, in _resume_span
TypeError: 'NoneType' object is not callable
```
For **reproduction**, I was just going through the basic RLlib PPOTrainer on the Taxi Domain example at https://docs.ray.io/en/master/rllib/index.html by doing
```
$ conda create -n rllib python=3.8
$ conda activate rllib
$ pip install "ray[rllib]" tensorflow 
```
and the source code to run was as in the link, where the first line of import was changed to fit what Ray is supporting currently, i.e. rllib is now using agents instead of algorithms  (minor tip to Ray community: consider modifying the typo here in the link)
```
# Import the RL algorithm (Algorithm) we would like to use.
from ray.rllib.agents.ppo import PPOTrainer

# Configure the algorithm.
config = {
    # Environment (RLlib understands openAI gym registered strings).
    "env": "Taxi-v3",
    # Use 2 environment workers (aka "rollout workers") that parallelly
    # collect samples from their own environment clone(s).
    "num_workers": 2,
    # Change this to "framework: torch", if you are using PyTorch.
    # Also, use "framework: tf2" for tf2.x eager execution.
    "framework": "tf",
    # Tweak the default model provided automatically by RLlib,
    # given the environment's observation- and action spaces.
    "model": {
        "fcnet_hiddens": [64, 64],
        "fcnet_activation": "relu",
    },
    # Set up a separate evaluation worker set for the
    # `algo.evaluate()` call after training (see below).
    "evaluation_num_workers": 1,
    # Only for evaluation runs, render the env.
    "evaluation_config": {
        "render_env": True,
    },
}

# Create our RLlib Trainer.
algo = PPOTrainer(config=config)

# Run it for n training iterations. A training iteration includes
# parallel sample collection by the environment workers as well as
# loss calculation on the collected batch and a model update.
for _ in range(3):
    print(algo.train())

# Evaluate the trained Trainer (and render each timestep to the shell's
# output).
algo.evaluate()

```

The version and dependencies I was using are:
Ray 1.13.0
Python 3.8.13
tensorflow 2.9.1
Windows 10


Thanks!

**Comment by kouroshHakha** [comment]
I have reproduced @justinxia6dot5 's error with python=3.8 and it is related to this line of code https://sourcegraph.com/github.com/ray-project/ray/-/blob/rllib/evaluation/rollout_worker.py?L1708. It is a very weird garbage collection issue. It seems that this is reproducible even in python 3.8.

**Comment by kouroshHakha** [comment]
minimal script is actually much simpler:
```
from ray.rllib.algorithms.ppo.ppo import PPO, PPOConfig

config = (
    PPOConfig()
    .environment(env="CartPole-v0")
)
algo = PPO(config=config)
#del algo
```
uncommenting the last line (explicitly garbage collecting algo) will mitigate the issue.

**Comment by rkooo567** [comment]
But in a glance, it looks like a core bug, and I think we should take it over. cc @scv119

**Comment by kouroshHakha** [comment]
@rkooo567 so on master it gives the same error (I have not reproduced it on 1.13 myself)
On 1.12 the script should be modified a bit due to API changes, but the interesting part is that **IT DOES NOT ERROR**.
```
from ray.rllib.agents.ppo.ppo import PPOTrainer, DEFAULT_CONFIG

config = DEFAULT_CONFIG
config.update(env="CartPole-v0")
algo = PPOTrainer(config=config)
```

**Comment by rkooo567** [comment]
Hmm cannot reproduce in MacOS 

Python 3.8.13
Master (built from the source).

**Comment by sven1977** [comment]
Cannot reproduce either on master, py3.9, Win.

**Comment by rkooo567** [comment]
I found out the fix, although the root cause is way harder to be fixed. But with the fix, you won't see this error anymore at least. I will push a PR in a few days.
