### ISSUE TITLE
RLlib A3C AttributeError: 'RolloutWorker' object has no attribute 'tf_sess'

### ISSUE THREAD

**Issue by jiewu-stanford** [ray-project/ray#26271]
Attempted to adapt the PPO trainer script to run A3C trainer in RLlib but got the following error:

```
2022-07-02 16:05:44,986    ERROR trial_runner.py:773 -- Trial A3C_3_vs_3_auto_GK_d291d_00000: Error processing event.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trial_runner.py", line 739, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/ray_trial_executor.py", line 746, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/usr/local/lib/python3.7/dist-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ray/worker.py", line 1621, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::A3C.train() (pid=2558, ip=172.28.0.2, repr=A3C)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer.py", line 648, in train
    raise e
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer.py", line 637, in train
    result = Trainable.train(self)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trainable.py", line 237, in train
    result = self.step()
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer_template.py", line 193, in step
    res = next(self.train_exec_impl)
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 828, in add_wait_hooks
    item = next(it)
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 551, in base_iterator
    batch = ray.get(obj_ref)
ray.exceptions.RayTaskError(AttributeError): ray::RolloutWorker.par_iter_next_batch() (pid=2558, ip=172.28.0.2, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x7f554dcc4f10>)
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 1157, in par_iter_next_batch
    batch.append(self.par_iter_next())
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 1151, in par_iter_next
    return next(self.local_it)
  File "/usr/local/lib/python3.7/dist-packages/ray/util/iter.py", line 791, in apply_foreach
    result = fn(item)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/execution/rollout_ops.py", line 122, in samples_to_grads
    return get_global_worker().compute_gradients(samples), samples.count
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/evaluation/rollout_worker.py", line 856, in compute_gradients
    if self.tf_sess is not None:
AttributeError: 'RolloutWorker' object has no attribute 'tf_sess'
```

All what I did is simply to use the default config of A3C:

```
from ray.rllib.agents.a3c import DEFAULT_CONFIG
config = DEFAULT_CONFIG.copy()
config = {
    'env': env_name,
    'framework': 'torch',
    "use_critic": True,
    "use_gae": True,
    "rollout_fragment_length": 100,
    "lambda": 0.9517171675473532,
    "grad_clip": 40.0,
    "lr": 0.00022602718266055705,
    "vf_loss_coeff": 0.3503035138680095,
    "entropy_coeff": 0.0004158966184268587,
    "sample_async": True,
    'observation_filter': 'NoFilter',
    'log_level': 'INFO' if not debug else 'DEBUG',
    'ignore_worker_failures': False,
    'multiagent': default_multiagent,
}
a = tune.run('A3C', config=config)
```

I am really not sure where this attribute 'tf_sess' comes from.  Could somebody help me out or it is a bug? Many thanks!

**Comment by jiewu-stanford** [comment]
This turns out to be the Ray version issue. The error occurs for Ray v1.6 but disappears once Ray is upgraded to v1.13
