### ISSUE TITLE
[RLlib] Repeated space doesn't work with DQNTrainer

### ISSUE THREAD

**Issue by ThomasCassimon** [ray-project/ray#26280]
### What happened + What you expected to happen

When using a `ray.rllib.utils.spaces.repeated.Repeated` observation space in combination with the `ray.rllib.agents.dqn.dqn.DQNTrainer`, I am unable to start training.
The training process crashes before any actual training is done, due to various bugs related to support of the `Repeated` space.

Currently a bug that I am running into is that `get_dummy_batch_for_space()` in `space_utils.py` is crashing on line 133 (` return np.full(shape + list(space.shape), fill_value=fill_value, dtype=space.dtype)`) because none of the other branches handle the case of a `Repeated` space and it doesn't have a shape associated with it, but the reproduction script crashes elsewhere, so there's likely more than 1 issue with these spaces.

I would also like to ntoe that RLLib is unable to determine the observation space/action space from this example environment, but this feels like a separate bug?

It appears that this bug report might be related to https://github.com/ray-project/ray/issues/25797

I expect to be able to use the `DQNTrainer` in combination with the `Repeated` space without it crashing.

### Versions / Dependencies

```
gym==0.21.0
ray==1.11.1
numpy==1.22.3
```

Python 3.8.10

Ubuntu 20.04 LTS

### Reproduction script

```
import gym

from ray import tune

from ray.rllib.agents.dqn.dqn import DQNTrainer
from ray.rllib.models.repeated_values import RepeatedValues
from ray.rllib.utils.spaces.repeated import Repeated

def obs_space():
	return Repeated(
		child_space=gym.spaces.Discrete(n=1),
		max_len=2
	)


class TestEnv(gym.Env):
	def __init__():
		self.observation_space = obs_space()
		self.action_space = gym.spaces.Discrete(n=1)

	def __observe():
		return RepeatedValues(
			values=[1],
			lengths=[1],
			max=2
		)

	def reset():
		return self.__observe()

	def step(action):
		return self.__observe(), 1, True, {}

trainer = DQNTrainer

cfg = trainer.get_default_config()


# This crashes because RLLib is unable to determine the action and observation space, this might be a separate bug?
#tune.run(
#	DQNTrainer,
#	stop={"episodes_total": 1},
#	config=cfg
#)

cfg["action_space"] = gym.spaces.Discrete(n=1)
cfg["observation_space"] = obs_space()

tune.run(
	trainer,
	stop={"episodes_total": 1},
	config=cfg
)
```

<details>
<summary>This is the output I am currently seeing</summary>

```

```2022-07-06 17:38:22,016	INFO services.py:1412 -- View the Ray dashboard at http://127.0.0.1:8265
== Status ==
Current time: 2022-07-06 17:38:23 (running for 00:00:00.15)
Memory usage on this node: 2.6/38.3 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/10 CPUs, 0/0 GPUs, 0.0/22.12 GiB heap, 0.0/11.06 GiB objects
Result logdir: /home/user/ray_results/DQNTrainer_2022-07-06_17-38-23
Number of trials: 1/1 (1 PENDING)
+-----------------------------+----------+-------+
| Trial name                  | status   | loc   |
|-----------------------------+----------+-------|
| DQNTrainer_None_ab86b_00000 | PENDING  |       |
+-----------------------------+----------+-------+


(DQNTrainer pid=53414) 2022-07-06 17:38:25,928	INFO trainer.py:2140 -- Your framework setting is 'tf', meaning you are using static-graph mode. Set framework='tf2' to enable eager execution with tf2.x. You may also then want to set eager_tracing=True in order to reach similar execution speed as with static-graph mode.
(DQNTrainer pid=53414) 2022-07-06 17:38:25,928	INFO simple_q.py:154 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting `simple_optimizer=True` if this doesn't work for you.
(DQNTrainer pid=53414) 2022-07-06 17:38:25,928	INFO trainer.py:779 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
2022-07-06 17:38:27,356	ERROR trial_runner.py:920 -- Trial DQNTrainer_None_ab86b_00000: Error processing event.
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 886, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/user/.local/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 675, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/user/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/ray/worker.py", line 1763, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::DQNTrainer.train() (pid=53414, ip=10.0.10.84, repr=DQNTrainer)
  File "/home/user/.local/lib/python3.8/site-packages/ray/tune/trainable.py", line 319, in train
    result = self.step()
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 984, in step
    raise e
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 965, in step
    step_attempt_results = self.step_attempt()
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1044, in step_attempt
    step_results = self._exec_plan_or_training_iteration_fn()
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 2032, in _exec_plan_or_training_iteration_fn
    results = next(self.train_exec_impl)
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 1075, in build_union
    item = next(it)
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/user/local/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/execution/rollout_ops.py", line 263, in sampler
    yield workers.local_worker().sample()
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 751, in sample
    raise ValueError("RolloutWorker has no `input_reader` object! "
ValueError: RolloutWorker has no `input_reader` object! Cannot call `sample()`. You can try setting `create_env_on_driver` to True.
Result for DQNTrainer_None_ab86b_00000:
  date: 2022-07-06_17-38-26
  experiment_id: 3fbf0bf90d4f4f83966cbd78fe21762c
  hostname: ubuntu
  node_ip: 10.0.10.84
  pid: 53414
  timestamp: 1657121906
  trial_id: ab86b_00000
  
== Status ==
Current time: 2022-07-06 17:38:27 (running for 00:00:03.94)
Memory usage on this node: 2.9/38.3 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/10 CPUs, 0/0 GPUs, 0.0/22.12 GiB heap, 0.0/11.06 GiB objects
Result logdir: /home/user/ray_results/DQNTrainer_2022-07-06_17-38-23
Number of trials: 1/1 (1 ERROR)
+-----------------------------+----------+------------------+
| Trial name                  | status   | loc              |
|-----------------------------+----------+------------------|
| DQNTrainer_None_ab86b_00000 | ERROR    | 10.0.10.84:53414 |
+-----------------------------+----------+------------------+
Number of errored trials: 1
+-----------------------------+--------------+--------------------------------------------------------------------------------------------------------------------+
| Trial name                  |   # failures | error file                                                                                                         |
|-----------------------------+--------------+--------------------------------------------------------------------------------------------------------------------|
| DQNTrainer_None_ab86b_00000 |            1 | /home/user/ray_results/DQNTrainer_2022-07-06_17-38-23/DQNTrainer_None_ab86b_00000_0_2022-07-06_17-38-23/error.txt |
+-----------------------------+--------------+--------------------------------------------------------------------------------------------------------------------+

Traceback (most recent call last):
  File "dqn.py", line 49, in <module>
    tune.run(
  File "/home/user/.local/lib/python3.8/site-packages/ray/tune/tune.py", line 633, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [DQNTrainer_None_ab86b_00000])
```

</details>

<details>
<summary>And the `error.txt` file contains the same stack trace</summary>

```
Failure # 1 (occurred at 2022-07-06_17-38-27)
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 886, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/user/.local/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 675, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/user/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/ray/worker.py", line 1763, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): [36mray::DQNTrainer.train()[39m (pid=53414, ip=10.0.10.84, repr=DQNTrainer)
  File "/home/user/.local/lib/python3.8/site-packages/ray/tune/trainable.py", line 319, in train
    result = self.step()
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 984, in step
    raise e
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 965, in step
    step_attempt_results = self.step_attempt()
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1044, in step_attempt
    step_results = self._exec_plan_or_training_iteration_fn()
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 2032, in _exec_plan_or_training_iteration_fn
    results = next(self.train_exec_impl)
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 1075, in build_union
    item = next(it)
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/user/.local/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/execution/rollout_ops.py", line 263, in sampler
    yield workers.local_worker().sample()
  File "/home/user/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 751, in sample
    raise ValueError("RolloutWorker has no `input_reader` object! "
ValueError: RolloutWorker has no `input_reader` object! Cannot call `sample()`. You can try setting `create_env_on_driver` to True.
```
</details>

### Issue Severity

High: It blocks me from completing my task.

**Comment by ThomasCassimon** [comment]
For anyone encountering the aforementioned issue with the `shape` attribute not being set correctly, the following is a possible workaround that works for me:

```
repeated_space = Repeated( ... )

setattr(repeated_space, "_shape", [repeated_space.max_len] + list(repeated_space.child_space.shape))
```

Each `gym.space` has a field `_shape` that can be accessed through a property `shape`. By setting this shape to the correct value, RLlib is able to continue working as if everything is OK, although this may lead to other issues down the line...

**Comment by ThomasCassimon** [comment]
Upon further investigation, I've found that `SampleBatch` concatenation for elements from `Repeated` spaces doesn't seem to work?

The following script gives me the following output:

```
import gym
import numpy as np

from ray.rllib.models.repeated_values import RepeatedValues
from ray.rllib.policy.sample_batch import SampleBatch
from ray.rllib.utils.spaces.repeated import Repeated


space = Repeated(child_space=gym.spaces.Box(-1, 1, (1,)), max_len=5)

obs_1 = space.sample()
obs_2 = space.sample()

batch_1 = SampleBatch({SampleBatch.OBS: obs_1})
batch_2 = SampleBatch({SampleBatch.OBS: obs_2})

print("BATCH 1")
print(batch_1[SampleBatch.OBS])

print("BATCH 2")
print(batch_2[SampleBatch.OBS])

concatd = batch_1.concat_samples([batch_2])

print("BATCH 1")
print(batch_1[SampleBatch.OBS])

print("BATCH 2")
print(batch_2[SampleBatch.OBS])

print("CONCATD")
print(concatd[SampleBatch.OBS])
```

For `ray==1.11.1`:
```
BATCH 1
[[0.3385295]]
BATCH 2
[[-0.8054722 ]
 [ 0.18724944]
 [-0.30337888]
 [-0.10023372]]
BATCH 1
[[0.3385295]]
BATCH 2
[[-0.8054722 ]
 [ 0.18724944]
 [-0.30337888]
 [-0.10023372]]
CONCATD
[[-0.8054722 ]
 [ 0.18724944]
 [-0.30337888]
 [-0.10023372]]
```

For `ray==1.13.0`:
```
BATCH 1
[[0.7035328]]
BATCH 2
[[-0.8922755 ]
 [-0.2667641 ]
 [-0.73433834]
 [ 0.15237445]]
BATCH 1
[[0.7035328]]
BATCH 2
[[-0.8922755 ]
 [-0.2667641 ]
 [-0.73433834]
 [ 0.15237445]]
CONCATD
[[-0.8922755 ]
 [-0.2667641 ]
 [-0.73433834]
 [ 0.15237445]]
```

**Comment by ThomasCassimon** [comment]
Going one step further, I noticed that both `concat()` and `concat_samples()` simply stopped working for complex spaces involving `Repeated`.

Test code:
```
import gym

from ray.rllib.utils.spaces.repeated import Repeated
from ray.rllib.policy.sample_batch import SampleBatch

space = gym.spaces.Dict({
	"box": gym.spaces.Box(-1, 1, (1,)),
	"repeated": Repeated(child_space=gym.spaces.Box(-1, 1, (1,)), max_len=5)
})

obs_1 = space.sample()
obs_2 = space.sample()

batch_1 = SampleBatch({SampleBatch.OBS: obs_1})
batch_2 = SampleBatch({SampleBatch.OBS: obs_2})

print("BATCH 1")
print(batch_1[SampleBatch.OBS])

print("BATCH 2")
print(batch_2[SampleBatch.OBS])

concatd = batch_1.concat_samples([batch_2])
# concatd = batch_1.concat(batch_2)

print("BATCH 1")
print(batch_1[SampleBatch.OBS])

print("BATCH 2")
print(batch_2[SampleBatch.OBS])

print("CONCATD")
print(concatd)
```

<details>
<summary>For `ray==1.11.1`</summary>

```
BATCH 1
OrderedDict([('box', array([-0.14507951], dtype=float32)), ('repeated', [array([-0.89748883], dtype=float32), array([-0.6130012], dtype=float32), array([-0.26814732], dtype=float32), array([0.14204255], dtype=float32), array([0.17315125], dtype=float32)])])
BATCH 2
OrderedDict([('box', array([0.22964387], dtype=float32)), ('repeated', [array([-0.60214466], dtype=float32), array([-0.8637297], dtype=float32), array([0.9500285], dtype=float32), array([0.06685942], dtype=float32), array([-0.39285642], dtype=float32)])])
BATCH 1
OrderedDict([('box', array([-0.14507951], dtype=float32)), ('repeated', [array([-0.89748883], dtype=float32), array([-0.6130012], dtype=float32), array([-0.26814732], dtype=float32), array([0.14204255], dtype=float32), array([0.17315125], dtype=float32)])])
BATCH 2
OrderedDict([('box', array([0.22964387], dtype=float32)), ('repeated', [array([-0.60214466], dtype=float32), array([-0.8637297], dtype=float32), array([0.9500285], dtype=float32), array([0.06685942], dtype=float32), array([-0.39285642], dtype=float32)])])
CONCATD
SampleBatch(0: [])
```
</details>

<details>
<summary>For `ray==1.13.0`</summary>

```
BATCH 1
OrderedDict([('box', array([-0.48365057], dtype=float32)), ('repeated', [array([0.36899945], dtype=float32), array([0.73708457], dtype=float32)])])
BATCH 2
OrderedDict([('box', array([-0.7202338], dtype=float32)), ('repeated', [array([0.7911191], dtype=float32), array([-0.7040191], dtype=float32)])])
BATCH 1
OrderedDict([('box', array([-0.48365057], dtype=float32)), ('repeated', [array([0.36899945], dtype=float32), array([0.73708457], dtype=float32)])])
BATCH 2
OrderedDict([('box', array([-0.7202338], dtype=float32)), ('repeated', [array([0.7911191], dtype=float32), array([-0.7040191], dtype=float32)])])
CONCATD
SampleBatch(0: [])
```
</details>

**Comment by Misterion777** [comment]
Hey, glad somebody else also found this problem. It seems, Rllib support for Repeated is buggy now, so I removed all repeated space in my project and made fixed Box spaces and handling padding myself. Hope the team will take a look into this problem.

**Comment by kouroshHakha** [comment]
@ThomasCassimon You should not return RepeatedValues yourself from the env restart / step functions. Instead you should use `space.sample()` or create the structure that `sample()` returns. Look at Repeat space for more info on the returned data structure in `sample()`.  You can run the following code to confirm:

```
import gym

from ray import tune

from ray.rllib.agents.dqn.dqn import DQNTrainer
from ray.rllib.utils.spaces.repeated import Repeated

def obs_space():
	return Repeated(
		child_space=gym.spaces.Discrete(n=2),
		max_len=2
	)


class TestEnv(gym.Env):
    def __init__(self, config):
        self.observation_space = obs_space()
        self.action_space = gym.spaces.Discrete(n=1)

    def __observe(self):
        return self.observation_space.sample()

    def reset(self):
        return self.__observe()

    def step(self, action):
        return self.observation_space.sample(), 1, True, {}

cfg = DQNTrainer.get_default_config()
cfg["env"] = TestEnv
cfg["env_config"] = {}

tune.run(
	DQNTrainer,
	stop={"episodes_total": 10},
	config=cfg
)
```
