### ISSUE TITLE
ImportError: cannot import name '_mark_annotated'

### ISSUE THREAD

**Issue by pmy0721** [ray-project/ray#26315]
### What happened + What you expected to happen

I want to run the code of https://github.com/ray-project/ray/blob/master/rllib/examples/two_step_game.py, but I meet the error as follows:

Traceback (most recent call last):
  File "G:/Python3/RL/Pytorch/moziai/mozi_windows_ai_dev_code/moziai/mozi_ai_sdk/sc_code/ray_test6.py", line 12, in <module>
    from ray.rllib.agents import with_common_config
  File "C:\Users\pmy\anaconda3\envs\virtualpy369\lib\site-packages\ray\rllib\__init__.py", line 7, in <module>
    from ray.rllib.env.base_env import BaseEnv
  File "C:\Users\pmy\anaconda3\envs\virtualpy369\lib\site-packages\ray\rllib\env\__init__.py", line 1, in <module>
    from ray.rllib.env.base_env import BaseEnv
  File "C:\Users\pmy\anaconda3\envs\virtualpy369\lib\site-packages\ray\rllib\env\base_env.py", line 6, in <module>
    from ray.rllib.utils.annotations import Deprecated, DeveloperAPI, PublicAPI
  File "C:\Users\pmy\anaconda3\envs\virtualpy369\lib\site-packages\ray\rllib\utils\__init__.py", line 4, in <module>
    from ray.rllib.utils.annotations import override, PublicAPI, DeveloperAPI
  File "C:\Users\pmy\anaconda3\envs\virtualpy369\lib\site-packages\ray\rllib\utils\annotations.py", line 1, in <module>
    from ray.rllib.utils.deprecation import Deprecated
  File "C:\Users\pmy\anaconda3\envs\virtualpy369\lib\site-packages\ray\rllib\utils\deprecation.py", line 6, in <module>
    from ray.util.annotations import _mark_annotated
ImportError: cannot import name '_mark_annotated'

Process finished with exit code 1

### Versions / Dependencies

Ray ---- 1.12.1
Python ---- 3.6
OS ---- win10

### Reproduction script

from ray.util.annotations import    _mark_annotated

But there is no _mark_annotated in the annotations.py

### Issue Severity

Low: It annoys or frustrates me.

**Comment by stefan4444** [comment]
Is there a workaround until this issue is fixed?

**Comment by kouroshHakha** [comment]
Can you try the latest release? I was able to confirm that the script runs on the master branch.

**Comment by kouroshHakha** [comment]
closing this issue as it seems to have been fixed on master.
