### ISSUE TITLE
[Core] Ray Example-Cluster Timeout from Quickstart NoHelm

### ISSUE THREAD

**Issue by Anando304** [ray-project/ray#26375]
### **Context**

I was following the guide [here](https://docs.ray.io/en/latest/cluster/job-submission.html) on being able to start a ray cluster **without helm.**

### **Problem**

The [example_cluster.yaml](https://github.com/ray-project/ray/blob/master/deploy/components/example_cluster.yaml) used for running a ray cluster seems to be having **trouble port-forwarding** as it is **timing out**.

I suspect this is likely a configuration setting in the yaml that is causing this since it is quite old.

**Timeout when port-forwarding and navigating to localhost:8265**
```
Handling connection for 8265
E0707 18:35:27.421779   23849 portforward.go:400] an error occurred forwarding 8265 -> 8265: error forwarding port 8265 to pod ef7d5be5015b3cf32016dedc43bd3cd0ef3192480a1f1e338afdfceb72ebd904, uid : failed to execute portforward in network namespace "/var/run/netns/cni-65a38638-d718-de76-c514-02f279d78b3d": failed to dial 8265: dial tcp4 127.0.0.1:8265: connect: connection refused
Handling connection for 8265

```

After looking at the cluster logs, it seems as though it might be a memory configuration issue...
```
Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 2339, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py", line 852, in wrapper
    return f(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 738, in start
    ray_params, head=True, shutdown_at_exit=block, spawn_reaper=block
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 300, in __init__
    self.start_ray_processes()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 1130, in start_ray_processes
    huge_pages=self._ray_params.huge_pages,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 2044, in determine_plasma_store_config
    object_store_memory, ray_constants.OBJECT_STORE_MINIMUM_MEMORY_BYTES
ValueError: Attempting to cap object store memory usage at 60947251 bytes, but the minimum allowed is 78643200 bytes.
```

### Steps to reproduce error 
Download the RayCLuster CRD, Operator cluster-scoped, and example-cluster yaml files from [here](https://docs.ray.io/en/latest/cluster/job-submission.html)

Run the following commands in order:
- `kubectl create -n <namespace> -f ./src/python/twitter/ml/tfx/experimental/nohelm/cluster_crd.yaml`
- `kubectl create -n <namespace> -f ./src/python/twitter/ml/tfx/experimental/nohelm/operator_cluster_scoped.yaml`

Run the following command to deploy the cluster to a different namespace than the CRD above:
- `kubectl create -n <NAMESPACE2> -f ./src/python/twitter/ml/tfx/experimental/nohelm/example_cluster.yaml`

Port forward:
- Get the name of the example cluster head pod: `kubectl -n <NAMESPACE2> get pods
- `kubectl -n <NAMESPACE2> port-forward <CLUSTER_NAME> 8265:8265

Now navigate to **localhost:8265**.

This should cause a timeout error similar to the following...
<img width="1550" alt="Screen Shot 2022-07-07 at 6 10 09 PM" src="https://user-images.githubusercontent.com/45672939/177883925-9855e4ff-bac5-43d5-9d2f-35c276f07b2c.png">

### Attempts at Solution

It seems as though the [example_cluster.yaml](https://github.com/ray-project/ray/blob/master/deploy/components/example_cluster.yaml) may be outdated and have insufficient memory and cpu amounts.

The error is quite similar to that of another user found [here](https://discuss.ray.io/t/valueerror-attempting-to-cap-object-store-memory-usage-at-67108864-bytes-but-the-minimum-allowed-is-78643200-bytes/1294/2).

I tried the changes from the above link as shown below

The following changes:
- change the cpu to 1
- change the memory to 4Gi
- change the ephermeral-storage to 4Gi

Even after increasing the memory and cpu, I still seem to get the same issue.

### Link

Existing documentation followed: https://docs.ray.io/en/latest/cluster/kubernetes-advanced.html#deploying-without-helm

**Comment by Anando304** [comment]
Any idea what might be causing this? I already tried the suggestions [here](https://discuss.ray.io/t/valueerror-attempting-to-cap-object-store-memory-usage-at-67108864-bytes-but-the-minimum-allowed-is-78643200-bytes/1294/2), but the port-forward still seems to timeout.

### Yaml CHANGES:
I did the following changes to the [example_cluster.yaml](https://github.com/ray-project/ray/blob/master/deploy/components/example_cluster.yaml):
**Increased the cpu, memory, and ephermal-storage**
```
resources:
  requests:
    cpu: 1
    memory: 4Gi
    ephemeral-storage: 4Gi
  limits:
    cpu: 1
```
AND **added an object-store-flag**
```
headStartRayCommands:
    - ray stop
    - ulimit -n 65536; ray start --object-store-memory=100000000 --head --port=6379 --no-monitor --dashboard-host 0.0.0.0 &> /tmp/raylogs


  # Commands to start Ray on worker nodes. You don't need to change this.
  workerStartRayCommands:
    - ray stop
    - ulimit -n 65536; ray start --object-store-memory=100000000 --address=$RAY_HEAD_IP:6379 &> /tmp/raylogs
```


### RESULTS
The memory issue shown in the logs seem to be gone but the port-forwarding still seems to fail. The cluster logs seem normal:

```
2022-07-08 10:39:18,913 INFO services.py:1476 -- View the Ray dashboard at http://7.255.242.88:8265/
2022-07-08 10:39:15,170 INFO usage_lib.py:325 -- Usage stats collection is enabled. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.
2022-07-08 10:39:15,171 INFO scripts.py:715 -- Local node IP: 7.255.242.88
2022-07-08 10:39:19,293 SUCC scripts.py:757 -- --------------------
2022-07-08 10:39:19,293 SUCC scripts.py:758 -- Ray runtime started.
2022-07-08 10:39:19,293 SUCC scripts.py:759 -- --------------------
2022-07-08 10:39:19,294 INFO scripts.py:761 -- Next steps
2022-07-08 10:39:19,294 INFO scripts.py:762 -- To connect to this Ray runtime from another node, run
2022-07-08 10:39:19,294 INFO scripts.py:767 --   ray start --address='7.255.242.88:6379'
2022-07-08 10:39:19,294 INFO scripts.py:770 -- Alternatively, use the following Python code:
2022-07-08 10:39:19,294 INFO scripts.py:772 -- import ray
2022-07-08 10:39:19,294 INFO scripts.py:785 -- ray.init(address='auto')
2022-07-08 10:39:19,294 INFO scripts.py:789 -- To connect to this Ray runtime from outside of the cluster, for example to
2022-07-08 10:39:19,294 INFO scripts.py:793 -- connect to a remote cluster from your laptop directly, use the following
2022-07-08 10:39:19,294 INFO scripts.py:796 -- Python code:
2022-07-08 10:39:19,294 INFO scripts.py:798 -- import ray
2022-07-08 10:39:19,294 INFO scripts.py:804 -- ray.init(address='ray://<head_node_ip_address>:10001')
2022-07-08 10:39:19,294 INFO scripts.py:810 -- If connection fails, check your firewall settings and network configuration.
2022-07-08 10:39:19,294 INFO scripts.py:816 -- To terminate the Ray runtime, run
2022-07-08 10:39:19,294 INFO scripts.py:817 --   ray stop
```


I also tried to force the connection to stay active using suggestions from [here](https://stackoverflow.com/questions/47484312/kubectl-port-forwarding-timeout-issue), but still same issue.
Any suggestions?

**Comment by DmitriGekhtman** [comment]
I'd love to pair program on this, as we have been seeing dashboard port-forwarding issues off and on K8s.
https://github.com/ray-project/ray/issues/25909

**Comment by Anando304** [comment]
Seems like we resolved the timeout issue!

### Solution:
Updating the **example-cluster.yaml** used for deploying the ray cluster via no helm approach, did the trick:
```
apiVersion: cluster.ray.io/v1
kind: RayCluster
metadata:
  name: example-cluster
spec:
  # The maximum number of workers nodes to launch in addition to the head node.
  maxWorkers: 3
  # The autoscaler will scale up the cluster faster with higher upscaling speed.
  # E.g., if the task requires adding more nodes then autoscaler will gradually
  # scale up the cluster in chunks of upscaling_speed*currently_running_nodes.
  # This number should be > 0.
  upscalingSpeed: 1.0
  # If a node is idle for this many minutes, it will be removed.
  idleTimeoutMinutes: 5
  # Specify the pod type for the ray head node (as configured below).
  headPodType: head-node
  # Optionally, configure ports for the Ray head service.
  # The ports specified below are the defaults.
  headServicePorts:
    - name: client
      port: 10001
      targetPort: 10001
    - name: dashboard
      port: 8265
      targetPort: 8265
    - name: ray-serve
      port: 8000
      targetPort: 8000
  # Specify the allowed pod types for this ray cluster and the resources they provide.
  podTypes:
    - name: head-node
      podConfig:
        apiVersion: v1
        kind: Pod
        metadata:
          # The operator automatically prepends the cluster name to this field.
          generateName: ray-head-
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          restartPolicy: Never
          # This volume allocates shared memory for Ray to use for its plasma
          # object store. If you do not provide this, Ray will fall back to
          # /tmp which cause slowdowns if is not a shared memory volume.
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
          containers:
            - name: ray-node
              imagePullPolicy: Always
              image: rayproject/ray:latest
              # Do not change this command - it keeps the pod alive until it is
              # explicitly killed.
              command: ["/bin/bash", "-c", "--"]
              args: ["trap : TERM INT; touch /tmp/raylogs; tail -f /tmp/raylogs; sleep infinity & wait;"]
              ports:
                - containerPort: 6379  # Redis port for Ray <= 1.10.0. GCS server port for Ray >= 1.11.0.
                - containerPort: 10001  # Used by Ray Client
                - containerPort: 8265  # Used by Ray Dashboard
                - containerPort: 8000 # Used by Ray Serve

              # This volume allocates shared memory for Ray to use for its plasma
              # object store. If you do not provide this, Ray will fall back to
              # /tmp which cause slowdowns if is not a shared memory volume.
              volumeMounts:
                - mountPath: /dev/shm
                  name: dshm
              resources:
                requests:
                  cpu: 1000m
                  memory: 1Gi
                  ephemeral-storage: 1Gi
                limits:
                  cpu: 1000m
                  # The maximum memory that this pod is allowed to use. The
                  # limit will be detected by ray and split to use 10% for
                  # redis, 30% for the shared memory object store, and the
                  # rest for application memory. If this limit is not set and
                  # the object store size is not set manually, ray will
                  # allocate a very large object store in each pod that may
                  # cause problems for other pods.
                  memory: 1Gi
    - name: worker-node
      # Minimum number of Ray workers of this Pod type.
      minWorkers: 2
      # Maximum number of Ray workers of this Pod type. Takes precedence over minWorkers.
      maxWorkers: 3
      # User-specified custom resources for use by Ray.
      # (Ray detects CPU and GPU from pod spec resource requests and limits, so no need to fill those here.)
      rayResources: {"example-resource-a": 1, "example-resource-b": 1}
      podConfig:
        apiVersion: v1
        kind: Pod
        metadata:
          # The operator automatically prepends the cluster name to this field.
          generateName: ray-worker-
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          restartPolicy: Never
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
          containers:
            - name: ray-node
              imagePullPolicy: Always
              image: rayproject/ray:latest
              command: ["/bin/bash", "-c", "--"]
              args: ["trap : TERM INT; touch /tmp/raylogs; tail -f /tmp/raylogs; sleep infinity & wait;"]
              # This volume allocates shared memory for Ray to use for its plasma
              # object store. If you do not provide this, Ray will fall back to
              # /tmp which cause slowdowns if is not a shared memory volume.
              volumeMounts:
                - mountPath: /dev/shm
                  name: dshm
              resources:
                requests:
                  cpu: 1000m
                  memory: 1Gi
                  ephemeral-storage: 1Gi
                limits:
                  cpu: 1000m
                  # The maximum memory that this pod is allowed to use. The
                  # limit will be detected by ray and split to use 10% for
                  # redis, 30% for the shared memory object store, and the
                  # rest for application memory. If this limit is not set and
                  # the object store size is not set manually, ray will
                  # allocate a very large object store in each pod that may
                  # cause problems for other pods.
                  memory: 1Gi
  # Commands to start Ray on the head node. You don't need to change this.
  # Note dashboard-host is set to 0.0.0.0 so that Kubernetes can port forward.
  headStartRayCommands:
    - ray stop
    - ulimit -n 65536; ray start --head --port=6379 --no-monitor --dashboard-host 0.0.0.0 &> /tmp/raylogs
  # Commands to start Ray on worker nodes. You don't need to change this.
  workerStartRayCommands:
    - ray stop
    - ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379 &> /tmp/raylogs
```

the difference is adding:
      
```
 annotations:
          sidecar.istio.io/inject: "false"
```
to each pod.

**Istio** is a mesh network add-on to Kubernetes, that injects a sidecar into every pod which can cause some issues. We can disable it on a pod-by-pod basis with that annotation. This resolves the problem. All other yaml files can stay as is, only the `example-cluster.yaml` changed to the above is needed.
