### ISSUE TITLE
[Core] Deadlock when actor is failed

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#26414]
### What happened + What you expected to happen

When actor is dead and driver submitting tasks, there is a deadlock. The deadlock is caused by GIL in python. 

In this https://github.com/ray-project/ray/issues/12644, NOGIL is removed and this is the root cause.

### Versions / Dependencies

master

### Reproduction script

kill actor and submit task in the same time.

### Issue Severity

High: It blocks me from completing my task.

**Comment by iycheng** [comment]
```
#1  0x00007fa43044020e in absl::lts_20211102::synchronization_internal::Waiter::Wait(absl::lts_20211102::synchronization_internal::KernelTimeout) () from /home/ray/anaconda3/lib/python3.9/site-packages/ra
y/_raylet.so
#2  0x00007fa430440143 in AbslInternalPerThreadSemWait_lts_20211102 () from /home/ray/anaconda3/lib/python3.9/site-packages/ray/_raylet.so
#3  0x00007fa43043ea73 in absl::lts_20211102::Mutex::Block(absl::lts_20211102::base_internal::PerThreadSynch*) () from /home/ray/anaconda3/lib/python3.9/site-packages/ray/_raylet.so
#4  0x00007fa43043f7f4 in absl::lts_20211102::Mutex::LockSlowLoop(absl::lts_20211102::SynchWaitParams*, int) () from /home/ray/anaconda3/lib/python3.9/site-packages/ray/_raylet.so
#5  0x00007fa43043fa1c in absl::lts_20211102::Mutex::LockSlowWithDeadline(absl::lts_20211102::MuHowS const*, absl::lts_20211102::Condition const*, absl::lts_20211102::synchronization_internal::KernelTimeo
ut, int) () from /home/ray/anaconda3/lib/python3.9/site-packages/ray/_raylet.so
#6  0x00007fa42fb4820a in absl::lts_20211102::Mutex::LockSlow(absl::lts_20211102::MuHowS const*, absl::lts_20211102::Condition const*, int) () from /home/ray/anaconda3/lib/python3.9/site-packages/ray/_ray
let.so
#7  0x00007fa42fd6cb71 in ray::core::CoreWorkerDirectActorTaskSubmitter::PendingTasksFull(ray::ActorID const&) const () from /home/ray/anaconda3/lib/python3.9/site-packages/ray/_raylet.so
#8  0x00007fa42fd47bb3 in ray::core::CoreWorker::SubmitActorTask(ray::ActorID const&, ray::core::RayFunction const&, std::vector<std::unique_ptr<ray::TaskArg, std::default_delete<ray::TaskArg> >, std::all
ocator<std::unique_ptr<ray::TaskArg, std::default_delete<ray::TaskArg> > > > const&, ray::core::TaskOptions const&) () from /home/ray/anaconda3/lib/python3.9/site-packages/ray/_raylet.so
#9  0x00007fa42fc62036 in __pyx_pw_3ray_7_raylet_10CoreWorker_61submit_actor_task(_object*, _object*, _object*) () from /home/ray/anaconda3/lib/python3.9/site-packages/ray/_raylet.so
#10 0x000055d0ba93020b in method_vectorcall_VARARGS_KEYWORDS (func=<optimized out>, args=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at /home/builder/ktietz/cos6/ci_cos6/python-split
_1622827272909/work/Objects/descrobject.c:346
#11 0x000055d0ba8881a4 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7fa17802d390, callable=0x7fa430994d60, tstate=<optimized out>) at /home/builder/ktietz/cos6/ci_cos6/python
-split_1622827272909/work/Include/cpython/abstract.h:118
#12 PyObject_Vectorcall () at /home/builder/ktietz/cos6/ci_cos6/python-split_1622827272909/work/Include/cpython/abstract.h:127
#13 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x55d0bd0dc610) at /home/builder/ktietz/cos6/ci_cos6/python-split_1622827272909/work/Python/ceval.c:5072
#14 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7fa17802d1c0, throwflag=<optimized out>) at /home/builder/ktietz/cos6/ci_cos6/python-split_1622827272909/work/Python/ceval.c:3504
#15 0x000055d0ba93b3fd in _PyEval_EvalFrame () at /home/builder/ktietz/cos6/ci_cos6/python-split_1622827272909/work/Include/internal/pycore_ceval.h:40
#16 _PyEval_EvalCode (qualname=0x7fa429d578f0, name=<optimized out>, closure=0x0, kwdefs=0x0, defcount=<optimized out>, defs=0x7fa429d57dc8, kwstep=1, kwcount=<optimized out>, kwargs=<optimized out>, kwna
mes=0x7fa42a260e18, argcount=<optimized out>, args=<optimized out>, locals=0x0, globals=<optimized out>, _co=<optimized out>, tstate=0x55d0bd0dc610) at /home/builder/ktietz/cos6/ci_cos6/python-split_16228
27272909/work/Python/ceval.c:4327
#17 _PyFunction_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, stack=<optimized out>, func=0x7fa429d5ac10) at /home/builder/ktietz/cos6/ci_cos6/python-split_1622827272909/work/Objects/call.$
```

```
Thread 10 (Thread 0x7fa414dfa700 (LWP 99)):
#0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7fa414df9330, clockid=<optimized out>, expected=0, futex_word=0x55d0bab20e4c <_PyRuntime+428>) at ../sysdeps/nptl/futex-internal.h:32
0
#1  __pthread_cond_wait_common (abstime=0x7fa414df9330, clockid=<optimized out>, mutex=0x55d0bab20e50 <_PyRuntime+432>, cond=0x55d0bab20e20 <_PyRuntime+384>) at pthread_cond_wait.c:520
#2  __pthread_cond_timedwait (cond=0x55d0bab20e20 <_PyRuntime+384>, mutex=0x55d0bab20e50 <_PyRuntime+432>, abstime=0x7fa414df9330) at pthread_cond_wait.c:665
#3  0x000055d0ba98d72d in PyCOND_TIMEDWAIT (us=<optimized out>, mut=<optimized out>, cond=0x55d0bab20e20 <_PyRuntime+384>) at /home/builder/ktietz/cos6/ci_cos6/python-split_1622827272909/work/Python/condv
ar.h:73
#4  take_gil (tstate=<optimized out>) at /home/builder/ktietz/cos6/ci_cos6/python-split_1622827272909/work/Python/ceval_gil.h:247
#5  0x000055d0ba8bdf92 in PyEval_RestoreThread (tstate=0x7fa3f8246540) at /home/builder/ktietz/cos6/ci_cos6/python-split_1622827272909/work/Python/ceval.c:467
#6  0x000055d0ba9918a8 in PyGILState_Ensure () at /home/builder/ktietz/cos6/ci_cos6/python-split_1622827272909/work/Python/pystate.c:1378
#7  0x00007fa42fc133af in __pyx_f_3ray_7_raylet_async_callback(std::shared_ptr<ray::RayObject>, ray::ObjectID, void*) () from /home/ray/anaconda3/lib/python3.9/site-packages/ray/_raylet.so
#8  0x00007fa42fc0c571 in std::_Function_handler<void (std::shared_ptr<ray::RayObject>, ray::ObjectID, void*), void (*)(std::shared_ptr<ray::RayObject>, ray::ObjectID, void*)>::_M_invoke(std::_Any_data co
nst&, std::shared_ptr<ray::RayObject>&&, ray::ObjectID&&, void*&&) () from /home/ray/anaconda3/lib/python3.9/site-packages/ray/_raylet.so
#9  0x00007fa42fcac287 in std::_Function_handler<void (std::shared_ptr<ray::RayObject>), ray::core::CoreWorker::GetAsync(ray::ObjectID const&, std::function<void (std::shared_ptr<ray::RayObject>, ray::Obj
ectID, void*)>, void*)::{lambda(std::shared_ptr<ray::RayObject>)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<ray::RayObject>&&) () from /home/ray/anaconda3/lib/python3.9/site-packages/ray/_rayle
t.so
#10 0x00007fa42fd98a89 in ray::core::CoreWorkerMemoryStore::Put(ray::RayObject const&, ray::ObjectID const&) () from /home/ray/anaconda3/lib/python3.9/site-packages/ray/_raylet.so
#11 0x00007fa42fd89792 in ray::core::TaskManager::MarkTaskReturnObjectsFailed(ray::TaskSpecification const&, ray::rpc::ErrorType, ray::rpc::RayErrorInfo const*) () from /home/ray/anaconda3/lib/python3.9/s
ite-packages/ray/_raylet.so
#12 0x00007fa42fd72081 in ray::core::CoreWorkerDirectActorTaskSubmitter::DisconnectActor(ray::ActorID const&, long, bool, ray::rpc::ActorDeathCause const&) () from /home/ray/anaconda3/lib/python3.9/site-p
ackages/ray/_raylet.so
#13 0x00007fa42fdc31a6 in ray::core::ActorManager::HandleActorStateNotification(ray::ActorID const&, ray::rpc::ActorTableData const&) () from /home/ray/anaconda3/lib/python3.9/site-packages/ray/_raylet.so
--Type <RET> for more, q to quit, c to continue without paging--

#14 0x00007fa42fe6d0f9 in std::_Function_handler<void (ray::rpc::PubMessage const&), ray::gcs::GcsSubscriber::SubscribeActor(ray::ActorID const&, std::function<void (ray::ActorID const&, ray::rpc::ActorTa
bleData const&)> const&, std::function<void (ray::Status)> const&)::{lambda(ray::rpc::PubMessage const&)#1}>::_M_invoke(std::_Any_data const&, ray::rpc::PubMessage const&) () from /home/ray/anaconda3/lib/
python3.9/site-packages/ray/_raylet.so
#15 0x00007fa42ffa5459 in EventTracker::RecordExecution(std::function<void ()> const&, std::shared_ptr<StatsHandle>) () from /home/ray/anaconda3/lib/python3.9/site-packages/ray/_raylet.so
#16 0x00007fa42ff4dc7b in std::_Function_handler<void (), instrumented_io_context::post(std::function<void ()>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#
```
