### ISSUE TITLE
[RLlib] Subclassing DefaultCallbacks no longer works when passed as callback option

### ISSUE THREAD

**Issue by olipinski** [ray-project/ray#26594]
### What happened + What you expected to happen

I'm uncertain if this is the desired behaviour, but DefaultCallbacks cannot be subclassed and passed to ray tune as an argument to callbacks. It has to be passed in the config. If this is correct, then with the new API, with config objects, I don't see how to pass arguments to the Callback class (i.e. `ray_config.callbacks(Callback(arg=args))`)

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\JetBrains\PyCharm2022.1\scratches\scratch_2.py", line 65, in <module>
    trials = tune.run(
  File "C:\Users\user\Anaconda3\envs\project\lib\site-packages\ray\tune\tune.py", line 655, in run
    runner.setup_experiments(
  File "C:\Users\user\Anaconda3\envs\project\lib\site-packages\ray\tune\trial_runner.py", line 420, in setup_experiments
    self._callbacks.setup(**spec)
  File "C:\Users\user\Anaconda3\envs\project\lib\site-packages\ray\tune\callback.py", line 284, in setup
    callback.setup(**info)
AttributeError: 'MyCallbacks' object has no attribute 'setup'
```

### Versions / Dependencies

Ray RLLib 1.13.0

### Reproduction script

```
"""Example of using RLlib's debug callbacks.

Here we use callbacks to track the average CartPole pole angle magnitude as a
custom metric.
"""

from typing import Dict
import argparse
import numpy as np
import os

import ray
from ray import tune
from ray.rllib.agents.callbacks import DefaultCallbacks
from ray.rllib.env import BaseEnv
from ray.rllib.evaluation import Episode, RolloutWorker
from ray.rllib.policy import Policy

parser = argparse.ArgumentParser()
parser.add_argument(
    "--framework",
    choices=["tf", "tf2", "tfe", "torch"],
    default="tf",
    help="The DL framework specifier.",
)
parser.add_argument("--stop-iters", type=int, default=2000)


class MyCallbacks(DefaultCallbacks):
    def on_episode_end(
        self,
        *,
        worker: RolloutWorker,
        base_env: BaseEnv,
        policies: Dict[str, Policy],
        episode: Episode,
        env_index: int,
        **kwargs
    ):
        # Check if there are multiple episodes in a batch, i.e.
        # "batch_mode": "truncate_episodes".
        if worker.policy_config["batch_mode"] == "truncate_episodes":
            # Make sure this episode is really done.
            assert episode.batch_builder.policy_collectors["default_policy"].batches[
                -1
            ]["dones"][-1], (
                "ERROR: `on_episode_end()` should only be called "
                "after episode is done!"
            )
        pole_angle = np.mean(episode.user_data["pole_angles"])
        print(
            "episode {} (env-idx={}) ended with length {} and pole "
            "angles {}".format(
                episode.episode_id, env_index, episode.length, pole_angle
            )
        )
        episode.custom_metrics["pole_angle"] = pole_angle
        episode.hist_data["pole_angles"] = episode.user_data["pole_angles"]


if __name__ == "__main__":
    args = parser.parse_args()

    ray.init()
    trials = tune.run(
        "PG",
        stop={
            "training_iteration": args.stop_iters,
        },
        config={
            "env": "CartPole-v0",
            "num_envs_per_worker": 2,
            "framework": args.framework,
            # Use GPUs iff `RLLIB_NUM_GPUS` env var set to > 0.
            "num_gpus": int(os.environ.get("RLLIB_NUM_GPUS", "0")),
        },
        callbacks=[MyCallbacks()]
    ).trials

```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by Rohan138** [comment]
The RLlib and Tune callbacks are separate-you should pass your callback directly to the config dictionary, not to `tune.run`.

If you're using an RLlib config object, use e.g. `config = DQNConfig().callbacks(MyCallbacks)`. Note that `tune.run()` does not support RLlib's Config objects yet, so you'll have convert it to a dict before passing it to Tune i.e. `tune.run(config = config.to_dict())`.

**Comment by olipinski** [comment]
> If you're using an RLlib config object, use e.g. `config = DQNConfig().callbacks(MyCallbacks)`. Note that `tune.run()` does not support RLlib's Config objects yet, so you'll have convert it to a dict before passing it to Tune i.e. `tune.run(config = config.to_dict())`.

Is there any way to pass init arguments tot the callback class this way? Or is this not supported for RLlib Callbacks?

**Comment by Rohan138** [comment]
No, the RLlib callbacks can only take in the arguments defined in the documentation.
