### ISSUE TITLE
[k8s Cluster] Autoscaler fails when unable to find pod name 

### ISSUE THREAD

**Issue by spolcyn** [ray-project/ray#26595]
### What happened + What you expected to happen

Bug: The autoscaler occasionally fails with the error "pod not found". This prevents other pods from coming up and generally requires a restart of the operator deployment to resolve.

Expected behavior: If a pod is not found, the autoscaler assumes it's dead and continues functioning

Error trace:
```
cluster,ray:2022-07-15 14:42:00,972     ERROR autoscaler.py:290 -- StandardAutoscaler: Error during autoscaling.
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/ray/autoscaler/_private/autoscaler.py", line 287, in update
    self._update()
  File "/venv/lib/python3.9/site-packages/ray/autoscaler/_private/autoscaler.py", line 339, in _update
    self.process_completed_updates()
  File "/venv/lib/python3.9/site-packages/ray/autoscaler/_private/autoscaler.py", line 648, in process_completed_updates
    self.load_metrics.mark_active(self.provider.internal_ip(node_id))
  File "/venv/lib/python3.9/site-packages/ray/autoscaler/_private/_kubernetes/node_provider.py", line 94, in internal_ip
    pod = core_api().read_namespaced_pod(node_id, self.namespace)
  File "/venv/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 23084, in read_namespaced_pod
    return self.read_namespaced_pod_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/venv/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 23171, in read_namespaced_pod_with_http_info
    return self.api_client.call_api(
  File "/venv/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/venv/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/venv/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/venv/lib/python3.9/site-packages/kubernetes/client/rest.py", line 240, in GET
    return self.request("GET", url,
  File "/venv/lib/python3.9/site-packages/kubernetes/client/rest.py", line 234, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '291ccc15-7bee-46fe-bd63-527f4863cb04', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '933f3b9d-51cf-4b7d-9d0b-c753c174c86c', 'X-Kubernetes-Pf-Prioritylevel-Uid': '67d043b6-5631-4c14-9cd8-df39c5b85070', 'Date': 'Fri, 15 Jul 2022 14:42:00 GMT', 'Content-Length': '232'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"cluster-ray-worker-f4f9h\" not found","reason":"NotFound","details":{"name":"cluster-ray-worker-f4f9h","kind":"pods"},"code":404}
```

### Versions / Dependencies

Ray 1.13, using Ray Operator on k8s, Python 3.9.10, Ubuntu 20.04

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by zhe-thoughts** [comment]
@DmitriGekhtman to verify if this is still a problem on KubeRay, and triage this

**Comment by DmitriGekhtman** [comment]
We can reopen if the issue is detected on KubeRay.
I have some design ideas I'd like to implement soon (https://github.com/ray-project/ray/issues/28036) which would make this kind of error impossible.

**Comment by kaushik143** [comment]
@spolcyn Did you find any possible solution for this?

**Comment by DmitriGekhtman** [comment]
To be clear, I doubt this can happen with the current KubeRay autoscaling support.
