### ISSUE TITLE
[Serve] [Release] `serve_autoscaling_multi_deployment` is failing

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#26679]
This release tests has only 42% success rate the past week. 

From @architkulkarni 

```
These two tests have been flaky. Based on the error messages for  serve_autoscaling_multi_deployment we think we need to increase the instance size because actors are dying.  Increasing the instance size fixed similar release test flakiness in the past.  We'll merge this PR today or tomorrow and see if it improves things
```

Error:
```
Trials finished!
Traceback (most recent call last):
  File "workloads/autoscaling_multi_deployment.py", line 206, in <module>
    main()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "workloads/autoscaling_multi_deployment.py", line 190, in main
    trial_length, NUM_CONNECTIONS, http_host, http_port, all_endpoints=all_endpoints
  File "/home/ray/e2e-tests/workloads/serve_test_utils.py", line 303, in run_wrk_on_all_nodes
    parsed_metrics["per_thread_latency_avg_ms"]
KeyError: 'per_thread_latency_avg_ms'
```

**Comment by simon-mo** [comment]
@architkulkarni will add a PR to do more debugging and I'll take over once PR exists.

**Comment by matthewdeng** [comment]
@simon-mo what's the status of this?

**Comment by simon-mo** [comment]
no longer failing

**Comment by zhe-thoughts** [comment]
Hi @simon-mo : what changed so that it's no longer failing? Was it failing just due to infra and flakiness?

**Comment by simon-mo** [comment]
We didn't get the chance to investigate, it looks like infra flakiness
