### ISSUE TITLE
[Ray AIR : Trainer] Code Sample fails with a stack trace

### ISSUE THREAD

**Issue by dmatrix** [ray-project/ray#26693]
### Description

The [code sample](https://docs.ray.io/en/master/ray-air/key-concepts.html#trainers) in from Ray AIR for Trainers is failing in the master. This is part of the quick start guide for Ray AIR. 
The `preprocessor` works fine. It reads data off the S3 bucket. The next section is to configure the Trainer, where all
breaks loose. 

```
from ray.train.xgboost import XGBoostTrainer

trainer = XGBoostTrainer(
    scaling_config={
        # Number of workers to use for data parallelism.
        "num_workers": 2,
        # Whether to use GPU acceleration.
        "use_gpu": False,
    },
    label_column="target",
    num_boost_round=20,
    params={
        # XGBoost specific params
        "objective": "binary:logistic",
        "eval_metric": ["logloss", "error"],
    },
    datasets={"train": train_dataset, "valid": valid_dataset},
    preprocessor=preprocessor,
)
result = trainer.fit()
print(result.metrics)
```

Results in the following stack trace in the master running `ray, version 3.0.0.dev0`:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/git-repos/ray/python/ray/tune/execution/trial_runner.py:756, in TrialRunner._wait_and_handle_event(self, next_trial)
    754 try:
    755     # Single wait of entire tune loop.
--> 756     event = self.trial_executor.get_next_executor_event(
    757         self._live_trials, next_trial is not None
    758     )
    759     if event.type == _ExecutorEventType.PG_READY:

File ~/git-repos/ray/python/ray/tune/execution/ray_trial_executor.py:910, in RayTrialExecutor.get_next_executor_event(self, live_trials, next_trial_exists)
    909 # First update status of staged placement groups
--> 910 self._stage_and_update_status(live_trials)
    911 while True:
    912     ###################################################################
    913     # when next_trial_exists and there are cached resources
   (...)
    917     # a next trial to run, we return `PG_READY` future for trial
    918     # runner. The next trial can then be scheduled on this PG.

File ~/git-repos/ray/python/ray/tune/execution/ray_trial_executor.py:299, in RayTrialExecutor._stage_and_update_status(self, trials)
    297     continue
--> 299 if not self._pg_manager.stage_trial_pg(trial):
    300     # Break if we reached the limit of pending placement groups.
    301     break

File ~/git-repos/ray/python/ray/tune/execution/placement_groups.py:433, in _PlacementGroupManager.stage_trial_pg(self, trial)
    432 pgf = trial.placement_group_factory
--> 433 return self._stage_pgf_pg(pgf)

File ~/git-repos/ray/python/ray/tune/execution/placement_groups.py:444, in _PlacementGroupManager._stage_pgf_pg(self, pgf)
    442 else:
    443     # This creates the placement group
--> 444     pg = pgf(name=f"{self._prefix}{uuid.uuid4().hex[:8]}")
    446 self._staging[pgf].add(pg)

File ~/git-repos/ray/python/ray/tune/execution/placement_groups.py:211, in PlacementGroupFactory.__call__(self, *args, **kwargs)
    210 # Call with bounded *args and **kwargs
--> 211 return placement_group(*self._bound.args, **kwargs)

File ~/git-repos/ray/python/ray/_private/client_mode_hook.py:155, in client_mode_wrap.<locals>.wrapper(*args, **kwargs)
    154     return ray.get(ref)
--> 155 return func(*args, **kwargs)

File ~/git-repos/ray/python/ray/util/placement_group.py:202, in placement_group(bundles, strategy, name, lifetime, _max_cpu_fraction_per_node)
    198     raise ValueError(
    199         "placement group `lifetime` argument must be either `None` or 'detached'"
    200     )
--> 202 placement_group_id = worker.core_worker.create_placement_group(
    203     name,
    204     bundles,
    205     strategy,
    206     detached,
    207     _max_cpu_fraction_per_node,
    208 )
    210 return PlacementGroup(placement_group_id)

File python/ray/_raylet.pyx:1657, in ray._raylet.CoreWorker.create_placement_group()

TypeError: create_placement_group() takes exactly 4 positional arguments (5 given)

During handling of the above exception, another exception occurred:

TuneError                                 Traceback (most recent call last)
File ~/git-repos/ray/python/ray/tune/tuner.py:192, in Tuner.fit(self)
    191 try:
--> 192     return self._local_tuner.fit()
    193 except Exception as e:

File ~/git-repos/ray/python/ray/tune/impl/tuner_internal.py:146, in TunerInternal.fit(self)
    145     param_space = copy.deepcopy(self._param_space)
--> 146     analysis = self._fit_internal(trainable, param_space)
    147 else:

File ~/git-repos/ray/python/ray/tune/impl/tuner_internal.py:190, in TunerInternal._fit_internal(self, trainable, param_space)
    177 args = {
    178     **self._get_tune_run_arguments(),
    179     **dict(
   (...)
    188     **self._tuner_kwargs,
    189 }
--> 190 analysis = run(
    191     **args,
    192 )
    193 return analysis

File ~/git-repos/ray/python/ray/tune/tune.py:701, in run(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, reuse_actors, trial_executor, raise_on_failed_trial, callbacks, max_concurrent_trials, _experiment_checkpoint_dir, _remote)
    700 while not runner.is_finished() and not state["signal"]:
--> 701     runner.step()
    702     if has_verbosity(Verbosity.V1_EXPERIMENT):

File ~/git-repos/ray/python/ray/tune/execution/trial_runner.py:813, in TrialRunner.step(self)
    811     logger.debug(f"Got new trial to run: {next_trial}")
--> 813 self._wait_and_handle_event(next_trial)
    815 self._stop_experiment_if_needed()

File ~/git-repos/ray/python/ray/tune/execution/trial_runner.py:792, in TrialRunner._wait_and_handle_event(self, next_trial)
    791 else:
--> 792     raise TuneError(traceback.format_exc())

TuneError: Traceback (most recent call last):
  File "/Users/jules/git-repos/ray/python/ray/tune/execution/trial_runner.py", line 756, in _wait_and_handle_event
    event = self.trial_executor.get_next_executor_event(
  File "/Users/jules/git-repos/ray/python/ray/tune/execution/ray_trial_executor.py", line 910, in get_next_executor_event
    self._stage_and_update_status(live_trials)
  File "/Users/jules/git-repos/ray/python/ray/tune/execution/ray_trial_executor.py", line 299, in _stage_and_update_status
    if not self._pg_manager.stage_trial_pg(trial):
  File "/Users/jules/git-repos/ray/python/ray/tune/execution/placement_groups.py", line 433, in stage_trial_pg
    return self._stage_pgf_pg(pgf)
  File "/Users/jules/git-repos/ray/python/ray/tune/execution/placement_groups.py", line 444, in _stage_pgf_pg
    pg = pgf(name=f"{self._prefix}{uuid.uuid4().hex[:8]}")
  File "/Users/jules/git-repos/ray/python/ray/tune/execution/placement_groups.py", line 211, in __call__
    return placement_group(*self._bound.args, **kwargs)
  File "/Users/jules/git-repos/ray/python/ray/_private/client_mode_hook.py", line 155, in wrapper
    return func(*args, **kwargs)
  File "/Users/jules/git-repos/ray/python/ray/util/placement_group.py", line 202, in placement_group
    placement_group_id = worker.core_worker.create_placement_group(
  File "python/ray/_raylet.pyx", line 1657, in ray._raylet.CoreWorker.create_placement_group
TypeError: create_placement_group() takes exactly 4 positional arguments (5 given)


The above exception was the direct cause of the following exception:

TuneError                                 Traceback (most recent call last)
Input In [26], in <cell line: 20>()
      1 from ray.train.xgboost import XGBoostTrainer
      3 trainer = XGBoostTrainer(
      4     scaling_config={
      5         # Number of workers to use for data parallelism.
   (...)
     18     preprocessor=preprocessor,
     19 )
---> 20 result = trainer.fit()
     21 print(result.metrics)

File ~/git-repos/ray/python/ray/train/base_trainer.py:334, in BaseTrainer.fit(self)
    331 trainable = self.as_trainable()
    333 tuner = Tuner(trainable=trainable, run_config=self.run_config)
--> 334 result_grid = tuner.fit()
    335 assert len(result_grid) == 1
    336 try:

File ~/git-repos/ray/python/ray/tune/tuner.py:194, in Tuner.fit(self)
    192         return self._local_tuner.fit()
    193     except Exception as e:
--> 194         raise TuneError(
    195             f"Tune run failed. "
    196             f'Please use tuner = Tuner.restore("'
    197             f'{self._local_tuner.get_experiment_checkpoint_dir()}") to resume.'
    198         ) from e
    199 else:
    200     experiment_checkpoint_dir = ray.get(
    201         self._remote_tuner.get_experiment_checkpoint_dir.remote()
    202     )

TuneError: Tune run failed. Please use tuner = Tuner.restore("/Users/jules/ray_results/XGBoostTrainer_2022-07-18_17-01-55") to resume.
```

**Comment by richardliaw** [comment]
Do you need to rebuild ray?

**Comment by dmatrix** [comment]
I did rebuild and reinstall install it from my dev environment, if that's what you mean?

**Comment by dmatrix** [comment]
I had to rebuild and reinstall it. It seems to run with stack trace:

```
(XGBoostTrainer pid=67597) 2022-07-18 20:24:17,785	WARNING base_trainer.py:162 -- When passing `datasets` to a Trainer, it is recommended to reserve at least 20% of node CPUs for Dataset execution by setting `_max_cpu_fraction_per_node = 0.8` in the Trainer `scaling_config`. Not doing so can lead to resource contention or hangs. See https://docs.ray.io/en/master/data/key-concepts.html#example-datasets-in-tune for more info.
(XGBoostTrainer pid=67597) 2022-07-18 20:24:19,471	INFO main.py:980 -- [RayXGBoost] Created 2 new actors (2 total actors). Waiting until actors are ready for training.
(_RemoteRayXGBoostActor pid=67610) 2022-07-18 20:24:20,520	WARNING __init__.py:192 -- DeprecationWarning: `ray.worker.get_resource_ids` is a private attribute and access will be removed in a future Ray version.
(_RemoteRayXGBoostActor pid=67610)   File "/Users/jules/git-repos/ray/python/ray/_private/workers/default_worker.py", line 237, in <module>
(_RemoteRayXGBoostActor pid=67610)     ray._private.worker.global_worker.main_loop()
(_RemoteRayXGBoostActor pid=67610)   File "/Users/jules/git-repos/ray/python/ray/_private/worker.py", line 754, in main_loop
(_RemoteRayXGBoostActor pid=67610)     self.core_worker.run_task_loop()
(_RemoteRayXGBoostActor pid=67610)   File "/Users/jules/git-repos/ray/python/ray/_private/function_manager.py", line 674, in actor_method_executor
(_RemoteRayXGBoostActor pid=67610)     return method(__ray_actor, *args, **kwargs)
(_RemoteRayXGBoostActor pid=67610)   File "/Users/jules/git-repos/ray/python/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
(_RemoteRayXGBoostActor pid=67610)     return method(self, *_args, **_kwargs)
(_RemoteRayXGBoostActor pid=67610)   File "/opt/miniconda3/envs/ray-build/lib/python3.8/site-packages/xgboost_ray/main.py", line 474, in __init__
(_RemoteRayXGBoostActor pid=67610)     _set_omp_num_threads()
(_RemoteRayXGBoostActor pid=67610)   File "/opt/miniconda3/envs/ray-build/lib/python3.8/site-packages/xgboost_ray/main.py", line 280, in _set_omp_num_threads
(_RemoteRayXGBoostActor pid=67610)     ray_cpus = _ray_get_actor_cpus()
(_RemoteRayXGBoostActor pid=67610)   File "/opt/miniconda3/envs/ray-build/lib/python3.8/site-packages/xgboost_ray/main.py", line 262, in _ray_get_actor_cpus
(_RemoteRayXGBoostActor pid=67610)     resource_ids = ray.worker.get_resource_ids()
(_RemoteRayXGBoostActor pid=67610)   File "/Users/jules/git-repos/ray/python/ray/__init__.py", line 196, in __getattr__
(_RemoteRayXGBoostActor pid=67610)     traceback.print_stack()
(_RemoteRayXGBoostActor pid=67611) 2022-07-18 20:24:20,521	WARNING __init__.py:192 -- DeprecationWarning: `ray.worker.get_resource_ids` is a private attribute and access will be removed in a future Ray version.
(_RemoteRayXGBoostActor pid=67611)   File "/Users/jules/git-repos/ray/python/ray/_private/workers/default_worker.py", line 237, in <module>
(_RemoteRayXGBoostActor pid=67611)     ray._private.worker.global_worker.main_loop()
(_RemoteRayXGBoostActor pid=67611)   File "/Users/jules/git-repos/ray/python/ray/_private/worker.py", line 754, in main_loop
(_RemoteRayXGBoostActor pid=67611)     self.core_worker.run_task_loop()
(_RemoteRayXGBoostActor pid=67611)   File "/Users/jules/git-repos/ray/python/ray/_private/function_manager.py", line 674, in actor_method_executor
(_RemoteRayXGBoostActor pid=67611)     return method(__ray_actor, *args, **kwargs)
(_RemoteRayXGBoostActor pid=67611)   File "/Users/jules/git-repos/ray/python/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
(_RemoteRayXGBoostActor pid=67611)     return method(self, *_args, **_kwargs)
(_RemoteRayXGBoostActor pid=67611)   File "/opt/miniconda3/envs/ray-build/lib/python3.8/site-packages/xgboost_ray/main.py", line 474, in __init__
(_RemoteRayXGBoostActor pid=67611)     _set_omp_num_threads()
(_RemoteRayXGBoostActor pid=67611)   File "/opt/miniconda3/envs/ray-build/lib/python3.8/site-packages/xgboost_ray/main.py", line 280, in _set_omp_num_threads
(_RemoteRayXGBoostActor pid=67611)     ray_cpus = _ray_get_actor_cpus()
(_RemoteRayXGBoostActor pid=67611)   File "/opt/miniconda3/envs/ray-build/lib/python3.8/site-packages/xgboost_ray/main.py", line 262, in _ray_get_actor_cpus
(_RemoteRayXGBoostActor pid=67611)     resource_ids = ray.worker.get_resource_ids()
(_RemoteRayXGBoostActor pid=67611)   File "/Users/jules/git-repos/ray/python/ray/__init__.py", line 196, in __getattr__
(_RemoteRayXGBoostActor pid=67611)     traceback.print_stack()
(XGBoostTrainer pid=67597) 2022-07-18 20:24:20,639	INFO main.py:1025 -- [RayXGBoost] Starting XGBoost training.
(_RemoteRayXGBoostActor pid=67610) [20:24:20] task [xgboost.ray]:4823308560 got new rank 0
(_RemoteRayXGBoostActor pid=67611) [20:24:20] task [xgboost.ray]:5862185280 got new rank 1
```

**Comment by richardliaw** [comment]
Should work now.
