### ISSUE TITLE
[tune] Can't report metric of infinity

### ISSUE THREAD

**Issue by old-bear** [ray-project/ray#2669]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **Ray installed from (source or binary)**: latest wheel package
- **Ray version**: master
- **Python version**: 2.7
- **Exact command to reproduce**: python ray_test.py

### Describe the problem

Can not report metric=float('inf') in the master version of ray.tune. Code snippet:
```
def train_func(config, reporter):  
    for i in range(10):
        time.sleep(1)
        reporter(timesteps_total=i, mean_accuracy=float('inf'))  # <----- HERE

ray.init()
ray.tune.register_trainable("train_func", train_func)

trials = tune.run_experiments({
    "my_experiment": {
        "run": "train_func",
        "stop": {"mean_accuracy": 99},
        "config": {
            "layer1": {
                "class_name": tune.grid_search(["a", "b"]),
                "config": {"lr": tune.grid_search([1, 2])}
            },
        },
        "local_dir": os.path.expanduser("~/tmp")
    }
})
```

When running the code above, it would complain about json serialization of the result:
```
Worker ip unknown, skipping log sync for /Users/Bear/tmp/my_experiment/train_func_0_class_name=a,lr=1_2018-08-16_14-29-56Fh2JI4
Error processing event: Traceback (most recent call last):
  File "/Users/Bear/Workspace/Alps-automl/venv/lib/python2.7/site-packages/ray/tune/trial_runner.py", line 282, in _process_events
    result, terminate=(decision == TrialScheduler.STOP))
  File "/Users/Bear/Workspace/Alps-automl/venv/lib/python2.7/site-packages/ray/tune/trial.py", line 352, in update_last_result
    print("  {}".format(pretty_print(result).replace("\n", "\n  ")))
  File "/Users/Bear/Workspace/Alps-automl/venv/lib/python2.7/site-packages/ray/tune/logger.py", line 208, in pretty_print
    return yaml.safe_dump(json.loads(cleaned), default_flow_style=False)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

### Source code / logs

I think this error originated from here `logger.py`:
```
class _SafeFallbackEncoder(json.JSONEncoder):
    def __init__(self, nan_str="null", **kwargs):
        super(_SafeFallbackEncoder, self).__init__(**kwargs)
        self.nan_str = nan_str

    def iterencode(self, o, _one_shot=False):
        if self.ensure_ascii:
            _encoder = json.encoder.encode_basestring_ascii
        else:
            _encoder = json.encoder.encode_basestring

        def floatstr(o, allow_nan=self.allow_nan, nan_str=self.nan_str):
            return repr(o) if not np.isnan(o) else nan_str     # <-------------- HERE reformat the float object

        _iterencode = json.encoder._make_iterencode(
            None, self.default, _encoder, self.indent, floatstr,
            self.key_separator, self.item_separator, self.sort_keys,
            self.skipkeys, _one_shot)
        return _iterencode(o, 0)

 ...
    cleaned = json.dumps(out, cls=_SafeFallbackEncoder)        <------   float('inf') => 'inf'
    return yaml.safe_dump(json.loads(cleaned), default_flow_style=False)   <---- can't load 'inf' here
```

And It looks like the default JSONEncoder already supports the serialization/parse of float('inf') ,  maybe we could remove the `iterencode` function to use the default?

**Comment by ericl** [comment]
Yeah I agree. We had the custom encoder to produce aws/athena-queryable json, but I don't think that is necessary any more.
