### ISSUE TITLE
[AIR][Nighly-test] Air related release tests are failing 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#26727]
### What happened + What you expected to happen

a bunch of air tests are failing. one of the test failed like following: 

2022-07-18 23:08:26 | air_benchmark_tensorflow_mnist_cpu_1x4 | AIR tests | ml | false | error | 40 | https://buildkite.com/ray-project/release-tests-branch/builds/793#0182137e-3f45-45e8-9576-f0d71968c449 | https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_mWECugke9RzMh79BZQqeykjN/clusters/ses_Gag3aR2kvRZU1zebtdqz4ZPm | -1.0 | true | https://s3-us-west-2.amazonaws.com/ray-wheels/master/c747dd1b707be198e315c5e1cd2cf032b9c1bfe1/ray-3.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl | {}
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2022-07-18 23:09:32 | air_benchmark_pytorch_training_e2e_gpu_1x1_20gb | AIR tests | ml | false | error | 40 | https://buildkite.com/ray-project/release-tests-branch/builds/793#0182137e-3f4f-4262-b972-ecedfbbf560e | https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_mWECugke9RzMh79BZQqeykjN/clusters/ses_LRutPQeLLkYVB3k89ADGGU1V | -1.0 | true | https://s3-us-west-2.amazonaws.com/ray-wheels/master/c747dd1b707be198e315c5e1cd2cf032b9c1bfe1/ray-3.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl | {}
2022-07-18 23:11:24 | air_benchmark_torch_mnist_cpu_1x4 | AIR tests | ml | false | error | 40 | https://buildkite.com/ray-project/release-tests-branch/builds/793#0182137e-3f2e-4601-9b00-60f54e42bc84 | https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_mWECugke9RzMh79BZQqeykjN/clusters/ses_hYz7shvdDZn7STmcupNTrMiH | -1.0 | true | https://s3-us-west-2.amazonaws.com/ray-wheels/master/c747dd1b707be198e315c5e1cd2cf032b9c1bfe1/ray-3.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl | {}
2022-07-18 23:12:11 | air_benchmark_torch_mnist_cpu_4x4 | AIR tests | ml | false | error | 40 | https://buildkite.com/ray-project/release-tests-branch/builds/793#0182137e-3f39-4185-a10a-3f1e218a8cf5 | https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_mWECugke9RzMh79BZQqeykjN/clusters/ses_wMa3AJVJcgbnn78XqAgKFwxD | -1.0 | true | https://s3-us-west-2.amazonaws.com/ray-wheels/master/c747dd1b707be198e315c5e1cd2cf032b9c1bfe1/ray-3.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl | {}
2022-07-18 23:12:51 | air_benchmark_torch_mnist_cpu_4x1 | AIR tests | ml | false | error | 40 | https://buildkite.com/ray-project/release-tests-branch/builds/793#0182137e-3f24-4abd-803f-1fb149f9e9e7 | https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_mWECugke9RzMh79BZQqeykjN/clusters/ses_E47vdiRwKm8CkemqnZi5KCHQ | -1.0 | true | https://s3-us-west-2.amazonaws.com/ray-wheels/master/c747dd1b707be198e315c5e1cd2cf032b9c1bfe1/ray-3.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl | {}
2022-07-18 23:14:07 | air_benchmark_data_bulk_ingest | AIR tests | ml | false | error | 40 | https://buildkite.com/ray-project/release-tests-branch/builds/793#0182137e-3f19-4d87-b2e0-2b04d792ee13 | https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_mWECugke9RzMh79BZQqeykjN/clusters/ses_3d2LLmTm7cThKC15MmQVRiV3 | -1.0 | true | https://s3-us-west-2.amazonaws.com/ray-wheels/master/c747dd1b707be198e315c5e1cd2cf032b9c1bfe1/ray-3.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl | {}
2022-07-18 23:14:53 | air_benchmark_tensorflow_mnist_cpu_4x1 | AIR tests | ml | false | error | 40 | https://buildkite.com/ray-project/release-tests-branch/builds/793#0182137e-3f3f-4e11-b888-bdf7df0b16f2 | https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_mWECugke9RzMh79BZQqeykjN/clusters/ses_qp44v9n4MAVSF6BHF2JCtHBA | -1.0 | true | https://s3-us-west-2.amazonaws.com/ray-wheels/master/c747dd1b707be198e315c5e1cd2cf032b9c1bfe1/ray-3.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl | {}
2022-07-18 23:19:13 | air_benchmark_torch_mnist_gpu_4x1

```
[Run 1/3] Running Tensorflow Ray benchmark
Traceback (most recent call last):
  File "workloads/tensorflow_benchmark.py", line 375, in <module>
    main()
  File "workloads/tensorflow_benchmark.py", line 371, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "workloads/tensorflow_benchmark.py", line 261, in run
    config=config,
  File "workloads/tensorflow_benchmark.py", line 115, in train_tf_ray_air
    use_gpu=use_gpu,
  File "/home/ray/anaconda3/lib/python3.7/typing.py", line 673, in __call__
    raise TypeError(f"Type {self._name} cannot be instantiated; "
TypeError: Type Dict cannot be instantiated; use dict() instead
```
https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_mWECugke9RzMh79BZQqeykjN/clusters/ses_qp44v9n4MAVSF6BHF2JCtHBA?command-history-section=command_history&drivers-section=deployments

### Versions / Dependencies

latest ray

### Reproduction script

release tests

### Issue Severity

High: It blocks me from completing my task.

**Comment by richardliaw** [comment]
I think this is because we merged #25712 and introduced some race condition.

**Comment by richardliaw** [comment]
All of the tests fail with the same problem.

**Comment by jiaodong** [comment]
Re-using same issue for latest staus:

Nightly release tests: https://buildkite.com/ray-project/release-tests-branch/builds/819
Based on commit [8ecd928](https://github.com/ray-project/ray/commit/8ecd928c34db0b23e4aa2a4ea0c8cff25c37b413) merged around 7/25, 12PM



air_benchmark_data_bulk_ingest (8ecd928)
air_benchmark_xgboost_cpu_10 (8ecd928)
air_benchmark_torch_mnist_cpu_4x1 (8ecd928)
air_benchmark_torch_mnist_gpu_4x4 [smoke test] (8ecd928)
air_benchmark_torch_mnist_cpu_1x4 (8ecd928)
air_benchmark_torch_batch_prediction_gpu_1x1_20gb (8ecd928)
air_benchmark_torch_mnist_cpu_4x4 (8ecd928)
air_benchmark_tune_torch_mnist (8ecd928)
air_benchmark_tune_torch_mnist_gpu (8ecd928)
air_benchmark_tensorflow_mnist_cpu_4x1 (8ecd928)
air_benchmark_tensorflow_mnist_cpu_1x4 (8ecd928)
[unstable] air_benchmark_tensorflow_mnist_cpu_4x4 (8ecd928)
air_benchmark_tensorflow_mnist_gpu_4x4 [smoke test] (8ecd928)
air_benchmark_pytorch_training_e2e_gpu_1x1_20gb (8ecd928)
[unstable] air_benchmark_pytorch_training_e2e_gpu_4x4_100gb (8ecd928)

**Comment by zhe-thoughts** [comment]
@scv119 @matthewdeng to see if we still need this

**Comment by matthewdeng** [comment]
All AIR tests passing for 2.0.0rc0. https://buildkite.com/ray-project/release-tests-branch/builds/846
