### ISSUE TITLE
[RLlib] When using `gym.spaces.Dict` as observation_space `export_model` breaks

### ISSUE THREAD

**Issue by Stefan-1313** [ray-project/ray#26782]
### What happened + What you expected to happen

When I create a custom Environment which has a `gym.spaces.Dict` as `observation_space`, I cannot export the model to TorchScript.

For this I use: 
```
agent = SimpleQTrainer(config=config_simple, env=select_env)
agent.get_policy().export_model(export_dir)
```

See below for full code to reproduce the issue.

When running it I get the following error: 
```
2022-07-20 16:19:23,831	WARNING env.py:135 -- Your env doesn't have a .spec.max_episode_steps attribute. This is fine if you have set 'horizon' in your config dictionary, or `soft_horizon`. However, if you haven't, 'horizon' will default to infinity, and your environment will not be reset.
Traceback (most recent call last):
  File "C:\Users\Stefan\Documents\Dev\Ray RLlib\minimal_ray_working_example (with export error)\main_MinWorkingExample.py", line 79, in <module>
    agent.get_policy().export_model(export_dir)
  File "C:\ProgramData\Miniconda3\envs\cenv39rl\lib\site-packages\ray\rllib\policy\torch_policy.py", line 912, in export_model
    traced = torch.jit.trace(self.model, (dummy_inputs, state_ins, seq_lens))
  File "C:\ProgramData\Miniconda3\envs\cenv39rl\lib\site-packages\torch\jit\_trace.py", line 741, in trace
    return trace_module(
  File "C:\ProgramData\Miniconda3\envs\cenv39rl\lib\site-packages\torch\jit\_trace.py", line 958, in trace_module
    module._c._create_method_from_trace(
RuntimeError: Tracer cannot infer type of ({'obs': {'obs_1': tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])}, 'new_obs': {'obs_1': tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])}, 'actions': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0]), 'prev_actions': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0]), 'rewards': tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]), 'prev_rewards': tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]), 'dones': tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]), 'infos': tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]), 'eps_id': tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]), 'unroll_id': tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]), 'agent_index': tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]), 't': tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]), 'q_values': tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), 'action_dist_inputs': tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), 'action_prob': tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]), 'action_logp': tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]), 'state_in_0': tensor([1.]), 'seq_lens': tensor([1.])}, [tensor([1.])], tensor([1.]))
:Dictionary inputs to traced functions must have consistent type. Found Dict[str, Tensor] and Tensor

Process finished with exit code 1

```

I also included (commented) code lines to use a `gym.spaces.Box` as `observation_space`. In the comments is which lines you have to comment+uncomment to switch. Then you can see the issue no longer occurs.

### Versions / Dependencies

Python v3.9.12
pip install Ray==1.13.0
pip install Ray[tune]==1.13.0
pip install Ray[rllib]==1.13.0

### Reproduction script

from typing import Dict, List

import torch.nn as nn
import gym
import numpy as np
from ray.rllib.agents.dqn.simple_q import DEFAULT_CONFIG, SimpleQTrainer
from ray.rllib.models import ModelCatalog
from ray.rllib.models.torch.torch_modelv2 import TorchModelV2
from ray.rllib.utils.typing import TensorType, ModelConfigDict
from ray.tune.registry import register_env

class SimpleEnv(gym.Env):
    def __init__(self):
        self.shape = 4
        self.action_space = gym.spaces.Discrete(self.shape)  # +1 for escape action
        self.observation_space = gym.spaces.Dict({"obs_1": gym.spaces.Box(low=np.float32(0),
                                                                          high=np.float32(1),
                                                                          shape=(self.shape,),
                                                                          dtype=np.float32)})
        # self.observation_space = gym.spaces.Box(low=np.float32(0),
        #                                         high=np.float32(1),
        #                                         shape=(self.shape,),
        #                                         dtype=np.float32)

    def reset(self):
        return {"obs_1": np.zeros(self.shape, dtype=np.float32)}  # Comment out if only using Box gym space.
        # return np.zeros(self.shape, dtype=np.float32)  # Uncomment out if only using Box gym space.

    def step(self, action):
        state = {"obs_1": np.zeros(self.shape, dtype=np.float32)}  # Comment out if only using Box gym space.
        # state = np.zeros(self.shape, dtype=np.float32)  # Uncomment out if only using Box gym space.
        return state, 1, False, {}

class SimpleNetwork(TorchModelV2, nn.Module):
    def __init__(self,
                 obs_space: gym.spaces.Space,
                 action_space: gym.spaces.Space,
                 num_outputs: int,
                 model_config: ModelConfigDict,
                 name: str,
                 **customized_model_kwargs):
        TorchModelV2.__init__(self, obs_space, action_space, num_outputs, model_config, name)
        nn.Module.__init__(self)
        self.layers = nn.Sequential(nn.Linear(in_features=4, out_features=4, bias=True),
                                    nn.ReLU(),
                                    nn.Linear(in_features=4, out_features=num_outputs, bias=True))

    def forward(self, input_dict: Dict[str, TensorType], state: List[TensorType], seq_lens: TensorType) -> (TensorType, List[TensorType]):
        obs = input_dict["obs"]
        obs_1 = obs["obs_1"]  # comment out if only using Box gym space.
        # obs_1 = obs  # Uncomment out if only using Box gym space.

        q_values = self.layers(obs_1)
        return q_values, state

config_simple = DEFAULT_CONFIG.copy()
config_simple["model"] = {"custom_model": "simple_network"}
config_simple["framework"] = "torch"

ModelCatalog.register_custom_model("simple_network", SimpleNetwork)

select_env = "simple_env"
register_env(select_env, lambda config: SimpleEnv())
config_simple["env"] = select_env
config_simple["_disable_preprocessor_api"] = True
config_simple["num_gpus"] = 0

agent = SimpleQTrainer(config=config_simple, env=select_env)

# Train network.
for n in range(2):
    result = agent.train()
agent.stop()

# Export network.
export_dir = r'D:\Default_Folders\Documents\_TEMP\U-SKU-test-runs\TESTER'
agent.get_policy().export_model(export_dir)

### Issue Severity

High: It blocks me from completing my task.

**Comment by Stefan-1313** [comment]
I know about this issue: #26593 of a co-worker. It seems totally different, but the issue there also (only) occurs when using a `gym.spaces.Dict` as `observation_space`. The reproduction code is practically identical.

**Comment by Stefan-1313** [comment]
To summarize, the problem occurs when using both:

- gym.spaces.Dict as observation_space
- setting config_simple["_disable_preprocessor_api"] = True

**Comment by kouroshHakha** [comment]
I have looked into the issue and it is rooted in `torch.jit.trace` not allowing to specify dicts with different value types as input to nn.Modules that are being traced. You can look for more info here: https://github.com/pytorch/pytorch/issues/16847#issuecomment-544227905
The reason that it gets solved with "_disable_preprocessor_api" = True is that under the hood the input sample_batch will only use the flattened tensors and you won't get nested dictionaries with tensor leaves. So I cannot think of any other solutions that would be more elegant here. @Stefan-1313 Do you have any suggestions? I don't see why trace does not support this common use-case by default.

**Comment by Stefan-1313** [comment]
Hi @kouroshHakha ,

Thanks for you looking into it.

**Why we cannot use `"_disable_preprocessor_api" = False`:**
We use a `CustomGymSpace` so that is why `"_disable_preprocessor_api" = True` has to be. For us setting `"_disable_preprocessor_api" = False` is thus not feasible.

**Best solution?**
The best solution is for `torch.jit.trace` to support this, but under the hood it is C++. You can also import these modules in C++ (which we actually do). So I can imagine it is difficult (impossible?) for C++ to handle list/dict/vector types which hold items of different types.

**Our temporary solution:**
For us, we only use the `"obs"` (observation from the environment) key-values in the `input_dict`. We don't use all other stuff in there, so maybe it can simply be left out from the `input_dict`? I don't know if this holds in general so maybe it's not a feasible solution.

I have a work around, which is working but I don't think it is great.
I manually call `torch.jit.trace` on my `custom_model`. Then I provide as inputs an `input_dict` with only the stuff I need (so only consistent datatypes). This is a lot of work to maintain and may break with future versions. It may be hard to generalize this.

**A feasible general solution?**
The forward method of a `custom_module` gets 3 inputs:

- `input_dict: Dict[str, Any]`  ==> But we want this to be `input_dict: Dict[str, TensorType]` to solve the problem.
- `state: List[TensorType]`
- `seq_lens: TensorType`

From my observation the `input_dict` holds only consistent datatypes (of `TensorType`) and ALSO another copy of `state` and `seq_lens`! Especially `state` has a different type and causes the problem. I think both don't have to be inside the `input_dict` as both are already supplied to forward as separate inputs.

So maybe the solution is simple?
Off course there is more I don't know then I do know, so it is very possible I overlook something.

**Comment by Missourl** [comment]
Hello, 

Iam also using my obs space as dict, however I dont understand how can I custom my model . Knowing that Iam using DDPG.

Would anybody please give me some hint?

Thank you
