### ISSUE TITLE
[Core][State Observability] Filtering not handled properly when key missing in the datum  

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#26811]
### What happened + What you expected to happen

```
ray.experimental.state.exception.RayStateApiException: API server internal error. See dashboard.log file for more details. Error: Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/optional_utils.py", line 95, in _handler_route
    return await handler(bind_info.instance, req)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/state/state_head.py", line 107, in async_wrapper
    ret = await func(self, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/state/state_head.py", line 286, in list_workers
    return await self._handle_list_api(self._state_api.list_workers, req)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/state/state_head.py", line 244, in _handle_list_api
    result = await list_api_fn(option=self._options_from_req(req))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/state_aggregator.py", line 293, in list_workers
    result = self._filter(result, option.filters, WorkerState, option.detail)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/state_aggregator.py", line 166, in _filter
    match = datum[filter_column] == filter_value
KeyError: 'exit_type'
```

### Versions / Dependencies

master

### Reproduction script

`ray list workers -f exit_type=INTENDED_SYSTEM_EXIT` when there are active workers.

**Comment by rkooo567** [comment]
I can take this over.
