### ISSUE TITLE
[Core][Nightly] chaos_pipelined_ingestion_1500_gb_15_windows is failing consistently

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#26812]
### What happened + What you expected to happen

<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">chaos_pipelined_ingestion_1500_gb_15_windows is failing consistently</p><div id="user-content-app" dir="auto" style="box-sizing: border-box; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div id="user-content-grid_id" dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div id="user-content-grid_id-panel-grid_id" tabindex="0" dir="auto" style="box-sizing: border-box; outline: none;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div height="627" width="1340" dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div id="user-content-chart-id-417" dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;"><div dir="auto" style="box-sizing: border-box;">

2022-07-17 23:35:37 | chaos_pipelined_ingestion_1500_gb_15_windows | core-dataset-tests | core | false | finished | 0 | https://s3-us-west-2.amazonaws.com/ray-wheels/master/38c9e1d52aeada536a0460fba01b2633973bc989/ray-3.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl | 3832.707908033 | https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_SL9MdqfUezDwUHUkUa4ZH6KD | true | https://buildkite.com/ray-project/release-tests-branch/builds/790#01820e46-da20-4b12-82d5-cfafccabe6c4 | {"ingest_time":2026.4035325050354,"success":1}
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2022-07-18 23:20:33 | chaos_pipelined_ingestion_1500_gb_15_windows | core-dataset-tests | core | false | error | 40 | https://s3-us-west-2.amazonaws.com/ray-wheels/master/c747dd1b707be198e315c5e1cd2cf032b9c1bfe1/ray-3.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl | -1.0 | https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_T5TdcVKkBfau5DWa5sy8ZyLv | true | https://buildkite.com/ray-project/release-tests-branch/builds/793#0182137e-42dd-4efa-8529-709b69132593 | {}
2022-07-19 22:42:01 | chaos_pipelined_ingestion_1500_gb_15_windows | core-dataset-tests | core | false | error | 40 | https://s3-us-west-2.amazonaws.com/ray-wheels/master/fdd5c53bfde12b387138010e00ab27c2bba4db03/ray-3.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl | -1.0 | https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_USzskxhRV4AWE2mA5cjQhVhA | true | https://buildkite.com/ray-project/release-tests-branch/builds/796#0182187f-a88b-4056-b3fa-671378f4dc08 | {}

</div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div>

### Versions / Dependencies

latest ray

### Reproduction script

run it

**Comment by scv119** [comment]
```
Traceback (most recent call last):
  File "dataset/pipelined_training.py", line 329, in <module>
    ray.get(tasks)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py", line 2197, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::consume() (pid=286, ip=10.0.3.153)
  File "dataset/pipelined_training.py", line 276, in consume
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/torch_iterable_dataset.py", line 10, in __iter__
    yield from it
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 2691, in make_generator
    local_shuffle_seed=local_shuffle_seed,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset_pipeline.py", line 195, in iter_batches
    shuffle_seed=local_shuffle_seed,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/block_batching.py", line 129, in batch_blocks
    yield from get_batches(block_window[0])
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/block_batching.py", line 87, in get_batches
    block = ray.get(block)
ray.exceptions.OwnerDiedError: Failed to retrieve object 00065947abc0c379ffffffffffffffffffffffff0300000003000000. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.

The object's owner has exited. This is the Python worker that first created the ObjectRef via `.remote()` or `ray.put()`. Check cluster logs (`/tmp/ray/session_latest/logs/*8c64cd55a63170a04002da365f0b016ac2aededfdae0ccd84a378b35*` at IP address 10.0.3.232) for more information about the Python worker failure.
```

**Comment by scv119** [comment]
Looks it's related to our recent change introduced by local shuffle https://github.com/ray-project/ray/pull/26094

@stephanie-wang @clarkzinzow did we change the ownership model which leads to this failure?

**Comment by scv119** [comment]
[test failed ](https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_2YFF7nnDufbQd1KfExh6fXAr ) at commit 864af14f410ab12c7553332dd3a62e716f24a667

**Comment by scv119** [comment]
[tests running (likely passing)](https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_8FHQVXs8NKxwLptRSk2ESKnF?command-history-section=command_history) at commit 38c9e1d52aeada536a0460fba01b2633973bc989

**Comment by jianoaix** [comment]
> [test failed ](https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_2YFF7nnDufbQd1KfExh6fXAr) at commit [864af14](https://github.com/ray-project/ray/commit/864af14f410ab12c7553332dd3a62e716f24a667)

There was also this error at block splitting:
```
ray.exceptions.RayTaskError: ray::PipelineSplitExecutorCoordinator.next_dataset_if_ready() (pid=3055, ip=10.0.3.109, repr=<ray.data._internal.pipeline_executor.PipelineSplitExecutorCoordinator object at 0x7f2187672b90>)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/pipeline_executor.py", line 155, in next_dataset_if_ready
    self.cur_splits = self.splitter(ds)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset_pipeline.py", line 270, in <lambda>
    n, equal=equal, locality_hints=locality_hints
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 1064, in split
    n,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 1041, in equalize
    smaller_splits, target_size, counts, num_splits - len(new_splits)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 984, in _equalize_smaller_splits
    diff_split, new_low_split = low_split.split_at_indices([diff])
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 1214, in split_at_indices
    blocks, metadata = _split_at_indices(blocks_with_metadata, indices)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/split.py", line 218, in _split_at_indices
    ] = _split_all_blocks(blocks_with_metadata, block_rows, per_block_split_indices)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/split.py", line 151, in _split_all_blocks
    split_single_block_results = ray.get(split_single_block_futures)
ray.exceptions.RayTaskError: ray::_split_single_block() (pid=253, ip=10.0.3.78)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.OwnerDiedError: Failed to retrieve object 00ad0a25ba656727ffffffffffffffffffffffff0300000003000000. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.

The object's owner has exited. This is the Python worker that first created the ObjectRef via `.remote()` or `ray.put()`. Check cluster logs (`/tmp/ray/session_latest/logs/*4540e05b88e8a24fcf3266629b44342fa512def8e6c7eccf83a2a8aa*` at IP address 10.0.3.211) for more information about the Python worker failure.
```

I wonder if there is any interaction between the owned_by_consumer (which free the block after it's been splitted), but that was added after the local shuffle PR.

**Comment by scv119** [comment]
bf97a6944b517978f57fa51ec75c9f78882a91f7 failed:  https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_RkCgWLyjTayXwRUMWgRawedp

**Comment by clarkzinzow** [comment]
@scv119 That's a different release test failure, right?

**Comment by scv119** [comment]
> @scv119 That's a different release test failure, right?

lol, so many bisecting going on and posted on the wrong thread. sorry for the confusion!

**Comment by jianoaix** [comment]
Looked into this with a few hypotheses:
- Interaction with object GC:  Disabling the GC (https://github.com/ray-project/ray/commit/34dc9c1cddd432c564442149e0158d2fe93a6a18), test still failed at the same issue
- The new Batcher: Reverting to the old Batcher (https://github.com/ray-project/ray/pull/27066), test still failed at the same issue
- The torch iterator used in the test itself (why this hypothesis: the Workspace running without torch iterator passed conssistently): Changing to the plain DatasetPipeline iter_batches (https://github.com/ray-project/ray/pull/27070/files),  test still failed at the same issue
- The owner of blocks is not actually the Head node: Logging the owner at failure (https://github.com/ray-project/ray/pull/27079), and it verified the owner was indeed not Head node! (Test: https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_B4nEmbmGNpmi2HjJEcUhTMNZ)

The owner of the failed object:
`(consume pid=292, ip=10.0.3.166) obj ref:  ObjectRef(00a1490e95a50984ffffffffffffffffffffffff0300000003000000)  owner address from objref:  b'\n\x1c\xc4W\x8f0\x85\xdd\xd4\xf5\xf8\x19L\x01!\x94\x13\x15\x9c\x84~-]F\xbe\xd7+\xdf|>\x12\t10.0.3.97\x18\x93N"\x1cE\x9a11]\x87cG<\xd6\xc8q,u<\xc8`\xde\xc9\xcb\xf9Izw\xbf\xc1\xf7\x95'  owner address from core worker:  b'\n\x1c\xc4W\x8f0\x85\xdd\xd4\xf5\xf8\x19L\x01!\x94\x13\x15\x9c\x84~-]F\xbe\xd7+\xdf|>\x12\t10.0.3.97\x18\x93N"\x1cE\x9a11]\x87cG<\xd6\xc8q,u<\xc8`\xde\xc9\xcb\xf9Izw\xbf\xc1\xf7\x95' exception:  Failed to retrieve object 00a1490e95a50984ffffffffffffffffffffffff0300000003000000. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.`

The Head node (from Head start log):
```
2022-07-27 09:08:31,520 VVINFO command_runner.py:512 -- Full command is `ssh -tt -i /tmp/secretu0zxiuhp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_63a9f0ea7b/bcc242f4b0/%C -o ControlPersist=10s -o ConnectTimeout=120s ubuntu@44.234.33.20 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (docker exec -it  ray_container /bin/bash -c '"'"'bash --login -c -i '"'"'"'"'"'"'"'"'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (export RAY_OVERRIDE_RESOURCES='"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'{"CPU":32}'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"';ray stop --force; ulimit -n 65536; cd /home/ray/e2e-tests && ray start --head --port=9031 --object-manager-port=8076 --no-monitor)'"'"'"'"'"'"'"'"''"'"' )'`
Did not find any active Ray processes.

Local node IP: 10.0.3.163

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='10.0.3.163:9031'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto')
  
  To connect to this Ray runtime from outside of the cluster, for example to
  connect to a remote cluster from your laptop directly, use the following
  Python code:
    import ray
    ray.init(address='ray://<head_node_ip_address>:10001')
```

**Comment by jianoaix** [comment]
I tested a PR before the local shuffle PR: https://github.com/ray-project/ray/commit/38c9e1d52aeada536a0460fba01b2633973bc989

It failed with same error: https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_dr8qxiYMr16y2MTfw8WfUAZy

So this indeed seems possible caused by something else. I'll do some bisecting.

**Comment by jianoaix** [comment]
Still running bisecting, but checking the PRs backward from the above PR, I think these two are the possible culprits: 1) https://github.com/ray-project/ray/commit/fb54679a239e4c7368a72a2fe3023cac04380827 and 2) https://github.com/ray-project/ray/commit/feb53d01ab718070584941d43a30e411cf72f5bf.
- How we create objects whose owner are not Head node: The PR (1) _split_single_block used ray.put() to create split results, so the owner is the remote split task, which was launched by the splitting actor to a worker node
- How the test failing faster recently: With PR (2), the remote split tasks were spread, so it's more likely for the Node Killer to kill a node which owns some objects.

**Comment by jianoaix** [comment]
So the test failed at both possible culprits: for (1) https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_PM3SqkZgcd6hffYx8YBvnRSG and for (2) https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_hUCT6LaJD23qWbwC9UbGi6cF

Doing one more verification at 0f0102666a628494ad175c1484cb7cc939a49c87.

**Comment by jianoaix** [comment]
https://github.com/ray-project/ray/commit/0f0102666a628494ad175c1484cb7cc939a49c87 is passing: https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_tYYDUk1TcrEA6HuP4YpHPhn4

So this should conclude the above analysis.
