### ISSUE TITLE
[core/tune] Actor tasks hangs forever after pystan compilation failed

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#26828]
### What happened + What you expected to happen

A proprietary tune training script is using orbit and pystan to fit prediciton models using Ray Tune.

As part of the model fitting, pystan compiles a C++ model:

```
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_ce583eb84b35032d795f7056cd3c761e NOW.
```

this sometimes fails:

```
2022-07-21 01:47:43,896	WARNING worker.py:1404 -- The node with node id: 0c602370c6f7d5929662bad2aa0729e1f502dba1e98f1c9bf9f34cde and address: 172.31.33.51 and node name: 172.31.33.51 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m 2022-07-21 01:47:46,201	ERROR function_runner.py:286 -- Runner Thread raised error.
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m Traceback (most recent call last):
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 178, in _compile
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 980, in spawn
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     spawn(cmd, dry_run=self.dry_run, **kwargs)
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/spawn.py", line 68, in spawn
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     raise DistutilsExecError(
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m 
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m During handling of the above exception, another exception occurred:
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m 
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m Traceback (most recent call last):
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/tune/function_runner.py", line 277, in run
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     self._entrypoint()
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/tune/function_runner.py", line 349, in entrypoint
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     return self._trainable_func(
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 462, in _resume_span
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     return method(self, *_args, **_kwargs)
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/tune/function_runner.py", line 642, in _trainable_func
[omitted]
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/sklearn/pipeline.py", line 346, in fit
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     self._final_estimator.fit(Xt, y, **fit_params_last_step)
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/orbit/forecaster/svi.py", line 30, in fit
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     super().fit(df)
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/orbit/forecaster/forecaster.py", line 131, in fit
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     self._model.set_dynamic_attributes(df=df, training_meta=self.get_training_meta())
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/orbit/template/ktr.py", line 844, in set_dynamic_attributes
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     self._set_levs_and_seas(df, training_meta)
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/orbit/template/ktr.py", line 754, in _set_levs_and_seas
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     ktrlite.fit(df=df)
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/orbit/forecaster/map.py", line 23, in fit
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     super().fit(df)
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/orbit/forecaster/forecaster.py", line 145, in fit
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     _posterior_samples, training_metrics = estimator.fit(
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/orbit/estimators/stan_estimator.py", line 190, in fit
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     compiled_stan_file = get_compiled_stan_model(model_name)
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/orbit/utils/stan.py", line 44, in get_compiled_stan_model
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     compile_stan_model(stan_model_name)
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/orbit/utils/stan.py", line 31, in compile_stan_model
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     sm = StanModel(model_code=model_code)
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/pystan/model.py", line 378, in __init__
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     build_extension.run()
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     self.build_extensions()
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 459, in build_extensions
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     self._build_extensions_serial()
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 485, in _build_extensions_serial
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     self.build_extension(ext)
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 540, in build_extension
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     objects = self.compiler.compile(
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 591, in compile
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m   File "/home/ray/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 180, in _compile
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m     raise CompileError(msg)
[2m[36m(training_fun pid=423, ip=172.31.33.51)[0m distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1
```

These compilation issues can come up multiple times. Eventually we get the message:

```
[2m[36m(pid=gcs_server)[0m [2022-07-21 02:39:09,932 E 159 159] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Connection timed out; RPC Error details: 
[2m[36m(pid=gcs_server)[0m [2022-07-21 02:39:09,932 E 159 159] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Connection timed out; RPC Error details: 
[2m[36m(pid=gcs_server)[0m [2022-07-21 02:39:09,932 E 159 159] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Connection timed out; RPC Error details: 
```

indicating that something happened on the node, e.g. the raylet crashed, the node is OOM, or something else was impacted by the compilation.

Subsequently, Ray Tune hangs when trying to retrieve a future from a training actor:

```
Thread 404 (idle): "MainThread"
    get_objects (ray/worker.py:364)
    get (ray/worker.py:1825)
    wrapper (ray/_private/client_mode_hook.py:105)
    _get_default_result_or_future (ray/tune/trial.py:412)
    last_result (ray/tune/trial.py:437)
    _infer_user_metrics (ray/tune/progress_reporter.py:379)
    _progress_str (ray/tune/progress_reporter.py:331)
    report (ray/tune/progress_reporter.py:593)
    _report_progress (ray/tune/tune.py:122)
    run (ray/tune/tune.py:720)
```

I am not sure which actor it is. `reuse_actors` is `True` per default (as it's a function trainable), but errors should be detected and new actors should be spawned. Thus I don't believe we're trying to query a dead actor here, but rather we start an actor on the same node with the failing raylet, schedule a remote actor task, and it hangs forever.

### Expected behavior

I would expect the actor or the task to fail. Actors should not be scheduled on the node.

### Proposed workarounds

I assume this is a Ray runtime bug. Tune should be fine to just schedule new actors and tasks on them. The scheduled task is very short and should return basically immediately, which suggests that the ray worker process is hanging.

From a library perspective, we can introduce timeouts for the specific ray.get call here. 

### Versions / Dependencies

Ray 1.13.0
Anyscale
Using anyscale jobs, but that should be irrelevant.
orbit 1.1.2

### Reproduction script

This error doesn't always come up. The script is proprietary but can be obtained on request. The error comes up in 10-20% of cases.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by spolcyn** [comment]
@iycheng This issue is possibly another instance of https://github.com/ray-project/ray/issues/26772, https://discuss.ray.io/t/ray-actor-remote-call-blocks-forever/6820/5, https://github.com/ray-project/ray/issues/24419

**Comment by iycheng** [comment]
Yes, from the way it failed, it seems related. Basically if the  raylet failed, sometimes actor will hang

**Comment by iycheng** [comment]
@spolcyn  actually there are two issues here. One is about GIL which is fixed here https://github.com/ray-project/ray/pull/26421

Another one is about actor hanging in case of raylet died and this is related to grpc connection so far from my understanding.

**Comment by iycheng** [comment]
The bug should have been fixed. @krfricke could you give it another try?

**Comment by krfricke** [comment]
I'll let the user know!

**Comment by zhe-thoughts** [comment]
Assigning to @krfricke only to verify if can be closed

**Comment by krfricke** [comment]
Resolved for the user. Scheduling tasks/actors on nodes that are not working is still an ongoing issue though.

I'll close this for now as the original issue is resolved.
