### ISSUE TITLE
[core] Bad error message when `ray get actors` failed.

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#26851]
### What happened + What you expected to happen

When I call get actors sometimes it crashed. Maybe because the server is not responsing. We should give better error messages instead of the traceback.
```
(base) yic@ip-172-31-58-40:~ $ ray get actors 1ce495e23cb6412125d2b01000000
Traceback (most recent call last):
  File "/mnt/yic/miniconda3/bin/ray", line 33, in <module>
    sys.exit(load_entry_point('ray', 'console_scripts', 'ray')())
  File "/mnt/yic/ray/python/ray/scripts/scripts.py", line 2544, in main
    return cli()
  File "/mnt/yic/miniconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/yic/miniconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/mnt/yic/miniconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/yic/miniconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/yic/miniconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/yic/ray/python/ray/experimental/state/state_cli.py", line 394, in get
    format_list_api_output(
  File "/mnt/yic/ray/python/ray/experimental/state/state_cli.py", line 294, in format_list_api_output
    if len(state_data) == 0:
TypeError: object of type 'NoneType' has no len()
```

### Versions / Dependencies

master

### Reproduction script

`ray get actors  1ce495e23cb6412125d2b01000000` and sometimes it errored

**Comment by iycheng** [comment]
@rkooo567  I think this is important given that we are building observability tools. Observability of the observability tools is also important.

**Comment by rkooo567** [comment]
yeah we should definitely fix this by the branch cut.

**Comment by rkooo567** [comment]
Is it possible to provide a dashboard.log when you see this happens next time?

**Comment by rkooo567** [comment]
I have a guess, but it will help us confirming the root cause

**Comment by iycheng** [comment]
sure, I'll post it once I have this.

**Comment by rkooo567** [comment]
Duplicates https://github.com/ray-project/ray/issues/26808
