### ISSUE TITLE
ray.wait does not trigger reconstruction

### ISSUE THREAD

**Issue by matthew-z** [ray-project/ray#2691]
demo code: https://gist.github.com/matthew-z/3d5e326fa8aa8b147a0e9429b21f8cb6

I started a small cluster without autoscaler: 1 header and 1 worker node. Both of them have 8 CPU cores. I installed latest ray from https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.5.0-cp36-cp36m-manylinux1_x86_64.whl

After running the script for one iteration, I manually run `ray stop` on the worker node. Then, the driver hang without any error information and there is no meaningful log in /tmp/raylogs.

In contrast, if I avoiding using `ray.wait` and only use `ray.get` to retrieve objects sequentially, the code can be finished even I stopped a worker during the calculation.

This problem is in both raylet and the legacy version.

**Comment by matthew-z** [comment]
BTW, sometimes it raises this error when I only use ray.get on raylet

```
Traceback (most recent call last):
  File "/Users/zhaohaozeng/PycharmProjects/tensorflow_learn/ray_playground/remote.py", line 26, in <module>
    print(ray.get(s))
  File "/usr/local/var/pyenv/versions/anaconda3-4.1.1/lib/python3.6/site-packages/ray/worker.py", line 2493, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(01000000059524a0edb21ddc9a6242d905e19786). It was created by remote function <unknown> which failed with:

Remote function <unknown> failed with:

Invalid return value: likely worker died or was killed while executing the task.

```

**Comment by robertnishihara** [comment]
Thanks @matthew-z! This issue is related to #1273 (but not the same). The fix in both cases is the same.

Basically, in `ray.get`, we call `reconstruct_objects` on the objects that we are missing

https://github.com/ray-project/ray/blob/fbe6c59f72f9c467d02a46ab5aacd5b3aef16098/python/ray/worker.py#L532-L535

and then `notify_unblocked` when the `ray.get` call finishes

https://github.com/ray-project/ray/blob/fbe6c59f72f9c467d02a46ab5aacd5b3aef16098/python/ray/worker.py#L553

We need to do the analogous thing in `ray.wait`.
