### ISSUE TITLE
[Core][Nightly]  chaos_dataset_shuffle_push_based_sort_1tb is failing

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#26922]
### What happened + What you expected to happen

https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_KhVhrUjMDqNSs4wZTynWRU2t?command-history-section=command_history is one of the failure. looks like a logical bug?

```
Traceback (most recent call last):
  File "dataset/sort.py", line 165, in <module>
    raise exc
  File "dataset/sort.py", line 119, in <module>
    ds = ds.sort(key="c_0")
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 1806, in sort
    return Dataset(plan, self._epoch, self._lazy)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 200, in __init__
    self._plan.execute(allow_clear_input_blocks=False)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/plan.py", line 309, in execute
    blocks, clear_input_blocks, self._run_by_consumer
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/plan.py", line 756, in __call__
    blocks, clear_input_blocks, self.block_udf, self.ray_remote_args
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/stage_impl.py", line 194, in do_sort
    return sort_impl(blocks, clear_input_blocks, key, descending)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/sort.py", line 153, in sort_impl
    clear_input_blocks,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/push_based_shuffle.py", line 474, in execute
    self._reduce_args,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/push_based_shuffle.py", line 290, in __init__
    merge_results.pop(0) for merge_results in all_merge_results[merge_idx]
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/push_based_shuffle.py", line 290, in <listcomp>
    merge_results.pop(0) for merge_results in all_merge_results[merge_idx]
IndexError: pop from empty list
```

### Versions / Dependencies

latest ray

### Reproduction script

run nightly test

### Issue Severity

High: It blocks me from completing my task.

**Comment by scv119** [comment]
Per discussion: we will fix it after the branch cut.

**Comment by scv119** [comment]
duplicate
