### ISSUE TITLE
[Datasets] Can't create `TensorArray` from differently-sized arrays

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#26976]
### What happened + What you expected to happen

```
>>> import numpy as np
>>> from ray.data.extensions import TensorArray
>>> a1 = np.zeros([2, 2])
>>> a2 = np.zeros([3, 4])
>>> TensorArray([a1, a2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bveeramani/GitHub/ray/python/ray/air/util/tensor_extensions/pandas.py", line 671, in __init__
    self._tensor = np.stack([np.asarray(v) for v in values], axis=0)
  File "<__array_function__ internals>", line 180, in stack
  File "/Users/bveeramani/GitHub/ray/.venv/lib/python3.9/site-packages/numpy/core/shape_base.py", line 426, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
```

This issue is problematic because it makes it hard to read differently-sized images.

### Versions / Dependencies

**Ray**: ec1995a662b971bc5f6440a94d9c6b2258e32f2d

### Reproduction script

See above.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by clarkzinzow** [comment]
Duplicate: https://github.com/ray-project/ray/issues/18316

**Comment by bveeramani** [comment]
Closing because this issue is a duplicate of #18316
