### ISSUE TITLE
[runtime env] local `working_dir` doesn't work with strongly-typed `RuntimeEnv`

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#26984]
### What happened + What you expected to happen

Providing a local directory for `working_dir` doesn't work when using the strongly-typed RuntimeEnv.

It raises a validation error:

```python-traceback
Traceback (most recent call last):
  File "repro.py", line 3, in <module>
    ray.init(runtime_env=RuntimeEnv(working_dir="/.", config=RuntimeEnvConfig(setup_timeout_seconds=1)))
  File "/Users/archit/ray/python/ray/runtime_env/runtime_env.py", line 326, in __init__
    self[option] = option_val
  File "/Users/archit/ray/python/ray/runtime_env/runtime_env.py", line 377, in __setitem__
    res_value = OPTION_TO_VALIDATION_FN[key](jsonable_type)
  File "/Users/archit/ray/python/ray/_private/runtime_env/validation.py", line 59, in parse_and_validate_working_dir
    validate_uri(working_dir)
  File "/Users/archit/ray/python/ray/_private/runtime_env/validation.py", line 23, in validate_uri
    raise ValueError(
ValueError: /. is not a valid URI. Passing directories or modules to be dynamically uploaded is only supported at the job level (i.e., passed to `ray.init`).
```

The reason is that internally, Ray expects the runtime_env `working_dir` field to be a URI, so we don't validate it until the local working_dir has been uploaded to the GCS and the `working_dir` field has been replaced with a URI:
https://github.com/ray-project/ray/blob/43aa2299e6623c8f8c7c4a1b80133459d0aa68b0/python/ray/job_config.py#L53-L67

However, when defining a `runtime_env` using the strongly typed `RuntimeEnv`, we get the above validation error, probably because validation is always run.

### Versions / Dependencies

Master, MacOS

### Reproduction script

```python
import ray
from ray.runtime_env import RuntimeEnv, RuntimeEnvConfig
ray.init(runtime_env=RuntimeEnv(working_dir=".")) # {"working_dir": "."} succeeds.

@ray.remote
def f():
    return True

assert ray.get(f.remote())
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

The workaround is to use a dict instead of the strongly-typed API.

**Comment by hora-anyscale** [comment]
Per Triage Sync: @architkulkarni is this still an issue?

**Comment by architkulkarni** [comment]
Yeah, this is still an issue

**Comment by cszhu** [comment]
This P2 issue has seen no activity in the past 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please comment and remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
