### ISSUE TITLE
Error defining remote functions using TensorFlow in cluster setting.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#270]
On a 10-node cluster with Ubuntu, and

```python
import tensorflow as tf
tf.__version__  # '0.12.1'
```

Without Ray, I can do

```python
import tensorflow as tf
import cloudpickle

def f():
  x = tf.Variable(1)
  return 1

print(cloudpickle.dumps(f))
```

Then I can copy the output of `cloudpickle.dumps(f)` and load it on a different machine in the cluster.

```python
import cloudpickle

s = # string output by cloudpickle.dumps(f)
f = cloudpickle.loads(s)
f() # 1
```

However, If I define the same thing as a remote function,

```python
import ray

@ray.remote
def f():
  x = tf.Variable(1)
  return 1
```

I get the following error.

```python
Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/worker.py", line 1022, in fetch_and_register
    function = pickling.loads(serialized_function)
  File "/opt/conda/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/opt/conda/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/opt/conda/lib/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
  File "build/bdist.linux-x86_64/egg/cloudpickle/cloudpickle.py", line 717, in s
    __import__(name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/__init__.py",
    from tensorflow.python import *
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/__init
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/__init
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name pywrap_tensorflow


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

**Comment by robertnishihara** [comment]
The problem is gone now, and I'm having trouble recreating the original problem. The things I tried, one of which seems to have worked, were the following:

1. `pip install -U protobuf==3.0.0b2 --user` (I got the idea from tensorflow/tensorflow#1402).
2. Make sure to add the right version of Python to my PATH environment variable inside of the script for installing TensorFlow on all the nodes (see https://github.com/ray-project/ray/blob/master/doc/using-ray-on-a-large-cluster.md).
3. Instead of installing TensorFlow with `pip install tensorflow`, do
```
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tenso\
rflow-0.12.1-cp27-none-linux_x86_64.whl
pip install --ignore-installed --upgrade --user $TF_BINARY_URL
```
