### ISSUE TITLE
[rllib] trainable initialization failure in pendulum-ddpg.yaml

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#2705]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: mac 10.13.12
- **Ray installed from (source or binary)**: source 
- **Ray version**: 0.5.0
- **Python version**: 3.6.5
- **Exact command to reproduce**: python train.py -f tuned_examples/pendulum-ddpg.yaml

### Describe the problem

Trying to run train.py on some of the tuned_examples, they fail. Thought it was worth giving ya'll a heads up. 

### Source code / logs

(ray_testing) ➜  rllib git:(master) python train.py -f tuned_examples/pendulum-ddpg.yaml
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:21670 to respond...
Waiting for redis server at 127.0.0.1:22896 to respond...
Starting local scheduler with the following resources: {'CPU': 8, 'GPU': 0}.

======================================================================
View the web UI at http://localhost:8889/notebooks/ray_ui35661.ipynb?token=491f896b51f710b9a55076154bbaf4acdab75b898e751f9a
======================================================================

== Status ==
Using FIFO scheduling algorithm.

Created LogSyncer for /Users/eugenevinitsky/ray_results/pendulum-ddpg/DDPG_Pendulum-v0_0_2018-08-21_15-06-41p20bom4o ->
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 1/8 CPUs, 0/0 GPUs
Result logdir: /Users/eugenevinitsky/ray_results/pendulum-ddpg
RUNNING trials:
 - DDPG_Pendulum-v0_0:	RUNNING

Remote function __init__ failed with:

Traceback (most recent call last):
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/worker.py", line 932, in _process_task
    *arguments)
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/rllib/agents/agent.py", line 169, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/tune/trainable.py", line 78, in __init__
    self._setup()
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/rllib/agents/agent.py", line 187, in _setup
    self._allow_unknown_subkeys)
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/rllib/utils/__init__.py", line 35, in deep_update
    raise Exception("Unknown config parameter `{}` ".format(k))
Exception: Unknown config parameter `optimizer_config`

Remote function train failed with:

Traceback (most recent call last):
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/worker.py", line 932, in _process_task
    *arguments)
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/tune/trainable.py", line 139, in train
    "Trainable initialization failed, see previous errors")
ValueError: Trainable initialization failed, see previous errors

Error processing event: Traceback (most recent call last):
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/tune/trial_runner.py", line 265, in _process_events
    result = ray.get(result_id)
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/worker.py", line 2492, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(b8ded50cb0664aa7d6b20950d0046ee9da226a71). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/worker.py", line 932, in _process_task
    *arguments)
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/tune/trainable.py", line 139, in train
    "Trainable initialization failed, see previous errors")
ValueError: Trainable initialization failed, see previous errors

Worker ip unknown, skipping log sync for /Users/eugenevinitsky/ray_results/pendulum-ddpg/DDPG_Pendulum-v0_0_2018-08-21_15-06-41p20bom4o
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/8 CPUs, 0/0 GPUs
Result logdir: /Users/eugenevinitsky/ray_results/pendulum-ddpg
ERROR trials:
 - DDPG_Pendulum-v0_0:	ERROR, 1 failures: /Users/eugenevinitsky/ray_results/pendulum-ddpg/DDPG_Pendulum-v0_0_2018-08-21_15-06-41p20bom4o/error_2018-08-21_15-06-46.txt

Traceback (most recent call last):
  File "train.py", line 118, in <module>
    run(args, parser)
  File "train.py", line 112, in run
    queue_trials=args.queue_trials)
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/tune/tune.py", line 110, in run_experiments
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [DDPG_Pendulum-v0_0])

**Comment by ericl** [comment]
Fixed now.
