### ISSUE TITLE
[rllib] rllib train in LOCAL_MODE fails

### ISSUE THREAD

**Issue by pathway** [ray-project/ray#2719]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.4 LTS
- **Ray installed from (source or binary)**:  installed via pip
- **Ray version**: 0.5.0
- **Python version**: Python 3.5.2
- **Exact command to reproduce**:  python3 train.py --run DQN --env CartPole-v0

### Describe the problem

1) I use the existing ray/python/ray/rllib/train.py like this:
`ray/python/ray/rllib$ python3 train.py --run DQN --env CartPole-v0`

2) I make just one change to ray_init, hoping I could step through the code in local mode: 

    ray.init(
...
        driver_mode=2 # 2=LOCAL_MODE
        )

Result: Exception.

### Source code / logs
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    run(args, parser)
  File "train.py", line 114, in run
    queue_trials=args.queue_trials)
  File "/usr/local/CHUBBY/DYNAMIC/SRC/pathway/ray/python/ray/rllib/venv/lib/python3.5/site-packages/ray/tune/tune.py", line 83, in run_experiments
    scheduler.add_experiment(experiment, runner)
  File "/usr/local/CHUBBY/DYNAMIC/SRC/pathway/ray/python/ray/rllib/venv/lib/python3.5/site-packages/ray/tune/trial_scheduler.py", line 62, in add_experiment
    trial_runner.add_trial(next(generator))
  File "/usr/local/CHUBBY/DYNAMIC/SRC/pathway/ray/python/ray/rllib/venv/lib/python3.5/site-packages/ray/tune/variant_generator.py", line 75, in generate_trials
    max_failures=args.max_failures)
  File "/usr/local/CHUBBY/DYNAMIC/SRC/pathway/ray/python/ray/rllib/venv/lib/python3.5/site-packages/ray/tune/trial.py", line 97, in __init__
    if not has_trainable(trainable_name):
  File "/usr/local/CHUBBY/DYNAMIC/SRC/pathway/ray/python/ray/rllib/venv/lib/python3.5/site-packages/ray/tune/trial.py", line 61, in has_trainable
    ray.tune.registry.TRAINABLE_CLASS, trainable_name)
  File "/usr/local/CHUBBY/DYNAMIC/SRC/pathway/ray/python/ray/rllib/venv/lib/python3.5/site-packages/ray/tune/registry.py", line 83, in contains
    value = _internal_kv_get(_make_key(category, key))
  File "/usr/local/CHUBBY/DYNAMIC/SRC/pathway/ray/python/ray/rllib/venv/lib/python3.5/site-packages/ray/experimental/internal_kv.py", line 17, in _internal_kv_get
    return worker.redis_client.hget(key, "value")
AttributeError: 'Worker' object has no attribute 'redis_client'

**Comment by ericl** [comment]
This is expected, since we use some features not available in local mode.

For stepping through code, you can create DQN agent and call agent.train() manually. I believe the default num_workers=0 so it will run all in one process without invoking Ray.

**Comment by pathway** [comment]
Thank you for explaining.

**Comment by pathway** [comment]
I cannot make local mode step through.  My new code is very short:

```
import ray
import ray.rllib.agents.dqn as dqn
from ray.tune.logger import pretty_print
ray.init(driver_mode=2)
agent = dqn.DQNAgent( env="CartPole-v0")
for i in range(1000):
   # Perform one iteration of training the policy with PPO
   result = agent.train()
   print(pretty_print(result))
```
I get:
```
/SRC/pathway/pommerman/venv/bin/python /SRC/pathway/pommerman/playground/pommerman/rllib_simple.py
Traceback (most recent call last):
  File "/SRC/pathway/pommerman/playground/pommerman/rllib_simple.py", line 4, in <module>
    ray.init(driver_mode=2)
  File "/usr/local/CHUBBY/DYNAMIC/SRC/pathway/ray/python/ray/worker.py", line 1840, in init
    hook()
  File "/usr/local/CHUBBY/DYNAMIC/SRC/pathway/ray/python/ray/tune/registry.py", line 101, in flush_values
    _internal_kv_put(_make_key(category, key), value, overwrite=True)
  File "/usr/local/CHUBBY/DYNAMIC/SRC/pathway/ray/python/ray/experimental/internal_kv.py", line 31, in _internal_kv_put
    updated = worker.redis_client.hset(key, "value", value)
AttributeError: 'Worker' object has no attribute 'redis_client'
```

Looking for a way to run rllib without using distributed mode?  It is much harder to hack that way.

**Comment by ericl** [comment]
You can step through distributed mode right? Dqn will not actually use ray actors if num workers is zero.

**Comment by robertnishihara** [comment]
@ericl this can be closed, right?

**Comment by ericl** [comment]
Yeah local mode now works.
