### ISSUE TITLE
[ray dashboard] profile button not working 

### ISSUE THREAD

**Issue by mccrearyd** [ray-project/ray#27211]
### What happened + What you expected to happen

clicking any of the profile buttons results in the following error:

![image](https://user-images.githubusercontent.com/26421036/181624661-b899d3ae-5b06-487c-8c73-17104c7d92be.png)

text form:
```
Uncaught (in promise) Error: Traceback (most recent call last):
  File "/home/nollied/miniconda3/envs/quilt/lib/python3.8/site-packages/ray/dashboard/optional_utils.py", line 93, in _handler_route
    return await handler(bind_info.instance, req)
  File "/home/nollied/miniconda3/envs/quilt/lib/python3.8/site-packages/ray/dashboard/modules/reporter/reporter_head.py", line 60, in launch_profiling
    ip = req.query["ip"]
KeyError: 'ip'
```

note: this button was for an actor, but even non-actors don't work. 

### Versions / Dependencies

ray 1.13.0, python=3.8.12, ubuntu 20.04

browser=firefox v103.0 (64bit)

### Reproduction script

```python
import ray
from time import sleep

@ray.remote
class SomeActor:
    def test(self):
        sleep(10)
        return "hi"

@ray.remote
class MainActor:
    def run(self):
        self.sub_actors = [SomeActor.remote() for _ in range(10)]
        for _ in range(50):
            self.step()
        return "done"

    def step(self):
        tests = []
        for a in self.sub_actors:
            tests.append(a.test())
        print(ray.get(tests))
        

main = MainActor()
print(ray.get(main.run.remote()))  # note: while this is running, open the ray dashboard and try to profile.
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by jjyao** [comment]
cc @alanwguo for triage

**Comment by scottsun94** [comment]
@nollied 
In Ray 2.0, we changed the experimental dashboard to be the default dashboard. We plan to deprecate the old dashboard in the future. In the new dashboard, we currently don't support profiling the actor.

For better feature planning for the new dashboard, I have some questions:
- Could you help us understand what you want to achieve with "profiling actor" feature? How much value would it bring?
- Other related features you want?

**Comment by rkooo567** [comment]
We will add a profiling feature back to the new dashboard. The prototype is planned to be included in Ray 2.2 (will be released in Dec). I will get back to you once it is available.

**Comment by cszhu** [comment]
This P2 issue has seen no activity in the past 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please comment and remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
