### ISSUE TITLE
Jenkins test failure: `AttributeError: 'module' object has no attribute 'LZ4_compress'`

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#2727]
```
======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui46939.ipynb?token=906075fe3d05aa32b7462af7b53a9a0b88fc90f607f8f5cd
======================================================================

Traceback (most recent call last):
  File "/ray/python/ray/rllib/train.py", line 118, in <module>
    run(args, parser)
  File "/ray/python/ray/rllib/train.py", line 112, in run
    queue_trials=args.queue_trials)
  File "/ray/python/ray/tune/tune.py", line 102, in run_experiments
    runner.step()
  File "/ray/python/ray/tune/trial_runner.py", line 102, in step
== Status ==
Using FIFO scheduling algorithm.


    next_trial = self._get_next_trial()
  File "/ray/python/ray/tune/trial_runner.py", line 209, in _get_next_trial
    self._update_trial_queue(blocking=wait_for_trial)
  File "/ray/python/ray/tune/trial_runner.py", line 281, in _update_trial_queue
    trials = self._search_alg.next_trials()
  File "/ray/python/ray/tune/suggest/basic_variant.py", line 50, in next_trials
    trials = list(self._trial_generator)
  File "/ray/python/ray/tune/suggest/basic_variant.py", line 78, in _generate_trials
    experiment_tag=experiment_tag)
  File "/ray/python/ray/tune/config_parser.py", line 193, in create_trial_from_spec
    **trial_kwargs)
  File "/ray/python/ray/tune/trial.py", line 125, in __init__
    from ray import rllib  # noqa: F401
  File "/ray/python/ray/rllib/__init__.py", line 9, in <module>
    from ray.rllib.evaluation.policy_graph import PolicyGraph
  File "/ray/python/ray/rllib/evaluation/__init__.py", line 2, in <module>
    from ray.rllib.evaluation.policy_evaluator import PolicyEvaluator
  File "/ray/python/ray/rllib/evaluation/policy_evaluator.py", line 10, in <module>
    from ray.rllib.models import ModelCatalog
  File "/ray/python/ray/rllib/models/__init__.py", line 1, in <module>
    from ray.rllib.models.catalog import ModelCatalog
  File "/ray/python/ray/rllib/models/catalog.py", line 17, in <module>
    from ray.rllib.models.fcnet import FullyConnectedNetwork
  File "/ray/python/ray/rllib/models/fcnet.py", line 6, in <module>
    import tensorflow.contrib.slim as slim
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 40, in <module>
    from tensorflow.contrib import distributions
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/contrib/distributions/__init__.py", line 38, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/contrib/distributions/python/ops/estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/contrib/learn/__init__.py", line 95, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/contrib/learn/python/__init__.py", line 28, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 302, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 35, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 36, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 52, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 26, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 33, in <module>
    import dask.dataframe as dd
  File "/opt/conda/lib/python2.7/site-packages/dask/dataframe/__init__.py", line 5, in <module>
    from .io import (from_array, from_bcolz, from_array, from_bcolz,
  File "/opt/conda/lib/python2.7/site-packages/dask/dataframe/io.py", line 34, in <module>
    from ..bytes.core import write_bytes
  File "/opt/conda/lib/python2.7/site-packages/dask/bytes/__init__.py", line 4, in <module>
    from .core import read_bytes, open_files, open_text_files
  File "/opt/conda/lib/python2.7/site-packages/dask/bytes/core.py", line 9, in <module>
    from .compression import seekable_files, files as compress_files
  File "/opt/conda/lib/python2.7/site-packages/dask/bytes/compression.py", line 37, in <module>
    compress['lz4'] = lz4.LZ4_compress
AttributeError: 'module' object has no attribute 'LZ4_compress'
Build step 'Execute shell' marked build as failure
Setting commit status on GitHub for https://github.com/ray-project/ray/commit/0455ef9fad51e6992f6d3d79bd55340cbb0a0b97
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/7711/
Test FAILed.
Finished: FAILURE
```

**Comment by robertnishihara** [comment]
I've seen this in the past, and you can fix it with `pip install -U dask`. See https://github.com/ray-project/ray/issues/2137#issuecomment-391967245
