### ISSUE TITLE
[2.0][nightly]  long_running_distributed_pytorch_pbt_failure (8671807) failed

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27276]
### What happened + What you expected to happen

https://buildkite.com/ray-project/release-tests-branch/builds/837#0182494c-c416-47f7-8bc4-0465df3a7e7e
this failed on releases/2.0.0 branch
is this a rc0 release blocker?

### Versions / Dependencies

releases/2.0.0

### Reproduction script

N/a

### Issue Severity

High: It blocks me from completing my task.

**Comment by xwjiang2010** [comment]
seeing:
```
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tuner.py", line 234, in fit
    return self._local_tuner.fit()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/impl/tuner_internal.py", line 283, in fit
    analysis = self._fit_internal(trainable, param_space)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/impl/tuner_internal.py", line 381, in _fit_internal
    **args,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 724, in run
    runner.step()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/execution/trial_runner.py", line 863, in step
    iteration=self._iteration, trials=self._trials
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/callback.py", line 309, in on_step_begin
    callback.on_step_begin(**info)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/utils/mock.py", line 53, in on_step_begin
    override_cluster_name=None,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 533, in kill_node
    config = _bootstrap_config(config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 367, in _bootstrap_config
    validate_config(config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/util.py", line 143, in validate_config
    raise e from None
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/util.py", line 141, in validate_config
    jsonschema.validate(config, schema)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/jsonschema/validators.py", line 1059, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('worker_nodes' was unexpected)

Failed validating 'additionalProperties' in schema:
    {'$id': 'http://github.com/ray-project/ray/python/ray/autoscaler/ray-schema.json',
     '$schema': 'http://json-schema.org/draft-07/schema#',
     'additionalProperties': False,
     'definitions': {'commands': {'items': {'description': 'shell command',
                                            'type': 'string'},
                                  'type': 'array'}},
     'description': 'Ray autoscaler schema',
     'properties': {'auth': {'additionalProperties': False,
                             'description': 'How Ray will authenticate '
                                            'with newly launched nodes.',
                             'properties': {'ssh_private_key': {'type': 'string'},
                                            'ssh_proxy_command': {'description': 'A '
                                                                                 'value '
                                                                                 'for '
                                                                                 'ProxyCommand '
                                                                                 'ssh '
                                                                                 'option, '
                                                                                 'for '
                                                                                 'connecting '
                                                                                 'through '
                                                                                 'proxies. '
                                                                                 'Example: '
                                                                                 'nc '
                                                                                 '-x '
                                                                                 'proxy.example.com:1234 '
                                                                                 '%h '
                                                                                 '%p',
                                                                  'type': 'string'},
                                            'ssh_public_key': {'type': 'string'},
                                            'ssh_user': {'default': 'ubuntu',
                                                         'type': 'string'}},
                             'type': 'object'},
                    'available_node_types': {'additionalProperties': False,
                                             'description': 'A list of '
                                                            'node types '
                                                            'for '
                                                            'multi-node-type '
                                                            'autoscaling.',
                                             'patternProperties': {'.*': {'additionalProperties': False,
                                                                          'properties': {'docker': {'additionalProperties': False,
                                                                                                    'description': 'Configuration '
                                                                                                                   'of '
                                                                                                                   'Worker '
                                                                                                                   'nodes.',
                                                                                                    'properties': {'pull_before_run': {'description': 'run '
```

**Comment by xwjiang2010** [comment]
https://github.com/ray-project/ray/pull/27040/files

**Comment by scv119** [comment]
Fixed by reverting autoscaler changes.
