### ISSUE TITLE
[core] Bad logs when `__del__` is called

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#27296]
### What happened + What you expected to happen

It seems that in py3.9, something changed and the `__del__` can be called after the cleanup.
```
python test.py
Connecting to existing Ray cluster at address: 172.31.58.40:6379...
Connected to Ray cluster. View the dashboard at http://127.0.0.1:8265.
A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffa42108d40049a3d55fa3ae8603000000 Worker ID: 60969a729f49d2f157bc0a17a7c06e94da678e6dfc23ad88421a6ea8 Node ID: b2ee7fde80ca0f78621c13592ca82feb6f5170a51f0b9409173424d8 Worker IP address: 172.31.58.40 Worker port: 10005 Worker PID: 13381 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
Traceback (most recent call last):
  File "/mnt/yic/ray/test.py", line 30, in <module>
    ray.get(a.pid.remote())
  File "/mnt/yic/ray/python/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/mnt/yic/ray/python/ray/_private/worker.py", line 2249, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
Exception ignored in: <function ActorHandle.__del__ at 0x7fe760ebe3a0>
Traceback (most recent call last):
  File "/mnt/yic/ray/python/ray/actor.py", line 1098, in __del__
AttributeError: 'NoneType' object has no attribute 'worker'
```

### Versions / Dependencies

master, py39, linux

### Reproduction script

import os
import signal
from filelock import FileLock

import ray
ray.init('auto')

l = FileLock("tmp.lock")

@ray.remote(max_restarts=1, max_task_retries=0)
class Actor:
    def __init__(self):
        l = FileLock("tmp.lock")
        with l:
            pass
    def pid(self):
        return os.getpid()

a = Actor.remote()
# Get the pid of the actor
pid = ray.get(a.pid.remote())

# Actuire the lock the that the actor will be in restarting
# status forever
l.acquire()

os.kill(pid, signal.SIGKILL)

# This will fail immediately.
ray.get(a.pid.remote())

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by scv119** [comment]
Thanks @iycheng for reporting!
