### ISSUE TITLE
[Core] Ray 2.0.0rc0 missing `pydantic` from requirements.txt 

### ISSUE THREAD

**Issue by pyrito** [ray-project/ray#27322]
### What happened + What you expected to happen

Installing Ray 2.0.0 should pull in any dependencies that are required. After doing `pip install ray==2.0.0rc0`, I got the following error when doing a simple `ray.init()`. 

```
2022-08-01 10:25:40,651	ERROR services.py:1363 -- Failed to start the dashboard: Failed to start the dashboard, return code 1
 The last 10 lines of /tmp/ray/session_2022-08-01_10-25-38_629255_24646/logs/dashboard.log:
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/kvelayutham/opt/anaconda3/envs/modin-ray-2.0/lib/python3.9/site-packages/ray/dashboard/modules/job/job_head.py", line 33, in <module>
    from ray.dashboard.modules.job.pydantic_models import (
  File "/Users/kvelayutham/opt/anaconda3/envs/modin-ray-2.0/lib/python3.9/site-packages/ray/dashboard/modules/job/pydantic_models.py", line 4, in <module>
    from pydantic import BaseModel, Field
ModuleNotFoundError: No module named 'pydantic'
```

This fix is simple and just requires the requirements.txt file to be updated appropriately. 

### Versions / Dependencies

macOS 12.2.1
Ray 2.0.0rc0
Python 3.9.12

### Reproduction script

```python
In [1]: import ray

In [2]: ray.__version__
Out[2]: '2.0.0rc0'

In [3]: ray.init()
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by richardliaw** [comment]
Oh, I believe this comes up when you don't install via `ray[default]`. 

We need to catch this exception and raise a simple error message.

**Comment by pyrito** [comment]
@richardliaw ah yes, you're right. If I do `pip install ray[default]==2.0.0rc0` it seems to install things accordingly.

**Comment by matthewdeng** [comment]
`ray[default]` works as a workaround, but shouldn't this still work with just `ray`?

@alanwguo do you know if dashboard somehow got introduced into the initialization path?

**Comment by alanwguo** [comment]
It's possible a try catch has to happen earlier now due to this change.
Now things break at import time for the dashboard. It's possible previously, it would only break at run time and there was a try catch that would throw a better error message.

**Comment by matthewdeng** [comment]
Hmm strangely enough I'm not able to repro on my Mac (12.3.1)

```bash
(ray20rc0) ~/workspace/ray (master ✔) pip freeze                 
aiosignal==1.2.0
attrs==22.1.0
certifi==2022.6.15
charset-normalizer==2.1.0
click==8.0.4
distlib==0.3.5
filelock==3.7.1
frozenlist==1.3.0
grpcio==1.43.0
idna==3.3
jsonschema==4.9.0
msgpack==1.0.4
numpy==1.23.1
platformdirs==2.5.2
protobuf==3.20.1
pyrsistent==0.18.1
PyYAML==6.0
ray==2.0.0rc0
requests==2.28.1
six==1.16.0
urllib3==1.26.11
virtualenv==20.16.2
```
```python
(ray20rc0) ~/workspace/ray (master ✔) python    
Python 3.9.12 (main, Jun  1 2022, 06:36:29) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init()
2022-08-01 11:20:11,381	INFO worker.py:1490 -- Started a local Ray instance.
RayContext(dashboard_url='', python_version='3.9.12', ray_version='2.0.0rc0', ray_commit='a0588094ec52b45a878f59e98258cd5e90f4ec36', address_info={'node_ip_address': '127.0.0.1', 'raylet_ip_address': '127.0.0.1', 'redis_address': None, 'object_store_address': '/tmp/ray/session_2022-08-01_11-20-08_545270_4647/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2022-08-01_11-20-08_545270_4647/sockets/raylet', 'webui_url': '', 'session_dir': '/tmp/ray/session_2022-08-01_11-20-08_545270_4647', 'metrics_export_port': 55944, 'gcs_address': '127.0.0.1:62747', 'address': '127.0.0.1:62747', 'dashboard_agent_listen_port': 52365, 'node_id': '44c8c73f05d477c3ae981f6a8bd46785fc9c3d0396de715063204e76'})
>>> ray.__version__
'2.0.0rc0'
>>> ray.__commit__
'a0588094ec52b45a878f59e98258cd5e90f4ec36'
```

**Comment by scv119** [comment]
also cc @rkooo567 who has context.

**Comment by alanwguo** [comment]
I also could not reproduce this issue.

@pyrito, can you share the output of `ray.init()`? 
Ex:
```
In [3]: ray.init()
2022-08-01 12:49:37,629	INFO worker.py:1490 -- Started a local Ray instance.
Out[3]: RayContext(dashboard_url='', python_version='3.9.12', ray_version='2.0.0rc0', ray_commit='a0588094ec52b45a878f59e98258cd5e90f4ec36', address_info={'node_ip_address': '127.0.0.1', 'raylet_ip_address': '127.0.0.1', 'redis_address': None, 'object_store_address': '/tmp/ray/session_2022-08-01_12-49-34_481382_14225/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2022-08-01_12-49-34_481382_14225/sockets/raylet', 'webui_url': '', 'session_dir': '/tmp/ray/session_2022-08-01_12-49-34_481382_14225', 'metrics_export_port': 64312, 'gcs_address': '127.0.0.1:64739', 'address': '127.0.0.1:64739', 'dashboard_agent_listen_port': 52365, 'node_id': '5da067a3b9e1cf4062f3bfc7ae9475bf416718ee9ef604eac2b059c5'})
```

One thing to notice is `dashboard_url=''` when the dashboard is not enabled which should be the case when you only have the minimal ray installed.

**Comment by pyrito** [comment]
Oddly enough, I'm not able to reproduce the bug I saw with a clean environment either. I did the following:
1. `conda create --name test python=3.9`
2. `pip install ipython`
3. `pip install ray==2.0.0rc0`
4. I'm seeing this:
```python
In [1]: import ray

In [2]: ray.init()
2022-08-01 14:53:46,092	INFO worker.py:1490 -- Started a local Ray instance.
Out[2]: RayContext(dashboard_url='', python_version='3.9.12', ray_version='2.0.0rc0', ray_commit='a0588094ec52b45a878f59e98258cd5e90f4ec36', address_info={'node_ip_address': '127.0.0.1', 'raylet_ip_address': '127.0.0.1', 'redis_address': None, 'object_store_address': '/tmp/ray/session_2022-08-01_14-53-43_472406_33095/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2022-08-01_14-53-43_472406_33095/sockets/raylet', 'webui_url': '', 'session_dir': '/tmp/ray/session_2022-08-01_14-53-43_472406_33095', 'metrics_export_port': 64517, 'gcs_address': '127.0.0.1:64490', 'address': '127.0.0.1:64490', 'dashboard_agent_listen_port': 52365, 'node_id': '19604bbe1330d2ddbd846119cb671baae26e6f2bb0e2f4ab40c39b9c'})
```
I saw the issue in my modin development environment which has a bunch of other stuff in there, so maybe I triggered a bad code path?

**Comment by pyrito** [comment]
Aha. The behavior that's triggering the error that I've been seeing is when I uninstall ray and install Ray 2.0.0. I think somehow the old state of enabling the dashboard is left lingering around so dashboard gets enabled. You can reproduce it with these steps:
1. `conda create --name test python=3.9`
2. `pip install ipython`
3. `pip install ray[default]`
4. Run this:
```python
In [1]: import ray

In [2]: ray.init()
2022-08-01 15:02:47,828	INFO services.py:1456 -- View the Ray dashboard at http://127.0.0.1:8265
Out[2]: RayContext(dashboard_url='127.0.0.1:8265', python_version='3.9.12', ray_version='1.12.0', ray_commit='f18fc31c7562990955556899090f8e8656b48d2d', address_info={'node_ip_address': '127.0.0.1', 'raylet_ip_address': '127.0.0.1', 'redis_address': None, 'object_store_address': '/tmp/ray/session_2022-08-01_15-02-45_592000_34307/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2022-08-01_15-02-45_592000_34307/sockets/raylet', 'webui_url': '127.0.0.1:8265', 'session_dir': '/tmp/ray/session_2022-08-01_15-02-45_592000_34307', 'metrics_export_port': 65459, 'gcs_address': '127.0.0.1:65183', 'address': '127.0.0.1:65183', 'node_id': 'c4f38cae5a7070c8b18df2269f0cf0d022f231e7263043967d9607cf'})
```
5. `pip uninstall ray`
6. `pip install ray==2.0.0rc0`
7. Run the following and see the output:
```python
In [1]: import ray

In [2]: ray.init()
2022-08-01 15:03:54,681	ERROR services.py:1363 -- Failed to start the dashboard: Failed to start the dashboard, return code 1
 The last 10 lines of /tmp/ray/session_2022-08-01_15-03-51_764788_34600/logs/dashboard.log:
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/ray/dashboard/modules/job/job_head.py", line 33, in <module>
    from ray.dashboard.modules.job.pydantic_models import (
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/ray/dashboard/modules/job/pydantic_models.py", line 4, in <module>
    from pydantic import BaseModel, Field
ModuleNotFoundError: No module named 'pydantic'
2022-08-01 15:03:54,681	ERROR services.py:1364 -- Failed to start the dashboard, return code 1
 The last 10 lines of /tmp/ray/session_2022-08-01_15-03-51_764788_34600/logs/dashboard.log:
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/ray/dashboard/modules/job/job_head.py", line 33, in <module>
    from ray.dashboard.modules.job.pydantic_models import (
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/ray/dashboard/modules/job/pydantic_models.py", line 4, in <module>
    from pydantic import BaseModel, Field
ModuleNotFoundError: No module named 'pydantic'
Traceback (most recent call last):
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/ray/_private/services.py", line 1350, in start_dashboard
    raise Exception(err_msg + last_log_str)
Exception: Failed to start the dashboard, return code 1
 The last 10 lines of /tmp/ray/session_2022-08-01_15-03-51_764788_34600/logs/dashboard.log:
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/ray/dashboard/modules/job/job_head.py", line 33, in <module>
    from ray.dashboard.modules.job.pydantic_models import (
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/ray/dashboard/modules/job/pydantic_models.py", line 4, in <module>
    from pydantic import BaseModel, Field
ModuleNotFoundError: No module named 'pydantic'
```

I hope this helps. It doesn't look like this is a huge bug. Seems like a pretty quick fix.

**Comment by rkooo567** [comment]
> @matthewdeng , the ray dashboard is not supposed to work with the minimal ray installation.

cc @alanwguo  Btw, this is technically not true. We still start a dashboard with minimal ray installation, but we don't start HTTP servers or other modules that require additional dependencies.

**Comment by rkooo567** [comment]
I think the issue is when you install `pip install ray==2.0.0rc0`, it technically installs the minimal ray. If you run `pip install ray[default]` again, it will work. However, the dashboard shouldn't fail to start in this case (so this one is a bug)

**Comment by matthewdeng** [comment]
Based on the repro, seems like the logic to start the HTTPS server is gated by a dependency check and we'd need to add `pydantic` there as well?

**Comment by alanwguo** [comment]
> Based on the repro, seems like the logic to start the HTTPS server is gated by a dependency check and we'd need to add `pydantic` there as well?

yes, i believe I found the place. Just manually testing my fix now.
