### ISSUE TITLE
[Datasets] read_parquet() get a strange huge object size

### ISSUE THREAD

**Issue by guodashun** [ray-project/ray#27361]
### What happened + What you expected to happen

There is a local S3 server by minio and a local ray cluster. I want to read parquets from the server by the following code.
```
import ray
from s3fs import S3FileSystem

ray_init() # some initialization for ray

parquets = ray.data.read_parquet(
    's3://BUCKET',
    filesystem=S3FileSystem(   **{"key": "KEY",
                    "secret": "SECRET",
                    "client_kwargs":{
                        'endpoint_url': 'http://ip:port',
                    },
                    "config_kwargs":{
                        'signature_version': 's3v4'
                    }
    }),
)
print("parquet size", parquets.count())

parquets.show()
modin_format_data = parquets.to_modin()
```
From `.count()` I can get the correct parquets size, but the problem is when I want to instantiate the parquet (like `.show(), .to_modin()`), I met the error message.
```
Traceback (most recent call last):
  File "ut.py", line 29, in <module>
    a.show()
  File "/home/xxxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/ray/data/dataset.py", line 1814, in show
    for row in self.take(limit):
  File "/home/xxxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/ray/data/dataset.py", line 1778, in take
    for row in self.iter_rows():
  File "/home/xxxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/ray/data/dataset.py", line 2243, in iter_rows
    for batch in self.iter_batches(
  File "/home/xxxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/ray/data/dataset.py", line 2298, in iter_batches
    yield from batch_blocks(
  File "/home/xxxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/ray/data/_internal/block_batching.py", line 129, in batch_blocks
    yield from get_batches(block_window[0])
  File "/home/xxxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/ray/data/_internal/block_batching.py", line 87, in get_batches
    block = ray.get(block)
  File "/home/xxxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/xxxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/ray/_private/worker.py", line 2245, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::_execute_read_task() (pid=3703, ip=xxxx)
ray.exceptions.ObjectStoreFullError: Failed to put object 32d950ec0ccf9d2affffffffffffffffffffffff0100000001000000 in object store because it is full. Object size is 2271683242145 bytes.
The local object store is full of objects that are still in scope and cannot be evicted. Tip: Use the `ray memory` command to list active objects in the cluster.
(_execute_read_task pid=3703, ip=xxxx) [2022-08-02 10:14:28,262 E 3703 3703] plasma_store_provider.cc:132: Failed to put object 32d950ec0ccf9d2affffffffffffffffffffffff0100000001000000 in object store because it is full. Object size is 2271683242145 bytes.
(_execute_read_task pid=3703, ip=xxxx) Plasma store status:
(_execute_read_task pid=3703, ip=xxxx)
(_execute_read_task pid=3703, ip=xxxx) (global lru) capacity: 216423994163
(_execute_read_task pid=3703, ip=xxxx) (global lru) used: 0%
(_execute_read_task pid=3703, ip=xxxx) (global lru) num objects: 0
(_execute_read_task pid=3703, ip=xxxx) (global lru) num evictions: 0
(_execute_read_task pid=3703, ip=xxxx) (global lru) bytes evicted: 0
(_execute_read_task pid=3703, ip=xxxx) ---
(_execute_read_task pid=3703, ip=xxxx) --- Tip: Use the `ray memory` command to list active objects in the cluster.
(_execute_read_task pid=3703, ip=xxxx) ---
(_execute_read_task pid=3703, ip=xxxx)
(raylet, ip=xxxx) [2022-08-02 10:14:28,227 E 3605 3630] (raylet) file_system_monitor.cc:105: /tmp/ray/session_2022-08-02_10-11-10_488472_53120 is over 95% full, available space: 52532363264; capacity: 1056619761664. Object creation will fail if spilling is required.
(raylet, ip=xxxx) [2022-08-02 10:14:28,262 E 3605 3629] (raylet) dlmalloc.cc:202: Out of disk space with fallocate error: No space left on device
(raylet, ip=xxxx) [2022-08-02 10:14:28,262 E 3605 3629] (raylet) dlmalloc.cc:202: Out of disk space with fallocate error: No space left on device
(raylet, ip=xxxx) [2022-08-02 10:14:28,262 E 3605 3629] (raylet) object_lifecycle_manager.cc:214: Plasma fallback allocator failed, likely out of disk space.
```
The message shows the `read_parquets()` returned a strange huge size **2271683242145 bytes**. Actually the size of parquet in the local S3 server is about 3GiB (much less than the huge size). And I have the test with **different** parquet size, but the error message shows the same num **2271683242145 bytes**.

Another test is that I read the data by modin and convert it to ray dataset by `.from_modin()`
```
import modin.pandas as pd
df = pd.read_parquet('s3://BUCKET',
storage_options={"key": "KEY",
                    "secret": "SECRET",
                    "client_kwargs":{
                        'endpoint_url': 'ip:port',
                    },
                    "config_kwargs":{
                        'signature_version': 's3v4'
                    }
})
dtr = ray.data.from_modin(train_set)
```
The result is correct.

### Versions / Dependencies

|  lib | version  |
| ------------ | ------------ |
|  python | 3.8.13  |
|  ray | 2.0.0rc0 & 1.13  |
|s3fs|2022.5.0|
|modin|0.15.0|

### Reproduction script

```
import ray
from s3fs import S3FileSystem

ray_init() # some initialization for ray

parquets = ray.data.read_parquet(
    's3://BUCKET',
    filesystem=S3FileSystem(   **{"key": "KEY",
                    "secret": "SECRET",
                    "client_kwargs":{
                        'endpoint_url': 'http://ip:port',
                    },
                    "config_kwargs":{
                        'signature_version': 's3v4'
                    }
    }),
)
print("parquet size", parquets.count())

parquets.show()
modin_format_data = parquets.to_modin()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by cq70605** [comment]
I'm getting the same error when attempting to run `ds.show()`, the size of dataset is 20,000,000*5 and the disk is used more than 150GB.

**Comment by guodashun** [comment]
The parquet data generation script is as follow:
```
import pandas as pd
import pandas as ppd
import numpy as np

from sklearn.datasets import make_classification, make_regression
from sklearn.model_selection import train_test_split


def create_learnable_data(num_rows,
                          num_cols,
                          num_classes,
                          target_accuracy,
                          seed=1234,
                          split=True):
    """Create a synthetic dataset and return a pandas df."""
    seed = int(seed)
    np.random.seed(seed)

    num_rows = int(num_rows)
    num_cols = int(num_cols)
    num_classes = int(num_classes)
    target = float(target_accuracy)

    if num_classes > 0:
        x, y = make_classification(
            n_samples=num_rows,
            n_features=num_cols,
            n_informative=num_cols // 2,
            n_redundant=num_cols // 10,
            n_repeated=0,
            n_classes=num_classes,
            n_clusters_per_class=2,
            flip_y=1 - target,
            random_state=seed,
        )
    else:
        x, y = make_regression(
            n_samples=num_rows,
            n_features=num_cols,
            n_informative=num_cols // 2,
            n_targets=1,
            noise=0.1,
            random_state=seed,
        )

    data = ppd.DataFrame(x, columns=[f"feature_{i}" for i in range(num_cols)])
    # print(y)
    # y = list(map(str, y))
    data["labels"] = ppd.Series(y)
    return data


if __name__ == "__main__":
    train_data = create_learnable_data(num_rows=1e8,
                                       num_cols=4,
                                       num_classes=2,
                                       target_accuracy=0.8,
                                       seed=1234)
    print(train_data)
    train_data.to_parquet('./parquets/1.parquet')
```
The data shape is (1e8, 5) and the parquet file is about 3GiB.

**Comment by clarkzinzow** [comment]
Hey @guodashun, what pyarrow version are you using? There's a pyarrow bug in pyarrow 7.0.0+ that can cause this kind of huge object bloat.

**Comment by guodashun** [comment]
@clarkzinzow thx for your reply! I changed the pyarrow version from 8.0.0 to 6.0.1 and this bug was fixed!
