### ISSUE TITLE
[Kubernetes] ray-operator process hangs after head goes down, fails to restart it

### ISSUE THREAD

**Issue by mihajenko** [ray-project/ray#27414]
### What happened + What you expected to happen

Our ray cluster crashed with RayCluster CRD resource state `AutoscalingExceptionRecovery`. The head node Pod went down. The ray-operator Pod was in `Running` state, but the operator Python process seemed unresponsive.

I expected the head node to be restarted, as per the documentation.

Log from the ray-operator Pod:

```
ray-ac,auto-cat-ml:2022-07-29 01:10:29,580	INFO autoscaler.py:330 --
======== Autoscaler status: 2022-07-29 01:10:29.580599 ========
Node status
---------------------------------------------------------------
Healthy:
 1 rayHeadType
 4 rayInferenceCpuType
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 5.0/10.0 CPU
 1.0/1.0 ingress_capacity
 0.00/10.500 GiB memory
 0.00/4.317 GiB object_store_memory
 4.0/4.0 text_model_capacity

Demands:
 (no resource demands)
ray-ac,auto-cat-ml:2022-07-29 01:10:29,695	DEBUG gcs_utils.py:224 -- internal_kv_put b'__autoscaling_status_legacy' b"Cluster status: 4 nodes (1 failed to update)\n - MostDelayedHeartbeats: {'10.115.32.8': 0.4465169906616211, '10.115.12.22': 0.4464714527130127, '10.115.26.150': 0.4464387893676758, '10.115.40.235': 0.44640660285949707, '10.115.32.199': 0.4463787078857422}\n - NodeIdleSeconds: Min=0 Mean=0 Max=0\n - ResourceUsage: 5.0/10.0 CPU, 1.0/1.0 ingress_capacity, 0.0 GiB/10.5 GiB memory, 0.0 GiB/4.32 GiB object_store_memory, 4.0/4.0 text_model_capacity\n - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0\nWorker node types:\n - rayInferenceCpuType: 4" True None
ray-ac,auto-cat-ml:2022-07-29 01:10:29,697	DEBUG legacy_info_string.py:26 -- Cluster status: 4 nodes (1 failed to update)
 - MostDelayedHeartbeats: {'10.115.32.8': 0.4465169906616211, '10.115.12.22': 0.4464714527130127, '10.115.26.150': 0.4464387893676758, '10.115.40.235': 0.44640660285949707, '10.115.32.199': 0.4463787078857422}
 - NodeIdleSeconds: Min=0 Mean=0 Max=0
 - ResourceUsage: 5.0/10.0 CPU, 1.0/1.0 ingress_capacity, 0.0 GiB/10.5 GiB memory, 0.0 GiB/4.32 GiB object_store_memory, 4.0/4.0 text_model_capacity
 - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0
Worker node types:
 - rayInferenceCpuType: 4
ray-ac,auto-cat-ml:2022-07-29 01:10:29,993	DEBUG autoscaler.py:1212 -- ray-ac-ray-inference-cpu-type-7pl27 is not being updated and passes config check (can_update=True).
ray-ac,auto-cat-ml:2022-07-29 01:10:30,037	DEBUG autoscaler.py:1212 -- ray-ac-ray-inference-cpu-type-hffzb is not being updated and passes config check (can_update=True).
ray-ac,auto-cat-ml:2022-07-29 01:10:30,083	DEBUG autoscaler.py:1212 -- ray-ac-ray-inference-cpu-type-q9bc4 is not being updated and passes config check (can_update=True).
ray-ac,auto-cat-ml:2022-07-29 01:10:30,126	DEBUG autoscaler.py:1212 -- ray-ac-ray-inference-cpu-type-xjscs is not being updated and passes config check (can_update=True).
ray-ac,auto-cat-ml:2022-07-29 01:10:30,170	DEBUG autoscaler.py:1212 -- ray-ac-ray-inference-cpu-type-7pl27 is not being updated and passes config check (can_update=True).
ray-ac,auto-cat-ml:2022-07-29 01:10:30,198	DEBUG autoscaler.py:1212 -- ray-ac-ray-inference-cpu-type-hffzb is not being updated and passes config check (can_update=True).
ray-ac,auto-cat-ml:2022-07-29 01:10:30,225	DEBUG autoscaler.py:1212 -- ray-ac-ray-inference-cpu-type-q9bc4 is not being updated and passes config check (can_update=True).
ray-ac,auto-cat-ml:2022-07-29 01:10:30,259	DEBUG autoscaler.py:1212 -- ray-ac-ray-inference-cpu-type-xjscs is not being updated and passes config check (can_update=True).
ray-ac,auto-cat-ml:2022-07-29 01:10:30,523	DEBUG resource_demand_scheduler.py:193 -- Cluster resources: [{'memory': 2254857830.0, 'object_store_memory': 897622425.0, 'node:10.115.12.22': 0.98, 'CPU': 1.0, 'ingress_capacity': 0.0}, {'memory': 2254857830.0, 'CPU': 1.0, 'object_store_memory': 941982105.0, 'node:10.115.32.8': 1.0, 'text_model_capacity': 0.0}, {'memory': 2254857830.0, 'CPU': 1.0, 'object_store_memory': 941862912.0, 'node:10.115.40.235': 1.0, 'text_model_capacity': 0.0}, {'object_store_memory': 930361344.0, 'memory': 2254857830.0, 'CPU': 1.0, 'node:10.115.26.150': 1.0, 'text_model_capacity': 0.0}, {'object_store_memory': 923208499.0, 'CPU': 1.0, 'node:10.115.32.199': 1.0, 'memory': 2254857830.0, 'text_model_capacity': 0.0}]
ray-ac,auto-cat-ml:2022-07-29 01:10:30,523	DEBUG resource_demand_scheduler.py:194 -- Node counts: defaultdict(<class 'int'>, {'rayHeadType': 1, 'rayInferenceCpuType': 4})
ray-ac,auto-cat-ml:2022-07-29 01:10:30,523	DEBUG resource_demand_scheduler.py:211 -- Placement group demands: []
ray-ac,auto-cat-ml:2022-07-29 01:10:30,523	DEBUG resource_demand_scheduler.py:275 -- Resource demands: []
ray-ac,auto-cat-ml:2022-07-29 01:10:30,523	DEBUG resource_demand_scheduler.py:276 -- Unfulfilled demands: []
ray-ac,auto-cat-ml:2022-07-29 01:10:30,523	DEBUG resource_demand_scheduler.py:284 -- Final unfulfilled: []
ray-ac,auto-cat-ml:2022-07-29 01:10:30,664	DEBUG resource_demand_scheduler.py:309 -- Node requests: {}
ray-ac,auto-cat-ml:2022-07-29 01:10:30,825	DEBUG gcs_utils.py:224 -- internal_kv_put b'__autoscaling_status' b'{"load_metrics_report": {"usage": {"ingress_capacity": [1.0, 1.0], "object_store_memory": [0.0, 4635037285.0], "memory": [0.0, 11274289150.0], "CPU": [5.0, 10.0], "node:10.115.12.22": [0.020000000000000018, 1.0], "node:10.115.32.8": [0.0, 1.0], "text_model_capacity": [4.0, 4.0], "node:10.115.32.199": [0.0, 1.0], "node:10.115.26.150": [0.0, 1.0], "node:10.115.40.235": [0.0, 1.0]}, "resource_demand": [], "pg_demand": [], "request_demand": [], "node_types": [[{"ingress_capacity": 1.0, "node:10.115.12.22": 1.0, "object_store_memory": 897622425.0, "memory": 2254857830.0, "CPU": 2.0}, 1], [{"object_store_memory": 941982105.0, "text_model_capacity": 1.0, "memory": 2254857830.0, "node:10.115.32.8": 1.0, "CPU": 2.0}, 1], [{"object_store_memory": 923208499.0, "text_model_capacity": 1.0, "node:10.115.32.199": 1.0, "memory": 2254857830.0, "CPU": 2.0}, 1], [{"node:10.115.26.150": 1.0, "text_model_capacity": 1.0, "memory": 2254857830.0, "object_store_memory": 930361344.0, "CPU": 2.0}, 1], [{"node:10.115.40.235": 1.0, "text_model_capacity": 1.0, "memory": 2254857830.0, "CPU": 2.0, "object_store_memory": 941862912.0}, 1]], "head_ip": null}, "time": 1659082229.136676, "monitor_pid": 425, "autoscaler_report": {"active_nodes": {"rayHeadType": 1, "rayInferenceCpuType": 4}, "pending_nodes": [], "pending_launches": {}, "failed_nodes": []}}' True None
ray-ac,auto-cat-ml:2022-07-29 01:10:35,880	ERROR monitor.py:439 -- Error in monitor loop
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 484, in run
    self._run()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 338, in _run
    self.update_load_metrics()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 243, in update_load_metrics
    response = self.gcs_node_resources_stub.GetAllResourceUsage(request, timeout=60)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1659082235.832517133","description":"Error received from peer ipv4:10.115.12.22:6379","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Socket closed","grpc_status":14}"
>
ray-ac,auto-cat-ml:2022-07-29 01:10:35,880	DEBUG gcs_utils.py:224 -- internal_kv_put b'__autoscaling_error' b'The autoscaler failed with the following error:\nTraceback (most recent call last):\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 484, in run\n    self._run()\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 338, in _run\n    self.update_load_metrics()\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 243, in update_load_metrics\n    response = self.gcs_node_resources_stub.GetAllResourceUsage(request, timeout=60)\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "Socket closed"\n\tdebug_error_string = "{"created":"@1659082235.832517133","description":"Error received from peer ipv4:10.115.12.22:6379","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Socket closed","grpc_status":14}"\n>\n' True None
ray-ac,auto-cat-ml:2022-07-29 01:10:35,881	DEBUG gcs_utils.py:142 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1659082235.881193371","description":"Error received from peer ipv4:10.115.12.22:6379","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Socket closed","grpc_status":14}"
>
ray-ac,auto-cat-ml:2022-07-29 01:10:36,883	DEBUG gcs_utils.py:224 -- internal_kv_put b'__autoscaling_error' b'The autoscaler failed with the following error:\nTraceback (most recent call last):\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 484, in run\n    self._run()\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 338, in _run\n    self.update_load_metrics()\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 243, in update_load_metrics\n    response = self.gcs_node_resources_stub.GetAllResourceUsage(request, timeout=60)\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "Socket closed"\n\tdebug_error_string = "{"created":"@1659082235.832517133","description":"Error received from peer ipv4:10.115.12.22:6379","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Socket closed","grpc_status":14}"\n>\n' True None
ray-ac,auto-cat-ml:2022-07-29 01:10:56,884	DEBUG gcs_utils.py:142 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1659082256.884322359","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1659082256.884321223","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
ray-ac,auto-cat-ml:2022-07-29 01:10:57,886	DEBUG gcs_utils.py:224 -- internal_kv_put b'__autoscaling_error' b'The autoscaler failed with the following error:\nTraceback (most recent call last):\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 484, in run\n    self._run()\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 338, in _run\n    self.update_load_metrics()\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 243, in update_load_metrics\n    response = self.gcs_node_resources_stub.GetAllResourceUsage(request, timeout=60)\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "Socket closed"\n\tdebug_error_string = "{"created":"@1659082235.832517133","description":"Error received from peer ipv4:10.115.12.22:6379","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Socket closed","grpc_status":14}"\n>\n' True None
ray-ac,auto-cat-ml:2022-07-29 01:11:17,887	DEBUG gcs_utils.py:142 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1659082277.886839616","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1659082277.886838469","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
ray-ac,auto-cat-ml:2022-07-29 01:11:18,889	DEBUG gcs_utils.py:224 -- internal_kv_put b'__autoscaling_error' b'The autoscaler failed with the following error:\nTraceback (most recent call last):\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 484, in run\n    self._run()\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 338, in _run\n    self.update_load_metrics()\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 243, in update_load_metrics\n    response = self.gcs_node_resources_stub.GetAllResourceUsage(request, timeout=60)\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "Socket closed"\n\tdebug_error_string = "{"created":"@1659082235.832517133","description":"Error received from peer ipv4:10.115.12.22:6379","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Socket closed","grpc_status":14}"\n>\n' True None
ray-ac,auto-cat-ml:2022-07-29 01:11:38,889	DEBUG gcs_utils.py:142 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1659082298.888852869","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1659082298.888851620","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
ray-ac,auto-cat-ml:2022-07-29 01:11:39,891	DEBUG gcs_utils.py:224 -- internal_kv_put b'__autoscaling_error' b'The autoscaler failed with the following error:\nTraceback (most recent call last):\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 484, in run\n    self._run()\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 338, in _run\n    self.update_load_metrics()\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 243, in update_load_metrics\n    response = self.gcs_node_resources_stub.GetAllResourceUsage(request, timeout=60)\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "Socket closed"\n\tdebug_error_string = "{"created":"@1659082235.832517133","description":"Error received from peer ipv4:10.115.12.22:6379","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Socket closed","grpc_status":14}"\n>\n' True None
ray-ac,auto-cat-ml:2022-07-29 01:11:59,892	DEBUG gcs_utils.py:142 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1659082319.891854598","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1659082319.891852800","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
ray-ac,auto-cat-ml:2022-07-29 01:12:00,894	DEBUG gcs_utils.py:224 -- internal_kv_put b'__autoscaling_error' b'The autoscaler failed with the following error:\nTraceback (most recent call last):\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 484, in run\n    self._run()\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 338, in _run\n    self.update_load_metrics()\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 243, in update_load_metrics\n    response = self.gcs_node_resources_stub.GetAllResourceUsage(request, timeout=60)\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "Socket closed"\n\tdebug_error_string = "{"created":"@1659082235.832517133","description":"Error received from peer ipv4:10.115.12.22:6379","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Socket closed","grpc_status":14}"\n>\n' True None

2022-07-28 21:53:29,296	INFO updater.py:313 -- SSH still not available [2m(Exit Status 1): kubectl -n auto-cat-ml exec -it ray-ac-ray-inference-cpu-type-hffzb -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'[22m[26m, retrying in [1m5[22m[26m seconds.
2022-07-28 21:53:34,496	INFO updater.py:313 -- SSH still not available [2m(Exit Status 1): kubectl -n auto-cat-ml exec -it ray-ac-ray-inference-cpu-type-hffzb -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'[22m[26m, retrying in [1m5[22m[26m seconds.
2022-07-28 21:53:39,694	INFO updater.py:313 -- SSH still not available [2m(Exit Status 1): kubectl -n auto-cat-ml exec -it ray-ac-ray-inference-cpu-type-hffzb -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'[22m[26m, retrying in [1m5[22m[26m seconds.
2022-07-28 21:53:44,902	INFO updater.py:313 -- SSH still not available [2m(Exit Status 1): kubectl -n auto-cat-ml exec -it ray-ac-ray-inference-cpu-type-hffzb -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'[22m[26m, retrying in [1m5[22m[26m seconds.
2022-07-28 21:53:50,140	INFO updater.py:313 -- SSH still not available [2m(Exit Status 1): kubectl -n auto-cat-ml exec -it ray-ac-ray-inference-cpu-type-hffzb -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'[22m[26m, retrying in [1m5[22m[26m seconds.
2022-07-28 21:53:55,804	INFO updater.py:313 -- SSH still not available [2m(Exit Status 1): kubectl -n auto-cat-ml exec -it ray-ac-ray-inference-cpu-type-hffzb -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'[22m[26m, retrying in [1m5[22m[26m seconds.
2022-07-28 21:54:03,232	SUCC updater.py:281 -- [32mSuccess.[39m
2022-07-28 21:54:03,233	INFO log_timer.py:25 -- NodeUpdater: ray-ac-ray-inference-cpu-type-hffzb: Got remote shell  [LogTimer=144032ms]
2022-07-28 21:54:03,255	INFO updater.py:375 -- Updating cluster configuration.[0m[2m [hash=31a44662c31ef96921d7fcd991b631ed135aba1e][22m[0m
2022-07-28 21:54:06,393	INFO updater.py:382 -- [37mNew status[39m: [1msyncing-files[22m
2022-07-28 21:54:06,393	INFO updater.py:239 -- [2m[2/7][22m [36mProcessing file mounts[39m
2022-07-28 21:54:06,393	INFO updater.py:256 -- [2m[3/7][22m No worker file mounts to sync
2022-07-28 21:54:09,449	INFO updater.py:393 -- [37mNew status[39m: [1msetting-up[22m
2022-07-28 21:54:09,450	INFO updater.py:434 -- [2m[4/7][22m No initialization commands to run.
2022-07-28 21:54:09,450	INFO updater.py:438 -- [2m[5/7][22m [36mInitalizing command runner[39m
2022-07-28 21:54:09,450	INFO updater.py:485 -- [2m[6/7][22m No setup commands to run.
2022-07-28 21:54:09,450	INFO updater.py:490 -- [2m[7/7][22m [36mStarting the Ray runtime[39m
2022-07-28 21:54:16,866	INFO log_timer.py:25 -- NodeUpdater: ray-ac-ray-inference-cpu-type-hffzb: Ray start commands succeeded [LogTimer=7416ms]
2022-07-28 21:54:16,866	INFO log_timer.py:25 -- NodeUpdater: ray-ac-ray-inference-cpu-type-hffzb: Applied config 31a44662c31ef96921d7fcd991b631ed135aba1e  [LogTimer=160566ms]
2022-07-28 21:54:19,928	INFO updater.py:189 -- [37mNew status[39m: [1mup-to-date[22m
Process ray-ac,auto-cat-ml:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 484, in run
    self._run()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 338, in _run
    self.update_load_metrics()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 243, in update_load_metrics
    response = self.gcs_node_resources_stub.GetAllResourceUsage(request, timeout=60)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1659082235.832517133","description":"Error received from peer ipv4:10.115.12.22:6379","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Socket closed","grpc_status":14}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ray/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/ray_operator/operator.py", line 78, in _create_or_update
    self.start_monitor()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/ray_operator/operator.py", line 120, in start_monitor
    mtr.run()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 486, in run
    self._handle_failure(traceback.format_exc())
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 452, in _handle_failure
    _internal_kv_put(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/experimental/internal_kv.py", line 88, in _internal_kv_put
    return global_gcs_client.internal_kv_put(key, value, overwrite, namespace) == 0
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/gcs_utils.py", line 137, in wrapper
    return f(self, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/gcs_utils.py", line 228, in internal_kv_put
    reply = self._kv_stub.InternalKVPut(req)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1659082340.894811995","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1659082340.894810508","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
```

During the crash, we were still using the experimental Ray Serve `checkpoint_path` failure recovery feature. We tried reproducing from having operator/head/worker in various states, without success.

---

Would it be possible to add some kind of liveness probe to the operator Pod, in case the process hangs again?

### Versions / Dependencies

* Kubernetes 1.22 in Google Kubernetes Engine
* Ubuntu based ray docker images
* ray 1.3.0
* Python 3.8.12
* old ray-operator Deployment

### Reproduction script

Could not reproduce.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by simon-mo** [comment]
We would love for you to try out kuberay operator, where we have readiness and liveness prod setup and failure handling builtin.
https://ray-project.github.io/kuberay/guidance/rayservice/
https://docs.ray.io/en/master/serve/production-guide/fault-tolerance.html
