### ISSUE TITLE
[Serve] ray serve not compatible with newrelic

### ISSUE THREAD

**Issue by ArzelaAscoIi** [ray-project/ray#27494]
### What happened + What you expected to happen

If you run the ray serve sample and wrap it with `newrelic-admin run-program python <your-file-with-serve-deployments>.py` you will get the following error message: 
```
Traceback (most recent call last):
  File "/Users/arzelaascoli/Development/ray-newrelic/ray-newrelic.py", line 9, in <module>
    class Counter:
  File "/Users/arzelaascoli/.pyenv/versions/3.9.9/lib/python3.9/site-packages/ray/serve/api.py", line 287, in decorator
    frozen_app = cloudpickle.loads(cloudpickle.dumps(app))
  File "/Users/arzelaascoli/.pyenv/versions/3.9.9/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/Users/arzelaascoli/.pyenv/versions/3.9.9/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 620, in dump
    return Pickler.dump(self, obj)
NotImplementedError: object proxy must define __reduce_ex__()
```

I would expect that the serialization of the deployment is called on deployment (or maybe on `ray.init`/`serve.start`)  and not during initialization.  It might still be fine if this causes error messages. 

### Versions / Dependencies

ray==1.13.0

### Reproduction script

``` my-serve-deployment.py
from fastapi import FastAPI
from ray import serve

app = FastAPI()


@serve.deployment
@serve.ingress(app)
class Counter:
    pass
```

Run:
```sh 
NEW_RELIC_LICENSE_KEY=<my-license-key> newrelic-admin run-program python3 ray-newrelic.py
```

**Comment by simon-mo** [comment]
`newrelic-admin run-program`

Indeed. Ray runs workers in distributed manner, the newrelic-admin approach is not compatible because it attaches processes with a single driver python3 program.
