### ISSUE TITLE
Mujoco Rendering fails from Thread on Docker

### ISSUE THREAD

**Issue by febert** [ray-project/ray#2750]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Docker image with ubuntu 16.04:  available here: febert/tf_mj1.5:runmount
- **Ray installed from (source or binary)**: binary
- **Ray version**:  0.5.0
- **Python version**:  3.6
- **Exact command to reproduce**: 

### Describe the problem
Rendering with mujoco fails when called from a ray-thread inside the docker container. It works fine outside the docker container.

### Source code / logs
The source code is here:
https://github.com/febert/visual_mpc/blob/refactor_cem/python_visual_mpc/misc/minimal_ray_mujoco.py
the xml to run mujoco is here:
https://github.com/febert/visual_mpc/blob/refactor_cem/mjc_models/cartgripper_noautogen.xml

Here's the traceback:
```
Remote function run_sim failed with:
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/ray/worker.py", line 770, in _process_task
    *arguments)
  File "/usr/local/lib/python3.5/dist-packages/ray/actor.py", line 162, in actor_method_executor
    return method(actor, *args)
  File "minimal_ray_mujoco.py", line 19, in run_sim
    images.append(self.sim.render(100, 100))
  File "mjsim.pyx", line 151, in mujoco_py.cymj.MjSim.render
  File "mjsim.pyx", line 153, in mujoco_py.cymj.MjSim.render
  File "mjrendercontext.pyx", line 43, in mujoco_py.cymj.MjRenderContext.__init__
  File "mjrendercontext.pyx", line 98, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
ValueError: invalid literal for int() with base 10: ''


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:37665")
  
Traceback (most recent call last):
  File "minimal_ray_mujoco.py", line 46, in <module>
    run()
  File "minimal_ray_mujoco.py", line 41, in run
    images = ray.get(id)
  File "/usr/local/lib/python3.5/dist-packages/ray/worker.py", line 2253, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(7bc7814870c91dde283558b34923a65890aed14e). It was created by remote function run_sim which failed with:

Remote function run_sim failed with:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ray/worker.py", line 770, in _process_task
    *arguments)
  File "/usr/local/lib/python3.5/dist-packages/ray/actor.py", line 162, in actor_method_executor
    return method(actor, *args)
  File "minimal_ray_mujoco.py", line 19, in run_sim
    images.append(self.sim.render(100, 100))
  File "mjsim.pyx", line 151, in mujoco_py.cymj.MjSim.render
  File "mjsim.pyx", line 153, in mujoco_py.cymj.MjSim.render
  File "mjrendercontext.pyx", line 43, in mujoco_py.cymj.MjRenderContext.__init__
  File "mjrendercontext.pyx", line 98, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
ValueError: invalid literal for int() with base 10: ''
```
Thanks!

Frederik

**Comment by robertnishihara** [comment]
Does it work in the Docker container without using Ray at all? E.g., if you replace `ray.init()` with `ray.init(driver_mode=ray.PYTHON_MODE)` (which recently changed to `ray.LOCAL_MODE`), does that run?

**Comment by robertnishihara** [comment]
@febert and I just looked into this and the issue was that calling `run_sim.remote()` tried to use a GPU, but because `num_gpus=1` had not been passed into the decorator, Ray was setting `CUDA_VISIBLE_DEVICES=''` which was causing the rendering to fail.

**Comment by geyang** [comment]
Here is a message from our network admin:


> FYI, this is a known error where Ray assumes CUDA_VISIBLE_DEVICES is an integer. We’re using NVIDIA’s UUID API to set the device names to the UUID, rather than the default. The problem with the default naming scheme (0,1,etc) is that it is not consistent. What’s listed as GPU 0 might change even within a job, which you can imagine would cause major problems if you have two people on a node, each allocated one GPU. This sort of alludes to what I’m talking about, but doesn’t get into using the UUID’s instead: https://stackoverflow.com/questions/26123252/inconsistency-of-ids-between-nvidia-smi-l-and-cudevicegetname. It’s a big oversight on Ray’s part to assume that the GPU names are integers, both Tensorflow and Pytorch don’t seem to have a problem with it. I think what they need to understand is that in a shared environment you have to make sure people use only the GPU that’s been allocated to them, and the way to do that is to use the UUID.

**Comment by robertnishihara** [comment]
I thought this had been fixed by https://github.com/ray-project/ray/pull/9744, but maybe not? What version of Ray are you using?
