### ISSUE TITLE
[Serve] `ServeController` repeatedly logs a `TimeoutError`

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#27677]
### What happened + What you expected to happen

When I run Serve through the Python interpreter, it keeps logging a `TimeoutError`. However, everything seems to be working correctly, so I'm not sure whether this error should be surfaced:

```console
(ServeController pid=17473) 2022-08-08 16:55:20,981	INFO (unknown file):0 -- Task failed with unretryable exception: TaskID(7171655ca73a7054820439e395be52651b8c4f6101000000).
(ServeController pid=17473) Traceback (most recent call last):
(ServeController pid=17473)   File "python/ray/_raylet.pyx", line 709, in ray._raylet.execute_task
(ServeController pid=17473)   File "python/ray/_raylet.pyx", line 713, in ray._raylet.execute_task
(ServeController pid=17473)   File "python/ray/_raylet.pyx", line 655, in ray._raylet.execute_task.function_executor
(ServeController pid=17473)   File "python/ray/_raylet.pyx", line 2243, in ray._raylet.CoreWorker.run_async_func_in_event_loop
(ServeController pid=17473)   File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/concurrent/futures/_base.py", line 437, in result
(ServeController pid=17473)     return self.__get_result()
(ServeController pid=17473)   File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
(ServeController pid=17473)     raise self._exception
(ServeController pid=17473)   File "/Users/shrekris/Desktop/ray/python/ray/util/tracing/tracing_helper.py", line 498, in _resume_span
(ServeController pid=17473)     return await method(self, *_args, **_kwargs)
(ServeController pid=17473)   File "/Users/shrekris/Desktop/ray/python/ray/serve/controller.py", line 181, in listen_for_change
(ServeController pid=17473)     return await (self.long_poll_host.listen_for_change(keys_to_snapshot_ids))
(ServeController pid=17473)   File "/Users/shrekris/Desktop/ray/python/ray/serve/_private/long_poll.py", line 249, in listen_for_change
(ServeController pid=17473)     raise asyncio.TimeoutError("Polling request timed out.")
(ServeController pid=17473) asyncio.exceptions.TimeoutError: Polling request timed out.
```

### Versions / Dependencies

Ray on the latest master.

### Reproduction script

On the Python interpreter:

```python
>>> import ray
>>> from ray import serve

>>> @serve.deployment
>>> def f(): pass

>>> serve.start()

...After waiting about 35 seconds...

>>> (ServeController pid=18650) 2022-08-08 17:02:45,407	INFO (unknown file):0 -- Task failed with unretryable exception: TaskID(928a4e0aa6ea7800bf2f7875f2a6fbf7b2db89b101000000).
(ServeController pid=18650) Traceback (most recent call last):
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 709, in ray._raylet.execute_task
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 713, in ray._raylet.execute_task
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 655, in ray._raylet.execute_task.function_executor
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 2243, in ray._raylet.CoreWorker.run_async_func_in_event_loop
(ServeController pid=18650)   File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/concurrent/futures/_base.py", line 437, in result
(ServeController pid=18650)     return self.__get_result()
(ServeController pid=18650)   File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
(ServeController pid=18650)     raise self._exception
(ServeController pid=18650)   File "/Users/shrekris/Desktop/ray/python/ray/util/tracing/tracing_helper.py", line 498, in _resume_span
(ServeController pid=18650)     return await method(self, *_args, **_kwargs)
(ServeController pid=18650)   File "/Users/shrekris/Desktop/ray/python/ray/serve/controller.py", line 181, in listen_for_change
(ServeController pid=18650)     return await (self.long_poll_host.listen_for_change(keys_to_snapshot_ids))
(ServeController pid=18650)   File "/Users/shrekris/Desktop/ray/python/ray/serve/_private/long_poll.py", line 249, in listen_for_change
(ServeController pid=18650)     raise asyncio.TimeoutError("Polling request timed out.")
(ServeController pid=18650) asyncio.exceptions.TimeoutError: Polling request timed out.
(ServeController pid=18650) 2022-08-08 17:03:41,526	INFO (unknown file):0 -- Task failed with unretryable exception: TaskID(566a9d3467c6412abf2f7875f2a6fbf7b2db89b101000000).
(ServeController pid=18650) Traceback (most recent call last):
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 709, in ray._raylet.execute_task
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 713, in ray._raylet.execute_task
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 655, in ray._raylet.execute_task.function_executor
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 2243, in ray._raylet.CoreWorker.run_async_func_in_event_loop
(ServeController pid=18650)   File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/concurrent/futures/_base.py", line 437, in result
(ServeController pid=18650)     return self.__get_result()
(ServeController pid=18650)   File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
(ServeController pid=18650)     raise self._exception
(ServeController pid=18650)   File "/Users/shrekris/Desktop/ray/python/ray/util/tracing/tracing_helper.py", line 498, in _resume_span
(ServeController pid=18650)     return await method(self, *_args, **_kwargs)
(ServeController pid=18650)   File "/Users/shrekris/Desktop/ray/python/ray/serve/controller.py", line 181, in listen_for_change
(ServeController pid=18650)     return await (self.long_poll_host.listen_for_change(keys_to_snapshot_ids))
(ServeController pid=18650)   File "/Users/shrekris/Desktop/ray/python/ray/serve/_private/long_poll.py", line 249, in listen_for_change
(ServeController pid=18650)     raise asyncio.TimeoutError("Polling request timed out.")
(ServeController pid=18650) asyncio.exceptions.TimeoutError: Polling request timed out.
```

Here's a live example:

```python
shrekris@Shreyas-MacBook-Pro tests % python
Python 3.8.12 | packaged by conda-forge | (default, Sep 29 2021, 19:21:23) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
from ray>>> from ray import serve
>>> @serve.deployment
... def f(): pass
... 
>>> serve.start()
2022-08-08 17:02:08,881	INFO worker.py:1481 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265.
(ServeController pid=18650) INFO 2022-08-08 17:02:10,952 controller 18650 http_state.py:123 - Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:MFJzvi:SERVE_PROXY_ACTOR-2bccd2c817de1094197f40ad65601e3c23a7081255941c521703ccc3' on node '2bccd2c817de1094197f40ad65601e3c23a7081255941c521703ccc3' listening on '127.0.0.1:8000'
<ray.serve._private.client.ServeControllerClient object at 0x118d8e0a0>
>>> (HTTPProxyActor pid=18652) INFO:     Started server process [18652]

>>> (ServeController pid=18650) 2022-08-08 17:02:45,407	INFO (unknown file):0 -- Task failed with unretryable exception: TaskID(928a4e0aa6ea7800bf2f7875f2a6fbf7b2db89b101000000).
(ServeController pid=18650) Traceback (most recent call last):
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 709, in ray._raylet.execute_task
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 713, in ray._raylet.execute_task
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 655, in ray._raylet.execute_task.function_executor
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 2243, in ray._raylet.CoreWorker.run_async_func_in_event_loop
(ServeController pid=18650)   File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/concurrent/futures/_base.py", line 437, in result
(ServeController pid=18650)     return self.__get_result()
(ServeController pid=18650)   File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
(ServeController pid=18650)     raise self._exception
(ServeController pid=18650)   File "/Users/shrekris/Desktop/ray/python/ray/util/tracing/tracing_helper.py", line 498, in _resume_span
(ServeController pid=18650)     return await method(self, *_args, **_kwargs)
(ServeController pid=18650)   File "/Users/shrekris/Desktop/ray/python/ray/serve/controller.py", line 181, in listen_for_change
(ServeController pid=18650)     return await (self.long_poll_host.listen_for_change(keys_to_snapshot_ids))
(ServeController pid=18650)   File "/Users/shrekris/Desktop/ray/python/ray/serve/_private/long_poll.py", line 249, in listen_for_change
(ServeController pid=18650)     raise asyncio.TimeoutError("Polling request timed out.")
(ServeController pid=18650) asyncio.exceptions.TimeoutError: Polling request timed out.
(ServeController pid=18650) 2022-08-08 17:03:41,526	INFO (unknown file):0 -- Task failed with unretryable exception: TaskID(566a9d3467c6412abf2f7875f2a6fbf7b2db89b101000000).
(ServeController pid=18650) Traceback (most recent call last):
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 709, in ray._raylet.execute_task
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 713, in ray._raylet.execute_task
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 655, in ray._raylet.execute_task.function_executor
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 2243, in ray._raylet.CoreWorker.run_async_func_in_event_loop
(ServeController pid=18650)   File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/concurrent/futures/_base.py", line 437, in result
(ServeController pid=18650)     return self.__get_result()
(ServeController pid=18650)   File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
(ServeController pid=18650)     raise self._exception
(ServeController pid=18650)   File "/Users/shrekris/Desktop/ray/python/ray/util/tracing/tracing_helper.py", line 498, in _resume_span
(ServeController pid=18650)     return await method(self, *_args, **_kwargs)
(ServeController pid=18650)   File "/Users/shrekris/Desktop/ray/python/ray/serve/controller.py", line 181, in listen_for_change
(ServeController pid=18650)     return await (self.long_poll_host.listen_for_change(keys_to_snapshot_ids))
(ServeController pid=18650)   File "/Users/shrekris/Desktop/ray/python/ray/serve/_private/long_poll.py", line 249, in listen_for_change
(ServeController pid=18650)     raise asyncio.TimeoutError("Polling request timed out.")
(ServeController pid=18650) asyncio.exceptions.TimeoutError: Polling request timed out.
(ServeController pid=18650) 2022-08-08 17:04:17,368	INFO (unknown file):0 -- Task failed with unretryable exception: TaskID(33415c28028d02adbf2f7875f2a6fbf7b2db89b101000000).
(ServeController pid=18650) Traceback (most recent call last):
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 709, in ray._raylet.execute_task
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 713, in ray._raylet.execute_task
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 655, in ray._raylet.execute_task.function_executor
(ServeController pid=18650)   File "python/ray/_raylet.pyx", line 2243, in ray._raylet.CoreWorker.run_async_func_in_event_loop
(ServeController pid=18650)   File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/concurrent/futures/_base.py", line 437, in result
(ServeController pid=18650)     return self.__get_result()
(ServeController pid=18650)   File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
(ServeController pid=18650)     raise self._exception
(ServeController pid=18650)   File "/Users/shrekris/Desktop/ray/python/ray/util/tracing/tracing_helper.py", line 498, in _resume_span
(ServeController pid=18650)     return await method(self, *_args, **_kwargs)
(ServeController pid=18650)   File "/Users/shrekris/Desktop/ray/python/ray/serve/controller.py", line 181, in listen_for_change
(ServeController pid=18650)     return await (self.long_poll_host.listen_for_change(keys_to_snapshot_ids))
(ServeController pid=18650)   File "/Users/shrekris/Desktop/ray/python/ray/serve/_private/long_poll.py", line 249, in listen_for_change
(ServeController pid=18650)     raise asyncio.TimeoutError("Polling request timed out.")
(ServeController pid=18650) asyncio.exceptions.TimeoutError: Polling request timed out.
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by simon-mo** [comment]
This is actually the implementation detail and intended.. I think something probably changed under the hood with Ray's async handling logic. Do you have the bandwidth to make a minor change here?

**Comment by simon-mo** [comment]
@sihanwang41 the correct fix is to have the LongPollHost return an object instead of throw exception, and identity it in LongPollClient. Basically change the protocol for timeout-repull signal.

**Comment by simon-mo** [comment]
Marking this blocker because this is a major UX breakage.

**Comment by simon-mo** [comment]
I verified this doesn't happen in 2.0.0.rc1. Since #27586 hasn't been merged yet. Removing the blocker label

**Comment by sihanwang41** [comment]
Hi @clarkzinzow,

is this intended new behavior we will loudly print out the exception traceback for task into the log?

**Comment by clarkzinzow** [comment]
This PR demotes the offending new log statement to debug-level, which should prevent this log spam.
