### ISSUE TITLE
[Serve] Passing function deployment into class deployment raises "missing positional argument"

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#27705]
### What happened + What you expected to happen

Running the reproduction script below raises the following exception:

```python-traceback
(ServeReplica:EchoCaller pid=94601) ERROR 2022-08-09 08:25:35,709 EchoCaller EchoCaller#lTDddI replica.py:438 - Request failed due to RayTaskError(TypeError):
(ServeReplica:EchoCaller pid=94601) Traceback (most recent call last):
(ServeReplica:EchoCaller pid=94601)   File "/Users/archit/ray/python/ray/serve/_private/replica.py", line 420, in invoke_single
(ServeReplica:EchoCaller pid=94601)     result = await method_to_call(*args, **kwargs)
(ServeReplica:EchoCaller pid=94601)   File "repro.py", line 14, in __call__
(ServeReplica:EchoCaller pid=94601)     return await(await(self.echo.remote(data)))
(ServeReplica:EchoCaller pid=94601) ray.exceptions.RayTaskError(TypeError): ray::ServeReplica:echo.handle_request() (pid=94600, ip=127.0.0.1)
(ServeReplica:EchoCaller pid=94601)   File "/Users/archit/ray/python/ray/serve/_private/utils.py", line 231, in wrap_to_ray_error
(ServeReplica:EchoCaller pid=94601)     raise exception
(ServeReplica:EchoCaller pid=94601)   File "/Users/archit/ray/python/ray/serve/_private/replica.py", line 420, in invoke_single
(ServeReplica:EchoCaller pid=94601)     result = await method_to_call(*args, **kwargs)
(ServeReplica:EchoCaller pid=94601) TypeError: echo() missing 1 required positional argument: 'text'
(ServeReplica:EchoCaller pid=94601) INFO 2022-08-09 08:25:35,710 EchoCaller EchoCaller#lTDddI replica.py:482 - HANDLE __call__ ERROR 17.2ms
(ServeReplica:echo pid=94600) ERROR 2022-08-09 08:25:35,707 echo echo#gVyXGD replica.py:438 - Request failed due to TypeError:
(ServeReplica:echo pid=94600) Traceback (most recent call last):
(ServeReplica:echo pid=94600)   File "/Users/archit/ray/python/ray/serve/_private/replica.py", line 420, in invoke_single
(ServeReplica:echo pid=94600)     result = await method_to_call(*args, **kwargs)
(ServeReplica:echo pid=94600)   File "/Users/archit/ray/python/ray/_private/async_compat.py", line 43, in wrapper
(ServeReplica:echo pid=94600)     return func(*args, **kwargs)
(ServeReplica:echo pid=94600) TypeError: echo() missing 1 required positional argument: 'text'
(ServeReplica:echo pid=94600) INFO 2022-08-09 08:25:35,708 echo echo#gVyXGD replica.py:482 - HANDLE __call__ ERROR 1.3ms
Traceback (most recent call last):
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "repro.py", line 21, in <module>
    print(resp.json())
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] Task Error. Traceback: ray::ServeReplica:EchoCaller.handle_request() (pid=94601, ip=127.0.0.1)
  File "/Users/archit/ray/python/ray/serve/_private/utils.py", line 231, in wrap_to_ray_error
    raise exception
  File "/Users/archit/ray/python/ray/serve/_private/replica.py", line 420, in invoke_single
    result = await method_to_call(*args, **kwargs)
  File "repro.py", line 14, in __call__
    return await(await(self.echo.remote(data)))
ray.exceptions.RayTaskError(TypeError): ray::ServeReplica:echo.handle_request() (pid=94600, ip=127.0.0.1)
  File "/Users/archit/ray/python/ray/serve/_private/utils.py", line 231, in wrap_to_ray_error
    raise exception
  File "/Users/archit/ray/python/ray/serve/_private/replica.py", line 420, in invoke_single
    result = await method_to_call(*args, **kwargs)
TypeError: echo() missing 1 required positional argument: 'text'.: 0
```

A workaround is to use a class instead of a function for the nested deployment.

### Versions / Dependencies

Mac, Ray master, Python 3.8

### Reproduction script

```python
from ray import serve
import requests

@serve.deployment
def echo(text: str):
    return text

@serve.deployment
class EchoCaller:
    def __init__(self, echo):
        self.echo = echo
    async def __call__(self, request):
        data = request.query_params['data']
        return await(await(self.echo.remote(data)))

echo_caller = EchoCaller.bind(echo.bind())

serve.run(echo_caller)

resp = requests.get("http://127.0.0.1:8000/", params={'data': "hello"})
print(resp.json())

```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by simon-mo** [comment]
I don't think this happens on Ray 2.0.
