### ISSUE TITLE
[2.0rc1][nightly] datasets_ingest_train_infer failed

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27753]
### What happened + What you expected to happen

https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_EahfUwhMBcazCpzBCKTaVjqk?command-history-section=command_history
```
2m[36m(RayTrainWorker pid=386, ip=10.0.0.52)[0m testing batch [4700] loss: 0.29770761728286743
[2m[36m(PipelineSplitExecutorCoordinator pid=472, ip=10.0.0.183)[0m   At least one of the input arguments for this task could not be computed:
[2m[36m(PipelineSplitExecutorCoordinator pid=472, ip=10.0.0.183)[0m ray.exceptions.ObjectFetchTimedOutError: Failed to retrieve object 2958e020efe49b86ffffffffffffffffffffffff0200000001000000. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.
[2m[36m(PipelineSplitExecutorCoordinator pid=472, ip=10.0.0.183)[0m 
[2m[36m(PipelineSplitExecutorCoordinator pid=472, ip=10.0.0.183)[0m Fetch for object 2958e020efe49b86ffffffffffffffffffffffff0200000001000000 timed out because no locations were found for the object. This may indicate a system-level bug.

[2m[36m(RayTrainWorker pid=386, ip=10.0.0.233)[0m testing batch [5200] loss: 0.28327280282974243
[2m[36m(RayTrainWorker pid=386, ip=10.0.0.233)[0m epoch [2]: testing accuracy: 2354047 / 2666733 = 0.8827
[2m[36m(RayTrainWorker pid=386, ip=10.0.0.118)[0m testing batch [5100] loss: 0.29731643199920654
[2m[36m(RayTrainWorker pid=386, ip=10.0.0.175)[0m testing batch [5200] loss: 0.3039114475250244
[2m[36m(RayTrainWorker pid=386, ip=10.0.0.175)[0m epoch [2]: testing accuracy: 2355850 / 2666733 = 0.8834
[2m[36m(RayTrainWorker pid=387, ip=10.0.0.38)[0m testing batch [5200] loss: 0.2724732458591461
[2m[36m(RayTrainWorker pid=387, ip=10.0.0.38)[0m epoch [2]: testing accuracy: 2356448 / 2666733 = 0.8836
[2m[36m(RayTrainWorker pid=386, ip=10.0.0.52)[0m testing batch [4800] loss: 0.25921034812927246
[2m[36m(RayTrainWorker pid=386, ip=10.0.0.118)[0m testing batch [5200] loss: 0.2819257378578186
[2m[36m(RayTrainWorker pid=386, ip=10.0.0.118)[0m epoch [2]: testing accuracy: 2355372 / 2666733 = 0.8832
[2m[36m(RayTrainWorker pid=386, ip=10.0.0.52)[0m testing batch [4900] loss: 0.27592548727989197
[2m[36m(RayTrainWorker pid=386, ip=10.0.0.52)[0m testing batch [5000] loss: 0.27820727229118347
[2m[36m(RayTrainWorker pid=386, ip=10.0.0.52)[0m testing batch [5100] loss: 0.28425872325897217
[2m[36m(RayTrainWorker pid=386, ip=10.0.0.52)[0m testing batch [5200] loss: 0.31723833084106445
[2m[36m(RayTrainWorker pid=386, ip=10.0.0.52)[0m epoch [2]: testing accuracy: 2355983 / 2666733 = 0.8835
[2m[1m[36m(scheduler +39m3s)[0m Resized to 1568 CPUs, 16 GPUs.
[2m[1m[36m(scheduler +42m47s)[0m Resized to 1600 CPUs, 16 GPUs.
Traceback (most recent call last):
  File "ray_sgd_training.py", line 608, in <module>
    train_func=train_func, config=config, callbacks=callbacks, dataset=datasets
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/train/trainer.py", line 360, in run
    for intermediate_result in iterator:
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/train/trainer.py", line 758, in __next__
    next_results = self._run_with_error_handling(self._fetch_next_result)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/train/trainer.py", line 722, in _run_with_error_handling
    return func()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/train/trainer.py", line 784, in _fetch_next_result
    results = self._backend_executor.get_next_results()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/train/_internal/utils.py", line 185, in <lambda>
    return lambda *args, **kwargs: ray.get(actor_method.remote(*args, **kwargs))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py", line 2245, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::BackendExecutor.get_next_results()[39m (pid=386, ip=10.0.0.183, repr=<ray.train._internal.backend_executor.BackendExecutor object at 0x7fcdf0ea2210>)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/train/_internal/backend_executor.py", line 396, in get_next_results
    "Some workers returned results while "
RuntimeError: Some workers returned results while others didn't. Make sure that `session.report()` (legacy API:`train.report()` and `train.save_checkpoint()`) are called the same number of times on all workers.
```
### Versions / Dependencies

releases/2.0.0rc1

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by scv119** [comment]
end up picked https://github.com/ray-project/ray/pull/27567 which should solve this problem
