### ISSUE TITLE
[Tune][Air] MLFlow Callback is incompatible with PB2

### ISSUE THREAD

**Issue by olipinski** [ray-project/ray#27783]
### What happened + What you expected to happen

Reporting MLFlow metrics is incompatible with Population-Based Training. As the PB2 changes parameters during runtime, when Tune tries to report that to MLFlow, it throws an error, as MLFlow does not allow the parameters to be changed.

```
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\repro\lib\site-packages\ray\tune\execution\trial_runner.py", line 819, in _wait_and_handle_event
    self._on_pg_ready(next_trial)
  File "C:\Users\user\Anaconda3\envs\repro\lib\site-packages\ray\tune\execution\trial_runner.py", line 909, in _on_pg_ready
    if not _start_trial(next_trial) and next_trial.status != Trial.ERROR:
  File "C:\Users\user\Anaconda3\envs\repro\lib\site-packages\ray\tune\execution\trial_runner.py", line 901, in _start_trial
    self._callbacks.on_trial_start(
  File "C:\Users\user\Anaconda3\envs\repro\lib\site-packages\ray\tune\callback.py", line 317, in on_trial_start
    callback.on_trial_start(**info)
  File "C:\Users\user\Anaconda3\envs\repro\lib\site-packages\ray\tune\logger\logger.py", line 135, in on_trial_start
    self.log_trial_start(trial)
  File "C:\Users\user\Anaconda3\envs\repro\lib\site-packages\ray\air\callbacks\mlflow.py", line 118, in log_trial_start
    self.mlflow_util.log_params(run_id=run_id, params_to_log=config)
  File "C:\Users\user\Anaconda3\envs\repro\lib\site-packages\ray\air\_internal\mlflow.py", line 280, in log_params
    client.log_param(run_id=run_id, key=key, value=value)
  File "C:\Users\user\Anaconda3\envs\repro\lib\site-packages\mlflow\tracking\client.py", line 743, in log_param
    self._tracking_client.log_param(run_id, key, value)
  File "C:\Users\user\Anaconda3\envs\repro\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 248, in log_param
    raise MlflowException(msg, INVALID_PARAMETER_VALUE)
mlflow.exceptions.MlflowException: Changing param values is not allowed. Param with key='rollout_fragment_length' was already logged with value='590' for run ID='3d0a25a70dcc4a6b9c96374e908b0ad8'. Attempted logging new value '4590'.
```

### Versions / Dependencies

Ray 3.0.0 
Python 3.9
Windows 10 Enterprise 20H2

### Reproduction script

```python
import os
import random
import tempfile
import uuid

from ray.air.callbacks.mlflow import MLflowLoggerCallback
from ray.tune import run, sample_from
from ray.tune.schedulers.pb2 import PB2

if __name__ == "__main__":

    pb2 = PB2(
        time_attr="timesteps_total",
        metric="episode_reward_mean",
        mode="max",
        perturbation_interval=50000,
        hyperparam_bounds={
            "lambda": [0.9, 1.0],
            "clip_param": [0.1, 0.5],
            "lr": [1e-3, 1e-5],
            "train_batch_size": [1000, 60000],
        },
    )

    analysis = run(
        "PPO",
        scheduler=pb2,
        verbose=1,
        num_samples=4,
        stop={"timesteps_total": 1000000},
        config={
            "framework": "torch",
            "env": "CartPole-v0",
            "log_level": "INFO",
            "seed": 0,
            "kl_coeff": 1.0,
            "num_gpus": 0,
            "horizon": 1600,
            "observation_filter": "MeanStdFilter",
            "model": {
                "free_log_std": True,
            },
            "num_sgd_iter": 10,
            "sgd_minibatch_size": 128,
            "lambda": sample_from(lambda spec: random.uniform(0.9, 1.0)),
            "clip_param": sample_from(lambda spec: random.uniform(0.1, 0.5)),
            "lr": sample_from(lambda spec: random.uniform(1e-3, 1e-5)),
            "train_batch_size": sample_from(lambda spec: random.randint(1000, 60000)),
        },
        callbacks=[
            MLflowLoggerCallback(
                experiment_name=str(uuid.uuid4()),
                tracking_uri=f'file:{os.path.join(tempfile.gettempdir(), "mlruns")}',
            )
        ],
    )

```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by richardliaw** [comment]
@olipinski thanks for the report! I believe the fix here is just to makes sure we don't call into MLflow again when on_trial_start is called a second time for the trial.

Would you be open to posting a pull request?

**Comment by olipinski** [comment]
@richardliaw That sounds good, though wouldn't it create an issue, where if we do that, the reported params at the end of all trials will be incorrect? Since they have been by PB2 updated since the first log to MLflow?

**Comment by xwjiang2010** [comment]
@olipinski Yeah I think you have a valid point. Although I don't currently have a good answer to that.

Also a quick search shows multiple people run into the same issue apparently: https://github.com/ray-project/ray/issues/20473

A side note.. wandb seems to allow this scenario quite nicely. They even have a blog showcasing that: https://wandb.ai/wandb/DistHyperOpt/reports/Modern-Scalable-Hyperparameter-Tuning-Methods--VmlldzoyMTQxODM

Not sure about your integration requirement (mlflow vs wandb) but do you want to give that a try?

I may have to look into what is the recommendation from mlflow for handing cases like this. This is more of a restriction from their API..

**Comment by olipinski** [comment]
@xwjiang2010 Oh, I have not seen the other issues. 

Thanks for the wandb tip, I'll have a look if it is possible to integrate with my code!

And yes, it does seem to be an mlflow restriction, which means that the most that we could do in ray is the workaround, even if it means the params logged are incorrect. At least that way, the metrics will still be fine.

**Comment by richardliaw** [comment]
@xwjiang2010 can we document this?

**Comment by alex-treebeard** [comment]
I don't think I'm using PB2 but have had this error occur using the default tune scheduler.

**Comment by xwjiang2010** [comment]
@alex-treebeard 
Could you share your script? Thanks!

@richardliaw yes, will add it.

**Comment by akzaidi** [comment]
hello! has there been any further discussion or progress on this issue? currently, the PBT scheduler doesn’t play nicely with the mlflow callback because hyperparameter values are changed during a trial and that raises an exception. Wondering if a possible solution may be to treat each perturbation as a new trial and log it separately? thanks!

**Comment by grizzlybearg** [comment]
> hello! has there been any further discussion or progress on this issue? currently, the PBT scheduler doesn’t play nicely with the mlflow callback because hyperparameter values are changed during a trial and that raises an exception. Wondering if a possible solution may be to treat each perturbation as a new trial and log it separately? thanks!

Any update on this?

**Comment by sjp611** [comment]
I also faced the same issue. To address this problem, I fixed MLflowLoggerCallback. Please check the pull request I created.
