### ISSUE TITLE
TypeError: can't pickle function objects

### ISSUE THREAD

**Issue by Alxe1** [ray-project/ray#27820]
### What happened + What you expected to happen

I copied the code from official guid, and it raised the error:
```
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    ray.init()
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/ray/worker.py", line 1105, in init
    job_config=job_config,
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/ray/worker.py", line 1646, in connect
    lambda worker_info: sys.path.insert(1, script_directory)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/ray/worker.py", line 404, in run_function_on_all_workers
    pickled_function = pickle.dumps(function)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 620, in dump
    return Pickler.dump(self, obj)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/ray/pickle5_files/pickle5/pickle.py", line 485, in dump
    self.save(obj)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/ray/pickle5_files/pickle5/pickle.py", line 601, in save
    self.save_reduce(obj=obj, *rv)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/ray/pickle5_files/pickle5/pickle.py", line 689, in save_reduce
    save(func)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/ray/pickle5_files/pickle5/pickle.py", line 601, in save
    self.save_reduce(obj=obj, *rv)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/ray/pickle5_files/pickle5/pickle.py", line 689, in save_reduce
    save(func)
  File "/mnt/softwares/hvd_env/lib/python3.6/site-packages/ray/pickle5_files/pickle5/pickle.py", line 576, in save
    rv = reduce(self.proto)
TypeError: can't pickle function objects
```

### Versions / Dependencies

version:
ray: 1.13.0
cloudpickle: 2.1.0

### Reproduction script

```

from ray import train
from ray.train import Trainer

import numpy as np


def train_func(config):
    import tensorflow as tf
    n = 100
    # create a toy dataset
    # data   : X - dim = (n, 4)
    # target : Y - dim = (n, 1)
    X = np.random.normal(0, 1, size=(n, 4))
    Y = np.random.uniform(0, 1, size=(n, 1))

    strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()
    with strategy.scope():
        # toy neural network : 1-layer
        model = tf.keras.Sequential([tf.keras.layers.Dense(1, activation="linear", input_shape=(4,))])
        model.compile(optimizer="Adam", loss="mean_squared_error", metrics=["mse"])

    for epoch in range(config["num_epochs"]):
        model.fit(X, Y, batch_size=20)
        train.save_checkpoint(epoch=epoch, model_weights=model.get_weights())


trainer = Trainer(backend="tensorflow", num_workers=2)
trainer.start()
trainer.run(train_func, config={"num_epochs": 5})
trainer.shutdown()
```

**Comment by jjyao** [comment]
HI @Alxe1,

I was not able to reproduce the same error. The script works for me. Did you install cloudpickle explicitly? Are you able to reproduce it with a fresh environment with only Ray and tensorflow installed?

**Comment by Alxe1** [comment]
> HI @Alxe1,
> 
> I was not able to reproduce the same error. The script works for me. Did you install cloudpickle explicitly? Are you able to reproduce it with a fresh environment with only Ray and tensorflow installed?

Yes, I create a new virtual env, and the version:
tensorflow              2.3.0
ray                          1.13.0
cloudpickle             2.1.0

Is it a reason that I didn't have a GPU?

**Comment by jjyao** [comment]
What's your python version? Mine is 3.6.13.

Could you try `pip uninstall pickle5` and `pip uninstall cloudpickle` to see if that works?

Also could you share your `pip freeze`?

**Comment by Alxe1** [comment]
> What's your python version? Mine is 3.6.13.
> 
> Could you try `pip uninstall pickle5` and `pip uninstall cloudpickle` to see if that works?
> 
> Also could you share your `pip freeze`?

My python version is 3.6.5, and I uninstalled pickle5 and cloudpickle, it still has the error.
The packages:
```
absl-py==1.2.0
aiosignal==1.2.0
astunparse==1.6.3
attrs==22.1.0
cachetools==4.2.4
certifi==2022.6.15
charset-normalizer==2.0.12
click==8.0.4
dataclasses==0.8
distlib==0.3.5
filelock==3.4.1
frozenlist==1.2.0
gast==0.3.3
google-auth==2.10.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.43.0
h5py==2.10.0
idna==3.3
importlib-metadata==4.8.3
importlib-resources==5.4.0
jsonschema==3.2.0
Keras-Preprocessing==1.1.2
Markdown==3.3.7
msgpack==1.0.4
numpy==1.18.5
oauthlib==3.2.0
opt-einsum==3.3.0
pandas==1.1.5
platformdirs==2.4.0
protobuf==3.19.4
pyarrow==6.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyrsistent==0.18.0
python-dateutil==2.8.2
pytz==2022.2.1
PyYAML==6.0
ray==1.13.0
requests==2.27.1
requests-oauthlib==1.3.1
rsa==4.9
scipy==1.4.1
six==1.16.0
tensorboard==2.10.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.3.0
tensorflow-estimator==2.3.0
termcolor==1.1.0
typing_extensions==4.1.1
urllib3==1.26.11
virtualenv==20.16.3
Werkzeug==2.0.3
wrapt==1.14.1
zipp==3.6.0
```

**Comment by jjyao** [comment]
I can reproduce it with 3.6.5. Could you try to upgrade to 3.6.13  or even 3.7+ since 3.6 is EOLed which doesn't have this issue?

**Comment by Alxe1** [comment]
> I can reproduce it with 3.6.5. Could you try to upgrade to 3.6.13 or even 3.7+ since 3.6 is EOLed which doesn't have this issue?

Yes, I  upgrade python to 3.7.10, it works.
