### ISSUE TITLE
AttributeError: 'Worker' object has no attribute 'redis_client'

### ISSUE THREAD

**Issue by alexander-ossur** [ray-project/ray#2787]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: pip install ray
- **Ray version**: 0.5.2
- **Python version**: Python 3.6.5 :: Anaconda, Inc.
- **Exact command to reproduce**:

### Describe the problem
I just wanted to debug Environment and Model, as debugger will not "jump" into workers code. Not sure if "local_mode" is exactly for that

#### test.py
```
import ray
import ray.rllib.agents.ppo as ppo
from ray.tune.logger import pretty_print

ray.init (num_gpus=1, local_mode = True)
config = ppo.DEFAULT_CONFIG.copy()

agent = ppo.PPOAgent(config=config, env="CartPole-v0")

for i in range(1000):
   # Perform one iteration of training the policy with PPO
   result = agent.train()
   print(pretty_print(result))

   if i % 100 == 0:
       checkpoint = agent.save()
       print("checkpoint saved at", checkpoint)
```

> Traceback (most recent call last):  File "/home/aleksandr/Workspace/trad/tensorflow-test/test.py", line 5, in <module>
>     ray.init (num_gpus=1, local_mode = True)
>   File "/home/aleksandr/anaconda3/envs/ml-agents/lib/python3.6/site-packages/ray/worker.py", line 1853, in init
>     hook()
>   File "/home/aleksandr/anaconda3/envs/ml-agents/lib/python3.6/site-packages/ray/tune/registry.py", line 101, in flush_values
>     _internal_kv_put(_make_key(category, key), value, overwrite=True)
>   File "/home/aleksandr/anaconda3/envs/ml-agents/lib/python3.6/site-packages/ray/experimental/internal_kv.py", line 31, in _internal_kv_put
>     updated = worker.redis_client.hset(key, "value", value)
> AttributeError: 'Worker' object has no attribute 'redis_client'
> Terminated

**Comment by robertnishihara** [comment]
Thanks @alexander-ossur `local_mode` support currently isn't very complete and also RLlib directly uses the redis client in some places. I think it'd be really useful if we can make it so that RLlib can be run in `local_mode`.

**Comment by ericl** [comment]
Made a quick PR. Unfortunately Tune also doesn't support local mode, but we should also add that in the future (it's also unclear what the behavior of local Tune should be w.r.t. resource scheduling).
