### ISSUE TITLE
[Serve] 'SERVE_CONTROLLER_ACTOR' already exists in the namespace serve

### ISSUE THREAD

**Issue by Joshuaalbert** [ray-project/ray#27877]
### What happened + What you expected to happen

I am deploying a serve application. **Sometimes** I get this namespace clash, but not all the time. When it happens the ingress point does not launch. The deployment is always fresh using docker, so there is no preexisting ray instance running (so there shouldn't be something taking this namespace). This smells like a race condition.

This is not good because then the deployment mechanism has to detect if this one part of the deployment failed and then tear whatever else is up, and relaunch if so. 

```bash
Traceback (most recent call last):
  File "/home/albert/git/reclone/THA-Oracle/bin/../deployments/oracle_face/main.py", line 16, in <module>
    serve.start(detached=True, http_options={"host": host, "port": port})
  File "/home/albert/miniconda3/envs/tha_py/lib/python3.10/site-packages/ray/serve/api.py", line 155, in start
    controller = ServeController.options(
  File "/home/albert/miniconda3/envs/tha_py/lib/python3.10/site-packages/ray/actor.py", line 561, in remote
    return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/home/albert/miniconda3/envs/tha_py/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 383, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/home/albert/miniconda3/envs/tha_py/lib/python3.10/site-packages/ray/actor.py", line 888, in _remote
    actor_id = worker.core_worker.create_actor(
  File "python/ray/_raylet.pyx", line 1591, in ray._raylet.CoreWorker.create_actor
  File "python/ray/_raylet.pyx", line 1634, in ray._raylet.CoreWorker.create_actor
  File "python/ray/_raylet.pyx", line 173, in ray._raylet.check_status
ValueError: Actor with name 'SERVE_CONTROLLER_ACTOR' already exists in the namespace serve
```

### Versions / Dependencies

python 3.10
ray 1.13.0

### Reproduction script

This is nothing special. A docker file with entrypoint launching an app.
Put this in a Dockerfile,
```
FROM python:3.10

# install a package including Ray

ENTRYPOINT [ "/bin/bash", "/deployments/scripts/entrypoint.sh" ]
```

`entrypoint.sh` contains this,

```
ray start --head --port=6379 --redis-shard-ports=6380,6381 --object-manager-port=22345 --node-manager-port=22346 --dashboard-host=0.0.0.0
python /deployments/app/main.py
```

`main.py` contains
```python
# import some stuff

ray.init(address='auto')
serve.start(detached=True, http_options={"host": host, "port": port})
App.deploy()
```

Launch with docker.

### Issue Severity

High: It blocks me from completing my task.

**Comment by Joshuaalbert** [comment]
Could this be caused by starting a ray head immediately after calling `ray stop --force`? It seems to go away when `docker-compose  up --remove-orphans` is used.

**Comment by architkulkarni** [comment]
Oh, that sounds reasonable... Still, I would expect all Ray processes to be completely stopped after `ray stop --force` returns, so this still seems like a bug.

**Comment by simon-mo** [comment]
It should not be the case in Ray 2.0. Please feel free to re-open.
