### ISSUE TITLE
[Datasets/Core] worker died after the test succeeded in pipelined_data_ingest_benchmark test

### ISSUE THREAD

**Issue by jianoaix** [ray-project/ray#27874]
This nightly test has been succeeding: https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_91Vauj2sHzU9RLhtwRBCaTSw

However the worker died with the following:
```
2022-08-14 15:54:49,512 WARNING worker.py:1799 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 55b887dcf596f05ad5a30b597c58b96a5a36014a02000000 Worker ID: 13f182e1980b510efb4f1409eaad48d9a7029d425ad11e823aee9a72 Node ID: 17f986ae93b2122695f8e9118f5298136f9ca32ae9926511faceed28 Worker IP address: 172.31.77.228 Worker port: 10003 Worker PID: 257 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
(_map_block_nosplit pid=259, ip=172.31.79.127) 2022-08-14 15:54:49,476  ERROR worker.py:754 -- Worker exits with an exit code 1.
(_map_block_nosplit pid=259, ip=172.31.79.127) Traceback (most recent call last):
(_map_block_nosplit pid=259, ip=172.31.79.127)   File "python/ray/_raylet.pyx", line 864, in ray._raylet.task_execution_handler
(_map_block_nosplit pid=259, ip=172.31.79.127)   File "python/ray/_raylet.pyx", line 662, in ray._raylet.execute_task
(_map_block_nosplit pid=259, ip=172.31.79.127)   File "python/ray/_raylet.pyx", line 702, in ray._raylet.execute_task
(_map_block_nosplit pid=259, ip=172.31.79.127)   File "python/ray/_raylet.pyx", line 709, in ray._raylet.execute_task
(_map_block_nosplit pid=259, ip=172.31.79.127)   File "python/ray/_raylet.pyx", line 713, in ray._raylet.execute_task
(_map_block_nosplit pid=259, ip=172.31.79.127)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/compute.py", line 449, in _map_block_nosplit
(_map_block_nosplit pid=259, ip=172.31.79.127)     for new_block in block_fn(block, *fn_args, **fn_kwargs):
(_map_block_nosplit pid=259, ip=172.31.79.127)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/plan.py", line 633, in block_fn
(_map_block_nosplit pid=259, ip=172.31.79.127)     for tmp1 in block_fn1(block, *prev_fn_args, **prev_fn_kwargs):
(_map_block_nosplit pid=259, ip=172.31.79.127)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/plan.py", line 815, in block_fn
(_map_block_nosplit pid=259, ip=172.31.79.127)     for block in read_fn():
(_map_block_nosplit pid=259, ip=172.31.79.127)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/datasource/datasource.py", line 303, in <lambda>
(_map_block_nosplit pid=259, ip=172.31.79.127)     ReadTask(lambda i=i, count=count: [make_block(i, count)], meta)
(_map_block_nosplit pid=259, ip=172.31.79.127)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/datasource/datasource.py", line 265, in make_block
(_map_block_nosplit pid=259, ip=172.31.79.127)     tuple(range(1, 1 + len(tensor_shape))),
(_map_block_nosplit pid=259, ip=172.31.79.127)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py", line 751, in sigterm_handler
(_map_block_nosplit pid=259, ip=172.31.79.127)     sys.exit(1)
(_map_block_nosplit pid=259, ip=172.31.79.127) SystemExit: 1
```

cc @jjyao

**Comment by jjyao** [comment]
The reason is that the pipeline is infinite in the test and you only read first 2 epochs, which means when the script exits, there is some task running for the next window and it will be killed.

**Comment by jianoaix** [comment]
Downgrade to P2 since DatasetPipeline will be deprecated going forward.
