### ISSUE TITLE
[Collective] the demo is not working

### ISSUE THREAD

**Issue by supersglzc** [ray-project/ray#27923]
### What happened + What you expected to happen
```
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    results = ray.get([w.compute.remote() for w in workers])
  File "/scratch/steven/miniconda3/envs/rlgpu/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/scratch/steven/miniconda3/envs/rlgpu/lib/python3.7/site-packages/ray/worker.py", line 1831, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(NcclError): ray::Worker.compute() (pid=2574988, ip=128.30.27.119, repr=<test.Worker object at 0x7fb6ec8eb490>)
  File "test.py", line 18, in compute
    collective.allreduce(self.send, "default")
  File "/scratch/steven/miniconda3/envs/rlgpu/lib/python3.7/site-packages/ray/util/collective/collective.py", line 272, in allreduce
    g.allreduce([tensor], opts)
  File "/scratch/steven/miniconda3/envs/rlgpu/lib/python3.7/site-packages/ray/util/collective/collective_group/nccl_collective_group.py", line 197, in allreduce
    self._collective(tensors, tensors, collective_fn)
  File "/scratch/steven/miniconda3/envs/rlgpu/lib/python3.7/site-packages/ray/util/collective/collective_group/nccl_collective_group.py", line 604, in _collective
    comms = self._get_nccl_collective_communicator(key, devices)
  File "/scratch/steven/miniconda3/envs/rlgpu/lib/python3.7/site-packages/ray/util/collective/collective_group/nccl_collective_group.py", line 451, in _get_nccl_collective_communicator
    nccl_util.groupEnd()
  File "cupy_backends/cuda/libs/nccl.pyx", line 210, in cupy_backends.cuda.libs.nccl.groupEnd
  File "cupy_backends/cuda/libs/nccl.pyx", line 243, in cupy_backends.cuda.libs.nccl.groupEnd
  File "cupy_backends/cuda/libs/nccl.pyx", line 129, in cupy_backends.cuda.libs.nccl.check_status
cupy_backends.cuda.libs.nccl.NcclError: NCCL_ERROR_INVALID_USAGE: invalid usage`

I try to run the first example in the [documentation](https://docs.ray.io/en/latest/ray-more-libs/ray-collective.html#collective-primitives-support-matrix), however, it gives the above error. 

### Versions / Dependencies

ray 1.13.0
cupy-cuda111 11.0.0
cudatoolkit 11.1.1


### Reproduction script

import ray
import ray.util.collective as collective

import cupy as cp


@ray.remote(num_gpus=0.3)
class Worker:
   def __init__(self):
       self.send = cp.ones((4, ), dtype=cp.float32)
       self.recv = cp.zeros((4, ), dtype=cp.float32)

   def setup(self, world_size, rank):
       collective.init_collective_group(world_size, rank, "nccl", "default")
       return True

   def compute(self):
       collective.allreduce(self.send, "default")
       return self.send

   def destroy(self):
       collective.destroy_group()

# imperative
num_workers = 2
workers = []
init_rets = []
for i in range(num_workers):
   w = Worker.remote()
   workers.append(w)
   init_rets.append(w.setup.remote(num_workers, i))
_ = ray.get(init_rets)
results = ray.get([w.compute.remote() for w in workers])
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by richardliaw** [comment]
@zhisbug can you take a look?
