### ISSUE TITLE
[Dashboard] Failure to build for `node>=v17`

### ISSUE THREAD

**Issue by peytondmurray** [ray-project/ray#28023]
### What happened + What you expected to happen

The Ray dashboard fails to build with newer versions of Ray - `v16.17.0` is the version I'm currently using to successfully build the dashboard, but I've tried with later versions without success. Here's the error:

```
yarn run v1.22.19
$ react-scripts build
Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/pdmurray/Desktop/workspace/ray/dashboard/client/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.4.0
```

It seems like this is an issue with webpack, and it might only be a matter of upgrading `react-scripts` - see https://github.com/facebook/create-react-app/issues/11708.

### Versions / Dependencies

| Dependency | Version |
| --- | --- |
| Ray | `master` |
| node | `>16.17.0` |

### Reproduction script

1. Install `node@v18.7.0`
2. `cd ray/dashboard/client`
3. `yarn && yarn build`

### Issue Severity

Low: It annoys or frustrates me.

**Comment by alanwguo** [comment]
We've actually upgraded react-scripts since august so this may be fixed. I'll verify before closing
