### ISSUE TITLE
[air/train] Running huggingface trainer causes No module named 'datasets_modules' error

### ISSUE THREAD

**Issue by atinsood** [ray-project/ray#28084]
### What happened + What you expected to happen

As mentioned in the discussion here https://ray-distributed.slack.com/archives/CNECXMW22/p1661127032259049 , we ran into `No module named 'datasets_modules' ` error when running a pretty basic example of HF trainer. the example code is provided below for reproducing the error.

As mentioned in the discussion the error seems pretty similar to https://github.com/huggingface/datasets/issues/2318

also in the slack discussion the below workaround was provided that works well https://ray-distributed.slack.com/archives/CNECXMW22/p1661205441782679?thread_ts=1661127079.538249&cid=CNECXMW22

As a workaround, can you try putting the load_metric inside the compute_metrics function? That works fine for me. Let me know how that goes! 

```
    def compute_metrics(eval_pred):
        metric = load_metric("accuracy")
        logits, labels = eval_pred
        predictions = np.argmax(logits, axis=-1)
        return metric.compute(predictions=predictions, references=labels)
```

Below is the complete stack trace

```
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 658, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 699, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 665, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 669, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 616, in ray._raylet.execute_task.function_executor
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/function_manager.py", line 675, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/function_manager.py", line 589, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name TrainTrainable failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/function_manager.py", line 628, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'datasets_modules'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 799, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 618, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 740, in ray._raylet.execute_task
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/function_manager.py", line 589, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name TrainTrainable failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/function_manager.py", line 628, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'datasets_modules'

An unexpected internal error occurred while the worker was executing a task.
(TemporaryActor pid=318, ip=10.130.7.113) 2022-08-21 13:20:50,907	ERROR worker.py:451 -- SystemExit was raised from the worker. The worker may have exceeded K8s pod memory limits.
(TemporaryActor pid=318, ip=10.130.7.113) Traceback (most recent call last):
(TemporaryActor pid=318, ip=10.130.7.113)   File "python/ray/_raylet.pyx", line 658, in ray._raylet.execute_task
(TemporaryActor pid=318, ip=10.130.7.113)   File "python/ray/_raylet.pyx", line 699, in ray._raylet.execute_task
(TemporaryActor pid=318, ip=10.130.7.113)   File "python/ray/_raylet.pyx", line 665, in ray._raylet.execute_task
(TemporaryActor pid=318, ip=10.130.7.113)   File "python/ray/_raylet.pyx", line 669, in ray._raylet.execute_task
(TemporaryActor pid=318, ip=10.130.7.113)   File "python/ray/_raylet.pyx", line 616, in ray._raylet.execute_task.function_executor
(TemporaryActor pid=318, ip=10.130.7.113)   File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/function_manager.py", line 675, in actor_method_executor
(TemporaryActor pid=318, ip=10.130.7.113)     return method(__ray_actor, *args, **kwargs)
(TemporaryActor pid=318, ip=10.130.7.113)   File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/function_manager.py", line 589, in temporary_actor_method
(TemporaryActor pid=318, ip=10.130.7.113)     raise RuntimeError(
(TemporaryActor pid=318, ip=10.130.7.113) RuntimeError: The actor with name TrainTrainable failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:
(TemporaryActor pid=318, ip=10.130.7.113) 
(TemporaryActor pid=318, ip=10.130.7.113) Traceback (most recent call last):
(TemporaryActor pid=318, ip=10.130.7.113)   File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/function_manager.py", line 628, in _load_actor_class_from_gcs
(TemporaryActor pid=318, ip=10.130.7.113)     actor_class = pickle.loads(pickled_class)
(TemporaryActor pid=318, ip=10.130.7.113) ModuleNotFoundError: No module named 'datasets_modules'
(TemporaryActor pid=318, ip=10.130.7.113) 
(TemporaryActor pid=318, ip=10.130.7.113) 
(TemporaryActor pid=318, ip=10.130.7.113) During handling of the above exception, another exception occurred:
(TemporaryActor pid=318, ip=10.130.7.113) 
(TemporaryActor pid=318, ip=10.130.7.113) Traceback (most recent call last):
(TemporaryActor pid=318, ip=10.130.7.113)   File "python/ray/_raylet.pyx", line 799, in ray._raylet.task_execution_handler
(TemporaryActor pid=318, ip=10.130.7.113)   File "python/ray/_raylet.pyx", line 618, in ray._raylet.execute_task
(TemporaryActor pid=318, ip=10.130.7.113)   File "python/ray/_raylet.pyx", line 740, in ray._raylet.execute_task
(TemporaryActor pid=318, ip=10.130.7.113)   File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/function_manager.py", line 589, in temporary_actor_method
(TemporaryActor pid=318, ip=10.130.7.113)     raise RuntimeError(
(TemporaryActor pid=318, ip=10.130.7.113) RuntimeError: The actor with name TrainTrainable failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:
(TemporaryActor pid=318, ip=10.130.7.113) 
(TemporaryActor pid=318, ip=10.130.7.113) Traceback (most recent call last):
(TemporaryActor pid=318, ip=10.130.7.113)   File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/function_manager.py", line 628, in _load_actor_class_from_gcs
(TemporaryActor pid=318, ip=10.130.7.113)     actor_class = pickle.loads(pickled_class)
(TemporaryActor pid=318, ip=10.130.7.113) ModuleNotFoundError: No module named 'datasets_modules'
(TemporaryActor pid=318, ip=10.130.7.113) 
(TemporaryActor pid=318, ip=10.130.7.113) 
(TemporaryActor pid=318, ip=10.130.7.113) During handling of the above exception, another exception occurred:
(TemporaryActor pid=318, ip=10.130.7.113) 
(TemporaryActor pid=318, ip=10.130.7.113) Traceback (most recent call last):
(TemporaryActor pid=318, ip=10.130.7.113)   File "python/ray/_raylet.pyx", line 828, in ray._raylet.task_execution_handler
(TemporaryActor pid=318, ip=10.130.7.113) SystemExit
A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff49e62651a96bdbe429b82d1d01000000 Worker ID: b1fea738b47cc9a61519b20368544c38a066fe4ee4ebd691a0f59d13 Node ID: 21b18abf99b9ee0dfe761160e5c5ef211c0e2433b32377c1f344098c Worker IP address: 10.130.7.113 Worker port: 10004 Worker PID: 318
(train_fn pid=610) == Status ==
(train_fn pid=610) Current time: 2022-08-21 13:20:51 (running for 00:00:03.39)
(train_fn pid=610) Memory usage on this node: 15.6/377.4 GiB
(train_fn pid=610) Using FIFO scheduling algorithm.
(train_fn pid=610) Resources requested: 2.0/20 CPUs, 1.0/2 GPUs, 0.0/14.0 GiB heap, 0.0/11.68 GiB objects
(train_fn pid=610) Result logdir: /home/ray/ray_results/HuggingFaceTrainer_2022-08-21_13-20-47
(train_fn pid=610) Number of trials: 1/1 (1 RUNNING)
(train_fn pid=610) +--------------------------------+----------+-------+
(train_fn pid=610) | Trial name                     | status   | loc   |
(train_fn pid=610) |--------------------------------+----------+-------|
(train_fn pid=610) | HuggingFaceTrainer_be207_00000 | RUNNING  |       |
(train_fn pid=610) +--------------------------------+----------+-------+
(train_fn pid=610) 
(train_fn pid=610) 
(train_fn pid=610) Result for HuggingFaceTrainer_be207_00000:
(train_fn pid=610)   trial_id: be207_00000
(train_fn pid=610)   
(train_fn pid=610) == Status ==
(train_fn pid=610) Current time: 2022-08-21 13:20:51 (running for 00:00:03.40)
(train_fn pid=610) Memory usage on this node: 15.6/377.4 GiB
(train_fn pid=610) Using FIFO scheduling algorithm.
(train_fn pid=610) Resources requested: 0/20 CPUs, 0/2 GPUs, 0.0/14.0 GiB heap, 0.0/11.68 GiB objects
(train_fn pid=610) Result logdir: /home/ray/ray_results/HuggingFaceTrainer_2022-08-21_13-20-47
(train_fn pid=610) Number of trials: 1/1 (1 ERROR)
(train_fn pid=610) +--------------------------------+----------+-------+
(train_fn pid=610) | Trial name                     | status   | loc   |
(train_fn pid=610) |--------------------------------+----------+-------|
(train_fn pid=610) | HuggingFaceTrainer_be207_00000 | ERROR    |       |
(train_fn pid=610) +--------------------------------+----------+-------+
(train_fn pid=610) Number of errored trials: 1
(train_fn pid=610) +--------------------------------+--------------+-----------------------------------------------------------------------------------------------------------------------------+
(train_fn pid=610) | Trial name                     |   # failures | error file                                                                                                                  |
(train_fn pid=610) |--------------------------------+--------------+-----------------------------------------------------------------------------------------------------------------------------|
(train_fn pid=610) | HuggingFaceTrainer_be207_00000 |            1 | /home/ray/ray_results/HuggingFaceTrainer_2022-08-21_13-20-47/HuggingFaceTrainer_be207_00000_0_2022-08-21_13-20-47/error.txt |
(train_fn pid=610) +--------------------------------+--------------+-----------------------------------------------------------------------------------------------------------------------------+
(train_fn pid=610) 
(train_fn pid=610) 2022-08-21 13:20:51,136	ERROR trial_runner.py:886 -- Trial HuggingFaceTrainer_be207_00000: Error processing event.
(train_fn pid=610) NoneType: None
```

### Versions / Dependencies

ray 1.13.0
transformers 4.21.0

### Reproduction script

You can reproduce the error by running this example code. the code should result in the exception trace mentioned above

```@ray.remote
def train_fn():
    from datasets import load_dataset
    import transformers
    from transformers import AutoTokenizer, TrainingArguments
    from transformers import AutoModelForSequenceClassification
    import numpy as np
    from datasets import load_metric
    import ray
    from ray import tune
    from ray.ml.train.integrations.huggingface import HuggingFaceTrainer

    dataset = load_dataset("yelp_review_full")
    tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

    def tokenize_function(examples):
        return tokenizer(examples["text"], padding="max_length", truncation=True)

    tokenized_datasets = dataset.map(tokenize_function, batched=True)
    ray_train_ds = ray.data.from_huggingface(tokenized_datasets["train"])
    ray_evaluation_ds = ray.data.from_huggingface(tokenized_datasets["test"])

    metric = load_metric("accuracy")

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        predictions = np.argmax(logits, axis=-1)
        return metric.compute(predictions=predictions, references=labels)

    def trainer_init_per_worker(train_dataset, eval_dataset, **config):
        from datasets import load_dataset
        dataset = load_dataset("yelp_review_full")
        model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=5)
        
        #args = transformers.TrainingArguments(output_dir="test_trainer", evaluation_strategy="epoch")
        training_args = TrainingArguments("test", evaluate_during_training=True, eval_steps=500, disable_tqdm=True, skip_memory_metrics=True)

        return transformers.Trainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
            eval_dataset=eval_dataset,
            compute_metrics=compute_metrics
        )

    scaling_config = {"num_workers": 1, "use_gpu": True} #num workers is the number of gpus
    trainer = HuggingFaceTrainer(
        trainer_init_per_worker=trainer_init_per_worker,
        scaling_config=scaling_config,
        datasets={"train": ray_train_ds, "evaluation": ray_evaluation_ds},
    )
    result = trainer.fit()```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by krfricke** [comment]
Hi @atinsood, can you upgrade to Ray 2.0.0 or latest master and run this again?

I'm running it right now locally and can't reproduce the error.

The (slightly altered to match newest API) code I'm running is:

```
from ray.air import ScalingConfig


def train_fn():
    from datasets import load_dataset
    import transformers
    from transformers import AutoTokenizer, TrainingArguments
    from transformers import AutoModelForSequenceClassification
    import numpy as np
    from datasets import load_metric
    import ray
    from ray.train.huggingface import HuggingFaceTrainer

    dataset = load_dataset("yelp_review_full")
    tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

    def tokenize_function(examples):
        return tokenizer(examples["text"], padding="max_length",
                         truncation=True)

    tokenized_datasets = dataset.map(tokenize_function, batched=True)
    ray_train_ds = ray.data.from_huggingface(tokenized_datasets["train"])
    ray_evaluation_ds = ray.data.from_huggingface(tokenized_datasets["test"])

    metric = load_metric("accuracy")

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        predictions = np.argmax(logits, axis=-1)
        return metric.compute(predictions=predictions, references=labels)

    def trainer_init_per_worker(train_dataset, eval_dataset, **config):
        from datasets import load_dataset
        dataset = load_dataset("yelp_review_full")
        model = AutoModelForSequenceClassification.from_pretrained(
            "bert-base-cased", num_labels=5)

        # args = transformers.TrainingArguments(output_dir="test_trainer", evaluation_strategy="epoch")
        training_args = TrainingArguments("test", do_eval=True,
                                          eval_steps=500, disable_tqdm=True,
                                          skip_memory_metrics=True)

        return transformers.Trainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
            eval_dataset=eval_dataset,
            compute_metrics=compute_metrics
        )

    scaling_config = ScalingConfig(**{"num_workers": 1,
                      "use_gpu": True})  # num workers is the number of gpus
    trainer = HuggingFaceTrainer(
        trainer_init_per_worker=trainer_init_per_worker,
        scaling_config=scaling_config,
        datasets={"train": ray_train_ds, "evaluation": ray_evaluation_ds},
    )
    result = trainer.fit()


train_fn()
```

**Comment by krfricke** [comment]
Actually, after running for a bit longer, I can reproduce this after all:

```
2022-08-31 15:22:23,743	ERROR ray_trial_executor.py:104 -- An exception occurred when trying to stop the Ray actor:Traceback (most recent call last):
  File "/Users/kai/coding/ray/python/ray/tune/execution/ray_trial_executor.py", line 94, in _post_stop_cleanup
    ray.get(future, timeout=0)
  File "/Users/kai/coding/ray/python/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/kai/coding/ray/python/ray/_private/worker.py", line 2281, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: BaseTrainer.as_trainable.<locals>.TrainTrainable
	actor_id: 7736a2841bf8ed08ee3cd31c01000000
	pid: 33807
	namespace: 0f5cddcb-d697-4878-8b25-fbd91632627b
	ip: 127.0.0.1
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 702, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 755, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 709, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 713, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 660, in ray._raylet.execute_task.function_executor
  File "/Users/kai/coding/ray/python/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/kai/coding/ray/python/ray/_private/function_manager.py", line 587, in temporary_actor_method
    f"The actor with name {actor_class_name} "
RuntimeError: The actor with name TrainTrainable failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/kai/coding/ray/python/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'datasets_modules'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 864, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 662, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 801, in ray._raylet.execute_task
  File "/Users/kai/coding/ray/python/ray/_private/function_manager.py", line 587, in temporary_actor_method
    f"The actor with name {actor_class_name} "
RuntimeError: The actor with name TrainTrainable failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/kai/coding/ray/python/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'datasets_modules'
```

Looking into it... also cc @Yard1

**Comment by krfricke** [comment]
@Yard1 presumably we need to do something similar to this: https://sourcegraph.com/github.com/huggingface/transformers/-/blob/src/transformers/integrations.py?L271

**Comment by Yard1** [comment]
The workaround for now is to load datasets/metrics inside the `trainer_init_per_worker` function, as is done in examples.

@krfricke I'll get on that!
