### ISSUE TITLE
RuntimeError: Starting Ray client server failed

### ISSUE THREAD

**Issue by daipayandeb-brt** [ray-project/ray#28091]
### What happened + What you expected to happen

Hitting this error everytime and unable to setup runtime environment.  This is blocking me to run any job in any automated way. (The script is already shared with Uday)

My mac is running 
% python3 --version
Python 3.8.9
% ray --version    
ray, version 1.9.2
% anyscale --version
Authenticating
Loaded Anyscale authentication token from ~/.anyscale/credentials.json.

(anyscale +1.1s) 0.5.16

% python3 main_final_uk2.py
Authenticating
Loaded Anyscale authentication token from ~/.anyscale/credentials.json.

Parsing Ray Client arguments
Finished parsing arguments.

Choosing a project
Using the project jupiter-test-1:
  name:               jupiter-test-1
  project id:         prj_QeM3AFNJ8AuCrZtGemawzsfe

Preparing the cluster
Cluster charles_test_2 exists but not running. This cluster will be restarted.
Restarting cluster charles_test_2:
  cluster id:                   ses_MA2fG8YS1vbXhurAG1bsBTZc
  cluster environment:          apt_FvL544qpg3pB1Vf6EbnEQ32D:1
  cluster environment id:       bld_ukguqNBLbYeJa2zaiwUgWJ6X
  cluster compute:              jupiter_setup
  cluster compute id:           cpt_qzNf8NH43AQqwmFz21cXbwcU
  link:                         https://console.anyscale.com/projects/prj_QeM3AFNJ8AuCrZtGemawzsfe/clusters/ses_MA2fG8YS1vbXhurAG1bsBTZc
Waiting for cluster charles_test_2 to start. This may take a few minutes
                                                                                                                                           
Starting the interactive session
Uploading `working_dir: s3://blueriver-jupiter-data/experimental/deb/temp/working_dir.zip` and installing pip packages in the cluster ...
Connection Failed! Attempting to get Debug Information!
Traceback (most recent call last):
  File "main_final_uk2.py", line 83, in <module>
    ray.init("anyscale://jupiter-test-1/charles_test_2",
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ray/worker.py", line 775, in init
    return builder.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/anyscale/connect.py", line 848, in connect
    self._interactive_session_block = start_interactive_session_block(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/anyscale/connect_utils/start_interactive_session.py", line 425, in start_interactive_session_block
    return StartInteractiveSessionBlock(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/anyscale/connect_utils/start_interactive_session.py", line 88, in __init__
    self.connection_info = self._acquire_session_lock(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/anyscale/connect_utils/start_interactive_session.py", line 317, in _acquire_session_lock
    raise connection_exception
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/anyscale/connect_utils/start_interactive_session.py", line 275, in _acquire_session_lock
    info = self._ray.util.connect(session_url, **connect_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ray/util/client_connect.py", line 33, in connect
    conn = ray.connect(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ray/util/client/__init__.py", line 228, in connect
    conn = self.get_context().connect(*args, **kw_args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ray/util/client/__init__.py", line 88, in connect
    self.client_worker._server_init(job_config, ray_init_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ray/util/client/worker.py", line 697, in _server_init
    raise ConnectionAbortedError(
ConnectionAbortedError: Initialization failure from server:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/util/client/server/proxier.py", line 628, in Datapath
    raise RuntimeError(
RuntimeError: Starting Ray client server failed. See ray_client_server_23001.err for detailed log

### Versions / Dependencies

My mac is running 
% python3 --version
Python 3.8.9
% ray --version    
ray, version 1.9.2
% anyscale --version
Authenticating
Loaded Anyscale authentication token from ~/.anyscale/credentials.json.

(anyscale +1.1s) 0.5.16

### Reproduction script

Just run python3 main_final.py script shared with Uday

### Issue Severity

High: It blocks me from completing my task.

**Comment by udayk13** [comment]
@daipayandeb-brt  can we close this ticket? I think we got past this issue long time back.

**Comment by hora-anyscale** [comment]
Closing per conversation - this was addressed.
