### ISSUE TITLE
[tune] Population based training crashes (regression)

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#2810]
### Describe the problem

The problem can be reproduced by running pbt_example.py. This wasn't caught by tests since the number of iterations was too low to hit the bug:

```
--- a/python/ray/tune/examples/pbt_example.py
+++ b/python/ray/tune/examples/pbt_example.py
@@ -79,7 +79,7 @@ if __name__ == "__main__":
             "pbt_test": {
                 "run": MyTrainableClass,
                 "stop": {
-                    "training_iteration": 2 if args.smoke_test else 99999
+                    "training_iteration": 20 if args.smoke_test else 99999
                 },
                 "num_samples": 10,
                 "config": {
```

### Source code / logs
```
Error processing event: Traceback (most recent call last):
  File "/home/eric/Desktop/ray-private/python/ray/tune/trial_runner.py", line 243, in _process_events
    self.trial_executor.pause_trial(trial)
  File "/home/eric/Desktop/ray-private/python/ray/tune/ray_trial_executor.py", line 149, in pause_trial
    remote_id = self._find_item(self._running, trial)[0]
IndexError: list index out of range

Created LogSyncer for /home/eric/ray_results/pbt_test/MyTrainableClass_8_2018-09-02_15-53-49w7p3hrdy -> 
Error processing event: Traceback (most recent call last):
  File "/home/eric/Desktop/ray-private/python/ray/tune/trial_runner.py", line 243, in _process_events
    self.trial_executor.pause_trial(trial)
  File "/home/eric/Desktop/ray-private/python/ray/tune/ray_trial_executor.py", line 149, in pause_trial
    remote_id = self._find_item(self._running, trial)[0]
IndexError: list index out of range
```

**Comment by ericl** [comment]
cc @joyyoj @richardliaw
