### ISSUE TITLE
[data] Loading images from ImageFolderDatasource gives irrelevant errors

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#28144]
### What happened + What you expected to happen

I tried just loading a simple image dataset via the ImageFolderDatasource. 

The error given was not comprehensible nor actionable:

```python
(_execute_read_task pid=12456) 2022-08-27 17:06:48,416  INFO worker.py:756 -- Task failed with retryable exception: TaskID(39088be3736e590affffffffffffffffffffffff02000000).
(_execute_read_task pid=12456) Traceback (most recent call last):
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/air/util/data_batch_conversion.py", line 158, in _cast_ndarray_columns_to_tensor_extension
(_execute_read_task pid=12456)     df.loc[:, col_name] = TensorArray(col)
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/air/util/tensor_extensions/pandas.py", line 720, in __init__
(_execute_read_task pid=12456)     raise TypeError(
(_execute_read_task pid=12456) TypeError: Tried to convert an ndarray of ndarray pointers (object dtype) to a well-typed ndarray but this failed; convert the ndarray to a well-typed ndarray before casting it as a TensorArray, and note that ragged tensors are NOT supported by TensorArray. First 5 subndarray types: [dtype('uint8'), dtype('uint8'), dtype('uint8'), dtype('uint8'), dtype('uint8')]
(_execute_read_task pid=12456) 
(_execute_read_task pid=12456) The above exception was the direct cause of the following exception:
(_execute_read_task pid=12456) 
(_execute_read_task pid=12456) Traceback (most recent call last):
(_execute_read_task pid=12456)   File "python/ray/_raylet.pyx", line 662, in ray._raylet.execute_task
(_execute_read_task pid=12456)   File "python/ray/_raylet.pyx", line 666, in ray._raylet.execute_task
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/lazy_block_list.py", line 576, in _execute_read_task
(_execute_read_task pid=12456)     block = task()
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/datasource/datasource.py", line 202, in __call__
(_execute_read_task pid=12456)     for block in result:
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/datasource/file_based_datasource.py", line 430, in read_files
(_execute_read_task pid=12456)     yield output_buffer.next()
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/output_buffer.py", line 74, in next
(_execute_read_task pid=12456)     block = self._buffer.build()
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/delegating_block_builder.py", line 64, in build
(_execute_read_task pid=12456)     return self._builder.build()
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/table_block.py", line 85, in build
(_execute_read_task pid=12456)     return self._concat_tables(tables)
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/pandas_block.py", line 110, in _concat_tables
(_execute_read_task pid=12456)     df = _cast_ndarray_columns_to_tensor_extension(df)
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/air/util/data_batch_conversion.py", line 160, in _cast_ndarray_columns_to_tensor_extension
(_execute_read_task pid=12456)     raise ValueError(
(_execute_read_task pid=12456) ValueError: Tried to cast column image to the TensorArray tensor extension type but the conversion failed. To disable automatic casting to this tensor extension, set ctx = DatasetContext.get_current(); ctx.enable_tensor_extension_casting = False.
(_execute_read_task pid=12456) 2022-08-27 17:07:54,815  INFO worker.py:756 -- Task failed with retryable exception: TaskID(39088be3736e590affffffffffffffffffffffff02000000).
(_execute_read_task pid=12456) Traceback (most recent call last):
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/air/util/data_batch_conversion.py", line 158, in _cast_ndarray_columns_to_tensor_extension
(_execute_read_task pid=12456)     df.loc[:, col_name] = TensorArray(col)
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/air/util/tensor_extensions/pandas.py", line 720, in __init__
(_execute_read_task pid=12456)     raise TypeError(
(_execute_read_task pid=12456) TypeError: Tried to convert an ndarray of ndarray pointers (object dtype) to a well-typed ndarray but this failed; convert the ndarray to a well-typed ndarray before casting it as a TensorArray, and note that ragged tensors are NOT supported by TensorArray. First 5 subndarray types: [dtype('uint8'), dtype('uint8'), dtype('uint8'), dtype('uint8'), dtype('uint8')]
(_execute_read_task pid=12456) 
(_execute_read_task pid=12456) The above exception was the direct cause of the following exception:
(_execute_read_task pid=12456) 
(_execute_read_task pid=12456) Traceback (most recent call last):
(_execute_read_task pid=12456)   File "python/ray/_raylet.pyx", line 662, in ray._raylet.execute_task
(_execute_read_task pid=12456)   File "python/ray/_raylet.pyx", line 666, in ray._raylet.execute_task
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/lazy_block_list.py", line 576, in _execute_read_task
(_execute_read_task pid=12456)     block = task()
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/datasource/datasource.py", line 202, in __call__
(_execute_read_task pid=12456)     for block in result:
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/datasource/file_based_datasource.py", line 430, in read_files
(_execute_read_task pid=12456)     yield output_buffer.next()
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/output_buffer.py", line 74, in next
(_execute_read_task pid=12456)     block = self._buffer.build()
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/delegating_block_builder.py", line 64, in build
(_execute_read_task pid=12456)     return self._builder.build()
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/table_block.py", line 85, in build
(_execute_read_task pid=12456)     return self._concat_tables(tables)
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/pandas_block.py", line 110, in _concat_tables
(_execute_read_task pid=12456)     df = _cast_ndarray_columns_to_tensor_extension(df)
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/air/util/data_batch_conversion.py", line 160, in _cast_ndarray_columns_to_tensor_extension
(_execute_read_task pid=12456)     raise ValueError(
(_execute_read_task pid=12456) ValueError: Tried to cast column image to the TensorArray tensor extension type but the conversion failed. To disable automatic casting to this tensor extension, set ctx = DatasetContext.get_current(); ctx.enable_tensor_extension_casting = False.
(_execute_read_task pid=12456) 2022-08-27 17:09:02,630  INFO worker.py:756 -- Task failed with retryable exception: TaskID(39088be3736e590affffffffffffffffffffffff02000000).
(_execute_read_task pid=12456) Traceback (most recent call last):
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/air/util/data_batch_conversion.py", line 158, in _cast_ndarray_columns_to_tensor_extension
(_execute_read_task pid=12456)     df.loc[:, col_name] = TensorArray(col)
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/air/util/tensor_extensions/pandas.py", line 720, in __init__
(_execute_read_task pid=12456)     raise TypeError(
(_execute_read_task pid=12456) TypeError: Tried to convert an ndarray of ndarray pointers (object dtype) to a well-typed ndarray but this failed; convert the ndarray to a well-typed ndarray before casting it as a TensorArray, and note that ragged tensors are NOT supported by TensorArray. First 5 subndarray types: [dtype('uint8'), dtype('uint8'), dtype('uint8'), dtype('uint8'), dtype('uint8')]
(_execute_read_task pid=12456) 
(_execute_read_task pid=12456) The above exception was the direct cause of the following exception:
(_execute_read_task pid=12456) 
(_execute_read_task pid=12456) Traceback (most recent call last):
(_execute_read_task pid=12456)   File "python/ray/_raylet.pyx", line 662, in ray._raylet.execute_task
(_execute_read_task pid=12456)   File "python/ray/_raylet.pyx", line 666, in ray._raylet.execute_task
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/lazy_block_list.py", line 576, in _execute_read_task
(_execute_read_task pid=12456)     block = task()
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/datasource/datasource.py", line 202, in __call__
(_execute_read_task pid=12456)     for block in result:
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/datasource/file_based_datasource.py", line 430, in read_files
(_execute_read_task pid=12456)     yield output_buffer.next()
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/output_buffer.py", line 74, in next
(_execute_read_task pid=12456)     block = self._buffer.build()
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/delegating_block_builder.py", line 64, in build
(_execute_read_task pid=12456)     return self._builder.build()
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/table_block.py", line 85, in build
(_execute_read_task pid=12456)     return self._concat_tables(tables)
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/pandas_block.py", line 110, in _concat_tables
(_execute_read_task pid=12456)     df = _cast_ndarray_columns_to_tensor_extension(df)
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/air/util/data_batch_conversion.py", line 160, in _cast_ndarray_columns_to_tensor_extension
(_execute_read_task pid=12456)     raise ValueError(
(_execute_read_task pid=12456) ValueError: Tried to cast column image to the TensorArray tensor extension type but the conversion failed. To disable automatic casting to this tensor extension, set ctx = DatasetContext.get_current(); ctx.enable_tensor_extension_casting = False.
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    ds = ray.data.read_datasource(ImageFolderDatasource(), root=s3_path)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/read_api.py", line 312, in read_datasource
    block_list.ensure_metadata_for_first_block()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/lazy_block_list.py", line 371, in ensure_metadata_for_first_block
    metadata = ray.get(metadata_ref)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/worker.py", line 2275, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::_execute_read_task() (pid=12456, ip=172.31.91.158)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/air/util/tensor_extensions/pandas.py", line 720, in __init__
    raise TypeError(
TypeError: Tried to convert an ndarray of ndarray pointers (object dtype) to a well-typed ndarray but this failed; convert the ndarray to a well-typed ndarray before casting it as a TensorArray, and note that ragged tensors are NOT supported by TensorArray. First 5 subndarray types: [dtype('uint8'), dtype('uint8'), dtype('uint8'), dtype('uint8'), dtype('uint8')]

The above exception was the direct cause of the following exception:

ray::_execute_read_task() (pid=12456, ip=172.31.91.158)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/lazy_block_list.py", line 576, in _execute_read_task
    block = task()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/datasource/datasource.py", line 202, in __call__
    for block in result:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/datasource/file_based_datasource.py", line 430, in read_files
    yield output_buffer.next()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/output_buffer.py", line 74, in next
    block = self._buffer.build()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/delegating_block_builder.py", line 64, in build
    return self._builder.build()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/table_block.py", line 85, in build
    return self._concat_tables(tables)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/pandas_block.py", line 110, in _concat_tables
    df = _cast_ndarray_columns_to_tensor_extension(df)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/air/util/data_batch_conversion.py", line 160, in _cast_ndarray_columns_to_tensor_extension
    raise ValueError(
ValueError: Tried to cast column image to the TensorArray tensor extension type but the conversion failed. To disable automatic casting to this tensor extension, set ctx = DatasetContext.get_current(); ctx.enable_tensor_extension_casting = False.
(_execute_read_task pid=12456) 2022-08-27 17:09:59,954  INFO worker.py:756 -- Task failed with retryable exception: TaskID(39088be3736e590affffffffffffffffffffffff02000000).
(_execute_read_task pid=12456) Traceback (most recent call last):
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/air/util/data_batch_conversion.py", line 158, in _cast_ndarray_columns_to_tensor_extension
(_execute_read_task pid=12456)     df.loc[:, col_name] = TensorArray(col)
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/air/util/tensor_extensions/pandas.py", line 720, in __init__
(_execute_read_task pid=12456)     raise TypeError(
(_execute_read_task pid=12456) TypeError: Tried to convert an ndarray of ndarray pointers (object dtype) to a well-typed ndarray but this failed; convert the ndarray to a well-typed ndarray before casting it as a TensorArray, and note that ragged tensors are NOT supported by TensorArray. First 5 subndarray types: [dtype('uint8'), dtype('uint8'), dtype('uint8'), dtype('uint8'), dtype('uint8')]
(_execute_read_task pid=12456) 
(_execute_read_task pid=12456) The above exception was the direct cause of the following exception:
(_execute_read_task pid=12456) 
(_execute_read_task pid=12456) Traceback (most recent call last):
(_execute_read_task pid=12456)   File "python/ray/_raylet.pyx", line 662, in ray._raylet.execute_task
(_execute_read_task pid=12456)   File "python/ray/_raylet.pyx", line 666, in ray._raylet.execute_task
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/lazy_block_list.py", line 576, in _execute_read_task
(_execute_read_task pid=12456)     block = task()
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/datasource/datasource.py", line 202, in __call__
(_execute_read_task pid=12456)     for block in result:
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/datasource/file_based_datasource.py", line 430, in read_files
(_execute_read_task pid=12456)     yield output_buffer.next()
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/output_buffer.py", line 74, in next
(_execute_read_task pid=12456)     block = self._buffer.build()
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/delegating_block_builder.py", line 64, in build
(_execute_read_task pid=12456)     return self._builder.build()
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/table_block.py", line 85, in build
(_execute_read_task pid=12456)     return self._concat_tables(tables)
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/pandas_block.py", line 110, in _concat_tables
(_execute_read_task pid=12456)     df = _cast_ndarray_columns_to_tensor_extension(df)
(_execute_read_task pid=12456)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/air/util/data_batch_conversion.py", line 160, in _cast_ndarray_columns_to_tensor_extension
(_execute_read_task pid=12456)     raise ValueError(
(_execute_read_task pid=12456) ValueError: Tried to cast column image to the TensorArray tensor extension type but the conversion failed. To disable automatic casting to this tensor extension, set ctx = DatasetContext.get_current(); ctx.enable_tensor_extension_casting = False.
```

1. How do you get a dataset context? Is it even relevant?
2. None of these stacktraces trace back to user code.

### Versions / Dependencies

ray 2.0
python 3.8

### Reproduction script

```
import ray
from ray.data.datasource import ImageFolderDatasource

s3_path = "s3://anyscale-data/imagenet/"
ds = ray.data.read_datasource(ImageFolderDatasource(), root=s3_path)
sample = ds.take(1)[0]
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by richardliaw** [comment]
@matthewdeng assigning to you for you to triage

**Comment by matthewdeng** [comment]
@clarkzinzow assigning to you for now since you worked closest on the implementation. 

cc @amogkam @jiaodong @bveeramani since you've all encountered this as well.

**Comment by jiaodong** [comment]
You see this issue because `s3://anyscale-data/imagenet/` path has images of different sizes but we also auto-cast them into `TensorArray` that doesn't not work with ragged tensor yet. So we need to add `size=(x, y)` to the `read_datasource` which is supported by Ray 2.0 API (TODO here is better error message) and later we need to add ragged tensor support such as https://github.com/ray-project/ray/pull/27625.

**Comment by matthewdeng** [comment]
@clarkzinzow to confirm ragged tensor PR fixes this

**Comment by clarkzinzow** [comment]
Confirmed that this works with ragged tensors + `read_images()` API.
