### ISSUE TITLE
[Core] gcs_server SIGSEGV with ray 2.0.0

### ISSUE THREAD

**Issue by siavash119** [ray-project/ray#28198]
gcs_server crashing with SIGSEGV requiring me to restart the ray cluster to do anything again. Not exactly sure what's causing it yet, but I think it's to do with my use of get_actor on detached lifetime actors, but I wasn't getting this problem with ray 1.13.0. Rest of my environment exactly the same, reverting back to ray 1.13.0 fixes the issue. I'll try and see if I can get a small script to reproduce this problem, but I'll at least open this issue for now.

gcs_server.err
```
*** SIGSEGV received at time=1661937262 on cpu 4 ***
PC: @     0x563910b4922a  (unknown)  ray::rpc::PinRuntimeEnvURIRequest::PinRuntimeEnvURIRequest()
    @     0x7f5735a3daf0  (unknown)  (unknown)
    @     0x5639109c7ca1        256  ray::gcs::RuntimeEnvHandler::HandlePinRuntimeEnvURI()
    @     0x56391094461c         96  std::_Function_handler<>::_M_invoke()
    @     0x563910bbcfe6         96  EventTracker::RecordExecution()
    @     0x563910b6f83e         48  std::_Function_handler<>::_M_invoke()
    @     0x563910b6fd96        112  boost::asio::detail::completion_handler<>::do_complete()
    @     0x56391109079b        128  boost::asio::detail::scheduler::do_run_one()
    @     0x5639110919e1        192  boost::asio::detail::scheduler::run()
    @     0x563911091c10         64  boost::asio::io_context::run()
    @     0x5639108c7eb9       1440  main
    @     0x7f5735a2920a  (unknown)  (unknown)
[2022-08-31 17:14:22,051 E 368091 368091] (gcs_server) logging.cc:361: *** SIGSEGV received at time=1661937262 on cpu 4 ***
[2022-08-31 17:14:22,052 E 368091 368091] (gcs_server) logging.cc:361: PC: @     0x563910b4922a  (unknown)  ray::rpc::PinRuntimeEnvURIRequest::PinRuntimeEnvURIRequest()
[2022-08-31 17:14:22,052 E 368091 368091] (gcs_server) logging.cc:361:     @     0x7f5735a3daf0  (unknown)  (unknown)
[2022-08-31 17:14:22,052 E 368091 368091] (gcs_server) logging.cc:361:     @     0x5639109c7ca1        256  ray::gcs::RuntimeEnvHandler::HandlePinRuntimeEnvURI()
[2022-08-31 17:14:22,052 E 368091 368091] (gcs_server) logging.cc:361:     @     0x56391094461c         96  std::_Function_handler<>::_M_invoke()
[2022-08-31 17:14:22,052 E 368091 368091] (gcs_server) logging.cc:361:     @     0x563910bbcfe6         96  EventTracker::RecordExecution()
[2022-08-31 17:14:22,052 E 368091 368091] (gcs_server) logging.cc:361:     @     0x563910b6f83e         48  std::_Function_handler<>::_M_invoke()
[2022-08-31 17:14:22,052 E 368091 368091] (gcs_server) logging.cc:361:     @     0x563910b6fd96        112  boost::asio::detail::completion_handler<>::do_complete()
[2022-08-31 17:14:22,052 E 368091 368091] (gcs_server) logging.cc:361:     @     0x56391109079b        128  boost::asio::detail::scheduler::do_run_one()
[2022-08-31 17:14:22,052 E 368091 368091] (gcs_server) logging.cc:361:     @     0x5639110919e1        192  boost::asio::detail::scheduler::run()
[2022-08-31 17:14:22,052 E 368091 368091] (gcs_server) logging.cc:361:     @     0x563911091c10         64  boost::asio::io_context::run()
[2022-08-31 17:14:22,052 E 368091 368091] (gcs_server) logging.cc:361:     @     0x5639108c7eb9       1440  main
[2022-08-31 17:14:22,052 E 368091 368091] (gcs_server) logging.cc:361:     @     0x7f5735a2920a  (unknown)  (unknown)
```

ray_client_server.err
```
2022-08-31 17:17:09,610	ERROR server.py:908 -- <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1661937429.610358767","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1661937429.610358151","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ray/util/client/server/server.py", line 899, in main
    ray.experimental.internal_kv._internal_kv_put(
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/experimental/internal_kv.py", line 94, in _internal_kv_put
    return global_gcs_client.internal_kv_put(key, value, overwrite, namespace) == 0
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/gcs_utils.py", line 177, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/gcs_utils.py", line 296, in internal_kv_put
    reply = self._kv_stub.InternalKVPut(req, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1661937429.610358767","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1661937429.610358151","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
```

**Comment by architkulkarni** [comment]
@siavash119 Thanks for the details, if you can find a reproduction that would be very valuable.  Are you using a `runtime_env` anywhere? If so can you share the details of the `runtime_env`?

**Comment by architkulkarni** [comment]
Also, are you using Ray Client?

**Comment by architkulkarni** [comment]
@siavash119 Sorry for the repeated messages -- could you also share the Python version and operating system?

**Comment by siavash119** [comment]
okay, so it shouldn't be related to those detached actors or the flask/gunicorn servers. Those weren't running when the user with a few config files in a runtime_env working_dir ran again with ray 2.0.0 and got this crash.

**Comment by architkulkarni** [comment]
Reproduced by adding a 10 second sleep between these lines: https://github.com/ray-project/ray/blob/master/src/ray/gcs/gcs_server/runtime_env_handler.cc#L30-L31

Starting a local single node Ray cluster, running the following reproduction script (the pip packages are probably not important):
```
import ray

ray.init("ray://localhost:10001", runtime_env={"working_dir": ".", "pip": ["requests", "tensorflow", "unidic-lite", "torch", "numpy"]})

@ray.remote
def f():
    return 1

ray.get(f.remote())

print("Done")
```

About 75% of the time we get the following segfault which is similar to the one in the issue:
```
*** SIGSEGV received at time=1662744491 ***
PC: @        0x10acf7855  (unknown)  std::__1::basic_string<>::__is_long()
[2022-09-09 10:28:11,143 E 83696 6191639] (gcs_server) logging.cc:361: *** SIGSEGV received at time=1662744491 ***
[2022-09-09 10:28:11,150 E 83696 6191639] (gcs_server) logging.cc:361: PC: @        0x10acf7855  (unknown)  std::__1::basic_string<>::__is_long()
```

Which is likely coming from the URI string in the request.  With the fix in the linked PR, we never see the segfault.

**Comment by siavash119** [comment]
1 head and 8 nodes connected over 10GBe. Each node is started with --num-cpus=40.  The user was running with 200 actors.

the 1.13 crash was a little different now that I look at it. I'll paste some logs here for now; let me know if you want something else

gcs_server.err
```
[2022-09-09 16:46:54,170 C 902259 902259] (gcs_server) gcs_actor_manager.cc:170:  Check failed: actor_table_data_.state() != rpc::ActorTableData::DEAD 
*** StackTrace Information ***
    ray::SpdLogMessage::Flush()
    ray::RayLog::~RayLog()
    ray::gcs::GcsActor::GetCreationTaskSpecification()
    ray::gcs::GcsActorScheduler::CreateActorOnWorker()
    std::_Function_handler<>::_M_invoke()
    std::_Function_handler<>::_M_invoke()
    std::_Function_handler<>::_M_invoke()
    EventTracker::RecordExecution()
    std::_Function_handler<>::_M_invoke()
    boost::asio::detail::completion_handler<>::do_complete()
    boost::asio::detail::scheduler::do_run_one()
    boost::asio::detail::scheduler::run()
    boost::asio::io_context::run()
    main
```

ray_client_server.err
```
2022-09-09 18:08:39,252	ERROR server.py:873 -- [proxy] Failed to put health check on 192.168.66.73:6379
2022-09-09 18:08:39,252	ERROR server.py:876 -- <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1662718119.252399067","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1662718119.252398302","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ray/util/client/server/server.py", line 867, in main
    ray.experimental.internal_kv._internal_kv_put(
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/experimental/internal_kv.py", line 88, in _internal_kv_put
    return global_gcs_client.internal_kv_put(key, value, overwrite, namespace) == 0
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/gcs_utils.py", line 137, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/gcs_utils.py", line 228, in internal_kv_put
    reply = self._kv_stub.InternalKVPut(req)
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1662718119.252399067","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1662718119.252398302","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
```

monitor.log
```
2022-09-09 16:46:56,940	ERROR monitor.py:382 -- Monitor: Execution exception. Trying again...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ray/autoscaler/_private/monitor.py", line 338, in _run
    self.update_load_metrics()
  File "/usr/local/lib/python3.10/dist-packages/ray/autoscaler/_private/monitor.py", line 243, in update_load_metrics
    response = self.gcs_node_resources_stub.GetAllResourceUsage(request, timeout=60)
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1662713216.939884731","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1662713216.939884079","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
```
