### ISSUE TITLE
[Ray AIR] Load some layers of tensorflow model such as BatchNormalization layer raise pickle error

### ISSUE THREAD

**Issue by Alxe1** [ray-project/ray#28194]
### What happened + What you expected to happen

I write subclassed model of tensorflow and using ray air to train it. It goes well when I train my model and save it as SavedModel format. Last I want to predict my dataset using `BatchPredictor`, but unfortunately I can only load model using `tf.keras.models.load_model` but not `from_checkpoint` in the air, so I rewrite the `Predictor` and `BatchPredictor` class like below:

```
class CustomePredictor(Predictor):
    """user defined Predictor. """
    def __init__(self, model: tf.keras.Model):
        super(CustomePredictor, self).__init__()
        self.model = model

    @classmethod
    def from_model(cls, model_path: Union[str, os.PathLike], **kwargs) -> "CustomePredictor":
        """
        Instance Predictor using from_model
        :param model_path: keras model path
        :param kwargs:
        :return: CustomePredictor
        """
        model = load_model(model_path)
        return cls(model)

    @classmethod
    def from_checkpoint(cls, checkpoint: Checkpoint, **kwargs) -> "CustomePredictor":
        """
        NOT USED
        :param checkpoint:
        :param kwargs:
        :return:
        """
        # noinspection PyProtectedMember
        model_path = checkpoint._local_path  # can not pass to ScoringWrapper
        if not model_path:
            raise ValueError(f"Can not find checkpoint local path, "
                             f"please save checkpoint to local path first, got {model_path}")
        print(f"model path: {model_path}")
        model = load_model(model_path)
        return cls(model)

    def _predict_pandas(self,
                        data: "pd.DataFrame",
                        dtype: Union[TensorDtype, Dict[str, TensorDtype]] = None) -> "pd.DataFrame":
        """
        Implementation of super class
        :param data:
        :param dtype:
        :return:
        """
        tensors = convert_pandas_to_batch_type(
            data,
            DataType.NUMPY,
            self._cast_tensor_columns,
        )
        model_input = self._arrays_to_tensors(tensors, dtype)

        output = self.model(model_input)

        # Handle model multi-output. For example if model outputs 2 images.
        if isinstance(output, dict):
            return pd.DataFrame(
                {k: TensorArray(self._tensor_to_array(v)) for k, v in output.items()}
            )
        else:
            return pd.DataFrame(
                {"predictions": TensorArray(self._tensor_to_array(output))},
                columns=["predictions"],
            )

    def _predict_arrow(self, data: "pyarrow.Table", **kwargs) -> "pyarrow.Table":
        raise NotImplementedError

    def _arrays_to_tensors(
        self,
        numpy_arrays: Union[np.ndarray, Dict[str, np.ndarray]],
        dtypes: Union[tf.dtypes.DType, Dict[str, tf.dtypes.DType]],
    ) -> Union[tf.Tensor, Dict[str, tf.Tensor]]:
        return convert_ndarray_batch_to_tf_tensor_batch(numpy_arrays, dtypes=dtypes)

    def _tensor_to_array(self, tensor: tf.Tensor) -> np.ndarray:
        if not isinstance(tensor, tf.Tensor):
            raise ValueError(
                "Expected the model to return either a tf.Tensor or a "
                f"dict of tf.Tensor, but got {type(tensor)} instead. "
                f"To support models with different output types, subclass "
                f"TensorflowPredictor and override the `call_model` method "
                f"to process the output into either torch.Tensor or Dict["
                f"str, torch.Tensor]."
            )
        return tensor.numpy()


class CustomeBatchPredictor(object):
    """user defined batch predictor"""
    def __init__(self, model_path: Union[str, os.PathLike], predictor_cls: Type[Predictor], **predictor_kwargs):
        """

        :param model_path: tensorflow keras Model path
        :param predictor_cls: subclass of Predictor
        :param predictor_kwargs:
        """
        self.model_path = model_path
        self._predictor_cls = predictor_cls
        self._predictor_kwargs = predictor_kwargs
        # ================================
        self.model = load_model(self.model_path)
        # ================================

    def __repr__(self):
        return (
            f"{self.__class__.__name__}(model_path={self.model_path}, "
            f"predictor_cls={self._predictor_cls.__name__})"
        )

    @classmethod
    def from_model(cls,
                   model_path: Union[str, os.PathLike],
                   predictor_cls: Type[Predictor],
                   **kwargs) -> "CustomeBatchPredictor":
        """
        load keras model
        :param model_path: same as __init__ method
        :param predictor_cls: same as __init__ method
        :param kwargs:
        :return:
        """
        return cls(model_path, predictor_cls, **kwargs)

    def predict(self,
                data: Union[ray.data.Dataset, ray.data.DatasetPipeline],
                feature_columns: Optional[List[str]] = None,
                keep_columns: Optional[List[str]] = None,
                batch_size: int = 4096,
                min_scoring_workers: int = 1,
                max_scoring_workers: Optional[int] = None,
                **predict_kwargs) -> ray.data.Dataset:
        """
        Another implementation of BatchPredictor.predict
        """
        _predictor_cls = self._predictor_cls
        _model = self.model
        # ==============================
        _model_ref = ray.put(_model)
        # ==============================

        ctx = DatasetContext.get_current()
        cast_tensor_columns = ctx.enable_tensor_extension_casting

        class ScoringWrapper:
            def __init__(self):
                # ==================================
                self._predictor = _predictor_cls(ray.get(_model_ref))
                # ==================================

            def __call__(self, batch):
                if feature_columns:
                    prediction_batch = batch[feature_columns]
                else:
                    prediction_batch = batch
                prediction_output = self._predictor.predict(prediction_batch, **predict_kwargs)
                if keep_columns:
                    prediction_output[keep_columns] = batch[keep_columns]
                return convert_batch_type_to_pandas(prediction_output, cast_tensor_columns=cast_tensor_columns)

        compute = ray.data.ActorPoolStrategy(
            min_size=min_scoring_workers, max_size=max_scoring_workers
        )

        prediction_results = data.map_batches(
            ScoringWrapper,
            compute=compute,
            batch_format="pandas",
            batch_size=batch_size
        )
        return prediction_results

```

I use `ray.put` to put my model to worker, and in the `ScoringWrapper` class, I use `ray.get` to get the model. It goes well  when my model has no `BatchNormalization` layer, and when I add  `BatchNormalization` layer, it raised some error:
```
WARNING:absl:<keras.saving.saved_model.load.BatchNormalization object at 0x7f88ba6a7e90> has the same name 'BatchNormalization' as a built-in Keras object. Consider renaming <class 'keras.saving.saved_model.load.BatchNormalization'> to avoid naming conflicts when loading with `tf.keras.models.load_model`. If renaming is not possible, pass the object in the `custom_objects` parameter of the load function.
Put failed:
Traceback (most recent call last):
  File "test2.py", line 775, in <module>
    train_test()
  File "test2.py", line 770, in train_test
    predict_batch(testset)
  File "test2.py", line 731, in predict_batch
    keep_columns=["is_click"]
  File "test2.py", line 691, in predict
    _model_ref = ray.put(_model)
  File "/mnt/softwares/hvd_env/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/mnt/softwares/hvd_env/lib/python3.7/site-packages/ray/util/client/api.py", line 52, in put
    return self.worker.put(*args, **kwargs)
  File "/mnt/softwares/hvd_env/lib/python3.7/site-packages/ray/util/client/worker.py", line 490, in put
    return self._put_pickled(data, client_ref_id)
  File "/mnt/softwares/hvd_env/lib/python3.7/site-packages/ray/util/client/worker.py", line 499, in _put_pickled
    raise cloudpickle.loads(resp.error)
AttributeError: 'Ones' object has no attribute '_set_dtype_policy'
```

It smells a pickle problem, or it lost something when using `ray.put` or `ray.get`

### Versions / Dependencies

ray 2.0.0
tensorflow 2.7.0
python 3.7.10

### Reproduction script

In [What happened + What you expected to happen]

**Comment by richardliaw** [comment]
This is awesome feedback. Much appreciated, @Alxe1. 

@xwjiang2010 can you take a look at this when you get the chance? This is related to a previous feedback to use load_model for TensorflowCheckpoints.

**Comment by xwjiang2010** [comment]
@richardliaw could you link the other feedback?

@Alxe1 Thanks for the issue! For this immediate problem, the way to avoid ser/deser problem is to distribute the AIR checkpoint to different nodes (taken care by AIR Checkpoint itself) and load_model from each individual remote actor (that does batch inference). 

However, I wonder if we should also support SavedModel format in addition to model weights + model definition for TensorflowPredictor. Ideally user like Alex should not need to implement his own CustomePredictor for something as standardized as SavedModel. Is this something we want to revisit? Should we have two flavors of TensorflowPredictor then?

@jiaodong @amog any thoughts?

**Comment by richardliaw** [comment]
@xwjiang2010 here -- https://github.com/ray-project/ray/issues/26933
