### ISSUE TITLE
[Core] runtime_env ray version checking fails when there's extra logging

### ISSUE THREAD

**Issue by zygi** [ray-project/ray#28222]
### What happened + What you expected to happen

I have created a ray cluster and am trying to submit a job with a runtime env. The runtime env contains one package, "wandb". When creating the env, the job crashes with the following message:

```
2022-08-31 19:10:33,347 INFO packaging.py:498 -- Creating a file package for local directory './.'.
2022-08-31 19:10:33,371 INFO packaging.py:342 -- Pushing file package 'gcs://_ray_pkg_fc8fb8ff77b0621e.zip' (3.41MiB) to Ray cluster...
2022-08-31 19:10:35,482 INFO packaging.py:351 -- Successfully pushed file package 'gcs://_ray_pkg_fc8fb8ff77b0621e.zip'.
Traceback (most recent call last):
  File "/Users/zygi/llm/monorepo/models/mesh-transformer-jax/./repro.py", line 4, in <module>
    ray.init("ray://localhost:10001", runtime_env = {"working_dir": "./.", "pip":
  File "/Users/zygi/miniforge3/envs/mtj/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/zygi/miniforge3/envs/mtj/lib/python3.10/site-packages/ray/_private/worker.py", line 1248, in init
    ctx = builder.connect()
  File "/Users/zygi/miniforge3/envs/mtj/lib/python3.10/site-packages/ray/client_builder.py", line 178, in connect
    client_info_dict = ray.util.client_connect.connect(
  File "/Users/zygi/miniforge3/envs/mtj/lib/python3.10/site-packages/ray/util/client_connect.py", line 47, in connect
    conn = ray.connect(
  File "/Users/zygi/miniforge3/envs/mtj/lib/python3.10/site-packages/ray/util/client/__init__.py", line 252, in connect
    conn = self.get_context().connect(*args, **kw_args)
  File "/Users/zygi/miniforge3/envs/mtj/lib/python3.10/site-packages/ray/util/client/__init__.py", line 102, in connect
    self.client_worker._server_init(job_config, ray_init_kwargs)
  File "/Users/zygi/miniforge3/envs/mtj/lib/python3.10/site-packages/ray/util/client/worker.py", line 838, in _server_init
    raise ConnectionAbortedError(
ConnectionAbortedError: Initialization failure from server:
Traceback (most recent call last):
  File "/home/ray/.local/lib/python3.10/site-packages/ray/util/client/server/proxier.py", line 678, in Datapath
    if not self.proxy_manager.start_specific_server(
  File "/home/ray/.local/lib/python3.10/site-packages/ray/util/client/server/proxier.py", line 304, in start_specific_server
    serialized_runtime_env_context = self._create_runtime_env(
  File "/home/ray/.local/lib/python3.10/site-packages/ray/util/client/server/proxier.py", line 253, in _create_runtime_env
    raise RuntimeError(
RuntimeError: Failed to create runtime_env for Ray client server, it is caused by:
Traceback (most recent call last):
  File "/home/ray/.local/lib/python3.10/site-packages/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 341, in _create_runtime_env_with_retry
    runtime_env_context = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/home/ray/.local/lib/python3.10/site-packages/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 296, in _setup_runtime_env
    await create_for_plugin_if_needed(
  File "/home/ray/.local/lib/python3.10/site-packages/ray/_private/runtime_env/plugin.py", line 251, in create_for_plugin_if_needed
    size_bytes = await plugin.create(uri, runtime_env, context, logger=logger)
  File "/home/ray/.local/lib/python3.10/site-packages/ray/_private/runtime_env/pip.py", line 453, in create
    return await task
  File "/home/ray/.local/lib/python3.10/site-packages/ray/_private/runtime_env/pip.py", line 435, in _create_for_hash
    await PipProcessor(
  File "/home/ray/.local/lib/python3.10/site-packages/ray/_private/runtime_env/pip.py", line 331, in _run
    async with self._check_ray(python, exec_cwd, logger):
  File "/usr/lib/python3.10/contextlib.py", line 206, in __aexit__
    await anext(self.gen)
  File "/home/ray/.local/lib/python3.10/site-packages/ray/_private/runtime_env/pip.py", line 190, in _check_ray
    raise RuntimeError(
RuntimeError: Changing the ray version is not allowed: 
  current version: /usr/lib/python3/dist-packages/requests/__init__.py:89:, current path: RequestsDependencyWarning:
  expect version: 2.0.0, expect path: /home/ray/.local/lib/python3.10/site-packages/ray
Please ensure the dependencies in the runtime_env pip field do not install a different version of Ray.
```

It seems what's happening is that importing `ray` after installing `wandb` causes a logging message to get printed, and ray version checking logic doesn't handle that in https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/pip.py#L173

### Versions / Dependencies

python==3.10.6
ray==2.0.0
wandb==0.13.2

cluster is on gcp

### Reproduction script

import ray

ray.init("ray://localhost:10001", runtime_env = {"working_dir": "./.", "pip": 
    ["wandb"] # commenting out this line makes the code work
    })

@ray.remote
def hello():
    print("hello")

ray.get(hello.remote())

### Issue Severity

Low: It annoys or frustrates me.

**Comment by robertnishihara** [comment]
Looks like you're using Ray client. Can you confirm that you definitely have the same version of Ray on your laptop where you run the driver script as well as on the cluster?

Separately, does this get unblocked by running the driver script on the cluster? E.g., using `ray submit` or just ssh'ing to the cluster.

**Comment by Catch-Bull** [comment]
Hi @zygi,  We rely on stdout of the following command to check the ray version, the implementation here is really not very robust, I probably need a week to fix it:
``` bash
$python -c "import ray; print(ray.__version__, ray.__path__[0])"
2.0.0 /home/admin/.pyenv/versions/3.6.13/lib/python3.6/site-packages/ray
```
I read the code of package `requests`, It should be that your `cryptography` version is too low, which caused the `requests` to print some warnings. It should be solved by upgrading it.

**Comment by zygi** [comment]
Hmm, I had expected the "cryptography" version upgrade to work but for some reason it doesn't! Looking at the code of `requests` ( https://github.com/psf/requests/blob/main/requests/__init__.py#L96 ), the threshold version is 1.3.4 . But the version the code should be using already is higher!

On head:
```
> ray attach <config>.yaml

> python -c "import cryptography; print(cryptography.__version__)"
2.8
```


Inside runtime_env in a job:
running this prints "2.8"
```
import cryptography
ray.init("ray://localhost:10001", runtime_env = {"working_dir": "./.", "pip": []})

@ray.remote
def hello():
    print(cryptography.__version__)

ray.get(hello.remote())
```

But, running this throws the same error from above:
```
import cryptography
ray.init("ray://localhost:10001", runtime_env = {"working_dir": "./.", "pip": ["wandb"]})

@ray.remote
def hello():
    print(cryptography.__version__)

ray.get(hello.remote())
```

So I guess my question is, what scope is the code at https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/pip.py#L173 running in? Which python environment should have the updated "cryptography" version available?

**Comment by SongGuyang** [comment]
@zygi Can you run and show the output of the command?
```
python -c "import ray; print(ray.__version__, ray.__path__[0])"
```

I think this is a bug which we should fix. As what @Catch-Bull said above, we didn't consider very well when we parse the stdout of the command. And When some unknown messages appear in the stdout, the version of ray will fail to be parsed. 

Can you wait for us to fix it and try it again by a snapshot ray wheel?

**Comment by Catch-Bull** [comment]
I will fix it this week.

**Comment by robertnishihara** [comment]
Thanks @Catch-Bull is there a good workaround for now?

**Comment by SongGuyang** [comment]
> Thanks @Catch-Bull is there a good workaround for now?

Modify the code https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/pip.py#L190 to skip it temporarily?

@zygi you can change the exception to be an warning log: `raise RuntimeError` -> `logger.warning`

Your source code is located in /home/ray/.local/lib/python3.10/site-packages/ray/_private/runtime_env/pip.py

But it is not a good way because you should modify it in all of your machines.

**Comment by architkulkarni** [comment]
> So I guess my question is, what scope is the code at https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/pip.py#L173 running in? Which python environment should have the updated "cryptography" version available?

@zygi To answer the question, it's running in the same environment that it would be running in without using `runtime_env`; the `wandb` package is just installed on top using `virtualenv`.  So the `cryptography` version might not be the issue.

To be sure about the warning, can you try the command at https://github.com/ray-project/ray/issues/28222#issuecomment-1236527176?  It should print the full warning from `requests` and might give clues for a simple workaround.
