### ISSUE TITLE
[Tune] got 'FileNotFoundError' , 'Trials did not complete' error whenever model checkpointing

### ISSUE THREAD

**Issue by hyoonsoo** [ray-project/ray#28233]
### What happened + What you expected to happen

I'm training multi-agent reinforcement learning agents in 'metadrive' environment.  I have two problems.

1)  FileNotFoundError occured whenever I save checkpoints.
I think that new files are created and checkpoints are saved. By the way, why do I get an error that says there are no files in that path? that check point files are not saved yet... 
And there are many cases where checkpoints cannot be saved. 

1-1) this is Error message.

Failure # 1 (occurred at 2022-09-01_16-25-24)
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\tune\trial_runner.py", line 586, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\tune\ray_trial_executor.py", line 609, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\_private\client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AccessDenied): [36mray::CoPO.train_buffered()[39m (pid=30008, ip=10.19.40.19)
  File "python\ray\_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\function_manager.py", line 556, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\tune\trainable.py", line 167, in train_buffered
    result = self.train()
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\rllib\agents\trainer.py", line 526, in train
    raise e
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\rllib\agents\trainer.py", line 515, in train
    result = Trainable.train(self)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\tune\trainable.py", line 226, in train
    result = self.step()
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\rllib\agents\trainer_template.py", line 148, in step
    res = next(self.train_exec_impl)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\util\iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\util\iter.py", line 843, in apply_filter
    for item in it:
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\util\iter.py", line 843, in apply_filter
    for item in it:
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 2 more times]
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\util\iter.py", line 876, in apply_flatten
    for item in it:
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\util\iter.py", line 828, in add_wait_hooks
    item = next(it)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\util\iter.py", line 471, in base_iterator
    yield ray.get(futures, timeout=timeout)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\_private\client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AccessDenied): [36mray::RolloutWorker.par_iter_next()[39m (pid=12816, ip=10.19.40.19)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 780, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=True)
PermissionError: [WinError 5]  Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

[36mray::RolloutWorker.par_iter_next()[39m (pid=12816, ip=10.19.40.19)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 695, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 783, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=False)
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

[36mray::RolloutWorker.par_iter_next()[39m (pid=12816, ip=10.19.40.19)
  File "python\ray\_raylet.pyx", line 440, in ray._raylet.execute_task
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\memory_monitor.py", line 132, in raise_if_low_memory
    self.error_threshold))
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\memory_monitor.py", line 43, in get_message
    proc.cmdline()))
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\thirdparty_files\psutil\__init__.py", line 677, in cmdline
    return self._proc.cmdline()
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=116)

Failure # 2 (occurred at 2022-09-01_16-32-15)
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\tune\trial_runner.py", line 763, in _process_trial_save
    results = self.trial_executor.fetch_result(trial)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\tune\ray_trial_executor.py", line 609, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\_private\client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(FileNotFoundError): [36mray::CoPO.save()[39m (pid=45576, ip=10.19.40.19)
  File "python\ray\_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\function_manager.py", line 556, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\tune\trainable.py", line 326, in save
    trainable_state=trainable_state)
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\tune\utils\trainable.py", line 42, in process_checkpoint
    with open(checkpoint_path + ".tune_metadata", "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\PycharmProjects\\metaCoPo\\CoPO\\copo_code\\copo\\TEST0901\\CoPO_CCMultiAgentIntersectionEnv_0448b_00005_5_env=CCMultiAgentIntersectionEnv,start_seed=10000,seed=0,use_centralized_critic=Fals_2022-09-01_16-23-46\\checkpoint_10\\checkpoint-10.tune_metadata'

2) 'Trials did not complete' error. I don't know when it occurs.
2-2) This is the error message. 

Traceback (most recent call last):
  File "train_all_copo_dist.py", line 66, in <module>
    custom_callback=MultiAgentDrivingCallbacks,
  File "c:\users\user\pycharmprojects\metacopo\copo\copo_code\copo\train\train.py", line 108, in train
    **kwargs
  File "C:\Users\user\anaconda3\envs\copo\lib\site-packages\ray\tune\tune.py", line 444, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [CoPO_CCMultiAgentIntersectionEnv_0448b_00000, CoPO_CCMultiAgentIntersectionEnv_0448b_00001, CoPO_CCMultiAgentIntersectionEnv_0448b_00002, CoPO_CCMultiAgentIntersectionEnv_0448b_00003, CoPO_CCMultiAgentIntersectionEnv_0448b_00004, CoPO_CCMultiAgentIntersec
tionEnv_0448b_00005, CoPO_CCMultiAgentIntersectionEnv_0448b_00006, CoPO_CCMultiAgentIntersectionEnv_0448b_00007])
(copo)

### Versions / Dependencies

I'm using

ray==1.2.0
gym==0.19.0
tensorflow==2.3.1
metadrive-simulator==0.2.5.1

The code I use requires ray==1.2.0, so I want to keep the version of ray.
How should I correct and fix the errors? ?

### Reproduction script

The code is so complicated that it will be difficult to reproduce it with a simple snippet. T.T (project also has external dependencies...)

### Issue Severity

High: It blocks me from completing my task.

**Comment by krfricke** [comment]
Ray 1.2.0 is very old (over 1.5 years now), so many fixes have been implemented since then.

However, for the specific file not found error, this seems to be a filesystem issue on Windows. The path `C:\Users\user\PycharmProjects\metaCoPo\CoPO\copo_code\copo\TEST0901\CoPO_CCMultiAgentIntersectionEnv_0448b_00005_5_env=CCMultiAgentIntersectionEnv,start_seed=10000,seed=0,use_centralized_critic=Fals_2022-09-01_16-23-46\checkpoint_10\checkpoint-10.tune_metadata` is 266 chars long, and I reckon that your Windows version or filesystem can't handle filenames longer than 254 characters.

You can try to pass a `trial_dirname_creator` to `tune.run()` to create a shorter name:

```
tune.run(
    # ...
    trial_dirname_creator=lambda trial: str(trial)

```

For the second error, if a trial does not complete there is another error thrown that you should find in the respective error.log file (which is displayed in the output table). If you paste that here, we may be able to help you.
