### ISSUE TITLE
[Nightly test] chaos_dataset_shuffle_push_based_sort_1tb fails 5/3 by the RPC failure to  

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#28242]
### What happened + What you expected to happen

https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_18YK5Pj8tmfCFG5cW6v7XJh3?command-history-section=command_history

```
Shuffle Reduce: 100%|██████████| 1000/1000 [13:36<00:00,  2.09s/it]
Shuffle Reduce: 100%|██████████| 1000/1000 [13:36<00:00,  1.22it/s]
(raylet, ip=172.31.88.227) Spilled 34827 MiB, 716 objects, write throughput 524 MiB/s.
(scheduler +1h24s) Restarting 1 nodes of type worker_node (lost contact with raylet).
Finished in 3628.4985580444336

==== Driver memory summary ====
max: 0.496248/GB
rss: 0.508157952/GB
Traceback (most recent call last):
  File "dataset/sort.py", line 137, in <module>
    print(memory_summary(stats_only=True))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/internal_api.py", line 39, in memory_summary
    return get_store_stats(state)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/internal_api.py", line 77, in get_store_stats
    timeout=60.0,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1661903598.593182498","description":"Error received from peer ipv4:172.31.77.110:45779","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
```

### Versions / Dependencies

master

### Reproduction script

N/A

**Comment by rkooo567** [comment]
cc @jjyao @stephanie-wang can you guys help finding the owner of this test to fix?

**Comment by stephanie-wang** [comment]
This is a known issue with the `ray memory` command when there are lots of objects.

**Comment by scv119** [comment]
let's add a try catch around it so it doesn't fail? separately does the new ray observability API fix the problem?

**Comment by stephanie-wang** [comment]
> let's add a try catch around it so it doesn't fail? separately does the new ray observability API fix the problem?

Yeah, that sounds good! I'll take this one.

Not sure if the new APIs have the same problem, I think we just need to paginate the results to avoid the issue. Probably we should deprecate the old `ray memory` command and/or swap out the implementation.
