### ISSUE TITLE
RuntimeError: Head node of cluster  not found!

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#2825]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.13.2
- **Ray version**: 5.0.2
- **Python version**: 3.5.2 
- **Exact command to reproduce**: ray attach ray_autoscale.yaml --cluster-name ray-param-search-head

### Describe the problem

I try to attach to a node that's open but ray attach doesn't find it. 
The node is described in the following image:
![image](https://user-images.githubusercontent.com/7660397/45066360-e6382680-b072-11e8-99d5-f91bac56c515.png)

I have also tried running ray attach ray_autoscale.yaml --cluster-name ray-param-search because I wasn't sure if the head was needed. 

### Source code / logs

Traceback (most recent call last):
  File "/Users/eugenevinitsky/anaconda2/envs/flow/bin/ray", line 11, in <module>
    load_entry_point('ray', 'console_scripts', 'ray')()
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/scripts/scripts.py", line 570, in main
    return cli()
  File "/Users/eugenevinitsky/anaconda2/envs/flow/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/eugenevinitsky/anaconda2/envs/flow/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/eugenevinitsky/anaconda2/envs/flow/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/eugenevinitsky/anaconda2/envs/flow/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/eugenevinitsky/anaconda2/envs/flow/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/eugenevinitsky/anaconda2/envs/flow/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/eugenevinitsky/anaconda2/envs/flow/lib/python3.5/site-packages/click/core.py", line 87, in augment_usage_errors
    yield
  File "/Users/eugenevinitsky/anaconda2/envs/flow/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/scripts/scripts.py", line 481, in attach
    attach_cluster(cluster_config_file, start, cluster_name)
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/autoscaler/commands.py", line 223, in attach_cluster
    override_cluster_name, None)
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/autoscaler/commands.py", line 245, in exec_cluster
    config, config_file, override_cluster_name, create_if_needed=start)
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/ray_upstream/python/ray/autoscaler/commands.py", line 343, in _get_head_node
    raise RuntimeError("Head node of cluster ({}) not found!".format(
RuntimeError: Head node of cluster (ray-param-search-head) not found!

**Comment by ericl** [comment]
The cluster name should just be 'param-search' I believe (or you can omit it and it will pull it from the yaml file).

**Comment by 0xHHHH** [comment]
@eugenevinitsky hello, I also encountered this problem. Have you solved it yet? or can I have your yaml file ?!

**Comment by LeLoMAu** [comment]
You need to create a new head node by setting up the cluster first: 
`ray up tune-default.yaml`
