### ISSUE TITLE
[Serve] DAGDriver cannot run with more than one dag

### ISSUE THREAD

**Issue by mfojtak** [ray-project/ray#28338]
### What happened + What you expected to happen

"Each DAG should only have one unique InputNode"
exception is fired when using DAGDriver with more than one dags each containing InputNode

### Versions / Dependencies

Ray 2.0.0
Python 3.9.5

### Reproduction script

Dags are constructed like this. They each contain InputNode.

``` python
with InputNode as inp:
   out = dep.bind(inp)
return out
```
Now when trying to run the DAGDriver with both dags - the exception is fired.
Running driver with only one dag works.

``` python
driver = DAGDriver.bind({"/dag1": dag1, "/dag2": dag2}) #both dags are valid and can be run separately
handle = serve.run(driver) #exception fired here
```

Traceback (most recent call last):
  File "/data/serving/test.py", line 71, in <module>
    handle = serve.run(driver)
  File "/opt/conda/lib/python3.9/site-packages/ray/serve/api.py", line 466, in run
    deployments = pipeline_build(target)
  File "/opt/conda/lib/python3.9/site-packages/ray/serve/_private/deployment_graph_build.py", line 87, in build
    serve_root_dag = ray_dag_root_node.apply_recursive(
  File "/opt/conda/lib/python3.9/site-packages/ray/dag/dag_node.py", line 215, in apply_recursive
    self._apply_and_replace_all_child_nodes(
  File "/opt/conda/lib/python3.9/site-packages/ray/dag/dag_node.py", line 171, in _apply_and_replace_all_child_nodes
    replace_table[node] = fn(node)
  File "/opt/conda/lib/python3.9/site-packages/ray/dag/dag_node.py", line 216, in <lambda>
    lambda node: node.apply_recursive(fn)
  File "/opt/conda/lib/python3.9/site-packages/ray/dag/dag_node.py", line 215, in apply_recursive
    self._apply_and_replace_all_child_nodes(
  File "/opt/conda/lib/python3.9/site-packages/ray/dag/dag_node.py", line 171, in _apply_and_replace_all_child_nodes
    replace_table[node] = fn(node)
  File "/opt/conda/lib/python3.9/site-packages/ray/dag/dag_node.py", line 216, in <lambda>
    lambda node: node.apply_recursive(fn)
  File "/opt/conda/lib/python3.9/site-packages/ray/dag/dag_node.py", line 214, in apply_recursive
    return fn(
  File "/opt/conda/lib/python3.9/site-packages/ray/dag/dag_node.py", line 206, in __call__
    raise AssertionError(
AssertionError: Each DAG should only have one unique InputNode.

### Issue Severity

High: It blocks me from completing my task.

**Comment by mfojtak** [comment]
@sihanwang41 Thank you. That works.
