### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by Sundar0989** [ray-project/ray#28415]
### What happened + What you expected to happen

When i run the command below,
```python
import ray
ray.init(dashboard_host='xyz.somehost.com', dashboard_port=6380)
```
I get the following error
```
(raylet) Traceback (most recent call last):
(raylet) File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/agent.py", line 375, in
(raylet) raise e
(raylet) File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/agent.py", line 363, in
(raylet) loop.run_until_complete(agent.run())
(raylet) File "/users/usr_name/.conda/envs/3point8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
(raylet) return future.result()
(raylet) File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/agent.py", line 152, in run
(raylet) modules = self._load_modules()
(raylet) File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/agent.py", line 106, in _load_modules
(raylet) c = cls(self)
(raylet) File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 152, in init
(raylet) self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)
(raylet) File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/_private/metrics_agent.py", line 75, in init
(raylet) prometheus_exporter.new_stats_exporter(
(raylet) File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 332, in new_stats_exporter
(raylet) exporter = PrometheusStatsExporter(
(raylet) File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 265, in init
(raylet) self.serve_http()
(raylet) File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 319, in serve_http
(raylet) start_http_server(
(raylet) File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/prometheus_client/exposition.py", line 168, in start_wsgi_server
(raylet) TmpServer.address_family, addr = _get_best_family(addr, port)
(raylet) File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/prometheus_client/exposition.py", line 157, in _get_best_family
(raylet) infos = socket.getaddrinfo(address, port)
(raylet) File "/users/usr_name/.conda/envs/3point8/lib/python3.8/socket.py", line 918, in getaddrinfo
(raylet) for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
(raylet) socket.gaierror: [Errno -2] Name or service not known
2022-09-09 15:03:12,280 WARNING worker.py:1227 -- The agent on node xyz.somehost.com failed with the following error:
Traceback (most recent call last):
File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/agent.py", line 363, in
loop.run_until_complete(agent.run())
File "/users/usr_name/.conda/envs/3point8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/agent.py", line 152, in run
modules = self._load_modules()
File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/agent.py", line 106, in _load_modules
c = cls(self)
File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 152, in init
self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)
File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/_private/metrics_agent.py", line 75, in init
prometheus_exporter.new_stats_exporter(
File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 332, in new_stats_exporter
exporter = PrometheusStatsExporter(
File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 265, in init
self.serve_http()
File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 319, in serve_http
start_http_server(
File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/prometheus_client/exposition.py", line 168, in start_wsgi_server
TmpServer.address_family, addr = _get_best_family(addr, port)
File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/prometheus_client/exposition.py", line 157, in _get_best_family
infos = socket.getaddrinfo(address, port)
File "/users/usr_name/.conda/envs/3point8/lib/python3.8/socket.py", line 918, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

Please assist

### Versions / Dependencies

Ray version - 1.7.0
Python version - 3.8.13
OS - Linux

This is part of using modin & ray package together. I raised the issue with Modin team and they asked me to raise the issue here.

### Reproduction script

```python
import ray
ray.init(dashboard_host='xyz.somehost.com', dashboard_port=6380)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by pcmoritz** [comment]
Thanks for opening the issue!

As described in the docstring https://docs.ray.io/en/latest/ray-core/package-ref.html#ray-init, the dashboard_host can only be set to either `0.0.0.0` (listen on all interfaces) or `127.0.0.1` (listen on localhost only). Other values are not supported.

If you want to run the dashboard behind a URL, you need to
- Run the dashboard with dashboard_host = 0.0.0.0 on a node
- Set up an https proxy for your custom URL that proxies the request to the node and the right port

You need to make sure the proxy is configured with some authentication mechanism because the dashboard should not be exposed to the public.

Please let us know if that satisfies your use case or if not, what you are trying to achieve :)

**Comment by smdabdoub** [comment]
I get what appears to be the same error but with init_dashboard=False:

`ray.init(include_dashboard=False)
{'node_ip_address': '10.4.8.1', 'raylet_ip_address': '10.4.8.1', 'redis_address': '10.4.8.1:6379', 'object_store_address': '/tmp/ray/session_2023-04-27_16-06-18_692202_116464/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2023-04-27_16-06-18_692202_116464/sockets/raylet', 'webui_url': None, 'session_dir': '/tmp/ray/session_2023-04-27_16-06-18_692202_116464', 'metrics_export_port': 65062, 'node_id': '63562852c8b6d0cf6adf13771e84aab036ff1336'}
>>> 2023-04-27 16:06:36,946	WARNING worker.py:1034 -- The agent on node x.y.z failed with the following error:
Traceback (most recent call last):
  File "lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 306, in <module>
    loop.run_until_complete(agent.run())
  File "lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 131, in run
    modules = self._load_modules()
  File "lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 86, in _load_modules
    c = cls(self)
  File "lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 72, in __init__
    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)
  File "lib/python3.8/site-packages/ray/metrics_agent.py", line 40, in __init__
    prometheus_exporter.new_stats_exporter(
  File "lib/python3.8/site-packages/ray/prometheus_exporter.py", line 333, in new_stats_exporter
    exporter = PrometheusStatsExporter(
  File "lib/python3.8/site-packages/ray/prometheus_exporter.py", line 266, in __init__
    self.serve_http()
  File "lib/python3.8/site-packages/ray/prometheus_exporter.py", line 320, in serve_http
    start_http_server(
  File "lib/python3.8/site-packages/prometheus_client/exposition.py", line 169, in start_wsgi_server
    TmpServer.address_family, addr = _get_best_family(addr, port)
  File "lib/python3.8/site-packages/prometheus_client/exposition.py", line 158, in _get_best_family
    infos = socket.getaddrinfo(address, port)
  File "lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

(pid=raylet) Traceback (most recent call last):
(pid=raylet)   File "lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 317, in <module>
(pid=raylet)     raise e
(pid=raylet)   File "lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 306, in <module>
(pid=raylet)     loop.run_until_complete(agent.run())
(pid=raylet)   File "lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
(pid=raylet)     return future.result()
(pid=raylet)   File "lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 131, in run
(pid=raylet)     modules = self._load_modules()
(pid=raylet)   File "lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 86, in _load_modules
(pid=raylet)     c = cls(self)
(pid=raylet)   File "lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 72, in __init__
(pid=raylet)     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)
(pid=raylet)   File "lib/python3.8/site-packages/ray/metrics_agent.py", line 40, in __init__
(pid=raylet)     prometheus_exporter.new_stats_exporter(
(pid=raylet)   File "lib/python3.8/site-packages/ray/prometheus_exporter.py", line 333, in new_stats_exporter
(pid=raylet)     exporter = PrometheusStatsExporter(
(pid=raylet)   File "lib/python3.8/site-packages/ray/prometheus_exporter.py", line 266, in __init__
(pid=raylet)     self.serve_http()
(pid=raylet)   File "lib/python3.8/site-packages/ray/prometheus_exporter.py", line 320, in serve_http
(pid=raylet)     start_http_server(
(pid=raylet)   File "lib/python3.8/site-packages/prometheus_client/exposition.py", line 169, in start_wsgi_server
(pid=raylet)     TmpServer.address_family, addr = _get_best_family(addr, port)
(pid=raylet)   File "lib/python3.8/site-packages/prometheus_client/exposition.py", line 158, in _get_best_family
(pid=raylet)     infos = socket.getaddrinfo(address, port)
(pid=raylet)   File "lib/python3.8/socket.py", line 918, in getaddrinfo
(pid=raylet)     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
(pid=raylet) socket.gaierror: [Errno -2] Name or service not known`
