### ISSUE TITLE
[Windows,Core] (De)serialization fails on Windows

### ISSUE THREAD

**Issue by fehrin** [ray-project/ray#28446]
### What happened + What you expected to happen

1. (de)serialization with registered (de)serializers works on Linux but fails on Windows.
    The error on Windows is
    FileNotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ram://008a291b-1a52-4b98-b858-68fd80866136/variables/variables
    You may be trying to load on a different device from the computational device. Consider setting the `experimental_io_device` option in `tf.saved_model.LoadOptions` to the io_device such as '/job:localhost'.
2. (de)serialization with registered (de)serializers should work on Windows too.
3. The attached Python script will raise the FileNotFoundError when run on Windows.
    With explicit serialization Windows runs OK.

### Versions / Dependencies

OK: Ubuntu 20.04 Python 3.10.7 ray 2.0.0
KO: Windows 10 20H2 Python 3.10.7 ray 2.0.0

### Reproduction script

[single_model_deploy.zip](https://github.com/ray-project/ray/files/9549337/single_model_deploy.zip)

### Issue Severity

High: It blocks me from completing my task.

**Comment by mattip** [comment]
Here is the reproducer script

<details><summary>`single_model_deploy.py`</summary>

```
import io
import time

import h5py
import numpy as np
import pandas as pd
import ray
import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras import Model, layers
from tensorflow.keras.models import load_model
from tensorflow.python.keras.models import Functional


def serialize_model(model: Model):
    bytes_file = io.BytesIO()
    with h5py.File(bytes_file, "w") as f:
        model.save(filepath=f, save_format="tf")
    return bytes_file.getvalue()


def deserialize_model(b: bytes) -> Model:
    stream = io.BytesIO(b)
    h5 = h5py.File(stream, "r")
    return load_model(h5)


@ray.remote(num_gpus=1, num_cpus=1)
class Model:
    def __init__(self, inputs, outputs):
        self._model = None
        self._inputs = inputs
        self._outputs = outputs

    def create_model(self):
        inputs = keras.Input(shape=(len(self._inputs),))
        dense_1 = layers.Dense(10, activation="selu")(inputs)
        dense_2 = layers.Dense(10, activation="selu")(dense_1)
        output = layers.Dense(len(self._outputs), activation="linear")(dense_2)

        self._model = tf.keras.Model(inputs=[inputs], outputs=[output])
        self._model.compile(optimizer="Adam", loss="mse")

    def predict(self, data):
        return self._model.predict(data[self._inputs])

    def train(self, data):
        self._model.fit(data[self._inputs], data[self._outputs], epochs=100)

    def deploy(self):
        # return serialize_model(self._model)
        return self._model


if __name__ == "__main__":
    data = pd.DataFrame()
    data["input_1"] = np.random.uniform(low=0.5, high=13.3, size=(100,))
    data["input_2"] = np.random.uniform(low=-2, high=48, size=(100,))
    data["input_3"] = np.random.uniform(low=0, high=1, size=(100,))
    data["output_1"] = data["input_1"] * data["input_3"] - data["input_2"]

    # connect to ray cluster
    # ray.init(address='127.0.0.1:6379')
    ray.init(num_gpus=1, num_cpus=1)

    ray.util.register_serializer(
        Functional, serializer=serialize_model, deserializer=deserialize_model
    )

    # create remote actor
    model = Model.remote(inputs=["input_1", "input_2", "input_3"], outputs=["output_1"])

    # call create model on actor

    model.create_model.remote()

    model.train.remote(data)

    future = model.predict.remote(data)

    preds = ray.get(future).flatten()
    print("Max absolute error:")
    print(np.max(np.abs(preds - data["output_1"])))

    # tf_model = deserialize_model(ray.get(model.deploy.remote()))
    tf_model = ray.get(model.deploy.remote())

    tf_model.save("model")

    ray.shutdown()
```

</details>

> With explicit serialization Windows runs OK.

I am not sure what you mean by this.

**Comment by mattip** [comment]
Can reproduce, on linux it successfully completes and on windows + latest HEAD, the epoch trains and then I get a different error:
```
TypeError: cannot pickle 'weakref' object
```

<details><summary>traceback</summary>

```
(Model pid=14036) 1/4 [======>.......................] - ETA: 0s - loss: 5.0464
(Model pid=14036) 4/4 [==============================] - 0s 0s/step - loss: 4.3520
Max absolute error:
5.778376412142869
Traceback (most recent call last):
  File "\temp\issue28446.py", line 86, in <module>
    tf_model = ray.get(model.deploy.remote())
  File "d:\ray_dev\python\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "d:\ray_dev\python\ray\_private\worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::Model.deploy() (pid=14036, ip=127.0.0.1, repr=<issue28446.Model object at 0x00000255829FEC70>)
  File "python\ray\_raylet.pyx", line 904, in ray._raylet.execute_task
    with core_worker.profile_event(b"task:store_outputs"):
  File "python\ray\_raylet.pyx", line 941, in ray._raylet.execute_task
    core_worker.store_task_outputs(
  File "python\ray\_raylet.pyx", line 2447, in ray._raylet.CoreWorker.store_task_outputs
    serialized_object = context.serialize(output)
  File "d:\ray_dev\python\ray\_private\serialization.py", line 450, in serialize
    return self._serialize_to_msgpack(value)
  File "d:\ray_dev\python\ray\_private\serialization.py", line 428, in _serialize_to_msgpack
    pickle5_serialized_object = self._serialize_to_pickle5(
  File "d:\ray_dev\python\ray\_private\serialization.py", line 390, in _serialize_to_pickle5
    raise e
  File "d:\ray_dev\python\ray\_private\serialization.py", line 385, in _serialize_to_pickle5
    inband = pickle.dumps(
  File "d:\ray_dev\python\ray\cloudpickle\cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "d:\ray_dev\python\ray\cloudpickle\cloudpickle_fast.py", line 627, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'weakref' object
```

</details>
<details><summary>pip list</summary>

```
>pip list
Package                      Version             Editable project location
---------------------------- ------------------- ----------------------------
absl-py                      0.15.0
aiohttp                      3.7.4.post0
aiohttp-cors                 0.7.0
aioredis                     1.3.1
aiorwlock                    1.2.0
aiosignal                    1.2.0
ale-py                       0.7.5
ansicon                      1.89.0
anyio                        3.4.0
asgiref                      3.4.1
astunparse                   1.6.3
async-timeout                3.0.1
atomicwrites                 1.4.0
attrs                        21.2.0
AutoROM                      0.4.2
AutoROM.accept-rom-license   0.4.2
beautifulsoup4               4.9.3
blessed                      1.19.0
blessings                    1.7
cachetools                   4.2.2
certifi                      2021.5.30
cffi                         1.15.1
chardet                      4.0.0
charset-normalizer           2.0.4
click                        8.0.1
cloudpickle                  2.0.0
colorama                     0.4.4
colorful                     0.5.4
Cython                       0.29.30
distlib                      0.3.4
dm-tree                      0.1.6
fastapi                      0.70.1
filelock                     3.6.0
flatbuffers                  1.12
frozenlist                   1.2.0
gast                         0.4.0
glfw                         2.5.3
google                       3.0.0
google-api-core              1.31.2
google-auth                  1.35.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
googleapis-common-protos     1.53.0
gpustat                      1.0.0
GPUtil                       1.4.0
grpcio                       1.34.1
gym                          0.24.1
gym-notices                  0.0.5
h11                          0.12.0
h5py                         3.1.0
hiredis                      2.0.0
idna                         3.2
imageio                      2.16.1
importlib-metadata           4.11.2
importlib-resources          5.8.0
iniconfig                    1.1.1
jinxed                       1.1.0
jsonschema                   3.2.0
keras                        2.9.0
keras-nightly                2.5.0.dev2021032900
Keras-Preprocessing          1.1.2
libclang                     14.0.1
lockfile                     0.12.2
lz4                          4.0.1
Markdown                     3.3.7
msgpack                      1.0.2
multidict                    5.1.0
networkx                     2.7.1
numpy                        1.19.5
nvidia-ml-py                 11.495.46
oauthlib                     3.2.0
opencensus                   0.7.13
opencensus-context           0.1.2
opencv-python                4.6.0.66
opt-einsum                   3.3.0
packaging                    21.0
pandas                       1.4.1
Pillow                       9.0.1
pip                          22.3.1
platformdirs                 2.5.1
pluggy                       1.0.0
prometheus-client            0.11.0
protobuf                     3.17.3
psutil                       5.8.0
py                           1.11.0
py-spy                       0.3.8
pyarrow                      9.0.0
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pycparser                    2.21
pydantic                     1.8.2
pygame                       2.1.0
pyglet                       1.5.22
pyparsing                    2.4.7
pyrsistent                   0.18.0
pytest                       6.2.5
pytest-runner                5.3.1
python-dateutil              2.8.2
pytz                         2021.1
PyWavelets                   1.2.0
PyYAML                       5.4.1
ray                          3.0.0.dev0          d:\ray_dev\python
redis                        3.5.0
requests                     2.26.0
requests-oauthlib            1.3.1
rsa                          4.7.2
scikit-image                 0.19.2
scipy                        1.8.0
setuptools                   41.2.0
six                          1.15.0
smart-open                   5.2.1
sniffio                      1.2.0
soupsieve                    2.2.1
starlette                    0.16.0
tabulate                     0.8.9
tensorboard                  2.9.1
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorboardX                 2.5
tensorflow                   2.5.0
tensorflow-estimator         2.5.0
tensorflow-io-gcs-filesystem 0.26.0
termcolor                    1.1.0
tifffile                     2022.2.9
toml                         0.10.2
torch                        1.9.0
tqdm                         4.64.0
typing-extensions            3.7.4.3
urllib3                      1.26.6
uvicorn                      0.16.0
virtualenv                   20.13.3
wcwidth                      0.2.5
Werkzeug                     2.1.2
wheel                        0.37.1
wrapt                        1.12.1
yarl                         1.6.3
zipp                         3.7.0
```

</details>

**Comment by fehrin** [comment]
This error occurs inside Tensorflow and is present up to and including version 2.10.1. With Tensorflow version 2.11 it is gone now. Implicit (de)serialization (as in the attached example) now works on Windows too. It would be interesting if this is (was) a Tensorflow problem tracked by some Tensorflow (github) issue.

**Comment by fehrin** [comment]
> This error occurs inside Tensorflow and is present up to and including version 2.10.1. With Tensorflow version 2.11 it is gone now. Implicit (de)serialization (as in the attached example) now works on Windows too. It would be interesting if this is (was) a Tensorflow problem tracked by some Tensorflow (github) issue.

I used ray version 2.2 with Python 3.10.9 to check and verify this (on Windows).

**Comment by fehrin** [comment]
@mattip 
"With explicit serialization Windows runs OK. I am not sure what you mean by this."
This means activating the commented away lines
# return serialize_model(self._model)
and
# tf_model = deserialize_model(ray.get(model.deploy.remote()))

**Comment by mattip** [comment]
> This error occurs inside Tensorflow and is present up to and including version 2.10.1. With Tensorflow version 2.11 it is gone now.

Good to hear. Closing. Please open a new issue if needed.
