### ISSUE TITLE
LD_LIBRARY_PATH not set on workers on different machine.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#285]
Starting Ray on a cluster of 3 nodes (Ubuntu 16), I encountered the following.

```python
import ray
import os

ray.init(redis_address="...")

@ray.remote
def f():
  node_ip_address = ray.services.get_node_ip_address()
  if "LD_LIBRARY_PATH" in os.environ:
    return os.environ["LD_LIBRARY_PATH"], node_ip_address
  return "", node_ip_address

results = ray.get([f.remote() for _ in range(1000)])
```

Then `set(results)` looked something like this

```
{('', '172.31.16.145'),
 ('', '172.31.29.31'),
 ('/usr/local/lib64:/usr/local/lib64::/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_', '172.31.38.127')}
```

So locally the `LD_LIBRARY_PATH` was set for each worker, but on the remote machines it was not.

The reason is that parallel-ssh does not run `source ~/.bashrc` so a bunch of environment variables are not set. We should change the cluster documentation instructions to run `source ~/.bashrc` in the script that starts Ray on the workers.

By the way, the symptom of this problem was that a remote function definition failed to be defined on the workers on the remote machines because it needed something on the `LD_LIBRARY_PATH`. The actual error message (when defining the remote function) was something like

```python
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/ray-0.0.1-py2.7.egg/ray/worker.py", line 1022, in fetch_and_register_remote_function
    function = pickling.loads(serialized_function)
  File "/usr/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
  File "build/bdist.linux-x86_64/egg/cloudpickle/cloudpickle.py", line 717, in subimport
    __import__(name)
  File "/home/ubuntu/dex-net/deps/meshpy/meshpy/__init__.py", line 1, in <module>
    import meshrender
ImportError: libboost_numpy.so: cannot open shared object file: No such file or directory
```

Note: I just tried starting Ray on the non-head nodes by using

```
parallel-ssh -h workers.txt -P -I < start_worker.sh
```

where `start_worker.sh` manually sets the `LD_LIBRARY_PATH` via

```
export LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib64::/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_
ray/scripts/start_ray.sh --num-workers=40 --redis-address=172.31.38.127:6666
```

and that solved the problem.

However, if instead of manually setting `LD_LIBRARY_PATH`, I instead do `source /home/ubuntu/.bashrc`, that somehow does not help. I'm not sure why.

**Comment by robertnishihara** [comment]
FYI @jssmith, I would have thought that adding `source /home/ubuntu/.bashrc` to the `start_worker.sh` script would solve the problem.

**Comment by robertnishihara** [comment]
Closing because this is a special case of #418.
