### ISSUE TITLE
[Ray: Core] - Unable to enable TLS on the ray head node

### ISSUE THREAD

**Issue by praveenblr32** [ray-project/ray#28534]
### What happened + What you expected to happen

On enabling the TLS on the ray cluster as per the ray documentation https://docs.ray.io/en/latest/ray-core/configure.html#tls-authentication,the ray cluster fails to start with the below error

```
2022-09-13 00:42:05,840 INFO usage_lib.py:452 -- Usage stats collection is disabled.
2022-09-13 00:42:05,841 INFO scripts.py:719 -- Local node IP: 10.10.xx.xxx
Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 2588, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/cli_logger.py", line 852, in wrapper
    return f(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 746, in start
    node = ray._private.node.Node(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/node.py", line 271, in __init__
    self.start_head_processes()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/node.py", line 1055, in start_head_processes
    self._write_cluster_info_to_kv()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/node.py", line 1039, in _write_cluster_info_to_kv
    ray_usage_lib.put_cluster_metadata(self.get_gcs_client())
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/usage/usage_lib.py", line 538, in put_cluster_metadata
    gcs_client.internal_kv_put(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/gcs_utils.py", line 177, in wrapper
    return f(self, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/gcs_utils.py", line 296, in internal_kv_put
    reply = self._kv_stub.InternalKVPut(req, timeout=timeout)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1663054930.890563045","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1663054930.890561882","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
command terminated with exit code 1
Exception in thread Thread-2:
Traceback (most recent call last):
```

Note: If TLS is disabled RAY_USE_TLS: '0', everything works fine.

### Versions / Dependencies

ray: 2.0.0
Python: 3.8.5

### Reproduction script

import os
import ray

os.environ["RAY_USE_TLS"] = "1"
os.environ["RAY_TLS_SERVER_CERT"] = "/cert/localhost.crt"
os.environ["RAY_TLS_SERVER_KEY"] = "/cert/localhost.key"
os.environ["RAY_TLS_CA_CERT"] = "/rootCA.crt"
RAY_HOST = "localhost"

info = ray.init()

### Issue Severity

High: It blocks me from completing my task.

**Comment by kristof9851** [comment]
Check that the TLS certificate you have also has the following in the SAN list:
- "DNS:localhost"
- "IP Address:127.0.0.1"
- "IP Address:$POD_IP" (where $POD_IP is ie.: 100.70.80.123)

**Comment by rickyyx** [comment]
@praveenblr32 sorry for the late response, but were you able to check the certificate as suggested above? If having those added to the certs work?

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
