### ISSUE TITLE
[AIR/Tune] [Windows] Wandb fails when running on a non C drive

### ISSUE THREAD

**Issue by c-phillips** [ray-project/ray#28542]
### The Bug
WandB integration fails when you run your script from another drive letter. It doesn't matter where you put the `api_key_file` or if you use the `api_key` directly, it will still fail when running your main script from a non-C drive

### Expected Behavior
WandB should initialize and start logging metrics returned from Tuner

### Useful Information
Error Log:
```
Traceback (most recent call last):
  File "C:\Users\colli\miniconda3\envs\raylearn\lib\site-packages\wandb\sdk\wandb_init.py", line 1040, in init
    wi.setup(kwargs)
  File "C:\Users\colli\miniconda3\envs\raylearn\lib\site-packages\wandb\sdk\wandb_init.py", line 151, in setup
    self._wl = wandb_setup.setup()
  File "C:\Users\colli\miniconda3\envs\raylearn\lib\site-packages\wandb\sdk\wandb_setup.py", line 320, in setup
    ret = _setup(settings=settings)
  File "C:\Users\colli\miniconda3\envs\raylearn\lib\site-packages\wandb\sdk\wandb_setup.py", line 315, in _setup
    wl = _WandbSetup(settings=settings)
  File "C:\Users\colli\miniconda3\envs\raylearn\lib\site-packages\wandb\sdk\wandb_setup.py", line 301, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "C:\Users\colli\miniconda3\envs\raylearn\lib\site-packages\wandb\sdk\wandb_setup.py", line 108, in __init__
    self._settings = self._settings_setup(settings, self._early_logger)
  File "C:\Users\colli\miniconda3\envs\raylearn\lib\site-packages\wandb\sdk\wandb_setup.py", line 138, in _settings_setup
    s._infer_run_settings_from_environment(_logger=early_logger)
  File "C:\Users\colli\miniconda3\envs\raylearn\lib\site-packages\wandb\sdk\wandb_settings.py", line 1426, in _infer_run_settings_from_environment
    program_relpath = self.program_relpath or _get_program_relpath_from_gitrepo(
  File "C:\Users\colli\miniconda3\envs\raylearn\lib\site-packages\wandb\sdk\wandb_settings.py", line 146, in _get_program_relpath_from_gitrepo
    relative_path = os.path.relpath(full_path_to_program, start=root)
  File "C:\Users\colli\miniconda3\envs\raylearn\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'D:', start on mount 'C:'
wandb: ERROR Abnormal program exit
```

### Versions / Dependencies

Ray 2.0.0
WandB 0.13.2
Python 3.9.13
PettingZoo 1.20.1

### Reproduction script

Run from `C:` - works
Run from `D:` - doesn't work

```
from ray import air, tune
from ray.tune.registry import register_env
from ray.rllib.env.wrappers.pettingzoo_env import PettingZooEnv
from pettingzoo.mpe import simple_spread_v2
from ray.air.callbacks.wandb import WandbLoggerCallback

# Based on code from github.com/parametersharingmadrl/parametersharingmadrl

if __name__ == "__main__":

    register_env("simple_spread", lambda _: PettingZooEnv(simple_spread_v2.env()))

    tune.Tuner(
        "PPO",
        run_config=air.RunConfig(
            stop={"episodes_total": 60000},
            checkpoint_config=air.CheckpointConfig(
                checkpoint_frequency=10,
            ),
            callbacks=[WandbLoggerCallback(
                project = "ray_test",
                api_key_file = "C:\\Users\\colli\\wandb_api_key.txt",
                log_config = True,
            )],
        ),
        param_space={
            # Enviroment specific.
            "env": "simple_spread",

            # General
            "framework":"torch",
            # "num_gpus": 0.01,
            "num_gpus":1,
            "num_workers": 20,
            # "num_gpus_per_worker": (1-0.01)/22,
            "num_envs_per_worker": 1,
            "compress_observations": True,

            # Algorithm Specific
            "lambda": 0.99,
            "train_batch_size": 512,
            "sgd_minibatch_size": 32,
            "num_sgd_iter": 5,
            "batch_mode": "truncate_episodes",
            "entropy_coeff": 0.01,
            "lr": 2e-5,

            #Multiagent
            "multiagent": {
                "policies": {"shared_policy"},
                "policy_mapping_fn": (
                    lambda agent_id, episode, **kwargs: "shared_policy"
                ),
            },
        },
    ).fit()
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by richardliaw** [comment]
hey there; my guess from the stacktrace is that this might a wandb issue? let me ping them to see if they have any ideas.

**Comment by mattip** [comment]
This seems to be a known problem with wandb, see the issue I linked above. There is also wandb/wandb#1991 which was closed (stale?) and has some work-arounds. I think this should be fixed by wandb, there is not much ray can do.

**Comment by mattip** [comment]
@richardliaw can we close this as an wandb problem?

**Comment by mattip** [comment]
Closing. Please reopen if there is something actionable for ray.
