### ISSUE TITLE
[core] All long-running release tests that use a local Ray cluster are failing

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#28559]
### What happened + What you expected to happen

long_running_* tests create a local Ray cluster and are failing:

```python
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/node.py", line 316, in __init__
    self.redis_password,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 385, in wait_for_node
    raise TimeoutError("Timed out while waiting for node to startup.")
TimeoutError: Timed out while waiting for node to startup.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "workloads/many_tasks_serialized_ids.py", line 49, in <module>
    dashboard_host="0.0.0.0",
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/cluster_utils.py", line 224, in add_node
    spawn_reaper=self._shutdown_at_exit,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/node.py", line 320, in __init__
```

### Versions / Dependencies

Last good commit: 9ff23cd6224a39254048738fcc469289df387d08
First bad commit: 71bb155c5568e693c6f06a9392889ce4085c7750

### Reproduction script

long_running_* tests

**Comment by stephanie-wang** [comment]
Note, this appears to be an issue with testing infrastructure, not OSS-related change.

**Comment by rickyyx** [comment]
Yes, confirmed that test is working after I run `unset RAY_RAYLET_NODE_ID` - so this is the same root cause as #28562

**Comment by rickyyx** [comment]
I am creating a PR that explicitly unsets this variable for these long running nightly tests before product PR is rollout as a mitigation.
