### ISSUE TITLE
[core] microbenchmark_staging release test is failing from ValueError

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#28560]
### What happened + What you expected to happen

Test fails with:

```python
Traceback (most recent call last):
  File "run_microbenchmark.py", line 16, in <module>
    results = main() or []
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/ray_perf.py", line 279, in main
    ray.init(resources={"custom": 100})
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py", line 1419, in init
    head=True, shutdown_at_exit=False, spawn_reaper=True, ray_params=ray_params
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/node.py", line 309, in __init__
    self.start_ray_processes()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/node.py", line 1121, in start_ray_processes
    self.start_raylet(plasma_directory, object_store_memory)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/node.py", line 982, in start_raylet
    node_name=self._ray_params.node_name,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 1538, in start_raylet
    static_resources = resource_spec.to_resource_dict()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/resource_spec.py", line 120, in to_resource_dict
    "Violated by resource '{}' in {}.".format(resource_label, resources)
ValueError: Resource quantities must all be whole numbers. Violated by resource 'memory' in {'custom': 100, 'node:172.31.73.9': 1.0, 'CPU': 57, 'memory': 177372328550.4, 'object_store_memory': 55759759769.6}.
```

### Versions / Dependencies

Last good commit: 38d87c281b1424a365ee8a23a50a6ec0db5777c8
First bad commit: 71bb155c5568e693c6f06a9392889ce4085c7750

### Reproduction script

microbenchmark_staging test

**Comment by scv119** [comment]
@wuisawesome is it possible https://github.com/ray-project/ray/commit/d8dc04c3aa759c9d4d0d1e99b011b9a64cea2166 leads to this test failure? if this is the case can you suggest the fix?

**Comment by stephanie-wang** [comment]
Test is still failing. @wuisawesome can we revert this PR?

**Comment by wuisawesome** [comment]
> @wuisawesome can we revert this PR?

Looks like @scv119 is on it already. https://github.com/ray-project/ray/pull/28620 should also fix it, but i'm fine reverting first if that's faster

**Comment by wuisawesome** [comment]
Shall we just roll forward and merge https://github.com/ray-project/ray/pull/28620 since it's ready?
