### ISSUE TITLE
[P0] test_submit_cpp_job  failed in osx

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#28592]
### What happened + What you expected to happen

https://buildkite.com/ray-project/ray-builders-branch/builds/9913#01834e45-3eb1-498b-ac67-d757a80716fa

failed with following errors:

```


E       RuntimeError: The condition wasn't met before the timeout expired. Last exception: Traceback (most recent call last):
--
  | E         File "/Users/ec2-user/.buildkite-agent/builds/bk-mac1-branch-queue-i-06406ef93431cdb87-1/ray-project/ray-builders-branch/python/ray/_private/test_utils.py", line 364, in wait_for_condition
  | E           if condition_predictor(**kwargs):
  | E         File "/private/var/tmp/_bazel_ec2-user/405b8ad868e964bae5b383059d2491f9/execroot/com_github_ray_project_ray/bazel-out/darwin-opt/bin/cpp/test_submit_cpp_job.runfiles/com_github_ray_project_ray/cpp/test_submit_cpp_job.py", line 34, in _check_job_succeeded
  | E           raise RuntimeError(f"Job failed\nlogs:\n{logs}")
  | E       RuntimeError: Job failed
  | E       logs:
  | E       [2022-09-18 18:41:06,376 I 64531 974221] config_internal.cc:192: No code search path found yet. The program location path "/private/tmp/ray/session_2022-09-18_18-40-51_379388_64485/runtime_resources/working_dir_files/_ray_pkg_3f8338c889eed8db/." will be added for searching dynamic libraries by default. And you can add some search paths by '--ray_code_search_path'
  | E       [2022-09-18 18:41:11,379 E 64531 974221] gcs_rpc_client.h:202: Failed to connect to GCS at address 10.0.2.52:62047 within 5 seconds.
  | E       [2022-09-18 18:42:06,692 C 64531 974225] gcs_rpc_client.h:538:  Check failed: absl::ToInt64Seconds(absl::Now() - gcs_last_alive_time_) < ::RayConfig::instance().gcs_rpc_server_reconnect_timeout_s() Failed to connect to GCS within 60 seconds


```

### Versions / Dependencies

master

### Reproduction script

run test

### Issue Severity

High: It blocks me from completing my task.

**Comment by scv119** [comment]
@Catch-Bull can you help take a look? this test might be flaky for a while.

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
