### ISSUE TITLE
[<Ray component: Core|RLlib|etc...>] 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#28716]
### What happened + What you expected to happen

Test failing - a direct traceback on the exception thrown as below: 

```
Traceback (most recent call last):
  File "dataset/sort.py", line 165, in <module>
    raise exc
  File "dataset/sort.py", line 117, in <module>
    ds = ds.random_shuffle()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 798, in random_shuffle
    return Dataset(plan, self._epoch, self._lazy)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 217, in __init__
    self._plan.execute(allow_clear_input_blocks=False)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/plan.py", line 309, in execute
    blocks, clear_input_blocks, self._run_by_consumer
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/plan.py", line 756, in __call__
    blocks, clear_input_blocks, self.block_udf, self.ray_remote_args
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/stage_impl.py", line 118, in do_shuffle
    reduce_ray_remote_args=remote_args,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/shuffle.py", line 117, in execute
    new_metadata = reduce_bar.fetch_until_complete(list(new_metadata))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/progress_bar.py", line 75, in fetch_until_complete
    for ref, result in zip(done, ray.get(done)):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py", line 2279, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: [36mray::reduce()[39m (pid=1979, ip=172.31.64.202)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.ObjectFetchTimedOutError: Failed to retrieve object ae7580a8350a8021ffffffffffffffffffffffff0300000090010000. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.

Fetch for object ae7580a8350a8021ffffffffffffffffffffffff0300000090010000 timed out because no locations were found for the object. This may indicate a system-level bug.
```

There seems to be a seg fault in GCS: 

```

(raylet, ip=172.31.92.227) *** SIGSEGV received at time=1663811727 on cpu 14 ***
(raylet, ip=172.31.92.227) *** SIGSEGV received at time=1663811727 on cpu 11 ***
(pid=1768, ip=172.31.92.227) PC: @     0x7fb01c1021c0  (unknown)  absl::lts_20211102::Mutex::Lock()
(pid=1768, ip=172.31.92.227)     @     0x7fb01cfb2420       3504  (unknown)
(pid=1768, ip=172.31.92.227)     @     0x7fb01bb7ea5f        192  ray::gcs::NodeInfoAccessor::HandleNotification()
(pid=1768, ip=172.31.92.227)     @     0x7fb01bb1c84f         64  std::_Function_handler<>::_M_invoke()
(pid=1768, ip=172.31.92.227)     @     0x7fb01bb55535        176  std::_Function_handler<>::_M_invoke()
(pid=1768, ip=172.31.92.227)     @     0x7fb01bb7d580        112  ray::rpc::GcsRpcClient::GetAllNodeInfo()::{lambda()#2}::operator()()
(pid=1768, ip=172.31.92.227)     @     0x7fb01bb1e1d5         64  ray::rpc::ClientCallImpl<>::OnReplyReceived()
(pid=1768, ip=172.31.92.227)     @     0x7fb01b9e0e35         32  std::_Function_handler<>::_M_invoke()
(pid=1768, ip=172.31.92.227)     @     0x7fb01bca25c6         96  EventTracker::RecordExecution()
(pid=1769, ip=172.31.92.227) PC: @     0x7f3ca04741c0  (unknown)  absl::lts_20211102::Mutex::Lock()
(pid=1769, ip=172.31.92.227)     @     0x7f3ca1324420       3504  (unknown)
(pid=1769, ip=172.31.92.227)     @     0x7f3c9fef0a5f        192  ray::gcs::NodeInfoAccessor::HandleNotification()
(pid=1769, ip=172.31.92.227)     @     0x7f3c9fe8e84f         64  std::_Function_handler<>::_M_invoke()
(pid=1769, ip=172.31.92.227)     @     0x7f3c9fec7535        176  std::_Function_handler<>::_M_invoke()
(pid=1769, ip=172.31.92.227)     @     0x7f3c9feef580        112  ray::rpc::GcsRpcClient::GetAllNodeInfo()::{lambda()#2}::operator()()
(pid=1769, ip=172.31.92.227)     @     0x7f3c9fe901d5         64  ray::rpc::ClientCallImpl<>::OnReplyReceived()
(pid=1769, ip=172.31.92.227)     @     0x7f3c9fd52e35         32  std::_Function_handler<>::_M_invoke()
(pid=1769, ip=172.31.92.227)     @     0x7f3ca00145c6         96  EventTracker::RecordExecution()
(pid=1768, ip=172.31.92.227)     @     0x7fb01bc5ab8e         48  std::_Function_handler<>::_M_invoke()
(pid=1769, ip=172.31.92.227)     @     0x7f3c9ffccb8e         48  std::_Function_handler<>::_M_invoke()
(pid=1769, ip=172.31.92.227)     @     0x7f3c9ffccd06        112  boost::asio::detail::completion_handler<>::do_complete()
(pid=1768, ip=172.31.92.227)     @     0x7fb01bc5ad06        112  boost::asio::detail::completion_handler<>::do_complete()
(pid=1768, ip=172.31.92.227)     @     0x7fb01c0d3bab        128  boost::asio::detail::scheduler::do_run_one()
(pid=1769, ip=172.31.92.227)     @     0x7f3ca0445bab        128  boost::asio::detail::scheduler::do_run_one()
(pid=1768, ip=172.31.92.227)     @     0x7fb01c0d4de1        192  boost::asio::detail::scheduler::run()
(pid=1769, ip=172.31.92.227)     @     0x7f3ca0446de1        192  boost::asio::detail::scheduler::run()
(pid=1769, ip=172.31.92.227)     @     0x7f3ca0447050         64  boost::asio::io_context::run()
(pid=1768, ip=172.31.92.227)     @     0x7fb01c0d5050         64  boost::asio::io_context::run()
(pid=1768, ip=172.31.92.227)     @     0x7fb01ba4d86d        240  ray::core::CoreWorker::RunIOService()
(pid=1768, ip=172.31.92.227)     @     0x7fb01c200b70  (unknown)  execute_native_thread_routine
(pid=1768, ip=172.31.92.227)     @     0x56504c077060  (unknown)  (unknown)
(pid=1768, ip=172.31.92.227)     @     0x7fb01b9c0830  (unknown)  (unknown)
(pid=1768, ip=172.31.92.227)     @ 0x9000840361e90789  (unknown)  (unknown)
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,600 E 1768 1803] logging.cc:361: *** SIGSEGV received at time=1663811727 on cpu 11 ***
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,601 E 1768 1803] logging.cc:361: PC: @     0x7fb01c1021c0  (unknown)  absl::lts_20211102::Mutex::Lock()
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,601 E 1768 1803] logging.cc:361:     @     0x7fb01cfb2420       3504  (unknown)
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,601 E 1768 1803] logging.cc:361:     @     0x7fb01bb7ea5f        192  ray::gcs::NodeInfoAccessor::HandleNotification()
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,601 E 1768 1803] logging.cc:361:     @     0x7fb01bb1c84f         64  std::_Function_handler<>::_M_invoke()
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,601 E 1768 1803] logging.cc:361:     @     0x7fb01bb55535        176  std::_Function_handler<>::_M_invoke()
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,601 E 1768 1803] logging.cc:361:     @     0x7fb01bb7d580        112  ray::rpc::GcsRpcClient::GetAllNodeInfo()::{lambda()#2}::operator()()
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,601 E 1768 1803] logging.cc:361:     @     0x7fb01bb1e1d5         64  ray::rpc::ClientCallImpl<>::OnReplyReceived()
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,601 E 1768 1803] logging.cc:361:     @     0x7fb01b9e0e35         32  std::_Function_handler<>::_M_invoke()
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,601 E 1768 1803] logging.cc:361:     @     0x7fb01bca25c6         96  EventTracker::RecordExecution()
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,601 E 1768 1803] logging.cc:361:     @     0x7fb01bc5ab8e         48  std::_Function_handler<>::_M_invoke()
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,601 E 1768 1803] logging.cc:361:     @     0x7fb01bc5ad06        112  boost::asio::detail::completion_handler<>::do_complete()
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1768 1803] logging.cc:361:     @     0x7fb01c0d3bab        128  boost::asio::detail::scheduler::do_run_one()
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1768 1803] logging.cc:361:     @     0x7fb01c0d4de1        192  boost::asio::detail::scheduler::run()
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1768 1803] logging.cc:361:     @     0x7fb01c0d5050         64  boost::asio::io_context::run()
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1768 1803] logging.cc:361:     @     0x7fb01ba4d86d        240  ray::core::CoreWorker::RunIOService()
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1768 1803] logging.cc:361:     @     0x7fb01c200b70  (unknown)  execute_native_thread_routine
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1768 1803] logging.cc:361:     @     0x56504c077060  (unknown)  (unknown)
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,607 E 1768 1803] logging.cc:361:     @     0x7fb01b9c0830  (unknown)  (unknown)
(pid=1768, ip=172.31.92.227) [2022-09-21 18:55:27,608 E 1768 1803] logging.cc:361:     @ 0x9000840361e90789  (unknown)  (unknown)
(pid=1768, ip=172.31.92.227) Fatal Python error: Segmentation fault
(pid=1768, ip=172.31.92.227) 
(pid=1769, ip=172.31.92.227)     @     0x7f3c9fdbf86d        240  ray::core::CoreWorker::RunIOService()
(pid=1769, ip=172.31.92.227)     @     0x7f3ca0572b70  (unknown)  execute_native_thread_routine
(pid=1769, ip=172.31.92.227)     @     0x5589fd829060  (unknown)  (unknown)
(pid=1769, ip=172.31.92.227)     @     0x7f3c9fd32830  (unknown)  (unknown)
(pid=1769, ip=172.31.92.227)     @ 0x9000840361e90789  (unknown)  (unknown)
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,601 E 1769 1804] logging.cc:361: *** SIGSEGV received at time=1663811727 on cpu 14 ***
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,601 E 1769 1804] logging.cc:361: PC: @     0x7f3ca04741c0  (unknown)  absl::lts_20211102::Mutex::Lock()
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1769 1804] logging.cc:361:     @     0x7f3ca1324420       3504  (unknown)
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1769 1804] logging.cc:361:     @     0x7f3c9fef0a5f        192  ray::gcs::NodeInfoAccessor::HandleNotification()
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1769 1804] logging.cc:361:     @     0x7f3c9fe8e84f         64  std::_Function_handler<>::_M_invoke()
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1769 1804] logging.cc:361:     @     0x7f3c9fec7535        176  std::_Function_handler<>::_M_invoke()
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1769 1804] logging.cc:361:     @     0x7f3c9feef580        112  ray::rpc::GcsRpcClient::GetAllNodeInfo()::{lambda()#2}::operator()()
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1769 1804] logging.cc:361:     @     0x7f3c9fe901d5         64  ray::rpc::ClientCallImpl<>::OnReplyReceived()
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1769 1804] logging.cc:361:     @     0x7f3c9fd52e35         32  std::_Function_handler<>::_M_invoke()
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1769 1804] logging.cc:361:     @     0x7f3ca00145c6         96  EventTracker::RecordExecution()
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1769 1804] logging.cc:361:     @     0x7f3c9ffccb8e         48  std::_Function_handler<>::_M_invoke()
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1769 1804] logging.cc:361:     @     0x7f3c9ffccd06        112  boost::asio::detail::completion_handler<>::do_complete()
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1769 1804] logging.cc:361:     @     0x7f3ca0445bab        128  boost::asio::detail::scheduler::do_run_one()
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1769 1804] logging.cc:361:     @     0x7f3ca0446de1        192  boost::asio::detail::scheduler::run()
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1769 1804] logging.cc:361:     @     0x7f3ca0447050         64  boost::asio::io_context::run()
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1769 1804] logging.cc:361:     @     0x7f3c9fdbf86d        240  ray::core::CoreWorker::RunIOService()
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,602 E 1769 1804] logging.cc:361:     @     0x7f3ca0572b70  (unknown)  execute_native_thread_routine
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,604 E 1769 1804] logging.cc:361:     @     0x5589fd829060  (unknown)  (unknown)
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,608 E 1769 1804] logging.cc:361:     @     0x7f3c9fd32830  (unknown)  (unknown)
(pid=1769, ip=172.31.92.227) [2022-09-21 18:55:27,610 E 1769 1804] logging.cc:361:     @ 0x9000840361e90789  (unknown)  (unknown)
(pid=1769, ip=172.31.92.227) Fatal Python error: Segmentation fault
(pid=1769, ip=172.31.92.227) 
```

### Versions / Dependencies

This test was not stable test though - but tracking here since segfaults sound bad enough.
Failure nightly commit: https://github.com/ray-project/ray/commit/45d7cd2f86d0eccdad632ac04514279f4d126106

### Reproduction script

Past runs: 
https://b534fd88.us1a.app.preset.io/superset/dashboard/p/AxJ0pb94Gr2/

**Comment by rickyyx** [comment]
cc @scv119

**Comment by rickyyx** [comment]
Looks like recent failures are more on worker died unexpectedly following a bunch of OOM killings:
https://b534fd88.us1a.app.preset.io/superset/dashboard/p/KO2WOeewLdP/

Spotchecked a few (most recent 3), with similar stacktraces: 
```
(raylet, ip=172.31.74.117) [2022-09-22 16:07:37,016 E 139 139] (raylet) node_manager.cc:2966: System memory low at node with IP 172.31.74.117. Used memory (54.98GB) / total capacity (57.60GB) (0.954554) exceeds threshold 0.95, killing latest task with name map() and task ID b3ec622a5e68fc5733289bd06b89452551597a3c03000000 to avoid running out of memory.
(raylet, ip=172.31.74.117) This may indicate a memory leak in a task or actor, or that too many tasks are running in parallel.
(raylet, ip=172.31.74.117) To find the highest memory consumers, use `ray logs raylet.out -ip 172.31.74.117`.
(raylet, ip=172.31.74.117) Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. To adjust the eviction threshold, set the environment variable `RAY_memory_usage_threshold_fraction` when starting Ray. To disable worker eviction, set the environment variable `RAY_memory_monitor_interval_ms` to zero.
...

Traceback (most recent call last):
  File "dataset/sort.py", line 165, in <module>
    raise exc
  File "dataset/sort.py", line 117, in <module>
    ds = ds.random_shuffle()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 798, in random_shuffle
    return Dataset(plan, self._epoch, self._lazy)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 217, in __init__
    self._plan.execute(allow_clear_input_blocks=False)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/plan.py", line 309, in execute
    blocks, clear_input_blocks, self._run_by_consumer
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/plan.py", line 756, in __call__
    blocks, clear_input_blocks, self.block_udf, self.ray_remote_args
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/stage_impl.py", line 118, in do_shuffle
    reduce_ray_remote_args=remote_args,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/shuffle.py", line 102, in execute
    shuffle_map_metadata = map_bar.fetch_until_complete(shuffle_map_metadata)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/progress_bar.py", line 75, in fetch_until_complete
    for ref, result in zip(done, ray.get(done)):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py", line 2281, in get
    raise value
ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
```
