### ISSUE TITLE
[Tune] HyperOptSearch fails with nested config dicts and points_to_evaluate

### ISSUE THREAD

**Issue by mgerstgrasser** [ray-project/ray#28753]
### What happened + What you expected to happen

When using HyperOptSearch together with (a) nested configuration dicts, as are commonly used in RLlib, and (b) some initial configurations to evaluate, Tune will fail after some number of some number of trials. Interestingly, not immediately though, it will run a number of trials before it crashed. Also removing the `points_to_evaluate` in the reproduction script below seems to make it run just fine for thousands of trials.

What makes things slightly worse is that for some reason on our cluster when this happens the Ray process won't exit, it will just hang, meaning the job will continue to block resources until manually killed. I can' reproduce this on my local machine though, here it just crashes and exits.

Update: Looks like BayesOptSearch also does not work with nested configuration dicts. See reproduction script below.

Error message for Hyperopt:
```
....
  File ".../lib/python3.10/site-packages/ray/tune/search/hyperopt/hyperopt_search.py", line 304, in suggest
    new_trials = self.algo(
  File ".../lib/python3.10/site-packages/hyperopt/tpe.py", line 927, in suggest
    observed_idxs_dict, observed_vals_dict = miscs_to_idxs_vals(
  File ".../lib/python3.10/site-packages/hyperopt/base.py", line 199, in miscs_to_idxs_vals
    t_idxs = misc["idxs"][node_id]
KeyError: 'nested_config/lr'
```

Error message for BayesOpt:
```
  
2022-09-25 13:25:39,394 ERROR trial_runner.py:1452 -- Trial lambda_1201e7f0: Error stopping trial.
Traceback (most recent call last):
  File ".../lib/python3.10/site-packages/bayes_opt/target_space.py", line 112, in _as_array
    x = np.asarray(x, dtype=float)
TypeError: float() argument must be a string or a real number, not 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../lib/python3.10/site-packages/bayes_opt/target_space.py", line 92, in params_to_array
    assert set(params) == set(self.keys)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../lib/python3.10/site-packages/ray/tune/execution/trial_runner.py", line 1442, in stop_trial
    self._search_alg.on_trial_complete(
  File ".../lib/python3.10/site-packages/ray/tune/search/search_generator.py", line 142, in on_trial_complete
    self.searcher.on_trial_complete(trial_id=trial_id, result=result, error=error)
  File ".../lib/python3.10/site-packages/ray/tune/search/bayesopt/bayesopt_search.py", line 358, in on_trial_complete
    self._register_result(params, result)
  File ".../lib/python3.10/site-packages/ray/tune/search/bayesopt/bayesopt_search.py", line 364, in _register_result
    self.optimizer.register(params, self._metric_op * result[self.metric])
  File ".../lib/python3.10/site-packages/bayes_opt/bayesian_optimization.py", line 108, in register
    self._space.register(params, target)
  File ".../lib/python3.10/site-packages/bayes_opt/target_space.py", line 159, in register
    x = self._as_array(params)
  File ".../lib/python3.10/site-packages/bayes_opt/target_space.py", line 114, in _as_array
    x = self.params_to_array(x)
  File ".../lib/python3.10/site-packages/bayes_opt/target_space.py", line 94, in params_to_array
    raise ValueError(
ValueError: Parameters' keys (['nested_config']) do not match the expected set of keys (['nested_config/lr']).
```

### Versions / Dependencies

ray==2.0.0
hyperopt==0.2.7

### Reproduction script

For HyperOptSearch
```
import ray
from ray import tune
from ray.air.config import RunConfig
from ray.tune.search.hyperopt import HyperOptSearch

ray.init(local_mode=False, num_cpus=4)

trainable = lambda config: {"fake_metric": 1.0}

config = {
    "nested_config": {
        "lr": tune.loguniform(1e-4, 1e-1),
    },
}

configs_to_try = [
    {
        "nested_config": {
            "lr": 0.008,
        },
    }
]

hyperopt_search = HyperOptSearch(metric="fake_metric", mode="max", points_to_evaluate=configs_to_try)
tune_config = tune.TuneConfig(mode="max", metric="fake_metric", num_samples=100000, search_alg=hyperopt_search)

tuner = tune.Tuner(
    trainable,
    param_space=config,
    run_config=RunConfig(name="test"),
    tune_config=tune_config,
)

results = tuner.fit()

```
For BayesOptSearch:
```
import ray
from ray import tune
from ray.air.config import RunConfig
from ray.tune.search.bayesopt import BayesOptSearch
from ray.tune.search.hyperopt import HyperOptSearch

ray.init(local_mode=False, num_cpus=4)

trainable = lambda config: {"fake_metric": 1.0}

config = {
    "nested_config": {
        "lr": tune.loguniform(1e-4, 1e-1),
    },
}

configs_to_try = [
    {
        "nested_config": {
            "lr": 0.008,
        },
    }
]

hyperopt_search = BayesOptSearch(metric="fake_metric", mode="max", points_to_evaluate=configs_to_try)
tune_config = tune.TuneConfig(mode="max", metric="fake_metric", num_samples=100000, search_alg=hyperopt_search)

tuner = tune.Tuner(
    trainable,
    param_space=config,
    run_config=RunConfig(name="test"),
    tune_config=tune_config,
)

results = tuner.fit()
```

### Issue Severity

High

**Comment by krfricke** [comment]
As a workaround for hyperopt, try this:

```
configs_to_try = [
    {
        "nested_config/lr": 0.008,
    }
]
```

hyperopt internally flattens the config names. I guess we should do this automatically within tune for preprocessing of the configs to try

**Comment by mgerstgrasser** [comment]
That does seem to fix it - thank you!!

**Comment by cszhu** [comment]
This P2 issue has seen no activity in the past 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please comment and remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!

**Comment by hongha912** [comment]
Fyi I encountered this bug again today with Ray 2.55. While I eventually found this issue and the workaround, it was frustrating when it happened.


## Versions / Dependencies

- ray 2.55.0
- bayesian-optimization 1.4.3 (installed via `ray[tune]`)
- Python 3.12, macOS

## Reproduction script (no cluster needed)

```python
import ray
from ray import tune
from ray.tune.search.bayesopt import BayesOptSearch

s = BayesOptSearch(metric="loss", mode="min", random_search_steps=1,
                   points_to_evaluate=[{"a": {"x": 0.5}}])       # nested warm-start point
# what tune.Tuner(param_space=...) injects internally at fit time:
s.set_search_properties("loss", "min", {"a": {"x": tune.uniform(0.0, 1.0)}})

tid = "trial_0"
print(s.suggest(tid))                            # -> {'a': {'x': 0.5}}  (works, dispatches)
s.on_trial_complete(tid, result={"loss": 0.25})  # ValueError: keys ['a'] != ['a/x']
```
