### ISSUE TITLE
[2.0.1][release] rllib learning/stress tests fail

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#28763]
https://buildkite.com/ray-project/release-tests-branch/builds/1053

There are a number of tests failing. At a quick glance it look like they may be due to the same root cause (unable to install environment).

- [rllib_learning_tests_a2c (30f2e58)](https://buildkite.com/ray-project/release-tests-branch/builds/1053#018375b1-6ff9-4aef-9c1a-59f37f6c1044)
- [rllib_learning_tests_a3c (30f2e58)](https://buildkite.com/ray-project/release-tests-branch/builds/1053#018375b1-b20c-44c7-a7fc-1ed0969efea4)
- [rllib_learning_tests_apex (30f2e58)](https://buildkite.com/ray-project/release-tests-branch/builds/1053#018375b1-ba65-46bc-b0b5-5741355eaf04)
- [rllib_learning_tests_appo (30f2e58)](https://buildkite.com/ray-project/release-tests-branch/builds/1053#018375b1-c372-4c9b-ad3a-000dc15afa42)
- [rllib_learning_tests_dqn (30f2e58)](https://buildkite.com/ray-project/release-tests-branch/builds/1053#018375b1-d122-48e3-b867-195ce076bef4)
- [rllib_learning_tests_impala (30f2e58)](https://buildkite.com/ray-project/release-tests-branch/builds/1053#018375b1-da51-4bbb-875f-bd4725bad560)
- [rllib_stress_tests (30f2e58)](https://buildkite.com/ray-project/release-tests-branch/builds/1053#018375b1-eac4-490a-bfd5-08b616e47062)

Example trace:
```
ray::Impala.__init__() (pid=4330, ip=172.31.70.78, repr=Impala)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py", line 312, in __init__
    super().__init__(config=config, logger_creator=logger_creator, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trainable/trainable.py", line 159, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/algorithms/impala/impala.py", line 548, in setup
    super().setup(config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py", line 447, in setup
    raise e.args[0].args[2]
ray.rllib.utils.error.EnvError: The env string you provided ('BeamRiderNoFrameskip-v4') is:
a) Not a supported/installed environment.
b) Not a tune-registered environment creator.
c) Not a valid env class string.

Try one of the following:
a) For Atari support: `pip install gym[atari] autorom[accept-rom-license]`.
   For VizDoom support: Install VizDoom
   (https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md) and
   `pip install vizdoomgym`.
   For PyBullet support: `pip install pybullet`.
b) To register your custom env, do `from ray import tune;
   tune.register('[name]', lambda cfg: [return env obj from here using cfg])`.
   Then in your config, do `config['env'] = [name]`.
c) Make sure you provide a fully qualified classpath, e.g.:
   `ray.rllib.examples.env.repeat_after_me_env.RepeatAfterMeEnv`

2022-09-25 10:52:52,990 ERROR trial_runner.py:987 -- Trial IMPALA_SpaceInvadersNoFrameskip-v4_c1166_00003: Error processing event.
ray.tune.error._TuneNoNextExecutorEventError: Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/execution/ray_trial_executor.py", line 996, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py", line 2282, in get
    raise value
  File "python/ray/_raylet.pyx", line 804, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 615, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 764, in ray._raylet.execute_task
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::Impala.__init__() (pid=4333, ip=172.31.70.78, repr=Impala)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 127, in __init__
    validate=trainer_config.get("validate_workers_after_construction"),
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 269, in add_workers
    self.foreach_worker(lambda w: w.assert_healthy())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 391, in foreach_worker
    remote_results = ray.get([w.apply.remote(func) for w in self.remote_workers()])
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=241, ip=172.31.70.209, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7eef20391f10>)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py", line 582, in make
    _check_version_exists(ns, name, version)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py", line 201, in _check_version_exists
    _check_name_exists(ns, name)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py", line 180, in _check_name_exists
    f"Environment {name} doesn't exist{namespace_msg}. {suggestion_msg}"
gym.error.NameNotFound: Environment SpaceInvadersNoFrameskip doesn't exist. 

During handling of the above exception, another exception occurred:

ray::RolloutWorker.__init__() (pid=241, ip=172.31.70.209, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7eef20391f10>)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 490, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/env/utils.py", line 52, in _gym_env_creator
    raise EnvError(ERR_MSG_INVALID_ENV_DESCRIPTOR.format(env_descriptor))
ray.rllib.utils.error.EnvError: The env string you provided ('SpaceInvadersNoFrameskip-v4') is:
a) Not a supported/installed environment.
b) Not a tune-registered environment creator.
c) Not a valid env class string.

Try one of the following:
a) For Atari support: `pip install gym[atari] autorom[accept-rom-license]`.
   For VizDoom support: Install VizDoom
   (https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md) and
   `pip install vizdoomgym`.
   For PyBullet support: `pip install pybullet`.
b) To register your custom env, do `from ray import tune;
   tune.register('[name]', lambda cfg: [return env obj from here using cfg])`.
   Then in your config, do `config['env'] = [name]`.
c) Make sure you provide a fully qualified classpath, e.g.:
   `ray.rllib.examples.env.repeat_after_me_env.RepeatAfterMeEnv`

During handling of the above exception, another exception occurred:

ray::Impala.__init__() (pid=4333, ip=172.31.70.78, repr=Impala)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py", line 312, in __init__
    super().__init__(config=config, logger_creator=logger_creator, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trainable/trainable.py", line 159, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/algorithms/impala/impala.py", line 548, in setup
    super().setup(config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py", line 447, in setup
    raise e.args[0].args[2]
ray.rllib.utils.error.EnvError: The env string you provided ('SpaceInvadersNoFrameskip-v4') is:
a) Not a supported/installed environment.
b) Not a tune-registered environment creator.
c) Not a valid env class string.

Try one of the following:
a) For Atari support: `pip install gym[atari] autorom[accept-rom-license]`.
   For VizDoom support: Install VizDoom
   (https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md) and
   `pip install vizdoomgym`.
   For PyBullet support: `pip install pybullet`.
b) To register your custom env, do `from ray import tune;
   tune.register('[name]', lambda cfg: [return env obj from here using cfg])`.
   Then in your config, do `config['env'] = [name]`.
c) Make sure you provide a fully qualified classpath, e.g.:
   `ray.rllib.examples.env.repeat_after_me_env.RepeatAfterMeEnv`
```

**Comment by matthewdeng** [comment]
@ArturNiederfahrenhorst looks like this is still failing in [2.0.1](https://buildkite.com/ray-project/release-tests-branch/builds/1070) and in [master](https://buildkite.com/ray-project/release-tests-branch/builds/1063). 

For #28703, is the important change `gym[atari]`? Should we be adding the `atari` extra in [requirements_rllib](https://github.com/ray-project/ray/blob/master/python/requirements/ml/requirements_rllib.txt#L7)?

**Comment by avnishn** [comment]
fix is here. pending release tests passing 

https://github.com/ray-project/ray/pull/28913#pullrequestreview-1126097194
