### ISSUE TITLE
[2.0.1][release] tune_cloud_gcp_k8s_durable_upload fails

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#28762]
https://buildkite.com/ray-project/release-tests-branch/builds/1053#018375b1-3f91-4918-a809-1ac6bcbb6097

```
Traceback (most recent call last):
--
  | File "workloads/run_cloud_test.py", line 1300, in <module>
  | raise err
  | File "workloads/run_cloud_test.py", line 1282, in <module>
  | remote_tune_script,
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
  | return getattr(ray, func.__name__)(*args, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/api.py", line 42, in get
  | return self.worker.get(vals, timeout=timeout)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 434, in get
  | res = self._get(to_get, op_timeout)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 462, in _get
  | raise err
  | types.RayTaskError(RuntimeError): ray::_run_test() (pid=980, ip=172.18.0.67)
  | File "workloads/run_cloud_test.py", line 1234, in _run_test
  | File "workloads/run_cloud_test.py", line 1170, in test_durable_upload
  | File "workloads/run_cloud_test.py", line 403, in run_resume_flow
  | File "workloads/run_cloud_test.py", line 1134, in after_experiments
  | File "workloads/run_cloud_test.py", line 693, in get_experiment_and_trial_data
  | File "workloads/run_cloud_test.py", line 577, in load_experiment_checkpoint_from_dir
  | RuntimeError: Trial with dirname fn_trainable_b9454_00000_0_score_multiplied=12_2022-09-25_10-37-29 not found.
```

**Comment by matthewdeng** [comment]
@krfricke looks like this has been failing on master as well - do you know if it's expected to be stable?

**Comment by amogkam** [comment]
@matthewdeng can you pick https://github.com/ray-project/ray/pull/28770
