### ISSUE TITLE
[RLlib] Decision Transformer training fails with GPU

### ISSUE THREAD

**Issue by antoine-galataud** [ray-project/ray#28849]
### What happened + What you expected to happen

Training DT on a GPU-based instance fails with following exception:

```
ray.exceptions.RayTaskError(ValueError): ray::DT.train() (pid=25558, ip=10.0.46.58, repr=DT)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 353, in train
    raise skip_exceptions(e) from None
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 351, in train
    result = self.step()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 670, in step
    ) = self._run_one_training_iteration_and_evaluation_in_parallel()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 2728, in _run_one_training_iteration_and_evaluation_in_parallel
    train_results, train_iter_ctx = train_future.result()
  File "/home/ray/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/ray/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/ray/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 2722, in <lambda>
    train_future = executor.submit(lambda: self._run_one_training_iteration())
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 2626, in _run_one_training_iteration
    num_recreated += self.try_recover_from_step_attempt(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 2423, in try_recover_from_step_attempt
    raise error
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 2621, in _run_one_training_iteration
    results = self.training_step()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/rllib/algorithms/dt/dt.py", line 302, in training_step
    train_results = multi_gpu_train_one_step(self, train_batch)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/rllib/execution/train_ops.py", line 176, in multi_gpu_train_one_step
    results = policy.learn_on_loaded_batch(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/rllib/policy/torch_policy_v2.py", line 741, in learn_on_loaded_batch
    tower_outputs = self._multi_gpu_parallel_grad_calc(device_batches)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/rllib/policy/torch_policy_v2.py", line 1209, in _multi_gpu_parallel_grad_calc
    raise output[0] from output[1]
ValueError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_addmm)
 tracebackTraceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/rllib/policy/torch_policy_v2.py", line 1103, in _worker
    self.loss(model, self.dist_class, sample_batch)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/rllib/algorithms/dt/dt_torch_policy.py", line 482, in loss
    preds = self.model.get_prediction(model_out, train_batch)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/rllib/algorithms/dt/dt_torch_model.py", line 191, in get_prediction
    output_embeds = self.transformer(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/rllib/models/torch/mingpt.py", line 289, in forward
    x, att = block(x, attention_masks=attention_masks)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/rllib/models/torch/mingpt.py", line 145, in forward
    x = x + self.mlpf(self.ln_2(x))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/rllib/models/torch/mingpt.py", line 140, in <lambda>
    self.mlpf = lambda x: m.dropout(m.c_proj(m.act(m.c_fc(x))))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
```

Possible fix: move model to cuda device. Instead of 

https://github.com/ray-project/ray/blob/27292c41242e1c98bbc8e5e6ea7dc10349e2cb3c/rllib/models/torch/mingpt.py#L140

Use

```python
def _fwd(x):
    _m = m.to(x.device)
    return _m.dropout(_m.c_proj(_m.act(_m.c_fc(x))))
self.mlpf = _fwd
```

### Versions / Dependencies

Ray nightly
Ubuntu 18.04
Python 3.8

### Reproduction script

Use `rllib train -f ./tuned_examples/dt/cartpole-v0-dt.yaml` (edit `num_gpus: 1`) on a GPU-based instance.

### Issue Severity

High: It blocks me from completing my task.

**Comment by sven1977** [comment]
Hey @antoine-galataud , thanks for filing this issue and sorry for the delay. Yes, it's indeed an error in the mingpt code.
Since the `self.mlp` is referenced inside the lambda (prior to being moved to the GPU by the encapsulating TorchPolicy), the model used in the lambda is still the CPU version.

This PR here fixes the issue:
https://github.com/ray-project/ray/pull/31297
