### ISSUE TITLE
Reduce Verbosity of RayGetErrors

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#2886]
### Describe the problem
Error messages should not require scrolling up multiple pages to identify the issue.

This occurs often in RLlib development.

**Comment by robertnishihara** [comment]
Can you give an example?

**Comment by richardliaw** [comment]
```
Created LogSyncer for /root/ray_results/default/A3C_PongDeterministic-v4_0_2018-09-15_07-14-47RrorV0 -> 
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 3/32 CPUs, 0/0 GPUs
Result logdir: /root/ray_results/default
RUNNING trials:
 - A3C_PongDeterministic-v4_0:	RUNNING

Result for A3C_PongDeterministic-v4_0:
  date: 2018-09-15_07-15-17
  done: false
  episode_len_mean: .nan
  episode_reward_max: .nan
  episode_reward_mean: .nan
  episode_reward_min: .nan
  episodes: 0
  experiment_id: 487bcb55b6274d0f974df6e74b1fd648
  hostname: d73a20fb732d
  info:
    apply_time_ms: 56.453
    dispatch_time_ms: 24.407
    learner: {}
    num_steps_sampled: 1110
    num_steps_trained: 1110
    wait_time_ms: 97.395
  iterations_since_restore: 1
  node_ip: 172.17.0.3
  pid: 43
  policy_reward_mean: {}
  time_since_restore: 27.188933849334717
  time_this_iter_s: 27.188933849334717
  time_total_s: 27.188933849334717
  timestamp: 1536995717
  timesteps_since_restore: 1110
  timesteps_this_iter: 1110
  timesteps_total: 1110
  training_iteration: 1
  
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 3/32 CPUs, 0/0 GPUs
Result logdir: /root/ray_results/default
RUNNING trials:
 - A3C_PongDeterministic-v4_0:	RUNNING [pid=43], 27 s, 1 iter, 1110 ts, nan rew

The worker with ID 3ec76a35fb5b058a063732da643e53f0ec8de6c5 died or was killed while executing the task with ID ce983c73ef22e8295794e7de0e02563aae192386
Error processing event.
Traceback (most recent call last):
  File "/ray/python/ray/tune/trial_runner.py", line 219, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/ray/python/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/ray/python/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
RayGetError: Could not get objectid ObjectID(4cae3d9cee6657c213e19a6be394c376cd28b4e2). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/ray/python/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/ray/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/ray/python/ray/rllib/agents/agent.py", line 212, in train
    return Trainable.train(self)
  File "/ray/python/ray/tune/trainable.py", line 143, in train
    result = self._train()
  File "/ray/python/ray/rllib/agents/a3c/a3c.py", line 106, in _train
    self.optimizer.step()
  File "/ray/python/ray/rllib/optimizers/async_gradients_optimizer.py", line 44, in step
    gradient, info = ray.get(fut)
  File "/ray/python/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
RayGetError: Could not get objectid ObjectID(d07974f37d803d13bb2e67c4c6a555835b438cbd). It was created by remote function <unknown> which failed with:

Remote function <unknown> failed with:

Invalid return value: likely worker died or was killed while executing the task.

Remote function train failed with:

Traceback (most recent call last):
  File "/ray/python/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/ray/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/ray/python/ray/rllib/agents/agent.py", line 212, in train
    return Trainable.train(self)
  File "/ray/python/ray/tune/trainable.py", line 143, in train
    result = self._train()
  File "/ray/python/ray/rllib/agents/a3c/a3c.py", line 106, in _train
    self.optimizer.step()
  File "/ray/python/ray/rllib/optimizers/async_gradients_optimizer.py", line 44, in step
    gradient, info = ray.get(fut)
  File "/ray/python/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
RayGetError: Could not get objectid ObjectID(d07974f37d803d13bb2e67c4c6a555835b438cbd). It was created by remote function <unknown> which failed with:

Remote function <unknown> failed with:

Invalid return value: likely worker died or was killed while executing the task.

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/32 CPUs, 0/0 GPUs
Result logdir: /root/ray_results/default
ERROR trials:
 - A3C_PongDeterministic-v4_0:	ERROR, 1 failures: /root/ray_results/default/A3C_PongDeterministic-v4_0_2018-09-15_07-14-47RrorV0/error_2018-09-15_07-15-32.txt [pid=43], 27 s, 1 iter, 1110 ts, nan rew

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/32 CPUs, 0/0 GPUs
Result logdir: /root/ray_results/default
ERROR trials:
 - A3C_PongDeterministic-v4_0:	ERROR, 1 failures: /root/ray_results/default/A3C_PongDeterministic-v4_0_2018-09-15_07-14-47RrorV0/error_2018-09-15_07-15-32.txt [pid=43], 27 s, 1 iter, 1110 ts, nan rew

Traceback (most recent call last):
  File "/ray/python/ray/rllib/train.py", line 118, in <module>
    run(args, parser)
  File "/ray/python/ray/rllib/train.py", line 112, in run
    queue_trials=args.queue_trials)
  File "/ray/python/ray/tune/tune.py", line 118, in run_experiments
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [A3C_PongDeterministic-v4_0])
```
