### ISSUE TITLE
[ray client] surface ray client logs better

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#28890]
### What happened + What you expected to happen

Seems like we still need to continue to support Ray Client. Currently to debug ray client issue, one has to do several hops as shown below.

what one sees on ray client side:
```
Put failed:

....
  File "/home/ubuntu/.pyenv/versions/3.8.6/envs/prediction-service/lib/python3.8/site-packages/ray/util/client/worker.py", line 545, in call_remote
    task = instance._prepare_client_task()
           │        └ <function OptionWrapper._prepare_client_task at 0x7fa9698ae0d0>
           └ <ray.util.client.common.ActorOptionWrapper object at 0x7fa9682ab3d0>
  File "/home/ubuntu/.pyenv/versions/3.8.6/envs/prediction-service/lib/python3.8/site-packages/ray/util/client/common.py", line 578, in _prepare_client_task
    task = self._remote_stub._prepare_client_task()
           │    │            └ <function ClientActorClass._prepare_client_task at 0x7fa9698ac5e0>
           │    └ ClientActorClass(RayTuneExecutor, InProgressSentinel)
           └ <ray.util.client.common.ActorOptionWrapper object at 0x7fa9682ab3d0>
  File "/home/ubuntu/.pyenv/versions/3.8.6/envs/prediction-service/lib/python3.8/site-packages/ray/util/client/common.py", line 407, in _prepare_client_task
    self._ensure_ref()
    │    └ <function ClientActorClass._ensure_ref at 0x7fa9698ac280>
    └ ClientActorClass(RayTuneExecutor, InProgressSentinel)
  File "/home/ubuntu/.pyenv/versions/3.8.6/envs/prediction-service/lib/python3.8/site-packages/ray/util/client/common.py", line 377, in _ensure_ref
    self._ref = ray.worker._put_pickled(
    │    │      └ <ray.util.client.RayAPIStub object at 0x7fa98d0a3dc0>
    │    └ InProgressSentinel
    └ ClientActorClass(RayTuneExecutor, InProgressSentinel)
  File "/home/ubuntu/.pyenv/versions/3.8.6/envs/prediction-service/lib/python3.8/site-packages/ray/util/client/worker.py", line 499, in _put_pickled
    raise cloudpickle.loads(resp.error)
          │           │     │    └ <field property 'ray.rpc.PutResponse.error'>
          │           │     └ error: "\200\005\225\327\000\000\000\000\000\000\000\214\026pony.orm.dbapiprovider\224\214\020OperationalError\224\223\224\21...
          │           └ <built-in function loads>
          └ <module 'ray.cloudpickle' from '/home/ubuntu/.pyenv/versions/3.8.6/envs/prediction-service/lib/python3.8/site-packages/ray/cl...

pony.orm.dbapiprovider.OperationalError
```

And then going to core logs, one sees
```
2022-09-16 11:20:32,574 INFO proxier.py:340 -- SpecificServer started on port: 23017 with PID: 26977 for client: c64545ed41bb4c82af456ae5de08d8c3
2022-09-16 10:00:34,692 ERROR proxier.py:723 -- Proxying Datapath failed!
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/util/client/server/proxier.py", line 716, in Datapath
    for resp in resp_stream:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.FAILED_PRECONDITION
        details = "could not translate host name "postgres-postgresql" to address: Temporary failure in name resolution
"
        debug_error_string = "{"created":"@1663347634.692195547","description":"Error received from peer ipv4:127.0.0.1:23013","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"could not translate host name "postgres-postgresql" to address: Temporary failure in name resolution\n","grpc_status":9}"

```

After hopping to the correct ray client server log, one sees
```
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/util/client/server/dataservicer.py", line 269, in Datapath
    arglist, kwargs = loads_from_client(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/util/client/server/server_pickler.py", line 129, in loads_from_client
    return ClientUnpickler(
  File "/tmp/ray/session_2022-09-16_08-58-43_149941_185/runtime_resources/working_dir_files/_ray_pkg_ce0548747c6e2c95/prediction/app/worker/data_preprocessor/tsa.py", line 15, in <module>
    from prediction.app.worker.data_preprocessor.validators import Validator
  File "/tmp/ray/session_2022-09-16_08-58-43_149941_185/runtime_resources/working_dir_files/_ray_pkg_ce0548747c6e2c95/prediction/app/worker/data_preprocessor/validators.py", line 6, in <module>
    import prediction.src.db.prediction_database as pred_db
  File "/tmp/ray/session_2022-09-16_08-58-43_149941_185/runtime_resources/working_dir_files/_ray_pkg_ce0548747c6e2c95/prediction/src/db/prediction_database.py", line 148, in <module>
    db.bind("postgres", PREDICTION_CONTEXT.db_uri)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/pony/orm/core.py", line 765, in bind
    self._bind(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/pony/orm/core.py", line 787, in _bind
    self.provider = provider_cls(self, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/pony/orm/dbapiprovider.py", line 131, in __init__
    connection, is_new_connection = provider.connect()
  File "<string>", line 2, in connect
  File "/home/ray/anaconda3/lib/python3.8/site-packages/pony/orm/dbapiprovider.py", line 72, in wrap_dbapi_exceptions
    raise OperationalError(e)
pony.orm.dbapiprovider.OperationalError: could not translate host name "postgres-postgresql" to address: Temporary failure in name resolution

```
This is where the real error information is revealed.

The request is to better surface ray client logs.

### Versions / Dependencies

master

### Reproduction script

NA

See more information here: https://docs.google.com/document/d/1gBNquaGUbDt9_2HA2ogbg2FdN0lnB6LNKHfj5cTMBSs/edit#heading=h.g1usyxq5zrtd

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xwjiang2010** [comment]
cc @ericl

**Comment by ericl** [comment]
@ckw017 , do you have enough context on this one or shall we walk through it together sometime?

**Comment by ckw017** [comment]
I have enough context on this one.

**Comment by rkooo567** [comment]
@ckw017 are you planning to work on this?

**Comment by ckw017** [comment]
@rkooo567 Likely won't have time until after November

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
