### ISSUE TITLE
Raise helpful error message when `ImportError: cannot import name '_psutil_osx`

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#28903]
### Description

If you install Ray from source, you might get this error.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../ray/python/ray/__init__.py", line 63, in <module>
    import ray._raylet  # noqa: E402
  File "python/ray/_raylet.pyx", line 98, in init ray._raylet
    import ray.memory_monitor as memory_monitor
  File ".../ray/python/ray/memory_monitor.py", line 9, in <module>
    import psutil  # noqa E402
  File ".../ray/python/ray/thirdparty_files/psutil/__init__.py", line 159, in <module>
    from . import _psosx as _psplatform
  File ".../ray/python/ray/thirdparty_files/psutil/_psosx.py", line 15, in <module>
    from . import _psutil_osx as cext
ImportError: cannot import name '_psutil_osx' from partially initialized module 'psutil' (most likely due to a circular import) (.../ray/python/ray/thirdparty_files/psutil/__init__.py)
```

There's a [fix in the documentation](https://docs.ray.io/en/master/ray-contribute/development.html#troubleshooting), but it'd be nice if this information was in the error message:

```
try:
     from . import _psutil_osx as cext
except:
    raise ImportError(
        "blah blah run these commands:"
        "rm -rf python/ray/thirdparty_files/"
        "python3 -m pip install setproctitle"
    )
```

### Use case

QOL

**Comment by Reemyos** [comment]
Hi, this is my first time contributing :) I think I can help. Could I get assigned?

**Comment by bhavika** [comment]
I just ran into this so I'd be happy to take it. @bveeramani sound good?

**Comment by bveeramani** [comment]
@bhavika Go for it!

**Comment by sairajab** [comment]
@bveeramani and @bhavika , I can work on this.

**Comment by bhavika** [comment]
@sairajab go ahead!

**Comment by sairajab** [comment]
What are the steps to reproduce this error?
Did you try to build for Python only or linux (full) ?

**Comment by rkooo567** [comment]
@sairajab I think you can repro by 
1. build ray from source.
2. Create a conda env with different python version and try building from the source again.
3. Try starting ray (ray start --head)

**Comment by mineshkumar** [comment]
Hi @richardliaw, @cszhu, @alanwguo, @rkooo567 - I'd like to work on this.

My plan:
- Wrap the failing import in `_psosx.py` and `_pslinux.py` with a `try/except`
- Raise a clear `ImportError` that surfaces the fix commands shared by Balaji (`rm -rf python/ray/thirdparty_files/` and `python3 -m pip install psutil`) along with a link to the build docs

Let me know if there's a preferred approach or anything I should be aware of before I open a PR.

**Comment by mineshkumar** [comment]
A fix for this is ready in PR #63095. It wraps the psutil import in ray/__init__.py with a targeted try/except that raises a clear, actionable error message when a psutil C extension fails to load due to stale thirdparty_files — including the exact commands to resolve it. Would appreciate a review.
