### ISSUE TITLE
[core][release] chaos_dataset_shuffle_random_shuffle_1tb failed with node failure 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#28904]
### What happened + What you expected to happen

The test is unstable for now 

[most recent failure cluster ](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_ZpmX3chUNsc4MVYAmXwexECB?command-history-section=command_history)

The stack looks really deep and given it's a chaos test - it's hard to see what's the expected error and what's not at first glances. 

```
.....
Traceback (most recent call last):
  File "dataset/sort.py", line 165, in <module>
    raise exc
  File "dataset/sort.py", line 117, in <module>
    ds = ds.random_shuffle()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 839, in random_shuffle
    return Dataset(plan, self._epoch, self._lazy)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 217, in __init__
    self._plan.execute(allow_clear_input_blocks=False)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/plan.py", line 309, in execute
    blocks, clear_input_blocks, self._run_by_consumer
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/plan.py", line 756, in __call__
    blocks, clear_input_blocks, self.block_udf, self.ray_remote_args
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/stage_impl.py", line 118, in do_shuffle
    reduce_ray_remote_args=remote_args,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/shuffle.py", line 117, in execute
    new_metadata = reduce_bar.fetch_until_complete(list(new_metadata))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/progress_bar.py", line 75, in fetch_until_complete
    for ref, result in zip(done, ray.get(done)):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py", line 2279, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: [36mray::reduce()[39m (pid=1851, ip=172.31.73.78)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.ObjectFetchTimedOutError: Failed to retrieve object 51edee597348f8b6ffffffffffffffffffffffff03000000b0020000. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.

Fetch for object 51edee597348f8b6ffffffffffffffffffffffff03000000b0020000 timed out because no locations were found for the object. This may indicate a system-level bug.
```

### Versions / Dependencies

Unfortunately the test wasn't able to succeed in the past few days - the last success run at : https://buildkite.com/ray-project/release-tests-branch/builds/1016#018357ca-5e56-42ac-9924-37ec2c7617ab

### Reproduction script

NA

**Comment by hora-anyscale** [comment]
Per Triage Sync: Flaky test
