### ISSUE TITLE
[core][release] chaos_dask_on_ray_large_scale_test_spilling failed with grpc deadline exceeds

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#28932]
### What happened + What you expected to happen

[Failure](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_Wp2GWzwuYdUn8tT7aGbM1haG?command-history-section=command_history)

```
Peak memory usage: 26.12GB
Peak memory usage per processes:
 PID    MEM     COMMAND
337     2.68GiB /home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=
9911    1.39GiB ray::dask:('decimate_raw_data-86d0313b27a931cdd7ec63af2a077139', 0, 1552)
5694    1.37GiB ray::dask:('decimate_raw_data-86d0313b27a931cdd7ec63af2a077139', 0, 80)
15117   1.3GiB  ray::dask:('decimate_raw_data-86d0313b27a931cdd7ec63af2a077139', 0, 1106)
16033   1.26GiB ray::dask:('decimate_raw_data-86d0313b27a931cdd7ec63af2a077139', 0, 1553)
8738    1.17GiB ray::dask:('decimate_raw_data-86d0313b27a931cdd7ec63af2a077139', 0, 1103)
6311    1.17GiB ray::dask:('decimate_raw_data-86d0313b27a931cdd7ec63af2a077139', 0, 714)
15066   1.11GiB ray::dask:('decimate_raw_data-86d0313b27a931cdd7ec63af2a077139', 0, 713)
16687   1.06GiB ray::dask:('decimate_raw_data-86d0313b27a931cdd7ec63af2a077139', 0, 87)
15065   1.04GiB ray::dask:('decimate_raw_data-86d0313b27a931cdd7ec63af2a077139', 0, 1105)
Traceback (most recent call last):
  File "dask_on_ray/large_scale_test.py", line 479, in <module>
    main()
  File "dask_on_ray/large_scale_test.py", line 465, in main
    print(ray._private.internal_api.memory_summary(stats_only=True))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/internal_api.py", line 39, in memory_summary
    return get_store_stats(state)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/internal_api.py", line 77, in get_store_stats
    timeout=60.0,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:172.31.70.141:44943 {created_time:"2022-09-29T15:45:03.591722687-07:00", grpc_status:4, grpc_message:"Deadline Exceeded"}"
```

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by rickyyx** [comment]
Passing now and due to ray memory timeout. 
Downgrading to P1.

**Comment by richardliaw** [comment]
closing this since it's going to go stale. reopen a new issue if you see it.
