### ISSUE TITLE
[release][CI] long_running_serve failure 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#28977]
### What happened + What you expected to happen

[Build failure nighltly 09/30 ](https://buildkite.com/ray-project/release-tests-branch/builds/1080#0183906e-8822-4d3b-a676-317926459ebb)
[Cluster](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_mnpepCVJs28Y8m4cjW3xmA8U)

```


[INFO 2022-10-01 17:37:19,470] log.py: 36  Did not find any results.
--
  | [INFO 2022-10-01 17:37:19,471] artifacts.py: 34  Wrote test config and result to artifacts directory: /tmp/artifacts
  | [INFO 2022-10-01 17:37:19,471] legacy_rds.py: 30  Persisting results to database...
  | [INFO 2022-10-01 17:37:19,945] legacy_rds.py: 122  Result has been persisted to the database
  | [INFO 2022-10-01 17:37:19,946] db.py: 17  Persisting result to the databricks delta lake...
  | [INFO 2022-10-01 17:37:19,994] db.py: 47  Result has been persisted to the databricks delta lake
  | [ERROR 2022-10-01 17:37:19,994] run_release_test.py: 159  Last update to results json was too long ago (inf > 480)
  | Traceback (most recent call last):
  | File "ray_release/scripts/run_release_test.py", line 155, in main
  | no_terminate=no_terminate,
  | File "/tmp/release-iGfl8oSEe4/release/ray_release/glue.py", line 333, in run_release_test
  | raise pipeline_exception
  | File "/tmp/release-iGfl8oSEe4/release/ray_release/glue.py", line 311, in run_release_test
  | handle_result(test, result)
  | File "/tmp/release-iGfl8oSEe4/release/ray_release/alerts/handle.py", line 39, in handle_result
  | raise ResultsAlert(error)
  | ray_release.exception.ResultsAlert: Last update to results json was too long ago (inf > 480)
  | [INFO 2022-10-01 17:37:19,994] run_release_test.py: 163  Release test pipeline for test long_running_serve completed. Returning with exit code = 41
  | Script failed on try 1/1 with exit code 41 (command error), aborting.


```

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by architkulkarni** [comment]
Seems the results can't be read due to a JSON parsing error (does this actually mean the file is empty?)
https://buildkite.com/ray-project/release-tests-branch/builds/1067#0183811b-9941-49ba-9fee-68d6a830020f/3613-3616
```
[ERROR 2022-09-28 16:00:40,941] glue.py: 268  Could not fetch results from session: Expecting ',' delimiter: line 1 column 35 (char 34)
--
  | Traceback (most recent call last):
  | File "/tmp/release-aTxQWkOlhp/release/ray_release/command_runner/sdk_runner.py", line 173, in fetch_results
  | data = json.load(f)
  | File "/home/ray/anaconda3/lib/python3.7/json/__init__.py", line 296, in load
  | parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  | File "/home/ray/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
  | return _default_decoder.decode(s)
  | File "/home/ray/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
  | obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  | File "/home/ray/anaconda3/lib/python3.7/json/decoder.py", line 353, in raw_decode
  | obj, end = self.scan_once(s, idx)
  | json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 35 (char 34)
```

**Comment by architkulkarni** [comment]
Manually looking at the results JSON file on a running test https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_niFkx7QdRuXQ286jSMRQD5h5?command-history-section=command_history, looks normal and is being updated every 5 minutes as expected.  The Serve cluster seems to be healthy after 18 hours
```{"latency_avg": "99.66ms", "latency_stdev": "27.07ms", "latency_max": "219.87ms", "latency_+/-_stdev": "65.90%", "req/sec_avg": "423.30", "req/sec_stdev": "66.53", "req/sec_max": "595.00", "req/sec_+/-_stdev": "64.82%", "requests/sec": "842.62", "transfer/sec": "126.73KB", "last_update": 1664993193.9291553}```

**Comment by architkulkarni** [comment]
We also see this error quite a lot:
```
[INFO 2022-09-27 15:55:36,482] job_manager.py: 40  Executing pip install -q awscli && aws s3 cp /tmp/release_test_out.json s3://ray-release-automation-results/tmp/fdpkthdvvq --acl bucket-owner-full-control with {} via ray job submit
--
  | [ERROR 2022-09-27 15:56:18,851] glue.py: 267  Could not fetch results for test command
  | [ERROR 2022-09-27 15:56:18,851] glue.py: 268  Could not fetch results from session: Error downloading file /tmp/release_test_out.json to /tmp/tmpazmxk1m0
  | Traceback (most recent call last):
  | File "/tmp/release-4mTqZU2U2R/release/ray_release/command_runner/sdk_runner.py", line 170, in fetch_results
  | self.file_manager.download(self.result_output_json, tmpfile)
  | File "/tmp/release-4mTqZU2U2R/release/ray_release/file_manager/job_file_manager.py", line 63, in download
  | raise FileDownloadError(f"Error downloading file {source} to {target}")
  | ray_release.exception.FileDownloadError: Error downloading file /tmp/release_test_out.json to /tmp/tmpazmxk1m0
```
[Example 1](https://buildkite.com/ray-project/release-tests-branch/builds/1063#01837bf3-dc04-49ec-a2f5-6ad98d6a410f/3698-3699)
[Example 2](https://buildkite.com/ray-project/release-tests-branch/builds/1033#01836740-399f-4175-98fd-aa2571b7bb73/3596-3606)

**Comment by architkulkarni** [comment]
@krfricke tagging you just in case if you've seen these kinds of errors before when fetching the results and have any ideas off the top of your head.  We'll continue to investigate
