### ISSUE TITLE
[release][CI] air_benchmark_tune_torch_mnist_large_gpu failed 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#28996]
### What happened + What you expected to happen

[Build failure weekly 10/01](https://buildkite.com/ray-project/release-tests-branch/builds/1081#0183974c-98c5-424d-9471-ad1651cb1e81)

[Cluster](https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_PRDx3H79TMdzpGqHtgPecpH4) 

```


== Status ==
Current time: 2022-10-02 00:09:00 (running for 00:30:13.44)
Memory usage on this node: 19.6/186.6 GiB 
Using FIFO scheduling algorithm.
Resources requested: 16.0/384 CPUs, 8.0/32 GPUs, 0.0/1052.16 GiB heap, 0.0/413.87 GiB objects (0.0/8.0 accelerator_type:T4)
Result logdir: /home/ray/ray_results/TorchTrainer_2022-10-01_23-38-47
Number of trials: 1/1 (1 RUNNING)
+--------------------------+----------+------------------+
| Trial name               | status   | loc              |
|--------------------------+----------+------------------|
| TorchTrainer_de45d_00000 | RUNNING  | 172.31.69.30:757 |
+--------------------------+----------+------------------+


Result for TorchTrainer_de45d_00000:
  date: 2022-10-01_23-38-50
  experiment_id: 19ec039366214db88756b0cee00d85de
  hostname: ip-172-31-69-30
  node_ip: 172.31.69.30
  pid: 757
  timestamp: 1664692730
  trial_id: de45d_00000
  (raylet) 2022-10-02 00:09:01,827      INFO runtime_env_agent.py:482 -- Got request from raylet to decrease reference for runtime env: {"env_vars":{"NCCL_SOCKET_IFNAME":"ens","PL_DISABLE_FORK":"1","TUNE_ORIG_WORKING_DIR":"/home/ray/oss-release-tests-2"},"working_dir":"gcs://_ray_pkg_fe27ced910fcb345.zip"}.
2022-10-02 00:09:01,893 ERROR tune.py:758 -- Trials did not complete: [TorchTrainer_de45d_00000]
2022-10-02 00:09:01,893 INFO tune.py:763 -- Total run time: 1814.50 seconds (1814.39 seconds for the tuning loop).

== Status ==
Current time: 2022-10-02 00:09:01 (running for 00:30:14.39)
Memory usage on this node: 19.5/186.6 GiB 
Using FIFO scheduling algorithm.
Resources requested: 0/384 CPUs, 0/32 GPUs, 0.0/1052.16 GiB heap, 0.0/413.87 GiB objects (0.0/8.0 accelerator_type:T4)
Result logdir: /home/ray/ray_results/TorchTrainer_2022-10-01_23-38-47
Number of trials: 1/1 (1 ERROR)
+--------------------------+----------+------------------+
| Trial name               | status   | loc              |
|--------------------------+----------+------------------|
| TorchTrainer_de45d_00000 | ERROR    | 172.31.69.30:757 |
+--------------------------+----------+------------------+
Number of errored trials: 1
+--------------------------+--------------+-----------------------------------------------------------------------------------------------------------------+
| Trial name               |   # failures | error file                                                                                                      |
|--------------------------+--------------+-----------------------------------------------------------------------------------------------------------------|
| TorchTrainer_de45d_00000 |            1 | /home/ray/ray_results/TorchTrainer_2022-10-01_23-38-47/TorchTrainer_de45d_00000_0_2022-10-01_23-38-47/error.txt |
+--------------------------+--------------+-----------------------------------------------------------------------------------------------------------------+

Traceback (most recent call last):
  File "workloads/tune_torch_benchmark.py", line 152, in <module>
    main()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "workloads/tune_torch_benchmark.py", line 108, in main
    lambda: train_torch(num_workers=num_workers, use_gpu=use_gpu), number=1
  File "/home/ray/anaconda3/lib/python3.7/timeit.py", line 233, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "/home/ray/anaconda3/lib/python3.7/timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "workloads/tune_torch_benchmark.py", line 108, in <lambda>
    lambda: train_torch(num_workers=num_workers, use_gpu=use_gpu), number=1
  File "workloads/tune_torch_benchmark.py", line 54, in train_torch
    trainer.fit()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/train/base_trainer.py", line 360, in fit
    raise result.error
ray.exceptions.RayTaskError(RuntimeError): ray::_Inner.train() (pid=757, ip=172.31.69.30, repr=TorchTrainer)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trainable/trainable.py", line 353, in train
    raise skip_exceptions(e) from None
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/train/_internal/utils.py", line 54, in check_for_failure
    ray.get(object_ref)
ray.exceptions.RayTaskError(RuntimeError): ray::RayTrainWorker._RayTrainWorker__execute() (pid=12455, ip=172.31.43.57, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x7fa3200c3f90>)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/train/_internal/worker_group.py", line 30, in __execute
    raise skip_exceptions(e) from None
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/train/_internal/utils.py", line 129, in discard_return_wrapper
    train_func(*args, **kwargs)
  File "workloads/tune_torch_benchmark.py", line 37, in train_loop
  File "/home/ray/oss-release-tests-2/workloads/torch_benchmark.py", line 204, in train_func
    local_rank=local_rank,
  File "/home/ray/oss-release-tests-2/workloads/torch_benchmark.py", line 58, in train_epoch
    pred = model(X)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ray/oss-release-tests-2/workloads/torch_benchmark.py", line 47, in forward
    logits = self.linear_relu_stack(x)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking arugment for argument mat1 in method wrapper_addmm)

```

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by c21** [comment]
Two other similar AIR test failures:

air_benchmark_torch_mnist_gpu_4x4 - https://buildkite.com/ray-project/release-tests-branch/builds/1090#01839fe4-5462-4aff-a4bc-4fbd802de000

air_benchmark_tune_torch_mnist_gpu - https://buildkite.com/ray-project/release-tests-branch/builds/1090#01839fe4-5471-44f4-8980-f8386da26275
