### ISSUE TITLE
Segfault renders Ray unusable

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#290]
Ray ran into a segfault in a previous script. Processes remain alive, and trying to run the script again would throw this error: 

```
/home/ubuntu/pg/pong_a3c.py in train(u_itr)
    123         result, remaining = ray.wait(remaining)
    124         get_task = time.time()
--> 125         grads, info = ray.get(result)[0]
    126         average_reward.add(info["rews"])
    127         rwds.extend(info["real_rwds"])

/home/ubuntu/ray/python/ray/worker.pyc in get(object_ids, worker)
   1415       for i, value in enumerate(values):
   1416         if isinstance(value, RayTaskError):
-> 1417           raise RayGetError(object_ids[i], value)
   1418       return values
   1419     else:

RayGetError: Could not get objectid ObjectID(5ae764ab768e2a257886dc2e7d8e46183ad6304f). It was created by remote function __main__.a3c_rollout_grad which failed with:

Remote function __main__.a3c_rollout_grad failed with:

Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/worker.py", line 1585, in process_task
    store_outputs_in_objstore(return_object_ids, outputs, worker)
  File "/home/ubuntu/ray/python/ray/worker.py", line 1935, in store_outputs_in_objstore
    worker.put_object(objectids[i], outputs[i])
  File "/home/ubuntu/ray/python/ray/worker.py", line 441, in put_object
    numbuf.store_list(objectid.id(), self.plasma_client.conn, [value])
error: The plasma store ran out of memory and could not create this object.

[INFO] (/home/ubuntu/ray/src/plasma/eviction_policy.c:178) There is not enough space to create this object, so evicting 32 objects to free up 172353280 bytes.
[INFO] (/home/ubuntu/ray/src/plasma/plasma_store.c:796) Disconnecting client on fd 16
[INFO] (/home/ubuntu/ray/src/plasma/plasma_manager.c:1396) Disconnecting client on fd 19
[INFO] (/home/ubuntu/ray/src/plasma/plasma_manager.c:1396) Disconnecting client on fd 17
[INFO] (/home/ubuntu/ray/src/plasma/plasma_store.c:796) Disconnecting client on fd 14
[INFO] (/home/ubuntu/ray/src/plasma/plasma_manager.c:1396) Disconnecting client on fd 18
[INFO] (/home/ubuntu/ray/src/plasma/plasma_store.c:796) Disconnecting client on fd 15
[INFO] (/home/ubuntu/ray/src/plasma/plasma_manager.c:1396) Disconnecting client on fd 16
[INFO] (/home/ubuntu/ray/src/plasma/plasma_store.c:796) Disconnecting client on fd 12
[INFO] (/home/ubuntu/ray/src/plasma/plasma_store.c:796) Disconnecting client on fd 10
2753:signal-handler (1487362224) Received SIGTERM scheduling shutdown...
2753:M 17 Feb 20:10:24.675 # User requested shutdown...
2753:M 17 Feb 20:10:24.675 # Redis is now ready to exit, bye bye...
Exception UnboundLocalError: "local variable 'status' referenced before assignment" in <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7f7e57ffebd0>> ignored
(ray) ubuntu@ip-172-31-7-205:~/pg$ logout
```

**Comment by robertnishihara** [comment]
Most likely the object store from the original run (the one that segfaulted) is still running and using up a ton of shared memory, thus causing the new object store that gets created when you run the script a second time to run out of memory quickly.

You can check if there is still an object store running by doing `ps aux | grep plasma_store`.

Note that if this is the problem, if you start python and do `ray.init()`, you should get an error message along the lines of

```
Warning: Reducing object store memory because /dev/shm has only <NUMBER> bytes available. You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
```

If that's the case, you can try killing all of the old Ray processes with `./ray/scripts/stop_ray.sh`.

If that's not the problem, you make check `/dev/shm` (on Linux) and see if there are large files there that can be deleted.
