### ISSUE TITLE
ValueError: dict contains fields not in fieldnames: duration

### ISSUE THREAD

**Issue by Nithanaroy** [ray-project/ray#2903]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: RHEL 7
- **Ray installed from (source or binary)**: No
- **Ray version**: 0.5.2
- **Python version**: 2.7
- **Exact command to reproduce**: Occurred while running the trails. See below

### Describe the problem
Here is the error stack trace after which the experiment stopped running,
```
Error processing event: Traceback (most recent call last):
  File "<PROJECT_HOME>/env_27/lib/python2.7/site-packages/ray/tune/trial_runner.py", line 235, in _process_events
    result, terminate=(decision == TrialScheduler.STOP))
  File "<PROJECT_HOME>/env_27/lib/python2.7/site-packages/ray/tune/trial.py", line 275, in update_last_result
    self.result_logger.on_result(self.last_result)
  File "<PROJECT_HOME>/env_27/lib/python2.7/site-packages/ray/tune/logger.py", line 70, in on_result
    logger.on_result(result)
  File "<PROJECT_HOME>/env_27/lib/python2.7/site-packages/ray/tune/logger.py", line 162, in on_result
    self._csv_out.writerow(result.copy())
  File "/usr/lib64/python2.7/csv.py", line 148, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/usr/lib64/python2.7/csv.py", line 144, in _dict_to_list
    ", ".join(wrong_fields))
ValueError: dict contains fields not in fieldnames: duration

== Status ==
Using AsyncHyperBand: num_stopped=4
Bracket: Iter 729.000: 0.701243320224 | Iter 243.000: 1.90358602591 | Iter 81.000: 4.87482543814 | Iter 27.000: 9.06012251408 | Iter 9.000: 10.7916165993 | Iter 3.000: 12.6251589523 | Iter 1.000: 13.5951920582
Bracket: Iter 729.000: 0.692626866355 | Iter 243.000: 1.37307462143 | Iter 81.000: 2.04405799716 | Iter 27.000: 2.59210393295 | Iter 9.000: 5.17456468471 | Iter 3.000: 7.10016327688
Bracket: Iter 729.000: 1.48970766281 | Iter 243.000: 1.23661574345 | Iter 81.000: 2.21857558151 | Iter 27.000: 2.73626789952 | Iter 9.000: 3.18781074054
Resources requested: 0/16 CPUs, 0/1 GPUs
Result logdir: ./ray_search_results/nqs_input_pipeline
ERROR trials:
 - _data_fetch_for_search_e=1015.8,r=1050.6,h=20.888,s=12.727,e=1741.1,y=False,r=234.25:	ERROR, 1 failures: ./ray_search_results/nqs_input_pipeline/_data_fetch_for_search_e=1015.8,r=1050.6,h=20.888,s=12.727,e=1741.1,y=False,r=234.25_2018-09-17_19-19-10Kml2ar/error_2018-09-17_19-29-14.txt [pid=166721], 546 s, 0 ts
 - _data_fetch_for_search_e=738.07,r=723.28,h=15.7,s=12.959,e=937.62,y=True,r=712.3:	ERROR, 1 failures: ./ray_search_results/nqs_input_pipeline/_data_fetch_for_search_e=738.07,r=723.28,h=15.7,s=12.959,e=937.62,y=True,r=712.3_2018-09-17_18-46-46Smic23/error_2018-09-17_19-16-51.txt [pid=159721], 1741 s, 0 ts
 - _data_fetch_for_search_e=790.8,r=1908.0,h=27.032,s=14.791,e=1616.7,y=True,r=468.94:	ERROR, 1 failures: ./ray_search_results/nqs_input_pipeline/_data_fetch_for_search_e=790.8,r=1908.0,h=27.032,s=14.791,e=1616.7,y=True,r=468.94_2018-09-17_19-13-156gm1sI/error_2018-09-17_19-33-55.txt [pid=165975], 1211 s, 0 ts
 - _data_fetch_for_search_e=984.65,r=1975.0,h=12.107,s=29.667,e=1763.4,y=True,r=805.79:	ERROR, 1 failures: ./ray_search_results/nqs_input_pipeline/_data_fetch_for_search_e=984.65,r=1975.0,h=12.107,s=29.667,e=1763.4,y=True,r=805.79_2018-09-17_18-46-46Uvekqh/error_2018-09-17_19-13-15.txt [pid=159713], 1522 s, 0 ts
 - _data_fetch_for_search_e=991.69,r=2032.8,h=10.824,s=12.397,e=1125.1,y=False,r=260.47:	ERROR, 1 failures: ./ray_search_results/nqs_input_pipeline/_data_fetch_for_search_e=991.69,r=2032.8,h=10.824,s=12.397,e=1125.1,y=False,r=260.47_2018-09-17_19-12-55J4BxSP/error_2018-09-17_19-23-38.txt [pid=165208], 576 s, 0 ts
TERMINATED trials:
 - _data_fetch_for_search_e=1010.0,r=1832.9,h=29.669,s=18.436,e=975.22,y=False,r=217.75:	TERMINATED [pid=159720], 708 s, 0 ts
 - _data_fetch_for_search_e=690.9,r=672.33,h=22.759,s=30.931,e=799.48,y=True,r=660.18:	TERMINATED [pid=159719], 1222 s, 0 ts
 - _data_fetch_for_search_e=718.19,r=1240.3,h=17.697,s=17.651,e=1113.1,y=False,r=344.95:	TERMINATED [pid=166234], 943 s, 0 ts
 - _data_fetch_for_search_e=965.55,r=1922.4,h=31.713,s=24.088,e=1013.8,y=False,r=385.55:	TERMINATED [pid=159715], 1564 s, 0 ts

Traceback (most recent call last):
  File "optimizing-input-pipeline.py", line 374, in <module>
    ray_search(9)
  File "optimizing-input-pipeline.py", line 340, in ray_search
    run_experiments(experiment_spec, scheduler=ahb, search_alg=algo, verbose=False)
  File "<PROJECT_HOME>/env_27/lib/python2.7/site-packages/ray/tune/tune.py", line 115, in run_experiments
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [_data_fetch_for_search_e=738.07,r=723.28,h=15.7,s=12.959,e=937.62,y=True,r=712.3, _data_fetch_for_search_e=984.65,r=1975.0,h=12.107,s=29.667,e=1763.4,y=True,r=805.79, _data_fetch_for_search_e=991.69,r=2032.8,h=10.824,s=12.397,e=1125.1,y=False,r=260.47, _data_fetch_for_search_e=790.8,r=1908.0,h=27.032,s=14.791,e=1616.7,y=True,r=468.94, _data_fetch_for_search_e=1015.8,r=1050.6,h=20.888,s=12.727,e=1741.1,y=False,r=234.25])
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0917 19:33:56.190738 159709 local_scheduler.cc:177] Killed worker pid 170635 which hadn't started yet.
```
I am trying to optimize my `tensorflow.dataset` input pipeline trying to maximize `samples_freq`, i.e. number of input records fetched from input file per second, using `ray.tune`

Here is how I am conducting the experiment,
```python
def _data_fetch_for_search(config, reporter):
    start = time()
    records_to_fetch = 10000

    with tf.Session() as sess:
        dataset = tfdata_generator_with_interleave(data_files, True,
                                                   batch_size=config["..."],
                                                   num_parallel_data_fetch=config["..."],
                                                   buffer_size=config["..."],
                                                   sloppy=config["..."],
                                                   yield_after=config["..."],
                                                   parallel_file_reads=config["..."],
                                                   prefetch_buffer=config["..."])
        next_batch = dataset.make_one_shot_iterator().get_next()
        records_fetched = 0

        while True:
            try:
                records = sess.run(next_batch)  # an array of x's and y's
                records_fetched += records[0].shape[0]
                
                duration = time() - start
                reporter(samples_freq=records_fetched / duration, intermediate_duration=duration, samples_fetched=records_fetched)
                
                if records_fetched >= records_to_fetch:
                    break
            except tf.errors.OutOfRangeError:
                print("Exhausted all data")
                break

        duration = time() - start
        reporter(samples_freq=records_fetched / duration, duration=duration, samples_fetched=records_fetched)


def ray_search(total_trails=80):
    num_parallel_trails = 4
    max_time_for_trail_s = 30 * 60 # 30 minutes
    cores = multiprocessing.cpu_count()
    ray_results_save_dir = "./ray_search_results"
    experiment_name = "nqs_input_pipeline"

    # AsyncHyperBandScheduler or HyperBandScheduler are tuned for trails with multiple iterations
    # An iteration is number of times reporter() is called during the trail
    # Check the discussion on https://groups.google.com/forum/#!topic/ray-dev/wx5zdzbgMfs
    # "max_t" is only checked between iterations and stopped if the trail timesout
    ahb = AsyncHyperBandScheduler(
        time_attr="time_total_s",
        reward_attr="samples_freq",
        grace_period=1,
        max_t=max_time_for_trail_s)

    # https://github.com/hyperopt/hyperopt/wiki/FMin#21-parameter-expressions
    space = {
        "batch_size": hp.uniform("batch_size", 512, 1024),  # integer only
        "num_parallel_data_fetch": hp.uniform("num_parallel_data_fetch", cores / 2, cores * 2),  # integer only
        "buffer": hp.uniform("buffer", 250, 2048),  # integer only
        "sloppy": hp.choice("sloppy", [True, False]),  # one of these two only
        "parallel_file_reads": hp.uniform("parallel_file_reads", cores / 2, cores * 2),  # integer only
        "prefetch_buffer_size": hp.uniform("prefetch_buffer_size", 250, 2048),
        "yield_after": hp.uniform("yield_after", 250 / cores, 1024)
    }

    experiment_spec = {
        experiment_name: {
            "run": _data_fetch_for_search,
            "stop": {
                # "training_iteration": 100,
                "time_total_s": max_time_for_trail_s # not useful as ray.tune only checks for stopping condition at the end of each iteration of trail
            },
            "trial_resources": {"cpu": cores / num_parallel_trails, "gpu": 0}, # using only some of the CPUs so that multiple trails can run at once
            "num_samples": total_trails,
            "local_dir": ray_results_save_dir,
            "max_failures": 2
        }
    }

    algo = HyperOptSearch(space, max_concurrent=num_parallel_trails, reward_attr="samples_freq")
    ray.init(redirect_output=True)
    run_experiments(experiment_spec, scheduler=ahb, search_alg=algo, verbose=False)
```
The call to `reporter` in `_data_fetch_for_search` has different arguments in both the calls. Will that be a problem? If that's the case, not all trails failed, why?

**Comment by richardliaw** [comment]
Hi Nitin, we can't report different arguments within one train run because we log to CSV (which requires some form of schema). I guess we should be clearer about this on the docs. 

What would be the issue with just logging `duration` instead of `intermediate_duration`?

**Comment by Nithanaroy** [comment]
Hi Richard, thanks for the information. To avoid mixing up the final result of the trial with intermediate ones. My original implementation did not have any intermediate results. But learned that ray only checks for stopping conditions (like `time_total_s < 1000`) only after an iteration and does not preempt a trial in between. So added intermediate reporting which are not quite useful for me but only for ray to preempt the trial. So in the final results I will filter out rows which have a value for `intermediate_duration` column.

**Comment by Nithanaroy** [comment]
Figured a simple way to detect intermediate reporting and final reporting results. For intermediate reports negated every non-reward metrics  like `duration` in my case,
```python
duration = time() - start
reporter(samples_freq=records_fetched / duration, duration=-duration, samples_fetched=-records_fetched)
```
In the post analysis phase, I can easily filter out negative duration results.
