### ISSUE TITLE
[Tune] Logging error: ValueError: I/O operation on closed file. 

### ISSUE THREAD

**Issue by tadejsv** [ray-project/ray#29080]
### What happened + What you expected to happen

For some reason, I get this error message when logging inside the objective function using the `logging` module form standard library: `ValueError: I/O operation on closed file.` - see reproduction script for more details + log.

I also notice that this happens only when I run more trials than there are CPU cores (i.e. more than can run concurrently in one go). Change `num_samples` to 4, for example, and the error doesn't occur.

### Versions / Dependencies

Running inside a docker container (VSCode development container), Ubuntu 20.04, ray 2.0.0, optuna 2.10.1

### Reproduction script

```python
from ray import tune, air
import time
import logging

from ray.tune.search.optuna import OptunaSearch
import optuna


def objective(config):
    logging.basicConfig(format="%(levelname)s:%(message)s", level=logging.DEBUG)
    logger = logging.getLogger(__name__)
    logger.error("Woke up")
    score = config["a"] + config["b"]
    time.sleep(5)
    return {"score": score}


search_space = {
    "a": tune.uniform(0, 10),
    "b": tune.uniform(0, 10),
}

tuner = tune.Tuner(
    tune_config=tune.TuneConfig(
        search_alg=OptunaSearch(sampler=optuna.samplers.RandomSampler()),
        num_samples=20,
        metric="score",
        mode="max",
    ),
    trainable=objective,
    param_space=search_space,
    run_config=air.RunConfig(
        local_dir="./results",
        name="test",
        verbose=2,
        log_to_file="output.log",
    ),
)

results = tuner.fit()
print(results.get_best_result(metric="score", mode="min").config)
```

<details>
<summary>Console log output</summary>

```
2022-10-05 08:14:43,768 INFO worker.py:1518 -- Started a local Ray instance.
2022-10-05 08:14:44,455 WARNING function_trainable.py:619 -- Function checkpointing is disabled. This may result in unexpected behavior when using checkpointing features or certain schedulers. To enable, set the train function arguments to be `func(config, checkpoint_dir=None)`.
[I 2022-10-05 08:14:44,458] A new study created in memory with name: optuna
2022-10-05 08:14:44,459 INFO tensorboardx.py:170 -- pip install "ray[tune]" to see TensorBoard files.
2022-10-05 08:14:44,459 WARNING callback.py:108 -- The TensorboardX logger cannot be instantiated because either TensorboardX or one of it's dependencies is not installed. Please make sure you have the latest version of TensorboardX installed: `pip install -U tensorboardx`
== Status ==
Current time: 2022-10-05 08:14:45 (running for 00:00:01.20)
Memory usage on this node: 4.0/31.3 GiB
Using FIFO scheduling algorithm.
Resources requested: 1.0/16 CPUs, 0/2 GPUs, 0.0/17.35 GiB heap, 0.0/8.68 GiB objects (0.0/1.0 accelerator_type:G)
Result logdir: /workspaces/trackers/results/test
Number of trials: 1/20 (1 RUNNING)


(objective pid=1884423) ERROR:Woke up
(objective pid=1884536) ERROR:Woke up
(objective pid=1884539) ERROR:Woke up
(objective pid=1884548) ERROR:Woke up
(objective pid=1884550) ERROR:Woke up
(objective pid=1884537) ERROR:Woke up
(objective pid=1884554) ERROR:Woke up
(objective pid=1884556) ERROR:Woke up
(objective pid=1884558) ERROR:Woke up
(objective pid=1884542) ERROR:Woke up
(objective pid=1884544) ERROR:Woke up
(objective pid=1884546) ERROR:Woke up
(objective pid=1884563) ERROR:Woke up
(objective pid=1884551) ERROR:Woke up
(objective pid=1884538) ERROR:Woke up
(objective pid=1884560) ERROR:Woke up
Trial objective_c4fce3ec reported score=8.99 with parameters={'a': 6.026233128486132, 'b': 2.967143747139179}.
== Status ==
Current time: 2022-10-05 08:14:50 (running for 00:00:06.23)
Memory usage on this node: 4.4/31.3 GiB
Using FIFO scheduling algorithm.
Resources requested: 16.0/16 CPUs, 0/2 GPUs, 0.0/17.35 GiB heap, 0.0/8.68 GiB objects (0.0/1.0 accelerator_type:G)
Current best trial: c4fce3ec with score=8.993376875625312 and parameters={'a': 6.026233128486132, 'b': 2.967143747139179}
Result logdir: /workspaces/trackers/results/test
Number of trials: 17/20 (1 PENDING, 16 RUNNING)


Trial objective_c4fce3ec completed. Last result: score=8.993376875625312
(objective pid=1884423) ERROR:Woke up
(objective pid=1884423) --- Logging error ---
(objective pid=1884423) Traceback (most recent call last):
(objective pid=1884423)   File "/usr/lib/python3.8/logging/__init__.py", line 1088, in emit
(objective pid=1884423)     stream.write(msg + self.terminator)
(objective pid=1884423)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/tune/utils/util.py", line 235, in write
(objective pid=1884423)     self.stream2.write(*args, **kwargs)
(objective pid=1884423) ValueError: I/O operation on closed file.
(objective pid=1884423) Call stack:
(objective pid=1884423)   File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
(objective pid=1884423)     self._bootstrap_inner()
(objective pid=1884423)   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
(objective pid=1884423)     self.run()
(objective pid=1884423)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 289, in run
(objective pid=1884423)     self._entrypoint()
(objective pid=1884423)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 362, in entrypoint
(objective pid=1884423)     return self._trainable_func(
(objective pid=1884423)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
(objective pid=1884423)     return method(self, *_args, **_kwargs)
(objective pid=1884423)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 684, in _trainable_func
(objective pid=1884423)     output = fn()
(objective pid=1884423)   File "error_test.py", line 12, in objective
(objective pid=1884423)     logger.error("Woke up")
(objective pid=1884423) Message: 'Woke up'
(objective pid=1884423) Arguments: ()
Trial objective_c5b3c288 reported score=11.04 with parameters={'a': 3.754200051168539, 'b': 7.283099131805829}.
Trial objective_c5b5457c reported score=11.44 with parameters={'a': 9.19720625690103, 'b': 2.246803891700454}.
Trial objective_c5b3c288 completed. Last result: score=11.037299182974369
Trial objective_c5b5457c completed. Last result: score=11.444010148601484
Trial objective_c5be68b4 reported score=12.12 with parameters={'a': 6.066551162932531, 'b': 6.0560688164822265}.
Trial objective_c5be68b4 completed. Last result: score=12.122619979414758
Trial objective_c5bd259e reported score=5.73 with parameters={'a': 1.8972792482983414, 'b': 3.8303709077054036}.
Trial objective_c5bd259e completed. Last result: score=5.727650156003745
(objective pid=1884536) ERROR:Woke up
(objective pid=1884536) --- Logging error ---
(objective pid=1884536) Traceback (most recent call last):
(objective pid=1884536)   File "/usr/lib/python3.8/logging/__init__.py", line 1088, in emit
(objective pid=1884536)     stream.write(msg + self.terminator)
(objective pid=1884536)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/tune/utils/util.py", line 235, in write
(objective pid=1884536)     self.stream2.write(*args, **kwargs)
(objective pid=1884536) ValueError: I/O operation on closed file.
(objective pid=1884536) Call stack:
(objective pid=1884536)   File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
(objective pid=1884536)     self._bootstrap_inner()
(objective pid=1884536)   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
(objective pid=1884536)     self.run()
(objective pid=1884536)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 289, in run
(objective pid=1884536)     self._entrypoint()
(objective pid=1884536)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 362, in entrypoint
(objective pid=1884536)     return self._trainable_func(
(objective pid=1884536)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
(objective pid=1884536)     return method(self, *_args, **_kwargs)
(objective pid=1884536)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 684, in _trainable_func
(objective pid=1884536)     output = fn()
(objective pid=1884536)   File "error_test.py", line 12, in objective
(objective pid=1884536)     logger.error("Woke up")
(objective pid=1884536) Message: 'Woke up'
(objective pid=1884536) Arguments: ()
(objective pid=1884550) ERROR:Woke up
Trial objective_c5b7827e reported score=14.48 with parameters={'a': 8.507060377920968, 'b': 5.96795069206232}.
(objective pid=1884550) --- Logging error ---
(objective pid=1884550) Traceback (most recent call last):
(objective pid=1884550)   File "/usr/lib/python3.8/logging/__init__.py", line 1088, in emit
(objective pid=1884550)     stream.write(msg + self.terminator)
(objective pid=1884550)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/tune/utils/util.py", line 235, in write
(objective pid=1884550)     self.stream2.write(*args, **kwargs)
(objective pid=1884550) ValueError: I/O operation on closed file.
(objective pid=1884550) Call stack:
(objective pid=1884550)   File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
(objective pid=1884550)     self._bootstrap_inner()
(objective pid=1884550)   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
(objective pid=1884550)     self.run()
(objective pid=1884550)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 289, in run
(objective pid=1884550)     self._entrypoint()
(objective pid=1884550)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 362, in entrypoint
(objective pid=1884550)     return self._trainable_func(
(objective pid=1884550)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
(objective pid=1884550)     return method(self, *_args, **_kwargs)
(objective pid=1884550)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 684, in _trainable_func
(objective pid=1884550)     output = fn()
(objective pid=1884550)   File "error_test.py", line 12, in objective
(objective pid=1884550)     logger.error("Woke up")
(objective pid=1884550) Message: 'Woke up'
(objective pid=1884550) Arguments: ()
(objective pid=1884537) ERROR:Woke up
(objective pid=1884537) --- Logging error ---
(objective pid=1884537) Traceback (most recent call last):
(objective pid=1884537)   File "/usr/lib/python3.8/logging/__init__.py", line 1088, in emit
(objective pid=1884537)     stream.write(msg + self.terminator)
(objective pid=1884537)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/tune/utils/util.py", line 235, in write
(objective pid=1884537)     self.stream2.write(*args, **kwargs)
(objective pid=1884537) ValueError: I/O operation on closed file.
(objective pid=1884537) Call stack:
(objective pid=1884537)   File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
(objective pid=1884537)     self._bootstrap_inner()
(objective pid=1884537)   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
(objective pid=1884537)     self.run()
(objective pid=1884537)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 289, in run
(objective pid=1884537)     self._entrypoint()
(objective pid=1884537)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 362, in entrypoint
(objective pid=1884537)     return self._trainable_func(
(objective pid=1884537)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
(objective pid=1884537)     return method(self, *_args, **_kwargs)
(objective pid=1884537)   File "/home/tadej/.local/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 684, in _trainable_func
(objective pid=1884537)     output = fn()
(objective pid=1884537)   File "error_test.py", line 12, in objective
(objective pid=1884537)     logger.error("Woke up")
(objective pid=1884537) Message: 'Woke up'
(objective pid=1884537) Arguments: ()
Trial objective_c5b7827e completed. Last result: score=14.475011069983289
Trial objective_c5c1286a reported score=8.32 with parameters={'a': 1.5151023617766124, 'b': 6.800279838387811}.
Trial objective_c5c1286a completed. Last result: score=8.315382200164423
Trial objective_c5c26da6 reported score=9.65 with parameters={'a': 5.231338959479611, 'b': 4.4146533056979305}.
Trial objective_c5c26da6 completed. Last result: score=9.645992265177542
Trial objective_c5b90270 reported score=10.41 with parameters={'a': 7.049496105461197, 'b': 3.3620708428366664}.
Trial objective_c5b90270 completed. Last result: score=10.411566948297864
Trial objective_c5baaf94 reported score=4.83 with parameters={'a': 3.6002904023180973, 'b': 1.233169381589465}.
Trial objective_c5baaf94 completed. Last result: score=4.833459783907562
Trial objective_c5c3e21c reported score=12.09 with parameters={'a': 8.948163211139228, 'b': 3.1462509208487544}.
Trial objective_c5c3e21c completed. Last result: score=12.094414131987982
Trial objective_c5c7b702 reported score=7.29 with parameters={'a': 1.5049509239591896, 'b': 5.782908311915474}.
Trial objective_c5c7b702 completed. Last result: score=7.287859235874663
Trial objective_c5b64b8e reported score=10.74 with parameters={'a': 8.582132612793242, 'b': 2.1582872726211013}.
Trial objective_c5b64b8e completed. Last result: score=10.740419885414344
Trial objective_c5bbd798 reported score=11.56 with parameters={'a': 3.3781975787344143, 'b': 8.178174414499026}.
Trial objective_c5bfaddc reported score=18.53 with parameters={'a': 9.750015850101693, 'b': 8.784110596832923}.
Trial objective_c5bbd798 completed. Last result: score=11.55637199323344
Trial objective_c5bfaddc completed. Last result: score=18.534126446934614
Trial objective_c5c55f84 reported score=19.26 with parameters={'a': 9.327002185711944, 'b': 9.935447820822596}.
Trial objective_c5c55f84 completed. Last result: score=19.26245000653454
Trial objective_c5c9f5f8 reported score=10.83 with parameters={'a': 4.682692376373546, 'b': 6.14279950429858}.
== Status ==
Current time: 2022-10-05 08:14:55 (running for 00:00:11.28)
Memory usage on this node: 3.6/31.3 GiB
Using FIFO scheduling algorithm.
Resources requested: 4.0/16 CPUs, 0/2 GPUs, 0.0/17.35 GiB heap, 0.0/8.68 GiB objects (0.0/1.0 accelerator_type:G)
Current best trial: c5c55f84 with score=19.26245000653454 and parameters={'a': 9.327002185711944, 'b': 9.935447820822596}
Result logdir: /workspaces/trackers/results/test
Number of trials: 20/20 (4 RUNNING, 16 TERMINATED)


Trial objective_c5c9f5f8 completed. Last result: score=10.825491880672125
Trial objective_c8b3ac78 reported score=14.30 with parameters={'a': 9.040820010099536, 'b': 5.255036293739873}.
Trial objective_c8b3ac78 completed. Last result: score=14.295856303839408
Trial objective_c9bb3816 reported score=14.69 with parameters={'a': 4.926071167701915, 'b': 9.759884620368865}.
Trial objective_c9bb3816 completed. Last result: score=14.68595578807078
Trial objective_c9bc237a reported score=17.21 with parameters={'a': 9.622422643506264, 'b': 7.586523263717245}.
Trial objective_c9bc237a completed. Last result: score=17.20894590722351
== Status ==
Current time: 2022-10-05 08:14:57 (running for 00:00:13.01)
Memory usage on this node: 3.2/31.3 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/16 CPUs, 0/2 GPUs, 0.0/17.35 GiB heap, 0.0/8.68 GiB objects (0.0/1.0 accelerator_type:G)
Current best trial: c5c55f84 with score=19.26245000653454 and parameters={'a': 9.327002185711944, 'b': 9.935447820822596}
Result logdir: /workspaces/trackers/results/test
Number of trials: 20/20 (20 TERMINATED)
+--------------------+------------+--------------------+---------+---------+--------+------------------+----------+
| Trial name         | status     | loc                |       a |       b |   iter |   total time (s) |    score |
|--------------------+------------+--------------------+---------+---------+--------+------------------+----------|
| objective_c4fce3ec | TERMINATED | 172.17.0.2:1884423 | 6.02623 | 2.96714 |      1 |          5.02284 |  8.99338 |
| objective_c5b3c288 | TERMINATED | 172.17.0.2:1884536 | 3.7542  | 7.2831  |      1 |          5.00767 | 11.0373  |
| objective_c5b5457c | TERMINATED | 172.17.0.2:1884537 | 9.19721 | 2.2468  |      1 |          5.0033  | 11.444   |
| objective_c5b64b8e | TERMINATED | 172.17.0.2:1884538 | 8.58213 | 2.15829 |      1 |          5.03497 | 10.7404  |
| objective_c5b7827e | TERMINATED | 172.17.0.2:1884539 | 8.50706 | 5.96795 |      1 |          5.02452 | 14.475   |
| objective_c5b90270 | TERMINATED | 172.17.0.2:1884542 | 7.0495  | 3.36207 |      1 |          5.02278 | 10.4116  |
| objective_c5baaf94 | TERMINATED | 172.17.0.2:1884544 | 3.60029 | 1.23317 |      1 |          5.02993 |  4.83346 |
| objective_c5bbd798 | TERMINATED | 172.17.0.2:1884546 | 3.3782  | 8.17817 |      1 |          5.05083 | 11.5564  |
| objective_c5bd259e | TERMINATED | 172.17.0.2:1884548 | 1.89728 | 3.83037 |      1 |          5.02543 |  5.72765 |
| objective_c5be68b4 | TERMINATED | 172.17.0.2:1884550 | 6.06655 | 6.05607 |      1 |          5.02409 | 12.1226  |
| objective_c5bfaddc | TERMINATED | 172.17.0.2:1884551 | 9.75002 | 8.78411 |      1 |          5.034   | 18.5341  |
| objective_c5c1286a | TERMINATED | 172.17.0.2:1884554 | 1.5151  | 6.80028 |      1 |          5.02209 |  8.31538 |
| objective_c5c26da6 | TERMINATED | 172.17.0.2:1884556 | 5.23134 | 4.41465 |      1 |          5.02464 |  9.64599 |
| objective_c5c3e21c | TERMINATED | 172.17.0.2:1884558 | 8.94816 | 3.14625 |      1 |          5.04343 | 12.0944  |
| objective_c5c55f84 | TERMINATED | 172.17.0.2:1884560 | 9.327   | 9.93545 |      1 |          5.02646 | 19.2625  |
| objective_c5c7b702 | TERMINATED | 172.17.0.2:1884563 | 1.50495 | 5.78291 |      1 |          5.02664 |  7.28786 |
| objective_c5c9f5f8 | TERMINATED | 172.17.0.2:1884423 | 4.68269 | 6.1428  |      1 |          5.02665 | 10.8255  |
| objective_c8b3ac78 | TERMINATED | 172.17.0.2:1884536 | 9.04082 | 5.25504 |      1 |          5.02634 | 14.2959  |
| objective_c9bb3816 | TERMINATED | 172.17.0.2:1884537 | 4.92607 | 9.75988 |      1 |          5.02404 | 14.686   |
| objective_c9bc237a | TERMINATED | 172.17.0.2:1884550 | 9.62242 | 7.58652 |      1 |          5.02612 | 17.2089  |
+--------------------+------------+--------------------+---------+---------+--------+------------------+----------+


2022-10-05 08:14:57,679 INFO tune.py:758 -- Total run time: 13.22 seconds (13.00 seconds for the tuning loop).
{'a': 3.6002904023180973, 'b': 1.233169381589465}
```

</details>

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by Yard1** [comment]
Hey @tadejsv, I can reproduce this issue, but I am unsure if this is something we can fix on our side. I managed to run it successfully by initialising the logger outside the objective function:

```python
logging.basicConfig(format="%(levelname)s:%(message)s", level=logging.DEBUG)
logger = logging.getLogger(__name__)


def objective(config):
    logger.error("Woke up")
    score = config["a"] + config["b"]
    time.sleep(5)
    return {"score": score}
```

Would that be an acceptable workaround for you?

**Comment by Yard1** [comment]
I'll close this issue for now - feel free to reopen if needed.
