### ISSUE TITLE
How does on use Ray Tune with keras functional models?

### ISSUE THREAD

**Issue by ruojol** [ray-project/ray#2911]
### System information
- **Linux Ubuntu 16.04)**:
- **Current dev version of Ray Tune**:
- **Python 3.5**:
-**Cloudera DataScience Workbench 1.4**

Solved

**Comment by richardliaw** [comment]
Hi @ruojol, at a high level the code looks fine. Tune isn't affected by the way you construct your model.

Was there any issue with the above code?

**Comment by ruojol** [comment]
There seems to be some problem with the model definition when I shifted to using the generator. Now it stops on the first epoch, so not sure what the problem underneath is atm.

**Comment by richardliaw** [comment]
Can you post some error logs? That would be helpful for me to pinpoint your issue. Thanks!

**Comment by ruojol** [comment]
Keras doesn't give out any errors it just freezer during the first epoch so I think that this is more related to my datagenerator and model spesification than ray tune

**Comment by ruojol** [comment]
The function g has a **kwargs argument, which is currently not supported.
Created LogSyncer for /home/cdsw/ray_results/pbt_DAE/DAE_Model_1_bias_reg=0.0079559,dropout=0.51035,lr=0.037972,ouput_regularizer=0.007216,weight_reg=0.0034159_2018-09-26_05-04-035yj9pwn4 -> 
Remote function train failed with:

Traceback (most recent call last):
  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/worker.py", line 931, in _process_task
    *arguments)
  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 142, in train
    result = self._train()
  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 278, in _train
    raise NotImplementedError
NotImplementedError

**Comment by ruojol** [comment]
The error propably rises from this threadsafe generator class `   class Threadsafe_Iter:
       """Takes an iterator/generator and makes it thread-safe by
       serializing call to the `next` method of given iterator/generator.
       Can be run both on fit_generator(...workers=x,...use_multiprocessing=True/False)
       If use_multiprocessing = True creates a generator per CPU
       """
       def __init__(self, it):
           self.it = it
           self.lock = threading.Lock()
   
       def __iter__(self):
           return self
   
       def __next__(self):
           with self.lock:
               return self.it.__next__()
   
   
   def threadsafe_generator(lock=None):
    def wrap(f):
        """A decorator that takes a generator function and makes it thread-safe.
        Taken from
        http://anandology.com/blog/using-iterators-and-generators/
        """
        def g(*a, **kw):
            return threadsafe_iter(f(*a, **kw), lock=lock)
        return g
    return wrap
   
   @threadsafe_generator(lock=None)
   def custom_generator(data=train, batch_size=32, num_negatives=1):
       user_input, item_input, labels = data_generator(data, num_negatives)
       print('generator initiated')
       X_train = np.array(user_input)
       Y_train = np.array(item_input)
       y_train = np.array(labels)
       idx=0
       while True:
           for i in range(p['n_users']):
               index = np.random.choice(len(labels))
               X_train[i] = X_train[index]
               Y_train[i] = Y_train[index]
               y_train[i] = y_train[index]
               X = [X_train[:batch_size], Y_train[:batch_size]]
               y = y_train[:batch_size]
               yield X, y
               print('generator yielded a batch %d' % idx)
               idx+=1`

**Comment by ruojol** [comment]
```
ray.error_info()

[{'data': '{}',
  'message': 'Warning: The actor DAE_Model has size 157591933 when pickled. It will be stored in Redis, which could cause memory issues. This may mean that its definition uses a large array or other object.',
  'type': 'pickling_large_object'},
 {'data': '{\'function_id\': b\'\\xaa,H\\x9a\\xa5\\x94\\x10_\\xd6}\\x99\\x16{\\xcd\\x15;\\x9f"3\\xd3\', \'function_name\': \'train\'}',
  'message': 'Remote function \x1b[31mtrain\x1b[39m failed with:\n\nTraceback (most recent call last):\n  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/worker.py", line 931, in _process_task\n    *arguments)\n  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor\n    method_returns = method(actor, *args)\n  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 142, in train\n    result = self._train()\n  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 278, in _train\n    raise NotImplementedError\nNotImplementedError\n',
  'type': 'task'},
 {'data': '{}',
  'message': 'Warning: The actor DAE_Model has size 157591933 when pickled. It will be stored in Redis, which could cause memory issues. This may mean that its definition uses a large array or other object.',
  'type': 'pickling_large_object'},
 {'data': '{\'function_id\': b\'\\xaa,H\\x9a\\xa5\\x94\\x10_\\xd6}\\x99\\x16{\\xcd\\x15;\\x9f"3\\xd3\', \'function_name\': \'train\'}',
  'message': 'Remote function \x1b[31mtrain\x1b[39m failed with:\n\nTraceback (most recent call last):\n  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/worker.py", line 931, in _process_task\n    *arguments)\n  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor\n    method_returns = method(actor, *args)\n  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 142, in train\n    result = self._train()\n  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 278, in _train\n    raise NotImplementedError\nNotImplementedError\n',
  'type': 'task'},
 {'data': '{}',
  'message': 'Warning: The actor DAE_Model has size 157591933 when pickled. It will be stored in Redis, which could cause memory issues. This may mean that its definition uses a large array or other object.',
  'type': 'pickling_large_object'},
 {'data': '{\'function_id\': b\'\\xaa,H\\x9a\\xa5\\x94\\x10_\\xd6}\\x99\\x16{\\xcd\\x15;\\x9f"3\\xd3\', \'function_name\': \'train\'}',
  'message': 'Remote function \x1b[31mtrain\x1b[39m failed with:\n\nTraceback (most recent call last):\n  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/worker.py", line 931, in _process_task\n    *arguments)\n  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor\n    method_returns = method(actor, *args)\n  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 142, in train\n    result = self._train()\n  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 278, in _train\n    raise NotImplementedError\nNotImplementedError\n',
  'type': 'task'},
 {'data': '{}',
  'message': 'Warning: The actor DAE_Model has size 157591933 when pickled. It will be stored in Redis, which could cause memory issues. This may mean that its definition uses a large array or other object.',
  'type': 'pickling_large_object'},
 {'data': '{\'function_id\': b\'\\xaa,H\\x9a\\xa5\\x94\\x10_\\xd6}\\x99\\x16{\\xcd\\x15;\\x9f"3\\xd3\', \'function_name\': \'train\'}',
  'message': 'Remote function \x1b[31mtrain\x1b[39m failed with:\n\nTraceback (most recent call last):\n  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/worker.py", line 931, in _process_task\n    *arguments)\n  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor\n    method_returns = method(actor, *args)\n  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 142, in train\n    result = self._train()\n  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 278, in _train\n    raise NotImplementedError\nNotImplementedError\n',
  'type': 'task'}]
```

**Comment by ruojol** [comment]
```
run_experiments({"pbt_DAE_test": train_spec}, scheduler=pbt)

== Status ==
PopulationBasedTraining: 0 checkpoints, 0 perturbs


Created LogSyncer for /home/cdsw/ray_results/pbt_DAE_test/DAE_Model_0_bias_reg=0.0095915,dropout=0.5964,encoding_activation=relu,hidden_activation=elu,kernel_initializer=uniform,lr=0.09503_2018-09-27_08-59-140mtq9m9a -> 
== Status ==
PopulationBasedTraining: 0 checkpoints, 0 perturbs
Resources requested: 16/48 CPUs, 0/0 GPUs
Result logdir: /home/cdsw/ray_results/pbt_DAE_test
PENDING trials:
 - DAE_Model_1_bias_reg=0.0071026,dropout=0.22185,encoding_activation=sigmoid,hidden_activation=elu,kernel_initializer=uniform,lr=0.09687,ouput_regularizer=0.0027303,weight_reg=0.0027847:	PENDING
 - DAE_Model_2_bias_reg=0.0024007,dropout=0.68916,encoding_activation=relu,hidden_activation=relu,kernel_initializer=uniform,lr=0.019036,ouput_regularizer=0.0022855,weight_reg=0.0075492:	PENDING
 - DAE_Model_3_bias_reg=0.0007085,dropout=0.76486,encoding_activation=sigmoid,hidden_activation=relu,kernel_initializer=uniform,lr=0.076834,ouput_regularizer=0.0042106,weight_reg=0.0092844:	PENDING
 - DAE_Model_4_bias_reg=0.0049972,dropout=0.10605,encoding_activation=relu,hidden_activation=elu,kernel_initializer=normal,lr=0.066396,ouput_regularizer=0.0099437,weight_reg=0.0033373:	PENDING
 - DAE_Model_5_bias_reg=0.0068268,dropout=0.38129,encoding_activation=sigmoid,hidden_activation=elu,kernel_initializer=normal,lr=0.046873,ouput_regularizer=0.0051698,weight_reg=0.0078078:	PENDING
 - DAE_Model_6_bias_reg=0.006143,dropout=0.89833,encoding_activation=relu,hidden_activation=relu,kernel_initializer=normal,lr=0.0092306,ouput_regularizer=0.0029451,weight_reg=0.0019003:	PENDING
 - DAE_Model_7_bias_reg=0.0087893,dropout=0.43026,encoding_activation=sigmoid,hidden_activation=relu,kernel_initializer=normal,lr=0.026148,ouput_regularizer=0.0085478,weight_reg=0.006145:	PENDING
RUNNING trials:
 - DAE_Model_0_bias_reg=0.0095915,dropout=0.5964,encoding_activation=relu,hidden_activation=elu,kernel_initializer=uniform,lr=0.095036,ouput_regularizer=0.0012393,weight_reg=0.0017658:	RUNNING

Created LogSyncer for /home/cdsw/ray_results/pbt_DAE_test/DAE_Model_1_bias_reg=0.0071026,dropout=0.22185,encoding_activation=sigmoid,hidden_activation=elu,kernel_initializer=uniform,lr=0.0_2018-09-27_08-59-14p96gk351 -> 
Created LogSyncer for /home/cdsw/ray_results/pbt_DAE_test/DAE_Model_2_bias_reg=0.0024007,dropout=0.68916,encoding_activation=relu,hidden_activation=relu,kernel_initializer=uniform,lr=0.019_2018-09-27_08-59-14vb6lzbfn -> 
Remote function train failed with:

Traceback (most recent call last):
  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/worker.py", line 931, in _process_task
    *arguments)
  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 142, in train
    result = self._train()
  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 278, in _train
    raise NotImplementedError
NotImplementedError

Suppressing duplicate error message.
Suppressing duplicate error message.
fetch_one_result failed: Traceback (most recent call last):
  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 165, in fetch_one_result
    result = ray.get(result_id)
  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/worker.py", line 2506, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(8fb90e5aad86f2ef8983ccb83c2e3b28a18d396c). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/worker.py", line 931, in _process_task
    *arguments)
  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 142, in train
    result = self._train()
  File "/home/cdsw/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 278, in _train
    raise NotImplementedError
NotImplementedError
```

**Comment by ruojol** [comment]
I think that the class isn't loading the data and or the generator isn't working since train never goes to fit_generator stage.
