### ISSUE TITLE
[data] map_groups doesn't allow returning a list of simple values

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#29175]
It seems like unlike map_batches, with map_groups you have to return a pd.DataFrame, even if you want to return a list of simple results. I would expect returning a list to create a dataset of simple list blocks:

```
import ray
import pandas as pd

ds = ray.data.from_items([
    {"group": 1, "value": 1},
    {"group": 1, "value": 2},
    {"group": 2, "value": 3},
    {"group": 2, "value": 4},
])

def func(group):
    return [1,2,3]

ds.groupby("group").map_groups(func).show()
```

```
(_map_block_nosplit pid=657829) Traceback (most recent call last):
(_map_block_nosplit pid=657829)   File "python/ray/_raylet.pyx", line 662, in ray._raylet.execute_task
(_map_block_nosplit pid=657829)   File "python/ray/_raylet.pyx", line 666, in ray._raylet.execute_task
(_map_block_nosplit pid=657829)   File "/home/eric/.local/lib/python3.8/site-packages/ray/data/_internal/compute.py", line 449, in _map_block_nosplit
(_map_block_nosplit pid=657829)     for new_block in block_fn(block, *fn_args, **fn_kwargs):
(_map_block_nosplit pid=657829)   File "/home/eric/.local/lib/python3.8/site-packages/ray/data/dataset.py", line 457, in transform
(_map_block_nosplit pid=657829)     applied = batch_fn(view, *fn_args, **fn_kwargs)
(_map_block_nosplit pid=657829)   File "/home/eric/.local/lib/python3.8/site-packages/ray/data/grouped_dataset.py", line 282, in group_fn
(_map_block_nosplit pid=657829)     builder.add_block(applied)
(_map_block_nosplit pid=657829)   File "/home/eric/.local/lib/python3.8/site-packages/ray/data/_internal/table_block.py", line 57, in add_block
(_map_block_nosplit pid=657829)     raise TypeError(
(_map_block_nosplit pid=657829) TypeError: Got a block of type <class 'list'>, expected <class 'pandas.core.frame.DataFrame'>.If you are mapping a function, ensure it returns an object with the expected type. Block:
```

**Comment by c21** [comment]
We should use `DelegatingBlockBuilder` here - https://github.com/ray-project/ray/blob/master/python/ray/data/grouped_dataset.py#L320 . Will put up a fix today.
