### ISSUE TITLE
[Core] `py_modules` does not support imported modules

### ISSUE THREAD

**Issue by simonsays1980** [ray-project/ray#29200]
### What happened + What you expected to happen

I have a custom package I installed into my virtual environment. In my script I import this package and pass it to `runtime_env` like this:

```python
import my_module
ray.init(runtime_env={"py_modules": [my_module]})
```
I get an error: 
```
Traceback (most recent call last):
  File "/home/simon/git-projects/eplus-external-env/eplus_policy_server.py", line 80, in <module>
    ray.init(local_mode=args.local_mode, runtime_env={"py_modules": [eplus_env]})
  File "/home/simon/git-projects/eplus-external-env/.venv/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/simon/git-projects/eplus-external-env/.venv/lib/python3.9/site-packages/ray/_private/worker.py", line 1520, in init
    connect(
  File "/home/simon/git-projects/eplus-external-env/.venv/lib/python3.9/site-packages/ray/_private/worker.py", line 1995, in connect
    serialized_job_config = job_config.serialize()
  File "/home/simon/git-projects/eplus-external-env/.venv/lib/python3.9/site-packages/ray/job_config.py", line 51, in serialize
    return self.get_proto_job_config().SerializeToString()
  File "/home/simon/git-projects/eplus-external-env/.venv/lib/python3.9/site-packages/ray/job_config.py", line 114, in get_proto_job_config
    parsed_env = self._validate_runtime_env()
  File "/home/simon/git-projects/eplus-external-env/.venv/lib/python3.9/site-packages/ray/job_config.py", line 94, in _validate_runtime_env
    return RuntimeEnv(**self.runtime_env)
  File "/home/simon/git-projects/eplus-external-env/.venv/lib/python3.9/site-packages/ray/runtime_env/runtime_env.py", line 329, in __init__
    self[option] = option_val
  File "/home/simon/git-projects/eplus-external-env/.venv/lib/python3.9/site-packages/ray/runtime_env/runtime_env.py", line 356, in __setitem__
    res_value = OPTION_TO_VALIDATION_FN[key](jsonable_type)
  File "/home/simon/git-projects/eplus-external-env/.venv/lib/python3.9/site-packages/ray/_private/runtime_env/validation.py", line 44, in parse_and_validate_py_modules
    validate_uri(uri)
  File "/home/simon/git-projects/eplus-external-env/.venv/lib/python3.9/site-packages/ray/_private/runtime_env/validation.py", line 14, in validate_uri
    raise TypeError(
TypeError: URIs for working_dir and py_modules must be strings, got <class 'module'>.
```

This is due to the fact that the [validation](https://github.com/ray-project/ray/blob/ed06ceb68d42a02655b136d9cf8149f3a07b1231/python/ray/_private/runtime_env/validation.py#L33) happens to check only for URIs and nothing else. Shouldn't there be also a validation for imported python modules?  

### Versions / Dependencies

Fedora 34
Python 3.9.0
Ray 2.0.0

### Reproduction script

Try to import any module and pass it into the `runtime_env`

```python
import my_module
ray.init(runtime_env={"py_modules": [my_module]})
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by hora-anyscale** [comment]
Per Triage Sync: @architkulkarni any thoughts here?

**Comment by architkulkarni** [comment]
@hora-anyscale Thanks for the ping, the prioritization is correct.  

@simonsays1980 Thanks for reporting this!  Until this is fixed, I think the following workaround will work: pass in the `runtime_env` in the `@ray.remote()` decorator for your tasks and actors instead of `ray.init()`.

**Comment by architkulkarni** [comment]
@simonsays1980 do you know if local mode is being set to `True` in your reproduction?

**Comment by simonsays1980** [comment]
> @simonsays1980 do you know if local mode is being set to `True` in your reproduction?

@architkulkarni Thanks for coming back to this. I cannot remember to be honest. I usually have `local_mode=False` by default.

**Comment by jmakov** [comment]
Stumbled on the same exception. In my case `local_mode=True`.
