### ISSUE TITLE
[python3.10] cannot import name 'GenericAlias' due to circular import

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29236]
### What happened + What you expected to happen

```


Traceback (most recent call last):
  File "/data/home/rickyx/ray/python/ray/setup-dev.py", line 6, in <module>
    import argparse
  File "/data/home/rickyx/anaconda3/envs/python310/lib/python3.10/argparse.py", line 89, in <module>
    import re as _re
  File "/data/home/rickyx/anaconda3/envs/python310/lib/python3.10/re.py", line 124, in <module>
    import enum
  File "/data/home/rickyx/anaconda3/envs/python310/lib/python3.10/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/data/home/rickyx/ray/python/ray/types.py", line 1, in <module>
    from typing import Generic, TypeVar
  File "/data/home/rickyx/anaconda3/envs/python310/lib/python3.10/typing.py", line 25, in <module>
    import contextlib
  File "/data/home/rickyx/anaconda3/envs/python310/lib/python3.10/contextlib.py", line 6, in <module>
    from functools import wraps
  File "/data/home/rickyx/anaconda3/envs/python310/lib/python3.10/functools.py", line 22, in <module>
    from types import GenericAlias
ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (/data/home/rickyx/ray/python/ray/types.py)
```

### Versions / Dependencies

Python3.10.6
4b79a6f1d270658eca3bf65df2b16b4e512f6513

### Reproduction script

`conda create --name python310 python=3.10`
`conda activate python310`

`python python/ray/setup-dev.py`

**Comment by rickyyx** [comment]
Actually if I do this, 

`conda create --name python310 python=3.10`
`conda activate python310`

`pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp310-cp310-manylinux2014_x86_64.whl` 

`python python/ray/setup-dev.py`


Things work fine. So maybe this is not an issue.
