### ISSUE TITLE
[Core] Remote decorator fails on class with jax.jitted function 

### ISSUE THREAD

**Issue by 011235813** [ray-project/ray#29238]
### What happened + What you expected to happen

I'm trying to use Ray to parallelize an Actor class that contains a function wrapped by Jax.
Although it seems to run correctly, there are error messages regarding the "socket".

> (raylet) Traceback (most recent call last):
(raylet)   File "/usr/WS2/yang40/venvs/amr_jax/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 366, in <module>
(raylet)     raise e
(raylet)   File "/usr/WS2/yang40/venvs/amr_jax/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 354, in <module>
(raylet)     loop.run_until_complete(agent.run())
(raylet)   File "/g/g92/yang40/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
(raylet)     return future.result()
(raylet)   File "/usr/WS2/yang40/venvs/amr_jax/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 144, in run
(raylet)     modules = self._load_modules()
(raylet)   File "/usr/WS2/yang40/venvs/amr_jax/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 98, in _load_modules
(raylet)     c = cls(self)
(raylet)   File "/usr/WS2/yang40/venvs/amr_jax/lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 148, in __init__
(raylet)     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)
(raylet)   File "/usr/WS2/yang40/venvs/amr_jax/lib/python3.8/site-packages/ray/_private/metrics_agent.py", line 75, in __init__
(raylet)     prometheus_exporter.new_stats_exporter(
(raylet)   File "/usr/WS2/yang40/venvs/amr_jax/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 333, in new_stats_exporter
(raylet)     exporter = PrometheusStatsExporter(
(raylet)   File "/usr/WS2/yang40/venvs/amr_jax/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 266, in __init__
(raylet)     self.serve_http()
(raylet)   File "/usr/WS2/yang40/venvs/amr_jax/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 320, in serve_http
(raylet)     start_http_server(
(raylet)   File "/usr/WS2/yang40/venvs/amr_jax/lib/python3.8/site-packages/prometheus_client/exposition.py", line 168, in start_wsgi_server
(raylet)     TmpServer.address_family, addr = _get_best_family(addr, port)
(raylet)   File "/usr/WS2/yang40/venvs/amr_jax/lib/python3.8/site-packages/prometheus_client/exposition.py", line 157, in _get_best_family
(raylet)     infos = socket.getaddrinfo(address, port)
(raylet)   File "/g/g92/yang40/lib/python3.8/socket.py", line 918, in getaddrinfo
(raylet)     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
(raylet) socket.gaierror: [Errno -2] Name or service not known

### Versions / Dependencies

jax==0.3.13
jaxlib==0.3.10+cuda11.cudnn805
ray==1.5.1

### Reproduction script

```
import ray
import jax

class Sequential:

    def __init__(self):

        self.x = 0
        self.increment = jax.jit(self.increment)

    def increment(self):

        self.x += 1
        print(self.x)

@ray.remote
class Parallel(Sequential):

    def __init__(self):

        super().__init__()


runners = [Parallel.remote() for i in range(10)]
ray.get([r.increment.remote() for r in runners]) # prints a bunch of 1s
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by 011235813** [comment]
Solve by upgrading from ray==1.5.1 to ray==1.13.0
