### ISSUE TITLE
Ray Data: Uploading Large Files Crashes Ray

### ISSUE THREAD

**Issue by vedantroy** [ray-project/ray#29379]
### What happened + What you expected to happen

The reproduction script, which uploads a 1GB binary file to S3 crashes on a m5.large machine.

It does not crash for a 500 MB file.
This in and of itself is not a problem, but I'm getting other flakiness with ray's `write_parquet` method, and I suspect this could??? be the source of the issue (not sure).

## Logs
```
Job submission server address: http://100.112.108.179:8265
Processing /tmp/ray/session_2022-10-14_23-48-01_556375_5764/runtime_resources/working_dir_files/_ray_pkg_136e87ef4f0c2fb0
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: distributed-ml
  Building wheel for distributed-ml (setup.py): started
  Building wheel for distributed-ml (setup.py): finished with status 'done'
  Created wheel for distributed-ml: filename=distributed_ml-0.0.0-py3-none-any.whl size=1173 sha256=0aca4e7b343c686da1ac09abd7475fe851e82d71777446575af084e0334dafef
  Stored in directory: /tmp/pip-ephem-wheel-cache-vjgtrblt/wheels/fb/6e/20/7cb03ca3b02bdf1d34bf414ed66a6e812596970409fb2834c7
Successfully built distributed-ml
Installing collected packages: distributed-ml
  Attempting uninstall: distributed-ml
    Found existing installation: distributed-ml 0.0.0
    Uninstalling distributed-ml-0.0.0:
      Successfully uninstalled distributed-ml-0.0.0
Successfully installed distributed-ml-0.0.0
2022-10-14 23:55:01,256 INFO worker.py:1223 -- Using address 172.31.39.99:6379 set in the environment variable RAY_ADDRESS
2022-10-14 23:55:01,256 INFO worker.py:1333 -- Connecting to existing Ray cluster at address: 172.31.39.99:6379...
2022-10-14 23:55:01,263 INFO worker.py:1509 -- Connected to Ray cluster. View the dashboard at http://172.31.39.99:8265 
Checking if can access bucket:
<FileInfo for 'data': type=FileType.Directory>
Running: head -c 1G </dev/urandom > /tmp/tmp1n5mjbsz/test_file
Sure file: /tmp/tmp1n5mjbsz/test_file exists, forcing full execution...
2022-10-14 23:55:07,246 WARNING read_api.py:280 -- ⚠️  The blocks of this dataset are estimated to be 2.0x larger than the target block size of 512 MiB. This may lead to out-of-memory errors during processing. Consider reducing the size of input files or using `.repartition(n)` to increase the number of dataset blocks.
Uploading file ...
2022-10-14 23:55:22,883 WARNING worker.py:1829 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 0ae379fdbebb0af611f87d440975d060460262ac04000000 Worker ID: ab787f5facdbb94e442f61eb16cfad8b9ec215436baffb42de1b730e Node ID: 4bbaf5f5b271e7ec08d4f4d98a5e6cac036aba3f6cc9209c92d08c59 Worker IP address: 172.31.39.99 Worker port: 10017 Worker PID: 6835 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
2022-10-14 23:55:35,348 WARNING worker.py:1829 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 89efda9b9c0de1e66c9391d26d443ece4a5fe06104000000 Worker ID: cd66559b3cd2178bb2f703d5e6fce3fd2b323a9919aa769ee6432f6f Node ID: 4bbaf5f5b271e7ec08d4f4d98a5e6cac036aba3f6cc9209c92d08c59 Worker IP address: 172.31.39.99 Worker port: 10015 Worker PID: 6767 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
2022-10-14 23:55:35,363 WARNING worker.py:2278 -- Local object store memory usage:

(global lru) capacity: 2186761420
(global lru) used: 0%
(global lru) num objects: 0
(global lru) num evictions: 0
(global lru) bytes evicted: 0

Traceback (most recent call last):
  File "cluster_scripts/test_s3.py", line 29, in <module>
    items.write_parquet(path=S3_DEST_URL, filesystem=fs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/dataset.py", line 1999, in write_parquet
    self.write_datasource(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/dataset.py", line 2242, in write_datasource
    datasource.on_write_complete(ray.get(write_results))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/worker.py", line 2282, in get
    raise value
ray.exceptions.OwnerDiedError: Failed to retrieve object e4913f0f723b0040ffffffffffffffffffffffff0400000001000000. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.

The object's owner has exited. This is the Python worker that first created the ObjectRef via `.remote()` or `ray.put()`. Check cluster logs (`/tmp/ray/session_latest/logs/*cd66559b3cd2178bb2f703d5e6fce3fd2b323a9919aa769ee6432f6f*` at IP address 172.31.39.99) for more information about the Python worker failure.
```

### Versions / Dependencies

Python:
```
Package                                Version
-------------------------------------- ---------
adal                                   1.2.7
aiohttp                                3.8.3
aiohttp-cors                           0.7.0
aiorwlock                              1.3.0
aiosignal                              1.2.0
anyio                                  3.6.1
applicationinsights                    0.11.10
argcomplete                            1.12.3
asgiref                                3.5.2
async-timeout                          4.0.2
attrs                                  22.1.0
av                                     9.2.0
azure-cli-core                         2.29.1
azure-cli-telemetry                    1.0.6
azure-common                           1.1.28
azure-core                             1.26.0
azure-identity                         1.7.0
azure-mgmt-compute                     23.1.0
azure-mgmt-core                        1.2.2
azure-mgmt-network                     19.0.0
azure-mgmt-resource                    20.0.0
backoff                                1.10.0
bcrypt                                 4.0.0
blessed                                1.19.1
boto3                                  1.4.8
botocore                               1.8.50
brotlipy                               0.7.0
cachetools                             5.2.0
certifi                                2022.9.24
cffi                                   1.15.0
chardet                                4.0.0
charset-normalizer                     2.0.4
click                                  8.0.4
cloudpickle                            2.2.0
colorama                               0.4.4
colorful                               0.5.4
conda                                  22.9.0
conda-content-trust                    0+unknown
conda-package-handling                 1.8.1
contourpy                              1.0.5
cryptography                           37.0.1
cycler                                 0.11.0
Cython                                 0.29.26
distlib                                0.3.6
dm-tree                                0.1.7
docutils                               0.19
fastapi                                0.85.0
filelock                               3.8.0
flatbuffers                            22.9.24
fonttools                              4.37.4
frozenlist                             1.3.1
fsspec                                 2022.8.2
google-api-core                        2.10.1
google-api-python-client               1.7.8
google-auth                            2.12.0
google-auth-httplib2                   0.1.0
google-oauth                           1.0.1
googleapis-common-protos               1.56.4
gpustat                                1.0.0
grpcio                                 1.43.0
gym                                    0.23.1
gym-notices                            0.0.8
h11                                    0.14.0
httplib2                               0.20.4
humanfriendly                          9.2
idna                                   2.10
imageio                                2.22.1
importlib-metadata                     5.0.0
importlib-resources                    5.9.0
iso8601                                1.1.0
isodate                                0.6.1
jmespath                               0.10.0
jsonschema                             4.16.0
kiwisolver                             1.4.4
knack                                  0.8.2
kopf                                   1.35.6
kubernetes                             24.2.0
lz4                                    4.0.2
matplotlib                             3.6.0
msal                                   1.19.0
msal-extensions                        0.3.1
msgpack                                1.0.4
msrest                                 0.7.1
msrestazure                            0.6.4
multidict                              6.0.2
networkx                               2.8.7
numpy                                  1.23.3
nvidia-ml-py                           11.495.46
oauthlib                               3.2.1
opencensus                             0.11.0
opencensus-context                     0.1.3
opentelemetry-api                      1.1.0
opentelemetry-exporter-otlp            1.1.0
opentelemetry-exporter-otlp-proto-grpc 1.1.0
opentelemetry-proto                    1.1.0
opentelemetry-sdk                      1.1.0
opentelemetry-semantic-conventions     0.20b0
packaging                              21.3
pandas                                 1.5.0
paramiko                               2.11.0
Pillow                                 9.2.0
pip                                    22.2.2
pkginfo                                1.8.3
pkgutil_resolve_name                   1.3.10
platformdirs                           2.5.2
portalocker                            1.7.1
prometheus-client                      0.13.1
protobuf                               3.20.1
psutil                                 5.9.2
py-spy                                 0.3.14
pyarrow                                6.0.1
pyasn1                                 0.4.8
pyasn1-modules                         0.2.8
pycosat                                0.6.3
pycparser                              2.21
pydantic                               1.10.2
Pygments                               2.13.0
PyJWT                                  2.5.0
PyNaCl                                 1.5.0
pyOpenSSL                              22.0.0
pyparsing                              3.0.9
pyrsistent                             0.18.1
PySocks                                1.7.1
python-dateutil                        2.8.2
python-json-logger                     2.0.4
pytz                                   2022.4
PyWavelets                             1.4.1
PyYAML                                 6.0
ray                                    2.0.1
ray-cpp                                2.0.1
redis                                  3.5.3
requests                               2.25.1
requests-oauthlib                      1.3.1
rsa                                    4.9
ruamel-yaml-conda                      0.15.100
s3transfer                             0.1.13
scikit-image                           0.19.3
scipy                                  1.9.1
setuptools                             63.4.1
six                                    1.13.0
smart-open                             6.2.0
sniffio                                1.3.0
starlette                              0.20.4
structlog                              22.1.0
tabulate                               0.9.0
tensorboardX                           2.5.1
tifffile                               2022.8.12
toolz                                  0.11.2
tqdm                                   4.63.0
types-cryptography                     3.3.23
typing_extensions                      4.4.0
uritemplate                            3.0.1
urllib3                                1.26.8
uvicorn                                0.16.0
virtualenv                             20.16.5
wcwidth                                0.2.5
websocket-client                       1.4.1
wheel                                  0.37.1
yarl                                   1.8.1
zipp                                   3.8.1
```

Using a modified version of `rayproject/ray:2.0.1-py38-cpu`.

### Reproduction script

```
from pathlib import Path
import os
import subprocess
import tempfile

import pyarrow.fs as arrow_fs
import ray

from distributed_ml.config.s3 import S3Config

ray.init()

# I have a helper class to read an S3 config, but you can just manually plug it in ...
fs = arrow_fs.S3FileSystem(**S3Config().dict())
print("Checking if can access bucket:")
print(fs.get_file_info(os.environ["S3_BUCKET_NAME"]))

S3_DEST_URL = os.environ["S3_DEST_URL"]

with tempfile.TemporaryDirectory() as dir:
    ray.data.set_progress_bars(False)
    final_path = f"{dir}/test_file"
    command = f"head -c 1G </dev/urandom > {final_path}"
    print(f"Running: {command}")
    proc = subprocess.run(command, shell=True, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    assert Path(final_path).is_file()
    print(f"Sure file: {final_path} exists, forcing full execution...")
    items = ray.data.read_binary_files(paths=dir).fully_executed()
    print("Uploading file ...")
    items.write_parquet(path=S3_DEST_URL, filesystem=fs)

print("Success!")
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by c21** [comment]
@vedantroy - thanks for reporting. This looks OOM when writing the Parquet file to S3. Internally in Ray Datasets, we are using [PyArrow](https://arrow.apache.org/docs/python/index.html) to read and write files.

m5.large only has 8GB memory, it looks too tight to read and write 1GB binary data here (Ray object store memory takes 2GB already). Can you try with a larger machine - m5.xlarge?

**Comment by c21** [comment]
@vedantroy - a separate question, what's the end-to-end use case here? Are you just trying to upload local binary file to S3 in Parquet format? Or you have other work to be done in Ray Datasets except that?

**Comment by hora-anyscale** [comment]
Per Triage Sync: @c21 assigning to you, please try to repro via script?
