### ISSUE TITLE
[Ray Log_monitor]: close_all_files ProcessLookupError

### ISSUE THREAD

**Issue by KimmiShi** [ray-project/ray#29452]
### What happened + What you expected to happen

1. the error log:
```
The log monitor on node 10-140-24-21 failed with the following error:
Traceback (most recent call last):
  File "/mnt/xx/miniconda3/uniscale/lib/python3.7/site-packages/ray/_private/log_monitor.py", line 130, in close_all_files
    os.kill(file_info.worker_pid, 0)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/xx/miniconda3/uniscale/lib/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)
OSError: [Errno 16] Device or resource busy: '/mnt/xx/tmp/session_2022-10-19_09-36-59_337210_18272/logs/worker-5bf0d06af3101ada673cd25cebde4e860597eb7e05c1f975caf34c04-04000000-121637.err' -> '/mnt/xx/tmp/session_2022-10-19_09-36-59_337210_18272/logs/old/worker-5bf0d06af3101ada673cd25cebde4e860597eb7e05c1f975caf34c04-04000000-121637.err'

During handling of the above exception, another exception occurred:
...
```

2. expected behavior:
It should not abort?

### Versions / Dependencies

Ray  1.13

### Reproduction script

Sorry I cannot provide.

### Issue Severity

High: It blocks me from completing my task.

**Comment by hora-anyscale** [comment]
@AwesomePH - could you please share a repro script and confirm it happens on Ray 2.0?

**Comment by rkooo567** [comment]
The first one seems to be easy to fix. The second one is probably the env specific, and you might need to figure out why the device is busy. I think when you see this sort of error so many things will be broken at the same time

**Comment by rkooo567** [comment]
Hmm actually we properly catch the ProcesLookupError and not abort. https://github.com/ray-project/ray/blob/e4ce38d001dbbe09cd21c497fedd03d692b2be3e/python/ray/_private/log_monitor.py#L130

Are you sure you are using ray 1.13?

**Comment by AwesomePH** [comment]
Hi, I still do not know why `os.kill(file_info.worker_pid, 0)` would fail, but I solved the following exception:
```
Traceback (most recent call last):
  File "/mnt/xx/miniconda3/uniscale/lib/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)
OSError: [Errno 16] Device or resource busy:
```
This is due to the file system. So after I changed a file system the problem goes away. 
I guess there is still `os.kill(file_info.worker_pid, 0)`  issues but the exception handling succeeded.

**Comment by cszhu** [comment]
This P2 issue has seen no activity in the past 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please comment and remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
