### ISSUE TITLE
QMixagent.compute_single_action(obs['group_1'], state) error?

### ISSUE THREAD

**Issue by Coastline-lhy** [ray-project/ray#29496]
### What happened + What you expected to happen

ray_results/DangerUAV2_v1/QMIX/QMIX_DangerUAV2_v1_83686_00000_0_2022-10-05_13-49-20/checkpoint_001500/checkpoint-1500
2022-10-13 13:00:31,396	INFO trainable.py:669 -- Restored on 172.28.0.2 from checkpoint: ray_results/DangerUAV2_v1/QMIX/QMIX_DangerUAV2_v1_83686_00000_0_2022-10-05_13-49-20/checkpoint_001500
2022-10-13 13:00:31,397	INFO trainable.py:677 -- Current state after restoring: {'_iteration': 1500, '_timesteps_total': None, '_time_total': 18878.440465450287, '_episodes_total': 73197}
Traceback (most recent call last):
  File "rllib_test2_danger_v1.py", line 193, in <module>
    action,state_out,_=QMixagent.compute_single_action(obs['group_1'], state)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/algorithms/algorithm.py", line 1148, in compute_single_action
    episode=episode,
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/policy/policy.py", line 331, in compute_single_action
    timestep=timestep,
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/algorithms/qmix/qmix_policy.py", line 317, in compute_actions_from_input_dict
    explore=explore,
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/utils/exploration/epsilon_greedy.py", line 101, in get_exploration_action
    action_distribution, explore, timestep
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/utils/exploration/epsilon_greedy.py", line 188, in _get_torch_exploration_action
    epsilon = self.epsilon_schedule(self.last_timestep)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/utils/schedules/schedule.py", line 46, in __call__
    return self.value(t)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/utils/schedules/schedule.py", line 42, in value
    return self._value(t)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/utils/schedules/piecewise_schedule.py", line 62, in _value
    if l_t <= t < r_t:
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
t is None?How to solve it?

### Versions / Dependencies

python 3.7

### Reproduction script

grouping = {
        "group_1": [0, 1],
    }
   
obs_space = Tuple(
    [
        Dict(
            {
                "obs":env.obs_space,
                ENV_STATE: spaces.Box(low=0.0, high=1.0, shape=(1,42, 42), dtype=np.float32),
            }
        ),
        Dict(
            {
                "obs": env.obs_space,
                ENV_STATE: spaces.Box(low=0.0, high=1.0, shape=(1,42, 42), dtype=np.float32),
            }
        ),
    ]
)
act_space = Tuple(
    [
        Discrete(5),
        Discrete(5),
    ]
)
    
register_env(
    env_name,
    lambda config: env.with_agent_groups(
        grouping, obs_space=obs_space, act_space=act_space
    ),
)
    
env_config = {"max_steps": 200}

config={
    # Enviroment specific
    "env": env_name,
    "env_config": env_config,
    "framework": "torch",
    "mixer":"qmix",
    "mixing_embed_dim" : 32,
    "double_q" : True,
    "optim_alpha" : 0.99,
    "optim_eps" : 0.00001,
    "grad_clip" : 10,
    "in_evaluation": True,
    "lr" : 0.0005,
    "train_batch_size" : 32,
    "target_network_update_freq" : 500,
    "simple_optimizer":True,
    "replay_buffer_config" : {
        "type": "ReplayBuffer",
        # Specify prioritized replay by supplying a buffer type that supports
        # prioritization, for example: MultiAgentPrioritizedReplayBuffer.
        "prioritized_replay": DEPRECATED_VALUE,
        # Size of the replay buffer in batches
        "capacity": 1000,
        # Choosing `fragments` here makes it so that the buffer stores entire
        # batches, instead of sequences, episodes or timesteps.
        "storage_unit": "fragments",
        "learning_starts": 1000,
        # Whether to compute priorities on workers.
        "worker_side_prioritization": False,
    },
    #"model":{
    #    "custom_model": "CNNModelV2",
    #},
    "model" : {
                "lstm_cell_size": 64,
                "max_seq_len": 20,
                "fcnet_hiddens": [64,64],
                "max_seq_len": 20,
            },
    # .framework()
    #self.framework_str = "torch"

    # .rollouts()
    #"num_gpus": 1,
    #"num_workers": 0,
    "rollout_fragment_length" : 4,
    "batch_mode": 'truncate_episodes',

    # .reporting()
    "min_time_s_per_iteration" : 1,
    "min_sample_timesteps_per_iteration" : 1000,

    ## .exploration()
    "exploration_config" : {
        # The Exploration class to use.
        "type": "EpsilonGreedy",
        # Config for the Exploration class' constructor:
        "initial_epsilon": 0.0,
        "final_epsilon": 0.0,
        # Timesteps over which to anneal epsilon.
        "epsilon_timesteps": 40000,
    },
    "evaluation_config":{
            "explore": False,
                "env_config": {
                # Use test set to evaluate
                'mode': "test"}
    }
}

init_state = [np.zeros([2,64], np.float32) for _ in range(2)]

### Issue Severity

High: It blocks me from completing my task.

**Comment by Coastline-lhy** [comment]
I am sorry，just input timestep will solve it.
