### ISSUE TITLE
[tune] Hyperband bug that contains None in current band

### ISSUE THREAD

**Issue by old-bear** [ray-project/ray#2955]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.11
- **Ray installed from (source or binary)**: binary
- **Ray version**: master
- **Python version**: 2.7
- **Exact command to reproduce**: 

### Describe the problem

Here is the experiment code that triggers this bug:
```
def train_func(config, reporter):  # add a reporter arg
    for i in range(20):
        time.sleep(1)
        auc = random.random() + i
        reporter(timesteps_total=i, mean_accuracy=auc)  # report metrics

ray.init()
ray.tune.register_trainable("train_func", train_func)

trials = run_experiments({
    "my_experiment": {
        "run": "train_func",
        "stop": {"mean_accuracy": 99},
        "config": {
            "param1": grid_search(["a", "b", "c", "d"]),
            "param2": grid_search([1, 2, 3, 4, 5, 6]),
            "param3": tune.grid_search([1, 3])
        },
    }
}, scheduler=HyperBandScheduler(reward_attr='mean_accuracy', max_t=20))
```

After running this, a NoneType error occurs:
```
Traceback (most recent call last):
  File "/Users/Bear/Workspace/Alps-automl/python/alps/ray_test.py", line 40, in <module>
    }, scheduler=HyperBandScheduler(reward_attr='mean_accuracy', max_t=20))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ray/tune/tune.py", line 105, in run_experiments
    runner.step()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ray/tune/trial_runner.py", line 112, in step
    next_trial = self._get_next_trial()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ray/tune/trial_runner.py", line 233, in _get_next_trial
    trial = self._scheduler_alg.choose_trial_to_run(self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ray/tune/schedulers/hyperband.py", line 229, in choose_trial_to_run
    hyperband, key=lambda b: b.completion_percentage()):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ray/tune/schedulers/hyperband.py", line 229, in <lambda>
    hyperband, key=lambda b: b.completion_percentage()):
AttributeError: 'NoneType' object has no attribute 'completion_percentage'
```
It seems the experiment failed during the setup step (before running any trials)

### Source code / logs

After some debug trace into the source code, I think this bug originates from here in hyperband.py:
```
def on_trial_add(self, trial_runner, trial):
    ......
    cur_band = self._hyperbands[self._state["band_idx"]]    <---- 3. cur_band originated from
                                                    _hyperbands, thus _hyperbands contains None
    if cur_bracket is None or cur_bracket.filled():
        retry = True
        while retry:
            # if current iteration is filled, create new iteration
            if self._cur_band_filled():
                cur_band = []
                self._hyperbands.append(cur_band)
                self._state["band_idx"] += 1

            # cur_band will always be less than s_max_1 or else filled
            s = len(cur_band)
            assert s < self._s_max_1, "Current band is filled!"
            if self._get_r0(s) == 0:
                logger.info("Bracket too small - Retrying...")
                cur_bracket = None     <---- 1. cur_bracket is set to None
            else:
                retry = False
                cur_bracket = Bracket(self._time_attr, self._get_n0(s),
                                      self._get_r0(s), self._max_t_attr,
                                      self._eta, s)
            cur_band.append(cur_bracket)     <---- 2. None being added to cur_band
            self._state["bracket"] = cur_bracket


# This function will be called to setup all trials
def choose_trial_to_run(self, trial_runner):
    for hyperband in self._hyperbands:
        for bracket in sorted(
                hyperband, key=lambda b: b.completion_percentage()):
                    ^------- 4. hyperband contains None here, so that the lambda function throws.
            for trial in bracket.current_trials():
                if (trial.status == Trial.PENDING
                        and trial_runner.has_resources(trial.resources)):
                    return trial
    return None
```

As for the fix approach, we could forbid any band to contain None inside. However, this breaks the assumption that each lower band contains s_max_1=5 brackets (some UT assert this). Another way is to filter out None bracket.

**Comment by ericl** [comment]
Btw @richardliaw maybe we should deprecate hyperband? It seems like AsyncHyperBand is the better implemention.

**Comment by richardliaw** [comment]
@ericl I see what you're saying; maybe we can just make it less visible in the documentation and maybe rename AsyncHyperBand to HyperBand? 

I think it would be still nice to have given AsyncHyperBand is not published and HyperBand is still very well known.

@old-bear From a quick-glance, the None is added for brackets that don't get any resources. I think the fix here is that we actually just want to filter out the None brackets (or create a NoopBracket that is there just to fill the band space).
