### ISSUE TITLE
[Dashboard] [Jobs] Jobs API request causes exception in metrics middleware

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#29632]
### What happened + What you expected to happen

Upon a (successful) job submit REST API call, an error appears in `dashboard.log` (see repro below).  There are no obvious symptoms, but it might be indicative of a bug in the dashboard metrics middleware, or the Job Head server might be returning the wrong kind of response.

### Versions / Dependencies

Master (Oct 24, 2022), Python 3.8, macOS

### Reproduction script

`ray start --head`

`ray job submit -- echo hello`

In `dashboard.log`:

```
2022-10-24 16:40:04,010	INFO web_log.py:206 -- 127.0.0.1 [24/Oct/2022:23:40:03 +0000] 'POST /api/jobs/ HTTP/1.1' 200 244 bytes 53028 us '-' 'python-requests/2.25.1'
2022-10-24 16:40:04,014	INFO web_log.py:206 -- 127.0.0.1 [24/Oct/2022:23:40:04 +0000] 'GET /api/version HTTP/1.1' 200 238 bytes 377 us '-' 'python-requests/2.25.1'
2022-10-24 16:40:06,023	ERROR web_protocol.py:405 -- Error handling request
Traceback (most recent call last):
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/Users/archit/ray/python/ray/dashboard/http_server_head.py", line 122, in metrics_middleware
    status_tag = f"{floor(response.status / 100)}xx"
AttributeError: 'NoneType' object has no attribute 'status'
2022-10-24 16:40:06,030	INFO web_log.py:206 -- 127.0.0.1 [24/Oct/2022:23:40:06 +0000] 'GET /api/jobs/raysubmit_aC2SjbGKieq1dqcZ HTTP/1.1' 200 464 bytes 1604 us '-' 'python-requests/2.25.1'
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by architkulkarni** [comment]
cc @alanwguo for awareness

**Comment by alanwguo** [comment]
I made this error go away in master, but it's probably worth cherry-picking... Will produce a quick PR for that.

**Comment by rkooo567** [comment]
Hey @architkulkarni can you do more investigation on why the response doesn't contain `status`? Last time I saw this, it was a bug that we couldn't catch `AsyncIoCancelledError`. Basically the handler raises an exception that wasn't caught from try:catch blocks.

**Comment by rkooo567** [comment]
basically the handler returning `None` is undefined behavior and there's something going bad under the hood.

**Comment by architkulkarni** [comment]
@rkooo567 thanks, that's what I was wondering about.  I'll take a look

**Comment by architkulkarni** [comment]
@rkooo567 Are you saying there's a bad response coming from the Jobs server?

**Comment by rkooo567** [comment]
or job server has exception in the middle that's somehow not caught. The handler should never return None in theory if you read the code
