### ISSUE TITLE
[AIR] `XGBoostTrainer` gives misleading error if column missing

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#29695]
### What happened + What you expected to happen

My dataset doesn't contain the specified `label_columns`. I expected to receive a descriptive `ValueError`, but I instead got a verbose `RayActorError`.

For motivation, see https://github.com/ray-project/ray/issues/29640.
```
2022-10-25 21:58:30,414 ERROR trial_runner.py:993 -- Trial XGBoostTrainer_d0508_00000: Error processing event.
ray.exceptions.RayTaskError(RuntimeError): ray::_Inner.train() (pid=81811, ip=127.0.0.1, repr=XGBoostTrainer)
ray.exceptions.RayTaskError(KeyError): ray::_RemoteRayXGBoostActor.train() (pid=81815, ip=127.0.0.1, repr=<xgboost_ray.main._RemoteRayXGBoostActor object at 0x116b00940>)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'label'

The above exception was the direct cause of the following exception:

ray::_RemoteRayXGBoostActor.train() (pid=81815, ip=127.0.0.1, repr=<xgboost_ray.main._RemoteRayXGBoostActor object at 0x116b00940>)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/main.py", line 599, in train
    self.load_data(deval)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/main.py", line 561, in load_data
    param = data.get_data(self.rank, self.num_actors)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/matrix.py", line 832, in get_data
    self.load_data(num_actors=num_actors, rank=rank)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/matrix.py", line 818, in load_data
    refs, self.n = self.loader.load_data(
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/matrix.py", line 548, in load_data
    x, y, w, b, ll, lu, qid = self._split_dataframe(
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/matrix.py", line 263, in _split_dataframe
    label, exclude = data_source.get_column(local_data, self.label)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/data_sources/data_source.py", line 125, in get_column
    return data[column], column
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/pandas/core/frame.py", line 3804, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    raise KeyError(key) from err
KeyError: 'label'

The above exception was the direct cause of the following exception:

ray::_Inner.train() (pid=81811, ip=127.0.0.1, repr=XGBoostTrainer)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/main.py", line 1457, in train
    bst, train_evals_result, train_additional_results = _train(
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/main.py", line 1169, in _train
    raise RayActorError from exc
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.

The above exception was the direct cause of the following exception:

ray::_Inner.train() (pid=81811, ip=127.0.0.1, repr=XGBoostTrainer)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/tune/trainable/trainable.py", line 361, in train
    raise skipped from exception_cause(skipped)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/tune/trainable/function_trainable.py", line 325, in entrypoint
    return self._trainable_func(
  File "/Users/balaji/Documents/GitHub/ray/python/ray/train/base_trainer.py", line 485, in _trainable_func
    super()._trainable_func(self._merged_config, reporter, checkpoint_dir)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/tune/trainable/function_trainable.py", line 642, in _trainable_func
    output = fn()
  File "/Users/balaji/Documents/GitHub/ray/python/ray/train/base_trainer.py", line 390, in train_func
    trainer.training_loop()
  File "/Users/balaji/Documents/GitHub/ray/python/ray/train/gbdt_trainer.py", line 257, in training_loop
    model = self._train(
  File "/Users/balaji/Documents/GitHub/ray/python/ray/train/xgboost/xgboost_trainer.py", line 84, in _train
    return xgboost_ray.train(**kwargs)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/main.py", line 1534, in train
    raise RuntimeError(
RuntimeError: A Ray actor died during training and the maximum number of retries (0) is exhausted.
2022-10-25 21:58:30,524 ERROR tune.py:783 -- Trials did not complete: [XGBoostTrainer_d0508_00000]
2022-10-25 21:58:30,524 INFO tune.py:787 -- Total run time: 9.29 seconds (8.89 seconds for the tuning loop).
Traceback (most recent call last):
  File "/Users/balaji/Documents/GitHub/ray/repro.py", line 19, in <module>
    trainer.fit()
  File "/Users/balaji/Documents/GitHub/ray/python/ray/train/base_trainer.py", line 360, in fit
    raise result.error
types.RayTaskError(RuntimeError): ray::_Inner.train() (pid=81811, ip=127.0.0.1, repr=XGBoostTrainer)
ray.exceptions.RayTaskError(KeyError): ray::_RemoteRayXGBoostActor.train() (pid=81815, ip=127.0.0.1, repr=<xgboost_ray.main._RemoteRayXGBoostActor object at 0x116b00940>)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'label'

The above exception was the direct cause of the following exception:

ray::_RemoteRayXGBoostActor.train() (pid=81815, ip=127.0.0.1, repr=<xgboost_ray.main._RemoteRayXGBoostActor object at 0x116b00940>)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/main.py", line 599, in train
    self.load_data(deval)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/main.py", line 561, in load_data
    param = data.get_data(self.rank, self.num_actors)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/matrix.py", line 832, in get_data
    self.load_data(num_actors=num_actors, rank=rank)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/matrix.py", line 818, in load_data
    refs, self.n = self.loader.load_data(
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/matrix.py", line 548, in load_data
    x, y, w, b, ll, lu, qid = self._split_dataframe(
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/matrix.py", line 263, in _split_dataframe
    label, exclude = data_source.get_column(local_data, self.label)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/data_sources/data_source.py", line 125, in get_column
    return data[column], column
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/pandas/core/frame.py", line 3804, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    raise KeyError(key) from err
KeyError: 'label'

The above exception was the direct cause of the following exception:

ray::_Inner.train() (pid=81811, ip=127.0.0.1, repr=XGBoostTrainer)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/main.py", line 1457, in train
    bst, train_evals_result, train_additional_results = _train(
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/main.py", line 1169, in _train
    raise RayActorError from exc
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.

The above exception was the direct cause of the following exception:

ray::_Inner.train() (pid=81811, ip=127.0.0.1, repr=XGBoostTrainer)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/tune/trainable/trainable.py", line 361, in train
    raise skipped from exception_cause(skipped)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/tune/trainable/function_trainable.py", line 325, in entrypoint
    return self._trainable_func(
  File "/Users/balaji/Documents/GitHub/ray/python/ray/train/base_trainer.py", line 485, in _trainable_func
    super()._trainable_func(self._merged_config, reporter, checkpoint_dir)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/tune/trainable/function_trainable.py", line 642, in _trainable_func
    output = fn()
  File "/Users/balaji/Documents/GitHub/ray/python/ray/train/base_trainer.py", line 390, in train_func
    trainer.training_loop()
  File "/Users/balaji/Documents/GitHub/ray/python/ray/train/gbdt_trainer.py", line 257, in training_loop
    model = self._train(
  File "/Users/balaji/Documents/GitHub/ray/python/ray/train/xgboost/xgboost_trainer.py", line 84, in _train
    return xgboost_ray.train(**kwargs)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/xgboost_ray/main.py", line 1534, in train
    raise RuntimeError(
RuntimeError: A Ray actor died during training and the maximum number of retries (0) is exhausted.
```

### Versions / Dependencies

Ray: 8b4283fb3da524c63a41f34a5221e762a3dc1587

### Reproduction script

```
import ray
from ray.train.xgboost import XGBoostTrainer
from ray.air.config import ScalingConfig

dataset = ray.data.from_items(10 * [{"feature": 0, "label": "spam"}])
# Dataset(num_blocks=10, num_rows=10, schema={feature: int64, label: string})

train_dataset, test_dataset = dataset.train_test_split(test_size=0.3)
test_dataset = test_dataset.drop_columns(["label"])


trainer = XGBoostTrainer(
    label_column="label",
    params={"objective": "binary:logistic", "eval_metric": ["logloss", "error"], "tree_method": "approx"},
    scaling_config=ScalingConfig(num_workers=1),
    datasets={"train": train_dataset, "test": test_dataset},
    num_boost_round=1,
)
trainer.fit()
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by cszhu** [comment]
This P2 issue has seen no activity in the past 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please comment and remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
