### ISSUE TITLE
[tune] Tune not usable with tensorflow eager mode due to FileWriter

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#2985]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu: 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5.2 @ 5eaf429c531e01c2956a2297ff0e5dd2e9660203
- **Python version**: 3.6
- **Exact command to reproduce**: See below

### Describe the problem
Ray Tune seems to be unusable when running tensorflow in eager code, since the tf summary writing flow has changed and thus tune logger fails.

Example:
```python
import time
import tensorflow as tf
import ray
from ray import tune


tf.enable_eager_execution()


def my_func(config, reporter):  # add the reporter parameter
    i = 0
    while True:
        reporter(timesteps_total=i, mean_accuracy=i ** config['alpha'])
        i += config['beta']
        time.sleep(0.01)


tune.register_trainable('my_func', my_func)
ray.init()


tune.run_experiments({
    'my_experiment': {
        'run': 'my_func',
        'trial_resources': {'cpu': 8},
        'stop': {'mean_accuracy': 100},
        'config': {
            'alpha': tune.grid_search([0.0, 0.2, 0.4, 0.6, 0.8, 1.0]),
            'beta': tune.grid_search([2]),
        },
        'local_dir': '~/ray_results',
    }
})
```

Output:
```
$ python ./ray_report.py
...

Error stopping runner - retrying...
Traceback (most recent call last):
File "/home/kristian/github/hartikainen/ray/python/ray/tune/ray_trial_executor.py", line 116, in start_trial
self._start_trial(trial, checkpoint_obj)
File "/home/kristian/github/hartikainen/ray/python/ray/tune/ray_trial_executor.py", line 62, in _start_trial
trial.runner = self._setup_runner(trial)
File "/home/kristian/github/hartikainen/ray/python/ray/tune/ray_trial_executor.py", line 38, in _setup_runner
trial.init_logger()
File "/home/kristian/github/hartikainen/ray/python/ray/tune/trial.py", line 178, in init_logger
self.upload_dir)
File "/home/kristian/github/hartikainen/ray/python/ray/tune/logger.py", line 37, in __init__
self._init()
File "/home/kristian/github/hartikainen/ray/python/ray/tune/logger.py", line 70, in _init
self._loggers.append(cls(self.config, self.logdir, self.uri))
File "/home/kristian/github/hartikainen/ray/python/ray/tune/logger.py", line 37, in __init__
self._init()
File "/home/kristian/github/hartikainen/ray/python/ray/tune/logger.py", line 131, in _init
self._file_writer = tf.summary.FileWriter(self.logdir)
File "/home/kristian/miniconda/envs/softlearning/lib/python3.6/site-packages/tensorflow/python/summary/writer/writer.py", line 359, in __init__
"tf.summary.FileWriter is not compatible with eager execution. "
RuntimeError: tf.summary.FileWriter is not compatible with eager execution. Use tf.contrib.summary instead.
Error starting runner, aborting!
Traceback (most recent call last):
File "/home/kristian/github/hartikainen/ray/python/ray/tune/ray_trial_executor.py", line 116, in start_trial
self._start_trial(trial, checkpoint_obj)
File "/home/kristian/github/hartikainen/ray/python/ray/tune/ray_trial_executor.py", line 62, in _start_trial
trial.runner = self._setup_runner(trial)
File "/home/kristian/github/hartikainen/ray/python/ray/tune/ray_trial_executor.py", line 38, in _setup_runner
trial.init_logger()
File "/home/kristian/github/hartikainen/ray/python/ray/tune/trial.py", line 178, in init_logger
self.upload_dir)
File "/home/kristian/github/hartikainen/ray/python/ray/tune/logger.py", line 37, in __init__
self._init()
File "/home/kristian/github/hartikainen/ray/python/ray/tune/logger.py", line 70, in _init
self._loggers.append(cls(self.config, self.logdir, self.uri))
File "/home/kristian/github/hartikainen/ray/python/ray/tune/logger.py", line 37, in __init__
self._init()
File "/home/kristian/github/hartikainen/ray/python/ray/tune/logger.py", line 131, in _init
self._file_writer = tf.summary.FileWriter(self.logdir)
File "/home/kristian/miniconda/envs/softlearning/lib/python3.6/site-packages/tensorflow/python/summary/writer/writer.py", line 359, in __init__
"tf.summary.FileWriter is not compatible with eager execution. "
RuntimeError: tf.summary.FileWriter is not compatible with eager execution. Use tf.contrib.summary instead.

...

```

Seems like the summary writing flow should be changed to use the new tf.contrib.summary spec. E.g., create file writer with [tf.contrib.summary.create_file_writer](https://www.tensorflow.org/api_docs/python/tf/contrib/summary/create_file_writer) and use the [tf.contrib.summary functions](https://www.tensorflow.org/api_docs/python/tf/contrib/summary/scalar) to write the summaries. These should support both eager and graph modes.

Also, related to this, I was trying to find a way to specify a custom logger for ray tune but could find one. I think that would be very useful to have if it didn't exist yet. Also, maybe `UnifiedLogger` could support some arguments specifying which loggers to actually use? Something like:

```python

LOGGER_CLASSES = {
  'tf': _TFLogger,
  'json': _JsonLogger,
  'viskit': _VisKitLogger
}

class UnifiedLogger(Logger):
    """Unified result logger for TensorBoard, rllab/viskit, plain json.

    This class also periodically syncs output to the given upload uri."""

    def _init(self, logger_names=('tf', 'viskit', 'json')):
        # this is missing the tf import check.
        self._loggers = [
            LOGGER_CLASSES[logger_name](self.config, self.logdir, self.uri)
            for logger_name in logger_names
        ]
        self._log_syncer = get_syncer(self.logdir, self.uri)

    ...
```

**Comment by richardliaw** [comment]
This should work now? There's a check that just skips TFLogger if it can't start. Let me know if any issues arise.

**Comment by timediv** [comment]
I think there should be an tf eager logger too. Possibly also a flag which one to use.

```
class TFEagerLogger(Logger):

    def _init(self):
        self._file_writer = tfc.summary.create_file_writer(self.logdir)
        self._file_writer.set_as_default()

    def on_result(self, result):
        tmp = result.copy()
        for k in [
                "config", "pid", "timestamp", TIME_TOTAL_S, TRAINING_ITERATION
        ]:
            if k in tmp:
                del tmp[k]  # not useful to tf log these
        values = to_tf_values(tmp, ["ray", "tune"])
        iteration_value = to_tf_values({
            "training_iteration": result[TRAINING_ITERATION]
        }, ["ray", "tune"])
        t = result.get(TIMESTEPS_TOTAL) or result[TRAINING_ITERATION]
        with tfc.summary.always_record_summaries():
            for value in values + iteration_value:
                tfc.summary.scalar(value.tag, value.simple_value, step=t)
        self._file_writer.flush()

    def flush(self):
        self._file_writer.flush()

    def close(self):
        self._file_writer.close()
```

**Comment by drozzy** [comment]
This still happens? Nothing gets logged with tf2.

**Comment by richardliaw** [comment]
Try the tensorboardX logger (just added on master). https://ray.readthedocs.io/en/latest/tune-usage.html#tbxlogger-tensorboardx
