### ISSUE TITLE
[CI] `ray-data-bulk-ingest-out-of-core-benchmark` weekly test fails

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#29885]
https://buildkite.com/ray-project/release-tests-branch/builds/1176#01843019-384a-4494-8fda-3f23ca1decef

```
[ERROR 2022-10-31 15:18:01,998] run_release_test.py: 157  Cannot load yaml template from /tmp/release-qSC6LJzebp/release/air_tests/air_benchmarks/mlperf-train/app_config.yaml: Path not found.
--
  | Traceback (most recent call last):
  | File "ray_release/scripts/run_release_test.py", line 153, in main
  | no_terminate=no_terminate,
  | File "/tmp/release-qSC6LJzebp/release/ray_release/glue.py", line 354, in run_release_test
  | raise pipeline_exception
  | File "/tmp/release-qSC6LJzebp/release/ray_release/glue.py", line 142, in run_release_test
  | cluster_env = load_test_cluster_env(test, ray_wheels_url=ray_wheels_url)
  | File "/tmp/release-qSC6LJzebp/release/ray_release/template.py", line 118, in load_test_cluster_env
  | return load_and_render_yaml_template(cluster_env_path, env=env)
  | File "/tmp/release-qSC6LJzebp/release/ray_release/template.py", line 87, in load_and_render_yaml_template
  | f"Cannot load yaml template from {template_path}: Path not found."
  | ray_release.exception.ReleaseTestConfigError: Cannot load yaml template from /tmp/release-qSC6LJzebp/release/air_tests/air_benchmarks/mlperf-train/app_config.yaml: Path not found.
  | [INFO 2022-10-31 15:18:01,999] run_release_test.py: 161  Release test pipeline for test ray-data-bulk-ingest-out-of-core-benchmark completed. Returning with exit code = 11
  | Script failed on try 1/1 with exit code 11 (infra error), aborting.
```

**Comment by bveeramani** [comment]
Looks like the error was introduced by https://github.com/ray-project/ray/pull/29679
