### ISSUE TITLE
[Kuberay] Ray on Kubernetes + ray.init() from outside network/subnet does not work?

### ISSUE THREAD

**Issue by dirtyValera** [ray-project/ray#29893]
### What happened + What you expected to happen

I've managed to run a ray cluster on minikube using kuberay-operator and ray-cluster helm charts. Now I'm trying to run a simple driver program in my laptop's local environment and got stuck on `ray.init()`.

I've exposed head pod's port via `kubectl port-forward ray-cluster-kuberay-head-hjjx8 6379:6379`, meaning I can access pod's port via localhost (`127.0.0.1:6379` redirects all traffic to the pod inside minikube). Then I run

`ray.init(127.0.01:6379)`

and get 

`RuntimeError: b"This node has an IP address of 127.0.0.1, and Ray expects this IP address to be either the GCS address or one of the Raylet addresses. Connected to GCS at 127.0.0.1 and found raylets at 10.244.1.3, 10.244.2.4 but none of these match this node's IP 127.0.0.1. Are any of these actually a different IP address for the same node?You might need to provide --node-ip-address to specify the IP address that the head should use when sending to this node."`

Does it mean I have to run my driver program in the same subnet as head/worker pods? This looks very inconvenient, e.g. every time I debug/develop and change a code in a driver program I have to run a full CD pipeline (rebuild, containerise, deploy to cluster). What about running a simple script from Jupyter notebook on my local machine? Is there a known workaround?

If this is the case, how do I implement a general PaaS platform where users can access remote ray clusters from local env and run/develop local scripts remotely?

### Versions / Dependencies

Ray 2.0.0, Kuberay, minikube on MacOS

### Reproduction script

`kubectl port-forward ray-cluster-kuberay-head-hjjx8 6379:6379`

`ray.init(127.0.01:6379)`

### Issue Severity

High: It blocks me from completing my task.

**Comment by dirtyValera** [comment]
Tried using port 10001 instead of 6379, got another error when running `ray.init()`

```
2022-11-01 12:10:19,763 ERROR utils.py:1340 -- Internal KV Get failed
Traceback (most recent call last):
  File "/Users/anov/IdeaProjects/svoe/venv/lib/python3.9/site-packages/ray/_private/utils.py", line 1327, in internal_kv_get_with_retry
    result = gcs_client.internal_kv_get(key, namespace)
  File "/Users/anov/IdeaProjects/svoe/venv/lib/python3.9/site-packages/ray/_private/gcs_utils.py", line 177, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/anov/IdeaProjects/svoe/venv/lib/python3.9/site-packages/ray/_private/gcs_utils.py", line 269, in internal_kv_get
    reply = self._kv_stub.InternalKVGet(req, timeout=timeout)
  File "/Users/anov/IdeaProjects/svoe/venv/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/anov/IdeaProjects/svoe/venv/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "Method not found!"
        debug_error_string = "{"created":"@1667293819.762858000","description":"Error received from peer ipv4:127.0.0.1:10001","file":"src/core/lib/surface/call.cc","file_line":1075,"grpc_message":"Method not found!","grpc_status":12}"
>
Traceback (most recent call last):
  File "/Users/anov/IdeaProjects/svoe/ray/test.py", line 19, in <module>
    ray.init(address=ADDRESS)
  File "/Users/anov/IdeaProjects/svoe/venv/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/anov/IdeaProjects/svoe/venv/lib/python3.9/site-packages/ray/_private/worker.py", line 1475, in init
    _global_node = ray._private.node.Node(
  File "/Users/anov/IdeaProjects/svoe/venv/lib/python3.9/site-packages/ray/_private/node.py", line 182, in __init__
    session_name = ray._private.utils.internal_kv_get_with_retry(
  File "/Users/anov/IdeaProjects/svoe/venv/lib/python3.9/site-packages/ray/_private/utils.py", line 1349, in internal_kv_get_with_retry
    raise ConnectionError(
ConnectionError: Could not read 'session_name' from GCS. Did GCS start successfully?

```

**Comment by dirtyValera** [comment]
Figured this out. For anyone with similar issues, the problem was not adding `ray://` prefix to address. The port should be `10001`

`ray.init('ray://127.0.0.1:10001')`
