### ISSUE TITLE
Is boost.python supported by ray?

### ISSUE THREAD

**Issue by tianyapiaozi** [ray-project/ray#2994]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux CentOS 7
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5.2
- **Python version**: 2.7
- **Exact command to reproduce**:

### Describe the problem
I write a simple Python module with boost.python to test with ray. There are some errors
```
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:22892 to respond...
Waiting for redis server at 127.0.0.1:57918 to respond...
Starting local scheduler with the following resources: {'GPU': 0, 'CPU': 4}.
Failed to start the UI, you may need to run 'pip install jupyter'.
WARNING: Serializing objects of type <class 'example.student'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
Remote function __main__.test_stu failed with:

Traceback (most recent call last):
  File "test_example.py", line 11, in test_stu
    return (ray.services.get_node_ip_address(), stu.name, stu.age)
ArgumentError: Python argument types in
    None.None(student)
did not match C++ signature:
    None(student {lvalue})

Suppressing duplicate error message.
Traceback (most recent call last):
  File "test_example.py", line 16, in <module>
    print(ray.get([test_stu.remote(stu) for i in range(3)]))
  File "/usr/lib/python2.7/site-packages/ray/worker.py", line 2498, in get
    raise RayGetError(object_ids[i], value)
ray.worker.RayGetError: Could not get objectid ObjectID(a4cd8971ed47907c0c2669b204f3e2d1ffb1d736). It was created by remote function __main__.test_stu which failed with:

Remote function __main__.test_stu failed with:

Traceback (most recent call last):
  File "test_example.py", line 11, in test_stu
    return (ray.services.get_node_ip_address(), stu.name, stu.age)
ArgumentError: Python argument types in
    None.None(student)
did not match C++ signature:
    None(student {lvalue})

Suppressing duplicate error message.
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0929 16:18:54.393844  4256 local_scheduler.cc:177] Killed worker pid 4258 which hadn't started yet.
```

### Source code / logs
$ cat test_example.py
```python
#!/bin/env python

import sys
import ray
import example
ray.init()

@ray.remote
def test_stu(stu):
  return (ray.services.get_node_ip_address(), stu.name, stu.age)

stu = example.student()
stu.setname("mjf")
stu.setage(25)
print(ray.get([test_stu.remote(stu) for i in range(3)]))
```

$ cat student.cpp
```cpp
#include <iostream>
#include <string>
using namespace std;

class student
{
public:
	void setname(string str)
	{
		name_ = str;
	}

	string getname()
	{
		return name_;
	}

	void setage(int age)
	{
		age_ = age;
	}

	int getage()
	{
		return age_;
	}

private:
	string name_;
	int age_;

};
```
$ cat student2py.cpp
```cpp
#include <boost/python.hpp>
#include "student.cpp"
using namespace boost::python;
BOOST_PYTHON_MODULE(example)  //python模块
{
class_<student>("student")
.def("setname",&student::setname)
.def("getname",&student::getname)
.def("setage",&student::setage)
.def("getage",&student::getage)
.add_property("name",&student::getname,&student::setname)
.add_property("age",&student::getage,&student::setage)
;
}
```

**Comment by robertnishihara** [comment]
Hmm, can you try the following?

```python
stu = example.student()
stu.setname("mjf")
stu.setage(25)

stu_id = ray.put(stu)
new_stu = ray.get(stu_id)
```

Then check if `new_stu` is formed correctly or is malformed in someway? E.g., the name and age are wrong?

Can you also try

```python
@ray.remote
def f():
    stu = example.student()
    stu.setname("mjf")
    stu.setage(25)
    return stu.name, stu.age

ray.get(f.remote())
```

and see if that behaves correctly and the returned values are correct?

**Comment by tianyapiaozi** [comment]
@robertnishihara thanks for your reply.

```python
@ray.remote
def f():
    stu = example.student()
    stu.setname("mjf")
    stu.setage(25)
    return stu.name, stu.age

def test_f():
  ray.init(redis_address="11.166.213.159:6379")
  print(ray.get(f.remote()))
```
It works as expected.
Output:
```
('mjf', 25)
```
-----------------
```python
def test():
  ray.init(redis_address="11.166.213.159:6379")
  stu = example.student()
  stu.setname("mjf")
  stu.setage(25)
  stu_id = ray.put(stu)
  new_stu = ray.get(stu_id)
  print new_stu.name, new_stu.age
```
There are some errors.
Output:
```
WARNING: Serializing objects of type <class 'example.student'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
Traceback (most recent call last):
  File "test_example.py", line 39, in <module>
    test()
  File "test_example.py", line 37, in test
    print new_stu.name, new_stu.age
Boost.Python.ArgumentError: Python argument types in
    None.None(student)
did not match C++ signature:
    None(student {lvalue})
```

**Comment by tianyapiaozi** [comment]
```python
>>> print(type(stu))
<class 'example.student'>
```
Use pickle to serialize student works fine.
By the way, I have also tried with SWIG and cython to wrap a simple C++ class to python.  There are some different errors when I try to call the class's method remotely. Picke may be able to get rid of these errors.
I wonder if pickle is the recommended way to deal with these kind of problems.
