### ISSUE TITLE
[core][dashboard] state api on worker nodes can not connect to dashboard url

### ISSUE THREAD

**Issue by valiantljk** [ray-project/ray#29959]
### What happened + What you expected to happen

The ray state api can not work on worker nodes. 
The state api will need talk to dashboard: https://github.com/ray-project/ray/blob/2947e2360676b2034163282f7426d979849fa79a/python/ray/experimental/state/common.py#L924

However, on workers nodes, it seems like the dashboard address is not the head node cluster ip. The error shows the dashboard address is 127.0.0.1. 

After talking to @rkooo567, we believe this might be a bug of dashboard. 

### Versions / Dependencies

ray 2.0.0, 2.0.1, and nightlies
python 3.7.7
os: ubuntu

### Reproduction script

```
import ray
from ray.experimental.state.api import list_placement_groups
ray.init()
list_placement_groups()
```

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/ubuntu/anaconda3/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ubuntu/anaconda3/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ubuntu/anaconda3/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ubuntu/anaconda3/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/ubuntu/anaconda3/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5960332850>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8265): Max retries exceeded with url: /api/v0/nodes?limit=100&timeout=24&_server_timeout_multiplier=0.8 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5960332850>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/experimental/state/api.py", line 194, in _make_http_get_request
    params=params,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 280, in _do_request
    **kwargs,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8265): Max retries exceeded with url: /api/v0/nodes?limit=100&timeout=24&_server_timeout_multiplier=0.8 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5960332850>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 2588, in main
    return cli()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/experimental/state/state_cli.py", line 536, in ray_list
    _explain=_should_explain(format),
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/experimental/state/api.py", line 465, in list
    _explain=_explain,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/experimental/state/api.py", line 209, in _make_http_get_request
    raise ServerUnavailable(err_str)
ray.experimental.state.exception.ServerUnavailable: Failed to make request to http://127.0.0.1:8265/api/v0/nodes. Failed to connect to API server. Please check the API server log for details. Make sure dependencies are installed with `pip install ray[default]`.
==========ALPHA, FEEDBACK NEEDED ===============
State Observability APIs is currently in Alpha.
If you have any feedback, you could do so at either way as below:
    1. Report bugs/issues with details: https://forms.gle/gh77mwjEskjhN8G46
    2. Follow up in #ray-state-observability-dogfooding slack channel of Ray: https://tinyurl.com/2pm26m4a
==========================================================
```

**Comment by rkooo567** [comment]
btw @valiantljk. Would you be interested in making a PR to fix the issue?

**Comment by rkooo567** [comment]
cc @rickyyx

**Comment by cszhu** [comment]
This P2 issue has seen no activity in the past 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please comment and remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
