### ISSUE TITLE
[ml release]  tune_cloud_aws_durable_upload_rllib_str is flaky

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#29982]
### What happened + What you expected to happen

https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_Qm5W5G1zehx6ji9i2YZgnQp8?command-history-section=command_history&drivers-section=runs

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xwjiang2010** [comment]
A failed one: https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_Qm5W5G1zehx6ji9i2YZgnQp8?command-history-section=command_history&drivers-section=runs

A successful one: 
https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_m6FYmdLfYWPXtSJX13WPdhgq?command-history-section=command_history


A normal run's flow looks like
```
Running cloud test variant: durable_upload
This test will *not* use Ray client.
Running test variant `durable_upload` on node 172.31.105.33 with 2 CPUs per trial.
Before experiments: Invoking callback
Clearing bucket contents: s3://tune-cloud-tests/durable_upload_rllib_str/test_1667257766
Before experiments: Callback completed
Running command: python workloads/_tune_script.py --upload-dir s3://tune-cloud-tests/durable_upload_rllib_str/test_1667257766 --experiment-name cloud_durable_upload --indicator-file /tmp/cloud_durable_upload_indicator
Waiting up to 600 seconds until trials have been started (indicated by existence of `/tmp/cloud_durable_upload_indicator`)
Process started, trials are running
Waiting 180 seconds until sending signal 10 to process 1827
Sending signal 10 to process 1827
Waiting up to 45 seconds until process 1827 terminates
Process 1827 terminated gracefully.
Between experiments: Invoking callback
Copied local node experiment dir /home/ray/ray_results/cloud_durable_upload to /tmp/tune_cloud_testdisk2s2r for trial 195aa_00002
Copied bucket data from s3://tune-cloud-tests/durable_upload_rllib_str/test_1667257766 to /tmp/tune_cloud_testojy_b_bi
Deleting remote checkpoints before resume
Between experiments: Callback completed
Running command: python workloads/_tune_script.py --upload-dir s3://tune-cloud-tests/durable_upload_rllib_str/test_1667257766 --experiment-name cloud_durable_upload --indicator-file /tmp/cloud_durable_upload_indicator
Waiting up to 30 seconds until trials have been started (indicated by existence of `/tmp/cloud_durable_upload_indicator`)
Process started, trials are running
Waiting 180 seconds until sending signal 10 to process 2915
Sending signal 10 to process 2915
Waiting up to 45 seconds until process 2915 terminates
Process 2915 terminated gracefully.
After experiments: Invoking callback
Copied local node experiment dir /home/ray/ray_results/cloud_durable_upload to /tmp/tune_cloud_testgbxmahip for trial 195aa_00002
Copied bucket data from s3://tune-cloud-tests/durable_upload_rllib_str/test_1667257766 to /tmp/tune_cloud_testiuy6yxny
After experiments: Callback completed
Test for variant durable_upload SUCCEEDED
```

**Comment by xwjiang2010** [comment]
Note we are running on spot instances.

A few seconds before a stop signal is received, one of the worker nodes is gone. And I think the driver pretty much just hangs. See log below

```
2022-11-01 17:17:36,209	WARNING tune.py:716 -- Stop signal received (e.g. via SIGINT/Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip. 
2022-11-01 17:17:48,323	ERROR ray_trial_executor.py:111 -- An exception occurred when trying to stop the Ray actor:Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/execution/ray_trial_executor.py", line 101, in _post_stop_cleanup
    ray.get(future, timeout=timeout)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py", line 2305, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.

2022-11-01 17:17:48,540	ERROR tune.py:783 -- Trials did not complete: [PPO_CartPole-v1_54830_00000, PPO_CartPole-v1_54830_00001, PPO_CartPole-v1_54830_00002, PPO_CartPole-v1_54830_00003]
2022-11-01 17:17:48,540	INFO tune.py:788 -- Total run time: 194.26 seconds (182.13 seconds for the tuning loop).
2022-11-01 17:17:48,540	WARNING tune.py:794 -- Experiment has been interrupted, but the most recent state was saved. You can continue running this experiment by passing `resume=True` to `tune.run()`

Trial PPO_CartPole-v1_54830_00002 reported episode_reward_mean=312.58,num_env_steps_sampled=44000,num_env_steps_trained=44000 with parameters={'env': 'CartPole-v1', 'num_workers': 1, 'num_envs_per_worker': 1, 'callbacks': <class '__main__.RLlibCallback'>}.
[2m[1m[36m(scheduler +3m12s)[0m Tip: use `ray status` to view detailed cluster status. To disable these messages, set RAY_SCHEDULER_EVENTS=0.
[2m[1m[36m(scheduler +3m12s)[0m Adding 1 node(s) of type worker_node.
Trial PPO_CartPole-v1_54830_00003 reported episode_reward_mean=284.42,num_env_steps_sampled=40000,num_env_steps_trained=40000 with parameters={'env': 'CartPole-v1', 'num_workers': 1, 'num_envs_per_worker': 1, 'callbacks': <class '__main__.RLlibCallback'>}.
== Status ==
Current time: 2022-11-01 17:17:37 (running for 00:03:02.12)
Memory usage on this node: 3.0/7.5 GiB 
Using FIFO scheduling algorithm.
Resources requested: 6.0/8 CPUs, 0/0 GPUs, 0.0/20.87 GiB heap, 0.0/8.25 GiB objects
Result logdir: /home/ray/ray_results/cloud_durable_upload
Number of trials: 4/4 (1 ERROR, 3 RUNNING)
Number of errored trials: 1
+-----------------------------+--------------+--------------------------------------------------------------------------------------------------------+
| Trial name                  |   # failures | error file                                                                                             |
|-----------------------------+--------------+--------------------------------------------------------------------------------------------------------|
| PPO_CartPole-v1_54830_00000 |            1 | /home/ray/ray_results/cloud_durable_upload/PPO_CartPole-v1_54830_00000_0_2022-11-01_17-14-36/error.txt |
+-----------------------------+--------------+--------------------------------------------------------------------------------------------------------+

== Status ==
Current time: 2022-11-01 17:17:42 (running for 00:03:07.10)
Memory usage on this node: 3.0/7.5 GiB 
Using FIFO scheduling algorithm.
Resources requested: 6.0/8 CPUs, 0/0 GPUs, 0.0/20.87 GiB heap, 0.0/8.25 GiB objects
Result logdir: /home/ray/ray_results/cloud_durable_upload
Number of trials: 4/4 (1 ERROR, 3 RUNNING)
+-----------------------------+----------+--------------------+--------+------------------+-------+----------+------------------------+----------------------+----------------------+
| Trial name                  | status   | loc                |   iter |   total time (s) |    ts |   reward |   num_recreated_worker |   episode_reward_max |   episode_reward_min |
|                             |          |                    |        |                  |       |          |                      s |                      |                      |
|-----------------------------+----------+--------------------+--------+------------------+-------+----------+------------------------+----------------------+----------------------|
| PPO_CartPole-v1_54830_00001 | RUNNING  | 172.31.101.32:2010 |      7 |         100.601  | 28000 |   205.89 |                      0 |                  500 |                   13 |
| PPO_CartPole-v1_54830_00002 | RUNNING  | 172.31.67.51:255   |     11 |         105.254  | 44000 |   312.58 |                      0 |                  500 |                   28 |
| PPO_CartPole-v1_54830_00003 | RUNNING  | 172.31.87.4:258    |     10 |          99.3577 | 40000 |   284.42 |                      0 |                  500 |                   58 |
| PPO_CartPole-v1_54830_00000 | ERROR    | 172.31.81.171:252  |     10 |          89.099  | 40000 |   264.47 |                      0 |                  500 |                   57 |
+-----------------------------+----------+--------------------+--------+------------------+-------+----------+------------------------+----------------------+----------------------+
Number of errored trials: 1
+-----------------------------+--------------+--------------------------------------------------------------------------------------------------------+
| Trial name                  |   # failures | error file                                                                                             |
|-----------------------------+--------------+--------------------------------------------------------------------------------------------------------|
| PPO_CartPole-v1_54830_00000 |            1 | /home/ray/ray_results/cloud_durable_upload/PPO_CartPole-v1_54830_00000_0_2022-11-01_17-14-36/error.txt |
+-----------------------------+--------------+--------------------------------------------------------------------------------------------------------+

/home/ray/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py:424: UserWarning: [33mWARN: Custom namespace `ALE` is being overridden by namespace `ALE`. If you are developing a plugin you shouldn't specify a namespace in `register` calls. The namespace is specified through the entry point package metadata.[0m
  f"Custom namespace `{spec.namespace}` is being overridden "
Warning: Gym version v0.24.0 has a number of critical issues with `gym.make` such that the `reset` and `step` functions are called before returning the environment. It is recommend to downgrading to v0.23.1 or upgrading to v0.25.1
2022-11-01 17:17:54,206	WARNING worker.py:1849 -- The node with node id: 6d325b939d357a5e639c97bea56af71de16a34802b8620e20727b558 and address: 172.31.81.171 and node name: 172.31.81.171 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a 	(1) raylet crashes unexpectedly (OOM, preempted node, etc.) 
	(2) raylet has lagging heartbeats due to slow network or busy workload.
/home/ray/anaconda3/lib/python3.7/site-packages/flatbuffers/compat.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/ray/anaconda3/lib/python3.7/site-packages/keras/utils/image_utils.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': pil_image.NEAREST,
/home/ray/anaconda3/lib/python3.7/site-packages/keras/utils/image_utils.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': pil_image.BILINEAR,
/home/ray/anaconda3/lib/python3.7/site-packages/keras/utils/image_utils.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': pil_image.BICUBIC,
/home/ray/anaconda3/lib/python3.7/site-packages/keras/utils/image_utils.py:39: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': pil_image.HAMMING,
/home/ray/anaconda3/lib/python3.7/site-packages/keras/utils/image_utils.py:40: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': pil_image.BOX,
/home/ray/anaconda3/lib/python3.7/site-packages/keras/utils/image_utils.py:41: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': pil_image.LANCZOS,
/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/__init__.py:57: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if (distutils.version.LooseVersion(tf.__version__) <
2022-11-01 17:19:53,221	WARNING worker.py:1849 -- The node with node id: 0721901e630e941fd4d0d2d1bd697e56e2b7106e6f8e0282c4c48f81 and address: 172.31.67.51 and node name: 172.31.67.51 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a 	(1) raylet crashes unexpectedly (OOM, preempted node, etc.) 
	(2) raylet has lagging heartbeats due to slow network or busy workload.
2022-11-01 17:23:56,243	WARNING worker.py:1849 -- The node with node id: a8d5fbdd7593f493367545934974f22d24da5f73d3be54f0117f3b42 and address: 172.31.87.4 and node name: 172.31.87.4 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a 	(1) raylet crashes unexpectedly (OOM, preempted node, etc.) 
	(2) raylet has lagging heartbeats due to slow network or busy workload.
```

**Comment by xwjiang2010** [comment]
cc @krfricke 
I am trying to understand if this is a real fault tolerance issue or this test should be moved back to using non-spot instance.
