### ISSUE TITLE
[CI] :mac: Kick-off: Launching MacOS pipeline succeeds even on error during step generation

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#30062]
We should fail if the step generation script fails.

Seen in https://github.com/ray-project/ray/pull/30044

```
~/builds/bk-builder-queue-pr-i-0dfc61feea55d0f5d-1/ray-project/oss-ci-build-pr/.buildkite ~/builds/bk-builder-queue-pr-i-0dfc61feea55d0f5d-1/ray-project/oss-ci-build-pr
--
  | From https://github.com/ray-project/ray
  | * branch                master     -> FETCH_HEAD
  | 'origin/master...5ec05c04619c2e89d2a262561a24e4a5bc7b5d2b'
  | [u'.buildkite/pipeline.macos.yml']
  | Failed to dry run py_dep_analysis.py
  | Traceback (most recent call last):
  | File "../ci/pipeline/determine_tests_to_run.py", line 116, in <module>
  | import py_dep_analysis as pda
  | File "/var/lib/buildkite-agent/builds/bk-builder-queue-pr-i-0dfc61feea55d0f5d-1/ray-project/oss-ci-build-pr/ci/pipeline/py_dep_analysis.py", line 29
  | self.edges: Dict[str, Dict[str, bool]] = {}
  | ^
  | SyntaxError: invalid syntax


```

**Comment by krfricke** [comment]
I'll re-assign this to @can-anyscale and will let you guys prioritize this!

**Comment by aslonnie** [comment]
this should be fixed now.
