### ISSUE TITLE
[Core] GCS hanging even cpu utilization low

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#30086]
### What happened + What you expected to happen

```

Thread 1 (Thread 0x7f04b613fb00 (LWP 1746)):
#0  __libc_sendmsg (flags=16384, msg=0x7ffea7f3e490, fd=147) at ../sysdeps/unix/sysv/linux/sendmsg.c:28
#1  __libc_sendmsg (fd=147, msg=0x7ffea7f3e490, flags=16384) at ../sysdeps/unix/sysv/linux/sendmsg.c:25
#2  0x00005633ab3266ae in tcp_send (fd=147, msg=0x7ffea7f3e490, additional_flags=0) at external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_posix.cc:916
#3  0x00005633ab327305 in tcp_flush (tcp=0x7f046009a520, error=0x7ffea7f3f548) at external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_posix.cc:1448
#4  0x00005633ab327ca7 in tcp_write (ep=0x7f046009a520, buf=0x7f04600883d0, cb=0x7f04600881b8, arg=0x0) at external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_posix.cc:1588
#5  0x00005633ab33216b in grpc_endpoint_write (ep=0x7f046009a520, slices=0x7f04600883d0, cb=0x7f04600881b8, arg=0x0) at external/com_github_grpc_grpc/src/core/lib/iomgr/endpoint.cc:32
#6  0x00005633aafa7d83 in write_action (gt=0x7f0460088010) at external/com_github_grpc_grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:983
#7  0x00005633aafa7bd7 in write_action_begin_locked (gt=0x7f0460088010) at external/com_github_grpc_grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:957
#8  0x00005633ab36c408 in grpc_combiner_continue_exec_ctx () at external/com_github_grpc_grpc/src/core/lib/iomgr/combiner.cc:264
#9  0x00005633ab36e159 in grpc_core::ExecCtx::Flush (this=0x7ffea7f3f7a0) at external/com_github_grpc_grpc/src/core/lib/iomgr/exec_ctx.cc:82
#10 0x00005633aad5a033 in grpc_core::ExecCtx::~ExecCtx (this=0x7ffea7f3f7a0, __in_chrg=<optimized out>) at external/com_github_grpc_grpc/src/core/lib/iomgr/exec_ctx.h:117
#11 0x00005633ab2fd738 in grpc_call_start_batch (call=0x7f032c760ff0, ops=0x7ffea7f3f870, nops=3, tag=0x7f049902fd58, reserved=0x0) at external/com_github_grpc_grpc/src/core/lib/surface/call.cc:1767
#12 0x00005633aad93e7b in grpc::CoreCodegen::grpc_call_start_batch (this=0x5633ad4f0e90, call=0x7f032c760ff0, ops=0x7ffea7f3f870, nops=3, tag=0x7f049902fd58, reserved=0x0) at external/com_github_grpc_grpc/src/cpp/common/core_codegen.cc:113
#13 0x00005633aa6f4dad in grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal::CallOpSendMessage, grpc::internal::CallOpServerSendStatus, grpc::internal::CallNoOp<4>, grpc::internal::CallNoOp<5>, grpc::internal::CallNoOp<6> >::ContinueFil
lOpsAfterInterception (this=0x7f049902fd58) at external/com_github_grpc_grpc/include/grpcpp/impl/codegen/call_op_set.h:976
#14 0x00005633aa6f4b69 in grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal::CallOpSendMessage, grpc::internal::CallOpServerSendStatus, grpc::internal::CallNoOp<4>, grpc::internal::CallNoOp<5>, grpc::internal::CallNoOp<6> >::FillOps (this=0x7f049902fd58, call=0x7f049902fbc0) at external/com_github_grpc_grpc/include/grpcpp/impl/codegen/call_op_set.h:906
#15 0x00005633aad68c1c in grpc::Server::PerformOpsOnCall (this=0x5633ad54a770, ops=0x7f049902fd58, call=0x7f049902fbc0) at external/com_github_grpc_grpc/src/cpp/server/server_cc.cc:1305
#16 0x00005633aa61dc7b in grpc::internal::Call::PerformOps (this=0x7f049902fbc0, ops=0x7f049902fd58) at external/com_github_grpc_grpc/include/grpcpp/impl/codegen/call.h:68
#17 0x00005633aa710d18 in grpc::ServerAsyncResponseWriter<ray::rpc::GcsSubscriberPollReply>::Finish (this=0x7f049902fbb8, msg=..., status=..., tag=0x7f049902f800) at external/com_github_grpc_grpc/include/grpcpp/impl/codegen/async_unary_call.h:358
#18 0x00005633aa702b74 in ray::rpc::ServerCallImpl<ray::rpc::InternalPubSubGcsServiceHandler, ray::rpc::GcsSubscriberPollRequest, ray::rpc::GcsSubscriberPollReply>::SendReply (this=0x7f049902f800, status=...) at bazel-out/k8-dbg/bin/_virtual_includes/grpc_common_lib/ray
/rpc/server_call.h:247
#19 0x00005633aa7028ea in ray::rpc::ServerCallImpl<ray::rpc::InternalPubSubGcsServiceHandler, ray::rpc::GcsSubscriberPollRequest, ray::rpc::GcsSubscriberPollReply>::HandleRequestImpl()::{lambda(ray::Status, std::function<void ()>, std::function<void ()>)#1}::operator()(
ray::Status, std::function<void ()>, std::function<void ()>) const (this=0x7f049902f800, status=..., success=..., failure=...) at bazel-out/k8-dbg/bin/_virtual_includes/grpc_common_lib/ray/rpc/server_call.h:207
#20 0x00005633aa735319 in std::__invoke_impl<void, ray::rpc::ServerCallImpl<ray::rpc::InternalPubSubGcsServiceHandler, ray::rpc::GcsSubscriberPollRequest, ray::rpc::GcsSubscriberPollReply>::HandleRequestImpl()::{lambda(ray::Status, std::function<void ()>, std::function<
void ()>)#1}&, ray::Status, std::function<void ()>, std::function<void ()> >(std::__invoke_other, ray::rpc::ServerCallImpl<ray::rpc::InternalPubSubGcsServiceHandler, ray::rpc::GcsSubscriberPollRequest, ray::rpc::GcsSubscriberPollReply>::HandleRequestImpl()::{lambda(ray::Status, std::function<void ()>, std::function<void ()>)#1}&, ray::Status&&, std::function<void ()>&&, std::function<void ()>&&) (__f=...) at /opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
#21 0x00005633aa72e86b in std::__invoke_r<void, ray::rpc::ServerCallImpl<ray::rpc::InternalPubSubGcsServiceHandler, ray::rpc::GcsSubscriberPollRequest, ray::rpc::GcsSubscriberPollReply>::HandleRequestImpl()::{lambda(ray::Status, std::function<void ()>, std::function<void ()>)#1}&, ray::Status, std::function<void ()>, std::function<void ()> >(void&&, (ray::rpc::ServerCallImpl<ray::rpc::InternalPubSubGcsServiceHandler, ray::rpc::GcsSubscriberPollRequest, ray::rpc::GcsSubscriberPollReply>::HandleRequestImpl()::{lambda(ray::Status, std::f
unction<void ()>, std::function<void ()>)#1}&)...) (__fn=...) at /opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:110
#22 0x00005633aa720182 in std::_Function_handler<void (ray::Status, std::function<void ()>, std::function<void ()>), ray::rpc::ServerCallImpl<ray::rpc::InternalPubSubGcsServiceHandler, ray::rpc::GcsSubscriberPollRequest, ray::rpc::GcsSubscriberPollReply>::HandleRequestI
mpl()::{lambda(ray::Status, std::function<void ()>, std::function<void ()>)#1}>::_M_invoke(std::_Any_data const&, ray::Status&&, std::function<void ()>&&, ray::Status&&) (__functor=..., __args#0=..., __args#1=..., __args#2=...) at /opt/rh/devtoolset-10/root/usr/lib/gcc/
x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291
#23 0x00005633aa74c96a in std::function<void (ray::Status, std::function<void ()>, std::function<void ()>)>::operator()(ray::Status, std::function<void ()>, std::function<void ()>) const (this=0x7f04783e33f8, __args#0=..., __args#1=..., __args#2=...) at /opt/rh/devtools
et-10/root/usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622
#24 0x00005633aa75299f in operator()(ray::Status, std::function<void()>, std::function<void()>) const (__closure=0x7f04783e33f0, status=..., success_cb=..., failure_cb=...) at src/ray/gcs/gcs_server/pubsub_handler.cc:77
#25 0x00005633aa7539f3 in std::__invoke_impl<void, ray::gcs::InternalPubSubHandler::HandleGcsSubscriberPoll(ray::rpc::GcsSubscriberPollRequest, ray::rpc::GcsSubscriberPollReply*, ray::rpc::SendReplyCallback)::<lambda(ray::Status, std::function<void()>, std::function<voi
d()>)>&, ray::Status, std::function<void()>, std::function<void()> >(std::__invoke_other, struct {...} &) (__f=...) at /opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
#26 0x00005633aa7537cc in std::__invoke_r<void, ray::gcs::InternalPubSubHandler::HandleGcsSubscriberPoll(ray::rpc::GcsSubscriberPollRequest, ray::rpc::GcsSubscriberPollReply*, ray::rpc::SendReplyCallback)::<lambda(ray::Status, std::function<void()>, std::function<void()
>)>&, ray::Status, std::function<void()>, std::function<void()> >(struct {...} &) (__fn=...) at /opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:110
#27 0x00005633aa7535a6 in std::_Function_handler<void(ray::Status, std::function<void()>, std::function<void()>), ray::gcs::InternalPubSubHandler::HandleGcsSubscriberPoll(ray::rpc::GcsSubscriberPollRequest, ray::rpc::GcsSubscriberPollReply*, ray::rpc::SendReplyCallback)
::<lambda(ray::Status, std::function<void()>, std::function<void()>)> >::_M_invoke(const std::_Any_data &, ray::Status &&, std::function<void()> &&, std::function<void()> &&) (__functor=..., __args#0=..., __args#1=..., __args#2=...) at /opt/rh/devtoolset-10/root/usr/lib
/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291
```

### Versions / Dependencies

master

### Reproduction script

create a lot of nodes and run

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by iycheng** [comment]
https://gist.github.com/iycheng/4d873195bee53f15560a5ef83fdacaea

**Comment by iycheng** [comment]
https://github.com/ray-project/ray/pull/30131

**Comment by iycheng** [comment]
https://github.com/ray-project/ray/pull/30112
