### ISSUE TITLE
[Datasets] local:// URI doesn't work for parquet datasource due to sampling

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#30119]
When I tried to `ray.data.read_parquet("local://path/to/parquet")` files in a multi-node cluster, the data sample tasks seemed to fail since they weren't pinned to the head node.

```
FileNotFoundError: [Errno 2] Failed to open local file '/tmp/output.parquet/e3498b5548d14ea9b223620036f899c2_000384.parquet'. Detail: [errno 2] No such file or directory
Parquet Files Sample:  33%|███▎      | 1/3 [00:02<00:05,  2.81s/it]
(_sample_piece pid=19204, ip=172.31.115.11) 2022-11-08 17:25:38,325     INFO worker.py:763 -- Task failed with retryable exception: TaskID(ceed8a3183bf2d1bffffffffffffffffffffffff13000000).
(_sample_piece pid=19204, ip=172.31.115.11) Traceback (most recent call last):
(_sample_piece pid=19204, ip=172.31.115.11)   File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
(_sample_piece pid=19204, ip=172.31.115.11)   File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
(_sample_piece pid=19204, ip=172.31.115.11)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/datasource/parquet_datasource.py", line 436, in _sample_piece
(_sample_piece pid=19204, ip=172.31.115.11)     piece = piece.subset(row_group_ids=[0])
(_sample_piece pid=19204, ip=172.31.115.11)   File "pyarrow/_dataset_parquet.pyx", line 424, in pyarrow._dataset_parquet.ParquetFileFragment.subset
(_sample_piece pid=19204, ip=172.31.115.11)   File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
(_sample_piece pid=19204, ip=172.31.115.11)   File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
(_sample_piece pid=19204, ip=172.31.115.11) FileNotFoundError: [Errno 2] Failed to open local file '/tmp/output.parquet/e3498b5548d14ea9b223620036f899c2_000384.parquet'. Detail: [errno 2] No such file or directory
```

Presumably this would apply to reading `example://` URIs as well, though I haven't tried that yet.

PR that added the local:// URI: https://github.com/ray-project/ray/pull/29565

**Comment by jianoaix** [comment]
This has two other issues to fix as well:
- `parallelism` which is detected based on available resource in cluster, may not fit well when it's local mode
- The metadata fetch is using SPREAD, which may also need to be fixed

**Comment by ericl** [comment]
Parallelism detection should still be correct here, since it impacts downstream stages from the read stage. If we detected parallelism based on the local node that would force all stages to be under parallelized instead of just the read.
