### ISSUE TITLE
[Serve] Dependency issues with Poetry around starlette/fastapi

### ISSUE THREAD

**Issue by Limess** [ray-project/ray#30140]
### What happened + What you expected to happen

Currently ray serve breaks out the box when installed by Poetry.

This is because Poetry installs a very old version of fastapi (0.1.17).

1. Ray selects `*` for both starlette and fastapi
2. Poetry selects the latest version of starlette (0.21.0).
3. Poetry selects the latest compatible version of fastapi. All modern versions are pinned to a specific starlette version, non currently support 0.21.0, hence poetry falls back to the first one it can find which has an unpinned dependency version: fastapi 0.1.17. This has a `>=` version range for starlette so is compatible
5. The old version of fastapi is incompatible with everything else

I'm not sure how pip resolution works here, it somehow decides to select the new version of fastapi - I can't see explicit decisions in the logs so I'm unsure what the algorithm is.

Ideally I feel Ray would pin at least one of the versions to guarantee compatibility.

### Versions / Dependencies

- Ubuntu 20.04.5 LTS
- Python 3.9.12
- Poetry 1.2.2
- Pip 22.3.1
- Ray 2.1.0

### Reproduction script

Follow the ray serve tutorial: 

This will fail with the following error (the same as https://discuss.ray.io/t/from-ray-import-serve-causes-importerror-cannot-import-name-schema-from-pydantic/7119):

```
Traceback (most recent call last):
  File "/Users/me/Developer/ray_demo/serve.py", line 9, in <module>
    from ray import serve
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/yes-6KwWb3XD-py3.9/lib/python3.9/site-packages/ray/serve/__init__.py", line 2, in <module>
    from ray.serve.api import (
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/yes-6KwWb3XD-py3.9/lib/python3.9/site-packages/ray/serve/api.py", line 14, in <module>
    from fastapi import APIRouter, FastAPI
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/yes-6KwWb3XD-py3.9/lib/python3.9/site-packages/fastapi/__init__.py", line 5, in <module>
    from .applications import FastAPI
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/yes-6KwWb3XD-py3.9/lib/python3.9/site-packages/fastapi/applications.py", line 3, in <module>
    from fastapi import routing
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/yes-6KwWb3XD-py3.9/lib/python3.9/site-packages/fastapi/routing.py", line 6, in <module>
    from fastapi import params
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/yes-6KwWb3XD-py3.9/lib/python3.9/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic import Schema
ImportError: cannot import name 'Schema' from 'pydantic' (/Users/me/Library/Caches/pypoetry/virtualenvs/yes-6KwWb3XD-py3.9/lib/python3.9/site-packages/pydantic/__init__.cpython-39-darwin.so)
```

```shell
pyenv install 3.9.12
pyenv local 3.9

poetry init
poetry add "ray[serve]"

cat << EOF > model.py
from typing import Dict

import requests
from ray import serve
from starlette.requests import Request


# 1: Define a Ray Serve deployment.
@serve.deployment(route_prefix="/")
class MyModelDeployment:
    def __init__(self, msg: str):
        # Initialize model state: could be very large neural net weights.
        self._msg = msg

    def __call__(self, request: Request) -> Dict:
        return {"result": self._msg}


# 2: Deploy the model.
serve.run(MyModelDeployment.bind(msg="Hello world!"))

# 3: Query the deployment and print the result.
print(requests.get("http://localhost:8000/").json())
# {'result': 'Hello world!'}
EOF

poetry run python model.py
```

Install fastapi explicitly - this will force poetry to use the latest fastapi version, and so downgrade starlette, this will now work as expected

```shell
poetry add fastapi
poetry run python model.py
```

logs:
```
poetry add fastapi
Using version ^0.86.0 for fastapi

Updating dependencies
Resolving dependencies... (1.2s)

Writing lock file

Package operations: 0 installs, 2 updates, 0 removals

  • Updating starlette (0.21.0 -> 0.20.4)
  • Updating fastapi (0.1.17 -> 0.86.0)
```

This reproduction may change if new fastapi/starlette versions are released, e.g. if a new fastapi version supports the latest starlette version this should start working again without issues.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by DmitriGekhtman** [comment]
cc @sihanwang41

**Comment by Martin4R** [comment]
Just ran into the same issue with Ray 2.7. The solution within Ray could be to specify a minimum version for fastapi which is at least fastapi >= 0.1.19, because from there fast-api has upper bound restrictions for the starlette version which prevents the issue.

**Comment by thatcort** [comment]
I'm still seeing this problem and poetry refuses to install a more recent version of fastapi:

```
# poetry add fastapi
Using version ^0.110.2 for fastapi

Updating dependencies
Resolving dependencies... (448.4s)

Because flock-driver depends on ray[data,default,serve,train] (2.9.2) which depends on fastapi (<=0.108.0), fastapi is required.
So, because flock-driver depends on fastapi (^0.110.2), version solving failed.
```
