### ISSUE TITLE
[Dashboard] diskless nodes 

### ISSUE THREAD

**Issue by Data-drone** [ray-project/ray#30229]
### What happened + What you expected to happen

When running ray on a databricks cluster, no stats appear in the dashboard.
In the dashboard_agent.log I see:

```

Traceback (most recent call last):40  File "/databricks/python/lib/python3.9/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 827, in _perform_iteration41    stats = self._get_all_stats()42  File "/databricks/python/lib/python3.9/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 491, in _get_all_stats43    disk_stats = self._get_disk_io_stats()44  File "/databricks/python/lib/python3.9/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 401, in _get_disk_io_stats45    stats.read_bytes,46AttributeError: 'NoneType' object has no attribute 'read_bytes

```

the ` def _get_disk_io_stats():` method in `reporter_agent.py` needs some sort of error handling for that rather than crashing the report for all the other stats

### Versions / Dependencies

ray 2.1.0
python 3.9.5

### Reproduction script

start ray with:

```

ray start --head --include-dashboard=true

```

on a databricks cluster and check the dashboard_agent.log

### Issue Severity

Low: It annoys or frustrates me.

**Comment by hora-anyscale** [comment]
Per Triage Sync: @rkooo567 thoughts here?

**Comment by rkooo567** [comment]
We will fix it by 2.2

**Comment by rkooo567** [comment]
@Data-drone are you open to try the fix ^ using the wheel I will provide?

**Comment by Data-drone** [comment]
sure I can

**Comment by rkooo567** [comment]
@Data-drone you can try the master wheel for verification https://docs.ray.io/en/master/ray-overview/installation.html#daily-releases-nightlies

**Comment by Data-drone** [comment]
Hi @rkooo567 I tried to install the master wheel via both:

`pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/master/615d6170790c65334acd1adc4963ed0cc6e9a8e7/ray-3.0.0.dev0-cp39-cp39m-manylinux2014_x86_64.whl`

and

`pip install -U "ray[default] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp39-cp39-manylinux2014_x86_64.whl"`

and both times got the old version rather than the fixed one?

**Comment by rkooo567** [comment]
> both times got the old version rather than the fixed one?

Can you tell me what this means? You can probably give me the commit

```python 3
import ray
print(ray.__commit__)
```

**Comment by Data-drone** [comment]
I ran:

```
pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/master/615d6170790c65334acd1adc4963ed0cc6e9a8e7/ray-3.0.0.dev0-cp39-cp39m-manylinux2014_x86_64.whl
```

and got:

```
print(ray.__version__) 
'2.0.1'
```
and got:

```
print(ray.__commit__)
03b6bc7b5a305877501110ec04710a9c57011479
```

**Comment by axu-git** [comment]
> @Data-drone you can try the master wheel for verification https://docs.ray.io/en/master/ray-overview/installation.html#daily-releases-nightlies

Thanks for this! I was having the same problem, and with

pip install -U "ray[default] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp39-cp39-manylinux2014_x86_64.whl"

it works now!

**Comment by Data-drone** [comment]
Cool it works now
