### ISSUE TITLE
PPO optimizer erred when running with a custom CNN model

### ISSUE THREAD

**Issue by fywu85** [ray-project/ray#3024]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Ray installed from (source or binary)**: Source from `https://github.com/eugenevinitsky/ray`
- **Ray version**: 0.5.2
- **Python version**: Python 3.6.5 :: Anaconda, Inc.
- **Exact command to reproduce**: Run the file in the attachment.
[circle.zip](https://github.com/ray-project/ray/files/2448061/circle.zip)

### Describe the problem

PPO optimizer erred when running with the following custom CNN model with a input image of dim (82, 82, 1).
```
class PixelFlowNetwork(Model):
    def _build_layers(self, inputs, num_outputs, options):
        print(inputs)
        # Convolutional Layer #1 and Pooling Layer #1
        conv1 = tf.layers.conv2d(
          inputs=inputs,
          filters=32,
          kernel_size=[4, 4],
          padding="same",
          activation=tf.nn.relu)
        pool1 = tf.layers.max_pooling2d(
          inputs=conv1,
          pool_size=[2, 2],
          strides=2)
        # Convolutional Layer #2 and Pooling Layer #2
        conv2 = tf.layers.conv2d(
          inputs=pool1,
          filters=64,
          kernel_size=[4, 4],
          padding="same",
          activation=tf.nn.relu)
        pool2 = tf.layers.max_pooling2d(
          inputs=conv2,
          pool_size=[2, 2],
          strides=2)
        # Dense Layer
        pool2_flat = tf.contrib.layers.flatten(pool2)
        fc1 = tf.layers.dense(
          inputs=pool2_flat,
          units=1024,
          activation=tf.nn.relu)
        fc2 = tf.layers.dense(
          inputs=fc1,
          units=2,
          activation=None)
        return fc2, fc1
```

### Source code / logs

```
Error processing event.
Traceback (most recent call last):
  File "/home/fangyu/GitHub/ray-eugene/python/ray/tune/trial_runner.py", line 239, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/fangyu/GitHub/ray-eugene/python/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(2dd1daacb78b481fef338f8f9829018aee723398). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [2000] vs. [4000]
	 [[Node: default_1/tower_1/sub_14 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](default_1/tower_1/Slice_1, default_1/tower_1/value_function/Reshape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fangyu/GitHub/ray-eugene/python/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/agents/agent.py", line 235, in train
    return Trainable.train(self)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/tune/trainable.py", line 143, in train
    result = self._train()
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/agents/ppo/ppo.py", line 123, in _train
    fetches = self.optimizer.step()
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/optimizers/multi_gpu_optimizer.py", line 135, in step
    permutation[batch_index] * self.per_device_batch_size)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/optimizers/multi_gpu_impl.py", line 185, in optimize
    return sess.run(fetches, feed_dict=feed_dict)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [2000] vs. [4000]
	 [[Node: default_1/tower_1/sub_14 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](default_1/tower_1/Slice_1, default_1/tower_1/value_function/Reshape)]]

Caused by op 'default_1/tower_1/sub_14', defined at:
  File "/home/fangyu/GitHub/ray-eugene/python/ray/workers/default_worker.py", line 88, in <module>
    ray.worker.global_worker.main_loop()
  File "/home/fangyu/GitHub/ray-eugene/python/ray/worker.py", line 1103, in main_loop
    self._wait_for_and_process_task(task)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/worker.py", line 1060, in _wait_for_and_process_task
    self._process_task(task)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/agents/agent.py", line 216, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/tune/trainable.py", line 84, in __init__
    self._setup()
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/agents/agent.py", line 258, in _setup
    self._init()
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/agents/ppo/ppo.py", line 118, in _init
    "standardize_fields": ["advantages"],
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/optimizers/policy_optimizer.py", line 50, in __init__
    self._init(**self.config)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/optimizers/multi_gpu_optimizer.py", line 85, in _init
    os.getcwd())
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/optimizers/multi_gpu_impl.py", line 87, in __init__
    len(input_placeholders)))
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/optimizers/multi_gpu_impl.py", line 220, in _setup_device
    graph_obj = self.build_graph(device_input_slices)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/agents/ppo/ppo_policy_graph.py", line 234, in copy
    existing_inputs=existing_inputs)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/agents/ppo/ppo_policy_graph.py", line 217, in __init__
    self.value_function)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/utils/explained_variance.py", line 10, in explained_variance
    _, diff_var = tf.nn.moments(y - pred, axes=[0])
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 850, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 8188, in sub
    "Sub", x=x, y=y, name=name)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Incompatible shapes: [2000] vs. [4000]
	 [[Node: default_1/tower_1/sub_14 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](default_1/tower_1/Slice_1, default_1/tower_1/value_function/Reshape)]]


Remote function train failed with:

Traceback (most recent call last):
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [2000] vs. [4000]
	 [[Node: default_1/tower_1/sub_14 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](default_1/tower_1/Slice_1, default_1/tower_1/value_function/Reshape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fangyu/GitHub/ray-eugene/python/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/agents/agent.py", line 235, in train
    return Trainable.train(self)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/tune/trainable.py", line 143, in train
    result = self._train()
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/agents/ppo/ppo.py", line 123, in _train
    fetches = self.optimizer.step()
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/optimizers/multi_gpu_optimizer.py", line 135, in step
    permutation[batch_index] * self.per_device_batch_size)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/optimizers/multi_gpu_impl.py", line 185, in optimize
    return sess.run(fetches, feed_dict=feed_dict)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [2000] vs. [4000]
	 [[Node: default_1/tower_1/sub_14 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](default_1/tower_1/Slice_1, default_1/tower_1/value_function/Reshape)]]

Caused by op 'default_1/tower_1/sub_14', defined at:
  File "/home/fangyu/GitHub/ray-eugene/python/ray/workers/default_worker.py", line 88, in <module>
    ray.worker.global_worker.main_loop()
  File "/home/fangyu/GitHub/ray-eugene/python/ray/worker.py", line 1103, in main_loop
    self._wait_for_and_process_task(task)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/worker.py", line 1060, in _wait_for_and_process_task
    self._process_task(task)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/agents/agent.py", line 216, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/tune/trainable.py", line 84, in __init__
    self._setup()
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/agents/agent.py", line 258, in _setup
    self._init()
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/agents/ppo/ppo.py", line 118, in _init
    "standardize_fields": ["advantages"],
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/optimizers/policy_optimizer.py", line 50, in __init__
    self._init(**self.config)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/optimizers/multi_gpu_optimizer.py", line 85, in _init
    os.getcwd())
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/optimizers/multi_gpu_impl.py", line 87, in __init__
    len(input_placeholders)))
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/optimizers/multi_gpu_impl.py", line 220, in _setup_device
    graph_obj = self.build_graph(device_input_slices)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/agents/ppo/ppo_policy_graph.py", line 234, in copy
    existing_inputs=existing_inputs)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/agents/ppo/ppo_policy_graph.py", line 217, in __init__
    self.value_function)
  File "/home/fangyu/GitHub/ray-eugene/python/ray/rllib/utils/explained_variance.py", line 10, in explained_variance
    _, diff_var = tf.nn.moments(y - pred, axes=[0])
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 850, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 8188, in sub
    "Sub", x=x, y=y, name=name)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/fangyu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Incompatible shapes: [2000] vs. [4000]
	 [[Node: default_1/tower_1/sub_14 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](default_1/tower_1/Slice_1, default_1/tower_1/value_function/Reshape)]]
```

**Comment by ericl** [comment]
Did you return the right number of outputs as specified by num_outputs? (this might be greater than the action space dimensions).

**Comment by fywu85** [comment]
Yes, that was the problem. Thx!
