### ISSUE TITLE
Installation failure on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by Anya28** [ray-project/ray#3027]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows Subsystem for Linux - Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: Unknown (cannot run ray.__version__ yet). Source was cloned from https://github.com/ray-project/ray.git on Oct 5, 2018.
- **Python version**: 3.6
- **Exact command to reproduce**: pip install -e . --verbose

### Describe the problem
 I followed the steps of ray installations as specified on the original website. I cloned the repo, and went into python folder using cd ray/python. But when I try running the "pip install -e . --verbose", it keeps on failing with an error shown below. Does anyone has any suggestions on how to fix this please?

### Source code / logs
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 845, in install
    install_options, global_options, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1007, in install_editable
    show_stdout=False)
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 725, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/mnt/c/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=" failed with error code 1 in /mnt/c/ray/python/

**Comment by robertnishihara** [comment]
I suspect it's failing earlier before this error message. Can you share the full output?
