### ISSUE TITLE
[Tune] Tuner.restore fails when restoring a relative path

### ISSUE THREAD

**Issue by aRI0U** [ray-project/ray#30342]
### What happened + What you expected to happen

When using `Tuner.restore` with `path` being a relative path, I get an `AssertionError`:
```
2022-11-16 17:14:33,790 INFO worker.py:1528 -- Started a local Ray instance.
Traceback (most recent call last):
  File "/home/alain/miniconda3/envs/evaltmp/lib/python3.10/site-packages/ray/tune/tuner.py", line 243, in fit
    return self._local_tuner.fit()
  File "/home/alain/miniconda3/envs/evaltmp/lib/python3.10/site-packages/ray/tune/impl/tuner_internal.py", line 297, in fit
    analysis = self._fit_resume(trainable)
  File "/home/alain/miniconda3/envs/evaltmp/lib/python3.10/site-packages/ray/tune/impl/tuner_internal.py", line 431, in _fit_resume
    analysis = run(**args)
  File "/home/alain/miniconda3/envs/evaltmp/lib/python3.10/site-packages/ray/tune/tune.py", line 538, in run
    experiments[i] = Experiment(
  File "/home/alain/miniconda3/envs/evaltmp/lib/python3.10/site-packages/ray/tune/experiment/experiment.py", line 155, in __init__
    assert local_dir_path in experiment_checkpoint_dir_path.parents
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alain/code/teacher-student/test_restore.py", line 47, in <module>
    train_dummy_models()
  File "/home/alain/code/teacher-student/test_restore.py", line 37, in train_dummy_models
    results = tuner.fit()
  File "/home/alain/miniconda3/envs/evaltmp/lib/python3.10/site-packages/ray/tune/tuner.py", line 245, in fit
    raise TuneError(
ray.tune.error.TuneError: The Ray Tune run failed. Please inspect the previous error messages for a cause. After fixing the issue, you can restart the run from scratch or continue this run. To continue this run, you can use `tuner = Tuner.restore("test-restore/train_dummy_2022-11-16_17-12-16")`.
```
 I finally figured out that this is because `local_dir_path` is always an absolute path whereas `experiment_checkpoint_dir_path` is the one you provide so they don't match if it is relative.

Using only absolute paths is an easy workaround, but the issue is that it was quite hard to guess the error with only the error message, so it would be great if relative paths would be supported or at least if it would be written somewhere that they're not. This is even more bothering since the final error message suggest that relative paths are actually supported...

### Versions / Dependencies

- Python: 3.10.6
- Ray: 2.1.0
- OS: Ubuntu 22.04

### Reproduction script

```python
import random
import time

import ray.air as air
import ray.tune as tune


def train_dummy(config):
    v = config["val"]
    for i in range(1, 10):
        time.sleep(random.randint(5, 15))
        tune.report(val=v / i)


def train_dummy_models():
    config = {'val': tune.uniform(10, 20)}
    tuner = tune.Tuner(
        tune.with_resources(
            train_dummy,
            resources={"cpu": 12, "gpu": 1}
        ),
        tune_config=tune.TuneConfig(
            num_samples=10,
            metric="val",
            mode="min"
        ),
        run_config=air.RunConfig(
            local_dir="test-restore"
        ),
        param_space=config
    )
    # comment the line below first time you run the script, and replace by the according timestamp when you restore it
    tuner = tune.Tuner.restore(path="test-restore/train_dummy_2022-11-16_17-12-16")
    results = tuner.fit()

    best_trial = results.get_best_result()
    print("Best trial:")
    print(best_trial)
    print("Best trial config:")
    print(best_trial.config)


if __name__ == "__main__":
    train_dummy_models()
```

Launch the script, wait a little, interrupt it with `CTRL+C` and then restore it with `tune.Tuner.restore` using the right path

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by Yard1** [comment]
@justinvyu
