### ISSUE TITLE
[RLlib] Error when running RLlib

### ISSUE THREAD

**Issue by Clown1206** [ray-project/ray#30412]
### What happened + What you expected to happen

I'm just starting to learn to use ray，I have a mistake, but I don't know how to solve it
```
Failure # 1 (occurred at 2022-11-17_18-45-44)
Traceback (most recent call last):
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\tune\execution\ray_trial_executor.py", line 989, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\_private\worker.py", line 2277, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::DQN.__init__()[39m (pid=27952, ip=127.0.0.1, repr=DQN)
  File "python\ray\_raylet.pyx", line 662, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 666, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 613, in ray._raylet.execute_task.function_executor
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\_private\function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 308, in __init__
    super().__init__(config=config, logger_creator=logger_creator, **kwargs)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\tune\trainable\trainable.py", line 157, in __init__
    self.setup(copy.deepcopy(self.config))
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 345, in setup
    self.validate_config(self.config)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\rllib\algorithms\dqn\dqn.py", line 320, in validate_config
    super().validate_config(config)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\rllib\algorithms\simple_q\simple_q.py", line 289, in validate_config
    validate_buffer_config(config)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\rllib\utils\replay_buffers\utils.py", line 170, in validate_buffer_config
    error=True,
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\rllib\utils\deprecation.py", line 43, in deprecation_warning
    raise DeprecationWarning(msg)
DeprecationWarning: `config['prioritized_replay'] or config['replay_buffer_config']['prioritized_replay']` has been deprecated. Replay prioritization specified by config key. RLlib's new replay buffer API requires setting `config['replay_buffer_config']['type']`, e.g. `config['replay_buffer_config']['type'] = 'MultiAgentPrioritizedReplayBuffer'` to change the default behaviour.
```

### Versions / Dependencies

ray=2.0
python=3.7

### Reproduction script
```
Failure # 1 (occurred at 2022-11-17_18-45-44)
Traceback (most recent call last):
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\tune\execution\ray_trial_executor.py", line 989, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\_private\worker.py", line 2277, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::DQN.__init__()[39m (pid=27952, ip=127.0.0.1, repr=DQN)
  File "python\ray\_raylet.pyx", line 662, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 666, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 613, in ray._raylet.execute_task.function_executor
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\_private\function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 308, in __init__
    super().__init__(config=config, logger_creator=logger_creator, **kwargs)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\tune\trainable\trainable.py", line 157, in __init__
    self.setup(copy.deepcopy(self.config))
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 345, in setup
    self.validate_config(self.config)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\rllib\algorithms\dqn\dqn.py", line 320, in validate_config
    super().validate_config(config)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\rllib\algorithms\simple_q\simple_q.py", line 289, in validate_config
    validate_buffer_config(config)
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\rllib\utils\replay_buffers\utils.py", line 170, in validate_buffer_config
    error=True,
  File "D:\Environment\Anaconda\envs\gpu-python3.7\lib\site-packages\ray\rllib\utils\deprecation.py", line 43, in deprecation_warning
    raise DeprecationWarning(msg)
DeprecationWarning: `config['prioritized_replay'] or config['replay_buffer_config']['prioritized_replay']` has been deprecated. Replay prioritization specified by config key. RLlib's new replay buffer API requires setting `config['replay_buffer_config']['type']`, e.g. `config['replay_buffer_config']['type'] = 'MultiAgentPrioritizedReplayBuffer'` to change the default behaviour.
```

**Comment by matthewdeng** [comment]
@Clown1206

Are you able to apply the suggestion in the warning?
> DeprecationWarning: `config['prioritized_replay'] or config['replay_buffer_config']['prioritized_replay']` has been deprecated. Replay prioritization specified by config key. RLlib's new replay buffer API requires setting `config['replay_buffer_config']['type']`, e.g. `config['replay_buffer_config']['type'] = 'MultiAgentPrioritizedReplayBuffer'` to change the default behaviour.

Alternatively, can you provide a repro script?

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
