### ISSUE TITLE
[Rllib] Using Dict state space throws exception (not supported yet?)

### ISSUE THREAD

**Issue by Jonathan-Livingston-Seagull** [ray-project/ray#3042]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux 16.04
- **Ray installed from (source or binary)**: Source
- **Ray version**:0.5.3
- **Python version**: 3.6.6
- **Exact command to reproduce**:

### Describe the problem

I am trying to use Dict state space with PPO but it throws an exception.  More details below.
### Source code / logs

```
class MyServing(ServingEnv):
    def __init__(self):
        ServingEnv.__init__(
            self, spaces.Box(-1.0, 1.0, (1,), dtype=np.float32),
            spaces.Dict({"image":spaces.Box(0.0, 1.0, (img_height, img_width, 3), dtype=np.float32),
                         "speed": spaces.Box(0.0, 1.0, (1,), dtype=np.float32)}))
    def run(self):
        print("Starting policy server at {}:{}".format(SERVER_ADDRESS,
                                                       SERVER_PORT))
        server = PolicyServer(self, SERVER_ADDRESS, SERVER_PORT)
        server.serve_forever()
if __name__ == "__main__":
    register_my_model()
    ray.init(num_gpus=1)
    register_env("srv", lambda _: MyServing())

    # We use DQN since it supports off-policy actions, but you can choose and
    # configure any agent.
    ppo = PPOAgent(
        env="srv",
        config={
            # Use a single process to avoid needing to set up a load balancer
            "num_workers": 0,
            "num_gpus": 1,
            "batch_mode": "complete_episodes",
            "train_batch_size": 2000,
            "model": {
                "custom_model": "mymodel"
            },
            #"num_gpus":1,
            # Configure the agent to run short iterations for debugging
            #"exploration_fraction": 0.01,
            #"learning_starts": 100,
            #"timesteps_per_iteration": 200,
            #"schedule_max_timesteps": 100000,
            #"gamma": 0.8,
            "tf_session_args": {
                "gpu_options": {"allow_growth": True},
            },
        })

  File "/RL/ray-master/ray/python/ray/rllib/my_scripts/ppo/udacity_server_ppo.py", line 142, in <module>
    "gpu_options": {"allow_growth": True},
  File "/RL/ray-master/ray/python/ray/rllib/agents/agent.py", line 216, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/RL/ray-master/ray/python/ray/tune/trainable.py", line 86, in __init__
    self._setup()
  File "/RL/ray-master/ray/python/ray/rllib/agents/agent.py", line 258, in _setup
    self._init()
  File "/RL/ray-master/ray/python/ray/rllib/agents/ppo/ppo.py", line 85, in _init
    self.env_creator, self._policy_graph)
  File "/RL/ray-master/ray/python/ray/rllib/agents/agent.py", line 131, in make_local_evaluator
    "inter_op_parallelism_threads": None,
  File "/RL/ray-master/ray/python/ray/rllib/agents/agent.py", line 171, in _make_evaluator
    monitor_path=self.logdir if config["monitor"] else None)
  File "/RL/ray-master/ray/python/ray/rllib/evaluation/policy_evaluator.py", line 228, in __init__
    policy_dict, policy_config)
  File "/RL/ray-master/ray/python/ray/rllib/evaluation/policy_evaluator.py", line 286, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/RL/ray-master/ray/python/ray/rllib/agents/ppo/ppo_policy_graph.py", line 123, in __init__
    shape=(None, ) + observation_space.shape)
TypeError: can only concatenate tuple (not "NoneType") to tuple
```

**Comment by ericl** [comment]
We don't support dict spaces right now, but one reasonable workaround is to flatten your dict into a vector, and reconstruct the original dict within your model using tf.slice / tf.reshape.

There's an example of this with Carla here: https://github.com/ray-project/ray/blob/master/python/ray/rllib/examples/carla/models.py

**Comment by Jonathan-Livingston-Seagull** [comment]
Thanks for the reference. That helps.

**Comment by ericl** [comment]
@Jonathan-Livingston-Seagull this is also fixed in https://github.com/ray-project/ray/pull/3051, it would be great if you could that a try!

**Comment by Jonathan-Livingston-Seagull** [comment]
@ericl I have tried the pull request but it seems the fix did not help. I get the same error as before.

**Comment by ericl** [comment]
@Jonathan-Livingston-Seagull Thanks for testing this. I've pushed a change to that branch that adds the dict support for ServingEnv as well.

**Comment by richardliaw** [comment]
@Jonathan-Livingston-Seagull Can you try the updated fix in the PR and let us know if it solves your issue?

**Comment by Jonathan-Livingston-Seagull** [comment]
@ericl @richardliaw It works now. Thanks. However I had to parse the inputs in build_layer as in the previously mentioned carla example. Is it the intended  solution? I thought the build_layer method will get a dict so that one does not need to parse the inputs, but access it via key instead.

**Comment by ericl** [comment]
You should use build_layers_v2, which exposes it as a dict. I left the
original function alone for backwards compatibility.

**Comment by Jonathan-Livingston-Seagull** [comment]
@ericl ok. Thanks for pointing that out. I tired with build_layers_v2 and I have noticed that for the first two calls to build_layers_v2, I get the dict as expected but for the third call I get a dict of concatenated input as shown before which results in an exception since key indexing does not work anymore on that.
`{'obs': <tf.Tensor 'default/obs:0' shape=(?, 39601) dtype=float32>, 'prev_actions': <tf.Tensor 'default/action_1:0' shape=(?, 1) dtype=float32>, 'prev_rewards': <tf.Tensor 'default/prev_reward:0' shape=(?,) dtype=float32>}
`

**Comment by ericl** [comment]
@Jonathan-Livingston-Seagull thanks for reporting that. Turns out I forgot to pass the observation space to the gpu model replicas. It should be fixed, can you try again now?

**Comment by Jonathan-Livingston-Seagull** [comment]
@ericl I can confirm that, the dict state space works now. Thanks for the fix.

**Comment by kivo360** [comment]
Does this work with an action space too? I'm getting an error after modifying the sample code. It's only a slight modification of the code from the policyserver example:

```python
import os
from gym import spaces
import numpy as np

import ray
from ray.rllib.agents.dqn import DQNAgent
from ray.rllib.agents.ppo import PPOAgent
from ray.rllib.env.external_env import ExternalEnv
from ray.rllib.utils.policy_server import PolicyServer
from ray.tune.logger import pretty_print
from ray.tune.registry import register_env

SERVER_ADDRESS = "localhost"
SERVER_PORT = 9900
CHECKPOINT_FILE = "last_checkpoint.out"


class CartpoleServing(ExternalEnv):
    def __init__(self):
        ExternalEnv.__init__(
            self, spaces.Dict({'micro': spaces.Discrete(3)}),
            spaces.Box(low=-10, high=10, shape=(4, ), dtype=np.float32))

    def run(self):
        print("Starting policy server at {}:{}".format(SERVER_ADDRESS,
                                                       SERVER_PORT))
        server = PolicyServer(self, SERVER_ADDRESS, SERVER_PORT)
        server.serve_forever()


if __name__ == "__main__":
    ray.init()
    register_env("srv", lambda _: CartpoleServing())

    # We use DQN since it supports off-policy actions, but you can choose and
    # configure any agent.
    dqn = PPOAgent(
        env="srv",
        config={
            # Use a single process to avoid needing to set up a load balancer
            "num_workers": 0,
            "num_gpus": 1
        })
```

It returns the error:

```python
Traceback (most recent call last):
  File "cartpole_server.py", line 55, in <module>
    "num_gpus": 1
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 257, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/tune/trainable.py", line 88, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 333, in _setup
    self._init()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/agents/ppo/ppo.py", line 77, in _init
    self.env_creator, self._policy_graph)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 466, in make_local_evaluator
    extra_config or {}))
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 608, in _make_evaluator
    output_creator=output_creator)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 274, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 611, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/agents/ppo/ppo_policy_graph.py", line 120, in __init__
    action_space, self.config["model"])
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/models/catalog.py", line 137, in get_action_dist
    action_space, dist_type))
NotImplementedError: Unsupported args: Dict(order:Discrete(3)) None
Exception ignored in: <bound method PolicyEvaluator.__del__ of <ray.rllib.evaluation.policy_evaluator.PolicyEvaluator object at 0x7f42c3ea6710>>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 615, in __del__
    if isinstance(self.sampler, AsyncSampler):
AttributeError: 'PolicyEvaluator' object has no attribute 'sampler'

```

**Comment by ericl** [comment]
No, but Tuple action spaces are supported (you could probably get dict actions to work on top of that).
