### ISSUE TITLE
[rllib] ValueError: setting an array element with a sequence

### ISSUE THREAD

**Issue by pethor** [ray-project/ray#3043]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 9.5
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5.3
- **Python version**: 3.5.2
- **Exact command to reproduce**: `agent.train()`

### Describe the problem

I'm trying to develop a custom recurrent network similar to LSTMs for Ray. Sticking to the PPO example, I use the following code to produce the error below:

```python3
import ray
import ray.rllib.agents.ppo as ppo
from ray.tune.logger import pretty_print

ray.init()
config = ppo.DEFAULT_CONFIG.copy()
config["num_gpus"] = 0
config["num_workers"] = 1
config["model"]["use_rnn"] = True
agent = ppo.PPOAgent(config=config, env="CartPole-v0")

for i in range(100):
    result = agent.train() # <-- here it dies
    print(pretty_print(result))
```

This produces the following error that I'm unable to interpret. What I try to do is to simulate the behaviour of the built-in LSTM by appropriately duplicating / expanding all occurances of `'use_lstm'` with `'use_rnn'`. The thing is, that my internal state for my RNN has different shapes than the LSTM state, could this be a problem?

I know that when you try to do something like 
```python3
np.asarray([[1, 2], [2, 3, 4]], dtype=np.float)
```
you will get the same error. However, since I'm new to Ray I'm unfamiliar with how to debug such issues deep in the framework. Do you have any suggestions?

### Source code / logs

```
Error fetching: [<tf.Tensor 'default/Squeeze:0' shape=(?,) dtype=int64>, <tf.Tensor 'default/rnn/while/Exit_4:0' shape=(128, 256) dtype=float32>, <tf.Tensor 'default/rnn/while/Exit_5:0' shape=(128, 256) dtype=float32>, <tf.Tensor 'default/rnn/while/Exit_6:0' shape=(128, 256) dtype=float32>, <tf.Tensor 'default/rnn/while/Exit_7:0' shape=(128, 256, 1) dtype=float32>, <tf.Tensor 'default/rnn/while/Exit_8:0' shape=(128, 256, 3) dtype=float32>, {'vf_preds': <tf.Tensor 'default/value_function/Reshape_2:0' shape=(?,) dtype=float32>, 'logits': <tf.Tensor 'default/add:0' shape=(?, 2) dtype=float32>}], feed_dict={<tf.Tensor 'default/PlaceholderWithDefault:0' shape=() dtype=bool>: True, <tf.Tensor 'default/TupleStateHolder/b:0' shape=(128, 256) dtype=float32>: [<tf.Tensor 'default/zeros_2:0' shape=(128, 256) dtype=float32>], <tf.Tensor 'default/TupleStateHolder/z_buffer:0' shape=(128, 256, 3) dtype=float32>: [<tf.Tensor 'default/zeros_4:0' shape=(128, 256, 3) dtype=float32>], <tf.Tensor 'default/obs:0' shape=(?, 4) dtype=float32>: [array([0., 0., 0., 0.])], <tf.Tensor 'default/TupleStateHolder/z:0' shape=(128, 256) dtype=float32>: [<tf.Tensor 'default/zeros_1:0' shape=(128, 256) dtype=float32>], <tf.Tensor 'default/seq_lens_1:0' shape=(?,) dtype=int32>: array([1.]), <tf.Tensor 'default/TupleStateHolder/v:0' shape=(128, 256) dtype=float32>: [<tf.Tensor 'default/zeros:0' shape=(128, 256) dtype=float32>], <tf.Tensor 'default/TupleStateHolder/i_future_buffer:0' shape=(128, 256, 1) dtype=float32>: [<tf.Tensor 'default/zeros_3:0' shape=(128, 256, 1) dtype=float32>]}
Remote function sample failed with:

Traceback (most recent call last):
  File "/home/pethor/Documents/project/venv/lib/python3.5/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/pethor/Documents/project/venv/lib/python3.5/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/pethor/Documents/project/venv/lib/python3.5/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 303, in sample
    batches = [self.sampler.get_data()]
  File "/home/pethor/Documents/project/venv/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 58, in get_data
    item = next(self.rollout_provider)
  File "/home/pethor/Documents/project/venv/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 362, in _env_runner
    eval_results[k] = builder.get(v)
  File "/home/pethor/Documents/project/venv/lib/python3.5/site-packages/ray/rllib/utils/tf_run_builder.py", line 47, in get
    raise e
  File "/home/pethor/Documents/project/venv/lib/python3.5/site-packages/ray/rllib/utils/tf_run_builder.py", line 43, in get
    self.feed_dict, os.environ.get("TF_TIMELINE_DIR"))
  File "/home/pethor/Documents/project/venv/lib/python3.5/site-packages/ray/rllib/utils/tf_run_builder.py", line 82, in run_timeline
    fetches = sess.run(ops, feed_dict=feed_dict)
  File "/home/pethor/Documents/project/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/pethor/Documents/project/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1109, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/pethor/Documents/project/venv/lib/python3.5/site-packages/numpy/core/numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
```

**Comment by ericl** [comment]
Hmm, if the state size is changed, did you make sure to change the initial state as well? I'd try to start with the included LSTM model and adapt it to your needs.

**Comment by llan-ml** [comment]
@pethor The reason for that error is the value of a feed is a list of a single tensor.
<pre>
In [1]: import tensorflow as tf

In [2]: import numpy as np

In [3]: x = tf.placeholder(tf.float32, [10, 10])

In [4]: y = tf.zeros([10, 10], dtype=tf.float32)

In [5]: sess = tf.InteractiveSession()
2018-10-11 18:17:59.095853: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

In [6]: try:
   ...:     sess.run(x, feed_dict={x: [y]})
   ...: except Exception as e:
   ...:     print(e)
   ...:
setting an array element with a sequence.

In [7]: try:
   ...:     sess.run(x, feed_dict={x: y})
   ...: except Exception as e:
   ...:     print(e)
   ...:
The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles.For reference, the tensor object was Tensor("zeros:0", shape=(10, 10), dtype=float32) which was passed to the feed with key Tensor("Placeholder:0", shape=(10, 10), dtype=float32).
</pre>
