### ISSUE TITLE
[Core] Generator API does not work with Ray Client

### ISSUE THREAD

**Issue by c21** [ray-project/ray#30458]
### What happened + What you expected to happen

When enabling dynamic block splitting in Datasets (i.e. enabling using generator API from Core), found it failed CI test `python/ray/tests/test_usage_stats.py::test_library_usages[True]`, with stack trace:

```
python/ray/tests/test_usage_stats.py::test_library_usages[True] 2022-11-17 19:17:28,147 INFO workflow_access.py:356 -- Initializing workflow manager...
Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "/Users/chengsu/ray/python/ray/data/read_api.py", line 152, in range
    return read_datasource(
  File "/Users/chengsu/ray/python/ray/data/read_api.py", line 333, in read_datasource
    block_list.compute_first_block()
  File "/Users/chengsu/ray/python/ray/data/_internal/lazy_block_list.py", line 357, in compute_first_block
    self._get_or_compute(0)
  File "/Users/chengsu/ray/python/ray/data/_internal/lazy_block_list.py", line 561, in _get_or_compute
    ) = self._submit_task(j)
  File "/Users/chengsu/ray/python/ray/data/_internal/lazy_block_list.py", line 591, in _submit_task
    cached_remote_fn(_execute_read_task_split)
  File "/Users/chengsu/ray/python/ray/remote_function.py", line 225, in remote
    return func_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/Users/chengsu/ray/python/ray/util/tracing/tracing_helper.py", line 307, in _invocation_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/Users/chengsu/ray/python/ray/remote_function.py", line 246, in _remote
    return client_mode_convert_function(self, args, kwargs, **task_options)
  File "/Users/chengsu/ray/python/ray/_private/client_mode_hook.py", line 178, in client_mode_convert_function
    return client_func._remote(in_args, in_kwargs, **kwargs)
  File "/Users/chengsu/ray/python/ray/util/client/common.py", line 298, in _remote
    return self.options(**option_args).remote(*args, **kwargs)
  File "/Users/chengsu/ray/python/ray/util/client/common.py", line 572, in remote
    return return_refs(ray.call_remote(self, *args, **kwargs))
  File "/Users/chengsu/ray/python/ray/util/client/api.py", line 100, in call_remote
    return self.worker.call_remote(instance, *args, **kwargs)
  File "/Users/chengsu/ray/python/ray/util/client/worker.py", line 559, in call_remote
    return self._call_schedule_for_task(task, instance._num_returns())
  File "/Users/chengsu/ray/python/ray/util/client/worker.py", line 569, in _call_schedule_for_task
    id_futures = [Future() for _ in range(num_returns)]
TypeError: 'str' object cannot be interpreted as an integer
```

With generator API, `num_returns` would be "dynamic", but not an integer. So it looks like generator API does not work with current Ray client code.

### Versions / Dependencies

master (w/ dynamic block splittiing enabled)

### Reproduction script

Above unit test

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by c21** [comment]
cc @stephanie-wang FYI.
