### ISSUE TITLE
[release][core] all microbenchmark_* are failing

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30498]
https://buildkite.com/ray-project/release-tests-branch/builds/1202#_

(AsyncActor pid=47938) sys:1: RuntimeWarning: coroutine 'execute_task.<locals>.deserialize_args' was never awaited
Traceback (most recent call last):
  File "run_microbenchmark.py", line 16, in <module>
    results = main() or []
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/ray_perf.py", line 250, in main
    results += timeit("1:1 async-actor calls with args async", async_actor, 1000)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/ray_microbenchmark_helpers.py", line 26, in timeit
    fn()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/ray_perf.py", line 248, in async_actor
    ray.get([a.small_value_with_arg.remote(i) for i in range(1000)])
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RecursionError): ray::AsyncActor.small_value_with_arg() (pid=47938, ip=172.31.116.13, repr=<ray._private.ray_perf.AsyncActor object at 0x7f6c5192fb50>)
  File "/home/ray/anaconda3/lib/python3.7/asyncio/tasks.py", line 836, in run_coroutine_threadsafe
    future = concurrent.futures.Future()
  File "/home/ray/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 314, in __init__
    self._condition = threading.Condition()
  File "/home/ray/anaconda3/lib/python3.7/threading.py", line 218, in __init__
    lock = RLock()
RecursionError: maximum recursion depth exceeded

**Comment by iycheng** [comment]
```
1:1 async-actor calls async per second 2831.84 +- 23.13
Traceback (most recent call last):
  File "run_microbenchmark.py", line 16, in <module>
    results = main() or []
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/ray_perf.py", line 250, in main
    results += timeit("1:1 async-actor calls with args async", async_actor, 1000)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/ray_microbenchmark_helpers.py", line 26, in timeit
    fn()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/ray_perf.py", line 248, in async_actor
    ray.get([a.small_value_with_arg.remote(i) for i in range(1000)])
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RecursionError): ray::AsyncActor.small_value_with_arg() (pid=42918, ip=172.31.61.108, repr=<ray._private.ray_perf.AsyncActor object at 0x7f02a879b100>)
  File "/home/ray/anaconda3/lib/python3.8/asyncio/tasks.py", line 918, in run_coroutine_threadsafe
    future = concurrent.futures.Future()
  File "/home/ray/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 318, in __init__
    self._condition = threading.Condition()
  File "/home/ray/anaconda3/lib/python3.8/threading.py", line 224, in __init__
    lock = RLock()
RecursionError: maximum recursion depth exceeded
(AsyncActor pid=42918) sys:1: RuntimeWarning: coroutine 'execute_task.<locals>.deserialize_args' was never awaited
```

**Comment by iycheng** [comment]
Reproduced. Bisecting now.

**Comment by iycheng** [comment]
Seems the offending one is 3fbd9a66389fd720cb38da252498b7d485beeedc. Still double confirming.
```
commit 3fbd9a66389fd720cb38da252498b7d485beeedc (refs/bisect/bad)
Author: Ricky Xu <xuchen727@hotmail.com>
Date:   Wed Nov 16 15:48:14 2022 -0800

    Revert "Revert "[Prototype] [Core] Make expensive subpackage imports dynamic. (#27658)" (#29659)" (#30219)

    This reverts commit b0bd2700a5f14d8d11555677805d773b7beb9bd4.

commit 46d5b74fdd250b7adef4f45b28b5cea3047b39c1 (refs/bisect/good-46d5b74fdd250b7adef4f45b28b5cea3047b39c1)
Author: clarng <clarence.wyng@gmail.com>
Date:   Wed Nov 16 15:46:36 2022 -0800

    [core] allow fractional memory for remote options (#30208)

    Fixes regression. We used to allow fractional memory inputs. As part of fixing the regression we are also slightly modifying the behavior to round down the memory value, which is consistent with the memory option in ray.init

    Signed-off-by: Clarence Ng <clarence.wyng@gmail.com>
```

**Comment by iycheng** [comment]
@rickyyx  3fbd9a66389fd720cb38da252498b7d485beeedc is the offending one

Pass to you for further investigation.

**Comment by rickyyx** [comment]
So reverting the indirect import with direct import here fixes the issue: https://github.com/ray-project/ray/blob/7c8859f1428224710e4c2db2abf0d9ec28536301/python/ray/__init__.py#L259-L265

Seems to me the recursion is caused by we overriding `__getattr__` and somehow the importlib call recursively calls it it again. But I don't have a clear stacktrace yet. 

Also cc @clarkzinzow and see if you have any thoughts on fixes for this.
