### ISSUE TITLE
[Core] ray.exceptions.RaySystemError: System error: buffer source array is read-only

### ISSUE THREAD

**Issue by hanyuyangddgh** [ray-project/ray#30505]
### What happened + What you expected to happen

Hi team, we encountered this error with ray when using pandas: `ray.exceptions.RaySystemError: System error: buffer source array is read-only` and there seems to be still no fix yet? https://github.com/project-codeflare/codeflare/issues/39

The expected behavior should return a list when this code block is called:
```python
futures = [
    parallel_fit_wrapper.remote(
        model_class=self.model_class,
        data_class=self.data_class,
        process_date=params['process_date'],
        external_config=params['external_config'],
        model_fit_config=params['model_config'],
        n_preds=self.prediction_horizon,
        min_pred_value=self.min_pred_value,
        replace_low_preds=self.replace_low_preds,
        final_model_flag=params['process_date'] == self.end_date,
        ignore_not_enough_data=ignore_not_enough_data,
    )
    for params in param_list
]
results = ray.get(futures)
```

the below joblib.Parallel() alternative works though:
```
with Parallel(n_jobs=n_jobs, backend='loky') as parallel:
    results = parallel(
        delayed(parallel_fit_wrapper)(
            model_class=self.model_class,
            data_class=self.data_class,
            process_date=params['process_date'],
            external_config=params['external_config'],
            model_fit_config=params['model_config'],
            n_preds=self.prediction_horizon,
            min_pred_value=self.min_pred_value,
            replace_low_preds=self.replace_low_preds,
            final_model_flag=params['process_date'] == self.end_date,
            ignore_not_enough_data=ignore_not_enough_data,
        )
        for params in param_list
    )
```

so we are blocked on the ray migration on this block of code in unit test.

here are the logs:
```
[2022-11-18T16:54:09.584Z] =================================== FAILURES ===================================
[2022-11-18T16:54:09.584Z] _____________________ TestModels.test_sarimax_integration ______________________
[2022-11-18T16:54:09.584Z] 
[2022-11-18T16:54:09.584Z] self = <tests.unit.forecast_factory.daily_model_test.TestModels object at 0x7f66bb168880>
[2022-11-18T16:54:09.584Z] 
[2022-11-18T16:54:09.584Z]     def test_sarimax_integration(self):
[2022-11-18T16:54:09.584Z]         configs = sarimax_daily_pred_config(
[2022-11-18T16:54:09.584Z]             order=[[3, 1, 3]], seasonal_order=[[1, 1, 1, 7]], trend=[[0, 0, 0, 0]]
[2022-11-18T16:54:09.584Z]         )
[2022-11-18T16:54:09.584Z] >       error, model = self.base_model_run(
[2022-11-18T16:54:09.584Z]             SARIMAXFit, configs, model_eval_class=MASEEvaluator, naive_steps=7
[2022-11-18T16:54:09.584Z]         )
[2022-11-18T16:54:09.584Z] 
[2022-11-18T16:54:09.584Z] tests/unit/forecast_factory/daily_model_test.py:215: 
[2022-11-18T16:54:09.584Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2022-11-18T16:54:09.584Z] tests/unit/forecast_factory/daily_model_test.py:160: in base_model_run
[2022-11-18T16:54:09.584Z]     grids.random_search(n_jobs=1, n_iter=4)
[2022-11-18T16:54:09.584Z] /usr/local/lib/python3.8/site-packages/typeguard/__init__.py:927: in wrapper
[2022-11-18T16:54:09.584Z]     retval = func(*args, **kwargs)
[2022-11-18T16:54:09.584Z] forecast_factory/parameter_search/parameter_search.py:757: in random_search
[2022-11-18T16:54:09.584Z]     df_predictions, df_models = self._train_models(
[2022-11-18T16:54:09.584Z] /usr/local/lib/python3.8/site-packages/typeguard/__init__.py:927: in wrapper
[2022-11-18T16:54:09.584Z]     retval = func(*args, **kwargs)
[2022-11-18T16:54:09.584Z] forecast_factory/parameter_search/parameter_search.py:630: in _train_models
[2022-11-18T16:54:09.584Z]     results = ray.get(futures)
[2022-11-18T16:54:09.584Z] /usr/local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:105: in wrapper
[2022-11-18T16:54:09.584Z]     return func(*args, **kwargs)
[2022-11-18T16:54:09.584Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2022-11-18T16:54:09.584Z] 
[2022-11-18T16:54:09.584Z] object_refs = [ObjectRef(a631fe8d231813bfffffffffffffffffffffffff0100000001000000), ObjectRef(79cc316456d39201ffffffffffffffffffffff...9deffffffffffffffffffffffff0100000001000000), ObjectRef(ae46b8beecd25f3affffffffffffffffffffffff0100000001000000), ...]
[2022-11-18T16:54:09.584Z] 
[2022-11-18T16:54:09.584Z]     @PublicAPI
[2022-11-18T16:54:09.584Z]     @client_mode_hook(auto_init=True)
[2022-11-18T16:54:09.584Z]     def get(
[2022-11-18T16:54:09.584Z]         object_refs: Union[ray.ObjectRef, Sequence[ray.ObjectRef]],
[2022-11-18T16:54:09.584Z]         *,
[2022-11-18T16:54:09.584Z]         timeout: Optional[float] = None,
[2022-11-18T16:54:09.584Z]     ) -> Union[Any, List[Any]]:
[2022-11-18T16:54:09.584Z]         """Get a remote object or a list of remote objects from the object store.
[2022-11-18T16:54:09.584Z]     
[2022-11-18T16:54:09.584Z]         This method blocks until the object corresponding to the object ref is
[2022-11-18T16:54:09.584Z]         available in the local object store. If this object is not in the local
[2022-11-18T16:54:09.584Z]         object store, it will be shipped from an object store that has it (once the
[2022-11-18T16:54:09.584Z]         object has been created). If object_refs is a list, then the objects
[2022-11-18T16:54:09.584Z]         corresponding to each object in the list will be returned.
[2022-11-18T16:54:09.584Z]     
[2022-11-18T16:54:09.584Z]         Ordering for an input list of object refs is preserved for each object
[2022-11-18T16:54:09.584Z]         returned. That is, if an object ref to A precedes an object ref to B in the
[2022-11-18T16:54:09.584Z]         input list, then A will precede B in the returned list.
[2022-11-18T16:54:09.584Z]     
[2022-11-18T16:54:09.584Z]         This method will issue a warning if it's running inside async context,
[2022-11-18T16:54:09.584Z]         you can use ``await object_ref`` instead of ``ray.get(object_ref)``. For
[2022-11-18T16:54:09.584Z]         a list of object refs, you can use ``await asyncio.gather(*object_refs)``.
[2022-11-18T16:54:09.584Z]     
[2022-11-18T16:54:09.584Z]         Args:
[2022-11-18T16:54:09.584Z]             object_refs: Object ref of the object to get or a list of object refs
[2022-11-18T16:54:09.584Z]                 to get.
[2022-11-18T16:54:09.584Z]             timeout (Optional[float]): The maximum amount of time in seconds to
[2022-11-18T16:54:09.584Z]                 wait before returning.
[2022-11-18T16:54:09.584Z]     
[2022-11-18T16:54:09.584Z]         Returns:
[2022-11-18T16:54:09.584Z]             A Python object or a list of Python objects.
[2022-11-18T16:54:09.584Z]     
[2022-11-18T16:54:09.584Z]         Raises:
[2022-11-18T16:54:09.584Z]             GetTimeoutError: A GetTimeoutError is raised if a timeout is set and
[2022-11-18T16:54:09.584Z]                 the get takes longer than timeout to return.
[2022-11-18T16:54:09.584Z]             Exception: An exception is raised if the task that created the object
[2022-11-18T16:54:09.584Z]                 or that created one of the objects raised an exception.
[2022-11-18T16:54:09.584Z]         """
[2022-11-18T16:54:09.584Z]         worker = global_worker
[2022-11-18T16:54:09.584Z]         worker.check_connected()
[2022-11-18T16:54:09.584Z]     
[2022-11-18T16:54:09.584Z]         if hasattr(worker, "core_worker") and worker.core_worker.current_actor_is_asyncio():
[2022-11-18T16:54:09.584Z]             global blocking_get_inside_async_warned
[2022-11-18T16:54:09.584Z]             if not blocking_get_inside_async_warned:
[2022-11-18T16:54:09.584Z]                 logger.warning(
[2022-11-18T16:54:09.584Z]                     "Using blocking ray.get inside async actor. "
[2022-11-18T16:54:09.584Z]                     "This blocks the event loop. Please use `await` "
[2022-11-18T16:54:09.584Z]                     "on object ref with asyncio.gather if you want to "
[2022-11-18T16:54:09.584Z]                     "yield execution to the event loop instead."
[2022-11-18T16:54:09.584Z]                 )
[2022-11-18T16:54:09.584Z]                 blocking_get_inside_async_warned = True
[2022-11-18T16:54:09.584Z]     
[2022-11-18T16:54:09.584Z]         with profiling.profile("ray.get"):
[2022-11-18T16:54:09.584Z]             is_individual_id = isinstance(object_refs, ray.ObjectRef)
[2022-11-18T16:54:09.584Z]             if is_individual_id:
[2022-11-18T16:54:09.584Z]                 object_refs = [object_refs]
[2022-11-18T16:54:09.584Z]     
[2022-11-18T16:54:09.584Z]             if not isinstance(object_refs, list):
[2022-11-18T16:54:09.584Z]                 raise ValueError(
[2022-11-18T16:54:09.584Z]                     "'object_refs' must either be an object ref "
[2022-11-18T16:54:09.584Z]                     "or a list of object refs."
[2022-11-18T16:54:09.584Z]                 )
[2022-11-18T16:54:09.584Z]     
[2022-11-18T16:54:09.584Z]             # TODO(ujvl): Consider how to allow user to retrieve the ready objects.
[2022-11-18T16:54:09.584Z]             values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
[2022-11-18T16:54:09.584Z]             for i, value in enumerate(values):
[2022-11-18T16:54:09.584Z]                 if isinstance(value, RayError):
[2022-11-18T16:54:09.584Z]                     if isinstance(value, ray.exceptions.ObjectLostError):
[2022-11-18T16:54:09.584Z]                         worker.core_worker.dump_object_store_memory_usage()
[2022-11-18T16:54:09.584Z]                     if isinstance(value, RayTaskError):
[2022-11-18T16:54:09.584Z]                         raise value.as_instanceof_cause()
[2022-11-18T16:54:09.584Z]                     else:
[2022-11-18T16:54:09.584Z] >                       raise value
[2022-11-18T16:54:09.584Z] E                       ray.exceptions.RaySystemError: System error: buffer source array is read-only
[2022-11-18T16:54:09.584Z] E                       traceback: Traceback (most recent call last):
[2022-11-18T16:54:09.584Z] E                         File "/usr/local/lib/python3.8/site-packages/ray/_private/serialization.py", line 352, in deserialize_objects
[2022-11-18T16:54:09.584Z] E                           obj = self._deserialize_object(data, metadata, object_ref)
[2022-11-18T16:54:09.584Z] E                         File "/usr/local/lib/python3.8/site-packages/ray/_private/serialization.py", line 241, in _deserialize_object
[2022-11-18T16:54:09.584Z] E                           return self._deserialize_msgpack_data(data, metadata_fields)
[2022-11-18T16:54:09.584Z] E                         File "/usr/local/lib/python3.8/site-packages/ray/_private/serialization.py", line 196, in _deserialize_msgpack_data
[2022-11-18T16:54:09.584Z] E                           python_objects = self._deserialize_pickle5_data(pickle5_data)
[2022-11-18T16:54:09.584Z] E                         File "/usr/local/lib/python3.8/site-packages/ray/_private/serialization.py", line 184, in _deserialize_pickle5_data
[2022-11-18T16:54:09.584Z] E                           obj = pickle.loads(in_band, buffers=buffers)
[2022-11-18T16:54:09.584Z] E                         File "statsmodels/tsa/statespace/_initialization.pyx", line 227, in statsmodels.tsa.statespace._initialization.dInitialization.__init__
[2022-11-18T16:54:09.584Z] E                         File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
[2022-11-18T16:54:09.584Z] E                         File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
[2022-11-18T16:54:09.584Z] E                       ValueError: buffer source array is read-only
[2022-11-18T16:54:09.584Z] 
[2022-11-18T16:54:09.584Z] /usr/local/lib/python3.8/site-packages/ray/_private/worker.py:2282: RaySystemError
```

### Versions / Dependencies

ray[default]==2.0.1
pandas==1.2.3
pandas-stubs==1.5.1.221024
gspread-pandas==2.3.0

platform linux -- Python 3.8.5, pytest-5.4.3, py-1.11.0, pluggy-0.13.1

### Reproduction script

Will add later

### Issue Severity

High: It blocks me from completing my task.

**Comment by cszhu** [comment]
This P2 issue has seen no activity in the past 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please comment and remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
