### ISSUE TITLE
setting up ray on a  sge cluster throws error

### ISSUE THREAD

**Issue by kirk86** [ray-project/ray#3052]
### System information
- **OS Platform and Distribution (RedHat 6.xx, SGE)**:
- **Ray installed from (binary)**:
- **Ray version: 0.5.3**:
- **Python version: 3.6.6**:

### Describe the problem
Hi I am trying to setup ray on a SGE cluster using pbs scheduler,
I have managed to execute the commands between two nodes one acting as master and the other as worker. The problem is that ray is not able to connect the worker node to the master node.

Here's the error:

### Source code / logs
```
*** Launching Ray on head node node16, saving redis_address in ~/raylogs.txt ***
Using IP address xxx.xxx.xxx.24 for this node.
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:9999 to respond...
Waiting for redis server at 127.0.0.1:59695 to respond...
Starting the Plasma object store with 54.00 GB memory.
Starting local scheduler with the following resources: {'CPU': 24, 'GPU': 0}.
Failed to start the UI, you may need to run 'pip install jupyter'.
{'node_ip_address': 'xxx.xxx.xxx.24', 'redis_address': 'xxx.xxx.xxx.24:9999', 'object_store_addresses': [ObjectStoreAddress(name='/tmp/plasma_store67503539', manager_name='/tmp/plasma_manager14134124', manager_port=56672)], 'local_scheduler_socket_names': ['/tmp/scheduler97265308'], 'raylet_socket_names': [], 'webui_url': None}

Started Ray on this node. You can add additional nodes to the cluster by calling

    ray start --redis-address xxx.xxx.xxx.24:9999

from the node you wish to add. You can connect a driver to the cluster from Python by running

    import ray
    ray.init(redis_address="xxx.xxx.xxx.24:9999")

If you have trouble connecting from a different machine, check that your firewall is configured properly. If you wish to terminate the processes that have been started, run

    ray stop

*** Launching Ray on worker node node40 ***
redis address is: xxx.xxx.xxx.24:9999
Waiting for redis server at xxx.xxx.xxx..24:9999 to respond...
Failed to connect to the redis server, retrying.
Waiting for redis server at xxx.xxx.xxx.24:9999 to respond...
Failed to connect to the redis server, retrying.
Waiting for redis server at xxx.xxx.xxx.24:9999 to respond...
Failed to connect to the redis server, retrying.
Waiting for redis server at xxx.xxx.xxx.24:9999 to respond...
Failed to connect to the redis server, retrying.
Waiting for redis server at xxx.xxx.xxx.24:9999 to respond...
Failed to connect to the redis server, retrying.
Traceback (most recent call last):
  File "~/.conda/envs/bin/ray", line 11, in <module>
    sys.exit(main())
  File "~/.conda/envs/lib/python3.6/site-packages/ray/scripts/scripts.py", line 569, in main
    return cli()
  File "~/.conda/envs/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "~/.conda/envs/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "~/.conda/envs/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/.conda/envs/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/.conda/envs/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "~/.conda/envs/lib/python3.6/site-packages/ray/scripts/scripts.py", line 302, in start
    services.wait_for_redis_to_start(redis_ip_address, int(redis_port))
  File "~/.conda/envs/lib/python3.6/site-packages/ray/services.py", line 333, in wait_for_redis_to_start
    raise Exception("Unable to connect to Redis. If the Redis instance is "
Exception: Unable to connect to Redis. If the Redis instance is on a different machine, check that your firewall is configured properly.
```

**Comment by richardliaw** [comment]
This might be a internal/external IP address issue; though this issue is stale and should be reopened if problem persists.
