### ISSUE TITLE
[Core|RayTrain]  RuntimeError: Some workers returned results while others didn't

### ISSUE THREAD

**Issue by HuangLED** [ray-project/ray#30545]
### What happened + What you expected to happen

Expect parallel training to succeed, but constantly fail with following error. 

Error message: 
`Traceback (most recent call last):
  File "bytegnn/examples/bgtrain.py", line 471, in <module>
    trainer.run(train_func, config=train_config)
  File "/home/ruoyun.huang/anaconda3/envs/py38/lib/python3.8/site-packages/ray/train/trainer.py", line 334, in run
    for intermediate_result in iterator:
  File "/home/ruoyun.huang/anaconda3/envs/py38/lib/python3.8/site-packages/ray/train/trainer.py", line 716, in __next__
    next_results = self._run_with_error_handling(self._fetch_next_result)
  File "/home/ruoyun.huang/anaconda3/envs/py38/lib/python3.8/site-packages/ray/train/trainer.py", line 687, in _run_with_error_handling
    return func()
  File "/home/ruoyun.huang/anaconda3/envs/py38/lib/python3.8/site-packages/ray/train/trainer.py", line 742, in _fetch_next_result
    results = self._backend_executor.get_next_results()
  File "/home/ruoyun.huang/anaconda3/envs/py38/lib/python3.8/site-packages/ray/train/utils.py", line 173, in <lambda>
    return lambda *args, **kwargs: ray.get(actor_method.remote(*args, **kwargs))
  File "/home/ruoyun.huang/anaconda3/envs/py38/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ruoyun.huang/anaconda3/envs/py38/lib/python3.8/site-packages/ray/worker.py", line 1809, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::BackendExecutor.get_next_results() (pid=1368173, ip=10.231.243.221, repr=<ray.train.backend.BackendExecutor object at 0x7f7432025220>)
  File "/home/ruoyun.huang/anaconda3/envs/py38/lib/python3.8/site-packages/ray/train/backend.py", line 483, in get_next_results
    raise RuntimeError(
RuntimeError: Some workers returned results while others didn't. Make sure that `train.report()` and `train.save_checkpoint()` are called the same number of times on all workers.`

### Versions / Dependencies

ray==1.12.1

### Reproduction script

n/a

We are using RayTrain to do parallel training, then constantly run into this error once scaling up. We also observed that it is easier to trigger when there are between 10 - 19 trainers. The whole thing is more stable when there are either more than 19 or less than 10 trainers in parallel. 

I understand in more recent releases, this issue has been mitigated, though we have been using RayTrain interface and it will take time to migrate to 2.0 interface. If there is no 1.x version that gets this issue fixed, is there any work around we can take to prevent this from happening?

Thanks. 

@matt

### Issue Severity

High: It blocks me from completing my task.

**Comment by matthewdeng** [comment]
@HuangLED do you have a simple repro for this?

Off the top of my head I can think of two reasons:

1. As the message indicates, the different workers are each reading a different number of batches/epochs of data, which leads to a mismatch in the number of `train.report()` calls.
2. One or more of the workers died, which leads to these workers not calling `train.report()`.

Do either of these seem likely to be happening based on your workload?

**Comment by cszhu** [comment]
This P2 issue has seen no activity in the past 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please comment and remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
