### ISSUE TITLE
[tune] Trial executor crashes with certain stop conditions

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#3057]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem
It seems one trial finishes, but the rest fail.
### Source code / logs
```
Traceback (most recent call last):
  File "/home/eric/Desktop/ray-private/python/ray/tune/trial_runner.py", line 242, in _process_events
    if trial.should_stop(result):
  File "/home/eric/Desktop/ray-private/python/ray/tune/trial.py", line 213, in should_stop
    if result[criteria] >= stop_value:
TypeError: unorderable types: NoneType() >= int()
Worker ip unknown, skipping log sync for /home/eric/ray_results/test/IMPALA_cartpole_stateless_4_2018-10-14_00-11-54wk3lun7w
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/4 CPUs, 0/0 GPUs
Result logdir: /home/eric/ray_results/test
ERROR trials:
 - IMPALA_cartpole_stateless_1:	ERROR, 1 failures: /home/eric/ray_results/test/IMPALA_cartpole_stateless_1_2018-10-14_00-11-08bzsn9bjz/error_2018-10-14_00-11-23.txt
 - IMPALA_cartpole_stateless_2:	ERROR, 1 failures: /home/eric/ray_results/test/IMPALA_cartpole_stateless_2_2018-10-14_00-11-23zv6jbrbr/error_2018-10-14_00-11-38.txt
 - IMPALA_cartpole_stateless_3:	ERROR, 1 failures: /home/eric/ray_results/test/IMPALA_cartpole_stateless_3_2018-10-14_00-11-38p18gjmul/error_2018-10-14_00-11-54.txt
 - IMPALA_cartpole_stateless_4:	ERROR, 1 failures: /home/eric/ray_results/test/IMPALA_cartpole_stateless_4_2018-10-14_00-11-54wk3lun7w/error_2018-10-14_00-12-09.txt
TERMINATED trials:
 - IMPALA_cartpole_stateless_0:	TERMINATED [pid=19362], 173 s, 17 iter, 143900 ts, 221 rew
```

```
    tune.run_experiments({
        "test": {
            "env": "cartpole_stateless",
            "run": "IMPALA",
            "num_samples": 5,
            "stop": {
                "episode_reward_mean": args.stop,
                "timesteps_total": 200000,
            },
            "config": {
                "num_workers": 2,
                "num_gpus": 0,
                "vf_loss_coeff": 0.01,
                "model": {
                    "use_lstm": True,
                },
            },
        }
    })

```

**Comment by ericl** [comment]
@richardliaw
