### ISSUE TITLE
rock_paper_scissors_multiagent error

### ISSUE THREAD

**Issue by JackYansongLi** [ray-project/ray#30596]
### What happened + What you expected to happen

When I run the examples in: https://github.com/ray-project/ray/blob/master/rllib/examples/rock_paper_scissors_multiagent.py. I got an immediate value error.

### Versions / Dependencies

pettingzoo == 1.22.2
python == 3.8
ray == 2.1.0

### Error log

```console
Traceback (most recent call last):
  File "rock_paper_scissors_multiagent.py", line 206, in <module>
    run_heuristic_vs_learned(args, use_lstm=False)
  File "rock_paper_scissors_multiagent.py", line 130, in run_heuristic_vs_learned
    algo = cls(config=config)
  File "/home/jackyansongli/mambaforge-pypy3/envs/rllib/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 414, in __init__
    super().__init__(config=config, logger_creator=logger_creator, **kwargs)
  File "/home/jackyansongli/mambaforge-pypy3/envs/rllib/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 161, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/jackyansongli/mambaforge-pypy3/envs/rllib/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 524, in setup
    self.workers = WorkerSet(
  File "/home/jackyansongli/mambaforge-pypy3/envs/rllib/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 185, in __init__
    self._local_worker = self._make_worker(
  File "/home/jackyansongli/mambaforge-pypy3/envs/rllib/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 892, in _make_worker
    worker = cls(
  File "/home/jackyansongli/mambaforge-pypy3/envs/rllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 567, in __init__
    self.policy_dict = _determine_spaces_for_multi_agent_dict(
  File "/home/jackyansongli/mambaforge-pypy3/envs/rllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 2121, in _determine_spaces_for_multi_agent_dict
    raise ValueError(
ValueError: `observation_space` not provided in PolicySpec for always_same and env does not have an observation space OR no spaces received from other workers' env(s) OR no `observation_space` specified in config!
```

**Comment by sven1977** [comment]
Hey @JackYansongLi , thanks for posting this issue. I do see the same on my Win machine. However, there is a version conflict between your pettingzoo version (1.22.x?) and your gym/gymnasium version. The newer pettingzoo versions are using gymnasium (instead of gym), so one of the checks in RLlib fails (env.observation_space is not an inatance of gym.Space anymore, but of gymnasium.Space).

Can you try re-installing pettingzoo 1.15 as we do in our `requirements_rllib.txt`? I'm aware that there are some mismatches then when trying to use certain envs in case you use Win vs Linux, etc.. (e.g. for Win `rps_v2` does not seem to be available).

This will be fully solved once we move RLlib to gymnasium and deprecate gym support, but it's still in progress and will be available in Ray 2.3 (or master some time earlier).
