### ISSUE TITLE
[release test][jobs] jobs_specify_num_gpus is failing on release branch

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30616]
See

https://buildkite.com/ray-project/release-tests-branch/builds/1209#0184a298-d1a5-4782-a189-ad3d3bb0b911

```


Traceback (most recent call last):
--
  | File "workloads/jobs_specify_num_gpus.py", line 69, in <module>
  | entrypoint_num_gpus=num_gpus,
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/sdk.py", line 188, in submit_job
  | version_error_message="`entrypoint_num_cpus`, `entrypoint_num_gpus`, "
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 228, in _check_connection_and_version
  | self._check_connection_and_version_with_url(min_version, version_error_message)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 253, in _check_connection_and_version_with_url
  | + version_error_message
  | RuntimeError: Ray version 2.2.0rc0 is running on the cluster. `entrypoint_num_cpus`, `entrypoint_num_gpus`, and `entrypoint_resources` kwargs are not supported on the Ray cluster. Please ensure the cluster is running Ray 2.2 or higher.


```

**Comment by xwjiang2010** [comment]
cc @edoakes

**Comment by simon-mo** [comment]
looking....

**Comment by simon-mo** [comment]
The root cause is the version requirement was specified as 2.2, which is greater than 2.2.0rc0. We should specify the minimal version to 2.2.0dev0 instead for the test to pass. This shouldn't impact the final release because the actual released version will pass the version check. I'll send a PR directly to the release branch to relax the minimal requirement.

https://peps.python.org/pep-0440/#summary-of-permitted-suffixes-and-relative-ordering

```
Within a numeric release (1.0, 2.7.3), the following suffixes are permitted and MUST be ordered as shown:

.devN, aN, bN, rcN, <no suffix>, .postN
```
