### ISSUE TITLE
Issue on page /ray-air/examples/torch_image_example.html

### ISSUE THREAD

**Issue by jpgard** [ray-project/ray#30648]
The code in this tutorial doesn't run.

Unmodified, running this code leads to the following traceback:

```
---------------------------------------------------------------------------
RayTaskError(TypeError)                   Traceback (most recent call last)
Cell In [5], line 10
      2 from ray.air.config import ScalingConfig
      4 trainer = TorchTrainer(
      5     train_loop_per_worker=train_loop_per_worker,
      6     train_loop_config={"batch_size": 2},
      7     datasets={"train": train_dataset},
      8     scaling_config=ScalingConfig(num_workers=2),
      9 )
---> 10 result = trainer.fit()
     11 latest_checkpoint = result.checkpoint

File ~/venv/lib/python3.8/site-packages/ray/train/base_trainer.py:360, in BaseTrainer.fit(self)
    358     result = result_grid[0]
    359     if result.error:
--> 360         raise result.error
    361 except TuneError as e:
    362     raise TrainingFailedError from e

RayTaskError(TypeError): ray::_Inner.train() (pid=1637, ip=127.0.0.1, repr=TorchTrainer)
  File "/path/to/venv/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 355, in train
    raise skipped from exception_cause(skipped)
  File "/path/to/venv/lib/python3.8/site-packages/ray/train/_internal/utils.py", line 54, in check_for_failure
    ray.get(object_ref)
ray.exceptions.RayTaskError(TypeError): ray::RayTrainWorker._RayTrainWorker__execute() (pid=1645, ip=127.0.0.1, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x7fa43b7e17c0>)
  File "/path/to/venv/lib/python3.8/site-packages/ray/train/_internal/worker_group.py", line 31, in __execute
    raise skipped from exception_cause(skipped)
  File "/path/to/venv/lib/python3.8/site-packages/ray/train/_internal/utils.py", line 129, in discard_return_wrapper
    train_func(*args, **kwargs)
  File "/var/folders/3f/96kfmy7s1y5_5fr8cgqtfzpm0000gn/T/ipykernel_1601/1449527742.py", line 22, in train_loop_per_worker
  File "/path/to/venv/lib/python3.8/site-packages/ray/data/dataset.py", line 2531, in iter_torch_batches
    yield convert_ndarray_batch_to_torch_tensor_batch(
  File "/path/to/venv/lib/python3.8/site-packages/ray/air/_internal/torch_utils.py", line 163, in convert_ndarray_batch_to_torch_tensor_batch
    batch = convert_ndarray_to_torch_tensor(ndarrays, dtype=dtypes, device=device)
  File "/path/to/venv/lib/python3.8/site-packages/ray/air/_internal/torch_utils.py", line 135, in convert_ndarray_to_torch_tensor
    return torch.as_tensor(ndarray, dtype=dtype, device=device)
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

```

I am using the following versions:
* Python 3.8
* ray==2.1.0
* torch==1.13.0
* numpy==1.23.4

**Comment by richardliaw** [comment]
hmm which version of the docs are you looking at? is it latest or master?

**Comment by jpgard** [comment]
looks like it is latest, here: https://docs.ray.io/en/latest/ray-air/examples/torch_image_example.html

could this be an environment issue? there isn't any information about which versions to use in the docs.

**Comment by richardliaw** [comment]
Yeah, maybe.

The tests were run with this environment, if you want to be conservative: https://buildkite.com/ray-project/ray-builders-branch/builds/9730#01831585-39d5-4975-b962-94804464819f/149-1105

torch 1.9
numpy 1.19.5
pyarrow 6.0.01

That being said my personal environment is:

torch 1.12
numpy 1.19.5
pyarrow 8.0.0

and @bveeramani touched this code last and he may have a different env.

Try these out?

**Comment by jpgard** [comment]
I tried both of the configurations above with python3.8, no success. Also tried them in a clean environment with Python 3.7 (which looks to be the Python version of the testing environment), no success.

In Python3.7, it raises the following stack trace:

```
---------------------------------------------------------------------------
RayTaskError(ValueError)                  Traceback (most recent call last)
/var/folders/3f/96kfmy7s1y5_5fr8cgqtfzpm0000gn/T/ipykernel_1816/4251098542.py in <module>
      8     scaling_config=ScalingConfig(num_workers=2),
      9 )
---> 10 result = trainer.fit()
     11 latest_checkpoint = result.checkpoint

~/path/to/venv3.7/lib/python3.7/site-packages/ray/train/base_trainer.py in fit(self)
    358             result = result_grid[0]
    359             if result.error:
--> 360                 raise result.error
    361         except TuneError as e:
    362             raise TrainingFailedError from e

RayTaskError(ValueError): ray::_Inner.train() (pid=1855, ip=127.0.0.1, repr=TorchTrainer)
  File "/path/to/venv3.7/lib/python3.7/site-packages/ray/tune/trainable/trainable.py", line 355, in train
    raise skipped from exception_cause(skipped)
  File "/path/to/venv3.7/lib/python3.7/site-packages/ray/train/_internal/utils.py", line 54, in check_for_failure
    ray.get(object_ref)
ray.exceptions.RayTaskError(ValueError): ray::RayTrainWorker._RayTrainWorker__execute() (pid=1868, ip=127.0.0.1, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x7feebb7af610>)
  File "/path/to/venv3.7/lib/python3.7/site-packages/ray/train/_internal/worker_group.py", line 31, in __execute
    raise skipped from exception_cause(skipped)
  File "/path/to/venv3.7/lib/python3.7/site-packages/ray/train/_internal/utils.py", line 129, in discard_return_wrapper
    train_func(*args, **kwargs)
  File "/var/folders/3f/96kfmy7s1y5_5fr8cgqtfzpm0000gn/T/ipykernel_1816/1449527742.py", line 22, in train_loop_per_worker
  File "/path/to/venv3.7/lib/python3.7/site-packages/ray/data/dataset.py", line 2529, in iter_torch_batches
    local_shuffle_seed=local_shuffle_seed,
  File "/path/to/venv3.7/lib/python3.7/site-packages/ray/data/dataset.py", line 2458, in iter_batches
    shuffle_seed=local_shuffle_seed,
  File "/path/to/venv3.7/lib/python3.7/site-packages/ray/data/_internal/block_batching.py", line 129, in batch_blocks
    yield from get_batches(block_window[0])
  File "/path/to/venv3.7/lib/python3.7/site-packages/ray/data/_internal/block_batching.py", line 99, in get_batches
    result = _format_batch(batch, batch_format)
  File "/path/to/venv3.7/lib/python3.7/site-packages/ray/data/_internal/block_batching.py", line 147, in _format_batch
    batch = BlockAccessor.for_block(batch).to_numpy()
  File "/path/to/venv3.7/lib/python3.7/site-packages/ray/data/_internal/simple_block.py", line 102, in to_numpy
    return np.array(self._items)
ValueError: only one element tensors can be converted to Python scalars
```
I still don't know if this is a bug, or an issue with the environment, since there isn't any information in the tutorial about the environment setup besides requiring ray 2.0.

Does the code for that tutorial actually run to completion in your environment (or anyone else's)? Can you provide some more detail on how I can create a working environment to just run the example code in the tutorial? 

Happy to also try and debug this and submit a PR if you can provide some guidance on where changes are needed, once I can get things working.....

**Comment by richardliaw** [comment]
Not sure if related but can you try using conda...? I think i've seen weird behavior with standard venv before

**Comment by richardliaw** [comment]
```

Result for TorchTrainer_dc315_00000:
  _time_this_iter_s: 53.874094009399414
  _timestamp: 1669353744
  _training_iteration: 2
  date: 2022-11-24_21-22-24
  done: true
  experiment_id: d7e1a497b6974ad692ff250d6735779c
  experiment_tag: '0'
  hostname: Richards-MBP.attlocal.net
  iterations_since_restore: 2
  node_ip: 127.0.0.1
  pid: 89359
  running_loss: 591.9546077598352
  should_checkpoint: true
  time_since_restore: 118.86062622070312
  time_this_iter_s: 53.872299909591675
  time_total_s: 118.86062622070312
  timestamp: 1669353744
  timesteps_since_restore: 0
  training_iteration: 2
  trial_id: dc315_00000
  warmup_time: 0.1104578971862793

== Status ==
Current time: 2022-11-24 21:22:26 (running for 00:02:03.57)
Memory usage on this node: 36.0/64.0 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/16 CPUs, 0/0 GPUs, 0.0/25.56 GiB heap, 0.0/2.0 GiB objects
Result logdir: /Users/rliaw/ray_results/TorchTrainer_2022-11-24_21-20-22
Number of trials: 1/1 (1 TERMINATED)
+--------------------------+------------+-----------------+--------+------------------+----------------+--------------+---------------------+
| Trial name               | status     | loc             |   iter |   total time (s) |   running_loss |   _timestamp |   _time_this_iter_s |
|--------------------------+------------+-----------------+--------+------------------+----------------+--------------+---------------------|
| TorchTrainer_dc315_00000 | TERMINATED | 127.0.0.1:89359 |      2 |          118.861 |        591.955 |   1669353744 |             53.8741 |
+--------------------------+------------+-----------------+--------+------------------+----------------+--------------+---------------------+


2022-11-24 21:22:26,193	INFO tune.py:778 -- Total run time: 123.78 seconds (123.57 seconds for the tuning loop).
```

I just tried it on my local laptop and it ran fine for me (pip installed Ray from scratch)

**Comment by jpgard** [comment]
I tried using conda, it also doesn't work. Below is the environment.yml I am using.

It would be really helpful if someone could provide the configuration for a working environment that can actually run this example, otherwise I'm stuck shooting in the dark. I am really excited to try Ray, but this is the most painful setup process I've ever experienced with a Python library.

`environment.yml:`
```
name: myenv
channels:
  - defaults
dependencies:
  - python=3.8
  - lightgbm 
  - xgboost
  - scikit-learn
  - cudatoolkit 
  - pytorch
  - torchvision
  - pandas
  - pip
  - pip:
    - ray[air]
    - ray[data]
    - ray[tune]
    - frozendict
    - xport
    - -e .


```

running the tutorial code with this environment gives

```
OMP: Error #15: Initializing libiomp5.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
Abort trap: 6
```

it looks like installing `nomkl` might help with that, but (a) it's incompatible with the other packages and (b) that seems like a hack that shouldn't be necessary.

Thanks for your help on this....

**Comment by jpgard** [comment]
I also tried running the code in a clean python3.8 venv with ONLY ray[data], ray[air], torch, torchvision, and some possibly missing required dependencies (`packaging`, `tabulate`), and this raised the same original error as above (`TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.`). 

FWIW, the output of `pip freeze` for that environment is below.

`pip freeze:`
```
aiohttp==3.8.3
aiohttp-cors==0.7.0
aiorwlock==1.3.0
aiosignal==1.3.1
anyio==3.6.2
async-timeout==4.0.2
attrs==22.1.0
blessed==1.19.1
cachetools==5.2.0
certifi==2022.9.24
charset-normalizer==2.1.1
click==8.0.4
colorful==0.5.4
distlib==0.3.6
fastapi==0.87.0
filelock==3.8.0
frozenlist==1.3.3
fsspec==2022.11.0
google-api-core==2.10.2
google-auth==2.14.1
googleapis-common-protos==1.57.0
gpustat==1.0.0
grpcio==1.50.0
h11==0.14.0
idna==3.4
importlib-resources==5.10.0
jsonschema==4.17.1
msgpack==1.0.4
multidict==6.0.2
numpy==1.23.5
nvidia-ml-py==11.495.46
opencensus==0.11.0
opencensus-context==0.1.3
packaging==21.3
pandas==1.5.2
Pillow==9.3.0
pkgutil-resolve-name==1.3.10
platformdirs==2.5.4
prometheus-client==0.13.1
protobuf==3.19.6
psutil==5.9.4
py-spy==0.3.14
pyarrow==6.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydantic==1.10.2
pyparsing==3.0.9
pyrsistent==0.19.2
python-dateutil==2.8.2
pytz==2022.6
PyYAML==6.0
ray==2.1.0
requests==2.28.1
rsa==4.9
six==1.16.0
smart-open==6.2.0
sniffio==1.3.0
starlette==0.21.0
tabulate==0.9.0
tensorboardX==2.5.1
torch==1.13.0
torchvision==0.14.0
typing-extensions==4.4.0
urllib3==1.26.13
uvicorn==0.20.0
virtualenv==20.16.7
wcwidth==0.2.5
yarl==1.8.1
zipp==3.10.0
```

**Comment by jpgard** [comment]
I tried doing the same as above but with conda (create a clean python 3.8 environment, pip install only `ray[tune] ray[air] torch torchvision packaging tabulate`, and it raises the OMP error described in a previous post.

Together, the experiments with clean venv and clean conda environment seem to suggest that this isn't just a local issue or a problem with the other packages I was trying to install, but a problem internal to ray and how its dependencies are configured...any ideas here? Genuinely stumped by this.

**Comment by richardliaw** [comment]
Tried a fresh conda environment and ran the notebook fine using that environment. Commands I ran:

```
  10189  conda create -n raytest python=3.8
  10190  conda activate raytest
  10191  pip install -U 'ray[air]' torch torchvision
  10192  pip install ipython # not needed
  10193  ipython # not needed
  10194  weget https://raw.githubusercontent.com/ray-project/ray/releases/2.1.0/doc/source/ray-air/examples/torch_image_example.ipynb . # typo
  10195  wget https://raw.githubusercontent.com/ray-project/ray/releases/2.1.0/doc/source/ray-air/examples/torch_image_example.ipynb .
  10196  ls # typo
  10197  jupyterlab  # typo
  10198  jupyter # typo
  10199  pip install jupyterlab
  10200  jupyter lab  # ran the notebook  here 
  10201  conda freeze # typo
  10202  conda # typo
  10203  conda list
> 10204  pip freeze
```

my pip freeze:
```
aiohttp==3.8.3
aiohttp-cors==0.7.0
aiorwlock==1.3.0
aiosignal==1.3.1
anyio==3.6.2
appnope==0.1.3
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.1.0
async-timeout==4.0.2
attrs==22.1.0
Babel==2.11.0
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.1
blessed==1.19.1
cachetools==5.2.0
certifi @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_0ek9yztvu3/croot/certifi_1665076692562/work/certifi
cffi==1.15.1
charset-normalizer==2.1.1
click==8.0.4
colorful==0.5.4
debugpy==1.6.3
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.6
entrypoints==0.4
executing==1.2.0
fastapi==0.87.0
fastjsonschema==2.16.2
filelock==3.8.0
frozenlist==1.3.3
fsspec==2022.11.0
google-api-core==2.10.2
google-auth==2.14.1
googleapis-common-protos==1.57.0
gpustat==1.0.0
grpcio==1.50.0
h11==0.14.0
idna==3.4
importlib-metadata==5.1.0
importlib-resources==5.10.0
ipykernel==6.17.1
ipython==8.6.0
ipython-genutils==0.2.0
jedi==0.18.2
Jinja2==3.1.2
json5==0.9.10
jsonschema==4.17.1
jupyter-server==1.23.3
jupyter_client==7.4.7
jupyter_core==5.0.0
jupyterlab==3.5.0
jupyterlab-pygments==0.2.2
jupyterlab_server==2.16.3
MarkupSafe==2.1.1
matplotlib-inline==0.1.6
mistune==2.0.4
msgpack==1.0.4
multidict==6.0.2
nbclassic==0.4.8
nbclient==0.7.0
nbconvert==7.2.5
nbformat==5.7.0
nest-asyncio==1.5.6
notebook==6.5.2
notebook_shim==0.2.2
numpy==1.23.5
nvidia-ml-py==11.495.46
opencensus==0.11.0
opencensus-context==0.1.3
packaging==21.3
pandas==1.5.2
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.3.0
pkgutil_resolve_name==1.3.10
platformdirs==2.5.4
prometheus-client==0.13.1
prompt-toolkit==3.0.33
protobuf==3.19.6
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
py-spy==0.3.14
pyarrow==6.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pydantic==1.10.2
Pygments==2.13.0
pyparsing==3.0.9
pyrsistent==0.19.2
python-dateutil==2.8.2
pytz==2022.6
PyYAML==6.0
pyzmq==24.0.1
ray==2.1.0
requests==2.28.1
rsa==4.9
Send2Trash==1.8.0
six==1.16.0
smart-open==6.2.0
sniffio==1.3.0
soupsieve==2.3.2.post1
stack-data==0.6.1
starlette==0.21.0
tabulate==0.9.0
tensorboardX==2.5.1
terminado==0.17.0
tinycss2==1.2.1
tomli==2.0.1
torch==1.13.0
torchvision==0.14.0
tornado==6.2
traitlets==5.5.0
typing_extensions==4.4.0
urllib3==1.26.13
uvicorn==0.20.0
virtualenv==20.16.7
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.4.2
yarl==1.8.1
zipp==3.11.0
```

conda list:
```
# packages in environment at /Users/rliaw/miniconda3/envs/raytest:
#
# Name                    Version                   Build  Channel
aiohttp                   3.8.3                    pypi_0    pypi
aiohttp-cors              0.7.0                    pypi_0    pypi
aiorwlock                 1.3.0                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
appnope                   0.1.3                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
asttokens                 2.1.0                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
babel                     2.11.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
bleach                    5.0.1                    pypi_0    pypi
blessed                   1.19.1                   pypi_0    pypi
ca-certificates           2022.10.11           hecd8cb5_0
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.9.24        py38hecd8cb5_0
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.0.4                    pypi_0    pypi
colorful                  0.5.4                    pypi_0    pypi
debugpy                   1.6.3                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
distlib                   0.3.6                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
fastapi                   0.87.0                   pypi_0    pypi
fastjsonschema            2.16.2                   pypi_0    pypi
filelock                  3.8.0                    pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2022.11.0                pypi_0    pypi
google-api-core           2.10.2                   pypi_0    pypi
google-auth               2.14.1                   pypi_0    pypi
googleapis-common-protos  1.57.0                   pypi_0    pypi
gpustat                   1.0.0                    pypi_0    pypi
grpcio                    1.50.0                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        5.1.0                    pypi_0    pypi
importlib-resources       5.10.0                   pypi_0    pypi
ipykernel                 6.17.1                   pypi_0    pypi
ipython                   8.6.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
json5                     0.9.10                   pypi_0    pypi
jsonschema                4.17.1                   pypi_0    pypi
jupyter-client            7.4.7                    pypi_0    pypi
jupyter-core              5.0.0                    pypi_0    pypi
jupyter-server            1.23.3                   pypi_0    pypi
jupyterlab                3.5.0                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.16.3                   pypi_0    pypi
libcxx                    14.0.6               h9765a3e_0
libffi                    3.4.2                hecd8cb5_6
markupsafe                2.1.1                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   2.0.4                    pypi_0    pypi
msgpack                   1.0.4                    pypi_0    pypi
multidict                 6.0.2                    pypi_0    pypi
nbclassic                 0.4.8                    pypi_0    pypi
nbclient                  0.7.0                    pypi_0    pypi
nbconvert                 7.2.5                    pypi_0    pypi
nbformat                  5.7.0                    pypi_0    pypi
ncurses                   6.3                  hca72f7f_3
nest-asyncio              1.5.6                    pypi_0    pypi
notebook                  6.5.2                    pypi_0    pypi
notebook-shim             0.2.2                    pypi_0    pypi
numpy                     1.23.5                   pypi_0    pypi
nvidia-ml-py              11.495.46                pypi_0    pypi
opencensus                0.11.0                   pypi_0    pypi
opencensus-context        0.1.3                    pypi_0    pypi
openssl                   1.1.1s               hca72f7f_0
packaging                 21.3                     pypi_0    pypi
pandas                    1.5.2                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.3.0                    pypi_0    pypi
pip                       22.2.2           py38hecd8cb5_0
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              2.5.4                    pypi_0    pypi
prometheus-client         0.13.1                   pypi_0    pypi
prompt-toolkit            3.0.33                   pypi_0    pypi
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
py-spy                    0.3.14                   pypi_0    pypi
pyarrow                   6.0.1                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pydantic                  1.10.2                   pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.19.2                   pypi_0    pypi
python                    3.8.15               h218abb5_2
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2022.6                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     24.0.1                   pypi_0    pypi
ray                       2.1.0                    pypi_0    pypi
readline                  8.2                  hca72f7f_0
requests                  2.28.1                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                65.5.0           py38hecd8cb5_0
six                       1.16.0                   pypi_0    pypi
smart-open                6.2.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlite                    3.40.0               h880c91c_0
stack-data                0.6.1                    pypi_0    pypi
starlette                 0.21.0                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tensorboardx              2.5.1                    pypi_0    pypi
terminado                 0.17.0                   pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h5d9f67b_0
tomli                     2.0.1                    pypi_0    pypi
torch                     1.13.0                   pypi_0    pypi
torchvision               0.14.0                   pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
traitlets                 5.5.0                    pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
urllib3                   1.26.13                  pypi_0    pypi
uvicorn                   0.20.0                   pypi_0    pypi
virtualenv                20.16.7                  pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.4.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
xz                        5.2.6                hca72f7f_0
yarl                      1.8.1                    pypi_0    pypi
zipp                      3.11.0                   pypi_0    pypi
zlib                      1.2.13               h4dc903c_0
```

**Comment by richardliaw** [comment]
Also on py3.8, using a macos 10.15

**Comment by jpgard** [comment]
It works!!! thank you for sticking with this issue.

I don't know what the root cause was here, but it seems like there is an extremely fragile set of dependencies at play here that I don't have the time or inclination to look into much further; will add to this thread later if I can identify the exact culprit. 

If I can give back with a PR to resolve this in the future let me know :). 

Closing the issue.
