### ISSUE TITLE
[RLlib] Default policy error in two trainer work flow

### ISSUE THREAD

**Issue by JackYansongLi** [ray-project/ray#30676]
### What happened + What you expected to happen

I am trying to replicate the example introduced in _https://github.com/ray-project/ray/blob/master/rllib/examples/multi_agent_two_trainers.py_ by replacing the DQN policy by MARWIL policy. However, we met the following issue,
```console
Traceback (most recent call last):
  File "/home/jackyansongli/mambaforge-pypy3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/rllib/offline/json_reader.py", line 358, in _try_parse
    batch = self._from_json(line)
  File "/home/jackyansongli/mambaforge-pypy3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/rllib/offline/json_reader.py", line 404, in _from_json
    return from_json_data(json_data, self.ioctx.worker)
  File "/home/jackyansongli/mambaforge-pypy3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/rllib/offline/json_reader.py", line 168, in from_json_data
    raise ValueError(
ValueError: Found single-agent SampleBatch in input file, but our PolicyMap contains more than 1 policy!
Traceback (most recent call last):
  File "/home/jackyansongli/ray/multi_agents_ppo_marwil.py", line 171, in <module>
    result_marwil = marwil.train()
  File "/home/jackyansongli/mambaforge-pypy3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 355, in train
    raise skipped from exception_cause(skipped)
  File "/home/jackyansongli/mambaforge-pypy3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 352, in train
    result = self.step()
  File "/home/jackyansongli/mambaforge-pypy3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 772, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "/home/jackyansongli/mambaforge-pypy3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 2953, in _run_one_training_iteration
    num_recreated += self.try_recover_from_step_attempt(
  File "/home/jackyansongli/mambaforge-pypy3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 2622, in try_recover_from_step_attempt
    raise error
  File "/home/jackyansongli/mambaforge-pypy3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 2948, in _run_one_training_iteration
    results = self.training_step()
  File "/home/jackyansongli/mambaforge-pypy3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/rllib/algorithms/marwil/marwil.py", line 244, in training_step
    train_batch = synchronous_parallel_sample(worker_set=self.workers)
  File "/home/jackyansongli/mambaforge-pypy3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/rllib/execution/rollout_ops.py", line 97, in synchronous_parallel_sample
    sample_batches = [worker_set.local_worker().sample()]
  File "/home/jackyansongli/mambaforge-pypy3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 828, in sample
    batches = [self.input_reader.next()]
  File "/home/jackyansongli/mambaforge-pypy3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/rllib/offline/shuffled_input.py", line 34, in next
    return self.child.next()
  File "/home/jackyansongli/mambaforge-pypy3/envs/pettingzoo_rllib/lib/python3.8/site-packages/ray/rllib/offline/json_reader.py", line 275, in next
    raise ValueError(
ValueError: Failed to read valid experience batch from file: <_io.TextIOWrapper name='./rllib/tests/data/cartpole/large.json' mode='r' encoding='UTF-8'>
```

### Versions / Dependencies

Ray==2.1.0
Python==3.8

### Reproduction script

```python
import argparse
import gym
import os

import ray
from ray.rllib.algorithms.marwil import (
    MARWIL,
    MARWILConfig,
    MARWILTF1Policy
)
from ray.rllib.algorithms.marwil.marwil_tf_policy import MARWILTF2Policy
from ray.rllib.algorithms.marwil.marwil_torch_policy import MARWILTorchPolicy
from ray.rllib.algorithms.ppo import (
    PPOConfig,
    PPOTF1Policy,
    PPOTF2Policy,
    PPOTorchPolicy,
)
from ray.rllib.examples.env.multi_agent import MultiAgentCartPole
from ray.tune.logger import pretty_print
from ray.tune.registry import register_env

parser = argparse.ArgumentParser()
# Use torch for both policies.
parser.add_argument(
    "--framework",
    choices=["tf", "tf2", "torch"],
    default="torch",
    help="The DL framework specifier.",
)
parser.add_argument(
    "--as-test",
    action="store_true",
    help="Whether this script should be run as a test: --stop-reward must "
    "be achieved within --stop-timesteps AND --stop-iters.",
)
parser.add_argument(
    "--stop-iters", type=int, default=20, help="Number of iterations to train."
)
parser.add_argument(
    "--stop-timesteps", type=int, default=100000, help="Number of timesteps to train."
)
parser.add_argument(
    "--stop-reward", type=float, default=50.0, help="Reward at which we stop training."
)

if __name__ == "__main__":
    args = parser.parse_args()

    ray.init()

    # Simple environment with 4 independent cartpole entities
    register_env(
        "multi_agent_cartpole", lambda _: MultiAgentCartPole({"num_agents": 4})
    )
    single_dummy_env = gym.make("CartPole-v1")
    obs_space = single_dummy_env.observation_space
    act_space = single_dummy_env.action_space

    def seelct_policy(algorithm, framework):
        if algorithm == "PPO":
            if framework == "torch":
                return PPOTorchPolicy
            elif framework == "tf":
                return PPOTF1Policy
            else:
                return PPOTF2Policy
        elif algorithm == "MARWIL":
            if framework == "torch":
                return MARWILTorchPolicy
            elif framework == "tf":
                return MARWILTF1Policy
            else:
                return MARWILTF2Policy
        else:
            raise ValueError("Unknown algorithm: ", algorithm)

    # You can also have multiple policies per algorithm, but here we just
    # show one each for PPO and MARWIL.
    policies = {
        "ppo_policy": (
            seelct_policy("PPO", args.framework),
            obs_space,
            act_space,
            {},
        ),
        "marwil_policy": (
            seelct_policy("MARWIL", args.framework),
            obs_space,
            act_space,
            {},
        ),
    }

    def policy_mapping_fn(agent_id, episode, worker, **kwargs):
        if agent_id % 2 == 0:
            return "ppo_policy"
        else:
            return "marwil_policy"

    ppo_config = (
        PPOConfig()
        .environment("multi_agent_cartpole")
        .framework(args.framework)
        # disable filters, otherwise we would need to synchronize those
        # as well to the MARWIL agent
        .rollouts(observation_filter="MeanStdFilter")
        .training(
            model={"vf_share_layers": True},
            vf_loss_coeff=0.01,
            num_sgd_iter=6,
        )
        .multi_agent(
            policies=policies,
            policy_mapping_fn=policy_mapping_fn,
            policies_to_train=["ppo_policy"],
        )
        # Use GPUs iff `RLLIB_NUM_GPUS` env var set to > 0.
        .resources(num_gpus=int(os.environ.get("RLLIB_NUM_GPUS", "0")))
    )
    ppo = ppo_config.build()

    marwil_config = (
        MARWILConfig()
        .environment("multi_agent_cartpole")
        .framework(args.framework)
        # disable filters, otherwise we would need to synchronize those
        # as well to the MARWIL agent
        .rollouts(observation_filter="MeanStdFilter")
        .training(
            model={"vf_share_layers": True},
            beta=1.0,
            lr=0.00001,
            gamma=0.99
            #vf_loss_coeff=0.01,
            #num_sgd_iter=6,
        )
        .offline_data(
            input_=["./rllib/tests/data/cartpole/large.json"]
        )
        .multi_agent(
            policies=policies,
            policy_mapping_fn=policy_mapping_fn,
            policies_to_train=["marwil_policy"],
        )
        # Use GPUs iff `RLLIB_NUM_GPUS` env var set to > 0.
        .resources(num_gpus=int(os.environ.get("RLLIB_NUM_GPUS", "0")))
    )
    marwil = marwil_config.build()
    for i in range(args.stop_iters):
        print("== Iteration", i, "==")

        # improve the Marwil policy
        print("-- MARWIL --")
        result_marwil = marwil.train()
        print(pretty_print(result_marwil))

        # improve the PPO policy
        print("-- PPO --")
        result_ppo = ppo.train()
        print(pretty_print(result_ppo))

        # Test passed gracefully.
        if (
            args.as_test
            and result_marwil["episode_reward_mean"] > args.stop_reward
            and result_ppo["episode_reward_mean"] > args.stop_reward
        ):
            print("test passed (both agents above requested reward)")
            quit(0)

        # swap weights to synchronize
        marwil.set_weights(ppo.get_weights(["ppo_policy"]))
        ppo.set_weights(marwil.get_weights(["marwil_policy"]))

    # Desired reward not reached.
    if args.as_test:
        raise ValueError("Desired reward ({}) not reached!".format(args.stop_reward))
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
@JackYansongLi This is failing because your input is derived from a single-agent case, but you are using it in a multi agent setting. We are not verbose enough about this. I'll craft something that gets rid of the underlying issue though. Thanks for posting this.

**Comment by cszhu** [comment]
This P2 issue has seen no activity in the past 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please comment and remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
