### ISSUE TITLE
[Rllib] Error in running cartpole-marwil.yaml

### ISSUE THREAD

**Issue by yingyaozhou** [ray-project/ray#30725]
### What happened + What you expected to happen

I am trying to run the cartpole-marwil.yaml in https://github.com/ray-project/ray/blob/master/rllib/tuned_examples/marwil/cartpole-marwil.yaml.

I first run the following code to generate data.
```python
python train.py --run=PPO --env=CartPole-v1 --stop='{"timesteps_total": 50000}' --config='{"output": "/tmp/out", "batch_mode": "complete_episodes"}'
```

Then I run the code:
```python
rllib train -f cartpole-marwil.yaml
```

However, I met the following issue.
```console
Traceback (most recent call last):
  File "/home/yingyao/anaconda3/envs/rllib/bin/rllib", line 8, in <module>
    sys.exit(cli())
  File "/home/yingyao/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/scripts.py", line 41, in cli
    train.run(options, train_parser)
  File "/home/yingyao/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/train.py", line 271, in run
    run_experiments(
  File "/home/yingyao/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/tune/tune.py", line 867, in run_experiments
    return run(
  File "/home/yingyao/anaconda3/envs/rllib/lib/python3.8/site-packages/ray/tune/tune.py", line 771, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [MARWIL_CartPole-v1_35004_00000])
```

Could you please help me with this problem? 
Thank you so much.

### Versions / Dependencies

Ray==2.1.0
Python==3.8

### Reproduction script

```Python
# To generate training data, first run:
# $ ./train.py --run=PPO --env=CartPole-v1 \
#      --stop='{"timesteps_total": 50000}' \
#      --config='{"output": "/tmp/out", "batch_mode": "complete_episodes"}'
cartpole-marwil:
    env: CartPole-v1
    run: MARWIL
    stop:
        timesteps_total: 500000
    config:
        # Works for both torch and tf.
        framework: torch
        # In order to evaluate on an actual environment, use these following
        # settings:
        evaluation_num_workers: 1
        evaluation_interval: 1
        evaluation_config:
            input: sampler
        beta: 1.0  # Compare to behavior cloning (beta=0.0).
        # The historic (offline) data file from the PPO run (at the top).
        input: /home/yingyao/ray/zyy
```

**Comment by ArturNiederfahrenhorst** [comment]
Hi @yingyaozhou , Thanks for opening this issue! 

The error you posted is not the actual error itself, but additional information from Tune. Check your output for more information and post it here.
I tried to run this and it is running fine on master.
If you are on master, you can run it with `rllib train file rllib/tuned_examples/marwil/cartpole-marwil.yaml`. Feel free to reopen this issue if this problem is not solved by resolving the actual error that tune should output or by running on nightlies!

**Comment by yingyaozhou** [comment]
Thank you so much. It works when running on nightlies!
