### ISSUE TITLE
[Tune] key error:"training_iteration" when first iteration finished

### ISSUE THREAD

**Issue by luffy2389** [ray-project/ray#30786]
`###` When I want use hyperopt to tune a model, it shows a bug name keyError: in ray2.1.0
```
Traceback (most recent call last):
  File "anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/tune/execution/trial_runner.py", line 853, in _wait_and_handle_event
    self._on_training_result(
  File "anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/tune/execution/trial_runner.py", line 978, in _on_training_result
    self._process_trial_results(trial, result)
  File "anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/tune/execution/trial_runner.py", line 1061, in _process_trial_results
    decision = self._process_trial_result(trial, result)
  File "anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/tune/execution/trial_runner.py", line 1116, in _process_trial_result
    self._callbacks.on_trial_result(
  File "anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/tune/callback.py", line 329, in on_trial_result
    callback.on_trial_result(**info)
  File "anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/tune/logger/logger.py", line 130, in on_trial_result
    self.log_trial_result(iteration, trial, result)
  File "anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/tune/logger/tensorboardx.py", line 188, in log_trial_result
    step = result.get(TIMESTEPS_TOTAL) or result[TRAINING_ITERATION]
KeyError: 'training_iteration'
During handling of the above exception, another exception occurred:
```

### Versions / Dependencies

```
protobuf                 3.19.0

ray                      2.1.0

scikit-learn             0.24.0

tensorboardX             2.1
```

### Reproduction script
```
import ray.tune as tune
class RayTrainer(ray.tune.Trainable):
    def setup(self, config):

        # one iteration is five training epochs, one test epoch
        self.epochs = RAY_TEST_EVERY

        print(config)

        args = Namespace(**config)
        self.traindataloader, self.validdataloader = prepare_dataset(args)

        args.nclasses = self.traindataloader.dataset.nclasses

        args.seqlength = self.traindataloader.dataset.sequencelength

        args.input_dims = self.traindataloader.dataset.ndims
        self.model = getModel(args)

        if torch.cuda.is_available():
            self.model = self.model.cuda()

        if "model" in config.keys():
            config.pop('model', None)
        #trainer = Trainer(self.model, self.traindataloader, self.validdataloader, **config)
        self.trainer = Trainer(self.model, self.traindataloader, self.validdataloader, optimizer=optimizer, **config)

    def train(self):
        # epoch is used to distinguish training phases. epoch=None will default to (first) cross entropy phase

        # train five epochs and then infer once. to avoid overhead on these small datasets
        for i in range(self.epochs):
            trainstats = self.trainer.train_epoch(epoch=None)

        stats = self.trainer.test_epoch(self.validdataloader, epoch=None)
        stats.pop("inputs")
        stats.pop("ids")
        stats.pop("confusion_matrix")
        stats.pop("probas")

        stats["lossdelta"] = trainstats["loss"] - stats["loss"]
        stats["trainloss"] = trainstats["loss"]

        return stats

    def save(self, path):
        path = path + ".pth"
        torch.save(self.model.state_dict(), path)
        return path

    def restore(self, path):
        state_dict = torch.load(path, map_location="cpu")
        self.model.load_state_dict(state_dict)

def main():
    args = parse_args()

    try:
        # nruns = ray.tune.Analysis(os.path.join(args.local_dir, args.experiment)).dataframe().shape[0]
        nruns =1
        resume=False
        todo_runs = RAY_NUM_SAMPLES - nruns
        print(f"{nruns} found in {os.path.join(args.local_dir, args.experiment)} starting remaining {todo_runs}")
        if todo_runs <= 0:
            print(f"finished all {RAY_NUM_SAMPLES} runs. Increase TUNE_RUNS in databases.py if necessary. skipping tuning")
            return

    except ValueError as e:
        print(f"could not find any runs in {os.path.join(args.local_dir, args.experiment)}")
        resume=False
        todo_runs = RAY_NUM_SAMPLES

    if args.redis_address is not None:
        ray.init(redis_address=args.redis_address)
    elif not ray.is_initialized():
        ray.init()
        # include_webui = False

    config, points_to_evaluate = get_hyperparameter_search_space(args.experiment, args)

    args_dict = vars(args)
    config = {**config, **args_dict}
    args = Namespace(**config)

    algo = HyperOptSearch(
         config,

         metric="kappa",
         mode="max",
         points_to_evaluate=points_to_evaluate,
         n_initial_points=args.max_concurrent
     )


    scheduler = AsyncHyperBandScheduler(metric="kappa", mode="max",max_t=RAY_EPOCHS//RAY_TEST_EVERY,
        grace_period=HYPERBAND_GRACE_PERIOD,
        reduction_factor=HYPERBAND_REDUCTION_FACTOR,
        brackets=HYPERBAND_BRACKETS)


    analysis = tune.run(
        RayTrainer,
        config=config,
        name=args.experiment,
        num_samples=todo_runs,
        local_dir=args.local_dir,
        search_alg=algo,
        scheduler=scheduler,
        verbose=True,
        reuse_actors=False,
        resume=resume,
        checkpoint_at_end=True,
        checkpoint_score_attr="kappa")
```

**Comment by Yard1** [comment]
Hey @luffy2389, The `train` method should not be overriden as it contains important internal code, that, among many other things, sets the `TRAINING_ITERATION`.

Instead, you should override the `step` method (each time it returns, one iteration of training is registered, and it will be called until the stopping condition is met or `"done": True` is present in the returned dict). Furthermore, instead of overriding `save` and `load`, you should override `save_checkpoint` and `load_checkpoint`.

For more information, please refer to https://docs.ray.io/en/latest/tune/api_docs/trainable.html#trainable-class-api.

**Comment by luffy2389** [comment]
Thank you very much, because I was using RAY 1.1.0 before. It was a bit hard to adapt to 2.1.0.
Another problem, I was used in 1.1.0
`nruns = ray.tune.Analysis(os.path.join(args.local_dir, args.experiment)).dataframe().shape[0]`
Now what should I use to analyze all the experiments, you can refer to my original code


> Hey @luffy2389, The `train` method should not be overriden as it contains important internal code, that, among many other things, sets the `TRAINING_ITERATION`.
> 
> Instead, you should override the `step` method (each time it returns, one iteration of training is registered, and it will be called until the stopping condition is met or `"done": True` is present in the returned dict). Furthermore, instead of overriding `save` and `load`, you should override `save_checkpoint` and `load_checkpoint`.
> 
> For more information, please refer to https://docs.ray.io/en/latest/tune/api_docs/trainable.html#trainable-class-api.

**Comment by Yard1** [comment]
You should be able to access the same methods on the `ExperimentAnalysis` object returned by `tune.run`.

**Comment by luffy2389** [comment]
Many thanks
