### ISSUE TITLE
[AIR] `fail_fast="raise"` fails during validation

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#30813]
### What happened + What you expected to happen

```python
from ray import tune
from ray.tune import Tuner
from ray.air.config import RunConfig, FailureConfig


def train_fn(config):
    pass
    
failure_config = FailureConfig(fail_fast="raise")

tuner = Tuner(train_fn, run_config=RunConfig(failure_config=failure_config))
tuner.fit()
```

I expect `fail_fast="raise"` to work (as mentioned in the documentation). Yet it fails with an unhelpful error message

```
Traceback (most recent call last):
  File "tune_test.py", line 9, in <module>
    failure_config = FailureConfig(fail_fast="raise")
  File "<string>", line 5, in __init__
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/air/config.py", line 481, in __post_init__
    raise ValueError(
ValueError: fail_fast must be one of {bool, 'raise'}. Got raise.
```

### Versions / Dependencies

master

### Reproduction script

see above

### Issue Severity

High: It blocks me from completing my task.

**Comment by amogkam** [comment]
Even after fixing this validation error, it still does not work as intended:

In `Tuner` we are always raising `TuneError`, and never the actual exception from the Trainable.

```
def test_tuner_fail_fast_true(self):
        trainer = FailingTrainer()
        param_space = {
            "scaling_config": ScalingConfig(num_workers=tune.grid_search([1, 2]))
        }

        failure_config = FailureConfig(fail_fast=True)

        tuner = Tuner(
            trainable=trainer,
            run_config=RunConfig(
                name="test_tuner_trainer_fail", failure_config=failure_config
            ),
            param_space=param_space,
            tune_config=TuneConfig(mode="max", metric="iteration"),
        )
        with self.assertRaises(TuneError):
            results = tuner.fit()
            errors = [result.error for result in results if result.error]
            assert len(errors) == 1

    def test_tuner_fail_fast_raise(self):
        trainer = FailingTrainer()
        param_space = {
            "scaling_config": ScalingConfig(num_workers=tune.grid_search([1, 2]))
        }

        failure_config = FailureConfig(fail_fast="raise")

        tuner = Tuner(
            trainable=trainer,
            run_config=RunConfig(
                name="test_tuner_trainer_fail", failure_config=failure_config
            ),
            param_space=param_space,
            tune_config=TuneConfig(mode="max", metric="iteration"),
        )
        with self.assertRaises(RuntimeError):
            tuner.fit()
```
