### ISSUE TITLE
[data] buffer is too small for requested array

### ISSUE THREAD

**Issue by Alpe6825** [ray-project/ray#30857]
### What happened + What you expected to happen

When I use the `train_test_split` for a dataset I can not iter with `iter_torch_batches` through the dataset. 

I get the following error
```

Traceback (most recent call last):
  File "/home/USER/PycharmProjects/Projectname_Preprocessing/CanonicalDataset.py", line 395, in <module>
    for batch in train.iter_torch_batches(batch_size=1, device="cuda:0", ):
  File "/home/USER/anaconda3/envs/Projectname_Preprocessing/lib/python3.9/site-packages/ray/data/dataset.py", line 2523, in iter_torch_batches
    for batch in self.iter_batches(
  File "/home/USER/anaconda3/envs/Projectname_Preprocessing/lib/python3.9/site-packages/ray/data/dataset.py", line 2450, in iter_batches
    yield from batch_blocks(
  File "/home/USER/anaconda3/envs/Projectname_Preprocessing/lib/python3.9/site-packages/ray/data/_internal/block_batching.py", line 129, in batch_blocks
    yield from get_batches(block_window[0])
  File "/home/USER/anaconda3/envs/Projectname_Preprocessing/lib/python3.9/site-packages/ray/data/_internal/block_batching.py", line 99, in get_batches
    result = _format_batch(batch, batch_format)
  File "/home/USER/anaconda3/envs/Projectname_Preprocessing/lib/python3.9/site-packages/ray/data/_internal/block_batching.py", line 147, in _format_batch
    batch = BlockAccessor.for_block(batch).to_numpy()
  File "/home/USER/anaconda3/envs/Projectname_Preprocessing/lib/python3.9/site-packages/ray/data/_internal/arrow_block.py", line 217, in to_numpy
    arrays.append(array.to_numpy(zero_copy_only=False))
  File "/home/USER/anaconda3/envs/Projectname_Preprocessing/lib/python3.9/site-packages/ray/air/util/tensor_extensions/arrow.py", line 285, in to_numpy
    return self._to_numpy(zero_copy_only=zero_copy_only)
  File "/home/USER/anaconda3/envs/Projectname_Preprocessing/lib/python3.9/site-packages/ray/air/util/tensor_extensions/arrow.py", line 269, in _to_numpy
    return np.ndarray(shape, dtype=ext_dtype, buffer=data_buffer, offset=offset)
TypeError: buffer is too small for requested array
```

### Versions / Dependencies

ray 2.1, python 3.9

### Reproduction script

```
ds_train, ds_test = ds.train_test_split(test_size=0.05, shuffle=True)

for batch in ds_train.iter_torch_batches(bacth_size=1, device="cuda:0")
   # do something here
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jianoaix** [comment]
@Alpe6825 can you provide a more complete script? e.g. how is `ds` in your script created in order to reproduce?

**Comment by Alpe6825** [comment]
yes of - it's a bit complicated: originally I had a custom torch dataset and wanted to convert it into a ray dataset unfortunately there is no function like `from_torch` so I tried to covert it like this:

```
def converting_dataset_from_torch_to_ray(ds):
    ray_ds = None
    for i, ds_entry in tqdm(enumerate(ds), total=len(ds), desc="load torch dataset to ray"):
        for k, v in ds_entry.items():
            ds_entry[k] = v.detach().cpu().numpy() 

        if ray_ds is None:
            ray_ds = ray.data.from_items([ds_entry])
        else:
            ray_ds = ray_ds.union(ray.data.from_items([ds_entry]))

    return ray_ds
```

After that I exported the ray_ds to parquet because the script above runs a while.

`ds_ray.write_parquet(cd.parquet_path)`

my plan was to use this for training but unfortunately it doesn't worked.
```
ds_ray = ray.data.read_parquet(cd.parquet_path)
train, test = ds_ray.train_test_split(test_size=0.05, shuffle=True)

for batch in train.iter_torch_batches(batch_size=1, device="cuda:0", ):
     img_gt = batch["gt"]
     .
     . 
     .
```

**Comment by jianoaix** [comment]
Thank you @Alpe6825 for providing more context. IIUC, this is just a single parquet file, so how large the parquet file? From the error msg it seems the memory you provisioned is not sufficient to support the conversion to numpy. I'd suggest check the data size (you can do with `ds_ray.size_bytes()`) against the memory size. Btw, if that parquet  (or a synthesized version of it) can be shared, that's even better for debugging.
