### ISSUE TITLE
[Dashboard] The dashboard crashes, i.e. blank screen 

### ISSUE THREAD

**Issue by fzyzcjy** [ray-project/ray#30854]
### What happened + What you expected to happen

When the page is loading, it looks like the following:

![image](https://user-images.githubusercontent.com/5236035/205250937-6201fe30-8942-4f2a-9ebd-3684aa754778.png)

However, after ~1 second, i.e. when the page finished loading, it becomes blank with the following errors;

![image](https://user-images.githubusercontent.com/5236035/205250846-3ed273a7-8f10-4c07-8201-aecaf7f208c6.png)

Text version of error:

```
react-dom.production.min.js:209 TypeError: Cannot read properties of null (reading 'find')
    at GRAMColumn.tsx:43:37
    at Array.map (<anonymous>)
    at ne (GRAMColumn.tsx:42:6)
    at Xi (react-dom.production.min.js:153:146)
    at ys (react-dom.production.min.js:261:496)
    at El (react-dom.production.min.js:246:265)
    at fl (react-dom.production.min.js:246:194)
    at sl (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
as @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
fi @ react-dom.production.min.js:131
cs @ react-dom.production.min.js:212
vl @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
qa @ react-dom.production.min.js:122
hl @ react-dom.production.min.js:248
sl @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
qa @ react-dom.production.min.js:122
Qa @ react-dom.production.min.js:123
Ka @ react-dom.production.min.js:122
nl @ react-dom.production.min.js:230
So @ react-dom.production.min.js:163
(anonymous) @ NodeRow.tsx:251
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ NodeRow.tsx:262
ls @ react-dom.production.min.js:211
Ol @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
qa @ react-dom.production.min.js:122
Tl @ react-dom.production.min.js:257
sl @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
qa @ react-dom.production.min.js:122
Qa @ react-dom.production.min.js:123
Ka @ react-dom.production.min.js:122
nl @ react-dom.production.min.js:230
So @ react-dom.production.min.js:163
(anonymous) @ useNodeList.ts:35
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ useNodeList.ts:45
ls @ react-dom.production.min.js:211
Ol @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
qa @ react-dom.production.min.js:122
Tl @ react-dom.production.min.js:257
sl @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
qa @ react-dom.production.min.js:122
Qa @ react-dom.production.min.js:123
B @ scheduler.production.min.js:17
T.port1.onmessage @ scheduler.production.min.js:14
GRAMColumn.tsx:43 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'find')
    at GRAMColumn.tsx:43:37
    at Array.map (<anonymous>)
    at ne (GRAMColumn.tsx:42:6)
    at Xi (react-dom.production.min.js:153:146)
    at ys (react-dom.production.min.js:261:496)
    at El (react-dom.production.min.js:246:265)
    at fl (react-dom.production.min.js:246:194)
    at sl (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)

### Versions / Dependencies

```
>>> ray.__version__
'2.1.0'
```

python 3.10.0

ubuntu 16.04

### Reproduction script

It constantly crashes in my usage, so completely cannot use the dashboard at all :(

No reproduction yet, since not sure how this is caused

### Issue Severity

High: It blocks me from completing my task.

**Comment by scottsun94** [comment]
cc: @rkooo567 @alanwguo

**Comment by alanwguo** [comment]
looks like the /nodes endpoint returns gpus.processes can be undefined. I can write code to make this handle more gracefully on the UI but we should also look into the backend to understand why the processes array is null.

@fzyzcjy Does this happen consistently for you? I may ask you some questions about your setup as I do more digging.

**Comment by fzyzcjy** [comment]
@alanwguo Yes, consistently. It is blank now for each and every refresh.

But the server may be restarted soon so I cannot guarantee it will have this problem in a few hours. But surely I can reply now for more info.

**Comment by alanwguo** [comment]
It seems like `gpu.processes` we get directly from `gpustat` python package and it's possible the value is `None`. I don't know if this is some sort of error but atleast I can make the UI not crash in these scenarios.

CC: @rkooo567 , do you know more about the gpustat package?

**Comment by rkooo567** [comment]
I am not exactly sure when None is returned. In a glance, it can happen when the API has the exception. I think it can rarely happen. We should just handle null case better
