### ISSUE TITLE
Exception while using ray stop

### ISSUE THREAD

**Issue by guoyuhong** [ray-project/ray#3086]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**: source
- **Ray version**: GitHub
- **Python version**: Python 3.6.4
- **Exact command to reproduce**: `ray stop`

### Describe the problem

Recently, there is an exception caught while using `ray stop`.  It looks like the file opened by notebook.notebookapp.list_running_servers contains nothing in it. 
One mitigation is to exclude this exception using `except json.decoder.JSONDecodeError:`. However, the `jupyter-notebook` process still exists. I need to clean it by hand.

Is there a way to suppress this exception and clean the process?
### Source code / logs

```
Traceback (most recent call last):
  File "/home/admin/py3/bin/ray", line 11, in <module>
    load_entry_point('ray', 'console_scripts', 'ray')()
  File "/home/gitlab-runner/builds/e3c78643/0/Arc/X/ray/python/ray/scripts/scripts.py", line 613, in main
    return cli()
  File "/home/admin/py3/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/admin/py3/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/admin/py3/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/admin/py3/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/admin/py3/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/gitlab-runner/builds/e3c78643/0/Arc/X/ray/python/ray/scripts/scripts.py", line 423, in stop
    str(server["pid"]) for server in list_running_servers()
  File "/home/gitlab-runner/builds/e3c78643/0/Arc/X/ray/python/ray/scripts/scripts.py", line 423, in <listcomp>
    str(server["pid"]) for server in list_running_servers()
  File "/home/admin/py3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1767, in list_running_servers
    info = json.load(f)
  File "/usr/local/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by robertnishihara** [comment]
I've seen this error in the past. Basically, `list_running_servers()` was failing I think. I can't remember how I solved it. I may have had to reinstall Jupyter or anaconda.

**Comment by robertnishihara** [comment]
We aren't using Jupyter for the UI anymore, so this should be fixed.
