### ISSUE TITLE
[AIR|DATA] Ray dataset schema evaluated to Null during training.   

### ISSUE THREAD

**Issue by n30111** [ray-project/ray#30884]
### What happened + What you expected to happen

During training of model using Ray AIR, the input dataset schema is evaluated to None, when preprocessor is set to None. 

When we run training will no preprocessor, it throws the following errors:
```
Traceback (most recent call last):
  File "schema_issue.py", line 191, in <module>
    result = trainer.fit()
  File "/lib/python3.8/site-packages/ray/train/base_trainer.py", line 360, in fit
    raise result.error
ray.exceptions.RayTaskError(AttributeError): ray::_Inner.train() (pid=19112, ip=10.5.0.4, repr=TensorflowTrainer)
  File "lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 355, in train
    raise skipped from exception_cause(skipped)
  File "/lib/python3.8/site-packages/ray/train/_internal/utils.py", line 54, in check_for_failure
    ray.get(object_ref)
ray.exceptions.RayTaskError(AttributeError): ray::RayTrainWorker._RayTrainWorker__execute() (pid=19145, ip=10.5.0.4, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x7f4f6f69c220>)
  File "lib/python3.8/site-packages/ray/train/_internal/worker_group.py", line 31, in __execute
    raise skipped from exception_cause(skipped)
  File "lib/python3.8/site-packages/ray/train/_internal/utils.py", line 129, in discard_return_wrapper
    train_func(*args, **kwargs)
  File "schema_issue.py", line 167, in train_loop_per_worker
    tf_dataset = dataset_shard.to_tf("input", "is_big_tip", batch_size=BATCH_SIZE)
  File "/lib/python3.8/site-packages/ray/data/dataset.py", line 2871, in to_tf
    valid_columns = schema.names
AttributeError: 'NoneType' object has no attribute 'names'
```

The error disappears if we use a preprocessor. Or if we just add one extra op such as `dataset.count()` just before the op that requires dataset.schema(). 

```
dataset_shard = session.get_dataset_shard("train")
dataset_shard.schema() # this evaluates to None 
>>> None
dataset_shard.count()
dataset_shard.shema() # THis returns correct result
>>> Schema object
```

### Versions / Dependencies

Ray 2.1.0
Python 3.8
OS: Ubuntu

### Reproduction script

```
from pprint import pprint

import ray

ray.shutdown()
ray.init()

from typing import Tuple

import numpy as np
import pandas as pd
import tensorflow as tf
from ray.air import Checkpoint, session
from ray.air.config import DatasetConfig, ScalingConfig
from ray.data.preprocessors import BatchMapper, Chain, OneHotEncoder, SimpleImputer
from ray.train.tensorflow import TensorflowCheckpoint, TensorflowTrainer, prepare_dataset_shard
from sklearn.model_selection import train_test_split

INPUT = "input"
LABEL = "is_big_tip"


def get_data() -> pd.DataFrame:
    """Fetch the taxi fare data to work on."""
    _data = pd.read_csv(
        "https://raw.githubusercontent.com/tensorflow/tfx/master/"
        "tfx/examples/chicago_taxi_pipeline/data/simple/data.csv"
    )
    _data[LABEL] = _data["tips"] / _data["fare"] > 0.2
    # We drop some columns here for the sake of simplicity.
    return _data.drop(
        [
            "tips",
            "fare",
            "dropoff_latitude",
            "dropoff_longitude",
            "pickup_latitude",
            "pickup_longitude",
            "pickup_census_tract",
        ],
        axis=1,
    )


data = get_data()


def split_data(data: pd.DataFrame) -> Tuple[ray.data.Dataset, pd.DataFrame, np.array]:
    """Split the data in a stratified way.

    Returns:
        A tuple containing train dataset, test data and test label.
    """
    # There is a native offering in Ray Dataset for split as well.
    # However, supporting stratification is a TODO there. So use
    # scikit-learn equivalent here.
    train_data, test_data = train_test_split(data, stratify=data[[LABEL]], random_state=1113)
    _train_ds = ray.data.from_pandas(train_data)
    _test_label = test_data[LABEL].values
    _test_df = test_data.drop([LABEL], axis=1)
    return _train_ds, _test_df, _test_label


dev_ds, test_df, test_label = split_data(data)


def get_preprocessor():
    """Construct a chain of preprocessors."""
    imputer1 = SimpleImputer(["dropoff_census_tract"], strategy="most_frequent")
    imputer2 = SimpleImputer(
        ["pickup_community_area", "dropoff_community_area"],
        strategy="most_frequent",
    )
    imputer3 = SimpleImputer(["payment_type"], strategy="most_frequent")
    imputer4 = SimpleImputer(["company"], strategy="most_frequent")
    imputer5 = SimpleImputer(
        ["trip_start_timestamp", "trip_miles", "trip_seconds"], strategy="mean"
    )

    ohe = OneHotEncoder(
        columns=[
            "trip_start_hour",
            "trip_start_day",
            "trip_start_month",
            "dropoff_census_tract",
            "pickup_community_area",
            "dropoff_community_area",
            "payment_type",
            "company",
        ],
        max_categories={
            "dropoff_census_tract": 25,
            "pickup_community_area": 20,
            "dropoff_community_area": 20,
            "payment_type": 2,
            "company": 7,
        },
    )

    def batch_mapper_fn(df):
        df["trip_start_year"] = pd.to_datetime(df["trip_start_timestamp"], unit="s").dt.year
        df = df.drop(["trip_start_timestamp"], axis=1)
        return df

    def concat_for_tensor(dataframe):
        from ray.data.extensions import TensorArray

        result = {}
        feature_cols = [col for col in dataframe.columns if col != LABEL]
        result[INPUT] = TensorArray(dataframe[feature_cols].to_numpy(dtype=np.float32))
        if LABEL in dataframe.columns:
            result[LABEL] = dataframe[LABEL]
        return pd.DataFrame(result)

    chained_pp = Chain(
        imputer1,
        imputer2,
        imputer3,
        imputer4,
        imputer5,
        ohe,
        BatchMapper(batch_mapper_fn),
        BatchMapper(concat_for_tensor),
    )
    return chained_pp


INPUT_SIZE = 120
BATCH_SIZE = 8
EPOCH = 1
NUM_WORKERS = 2


def build_model():
    model = tf.keras.models.Sequential()
    model.add(tf.keras.Input(shape=(INPUT_SIZE,)))
    model.add(tf.keras.layers.Dense(50, activation="relu"))
    model.add(tf.keras.layers.Dense(1, activation="sigmoid"))
    return model


def train_loop_per_worker():
    dataset_shard = session.get_dataset_shard("train")
    dataset_shard_eval = session.get_dataset_shard("evaluation")
    # dataset_shard.count()
    # dataset_shard_eval.count()

    strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()
    with strategy.scope():
        model = build_model()
        model.compile(
            loss="binary_crossentropy",
            optimizer="adam",
            metrics=["accuracy"],
        )

    tf_dataset = dataset_shard.to_tf("input", "is_big_tip", batch_size=BATCH_SIZE)
    tf_dataset_eval = dataset_shard_eval.to_tf("input", "is_big_tip", batch_size=BATCH_SIZE)

    model.fit(tf_dataset, validation_data=tf_dataset_eval, epochs=EPOCH)
    # This saves checkpoint in a way that can be used by Ray Serve coherently.
    session.report(
        {},
        checkpoint=TensorflowCheckpoint.from_model(model),
    )


train_ds, eval_ds = dev_ds.train_test_split(test_size=0.2)
preprocessor = get_preprocessor()

train_ds_processed = preprocessor.fit_transform(train_ds)
eval_ds_processed = preprocessor.fit_transform(eval_ds)


trainer = TensorflowTrainer(
    train_loop_per_worker=train_loop_per_worker,
    scaling_config=ScalingConfig(num_workers=NUM_WORKERS),
    datasets={"train": train_ds_processed, "evaluation": eval_ds_processed},
    dataset_config={
        "train": DatasetConfig(fit=False, split=False),
        "evaluation": DatasetConfig(split=False),
    },
    preprocessor=None,
)
result = trainer.fit()

```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jianoaix** [comment]
@n30111 could you try with master wheel? This could be the same issue as https://github.com/ray-project/ray/issues/30465, which should have been fixed recently.

**Comment by n30111** [comment]
@jianoaix thanks, its fixed.
