### ISSUE TITLE
[AIR] `TorchPredictor` doesn't work with ragged tensors

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#30930]
### What happened + What you expected to happen

Used `BatchPredictor` + `TorchPredictor` on ragged image data. Got a `TypeError`.
```
Traceback (most recent call last):
  File "/Users/balaji/Documents/detection/repro.py", line 16, in <module>
    predictor.predict(dataset, batch_size=2)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/train/batch_predictor.py", line 300, in predict
    prediction_results = data.map_batches(
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/dataset.py", line 617, in map_batches
    return Dataset(plan, self._epoch, self._lazy)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/dataset.py", line 223, in __init__
    self._plan.execute(allow_clear_input_blocks=False)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/plan.py", line 321, in execute
    blocks, stage_info = stage(
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/plan.py", line 685, in __call__
    blocks = compute._apply(
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/compute.py", line 424, in _apply
    raise e from None
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/compute.py", line 412, in _apply
    new_metadata = ray.get(new_metadata)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/_private/worker.py", line 2313, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::BlockWorker.map_block_nosplit() (pid=52927, ip=127.0.0.1, repr=<ray.data._internal.compute.BlockWorker object at 0x16a4f7460>)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/compute.py", line 315, in map_block_nosplit
    return _map_block_nosplit(
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/compute.py", line 487, in _map_block_nosplit
    for new_block in block_fn(blocks, *fn_args, **fn_kwargs):
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/dataset.py", line 589, in transform
    yield from process_next_batch(batch)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/dataset.py", line 577, in process_next_batch
    batch = batch_fn(batch, *fn_args, **fn_kwargs)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/train/batch_predictor.py", line 266, in __call__
    prediction_output_batch: DataBatchType = self._predictor.predict(
  File "/Users/balaji/Documents/GitHub/ray/python/ray/train/torch/torch_predictor.py", line 224, in predict
    return super(TorchPredictor, self).predict(data=data, dtype=dtype)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/train/predictor.py", line 211, in predict
    return self._predict_numpy(data, **kwargs)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/train/_internal/dl_predictor.py", line 94, in _predict_numpy
    model_input = self._arrays_to_tensors(data, dtype)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/train/torch/torch_predictor.py", line 231, in _arrays_to_tensors
    return convert_ndarray_batch_to_torch_tensor_batch(
  File "/Users/balaji/Documents/GitHub/ray/python/ray/air/_internal/torch_utils.py", line 172, in convert_ndarray_batch_to_torch_tensor_batch
    batch = convert_ndarray_to_torch_tensor(ndarrays, dtype=dtypes, device=device)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/air/_internal/torch_utils.py", line 144, in convert_ndarray_to_torch_tensor
    return torch.as_tensor(ndarray, dtype=dtype, device=device)
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
(BlockWorker pid=52927) /Users/balaji/Documents/GitHub/ray/python/ray/air/util/data_batch_conversion.py:228: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
(BlockWorker pid=52927)   arr = np.array([np.asarray(v) for v in arr])
```

### Versions / Dependencies

Ray: fcbee30ac186aa78e9b7a79677851bd3f2c0b4b2

### Reproduction script

```python
import numpy as np
import torch

import ray
from ray.train.batch_predictor import BatchPredictor
from ray.train.torch import TorchCheckpoint, TorchPredictor

dataset = ray.data.from_items(
    [{"image": np.zeros((32, 32, 3))}, {"image": np.zeros((64, 64, 3))}]
)
model = torch.nn.Identity()
checkpoint = TorchCheckpoint.from_model(model)
predictor = BatchPredictor(checkpoint=checkpoint, predictor_cls=TorchPredictor)
predictor.predict(dataset, batch_size=2)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by anyscalesam** [comment]
@bveeramani is this still an issue on latest ray?

**Comment by bveeramani** [comment]
Probably, but `Predictor`s are deprecated so this is a non-issue
