### ISSUE TITLE
[core][nightly] many_nodes test failed with dashboard test

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#31011]
### What happened + What you expected to happen

https://buildkite.com/ray-project/release-tests-branch/builds/1248#0184f908-b524-429f-8017-2f3fa2d33e2c

```
Waiting for memory monitor actor to be ready...
Memory monitor actor is ready now.
Traceback (most recent call last):
  File "distributed/test_many_tasks.py", line 139, in <module>
    test()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "distributed/test_many_tasks.py", line 80, in test
    dashboard_test = DashboardTestAtScale(addr)
  File "/home/ray/oss-release-tests-2/distributed/dashboard_test.py", line 89, in __init__
    node = list(filter(lambda n: n["node_ip"] == current_node_ip, nodes))[0]
IndexError: list index out of range
```

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

None

**Comment by rickyyx** [comment]
@rkooo567 somehow the node list is empty - is it expected?

**Comment by rickyyx** [comment]
oh actually I guess I know why - our default limit is 100. this cluster has 250.
