### ISSUE TITLE
[core][cluster] log monitor errors when os stat fails on worker log

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#31119]
### What happened + What you expected to happen

Seems we have logic to reopen file when the underlying file changes, but that logic could fail as reported in https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1671055386459259

Stack trace
```
The log monitor on node ray-head failed with the following error:
Traceback (most recent call last):
  File "/app/src/python/engine/py_image.binary.runfiles/pip_deps_ray/ray/_private/log_monitor.py", line 520, in <module>
    log_monitor.run()
  File "/app/src/python/engine/py_image.binary.runfiles/pip_deps_ray/ray/_private/log_monitor.py", line 436, in run
    anything_published = self.check_log_files_and_publish_updates()
  File "/app/src/python/engine/py_image.binary.runfiles/pip_deps_ray/ray/_private/log_monitor.py", line 339, in check_log_files_and_publish_updates
    file_info.reopen_if_necessary()
  File "/app/src/python/engine/py_image.binary.runfiles/pip_deps_ray/ray/_private/log_monitor.py", line 79, in reopen_if_necessary
    new_inode = os.stat(self.filename).st_ino
FileNotFoundError: [Errno 2] No such file or directory: '/data/.logs/ray/ray-head/session_2022-12-14_11-10-13_062347_1/logs/worker-a70dc50e6f4b179de4f30cdba9bafedc1e8b455faf9d72c47e798bf8-01000000-211.out'
```

### Versions / Dependencies

2.2 / master

### Reproduction script

David Hao provided a script that shows the issue:

```

import os
from pathlib import Path

filename = "/tmp/log.txt"

Path(filename).touch()

file_handle = open(filename)

# Simulate log rotation
os.rename(filename, f"{filename}.1")

# This passes
open_inode = os.fstat(file_handle.fileno()).st_ino
print(open_inode)

# This fails
new_inode = os.stat(filename).st_ino

```

### Issue Severity

None

**Comment by zhe-thoughts** [comment]
Thanks for staying on top of the user issue @clarng ! I have two questions:
1. Is this a regression between 1.13 and 2.0, or from 2.0 to 2.1, or 2.1 to 2.2?
2. Depending on the above, we should decide which patch releases to do

**Comment by clarng** [comment]
Looks like this affects 2.0 and above.

The offending commit:

```
commit a72b673ce49f504ff9e43d23a9559075e9f0df40
Author: Alex Wu <itswu.alex@gmail.com>
Date:   Tue Jul 26 10:32:47 2022 -0700

    [log_monitor] Check if files need to be reopened (#26847)

diff --git a/python/ray/_private/log_monitor.py b/python/ray/_private/log_monitor.py
index 3cdd808ad..9bb970746 100644
--- a/python/ray/_private/log_monitor.py
+++ b/python/ray/_private/log_monitor
```

Where 2.0 is cut here:

```
commit 4ab97399cda80be1e146946c43d6fb2926248b28
Author: shrekris-anyscale <92341594+shrekris-anyscale@users.noreply.github.com>
Date:   Wed Jul 27 11:21:19 2022 -0700

    [Serve] Only start Serve in the CLI through the `serve deploy` command (#27063)
    
    These Serve CLI commands start Serve if it's not already running:
    
    * `serve deploy`
    * `serve config`
    * `serve status`
    * `serve shutdown`
    
    #27026 introduces the ability to specify a `host` and `port` in the Serve config file. However, once Serve starts running, changing these options requires tearing down the entire Serve application and relaunching it. This limitation is an issue because users can inadvertently start Serve by running one of the `GET`-based CLI commands (i.e. `serve config` or `serve status`) before running `serve deploy`.
    
    This change makes `serve deploy` the only CLI command that can start a Serve application on a Ray cluster. The other commands have updated behavior when Serve is not yet running on the cluster.
    
    * `serve config`: prints an empty config body.
    
    ```yaml
```

**Comment by damdaepark** [comment]
I also had the same issue. The terminal displayed follows:

```
2023-02-24 04:30:19,237 WARNING worker.py:1851 -- Raylet is terminated: ip=192.168.207.5, id=abc3bfd36381a1e890104187b695fe0f938fbfc60e80ac16f9bf12c2. Termination is unexpected. Possible reasons include: (1) SIGKILL by the user or system OOM killer, (2) Invalid memory access from Raylet causing SIGSEGV or SIGBUS, (3) Other termination signals. Last 20 lines of the Raylet logs:
    [state-dump]        CoreWorkerService.grpc_client.Exit - 389 total (0 active), CPU time: mean = 9.412 us, total = 3.661 ms
    [state-dump]        NodeManager.deadline_timer.print_event_loop_stats - 316 total (1 active, 1 running), CPU time: mean = 1.193 ms, total = 377.037 ms
    [state-dump]        PeriodicalRunner.RunFnPeriodically - 9 total (0 active), CPU time: mean = 279.490 us, total = 2.515 ms
    [state-dump]        NodeResourceInfoGcsService.grpc_client.GetResources - 7 total (0 active), CPU time: mean = 25.903 us, total = 181.323 us
    [state-dump]        Subscriber.HandlePublishedMessage_GCS_NODE_INFO_CHANNEL - 5 total (0 active), CPU time: mean = 97.001 us, total = 485.004 us
    [state-dump]        ObjectManagerService.grpc_client.Push - 3 total (0 active), CPU time: mean = 27.501 us, total = 82.502 us
    [state-dump]        ObjectManager.Push - 3 total (0 active), CPU time: mean = 30.475 us, total = 91.424 us
    [state-dump]        ObjectManager.HandlePull - 3 total (0 active), CPU time: mean = 339.323 us, total = 1.018 ms
    [state-dump]        InternalPubSubGcsService.grpc_client.GcsSubscriberCommandBatch - 2 total (0 active), CPU time: mean = 64.520 us, total = 129.041 us
    [state-dump]        NodeInfoGcsService.grpc_client.GetAllNodeInfo - 1 total (0 active), CPU time: mean = 131.703 us, total = 131.703 us
    [state-dump]        Subscriber.HandlePublishedMessage_GCS_JOB_CHANNEL - 1 total (0 active), CPU time: mean = 323.899 us, total = 323.899 us
    [state-dump]        AgentManagerService.grpc_server.RegisterAgent - 1 total (0 active), CPU time: mean = 163.764 us, total = 163.764 us
    [state-dump]        JobInfoGcsService.grpc_client.GetAllJobInfo - 1 total (0 active), CPU time: mean = 8.195 us, total = 8.195 us
    [state-dump]        NodeInfoGcsService.grpc_client.GetInternalConfig - 1 total (0 active), CPU time: mean = 15.551 ms, total = 15.551 ms
    [state-dump]        ObjectManagerService.grpc_client.Pull - 1 total (0 active), CPU time: mean = 7.615 us, total = 7.615 us
    [state-dump]        NodeInfoGcsService.grpc_client.RegisterNode - 1 total (0 active), CPU time: mean = 172.184 us, total = 172.184 us
    [state-dump]        CoreWorkerService.grpc_client.UpdateObjectLocationBatch - 1 total (0 active), CPU time: mean = 6.873 us, total = 6.873 us
    [state-dump] DebugString() time ms: 0
    [state-dump] 
    [state-dump] 

2023-02-24 04:30:19,408 WARNING worker.py:1851 -- Raylet is terminated: ip=192.168.207.3, id=b771a303705a4f53d153d8a264aa37d28b66c2332d7e2747285aea9a. Termination is unexpected. Possible reasons include: (1) SIGKILL by the user or system OOM killer, (2) Invalid memory access from Raylet causing SIGSEGV or SIGBUS, (3) Other termination signals. Last 20 lines of the Raylet logs:
    [state-dump]        ObjectManager.ObjectDeleted - 346 total (0 active), CPU time: mean = 15.108 us, total = 5.227 ms
    [state-dump]        CoreWorkerService.grpc_client.Exit - 331 total (0 active), CPU time: mean = 9.852 us, total = 3.261 ms
    [state-dump]        RuntimeEnvService.grpc_client.DeleteRuntimeEnvIfPossible - 331 total (0 active), CPU time: mean = 7.306 us, total = 2.418 ms
    [state-dump]        WorkerInfoGcsService.grpc_client.ReportWorkerFailure - 331 total (0 active), CPU time: mean = 7.950 us, total = 2.631 ms
    [state-dump]        NodeManager.deadline_timer.print_event_loop_stats - 314 total (1 active, 1 running), CPU time: mean = 1.544 ms, total = 484.832 ms
    [state-dump]        PeriodicalRunner.RunFnPeriodically - 9 total (0 active), CPU time: mean = 289.001 us, total = 2.601 ms
    [state-dump]        NodeResourceInfoGcsService.grpc_client.GetResources - 7 total (0 active), CPU time: mean = 16.195 us, total = 113.364 us
    [state-dump]        InternalPubSubGcsService.grpc_client.GcsSubscriberCommandBatch - 2 total (0 active), CPU time: mean = 58.548 us, total = 117.097 us
    [state-dump]        Subscriber.HandlePublishedMessage_GCS_NODE_INFO_CHANNEL - 2 total (0 active), CPU time: mean = 92.665 us, total = 185.329 us
    [state-dump]        AgentManagerService.grpc_server.RegisterAgent - 1 total (0 active), CPU time: mean = 168.721 us, total = 168.721 us
    [state-dump]        NodeInfoGcsService.grpc_client.RegisterNode - 1 total (0 active), CPU time: mean = 166.734 us, total = 166.734 us
    [state-dump]        Subscriber.HandlePublishedMessage_GCS_JOB_CHANNEL - 1 total (0 active), CPU time: mean = 293.766 us, total = 293.766 us
    [state-dump]        JobInfoGcsService.grpc_client.GetAllJobInfo - 1 total (0 active), CPU time: mean = 8.132 us, total = 8.132 us
    [state-dump]        NodeInfoGcsService.grpc_client.GetAllNodeInfo - 1 total (0 active), CPU time: mean = 249.345 us, total = 249.345 us
    [state-dump]        ObjectManagerService.grpc_client.Pull - 1 total (0 active), CPU time: mean = 21.520 us, total = 21.520 us
    [state-dump]        CoreWorkerService.grpc_client.UpdateObjectLocationBatch - 1 total (0 active), CPU time: mean = 7.177 us, total = 7.177 us
    [state-dump]        NodeInfoGcsService.grpc_client.GetInternalConfig - 1 total (0 active), CPU time: mean = 16.144 ms, total = 16.144 ms
    [state-dump] DebugString() time ms: 0
    [state-dump] 
    [state-dump] 

2023-02-24 04:30:19,409 WARNING worker.py:1851 -- Raylet is terminated: ip=192.168.207.6, id=097320340fbf79e194e3431aeb41ae779264920c25cda4a64689ed5d. Termination is unexpected. Possible reasons include: (1) SIGKILL by the user or system OOM killer, (2) Invalid memory access from Raylet causing SIGSEGV or SIGBUS, (3) Other termination signals. Last 20 lines of the Raylet logs:
    [state-dump]        ObjectManagerService.grpc_client.Pull - 1 total (0 active), CPU time: mean = 9.147 us, total = 9.147 us
    [state-dump]        Subscriber.HandlePublishedMessage_GCS_JOB_CHANNEL - 1 total (0 active), CPU time: mean = 298.723 us, total = 298.723 us
    [state-dump]        CoreWorkerService.grpc_client.UpdateObjectLocationBatch - 1 total (0 active), CPU time: mean = 6.579 us, total = 6.579 us
    [state-dump]        JobInfoGcsService.grpc_client.GetAllJobInfo - 1 total (0 active), CPU time: mean = 10.603 us, total = 10.603 us
    [state-dump] DebugString() time ms: 1
    [state-dump] 
    [state-dump] 
    [2023-02-24 04:29:48,136 I 3772 3772] (raylet) worker_pool.cc:469: Started worker process with pid 6448, the token is 5539
    [2023-02-24 04:29:49,230 I 3772 3772] (raylet) worker_pool.cc:469: Started worker process with pid 6453, the token is 5540
    [2023-02-24 04:29:51,677 I 3772 3772] (raylet) node_manager.cc:1490: NodeManager::DisconnectClient, disconnect_type=1, has creation task exception = true
    [2023-02-24 04:29:52,475 I 3772 3772] (raylet) node_manager.cc:1490: NodeManager::DisconnectClient, disconnect_type=1, has creation task exception = true
    [2023-02-24 04:29:55,259 I 3772 3772] (raylet) worker_pool.cc:469: Started worker process with pid 6556, the token is 5541
    [2023-02-24 04:29:57,883 I 3772 3772] (raylet) node_manager.cc:1490: NodeManager::DisconnectClient, disconnect_type=1, has creation task exception = true
    [2023-02-24 04:29:59,674 I 3772 3772] (raylet) worker_pool.cc:469: Started worker process with pid 6616, the token is 5542
    [2023-02-24 04:30:02,680 I 3772 3772] (raylet) node_manager.cc:1490: NodeManager::DisconnectClient, disconnect_type=1, has creation task exception = true
    [2023-02-24 04:30:03,289 I 3772 3772] (raylet) worker_pool.cc:469: Started worker process with pid 6677, the token is 5543
    [2023-02-24 04:30:06,081 I 3772 3772] (raylet) node_manager.cc:1490: NodeManager::DisconnectClient, disconnect_type=1, has creation task exception = true
    [2023-02-24 04:30:14,549 I 3772 3772] (raylet) worker_pool.cc:469: Started worker process with pid 6823, the token is 5544
    [2023-02-24 04:30:17,411 I 3772 3772] (raylet) node_manager.cc:1490: NodeManager::DisconnectClient, disconnect_type=1, has creation task exception = true
    [2023-02-24 04:30:18,909 I 3772 3772] (raylet) accessor.cc:612: Received notification for node id = abc3bfd36381a1e890104187b695fe0f938fbfc60e80ac16f9bf12c2, IsAlive = 0

2023-02-24 04:31:07,576 WARNING worker.py:1851 -- The log monitor on node node05 failed with the following error:
Traceback (most recent call last):
  File "/home/damdaepark/anaconda3/envs/arena/lib/python3.8/site-packages/ray/_private/log_monitor.py", line 520, in <module>
    log_monitor.run()
  File "/home/damdaepark/anaconda3/envs/arena/lib/python3.8/site-packages/ray/_private/log_monitor.py", line 436, in run
    anything_published = self.check_log_files_and_publish_updates()
  File "/home/damdaepark/anaconda3/envs/arena/lib/python3.8/site-packages/ray/_private/log_monitor.py", line 339, in check_log_files_and_publish_updates
    file_info.reopen_if_necessary()
  File "/home/damdaepark/anaconda3/envs/arena/lib/python3.8/site-packages/ray/_private/log_monitor.py", line 79, in reopen_if_necessary
    new_inode = os.stat(self.filename).st_ino
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2023-02-23_23-13-32_104035_25176/logs/worker-fb837995504b7f9900954616801902fe25796ae8e37e546569de7cb4-01000000-28224.err'
```
