### ISSUE TITLE
[AIR] Can't load model with `TensorflowCheckpoint`

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#31149]
### What happened + What you expected to happen

Tried to resume training a TensorFlow model, got an error:
```
Traceback (most recent call last):
  File "/private/tmp/workspace/repro.py", line 45, in <module>
    results = trainer.fit()
  File "/private/tmp/workspace/.venv/lib/python3.10/site-packages/ray/train/base_trainer.py", line 360, in fit
    raise result.error
types.RayTaskError(ValueError): ray::_Inner.train() (pid=18227, ip=127.0.0.1, repr=TensorflowTrainer)
  File "/private/tmp/workspace/.venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 367, in train
    raise skipped from exception_cause(skipped)
  File "/private/tmp/workspace/.venv/lib/python3.10/site-packages/ray/train/_internal/utils.py", line 54, in check_for_failure
    ray.get(object_ref)
ray.exceptions.RayTaskError(ValueError): ray::RayTrainWorker._RayTrainWorker__execute() (pid=18237, ip=127.0.0.1, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x144b89b10>)
  File "/private/tmp/workspace/.venv/lib/python3.10/site-packages/ray/train/_internal/worker_group.py", line 31, in __execute
    raise skipped from exception_cause(skipped)
  File "/private/tmp/workspace/.venv/lib/python3.10/site-packages/ray/train/_internal/utils.py", line 129, in discard_return_wrapper
    train_func(*args, **kwargs)
  File "/private/tmp/workspace/repro.py", line 23, in train_loop_per_worker
    model = checkpoint.get_model(model)
  File "/private/tmp/workspace/.venv/lib/python3.10/site-packages/ray/train/tensorflow/tensorflow_checkpoint.py", line 233, in get_model
    model = model_definition()
  File "/private/tmp/workspace/.venv/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/private/tmp/workspace/.venv/lib/python3.10/site-packages/keras/utils/layer_utils.py", line 809, in split_out_first_arg
    raise ValueError(
ValueError: The first argument to `Layer.call` must always be passed.
```

### Versions / Dependencies

Ray: 6229bd1552243bbd95301cce979ead697742fed0

### Reproduction script

First, run this:

```
import ray
import tensorflow as tf
from ray.air import session, ScalingConfig
from ray.train.tensorflow import TensorflowCheckpoint, TensorflowTrainer


(images, labels), _ = tf.keras.datasets.cifar10.load_data()
dataset = ray.data.from_items(
    [
        {"image": image / 255.0, "label": label.flatten()}
        for image, label in zip(images, labels)
    ]
)


def train_loop_per_worker(config):
    strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()
    with strategy.scope():
        model = tf.keras.applications.MobileNetV3Small(input_shape=(32, 32, 3))

        checkpoint = session.get_checkpoint()
        if checkpoint is not None:
            model = checkpoint.get_model(model)

        model.compile(
            optimizer="adam",
            loss="sparse_categorical_crossentropy",
            metrics=["accuracy"],
        )

    dataset = session.get_dataset_shard("train").to_tf("image", "label", batch_size=4)
    model.fit(dataset, epochs=1)
    session.report({}, checkpoint=TensorflowCheckpoint.from_model(model))


checkpoint = None
trainer = TensorflowTrainer(
    train_loop_per_worker=train_loop_per_worker,
    datasets={"train": dataset.limit(10)},
    scaling_config=ScalingConfig(num_workers=2),
    resume_from_checkpoint=checkpoint,
)
results = trainer.fit()

results.checkpoint.to_directory("checkpoint")
```

Then replace `checkpoint = None` with `checkpoint = TensorflowCheckpoint.from_directory("checkpoint")` and run the script again.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by bveeramani** [comment]
Closing because this isn't a bug. The argument passed to `get_model` is supposed to be a `Callable[[], Model]`
