### ISSUE TITLE
[Serve] error running Gradio Serve example

### ISSUE THREAD

**Issue by maxpumperla** [ray-project/ray#31161]
### What happened + What you expected to happen

Running the example in this notebook https://maxpumperla.com/learning_ray/ch_11_ecosystem/ locally we see a strange pickle error that didn't come up before (we tested this on Ray 2.0) when running `serve run gradio_demo:app`, namely:

```
2022-12-16 12:13:34,989 INFO scripts.py:304 -- Deploying from import path: "gradio_demo:app".
2022-12-16 12:13:43,820 INFO worker.py:1535 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8266 
(ServeController pid=94942) INFO 2022-12-16 12:13:46,439 controller 94942 http_state.py:132 - Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-f81802bedd5a4c7d6683582cee5bd36bda82264b61c4a7939f58d5a0' on node 'f81802bedd5a4c7d6683582cee5bd36bda82264b61c4a7939f58d5a0' listening on '127.0.0.1:8000'
Traceback (most recent call last):
  File "/Users/maxpumperla/code/learning_ray_public/venv/bin/serve", line 8, in <module>
    sys.exit(cli())
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/serve/scripts.py", line 333, in run
    handle = serve.run(node, host=host, port=port)
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/serve/api.py", line 537, in run
    parameter_group, _blocking=_blocking, remove_past_deployments=True
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/serve/_private/client.py", line 37, in check
    return f(self, *args, **kwargs)
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/serve/_private/client.py", line 260, in deploy_group
    is_driver_deployment=deployment["is_driver_deployment"],
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/serve/_private/client.py", line 37, in check
    return f(self, *args, **kwargs)
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/serve/_private/client.py", line 459, in get_deploy_args
    ray_actor_options=ray_actor_options,
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/serve/config.py", line 381, in create
    cloudpickle.dumps(init_args),
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 627, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle Context objects
(HTTPProxyActor pid=94946) INFO:     Started server process [94946]
```

Of note is that running the gradio interface with `demo.launch()` works as expected, so it's not an issue with loading the AIR checkpoint etc.

To reproduce this, first run the training step and generate a checkpoint from [this notebook](https://github.com/maxpumperla/learning_ray/blob/main/notebooks/ch_11_ecosystem.ipynb) and then run this [gradio demo](https://github.com/maxpumperla/learning_ray/blob/main/notebooks/gradio_demo.py).

My hope is that this might just be a wonky dependency issue that's just not obvious. 

### Versions / Dependencies

! pip install "ray[air, serve]==2.2.0" "gradio==3.11.0" "requests==2.28.1"
! pip install "mlflow==1.30.0" "torch==1.12.1" "torchvision==0.13.1"

### Reproduction script

discussed above

### Issue Severity

High: It blocks me from completing my task.

**Comment by zcin** [comment]
This issue is resolved if you downgrade Gradio to 3.5. Updating the integration to work with newer versions of Gradio is currently between a P1/P2 issue, the priority can be bumped if necessary.
