### ISSUE TITLE
Import no working in a cluster

### ISSUE THREAD

**Issue by tihom** [ray-project/ray#3116]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: pip
- **Ray version**: 0.5.3
- **Python version**: 3.5.2
- **Exact command to reproduce**: python3 hello.py

### Describe the problem

I have 2 AWS EC2 instances running with one as head and one as worked. I followed the instructions using Manual cluster setup. I have two python files. One of them imports a function from the other and calls that function inside a `remote` function. When I run this I get as error `Exception: This function was not imported properly.`. The set up runs fine if I do not import from the second file.

### Source code / logs

Two files:
```
# hello.py

import ray
import sys

ray.init(redis_address="172.31.2.108:6379")

import time
from testimport import sleep

@ray.remote
def f():
    time.sleep(0.01)
    sleep(0.01)
    return "python version: %s, ip: %s" % (sys.version_info, ray.services.get_node_ip_address())

# Get a list of the IP addresses of the nodes that have joined the cluster.
print(set(ray.get([f.remote() for _ in range(100)])))
```
```
# testimport.py
import time

def sleep(n):
    time.sleep(n)
```
Command run:
`python3 hello.py`

Output:

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/ray/import_thread.py", line 131, in fetch_and_register_remote_function
    function = pickle.loads(serialized_function)
ImportError: No module named 'testimport'
.
.
.
Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.
Traceback (most recent call last):
  File "hello.py", line 16, in <module>
    print(set(ray.get([f.remote() for _ in range(100)])))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/ray/worker.py", line 2514, in get
    raise RayGetError(object_ids[i], value)
ray.worker.RayGetError: Could not get objectid ObjectID(46fe73ad1bbfdc7c6293a0d80e570329a911ecf9). It was created by remote function __main__.f which failed with:

Remote function __main__.f failed with:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/ray/import_thread.py", line 123, in f
    raise Exception("This function was not imported properly.")
Exception: This function was not imported properly.
```

Commenting out `sleep(0.01)` from `hello.py` gives:
`{"python version: sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0), ip: 172.31.2.108", "python version: sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0), ip: 172.31.0.97"}`
So the set up is working for a single file with no imports.

Removing the worker node from the cluster gives:
`{"python version: sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0), ip: 172.31.2.108"}`
So the import works on a single node cluster.

Seems like the import of the second file does not work when running on a cluster.

**Comment by robertnishihara** [comment]
Thanks for reporting this @tihom! It sounds like it may be a bug with cloudpickle.

Does it work if you instead do `import testimport` and then `test_import.sleep` inside of the remote function?

**Comment by tihom** [comment]
Changing the call to `testimport.sleep` does not work either, have the same error and behavior (works on single node and works on two nodes without the import)

**Comment by robertnishihara** [comment]
Hm, well one thing that should probably work is to also move the `import testimport` statement into the remote function.

**Comment by tihom** [comment]
Error changes after moving `import testimport` statement into the remote function to:

```
Remote function __main__.f failed with:

Traceback (most recent call last):
  File "hello.py", line 12, in f
ImportError: No module named testimport
```

I am guessing that `testimport.py` is not shipped hence the error while previously found the module but could not find the function `sleep` in it.

**Comment by robertnishihara** [comment]
That’s right, in this case the module needs to be somewhere on your PYTHONPATH on both machines.

**Comment by edoakes** [comment]
Stale - please open new issue if still relevant

**Comment by mohitranawat** [comment]
Can someone help me to fix this issue ? I am not able to fix this issue

**Comment by robertnishihara** [comment]
@mohitranawat can you post a small self-contained script that reproduces the issue? Then we might be able to help diagnose it.

**Comment by mohitranawat** [comment]
@robertnishihara actually issue is same. Whenever the process is going into the different machine import is not happening.

Error is `File "/home/mohit/virtualenvironment/pytorch_env/lib/python3.6/site-packages/ray/function_manager.py", line 177, in fetch_and_register_remote_function
    function = pickle.loads(serialized_function)
  File "/home/mohit/virtualenvironment/pytorch_env/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle.py", line 1096, in subimport
    __import__(name)
ModuleNotFoundError: No module named 'model' `

It i s not able to 'model' module

**Comment by robertnishihara** [comment]
Do you have a file called `model.py` that you are trying to import? It will need to be on the PYTHONPATH on all the machines. If that's not the issue, please provide detailed instructions for how to reproduce the issue!

**Comment by mohitranawat** [comment]
@robertnishihara how to put `model.py` on PYTHONPATH on all machines? Can you elaborate?

**Comment by robertnishihara** [comment]
Possibilities
- Make it a Python module (e.g., by creating a `setup.py` file) and install it on each machine.
- Put the file in the same location, e.g., `$HOME/model.py`, on each machine and then start the Ray driver from the same directory as `model.py` (so that `import model` works in Python in that directory).

**Comment by jseppanen** [comment]
also this patch to cloudpickle might help: https://github.com/cloudpipe/cloudpickle/pull/391

**Comment by architkulkarni** [comment]
The new Runtime Environments feature, which didn't exist at the time of this post, should help with this issue: https://docs.ray.io/en/latest/handling-dependencies.html#runtime-environments. (See the `working_dir` and `py_modules` entries.)
