### ISSUE TITLE
[slurm] Unable to connect to Ray instance from python 

### ISSUE THREAD

**Issue by UmerTariq1** [ray-project/ray#31199]
### What happened + What you expected to happen

I am having a problem with intializing ray in python.  After i have started ray by `ray start` , I cannot connect/init() to it via python when i am using slurm. I **CAN** connect  to ray instance (using init() ) without slurm but when combining both then that is the issue.  I stumbled on [this](https://github.com/ray-project/ray/issues/21592) and [this](https://discuss.ray.io/t/ray-on-slurm-problems-with-initialization/6361) because i was facing the same errors but i am unable to resolve my issue. Below I am pasting my errors that i have received maybe that will be of help. Note that  ray instance is running in the back all the time (checked with ray status), so ray instance unavailability is not an issue. Also, I was facing the error on 2nd link (#6361 issue on ray discussions) but i resolved it by using num_cpus=X. but then i got other error (mentioned below)

### System Info
- `transformers` version: 4.22.0
- Platform: Slurm on Linux-5.4.0-80-generic-x86_64-with-debian-buster-sid
- Python version: 3.7.9
- Huggingface_hub version: 0.9.1
- PyTorch version (GPU?): 1.12.1+cu102 (False)
- Ray: 2.2.0

### Reproduction script

 - this needs to be on slurm.  Problem is working with slurm

1)  
```
python=/netscratch/butt/installations/miniconda3/envs/trainsformers3.0.2/bin/python
$python test.py
```

2)
```
import ray

@ray.remote
def hello_world():
    return "hello world"

# Automatically connect to the running Ray cluster.
# ray.init(num_cpus=1)
ray.init(namespace="rag", address="auto")
print(ray.get(hello_world.remote()))
```

3) run the (1) script.

### Error logs
————————————————————————————————————————————————————————
python code: 
ray.init(address="192.168.33.185:6379", namespace="rag",num_cpus=1)

Error output:
Traceback (most recent call last):
  File "finetune_rag.py", line 836, in <module>
    main(args)
  File "finetune_rag.py", line 736, in main
    ray.init(address="192.168.33.185:6379", namespace="rag",num_cpus=1)
  File "/netscratch/butt/installations/miniconda3/envs/trainsformers3.0.2/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/netscratch/butt/installations/miniconda3/envs/trainsformers3.0.2/lib/python3.7/site-packages/ray/worker.py", line 1046, in init
    "When connecting to an existing cluster, num_cpus "
ValueError: When connecting to an existing cluster, num_cpus and num_gpus must not be provided.
srun: error: glasgow: task 0: Exited with exit code 1

————————————————————————————————————————————————————————
python code: 
ray.init(address="192.168.33.185:6379", namespace="rag")

Error output:
INFO:ray.worker:Connecting to existing Ray cluster at address: 192.168.33.185:6379
[2022-12-15 20:47:58,290 I 2312185 2312185] global_state_accessor.cc:357: This node has an IP address of 192.168.33.203, while we can not found the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.
[2022-12-15 20:48:07,439 E 2312185 2312362] core_worker_process.cc:223: Failed to get the system config from raylet because it is dead. Worker will terminate. Status: GrpcUnavailable: RPC Error message: failed to connect to all addresses; RPC Error details:  .Please see `raylet.out` for more details.
srun: error: glasgow: task 0: Exited with exit code 1

————————————————————————————————————————————————————————
python code: 
ray.init(address="127.0.0.1:8265", namespace="rag")

Error output:
Traceback (most recent call last):
  File "finetune_rag.py", line 837, in <module>
    main(args)
  File "finetune_rag.py", line 737, in main
    ray.init(address="127.0.0.1:8265", namespace="rag")
  File "/netscratch/butt/installations/miniconda3/envs/trainsformers3.0.2/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/netscratch/butt/installations/miniconda3/envs/trainsformers3.0.2/lib/python3.7/site-packages/ray/_private/worker.py", line 1499, in init
    connect_only=True,
  File "/netscratch/butt/installations/miniconda3/envs/trainsformers3.0.2/lib/python3.7/site-packages/ray/_private/node.py", line 186, in __init__
    num_retries=NUM_REDIS_GET_RETRIES,
  File "/netscratch/butt/installations/miniconda3/envs/trainsformers3.0.2/lib/python3.7/site-packages/ray/_private/utils.py", line 1431, in internal_kv_get_with_retry
    f"Could not read '{key.decode()}' from GCS. Did GCS start successfully?"
ConnectionError: Could not read 'session_name' from GCS. Did GCS start successfully?
srun: error: glasgow: task 0: Exited with exit code 1

————————————————————————————————————————————————————————
python code: 
ray.init(address="127.0.0.1:8265", namespace="rag", num_cpus=1)

Error output:
raceback (most recent call last):
  File "finetune_rag.py", line 837, in <module>
    main(args)
  File "finetune_rag.py", line 737, in main
    ray.init(address="127.0.0.1:8265", namespace="rag", num_cpus=1)
  File "/netscratch/butt/installations/miniconda3/envs/trainsformers3.0.2/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/netscratch/butt/installations/miniconda3/envs/trainsformers3.0.2/lib/python3.7/site-packages/ray/_private/worker.py", line 1446, in init
    "When connecting to an existing cluster, num_cpus "
ValueError: When connecting to an existing cluster, num_cpus and num_gpus must not be provided.
srun: error: glasgow: task 0: Exited with exit code 1

### Issue Severity

High: It blocks me from completing my task.

Edit: reformatted the question for better understanding

**Comment by zhe-thoughts** [comment]
Thanks for reporting this @UmerTariq1 ! Does this only happen when you use Slurm? Marking as P2 since our Slurm support is work-in-progress. But if this happens even without Slurm looks like a P0/P1

**Comment by fif911** [comment]
Was there any progress on this? I get the same issue while using SLURM

**Comment by fif911** [comment]
Hey @zhe-thoughts. Was there any progress on this? I am getting the same issue when using SLURM.
