### ISSUE TITLE
Benchmarking Ray on Kubernetes cluster and facing errors

### ISSUE THREAD

**Issue by dalbhanj** [ray-project/ray#31243]
### What happened + What you expected to happen

I am going through benchmark documentation and apply it on EKS (Amazon managed k8s) clusters. I'm getting errors as shown below. I am new to Ray. Is this the right approach to benchmark Ray performance on K8s clusters? 

### Versions / Dependencies

Ray 2.2.0

### Reproduction script

Install KubeRay Operator on EKS cluster & deploy Ray cluster as per docs (https://docs.ray.io/en/latest/cluster/kubernetes/getting-started.html)
Go through docs to run benchmark tests (https://docs.ray.io/en/latest/ray-air/benchmarks.html)

! ray job submit --working-dir . -- python benchmarks/data_benchmark.py --dataset-size-gib=10 --num-workers=1
```
Status message: Job failed due to an application error, last available logs (truncated to 20,000 chars):
2022-12-20 11:56:54,234	INFO worker.py:1224 -- Using address 192.168.63.158:6379 set in the environment variable RAY_ADDRESS
2022-12-20 11:56:54,234	INFO worker.py:1333 -- Connecting to existing Ray cluster at address: 192.168.63.158:6379...
2022-12-20 11:56:54,244	INFO worker.py:1515 -- Connected to Ray cluster. View the dashboard at http://192.168.63.158:8265 
Created dataset Dataset(num_blocks=201, num_rows=1048576, schema={__value__: ArrowTensorType(shape=(1280,), dtype=int64)}) of size 10737418240
Traceback (most recent call last):
  File "benchmarks/data_benchmark2.py", line 57, in <module>
    run_ingest_bulk(ds, args.num_workers, args.num_cpus_per_worker)
  File "benchmarks/data_benchmark2.py", line 26, in run_ingest_bulk
    dummy_prep = BatchMapper(lambda df: df * 2, batch_format="pandas")
TypeError: __init__() got an unexpected keyword argument 'batch_format'
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by cadedaniel** [comment]
cc @c21 does this look like a version mismatch?

**Comment by c21** [comment]
Looks like to me the Ray version is not set to 2.2.0 correctly. @dalbhanj - could you help double check the Ray version you are using is Ray 2.2.0? Thanks.

**Comment by dalbhanj** [comment]
I'm hoping this is what you need. Let me know if I need upgrade ray CLI, raycluster or both. Thanks!
```
$ ray --version
ray, version 2.1.0
$ k get raycluster/raycluster-autoscaler -n ray -o yaml
...
        containers:
        - image: rayproject/ray:2.0.0
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - ray stop
          name: ray-head
          ports:
          - containerPort: 6379
            name: gcs
            protocol: TCP
          - containerPort: 8265
            name: dashboard
            protocol: TCP
          - containerPort: 10001
            name: client
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2G
            requests:
              cpu: 500m
              memory: 1G
  rayVersion: 2.0.0
...
```
