### ISSUE TITLE
[Debugger] `RAY_PDB=1` crashes due to nonextant `post_mortem`

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#31273]
Impacted versions: Ray 2.2, 2.1, 2.0 (changed added in 21 June 2022)

We renamed `post_mortem` to `_post_mortem` here https://github.com/ray-project/ray/blob/00152a4b4b732d59bd2656480f4dc41f213b1156/python/ray/util/rpdb.py#L317

but we didn't change usages of it in two places:
https://github.com/ray-project/ray/blob/00152a4b4b732d59bd2656480f4dc41f213b1156/python/ray/_raylet.pyx#L575-L577

https://github.com/ray-project/ray/blob/00152a4b4b732d59bd2656480f4dc41f213b1156/python/ray/serve/_private/replica.py#L463-L464

This breaks debugging with `RAY_PDB=1` for many common failure cases, such as when there is a task error (as a user reported). We should make sure to fix this with good tests, these codepaths apparently don't have test coverage!

**Comment by cadedaniel** [comment]
The workaround is to rename `_post_mortem` to `post_mortem` in `rpdb.py`.

**Comment by cadedaniel** [comment]
This impacted a user, bumping to 2.3 unless we have a good reason otherwise.

**Comment by architkulkarni** [comment]
Ran into this independently.

Reproduction script:
```
import ray

ray.init()

@ray.remote
def compute():
    return 5/0

compute.remote()
```

```RAY_PDB=1 python script.py```


<details>
  <summary>Traceback</summary>

```
2022-12-30 15:04:15,052 INFO worker.py:1536 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265 
2022-12-30 15:04:17,672 WARNING worker.py:1858 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 842, in ray._raylet.execute_task
    with core_worker.profile_event(b"task:execute"):
  File "python/ray/_raylet.pyx", line 894, in ray._raylet.execute_task
    raise e
  File "python/ray/_raylet.pyx", line 849, in ray._raylet.execute_task
    with ray._private.worker._changeproctitle(title, next_title):
  File "python/ray/_raylet.pyx", line 853, in ray._raylet.execute_task
    outputs = function_executor(*args, **kwargs)
  File "serve_debugging.py", line 7, in compute
    return 5/0
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1154, in ray._raylet.task_execution_handler
    execute_task_with_cancellation_handler(
  File "python/ray/_raylet.pyx", line 1064, in ray._raylet.execute_task_with_cancellation_handler
    execute_task(caller_address,
  File "python/ray/_raylet.pyx", line 792, in ray._raylet.execute_task
    with core_worker.profile_event(b"task::" + name, extra_data=extra_data):
  File "python/ray/_raylet.pyx", line 964, in ray._raylet.execute_task
    num_errors_stored = store_task_errors(
  File "python/ray/_raylet.pyx", line 577, in ray._raylet.store_task_errors
    ray.util.pdb.post_mortem()
AttributeError: module 'ray.util.rpdb' has no attribute 'post_mortem'
An unexpected internal error occurred while the worker was executing a task.
2022-12-30 15:04:17,674 WARNING worker.py:1858 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 6e89b6400e66abd72e7e0f023c26cc9c81807da001000000 Worker ID: a1f4fadf264b6bb56049afdcd60e2251a6c0f7d9efccba6a50ee4d24 Node ID: e29f7c16f1685c8ae2a4aa02239a981d7524fe528a04ebbf112fd7a2 Worker IP address: 127.0.0.1 Worker port: 65050 Worker PID: 63923 Worker exit type: SYSTEM_ERROR Worker exit detail: The leased worker has unrecoverable failure. Worker is requested to be destroyed when it is returned.
(compute pid=63923) 2022-12-30 15:04:17,671     ERROR worker.py:767 -- Worker exits with an exit code None.
(compute pid=63923)  Traceback (most recent call last):
(compute pid=63923)   File "python/ray/_raylet.pyx", line 842, in ray._raylet.execute_task
(compute pid=63923)     with core_worker.profile_event(b"task:execute"):
(compute pid=63923)   File "python/ray/_raylet.pyx", line 894, in ray._raylet.execute_task
(compute pid=63923)     raise e
(compute pid=63923)   File "python/ray/_raylet.pyx", line 849, in ray._raylet.execute_task
(compute pid=63923)     with ray._private.worker._changeproctitle(title, next_title):
(compute pid=63923)   File "python/ray/_raylet.pyx", line 853, in ray._raylet.execute_task
(compute pid=63923)     outputs = function_executor(*args, **kwargs)
(compute pid=63923)   File "serve_debugging.py", line 7, in compute
(compute pid=63923)     return 5/0
(compute pid=63923) ZeroDivisionError: division by zero
(compute pid=63923) 
(compute pid=63923) During handling of the above exception, another exception occurred:
(compute pid=63923) 
(compute pid=63923) Traceback (most recent call last):
(compute pid=63923)   File "python/ray/_raylet.pyx", line 1154, in ray._raylet.task_execution_handler
(compute pid=63923)     execute_task_with_cancellation_handler(
(compute pid=63923)   File "python/ray/_raylet.pyx", line 1064, in ray._raylet.execute_task_with_cancellation_handler
(compute pid=63923)     execute_task(caller_address,
(compute pid=63923)   File "python/ray/_raylet.pyx", line 792, in ray._raylet.execute_task
(compute pid=63923)     with core_worker.profile_event(b"task::" + name, extra_data=extra_data):
(compute pid=63923)   File "python/ray/_raylet.pyx", line 964, in ray._raylet.execute_task
(compute pid=63923)     num_errors_stored = store_task_errors(
(compute pid=63923)   File "python/ray/_raylet.pyx", line 577, in ray._raylet.store_task_errors
(compute pid=63923)     ray.util.pdb.post_mortem()
(compute pid=63923) AttributeError: module 'ray.util.rpdb' has no attribute 'post_mortem'
(compute pid=63923) An unexpected internal error occurred while the worker was executing a task.
(compute pid=63923) Traceback (most recent call last):
(compute pid=63923)   File "python/ray/_raylet.pyx", line 842, in ray._raylet.execute_task
(compute pid=63923)     with core_worker.profile_event(b"task:execute"):
(compute pid=63923)   File "python/ray/_raylet.pyx", line 894, in ray._raylet.execute_task
(compute pid=63923)     raise e
(compute pid=63923)   File "python/ray/_raylet.pyx", line 849, in ray._raylet.execute_task
(compute pid=63923)     with ray._private.worker._changeproctitle(title, next_title):
(compute pid=63923)   File "python/ray/_raylet.pyx", line 853, in ray._raylet.execute_task
(compute pid=63923)     outputs = function_executor(*args, **kwargs)
(compute pid=63923)   File "serve_debugging.py", line 7, in compute
(compute pid=63923)     return 5/0
(compute pid=63923) ZeroDivisionError: division by zero
(compute pid=63923) 
(compute pid=63923) During handling of the above exception, another exception occurred:
(compute pid=63923) 
(compute pid=63923) Traceback (most recent call last):
(compute pid=63923)   File "python/ray/_raylet.pyx", line 1154, in ray._raylet.task_execution_handler
(compute pid=63923)     execute_task_with_cancellation_handler(
(compute pid=63923)   File "python/ray/_raylet.pyx", line 1064, in ray._raylet.execute_task_with_cancellation_handler
(compute pid=63923)     execute_task(caller_address,
(compute pid=63923)   File "python/ray/_raylet.pyx", line 792, in ray._raylet.execute_task
(compute pid=63923)     with core_worker.profile_event(b"task::" + name, extra_data=extra_data):
(compute pid=63923)   File "python/ray/_raylet.pyx", line 964, in ray._raylet.execute_task
(compute pid=63923)     num_errors_stored = store_task_errors(
(compute pid=63923)   File "python/ray/_raylet.pyx", line 577, in ray._raylet.store_task_errors
(compute pid=63923)     ray.util.pdb.post_mortem()
(compute pid=63923) AttributeError: module 'ray.util.rpdb' has no attribute 'post_mortem'
(compute pid=63923) 
(compute pid=63923) During handling of the above exception, another exception occurred:
(compute pid=63923) 
(compute pid=63923) Traceback (most recent call last):
(compute pid=63923)   File "python/ray/_raylet.pyx", line 1195, in ray._raylet.task_execution_handler
(compute pid=63923)     raise sys_exit
(compute pid=63923) SystemExit
```

</details>
