### ISSUE TITLE
No worker logs in the dashboard after recreating the K8S Ray pods

### ISSUE THREAD

**Issue by YQ-Wang** [ray-project/ray#31288]
### What happened + What you expected to happen

After deleted the pods and restarted the pods using the preserved data from Redis, the Ray job worker logs no longer get exported to the dashboard. 
It returns the following error when using the get_job_logs API:
```
Traceback (most recent call last):
  File "test.py", line 64, in <module>
    logs = client.get_job_logs(job_id)
  File "/Users/yiqingwang/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ray/dashboard/modules/job/sdk.py", line 341, in get_job_logs
    self._raise_error(r)
  File "/Users/yiqingwang/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 260, in _raise_error
    f"Request failed with status code {r.status_code}: {r.text}."
RuntimeError: Request failed with status code 500: Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/home/ray/anaconda3/lib/python3.7/asyncio/base_events.py", line 962, in create_connection
    raise exceptions[0]
  File "/home/ray/anaconda3/lib/python3.7/asyncio/base_events.py", line 949, in create_connection
    await self.sock_connect(sock, address)
  File "/home/ray/anaconda3/lib/python3.7/asyncio/selector_events.py", line 473, in sock_connect
    return await fut
  File "/home/ray/anaconda3/lib/python3.7/asyncio/selector_events.py", line 503, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('10.0.35.85', 52365)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/job_head.py", line 464, in get_job_logs
    resp = await job_agent_client.get_job_logs_internal(job.submission_id)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/job_head.py", line 113, in get_job_logs_internal
    f"{self._agent_address}/api/job_agent/jobs/{job_id}/logs"
  File "/home/ray/anaconda3/lib/python3.7/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/home/ray/anaconda3/lib/python3.7/site-packages/aiohttp/client.py", line 536, in _request
    req, traces=traces, timeout=real_timeout
  File "/home/ray/anaconda3/lib/python3.7/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/home/ray/anaconda3/lib/python3.7/site-packages/aiohttp/connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 10.0.35.85:52365 ssl:default [Connect call failed ('10.0.35.85', 52365)]
```
The worker dashboard agent logs contain this error
```
182022-12-21 13:22:26,046	ERROR event_agent.py:85 -- Report event failed, reconnect to the dashboard.1119Traceback (most recent call last):1120  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/event/event_agent.py", line 81, in report_events1121    await self._stub.ReportEvents(request)1122  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/aio/_call.py", line 286, in __await__1123    self._cython_call._status)1124grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:1125	status = StatusCode.UNAVAILABLE1126	details = "failed to connect to all addresses"1127	debug_error_string = "{"created":"@1671657746.044145704","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5390,"referenced_errors":[{"created":"@1671657746.044142142","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"1128>

```

### Versions / Dependencies

We set up the static Ray cluster with an external Redis in K8S.
Ray 2.2.0
Python 3.7

### Reproduction script

If you delete the Ray pods (both head and worker) and recreate Ray pods using the preserved metadata from Redis in the K8S, you will find the newly submitted jobs have no logs from the worker.

### Issue Severity

High: It blocks me from completing my task.

**Comment by cszhu** [comment]
This P2 issue has seen no activity in the past 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please comment and remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
