### ISSUE TITLE
Object store running out of memory.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#313]
I ran into the following problem today in a friend's experiment (on Ubuntu using Python 2). The code had the structure

```python
import ray
import numpy as np

ray.init()

@ray.remote
def f():
  return np.zeros(10000000)

results = []
for i in range(100):
  print(i)
  results += ray.get([f.remote() for _ in range(50)])
```

On my machine, this script throws an exception. The beginning of the output looks like this.

```
0
1
2
3
[INFO] (/Users/rkn/Workspace/ray/src/plasma/eviction_policy.c:178) There is not enough space to create this object, so evicting 0 objects to free up 0 bytes.
Remote function __main__.f failed with:

Traceback (most recent call last):
  File "/Users/rkn/Workspace/ray/python/ray/worker.py", line 1602, in process_task
    store_outputs_in_objstore(return_object_ids, outputs, worker)
  File "/Users/rkn/Workspace/ray/python/ray/worker.py", line 1952, in store_outputs_in_objstore
    worker.put_object(objectids[i], outputs[i])
  File "/Users/rkn/Workspace/ray/python/ray/worker.py", line 441, in put_object
    numbuf.store_list(objectid.id(), self.plasma_client.conn, [value])
numbuf_plasma_out_of_memory.error: The plasma store ran out of memory and could not create this object.


You can inspect errors by running

    ray.error_info()

If this driver is hanging, start a new one with

    ray.init(redis_address="127.0.0.1:25397")
```

Normally, when the object store fills up, it begins evicting objects that are not in use (in a least-recently used fashion). However, because all of the objects are numpy arrays that are being held in the `results` list, they are all still in use, and the memory that those numpy arrays live in is actually in the object store, so they are taking up space in the object store. The object store can't evict them until those objects go out of scope.

We got around this by changing the script to something like the following.

```python
import ray
import numpy as np

ray.init()

@ray.remote
def f():
  return np.zeros(10000000)

results = []
for i in range(100):
  print(i)
  values = ray.get([f.remote() for _ in range(50)])
  values = [np.array(value, copy=True) for value in values]
  results += values
```

This copies the numpy arrays so that the copies backed by the object store memory go out of scope and so the object store can evict those objects.

Of course, the program will eventually run out of memory, but at least the object store will be able to evict stuff. The object store size on Ubuntu was limited to the size of `/dev/shm` which is typically half the amount of memory.

The output of this version on my machine is the following (before the machine runs out of memory).

```
0
1
2
3
[INFO] (/Users/rkn/Workspace/ray/src/plasma/eviction_policy.c:178) There is not enough space to create this object, so evicting 35 objects to free up 2800041720 bytes.
4
[INFO] (/Users/rkn/Workspace/ray/src/plasma/eviction_policy.c:178) There is not enough space to create this object, so evicting 35 objects to free up 2800041720 bytes.
[INFO] (/Users/rkn/Workspace/ray/src/plasma/eviction_policy.c:178) There is not enough space to create this object, so evicting 35 objects to free up 2800041720 bytes.
5
[INFO] (/Users/rkn/Workspace/ray/src/plasma/eviction_policy.c:178) There is not enough space to create this object, so evicting 35 objects to free up 2800041720 bytes.
```

**Comment by robertnishihara** [comment]
Closing for now. We need to provide better documentation about how object store eviction works.
