### ISSUE TITLE
ray-ml docker images - TypeError: Descriptors cannot not be created directly

### ISSUE THREAD

**Issue by tekumara** [ray-project/ray#31309]
### What happened + What you expected to happen

When running [the mnist example](https://docs.ray.io/en/latest/train/examples/tensorflow_mnist_example.html) on a cluster using the [rayproject/ray-ml:2.2.0-py39-cpu docker image](https://hub.docker.com/layers/rayproject/ray-ml/2.2.0-py39-cpu/images/sha256-f1dc562c594fc4f10d7e6f17802080764eecee35820367a7b7a37003e50ec55f?context=explore):

```
❯ python -m rayexample.tf_mnist --address ray://localhost:10001
2022-12-23 06:43:11.853279: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-23 06:43:13.950258: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/extras/CUPTI/lib64:
2022-12-23 06:43:13.950867: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/extras/CUPTI/lib64:
2022-12-23 06:43:13.950897: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
/home/compute/code/ray-demo/rayexample/tf_mnist.py:12: DeprecationWarning: The module `ray.air.callbacks.keras` has been moved to `ray.air.integrations.keras` and the old location will be deprecated soon. Please adjust your imports to point to the new location. Example: Do a global search and replace `ray.air.callbacks.keras` with `ray.air.integrations.keras`.
  from ray.air.callbacks.keras import Callback as TrainReportCallback
Put failed:
2022-12-23 06:43:22,678 ERROR worker.py:512 -- Failed to deserialize b'\x80\x05\x953\x02\x00\x00\x00\x00\x00\x00\x8c\x08builtins\x94\x8c\tTypeError\x94\x93\x94X\x0f\x02\x00\x00Descriptors cannot not be created directly.\nIf this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.\nIf you cannot immediately regenerate your protos, some other possible workarounds are:\n 1. Downgrade the protobuf package to 3.20.x or lower.\n 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).\n\nMore information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates\x94\x85\x94R\x94.'
Traceback (most recent call last):
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/util/client/worker.py", line 510, in _put_pickled
    raise cloudpickle.loads(resp.error)
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/compute/code/ray-demo/rayexample/tf_mnist.py", line 124, in <module>
    train_tensorflow_mnist(
  File "/home/compute/code/ray-demo/rayexample/tf_mnist.py", line 86, in train_tensorflow_mnist
    results = trainer.fit()
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/train/base_trainer.py", line 352, in fit
    trainable = self.as_trainable()
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/train/base_trainer.py", line 508, in as_trainable
    return tune.with_parameters(trainable_cls, **base_config)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/tune/trainable/util.py", line 355, in with_parameters
    parameter_registry.put(prefix + k, v)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/tune/registry.py", line 229, in put
    self.flush()
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/tune/registry.py", line 241, in flush
    self.references[k] = ray.put(v)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/util/client/api.py", line 52, in put
    return self.worker.put(*args, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/util/client/worker.py", line 496, in put
    return self._put_pickled(data, client_ref_id, _owner)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/util/client/worker.py", line 510, in _put_pickled
    raise cloudpickle.loads(resp.error)
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

### Versions / Dependencies

Client:
```
❯ pip list | grep proto
protobuf                     3.19.6
```

Head node using [rayproject/ray-ml:2.2.0-py39-cpu docker image](https://hub.docker.com/layers/rayproject/ray-ml/2.2.0-py39-cpu/images/sha256-f1dc562c594fc4f10d7e6f17802080764eecee35820367a7b7a37003e50ec55f?context=explore):
```
(base) ray@raycluster-kuberay-head-sr4hx:~$ pip list | grep protobuf
protobuf                               4.21.10
```

### Reproduction script

```
docker run --rm -it --entrypoint python rayproject/ray-ml:2.2.0-py39-cpu -c "from ray.train.tensorflow import TensorflowTrainer"

2022-12-23 00:04:36.973251: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-12-23 00:04:36.973301: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/tensorflow/__init__.py", line 3, in <module>
    import tensorflow as tf  # noqa: F401
  File "/home/ray/anaconda3/lib/python3.9/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/ray/anaconda3/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/home/ray/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/home/ray/anaconda3/lib/python3.9/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/ray/anaconda3/lib/python3.9/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/ray/anaconda3/lib/python3.9/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/ray/anaconda3/lib/python3.9/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/home/ray/anaconda3/lib/python3.9/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by bveeramani** [comment]
Hey @tekumara, thanks for opening this issue!

I was able to reproduce the issue on my laptop.

```
(base) ray@bc374d4a3514:~$ pip freeze | grep protobuf
protobuf==4.21.10
```

The protobuf version is `4.21.10`, but it should be `3.20.3`.

I'll look into this and try to identify the underlying issue. In the meantime, either of the suggested workarounds should be okay:
> If you cannot immediately regenerate your protos, some other possible workarounds are:
> 1. Downgrade the protobuf package to 3.20.x or lower.
> 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

**Comment by matthewdeng** [comment]
Hey @tekumara, thanks for bringing this up. 

I was able to reproduce this with the following:

1. Create `minimal.yaml`.
```yaml
cluster_name: minimal

provider:
    type: aws
    region: us-west-1

docker:
    image: rayproject/ray-ml:2.2.0-py39-cpu
    container_name: ray_container
```

2. Run the following commands.
```bash
# Start cluster.
~ ray up -y minimal.yaml

# Attach to the cluster.
~ ray attach minimal.yaml

# Import tensorflow.
(base) ray@ip-10-0-1-116:~$ python -c "import tensorflow"
```

While `ray` has been updated to support the latest `protobuf`, `tensorflow` seems to be generated with an older version of `protobuf` and is not yet compatible. I would have expected the Docker image to be generated with a version that satisfies the criteria of both libraries, and will need to dig a little deeper to understand why that's not the case. cc @scv119  FYI

**Comment by matthewdeng** [comment]
I think this may be because we're using the `legacy-resolver` to install the ML extras.

https://github.com/ray-project/ray/blob/037806a121d55557b07413676438396ac24098fd/docker/ray-ml/Dockerfile#L29-L35

@krfricke do you know what would happen if we didn't use the legacy pip resolver?

**Comment by Yicheng-Lu-llll** [comment]
Hi, I am wondering if there is any update on this issue. kuberay is facing the same issue: [#873.](https://github.com/ray-project/kuberay/issues/873)

**Comment by krfricke** [comment]
We're working on a resolution for affected images. I'll keep this thread updated.

See also e.g. https://github.com/ray-project/ray/issues/31855 and https://github.com/ray-project/ray/issues/31719

**Comment by krfricke** [comment]
I've manually downgraded protobuf to <3.21 in the latest release images.

All updated tags:

```
['2.2.0', '2.2.0-cpu', '2.2.0-cu116', '2.2.0-gpu', '2.2.0-gpu', '2.2.0-py310', '2.2.0-py310-cpu', '2.2.0-py310-cu116', '2.2.0-py310-gpu', '2.2.0-py310-gpu', '2.2.0-py311', '2.2.0-py311-cpu', '2.2.0-py311-cu116', '2.2.0-py311-gpu', '2.2.0-py311-gpu', '2.2.0-py37', '2.2.0-py37-cpu', '2.2.0-py37-cu116', '2.2.0-py37-gpu', '2.2.0-py37-gpu', '2.2.0-py38', '2.2.0-py38-cpu', '2.2.0-py38-cu116', '2.2.0-py38-gpu', '2.2.0-py38-gpu', '2.2.0-py39', '2.2.0-py39-cpu', '2.2.0-py39-cu116', '2.2.0-py39-gpu', '2.2.0-py39-gpu', 'latest', 'latest-cpu', 'latest-cu116', 'latest-gpu', 'latest-gpu', 'latest-py310', 'latest-py310-cpu', 'latest-py310-cu116', 'latest-py310-gpu', 'latest-py310-gpu', 'latest-py311', 'latest-py311-cpu', 'latest-py311-cu116', 'latest-py311-gpu', 'latest-py311-gpu', 'latest-py37', 'latest-py37-cpu', 'latest-py37-cu116', 'latest-py37-gpu', 'latest-py37-gpu', 'latest-py38', 'latest-py38-cpu', 'latest-py38-cu116', 'latest-py38-gpu', 'latest-py38-gpu', 'latest-py39', 'latest-py39-cpu', 'latest-py39-cu116', 'latest-py39-gpu', 'latest-py39-gpu']
```

**Comment by Stack-Attack** [comment]
@krfricke It seems when pulling the rayproject/ray-ml:nightly-cpu or :latest images that the protobuff version is still 4.22.0

Unfortunately I'm getting this error still, specifically when importing transformers.pipeline:
