### ISSUE TITLE
RLlib readme quick start issues

### ISSUE THREAD

**Issue by TeamDman** [ray-project/ray#31321]
### Description

Tried the instructions from the README

From the docs:
```
$ conda create -n rllib python=3.8
$ conda activate rllib
$ pip install "ray[rllib]" torch "gym[atari]" "gym[accept-rom-license]" atari_py
$ # Run a test job:
$ rllib train --run APPO --env CartPole-v0 --torch
```

My console:
```
$ conda activate rllib
$ pip install "ray[rllib]" torch "gym[atari]" "gym[accept-rom-license]" atari_py
```

```
$ rllib train --run APPO --env CartPole-v0 --torch
C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\tune\logger\tensorboardx.py:35: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  VALID_NP_HPARAMS = (np.bool8, np.float32, np.float64, np.int32, np.int64)
C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\skimage\util\dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
Usage: rllib train [OPTIONS] COMMAND [ARGS]...
Try 'rllib train --help' for help.
╭─ Error ──────────────────────────────────────╮
│ No such option: --torch (Possible options: --restore, --stop, --trace)

```

Looks like the `--torch` option had changed, so I used the help command to find the new flag
```
$ rllib train --help | select-string torch
C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\tune\logger\tensorboardx.py:35: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  VALID_NP_HPARAMS = (np.bool8, np.float32, np.float64, np.int32, np.int64)
C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\skimage\util\dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),

| --framework                                [tf|tf2|torch]  The identifier   |
|                                                            PyTorch          |
|                                                            ('torch').       |
```

and still encountered issues

```
$ rllib train --run APPO --env CartPole-v0 --framework torch
C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\tune\logger\tensorboardx.py:35: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  VALID_NP_HPARAMS = (np.bool8, np.float32, np.float64, np.int32, np.int64)
C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\skimage\util\dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
2022-12-25 22:31:26,619 INFO worker.py:1538 -- Started a local Ray instance.
...
ModuleNotFoundError: No module named 'tensorflow_probability'
```

So I had to install the `tensorflow_probability` module

```
$ pip install tensorflow_probability
Collecting tensorflow_probability
  Downloading tensorflow_probability-0.19.0-py2.py3-none-any.whl (6.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 10.2 MB/s eta 0:00:00
Requirement already satisfied: dm-tree in c:\users\teamd\.conda\envs\rllib\lib\site-packages (from tensorflow_probability) (0.1.8)
Collecting decorator
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Requirement already satisfied: cloudpickle>=1.3 in c:\users\teamd\.conda\envs\rllib\lib\site-packages (from tensorflow_probability) (2.2.0)
Collecting absl-py
  Downloading absl_py-1.3.0-py3-none-any.whl (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.6/124.6 kB 7.1 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.13.3 in c:\users\teamd\.conda\envs\rllib\lib\site-packages (from tensorflow_probability) (1.24.0)
Requirement already satisfied: six>=1.10.0 in c:\users\teamd\.conda\envs\rllib\lib\site-packages (from tensorflow_probability) (1.16.0)
Collecting gast>=0.3.2
  Downloading gast-0.5.3-py3-none-any.whl (19 kB)
Installing collected packages: gast, decorator, absl-py, tensorflow_probability
Successfully installed absl-py-1.3.0 decorator-5.1.1 gast-0.5.3 tensorflow_probability-0.19.0
```

and still had errors, this time about `pygame`

```
$ rllib train --run APPO --env CartPole-v0 --framework torch
C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\tune\logger\tensorboardx.py:35: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  VALID_NP_HPARAMS = (np.bool8, np.float32, np.float64, np.int32, np.int64)
C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\skimage\util\dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
2022-12-25 22:34:45,476 INFO worker.py:1538 -- Started a local Ray instance.
(pid=23012) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\tune\logger\tensorboardx.py:35: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=23012)   VALID_NP_HPARAMS = (np.bool8, np.float32, np.float64, np.int32, np.int64)
(pid=23012) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\skimage\util\dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=23012)   np.bool8: (False, True),
(APPO pid=23012) 2022-12-25 22:34:52,010        WARNING algorithm_config.py:488 -- Cannot create APPOConfig from given `config_dict`! Property __stdout_file__ not supported.
(APPO pid=23012) 2022-12-25 22:34:52,013        INFO algorithm.py:501 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=26244) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\tune\logger\tensorboardx.py:35: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=26244)   VALID_NP_HPARAMS = (np.bool8, np.float32, np.float64, np.int32, np.int64)
(pid=18668) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\tune\logger\tensorboardx.py:35: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=18668)   VALID_NP_HPARAMS = (np.bool8, np.float32, np.float64, np.int32, np.int64)
(pid=26244) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\skimage\util\dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=26244)   np.bool8: (False, True),
(pid=18668) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\skimage\util\dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=18668)   np.bool8: (False, True),
== Status ==
Current time: 2022-12-25 22:34:56 (running for 00:00:09.79)
Memory usage on this node: 16.9/31.9 GiB
Using FIFO scheduling algorithm.
Resources requested: 3.0/12 CPUs, 0/0 GPUs, 0.0/9.85 GiB heap, 0.0/4.93 GiB objects
Result logdir: C:\Users\TeamD\ray_results\default
Number of trials: 1/1 (1 RUNNING)


2022-12-25 22:34:56,898 ERROR trial_runner.py:1088 -- Trial APPO_CartPole-v0_3ed67_00000: Error processing event.
ray.tune.error._TuneNoNextExecutorEventError: Traceback (most recent call last):
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\tune\execution\ray_trial_executor.py", line 1070, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\_private\worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::APPO.__init__() (pid=23012, ip=127.0.0.1, repr=APPO)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 239, in _setup
    self.add_workers(
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 612, in add_workers
    raise result.get()
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\utils\actor_manager.py", line 473, in __fetch_result
    result = ray.get(r)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\_private\worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=26244, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000025506E5CA90>)
  File "python\ray\_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\_private\function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 585, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\env\utils.py", line 50, in _gym_env_creator
    return gym.make(env_descriptor, **env_context)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\gym\envs\registration.py", line 676, in make
    return registry.make(id, **kwargs)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\gym\envs\registration.py", line 520, in make
    return spec.make(**kwargs)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\gym\envs\registration.py", line 139, in make
    cls = load(self.entry_point)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\gym\envs\registration.py", line 55, in load
    mod = importlib.import_module(mod_name)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\gym\envs\classic_control\__init__.py", line 1, in <module>
    from gym.envs.classic_control.cartpole import CartPoleEnv
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\gym\envs\classic_control\cartpole.py", line 10, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'

During handling of the above exception, another exception occurred:

ray::APPO.__init__() (pid=23012, ip=127.0.0.1, repr=APPO)
  File "python\ray\_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\_private\function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\algorithms\appo\appo.py", line 201, in __init__
    super().__init__(config, *args, **kwargs)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 441, in __init__
    super().__init__(
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\tune\trainable\trainable.py", line 169, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\algorithms\appo\appo.py", line 210, in setup
    super().setup(config)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\algorithms\impala\impala.py", line 464, in setup
    super().setup(config)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 566, in setup
    self.workers = WorkerSet(
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 191, in __init__
    raise e.args[0].args[2]
ModuleNotFoundError: No module named 'pygame'
...
TuneError: ('Trials did not complete', [APPO_CartPole-v0_3ed67_00000])
```

So I installed pygame

```
$ pip install pygame
Collecting pygame
  Downloading pygame-2.1.2-cp38-cp38-win_amd64.whl (8.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 10.6 MB/s eta 0:00:00
Installing collected packages: pygame
Successfully installed pygame-2.1.2
```

Then I ran into https://github.com/ray-project/ray/issues/31293

```
$ rllib train --run APPO --env CartPole-v0 --framework torch
C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\tensorflow\python\framework\dtypes.py:246: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:326: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\tune\logger\tensorboardx.py:35: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  VALID_NP_HPARAMS = (np.bool8, np.float32, np.float64, np.int32, np.int64)
C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\skimage\util\dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\tensorflow_probability\python\__init__.py:57: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if (distutils.version.LooseVersion(tf.__version__) <
2022-12-25 22:42:45,146 INFO worker.py:1538 -- Started a local Ray instance.
(pid=3516) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\tensorflow\python\framework\dtypes.py:246: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=3516)   np.bool8: (False, True),
(pid=3516) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:326: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=3516)   np.bool8: (False, True),
(pid=3516) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\tune\logger\tensorboardx.py:35: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=3516)   VALID_NP_HPARAMS = (np.bool8, np.float32, np.float64, np.int32, np.int64)
(pid=3516) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\skimage\util\dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=3516)   np.bool8: (False, True),
(pid=3516) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\tensorflow_probability\python\__init__.py:57: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
(pid=3516)   if (distutils.version.LooseVersion(tf.__version__) <
(APPO pid=3516) 2022-12-25 22:42:54,250 WARNING algorithm_config.py:488 -- Cannot create APPOConfig from given `config_dict`! Property __stdout_file__ not supported.
(APPO pid=3516) 2022-12-25 22:42:54,253 INFO algorithm.py:501 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=22748) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\tensorflow\python\framework\dtypes.py:246: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=22748)   np.bool8: (False, True),
(pid=12952) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\tensorflow\python\framework\dtypes.py:246: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=12952)   np.bool8: (False, True),
(pid=22748) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:326: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=22748)   np.bool8: (False, True),
(pid=12952) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:326: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=12952)   np.bool8: (False, True),
(pid=22748) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\tune\logger\tensorboardx.py:35: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=22748)   VALID_NP_HPARAMS = (np.bool8, np.float32, np.float64, np.int32, np.int64)
(pid=12952) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\tune\logger\tensorboardx.py:35: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=12952)   VALID_NP_HPARAMS = (np.bool8, np.float32, np.float64, np.int32, np.int64)
(pid=22748) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\skimage\util\dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=22748)   np.bool8: (False, True),
(pid=12952) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\skimage\util\dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
(pid=12952)   np.bool8: (False, True),
(pid=22748) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\tensorflow_probability\python\__init__.py:57: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
(pid=22748)   if (distutils.version.LooseVersion(tf.__version__) <
(pid=12952) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\tensorflow_probability\python\__init__.py:57: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
(pid=12952)   if (distutils.version.LooseVersion(tf.__version__) <
== Status ==
Current time: 2022-12-25 22:43:01 (running for 00:00:15.22)
Memory usage on this node: 17.4/31.9 GiB
Using FIFO scheduling algorithm.
Resources requested: 3.0/12 CPUs, 0/0 GPUs, 0.0/9.78 GiB heap, 0.0/4.89 GiB objects
Result logdir: C:\Users\TeamD\ray_results\default
Number of trials: 1/1 (1 RUNNING)


2022-12-25 22:43:01,969 ERROR trial_runner.py:1088 -- Trial APPO_CartPole-v0_5cb96_00000: Error processing event.
ray.tune.error._TuneNoNextExecutorEventError: Traceback (most recent call last):
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\tune\execution\ray_trial_executor.py", line 1070, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\_private\worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::APPO.__init__() (pid=3516, ip=127.0.0.1, repr=APPO)
  File "python\ray\_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\_private\function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\algorithms\appo\appo.py", line 201, in __init__
    super().__init__(config, *args, **kwargs)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 441, in __init__
    super().__init__(
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\tune\trainable\trainable.py", line 169, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\algorithms\appo\appo.py", line 210, in setup
    super().setup(config)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\algorithms\impala\impala.py", line 464, in setup
    super().setup(config)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 566, in setup
    self.workers = WorkerSet(
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 169, in __init__
    self._setup(
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 253, in _setup
    spaces = self._get_spaces_from_remote_worker()
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 279, in _get_spaces_from_remote_worker
    remote_spaces = self.foreach_worker(
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 696, in foreach_worker
    handle_remote_call_result_errors(remote_results, self._ignore_worker_failures)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 73, in handle_remote_call_result_errors
    raise r.get()
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\rllib\utils\actor_manager.py", line 473, in __fetch_result
    result = ray.get(r)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\_private\worker.py", line 2311, in get
    raise value
ray.exceptions.RaySystemError: System error: _generator_ctor() takes from 0 to 1 positional arguments but 2 were given
traceback: Traceback (most recent call last):
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\_private\serialization.py", line 369, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\_private\serialization.py", line 252, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\_private\serialization.py", line 207, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\ray\_private\serialization.py", line 195, in _deserialize_pickle5_data
    obj = pickle.loads(in_band, buffers=buffers)
TypeError: _generator_ctor() takes from 0 to 1 positional arguments but 2 were given
...
TuneError: ('Trials did not complete', [APPO_CartPole-v0_5cb96_00000])
```

So I had to downgrade numpy

```
$ pip install numpy==1.23.5
Collecting numpy==1.23.5
  Downloading numpy-1.23.5-cp38-cp38-win_amd64.whl (14.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.7/14.7 MB 11.3 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.0
    Uninstalling numpy-1.24.0:
      Successfully uninstalled numpy-1.24.0
Successfully installed numpy-1.23.5
```

and finally it started training

```
$ rllib train --run APPO --env CartPole-v0 --framework torch
C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\tensorflow_probability\python\__init__.py:57: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if (distutils.version.LooseVersion(tf.__version__) <
2022-12-25 22:45:35,467 INFO worker.py:1538 -- Started a local Ray instance.
(pid=22748) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\tensorflow_probability\python\__init__.py:57: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
(pid=22748)   if (distutils.version.LooseVersion(tf.__version__) <
(APPO pid=22748) 2022-12-25 22:45:44,645        WARNING algorithm_config.py:488 -- Cannot create APPOConfig from given `config_dict`! Property __stdout_file__ not supported.
(APPO pid=22748) 2022-12-25 22:45:44,648        INFO algorithm.py:501 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=16556) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\tensorflow_probability\python\__init__.py:57: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
(pid=16556)   if (distutils.version.LooseVersion(tf.__version__) <
(pid=22324) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\tensorflow_probability\python\__init__.py:57: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
(pid=22324)   if (distutils.version.LooseVersion(tf.__version__) <
(RolloutWorker pid=16556) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\gym\envs\registration.py:505: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1` with the environment ID `CartPole-v1`.
(RolloutWorker pid=16556)   logger.warn(
(RolloutWorker pid=22324) C:\Users\TeamD\.conda\envs\rllib\lib\site-packages\gym\envs\registration.py:505: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1` with the environment ID `CartPole-v1`.
(RolloutWorker pid=22324)   logger.warn(
== Status ==
Current time: 2022-12-25 22:45:52 (running for 00:00:15.28)
Memory usage on this node: 17.5/31.9 GiB
Using FIFO scheduling algorithm.
Resources requested: 3.0/12 CPUs, 0/0 GPUs, 0.0/9.71 GiB heap, 0.0/4.85 GiB objects
Result logdir: C:\Users\TeamD\ray_results\default
Number of trials: 1/1 (1 RUNNING)


(APPO pid=22748) 2022-12-25 22:45:52,344        WARNING util.py:66 -- Install gputil for GPU system monitoring.
(RolloutWorker pid=16556) 2022-12-25 22:45:52,279       WARNING env.py:159 -- Your env reset() method appears to take 'seed' or 'return_info' arguments. Note that these are not yet supported in RLlib. Seeding will take place using 'env.seed()' and the info dict will not be returned from reset.
(APPO pid=22748) 2022-12-25 22:45:52,416        WARNING deprecation.py:47 -- DeprecationWarning: `concat_samples` has been deprecated. Use `concat_samples() from rllib.policy.sample_batch` instead. This will raise an error in the future!
== Status ==
Current time: 2022-12-25 22:45:57 (running for 00:00:20.33)
Memory usage on this node: 17.5/31.9 GiB
Using FIFO scheduling algorithm.
Resources requested: 3.0/12 CPUs, 0/0 GPUs, 0.0/9.71 GiB heap, 0.0/4.85 GiB objects
Result logdir: C:\Users\TeamD\ray_results\default
Number of trials: 1/1 (1 RUNNING)


== Status ==
Current time: 2022-12-25 22:46:02 (running for 00:00:25.41)
Memory usage on this node: 17.5/31.9 GiB
Using FIFO scheduling algorithm.
Resources requested: 3.0/12 CPUs, 0/0 GPUs, 0.0/9.71 GiB heap, 0.0/4.85 GiB objects
Result logdir: C:\Users\TeamD\ray_results\default
Number of trials: 1/1 (1 RUNNING)
```

I let it train for 4 minutes but nothing happened beyond status updates. I cancelled the job since I expected it to have finished already if everything was working.

I tried again with `--run DQN` and let that run for 16 minutes, terminating it before it finished again

Also noticed that a JSON file that was generated is invalid due to `-Infinity` which might be related to https://github.com/ray-project/ray/issues/9103
![image](https://user-images.githubusercontent.com/9356891/209498226-30965ce6-dfcb-4dae-b233-84eda412c2e9.png)

Ideally I'd be able to run the commands given as someone with zero knowledge of the framework, and would have a model trained that solves cartpole in a few minutes

I originally included more console output but hit the character limit, so here's my original post: https://hastebin.com/wojofojuce.md

### Link

https://github.com/ray-project/ray/blob/master/rllib/README.rst

(permalink) https://github.com/ray-project/ray/blob/01b19bafb224ddd2b7cc3aef557274ffb38c9c42/rllib/README.rst

**Comment by ArturNiederfahrenhorst** [comment]
Related to the tensorflow probability import: https://github.com/ray-project/ray/pull/31331

**Comment by rbeauchemin** [comment]
I just got this same error trying to use ray tune with MADDPG. Did this get resolved? I don't see a solution here.
