### ISSUE TITLE
[CI] `tune_scalability_result_throughput_cluster` is flaky due to timeout

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#31337]
https://buildkite.com/ray-project/release-tests-branch/builds/1268#0185507d-0d97-49d0-bf69-98a769879796

```
Traceback (most recent call last):
--
  | File "ray_release/scripts/run_release_test.py", line 153, in main
  | no_terminate=no_terminate,
  | File "/tmp/release-nbV1J6hSen/release/ray_release/glue.py", line 395, in run_release_test
  | raise pipeline_exception
  | File "/tmp/release-nbV1J6hSen/release/ray_release/glue.py", line 373, in run_release_test
  | handle_result(test, result)
  | File "/tmp/release-nbV1J6hSen/release/ray_release/alerts/handle.py", line 39, in handle_result
  | raise ResultsAlert(error)
  | ray_release.exception.ResultsAlert: Took too long to complete (time_taken=132.05 > 130).
  | ERROR:ray_release.logger:Took too long to complete (time_taken=132.05 > 130).
  | Traceback (most recent call last):
  | File "ray_release/scripts/run_release_test.py", line 153, in main
  | no_terminate=no_terminate,
  | File "/tmp/release-nbV1J6hSen/release/ray_release/glue.py", line 395, in run_release_test
  | raise pipeline_exception
  | File "/tmp/release-nbV1J6hSen/release/ray_release/glue.py", line 373, in run_release_test
  | handle_result(test, result)
  | File "/tmp/release-nbV1J6hSen/release/ray_release/alerts/handle.py", line 39, in handle_result
  | raise ResultsAlert(error)
  | ray_release.exception.ResultsAlert: Took too long to complete (time_taken=132.05 > 130).
```

**Comment by cadedaniel** [comment]
Did the timeout change? I am seeing a failure `--- FAILED: RESULT THROUGHPUT CLUSTER ::: 135.04 > 130.00 ---`
* https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_sfibdqaahueu8ck8vmbwmlx574?command-history-section=command_history&drivers-section=interactive-sessions
* https://buildkite.com/ray-project/release-tests-branch/builds/1311#0185eb03-8490-4a7c-b6b3-f85979553241

**Comment by cadedaniel** [comment]
cc @krfricke @bveeramani can we bump this timeout again? this is flaky and requiring retries

**Comment by cadedaniel** [comment]
Created PR https://github.com/ray-project/ray/pull/32062
