### ISSUE TITLE
[SGD] Assertion failure: assert len(gv_list) == num_gv if TRAINABLE_VARIABLES is used

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#3136]
The following script:

```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf

import argparse
import ray

from ray.experimental.sgd.sgd import DistributedSGD

class TestModel(object):

    def __init__(self, session):
        self._sess = session

        W1 = tf.Variable(tf.ones([1, 100000]))
        W2 = tf.Variable(tf.ones([1, 100000]))
        self.loss = tf.reduce_mean(W1)
        self.loss += tf.reduce_mean(W2)

        print("XXX", len(tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)))

        l2_cost = tf.add_n([tf.nn.l2_loss(v) for v in tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)])

        self.loss += l2_cost

        self.optimizer = tf.train.GradientDescentOptimizer(1e-6)

    def get_feed_dict(self):
        return dict()

parser = argparse.ArgumentParser()

parser.add_argument(
    "--num-iters", default=100, type=int, help="Number of iterations to run")

if __name__ == "__main__":
    ray.init()

    args, _ = parser.parse_known_args()

    model_creator = (
        lambda worker_idx, device_idx: TestModel(tf.Session()))

    sgd = DistributedSGD(
        model_creator,
        num_workers=2,
        devices_per_worker=2,
        use_cpus=True,
        use_plasma_op=False)

    for _ in range(args.num_iters):
        loss = sgd.step()
        print("Current loss", loss)
```

Gives the error:

```
Traceback (most recent call last):
  File "/Users/pcmoritz/ray/python/ray/worker.py", line 809, in _process_task
    self.reraise_actor_init_error()
  File "/Users/pcmoritz/ray/python/ray/worker.py", line 239, in reraise_actor_init_error
    raise self.actor_init_error
  File "/Users/pcmoritz/ray/python/ray/worker.py", line 831, in _process_task
    *arguments)
  File "/Users/pcmoritz/ray/python/ray/function_manager.py", line 481, in actor_method_executor
    method_returns = method(actor, *args)
  File "/Users/pcmoritz/ray/python/ray/experimental/sgd/sgd.py", line 77, in __init__
    agg_small_grads_max_bytes=max_bytes))
  File "/Users/pcmoritz/ray/python/ray/experimental/sgd/modified_allreduce.py", line 404, in sum_gradients_all_reduce
    tower_grads, max_bytes=agg_small_grads_max_bytes)
  File "/Users/pcmoritz/ray/python/ray/experimental/sgd/modified_allreduce.py", line 587, in pack_small_tensors
    assert len(gv_list) == num_gv
AssertionError
```

This is because the first time (i.e. when the first model is instantiaged) `tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES))` is called, it is 2 and the second time it is 4.

**Comment by pcmoritz** [comment]
The obvious solution of making this work by constructing the networks in separate graphs doesn't really work because graphs can't be merged in tensorflow, see e.g. https://stackoverflow.com/a/41371381 (there is potentially https://www.tensorflow.org/api_docs/python/tf/import_graph_def but it looks like it will be awkward/brittle).

The best solution to this I'm currently aware is to use
```
tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, scope="device_%d" % device_index)
```

This fixes the problem. I'm updating the assert with a better error message that points out the issue and links here.

**Comment by ericl** [comment]
I think the canonical way to do this
```
tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, scope=tf.get_variable_scope().name)
```

**Comment by pcmoritz** [comment]
fixed by https://github.com/ray-project/ray/pull/3139
