### ISSUE TITLE
core - ray logs CLI doesn't work for kubernetes raycluster

### ISSUE THREAD

**Issue by tekumara** [ray-project/ray#31381]
### What happened + What you expected to happen

I have port forwarded the GCS in a ray cluster in kubernetes to 127.0.0.1:6379 and the dashboard to 127.0.0.1:8265

```
$ ray logs cluster --address 127.0.0.1:6379
Traceback (most recent call last):
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa3143e7070>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.42.0.16', port=8265): Max retries exceeded with url: /api/v0/logs?node_ip=10.97.36.20&glob=%2A&timeout=30 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa3143e7070>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/compute/code/ray-demo/.venv/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/scripts/scripts.py", line 2386, in main
    return cli()
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/experimental/state/state_cli.py", line 930, in log_cluster
    logs = list_logs(
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/experimental/state/api.py", line 1250, in list_logs
    r = requests.get(
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.42.0.16', port=8265): Max retries exceeded with url: /api/v0/logs?node_ip=10.97.36.20&glob=%2A&timeout=30 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa3143e7070>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

It's trying to connect to the dashboard port on 10.42.0.16, ie: the head node's IP in the cluster, rather than 127.0.0.1. 

ray status works fine:

```
ray status --address 127.0.0.1:6379 -v
======== Autoscaler status: 2022-12-31 03:58:49.312919 ========
GCS request time: 0.001129s
Node Provider non_terminated_nodes time: 0.038014s

Node status
---------------------------------------------------------------
Healthy:
 1 workergroup
 1 head-group
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Total Usage:
 0.0/2.0 CPU
 0.00/3.725 GiB memory
 0.00/1.030 GiB object_store_memory

Total Demands:
 (no resource demands)

Node: 10.42.0.16
 Usage:
  0.00/1.863 GiB memory
  0.00/0.495 GiB object_store_memory

Node: 10.42.1.19
 Usage:
  0.0/2.0 CPU
  0.00/1.863 GiB memory
  0.00/0.535 GiB object_store_memory
```

### Versions / Dependencies

ray 2.2.0

### Reproduction script

1. Create a raycluster in kubernetes.
2. Use the ray cli to connect to the exposed address of the GCS server, eg: `ray logs cluster --address 127.0.0.1:6379`

### Issue Severity

Low: It annoys or frustrates me.

**Comment by rkooo567** [comment]
cc @rickyyx

**Comment by rkooo567** [comment]
we should make sure this API works at k8s

**Comment by rickyyx** [comment]
@tekumara Could you try starting the ray cluster with dashboard host overriden? 
e.g. 
```
ray start --dashboard-host=127.0.0.0 <other flags> 
```

And for @rkooo567, I think we retrieved the dashboard url from GCS, and when it's written, I don't think the writer (the head node) is aware of the forwarding done externally. 
The reason that `ray status` works is because it talks to GCS directly. 

 if using `dashboard-host` flag works, I think maybe we should improve the doc for this.

**Comment by rkooo567** [comment]
ping @tekumara to try to ^ out!

**Comment by tekumara** [comment]
With:
```
  rayStartParams:
    dashboard-host: "127.0.0.1"
```

From the client I now get:
```
❯ ray logs cluster --address 127.0.0.1:6379
Traceback (most recent call last):
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/compute/code/ray-demo/.venv/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/scripts/scripts.py", line 2386, in main
    return cli()
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/experimental/state/state_cli.py", line 930, in log_cluster
    logs = list_logs(
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/experimental/state/api.py", line 1250, in list_logs
    r = requests.get(
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
```

**Comment by rickyyx** [comment]
Thanks for trying this out. I will work on a repro!
