### ISSUE TITLE
No jobs scheduled when using redis-password

### ISSUE THREAD

**Issue by dhroth** [ray-project/ray#3141]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.1
- **Ray installed from (source or binary)**: pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.5.3-cp35-cp35m-manylinux1_x86_64.whl
- **Ray version**: 0.5.3
- **Python version**: 3.5.2
- **Exact command to reproduce**: Given `foo.py` below, running the following reproduces the problem:
```
export RAY_USE_XRAY=1
ray start --head --redis-password=thequickbrownfox
python foo.py
```

### Describe the problem
When I start ray without a `--redis-password`, `foo.py` works as expected (writes 5 `foo#.out` files). When using the `--redis-password`, `foo.py` hangs indefinitely.

### Source code / logs
`foo.py`:
```
import ray
# using whatever address and port were given when I ran ray start
ray.init(redis_address="<addr>:<port>", redis_password="thequickbrownfox")
@ray.remote
def foo(i):
    with open("foo{}.out".format(i), "w") as fooF:
        fooF.write("hello world")

ids = []
for i in range(5):
    ids.append(foo.remote(i))

ray.get(ids)
print("done!")
```

**Comment by dhroth** [comment]
If I Ctr+C once it's hanging, I consistently get this:
```
^CTraceback (most recent call last):
  File "foo.py", line 14, in <module>
    ray.get(ids)
  File "/work/drothchild/virtualenvs/tflow/lib/python3.5/site-packages/ray/worker.py", line 2447, in get
    values = worker.get_object(object_ids)
  File "/work/drothchild/virtualenvs/tflow/lib/python3.5/site-packages/ray/worker.py", line 523, in get_object
    int(0.01 * len(unready_ids))
  File "/work/drothchild/virtualenvs/tflow/lib/python3.5/site-packages/ray/worker.py", line 406, in retrieve_and_deserialize
    self.get_serialization_context(self.task_driver_id))
  File "/work/drothchild/virtualenvs/tflow/lib/python3.5/site-packages/ray/utils.py", line 405, in _wrapper
    return orig_attr(*args, **kwargs)
KeyboardInterrupt
```

**Comment by robertnishihara** [comment]
Running something similar, I can reproduce the issue and see the following in some of the worker logs (in general, check `/tmp/ray/` for logs).

```
Traceback (most recent call last):
  File "/Users/rkn/Workspace/ray/python/ray/workers/default_worker.py", line 91, in <module>
    info, mode=ray.WORKER_MODE, redis_password=args.redis_password)
  File "/Users/rkn/Workspace/ray/python/ray/worker.py", line 1910, in connect
    [log_stdout_file, log_stderr_file])
  File "/Users/rkn/Workspace/ray/python/ray/services.py", line 268, in record_log_files_in_redis
    redis_client.rpush(log_file_list_key, log_file.name)
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 1388, in rpush
    return self.execute_command('RPUSH', name, *values)
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/anaconda3/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: NOAUTH Authentication required.
```
