### ISSUE TITLE
[RLlib] Stashed policies are being accessed excessively, defeating the purpose of a policy cache

### ISSUE THREAD

**Issue by gjoliver** [ray-project/ray#31432]
### What happened + What you expected to happen

The idea of a policy cache is to stash unused policies on disk or in object store, to alleviate memory stress.
That requires our code to only access cached policies, and restore states properly when a policy is un-stashed, at all times.
If we access already stashed policies blindly, we will get into a situation where useful policies get stashed then immediately un-stashed, which will slow down things significantly and unnecessarilly.
While debugging things, I notice at least the following places where we are accessing ALL policies, regardless of whether they are in the cache or not:

1. Syncing weights from all policies to Eval workers. This will cause the local and eval workers to stash then unstash all policies.
https://github.com/ray-project/ray/blob/50e1fda022a81e5015978cf723f7b5fd9cc06b2c/rllib/algorithms/algorithm.py#L816-L826

2. RolloutWorker seems to set global vars on all policies regardless of whether they are stashed.
https://github.com/ray-project/ray/blob/master/rllib/evaluation/rollout_worker.py#L1781-L1782

3. APPO target network update works on all trainable policies. This will cause excessive policy restoring on the training workers.
https://github.com/ray-project/ray/blob/50e1fda022a81e5015978cf723f7b5fd9cc06b2c/rllib/algorithms/appo/appo.py#L239-L242

These are the places I have discovered so far. Things do seem a lot quieter if I comment out all these logics.

### Versions / Dependencies

Master

### Reproduction script

Add logging lines where we restore and stashing policies, then run:
``bazel run rllib/learning_tests_multi_agent_cartpole_w_100_policies_appo``

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by sven1977** [comment]
Thanks for raising this @gjoliver .
On 1. and 2.: Only policies that actually changed (got updated) should be synched (and possibly even have their global-vars updated, but I'm not sure about that).
3. True, but there is no real solution for this. If a policy is trained AND has been trained in that iteration, it must be updated.

Some thought on this: Usually, when this massive caching is used, most of the (cached) policies are not trained.

**Comment by gjoliver** [comment]
@sven1977 totally agree what you described is the ideal state.
maybe I didn't make it clear, what I am seeing is that we are accessing all policies even if there is only 1 rollout worker and 1 env, and we are only training 1 policy at a time.

**Comment by gjoliver** [comment]
actually, here is another error that I sometimes see:
```
(APPO pid=15631) Exception in thread Thread-2:
(APPO pid=15631) Traceback (most recent call last):
(APPO pid=15631)   File "/ray/python/ray/rllib/policy/torch_policy_v2.py", line 1197, in _worker
(APPO pid=15631)     loss_out[opt_idx].backward(retain_graph=True)
(APPO pid=15631)   File "/opt/miniconda/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
(APPO pid=15631)     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
(APPO pid=15631)   File "/opt/miniconda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
(APPO pid=15631)     allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
(APPO pid=15631) RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [32, 1]], which is output 0 of AsStridedBackward0, is at version 1879; expected version 1878 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
(APPO pid=15631) 
(APPO pid=15631) The above exception was the direct cause of the following exception:
(APPO pid=15631) 
(APPO pid=15631) Traceback (most recent call last):
(APPO pid=15631)   File "/opt/miniconda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
(APPO pid=15631)     self.run()
(APPO pid=15631)   File "/ray/python/ray/rllib/execution/learner_thread.py", line 74, in run
(APPO pid=15631)     self.step()
(APPO pid=15631)   File "/ray/python/ray/rllib/execution/learner_thread.py", line 91, in step
(APPO pid=15631)     multi_agent_results = self.local_worker.learn_on_batch(batch)
(APPO pid=15631)   File "/ray/python/ray/rllib/evaluation/rollout_worker.py", line 1025, in learn_on_batch
(APPO pid=15631)     info_out[pid] = policy.learn_on_batch(batch)
(APPO pid=15631)   File "/ray/python/ray/rllib/utils/threading.py", line 24, in wrapper
(APPO pid=15631)     return func(self, *a, **k)
(APPO pid=15631)   File "/ray/python/ray/rllib/policy/torch_policy_v2.py", line 629, in learn_on_batch
(APPO pid=15631)     grads, fetches = self.compute_gradients(postprocessed_batch)
(APPO pid=15631)   File "/ray/python/ray/rllib/utils/threading.py", line 24, in wrapper
(APPO pid=15631)     return func(self, *a, **k)
(APPO pid=15631)   File "/ray/python/ray/rllib/policy/torch_policy_v2.py", line 833, in compute_gradients
(APPO pid=15631)     tower_outputs = self._multi_gpu_parallel_grad_calc([postprocessed_batch])
(APPO pid=15631)   File "/ray/python/ray/rllib/policy/torch_policy_v2.py", line 1259, in _multi_gpu_parallel_grad_calc
(APPO pid=15631)     raise last_result[0] from last_result[1]
(APPO pid=15631) ValueError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [32, 1]], which is output 0 of AsStridedBackward0, is at version 1879; expected version 1878 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
(APPO pid=15631)  tracebackTraceback (most recent call last):
(APPO pid=15631)   File "/ray/python/ray/rllib/policy/torch_policy_v2.py", line 1197, in _worker
(APPO pid=15631)     loss_out[opt_idx].backward(retain_graph=True)
(APPO pid=15631)   File "/opt/miniconda/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
(APPO pid=15631)     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
(APPO pid=15631)   File "/opt/miniconda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
(APPO pid=15631)     allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
(APPO pid=15631) RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [32, 1]], which is output 0 of AsStridedBackward0, is at version 1879; expected version 1878 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
(APPO pid=15631) 
(APPO pid=15631) In tower 0 on device cpu
(APPO pid=15631) 
2023-01-05 18:32:28,414	ERROR trial_runner.py:1093 -- Trial APPO_multi_cartpole_fd325_00000: Error processing event.
ray.exceptions.RayTaskError(RuntimeError): ray::APPO.train() (pid=15631, ip=172.18.0.3, repr=APPO)
  File "/ray/python/ray/tune/trainable/trainable.py", line 367, in train
    raise skipped from exception_cause(skipped)
  File "/ray/python/ray/tune/trainable/trainable.py", line 364, in train
    result = self.step()
  File "/ray/python/ray/rllib/algorithms/algorithm.py", line 732, in step
    ) = self._run_one_training_iteration_and_evaluation_in_parallel()
  File "/ray/python/ray/rllib/algorithms/algorithm.py", line 2745, in _run_one_training_iteration_and_evaluation_in_parallel
    train_results, train_iter_ctx = train_future.result()
  File "/opt/miniconda/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/opt/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/miniconda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/ray/python/ray/rllib/algorithms/algorithm.py", line 2739, in <lambda>
    train_future = executor.submit(lambda: self._run_one_training_iteration())
  File "/ray/python/ray/rllib/algorithms/algorithm.py", line 2651, in _run_one_training_iteration
    results = self.training_step()
  File "/ray/python/ray/rllib/algorithms/appo/appo.py", line 268, in training_step
    train_results = super().training_step()
  File "/ray/python/ray/rllib/algorithms/impala/impala.py", line 536, in training_step
    raise RuntimeError("The learner thread died while training!")
RuntimeError: The learner thread died while training!
```
