### ISSUE TITLE
[core][ci] raylet not runnable in Mac M1 machine

### ISSUE THREAD

**Issue by jiwq** [ray-project/ray#31736]
### What happened + What you expected to happen

In head node pod execute a job throw RuntimeError.
```
(base) ray@raycluster-kuberay-head-whfnr:~$ python -c "import ray; ray.init()"
2023-01-18 07:59:37,046	INFO worker.py:1245 -- Using address 127.0.0.1:6379 set in the environment variable RAY_ADDRESS
2023-01-18 07:59:37,049	INFO worker.py:1366 -- Connecting to existing Ray cluster at address: 10.244.0.6:6379...
[2023-01-18 07:59:37,302 W 1207 1207] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-01-18 07:59:38,310 W 1207 1207] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-01-18 07:59:39,317 W 1207 1207] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-01-18 07:59:40,326 W 1207 1207] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-01-18 07:59:41,335 W 1207 1207] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-01-18 07:59:42,347 W 1207 1207] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-01-18 07:59:43,361 W 1207 1207] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-01-18 07:59:44,370 W 1207 1207] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-01-18 07:59:45,375 W 1207 1207] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-01-18 07:59:46,390 W 1207 1207] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py", line 1516, in init
    connect_only=True,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/node.py", line 246, in __init__
    self._raylet_ip_address,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 444, in get_node_to_connect_for_driver
    return global_state.get_node_to_connect_for_driver(node_ip_address)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/state.py", line 753, in get_node_to_connect_for_driver
    node_ip_address
  File "python/ray/includes/global_state_accessor.pxi", line 155, in ray._raylet.GlobalStateAccessor.get_node_to_connect_for_driver
RuntimeError: b'GCS has started but no raylets have registered yet.'
```

Check process for ray not found raylet.
```

(base) ray@raycluster-kuberay-head-whfnr:~$ ps aux | grep ray
ray            1  0.0  0.1 150508 12032 ?        Ssl  Jan17   0:00 /usr/bin/qemu-x86_64 /bin/bash /bin/bash -lc -- ulimit -n 65536; ray start --head  --block  --dashboard-host=0.0.0.0  --metrics-export-port=8080  --num-cpus=1  --memory=2000000000
ray           14  0.2  4.1 1879008 333852 ?      Sl   Jan17   4:05 /usr/bin/qemu-x86_64 /home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/ray start --head --block --dashboard-host=0.0.0.0 --metrics-export-port=8080 --num-cpus=1 --memory=2000000000
ray          345  0.0  0.1 151504 15556 pts/0    Ssl  Jan17   0:00 /usr/bin/qemu-x86_64 /usr/bin/bash bash
ray          869  5.4  0.9 1683756 78480 pts/0   Sl   06:13   5:54 /usr/bin/qemu-x86_64 /home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/gcs/gcs_server /home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/gcs/gcs_server --log_dir=/tmp/ray/session_2023-01-18_06-13-32_977482_855/logs --config_list=eyJvYmplY3Rfc3BpbGxpbmdfY29uZmlnIjogIntcInR5cGVcIjogXCJmaWxlc3lzdGVtXCIsIFwicGFyYW1zXCI6IHtcImRpcmVjdG9yeV9wYXRoXCI6IFwiL3RtcC9yYXkvc2Vzc2lvbl8yMDIzLTAxLTE4XzA2LTEzLTMyXzk3NzQ4Ml84NTVcIn19IiwgImlzX2V4dGVybmFsX3N0b3JhZ2VfdHlwZV9mcyI6IHRydWV9 --gcs_server_port=6379 --metrics-agent-port=64363 --node-ip-address=10.244.0.6 --session-name=session_2023-01-18_06-13-32_977482_855
ray          899  0.6  2.0 1476316 162240 pts/0  Sl   06:13   0:39 /usr/bin/qemu-x86_64 /home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py --logs-dir=/tmp/ray/session_2023-01-18_06-13-32_977482_855/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.244.0.6:6379 --monitor-ip=10.244.0.6
ray          920  1.4  2.0 1408540 165996 pts/0  Sl   06:13   1:31 /usr/bin/qemu-x86_64 /home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/python -m ray.util.client.server --address=10.244.0.6:6379 --host=0.0.0.0 --port=10001 --mode=proxy --metrics-agent-port=64363
ray          941  2.8  3.1 2485584 251332 pts/0  Sl   06:13   3:07 /usr/bin/qemu-x86_64 /home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/python /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/dashboard.py --host=localhost --port=8265 --port-retries=0 --temp-dir=/tmp/ray --log-dir=/tmp/ray/session_2023-01-18_06-13-32_977482_855/logs --session-dir=/tmp/ray/session_2023-01-18_06-13-32_977482_855 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.244.0.6:6379
ray         1057  7.0  1.9 1249732 156700 pts/0  Sl   06:13   7:35 /usr/bin/qemu-x86_64 /home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/log_monitor.py --logs-dir=/tmp/ray/session_2023-01-18_06-13-32_977482_855/logs --gcs-address=10.244.0.6:6379 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5
ray         1242  0.0  0.1 152128 11296 ?        Rl+  Jan17   0:00 ps aux
ray         1244  2.0  0.1 149400  8460 pts/0    Sl+  08:01   0:00 /usr/bin/qemu-x86_64 /usr/bin/grep grep --color=auto ray
```

### Versions / Dependencies

```
# docker image ls

REPOSITORY                      TAG       IMAGE ID       CREATED        SIZE
rayproject/ray                  nightly   e55824602a37   41 hours ago   2.72GB
```

### Reproduction script

```
# Step 1: Create a Kind cluster 
kind create cluster

# Step 2: Register a Helm chart repo
helm repo add kuberay https://ray-project.github.io/kuberay-helm/

# Step 3: Install both CRDs and KubeRay operator v0.4.0.
helm install kuberay-operator kuberay/kuberay-operator --version 0.4.0

# Step 4: Install a RayCluster custom resource
helm install raycluster kuberay/ray-cluster --version 0.4.0

# Step 5: Verify the installation of KubeRay operator and RayCluster 
kubectl get pods
# NAME                                          READY   STATUS    RESTARTS   AGE
# kuberay-operator-6fcbb94f64-gkpc9             1/1     Running   0          89s
# raycluster-kuberay-head-qp9f4                 1/1     Running   0          66s
# raycluster-kuberay-worker-workergroup-2jckt   1/1     Running   0          66s

# Step 6: Forward the port of Dashboard
kubectl port-forward --address 0.0.0.0 svc/raycluster-kuberay-head-svc 8265:8265

# Step 7: Check ${YOUR_IP}:8265 for the Dashboard (e.g. 127.0.0.1:8265)

# Step 8: Log in to Ray head Pod and execute a job.
kubectl exec -it ${RAYCLUSTER_HEAD_POD} -- bash
python -c "import ray; ray.init(); print(ray.cluster_resources())" # (in Ray head Pod)
```

### Issue Severity

None

**Comment by kevin85421** [comment]
Thank @jiwq for pointing this out! I can reproduce the same bug on my Mac M1 too. cc @krfricke

**Comment by krfricke** [comment]
We currently do not build docker images for ARM64, see https://github.com/ray-project/ray/issues/31537

The workaround at the moment is to build your own docker image and install the Linux ARM64 wheels manually.

I'll follow up internally to see if we can prioritize this.

**Comment by jiwq** [comment]
Thanks @krfricke pointed this, and hope as soon as possible to provide arm64 image, so reduce the threshold for newbie.
@kevin85421 Maybe we should reorganize the doc in [ray-project/kuberay#869](https://github.com/ray-project/kuberay/pull/869).

**Comment by kevin85421** [comment]
@jiwq I will update https://github.com/ray-project/kuberay/pull/869 when this issue is resolved.

@krfricke may be a dumb question. Is https://github.com/ray-project/ray/pull/31522 only for Linux ARM 64 but not for Mac M1?

**Comment by jiwq** [comment]
> @krfricke may be a dumb question. Is #31522 only for Linux ARM 64 but not for Mac M1?
@kevin85421 If I understand correctly,  #31522 resolved for build wheels for arm64 but not for docker image.

**Comment by krfricke** [comment]
That's right. To be clear:

- We have latest and nightly *python wheels* for linux arm64
- We have latest *python wheels* for mac arm64
- We have latest and nightly *docker images* only for x86_64
- We don't have any *docker images* for arm64 

Since docker images always use a linux base, there is no difference between docker images for mac and linux.

**Comment by kevin85421** [comment]
Thank @jiwq and @krfricke for the explanation!

**Comment by kevin85421** [comment]
The nightly docker images for arm64 are available. See https://github.com/ray-project/ray/issues/31537#issuecomment-1405687464 for more details. Thank @krfricke for this great work! I will try it with KubeRay.

**Comment by jiwq** [comment]
Thank @krfricke for the great work, and @kevin85421 for the kuberay doc.  Close this issue.
