### ISSUE TITLE
[Core] Ray Start --head fails with gRPC error for nightly release (Jupyter Notebook)

### ISSUE THREAD

**Issue by peterghaddad** [ray-project/ray#31765]
### What happened + What you expected to happen

After installing the nightly release of Ray and running `ray start --head` I receive the following errors:

I am doing this inside of a Jupyter Notebook hosted on the cloud, but also run into the same errors locally.

```
Traceback (most recent call last):
  File "/home/jovyan/.local/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/scripts/scripts.py", line 2441, in main
    return cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/autoscaler/_private/cli_logger.py", line 852, in wrapper
    return f(*args, **kwargs)
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/scripts/scripts.py", line 737, in start
    node = ray._private.node.Node(
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/_private/node.py", line 287, in __init__
    self.start_head_processes()
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/_private/node.py", line 1121, in start_head_processes
    self._write_cluster_info_to_kv()
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/_private/node.py", line 1070, in _write_cluster_info_to_kv
    ray_usage_lib.put_cluster_metadata(self.get_gcs_client())
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/_private/usage/usage_lib.py", line 521, in put_cluster_metadata
    gcs_client.internal_kv_put(
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/_private/gcs_utils.py", line 198, in wrapper
    return f(self, *args, **kwargs)
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/_private/gcs_utils.py", line 317, in internal_kv_put
    reply = self._kv_stub.InternalKVPut(req, timeout=timeout)
  File "/home/jovyan/.local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/jovyan/.local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:10.32.123.12:6379: Failed to connect to remote host: Connection refused"
        debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:10.32.123.12:6379: Failed to connect to remote host: Connection refused {created_time:"2023-01-19T00:07:53.287699885+00:00", grpc_status:14}"
```

When running Ray 2.2.0, I am able to start the head node perfectly fine and run into zero issues. I am trying to run the nightly release to test some of the Multi Agent RL examples, and the nightly release fixes problems with PettingZoo environments.

I wanted to create this issue since it works for the latest release, and want to ensure no breaking changes get released in 2.3.0.

### Versions / Dependencies

Nightly release of Ray 3.9 Linux
Python 3.9.7
JupyterNotebook

### Reproduction script

`ray start --head`

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by stephanie-wang** [comment]
I wasn't able to reproduce this on Ubuntu 20.04, python 3.9.

Could you include which exact OS you're on? Note that currently there is no support for nightly wheels support for M1 Macs.
