### ISSUE TITLE
[Core/Data] Failure to serialize trivial Ray Dataset across nodes

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#31760]
TL;DR Ray fails to transfer a trivial Ray Dataset (`ray.data.range_tensor(10)`) from one node to another when it is a return value of a task.

Ray on master branch, commit 1012fbc375d55540fb944a1176a8a54af34182f6

To reproduce:
1. Create Ray cluster with >=2 nodes.
2. Run below repro script.
3. Observe crash.

```
 File "/home/ray/cadelabs/ray-wait-perf-regression/./crash_repro.py", line 41, in <module>
    ray.get(future)
  File "/data/pypi/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/data/pypi/lib/python3.10/site-packages/ray/_private/worker.py", line 2352, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::destination_task() (pid=176541, ip=10.0.209.83)
  File "/home/ray/cadelabs/ray-wait-perf-regression/./crash_repro.py", line 24, in destination_task
    ds = ray.get(future)
ray.exceptions.RaySystemError: System error: Can't get attribute '_make_function' on <module 'ray.cloudpickle.cloudpickle' from '/data/pypi/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle.py'>
traceback: Traceback (most recent call last):
AttributeError: Can't get attribute '_make_function' on <module 'ray.cloudpickle.cloudpickle' from '/data/pypi/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle.py'>
(destination_task pid=176541) 2023-01-18 15:06:47,672   ERROR serialization.py:371 -- Can't get attribute '_make_function' on <module 'ray.cloudpickle.cloudpickle' from '/data/pypi/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle.py'>
(destination_task pid=176541) Traceback (most recent call last):
(destination_task pid=176541)   File "/data/pypi/lib/python3.10/site-packages/ray/_private/serialization.py", line 369, in deserialize_objects
(destination_task pid=176541)     obj = self._deserialize_object(data, metadata, object_ref)
(destination_task pid=176541)   File "/data/pypi/lib/python3.10/site-packages/ray/_private/serialization.py", line 252, in _deserialize_object
(destination_task pid=176541)     return self._deserialize_msgpack_data(data, metadata_fields)
(destination_task pid=176541)   File "/data/pypi/lib/python3.10/site-packages/ray/_private/serialization.py", line 207, in _deserialize_msgpack_data
(destination_task pid=176541)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(destination_task pid=176541)   File "/data/pypi/lib/python3.10/site-packages/ray/_private/serialization.py", line 197, in _deserialize_pickle5_data
(destination_task pid=176541)     obj = pickle.loads(in_band)
(destination_task pid=176541) AttributeError: Can't get attribute '_make_function' on <module 'ray.cloudpickle.cloudpickle' from '/data/pypi/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle.py'>
```

```python3
#!/usr/bin/env python3

import ray


def node_assignment(node):
    return {'node:{}'.format(node['NodeName']): 0.001}


@ray.remote
def source_task():
    print('src task')
    ds = ray.data.range_tensor(10)
    return ds


@ray.remote
def destination_task(other_node):
    future = source_task.options(
        resources=node_assignment(other_node)
    ).remote()

    print('dest task')
    ds = ray.get(future)
    print(ds.size_bytes())


if __name__ == '__main__':
    ray.init()

    # Need to guarantee that the src and dest tasks run on different nodes.
    nodes = ray.nodes()
    assert len(nodes) >= 2, "Must have at least two nodes to reproduce crash"
    destination_node = nodes[0]
    source_node = nodes[1]

    future = destination_task.options(
        resources=node_assignment(destination_node),
    ).remote(source_node)

    ray.get(future)
```

**Comment by stephanie-wang** [comment]
Hmm I wasn't able to reproduce the error on master (a205fda91a1262dfb152918f70bf425d9ba5bca4). Could it be some issue with the Ray installation? Maybe try with nightly wheels?

**Comment by cadedaniel** [comment]
Thanks for the repro attempt @stephanie-wang ! It could be due to worker nodes not picking up new Ray versions installed in `/mnt/cluster_storage/pypi/bin/ray`. I will retry with nightly wheels.

**Comment by cadedaniel** [comment]
Closing for now, will reopen if I repro it on nightly
