### ISSUE TITLE
build-wheel-manylinux2014.sh doe not work as specified in the documentation

### ISSUE THREAD

**Issue by pcheema-scribd** [ray-project/ray#31775]
### Description

`docker run -e TRAVIS_COMMIT=f0a117320ccf4db2b8a334a8fe44a061e483135f --rm -w /ray -v `pwd`:/ray -ti quay.io/pypa/manylinux2014_x86_64  /ray/python/build-wheel-manylinux2014.sh
`
Error ->
```
gcc: fatal error: Killed signal terminated program cc1plus
compilation terminated.
INFO: Elapsed time: 1376.627s, Critical Path: 331.06s
INFO: 3950 processes: 1218 internal, 5 local, 2727 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "setup.py", line 794, in <module>
    ) if __name__ == "__main__" else None
  File "/opt/python/cp36-cp36m/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python/cp36-cp36m/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python/cp36-cp36m/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/python/cp36-cp36m/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/python/cp36-cp36m/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/opt/python/cp36-cp36m/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/python/cp36-cp36m/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/python/cp36-cp36m/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/opt/python/cp36-cp36m/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/python/cp36-cp36m/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 740, in run
    return pip_run(self)
  File "setup.py", line 641, in pip_run
    build(True, BUILD_JAVA, True)
  File "setup.py", line 592, in build
    env=bazel_env,
  File "setup.py", line 356, in bazel_invoke
    result = invoker([cmd] + cmdline, *args, **kwargs)
  File "/opt/python/cp36-cp36m/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/.bazel/bin/bazel', 'build', '--verbose_failures', '--', '//:ray_pkg', '//cpp:ray_cpp_pkg']' returned non-zero exit status 1.
```

### Link

https://github.com/ray-project/ray/blob/master/python/README-building-wheels.md

**Comment by pcheema-scribd** [comment]
gcc error
ERROR: /ray/BUILD.bazel:2113:11: Compiling src/ray/gcs/gcs_client/accessor.cc failed: (Exit 1): gcc failed: error executing command

**Comment by pcheema-scribd** [comment]
fixed, it was a memory issue which was making gcc crash, thanks to @architkulkarni
