### ISSUE TITLE
General error on game  PongNoFrameskip-v4 

### ISSUE THREAD

**Issue by rnunziata** [ray-project/ray#3178]
When I run with Pong-ram-v4 it works but when I run with PongNoFrameskip-v4   as shown below:
>> python/ray/rllib/train.py  --run=IMPALA --config-file=my.yaml
Why is the selection of the game cause this kind of error?
I am going to try to update my cudnn and see if that fixes it....

My config-file is 
```
pong-impala:
    env: Pong-ram-v4 
#    env: PongNoFrameskip-v4    
    run: IMPALA
    config:
        sample_batch_size: 50
        train_batch_size: 500
        num_workers: 7     


======================================== ERROR

This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').
WARNING: Serializing objects of type <class 'ray.rllib.evaluation.sample_batch.SampleBatch'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.rllib.evaluation.sample_batch.SampleBatch'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
2018-10-31 16:56:42.442805: E tensorflow/stream_executor/cuda/cuda_dnn.cc:343] Loaded runtime CuDNN library: 7.1.4 but source was compiled with: 7.2.1.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
Error processing event.
Traceback (most recent call last):
  File "/home/rjn/.local/lib/python2.7/site-packages/ray/tune/trial_runner.py", line 239, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/rjn/.local/lib/python2.7/site-packages/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/rjn/.local/lib/python2.7/site-packages/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
RayGetError: Could not get objectid ObjectID(a48f0b24eaa3f88e87554a4c29634757c64a0027). It was created by remote function <unknown> which failed with:

Remote function <unknown> failed with:
 
```

**Comment by ericl** [comment]
Can you post the complete error?

**Comment by rnunziata** [comment]
here is the complete output. 
```
pong-impala:
    env: PongNoFrameskip-v4    
    run: IMPALA
    checkpoint_freq: 20    
    config:
        sample_batch_size: 50
        train_batch_size: 500
        num_workers: 7     
        model:
            use_lstm: true
            conv_activation: elu
            dim: 42
            grayscale: true
            zero_mean: false
```




```
python/ray/rllib/train.py --run=IMPALA --config-file="my.yaml"
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:38711 to respond...
Waiting for redis server at 127.0.0.1:43880 to respond...
Starting the Plasma object store with 6.00 GB memory.
Starting local scheduler with the following resources: {'GPU': 1, 'CPU': 8}.

======================================================================
View the web UI at http://localhost:8889/notebooks/ray_ui84886.ipynb?token=e5f8edd6dfad9b8a512bbb747e5eb5e542d6f83cd84e591b
======================================================================

== Status ==
Using FIFO scheduling algorithm.


WARNING: lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
Created LogSyncer for /home/rjn/ray_results/pong-impala/IMPALA_PongNoFrameskip-v4_0_2018-10-31_21-05-07Um1eh6 -> 
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 8/8 CPUs, 1/1 GPUs
Result logdir: /home/rjn/ray_results/pong-impala
RUNNING trials:
 - IMPALA_PongNoFrameskip-v4_0:	RUNNING

WARNING: lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
2018-10-31 21:05:08.537099: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-31 21:05:08.635087: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-10-31 21:05:08.636225: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.733
pciBusID: 0000:01:00.0
totalMemory: 5.93GiB freeMemory: 5.51GiB
2018-10-31 21:05:08.636240: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-10-31 21:05:08.835532: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-10-31 21:05:08.835561: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2018-10-31 21:05:08.835569: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2018-10-31 21:05:08.835749: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5277 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
From /home/rjn/.local/lib/python2.7/site-packages/ray/rllib/models/lstm.py:142: __init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').
WARNING: lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
WARNING: lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
WARNING: lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
2018-10-31 21:05:11.864948: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-31 21:05:11.868287: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2018-10-31 21:05:11.868427: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: rjn-Oryx-Pro
2018-10-31 21:05:11.868492: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: rjn-Oryx-Pro
2018-10-31 21:05:11.868590: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 396.44.0
2018-10-31 21:05:11.868691: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 396.44.0
2018-10-31 21:05:11.868749: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 396.44.0
WARNING: lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
WARNING: lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
WARNING: lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
WARNING: lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
From /home/rjn/.local/lib/python2.7/site-packages/ray/rllib/models/lstm.py:142: __init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').
2018-10-31 21:05:12.085708: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-31 21:05:12.088822: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2018-10-31 21:05:12.088859: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: rjn-Oryx-Pro
2018-10-31 21:05:12.088876: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: rjn-Oryx-Pro
2018-10-31 21:05:12.088923: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 396.44.0
2018-10-31 21:05:12.088954: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 396.44.0
2018-10-31 21:05:12.088963: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 396.44.0
2018-10-31 21:05:12.103043: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-31 21:05:12.105602: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2018-10-31 21:05:12.105643: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: rjn-Oryx-Pro
2018-10-31 21:05:12.105666: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: rjn-Oryx-Pro
2018-10-31 21:05:12.105713: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 396.44.0
2018-10-31 21:05:12.105746: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 396.44.0
2018-10-31 21:05:12.105763: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 396.44.0
From /home/rjn/.local/lib/python2.7/site-packages/ray/rllib/models/lstm.py:142: __init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').
From /home/rjn/.local/lib/python2.7/site-packages/ray/rllib/models/lstm.py:142: __init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').
2018-10-31 21:05:12.271512: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-31 21:05:12.274786: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2018-10-31 21:05:12.274839: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: rjn-Oryx-Pro
2018-10-31 21:05:12.274858: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: rjn-Oryx-Pro
2018-10-31 21:05:12.274919: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 396.44.0
2018-10-31 21:05:12.274960: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 396.44.0
2018-10-31 21:05:12.274976: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 396.44.0
2018-10-31 21:05:12.276808: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-31 21:05:12.279382: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-31 21:05:12.280296: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2018-10-31 21:05:12.280348: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: rjn-Oryx-Pro
2018-10-31 21:05:12.280369: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: rjn-Oryx-Pro
2018-10-31 21:05:12.280432: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 396.44.0
2018-10-31 21:05:12.280477: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 396.44.0
2018-10-31 21:05:12.280495: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 396.44.0
2018-10-31 21:05:12.282912: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2018-10-31 21:05:12.282971: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: rjn-Oryx-Pro
2018-10-31 21:05:12.282989: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: rjn-Oryx-Pro
2018-10-31 21:05:12.283047: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 396.44.0
2018-10-31 21:05:12.283083: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 396.44.0
2018-10-31 21:05:12.283093: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 396.44.0
2018-10-31 21:05:12.292127: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-31 21:05:12.295680: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2018-10-31 21:05:12.295751: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: rjn-Oryx-Pro
2018-10-31 21:05:12.295770: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: rjn-Oryx-Pro
2018-10-31 21:05:12.295829: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 396.44.0
2018-10-31 21:05:12.295878: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 396.44.0
2018-10-31 21:05:12.295895: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 396.44.0
From /home/rjn/.local/lib/python2.7/site-packages/ray/rllib/models/lstm.py:142: __init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').
From /home/rjn/.local/lib/python2.7/site-packages/ray/rllib/models/lstm.py:142: __init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').
From /home/rjn/.local/lib/python2.7/site-packages/ray/rllib/models/lstm.py:142: __init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').
From /home/rjn/.local/lib/python2.7/site-packages/ray/rllib/models/lstm.py:142: __init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').
WARNING: Serializing objects of type <class 'ray.rllib.evaluation.sample_batch.SampleBatch'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.rllib.evaluation.sample_batch.SampleBatch'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
2018-10-31 21:05:16.279044: E tensorflow/stream_executor/cuda/cuda_dnn.cc:343] Loaded runtime CuDNN library: 7.1.4 but source was compiled with: 7.2.1.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
Error processing event.
Traceback (most recent call last):
  File "/home/rjn/.local/lib/python2.7/site-packages/ray/tune/trial_runner.py", line 239, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/rjn/.local/lib/python2.7/site-packages/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/rjn/.local/lib/python2.7/site-packages/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
RayGetError: Could not get objectid ObjectID(708eccb264dfc57d7a3de9623d2b7f62ca892325). It was created by remote function <unknown> which failed with:

Remote function <unknown> failed with:

Invalid return value: likely worker died or was killed while executing the task.
The worker with ID 36f714321ea53c00e6c6c2864ed024ee46bc4c9e died or was killed while executing the task with ID 718eccb264dfc57d7a3de9623d2b7f62ca892325
Worker ip unknown, skipping log sync for /home/rjn/ray_results/pong-impala/IMPALA_PongNoFrameskip-v4_0_2018-10-31_21-05-07Um1eh6
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/8 CPUs, 0/1 GPUs
Result logdir: /home/rjn/ray_results/pong-impala
ERROR trials:
 - IMPALA_PongNoFrameskip-v4_0:	ERROR, 1 failures: /home/rjn/ray_results/pong-impala/IMPALA_PongNoFrameskip-v4_0_2018-10-31_21-05-07Um1eh6/error_2018-10-31_21-05-16.txt

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/8 CPUs, 0/1 GPUs
Result logdir: /home/rjn/ray_results/pong-impala
ERROR trials:
 - IMPALA_PongNoFrameskip-v4_0:	ERROR, 1 failures: /home/rjn/ray_results/pong-impala/IMPALA_PongNoFrameskip-v4_0_2018-10-31_21-05-07Um1eh6/error_2018-10-31_21-05-16.txt

Traceback (most recent call last):
  File "python/ray/rllib/train.py", line 118, in <module>
    run(args, parser)
  File "python/ray/rllib/train.py", line 112, in run
    queue_trials=args.queue_trials)
  File "/home/rjn/.local/lib/python2.7/site-packages/ray/tune/tune.py", line 118, in run_experiments
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [IMPALA_PongNoFrameskip-v4_0])
I1031 21:05:16.569010 13545 local_scheduler.cc:178] Killed worker pid 13895 which hadn't started yet.
I1031 21:05:16.569968 13545 local_scheduler.cc:178] Killed worker pid 13897 which hadn't started yet.
I1031 21:05:16.570338 13545 local_scheduler.cc:178] Killed worker pid 13898 which hadn't started yet.
I1031 21:05:16.570489 13545 local_scheduler.cc:178] Killed worker pid 13899 which hadn't started yet.
I1031 21:05:16.576499 13545 local_scheduler.cc:178] Killed worker pid 13900 which hadn't started yet.
I1031 21:05:16.577198 13545 local_scheduler.cc:178] Killed worker pid 13901 which hadn't started yet.
I1031 21:05:16.577630 13545 local_scheduler.cc:178] Killed worker pid 13902 which hadn't started yet.
I1031 21:05:16.577906 13545 local_scheduler.cc:178] Killed worker pid 13903 which hadn't started yet.

```

**Comment by richardliaw** [comment]
One potential issue - Maybe try downgrading TF to something like 1.10. TF
1.11 is compiled with CuDNN 7.2 rather than CuDNN 7.1.

**Comment by ericl** [comment]
> Invalid return value: likely worker died or was killed while executing the task.
Looks like some worker died unexpectedly without returning an error. Check your kernel logs (dmesg), you might be exceeding some limit. Or check /tmp/raylogs/worker-* https://ray.readthedocs.io/en/latest/rllib.html#troubleshooting

**Comment by rnunziata** [comment]
The logs have the following: I ran it with one worker in the config file. I still have to try to compile locally.
Note the line starting with >> are my command lines to cat the file content 
```
>>rjn@rjn-Oryx-Pro:/tmp/ray/session_2018-10-31_22-51-28_20763$ cat sockets/plasma_store 

cat: sockets/plasma_store: No such device or address

>>rjn@rjn-Oryx-Pro:/tmp/ray/session_2018-10-31_22-51-28_20763$ cat logs/monitor.err

*** Aborted at 1541040698 (unix time) try "date -d @1541040698" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGTERM (@0x3e80000511b) received by PID 20792 (TID 0x7f73fb64a740) from PID 20763; stack trace: ***
    @     0x7f73fb273390 (unknown)
    @     0x7f73fa6fe9f3 epoll_wait
    @           0x44a6cc boost::asio::detail::epoll_reactor::run()
    @           0x44affd boost::asio::detail::task_io_service::run()
    @           0x448002 main
    @     0x7f73fa617830 __libc_start_main
    @           0x449211 (unknown)

>>rjn@rjn-Oryx-Pro:/tmp/ray/session_2018-10-31_22-51-28_20763$ cat logs/redis-shard_0.err

/ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:1000: Allowing the Plasma store to use up to 6.70709GB of memory.
/ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:1030: Starting object store with directory /dev/shm and huge page support disabled
/ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 21
/ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 13
/ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 20
/ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 16
/ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 15
/ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 18
/ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 14
/ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 17
/ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 19
/ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 12

>>rjn@rjn-Oryx-Pro:/tmp/ray/session_2018-10-31_22-51-28_20763$ cat logs/redis.out 

20783:M 31 Oct 22:51:28.344 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
20783:M 31 Oct 22:51:28.344 # Server started, Redis version 3.9.102
20783:M 31 Oct 22:51:28.344 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
20783:M 31 Oct 22:51:28.344 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
20783:signal-handler (1541040698) Received SIGTERM scheduling shutdown...
20783:M 31 Oct 22:51:38.254 # User requested shutdown...
20783:M 31 Oct 22:51:38.254 # Redis is now ready to exit, bye bye...

>>rjn@rjn-Oryx-Pro:/tmp/ray/session_2018-10-31_22-51-28_20763$ cat logs/redis-shard_0.out

same as above error
```

**Comment by ericl** [comment]
Should there be logs for worker-*?

**Comment by rnunziata** [comment]
there was none....this is all there was...for one complete run with the error. 
there is a ray_result directory which has the following:

```
>> rjn@rjn-Oryx-Pro:~/ray_results/pong-impala/IMPALA_PongNoFrameskip-v4_0_2018-11-01_00-12-41WIgB1D$ ls
(there are four files here)
error_2018-11-01_00-12-50.txt  params.json  progress.csv  result.json
==========================================================================

>>cat result.json 

>>rcat progress.csv 

>>cat error_2018-11-01_00-12-50.txt 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ray/tune/trial_runner.py", line 243, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/usr/local/lib/python2.7/dist-packages/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 2257, in get
    raise RayGetError(object_ids, value)
RayGetError: Could not get objectid ObjectID(01000000f76b6d8abfab1217320bb6497ba6bcf0). It was created by remote function <unknown> which failed with:

Remote function <unknown> failed with:

Invalid return value: likely worker died or was killed while executing the task.

>> cat params.json 

{"env": "PongNoFrameskip-v4", "model": {"conv_activation": "elu", "dim": 42, "grayscale": true, "use_lstm": true, "zero_mean": false}, "num_workers": 2, "sample_batch_size": 50, "train_batch_size": 500}



```

**Comment by rnunziata** [comment]
Here is an update:
  I can run any game that has "-ram" in the title. Every thing else fails with following in the specified log file.

```

>> cat /home/rjn/ray_results/pong-impala/IMPALA_SpaceInvadersNoFrameskip-v4_0_2018-11-01_18-47-

03z7uaIU/error_2018-11-01_18-47-12.txt
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ray/tune/trial_runner.py", line 243, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/usr/local/lib/python2.7/dist-packages/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 2257, in get
    raise RayGetError(object_ids, value)
RayGetError: Could not get objectid ObjectID(0100000051f83b9fe5d3ab442463a5e99e1fef47). It was created by remote function <unknown> which failed with:

Remote function <unknown> failed with:

Invalid return value: likely worker died or was killed while executing the task.

```




In the /tmp/log files there is the following:

```
Beginning to track file /tmp/ray/session_2018-11-01_18-47-01_31027/logs/redis.out
Beginning to track file /tmp/ray/session_2018-11-01_18-47-01_31027/logs/redis.err
Beginning to track file /tmp/ray/session_2018-11-01_18-47-01_31027/logs/monitor.out
Beginning to track file /tmp/ray/session_2018-11-01_18-47-01_31027/logs/monitor.err
Beginning to track file /tmp/ray/session_2018-11-01_18-47-01_31027/logs/log_monitor.out
Beginning to track file /tmp/ray/session_2018-11-01_18-47-01_31027/logs/log_monitor.err
Beginning to track file /tmp/ray/session_2018-11-01_18-47-01_31027/logs/plasma_store_0.out
Beginning to track file /tmp/ray/session_2018-11-01_18-47-01_31027/logs/plasma_store_0.err
*** Aborted at 1541112432 (unix time) try "date -d @1541112432" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGTERM (@0x3e800007933) received by PID 31056 (TID 0x7fc7cd310740) from PID 31027; stack trace: ***
    @     0x7fc7ccf39390 (unknown)
    @     0x7fc7cc3c49f3 epoll_wait
    @           0x44a6cc boost::asio::detail::epoll_reactor::run()
    @           0x44affd boost::asio::detail::task_io_service::run()
    @           0x448002 main
    @     0x7fc7cc2dd830 __libc_start_main
    @           0x449211 (unknown)

```

**Comment by ericl** [comment]
You're using ray master or latest right? This has an experimental backend enabled, and you can disable it via ray.init(use_raylet=False) I believe.

@robertnishihara should we disable this by default?

**Comment by robertnishihara** [comment]
@ericl the old backend no longer exists.

**Comment by rnunziata** [comment]
all I did was 
pip install ray
I tried cloning the repository but can not get it to compile correctly ...seehttps://github.com/ray-project/ray/issues/3186

**Comment by rnunziata** [comment]
OK...some new data.
If I change my config file to run DNQ  then say SpaceInvadersNoFrameskip-v4_0 runs fine
If I change my config file to A3C also fine
but if I change it to run IMPALA...then it fails.....

**Comment by ericl** [comment]
Can you try `pip install ray==0.5.3`. The stack trace you have is from having xray enabled, I don't think the old backend should print errors like that.

**Comment by rnunziata** [comment]
```
pip install ray==0.5.3
Requirement already satisfied: ray==0.5.3 in /usr/local/lib/python2.7/dist-packages (0.5.3)
Requirement already satisfied: flatbuffers in ./.local/lib/python2.7/site-packages (from ray==0.5.3) (1.10)
Requirement already satisfied: colorama in ./.local/lib/python2.7/site-packages (from ray==0.5.3) (0.4.0)
Requirement already satisfied: six>=1.0.0 in ./.local/lib/python2.7/site-packages (from ray==0.5.3) (1.11.0)
Requirement already satisfied: redis in ./.local/lib/python2.7/site-packages (from ray==0.5.3) (2.10.6)
Requirement already satisfied: click in ./.local/lib/python2.7/site-packages (from ray==0.5.3) (7.0)
Requirement already satisfied: pytest in ./.local/lib/python2.7/site-packages (from ray==0.5.3) (3.9.3)
Requirement already satisfied: funcsigs in ./.local/lib/python2.7/site-packages (from ray==0.5.3) (1.0.2)
Requirement already satisfied: pyyaml in ./.local/lib/python2.7/site-packages (from ray==0.5.3) (3.13)
Requirement already satisfied: numpy in ./.local/lib/python2.7/site-packages (from ray==0.5.3) (1.15.3)
Requirement already satisfied: atomicwrites>=1.0 in ./.local/lib/python2.7/site-packages (from pytest->ray==0.5.3) (1.2.1)
Requirement already satisfied: py>=1.5.0 in ./.local/lib/python2.7/site-packages (from pytest->ray==0.5.3) (1.7.0)
Requirement already satisfied: pluggy>=0.7 in ./.local/lib/python2.7/site-packages (from pytest->ray==0.5.3) (0.8.0)
Requirement already satisfied: setuptools in ./.local/lib/python2.7/site-packages (from pytest->ray==0.5.3) (40.5.0)
Requirement already satisfied: pathlib2>=2.2.0; python_version < "3.6" in ./.local/lib/python2.7/site-packages (from pytest->ray==0.5.3) (2.3.2)
Requirement already satisfied: more-itertools>=4.0.0 in ./.local/lib/python2.7/site-packages (from pytest->ray==0.5.3) (4.3.0)
Requirement already satisfied: attrs>=17.4.0 in ./.local/lib/python2.7/site-packages (from pytest->ray==0.5.3) (18.2.0)
Requirement already satisfied: scandir; python_version < "3.5" in ./.local/lib/python2.7/site-packages (from pathlib2>=2.2.0; python_version < "3.6"->pytest->ray==0.5.3) (1.9.0)

```
