### ISSUE TITLE
[Core] Ray fails to serialize no-args exception

### ISSUE THREAD

**Issue by iamhatesz** [ray-project/ray#31806]
### What happened + What you expected to happen

Ray serializes and deserializes exceptions in an unexpected, for a developer, way. For example, it fails when there is a custom exception with no args:

```python
class NoArgsException(Exception):
    def __init__(self):
        super().__init__("There was another exception")
```

This ends up with (full reproduction below):

```
2023-01-20 16:26:23,867	ERROR serialization.py:371 -- Failed to unpickle serialized exception
Traceback (most recent call last):
  File "/home/iamhatesz/.pyenv/versions/alan-brain-py3.10/lib/python3.10/site-packages/ray/exceptions.py", line 46, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
TypeError: NoArgsException.__init__() takes 1 positional argument but 2 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/iamhatesz/.pyenv/versions/alan-brain-py3.10/lib/python3.10/site-packages/ray/_private/serialization.py", line 369, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/iamhatesz/.pyenv/versions/alan-brain-py3.10/lib/python3.10/site-packages/ray/_private/serialization.py", line 275, in _deserialize_object
    return RayError.from_bytes(obj)
  File "/home/iamhatesz/.pyenv/versions/alan-brain-py3.10/lib/python3.10/site-packages/ray/exceptions.py", line 40, in from_bytes
    return RayError.from_ray_exception(ray_exception)
  File "/home/iamhatesz/.pyenv/versions/alan-brain-py3.10/lib/python3.10/site-packages/ray/exceptions.py", line 49, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception
Traceback (most recent call last):
  File "/home/iamhatesz/.config/JetBrains/PyCharm2022.2/scratches/ray_exception_test.py", line 37, in <module>
    main()
  File "/home/iamhatesz/.config/JetBrains/PyCharm2022.2/scratches/ray_exception_test.py", line 27, in main
    result = ray.get(ref)
  File "/home/iamhatesz/.pyenv/versions/alan-brain-py3.10/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/iamhatesz/.pyenv/versions/alan-brain-py3.10/lib/python3.10/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception
traceback: Traceback (most recent call last):
  File "/home/iamhatesz/.pyenv/versions/alan-brain-py3.10/lib/python3.10/site-packages/ray/exceptions.py", line 46, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
TypeError: NoArgsException.__init__() takes 1 positional argument but 2 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/iamhatesz/.pyenv/versions/alan-brain-py3.10/lib/python3.10/site-packages/ray/_private/serialization.py", line 369, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/iamhatesz/.pyenv/versions/alan-brain-py3.10/lib/python3.10/site-packages/ray/_private/serialization.py", line 275, in _deserialize_object
    return RayError.from_bytes(obj)
  File "/home/iamhatesz/.pyenv/versions/alan-brain-py3.10/lib/python3.10/site-packages/ray/exceptions.py", line 40, in from_bytes
    return RayError.from_ray_exception(ray_exception)
  File "/home/iamhatesz/.pyenv/versions/alan-brain-py3.10/lib/python3.10/site-packages/ray/exceptions.py", line 49, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception


Process finished with exit code 1
```

The situation is not much better for exception with args:

```python
class SingleArgException(Exception):
    def __init__(self, why: str):
        super().__init__(f"There was an exception: {why}")
        self.why = why
```

```python
print(repr(e))
```

```
RayTaskError(SingleArgException)(SingleArgException('There was an exception: There was an exception: FIRE FIRE FIRE'))
```

The error message is doubled and there's no `why` in `__repr__`.

### Versions / Dependencies

Ray 2.2.0, Ubuntu 22.04

### Reproduction script

```python
import ray


class SingleArgException(Exception):
    def __init__(self, why: str):
        super().__init__(f"There was an exception: {why}")
        self.why = why


class NoArgsException(Exception):
    def __init__(self):
        super().__init__("There was another exception")


@ray.remote
def collect_trajectory():
    print("Collecting...")
    raise SingleArgException("FIRE FIRE FIRE")
    # raise NoArgsException()


def main():
    ray.init(include_dashboard=False)

    ref = collect_trajectory.remote()
    try:
        result = ray.get(ref)
        print(result)
    except SingleArgException as e:
        print(e)
        print(repr(e))
        print(e.why)
    except NoArgsException as e:
        print(e)


if __name__ == "__main__":
    main()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by iamhatesz** [comment]
After some tests it turned out that this is more a Python built-in problem, sorry.
