### ISSUE TITLE
ray.exceptions.RuntimeEnvSetupError

### ISSUE THREAD

**Issue by jdefriel** [ray-project/ray#31818]
### What happened + What you expected to happen

I am trying to run Ray Tune for hyperparameter tuning and it starts to initialize but then throws a Runtime error. Please see the dashboard_agent.log for further details

023-01-20 14:15:21,006 INFO agent.py:105 -- Parent pid is 748163
2023-01-20 14:15:21,007 INFO agent.py:131 -- Dashboard agent grpc address: 0.0.0.0:44105
2023-01-20 14:15:21,010 INFO utils.py:112 -- Get all modules by type: DashboardAgentModule
2023-01-20 14:15:21,216 INFO utils.py:145 -- Available modules: [<class 'ray.dashboard.modules.event.event_agent.EventAgent'>, <class 'ray.dashboa>
2023-01-20 14:15:21,216 INFO agent.py:160 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.event.event_agent.EventAgent'>
2023-01-20 14:15:21,216 INFO event_agent.py:38 -- Event agent cache buffer size: 10240
2023-01-20 14:15:21,216 INFO agent.py:160 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.healthz.healthz_agent.HealthzAgent'>
2023-01-20 14:15:21,216 INFO agent.py:160 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.job.job_agent.JobAgent'>
2023-01-20 14:15:21,216 INFO agent.py:160 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.log.log_agent.LogAgent'>
2023-01-20 14:15:21,218 INFO agent.py:160 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.log.log_agent.LogAgentV1Grpc'>
2023-01-20 14:15:21,218 INFO agent.py:160 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.reporter.reporter_agent.ReporterAgent'>
2023-01-20 14:15:21,219 INFO agent.py:160 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.runtime_env.runtime_env_agent.RuntimeEnvA>
2023-01-20 14:15:21,219 INFO agent.py:160 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.serve.serve_agent.ServeAgent'>
2023-01-20 14:15:21,219 INFO agent.py:165 -- Loaded 8 modules.
2023-01-20 14:15:21,221 ERROR http_server_agent.py:67 -- Agent port #52365 already in use. Failed to start agent. Ensure port #52365 is available,>
2023-01-20 14:15:21,221 ERROR agent.py:290 -- Failed to start http server. Agent will stay alive but disable the http service.
Traceback (most recent call last):
  File "/home/jdefriel/miniconda3/envs/torch/lib/python3.10/site-packages/ray/dashboard/agent.py", line 285, in run
    self.http_server = await self._configure_http_server(modules)
  File "/home/jdefriel/miniconda3/envs/torch/lib/python3.10/site-packages/ray/dashboard/agent.py", line 150, in _configure_http_server
    await http_server.start(modules)
  File "/home/jdefriel/miniconda3/envs/torch/lib/python3.10/site-packages/ray/dashboard/http_server_agent.py", line 72, in start
    raise e
  File "/home/jdefriel/miniconda3/envs/torch/lib/python3.10/site-packages/ray/dashboard/http_server_agent.py", line 65, in start
    await site.start()
  File "/home/jdefriel/miniconda3/envs/torch/lib/python3.10/site-packages/aiohttp/web_runner.py", line 121, in start
    self._server = await loop.create_server(
  File "/home/jdefriel/miniconda3/envs/torch/lib/python3.10/asyncio/base_events.py", line 1508, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 52365): address already in use
2023-01-20 14:15:21,221 ERROR base_events.py:1747 -- Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f9544b36620>
2023-01-20 14:15:21,223 INFO event_agent.py:56 -- Report events to 192.168.86.233:37011
2023-01-20 14:15:21,223 INFO event_utils.py:131 -- Monitor events logs modified after 1674247521.16718 on /tmp/ray/session_2023-01-20_14-15-18_397>

### Versions / Dependencies

Ray 2.2.0
python 3.10.8
PyTorch 1.13.0

Local machine
1 CPU
2 GPU

### Reproduction script

import ray
from ray import tune
from ray.tune.schedulers import ASHAScheduler

import os

ray.init()
assert ray.is_initialized()

def ddp_setup():
    init_process_group(backend="nccl")

def define_model(
                    param_config = None):

    # Load train and val datasets
    train_dataset = Dataset(train_data_cfg)
    if val_data_cfg.files != "None":
        val_dataset = Dataset(val_data_cfg)
    else:
        val_dataset = None
    if test_data_cfg.files != "None":
        test_dataset = Dataset(test_data_cfg)
    else:
        test_dataset = None
    
    performer_cfg.n_layer = param_config["n_layer"]

    model = PerformerEncoderClassifier(performer_cfg)
    optimizer = create_optimizer(model, opt_cfg)

    return model, optimizer, scheduler, train_dataset, test_dataset, val_dataset

def objective(param_config):

    model, optimizer, scheduler, train_data, test_data, val_data = define_model(param_config)

    trainer = Trainer(trainer_cfg, model, optimizer,
                      scheduler, train_data, test_data, val_data)
    trainer.train()

@hydra.main(version_base=None, config_path="config", config_name="disco_ray_tune_cfg")
def main(cfg: DictConfig):
    ddp_setup()

    param_config = {
        "n_layer": tune.sample_from(lambda _: 4 * np.random.randint(1,10)),
    }

    opt_func = lambda param_config: objective(param_config)

    tune_scheduler = ASHAScheduler(
        max_t=tune_cfg.max_t,
        grace_period=tune_cfg.grace_period,
        reduction_factor=tune_cfg.reduction_factor
    )

    tuner = tune.Tuner(
        tune.with_resources(
            tune.with_parameters(opt_func),
            resources={"gpu": tune_cfg.num_gpus}
        ),
        tune_config=tune.TuneConfig(
            metric="f1",
            mode="max",
            scheduler=tune_scheduler,
            num_samples=trainer_cfg.batch_size
        ),
        param_space=param_config
    )

    results = tuner.fit()

    best_results = results.get_best_results("f1", "max")
        
    print(f"Best trial config: {best_results.config}")
    print(f"Best trial final validation f1: {best_results.metrics['f1']}")
    print(f"Best trial final validation loss: {best_results.metrics['loss']}")
    print(f"Best tiral final validation accuracy: {best_results.metrics['accuracy']}")

    destroy_process_group()

if __name__ == "__main__":
    main()

### Issue Severity

High: It blocks me from completing my task.

**Comment by jdefriel** [comment]
I updated Ray and I got past this issue... on to the next one.
