### ISSUE TITLE
[AIR] TorchTrainer exit failed during _fetch_next_result

### ISSUE THREAD

**Issue by mizhazha** [ray-project/ray#31828]
### What happened + What you expected to happen

I took the official mnist example, and use python client to submit the job to Kubernetes cluster. 
After the training finished, the job failed at the report step. I expect the job to exit successfully. 
```
[2m[36m(RayTrainWorker pid=1942, ip=100.97.252.234)[0m 17-Jan-23 17:21:19 [Worker:0] [INFO] Final Sync to HDFS completed!
[2m[36m(RayTrainWorker pid=1942, ip=100.97.252.234)[0m 17-Jan-23 17:21:19 [Worker:0] [INFO] Returning from train func!!
2023-01-17 17:21:35,472	WARNING worker.py:1829 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff686c4586a18aa58bf9747eb504000000 Worker ID: 0c62b78d30f3642bc1fc9a6f3cb257202e1230b03d988031722bc993 Node ID: 38300cefdc3b42caebdba478cc1da1adbba154304cecb24fd8ba1a7e Worker IP address: 100.97.252.234 Worker port: 10016 Worker PID: 1942 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
2023-01-17 17:21:35,509	ERROR trial_runner.py:980 -- Trial TorchTrainer_b13e7_00000: Error processing event.
ray.exceptions.RayTaskError(RuntimeError): [36mray::TrainTrainable.train()[39m (pid=1876, ip=100.97.252.234, repr=TorchTrainer)
  File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/tune/trainable/trainable.py", line 347, in train
    result = self.step()
  File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 417, in step
    self._report_thread_runner_error(block=True)
  File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 589, in _report_thread_runner_error
    raise e
  File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 289, in run
    self._entrypoint()
  File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 365, in entrypoint
    self._status_reporter.get_checkpoint(),
  File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/train/base_trainer.py", line 460, in _trainable_func
    super()._trainable_func(self._merged_config, reporter, checkpoint_dir)
  File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 684, in _trainable_func
    output = fn()
  File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/train/base_trainer.py", line 375, in train_func
    trainer.training_loop()
  File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/train/data_parallel_trainer.py", line 358, in training_loop
    for results in training_iterator:
  File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/train/trainer.py", line 758, in __next__
    next_results = self._run_with_error_handling(self._fetch_next_result)
  File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/train/trainer.py", line 722, in _run_with_error_handling
    return func()
  File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/train/trainer.py", line 784, in _fetch_next_result
    results = self._backend_executor.get_next_results()
  File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/train/_internal/backend_executor.py", line 389, in get_next_results
    results = self.get_with_failure_handling(futures)
  File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/train/_internal/backend_executor.py", line 481, in get_with_failure_handling
    self._increment_failures()
  File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/train/_internal/backend_executor.py", line 530, in _increment_failures
    ) from None
RuntimeError: Training has failed even after 1 attempts. You can change the number of max failure attempts by setting the `max_retries` arg in your `Trainer`.
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m 2023-01-17 17:21:35,469	ERROR utils.py:54 -- The actor died unexpectedly before finishing this task.
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m 	class_name: RayTrainWorker
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m 	actor_id: 686c4586a18aa58bf9747eb504000000
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m 	pid: 1942
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m 	namespace: 0ffa894b-5410-4969-8889-0f8ac86551c4
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m 	ip: 100.97.252.234
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m Traceback (most recent call last):
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m   File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/train/_internal/utils.py", line 52, in check_for_failure
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m     ray.get(object_ref)
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m   File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m     return func(*args, **kwargs)
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m   File "/home/jobuser/build/lipy-drex/environments/satellites/python/lib/python3.7/site-packages/ray/_private/worker.py", line 2277, in get
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m     raise value
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m 	class_name: RayTrainWorker
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m 	actor_id: 686c4586a18aa58bf9747eb504000000
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m 	pid: 1942
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m 	namespace: 0ffa894b-5410-4969-8889-0f8ac86551c4
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m 	ip: 100.97.252.234
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m 2023-01-17 17:21:35,470	INFO utils.py:56 -- Worker 0 has failed.
[2m[36m(TorchTrainer pid=1876, ip=100.97.252.234)[0m 2023-01-17 17:21:35,470	ERROR function_trainable.py:298 -- Runner Thread raised error.
```
Here is how I author the report code: 
```
for _ in range(epochs):
        train_epoch(train_dataloader, model, loss_fn, optimizer)
        loss = validate_epoch(test_dataloader, model, loss_fn)
        loss_results.append(loss)
        train.report({"loss":loss})
```

### Versions / Dependencies

Ray 2.0

### Reproduction script

Here is how I author the report code: 
```
for _ in range(epochs):
        train_epoch(train_dataloader, model, loss_fn, optimizer)
        loss = validate_epoch(test_dataloader, model, loss_fn)
        loss_results.append(loss)
        train.report({"loss":loss})
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by mizhazha** [comment]
Resolved by bumping up memory. Sorry for the noise.

**Comment by amogkam** [comment]
Thanks for raising this @mizhazha! By bumping memory do you mean available memory in your instance, or the object store memory?

Also, if you upgrade to Ray 2.2, you should see a much better error message here :)

**Comment by mizhazha** [comment]
Thanks @amogkam for the suggestion.  After I bumping up the container memory, the above error did go, but there is still some warning message which I cannot get a hang of. 
```
2023-01-21 01:49:30,010	WARNING worker.py:1829 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffda2292ce2b9070ff85d65dae02000000 Worker ID: e95d66ae5c120837884230b03830de280d90586dfeb3998a2edc9b6f Node ID: 6c43e6e6f30a08e1316120942101f647700eaecb0e9cfc46878c66d5 Worker IP address: 100.96.157.251 Worker port: 10004 Worker PID: 258 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
(_get_recursive_files_and_stats pid=691) E0121 01:49:49.662029266     751 chttp2_transport.cc:1132]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
(_unpack_from_actor pid=692) E0121 01:49:49.607499028     750 chttp2_transport.cc:1132]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
```
I also noticed that the job status is still RUNNING after the training has completed for more than 5 mins and eventually it was marked as succeeded. I am wondering if you have any insight on what is going on? I was also tailing logs using ray client, not sure whether that's related.

**Comment by amogkam** [comment]
You can check the logs for the worker id (e95d66ae5c120837884230b03830de280d90586dfeb3998a2edc9b6f) under `/tmp/ray/session_latest/logs`.

**Comment by mizhazha** [comment]
Interestingly, I found out this issue is not related to Ray at all. The torchvision lib was not installed properly due to some conflicts, which throws warning
```
>>> import torchvision /home/jobuser/.local/lib/python3.7/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/jobuser/.local/lib/python3.7/site-packages/torchvision/image.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE warn(f"Failed to load image Python extension: {e}") 
```
After I reinstalled torchvision lib, the TorchTrainer issue mentioned originally is resolved. Not sure how these interact, but the tracing information is a bit misleading.

**Comment by xwjiang2010** [comment]
Closing the issue out as this does not seem to be related to Ray.
