### ISSUE TITLE
[Tune] OpenSSL version outdated

### ISSUE THREAD

**Issue by tbukic** [ray-project/ray#31852]
### What happened + What you expected to happen

When running job which sincs to Azure I'm getting this error:

> Status message: Job failed due to an application error, last available logs (truncated to 20,000 chars):
>     from .lib import DatalakeRESTInterface
>   File "/tmp/ray/session_2023-01-23_01-11-06_047370_8/runtime_resources/pip/147b9dd6a1b623728a860b6dc85a7b683340befe/virtualenv/lib/python3.10/site-packages/azure/datalake/store/lib.py", line 39, in <module>
>     from requests.packages.urllib3.contrib.pyopenssl import extract_from_urllib3 as enforce_no_py_open_ssl
>   File "/tmp/ray/session_2023-01-23_01-11-06_047370_8/runtime_resources/pip/147b9dd6a1b623728a860b6dc85a7b683340befe/virtualenv/lib/python3.10/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
>     import OpenSSL.crypto
>   File "/home/ray/anaconda3/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
>     from OpenSSL import crypto, SSL
>   File "/home/ray/anaconda3/lib/python3.10/site-packages/OpenSSL/crypto.py", line 3268, in <module>
>     _lib.OpenSSL_add_all_algorithms()
> AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

```
>>> import OpenSSL
>>> OpenSSL.__version__
'22.0.0'
>>> import cryptography 
>>> cryptography.__version__
'38.0.1'
```
Despite versions are not a problematic combination as described [here](https://stackoverflow.com/a/75053968/17810929), manually updating `pyopenssl` to `23.0.0` solved the problem for me.

### Versions / Dependencies

Ray image: '25d3d5-py310-cpu'

### Reproduction script

```
    ray.init()
    tuner = tune.Tuner(
        "PPO",
        run_config=air.RunConfig(
            stop={"episode_reward_mean": 200},
            sync_config=SyncConfig(
                upload_dir=azure_upload_dir
            ),
        ),
        tune_config=tune.TuneConfig(
            metric="episode_reward_mean",
            mode="max",
        ),
        param_space={
            "env": "CartPole-v1",
            "framework": "torch",
            "num_gpus": 0,
            "num_workers": 1,
            "lr": tune.grid_search([0.01, 0.001, 0.0001]),
            "env_config": {}
        },
    )
    tuner.fit()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by tbukic** [comment]
### Update
Seems like I actually **can't** make a workaround this. I guess I've updated a head node and it didn't crash upon the start of training. But it crashed at the end. Is it possible that later some other python env was instantiated while running from old requirements.txt or image?

```
3970Trial PPO_CartPole-v1_98ecb_00000 completed.
39712023-01-23 04:47:18,558	WARNING util.py:244 -- The `callbacks.on_trial_result` operation took 0.767 s, which may be a performance bottleneck.
39722023-01-23 04:47:18,562	WARNING util.py:244 -- The `process_trial_result` operation took 0.772 s, which may be a performance bottleneck.
39732023-01-23 04:47:18,562	WARNING util.py:244 -- Processing trial results took 0.772 s, which may be a performance bottleneck. Please consider reporting results less frequently to Ray Tune.
39742023-01-23 04:47:18,562	WARNING util.py:244 -- The `process_trial_result` operation took 0.774 s, which may be a performance bottleneck.
3975[2m[36m(PPO pid=1264, ip=)[0m Exception in thread Thread-4 (_try_fn):
3976[2m[36m(PPO pid=1264, ip=)[0m Traceback (most recent call last):
3977[2m[36m(PPO pid=1264, ip=)[0m   File "/home/ray/anaconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
3978[2m[36m(PPO pid=1264, ip=)[0m     self.run()
3979[2m[36m(PPO pid=1264, ip=)[0m   File "/home/ray/anaconda3/lib/python3.10/threading.py", line 953, in run
3980[2m[36m(PPO pid=1264, ip=)[0m     self._target(*self._args, **self._kwargs)
3981[2m[36m(PPO pid=1264, ip=)[0m   File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/tune/utils/util.py", line 137, in _try_fn
3982[2m[36m(PPO pid=1264, ip=)[0m     fn()
3983[2m[36m(PPO pid=1264, ip=)[0m   File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 589, in <lambda>
3984[2m[36m(PPO pid=1264, ip=)[0m     lambda: checkpoint.to_uri(checkpoint_uri),
3985[2m[36m(PPO pid=1264, ip=)[0m   File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/air/checkpoint.py", line 716, in to_uri
3986[2m[36m(PPO pid=1264, ip=)[0m     if not is_non_local_path_uri(uri):
3987[2m[36m(PPO pid=1264, ip=)[0m   File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/air/_internal/remote_storage.py", line 72, in is_non_local_path_uri
3988[2m[36m(PPO pid=1264, ip=)[0m     if bool(get_fs_and_path(uri)[0]):
3989[2m[36m(PPO pid=1264, ip=)[0m   File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/air/_internal/remote_storage.py", line 109, in get_fs_and_path
3990[2m[36m(PPO pid=1264, ip=)[0m     fsspec_fs = fsspec.filesystem(parsed.scheme)
3991[2m[36m(PPO pid=1264, ip=)[0m   File "/tmp/ray/session_2023-01-23_01-11-06_047370_8/runtime_resources/pip/147b9dd6a1b623728a860b6dc85a7b683340befe/virtualenv/lib/python3.10/site-packages/fsspec/registry.py", line 283, in filesystem
3992[2m[36m(PPO pid=1264, ip=)[0m     cls = get_filesystem_class(protocol)
3993[2m[36m(PPO pid=1264, ip=)[0m   File "/tmp/ray/session_2023-01-23_01-11-06_047370_8/runtime_resources/pip/147b9dd6a1b623728a860b6dc85a7b683340befe/virtualenv/lib/python3.10/site-packages/fsspec/registry.py", line 243, in get_filesystem_class
3994[2m[36m(PPO pid=1264, ip=)[0m     register_implementation(protocol, _import_class(bit["class"]))
3995[2m[36m(PPO pid=1264, ip=)[0m   File "/tmp/ray/session_2023-01-23_01-11-06_047370_8/runtime_resources/pip/147b9dd6a1b623728a860b6dc85a7b683340befe/virtualenv/lib/python3.10/site-packages/fsspec/registry.py", line 266, in _import_class
3996[2m[36m(PPO pid=1264, ip=)[0m     mod = importlib.import_module(mod)
3997[2m[36m(PPO pid=1264, ip=)[0m   File "/home/ray/anaconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
3998[2m[36m(PPO pid=1264, ip=)[0m     return _bootstrap._gcd_import(name[level:], package, level)
3999[2m[36m(PPO pid=1264, ip=)[0m   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
4000[2m[36m(PPO pid=1264, ip=)[0m   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
4001[2m[36m(PPO pid=1264, ip=)[0m   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
4002[2m[36m(PPO pid=1264, ip=)[0m   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
4003[2m[36m(PPO pid=1264, ip=)[0m   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
4004[2m[36m(PPO pid=1264, ip=)[0m   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
4005[2m[36m(PPO pid=1264, ip=)[0m   File "/tmp/ray/session_2023-01-23_01-11-06_047370_8/runtime_resources/pip/147b9dd6a1b623728a860b6dc85a7b683340befe/virtualenv/lib/python3.10/site-packages/adlfs/__init__.py", line 2, in <module>
4006[2m[36m(PPO pid=1264, ip=)[0m     from .gen1 import AzureDatalakeFileSystem
4007[2m[36m(PPO pid=1264, ip=)[0m   File "/tmp/ray/session_2023-01-23_01-11-06_047370_8/runtime_resources/pip/147b9dd6a1b623728a860b6dc85a7b683340befe/virtualenv/lib/python3.10/site-packages/adlfs/gen1.py", line 9, in <module>
4008[2m[36m(PPO pid=1264, ip=)[0m     from azure.datalake.store import AzureDLFileSystem, lib
4009[2m[36m(PPO pid=1264, ip=)[0m   File "/tmp/ray/session_2023-01-23_01-11-06_047370_8/runtime_resources/pip/147b9dd6a1b623728a860b6dc85a7b683340befe/virtualenv/lib/python3.10/site-packages/azure/datalake/store/__init__.py", line 11, in <module>
4010[2m[36m(PPO pid=1264, ip=)[0m     from .core import AzureDLFileSystem
4011[2m[36m(PPO pid=1264, ip=)[0m   File "/tmp/ray/session_2023-01-23_01-11-06_047370_8/runtime_resources/pip/147b9dd6a1b623728a860b6dc85a7b683340befe/virtualenv/lib/python3.10/site-packages/azure/datalake/store/core.py", line 27, in <module>
4012[2m[36m(PPO pid=1264, ip=)[0m     from .lib import DatalakeRESTInterface
4013[2m[36m(PPO pid=1264, ip=)[0m   File "/tmp/ray/session_2023-01-23_01-11-06_047370_8/runtime_resources/pip/147b9dd6a1b623728a860b6dc85a7b683340befe/virtualenv/lib/python3.10/site-packages/azure/datalake/store/lib.py", line 39, in <module>
4014[2m[36m(PPO pid=1264, ip=)[0m     from requests.packages.urllib3.contrib.pyopenssl import extract_from_urllib3 as enforce_no_py_open_ssl
4015[2m[36m(PPO pid=1264, ip=)[0m   File "/tmp/ray/session_2023-01-23_01-11-06_047370_8/runtime_resources/pip/147b9dd6a1b623728a860b6dc85a7b683340befe/virtualenv/lib/python3.10/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
4016[2m[36m(PPO pid=1264, ip=)[0m     import OpenSSL.crypto
4017[2m[36m(PPO pid=1264, ip=)[0m   File "/home/ray/anaconda3/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
4018[2m[36m(PPO pid=1264, ip=)[0m     from OpenSSL import crypto, SSL
4019[2m[36m(PPO pid=1264, ip=)[0m   File "/home/ray/anaconda3/lib/python3.10/site-packages/OpenSSL/crypto.py", line 3268, in <module>
4020[2m[36m(PPO pid=1264, ip=)[0m     _lib.OpenSSL_add_all_algorithms()
4021[2m[36m(PPO pid=1264, ip=)[0m AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
```

**Comment by idantene** [comment]
I'm experiencing the same issue, did you ever solve it?
