### ISSUE TITLE
[Ray release glue.py] `Error setting up remote environment: Error uploading local dir to session rllib_stress_tests_1674368507.`

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#31878]
Seeing this in the following release tests:
* dask_on_ray_1tb_sort https://buildkite.com/ray-project/release-tests-branch/builds/1304#0185d156-acdf-4b5c-b63f-9fc4f6b2f7c2
* rllib_stress_tests https://buildkite.com/ray-project/release-tests-branch/builds/1305#0185d81d-437e-49ff-9103-4bf92a4d11ea
* shuffle_1tb_5000_partitions https://buildkite.com/ray-project/release-tests-branch/builds/1304#0185d156-ace6-4f9a-8255-25901c91daa7
* map_batches_benchmark_single_node https://buildkite.com/ray-project/release-tests-branch/builds/1333#0186130c-2057-4ecf-8be2-25bc4159fade

```
[ERROR 2023-01-21 22:46:41,582] run_release_test.py: 157  Error setting up remote environment: Error uploading local dir to session rllib_stress_tests_1674368507.
--
  | Traceback (most recent call last):
  | File "/tmp/release-4K7NOSGKrN/release/ray_release/command_runner/sdk_runner.py", line 69, in prepare_remote_env
  | self.file_manager.upload()
  | File "/tmp/release-4K7NOSGKrN/release/ray_release/file_manager/job_file_manager.py", line 122, in upload
  | self._push_local_dir()
  | File "/tmp/release-4K7NOSGKrN/release/ray_release/file_manager/job_file_manager.py", line 107, in _push_local_dir
  | f"Error uploading local dir to session "
  | ray_release.exception.FileUploadError: Error uploading local dir to session rllib_stress_tests_1674368507.
  |  
  | The above exception was the direct cause of the following exception:
  |  
  | Traceback (most recent call last):
  | File "ray_release/scripts/run_release_test.py", line 153, in main
  | no_terminate=no_terminate,
  | File "/tmp/release-4K7NOSGKrN/release/ray_release/glue.py", line 404, in run_release_test
  | raise pipeline_exception
  | File "/tmp/release-4K7NOSGKrN/release/ray_release/glue.py", line 275, in run_release_test
  | command_runner.prepare_remote_env()
  | File "/tmp/release-4K7NOSGKrN/release/ray_release/command_runner/sdk_runner.py", line 73, in prepare_remote_env
  | ) from e
  | ray_release.exception.RemoteEnvSetupError: Error setting up remote environment: Error uploading local dir to session rllib_stress_tests_1674368507.
  | ERROR:ray_release.logger:Error setting up remote environment: Error uploading local dir to session rllib_stress_tests_1674368507.
  | Traceback (most recent call last):
  | File "/tmp/release-4K7NOSGKrN/release/ray_release/command_runner/sdk_runner.py", line 69, in prepare_remote_env
  | self.file_manager.upload()
  | File "/tmp/release-4K7NOSGKrN/release/ray_release/file_manager/job_file_manager.py", line 122, in upload
  | self._push_local_dir()
  | File "/tmp/release-4K7NOSGKrN/release/ray_release/file_manager/job_file_manager.py", line 107, in _push_local_dir
  | f"Error uploading local dir to session "
  | ray_release.exception.FileUploadError: Error uploading local dir to session rllib_stress_tests_1674368507.
```

cc @krfricke

**Comment by cadedaniel** [comment]
@krfricke I am seeing this in 3 release test failures, is this easily fixable?

**Comment by krfricke** [comment]
So the upload should generally work. It looks to me like there was an anyscale SDK/API error. The upload job does not show up in the anyscale logs.

Best course of action here is to just retry (I triggered a retry for one of the tests).

**Comment by cadedaniel** [comment]
Thanks. I'll encapsulate this knowledge in a doc for the next release manager.

**Comment by cadedaniel** [comment]
Do we already have retries for this in the glue code? If so I think we can close this

**Comment by krfricke** [comment]
I don't think we have a retry. But we're going to move everything to jobs (first Ray jobs then Anyscale jobs) soon which will not use any file upload functionality (we rely on working dir upload) so this should be solved soon.

**Comment by can-anyscale** [comment]
sdk_runner is deprecated, everything is using anyscale now
