### ISSUE TITLE
[Ray 2.3 release] `cluster_tune_scale_up_down` release test fails

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#31883]
https://buildkite.com/ray-project/release-tests-branch/builds/1303#0185d157-4ce0-43da-a273-478fd7fbf07e

```
2023-01-20 15:32:36,885	INFO tune.py:782 -- Total run time: 1806.15 seconds (1805.96 seconds for the tuning loop).
--
  | Traceback (most recent call last):
  | File "workloads/tune_scale_up_down.py", line 57, in <module>
  | main()
  | File "workloads/tune_scale_up_down.py", line 53, in main
  | assert node_counter.node_counts[-1] == 1, "Cluster didn't scale down to 1 node."
  | AssertionError: Cluster didn't scale down to 1 node.
```

**Comment by cadedaniel** [comment]
cc @krfricke , I think the oncall switched to you

**Comment by krfricke** [comment]
I'll rerun, if the issue persists I'll check with Ray core or product infra
