### ISSUE TITLE
[Ray 2.3 release] [rllib] `rllib_learning_tests_marwil_torch` release test fails

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#31886]
```
Traceback (most recent call last):
  File "learning_tests/run.py", line 57, in <module>
    framework=args.framework,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/test_utils.py", line 859, in run_learning_tests_from_yaml
    max_report_frequency=30,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 880, in run_experiments
    callbacks=callbacks,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 775, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [MARWIL_HalfCheetah-v4_94bed_00000])
```

**Comment by kouroshHakha** [comment]
Not really release blocker since the training data is broken and we knew about this. @sven1977 or I will generate some new datasets for this release test but it is still fine if we don't get green on this by release.
