### ISSUE TITLE
[Ray 2.3 release] [core] stress_test_state_api_scale fails with `Mismatch log file`

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#31887]
https://buildkite.com/ray-project/release-tests-branch/builds/1303#0185d157-4e15-4b9b-8cce-b473d4641435

```
Traceback (most recent call last):
  File "stress_tests/test_state_api_scale.py", line 438, in <module>
    test()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "stress_tests/test_state_api_scale.py", line 399, in test
    test_large_log_file(log_file_size_byte=n)
  File "stress_tests/test_state_api_scale.py", line 286, in test_large_log_file
    assert expected_hash == ctx.hexdigest(), "Mismatch log file"
AssertionError: Mismatch log file
```

**Comment by rickyyx** [comment]
Fixed in https://github.com/ray-project/ray/pull/31865
