### ISSUE TITLE
[tune] Serialization error: '_io.TextIOWrapper'

### ISSUE THREAD

**Issue by shonaka** [ray-project/ray#3192]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Ray installed from (source or binary)**: pip install ray
- **Ray version**: 0.5.3
- **Python version**: 3.5
- **Exact command to reproduce**:

### Describe the problem

I'm trying to use ray.tune for my project and modified the code from https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mnist_pytorch.py and
https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mnist_pytorch_trainable.py
I'm getting the following cannot serialize error which I cannot solve. I would really appreciate your help.

### Source code / logs

Source Code:
```python
ray.init()
        sched = AsyncHyperBandScheduler(
            time_attr="training_iteration",
            reward_attr="neg_mean_loss"
        )

        # ===== Training & Testing =====
        tune.run_experiments(
            {
                "exp": {
                    "stop": {
                        "mean_accuracy": 0.9,
                        "training_iteration": 1 if cfig.smoke_test else params.num_epochs
                    },
                    "trial_resources": {
                        "gpu": 1
                    },
                    "run": TrainEach, # This is a class
                    "num_samples": 1 if cfig.smoke_test else params.batch_size,
                    "checkpoint_at_end": True,
                    "config": {
                        "log": log,
                        "cfig": cfig,
                        "params": params,
                        "paths": paths,
                        "lr": lambda spec: np.random.uniform(0.0001, 0.01),
                    }
                }
            },
            verbose=2,
            scheduler=sched
        )
```

Error logs:
```
Traceback (most recent call last):
  File "/home/user/Documents/project/src/pytorch/hyperparameter_search.py", line 454, in <module>
    scheduler=sched
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/tune/tune.py", line 90, in run_experiments
    search_alg.add_configurations(experiments)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/tune/suggest/basic_variant.py", line 38, in add_configurations
    experiment_list = convert_to_experiment_list(experiments)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/tune/experiment.py", line 202, in convert_to_experiment_list
    for name, spec in experiments.items()
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/tune/experiment.py", line 202, in <listcomp>
    for name, spec in experiments.items()
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/tune/experiment.py", line 135, in from_json
    spec = copy.deepcopy(spec)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/copy.py", line 174, in deepcopy
    rv = reductor(4)
TypeError: cannot serialize '_io.TextIOWrapper' object
```

**Comment by shonaka** [comment]
In fact, if I just try to run the code without any change, I get the following error.
https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mnist_pytorch_trainable.py

```
Remote function train failed with:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/worker.py", line 923, in _process_task
    self.reraise_actor_init_error()
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/worker.py", line 267, in reraise_actor_init_error
    raise self.actor_init_error
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/tune/trainable.py", line 84, in __init__
    self._setup()
TypeError: _setup() missing 1 required positional argument: 'config'
```

**Comment by richardliaw** [comment]
Thanks for posting this issue!

Can you first install the latest ray via wheels (https://ray.readthedocs.io/en/latest/installation.html)? Your second issue should be resolved. 

The first issue I believe may be an issue where you have "log" in the configuration; would it be possible to just do that as part of the `_setup` of the Trainable?

**Comment by shonaka** [comment]
Thank you for your quick response. I really appreciate your help. As suggested, I reinstalled from wheel and the code without any change started running. However, the following new error emerged:

```
Remote function restore_from_object failed with:

Failed to get objectid ObjectID(0100000029cebe1f8be8d4575b653005c7c30aee) as argument 0 for remote function restore_from_object. It was created by remote function save_to_object which failed with:
Remote function save_to_object failed with:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/worker.py", line 801, in _process_task
    *arguments)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/function_manager.py", line 481, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/tune/trainable.py", line 256, in save_to_object
    data[os.path.basename(path)] = open(path, "rb").read()
IsADirectoryError: [Errno 21] Is a directory: '/home/user/ray_results/exp/TrainMNIST_17_lr=0.098507,momentum=0.88414_2018-11-01_20-31-3283dfv8na/tmpdue6schzsave_to_object/checkpoint_9wu1t41bi'

== Status ==
Using HyperBand: num_stopped=0 total_brackets=3
Round #0:
  Bracket(Max Size (n)=5, Milestone (r)=81, completed=100.0%): {TERMINATED: 5}
  Bracket(Max Size (n)=3, Milestone (r)=81, completed=100.0%): {TERMINATED: 8}
  Bracket(Max Size (n)=5, Milestone (r)=36, completed=3.6%): {ERROR: 1, TERMINATED: 6}
Resources requested: 3/8 CPUs, 0/2 GPUs
Result logdir: /home/user/ray_results/exp
ERROR trials:
 - TrainMNIST_17_lr=0.098507,momentum=0.88414:  ERROR [pid=27015], 328 s, 9 iter, 0.925 loss, 0.723 acc
TERMINATED trials:
 - TrainMNIST_0_lr=0.023931,momentum=0.79987:   TERMINATED [pid=4493], 39 s, 1 iter, 0.0872 loss, 0.971 acc
 - TrainMNIST_1_lr=0.031427,momentum=0.41335:   TERMINATED [pid=4423], 38 s, 1 iter, 0.121 loss, 0.965 acc
 - TrainMNIST_2_lr=0.063787,momentum=0.85323:   TERMINATED [pid=4502], 39 s, 1 iter, 0.156 loss, 0.956 acc
 - TrainMNIST_3_lr=0.05126,momentum=0.74525:    TERMINATED [pid=4421], 38 s, 1 iter, 0.0905 loss, 0.971 acc
 - TrainMNIST_4_lr=0.022249,momentum=0.45414:   TERMINATED [pid=4498], 38 s, 1 iter, 0.139 loss, 0.958 acc
 - TrainMNIST_5_lr=0.052895,momentum=0.413:     TERMINATED [pid=4422], 37 s, 1 iter, 0.0985 loss, 0.97 acc
 - TrainMNIST_6_lr=0.07729,momentum=0.45828:    TERMINATED [pid=4420], 38 s, 1 iter, 0.0863 loss, 0.974 acc
 - TrainMNIST_7_lr=0.065795,momentum=0.58677:   TERMINATED [pid=11554], 36 s, 1 iter, 0.0944 loss, 0.972 acc
 - TrainMNIST_8_lr=0.063318,momentum=0.8058:    TERMINATED [pid=4419], 36 s, 1 iter, 0.102 loss, 0.966 acc
 - TrainMNIST_9_lr=0.09026,momentum=0.28287:    TERMINATED [pid=4418], 38 s, 1 iter, 0.0914 loss, 0.972 acc
 - TrainMNIST_10_lr=0.054653,momentum=0.24095:  TERMINATED [pid=4416], 37 s, 1 iter, 0.105 loss, 0.969 acc
 - TrainMNIST_11_lr=0.022981,momentum=0.83481:  TERMINATED [pid=4417], 38 s, 1 iter, 0.0926 loss, 0.974 acc
 - TrainMNIST_12_lr=0.063872,momentum=0.46114:  TERMINATED [pid=11572], 37 s, 1 iter, 0.09 loss, 0.973 acc
 - TrainMNIST_13_lr=0.0065688,momentum=0.22885: TERMINATED [pid=26960], 144 s, 4 iter, 0.137 loss, 0.959 acc
 - TrainMNIST_14_lr=0.090342,momentum=0.61352:  TERMINATED [pid=26987], 36 s, 1 iter, 0.0926 loss, 0.972 acc
 - TrainMNIST_15_lr=0.0040368,momentum=0.64587: TERMINATED [pid=26988], 108 s, 3 iter, 0.14 loss, 0.957 acc
 - TrainMNIST_16_lr=0.084079,momentum=0.29146:  TERMINATED [pid=27013], 37 s, 1 iter, 0.0966 loss, 0.971 acc
 - TrainMNIST_18_lr=0.052405,momentum=0.65585:  TERMINATED [pid=26959], 36 s, 1 iter, 0.0846 loss, 0.974 acc
 - TrainMNIST_19_lr=0.0067516,momentum=0.68086: TERMINATED [pid=11555], 74 s, 2 iter, 0.129 loss, 0.96 acc

Traceback (most recent call last):
  File "/home/user/Documents/pytorch/src/torchRunRaw/test.py", line 203, in <module>
    scheduler=sched)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/tune/tune.py", line 124, in run_experiments
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [TrainMNIST_17_lr=0.098507,momentum=0.88414])
```

I will try to remove the "log" for the first issue.

Best,

**Comment by shonaka** [comment]
For the first issue, I removed "log" as you suggested. Although the initial error has been removed, now I get the following error without any error messages. Tried both with cpu and gpu but with the same error.

Does this have to do with some kind of memory error? I'm using a rather large dataset for the first issue.

```
2018-11-01 20:57:28,876 ray.services 1323 [INFO][start_ray_processes] Process STDOUT and STDERR is being redirected to /tmp/ray/session_2018-11-01_20-57-28_10654/logs.
2018-11-01 20:57:29,047 ray.services 315 [INFO][wait_for_redis_to_start] Waiting for redis server at 127.0.0.1:61576 to respond...
2018-11-01 20:57:29,246 ray.services 315 [INFO][wait_for_redis_to_start] Waiting for redis server at 127.0.0.1:26990 to respond...
2018-11-01 20:57:29,709 ray.services 1091 [INFO][start_plasma_store] Starting the Plasma object store with 13.456960716000001 GB memory using /dev/shm.
2018-11-01 20:57:30,365 ray.services 790 [INFO][start_ui]
======================================================================
2018-11-01 20:57:30,365 ray.services 791 [INFO][start_ui] View the web UI at http://localhost:8888/notebooks/ray_ui.ipynb?token=165edff8e18c3b2678df6b87947b00289121fbe13267c1fc
2018-11-01 20:57:30,365 ray.services 792 [INFO][start_ui] ======================================================================

2018-11-01 20:57:31,219 ray.tune.tune 104 [INFO][run_experiments] == Status ==
Using HyperBand: num_stopped=0 total_brackets=0
Round #0:


Killed
```

**Comment by richardliaw** [comment]
Weird, never seen this one before; any way you can find out where it’s failing? Maybe try running Tune with  `"num_samples": 1`...

**Comment by shonaka** [comment]
Thank you for your suggestion. I changed the "num_samples" to 1 and now it started running with the following error.
1) I thought the "num_samples" was a batch_size. I was currently using 32, but would this be too much to run ray.tune? "num_samples" == 1 seems to be very slow.
2) It seems like the following new error is related to importing a custom library of my own. I'm currently importing this as 
```python
import sys
sys.path.append("/home/user/Documents/customlib")
from customlib.utils.somefunction import FunctionName
```
How could I remove this error?

```
2018-11-02 09:13:39,211 ray.services 791 [INFO][start_ui] View the web UI at http://localhost:8888/notebooks/ray_ui.ipynb?token=824fee95e855818f572ad006c6626880c9c9f1583fe7794b
2018-11-02 09:13:39,211 ray.services 792 [INFO][start_ui] ======================================================================

2018-11-02 09:13:40,085 ray.tune.tune 104 [INFO][run_experiments] == Status ==
Using HyperBand: num_stopped=0 total_brackets=0
Round #0:


2018-11-02 09:13:41,904 ray.tune.log_sync 80 [INFO][__init__] Created LogSyncer for /home/user/ray_results/exp/TrainEachTrial_0_lr=0.0096341_2018-11-02_09-13-41hi_j_f7d ->
2018-11-02 09:13:41,920 ray.worker 315 [WARNING][store_and_register] WARNING: Serializing objects of type <class 'customlib.utils.somefunction.FunctionName'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.

2018-11-02 09:13:41,922 ray.worker 1753 [ERROR][print_error_messages_raylet] Traceback (most recent call last):
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/import_thread.py", line 120, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
ImportError: No module named 'customlib'
```

3) Then the program is stuck at:
```
2018-11-02 09:13:50,801 ray.tune.tune 110 [INFO][run_experiments] == Status ==
Using HyperBand: num_stopped=0 total_brackets=1
Round #0:
  Bracket(Max Size (n)=5, Milestone (r)=81, completed=0.0%): {RUNNING: 1}
Resources requested: 1/8 CPUs, 1/2 GPUs
Result logdir: /home/user/ray_results/exp
RUNNING trials:
 - TrainEach_0_lr=0.0055835:       RUNNING
```
For more than 30 minutes.

Thank you in advance for your help.

Best,

**Comment by richardliaw** [comment]
> I thought the "num_samples" was a batch_size. I was currently using 32, but would this be too much to run ray.tune? "num_samples" == 1 seems to be very slow.

This specifies the number of trials you're running...

> It seems like the following new error is related to importing a custom library of my own. 
This is a known usability problem - #2327. One workaround is to run the sys import and path appending in `_setup` of your trainable.

This should address 2 and 3.

Give this a shot and let me know?

**Comment by shonaka** [comment]
Thank you for your answer. The importing error is resolved. However, I'm still having some issues.
This time the class "TrainEach" (equivalent to TrainMNIST in the original example) in the same script is failing to be imported.

I'm defining it as follows:
```python
class TrainEach(Trainable):
    """
    A class that wraps training, validation, and testing.
    https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mnist_pytorch_trainable.py#L179
    """
    def _setup(self, config):
        # According to the feedback, we need to do this
        sys.path.append("/home/user/Documents/customlib")
...
```

ERROR LOG:
```
2018-11-02 14:34:31,085 ray.worker 1753 [ERROR][print_error_messages_raylet] Remote function __ray_terminate__ failed with:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/worker.py", line 801, in _process_task
    *arguments)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/function_manager.py", line 481, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/function_manager.py", line 367, in temporary_actor_method
    "and so cannot execute this method".format(class_name))
Exception: The actor with name TrainEach failed to be imported, and so cannot execute this method
```

**Comment by richardliaw** [comment]
When does this error occur? Is there more to this trace?

**Comment by richardliaw** [comment]
Closing this due to inactivity -- feel free to reopen
