### ISSUE TITLE
[Ray 2.3 release] tune_cloud_gcp_k8s_durable_upload fails

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32007]
https://buildkite.com/ray-project/release-tests-branch/builds/1313#0185f02a-4912-42cd-a110-3ee9629dc8a7

```
Traceback (most recent call last):
--
  | File "workloads/run_cloud_test.py", line 1305, in <module>
  | raise err
  | File "workloads/run_cloud_test.py", line 1287, in <module>
  | remote_tune_script,
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
  | return getattr(ray, func.__name__)(*args, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/api.py", line 42, in get
  | return self.worker.get(vals, timeout=timeout)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 434, in get
  | res = self._get(to_get, op_timeout)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 462, in _get
  | raise err
  | types.RayTaskError(TypeError): ray::_run_test() (pid=1438, ip=172.18.1.131)
  | File "workloads/run_cloud_test.py", line 1239, in _run_test
  | File "workloads/run_cloud_test.py", line 1175, in test_durable_upload
  | File "workloads/run_cloud_test.py", line 386, in run_resume_flow
  | File "workloads/run_cloud_test.py", line 1079, in between_experiments
  | File "workloads/run_cloud_test.py", line 692, in get_experiment_and_trial_data
  | File "workloads/run_cloud_test.py", line 554, in load_experiment_checkpoint_from_state_file
  | TypeError: __init__() missing 1 required positional argument: 'local_dir'
  | (_run_test pid=1438) Process 2168 terminated gracefully.
  | (_run_test pid=1438) Between experiments: Invoking callback
```

**Comment by cadedaniel** [comment]
The sibling tests tune_cloud_gcp_k8s_ssh_sync,  tune_cloud_gcp_k8s_no_sync_down also fail with the same error

https://buildkite.com/ray-project/release-tests-branch/builds/1313#0185f02a-490f-46dd-a179-d520adf84776
https://buildkite.com/ray-project/release-tests-branch/builds/1313#0185f02a-490c-4404-8b07-4f24e140f291

**Comment by krfricke** [comment]
Yep, that's due to some recent refactoring, I'll fix this later today. Thanks for flagging!
