### ISSUE TITLE
[datasets] Segfault in read_images_benchmark_single_node

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32006]
Exitcode 139 while a test ran. The test looks like it passed, but the glue code failed https://buildkite.com/ray-project/release-tests-branch/builds/1313#0185f02a-49cb-47d9-b976-38ff94d44d12

```
[INFO 2023-01-26 15:49:53,997] sdk_runner.py: 135  ... command still running ...(120 seconds) ...
[ERROR 2023-01-26 15:49:58,275] glue.py: 352  Command returned non-success status: 139
Traceback (most recent call last):
  File "/tmp/release-MfOemcy8m4/release/ray_release/glue.py", line 311, in run_release_test
    command, env=command_env, timeout=command_timeout
  File "/tmp/release-MfOemcy8m4/release/ray_release/command_runner/sdk_runner.py", line 155, in run_command
    raise CommandError(f"Command returned non-success status: {status_code}")
ray_release.exception.CommandError: Command returned non-success status: 139
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/tmp/release-MfOemcy8m4/release/ray_release/glue.py", line 314, in run_release_test
    raise TestCommandError(e)
ray_release.exception.TestCommandError: Command returned non-success status: 139
```

**Comment by cadedaniel** [comment]
Another instance https://buildkite.com/ray-project/release-tests-branch/builds/1314#0185f566-a0a8-40ac-abb8-42ff77bbaa04

flaky!

**Comment by can-anyscale** [comment]
Fixed, sdk-runner is deprecated
