### ISSUE TITLE
[tune] save_to_object does not work for subdirectories

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#3202]
### Describe the problem
If a path is passed to `save_to_object` where there are subdirectories, errors are thrown because currently, it assumes that the subdirectory is flat.

### Source code / logs

```
Remote function restore_from_object failed with:

Failed to get objectid ObjectID(0100000029cebe1f8be8d4575b653005c7c30aee) as argument 0 for remote function restore_from_object. It was created by remote function save_to_object which failed with:
Remote function save_to_object failed with:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/worker.py", line 801, in _process_task
    *arguments)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/function_manager.py", line 481, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/tune/trainable.py", line 256, in save_to_object
    data[os.path.basename(path)] = open(path, "rb").read()
IsADirectoryError: [Errno 21] Is a directory: '/home/user/ray_results/exp/TrainMNIST_17_lr=0.098507,momentum=0.88414_2018-11-01_20-31-3283dfv8na/tmpdue6schzsave_to_object/checkpoint_9wu1t41bi'

== Status ==
Using HyperBand: num_stopped=0 total_brackets=3
Round #0:
  Bracket(Max Size (n)=5, Milestone (r)=81, completed=100.0%): {TERMINATED: 5}
  Bracket(Max Size (n)=3, Milestone (r)=81, completed=100.0%): {TERMINATED: 8}
  Bracket(Max Size (n)=5, Milestone (r)=36, completed=3.6%): {ERROR: 1, TERMINATED: 6}
Resources requested: 3/8 CPUs, 0/2 GPUs
Result logdir: /home/user/ray_results/exp
ERROR trials:
 - TrainMNIST_17_lr=0.098507,momentum=0.88414:  ERROR [pid=27015], 328 s, 9 iter, 0.925 loss, 0.723 acc
TERMINATED trials:
 - TrainMNIST_0_lr=0.023931,momentum=0.79987:   TERMINATED [pid=4493], 39 s, 1 iter, 0.0872 loss, 0.971 acc
 - TrainMNIST_1_lr=0.031427,momentum=0.41335:   TERMINATED [pid=4423], 38 s, 1 iter, 0.121 loss, 0.965 acc
 - TrainMNIST_2_lr=0.063787,momentum=0.85323:   TERMINATED [pid=4502], 39 s, 1 iter, 0.156 loss, 0.956 acc
 - TrainMNIST_3_lr=0.05126,momentum=0.74525:    TERMINATED [pid=4421], 38 s, 1 iter, 0.0905 loss, 0.971 acc
 - TrainMNIST_4_lr=0.022249,momentum=0.45414:   TERMINATED [pid=4498], 38 s, 1 iter, 0.139 loss, 0.958 acc
 - TrainMNIST_5_lr=0.052895,momentum=0.413:     TERMINATED [pid=4422], 37 s, 1 iter, 0.0985 loss, 0.97 acc
 - TrainMNIST_6_lr=0.07729,momentum=0.45828:    TERMINATED [pid=4420], 38 s, 1 iter, 0.0863 loss, 0.974 acc
 - TrainMNIST_7_lr=0.065795,momentum=0.58677:   TERMINATED [pid=11554], 36 s, 1 iter, 0.0944 loss, 0.972 acc
 - TrainMNIST_8_lr=0.063318,momentum=0.8058:    TERMINATED [pid=4419], 36 s, 1 iter, 0.102 loss, 0.966 acc
 - TrainMNIST_9_lr=0.09026,momentum=0.28287:    TERMINATED [pid=4418], 38 s, 1 iter, 0.0914 loss, 0.972 acc
 - TrainMNIST_10_lr=0.054653,momentum=0.24095:  TERMINATED [pid=4416], 37 s, 1 iter, 0.105 loss, 0.969 acc
 - TrainMNIST_11_lr=0.022981,momentum=0.83481:  TERMINATED [pid=4417], 38 s, 1 iter, 0.0926 loss, 0.974 acc
 - TrainMNIST_12_lr=0.063872,momentum=0.46114:  TERMINATED [pid=11572], 37 s, 1 iter, 0.09 loss, 0.973 acc
 - TrainMNIST_13_lr=0.0065688,momentum=0.22885: TERMINATED [pid=26960], 144 s, 4 iter, 0.137 loss, 0.959 acc
 - TrainMNIST_14_lr=0.090342,momentum=0.61352:  TERMINATED [pid=26987], 36 s, 1 iter, 0.0926 loss, 0.972 acc
 - TrainMNIST_15_lr=0.0040368,momentum=0.64587: TERMINATED [pid=26988], 108 s, 3 iter, 0.14 loss, 0.957 acc
 - TrainMNIST_16_lr=0.084079,momentum=0.29146:  TERMINATED [pid=27013], 37 s, 1 iter, 0.0966 loss, 0.971 acc
 - TrainMNIST_18_lr=0.052405,momentum=0.65585:  TERMINATED [pid=26959], 36 s, 1 iter, 0.0846 loss, 0.974 acc
 - TrainMNIST_19_lr=0.0067516,momentum=0.68086: TERMINATED [pid=11555], 74 s, 2 iter, 0.129 loss, 0.96 acc

Traceback (most recent call last):
  File "/home/user/Documents/pytorch/src/torchRunRaw/test.py", line 203, in <module>
    scheduler=sched)
  File "/home/user/miniconda3/envs/pytorch/lib/python3.5/site-packages/ray/tune/tune.py", line 124, in run_experiments
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [TrainMNIST_17_lr=0.098507,momentum=0.88414])
```

**Comment by ericl** [comment]
This shouldn't be an issue after https://github.com/ray-project/ray/pull/3211 , which strictly enforces that the user return a file in the given checkpoint dir.
