### ISSUE TITLE
[rllib] rollout.py not finding params.json

### ISSUE THREAD

**Issue by rnunziata** [ray-project/ray#3206]
When doing a evaluation using rollout.py
Roll out expects to find the params.json file with the checkpoint-xxx.tune_metadata and checkpoiint-xxx.agent_state files. I had to move it there in order to get rollout to run.

Also:
requiring env and run parameters to parser are not needed sense they could be specified in the config file, this is how train.py works...yes?

**Comment by rnunziata** [comment]
I tried to install using new master but get the following errors on install:
```
Removed build tracker '/tmp/pip-req-tracker-or38a9'
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/home/rjn/projects/RL/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/rjn/projects/RL/ray/python/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/req/req_install.py", line 750, in install
    install_options, global_options, prefix=prefix,
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/req/req_install.py", line 628, in install_editable
    show_stdout=False,
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/home/rjn/projects/RL/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/rjn/projects/RL/ray/python/


rjn@rjn-Oryx-Pro:~/projects/RL/ray/python$ cd ..
rjn@rjn-Oryx-Pro:~/projects/RL/ray$ python python/ray/rllib/rollout.py --run IMPALA --steps 10000  /home/rjn/ray_results/pong-impala/IMPALA_Pong-ram-v4_0_2018-11-06_12-46-53qEzuKa/checkpoint_840Fl1Un4/checkpoint-840
Traceback (most recent call last):
  File "python/ray/rllib/rollout.py", line 13, in <module>
    import ray
ImportError: No module named ray
```

**Comment by rnunziata** [comment]
I am running test now....I noticed the directory structure has changed....I like it better then what it was. Will update here once I run with restore.

**Comment by rnunziata** [comment]
Tested....now finds params.json located with checkpoints
