### ISSUE TITLE
[Ray 2.3 release] `rllib_learning_tests_leela_chess_zero` fails with `AttributeError`

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32147]
* BuildKite: https://buildkite.com/ray-project/release-tests-branch/builds/1322#018604d8-3e68-41c7-8116-60745d3bc851
* Cluster: https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_rkgj4fx9ld92ptxdavu6njtcln?command-history-section=command_history&drivers-section=interactive-sessions

```
Traceback (most recent call last):
  File "learning_tests/run.py", line 57, in <module>
    framework=args.framework,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/test_utils.py", line 859, in run_learning_tests_from_yaml
    max_report_frequency=30,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 897, in run_experiments
    callbacks=callbacks,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 756, in run
    runner.step()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/execution/trial_runner.py", line 946, in step
    next_trial = self._update_trial_queue_and_get_next_trial()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/execution/trial_runner.py", line 882, in _update_trial_queue_and_get_next_trial
    if not self._update_trial_queue(blocking=wait_for_trial):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/execution/trial_runner.py", line 1468, in _update_trial_queue
    trial = self._search_alg.next_trial()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/search/basic_variant.py", line 376, in next_trial
    trial = next(self._trial_iter)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/search/basic_variant.py", line 182, in __next__
    return self.create_trial(resolved_vars, spec)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/search/basic_variant.py", line 133, in create_trial
    experiment_tag=experiment_tag,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/experiment/config_parser.py", line 249, in _create_trial_from_spec
    **trial_kwargs,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/experiment/trial.py", line 304, in __init__
    default_resources = trainable_cls.default_resource_request(self.config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py", line 2125, in default_resource_request
    cf = cls.get_default_config().update_from_dict(config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/algorithms/leela_chess_zero/leela_chess_zero.py", line 285, in update_from_dict
    return super().update_from_dict(config_dict)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm_config.py", line 577, in update_from_dict
    self.multi_agent(**kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm_config.py", line 1942, in multi_agent
    policy_mapping_fn = from_config(policy_mapping_fn)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/from_config.py", line 187, in from_config
    f"String specifier ({type_}) must be a valid filename, "
AttributeError: 'NoneType' object has no attribute '__module__'
```

**Comment by cadedaniel** [comment]
Looks like a real failure to me, cc @kouroshHakha and @avnishn for triaging
