### ISSUE TITLE
[Ray 2.3 Release] `air_benchmark_torch_mnist_gpu_4x4` fails on release branch

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32173]
* BuildKite: https://buildkite.com/ray-project/release-tests-branch/builds/1328#01860e31-1e39-42b7-8d26-561be566fd16

```
Traceback (most recent call last):
--
  | File "workloads/torch_benchmark.py", line 597, in <module>
  | main()
  | File "workloads/torch_benchmark.py", line 593, in main
  | return cli()
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
  | return self.main(*args, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1055, in main
  | rv = self.invoke(ctx)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
  | return _process_result(sub_ctx.command.invoke(sub_ctx))
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 760, in invoke
  | return __callback(*args, **kwargs)
  | File "workloads/torch_benchmark.py", line 422, in run
  | from benchmark_util import upload_file_to_all_nodes, run_command_on_all_nodes
  | File "/tmp/ray/session_2023-02-01_10-27-08_726053_254/runtime_resources/working_dir_files/_ray_pkg_8c8bdbade4a442f6/workloads/benchmark_util.py", line 7, in <module>
  | from python.ray.air.util.node import _force_on_node
  | ModuleNotFoundError: No module named 'python'
```

**Comment by Yard1** [comment]
Looks to be related to https://github.com/ray-project/ray/pull/32016, we may need to revert
