### ISSUE TITLE
[Datasets] `write_tfrecords` doesn't work with tensor type

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#32257]
### What happened + What you expected to happen

```
>>> import ray
>>> ray.data.range_tensor(1)
2023-02-06 17:39:00,236 INFO worker.py:1544 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
2023-02-06 17:39:02,992 WARNING read_api.py:330 -- ⚠️  The number of blocks in this dataset (1) limits its parallelism to 1 concurrent tasks. This is much less than the number of available CPU slots in the cluster. Use `.repartition(n)` to increase the number of dataset blocks.
Dataset(num_blocks=1, num_rows=1, schema={__value__: ArrowTensorType(shape=(1,), dtype=int64)})
>>> ray.data.range_tensor(1).write_tfrecords("spam")
2023-02-06 17:39:08,915 WARNING read_api.py:330 -- ⚠️  The number of blocks in this dataset (1) limits its parallelism to 1 concurrent tasks. This is much less than the number of available CPU slots in the cluster. Use `.repartition(n)` to increase the number of dataset blocks.
Read progress: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 901.81it/s]
Write Progress:   0%|                                                                                                  | 0/1 [00:00<?, ?it/s](write_block pid=75082) 2023-02-06 17:39:10,689 INFO worker.py:772 -- Task failed with retryable exception: TaskID(de861c4272e4201effffffffffffffffffffffff01000000).
(write_block pid=75082) Traceback (most recent call last):
(write_block pid=75082)   File "python/ray/_raylet.pyx", line 862, in ray._raylet.execute_task
(write_block pid=75082)     next_breakpoint = (
(write_block pid=75082)   File "python/ray/_raylet.pyx", line 866, in ray._raylet.execute_task
(write_block pid=75082)     # there were no more remote calls left in this
(write_block pid=75082)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/file_based_datasource.py", line 302, in write_block
(write_block pid=75082)     _write_block_to_file(
(write_block pid=75082)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/tfrecords_datasource.py", line 61, in _write_block
(write_block pid=75082)     for example in examples:
(write_block pid=75082)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/tfrecords_datasource.py", line 101, in _convert_arrow_table_to_examples
(write_block pid=75082)     features[name] = _value_to_feature(arrow_table[name][i].as_py())
(write_block pid=75082)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/tfrecords_datasource.py", line 146, in _value_to_feature
(write_block pid=75082)     raise ValueError(
(write_block pid=75082) ValueError: Value is of type <class 'numpy.ndarray'>, which is not a supported tf.train.Feature storage type (bytes, float, or int).
(write_block pid=75082) 2023-02-06 17:39:11,567 INFO worker.py:772 -- Task failed with retryable exception: TaskID(de861c4272e4201effffffffffffffffffffffff01000000).
(write_block pid=75082) Traceback (most recent call last):
(write_block pid=75082)   File "python/ray/_raylet.pyx", line 862, in ray._raylet.execute_task
(write_block pid=75082)     next_breakpoint = (
(write_block pid=75082)   File "python/ray/_raylet.pyx", line 866, in ray._raylet.execute_task
(write_block pid=75082)     # there were no more remote calls left in this
(write_block pid=75082)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/file_based_datasource.py", line 302, in write_block
(write_block pid=75082)     _write_block_to_file(
(write_block pid=75082)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/tfrecords_datasource.py", line 61, in _write_block
(write_block pid=75082)     for example in examples:
(write_block pid=75082)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/tfrecords_datasource.py", line 101, in _convert_arrow_table_to_examples
(write_block pid=75082)     features[name] = _value_to_feature(arrow_table[name][i].as_py())
(write_block pid=75082)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/tfrecords_datasource.py", line 146, in _value_to_feature
(write_block pid=75082)     raise ValueError(
(write_block pid=75082) ValueError: Value is of type <class 'numpy.ndarray'>, which is not a supported tf.train.Feature storage type (bytes, float, or int).
(write_block pid=75082) 2023-02-06 17:39:12,566 INFO worker.py:772 -- Task failed with retryable exception: TaskID(de861c4272e4201effffffffffffffffffffffff01000000).
(write_block pid=75082) Traceback (most recent call last):
(write_block pid=75082)   File "python/ray/_raylet.pyx", line 862, in ray._raylet.execute_task
(write_block pid=75082)     next_breakpoint = (
(write_block pid=75082)   File "python/ray/_raylet.pyx", line 866, in ray._raylet.execute_task
(write_block pid=75082)     # there were no more remote calls left in this
(write_block pid=75082)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/file_based_datasource.py", line 302, in write_block
(write_block pid=75082)     _write_block_to_file(
(write_block pid=75082)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/tfrecords_datasource.py", line 61, in _write_block
(write_block pid=75082)     for example in examples:
(write_block pid=75082)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/tfrecords_datasource.py", line 101, in _convert_arrow_table_to_examples
(write_block pid=75082)     features[name] = _value_to_feature(arrow_table[name][i].as_py())
(write_block pid=75082)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/tfrecords_datasource.py", line 146, in _value_to_feature
(write_block pid=75082)     raise ValueError(
(write_block pid=75082) ValueError: Value is of type <class 'numpy.ndarray'>, which is not a supported tf.train.Feature storage type (bytes, float, or int).
Write Progress: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.63s/it]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/dataset.py", line 2494, in write_tfrecords
    self.write_datasource(
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/dataset.py", line 2683, in write_datasource
    datasource.on_write_complete(ray.get(write_results))
  File "/Users/balaji/Documents/GitHub/ray/python/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/_private/worker.py", line 2380, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::write_block() (pid=75082, ip=127.0.0.1)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/file_based_datasource.py", line 302, in write_block
    _write_block_to_file(
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/tfrecords_datasource.py", line 61, in _write_block
    for example in examples:
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/tfrecords_datasource.py", line 101, in _convert_arrow_table_to_examples
    features[name] = _value_to_feature(arrow_table[name][i].as_py())
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/tfrecords_datasource.py", line 146, in _value_to_feature
    raise ValueError(
ValueError: Value is of type <class 'numpy.ndarray'>, which is not a supported tf.train.Feature storage type (bytes, float, or int).
>>> (write_block pid=75082) 2023-02-06 17:39:13,566     INFO worker.py:772 -- Task failed with retryable exception: TaskID(de861c4272e4201effffffffffffffffffffffff01000000).
(write_block pid=75082) Traceback (most recent call last):
(write_block pid=75082)   File "python/ray/_raylet.pyx", line 862, in ray._raylet.execute_task
(write_block pid=75082)     next_breakpoint = (
(write_block pid=75082)   File "python/ray/_raylet.pyx", line 866, in ray._raylet.execute_task
(write_block pid=75082)     # there were no more remote calls left in this
(write_block pid=75082)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/file_based_datasource.py", line 302, in write_block
(write_block pid=75082)     _write_block_to_file(
(write_block pid=75082)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/tfrecords_datasource.py", line 61, in _write_block
(write_block pid=75082)     for example in examples:
(write_block pid=75082)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/tfrecords_datasource.py", line 101, in _convert_arrow_table_to_examples
(write_block pid=75082)     features[name] = _value_to_feature(arrow_table[name][i].as_py())
(write_block pid=75082)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/tfrecords_datasource.py", line 146, in _value_to_feature
(write_block pid=75082)     raise ValueError(
(write_block pid=75082) ValueError: Value is of type <class 'numpy.ndarray'>, which is not a supported tf.train.Feature storage type (bytes, float, or int).
```

### Versions / Dependencies

Ray: 095960cf650bcbd672e72b6e8e383a1812ce0ab9

### Reproduction script

See above.

### Issue Severity

None

**Comment by bveeramani** [comment]
This is still an issue

**Comment by pythoncrazy** [comment]
can work around this via tf.io.serialize_tensor

**Comment by owenowenisme** [comment]
@kyuds Could you take a look at this?

**Comment by kyuds** [comment]
have a decent idea on how to tackle this. Will submit a PR soon
