### ISSUE TITLE
[Cluster]  Raylet crashes with multiple worker cluster and cloudwatch dashboard config.

### ISSUE THREAD

**Issue by gilvikra** [ray-project/ray#32264]
Hi Folks! I believe there is a bug  in the code which is hit while launching multiple workers with AWS cloudwatch dashboard. Removing the dashboard config from the cluster configuration prevents the crash. This piece of code =  "head_node_hash = self._get_head_node_config_hash(config_type)" in  file cloudwatch_helper.py will return head_node_hash as None for worker node and dashboard config type.  I have attached my cluster yaml for reproduction. Here is the log , with which the raylet dies on the worker node. :
```
Resources
---------------------------------------------------------------
Usage:
 0.0/64.0 CPU
 0.0/64.0 head_workers
 0.00/337.269 GiB memory
 0.00/148.535 GiB object_store_memory

Demands:
 (no resource demands)
2023-02-07 09:53:21,385	INFO autoscaler.py:453 -- The autoscaler took 0.062 seconds to complete the update iteration.
2023-02-07 09:53:25,822	INFO cloudwatch_helper.py:120 -- Cloudwatch dashboard config file has changed.

==> /tmp/ray/session_latest/logs/monitor.out <==
2023-02-07 09:53:25,822	INFO log_timer.py:30 -- NodeUpdater: i-02ff439b715d2e9fb: Applied config a2ab74e40c7cc1aa7d83c97eb24309db6bcabbb7  [LogTimer=269976ms]

==> /tmp/ray/session_latest/logs/monitor.log <==
2023-02-07 09:53:26,465	INFO autoscaler.py:142 -- The autoscaler took 0.057 seconds to fetch the list of non-terminated nodes.
2023-02-07 09:53:26,465	INFO autoscaler.py:409 -- 
======== Autoscaler status: 2023-02-07 09:53:26.465665 ========
Node status
---------------------------------------------------------------
Healthy:
 1 head
Pending:
 172.31.72.11: worker_cpu, waiting-for-ssh
Recent failures:
 worker_cpu: RayletUnexpectedlyDied (ip: 172.31.78.221)

Resources
---------------------------------------------------------------
Usage:
 0.0/64.0 CPU
 0.0/64.0 head_workers
 0.00/337.269 GiB memory
 0.00/148.535 GiB object_store_memory

Demands:
 (no resource demands)
2023-02-07 09:53:26,467	INFO autoscaler.py:453 -- The autoscaler took 0.058 seconds to complete the update iteration.

==> /tmp/ray/session_latest/logs/monitor.out <==
2023-02-07 09:53:26,924	INFO log_timer.py:30 -- AWSNodeProvider: Set tag ray-node-status=update-failed on ['i-02ff439b715d2e9fb']  [LogTimer=101ms]
2023-02-07 09:53:26,924	ERR updater.py:158 -- New status: update-failed
2023-02-07 09:53:26,924	ERR updater.py:160 -- !!!
2023-02-07 09:53:26,924	VERR updater.py:168 -- {'kwargs': {'report': "Invalid type for parameter Tags[0].Value, value: None, type: <class 'NoneType'>, valid types: <class 'str'>"}}
2023-02-07 09:53:26,924	ERR updater.py:170 -- Parameter validation failed:
Invalid type for parameter Tags[0].Value, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
2023-02-07 09:53:26,924	ERR updater.py:172 -- !!!

==> /tmp/ray/session_latest/logs/monitor.err <==
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 153, in run
    self.do_update()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 340, in do_update
    ).update_from_config(self.is_head_node)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ray/autoscaler/_private/aws/cloudwatch/cloudwatch_helper.py", line 71, in update_from_config
    self._update_cloudwatch_config(config_type.value, is_head_node)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ray/autoscaler/_private/aws/cloudwatch/cloudwatch_helper.py", line 130, in _update_cloudwatch_config
    self.node_id, head_node_hash, config_type
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ray/autoscaler/_private/aws/cloudwatch/cloudwatch_helper.py", line 440, in _update_cloudwatch_hash_tag_value
    Tags=[{"Key": hash_key_value, "Value": sha1_hash_value}],
  File "/home/ec2-user/.local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/botocore/client.py", line 924, in _make_api_call
    headers=additional_headers,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/botocore/client.py", line 991, in _convert_to_request_dict
    api_params, operation_model
  File "/home/ec2-user/.local/lib/python3.7/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Tags[0].Value, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```
[cluster.yaml.txt](https://github.com/ray-project/ray/files/10674242/cluster.yaml.txt)

### Versions / Dependencies

Ray 2.2, with cloudwatch integration

### Reproduction script

ray up -y cluster.yaml

follow the autoscaling logs:
ray exec /home/ec2-user/RAY_GIT/ClusterExp/clusterg.yaml 'tail -n 100 -f /tmp/ray/session_latest/logs/monitor*'

### Issue Severity

High: It blocks me from completing my task.

**Comment by wuisawesome** [comment]
@ray-project/amazon-ray ptal

**Comment by Zyiqin-Miranda** [comment]
Hi @gilvikra, as a quick fix, could you try delete the dashboard config file cached at your AWS Systems Manager > Parameter Store? Dashboard config should start with the name `AmazonCloudWatch-ray_dashboard_config_{your_cluster_name}`.
