### ISSUE TITLE
[RLlib] example/custom_env.py failing when replacing gymnasium with gym

### ISSUE THREAD

**Issue by akash-isu** [ray-project/ray#32268]
### What happened + What you expected to happen

Steps to reproduce:
1. replace "import gymnasium as gym" with "import gym"
2. replace "from gymnasium.spaces import Discrete, Box" with "from gym.spaces import Discrete, Box"
3. python3 rl_custom_env.py

I'm very new to RL with Ray. Don't know if I'm missing something. The traceback below is from MacOS 13.0.1. The same issue is reproducible on Ubuntu 20.04.4 LTS

Failure # 1 (occurred at 2023-02-07_11-08-01)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/tune/execution/ray_trial_executor.py", line 1070, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::PPO.__init__()[39m (pid=16322, ip=127.0.0.1, repr=PPO)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 239, in _setup
    self.add_workers(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 612, in add_workers
    raise result.get()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/rllib/utils/actor_manager.py", line 473, in __fetch_result
    result = ray.get(r)
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::RolloutWorker.__init__()[39m (pid=16329, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x16986ff70>)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/rllib/utils/pre_checks/env.py", line 174, in check_gym_environments
    if not env.observation_space.contains(reset_obs):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gym/spaces/box.py", line 156, in contains
    x = np.asarray(x, dtype=self.dtype)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

During handling of the above exception, another exception occurred:

[36mray::RolloutWorker.__init__()[39m (pid=16329, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x16986ff70>)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 592, in __init__
    check_env(self.env)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/rllib/utils/pre_checks/env.py", line 88, in check_env
    raise ValueError(
ValueError: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/rllib/utils/pre_checks/env.py", line 77, in check_env
    check_gym_environments(env)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/rllib/utils/pre_checks/env.py", line 174, in check_gym_environments
    if not env.observation_space.contains(reset_obs):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gym/spaces/box.py", line 156, in contains
    x = np.asarray(x, dtype=self.dtype)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

The above error has been found in your environment! We've added a module for checking your custom environments. It may cause your experiment to fail if your environment is not set up correctly. You can disable this behavior by setting `disable_env_checking=True` in your environment config dictionary. You can run the environment checking module standalone by calling ray.rllib.utils.check_env([env]).

During handling of the above exception, another exception occurred:

[36mray::PPO.__init__()[39m (pid=16322, ip=127.0.0.1, repr=PPO)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 441, in __init__
    super().__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 169, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 566, in setup
    self.workers = WorkerSet(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 191, in __init__
    raise e.args[0].args[2]
ValueError: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/rllib/utils/pre_checks/env.py", line 77, in check_env
    check_gym_environments(env)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/rllib/utils/pre_checks/env.py", line 174, in check_gym_environments
    if not env.observation_space.contains(reset_obs):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gym/spaces/box.py", line 156, in contains
    x = np.asarray(x, dtype=self.dtype)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

The above error has been found in your environment! We've added a module for checking your custom environments. It may cause your experiment to fail if your environment is not set up correctly. You can disable this behavior by setting `disable_env_checking=True` in your environment config dictionary. You can run the environment checking module standalone by calling ray.rllib.utils.check_env([env]).

### Versions / Dependencies

MacOS: 

python 3.10.0
gym 0.23.1
ray 2.2.0
torch 1.13.1
tensorflow 2.11.0

Ubuntu:

python 3.8.10
gym 0.23.1
ray 2.2.0
torch 1.13.0+cpu
tensorflow 2.11.0

### Reproduction script

python3 custom_env.py

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
Hi @akash-isu,

- We don't support gym directly anymore. Please use gymnasium whenever possible and use `from ray.rllib.utils.gym import convert_old_gym_space_to_gymnasium_space` to convert spaces.
- Could it be that the script you post is taken from the master branch and not from the branch of the release you are using? Please always use the script provided with their particular release.
- Like the error message states, you can disable this check with `disable_env_checking=True`

Please regard these three points on your way to a solution and let us know if they don't help.
