### ISSUE TITLE
[Datasets] The projection pushdown cannot work with hive style partitioning file path

### ISSUE THREAD

**Issue by jianoaix** [ray-project/ray#32301]
Version: Ray master

Projection pushdown cannot work with file path with hive style partitioning (e.g. "some/file/path/X=A/shard"). It will treat the "X" in the path as a field and expect the field to exist in the file.

```
import ray

ds = ray.data.read_parquet(
    ["s3://anonymous@air-example-data/ursa-labs-taxi-data/epoch=10001/downsampled_2009_01_data.parquet", "s3://anonymous@air-example-data/ursa-labs-taxi-data/epoch=10002/downsampled_2009_01_data.parquet"],
    columns=["vendor_id", "trip_distance"]
)

print(ds.take(10))
```
It failed with:

```
(_execute_read_task_split pid=1903508) Traceback (most recent call last):
(_execute_read_task_split pid=1903508)   File "python/ray/_raylet.pyx", line 641, in ray._raylet.execute_dynamic_generator_and_store_task_outputs
(_execute_read_task_split pid=1903508)     core_worker.store_task_outputs(
(_execute_read_task_split pid=1903508)   File "python/ray/_raylet.pyx", line 2498, in ray._raylet.CoreWorker.store_task_outputs
(_execute_read_task_split pid=1903508)     for i, output in enumerate(outputs):
(_execute_read_task_split pid=1903508)   File "/home/ubuntu/ray/python/ray/data/_internal/lazy_block_list.py", line 685, in _execute_read_task_split
(_execute_read_task_split pid=1903508)     for block in blocks:
(_execute_read_task_split pid=1903508)   File "/home/ubuntu/ray/python/ray/data/datasource/datasource.py", line 185, in __call__
(_execute_read_task_split pid=1903508)     for block in result:
(_execute_read_task_split pid=1903508)   File "/home/ubuntu/ray/python/ray/data/datasource/parquet_datasource.py", line 393, in _read_pieces
(_execute_read_task_split pid=1903508)     table = table.set_column(
(_execute_read_task_split pid=1903508)   File "pyarrow/table.pxi", line 4503, in pyarrow.lib.Table.set_column
(_execute_read_task_split pid=1903508)   File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
(_execute_read_task_split pid=1903508)   File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
(_execute_read_task_split pid=1903508) pyarrow.lib.ArrowInvalid: Invalid column index to set field.
(raylet) /usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!
(raylet)   warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
(_execute_read_task_split pid=1903508) 2023-02-08 00:57:28,778	INFO worker.py:772 -- Task failed with retryable exception: TaskID(32d950ec0ccf9d2affffffffffffffffffffffff01000000).
(_execute_read_task_split pid=1903508) Traceback (most recent call last):
(_execute_read_task_split pid=1903508)   File "python/ray/_raylet.pyx", line 641, in ray._raylet.execute_dynamic_generator_and_store_task_outputs
(_execute_read_task_split pid=1903508)     core_worker.store_task_outputs(
(_execute_read_task_split pid=1903508)   File "python/ray/_raylet.pyx", line 2498, in ray._raylet.CoreWorker.store_task_outputs
(_execute_read_task_split pid=1903508)     for i, output in enumerate(outputs):
(_execute_read_task_split pid=1903508)   File "/home/ubuntu/ray/python/ray/data/_internal/lazy_block_list.py", line 685, in _execute_read_task_split
(_execute_read_task_split pid=1903508)     for block in blocks:
(_execute_read_task_split pid=1903508)   File "/home/ubuntu/ray/python/ray/data/datasource/datasource.py", line 185, in __call__
(_execute_read_task_split pid=1903508)     for block in result:
(_execute_read_task_split pid=1903508)   File "/home/ubuntu/ray/python/ray/data/datasource/parquet_datasource.py", line 393, in _read_pieces
(_execute_read_task_split pid=1903508)     table = table.set_column(
(_execute_read_task_split pid=1903508)   File "pyarrow/table.pxi", line 4503, in pyarrow.lib.Table.set_column
(_execute_read_task_split pid=1903508)   File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
(_execute_read_task_split pid=1903508)   File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
(_execute_read_task_split pid=1903508) pyarrow.lib.ArrowInvalid: Invalid column index to set field.
(_execute_read_task_split pid=1903508) 2023-02-08 00:57:29,704	INFO worker.py:772 -- Task failed with retryable exception: TaskID(32d950ec0ccf9d2affffffffffffffffffffffff01000000).
```

**Comment by jianoaix** [comment]
As a workaround, user can add "epoch" into the column list to push down. The following will work:
```
import ray

ds = ray.data.read_parquet(
    ["s3://anonymous@air-example-data/ursa-labs-taxi-data/epoch=10001/downsampled_2009_01_data.parquet", "s3://anonymous@air-example-data/ursa-labs-taxi-data/epoch=10002/downsampled_2009_01_data.parquet"],
    columns=["vendor_id", "trip_distance", "epoch"]
)

print(ds.take(10))
```

**Comment by cszhu** [comment]
This P2 issue has seen no activity in the past 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please comment and remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
