### ISSUE TITLE
WandbLoggerCallback causing OSError

### ISSUE THREAD

**Issue by aga-relation** [ray-project/ray#32315]
Hi, when I add the `WandbLoggerCallback`, as shown in the example code provided [here](https://docs.ray.io/en/latest/ray-air/examples/upload_to_wandb.html), it causes an OSError at the end of training. Any ideas how to fix this?
Thanks!

`ray version: '2.2.0'`

### Error:
```
== Status ==
Current time: 2023-02-08 10:32:01 (running for 00:00:21.96)
Memory usage on this node: 101.0/2015.7 GiB 
Using FIFO scheduling algorithm.
Resources requested: 0/256 CPUs, 0/8 GPUs, 0.0/1726.37 GiB heap, 0.0/186.26 GiB objects (0.0/1.0 accelerator_type:A100)
Result logdir: /home/user/ray_results/XGBoostTrainer_2023-02-08_10-31-39
Number of trials: 1/1 (1 TERMINATED)
+----------------------------+------------+--------------------+--------+------------------+--------------+
| Trial name                 | status     | loc                |   iter |   total time (s) |   train-rmse |
|----------------------------+------------+--------------------+--------+------------------+--------------|
| XGBoostTrainer_aea05_00000 | TERMINATED | 10.21.8.18:1356771 |     11 |            8.044 |    0.0285877 |
+----------------------------+------------+--------------------+--------+------------------+--------------+


2023-02-08 10:32:01,918 INFO tune.py:762 -- Total run time: 22.07 seconds (21.96 seconds for the tuning loop).
Exception in thread MsgRouterThr:
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/ml-rosa/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/user/miniconda3/envs/ml-rosa/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/miniconda3/envs/ml-rosa/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/home/user/miniconda3/envs/ml-rosa/lib/python3.10/site-packages/wandb/sdk/interface/router_queue.py", line 36, in _read_message
    msg = self._response_queue.get(timeout=1)
  File "/home/user/miniconda3/envs/ml-rosa/lib/python3.10/multiprocessing/queues.py", line 117, in get
    res = self._recv_bytes()
  File "/home/user/miniconda3/envs/ml-rosa/lib/python3.10/multiprocessing/connection.py", line 212, in recv_bytes
    self._check_closed()
  File "/home/user/miniconda3/envs/ml-rosa/lib/python3.10/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
```
### To reproduce:
```
import ray

from ray.air.config import RunConfig, ScalingConfig
from ray.air.result import Result
from ray.air.integrations.wandb import WandbLoggerCallback
from ray.train.xgboost import XGBoostTrainer


def train_model_xgboost(train_dataset: ray.data.Dataset, wandb_project: str) -> Result:
    """Train a simple XGBoost model and return the result."""
    trainer = XGBoostTrainer(
        scaling_config=ScalingConfig(num_workers=2),
        params={"tree_method": "auto"},
        label_column="target",
        datasets={"train": train_dataset},
        num_boost_round=10,
        run_config=RunConfig(
            callbacks=[
                # This is the part needed to enable logging to Weights & Biases.
                # It assumes you've logged in before, e.g. with `wandb login`.
                WandbLoggerCallback(
                    project=wandb_project,
                    save_checkpoints=True,
                )
            ]
        ),
    )
    result = trainer.fit()
    return result

def get_train_dataset() -> ray.data.Dataset:
    dataset = ray.data.read_csv("s3://anonymous@air-example-data/breast_cancer.csv")
    return dataset


wandb_project = "xgboost_ray_test"

train_dataset = get_train_dataset()
result = train_model_xgboost(train_dataset=train_dataset, wandb_project=wandb_project)
```

**Comment by xwjiang2010** [comment]
Is it sporadic or always happening? 

I have never seen it myself. Do all results show up correctly in your w&b project in the end though? Feels like some internal racing condition during clean up in one of the threads used by w&b. I am not convinced that this is ray air related.

**Comment by aga-relation** [comment]
Hi! This happens every time at the end of the training, so the results show up fine, and it crashes at the very end. Could the version of wandb I have installed locally matter?

**Comment by xwjiang2010** [comment]
hmm, could you check with w&b team? I believe this is one of their internal threads.

**Comment by xwjiang2010** [comment]
Closing this out as it seems being fixed on wandb side.
