### ISSUE TITLE
[Train] HorovodTrainer utllity imports torch while user only want to use Tensorflow

### ISSUE THREAD

**Issue by woshiyyya** [ray-project/ray#32332]
### What happened + What you expected to happen

If a user only wants to use `HorovodTrainer` to train a tensorflow model. They should just need to install `ray`, `horovod`, and `tensorflow` in their conda environment. 

However, when we imported HorovodTrainer, it imported torch internally, which is not an expected behavior.

```python
from ray.train.horovod import HorovodTrainer

>>>
2023-02-08 13:54:17.162209: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "demo.py", line 14, in <module>
    from ray.train.horovod import HorovodTrainer
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/train/horovod/__init__.py", line 10, in <module>
    from ray.train.horovod.horovod_trainer import HorovodTrainer
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/train/horovod/horovod_trainer.py", line 9, in <module>
    from ray.train.horovod.config import HorovodConfig
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/train/horovod/config.py", line 8, in <module>
    from ray.air._internal.torch_utils import contains_tensor
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/air/_internal/torch_utils.py", line 5, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

### Versions / Dependencies

~~Ray master version~~
ray 2.1

### Reproduction script

```python
from ray.train.horovod import HorovodTrainer
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xwjiang2010** [comment]
The method is gated by `"torch" in sys.modules` though: https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/train/horovod/config.py?L157&subtree=true
Can you check if that's the case in your environment?

**Comment by woshiyyya** [comment]
@xwjiang2010 Oh I just realized that I was using Ray 2.1. It should have been fixed in the latest version.
