### ISSUE TITLE
[tune/air] "no space left on device" should be handled 

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#32481]
### What happened + What you expected to happen

showed up in one weekly test

https://buildkite.com/ray-project/release-tests-branch/builds/1396#0186443f-992d-4c16-a9d1-c0d02155442c

```
2023-02-12 20:31:03,681 ERROR trial_runner.py:1319 -- Trial TorchTrainer_e17ed_00000: Error handling checkpoint /home/ray/ray_results/TorchTrainer_2023-02-11_22-38-37/TorchTrainer_e17ed_00000_0_lr=0.0100_2023-02-11_22-42-29/checkpoint_000045
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/execution/trial_runner.py", line 1311, in _process_trial_save
    checkpoint=trial.saving_to,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/callback.py", line 368, in on_checkpoint
    callback.on_checkpoint(**info)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/syncer.py", line 832, in on_checkpoint
    trial, force=trial.sync_on_checkpoint, wait=True
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/syncer.py", line 775, in _sync_trial_dir
    sync_process.wait()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/syncer.py", line 245, in wait
    raise exception
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/syncer.py", line 208, in entrypoint
    result = self._fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/utils/file_transfer.py", line 78, in sync_dir_between_nodes
    return_futures=return_futures,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/utils/file_transfer.py", line 197, in _sync_dir_between_different_nodes
    return ray.get(unpack_future)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py", line 2380, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(OSError): ray::_unpack_from_actor() (pid=3058, ip=172.31.211.27)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/utils/file_transfer.py", line 446, in _unpack_from_actor
    _unpack_dir(stream, target_dir=target_dir)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/utils/file_transfer.py", line 421, in _unpack_dir
    tar.extractall(target_dir)
  File "/home/ray/anaconda3/lib/python3.7/tarfile.py", line 2002, in extractall
    numeric_owner=numeric_owner)
  File "/home/ray/anaconda3/lib/python3.7/tarfile.py", line 2044, in extract
    numeric_owner=numeric_owner)
  File "/home/ray/anaconda3/lib/python3.7/tarfile.py", line 2114, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/home/ray/anaconda3/lib/python3.7/tarfile.py", line 2163, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/home/ray/anaconda3/lib/python3.7/tarfile.py", line 250, in copyfileobj
    dst.write(buf)
OSError: [Errno 28] No space left on device
```

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

None

**Comment by xwjiang2010** [comment]
Another idea is to correlate the time with console logs.

**Comment by ankitshah009** [comment]
@xwjiang2010 is this problem resolved? facing the same issue with using cloud resources.
