### ISSUE TITLE
[Datasets] `PipelinedDatasetIterator.to_tf` doesn't work

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#32528]
### What happened + What you expected to happen

I tried to train a TensorFlow model with per-epoch preprocessing, but I got an error:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 787, in __next__
    return self._next_internal()
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 770, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3017, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7215, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.UnknownError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} RuntimeError: Pipeline cannot be read multiple times.
Traceback (most recent call last):

  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 271, in __call__
    ret = func(*args)

  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.10/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1039, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/dataset.py", line 3368, in generator
    for batch in self.iter_batches(

  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/dataset_pipeline.py", line 219, in iter_batches
    raise RuntimeError("Pipeline cannot be read multiple times.")

RuntimeError: Pipeline cannot be read multiple times.


         [[{{node PyFunc}}]] [Op:IteratorGetNext]
```

### Versions / Dependencies

Ray: 66c05338b07f1ef149928d4742b5f70c6c49b138
Python: 3.9

### Reproduction script

```
import ray
from ray.data._internal.pipelined_dataset_iterator import PipelinedDatasetIterator


dataset = ray.data.from_items([{"x": 0, "y": 0}])
pipeline = dataset.repeat()
iterator = PipelinedDatasetIterator(pipeline)

tf_dataset = iterator.to_tf("x", "y")
for epoch in range(2):
    for (inputs, targets) in tf_dataset:
        pass
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by amogkam** [comment]
Hey, so actually this usage is not expected to work. You want to call `to_tf` for each epoch right? If it's being called just once in the beginning, then it will iterate over the same epoch's worth of data again. So per-epoch processing won't be applied.
