### ISSUE TITLE
[gcs] Better error message when failing to connect to GCS external storage

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#32541]
Failing to connect to GCS external storage gives a very hard to understand error message.

```
(anyscale) eoakes@Edwards-MacBook-Pro-2 test_yamls % RAY_REDIS_ADDRESS=does_not_exist:6379 ray start --head
Usage stats collection is enabled. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.

Local node IP: 127.0.0.1
Traceback (most recent call last):
  File "/Users/eoakes/miniforge3/envs/anyscale/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/site-packages/ray/scripts/scripts.py", line 2386, in main
    return cli()
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/site-packages/ray/autoscaler/_private/cli_logger.py", line 852, in wrapper
    return f(*args, **kwargs)
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/site-packages/ray/scripts/scripts.py", line 729, in start
    node = ray._private.node.Node(
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/site-packages/ray/_private/node.py", line 269, in __init__
    self.start_head_processes()
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/site-packages/ray/_private/node.py", line 1059, in start_head_processes
    self._write_cluster_info_to_kv()
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/site-packages/ray/_private/node.py", line 1043, in _write_cluster_info_to_kv
    ray_usage_lib.put_cluster_metadata(self.get_gcs_client())
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/site-packages/ray/_private/usage/usage_lib.py", line 576, in put_cluster_metadata
    gcs_client.internal_kv_put(
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/site-packages/ray/_private/gcs_utils.py", line 179, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/site-packages/ray/_private/gcs_utils.py", line 298, in internal_kv_put
    reply = self._kv_stub.InternalKVPut(req, timeout=timeout)
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused"
        debug_error_string = "UNKNOWN:Failed to pick subchannel {created_time:"2023-02-14T12:29:09.945699-06:00", children:[UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused {grpc_status:14, created_time:"2023-02-14T12:29:09.945695-06:00"}]}"
>
```

Contents of `gcs_server.out`:
```
(anyscale) eoakes@Edwards-MacBook-Pro-2 test_yamls % cat /tmp/ray/session_latest/logs/gcs_server.out
[2023-02-14 12:29:04,956 I 6945 19577686] (gcs_server) io_service_pool.cc:35: IOServicePool is running with 1 io_service.
[2023-02-14 12:29:04,964 I 6945 19577686] (gcs_server) gcs_server.cc:475: Using external Redis for KV storage: does_not_exist:6379
[2023-02-14 12:29:04,964 I 6945 19577686] (gcs_server) gcs_server.cc:60: GCS storage type is redis
[2023-02-14 12:29:05,065 W 6945 19577686] (gcs_server) redis_context.cc:363:  Will retry in 100 milliseconds. Each retry takes about two minutes.
[2023-02-14 12:29:05,171 W 6945 19577686] (gcs_server) redis_context.cc:363:  Will retry in 100 milliseconds. Each retry takes about two minutes.
[2023-02-14 12:29:05,279 W 6945 19577686] (gcs_server) redis_context.cc:363:  Will retry in 100 milliseconds. Each retry takes about two minutes.
[2023-02-14 12:29:05,388 W 6945 19577686] (gcs_server) redis_context.cc:363:  Will retry in 100 milliseconds. Each retry takes about two minutes.
[2023-02-14 12:29:05,501 W 6945 19577686] (gcs_server) redis_context.cc:363:  Will retry in 100 milliseconds. Each retry takes about two minutes.
```

**Comment by kevin85421** [comment]
+1

I got the same error when using the wrong redis password (https://github.com/ray-project/kuberay/issues/927). Without help from @iycheng, it is hard to find the reason by myself. It would be great to have an easy-to-understand error message.

**Comment by edoakes** [comment]
@scv119 can we prioritize this for the 2.4 release?
