### ISSUE TITLE
[Serve] `serve run` fails unless `RAY_ENABLE_WINDOWS_OR_OSX_CLUSTER` is set

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#32612]
### What happened + What you expected to happen

Due to #32409, `serve run` fails on MacOS with a misleading error message when the user doesn't set the `RAY_ENABLE_WINDOWS_OR_OSX_CLUSTER` env var to `"true"`. I would expect `serve run` to work regardless of the user's environment variables.

Kudos to @zcin for discovering the connection between `serve run` failing and the change in #32409!

### Versions / Dependencies

MacOS version 11.4. M1 MacBook. Ray on the latest `master`.

### Reproduction script

```yaml
# config.yaml

import_path: fruit:deployment_graph

runtime_env:
    working_dir: "https://github.com/ray-project/serve_config_examples/archive/HEAD.zip"
```

```console
% serve run works.yaml
2023-02-15 17:38:03,060	INFO worker.py:1553 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265/ 
(raylet) [2023-02-15 17:38:08,090 I 81560 84254417] global_state_accessor.cc:356: This node has an IP address of 10.142.7.240, but we cannot find a local Raylet with the same address. This can happen when you connect to the Ray cluster with a different IP address or when connecting to a container.
Traceback (most recent call last):
  File "/Users/shrekris/miniforge3/envs/ae/bin/serve", line 33, in <module>
    sys.exit(load_entry_point('ray', 'console_scripts', 'serve')())
  File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/shrekris/Desktop/ray/python/ray/serve/scripts.py", line 315, in run
    submission_id = client.submit_job(
  File "/Users/shrekris/Desktop/ray/python/ray/dashboard/modules/job/sdk.py", line 226, in submit_job
    self._raise_error(r)
  File "/Users/shrekris/Desktop/ray/python/ray/dashboard/modules/dashboard_sdk.py", line 263, in _raise_error
    raise RuntimeError(
RuntimeError: Request failed with status code 500: Traceback (most recent call last):
  File "/Users/shrekris/Desktop/ray/python/ray/dashboard/modules/job/job_head.py", line 292, in submit_job
    resp = await job_agent_client.submit_job_internal(submit_request)
  File "/Users/shrekris/Desktop/ray/python/ray/dashboard/modules/job/job_head.py", line 74, in submit_job_internal
    async with self._session.post(
  File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
.
(raylet) [2023-02-15 17:38:17,124 E 81560 84255700] core_worker_process.cc:216: Failed to get the system config from raylet because it is dead. Worker will terminate. Status: GrpcUnavailable: RPC Error message: failed to connect to all addresses; RPC Error details:  .Please see `raylet.out` for more details.
(raylet) [2023-02-15 17:38:17,138 E 81557 84254416] (raylet) agent_manager.cc:135: The raylet exited immediately because the Ray agent failed. The raylet fate shares with the agent. This can happen because the Ray agent was unexpectedly killed or failed. Agent can fail when
(raylet) - The version of `grpcio` doesn't follow Ray's requirement. Agent can segfault with the incorrect `grpcio` version. Check the grpcio version `pip freeze | grep grpcio`.
(raylet) - The agent failed to start because of unexpected error or port conflict. Read the log `cat /tmp/ray/session_latest/dashboard_agent.log`. You can find the log file structure here https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure.
(raylet) - The agent is killed by the OS (e.g., out of memory).
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by shrekris-anyscale** [comment]
This has stopped happening on `master`, likely thanks to #32646. Users can run `serve run` successfully without setting the `RAY_ENABLE_WINDOWS_OR_OSX_CLUSTER`.
