### ISSUE TITLE
Adding tensorflow network to ARS model. Returning TypeError. #question

### ISSUE THREAD

**Issue by 170928** [ray-project/ray#3261]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**:  source
- **Ray version**: 0.5.3
- **Python version**: 3.5.2
- **Exact command to reproduce**: 

### Describe the problem

I would like to use ray in my code but i get a lot of warning and TypeError raised.
I can't find the appropriate answer in google.
Basically I'm using ARS using ray. I want to add another tensorflow network model ( called predictioner ) which is just normal structure of tensorflow network.
I just added the normal class and initialize it and call in the ARS Learner of default ARS code.

### Source code / logs

WARNING: Serializing objects of type <class 'predictioner.predictioner'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'tensorflow.python.framework.ops.Tensor'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'tensorflow.python.framework.ops.Operation'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f8b08207080>>
Traceback (most recent call last):
  File "/home/shin/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 704, in __del__
    if self._session is not None:
AttributeError: 'Session' object has no attribute '_session'
WARNING: Serializing objects of type <class 'tensorflow.python.client.session.Session'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'tensorflow.python.ops.variables.Variable'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'tensorflow.python.framework.dtypes.DType'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'tensorflow.python.framework.tensor_shape.TensorShape'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Pickling the class <class 'SwigPyObject'> failed, so we are using pickle and only registering the class locally.
Traceback (most recent call last):
  File "/home/shin/바탕화면/ARS/ARS-master/code/gail_ars.py", line 495, in <module>
    run_ars(params)
  File "/home/shin/바탕화면/ARS/ARS-master/code/gail_ars.py", line 456, in run_ars
    seed=params['seed'])
  File "/home/shin/바탕화면/ARS/ARS-master/code/gail_ars.py", line 217, in __init__
    delta_std=delta_std) for i in range(num_workers)]
  File "/home/shin/바탕화면/ARS/ARS-master/code/gail_ars.py", line 217, in <listcomp>
    delta_std=delta_std) for i in range(num_workers)]
  File "/home/shin/.local/lib/python3.5/site-packages/ray/actor.py", line 571, in remote
    return self._submit(args=args, kwargs=kwargs)
  File "/home/shin/.local/lib/python3.5/site-packages/ray/actor.py", line 646, in _submit
    actor_handle.__init__.remote(*args, **kwargs)
  File "/home/shin/.local/lib/python3.5/site-packages/ray/actor.py", line 469, in remote
    return self._submit(args, kwargs)
  File "/home/shin/.local/lib/python3.5/site-packages/ray/actor.py", line 480, in _submit
    dependency=self._actor._ray_actor_cursor)
  File "/home/shin/.local/lib/python3.5/site-packages/ray/actor.py", line 819, in _actor_method_call
    driver_id=self._ray_actor_driver_id)
  File "/home/shin/.local/lib/python3.5/site-packages/ray/worker.py", line 638, in submit_task
    args_for_local_scheduler.append(put(arg))
  File "/home/shin/.local/lib/python3.5/site-packages/ray/worker.py", line 2542, in put
    worker.put_object(object_id, value)
  File "/home/shin/.local/lib/python3.5/site-packages/ray/worker.py", line 406, in put_object
    self.store_and_register(object_id, value)
  File "/home/shin/.local/lib/python3.5/site-packages/ray/worker.py", line 341, in store_and_register
    self.task_driver_id))
  File "/home/shin/.local/lib/python3.5/site-packages/ray/utils.py", line 387, in _wrapper
    return orig_attr(*args, **kwargs)
  File "pyarrow/_plasma.pyx", line 435, in pyarrow._plasma.PlasmaClient.put
  File "pyarrow/serialization.pxi", line 337, in pyarrow.lib.serialize
  File "pyarrow/serialization.pxi", line 144, in pyarrow.lib.SerializationContext._serialize_callback
  File "/home/shin/.local/lib/python3.5/site-packages/ray/cloudpickle/cloudpickle.py", line 881, in dumps
    cp.dump(obj)
  File "/home/shin/.local/lib/python3.5/site-packages/ray/cloudpickle/cloudpickle.py", line 268, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/usr/lib/python3.5/pickle.py", line 495, in save
    rv = reduce(self.proto)
TypeError: can't pickle SwigPyObject objects

**Comment by ericl** [comment]
Usually this means you're referencing some un-picklable static object -- double check that your class definition isn't referencing some object instance. Instead you can usually create the object inside the remote class.

**Comment by richardliaw** [comment]
Closing this because it seems resolved.
