### ISSUE TITLE
Test failure in multi_node_test.py.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#327]
We very occasionally see the following test failure (e.g., https://s3.amazonaws.com/archive.travis-ci.org/jobs/205966635/log.txt).

```
$ python test/multi_node_test.py
testErrorIsolation (__main__.MultiNodeTest) ... /home/travis/.local/lib/python3.6/site-packages/ray-0.0.1-py3.6.egg/ray/worker.py:873: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('10.10.8.142', 56579), raddr=('10.10.8.142', 49606)>
  node_ip_address = services.get_node_ip_address(redis_address)
/home/travis/miniconda/lib/python3.6/site-packages/cloudpickle/cloudpickle.py:180: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/travis/miniconda/lib/python3.6/site-packages/cloudpickle/cloudpickle.py' mode='r' encoding='utf-8'>
  _find_module(mod_name)
/home/travis/miniconda/lib/python3.6/site-packages/cloudpickle/cloudpickle.py:180: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/travis/.local/lib/python3.6/site-packages/ray-0.0.1-py3.6.egg/ray/serialization.py' mode='r' encoding='utf-8'>
  _find_module(mod_name)
Waiting for error to appear.
Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads

Thread 0x00007fb24e294700 (most recent call first):
  File "/home/travis/miniconda/lib/python3.6/site-packages/colorama/ansitowin32.py", line 175 in write_plain_text
  File "/home/travis/miniconda/lib/python3.6/site-packages/colorama/ansitowin32.py", line 169 in write_and_convert
  File "/home/travis/miniconda/lib/python3.6/site-packages/colorama/ansitowin32.py", line 141 in write
  File "/home/travis/miniconda/lib/python3.6/site-packages/colorama/ansitowin32.py", line 40 in write
  File "/home/travis/.local/lib/python3.6/site-packages/ray-0.0.1-py3.6.egg/ray/worker.py", line 1026 in print_error_messages
  File "/home/travis/miniconda/lib/python3.6/threading.py", line 864 in run
  File "/home/travis/miniconda/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/travis/miniconda/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x00007fb2543f8740 (most recent call first):
polymer: no process found
ERROR
testRemoteFunctionIsolation (__main__.MultiNodeTest) ... /home/travis/.local/lib/python3.6/site-packages/ray-0.0.1-py3.6.egg/ray/worker.py:873: ResourceWarning: unclosed <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('10.10.8.142', 34630), raddr=('10.10.8.142', 53722)>
  node_ip_address = services.get_node_ip_address(redis_address)
polymer: no process found
FAIL
testCallingStartRayHead (__main__.StartRayScriptTest) ... polymer: no process found
polymer: no process found
polymer: no process found
polymer: no process found
polymer: no process found
polymer: no process found
polymer: no process found
polymer: no process found
Traceback (most recent call last):
  File "/home/travis/build/ray-project/ray/scripts/start_ray.py", line 47, in <module>
    raise Exception("If --head is passed in, a Redis server will be started, so a Redis address should not be provided.")
Exception: If --head is passed in, a Redis server will be started, so a Redis address should not be provided.
global_scheduler: no process found
plasma_store: no process found
plasma_manager: no process found
local_scheduler: no process found
polymer: no process found
ok

======================================================================
ERROR: testErrorIsolation (__main__.MultiNodeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/multi_node_test.py", line 94, in testErrorIsolation
    out = subprocess.check_output(["python", f.name]).decode("ascii")
  File "/home/travis/miniconda/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/travis/miniconda/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python', '/tmp/tmpcahrx8if']' died with <Signals.SIGABRT: 6>.
```

I can reproduce this error (on Ubuntu 16.04, with Anaconda, Python 3.5.2) by running the following (from `ray/`).

```
for i in {1..10000}; do python test/multi_node_test.py MultiNodeTest.testErrorIsolation; done
```

The problem may be related to our use of daemon threads (e.g., `t.daemon = True`) in `worker.py`.

**Comment by robertnishihara** [comment]
Haven't seen this recently.
