### ISSUE TITLE
ray error packaging zip file even with smart_open installed

### ISSUE THREAD

**Issue by slow-zhang** [ray-project/ray#32729]
### What happened + What you expected to happen

1. i have install the smart open but ray could not got the ray when i submit job in head node
2. expect: run the python code
3. logs here
```
root@raycluster-complete-head-vgbmc:/workspace# python -c "from smart_open import open as open_file"
root@raycluster-complete-head-vgbmc:/workspace# ray job submit --runtime-env-json='{"pip": ["smart_open==2.0.0"],"working_dir": "https://github.prod.hulu.com/Recommendation/auto-py
train/archive/refs/heads/test-pcs.zip"}'  python test2.py
Job submission server address: http://192.168.5.32:8265

-------------------------------------------------------
Job 'raysubmit_MEyFWJHUAx94UwRv' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_MEyFWJHUAx94UwRv
  Query the status of the job:
    ray job status raysubmit_MEyFWJHUAx94UwRv
  Request the job to be stopped:
    ray job stop raysubmit_MEyFWJHUAx94UwRv

Tailing logs until the job exits (disable with --no-wait):

---------------------------------------
Job 'raysubmit_MEyFWJHUAx94UwRv' failed
---------------------------------------

Status message: runtime_env setup failed: Failed to set up runtime environment.
Could not create the actor because its associated runtime env failed to be created.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/_private/runtime_env/packaging.py", line 706, in download_and_unpack_package
    from smart_open import open as open_file
ImportError: cannot import name 'open'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 342, in _create_runtime_env_with_retry
    runtime_env_setup_task, timeout=setup_timeout_seconds
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/dist-packages/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 297, in _setup_runtime_env
    runtime_env, plugin, uri_cache, context, per_job_logger
  File "/usr/local/lib/python3.6/dist-packages/ray/_private/runtime_env/plugin.py", line 252, in create_for_plugin_if_needed
    size_bytes = await plugin.create(uri, runtime_env, context, logger=logger)
  File "/usr/local/lib/python3.6/dist-packages/ray/_private/runtime_env/working_dir.py", line 156, in create
    uri, self._resources_dir, self._gcs_aio_client, logger=logger
  File "/usr/local/lib/python3.6/dist-packages/ray/_private/runtime_env/packaging.py", line 709, in download_and_unpack_package
    "You must `pip install smart_open` "
ImportError: You must `pip install smart_open` to fetch HTTPS URIs.
```

### Versions / Dependencies

Name: ray
Version: 2.1.0
Summary: Ray provides a simple, universal API for building distributed applications.
Home-page: https://github.com/ray-project/ray
Author: Ray Team
Author-email: ray-dev@googlegroups.com
License: Apache 2.0
Location: /usr/local/lib/python3.6/dist-packages
Requires: jsonschema, requests, filelock, virtualenv, pyyaml, numpy, frozenlist, dataclasses, msgpack, attrs, protobuf, grpcio, click, typing-extensions, aiosignal
Required-by: xgboost-ray
root@raycluster-complete-head-v

### Reproduction script

pip install smart_open==2.0.0
ray job submit --runtime-env-json='{"pip": ["smart_open==2.0.0"],"working_dir": "https://xxx/test-pcs.zip"}'  python test2.py

### Issue Severity

High: It blocks me from completing my task.

**Comment by rickyyx** [comment]
cc @architkulkarni

**Comment by architkulkarni** [comment]
Hi @slow-zhang, you would need to install `smart_open` on all the Ray nodes prior to starting Ray; in particular specifying it in the `runtime_env` won't work. In newer Ray versions we've updated the error message to be more clear here.

Can you try this and see if it works?
