### ISSUE TITLE
[Jobs] Specifying API server address without `http://` raises unhelpful error "Unable to connect to GCS at localhost:8265"

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#32736]
### What happened + What you expected to happen

`ray job submit --address localhost:8265 -- python -c "import ray; ray.init();"` fails with
`2023-02-22 10:28:37,509 WARNING utils.py:1445 -- Unable to connect to GCS at localhost:8265. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.` repeating until finally failing with
```
Traceback (most recent call last):
  File "/Users/archit/anaconda3/envs/ray-py38/bin/ray", line 33, in <module>
    sys.exit(load_entry_point('ray', 'console_scripts', 'ray')())
  File "/Users/archit/ray/python/ray/scripts/scripts.py", line 2472, in main
    return cli()
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/archit/ray/python/ray/autoscaler/_private/cli_logger.py", line 852, in wrapper
    return f(*args, **kwargs)
  File "/Users/archit/ray/python/ray/dashboard/modules/job/cli.py", line 204, in submit
    client = _get_sdk_client(address, create_cluster_if_needed=True)
  File "/Users/archit/ray/python/ray/dashboard/modules/job/cli.py", line 22, in _get_sdk_client
    client = JobSubmissionClient(address, create_cluster_if_needed)
  File "/Users/archit/ray/python/ray/dashboard/modules/job/sdk.py", line 96, in __init__
    api_server_url = get_address_for_submission_client(address)
  File "/Users/archit/ray/python/ray/dashboard/utils.py", line 653, in get_address_for_submission_client
    address = ray_address_to_api_server_url(address)
  File "/Users/archit/ray/python/ray/dashboard/utils.py", line 605, in ray_address_to_api_server_url
    api_server_url = ray._private.utils.internal_kv_get_with_retry(
  File "/Users/archit/ray/python/ray/_private/utils.py", line 1461, in internal_kv_get_with_retry
    raise ConnectionError(
ConnectionError: Could not read 'dashboard' from GCS. Did GCS start successfully?
```

The job succeeds if `http://localhost:8265` is used instead of `localhost:8265`.

The problem is Ray is trying to use the Ray API server address as the GCS address when `http://` is not given.

We should at the very least have a better error message here, and perhaps support both ways if it makes sense.

### Versions / Dependencies

Master, macOS, Python 3.8

### Reproduction script

Above

### Issue Severity

Low: It annoys or frustrates me.

**Comment by architkulkarni** [comment]
Multiple reports, bumping to P1
