### ISSUE TITLE
[Data] Possible race condition in Streaming executor

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#32766]
### What happened + What you expected to happen

Sometimes see this failure when running streaming batch inference on 10 TB dataset:

```
Traceback (most recent call last):
  File "batch_predict.py", line 50, in <module>
    for _ in ds.iter_batches(batch_size=None, batch_format="pyarrow"):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/dataset.py", line 2887, in iter_batches
    yield from batch_block_refs(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching.py", line 113, in batch_block_refs
    yield from batch_blocks(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching.py", line 172, in batch_blocks
    for formatted_batch in batch_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching.py", line 379, in _format_batches
    for block in block_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching.py", line 342, in _blocks_to_batches
    for block in block_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching.py", line 243, in _resolve_blocks
    for block_ref in block_ref_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching.py", line 276, in _prefetch_blocks
    for block_ref in block_ref_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/legacy_compat.py", line 61, in execute_to_legacy_block_iterator
    for bundle in bundle_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 91, in execute
    raise item
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 133, in run
    while self._scheduling_loop_step(self._topology) and not self._shutdown:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 185, in _scheduling_loop_step
    cur_usage = TopologyResourceUsage.of(topology)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor_state.py", line 56, in of
    for bundle in state.outqueue:
RuntimeError: deque mutated during iteration
```

cc @ericl 

### Versions / Dependencies

master

### Reproduction script

mlperf batch inference

### Issue Severity

None

**Comment by amogkam** [comment]
Closing as duplicate of #32765
