### ISSUE TITLE
[data] [streaming] deque mutated during iteration

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#32765]
```
Traceback (most recent call last):
  File "batch_predict.py", line 50, in <module>
    for _ in ds.iter_batches(batch_size=None, batch_format="pyarrow"):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/dataset.py", line 2887, in iter_batches
    yield from batch_block_refs(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching.py", line 113, in batch_block_refs
    yield from batch_blocks(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching.py", line 172, in batch_blocks
    for formatted_batch in batch_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching.py", line 379, in _format_batches
    for block in block_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching.py", line 342, in _blocks_to_batches
    for block in block_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching.py", line 243, in _resolve_blocks
    for block_ref in block_ref_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching.py", line 276, in _prefetch_blocks
    for block_ref in block_ref_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/legacy_compat.py", line 61, in execute_to_legacy_block_iterator
    for bundle in bundle_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 91, in execute
    raise item
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 133, in run
    while self._scheduling_loop_step(self._topology) and not self._shutdown:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 185, in _scheduling_loop_step
    cur_usage = TopologyResourceUsage.of(topology)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor_state.py", line 56, in of
    for bundle in state.outqueue:
RuntimeError: deque mutated during iteration
```
FYI @amogkam

**Comment by amogkam** [comment]
Reproduction: 100 m5.12xlarge instance, each instance has 4 GPUs manually set

```python
import ray
from torchvision.models import resnet50, ResNet50_Weights
import torch
import time
import os
import numpy as np
from torchvision import transforms

from ray.data import ActorPoolStrategy

BATCH_SIZE = 1000

os.environ["RAY_DATASET_NEW_EXECUTION_BACKEND"] = "1"
os.environ["RAY_DATASET_USE_STREAMING_EXECUTOR"] = "1"
ctx = ray.data.context.DatasetContext.get_current()
ray.data.context.DatasetContext.get_current().use_streaming_executor = True

ds = ray.data.read_parquet("s3://air-example-data-2/10T-image-data-synthetic-raw-parquet/")

def preprocess(image_batch):
    preprocess = transforms.Compose(
        [
            transforms.Resize(256),
            transforms.CenterCrop(224),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        ]
    )
    torch_tensor = torch.Tensor(image_batch["image"].transpose(0, 3, 1, 2))
    preprocessed_images = preprocess(torch_tensor).numpy()
    return {"image": preprocessed_images}

model = resnet50(weights=ResNet50_Weights.DEFAULT)
model_ref = ray.put(model)

class Actor:
    def __init__(self, model):
        self.model = ray.get(model)
        self.model.eval()

    def __call__(self, batch):
        time.sleep(1)
        return np.ones(10)

start_time = time.time()
ds = ds.map_batches(preprocess, batch_format="numpy")
ds = ds.map_batches(Actor, batch_size=BATCH_SIZE, compute=ActorPoolStrategy(min_size=400, max_size=400, max_tasks_in_flight_per_actor=4), num_gpus=1, batch_format="numpy", fn_constructor_kwargs={"model": model_ref})
for _ in ds.iter_batches(batch_size=None, batch_format="pyarrow"):
    pass
end_time = time.time()

print("Total time: ", end_time-start_time)
print("Throughput (img/sec): ", (16232*1000)/(end_time-start_time))
```
