### ISSUE TITLE
[docker] ray-ml:2.3. uses a very old version of mlflow=1.21

### ISSUE THREAD

**Issue by sfc-gh-pjoziak** [ray-project/ray#32775]
### What happened + What you expected to happen

1) ray-ml:2.3.0rc1 uses a very old version of `mlflow=1.21` (from >1.5 year ago), that relies on `numpy.object` that has been deprecated in `numpy=1.20` (2 years ago). This causes issues when executing code via `ray job submit`. 
As a consequence, one sees a stacktrace as follows:

```
/home/ray/anaconda3/lib/python3.10/site-packages/mlflow/types/schema.py:49: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  binary = (7, np.dtype("bytes"), "BinaryType", np.object)
Traceback (most recent call last):
  File "/tmp/ray/session_2023-02-23_05-25-40_969440_8/runtime_resources/working_dir_files/_ray_pkg_d5c50b971787ff92/demo_10.py", line 6, in <module>
    import pytorch_lightning as pl
  File "/home/ray/anaconda3/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 30, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/ray/anaconda3/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/home/ray/anaconda3/lib/python3.10/site-packages/pytorch_lightning/callbacks/pruning.py", line 31, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/home/ray/anaconda3/lib/python3.10/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/home/ray/anaconda3/lib/python3.10/site-packages/pytorch_lightning/core/lightning.py", line 41, in <module>
    from pytorch_lightning.loggers import LightningLoggerBase, LoggerCollection
  File "/home/ray/anaconda3/lib/python3.10/site-packages/pytorch_lightning/loggers/__init__.py", line 23, in <module>
    from pytorch_lightning.loggers.mlflow import _MLFLOW_AVAILABLE, MLFlowLogger  # noqa: F401
  File "/home/ray/anaconda3/lib/python3.10/site-packages/pytorch_lightning/loggers/mlflow.py", line 32, in <module>
    _MLFLOW_AVAILABLE = _module_available("mlflow")
  File "/home/ray/anaconda3/lib/python3.10/site-packages/pytorch_lightning/utilities/imports.py", line 56, in _module_available
    importlib.import_module(module_path)
  File "/home/ray/anaconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/mlflow/__init__.py", line 50, in <module>
    import mlflow.catboost as catboost  # noqa: E402
  File "/home/ray/anaconda3/lib/python3.10/site-packages/mlflow/catboost.py", line 24, in <module>
    from mlflow import pyfunc
  File "/home/ray/anaconda3/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py", line 219, in <module>
    import mlflow.pyfunc.model
  File "/home/ray/anaconda3/lib/python3.10/site-packages/mlflow/pyfunc/model.py", line 17, in <module>
    from mlflow.models import Model
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/ray/anaconda3/lib/python3.10/site-packages/comet_ml/monkey_patching.py", line 83, in exec_module
    self.loader.exec_module(module)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/mlflow/models/__init__.py", line 26, in <module>
    from .signature import ModelSignature, infer_signature
  File "/home/ray/anaconda3/lib/python3.10/site-packages/mlflow/models/signature.py", line 12, in <module>
    from mlflow.types.schema import Schema
  File "/home/ray/anaconda3/lib/python3.10/site-packages/mlflow/types/__init__.py", line 6, in <module>
    from .schema import DataType, ColSpec, Schema, TensorSpec
  File "/home/ray/anaconda3/lib/python3.10/site-packages/mlflow/types/schema.py", line 20, in <module>
    class DataType(Enum):
  File "/home/ray/anaconda3/lib/python3.10/site-packages/mlflow/types/schema.py", line 49, in DataType
    binary = (7, np.dtype("bytes"), "BinaryType", np.object)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'object_'?
```

workaround:
```
ray job submit -- pip install mlflow==2.1
```

2. There is some package (have not tracked it yet) that has been compiled with a very old `protoc` version, causing the widely-known issue:

```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

workaround: 
```
ray job submit --runtime-env-json '{"PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION": "python"}' -- ...
```

### Versions / Dependencies

ray-ml:2.3.0rc1

### Reproduction script

(assumes raycluster connection already established)
git clone https://github.com/ray-project/ray_lightning.git
ray job submit -- python ray_lightning/examples/ray_ddp_example.py [params]

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by robnsngh** [comment]
I am running into the same issue but the proposed workaround isn't working

**Comment by richardliaw** [comment]
Would it be ok if we just removed mlflow from ray-ml docker image?

**Comment by justinvyu** [comment]
This has been fixed in master: https://github.com/ray-project/ray/pull/32620

Does running with the latest ray nightly work for you? @robnsngh

**Comment by robnsngh** [comment]
@justinvyu yes, nightly built worked. thanks for the fix

**Comment by justinvyu** [comment]
Reopening, since issue 2 in the OP is still unresolved.

**Comment by justinvyu** [comment]
@sfc-gh-pjoziak The second issue can be worked around for now with `pip install -U ray_lightning` (which will downgrade protobuf).

**Comment by justinvyu** [comment]
The protobuf issue (issue 2) should be fixed in future docker releases (see linked PR above).
