### ISSUE TITLE
I believe missing .yaml file in latest wheel

### ISSUE THREAD

**Issue by waldroje** [ray-project/ray#3283]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

Linux version 3.10.0-957.el7.x86_64 (mockbuild@x86-040.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Oct 4 20:48:51 UTC 2018

pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.5.3-cp36-cp36m-manylinux1_x86_64.whl

### Describe the problem

There seems to be a missing example-full.yaml file in the latest wheel for provider type "local". 

### Source code / logs

(algo_new) ➜  clusters ray up local.yaml
Traceback (most recent call last):
  File "/home/svc-tai-dev/miniconda3/envs/algo_new/bin/ray", line 11, in <module>
    sys.exit(main())
  File "/home/svc-tai-dev/miniconda3/envs/algo_new/lib/python3.5/site-packages/ray/scripts/scripts.py", line 635, in main
    return cli()
  File "/home/svc-tai-dev/miniconda3/envs/algo_new/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/svc-tai-dev/miniconda3/envs/algo_new/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/svc-tai-dev/miniconda3/envs/algo_new/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/svc-tai-dev/miniconda3/envs/algo_new/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/svc-tai-dev/miniconda3/envs/algo_new/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/svc-tai-dev/miniconda3/envs/algo_new/lib/python3.5/site-packages/ray/scripts/scripts.py", line 469, in create_or_update
    no_restart, restart_only, yes, cluster_name)
  File "/home/svc-tai-dev/miniconda3/envs/algo_new/lib/python3.5/site-packages/ray/autoscaler/commands.py", line 42, in create_or_update_cluster
    config = _bootstrap_config(config)
  File "/home/svc-tai-dev/miniconda3/envs/algo_new/lib/python3.5/site-packages/ray/autoscaler/commands.py", line 48, in _bootstrap_config
    config = fillout_defaults(config)
  File "/home/svc-tai-dev/miniconda3/envs/algo_new/lib/python3.5/site-packages/ray/autoscaler/autoscaler.py", line 637, in fillout_defaults
    defaults = get_default_config(config["provider"])
  File "/home/svc-tai-dev/miniconda3/envs/algo_new/lib/python3.5/site-packages/ray/autoscaler/node_provider.py", line 111, in get_default_config
    with open(path_to_default) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/svc-tai-dev/miniconda3/envs/algo_new/lib/python3.5/site-packages/ray/autoscaler/local/example-full.yaml'

**Comment by robertnishihara** [comment]
If we want to ship these files with the wheels then they may need to be included in https://github.com/ray-project/ray/blob/22113be04cc735da61897a24f5916c3f4d681f68/python/setup.py#L22 and https://github.com/ray-project/ray/blob/22113be04cc735da61897a24f5916c3f4d681f68/CMakeLists.txt#L101.
