### ISSUE TITLE
[core][state] Better error message for incorrect node id/ip with ray logs 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#32879]
### What happened + What you expected to happen

If node id or node ip results in a node not found, currently the state api returns 

```

Traceback (most recent call last):
  File "/data/home/rickyx/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/data/home/rickyx/anaconda3/lib/python3.9/site-packages/ray/scripts/scripts.py", line 2422, in main
    return cli()
  File "/data/home/rickyx/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/data/home/rickyx/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/data/home/rickyx/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/home/rickyx/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/home/rickyx/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/home/rickyx/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/data/home/rickyx/anaconda3/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data/home/rickyx/anaconda3/lib/python3.9/site-packages/ray/experimental/state/state_cli.py", line 930, in log_cluster
    logs = list_logs(
  File "/data/home/rickyx/anaconda3/lib/python3.9/site-packages/ray/experimental/state/api.py", line 1260, in list_logs
    r.raise_for_status()
  File "/data/home/rickyx/anaconda3/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8265/api/v0/logs?node_id=c40ab736a3fcc50ca5e51f6671b3fe8e43030cab0ebe378ab0da165&glob=%2A&timeout=30

```
We should check the validity of the params as early as possible, and hopefully return more specific error info. 

### Versions / Dependencies

master

### Reproduction script

```
pip install ray[default]
ray start --head
ray logs cluster --node-id XXXX 
```

### Issue Severity

None

**Comment by DACUS1995** [comment]
Hi, @rickyyx  is this issue still available, I'd like to take a shot at it.

**Comment by rickyyx** [comment]
Yes, feel free. So I think one potential solution of what we could do is:

- Add a `reason` field to the aiohttp.web.json_response here: https://github.com/ray-project/ray/blob/pr-actor-creation-fail/python/ray/dashboard/optional_utils.py#L163-L172
  - This way, we will be able to overwrite the default `Internal Server Error messages` 

This should be a rather simple change, but we might have downstream code that depends on this default "internal Server Errror" - I am not 100% yet, but we could run all the tests to see if anything bad happens.

**Comment by DACUS1995** [comment]
@rickyyx, is this close to what you had in mind? https://github.com/ray-project/ray/pull/33141
