### ISSUE TITLE
[serve] `serve run` command within job entrypoint fails if a `working_dir` is specified

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#32881]
Repro:
```
(anyscale) eoakes@Edwards-MacBook-Pro-2 tmp % ray --version
ray, version 2.3.0
(anyscale) eoakes@Edwards-MacBook-Pro-2 tmp % ray start --head
Usage stats collection is enabled. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.

Local node IP: 127.0.0.1

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='127.0.0.1:6379'
  This Ray runtime only accepts connections from local host.
  To accept connections from remote hosts, specify a public ip when starting
  the head node: ray start --head --node-ip-address=<public-ip>.

  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto')

  To see the status of the cluster, use
    ray status
  To monitor and debug Ray, view the dashboard at
    127.0.0.1:8265

  If connection fails, check your firewall settings and network configuration.

  To terminate the Ray runtime, run
    ray stop
(anyscale) eoakes@Edwards-MacBook-Pro-2 tmp % ray job submit --working-dir=https://github.com/anyscale/docs_examples/archive/refs/heads/main.zip -- serve run --non-blocking serve_hello:entrypoint
Job submission server address: http://127.0.0.1:8265

-------------------------------------------------------
Job 'raysubmit_CHgG77Qpg2fF7vum' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_CHgG77Qpg2fF7vum
  Query the status of the job:
    ray job status raysubmit_CHgG77Qpg2fF7vum
  Request the job to be stopped:
    ray job stop raysubmit_CHgG77Qpg2fF7vum

Tailing logs until the job exits (disable with --no-wait):
2023-02-27 17:56:15,704	INFO <string>:62 -- Deploying from import path: serve_hello:entrypoint.
Traceback (most recent call last):
  File "<string>", line 124, in <module>
  File "<string>", line 63, in main
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/site-packages/ray/_private/utils.py", line 1245, in import_attr
    module = importlib.import_module(module_name)
  File "/Users/eoakes/miniforge3/envs/anyscale/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'serve_hello'

------------------------------------------
Job 'raysubmit_CHgG77Qpg2fF7vum' succeeded
------------------------------------------
```

Using `python serve_hello.py` as the entrypoint instead works because this path goes over Ray client. This is likely caused by @zcin's recent change because we are no longer picking up the runtime_env of the job for the `serve run` command.

**Comment by edoakes** [comment]
Note that there is a second oddity here: the job is being marked as `SUCCEEDED` so `serve run` is exiting with a nonzero exit code.

**Comment by zcin** [comment]
The root cause of this issue is because we changed the local behavior of `serve run`:
- Previously, if connecting to a local cluster, serve run will directly call ray.init() and serve.run()
- With the above-mentioned change, even when connecting to a local cluster, serve run would submit a Ray Job to the local cluster and then call ray.init() and serve.run() inside that job. This means if a user ran serve run inside a Job (or any other process with a runtime environment), they should expect to have access to the dependencies installed in that runtime environment. However since serve run goes through another layer of Job submission, they don't.

We should revert this change to the local behavior of `serve run`.
