### ISSUE TITLE
[Data] FileNotFoundError

### ISSUE THREAD

**Issue by zhimin-z** [ray-project/ray#32901]
### Description

I am learning ray from https://docs.ray.io/en/latest/ray-overview/getting-started.html and found there is a file missing error from the tutorial:
If you tried the snippet using the latest `Ray==2.3.0`:
```
# Create from CSV.
# Tip: "example://" is a convenient protocol to access the
# python/ray/data/examples/data directory.
ds = ray.data.read_csv("example://iris.csv")
# Dataset(num_blocks=1, num_rows=150,
#         schema={sepal.length: float64, sepal.width: float64,
#                 petal.length: float64, petal.width: float64, variety: object})

# Create from Parquet.
ds = ray.data.read_parquet("example://iris.parquet")
# Dataset(num_blocks=1, num_rows=150,
#         schema={sepal.length: float64, sepal.width: float64,
#                 petal.length: float64, petal.width: float64, variety: object})
```
You will get the following error:
```
RayTaskError(FileNotFoundError)           Traceback (most recent call last)
Cell In[4], line 4
      1 # Create from CSV.
      2 # Tip: "example://" is a convenient protocol to access the
      3 # python/ray/data/examples/data directory.
----> 4 ds = ray.data.read_csv("example://iris.csv")
      5 # Dataset(num_blocks=1, num_rows=150,
      6 #         schema={sepal.length: float64, sepal.width: float64,
      7 #                 petal.length: float64, petal.width: float64, variety: object})
      8 
      9 # Create from Parquet.
     10 ds = ray.data.read_parquet("example://iris.parquet")

File /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/ray/data/read_api.py:867, in read_csv(paths, filesystem, parallelism, ray_remote_args, arrow_open_stream_args, meta_provider, partition_filter, partitioning, **arrow_csv_args)
    780 @PublicAPI
    781 def read_csv(
    782     paths: Union[str, List[str]],
   (...)
    791     **arrow_csv_args,
    792 ) -> Dataset[ArrowRow]:
    793     r"""Create an Arrow dataset from csv files.
    794 
    795     Examples:
   (...)
...
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/ray/data/datasource/file_based_datasource.py", line 379, in __init__
    self._paths, self._file_sizes = meta_provider.expand_paths(
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/ray/data/datasource/file_meta_provider.py", line 183, in expand_paths
    raise FileNotFoundError(path)
FileNotFoundError: /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/ray/data/examples/data/iris.csv
```

**Comment by amogkam** [comment]
Thanks for catching this @zhimin-z!

We will fix the example, but in the meantime, you can read the file directly from S3: 
`ds = ray.data.read_csv("s3://anonymous@air-example-data/iris.csv") `

**Comment by drcege** [comment]
The issue has reoccurred. It seems the document has been reset to `example://` again.

**Comment by drcege** [comment]
Moreover, the examples in the document do not seem to match the actual outcome. 

When I run the example from https://docs.ray.io/en/releases-2.10.0/data/performance-tips.html:
```python
import ray
# Pretend there are two CPUs.
ray.init(num_cpus=2)

# Repeat the iris.csv file 16 times.
ds = ray.data.read_csv(["example://iris.csv"] * 16)
print(ds.materialize())
```
The printed result is 1 block:
```python
MaterializedDataset(
   num_blocks=1,
   num_rows=2400,
   schema={
      sepal length (cm): double,
      sepal width (cm): double,
      petal length (cm): double,
      petal width (cm): double,
      target: int64
   }
)
```
instead of the 4 blocks shown in the document:
```
MaterializedDataset(
   num_blocks=4,
   num_rows=2400,
   ...
)
```
