### ISSUE TITLE
[Core] `get_runtime_context()` in task fails with unhelpful error  "cannot pickle '_thread.lock' object"

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#32987]
### What happened + What you expected to happen

```ray start --head```

```python
import ray
from ray.runtime_context import get_runtime_context

ray.init(address="auto")

@ray.remote
def g():
    return get_runtime_context()

print(ray.get(g.remote()))
```

This yields 
```python-traceback
Traceback (most recent call last):
  File "repro.py", line 10, in <module>
    print(ray.get(g.remote()))
  File "/Users/archit/ray/python/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/archit/ray/python/ray/_private/worker.py", line 2384, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::g() (pid=56435, ip=127.0.0.1)
  File "/Users/archit/ray/python/ray/cloudpickle/cloudpickle_fast.py", line 88, in dumps
    cp.dump(obj)
  File "/Users/archit/ray/python/ray/cloudpickle/cloudpickle_fast.py", line 733, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_thread.lock' object
```

If you replace `get_runtime_context()` with `get_runtime_context().get()`, then it works.  It prints some messages about this being a deprecated API, but hopefully this issue is still helpful if someone else runs into this.  The docs don't mention anything about the deprecation, at least on this page: https://docs.ray.io/en/latest/ray-core/api/core.html#runtime-context

### Versions / Dependencies

Master, MacOS

### Reproduction script

Above

### Issue Severity

Low: It annoys or frustrates me.

**Comment by jovany-wang** [comment]
So what we need to do is just fixing the doc?

**Comment by architkulkarni** [comment]
I guess there's two related issues:
1. For `get_runtime_context()`, better error message (and mention deprecation in the docs, or remove from docs if you're not supposed to use it)
2. For `get_runtime_context().get()`, mention deprecation in the docs

**Comment by architkulkarni** [comment]
Guessing at the priority here, might be P3.

**Comment by jovany-wang** [comment]
Hi @architkulkarni , I did an overall investigation on this issue.


> For get_runtime_context().get(), mention deprecation in the docs

For this, we should just fix it to avoid complaining about any deprecations.

**Comment by jovany-wang** [comment]
> For get_runtime_context(), better error message (and mention deprecation in the docs, or remove from docs if you're not supposed to use it)

`get_runtime_context()` works well. But users are not allowed to serialize `runtime_context` object.

**Comment by jovany-wang** [comment]
The following up stuff that we could do is to make runtime_context serializable.

**Comment by anydayeol** [comment]
`ray/util/tracing/tracing_helper.py` seems to be using the function:

https://github.com/ray-project/ray/blob/63ab82b4484997f334404e672c517a1d25638551/python/ray/util/tracing/tracing_helper.py#L193

**Comment by peterghaddad** [comment]
May be unrelated, but also seeing some cloud pickle errors with RayDP: https://github.com/oap-project/raydp/issues/316

**Comment by anydayeol** [comment]
I think this issue was accidentally closed because my commit that was merged included "Fixes #32987", should we reopen this? @pcmoritz

**Comment by architkulkarni** [comment]
Thanks @anydayeol, I tested the reproduction and this bug is still present. Reopening

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
