### ISSUE TITLE
[Rllib] Decision Transformer broken during loss calculation

### ISSUE THREAD

**Issue by Phirefly9** [ray-project/ray#32985]
### What happened + What you expected to happen

Decision Transformer does not work in ray 2.3, I'm not 100% sure if DT is supported yet as it is not in the docs but just in case

```
tracebackTraceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/ray/rllib/policy/torch_policy_v2.py", line 1174, in _worker
    self.loss(model, self.dist_class, sample_batch)
  File "/opt/conda/lib/python3.10/site-packages/ray/rllib/algorithms/dt/dt_torch_policy.py", line 485, in loss
    preds = self.model.get_prediction(model_out, train_batch)
  File "/opt/conda/lib/python3.10/site-packages/ray/rllib/algorithms/dt/dt_torch_model.py", line 176, in get_prediction
    obs_embeds = obs_embeds + timestep_embeds
RuntimeError: The size of tensor a (3) must match the size of tensor b (200) at non-singleton dimension 1
```

### Versions / Dependencies

```
ray==2.3.0
ray-cpp==2.3.0
Gymnasium==0.26.3
gym==0.23.0
torch==1.13.1
numpy==1.23.5
```

### Reproduction script

I was able to modify https://github.com/ray-project/ray/blob/ray-2.3.0/rllib/tuned_examples/dt/cartpole-v1-dt.yaml and reproduce by deleting the 
```
input: 'dataset'
input_config:         
        paths: 'tests/data/cartpole/large.json'
        format: 'json'
```
section and then running from `rllib train file <X>.yml`

or

```python
import gymnasium as gym
from ray import tune

rllib_config = {
    "horizon": 800,
    "target_return": 1.5,
    "batch_mode": 'complete_episodes',

    # === Resources ===
    "num_workers": 6,
    "num_cpus_per_worker": 1,
    'num_gpus_per_worker': 0,
    'num_envs_per_worker': 1,

    'custom_resources_per_worker': {},

    'num_cpus_for_driver': 1,
    'num_gpus': 1,

    # === Other ===
    'seed': 1,

    'framework': 'torch',
    'env': 'CartPole-v1'
}


tune.run(
    "DT",
    config=rllib_config
)
```

### Issue Severity

None

**Comment by avnishn** [comment]
you can't delete those lines. or rather, dt is an offline algorithm. It was not written to support online sampling, and it looks like that is what happens when you delete those lines. If you want to delete those lines you'll need to replace them with another offline dataset.
