### ISSUE TITLE
[Workflow] Logger can't handle PyTorch Lightning progress bar

### ISSUE THREAD

**Issue by lcaquot94** [ray-project/ray#33106]
Ray Version : 2.3.0
PyTorch Lightning : 1.6.0
Python : 3.9

I got an issue when trying to use ray workflow with PyTorch Lightning.
I use default progress bar of PyTorch Lightning Trainer when training my model. Everything works fine until I reach the trainer.fit() part of my script where an exception is raised.
I tried calling my task as following (where train model is a ray.remote function):
- `ray.workflow.run(train_model.bind())` --> Not working : this is where I got my issue
- `ray.get(train_model.remote())` --> Working : No problem here
- `ray.workflow.run(train_model.bind())` + `enable_progress_bar=False` in  PyTorch Lightning Trainer parameters --> working 👍
It seems that the issue comes from progress bar characters that are not supported by ray workflow logger...

Here is a stacktrace I get when reachning the Exception:
```
Exception in thread ray_print_logs:
Traceback (most recent call last):
  File "C:\Users\Leonard.Caquot\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\Leonard.Caquot\AppData\Local\Programs\Python\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Leonard.Caquot\PycharmProjects\ai-developments\venv\lib\site-packages\ray\_private\worker.py", line 799, in print_logs
    global_worker_stdstream_dispatcher.emit(data)
  File "C:\Users\Leonard.Caquot\PycharmProjects\ai-developments\venv\lib\site-packages\ray\_private\ray_logging.py", line 317, in emit
    handle(data)
  File "C:\Users\Leonard.Caquot\PycharmProjects\ai-developments\venv\lib\site-packages\ray\_private\worker.py", line 1663, in print_to_stdstream
    print_worker_logs(data, print_file)
  File "C:\Users\Leonard.Caquot\PycharmProjects\ai-developments\venv\lib\site-packages\ray\_private\worker.py", line 1769, in print_worker_logs
    print(
  File "C:\Users\Leonard.Caquot\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 160-164: character maps to <undefined>
```

**Comment by lcaquot94** [comment]
Hi everyone, does someone know how to handle this issue ?

**Comment by phosseini** [comment]
> Hi everyone, does someone know how to handle this issue ?

I'm getting the same error. Did you find a solution by any chance?
