### ISSUE TITLE
[Tune][wandb] Not all logs and artifacts get uploaded to wandb when a Tune experiment finishes

### ISSUE THREAD

**Issue by justinvyu** [ray-project/ray#33129]
### What happened + What you expected to happen

Only 3/5 trials finish uploading all 10 iterations of data. 1/5 trial reports only iteration 0. 1/5 trial reports up to iteration 4.

<img width="393" alt="Screen Shot 2023-03-07 at 10 18 30 PM" src="https://user-images.githubusercontent.com/3887863/223634539-82c504a2-6849-4492-a802-8df115984ebc.png">

This is consistent with missing uploaded checkpoint artifacts (via `WandbLoggerCallback(upload_artifacts=True)`):

<img width="380" alt="Screen Shot 2023-03-07 at 10 19 21 PM" src="https://user-images.githubusercontent.com/3887863/223634689-955bf66d-316e-4533-958e-738db35d25c8.png">

Also, each trial is "running", "finished", or "crashed" randomly in the wandb info tab - they should all be finished...

<img width="367" alt="Screen Shot 2023-03-07 at 10 25 10 PM" src="https://user-images.githubusercontent.com/3887863/223635559-c29c1e0d-cca4-4a2e-9e1e-03441e4f8f37.png">

<img width="358" alt="Screen Shot 2023-03-07 at 10 27 13 PM" src="https://user-images.githubusercontent.com/3887863/223635993-bb686408-627d-4b18-a7ec-a8359afc0119.png">

<img width="318" alt="Screen Shot 2023-03-07 at 10 28 13 PM" src="https://user-images.githubusercontent.com/3887863/223636046-2c9d0481-ba8f-4460-bc9d-cbddf69712f9.png">

### Versions / Dependencies

a50d30ff19ed13cb72b5d8c6fb1c09ea6f5ccde6

### Reproduction script

Run `wandb login` beforehand or provide an API key to the callback.

```python
from ray import air, tune
from ray.air import session, Checkpoint
from ray.air.integrations.wandb import WandbLoggerCallback


def train_fn(config):
    for i in range(10):
        session.report({"score": i}, checkpoint=Checkpoint.from_dict({"score": i}))


if __name__ == "__main__":
    tuner = tune.Tuner(
        train_fn,
        tune_config=tune.TuneConfig(num_samples=5),
        run_config=air.RunConfig(
            callbacks=[
                WandbLoggerCallback(
                    project="test_wandb_checkpointing", upload_checkpoints=True
                ),
            ],
        ),
    )
    results = tuner.fit()

    print(
        "Best hyperparameters found were: ",
        results.get_best_result(metric="score", mode="max").config,
    )
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by justinvyu** [comment]
Adding a sleep at the end of the training loop + lowering # of checkpoints/reports to upload seems to work. Short trials -> Tune experiment ends before the logger callback has time to finish up syncing. This can also happen for realistic examples, if you have a backlog of checkpoints to upload, and the Tune experiment ends before they're all good.

**Comment by justinvyu** [comment]
If you only have a single trial - only a single data point gets logged (0th iteration).

**Comment by justinvyu** [comment]
This log sometimes shows up:
```
(_WandbLoggingActor pid=12946) wandb: Waiting for W&B process to finish... (success).
(_WandbLoggingActor pid=12635) Exception in thread MsgRouterThr:
(_WandbLoggingActor pid=12635) Traceback (most recent call last):
(_WandbLoggingActor pid=12635)   File "/home/ray/anaconda3/lib/python3.9/threading.py", line 980, in _bootstrap_inner
(_WandbLoggingActor pid=12635)     self.run()
(_WandbLoggingActor pid=12635)   File "/home/ray/anaconda3/lib/python3.9/threading.py", line 917, in run
(_WandbLoggingActor pid=12635)     self._target(*self._args, **self._kwargs)
(_WandbLoggingActor pid=12635)   File "/home/ray/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
(_WandbLoggingActor pid=12635)     msg = self._read_message()
(_WandbLoggingActor pid=12635)   File "/home/ray/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/router_queue.py", line 36, in _read_message
(_WandbLoggingActor pid=12635)     msg = self._response_queue.get(timeout=1)
(_WandbLoggingActor pid=12635)   File "/home/ray/anaconda3/lib/python3.9/multiprocessing/queues.py", line 117, in get
(_WandbLoggingActor pid=12635)     res = self._recv_bytes()
(_WandbLoggingActor pid=12635)   File "/home/ray/anaconda3/lib/python3.9/multiprocessing/connection.py", line 212, in recv_bytes
(_WandbLoggingActor pid=12635)     self._check_closed()
(_WandbLoggingActor pid=12635)   File "/home/ray/anaconda3/lib/python3.9/multiprocessing/connection.py", line 136, in _check_closed
(_WandbLoggingActor pid=12635)     raise OSError("handle is closed")
(_WandbLoggingActor pid=12635) OSError: handle is closed
```
