### ISSUE TITLE
[RLlib, Tune] tune.fit() fails for PPO with TypeError: got an unexpected keyword argument 'config'

### ISSUE THREAD

**Issue by PhilippWillms** [ray-project/ray#33148]
### What happened + What you expected to happen

Running PPO for the examples files `action_masking.py` or `custom_env.py` with tune leads to a TypeError. See below the error traceback for the action_masking example:

> Running with following CLI args: Namespace(eager_tracing=False, framework='tf', local_mode=False, no_masking=False, no_tune=False, num_cpus=0, run='PPO', stop_iters=10, stop_reward=80.0, stop_timesteps=10000)
2023-03-08 23:24:58,195 INFO worker.py:1553 -- Started a local Ray instance.
2023-03-08 23:25:01,915 INFO algorithm_config.py:2899 -- Your framework setting is 'tf', meaning you are using static-graph mode. Set framework='tf2' to enable eager execution with tf2.x. You may also then want to set eager_tracing=True in order to reach similar execution speed as with static-graph mode.
2023-03-08 23:25:01,916 INFO algorithm_config.py:2899 -- Your framework setting is 'tf', meaning you are using static-graph mode. Set framework='tf2' to enable eager execution with tf2.x. You may also then want to set eager_tracing=True in order to reach similar execution speed as with static-graph mode.
2023-03-08 23:25:02,087 ERROR ray_trial_executor.py:687 -- Trial PPO_ActionMaskEnv_115cf_00000: Unexpected error starting runner.
Traceback (most recent call last):
  File "C:\Users\Philipp\anaconda3\envs\wksimrl\lib\site-packages\ray\tune\execution\ray_trial_executor.py", line 680, in start_trial
    return self._start_trial(trial)
  File "C:\Users\Philipp\anaconda3\envs\wksimrl\lib\site-packages\ray\tune\execution\ray_trial_executor.py", line 521, in _start_trial
    runner = self._setup_remote_runner(trial)
  File "C:\Users\Philipp\anaconda3\envs\wksimrl\lib\site-packages\ray\tune\execution\ray_trial_executor.py", line 462, in _setup_remote_runner
    return full_actor_class.remote(**kwargs)
  File "C:\Users\Philipp\anaconda3\envs\wksimrl\lib\site-packages\ray\actor.py", line 639, in remote
    return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "C:\Users\Philipp\anaconda3\envs\wksimrl\lib\site-packages\ray\util\tracing\tracing_helper.py", line 387, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "C:\Users\Philipp\anaconda3\envs\wksimrl\lib\site-packages\ray\actor.py", line 886, in _remote
    creation_args = signature.flatten_args(function_signature, args, kwargs)
  File "C:\Users\Philipp\anaconda3\envs\wksimrl\lib\site-packages\ray\_private\signature.py", line 114, in flatten_args
    raise TypeError(str(exc)) from None
**TypeError: got an unexpected keyword argument 'config'**

The expected behavior is that tune fitting can start the trial runs. While the issue can be best demonstrated with the publicly available example file, the impact is potentially high as there seems to be a general issue with PPO, independent on the particular model and environment.

### Versions / Dependencies

ray==2.3.0
tensorflow==2.11.0
numpy==1.23.5
gymnasium==0.26.3

### Reproduction script

Browse to your local ray package installation and execute on terminal:
`python ray/rllib/examples/action_masking.py --run=PPO`

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
Hi @PhilippWillms ,

I can not reproduce the error (Tried using Python 3.10, Ray 2.3.0).
Also, the error looks weird because the Algorithm's constructor generally takes in a kwarg "config".
Is there maybe some information missing here? Did you produce this on a bare clone of the 2.3.0 branch? Or a bare 2.3.0 pip  install?

**Comment by PhilippWillms** [comment]
Hi @ArturNiederfahrenhorst 
it seems it was an issue with "unclean install". For whatever reason, poetry did not install it properly.
After running `pip install --no-cache-dir` it was working fine!
