### ISSUE TITLE
[RLlib] ValueError: mutable default ExecutionResources for field resource_limits is not allowed: use default_factory

### ISSUE THREAD

**Issue by cool-RR** [ray-project/ray#33232]
### What happened + What you expected to happen

```
(ray_env) ➜  nichos git:(master) python -c "import ray.rllib.env.multi_agent_env"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import ray.rllib.env.multi_agent_env
  File "/home/ramrachum/.venvs/ray_env/lib/python3.11/site-packages/ray/rllib/__init__.py", line 7, in <module>
    from ray.rllib.env.base_env import BaseEnv
  File "/home/ramrachum/.venvs/ray_env/lib/python3.11/site-packages/ray/rllib/env/__init__.py", line 1, in <module>
    from ray.rllib.env.base_env import BaseEnv
  File "/home/ramrachum/.venvs/ray_env/lib/python3.11/site-packages/ray/rllib/env/base_env.py", line 6, in <module>
    from ray.rllib.utils.annotations import Deprecated, DeveloperAPI, PublicAPI
  File "/home/ramrachum/.venvs/ray_env/lib/python3.11/site-packages/ray/rllib/utils/__init__.py", line 29, in <module>
    from ray.rllib.utils.test_utils import (
  File "/home/ramrachum/.venvs/ray_env/lib/python3.11/site-packages/ray/rllib/utils/test_utils.py", line 27, in <module>
    from ray import air, tune
  File "/home/ramrachum/.venvs/ray_env/lib/python3.11/site-packages/ray/air/__init__.py", line 2, in <module>
    from ray.air.config import (
  File "/home/ramrachum/.venvs/ray_env/lib/python3.11/site-packages/ray/air/config.py", line 18, in <module>
    from ray.data.preprocessor import Preprocessor
  File "/home/ramrachum/.venvs/ray_env/lib/python3.11/site-packages/ray/data/__init__.py", line 1, in <module>
    from ray.data._internal.compute import ActorPoolStrategy
  File "/home/ramrachum/.venvs/ray_env/lib/python3.11/site-packages/ray/data/_internal/compute.py", line 9, in <module>
    from ray.data._internal.execution.interfaces import TaskContext
  File "/home/ramrachum/.venvs/ray_env/lib/python3.11/site-packages/ray/data/_internal/execution/interfaces.py", line 138, in <module>
    @dataclass
  File "/usr/lib/python3.11/dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           │    └ <class 'ray.data._internal.execution.interfaces.ExecutionOptions'>
           └ <function dataclass.<locals>.wrap at 0x7fea0fb9bec0>
  File "/usr/lib/python3.11/dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
    │                 │          │    │     │     └ False
    │                 │          │    │     └ <class 'ray.data._internal.execution.interfaces.ExecutionResources'>
    │                 │          │    └ 'resource_limits'
    │                 │          └ <class 'ray.data._internal.execution.interfaces.ExecutionOptions'>
    │                 └ <function _get_field at 0x7feae3352a20>
    └ []
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'ray.data._internal.execution.interfaces.ExecutionResources'> for field resource_limits is not allowed: use default_factory
```

### Versions / Dependencies

Ubuntu 22.04.1 LTS
Python 3.11

```
absl-py==1.4.0
aiohttp==3.8.4
aiohttp-cors==0.7.0
aiosignal==1.3.1
alabaster==0.7.13
anyio==3.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
astunparse==1.6.3
async-timeout==4.0.2
attrs==22.2.0
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.11.2
better-exceptions==0.3.3
black==23.1.0
bleach==6.0.0
blessed==1.20.0
cachetools==5.3.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
cloudpickle==2.2.1
colorama==0.4.6
colorful==0.5.5
comm==0.1.2
contourpy==1.0.7
cryptography==39.0.2
cycler==0.11.0
debugpy==1.6.6
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.6
dm-tree==0.1.8
docutils==0.19
entrypoints==0.4
executing==1.2.0
fastjsonschema==2.16.3
filelock==3.9.0
flatbuffers==23.3.3
fonttools==4.39.0
fqdn==1.5.1
frozendict==2.3.5
frozenlist==1.3.3
future==0.18.3
gast==0.4.0
google-api-core==2.11.0
google-auth==2.16.2
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
googleapis-common-protos==1.58.0
gpustat==1.0.0
griddly==1.6.6
grpcio==1.51.3
gym==0.23.1
gym-notices==0.0.8
gymnasium==0.27.1
gymnasium-notices==0.0.1
h5py==3.8.0
hyperopt==0.2.7
idna==3.4
imageio==2.26.0
imagesize==1.4.1
importlab==0.8
iniconfig==2.0.0
ipykernel==6.21.3
ipython==8.11.0
ipython-genutils==0.2.0
ipywidgets==8.0.4
isoduration==20.11.0
jax==0.4.6
jax-jumpy==0.2.0
jedi==0.18.2
Jinja2==3.1.2
joblib==1.2.0
jsonpointer==2.3
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.6.3
jupyter_client==8.0.3
jupyter_core==5.2.0
jupyter_server==2.4.0
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.5
keras==2.12.0rc1
Keras-Preprocessing==1.1.2
kiwisolver==1.4.4
lazy_loader==0.1
libclang==15.0.6.1
libcst==0.4.9
logging-tree==1.9
lxml==4.9.2
lz4==4.3.2
Markdown==3.4.1
MarkupSafe==2.1.2
matplotlib==3.7.1
matplotlib-inline==0.1.6
mistune==2.0.5
more-itertools==9.1.0
msgpack==1.0.5
multidict==6.0.4
mypy==1.1.1
mypy-extensions==1.0.0
nbclassic==0.5.3
nbclient==0.7.2
nbconvert==7.2.9
nbformat==5.7.3
nest-asyncio==1.5.6
networkx==3.0
ninja==1.11.1
notebook==6.5.3
notebook_shim==0.2.2
numpy==1.23.5
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-ml-py==11.495.46
oauthlib==3.2.2
opencensus==0.11.2
opencensus-context==0.1.3
opt-einsum==3.3.0
packaging==23.0
pandas==1.5.3
pandocfilters==1.5.0
parso==0.8.3
pathspec==0.11.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.4.0
platformdirs==3.1.1
plotly==5.13.1
pluggy==1.0.0
prometheus-client==0.16.0
prompt-toolkit==3.0.38
protobuf==3.20.3
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
py-spy==0.3.14
py4j==0.10.9.7
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.10.0
pycparser==2.21
pydantic==1.10.6
pydot==1.4.2
pygame==2.2.0
Pygments==2.14.0
pyOpenSSL==23.0.0
pyparsing==3.0.9
pyrsistent==0.19.3
PySnooper==1.1.1
pytest==7.2.2
python-dateutil==2.8.2
python-json-logger==2.0.7
pytype==2020.2.6
pytz==2022.7.1
PyWavelets==1.4.1
PyYAML==6.0
pyzmq==25.0.0
Qt.py==1.3.8
qtconsole==5.4.0
QtPy==2.3.0
ray==2.3.0
regex==2022.10.31
requests==2.28.2
requests-oauthlib==1.3.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rsa==4.9
ruamel.yaml==0.17.21
scikit-image==0.20.0
scikit-learn==1.2.2
scipy==1.10.1
Send2Trash==1.8.0
six==1.16.0
smart-open==6.3.0
sniffio==1.3.0
snowballstemmer==2.2.0
soupsieve==2.4
Sphinx==6.1.3
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
stack-data==0.6.2
tabulate==0.9.0
tenacity==8.2.2
tensorboard==2.12.0
tensorboard-data-server==0.7.0
tensorboard-plugin-wit==1.8.1
tensorboardX==2.6
tensorflow==2.12.0rc1
tensorflow-estimator==2.12.0rc0
tensorflow-io-gcs-filesystem==0.31.0
tensorflow-probability==0.19.0
termcolor==2.2.0
terminado==0.17.1
testpath==0.6.0
threadpoolctl==3.1.0
tifffile==2023.2.28
tinycss2==1.2.1
tokenizers==0.13.2
toml==0.10.2
tomli==2.0.1
torch==1.13.1
tornado==6.2
tqdm==4.65.0
traitlets==5.9.0
typed-ast==1.5.4
types-PySide2==5.15.2.1.3
typing-inspect==0.8.0
typing_extensions==4.5.0
tzdata==2022.7
unasync==0.5.0
uri-template==1.2.0
urllib3==1.26.15
validators==0.20.0
virtualenv==20.20.0
wcwidth==0.2.6
webcolors==1.12
webencodings==0.5.1
websocket-client==1.5.1
Werkzeug==2.2.3
widgetsnbextension==4.0.5
wrapt==1.14.1
xarray==2023.2.0
yarl==1.8.2
zipp==3.15.0
```

### Reproduction script

```
import ray.rllib.env.multi_agent_env
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by avnishn** [comment]
hey @cool-RR I can't reproduce your issue on master, but also ray does not currently support python 3.11. The latest version we support is 3.10:

https://docs.ray.io/en/latest/ray-overview/installation.html#daily-releases-nightlies

**Comment by cool-RR** [comment]
If Python 3.11 isn't supported, I don't understand the context of this comment on that issue: https://github.com/ray-project/ray/issues/27881#issuecomment-1444862792

**Comment by cool-RR** [comment]
This problem still happens on Ray 2.3.1.

**Comment by avnishn** [comment]
looks like support for 3.11 is still experimental. we'll have to wait for the ray libraries to be tested on 3.11. I think for now only ray core works.

**Comment by cool-RR** [comment]
If support for 3.11 is not working, shouldn't there be an open issue for that? Either this one for this specific problem, or a more general issue for 3.11 support?
