### ISSUE TITLE
Ray component: RLlib -- Have samplers be able to provide a sample batch given specific policies

### ISSUE THREAD

**Issue by aadharna** [ray-project/ray#33255]
### Description

I recently came into a problem where I have lots of policies (because I'm training with self-play) and so I have many policies. My method wants me to get a full matrix of evaluations of the different models I've snapshotted. 

e.g., 
```
score_1_2 = algorithm.rollout_workers.local_worker().sample(policies_to_use=["main_v1", "main_v2"])
```

Right now I can do 
```
algorithm.rollout_workers.local_worker().sample()
```
but that returns a random sample from the policies that the algorithm has and not specific policies.

### Use case

A feature like this is necessary when using methods like `reevaluation evaluation` that want you to build Agent vs Agent score matrices which you can then decompose to inform future updates. 

In my specific case here I am using this to calculate a AvA matrix to then use for novelty calculations to inform diversity optimization.

**Comment by avnishn** [comment]
Thanks for opening this @aadharna . We'll keep track of this as we write our new sampling satck

**Comment by aadharna** [comment]
Just FYI, it seems that my hacked-together-duct tape solution has broken something in ray because I'm getting the following error: 

```
(pid=) configthreadlocale
(pid=) BaseThreadInitThunk
(pid=) RtlUserThreadStart
(pid=) 
2023-03-17 16:35:20,412	ERROR trial_runner.py:993 -- Trial CustomPPO_marching25_no_impute_masked_o1_random_6ad51_00000: Error processing event.
ray.tune.error._TuneNoNextExecutorEventError: Traceback (most recent call last):
  File "D:\miniconda\envs\mapo\lib\site-packages\ray\tune\execution\ray_trial_executor.py", line 1050, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "D:\miniconda\envs\mapo\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "D:\miniconda\envs\mapo\lib\site-packages\ray\_private\worker.py", line 2291, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.

```

I'll add a gist with the necessary files to recreate the error (note, this has been tested on windows so it could just be windows being weird)

**Comment by aadharna** [comment]
The duct tape solution I have was to create the following class and just stick one of these inside my customPPO class: 

```
import ray
import gym

import numpy as np

from ray.rllib.policy.torch_policy import TorchPolicy


# custom remote worker class
class CRW:
    """
    Custom remote worker class
    Temporary workaround for the fact that you cannot do:
    algorithm.evaluation_workers.local_worker().rollout('policy_1', 'policy_2')
    """
    def __init__(self, env_creator, env_config, policy_config):
        self.env = env_creator(env_config)
        self.p1_name = env_config["players_ids"][0]
        self.p2_name = env_config["players_ids"][1]

        if isinstance(self.env.observation_space, gym.spaces.Discrete):
            self.observation_space = gym.spaces.Box(low=0, high=1, shape=(self.env.observation_space.n,))

        # make the config meet minimal requirements that rllib expects
        policy_config['num_gpus'] = 0
        policy_config['_fake_gpus'] = False
        # dummy values
        policy_config['lr'] = 0.0001
        policy_config['explore'] = True

        foo = policy_config.copy()
        foo['model']['custom_model'] = 'masked_mlp'

        # random opponent
        self.p1 = TorchPolicy(observation_space=self.observation_space,
                              action_space=self.env.P2_ACTION_SPACE,
                              config=foo)
        # main agent
        self.p2 = TorchPolicy(observation_space=self.observation_space,
                              action_space=self.env.P2_ACTION_SPACE,
                              config=policy_config)

    def get_discounted_rewards(self, p1_state, p2_state, discount=1.0):
        self.p1.set_state(p1_state)
        self.p2.set_state(p2_state)
        r1_list, r2_list = self.rollout()
        # get rewards for the opponent
        r1_disc = r1_list * discount ** np.arange(len(r1_list))
        r2_disc = r2_list * discount ** np.arange(len(r2_list))
        return {self.p1_name: r1_disc.sum(), self.p2_name: r2_disc.sum()}

    def rollout(self):
        obs = self.env.reset()
        done = {"__all__": False}
        r1_list = []
        r2_list = []
        while not done["__all__"]:
            o1 = obs[self.p1_name]
            o2 = obs[self.p2_name]
            hot_o1 = np.zeros(self.observation_space.shape[0])
            hot_o1[o1] = 1
            hot_o2 = np.zeros(self.observation_space.shape[0])
            hot_o2[o2] = 1
            action1 = self.p1.compute_single_action(obs=hot_o1)[0]
            action2 = self.p2.compute_single_action(obs=hot_o2)[0]
            obs, reward, done, info = self.env.step({self.p1_name: action1, self.p2_name: action2})
            r1_list.append(reward[self.p1_name])
            r2_list.append(reward[self.p2_name])
        return np.array(r1_list), np.array(r2_list)


if __name__ == "__main__":
    from ray.tune import CLIReporter, register_env
    from ray.rllib.models import ModelCatalog
    from RPS_W import IteratedRPS_W
    from mlp import MLP
    from ray.rllib.algorithms.ppo import PPOConfig

    ray.init()
    env_config = {
        # although random is also tagged with a zero, it will get removed when we update the
        #  policy mapping function therefore this doesn't break anything and the original
        #  policy mapping function can be used at the start which will select random
        "players_ids": ["random_r0", "main0"],
        "max_steps": 20,
        "get_additional_info": True,
    }
    game_name = 'foo'

    register_env(game_name, lambda config: IteratedRPS_W(config))
    ModelCatalog.register_custom_model('mlp', MLP)

    config = (
        PPOConfig()
        .environment(env=game_name,
                     env_config=env_config)
        .framework("torch")
        .multi_agent(
            # Initial policy map: Random and PPO. This will be expanded
            # to more policy snapshots taken from "main" against which "main"
            # will then play (instead of "random"). This is done in the
            # custom callback defined above (`SelfPlayCallback`).
            policies={
                env_config["players_ids"][0]: (
                    None,
                    IteratedRPS_W.OBSERVATION_SPACE,
                    IteratedRPS_W.P2_ACTION_SPACE,
                    {'model': {'custom_model': 'mlp'}},
                ),
                env_config["players_ids"][1]: (
                    None,
                    IteratedRPS_W.OBSERVATION_SPACE,
                    IteratedRPS_W.P2_ACTION_SPACE,
                    {'model': {'custom_model': 'mlp'}},
                ),
            },
            # Assign agent 0 and 1 randomly to the "main" policy or
            # to the opponent ("random" at first). Make sure (via episode_id)
            # that "main" always plays against "random" (and not against
            # another "main").
            policy_mapping_fn=lambda agent_id, episode, worker, **kwargs: agent_id,
            # Always just train the "main" policy.
            policies_to_train=["main0"],
        )
        # Use GPUs iff `RLLIB_NUM_GPUS` env var set to > 0.
        .resources(num_gpus=0)
    )

    algo = config.build(env=game_name)
    policy_config = {'model': {'custom_model': 'mlp'}}

    crw = CRW(lambda config: IteratedRPS_W(config), env_config,
              policy_config)

    m_state = algo.get_policy('main0').get_state()
    r_state = algo.get_policy('random_r0').get_state()
    print(crw.get_discounted_rewards(m_state, r_state))

    ray.shutdown()
```

**Comment by aadharna** [comment]
@avnishn here's that gist: https://gist.github.com/aadharna/0dd3edc434d1aefd1e28554a2367f311 I can move this to discuss if that's more appropriate
