### ISSUE TITLE
[Tune] some examples of tune can not work

### ISSUE THREAD

**Issue by chjq201410695** [ray-project/ray#3328]
### System information
- **OS Platform and Distribution：Linux Ubuntu 16.04**:
- **Ray installed from source**:
- **Ray version：0.5.3**:
- **Python version： 3.6.6**:
- **Exact command to reproduce**:

### Describe the problem
I want use ray.tune fine-tuneing my keras DNN model with PBT(scheduler), but it does not work. after that, I directly copy the code of each example in tune. Result shows that all the examples with PBT can not work on my machine.

Please give me some advise. Thank you.

------------------------------------------
### Source code / logs
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:26321 to respond...
Waiting for redis server at 127.0.0.1:60703 to respond...
Starting the Plasma object store with 26.00 GB memory.
Starting local scheduler with the following resources: {'CPU': 12, 'GPU': 3}.

======================================================================
View the web UI at http://localhost:8889/notebooks/ray_ui59239.ipynb?token=5b793ab47f98638597efd33fe07c9f7037f151996f09a40d
======================================================================

== Status ==
PopulationBasedTraining: 0 checkpoints, 0 perturbs

Created LogSyncer for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_0_2018-11-15_13-11-16r0g82miz -> 
== Status ==
PopulationBasedTraining: 0 checkpoints, 0 perturbs
Resources requested: 1/12 CPUs, 0/3 GPUs
Result logdir: /home/zhouhao/ray_results/pbt_test
PENDING trials:
 - MyTrainableClass_1:	PENDING
 - MyTrainableClass_2:	PENDING
 - MyTrainableClass_3:	PENDING
 - MyTrainableClass_4:	PENDING
 - MyTrainableClass_5:	PENDING
 - MyTrainableClass_6:	PENDING
 - MyTrainableClass_7:	PENDING
 - MyTrainableClass_8:	PENDING
 - MyTrainableClass_9:	PENDING
RUNNING trials:
 - MyTrainableClass_0:	RUNNING

Created LogSyncer for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_1_2018-11-15_13-11-16ohm734rd -> 
Created LogSyncer for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_2_2018-11-15_13-11-16o8n9945y -> 
Created LogSyncer for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_3_2018-11-15_13-11-1745sv5k89 -> 
Created LogSyncer for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_4_2018-11-15_13-11-17i6_sblve -> 
Created LogSyncer for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_5_2018-11-15_13-11-17_s98459m -> 
Created LogSyncer for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_6_2018-11-15_13-11-17s0c8fpea -> 
Created LogSyncer for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_7_2018-11-15_13-11-17c1clrzoi -> 
Created LogSyncer for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_8_2018-11-15_13-11-17msy1rt0k -> 
Created LogSyncer for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_9_2018-11-15_13-11-179s0wlhr3 -> 
Remote function __init__ failed with:

Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 84, in __init__
    self._setup()
TypeError: _setup() missing 1 required positional argument: 'config'

Error processing event.
Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 239, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(a93f5394f4c643b91492f94a2b3beff878019d31). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 923, in _process_task
    self.reraise_actor_init_error()
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 267, in reraise_actor_init_error
    raise self.actor_init_error
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 84, in __init__
    self._setup()
TypeError: _setup() missing 1 required positional argument: 'config'

Remote function train failed with:

Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 923, in _process_task
    self.reraise_actor_init_error()
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 267, in reraise_actor_init_error
    raise self.actor_init_error
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 84, in __init__
    self._setup()
TypeError: _setup() missing 1 required positional argument: 'config'

Remote function stop failed with:

Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 923, in _process_task
    self.reraise_actor_init_error()
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 267, in reraise_actor_init_error
    raise self.actor_init_error
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 923, in _process_task
    self.reraise_actor_init_error()
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 267, in reraise_actor_init_error
    raise self.actor_init_error
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 84, in __init__
    self._setup()
TypeError: _setup() missing 1 required positional argument: 'config'

Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.
Worker ip unknown, skipping log sync for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_1_2018-11-15_13-11-16ohm734rd
Error processing event.
Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 239, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(b2be04d13abcd7e7ef7cbaa6f1c1c415860321d5). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 923, in _process_task
    self.reraise_actor_init_error()
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 267, in reraise_actor_init_error
    raise self.actor_init_error
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 84, in __init__
    self._setup()
TypeError: _setup() missing 1 required positional argument: 'config'

Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.

Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.
Worker ip unknown, skipping log sync for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_3_2018-11-15_13-11-1745sv5k89
Error processing event.
Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 239, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(febfa6ee7eee0f47f3362869b50a9a314dca6ee9). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 923, in _process_task
    self.reraise_actor_init_error()
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 267, in reraise_actor_init_error
    raise self.actor_init_error
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 84, in __init__
    self._setup()
TypeError: _setup() missing 1 required positional argument: 'config'

Suppressing duplicate error message.
Worker ip unknown, skipping log sync for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_8_2018-11-15_13-11-17msy1rt0k
Error processing event.
Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 239, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(4145c787694f8b5cf1a4d9d4b71133906e38381b). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 923, in _process_task
    self.reraise_actor_init_error()
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 267, in reraise_actor_init_error
    raise self.actor_init_error
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 84, in __init__
    self._setup()
TypeError: _setup() missing 1 required positional argument: 'config'

Suppressing duplicate error message.
Worker ip unknown, skipping log sync for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_7_2018-11-15_13-11-17c1clrzoi
Error processing event.
Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 239, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(83eb734aa537236f5c5275d5456e9359c001d919). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 923, in _process_task
    self.reraise_actor_init_error()
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 267, in reraise_actor_init_error
    raise self.actor_init_error
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 84, in __init__
    self._setup()
TypeError: _setup() missing 1 required positional argument: 'config'

Suppressing duplicate error message.
Worker ip unknown, skipping log sync for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_6_2018-11-15_13-11-17s0c8fpea
Error processing event.
Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 239, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(a73c88444180e11c96b49f5b9a25672fa17d604c). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 923, in _process_task
    self.reraise_actor_init_error()
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 267, in reraise_actor_init_error
    raise self.actor_init_error
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 84, in __init__
    self._setup()
TypeError: _setup() missing 1 required positional argument: 'config'

Suppressing duplicate error message.
Worker ip unknown, skipping log sync for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_5_2018-11-15_13-11-17_s98459m
Error processing event.
Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 239, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(d9f2904b9faab72ff8d76f228d851a0d86039b14). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 923, in _process_task
    self.reraise_actor_init_error()
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 267, in reraise_actor_init_error
    raise self.actor_init_error
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 84, in __init__
    self._setup()
TypeError: _setup() missing 1 required positional argument: 'config'

Suppressing duplicate error message.
Worker ip unknown, skipping log sync for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_4_2018-11-15_13-11-17i6_sblve
Error processing event.
Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 239, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(65d8acf10a04a54be4c3fad1fbe688806d768f97). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 923, in _process_task
    self.reraise_actor_init_error()
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 267, in reraise_actor_init_error
    raise self.actor_init_error
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 84, in __init__
    self._setup()
TypeError: _setup() missing 1 required positional argument: 'config'

Suppressing duplicate error message.
Worker ip unknown, skipping log sync for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_2_2018-11-15_13-11-16o8n9945y
Error processing event.
Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 239, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(1f283d86b8e3dc4dddf32cb0a8805cbe3d3d721b). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 923, in _process_task
    self.reraise_actor_init_error()
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 267, in reraise_actor_init_error
    raise self.actor_init_error
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 84, in __init__
    self._setup()
TypeError: _setup() missing 1 required positional argument: 'config'

Suppressing duplicate error message.
Worker ip unknown, skipping log sync for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_9_2018-11-15_13-11-179s0wlhr3
Error processing event.
Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 239, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(df3acec589ab598c7c09b30a16bcaa41b27dce03). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 923, in _process_task
    self.reraise_actor_init_error()
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 267, in reraise_actor_init_error
    raise self.actor_init_error
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/zhouhao/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 84, in __init__
    self._setup()
TypeError: _setup() missing 1 required positional argument: 'config'

Suppressing duplicate error message.
Worker ip unknown, skipping log sync for /home/zhouhao/ray_results/pbt_test/MyTrainableClass_0_2018-11-15_13-11-16r0g82miz
== Status ==
PopulationBasedTraining: 0 checkpoints, 0 perturbs
Resources requested: 0/12 CPUs, 0/3 GPUs
Result logdir: /home/zhouhao/ray_results/pbt_test
ERROR trials:
 - MyTrainableClass_0:	ERROR, 1 failures: /home/zhouhao/ray_results/pbt_test/MyTrainableClass_0_2018-11-15_13-11-16r0g82miz/error_2018-11-15_13-11-21.txt
 - MyTrainableClass_1:	ERROR, 1 failures: /home/zhouhao/ray_results/pbt_test/MyTrainableClass_1_2018-11-15_13-11-16ohm734rd/error_2018-11-15_13-11-19.txt
 - MyTrainableClass_2:	ERROR, 1 failures: /home/zhouhao/ray_results/pbt_test/MyTrainableClass_2_2018-11-15_13-11-16o8n9945y/error_2018-11-15_13-11-21.txt
 - MyTrainableClass_3:	ERROR, 1 failures: /home/zhouhao/ray_results/pbt_test/MyTrainableClass_3_2018-11-15_13-11-1745sv5k89/error_2018-11-15_13-11-19.txt
 - MyTrainableClass_4:	ERROR, 1 failures: /home/zhouhao/ray_results/pbt_test/MyTrainableClass_4_2018-11-15_13-11-17i6_sblve/error_2018-11-15_13-11-20.txt
 - MyTrainableClass_5:	ERROR, 1 failures: /home/zhouhao/ray_results/pbt_test/MyTrainableClass_5_2018-11-15_13-11-17_s98459m/error_2018-11-15_13-11-20.txt
 - MyTrainableClass_6:	ERROR, 1 failures: /home/zhouhao/ray_results/pbt_test/MyTrainableClass_6_2018-11-15_13-11-17s0c8fpea/error_2018-11-15_13-11-20.txt
 - MyTrainableClass_7:	ERROR, 1 failures: /home/zhouhao/ray_results/pbt_test/MyTrainableClass_7_2018-11-15_13-11-17c1clrzoi/error_2018-11-15_13-11-19.txt
 - MyTrainableClass_8:	ERROR, 1 failures: /home/zhouhao/ray_results/pbt_test/MyTrainableClass_8_2018-11-15_13-11-17msy1rt0k/error_2018-11-15_13-11-19.txt
 - MyTrainableClass_9:	ERROR, 1 failures: /home/zhouhao/ray_results/pbt_test/MyTrainableClass_9_2018-11-15_13-11-179s0wlhr3/error_2018-11-15_13-11-21.txt

---------------------------------------------------------------------------
TuneError                                 Traceback (most recent call last)
<ipython-input-1-381ca3f603f6> in <module>
     95         },
     96         scheduler=pbt,
---> 97         verbose=False)

~/.local/lib/python3.6/site-packages/ray/tune/tune.py in run_experiments(experiments, search_alg, scheduler, with_server, server_port, verbose, queue_trials, trial_executor)
    116 
    117     if errored_trials:
--> 118         raise TuneError("Trials did not complete", errored_trials)
    119 
    120     wait_for_log_sync()

TuneError: ('Trials did not complete', [MyTrainableClass_0, MyTrainableClass_1, MyTrainableClass_2, MyTrainableClass_3, MyTrainableClass_4, MyTrainableClass_5, MyTrainableClass_6, MyTrainableClass_7, MyTrainableClass_8, MyTrainableClass_9])

**Comment by richardliaw** [comment]
Hi,

Can you install Ray from the latest wheels?
https://ray.readthedocs.io/en/latest/installation.html Let me know if you
still run into any issues.

Thanks!
Richard

**Comment by richardliaw** [comment]
The first two seem odd - does it work if you run `python tune_mnist_ray.py` and `python tune_mnist_keras.py` rather than via ipython or some other kernel?

For the CIFAR10 example, I think you may want to try running (separately in a separate script first): 
```
from tensorflow.python.keras.datasets import cifar10
cifar10.load_data()
```

This should download the data onto your local machine.

**Comment by chjq201410695** [comment]
OK thanks， these can work on pycharm.
