### ISSUE TITLE
[docs] Improve error message when the wrong pickle version is installed

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#33407]
### Description

Running the Getting Started example, I ran into this error message. Since it's a known issue, could we improve the error message?

2023-03-16 13:54:40,606	WARNING worker.py:1851 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 8c3ebfc86d9ecb4ac14eeb7ef10d5464a8cb9b1f01000000 Worker ID: 17f98d7c6518bab85b6162f6d004f10db0dc6d38ef001331b45785e5 Node ID: 0e8172d52bd6e0917a45b357e9c91cf8fcd62729383587d44c21b515 Worker IP address: 127.0.0.1 Worker port: 54680 Worker PID: 14061 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.

**Comment by bveeramani** [comment]
@angelinalg could you remind me of your Python and Ray versions, and also share the full traceback?

**Comment by angelinalg** [comment]
ray==2.3.0

(ray) angelina@AngelinasLaptop ~ % python --version
Python 3.9.15

(ray) angelina@AngelinasLaptop ~ % python data.py
2023-03-16 13:54:32,712	INFO worker.py:1538 -- Started a local Ray instance.
2023-03-16 13:54:40,079	WARNING read_api.py:326 -- ⚠️  The number of blocks in this dataset (1) limits its parallelism to 1 concurrent tasks. This is much less than the number of available CPU slots in the cluster. Use `.repartition(n)` to increase the number of dataset blocks.
2023-03-16 13:54:40,606	WARNING worker.py:1851 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 8c3ebfc86d9ecb4ac14eeb7ef10d5464a8cb9b1f01000000 Worker ID: 17f98d7c6518bab85b6162f6d004f10db0dc6d38ef001331b45785e5 Node ID: 0e8172d52bd6e0917a45b357e9c91cf8fcd62729383587d44c21b515 Worker IP address: 127.0.0.1 Worker port: 54680 Worker PID: 14061 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
(_execute_read_task_split pid=14061) 2023-03-16 13:54:40,601	INFO worker.py:763 -- Task failed with retryable exception: TaskID(32d950ec0ccf9d2affffffffffffffffffffffff01000000).
(_execute_read_task_split pid=14061) Traceback (most recent call last):
(_execute_read_task_split pid=14061)   File "python/ray/_raylet.pyx", line 619, in ray._raylet.execute_dynamic_generator_and_store_task_outputs
(_execute_read_task_split pid=14061)   File "python/ray/_raylet.pyx", line 2447, in ray._raylet.CoreWorker.store_task_outputs
(_execute_read_task_split pid=14061)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/serialization.py", line 450, in serialize
(_execute_read_task_split pid=14061)     return self._serialize_to_msgpack(value)
(_execute_read_task_split pid=14061)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/serialization.py", line 428, in _serialize_to_msgpack
(_execute_read_task_split pid=14061)     pickle5_serialized_object = self._serialize_to_pickle5(
(_execute_read_task_split pid=14061)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/serialization.py", line 390, in _serialize_to_pickle5
(_execute_read_task_split pid=14061)     raise e
(_execute_read_task_split pid=14061)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/serialization.py", line 385, in _serialize_to_pickle5
(_execute_read_task_split pid=14061)     inband = pickle.dumps(
(_execute_read_task_split pid=14061)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
(_execute_read_task_split pid=14061)     cp.dump(obj)
(_execute_read_task_split pid=14061)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 627, in dump
(_execute_read_task_split pid=14061)     return Pickler.dump(self, obj)
(_execute_read_task_split pid=14061) TypeError: cannot pickle 'pickle5.PickleBuffer' object
2023-03-16 13:54:41,719	WARNING worker.py:1851 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: de429f156b4d85df80b1e59281561590a93f842201000000 Worker ID: fa9fd1e2e9cf1190eac6c2461cbe484ef4b7a01611b1454af4f0f1f9 Node ID: 0e8172d52bd6e0917a45b357e9c91cf8fcd62729383587d44c21b515 Worker IP address: 127.0.0.1 Worker port: 54673 Worker PID: 14068 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
(_execute_read_task_split pid=14068) 2023-03-16 13:54:41,713	INFO worker.py:763 -- Task failed with retryable exception: TaskID(32d950ec0ccf9d2affffffffffffffffffffffff01000000).
(_execute_read_task_split pid=14068) Traceback (most recent call last):
(_execute_read_task_split pid=14068)   File "python/ray/_raylet.pyx", line 619, in ray._raylet.execute_dynamic_generator_and_store_task_outputs
(_execute_read_task_split pid=14068)   File "python/ray/_raylet.pyx", line 2447, in ray._raylet.CoreWorker.store_task_outputs
(_execute_read_task_split pid=14068)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/serialization.py", line 450, in serialize
(_execute_read_task_split pid=14068)     return self._serialize_to_msgpack(value)
(_execute_read_task_split pid=14068)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/serialization.py", line 428, in _serialize_to_msgpack
(_execute_read_task_split pid=14068)     pickle5_serialized_object = self._serialize_to_pickle5(
(_execute_read_task_split pid=14068)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/serialization.py", line 390, in _serialize_to_pickle5
(_execute_read_task_split pid=14068)     raise e
(_execute_read_task_split pid=14068)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/serialization.py", line 385, in _serialize_to_pickle5
(_execute_read_task_split pid=14068)     inband = pickle.dumps(
(_execute_read_task_split pid=14068)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
(_execute_read_task_split pid=14068)     cp.dump(obj)
(_execute_read_task_split pid=14068)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 627, in dump
(_execute_read_task_split pid=14068)     return Pickler.dump(self, obj)
(_execute_read_task_split pid=14068) TypeError: cannot pickle 'pickle5.PickleBuffer' object
2023-03-16 13:54:42,686	WARNING worker.py:1851 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 6ab32a57fa1c871863e61e31fda298095501051f01000000 Worker ID: 59fefcbbdf2191386a188888547c7538529a573f6f18b8f05fdda8c8 Node ID: 0e8172d52bd6e0917a45b357e9c91cf8fcd62729383587d44c21b515 Worker IP address: 127.0.0.1 Worker port: 54666 Worker PID: 14066 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
(_execute_read_task_split pid=14066) 2023-03-16 13:54:42,678	INFO worker.py:763 -- Task failed with retryable exception: TaskID(32d950ec0ccf9d2affffffffffffffffffffffff01000000).
(_execute_read_task_split pid=14066) Traceback (most recent call last):
(_execute_read_task_split pid=14066)   File "python/ray/_raylet.pyx", line 619, in ray._raylet.execute_dynamic_generator_and_store_task_outputs
(_execute_read_task_split pid=14066)   File "python/ray/_raylet.pyx", line 2447, in ray._raylet.CoreWorker.store_task_outputs
(_execute_read_task_split pid=14066)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/serialization.py", line 450, in serialize
(_execute_read_task_split pid=14066)     return self._serialize_to_msgpack(value)
(_execute_read_task_split pid=14066)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/serialization.py", line 428, in _serialize_to_msgpack
(_execute_read_task_split pid=14066)     pickle5_serialized_object = self._serialize_to_pickle5(
(_execute_read_task_split pid=14066)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/serialization.py", line 390, in _serialize_to_pickle5
(_execute_read_task_split pid=14066)     raise e
(_execute_read_task_split pid=14066)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/serialization.py", line 385, in _serialize_to_pickle5
(_execute_read_task_split pid=14066)     inband = pickle.dumps(
(_execute_read_task_split pid=14066)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
(_execute_read_task_split pid=14066)     cp.dump(obj)
(_execute_read_task_split pid=14066)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 627, in dump
(_execute_read_task_split pid=14066)     return Pickler.dump(self, obj)
(_execute_read_task_split pid=14066) TypeError: cannot pickle 'pickle5.PickleBuffer' object
2023-03-16 13:54:43,661	WARNING worker.py:1851 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: c6bca86d514a58fc457d1481955c058ab164cb1b01000000 Worker ID: 7aab204d53c455478d6dcc21ae655d258e6c492792b3b9dcf0422c4b Node ID: 0e8172d52bd6e0917a45b357e9c91cf8fcd62729383587d44c21b515 Worker IP address: 127.0.0.1 Worker port: 54661 Worker PID: 14063 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
Traceback (most recent call last):
  File "/Users/angelina/data.py", line 4, in <module>
    dataset = ray.data.read_csv("s3://anonymous@air-example-data/breast_cancer.csv")
  File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/data/read_api.py", line 858, in read_csv
    return read_datasource(
  File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/data/read_api.py", line 339, in read_datasource
    block_list.ensure_metadata_for_first_block()
  File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/data/_internal/lazy_block_list.py", line 387, in ensure_metadata_for_first_block
    generator = ray.get(block_partition_ref)
  File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
(_execute_read_task_split pid=14063) 2023-03-16 13:54:43,656	INFO worker.py:763 -- Task failed with retryable exception: TaskID(32d950ec0ccf9d2affffffffffffffffffffffff01000000).
(_execute_read_task_split pid=14063) Traceback (most recent call last):
(_execute_read_task_split pid=14063)   File "python/ray/_raylet.pyx", line 619, in ray._raylet.execute_dynamic_generator_and_store_task_outputs
(_execute_read_task_split pid=14063)   File "python/ray/_raylet.pyx", line 2447, in ray._raylet.CoreWorker.store_task_outputs
(_execute_read_task_split pid=14063)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/serialization.py", line 450, in serialize
(_execute_read_task_split pid=14063)     return self._serialize_to_msgpack(value)
(_execute_read_task_split pid=14063)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/serialization.py", line 428, in _serialize_to_msgpack
(_execute_read_task_split pid=14063)     pickle5_serialized_object = self._serialize_to_pickle5(
(_execute_read_task_split pid=14063)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/serialization.py", line 390, in _serialize_to_pickle5
(_execute_read_task_split pid=14063)     raise e
(_execute_read_task_split pid=14063)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/_private/serialization.py", line 385, in _serialize_to_pickle5
(_execute_read_task_split pid=14063)     inband = pickle.dumps(
(_execute_read_task_split pid=14063)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
(_execute_read_task_split pid=14063)     cp.dump(obj)
(_execute_read_task_split pid=14063)   File "/Users/angelina/miniforge3/envs/ray/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 627, in dump
(_execute_read_task_split pid=14063)     return Pickler.dump(self, obj)
(_execute_read_task_split pid=14063) TypeError: cannot pickle 'pickle5.PickleBuffer' object

**Comment by bveeramani** [comment]
Interesting. Looks like we already check for this in `ray/__init__.py`
```
def _configure_system():
    import os
    import platform
    import sys

    """Wraps system configuration to avoid 'leaking' variables into ray."""

    # Sanity check pickle5 if it has been installed.
    if "pickle5" in sys.modules:
        if sys.version_info >= (3, 8):
            logger.warning(
                "Package pickle5 becomes unnecessary in Python 3.8 and above. "
                "Its presence may confuse libraries including Ray. "
                "Please uninstall the package."
            )
```

Maybe there's a problem with out check `"pickle5" in sys.modules`?

**Comment by angelinalg** [comment]
Here is the code I was trying to run:
(ray) angelina@AngelinasLaptop ~ % more data.py
import ray

# Load data.
dataset = ray.data.read_csv("s3://anonymous@air-example-data/breast_cancer.csv")

# Split data into train and validation.
train_dataset, valid_dataset = dataset.train_test_split(test_size=0.3)

# Create a test dataset by dropping the target column.
test_dataset = valid_dataset.drop_columns(cols=["target"])

The command I typed at the CL is:
 % python data.py

**Comment by bveeramani** [comment]
Closing because I couldn't reproduce with Python 3.9 and Ray 2.3.
