### ISSUE TITLE
[RLlib] examples/attention_net.py throws error

### ISSUE THREAD

**Issue by gdevos010** [ray-project/ray#33462]
### What happened + What you expected to happen

when running the [attention_net.py](https://github.com/ray-project/ray/blob/master/rllib/examples/attention_net.py) in no tune mode, `compute_single_action` throws the following exception:

```bash
Traceback (most recent call last):
  File "/home/greg.devosnouri@int-episci.com/passerine/starling_rl/ray_examples/attention_net.py", line 198, in <module>
    action, state_out, _ = algo.compute_single_action(obs, state)
  File "/home/greg.devosnouri@int-episci.com/.local/share/virtualenvs/starling_rl-vx1Lc4ph/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 1577, in compute_single_action
    action, state, extra = policy.compute_single_action(
  File "/home/greg.devosnouri@int-episci.com/.local/share/virtualenvs/starling_rl-vx1Lc4ph/lib/python3.10/site-packages/ray/rllib/policy/policy.py", line 507, in compute_single_action
    out = self.compute_actions_from_input_dict(
  File "/home/greg.devosnouri@int-episci.com/.local/share/virtualenvs/starling_rl-vx1Lc4ph/lib/python3.10/site-packages/ray/rllib/policy/torch_policy_v2.py", line 506, in compute_actions_from_input_dict
    return self._compute_action_helper(
  File "/home/greg.devosnouri@int-episci.com/.local/share/virtualenvs/starling_rl-vx1Lc4ph/lib/python3.10/site-packages/ray/rllib/utils/threading.py", line 24, in wrapper
    return func(self, *a, **k)
  File "/home/greg.devosnouri@int-episci.com/.local/share/virtualenvs/starling_rl-vx1Lc4ph/lib/python3.10/site-packages/ray/rllib/policy/torch_policy_v2.py", line 1097, in _compute_action_helper
    dist_inputs, state_out = self.model(input_dict, state_batches, seq_lens)
  File "/home/greg.devosnouri@int-episci.com/.local/share/virtualenvs/starling_rl-vx1Lc4ph/lib/python3.10/site-packages/ray/rllib/models/modelv2.py", line 259, in __call__
    res = self.forward(restored, state or [], seq_lens)
  File "/home/greg.devosnouri@int-episci.com/.local/share/virtualenvs/starling_rl-vx1Lc4ph/lib/python3.10/site-packages/ray/rllib/models/torch/attention_net.py", line 436, in forward
    self._features, memory_outs = self.gtrxl(input_dict, state, seq_lens)
  File "/home/greg.devosnouri@int-episci.com/.local/share/virtualenvs/starling_rl-vx1Lc4ph/lib/python3.10/site-packages/ray/rllib/models/modelv2.py", line 259, in __call__
    res = self.forward(restored, state or [], seq_lens)
  File "/home/greg.devosnouri@int-episci.com/.local/share/virtualenvs/starling_rl-vx1Lc4ph/lib/python3.10/site-packages/ray/rllib/models/torch/attention_net.py", line 223, in forward
    all_out = self.layers[i](all_out, memory=state[i // 2])
  File "/home/greg.devosnouri@int-episci.com/.local/share/virtualenvs/starling_rl-vx1Lc4ph/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/greg.devosnouri@int-episci.com/.local/share/virtualenvs/starling_rl-vx1Lc4ph/lib/python3.10/site-packages/ray/rllib/models/torch/modules/skip_connection.py", line 32, in forward
    outputs = self._layer(inputs, **kwargs)
  File "/home/greg.devosnouri@int-episci.com/.local/share/virtualenvs/starling_rl-vx1Lc4ph/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/greg.devosnouri@int-episci.com/.local/share/virtualenvs/starling_rl-vx1Lc4ph/lib/python3.10/site-packages/ray/rllib/models/torch/modules/relative_multi_head_attention.py", line 120, in forward
    inputs = torch.cat((memory.detach(), inputs), dim=1)
RuntimeError: Tensors must have same number of dimensions: got 2 and 3
```

### Versions / Dependencies

ray: 2.3
python: 3.10.10

### Reproduction script

```bash
python rattention_net.py --framework="torch" --no-tune --stop-reward=2
```

### Issue Severity

None

**Comment by JesseLT** [comment]
How do you fix it now?@[gdevos010](https://github.com/gdevos010)

**Comment by shajeeck** [comment]
Any fix or workaround? @kouroshHakha

**Comment by JesseLT** [comment]
> Any fix or workaround? @kouroshHakha @JesseLT

add this line `
state = np.expand_dims(state, axis=0)
` after the line `state = algo.get_policy().get_initial_state()`
