### ISSUE TITLE
[state api] better error message when applying filters to ray list command 

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#33548]
### What happened + What you expected to happen

I tried to filter tasks by state and saw this error. The problem is that I used the wrong format but the error message is not to the point. Not sure if we could provide a specific error for wrong formats but maybe at least give an example of how to use filter in the error message?

```
(base) ray@ip-10-0-25-201:~/default$ ray list tasks --filter={state=running}
Usage: ray list [OPTIONS] {actors|jobs|placement-
                groups|nodes|workers|tasks|objects|runtime-envs|cluster-
                events}
Try 'ray list --help' for help.

Error: API server internal error. See dashboard.log file for more details. Error: Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/optional_utils.py", line 95, in _handler_route
    return await handler(bind_info.instance, req)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/modules/state/state_head.py", line 113, in async_wrapper
    ret = await func(self, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/modules/state/state_head.py", line 327, in list_tasks
    return await self._handle_list_api(self._state_api.list_tasks, req)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/modules/state/state_head.py", line 274, in _handle_list_api
    result = await list_api_fn(option=self._options_from_req(req))
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/state_aggregator.py", line 485, in list_tasks
    result = self._filter(result, option.filters, TaskState, option.detail)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/state_aggregator.py", line 173, in _filter
    raise ValueError(
ValueError: The given filter column {state is not supported. Supported filter columns: {'func_or_class_name', 'language', 'node_id', 'task_id', 'parent_task_id', 'placement_group_id', 'name', 'state', 'actor_id', 'attempt_number', 'job_id', 'worker_id', 'type'}

==========ALPHA, FEEDBACK NEEDED ===============
State Observability APIs is currently in Alpha. 
If you have any feedback, you could do so at either way as below:
    1. Report bugs/issues with details: https://forms.gle/gh77mwjEskjhN8G46
    2. Follow up in #ray-state-observability-dogfooding slack channel of Ray: https://tinyurl.com/2pm26m4a
==========================================================
```
```

### Versions / Dependencies

nightly

### Reproduction script

n/a

### Issue Severity

None

**Comment by scottsun94** [comment]
unstale
