### ISSUE TITLE
[State api] Error when using ray get tasks

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#33551]
### What happened + What you expected to happen

Ran into an error when trying to get a task.

1. not sure what's the issue. Cannot get a finished task?
2. the error message doesn't really help. We should provide actionable error emssage

```
(base) ray@ip-10-0-25-201:~/default$ ray list tasks --limit=10
/home/ray/anaconda3/lib/python3.10/site-packages/ray/experimental/state/api.py:374: UserWarning: The returned data may contain incomplete result. 10000 (63000 total from the cluster) tasks are retrieved from the data source. 53000 entries have been truncated. Max of 10000 entries are retrieved from data source to prevent over-sized payloads.
  warnings.warn(
/home/ray/anaconda3/lib/python3.10/site-packages/ray/experimental/state/api.py:391: UserWarning: Limit last 10 entries (Total 10000). Use `--filter` to reduce the amount of data to return or setting a higher limit with `--limit` to see all data. 
  warnings.warn(

======== List: 2023-03-21 14:55:53.503955 ========
Stats:
------------------------------
Total: 10

Table:
------------------------------
    TASK_ID                                             ATTEMPT_NUMBER  NAME                STATE       JOB_ID  NODE_ID                                                   ACTOR_ID                          TYPE        FUNC_OR_CLASS_NAME    PARENT_TASK_ID                                    WORKER_ID                                                 ERROR_TYPE
 0  00061682be66de000c423a6a022cfc487a94853106000000                 0  ImplicitFunc.train  FINISHED  06000000  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  0c423a6a022cfc487a94853106000000  ACTOR_TASK  ImplicitFunc.train    ffffffffffffffffffffffffffffffffffffffff06000000  99f9532797cf1d6d28dac78b0d6c638249626abbfa37da090fc9cc6b
 1  000ca652d088b5b6e52c8841707ffb604e656eea06000000                 0  ImplicitFunc.train  FINISHED  06000000  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  e52c8841707ffb604e656eea06000000  ACTOR_TASK  ImplicitFunc.train    ffffffffffffffffffffffffffffffffffffffff06000000  35b8d8041bb2d9a010ceb45d2860cdde4d33621ed327fbcca86976eb
 2  0015b4a8b115cd9e7dc11e599a5ce18cf1ae1df406000000                 0  ImplicitFunc.train  FINISHED  06000000  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  7dc11e599a5ce18cf1ae1df406000000  ACTOR_TASK  ImplicitFunc.train    ffffffffffffffffffffffffffffffffffffffff06000000  ac1c9fb62927c1dc9061255c8e52854185c2086f2476fa27c3785e16
 3  001705ea4e085bb3e52c8841707ffb604e656eea06000000                 0  ImplicitFunc.train  FINISHED  06000000  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  e52c8841707ffb604e656eea06000000  ACTOR_TASK  ImplicitFunc.train    ffffffffffffffffffffffffffffffffffffffff06000000  35b8d8041bb2d9a010ceb45d2860cdde4d33621ed327fbcca86976eb
 4  002113c91b9143540c423a6a022cfc487a94853106000000                 0  ImplicitFunc.train  FINISHED  06000000  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  0c423a6a022cfc487a94853106000000  ACTOR_TASK  ImplicitFunc.train    ffffffffffffffffffffffffffffffffffffffff06000000  99f9532797cf1d6d28dac78b0d6c638249626abbfa37da090fc9cc6b
 5  0026c0d7616569fde52c8841707ffb604e656eea06000000                 0  ImplicitFunc.train  FINISHED  06000000  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  e52c8841707ffb604e656eea06000000  ACTOR_TASK  ImplicitFunc.train    ffffffffffffffffffffffffffffffffffffffff06000000  35b8d8041bb2d9a010ceb45d2860cdde4d33621ed327fbcca86976eb
 6  0029b07f98cad6fb7dc11e599a5ce18cf1ae1df406000000                 0  ImplicitFunc.train  FINISHED  06000000  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  7dc11e599a5ce18cf1ae1df406000000  ACTOR_TASK  ImplicitFunc.train    ffffffffffffffffffffffffffffffffffffffff06000000  ac1c9fb62927c1dc9061255c8e52854185c2086f2476fa27c3785e16
 7  002b4aa46848feb6e52c8841707ffb604e656eea06000000                 0  ImplicitFunc.train  FINISHED  06000000  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  e52c8841707ffb604e656eea06000000  ACTOR_TASK  ImplicitFunc.train    ffffffffffffffffffffffffffffffffffffffff06000000  35b8d8041bb2d9a010ceb45d2860cdde4d33621ed327fbcca86976eb
 8  00395c4fa9b25af3b8db56d7c0c683f795ee57bf06000000                 0  ImplicitFunc.train  FINISHED  06000000  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  b8db56d7c0c683f795ee57bf06000000  ACTOR_TASK  ImplicitFunc.train    ffffffffffffffffffffffffffffffffffffffff06000000  b6ead798fa7996a15973444707d088d2a2c85c45b2c7aef6e735f8f4
 9  004465bd52418d6c0c423a6a022cfc487a94853106000000                 0  ImplicitFunc.train  FINISHED  06000000  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  0c423a6a022cfc487a94853106000000  ACTOR_TASK  ImplicitFunc.train    ffffffffffffffffffffffffffffffffffffffff06000000  99f9532797cf1d6d28dac78b0d6c638249626abbfa37da090fc9cc6b

(base) ray@ip-10-0-25-201:~/default$ ray get tasks 00061682be66de000c423a6a022cfc487a94853106000000
Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/scripts/scripts.py", line 2472, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/experimental/state/state_cli.py", line 421, in ray_get
    format_get_api_output(
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/experimental/state/state_cli.py", line 291, in format_get_api_output
    augmented_task_state_data = [
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/experimental/state/state_cli.py", line 292, in <listcomp>
    {("task_id: " + state["task_id"]): state} for state in state_data
TypeError: string indices must be integers
(base) ray@ip-10-0-25-201:~/default$ 
```

### Versions / Dependencies

nightly

### Reproduction script

n/a

### Issue Severity

None

**Comment by scottsun94** [comment]
unstale
