### ISSUE TITLE
[State api] Not sure if I can run ray get cluster-events 

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#33559]
### What happened + What you expected to happen

`ray get --help` tells me that i could `ray get cluster-events ID` but I ran into the error that is opposite to it.
```
(base) ray@ip-10-0-25-201:~/default$ ray list cluster-events
ray 
======== List: 2023-03-21 16:00:49.422621 ========
Stats:
------------------------------
Total: 1

Table:
------------------------------
    SEVERITY    TIME                 SOURCE_TYPE    MESSAGE             EVENT_ID
 0  INFO        2023-03-21 18:50:20  AUTOSCALER     Resized to 8 CPUs.  77a5BCbc2d82EE25DcBd3fEA9AD6Ce83ABEF

ge(base) ray@ip-10-0-25-201:~/default$ ray get cluster-events 77a5BCbc2d82EE25DcBd3fEA9AD6Ce83ABEF
Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/scripts/scripts.py", line 2472, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/experimental/state/state_cli.py", line 410, in ray_get
    data = client.get(
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/experimental/state/api.py", line 296, in get
    raise ValueError(f"Can't get {resource.name} by id.")
ValueError: Can't get CLUSTER_EVENTS by id.
(base) ray@ip-10-0-25-201:~/default$ ray get --help
Usage: ray get [OPTIONS] {actors|placement-
               groups|nodes|workers|tasks|objects|cluster-events} ID

  Get a state of a given resource by ID.

  We currently DO NOT support get by id for jobs and runtime-envs

  The output schema is defined at :ref:`State API Schema section. <state-api-
  schema>`

  For example, the output schema of `ray get tasks <task-id>` is
  :class:`~ray.experimental.state.common.TaskState`.

  Usage:

      Get an actor with actor id <actor-id>

      ```     ray get actors <actor-id>     ```

      Get a placement group information with <placement-group-id>

      ```     ray get placement-groups <placement-group-id>     ```

  The API queries one or more components from the cluster to obtain the data.
  The returned state snapshot could be stale, and it is not guaranteed to
  return the live data.

  Args:     resource: The type of the resource to query.     id: The id of the
  resource.

  Raises:     :class:`RayStateApiException
  <ray.experimental.state.exception.RayStateApiException>`         if the CLI
  is failed to query the data.

  **PublicAPI (alpha):** This API is in alpha and may change before becoming
  stable.

Options:
  --address TEXT     The address of Ray API server. If not provided, it will
                     be configured automatically from querying the GCS server.
  --timeout INTEGER  Timeout in seconds for the API requests. Default is 30
  --help             Show this message and exit.
```

### Versions / Dependencies

nightly

### Reproduction script

n/a

### Issue Severity

None

**Comment by scottsun94** [comment]
Unstale
