### ISSUE TITLE
[AIR] `TuneError` shouldn't get propagated when using Train only

### ISSUE THREAD

**Issue by justinvyu** [ray-project/ray#33566]
### What happened + What you expected to happen

When a Train experiment fails during the actual call to `trainer.fit()`, some errors propagated by `tuner.fit()` that gets called under the hood will raise a `TuneError` and tell users to restore using `Tuner.restore`. This should be a training failed error and direct users to use `XTrainer.restore` instead.

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "error_prop.py", line 22, in <module>
    t.fit()
  File "/Users/justin/Developer/justinvyu-dev/python/ray/train/base_trainer.py", line 576, in fit
    result_grid = tuner.fit()
  File "/Users/justin/Developer/justinvyu-dev/python/ray/tune/tuner.py", line 352, in fit
    raise TuneError(
ray.tune.error.TuneError: The Ray Tune run failed. Please inspect the previous error messages for a cause. After fixing the issue, you can restart the run from scratch or continue this run. To continue this run, you can use `tuner = Tuner.restore("/Users/justin/ray_results/DataParallelTrainer_2023-03-21_17-22-07")`.
```

### Versions / Dependencies

83dc07a28d7f9427366bc22e7ce57c07af5b63a2

### Reproduction script

```python
import ray
from ray import air, tune
from ray.air import session
from ray.train.data_parallel_trainer import DataParallelTrainer
from ray.tune import Callback


class C(Callback):
    def on_trial_result(self, *args, **kwargs):
        raise RuntimeError()


def train_loop(config):
    session.report({"score": 1})


t = DataParallelTrainer(
    train_loop,
    scaling_config=air.ScalingConfig(num_workers=1),
    run_config=air.RunConfig(callbacks=[C()]),
)
t.fit()

```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by amogkam** [comment]
There should never be a reason why `TuneError` is exposed to the user: https://github.com/ray-project/ray/pull/30817.

All exceptions raised on the driver should be proper exceptions, and not TuneError
