### ISSUE TITLE
[State api] ux issues with ray logs worker

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#33583]
### What happened + What you expected to happen

I have several questions:
- by default, does it open `.out` or `.err` of the worker log files?
- we should provide a better error message when users try to fetch logs of a driver?

```
(base) ray@ip-10-0-25-201:~/default$ ray list workers

======== List: 2023-03-21 20:37:16.471367 ========
Stats:
------------------------------
Total: 68

Table:
------------------------------
    WORKER_ID                                                 IS_ALIVE    WORKER_TYPE    EXIT_TYPE             NODE_ID                                                   IP              PID
 0  01000000ffffffffffffffffffffffffffffffffffffffffffffffff  False       DRIVER         INTENDED_USER_EXIT    ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201    4489
 1  02000000ffffffffffffffffffffffffffffffffffffffffffffffff  False       DRIVER         INTENDED_USER_EXIT    ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   10380
 2  03000000ffffffffffffffffffffffffffffffffffffffffffffffff  False       DRIVER         INTENDED_USER_EXIT    ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   50546
 3  04000000ffffffffffffffffffffffffffffffffffffffffffffffff  False       DRIVER         INTENDED_USER_EXIT    ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   63060
 4  05000000ffffffffffffffffffffffffffffffffffffffffffffffff  False       DRIVER         INTENDED_USER_EXIT    ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  105845
 5  050303c5763b95bdeb70f07527ca903409cf0ca832da9c104a78b7fc  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  171137
 6  06000000ffffffffffffffffffffffffffffffffffffffffffffffff  False       DRIVER         INTENDED_USER_EXIT    ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  110761
 7  07000000ffffffffffffffffffffffffffffffffffffffffffffffff  False       DRIVER         INTENDED_USER_EXIT    ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  125523
 8  08000000ffffffffffffffffffffffffffffffffffffffffffffffff  False       DRIVER         INTENDED_USER_EXIT    ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  152125
 9  09000000ffffffffffffffffffffffffffffffffffffffffffffffff  False       DRIVER         INTENDED_USER_EXIT    ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  159152
10  0a000000ffffffffffffffffffffffffffffffffffffffffffffffff  False       DRIVER         INTENDED_USER_EXIT    ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  170717
11  0b000000ffffffffffffffffffffffffffffffffffffffffffffffff  False       DRIVER         INTENDED_USER_EXIT    ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  212935
12  0b4643539a51385001e948dd42e482d85ec560d942bbdafafb0c3802  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   51021
13  0d959fabe28b5ff34b9f06d5679e4bc15c0543403cc89ac62ed07e0c  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  125933
14  0df7e9695742f0b119e6280973c5893d97f0ac9d435f8287de2f5a1f  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  106262
15  1441dae49f757bbd60e618d6f36d34382b6e00080a73e636739c62d7  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   10681
16  17bf0a6082e44a6d315a74ed78eb8db1305f6748e7ec03adbe2c42e3  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  125935
17  191181af2d2eedf6a5088eb3b93e3d3f95d6dca67e457c19c693f7e1  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  159579
18  1cfca9a1a56c0833fef120ec4627df7f5235dec1f9c5b0921cd29a62  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  159574
19  1fc7ad1f0629746ea608f62bef3ef02500a57ee93b2c44509cb4260f  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  171141
20  22d2f7529ae94ab08c9f30a5ceb98aa11d69ef7b0f1fe995697390e6  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   10862
21  22f384a38e18423f9db5d8ccd7a6e34b241d9f8203449d85e96a403c  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201    4901
22  232394bb95e7ed7db327887b9bb2bdd2ed0bb0009b4ad10f6f67d3d9  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  106160
23  27bd0c88c2dbed0542d888f1f9c46e44fb95f349eea5bd5b86a57bd7  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201    4823
24  2d6fd3cdd19b9fa83e1db4a4771b11b3618c7a97f7ba974d39eed453  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   50898
25  2f1cc319dc38ac14f669c68bd3a6ed9ae929988563b0f93d84280add  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   51017
26  31aabaef089ebe0decb7be606522fa8ca97231719c85840845119444  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   50828
27  336468b7a73ef62caf781a5aac2d4523e4e2068d9510aa1fdc6dba86  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201    4903
28  35b8d8041bb2d9a010ceb45d2860cdde4d33621ed327fbcca86976eb  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  111176
29  3c87c19d533054d8d7f62441088ed41a5f4ff3d5983104a4a68277d5  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  171139
30  45a617d329eb0a575ffe6417cd207e438a9bba6ca364b7c17315c884  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   11233
31  486180200aed55d2c0bc550c9b668da161df7908872d7be85457a9df  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  106260
32  49c5f28be6dac8022a1593acad03ae7946749f826937f0253c1ed2df  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  125770
33  4b256cfdc85474208d25b300cd8a09bd7c367f4ffcd2b51443542520  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  152372
34  5867ab3f47b5971b86fd84cf7560bf5aa84e5ce479647834ce211011  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  171041
35  5ccafb94cd6f74aa14906260816d28ec706c022bdca1f900315e2415  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   10771
36  5cecbde0b8702346e0e191fee3fe4b60469a602b7beda5d6ee382adb  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   10866
37  5d33ec496389cf279e1df63c417eb6054fa1f7ad4b8b2567d426e9a1  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  152445
38  64dd4019b7f4a4fbb5a3a48556765e796f37f12cc9853d52aea6d94a  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201    4905
39  7202441e4933646e1746e6c6180589a5da1b80f9870332ef5db09dfd  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  159392
40  7a8b51ae6b0fc18479f2195bc2ebd3405bbba80861b80fe2f980f74f  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  159577
41  7ba5988fd40c92672e03a03470764a279c44645c8f2a394b8adf3530  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  125937
42  7f68b0fe1c4751bd4ebbafefed4497fdd24312385da3f0307b88077d  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  106092
43  7ff8f318ef85c58e18712b1c366250d94a1d6669be3c43a8921ccb96  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  152540
44  884ebb571160d54202c43087e3cf0c748b83c01cdb9c3d9632768f16  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  159469
45  89b69d1e45f620cab10e74c0ca513e179ca8a03e13a695ae30934b53  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   63547
46  99f9532797cf1d6d28dac78b0d6c638249626abbfa37da090fc9cc6b  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  111178
47  9a7185d61694f63b589eadc9337d082df33a23bf8b81e3df93b6e81b  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  213206
48  a6b3d3d4ce28cbe637f4176b82f17704aca2159f458b5b152493bcc0  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   51019
49  a8d8611cca0d83dc7ca269f71d7741c3a74fee94cceb501c32a7ae4e  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  162161
50  ac1c9fb62927c1dc9061255c8e52854185c2086f2476fa27c3785e16  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  111077
51  ae32d0ea2fe6ea58aed29d277b86ae1c69064148e9d2439057b56759  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   63545
52  b6ead798fa7996a15973444707d088d2a2c85c45b2c7aef6e735f8f4  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  111174
53  bb830060d4686f7cd3afbf36f9ab5b2943afe9b8cb4ffc92760e2807  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  213380
54  bfce7780275c71dbb7bb8afc635638eb16e78521fef1b073230d1870  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  152544
55  ccfc0648ed26e95f4a016b152348eaf3dfc6f1e550a96cba46b0595c  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  170964
56  d776e114e3b736121609f26f92c316cde7d2ef57717716b9780d71ba  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201    4753
57  d8f0fb0d5c95b634dc6b66128b60398f950ff48cc4c2531ee375bc89  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  152542
58  dfce9023733b62c544758e39c12a6c1be5fe1dc0653e283da73b8cde  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  213382
59  e02435116c86102ef04811a31ecc05382a00c44ef5ee3a7e16749b47  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   63551
60  e3818eaa39feace0196884d458a6b5f97deb649cbf37f4fadecd6b3d  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  213384
61  e4924d722e921ae710dee23aa053426122c87ae504641d32d9fdd761  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  106264
62  e6467d88b1dd8d24bad4f77918b1426082272c547c6e288709502096  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  213280
63  e6e96c9b1f4387fb2baf83485ee20d69f3cc3bf8bf694cecc731ba59  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   63549
64  ede739f021bfd814fb9b1a94e09dc7e2bec7b92b302bce9bfdf64709  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   10864
65  f319fa52816bb927145e12fc9217dbc6dd8d47df7b73830ed5520f53  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  125839
66  fc8e589709bfd6f9e7a403c5e0d72398d0f4490e97e71fa066257f84  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201  111003
67  fdeac06922ebfdceb53d9113feee9c64a97d16a74174eb45965ff4bf  False       WORKER         INTENDED_SYSTEM_EXIT  ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8  10.0.25.201   63468

(base) ray@ip-10-0-25-201:~/default$ ray logs worker --pid 212935
--- Log has been truncated to last 1000 lines. Use `--tail` flag to toggle. Set to -1 for getting the entire file. ---

Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/scripts/scripts.py", line 2472, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/experimental/state/state_cli.py", line 1126, in log_worker
    _print_log(
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/experimental/state/state_cli.py", line 808, in _print_log
    for chunk in get_log(
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/experimental/state/api.py", line 1208, in get_log
    raise RayStateApiException(error_msg)
ray.experimental.state.exception.RayStateApiException: 0Closing HTTP stream due to internal server error.
Could not find a log file. Please make sure the given option exists in the cluster.

ode_id: ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8

ilename: None
        actor_id: None
        ask_id: None
        pid: 212935
        suffix: out

==========ALPHA, FEEDBACK NEEDED ===============
State Observability APIs is currently in Alpha. 
If you have any feedback, you could do so at either way as below:
    1. Report bugs/issues with details: https://forms.gle/gh77mwjEskjhN8G46
    2. Follow up in #ray-state-observability-dogfooding slack channel of Ray: https://tinyurl.com/2pm26m4a
==========================================================
```

### Versions / Dependencies

nightly

### Reproduction script

n/a

### Issue Severity

None

**Comment by scottsun94** [comment]
Unstale
