### ISSUE TITLE
[data] [streaming] backpressure memory usage tracking broken for some datasets

### ISSUE THREAD

**Issue by v4if** [ray-project/ray#33627]
### Description

With datasets streaming execution, when processing large-scale images, the processing speed of the upstream and downstream operators does not match. The size of the operator queue is not limited and will continue to grow. When the system memory is insufficient, it will be spilled to the disk, resulting in insufficient disk space.
In this execution mode, is it possible to set the size of the queue and support back pressure?

## Reproduction script
```python
import ray
from ray.data.read_api import read_datasource
from ray.data.datasource.datasource import Datasource, Reader, ReadTask
from typing import Any, Dict, List, Optional, Union
from ray.data.block import Block, BlockMetadata

import time
import numpy as np

assert (
    ray.__version__ >= "2.3.0"
), f"The version of ray must be greater than 2.3.0, the current version is {ray.__version__}"

ray.init()

ctx = ray.data.context.DatasetContext.get_current()
ctx.use_streaming_executor = True
ctx.execution_options.preserve_order = False


class SampleDatasourceReader(Reader):
    def __init__(self, sample_count):
        self.sample_count = sample_count

    def estimate_inmemory_data_size(self) -> Optional[int]:
        """Return an estimate of the in-memory data size, or None if unknown.

        Note that the in-memory data size may be larger than the on-disk data size.
        """
        return None

    def _read(self, idx) -> List[Block]:
        blocks = []
        block = [np.random.randn(3, 1024, 1024)]
        blocks.append(block)
        time.sleep(0.5)
        return blocks

    def get_read_tasks(self, parallelism: int) -> List[ReadTask]:
        read_tasks: List[ReadTask] = []

        for i in range(self.sample_count):
            metadata = BlockMetadata(
                num_rows=1,
                size_bytes=10,  # guess
                schema=None,
                input_files=None,
                exec_stats=None,
            )

            read_task = ReadTask(lambda idx=i: self._read(idx), metadata)
            read_tasks.append(read_task)

        return read_tasks


class SampleDatasource(Datasource):
    def create_reader(self, sample_count, **read_args) -> "Reader[T]":
        return SampleDatasourceReader(sample_count)


def read_sample(
    sample_count: int,
    parallelism: int = -1,
    ray_remote_args: Dict[str, Any] = None,
    **read_args,
):
    return read_datasource(
        SampleDatasource(),
        parallelism=parallelism,
        ray_remote_args=ray_remote_args,
        sample_count=sample_count,
        **read_args,
    )


class TestSlow:
    def __call__(self, df):
        time.sleep(10)
        return df


class TestFast:
    def __call__(self, df):
        time.sleep(0.1)
        return df


ds = read_sample(10000, 2)
print(ds)
pipe = ds.map_batches(
    TestFast,
    batch_size=1,
    num_cpus=0.1,
    compute=ray.data.ActorPoolStrategy(10, 10),
).map_batches(
    TestSlow,
    batch_size=1,
    num_cpus=0.5,
    compute=ray.data.ActorPoolStrategy(2, 2),
)
for batch in pipe.iter_batches(batch_size=1):
    ...
```

## Execution log

No space left on device

```text
2023-03-23 16:38:08,475 INFO worker.py:1550 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8266 
Dataset(num_blocks=10000, num_rows=10000, schema=<class 'numpy.ndarray'>)
2023-03-23 16:38:39,222 INFO streaming_executor.py:65 -- Executing DAG InputDataBuffer[Input] -> TaskPoolMapOperator[read] -> ActorPoolMapOperator[MapBatches(TestFast)] -> ActorPoolMapOperator[MapBatches(TestSlow)]
Resource usage vs limits: 8.0/8.0 CPU, 0.0/0.0 GPU, 0.0 MiB/512.0 MiB object_store_memory:   0%|                       | 0/1 [00:34<?, ?it/s(raylet) Spilled 2356 MiB, 10025 objects, write throughput 194 MiB/s. Set RAY_verbose_spill_logs=0 to disable this message.1:01:33,  2.68it/s]
Resource usage vs limits: 8.0/8.0 CPU, 0.0/0.0 GPU, 0.0 MiB/512.0 MiB object_store_memory:   0%|                       | 0/1 [00:53<?, ?it/s(raylet) Spilled 4420 MiB, 10111 objects, write throughput 217 MiB/s.                                     | 155/10000 [00:53<28:04,  5.85it/s]
Resource usage vs limits: 8.0/8.0 CPU, 0.0/0.0 GPU, 0.0 MiB/512.0 MiB object_store_memory:   0%|                       | 0/1 [01:09<?, ?it/s(raylet) Spilled 8236 MiB, 10270 objects, write throughput 260 MiB/s.                                     | 241/10000 [01:08<27:44,  5.86it/s]
Resource usage vs limits: 8.0/8.0 CPU, 0.0/0.0 GPU, 0.0 MiB/512.0 MiB object_store_memory:   0%|                       | 0/1 [01:45<?, ?it/s(raylet) Spilled 16612 MiB, 10619 objects, write throughput 298 MiB/s.                                    | 453/10000 [01:45<26:02,  6.11it/s]
Resource usage vs limits: 8.0/8.0 CPU, 0.0/0.0 GPU, 0.0 MiB/512.0 MiB object_store_memory:   0%|                       | 0/1 [02:52<?, ?it/s(raylet) Spilled 32812 MiB, 11294 objects, write throughput 317 MiB/s.                                    | 852/10000 [02:52<20:59,  7.26it/s]
Resource usage vs limits: 8.0/8.0 CPU, 0.0/0.0 GPU, 0.0 MiB/512.0 MiB object_store_memory:   0%|                       | 0/1 [02:58<?, ?it/s](raylet) [2023-03-23 16:41:37,639 E 8163 4074926] (raylet) file_system_monitor.cc:105: /tmp/ray/session_2023-03-23_16-38-02_026919_8133 is over 95% full, available space: 12532576256; capacity: 250685575168. Object creation will fail if spilling is required.[02:58<29:27,  5.16it/s]
Resource usage vs limits: 8.0/8.0 CPU, 0.0/0.0 GPU, 0.0 MiB/512.0 MiB object_store_memory:   0%|                       | 0/1 [03:08<?, ?it/s(raylet) [2023-03-23 16:41:47,645 E 8163 4074926] (raylet) file_system_monitor.cc:105: /tmp/ray/session_2023-03-23_16-38-02_026919_8133 is over 95% full, available space: 11353731072; capacity: 250685575168. Object creation will fail if spilling is required. [03:08<19:03,  7.92it/s]
Resource usage vs limits: 8.0/8.0 CPU, 0.0/0.0 GPU, 0.0 MiB/512.0 MiB object_store_memory:   0%|                       | 0/1 [03:18<?, ?it/s(raylet) [2023-03-23 16:41:57,689 E 8163 4074926] (raylet) file_system_monitor.cc:105: /tmp/ray/session_2023-03-23_16-38-02_026919_8133 is over 95% full, available space: 9104691200; capacity: 250685575168. Object creation will fail if spilling is required.0 [03:18<25:38,  5.85it/s]
Resource usage vs limits: 6.0/8.0 CPU, 0.0/0.0 GPU, 0.0 MiB/512.0 MiB object_store_memory:   0%|                       | 0/1 [03:28<?, ?it/s(raylet) [2023-03-23 16:42:07,768 E 8163 4074926] (raylet) file_system_monitor.cc:105: /tmp/ray/session_2023-03-23_16-38-02_026919_8133 is over 95% full, available space: 6550011904; capacity: 250685575168. Object creation will fail if spilling is required.0 [03:28<27:23,  5.44it/s]
Resource usage vs limits: 8.0/8.0 CPU, 0.0/0.0 GPU, 0.0 MiB/512.0 MiB object_store_memory:   0%|                       | 0/1 [03:36<?, ?it/s(raylet) [2023-03-23 16:42:17,818 E 8163 4074926] (raylet) file_system_monitor.cc:105: /tmp/ray/session_2023-03-23_16-38-02_026919_8133 is over 95% full, available space: 4248203264; capacity: 250685575168. Object creation will fail if spilling is required.0 [03:36<24:43,  6.00it/s]
2023-03-23 16:42:18,492 WARNING worker.py:1866 -- WARNING: 46 PYTHON worker processes have been started on node: 4615ec90952904b5c4914bc88c5990fc436b55199e1c7a0c676bbf95 with address: 127.0.0.1. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).
Resource usage vs limits: 8.0/8.0 CPU, 0.0/0.0 GPU, 0.0 MiB/512.0 MiB object_store_memory:   0%|                       | 0/1 [03:49<?, ?it/s(raylet) [2023-03-23 16:42:27,848 E 8163 4074926] (raylet) file_system_monitor.cc:105: /tmp/ray/session_2023-03-23_16-38-02_026919_8133 is over 95% full, available space: 3362476032; capacity: 250685575168. Object creation will fail if spilling is required.[03:49<1:16:43,  1.93it/s]
Resource usage vs limits: 8.0/8.0 CPU, 0.0/0.0 GPU, 0.0 MiB/512.0 MiB object_store_memory:   0%|                       | 0/1 [03:58<?, ?it/s(raylet) [2023-03-23 16:42:37,915 E 8163 4074926] (raylet) file_system_monitor.cc:105: /tmp/ray/session_2023-03-23_16-38-02_026919_8133 is over 95% full, available space: 3416354816; capacity: 250685575168. Object creation will fail if spilling is required.0 [03:58<36:53,  4.00it/s]
Resource usage vs limits: 8.0/8.0 CPU, 0.0/0.0 GPU, 0.0 MiB/512.0 MiB object_store_memory:   0%|                       | 0/1 [04:08<?, ?it/s(raylet) [2023-03-23 16:42:47,949 E 8163 4074926] (raylet) file_system_monitor.cc:105: /tmp/ray/session_2023-03-23_16-38-02_026919_8133 is over 95% full, available space: 2180833280; capacity: 250685575168. Object creation will fail if spilling is required.0 [04:08<43:02,  3.42it/s]
Resource usage vs limits: 8.0/8.0 CPU, 0.0/0.0 GPU, 0.0 MiB/512.0 MiB object_store_memory:   0%|                       | 0/1 [04:18<?, ?it/s(raylet) [2023-03-23 16:42:57,984 E 8163 4074926] (raylet) file_system_monitor.cc:105: /tmp/ray/session_2023-03-23_16-38-02_026919_8133 is over 95% full, available space: 1429213184; capacity: 250685575168. Object creation will fail if spilling is required.0 [04:18<34:09,  4.28it/s]
Resource usage vs limits: 8.0/8.0 CPU, 0.0/0.0 GPU, 0.0 MiB/512.0 MiB object_store_memory:   0%|                       | 0/1 [04:24<?, ?it/s2023-03-23 16:43:04,653ueWARNING worker.py:1866 -- Traceback (most recent call last):                    | 1258/10000 [04:24<30:10,  4.83it/s]
  File "python/ray/_raylet.pyx", line 1280, in ray._raylet.spill_objects_handler                        | 1258/10000 [04:24<26:55,  5.41it/s]
  File "python/ray/_raylet.pyx", line 1283, in ray._raylet.spill_objects_handler                       | 47/10000 [04:25<14:15:17,  5.16s/it]
  File "/Users/leyi/miniconda3/envs/python37/lib/python3.7/site-packages/ray/_private/external_storage.py", line 668, in spill_objects16s/it]
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/Users/leyi/miniconda3/envs/python37/lib/python3.7/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/Users/leyi/miniconda3/envs/python37/lib/python3.7/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
```

**Comment by amogkam** [comment]
Hey @v4if, what cluster configuration are you using?

**Comment by ericl** [comment]
>                 size_bytes=10,  # guess

This is likely the cause--- you need to provide accurate estimates in the datasource, or the executor cannot properly throttle the number of active tasks. One way of testing this is to swap out the custom datasource with `ray.data.range_tensor()`, which does return byte size estimates.

**Comment by v4if** [comment]
Testing on my local mac laptop.
Cpu core: 8
Mem: 16GB
Avail disk space: 47Gi

After changing the byte size estimates, the size of the queue still continue to grow.
```python
    def estimate_inmemory_data_size(self) -> Optional[int]:
        """Return an estimate of the in-memory data size, or None if unknown.

        Note that the in-memory data size may be larger than the on-disk data size.
        """

        element_size = 3 * 1024 * 1024
        return 8 * element_size
```
```python
                size_bytes=3*1024*1024*8,
```

The queue size of `MapBatches(TestSlow)` has grown to 1303, resulting in insufficient spilled disk space
```text
MapBatches(TestFast): 5 active, 0 queued, 10 actors:  14%|██████▏                                       | 1353/10000 [04:17<27:28,  5.25it/s]
MapBatches(TestSlow): 4 active, 1303 queued, 2 actors:   0%|▏                                          | 46/10000 [04:17<15:30:16,  5.61s/it]
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
```

What is the strategy of executor throttle the number of active tasks.  Or can I control the size of the MapBatches operator queue. Thanks.

cc @amogkam @ericl

**Comment by ericl** [comment]
Thanks! I can confirm the issue and will look into this. The issue seem to be related to tracking the size of the intermediate objects. It seems like the tracking is broken for certain block types.

For example, for tensor datasets it does work:

```
#ds = read_sample(10000, 2)
ds = ray.data.range_tensor(1000, shape=(3, 1024, 1024), parallelism=1000)
```

Gives you the following (nightly build):
```
2023-03-23 22:30:21,177	INFO streaming_executor.py:74 -- Executing DAG InputDataBuffer[Input] -> TaskPoolMapOperator[ReadRange] -> ActorPoolMapOperator[MapBatches(TestFast)] -> ActorPoolMapOperator[MapBatches(TestSlow)]
Resource usage vs limits: 2.0/8.0 CPU, 0.0/0.0 GPU, 1.55 GiB/1.53 GiB object_store_memory 0:   0%|                                                                                   | 0/1 [00:19<?, ?it/s]
ReadRange: 0 active, 932 queued 1:   7%|████████▊                                                                                                                        | 68/1000 [00:19<16:25,  1.06s/it]
MapBatches(TestFast): 0 active, 9 queued, 10 actors [59 locality hits, 0 misses] 2:   6%|████▋                                                                           | 59/1000 [00:19<00:24, 38.81it/s]
MapBatches(TestSlow): 8 active, 49 queued, 2 actors [10 locality hits, 0 misses] 3:   0%|▏                                                                              | 2/1000 [00:19<5:16:19, 19.02s/it]
output: 0 queued 4:   0%|▎                                                                                                                                              | 2/1000 [00:19<5:16:26, 19.02s/it]

```

**Comment by v4if** [comment]
Using range_tensor seems to work with backpressure memory, but there are also a lot of objects spilled to disk.
```python
ds = ray.data.range_tensor(1000, shape=(3, 1024, 1024), parallelism=1000)
```
```text
16G	/private/tmp/ray/session_latest/ray_spilled_objects
```
logs:
```text
2023-03-24 16:11:47,274 INFO streaming_executor.py:65 -- Executing DAG InputDataBuffer[Input] -> TaskPoolMapOperator[read] -> ActorPoolMapOperator[MapBatches(TestFast)] -> ActorPoolMapOperator[MapBatches(TestSlow)]
Resource usage vs limits: 2.0/8.0 CPU, 0.0/0.0 GPU, 2.13 GiB/512.0 MiB object_store_memory:   0%|                               | 0/1 [00:24<?, ?it/s(raylet) Spilled 2088 MiB, 93 objects, write throughput 142 MiB/s. Set RAY_verbose_spill_logs=0 to disable this message.1/1000 [00:18<09:25,  1.61it/s]
Resource usage vs limits: 2.0/8.0 CPU, 0.0/0.0 GPU, 2.11 GiB/512.0 MiB object_store_memory:   0%|                               | 0/1 [00:30<?, ?it/s(raylet) Spilled 4226 MiB, 1179 objects, write throughput 222 MiB/s.                                                 | 91/1000 [00:29<09:25,  1.61it/s]
Resource usage vs limits: 2.0/8.0 CPU, 0.0/0.0 GPU, 504.0 MiB/512.0 MiB object_store_memory:   0%|                              | 0/1 [02:52<?, ?it/s2023-03-24 16:14:39,833euWARNING worker.py:1866 -- WARNING: 34 PYTHON worker processes have been started on node: f7ceef973583bd07ad68705b6d656f337711bf90637563d636c2aaaf with address: 127.0.0.1. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).                                | 70/1000 [02:52<31:49,  2.05s/it]
Resource usage vs limits: 7.0/8.0 CPU, 0.0/0.0 GPU, 504.0 MiB/512.0 MiB object_store_memory:   0%|                              | 0/1 [02:58<?, ?it/s2023-03-24 16:14:46,108euWARNING worker.py:1866 -- WARNING: 44 PYTHON worker processes have been started on node: f7ceef973583bd07ad68705b6d656f337711bf90637563d636c2aaaf with address: 127.0.0.1. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).                                | 75/1000 [02:58<20:40,  1.34s/it]
Resource usage vs limits: 8.0/8.0 CPU, 0.0/0.0 GPU, 384.0 MiB/512.0 MiB object_store_memory:   0%|                              | 0/1 [04:18<?, ?it/s](raylet) Spilled 8594 MiB, 1361 objects, write throughput 254 MiB/s.                                               | 276/1000 [04:17<01:26,  8.37it/s]
Resource usage vs limits: 6.0/8.0 CPU, 0.0/0.0 GPU, 360.0 MiB/512.0 MiB object_store_memory:   0%|                              | 0/1 [04:36<?, ?it/s(raylet) Spilled 16394 MiB, 1686 objects, write throughput 316 MiB/s.███████▎                                       | 516/1000 [04:35<00:31, 15.40it/s]
Resource usage vs limits: 2.0/8.0 CPU, 0.0/0.0 GPU, 552.0 MiB/512.0 MiB object_store_memory:   0%|                              | 0/1 [05:10<?, ?it/s]
read: 0 active, 388 queued:  61%|██████████████████████████████████████████████████▏                               | 612/1000 [04:59<00:22, 17.15it/s]
MapBatches(TestFast): 0 active, 9 queued, 10 actors:  60%|██████████████████████████████████▎                      | 603/1000 [04:59<00:20, 19.53it/s]
MapBatches(TestSlow): 4 active, 399 queued, 2 actors:  20%|███████████▏                                            | 200/1000 [05:10<12:41,  1.05it/s]
output: 1 queued:  20%|██████████████████▍                                                                         | 200/1000 [05:10<12:42,  1.05it/s]
```

**There is still some confusion:**
1、What is the backpressure memory strategy and threshold? Throttling has a certain time lag, resulting in disk spilled. And there are some differences in the throttling of multiple runs.
2、Can provide a backpressure strategy based on the size of the queue? What are the considerations based on memory?

**Comment by ericl** [comment]
Hm, are you using the latest nightly build? When I ran it, I did see bounded memory usage (2GiB for my machine):

I monitored the memory usage with `while true; do ray memory --stats-only; done` in a separate terminal:

```
======== Object references status: 2023-03-24 14:49:59.035323 ========
--- Aggregate object store stats across all nodes ---
Plasma memory usage 24 MiB, 2 objects, 0.3% full, 0.3% needed
Objects consumed by Ray tasks: 0 MiB.

======== Object references status: 2023-03-24 14:50:01.232192 ========
--- Aggregate object store stats across all nodes ---
Plasma memory usage 97 MiB, 1007 objects, 1.23% full, 1.23% needed
Objects consumed by Ray tasks: 0 MiB.

======== Object references status: 2023-03-24 14:50:03.412154 ========
--- Aggregate object store stats across all nodes ---
Plasma memory usage 937 MiB, 1041 objects, 11.75% full, 11.75% needed
Objects consumed by Ray tasks: 216 MiB.

======== Object references status: 2023-03-24 14:50:04.797045 ========
--- Aggregate object store stats across all nodes ---
Plasma memory usage 2041 MiB, 1013 objects, 25.58% full, 25.58% needed
Objects consumed by Ray tasks: 744 MiB.

======== Object references status: 2023-03-24 14:50:05.873390 ========
--- Aggregate object store stats across all nodes ---
Plasma memory usage 2041 MiB, 1013 objects, 25.58% full, 25.58% needed
Objects consumed by Ray tasks: 744 MiB.
```

> 1、What is the backpressure memory strategy and threshold? Throttling has a certain time lag, resulting in disk spilled. And there are some differences in the throttling of multiple runs.

The current strategy is that we only schedule tasks on operators if wouldn't exceed the memory limit, and we prioritize scheduling operators that are falling behind. The memory limit is based on the usage of all downstream operators. For example, suppose you have a 3-operator DAG. The first operator is throttled if `sum(op1_usage, op2_usage, op3_usage)` (including queue memory usage) exceeds the limit. The second operator is throttled if `sum(op2_usage, op3_usage)` exceeds 2/3 of the limit, and so on.

> 2、Can provide a backpressure strategy based on the size of the queue? What are the considerations based on memory?

We currently limit based on the object store usage of the queue + in-flight task arguments size only, since this is assuming we can accurately measure the object store size of all objects queued (this really should be the case, I think there's a bug in your particular example).

**Comment by ericl** [comment]
Update: the root cause seems to be that the code above is returning a list of np.ndarrays, which is serialized as a "SimpleBlock" (Python serialization). It seems that `sys.getsizeof` doesn't work properly for numpy arrays, returning 64 as the size instead of the real size.

The following patch fixes:
```
@@ -118,7 +119,7 @@ class SimpleBlockAccessor(BlockAccessor):
         return self._items
 
     def size_bytes(self) -> int:
-        return sys.getsizeof(self._items)
+        return len(cloudpickle.dumps(self._items))
 
```

**Comment by v4if** [comment]
Using the latest nightly build, backpressure memory works with one parallelism, but it will still spilled to disk with multi parallelisms.

Run log:
```text
(task pid=1002, ip=172.17.0.107) 2023-03-28 14:52:11,506        INFO streaming_executor.py:83 -- Executing DAG InputDataBuffer[Input] -> TaskPoolMapOperator[ReadRange] -> ActorPoolMapOperator[MapBatches(TestFast)] -> ActorPoolMapOperator[MapBatches(TestSlow)]
(task pid=1007, ip=172.17.0.107) 2023-03-28 14:52:12,730        INFO streaming_executor.py:83 -- Executing DAG InputDataBuffer[Input] -> TaskPoolMapOperator[ReadRange] -> ActorPoolMapOperator[MapBatches(TestFast)] -> ActorPoolMapOperator[MapBatches(TestSlow)]
(task pid=1040, ip=172.17.0.107) 2023-03-28 14:52:13,011        INFO streaming_executor.py:83 -- Executing DAG InputDataBuffer[Input] -> TaskPoolMapOperator[ReadRange] -> ActorPoolMapOperator[MapBatches(TestFast)] -> ActorPoolMapOperator[MapBatches(TestSlow)]
(task pid=1041, ip=172.17.0.107) 2023-03-28 14:52:13,912        INFO streaming_executor.py:83 -- Executing DAG InputDataBuffer[Input] -> TaskPoolMapOperator[ReadRange] -> ActorPoolMapOperator[MapBatches(TestFast)] -> ActorPoolMapOperator[MapBatches(TestSlow)]
(task pid=1061, ip=172.17.0.107) 2023-03-28 14:52:13,977        INFO streaming_executor.py:83 -- Executing DAG InputDataBuffer[Input] -> TaskPoolMapOperator[ReadRange] -> ActorPoolMapOperator[MapBatches(TestFast)] -> ActorPoolMapOperator[MapBatches(TestSlow)]
(pid=1002, ip=172.17.0.107) Resource usage vs limits: 4.0/16.0 CPU, 0.0/0.0 GPU, 2.23 GiB/2.21 GiB object_store_memory 0:   0%|         | 0/1 [01:05<?, ?it/s^(pid=1002, ip=172.17.0.107) Resource usage vs limits: 2.0/16.0 CPU, 0.0/0.0 GPU, 2.23 GiB/2.21 GiB object_store_memory 0:   0%|         | 0/1 [02:05<?, ?it/s^(pid=1002, ip=172.17.0.107) Resource usage vs limits: 3.0/16.0 CPU, 0.0/0.0 GPU, 2.23 GiB/2.21 GiB object_store_memory 0:   0%|         | 0/1 [03:06<?, ?it/s^(pid=1002, ip=172.17.0.107) Resource usage vs limits: 3.0/16.0 CPU, 0.0/0.0 GPU, 2.23 GiB/2.21 GiB object_store_memory 0:   0%|         | 0/1 [04:06<?, ?it/s^(pid=1002, ip=172.17.0.107) Resource usage vs limits: 3.0/16.0 CPU, 0.0/0.0 GPU, 2.23 GiB/2.21 GiB object_store_memory 0:   0%|         | 0/1 [04:34<?, ?it/s]
(pid=1002, ip=172.17.0.107) ReadRange: 1 active, 687 queued 1:  31%|█████████████████▏                                     | 312/1000 [04:34<13:55,  1.21s/it]
(pid=1002, ip=172.17.0.107) MapBatches(TestFast): 2 active, 31 queued, 10 actors [281 locality hits, 0 misses] 2:  28%|█   | 279/1000 [04:34<14:25,  1.20s/it]
(pid=1002, ip=172.17.0.107) MapBatches(TestSlow): 8 active, 53 queued, 2 actors [226 locality hits, 0 misses] 3:  22%|█    | 218/1000 [04:33<20:17,  1.56s/it]
(pid=1002, ip=172.17.0.107) output: 0 queued 4:  22%|███████████████▎                                                      | 218/1000 [04:33<20:17,  1.56s/it]
(pid=1007, ip=172.17.0.107) Resource usage vs limits: 3.0/16.0 CPU, 0.0/0.0 GPU, 2.23 GiB/2.21 GiB object_store_memory 0:   0%|         | 0/1 [04:32<?, ?it/s]
(pid=1007, ip=172.17.0.107) ReadRange: 1 active, 699 queued 1:  30%|████████████████▌                                      | 300/1000 [04:32<11:39,  1.00it/s]
(pid=1007, ip=172.17.0.107) MapBatches(TestFast): 1 active, 31 queued, 10 actors [269 locality hits, 0 misses] 2:  27%|█   | 268/1000 [04:33<12:10,  1.00it/s]
(pid=1007, ip=172.17.0.107) MapBatches(TestSlow): 8 active, 54 queued, 2 actors [214 locality hits, 0 misses] 3:  21%|█    | 206/1000 [04:33<14:51,  1.12s/it]
(pid=1007, ip=172.17.0.107) output: 0 queued 4:  21%|██████████████▍                                                       | 206/1000 [04:31<14:46,  1.12s/it]
(pid=1040, ip=172.17.0.107) Resource usage vs limits: 4.0/16.0 CPU, 0.0/0.0 GPU, 2.23 GiB/2.21 GiB object_store_memory 0:   0%|         | 0/1 [04:32<?, ?it/s]
(pid=1040, ip=172.17.0.107) ReadRange: 2 active, 691 queued 1:  31%|████████████████▉                                      | 307/1000 [04:32<11:38,  1.01s/it]
(pid=1040, ip=172.17.0.107) MapBatches(TestFast): 2 active, 30 queued, 10 actors [277 locality hits, 0 misses] 2:  28%|█   | 275/1000 [04:32<12:48,  1.06s/it]
(pid=1040, ip=172.17.0.107) MapBatches(TestSlow): 8 active, 53 queued, 2 actors [222 locality hits, 0 misses] 3:  21%|█    | 214/1000 [04:32<13:27,  1.03s/it]
(pid=1040, ip=172.17.0.107) output: 0 queued 4:  21%|██████████████▉                                                       | 214/1000 [04:31<13:21,  1.02s/it]
(pid=1041, ip=172.17.0.107) Resource usage vs limits: 4.0/16.0 CPU, 0.0/0.0 GPU, 2.23 GiB/2.21 GiB object_store_memory 0:   0%|         | 0/1 [04:32<?, ?it/s]
(pid=1041, ip=172.17.0.107) ReadRange: 2 active, 699 queued 1:  30%|████████████████▍                                      | 299/1000 [04:32<17:06,  1.46s/it]
(pid=1041, ip=172.17.0.107) MapBatches(TestFast): 3 active, 30 queued, 10 actors [269 locality hits, 0 misses] 2:  27%|█   | 266/1000 [04:32<19:36,  1.60s/it]
(pid=1041, ip=172.17.0.107) MapBatches(TestSlow): 8 active, 52 queued, 2 actors [214 locality hits, 0 misses] 3:  21%|█    | 206/1000 [04:31<17:11,  1.30s/it]
(pid=1041, ip=172.17.0.107) output: 0 queued 4:  21%|██████████████▍                                                       | 206/1000 [04:31<17:24,  1.32s/it]
(pid=1061, ip=172.17.0.107) Resource usage vs limits: 5.0/16.0 CPU, 0.0/0.0 GPU, 2.2 GiB/2.21 GiB object_store_memory 0:   0%|          | 0/1 [04:32<?, ?it/s]
(pid=1061, ip=172.17.0.107) ReadRange: 4 active, 682 queued 1:  31%|█████████████████▎                                     | 314/1000 [04:32<12:07,  1.06s/it]
(pid=1061, ip=172.17.0.107) MapBatches(TestFast): 4 active, 28 queued, 10 actors [286 locality hits, 0 misses] 2:  28%|█▏  | 282/1000 [04:32<13:02,  1.09s/it]
(pid=1061, ip=172.17.0.107) MapBatches(TestSlow): 8 active, 51 queued, 2 actors [231 locality hits, 0 misses] 3:  22%|█    | 223/1000 [04:32<12:35,  1.03it/s]
(pid=1061, ip=172.17.0.107) output: 0 queued 4:  22%|███████████████▌                                                      | 223/1000 [04:32<12:35,  1.03it/s]
```

Memory usage:
```text
======== Object references status: 2023-03-28 14:57:58.667944 ========
--- Aggregate object store stats across all nodes ---
Plasma memory usage 3770 MiB, 244 objects, 41.66% full, 1.07% needed
Spilled 394001 MiB, 31330 objects, avg write throughput 255 MiB/s
Restored 294504 MiB, 19809 objects, avg read throughput 218 MiB/s
Objects consumed by Ray tasks: 328350 MiB.

======== Object references status: 2023-03-28 14:58:00.429521 ========
--- Aggregate object store stats across all nodes ---
Plasma memory usage 4202 MiB, 271 objects, 46.44% full, 2.13% needed
Spilled 394481 MiB, 31350 objects, avg write throughput 255 MiB/s
Restored 294960 MiB, 19837 objects, avg read throughput 218 MiB/s
Objects consumed by Ray tasks: 328662 MiB.

======== Object references status: 2023-03-28 14:58:02.158822 ========
--- Aggregate object store stats across all nodes ---
Plasma memory usage 3650 MiB, 234 objects, 40.34% full, 1.34% needed
Spilled 394841 MiB, 31365 objects, avg write throughput 255 MiB/s
Restored 295320 MiB, 19859 objects, avg read throughput 218 MiB/s
Objects consumed by Ray tasks: 328975 MiB.

======== Object references status: 2023-03-28 14:58:04.371206 ========
--- Aggregate object store stats across all nodes ---
Plasma memory usage 4082 MiB, 261 objects, 45.11% full, 1.34% needed
Spilled 395441 MiB, 31390 objects, avg write throughput 255 MiB/s
Restored 295800 MiB, 19888 objects, avg read throughput 218 MiB/s
Objects consumed by Ray tasks: 329359 MiB.

======== Object references status: 2023-03-28 14:58:06.328510 ========
--- Aggregate object store stats across all nodes ---
Plasma memory usage 3626 MiB, 230 objects, 40.07% full, 1.07% needed
Spilled 395921 MiB, 31410 objects, avg write throughput 255 MiB/s
Restored 296232 MiB, 19916 objects, avg read throughput 218 MiB/s
Objects consumed by Ray tasks: 329791 MiB.

======== Object references status: 2023-03-28 14:58:08.429327 ========
--- Aggregate object store stats across all nodes ---
Plasma memory usage 4010 MiB, 254 objects, 44.32% full, 2.4% needed
Spilled 396401 MiB, 31430 objects, avg write throughput 255 MiB/s
Restored 296592 MiB, 19939 objects, avg read throughput 218 MiB/s
Objects consumed by Ray tasks: 330127 MiB.
```

Reproduction script:
```python
import ray
import time

assert (
    ray.__version__ >= "2.3.0"
), f"The version of ray must be greater than 2.3.0, the current version is {ray.__version__}"

ray.init()

ctx = ray.data.context.DatasetContext.get_current()
ctx.use_streaming_executor = True
ctx.execution_options.preserve_order = False


class TestSlow:
    def __call__(self, df):
        time.sleep(2)
        return df


class TestFast:
    def __call__(self, df):
        time.sleep(0.1)
        return df


@ray.remote
def task(ds):
    pipe = ds.map_batches(
        TestFast,
        batch_size=1,
        num_cpus=0.1,
        compute=ray.data.ActorPoolStrategy(10, 10),
    ).map_batches(
        TestSlow,
        batch_size=1,
        num_cpus=0.5,
        compute=ray.data.ActorPoolStrategy(2, 2),
    )

    for batch in pipe.iter_batches(batch_size=1):
        ...


N = 5
ds = ray.data.range_tensor(1000, shape=(3, 1024, 1024), parallelism=1000)
results = [task.remote(ds) for i in range(N)]

ray.wait(results)
```

1、Whether spilled to disk is expected with multi parallelisms?
2、My usage scenario is large-scale image semantic segmentation, I want to split the image into multi chunks for parallel processing. Is it the correct processing pattern?

**Comment by ericl** [comment]
> 1、Whether spilled to disk is expected with multi parallelism?

Each stream's memory limit is set independently, so if there are multiple you need to manually set the memory limit (ctx.execution_options.resource_limits.object_store_memory) to avoid oversubscribing the cluster. I'd recommend setting the sum of the memory limits to less than 25% of the cluster memory to start and see how that goes.

> 2、My usage scenario is large-scale image semantic segmentation, I want to split the image into multi chunks for parallel processing. Is it the correct processing pattern?

I'd recommend using one big streaming job to run all the workloads, instead of many independent streams. Or, you can run the streams one by one if it's not possible to combine them together.
