### ISSUE TITLE
[Core] specify dashboard-agent-listen-port in ray2.3 lead to ray job submit failed to get logs

### ISSUE THREAD

**Issue by Basasuya** [ray-project/ray#33664]
### What happened + What you expected to happen

The problem happens when the dashboard-agent-listen-port is given but job_head.py just use the default dashboard-agent port(52365), which would leads to failed to get ray job logs
```
2023-03-24 14:08:40,690 ERROR optional_utils.py:97 -- Handle GET /api/jobs/{job_or_submission_id}/logs/tail failed.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/root/miniconda3/lib/python3.7/asyncio/base_events.py", line 962, in create_connection
    raise exceptions[0]
  File "/root/miniconda3/lib/python3.7/asyncio/base_events.py", line 949, in create_connection
    await self.sock_connect(sock, address)
  File "/root/miniconda3/lib/python3.7/asyncio/selector_events.py", line 473, in sock_connect
    return await fut
  File "/root/miniconda3/lib/python3.7/asyncio/selector_events.py", line 503, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('10.15.54.87', 52365)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/ray/dashboard/optional_utils.py", line 95, in _handler_route
    return await handler(bind_info.instance, req)
  File "/root/miniconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/job_head.py", line 520, in tail_job_logs
    async for lines in job_agent_client.tail_job_logs(job.submission_id):
  File "/root/miniconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/job_head.py", line 124, in tail_job_logs
    f"{self._agent_address}/api/job_agent/jobs/{job_id}/logs/tail"
  File "/root/miniconda3/lib/python3.7/site-packages/aiohttp/client.py", line 789, in _ws_connect
    proxy_headers=proxy_headers,
  File "/root/miniconda3/lib/python3.7/site-packages/aiohttp/client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "/root/miniconda3/lib/python3.7/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/root/miniconda3/lib/python3.7/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/root/miniconda3/lib/python3.7/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/root/miniconda3/lib/python3.7/site-packages/aiohttp/connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "/root/miniconda3/lib/python3.7/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc`
```

when a job is submitted, job_head.py:choose_agent would choose a dashboard-agent from nodes to new `JobAgentSubmissionClient`, the agent port is correct in this func.
But the job_head.py:get_job_logs use the `job.driver_agent_http_address` to new a `JobAgentSubmissionClient` if this node_id client is not existed. driver_agent_http_address is incorrect because this value is given by default-worker.py, which is the default value.

### Versions / Dependencies

pip install ray==2.3

### Reproduction script

This problem has some probability to reproduce. which would occur if the job is submitted by worker node in job_head.py:choose_agent.

// master node
ray start --head --block --disable-usage-stats --node-ip-address={MASTER_IP} --block --dashboard-host=''
--dashboard-agent-listen-port=23003
// worker node
ray start --address={MASTER_IP}:6379 --block  --node-ip-address={WORKER_IP} --dashboard-agent-listen-port=23001
// your laptop
export RAY_ADDRESS=http://{NODE_IP}:8265
ray job submit --runtime-env-json='{"working_dir": "./"}' -- python3 counter.py
ray job logs raysubmit_PgPQ2FFFLCa98i79

ray job submit would not return the running result
ray job logs would return error similar to the above description

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by MissiontoMars** [comment]
@rkooo567 Could you help analyze this problem? Thanks.
