### ISSUE TITLE
Core: nightly builds for macos only include an x86 _raylet.so even though they claim to be universal

### ISSUE THREAD

**Issue by cosnicolaou** [ray-project/ray#33720]
### What happened + What you expected to happen

Following the instructions at [at](https://docs.ray.io/en/latest/ray-contribute/development.html#building-ray) for building ray for python I ray into the following problem:

```
$ python python/ray/setup-dev.py
Traceback (most recent call last):
  File "/Users/cnicolaou/Dropbox/dev/github.com/ray-project/ray/python/ray/setup-dev.py", line 23, in <module>
    import ray
  File "/Users/cnicolaou/mambaforge/envs/ray-dev/lib/python3.10/site-packages/ray/__init__.py", line 101, in <module>
    _configure_system()
  File "/Users/cnicolaou/mambaforge/envs/ray-dev/lib/python3.10/site-packages/ray/__init__.py", line 98, in _configure_system
    CDLL(so_path, ctypes.RTLD_GLOBAL)
  File "/Users/cnicolaou/mambaforge/envs/ray-dev/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/cnicolaou/mambaforge/envs/ray-dev/lib/python3.10/site-packages/ray/_raylet.so, 0x000A): tried: '/Users/cnicolaou/mambaforge/envs/ray-dev/lib/python3.10/site-packages/ray/_raylet.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/cnicolaou/mambaforge/envs/ray-dev/lib/python3.10/site-packages/ray/_raylet.so' (no such file), '/Users/cnicolaou/mambaforge/envs/ray-dev/lib/python3.10/site-packages/ray/_raylet.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```
The installed _raylet.so is for x86 only: ```
file /Users/cnicolaou/mambaforge/envs/ray-dev/lib/python3.10/site-packages/ray/_raylet.so
/Users/cnicolaou/mambaforge/envs/ray-dev/lib/python3.10/site-packages/ray/_raylet.so: Mach-O 64-bit dynamically linked shared library x86_64
```

### Versions / Dependencies

Nightly build ray-3.0.0.dev0-cp310-cp310-macosx_10_15_universal2.whl

### Reproduction script

cat > env.yml <<!
name: ray-dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - grpcio=1.43.0 # for m1 support
  - pip
  - pip:
    - https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp310-cp310-macosx_10_15_universal2.whl
!
conda env create -f env.yml
conda activate ray-dev
python python/ray/setup-dev.py

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by clarng** [comment]
For now we support that for release : https://docs.ray.io/en/master/ray-overview/installation.html#apple-silicon-support

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
