### ISSUE TITLE
[RLLib] [RaySystemError]use torch 2.0 torch.compile error ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception

### ISSUE THREAD

**Issue by xiezhipeng-git** [ray-project/ray#33743]
### What happened + What you expected to happen

use pytorch 2.0 torch.compoile(model) ray raise error by ray put or get
error info 
ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception

ray init success cpus= 32 0.031
(raylet) /home/xzpwsl2/.local/lib/python3.10/site-packages/ray/dashboard/agent.py:51: DeprecationWarning: There is no current event loop
(raylet)   aiogrpc.init_grpc_aio()
(Worker pid=23701) /home/xzpwsl2/.local/lib/python3.10/site-packages/torch/fx/interpreter.py:122: TqdmMonitorWarning: tqdm:disabling monitor support (monitor_interval = 0) due to:
(Worker pid=23701) can't start new thread
(Worker pid=23701)   pbar = tqdm(total=len(self.module.graph.nodes),
(Worker pid=23704) Exception in initializer:
(Worker pid=23704) Traceback (most recent call last):
(Worker pid=23704)   File "/usr/lib/python3.10/concurrent/futures/process.py", line 233, in _process_worker
(Worker pid=23704)     initializer(*initargs)
(Worker pid=23704)   File "/home/xzpwsl2/.local/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 620, in init
(Worker pid=23704)     _watchdog_thread.start()
(Worker pid=23704)   File "/usr/lib/python3.10/threading.py", line 935, in start
(Worker pid=23704)     _start_new_thread(self._bootstrap, ())
(Worker pid=23704) RuntimeError: can't start new thread
(Worker pid=23802) Exception in initializer:
(Worker pid=23802) Traceback (most recent call last):
(Worker pid=23802)   File "/usr/lib/python3.10/concurrent/futures/process.py", line 233, in _process_worker
(Worker pid=23802)     initializer(*initargs)
(Worker pid=23802)   File "/home/xzpwsl2/.local/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 620, in init
(Worker pid=23802)     _watchdog_thread.start()
(Worker pid=23802)   File "/usr/lib/python3.10/threading.py", line 935, in start
(Worker pid=23802)     _start_new_thread(self._bootstrap, ())
(Worker pid=23802) RuntimeError: can't start new thread
(Worker pid=23810) Exception in initializer:
(Worker pid=23810) Traceback (most recent call last):
(Worker pid=23810)   File "/usr/lib/python3.10/concurrent/futures/process.py", line 233, in _process_worker
(Worker pid=23810)     initializer(*initargs)
(Worker pid=23810)   File "/home/xzpwsl2/.local/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 620, in init
(Worker pid=23810)     _watchdog_thread.start()
(Worker pid=23810)   File "/usr/lib/python3.10/threading.py", line 935, in start
(Worker pid=23810)     _start_new_thread(self._bootstrap, ())
(Worker pid=23810) RuntimeError: can't start new thread
2023-03-27 23:43:01,472 ERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::WorkerCaller.start() (pid=27551, ip=172.28.246.219, repr=<rl_ray_ppo.WorkerCaller object at 0x7f6109032680>)
  File "/home/xzpwsl2/my/work/rlFrame/rl_frame/rayTest/dl-template/rl_ray_ppo.py", line 229, in start
    ray.get(self.worker.rollout.remote())
ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception
traceback: Traceback (most recent call last):
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/exceptions.py", line 46, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
TypeError: BackendCompilerFailed.__init__() missing 1 required positional argument: 'inner_exception'

The above exception was the direct cause of the following exception:

ray::WorkerCaller.start() (pid=27551, ip=172.28.246.219, repr=<rl_ray_ppo.WorkerCaller object at 0x7f6109032680>)
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/exceptions.py", line 40, in from_bytes
    return RayError.from_ray_exception(ray_exception)
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/exceptions.py", line 49, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception
2023-03-27 23:43:01,478 ERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::WorkerCaller.start() (pid=27581, ip=172.28.246.219, repr=<rl_ray_ppo.WorkerCaller object at 0x7f25d460a740>)
  File "/home/xzpwsl2/my/work/rlFrame/rl_frame/rayTest/dl-template/rl_ray_ppo.py", line 229, in start
    ray.get(self.worker.rollout.remote())
ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception
traceback: Traceback (most recent call last):
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/exceptions.py", line 46, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
TypeError: BackendCompilerFailed.__init__() missing 1 required positional argument: 'inner_exception'

The above exception was the direct cause of the following exception:

ray::WorkerCaller.start() (pid=27581, ip=172.28.246.219, repr=<rl_ray_ppo.WorkerCaller object at 0x7f25d460a740>)
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/exceptions.py", line 40, in from_bytes
    return RayError.from_ray_exception(ray_exception)
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/exceptions.py", line 49, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception
2023-03-27 23:43:01,482 ERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::WorkerCaller.start() (pid=27578, ip=172.28.246.219, repr=<rl_ray_ppo.WorkerCaller object at 0x7fd88818e6e0>)
  File "/home/xzpwsl2/my/work/rlFrame/rl_frame/rayTest/dl-template/rl_ray_ppo.py", line 229, in start
    ray.get(self.worker.rollout.remote())
ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception
traceback: Traceback (most recent call last):
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/exceptions.py", line 46, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
TypeError: BackendCompilerFailed.__init__() missing 1 required positional argument: 'inner_exception'

The above exception was the direct cause of the following exception:

ray::WorkerCaller.start() (pid=27578, ip=172.28.246.219, repr=<rl_ray_ppo.WorkerCaller object at 0x7fd88818e6e0>)
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/exceptions.py", line 40, in from_bytes
    return RayError.from_ray_exception(ray_exception)
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/exceptions.py", line 49, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception
2023-03-27 23:43:01,492 ERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::WorkerCaller.start() (pid=27554, ip=172.28.246.219, repr=<rl_ray_ppo.WorkerCaller object at 0x7f565c9f6710>)
  File "/home/xzpwsl2/my/work/rlFrame/rl_frame/rayTest/dl-template/rl_ray_ppo.py", line 229, in start
    ray.get(self.worker.rollout.remote())
ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception
traceback: Traceback (most recent call last):
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/exceptions.py", line 46, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
TypeError: BackendCompilerFailed.__init__() missing 1 required positional argument: 'inner_exception'

###if use ray put I found it error by torch ConfigModuleInstance [torch/_dynamo/config_utils.py](https://github.com/pytorch/pytorch/blob/3e6978172e86a97dc4c248406d2b2509a837299f/torch/_dynamo/config_utils.py)

Traceback (most recent call last):
  File "/home/xzpwsl2/my/work/rlFrame/rl_frame/jorldy/run_mode.py", line 343, in sync_distributed_train
    distributed_manager = DistributedManager(
  File "/home/xzpwsl2/my/work/rlFrame/rl_frame/jorldy/manager/distributed_manager.py", line 39, in __init__
    Env, env_config, agent = map(ray.put, [Env, dict(env_config), agent])
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2452, in put
    object_ref = worker.put_object(value, owner_address=serialize_owner_address)
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 613, in put_object
    serialized_value = self.get_serialization_context().serialize(value)
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/_private/serialization.py", line 450, in serialize
    return self._serialize_to_msgpack(value)
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/_private/serialization.py", line 428, in _serialize_to_msgpack
    pickle5_serialized_object = self._serialize_to_pickle5(
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/_private/serialization.py", line 390, in _serialize_to_pickle5
    raise e
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/_private/serialization.py", line 385, in _serialize_to_pickle5
    inband = pickle.dumps(
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 88, in dumps
    cp.dump(obj)
  File "/home/xzpwsl2/.local/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 733, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'ConfigModuleInstance' object

### Versions / Dependencies

ray 2.3.1
torch 2.0
python 3.10.6
wsl linux

### Reproduction script

git clone  https://github.com/chaihahaha/dl-template/blob/main/rl_ray_ppo.py
then add 
self.actor = torch.compile(self.actor)
after 
self.actor = ActorModel(self.ctx_size, self.d_obs, self.d_act, self.low, self.high)

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by Rohan138** [comment]
Currently, RLlib does not support torch 2.0 or `torch.compile`; we are working on this and will make it available in a few releases.

**Comment by Cobular** [comment]
Bumping this again - has it seen any major progress yet?

**Comment by rbavery** [comment]
I'm also curious about this, should the issue be re-opened? I think this also blocks AOTInductor compiled models from being loaded into Ray, see https://discuss.ray.io/t/why-is-my-model-inference-class-not-serializable/14553

**Comment by DefTruth** [comment]
still have this error in torch 2.5.1
