### ISSUE TITLE
[CI] Windows flaky? test failure due to bazel version

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#33764]
BK: https://buildkite.com/ray-project/oss-ci-build-pr/builds/16434#018724a5-9553-40d6-9d34-24242743952a

```
ERROR: Traceback (most recent call last):
--
  | File "C:/install/ray/WORKSPACE", line 25, column 15, in <toplevel>
  | versions.check(minimum_bazel_version = "5.4.0")
  | File "C:/tmp/4lhdprva/external/bazel_skylib/lib/versions.bzl", line 105, column 13, in _check_bazel_version
  | fail("Current Bazel version is {}; expected at least {}".format(
  | Error in fail: Current Bazel version is 4.2.1; expected at least 5.4.0
```

**Comment by hora-anyscale** [comment]
@cadedaniel - can you please assign a priority and remove the triage label?

**Comment by cadedaniel** [comment]
@hora-anyscale this is for devprod to triage.

**Comment by aslonnie** [comment]
old pipeline deprecated. new pipeline has been reworked.
