### ISSUE TITLE
[Serve] Failed to fetch URI gcs://plugin-0.0.0-63635-py3-none-any.whl from GCS.

### ISSUE THREAD

**Issue by saswatac** [ray-project/ray#33799]
### What happened + What you expected to happen

We have a ray serve application deployed on a ray cluster created by Kuberay (RayCluster crd). The cluster has a head node pod and multiple worker pods. The serve replica actor is deployed on the worker pods.

If a worker pod is deleted, ray serves automatically deploys the serve deployment on another worker pod, as expected. 

However, if the ray serve deployment has some dependent wheels specified as py_modules in the runtime_env, then the redeployment fails with this error about `Failed to fetch URI gcs://plugin-0.0.0-63635-py3-none-any.whl` . The error is logged in the serve controller logs.

I expect the re-deployment to be created successfully in case of worker pod deletion even when there are wheels specified in the runtime envs. Since the head node pod is not affected, the gcs should continue to work. In fact, on the head node pod, I checked that the python modules from the wheels were available in the path `/tmp/ray/session_latest/runtime_resources/py_modules_files` .

### Versions / Dependencies

ray==2.0.0

python 3.8

ubuntu 20.04.5 LTS (Focal Fossa)

### Reproduction script

todo

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by hora-anyscale** [comment]
@sihanwang41 - please assign priority and remove triage label

**Comment by sihanwang41** [comment]
Hi @saswatac , do you mind providing a repro script? Looks like there is runtime env issue with serve.

**Comment by saswatac** [comment]
Its a bit hard to give the exact steps. I can describe the setup and provide some snippets - 

* Create a RayCluster in kubernetes. i have the num-cpus: '0' for head node so that no workload runs on it.
* Deploy a serve model as follows - 

```python
import os
import ray

class MyModel:
  def predict(self):
    pass


runtime_env = {"py_modules":  ["/path/to/test.whl"]}
# Set hostname to ray head svc
os.environ["RAY_ADDRESS"] = f"ray://{hostname}:10001"
ray.init(
      namespace="serve",
      address="auto",
      runtime_env=runtime_env,
      ignore_reinit_error=True,
  )

serve_model_class = serve.deployment(MyModel)
serve_model_class.options(
    route_prefix="/",
    max_concurrent_queries=3,
    name="test",
).deploy()
```

* Model is deployed, and verify replica actors in dashboard
* Now delete the cluster worker pod with kubectl delete pod
* The replica actor now fails to start up repeatedly. The stack trace in the serve controller actor is similar to the following - 

```
OSError: Failed to fetch URI gcs://rwdi_plugin-3.5.2-19625-py3-none-any.whl from GCS.5677    

  raise IOError(f"Failed to fetch URI {pkg_uri} from GCS.")5676  File "/usr/local/lib/python3.8/dist-packages/ray/_private/runtime_env/packaging.py", line 595, in download_and_unpack_package5675    wheel_file = await download_and_unpack_package(5674  File "/usr/local/lib/python3.8/dist-packages/ray/_private/runtime_env/py_modules.py", line 160, in _download_and_install_wheel5673    module_dir = await self._download_and_install_wheel(uri=uri, logger=logger)5672  File "/usr/local/lib/python3.8/dist-packages/ray/_private/runtime_env/py_modules.py", line 198, in create5671    size_bytes = await plugin.create(uri, runtime_env, context, logger=logger)5670  File "/usr/local/lib/python3.8/dist-packages/ray/_private/runtime_env/plugin.py", line 251, in create_for_plugin_if_needed5669    await create_for_plugin_if_needed(5668  File "/usr/local/lib/python3.8/dist-packages/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 296, in _setup_runtime_env5667    return fut.result()5666  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for5665    runtime_env_context = await asyncio.wait_for(5664  File "/usr/local/lib/python3.8/dist-packages/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 341, in _create_runtime_env_with_retry5663Traceback (most recent call last):5662Could not create the actor because its associated runtime env failed to be created.5661ray.exceptions.RuntimeEnvSetupError: Failed to setup runtime environment.5660    raise value5659  File "/usr/local/lib/python3.8/dist-packages/ray/_private/worker.py", line 2277, in get5658    return func(*args, **kwargs)5657  File "/usr/local/lib/python3.8/dist-packages/ray/_private/client_mode_hook.py", line 105, in wrapper5656    deployment_config, version = ray.get(self._ready_obj_ref)5655  File "/usr/local/lib/python3.8/dist-packages/ray/serve/_private/deployment_state.py", line 416, in check_ready5654Traceback (most recent call last):5653ERROR 2023-05-03 06:19:27,095 controller 219 deployment_state.py:425 - Exception in deployment 'cladding-api-repro-baseline'5652INFO 2023-05-03 06:19:26,987 controller 219 deployment_state.py:1232 - Adding 1 replicas to deployment 'cladding-api-repro-baseline'.
```

**Comment by sihanwang41** [comment]
Hi @saswatac , do you see any issue in the kube apiserve log at that time?

**Comment by saswatac** [comment]
This seems a bit related to https://github.com/ray-project/ray/issues/23423 . 

Following https://github.com/ray-project/ray/pull/24719 , I tried to set env `RAY_RUNTIME_ENV_TEMPORARY_REFERENCE_EXPIRATION_S` to a high value, but it didn't seem to help.

**Comment by architkulkarni** [comment]
Thanks for the additional details @saswatac, we will try to reproduce it and debug it on our side.  The env var you mentioned is only for the deletion of files that have been downloaded onto the nodes, it's not for the files uploaded to the GCS.  I'll update the docs to make this clearer.

The files in the GCS are garbage collected using reference counting. This part is managed by [runtime_env_manager.cc](https://github.com/ray-project/ray/blob/master/src/ray/common/runtime_env_manager.cc). There are some debug logs which can be enabled by setting `export RAY_BACKEND_LOG_LEVEL=debug` before starting Ray.

Here's how I think the reference count should look:

+1 on ray.init()
+1 when ray serve controller actor is created
+1 when the replica is created
-1 when the script exits (the "ray client job" exits)
-1 when the worker pod dies

So it should never hit zero and never be deleted.

**Comment by architkulkarni** [comment]
@saswatac I debugged with @sihanwang41 and we have a candidate explanation.   Your repro script as written doesn't work because `.deploy()` won't work unless the Serve controller is running.  So we have to separately call `serve.start(detached=True)` in another process first.

Since `serve.start()` is called without a runtime environment, we actually don't get the "+1 when ray serve controller actor is created", so the reference count actually does go to zero during the period where the replica doesn't exist.

- As a workaround, you should be able to set `RAY_RUNTIME_ENV_TEMPORARY_REFERENCE_EXPIRATION_S` to a high value, but note that this should be set before `ray start` is called. That might be why it didn't work earlier.
- Are you able to pass the runtime env in when the Serve controller is started? That will also circumvent the bug, because the Serve controller will always hold a reference to the URI.

**Comment by architkulkarni** [comment]
We were able to validate the above hypothesis and reproduce the error.  Since `serve.deploy()` is a deprecated, it is unlikely we'll be able to prioritize a fix. 

The recommended usage in this case would be to use a [Remote URI](https://docs.ray.io/en/latest/ray-core/handling-dependencies.html#remote-uris) for your `py_modules` `.whl` file instead of a local file.

The workarounds above should also work, but are not recommended.

**Comment by saswatac** [comment]
Thanks a lot @architkulkarni for debugging. Sorry about the repro script - indeed it assumes serve is already running in  detached mode in the cluster I am connecting to.

* RAY_RUNTIME_ENV_TEMPORARY_REFERENCE_EXPIRATION_S should be getting set before ray start is called. I am setting it as an environment variable in the RayCluster spec of the kuberay operator - so it should ideally be getting picked up when kuberay starts ray.
* I want to keep the flexibility of having different runtime envs for different serve deployments, so passing during the init of the serve controller is not an option.
* I will look into the bind API 
* Reg. Remote URI - is there any plan to add support for file paths from a shared volume mounted on all nodes of the ray cluster)?

**Comment by saswatac** [comment]
I think for wheels, it is not pinning the runtime env uri. Here the package is uploaded https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/py_modules.py#L115 . This function https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/packaging.py#L481 does not do the pinning, but it happens in upload_package_if_needed .
