### ISSUE TITLE
Docker container not requiring root

### ISSUE THREAD

**Issue by nilsjohanbjorck** [ray-project/ray#3393]
Dear Ray-team,

It seems like running ray in the docker container described in (https://ray.readthedocs.io/en/latest/install-on-docker.html) requires root access. In some cases, for example when using the singularity container service, one does not have root access. Would it be possible to provide docker-containers runnable with only user-access?

**Comment by robertnishihara** [comment]
It should be possible to build the relevant docker images by running

```
cd ray
./build-docker.sh
```

without root access.

**Comment by nilsjohanbjorck** [comment]
I'm able to build the container. However, the ray folder in ``` /ray/python/ray/core/generated ``` is only available for the root-user

```
root@f50211b3a8ff:/ray/python/ray/core/generated# ls -al
total 132
drwxrwxr-x 1 root root 4096 Nov 21 04:50 .
drwxrwxr-x 1 root root 4096 Nov 20 22:47 ..
-rw-r--r-- 1 root root 2187 Nov 21 04:50 ActorTableData.py
-rw-r--r-- 1 root root 1595 Nov 21 04:50 Arg.py
-rw-r--r-- 1 root root  606 Nov 21 04:50 ClassTableData.py
-rw-r--r-- 1 root root 5332 Nov 21 04:50 ClientTableData.py
-rw-r--r-- 1 root root  612 Nov 21 04:50 ConfigTableData.py
-rw-r--r-- 1 root root  642 Nov 21 04:50 CustomSerializerData.py
-rw-r--r-- 1 root root 1321 Nov 21 04:50 DriverTableData.py
-rw-r--r-- 1 root root 2068 Nov 21 04:50 ErrorTableData.py
-rw-r--r-- 1 root root 1698 Nov 21 04:50 FunctionTableData.py
-rw-r--r-- 1 root root 1695 Nov 21 04:50 GcsTableEntry.py
-rw-r--r-- 1 root root 1618 Nov 21 04:50 HeartbeatBatchTableData.py
-rw-r--r-- 1 root root 7071 Nov 21 04:50 HeartbeatTableData.py
-rw-r--r-- 1 root root  150 Nov 21 04:50 Language.py
-rw-r--r-- 1 root root 2046 Nov 21 04:50 ObjectTableData.py
-rw-r--r-- 1 root root 2033 Nov 21 04:50 ProfileEvent.py
-rw-r--r-- 1 root root 2763 Nov 21 04:50 ProfileTableData.py
-rw-r--r-- 1 root root 1347 Nov 21 04:50 RayResource.py
-rw-r--r-- 1 root root 1277 Nov 21 04:50 ResourcePair.py
-rw-r--r-- 1 root root  247 Nov 21 04:50 SchedulingState.py
-rw-r--r-- 1 root root  365 Nov 21 04:50 TablePrefix.py
-rw-r--r-- 1 root root  305 Nov 21 04:50 TablePubsub.py
-rw-r--r-- 1 root root 9358 Nov 21 04:50 TaskInfo.py
-rw-r--r-- 1 root root 1675 Nov 21 04:50 TaskLeaseData.py
-rw-r--r-- 1 root root 1461 Nov 21 04:50 TaskReconstructionData.py
-rw-r--r-- 1 root root 2846 Nov 21 04:50 TaskTableData.py
-rw-r--r-- 1 root root 1831 Nov 21 04:50 TaskTableTestAndUpdate.py
-rw-rw-r-- 1 root root    0 Nov 20 22:47 __init__.py
drwxr-x--- 3 root root 4096 Nov 21 04:50 ray
```

I've tried to manually add user permission to the ray folder and the /opt folder via ```chmod -R 755``` but still run into the following permission error:

```
Singularity lolcow.simg:~/rl_docker> python ray/python/ray/rllib/train.py --run DQN --env CartPole-v0

Traceback (most recent call last):
  File "ray/python/ray/rllib/train.py", line 12, in <module>
    from ray.tune.config_parser import make_parser, resources_to_json
  File "/ray/python/ray/tune/__init__.py", line 6, in <module>
    from ray.tune.tune import run_experiments
  File "/ray/python/ray/tune/tune.py", line 9, in <module>
    from ray.tune.suggest import BasicVariantGenerator
  File "/ray/python/ray/tune/suggest/__init__.py", line 2, in <module>
    from ray.tune.suggest.basic_variant import BasicVariantGenerator
  File "/ray/python/ray/tune/suggest/basic_variant.py", line 9, in <module>
    from ray.tune.config_parser import make_parser, create_trial_from_spec
  File "/ray/python/ray/tune/config_parser.py", line 14, in <module>
    from ray.tune.trial import Resources, Trial
  File "/ray/python/ray/tune/trial.py", line 15, in <module>
    from ray.tune.logger import pretty_print, UnifiedLogger
  File "/ray/python/ray/tune/logger.py", line 19, in <module>
    import tensorflow as tf
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 59, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/opt/conda/lib/python2.7/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3086, in <module>
    @_call_aside
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3099, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in _build_master
    ws = cls()
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in __init__
    self.add_entry(entry)
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in add_entry
    for dist in find_distributions(entry, True):
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1962, in find_on_path
    for dist in factory(fullpath):
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2032, in distributions_from_metadata
    root, entry, metadata, precedence=DEVELOP_DIST,
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2471, in from_location
    py_version=py_version, platform=platform, **kw
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2833, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2435, in _version_from_file
    line = next(iter(version_lines), '')
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2625, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1808, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1794, in get_metadata
    with io.open(self.path, encoding='utf-8', errors="replace") as f:
IOError: [Errno 13] Permission denied: '/opt/conda/lib/python2.7/site-packages/.wh.h5py-2.7.1-py2.7.egg-info'

```

**Comment by richardliaw** [comment]
How are you generating this docker container? If you're using `./build-docker.sh`, what happens when you do something like:
```
docker run --rm --shm-size=10G --memory=10G [DOCKER CONTAINER ID] \
    python /ray/python/ray/tune/examples/async_hyperband_example.py
```
?

**Comment by richardliaw** [comment]
Oops, sorry I misread your comment - I didn't realize you were using a container service. 

I think the instructions you have there are for building from source in a Docker container. If you don't need to do this, you can do something like this in a Docker file:


```
FROM ray-project/base-deps
RUN conda env create -n ray
RUN conda activate ray && pip install -U ray
```

This should create a docker container that has everything accessible without requiring root access.

(I actually haven't tried this out but this is the main idea).

Let me know if this helps...
