### ISSUE TITLE
[Core/Data] Segfault with batch inference using concurrent actors

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#33982]
### What happened + What you expected to happen

The below code fails with 

```
(ReadParquet->MapBatches(preprocess) pid=14184)   warnings.warn( [repeated 11x across cluster]                                                              
(MapWorker(MapBatches(Actor)) pid=13986) [2023-03-31 15:29:21,352 E 13986 14159] logging.cc:361:     @     0x7f8495ede420  (unknown)  (unknown)             
(MapWorker(MapBatches(Actor)) pid=13986) Fatal Python error: Segmentation fault                                                                             
(MapWorker(MapBatches(Actor)) pid=13986)                                                                                                                    
(MapWorker(MapBatches(Actor)) pid=13986) Stack (most recent call first):                                                                                    
(MapWorker(MapBatches(Actor)) pid=13986)   File "predict.py", line 46 in __call__
(MapWorker(MapBatches(Actor)) pid=13986)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/legacy_compat.py", line 280 in fn
(MapWorker(MapBatches(Actor)) pid=13986)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/planner/map_batches.py", line 59 in process_next_batch
(MapWorker(MapBatches(Actor)) pid=13986)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/planner/map_batches.py", line 98 in fn
(MapWorker(MapBatches(Actor)) pid=13986)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/legacy_compat.py", line 292 in do_map
(MapWorker(MapBatches(Actor)) pid=13986)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 374 in _map_task
(MapWorker(MapBatches(Actor)) pid=13986)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/operators/actor_pool_map_operator.py", line 313 in submit
Resource usage vs limits: 0.0/48.0 CPU, 1.0/4.0 GPU, 7.96 GiB/12.9 GiB object_store_memory 0:   0%|                                   | 0/1 [00:27<?, ?it/s2023-03-31 15:29:21,895s(WARNING worker.py:1973 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff3b9d7910678b0b8168fbf23002000000 Worker ID: 5d4108590488b3c014a561f160cfc9c5e25158ecfdeec226e79a8043 Node ID: 4b239f2336bf09b03564039891853312b894effdeb2d25c86566c136 Worker IP address: 10.0.30.250 Worker port: 10026 Worker PID: 13986 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
                                                                                                                                                           Traceback (most recent call last):                                                                                                                           
  File "predict.py", line 52, in <module>                                                                                                                   
    for _ in ds.iter_batches(batch_size=None, batch_format="pyarrow"):                                                                                      
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/dataset_iterator.py", line 175, in iter_batches
    yield from iter_batches(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 179, in iter_batches
    next_batch = next(async_batch_iter)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 268, in make_async_gen
    raise next_item
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 249, in execute_computation
    for item in fn(thread_safe_generator):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 170, in _async_iter_batches
    yield from extract_data_from_batch(batch_iter)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 193, in extract_data_from_batch
    for batch in batch_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 307, in restore_original_order
    for batch in batch_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 268, in make_async_gen
    raise next_item
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 249, in execute_computation
    for item in fn(thread_safe_generator):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 221, in threadpool_computations
    yield from formatted_batch_iter
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 167, in format_batches
    for batch in block_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 229, in __next__
    return next(self.it)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 126, in blocks_to_batches
    for block in block_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 63, in resolve_block_refs
    for block_ref in block_ref_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 286, in prefetch_batches_locally
    sliding_window.append(next(block_ref_iter))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 229, in __next__
    return next(self.it)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/legacy_compat.py", line 50, in execute_to_legacy_block_iterator
    for bundle in bundle_iter:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/interfaces.py", line 465, in __next__
    return self.get_next()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 112, in get_next
    raise item
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 159, in run
    while self._scheduling_loop_step(self._topology) and not self._shutdown:
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 207, in _scheduling_loop_step
    process_completed_tasks(topology)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor_state.py", line 303, in process_completed_tasks
    op.notify_work_completed(ref)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/operators/actor_pool_map_operator.py", line 184, in notify_work_completed
    task.output = self._map_ref_to_ref_bundle(ref)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 316, in _map_ref_to_ref_bundle
    all_refs = list(ray.get(ref))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/worker.py", line 2510, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
        class_name: _MapWorker
        actor_id: 3b9d7910678b0b8168fbf23002000000
        pid: 13986
        namespace: b5e06bde-b373-4e1a-9e81-0d262ad06903
        ip: 10.0.30.250
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
```

### Versions / Dependencies

this patch of ray data: https://github.com/amogkam/ray/tree/thread-safe-actor-predictor

### Reproduction script

```python
import ray
from torchvision.models import resnet50, ResNet50_Weights
import torch
import time
import os
import threading
from torchvision import transforms

from ray.data import ActorPoolStrategy

BATCH_SIZE = 1000

os.environ["RAY_DATASET_NEW_EXECUTION_BACKEND"] = "1"
os.environ["RAY_DATASET_USE_STREAMING_EXECUTOR"] = "1"
ctx = ray.data.context.DatasetContext.get_current()
ray.data.context.DatasetContext.get_current().use_streaming_executor = True

ds = ray.data.read_parquet("s3://air-example-data-2/10G-image-data-synthetic-raw-parquet/")

def preprocess(image_batch):
    preprocess = transforms.Compose(
        [
            transforms.Resize(256),
            transforms.CenterCrop(224),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        ]
    )
    torch_tensor = torch.Tensor(image_batch["image"].transpose(0, 3, 1, 2))
    preprocessed_images = preprocess(torch_tensor).numpy()
    return {"image": preprocessed_images}

model = resnet50(weights=ResNet50_Weights.DEFAULT)
model_ref = ray.put(model)

class Actor:
    def __init__(self, model):
        print("Called init")
        self.model = ray.get(model)
        self.model.eval()
        self.model.to("cuda")
        self.lock = threading.Lock()

    def __call__(self, batch):
        with self.lock:
            with torch.inference_mode():
                output = self.model(torch.as_tensor(batch["image"], device="cuda"))
        return output.cpu().numpy()

start_time = time.time()
ds = ds.map_batches(preprocess, batch_format="numpy")
ds = ds.map_batches(Actor, batch_size=BATCH_SIZE, compute=ActorPoolStrategy(min_size=1, max_size=1), num_gpus=1, batch_format="numpy", fn_constructor_kwargs={"model": model_ref}, max_concurrency=2)
for _ in ds.iter_batches(batch_size=None, batch_format="pyarrow"):
    pass
end_time = time.time()

print("Total time: ", end_time-start_time)
print("Throughput (img/sec): ", (16232)/(end_time-start_time))
```

https://console.anyscale-staging.com/o/anyscale-internal/workspaces/expwrk_bv29stqpui4q5acyea9ufw7vgg/ses_miuf8zf43nwgkyjedf8zd7365f?command-history-section=head_start_up_log

Requires this patch of Ray Datasets: https://github.com/amogkam/ray/tree/thread-safe-actor-predictor

### Issue Severity

None

**Comment by amogkam** [comment]
Deprioritizing as we have found a workaround

**Comment by zhe-thoughts** [comment]
@amogkam What is the workaround? Thanks

**Comment by amogkam** [comment]
Running all the GPU code in a separate thread rather than using a lock.

```python
class Actor:
    def __init__(self, model):
        print("Called init")
        self.model = ray.get(model)
        self.model.eval()
        self.model.to("cuda")
        self.executor = concurrent.futures.ThreadPoolExecutor(max_workers=1)

    def inference(self, batch):
        with torch.inference_mode():
            output = self.model(torch.as_tensor(batch["image"], device="cuda"))
            output = output.cpu().numpy()
            return output

    def __call__(self, batch):
        future = self.executor.submit(self.inference, batch)
        return future.result()
```

**Comment by scv119** [comment]
Yeah. Debugged with @amogkam yesterday and we found a workaround. For the root cause, we believe it's either ray core thread has concurrency bugs, or pytorch is not designed to run in multiple thread, even if lock is used. At the moment we believe the latter is more likely.

**Comment by rkooo567** [comment]
@amogkam if you increase the `max_workers` to something like 5, does it work? If so, it is a Ray bug. Otherwise, I think it could be that pytorch GPU inference doesn't work well with multi threads?

**Comment by rkooo567** [comment]
(increase max workers and do 5 inference concurrently)

**Comment by rkooo567** [comment]
Is this low priority to fix?
