### ISSUE TITLE
[Core] Odd error propagation of GCS connection errors

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#34035]
### What happened + What you expected to happen

When I run the `ray/tests/test_ray_shutdown.py::test_driver_dead` test on linux on current master (say on https://github.com/ray-project/ray/pull/33936, one of the worker logs has an odd error message), even thought it passes:

```
2023-04-03 19:42:14,259 ERROR utils.py:231 -- Failed to publish error job_id: "\377\377\377\377"
type: "version_mismatch"
error_message: "Traceback (most recent call last):\n  File \"/home/pcmoritz/ray/python/ray/_private/worker.py\", line 2091, in connect\n    node.check_version_info()\n  File \"/home/pcmoritz/ray/python/ray/_private/node.py\", line 344, in check_version_info\n    cluster_metadata = ray_usage_lib.get_cluster_metadata(self.get_gcs_client())\n  File \"/home/pcmoritz/ray/python/ray/_private/usage/usage_lib.py\", line 703, in get_cluster_metadata\n    namespace=ray_constants.KV_NAMESPACE_CLUSTER,\n  File \"/home/pcmoritz/ray/python/ray/_private/gcs_utils.py\", line 198, in wrapper\n    return f(self, *args, **kwargs)\n  File \"/home/pcmoritz/ray/python/ray/_private/gcs_utils.py\", line 290, in internal_kv_get\n    reply = self._kv_stub.InternalKVGet(req, timeout=timeout)\n  File \"/home/pcmoritz/anaconda3/lib/python3.7/site-packages/grpc/_channel.py\", line 946, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n  File \"/home/pcmoritz/anaconda3/lib/python3.7/site-packages/grpc/_channel.py\", line 849, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses\"\n\tdebug_error_string = \"{\"created\":\"@1680576133.259440215\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3134,\"referenced_errors\":[{\"created\":\"@1680576133.259439717\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n>\n"
timestamp: 1680576133.2607403
Traceback (most recent call last):
  File "/home/pcmoritz/ray/python/ray/_private/worker.py", line 2091, in connect
    node.check_version_info()
  File "/home/pcmoritz/ray/python/ray/_private/node.py", line 344, in check_version_info
    cluster_metadata = ray_usage_lib.get_cluster_metadata(self.get_gcs_client())
  File "/home/pcmoritz/ray/python/ray/_private/usage/usage_lib.py", line 703, in get_cluster_metadata
    namespace=ray_constants.KV_NAMESPACE_CLUSTER,
  File "/home/pcmoritz/ray/python/ray/_private/gcs_utils.py", line 198, in wrapper
    return f(self, *args, **kwargs)
  File "/home/pcmoritz/ray/python/ray/_private/gcs_utils.py", line 290, in internal_kv_get
    reply = self._kv_stub.InternalKVGet(req, timeout=timeout)
  File "/home/pcmoritz/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/pcmoritz/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.UNAVAILABLE
details = "failed to connect to all addresses"
debug_error_string = "{"created":"@1680576133.259440215","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1680576133.259439717","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
```

The fact that an RPC error is shipped as a `version_mismatch` error (which I believe is reserved for Python / Ray version mismatches) tells us that something funky is going on here.

### Versions / Dependencies

Ray master
Python 3.7.6
Ubuntu

### Reproduction script

python -m pytest ray/tests/test_ray_shutdown.py::test_driver_dead

### Issue Severity

Low: It annoys or frustrates me.

**Comment by bchalk101** [comment]
Hey - I believe that I am getting this same issue. Been seeing this printout when running a training job on a Ray cluster.

```
(raylet, ip=10.250.174.232) Failed to publish error: Traceback (most recent call last):
(raylet, ip=10.250.174.232)   File "/usr/local/lib/python3.8/site-packages/ray/_private/worker.py", line 2101, in connect
(raylet, ip=10.250.174.232)     node.check_version_info()
(raylet, ip=10.250.174.232)   File "/usr/local/lib/python3.8/site-packages/ray/_private/node.py", line 339, in check_version_info
(raylet, ip=10.250.174.232)     cluster_metadata = ray_usage_lib.get_cluster_metadata(self.get_gcs_client())
(raylet, ip=10.250.174.232)   File "/usr/local/lib/python3.8/site-packages/ray/_private/usage/usage_lib.py", line 711, in get_cluster_metadata
(raylet, ip=10.250.174.232)     gcs_client.internal_kv_get(
(raylet, ip=10.250.174.232)   File "python/ray/_raylet.pyx", line 2198, in ray._raylet._auto_reconnect.wrapper
(raylet, ip=10.250.174.232)   File "python/ray/_raylet.pyx", line 2186, in ray._raylet._auto_reconnect.wrapper
(raylet, ip=10.250.174.232)   File "python/ray/_raylet.pyx", line 2251, in ray._raylet.GcsClient.internal_kv_get
(raylet, ip=10.250.174.232)   File "python/ray/_raylet.pyx", line 466, in ray._raylet.check_status
(raylet, ip=10.250.174.232) ray.exceptions.RpcError: failed to connect to all addresses
(raylet, ip=10.250.174.232)  [type version_mismatch]
```

I am using Ray nightly.
I have not noticed that it has been affecting the job running on the cluster but not 100% sure.

I've attached the gcs_server.out.
[gcs_server.out.txt](https://github.com/ray-project/ray/files/11715071/gcs_server.out.txt)
