### ISSUE TITLE
[autoscaler] Issue with escaping symbols in commands.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#3407]
When I run the autoscaler with

```
head_start_ray_commands:
    - ray stop
    - ulimit -n 65536; ray start --head --num-redis-shards=5 --redis-port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml --resources={"Custom":1}
```

I see the error

```
Role not specified for head node, using arn:aws:iam::339530224232:instance-profile/ray-autoscaler-v1
KeyName not specified for nodes, using ray-autoscaler_us-west-2
SubnetIds not specified for head node, using [('subnet-4645f631', 'us-west-2a')]
SubnetId not specified for workers, using [('subnet-4645f631', 'us-west-2a')]
SecurityGroupIds not specified for head node, using ray-autoscaler-stress-testing
SecurityGroupIds not specified for workers, using ray-autoscaler-stress-testing
Updating files on head node...
NodeUpdater: Updating i-03728bdf7b1fc0ac6 to ec1020bc7cb95cdb615732a9f05f78b8c0bb223e, logging to (console)
NodeUpdater: Waiting for IP of i-03728bdf7b1fc0ac6...
NodeUpdater: Waiting for SSH to i-03728bdf7b1fc0ac6...
NodeUpdater: Syncing /Users/rnishihara/.ssh/ray-autoscaler_us-west-2.pem to ~/ray_bootstrap_key.pem...
building file list ... done

sent 108 bytes  received 20 bytes  256.00 bytes/sec
total size is 1670  speedup is 13.05
NodeUpdater: Syncing /var/folders/95/3vf038bd0tx3gskyfm1ljb6c0000gn/T/ray-bootstrap-14idlwwg to ~/ray_bootstrap_config.yaml...
building file list ... done
ray-bootstrap-14idlwwg

sent 430 bytes  received 60 bytes  980.00 bytes/sec
total size is 1955  speedup is 3.99
NodeUpdater: running 

	ray stop

 on 54.201.232.76...
NodeUpdater: running 

	ulimit -n 65536; ray start --head --num-redis-shards=5 --redis-port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml --resources={"Custom":1}

 on 54.201.232.76...
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/scripts/scripts.py", line 217, in start
    resources = json.loads(resources)
  File "/home/ubuntu/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/anaconda3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/ray", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/scripts/scripts.py", line 691, in main
    return cli()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/scripts/scripts.py", line 219, in start
    raise Exception("Unable to parse the --resources argument using "
Exception: Unable to parse the --resources argument using json.loads. Try using a format like

    --resources='{"CustomResource1": 3, "CustomReseource2": 2}'
NodeUpdater: Error updating (Exit Status 1) 

	ssh -o ConnectTimeout=120s -o StrictHostKeyChecking=no -i /Users/rnishihara/.ssh/ray-autoscaler_us-west-2.pem ubuntu@54.201.232.76 bash --login -c 'set -i || true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && ulimit -n 65536; ray start --head --num-redis-shards=5 --redis-port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml --resources={"Custom":1}'

See (console) for remote logs.
Process NodeUpdaterProcess-1:
Traceback (most recent call last):
  File "/Users/rnishihara/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/rnishihara/ray_scratch/ray/python/ray/autoscaler/updater.py", line 104, in run
    raise e
  File "/Users/rnishihara/ray_scratch/ray/python/ray/autoscaler/updater.py", line 89, in run
    self.do_update()
  File "/Users/rnishihara/ray_scratch/ray/python/ray/autoscaler/updater.py", line 176, in do_update
    self.ssh_cmd(cmd, verbose=True)
  File "/Users/rnishihara/ray_scratch/ray/python/ray/autoscaler/updater.py", line 244, in ssh_cmd
    stderr=redirect or self.stderr)
  File "/Users/rnishihara/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh', '-o', 'ConnectTimeout=120s', '-o', 'StrictHostKeyChecking=no', '-i', '/Users/rnishihara/.ssh/ray-autoscaler_us-west-2.pem', 'ubuntu@54.201.232.76', 'bash --login -c \'set -i || true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && ulimit -n 65536; ray start --head --num-redis-shards=5 --redis-port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml --resources={"Custom":1}\'']' returned non-zero exit status 1.
Updating 54.201.232.76 failed
```

**Comment by ericl** [comment]
I think this is just a case of writing invalid YAML (yaml is terrible) -- consider putting the entire thing in single quotes like:

    - 'ulimit -n 65536; ray start --head --num-redis-shards=5 --redis-port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml --resources={"Custom":1}'

**Comment by hexamax** [comment]
I think this is might be a problem with the locale. If I export LC_ALL=C.UTF-8 and LANG=C.UTF-8 to the bashrc file during setup, everything runs smooth.
