### ISSUE TITLE
[Ray: Cluster] GPUs not correctly detected on all cluster nodes

### ISSUE THREAD

**Issue by arndt-k** [ray-project/ray#34095]
### What happened + What you expected to happen

I am trying to do distributed HPO on a Slurm cluster but ray does not detect the GPUs correctly. I have a head node with only CPUs that is only supposed to run the schduler, and X identical workers nodes with 4 GPUs each, but ray only detects the full 4 on a single node and one GPU on all the others.
My code completes trials on all the detected GPUs concurrently, the number of detected GPUs is just too small.
see also:  https://stackoverflow.com/questions/75937360/ray-cluster-gpu-detection

### Versions / Dependencies

python 3.10.4
ray 2.3.1

### Reproduction script

On the head-node:  
```
ray start --head --temp-dir /tmp/UID/ray/ --node-ip-address=10.13.22.34 --port=6374 --block --dashboard-port 3232 --dashboard-host 0.0.0.0 --num-cpus 2 &
```
script for slurm worker nodes:  
```
#!/bin/bash
sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=dagan_tune
#SBATCH --partition=booster
#SBATCH --nodes=$1
#SBATCH --exclusive
#SBATCH --tasks-per-node=1
#SBATCH --mem=400G
#SBATCH -A icon-a-ml
# #SBATCH --gres=gpu:4
#SBATCH -t 04:00:00
#SBATCH -o /p/scratch/icon-a-ml/kaps1/sbatch/%j.%x.%N_o
# Getting the node names
nodes=\$(scontrol show hostnames "\${SLURM_JOB_NODELIST}")
nodes_array=(\${nodes})
num_workers=\$((\$SLURM_JOB_NUM_NODES - 1))
echo \${num_workers}
for ((i = 0; i <= \${num_workers}; i++)); do
        node_i=\${nodes_array[\${i}]}
        echo "Starting WORKER \${i} at \${node_i}"
        srun --gres=gpu:4 --nodes=1 --ntasks=1 -w "\${node_i}" ray start --address 10.13.22.34:6374 --block &

        sleep 5
done
sleep infinity
exit 0
EOT
```
and the relevant parts of the tuning script that I am running on the head node:
```
ray.init(address="10.13.22.34:6374")
res = cluster_resources()
num_gpu=int(res["GPU"])
tuner = Tuner(tune.with_resources(
                trainable=fun_to_tune,
                resources = tune.PlacementGroupFactory([{"CPU": 0, "GPU": 1}])),
                param_space = parameters,
                run_config = RunConfig(name, verbose=3,
                                        local_dir= os.path.join(os.environ["SCR"],"ray_results"),
                                        failure_config=FailureConfig(fail_fast=True)),
                tune_config = TuneConfig(metric = "mean_JSD_impr",mode = "max",
                                            num_samples = -1, time_budget_s = 3600*4,
                                            max_concurrent_trials=num_gpu))
            
analysis = tuner.fit()
```
printing `ray.nodes()` and `ray.cluster_resources()` gives:  
[{'NodeID': '3b793f590f23b9a3f8eb4da86f870a2c6a20967ea1ea1093945fb2d9', 'Alive': True, 'NodeManagerAddress': '10.13.31.131', 'NodeManagerHostname': 'jwb0801.juwels', 'NodeManagerPort': 44655, 'ObjectManagerPort': 40891, 'ObjectStore
SocketName': '/tmp/ray/session_2023-04-05_09-43-27_453188_1518/sockets/plasma_store', 'RayletSocketName': '/tmp/ray/session_2023-04-05_09-43-27_453188_1518/sockets/raylet', 'MetricsExportPort': 43462, 'NodeName': '10.13.31.131', 'al
ive': True, 'Resources': {'CPU': 96.0, 'memory': 359211870618.0, 'GPU': 4.0, 'node:10.13.31.131': 1.0, 'object_store_memory': 153947944550.0, 'accelerator_type:A100': 1.0}}, {'NodeID': '5f803a7dd410074ea9d3fb3058b3ab3044011c54536c78
08bd9a947c', 'Alive': True, 'NodeManagerAddress': '10.13.22.34', 'NodeManagerHostname': 'jwlogin24.juwels', 'NodeManagerPort': 34927, 'ObjectManagerPort': 41163, 'ObjectStoreSocketName': '/tmp/UID/ray/session_2023-04-05_09-43-27_4
53188_1518/sockets/plasma_store', 'RayletSocketName': '/tmp/UID/ray/session_2023-04-05_09-43-27_453188_1518/sockets/raylet', 'MetricsExportPort': 60382, 'NodeName': '10.13.22.34', 'alive': True, 'Resources': {'memory': 21657799987
2.0, 'CPU': 2.0, 'node:10.13.22.34': 1.0, 'object_store_memory': 97104857088.0}}, {'NodeID': 'cf76300b5a3d269db3f859ab1b3f87ce03d8ebd344a37bd7421c2dd0', 'Alive': True, 'NodeManagerAddress': '10.13.31.137', 'NodeManagerHostname': 'jw
b0807.juwels', 'NodeManagerPort': 34425, 'ObjectManagerPort': 34533, 'ObjectStoreSocketName': '/tmp/ray/session_2023-04-05_09-43-27_453188_1518/sockets/plasma_store', 'RayletSocketName': '/tmp/ray/session_2023-04-05_09-43-27_453188_
1518/sockets/raylet', 'MetricsExportPort': 62643, 'NodeName': '10.13.31.137', 'alive': True, 'Resources': {'accelerator_type:A100': 1.0, 'object_store_memory': 154205725900.0, 'CPU': 96.0, 'GPU': 1.0, 'memory': 359813360436.0, 'node
:10.13.31.137': 1.0}}]
{'CPU': 194.0, 'GPU': 5.0, 'accelerator_type:A100': 2.0, 'memory': 935603230926.0, 'object_store_memory': 405258527538.0, 'node:10.13.31.131': 1.0, 'node:10.13.22.34': 1.0, 'node:10.13.31.137': 1.0}
```
As you can see the number of GPUs here is 5 even though it should be 8. Interestingly the dashboard shows all 8 GPUs.

### Issue Severity

None

**Comment by rkooo567** [comment]
Looks like the relevant code is https://github.com/ray-project/ray/blob/5568b6142f0e6eb60165265e5415fda6342eb15f/python/ray/_private/resource_spec.py#L164

It seems like there are some limitations here.

1. It can only detect Nvidia 
2. And then it uses this method

```
def _autodetect_num_gpus():
    """Attempt to detect the number of GPUs on this machine.

    TODO(rkn): Only detects NVidia GPUs (except when using WMIC on windows)

    Returns:
        The number of GPUs if any were detected, otherwise 0.
    """
    result = 0
    if importlib.util.find_spec("GPUtil"):
        gpu_list = GPUtil.getGPUs()
        result = len(gpu_list)
    elif sys.platform.startswith("linux"):
        proc_gpus_path = "/proc/driver/nvidia/gpus"
        if os.path.isdir(proc_gpus_path):
            result = len(os.listdir(proc_gpus_path))
    elif sys.platform == "win32":
        props = "AdapterCompatibility"
        cmdargs = ["WMIC", "PATH", "Win32_VideoController", "GET", props]
        lines = subprocess.check_output(cmdargs).splitlines()[1:]
        result = len([x.rstrip() for x in lines if x.startswith(b"NVIDIA")])
    return result
```

Is it possible for you to just run these methods directly on the incorrect node and see which part of code produces the wrong GPU numbers?

**Comment by arndt-k** [comment]
if I replace the srun line in the above bash script with:  
```
srun --gres=gpu:4 --nodes=1 --ntasks=1 -w "\${node_i}" python gpus.py
```
Where `gpus.py` just prints the result of `_autodetect_num_gpus()`, I get 4 on every node.
No idea what to make of that

**Comment by rkooo567** [comment]
I think GpuUtil only supports nvidia GPUs. From your node, can you access the nvidia-smi?

**Comment by arndt-k** [comment]
All the GPUs involved here are nvidia (A100). nvidia-smi works on all nodes, except the head node which does not have GPUs

**Comment by jjyao** [comment]
As a workaround to unblock you, you can manually do `ray start --num-gpus=4 xxx` instead of letting Ray auto figure it out.

**Comment by arndt-k** [comment]
Using `ray start --num-gpus=4` was how I originally had my script set up. But that always errored. Adapting the above script like:  
```
for ((i = 0; i <= \${num_workers}; i++)); do
    node_i=\${nodes_array[\${i}]}
    srun --gres=gpu:4 --nodes=1 --ntasks=1 -w "\${node_i}" echo " Visible \${CUDA_VISIBLE_DEVICES}"
    srun --gres=gpu:4 --nodes=1 --ntasks=1 -w "\${node_i}" ray start --address 134.94.1.99:6374 --block --num-gpus=4 &

```
I get, for all but the first srun run through the loop:  
```
Visibible 0,1,2,3
Traceback (most recent call last):
  File "/p/home/jusers/kaps1/juwels/.local/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/p/home/jusers/kaps1/juwels/.local/lib/python3.10/site-packages/ray/scripts/scripts.py", line 2422, in main
    return cli()
  File "/p/home/jusers/kaps1/juwels/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
 File "/p/home/jusers/kaps1/juwels/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/p/home/jusers/kaps1/juwels/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/p/home/jusers/kaps1/juwels/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/p/home/jusers/kaps1/juwels/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/p/home/jusers/kaps1/juwels/.local/lib/python3.10/site-packages/ray/autoscaler/_private/cli_logger.py", line 852, in wrapper
    return f(*args, **kwargs)
  File "/p/home/jusers/kaps1/juwels/.local/lib/python3.10/site-packages/ray/scripts/scripts.py", line 868, in start
    node = ray._private.node.Node(
  File "/p/home/jusers/kaps1/juwels/.local/lib/python3.10/site-packages/ray/_private/node.py", line 290, in __init__
  self.start_ray_processes()
  File "/p/home/jusers/kaps1/juwels/.local/lib/python3.10/site-packages/ray/_private/node.py", line 1173, in start_ray_processes
    resource_spec = self.get_resource_spec()
  File "/p/home/jusers/kaps1/juwels/.local/lib/python3.10/site-packages/ray/_private/node.py", line 459, in get_resource_spec
    self._resource_spec = ResourceSpec(
  File "/p/home/jusers/kaps1/juwels/.local/lib/python3.10/site-packages/ray/_private/resource_spec.py", line 169, in resolve
    raise ValueError(
ValueError: Attempting to start raylet with 4 GPUs, but CUDA_VISIBLE_DEVICES contains ['0'].
```
Which is obviously true if enumeration starts at 0, so why does this (only sometimes) raise an exception?
So the key to the problem seems to be somewhere in the loop. Might the problem be with my bash script or with slurm somewhere?

**Comment by jjyao** [comment]
Oh I see why Ray only detects one GPU: because `CUDA_VISIBLE_DEVICES` is "[0]" for all but the first srun run. This env var basically tells Ray the available GPUs to it. You need to make sure `CUDA_VISIBLE_DEVICES` env var is "[0, 1, 2, 3]" for all srun run.

**Comment by arndt-k** [comment]
But doesn't my printout show that CUDA_VISIBLE_DEVICES is in fact 0,1,2,3 and not 0? Also the error says it **contains**, not **is** 0. And why would it be different for the different for the different iterations?

**Comment by scv119** [comment]
@arndt-k can you try combine both printing and ray start in the same srun and see the output? something like following

``` srun --gres=gpu:4 --nodes=1 --ntasks=1 -w "\${node_i}" 'echo " Visible \${CUDA_VISIBLE_DEVICES}" && ray start --address 134.94.1.99:6374 --block --num-gpus=4 &'

**Comment by rkooo567** [comment]
Hey, so I think there are 2 issues here.

For the original issue, Ray is supposed to detect GPUs correctly and set `CUDA_VISIBLE_DEVICES`. The issue here seems like your machine probably has lost a NVIDIA driver. I think this issue is related https://forums.developer.nvidia.com/t/nvidia-smi-has-failed-because-it-couldnt-communicate-with-the-nvidia-driver-make-sure-that-the-latest-nvidia-driver-is-installed-and-running/197141. 

For the manual configuration, you need to make sure --num-gpus is set, and `CUDA_VISIBLE_DEVICES` env var is properly passed to all the workers. `CUDA_VISIBLE_DEVICES=0,1,2,3 ray start --num-gpus=4`

For this one, +1 on @scv119's comment above ^.
