### ISSUE TITLE
[serve] windows test_standalone3 failing

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#34098]
### What happened + What you expected to happen

================================== FAILURES ===================================
--
  | _______________________ test_legacy_sync_handle_env_var _______________________
  |  
  | call_ray_stop_only = None
  |  
  | def test_legacy_sync_handle_env_var(call_ray_stop_only):  # noqa: F811
  | script = """
  | from ray import serve
  | from ray.serve.dag import InputNode
  | from ray.serve.drivers import DAGDriver
  | import ray
  |  
  | @serve.deployment
  | class A:
  | def predict(self, inp):
  | return inp
  |  
  | @serve.deployment
  | class Dispatch:
  | def __init__(self, handle):
  | self.handle = handle
  |  
  | def predict(self, inp):
  | ref = self.handle.predict.remote(inp)
  | assert isinstance(ref, ray.ObjectRef), ref
  | return ray.get(ref)
  |  
  | with InputNode() as inp:
  | a = A.bind()
  | d = Dispatch.bind(a)
  | dag = d.predict.bind(inp)
  |  
  | handle = serve.run(DAGDriver.bind(dag))
  | assert ray.get(handle.predict.remote(1)) == 1
  | """
  |  
  | >       run_string_as_driver(script, env={SYNC_HANDLE_IN_DAG_FEATURE_FLAG_ENV_KEY: "1"})
  |  
  | \\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\Bazel.runfiles_b7o46yfs\runfiles\com_github_ray_project_ray\python\ray\serve\tests\test_standalone3.py:378:
  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  |  
  | driver_script = '\nfrom ray import serve\nfrom ray.serve.dag import InputNode\nfrom ray.serve.drivers import DAGDriver\nimport ray\n\n... = d.predict.bind(inp)\n\nhandle = serve.run(DAGDriver.bind(dag))\nassert ray.get(handle.predict.remote(1)) == 1\n    '
  | env = {'SERVE_DEPLOYMENT_HANDLE_IS_SYNC': '1'}, encode = 'utf-8'
  |  
  | def run_string_as_driver(driver_script: str, env: Dict = None, encode: str = "utf-8"):
  | """Run a driver as a separate process.
  |  
  | Args:
  | driver_script: A string to run as a Python script.
  | env: The environment variables for the driver.
  |  
  | Returns:
  | The script's output.
  | """
  | proc = subprocess.Popen(
  | [sys.executable, "-"],
  | stdin=subprocess.PIPE,
  | stdout=subprocess.PIPE,
  | stderr=subprocess.STDOUT,
  | env=env,
  | )
  | with proc:
  | output = proc.communicate(driver_script.encode(encoding=encode))[0]
  | if proc.returncode:
  | print(ray._private.utils.decode(output, encode_type=encode))
  | >               raise subprocess.CalledProcessError(
  | proc.returncode, proc.args, output, proc.stderr
  | )
  | E               subprocess.CalledProcessError: Command '['C:\\Miniconda3\\python.exe', '-']' returned non-zero exit status 1.
  |  
  | c:\install\ray\python\ray\_private\test_utils.py:396: CalledProcessError
  | ============================== warnings summary ===============================
  | ..\..\..\..\..\..\..\..\Miniconda3\lib\site-packages\_pytest\config\__init__.py:1126
  | C:\Miniconda3\lib\site-packages\_pytest\config\__init__.py:1126: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: anyio
  | self._mark_plugins_for_rewrite(hook)
  |  
  | ::test_long_poll_timeout_with_max_concurrent_queries[ray_instance0]
  | ::test_http_request_number_of_retries[True-ray_instance0]
  | ::test_http_request_number_of_retries[False-ray_instance0]
  | ::test_handle_early_detect_failure
  | c:\install\ray\python\ray\serve\_private\router.py:92: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  | self.config_updated_event = asyncio.Event(loop=event_loop)
  |  
  | ::test_autoscaler_shutdown_node_http_everynode
  | C:\Miniconda3\lib\site-packages\_pytest\threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread ray_listen_error_messages
  |  
  | Traceback (most recent call last):
  | File "C:\Miniconda3\lib\threading.py", line 932, in _bootstrap_inner
  | self.run()
  | File "C:\Miniconda3\lib\threading.py", line 870, in run
  | self._target(*self._args, **self._kwargs)
  | File "c:\install\ray\python\ray\_private\worker.py", line 1977, in listen_error_messages
  | _, error_data = worker.gcs_error_subscriber.poll()
  | File "c:\install\ray\python\ray\_private\gcs_pubsub.py", line 327, in poll
  | self._poll_locked(timeout=timeout)
  | File "c:\install\ray\python\ray\_private\gcs_pubsub.py", line 258, in _poll_locked
  | fut.result(timeout=1)
  | File "C:\Miniconda3\lib\site-packages\grpc\_channel.py", line 744, in result
  | raise self
  | grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
  | status = StatusCode.UNKNOWN
  | details = "Stream removed"
  | debug_error_string = "UNKNOWN:Error received from peer ipv4:172.28.59.137:6379 {grpc_message:"Stream removed", grpc_status:2, created_time:"2023-04-05T03:12:41.744469434+00:00"}"
  | >
  |  
  | warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

### Versions / Dependencies

master and 2.4.0 branch

### Reproduction script

https://buildkite.com/ray-project/oss-ci-build-branch/builds/3177#01874fb7-ffaf-4844-92a4-e5a560abbc40

https://buildkite.com/ray-project/oss-ci-build-branch/builds/3180#01874f35-2fa9-4365-891d-9257c3034b50

### Issue Severity

None

**Comment by clarng** [comment]
tagging serve oncall, feel free to re-assign if this is not assignment, thanks!
