### ISSUE TITLE
async_hyperband_example cannot run through

### ISSUE THREAD

**Issue by hohaxu** [ray-project/ray#3410]
### System information
- **Ubuntu**:
- **Ray installed: pip install**:
- **Ray version: 0.5.3**:
- **Python version  3.5**:
- **Exact command to reproduce**:
python async_hyperband_example.py

### Describe the problem

cannot run through the example with error of 'config' argument missing.

### Source code / logs

Suppressing duplicate error message.
Worker ip unknown, skipping log sync for /home/hao/ray_results/asynchyperband_test/MyTrainableClass_0_height=68,width=45_2018-11-26_14-53-12menkgsuo
Error processing event.
Traceback (most recent call last):
  File "/home/hao/src/sse/env/sse/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 239, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/hao/src/sse/env/sse/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/hao/src/sse/env/sse/lib/python3.5/site-packages/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(efb73495bdd5d323552cf8db4a260d713f7889b3). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/home/hao/src/sse/env/sse/lib/python3.5/site-packages/ray/worker.py", line 923, in _process_task
    self.reraise_actor_init_error()
  File "/home/hao/src/sse/env/sse/lib/python3.5/site-packages/ray/worker.py", line 267, in reraise_actor_init_error
    raise self.actor_init_error
  File "/home/hao/src/sse/env/sse/lib/python3.5/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/home/hao/src/sse/env/sse/lib/python3.5/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/hao/src/sse/env/sse/lib/python3.5/site-packages/ray/tune/trainable.py", line 84, in __init__
    self._setup()
TypeError: _setup() missing 1 required positional argument: 'config'

**Comment by ericl** [comment]
Please upgrade to the the latest ray version, which passes in config correctly.

**Comment by hohaxu** [comment]
thanks!  seems 0.5.3 is the latest for pip install?
