### ISSUE TITLE
[Data] FastFileMetadataProvider does not work with streaming executor

### ISSUE THREAD

**Issue by c21** [ray-project/ray#34139]
### What happened + What you expected to happen

`FastFileMetadataProvider` does not provide size_bytes metadata in block metadata, so it does not work with streaming executor at this moment. Example error stack trace:

```
>>> ds = ray.data.read_images(["/Users/chengsu/try/image/38961.jpg", "/Users/chengsu/try/image/39726.jpg"], meta_provider=FastFileMetadataProvider())
>>> ds = ds.map_batches(lambda x:x)
>>> ds.cache()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chengsu/ray/python/ray/data/dataset.py", line 4088, in cache
    self._plan.execute(force_read=True)
  File "/Users/chengsu/ray/python/ray/data/_internal/plan.py", line 580, in execute
    blocks = execute_to_legacy_block_list(
  File "/Users/chengsu/ray/python/ray/data/_internal/execution/legacy_compat.py", line 107, in execute_to_legacy_block_list
    dag, stats = _get_execution_dag(
  File "/Users/chengsu/ray/python/ray/data/_internal/execution/legacy_compat.py", line 136, in _get_execution_dag
    dag, stats = _to_operator_dag(plan, allow_clear_input_blocks)
  File "/Users/chengsu/ray/python/ray/data/_internal/execution/legacy_compat.py", line 169, in _to_operator_dag
    operator = _blocks_to_input_buffer(blocks, owns_blocks)
  File "/Users/chengsu/ray/python/ray/data/_internal/execution/legacy_compat.py", line 225, in _blocks_to_input_buffer
    output = _block_list_to_bundles(blocks, owns_blocks=owns_blocks)
  File "/Users/chengsu/ray/python/ray/data/_internal/execution/legacy_compat.py", line 347, in _block_list_to_bundles
    RefBundle(
  File "<string>", line 7, in __init__
  File "/Users/chengsu/ray/python/ray/data/_internal/execution/interfaces.py", line 56, in __post_init__
    raise ValueError(
ValueError: The size in bytes of the block must be known: (ObjectRef(00ffffffffffffffffffffffffffffffffffffff0100000001000000), BlockMetadata(num_rows=1, size_bytes=None, schema=None, input_files=array(['/Users/chengsu/try/image/38961.jpg'], dtype='<U34'), exec_stats=None))
>>> ds = ray.data.read_images(["/Users/chengsu/try/image/38961.jpg", "/Users/chengsu/try/image/39726.jpg"], meta_provider=FastFileMetadataProvider())
```

### Versions / Dependencies

master

### Reproduction script

as above

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ericl** [comment]
@c21 given the improvements in the default file meta provider, shall we remove the meta_provider arg for all formats except for parquet?
