### ISSUE TITLE
[RLlib] Value Error when running PPO  

### ISSUE THREAD

**Issue by esham01** [ray-project/ray#34199]
### What happened + What you expected to happen

When I run PPO with my custom environment and custom model (pasted below), I run into the below error after a different random number of epochs each time: 

```
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/emittal2/code/Users/emittal/MineCLIP/main/mineagent/ppo_train_gpu.py", line 147, in <module>
    result = algo.train()
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 368, in train
    raise skipped from exception_cause(skipped)
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 365, in train
    result = self.step()
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 782, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 2713, in _run_one_training_iteration
    results = self.training_step()
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/algorithms/ppo/ppo.py", line 358, in training_step
    train_batch = synchronous_parallel_sample(
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/execution/rollout_ops.py", line 82, in synchronous_parallel_sample
    sample_batches = [worker_set.local_worker().sample()]
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 914, in sample
    batches = [self.input_reader.next()]
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/evaluation/sampler.py", line 92, in next
    batches = [self.get_data()]
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/evaluation/sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 323, in run
    outputs = self.step()
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 349, in step
    active_envs, to_eval, outputs = self._process_observations(
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 667, in _process_observations
    self._handle_done_episode(
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 816, in _handle_done_episode
    self._build_done_episode(env_id, is_done, outputs)
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 706, in _build_done_episode
    episode.postprocess_episode(
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/evaluation/episode_v2.py", line 275, in postprocess_episode
    pre_batch = collector.build_for_training(policy.view_requirements)
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/evaluation/collectors/agent_collector.py", line 426, in build_for_training
    self._cache_in_np(np_data, data_col)
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/evaluation/collectors/agent_collector.py", line 596, in _cache_in_np
    cache_dict[key] = [_to_float_np_array(d) for d in self.buffers[key]]
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/evaluation/collectors/agent_collector.py", line 596, in <listcomp>
    cache_dict[key] = [_to_float_np_array(d) for d in self.buffers[key]]
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/evaluation/collectors/agent_collector.py", line 33, in _to_float_np_array
    raise ValueError
ValueError
```

### Versions / Dependencies

ray: 2.3.1 

### Reproduction script

# Code for creating PPO algorithm: 

```

 ModelCatalog.register_custom_model("my_torch_model", CustomTorchModel)
  ray.init()

 def env_creator(env_config):
       return CustomEnv(env_config)

register_env("custom_env", env_creator)
algo = ppo.PPO(env="custom_env", config={
        "framework": "torch",
        "disable_env_checking": True,
        "simple_optimizer":True,
        "model": {
            "custom_model": "my_torch_model",
            # Extra kwargs to be passed to your model's c'tor.
            "custom_model_config": {},
        },
    })


for i in range(10):
        result = algo.train()

```

For my custom env, it returns a float for the reward and this is the observation space that I have:

```
dict = {}
dict["rgb"] = gymnasium.spaces.Box(low=-80, high=80, shape = (512,))
dict["compass"] = gymnasium.spaces.Box(low = -60, high =60, shape=(4,))
dict["gps"] = gymnasium.spaces.Box(low = -80, high = 80, shape=(3,))


dict["voxels"] = gymnasium.spaces.Box(low=0, high=26, shape=(27,))

dict["prompt"] = gymnasium.spaces.Box(low=-50, high= 50, shape = [512,])

self.observation_space = gymnasium.spaces.Dict(dict)
```

I also pasted some code from my custom model below:

```
class CustomTorchModel(TorchModelV2, nn.Module):
    def __init__(self, obs_space, action_space, num_outputs, model_config, name):
        TorchModelV2.__init__(
            self, obs_space, action_space, num_outputs, model_config, name
        )
        nn.Module.__init__(self)

        self._obs_= []


        cfg = OmegaConf.load("conf.yaml")

        feature_net_kwargs = cfg.feature_net_kwargs

        feature_net = {}
        for k, v in feature_net_kwargs.items():
            v = dict(v)
            cls = v.pop("cls")
            cls = getattr(F, cls)
            feature_net[k] = cls(**v, device=device)

        feature_fusion_kwargs = cfg.feature_fusion

        feature_net = SimpleFeatureFusion(
        feature_net, **feature_fusion_kwargs, device=device)
        
        self._actor_ = actor = MultiCategoricalActor(
        feature_net,
        action_dim=[3, 3, 4, 25, 25, 8],
        device=device,
        **cfg.actor)

        self._mine_agent_ = MineAgent(actor=actor).to(device)
        self._value_ = None
        
    @override(TorchModelV2)
    def forward(self, input_dict, state, seq_lens):


        obs = input_dict["obs"]
        self._obs_ = obs

       
        dic = {
        "compass": obs["compass"],
        "gps": obs["gps"],
        "voxels": obs["voxels"].cpu().int(),
        "prompt": obs["prompt"],
        "rgb": obs["rgb"],
        }
        
        batch_obs = Batch(obs=dic)
        batch_val, self._value_ = self._mine_agent_(batch_obs)

        logits = batch_val.logits


        # masking out invalid actions 
        logits[:,-6] = -1e6
        
        logits[:,-4:] = -1e6

        x,_ = logits.shape

        zeros = torch.zeros((x, 280))

        logits_final = torch.cat((logits, zeros), dim=1)
    
        return logits_final, []

    @override(TorchModelV2)
    def value_function(self):
        return self._value_
    




class MineAgent(nn.Module):
    def __init__(
        self,
        actor: nn.Module,
        deterministic_eval: bool = True,
    ):
        super().__init__()
        self.actor = actor
        self._deterministic_eval = deterministic_eval
        self.dist_fn = actor.dist_fn

    def forward(
        self,
        batch: Batch,
        state=None,
        **kwargs,
    ) -> Batch:
        logits, hidden,value = self.actor(batch.obs, state=state)

        
        if isinstance(logits, tuple):
            dist = self.dist_fn(*logits)
        else:
            dist = self.dist_fn(logits)
        if self._deterministic_eval and not self.training:
            act = dist.mode()
        else:
            act = dist.sample()
        return Batch(logits=logits, act=act, state=hidden, dist=dist), value
    


class MultiCategoricalActor(nn.Module):
    def __init__(
        self,
        preprocess_net: nn.Module,
        *,
        action_dim: list[int],
        hidden_dim: int,
        hidden_depth: int,
        activation: str = "relu",
        device,
    ):
        super().__init__()
        self.mlps = nn.ModuleList()
        self.preprocess = preprocess_net
        for action in action_dim:
            net = build_mlp(
                input_dim=preprocess_net.output_dim,
                output_dim=action,
                hidden_dim=hidden_dim,
                hidden_depth=hidden_depth,
                activation=activation,
                norm_type=None,
            )
            self.mlps.append(net)
        self._action_dim = action_dim
        self._device = device

        self._lin_layer = nn.Sequential(nn.ReLU(), nn.Linear(68,68), nn.ReLU(), nn.Linear(68,1))

    def forward(self, x, state=None, info=None):
        hidden = None

        x, _ = self.preprocess(x)


        value = torch.cat([mlp(x) for mlp in self.mlps], dim=1)

        value = self._lin_layer(value).squeeze(1)
        
        return torch.cat([mlp(x) for mlp in self.mlps], dim=1), hidden, value

    @property
    def dist_fn(self):
        return lambda x: MultiCategorical(logits=x, action_dims=self._action_dim)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
@esham01 Thanks for filing this issue.
My best guess is that you environment returns a torch tensor instead of a numpy array.
While we plan on supporting this in the future, we currently only support numpy arrays I believe.

If that does not solve the proble, could you please compile the code you posted into a full reproduction script that we can run on our end?

**Comment by ArturNiederfahrenhorst** [comment]
I'm closing this issue for now, assuming that the environment returning torch tensor was the issue.
We would like to support this in the future, too.

Feel free to reopen the issue if there is something else coming up that is directly related.

**Comment by TooSchoolForCool** [comment]
> I'm closing this issue for now, assuming that the environment returning torch tensor was the issue. We would like to support this in the future, too.
> 
> Feel free to reopen the issue if there is something else coming up that is directly related.

Hi there,

I am facing the same issue, i.e., the environment returning torch tensor.

I am wondering does ray/rllib currently support environment that retursn torch.Tensor?
