### ISSUE TITLE
[Runtime Env/Ray Job] Job submission fails when specifing local zip file as working dir 

### ISSUE THREAD

**Issue by spolcyn** [ray-project/ray#34605]
### What happened + What you expected to happen

1. The docs (https://docs.ray.io/en/latest/ray-core/handling-dependencies.html#api-reference) imply a local `.zip` file can be passed as the working dir in a `runtime_env`. However, doing so fails.
2. Expected to be able to pass in a local `.zip` file, just like a local directory
3. The error may be related to the `@client_mode_hook` decorator on the `_internal_kv_put` function. In the repro script below, `ray.init()` is never called, so a Ray Client connection is not made -- only the `JobSubmissionClient` is initialized.

Full traceback:
```
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/ray/_private/runtime_env/working_dir.py", line 64, in upload_working_dir_if_needed
    working_dir_uri = get_uri_for_directory(working_dir, excludes=excludes)
  File "/venv/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 479, in get_uri_for_directory
    raise ValueError(f"directory {directory} must be an existing directory")
ValueError: directory /tmp/local.zip must be an existing directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 360, in _store_package_in_gcs
    _internal_kv_put(pkg_uri, data)
  File "/venv/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/ray/experimental/internal_kv.py", line 94, in _internal_kv_put
    return global_gcs_client.internal_kv_put(key, value, overwrite, namespace) == 0
AttributeError: 'NoneType' object has no attribute 'internal_kv_put'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/ray/_private/runtime_env/working_dir.py", line 75, in upload_working_dir_if_needed
    upload_package_to_gcs(pkg_uri, package_path.read_bytes())
  File "/venv/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 504, in upload_package_to_gcs
    _store_package_in_gcs(pkg_uri, pkg_bytes)
  File "/venv/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 362, in _store_package_in_gcs
    raise RuntimeError(
RuntimeError: Failed to store package in the GCS.
  - GCS URI: gcs://_ray_pkg_81681dbe1fcacac350b9fd95f3734ae6.zip
  - Package data (0.00MiB): b'PK\x03\x04\x14\x00\x00\x00\x00\x00\xec\x00\x94V\x00'...


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/test_ray_job.py", line 18, in <module>
    client.submit_job(entrypoint="foo.py", runtime_env=runtime_env)
  File "/venv/lib/python3.9/site-packages/ray/dashboard/modules/job/sdk.py", line 160, in submit_job
    self._upload_working_dir_if_needed(runtime_env)
  File "/venv/lib/python3.9/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 373, in _upload_working_dir_if_needed
    upload_working_dir_if_needed(runtime_env, upload_fn=_upload_fn)
  File "/venv/lib/python3.9/site-packages/ray/_private/runtime_env/working_dir.py", line 77, in upload_working_dir_if_needed
    raise RuntimeEnvSetupError(
ray.exceptions.RuntimeEnvSetupError: Failed to set up runtime environment.
Failed to upload package local.zip to the Ray cluster: Failed to store package in the GCS.
  - GCS URI: gcs://_ray_pkg_81681dbe1fcacac350b9fd95f3734ae6.zip
  - Package data (0.00MiB): b'PK\x03\x04\x14\x00\x00\x00\x00\x00\xec\x00\x94V\x00'...
```

### Versions / Dependencies

Ray 2.3.0 
Python 3.9.10
Ubuntu

### Reproduction script

```
import shutil
import os
from ray.job_submission import JobSubmissionClient

if not os.path.exists("foo"):
    os.mkdir("foo")
with open("foo/file.txt", mode="w") as f:
    f.write("foofile")
shutil.make_archive(base_name="local", base_dir="foo", format="zip")
assert os.path.exists(os.path.abspath("local.zip"))

address = # insert Ray cluster address here
runtime_env: dict = {"working_dir": "local.zip"}
client = JobSubmissionClient(address)
try:
    client.submit_job(entrypoint="foo.py", runtime_env=runtime_env)
except:
    print("Failed to submit with zip")


runtime_env["working_dir"] = "foo"
client.submit_job(entrypoint="foo.py", runtime_env=runtime_env)
print("Succeeded with non-zip")
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment]
cc @architkulkarni I suppose the local zip is currently not supported? (Maybe because we need to support unzipping all these).

**Comment by architkulkarni** [comment]
I think this is actually a bug. The Ray Job API should support every runtime env behavior that's supported in `ray.init()`. It was probably an oversight because we have two separate code paths for uploading the local files for the Job API and for `ray.init()`.

**Comment by cszhu** [comment]
This P2 issue has seen no activity in the past 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please comment and remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
