### ISSUE TITLE
[Serve] Original error gets lost in serializing exception object 

### ISSUE THREAD

**Issue by smit-kiri** [ray-project/ray#34683]
### What happened + What you expected to happen

When a deployment initialization raises an exception from a package that is not available in the controller environment, the controller is unable to de-serialize the object, and raises a `package not found` exception instead.

The original error in the deployment gets lost and the only way to see what caused the exception is to install the relevant package in the base docker image.

### Versions / Dependencies

Tested on `ray == 2.3.1` and `ray==2.2.0`

### Reproduction script

# Scripts

`test.py`
```
from ray import serve
from ray.serve.drivers import DAGDriver


@serve.deployment(name="test-deployment")
class TestDeployment:
    def __init__(self):
        from sqlalchemy import create_engine

        # Will raise an error
        create_engine("mysql://some_wrong_url:3306").connect()


driver = DAGDriver.bind({"/test": TestDeployment.bind()})
```

`test_deployment.py`
```
import_path: test:driver

host: 127.0.0.1
port: 8000

deployments:
  - name: test-deployment
    num_replicas: 1
    ray_actor_options:
      runtime_env:
        pip:
          - mysqlclient==2.1.1
          - sqlalchemy==1.3.19
```

# Commands
```
serve run test_deployment.yaml
```

# Expected output
```
(ServeController pid=39362) ERROR 2023-04-21 18:04:28,618 controller 39362 deployment_state.py:481 - Exception in deployment 'test-deployment'
(ServeController pid=39362) Traceback (most recent call last):
(ServeController pid=39362)   File "/Users/smit.kiri/.pyenv/versions/3.8.9/envs/rayserve/lib/python3.8/site-packages/ray/serve/_private/deployment_state.py", line 472, in check_ready
(ServeController pid=39362)     deployment_config, version = ray.get(self._ready_obj_ref)
(ServeController pid=39362)   File "/Users/smit.kiri/.pyenv/versions/3.8.9/envs/rayserve/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
(ServeController pid=39362)     return func(*args, **kwargs)
(ServeController pid=39362)   File "/Users/smit.kiri/.pyenv/versions/3.8.9/envs/rayserve/lib/python3.8/site-packages/ray/_private/worker.py", line 2382, in get
(ServeController pid=39362)     raise value
(ServeController pid=39362) ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception
(ServeController pid=39362) traceback: Traceback (most recent call last):
(ServeController pid=39362)   File "/Users/smit.kiri/.pyenv/versions/3.8.9/envs/rayserve/lib/python3.8/site-packages/ray/exceptions.py", line 46, in from_ray_exception
(ServeController pid=39362)     return pickle.loads(ray_exception.serialized_exception)
(ServeController pid=39362) ModuleNotFoundError: No module named 'sqlalchemy'
(ServeController pid=39362) 
(ServeController pid=39362) The above exception was the direct cause of the following exception:
(ServeController pid=39362) 
(ServeController pid=39362) Traceback (most recent call last):
(ServeController pid=39362)   File "/Users/smit.kiri/.pyenv/versions/3.8.9/envs/rayserve/lib/python3.8/site-packages/ray/_private/serialization.py", line 369, in deserialize_objects
(ServeController pid=39362)     obj = self._deserialize_object(data, metadata, object_ref)
(ServeController pid=39362)   File "/Users/smit.kiri/.pyenv/versions/3.8.9/envs/rayserve/lib/python3.8/site-packages/ray/_private/serialization.py", line 275, in _deserialize_object
(ServeController pid=39362)     return RayError.from_bytes(obj)
(ServeController pid=39362)   File "/Users/smit.kiri/.pyenv/versions/3.8.9/envs/rayserve/lib/python3.8/site-packages/ray/exceptions.py", line 40, in from_bytes
(ServeController pid=39362)     return RayError.from_ray_exception(ray_exception)
(ServeController pid=39362)   File "/Users/smit.kiri/.pyenv/versions/3.8.9/envs/rayserve/lib/python3.8/site-packages/ray/exceptions.py", line 49, in from_ray_exception
(ServeController pid=39362)     raise RuntimeError(msg) from e
(ServeController pid=39362) RuntimeError: Failed to unpickle serialized exception
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by smit-kiri** [comment]
@edoakes

**Comment by smit-kiri** [comment]
^However you serialize the exception for the fix, please make sure the traceback is available in the error message

**Comment by edoakes** [comment]
Yep, thanks for filing
