### ISSUE TITLE
[Tune] thread limit resulting in the job failure in multi-tenancy usage

### ISSUE THREAD

**Issue by lly-zero-one** [ray-project/ray#34745]
### What happened + What you expected to happen

We touched an issue related to the thread limit in Ray tune. Our application of using Ray is multi-tenancy usage and multiple clients could submit job to the cluster, and there could be many pending jobs due to the resource constraint. Each Ray tune (ray.util.client.server) process is creating several hundreds of threads for either running or pending job. When the total number of jobs reached 30+, we started seeing the following thread creation error. I have done: 1) OPENBLAS_NUM_THREADS=1 2) ulimit -u unlimited, but they didn't fully solve the issue. There seems to be a threshold of 13.5k on total number of threads. We actually didn't find a matched thread limit setting in our system. 

```python
Exception in thread ray_print_logs:
Traceback (most recent call last):
  File "/mnt/miniconda3/envs/ray/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/mnt/miniconda3/envs/ray/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/miniconda3/envs/ray/lib/python3.7/site-packages/ray/_private/worker.py", line 787, in print_logs
    data = subscriber.poll()
  File "/mnt/miniconda3/envs/ray/lib/python3.7/site-packages/ray/_private/gcs_pubsub.py", line 357, in poll
    self._poll_locked(timeout=timeout)
  File "/mnt/miniconda3/envs/ray/lib/python3.7/site-packages/ray/_private/gcs_pubsub.py", line 247, in _poll_locked
    self._poll_request(), timeout=timeout
  File "/tmp/ray/session_2023-04-25_06-34-10_629284_79518/runtime_resources/py_modules_files/XXX_QBI7JZVEGCO6S3WYUN2MIFI42MY3273F/grpc/_channel.py", line 976, in future
    (operations,), event_handler, self._context)
  File "/tmp/ray/session_2023-04-25_06-34-10_629284_79518/runtime_resources/py_modules_files/XXX_QBI7JZVEGCO6S3WYUN2MIFI42MY3273F/grpc/_channel.py", line 1306, in create
    _run_channel_spin_thread(state)
  File "/tmp/ray/session_2023-04-25_06-34-10_629284_79518/runtime_resources/py_modules_files/XXX_QBI7JZVEGCO6S3WYUN2MIFI42MY3273F/grpc/_channel.py", line 1270, in _run_channel_spin_thread
    channel_spin_thread.start()
  File "src/python/grpcio/grpc/_cython/_cygrpc/fork_posix.pyx.pxi", line 117, in grpc._cython.cygrpc.ForkManagedThread.start
  File "/mnt/miniconda3/envs/ray/lib/python3.7/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```
### Versions / Dependencies

ray, version 2.2.0
Python 3.7.11 (default, Jul 27 2021, 14:32:16)

### Reproduction script

```
import torch
import torch.nn as nn

import manta
import ray
from ray import train
from ray.air import session, Checkpoint
from ray.train.torch import TorchTrainer
from ray.air.config import ScalingConfig
from ray.air.config import RunConfig
from ray.air.config import CheckpointConfig


input_size = 1
layer_size = 32
output_size = 1
num_epochs = 200
num_workers = 3

class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.layer1 = nn.Linear(input_size, layer_size)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(layer_size, output_size)

    def forward(self, input):
        return self.layer2(self.relu(self.layer1(input)))

def train_loop_per_worker():

    dataset_shard = session.get_dataset_shard("train")
    model = NeuralNetwork()
    loss_fn = nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(),
                lr=0.01,
                weight_decay=0.01)
    model = train.torch.prepare_model(model)

    for epoch in range(num_epochs):
        print(epoch)

torch.manual_seed(42)

ray.init(address=YOURCLUSTER)
scaling_config = ScalingConfig(num_workers=128, use_gpu=True)

trainer = TorchTrainer(
    train_loop_per_worker=train_loop_per_worker,
    scaling_config=scaling_config)

result = trainer.fit()

```

Then you can start the script 50+ times, and will see the thread creation issue in the header node. 

### Issue Severity

High: It blocks me from completing my task.

**Comment by richardliaw** [comment]
cc @matthewdeng and cc @rkooo567 to provide some assistance here?

**Comment by richardliaw** [comment]
So this is a threading overload primarily on the header process?

**Comment by lly-zero-one** [comment]
> @lly-zero-one So this is a threading overload primarily on the head process?

Yes

**Comment by rkooo567** [comment]
I have a couple of qusetions.

> OPENBLAS_NUM_THREADS=1 2) ulimit -u unlimited

How did you set this? Did you specify it in ray start, initialization command, or driver?

> Each Ray tune (ray.util.client.server) process is creating several hundreds of threads

Is using ray client necessary for your use case? We generally recommend using the job API https://docs.ray.io/en/master/cluster/running-applications/job-submission/index.html#ray-jobs-api instead of ray client. 

If you can use the job submission, you can limit the number of concurrent jobs by specifying https://docs.ray.io/en/master/cluster/running-applications/job-submission/cli.html#cmdoption-ray-job-submit-entrypoint-num-cpus.

Or alternatively you can increase the system level thread limit https://stackoverflow.com/questions/32283003/python-cant-start-new-thread-100-active-threads.

**Comment by lly-zero-one** [comment]
> How did you set this? Did you specify it in ray start, initialization command, or driver?

Just before the `ray start ` command in head node. 
```
export OPENBLAS_NUM_THREADS=1
ulimit -n unlimited
ray start XXX
```

> Is using ray client necessary for your use case? We generally recommend using the job API
hmm, this is more like a legacy reason. We started without the availability of Job API.  :) 

> Or alternatively you can increase the system level thread limit

We already set it to unlimited. 

Is there any hint where these threads are from?

**Comment by rkooo567** [comment]
I think ulimit -n is for setting the maximum number of open files, not number of threads. I think you need to use `ulimit -u` for the threads.

**Comment by rkooo567** [comment]
> hmm, this is more like a legacy reason. We started without the availability of Job API. :)

I recommend you to migrate if possible! This can also allow you to limit the number of jobs concurrently running. We are in the path of discouraging ray client because it has lots of subtle (and bad) issues that happens due to the fact that your driver runs outside the cluster.

**Comment by lly-zero-one** [comment]
> I think ulimit -n is for setting the maximum number of open files, not number of threads. I think you need to use `ulimit -u` for the threads.

Good catch. I saw the setting is already large. 
```
(root) ~ # ulimit -u
3062704
```

**Comment by rkooo567** [comment]
Can you try `sudo py-spy dump --pid <driver_pid>` and workers and see how many threads are there?

Normally, Ray processes have many threads, but 3062704 seems to be pretty hard to exceed...

**Comment by lly-zero-one** [comment]
yes, we got ~500 threads for each running job and ~200 threads for each pending job. All of them are actually idle state. 
```
Thread 48069 (idle): "MainThread"
Thread 48118 (idle): "Thread-1"
Thread 48134 (idle): "ray_client_server_0"
Thread 48136 (idle): "Thread-2"
Thread 48138 (idle): "ray_client_server_1"
Thread 48139 (idle): "Thread-3"
Thread 48177 (idle): "ray_import_thread"
Thread 48178 (idle): "ray_listen_error_messages"
Thread 48179 (idle): "ray_print_logs"
Thread 48187 (idle): "ray_client_server_2"
Thread 48192 (idle): "ray_client_server_3"
Thread 48254 (idle): "ray_client_server_4"
```

I can see clearly in our dashboard, when the number of threads is around 16k, there will be thread creation issue.

**Comment by lly-zero-one** [comment]
BTW, Any known side effect to reduce RAY_CLIENT_SERVER_MAX_THREADS?

**Comment by rkooo567** [comment]
cc @ckw017 for the question ^

**Comment by ckw017** [comment]
It looks like this will lower the maximum number of concurrent ray client connections you can have. At the moment there's one thread spawned for transferring serialized objects, and one thread for handling logs, so if you lower it you'll want to set it to twice the number of connections you expect to be open concurrently.

**Comment by lly-zero-one** [comment]
Thanks. Yes, we found some scheduling issue when we lower the setting (we did see the idle threads are reduced). Basically, the `ray.utill.client.server` will not exit even the job is finished.

**Comment by ckw017** [comment]
Looks like its used in a few spots:
* On the client side (i.e. local laptop) -- this doesn't control any functionality, looks like its just used to raise errors
* On the server side proxier: this proxy is used so that you don't need to use a separate port per client connection, and forwards requests to the server defined at `ray/python/ray/util/client/server/server.py`
* On the individual client servers: these are what ultimately receive requests and execute them on a driver on the head node.

For the latter two, this is based off of whatever the environment variable is set to when you call `ray start`. The real bottle neck is likely the proxier, since every connection goes through it. 

>Can you clarify if this is the case 
> you'll want to set it to twice the number of connections you expect to be open concurrently.

The client has two separate streams for talking to the driver on the head node, one for serialized python objects (`ray/python/ray/util/client/dataclient.py`) and one for logs (`ray/python/ray/util/client/logsclient.py`).

**Comment by pablete** [comment]
Ack .. thanks for the reply. 

It looks like the proxier needs a different env variable  `CLIENT_SERVER_PROXIER_MAX_THREADS = 100` 
(ie: that limits to 50 clients with 2 threads per client)

But the actual server does not need that many threads, and can use `CLIENT_SERVER_MAX_THREADS = 10` (or any lower number) 

Perhaps that could limit the large number of threads we are seeing.

**Comment by ckw017** [comment]
> It looks like the proxier needs a different env variable CLIENT_SERVER_PROXIER_MAX_THREADS = 100 (ie: that limits to 50 clients with 2 threads per client)

Having separate parameters for the two limits sounds like a reasonable ask, I can look into adding this. It also looks like Python 3.7 and below has some surprising default behavior for [ThreadPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#threadpoolexecutor): 

> Changed in version 3.8: ...
> 
> ThreadPoolExecutor now reuses idle worker threads before starting max_workers worker threads too.

What I suspect is happening here is that the client makes unary-unary calls for some operations (mainly for talking to the internal KV store on the head node), and because of the behavior for 3.8 or below, each of these calls spawns a new thread instead of reusing idle ones until hitting max workers. However, to get around this you would need to upgrade to Python 3.8.

**Comment by cszhu** [comment]
This P2 issue has seen no activity in the past 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please comment and remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
