### ISSUE TITLE
[Ray Data] cannot run ds.show() with Ray client connected

### ISSUE THREAD

**Issue by kira-lin** [ray-project/ray#34770]
### What happened + What you expected to happen

When I connect to a Ray cluster via Ray client, I found that ds.show will fail because it tries to call functions of core_worker. 
The error logs are:
> 2023-04-26 17:50:33,089 INFO datastream.py:2271 -- Tip: Use `take_batch()` instead of `take() / show()` to return records in pandas or numpy batch format.
2023-04-26 17:50:33,156 INFO streaming_executor.py:87 -- Executing DAG InputDataBuffer[Input] -> TaskPoolMapOperator[ReadRange]
2023-04-26 17:50:33,156 INFO streaming_executor.py:88 -- Execution config: ExecutionOptions(resource_limits=ExecutionResources(cpu=None, gpu=None, object_store_memory=None), locality_with_output=False, preserve_order=False, actor_locality_enabled=True, verbose_progress=False)
2023-04-26 17:50:33,156 INFO streaming_executor.py:90 -- Tip: To enable per-operator progress reporting, set RAY_DATA_VERBOSE_PROGRESS=1.
Traceback (most recent call last):                                                                                                   
  File "<stdin>", line 1, in <module>
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/data/datastream.py", line 2318, in show
    for row in self.take(limit):
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/data/datastream.py", line 2276, in take
    for row in self.iter_rows():
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/data/iterator.py", line 234, in iter_rows
    for batch in self.iter_batches(**iter_batch_args):
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/data/iterator.py", line 167, in iter_batches
    block_iterator, stats, blocks_owned_by_consumer = self._to_block_iterator()
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/data/_internal/iterator/iterator_impl.py", line 33, in _to_block_iterator
    block_iterator, stats, executor = ds._plan.execute_to_iterator()
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/data/_internal/plan.py", line 512, in execute_to_iterator
    block_iter = itertools.chain([next(gen)], gen)
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/data/_internal/execution/legacy_compat.py", line 54, in execute_to_legacy_block_iterator
    for bundle in bundle_iter:
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/data/_internal/execution/interfaces.py", line 496, in __next__
    return self.get_next()
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 120, in get_next
    raise item
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 168, in run
    while self._scheduling_loop_step(self._topology) and not self._shutdown:
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 216, in _scheduling_loop_step
    process_completed_tasks(topology)
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor_state.py", line 328, in process_completed_tasks
    op.notify_work_completed(ref)
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/data/_internal/execution/operators/task_pool_map_operator.py", line 66, in notify_work_completed
    self._handle_task_done(task)
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 252, in _handle_task_done
    task.inputs.destroy_if_owned()
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/data/_internal/execution/interfaces.py", line 84, in destroy_if_owned
    trace_deallocation(b[0], "RefBundle.destroy_if_owned", free=should_free)
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/data/_internal/memory_tracing.py", line 48, in trace_deallocation
    ray._private.internal_api.free(ref, local_only=False)
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/_private/internal_api.py", line 211, in free
    worker.check_connected()
  File "/home/lzhi/miniconda3/lib/python3.8/site-packages/ray/_private/worker.py", line 611, in check_connected
    raise RaySystemError(
ray.exceptions.RaySystemError: System error: Ray has not been started yet. You can start Ray with 'ray.init()'.

### Versions / Dependencies

ray nightly

### Reproduction script

```python
import ray
ray.init(address="ray://localhost:10001")
ds = ray.data.range_arrow(10)
ds.show()
```

### Issue Severity

None

**Comment by raulchen** [comment]
This problem may not be easy to fix. Because based on current design, the driver is heavily involved in the execution. Can you wrap "ds.show()" in a remote task to work around this?

**Comment by kira-lin** [comment]
Yeah, I see. I'll just skip the related tests in RayDP if it's a behavior change
