### ISSUE TITLE
[Datasets] Import issue with `packaging` module in ray.data.extensions

### ISSUE THREAD

**Issue by jaychia** [ray-project/ray#34806]
### What happened + What you expected to happen

On a clean install of `pip install ray` in Python versions < 3.10

When importing `ray.data.extensions`, this fails with:

```
>>> import ray.data.extensions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jaychia/code/Daft/venv/lib/python3.8/site-packages/ray/data/extensions/__init__.py", line 1, in <module>
    from ray.data.extensions.tensor_extension import (
  File "/Users/jaychia/code/Daft/venv/lib/python3.8/site-packages/ray/data/extensions/tensor_extension.py", line 1, in <module>
    from ray.air.util.tensor_extensions.pandas import (  # noqa: F401
  File "/Users/jaychia/code/Daft/venv/lib/python3.8/site-packages/ray/air/util/tensor_extensions/pandas.py", line 35, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

### Versions / Dependencies

Python 3.8 (or any version of Python < 3.10)
Ray 2.4.0

### Reproduction script

```
import ray.data.extensions
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jaychia** [comment]
Digging a little further, this is because Ray `setup.py` declares the `packaging` dependency only for certain python versions:
https://github.com/ray-project/ray/blob/master/python/setup.py#L324
