### ISSUE TITLE
[Serve] Endless exception log when shutdown serve.

### ISSUE THREAD

**Issue by MissiontoMars** [ray-project/ray#34892]
### What happened + What you expected to happen

When shutdown serve, we got endless exception logs like the following:

Exception ignored in: <function RayServeHandle.__del__ at 0x7fce8b18cd40>
Traceback (most recent call last):
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/serve/handle.py", line 272, in __del__
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/serve/handle.py", line 176, in stop_metrics_pusher
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/serve/handle.py", line 269, in __getattr__
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/serve/handle.py", line 217, in options
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/serve/handle.py", line 145, in __init__
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/actor.py", line 138, in remote
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py", line 425, in _start_span
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/actor.py", line 184, in _remote
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/actor.py", line 177, in invocation
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/actor.py", line 1169, in _actor_method_call
AttributeError: 'Worker' object has no attribute 'core_worker'
Exception ignored in: <function RayServeHandle.__del__ at 0x7fce8b18cd40>
Traceback (most recent call last):
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/serve/handle.py", line 272, in __del__
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/serve/handle.py", line 176, in stop_metrics_pusher
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/serve/handle.py", line 269, in __getattr__
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/serve/handle.py", line 217, in options
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/serve/handle.py", line 145, in __init__
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/actor.py", line 138, in remote
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py", line 425, in _start_span
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/actor.py", line 184, in _remote
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/actor.py", line 177, in invocation
  File "/home/wangwanxing/miniconda3/envs/ray2.3/lib/python3.7/site-packages/ray/actor.py", line 1169, in _actor_method_call
AttributeError: 'Worker' object has no attribute 'core_worker'

### Versions / Dependencies

ray 2.3

### Reproduction script

```
import ray
from ray import serve
import time
import threading
from tqdm import tqdm
import os
import random

ray.init()

@serve.deployment(num_replicas=16, ray_actor_options={"num_cpus": 0.01})
class Model:
    def mode_call(self):
        import time
        time.sleep(0.2)
        return ""

serve.start(http_options={"port":12345})
Model.deploy()
func_handle = Model.get_handle()

def example():

    work_items = []
    for i in range(1000):
        work_items.append(1)
    from multiprocessing.pool import ThreadPool
    with ThreadPool(16) as pool:
        def _loop(from_num):
            mode_call = func_handle.mode_call
            ray.get(mode_call.remote())
            return '1'
        iter = pool.imap_unordered(_loop, work_items)
        idx_and_result = list(tqdm(iter, total=len(work_items), disable=False))

# shutdown serve in another thread
def shutdown():
    import time
    time.sleep(4)
    serve.shutdown()

my_t = threading.Thread(target=shutdown)
my_t.start()

example()

my_t.join()

import time
time.sleep(100000)
```

### Issue Severity

None

**Comment by MissiontoMars** [comment]
@sihanwang41
