### ISSUE TITLE
[dashboard] Dashboard error for cluster with CPU <1 with division by zero

### ISSUE THREAD

**Issue by bewestphal** [ray-project/ray#34895]
## What Happened
Attempting to start a Ray cluster on version 2.4.0 with CPU <1, a fractional number such as 0.5 creates a division by zero, immediately crashing the server.

```
2023-04-29 00:01:45,428	ERROR reporter_agent.py:1036 -- Error publishing node physical stats.
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 1019, in _perform_iteration
    stats = self._get_all_stats()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 605, in _get_all_stats
    "loadAvg": self._get_load_avg(),
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 572, in _get_load_avg
    per_cpu_load = tuple((round(x / self._cpu_counts[0], 2) for x in load))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 572, in <genexpr>
    per_cpu_load = tuple((round(x / self._cpu_counts[0], 2) for x in load))
ZeroDivisionError: float division by zero
2023-04-29 00:01:46,330	INFO web_log.py:206 -- 127.0.0.1 [29/Apr/2023:07:01:46 +0000] "GET /api/local_raylet_healthz HTTP/1.1" 200 163 "-" "Wget/1.20.3 (linux-gnu)"
2023-04-29 00:01:47,022	WARNING agent.py:517 -- Exiting with SIGTERM immediately...
```

## What's Expected

Clusters should allow fractional CPU <1. If this setup is not suggested create a warning but do not crash the entire server.

### Versions / Dependencies

Ray 2.4.0
Kuberay 0.5.0 (via helm chart)

### Reproduction script

Create a kuberay cluster where the headnode CPU is <1, some fractional number like 0.5

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

Leaving as medium because I think this could break some setups upgrading an existing <1 CPU setup. This also took going into the dashboard to diagnose the issue.

**Comment by alanwguo** [comment]
@rkooo567 , are you planning on looking at this? If this is a p0, do we need to get in for ray 2.7?

**Comment by rkooo567** [comment]
Let's go through all P0s in Th meeting and decide what to cherry pick>?

**Comment by rkooo567** [comment]
Hmm this seems irrelevant in 2.7 now. I couldn't start ray using `ray start --num_cpus=0.5` or  `ray.init(num_cpus=0.5)`

**Comment by rkooo567** [comment]
After a bit more work; 

1. It seems like the same error happens only when hardware cpu_counts == 0 (which should never happen?), not < 1
2. I couldn't reproduce the agent exiting (it just keeps failing at that point).

I will make a PR to handle cpu counts == 0 handled more gracefully, but maybe not additional work will be done here.
