### ISSUE TITLE
stress_test_many_tasks failed

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#34971]
```
INFO:__main__:Submitted 19960000
INFO:__main__:Submitted 19980000
Traceback (most recent call last):
  File "stress_tests/test_many_tasks.py", line 217, in <module>
    total_num_remote_cpus, smoke=is_smoke_test
  File "stress_tests/test_many_tasks.py", line 123, in stage3
    ray.get(x_ids)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py", line 2536, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
        class_name: Actor
        actor_id: c6b718fb0215a1e6db8ac14403000000
        pid: 248
        namespace: 75ce5879-c33a-49ca-a9ae-92461cfb3064
        ip: 10.0.22.142
The actor is dead because its node has died. Node Id: 2eea4cfb179ce7951c4bbdd5ba3029c3a4dcf7cb66db376084f7c270
Subprocess return code: 1
[INFO 2023-05-01 16:45:18,295] anyscale_job_wrapper.py: 190  Process 11264 exited with return code 1.
```

https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_i2sxqn3ae48l2b74invz7h3stn

**Comment by iycheng** [comment]
```
[2023-05-01 16:19:23,477 W 281 281] (gcs_server) gcs_health_check_manager.cc:108: Health check failed for node 2eea4cfb179ce7951c4bbdd5ba3029c3a4dcf7cb66db376084f7c270, remaining checks 4
[2023-05-01 16:19:36,478 W 281 281] (gcs_server) gcs_health_check_manager.cc:108: Health check failed for node 2eea4cfb179ce7951c4bbdd5ba3029c3a4dcf7cb66db376084f7c270, remaining checks 3
[2023-05-01 16:19:49,479 W 281 281] (gcs_server) gcs_health_check_manager.cc:108: Health check failed for node 2eea4cfb179ce7951c4bbdd5ba3029c3a4dcf7cb66db376084f7c270, remaining checks 2
[2023-05-01 16:20:02,480 W 281 281] (gcs_server) gcs_health_check_manager.cc:108: Health check failed for node 2eea4cfb179ce7951c4bbdd5ba3029c3a4dcf7cb66db376084f7c270, remaining checks 1
[2023-05-01 16:20:15,481 W 281 281] (gcs_server) gcs_health_check_manager.cc:108: Health check failed for node 2eea4cfb179ce7951c4bbdd5ba3029c3a4dcf7cb66db376084f7c270, remaining checks 0
[2023-05-01 16:20:15,481 W 281 281] (gcs_server) gcs_health_check_manager.cc:63: Node 2eea4cfb179ce7951c4bbdd5ba3029c3a4dcf7cb66db376084f7c270 is dead because the health check failed.
[2023-05-01 16:20:15,481 I 281 281] (gcs_server) gcs_node_manager.cc:212: Removing node, node id = 2eea4cfb179ce7951c4bbdd5ba3029c3a4dcf7cb66db376084f7c270, node name = 10.0.22.142
[2023-05-01 16:20:15,482 W 281 281] (gcs_server) gcs_node_manager.cc:237: The node with node id: 2eea4cfb179ce7951c4bbdd5ba3029c3a4dcf7cb66db376084f7c270 and address: 10.0.22.142 and node name: 10.0.22.142 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a  (1) raylet crashes unexpectedly (OOM, preempted node, etc.)
```

The health check failed for the raylet.

**Comment by iycheng** [comment]
Retry here:
https://buildkite.com/ray-project/release-tests-branch/builds/1628#0187dea9-ef37-4817-8847-ce02ad81d895

**Comment by iycheng** [comment]
Retry look OK

**Comment by jjyao** [comment]
Consistently passing now.
