### ISSUE TITLE
[RLlib] `ExternalMultiAgentEnv` yields error on `log_returns` with `multiagent_done_dict`

### ISSUE THREAD

**Issue by vec2k4** [ray-project/ray#35189]
### What happened + What you expected to happen

When using `log_returns` of the `ExternalMultiAgentEnv` with a provided `multiagent_done_dict`, an error is raised stating that `_ExternalEnvEpisode` has no `cur_done_dict` attribute.

Here is the full output:
```
Ray version: 2.3.1
Traceback (most recent call last):
  File "./07_external_multienv_github_issue.py", line 6, in <module>
    env.log_returns(eid, { "policy": 1.0 }, {}, { "policy": True})
  File "./venv/lib/python3.10/site-packages/ray/rllib/env/external_multi_agent_env.py", line 154, in log_returns
    episode.cur_done_dict[agent] = done
AttributeError: '_ExternalEnvEpisode' object has no attribute 'cur_done_dict'. Did you mean: 'cur_info_dict'?
```

The problem seems to be [here](https://github.com/ray-project/ray/blob/cc3fa331b8599c86da0078bce93fe6d84dba1f87/rllib/env/external_multi_agent_env.py#L154) and/or [here](https://github.com/ray-project/ray/blob/cc3fa331b8599c86da0078bce93fe6d84dba1f87/rllib/env/external_env.py#L260-L266).

### Versions / Dependencies

Ray version: 2.3.1
Python: 3.10
Windows 10 using WSL with Ubuntu 22.04.2 LTS

### Reproduction script

Really simple example without `PolicyServerInput` & `PolicyClient`. The snippet outputs the formerly mentioned error.

```python
from ray.rllib.env.external_multi_agent_env import ExternalMultiAgentEnv
from gymnasium.spaces import Discrete, Box
import ray

print("Ray version:", ray.__version__)

env = ExternalMultiAgentEnv(Discrete(2), Box(float("-inf"), float("inf"), (1,)))
eid = env.start_episode(training_enabled=True)
env.log_returns(eid, { "policy": 1.0 }, {}, { "policy": True})
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by MatFl** [comment]
I am facing the same issue.

**Comment by Paolo-Fermin** [comment]
Is there any progress on this issue? I am running into the same bug.
