### ISSUE TITLE
Unable to create ros2 context using rclpy when running script in remote node. 

### ISSUE THREAD

**Issue by SridharPandian** [ray-project/ray#35195]
Hi!
I am currently working on creating a ray task which can be run in parallel across many machines in the same network. This task depends on rclpy (from ROS2). All the nodes in the network have ros2 galactic installed and sourced along with ray and the other python dependencies in a pip venv. This is the script that I used on the head node.
```
import ray
import rclpy

@ray.remote
def run_eval():
    rclpy.init()
    # Insert other code here
    rclpy.shutdown()

def main():
    runtime_env = {"working_dir": "."}
    ray.init(address='auto', runtime_env=runtime_env)
    futures = [run_eval.remote()]
    ray.get(futures)
    ray.shutdown()
```
I used the command `ray start --head --num-cpus=1 --num-gpus=1` to start the head node and `ray start --address=<address>: <port>` on the remote nodes after initialzing the python venvs and sourcing the ros packages.

This script works on the head node and does not work on the remote nodes (crashes on the line where rclpy is initialized). Here is the error:
```
2023-05-09 13:47:41,057	INFO worker.py:1364 -- Connecting to existing Ray cluster at address: <HEAD_IP>:6379...
2023-05-09 13:47:41,065	INFO worker.py:1553 -- Connected to Ray cluster.
2023-05-09 13:47:41,276	INFO packaging.py:503 -- Creating a file package for local directory '/home/sridhar/repos/<script_repo>'.
2023-05-09 13:47:41,516	INFO packaging.py:330 -- Pushing file package 'gcs://_ray_pkg_73987ba3027b2f32.zip' (105.73MiB) to Ray cluster...
2023-05-09 13:47:42,520	INFO packaging.py:343 -- Successfully pushed file package 'gcs://_ray_pkg_73987ba3027b2f32.zip'.
3 nodes have joined the network...
Traceback (most recent call last):
  File "scripts/distributed_eval.py", line 127, in <module>
    app.run(main)
  File "/home/sridhar/repos/ros-visual-nav/venv/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/sridhar/repos/ros-visual-nav/venv/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "scripts/distributed_eval.py", line 123, in main
    ray.get(futures)
  File "/home/sridhar/repos/ros-visual-nav/venv/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/sridhar/repos/ros-visual-nav/venv/lib/python3.8/site-packages/ray/_private/worker.py", line 2380, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RCLError): ray::run_eval() (pid=395720, ip=<CHILD_IP>)
AttributeError: 'Context' object has no attribute '_Context__context'

During handling of the above exception, another exception occurred:

ray::run_eval() (pid=395720, ip=<HEAD_IP>)
  File "scripts/distributed_eval.py", line 46, in run_eval
    rclpy.init()
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/__init__.py", line 76, in init
    return context.init(args, domain_id=domain_id)
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/context.py", line 72, in init
    self.__context = _rclpy.Context(
rclpy._rclpy_pybind11.RCLError: Failed to initialize init options: failed to load shared library 'librmw_cyclonedds_cpp.so' due to dlopen error: librmw_cyclonedds_cpp.so: cannot open shared object file: No such file or directory, at /tmp/binarydeb/ros-galactic-rcutils-4.0.4/src/shared_library.c:99, at /tmp/binarydeb/ros-galactic-rmw-implementation-2.4.1/src/functions.cpp:75, at /tmp/binarydeb/ros-galactic-rcl-3.1.4/src/rcl/init_options.c:75
(raylet, ip=<CHILD_IP>) [2023-05-09 13:47:43,180 E 1557721 1557840] (raylet) file_system_monitor.cc:105: /tmp/ray/session_2023-05-09_11-03-34_634222_1501810 is over 95% full, available space: 14798692352; capacity: 383136198656. Object creation will fail if spilling is required.
```

All the nodes have the following installed:
1. Ubuntu 20.04
2. [ROS2 Galactic](https://docs.ros.org/en/galactic/Installation/Ubuntu-Install-Debians.html)
3. ray 2.3.0

Also, all the other environment variables such as the `LD_LIBRARY_PATH` are correct. Help with figuring out the issue will be much appreciated. Thanks!

**Comment by richardliaw** [comment]
Hey! Could you try moving the ros library import into the ray.remote function?

**Comment by richardliaw** [comment]
also is ros2 installed on worker nodes? the error says the shared library is not found, which suggests a different compute environment

**Comment by SridharPandian** [comment]
Hey Richard! Thanks for responding. I tried moving the ros imports inside the ray.remote task function. Sadly, it didn't seem to work. Also, ros2 is indeed installed and sourced in all the worker nodes. When I run the remote task function, I am able to import rclpy in the remote node, but not able to initialize the context.

**Comment by richardliaw** [comment]
There seems to be an attribute error first -- can you make sure this is expected?

```
ray.exceptions.RayTaskError(RCLError): ray::run_eval() (pid=395720, ip=<CHILD_IP>)
AttributeError: 'Context' object has no attribute '_Context__context'
```

Looking at https://github.com/ros2/rclpy/blob/rolling/rclpy/rclpy/context.py there doesn't seem to be a `_Context__context` variable in the codebase.
