### ISSUE TITLE
[Cluster launcher] GCP `example-gpu-docker.yaml` fails setup commands waiting for `nvidia-smi`

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#35266]
### What happened + What you expected to happen

The head setup commands fail, causing the cluster to fail to be launched.

This message repeats until the timeout of 300 seconds.  Perhaps we just need to increase the timeout.
```
/usr/bin/nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```
Here's the final error message:
```
/usr/bin/nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

/usr/bin/nvidia-smi
Connection to 35.197.18.246 closed.
2023-05-11 10:56:14,783 INFO node.py:311 -- wait_for_compute_zone_operation: Waiting for operation operation-1683827774568-5fb6eb45db675-806a19f1-6710500a to finish...
2023-05-11 10:56:20,069 INFO node.py:330 -- wait_for_compute_zone_operation: Operation operation-1683827774568-5fb6eb45db675-806a19f1-6710500a finished.
  New status: update-failed
  !!!
  {'message': 'SSH command failed.'}
  SSH command failed.
  !!!
  
  Failed to setup head node.
Traceback (most recent call last):
  File "/Users/archit/ray/python/ray/autoscaler/launch_and_verify_cluster.py", line 218, in <module>
    run_ray_commands(cluster_config, retries, no_config_cache)
  File "/Users/archit/ray/python/ray/autoscaler/launch_and_verify_cluster.py", line 124, in run_ray_commands
    subprocess.run(cmd, check=True)
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ray', 'up', '-v', '-y', '--no-config-cache', '/var/folders/75/7kpb8gj57k11df4ksj9lnt900000gn/T/tmp9bsxmi8j.yaml']' returned non-zero exit status 1.
```
### Versions / Dependencies

Client: MacOS, Python 3.8

### Reproduction script

```bash
python/ray/autoscaler/launch_and_verify_cluster.py python/ray/autoscaler/gcp/example-gpu-docker.yaml
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by PaulFenton** [comment]
I'm also experiencing the same issue when trying to adopt aspects of the `example-gpu-docker.yaml` cluster config.

**Comment by PaulFenton** [comment]
I was eventually able to get past this issue by using `machineType: n1-standard-2`, `sourceImage: projects/deeplearning-platform-release/global/images/family/common-cu113`, and `acceleratorType: nvidia-tesla-t4`.  Here is the full `ray_head_gpu` node type spec I used to modify `example-gpu-docker.yaml`:
```
ray_head_gpu:
    # The resources provided by this node type.
    resources: {"CPU": 2, "GPU": 1}
    # Provider-specific config for the head node, e.g. instance type. By default
    # Ray will auto-configure unspecified fields such as subnets and ssh-keys.
    # For more documentation on available fields, see:
    # https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert
    node_config:
        machineType: n1-standard-2
        disks:
          - boot: true
            autoDelete: true
            type: PERSISTENT
            initializeParams:
              diskSizeGb: 50
              # See https://cloud.google.com/compute/docs/images for more images
              sourceImage: projects/deeplearning-platform-release/global/images/family/common-cu113
        # Make sure to set scheduling->onHostMaintenance to TERMINATE when GPUs are present
        guestAccelerators:
          - acceleratorType: nvidia-tesla-t4
            acceleratorCount: 1
        metadata:
          items:
            - key: install-nvidia-driver
              value: "True"
        scheduling:
          - onHostMaintenance: TERMINATE
```

 I also made similar changes to `ray_worker_gpu`.
