### ISSUE TITLE
RAY Serve: AttributeError: module 'pynvml' has no attribute '_nvmlGetFunctionPointer'

### ISSUE THREAD

**Issue by illyakaynov** [ray-project/ray#35384]
### What happened + What you expected to happen

I am running official pytorch nvidia image 22.04. Using ray serve to start the model serving and getting this error. From what I can tell the dashboard crashes and my code is not even reached.

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/ray/dashboard/dashboard.py", line 240, in <module>
    raise e
  File "/opt/conda/lib/python3.8/site-packages/ray/dashboard/dashboard.py", line 228, in <module>
    loop.run_until_complete(dashboard.run())
  File "/opt/conda/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.8/site-packages/ray/dashboard/dashboard.py", line 70, in run
    await self.dashboard_head.run()
  File "/opt/conda/lib/python3.8/site-packages/ray/dashboard/head.py", line 297, in run
    modules = self._load_modules(self._modules_to_load)
  File "/opt/conda/lib/python3.8/site-packages/ray/dashboard/head.py", line 204, in _load_modules
    head_cls_list = dashboard_utils.get_all_modules(DashboardHeadModule)
  File "/opt/conda/lib/python3.8/site-packages/ray/dashboard/utils.py", line 121, in get_all_modules
    importlib.import_module(name)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 52, in <module>
    import gpustat.core as gpustat
  File "/opt/conda/lib/python3.8/site-packages/gpustat/__init__.py", line 16, in <module>
    from .core import GPUStat, GPUStatCollection
  File "/opt/conda/lib/python3.8/site-packages/gpustat/core.py", line 24, in <module>
    from gpustat.nvml import pynvml as N
  File "/opt/conda/lib/python3.8/site-packages/gpustat/nvml.py", line 57, in <module>
    _original_nvmlGetFunctionPointer = pynvml._nvmlGetFunctionPointer
AttributeError: module 'pynvml' has no attribute '_nvmlGetFunctionPointer'

### Versions / Dependencies

ray==2.3.1
gpustat==1.1

### Reproduction script

Downgrading to gpustat==1.0.0 solved the issue. I have spend 3 full days on this problem so I want some other people to find this solution.

### Issue Severity

High: It blocks me from completing my task.

**Comment by zakajd** [comment]
+1 
observe same problem when running AWS Deep Learning AMI with ray==2.4.0

**Comment by robcaulk** [comment]
I confirm same issue running simple Ray Core locally with installation ray["default"]==2.4.0 on Ubuntu 22.04.

Running with ray==2.4.0 works, but the dashboard is not installed with this version. So seems to have something to do with the dashboard.

Downgrading to `gpustat==1.0.0` solved it for me as well.

I should note that this sandbox server does not have a gpu installed.

**Comment by fostiropoulos** [comment]
error persists.

**Comment by davidxia** [comment]
I saw the same error with kuberay 1.0.0 creating K8s RayClusters running Ray 2.9.2 with gpustat 1.1.1 installed. This error
causes the head Pod's ray-head Container to fail the K8s liveness and readiness probes because the Ray dashboard isn't listening on the assigned port.

Pinning gpustat to 1.0.0 fixed it.

```
❯ kubectl get pods

NAME                                                      READY   STATUS                  RESTARTS   AGE
dxia-ray-29-test-head-mkksc                               1/2     Running                 0          156m
dxia-ray-29-test-worker-worker-2vl55                      0/2     Init:1/2                0          156m

❯ kubectl logs -f dxia-ray-29-test-head-mkksc

Defaulted container "ray-head" out of: ray-head, fluentbit
2024-02-20 08:27:09,343	ERROR services.py:1329 -- Failed to start the dashboard , return code 1
2024-02-20 08:27:09,343	ERROR services.py:1354 -- Error should be written to 'dashboard.log' or 'dashboard.err'. We are printing the last 20 lines for you. See 'https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure' to find where the log file is.
2024-02-20 08:27:09,343	ERROR services.py:1398 --
The last 20 lines of /tmp/ray/session_2024-02-20_08-27-07_182583_8/logs/dashboard.log (it contains the error message from the dashboard):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/dashboard/utils.py", line 121, in get_all_modules
    importlib.import_module(name)
  File "/home/ray/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 52, in <module>
    import gpustat.core as gpustat
  File "/home/ray/anaconda3/lib/python3.9/site-packages/gpustat/__init__.py", line 16, in <module>
    from .core import GPUStat, GPUStatCollection
  File "/home/ray/anaconda3/lib/python3.9/site-packages/gpustat/core.py", line 24, in <module>
    from gpustat.nvml import pynvml as N
  File "/home/ray/anaconda3/lib/python3.9/site-packages/gpustat/nvml.py", line 57, in <module>
    _original_nvmlGetFunctionPointer = pynvml._nvmlGetFunctionPointer
AttributeError: module 'pynvml' has no attribute '_nvmlGetFunctionPointer'
2024-02-20 08:27:07,181	INFO usage_lib.py:423 -- Usage stats collection is disabled.
2024-02-20 08:27:07,181	INFO scripts.py:744 -- Local node IP: 10.169.18.195
2024-02-20 08:27:09,471	SUCC scripts.py:781 -- --------------------
2024-02-20 08:27:09,471	SUCC scripts.py:782 -- Ray runtime started.
2024-02-20 08:27:09,472	SUCC scripts.py:783 -- --------------------
2024-02-20 08:27:09,472	INFO scripts.py:785 -- Next steps
2024-02-20 08:27:09,472	INFO scripts.py:788 -- To add another node to this Ray cluster, run
2024-02-20 08:27:09,472	INFO scripts.py:791 --   ray start --address='10.169.18.195:6379'
2024-02-20 08:27:09,472	INFO scripts.py:800 -- To connect to this Ray cluster:
2024-02-20 08:27:09,472	INFO scripts.py:802 -- import ray
2024-02-20 08:27:09,472	INFO scripts.py:803 -- ray.init()
2024-02-20 08:27:09,472	INFO scripts.py:834 -- To terminate the Ray runtime, run
2024-02-20 08:27:09,472	INFO scripts.py:835 --   ray stop
2024-02-20 08:27:09,472	INFO scripts.py:838 -- To view the status of the cluster, use
2024-02-20 08:27:09,472	INFO scripts.py:839 --   ray status
2024-02-20 08:27:09,473	INFO scripts.py:952 -- --block
2024-02-20 08:27:09,474	INFO scripts.py:953 -- This command will now block forever until terminated by a signal.
2024-02-20 08:27:09,474	INFO scripts.py:956 -- Running subprocesses are monitored and a message will be printed if any of them terminate unexpectedly. Subprocesses exit with SIGTERM will be treated as graceful, thus NOT reported.

❯ kubectl describe pods dxia-ray-29-test-head-mkksc

Name:                 dxia-ray-29-test-head-mkksc
Namespace:            hyperkube
Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Warning  Unhealthy  3m52s (x24 over 143m)  kubelet  Readiness probe errored: command "bash -c wget -T 2 -q -O- http://localhost:52365/api/local_raylet_healthz | grep success && wget -T 2 -q -O- http://localhost:8265/api/gcs_healthz | grep success" timed out
  Warning  Unhealthy  3m32s (x24 over 142m)  kubelet  Liveness probe errored: command "bash -c wget -T 2 -q -O- http://localhost:52365/api/local_raylet_healthz | grep success && wget -T 2 -q -O- http://localhost:8265/api/gcs_healthz | grep success" timed out
```

**Comment by anyscalesam** [comment]
@can-anyscale what's our gpustats pin now in latest ray images release with ray29?

**Comment by can-anyscale** [comment]
@anyscalesam it was 1.1.1 for ray29 (https://github.com/ray-project/ray/blob/releases/2.9.3/python/requirements_compiled.txt#L636)

**Comment by jjyao** [comment]
Latest Ray doesn't depend on gpustats anymore: #41399
