### ISSUE TITLE
[ml][release-test] air_example_gptj_deepspeed_fine_tuning.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#35423]
### What happened + What you expected to happen

air_example_gptj_deepspeed_fine_tuning.aws is failing consistently

https://buildkite.com/ray-project/release-tests-branch/builds/1650#0188142d-408c-4df3-9bdc-b63d7b463125

[Bisect](https://buildkite.com/ray-project/release-tests-bisect/builds/154#_) blamed this https://github.com/ray-project/ray/commit/bfd6a63fbbae51f79eb738643361ee3b15f7a146. Please help review and resolve the issue.

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/1650#0188142d-408c-4df3-9bdc-b63d7b463125

### Issue Severity

High: It blocks me from completing my task.

**Comment by woshiyyya** [comment]
hmm. There are no logs in the anyscale job page.

By the way, maybe we can remove the release test of ray_lightning? @matthewdeng

**Comment by woshiyyya** [comment]
```python
2023-05-13 01:52:46,342 ERROR tune_controller.py:859 -- Trial task failed
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 18, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/worker.py", line 2518, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): ray::_Inner.train() (pid=24386, ip=10.0.16.114, actor_id=0f3b6cac57dec24813e64f1402000000, repr=TransformersTrainer)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 388, in train
    raise skipped from exception_cause(skipped)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 54, in check_for_failure
    ray.get(object_ref)
ray.exceptions.RayTaskError(AssertionError): ray::_RayTrainWorker__execute.get_next() (pid=4815, ip=10.0.49.30, actor_id=862ab78426c5717f0525c77902000000, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x7fc6e7c3b2b0>)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/worker_group.py", line 32, in __execute
    raise skipped from exception_cause(skipped)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 129, in discard_return_wrapper
    train_func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/hf_transformers/transformers_trainer.py", line 390, in _huggingface_train_loop_per_worker
    trainer: transformers.trainer.Trainer = trainer_init_per_worker(
  File "/tmp/tmp4_9lv1ws", line 336, in trainer_init_per_worker
  File "/home/ray/anaconda3/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2606, in from_pretrained
    init_contexts = [deepspeed.zero.Init(config_dict_or_path=deepspeed_config())] + init_contexts
  File "/home/ray/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 724, in __init__
    _ds_config = deepspeed.runtime.config.DeepSpeedConfig(config_dict_or_path,
  File "/home/ray/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/config.py", line 764, in __init__
    self._configure_train_batch_size()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/config.py", line 937, in _configure_train_batch_size
    self._batch_assertion()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/config.py", line 885, in _batch_assertion
    assert train_batch == micro_batch * grad_acc * self.world_size, (
AssertionError: Check batch related parameters. train_batch_size is not equal to micro_batch_per_gpu * gradient_acc_step * world_size 256 != 16 * 1 * 1
```

It seems that deepspeed doesn't recognize world_size correctly. (should have been 16 but turned out to be 1). cc @Yard1

**Comment by woshiyyya** [comment]
@gjoliver seems to related to version imcompatibility between accelerate and deepspeed. Maybe we can pin deepspeed<0.9

https://github.com/OpenGVLab/InternImage/issues/111

**Comment by Yard1** [comment]
this should be fixed by deepspeed==0.9.1, is that not the case? https://github.com/microsoft/DeepSpeed/issues/3228

**Comment by can-anyscale** [comment]
@gjoliver

**Comment by ArturNiederfahrenhorst** [comment]
@can-anyscale Is this resolved? The issue is still open but I see the PR has been merged :)

**Comment by can-anyscale** [comment]
@ArturNiederfahrenhorst it is resolved!
