### ISSUE TITLE
Ray component: Data - Incorrectly detects snappy decoding

### ISSUE THREAD

**Issue by jbpdl22** [ray-project/ray#35497]
### What happened + What you expected to happen

I have hadoop snappy compressed files (EMR, Databricks) in s3.  Ray fails to recognize these as hadhoop snappy.  I see in the code that some attempt was made to accomodate this but I don't see a way to explicitly specify that the files are hadoop snappy when reading.  I would expect Ray to either correctly detect the format or else allow me to specify. 

### Versions / Dependencies

2.4

### Reproduction script

ds = data.read_text("s3://some_hadoop_snappy_files")
ds.show()

### Issue Severity

High: It blocks me from completing my task.

**Comment by amogkam** [comment]
@jbpdl22 what do your file names look like? Do they end in `.snappy` suffix?

If they do, as you said, there is detection for this with the Ray Data read logic.

**Comment by amogkam** [comment]
Also what `read` API are you using?

**Comment by jbpdl22** [comment]
Yes, files end with .snappy.  I'm using data.read_text.

**Comment by amogkam** [comment]
Unfortunately I am not able to reproduce @jbpdl22. How are you determining that snappy compression is not being detected?

Are you share an example file?

**Comment by jbpdl22** [comment]
Let me see if I can create an example with some sample data for you, I can't share the files I was trying to read.  I think its the wrong snappy because while it detected that it was snappy compressed (originally it complained that it couldn't import snappy) it failed to decompress it.  I've had this trouble before in python with hadoop compressed snappy.

**Comment by amogkam** [comment]
If you could also share the stack trade you are getting, that would be great

**Comment by jbpdl22** [comment]
[part-00023-tid-4714779310635191706-b0a49336-359a-44e7-b39d-d42f89b4e3ea-21456-1-c000.txt.snappy.zip](https://github.com/ray-project/ray/files/11512238/part-00023-tid-4714779310635191706-b0a49336-359a-44e7-b39d-d42f89b4e3ea-21456-1-c000.txt.snappy.zip)

Note that I had to zip the file to upload to github.  Unzip before testing.

**Comment by amogkam** [comment]
thanks, is this the error you are getting?

```
RayTaskError(AttributeError): ray::_execute_read_task_split() (pid=80882, ip=127.0.0.1)
  File "/Users/amog/dev/ray/python/ray/data/_internal/lazy_block_list.py", line 689, in _execute_read_task_split
    for block in blocks:
  File "/Users/amog/dev/ray/python/ray/data/datasource/datasource.py", line 214, in __call__
    for block in result:
  File "/Users/amog/dev/ray/python/ray/data/datasource/file_based_datasource.py", line 492, in read_files
    for data in read_stream(f, read_path, **reader_args):
  File "/Users/amog/dev/ray/python/ray/data/datasource/file_based_datasource.py", line 243, in _read_stream
    yield self._read_file(f, path, **reader_args)
  File "/Users/amog/dev/ray/python/ray/data/datasource/text_datasource.py", line 21, in _read_file
    block = super()._read_file(f, path, **reader_args)
  File "/Users/amog/dev/ray/python/ray/data/datasource/binary_datasource.py", line 40, in _read_file
    snappy.stream_decompress(src=f, dst=rawbytes)
AttributeError: module 'snappy' has no attribute 'stream_decompress'
```

**Comment by jbpdl22** [comment]
```
(DoRead pid=34274) 2023-05-18 16:29:32,022      INFO worker.py:844 -- Task failed with retryable exception: TaskID(e4ecaa1c2146246affffffffffffffffffffffff01000000).
(DoRead pid=34274) Traceback (most recent call last):
(DoRead pid=34274)   File "python/ray/_raylet.pyx", line 653, in ray._raylet.execute_dynamic_generator_and_store_task_outputs
(DoRead pid=34274)   File "python/ray/_raylet.pyx", line 2537, in ray._raylet.CoreWorker.store_task_outputs
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 375, in _map_task
(DoRead pid=34274)     for b_out in fn(iter(blocks), ctx):
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/legacy_compat.py", line 219, in do_read
(DoRead pid=34274)     yield from read_task()
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/datasource.py", line 216, in __call__
(DoRead pid=34274)     for block in result:
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 490, in read_files
(DoRead pid=34274)     for data in read_stream(f, read_path, **reader_args):
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 242, in _read_stream
(DoRead pid=34274)     yield self._read_file(f, path, **reader_args)
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/text_datasource.py", line 21, in _read_file
(DoRead pid=34274)     block = super()._read_file(f, path, **reader_args)
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/binary_datasource.py", line 40, in _read_file
(DoRead pid=34274)     snappy.stream_decompress(src=f, dst=rawbytes)
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/snappy/snappy.py", line 321, in stream_decompress
(DoRead pid=34274)     buf = decompressor.decompress(buf)
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/snappy/snappy.py", line 235, in decompress
(DoRead pid=34274)     raise UncompressError("stream missing snappy identifier")
(DoRead pid=34274) snappy.UncompressError: stream missing snappy identifier
(DoRead pid=34274) 2023-05-18 16:29:32,809      INFO worker.py:844 -- Task failed with retryable exception: TaskID(e4ecaa1c2146246affffffffffffffffffffffff01000000).
(DoRead pid=34274) Traceback (most recent call last):
(DoRead pid=34274)   File "python/ray/_raylet.pyx", line 653, in ray._raylet.execute_dynamic_generator_and_store_task_outputs
(DoRead pid=34274)   File "python/ray/_raylet.pyx", line 2537, in ray._raylet.CoreWorker.store_task_outputs
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 375, in _map_task
(DoRead pid=34274)     for b_out in fn(iter(blocks), ctx):
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/legacy_compat.py", line 219, in do_read
(DoRead pid=34274)     yield from read_task()
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/datasource.py", line 216, in __call__
(DoRead pid=34274)     for block in result:
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 490, in read_files
(DoRead pid=34274)     for data in read_stream(f, read_path, **reader_args):
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 242, in _read_stream
(DoRead pid=34274)     yield self._read_file(f, path, **reader_args)
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/text_datasource.py", line 21, in _read_file
(DoRead pid=34274)     block = super()._read_file(f, path, **reader_args)
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/binary_datasource.py", line 40, in _read_file
(DoRead pid=34274)     snappy.stream_decompress(src=f, dst=rawbytes)
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/snappy/snappy.py", line 321, in stream_decompress
(DoRead pid=34274)     buf = decompressor.decompress(buf)
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/snappy/snappy.py", line 235, in decompress
(DoRead pid=34274)     raise UncompressError("stream missing snappy identifier")
(DoRead pid=34274) snappy.UncompressError: stream missing snappy identifier
(DoRead pid=34274) 2023-05-18 16:29:33,793      INFO worker.py:844 -- Task failed with retryable exception: TaskID(e4ecaa1c2146246affffffffffffffffffffffff01000000).
(DoRead pid=34274) Traceback (most recent call last):
(DoRead pid=34274)   File "python/ray/_raylet.pyx", line 653, in ray._raylet.execute_dynamic_generator_and_store_task_outputs
(DoRead pid=34274)   File "python/ray/_raylet.pyx", line 2537, in ray._raylet.CoreWorker.store_task_outputs
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 375, in _map_task
(DoRead pid=34274)     for b_out in fn(iter(blocks), ctx):
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/legacy_compat.py", line 219, in do_read
(DoRead pid=34274)     yield from read_task()
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/datasource.py", line 216, in __call__
(DoRead pid=34274)     for block in result:
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 490, in read_files
(DoRead pid=34274)     for data in read_stream(f, read_path, **reader_args):
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 242, in _read_stream
(DoRead pid=34274)     yield self._read_file(f, path, **reader_args)
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/text_datasource.py", line 21, in _read_file
(DoRead pid=34274)     block = super()._read_file(f, path, **reader_args)
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/binary_datasource.py", line 40, in _read_file
(DoRead pid=34274)     snappy.stream_decompress(src=f, dst=rawbytes)
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/snappy/snappy.py", line 321, in stream_decompress
(DoRead pid=34274)     buf = decompressor.decompress(buf)
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/snappy/snappy.py", line 235, in decompress
(DoRead pid=34274)     raise UncompressError("stream missing snappy identifier")
(DoRead pid=34274) snappy.UncompressError: stream missing snappy identifier
(DoRead pid=34274) 2023-05-18 16:29:34,834      INFO worker.py:844 -- Task failed with retryable exception: TaskID(e4ecaa1c2146246affffffffffffffffffffffff01000000).
(DoRead pid=34274) Traceback (most recent call last):
(DoRead pid=34274)   File "python/ray/_raylet.pyx", line 653, in ray._raylet.execute_dynamic_generator_and_store_task_outputs
(DoRead pid=34274)   File "python/ray/_raylet.pyx", line 2537, in ray._raylet.CoreWorker.store_task_outputs
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 375, in _map_task
(DoRead pid=34274)     for b_out in fn(iter(blocks), ctx):
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/legacy_compat.py", line 219, in do_read
(DoRead pid=34274)     yield from read_task()
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/datasource.py", line 216, in __call__
(DoRead pid=34274)     for block in result:
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 490, in read_files
(DoRead pid=34274)     for data in read_stream(f, read_path, **reader_args):
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 242, in _read_stream
(DoRead pid=34274)     yield self._read_file(f, path, **reader_args)
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/text_datasource.py", line 21, in _read_file
(DoRead pid=34274)     block = super()._read_file(f, path, **reader_args)
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/datasource/binary_datasource.py", line 40, in _read_file
(DoRead pid=34274)     snappy.stream_decompress(src=f, dst=rawbytes)
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/snappy/snappy.py", line 321, in stream_decompress
(DoRead pid=34274)     buf = decompressor.decompress(buf)
(DoRead pid=34274)   File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/snappy/snappy.py", line 235, in decompress
(DoRead pid=34274)     raise UncompressError("stream missing snappy identifier")
(DoRead pid=34274) snappy.UncompressError: stream missing snappy identifier
Traceback (most recent call last):                                                                                                              
  File "/Users/someone/Projects/myproject/src/project/builds/person/ray_jobs/snappy_test.py", line 6, in <module>
    ds.show()
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/dataset.py", line 2295, in show
    for row in self.take(limit):
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/dataset.py", line 2251, in take
    for row in self.iter_rows():
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/dataset_iterator.py", line 232, in iter_rows
    for batch in self.iter_batches(**iter_batch_args):
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/dataset_iterator.py", line 165, in iter_batches
    block_iterator, stats, blocks_owned_by_consumer = self._to_block_iterator()
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/dataset_iterator/dataset_iterator_impl.py", line 31, in _to_block_iterator
    block_iterator, stats, executor = ds._plan.execute_to_iterator()
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/plan.py", line 530, in execute_to_iterator
    block_iter = itertools.chain([next(gen)], gen)
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/legacy_compat.py", line 49, in execute_to_legacy_block_iterator
    for bundle in bundle_iter:
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/interfaces.py", line 484, in __next__
    return self.get_next()
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py", line 111, in get_next
    raise item
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py", line 157, in run
    while self._scheduling_loop_step(self._topology) and not self._shutdown:
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py", line 205, in _scheduling_loop_step
    process_completed_tasks(topology)
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor_state.py", line 312, in process_completed_tasks
    op.notify_work_completed(ref)
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/task_pool_map_operator.py", line 65, in notify_work_completed
    task.output = self._map_ref_to_ref_bundle(ref)
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 317, in _map_ref_to_ref_bundle
    all_refs = list(ray.get(ref))
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/_private/worker.py", line 2521, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(UncompressError): ray::DoRead() (pid=34274, ip=127.0.0.1)
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 375, in _map_task
    for b_out in fn(iter(blocks), ctx):
  File "/Users/someone/Library/Caches/pypoetry/virtualenvs/myproject-requirements-buuWtXoa-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/legacy_compat.py", line 219, in do_read
```

**Comment by amogkam** [comment]
Thanks, @jbpdl22. I believe there is some issue in your snappy file. I couldn't decompress it using snappy directly.

```
>>> import snappy
>>> file = open("./part-00023-tid-4714779310635191706-b0a49336-359a-44e7-b39d-d42f89b4e3ea-21456-1-c000.txt.snappy")
>>> snappy.stream_decompress(src=file, dst=rawbytes)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/amog/miniforge3/envs/ray/lib/python3.8/site-packages/snappy/snappy.py", line 321, in stream_decompress
    buf = decompressor.decompress(buf)
  File "/Users/amog/miniforge3/envs/ray/lib/python3.8/site-packages/snappy/snappy.py", line 235, in decompress
    raise UncompressError("stream missing snappy identifier")
snappy.UncompressError: stream missing snappy identifier
```

```
 >>> import snappy
>>> file = open("./part-00023-tid-4714779310635191706-b0a49336-359a-44e7-b39d-d42f89b4e3ea-21456-1-c000.txt.snappy")
>>> data = file.read()
>>> snappy.decompress(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/amog/miniforge3/envs/ray/lib/python3.8/site-packages/snappy/snappy.py", line 92, in uncompress
    return _uncompress(data)
snappy.UncompressError: Error while decompressing: invalid input
```

**Comment by jbpdl22** [comment]
The file is fine.  Its hadoop snappy.  

```
❯ python
Python 3.9.13 (main, Jun 22 2022, 09:14:33) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import snappy
>>> with open("part-00023-tid-4714779310635191706-b0a49336-359a-44e7-b39d-d42f89b4e3ea-21456-1-c000.txt.snappy", "rb") as f:
...     data = f.read()
...     decompressor = snappy.hadoop_snappy.StreamDecompressor()
...     uncompressed = decompressor.decompress(data)
... 
>>> uncompressed
b'bar\n'
```
