### ISSUE TITLE
[M1 Installation] Ray cannot be imported after installation due to gRPC

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#35509]
### Description

After following [the Apple M1 installation directions](https://docs.ray.io/en/releases-2.4.0/ray-overview/installation.html#m1-mac-apple-silicon-support) on a fresh Conda environment, I was unable to import Ray:

```python
>>> import ray
Traceback (most recent call last):
  File "/Users/shrekris/miniforge3/envs/aehf/lib/python3.10/site-packages/ray/__init__.py", line 63, in _configure_system
    import grpc  # noqa: F401
  File "/Users/shrekris/miniforge3/envs/aehf/lib/python3.10/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/shrekris/miniforge3/envs/aehf/lib/python3.10/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/shrekris/miniforge3/envs/aehf/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 2): Symbol not found: _CFRelease
  Referenced from: /Users/shrekris/miniforge3/envs/aehf/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so
  Expected in: flat namespace
 in /Users/shrekris/miniforge3/envs/aehf/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shrekris/miniforge3/envs/aehf/lib/python3.10/site-packages/ray/__init__.py", line 101, in <module>
    _configure_system()
  File "/Users/shrekris/miniforge3/envs/aehf/lib/python3.10/site-packages/ray/__init__.py", line 65, in _configure_system
    raise ImportError(
ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.
```

I expect the instructions in the docs to include the `pip uninstall grpcio; conda install grpcio` instruction if it's necessary.

### Link

https://docs.ray.io/en/releases-2.4.0/ray-overview/installation.html#m1-mac-apple-silicon-support

**Comment by shrekris-anyscale** [comment]
Switching steps 3 and 4 seem to fix the issue. I'll follow up with a doc fix.

```console
% pip install ray
...

% python
>>> import ray
Traceback (most recent call last):
  File "/Users/shrekris/miniforge3/envs/aehf/lib/python3.10/site-packages/ray/__init__.py", line 63, in _configure_system
    import grpc  # noqa: F401
  File "/Users/shrekris/miniforge3/envs/aehf/lib/python3.10/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/shrekris/miniforge3/envs/aehf/lib/python3.10/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/shrekris/miniforge3/envs/aehf/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 2): Symbol not found: _CFRelease
  Referenced from: /Users/shrekris/miniforge3/envs/aehf/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so
  Expected in: flat namespace
 in /Users/shrekris/miniforge3/envs/aehf/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shrekris/miniforge3/envs/aehf/lib/python3.10/site-packages/ray/__init__.py", line 101, in <module>
    _configure_system()
  File "/Users/shrekris/miniforge3/envs/aehf/lib/python3.10/site-packages/ray/__init__.py", line 65, in _configure_system
    raise ImportError(
ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.
>>> exit()

% pip uninstall grpcio; conda install grpcio=1.43.0 -c conda-forge
...

% python
>>> import ray
>>> ray.__version__
'2.4.0'
```
