### ISSUE TITLE
System error: Ray has not been started yet. You can start Ray with 'ray.init()'

### ISSUE THREAD

**Issue by veryhannibal** [ray-project/ray#35592]
### 

```
Traceback (most recent call last):                                                                                                                                                                   
  File "/app/test/test.py", line 13, in <module>                                                                                                                                                    
    data.show()
  File "/usr/local/lib/python3.10/dist-packages/ray/data/dataset.py", line 2295, in show
    for row in self.take(limit):
  File "/usr/local/lib/python3.10/dist-packages/ray/data/dataset.py", line 2251, in take
    for row in self.iter_rows():
  File "/usr/local/lib/python3.10/dist-packages/ray/data/dataset_iterator.py", line 232, in iter_rows
    for batch in self.iter_batches(**iter_batch_args):
  File "/usr/local/lib/python3.10/dist-packages/ray/data/dataset_iterator.py", line 165, in iter_batches
    block_iterator, stats, blocks_owned_by_consumer = self._to_block_iterator()
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/dataset_iterator/dataset_iterator_impl.py", line 31, in _to_block_iterator
    block_iterator, stats, executor = ds._plan.execute_to_iterator()
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/plan.py", line 530, in execute_to_iterator
    block_iter = itertools.chain([next(gen)], gen)
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/execution/legacy_compat.py", line 49, in execute_to_legacy_block_iterator
    for bundle in bundle_iter:
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/execution/interfaces.py", line 484, in __next__
    return self.get_next()
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/execution/streaming_executor.py", line 111, in get_next
    raise item
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/execution/streaming_executor.py", line 157, in run
    while self._scheduling_loop_step(self._topology) and not self._shutdown:
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/execution/streaming_executor.py", line 205, in _scheduling_loop_step
    process_completed_tasks(topology)
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/execution/streaming_executor_state.py", line 328, in process_completed_tasks
    op.inputs_done()
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/execution/operators/all_to_all_operator.py", line 65, in inputs_done
    self._output_buffer, self._stats = self._bulk_fn(self._input_buffer, ctx)
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/execution/legacy_compat.py", line 312, in bulk_fn
    block_list, stats_dict = fn(
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/stage_impl.py", line 86, in do_fast_repartition
    return fast_repartition(blocks, num_blocks, ctx)
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/fast_repartition.py", line 35, in fast_repartition
    splits = wrapped_ds.split_at_indices(indices)
  File "/usr/local/lib/python3.10/dist-packages/ray/data/dataset.py", line 1452, in split_at_indices
    blocks, metadata = _split_at_indices(
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/split.py", line 283, in _split_at_indices
    ] = _split_all_blocks(
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/split.py", line 208, in _split_all_blocks
    trace_deallocation(b, "split._split_all_blocks")
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/memory_tracing.py", line 48, in trace_deallocation
    ray._private.internal_api.free(ref, local_only=False)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/internal_api.py", line 211, in free
    worker.check_connected()
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 611, in check_connected
    raise RaySystemError(
ray.exceptions.RaySystemError: System error: Ray has not been started yet. You can start Ray with 'ray.init()'.
```

**I run the following codes in jupyter notebook and got the above error:**

```
import ray
from ray.data.preprocessors import UniformKBinsDiscretizer

ray.init(address="ray://192.11.145.135:10001", runtime_env = {"working_dir": "./"})
data = ray.data.read_csv("/data/raydata/leader.csv")
data = data.repartition(10)

data.show()
```

### Versions / Dependencies

Python: 3.10.6
Ray: 2.4.0

### Reproduction script
```
`import ray
from ray.data.preprocessors import UniformKBinsDiscretizer

ray.init(address="ray://192.11.145.135:10001", runtime_env = {"working_dir": "./"})
data = ray.data.read_csv("/data/raydata/leader.csv")
data = data.repartition(10)

data.show()`
```
### Issue Severity

None

**Comment by Sahand-Razzaghi** [comment]
Well, apparently you are trying to connect to an exisiting Ray Scheduler running at "192.11.145.135:10001"
You haven't added anything to your Reproduction script regarding how this was setup before hand... configuration etc.

**Comment by veryhannibal** [comment]
> Well, apparently you are trying to connect to an exisiting Ray Scheduler running at "192.11.145.135:10001" You haven't added anything to your Reproduction script regarding how this was setup before hand... configuration etc.

Yeah, my ray scheduler was running at  "192.11.145.135:10001". I ran the coding in jupyter notebook the above error occuried.



But I if I copy the following code to a python file named runner.py.  And then use command `ray job submit --address=1192.11.145.135:6379 --working-dir ./ – python3 runner.py`.  It will run successfully.   


`
import ray
from ray.data.preprocessors import UniformKBinsDiscretizer

ray.init(address="auto", runtime_env = {"working_dir": "./"})
data = ray.data.read_csv("/data/raydata/leader.csv")
data = data.repartition(10)

data.show()
`

Thanks for your attention,  the environment of my ray-cluster and jupyter notebook is same, because they use the same docker image.

**Comment by rkooo567** [comment]
If you use ray.remote instead of data 

```
ray.init(address="ray://192.11.145.135:10001", runtime_env = {"working_dir": "./"})

@ray.remote
def f():
    pass

ray.get(f.remote())
```

does it work?

**Comment by rkooo567** [comment]
cc @ckw017

**Comment by veryhannibal** [comment]
> ray.init(address="ray://192.11.145.135:10001", runtime_env = {"working_dir": "./"})

 I modified my code, but new error occurred.

code: 
`
import ray
import pandas as pd

ray.init(address="ray://192.11.145.135:10001", runtime_env = {"working_dir": "./"})

@ray.remote
def func():
    d = pd.read_csv("/data/raydata/leader.csv")
    return d

df = ray.get(func.remote())
data = ray.data.from_pandas(df)
data = data.repartition(10)
data.show()
`
error:
`
File "/app/test1.py", line 20, in <module>██████████████████████████████████████████████████████████████████████████████████████████▏                                              | 7/10 [00:05<00:01,  2.13it/s]
    data.show()
  File "/usr/local/lib/python3.10/dist-packages/ray/data/dataset.py", line 2295, in show
    for row in self.take(limit):
  File "/usr/local/lib/python3.10/dist-packages/ray/data/dataset.py", line 2251, in take
    for row in self.iter_rows():
  File "/usr/local/lib/python3.10/dist-packages/ray/data/dataset_iterator.py", line 232, in iter_rows
    for batch in self.iter_batches(**iter_batch_args):
  File "/usr/local/lib/python3.10/dist-packages/ray/data/dataset_iterator.py", line 185, in iter_batches
    yield from iter_batches(
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/block_batching/iter_batches.py", line 179, in iter_batches
    next_batch = next(async_batch_iter)
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/block_batching/util.py", line 268, in make_async_gen
    raise next_item
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/block_batching/util.py", line 249, in execute_computation
    for item in fn(thread_safe_generator):
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/block_batching/iter_batches.py", line 170, in _async_iter_batches
    yield from extract_data_from_batch(batch_iter)
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/block_batching/util.py", line 193, in extract_data_from_batch
    for batch in batch_iter:
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/block_batching/iter_batches.py", line 307, in restore_original_order
    for batch in batch_iter:
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/block_batching/iter_batches.py", line 221, in threadpool_computations
    yield from formatted_batch_iter
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/block_batching/util.py", line 167, in format_batches
    for batch in block_iter:
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/block_batching/util.py", line 126, in blocks_to_batches
    for block in block_iter:
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/block_batching/util.py", line 64, in resolve_block_refs
    current_hit, current_miss, current_unknown = _calculate_ref_hits([block_ref])
  File "/usr/local/lib/python3.10/dist-packages/ray/data/_internal/block_batching/util.py", line 41, in _calculate_ref_hits
    locs = ray.experimental.get_object_locations(refs)
  File "/usr/local/lib/python3.10/dist-packages/ray/experimental/locations.py", line 38, in get_object_locations
    return ray._private.worker.global_worker.core_worker.get_object_locations(
AttributeError: 'Worker' object has no attribute 'core_worker'
`

**Comment by hsuyuanyuan** [comment]
I ran into a similar issue. I have a Ray cluster up-running in k8s. I used the following code to connect to it from Jupyter Notebook:
```
ray.init("ray://raycluster-head-svc.aaa.svc.cluster.local:10001")
```
The connection was successful, as it showed the python version, ray version, and the dashboard URL.

Then I treid to follow your [Batch Training with Ray Datasets example](https://docs.ray.io/en/latest/data/examples/batch_training.html).

It worked all the way till I got to [here](https://docs.ray.io/en/latest/data/examples/batch_training.html#transforming-a-ray-dataset-in-parallel-using-custom-functions-a-class-anchor-id-transform-ds-a). More specifically, 
```
# .map_batches applies a UDF to each partition of the data in parallel.
ds = ds.map_batches(transform_df, batch_format="pandas")
```

This is the complete error message for your reference:
```
---------------------------------------------------------------------------
RaySystemError                            Traceback (most recent call last)
Cell In [25], line 4
      2 ds = ds.map_batches(transform_df, batch_format="pandas")
      3 # Verify row count.
----> 4 print(f"Number of rows after transformation: {ds.count()}")

File /opt/conda/lib/python3.9/site-packages/ray/data/dataset.py:2324, in Dataset.count(self)
   2318     return meta_count
   2320 get_num_rows = cached_remote_fn(_get_num_rows)
   2322 return sum(
   2323     ray.get(
-> 2324         [get_num_rows.remote(block) for block in self.get_internal_block_refs()]
   2325     )
   2326 )

File /opt/conda/lib/python3.9/site-packages/ray/data/dataset.py:4118, in Dataset.get_internal_block_refs(self)
   4105 @ConsumptionAPI(pattern="Time complexity:")
   4106 @DeveloperAPI
   4107 def get_internal_block_refs(self) -> List[ObjectRef[Block]]:
   4108     """Get a list of references to the underlying blocks of this dataset.
   4109 
   4110     This function can be used for zero-copy access to the data. It blocks
   (...)
   4116         A list of references to this dataset's blocks.
   4117     """
-> 4118     blocks = self._plan.execute().get_blocks()
   4119     self._synchronize_progress_bar()
   4120     return blocks

File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/plan.py:580, in ExecutionPlan.execute(self, allow_clear_input_blocks, force_read, preserve_order)
    578 else:
    579     executor = BulkExecutor(copy.deepcopy(context.execution_options))
--> 580 blocks = execute_to_legacy_block_list(
    581     executor,
    582     self,
    583     allow_clear_input_blocks=allow_clear_input_blocks,
    584     dataset_uuid=self._dataset_uuid,
    585     preserve_order=preserve_order,
    586 )
    587 # TODO(ekl) we shouldn't need to set this in the future once we move
    588 # to a fully lazy execution model, unless .materialize() is used. Th
    589 # reason we need it right now is since the user may iterate over a
    590 # Dataset multiple times after fully executing it once.
    591 if not self._run_by_consumer:

File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/legacy_compat.py:114, in execute_to_legacy_block_list(executor, plan, allow_clear_input_blocks, dataset_uuid, preserve_order)
    107 dag, stats = _get_execution_dag(
    108     executor,
    109     plan,
    110     allow_clear_input_blocks,
    111     preserve_order,
    112 )
    113 bundles = executor.execute(dag, initial_stats=stats)
--> 114 block_list = _bundles_to_block_list(bundles)
    115 # Set the stats UUID after execution finishes.
    116 _set_stats_uuid_recursive(executor.get_stats(), dataset_uuid)

File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/legacy_compat.py:334, in _bundles_to_block_list(bundles)
    332 blocks, metadata = [], []
    333 owns_blocks = True
--> 334 for ref_bundle in bundles:
    335     if not ref_bundle.owns_blocks:
    336         owns_blocks = False

File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/interfaces.py:484, in OutputIterator.__next__(self)
    483 def __next__(self) -> RefBundle:
--> 484     return self.get_next()

File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py:111, in StreamingExecutor.execute.<locals>.StreamIterator.get_next(self, output_split_idx)
    109     raise StopIteration
    110 elif isinstance(item, Exception):
--> 111     raise item
    112 else:
    113     # Otherwise return a concrete RefBundle.
    114     if self._outer._global_info:

File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py:157, in StreamingExecutor.run(self)
    151 """Run the control loop in a helper thread.
    152 
    153 Results are returned via the output node's outqueue.
    154 """
    155 try:
    156     # Run scheduling loop until complete.
--> 157     while self._scheduling_loop_step(self._topology) and not self._shutdown:
    158         pass
    159 except Exception as e:
    160     # Propagate it to the result iterator.

File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py:205, in StreamingExecutor._scheduling_loop_step(self, topology)
    200     logger.get_logger().info("Scheduling loop step...")
    202 # Note: calling process_completed_tasks() is expensive since it incurs
    203 # ray.wait() overhead, so make sure to allow multiple dispatch per call for
    204 # greater parallelism.
--> 205 process_completed_tasks(topology)
    207 # Dispatch as many operators as we can for completed tasks.
    208 limits = self._get_or_refresh_resource_limits()

File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor_state.py:328, in process_completed_tasks(topology)
    321 inputs_done = all(
    322     [
    323         dep.completed() and not topology[dep].outqueue
    324         for dep in op.input_dependencies
    325     ]
    326 )
    327 if inputs_done and not op_state.inputs_done_called:
--> 328     op.inputs_done()
    329     op_state.inputs_done_called = True

File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/operators/all_to_all_operator.py:65, in AllToAllOperator.inputs_done(self)
     60 def inputs_done(self) -> None:
     61     ctx = TaskContext(
     62         task_idx=self._next_task_index,
     63         sub_progress_bar_dict=self._sub_progress_bar_dict,
     64     )
---> 65     self._output_buffer, self._stats = self._bulk_fn(self._input_buffer, ctx)
     66     self._next_task_index += 1
     67     self._input_buffer.clear()

File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/legacy_compat.py:312, in _stage_to_operator.<locals>.bulk_fn(refs, ctx)
    310     output_owned = True
    311 block_list = _bundles_to_block_list(refs)
--> 312 block_list, stats_dict = fn(
    313     block_list, ctx, input_owned, block_udf, remote_args
    314 )
    315 output = _block_list_to_bundles(block_list, owns_blocks=output_owned)
    316 if not stats_dict:

File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/stage_impl.py:86, in RepartitionStage.__init__.<locals>.do_fast_repartition(block_list, ctx, clear_input_blocks, *_)
     84 else:
     85     blocks = block_list
---> 86 return fast_repartition(blocks, num_blocks, ctx)

File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/fast_repartition.py:35, in fast_repartition(blocks, num_blocks, ctx)
     33 assert len(indices) < num_blocks, (indices, num_blocks)
     34 if indices:
---> 35     splits = wrapped_ds.split_at_indices(indices)
     36 else:
     37     splits = [wrapped_ds]

File /opt/conda/lib/python3.9/site-packages/ray/data/dataset.py:1452, in Dataset.split_at_indices(self, indices)
   1450 start_time = time.perf_counter()
   1451 block_list = self._plan.execute()
-> 1452 blocks, metadata = _split_at_indices(
   1453     block_list.get_blocks_with_metadata(),
   1454     indices,
   1455     block_list._owned_by_consumer,
   1456 )
   1457 split_duration = time.perf_counter() - start_time
   1458 parent_stats = self._plan.stats()

File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/split.py:283, in _split_at_indices(blocks_with_metadata, indices, owned_by_consumer, block_rows)
    276 per_block_split_indices: List[List[int]] = _generate_per_block_split_indices(
    277     block_rows, valid_indices
    278 )
    280 # phase 2: split each block based on the indices from previous step.
    281 all_blocks_split_results: Iterable[
    282     Tuple[ObjectRef[Block], BlockMetadata]
--> 283 ] = _split_all_blocks(
    284     blocks_with_metadata, per_block_split_indices, owned_by_consumer
    285 )
    287 # phase 3: generate the final split.
    288 
    289 # first calculate the size for each split.
    290 helper = [0] + valid_indices + [sum(block_rows)]

File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/split.py:208, in _split_all_blocks(blocks_with_metadata, per_block_split_indices, owned_by_consumer)
    206 if owned_by_consumer:
    207     for b in blocks_splitted:
--> 208         trace_deallocation(b, "split._split_all_blocks")
    209 else:
    210     for b in blocks_splitted:

File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/memory_tracing.py:48, in trace_deallocation(ref, loc, free)
     39 """Record that an object has been deleted (and delete if free=True).
     40 
     41 Args:
   (...)
     45         reference counting to kick in.
     46 """
     47 if free:
---> 48     ray._private.internal_api.free(ref, local_only=False)
     49 ctx = DatasetContext.get_current()
     50 if ctx.trace_allocations:

File /opt/conda/lib/python3.9/site-packages/ray/_private/internal_api.py:211, in free(object_refs, local_only)
    205     if not isinstance(object_ref, ray.ObjectRef):
    206         raise TypeError(
    207             "Attempting to call `free` on the value {}, "
    208             "which is not an ray.ObjectRef.".format(object_ref)
    209         )
--> 211 worker.check_connected()
    212 with profiling.profile("ray.free"):
    213     if len(object_refs) == 0:

File /opt/conda/lib/python3.9/site-packages/ray/_private/worker.py:611, in Worker.check_connected(self)
    605 """Check if the worker is connected.
    606 
    607 Raises:
    608   Exception: An exception is raised if the worker is not connected.
    609 """
    610 if not self.connected:
--> 611     raise RaySystemError(
    612         "Ray has not been started yet. You can start Ray with 'ray.init()'."
    613     )

RaySystemError: System error: Ray has not been started yet. You can start Ray with 'ray.init()'.
```

**Comment by veryhannibal** [comment]
> I ran into a similar issue. I have a Ray cluster up-running in k8s. I used the following code to connect to it from Jupyter Notebook (tried the notebook from my local macbook as well as another pod. both had the same error)
> 
> ```
> ray.init("ray://raycluster-head-svc.aaa.svc.cluster.local:10001")
> ```
> 
> The connection was successful, as it showed the python version, ray version, and the dashboard URL.
> 
> Then I treid to follow your [Batch Training with Ray Datasets example](https://docs.ray.io/en/latest/data/examples/batch_training.html).
> 
> It worked all the way till I got to [here](https://docs.ray.io/en/latest/data/examples/batch_training.html#transforming-a-ray-dataset-in-parallel-using-custom-functions-a-class-anchor-id-transform-ds-a). More specifically,
> 
> ```
> # .map_batches applies a UDF to each partition of the data in parallel.
> ds = ds.map_batches(transform_df, batch_format="pandas")
> 
> # Verify row count.
> print(f"Number of rows after transformation: {ds.count()}")
> ```
> 
> This is the error:
> 
> ```
> File ~/.pyenv/versions/3.9.16/lib/python3.9/site-packages/ray/_private/worker.py:611, in Worker.check_connected(self)
>     605 """Check if the worker is connected.
>     606 
>     607 Raises:
>     608   Exception: An exception is raised if the worker is not connected.
>     609 """
>     610 if not self.connected:
> --> 611     raise RaySystemError(
>     612         "Ray has not been started yet. You can start Ray with 'ray.init()'."
>     613     )
> 
> RaySystemError: System error: Ray has not been started yet. You can start Ray with 'ray.init()'.
> ```
> 
> Here is the complete stack trace for your reference:
> 
> ```
> ---------------------------------------------------------------------------
> RaySystemError                            Traceback (most recent call last)
> Cell In [25], line 4
>       2 ds = ds.map_batches(transform_df, batch_format="pandas")
>       3 # Verify row count.
> ----> 4 print(f"Number of rows after transformation: {ds.count()}")
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/dataset.py:2324, in Dataset.count(self)
>    2318     return meta_count
>    2320 get_num_rows = cached_remote_fn(_get_num_rows)
>    2322 return sum(
>    2323     ray.get(
> -> 2324         [get_num_rows.remote(block) for block in self.get_internal_block_refs()]
>    2325     )
>    2326 )
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/dataset.py:4118, in Dataset.get_internal_block_refs(self)
>    4105 @ConsumptionAPI(pattern="Time complexity:")
>    4106 @DeveloperAPI
>    4107 def get_internal_block_refs(self) -> List[ObjectRef[Block]]:
>    4108     """Get a list of references to the underlying blocks of this dataset.
>    4109 
>    4110     This function can be used for zero-copy access to the data. It blocks
>    (...)
>    4116         A list of references to this dataset's blocks.
>    4117     """
> -> 4118     blocks = self._plan.execute().get_blocks()
>    4119     self._synchronize_progress_bar()
>    4120     return blocks
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/plan.py:580, in ExecutionPlan.execute(self, allow_clear_input_blocks, force_read, preserve_order)
>     578 else:
>     579     executor = BulkExecutor(copy.deepcopy(context.execution_options))
> --> 580 blocks = execute_to_legacy_block_list(
>     581     executor,
>     582     self,
>     583     allow_clear_input_blocks=allow_clear_input_blocks,
>     584     dataset_uuid=self._dataset_uuid,
>     585     preserve_order=preserve_order,
>     586 )
>     587 # TODO(ekl) we shouldn't need to set this in the future once we move
>     588 # to a fully lazy execution model, unless .materialize() is used. Th
>     589 # reason we need it right now is since the user may iterate over a
>     590 # Dataset multiple times after fully executing it once.
>     591 if not self._run_by_consumer:
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/legacy_compat.py:114, in execute_to_legacy_block_list(executor, plan, allow_clear_input_blocks, dataset_uuid, preserve_order)
>     107 dag, stats = _get_execution_dag(
>     108     executor,
>     109     plan,
>     110     allow_clear_input_blocks,
>     111     preserve_order,
>     112 )
>     113 bundles = executor.execute(dag, initial_stats=stats)
> --> 114 block_list = _bundles_to_block_list(bundles)
>     115 # Set the stats UUID after execution finishes.
>     116 _set_stats_uuid_recursive(executor.get_stats(), dataset_uuid)
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/legacy_compat.py:334, in _bundles_to_block_list(bundles)
>     332 blocks, metadata = [], []
>     333 owns_blocks = True
> --> 334 for ref_bundle in bundles:
>     335     if not ref_bundle.owns_blocks:
>     336         owns_blocks = False
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/interfaces.py:484, in OutputIterator.__next__(self)
>     483 def __next__(self) -> RefBundle:
> --> 484     return self.get_next()
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py:111, in StreamingExecutor.execute.<locals>.StreamIterator.get_next(self, output_split_idx)
>     109     raise StopIteration
>     110 elif isinstance(item, Exception):
> --> 111     raise item
>     112 else:
>     113     # Otherwise return a concrete RefBundle.
>     114     if self._outer._global_info:
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py:157, in StreamingExecutor.run(self)
>     151 """Run the control loop in a helper thread.
>     152 
>     153 Results are returned via the output node's outqueue.
>     154 """
>     155 try:
>     156     # Run scheduling loop until complete.
> --> 157     while self._scheduling_loop_step(self._topology) and not self._shutdown:
>     158         pass
>     159 except Exception as e:
>     160     # Propagate it to the result iterator.
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py:205, in StreamingExecutor._scheduling_loop_step(self, topology)
>     200     logger.get_logger().info("Scheduling loop step...")
>     202 # Note: calling process_completed_tasks() is expensive since it incurs
>     203 # ray.wait() overhead, so make sure to allow multiple dispatch per call for
>     204 # greater parallelism.
> --> 205 process_completed_tasks(topology)
>     207 # Dispatch as many operators as we can for completed tasks.
>     208 limits = self._get_or_refresh_resource_limits()
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor_state.py:328, in process_completed_tasks(topology)
>     321 inputs_done = all(
>     322     [
>     323         dep.completed() and not topology[dep].outqueue
>     324         for dep in op.input_dependencies
>     325     ]
>     326 )
>     327 if inputs_done and not op_state.inputs_done_called:
> --> 328     op.inputs_done()
>     329     op_state.inputs_done_called = True
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/operators/all_to_all_operator.py:65, in AllToAllOperator.inputs_done(self)
>      60 def inputs_done(self) -> None:
>      61     ctx = TaskContext(
>      62         task_idx=self._next_task_index,
>      63         sub_progress_bar_dict=self._sub_progress_bar_dict,
>      64     )
> ---> 65     self._output_buffer, self._stats = self._bulk_fn(self._input_buffer, ctx)
>      66     self._next_task_index += 1
>      67     self._input_buffer.clear()
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/execution/legacy_compat.py:312, in _stage_to_operator.<locals>.bulk_fn(refs, ctx)
>     310     output_owned = True
>     311 block_list = _bundles_to_block_list(refs)
> --> 312 block_list, stats_dict = fn(
>     313     block_list, ctx, input_owned, block_udf, remote_args
>     314 )
>     315 output = _block_list_to_bundles(block_list, owns_blocks=output_owned)
>     316 if not stats_dict:
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/stage_impl.py:86, in RepartitionStage.__init__.<locals>.do_fast_repartition(block_list, ctx, clear_input_blocks, *_)
>      84 else:
>      85     blocks = block_list
> ---> 86 return fast_repartition(blocks, num_blocks, ctx)
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/fast_repartition.py:35, in fast_repartition(blocks, num_blocks, ctx)
>      33 assert len(indices) < num_blocks, (indices, num_blocks)
>      34 if indices:
> ---> 35     splits = wrapped_ds.split_at_indices(indices)
>      36 else:
>      37     splits = [wrapped_ds]
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/dataset.py:1452, in Dataset.split_at_indices(self, indices)
>    1450 start_time = time.perf_counter()
>    1451 block_list = self._plan.execute()
> -> 1452 blocks, metadata = _split_at_indices(
>    1453     block_list.get_blocks_with_metadata(),
>    1454     indices,
>    1455     block_list._owned_by_consumer,
>    1456 )
>    1457 split_duration = time.perf_counter() - start_time
>    1458 parent_stats = self._plan.stats()
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/split.py:283, in _split_at_indices(blocks_with_metadata, indices, owned_by_consumer, block_rows)
>     276 per_block_split_indices: List[List[int]] = _generate_per_block_split_indices(
>     277     block_rows, valid_indices
>     278 )
>     280 # phase 2: split each block based on the indices from previous step.
>     281 all_blocks_split_results: Iterable[
>     282     Tuple[ObjectRef[Block], BlockMetadata]
> --> 283 ] = _split_all_blocks(
>     284     blocks_with_metadata, per_block_split_indices, owned_by_consumer
>     285 )
>     287 # phase 3: generate the final split.
>     288 
>     289 # first calculate the size for each split.
>     290 helper = [0] + valid_indices + [sum(block_rows)]
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/split.py:208, in _split_all_blocks(blocks_with_metadata, per_block_split_indices, owned_by_consumer)
>     206 if owned_by_consumer:
>     207     for b in blocks_splitted:
> --> 208         trace_deallocation(b, "split._split_all_blocks")
>     209 else:
>     210     for b in blocks_splitted:
> 
> File /opt/conda/lib/python3.9/site-packages/ray/data/_internal/memory_tracing.py:48, in trace_deallocation(ref, loc, free)
>      39 """Record that an object has been deleted (and delete if free=True).
>      40 
>      41 Args:
>    (...)
>      45         reference counting to kick in.
>      46 """
>      47 if free:
> ---> 48     ray._private.internal_api.free(ref, local_only=False)
>      49 ctx = DatasetContext.get_current()
>      50 if ctx.trace_allocations:
> 
> File /opt/conda/lib/python3.9/site-packages/ray/_private/internal_api.py:211, in free(object_refs, local_only)
>     205     if not isinstance(object_ref, ray.ObjectRef):
>     206         raise TypeError(
>     207             "Attempting to call `free` on the value {}, "
>     208             "which is not an ray.ObjectRef.".format(object_ref)
>     209         )
> --> 211 worker.check_connected()
>     212 with profiling.profile("ray.free"):
>     213     if len(object_refs) == 0:
> 
> File /opt/conda/lib/python3.9/site-packages/ray/_private/worker.py:611, in Worker.check_connected(self)
>     605 """Check if the worker is connected.
>     606 
>     607 Raises:
>     608   Exception: An exception is raised if the worker is not connected.
>     609 """
>     610 if not self.connected:
> --> 611     raise RaySystemError(
>     612         "Ray has not been started yet. You can start Ray with 'ray.init()'."
>     613     )
> 
> RaySystemError: System error: Ray has not been started yet. You can start Ray with 'ray.init()'.
> ```
> 
I found a temporary solution, run the following code before map_batches：
`ds = ray.data.from_arrow_refs(ds.to_arrow_refs())`

I tried this on ray2.3.1, and it worked.

**Comment by hsuyuanyuan** [comment]
Thanks @veryhannibal.  I tried `ds = ray.data.from_arrow_refs(ds.to_arrow_refs())`, but it hit the same error. I am using 2.4.0 though.
```
File /opt/conda/lib/python3.9/site-packages/ray/_private/worker.py:611, in Worker.check_connected(self)
    605 """Check if the worker is connected.
    606 
    607 Raises:
    608   Exception: An exception is raised if the worker is not connected.
    609 """
    610 if not self.connected:
--> 611     raise RaySystemError(
    612         "Ray has not been started yet. You can start Ray with 'ray.init()'."
    613     )

RaySystemError: System error: Ray has not been started yet. You can start Ray with 'ray.init()'.
```

**Comment by veryhannibal** [comment]
Maybe you can have a try. Some error I meet on 2.4.0 doesn't occur on 2.3.1.

**Comment by rgasper** [comment]
I get the same issues trying to connect to a running cluster that I launched on AWS. I can verify the cluster is running with `ray status` and `ray submit whatever.py` works fine, but I cannot run the same exact ray-powered code from `whatever.py` from a jupyter notebook talking to the cluster via `ray.init(some_aws_ip_port10001)`

**Comment by rgasper** [comment]
I used this cluster configuration: https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/aws/example-full.yaml

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
