### ISSUE TITLE
[release-tests] aws_cluster_launcher/minimal failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#35661]
### What happened + What you expected to happen

https://buildkite.com/ray-project/release-tests-branch/builds/1682#01884695-3337-4881-90c2-82e608d4861e
https://buildkite.com/ray-project/release-tests-branch/builds/1682#01884695-333b-4544-b6ed-56ca0ebc7eac

### Versions / Dependencies

master, 2.5.0 release branch

### Reproduction script

buildkite

### Issue Severity

High: It blocks me from completing my task.

**Comment by scv119** [comment]
```
2023-05-22 21:05:10,846 INFO updater.py:490 -- [7/7] Starting the Ray runtime
2023-05-22 21:05:10,847 VINFO command_runner.py:371 -- Running `export RAY_USAGE_STATS_ENABLED=1;export RAY_OVERRIDE_RESOURCES='{"CPU":2}';ray stop`
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/bin/ray", line 5, in <module>
    from ray.scripts.scripts import main
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/scripts/scripts.py", line 2430, in <module>
    from ray.util.state.state_cli import (
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/util/state/__init__.py", line 1, in <module>
    from ray.util.state.api import (
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/util/state/api.py", line 17, in <module>
    from ray.util.state.common import (
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/util/state/common.py", line 411, in <module>
    class ActorState(StateSchema):
  File "pydantic/dataclasses.py", line 224, in pydantic.dataclasses.dataclass.wrap
    #
  File "pydantic/dataclasses.py", line 347, in pydantic.dataclasses._add_pydantic_validation_attributes
    # Special case for the 0-tuple.
  File "pydantic/dataclasses.py", line 400, in pydantic.dataclasses.create_pydantic_model_from_dataclass
    
  File "pydantic/main.py", line 1026, in pydantic.main.create_model
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

**Comment by scv119** [comment]
could it related to new release?

**Comment by can-anyscale** [comment]
Happen both on master and release branch so probably related to some external python library upgrade

**Comment by jjyao** [comment]
I think pydantic 1.10.8 that's released two hours ago fixed the issue: https://buildkite.com/ray-project/release-tests-branch/builds/1686#01884a60-48c8-452a-a25e-47f63ce9067a

**Comment by can-anyscale** [comment]
![](https://media4.giphy.com/media/5GoVLqeAOo6PK/200.gif?cid=5a38a5a20h4auaf748wtw6rii19gmlda1wgi81l2i23iejp2&ep=v1_gifs_search&rid=200.gif&ct=g)

**Comment by jjyao** [comment]
@can-anyscale could you rerun the release test and close it if it passes.

**Comment by can-anyscale** [comment]
@jjyao sound good, I retried them here: https://buildkite.com/ray-project/release-tests-branch/builds/1682#01884aa2-9cf6-4e44-a2be-1a2bc71540f7

**Comment by jjyao** [comment]
@can-anyscale it passed on the release branch as well. I think we need to make a decision to see if we need to ban pydantic `1.10.7` in Ray setup.py

**Comment by can-anyscale** [comment]
Ok, I removed the release-blocker tag for now since it is passing

**Comment by jjyao** [comment]
OK, the issue happen when we use `pydantic 1.10.7` AND `typing-extensions > 4.5.0`

**Comment by jjyao** [comment]
Upgrading pydantic to latest or downgrading typing-extensions below 4.6 solves the issue.
