### ISSUE TITLE
[RLlib] Curiosity Module does not work  with DQN

### ISSUE THREAD

**Issue by TomOrth** [ray-project/ray#35867]
### What happened + What you expected to happen

1. **The bug**: The Curiosity module does not work with DQN despite documentation claiming it does.

2. **Expected Behavior**: A DQN agent can be trained on a discrete environment.

3. **Useful Information**
     1. The logs (for torch):
     ```
     Traceback (most recent call last):
      File "/Users/thomasorth/agent.py", line 49, in <module>
        algo = config.build()
      File "/usr/local/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm_config.py", line 1071, in build
        return algo_class(
      File "/usr/local/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 466, in __init__
        super().__init__(
      File "/usr/local/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 169, in __init__
        self.setup(copy.deepcopy(self.config))
      File "/usr/local/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 592, in setup
        self.workers = WorkerSet(
      File "/usr/local/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 172, in __init__
        self._setup(
      File "/usr/local/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 262, in _setup
        self._local_worker = self._make_worker(
      File "/usr/local/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 967, in _make_worker
        worker = cls(
      File "/usr/local/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 738, in __init__
        self._update_policy_map(policy_dict=self.policy_dict)
      File "/usr/local/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1985, in _update_policy_map
        self._build_policy_map(
      File "/usr/local/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 2097, in _build_policy_map
        new_policy = create_policy_for_framework(
      File "/usr/local/lib/python3.9/site-packages/ray/rllib/utils/policy.py", line 142, in create_policy_for_framework
        return policy_class(observation_space, action_space, merged_config)
      File "/usr/local/lib/python3.9/site-packages/ray/rllib/policy/policy_template.py", line 327, in __init__
        self._initialize_loss_from_dummy_batch(
      File "/usr/local/lib/python3.9/site-packages/ray/rllib/policy/policy.py", line 1451, in _initialize_loss_from_dummy_batch
        self.exploration.postprocess_trajectory(self, self._dummy_batch)
      File "/usr/local/lib/python3.9/site-packages/ray/rllib/utils/exploration/curiosity.py", line 258, in postprocess_trajectory
        self._postprocess_torch(policy, sample_batch)
      File "/usr/local/lib/python3.9/site-packages/ray/rllib/utils/exploration/curiosity.py", line 342, in _postprocess_torch
        phis, _ = self.model._curiosity_feature_net(
      File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
        raise AttributeError("'{}' object has no attribute '{}'".format(
      AttributeError: 'FullyConnectedNetwork_as_DQNTorchModel' object has no attribute '_curiosity_feature_net'
      ```
      2. The logs (tensorflow):
      ```
      Traceback (most recent call last):
  File "/Users/thomasorth/agent.py", line 49, in <module>
    algo = config.build()
  File "/usr/local/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm_config.py", line 1071, in build
    return algo_class(
  File "/usr/local/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 466, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 169, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/usr/local/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 592, in setup
    self.workers = WorkerSet(
  File "/usr/local/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 172, in __init__
    self._setup(
  File "/usr/local/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 262, in _setup
    self._local_worker = self._make_worker(
  File "/usr/local/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 967, in _make_worker
    worker = cls(
  File "/usr/local/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 738, in __init__
    self._update_policy_map(policy_dict=self.policy_dict)
  File "/usr/local/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1985, in _update_policy_map
    self._build_policy_map(
  File "/usr/local/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 2097, in _build_policy_map
    new_policy = create_policy_for_framework(
  File "/usr/local/lib/python3.9/site-packages/ray/rllib/utils/policy.py", line 139, in create_policy_for_framework
    return policy_class(observation_space, action_space, merged_config)
  File "/usr/local/lib/python3.9/site-packages/ray/rllib/policy/eager_tf_policy.py", line 460, in __init__
    after_init(self, observation_space, action_space, config)
  File "/usr/local/lib/python3.9/site-packages/ray/rllib/algorithms/dqn/dqn_tf_policy.py", line 386, in setup_late_mixins
    TargetNetworkMixin.__init__(policy)
  File "/usr/local/lib/python3.9/site-packages/ray/rllib/policy/tf_mixins.py", line 241, in __init__
    self.update_target(tau=1.0)  # self.config.get("tau", 1.0))
  File "/usr/local/lib/python3.9/site-packages/ray/rllib/policy/tf_mixins.py", line 263, in update_target
    self._do_update(np.float32(tau or self.config.get("tau", 1.0)))
  File "/usr/local/lib/python3.9/site-packages/ray/rllib/policy/tf_mixins.py", line 224, in update_target_fn
    assert len(model_vars) == len(target_model_vars), (
    ```
    3. The documentation page: https://docs.ray.io/en/latest/rllib/rllib-algorithms.html#curiosity-icm-intrinsic-curiosity-module -> Has verbiage about DQN in the example configuration. Additionally: https://docs.ray.io/en/latest/rllib/rllib-algorithms.html#available-algorithms-overview -> For the curiosity module it says, **Exploration-based plug-ins (can be combined with any algo)**

 

### Versions / Dependencies

ray==2.4.0
torch==2.0.1
tensorflow==2.9.0

### Reproduction script

```python
import ray.rllib.algorithms.dqn as dqn
config = (
    dqn.DQNConfig()
    # A very large frozen-lake that's hard for a random policy to solve
    # due to 0.0 feedback.
    .environment(
        "FrozenLake-v1",
        env_config={
            "desc": [
                "SFFFFFFF",
                "FFFFFFFF",
                "FFFFFFFF",
                "FFFFFFFF",
                "FFFFFFFF",
                "FFFFFFFF",
                "FFFFFFFF",
                "FFFFFFFG",
            ],
            "is_slippery": False,
            "max_episode_steps": 16,
        },
    )
    # Print out observations to see how far we already get inside the Env.
    # Limit horizon to make it really hard for non-curious agent to reach
    # the goal state.
    .rollouts(num_rollout_workers=0)
    # TODO (Kourosh): We need to provide examples on how we do curiosity with
    # RLModule API
    .training(lr=0.001, _enable_learner_api=False)
    .framework("tf2")  # Replace with torch for torch backend
    .exploration(
        exploration_config={
            "type": "Curiosity",
            "eta": 0.2,
            "lr": 0.001,
            "feature_dim": 128,
            "feature_net_config": {
                "fcnet_hiddens": [],
                "fcnet_activation": "relu",
            },
            "sub_exploration": {
                "type": "EpsilonGreedy",
            },
        }
    )
    .rl_module(_enable_rl_module_api=False)
)
num_iterations = 10
algo = config.build()
learnt = False
for i in range(num_iterations):
    result = algo.train()
    print(result)
    if result["episode_reward_max"] > 0.0:
        print("Reached goal after {} iters!".format(i))
        learnt = True
        break
algo.stop()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by Rohan138** [comment]
See: https://github.com/ray-project/ray/issues/35833#issuecomment-1599334364

Try turning `_enable_rl_module_api=False` for now, eventually we'll migrate Curiosity to the RLmodule API.
