### ISSUE TITLE
`get_runtime_context` raises confusing `AssertionError` if Ray is not initialized

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#35889]
```python
>>> import ray
>>> ray.get_runtime_context().get()
<stdin>:1: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
Use get_xxx_id() methods to get relevant ids instead
/Users/eoakes/code/ray/python/ray/runtime_context.py:30: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
Use get_job_id() instead
  "job_id": self.job_id,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eoakes/code/ray/python/ray/util/annotations.py", line 168, in wrapper
    return obj(*args, **kwargs)
  File "/Users/eoakes/code/ray/python/ray/runtime_context.py", line 30, in get
    "job_id": self.job_id,
  File "/Users/eoakes/code/ray/python/ray/util/annotations.py", line 168, in wrapper
    return obj(*args, **kwargs)
  File "/Users/eoakes/code/ray/python/ray/runtime_context.py", line 55, in job_id
    assert not job_id.is_nil()
AssertionError
```

**Comment by edoakes** [comment]
@scv119 @jjyao for triage

**Comment by jjyao** [comment]
If you use the new `get_xx_ids()`, they print out the nice message

```
>>> ray.get_runtime_context().get_job_id()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jjyao/Workspace/ray2/python/ray/runtime_context.py", line 72, in get_job_id
    assert ray.is_initialized(), (
AssertionError: Job ID is not available because Ray has not been initialized.
```

**Comment by edoakes** [comment]
we should not be using `AssertionError` for user-facing error messages:
https://google.github.io/styleguide/pyguide.html#244-decision

**Comment by jjyao** [comment]
Good point, I can fix that.
