### ISSUE TITLE
[RLlib] Custom Policy Example Error

### ISSUE THREAD

**Issue by emcyroyale** [ray-project/ray#36159]
### What happened + What you expected to happen

I am trying to build a custom policy. To that end, I tried to run https://github.com/ray-project/ray/blob/master/rllib/examples/custom_torch_policy.py in order to build off a correct method of creating a custom policy. But it fails with the below output.

```
python custom_torch_policy.py

Failure # 1 (occurred at 2023-06-07_13-49-29)
Traceback (most recent call last):
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/tune/execution/ray_trial_executor.py", line 1231, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/_private/worker.py", line 2523, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::MyAlgorithm.__init__()[39m (pid=319934, ip=10.129.33.170, repr=MyAlgorithm)
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 242, in _setup
    self.add_workers(
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 635, in add_workers
    raise result.get()
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/rllib/utils/actor_manager.py", line 488, in __fetch_result
    result = ray.get(r)
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::RolloutWorker.__init__()[39m (pid=320148, ip=10.129.33.170, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fcce6727460>)
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 738, in __init__
    self._update_policy_map(policy_dict=self.policy_dict)
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1985, in _update_policy_map
    self._build_policy_map(
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 2097, in _build_policy_map
    new_policy = create_policy_for_framework(
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/rllib/utils/policy.py", line 142, in create_policy_for_framework
    return policy_class(observation_space, action_space, merged_config)
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/rllib/policy/policy_template.py", line 327, in __init__
    self._initialize_loss_from_dummy_batch(
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/rllib/policy/policy.py", line 1405, in _initialize_loss_from_dummy_batch
    actions, state_outs, extra_outs = self.compute_actions_from_input_dict(
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/rllib/policy/torch_policy.py", line 332, in compute_actions_from_input_dict
    return self._compute_action_helper(
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/rllib/utils/threading.py", line 24, in wrapper
    return func(self, *a, **k)
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/rllib/policy/torch_policy.py", line 1045, in _compute_action_helper
    actions, logp = self.exploration.get_exploration_action(
TypeError: cannot unpack non-iterable NoneType object

During handling of the above exception, another exception occurred:

[36mray::MyAlgorithm.__init__()[39m (pid=319934, ip=10.129.33.170, repr=MyAlgorithm)
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 466, in __init__
    super().__init__(
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 169, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 592, in setup
    self.workers = WorkerSet(
  File "/home/jovyan/.local/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 194, in __init__
    raise e.args[0].args[2]
TypeError: cannot unpack non-iterable NoneType object



```

I was able to print out the parameters that are being passed to get_exploration_action. Then using those sample values, I ran get_exploration_action with StochasticSampling (self.exploration defaulted to this) and was at least able to get something other than NoneType. I basically took MyTorchPolicy from custom_torch_policy.py. Instantiated it, collected the params, and ran get_exploration_action as below. Given this, I am not certain where the issue is, but my overall goal is to be able to create custom policies. Any help would be appreciated.

```
mtpolicy= MyTorchPolicy(env.observation_space, env.action_space, PGConfig())

dist_inputs, state_out = mtpolicy.model(mtpolicy._dummy_batch, [], None)
action_dist = mtpolicy.dist_class(dist_inputs, mtpolicy.model)

mtpolicy.exploration.get_exploration_action(action_distribution=action_dist,
                                            timestep=mtpolicy.global_timestep,
                                            explore=False)
```

```
stdout:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.]))
```

### Versions / Dependencies

ray 2.4.0
python 3.9.16
Debian GNU/Linux 11 (bullseye)
torch 2.0.0

### Reproduction script

```
python custom_torch_policy.py
```

```
import ray
from ray import air, tune
from ray.rllib.algorithms.algorithm import Algorithm
from ray.rllib.policy.policy_template import build_policy_class
from ray.rllib.policy.sample_batch import SampleBatch

def policy_gradient_loss(policy, model, dist_class, train_batch):
    logits, _ = model({SampleBatch.CUR_OBS: train_batch[SampleBatch.CUR_OBS]})
    action_dist = dist_class(logits, model)
    log_probs = action_dist.logp(train_batch[SampleBatch.ACTIONS])
    return -train_batch[SampleBatch.REWARDS].dot(log_probs)


# <class 'ray.rllib.policy.torch_policy_template.MyTorchPolicy'>

from ray.rllib.algorithms.pg import PGConfig
MyTorchPolicy = build_policy_class(
    name="MyTorchPolicy",
    framework="torch",
    loss_fn=policy_gradient_loss,
    get_default_config=lambda: PGConfig())


# Create a new Algorithm using the Policy defined above.
class MyAlgorithm(Algorithm):
    @classmethod
    def get_default_policy_class(cls, config):
        return 

mtpolicy= MyTorchPolicy(env.observation_space, env.action_space, PGConfig())

dist_inputs, state_out = mtpolicy.model(mtpolicy._dummy_batch, [], None)
action_dist = mtpolicy.dist_class(dist_inputs, mtpolicy.model)

mtpolicy.exploration.get_exploration_action(action_distribution=action_dist,
                                            timestep=mtpolicy.global_timestep,
                                            explore=False)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by Rohan138** [comment]
You'll need to add `"_enable_rl_module_api": False` to your `AlgorithmConfig`. I'll put up a PR with this fix.

However, I would recommend switching to the new (RLModule)[https://docs.ray.io/en/latest/rllib/rllib-rlmodule.html] API for your custom policy; it's an improved version of the old RLlib Policy and Model APIs, and as such, will become the default soon (the `Policy` API will be deprecated in favor of it).
