### ISSUE TITLE
[release] decision_tree_autoscaling_20_runs & single_node failed due to infra error

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#36178]
https://buildkite.com/ray-project/release-tests-probes/builds/631#01888eaa-5445-48a4-865b-37c4c6fba890
https://buildkite.com/ray-project/release-tests-probes/builds/631#01888eaa-5448-4699-8a6f-7a00ac7c6a05

```




[INFO 2023-06-05 20:31:05,826] log.py: 31  Got the following metadata:
  | name:    decision_tree_autoscaling_20_runs.aws
  | status:  error
  | runtime: 0.00
  | stable:  True
  |  
  | buildkite_url: https://buildkite.com/ray-project/release-tests-probes/builds/631#01888eaa-5445-48a4-865b-37c4c6fba890
  |  
  | wheels_url:    https://s3-us-west-2.amazonaws.com/ray-wheels/master/a38ddb1372f9fbba128ea9d19e88b86de8b468f6/ray-3.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl
  |  
  | cluster_url:   https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_gkc9wxxrupn63jzbx41ysjbffe
  |  
  | job_url:   https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_7pf4759lg8lc4l6bhfxmafzfhr
  |  
  |  
  | [INFO 2023-06-05 20:31:05,826] log.py: 41  Observed the following results:
  |  
  | build_time = 630.1749491691589
  | success = 1
  |  
  | [INFO 2023-06-05 20:31:05,826] artifacts.py: 39  Wrote test config and result to artifacts directory: /tmp/artifacts
  | [INFO 2023-06-05 20:31:05,827] artifacts.py: 48  Wrote prometheus metrics to artifacts directory: /tmp/artifacts
  | [INFO 2023-06-05 20:31:05,827] db.py: 18  Persisting result to the databricks delta lake...
  | [INFO 2023-06-05 20:31:05,865] db.py: 59  Result has been persisted to the databricks delta lake
  | [ERROR 2023-06-05 20:31:05,865] run_release_test.py: 171  Test script did not finish successfully (success).
  | Traceback (most recent call last):
  | File "ray_release/scripts/run_release_test.py", line 158, in main
  | result = run_release_test(
  | File "/tmp/release-18aVIuB4VJ/release/ray_release/glue.py", line 537, in run_release_test
  | raise pipeline_exception
  | File "/tmp/release-18aVIuB4VJ/release/ray_release/glue.py", line 527, in run_release_test
  | raise pipeline_exception
  | File "/tmp/release-18aVIuB4VJ/release/ray_release/glue.py", line 511, in run_release_test
  | handle_result(test, result)
  | File "/tmp/release-18aVIuB4VJ/release/ray_release/alerts/handle.py", line 50, in handle_result
  | raise ResultsAlert(error)
  | ray_release.exception.ResultsAlert: Test script did not finish successfully (success).
  | [INFO 2023-06-05 20:31:05,866] run_release_test.py: 173  Release test pipeline for test decision_tree_autoscaling_20_runs.aws completed. Returning with exit code = 41
  | Script failed on try 1/1 with exit code 41 (command error), aborting.
  | ----------------------------------------
  | Release test finished with final exit code 41 after 1/1 tries
  | Run results:
  | Run 1: Exit code = 41 (command error)
  | ----------------------------------------
  | Final release test exit code is 41 (command error). Took 1423s
  | RELEASE MANAGER: This could be an error in the test. Please REVIEW THE LOGS and ping the test owner.
 

<br class="Apple-interchange-newline">
```

**Comment by can-anyscale** [comment]
This should already been fixed on more recent runs https://buildkite.com/ray-project/release-tests-branch/builds/1766#01889498-b89b-4b10-a333-bc4dd7fd1f72
