### ISSUE TITLE
The "ray start" command gives a strange warning when it exits.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#363]
Running `start_ray.sh --head` gives the following error as it exits. I have only seen the error on Mac OS and not on Linux.

```
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x10532f978>>
Traceback (most recent call last):
  File "/Users/rkn/anaconda3/lib/python3.6/subprocess.py", line 760, in __del__
AttributeError: 'NoneType' object has no attribute 'warn'
```

The full output is

```
$ ./scripts/start_ray.sh --head
Using IP address 128.32.44.14 for this node.
Waiting for redis server at 127.0.0.1:62396 to respond...
View the web UI at http://localhost:8080.
{'node_ip_address': '128.32.44.14', 'redis_address': '128.32.44.14:62396', 'object_store_addresses': [ObjectStoreAddress(name='/tmp/plasma_store8096180', manager_name='/tmp/plasma_manager75907687', manager_port=52514)], 'local_scheduler_socket_names': ['/tmp/scheduler590997']}

Started Ray with 10 workers on this node. A different number of workers can be set with the --num-workers flag (but you have to first terminate the existing cluster). You can add additional nodes to the cluster by calling

    ./scripts/start_ray.sh --redis-address 128.32.44.14:62396

from the node you wish to add. You can connect a driver to the cluster from Python by running

    import ray
    ray.init(redis_address="128.32.44.14:62396")

If you have trouble connecting from a different machine, check that your firewall is configured properly. If you wish to terminate the processes that have been started, run

    ./scripts/stop_ray.sh
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x10532f978>>
Traceback (most recent call last):
  File "/Users/rkn/anaconda3/lib/python3.6/subprocess.py", line 760, in __del__
AttributeError: 'NoneType' object has no attribute 'warn'
```

**Comment by robertnishihara** [comment]
It looks like the error is coming from a line like this one https://github.com/python/cpython/blob/master/Lib/subprocess.py#L762. It seems that you aren't supposed to start processes with `Popen` and then leave them running after the parent script exits.

**Comment by robertnishihara** [comment]
This is addressed by #429. Note that this is only a partial solution, and discussion about how to handle it properly can take place in #432.

**Comment by robertnishihara** [comment]
Reopening because we reverted #429 in #437, so the problem has been reintroduced.

**Comment by robertnishihara** [comment]
The relevant command now is `ray start --head`.

**Comment by robertnishihara** [comment]
The relevant command now is `ray start --head`.

**Comment by robertnishihara** [comment]
Closing because I haven't seen this in a while. At least I don't see it right now with **Python 3.5.2 :: Anaconda 4.2.0 (64-bit)** on Ubuntu 16 or with **Python 3.6.0 :: Anaconda 4.3.0 (x86_64)** on MacOS.
