### ISSUE TITLE
[Ray Collective Communication Lib]: Barrier op for Gloo-Backend timed out.

### ISSUE THREAD

**Issue by pratkpranav** [ray-project/ray#36317]
### What happened + What you expected to happen

We tried using[ Ray-Collective Communication](https://docs.ray.io/en/latest/ray-more-libs/ray-collective.html) for one of our use cases. However, we encountered an issue while using the gloo backend to use the barrier. It appears that the barrier is invoking an all-reduce operation, which in turn triggers a timeout as indicated in this code snippet: [link](https://github.com/facebookincubator/gloo/blob/597accfd79f5b0f9d57b228dec088ca996686475/gloo/transport/tcp/unbound_buffer.cc#L132).
```
Traceback (most recent call last):
  File "barrier_pygloo.py", line 32, in <module>
    ray.get([actor.wait.remote() for actor_id, actor in enumerate(comm_actors)])
  File "/home/pratik/.local/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 18, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/pratik/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/pratik/.local/lib/python3.8/site-packages/ray/_private/worker.py", line 2540, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::CommActor.wait() (pid=49178, ip=192.168.1.8, actor_id=df76b2062367d9f4a1b1d66a01000000, repr=<barrier_pygloo.CommActor object at 0x7ef5d0e74e80>)
  File "barrier_pygloo.py", line 28, in wait
    col.barrier("default")
  File "/home/pratik/.local/lib/python3.8/site-packages/ray/util/collective/collective.py", line 308, in barrier
    g.barrier()
  File "/home/pratik/.local/lib/python3.8/site-packages/ray/util/collective/collective_group/gloo_collective_group.py", line 264, in barrier
    self.allreduce([barrier_tensor])
  File "/home/pratik/.local/lib/python3.8/site-packages/ray/util/collective/collective_group/gloo_collective_group.py", line 252, in allreduce
    self._collective(tensors, tensors, collective_fn)
  File "/home/pratik/.local/lib/python3.8/site-packages/ray/util/collective/collective_group/gloo_collective_group.py", line 466, in _collective
    collective_fn(input_tensors[0], output_tensors[0], self._gloo_context)
  File "/home/pratik/.local/lib/python3.8/site-packages/ray/util/collective/collective_group/gloo_collective_group.py", line 243, in collective_fn
    pygloo.allreduce(
RuntimeError: [/root/.cache/bazel/_bazel_root/22470c32b6b05656d37eca60778f3711/sandbox/linux-sandbox/4/execroot/pygloo/external/gloo/gloo/transport/tcp/unbound_buffer.cc:133] Timed out waiting 30000ms for send operation to complete
```

### Versions / Dependencies

ray==2.5.0
pygloo=Build from source(https://discuss.ray.io/t/urgent-attributeerror-module-pygloo-rendezvous-has-no-attribute-customstore/7025/4)

### Reproduction script

```import ray

import ray.util.collective as col
import numpy as np
from ray.util.collective.types import Backend, ReduceOp


@ray.remote(num_cpus=1)
class CommActor:
    def __init__(
        self,
        id,
        num_workers,
    ):
        self.id = id
        self.num_workers = num_workers
        col.init_collective_group(
            world_size=num_workers,
            rank=id,
            backend=Backend.GLOO,
            group_name="default",
        )

    def wait(self):
        if self.id % 2 == 0:
            import time

            time.sleep(40)

        col.barrier("default")

    def test_allreduce(self, group_name="default"):
        self.sendbuf = np.ones((4096, 1024, 256), dtype=np.float32)
        col.allreduce(tensor=self.sendbuf, group_name=group_name, op=ReduceOp.SUM)
        # Test whether the sum actually happened
        np.allclose(
            self.sendbuf,
            self.num_workers * np.ones((4096, 1024, 256), dtype=np.float32),
        )


ray.init(address="auto")
comm_actors = [CommActor.remote(id, 2) for id in range(2)]

print("Calling all reduce")
ray.get([actor.test_allreduce.remote("default") for actor in comm_actors])
print("Workers completing all reduce")

ray.get([actor.wait.remote() for actor_id, actor in enumerate(comm_actors)])
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by cadedaniel** [comment]
Hi @pratkpranav. Thanks for creating the issue.

It is OK that barrier calls allreduce on a small array; this guarantees barrier semantics without large data transfer, without writing a custom codepath for barrier. This is standard and shouldn't be an issue.

I don't know why your barrier call is failing. Typically this is because the processes can't communicate with each other, or you're using the wrong `tag`. I see that Ray doesn't let you provide the tag at the moment, so my question is can these processes communicate with each other?

How are you running this script?

**Comment by pratkpranav** [comment]
Hi  @cadedaniel, Thanks for replying.  I am running that as mentioned [here](https://docs.ray.io/en/latest/ray-more-libs/ray-collective.html). 
Here is an updated script that also does all-reduce among all the processes, which should make sure the processes communicate with each other. I also added pygloo as requirements which I missed earlier. Can you reproduce the error?

```
import ray

import ray.util.collective as col
import numpy as np
from ray.util.collective.types import Backend, ReduceOp


@ray.remote(num_cpus=1)
class CommActor:
    def __init__(
        self,
        id,
        num_workers,
    ):
        self.id = id
        self.num_workers = num_workers
        col.init_collective_group(
            world_size=num_workers,
            rank=id,
            backend=Backend.GLOO,
            group_name="default",
        )

    def wait(self):
        if self.id % 2 == 0:
            import time

            time.sleep(40)

        col.barrier("default")

    def test_allreduce(self, group_name="default"):
        self.sendbuf = np.ones((4096, 1024, 256), dtype=np.float32)
        col.allreduce(tensor=self.sendbuf, group_name=group_name, op=ReduceOp.SUM)
        # Test whether the sum actually happened
        np.allclose(
            self.sendbuf,
            self.num_workers * np.ones((4096, 1024, 256), dtype=np.float32),
        )


ray.init(address="auto")
comm_actors = [CommActor.remote(id, 2) for id in range(2)]

print("Calling all reduce")
ray.get([actor.test_allreduce.remote("default") for actor in comm_actors])
print("Workers completing all reduce")

ray.get([actor.wait.remote() for actor_id, actor in enumerate(comm_actors)])
```

**Comment by cadedaniel** [comment]
Hi @pratkpranav . It seems that this is the expected behavior with Gloo. Even if pygloo used the Barrier call in Gloo, it would still call a communication function with a timeout https://github.com/facebookincubator/gloo/blob/cf1e1abc95d0b961222ee82b6935f76250fbcf16/gloo/barrier.cc#L33C17-L34

If there is some other function which doesn't have a timeout, then we can look at adding that to pygloo. But seems this is intended behavior. Maybe Gloo has some way to configure this timeout so it's larger for your usecase?
