### ISSUE TITLE
[Serve] Basic serve deployment example in documentation throws error with Python 3.11

### ISSUE THREAD

**Issue by jharaldson** [ray-project/ray#36319]
### Description
The basic deployment example in "Key Concepts" of the Serve documentation throws an error when run with Python 3.11.  
https://docs.ray.io/en/latest/serve/key-concepts.html#serve-key-concepts-deployment

```
@serve.deployment
class MyFirstDeployment:
  # Take the message to return as an argument to the constructor.
  def __init__(self, msg):
      self.msg = msg

  def __call__(self):
      return self.msg

my_first_deployment = MyFirstDeployment.bind("Hello world!")
handle = serve.run(my_first_deployment)
```

### Expected behavior
Python 3.11 has experimental support in Ray 2.5, but it would be expected that the basic examples in the documentation would work. 

### Logs:
```
(ServeController pid=154501) INFO 2023-06-12 12:47:49,598 controller 154501 deployment_state.py:1298 - Deploying new version of deployment default_MyFirstDeployment.
(ServeController pid=154501) INFO 2023-06-12 12:47:49,630 controller 154501 deployment_state.py:1537 - Adding 1 replica to deployment default_MyFirstDeployment.
(HTTPProxyActor pid=154538) INFO:     Started server process [154538]
---------------------------------------------------------------------------
RayTaskError(ValueError)                  Traceback (most recent call last)
Cell In[4], line 1
----> 1 handle = serve.run(my_first_deployment)

File ~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/serve/api.py:544, in run(target, _blocking, host, port, name, route_prefix)
    530     deployment_parameters = {
    531         "name": deployment._name,
    532         "func_or_class": deployment._func_or_class,
   (...)
    541         "docs_path": deployment._docs_path,
    542     }
    543     parameter_group.append(deployment_parameters)
--> 544 client.deploy_application(
    545     name,
    546     parameter_group,
    547     _blocking=_blocking,
    548     remove_past_deployments=remove_past_deployments,
    549 )
    551 if ingress is not None:
    552     return ingress._get_handle()

File ~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/serve/_private/client.py:44, in _ensure_connected.<locals>.check(self, *args, **kwargs)
     42 if self._shutdown:
     43     raise RayServeException("Client has already been shut down.")
---> 44 return f(self, *args, **kwargs)

File ~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/serve/_private/client.py:300, in ServeControllerClient.deploy_application(self, name, deployments, _blocking, remove_past_deployments)
    297     url = deployment["url"]
    299     if _blocking:
--> 300         self._wait_for_deployment_healthy(deployment_name)
    301         self.log_deployment_ready(deployment_name, version, url, tags[i])
    303 if remove_past_deployments:
    304     # clean up the old deployments

File ~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/serve/_private/client.py:168, in ServeControllerClient._wait_for_deployment_healthy(self, name, timeout_s)
    165 start = time.time()
    166 while time.time() - start < timeout_s or timeout_s < 0:
--> 168     status_bytes = ray.get(self._controller.get_deployment_status.remote(name))
    170     if status_bytes is None:
    171         raise RuntimeError(
    172             f"Waiting for deployment {name} to be HEALTHY, "
    173             "but deployment doesn't exist."
    174         )

File ~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/_private/auto_init_hook.py:18, in wrap_auto_init.<locals>.auto_init_wrapper(*args, **kwargs)
     15 @wraps(fn)
     16 def auto_init_wrapper(*args, **kwargs):
     17     auto_init_ray()
---> 18     return fn(*args, **kwargs)

File ~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/_private/client_mode_hook.py:103, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    101     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    102         return getattr(ray, func.__name__)(*args, **kwargs)
--> 103 return func(*args, **kwargs)

File ~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/_private/worker.py:2540, in get(object_refs, timeout)
   2538     worker.core_worker.dump_object_store_memory_usage()
   2539 if isinstance(value, RayTaskError):
-> 2540     raise value.as_instanceof_cause()
   2541 else:
   2542     raise value

RayTaskError(ValueError): ray::ServeController.get_deployment_status() (pid=154501, ip=172.31.205.52, actor_id=f8a11a1797548a78b16ce2cc01000000, repr=<ray.serve.controller.ServeController object at 0x7f806ab0f010>)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'DEPLOYMENT_STATUS_DeploymentStatus.UPDATING'

During handling of the above exception, another exception occurred:

ray::ServeController.get_deployment_status() (pid=154501, ip=172.31.205.52, actor_id=f8a11a1797548a78b16ce2cc01000000, repr=<ray.serve.controller.ServeController object at 0x7f806ab0f010>)
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
           ^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/serve/controller.py", line 779, in get_deployment_status
    return status[0].to_proto().SerializeToString()
           ^^^^^^^^^^^^^^^^^^^^
  File "~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/serve/_private/common.py", line 92, in to_proto
    return DeploymentStatusInfoProto(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ~/sandbox/.venvs/py311/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 556, in init
    field_value = _GetIntegerEnumValue(field.enum_type, field_value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/sandbox/.venvs/py311/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 494, in _GetIntegerEnumValue
    raise ValueError('Enum type %s: unknown label "%s"' % (
ValueError: Enum type ray.serve.DeploymentStatus: unknown label "DEPLOYMENT_STATUS_DeploymentStatus.UPDATING"
```

### Versions / Dependencies

Ray 2.5
Python 3.11.3
Ubuntu 22.04.1

### Reproduction script

```
@serve.deployment
class MyFirstDeployment:
  # Take the message to return as an argument to the constructor.
  def __init__(self, msg):
      self.msg = msg

  def __call__(self):
      return self.msg

my_first_deployment = MyFirstDeployment.bind("Hello world!")
handle = serve.run(my_first_deployment)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by ddelange** [comment]
^ it seems to occur only on py 3.11 🤔

**Comment by ddelange** [comment]
cc @rickyyx

**Comment by sihanwang41** [comment]
Hi @rickyyx , I just assigned this issue to you, feel free to loop me in (or reassign the task to me) if any serve context needed.

**Comment by ddelange** [comment]
Might a fix for this regression make the 2.5.2 or 2.6.0 release? cc @krfricke

**Comment by ddelange** [comment]
Opened #36954

**Comment by mertalev** [comment]
I tried running the nightly and the same error is now coming from the `to_proto` method of `ApplicationStatusInfoProto` in the same module. I'm assuming this is because it's still referenced with `self.status` instead of `self.status.name`.

```
return ApplicationStatusInfoProto(
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: unknown enum label "APPLICATION_STATUS_ApplicationStatus.DEPLOYING"
```

**Comment by mertalev** [comment]
The error still occurs in the nightly with 3.11, but in `ApplicationStatusInfoProto` instead of `DeploymentStatusInfoProto`. I'm assuming this is because `ApplicationStatusInfoProto.to_proto` references `self.status` instead of `self.status.name`.

```
Traceback (most recent call last):
  File "~/test1.py", line 14, in <module>
    handle = serve.run(my_first_deployment)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/venv/lib/python3.11/site-packages/ray/serve/api.py", line 496, in run
    client.deploy_application(
  File "~/venv/lib/python3.11/site-packages/ray/serve/_private/client.py", line 45, in check
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/venv/lib/python3.11/site-packages/ray/serve/_private/client.py", line 353, in deploy_application
    self._wait_for_application_running(name)
  File "~/venv/lib/python3.11/site-packages/ray/serve/_private/client.py", line 257, in _wait_for_application_running
    status_bytes = ray.get(self._controller.get_serve_status.remote(name))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/venv/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "~/venv/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "~/venv/lib/python3.11/site-packages/ray/_private/worker.py", line 2491, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::ServeController.get_serve_status() (pid=248136, ip=<IP>, actor_id=3da2b2e0ce7e48e5c7bdf8c001000000, repr=<ray.serve.controller.ServeController object at 0x7f70c746b910>)
  File "~/venv/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "~/venv/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
           ^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/venv/lib/python3.11/site-packages/ray/serve/controller.py", line 782, in get_serve_status
    return status_info.to_proto().SerializeToString()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "~/venv/lib/python3.11/site-packages/ray/serve/_private/common.py", line 138, in to_proto
    app_status_proto = self.app_status.to_proto()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/venv/lib/python3.11/site-packages/ray/serve/_private/common.py", line 62, in to_proto
    return ApplicationStatusInfoProto(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: unknown enum label "APPLICATION_STATUS_ApplicationStatus.DEPLOYING"
```

**Comment by ddelange** [comment]
@edoakes looks like the same thing indeed, maybe there are even more occurrences. do you have time to patch?

**Comment by ddelange** [comment]
#37258 cc @edoakes
