### ISSUE TITLE
[Dashboard] Permission denied: metrics/grafana/provisioning

### ISSUE THREAD

**Issue by spearman** [ray-project/ray#36328]
### What happened + What you expected to happen

1. Dashboard is not served on port 8265, although the script outputs "`2023-06-12 19:19:18,553	INFO worker.py:1616 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265`"
2. Dashboard served on localhost port 8265
3. Looking at dashboard.err shows the following error log:
```
$ cat ray/session_2023-06-12_19-19-16_211767_33313/logs/dashboard.err 
Traceback (most recent call last):
  File "/nix/store/jnkjfn6s5g8g2r3ii45hg3j3vg0lgi0j-python3-3.10.11-env/lib/python3.10/site-packages/ray/dashboard/dashboard.py", line 240, in <module>
    raise e
  File "/nix/store/jnkjfn6s5g8g2r3ii45hg3j3vg0lgi0j-python3-3.10.11-env/lib/python3.10/site-packages/ray/dashboard/dashboard.py", line 228, in <module>
    loop.run_until_complete(dashboard.run())
  File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/nix/store/jnkjfn6s5g8g2r3ii45hg3j3vg0lgi0j-python3-3.10.11-env/lib/python3.10/site-packages/ray/dashboard/dashboard.py", line 70, in run
    await self.dashboard_head.run()
  File "/nix/store/jnkjfn6s5g8g2r3ii45hg3j3vg0lgi0j-python3-3.10.11-env/lib/python3.10/site-packages/ray/dashboard/head.py", line 329, in run
    await asyncio.gather(*concurrent_tasks, *(m.run(self.server) for m in modules))
  File "/nix/store/jnkjfn6s5g8g2r3ii45hg3j3vg0lgi0j-python3-3.10.11-env/lib/python3.10/site-packages/ray/dashboard/modules/metrics/metrics_head.py", line 305, in run
    self._create_default_grafana_configs()
  File "/nix/store/jnkjfn6s5g8g2r3ii45hg3j3vg0lgi0j-python3-3.10.11-env/lib/python3.10/site-packages/ray/dashboard/modules/metrics/metrics_head.py", line 200, in _create_default_grafana_configs
    os.makedirs(
  File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/spearman/py/try/tryray/ray/session_2023-06-12_19-19-16_211767_33313/metrics/grafana/provisioning'
```
Looking at the directory `metrics/grafana` does not have write permissions:
```
$ ls -l ray/session_2023-06-12_19-19-16_211767_33313/metrics/
total 4
dr-xr-xr-x 2 spearman users 4096 Jan  1  1970 grafana
```

### Versions / Dependencies

Ray 2.4.0

Python 3.10.11

NixOS 23.05

### Reproduction script

```
import logging
import time

import ray

print("ray version:", ray.__version__)
ray.init(include_dashboard=True, logging_level=logging.DEBUG)
iter = 0
while True:
  time.sleep(2)
  print(f"tick[{iter}]")
  iter += 1
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by spearman** [comment]
I'm going to close this as it only seems to affect the ray NixOS package. If ray is installed with pip then I can access the Dashboard.
