### ISSUE TITLE
[CI][Docs] Example in Train FAQ is flakey 

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#36399]
### What happened + What you expected to happen

The Train FAQ fails doctest in about 10% of runs. For example: https://buildkite.com/ray-project/oss-ci-build-branch/builds/4465#0188b6b7-4f32-4bb6-9b88-84008cf88d8f.

```
______________________________ [doctest] faq.rst _______________________________
--
  | 082    gets propagated to all training workers.
  | 083
  | 084 .. testcode::
  | 085
  | 086     import ray
  | 087
  | 088     # Add this at the top of your Ray application.
  | 089     runtime_env = {"env_vars": {"NCCL_SOCKET_IFNAME": "ens5"}}
  | 090     ray.init(runtime_env=runtime_env, ignore_reinit_error=True)
  | 091
  | UNEXPECTED EXCEPTION: AttributeError("'NoneType' object has no attribute 'address_info'")
  | Traceback (most recent call last):
  | File "/opt/miniconda/lib/python3.7/site-packages/pytest_sphinx.py", line 457, in _DocTestRunner__run
  | test.globs,
  | File "<doctest faq.rst[0]>", line 5, in <module>
  | File "/ray/python/ray/_private/client_mode_hook.py", line 103, in wrapper
  | return func(*args, **kwargs)
  | File "/ray/python/ray/_private/worker.py", line 1450, in init
  | return RayContext(dict(_global_node.address_info, node_id=node_id.hex()))
  | AttributeError: 'NoneType' object has no attribute 'address_info'
  | faq.rst:91: UnexpectedException
  | ---------------------------- Captured stderr setup -----------------------------
```

### Versions / Dependencies

Ray: 66617f6b247c44d839f612a33f2b5f5d38f10306

### Reproduction script

Reproduce https://buildkite.com/ray-project/oss-ci-build-branch/builds/4465#0188b6b7-4f32-4bb6-9b88-84008cf88d8f.

### Issue Severity

None

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
