### ISSUE TITLE
Containerized multi node with Docker compose: FileNotFoundError

### ISSUE THREAD

**Issue by robcaulk** [ray-project/ray#36495]
### What happened + What you expected to happen

I am using pip installed Ray 2.5.0 and following the [documentation guide](https://docs.ray.io/en/master/ray-contribute/fake-autoscaler.html#testing-containerized-multi-nodes-locally-with-docker-compose) to test autoscaling.

I start the docker monitor and see the following output:

```
python3 flowdapt/compute/executor/ray/docker_monitor.py path/to/example_docker.yaml 
Starting monitor process. Please start Ray cluster with:
   RAY_FAKE_CLUSTER=1 ray up path/to/example_docker.yaml
 ```
   
I follow these instructions and fail with the following error:

```
RAY_FAKE_CLUSTER=1 ray up -y path/to/example_docker.yaml
Cluster: fake_docker

Traceback (most recent call last):
  File "/home/worker/flowdapt_dev_env/.venv/bin/ray", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/worker/flowdapt_dev_env/.venv/lib/python3.11/site-packages/ray/scripts/scripts.py", line 2462, in main
    return cli()
           ^^^^^
  File "/home/worker/flowdapt_dev_env/.venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/flowdapt_dev_env/.venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/worker/flowdapt_dev_env/.venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/flowdapt_dev_env/.venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/flowdapt_dev_env/.venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/flowdapt_dev_env/.venv/lib/python3.11/site-packages/ray/autoscaler/_private/cli_logger.py", line 856, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/worker/flowdapt_dev_env/.venv/lib/python3.11/site-packages/ray/scripts/scripts.py", line 1264, in up
    create_or_update_cluster(
  File "/home/worker/flowdapt_dev_env/.venv/lib/python3.11/site-packages/ray/autoscaler/_private/commands.py", line 279, in create_or_update_cluster
    config = _bootstrap_config(config, no_config_cache=no_config_cache)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/flowdapt_dev_env/.venv/lib/python3.11/site-packages/ray/autoscaler/_private/commands.py", line 300, in _bootstrap_config
    config = prepare_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/flowdapt_dev_env/.venv/lib/python3.11/site-packages/ray/autoscaler/_private/util.py", line 237, in prepare_config
    with_defaults = fillout_defaults(config)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/flowdapt_dev_env/.venv/lib/python3.11/site-packages/ray/autoscaler/_private/util.py", line 262, in fillout_defaults
    defaults = _get_default_config(config["provider"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/flowdapt_dev_env/.venv/lib/python3.11/site-packages/ray/autoscaler/_private/providers.py", line 256, in _get_default_config
    with open(path_to_default) as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/worker/flowdapt_dev_env/.venv/lib/python3.11/site-packages/ray/autoscaler/_private/fake_multi_node/example_docker.yaml'
```

It seems to be ignoring the path to the custom config path that I am passing to it. 

Is this feature unavailable to pip installed Ray? When I look through the virtual env files, it is clear that the `example_docker.yaml` is omitted from the source. However, when I look through a latest git cloned repo, those files do exist. 

Thanks for offering some clarification. 

### Versions / Dependencies

Ray 2.5.0
Ubuntu 22.04

### Reproduction script

Pip install Ray 2.5.0.

Copy copy/paste `example_docker.yaml` and `docker_monitor.py` from https://github.com/ray-project/ray/tree/master/python/ray/autoscaler/_private/fake_multi_node

to a custom directory. Try to follow the [doc guide](https://docs.ray.io/en/master/ray-contribute/fake-autoscaler.html#testing-containerized-multi-nodes-locally-with-docker-compose) using your custom files.

```
python3 flowdapt/compute/executor/ray/docker_monitor.py path/to/docker_example.yaml 
```

open a second terminal:

```
RAY_FAKE_CLUSTER=1 ray up -y path/to/example_docker.yaml
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by architkulkarni** [comment]
@robcaulk You're right, not all files in the github repo are included in the package that is built and hosted at PyPI.  Omitting this particular file is an oversight on our end.  We will include this file in future releases, thanks for reporting the issue!
