### ISSUE TITLE
Release test air_example_gptj_deepspeed_fine_tuning.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#36537]
Release test air_example_gptj_deepspeed_fine_tuning.aws failed.
See https://buildkite.com/ray-project/release-tests-branch/builds/1807#0188c86c-d999-46fc-8f01-0ab4264db1ce for more details.
cc @ml

	 -- created by ray-test-bot

**Comment by can-anyscale** [comment]
Blamed commit: c9965d307a4c8d69ff4e8d9213d84cbc8c00b9bd found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/264

**Comment by krfricke** [comment]
I think the commit is unrelated. The error message we get is this:

```
2023-06-17 02:16:38,194 ERROR tune_controller.py:905 -- Trial task failed for trial TransformersTrainer_31d61_00000
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/worker.py", line 2485, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::_Inner.train() (pid=2876, ip=10.0.2.31, actor_id=e7d8e3dbf3bf04375da73b4a02000000, repr=TransformersTrainer)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 391, in train
    raise skipped from exception_cause(skipped)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 54, in check_for_failure
    ray.get(object_ref)
ray.exceptions.RayTaskError(AttributeError): ray::_RayTrainWorker__execute.get_next() (pid=2868, ip=10.0.8.193, actor_id=eb4b0f0188e4cb2395406f4602000000, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x7f6a22ede2e0>)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/worker_group.py", line 32, in __execute
    raise skipped from exception_cause(skipped)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 129, in discard_return_wrapper
    train_func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/huggingface/transformers/transformers_trainer.py", line 474, in _huggingface_train_loop_per_worker
    trainer.train()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 1543, in train
    return inner_training_loop(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 1765, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ray/anaconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/home/ray/anaconda3/lib/python3.9/site-packages/transformers/trainer_pt_utils.py", line 804, in __iter__
    for element in self.dataset:
  File "/home/ray/anaconda3/lib/python3.9/site-packages/datasets/iterable_dataset.py", line 1344, in __iter__
    if self._formatting and (ex_iterable.iter_arrow or self._formatting.format_type == "arrow"):
AttributeError: 'RayDatasetHFIterable' object has no attribute 'iter_arrow'
2023-06-17 02:16:38,206 ERROR tune.py:1144 -- Trials did not complete: [TransformersTrainer_31d61_00000]
2023-06-17 02:16:38,211 WARNING experiment_analysis.py:912 -- Failed to read the results for 1 trials:
- /home/ray/ray_results/TransformersTrainer_2023-06-17_02-13-16/TransformersTrainer_31d61_00000_0_2023-06-17_02-13-16
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│                                                                              │
│ /tmp/tmpk1f31k_0:400 in <module>                                             │
│                                                                              │
│   397 # Finally, we call the {meth}`~ray.train.huggingface.TransformersTrain │
│   398                                                                        │
│   399 # %%                                                                   │
│ ❱ 400 results = trainer.fit()                                                │
│   401                                                                        │
│   402 # %% [markdown]                                                        │
│   403 # You can use the returned {class}`~ray.air.Result` object to access m │
│ /home/ray/anaconda3/lib/python3.9/site-packages/ray/train/base_trainer.py:61 │
│ 9 in fit                                                                     │
│                                                                              │
│   616 │   │   if result.error:                                               │
│   617 │   │   │   # Raise trainable errors to the user with a message to res │
│   618 │   │   │   # or configure `FailureConfig` in a new run.               │
│ ❱ 619 │   │   │   raise TrainingFailedError(                                 │
│   620 │   │   │   │   "\n".join([restore_msg, TrainingFailedError._FAILURE_C │
│   621 │   │   │   ) from result.error                                        │
│   622 │   │   return result                                                  │
╰──────────────────────────────────────────────────────────────────────────────╯
TrainingFailedError: The Ray Train run failed. Please inspect the previous error
messages for a cause. After fixing the issue (assuming that the error is not 
caused by your own application logic, but rather an error such as OOM), you can 
restart the run from scratch or continue this run.
To continue this run, you can use: `trainer = TransformersTrainer.restore("/home
/ray/ray_results/TransformersTrainer_2023-06-17_02-13-16")`.
To start a new run that will retry on training failures, set 
`air.RunConfig(failure_config=air.FailureConfig(max_failures))` in the Trainer's
`run_config` with `max_failures > 0`, or `max_failures = -1` for unlimited 
retries.
```

I'll investigate.

**Comment by krfricke** [comment]
The failing test has `datasets==2.13.0` and the passing test has `datasets==2.12.0`, so I think this is again related to base image dependency changes.

In any case, this test should be fixed here: https://github.com/ray-project/ray/pull/36276 (successful run: https://buildkite.com/ray-project/release-tests-pr/builds/42460)

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/1826#0188eca2-c14f-4e06-a9bf-b20a98896f69
