### ISSUE TITLE
[<Ray component: Core|RLlib|etc...>] 

### ISSUE THREAD

**Issue by frazierprime** [ray-project/ray#36578]
### Description

Hello!
I am a new user, making my way through the jobs API quickstart guide, and I am seeing a strange error. Perhaps I am doing something wrong, in which case please let me know!

## Context:
Ray version: `ray==2.5.0`
I have a local cluster for testing running via this command: `ray start --head`

`ray status` output:
```
ray status
======== Autoscaler status: 2023-06-20 12:11:18.250073 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_6cab00f1082e513eb8b2fab1bbe4440cd045f2e052e2b253c74e3e31
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/8.0 CPU
 0B/17.70GiB memory
 0B/8.85GiB object_store_memory

Demands:
 (no resource demands)
```

## Error:
```
RuntimeError: Request failed with status code 400: Traceback (most recent call last):
  File "/home/jovyan/.conda/envs/ray-experiments-0/lib/python3.11/site-packages/ray/dashboard/modules/job/job_head.py", line 283, in submit_job
    job_agent_client = await asyncio.wait_for(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/ray-experiments-0/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/ray-experiments-0/lib/python3.11/site-packages/ray/dashboard/modules/job/job_head.py", line 206, in choose_agent
    node_id = sample(set(agent_infos), 1)[0]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/ray-experiments-0/lib/python3.11/random.py", line 439, in sample
    raise TypeError("Population must be a sequence.  "
TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
```

## Code:
```
import ray

@ray.remote
def hello_world():
    return "Hello World!"

ray.init()
print(ray.get(hello_world.remote()))
```

## Command to submit:
```
ray job submit --working-dir ray_experiments -- python toy_script.py
```

### Link

https://docs.ray.io/en/latest/cluster/running-applications/job-submission/quickstart.html#quickstart-using-the-ray-jobs-cli

**Comment by architkulkarni** [comment]
This seems to be a breaking change in Python 3.11: https://docs.python.org/3.11/library/random.html#random.sample

@frazierprime Thanks for reporting this, would you be willing to open a PR to fix it? We just need to convert it to a list instead of a set.

**Comment by frazierprime** [comment]
> This seems to be a breaking change in Python 3.11: https://docs.python.org/3.11/library/random.html#random.sample
> 
> @frazierprime Thanks for reporting this, would you be willing to open a PR to fix it? We just need to convert it to a list instead of a set.

https://github.com/ray-project/ray/pull/36642

Not letting me add an assignee. Guessing there's some git rule that doesn't allow it. 

Also; can't follow your build steps in https://docs.ray.io/en/latest/ray-contribute/getting-involved.html#setting-up-your-development-environment
Basically looks like there is some work to do to bring Ray in line with 3.11 I didn't include it in my PR, since the small change is fairly self contained.

get the following error:
```
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-hbtjcxte/numba_588b5e126a824717a38608e494f0015b/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/tmp/pip-install-hbtjcxte/numba_588b5e126a824717a38608e494f0015b/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.3; only versions >=3.7,<3.11 are supported.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by frazierprime** [comment]
@architkulkarni | @rickyyx - any updates on if/when this fix will go out? I just tested with Ray version `2.5.1` and I am still getting the same error.

**Comment by architkulkarni** [comment]
It will be in Ray 2.6, which should be released in late July.
