### ISSUE TITLE
[Data] `ocr_example` is broken 

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#36619]
### Description

```
(ReadBinary->Map pid=28743) Traceback (most recent call last):
--
  | (ReadBinary->Map pid=28743)   File "python/ray/_raylet.pyx", line 1073, in ray._raylet.execute_dynamic_generator_and_store_task_outputs
  | (ReadBinary->Map pid=28743)   File "python/ray/_raylet.pyx", line 3291, in ray._raylet.CoreWorker.store_task_outputs
  | (ReadBinary->Map pid=28743)   File "/ray/python/ray/data/_internal/execution/operators/map_operator.py", line 389, in _map_task
  | (ReadBinary->Map pid=28743)     for b_out in fn(iter(blocks), ctx):
  | (ReadBinary->Map pid=28743)   File "/ray/python/ray/data/_internal/execution/legacy_compat.py", line 305, in do_map
  | (ReadBinary->Map pid=28743)     yield from block_fn(blocks, ctx, *fn_args, **fn_kwargs)
  | (ReadBinary->Map pid=28743)   File "/ray/python/ray/data/_internal/planner/map_rows.py", line 26, in fn
  | (ReadBinary->Map pid=28743)     item = row_fn(row)
  | (ReadBinary->Map pid=28743)   File "/root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/bin/doc/source/data/doc_code/loading_data.runfiles/com_github_ray_project_ray/doc/source/data/doc_code/loading_data.py", line 370, in <lambda>
  | (ReadBinary->Map pid=28743)     ds = ds.map(lambda row: {"image": np.asarray(PIL.Image.open(BytesIO(row["bytes"])).convert("L"))})
  | (ReadBinary->Map pid=28743)   File "/opt/miniconda/lib/python3.7/site-packages/PIL/Image.py", line 3148, in open
  | (ReadBinary->Map pid=28743)     "cannot identify image file %r" % (filename if filename else fp)
  | (ReadBinary->Map pid=28743) PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fa51616b170>
```

### Link

https://docs.ray.io/en/latest/data/examples/ocr_example.html
https://buildkite.com/ray-project/oss-ci-build-pr/builds/22898#018844e6-35c8-460d-a072-829b57ce9785

### See also

https://github.com/ray-project/ray/pull/35618

**Comment by anyscalesam** [comment]
Already updated cc @c21
