### ISSUE TITLE
[JAVA] Ray.init() failed  when JNI load

### ISSUE THREAD

**Issue by imperio-wxm** [ray-project/ray#36637]
### What happened + What you expected to happen

First I started ray with `ray start --head` and got:
```shell
Usage stats collection is enabled. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.

Local node IP: 127.0.0.1

--------------------
Ray runtime started.
--------------------

Next steps

  To connect to this Ray cluster:
    import ray
    ray.init()

  To submit a Ray job using the Ray Jobs CLI:
    RAY_ADDRESS='http://127.0.0.1:8265' ray job submit --working-dir . -- python my_script.py

  See https://docs.ray.io/en/latest/cluster/running-applications/job-submission/index.html
  for more information on submitting Ray jobs to the Ray cluster.

  To terminate the Ray runtime, run
    ray stop

  To view the status of the cluster, use
    ray status

  To monitor and debug Ray, view the dashboard at
    127.0.0.1:8265

  If connection to the dashboard fails, check your firewall settings and network configuration.
```

Then I run my java code:
```java
public static void main(String[] args) {
    System.setProperty("ray.local-mode","true");
    System.setProperty("ray.address", "auto");
    Ray.init();
    Ray.shutdown();
}
```

And I get error:
```java
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library '/tmp/ray/1687317325598/libcore_worker_library_java.dylib':
dlopen(/tmp/ray/1687317325598/libcore_worker_library_java.dylib, 9): no suitable image found.  Did find:
	/tmp/ray/1687317325598/libcore_worker_library_java.dylib: mach-o, but wrong architecture
	/private/tmp/ray/1687317325598/libcore_worker_library_java.dylib: mach-o, but wrong architecture
dlopen(/tmp/ray/1687317325598/libcore_worker_library_java.dylib, 9): no suitable image found.  Did find:
	/tmp/ray/1687317325598/libcore_worker_library_java.dylib: mach-o, but wrong architecture
	/private/tmp/ray/1687317325598/libcore_worker_library_java.dylib: mach-o, but wrong architecture
Native library (tmp/ray/1687317325598/libcore_worker_library_java.dylib) not found in resource path ([file:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/charsets.jar, ......])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at io.ray.runtime.util.JniUtils.loadLibrary(JniUtils.java:72)
	at io.ray.runtime.RayNativeRuntime.start(RayNativeRuntime.java:80)
	at io.ray.runtime.DefaultRayRuntimeFactory.createRayRuntime(DefaultRayRuntimeFactory.java:37)
	at io.ray.api.Ray.init(Ray.java:32)
	at io.ray.api.Ray.init(Ray.java:19)
	at com.alibaba.iic.metaq.oss.ray.RayMain.main(RayMain.java:21)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/tmp/ray/1687317325598/libcore_worker_library_java.dylib, 9): no suitable image found.  Did find:
	/tmp/ray/1687317325598/libcore_worker_library_java.dylib: mach-o, but wrong architecture
	/private/tmp/ray/1687317325598/libcore_worker_library_java.dylib: mach-o, but wrong architecture
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 8 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/tmp/ray/1687317325598/libcore_worker_library_java.dylib, 9): no suitable image found.  Did find:
	/tmp/ray/1687317325598/libcore_worker_library_java.dylib: mach-o, but wrong architecture
	/private/tmp/ray/1687317325598/libcore_worker_library_java.dylib: mach-o, but wrong architecture
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 8 more
	Suppressed: java.io.IOException: Native library (tmp/ray/1687317325598/libcore_worker_library_java.dylib) not found in resource path ([file:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/lib/charsets.jar, .....])
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1119)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
		... 8 more
```

I found a similar closed issue, but didn't find any solution: https://github.com/ray-project/ray/issues/14479

### Versions / Dependencies

- Mac: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
- Ray: ray, version 2.5.0
- pom:
```xml
<dependency>
    <groupId>io.ray</groupId>
    <artifactId>ray-api</artifactId>
    <version>2.5.0</version>
</dependency>
<dependency>
    <groupId>io.ray</groupId>
    <artifactId>ray-runtime</artifactId>
    <version>2.5.0</version>
</dependency>
```
- java: version "1.8.0_301"

### Reproduction script

```java
public static void main(String[] args) {
    System.setProperty("ray.local-mode","true");
    System.setProperty("ray.address", "auto");
    Ray.init();
    Ray.shutdown();
}
```

### Issue Severity

None

**Comment by imperio-wxm** [comment]
I found: Non-fat file: libcore_worker_library_java.dylib is architecture: arm64, but Intel is x86_64.
Do I need to compile the source code myself?

**Comment by SongGuyang** [comment]
@imperio-wxm Thanks for this catch! I think the issue is that will only built the library in arm architecture environment. @jovany-wang can we built it in both the two architecture?

@imperio-wxm In short term, I think you can built the jar from source or you can try an old release version.

**Comment by imperio-wxm** [comment]
@SongGuyang  Hi, how to build the jar from source? Is there some documentation and tutorials.

**Comment by SongGuyang** [comment]
I'm sorry that there is no documentation about the java part. You can try as follows:
```
RAY_INSTALL_JAVA=1 pip install -e python/ --verbose
cd ../java
mvn clean install -U  -DskipTests -T10 -Dcheckstyle.skip
```
In the first step, you need to compile all the Ray project. So you can reference to https://docs.ray.io/en/latest/ray-contribute/development.html#building-ray

**Comment by mullerhai** [comment]
> I'm sorry that there is no documentation about the java part. You can try as follows:
> 
> ```
> RAY_INSTALL_JAVA=1 pip install -e python/ --verbose
> cd ../java
> mvn clean install -U  -DskipTests -T10 -Dcheckstyle.skip
> ```
> 
> In the first step, you need to compile all the Ray project. So you can reference to https://docs.ray.io/en/latest/ray-contribute/development.html#building-ray

does java version Ray support  windows ？ we need it ，now  I use apache spark  pytorch  in scala  with ray ,need  run test  on  windows ,please gen windows support,thanks

**Comment by zuston** [comment]
I meet the similar problems when using the ray java 2.9.0 .


```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/zuston/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.17.1/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/zuston/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/zuston/.m2/repository/org/slf4j/slf4j-reload4j/1.7.36/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]

java.lang.UnsatisfiedLinkError: /Users/zuston/Library/Caches/JNA/temp/jna4420077346987399926.tmp: dlopen(/Users/zuston/Library/Caches/JNA/temp/jna4420077346987399926.tmp, 0x0001): tried: '/Users/zuston/Library/Caches/JNA/temp/jna4420077346987399926.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zuston/Library/Caches/JNA/temp/jna4420077346987399926.tmp' (no such file), '/Users/zuston/Library/Caches/JNA/temp/jna4420077346987399926.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64'))

	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
	at java.lang.Runtime.load0(Runtime.java:783)
	at java.lang.System.load(System.java:1100)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:87)
	at io.ray.runtime.util.JniUtils.loadLibrary(JniUtils.java:47)
	at io.ray.runtime.RayNativeRuntime.<clinit>(RayNativeRuntime.java:53)
	at io.ray.runtime.DefaultRayRuntimeFactory.createRayRuntime(DefaultRayRuntimeFactory.java:32)
	at io.ray.api.Ray.init(Ray.java:32)
	at io.ray.api.Ray.init(Ray.java:19)
	at org.apache.uniffle.client.RayTest.test(RayTest.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)


Process finished with exit code 255
```
