### ISSUE TITLE
[Data] 

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#36727]
### What happened + What you expected to happen

I tried to read then shuffle same data, but I got an assertion error.

```
Traceback (most recent call last):                                                                                                                                                              
  File "/home/ray/default/repro.py", line 11, in <module>                                                                                                                                      
    data_pq.random_shuffle().get_internal_block_refs()                                                                                                                                         
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/dataset.py", line 4076, in get_internal_block_refs
    blocks = self._plan.execute().get_blocks()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/plan.py", line 571, in execute
    blocks = execute_to_legacy_block_list(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/legacy_compat.py", line 116, in execute_to_legacy_block_list
    block_list = _bundles_to_block_list(bundles)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/legacy_compat.py", line 349, in _bundles_to_block_list
    for ref_bundle in bundles:
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/interfaces.py", line 548, in __next__
    return self.get_next()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py", line 129, in get_next
    raise item
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py", line 181, in run
    while self._scheduling_loop_step(self._topology) and not self._shutdown:
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py", line 261, in _scheduling_loop_step
    update_operator_states(topology)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor_state.py", line 359, in update_operator_states
    op.all_inputs_done()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/operators/base_physical_operator.py", line 88, in all_inputs_done
    self._output_buffer, self._stats = self._bulk_fn(self._input_buffer, ctx)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/logical/rules/operator_fusion.py", line 316, in fused_all_to_all_transform_fn
    return down_transform_fn(blocks, ctx)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/planner/random_shuffle.py", line 60, in fn
    return scheduler.execute(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/planner/exchange/pull_based_shuffle_task_scheduler.py", line 72, in execute
    shuffle_map_metadata = map_bar.fetch_until_complete(shuffle_map_metadata)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/progress_bar.py", line 92, in fetch_until_complete
    for ref, result in zip(done, ray.get(done)):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/worker.py", line 2485, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): ray::map() (pid=2298, ip=10.0.1.87)
  File "/tmp/ray/session_2023-06-22_13-33-42_209475_129/runtime_resources/py_modules_files/_ray_pkg_175b5be2a45d9dbc/ray/data/_internal/planner/exchange/shuffle_task_spec.py", line 49, in map
    assert len(mapped_blocks) == 1, (
AssertionError: Expected upstream_map_fn to return one block, but instead returned 5 blocks
```

### Versions / Dependencies

Ray: e50e182e20431f785b73278636dc8ea51187ed86

### Reproduction script

```python
import ray

ds = ray.data.read_parquet( "s3://balaji-test-bucket2/reproduce_bug")
ds.random_shuffle().get_internal_block_refs()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by bveeramani** [comment]
We merge shuffles with upstream maps:

https://github.com/ray-project/ray/blob/d1101540dab9c9d4402126517637323301b2ad5d/python/ray/data/_internal/planner/exchange/shuffle_task_spec.py#L43-L45

In this case, the upstream map is a read:

https://github.com/ray-project/ray/blob/d1101540dab9c9d4402126517637323301b2ad5d/python/ray/data/_internal/planner/plan_read_op.py#L65-L67

The problem is that if block splitting is enabled, the read task can return multiple blocks:

https://github.com/ray-project/ray/blob/d1101540dab9c9d4402126517637323301b2ad5d/python/ray/data/datasource/datasource.py#L213-L215

**Comment by raulchen** [comment]
The issue is that when fusing a map + a shuffle, the shuffle's map function expects the upstream map to only return one block ([code here](https://github.com/ray-project/ray/blob/d1101540dab9c9d4402126517637323301b2ad5d/python/ray/data/_internal/planner/exchange/shuffle_task_spec.py#L43-L45)). 

However, the map (normal map or read) could potentially produce one or more blocks. Because we will split a large block into smaller ones. 

The following script can also reproduce this issue:
```
import ray
import numpy as np

ray.data.DatasetContext.get_current().target_max_block_size = 100
ds = ray.data.range(10)

def map(_):
    return {
        "data": np.zeros((100, 100)),
    }

ds.repartition(2).map(map).random_shuffle().materialize()
```

**Comment by raulchen** [comment]
I tried to fix this issue by making the shuffle map function able to handle multiple blocks ([draft PR](https://github.com/ray-project/ray/pull/36783)). 
However, this breaks `PullBasedShuffleTaskScheduler`, which needs to know the exact number of task returns (code [here](https://github.com/ray-project/ray/blob/4eab11e53df6fb93301367f720932655a6549059/python/ray/data/_internal/planner/exchange/pull_based_shuffle_task_scheduler.py#L61)). 

I think we may need to integrate streaming generator with PullBasedShuffleTaskScheduler to fix this issue. 

For now, my suggestion is to disable map + AllToAll fusion. What do you think? @stephanie-wang @ericl @c21

**Comment by ericl** [comment]
Hmm. Disabling fusion will have a pretty significant performance hit. On the other hand, modifying the task scheduler to deal with dynamic num blocks also seems tricky.

It sounds like we need to (1) change the num returns of map tasks to "dynamic", and (2) dynamically plan the reduce phase in case of split map blocks. We could do this now with the existing generator functionality afaik, without the full streaming generator.

**Comment by c21** [comment]
I think this is a bug in new optimizer backend.
New backend - https://github.com/ray-project/ray/blob/master/python/ray/data/_internal/planner/exchange/shuffle_task_spec.py#L45-L48
Old backend - https://github.com/ray-project/ray/blob/master/python/ray/data/_internal/shuffle_and_partition.py#L43-L47

We should allow the map function produces multiple blocks, and combine those blocks together, same as old backend. cc @scottjlee FYI.
