### ISSUE TITLE
[Data] `read_parquet` doesn't support partition filters

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#36753]
### What happened + What you expected to happen

Tried to read a bucket with both Parquet and JSON files, but got an error:

```
pyarrow.lib.ArrowInvalid: Error creating dataset. Could not read schema from 'ray-example-data/iris.json'. Is this a 'parquet' file?: Could not open Parquet input source 'ray-example-data/iris.json': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
```

I expected the JSON files to get ignored.

### Versions / Dependencies

Ray: 8e8e0a448cfbaa72b926f36890a16577f9d479c2

### Reproduction script

```python
import ray

ray.data.read_parquet("gs://ray-example-data/")
```

```
ray on  master [$?] via 🐍 v3.11.2 (.venv) on ☁️  balaji@anyscale.com took 9s 
❯ python repro.py
2023-06-22 22:02:54,274 INFO worker.py:1616 -- Started a local Ray instance.
Traceback (most recent call last):
  File "/Users/balaji/Documents/GitHub/ray/repro.py", line 5, in <module>
    ray.data.read_parquet("gs://ray-example-data/")
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/read_api.py", line 603, in read_parquet
    return read_datasource(
           ^^^^^^^^^^^^^^^^
  File "/Users/balaji/Documents/GitHub/ray/python/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/read_api.py", line 344, in read_datasource
    ) = ray.get(
        ^^^^^^^^
  File "/Users/balaji/Documents/GitHub/ray/python/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/balaji/Documents/GitHub/ray/python/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/balaji/Documents/GitHub/ray/python/ray/_private/worker.py", line 2485, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ArrowInvalid): ray::_get_read_tasks() (pid=6866, ip=127.0.0.1)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/read_api.py", line 1947, in _get_read_tasks
    reader = ds.create_reader(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/parquet_datasource.py", line 170, in create_reader
    return _ParquetDatasourceReader(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/datasource/parquet_datasource.py", line 204, in __init__
    pq_ds = pq.ParquetDataset(
            ^^^^^^^^^^^^^^^^^^
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 1776, in __new__
    return _ParquetDatasetV2(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 2490, in __init__
    self._dataset = ds.dataset(path_or_paths, filesystem=filesystem,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.11/site-packages/pyarrow/dataset.py", line 763, in dataset
    return _filesystem_dataset(source, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.11/site-packages/pyarrow/dataset.py", line 456, in _filesystem_dataset
    return factory.finish(schema)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_dataset.pyx", line 2752, in pyarrow._dataset.DatasetFactory.finish
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Error creating dataset. Could not read schema from 'ray-example-data/iris.json'. Is this a 'parquet' file?: Could not open Parquet input source 'ray-example-data/iris.json': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by bveeramani** [comment]
This issue is blocked on https://github.com/apache/arrow/issues/36278

**Comment by ericl** [comment]
@bveeramani isn't the `partition_filter` a pure Dataset functionality? It looks like its implemented in FileBasedDatasource but not in ParquetBaseDatasource.

**Comment by bveeramani** [comment]
The issue is that `ParquetDatasource` uses Arrow's [`ParquetDataset`](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetDataset.html), which requires all files to be Parquet. If we want to add `partition_filter`, we'd have to perform a non-trivial refactor.

If the problem is that you just need to exclude non-Parquet files, it's easier if Arrow exposes the `exclude_invalid_files` and you pass it as a keyword-arg to `read_parquet`:

```python
ray.data.read_parquet("s3://bucket-with-json/", dataset_kwargs={"exclude_invalid_files": True)
```

**Comment by martinbomio** [comment]
@bveeramani wouldn't that introduce a different way to exclude/filter files when reading from a datasource?

**Comment by bveeramani** [comment]
@martinbomio sort of. We wouldn't be introducing any new parameters (`dataset_kwargs` is already supported), but you're right that it'd be different than other `read_*` APIs that support partition filters.
