### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-68: character maps to <undefined>

### ISSUE THREAD

**Issue by phosseini** [ray-project/ray#36767]
### What happened + What you expected to happen

I'm running/testing my code on Windows that could successfully be completed on Mac. I'm facing the following error:

```
2023-06-23 16:56:48,324 WARNING tune.py:997 -- AIR_VERBOSITY is set, ignoring passed-in ProgressReporter for now.
Traceback (most recent call last):
  File "C:\Users\[my_user_name]\projects\nlp-engine\client\question_answering.py", line 126, in <module>
    best_trial = trainer.hyperparameter_search(
  File "C:\ProgramData\anaconda3\envs\[my_env]\lib\site-packages\transformers\trainer.py", line 2538, in hyperparameter_search
    best_run = backend_dict[backend](self, n_trials, direction, **kwargs)
  File "C:\ProgramData\anaconda3\envs\[my_env]\lib\site-packages\transformers\integrations.py", line 342, in run_hp_search_ray
    analysis = ray.tune.run(
  File "C:\ProgramData\anaconda3\envs\[my_env]\lib\site-packages\ray\tune\tune.py", line 1094, in run
    air_progress_reporter.experiment_started(
  File "C:\ProgramData\anaconda3\envs\[my_env]\lib\site-packages\ray\tune\experimental\output.py", line 728, in experiment_started
    print(
  File "C:\ProgramData\anaconda3\envs\[my_env]\lib\site-packages\ray\experimental\tqdm_ray.py", line 48, in safe_print
    _print(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\[my_env]\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-68: character maps to <undefined>
```

### Versions / Dependencies

Python: **3.9.16**
Ray: **3.0.0.dev0** (I installed Ray using the following file `ray-3.0.0.dev0-cp39-cp39-win_amd64.whl`)
Windows: **10 Pro** (this is VM on Azure)

### Reproduction script

Unfortunately can't share the code since it's part of a private repo for now.

### Issue Severity

High: It blocks me from completing my task.

**Comment by krfricke** [comment]
This should have been fixed after https://github.com/ray-project/ray/pull/35770 - can you make sure that your current installed wheels include this patch?
