### ISSUE TITLE
[release-test] `dask_on_ray_1tb_sort` failed.

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#36827]
https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_41mda5qqqjt1fwyd5l9jbbmyn9

```
(autoscaler +15s) Tip: use `ray status` to view detailed cluster status. To disable these messages, set RAY_SCHEDULER_EVENTS=0.
(autoscaler +15s) Resized to 264 CPUs.
Failed to load a file. core-nightly-test/df-100-0.parquet.gzip
Failed to load a file. core-nightly-test/df-100-0.parquet.gzip
Trial 0 start
Traceback (most recent call last):
  File "dask_on_ray/dask_on_ray_sort.py", line 212, in <module>
    file_path=args.file_path,
  File "dask_on_ray/dask_on_ray_sort.py", line 144, in trial
    df.set_index("a", shuffle="tasks", max_branch=float("inf")).head(
AttributeError: 'NoneType' object has no attribute 'set_index'
(dask:generate_s3_file-99bae9b7-2194-4254-8dbd-aa691056b0e9 pid=200, ip=10.0.47.86) S3 partition 5 exists [repeated 9x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
Subprocess return code: 1
[INFO 2023-06-26 08:46:10,196] anyscale_job_wrapper.py: 190  Process 1226 exited with return code 1.
[INFO 2023-06-26 08:46:10,196] anyscale_job_wrapper.py: 293  Finished with return code 1. Time taken: 92.94522974
[WARNING 2023-06-26 08:46:10,196] anyscale_job_wrapper.py: 68  Couldn't upload to cloud storage: '/tmp/release_test_out.json' does not exist.
upload: ../../../../../metrics_test_out.json to s3://ray-release-automation-results/working_dirs/dask_on_ray_1tb_sort/blvmxpwqsv/tmp/metrics_test_out.json
upload: ./output.json to s3://ray-release-automation-results/working_dirs/dask_on_ray_1tb_sort/blvmxpwqsv/tmp/output.json
```

**Comment by rkooo567** [comment]
Duplicate as https://github.com/ray-project/ray/issues/36827
