### ISSUE TITLE
[RLlib] PPO policy from checkpoint made in RLlib 2.4 not compatible with 2.5.1

### ISSUE THREAD

**Issue by Paolo-Fermin** [ray-project/ray#36830]
### What happened + What you expected to happen

I have checkpoints from PPO checkpoints that I have made in RLlib 2.4. When I attempt to load this checkpoint after upgrading to ray 2.5.1, I get the following error (with some paths modified/omitted): 
```
Traceback (most recent call last):
  File "path/to/my/test_load_algorithm.py", line 6, in <module>
    my_new_ppo = Algorithm.from_checkpoint("/path/to/my/ray_results/PPO/PPO_...")
  File "path/to/my/.venv/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 298, in from_checkpoint
    state = Algorithm._checkpoint_info_to_algorithm_state(
  File "path/to/my/.venv/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 2703, in _checkpoint_info_to_algorithm_state
    state = pickle.load(f)
ModuleNotFoundError: No module named 'ray.rllib.algorithms.ppo.ppo_learner_config'
```
It seems that a breaking change was made to PPO from 2.4->2.5, and thus the policies are no longer backwards compatible. However, the [docs](https://docs.ray.io/en/latest/rllib/rllib-saving-and-loading-algos-and-policies.html#which-algorithm-checkpoint-versions-can-i-use) promise backwards compatibility for all checkpoints made in ray 2.x or later. Doing some digging, it seems that the dataclass PPOLearnerHPs that used to be contained in [ray.rllib.algorithms.ppo.ppo_learner_config](https://github.com/ray-project/ray/blob/ray-2.4.0/rllib/algorithms/ppo/ppo_learner_config.py) has been moved to [ray.rllib.algorithms.ppo.ppo_learner](https://github.com/ray-project/ray/blob/ray-2.5.1/rllib/algorithms/ppo/ppo_learner.py) and renamed to PPOLearnerHyperparameters. Some python stub file with an import retain backwards compatibility for this class would be greatly appreciated

### Versions / Dependencies

Ray 2.5.1
Python 3.8
Ubuntu 20.04

### Reproduction script

Train script (taken directly from example in https://docs.ray.io/en/latest/rllib/rllib-training.html#using-the-python-api)
```
from ray.rllib.algorithms.ppo import PPOConfig

algo = (
    PPOConfig()
    .rollouts(num_rollout_workers=1)
    .resources(num_gpus=0)
    .environment(env="CartPole-v1")
    .build()
)

for i in range(10):
    result = algo.train()

    if i % 5 == 0:
        checkpoint_dir = algo.save()
        print(f"Checkpoint saved in directory {checkpoint_dir}")
```
Run script:
```
from ray.rllib.algorithms.algorithm import Algorithm

# Use the Algorithm's `from_checkpoint` utility to get a new algo instance
# that has the exact same state as the old one, from which the checkpoint was
# created in the first place:
my_new_ppo = Algorithm.from_checkpoint("path/to/checkpoint/")

# Continue training.
my_new_ppo.train()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by avnishn** [comment]
Something you can do here since you've changed ray versions is instead directly restore the underlying RLModule instead:

see this test for more details:

https://sourcegraph.com/github.com/ray-project/ray/-/blob/release/rllib_tests/checkpointing_tests/test_e2e_rl_module_restore.py?L176

we haven't gotten around to documenting this publicly yet, so than you for pointing that out so that I can take care of that :)

**Comment by Paolo-Fermin** [comment]
In that example, a PPOConfig object is created, before building a SingleAgentRLModuleSpec with the checkpoint path as initialization, then finally the SingleAgentRLModuleSpec is passed to PPOConfig via the rl_module() builder method. Is it possible to reload the RLModule without assuming anything about the AlgorithmConfig first? For example, I want something that is flexible enough to continue training any Algorithm without hardcoding it.

**Comment by Paolo-Fermin** [comment]
It also seems like SingleAgentRLModuleSpec doesn't accept load_state_path as an initialization arg as of Ray 2.5.1. Should I be working off of a nightly release?
