### ISSUE TITLE
APEX Multiagent incorrect policy mapping

### ISSUE THREAD

**Issue by mynkpl1998** [ray-project/ray#3688]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: Binary
- **Ray version**: 0.6.1

### Describe the problem
Hi, I am trying to use APEX for custom multi agent environment. However, I ran into an issue where during the training APEX is not mapping the policy correctly. I tried with other algorithms on my multi-agent environment and none of them raised any error like this. Exact error is reported below.

### Source code / logs

Error traceback:
```

Pushing error to dirver, type: task, message: ray_ApexAgent:train() (pid=19013, host=iiitd-MS-7B48)
  File "/home/sumantra/anaconda3/envs/mpython/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 283, in train
    result = Trainable.train(self)
  File "/home/sumantra/anaconda3/envs/mpython/lib/python3.6/site-packages/ray/tune/trainable.py", line 147, in train
    result = self._train()
  File "/home/sumantra/anaconda3/envs/mpython/lib/python3.6/site-packages/ray/rllib/agents/dqn/dqn.py", line 190, in _train
    self.update_target_if_needed()
  File "/home/sumantra/anaconda3/envs/mpython/lib/python3.6/site-packages/ray/rllib/agents/dqn/apex.py", line 54, in update_target_if_needed
    self.local_evaluator.for_policy(lambda p: p.update_target())
  File "/home/sumantra/anaconda3/envs/mpython/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 495, in for_policy
    return func(self.policy_map[policy_id])
KeyError: 'default'
```
Training Config file

```
apex-age-comm:
  run: APEX
  env: tsim-v0
  checkpoint_freq: 100
  config:
    n_step: 3
    lr: 0.0001
    num_gpus: 1
    num_workers: 4
    sample_batch_size: 50
    horizon: 1000
    train_batch_size: 512
    target_network_update_freq: 50000
    multiagent:
      policy_graphs: None
      policy_mapping_fn: None

```

Training Script

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import ray
from ray.tune.registry import register_env
from ray.rllib.agents.dqn.dqn_policy_graph import DQNPolicyGraph
from ray.rllib.agents.dqn.apex import ApexAgent

import yaml
from ray import tune
from ray.tune import run_experiments
from sim import tsim
from ray.tune.logger import pretty_print


def policy_mapper(agent_id):

	if agent_id == "age":
		return "age_policy"
	else:
		return "plan_policy"


if __name__ == "__main__":

	ray.init()

	with open("apex_config.yaml", "r") as handle:
		exp_config = yaml.load(handle)

	env_creator_name = "tsim-v0"
	register_env(env_creator_name, lambda config: tsim())
	tmp_env = tsim()

	age_obs_space = tmp_env.age_obs_space
	plan_obs_space = tmp_env.plan_obs_space
	age_act_space = tmp_env.age_act_space
	plan_act_space = tmp_env.plan_act_space

	def gen_policy(agent):

		config = {
			"gamma": 0.99
		}

		if agent == "age":
			obs = age_obs_space
			acts = age_act_space
		else:
			obs = plan_obs_space
			acts = plan_act_space

		return (DQNPolicyGraph, obs, acts, config)

	policy_graphs = {
		"age_policy": gen_policy("age"),
		"plan_policy": gen_policy("plan")
	}
	exp_config['apex-age-comm']["config"]["multiagent"]["policy_graphs"] = policy_graphs
	exp_config['apex-age-comm']["config"]["multiagent"]["policy_mapping_fn"] = tune.function(policy_mapper)

	run_experiments(exp_config)

```

**Comment by mynkpl1998** [comment]
I re-installed ray, I tried to build from source and also tried with latest binary but still, I am having the same issue. Here is the traceback.

```
Traceback (most recent call last):
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 353, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 222, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/worker.py", line 2292, in get
    raise value
ray.worker.RayTaskError: [36mray_ApexAgent:train()[39m (pid=33564, host=wsl)
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 283, in train
    result = Trainable.train(self)
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/tune/trainable.py", line 147, in train
    result = self._train()
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/rllib/agents/dqn/dqn.py", line 190, in _train
    self.update_target_if_needed()
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/rllib/agents/dqn/apex.py", line 54, in update_target_if_needed
    self.local_evaluator.for_policy(lambda p: p.update_target())
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 495, in for_policy
    return func(self.policy_map[policy_id])
KeyError: 'default'

```

**Comment by mynkpl1998** [comment]
I am posting the full error. It looks like, the issue is in checkpointing the model. 

```
Result for APEX_tsim-v0_0:
  custom_metrics: {}
  date: 2019-01-06_23-51-38
  done: false
  episode_len_mean: 13.443298969072165
  episode_reward_max: 12.090000000000002
  episode_reward_mean: -37.40547036082441
  episode_reward_min: -5004.999999999934
  episodes_this_iter: 194
  episodes_total: 194
  experiment_id: fbd4b0cdb8364b61b19c13eb4b6fb9f6
  hostname: wsl
  info:
    learner_queue:
      size_count: 15282
      size_mean: 0.08
      size_quantiles:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 2.0
      size_std: 0.33704599092705434
    max_exploration: 0.4
    min_exploration: 0.0
    num_samples_dropped: 15
    num_steps_sampled: 25000
    num_steps_trained: 0
    num_target_updates: 0
    num_weight_syncs: 55
    replay_shard_0:
      add_batch_time_ms: 12.708
      policy_age_policy:
        added_count: 6800
        est_size_bytes: 8881680
        num_entries: 6800
        sampled_count: 0
      policy_plan_policy:
        added_count: 6800
        est_size_bytes: 9670452
        num_entries: 6800
        sampled_count: 0
      replay_time_ms: .nan
      update_priorities_time_ms: .nan
    sample_throughput: 3915.657
    train_throughput: 0.0
  iterations_since_restore: 1
  node_ip: 192.168.1.205
  num_metric_batches_dropped: 0
  pid: 16026
  policy_reward_mean:
    age_policy: -29.5034085051543
    plan_policy: -7.902061855670103
  time_since_restore: 42.42207598686218
  time_this_iter_s: 42.42207598686218
  time_total_s: 42.42207598686218
  timestamp: 1546798898
  timesteps_since_restore: 25000
  timesteps_this_iter: 25000
  timesteps_total: 25000
  training_iteration: 1
  
Trial Runner checkpointing failed.
Traceback (most recent call last):
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 225, in step
    self.checkpoint()
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 120, in checkpoint
    json.dump(runner_state, f, indent=2)
  File "/home/mayankp/miniconda3/lib/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  [Previous line repeated 2 more times]
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'type' is not JSON serializable
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 23/32 CPUs, 1/1 GPUs
Memory usage on this node: 73.8/135.2 GB
Result logdir: /home/mayankp/ray_results/apex-age-comm-v2-v1
RUNNING trials:
 - APEX_tsim-v0_0:	RUNNING, 3 failures: /home/mayankp/ray_results/apex-age-comm-v2-v1/APEX_tsim-v0_0_2019-01-06_23-47-25kyfkueyv/error_2019-01-06_23-50-44.txt [pid=16026], 42 s, 1 iter, 25000 ts, -37.4 rew

Pushing error to dirver, type: task, message: [36mray_ApexAgent:train()[39m (pid=16026, host=wsl)
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 283, in train
    result = Trainable.train(self)
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/tune/trainable.py", line 147, in train
    result = self._train()
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/rllib/agents/dqn/dqn.py", line 190, in _train
    self.update_target_if_needed()
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/rllib/agents/dqn/apex.py", line 54, in update_target_if_needed
    self.local_evaluator.for_policy(lambda p: p.update_target())
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 495, in for_policy
    return func(self.policy_map[policy_id])
KeyError: 'default'
.Error processing event.
Traceback (most recent call last):
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 353, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 222, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/worker.py", line 2292, in get
    raise value
ray.worker.RayTaskError: [36mray_ApexAgent:train()[39m (pid=16026, host=wsl)
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 283, in train
    result = Trainable.train(self)
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/tune/trainable.py", line 147, in train
    result = self._train()
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/rllib/agents/dqn/dqn.py", line 190, in _train
    self.update_target_if_needed()
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/rllib/agents/dqn/apex.py", line 54, in update_target_if_needed
    self.local_evaluator.for_policy(lambda p: p.update_target())
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 495, in for_policy
    return func(self.policy_map[policy_id])
KeyError: 'default'


Trial Runner checkpointing failed.
Traceback (most recent call last):
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 225, in step
    self.checkpoint()
  File "/home/mayankp/miniconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 120, in checkpoint
    json.dump(runner_state, f, indent=2)
  File "/home/mayankp/miniconda3/lib/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  [Previous line repeated 2 more times]
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/home/mayankp/miniconda3/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'type' is not JSON serializable

```

**Comment by ericl** [comment]
That pull request is not in master, so you'll have to patch your install --
the stack trace you posted in not present in the PR branch...
