### ISSUE TITLE
[Core] (raylet) [2023-06-27 07:56:04,042 C 1257 1257] (raylet) local_task_manager.cc:431:  Check failed: task.GetTaskSpecification().PlacementGroupBundleId().first != PlacementGroupID::Nil() 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#36884]
### What happened + What you expected to happen

It looks like core could segfault with this error.

Based on what I see, it seems like it can happen if the resource usage goes to 0 before scheduling happens. I will do some initial investigation. 

```
Traceback (most recent call last):
  File "/home/ray/colabfold/evaluation_pipeline/afm_service.py", line 74, in <module>
    test_fxn('/home/ray/colabfold/fastas/vhh_sarscov.fasta')
  File "/home/ray/colabfold/evaluation_pipeline/afm_service.py", line 71, in test_fxn
    return ray.get(ray_object_ids)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/worker.py", line 2523, in get
    raise value
ray.exceptions.LocalRayletDiedError: The task's local raylet died. Check raylet.out for more information.
(raylet) [2023-06-27 07:56:04,042 C 1257 1257] (raylet) local_task_manager.cc:431:  Check failed: task.GetTaskSpecification().PlacementGroupBundleId().first != PlacementGroupID::Nil() 
(raylet) *** StackTrace Information ***
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x52ed5a) [0x557e949ced5a] ray::operator<<()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x530742) [0x557e949d0742] ray::SpdLogMessage::Flush()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x530a57) [0x557e949d0a57] ray::RayLog::~RayLog()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x2c2e81) [0x557e94762e81] ray::raylet::LocalTaskManager::PoppedWorkerHandler()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x2c3551) [0x557e94763551] std::_Function_handler<>::_M_invoke()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x237969) [0x557e946d7969] ray::raylet::WorkerPool::InvokePopWorkerCallbackForProcess()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x237c01) [0x557e946d7c01] ray::raylet::WorkerPool::PushWorker()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x28ca32) [0x557e9472ca32] ray::raylet::NodeManager::HandleWorkerAvailable()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x28cb5d) [0x557e9472cb5d] ray::raylet::NodeManager::HandleWorkerAvailable()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x28cc56) [0x557e9472cc56] ray::raylet::NodeManager::ProcessAnnounceWorkerPortMessage()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x29fdc2) [0x557e9473fdc2] ray::raylet::NodeManager::ProcessClientMessage()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x1ea171) [0x557e9468a171] std::_Function_handler<>::_M_invoke()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x4c54cd) [0x557e949654cd] ray::ClientConnection::ProcessMessage()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x50dcf6) [0x557e949adcf6] EventTracker::RecordExecution()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x4bc822) [0x557e9495c822] boost::asio::detail::binder2<>::operator()()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x4bcf78) [0x557e9495cf78] boost::asio::detail::reactive_socket_recv_op<>::do_complete()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0xa8d73b) [0x557e94f2d73b] boost::asio::detail::scheduler::do_run_one()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0xa8fcc9) [0x557e94f2fcc9] boost::asio::detail::scheduler::run()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0xa90182) [0x557e94f30182] boost::asio::io_context::run()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x16705a) [0x557e9460705a] main
(raylet) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f72272c9083] __libc_start_main
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x1ae457) [0x557e9464e457]
(raylet) 
```

### Versions / Dependencies

2.4

### Reproduction script

n/a

### Issue Severity

None

**Comment by zhe-thoughts** [comment]
@scv119 any luck on this? Thanks

**Comment by scv119** [comment]
the bug no longer show up in 2.5.0.
