### ISSUE TITLE
<Core> Worker unrecoverable failure on unserializable exceptions

### ISSUE THREAD

**Issue by jaychia** [ray-project/ray#36893]
### What happened + What you expected to happen

When returning non-pickleable objects from remote calls, Ray is fairly well-behaved and provides a nice friendly error:

```
RayTaskError(TypeError): ray::throw() (pid=91157, ip=127.0.0.1)
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 88, in dumps
    cp.dump(obj)
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 733, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle multidict._multidict.CIMultiDictProxy objects
```

However, if a non-pickleable exception is thrown, it seems that it results in a pretty scary looking worker failure.

```
...
TypeError: can't pickle multidict._multidict.CIMultiDictProxy objects
An unexpected internal error occurred while the worker was executing a task.
2023-06-27 17:19:03,949	WARNING worker.py:2019 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 62e0976023670f473c0711e466ac6916e8e36bfc01000000 Worker ID: 5be29f33e6dec58dc21818b312d2f85076852ec820f2f3fd98c71c93 Node ID: 3be3a0070d0678b7cacd4c56348e080ed6a818567cf996e419af85a3 Worker IP address: 127.0.0.1 Worker port: 65206 Worker PID: 91195 Worker exit type: SYSTEM_ERROR Worker exit detail: The leased worker has unrecoverable failure. Worker is requested to be destroyed when it is returned.
...
WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
```

### Versions / Dependencies

Ray 2.4.0 and 2.5.1
Python 3.10
M1 Mac and Linux

### Reproduction script

(using `multidict.CIMultiDictProxy` as an example of a non-pickleable object)

```python
import multidict  # (using `multidict.CIMultiDictProxy` as an example of a non-pickleable object)
import ray

ray.init()

@ray.remote
def throw():
    raise ValueError(multidict.CIMultiDictProxy(multidict.CIMultiDict(a="foo")))

ray.get(throw.remote())
```

This results in:

```
2023-06-27 17:16:51,052	WARNING worker.py:2019 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1431, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1510, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1434, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1438, in ray._raylet.execute_task
  File "<ipython-input-8-bbf9ebf6ee6c>", line 3, in throw
ValueError: <CIMultiDictProxy('a': 'foo')>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1796, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1695, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 1380, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1595, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.store_task_errors
  File "python/ray/_raylet.pyx", line 3456, in ray._raylet.CoreWorker.store_task_outputs
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/_private/serialization.py", line 466, in serialize
    return self._serialize_to_msgpack(value)
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/_private/serialization.py", line 421, in _serialize_to_msgpack
    value = value.to_bytes()
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/exceptions.py", line 32, in to_bytes
    serialized_exception=pickle.dumps(self),
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 88, in dumps
    cp.dump(obj)
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 733, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle multidict._multidict.CIMultiDictProxy objects
An unexpected internal error occurred while the worker was executing a task.
2023-06-27 17:16:51,054	WARNING worker.py:2019 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 34077524c2afebaed159fca135d386178717c17301000000 Worker ID: b31fb41267f65f3a8ed2c83e9f8e00a91cc433550d0c240504cb13ee Node ID: 3be3a0070d0678b7cacd4c56348e080ed6a818567cf996e419af85a3 Worker IP address: 127.0.0.1 Worker port: 65004 Worker PID: 90757 Worker exit type: SYSTEM_ERROR Worker exit detail: The leased worker has unrecoverable failure. Worker is requested to be destroyed when it is returned.
(throw pid=90757) 2023-06-27 17:16:51,052	ERROR worker.py:861 -- Worker exits with an exit code None. [repeated 4x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(throw pid=90757) Traceback (most recent call last): [repeated 20x across cluster]
(throw pid=90757)   File "python/ray/_raylet.pyx", line 1595, in ray._raylet.execute_task [repeated 48x across cluster]
(throw pid=90757)   File "<ipython-input-8-bbf9ebf6ee6c>", line 3, in throw [repeated 8x across cluster]
(throw pid=90757) ValueError: <CIMultiDictProxy('a': 'foo')> [repeated 8x across cluster]
(throw pid=90757)  [repeated 24x across cluster]
(throw pid=90757) During handling of the above exception, another exception occurred: [repeated 12x across cluster]
(throw pid=90757)   File "python/ray/_raylet.pyx", line 1838, in ray._raylet.task_execution_handler [repeated 12x across cluster]
(throw pid=90757)   File "python/ray/_raylet.pyx", line 1695, in ray._raylet.execute_task_with_cancellation_handler [repeated 8x across cluster]
(throw pid=90757)   File "python/ray/_raylet.pyx", line 875, in ray._raylet.store_task_errors [repeated 8x across cluster]
(throw pid=90757)   File "python/ray/_raylet.pyx", line 3456, in ray._raylet.CoreWorker.store_task_outputs [repeated 8x across cluster]
(throw pid=90757)   File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/_private/serialization.py", line 466, in serialize [repeated 8x across cluster]
(throw pid=90757)     return self._serialize_to_msgpack(value) [repeated 8x across cluster]
(throw pid=90757)   File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/_private/serialization.py", line 421, in _serialize_to_msgpack [repeated 8x across cluster]
(throw pid=90757)     value = value.to_bytes() [repeated 8x across cluster]
(throw pid=90757)   File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/exceptions.py", line 32, in to_bytes [repeated 8x across cluster]
(throw pid=90757)     serialized_exception=pickle.dumps(self), [repeated 8x across cluster]
(throw pid=90757)   File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 88, in dumps [repeated 8x across cluster]
(throw pid=90757)     cp.dump(obj) [repeated 8x across cluster]
(throw pid=90757)   File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 733, in dump [repeated 8x across cluster]
(throw pid=90757)     return Pickler.dump(self, obj) [repeated 8x across cluster]
(throw pid=90757) TypeError: can't pickle multidict._multidict.CIMultiDictProxy objects [repeated 8x across cluster]
(throw pid=90757) An unexpected internal error occurred while the worker was executing a task. [repeated 4x across cluster]
(throw pid=90757) SystemExit [repeated 4x across cluster]
2023-06-27 17:16:51,855	WARNING worker.py:2019 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1431, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1510, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1434, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1438, in ray._raylet.execute_task
  File "<ipython-input-8-bbf9ebf6ee6c>", line 3, in throw
ValueError: <CIMultiDictProxy('a': 'foo')>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1796, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1695, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 1380, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1595, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.store_task_errors
  File "python/ray/_raylet.pyx", line 3456, in ray._raylet.CoreWorker.store_task_outputs
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/_private/serialization.py", line 466, in serialize
    return self._serialize_to_msgpack(value)
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/_private/serialization.py", line 421, in _serialize_to_msgpack
    value = value.to_bytes()
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/exceptions.py", line 32, in to_bytes
    serialized_exception=pickle.dumps(self),
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 88, in dumps
    cp.dump(obj)
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 733, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle multidict._multidict.CIMultiDictProxy objects
An unexpected internal error occurred while the worker was executing a task.
2023-06-27 17:16:51,856	WARNING worker.py:2019 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: b7d58cda88252d0e1ab87ada2153986d2d93ad2901000000 Worker ID: fe635432c9382a71103d75578ff654b6f10949bef0e4231ddf86b5fd Node ID: 3be3a0070d0678b7cacd4c56348e080ed6a818567cf996e419af85a3 Worker IP address: 127.0.0.1 Worker port: 64997 Worker PID: 90754 Worker exit type: SYSTEM_ERROR Worker exit detail: The leased worker has unrecoverable failure. Worker is requested to be destroyed when it is returned.
2023-06-27 17:16:52,840	WARNING worker.py:2019 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1431, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1510, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1434, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1438, in ray._raylet.execute_task
  File "<ipython-input-8-bbf9ebf6ee6c>", line 3, in throw
ValueError: <CIMultiDictProxy('a': 'foo')>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1796, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1695, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 1380, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1595, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.store_task_errors
  File "python/ray/_raylet.pyx", line 3456, in ray._raylet.CoreWorker.store_task_outputs
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/_private/serialization.py", line 466, in serialize
    return self._serialize_to_msgpack(value)
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/_private/serialization.py", line 421, in _serialize_to_msgpack
    value = value.to_bytes()
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/exceptions.py", line 32, in to_bytes
    serialized_exception=pickle.dumps(self),
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 88, in dumps
    cp.dump(obj)
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 733, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle multidict._multidict.CIMultiDictProxy objects
An unexpected internal error occurred while the worker was executing a task.
2023-06-27 17:16:52,841	WARNING worker.py:2019 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 1b8210753bc404de287d73fb4cebce156fd17af401000000 Worker ID: 3b31ea64a306e8bb6901620a4ef1c0a8b8e1673c74c4a1aaf7bc98f9 Node ID: 3be3a0070d0678b7cacd4c56348e080ed6a818567cf996e419af85a3 Worker IP address: 127.0.0.1 Worker port: 64988 Worker PID: 90756 Worker exit type: SYSTEM_ERROR Worker exit detail: The leased worker has unrecoverable failure. Worker is requested to be destroyed when it is returned.
2023-06-27 17:16:53,856	WARNING worker.py:2019 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1431, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1510, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1434, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1438, in ray._raylet.execute_task
  File "<ipython-input-8-bbf9ebf6ee6c>", line 3, in throw
ValueError: <CIMultiDictProxy('a': 'foo')>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1796, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1695, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 1380, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1595, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.store_task_errors
  File "python/ray/_raylet.pyx", line 3456, in ray._raylet.CoreWorker.store_task_outputs
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/_private/serialization.py", line 466, in serialize
    return self._serialize_to_msgpack(value)
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/_private/serialization.py", line 421, in _serialize_to_msgpack
    value = value.to_bytes()
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/exceptions.py", line 32, in to_bytes
    serialized_exception=pickle.dumps(self),
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 88, in dumps
    cp.dump(obj)
  File "/Users/jaychia/code/Daft/venv/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 733, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle multidict._multidict.CIMultiDictProxy objects
An unexpected internal error occurred while the worker was executing a task.
2023-06-27 17:16:53,859	WARNING worker.py:2019 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: dd3ef888101b1c2b93cc075b7a1d6422eca61a0901000000 Worker ID: dfa4296cd3aaf93ffa46b223b08ee2cd49cad4fc8862ba83f2de9977 Node ID: 3be3a0070d0678b7cacd4c56348e080ed6a818567cf996e419af85a3 Worker IP address: 127.0.0.1 Worker port: 64980 Worker PID: 90755 Worker exit type: SYSTEM_ERROR Worker exit detail: The leased worker has unrecoverable failure. Worker is requested to be destroyed when it is returned.
---------------------------------------------------------------------------
WorkerCrashedError                        Traceback (most recent call last)
Cell In[9], line 1
----> 1 ray.get(throw.remote())

File ~/code/Daft/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py:18, in wrap_auto_init.<locals>.auto_init_wrapper(*args, **kwargs)
     15 @wraps(fn)
     16 def auto_init_wrapper(*args, **kwargs):
     17     auto_init_ray()
---> 18     return fn(*args, **kwargs)

File ~/code/Daft/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py:103, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    101     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    102         return getattr(ray, func.__name__)(*args, **kwargs)
--> 103 return func(*args, **kwargs)

File ~/code/Daft/venv/lib/python3.10/site-packages/ray/_private/worker.py:2542, in get(object_refs, timeout)
   2540             raise value.as_instanceof_cause()
   2541         else:
-> 2542             raise value
   2544 if is_individual_id:
   2545     values = values[0]

WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rkooo567** [comment]
Nice catch! I think we can fix it to have a smoother error message!
