### ISSUE TITLE
[Core] Activate Ray tracing casue error when calling actor method with decorator with wraps. (i propose the possible solution)

### ISSUE THREAD

**Issue by junehyuck-park** [ray-project/ray#36891]
### Summary

- Ray tracing doesn’t work with actor method with decorator implementing `functools.wraps`
- The error itself is raised inside `flatten_args` function during remote actor method call.
- I think the root cause of the bug is the “line 263 of `ray > actor.py`" which is `method = inspect.unwrap(method)` statement inside the `_ActorClassMethodMetadata.create()` method.
    - given ray version 2.5.0
- I propose deleting this line to fix bug.
    - Actually I did it and tracing works without problems.
    - the detailed reasoning is below

### Reproduction Script

```python
import ray
from functools import wraps
from time import sleep

ray.init(_tracing_startup_hook="ray.util.tracing.setup_local_tmp_tracing:setup_tracing")

def decorator_without_wraps(func):
    def wrapper(*args, **kwds):
        return func(*args, **kwds)
    return wrapper

def decorator_with_wraps(func):
    @wraps(func)
    def wrapper(*args, **kwds):
        return func(*args, **kwds)
    return wrapper

@ray.remote
class SimpleActor():
    @decorator_without_wraps
    def normal_method(self):
        print("this is normal method")
    
    @decorator_with_wraps
    def abnormal_method(self):
        print("this is abnormal method")

actor_handle = SimpleActor.remote()

# no problem
actor_handle.normal_method.remote()

# bug
actor_handle.abnormal_method.remote()

sleep(5)
```

### Error Log

```
2023-06-28 07:43:58,271 INFO worker.py:1627 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
Traceback (most recent call last):
  File "/home/jhpark/ray_issue_20230628/test.py", line 35, in <module>
    actor_handle.abnormal_method.remote()
  File "/home/jhpark/ray_issue_20230628/ray-issue-venv/lib/python3.10/site-packages/ray/actor.py", line 144, in remote
    return self._remote(args, kwargs)
  File "/home/jhpark/ray_issue_20230628/ray-issue-venv/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 442, in _start_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/home/jhpark/ray_issue_20230628/ray-issue-venv/lib/python3.10/site-packages/ray/actor.py", line 190, in _remote
    return invocation(args, kwargs)
  File "/home/jhpark/ray_issue_20230628/ray-issue-venv/lib/python3.10/site-packages/ray/actor.py", line 177, in invocation
    return actor._actor_method_call(
  File "/home/jhpark/ray_issue_20230628/ray-issue-venv/lib/python3.10/site-packages/ray/actor.py", line 1160, in _actor_method_call
    list_args = signature.flatten_args(function_signature, args, kwargs)
  File "/home/jhpark/ray_issue_20230628/ray-issue-venv/lib/python3.10/site-packages/ray/_private/signature.py", line 114, in flatten_args
    raise TypeError(str(exc)) from None
TypeError: got an unexpected keyword argument '_ray_trace_ctx'
(SimpleActor pid=6299) this is normal method
```

### Reasoning

- `_ray_trace_ctx` is injected to the method’s signature(`__signature__`) inside `ray.actor._make_actor` function during building `ActorClass` **(whether tracing is turn on or off)**
    - However `modified_cls` method is wrapping function of this method(which has `__signature__` with `_ray_trace_ctx`)
- This signature information should inject to `_ActorClassMetadata.method_meta`(which later used in `flatten_args` function and raise this bug)
    - This injection should be done inside `_ActorClassMethodMetadata.create` class method.
    - However `method = inspect.unwrap(method)` statement in line 263 unwrap too much when method already had decorator with wraps.
- I think the author might want to `method = method.__wrapped__`. However `inspect.unwrap` did this job recursively and this behavior cause this bug.
- I suggest delete this line because `signature.extract_signature` function called in line 272 can handle this requirement and precisely read `__signature__` object created through above process.
    - `signature.extract_signature` function rely on `inspect.signature` funciton and…
    - Because the `inspect.signature` is implemented through following algorithm ([PEP 362 – Function Signature Object | peps.python.org](https://peps.python.org/pep-0362/#implementation))
        - If the object is not callable - raise a TypeError
        - ⭐ **If the object has a `__signature__` attribute and if it is not `None` - return it**
        - ⭐ **If it has a `__wrapped__` attribute, return `signature(object.__wrapped__)`**
        - If the object is an instance of `FunctionType`, construct and return a new `Signature` for it
        - If the object is a bound method, construct and return a new `Signature` object, with its first parameter (usually `self` or `cls`) removed. (`classmethod` and `staticmethod` are supported too. Since both are descriptors, the former returns a bound method, and the latter returns its wrapped function.)
        - If the object is an instance of `functools.partial`, construct a new `Signature` from its `partial.func` attribute, and account for already bound `partial.args` and `partial.kwargs`
        - If the object is a class or metaclass:
            - If the object’s type has a `__call__` method defined in its MRO, return a Signature for it
            - If the object has a `__new__` method defined in its MRO, return a Signature object for it
            - If the object has a `__init__` method defined in its MRO, return a Signature object for it
        - Return `signature(object.__call__)`

Thanks.

### Versions / Dependencies

```
python: 3.10.11

ray[default]==2.5.0 
opentelemetry-api==1.1.0
opentelemetry-sdk==1.1.0
opentelemetry-exporter-otlp==1.1.0
```

### Reproduction script

```python
import ray
from functools import wraps
from time import sleep

ray.init(_tracing_startup_hook="ray.util.tracing.setup_local_tmp_tracing:setup_tracing")

def decorator_without_wraps(func):
    def wrapper(*args, **kwds):
        return func(*args, **kwds)
    return wrapper

def decorator_with_wraps(func):
    @wraps(func)
    def wrapper(*args, **kwds):
        return func(*args, **kwds)
    return wrapper

@ray.remote
class SimpleActor():
    @decorator_without_wraps
    def normal_method(self):
        print("this is normal method")
    
    @decorator_with_wraps
    def abnormal_method(self):
        print("this is abnormal method")

actor_handle = SimpleActor.remote()

# no problem
actor_handle.normal_method.remote()

# bug
actor_handle.abnormal_method.remote()

sleep(5)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rkooo567** [comment]
tracing feature is currenetly experimental, and we don't have bandwidth to improve. Please feel free to create contribution!

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
