### ISSUE TITLE
ray.init: can't find 'total memory' in 'vmstat' output

### ISSUE THREAD

**Issue by justusschock** [ray-project/ray#3690]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.0
- **Python version**: 3.7
- **Exact command to reproduce**: `ray.init()`

### Describe the problem
When calling the above function, the program exits with 
`ValueError: Can't find b'total memory' in 'vmstat' output.`

### Source code / logs
Traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/temp/schock/conda/envs/delira/lib/python3.7/site-packages/ray/worker.py", line 1727, in init
    _internal_config=_internal_config)
  File "/home/temp/schock/conda/envs/delira/lib/python3.7/site-packages/ray/worker.py", line 1489, in _init
    _internal_config=_internal_config)
  File "/home/temp/schock/conda/envs/delira/lib/python3.7/site-packages/ray/services.py", line 1730, in start_ray_head
    _internal_config=_internal_config)
  File "/home/temp/schock/conda/envs/delira/lib/python3.7/site-packages/ray/services.py", line 1475, in start_ray_processes
    redis_password=redis_password)
  File "/home/temp/schock/conda/envs/delira/lib/python3.7/site-packages/ray/services.py", line 1108, in start_plasma_store
    object_store_memory, plasma_directory, huge_pages)
  File "/home/temp/schock/conda/envs/delira/lib/python3.7/site-packages/ray/services.py", line 1017, in determine_plasma_store_config
    system_memory = ray.utils.get_system_memory()
  File "/home/temp/schock/conda/envs/delira/lib/python3.7/site-packages/ray/utils.py", line 321, in get_system_memory
    return vmstat("total memory") * bytes_in_kilobyte
  File "/home/temp/schock/conda/envs/delira/lib/python3.7/site-packages/ray/utils.py", line 282, in vmstat
    raise ValueError("Can't find {} in 'vmstat' output.".format(stat))
```

**Comment by robertnishihara** [comment]
Can you share the output of running `vmstat -s` from the command line?

As a quick workaround, you can install `psutil`, e.g., `pip install psutil` or `conda install psutil`. Ray falls back to using `vmstat` to determine how much memory is available only when `psutil` is not installed.

You might also try `ray==0.6.1` although I don't think that will change it.

**Comment by richardliaw** [comment]
Yeah - is there some flag to get an english output? We just want to check for "total memory".

**Comment by justusschock** [comment]
I don't think there is a flag for that. But psutil works fine for me.

**Comment by richardliaw** [comment]
OK, closing for now - feel free to reopen.
