### ISSUE TITLE
Jenkins test failure in rllib/test/run_regression_tests.py, "Can't call numpy() on Variable that requires grad."

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#3694]
The following test failure has been very common in Jenkins recently. E.g., https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/10597/console.

```
+ docker run --rm --shm-size=20G --memory=20G 807aba1c63b781bb970c1b7ae237be11eb45a4770613a73d5ed8fdaa1aa281f1 python /ray/python/ray/rllib/test/run_regression_tests.py /ray/python/ray/rllib/tuned_examples/regression_tests/cartpole-a2c-torch.yaml
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
WARNING: Not updating worker name since `setproctitle` is not installed. Install this with `pip install setproctitle` (or ray[debug]) to enable monitoring of worker processes.
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-01-05_02-42-54_1/logs.
Waiting for redis server at 127.0.0.1:27509 to respond...
Waiting for redis server at 127.0.0.1:17338 to respond...
Starting Redis shard with 10.0 GB max memory.
Starting the Plasma object store with 8.589934592 GB memory using /dev/shm.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui.ipynb?token=3f47b5a03fb0587447f94b9ecb11719cd724bc09bd0bba12
======================================================================

Did not find checkpoint file in /root/ray_results/cartpole-a2c-torch.
Starting a new experiment.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/48 CPUs, 0/0 GPUs
Memory usage on this node: 25.0/405.7 GB

Created LogSyncer for /root/ray_results/cartpole-a2c-torch/A2C_CartPole-v0_0_2019-01-05_02-43-03O2b49V -> 
Worker ip unknown, skipping log sync for /root/ray_results/cartpole-a2c-torch/A2C_CartPole-v0_0_2019-01-05_02-43-03O2b49V
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 1/48 CPUs, 0/0 GPUs
Memory usage on this node: 27.4/405.7 GB
Result logdir: /root/ray_results/cartpole-a2c-torch
RUNNING trials:
 - A2C_CartPole-v0_0:	RUNNING

Pushing error to dirver, type: task, message: ray_worker (pid=70, host=377469b1410c)
  File "/ray/python/ray/rllib/agents/agent.py", line 283, in train
    result = Trainable.train(self)
  File "/ray/python/ray/tune/trainable.py", line 147, in train
    result = self._train()
  File "/ray/python/ray/rllib/agents/a3c/a3c.py", line 68, in _train
    self.optimizer.step()
  File "/ray/python/ray/rllib/optimizers/sync_samples_optimizer.py", line 51, in step
    samples.append(self.local_evaluator.sample())
  File "/ray/python/ray/rllib/evaluation/policy_evaluator.py", line 364, in sample
    batches = [self.input_reader.next()]
  File "/ray/python/ray/rllib/offline/input_reader.py", line 28, in next
    batches = [self.sampler.get_data()]
  File "/ray/python/ray/rllib/evaluation/sampler.py", line 64, in get_data
    item = next(self.rollout_provider)
  File "/ray/python/ray/rllib/evaluation/sampler.py", line 267, in _env_runner
    preprocessors, obs_filters, unroll_length, pack, callbacks)
  File "/ray/python/ray/rllib/evaluation/sampler.py", line 392, in _process_observations
    outputs.append(episode.batch_builder.build_and_reset(episode))
  File "/ray/python/ray/rllib/evaluation/sample_batch.py", line 159, in build_and_reset
    self.postprocess_batch_so_far(episode)
  File "/ray/python/ray/rllib/evaluation/sample_batch.py", line 140, in postprocess_batch_so_far
    pre_batch, other_batches, episode)
  File "/ray/python/ray/rllib/agents/a3c/a3c_torch_policy_graph.py", line 77, in postprocess_trajectory
    last_r = self._value(sample_batch["new_obs"][-1])
  File "/ray/python/ray/rllib/agents/a3c/a3c_torch_policy_graph.py", line 85, in _value
    return vf.numpy().squeeze()
RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.
.
Error processing event.
Traceback (most recent call last):
  File "/ray/python/ray/tune/trial_runner.py", line 353, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/ray/python/ray/tune/ray_trial_executor.py", line 213, in fetch_result
    result = ray.get(trial_future[0])
  File "/ray/python/ray/worker.py", line 2292, in get
    raise value
RayTaskError: ray_worker (pid=70, host=377469b1410c)
  File "/ray/python/ray/rllib/agents/agent.py", line 283, in train
    result = Trainable.train(self)
  File "/ray/python/ray/tune/trainable.py", line 147, in train
    result = self._train()
  File "/ray/python/ray/rllib/agents/a3c/a3c.py", line 68, in _train
    self.optimizer.step()
  File "/ray/python/ray/rllib/optimizers/sync_samples_optimizer.py", line 51, in step
    samples.append(self.local_evaluator.sample())
  File "/ray/python/ray/rllib/evaluation/policy_evaluator.py", line 364, in sample
    batches = [self.input_reader.next()]
  File "/ray/python/ray/rllib/offline/input_reader.py", line 28, in next
    batches = [self.sampler.get_data()]
  File "/ray/python/ray/rllib/evaluation/sampler.py", line 64, in get_data
    item = next(self.rollout_provider)
  File "/ray/python/ray/rllib/evaluation/sampler.py", line 267, in _env_runner
    preprocessors, obs_filters, unroll_length, pack, callbacks)
  File "/ray/python/ray/rllib/evaluation/sampler.py", line 392, in _process_observations
    outputs.append(episode.batch_builder.build_and_reset(episode))
  File "/ray/python/ray/rllib/evaluation/sample_batch.py", line 159, in build_and_reset
    self.postprocess_batch_so_far(episode)
  File "/ray/python/ray/rllib/evaluation/sample_batch.py", line 140, in postprocess_batch_so_far
    pre_batch, other_batches, episode)
  File "/ray/python/ray/rllib/agents/a3c/a3c_torch_policy_graph.py", line 77, in postprocess_trajectory
    last_r = self._value(sample_batch["new_obs"][-1])
  File "/ray/python/ray/rllib/agents/a3c/a3c_torch_policy_graph.py", line 85, in _value
    return vf.numpy().squeeze()
RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

Worker ip unknown, skipping log sync for /root/ray_results/cartpole-a2c-torch/A2C_CartPole-v0_0_2019-01-05_02-43-03O2b49V
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/48 CPUs, 0/0 GPUs
Memory usage on this node: 28.0/405.7 GB
Result logdir: /root/ray_results/cartpole-a2c-torch
ERROR trials:
 - A2C_CartPole-v0_0:	ERROR, 1 failures: /root/ray_results/cartpole-a2c-torch/A2C_CartPole-v0_0_2019-01-05_02-43-03O2b49V/error_2019-01-05_02-43-08.txt

Traceback (most recent call last):
  File "/ray/python/ray/rllib/test/run_regression_tests.py", line 24, in <module>
== Test config ==
cartpole-a2c-torch:
  config: {num_workers: 0, use_pytorch: true}
  env: CartPole-v0
  run: A2C
  stop: {episode_reward_mean: 100, timesteps_total: 100000}

    trials = run_experiments(experiments, resume=False)
  File "/ray/python/ray/tune/tune.py", line 186, in run_experiments
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [A2C_CartPole-v0_0])
Build step 'Execute shell' marked build as failure
Setting commit status on GitHub for https://github.com/ray-project/ray/commit/0469231d44a1d33149b512c45427eb90909aed43
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/10597/
Test FAILed.
Finished: FAILURE
```

**Comment by richardliaw** [comment]
This is already fixed via #3681. 

Try rebasing off master?

**Comment by richardliaw** [comment]
(Feel free to close if rebasing off master on whatever PR you're seeing this on fixes it)

**Comment by richardliaw** [comment]
Closing this because it should be fixed.
