### ISSUE TITLE
[streaming] `RaySystemError('Unrecognized error type 24')` when running basic Serve example

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#36956]
Seeing the following error message for every HTTP request:
```
(HTTPProxyActor pid=61263) Task exception was never retrieved
(HTTPProxyActor pid=61263) future: <Task finished name='Task-16' coro=<_wrap_awaitable() done, defined at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/tasks.py:688> exception=RaySystemError('Unrecognized error type 24')>
(HTTPProxyActor pid=61263) Traceback (most recent call last):
(HTTPProxyActor pid=61263)   File "/Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
(HTTPProxyActor pid=61263)     return (yield from awaitable.__await__())
(HTTPProxyActor pid=61263) ray.exceptions.RaySystemError: System error: Unrecognized error type 24
```

Repro steps:

`test.py`:
```python
from ray import serve

@serve.deployment
class Greeter:
    def __call__(self, *args):
        return "hi"

app = Greeter.bind()
```

In one terminal:
`RAY_SERVE_ENABLE_EXPERIMENTAL_STREAMING=1 serve run test:app`

In another terminal:
```
(ray) eoakes@Edwards-MBP-2 serve % curl -X GET http://localhost:8000/
hi%
```

You'll see logs in the first terminal like:
```
(HTTPProxyActor pid=61263) Task exception was never retrieved
(HTTPProxyActor pid=61263) future: <Task finished name='Task-16' coro=<_wrap_awaitable() done, defined at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/tasks.py:688> exception=RaySystemError('Unrecognized error type 24')>
(HTTPProxyActor pid=61263) Traceback (most recent call last):
(HTTPProxyActor pid=61263)   File "/Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
(HTTPProxyActor pid=61263)     return (yield from awaitable.__await__())
(HTTPProxyActor pid=61263) ray.exceptions.RaySystemError: System error: Unrecognized error type 24
```

**Comment by edoakes** [comment]
It's likely coming from this line:
https://github.com/ray-project/ray/blob/master/python/ray/_raylet.pyx#L337

`asyncio.wait` will convert the coroutine to a future and that ref is likely raising some kind of exception we don't retrieve.

**Comment by edoakes** [comment]
Confirmed the above with this change:
```
 335         ref = core_worker.peek_object_ref_stream(
 336             self._generator_ref)
 337         async def wrap():
 338             try:
 339                 await ref
 340             except Exception as e:
 341                 print(e)
```

Now we just get:
`(HTTPProxyActor pid=62192) System error: Unrecognized error type 24`
