### ISSUE TITLE
[core] cluster launcher test failure

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#37060]
### What happened + What you expected to happen

```
[notice] A new release of pip available: 22.1.2 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
Shared connection to 34.222.195.75 closed.
2023-06-30 20:10:29,128 INFO updater.py:489 -- [7/7] Starting the Ray runtime
2023-06-30 20:10:29,128 VINFO command_runner.py:371 -- Running `export RAY_USAGE_STATS_ENABLED=1;export RAY_OVERRIDE_RESOURCES='{"CPU":2}';ray stop`
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/bin/ray", line 5, in <module>
    from ray.scripts.scripts import main
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/scripts/scripts.py", line 2442, in <module>
    from ray.util.state.state_cli import (
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/util/state/__init__.py", line 1, in <module>
    from ray.util.state.api import (
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/util/state/api.py", line 17, in <module>
    from ray.util.state.common import (
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/util/state/common.py", line 120, in <module>
    @dataclass(init=True)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/pydantic/dataclasses.py", line 139, in dataclass
    assert init is False, 'pydantic.dataclasses.dataclass only supports init=False'
AssertionError: pydantic.dataclasses.dataclass only supports init=False
Shared connection to 34.222.195.75 closed.
2023-06-30 20:10:43,087 ERR updater.py:158 -- New status: update-failed
2023-06-30 20:10:43,087 ERR updater.py:160 -- !!!
2023-06-30 20:10:43,087 VERR updater.py:168 -- {'message': 'SSH command failed.'}
2023-06-30 20:10:43,087 ERR updater.py:170 -- SSH command failed.
2023-06-30 20:10:43,087 ERR updater.py:172 -- !!!
2023-06-30 20:10:43,210 PANIC commands.py:830 -- Failed to setup head node.
Error: Failed to setup head node.
Traceback (most recent call last):
  File "launch_and_verify_cluster.py", line 225, in <module>
    run_ray_commands(cluster_config, retries, no_config_cache)
  File "launch_and_verify_cluster.py", line 124, in run_ray_commands
    subprocess.run(cmd, check=True)
  File "/home/ray/anaconda3/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ray', 'up', '-v', '-y', '/tmp/tmpmormtx31.yaml']' returned non-zero exit status 1.
Subprocess return code: 1
[INFO 2023-06-30 20:10:43,781] anyscale_job_wrapper.py: 190  Process 1177 exited with return code 1.
[INFO 2023-06-30 20:10:43,781] anyscale_job_wrapper.py: 292  Finished with return code 1. Time taken: 215.32972184599998
[WARNING 2023-06-30 20:10:43,781] anyscale_job_wrapper.py: 68  Couldn't upload to cloud storage: '/tmp/release_test_out.json' does not exist.
upload: ../../../../../metrics_test_out.json to s3://ray-release-automation-results/working_dirs/aws_cluster_launcher_minimal/qqkfgdsqjm/tmp/metrics_test_out.json
upload: ./output.json to s3://ray-release-automation-results/working_dirs/aws_cluster_launcher_minimal/qqkfgdsqjm/tmp/output.json
[INFO 2023-06-30 20:11:31,040] anyscale_job_wrapper.py: 345  ### Finished ###
[INFO 2023-06-30 20:11:31,040] anyscale_job_wrapper.py: 348  ### JSON |{"collected_metrics":true,"last_prepare_time_taken":null,"prepare_return_codes":[],"return_code":1,"total_time_taken":261.871214502,"uploaded_artifact":false,"uploaded_metrics":true,"uploaded_results":false,"workload_time_taken":215.32972184599998}| ###`

### Versions / Dependencies

latest

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by scv119** [comment]
https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_uj5m13c3mmuceangiyq7s2w5dw

**Comment by can-anyscale** [comment]
FYI, also fixed and picked with this https://github.com/ray-project/ray/commit/879249b490f41d6af7ca13d4c3f4a5110af08d09

**Comment by rkooo567** [comment]
I think it is safe to close it. We will also merge https://github.com/ray-project/ray/pull/37055 for a fundamental fix
