### ISSUE TITLE
[Tune] ImportError: cannot import name 'WandbLogger' from 'ray.tune.integration.wandb'

### ISSUE THREAD

**Issue by c4cld** [ray-project/ray#37086]
### What happened + What you expected to happen

```Traceback (most recent call last):
  File "/root/anaconda3/envs/scenarionet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/scenarionet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/aliyun/scenarionet-20230705/scenarionet_training/scripts/train_waymo.py", line 81, in <module>
    train(
  File "/root/aliyun/scenarionet-20230705/scenarionet_training/train_utils/utils.py", line 140, in train
    from scenarionet_training.wandb_utils.our_wandb_callbacks_ray100 import OurWandbLogger
  File "/root/aliyun/scenarionet-20230705/scenarionet_training/wandb_utils/our_wandb_callbacks_ray100.py", line 3, in <module>
    from ray.tune.integration.wandb import WandbLogger, _clean_log, _set_api_key
ImportError: cannot import name 'WandbLogger' from 'ray.tune.integration.wandb' (/root/anaconda3/envs/scenarionet/lib/python3.9/site-packages/ray/tune/integration/wandb.py)


### Versions / Dependencies

ray == 2.0.0
wandb == -.15.3

### Reproduction script

```Traceback (most recent call last):
  File "/root/anaconda3/envs/scenarionet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/scenarionet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/aliyun/scenarionet-20230705/scenarionet_training/scripts/train_waymo.py", line 81, in <module>
    train(
  File "/root/aliyun/scenarionet-20230705/scenarionet_training/train_utils/utils.py", line 140, in train
    from scenarionet_training.wandb_utils.our_wandb_callbacks_ray100 import OurWandbLogger
  File "/root/aliyun/scenarionet-20230705/scenarionet_training/wandb_utils/our_wandb_callbacks_ray100.py", line 3, in <module>
    from ray.tune.integration.wandb import WandbLogger, _clean_log, _set_api_key
ImportError: cannot import name 'WandbLogger' from 'ray.tune.integration.wandb' (/root/anaconda3/envs/scenarionet/lib/python3.9/site-packages/ray/tune/integration/wandb.py)


### Issue Severity

High: It blocks me from completing my task.

**Comment by woshiyyya** [comment]
Hey @c4cld , I noticed that you are using `ray==2.0.0`. We don't have `WandbLogger` in 2.0.0, can you update to 2.5 instead?

**Comment by c4cld** [comment]
Thank you for your concern. I have addressed this issue by downgrading the versions of wandb and ray.

**Comment by woshiyyya** [comment]
Close it now. 

Update: We've deprecated `ray.tune.integration.wandb.WandbLogger `. Users can directly import and use wandb library in your training function.
