### ISSUE TITLE
Run ray cli get error

### ISSUE THREAD

**Issue by imperio-wxm** [ray-project/ray#37135]
### What happened + What you expected to happen

- ray start --address=xxx
```
Traceback (most recent call last):
  File "/usr/local/python3/bin/ray", line 5, in <module>
    from ray.scripts.scripts import main
  File "/usr/local/python3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 2430, in <module>
    from ray.util.state.state_cli import (
  File "/usr/local/python3/lib/python3.8/site-packages/ray/util/state/__init__.py", line 1, in <module>
    from ray.util.state.api import (
  File "/usr/local/python3/lib/python3.8/site-packages/ray/util/state/api.py", line 17, in <module>
    from ray.util.state.common import (
  File "/usr/local/python3/lib/python3.8/site-packages/ray/util/state/common.py", line 120, in <module>
    @dataclass(init=True)
  File "/usr/local/python3/lib/python3.8/site-packages/pydantic/dataclasses.py", line 139, in dataclass
    assert init is False, 'pydantic.dataclasses.dataclass only supports init=False'
```
- pip list
```
Package                  Version
------------------------ ----------
aiohttp                  3.8.4
aiohttp-cors             0.7.0
aiosignal                1.3.1
annotated-types          0.5.0
async-timeout            4.0.2
attrs                    23.1.0
blessed                  1.20.0
cachetools               5.3.1
certifi                  2023.5.7
charset-normalizer       3.1.0
click                    8.1.3
colorful                 0.5.5
distlib                  0.3.6
filelock                 3.12.2
frozenlist               1.3.3
google-api-core          2.11.1
google-auth              2.21.0
googleapis-common-protos 1.59.1
gpustat                  1.1
grpcio                   1.51.3
idna                     3.4
importlib-resources      5.12.0
jsonschema               4.17.3
msgpack                  1.0.5
multidict                6.0.4
numpy                    1.24.4
nvidia-ml-py             11.525.131
opencensus               0.11.2
opencensus-context       0.1.3
packaging                23.1
pip                      23.1.2
pkgutil_resolve_name     1.3.10
platformdirs             3.8.0
prometheus-client        0.17.0
protobuf                 4.23.3
psutil                   5.9.5
py-spy                   0.3.14
pyasn1                   0.5.0
pyasn1-modules           0.3.0
pydantic                 2.0.2
pydantic_core            2.1.2
pyrsistent               0.19.3
PyYAML                   6.0
ray                      2.5.0
requests                 2.31.0
rsa                      4.9
setuptools               56.0.0
six                      1.16.0
smart-open               6.3.0
typing_extensions        4.7.1
urllib3                  1.26.16
virtualenv               20.21.0
wcwidth                  0.2.6
yarl                     1.9.2
zipp                     3.15.0
```

### Versions / Dependencies

ray: 2.5.0
python: 3.8.10

### Reproduction script

ray start --address=xxx

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment]
This is the same issue as https://github.com/ray-project/ray/issues/37019. Closing it as dupliate
