### ISSUE TITLE
[<Ray component: Core|RLlib|etc...>] 

### ISSUE THREAD

**Issue by kmattim5** [ray-project/ray#37224]
### What happened + What you expected to happen

Registering the env: tune.register_env(select_test_env, lambda config: NR_IES_test_v0(test_config))

    ray.shutdown()

Rollout Command: 
    rollout_command = f"rllib rollout {best_checkpoint._local_path} --config '{{\"env\": \"NR_IES_test-v0\"}}' --run PPO --no-render --steps 2880"

    # execute the command using subprocess
    subprocess.run(rollout_command, shell=True)
I'm getting the below error when tried to perform the rollout command to test the model using the checkpoints created in training.

2023-07-08 16:05:19,459 INFO algorithm.py:354 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=53288) /home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
(pid=53288)   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
(pid=53288) /home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
(pid=53288)   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
(pid=53288) /home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
(pid=53288)   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
(pid=53288) /home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
(pid=53288)   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
(pid=53288) /home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
(pid=53288)   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
(pid=53288) /home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
(pid=53288)   np_resource = np.dtype([("resource", np.ubyte, 1)])
(pid=53288) /home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
(pid=53288)   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
(pid=53288) /home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
(pid=53288)   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
(pid=53288) /home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
(pid=53288)   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
(pid=53288) /home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
(pid=53288)   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
(pid=53288) /home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
(pid=53288)   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
(pid=53288) /home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
(pid=53288)   np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py", line 425, in setup
    logdir=self.logdir,
  File "/home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 127, in __init__
    validate=trainer_config.get("validate_workers_after_construction"),
  File "/home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 269, in add_workers
    self.foreach_worker(lambda w: w.assert_healthy())
  File "/home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 391, in foreach_worker
    remote_results = ray.get([w.apply.remote(func) for w in self.remote_workers()])
  File "/home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/ray/_private/worker.py", line 2277, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=53288, ip=131.183.21.110, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f4668c68c50>)
KeyError: 'NR_IES_test-v0'

During handling of the above exception, another exception occurred:

ray::RolloutWorker.__init__() (pid=53288, ip=131.183.21.110, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f4668c68c50>)
  File "/home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/env/utils.py", line 50, in _gym_env_creator
    return gym.make(env_descriptor, **env_context)
  File "/home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/gym/envs/registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "/home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/gym/envs/registration.py", line 128, in make
    spec = self.spec(path)
  File "/home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/gym/envs/registration.py", line 203, in spec
    raise error.UnregisteredEnv("No registered env with id: {}".format(id))
gym.error.UnregisteredEnv: No registered env with id: NR_IES_test-v0

During handling of the above exception, another exception occurred:

ray::RolloutWorker.__init__() (pid=53288, ip=131.183.21.110, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f4668c68c50>)
  File "/home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 490, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "/home/drl-tperg/miniconda3/envs/rl/lib/python3.7/site-packages/ray/rllib/env/utils.py", line 52, in _gym_env_creator
    raise EnvError(ERR_MSG_INVALID_ENV_DESCRIPTOR.format(env_descriptor))
ray.rllib.utils.error.EnvError: The env string you provided ('NR_IES_test-v0') is:
a) Not a supported/installed environment.
b) Not a tune-registered environment creator.
c) Not a valid env class string.

Try one of the following:
a) For Atari support: `pip install gym[atari] autorom[accept-rom-license]`.
   For VizDoom support: Install VizDoom
   (https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md) and
   `pip install vizdoomgym`.
   For PyBullet support: `pip install pybullet`.
b) To register your custom env, do `from ray import tune;
   tune.register('[name]', lambda cfg: [return env obj from here using cfg])`.
   Then in your config, do `config['env'] = [name]`.
c) Make sure you provide a fully qualified classpath, e.g.:
   `ray.rllib.examples.env.repeat_after_me_env.RepeatAfterMeEnv`
   
   
   
   This worked fine in the previous versions of ray. But in this version i'm facing the above error

### Versions / Dependencies

Ray version 2.0.0

### Reproduction script

import ray.rllib.agents.ppo as ppo
import shutil
import subprocess
from ray import tune

# custom testing environment registration
    test_config = ppo.DEFAULT_CONFIG.copy()
    test_config["log_level"] = "WARN"
    test_config["num_workers"] = 1
    test_config["env"] = select_test_env
    test_config["env_config"] = {
        "hes" : best_hes,
        "tes" : best_tes,
        "bes" : best_bes
    }
    tune.register_env(select_test_env, lambda config: NR_IES_test_v0(test_config))

    ray.shutdown()

    # specify the command to run the rollout
    rollout_command = f"rllib rollout {best_checkpoint._local_path} --config '{{\"env\": \"NR_IES_test-v0\"}}' --run PPO --no-render --steps 2880"

    # execute the command using subprocess
    subprocess.run(rollout_command, shell=True)

### Issue Severity

High: It blocks me from completing my task.

**Comment by avnishn** [comment]
@kmattim5 thanks for reporting this. Could you possibly give us a simpler reproduction script, using one of the standard gym environments like cartpole?

can you also check to see if the issue persists on newer versions of ray (we are now on ray 2.5.1) as we do not provide backports.

**Comment by kmattim5** [comment]
Hi @avnishn, I tried with ray v2.5.1 
The script follows bellow
Script:
```
#!/usr/bin/env python
# encoding: utf-8
#import imp
import os
import ray
import ray.rllib.algorithms.ppo as ppo # here we can use DDPG
import shutil
import ray.rllib.policy.policy as PolicySpec
from ray import air, tune
from ray.tune.search.bayesopt import BayesOptSearch
from ray.tune.schedulers.pb2 import PB2

# Replace pickle files with these imports
from NR_IES.envs.main.NR_IES_env import NR_IES_v0

#from ray.tune.schedulers import PopulationBasedTraining


def main ():
    # initiate directory and save checkpoints
    
    currentPathDirectory = os.path.abspath(os.path.dirname(__file__))

    chkpt_root = currentPathDirectory + "/Checkpoints/raytune/PPO/BayesianSearch_OptimizedStorages"
    shutil.rmtree(chkpt_root, ignore_errors=True, onerror=None)

    ray.init(ignore_reinit_error= True)
    select_env = "NR_IES-v0"
    config = ppo.PPOConfig()
    config.log_level = "WARN"
    config.rollouts(num_rollout_workers = 1)
    config.env = select_env
    config.env_config = {
        "hes" : tune.uniform(3600, 36000),
        "tes" : tune.uniform(1000, 10000),
        "bes" : tune.uniform(30, 100)
    }
    #create agent and environment configuration
    bayesopt = BayesOptSearch(metric="episode_reward_mean", mode="max")

    tune.register_env(select_env, lambda cfg: NR_IES_v0(config))
    #create agent and environment configuration
    bayesopt = BayesOptSearch(metric="episode_reward_mean", mode="max")

    tuner = tune.Tuner(
        trainable="PPO",
        param_space=config.env_config,
        run_config=air.RunConfig(
            stop = {"training_iteration": 1},
            checkpoint_config=air.CheckpointConfig(
                checkpoint_score_attribute='episode_reward_mean',
                checkpoint_frequency=1
            ),
            storage_path="Checkpoints/raytune/PPO/BayesianSearch_OptimizedStorages"
        ),
        tune_config=tune.TuneConfig(
            search_alg=bayesopt,
            num_samples=8
        ),
              
    )
    results = tuner.fit()
    best_result = results.get_best_result(metric = 'episode_reward_mean', mode = 'max', scope = 'all')
    best_metric = best_result.metrics
    best_checkpoint = best_result.checkpoint
    best_trial_dir = best_result.log_dir
    best_config = best_result.config

    best_hes = best_config["env_config"]["hes"]
    best_tes = best_config["env_config"]["tes"]
    best_bes = best_config["env_config"]["bes"]

    ray.shutdown()

    print('best_checkpoint', best_checkpoint)
    print('best_config: ', best_config)
    print('best_hes: ', best_hes, ', best_tes: ', best_tes, ', best_bes: ', best_bes)

if __name__ == "__main__":
    main()
```
 This is the training script and I'm getting the following error for it and that's why I moved to ray v2.0.0 where my model's training was done without any errors or blockage

Error:

(PPO pid=355888)   File "/home/drl-tperg/miniconda3/envs/rl_up/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 682, in __init__ [repeated 13x across cluster]
(PPO pid=355888)     self.policy_dict, self.is_policy_to_train = self.config.get_multi_agent_setup( [repeated 7x across cluster]
(PPO pid=355888)   File "/home/drl-tperg/miniconda3/envs/rl_up/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm_config.py", line 2807, in get_multi_agent_setup [repeated 7x across cluster]
(PPO pid=355888)     raise ValueError( [repeated 7x across cluster]
(PPO pid=355888) ValueError: `observation_space` not provided in PolicySpec for default_policy and env does not have an observation space OR no spaces received from other workers' env(s) OR no `observation_space` specified in config! [repeated 7x across cluster]
(RolloutWorker pid=355699) ValueError: `observation_space` not provided in PolicySpec for default_policy and env does not have an observation space OR no spaces received from other workers' env(s) OR no `observation_space` specified in config!
(PPO pid=355888) 2023-07-18 18:55:00,414        ERROR actor_manager.py:507 -- Ray error, taking actor 2 out of service. The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=356022, ip=131.183.21.110, actor_id=a8512a5ca5dc560d0e3c752501000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fea8ba55a20>) [repeated 2x across cluster]
(PPO pid=355888) ValueError: `observation_space` not provided in PolicySpec for default_policy and env does not have an observation space OR no spaces received from other workers' env(s) OR no `observation_space` specified in config!
(PPO pid=355888) ValueError: `observation_space` not provided in PolicySpec for default_policy and env does not have an observation space OR no spaces received from other workers' env(s) OR no `observation_space` specified in config!
(PPO pid=355888) ValueError: `observation_space` not provided in PolicySpec for default_policy and env does not have an observation space OR no spaces received from other workers' env(s) OR no `observation_space` specified in config!
(PPO pid=355888) ValueError: `observation_space` not provided in PolicySpec for default_policy and env does not have an observation space OR no spaces received from other workers' env(s) OR no `observation_space` specified in config!
(PPO pid=355888) ValueError: `observation_space` not provided in PolicySpec for default_policy and env does not have an observation space OR no spaces received from other workers' env(s) OR no `observation_space` specified in config!
(PPO pid=355888) ValueError: `observation_space` not provided in PolicySpec for default_policy and env does not have an observation space OR no spaces received from other workers' env(s) OR no `observation_space` specified in config!
(RolloutWorker pid=356022) 2023-07-18 18:55:00,381      ERROR worker.py:861 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=356022, ip=131.183.21.110, actor_id=a8512a5ca5dc560d0e3c752501000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fea8ba55a20>)
2023-07-18 18:55:00,439 ERROR tune_controller.py:873 -- Trial task failed for trial PPO_c2982ca0
Traceback (most recent call last):
  File "/home/drl-tperg/miniconda3/envs/rl_up/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/home/drl-tperg/miniconda3/envs/rl_up/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 18, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/drl-tperg/miniconda3/envs/rl_up/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/drl-tperg/miniconda3/envs/rl_up/lib/python3.10/site-packages/ray/_private/worker.py", line 2542, in get
    raise value
  File "python/ray/_raylet.pyx", line 1796, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1695, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 1380, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1595, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 886, in ray._raylet.store_task_errors
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::PPO.__init__() (pid=355888, ip=131.183.21.110, actor_id=0cf649eff3f65b02a571a36501000000, repr=PPO)
  File "/home/drl-tperg/miniconda3/envs/rl_up/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 475, in __init__
    super().__init__(
  File "/home/drl-tperg/miniconda3/envs/rl_up/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 170, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/drl-tperg/miniconda3/envs/rl_up/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 601, in setup
    self.workers = WorkerSet(
  File "/home/drl-tperg/miniconda3/envs/rl_up/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 194, in __init__
    raise e.args[0].args[2]
  File "/home/drl-tperg/miniconda3/envs/rl_up/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 682, in __init__
    self.policy_dict, self.is_policy_to_train = self.config.get_multi_agent_setup(
  File "/home/drl-tperg/miniconda3/envs/rl_up/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm_config.py", line 2807, in get_multi_agent_setup
    raise ValueError(
ValueError: `observation_space` not provided in PolicySpec for default_policy and env does not have an observation space OR no spaces received from other workers' env(s) OR no `observation_space` specified in config!
Result for PPO_c2982ca0:
  trial_id: c2982ca0
  
  Can you help me with the script if any changes are present that differ from v2.0.0 and v2.5.1 (which I might have missed)?

**Comment by kmattim5** [comment]
Hi Team, Can anyone help me with this issue as it is a blockage to my work?
