### ISSUE TITLE
[train] Gloo Connection refused

### ISSUE THREAD

**Issue by pth2000** [ray-project/ray#37461]
### What happened + What you expected to happen

I’m trying to use two hosts for pytorch training at the same time, and I’m not sure if I use it correctly.

I executed the following instructions in one of the hosts：

`ray start --head --dashboard-host 0.0.0.0 --port 8264`

In another host:

`ray start --address 192.168.3.14:8264 `

I have observed that two hosts can already be seen in the panel.

After that, I tried to execute the sample code in the head host. And you can see my code below.

After that, I received an error:

```python
2023-07-16 19:01:03,149	ERROR tune.py:1107 -- Trials did not complete: [TorchTrainer_c52be_00000]
2023-07-16 19:01:03,149	INFO tune.py:1111 -- Total run time: 5.71 seconds (5.69 seconds for the tuning loop).
2023-07-16 19:01:03,152	WARNING experiment_analysis.py:910 -- Failed to read the results for 1 trials:
- /home/pth/ray_results/TorchTrainer_2023-07-16_19-00-57/TorchTrainer_c52be_00000_0_2023-07-16_19-00-57
ray.exceptions.RayTaskError(RuntimeError): ray::_Inner.train() (pid=12413, ip=192.168.123.22, actor_id=dc277cd1c1016c75ecb9175305000000, repr=TorchTrainer)
  File "/home/pth/Desktop/ray_test/venv/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 389, in train
    raise skipped from exception_cause(skipped)
  File "/home/pth/Desktop/ray_test/venv/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 336, in entrypoint
    return self._trainable_func(
  File "/home/pth/Desktop/ray_test/venv/lib/python3.9/site-packages/ray/train/base_trainer.py", line 795, in _trainable_func
    super()._trainable_func(self._merged_config, reporter, checkpoint_dir)
  File "/home/pth/Desktop/ray_test/venv/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 653, in _trainable_func
    output = fn()
  File "/home/pth/Desktop/ray_test/venv/lib/python3.9/site-packages/ray/train/base_trainer.py", line 705, in train_func
    trainer.training_loop()
  File "/home/pth/Desktop/ray_test/venv/lib/python3.9/site-packages/ray/train/data_parallel_trainer.py", line 424, in training_loop
    backend_executor.start(initialization_hook=None)
  File "/home/pth/Desktop/ray_test/venv/lib/python3.9/site-packages/ray/train/_internal/backend_executor.py", line 153, in start
    self._backend.on_start(self.worker_group, self._backend_config)
  File "/home/pth/Desktop/ray_test/venv/lib/python3.9/site-packages/ray/train/torch/config.py", line 205, in on_start
    ray.get(setup_futures)
ray.exceptions.RayTaskError(RuntimeError): ray::_RayTrainWorker__execute._setup_torch_process_group() (pid=7483, ip=192.168.123.21, actor_id=5ec72e21e7dea83daf53a63205000000, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x7f43ddbdda60>)
  File "/home/pth/Desktop/ray_test/venv/lib/python3.9/site-packages/ray/train/_internal/worker_group.py", line 32, in __execute
    raise skipped from exception_cause(skipped)
  File "/home/pth/Desktop/ray_test/venv/lib/python3.9/site-packages/ray/train/_internal/worker_group.py", line 29, in __execute
    return func(*args, **kwargs)
  File "/home/pth/Desktop/ray_test/venv/lib/python3.9/site-packages/ray/train/torch/config.py", line 113, in _setup_torch_process_group
    dist.init_process_group(
  File "/home/pth/Desktop/ray_test/venv/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 895, in init_process_group
    default_pg = _new_process_group_helper(
  File "/home/pth/Desktop/ray_test/venv/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 994, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [127.0.1.1]:19885: Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pth/Desktop/ray_test/quickstart.py", line 171, in <module>
    result = trainer.fit()
  File "/home/pth/Desktop/ray_test/venv/lib/python3.9/site-packages/ray/train/base_trainer.py", line 616, in fit
    raise TrainingFailedError(
ray.train.base_trainer.TrainingFailedError: The Ray Train run failed. Please inspect the previous error messages for a cause. After fixing the issue (assuming that the error is not caused by your own application logic, but rather an error such as OOM), you can restart the run from scratch or continue this run.
To continue this run, you can use: `trainer = TorchTrainer.restore("/home/pth/ray_results/TorchTrainer_2023-07-16_19-00-57")`.
To start a new run that will retry on training failures, set `air.RunConfig(failure_config=air.FailureConfig(max_failures))` in the Trainer's `run_config` with `max_failures > 0`, or `max_failures = -1` for unlimited retries.
```

I hope I can fix this problem because it means my program can't run distributed, thank you.

### Versions / Dependencies

ray: 2.5.0
python: 3.9.9
os: Ubuntu 20.04.3 VM (Two sets)

### Reproduction script

```python
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

import ray.train as train
from ray.air import session
from ray.train.torch import TorchTrainer
from ray.air.config import ScalingConfig
from ray.air import Checkpoint


class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28 * 28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits


def train_epoch(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset) // session.get_world_size()  # Divide by word size
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        # We don't need this anymore! Ray Train does this automatically:
        # X, y = X.to(device), y.to(device)

        # Compute prediction error
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            # print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")


def test_epoch(dataloader, model, loss_fn):
    size = len(dataloader.dataset) // session.get_world_size()  # Divide by word size
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            # X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    # print(f"Test Error: \n Accuracy: {(100 * correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")
    return test_loss


def save_model(model, name='model'):
    torch.save(model.state_dict(), f"{name}.pth")
    print(f"Saved PyTorch Model State to {name}.pth")


def load_model():
    model = NeuralNetwork()
    model.load_state_dict(torch.load("model.pth"))
    return model


def predictions(model):
    classes = [
        "T-shirt/top",
        "Trouser",
        "Pullover",
        "Dress",
        "Coat",
        "Sandal",
        "Shirt",
        "Sneaker",
        "Bag",
        "Ankle boot",
    ]

    model.eval()
    training_data, test_data = load_data()
    x, y = test_data[0][0], test_data[0][1]
    with torch.no_grad():
        pred = model(x)
        predicted, actual = classes[pred[0].argmax(0)], classes[y]
        print(f'Predicted: "{predicted}", Actual: "{actual}"')


def train_func(config: dict):
    # batch_size = 64
    # lr = 1e-3
    # epochs = 5
    batch_size = config["batch_size"]
    lr = config["lr"]
    epochs = config["epochs"]

    batch_size_per_worker = batch_size // session.get_world_size()

    training_data, test_data = load_data()

    # Create data loaders.
    train_dataloader = DataLoader(training_data, batch_size=batch_size_per_worker)
    test_dataloader = DataLoader(test_data, batch_size=batch_size_per_worker)

    train_dataloader = train.torch.prepare_data_loader(train_dataloader)
    test_dataloader = train.torch.prepare_data_loader(test_dataloader)

    # for X, y in test_dataloader:
    #     print(f"Shape of X [N, C, H, W]: {X.shape}")
    #     print(f"Shape of y: {y.shape} {y.dtype}")
    #     break

    model = NeuralNetwork()
    model = train.torch.prepare_model(model)

    loss_fn = nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=lr)

    for t in range(epochs):
        # print(f"Epoch {t + 1}\n-------------------------------")
        train_epoch(train_dataloader, model, loss_fn, optimizer)
        test_loss = test_epoch(test_dataloader, model, loss_fn)
        checkpoint = Checkpoint.from_dict(
            dict(epoch=t, model=model.state_dict())
        )
        session.report(dict(loss=test_loss), checkpoint=checkpoint)
    print("Done!")


def load_data():
    # Download training data from open datasets.
    training_data = datasets.FashionMNIST(
        root="./dataset",
        train=True,
        download=True,
        transform=ToTensor(),
    )

    # Download test data from open datasets.
    test_data = datasets.FashionMNIST(
        root="./dataset",
        train=False,
        download=True,
        transform=ToTensor(),
    )
    return training_data, test_data


if __name__ == '__main__':
    trainer = TorchTrainer(
        train_loop_per_worker=train_func,
        train_loop_config={"lr": 1e-3, "batch_size": 64, "epochs": 4},
        scaling_config=ScalingConfig(num_workers=1, use_gpu=False),
    )
    result = trainer.fit()
    print(f"Last result: {result.metrics}")
    print(f"Checkpoint: {result.checkpoint}")
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by xwjiang2010** [comment]
Could be some firewall set up issue.
For the record, gloo uses different transport than ray does. So the fact that you can see two nodes in Ray Dashboard doesn't mean gloo can also work properly across the two nodes. Ray only plays the role to call `init_process_group` with the correct set of args (like rank etc) in different processes. From that point on, it's purely torch distributed and gloo layer that are at play. 
I would encourage you to use pure `ray.remote()` to see if two processes in the two different nodes can call `init_process_group` and see each other over gloo properly. That way, you can strip away a lot of intermediate layers.
Hope this helps!

**Comment by pth2000** [comment]
> Could be some firewall set up issue. For the record, gloo uses different transport than ray does. So the fact that you can see two nodes in Ray Dashboard doesn't mean gloo can also work properly across the two nodes. Ray only plays the role to call `init_process_group` with the correct set of args (like rank etc) in different processes. From that point on, it's purely torch distributed and gloo layer that are at play. I would encourage you to use pure `ray.remote()` to see if two processes in the two different nodes can call `init_process_group` and see each other over gloo properly. That way, you can strip away a lot of intermediate layers. Hope this helps!

Thank you for your reply. In fact, I tried to solve this problem some time ago, which is a problem caused by the gloo backend. 

My method is as follows: Edit the hosts file in Ubuntu (/etc/hosts) and change 127.0.1.1 to the ip address used by the host in the current LAN.

After modifying both machines, the cpu can be used normally for distributed training.
