### ISSUE TITLE
AssertionError: cant parse version None

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#3766]
If you get the following error when trying to do an incremental build (i.e. run `make` in `ray/build`):

```
Traceback (most recent call last):
  File "setup.py", line 584, in <module>
    url="https://arrow.apache.org/"
  File "/Users/pcmoritz/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/Users/pcmoritz/anaconda3/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Users/pcmoritz/anaconda3/lib/python3.6/site-packages/setuptools/dist.py", line 372, in __init__
    _Distribution.__init__(self, attrs)
  File "/Users/pcmoritz/anaconda3/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/Users/pcmoritz/anaconda3/lib/python3.6/site-packages/setuptools/dist.py", line 528, in finalize_options
    ep.load()(self, ep.name, value)
  File "/Users/pcmoritz/anaconda3/lib/python3.6/site-packages/setuptools_scm/integration.py", line 22, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/Users/pcmoritz/anaconda3/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 119, in get_version
    parsed_version = _do_parse(root, parse)
  File "/Users/pcmoritz/anaconda3/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 67, in _do_parse
    return meta(pretended)
  File "/Users/pcmoritz/anaconda3/lib/python3.6/site-packages/setuptools_scm/version.py", line 110, in meta
    assert tag is not None, 'cant parse version %s' % tag
AssertionError: cant parse version None
```

You need to update setuptools_scm, for example with
```
pip install setuptools_scm=0.3.1
```

It happens for me on macOS. If this issue is wide spread, we should reconsider the way we specify the arrow version with setuptools_scm (see https://github.com/ray-project/ray/pull/3760).

**Comment by richardliaw** [comment]
Closing because stale.
