### ISSUE TITLE
[Tune] pbt_transformers.py failing to run - error code

### ISSUE THREAD

**Issue by ChrisRawstone** [ray-project/ray#37688]
### What happened + What you expected to happen

Hi whenever I try to run your test example for the file: ray/python/ray/tune/examples/pbt_transformers /pbt_transformers.py
I get an error that is very hard decipher. I figured out that the error comes from this:

```
import ray
ray.init()
```

error code for the script

ERROR:
Description = Not found
Traceback (most recent call last):
  File "C:\Users\Chris\HyperParameterTuning\PBT_Transformer.py", line 165, in <module>
    tune_transformer(num_samples=8, gpus_per_trial=0)
  File "C:\Users\Chris\HyperParameterTuning\PBT_Transformer.py", line 149, in tune_transformer
    log_to_file=True,
  File "C:\Users\Chris\AppData\Local\miniconda3\envs\SOPenv2\lib\site-packages\transformers\trainer.py", line 2432, in hyperparameter_search
    best_run = backend_dict[backend](self, n_trials, direction, **kwargs)
  File "C:\Users\Chris\AppData\Local\miniconda3\envs\SOPenv2\lib\site-packages\transformers\integrations.py", line 342, in run_hp_search_ray
    **kwargs,
  File "C:\Users\Chris\AppData\Local\miniconda3\envs\SOPenv2\lib\site-packages\ray\tune\tune.py", line 573, in run
    _ray_auto_init(entrypoint=error_message_map["entrypoint"])
  File "C:\Users\Chris\AppData\Local\miniconda3\envs\SOPenv2\lib\site-packages\ray\tune\tune.py", line 225, in _ray_auto_init
    ray.init()
  File "C:\Users\Chris\AppData\Local\miniconda3\envs\SOPenv2\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Chris\AppData\Local\miniconda3\envs\SOPenv2\lib\site-packages\ray\_private\worker.py", line 1518, in init
    ray_params=ray_params,
  File "C:\Users\Chris\AppData\Local\miniconda3\envs\SOPenv2\lib\site-packages\ray\_private\node.py", line 290, in __init__
    self.start_ray_processes()
  File "C:\Users\Chris\AppData\Local\miniconda3\envs\SOPenv2\lib\site-packages\ray\_private\node.py", line 1214, in start_ray_processes
    resource_spec = self.get_resource_spec()
  File "C:\Users\Chris\AppData\Local\miniconda3\envs\SOPenv2\lib\site-packages\ray\_private\node.py", line 468, in get_resource_spec
    ).resolve(is_head=self.head, node_ip_address=self.node_ip_address)
  File "C:\Users\Chris\AppData\Local\miniconda3\envs\SOPenv2\lib\site-packages\ray\_private\resource_spec.py", line 186, in resolve
    num_gpus = _autodetect_num_gpus()
  File "C:\Users\Chris\AppData\Local\miniconda3\envs\SOPenv2\lib\site-packages\ray\_private\resource_spec.py", line 298, in _autodetect_num_gpus
    lines = subprocess.check_output(cmdargs).splitlines()[1:]
  File "C:\Users\Chris\AppData\Local\miniconda3\envs\SOPenv2\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\Chris\AppData\Local\miniconda3\envs\SOPenv2\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['WMIC', 'PATH', 'Win32_VideoController', 'GET', 'AdapterCompatibility']' returned non-zero exit status 2147749890.

### Versions / Dependencies

I am using windows 10 with python Python 3.7.16

My environment looks like this: 

Package                  Version
------------------------ -----------
accelerate               0.20.3
aiohttp                  3.8.4
aiohttp-cors             0.7.0
aiorwlock                1.3.0
aiosignal                1.3.1
ansicon                  1.89.0
anyio                    3.5.0
appdirs                  1.4.4
argon2-cffi              20.1.0
async-timeout            4.0.2
asynctest                0.13.0
attrs                    22.2.0
Babel                    2.11.0
backcall                 0.2.0
beautifulsoup4           4.11.1
bleach                   4.1.0
blessed                  1.20.0
brotlipy                 0.7.0
cachetools               5.3.1
cchardet                 2.1.7
certifi                  2022.12.7
cffi                     1.15.1
chardet                  5.1.0
charset-normalizer       3.1.0
click                    8.1.3
cloudpickle              2.2.1
colorama                 0.4.6
colorful                 0.5.5
cryptography             39.0.1
cycler                   0.11.0
dask                     2022.2.0
datasets                 2.10.1
debugpy                  1.5.1
decorator                5.1.1
defusedxml               0.7.1
dill                     0.3.6
distlib                  0.3.6
docker-pycreds           0.4.0
entrypoints              0.4
et-xmlfile               1.1.0
evaluate                 0.4.0
fastapi                  0.100.0
fastjsonschema           2.16.2
filelock                 3.9.0
Flask                    2.2.5
fonttools                4.38.0
frozenlist               1.3.3
fsspec                   2023.1.0
gitdb                    4.0.10
GitPython                3.1.31
google-api-core          2.11.1
google-auth              2.22.0
googleapis-common-protos 1.59.1
gpustat                  1.1
grpcio                   1.51.3
h11                      0.14.0
huggingface-hub          0.13.2
idna                     3.4
importlib-metadata       6.0.0
importlib-resources      5.2.0
ipykernel                6.15.2
ipython                  7.31.1
ipython-genutils         0.2.0
ipywidgets               7.6.5
itsdangerous             2.1.2
jedi                     0.18.1
Jinja2                   3.1.2
jinxed                   1.2.0
joblib                   1.2.0
json5                    0.9.6
jsonschema               4.17.3
jupyter                  1.0.0
jupyter_client           7.4.9
jupyter-console          6.4.4
jupyter_core             4.11.2
jupyter-server           1.23.4
jupyterlab               3.5.3
jupyterlab-pygments      0.1.2
jupyterlab_server        2.19.0
jupyterlab-widgets       1.0.0
kiwisolver               1.4.4
locket                   1.0.0
lxml                     4.9.1
MarkupSafe               2.1.1
matplotlib               3.5.3
matplotlib-inline        0.1.6
mistune                  0.8.4
mkl-fft                  1.3.0
mkl-random               1.1.1
mkl-service              2.3.0
msgpack                  1.0.5
multidict                6.0.4
multiprocess             0.70.14
nbclassic                0.5.2
nbclient                 0.5.13
nbconvert                6.5.4
nbformat                 5.7.0
nest-asyncio             1.5.6
nltk                     3.8.1
notebook                 6.5.2
notebook_shim            0.2.2
numpy                    1.21.6
nvidia-ml-py             12.535.77
nvidia-ml-py3            7.352.0
openai                   0.27.8
opencensus               0.11.2
opencensus-context       0.1.3
openpyxl                 3.1.2
packaging                23.0
pandas                   1.3.5
pandocfilters            1.5.0
parso                    0.8.3
partd                    1.4.0
pathtools                0.1.2
pickleshare              0.7.5
Pillow                   9.3.0
pip                      22.3.1
pkgutil_resolve_name     1.3.10
platformdirs             3.1.1
ply                      3.11
prometheus-client        0.14.1
prompt-toolkit           3.0.36
protobuf                 3.20.3
psutil                   5.9.0
py-spy                   0.3.14
pyarrow                  6.0.1
pyasn1                   0.5.0
pyasn1-modules           0.3.0
pycparser                2.21
pydantic                 1.10.11
Pygments                 2.11.2
pyOpenSSL                23.0.0
pyparsing                3.0.9
PyQt5                    5.15.7
PyQt5-sip                12.11.0
pyrsistent               0.18.0
PySocks                  1.7.1
python-dateutil          2.8.2
pytz                     2022.7.1
pywin32                  305.1
pywinpty                 2.0.10
PyYAML                   6.0
pyzmq                    23.2.0
qtconsole                5.4.0
QtPy                     2.2.0
ray                      2.6.0
regex                    2022.10.31
requests                 2.28.2
responses                0.18.0
rsa                      4.9
scikit-learn             1.0.2
scipy                    1.7.3
seaborn                  0.12.2
Send2Trash               1.8.0
sentry-sdk               1.16.0
setproctitle             1.3.2
setuptools               65.6.3
sip                      6.6.2
six                      1.16.0
sklearn                  0.0.post1
smart-open               6.3.0
smmap                    5.0.0
sniffio                  1.2.0
soupsieve                2.3.2.post1
starlette                0.27.0
tabulate                 0.9.0
tensorboardX             2.6
terminado                0.17.1
threadpoolctl            3.1.0
tinycss2                 1.2.1
tokenizers               0.13.2
toml                     0.10.2
tomli                    2.0.1
toolz                    0.12.0
torch                    1.10.0
torchaudio               0.10.0
torchvision              0.11.0
tornado                  6.2
tqdm                     4.65.0
traitlets                5.7.1
transformers             4.26.1
typing_extensions        4.5.0
urllib3                  1.26.15
uvicorn                  0.22.0
virtualenv               20.21.0
wandb                    0.13.11
wcwidth                  0.2.5
webencodings             0.5.1
websocket-client         0.58.0
Werkzeug                 2.2.3
wheel                    0.38.4
widgetsnbextension       3.5.2
win-inet-pton            1.1.0
wincertstore             0.2
XlsxWriter               3.1.2
xlwt                     1.3.0
xxhash                   3.2.0
yarl                     1.8.2
zipp                     3.15.0

### Reproduction script

Just run this file from your github:

ray/python/ray/tune/examples/pbt_transformers /pbt_transformers.py

### Issue Severity

High: It blocks me from completing my task.

**Comment by xwjiang2010** [comment]
Can you do a `ray.init` only? Does it throw any error?
