### ISSUE TITLE
[Air] Can't restore training with s3 path

### ISSUE THREAD

**Issue by Uijeong97** [ray-project/ray#37697]
### What happened + What you expected to happen

I'm using TransformersTrainer.

And I want to restore training with artifacts in s3 path.

```python
trainer = TransformersTrainer.restore(
    path=s3_path_uri,
)
trainer.fit()
```

```
Traceback (most recent call last):
  File "/root/workspace/myrepo/main.py", line 349, in <module>
    train(cfg=cfg)
  File "/root/workspace/myrepo/main.py", line 260, in train
    trainer = TransformersTrainer.restore(
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/ray/train/huggingface/transformers/transformers_trainer.py", line 346, in restore
    return super(DataParallelTrainer, cls).restore(
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/ray/train/base_trainer.py", line 306, in restore
    trainer_state_path = cls._maybe_sync_down_trainer_state(path)
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/ray/train/base_trainer.py", line 487, in _maybe_sync_down_trainer_state
    download_from_uri(str(path / _TRAINER_PKL), str(tempdir / _TRAINER_PKL))
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/ray/air/_internal/remote_storage.py", line 485, in download_from_uri
    if is_directory(uri):
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/ray/air/_internal/remote_storage.py", line 625, in is_directory
    file_info = fs.get_file_info(bucket_path)
  File "pyarrow/_fs.pyx", line 571, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/_fs.pyx", line 1490, in pyarrow._fs._cb_get_file_info
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/pyarrow/fs.py", line 327, in get_file_info
    info = self.fs.info(path)
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/fsspec/asyn.py", line 115, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/fsspec/asyn.py", line 100, in sync
    raise return_result
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/fsspec/asyn.py", line 55, in _runner
    result[0] = await coro
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/s3fs/core.py", line 1248, in _info
    out = await self._call_s3(
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/s3fs/core.py", line 341, in _call_s3
    await self.set_session()
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/s3fs/core.py", line 527, in set_session
    self._s3 = await s3creator.__aenter__()
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/aiobotocore/session.py", line 27, in __aenter__
    self._client = await self._coro
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/aiobotocore/session.py", line 198, in _create_client
    client = await client_creator.create_client(
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/aiobotocore/client.py", line 75, in create_client
    client_args = self._get_client_args(
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/aiobotocore/client.py", line 265, in _get_client_args
    return args_creator.get_client_args(
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/aiobotocore/args.py", line 75, in get_client_args
    endpoint = endpoint_creator.create_endpoint(
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/aiobotocore/endpoint.py", line 308, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: https:/my-s3-endpoint.com
```

### Versions / Dependencies

ray 3.0.0 dev (commit hash https://github.com/ray-project/ray/commit/394766d26224a2407df45243e4aedc1c6e3b2112) --> same client, cluster
python 3.10.11

### Reproduction script

```python
s3_path_uri="s3://bucket/object_key?endpoint_override=https://my-s3-endpoint.com"
trainer = TransformersTrainer.restore(
    path=s3_path_uri,
)
trainer.fit()
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by xwjiang2010** [comment]
Can you directly establish the connection with the path using pyarrow/fsspec? From the stack trace, the issue doesn't seem to be in Ray.

**Comment by Uijeong97** [comment]
The issue has been resolved from this [PR](https://github.com/Uijeong97/ray/commit/cd00abfcc8bfff739305c416d6756437d5dabd11).
