### ISSUE TITLE
[Core] ray.init() ignores 'no_proxy' environment variable

### ISSUE THREAD

**Issue by batuhanfaik** [ray-project/ray#37757]
### Problem
In my development environment both `https_proxy` and `no_proxy` environment variables are set. My ray cluster is deployed on a
Docker Swarm and the head node service is running with name `ray-head`. Adding this service to `no_proxy` environment variable does not prevent `https_proxy` environment variable from being used. The connection still tries to go through the proxy. If I unset the `https_proxy` environment variable the connection succeeds as expected and everything works.

### Expected Behavior
During the initialisation of the connection to the cluster, `no_proxy` environment variable must be checked. If the address is in the no proxy list, connection must not be established through the proxy.

### Logs
```text
INFO client_builder.py:237 -- Passing the following kwargs to ray.init() on the server: logging_level
DEBUG worker.py:378 -- client gRPC channel state change: ChannelConnectivity.IDLE
DEBUG worker.py:378 -- client gRPC channel state change: ChannelConnectivity.CONNECTING
DEBUG worker.py:378 -- client gRPC channel state change: ChannelConnectivity.READY
DEBUG worker.py:813 -- Pinging server.
197441 hpack_parser.cc:1218]                 Error parsing metadata: error=invalid value key=content-type value=text/html; charset=utf-8
DEBUG worker.py:230 -- Ray client server unavailable, retrying in 5s...
DEBUG worker.py:233 -- Received when checking init: Received http2 header with status: 404
DEBUG worker.py:237 -- Waiting for Ray to become ready on the server, retry in 5s...
DEBUG worker.py:813 -- Pinging server.
DEBUG worker.py:230 -- Ray client server unavailable, retrying in 10s...
DEBUG worker.py:233 -- Received when checking init: Received http2 header with status: 404
DEBUG worker.py:237 -- Waiting for Ray to become ready on the server, retry in 10s...
DEBUG worker.py:813 -- Pinging server.
DEBUG worker.py:230 -- Ray client server unavailable, retrying in 15s...
DEBUG worker.py:233 -- Received when checking init: Received http2 header with status: 404
DEBUG worker.py:237 -- Waiting for Ray to become ready on the server, retry in 15s...
/<workdir>/.venv/lib64/python3.9/site-packages/ray/util/client/worker.py:253: UserWarning: Ray Client connection timed out. Ensure that the Ray Client port on the head node is reachable from your local machine. See https://docs.ray.io/en/latest/cluster/ray-client.html#step-2-check-ports for more information.
  warnings.warn(
Traceback (most recent call last):
  File "/<workdir>/example.py", line 32, in <module>
    ray.init(
  File "/<workdir>/.venv/lib64/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/<workdir>/.venv/lib64/python3.9/site-packages/ray/_private/worker.py", line 1338, in init
    ctx = builder.connect()
  File "/<workdir>/.venv/lib64/python3.9/site-packages/ray/client_builder.py", line 167, in connect
    client_info_dict = ray.util.client_connect.connect(
  File "/<workdir>/.venv/lib64/python3.9/site-packages/ray/util/client_connect.py", line 55, in connect
    conn = ray.connect(
  File "/<workdir>/.venv/lib64/python3.9/site-packages/ray/util/client/__init__.py", line 250, in connect
    conn = self.get_context().connect(*args, **kw_args)
  File "/<workdir>/.venv/lib64/python3.9/site-packages/ray/util/client/__init__.py", line 92, in connect
    self.client_worker = Worker(
  File "/<workdir>/.venv/lib64/python3.9/site-packages/ray/util/client/worker.py", line 139, in __init__
    self._connect_channel()
  File "/<workdir>/.venv/lib64/python3.9/site-packages/ray/util/client/worker.py", line 260, in _connect_channel
    raise ConnectionError("ray client connection timeout")
ConnectionError: ray client connection timeout
```

### Versions / Dependencies

ray v2.6.0
Python 3.9.16
Rocky Linux v8.8

### Reproduction script

```python
import ray
import os
import time

# Set $https_proxy
os.environ['https_proxy'] = '<proxy-server>'  # e.g. 'http://proxy.company.com:1234'
# Add ray-head to $no_proxy
os.environ['no_proxy'] = f'{os.environ["no_proxy"]}, ray-head'

address = 'ray://ray-head:10001'
ray.init(address=address, logging_level='DEBUG')

# Simple example from https://docs.ray.io/en/latest/ray-core/examples/gentle_walkthrough.html
DATABASE = ["Learning", "Ray", "Flexible", "Distributed", "Python", "for", "Machine", "Learning"]


def retrieve(item):
    time.sleep(item / 10.0)
    return item, DATABASE[item]


@ray.remote
def retrieve_task(item):
    return retrieve(item)


object_references = [retrieve_task.remote(item) for item in range(8)]
data = ray.get(object_references)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

#### Workaround
```python
# Unset $https_proxy
os.environ['https_proxy'] = ''
address = 'ray://ray-head:10001'
ray.init(address=address, logging_level='DEBUG')
```

**Comment by batuhanfaik** [comment]
`https_proxy` and `no_proxy` are common environment variables used to specify proxy settings to client programs in Linux operating systems. See [gRPC Go docs](https://github.com/grpc/grpc-go/blob/master/Documentation/proxy.md) or [gRPC++ docs](https://grpc.github.io/grpc/cpp/md_doc_environment_variables.html) for more ref. Even though gRPC implements the expected behaviour, `ray.init()` does not. Hence the connection tries to establish through `https_proxy`.

**Comment by batuhanfaik** [comment]
@rkooo567  do we have any updates on this?

**Comment by rkooo567** [comment]
We don't recommend using a ray client anymore https://docs.ray.io/en/master/cluster/running-applications/job-submission/ray-client.html#when-to-use-ray-client, so I don't think we will make any fix sooner or later. Please feel free to create a PR to fix!

**Comment by batuhanfaik** [comment]
I see, thanks for the reply! As expected, this issue does not exist when using the Jobs API. So, will the CLI be deprecated with 3.0.0 and if so, when do we expect the 3.0.0 release?

**Comment by rkooo567** [comment]
Ray client won't be deprecated. It will be there, but we don't make further improvement and recommend people to switch to job submission

**Comment by batuhanfaik** [comment]
Good to hear ☺️ Can you also take a look at the PR?
