### ISSUE TITLE
[Core] better failure handling during worker exit

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#37758]
### What happened + What you expected to happen

Notice following crash log which cause cascading failures
```
Traceback (most recent call last):
  File "some_helper.py", line 246, in subprocess_call
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 342, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1806, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.8/subprocess.py", line 1764, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/worker.py", line 776, in sigterm_handler
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1501, in ray._raylet.execute_task
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/worker.py", line 569, in record_task_log_end
    self.core_worker.record_task_log_end(
AttributeError: 'Worker' object has no attribute 'core_worker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1787, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1684, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 1366, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1367, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1583, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 813, in ray._raylet.store_task_errors
AttributeError: 'Worker' object has no attribute 'core_worker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1824, in ray._raylet.task_execution_handler
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/utils.py", line 174, in push_error_to_driver
    worker.core_worker.push_error(job_id, error_type, message, time.time())
AttributeError: 'Worker' object has no attribute 'core_worker'
Exception ignored in: 'ray._raylet.task_execution_handler'
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1824, in ray._raylet.task_execution_handler
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/utils.py", line 174, in push_error_to_driver
    worker.core_worker.push_error(job_id, error_type, message, time.time())
AttributeError: 'Worker' object has no attribute 'core_worker'
[2023-07-21 17:57:05,836 C 1076 1076] direct_actor_transport.cc:201:  Check failed: objects_valid
*** StackTrace Information ***
```

### Versions / Dependencies

2.5.1

### Reproduction script

n/a

### Issue Severity

None

**Comment by thoglu** [comment]
This is still there in 2.6. Is this gonna be solved soon?

**Comment by rickyyx** [comment]
Sorry, this is still not done yet - the impact is minimal, I believe it's a stacktrace when a core worker was shutdown forcefully so it wasn't prioritized. But we should fix it ASAP I agree. 

Or if you are seeing this showing up in other unexpected cases?
