### ISSUE TITLE
[Job CLI] Error on job connection (python 3.11, ray job cli)

### ISSUE THREAD

**Issue by aavbsouza** [ray-project/ray#37802]
### What happened + What you expected to happen

start a ray cluster with this kind of CLI command:
# head
`ray start --head --block --node-ip-address=10.10.10.20 --lots-of-args`
# workers
`ray start --address=10.10.10.20:1234 --block --node-ip-address=10.10.10.21`
try to connect to the cluster using the job API (CLI)

`ray job submit --address=http://10.10.10.20:8666/ -- python3 /usr/local/python/bin/main_script --ray_node_address=10.10.10.20 --lots-of-args`

# call ray init as ray.init(_node_ip_address=args.ray_node_address)

get the following error:

```bash
2023-07-21 17:41:46,001	INFO cli.py:27 -- Job submission server address: http://10.10.10.20:8666/
2023-07-21 17:41:47,606	SUCC cli.py:33 -- -------------------------------------------------------
2023-07-21 17:41:47,606	SUCC cli.py:34 -- Job 'raysubmit_VaEfTuTwivbwi78n' submitted successfully
2023-07-21 17:41:47,606	SUCC cli.py:35 -- -------------------------------------------------------
2023-07-21 17:41:47,606	INFO cli.py:240 -- Next steps
2023-07-21 17:41:47,606	INFO cli.py:241 -- Query the logs of the job:
2023-07-21 17:41:47,606	INFO cli.py:243 -- ray job logs raysubmit_VaEfTuTwivbwi78n
2023-07-21 17:41:47,606	INFO cli.py:245 -- Query the status of the job:
2023-07-21 17:41:47,606	INFO cli.py:247 -- ray job status raysubmit_VaEfTuTwivbwi78n
2023-07-21 17:41:47,606	INFO cli.py:249 -- Request the job to be stopped:
2023-07-21 17:41:47,606	INFO cli.py:251 -- ray job stop raysubmit_VaEfTuTwivbwi78n
2023-07-21 17:41:47,608	INFO cli.py:258 -- Tailing logs until the job exits (disable with --no-wait):
2023-07-21 17:41:49,294	INFO worker.py:1313 -- Using address 10.10.10.20:1234 set in the environment variable RAY_ADDRESS
2023-07-21 17:41:49,294	INFO worker.py:1431 -- Connecting to existing Ray cluster at address: 10.10.10.20:1234...
2023-07-21 17:41:49,326	INFO worker.py:1612 -- Connected to Ray cluster. View the dashboard at http://10.10.10.20:8666/ 
2023-07-21 17:41:49,629	ERR cli.py:41 -- ---------------------------------------
2023-07-21 17:41:49,629	ERR cli.py:42 -- Job 'raysubmit_VaEfTuTwivbwi78n' failed
2023-07-21 17:41:49,629	ERR cli.py:43 -- ---------------------------------------
2023-07-21 17:41:49,629	INFO cli.py:56 -- Status message: Traceback (most recent call last):
  File "/usr/local/python/lib/python3.11/site-packages/ray/dashboard/modules/job/job_manager.py", line 417, in run
    finished, _ = await asyncio.wait(
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/lib/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
```

### Versions / Dependencies

Python 3.11.4, Ray 2.6.0, ubuntu 22.04 based container image

### Reproduction script

The previous description it is sufficient 

### Issue Severity

High: It blocks me from completing my task.

**Comment by architkulkarni** [comment]
Thanks for filing the issue @aavbsouza! Would you be willing to file a pull request with a fix?

**Comment by architkulkarni** [comment]
cc @rickyyx let me know if there's any other process to follow for Python 3.11 fixes
