### ISSUE TITLE
Failed to execute `state.task_table()` when running a Java App

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#3780]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MBP 10.11.6
- **Ray installed from (source or binary)**: from source/current master
- **Ray version**:
- **Python version**:python3.6.5
- **Exact command to reproduce**:

### Describe the problem
1. Run a Java actor example
```Java
    RayActor<Counter> actor = Ray.createActor(ActorTest::factory, 1);
    Assert.assertNotEquals(actor.getId(), UniqueId.NIL);
    // Test calling an actor
    Assert.assertEquals(Integer.valueOf(1), Ray.call(Counter::getValue, actor).get());

    TimeUnit.SECONDS.sleep(100000);
```
2. run this scirpt to get task list from GCS:

```python
from ray.experimental import state

gs = state.GlobalState()
gs._initialize_global_state("127.0.0.1", 6379)

print(gs.task_table())
```
them we got this error:
```shell
_pickle.UnpicklingError: invalid load key, '\xf7'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "demo.py", line 6, in <module>
    print(gs.task_table())
  File "/Users/wangqing/Workspace/ray/python/ray/experimental/state.py", line 367, in task_table
    ray.ObjectID(task_id_binary))
  File "/Users/wangqing/Workspace/ray/python/ray/experimental/state.py", line 320, in _task_table
    "Args": task_spec.arguments(),
SystemError: <built-in method arguments of task.Task object at 0x117f22690> returned a result with an error set
```
I added some logs to trace it, and found that：
function `PyObject_CallMethodObjArgs` at [this line](https://github.com/ray-project/ray/blob/master/src/ray/raylet/lib/python/common_extension.cc#L597) returns a NULL.
That means `pickle.loads()` the arg failed.

PS:
 If I run a python actor example, then run the script, I will get correct result.

**Comment by jovany-wang** [comment]
It works fine for normal tasks.
