### ISSUE TITLE
Problems when running code with ray[TypeError: Experiment.__init__() got an unexpected keyword argument 'checkpoint_freq']

### ISSUE THREAD

**Issue by lazyaa** [ray-project/ray#37852]
### **System information:**
 OS Platform and Distribution:Linux Ubuntu 22.04 LTS
Ray installed from (source or binary): source
Ray version:3.0.0.dev0
Python version: 3.10.12
Code used:https://github.com/ninalopatina/Rocket_RL

### **Source code**  python Rocket_RL/python/main.py

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
 Import the Rocket_RL functions
import Rocket_RL.python.func.data_processing as RocketData
import Rocket_RL.python.func.ray_funcs as RF
import argparse, os, yaml
import ray
from ray.tune import run_experiments
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-rreg','--run_reg', dest = 'run_regression', type = bool,
                        default = True, help = 'True to run the regression')
    parser.add_argument('-sreg','--save_reg', dest = 'save_regression', type = bool,
                        default = False, help = 'True to save the regression')
    parser.add_argument('-rRL','--run_RL', dest = 'run_RL', type = bool,
                        default = True, help = 'True to run RL model')
    parser.add_argument('-pRL','--plot_RL', dest = 'plot_RL', type = bool,
                        default = True, help = 'True to plot RL results')
    parser.add_argument('-plot','--plot_data', dest = 'plot_data', type = int,
                        default = False, help = 'True to plot Fluent simulation data in 3d')
    parser.add_argument('-cfg','--config', dest = 'config_dir', type = str,
                        default = 'Rocket_RL/config/config.yml', help = 'where the config file is located')
    parser.add_argument('-rayinit','--rayinit', dest = 'rayinit', type = bool,
                        default = True, help = 'should only be init the first time you run if running in an IDE')
    args = parser.parse_args()
    CWD_PATH = os.getcwd()
    config_path = os.path.join(CWD_PATH,args.config_dir)
    with open(config_path, 'r') as ymlfile:
        cfg = yaml.load(ymlfile)
    cfg['CWD_PATH'] = CWD_PATH
    # If importing new data, set plot_data to true to take a glance at it to verify
    # if it looks reasonable.
    if (args.plot_data==True) | (args.run_regression == True):
        RocketData.data_process(cfg,args.plot_data,args.run_regression,args.save_regression)
    if args.run_RL == True:
        if args.rayinit == True:
            ray.init()
        run_experiments({
            "RocketRL": {
                "run": cfg['agent'],# Which agent to run
                #conditions under which you would stop:
                "stop": {"time_total_s": cfg['time_total_s'], "timesteps_total": cfg['timesteps_total'], "episode_reward_mean": cfg['episode_reward_mean']},
                #The custom environment:
                "env": "AllVar-v0",
                #Checkpoint on every iteration:
                "checkpoint-freq": cfg['checkpoint-freq'],
                #Num workers has to be 1 fewer than the available CPU!!!!!
                "config": {
                    "num_workers": cfg['num_workers'],
                    "gamma": cfg['gamma'],
                    "horizon": cfg['horizon'],
                    "num_sgd_iter": cfg['num_sgd_iter'],
                    "sgd_stepsize": cfg['sgd_stepsize'],
                    "timesteps_per_batch": cfg['timesteps_per_batch'],
                    "min_steps_per_task": cfg['min_steps_per_task']
                },
            },
        })
    if args.plot_RL == True:
        df_model = RF.rllib_plot(cfg)
```

### **Describe the problem**
When running the above code causes: 
` 
```
ridge  results for degree  4 & var  O_CH4_flow_uniformity :  0.9518325501300927
ridge  results for degree  4 & var  O_CH4_mol_frac :  0.9886783190934565
ridge  results for degree  4 & var  O_t :  0.9936236872942672
2023-07-27 16:14:08,396	INFO worker.py:1621 -- Started a local Ray instance.
Traceback (most recent call last):
  File "/home/lzy/ray/python/ray/tune/experiment/experiment.py", line 333, in from_json
    exp = cls(name, run_value, **spec)
TypeError: Experiment.__init__() got an unexpected keyword argument 'checkpoint_freq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lzy/Rocket_RL/python/main.py", line 74, in <module>
    run_experiments({
  File "/home/lzy/ray/python/ray/tune/tune.py", line 1258, in run_experiments
    experiments = _convert_to_experiment_list(experiments)
  File "/home/lzy/ray/python/ray/tune/experiment/experiment.py", line 533, in _convert_to_experiment_list
    exp_list = [
  File "/home/lzy/ray/python/ray/tune/experiment/experiment.py", line 534, in <listcomp>
    Experiment.from_json(name, spec) for name, spec in experiments.items()
  File "/home/lzy/ray/python/ray/tune/experiment/experiment.py", line 335, in from_json
    raise TuneError(
ray.tune.error.TuneError: Failed to load the following Tune experiment specification:

 {'checkpoint_freq': 1,
 'config': {'env': 'AllVar-v0',
            'gamma': 0.995,
            'horizon': 1000,
            'min_steps_per_task': 200,
            'num_sgd_iter': 30,
            'num_workers': 3,
            'sgd_stepsize': 5e-05,
            'timesteps_per_batch': 4000},
 'stop': {'episode_reward_mean': 10000,
          'time_total_s': 600000,
          'timesteps_total': 100000000}}.

Please check that the arguments are valid. Experiment creation failed with the following error:
 Experiment.__init__() got an unexpected keyword argument 'checkpoint_freq'
`
```

**Comment by xwjiang2010** [comment]
cc @justinvyu 
I think we are removing `checkpoint_freq`.
`CheckpoingConfig` is the recommended way of specifying the frequency of checkpointing.

**Comment by lazyaa** [comment]
@xwjian2010
```
The same problem occurs after modification:
ridge  results for degree  4 & var  O_CH4_flow_uniformity :  0.9477995314686805
ridge  results for degree  4 & var  O_CH4_mol_frac :  0.9906228330870663
ridge  results for degree  4 & var  O_t :  0.9932932526702213
2023-07-28 09:57:07,597	INFO worker.py:1621 -- Started a local Ray instance.
Traceback (most recent call last):
  File "/home/lzy/ray/python/ray/tune/experiment/experiment.py", line 333, in from_json
    exp = cls(name, run_value, **spec)
TypeError: Experiment.__init__() got an unexpected keyword argument 'CheckpoingConfig'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lzy/Rocket_RL/python/main.py", line 74, in <module>
    run_experiments({
  File "/home/lzy/ray/python/ray/tune/tune.py", line 1258, in run_experiments
    experiments = _convert_to_experiment_list(experiments)
  File "/home/lzy/ray/python/ray/tune/experiment/experiment.py", line 533, in _convert_to_experiment_list
    exp_list = [
  File "/home/lzy/ray/python/ray/tune/experiment/experiment.py", line 534, in <listcomp>
    Experiment.from_json(name, spec) for name, spec in experiments.items()
  File "/home/lzy/ray/python/ray/tune/experiment/experiment.py", line 335, in from_json
    raise TuneError(
ray.tune.error.TuneError: Failed to load the following Tune experiment specification:

 {'CheckpoingConfig': 1,
 'config': {'env': 'AllVar-v0',
            'gamma': 0.995,
            'horizon': 1000,
            'min_steps_per_task': 200,
            'num_sgd_iter': 30,
            'num_workers': 3,
            'sgd_stepsize': 5e-05,
            'timesteps_per_batch': 4000},
 'stop': {'episode_reward_mean': 10000,
          'time_total_s': 600000,
          'timesteps_total': 100000000}}.

Please check that the arguments are valid. Experiment creation failed with the following error:
 Experiment.__init__() got an unexpected keyword argument 'CheckpoingConfig'
```

**Comment by xwjiang2010** [comment]
my bad, there is a typo. It should be [`CheckpointConfig`](https://docs.ray.io/en/latest/ray-air/api/doc/ray.air.CheckpointConfig.html).
