### ISSUE TITLE
[Data] Negative array slice length with block splitting

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#37864]
### What happened + What you expected to happen

See repro.

```
2023-07-27 10:46:54,474 INFO worker.py:1621 -- Started a local Ray instance.
2023-07-27 10:46:55,211 INFO read_api.py:374 -- To satisfy the requested parallelism of 20, each read task output will be split into 20 smaller blocks.
[dataset]: Run `pip install tqdm` to enable progress reporting.
(raylet) Spilled 2220 MiB, 1 objects, write throughput 1286 MiB/s. Set RAY_verbose_spill_logs=0 to disable this message.
(raylet) Spilled 6660 MiB, 3 objects, write throughput 2227 MiB/s.
(raylet) Spilled 11100 MiB, 5 objects, write throughput 2275 MiB/s.

...

Traceback (most recent call last):
  File "/Users/balaji/Documents/GitHub/ray/repro.py", line 18, in <module>
    ray.data.read_datasource(CustomDatasource(), paths="empty.dat").materialize()
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.9/site-packages/ray/data/dataset.py", line 4149, in materialize
    copy._plan.execute(force_read=True)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.9/site-packages/ray/data/_internal/plan.py", line 645, in execute
    self._snapshot_blocks = self._snapshot_blocks.compute_to_blocklist()
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.9/site-packages/ray/data/_internal/lazy_block_list.py", line 358, in compute_to_blocklist
    blocks, metadata = self._get_blocks_with_metadata()
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.9/site-packages/ray/data/_internal/lazy_block_list.py", line 323, in _get_blocks_with_metadata
    generators = read_progress_bar.fetch_until_complete(unique_refs)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.9/site-packages/ray/data/_internal/progress_bar.py", line 93, in fetch_until_complete
    for ref, result in zip(done, ray.get(done)):
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.9/site-packages/ray/_private/worker.py", line 2493, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ArrowIndexError): ray::_execute_read_task_split() (pid=7826, ip=127.0.0.1)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.9/site-packages/ray/data/_internal/lazy_block_list.py", line 695, in _execute_read_task_split
    for block in blocks:
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.9/site-packages/ray/data/datasource/datasource.py", line 215, in __call__
    yield from self._do_additional_splits(block)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.9/site-packages/ray/data/datasource/datasource.py", line 231, in _do_additional_splits
    yield block.slice(offset, offset + size, copy=True)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.9/site-packages/ray/data/_internal/arrow_block.py", line 215, in slice
    view = _copy_table(view)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.9/site-packages/ray/data/_internal/arrow_block.py", line 653, in _copy_table
    return transform_pyarrow.combine_chunks(table)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.9/site-packages/ray/data/_internal/arrow_ops/transform_pyarrow.py", line 282, in combine_chunks
    arr = _concatenate_extension_column(col)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.9/site-packages/ray/air/util/transform_pyarrow.py", line 34, in _concatenate_extension_column
    return ArrowTensorArray._concat_same_type(ca.chunks)
  File "/Users/balaji/Documents/GitHub/ray/.venv/lib/python3.9/site-packages/ray/air/util/tensor_extensions/arrow.py", line 491, in _concat_same_type
    storage = pa.concat_arrays([c.storage for c in to_concat])
  File "pyarrow/array.pxi", line 3321, in pyarrow.lib.concat_arrays
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 127, in pyarrow.lib.check_status
pyarrow.lib.ArrowIndexError: Negative array slice length
```

### Versions / Dependencies

Ray: 052fb7899a1f966f8fa5223601c5fb4542dea2ae
pyarrow==12.0.1

### Reproduction script

```python
import ray
import numpy as np
import pyarrow
from ray.data.block import Block
from ray.data.datasource import FileBasedDatasource
from ray.data._internal.delegating_block_builder import DelegatingBlockBuilder


class CustomDatasource(FileBasedDatasource):

    def _read_file(self, f: "pyarrow.NativeFile", path: str, **reader_args) -> Block:
        batch = {"data": np.zeros((25256, 240, 320, 3))}
        builder = DelegatingBlockBuilder()
        builder.add_batch(batch) 
        return builder.build()
    

ray.data.read_datasource(CustomDatasource(), paths="empty.dat").materialize()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by bveeramani** [comment]
Looks like there's an issue with slicing arrays with our extension type. Here's a more minimal repro:

```
import numpy as np
from ray.data._internal.delegating_block_builder import DelegatingBlockBuilder

builder = DelegatingBlockBuilder()
batch = {"data": np.zeros((25256, 240, 320, 3))}
builder.add_batch(batch)
table = builder.build()

view = table.slice(8841, 10104)
print(view)
```

```
pyarrow.Table
data: extension<arrow.py_extension_type<ArrowTensorType>>
----
data: [<Invalid array: Negative offsets in list array>] 
```

**Comment by bveeramani** [comment]
For some reason, slicing only fails for certain offsets:
```
Offset   Status
------   ------
0        OKAY
1263     OKAY
2526     OKAY
3789     OKAY
5052     OKAY
6315     OKAY
7578     OKAY
8841     ERROR
10104    ERROR
11367    ERROR
12630    ERROR
13893    ERROR
15156    ERROR
16419    ERROR
17682    ERROR
18945    OKAY
20208    OKAY
21471    OKAY
22734    OKAY
23997    OKAY
```
