### ISSUE TITLE
[Data] `read_images_train_4_cpu` release test fails for 1 worker case

### ISSUE THREAD

**Issue by scottjlee** [ray-project/ray#37918]
### What happened + What you expected to happen

The [release test](https://github.com/ray-project/ray/blob/master/release/nightly_tests/dataset/image_train_benchmark.py) `read_images_train_4_cpu` has two issues when run with 1 worker:

1) 1 worker + no local shuffle: spilling
```
(pid=2637, ip=10.0.43.137) Running: 0.0/16.0 CPU, 0.0/0.0 GPU, 4.19 GiB/1.86 GiB object_store_memory: 100%|█| 200/2
```
The object store memory usage is way beyond the restriction.
2) 1 worker + local shuffle: spilling + OOM failure
```
(raylet, ip=10.0.43.137) Spilled 8655 MiB, 193 objects, write throughput 601 MiB/s.  
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/worker.py", line 2493, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::_Inner.train() (pid=320, ip=10.0.43.137, actor_id=c2ca765cbce8e779a44b3b0e02000000, repr=TorchTrainer)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 375, in train
    raise skipped from exception_cause(skipped)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 349, in entrypoint
    return self._trainable_func(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/base_trainer.py", line 809, in _trainable_func
    super()._trainable_func(self._merged_config, reporter, checkpoint_dir)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 666, in _trainable_func
    output = fn()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/base_trainer.py", line 719, in train_func
    trainer.training_loop()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/data_parallel_trainer.py", line 520, in training_loop
    self._report(training_iterator)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/data_parallel_trainer.py", line 427, in _report
    for results in training_iterator:
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/trainer.py", line 149, in __next__
    next_results = self._run_with_error_handling(self._fetch_next_result)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/trainer.py", line 112, in _run_with_error_handling
    return func()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/trainer.py", line 183, in _fetch_next_result
    results = self._backend_executor.get_next_results()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/backend_executor.py", line 485, in get_next_results
    results = self.get_with_failure_handling(futures)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/backend_executor.py", line 585, in get_with_failure_handling
    self._increment_failures()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/backend_executor.py", line 647, in _increment_failures
    raise failure
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 54, in check_for_failure
    ray.get(object_ref)
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
        class_name: RayTrainWorker
        actor_id: c8c5be0201e036dc018c49f502000000
        pid: 352
        namespace: d8788044-0e4f-4b97-b6e9-716d9fc66a8a
        ip: 10.0.43.137
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
2023-07-28 15:54:23,115 ERROR tune.py:1144 -- Trials did not complete: [TorchTrainer_7d269_00000]
2023-07-28 15:54:23,121 WARNING experiment_analysis.py:916 -- Failed to read the results for 1 trials:
- /home/ray/ray_results/TorchTrainer_2023-07-28_15-52-54/TorchTrainer_7d269_00000_0_2023-07-28_15-52-54
ray.exceptions.RayTaskError: ray::_Inner.train() (pid=320, ip=10.0.43.137, actor_id=c2ca765cbce8e779a44b3b0e02000000, repr=TorchTrainer)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 375, in train
    raise skipped from exception_cause(skipped)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 349, in entrypoint
    return self._trainable_func(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/base_trainer.py", line 809, in _trainable_func
    super()._trainable_func(self._merged_config, reporter, checkpoint_dir)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 666, in _trainable_func
    output = fn()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/base_trainer.py", line 719, in train_func
    trainer.training_loop()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/data_parallel_trainer.py", line 520, in training_loop
    self._report(training_iterator)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/data_parallel_trainer.py", line 427, in _report
    for results in training_iterator:
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/trainer.py", line 149, in __next__
    next_results = self._run_with_error_handling(self._fetch_next_result)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/trainer.py", line 112, in _run_with_error_handling
    return func()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/trainer.py", line 183, in _fetch_next_result
    results = self._backend_executor.get_next_results()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/backend_executor.py", line 485, in get_next_results
    results = self.get_with_failure_handling(futures)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/backend_executor.py", line 585, in get_with_failure_handling
    self._increment_failures()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/backend_executor.py", line 647, in _increment_failures
    raise failure
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 54, in check_for_failure
    ray.get(object_ref)
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
        class_name: RayTrainWorker
        actor_id: c8c5be0201e036dc018c49f502000000
        pid: 352
        namespace: d8788044-0e4f-4b97-b6e9-716d9fc66a8a
        ip: 10.0.43.137
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
```

### Versions / Dependencies

ray master
Python 3.9.16

### Reproduction script

https://github.com/ray-project/ray/blob/master/release/nightly_tests/dataset/image_train_benchmark.py
1 head node m5.2xlarge
1 worker node m5.2xlarge

### Issue Severity

High: It blocks me from completing my task.

**Comment by amogkam** [comment]
You can reproduce with just this

```python
ray.data.DataContext.get_current().execution_options.resource_limits.object_store_memory = 2e9

ray_dataset = ray.data.read_images("s3://air-cuj-imagenet-1gb")
 it = ray_dataset.iterator()
    for _ in range(10):
        for batch in it.iter_batches(
            batch_size=args.batch_size,
            local_shuffle_buffer_size=args.local_shuffle_buffer_size,
            prefetch_batches=0,
        ):
            pass
```
