### ISSUE TITLE
[Data] Aggregating on dataset with mixture of Block types causes pyarrow `AttributeError`

### ISSUE THREAD

**Issue by scottjlee** [ray-project/ray#37963]
### What happened + What you expected to happen

When I run all tests in the entire `test_consumption.py` file, the pandas-1 and pandas-30 cases will fail. However, if i run the `test_global_tabular_max`, `test_global_tabular_mean`, and `test_global_tabular_min` tests individually (including the entire test suite at once), they will pass. The error seems to be related to the case where the dataset has multiple blocks, some of which are empty, and we perform an aggregation on the dataset. The minimum reproducible example below narrows down the issue at hand.

### Versions / Dependencies

ray master, Python 3.9

### Reproduction script

```
import ray
ds = ray.data.range(10)
ds = ds.map_batches(lambda x: x, batch_size=None, batch_format="pandas")
assert ds.filter(lambda r: r["id"] > 10).max("id") is None
```

which gives the following:

```
Traceback (most recent call last):                                                                                                
  File "<stdin>", line 1, in <module>                                                                                                                                      
  File "/Users/sjl/src/ray/python/ray/data/dataset.py", line 2054, in max                                                                                                  
    ret = self._aggregate_on(Max, on, ignore_nulls)                                                                                                                        
  File "/Users/sjl/src/ray/python/ray/data/dataset.py", line 4855, in _aggregate_on
    return self.aggregate(*aggs)
  File "/Users/sjl/src/ray/python/ray/data/dataset.py", line 1928, in aggregate
    ret = self.groupby(None).aggregate(*aggs).take(1)
  File "/Users/sjl/src/ray/python/ray/data/dataset.py", line 2346, in take
    for row in self.iter_rows():
  File "/Users/sjl/src/ray/python/ray/data/iterator.py", line 241, in iter_rows
    for batch in self.iter_batches(**iter_batch_args):
  File "/Users/sjl/src/ray/python/ray/data/iterator.py", line 163, in iter_batches
    block_iterator, stats, blocks_owned_by_consumer = self._to_block_iterator()
  File "/Users/sjl/src/ray/python/ray/data/_internal/iterator/iterator_impl.py", line 32, in _to_block_iterator
    block_iterator, stats, executor = ds._plan.execute_to_iterator()
  File "/Users/sjl/src/ray/python/ray/data/_internal/plan.py", line 538, in execute_to_iterator
    block_iter = itertools.chain([next(gen)], gen)
  File "/Users/sjl/src/ray/python/ray/data/_internal/execution/legacy_compat.py", line 51, in execute_to_legacy_block_iterator
    for bundle in bundle_iter:
  File "/Users/sjl/src/ray/python/ray/data/_internal/execution/interfaces/executor.py", line 37, in __next__
    return self.get_next()
  File "/Users/sjl/src/ray/python/ray/data/_internal/execution/streaming_executor.py", line 128, in get_next
    raise item
  File "/Users/sjl/src/ray/python/ray/data/_internal/execution/streaming_executor.py", line 186, in run
    while self._scheduling_loop_step(self._topology) and not self._shutdown:
  File "/Users/sjl/src/ray/python/ray/data/_internal/execution/streaming_executor.py", line 266, in _scheduling_loop_step
    update_operator_states(topology)
  File "/Users/sjl/src/ray/python/ray/data/_internal/execution/streaming_executor_state.py", line 359, in update_operator_states
    op.all_inputs_done()
  File "/Users/sjl/src/ray/python/ray/data/_internal/execution/operators/base_physical_operator.py", line 88, in all_inputs_done
    self._output_buffer, self._stats = self._bulk_fn(self._input_buffer, ctx)
  File "/Users/sjl/src/ray/python/ray/data/_internal/planner/aggregate.py", line 76, in fn
    return scheduler.execute(refs, num_outputs, ctx)
  File "/Users/sjl/src/ray/python/ray/data/_internal/planner/exchange/pull_based_shuffle_task_scheduler.py", line 89, in execute
    new_metadata = reduce_bar.fetch_until_complete(list(new_metadata))
  File "/Users/sjl/src/ray/python/ray/data/_internal/progress_bar.py", line 93, in fetch_until_complete
    for ref, result in zip(done, ray.get(done)):
  File "/Users/sjl/src/ray/python/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/Users/sjl/src/ray/python/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/sjl/src/ray/python/ray/_private/worker.py", line 2520, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::reduce() (pid=62056, ip=127.0.0.1)
  File "/Users/sjl/src/ray/python/ray/data/_internal/planner/exchange/aggregate_task_spec.py", line 70, in reduce
    return BlockAccessor.for_block(mapper_outputs[0]).aggregate_combined_blocks(
  File "/Users/sjl/src/ray/python/ray/data/_internal/pandas_block.py", line 517, in aggregate_combined_blocks
    next_row = next(iter)
  File "/opt/anaconda3/envs/ray-build/lib/python3.9/heapq.py", line 373, in merge
    value = next()
  File "/Users/sjl/src/ray/python/ray/data/_internal/table_block.py", line 194, in __next__
    row = outer._get_row(self._cur)
  File "/Users/sjl/src/ray/python/ray/data/_internal/table_block.py", line 159, in _get_row
    base_row = self.slice(index, index + 1, copy=copy)
  File "/Users/sjl/src/ray/python/ray/data/_internal/pandas_block.py", line 155, in slice
    view.reset_index(drop=True, inplace=True)
AttributeError: 'pyarrow.lib.Table' object has no attribute 'reset_index'
>>> 2023-07-31 18:33:46,743	ERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::reduce() (pid=62056, ip=127.0.0.1)
  File "/Users/sjl/src/ray/python/ray/data/_internal/planner/exchange/aggregate_task_spec.py", line 70, in reduce
    return BlockAccessor.for_block(mapper_outputs[0]).aggregate_combined_blocks(
  File "/Users/sjl/src/ray/python/ray/data/_internal/pandas_block.py", line 517, in aggregate_combined_blocks
    next_row = next(iter)
  File "/opt/anaconda3/envs/ray-build/lib/python3.9/heapq.py", line 373, in merge
    value = next()
  File "/Users/sjl/src/ray/python/ray/data/_internal/table_block.py", line 194, in __next__
    row = outer._get_row(self._cur)
  File "/Users/sjl/src/ray/python/ray/data/_internal/table_block.py", line 159, in _get_row
    base_row = self.slice(index, index + 1, copy=copy)
  File "/Users/sjl/src/ray/python/ray/data/_internal/pandas_block.py", line 155, in slice
    view.reset_index(drop=True, inplace=True)
AttributeError: 'pyarrow.lib.Table' object has no attribute 'reset_index'
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by scottjlee** [comment]
It looks like the root of the issue is that we are using PandasBlock's aggregate_combined_blocks method, but the internal self._table is an Arrow table, and not a pandas DataFrame as expected.

The root cause can be traced to here:  https://github.com/ray-project/ray/blob/master/python/ray/data/_internal/planner/exchange/aggregate_task_spec.py#L70

When we run the reproducible example above, and print out the types of the Blocks in `mapper_outputs`, we see:
```
[<class 'pandas.core.frame.DataFrame'>, <class 'pyarrow.lib.Table'>, <class 'pandas.core.frame.DataFrame'>, <class 'pyarrow.lib.Table'>, <class 'pandas.core.frame.DataFrame'>, <class 'pyarrow.lib.Table'>, <class 'pandas.core.frame.DataFrame'>, <class 'pyarrow.lib.Table'>, <class 'pandas.core.frame.DataFrame'>, <class 'pyarrow.lib.Table'>, <class 'pandas.core.frame.DataFrame'>, <class 'pyarrow.lib.Table'>, <class 'pandas.core.frame.DataFrame'>, <class 'pyarrow.lib.Table'>, <class 'pandas.core.frame.DataFrame'>, <class 'pyarrow.lib.Table'>, <class 'pandas.core.frame.DataFrame'>, <class 'pyarrow.lib.Table'>, <class 'pandas.core.frame.DataFrame'>, <class 'pyarrow.lib.Table'>]
```

so the problem is that we get the BlockAccessor based off the first block, and assume all other blocks are of the same type.

**Comment by scottjlee** [comment]
Closed by https://github.com/ray-project/ray/pull/38161
