### ISSUE TITLE
Ctrl-C breaks Ray in interactive Python

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#3797]
To reproduce this:

1. pip install ray in 3.6
2. run `python`
3. `import ray; ray.init()`
4. Hit `Ctrl-C`.

```
>>> WARNING: Logging before InitGoogleLogging() is written to STDERR
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0116 18:51:21.137943 2857812864 raylet_extension.cc:68]  Check failed: _s.ok() [RayletClient] Failed to get a task from raylet.: IOError: [RayletClient] Raylet connection closed.
F0116 18:51:21.137928 2857812864 raylet_extension.cc:68]  Check failed: _s.ok() [RayletClient] Failed to get a task from raylet.: IOError: [RayletClient] Raylet connection closed.
*** Check failure stack trace: ***
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0116 18:51:21.137985 2857812864 raylet_extension.cc:68]  Check failed: _s.ok() [RayletClient] Failed to get a task from raylet.: IOError: [RayletClient] Raylet connection closed.
*** Check failure stack trace: ***
Fatal Python error: AbortedWARNING: Logging before InitGoogleLogging() is written to STDERR


F0116 18:51:21.138016 2857812864 raylet_extension.cc:68]  Check failed: _s.ok() [RayletClient] Failed to get a task from raylet.: IOError: [RayletClient] Raylet connection closed.
Stack (most recent call first):
*** Check failure stack trace: ***
  File "/Fatal Python error: UsAbortede

rStack (most recent call first):
s*** Check failure stack trace: ***
  File /r"Fatal Python error: liAborted/a

UwStack (most recent call first):
s/e  File mr"isn//irUclsoiFatal Python error: eanrAbortedws

d//Stack (most recent call first):
arm3l  File i/i"naeiwnc/v/omsUni/dsnraieac3roy/sn_ed/tane3rv/sletins/va/lswr/i/raWARNING: Logging before InitGoogleLogging() is written to STDERR
aymybF0116 18:51:21.138135 2857812864 raylet_extension.cc:68]  Check failed: _s.ok() [RayletClient] Failed to get a task from raylet.: IOError: [RayletClient] Raylet connection closed.
_/_ipttnyeeitsscthot/no/d*** Check failure stack trace: ***
llnai33b.i/6b//pe/sypnitvythsFatal Python error: to/eAbortednh

3o-r.Stack (most recent call first):
na6py/3  File as_."ictt6ke//e-aspsUtas/gcliekitrabeesg//epr-sypl/tsrhaWARNING: Logging before InitGoogleLogging() is written to STDERR
/aiorF0116 18:51:21.138226 2857812864 raylet_extension.cc:68]  Check failed: _s.ok() [RayletClient] Failed to get a task from raylet.: IOError: [RayletClient] Raylet connection closed.
acynawk3//.ym6wa//osgirwikneoi*** Check failure stack trace: ***
sct/eeorr-rnka.dypape3y/r/awe"cno., line kvr966apFatal Python error:  in gysAbortede/_"

grks, line Stack (most recent call first):
ee/966trra_ in   File y.anp_yyte_""ex/s, line gt/et966_/ in tlt_i_gbeant/sepkUx_y_tfsn_rteetorxmasht_/slrko_l_ntif3aar.swok6/m_/o_fscmlairiootncmeial_-c_lposlanocc_cdkashalcegad_e3hssuec//dhlreuaenldyveu/srwl/
eor  File rra"k
/ye  File Ur"_s./tepUeysrse"str, line /s/966r/ in llWARNING: Logging before InitGoogleLogging() is written to STDERR
iir_blF0116 18:51:21.138424 2857812864 raylet_extension.cc:68]  Check failed: _s.ok() [RayletClient] Failed to get a task from raylet.: IOError: [RayletClient] Raylet connection closed.
g/iaeapwtw/y/_mmntieihnxno*** Check failure stack trace: ***
tin_ci3toc.ano6sdnka/_3df/saeri3onFatal Python error: t/vmAbortedes_e

-nStack (most recent call first):
/lpv  File rosaa"cy/ca_r/klaUt_assyeegc_srhtes/et/sdleruisbl//leptryr/i
alat  File iyw"hb///o/wmpoUnirysnkti3ee.hr6rcs/o.ns/por3ilntiyea.dw-6"/a/, line mps966iai in cnt_keiag-cepgotane_cdsnk/aear3xg/ateey_s3t/n/a/wvsreoskr/arkna_yvyef/s_rw/torerros.akptmyy/__l"et, line irl983b. in /oeppmcyysaatitlhn/_"_ols, line lin983cb3o/ in .phm6oyaep/i
stn  File ihdt"_u/elo-Ulpsoneeo3rrpa.sc
/k
6a  File rg/  File es""/seiUrst/
eeU/  File r-s"pre/saUra/ssyc/e/rkrwarsgo/llreiirlsaai/kware/wrm./waip/mymi/iWARNING: Logging before InitGoogleLogging() is written to STDERR
ywnF0116 18:51:21.138753 2857812864 raylet_extension.cc:68]  Check failed: _s.ok() [RayletClient] Failed to get a task from raylet.: IOError: [RayletClient] Raylet connection closed.
"ionncir, line cioo983cnkodnen in *** Check failure stack trace: ***
drdam.aap33a3/y/ie/e"nne, line vn_966nvs in Fatal Python error: l/vsrAbortedo/_

ogarestStack (most recent call first):
pya_/_n
y  File ter_xe  File at""tye_s_//stUtUsteesats//erlsrslk/s_it/irrfbl/b/rlilpoiaimb/a_wyw/t//hlmmppiiooynntcnhyia3oli.n_6cc3osotnnc/.hddohsaaenid363ut/3l/e/.eese-r6n
pnv  File aisv/c"sts/k/r/aUeigraseaesyry/trs_ea_/ywrttle-e/iospawtsr/woka/rlmkciieenrirkcba.o.gpnepdsyy/atp""y/, line , line 3tr/983h966ae in oynn/m3vwsa. in o/6_irrn/kas_eyglr_oiesttot/e_pesd-tne/
ef  File xpltaa"i_cu/tblUa/tskpsey_rtkawsh/g_oofrerrsnl/o/i3-llp.rmaiaab_ycw//l/6kwo/ompsraiyicgtktneaelsihe/oc_-onprn3rid.aaas.36ycp//kcsyaie"ntg, line ev/hw-s966eeasd in /wuo_/lrrega/reypar/tawkyo_
ner_er  File t.cx"eptk/sykmUe_"trt/a, line lsa.i983spb in g/ykepe"r_, line ms983fs in ya/rimo/arrtnilmi_h_nloio_lnoal3pwo.oc
6oa/pla/_
  File smy  File "s//i"cUtwi/honUsesreee-rdpiuskar/eclrrcelsok/rsinradlg/a
aid3wae  File //wse"/e/mm/irfnainaUyiusv/necwlroston/idr_csaor/nkradlwai3eya3r/_so/we/e/ndtrmveieknfsse/atrvn/suir/.cralpoaltyyny__"iwd_toae, line brs93/t in 3ektp/se/<etlrn/mi.vbpysly//i"tpobr, line yd/up93th in hal<ooyemytnon_dh33uo>tln
e.e3.>6s.6
/6t//s/ssliiititebt-e/pe-pa-pycptakhaacokcngake3gas.e/g6rsen/asi/sy/rcrio/tanwyoea/dr-waypoka3/c/ekwrreaskn/evgdrseeosfsr//a/krurdelaaeyyr_f/t.w_atpwuoeyorlrkstekt_"erw, line ro./r983p.kyp in eyl""rm, line , line .a93983pi in  in y<nmm"_oa, line dliu93onl in o_<plm
oo  File dou"pl/e
U>  File s
"e/rUsse/e>rr
lsi/arwl/imaiwn/imcionnidcao3n/dean3v/se/nrvasy/_rtaeys_tt/elsitb//lpiybt/hpoynt3h.o6n/3s.6/sitei-tpea-cpkaacgkeasg/ersa/yr/awyo/rwkers/default_worker.py", line 93 in <module>
orkiebr/sp/ydefaultt_hwoonr3k.e6r/.sipte-packages/rya"yk/, line we93or in r.<kpmeyordsu/ldee>f
ault_worker.py", line 93 in <mo"du, line l93e in >
<module>
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0116 18:51:21.230031 224296960 raylet_client.cc:345] IOError: [RayletClient] Connection closed unexpectedly. [RayletClient] Failed to push profile events.

Error in sys.excepthook:
Traceback (most recent call last):
  File "/Users/rliaw/miniconda3/envs/ray_test/lib/python3.6/site-packages/redis/connection.py", line 181, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/Users/rliaw/miniconda3/envs/ray_test/lib/python3.6/site-packages/redis/_compat.py", line 71, in recv
    return sock.recv(*args, **kwargs)
ConnectionResetError: [Errno 54] Connection reset by peer```

**Comment by robertnishihara** [comment]
Maybe related to #2633.

**Comment by mitar** [comment]
Where was this fixed?
