### ISSUE TITLE
[data] read_images().take(1) produces scary errors

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#38021]
### What happened + What you expected to happen

Taking 1 image from a dataset works as expected but produces some scary-looking error messages about workers dying and a pyarrow exception that is apparently harmless. I think these are related to task cancellation.

### Versions / Dependencies

3.0dev

### Reproduction script

```python
In [24]: local_ds = ray.data.read_images("/home/ray/imagenet-1000/imagenet-mini/train/")

In [25]: %time img = ds2.take(1)
2023-08-02 12:00:37,502 INFO streaming_executor.py:92 -- Executing DAG InputDataBuffer[Input] -> TaskPoolMapOperator[ReadImage] -> LimitOperator[limit=1]
2023-08-02 12:00:37,502 INFO streaming_executor.py:93 -- Execution config: ExecutionOptions(resource_limits=ExecutionResources(cpu=None, gpu=None, object_store_memory=None), locality_with_output=False, preserve_order=False, actor_locality_enabled=True, verbose_progress=True)
2023-08-02 12:00:39,349 WARNING worker.py:2033 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 773f6165cbbbe5f2731165c4a7bfc02c03d1726c47010000 Worker ID: 98cf4dcc97a0eb8dabd1d6817a6d1aa1919480fb190d1181f4cd7896 Node ID: e6aef33925f0e880629da00475ae70cd620a1e5c45b4b20c534cd92d Worker IP address: 10.0.27.60 Worker port: 10089 Worker PID: 128668 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
2023-08-02 12:00:39,368 WARNING worker.py:2033 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 984a49cb3f482921ba738ded7468ce80edf5d16747010000 Worker ID: 7e338d3918699608e72258141995ba5e5305b917b36a80f8229dfde3 Node ID: e6aef33925f0e880629da00475ae70cd620a1e5c45b4b20c534cd92d Worker IP address: 10.0.27.60 Worker port: 10063 Worker PID: 117989 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
2023-08-02 12:00:39,369 WARNING worker.py:2033 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: fe3777ed6aa05d02c5f728b058b14ee8bd1a5de547010000 Worker ID: bc6319ac379b928fa09e111ef03c15e977bf6d260fb7efae5fa0bc94 Node ID: e6aef33925f0e880629da00475ae70cd620a1e5c45b4b20c534cd92d Worker IP address: 10.0.27.60 Worker port: 10083 Worker PID: 122571 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
                                                                                                                                                                                 CPU times: user 320 ms, sys: 24.4 ms, total: 345 ms                                                                                                                                
Wall time: 1.87 s                                                                                                                                                                 

(ReadImage pid=124927) Traceback (most recent call last):
(ReadImage pid=124927)   File "pyarrow/public-api.pxi", line 124, in pyarrow.lib.pyarrow_wrap_data_type
(ReadImage pid=124927)   File "pyarrow/types.pxi", line 452, in pyarrow.lib.StructType.init
(ReadImage pid=124927)   File "pyarrow/types.pxi", line 142, in pyarrow.lib.DataType.init
(ReadImage pid=124927)   File "pyarrow/types.pxi", line 76, in pyarrow.lib._datatype_to_pep3118
(ReadImage pid=124927)   File "pyarrow/types.pxi", line 1021, in pyarrow.lib.PyExtensionType.__arrow_ext_deserialize__
(ReadImage pid=124927)   File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/air/util/tensor_extensions/arrow.py", line 543, in __init__
(ReadImage pid=124927)     def __init__(self, dtype: pa.DataType, ndim: int):
(ReadImage pid=124927) KeyboardInterrupt: 
(ReadImage pid=124927) Task failed with retryable exception: TaskID(34a4ce30b24da3c2ffffffffffffffffffffffff47010000).
(ReadImage pid=124927) Traceback (most recent call last):
(ReadImage pid=124927)   File "python/ray/_raylet.pyx", line 1204, in ray._raylet.execute_dynamic_generator_and_store_task_outputs
(ReadImage pid=124927)     and core_worker.get_current_task_retry_exceptions()
(ReadImage pid=124927)   File "python/ray/_raylet.pyx", line 3731, in ray._raylet.CoreWorker.store_task_outputs
(ReadImage pid=124927)     # create another copy.
(ReadImage pid=124927)   File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 415, in _map_task
(ReadImage pid=124927)     for b_out in fn(iter(blocks), ctx):
(ReadImage pid=124927)   File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/planner/plan_read_op.py", line 67, in do_read
(ReadImage pid=124927)     yield from read_task()
(ReadImage pid=124927)   File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/datasource/datasource.py", line 217, in __call__
(ReadImage pid=124927)     for block in result:
(ReadImage pid=124927)   File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 487, in read_files
(ReadImage pid=124927)     yield output_buffer.next()
(ReadImage pid=124927)   File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/output_buffer.py", line 74, in next
(ReadImage pid=124927)     block = self._buffer.build()
(ReadImage pid=124927)   File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/delegating_block_builder.py", line 64, in build
(ReadImage pid=124927)     return self._builder.build()
(ReadImage pid=124927)   File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/table_block.py", line 123, in build
(ReadImage pid=124927)     return self._concat_tables(tables)
(ReadImage pid=124927)   File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/arrow_block.py", line 128, in _concat_tables
(ReadImage pid=124927)     return transform_pyarrow.concat(tables)
(ReadImage pid=124927)   File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/arrow_ops/transform_pyarrow.py", line 249, in concat
(ReadImage pid=124927)     table = pyarrow.Table.from_arrays(cols, schema=schema)
(ReadImage pid=124927)   File "pyarrow/table.pxi", line 3674, in pyarrow.lib.Table.from_arrays
(ReadImage pid=124927)   File "pyarrow/table.pxi", line 2837, in pyarrow.lib.Table.validate
(ReadImage pid=124927)   File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
(ReadImage pid=124927) pyarrow.lib.ArrowInvalid: Column 0: In chunk 62 expected type extension<arrow.py_extension_type<ArrowVariableShapedTensorType>> but saw extension<arrow.py_extension_type<ArrowVariableShapedTensorType>>
```

### Issue Severity

None

**Comment by stephanie-wang** [comment]
(Adding back the data label just for tracking purposes, but I do believe this is a core issue)

**Comment by jjyao** [comment]
@stephanie-wang @amogkam what is the priority for this one? What's your expected message?

**Comment by xieus** [comment]
Synced up with @amogkam offline - we don't have a repro for now. Will sync up with @stephanie-wang.

**Comment by stephanie-wang** [comment]
The PR description has a repro. I think any image folder will work, but the one used there is downloaded from the private bucket `s3://imagenetmini-1000/train`.

**Comment by ericl** [comment]
This is due to auto-cancellation on executor shutdown? This is unfortunate.

Short term, the risk of leaking resources might be worse than a few scary messages. That said, we should fix the messages:

1. For the task exception messages, is this since we aren't properly catching/suppressing these? I thought we actually did ray.get() the tasks after cancellation to suppress the errors before. This could be a regression [**in data**].

2. For the worker died messages, it seems like we should not be logging these for explicit cancellations [**in core**].
