### ISSUE TITLE
[tune] PyTorch ConnectionResetError for Multiprocessing

### ISSUE THREAD

**Issue by xiayandi** [ray-project/ray#3803]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.1 LTS
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.1
- **Python version**: 3.6.7
- **PyTorch version**: 1.0.0
- **Exact command to reproduce**: python mnist_pytorch.py

### Describe the problem

In your PyTorch example, https://github.com/ray-project/ray/blob/ray-0.6.1/python/ray/tune/examples/mnist_pytorch.py
If I change "num_workers" from 1 to n (n > 1), I will get a "ConnectionResetError" raised from PyTorch multiprocessing.

Here is the change I made to the example code:
```
kwargs = {'num_workers': 2, 'pin_memory': True} if args.cuda else {}

"resources_per_trial": {
     "cpu": 3,
     "extra_cpu": 3,
     "gpu": 1,
},
```
### Source code / logs

```
Error:
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/******/env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 158, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/******/env/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 256, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
    return recvfds(s, 1)[0]
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 153, in recvfds
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_SPACE(bytes_size))
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by richardliaw** [comment]
Sorry for the late reply - could this simply be a pytorch problem?

**Comment by richardliaw** [comment]
(Closing this because stale, feel free to reopen)
