### ISSUE TITLE
[xgboost ray] raises 'NoneType' object has no attribute 'fs'

### ISSUE THREAD

**Issue by Mrforeman1** [ray-project/ray#38055]
### What happened + What you expected to happen

When I type in from xgboost_ray import RayXGBClassifier, RayParams
```
Traceback (most recent call last):
  File "/home/mforeman/miniconda3/envs/rapids-23.06/classifiers4.py", line 11, in <module>
    from xgboost_ray import RayXGBClassifier, RayParams
  File "/home/mforeman/miniconda3/envs/rapids-23.06/lib/python3.10/site-packages/xgboost_ray/__init__.py", line 1, in <module>
    from xgboost_ray.main import RayParams, predict, train
  File "/home/mforeman/miniconda3/envs/rapids-23.06/lib/python3.10/site-packages/xgboost_ray/main.py", line 76, in <module>
    from xgboost_ray.matrix import (
  File "/home/mforeman/miniconda3/envs/rapids-23.06/lib/python3.10/site-packages/xgboost_ray/matrix.py", line 36, in <module>
    from ray.data.dataset import Dataset as RayDataset
  File "/home/mforeman/miniconda3/envs/rapids-23.06/lib/python3.10/site-packages/ray/data/__init__.py", line 5, in <module>
    from ray.data._internal.compute import ActorPoolStrategy
  File "/home/mforeman/miniconda3/envs/rapids-23.06/lib/python3.10/site-packages/ray/data/_internal/compute.py", line 8, in <module>
    from ray.data._internal.delegating_block_builder import DelegatingBlockBuilder
  File "/home/mforeman/miniconda3/envs/rapids-23.06/lib/python3.10/site-packages/ray/data/_internal/delegating_block_builder.py", line 4, in <module>
    from ray.data._internal.arrow_block import ArrowBlockBuilder
  File "/home/mforeman/miniconda3/envs/rapids-23.06/lib/python3.10/site-packages/ray/data/_internal/arrow_block.py", line 22, in <module>
    from ray.data._internal.numpy_support import (
  File "/home/mforeman/miniconda3/envs/rapids-23.06/lib/python3.10/site-packages/ray/data/_internal/numpy_support.py", line 5, in <module>
    from ray.air.util.tensor_extensions.utils import create_ragged_ndarray
  File "/home/mforeman/miniconda3/envs/rapids-23.06/lib/python3.10/site-packages/ray/air/__init__.py", line 1, in <module>
    from ray.air.checkpoint import Checkpoint
  File "/home/mforeman/miniconda3/envs/rapids-23.06/lib/python3.10/site-packages/ray/air/checkpoint.py", line 22, in <module>
    from ray.air._internal.remote_storage import (
  File "/home/mforeman/miniconda3/envs/rapids-23.06/lib/python3.10/site-packages/ray/air/_internal/remote_storage.py", line 142, in <module>
    _cached_fs: Dict[tuple, Tuple[float, pyarrow.fs.FileSystem]] = {}
AttributeError: 'NoneType' object has no attribute 'fs'
```
I shouldn't get any errors.  When I revert to version 1.5 the errors go away

### Versions / Dependencies

Ray version 2.6.1
ubuntu
python version 3.10.12

### Reproduction script

from lightgbm_ray import RayLGBMClassifier, RayParams

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
What happens if you install pyarrow with `pip install pyarrow`? It's actually part of Ray's requirements.

**Comment by Mrforeman1** [comment]
> What happens if you install pyarrow with `pip install pyarrow`? It's actually part of Ray's requirements.

It was already installed.

**Comment by Mrforeman1** [comment]
The error is no longer there.  I reinstalled Ray with xgboost and lightgbm and the error did not return.  I wonder if the code was fixed.

**Comment by justinvyu** [comment]
This issue should no longer be happening.
