### ISSUE TITLE
Release test serve_autoscaling_single_deployment.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#38102]
Release test **serve_autoscaling_single_deployment.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2019#0189bc7f-311c-42fa-b0b3-7f86fca93501 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Blamed commit: f6da73f09d869fece37164dca8eacdb3f93daa0b found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/472

**Comment by jjyao** [comment]
```
Trials finished!
Traceback (most recent call last):
  File "workloads/autoscaling_single_deployment.py", line 173, in <module>
    main()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "workloads/autoscaling_single_deployment.py", line 155, in main
    all_metrics, all_wrk_stdout = run_wrk_on_all_nodes(
  File "/tmp/ray/session_2023-08-03_10-46-08_112724_50/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_serve_autoscaling_single_deployment_aws_kuhinndzyp__anyscale_pkg_24b1974a31cb47551baf164e923ba1b7/workloads/serve_test_utils.py", line 306, in run_wrk_on_all_nodes
    parsed_metrics["per_thread_latency_avg_ms"]
KeyError: 'per_thread_latency_avg_ms'
```

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2028#0189d420-d7fc-4f9b-b19e-a2a782790257
