### ISSUE TITLE
Problems when running code with ray[ValueError: not enough values to unpack (expected 1, got 0)]

### ISSUE THREAD

**Issue by lazyaa** [ray-project/ray#38170]
This problem occurred when I tried to reproduce the code. The following is the relevant information of the code and the error information.
**System information:**
OS Platform and Distribution:Linux Ubuntu 22.04 LTS
Ray installed from (source or binary): source
Ray version:0.4.0
Python version: 3.6.10
Code used:https://github.com/ninalopatina/Rocket_RL

**python Rocket_RL/python/main.py**
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
 Import the Rocket_RL functions
import Rocket_RL.python.func.data_processing as RocketData
import Rocket_RL.python.func.ray_funcs as RF
import argparse, os, yaml
import ray
from ray.tune import run_experiments
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-rreg','--run_reg', dest = 'run_regression', type = bool,
                        default = True, help = 'True to run the regression')
    parser.add_argument('-sreg','--save_reg', dest = 'save_regression', type = bool,
                        default = False, help = 'True to save the regression')
    parser.add_argument('-rRL','--run_RL', dest = 'run_RL', type = bool,
                        default = True, help = 'True to run RL model')
    parser.add_argument('-pRL','--plot_RL', dest = 'plot_RL', type = bool,
                        default = True, help = 'True to plot RL results')
    parser.add_argument('-plot','--plot_data', dest = 'plot_data', type = int,
                        default = False, help = 'True to plot Fluent simulation data in 3d')
    parser.add_argument('-cfg','--config', dest = 'config_dir', type = str,
                        default = 'Rocket_RL/config/config.yml', help = 'where the config file is located')
    parser.add_argument('-rayinit','--rayinit', dest = 'rayinit', type = bool,
                        default = True, help = 'should only be init the first time you run if running in an IDE')
    args = parser.parse_args()
    CWD_PATH = os.getcwd()
    config_path = os.path.join(CWD_PATH,args.config_dir)
    with open(config_path, 'r') as ymlfile:
        cfg = yaml.load(ymlfile)
    cfg['CWD_PATH'] = CWD_PATH
    # If importing new data, set plot_data to true to take a glance at it to verify
    # if it looks reasonable.
    if (args.plot_data==True) | (args.run_regression == True):
        RocketData.data_process(cfg,args.plot_data,args.run_regression,args.save_regression)
    if args.run_RL == True:
        if args.rayinit == True:
            ray.init()
        run_experiments({
            "RocketRL": {
                "run": cfg['agent'],# Which agent to run
                #conditions under which you would stop:
                "stop": {"time_total_s": cfg['time_total_s'], "timesteps_total": cfg['timesteps_total'], "episode_reward_mean": cfg['episode_reward_mean']},
                #The custom environment:
                "env": "AllVar-v0",
                #Checkpoint on every iteration:
                "checkpoint-freq":1,
                #Num workers has to be 1 fewer than the available CPU!!!!!
                "config": {
                    "num_workers": 0,
                    "gamma": cfg['gamma'],
                    "horizon": cfg['horizon'],
                    "num_sgd_iter": cfg['num_sgd_iter'],
                    "sgd_stepsize": cfg['sgd_stepsize'],
                    "timesteps_per_batch": cfg['timesteps_per_batch'],
                    "min_steps_per_task": cfg['min_steps_per_task']
                },
            },
        })
    if args.plot_RL == True:
        df_model = RF.rllib_plot(cfg)
```

**Describe the problem**
```
/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:455: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:456: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:457: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:458: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:459: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:462: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
ridge  results for degree  4 & var  O_CH4_flow_uniformity :  0.9536069758674987
/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/sklearn/preprocessing/data.py:1263: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  for c in combinations)
ridge  results for degree  4 & var  O_CH4_mol_frac :  0.9886909887188299
/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/sklearn/preprocessing/data.py:1263: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  for c in combinations)
ridge  results for degree  4 & var  O_t :  0.9931738112272647
/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/sklearn/preprocessing/data.py:1263: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  for c in combinations)
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:16308 to respond...
Waiting for redis server at 127.0.0.1:49980 to respond...
Starting local scheduler with the following resources: {'CPU': 1, 'GPU': 0}.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui24862.ipynb?token=2181f6f5ab6ce84cf1a8c5a621b4f5bb2ee9ef8ede5d0ad2
======================================================================

== Status ==
Using FIFO scheduling algorithm.
Result logdir: /home/lzy/ray_results/RocketRL
PENDING trials:
 - PPO_AllVar-v0_0:	PENDING

Created LogSyncer for /home/lzy/ray_results/RocketRL/PPO_AllVar-v0_0_2023-08-07_21-07-40kc09v1wd -> 
WARNING: Serializing objects of type <class 'ray.tune.registry._Registry'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
== Status ==
Using FIFO scheduling algorithm.
Resources used: 1/1 CPUs, 0/0 GPUs
Result logdir: /home/lzy/ray_results/RocketRL
RUNNING trials:
 - PPO_AllVar-v0_0:	RUNNING

/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:455: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:456: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:457: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:458: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:459: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:462: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Observation shape is None
Using a TupleFlatteningPreprocessor
Creating sub-preprocessor for Box(1,)
Observation shape is (1,)
Not using any observation preprocessor.
Creating sub-preprocessor for Box(1,)
Observation shape is (1,)
Not using any observation preprocessor.
Creating sub-preprocessor for Box(1,)
Observation shape is (1,)
Not using any observation preprocessor.
Creating sub-preprocessor for Box(1,)
Observation shape is (1,)
Not using any observation preprocessor.
Creating sub-preprocessor for Box(1,)
Observation shape is (1,)
Not using any observation preprocessor.
Creating sub-preprocessor for Box(1,)
Observation shape is (1,)
Not using any observation preprocessor.
Creating sub-preprocessor for Box(1,)
Observation shape is (1,)
Not using any observation preprocessor.
Creating sub-preprocessor for Box(1,)
Observation shape is (1,)
Not using any observation preprocessor.
Creating sub-preprocessor for Box(1,)
Observation shape is (1,)
Not using any observation preprocessor.
Creating sub-preprocessor for Box(1,)
Observation shape is (1,)
Not using any observation preprocessor.
2023-08-07 21:07:43.949634: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2023-08-07 21:07:43.949792: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2023-08-07 21:07:43.949859: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2023-08-07 21:07:43.949924: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2023-08-07 21:07:43.949986: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "Rocket_RL/python/main.py", line 90, in <module>
    "min_steps_per_task": cfg['min_steps_per_task']
  File "/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/ray/tune/tune.py", line 81, in run_experiments
    runner.step()
  File "/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 91, in step
    self._process_events()
  File "/home/lzy/miniconda3/envs/RocketEnv/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 215, in _process_events
    [result_id], _ = ray.wait(list(self._running))
ValueError: not enough values to unpack (expected 1, got 0)
```

**Comment by sven1977** [comment]
Hey @lazyaa , thanks for filing this issue.
I see that you are on a very very old version of Ray (Ray version:0.4.0) :)
We are not supporting these older versions anymore.
Could you try upgrading to a newer version (e.g. 2.6.x)? And try to reproduce your script in that new version? I took a look at your config and you would have to change the following config keys:
```
sgd_stepsize -> sgd_minibatch_size
timesteps_per_batch -> train_batch_size
min_steps_per_task -> actually, this one I'm not even sure; probably you can just drop this
```

**Comment by lazyaa** [comment]
Thanks for your reply, I will try the method you mentioned @sven1977
