### ISSUE TITLE
Ray cluster in the tunnel of WSL

### ISSUE THREAD

**Issue by pingmalu** [ray-project/ray#38311]
### What happened + What you expected to happen

I used two PCs and they were Windows systems, but I installed the Ubuntu system using WSL2. Then use Zerotier to build a tunnel LAN for the WSL2 Ubuntu environment of two PCs, with the IP addresses of the tunnel LAN being:

A: 10.147.19.20 B: 10.147.19.134

Machine A can connect to Machine B through a tunnel: I formed a ray cluster using the following command:

Machine A:

Ray start -- head -- port=6333-- dashboard host=0.0.0-- node ip address=10.147.19.20-- num CPU=4

Machine B:

Ray start -- address=10.147.19.20:6333-- node ip address=10.147.19.134-- num CPU=4

Everything is normal at this point, and the ray status shows that the two machines are connected normally.

But using it for reinforcement learning training will result in an error:

```
2023-08-10 17:22:36,586 ERROR actor_manager.py:500 -- Ray error, taking actor 3 out of service. The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=2851, ip=10.147.19.134, actor_id=da35b1151ba6e2a3f948186d05000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f01705bdde0>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.OwnerDiedError: Failed to retrieve object 00ffffffffffffffffffffffffffffffffffffff0500000003e1f505. The ObjectRef was created at: (actor call)
  /usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/worker_set.py:_make_worker:925
  /usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/worker_set.py:<listcomp>:572
  /usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/worker_set.py:add_workers:571

The object's owner has exited. This is the Python worker that first created the ObjectRef via `.remote()` or `ray.put()`. Check cluster logs (`/tmp/ray/session_latest/logs/*05000000ffffffffffffffffffffffffffffffffffffffffffffffff*` at IP address 172.18.111.252) for more information about the Python worker failure.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/worker_set.py", line 157, in __init__
    self._setup(
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/worker_set.py", line 227, in _setup
    self.add_workers(
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/worker_set.py", line 593, in add_workers
    raise result.get()
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/utils/actor_manager.py", line 481, in __fetch_result
    result = ray.get(r)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 2522, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=2851, ip=10.147.19.134, actor_id=da35b1151ba6e2a3f948186d05000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f01705bdde0>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.OwnerDiedError: Failed to retrieve object 00ffffffffffffffffffffffffffffffffffffff0500000003e1f505. The ObjectRef was created at: (actor call)
  /usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/worker_set.py:_make_worker:925
  /usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/worker_set.py:<listcomp>:572
  /usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/worker_set.py:add_workers:571

The object's owner has exited. This is the Python worker that first created the ObjectRef via `.remote()` or `ray.put()`. Check cluster logs (`/tmp/ray/session_latest/logs/*05000000ffffffffffffffffffffffffffffffffffffffffffffffff*` at IP address 172.18.111.252) for more information about the Python worker failure
```

If only one ray machine is started, it can operate normally.

### Versions / Dependencies

Ubuntu 20.04.4 LTS  WSL2
Python 3.10.12
ray 2.6.2

pip install -U "ray[default]"

### Reproduction script

this is code:

```python
ray.init()

env_config = {
        'data': data,
        'args': args,
    }

env = TradingEnvironment(env_config)

ray.rllib.utils.check_env(env)
register_env("TradingEnvironment", TradingEnvironment)

config = {
    'env_config': env_config,
    # 'exploration_config': {},
    "num_workers": 3,
    "num_gpus": 1,
    "_enable_rl_module_api": True,
}

algo = ppo.PPO(env="TradingEnvironment",config=config)
for i in range(5):
    print(f"Training iteration {i}")
    reward = algo.train()
    pprint(reward['hist_stats'])
    # print(type(reward),reward)

ray.shutdown()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by pingmalu** [comment]
I think it may be an error caused by Zerotier's tunnel network, but I couldn't find a solution by flipping through the relevant documents

**Comment by ArturNiederfahrenhorst** [comment]
@pingmalu Any new insights on this?

**Comment by anyscalesam** [comment]
bump @pingmalu ?

**Comment by pingmalu** [comment]
The transmission under the tunnel network has a significant impact on performance. I have readjusted the network architecture so that it can be improved @ArturNiederfahrenhorst @anyscalesam
