### ISSUE TITLE
[Windows] Windows init() fails, Video Controller

### ISSUE THREAD

**Issue by jaxnb** [ray-project/ray#38388]
### What happened + What you expected to happen

The `_autodetect_num_gpus()` function in `resource_spec.py` on Windows calls the command: `WMICPATH Win32_VideoController GET AdapterCompatibility`. However, this command (at least on my virtualized qemu windows) returns an error.
My system has 1x NVIDIA GTX 970 using passthrough, although I'm not attempting to use it so I personally am not too concerned with that usecase being supported. However, Ray should initialize without error even if a GPU is not detected.

```
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init()
ERROR:
Description = Not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\Python311\Lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "...\Python311\Lib\site-packages\ray\_private\worker.py", line 1514, in init
    _global_node = ray._private.node.Node(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Python311\Lib\site-packages\ray\_private\node.py", line 290, in __init__
    self.start_ray_processes()
  File "...\Python311\Lib\site-packages\ray\_private\node.py", line 1214, in start_ray_processes
    resource_spec = self.get_resource_spec()
  File "...\Python311\Lib\site-packages\ray\_private\node.py", line 468, in get_resource_spec
    ).resolve(is_head=self.head, node_ip_address=self.node_ip_address)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Python311\Lib\site-packages\ray\_private\resource_spec.py", line 186, in resolve
    num_gpus = _autodetect_num_gpus()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "...\Python311\Lib\site-packages\ray\_private\resource_spec.py", line 298, in _autodetect_num_gpus
    lines = subprocess.check_output(cmdargs).splitlines()[1:]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['WMIC', 'PATH', 'Win32_VideoController', 'GET', 'AdapterCompatibility']' returned non-zero exit status 2147749890.
```
```
PS> WIMC PATH Win32_VideoController GET AdapterCompatibility
ERROR:
Description = Not found
PS> $LASTEXITCODE
-2147217406
```

### Versions / Dependencies

Python 3.11
Ray 2.6.2
Windows 10 (virtualized)

### Reproduction script

```
import ray
ray.init()
```
Note: likely system dependent

### Issue Severity

High: It blocks me from completing my task.

**Comment by anyscalesam** [comment]
Reviewed internal to Anyscale; to take up with QS team to further review and prioritize.

**Comment by mattip** [comment]
I think this would be solved by using gpustat everywhere ray wants to find gpu resources. See PR #35581.

**Comment by mattip** [comment]
For now, I think you can `pip install GPUtil`

**Comment by mattip** [comment]
@jaxnb did installing GPUtil help?

**Comment by mattip** [comment]
I will close this, the need for GPutil has been removed and the detection code refactored. Please open a new issue if this reappears.
