### ISSUE TITLE
Release test many_pgs.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#38404]
Release test **many_pgs.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2045#0189f464-53ea-4b2d-9925-05db2ff89290 for more details.

Managed by OSS Test Policy

**Comment by scv119** [comment]
```


Traceback (most recent call last):
--
  | File "/tmp/ray/session_2023-08-14_07-34-39_025864_48/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_many_pgs_aws_bxlrtcimmb__anyscale_pkg_cfdb3be332a46abf356f3dbbf95c6a43/distributed/dashboard_test.py", line 72, in ping
  | resp.raise_for_status()
  | File "/home/ray/anaconda3/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | Traceback (most recent call last):
  | File "/tmp/ray/session_2023-08-14_07-34-39_025864_48/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_many_pgs_aws_bxlrtcimmb__anyscale_pkg_cfdb3be332a46abf356f3dbbf95c6a43/distributed/dashboard_test.py", line 72, in ping
  | resp.raise_for_status()
  | File "/home/ray/anaconda3/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | Traceback (most recent call last):
  | File "/tmp/ray/session_2023-08-14_07-34-39_025864_48/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_many_pgs_aws_bxlrtcimmb__anyscale_pkg_cfdb3be332a46abf356f3dbbf95c6a43/distributed/dashboard_test.py", line 72, in ping
  | resp.raise_for_status()
  | File "/home/ray/anaconda3/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | Traceback (most recent call last):
  | File "/tmp/ray/session_2023-08-14_07-34-39_025864_48/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_many_pgs_aws_bxlrtcimmb__anyscale_pkg_cfdb3be332a46abf356f3dbbf95c6a43/distributed/dashboard_test.py", line 72, in ping
  | resp.raise_for_status()
  | File "/home/ray/anaconda3/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | Traceback (most recent call last):
  | File "/tmp/ray/session_2023-08-14_07-34-39_025864_48/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_many_pgs_aws_bxlrtcimmb__anyscale_pkg_cfdb3be332a46abf356f3dbbf95c6a43/distributed/dashboard_test.py", line 72, in ping
  | resp.raise_for_status()
  | File "/home/ray/anaconda3/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | Traceback (most recent call last):
  | File "/tmp/ray/session_2023-08-14_07-34-39_025864_48/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_many_pgs_aws_bxlrtcimmb__anyscale_pkg_cfdb3be332a46abf356f3dbbf95c6a43/distributed/dashboard_test.py", line 72, in ping
  | resp.raise_for_status()
  | File "/home/ray/anaconda3/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | Traceback (most recent call last):
  | File "/tmp/ray/session_2023-08-14_07-34-39_025864_48/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_many_pgs_aws_bxlrtcimmb__anyscale_pkg_cfdb3be332a46abf356f3dbbf95c6a43/distributed/dashboard_test.py", line 72, in ping
  | resp.raise_for_status()
  | File "/home/ray/anaconda3/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | Traceback (most recent call last):
  | File "/tmp/ray/session_2023-08-14_07-34-39_025864_48/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_many_pgs_aws_bxlrtcimmb__anyscale_pkg_cfdb3be332a46abf356f3dbbf95c6a43/distributed/dashboard_test.py", line 72, in ping
  | resp.raise_for_status()
  | File "/home/ray/anaconda3/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | Traceback (most recent call last):
  | File "/tmp/ray/session_2023-08-14_07-34-39_025864_48/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_many_pgs_aws_bxlrtcimmb__anyscale_pkg_cfdb3be332a46abf356f3dbbf95c6a43/distributed/dashboard_test.py", line 72, in ping
  | resp.raise_for_status()
  | File "/home/ray/anaconda3/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | Traceback (most recent call last):
  | File "/tmp/ray/session_2023-08-14_07-34-39_025864_48/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_many_pgs_aws_bxlrtcimmb__anyscale_pkg_cfdb3be332a46abf356f3dbbf95c6a43/distributed/dashboard_test.py", line 72, in ping
  | resp.raise_for_status()
  | File "/home/ray/anaconda3/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | Traceback (most recent call last):
  | File "/tmp/ray/session_2023-08-14_07-34-39_025864_48/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_many_pgs_aws_bxlrtcimmb__anyscale_pkg_cfdb3be332a46abf356f3dbbf95c6a43/distributed/dashboard_test.py", line 72, in ping
  | resp.raise_for_status()
  | File "/home/ray/anaconda3/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | Traceback (most recent call last):
  | File "/tmp/ray/session_2023-08-14_07-34-39_025864_48/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_many_pgs_aws_bxlrtcimmb__anyscale_pkg_cfdb3be332a46abf356f3dbbf95c6a43/distributed/dashboard_test.py", line 72, in ping
  | resp.raise_for_status()
  | File "/home/ray/anaconda3/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary
  | Traceback (most recent call last):
  | File "/tmp/ray/session_2023-08-14_07-34-39_025864_48/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_many_pgs_aws_bxlrtcimmb__anyscale_pkg_cfdb3be332a46abf356f3dbbf95c6a43/distributed/dashboard_test.py", line 72, in ping
  | resp.raise_for_status()
  | File "/home/ray/anaconda3/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.0.15.68:8265/nodes?view=summary


```

**Comment by scv119** [comment]
looks like dashboard crashed? doesn't seem a core issue.

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by brucez-anyscale** [comment]
not solved yet. It is due to gRPC size > 4MB. Should not be a blocker for ray release.
If you want to make the test green, you can try to test without PA.

The fix of gRPC size will be a followup, may take several weeks.

**Comment by rickyyx** [comment]
re-assigning since this will be addressed by infra fix later.

**Comment by can-anyscale** [comment]
can we add the 'stable: false' tag to mark it as non-blocking for now, thanks

**Comment by brucez-anyscale** [comment]
cc @scv119 @rickyyx 
I think it can be 'stable: false' for now. Otherwise, update the test with less pgs?
Then we will follow up with a streaming implementation of gRPC request.

**Comment by rkooo567** [comment]
what's the root cause of this? I am surprised this test has been jailed without me noticing

**Comment by hanming-lu** [comment]
> IF it is the infra issue, I think we should reduce the num pgs until infra issue is fixed, not jailing the test
Agreed. Let's reduce (number of pg * bundle per gp) to O(100) and re-enable this test.

**Comment by brucez-anyscale** [comment]
Could we revisit this issue? I think after we fix the protojson and increase the message size limit. It could pass.
@can-anyscale

**Comment by can-anyscale** [comment]
Sound good! Once the fix is in, you can simply close this issue to unjail the test

Alternatively, you can run this test on that PR that fixes it to confirm first

**Comment by brucez-anyscale** [comment]
I think the fix is in already. Let's manually run that test?

**Comment by can-anyscale** [comment]
Sound good, latest master run: https://buildkite.com/ray-project/release-tests-branch/builds/2181

**Comment by can-anyscale** [comment]
Passing now, closing

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2184#018aa7db-f555-4783-92a2-679ef31ec20f
