### ISSUE TITLE
[core] Ray failed to start

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#38517]
### What happened + What you expected to happen

Get a m5.xlarge, install lastest ray, run script:

```
import ray
ray.init()
```

And it will shows

```
Usage stats collection is disabled.
2023-08-16 20:33:12,045	INFO worker.py:1621 -- Started a local Ray instance.
[2023-08-16 20:33:13,055 E 7368 7368] core_worker.cc:202: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory

```

If we call:
```
ray start --head

```
and then 
```
import ray
ray.init()
```
it'll show:

```
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init()
2023-08-16 20:33:37,016	INFO worker.py:1431 -- Connecting to existing Ray cluster at address: 172.31.29.174:6379...
[2023-08-16 20:33:37,020 W 7602 7602] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-08-16 20:33:38,021 W 7602 7602] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-08-16 20:33:39,021 W 7602 7602] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-08-16 20:33:40,022 W 7602 7602] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-08-16 20:33:41,022 W 7602 7602] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-08-16 20:33:42,023 W 7602 7602] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-08-16 20:33:43,023 W 7602 7602] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-08-16 20:33:44,024 W 7602 7602] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-08-16 20:33:45,024 W 7602 7602] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-08-16 20:33:46,025 W 7602 7602] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 1577, in init
    _global_node = ray._private.node.Node(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ray/_private/node.py", line 239, in __init__
    node_info = ray._private.services.get_node_to_connect_for_driver(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ray/_private/services.py", line 471, in get_node_to_connect_for_driver
    return global_state.get_node_to_connect_for_driver(node_ip_address)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ray/_private/state.py", line 733, in get_node_to_connect_for_driver
    return self.global_state_accessor.get_node_to_connect_for_driver(
  File "python/ray/includes/global_state_accessor.pxi", line 192, in ray._raylet.GlobalStateAccessor.get_node_to_connect_for_driver
    def get_node_to_connect_for_driver(self, node_ip_address):
RuntimeError: b'GCS has started but no raylets have registered yet.'
```

The root cause is:

```
2023-08-16 20:33:35,194	INFO agent.py:118 -- Parent pid is 7565
2023-08-16 20:33:35,195	INFO agent.py:144 -- Dashboard agent grpc address: 0.0.0.0:50748
2023-08-16 20:33:35,196	INFO utils.py:112 -- Get all modules by type: DashboardAgentModule
2023-08-16 20:33:35,197	INFO utils.py:123 -- Module ray.dashboard.modules.actor.actor_head cannot be loaded because we cannot import all dependencies. Install this module using `pip install 'ray[default]'` for the full dashboard functionality. Error: No module named 'aiohttp'
```

### Versions / Dependencies

master

### Reproduction script

see description

### Issue Severity

High: It blocks me from completing my task.

**Comment by iycheng** [comment]
The minimal install should catch this. @rynewang  could you also give that a look?

**Comment by rynewang** [comment]
Not sure what happened but `2023-08-16 20:33:35,197	INFO utils.py:123 -- Module ray.dashboard.modules.actor.actor_head cannot be loaded because we cannot import all dependencies. Install this module using `pip install 'ray[default]'` for the full dashboard functionality. Error: No module named 'aiohttp'` this log seems to be normal in minimal Ray as it is properly caught in `dashboard/utils.py`. Possible we have other root causes?
