### ISSUE TITLE
Add error message when working_dir is more than 100MB

### ISSUE THREAD

**Issue by marho13** [ray-project/ray#38566]
### Description

Hi,
I strongly believe that there needs to be an error message when uploading too large files.
When using the JobSubmissionClient, and setting the working_dir; there should be a check which finds the total size of the working_dir and if it surpasses 100MB simply telling the user that the files are too large...

### Use case

Currently the error the user gets is that there is: "Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2396)')".
If you believe that you are under the 100MB limit, but are not, you are currently getting no information about what is going wrong.

A solution would be something like what is below implemented for the library

import os

def get_size(start_path = '.'):
    total_size = 0
    for dirpath, dirnames, filenames in os.walk(start_path):
        for f in filenames:
            fp = os.path.join(dirpath, f)
            # skip if it is symbolic link
            if not os.path.islink(fp):
                total_size += os.path.getsize(fp)

    return total_size

file_size = get_size()
if file_size > 104857600:
   raise Exception("The files in the working_dir are too large (over 100MB), it will therefore not submit the job")

**Comment by rkooo567** [comment]
cc @architkulkarni  (it is surprising that we don't have an error)?

**Comment by architkulkarni** [comment]
It's surprising. We have an error, but maybe it's not being triggered on the job submission codepath.

**Comment by architkulkarni** [comment]
Pretty easy to reproduce locally, got a slightly different error but the main point is the 100MB limit doesn't appear in the traceback:
```bash
(ray-py38) archit@archit-C02D27V8MD6N ray % ray start --head                              
Usage stats collection is enabled. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.

Local node IP: 127.0.0.1

--------------------
Ray runtime started.
--------------------

Next steps
  
  To connect to this Ray cluster:
    import ray
    ray.init()
  
  To submit a Ray job using the Ray Jobs CLI:
    RAY_ADDRESS='http://127.0.0.1:8265' ray job submit --working-dir . -- python my_script.py
  
  See https://docs.ray.io/en/latest/cluster/running-applications/job-submission/index.html 
  for more information on submitting Ray jobs to the Ray cluster.
  
  To terminate the Ray runtime, run
    ray stop
  
  To view the status of the cluster, use
    ray status
  
  To monitor and debug Ray, view the dashboard at 
    127.0.0.1:8265
  
  If connection to the dashboard fails, check your firewall settings and network configuration.

(ray-py38) archit@archit-C02D27V8MD6N ray % ?? create a directory called garbage with a single file that is 120MB i dont care about the contents  

 ──────────────────── Command ────────────────────

mkdir garbage
dd if=/dev/zero of=garbage/file.txt bs=1M count=120

 ────────────────── Explanation ──────────────────

○ mkdir is used to create a new directory.
○ dd is used to create a file filled with zeros.
  ◆ if=/dev/zero specifies that we want to read from the /dev/zero device which returns an infinite stream of zeros.
  ◆ of=garbage/file.txt specifies that we want to write to the file file.txt in the garbage folder.
  ◆ bs=1M specifies that we want to read and write in chunks of 1MB.
  ◆ count=120 specifies that we want to read and write 120 chunks.

🕕  Hold on, executing commmand...
120+0 records in
120+0 records out
125829120 bytes transferred in 0.051308 secs (2452426912 bytes/sec)
(ray-py38) archit@archit-C02D27V8MD6N ray % ray job submit --working-dir garbage -- echo hello world                          
Job submission server address: http://127.0.0.1:8265
2023-08-21 15:00:33,798 INFO dashboard_sdk.py:338 -- Uploading package gcs://_ray_pkg_7f832d0ede17ec70.zip.
2023-08-21 15:00:33,799 INFO packaging.py:518 -- Creating a file package for local directory 'garbage'.
2023-08-21 15:00:33,799 WARNING packaging.py:393 -- File /Users/archit/ray/garbage/file.txt is very large (120.00MiB). Consider adding this file to the 'excludes' list to skip uploading it: `ray.init(..., runtime_env={'excludes': ['/Users/archit/ray/garbage/file.txt']})`
Traceback (most recent call last):
  File "/Users/archit/anaconda3/envs/ray-py38/bin/ray", line 33, in <module>
    sys.exit(load_entry_point('ray', 'console_scripts', 'ray')())
  File "/Users/archit/ray/python/ray/scripts/scripts.py", line 2478, in main
    return cli()
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/archit/ray/python/ray/dashboard/modules/job/cli_utils.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/Users/archit/ray/python/ray/autoscaler/_private/cli_logger.py", line 856, in wrapper
    return f(*args, **kwargs)
  File "/Users/archit/ray/python/ray/dashboard/modules/job/cli.py", line 257, in submit
    job_id = client.submit_job(
  File "/Users/archit/ray/python/ray/dashboard/modules/job/sdk.py", line 203, in submit_job
    self._upload_working_dir_if_needed(runtime_env)
  File "/Users/archit/ray/python/ray/dashboard/modules/dashboard_sdk.py", line 398, in _upload_working_dir_if_needed
    upload_working_dir_if_needed(runtime_env, upload_fn=_upload_fn)
  File "/Users/archit/ray/python/ray/_private/runtime_env/working_dir.py", line 96, in upload_working_dir_if_needed
    upload_fn(working_dir, excludes=excludes)
  File "/Users/archit/ray/python/ray/dashboard/modules/dashboard_sdk.py", line 391, in _upload_fn
    self._upload_package_if_needed(
  File "/Users/archit/ray/python/ray/dashboard/modules/dashboard_sdk.py", line 377, in _upload_package_if_needed
    self._upload_package(
  File "/Users/archit/ray/python/ray/dashboard/modules/dashboard_sdk.py", line 358, in _upload_package
    self._raise_error(r)
  File "/Users/archit/ray/python/ray/dashboard/modules/dashboard_sdk.py", line 283, in _raise_error
    raise RuntimeError(
RuntimeError: Request failed with status code 500: Traceback (most recent call last):
  File "/Users/archit/ray/python/ray/dashboard/modules/job/job_head.py", line 264, in upload_package
    upload_package_to_gcs(package_uri, await req.read())
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/aiohttp/web_request.py", line 654, in read
    raise HTTPRequestEntityTooLarge(
aiohttp.web_exceptions.HTTPRequestEntityTooLarge: Request Entity Too Large
```

**Comment by marho13** [comment]
Ahh okay, i have been trying to fix this over the summer, and with both ray 2.6.2 and ray 2.5 i had the issue, but i get a different error on 2.6.3, which was just uploaded a week before this post, and as we were using your docker images, with the same image for the server and local image we tested with 2.6.2 last time.

Though getting the actual number is nice, thank you
