### ISSUE TITLE
[Core] Error message in ray.utli.ActorPool.get_next() doesn't support multiple return values

### ISSUE THREAD

**Issue by PRESIDENT810** [ray-project/ray#38607]
### What happened + What you expected to happen

1. The bug:
Reproduce code
```
import ray
from ray.util import ActorPool

ray.init()

@ray.remote
class Foo:
    @ray.method(num_returns=2)
    def some_task(self, x):
        # Simulate some work
        ray.sleep(10)
        return x, 2


actors = [Foo.remote() for _ in range(2)]
pool = ActorPool(actors)

pool.submit(lambda a, v: a.some_task.remote(v), 1)
pool.get_next(timeout=1, ignore_if_timedout=True)

```
This will trigger:
TypeError: wait() expected a list of ray.ObjectRef or ray.StreamingObjectRefGenerator, got list containing <class 'list'>

This is caused by line 299-301 in python/ray/util/actor_pool.py:
```
            raise TimeoutError(
                timeout_msg + ". The task {} has been ignored.".format(future)
            )
```
The future passed here could be a list of ray.ObjectRef instead of a single ray.ObjectRef when using @ray.method(num_return=<number greater than 1>).

2. Expected behavior:
I was expecting it to output multiple ray.ObjectRef's ID

3. Error message:
Traceback (most recent call last):
  File "/Users/zhongkaining/PycharmProjects/pythonProject1/main.py", line 19, in <module>
    pool.get_next(timeout=1, ignore_if_timedout=True)
  File "/usr/local/lib/python3.11/site-packages/ray/util/actor_pool.py", line 283, in get_next
    res, _ = ray.wait([future], timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ray/_private/worker.py", line 2701, in wait
    raise TypeError(
TypeError: wait() expected a list of ray.ObjectRef or ray.StreamingObjectRefGenerator, got list containing <class 'list'>

### Versions / Dependencies

I was using ray version = 2.6.2. I also pulled the source code and this problem still remains in mainline branch.

### Reproduction script

```
import ray
from ray.util import ActorPool

ray.init()

@ray.remote
class Foo:
    @ray.method(num_returns=2)
    def some_task(self, x):
        # Simulate some work
        ray.sleep(10)
        return x, 2


actors = [Foo.remote() for _ in range(2)]
pool = ActorPool(actors)

pool.submit(lambda a, v: a.some_task.remote(v), 1)
pool.get_next(timeout=1, ignore_if_timedout=True)

```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by PRESIDENT810** [comment]
This should be an easy fix. Please assign this to me and I will fix it quickly.

**Comment by rkooo567** [comment]
Yeah @PRESIDENT810 can you make a PR?

**Comment by PRESIDENT810** [comment]
> Yeah @PRESIDENT810 can you make a PR?

Yeah sure, I'm working on it.
