### ISSUE TITLE
Release test golden_notebook_torch_tune_serve_test.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#38636]
Release test **golden_notebook_torch_tune_serve_test.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2055#018a0e30-38b9-4b1f-90eb-5c37944d88e6 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
```
Traceback (most recent call last):
  File "workloads/torch_tune_serve_test.py", line 281, in <module>
    best_checkpoint_path = analysis.get_best_checkpoint(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/tune/analysis/experiment_analysis.py", line 618, in get_best_checkpoint
    checkpoint_paths = self.get_trial_checkpoints_paths(trial, metric)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/tune/analysis/experiment_analysis.py", line 587, in get_trial_checkpoints_paths
    raise ValueError("trial should be a string or a Trial instance.")
ValueError: trial should be a string or a Trial instance.
```

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2061#018a214b-e539-4011-a667-c57baa5bc669
