### ISSUE TITLE
[Core] ray.util.ActorPool's get_next_unordered doesn't work with timeout != None and ignore_if_timedout=True

### ISSUE THREAD

**Issue by PRESIDENT810** [ray-project/ray#38635]
### What happened + What you expected to happen

1. In ray.util.ActorPool, when calling `get_next_unordered` method, if we set a timeout != None, and ignore_if_timedout=True, when ray.wait() doesn't return any finished task, the following code will throw an error:

```
        res, _ = ray.wait(list(self._future_to_actor), num_returns=1, timeout=timeout)
        timeout_msg = "Timed out waiting for result"
        raise_timeout_after_ignore = False
        if res:
            [future] = res
        else:
            if not ignore_if_timedout:
                raise TimeoutError(timeout_msg)
            else:
                raise_timeout_after_ignore = True
        i, a = self._future_to_actor.pop(future)
```
Because there is no finished task, so res will be empty, and future will be undefined. When we try to pop this future from _future_to_actor, an error will occur.

2. Expected behavior
I don't any future should be poped if nothing is finished. I also feel like this ignore_if_timedout parameter is unnecessary. Since we are getting an unordered task's result, we don't have a specific future to ignore here.

3. log
Traceback (most recent call last):
  File "/Users/zhongkaining/PycharmProjects/pythonProject1/main.py", line 39, in <module>
    pool.get_next_unordered(timeout=1, ignore_if_timedout=True)
  File "/usr/local/lib/python3.11/site-packages/ray/util/actor_pool.py", line 353, in get_next_unordered
    i, a = self._future_to_actor.pop(future)
                                     ^^^^^^
UnboundLocalError: cannot access local variable 'future' where it is not associated with a value

### Versions / Dependencies

I'm using ray 2.6.2, but I think the mainline source code also has this bug.

### Reproduction script

```
import ray
import time
from ray.util import ActorPool

ray.init()

@ray.remote
class MyActor:
    def foo(self, x):
        # Simulate some work
        time.sleep(10)
        return x


actors = [MyActor.remote() for _ in range(2)]
pool = ActorPool(actors)

pool.submit(lambda a, v: a.foo.remote(v), 1)
pool.get_next_unordered(timeout=1, ignore_if_timedout=True)
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by functicons** [comment]
It seems that the expected behavior of `ignore_if_timedout` is not well defined when timout happens and there is no result. But I don't think we can simply remove the parameter, as it will be a breaking change. Maybe keep the parameter, but define the behavior expecitly, e.g., returning None?

**Comment by PRESIDENT810** [comment]
> It seems that the expected behavior of `ignore_if_timedout=True` is not well defined when timeout happens and there is no result. But I don't think we can simply remove the parameter, as it will be a breaking change. Maybe keep the parameter, but define the behavior expecitly, e.g., returning None?

Sure, that's more reasonable. I have modified my PR and now ignore_if_timeout=True will ignore the TimeoutError and return None instead. Please take a look and feel free to give feedback!
