### ISSUE TITLE
latest ray microbenchmark fails 

### ISSUE THREAD

**Issue by martystack** [ray-project/ray#38758]
### What happened + What you expected to happen

The microbenchmark does not complete on a fresh install. 

(ray) mstack@taiga-001:~$ ray start --head
Enable usage stats collection? This prompt will auto-proceed in 10 seconds to avoid blocking cluster startup. Confirm [Y/n]: 
Usage stats collection is enabled. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.

Local node IP: 10.33.110.145

--------------------
Ray runtime started.
--------------------

Next steps
  To add another node to this Ray cluster, run
    ray start --address='10.33.110.145:6379'
  
  To connect to this Ray cluster:
    import ray
    ray.init()
  
  To submit a Ray job using the Ray Jobs CLI:
    RAY_ADDRESS='http://127.0.0.1:8265' ray job submit --working-dir . -- python my_script.py
  
  See https://docs.ray.io/en/latest/cluster/running-applications/job-submission/index.html 
  for more information on submitting Ray jobs to the Ray cluster.
  
  To terminate the Ray runtime, run
    ray stop
  
  To view the status of the cluster, use
    ray status
  
  To monitor and debug Ray, view the dashboard at 
    127.0.0.1:8265
  
  If connection to the dashboard fails, check your firewall settings and network configuration.
(ray) mstack@taiga-001:~$ ray status
======== Autoscaler status: 2023-08-22 13:54:41.028968 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_45efa0fb0062f82a1d89e5d9ccc3c27d3cd7283644d25a900d6aa478
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/20.0 CPU
 0B/16.55GiB memory
 0B/8.28GiB object_store_memory

Demands:
 (no resource demands)
(ray) mstack@taiga-001:~$ ray microbenchmark
Tip: set TESTS_TO_RUN='pattern' to run a subset of benchmarks
2023-08-22 13:54:57,840	INFO worker.py:1431 -- Connecting to existing Ray cluster at address: 10.33.110.145:6379...
2023-08-22 13:54:57,846	INFO worker.py:1612 -- Connected to Ray cluster. View the dashboard at 127.0.0.1:8265 
single client get calls (Plasma Store) per second 6802.74 +- 454.36
single client put calls (Plasma Store) per second 2941.14 +- 56.22
multi client put calls (Plasma Store) per second 9197.58 +- 218.93
(raylet) Spilled 2400 MiB, 4 objects, write throughput 2785 MiB/s. Set RAY_verbose_spill_logs=0 to disable this message.
(raylet) Spilled 6400 MiB, 9 objects, write throughput 4697 MiB/s.
single client put gigabytes per second 32.07 +- 2.6
(raylet) Spilled 11200 MiB, 15 objects, write throughput 4587 MiB/s.
single client tasks and get batch per second 9.71 +- 0.63
(raylet) Spilled 16880 MiB, 68 objects, write throughput 2380 MiB/s.
multi client put gigabytes per second 31.42 +- 2.2
single client get object containing 10k refs per second 13.15 +- 0.1
(sm pid=1622181) all_value
single client wait 1k refs per second 4.84 +- 0.03
single client tasks sync per second 451.3 +- 18.72
single client tasks async per second 9677.19 +- 325.79
multi client tasks async per second 16119.8 +- 548.7
1:1 actor calls sync per second 867.33 +- 23.21
1:1 actor calls async per second 6595.38 +- 145.43
1:1 actor calls concurrent per second 2581.24 +- 54.76
1:n actor calls async per second 7275.98 +- 129.12
n:n actor calls async per second 20428.31 +- 436.94
2023-08-22 14:00:40,427	WARNING worker.py:2037 -- WARNING: 86 PYTHON worker processes have been started on node: 45efa0fb0062f82a1d89e5d9ccc3c27d3cd7283644d25a900d6aa478 with address: 10.33.110.145. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).
n:n actor calls with arg async per second 2633.87 +- 26.76
2023-08-22 14:01:09,649	WARNING worker.py:2037 -- WARNING: 126 PYTHON worker processes have been started on node: 45efa0fb0062f82a1d89e5d9ccc3c27d3cd7283644d25a900d6aa478 with address: 10.33.110.145. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).
1:1 async-actor calls sync per second 509.92 +- 14.04
1:1 async-actor calls async per second 1756.59 +- 41.25
1:1 async-actor calls with args async per second 1097.31 +- 48.56
1:n async-actor calls async per second 4966.1 +- 172.15
n:n async-actor calls async per second 12503.4 +- 125.86
2023-08-22 14:03:36,355	INFO worker.py:1431 -- Connecting to existing Ray cluster at address: 10.33.110.145:6379...
Traceback (most recent call last):
  File "/home/mstack/venv/ray/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/mstack/venv/ray/lib/python3.10/site-packages/ray/scripts/scripts.py", line 2474, in main
    return cli()
  File "/home/mstack/venv/ray/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/mstack/venv/ray/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/mstack/venv/ray/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mstack/venv/ray/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mstack/venv/ray/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/mstack/venv/ray/lib/python3.10/site-packages/ray/scripts/scripts.py", line 1822, in microbenchmark
    main()
  File "/home/mstack/venv/ray/lib/python3.10/site-packages/ray/_private/ray_perf.py", line 293, in main
    ray.init(resources={"custom": 100})
  File "/home/mstack/venv/ray/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/mstack/venv/ray/lib/python3.10/site-packages/ray/_private/worker.py", line 1528, in init
    raise ValueError(
ValueError: When connecting to an existing cluster, resources must not be provided.

### Versions / Dependencies

ray, version 2.6.3
Python 3.10.12
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

### Reproduction script

$ray start --head
$ray microbenchmark

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by martystack** [comment]
It also fails on Mac but at a different point for a different reason.

**Comment by jjyao** [comment]
```
(raylet) [2023-08-22 14:38:50,704 E 22974 2742920] (raylet) logging.cc:97: Unhandled exception: N5boost10wrapexceptINS_6system12system_errorEEE. what(): pipe_select_interrupter: Too many open files [system:24]
```

Can you increase the limit via `ulimit`?

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
