### ISSUE TITLE
[Ray Core][GCS FT] ray status after head node restart in FT mode

### ISSUE THREAD

**Issue by llidev** [ray-project/ray#38785]
### What happened + What you expected to happen

I have my local deployment of Ray with GCS in FT mode. Let's assume this is a single node cluster.

After the head node restart from failure, once I submit a new job to the recovered cluster, the `ray status` CLI constantly fails with below error:

```
Traceback (most recent call last):
  File "/miniconda/envs/ray/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/miniconda/envs/ray/lib/python3.10/site-packages/ray/scripts/scripts.py", line 2474, in main
    return cli()
  File "/miniconda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/miniconda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/miniconda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/miniconda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/miniconda/envs/ray/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/miniconda/envs/ray/lib/python3.10/site-packages/ray/scripts/scripts.py", line 1950, in status
    if not ray._raylet.check_health(address):
  File "python/ray/_raylet.pyx", line 2597, in ray._raylet.check_health
ValueError: too many values to unpack (expected 2)
```

### Versions / Dependencies

2.6.3

### Reproduction script

1. create a single node ray cluster with external redis for gcs FT
2. submit a single ray job with long running command such as `sleep 10000`
3. restart the head the node (in a new machine)
4. submit a new job (not sure if this is required)
5. run `ray status`, and you may see the above error

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by anyscalesam** [comment]
Think this should be Core; @rkooo567 what's your best take on priority for this item?

**Comment by rkooo567** [comment]
This seems bad. cc @rickyyx have you seen a similar issue before?

**Comment by rickyyx** [comment]
Looks like the address is wrong: 

https://github.com/ray-project/ray/blob/releases/2.6.3/python/ray/_raylet.pyx#L2597C24-L2597C24

Are there ":" in the ip address?

**Comment by rickyyx** [comment]
@llidev - and if you have a special ray address, wonder what's the value you passed to other commands like ray start/job submission.

**Comment by rkooo567** [comment]
We will close the issue until there's a follow up. We made a speculative fix in the master. Please follow up if you see this issue again.
