### ISSUE TITLE
Release test serve_autoscaling_single_deployment.aws failed

### ISSUE THREAD

**Issue by GeneDer** [ray-project/ray#38992]
Release test **serve_autoscaling_single_deployment.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2079#018a3a04-d7f3-4779-933b-bea3d95a5844 for more details.

**Comment by GeneDer** [comment]
Probably due to this test
```
Traceback (most recent call last):
  File "workloads/autoscaling_single_deployment.py", line 194, in <module>
    main()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "workloads/autoscaling_single_deployment.py", line 157, in main
    http_host = str(serve_client._http_config.host)
AttributeError: 'NoneType' object has no attribute '_http_config'
```
https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_xw6rnphkbgjlbaxuxqtn3fiiq1

**Comment by GeneDer** [comment]
Test passed for last night's build https://buildkite.com/ray-project/release-tests-branch/builds/2091#018a3f4b-2571-4ffa-a912-1dab1f0a3e1a
