### ISSUE TITLE
Ray Tune

### ISSUE THREAD

**Issue by nhaH-luaP** [ray-project/ray#39052]
### What happened + What you expected to happen

I tried running a script as an array of jobs on a cluster of my university, where each job ran an individual ray tune experiment. Since running a single job does not show any signs of problems, i expected the array to work just fine. But more than half of the jobs throw the same error code:

```
2023-08-29 11:06:59,362 INFO worker.py:1621 -- Started a local Ray instance.
[2023-08-29 11:07:31,197 E 10672 10672] core_worker.cc:201: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory
srun: error: gpu-v100-1: task 0: Exited with exit code 1
```

Sometimes, additional errors accure before but do not stop the experiment like:

```
2023-08-29 11:06:57,637 ERROR services.py:1207 -- Failed to start the dashboard
2023-08-29 11:06:57,638 ERROR services.py:1232 -- Error should be written to 'dashboard.log' or 'dashboard.err'. We are printing the last 20 lines for you. See 'https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure' to find where the log file is.
2023-08-29 11:06:57,678 ERROR services.py:1276 --
The last 20 lines of /mnt/stud/home/phahn/dev/output/13_69362/session_2023-08-29_11-06-29_385929_10672/logs/dashboard.log (it contains the error message from the dashboard):
2023-08-29 11:06:50,315 INFO head.py:254 -- Starting dashboard metrics server on port 44227
2023-08-29 11:06:50,381 ERROR head.py:266 -- An exception occurred while starting the metrics server.
Traceback (most recent call last):
  File "/mnt/stud/home/phahn/envs/rayworkerbug/lib64/python3.9/site-packages/ray/dashboard/head.py", line 260, in _setup_metrics
    prometheus_client.start_http_server(
  File "/mnt/stud/home/phahn/envs/rayworkerbug/lib64/python3.9/site-packages/prometheus_client/exposition.py", line 171, in start_wsgi_server
    httpd = make_server(addr, port, app, TmpServer, handler_class=_SilentHandler)
  File "/usr/lib64/python3.9/wsgiref/simple_server.py", line 154, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib64/python3.9/socketserver.py", line 453, in __init__
    self.server_activate()
  File "/usr/lib64/python3.9/socketserver.py", line 475, in server_activate
    self.socket.listen(self.request_queue_size)
OSError: [Errno 98] Address already in use
2023-08-29 11:06:50,504 INFO utils.py:112 -- Get all modules by type: DashboardHeadModule
```

or

```
2023-08-29 11:08:57,857 ERROR services.py:1207 -- Failed to start the dashboard
2023-08-29 11:08:57,857 ERROR services.py:1232 -- Error should be written to 'dashboard.log' or 'dashboard.err'. We are printing the last 20 lines for you. See 'https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure' to find where the log file is.
2023-08-29 11:08:57,914 ERROR services.py:1276 --
The last 20 lines of /mnt/stud/home/phahn/dev/output/14_69363/session_2023-08-29_11-08-26_946147_13668/logs/dashboard.log (it contains the error message from the dashboard):
2023-08-29 11:08:49,604 INFO head.py:254 -- Starting dashboard metrics server on port 44227
2023-08-29 11:08:49,631 ERROR head.py:266 -- An exception occurred while starting the metrics server.
Traceback (most recent call last):
  File "/mnt/stud/home/phahn/envs/rayworkerbug/lib64/python3.9/site-packages/ray/dashboard/head.py", line 260, in _setup_metrics
    prometheus_client.start_http_server(
  File "/mnt/stud/home/phahn/envs/rayworkerbug/lib64/python3.9/site-packages/prometheus_client/exposition.py", line 171, in start_wsgi_server
    httpd = make_server(addr, port, app, TmpServer, handler_class=_SilentHandler)
  File "/usr/lib64/python3.9/wsgiref/simple_server.py", line 154, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib64/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib64/python3.9/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib64/python3.9/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
2023-08-29 11:08:49,676 INFO utils.py:112 -- Get all modules by type: DashboardHeadModule
```

The percentage of runs that end like this vary from 20 up to 80%.

### Versions / Dependencies

Python 3.9.14
ray 2.6.3
OS Rocky Linux 9.1 (Blue Onyx)

more in the requirements.txt file in the repo given below.

### Reproduction script

This should be a minimal example of what i am trying to run:

https://github.com/nhaH-luaP/RayWorkerBug

Any questions with regards to the repo I'm happy to answer.

### Issue Severity

High: It blocks me from completing my task.

**Comment by matthewdeng** [comment]
This looks like a Core issue that happens when trying to start up the Prometheus client server, before any Tune code is ran.

**Comment by nhaH-luaP** [comment]
Will this be fixed in an upcomming patch? Would gladly use Ray in my Thesis:)

**Comment by rkooo567** [comment]
For port issue, it can happen if you use the default option. For robust port allocation, I recommend you to manually set all ports based on https://docs.ray.io/en/master/ray-core/configure.html#ports-configurations. 

For the first issue, it seems like a real issue. But it also looks like env specific. Can you reproduce the issue if you use conda?
