### ISSUE TITLE
[Serve] `asyncio.shield()` doesn't work as expected with Serve cancellation

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#39228]
### What happened + What you expected to happen

I tried running the following app:

```python
# File name: repro.py

import asyncio
from ray import serve
from ray.serve.handle import RayServeHandle


@serve.deployment
class Forwarder:
    def __init__(self, sleeper_handle: RayServeHandle):
        self.sleeper_handle = sleeper_handle

    async def __call__(self):
        try:
            print("Forwarder received request!")
            await (await self.sleeper_handle.remote())

        except asyncio.CancelledError:
            print("Forwarder's request was cancelled!")


@serve.deployment
async def sleeper():

    async def print_and_sleep():
        print("Inside print_and_sleep")
        await asyncio.sleep(3)

    try:
        print("Sleeper received request!")

        # Shield sleep call from cancellation
        await asyncio.shield(print_and_sleep())

        print("Sleeper deployment finished sleeping!")
    except asyncio.CancelledError:
        print("Sleeper was cancelled -- this should not happen!")


app = Forwarder.bind(sleeper.bind())
```

I ran this with `serve run`:

```
serve run repro:app
```

Then I sent a request and killed it before I got a response. I expected the `sleeper` deployment to finish sleeping successfully. However, it gets cancelled:

```
2023-09-01 15:42:55,318	SUCC scripts.py:519 -- Deployed Serve app successfully.
(ServeReplica:default:Forwarder pid=21133) Forwarder received request!
(ServeReplica:default:sleeper pid=21132) Sleeper received request!
(ServeReplica:default:sleeper pid=21132) Inside print_and_sleep
(HTTPProxyActor pid=21126) INFO 2023-09-01 15:43:02,310 http_proxy 10.103.209.171 b5e6782b-68d0-4990-8c79-aaeaa05c8092 / default http_proxy.py:1215 - Client for request b5e6782b-68d0-4990-8c79-aaeaa05c8092 disconnected during execution, cancelling request.
(ServeReplica:default:Forwarder pid=21133) Forwarder's request was cancelled!
(ServeReplica:default:sleeper pid=21132) Sleeper was cancelled -- this should not happen!
(ServeReplica:default:sleeper pid=21132) INFO 2023-09-01 15:43:02,314 sleeper default#sleeper#arFhHJ b5e6782b-68d0-4990-8c79-aaeaa05c8092 / default replica.py:749 - __CALL__ OK 1951.6ms
(ServeReplica:default:Forwarder pid=21133) INFO 2023-09-01 15:43:02,312 Forwarder default#Forwarder#kfCOKl b5e6782b-68d0-4990-8c79-aaeaa05c8092 / default replica.py:749 - __CALL__ OK 1964.6ms 
```

### Versions / Dependencies

Ray on the latest `master`.

### Reproduction script

See the issue description.

### Issue Severity

High: It blocks me from completing my task.

**Comment by shrekris-anyscale** [comment]
@edoakes found in [the asyncio docs](https://docs.python.org/3/library/asyncio-task.html#shielding-from-cancellation) that the caller of `asyncio.shield()` gets canceled, but the callee still executes. That is indeed what I see after modifying `print_and_sleep` a bit:

```python
...
@serve.deployment
async def sleeper():

    async def print_and_sleep():
        print("Inside print_and_sleep")
        await asyncio.sleep(3)
        print("Finished sleeping in print_and_sleep")
...
```

```
2023-09-01 16:39:51,591	SUCC scripts.py:519 -- Deployed Serve app successfully.
(ServeReplica:default:Forwarder pid=35945) Forwarder received request!
(ServeReplica:default:sleeper pid=35944) Sleeper received request!
(ServeReplica:default:sleeper pid=35944) Inside print_and_sleep
(HTTPProxyActor pid=35942) INFO 2023-09-01 16:39:55,853 http_proxy 10.103.209.171 ae40b189-5bdf-4763-b9e7-edc329cd5ae5 / default http_proxy.py:1215 - Client for request ae40b189-5bdf-4763-b9e7-edc329cd5ae5 disconnected during execution, cancelling request.
(ServeReplica:default:Forwarder pid=35945) Forwarder's request was cancelled!
(ServeReplica:default:sleeper pid=35944) INFO 2023-09-01 16:39:55,855 sleeper default#sleeper#hxSgDe ae40b189-5bdf-4763-b9e7-edc329cd5ae5 / default replica.py:749 - __CALL__ OK 488.8ms
(ServeReplica:default:sleeper pid=35944) Sleeper was cancelled -- this should not happen!
(ServeReplica:default:Forwarder pid=35945) INFO 2023-09-01 16:39:55,855 Forwarder default#Forwarder#WVCROE ae40b189-5bdf-4763-b9e7-edc329cd5ae5 / default replica.py:749 - __CALL__ OK 503.9ms
(ServeReplica:default:sleeper pid=35944) Finished sleeping in print_and_sleep
```

**Comment by shrekris-anyscale** [comment]
However, when I pull the `asyncio.shield()` call into the `Forwarder`, I get different exceptions:

```python
# File name: repro.py

import asyncio
from ray import serve
from ray.serve.handle import RayServeHandle


@serve.deployment
class Forwarder:
    def __init__(self, sleeper_handle: RayServeHandle):
        self.sleeper_handle = sleeper_handle

    async def __call__(self):
        try:
            print("Forwarder received request!")
            await asyncio.shield(await asyncio.shield(self.sleeper_handle.remote()))

        except asyncio.CancelledError:
            print("Forwarder's request was cancelled!")


@serve.deployment
async def sleeper():
    print("Sleeper received request!")
    await asyncio.sleep(3)
    print("Sleeper deployment finished sleeping!")


app = Forwarder.bind(sleeper.bind())
```

```
2023-09-01 16:46:13,793	SUCC scripts.py:519 -- Deployed Serve app successfully.
(ServeReplica:default:Forwarder pid=37487) Forwarder received request!
(ServeReplica:default:sleeper pid=37486) Sleeper received request!
(HTTPProxyActor pid=37484) INFO 2023-09-01 16:46:25,156 http_proxy 10.103.209.171 b18870e8-6d7b-4a9b-86f2-632b65dcfd25 / default http_proxy.py:1215 - Client for request b18870e8-6d7b-4a9b-86f2-632b65dcfd25 disconnected during execution, cancelling request.
(ServeReplica:default:Forwarder pid=37487) INFO 2023-09-01 16:46:25,160 Forwarder default#Forwarder#nvWseb b18870e8-6d7b-4a9b-86f2-632b65dcfd25 / default replica.py:749 - __CALL__ OK 772.0ms
(ServeReplica:default:Forwarder pid=37487) Task exception was never retrieved
(ServeReplica:default:Forwarder pid=37487) future: <Task finished name='Task-18' coro=<_wrap_awaitable() done, defined at /Users/shrekris/miniforge3/envs/ae/lib/python3.8/asyncio/tasks.py:688> exception=RayTaskError(TaskCancelledError)(TaskCancelledError(TaskID(5f48c11f63e4213b94f8a4e7d4bece97872eed8001000000)))>
(ServeReplica:default:Forwarder pid=37487) Traceback (most recent call last):
(ServeReplica:default:Forwarder pid=37487)   File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
(ServeReplica:default:Forwarder pid=37487)     return (yield from awaitable.__await__())
(ServeReplica:default:Forwarder pid=37487) ray.exceptions.RayTaskError(TaskCancelledError): ray::ServeReplica:default:sleeper.handle_request() (pid=37486, ip=10.103.209.171, actor_id=94f8a4e7d4bece97872eed8001000000, repr=<ray.serve._private.replica.ServeReplica:default:sleeper object at 0x10fa7cd60>)
(ServeReplica:default:Forwarder pid=37487)     raise CancelledError()
(ServeReplica:default:Forwarder pid=37487) concurrent.futures._base.CancelledError
(ServeReplica:default:Forwarder pid=37487) 
(ServeReplica:default:Forwarder pid=37487) During handling of the above exception, another exception occurred:
(ServeReplica:default:Forwarder pid=37487) 
(ServeReplica:default:Forwarder pid=37487) ray::ServeReplica:default:sleeper.handle_request() (pid=37486, ip=10.103.209.171, actor_id=94f8a4e7d4bece97872eed8001000000, repr=<ray.serve._private.replica.ServeReplica:default:sleeper object at 0x10fa7cd60>)
(ServeReplica:default:Forwarder pid=37487) ray.exceptions.TaskCancelledError: Task: TaskID(5f48c11f63e4213b94f8a4e7d4bece97872eed8001000000) was cancelled.
(ServeReplica:default:Forwarder pid=37487) Forwarder's request was cancelled!
```

I expect to see the `Forwarder` get cancelled (as happens), and the `sleeper` to finish executing (which doesn't happen). The scary-looking logs are unexpected too.

**Comment by shrekris-anyscale** [comment]
Removing either of the `asyncio.shield()` calls don't seem to help either.

If we remove the outer one, the scary-looking logs go away, but the `sleeper` gets canceled:

```python
# File name: repro.py

import asyncio
from ray import serve
from ray.serve.handle import RayServeHandle


@serve.deployment
class Forwarder:
    def __init__(self, sleeper_handle: RayServeHandle):
        self.sleeper_handle = sleeper_handle

    async def __call__(self):
        try:
            print("Forwarder received request!")
            await (await asyncio.shield(self.sleeper_handle.remote()))

        except asyncio.CancelledError:
            print("Forwarder's request was cancelled!")


@serve.deployment
async def sleeper():
    try:
        print("Sleeper received request!")
        await asyncio.sleep(3)
        print("Sleeper deployment finished sleeping!")
    except asyncio.CancelledError:
        print("Sleeper was cancelled.")


app = Forwarder.bind(sleeper.bind())
```

```
2023-09-01 16:50:42,710	SUCC scripts.py:519 -- Deployed Serve app successfully.
(ServeReplica:default:sleeper pid=38636) Sleeper received request!
(ServeReplica:default:Forwarder pid=38637) Forwarder received request!
(HTTPProxyActor pid=38629) INFO 2023-09-01 16:50:55,430 http_proxy 10.103.209.171 0c2c0846-e8ff-4970-a544-90d7b269f8ea / default http_proxy.py:1215 - Client for request 0c2c0846-e8ff-4970-a544-90d7b269f8ea disconnected during execution, cancelling request.
(ServeReplica:default:sleeper pid=38636) INFO 2023-09-01 16:50:55,434 sleeper default#sleeper#kwaprY 0c2c0846-e8ff-4970-a544-90d7b269f8ea / default replica.py:749 - __CALL__ OK 612.0ms
(ServeReplica:default:sleeper pid=38636) Sleeper was cancelled.
(ServeReplica:default:Forwarder pid=38637) Forwarder's request was cancelled!
(ServeReplica:default:Forwarder pid=38637) INFO 2023-09-01 16:50:55,433 Forwarder default#Forwarder#FYoENn 0c2c0846-e8ff-4970-a544-90d7b269f8ea / default replica.py:749 - __CALL__ OK 626.2ms
```

And if we remove the inner one, the `sleeper` gets canceled, and we see the scary-looking logs:

```python
# File name: repro.py

import asyncio
from ray import serve
from ray.serve.handle import RayServeHandle


@serve.deployment
class Forwarder:
    def __init__(self, sleeper_handle: RayServeHandle):
        self.sleeper_handle = sleeper_handle

    async def __call__(self):
        try:
            print("Forwarder received request!")
            await asyncio.shield(await self.sleeper_handle.remote())

        except asyncio.CancelledError:
            print("Forwarder's request was cancelled!")


@serve.deployment
async def sleeper():
    try:
        print("Sleeper received request!")
        await asyncio.sleep(3)
        print("Sleeper deployment finished sleeping!")
    except asyncio.CancelledError:
        print("Sleeper was cancelled.")


app = Forwarder.bind(sleeper.bind())
```

```
2023-09-01 16:51:43,705	SUCC scripts.py:519 -- Deployed Serve app successfully.
(ServeReplica:default:Forwarder pid=38923) Forwarder received request!
(ServeReplica:default:sleeper pid=38922) Sleeper received request!
(HTTPProxyActor pid=38913) INFO 2023-09-01 16:51:46,012 http_proxy 10.103.209.171 224a08dc-50ab-408f-bb4b-39cf8ed9c97d / default http_proxy.py:1215 - Client for request 224a08dc-50ab-408f-bb4b-39cf8ed9c97d disconnected during execution, cancelling request.
(ServeReplica:default:Forwarder pid=38923) Forwarder's request was cancelled!
(ServeReplica:default:Forwarder pid=38923) INFO 2023-09-01 16:51:46,014 Forwarder default#Forwarder#iohgyd 224a08dc-50ab-408f-bb4b-39cf8ed9c97d / default replica.py:749 - __CALL__ OK 532.0ms
(ServeReplica:default:sleeper pid=38922) Sleeper was cancelled.
(ServeReplica:default:sleeper pid=38922) INFO 2023-09-01 16:51:46,015 sleeper default#sleeper#uLxpNQ 224a08dc-50ab-408f-bb4b-39cf8ed9c97d / default replica.py:749 - __CALL__ OK 516.8ms
(ServeReplica:default:Forwarder pid=38923) Task exception was never retrieved
(ServeReplica:default:Forwarder pid=38923) future: <Task finished name='Task-17' coro=<_wrap_awaitable() done, defined at /Users/shrekris/miniforge3/envs/ae/lib/python3.8/asyncio/tasks.py:688> exception=RayTaskError(TaskCancelledError)(TaskCancelledError(TaskID(33aa54f9afa77becc15688d94cbcf495a8b3959901000000)))>
(ServeReplica:default:Forwarder pid=38923) Traceback (most recent call last):
(ServeReplica:default:Forwarder pid=38923)   File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
(ServeReplica:default:Forwarder pid=38923)     return (yield from awaitable.__await__())
(ServeReplica:default:Forwarder pid=38923) ray.exceptions.RayTaskError(TaskCancelledError): ray::ServeReplica:default:sleeper.handle_request() (pid=38922, ip=10.103.209.171, actor_id=c15688d94cbcf495a8b3959901000000, repr=<ray.serve._private.replica.ServeReplica:default:sleeper object at 0x1175e5d00>)
(ServeReplica:default:Forwarder pid=38923)     raise CancelledError()
(ServeReplica:default:Forwarder pid=38923) concurrent.futures._base.CancelledError
(ServeReplica:default:Forwarder pid=38923) 
(ServeReplica:default:Forwarder pid=38923) During handling of the above exception, another exception occurred:
(ServeReplica:default:Forwarder pid=38923) 
(ServeReplica:default:Forwarder pid=38923) ray::ServeReplica:default:sleeper.handle_request() (pid=38922, ip=10.103.209.171, actor_id=c15688d94cbcf495a8b3959901000000, repr=<ray.serve._private.replica.ServeReplica:default:sleeper object at 0x1175e5d00>)
(ServeReplica:default:Forwarder pid=38923) ray.exceptions.TaskCancelledError: Task: TaskID(33aa54f9afa77becc15688d94cbcf495a8b3959901000000) was cancelled.
```
