### ISSUE TITLE
[Core] Release candidate 2.7.0rc0 Failed Sanity Check on Windows

### ISSUE THREAD

**Issue by GeneDer** [ray-project/ray#39236]
When running the sanity check script on Windows for the latest release candidate `2.7.0rc0`, it consistently fails. Same instance was able to run successfully on `2.3.0rc0` and `2.6.3` so setup should be correct. 

Sanity check commands:
```
# 2.3.0rc0 succeeding for everything before 3.11
RAY_HASH=47a077655b2efaf4c561fdc70a071c02f854cec1 RAY_VERSION=2.3.0rc0 ./pip_download_test.sh

# 2.6.3 all succeeded
RAY_HASH=8a434b4ee7cd48e60fa1531315d39901fac5d79e RAY_VERSION=2.6.3 ./pip_download_test.sh

# 2.7.0rc0 failed
RAY_HASH=f3787df957ca456ae75f19b3307c102838ec6986 RAY_VERSION=2.7.0rc0 ./pip_download_test.sh
```

Failure logs:
```
Administrator@EC2AMAZ-OALT912 MINGW64 ~/ray/release/util (releases/2.7.0rc0)
$ RAY_HASH=f3787df957ca456ae75f19b3307c102838ec6986 RAY_VERSION=2.7.0rc0 ./pip_download_test.sh
conda exists
Start downloading Ray version 2.7.0rc0 of commit f3787df957ca456ae75f19b3307c102838ec6986
Requirement already satisfied: pip in c:\tools\anaconda3\lib\site-packages (23.2.1)
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.1.0
  latest version: 23.7.3

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.7.3



## Package Plan ##

  environment location: C:\tools\Anaconda3\envs\2.7.0rc0-3.7-env

  added / updated specs:
    - python=3.7


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2023.05.30-haa95532_0
  certifi            pkgs/main/win-64::certifi-2022.12.7-py37haa95532_0
  openssl            pkgs/main/win-64::openssl-1.1.1v-h2bbff1b_0
  pip                pkgs/main/win-64::pip-22.3.1-py37haa95532_0
  python             pkgs/main/win-64::python-3.7.16-h6244533_0
  setuptools         pkgs/main/win-64::setuptools-65.6.3-py37haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.41.2-h2bbff1b_0
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
  wheel              pkgs/main/win-64::wheel-0.38.4-py37haa95532_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37haa95532_2



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate 2.7.0rc0-3.7-env
#
# To deactivate an active environment, use
#
#     $ conda deactivate




=========================================================
Python version.
Python 3.7.16
This should be equal to 3.7
=========================================================



Looking in indexes: https://test.pypi.org/simple/, https://pypi.org/simple
Collecting ray[cpp]==2.7.0rc0
  Using cached ray-2.7.0rc0-cp37-cp37m-win_amd64.whl (24.1 MB)
Collecting aiosignal
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting msgpack<2.0.0,>=1.0.0
  Using cached msgpack-1.0.5-cp37-cp37m-win_amd64.whl (62 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Collecting filelock
  Using cached filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting click>=7.0
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting protobuf!=3.19.5,>=3.15.3
  Using cached protobuf-4.24.2-cp37-cp37m-win_amd64.whl (429 kB)
Collecting numpy>=1.16
  Using cached numpy-1.21.6-cp37-cp37m-win_amd64.whl (14.0 MB)
Collecting pyyaml
  Using cached PyYAML-6.0.1-cp37-cp37m-win_amd64.whl (153 kB)
Collecting frozenlist
  Using cached frozenlist-1.3.3-cp37-cp37m-win_amd64.whl (34 kB)
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting jsonschema
  Using cached jsonschema-4.17.3-py3-none-any.whl (90 kB)
Collecting packaging
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting ray-cpp==2.7.0rc0
  Using cached ray_cpp-2.7.0rc0-cp37-cp37m-win_amd64.whl (20.6 MB)
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting importlib-metadata
  Using cached importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Using cached pyrsistent-0.19.3-cp37-cp37m-win_amd64.whl (62 kB)
Collecting pkgutil-resolve-name>=1.3.10
  Using cached pkgutil_resolve_name-1.3.10-py3-none-any.whl (4.7 kB)
Collecting importlib-resources>=1.4.0
  Using cached importlib_resources-5.12.0-py3-none-any.whl (36 kB)
Collecting attrs>=17.4.0
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\tools\anaconda3\envs\2.7.0rc0-3.7-env\lib\site-packages (from requests->ray[cpp]==2.7.0rc0) (2022.12.7)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.2.0-cp37-cp37m-win_amd64.whl (94 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.0.4-py3-none-any.whl (123 kB)
Collecting zipp>=3.1.0
  Using cached zipp-3.15.0-py3-none-any.whl (6.8 kB)
Installing collected packages: ray-cpp, msgpack, zipp, urllib3, typing-extensions, pyyaml, pyrsistent, protobuf, pkgutil-resolve-name, packaging, numpy, idna, frozenlist, filelock, colorama, charset-normalizer, requests, importlib-resources, importlib-metadata, aiosignal, click, attrs, jsonschema, ray
Successfully installed aiosignal-1.3.1 attrs-23.1.0 charset-normalizer-3.2.0 click-8.1.7 colorama-0.4.6 filelock-3.12.2 frozenlist-1.3.3 idna-3.4 importlib-metadata-6.7.0 importlib-resources-5.12.0 jsonschema-4.17.3 msgpack-1.0.5 numpy-1.21.6 packaging-23.1 pkgutil-resolve-name-1.3.10 protobuf-4.24.2 pyrsistent-0.19.3 pyyaml-6.0.1 ray-2.7.0rc0 ray-cpp-2.7.0rc0 requests-2.31.0 typing-extensions-4.7.1 urllib3-2.0.4 zipp-3.15.0



=========================================================
Sanity check python version: 3.7.16 (default, Jan 17 2023, 16:06:28) [MSC v.1916 64 bit (AMD64)]
2023-09-02 23:43:36,146 INFO worker.py:1649 -- Started a local Ray instance.
[2023-09-02 23:43:37,572 E 3728 4600] core_worker.cc:203: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. Unknown error

```

AWS Account: 029272617770 (anyscale-dev-ossci)
EC2 instance: i-07e345ef63f3c7be9
Let me know if you need to get the passward to log into this instance for debugging

**Comment by scv119** [comment]
```
2023-09-06 12:41:20,073 INFO agent.py:153 -- Loaded 0 modules.
2023-09-06 12:41:20,075 ERROR agent.py:434 -- Agent is working abnormally. It will exit immediately.
Traceback (most recent call last):
  File "C:\Users\chenshen\miniconda3\envs\2.7.0rc0-3.7-env\lib\site-packages\ray\dashboard\agent.py", line 432, in <module>
    loop.run_until_complete(agent.run())
  File "C:\Users\chenshen\miniconda3\envs\2.7.0rc0-3.7-env\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\chenshen\miniconda3\envs\2.7.0rc0-3.7-env\lib\site-packages\ray\dashboard\agent.py", line 221, in run
    await self.server.wait_for_termination()
AttributeError: 'NoneType' object has no attribute 'wait_for_termination'
```
