### ISSUE TITLE
[autoscaler] GCP node provider fails due to out-of-sync label fingerprint

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#3930]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: Source @ https://github.com/ray-project/ray/commit/0f81bc9a33d02085311b5b04f07cf91323a8c362
- **Ray version**: 0.6.2 @ 0f81bc9a33d02085311b5b04f07cf91323a8c362
- **Python version**: 3.6
- **Exact command to reproduce**: `ray exec ${RAY_PATH}/python/ray/autoscaler/gcp/example-minimal.yaml "echo test" --start`

### Describe the problem
GCP autoscaler fails due to fingerprint mismatch when trying to update labels. The issue was introduced somewhere in #3720, as reverting those commits solves the problem.

### Source code / logs
```
$ ray exec ~/github/hartikainen/ray/python/ray/autoscaler/gcp/example-minimal.yaml "echo test" --start
/home/kristian/conda/envs/softlearning/lib/python3.6/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
/home/kristian/conda/envs/softlearning/lib/python3.6/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
/home/kristian/conda/envs/softlearning/lib/python3.6/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
2019-02-01 20:38:16,355 INFO config.py:266 -- _configure_key_pair: Private key not specified in config, using/home/kristian/.ssh/ray-autoscaler_gcp_us-west1_tuomas-softlearning_ubuntu.pem
/home/kristian/conda/envs/softlearning/lib/python3.6/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
/home/kristian/conda/envs/softlearning/lib/python3.6/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
2019-02-01 20:38:18,342 INFO commands.py:172 -- get_or_create_head_node: Launching new head node...
2019-02-01 20:38:20,450 INFO node_provider.py:25 -- wait_for_compute_zone_operation: Waiting for operation operation-1549082298374-580e1d41f58d0-547b4816-53b87b87 to finish...
2019-02-01 20:38:31,137 INFO node_provider.py:36 -- wait_for_compute_zone_operation: Operation operation-1549082298374-580e1d41f58d0-547b4816-53b87b87 finished.
2019-02-01 20:38:31,324 INFO commands.py:185 -- get_or_create_head_node: Updating files on head node...
2019-02-01 20:38:31,327 INFO updater.py:126 -- NodeUpdater: ray-minimal-head-94f80e8f: Updating to b544ca2ef7a259ce41c2bcff0e5b6be17ffb8aff
2019-02-01 20:38:31,947 INFO node_provider.py:25 -- wait_for_compute_zone_operation: Waiting for operation operation-1549082311362-580e1d4e587c6-fb14b8d2-d5967893 to finish...
2019-02-01 20:38:37,412 INFO node_provider.py:36 -- wait_for_compute_zone_operation: Operation operation-1549082311362-580e1d4e587c6-fb14b8d2-d5967893 finished.
2019-02-01 20:38:37,413 INFO updater.py:88 -- NodeUpdater: Waiting for IP of ray-minimal-head-94f80e8f...
2019-02-01 20:38:37,413 INFO log_timer.py:21 -- NodeUpdater: ray-minimal-head-94f80e8f: Got IP [LogTimer=0ms]
2019-02-01 20:38:37,459 INFO updater.py:153 -- NodeUpdater: ray-minimal-head-94f80e8f: Waiting for SSH...
2019-02-01 20:38:58,302 INFO log_timer.py:21 -- NodeUpdater: ray-minimal-head-94f80e8f: Got SSH [LogTimer=20842ms]
2019-02-01 20:38:59,019 INFO node_provider.py:25 -- wait_for_compute_zone_operation: Waiting for operation operation-1549082338321-580e1d680e4cb-17de11cd-7fd35025 to finish...
2019-02-01 20:39:04,540 INFO log_timer.py:21 -- NodeUpdater: ray-minimal-head-94f80e8f: Applied config b544ca2ef7a259ce41c2bcff0e5b6be17ffb8aff [LogTimer=33196ms]
2019-02-01 20:39:04,540 ERROR updater.py:138 -- NodeUpdater: ray-minimal-head-94f80e8f: Error updating {'errors': [{'code': 'CONDITION_NOT_MET', 'message': 'Labels fingerprint either invalid or resource labels have changed'}]}
2019-02-01 20:39:05,159 INFO node_provider.py:25 -- wait_for_compute_zone_operation: Waiting for operation operation-1549082344561-580e1d6e01b15-fcda49ca-091061e8 to finish...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/kristian/github/hartikainen/ray/python/ray/autoscaler/updater.py", line 130, in run
    self.do_update()
  File "/home/kristian/github/hartikainen/ray/python/ray/autoscaler/updater.py", line 192, in do_update
    {TAG_RAY_NODE_STATUS: "syncing-files"})
  File "/home/kristian/github/hartikainen/ray/python/ray/autoscaler/gcp/node_provider.py", line 128, in set_node_tags
    operation, availability_zone)
  File "/home/kristian/github/hartikainen/ray/python/ray/autoscaler/gcp/node_provider.py", line 32, in wait_for_compute_zone_operation
    raise Exception(result["error"])
Exception: {'errors': [{'code': 'CONDITION_NOT_MET', 'message': 'Labels fingerprint either invalid or resource labels have changed'}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kristian/conda/envs/softlearning/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/kristian/github/hartikainen/ray/python/ray/autoscaler/updater.py", line 140, in run
    {TAG_RAY_NODE_STATUS: "update-failed"})
  File "/home/kristian/github/hartikainen/ray/python/ray/autoscaler/gcp/node_provider.py", line 128, in set_node_tags
    operation, availability_zone)
  File "/home/kristian/github/hartikainen/ray/python/ray/autoscaler/gcp/node_provider.py", line 32, in wait_for_compute_zone_operation
    raise Exception(result["error"])
Exception: {'errors': [{'code': 'CONDITION_NOT_MET', 'message': 'Labels fingerprint either invalid or resource labels have changed'}]}

2019-02-01 20:39:10,790 ERROR commands.py:238 -- get_or_create_head_node: Updating 35.230.50.254 failed
```

**Comment by ericl** [comment]
Maybe this is due to the switch from processes to threads for updaters? I don't think the label handling code has changed for GCE.

Cc @ls-daniel

**Comment by hartikainen** [comment]
The change to threads sounds like a reasonable explanation for this. I'll try to find some time to fix this today.

**Comment by ericl** [comment]
One option is to revert back to processes for GCE, though in principle threads are supposed to improve the perf.

**Comment by hartikainen** [comment]
I think it would be preferable to use threads also for GCE. I'll see if there's an easy way to get it working.
