### ISSUE TITLE
[RLLib] ParallelPettingZooEnv wrapper fails rllib.utils.check_env()

### ISSUE THREAD

**Issue by chrisyeh96** [ray-project/ray#39453]
### What happened + What you expected to happen

I would expect that using RLLib's own [`ParallelPettingZooEnv`](https://github.com/ray-project/ray/blob/212cd04fc68c75dc5c48c46643a9ab6cc55fd842/rllib/env/wrappers/pettingzoo_env.py) wrapper around a PettingZoo `ParallelEnv` would pass RLLib's own [`check_env()`](https://github.com/ray-project/ray/blob/212cd04fc68c75dc5c48c46643a9ab6cc55fd842/rllib/utils/pre_checks/env.py#L31) test. However, this is not the case. See the simple reproduction script below. The error output is copied below.

<details>
<summary>Error output</summary>

```
2023-09-08 08:35:40,708	WARNING multi_agent_env.py:274 -- observation_space_sample() of <ParallelPettingZooEnv instance> has not been implemented. You can either implement it yourself or bring the observation space into the preferred format of a mapping from agent ids to their individual observation spaces. 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ray/rllib/utils/pre_checks/env.py](https://localhost:8080/#) in check_env(env, config)
     80         if isinstance(env, MultiAgentEnv):
---> 81             check_multiagent_environments(env)
     82         elif isinstance(env, VectorEnv):

3 frames
ValueError: The element returned by reset() has agent_ids that are not the names of the agents in the env. 
Agent_ids in this MultiAgentDict: ['player_0', 'player_1']
Agent_ids in this env:[]. You likely need to add the private attribute `_agent_ids` to your env, which is a set containing the ids of agents supported by your env.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ray/rllib/utils/pre_checks/env.py](https://localhost:8080/#) in check_env(env, config)
     94     except Exception:
     95         actual_error = traceback.format_exc()
---> 96         raise ValueError(
     97             f"{actual_error}\n"
     98             "The above error has been found in your environment! "

ValueError: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/utils/pre_checks/env.py", line 81, in check_env
    check_multiagent_environments(env)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/utils/pre_checks/env.py", line 320, in check_multiagent_environments
    _check_if_element_multi_agent_dict(env, reset_obs, "reset()")
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/utils/pre_checks/env.py", line 785, in _check_if_element_multi_agent_dict
    raise ValueError(error)
ValueError: The element returned by reset() has agent_ids that are not the names of the agents in the env. 
Agent_ids in this MultiAgentDict: ['player_0', 'player_1']
Agent_ids in this env:[]. You likely need to add the private attribute `_agent_ids` to your env, which is a set containing the ids of agents supported by your env.

The above error has been found in your environment! We've added a module for checking your custom environments. It may cause your experiment to fail if your environment is not set up correctly. You can disable this behavior via calling `config.environment(disable_env_checking=True)`. You can run the environment checking module standalone by calling ray.rllib.utils.check_env([your env]).
```

</details>

## Root Issue

The root issue for this error is that RLLib's `ParallelPettingZooEnv` wrapper does not adopt the so-called "preferred format" in RLLib's own [`MultiAgentEnv`](https://github.com/ray-project/ray/blob/master/rllib/env/multi_agent_env.py) API

https://github.com/ray-project/ray/blob/212cd04fc68c75dc5c48c46643a9ab6cc55fd842/rllib/env/wrappers/pettingzoo_env.py#L89-L114

## Recommendations

1. Update the `ParallelPettingZooEnv` wrapper to use the preferred format.

2. Add a unit test in [test_pettingzoo_env.py](https://github.com/ray-project/ray/blob/master/rllib/tests/test_pettingzoo_env.py) to ensure that a wrapped PettingZoo passes RLLib's own `check_env()` function.

## Why this is important

As a creator of various multi-agent RL environments following the PettingZoo API, I would love to be able to use RLLib's `check_env()` function as a unit test / sanity check for my own environment to ensure that users can train RLLib algorithms on my environment. Ideally, I'd like the following to work:

Implementing a new multi-agent RL environment:
```python
from pettingzoo.utils.env import ParallelEnv

class MyEnv(ParallelEnv):
    ...
```

Unit test
```python
import unittest

from ray.rllib.env.wrappers.pettingzoo_env import ParallelPettingZooEnv
import ray.rllib.utils

class TestMyEnv(unittest.TestCase):
    def test_rllib_check_env(self):
        env = MyEnv()
        rllib_env = ParallelPettingZooEnv(env)
        ray.rllib.utils.check_env(rllib_env)
```

### Versions / Dependencies

ray[rllib]==2.6.3
pettingzoo==1.22.3  (this is the latest version of pettingzoo that ray[rllib]==2.6.3 is compatible with)

### Reproduction script

Run the following in any Jupyter notebook or Google Colab notebook:

```python
!pip install "ray[rllib]==2.6.3" pettingzoo[classic]

from pettingzoo.classic import rps_v2
from ray.rllib.env.wrappers.pettingzoo_env import ParallelPettingZooEnv
import ray.rllib.utils

env = rps_v2.parallel_env(render_mode="human")
rllib_env = ParallelPettingZooEnv(env)
ray.rllib.utils.check_env(rllib_env)
```

### Issue Severity

None

**Comment by sven1977** [comment]
PR in review. Thanks for raising this issue @chrisyeh96 ! :)
