### ISSUE TITLE
[tune] Error running trial: CUDA error: out of memory

### ISSUE THREAD

**Issue by Spandan-Madan** [ray-project/ray#3947]
I ran the script with access to 2 GPUs each of 12GB, and the script itself was taking about 2.5GB, but I still got this error. Can someone please help debug?

```
2019-02-04 15:12:00,835	ERROR function_runner.py:83 -- Runner Thread raised error.
Traceback (most recent call last):
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/ray/tune/function_runner.py", line 80, in run
    self._entrypoint(*self._entrypoint_args)
  File "mnist_pytorch.py", line 298, in <lambda>
    lambda cfg, rprtr: train_mnist(args, cfg, rprtr))
  File "mnist_pytorch.py", line 279, in train_mnist
    test()
  File "mnist_pytorch.py", line 243, in test
    outputs = model(input_var)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/graphics/toyota-pytorch/training-scaffold_new/unet/runs/2019-01-30_2FACO2ZU/pspnet_model.py", line 90, in forward
    x = self.layer3(x)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/torchvision/models/resnet.py", line 84, in forward
    out = self.conv3(out)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/ray/tune/function_runner.py", line 84, in run
    raise e
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/ray/tune/function_runner.py", line 80, in run
    self._entrypoint(*self._entrypoint_args)
  File "mnist_pytorch.py", line 298, in <lambda>
    lambda cfg, rprtr: train_mnist(args, cfg, rprtr))
  File "mnist_pytorch.py", line 279, in train_mnist
    test()
  File "mnist_pytorch.py", line 243, in test
    outputs = model(input_var)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/graphics/toyota-pytorch/training-scaffold_new/unet/runs/2019-01-30_2FACO2ZU/pspnet_model.py", line 90, in forward
    x = self.layer3(x)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/torchvision/models/resnet.py", line 84, in forward
    out = self.conv3(out)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

2019-02-04 15:12:01,455	ERROR trial_runner.py:412 -- Error processing event.
Traceback (most recent call last):
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 378, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 228, in fetch_result
    result = ray.get(trial_future[0])
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/ray/worker.py", line 2211, in get
    raise value
ray.worker.RayTaskError: ray_worker (pid=30628, host=thousandeyes)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/ray/tune/trainable.py", line 151, in train
    result = self._train()
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/ray/tune/function_runner.py", line 122, in _train
    result = self._status_reporter._get_and_clear_status()
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/torch_tens/lib/python3.6/site-packages/ray/tune/function_runner.py", line 47, in _get_and_clear_status
    raise TuneError("Error running trial: " + str(self._error))
ray.tune.error.TuneError: Error running trial: CUDA error: out of memory

== Status ==
Using AsyncHyperBand: num_stopped=0
Bracket: Iter 180.000: None | Iter 60.000: None | Iter 20.000: None
Bracket: Iter 180.000: None | Iter 60.000: None
Bracket: Iter 180.000: None
Resources requested: 0/12 CPUs, 0/2 GPUs
Memory usage on this node: 32.2/67.5 GB
Result logdir: /afs/csail.mit.edu/u/s/smadan/ray_results/exp
ERROR trials:
 - train_mnist_0_lr=0.02582,momentum=0.22039:	ERROR, 1 failures: /afs/csail.mit.edu/u/s/smadan/ray_results/exp/train_mnist_0_lr=0.02582,momentum=0.22039_2019-02-04_14-43-52y8vfjp8z/error_2019-02-04_14-51-00.txt
 - train_mnist_1_lr=0.056926,momentum=0.51918:	ERROR, 1 failures: /afs/csail.mit.edu/u/s/smadan/ray_results/exp/train_mnist_1_lr=0.056926,momentum=0.51918_2019-02-04_14-51-000o4yo8gk/error_2019-02-04_14-58-01.txt
 - train_mnist_2_lr=0.023527,momentum=0.32848:	ERROR, 1 failures: /afs/csail.mit.edu/u/s/smadan/ray_results/exp/train_mnist_2_lr=0.023527,momentum=0.32848_2019-02-04_14-58-0284_a3oon/error_2019-02-04_15-05-03.txt
 - train_mnist_3_lr=0.019479,momentum=0.35535:	ERROR, 1 failures: /afs/csail.mit.edu/u/s/smadan/ray_results/exp/train_mnist_3_lr=0.019479,momentum=0.35535_2019-02-04_15-05-03phsaa9_i/error_2019-02-04_15-12-01.txt
```

Any clues what is happening?

**Comment by richardliaw** [comment]
Can you post your training script and check nvidia-smi?

Thanks,
Richard

**Comment by Spandan-Madan** [comment]
nvidia-smi showed about 2.5GB in use when it happened.

Here's the train code- 


```
# Original Code here:
# https://github.com/pytorch/examples/blob/master/mnist/main.py
from __future__ import print_function
from __future__ import print_function, division

import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable
import pickle
import torch
import sys
sys.path.append('../../res/')
#from loader.loader import get_loader
from synthetic_loader import ImageFolder
from model.model import get_model
from optimizer.optimizer import get_optimizer
#from loss.loss import get_loss
import torch
import torch.nn as nn
import torch.optim as optim
from torch.autograd import Variable
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time
import copy
import os
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
import pickle
import sys
from PIL import Image
import torch.nn.functional as F
import pspnet_model

# In[25]:





# In[ ]:


from config_file import *

# Training settings
parser = argparse.ArgumentParser(description='PyTorch MNIST Example')
parser.add_argument(
    '--batch-size',
    type=int,
    default=64,
    metavar='N',
    help='input batch size for training (default: 64)')
parser.add_argument(
    '--test-batch-size',
    type=int,
    default=1000,
    metavar='N',
    help='input batch size for testing (default: 1000)')
parser.add_argument(
    '--epochs',
    type=int,
    default=10,
    metavar='N',
    help='number of epochs to train (default: 10)')
parser.add_argument(
    '--lr',
    type=float,
    default=0.01,
    metavar='LR',
    help='learning rate (default: 0.01)')
parser.add_argument(
    '--momentum',
    type=float,
    default=0.5,
    metavar='M',
    help='SGD momentum (default: 0.5)')
parser.add_argument(
    '--no-cuda',
    action='store_true',
    default=False,
    help='disables CUDA training')
parser.add_argument(
    '--seed',
    type=int,
    default=1,
    metavar='S',
    help='random seed (default: 1)')
parser.add_argument(
    '--smoke-test', action="store_true", help="Finish quickly for testing")




data_transforms = {
    'train': transforms.Compose([
        transforms.Resize(IN_SIZE),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
    'val': transforms.Compose([
        transforms.Resize(IN_SIZE),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
   ])
}

label_transforms = {
    'train': transforms.Compose([
        transforms.Resize(IN_SIZE),
        transforms.ToTensor()
    ]),
    'val': transforms.Compose([
        transforms.Resize(IN_SIZE),
        transforms.ToTensor()
   ])
}

#loader = get_loader(DATASET_NAME)
loader = ImageFolder

class Net(nn.Module):
        def __init__(self):
            super(Net, self).__init__()
            self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
            self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
            self.conv2_drop = nn.Dropout2d()
            self.fc1 = nn.Linear(320, 50)
            self.fc2 = nn.Linear(50, 10)

        def forward(self, x):
            x = F.relu(F.max_pool2d(self.conv1(x), 2))
            x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
            x = x.view(-1, 320)
            x = F.relu(self.fc1(x))
            x = F.dropout(x, training=self.training)
            x = self.fc2(x)
            return F.log_softmax(x, dim=1)


def train_mnist(args, config, reporter):
    vars(args).update(config)
    args.cuda = not args.no_cuda and torch.cuda.is_available()

    torch.manual_seed(args.seed)
    if args.cuda:
        torch.cuda.manual_seed(args.seed)

    kwargs = {'num_workers': 1, 'pin_memory': True} if args.cuda else {}
    
    dset_train = loader(TRAIN_DIR, data_transforms['train'],target_transform=label_transforms['train'])
    dset_val = loader(VAL_DIR, data_transforms['val'],target_transform=label_transforms['val'])

    train_loader = torch.utils.data.DataLoader(dset_train, batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
    val_loader = torch.utils.data.DataLoader(dset_val, batch_size=BATCH_SIZE, shuffle=True, num_workers=2)

    
#     train_loader = loader(TRAIN_DIR, data_transforms['train'],target_transform=label_transforms['train'])
#     val_loader = loader(VAL_DIR, data_transforms['val'],target_transform=label_transforms['val'])

#     train_loader = torch.utils.data.DataLoader(
#         datasets.MNIST(
#             '~/data',
#             train=True,
#             download=False,
#             transform=transforms.Compose([
#                 transforms.ToTensor(),
#                 transforms.Normalize((0.1307, ), (0.3081, ))
#             ])),
#         batch_size=args.batch_size,
#         shuffle=True,
#         **kwargs)
#     test_loader = torch.utils.data.DataLoader(
#         datasets.MNIST(
#             '~/data',
#             train=False,
#             transform=transforms.Compose([
#                 transforms.ToTensor(),
#                 transforms.Normalize((0.1307, ), (0.3081, ))
#             ])),
#         batch_size=args.test_batch_size,
#         shuffle=True,
#         **kwargs)

    model = pspnet_model.PSPNet(num_classes=2,pretrained=False,use_aux=False)

#     model = Net()


    if args.cuda:
        model.cuda()

    optimizer = optim.SGD(
        model.parameters(), lr=args.lr, momentum=args.momentum)
    
    #segmentation_loss = get_loss(LOSS)
    segmentation_loss = nn.CrossEntropyLoss()
    if args.cuda:
        segmentation_loss.cuda() 
    def train(epoch):
        model.train()
        for batch_idx, (data, target) in enumerate(train_loader):
#             inputs, labels = data
                #input_var, label_var = transform_inputs_labels_dtype(inputs,labels,LOSS,GPU_MODE)
            resized_in = data[:,:,:,:224]
            resized_labels = target[:,:,:224]
            if args.cuda:
                input_var = Variable(resized_in.float().cuda())                             
                label_var = Variable(resized_labels.long().cuda())               
            outputs = model(input_var)              
            #print(outputs.size())
            #print(label_var.size())
            loss = segmentation_loss(outputs,label_var)
            #print(loss)    
            
#             if args.cuda:
#                 data, target = data.cuda(), target.cuda()
            #data, target = Variable(data), Variable(target)
            optimizer.zero_grad()
            #output = model(data)
            #loss = segmentation_loss(output, target)
            loss.backward()
            optimizer.step()

    def test():
        model.eval()
        total_loss = 0
        for data,target in val_loader:
            
#             inputs, labels = data
                #input_var, label_var = transform_inputs_labels_dtype(inputs,labels,LOSS,GPU_MODE)
            resized_in = data[:,:,:,:224]
            resized_labels = target[:,:,:224]
            if args.cuda:
                input_var = Variable(resized_in.float().cuda())                             
                label_var = Variable(resized_labels.long().cuda())               
            outputs = model(input_var)              
            loss = segmentation_loss(outputs,label_var)
                
                
        
#             if args.cuda:
#                 data, target = data.cuda(), target.cuda()
            #data, target = Variable(data), Variable(target)
            #optimizer.zero_grad()
            #output = model(data)
            #loss = segmentation_loss(output, target)
            total_loss += loss
#             optimizer.step()
        
        val_loss = total_loss / len(val_loader.dataset)
        reporter(mean_loss = val_loss)
#         model.eval()
#         test_loss = 0
#         correct = 0
#         for data, target in test_loader:
#             if args.cuda:
#                 data, target = data.cuda(), target.cuda()
#             data, target = Variable(data, volatile=True), Variable(target)
#             output = model(data)
#             test_loss += F.nll_loss(
#                 output, target, size_average=False).item()  # sum up batch loss
#             pred = output.data.max(
#                 1, keepdim=True)[1]  # get the index of the max log-probability
#             correct += pred.eq(target.data.view_as(pred)).long().cpu().sum()

#         test_loss = test_loss / len(test_loader.dataset)
#         accuracy = correct.item() / len(test_loader.dataset)
#         reporter(mean_loss=test_loss, mean_accuracy=accuracy)

    for epoch in range(1, args.epochs + 1):
        train(epoch)
        test()


if __name__ == '__main__':
    datasets.MNIST('~/data', train=True, download=True)
    args = parser.parse_args()

    import numpy as np
    import ray
    from ray import tune
    from ray.tune.schedulers import AsyncHyperBandScheduler

    ray.init()
    sched = AsyncHyperBandScheduler(
        time_attr="training_iteration",
        reward_attr="neg_mean_loss",
        max_t=400,
        grace_period=20)
    tune.register_trainable("train_mnist",
                            lambda cfg, rprtr: train_mnist(args, cfg, rprtr))
    tune.run_experiments(
        {
            "exp": {
                "stop": {
#                     "mean_accuracy": 0.98,
                    "training_iteration": 1 if args.smoke_test else 20
                },
                "resources_per_trial": {
                    "gpu": 2
                },
                "run": "train_mnist",
                "num_samples": 1 if args.smoke_test else 10,
                "config": {
                    "lr": tune.sample_from(
                        lambda spec: np.random.uniform(0.001, 0.1)),
                    "momentum": tune.sample_from(
                        lambda spec: np.random.uniform(0.1, 0.9)),
                }
            }
        },
        verbose=0,
        scheduler=sched)

```

**Comment by richardliaw** [comment]
Can you try just running train_mnist -- does this run without Tune? It
looks like you configured most of this correctly (specifically the
resources_per_trial), and if you're using 2 GPUs per trial it should be
basically equivalent to running this without Tune (because you only have 2
GPUs in the first place).

Let me know!

**Comment by Spandan-Madan** [comment]
Found the bug and corrected it! You were right, it wasn't in the integration. It was a very silly error in the train function which was leading to memory leak in pytorch. Thanks for the help!

**Comment by JessicaSchrouff** [comment]
Hi @Spandan-Madan ,
I'm also running out of memory on CUDA and wondering if there is a leak somewhere. Can you point out which error you fixed exactly?
Thank you!
Best,
Jessica

**Comment by knsong** [comment]
@Spandan-Madan  I also want to know how did you fix the out of memory error? Thanks
