### ISSUE TITLE
OSS CI `key_concepts` failure

### ISSUE THREAD

**Issue by GeneDer** [ray-project/ray#39539]
[📖 Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6072#018a81ce-0bb3-4cf5-8639-9584a483585c)
https://buildkite.com/ray-project/oss-ci-build-branch/builds/6072#018a81ce-0bb3-4cf5-8639-9584a483585c/1629-2842

**Comment by GeneDer** [comment]
Related log: https://buildkite.com/ray-project/oss-ci-build-branch/builds/6072#018a81ce-0bb3-4cf5-8639-9584a483585c/1629-2504
```


Training completed after 1 iterations at 2023-09-11 02:13:20. Total running time: 5s
--
  |  
  | Observed metrics: {'world_size': 2, 'world_rank': 0, 'local_rank': 0, 'data_shard':    item
  | 0     1
  | 1     4, 'timestamp': 1694398398, 'done': True, 'training_iteration': 1, 'trial_id': 'c379b_00000', 'date': '2023-09-11_02-13-19', 'time_this_iter_s': 3.0804243087768555, 'time_total_s': 3.0804243087768555, 'pid': 22653, 'hostname': '5ea91f2a4317', 'node_ip': '172.16.16.3', 'config': {}, 'time_since_restore': 3.0804243087768555, 'iterations_since_restore': 1, 'checkpoint_dir_name': None, 'experiment_tag': '0'}
  | Traceback (most recent call last):
  | File "/opt/miniconda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
  | return self._engine.get_loc(casted_key)
  | File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  | File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  | File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  | File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
  | KeyError: 'loss'
  |  
  | The above exception was the direct cause of the following exception:
  |  
  | Traceback (most recent call last):
  | File "/root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/bin/doc/source/train/doc_code/key_concepts.runfiles/com_github_ray_project_ray/doc/source/train/doc_code/key_concepts.py", line 132, in <module>
  | print("Minimum loss", min(df["loss"]))
  | File "/opt/miniconda/lib/python3.8/site-packages/pandas/core/frame.py", line 3807, in __getitem__
  | indexer = self.columns.get_loc(key)
  | File "/opt/miniconda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
  | raise KeyError(key) from err
  | KeyError: 'loss'


```

**Comment by anyscalesam** [comment]
Reviewed and triaged @justinvyu already has WIP PR for this already.
