### ISSUE TITLE
Release Test `gcp_cluster_launcher_nightly_image` failure

### ISSUE THREAD

**Issue by GeneDer** [ray-project/ray#39541]
[gcp_cluster_launcher_nightly_image](https://buildkite.com/ray-project/release-tests-branch/builds/2149#018a7e6c-a2ee-4fed-bc73-1d10802b307d)

**Comment by GeneDer** [comment]
Job: https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_qwm96x147bndd3bz5bb7idyzbf
Related log:
```
Cleaning up cluster...
2023-09-10 02:23:23,823	INFO util.py:374 -- setting max workers for head node type to 0
2023-09-10 02:23:23,983	INFO commands.py:385 -- Checking GCP environment settings
2023-09-10 02:23:25,319	INFO config.py:514 -- _configure_key_pair: Creating new key pair ray-autoscaler_gcp_us-west1_anyscale-bridge-cd812d38_ubuntu_0
Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 2490, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/cli_logger.py", line 856, in wrapper
    return f(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1329, in down
    teardown_cluster(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 438, in teardown_cluster
    config = _bootstrap_config(config)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 413, in _bootstrap_config
    resolved_config = provider_cls.bootstrap_config(config)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/gcp/node_provider.py", line 244, in bootstrap_config
    return bootstrap_gcp(cluster_config)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/gcp/config.py", line 365, in bootstrap_gcp
    config = _configure_key_pair(config, compute)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/gcp/config.py", line 519, in _configure_key_pair
    _create_project_ssh_key_pair(project, public_key, ssh_user, compute)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/gcp/config.py", line 777, in _create_project_ssh_key_pair
    compute.projects()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/googleapiclient/http.py", line 851, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 413 when requesting https://compute.googleapis.com/compute/v1/projects/anyscale-bridge-cd812d38/setCommonInstanceMetadata?alt=json returned "Value for field 'metadata.items[0].value' is too large: maximum size 262144 character(s); actual size 262257.">
Traceback (most recent call last):
  File "launch_and_verify_cluster.py", line 323, in <module>
    run_ray_commands(cluster_config, retries, no_config_cache, num_expected_nodes)
  File "launch_and_verify_cluster.py", line 187, in run_ray_commands
    cleanup_cluster(cluster_config)
  File "launch_and_verify_cluster.py", line 172, in cleanup_cluster
    subprocess.run(["ray", "down", "-v", "-y", str(cluster_config)], check=True)
  File "/home/ray/anaconda3/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ray', 'down', '-v', '-y', '/tmp/tmpv6la_h8o.yaml']' returned non-zero exit status 1.
Subprocess return code: 1
[INFO 2023-09-10 02:23:26,082] anyscale_job_wrapper.py: 190  Process 2797 exited with return code 1.
[INFO 2023-09-10 02:23:26,083] anyscale_job_wrapper.py: 292  Finished with return code 1. Time taken: 5.092032820000014
[WARNING 2023-09-10 02:23:26,083] anyscale_job_wrapper.py: 68  Couldn't upload to cloud storage: '/tmp/release_test_out.json' does not exist.
```

**Comment by GeneDer** [comment]
CC: @xieus @rkooo567 just in case if Jiajun is OOO, can you find an owner for this?

**Comment by rickyyx** [comment]
Rerunning this again - it should be a temporary GC issue.

**Comment by GeneDer** [comment]
I think this (and other GCP tests) been failing on master as well since last Thursday https://buildkite.com/ray-project/release-tests-branch/builds/2140, also tried numerously times over the weekend and this morning and never sew a success 😅
