### ISSUE TITLE
[Rllib] Ray Serialization does not work correctly for spaces.Dict depending on how you create it

### ISSUE THREAD

**Issue by Phirefly9** [ray-project/ray#39586]
### What happened + What you expected to happen

Depending on how you intialize a gymansium.spaces.Dict space the ray serialization will produce a space that is different and causes issues when attempting to reload a checkpoint. 

see reproduction script for what happens vs what happens. the spaces are in a different order which causes issues for the loaded policy (such as connectors being in the wrong order). 

This issue is caused by the following lines of code:

https://github.com/ray-project/ray/blob/master/rllib/utils/serialization.py#L271

and 

https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/spaces/dict.py#L74

on the gymnasium side gymnasium will sort the keys of the space if a gymnasium.space.Dict is passed a regular dictionary, while it will not if it is passed an ordered dict.  the rllib serialization code passed a regular dict.

proposed fix:
rllib should pass in an OrderedDict, or add a new path for handling OrderedDict

### Versions / Dependencies

ray==2.6.3
python==3.10
Gymnasium==0.26.3

### Reproduction script

```python
from collections import OrderedDict
import gymnasium as gym
import numpy as np
from ray.rllib.utils.serialization import space_from_dict, space_to_dict

input_space = gym.spaces.Dict(
    OrderedDict(
        {
            "b_key": gym.spaces.Box(low=np.array([-1.0]), high=np.array([1.0])),
            "a_key": gym.spaces.Discrete(n=3)
        }
    )
)

serialized_dict = space_to_dict(input_space)
deserialized_space = space_from_dict(serialized_dict)

print("OrderedDict")
print(input_space)
print(deserialized_space)
print("************************")

input_space = gym.spaces.Dict(
    {
        "b_key": gym.spaces.Box(low=np.array([-1.0]), high=np.array([1.0])),
        "a_key": gym.spaces.Discrete(n=3)
    }
)
serialized_dict = space_to_dict(input_space)
deserialized_space = space_from_dict(serialized_dict)

print("Dict")
print(input_space)
print(deserialized_space)
```

produces the output 
```
OrderedDict
Dict('b_key': Box(-1.0, 1.0, (1,), float32), 'a_key': Discrete(3))
Dict('a_key': Discrete(3), 'b_key': Box(-1.0, 1.0, (1,), float32))
************************
Dict
Dict('a_key': Discrete(3), 'b_key': Box(-1.0, 1.0, (1,), float32))
Dict('a_key': Discrete(3), 'b_key': Box(-1.0, 1.0, (1,), float32))
************************
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ArturNiederfahrenhorst** [comment]
I see the problem. Can you expand on the problem with the connectors?
Ultimately, it's desirable not to depend on some implicit ordering of sub-elements.
For example, if we flatten a space somewhere and concatenate all elements and later want to unflatten, this is one of the intricacies that can complicate things.

Do you also have a reproduction script that leads to an error?
We could use that or a broken down version of that as a higher-level test when fixing this.

**Comment by sven1977** [comment]
PR in review: https://github.com/ray-project/ray/pull/39627

Thanks for filing this issue @Phirefly9 !

**Comment by Phirefly9** [comment]
script leading to error (pre PR fix obviously):
```python
from ray.rllib.algorithms.ppo import PPOConfig
from ray.rllib.policy import Policy
from ray.rllib.utils.policy import local_policy_inference
import gymnasium

from gymnasium.spaces import Dict, Box, Discrete
from collections import OrderedDict
import os
import tempfile

class OrderedObsEnv(gymnasium.Env):

    def __init__(self, config):
        self.action_space = Box(-1.0, 1.0, (2,))
        self.observation_space = Dict(
            OrderedDict(
                {
                    "b_obs": Discrete(n=1),
                    "a_obs": Box(0.0, 1.0, ),
                }
            ),
        )
        self.max_episode_length = 20

    def reset(self, seed=None, options=None):
        self.steps = 0
        return self.observation_space.sample(), {}

    def step(self, action):
        reward = 0.0
        done = truncated = self.steps >=  self.max_episode_length
        return self.observation_space.sample(), reward, done, truncated, {}


def create_checkpoint(tmpdir):

    config = (
        PPOConfig()
        .environment(OrderedObsEnv)
    )
    algo = config.build()
    algo.save(checkpoint_dir=tmpdir)

def run(checkpoint_path, policy_id):

    policy = Policy.from_checkpoint(
        checkpoint=checkpoint_path,
        policy_ids=[policy_id]
    )

    env = OrderedObsEnv({})
    obs, _ = env.reset()
    terminated = truncated = False
    step = 0

    while not terminated and not truncated:
        step +=1
        policy_outputs = local_policy_inference(
            policy,
            "env1",
            "agent_0",
            obs,
            explore=False
        )
        action, _ ,_ = policy_outputs[0]
        print(f'actions: {action}')

if __name__ == "__main__":
    with tempfile.TemporaryDirectory() as tmpdir:
        policy_id = "default_policy"
        create_checkpoint(tmpdir)
        policy_path = os.path.join(
            tmpdir,
            "checkpoint_000000",
            "policies",
            policy_id)

        run(policy_path, policy_id)
```

leads to error message
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/user/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/user/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/user/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/user/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/user/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/opt/project/scripts/ordered_fail.py", line 78, in <module>
    run(policy_path, policy_id)
  File "/opt/project/scripts/ordered_fail.py", line 58, in run
    policy_outputs = local_policy_inference(
  File "/opt/conda/lib/python3.10/site-packages/ray/rllib/utils/policy.py", line 252, in local_policy_inference
    ac_outputs: List[AgentConnectorsOutput] = policy.agent_connectors(acd_list)
  File "/opt/conda/lib/python3.10/site-packages/ray/rllib/connectors/agent/pipeline.py", line 41, in __call__
    ret = c(ret)
  File "/opt/conda/lib/python3.10/site-packages/ray/rllib/connectors/connector.py", line 254, in __call__
    return [self.transform(d) for d in acd_list]
  File "/opt/conda/lib/python3.10/site-packages/ray/rllib/connectors/connector.py", line 254, in <listcomp>
    return [self.transform(d) for d in acd_list]
  File "/opt/conda/lib/python3.10/site-packages/ray/rllib/connectors/agent/obs_preproc.py", line 58, in transform
    d[SampleBatch.NEXT_OBS] = self._preprocessor.transform(
  File "/opt/conda/lib/python3.10/site-packages/ray/rllib/models/preprocessors.py", line 319, in transform
    self.write(observation, array, 0)
  File "/opt/conda/lib/python3.10/site-packages/ray/rllib/models/preprocessors.py", line 331, in write
    p.write(o, array, offset)
  File "/opt/conda/lib/python3.10/site-packages/ray/rllib/models/preprocessors.py", line 195, in write
    array[offset : offset + self.size] = self.transform(observation)
  File "/opt/conda/lib/python3.10/site-packages/ray/rllib/models/preprocessors.py", line 190, in transform
    self.check_shape(observation)
  File "/opt/conda/lib/python3.10/site-packages/ray/rllib/models/preprocessors.py", line 74, in check_shape
    raise ValueError(
ValueError: Observation ([0.89433795] dtype=None) outside given space (Discrete(1))!
```

**Comment by Phirefly9** [comment]
as far as the connectors, we hypothesize that you save the list of connectors in a certain order, and then when the checkpoint is unserialized, those connectors keep the same order, but then the obs space for the Dict space changes key order. so the connectors try to put obs in the wrong spot leading to the above error
