### ISSUE TITLE
[Data] `from_huggingface` returns `Dataset` with one block

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#39668]
### What happened + What you expected to happen

I used `from_huggingface`, but my dataset only had one block, so my preprocessing wasn't parallelized. 

I was able to work around this by calling `repartition`.

### Versions / Dependencies

Ray: fd227e29c41a9650fbe847e4815f58fb67ecc86f

### Reproduction script

```python
from datasets import load_dataset

import ray

dataset = load_dataset("lj_speech")["train"]
dataset = ray.data.from_huggingface(dataset)
assert dataset.num_blocks() > 1, dataset.num_blocks()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by scottjlee** [comment]
The dataset used here doesn't support streaming due to the `.tar` archive format:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/ray-build/lib/python3.9/site-packages/datasets/load.py", line 2146, in load_dataset
    return builder_instance.as_streaming_dataset(split=split)
  File "/opt/anaconda3/envs/ray-build/lib/python3.9/site-packages/datasets/builder.py", line 1329, in as_streaming_dataset
    splits_generators = {sg.name: sg for sg in self._split_generators(dl_manager)}
  File "/Users/sjl/.cache/huggingface/modules/datasets_modules/datasets/lj_speech/6e03b5308ab68705d902e2bbeaff59feb283307770fafb8d6704e604b6d179aa/lj_speech.py", line 90, in _split_generators
    root_path = dl_manager.download_and_extract(_DL_URL)
  File "/opt/anaconda3/envs/ray-build/lib/python3.9/site-packages/datasets/download/streaming_download_manager.py", line 1063, in download_and_extract
    return self.extract(self.download(url_or_urls))
  File "/opt/anaconda3/envs/ray-build/lib/python3.9/site-packages/datasets/download/streaming_download_manager.py", line 1015, in extract
    urlpaths = map_nested(self._extract, url_or_urls, map_tuple=True)
  File "/opt/anaconda3/envs/ray-build/lib/python3.9/site-packages/datasets/utils/py_utils.py", line 456, in map_nested
    return function(data_struct)
  File "/opt/anaconda3/envs/ray-build/lib/python3.9/site-packages/datasets/download/streaming_download_manager.py", line 1025, in _extract
    raise NotImplementedError(
NotImplementedError: Extraction protocol for TAR archives like 'https://data.keithito.com/data/speech/LJSpeech-1.1.tar.bz2' is not implemented in streaming mode. Please use `dl_manager.iter_archive` instead.
```

This means that `from_huggingface` will fall back to the non-streaming implementation, which calls `from_arrow` on the HF Dataset's underlying Arrow table. As a result, the Ray Dataset has only one block corresponding to this Arrow table.
