### ISSUE TITLE
[core][autoscaler][v1] Infeasible strict spread Placement group would cause autoscaler stops

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#39691]
### What happened + What you expected to happen

When a strict spread PG cannot be fulfilled, it currently crashed the autoscaler v1's processing loop. 

```
2023-09-15 18:46:02,079 CRITICAL autoscaler.py:377 -- StandardAutoscaler: Too many errors, abort.
2023-09-15 18:46:02,079 ERROR monitor.py:434 -- Monitor: Execution exception. Trying again...
Traceback (most recent call last):
  File "/data/home/rickyx/ray-2/python/ray/autoscaler/_private/monitor.py", line 391, in _run
    self.autoscaler.update()
  File "/data/home/rickyx/ray-2/python/ray/autoscaler/_private/autoscaler.py", line 378, in update
    raise e
  File "/data/home/rickyx/ray-2/python/ray/autoscaler/_private/autoscaler.py", line 371, in update
    self._update()
  File "/data/home/rickyx/ray-2/python/ray/autoscaler/_private/autoscaler.py", line 442, in _update
    to_launch, unfulfilled = self.resource_demand_scheduler.get_nodes_to_launch(
  File "/data/home/rickyx/ray-2/python/ray/autoscaler/_private/resource_demand_scheduler.py", line 270, in get_nodes_to_launch
    ) = self.reserve_and_allocate_spread(
  File "/data/home/rickyx/ray-2/python/ray/autoscaler/_private/resource_demand_scheduler.py", line 595, in reserve_and_allocate_spread
    assert not unfulfilled
```

This will crash the loop and not have any scaling effect. 

### Versions / Dependencies

master

### Reproduction script

```
import ray
from ray.cluster_utils import AutoscalingCluster
from ray.util.placement_group import placement_group


cluster = AutoscalingCluster(
    head_resources={"CPU": 1},
    worker_node_types={
        "type-1": {
            "resources": {"CPU": 2},
            "node_config": {},
            "min_workers": 0,
            "max_workers": 2,
        },
    },
    max_workers=2,
)

cluster.start()
ray.init("auto")

from ray.util.placement_group import (
    placement_group,
    placement_group_table,
    remove_placement_group,
)
from ray.util.scheduling_strategies import PlacementGroupSchedulingStrategy


pg = placement_group([{"CPU": 2}] * 3, strategy="STRICT_SPREAD")

from ray.autoscaler.sdk import request_resources
request_resources(num_cpus=4)
```

### Issue Severity

None

**Comment by rkooo567** [comment]
1. Is it a regression?
2. When is the plan to migrate to V2?

**Comment by rickyyx** [comment]
> 1. Is it a regression?
> 2. When is the plan to migrate to V2?

1. Not a regression, has been around in v1.
2. Will be fixed in v2.

**Comment by anyscalesam** [comment]
Fixing in v2 is P0 to explicitly scope the problem here.

**Comment by rkooo567** [comment]
is this fixed in v2?

**Comment by rkooo567** [comment]
I will downgrade all v1 autoscaling issue to p2. please make surer all relevant bugs are fixed in v2!

**Comment by anyscalesam** [comment]
@rickyyx confirming - has this been addressed in the v2 autoscaler codepath?

**Comment by rickyyx** [comment]
yes

**Comment by VassilisVassiliadis** [comment]
We're running into this Exception on our ray cluster which we deploy using the kuberay operator. 

```
 File "/venv/lib/python3.10/site-packages/ray/autoscaler/_private/monitor.py", line 584, in run
self._run()
File "/venv/lib/python3.10/site-packages/ray/autoscaler/_private/monitor.py", line 389, in _run
self.autoscaler.update()
File "/venv/lib/python3.10/site-packages/ray/autoscaler/_private/autoscaler.py", line 384, in update
raise e
File "/venv/lib/python3.10/site-packages/ray/autoscaler/_private/autoscaler.py", line 377, in update
self._update()
File "/venv/lib/python3.10/site-packages/ray/autoscaler/_private/autoscaler.py", line 448, in _update
to_launch, unfulfilled = self.resource_demand_scheduler.get_nodes_to_launch(
File "/venv/lib/python3.10/site-packages/ray/autoscaler/_private/resource_demand_scheduler.py", line 270, in get_nodes_to_launch
) = self.reserve_and_allocate_spread(
File "/venv/lib/python3.10/site-packages/ray/autoscaler/_private/resource_demand_scheduler.py", line 595, in reserve_and_allocate_spread
assert not unfulfilled
AssertionError
```

Does that mean we use v1 of autoscaler? if so, is there a way to switch on v2 ?
