### ISSUE TITLE
[RLlib; docs] MAML example uses wrong (non-supported) environment. Envs used with MAML need to support extra APIs.

### ISSUE THREAD

**Issue by cyAn-Nakamori** [ray-project/ray#39717]
### What happened + What you expected to happen

An error occurred when I ran the following code:
```
from ray.rllib.algorithms.maml import MAMLConfig
config = MAMLConfig().training(use_gae=False)
print(config.to_dict())  # doctest: +SKIP
# Build a Algorithm object from the config and run 1 training iteration.
algo = config.build(env="CartPole-v1")  # doctest: +SKIP
algo.train()  # doctest: +SKIP
```

Here is the error message:
```
C:\Users\liwenjian\Anaconda3\envs\python37\python.exe D:\ray\test.py
2023-09-17 10:27:51,383	WARNING deprecation.py:51 -- DeprecationWarning: `DirectStepOptimizer` has been deprecated. This will raise an error in the future!
{'extra_python_environs_for_driver': {}, 'extra_python_environs_for_worker': {}, 'num_gpus': 0, 'num_cpus_per_worker': 1, 'num_gpus_per_worker': 0, '_fake_gpus': False, 'num_learner_workers': 0, 'num_gpus_per_learner_worker': 0, 'num_cpus_per_learner_worker': 1, 'local_gpu_idx': 0, 'custom_resources_per_worker': {}, 'placement_strategy': 'PACK', 'eager_tracing': True, 'eager_max_retraces': 20, 'tf_session_args': {'intra_op_parallelism_threads': 2, 'inter_op_parallelism_threads': 2, 'gpu_options': {'allow_growth': True}, 'log_device_placement': False, 'device_count': {'CPU': 1}, 'allow_soft_placement': True}, 'local_tf_session_args': {'intra_op_parallelism_threads': 8, 'inter_op_parallelism_threads': 8}, 'torch_compile_learner': False, 'torch_compile_learner_what_to_compile': <TorchCompileWhatToCompile.FORWARD_TRAIN: 'forward_train'>, 'torch_compile_learner_dynamo_backend': 'inductor', 'torch_compile_learner_dynamo_mode': None, 'torch_compile_worker': False, 'torch_compile_worker_dynamo_backend': 'onnxrt', 'torch_compile_worker_dynamo_mode': None, 'env': None, 'env_config': {}, 'observation_space': None, 'action_space': None, 'env_task_fn': None, 'render_env': False, 'clip_rewards': None, 'normalize_actions': True, 'clip_actions': False, 'disable_env_checking': False, '_is_atari': None, 'auto_wrap_old_gym_envs': True, 'action_mask_key': 'action_mask', 'env_runner_cls': None, 'num_envs_per_worker': 1, 'sample_collector': <class 'ray.rllib.evaluation.collectors.simple_list_collector.SimpleListCollector'>, 'sample_async': False, 'enable_connectors': True, 'update_worker_filter_stats': True, 'use_worker_filter_stats': True, 'rollout_fragment_length': 200, 'batch_mode': 'complete_episodes', 'remote_worker_envs': False, 'remote_env_batch_wait_ms': 0, 'validate_workers_after_construction': True, 'preprocessor_pref': 'deepmind', 'observation_filter': 'NoFilter', 'compress_observations': False, 'enable_tf1_exec_eagerly': False, 'sampler_perf_stats_ema_coef': None, 'gamma': 0.99, 'lr': 0.001, 'grad_clip': None, 'grad_clip_by': 'global_norm', 'train_batch_size': 32, 'model': {'_disable_preprocessor_api': False, '_disable_action_flattening': False, 'fcnet_hiddens': [256, 256], 'fcnet_activation': 'tanh', 'conv_filters': None, 'conv_activation': 'relu', 'post_fcnet_hiddens': [], 'post_fcnet_activation': 'relu', 'free_log_std': False, 'no_final_linear': False, 'vf_share_layers': False, 'use_lstm': False, 'max_seq_len': 20, 'lstm_cell_size': 256, 'lstm_use_prev_action': False, 'lstm_use_prev_reward': False, '_time_major': False, 'use_attention': False, 'attention_num_transformer_units': 1, 'attention_dim': 64, 'attention_num_heads': 1, 'attention_head_dim': 32, 'attention_memory_inference': 50, 'attention_memory_training': 50, 'attention_position_wise_mlp_dim': 32, 'attention_init_gru_gate_bias': 2.0, 'attention_use_n_prev_actions': 0, 'attention_use_n_prev_rewards': 0, 'framestack': True, 'dim': 84, 'grayscale': False, 'zero_mean': True, 'custom_model': None, 'custom_model_config': {}, 'custom_action_dist': None, 'custom_preprocessor': None, 'encoder_latent_dim': None, 'always_check_shapes': False, 'lstm_use_prev_action_reward': -1, '_use_default_native_models': -1}, 'optimizer': {}, 'max_requests_in_flight_per_sampler_worker': 2, '_learner_class': None, '_enable_learner_api': False, 'explore': True, 'exploration_config': {'type': 'StochasticSampling'}, 'algorithm_config_overrides_per_module': {}, 'policy_map_capacity': 100, 'policy_mapping_fn': <function AlgorithmConfig.DEFAULT_POLICY_MAPPING_FN at 0x000002262124C708>, 'policies_to_train': None, 'policy_states_are_swappable': False, 'observation_fn': None, 'count_steps_by': 'env_steps', 'input_config': {}, 'actions_in_input_normalized': False, 'postprocess_inputs': False, 'shuffle_buffer_size': 0, 'output': None, 'output_config': {}, 'output_compress_columns': ['obs', 'new_obs'], 'output_max_file_size': 67108864, 'offline_sampling': False, 'evaluation_interval': None, 'evaluation_duration': 10, 'evaluation_duration_unit': 'episodes', 'evaluation_sample_timeout_s': 180.0, 'evaluation_parallel_to_training': False, 'evaluation_config': None, 'off_policy_estimation_methods': {}, 'ope_split_batch_by_episode': True, 'evaluation_num_workers': 0, 'always_attach_evaluation_results': False, 'enable_async_evaluation': False, 'in_evaluation': False, 'sync_filters_on_rollout_workers_timeout_s': 60.0, 'keep_per_episode_custom_metrics': False, 'metrics_episode_collection_timeout_s': 60.0, 'metrics_num_episodes_for_smoothing': 100, 'min_time_s_per_iteration': None, 'min_train_timesteps_per_iteration': 0, 'min_sample_timesteps_per_iteration': 0, 'export_native_model_files': False, 'checkpoint_trainable_policies_only': False, 'logger_creator': None, 'logger_config': None, 'log_level': 'WARN', 'log_sys_usage': True, 'fake_sampler': False, 'seed': None, 'ignore_worker_failures': False, 'recreate_failed_workers': False, 'max_num_worker_restarts': 1000, 'delay_between_worker_restarts_s': 60.0, 'restart_failed_sub_environments': False, 'num_consecutive_worker_failures_tolerance': 100, 'worker_health_probe_timeout_s': 60, 'worker_restore_timeout_s': 1800, 'rl_module_spec': None, '_enable_rl_module_api': False, '_AlgorithmConfig__prior_exploration_config': None, '_tf_policy_handles_more_than_one_loss': False, '_disable_preprocessor_api': False, '_disable_action_flattening': False, '_disable_execution_plan_api': False, '_disable_initialize_loss_from_dummy_batch': False, 'simple_optimizer': -1, 'policy_map_cache': -1, 'worker_cls': -1, 'synchronize_filters': -1, 'replay_sequence_length': None, 'use_gae': False, 'kl_coeff': 0.0005, 'vf_loss_coeff': 0.5, 'entropy_coeff': 0.0, 'clip_param': 0.3, 'vf_clip_param': 10.0, 'kl_target': 0.01, 'inner_adaptation_steps': 1, 'maml_optimizer_steps': 5, 'inner_lr': 0.1, 'use_meta_env': True, 'vf_share_layers': -1, 'lambda': 1.0, 'input': 'sampler', 'policies': {'default_policy': (None, None, None, None)}, 'callbacks': <class 'ray.rllib.algorithms.callbacks.DefaultCallbacks'>, 'create_env_on_driver': True, 'custom_eval_function': None, 'framework': 'torch', 'num_cpus_for_driver': 1, 'num_workers': 2}
2023-09-17 10:27:53,036	WARNING deprecation.py:51 -- DeprecationWarning: `rllib/algorithms/maml/` has been deprecated. Use `rllib_contrib/maml/` instead. This will raise an error in the future!
C:\Users\liwenjian\Anaconda3\envs\python37\lib\site-packages\ray\rllib\algorithms\algorithm.py:484: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
`UnifiedLogger` will be removed in Ray 2.7.
  return UnifiedLogger(config, logdir, loggers=None)
C:\Users\liwenjian\Anaconda3\envs\python37\lib\site-packages\ray\tune\logger\unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
The `JsonLogger interface is deprecated in favor of the `ray.tune.json.JsonLoggerCallback` interface and will be removed in Ray 2.7.
  self._loggers.append(cls(self.config, self.logdir, self.trial))
C:\Users\liwenjian\Anaconda3\envs\python37\lib\site-packages\ray\tune\logger\unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
The `CSVLogger interface is deprecated in favor of the `ray.tune.csv.CSVLoggerCallback` interface and will be removed in Ray 2.7.
  self._loggers.append(cls(self.config, self.logdir, self.trial))
C:\Users\liwenjian\Anaconda3\envs\python37\lib\site-packages\ray\tune\logger\unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
The `TBXLogger interface is deprecated in favor of the `ray.tune.tensorboardx.TBXLoggerCallback` interface and will be removed in Ray 2.7.
  self._loggers.append(cls(self.config, self.logdir, self.trial))
2023-09-17 10:28:03,454	INFO worker.py:1618 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
(pid=2300) DeprecationWarning: `DirectStepOptimizer` has been deprecated. This will raise an error in the future!
(RolloutWorker pid=4824) 2023-09-17 10:28:19,145	WARNING deprecation.py:51 -- DeprecationWarning: `ray.rllib.models.torch.fcnet.FullyConnectedNetwork` has been deprecated. This will raise an error in the future!
(RolloutWorker pid=4824) 2023-09-17 10:28:19,146	WARNING deprecation.py:51 -- DeprecationWarning: `ray.rllib.models.torch.torch_modelv2.TorchModelV2` has been deprecated. Use `ray.rllib.core.rl_module.rl_module.RLModule` instead. This will raise an error in the future!
(RolloutWorker pid=4824) 2023-09-17 10:28:20,833	WARNING deprecation.py:51 -- DeprecationWarning: `StochasticSampling` has been deprecated. This will raise an error in the future!
(RolloutWorker pid=4824) 2023-09-17 10:28:20,833	WARNING deprecation.py:51 -- DeprecationWarning: `Exploration` has been deprecated. This will raise an error in the future!
(RolloutWorker pid=4824) 2023-09-17 10:28:20,834	WARNING deprecation.py:51 -- DeprecationWarning: `Random` has been deprecated. This will raise an error in the future!
(RolloutWorker pid=4824) 2023-09-17 10:28:20,834	WARNING deprecation.py:51 -- DeprecationWarning: `ValueNetworkMixin` has been deprecated. This will raise an error in the future!
(RolloutWorker pid=4824) 2023-09-17 10:28:22,241	WARNING deprecation.py:51 -- DeprecationWarning: `ray.rllib.models.torch.torch_action_dist.TorchDistributionWrapper` has been deprecated. Use `ray.rllib.models.torch.torch_distributions.TorchCategorical` instead. This will raise an error in the future!
2023-09-17 10:28:22,989	WARNING deprecation.py:51 -- DeprecationWarning: `ray.rllib.models.torch.fcnet.FullyConnectedNetwork` has been deprecated. This will raise an error in the future!
2023-09-17 10:28:22,989	WARNING deprecation.py:51 -- DeprecationWarning: `ray.rllib.models.torch.torch_modelv2.TorchModelV2` has been deprecated. Use `ray.rllib.core.rl_module.rl_module.RLModule` instead. This will raise an error in the future!
2023-09-17 10:28:23,111	WARNING deprecation.py:51 -- DeprecationWarning: `StochasticSampling` has been deprecated. This will raise an error in the future!
2023-09-17 10:28:23,111	WARNING deprecation.py:51 -- DeprecationWarning: `Exploration` has been deprecated. This will raise an error in the future!
2023-09-17 10:28:23,111	WARNING deprecation.py:51 -- DeprecationWarning: `Random` has been deprecated. This will raise an error in the future!
2023-09-17 10:28:23,111	WARNING deprecation.py:51 -- DeprecationWarning: `ValueNetworkMixin` has been deprecated. This will raise an error in the future!
2023-09-17 10:28:23,115	WARNING deprecation.py:51 -- DeprecationWarning: `ray.rllib.models.torch.torch_action_dist.TorchDistributionWrapper` has been deprecated. Use `ray.rllib.models.torch.torch_distributions.TorchCategorical` instead. This will raise an error in the future!
2023-09-17 10:28:23,931	WARNING deprecation.py:51 -- DeprecationWarning: `remote_workers()` has been deprecated. Use `Use either the `foreach_worker()`, `foreach_worker_with_id()`, or `foreach_worker_async()` APIs of `WorkerSet`, which all handle fault tolerance.` instead. This will raise an error in the future!
Traceback (most recent call last):
  File "D:\ray\test.py", line 5, in <module>
    algo = config.build(env="CartPole-v1")  # doctest: +SKIP
  File "C:\Users\liwenjian\Anaconda3\envs\python37\lib\site-packages\ray\rllib\algorithms\algorithm_config.py", line 1094, in build
    logger_creator=self.logger_creator,
  File "C:\Users\liwenjian\Anaconda3\envs\python37\lib\site-packages\ray\rllib\utils\deprecation.py", line 106, in patched_init
    return obj_init(*args, **kwargs)
  File "C:\Users\liwenjian\Anaconda3\envs\python37\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 520, in __init__
    **kwargs,
  File "C:\Users\liwenjian\Anaconda3\envs\python37\lib\site-packages\ray\tune\trainable\trainable.py", line 169, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\Users\liwenjian\Anaconda3\envs\python37\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 660, in setup
    self.workers, self.config, **self._kwargs_for_execution_plan()
  File "C:\Users\liwenjian\Anaconda3\envs\python37\lib\site-packages\ray\rllib\algorithms\maml\maml.py", line 341, in execution_plan
    set_worker_tasks(workers, use_meta_env)
  File "C:\Users\liwenjian\Anaconda3\envs\python37\lib\site-packages\ray\rllib\algorithms\maml\maml.py", line 220, in set_worker_tasks
    tasks = workers.local_worker().foreach_env(lambda x: x)[0].sample_tasks(n_tasks)
  File "C:\Users\liwenjian\Anaconda3\envs\python37\lib\site-packages\gymnasium\core.py", line 282, in __getattr__
    return getattr(self.env, name)
  File "C:\Users\liwenjian\Anaconda3\envs\python37\lib\site-packages\gymnasium\core.py", line 282, in __getattr__
    return getattr(self.env, name)
  File "C:\Users\liwenjian\Anaconda3\envs\python37\lib\site-packages\gymnasium\core.py", line 282, in __getattr__
    return getattr(self.env, name)
AttributeError: 'CartPoleEnv' object has no attribute 'sample_tasks'
(pid=4824) DeprecationWarning: `DirectStepOptimizer` has been deprecated. This will raise an error in the future!

Process finished with exit code 1
```

### Versions / Dependencies

gym                      0.21.0
gymnasium            0.28.1
ray                        2.6.3
torch                     1.13.0

### Reproduction script

```
from ray.rllib.algorithms.maml import MAMLConfig
config = MAMLConfig().training(use_gae=False)
print(config.to_dict())  # doctest: +SKIP
# Build a Algorithm object from the config and run 1 training iteration.
algo = config.build(env="CartPole-v1")  # doctest: +SKIP
algo.train()  # doctest: +SKIP
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by sven1977** [comment]
I think I know what this is. MAML requires all environments to support an additional API: `sample_tasks`.
Could you try changing the repro script to the following?
```
from gymnasium.wrappers import TimeLimit

from ray.rllib.algorithms.maml import MAMLConfig
from ray.rllib.examples.env.cartpole_mass import CartPoleMassEnv
from ray.tune.registry import register_env

register_env(
            "cartpole",
            lambda env_cfg: TimeLimit(CartPoleMassEnv(), max_episode_steps=200),
        )


config = MAMLConfig().training(use_gae=False).environment("cartpole")
algo = config.build()
algo.train()
```

**Comment by sven1977** [comment]
We will fix the documentation here. ...

**Comment by cyAn-Nakamori** [comment]
I can successfully run the following code：
`from gymnasium.wrappers import TimeLimit`
`import ray`
`from ray import air`
`from ray import tune`
`from rllib_maml.maml import MAML, MAMLConfig`
`from ray.rllib.examples.env.cartpole_mass import CartPoleMassEnv`
`from ray.tune.registry import register_env`
``
`if __name__ == "__main__":`
`    ray.init()`
`    register_env(`
`        "cartpole",`
`        lambda env_cfg: TimeLimit(CartPoleMassEnv(), max_episode_steps=200),`
`    )`
``
`    rollout_fragment_length = 32`
``
`    config = (`
`        MAMLConfig()`
`        .rollouts(`
`            num_rollout_workers=1, rollout_fragment_length=rollout_fragment_length`
`        )`
`        .framework("torch")`
`        .environment("cartpole", clip_actions=False)`
`        .training(`
`            inner_adaptation_steps=1,`
`            maml_optimizer_steps=5,`
`            gamma=0.99,`
`            lambda_=1.0,`
`            lr=0.001,`
`            vf_loss_coeff=0.5,`
`            inner_lr=0.03,`
`            use_meta_env=False,`
`            clip_param=0.3,`
`            kl_target=0.01,`
`            kl_coeff=0.001,`
`            model=dict(fcnet_hiddens=[64, 64]),`
`            train_batch_size=rollout_fragment_length,`
`        )`
`    )`
``
`    num_iterations = 100`
``
`    tuner = tune.Tuner(`
`        MAML,`
`        param_space=config.to_dict(),`
`        run_config=air.RunConfig(`
`            stop={"training_iteration": num_iterations},`
`            failure_config=air.FailureConfig(fail_fast="raise"),`
`        ),`
`    )`
`    results = tuner.fit()`

Can you tell me at which step the MAML algorithm interacts with the environment and updates parameters？I tried to break the point but couldn't find any code fragments that used the MAML algorithm to calculate loss or interacted with the CartPole environment to obtain observation and action

**Comment by sven1977** [comment]
Closing this issue for now. Feel free to open a new one should you continue to have problems running the MAML algo.

Note, though, that this algo (and several others) will very soon move into a new `rllib_contrib` repository (outside of RLlib) and we will reduce support for any of these algos that will be moved in there due to our ongoing effort to reduce our maintenance load.
