### ISSUE TITLE
[autoscaler] Running example-gpu-docker

### ISSUE THREAD

**Issue by DeepakVellampalli** [ray-project/ray#3975]
Hi,

I am trying to run ray on dock. I downloaded the docker for ray from this "https://github.com/hartikainen/ray.git" repository and branch "feature/nvidia-docker".

When i tried to run "ray up" command on the "example-gpu-docker.yaml", i got the bellow error
```
Traceback (most recent call last):
  File "/home/deepakvellampalli/.local/bin/ray", line 11, in <module>
    sys.exit(main())
  File "/home/deepakvellampalli/.local/lib/python3.5/site-packages/ray/scripts/scripts.py", line 744, in main
    return cli()
  File "/home/deepakvellampalli/.local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/deepakvellampalli/.local/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/deepakvellampalli/.local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/deepakvellampalli/.local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/deepakvellampalli/.local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/deepakvellampalli/.local/lib/python3.5/site-packages/ray/scripts/scripts.py", line 463, in create_or_update
    no_restart, restart_only, yes, cluster_name)
  File "/home/deepakvellampalli/.local/lib/python3.5/site-packages/ray/autoscaler/commands.py", line 43, in create_or_update_cluster
    config = _bootstrap_config(config)
  File "/home/deepakvellampalli/.local/lib/python3.5/site-packages/ray/autoscaler/commands.py", line 57, in _bootstrap_config
    validate_config(config)
  File "/home/deepakvellampalli/.local/lib/python3.5/site-packages/ray/autoscaler/autoscaler.py", line 653, in validate_config
    check_extraneous(config, schema)
  File "/home/deepakvellampalli/.local/lib/python3.5/site-packages/ray/autoscaler/autoscaler.py", line 644, in check_extraneous
    check_extraneous(config[k], v)
  File "/home/deepakvellampalli/.local/lib/python3.5/site-packages/ray/autoscaler/autoscaler.py", line 631, in check_extraneous
    k, list(schema.keys())))
ValueError: Unexpected config key `run_options` not in ['image', 'container_name']
```
Kindly help, to resolve this issue.

**Comment by richardliaw** [comment]
Hi, @DeepakVellampalli, currently that branch is still a work in progress, so I will update this issue when it is ready to test.

Thanks!

**Comment by DeepakVellampalli** [comment]
Okat. Thanks @richardliaw

**Comment by robertnishihara** [comment]
cc @hartikainen

**Comment by richardliaw** [comment]
Hi @DeepakVellampalli, please try out the [latest version of master](https://ray.readthedocs.io/en/latest/installation.html). This example should work - please let us know if you run into issues.
