### ISSUE TITLE
[Core] Ray Gauge metric doesn't support inc and dec

### ISSUE THREAD

**Issue by ykoyfman** [ray-project/ray#39754]
### What happened + What you expected to happen

I need to convert my application's Prometheus metrics to Ray custom metrics, but I have several values represented as Gauges (to track quantities that go up and down over time.)  See: https://github.com/prometheus/client_python#gauge.  The Ray Gauge class only allows setting but not incrementing/decrementing.

### Versions / Dependencies

MacOS 13.5.1
Python 3.10 
Ray 2.7.0

### Reproduction script

Showing first Prometheus API with inc() and dec() and then using the Ray versions:

```
 $ python3.10
Python 3.10.12 (main, Jun 20 2023, 19:43:52) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from prometheus_client import Counter, Gauge
>>> g = Gauge("my_metric", "doc")
>>> g.inc()
>>> g.dec()
>>> from ray.util.metrics import Counter, Gauge
>>> g = Gauge("my_metric", "doc")
>>> g.inc()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Gauge' object has no attribute 'inc'
>>> g.dec()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Gauge' object has no attribute 'dec'
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by popojk** [comment]
Hi, I would like to work on this issue!
