### ISSUE TITLE
[Ray Data] Actor Task fault tolerance do not work as expected

### ISSUE THREAD

**Issue by lee1258561** [ray-project/ray#39800]
### What happened + What you expected to happen

Testing Fault tolerance when performing map_batches with ActorPoolStrategy. 

The following reading parquet dataset in. and apply an map_batches with class based transform that will randomly throw Runtime Error with some probability. And finally the dataset is splitted and consumed by a few worker.

Expect that when I set:
```python
ray_remote_args = {
        "max_restarts": 3,
        "max_task_retries": 3,
}
```
to the map_batches call. Actor fault tolerance will start kick in when the the error in actor tasks is randomly thrown. Instead, the application failed immediately. Full log: 
```
$ python test_actor_task_fault_tolerance.py
2023-09-21 22:31:30,478	INFO worker.py:1633 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8266
2023-09-21 22:31:34,530	WARNING read_api.py:430 -- ⚠️  The requested parallelism of 8512 is more than 4x the number of available CPU slots in the cluster of 16.0. This can lead to slowdowns during the data reading phase due to excessive task creation. Reduce the parallelism to match with the available CPU slots in the cluster, or set parallelism to -1 for Ray Data to automatically determine the parallelism. You can ignore this message if the cluster is expected to autoscale.
(SplitCoordinator pid=23222) Executing DAG InputDataBuffer[Input] -> TaskPoolMapOperator[ReadParquetBulk] -> ActorPoolMapOperator[MapBatches(ClassTransformRandomRaiseWhenCalled)] -> OutputSplitter[split(8, equal=False)]
(SplitCoordinator pid=23222) Execution config: ExecutionOptions(resource_limits=ExecutionResources(cpu=None, gpu=None, object_store_memory=85899345920), locality_with_output=False, preserve_order=False, actor_locality_enabled=True, verbose_progress=True)
(SplitCoordinator pid=23222) MapBatches(ClassTransformRandomRaiseWhenCalled): Waiting for 4 pool actors to start...
(pid=23222) Running: 16.0/16.0 CPU, 0.0/1.0 GPU, 10.97 GiB/80.0 GiB object_store_memory:   0%|                             | 0/8512 [00:04<?, ?it/sTraceback (most recent call last): active, 8500 queued, 10.21 GiB objects:   0%|                                  | 1/8512 [00:04<9:52:43,  4.18s/it]
  File "test_actor_task_fault_tolerance.py", line 65, in <module>active, 0 queued, 778.69 MiB objects, 4 actors [all objects local]:   0%| | 0/8512
    launch_dist_consume(ds, NUM_WORKERS)ctive, 0 queued, 0.0 MiB objects, [locality disabled]:   0%|                       | 0/8512 [00:00<?, ?it/s]
  File "test_actor_task_fault_tolerance.py", line 40, in launch_dist_consume
    ray.get(handles)
  File "/home/prod/.local/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/prod/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/prod/.local/lib/python3.8/site-packages/ray/_private/worker.py", line 2547, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::consume() (pid=22627, ip=10.9.227.123)
  File "test_actor_task_fault_tolerance.py", line 27, in consume
    for i, d in enumerate(it.iter_batches(batch_size=32)):
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/iterator.py", line 229, in _create_iterator
    for batch in iterator:
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 176, in iter_batches
    next_batch = next(async_batch_iter)
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/util.py", line 769, in make_async_gen
    raise next_item
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/util.py", line 746, in execute_computation
    for item in fn(thread_safe_generator):
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 167, in _async_iter_batches
    yield from extract_data_from_batch(batch_iter)
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 206, in extract_data_from_batch
    for batch in batch_iter:
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 306, in restore_original_order
    for batch in batch_iter:
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/util.py", line 769, in make_async_gen
    raise next_item
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/util.py", line 746, in execute_computation
    for item in fn(thread_safe_generator):
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 218, in threadpool_computations_format_collate
    yield from formatted_batch_iter
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 154, in format_batches
    for batch in block_iter:
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/util.py", line 726, in __next__
    return next(self.it)
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 113, in blocks_to_batches
    for block in block_iter:
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 50, in resolve_block_refs
    for block_ref in block_ref_iter:
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 271, in prefetch_batches_locally
    next_block_ref_and_metadata = next(block_ref_iter)
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/util.py", line 726, in __next__
    return next(self.it)
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/iterator/stream_split_iterator.py", line 85, in gen_blocks
    block_ref: Optional[Tuple[ObjectRef[Block], BlockMetadata]] = ray.get(
ray.exceptions.RayTaskError(RuntimeError): ray::SplitCoordinator.get() (pid=23222, ip=10.9.227.123, actor_id=2c8330349f6b6f92d541ecbf01000000, repr=<ray.data._internal.iterator.stream_split_iterator.SplitCoordinator object at 0x7f126a289a90>)
ray.exceptions.ObjectRefStreamEndOfStreamError

During handling of the above exception, another exception occurred:

ray::SplitCoordinator.get() (pid=23222, ip=10.9.227.123, actor_id=2c8330349f6b6f92d541ecbf01000000, repr=<ray.data._internal.iterator.stream_split_iterator.SplitCoordinator object at 0x7f126a289a90>)
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/execution/interfaces/physical_operator.py", line 80, in on_waitable_ready
    meta = ray.get(next(self._streaming_gen))
StopIteration

During handling of the above exception, another exception occurred:

ray::SplitCoordinator.get() (pid=23222, ip=10.9.227.123, actor_id=2c8330349f6b6f92d541ecbf01000000, repr=<ray.data._internal.iterator.stream_split_iterator.SplitCoordinator object at 0x7f126a289a90>)
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/iterator/stream_split_iterator.py", line 210, in get
    next_bundle = self._output_iterator.get_next(output_split_idx)
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 129, in get_next
    raise item
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 129, in get_next
    raise item
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 129, in get_next
    raise item
  [Previous line repeated 2 more times]
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 187, in run
    while self._scheduling_loop_step(self._topology) and not self._shutdown:
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 235, in _scheduling_loop_step
    process_completed_tasks(topology)
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor_state.py", line 333, in process_completed_tasks
    active_tasks[ref].on_waitable_ready()
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/execution/interfaces/physical_operator.py", line 88, in on_waitable_ready
    ex = ray.get(block_ref)
ray.exceptions.RayTaskError(RuntimeError): ray::MapBatches(ClassTransformRandomRaiseWhenCalled)() (pid=23960, ip=10.9.227.123, actor_id=892813da5a7c707344fa080a01000000, repr=MapWorker(MapBatches(ClassTransformRandomRaiseWhenCalled)))
    yield from _map_task(self._map_transformer, data_context, ctx, *blocks)
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 405, in _map_task
    for b_out in map_transformer.apply_transform(iter(blocks), ctx):
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/execution/operators/map_transformer.py", line 345, in __call__
    for data in iter:
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/execution/operators/map_transformer.py", line 190, in __call__
    yield from self._batch_fn(input, ctx)
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/planner/plan_udf_map_op.py", line 189, in transform_fn
    res = fn(batch)
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/planner/plan_udf_map_op.py", line 107, in fn
    return ray.data._cached_fn(item, *fn_args, **fn_kwargs)
  File "/home/prod/.local/lib/python3.8/site-packages/ray/data/_internal/execution/util.py", line 75, in __call__
    return future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "test_actor_task_fault_tolerance.py", line 21, in __call__
    raise_error_randomly(prob=0.2)
  File "test_actor_task_fault_tolerance.py", line 13, in raise_error_randomly
    raise RuntimeError("Intended Error")
RuntimeError: Intended Error


(pid=23222) - MapBatches(ClassTransformRandomRaiseWhenCalled): 1 active, 0 queued, 778.69 MiB objects, 4 actors [al(SplitCoordinator pid=23222) To ensure full parallelization across an actor pool of size 4, the Dataset should consist of at least 4 distinct blocks. Consider increasing the parallelism when creating the Dataset.
```

### Versions / Dependencies

ray 2.7.0

### Reproduction script

```python
import ray
import random
import time
from ray.data import ActorPoolStrategy
from ray.data.datasource.file_meta_provider import DefaultFileMetadataProvider

NUM_WORKERS = 8
ITERATIONS = 50


def raise_error_randomly(prob: float):
    if random.random() <= prob:
        raise RuntimeError("Intended Error")


class ClassTransformRandomRaiseWhenCalled:
    def __init__(self):
        pass

    def __call__(self, x):
        raise_error_randomly(prob=0.2)
        return x


@ray.remote
def consume(it):
    for i, d in enumerate(it.iter_batches(batch_size=32)):
        del d
        if i > ITERATIONS:
            break
        time.sleep(0.8)

        if i % 20 == 0:
            print(f"finished {i} iterations")


def launch_dist_consume(ds, num_workers):
    iters = ds.streaming_split(num_workers)
    handles = [consume.remote(it) for it in iters]
    ray.get(handles)


if __name__ == "__main__":
    ray.data.DataContext.get_current().execution_options.verbose_progress = True
    ray.data.DataContext.get_current().execution_options.resource_limits.object_store_memory = 80 * 1024 * 1024 * 1024


    ray_remote_args = {
        "max_restarts": 3,
        "max_task_retries": 3,
    }

    EXAMPLE_DATA = ["s3://..."]
    ds = ray.data.read_parquet_bulk(EXAMPLE_DATA, meta_provider=DefaultFileMetadataProvider())
    ds = ds.map_batches(
        ClassTransformRandomRaiseWhenCalled,
        batch_size=None,
        batch_format=None,
        compute=ActorPoolStrategy(size=4, max_tasks_in_flight_per_actor=1),
        **ray_remote_args,
    )

    launch_dist_consume(ds, NUM_WORKERS)

```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ericl** [comment]
I think this is because RuntimeError is treated as an application error rather than a system fault. Does the same thing happen if you os._exit(1) or some other forced shutdown of the process instead to mimic a system fault?

**Comment by lee1258561** [comment]
I confirmed that `os._exit(1)` will trigger retry. And I agree with you that by default application error for actor task should not be retried because it is stateful. In the reproduce script though I intentionally put in this to the map_batches by still did not retry
ray_remote_args = {
    "max_restarts": 3,
    "max_task_retries": 3,
}
I wonder if it is still good to leave an option to users so that if they think the actor is safe to retry they can retry. Also for e.g. let’s say a read task is fused with an downstream actor based transform. We want to retry on the flacky IO error, but since read & transform are now performed in the same _MapWorker actor we are not able to retry it.

**Comment by ericl** [comment]
It should be possible to adjust the exceptions that would be retried using
the retry_exceptions arg, which can take a list of exception classes to
retry.

Though I'm not sure if this issue still applies
https://github.com/ray-project/ray/issues/30456

**Comment by lee1258561** [comment]
@c21 
One Flacky error we face we we used boto based s3fs. 
```
Traceback (most recent call last):
  File "/machine-learning/trainer/ray/train/actor_based_trainer.py", line 272, in launch_mlenv_trainer
    wait_for_ray_mlenv_job(ray_mlenv_job)
  File "/machine-learning/trainer/ray/train/actor_based_trainer.py", line 172, in wait_for_ray_mlenv_job
    ray.get(finished_proc_ref)
  File "/usr/local/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/_private/worker.py", line 2493, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(SSLError): [36mray::RayMLEnvRunner.run_trainer()[39m (pid=719, ip=10.12.14.68, actor_id=2d06687add5ff296da94860c02000000, repr=<trainer.ray.train.actor_based_trainer.RayMLEnvRunner object at 0x7e849a57bf70>)
  File "/machine-learning/trainer/ray/train/actor_based_trainer.py", line 64, in run_trainer
    run_single_process(config_bundle, ds_iter)
  File "/machine-learning/trainer/ppytorch/utils/launcher.py", line 127, in run_single_process
    trainer.run()
  File "/machine-learning/trainer/ppytorch/base/distributed.py", line 107, in run
    super().run(base_dir)
  File "/machine-learning/trainer/utils/ptrainer.py", line 247, in run
    raise e
  File "/machine-learning/trainer/utils/ptrainer.py", line 234, in run
    solver.execute(gpus=self.gpus, run_dir=run_dir, tb_log_dir=tb_log_dir)
  File "/machine-learning/trainer/ppytorch/mlenv/common/solver/basic_solver.py", line 817, in execute
    for batch in self.train_dataset_loader:
  File "/usr/local/lib/python3.8/site-packages/ray/data/iterator.py", line 189, in iter_batches
    yield from iter_batches(
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 176, in iter_batches
    next_batch = next(async_batch_iter)
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 289, in make_async_gen
    raise next_item
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 266, in execute_computation
    for item in fn(thread_safe_generator):
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 167, in _async_iter_batches
    yield from extract_data_from_batch(batch_iter)
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 210, in extract_data_from_batch
    for batch in batch_iter:
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 306, in restore_original_order
    for batch in batch_iter:
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 218, in threadpool_computations_format_collate
    yield from formatted_batch_iter
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 179, in collate
    for batch in batch_iter:
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 158, in format_batches
    for batch in block_iter:
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 117, in blocks_to_batches
    for block in block_iter:
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 54, in resolve_block_refs
    for block_ref in block_ref_iter:
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 254, in prefetch_batches_locally
    for block_ref, metadata in block_ref_iter:
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/block_batching/util.py", line 246, in __next__
    return next(self.it)
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/iterator/stream_split_iterator.py", line 85, in gen_blocks
    block_ref: Optional[Tuple[ObjectRef[Block], BlockMetadata]] = ray.get(
ray.exceptions.RayTaskError(SSLError): [36mray::SplitCoordinator.get()[39m (pid=6305, ip=10.12.120.150, actor_id=3cf8ac336c1a012e46b685d202000000, repr=<ray.data._internal.iterator.stream_split_iterator.SplitCoordinator object at 0x7f5a89f3a070>)
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/iterator/stream_split_iterator.py", line 210, in get
    next_bundle = self._output_iterator.get_next(output_split_idx)
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 129, in get_next
    raise item
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 129, in get_next
    raise item
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 129, in get_next
    raise item
  [Previous line repeated 4 more times]
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 187, in run
    while self._scheduling_loop_step(self._topology) and not self._shutdown:
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor.py", line 235, in _scheduling_loop_step
    process_completed_tasks(topology)
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/execution/streaming_executor_state.py", line 333, in process_completed_tasks
    op.notify_work_completed(ref)
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/execution/operators/actor_pool_map_operator.py", line 219, in notify_work_completed
    task.output = self._map_ref_to_ref_bundle(ref)
  File "/usr/local/lib/python3.8/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 360, in _map_ref_to_ref_bundle
    block_metas = ray.get(all_refs[-1])
ray.exceptions.RayTaskError(SSLError): [36mray::ReadParquetBulk->MapBatches(bad_actors_filter)->MapBatches(tabularml_arrow_feature_converter)->MapBatches(BatcherActor)()[39m (pid=5704, ip=10.12.56.38)
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 515, in read
    data = self._fp.read() if not fp_closed else b""
  File "/usr/local/lib/python3.8/http/client.py", line 472, in read
    s = self._safe_read(self.length)
  File "/usr/local/lib/python3.8/http/client.py", line 613, in _safe_read
    data = self.fp.read(amt)
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2635)
```
When we use pyarrow S3FileSystem we could face OSError when it talking with aws-cpp-sdk

**Comment by raulchen** [comment]
This is a Ray Core issue, duplicated as https://github.com/ray-project/ray/issues/25457. 
Note, it can be worked around with an application-level try-catch.

**Comment by lee1258561** [comment]
@raulchen I think in the case where the read stage is fused with the actor transform stage and the flaky error happens in the s3 reading, a try catch in actor transform is not suffice to handle this error?

**Comment by c21** [comment]
Hi @lee1258561, yes and we are adding support to allow retrying user exception on Core - https://github.com/ray-project/ray/pull/41194 . ETA is Ray 2.9 in next few weeks, then you can specify which exceptions you want to retry, and configure number of retries for actor task.

**Comment by autolisis** [comment]
Hi I see that #41194 has been merged to master. However, looking through the changelog on https://github.com/ray-project/ray/releases, I was unable to find any mention of this new feature. Is this a supported capability now to set retry_exceptions on actor methods?
