### ISSUE TITLE
[Ray Dashboard] Dashboard exit after start a few days or hours

### ISSUE THREAD

**Issue by arcsun** [ray-project/ray#39822]
### What happened + What you expected to happen

We are using Ray as an alternative to Python's process pool，and everything runs well except for the dashboard.
After a few days or hours, the dashboard will exit, and I find these logs in dashboard.log
----------------------
2023-09-24 14:32:07,334 ERROR node_head.py:302 -- Cannot reach the node, a88290518677665bb0e49b9b8a31dbb1d347a8fd7dcd189b4775a3ad, after timeout 4. This node may have been overloaded, terminated, or the network is slow.
NoneType: None
2023-09-24 14:32:23,088 ERROR node_head.py:203 -- Error updating nodes.
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/ray/dashboard/modules/node/node_head.py", line 147, in _update_nodes
    nodes = await self._get_nodes()
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/ray/dashboard/modules/node/node_head.py", line 132, in _get_nodes
    reply = await self._gcs_node_info_stub.GetAllNodeInfo(request, timeout=2)
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/grpc/aio/_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2023-09-24T14:32:07.631232477+08:00", grpc_status:4}"
>
2023-09-24 14:42:31,233 ERROR head.py:187 -- Failed to check gcs health, client timed out.
2023-09-24 14:42:47,236 ERROR head.py:187 -- Failed to check gcs health, client timed out.
......
2023-09-24 14:43:03,238 ERROR head.py:187 -- Failed to check gcs health, client timed out.
2023-09-24 14:43:03,239 ERROR head.py:198 -- Dashboard exiting because it received too many GCS RPC errors count: 41, threshold is 40.

### Versions / Dependencies

ray 2.6.3
docker container of debian 10

### Reproduction script

ray start --disable-usage-stats --head --port=9270 --dashboard-port=9756 --dashboard-host='0.0.0.0'

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by arcsun** [comment]
It seems won't affect the ray workers，but it's annoying and I have to restart ray and django to fix it

**Comment by rkooo567** [comment]
Based on the logs, it seems like it couldn't communicate with GCS. This commonly happens when the GCS is terminated. Can you check the log of gcs_server.out around the time this issue happened?

**Comment by arcsun** [comment]
> Based on the logs, it seems like it couldn't communicate with GCS. This commonly happens when the GCS is terminated. Can you check the log of gcs_server.out around the time this issue happened?

dashboard.log:
```
2023-09-26 13:39:51,521 ERROR head.py:187 -- Failed to check gcs health, client timed out.
2023-09-26 13:40:07,524 ERROR head.py:187 -- Failed to check gcs health, client timed out.
2023-09-26 13:40:23,527 ERROR head.py:187 -- Failed to check gcs health, client timed out.
2023-09-26 13:40:39,531 ERROR head.py:187 -- Failed to check gcs health, client timed out.
2023-09-26 13:40:39,532 ERROR head.py:198 -- Dashboard exiting because it received too many GCS RPC errors count: 41, threshold is 40.
```
gcs_server.out:
```

[2023-09-26 13:38:13,844 I 3276 3276] (gcs_server) gcs_server.cc:873: GcsTaskManager Event stats:


Global stats: 0 total (0 active)
Queueing time: mean = -nan s, max = -0.000 s, min = 9223372036.855 s, total = 0.000 s
Execution time:  mean = -nan s, total = 0.000 s
Event stats:


[2023-09-26 13:39:13,844 I 3276 3276] (gcs_server) gcs_server.cc:255: GcsNodeManager:
- RegisterNode request count: 1
- DrainNode request count: 0
- GetAllNodeInfo request count: 333204
- GetInternalConfig request count: 1

GcsActorManager:
- RegisterActor request count: 0
- CreateActor request count: 0
- GetActorInfo request count: 0
- GetNamedActorInfo request count: 0
- GetAllActorInfo request count: 1
- KillActor request count: 0
- ListNamedActors request count: 0
- Registered actors count: 0
- Destroyed actors count: 0
- Named actors count: 0
- Unresolved actors count: 0
- Pending actors count: 0
- Created actors count: 0
- owners_: 0
- actor_to_register_callbacks_: 0
- actor_to_create_callbacks_: 0
- sorted_destroyed_actor_list_: 0

GcsResourceManager:
- GetResources request count: 0
- GetAllAvailableResources request count304312
- ReportResourceUsage request count: 0
- GetAllResourceUsage request count: 14438

GcsPlacementGroupManager:
- CreatePlacementGroup request count: 0
- RemovePlacementGroup request count: 0
- GetPlacementGroup request count: 0
- GetAllPlacementGroup request count: 0
- WaitPlacementGroupUntilReady request count: 0
- GetNamedPlacementGroup request count: 0
- Scheduling pending placement group count: 0
- Registered placement groups count: 0
- Named placement group count: 0
- Pending placement groups count: 0
- Infeasible placement groups count: 0

GcsPublisher {}

[runtime env manager] ID to URIs table:
[runtime env manager] URIs reference table:

GcsTaskManager:
-Total num task events reported: 0
-Total num status task events dropped: 0
-Total num profile events dropped: 0
-Total num bytes of task event stored: 0MiB
-Current num of task events stored: 0
-Total num of actor creation tasks: 0
-Total num of actor tasks: 0
-Total num of normal tasks: 0
-Total num of driver tasks: 0


[2023-09-26 13:39:13,844 I 3276 3276] (gcs_server) gcs_server.cc:872: Event stats:


Global stats: 1488739 total (4 active)
Queueing time: mean = 624.283 us, max = 38.023 s, min = -0.001 s, total = 929.395 s
Execution time:  mean = 139.046 us, total = 207.004 s
Event stats:
        NodeInfoGcsService.grpc_server.GetAllNodeInfo - 333204 total (0 active), CPU time: mean = 53.961 us, total = 17.980 s
        NodeResourceInfoGcsService.grpc_server.GetAllAvailableResources - 304312 total (0 active), CPU time: mean = 85.579 us, total = 26.043 s
        GcsInMemoryStore.Put - 187959 total (0 active), CPU time: mean = 38.312 us, total = 7.201 s
        InternalKVGcsService.grpc_server.InternalKVPut - 187955 total (0 active), CPU time: mean = 34.849 us, total = 6.550 s
        InternalKVGcsService.grpc_client.InternalKVPut - 86838 total (0 active), CPU time: mean = 16.821 us, total = 1.461 s
        RayletLoadPulled - 72353 total (1 active), CPU time: mean = 209.512 us, total = 15.159 s
        NodeManagerService.grpc_client.GetResourceLoad - 72350 total (0 active), CPU time: mean = 38.213 us, total = 2.765 s
        GcsInMemoryStore.Get - 71892 total (0 active), CPU time: mean = 38.854 us, total = 2.793 s
        InternalKVGcsService.grpc_server.InternalKVGet - 71890 total (0 active), CPU time: mean = 48.089 us, total = 3.457 s
        NodeInfoGcsService.grpc_server.CheckAlive - 28837 total (0 active), CPU time: mean = 47.886 us, total = 1.381 s
        UNKNOWN - 24128 total (1 active), CPU time: mean = 11.393 us, total = 274.895 ms
        HealthCheck - 24118 total (0 active), CPU time: mean = 8.396 us, total = 202.492 ms
        NodeResourceInfoGcsService.grpc_server.GetAllResourceUsage - 14438 total (0 active), CPU time: mean = 105.394 us, total = 1.522 s
        GCSServer.deadline_timer.debug_state_dump - 7237 total (1 active), CPU time: mean = 16.502 ms, total = 119.422 s
        GCSServer.deadline_timer.debug_state_event_stats_print - 1208 total (1 active, 1 running), CPU time: mean = 655.797 us, total = 792.202 ms
        GcsInMemoryStore.GetAll - 8 total (0 active), CPU time: mean = 21.456 us, total = 171.646 us
        PeriodicalRunner.RunFnPeriodically - 4 total (0 active), CPU time: mean = 85.590 us, total = 342.360 us
        InternalKVGcsService.grpc_server.InternalKVDel - 1 total (0 active), CPU time: mean = 52.823 us, total = 52.823 us
        GcsResourceManager::Update - 1 total (0 active), CPU time: mean = 101.194 us, total = 101.194 us
        NodeInfoGcsService.grpc_server.RegisterNode - 1 total (0 active), CPU time: mean = 186.007 us, total = 186.007 us
        JobInfoGcsService.grpc_server.GetAllJobInfo - 1 total (0 active), CPU time: mean = 88.961 us, total = 88.961 us
        NodeInfoGcsService.grpc_server.GetInternalConfig - 1 total (0 active), CPU time: mean = 34.975 us, total = 34.975 us
        GcsInMemoryStore.Delete - 1 total (0 active), CPU time: mean = 28.294 us, total = 28.294 us
        ActorInfoGcsService.grpc_server.GetAllActorInfo - 1 total (0 active), CPU time: mean = 25.894 us, total = 25.894 us
        GcsHealthCheckManager::AddNode - 1 total (0 active), CPU time: mean = 16.142 us, total = 16.142 us
```

**Comment by arcsun** [comment]
Our usage pattern is to have heavy load for several hours, followed by idle time of several hours to one day, and this cycle repeats. Could this be related to the issue?

**Comment by rkooo567** [comment]
So, the issue happens if the dashboard (that lives in the same proc as GCS) fails to health check the GCS for 40 times (10 seconds timeout each). 

So somehow your dashboard process couldn't communicate with gcs_server process for a while. You said this happens after "idle", not when you have a heavy workload?

**Comment by rkooo567** [comment]
I am not exactly sure why there's such issue. It can happen due to network error (which is not common because both gcs_server and dashboard runs in the same host). 2. The GCS is overloaded and responds slowly (which is also uncommon because you said it happens at idle time). 

you can alternatively modify this behavior by setting env var when you run ray start --head

GCS_CHECK_ALIVE_MAX_COUNT_OF_RPC_ERROR=40 by default
GCS_CHECK_ALIVE_RPC_TIMEOUT=10 (seconds) by default

**Comment by arcsun** [comment]
> I am not exactly sure why there's such issue. It can happen due to network error (which is not common because both gcs_server and dashboard runs in the same host). 2. The GCS is overloaded and responds slowly (which is also uncommon because you said it happens at idle time).
> 
> you can alternatively modify this behavior by setting env var when you run ray start --head
> 
> GCS_CHECK_ALIVE_MAX_COUNT_OF_RPC_ERROR=40 by default GCS_CHECK_ALIVE_RPC_TIMEOUT=10 (seconds) by default

This fixed my problem, it's still alive after a week。My args are:
```
export GCS_CHECK_ALIVE_MAX_COUNT_OF_RPC_ERROR=100
export GCS_CHECK_ALIVE_RPC_TIMEOUT=90
```
