### ISSUE TITLE
[Tune] TuneBOHB has errors when resumed from Tuner.restore

### ISSUE THREAD

**Issue by f2010126** [ray-project/ray#39900]
### What happened + What you expected to happen

While adding the `restore` function for [fault tolerance](https://docs.ray.io/en/latest/tune/tutorials/tune-fault-tolerance.html) when using the `TuneBOHB` search algorithm and ,  the experiments to stop functioning. 

I had used the fault tolerance code with `ASHAScheduler` and the restore function works as expected. If the trials were not terminated, they are restored and run correctly. If all trials are terminated, the best trial is displayed and nothing is started. 

#### CPU

When using `HyperBandForBOHB` and `TuneBOHB`, when running on CPU, restoring the checkpoint gives the following warning:
```
WARNING insufficient_resources_manager.py:163 -- Ignore this message if the cluster is autoscaling. No trial is running and no new trial has been started within the last 60 seconds. This could be due to the cluster not having enough resources available. You asked for 2.0 CPUs and 0 GPUs per trial, but the cluster only has 10.0 CPUs and 0 GPUs available. Stop the tuning and adjust the required resources (e.g. via the ScalingConfig or resources_per_trial, or num_workers for rllib), or add more resources to your cluster.
```

Some trails which showed as Terminated in the original run are restarted, set to `PAUSED` and the resource warning is shown, stopping any further running.

#### GPU

For GPUs, a error is thrown. The Trials which were in `PENDING` state are restarted and the error:
```
  File "/XXXXXXXXXXX/lib/python3.10/site-packages/ray/air/execution/_internal/actor_manager.py", line 224, in next
    self._actor_task_events.resolve_future(future)
  File "/XXXXXXXXXXX/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 118, in resolve_future
    on_result(result)
  File "/XXXXXXXXXXX/lib/python3.10/site-packages/ray/air/execution/_internal/actor_manager.py", line 765, in on_result
    self._actor_task_resolved(
  File "/XXXXXXXXXXX/lib/python3.10/site-packages/ray/air/execution/_internal/actor_manager.py", line 300, in _actor_task_resolved
    tracked_actor_task._on_result(tracked_actor, result)
  File "/XXXXXXXXXXX/lib/python3.10/site-packages/ray/tune/execution/tune_controller.py", line 1400, in _on_result
    raise TuneError(traceback.format_exc())
ray.tune.error.TuneError: Traceback (most recent call last):
  File "/XXXXXXXXXXX/lib/python3.10/site-packages/ray/tune/execution/tune_controller.py", line 1391, in _on_result
    on_result(trial, *args, **kwargs)
  File "/XXXXXXXXXXX/lib/python3.10/site-packages/ray/tune/execution/tune_controller.py", line 1705, in _on_training_result
    self._process_trial_results(trial, result)
  File "/XXXXXXXXXXX/lib/python3.10/site-packages/ray/tune/execution/tune_controller.py", line 1718, in _process_trial_results
    decision = self._process_trial_result(trial, result)
  File "/XXXXXXXXXXX/lib/python3.10/site-packages/ray/tune/execution/tune_controller.py", line 1777, in _process_trial_result
    self._search_alg.on_trial_result(trial.trial_id, flat_result)
  File "/XXXXXXXXXXX/lib/python3.10/site-packages/ray/tune/search/search_generator.py", line 137, in on_trial_result
    self.searcher.on_trial_result(trial_id, result)
  File "/XXXXXXXXXXX/lib/python3.10/site-packages/ray/tune/search/concurrency_limiter.py", line 143, in on_trial_result
    self.searcher.on_trial_result(trial_id, result)
  File "/XXXXXXXXXXX/lib/python3.10/site-packages/ray/tune/search/bohb/bohb_search.py", line 254, in on_trial_result
    hbs_wrapper = self.to_wrapper(trial_id, result)
  File "/XXXXXXXXXXX/lib/python3.10/site-packages/ray/tune/search/bohb/bohb_search.py", line 268, in to_wrapper
    self.trial_to_params[trial_id],
KeyError: 
```

I think this behavior is linked to the fact that BOHB pauses trials at some point while executing. 
Maybe  unfavorable trials should be terminated, not `PAUSED` when they are not picked for the next bracket. 

### Versions / Dependencies

ray                           2.7.0
torch                         2.0.1
transformers                  4.31.0
pytorch-lightning             2.0.8

CUDA 11.7

#### Data and Model Modules
```python 
class DataModuleMNIST(pl.LightningDataModule):
    def __init__(self):
        super().__init__()
        self.download_dir = './data'
        self.batch_size = 32
        self.transform = transforms.Compose([
            transforms.ToTensor()
        ])
        self.dataworkers = int(os.cpu_count() / 2)
        self.prepare_data_per_node = True

    def prepare_data(self):
        datasets.MNIST(self.download_dir,
                       train=True, download=True)

        datasets.MNIST(self.download_dir, train=False,
                       download=True)

    def setup(self, stage=None):
        data = datasets.MNIST(self.download_dir,
                              train=True, transform=self.transform, download=True)

        self.train_data, self.valid_data = random_split(data, [55000, 5000])

        self.test_data = datasets.MNIST(self.download_dir,
                                        train=False, transform=self.transform)

    def train_dataloader(self):
        return DataLoader(self.train_data, batch_size=self.batch_size, num_workers=self.dataworkers)

    def val_dataloader(self):
        return DataLoader(self.valid_data, batch_size=self.batch_size, num_workers=self.dataworkers)

    def test_dataloader(self):
        return DataLoader(self.test_data, batch_size=self.batch_size, num_workers=self.dataworkers)


class LightningMNISTClassifier(pl.LightningModule):
    def __init__(self, config):
        super(LightningMNISTClassifier, self).__init__()

        self.lr = config["lr"]
        layer_1, layer_2 = config["layer_1"], config["layer_2"]
        self.batch_size = config["batch_size"]

        # mnist images are (1, 28, 28) (channels, width, height)
        self.layer_1 = torch.nn.Linear(28 * 28, layer_1)
        self.layer_2 = torch.nn.Linear(layer_1, layer_2)
        self.layer_3 = torch.nn.Linear(layer_2, 10)
        self.accuracy = Accuracy(task="multiclass", num_classes=10)
        self.val_output_list = []

    def forward(self, x):
        batch_size, channels, width, height = x.size()
        x = x.view(batch_size, -1)
        x = self.layer_1(x)
        x = torch.relu(x)
        x = self.layer_2(x)
        x = torch.relu(x)
        x = self.layer_3(x)
        x = torch.log_softmax(x, dim=1)
        return x

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=self.lr)

    def on_fit_start(self):
        print("---------- Starting training")
        if torch.cuda.is_available():
            print(f" No of GPUs available : {torch.cuda.device_count()}")
        else:
            print("No GPU available")

    def training_step(self, train_batch, batch_idx):
        x, y = train_batch
        logits = self.forward(x)
        loss = F.nll_loss(logits, y)
        acc = self.accuracy(logits, y)
        self.log("ptl/train_loss", loss, on_step=True, on_epoch=True, prog_bar=True, logger=True, sync_dist=True)
        self.log("ptl/train_accuracy", acc, on_step=True, on_epoch=True, prog_bar=True, logger=True, sync_dist=True)
        return loss

    def validation_step(self, val_batch, batch_idx):
        x, y = val_batch
        logits = self.forward(x)
        loss = F.nll_loss(logits, y)
        acc = self.accuracy(logits, y)
        result = {"val_loss": loss, "val_accuracy": acc}
        self.val_output_list.append(result)
        return {"val_loss": loss, "val_accuracy": acc}

    def on_validation_epoch_end(self):
        outputs = self.val_output_list
        avg_loss = torch.stack([x["val_loss"] for x in outputs]).mean()
        avg_acc = torch.stack([x["val_accuracy"] for x in outputs]).mean()

        self.log("ptl/val_loss", avg_loss, on_step=False, on_epoch=True, prog_bar=True, logger=True)
        self.log("ptl/val_accuracy", avg_acc, on_step=False, on_epoch=True, prog_bar=True, logger=True)
        return {"loss": avg_loss, "acc": avg_acc}

    def on_validation_end(self):
        # last hook that's used by Trainer.
        print("---------- Finished validation?")
```

#### Ray Tune Functionality:

```python
config = {
        "layer_1": tune.choice([32, 64, 128]),
        "layer_2": tune.choice([64, 128, 256]),
        "lr": tune.loguniform(1e-4, 1e-1),
        "batch_size": tune.choice([32, 64, 128]),
    }

def objective_torch_trainer(config, data_dir=os.path.join(os.getcwd(), "testing_data")):
    logging.debug(f"config-------> {config} in dir {data_dir} and cwd {os.getcwd()}")
    dm =DataModuleMNIST()
    model = AshaTransformer(config=config)
    ckpt_report_callback = RayTrainReportCallback()
    log_dir = os.path.join(os.getcwd(), "ray_results_log/torch_trainer_logs")
    trainer = pl.Trainer(
        max_epochs=3,
        logger=[CSVLogger(save_dir=log_dir, name="csv_torch_trainer_logs", version="."),
                TensorBoardLogger(save_dir=log_dir, name="tensorboard_torch_trainer_logs", version=".")],

        devices='auto',
        accelerator='auto', # change to 'cpu' for local
        enable_progress_bar=True,
        max_time="00:12:00:00",  # give each run a time limit
        val_check_interval=0.5,  # check validation set 4 times during a training epoch
        strategy=RayDDPStrategy(),
        plugins=[RayLightningEnvironment()],
        callbacks=[ckpt_report_callback])

    # Validate your Lightning trainer configuration
    trainer = prepare_trainer(trainer)
    trainer.fit(model, datamodule=dm)
    print(f"trainer metrics: {trainer.callback_metrics}")
    print("Finished obj")


def debug_bohb(num_samples=10, num_epochs=10, exp_name="debug_bohb"):
    max_iterations = 3
    # scheduler
    bohb_hyperband = HyperBandForBOHB(
        time_attr="training_iteration",
        max_t=max_iterations,  # max time per trial? max length of time a trial
        reduction_factor=2,  # cut down trials by factor of?
        stop_last_trials=True,
    )

    # search Algo
    bohb_search = TuneBOHB(
        # space=config_space,  # If you want to set the space manually
    )
    # Number of parallel runs allowed
    bohb_search = tune.search.ConcurrencyLimiter(bohb_search, max_concurrent=4)

    if torch.cuda.is_available():
        gpus_per_worker = 4
        scaling_config = ray.train.ScalingConfig(
            num_workers=gpus_per_worker, use_gpu=True, resources_per_worker={"CPU": 2, "GPU": 1}
        )
    else:
        scaling_config = ray.train.ScalingConfig(
            num_workers=1, use_gpu=False, resources_per_worker={"CPU": 1, }
        )
    train_fn_with_parameters = tune.with_parameters(objective_torch_trainer,
                                                    data_dir=os.path.join(os.getcwd(), "debug_testing_data"))
    ray_trainer = TorchTrainer(
        train_fn_with_parameters,
        scaling_config=scaling_config,
        run_config=ray.train.RunConfig(
            checkpoint_config=ray.train.CheckpointConfig(
                num_to_keep=3,
                checkpoint_score_attribute="ptl/val_accuracy",
                checkpoint_score_order="max",
            ),
        )
    )

    result_dir = os.path.join(os.getcwd(), "ray_results_result")
    # Fault Tolerance Code
    exp_name = "bohb_tune_fault_tolerance_guide"
    restore_path = os.path.join(result_dir, exp_name)
    if tune.Tuner.can_restore(restore_path):
        tuner = tune.Tuner.restore(restore_path,
                                   trainable=ray_trainer,
                                   resume_unfinished=True,
                                   resume_errored=True,
                                   restart_errored=False,
                                   param_space={"train_loop_config":config},
                                   )
    else:
        tuner = tune.Tuner(ray_trainer,
                           tune_config=tune.TuneConfig(
                               metric="ptl/val_accuracy",
                               mode="max",
                               scheduler=bohb_hyperband,
                               search_alg=bohb_search,
                               reuse_actors=False,
                               num_samples=num_samples,
                               # trial_name_creator=trial_dir_name,
                               # trial_dirname_creator=trial_dir_name,
                           ),
                           run_config=ray.train.RunConfig(
                               name=exp_name,
                               verbose=2,
                               storage_path=result_dir,
                               log_to_file=True,
                               checkpoint_config=ray.train.CheckpointConfig(
                                   num_to_keep=3,
                                   checkpoint_score_attribute="ptl/val_accuracy",
                                   checkpoint_score_order="max",
                               ),
                           ),
                           param_space={"train_loop_config": config},
                           )
    results = tuner.fit()

    print("Best hyperparameters found were: ", results.get_best_result().config)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by justinvyu** [comment]
> Though, is the restarting of the unfinished trial the task of the scheduler or the Algorithm? Because BOHB as a whole has no means to resume a trial if there was a system failure. It can only do warmstarting, (uses prior results to select configs).


Restarting the (paused) trial is actually the job of our internal control loop. The scheduler should be the one to select paused trials to continue (`choose_trial_to_run`), but eventually the control loop will actually execute this decision.

What seems to be happening is that the scheduler loses track of paused trials and never chooses to unpause them. Then, because we have a concurrency limiter, we never choose to suggest any new trials either, so the run just hangs.

**Comment by f2010126** [comment]
> What seems to be happening is that the scheduler loses track of paused trials and never chooses to unpause them. Then, because we have a concurrency limiter, we never choose to suggest any new trials either, so the run just hangs.

Thank you for the explanation!  
It's only the HyperBandForBOHB scheduler that is acting out then. Because the same training function with ASHA works fine, including resuming.

**Comment by chrvt** [comment]
What is the conclusion then? Don't use HyperBandForBOHB if one wants to Tune.restore a failed experiment? I'm running into the same problem but the provided explanation does not help me to fix it.
