### ISSUE TITLE
MosaicML Trainer example fails with SigInt when launched through JobClient

### ISSUE THREAD

**Issue by rakataprime** [ray-project/ray#40035]
### What happened + What you expected to happen

The mosaicml trainer example script [mosaic_cifar10_example.py](https://github.com/ray-project/ray/blob/master/python/ray/train/examples/mosaic_cifar10_example.py) fails when launched through the python job api.  

This may be related to some of the other sigint issues reported:
https://github.com/ray-project/ray/pull/39482

[job-driver-raysubmit_fLYTLHwSRLjbe2ur.log](https://github.com/ray-project/ray/files/12787684/job-driver-raysubmit_fLYTLHwSRLjbe2ur.log)

full log is attached 
```

ray.exceptions.RaySystemError: System error: Can't set signal handler for SIGINT while SIGINT is being deferred within a DeferSigint context.
traceback: Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/train/mosaic/__init__.py", line 1, in <module>
    from ray.train.mosaic.mosaic_trainer import MosaicTrainer
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/train/mosaic/mosaic_trainer.py", line 5, in <module>
    from composer.trainer import Trainer
  File "/tmp/ray/session_2023-10-02_00-25-43_927843_1/runtime_resources/pip/a60ba9b5cbc0f59b95fd507281c195250e1b464d/virtualenv/lib/python3.10/site-packages/composer/__init__.py", line 7, in <module>
    from composer.core import Algorithm, Callback, DataSpec, Engine, Evaluator, Event, State, Time, Timestamp, TimeUnit
  File "/tmp/ray/session_2023-10-02_00-25-43_927843_1/runtime_resources/pip/a60ba9b5cbc0f59b95fd507281c195250e1b464d/virtualenv/lib/python3.10/site-packages/composer/core/__init__.py", line 14, in <module>
    from composer.core.engine import Engine, Trace
  File "/tmp/ray/session_2023-10-02_00-25-43_927843_1/runtime_resources/pip/a60ba9b5cbc0f59b95fd507281c195250e1b464d/virtualenv/lib/python3.10/site-packages/composer/core/engine.py", line 127, in <module>
    signal.signal(signal.SIGINT, sigterm_handler)
ValueError: Can't set signal handler for SIGINT while SIGINT is being deferred within a DeferSigint context.
```

### Versions / Dependencies

running off of the ray nightly ray container rayproject/ray-ml:9670b3-py310-gpu, python310, ubuntu 20.04, ray version 3.00-dev
[job-driver-raysubmit_fLYTLHwSRLjbe2ur.log](https://github.com/ray-project/ray/files/12787593/job-driver-raysubmit_fLYTLHwSRLjbe2ur.log)

### Reproduction script

```
# after copying mosaic_cifar10_example.py to the working directory of the ray cluster head
from ray.job_submission import JobSubmissionClient
dashboard_address= "ray://127.0.0.1:8265"
client = JobSubmissionClient(dashboard_address)
script_command = f"python mosaic_cifar10_example.py  --address 127.0.0.1:8265 --n 1 --use-gpu"
runtime_env = {"pip": ["mosaicml==0.12.1"]}
client.submit_job(entrypoint=script_command,  runtime_env=runtime_env )
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by matthewdeng** [comment]
@jonathan-anyscale @jjyao any ideas here? Not sure if this could be caused by the fact that Ray Train doesn't run the training script on the main thread?

**Comment by jonathan-anyscale** [comment]
Taking a look
Seems like the main issue is here 
https://github.com/ray-project/ray/blob/f45ef45edc55983edea8542fa338769f6d0b90b3/python/ray/_raylet.pyx#L1603
we can't set `sigterm_handler` for `signal.SIGINT` when we are running in main thread

**Comment by matthewdeng** [comment]
@rakataprime  I tried this with a simpler script (the `MosaicTrainer` is being deprecated).

```python
from ray.train.torch import TorchTrainer
from ray.train import ScalingConfig

def train_func():
    from composer.trainer import Trainer

trainer = TorchTrainer(train_func, scaling_config=ScalingConfig(num_workers=2))
trainer.fit() 
```

This fails with this:

```
ray.exceptions.RayTaskError(ValueError): ray::_RayTrainWorker__execute.get_next() (pid=9424, ip=10.0.0.180, actor_id=df0d155b0e8bb7c3d1ad00e707000000, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x7efc18733be0>)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/worker_group.py", line 33, in __execute
    raise skipped from exception_cause(skipped)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 129, in discard_return_wrapper
    train_func(*args, **kwargs)
  File "/home/ray/default/sigint_test.py", line 8, in f
    from composer.trainer import Trainer
  File "/mnt/cluster_storage/pypi/lib/python3.9/site-packages/composer/__init__.py", line 7, in <module>
    from composer.core import Algorithm, Callback, DataSpec, Engine, Evaluator, Event, State, Time, Timestamp, TimeUnit
  File "/mnt/cluster_storage/pypi/lib/python3.9/site-packages/composer/core/__init__.py", line 14, in <module>
    from composer.core.engine import Engine, Trace
  File "/mnt/cluster_storage/pypi/lib/python3.9/site-packages/composer/core/engine.py", line 126, in <module>
    signal.signal(signal.SIGTERM, sigterm_handler)
  File "/home/ray/anaconda3/lib/python3.9/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
```

This is happening because the `train_func` is being executed on a separate thread. What you can do here is disable the signal, but I'm not entirely sure if there are side effects from doing this:

```python
from ray.train.torch import TorchTrainer
from ray.train import ScalingConfig

def train_func():
    import signal
    signal.signal = lambda *args, **kwargs: None
    from composer.trainer import Trainer

trainer = TorchTrainer(train_func, scaling_config=ScalingConfig(num_workers=2))
trainer.fit() 
```

**Comment by anyscalesam** [comment]
reviewing - this can be foundationally fixed on train side only @matthewdeng
