### ISSUE TITLE
[Core] Throwing exception in tracing hook crashes worker

### ISSUE THREAD

**Issue by alexeykudinkin** [ray-project/ray#40136]
### What happened + What you expected to happen

Whenever exception is being thrown from utility provided as `--tracing-startup-hook`, it seems that the Ray Core worker crashes:

```
Traceback (most recent call last):
  File "/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_private/worker.py", line 2165, in connect
    node.check_version_info()
  File "/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_private/node.py", line 382, in check_version_info
    cluster_metadata = ray_usage_lib.get_cluster_metadata(self.get_gcs_client())
  File "/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_private/usage/usage_lib.py", line 721, in get_cluster_metadata
    namespace=ray_constants.KV_NAMESPACE_CLUSTER,
...skipping...
  % (secret_name, clientErrorCode)
/app/product_api_image.binary.runfiles/product/backend/utils/get_secret.py:46: UserWarning: Getting secret for endpoints_metronome_token failed with error code AccessDeniedException
  % (secret_name, clientErrorCode)
Traceback (most recent call last):
  File "/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_private/workers/default_worker.py", line 251, in <module>
    worker_launched_time_ms=worker_launched_time_ms,
  File "/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_private/worker.py", line 2343, in connect
    _setup_tracing()
  File "/app/product_api_image.binary.runfiles/product/backend/server/common/telemetry/__init__.py", line 72, in patch_in_tracing
    tracer_provider.add_span_processor(DynamicAttributeRecorder())
  File "/app/product_api_image.binary.runfiles/product/backend/server/common/telemetry/dynamic_attr_recorder.py", line 46, in __init__
    self._validate_fast_enough(dynamic_attributes, timedelta(microseconds=10))
  File "/app/product_api_image.binary.runfiles/product/backend/server/common/telemetry/dynamic_attr_recorder.py", line 72, in _validate_fast_enough
    f"Dynamic attribute {name} took an average of {duration/runs}s which is longer than {time_budget.total_seconds()}s to run"
ValueError: Dynamic attribute event_loop took an average of 9.184417873620987e-05s which is longer than 1e-05s to run
[2023-10-02 22:36:34,267 E 523 523] logging.cc:104: Stack trace:
 /app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(+0xf4761a) [0x7fabd8ae961a] ray::operator<<()
/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(+0xf49dd8) [0x7fabd8aebdd8] ray::TerminateHandler()
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa5966) [0x7fabd7a70966]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa59d1) [0x7fabd7a709d1]
/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(_ZN3ray4core10CoreWorkerD1Ev+0x1167) [0x7fabd82f4197] ray::core::CoreWorker::~CoreWorker()
/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(+0x60e44a) [0x7fabd81b044a] std::_Sp_counted_base<>::_M_release()
/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(_ZN3ray4core21CoreWorkerProcessImplD1Ev+0xfe) [0x7fabd833021e] ray::core::CoreWorkerProcessImpl::~CoreWorkerProcessImpl()
/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(_ZN3ray4core17CoreWorkerProcess12HandleAtExitEv+0x29) [0x7fabd83303f9] ray::core::CoreWorkerProcess::HandleAtExit()
/lib/x86_64-linux-gnu/libc.so.6(+0x3b4d7) [0x7fabd9b1b4d7]
/lib/x86_64-linux-gnu/libc.so.6(+0x3b67a) [0x7fabd9b1b67a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7fabd9b03d11] __libc_start_main
ray::IDLE(_start+0x2a) [0x555b425de08a] _start

[2023-10-02 22:36:34,880 E 515 515] logging.cc:104: Stack trace:
 /app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(+0xf4761a) [0x7f15c1a5761a] ray::operator<<()
/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(+0xf49dd8) [0x7f15c1a59dd8] ray::TerminateHandler()
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa5966) [0x7f15c09de966]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa59d1) [0x7f15c09de9d1]
/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(_ZN3ray4core10CoreWorkerD1Ev+0x1167) [0x7f15c1262197] ray::core::CoreWorker::~CoreWorker()
/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(+0x60e44a) [0x7f15c111e44a] std::_Sp_counted_base<>::_M_release()
/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(_ZN3ray4core21CoreWorkerProcessImplD1Ev+0xfe) [0x7f15c129e21e] ray::core::CoreWorkerProcessImpl::~CoreWorkerProcessImpl()
/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(_ZN3ray4core17CoreWorkerProcess12HandleAtExitEv+0x29) [0x7f15c129e3f9] ray::core::CoreWorkerProcess::HandleAtExit()
/lib/x86_64-linux-gnu/libc.so.6(+0x3b4d7) [0x7f15c2a894d7]
/lib/x86_64-linux-gnu/libc.so.6(+0x3b67a) [0x7f15c2a8967a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7f15c2a71d11] __libc_start_main
ray::IDLE(_start+0x2a) [0x5592ec7be08a] _start

[2023-10-02 22:36:34,980 E 494 494] logging.cc:104: Stack trace:
 /app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(+0xf4761a) [0x7f9f94e4e61a] ray::operator<<()
/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(+0xf49dd8) [0x7f9f94e50dd8] ray::TerminateHandler()
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa5966) [0x7f9f93dd5966]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa59d1) [0x7f9f93dd59d1]
/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(_ZN3ray4core10CoreWorkerD1Ev+0x1167) [0x7f9f94659197] ray::core::CoreWorker::~CoreWorker()
/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(+0x60e44a) [0x7f9f9451544a] std::_Sp_counted_base<>::_M_release()
/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(_ZN3ray4core21CoreWorkerProcessImplD1Ev+0xfe) [0x7f9f9469521e] ray::core::CoreWorkerProcessImpl::~CoreWorkerProcessImpl()
/app/product_api_image.binary.runfiles/py_deps_ray/site-packages/ray/_raylet.so(_ZN3ray4core17CoreWorkerProcess12HandleAtExitEv+0x29) [0x7f9f946953f9] ray::core::CoreWorkerProcess::HandleAtExit()
/lib/x86_64-linux-gnu/libc.so.6(+0x3b4d7) [0x7f9f95e804d7]
/lib/x86_64-linux-gnu/libc.so.6(+0x3b67a) [0x7f9f95e8067a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7f9f95e68d11] __libc_start_main
ray::IDLE(_start+0x2a) [0x55a986dc208a] _start
```

### Versions / Dependencies

2.7

### Reproduction script

Throw an exception from the method submitted as `--tracing-startup-hook`

### Issue Severity

Low: It annoys or frustrates me.

**Comment by rkooo567** [comment]
Btw, I think I discussed with @alexeykudinkin last time, and I guess the issue is the exception is raised while initializing a core worker. Maybe we can delay rasing an exception or we should run a startup hook after core worker is fully intiialized

**Comment by alexeykudinkin** [comment]
@rkooo567 we can't control application's code. I think the primary issue here is that the Core worker crashes instead of handling it gracefully

**Comment by rkooo567** [comment]
Oh I was talking about core side change (the core side fix)

**Comment by rkooo567** [comment]
The fix should be wait until core worker is initialized before running this; 
```
    # Setup tracing here
    tracing_hook_val = worker.gcs_client.internal_kv_get(
        b"tracing_startup_hook", ray_constants.KV_NAMESPACE_TRACING
    )
    if tracing_hook_val is not None:
        ray.util.tracing.tracing_helper._enable_tracing()
        if not getattr(ray, "__traced__", False):
            _setup_tracing = _import_from_string(tracing_hook_val.decode("utf-8"))
            _setup_tracing()
            ray.__traced__ = True
```

Btw @alexeykudinkin what's the priority for this? We have pretty big list of P0 bugs now (16), so unless it is critical from your end, we may want to fix it in 2.9

**Comment by alexeykudinkin** [comment]
We can push this to 2.9
