### ISSUE TITLE
[Core] Ray kills the worker process if the job runs into exceptions but recovers on reties

### ISSUE THREAD

**Issue by jhasm-ck** [ray-project/ray#40229]
### What Happened
If the job code runs into exception (e.g. when calling dependency services) but has retries configured it eventually gets killed by ray with message like following

```
2023-10-09 23:04:29,519	WARNING worker.py:2058 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 90e532d0d6bdd5b721b01faac8e67a11ebdd68820d000000 Worker ID: 6b7a0f3d03afacc65e17c50eb9a3f803567c32d6ccbd1ac1e5fbe297 Node ID: b84c11df2fa6619b489695775eb45dd85cd2ee113b9525d70a34bc96 Worker IP address: 10.184.24.227 Worker port: 10026 Worker PID: 2830 Worker exit type: SYSTEM_ERROR Worker exit detail: The leased worker has unrecoverable failure. Worker is requested to be destroyed when it is returned.
Traceback (most recent call last):
  File "ray_job_simulate_excessive_exceptions.py", line 64, in <module>
    run()
  File "ray_job_simulate_excessive_exceptions.py", line 59, in run
    ray.get(predict.remote())
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/worker.py", line 2549, in get
    raise value
ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
```

The worker log pointed by this message does not provide any helpful information. It looks like following,
```
[2023-10-09 23:04:29,525 I 2830 2845] core_worker.cc:570: Event stats:


Global stats: 56540 total (7 active)
Queueing time: mean = 35.015 us, max = 80.855 ms, min = -0.000 s, total = 1.980 s
Execution time:  mean = 20.534 us, total = 1.161 s
Event stats:
	UNKNOWN - 51309 total (6 active, 1 running), CPU time: mean = 14.780 us, total = 758.356 ms
	NodeManagerService.grpc_client.ReportWorkerBacklog - 4200 total (0 active), CPU time: mean = 12.316 us, total = 51.728 ms
	CoreWorkerService.grpc_server.GetCoreWorkerStats - 839 total (0 active), CPU time: mean = 33.006 us, total = 27.692 ms
	CoreWorkerService.grpc_server.PubsubCommandBatch - 45 total (0 active), CPU time: mean = 25.363 us, total = 1.141 ms
	CoreWorkerService.grpc_server.PubsubLongPolling - 30 total (0 active), CPU time: mean = 11.858 us, total = 355.752 us
	CoreWorkerService.grpc_server.ReportGeneratorItemReturns - 16 total (0 active), CPU time: mean = 46.839 us, total = 749.419 us
	CoreWorkerService.grpc_server.UpdateObjectLocationBatch - 12 total (0 active), CPU time: mean = 14.721 us, total = 176.650 us
	InternalPubSubGcsService.grpc_client.GcsSubscriberPoll - 11 total (1 active), CPU time: mean = 171.164 us, total = 1.883 ms
	CoreWorkerService.grpc_client.PushTask - 10 total (0 active), CPU time: mean = 111.031 us, total = 1.110 ms
	CoreWorker.SubmitTask - 9 total (0 active), CPU time: mean = 121.081 us, total = 1.090 ms
	NodeManagerService.grpc_client.PinObjectIDs - 9 total (0 active), CPU time: mean = 16.482 us, total = 148.337 us
	NodeManagerService.grpc_client.ReturnWorker - 9 total (0 active), CPU time: mean = 7.328 us, total = 65.953 us
	NodeManagerService.grpc_client.RequestWorkerLease - 9 total (0 active), CPU time: mean = 182.217 us, total = 1.640 ms
	CoreWorkerService.grpc_server.LocalGC - 7 total (0 active), CPU time: mean = 44.674 ms, total = 312.720 ms
	PeriodicalRunner.RunFnPeriodically - 6 total (0 active), CPU time: mean = 48.457 us, total = 290.740 us
	Subscriber.HandlePublishedMessage_GCS_NODE_INFO_CHANNEL - 4 total (0 active), CPU time: mean = 96.261 us, total = 385.044 us
	CoreWorkerService.grpc_server.GetObjectLocationsOwner - 3 total (0 active), CPU time: mean = 19.169 us, total = 57.507 us
	CoreWorkerService.grpc_client.GetObjectLocationsOwner - 3 total (0 active), CPU time: mean = 14.744 us, total = 44.233 us
	ActorInfoGcsService.grpc_client.GetNamedActorInfo - 2 total (0 active), CPU time: mean = 40.931 us, total = 81.862 us
	InternalPubSubGcsService.grpc_client.GcsSubscriberCommandBatch - 2 total (0 active), CPU time: mean = 84.828 us, total = 169.655 us
	CoreWorkerDirectActorTaskSubmitter::SubmitTask - 1 total (0 active), CPU time: mean = 7.944 us, total = 7.944 us
	CoreWorkerService.grpc_server.PushTask - 1 total (0 active), CPU time: mean = 49.131 us, total = 49.131 us
	WorkerInfoGcsService.grpc_client.AddWorkerInfo - 1 total (0 active), CPU time: mean = 22.782 us, total = 22.782 us
	ActorInfoGcsService.grpc_client.GetActorInfo - 1 total (0 active), CPU time: mean = 908.937 us, total = 908.937 us
	NodeInfoGcsService.grpc_client.GetAllNodeInfo - 1 total (0 active), CPU time: mean = 138.056 us, total = 138.056 us

-----------------
Task Event stats:

IO Service Stats:

Global stats: 4204 total (1 active)
Queueing time: mean = 34.152 us, max = 3.721 ms, min = -0.000 s, total = 143.575 ms
Execution time:  mean = 5.013 us, total = 21.075 ms
Event stats:
	CoreWorker.deadline_timer.flush_task_events - 4200 total (1 active), CPU time: mean = 5.003 us, total = 21.014 ms
	TaskInfoGcsService.grpc_client.AddTaskEventData - 3 total (0 active), CPU time: mean = 18.107 us, total = 54.321 us
	PeriodicalRunner.RunFnPeriodically - 1 total (0 active), CPU time: mean = 6.672 us, total = 6.672 us
Other Stats:
	grpc_in_progress:0
	current number of task events in buffer: 0
	total task events sent: 0 MiB
	total number of task events sent: 0
	num status task events dropped: 0
	num profile task events dropped: 0
```

### What I expect
I expect ray to either let the job run to completion, or provide a clear message for why it killed the job. In the current situation, we do not know how we can improve the chances of the job succeeding. The exception in the job are not necessarily in our control, if need to call dependency services or hosted model endpoints. We work around the exceptions by retrying, but the job gets killed by Ray anyway without any helpful information.

### Versions / Dependencies

Ray version: 2.7.0
Kuberay version: 0.6.0
Python version: 3.8
OS: Linux 5.15.0-1041-azure #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Reproduction script

Kuberay cluster definition yaml (uploaded as txt because github wont let me upload a yaml file): 
[kuberay-cluster-definition.yaml.txt](https://github.com/ray-project/ray/files/12860309/kuberay-cluster-definition.yaml.txt)

Ray job code to reproduce the issue

```
# ray_job_simulate_excessive_exceptions.py
import time
import random

import pandas as pd
import ray
import backoff


NUM_RECORDS = 100000
PARALLELISM = 8
FAIL_PROBABILITY = 0.3
SLEEP_SECONDS = 1


def get_data() -> ray.data.Dataset:
    return ray.data.range(n=NUM_RECORDS, parallelism=PARALLELISM)


@backoff.on_exception(
    backoff.expo,
    Exception,
    max_tries=20,
    max_time=60 * 10,
    jitter=backoff.full_jitter,
)
def process_row(row):
    print(f"Processing row: {row}")
    # Sleep to simulate work
    time.sleep(SLEEP_SECONDS)
    print(f"Woke up from sleep for row: {row}")
    if random.random() < FAIL_PROBABILITY:
        print(f"Simulating exception for row {row}")
        raise Exception(f"Simulated exception for row {row}")
    return row


def process_batch(df: pd.DataFrame) -> pd.DataFrame:
    for index, row in df.iterrows():
        process_row(row)
    return df


@ray.remote
def predict():
    ds = get_data()
    ds.map_batches(process_row)
    for row in ds.iter_rows():
        process_row(row)


def run():
    ray.get(predict.remote())


if __name__ == "__main__":
    start = time.time()
    run()
    end = time.time()
    print(f"Time taken: {end - start} seconds")

```

Job submission
```
ray job submit --address https://my-remote-ray-cluster/ --runtime-env-json='{"working_dir": ".", "pip": ["backoff"]}' -- python ray_job_simulate_excessive_exceptions.py
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by jhasm-ck** [comment]
@richardliaw FYI

**Comment by richardliaw** [comment]
A couple questions -- 
* do we have any more information here, especially with logs?
* the backoff library is a bit of a smell, not sure if that actually works well with Ray. You should try to use Ray's native backoff
* Any reason why you are using @ray.remote? If you remove it, what happens?

**Comment by richardliaw** [comment]
cc @xieus or @rkooo567 if you can find someone to triage

**Comment by zhe-thoughts** [comment]
I'm pretty sure this should be P1 but @xieus @rkooo567 pls update as you see fit
