### ISSUE TITLE
[Dashboard] Failed to load job driver logs on job page

### ISSUE THREAD

**Issue by BhautikDonga** [ray-project/ray#40249]
### What happened + What you expected to happen

I am running cluster using `cluster.yaml` file and submitting job via `JobSubmissionClient`. After submitting a job, when I tried to check driver logs on job page, it showing:
![image](https://github.com/ray-project/ray/assets/34915439/50228688-45aa-493b-bc6e-c78ba22a9c06)

When I check `dashboard.log` file, I could find following error:
```
2023-09-14 19:32:39,459	INFO state_head.py:421 -- Streaming logs with options: GetLogOptions(timeout=30, node_id='b677f4256cdb12b2dfbfbc055396f3aa859b4dd901d4ad65d4a08cc9', node_ip=None, media_type='file', filename='job-driver-raysubmit_XYcqmYJvTtnu4ui7.log', actor_id=None, task_id=None, attempt_number=0, pid=None, lines=50000, interval=None, suffix='out', submission_id=None)
2023-09-14 19:32:39,459	INFO log_manager.py:442 -- Resolved log file: node_id='b677f4256cdb12b2dfbfbc055396f3aa859b4dd901d4ad65d4a08cc9' filename='job-driver-raysubmit_XYcqmYJvTtnu4ui7.log' start_offset=None end_offset=None
2023-09-14 19:32:39,461	ERROR state_head.py:439 -- <AioRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Unexpected <class 'AttributeError'>: 'grpc._cython.cygrpc._ServicerContext' object has no attribute 'done'"
	debug_error_string = "{"created":"@1694700159.461056331","description":"Error received from peer ipv4:10.60.62.206:63358","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Unexpected <class 'AttributeError'>: 'grpc._cython.cygrpc._ServicerContext' object has no attribute 'done'","grpc_status":2}"
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ray/dashboard/modules/state/state_head.py", line 427, in get_logs
    async for logs_in_bytes in self._log_api.stream_logs(options):
  File "/usr/local/lib/python3.8/dist-packages/ray/dashboard/modules/log/log_manager.py", line 125, in stream_logs
    async for streamed_log in stream:
  File "/usr/local/lib/python3.8/dist-packages/grpc/aio/_call.py", line 321, in _fetch_stream_responses
    await self._raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/grpc/aio/_call.py", line 231, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Unexpected <class 'AttributeError'>: 'grpc._cython.cygrpc._ServicerContext' object has no attribute 'done'"
	debug_error_string = "{"created":"@1694700159.461056331","description":"Error received from peer ipv4:10.60.62.206:63358","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Unexpected <class 'AttributeError'>: 'grpc._cython.cygrpc._ServicerContext' object has no attribute 'done'","grpc_status":2}"
>
```

### Versions / Dependencies

ray==2.6.0
grpcio==1.34.1

python3.8
Ubuntu 20.04.6 LTS

### Reproduction script

submit a job to cluster started with following versions:
ray==2.6.0 and grpcio==1.34.1.

### Issue Severity

High: It blocks me from completing my task.

**Comment by BhautikDonga** [comment]
I have confirmed that driver log file is there under `Logs` section. So I guess there are some grpc version issues to read that file.

**Comment by scottsun94** [comment]
@alanwguo @rkooo567

**Comment by anyscalesam** [comment]
@rkooo567 @alanwguo which one of you are going to first take a look at this?

**Comment by rkooo567** [comment]
I think core team should take it.

**Comment by jjyao** [comment]
@BhautikDonga can you upgrade the grpcio version to 1.42 and see if it fixes the issue?

**Comment by jjyao** [comment]
We will update the lower bound of grpcio to avoid this issue in the first place.

**Comment by BhautikDonga** [comment]
> can you upgrade the grpcio version to 1.42 and see if it fixes the issue?

Yes, with upgraded version, it's working fine.

**Comment by anyscalesam** [comment]
@jjyao have we updated the base version in ray27+ ??

**Comment by jjyao** [comment]
We are doing 

```
"grpcio >= 1.32.0; python_version < '3.10'",  # noqa:E501
"grpcio >= 1.42.0; python_version >= '3.10'",  # noqa:E501
```

now.
