### ISSUE TITLE
[Tune] Checkpoints made with Ray 2.6.3 do not work with Ray 2.7.1

### ISSUE THREAD

**Issue by olipinski** [ray-project/ray#40262]
### What happened + What you expected to happen

Attempting to resume a tune run created with Ray 2.6.3 leads to the error below:

```python-traceback
2023-10-11 16:29:17,710 WARNING deprecation.py:50 -- DeprecationWarning: `DirectStepOptimizer` has been deprecated. This will raise an error in the future!
2023-10-11 16:29:54,618 INFO worker.py:1633 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265
/home/user/.conda/envs/pack/lib/python3.10/site-packages/ray/tune/impl/tuner_internal.py:338: UserWarning: `tune.SyncConfig` has been moved to `train.SyncConfig`. Please update your code to use `train.SyncConfig`, as this will raise an error in a future Ray version.
  tuner_state = pickle.loads(f.readall())
Traceback (most recent call last):
  File "/home/user/.conda/envs/pack/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/.conda/envs/pack/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mainfs/scratch/user/pack/pack/train.py", line 455, in <module>
    app.run(main)
  File "/home/user/.conda/envs/pack/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/user/.conda/envs/pack/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/mainfs/scratch/user/pack/pack/train.py", line 411, in main
    results = tuner.fit()
  File "/home/user/.conda/envs/pack/lib/python3.10/site-packages/ray/tune/tuner.py", line 372, in fit
    return self._local_tuner.fit()
  File "/home/user/.conda/envs/pack/lib/python3.10/site-packages/ray/tune/impl/tuner_internal.py", line 581, in fit
    analysis = self._fit_resume(trainable, param_space)
  File "/home/user/.conda/envs/pack/lib/python3.10/site-packages/ray/tune/impl/tuner_internal.py", line 734, in _fit_resume
    analysis = run(**args)
  File "/home/user/.conda/envs/pack/lib/python3.10/site-packages/ray/tune/tune.py", line 851, in run
    experiments[i] = Experiment(
  File "/home/user/.conda/envs/pack/lib/python3.10/site-packages/ray/tune/experiment/experiment.py", line 204, in __init__
    self.storage = StorageContext(
  File "/home/user/.conda/envs/pack/lib/python3.10/site-packages/ray/train/_internal/storage.py", line 451, in __init__
    dataclasses.replace(sync_config) if sync_config else SyncConfig()
  File "/home/user/.conda/envs/pack/lib/python3.10/dataclasses.py", line 1453, in replace
    return obj.__class__(**changes)
  File "/home/user/.conda/envs/pack/lib/python3.10/site-packages/ray/tune/syncer.py", line 22, in __new__
    return super(SyncConfig, cls).__new__(cls, *args, **kwargs)
TypeError: object.__new__() takes exactly one argument (the type to instantiate)
```

### Versions / Dependencies

Ray 2.6.3 / Ray 2.7.1
Python 3.10.13

### Reproduction script

```python
if not tune.Tuner.can_restore(run_dir):
    raise RuntimeError("Cannot restore requested checkpoint!")

tuner = tune.Tuner.restore(
    run_dir,
    trainable=APPO,
    resume_errored=True,
    param_space=ray_config.to_dict(),
)
results = tuner.fit()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by matthewdeng** [comment]
Hey @olipinski would you be able to complete this experiment using 2.6.3? Generally restoring across versions isn't well supported.

**Comment by olipinski** [comment]
Hi @matthewdeng, yes it should be fine to complete using 2.6.3. But is there any way to convert older checkpoints to a newer version of ray?

**Comment by matthewdeng** [comment]
Unfortunately there is currently not an implemented way of converting Tune Experiment checkpoints. 

If you have a Trial checkpoint (e.g. `.../checkpoints/checkpoint_00000`) you can do this by saving it as a new checkpoint in a newer version.

**Comment by olipinski** [comment]
Okay, thanks!
