### ISSUE TITLE
[Core] Does ray require python version 3.8 or higher?

### ISSUE THREAD

**Issue by larrylian** [ray-project/ray#40489]
### What happened + What you expected to happen

'Literal' from 'typing' don't support python 3.7.x.  Does ray require python version 3.8 or higher?

```
$ ray start --head
Traceback (most recent call last):
  File "/home/admin/.pyenv/versions/3.7.11_ray/bin/ray", line 11, in <module>
    load_entry_point('ray', 'console_scripts', 'ray')()
  File "/home/admin/.pyenv/versions/3.7.11/envs/3.7.11_ray/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/admin/.pyenv/versions/3.7.11/envs/3.7.11_ray/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/home/admin/.pyenv/versions/3.7.11/envs/3.7.11_ray/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/home/admin/.pyenv/versions/3.7.11/envs/3.7.11_ray/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/admin/code/ray/python/ray/__init__.py", line 110, in <module>
    from ray._private.worker import (  # noqa: E402,F401
  File "/home/admin/code/ray/python/ray/_private/worker.py", line 40, in <module>
    from typing import Literal, Protocol
ImportError: cannot import name 'Literal' from 'typing' (/home/admin/.pyenv/versions/3.7.11/lib/python3.7/typing.py)
```

### Versions / Dependencies

master

### Reproduction script

ray start --head

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by dizhouwu** [comment]
Is this related? https://github.com/ray-project/ray/issues/39395

**Comment by pcmoritz** [comment]
@larrylian You are probably using the code from Ray master here, right? As stated above, we are discontinuing Python 3.7 support for Ray 2.8 (similar to many other libraries in the Python ecosystem, since Python 3.7 is EOL). Since Ray 3.8 will be released from current master, we are already cleaning up the code in current master.

Python 3.7 will continue to work for older Ray releases <= 2.7 :)

**Comment by larrylian** [comment]
@pcmoritz  @gresavage   Thanks, I will upgrade my python version to 3.8.x
