### ISSUE TITLE
Ray Serve Example not working "KeyError: 'Request ID ... not found.'"

### ISSUE THREAD

**Issue by rk0n** [ray-project/ray#40499]
### What happened + What you expected to happen

I try to run the serve example from the docs https://docs.ray.io/en/latest/serve/tutorials/rllib.html.

But I get:

```bash
(ServeReplica:default:ServePPOModel pid=2194460) ray.exceptions.RayTaskError(KeyError): ray::HTTPProxyActor.receive_asgi_messages() (pid=2194384, ip=192.168.1.2, actor_id=e87c6a2cf308788f513b2d5201000000, repr=<ray.serve._private.http_proxy.HTTPProxyActor object at 0x7fea0f145b50>)
(ServeReplica:default:ServePPOModel pid=2194460)   File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
(ServeReplica:default:ServePPOModel pid=2194460)     return self.__get_result()
(ServeReplica:default:ServePPOModel pid=2194460)            ^^^^^^^^^^^^^^^^^^^
(ServeReplica:default:ServePPOModel pid=2194460)   File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
(ServeReplica:default:ServePPOModel pid=2194460)     raise self._exception
(ServeReplica:default:ServePPOModel pid=2194460)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(ServeReplica:default:ServePPOModel pid=2194460)   File "/home/project/.venv/lib/python3.11/site-packages/ray/serve/_private/http_proxy.py", line 1692, in receive_asgi_messages
(ServeReplica:default:ServePPOModel pid=2194460)     return pickle.dumps(await self.http_proxy.receive_asgi_messages(request_id))
(ServeReplica:default:ServePPOModel pid=2194460)                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(ServeReplica:default:ServePPOModel pid=2194460)   File "/home/project/.venv/lib/python3.11/site-packages/ray/serve/_private/http_proxy.py", line 1001, in receive_asgi_messages
(ServeReplica:default:ServePPOModel pid=2194460)     raise KeyError(f"Request ID {request_id} not found.")
(ServeReplica:default:ServePPOModel pid=2194460) KeyError: 'Request ID 00a0f8d9-4c81-4622-bfda-60f921e97fb7 not found.'
(ServeReplica:default:ServePPOModel pid=2194460) INFO 2023-10-19 11:07:13,238 ServePPOModel default#ServePPOModel#kBivAl 00a0f8d9-4c81-4622-bfda-60f921e97fb7 / default replica.py:749 - __CALL__ ERROR 5.6ms
(ServeReplica:default:ServePPOModel pid=2194460) Traceback (most recent call last):
```

When I try to debug I can see that the call function never goes behind response.json().

Downgrading to Python 3.10.13 fixes the problem

### Versions / Dependencies

ray 2.7.1 with python 3.11.5

### Reproduction script

```python
import ray.rllib.algorithms.ppo as ppo
from ray import serve
from starlette.requests import Request


@serve.deployment
class ServePPOModel:
    def __init__(self, checkpoint_path) -> None:
        # Re-create the originally used config.
        config = ppo.PPOConfig()\
            .framework("tf")\
            .rollouts(num_rollout_workers=0)
        # Build the Algorithm instance using the config.
        self.algorithm = config.build(env="CartPole-v1")
        # Restore the algo's state from the checkpoint.
        self.algorithm.restore(checkpoint_path)

    async def __call__(self, request: Request):
        json_input = await request.json()
        obs = json_input["observation"]

        action = self.algorithm.compute_single_action(obs)
        return {"action": int(action)}


if __name__ == '__main__':
    def train_ppo_model():
        # Configure our PPO algorithm.
        config = (
            ppo.PPOConfig()
            .environment("CartPole-v1")
            .framework("tf")
            .rollouts(num_rollout_workers=0)
        )
        # Create a `PPO` instance from the config.
        algo = config.build()
        # Train for one iteration.
        algo.train()
        # Save state of the trained Algorithm in a checkpoint.
        checkpoint_dir = algo.save("/mnt/workdisk/traintest")
        return checkpoint_dir

    import os
    path = train_ppo_model()
    checkpoint_path = path
    ppo_model = ServePPOModel.bind(checkpoint_path)
    serve.run(ppo_model)
    # Note: `gymnasium` (not `gym`) will be **the** API supported by RLlib from Ray 2.3 on.
    try:
        import gymnasium as gym

        gymnasium = True
    except Exception:
        import gym

        gymnasium = False

    import requests

    env = gym.make("CartPole-v1")

    for _ in range(5):
        if gymnasium:
            obs, infos = env.reset()
        else:
            obs = env.reset()

        print(f"-> Sending observation {obs}")
        resp = requests.get(
            "http://localhost:8000/", json={"observation": obs.tolist()}
        )
        print(f"<- Received response {resp.json()}")        
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by GeneDer** [comment]
@rk0n thanks for reporting this issue. At the moment python 3.11 support is still in experimental. Will add this to the todo when we productionize python 3.11 support in the near future

**Comment by sfrolich** [comment]
Python 3.12 is out now too. Might want to test that also.

**Comment by rickyyx** [comment]
https://ray-distributed.slack.com/archives/CNCKBBRJL/p1700162038008149?thread_ts=1697707213.372609&cid=CNCKBBRJL 

Looks might not be a python version thing.

**Comment by anyscalesam** [comment]
@rk0n  can you please test on latest ray versions that have python 311 and 312 support?
