### ISSUE TITLE
[Ray Data] RuntimeError: cannot join thread before it is started

### ISSUE THREAD

**Issue by charu-vl** [ray-project/ray#40594]
### What happened + What you expected to happen

Hi folks, we are running into this error with Ray Data when trying to run a large backfill.
The job seems to die with this error (commented below), not sure why there would be a timeout issue with retrieving the data. Any thoughts on why this could be?

When we run the job with 128 workers, we get the error below. When we reduce that to 32 workers, it seems to work without failing. I'm wondering why the worker reduction helps. The data is barely taking up any of the object store memory: 
<img width="569" alt="image" src="https://github.com/ray-project/ray/assets/118397827/4116834e-98dd-4a39-b69c-b787a6bf05c0">

```
Traceback (most recent call last):
  File "/tmp/ray/session_2023-10-12_11-34-58_162249_8/runtime_resources/working_dir_files/_ray_pkg_d411241c8e01325c/batch/bge-backfill/download.py", line 58, in <module>
    predictions.write_parquet("s3://ml-batch-scratch/message_embeddings/")
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/dataset.py", line 2720, in write_parquet
    self.write_datasource(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/dataset.py", line 3413, in write_datasource
    self._write_ds = Dataset(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/dataset.py", line 4713, in materialize
    copy._plan.execute(force_read=True)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/plan.py", line 591, in execute
    blocks = execute_to_legacy_block_list(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/legacy_compat.py", line 118, in execute_to_legacy_block_list
    bundles = executor.execute(dag, initial_stats=stats)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py", line 103, in execute
    self._topology, _ = build_streaming_topology(dag, self._options)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor_state.py", line 300, in build_streaming_topology
    setup_state(dag)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor_state.py", line 291, in setup_state
    parent_state = setup_state(parent)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor_state.py", line 297, in setup_state
    op.start(options)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/operators/actor_pool_map_operator.py", line 109, in start
    ray.get(refs, timeout=DEFAULT_WAIT_FOR_MIN_ACTORS_SEC)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/worker.py", line 2541, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/worker.py", line 756, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 3110, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 447, in ray._raylet.check_status
ray.exceptions.GetTimeoutError: Get timed out: some object(s) not ready.
Exception ignored in: <function StreamingExecutor.__del__ at 0x7fbfe0300280>
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py", line 147, in __del__
    self.shutdown()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py", line 160, in shutdown
    self.join(timeout=2.0)
  File "/home/ray/anaconda3/lib/python3.9/threading.py", line 1055, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started
```

### Versions / Dependencies

Ray 2.7.0

### Reproduction script

```

dataset = ray.data.read_sql(read_query('get-export.sql'), create_connection)

predictions = dataset.map_batches(
    YourModel,
    compute=ray.data.ActorPoolStrategy(size=POOL_SIZE),
    num_cpus=2,
    batch_size=BATCH_SIZE
)

predictions.write_parquet("your/s3/path")
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by raulchen** [comment]
>   File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/operators/actor_pool_map_operator.py", line 109, in start
    ray.get(refs, timeout=DEFAULT_WAIT_FOR_MIN_ACTORS_SEC)
    
This error means that the not all actors have started within the 10 minutes timeout. 
It's mostly likely because you don't have enough resources for the requested actor pool.

**Comment by raulchen** [comment]
Created an issue to optimize the error message https://github.com/ray-project/ray/issues/40600.
Closing this issue for now. Feel free to reopen if there are other issues.

**Comment by one-matrix** [comment]
the GPU resources not enough, you can set num_cpus=0.2
