### ISSUE TITLE
[data] when the map_batches used with a callable class, fn_args and fn_kwargs are not available.

### ISSUE THREAD

**Issue by MissiontoMars** [ray-project/ray#40613]
### What happened + What you expected to happen

I am a bit confused about the fn_args and fn_kwargs parameters of the map_batches API. What happens if a class is passed as the fn argument? I noticed that it throws an error.

If the fn_args and fn_kwargs parameters are not supported, they should be intercepted in the map_batches function.

### Versions / Dependencies

ray 2.7

### Reproduction script

```
import ray

ray.init(include_dashboard=True)


# Test class
class CachedModel:
    def __init__(self, param):
        self.init_large_model(param)
        self.count = 0

    def init_large_model(self, param):
        import time
        print(f'init_large_model {param}')
        time.sleep(5)
        print('init_large_model done')

    def model(self, x, *args):
        print(f'model is called {type(x)} {args}.')
        import time
        #time.sleep(1)
        return x

    def __call__(self, item):
        if self.count % 10 == 0:
            print('CachedModel __call__ is called.')
        self.count += 1
        return self.model(item)

ds = ray.data.read_parquet('./parquet_files/', parallelism=5)
ds = ds.map_batches(CachedModel, batch_size=None,
                    compute=ray.data.ActorPoolStrategy(min_size=5, max_size=5),
                    fn_args=(1,2,3,),
                    fn_constructor_args=(100,))
ds.write_parquet(f'./model_results/')

print('DONE')
```

2023-10-24 10:45:42,809 WARNING actor_pool_map_operator.py:275 -- To ensure full parallelization across an actor pool of size 5, the Dataset should consist of at least 5 distinct blocks. Consider increasing the parallelism when creating the Dataset.
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 345, in ray._raylet.StreamingObjectRefGenerator._next_sync
    # TODO(swang): Avoid fetching the value.
  File "python/ray/_raylet.pyx", line 4533, in ray._raylet.CoreWorker.try_read_next_object_ref_stream
  File "python/ray/_raylet.pyx", line 443, in ray._raylet.check_status
    return data_metadata_pairs
ray.exceptions.ObjectRefStreamEndOfStreamError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/_internal/execution/interfaces/physical_operator.py", line 80, in on_waitable_ready
    meta = ray.get(next(self._streaming_gen))
  File "python/ray/_raylet.pyx", line 300, in ray._raylet.StreamingObjectRefGenerator.__next__
    if len(unready) > 0:
  File "python/ray/_raylet.pyx", line 363, in ray._raylet.StreamingObjectRefGenerator._next_sync
    # In that case, it should raise StopIteration.
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wanxing/work/code/inf_ray/./mytest/issue_map_batches.py", line 35, in <module>
    ds.write_parquet(f'/Users/wanxing/work/code/inf_ray/model_results/')
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/dataset.py", line 2720, in write_parquet
    self.write_datasource(
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/dataset.py", line 3413, in write_datasource
    self._write_ds = Dataset(
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/dataset.py", line 4713, in materialize
    copy._plan.execute(force_read=True)
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/_internal/plan.py", line 591, in execute
    blocks = execute_to_legacy_block_list(
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/_internal/execution/legacy_compat.py", line 119, in execute_to_legacy_block_list
    block_list = _bundles_to_block_list(bundles)
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/_internal/execution/legacy_compat.py", line 357, in _bundles_to_block_list
    for ref_bundle in bundles:
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/_internal/execution/interfaces/executor.py", line 37, in __next__
    return self.get_next()
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py", line 129, in get_next
    raise item
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py", line 187, in run
    while self._scheduling_loop_step(self._topology) and not self._shutdown:
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor.py", line 235, in _scheduling_loop_step
    process_completed_tasks(topology)
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/_internal/execution/streaming_executor_state.py", line 333, in process_completed_tasks
    active_tasks[ref].on_waitable_ready()
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/_internal/execution/interfaces/physical_operator.py", line 88, in on_waitable_ready
    ex = ray.get(block_ref)
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/_private/worker.py", line 2547, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::ReadParquet->MapBatches(CachedModel)() (pid=96105, ip=127.0.0.1, actor_id=6d3e82ba5a9c51c4e25b285f01000000, repr=MapWorker(ReadParquet->MapBatches(CachedModel)))
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/_internal/execution/operators/actor_pool_map_operator.py", line 377, in submit
    yield from _map_task(self._map_transformer, data_context, ctx, *blocks)
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 405, in _map_task
    for b_out in map_transformer.apply_transform(iter(blocks), ctx):
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_transformer.py", line 345, in __call__
    for data in iter:
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_transformer.py", line 190, in __call__
    yield from self._batch_fn(input, ctx)
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/_internal/planner/plan_udf_map_op.py", line 189, in transform_fn
    res = fn(batch)
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/_internal/planner/plan_udf_map_op.py", line 107, in fn
    return ray.data._cached_fn(item, *fn_args, **fn_kwargs)
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/site-packages/ray/data/_internal/execution/util.py", line 75, in __call__
    return future.result()
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/wanxing/miniforge3/envs/ray-inf-2.7/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: __call__() takes 2 positional arguments but 5 were given

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by MissiontoMars** [comment]
@raulchen
