### ISSUE TITLE
Possible bug in ApexDDPGAgent with 2 GPUs and 20 workers

### ISSUE THREAD

**Issue by yangpeiren** [ray-project/ray#4064]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.3
- **Python version**: 3.5.6
- **Exact command to reproduce**:  python xxx.py

### Describe the problem

I have a machine with 2 GPUs, and a 32 core CPU, so I would like to use ApexDDPG with TD3 active to train my agent, but with 2 GPUs and 20 workers, the Redis server refuses to connect to, which is really a strange problem.

If I change the worker number to 18 or 24, as long as not 20, the Redis server could be connected, I thought it was something wrong with those IP ports, and tried lots of trouble-shooting methods including reboot the machine, until I changed the number.

Could anyone find out why it is like this, and is there any other coincident number of workers which could cause the same problem? Thanks a lot.

#### Error Stack partially

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/ray/workers/default_worker.py", line 91, in <module>
    ray.worker.global_worker.main_loop()
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/ray/worker.py", line 974, in main_loop
    self._wait_for_and_process_task(task)
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/ray/worker.py", line 896, in _wait_for_and_process_task
    function_descriptor)
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/ray/function_manager.py", line 566, in load_actor
    self.fetch_and_register_actor(key)
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/ray/function_manager.py", line 644, in fetch_and_register_actor
    traceback_str), driver_id)
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/ray/utils.py", line 66, in push_error_to_driver
    time.time())
  File "_raylet.pyx", line 254, in ray._raylet.RayletClient.push_error
  File "_raylet.pyx", line 46, in ray._raylet.check_status
Exception: [RayletClient] Connection closed unexpectedly.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/ray/workers/default_worker.py", line 98, in <module>
    driver_id=None)
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/ray/utils.py", line 66, in push_error_to_driver
    time.time())
  File "_raylet.pyx", line 254, in ray._raylet.RayletClient.push_error
  File "_raylet.pyx", line 46, in ray._raylet.check_status
Exception: [RayletClient] Connection closed unexpectedly.
Traceback (most recent call last):
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/redis/connection.py", line 184, in _read_from_socket
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/redis/client.py", line 755, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/redis/client.py", line 768, in parse_response
    response = connection.read_response()
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/redis/connection.py", line 636, in read_response
    raise e
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/redis/connection.py", line 633, in read_response
    response = self._parser.read_response()
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/redis/connection.py", line 291, in read_response
    response = self._buffer.readline()
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/redis/connection.py", line 223, in readline
    self._read_from_socket()
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/redis/connection.py", line 198, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/redis/connection.py", line 493, in connect
    sock = self._connect()
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/redis/connection.py", line 550, in _connect
    raise err
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/redis/connection.py", line 538, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/ray/function_manager.py", line 632, in fetch_and_register_actor
    unpickled_class = pickle.loads(pickled_class)
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/ray/rllib/__init__.py", line 43, in <module>
    _register_all()
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/ray/rllib/__init__.py", line 39, in _register_all
    register_trainable(key, get_agent_class(key))
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/ray/tune/registry.py", line 49, in register_trainable
    _global_registry.register(TRAINABLE_CLASS, name, trainable)
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/ray/tune/registry.py", line 90, in register
    self.flush_values()
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/ray/tune/registry.py", line 112, in flush_values
    _internal_kv_put(_make_key(category, key), value, overwrite=True)
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/ray/experimental/internal_kv.py", line 42, in _internal_kv_put
    updated = worker.redis_client.hset(key, "value", value)
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/ray/utils.py", line 452, in _wrapper
    return orig_attr(*args, **kwargs)
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/redis/client.py", line 2617, in hset
    return self.execute_command('HSET', name, key, value)
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/redis/client.py", line 760, in execute_command
    connection.send_command(*args)
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/home/yang_local/anaconda3/envs/ML/lib/python3.5/site-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:52897. Connection refused.

### Source code / logs

Here is the source code which could reproduce the error on a machine with 2 GPUs:

```python
import ray
import ray.tune as tune
from ray.rllib.agents.ddpg import ApexDDPGAgent
import gym


class TestEnv(gym.Env):
    def __init__(self, env_config):
        self.env = gym.make('MountainCarContinuous-v0')
        self.action_space = self.env.action_space
        self.observation_space = self.env.observation_space

    def reset(self):
        return self.env.reset()

    def step(self, action):
        return self.env.step(action)


def env_creator(env_config):
    return TestEnv(env_config)


tune.registry.register_env("testenv", env_creator)


if __name__ == '__main__':

    ray.init()

    agent = ApexDDPGAgent(env='testenv', config={
        'num_workers': 20,

        'env_config': {},

        'twin_q': True,
        'policy_delay': 2,
        'smooth_target_policy': True,

        'actor_hiddens': [256, 128],
        'critic_hiddens': [256, 128],

        'timesteps_per_iteration': 600,
        'target_network_update_freq': 10000,
        'tau': 1e-3,

        'buffer_size': 20000,
        'prioritized_replay': True,

        'learning_starts': 10000,
        'sample_batch_size': 50,
        'train_batch_size': 64,

        'num_gpus': 2,
        'num_gpus_per_worker': 2 / 20,

        'compress_observations': True,
    })

    for i in range(10000):
        agent.train()

```

**Comment by ericl** [comment]
I suspect you're running out of memory or something like that. I would try running in Tune, that gives much better messages for misconfigured resources.

Also, multiple GPUs don't work in Apex, and workers don't need GPUs, so I would do set num_gpus:1, num_gpus_per_worker:0.

**Comment by yangpeiren** [comment]
Thanks for your reply. 

Yes, given multiple GPUs to DDPGAgent is meaningless after reading the code of async replay optimizer. As I was working with PPO before and did not get satisfied results, I switched to DDPG without checking the optimizer carefully.

But multiple GPUs do work in Apex **(although meaningless)** since my program works with num_workers:32, num_gpus:2, num_gpus_per_worker: 2/32, and even with 32 workers, the RAM consumption is below 50G (my machine has 93G).

So 20 is a magic number which could trigger this problem with num_gpus:2, but it is an abnormal case in an abnormal use scenario, so I think it is also not worth to report it anymore, issue is closed.

Thanks again for your time!
