### ISSUE TITLE
[Dashboard] Cannot load `Jobs` tab 

### ISSUE THREAD

**Issue by spolcyn** [ray-project/ray#40660]
### What happened + What you expected to happen

1. While the Ray Dashboard loads, the `Jobs` tab doesn't load any jobs and continues spinning indefinitely (10+ minutes). The `Cluster` tab also does not update, and is stuck on a previous cluster state.
2. The `Jobs` tab should load the past and present jobs and the `Cluster` tab should reflect the current cluster state
3. In `dashboard.log`, the same message with the same nodes continuously repeats:
```
2023-10-25 14:45:50,679 ERROR node_head.py:380 -- Cannot reach the node, c309289356e41261567628f5bed341f3c191af458ebd37a239288bf6. The node may have been terminated.
NoneType: None
2023-10-25 14:45:50,680 ERROR node_head.py:380 -- Cannot reach the node, 362f7a88578199552c5dd6302bb8f89b28338ca77449ae1de5103697. The node may have been terminated.
NoneType: None
2023-10-25 14:45:50,680 ERROR node_head.py:380 -- Cannot reach the node, 454348e0cc99d7df33faa617832795b922bf229b8d140fd9ed1983f8. The node may have been terminated.
NoneType: None
2023-10-25 14:45:50,680 ERROR node_head.py:380 -- Cannot reach the node, 5fd60d59122bcb5e9fd6b3892afc027a686ee955f534ea7bd417f4d3. The node may have been terminated.
NoneType: None
2023-10-25 14:45:50,680 ERROR node_head.py:380 -- Cannot reach the node, 112d4c80c92a2d11da046cdf5036ea0b31c5a0815220b72ee67ae740. The node may have been terminated.
NoneType: None
2023-10-25 14:45:50,680 ERROR node_head.py:380 -- Cannot reach the node, ac10b4c7c228efe3400f0db2534730cf69e590469d2a85e6be57958b. The node may have been terminated.
NoneType: None
2023-10-25 14:45:55,689 ERROR node_head.py:380 -- Cannot reach the node, f06241dba92e6e690243718dc0a9ea27e645faee0f8d90aa945c4886. The node may have been terminated.
NoneType: None
2023-10-25 14:45:55,690 ERROR node_head.py:380 -- Cannot reach the node, 5fb8edbe4eec28d869c73858d9dca3ba830e5bc04be38d52825c8f3e. The node may have been terminated.
NoneType: None
2023-10-25 14:45:55,690 ERROR node_head.py:380 -- Cannot reach the node, 4d198eaba6341fe5d7f9ea57c1af40a05abccefd8d6a3bdc6717e6c0. The node may have been terminated.
NoneType: None
2023-10-25 14:45:55,690 ERROR node_head.py:380 -- Cannot reach the node, 2b152d1afeee788cd5629e3917e9a0c9ac10317127ab8860cd5b0d00. The node may have been terminated.
NoneType: None
2023-10-25 14:45:55,690 ERROR node_head.py:380 -- Cannot reach the node, 9a677902e2a9df8dd130f990d235aa63b88964c233cbf5cc216f015c. The node may have been terminated.
NoneType: None
2023-10-25 14:45:55,690 ERROR node_head.py:380 -- Cannot reach the node, 764c3dae2ce344ec9ef58695bcbbeac6f42397afadc726f7f630e1b6. The node may have been terminated.
NoneType: None
2023-10-25 14:45:55,690 ERROR node_head.py:380 -- Cannot reach the node, c309289356e41261567628f5bed341f3c191af458ebd37a239288bf6. The node may have been terminated.
NoneType: None
2023-10-25 14:45:55,690 ERROR node_head.py:380 -- Cannot reach the node, 362f7a88578199552c5dd6302bb8f89b28338ca77449ae1de5103697. The node may have been terminated.
NoneType: None
2023-10-25 14:45:55,690 ERROR node_head.py:380 -- Cannot reach the node, 454348e0cc99d7df33faa617832795b922bf229b8d140fd9ed1983f8. The node may have been terminated.
NoneType: None

```

Other present errors:
```
2023-10-29 18:14:12,416 ERROR node_head.py:375 -- Cannot reach the node, c0bbcf6a2f45f55ac568aef64fcef6b300ae8a7b16d8e0f1a826df79, after timeout 4. This node may have been overloaded, terminated, or the network is slow.
NoneType: None
2023-10-29 18:14:12,970 ERROR head.py:323 -- Error notifying coroutine <coroutine object Signal.send at 0x7f0558dfcac0>
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/ray/dashboard/head.py", line 321, in _async_notify
    await co
  File "/venv/lib/python3.9/site-packages/aiosignal/__init__.py", line 36, in send
    await receiver(*args, **kwargs)  # type: ignore
  File "/venv/lib/python3.9/site-packages/ray/dashboard/modules/state/state_head.py", line 260, in _update_agent_stubs
    self._state_api_data_source_client.unregister_agent_client(node_id)
  File "/venv/lib/python3.9/site-packages/ray/util/state/state_manager.py", line 220, in unregister_agent_client
    self._id_id_map.pop(node_id)
  File "/venv/lib/python3.9/site-packages/ray/util/state/state_manager.py", line 136, in pop
    assert ip in self._ip_to_node_id
AssertionError
```

### Versions / Dependencies

Python 3.9.10
Ray 2.7.0

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by anyscalesam** [comment]
Reads like something going on with the Job and/or even Core and not necessarily a Dashboard issue (fairly straightforward code path for that...) @sihanwang41 can you take a look first?

**Comment by rkooo567** [comment]
@spolcyn are you guys using Ray HA? 

There have been a bug where HA cluster has slow response time in job page after the head node restarts, but we've fixed that in the master (and Ray 2.8 that will be released this week).

**Comment by rkooo567** [comment]
Also, can you also share

1. the full logs if possible.
2. the way to repro the issue? 

We will assign P1.5 until the questions are resolved

**Comment by spolcyn** [comment]
> @spolcyn are you guys using Ray HA?
> 
> There have been a bug where HA cluster has slow response time in job page after the head node restarts, but we've fixed that in the master (and Ray 2.8 that will be released this week).

1. Ray HA: No, just single head
2. Full logs: That head has been since restarted; would current head logs be helpful, if it's not currently happening?
3. Repro: Haven't found a way to repro it yet

**Comment by rkooo567** [comment]
It's not very helpful if it is not happening. Since we made a potential fix, can you also try ray 2.8 (released in a few days)? If it still happens, we have other root cause in mind. We can prioritize fixing that issue.

**Comment by spolcyn** [comment]
> It's not very helpful if it is not happening. Since we made a potential fix, can you also try ray 2.8 (released in a few days)? If it still happens (though I feel like it should be fixed..), we have other root cause in mind. We can prioritize fixing that issue.

Sure, we'll try Ray 2.8 and see if it pops up again.

**Comment by anyscalesam** [comment]
@spolcyn did your issue show up on latest ray (2.8+)

**Comment by spolcyn** [comment]
This can be closed, I'll open a new issue with new logs if it comes back again
