### ISSUE TITLE
[Core] "Failed to start GCS" / "<jemalloc> Unsupported system page size" when running on certain ARM hardware

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#40815]
### What happened + What you expected to happen

If I run `ray.init()` on certain ARM hardware, I'm getting the following error:

```
python
Python 3.11.5 (main, Sep 11 2023, 13:14:08) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pcmoritz/miniconda3/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pcmoritz/miniconda3/lib/python3.11/site-packages/ray/_private/worker.py", line 1536, in init
    _global_node = ray._private.node.Node(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pcmoritz/miniconda3/lib/python3.11/site-packages/ray/_private/node.py", line 307, in __init__
    self.start_head_processes()
  File "/home/pcmoritz/miniconda3/lib/python3.11/site-packages/ray/_private/node.py", line 1404, in start_head_processes
    assert self.get_gcs_client() is not None
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pcmoritz/miniconda3/lib/python3.11/site-packages/ray/_private/node.py", line 676, in get_gcs_client
    self._init_gcs_client()
  File "/home/pcmoritz/miniconda3/lib/python3.11/site-packages/ray/_private/node.py", line 721, in _init_gcs_client
    raise RuntimeError(
RuntimeError: Failed to start GCS.  Last 0 lines of error files:

.Please check /tmp/ray/session_2023-10-30_15-21-20_500283_661751/logs/gcs_server.out for details
```

and the `gcs_server.err` log file contains the following error:
```
<jemalloc> Unsupported system page size
```

This happens for example on Nvidia's GH200 architecture.

### Versions / Dependencies

Ray 2.7.1 and master

### Reproduction script

See above

### Issue Severity

High: It blocks me from completing my task.

**Comment by anyscalesam** [comment]
@rkooo567 can you take a look at the PR in progress that @pcmoritz cut so we can close this out; it's failing on couple of tests.

**Comment by KastanDay** [comment]
Running Ray on [Railway.app](https://railway.app/), which means **I'm inside a docker (or really `nixpacks`) container**, I hit a similar issue:

```
2023-11-02 20:12:39,831	INFO usage_lib.py:416 -- Usage stats collection is enabled by default without user confirmation because this terminal is detected to be non-interactive. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.
2023-11-02 20:12:39,832	INFO scripts.py:744 -- Local node IP: 172.17.1.43
Traceback (most recent call last):
File "/opt/venv/bin/ray", line 8, in <module>
sys.exit(main())
File "/opt/venv/lib/python3.10/site-packages/ray/scripts/scripts.py", line 2498, in main
return cli()
File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
File "/opt/venv/lib/python3.10/site-packages/ray/autoscaler/_private/cli_logger.py", line 856, in wrapper
return f(*args, **kwargs)
File "/opt/venv/lib/python3.10/site-packages/ray/scripts/scripts.py", line 771, in start
node = ray._private.node.Node(
File "/opt/venv/lib/python3.10/site-packages/ray/_private/node.py", line 307, in __init__
self.start_head_processes()
File "/opt/venv/lib/python3.10/site-packages/ray/_private/node.py", line 1404, in start_head_processes
assert self.get_gcs_client() is not None
File "/opt/venv/lib/python3.10/site-packages/ray/_private/node.py", line 676, in get_gcs_client
self._init_gcs_client()
File "/opt/venv/lib/python3.10/site-packages/ray/_private/node.py", line 721, in _init_gcs_client
raise RuntimeError(
RuntimeError: Failed to start GCS.  Last 0 lines of error files:
```

Any advice here? Thanks.

**Comment by anyscalesam** [comment]
Re-assigning to @rynewang as this is P0 to please review for next steps.
