### ISSUE TITLE
[data] example does not work

### ISSUE THREAD

**Issue by rynewang** [ray-project/ray#40865]
### What happened + What you expected to happen

I am following https://docs.ray.io/en/latest/data/examples/nyc_taxi_basic_processing.html and got error when I am doing `ds.map_batches`.

### Versions / Dependencies

Nightly (3.0.0dev0)
10f40080660fa83d7ebdd3d4fc49bcffffcf6461
https://console.anyscale-staging.com/o/anyscale-internal/workspaces/expwrk_3pnm7sz7fv14848lqkmqjxpip6/ses_a6nt67dujsuxl8pef465a88klh

### Reproduction script

This works:

```
# Read two Parquet files in parallel.
ds = ray.data.read_parquet([
    "s3://anonymous@air-example-data/ursa-labs-taxi-data/downsampled_2009_01_data.parquet",
    "s3://anonymous@air-example-data/ursa-labs-taxi-data/downsampled_2009_02_data.parquet"
])
ds = ds.drop_columns(["store_and_fwd_flag", "mta_tax"])
ds.take(2)
```

This fails:

```
# Read two Parquet files in parallel.
ds = ray.data.read_parquet([
    "s3://anonymous@air-example-data/ursa-labs-taxi-data/downsampled_2009_01_data.parquet",
    "s3://anonymous@air-example-data/ursa-labs-taxi-data/downsampled_2009_02_data.parquet"
])
ds = ds.drop_columns(["store_and_fwd_flag", "mta_tax"])
ds = ds.map_batches(lambda df: df[df["passenger_count"] > 0])
ds.take(2)
```

With error message : 
```
---------------------------------------------------------------------------
ObjectRefStreamEndOfStreamError           Traceback (most recent call last)
File python/ray/_raylet.pyx:347, in ray._raylet.StreamingObjectRefGenerator._next_sync()

File python/ray/_raylet.pyx:4646, in ray._raylet.CoreWorker.try_read_next_object_ref_stream()

File python/ray/_raylet.pyx:447, in ray._raylet.check_status()

ObjectRefStreamEndOfStreamError: 

During handling of the above exception, another exception occurred:

StopIteration                             Traceback (most recent call last)
File ~/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/interfaces/physical_operator.py:80, in DataOpTask.on_data_ready(self, max_blocks_to_read)
     79 try:
---> 80     meta = ray.get(next(self._streaming_gen))
     81 except StopIteration:
     82     # The generator should always yield 2 values (block and metadata)
     83     # each time. If we get a StopIteration here, it means an error
   (...)
     86     # TODO(hchen): Ray Core should have a better interface for
     87     # detecting and obtaining the exception.

File python/ray/_raylet.pyx:302, in ray._raylet.StreamingObjectRefGenerator.__next__()

File python/ray/_raylet.pyx:353, in ray._raylet.StreamingObjectRefGenerator._next_sync()

StopIteration
```
... up to the worker error ...

```
   2572     raise value

RayTaskError(TypeError): ray::MapBatches(<lambda>)->MapBatches(<lambda>)() (pid=2800, ip=10.0.255.88)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 416, in _map_task
    for b_out in map_transformer.apply_transform(iter(blocks), ctx):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_transformer.py", line 371, in __call__
    for data in iter:
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_transformer.py", line 215, in __call__
    yield from self._batch_fn(input, ctx)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/planner/plan_udf_map_op.py", line 190, in transform_fn
    res = fn(batch)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/planner/plan_udf_map_op.py", line 120, in fn
    return op_fn(item, *fn_args, **fn_kwargs)
  File "/tmp/ipykernel_2218/1635213953.py", line 1, in <lambda>
TypeError: unhashable type: 'numpy.ndarray'

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by wingkitlee0** [comment]
```
 ds.map_batches(lambda df: df[df["passenger_count"] > 0])
```
The example was outdated. You will need to add `batch_format="pandas"` to `map_batches` as the mapping function is a pandas one.

**Comment by bveeramani** [comment]
Closing this issue because this example was removed on master. 

See #40127
