### ISSUE TITLE
raylet will keep resubmitting actor creation tasks that kill the process

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#4086]
### Describe the problem
Actor creation tasks that fail with process death keep getting resubmitted. This seems to be existing behavior at least of 0.6.1, but is probably undesirable. Note that when processes are killed *after* actor creation, then you get a proper error.

### Source code / logs
```
2019-02-18 00:13:34,646	INFO policy_evaluator.py:273 -- Creating policy evaluation worker 0 on CPU (please ignore any CUDA init errors)
2019-02-18 00:13:34.647063: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Hello there
Exception ignored in: <bound method PolicyEvaluator.__del__ of <ray.rllib.evaluation.policy_evaluator.PolicyEvaluator object at 0x7f049230a3c8>>
Traceback (most recent call last):
  File "/home/eric/Desktop/ray-private/python/ray/rllib/evaluation/policy_evaluator.py", line 659, in __del__
    if isinstance(self.sampler, AsyncSampler):
AttributeError: 'PolicyEvaluator' object has no attribute 'sampler'
I0218 00:13:34.663576 31281 store.cc:594] Disconnecting client on fd 12
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0218 00:14:04.663816 31282 node_manager.cc:1947] Resubmitting task 00000000fbe7494eed09ebf1283eef1daa2a72bc on client 9472d94315e5daac348d943c9abd511fe0ed5c90
2019-02-18 00:14:14,076	INFO policy_evaluator.py:273 -- Creating policy evaluation worker 0 on CPU (please ignore any CUDA init errors)
2019-02-18 00:14:14.076872: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Hello there
Exception ignored in: <bound method PolicyEvaluator.__del__ of <ray.rllib.evaluation.policy_evaluator.PolicyEvaluator object at 0x7f99e847d198>>
Traceback (most recent call last):
  File "/home/eric/Desktop/ray-private/python/ray/rllib/evaluation/policy_evaluator.py", line 659, in __del__
    if isinstance(self.sampler, AsyncSampler):
AttributeError: 'PolicyEvaluator' object has no attribute 'sampler'
I0218 00:14:14.094251 31281 store.cc:594] Disconnecting client on fd 15
I0218 00:14:54.095464 31282 node_manager.cc:1947] Resubmitting task 00000000fbe7494eed09ebf1283eef1daa2a72bc on client 9472d94315e5daac348d943c9abd511fe0ed5c90
2019-02-18 00:15:03,268	INFO policy_evaluator.py:273 -- Creating policy evaluation worker 0 on CPU (please ignore any CUDA init errors)
2019-02-18 00:15:03.269160: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Hello there
Exception ignored in: <bound method PolicyEvaluator.__del__ of <ray.rllib.evaluation.policy_evaluator.PolicyEvaluator object at 0x7ff731b36208>>
Traceback (most recent call last):
  File "/home/eric/Desktop/ray-private/python/ray/rllib/evaluation/policy_evaluator.py", line 659, in __del__
    if isinstance(self.sampler, AsyncSampler):
AttributeError: 'PolicyEvaluator' object has no attribute 'sampler'
I0218 00:15:03.281946 31281 store.cc:594] Disconnecting client on fd 14
I0218 00:15:53.282481 31282 node_manager.cc:1947] Resubmitting task 00000000fbe7494eed09ebf1283eef1daa2a72bc on client 9472d94315e5daac348d943c9abd511fe0ed5c90
2019-02-18 00:16:02,723	INFO policy_evaluator.py:273 -- Creating policy evaluation worker 0 on CPU (please ignore any CUDA init errors)
2019-02-18 00:16:02.724033: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Hello there
Exception ignored in: <bound method PolicyEvaluator.__del__ of <ray.rllib.evaluation.policy_evaluator.PolicyEvaluator object at 0x7fe2074624e0>>
Traceback (most recent call last):
  File "/home/eric/Desktop/ray-private/python/ray/rllib/evaluation/policy_evaluator.py", line 659, in __del__
    if isinstance(self.sampler, AsyncSampler):
AttributeError: 'PolicyEvaluator' object has no attribute 'sampler'
I0218 00:16:02.736913 31281 store.cc:594] Disconnecting client on fd 16
```

cc @raulchen @stephanie-wang

**Comment by raulchen** [comment]
Thanks, I'll take a look.
