### ISSUE TITLE
[core] serious memory leak with no activity

### ISSUE THREAD

**Issue by karrdy89** [ray-project/ray#41148]
### What happened + What you expected to happen

1. the bug:  There is a ray node running on the container, which is launched simply by Python script containing the ray.init() code by executing python3 -i command. 
After this container starts, the memory usage gradually increases, but the dashboard agent is killed by oom and the memory usage stabilizes.

2. expected behavior: Memory must be stable when idle.

3. useful information:
![image](https://github.com/ray-project/ray/assets/42703908/be86c8f9-be8d-404c-bd29-4917b2ef6ee5)
memory usage increased 125.9Gib -> 134.2Gib for 15 minutes and continued to increase until OOM.
The situation when OOM occurred yesterday is as follows.
```
2023-11-14 15:10:56,017 WARNING utils.py:581 -- Detecting docker specified CPUs. In previous versions of Ray, CPU detection in containers was incorrect. Please ensure that Ray has enough CPUs allocated. As a temporary workaround to revert to the prior behavior, set `RAY_USE_MULTIPROCESSING_CPU_COUNT=1` as an env var before starting Ray. Set the env var: `RAY_DISABLE_DOCKER_CPU_WARNING=1` to mute this warning.
2023-11-14 15:10:56,018 WARNING services.py:1996 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=0.64gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2023-11-14 15:10:57,133 INFO worker.py:1664 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
>>> (raylet) [2023-11-14 19:18:32,756 E 97 138] (raylet) agent_manager.cc:70: The raylet exited immediately because one Ray agent failed, agent_name = dashboard_agent/424238335.
(raylet) The raylet fate shares with the agent. This can happen because
(raylet) - The version of `grpcio` doesn't follow Ray's requirement. Agent can segfault with the incorrect `grpcio` version. Check the grpcio version `pip freeze | grep grpcio`.
(raylet) - The agent failed to start because of unexpected error or port conflict. Read the log `cat /tmp/ray/session_latest/logs/{dashboard_agent|runtime_env_agent}.log`. You can find the log file structure here https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure.
(raylet) - The agent is killed by the OS (e.g., out of memory).
```
dashboard_agent.log
```
root@c2a32daebf44:/home/xflow/app# cat tmp/ray/session_latest/logs/dashboard_agent.log
cat: tmp/ray/session_latest/logs/dashboard_agent.log: No such file or directory
root@c2a32daebf44:/home/xflow/app# cat ray/session_latest/logs/dashboard_agent.log
2023-11-14 15:10:58,926 INFO agent.py:145 -- Dashboard agent grpc address: 0.0.0.0:60204
2023-11-14 15:10:58,927 INFO utils.py:112 -- Get all modules by type: DashboardAgentModule
2023-11-14 15:10:59,341 INFO utils.py:145 -- Available modules: [<class 'ray.dashboard.modules.event.event_agent.EventAgent'>, <class 'ray.dashboard.modules.healthz.healthz_agent.HealthzAgent'>, <class 'ray.dashboard.modules.job.job_agent.JobAgent'>, <class 'ray.dashboard.modules.log.log_agent.LogAgent'>, <class 'ray.dashboard.modules.log.log_agent.LogAgentV1Grpc'>, <class 'ray.dashboard.modules.reporter.reporter_agent.ReporterAgent'>, <class 'ray.dashboard.modules.serve.serve_rest_api_impl.create_serve_rest_api.<locals>.ServeRestApiImpl'>]
2023-11-14 15:10:59,341 INFO agent.py:161 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.event.event_agent.EventAgent'>
2023-11-14 15:10:59,341 INFO event_agent.py:38 -- Event agent cache buffer size: 10240
2023-11-14 15:10:59,341 INFO agent.py:161 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.healthz.healthz_agent.HealthzAgent'>
2023-11-14 15:10:59,342 INFO agent.py:161 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.job.job_agent.JobAgent'>
2023-11-14 15:10:59,342 INFO agent.py:161 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.log.log_agent.LogAgent'>
2023-11-14 15:10:59,342 INFO agent.py:161 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.log.log_agent.LogAgentV1Grpc'>
2023-11-14 15:10:59,342 INFO agent.py:161 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.reporter.reporter_agent.ReporterAgent'>
2023-11-14 15:10:59,408 INFO agent.py:161 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.serve.serve_rest_api_impl.create_serve_rest_api.<locals>.ServeRestApiImpl'>
2023-11-14 15:10:59,408 INFO agent.py:166 -- Loaded 7 modules.
2023-11-14 15:10:59,411 INFO http_server_agent.py:71 -- Dashboard agent http address: 0.0.0.0:52365
2023-11-14 15:10:59,411 INFO http_server_agent.py:78 -- <ResourceRoute [GET] <PlainResource  /api/local_raylet_healthz> -> <function HealthzAgent.health_check at 0x7fb65c688ea0>
2023-11-14 15:10:59,411 INFO http_server_agent.py:78 -- <ResourceRoute [OPTIONS] <PlainResource  /api/local_raylet_healthz> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7fb65c295e10>>
2023-11-14 15:10:59,411 INFO http_server_agent.py:78 -- <ResourceRoute [POST] <PlainResource  /api/job_agent/jobs/> -> <function JobAgent.submit_job at 0x7fb65c6c44a0>
2023-11-14 15:10:59,411 INFO http_server_agent.py:78 -- <ResourceRoute [OPTIONS] <PlainResource  /api/job_agent/jobs/> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7fb65c295e10>>
2023-11-14 15:10:59,411 INFO http_server_agent.py:78 -- <ResourceRoute [POST] <DynamicResource  /api/job_agent/jobs/{job_or_submission_id}/stop> -> <function JobAgent.stop_job at 0x7fb65c6c63e0>
2023-11-14 15:10:59,411 INFO http_server_agent.py:78 -- <ResourceRoute [OPTIONS] <DynamicResource  /api/job_agent/jobs/{job_or_submission_id}/stop> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7fb65c295e10>>
2023-11-14 15:10:59,411 INFO http_server_agent.py:78 -- <ResourceRoute [DELETE] <DynamicResource  /api/job_agent/jobs/{job_or_submission_id}> -> <function JobAgent.delete_job at 0x7fb65c6c65c0>
2023-11-14 15:10:59,411 INFO http_server_agent.py:78 -- <ResourceRoute [OPTIONS] <DynamicResource  /api/job_agent/jobs/{job_or_submission_id}> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7fb65c295e10>>
2023-11-14 15:10:59,411 INFO http_server_agent.py:78 -- <ResourceRoute [GET] <DynamicResource  /api/job_agent/jobs/{job_or_submission_id}/logs> -> <function JobAgent.get_job_logs at 0x7fb65c6c67a0>
2023-11-14 15:10:59,411 INFO http_server_agent.py:78 -- <ResourceRoute [OPTIONS] <DynamicResource  /api/job_agent/jobs/{job_or_submission_id}/logs> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7fb65c295e10>>
2023-11-14 15:10:59,411 INFO http_server_agent.py:78 -- <ResourceRoute [GET] <DynamicResource  /api/job_agent/jobs/{job_or_submission_id}/logs/tail> -> <function JobAgent.tail_job_logs at 0x7fb65c6c6980>
2023-11-14 15:10:59,411 INFO http_server_agent.py:78 -- <ResourceRoute [OPTIONS] <DynamicResource  /api/job_agent/jobs/{job_or_submission_id}/logs/tail> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7fb65c295e10>>
2023-11-14 15:10:59,412 INFO http_server_agent.py:78 -- <ResourceRoute [GET] <PlainResource  /api/ray/version> -> <function create_serve_rest_api.<locals>.ServeRestApiImpl.get_version at 0x7fb65c2542c0>
2023-11-14 15:10:59,412 INFO http_server_agent.py:78 -- <ResourceRoute [OPTIONS] <PlainResource  /api/ray/version> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7fb65c295e10>>
2023-11-14 15:10:59,412 INFO http_server_agent.py:78 -- <ResourceRoute [GET] <PlainResource  /api/serve/deployments/> -> <function create_serve_rest_api.<locals>.ServeRestApiImpl.get_all_deployments at 0x7fb65c254360>
2023-11-14 15:10:59,412 INFO http_server_agent.py:78 -- <ResourceRoute [OPTIONS] <PlainResource  /api/serve/deployments/> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7fb65c295e10>>
2023-11-14 15:10:59,412 INFO http_server_agent.py:78 -- <ResourceRoute [GET] <PlainResource  /api/serve/applications/> -> <function create_serve_rest_api.<locals>.ServeRestApiImpl.get_serve_instance_details at 0x7fb65c2545e0>
rsConfigImpl object at 0x7fb65c295e10>>
2023-11-14 15:10:59,412 INFO http_server_agent.py:78 -- <ResourceRoute [GET] <PlainResource  /api/serve/deployments/status> -> <function create_serve_rest_api.<locals>.ServeRestApiImpl.get_all_deployment_statu2023-11-14 15:10:59,412 INFO http_server_agent.py:78 -- <ResourceRoute [OPTIONS] <PlainResource  /api/serve/deployments/status> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7fb65c295e10>>
2023-11-14 15:10:59,412 INFO http_server_agent.py:78 -- <ResourceRoute [DELETE] <PlainResource  /api/serve/deployments/> -> <function create_serve_rest_api.<locals>.ServeRestApiImpl.delete_serve_application at 0x7fb65c254ae0>
2023-11-14 15:10:59,412 INFO http_server_agent.py:78 -- <ResourceRoute [OPTIONS] <PlainResource  /api/serve/deployments/> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7fb65c295e10>>
2023-11-14 15:10:59,412 INFO http_server_agent.py:78 -- <ResourceRoute [DELETE] <PlainResource  /api/serve/applications/> -> <function create_serve_rest_api.<locals>.ServeRestApiImpl.delete_serve_applications at 0x7fb65c254d60>
2023-11-14 15:10:59,412 INFO http_server_agent.py:78 -- <ResourceRoute [OPTIONS] <PlainResource  /api/serve/applications/> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7fb65c295e10>>
2023-11-14 15:10:59,412 INFO http_server_agent.py:78 -- <ResourceRoute [PUT] <PlainResource  /api/serve/deployments/> -> <function create_serve_rest_api.<locals>.ServeRestApiImpl.put_all_deployments at 0x7fb65c2551c0>
2023-11-14 15:10:59,412 INFO http_server_agent.py:78 -- <ResourceRoute [OPTIONS] <PlainResource  /api/serve/deployments/> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7fb65c295e10>>
2023-11-14 15:10:59,412 INFO http_server_agent.py:78 -- <ResourceRoute [PUT] <PlainResource  /api/serve/applications/> -> <function create_serve_rest_api.<locals>.ServeRestApiImpl.put_all_applications at 0x7fb65c2554e0>
2023-11-14 15:10:59,412 INFO http_server_agent.py:78 -- <ResourceRoute [OPTIONS] <PlainResource  /api/serve/applications/> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7fb65c295e10>>
2023-11-14 15:10:59,412 INFO http_server_agent.py:78 -- <ResourceRoute [GET] <StaticResource  /logs -> PosixPath('/home/xflow/app/ray/session_2023-11-14_15-10-53_386571_1/logs')> -> <bound method StaticResource._handle of <StaticResource  /logs -> PosixPath('/home/xflow/app/ray/session_2023-11-14_15-10-53_386571_1/logs')>>
2023-11-14 15:10:59,412 INFO http_server_agent.py:78 -- <ResourceRoute [OPTIONS] <StaticResource  /logs -> PosixPath('/home/xflow/app/ray/session_2023-11-14_15-10-53_386571_1/logs')> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7fb65c295e10>>
2023-11-14 15:10:59,412 INFO http_server_agent.py:79 -- Registered 30 routes.
2023-11-14 15:10:59,413 INFO process_watcher.py:44 -- raylet pid is 97
2023-11-14 15:10:59,415 INFO event_agent.py:56 -- Report events to 172.17.0.2:43509
2023-11-14 15:10:59,416 INFO event_utils.py:132 -- Monitor events logs modified after 1699940459.229768 on /home/xflow/app/ray/session_2023-11-14_15-10-53_386571_1/logs/events, the source types are all.
2023-11-14 19:18:32,204 ERROR process_watcher.py:158 -- Failed to check parent PID, exiting.
Traceback (most recent call last):
  File "/home/xflow/.local/lib/python3.11/site-packages/ray/_private/process_watcher.py", line 73, in _check_parent
    parent = curr_proc.parent()
             ^^^^^^^^^^^^^^^^^^
  File "/home/xflow/.local/lib/python3.11/site-packages/ray/thirdparty_files/psutil/__init__.py", line 564, in parent
    ppid = self.ppid()
           ^^^^^^^^^^^
  File "/home/xflow/.local/lib/python3.11/site-packages/ray/thirdparty_files/psutil/_common.py", line 486, in wrapper
    raise raise_from(err, None)
          ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in raise_from
  File "/home/xflow/.local/lib/python3.11/site-packages/ray/thirdparty_files/psutil/_common.py", line 484, in wrapper
    return fun(self)
           ^^^^^^^^^
  File "/home/xflow/.local/lib/python3.11/site-packages/ray/thirdparty_files/psutil/__init__.py", line 623, in ppid
    self._raise_if_pid_reused()
  File "/home/xflow/.local/lib/python3.11/site-packages/ray/thirdparty_files/psutil/__init__.py", line 436, in _raise_if_pid_reused
    raise NoSuchProcess(self.pid, self._name, msg=msg)
psutil.NoSuchProcess: process no longer exists and its PID has been reused (pid=137)
```
"ray status" always outputs like this:
```
xflow@a549093c59bb:~/app$ ray status
======== Autoscaler status: 2023-11-15 10:17:48.916537 ========
Node status
---------------------------------------------------------------
Active:
 1 node_41e81cd73086d9eb318da9bbb18adcbad82620175d0877e14ea9a18a
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/1.0 CPU
 0B/679.85MiB memory
 0B/600.00MiB object_store_memory

Demands:
 (no resource demands)
```
"ray memory" always outputs like this:
```
xflow@a549093c59bb:~/app$ ray memory
======== Object references status: 2023-11-15 10:24:02.817301 ========
Grouping by node address...        Sorting by object size...        Display allentries per group...


--- Summary for node address: 172.17.0.2 ---
Mem Used by Objects  Local References  Pinned        Used by task   Captured in Objects  Actor Handles
0.0 B                0, (0.0 B)        0, (0.0 B)    0, (0.0 B)     0, (0.0 B)           4, (0.0 B)

--- Object references for node address: 172.17.0.2 ---
IP Address       PID    Type    Call Site               Status          Size    Reference Type      Object Ref
172.17.0.2       227    Worker  disabled                -               ?       ACTOR_HANDLE        ffffffffffffffff2bf29e4977ecba4a42a88d010100000001000000

172.17.0.2       259    Worker  disabled                -               ?       ACTOR_HANDLE        ffffffffffffffff764592e584cb1e588f6614bd0100000001000000

172.17.0.2       1      Driver  disabled                FINISHED        ?       ACTOR_HANDLE        ffffffffffffffff764592e584cb1e588f6614bd0100000001000000

172.17.0.2       1      Driver  disabled                FINISHED        ?       ACTOR_HANDLE        ffffffffffffffff2bf29e4977ecba4a42a88d010100000001000000

To record callsite information for each ObjectRef created, set env variable RAY_record_ref_creation_sites=1

--- Aggregate object store stats across all nodes ---
Plasma memory usage 0 MiB, 0 objects, 0.0% full, 0.0% needed
```

The memory has been stable since the dashboard agent was killed.

### Versions / Dependencies

1. tested ray version:
ray[default]==2.6
ray[default]==2.8

2. python version:
3.11.5

3. OS
devian 12(containerd)

4. other libraries
fastapi
fastapi-util
uvicorn[standard]
requests
tensorflow

### Reproduction script

I have placed the container on docker hub. you can start it as follows to monitor memory.
```
docker pull karrdy89/exctr_base:0.0.2
docker run -itd -e MANAGE_PORT=6000 -e CONCURRENCY=10 -e OBJECT_STORE_MEM=1073741824 --memory=2000m karrdy89/exctr_base:0.0.2
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by karrdy89** [comment]
As you mentioned, the problem was found by performing ray.init() without creating all actors and tasks. 
This happened because there was too little memory compared to the number of processors. 
If enough memory is available, ray.init() gradually ramps up to a certain level and then stabilizes. 
Thank you for your answer.
