### ISSUE TITLE
`ray.init` connect to remote Ray cluster raises error "ray client connection timeout"

### ISSUE THREAD

**Issue by WeichenXu123** [ray-project/ray#41158]
### What happened + What you expected to happen

When I created a Ray cluster like:

```
ray start --head --block
```
it will print a Ray cluster address like:

```
--------------------
Ray runtime started.
--------------------

Next steps
  To add another node to this Ray cluster, run
    ray start --address='10.110.25.111:6379'
```

But , when I call `ray.init` from either remote machine or local machine like:
```
ray.init("ray://10.110.25.111:6379")
```

it hangs for about several seconds and then raises error:
```
/home/weichen.xu/miniconda3/envs/py310/lib/python3.10/site-packages/ray/util/client/worker.py:253: UserWarning: Ray Client connection timed out. Ensure that the Ray Client port on the head node is reachable from your local machine. See https://docs.ray.io/en/latest/cluster/ray-client.html#step-2-check-ports for more information.
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/weichen.xu/miniconda3/envs/py310/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/weichen.xu/miniconda3/envs/py310/lib/python3.10/site-packages/ray/_private/worker.py", line 1379, in init
    ctx = builder.connect()
  File "/home/weichen.xu/miniconda3/envs/py310/lib/python3.10/site-packages/ray/client_builder.py", line 173, in connect
    client_info_dict = ray.util.client_connect.connect(
  File "/home/weichen.xu/miniconda3/envs/py310/lib/python3.10/site-packages/ray/util/client_connect.py", line 55, in connect
    conn = ray.connect(
  File "/home/weichen.xu/miniconda3/envs/py310/lib/python3.10/site-packages/ray/util/client/__init__.py", line 250, in connect
    conn = self.get_context().connect(*args, **kw_args)
  File "/home/weichen.xu/miniconda3/envs/py310/lib/python3.10/site-packages/ray/util/client/__init__.py", line 92, in connect
    self.client_worker = Worker(
  File "/home/weichen.xu/miniconda3/envs/py310/lib/python3.10/site-packages/ray/util/client/worker.py", line 139, in __init__
    self._connect_channel()
  File "/home/weichen.xu/miniconda3/envs/py310/lib/python3.10/site-packages/ray/util/client/worker.py", line 260, in _connect_channel
    raise ConnectionError("ray client connection timeout")
ConnectionError: ray client connection timeout
```

### Versions / Dependencies

Ray version 2.8.0

### Reproduction script

1. Command to start Ray head node

```
ray start --head --block
```

2. Python code to connect to Ray cluster:
```
ray.init("ray://<head_node_ip>:<port>")
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by WeichenXu123** [comment]
Note: but if I use `ray.init("10.110.25.111:6379")` it works

**Comment by WeichenXu123** [comment]
I confirmed that using "ray-client-server-port" instead of head node port addresses the issue.
