### ISSUE TITLE
Build fails with clang 3.8 on Linux

### ISSUE THREAD

**Issue by wesm** [ray-project/ray#413]
Excerpt: this is with `$CC` and `$CXX` set to clang and clang++ respectively

```
  3%] No patch step for 'flatbuffers_ep'
[  4%] No update step for 'flatbuffers_ep'
[  5%] Performing configure step for 'flatbuffers_ep'
-- The C compiler identification is Clang 3.8.0
-- The CXX compiler identification is Clang 3.8.0
-- Check for working C compiler: /home/wesm/code/native-toolchain/build/llvm-3.8.0/bin/clang
-- Check for working C compiler: /home/wesm/code/native-toolchain/build/llvm-3.8.0/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/wesm/code/native-toolchain/build/llvm-3.8.0/bin/clang++
-- Check for working CXX compiler: /home/wesm/code/native-toolchain/build/llvm-3.8.0/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep-build
[  6%] Performing build step for 'flatbuffers_ep'
Scanning dependencies of target flathash
Scanning dependencies of target flatc
Scanning dependencies of target flatbuffers
[  3%] Building CXX object CMakeFiles/flathash.dir/src/flathash.cpp.o
[  7%] Building CXX object CMakeFiles/flatbuffers.dir/src/code_generators.cpp.o
[ 11%] Building CXX object CMakeFiles/flatbuffers.dir/src/reflection.cpp.o
[ 15%] Building CXX object CMakeFiles/flatbuffers.dir/src/idl_parser.cpp.o
[ 19%] Building CXX object CMakeFiles/flatbuffers.dir/src/idl_gen_text.cpp.o
[ 23%] Building CXX object CMakeFiles/flatbuffers.dir/src/util.cpp.o
[ 26%] Building CXX object CMakeFiles/flatc.dir/src/code_generators.cpp.o
/home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/src/flathash.cpp:17:10: fatal error: 'iostream' file not found
#include <iostream>
         ^
/home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/src/idl_parser.cpp:17:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^
In file included from /home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/src/reflection.cpp:17:
In file included from /home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/include/flatbuffers/reflection.h:25:
In file included from /home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/include/flatbuffers/reflection_generated.h:7:
/home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/include/flatbuffers/flatbuffers.h:22:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^
In file included from /home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/src/idl_gen_text.cpp:19:
/home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/include/flatbuffers/flatbuffers.h:22:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^
In file included from /home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/src/code_generators.cpp:17:
/home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/include/flatbuffers/code_generators.h:20:10: fatal error: 'map' file not found
#include <map>
         ^
[ 30%] Building CXX object CMakeFiles/flatc.dir/src/idl_parser.cpp.o
In file included from /home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/src/util.cpp:17:
/home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/include/flatbuffers/util.h:20:10: fatal error: 'fstream' file not found
#include <fstream>
         ^
In file included from /home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/src/code_generators.cpp:17:
/home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/include/flatbuffers/code_generators.h:20:10: fatal error: 'map' file not found
#include <map>
         ^
1 error generated.
make[5]: *** [CMakeFiles/flathash.dir/src/flathash.cpp.o] Error 1
make[4]: *** [CMakeFiles/flathash.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 34%] Building CXX object CMakeFiles/flatc.dir/src/idl_gen_text.cpp.o
1 error generated.
make[5]: *** [CMakeFiles/flatbuffers.dir/src/util.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
/home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/src/idl_parser.cpp:17:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^
[ 38%] Building CXX object CMakeFiles/flatc.dir/src/reflection.cpp.o
1 error generated.
make[5]: *** [CMakeFiles/flatbuffers.dir/src/code_generators.cpp.o] Error 1
In file included from /home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/src/idl_gen_text.cpp:19:
/home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/include/flatbuffers/flatbuffers.h:22:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^
[ 42%] Building CXX object CMakeFiles/flatc.dir/src/util.cpp.o
1 error generated.
make[5]: *** [CMakeFiles/flatbuffers.dir/src/reflection.cpp.o] Error 1
1 error generated.
make[5]: *** [CMakeFiles/flatbuffers.dir/src/idl_gen_text.cpp.o] Error 1
[ 46%] Building CXX object CMakeFiles/flatc.dir/src/idl_gen_cpp.cpp.o
1 error generated.
make[5]: *** [CMakeFiles/flatc.dir/src/code_generators.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
[ 50%] Building CXX object CMakeFiles/flatc.dir/src/idl_gen_general.cpp.o
In file included from /home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/src/reflection.cpp:17:
In file included from /home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/include/flatbuffers/reflection.h:25:
In file included from /home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/include/flatbuffers/reflection_generated.h:7:
/home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/include/flatbuffers/flatbuffers.h:22:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^
In file included from /home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/src/util.cpp:17:
/home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/include/flatbuffers/util.h:20:10: fatal error: 'fstream' file not found
#include <fstream>
         ^
1 error generated.
make[5]: *** [CMakeFiles/flatbuffers.dir/src/idl_parser.cpp.o] Error 1
make[4]: *** [CMakeFiles/flatbuffers.dir/all] Error 2
In file included from /home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/src/idl_gen_cpp.cpp:19:
/home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/include/flatbuffers/flatbuffers.h:22:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^
In file included from /home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/src/idl_gen_general.cpp:19:
/home/wesm/code/ray/python/ray/core/src/common/flatbuffers_ep-prefix/src/flatbuffers_ep/include/flatbuffers/flatbuffers.h:22:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^
1 error generated.
1 error generated.
make[5]: *** [CMakeFiles/flatc.dir/src/idl_gen_text.cpp.o] Error 1
make[5]: *** [CMakeFiles/flatc.dir/src/util.cpp.o] Error 1
1 error generated.
make[5]: *** [CMakeFiles/flatc.dir/src/idl_parser.cpp.o] Error 1
1 error generated.
make[5]: *** [CMakeFiles/flatc.dir/src/reflection.cpp.o] Error 1
1 error generated.
make[5]: *** [CMakeFiles/flatc.dir/src/idl_gen_cpp.cpp.o] Error 1
1 error generated.
make[5]: *** [CMakeFiles/flatc.dir/src/idl_gen_general.cpp.o] Error 1
make[4]: *** [CMakeFiles/flatc.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [src/common/flatbuffers_ep-prefix/src/flatbuffers_ep-stamp/flatbuffers_ep-build] Error 2
make[1]: *** [src/common/CMakeFiles/flatbuffers_ep.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    license="Apache 2.0")
  File "/home/wesm/anaconda3/envs/py27/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/wesm/anaconda3/envs/py27/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/wesm/anaconda3/envs/py27/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 13, in run
    subprocess.check_call(["../build.sh"])
  File "/home/wesm/anaconda3/envs/py27/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../build.sh']' returned non-zero exit status 2
```

**Comment by wesm** [comment]
gcc works fine though

**Comment by pcmoritz** [comment]
Thanks! I looked into this some more, the problem here is that libc++ is not installed. If I do install it, it still doesn't compile because of this bug in ubuntu: http://stackoverflow.com/questions/37096062/get-a-basic-c-program-to-compile-using-clang-on-ubuntu-16

The only feasible solution I see right now is either compile a working version of clang/libc++ from source (which we don't want to do as part of ray) or use libstdc++ instead. The latter doesn't work with flatbuffers 1.6.0 but should work as soon as this https://github.com/google/flatbuffers/pull/4189 is included in the release tarball, which should be the case for 1.7.0.

I wonder if there is a better solution, let me know if you can think of one.

**Comment by wesm** [comment]
Got it, guess I never hit this problem because I usually have `$FLATBUFFERS_HOME` set. I guess we can wait until flatbuffers 1.7.0 release

**Comment by robertnishihara** [comment]
Should have been fixed a while ago.
