### ISSUE TITLE
[Core] getting/creating an actor from multiple thread errors

### ISSUE THREAD

**Issue by Zandew** [ray-project/ray#41324]
### What happened + What you expected to happen

Creating/getting an actor from multiple threads like this:
```
import ray
import threading
import time
import random


@ray.remote
class bar:
        pass

def foo():
        time.sleep(random.random())
        bar.options(name="bar", namespace="bar_name", get_if_exists=True, lifetime="detached").remote()


threads = []
for i in range(1000):
        threads.append(threading.Thread(target=foo))

for thread in threads:
        thread.start()

for thread in threads:
        thread.join()
```

sometimes results an error:
```
Traceback (most recent call last):
  File "/Users/andrewxue/anaconda3/envs/ray/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Users/andrewxue/anaconda3/envs/ray/lib/python3.9/threading.py", line 917, in run
    return ray.get_actor(name, namespace=namespace)
  File "/Users/andrewxue/fork/ray/python/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    self._target(*self._args, **self._kwargs)
  File "/Users/andrewxue/fork/ray/python/ray/data/tests/test.py", line 13, in foo
    bar.options(name="bar", namespace="bar_name", get_if_exists=True, lifetime="detached").remote()
  File "/Users/andrewxue/fork/ray/python/ray/actor.py", line 687, in remote
    return fn(*args, **kwargs)
  File "/Users/andrewxue/fork/ray/python/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/andrewxue/fork/ray/python/ray/_private/worker.py", line 2845, in get_actor
    return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/Users/andrewxue/fork/ray/python/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return worker.core_worker.get_named_actor_handle(name, namespace or "")
  File "python/ray/_raylet.pyx", line 4021, in ray._raylet.CoreWorker.get_named_actor_handle
    return fn(*args, **kwargs)
  File "/Users/andrewxue/fork/ray/python/ray/util/tracing/tracing_helper.py", line 388, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/Users/andrewxue/fork/ray/python/ray/actor.py", line 781, in _remote
    return ray.get_actor(name, namespace=namespace)
  File "/Users/andrewxue/fork/ray/python/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
  File "python/ray/_raylet.pyx", line 453, in ray._raylet.check_status
    return fn(*args, **kwargs)
  File "/Users/andrewxue/fork/ray/python/ray/_private/client_mode_hook.py", line 103, in wrapper
ValueError: Failed to look up actor with name 'bar'. This could because 1. You are trying to look up a named actor you didn't create. 2. The named actor died. 3. You did not use a namespace matching the namespace of the actor.
```

### Versions / Dependencies

latest master

### Reproduction script

script given above

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by anyscalesam** [comment]
@Zandew have you started work on this yet?

**Comment by Zandew** [comment]
> @Zandew have you started work on this yet?

I have not started to work on this, this looks like a core issue. On the data side was fixed by locking the remote call #41299.

**Comment by anyscalesam** [comment]
discussed internal to core - we'll possibly plan for this in ray210

**Comment by rkooo567** [comment]
cc @jjyao to repro

**Comment by ruisearch42** [comment]
I was able to reproduce the issue. Looking further.

**Comment by jobh** [comment]
I see a possibly related failure, using `get_if_exists` in a tight loop on a single thread. It looks like a race condition where the returned actor is dying/about to die. Should I create a separate report for this, or do you think it's the same underlying issue?

```
  Traceback (most recent call last):
  File "/home/jobh/src/simula/transact/Reference_route_service/test_ray_lock.py", line 20, in <module>
    test_lock()
  File "/home/jobh/src/simula/transact/Reference_route_service/test_ray_lock.py", line 15, in test_lock
    ray.get(actor.release.remote())
  File "/home/jobh/mambaforge/envs/transact/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/jobh/mambaforge/envs/transact/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/jobh/mambaforge/envs/transact/lib/python3.10/site-packages/ray/_private/worker.py", line 2626, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
        class_name: LockActor
        actor_id: f41165a4b8f1cca43c60623001000000
        pid: 1728191
        name: test
        namespace: locks
        ip: 172.16.0.146
The actor is dead because all references to the actor were removed.
```

Reproducer (might not work for you, the problem goes away if I remove the `import numpy` statement so it's probably very timing dependent):
```
import asyncio

import numpy as np
import ray


@ray.remote(namespace="locks", num_cpus=0)
class LockActor:
    def release(self):
        ...


def test_lock():
    actor = LockActor.options(name="test", get_if_exists=True).remote()
    ray.get(actor.release.remote())


ray.init()
for i in range(100):
    test_lock()
```

**Comment by ruisearch42** [comment]
@jobh Thanks for reporting. Can you open a separate issue and link this one? We can combine them when investigations provide more evidence they are the same.

**Comment by rkooo567** [comment]
Btw, it'd be nicer to think about how to safely enable thread-safety for APIs. right now, my impression is it is kind of happened to work (and prone to be broken).

**Comment by ruisearch42** [comment]
Looks like there is a race condition when accessing actor metadata in GCS. Full stack trace:
```
2024-03-18 10:43:06,446	WARNING worker.py:1422 -- SIGTERM handler is not set because current thread is not the main thread.
2024-03-18 10:43:08,121	INFO worker.py:1743 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265
[2024-03-18 10:43:08,122 I 74426 315464] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
2024-03-18 10:43:08,509	INFO function_manager.py:663 -- qr: class_name = None
2024-03-18 10:43:08,509	INFO function_manager.py:664 -- qr: type(class_name) = <class 'NoneType'>
Exception in thread Thread-130:
Traceback (most recent call last):
  File "/Users/ruiqiao/anaconda3/envs/env-ray/lib/python3.9/threading.py", line 980, in _bootstrap_inner
2024-03-18 10:43:08,509	INFO function_manager.py:663 -- qr: class_name = bar
2024-03-18 10:43:08,509	INFO function_manager.py:663 -- qr: class_name = bar
2024-03-18 10:43:08,509	INFO function_manager.py:664 -- qr: type(class_name) = <class 'str'>
2024-03-18 10:43:08,510	INFO function_manager.py:663 -- qr: class_name = None
2024-03-18 10:43:08,510	INFO function_manager.py:664 -- qr: type(class_name) = <class 'NoneType'>
Exception in thread Thread-347:
Traceback (most recent call last):
  File "/Users/ruiqiao/repos/ray/python/ray/actor.py", line 926, in _remote
2024-03-18 10:43:08,509	INFO function_manager.py:664 -- qr: type(class_name) = <class 'str'>
(raylet) [2024-03-18 10:43:08,442 I 74444 316646] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
    self.run()
  File "/Users/ruiqiao/anaconda3/envs/env-ray/lib/python3.9/threading.py", line 917, in run
    return ray.get_actor(name, namespace=namespace)
  File "/Users/ruiqiao/repos/ray/python/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    self._target(*self._args, **self._kwargs)
  File "/Users/ruiqiao/repos/ray/python/threads.py", line 13, in foo
    return fn(*args, **kwargs)
  File "/Users/ruiqiao/repos/ray/python/ray/_private/client_mode_hook.py", line 103, in wrapper
    bar.options(name="bar", namespace="bar_name", get_if_exists=True, lifetime="detached").remote()
  File "/Users/ruiqiao/repos/ray/python/ray/actor.py", line 830, in remote
    return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/Users/ruiqiao/repos/ray/python/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return func(*args, **kwargs)
  File "/Users/ruiqiao/repos/ray/python/ray/_private/worker.py", line 2927, in get_actor
    return fn(*args, **kwargs)
  File "/Users/ruiqiao/repos/ray/python/ray/util/tracing/tracing_helper.py", line 388, in _invocation_actor_class_remote_span
    return worker.core_worker.get_named_actor_handle(name, namespace or "")
  File "python/ray/_raylet.pyx", line 4370, in ray._raylet.CoreWorker.get_named_actor_handle
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/Users/ruiqiao/repos/ray/python/ray/actor.py", line 926, in _remote
  File "python/ray/_raylet.pyx", line 574, in ray._raylet.check_status
    return ray.get_actor(name, namespace=namespace)
  File "/Users/ruiqiao/repos/ray/python/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/Users/ruiqiao/repos/ray/python/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/ruiqiao/repos/ray/python/ray/_private/worker.py", line 2927, in get_actor
ValueError: Failed to look up actor with name 'bar'. This could because 1. You are trying to look up a named actor you didn't create. 2. The named actor died. 3. You did not use a namespace matching the namespace of the actor.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ruiqiao/anaconda3/envs/env-ray/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    return worker.core_worker.get_named_actor_handle(name, namespace or "")
  File "python/ray/_raylet.pyx", line 4372, in ray._raylet.CoreWorker.get_named_actor_handle
    self.run()
  File "/Users/ruiqiao/anaconda3/envs/env-ray/lib/python3.9/threading.py", line 917, in run
  File "python/ray/_raylet.pyx", line 4312, in ray._raylet.CoreWorker.make_actor_handle
    self._target(*self._args, **self._kwargs)
  File "/Users/ruiqiao/repos/ray/python/threads.py", line 13, in foo
  File "/Users/ruiqiao/repos/ray/python/ray/_private/function_manager.py", line 567, in load_actor_class
    bar.options(name="bar", namespace="bar_name", get_if_exists=True, lifetime="detached").remote()
  File "/Users/ruiqiao/repos/ray/python/ray/actor.py", line 830, in remote
    return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/Users/ruiqiao/repos/ray/python/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    actor_class = self._load_actor_class_from_gcs(
  File "/Users/ruiqiao/repos/ray/python/ray/_private/function_manager.py", line 666, in _load_actor_class_from_gcs
    return fn(*args, **kwargs)
  File "/Users/ruiqiao/repos/ray/python/ray/util/tracing/tracing_helper.py", line 388, in _invocation_actor_class_remote_span
    class_name = ensure_str(class_name)
  File "/Users/ruiqiao/repos/ray/python/ray/_private/utils.py", line 243, in ensure_str
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/Users/ruiqiao/repos/ray/python/ray/actor.py", line 932, in _remote
    assert isinstance(s, bytes)
AssertionError
    return self._remote(args, kwargs, **updated_options)
  File "/Users/ruiqiao/repos/ray/python/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/Users/ruiqiao/repos/ray/python/ray/util/tracing/tracing_helper.py", line 388, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/Users/ruiqiao/repos/ray/python/ray/actor.py", line 997, in _remote
    ray.get_actor(name, namespace=namespace)
  File "/Users/ruiqiao/repos/ray/python/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/Users/ruiqiao/repos/ray/python/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/ruiqiao/repos/ray/python/ray/_private/worker.py", line 2927, in get_actor
    return worker.core_worker.get_named_actor_handle(name, namespace or "")
  File "python/ray/_raylet.pyx", line 4372, in ray._raylet.CoreWorker.get_named_actor_handle
  File "python/ray/_raylet.pyx", line 4312, in ray._raylet.CoreWorker.make_actor_handle
  File "/Users/ruiqiao/repos/ray/python/ray/_private/function_manager.py", line 567, in load_actor_class
    actor_class = self._load_actor_class_from_gcs(
  File "/Users/ruiqiao/repos/ray/python/ray/_private/function_manager.py", line 666, in _load_actor_class_from_gcs
    class_name = ensure_str(class_name)
  File "/Users/ruiqiao/repos/ray/python/ray/_private/utils.py", line 243, in ensure_str
    assert isinstance(s, bytes)
AssertionError
```

**Comment by anyscalesam** [comment]
> I see a possibly related failure, using `get_if_exists` in a tight loop on a single thread.
> 
> It looks like it may by a race condition where the returned actor is not pinned properly because it's already marked for deletion.
> 
> Should I create a separate report for this, or do you think it's the same underlying issue?
> 
> ```
>   Traceback (most recent call last):
>   File "/home/jobh/src/simula/transact/Reference_route_service/test_ray_lock.py", line 20, in <module>
>     test_lock()
>   File "/home/jobh/src/simula/transact/Reference_route_service/test_ray_lock.py", line 15, in test_lock
>     ray.get(actor.release.remote())
>   File "/home/jobh/mambaforge/envs/transact/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
>     return fn(*args, **kwargs)
>   File "/home/jobh/mambaforge/envs/transact/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
>     return func(*args, **kwargs)
>   File "/home/jobh/mambaforge/envs/transact/lib/python3.10/site-packages/ray/_private/worker.py", line 2626, in get
>     raise value
> ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
>         class_name: LockActor
>         actor_id: f41165a4b8f1cca43c60623001000000
>         pid: 1728191
>         name: test
>         namespace: locks
>         ip: 172.16.0.146
> The actor is dead because all references to the actor were removed.
> ```
> 
> Reproducer. It may not work for you, the problem goes away if I remove the unused `import numpy` statement so it's probably very timing dependent:
> 
> ```
> import asyncio
> 
> import numpy as np
> import ray
> 
> 
> @ray.remote(namespace="locks", num_cpus=0)
> class LockActor:
>     def release(self):
>         ...
> 
> 
> def test_lock():
>     actor = LockActor.options(name="test", get_if_exists=True).remote()
>     ray.get(actor.release.remote())
> 
> 
> ray.init()
> for i in range(100):
>     test_lock()
> ```

Can you link the GH issue when you get a chance @jobh ?

**Comment by ruisearch42** [comment]
> Can you link the GH issue when you get a chance @jobh ?
@anyscalesam I think this is the one: https://github.com/ray-project/ray/issues/44083

**Comment by fishbone** [comment]
After inject a sleep after function table put, it's consistent reproducible. 
```
(base) ➜  ray git:(master) ✗ RAY_BACKEND_LOG_LEVEL=debug python err.py
2024-03-20 20:32:52,886	INFO worker.py:1743 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265
[2024-03-20 20:32:52,888 I 41566 871000] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
BeforeCreateActor 6193606656
AfterCreating 6193606656 ActorID(46ea7cf7d8c3ac7151e6a79f01000000)
(raylet) [2024-03-20 20:32:53,202 I 41585 871215] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
(raylet) Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 2281, in ray._raylet.task_execution_handler
    execute_task_with_cancellation_handler(
  File "python/ray/_raylet.pyx", line 2138, in ray._raylet.execute_task_with_cancellation_handler
    actor_class = manager.load_actor_class(job_id, function_descriptor)
  File "/Users/yic/Repos/ray/python/ray/_private/function_manager.py", line 569, in load_actor_class
    actor_class = self._load_actor_class_from_gcs(
  File "/Users/yic/Repos/ray/python/ray/_private/function_manager.py", line 665, in _load_actor_class_from_gcs
    class_name = ensure_str(class_name)
  File "/Users/yic/Repos/ray/python/ray/_private/utils.py", line 243, in ensure_str
    assert isinstance(s, bytes)
AssertionError
An unexpected internal error occurred while the worker was executing a task.
(raylet) A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff46ea7cf7d8c3ac7151e6a79f01000000 Worker ID: 9843049bea5b2b5823e0445f05f484507e28ddd523a235b5dead62b7 Node ID: 837d19167086617084f4771920ba602c73dd30633b731a2acb45c6dd Worker IP address: 127.0.0.1 Worker port: 59466 Worker PID: 41591 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None. Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 2281, in ray._raylet.task_execution_handler
    execute_task_with_cancellation_handler(
  File "python/ray/_raylet.pyx", line 2138, in ray._raylet.execute_task_with_cancellation_handler
    actor_class = manager.load_actor_class(job_id, function_descriptor)
  File "/Users/yic/Repos/ray/python/ray/_private/function_manager.py", line 569, in load_actor_class
    actor_class = self._load_actor_class_from_gcs(
  File "/Users/yic/Repos/ray/python/ray/_private/function_manager.py", line 665, in _load_actor_class_from_gcs
    class_name = ensure_str(class_name)
  File "/Users/yic/Repos/ray/python/ray/_private/utils.py", line 243, in ensure_str
    assert isinstance(s, bytes)
AssertionError
An unexpected internal error occurred while the worker was executing a task.
(pid=41591) KV_LOAD DONE
2024-03-20 20:32:55,275	ERROR function_manager.py:534 -- KV_PUT DONE
BeforeCreateActor 6176780288
AfterCreating 6176780288 ActorID(c2aa94ddeb178c236c24514501000000)
(raylet) [2024-03-20 20:32:55,496 I 41597 871779] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1 [repeated 11x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(pid=41597) KV_LOAD DONE
```

Definitely there is a race condition where two actors are created for the same name. Still checking.

**Comment by fishbone** [comment]
I think the race condition:

Suppose there are two thread doing: `bar.options(name="bar", namespace="bar_name", get_if_exists=True, lifetime="detached").remote()`

Thread A:
a. Put data into KV store
b. Create actor

Thread B:
a. Skip put data into KV store because of session issue
b. Create actor

If it happens: A.a (pending), B.a, B.b, A.b ===> fail.

**Comment by fishbone** [comment]
Following above comment: the reason thread B will skip the KV put is because of the session and the session was set before the put succeeded and this is the race condition. Changed to the following code should work.


```
diff --git a/python/ray/actor.py b/python/ray/actor.py
index 96ffd40a2d..40a774284c 100644
--- a/python/ray/actor.py
+++ b/python/ray/actor.py
@@ -1027,10 +1027,6 @@ class ActorClass:
         if not meta.is_cross_language and (
             meta.last_export_session_and_job != worker.current_session_and_job
         ):
-            # If this actor class was not exported in this session and job,
-            # we need to export this function again, because current GCS
-            # doesn't have it.
-            meta.last_export_session_and_job = worker.current_session_and_job
             # After serialize / deserialize modified class, the __module__
             # of modified class will be ray.cloudpickle.cloudpickle.
             # So, here pass actor_creation_function_descriptor to make
@@ -1040,6 +1036,10 @@ class ActorClass:
                 meta.actor_creation_function_descriptor,
                 meta.method_meta.methods.keys(),
             )
+            # If this actor class was not exported in this session and job,
+            # we need to export this function again, because current GCS
+            # doesn't have it.
+            meta.last_export_session_and_job = worker.current_session_and_job

         resources = ray._private.utils.resources_from_ray_options(actor_options)
         # Set the actor's default resources if not already set. First three
```

**Comment by fishbone** [comment]
I feel the chaos testing is important to catch this corner case. cc @jjyao @hongchaodeng

**Comment by ruisearch42** [comment]
Thanks @fishbone !

How do you like the following:
```
        # Export the actor.
        if not meta.is_cross_language and (
            meta.last_export_session_and_job != worker.current_session_and_job
        ):
            threadLock = threading.Lock()
            with threadLock:
                if (meta.last_export_session_and_job != worker.current_session_and_job):
                    meta.last_export_session_and_job = worker.current_session_and_job
                    worker.function_actor_manager.export_actor_class(
                        meta.modified_class,
                        meta.actor_creation_function_descriptor,
                        meta.method_meta.methods.keys(),
                    )
```
With this, `export_actor_class()` is called at most once instead of multiple times in multi-threads.
