### ISSUE TITLE
Release test chaos_many_actors.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#41335]
Release test **chaos_many_actors.aws** failed. See https://buildkite.com/ray-project/release/builds/2023#018bf69d-0fae-40f6-bb8c-30648ee82acc for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by rickyyx** [comment]
This is due to https://github.com/ray-project/ray/commit/80018ffaf484be15caa70aaa9ce04836ba77f12f

**Comment by rickyyx** [comment]
```
Running with failures
Traceback (most recent call last):
  File "chaos_test/test_chaos_basic.py", line 238, in <module>
    main()
  File "chaos_test/test_chaos_basic.py", line 209, in main
    node_killer = ray.get_actor("node_killer", namespace="release_test_namespace")
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/worker.py", line 2845, in get_actor
    return worker.core_worker.get_named_actor_handle(name, namespace or "")
  File "python/ray/_raylet.pyx", line 4028, in ray._raylet.CoreWorker.get_named_actor_handle
  File "python/ray/_raylet.pyx", line 453, in ray._raylet.check_status
ValueError: Failed to look up actor with name 'node_killer'. This could because 1. You are trying to look up a named actor you didn't create. 2. The named actor died. 3. You did not use a namespace matching the namespace of the actor.
(raylet) WARNING: 284 PYTHON worker processes have been started on node: 8fe29f0c9af42ce8489d924a3a1321946619053d420e58c9558e48a5 with address: 10.0.17.192. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds). [repeated 7x across cluster]
Subprocess return code: 1
```

**Comment by rickyyx** [comment]
Bisect result:

before https://github.com/ray-project/ray/commit/80018ffaf484be15caa70aaa9ce04836ba77f12f: https://buildkite.com/ray-project/release/builds/2058
at 80018ffaf484be15caa70aaa9ce04836ba77f12f: https://buildkite.com/ray-project/release/builds/2059#018bf894-e7a0-4bec-9471-f5b01d2e68e3

**Comment by can-anyscale** [comment]
Oh if this has been jailed, you need to close the issue to run it on nightly run.

It will open itself if it fails again on nightly.
