### ISSUE TITLE
[Data] Ray client error "Global node is not initialized."

### ISSUE THREAD

**Issue by WeichenXu123** [ray-project/ray#41333]
### What happened + What you expected to happen

1. Starting one Ray head node:
```
ray start --head --block --num-cpus=1
```

Then using Ray client to connect to Ray cluster, then run Ray dataset `to_pandas`
```
import ray
ray.init("ray://<head_node_ip>:10001")

import pandas as pd
p1 = pd.DataFrame({'a': [3,4] * 10000, 'b': [5,6] * 10000})
ds = ray.data.from_pandas(p1)
ds.repartition(4).to_pandas()
```

Error happens:

```
Traceback (most recent call last):                                                                                | 0/4 [00:00<?, ?it/s]
  File "<stdin>", line 1, in <module>                                                                             | 0/4 [00:00<?, ?it/s]
  File "/home/weichen.xu/ray/python/ray/data/dataset.py", line 4345, in to_pandas
    count = self.count()
  File "/home/weichen.xu/ray/python/ray/data/dataset.py", line 2532, in count
    [get_num_rows.remote(block) for block in self.get_internal_block_refs()]
  File "/home/weichen.xu/ray/python/ray/data/dataset.py", line 4688, in get_internal_block_refs
    blocks = self._plan.execute().get_blocks()
  File "/home/weichen.xu/ray/python/ray/data/_internal/plan.py", line 599, in execute
    blocks = execute_to_legacy_block_list(
  File "/home/weichen.xu/ray/python/ray/data/_internal/execution/legacy_compat.py", line 118, in execute_to_legacy_block_list
    bundles = executor.execute(dag, initial_stats=stats)
  File "/home/weichen.xu/ray/python/ray/data/_internal/execution/streaming_executor.py", line 130, in execute
    register_dataset_to_stats_actor(
  File "/home/weichen.xu/ray/python/ray/data/_internal/stats.py", line 406, in register_dataset_to_stats_actor
    _check_cluster_stats_actor()
  File "/home/weichen.xu/ray/python/ray/data/_internal/stats.py", line 352, in _check_cluster_stats_actor
    raise RuntimeError("Global node is not initialized.")
RuntimeError: Global node is not initialized.
```

### Versions / Dependencies

Ray latest nightly build version.

### Reproduction script

See above.

### Issue Severity

High: It blocks me from completing my task.

**Comment by jjyao** [comment]
@WeichenXu123 Ray data doesn't support Ray client. You can warp your dataset code inside a task:

```
import ray
import pandas as pd
ray.init("ray://<head_node_ip>:10001")

@ray.remote
def ray_data_task():
    p1 = pd.DataFrame({'a': [3,4] * 10000, 'b': [5,6] * 10000})
    ds = ray.data.from_pandas(p1)
    return ds.repartition(4).to_pandas()

ray.get(ray_data_task.remote())
```

**Comment by Jay-ju** [comment]
@jjyao Is there any update on this? Or has it been resolved?
