### ISSUE TITLE
2 Ray tune errors happens occasionally when I submitted my job

### ISSUE THREAD

**Issue by luyuhengCN** [ray-project/ray#41362]
### What happened + What you expected to happen

1. ERROR tune_controller.py:1988 -- Could not re-use actor for trial train_model_aac66_00002: Trainable runner reuse requires reset_config() to be implemented and return True.
2. FileNotFoundError: [Errno 2] No such file or directory: '~/ray_results/test_experiment/.tmp_generator' -> '~/ray_results/test_experiment/basic-variant-state-2023-11-24_10-39-19.json'

Below is my error log:

```
2023-11-24 10:39:17,305	INFO worker.py:1664 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
2023-11-24 10:39:19,096	INFO tune.py:595 -- [output] This will use the new output engine with verbosity 1. To disable the new output and use the legacy output engine, set the environment variable RAY_AIR_NEW_OUTPUT=0. For more information, please see https://github.com/ray-project/ray/issues/36949
2023-11-24 11:11:34,960	ERROR tune_controller.py:1988 -- Could not re-use actor for trial train_model_aac66_00002: Trainable runner reuse requires reset_config() to be implemented and return True.
2023-11-24 11:52:29,966	WARNING tune_controller.py:746 -- Trial controller checkpointing failed: [Errno 2] No such file or directory: '~/ray_results/test_experiment/.tmp_generator' -> '/share/home/yhlu/ray_results/test_experiment/basic-variant-state-2023-11-24_10-39-19.json'
Traceback (most recent call last):
  File "./train_mlp_raytune.py", line 265, in <module>
    ray_tune(args)
  File "./train_mlp_raytune.py", line 245, in ray_tune
    results = tuner.fit()
  File "~/anaconda3/envs/pytorch_py3.9/lib/python3.9/site-packages/ray/tune/tuner.py", line 364, in fit
    return self._local_tuner.fit()
  File "~/anaconda3/envs/pytorch_py3.9/lib/python3.9/site-packages/ray/tune/impl/tuner_internal.py", line 526, in fit
    analysis = self._fit_internal(trainable, param_space)
  File "~/anaconda3/envs/pytorch_py3.9/lib/python3.9/site-packages/ray/tune/impl/tuner_internal.py", line 645, in _fit_internal
    analysis = run(
  File "~/anaconda3/envs/pytorch_py3.9/lib/python3.9/site-packages/ray/tune/tune.py", line 1007, in run
    runner.step()
  File "~/anaconda3/envs/pytorch_py3.9/lib/python3.9/site-packages/ray/tune/execution/tune_controller.py", line 747, in step
    raise e
  File "~/anaconda3/envs/pytorch_py3.9/lib/python3.9/site-packages/ray/tune/execution/tune_controller.py", line 744, in step
    self.checkpoint()
  File "~/anaconda3/envs/pytorch_py3.9/lib/python3.9/site-packages/ray/tune/execution/tune_controller.py", line 481, in checkpoint
    self._checkpoint_manager.checkpoint(
  File "~/anaconda3/envs/pytorch_py3.9/lib/python3.9/site-packages/ray/tune/execution/experiment_state.py", line 228, in checkpoint
    save_fn()
  File "~/anaconda3/envs/pytorch_py3.9/lib/python3.9/site-packages/ray/tune/execution/tune_controller.py", line 384, in save_to_dir
    self._search_alg.save_to_dir(experiment_dir, session_str=self._session_str)
  File "~/anaconda3/envs/pytorch_py3.9/lib/python3.9/site-packages/ray/tune/search/basic_variant.py", line 404, in save_to_dir
    _atomic_save(
  File "~/anaconda3/envs/pytorch_py3.9/lib/python3.9/site-packages/ray/tune/utils/util.py", line 416, in _atomic_save
    os.replace(tmp_search_ckpt_path, os.path.join(checkpoint_dir, file_name))
FileNotFoundError: [Errno 2] No such file or directory: '~/ray_results/test_experiment/.tmp_generator' -> '~/ray_results/test_experiment/basic-variant-state-2023-11-24_10-39-19.json'
```

### Versions / Dependencies

python=3.9.18
ray=2.8.0
pytorch=1.13.1
cuda=11.6
CentOS7

### Reproduction script

```
# logging only status updates 
os.environ['RAY_AIR_NEW_OUTPUT'] = "1"
# This automatically detects available resources in the single machine.
ray.init()  
trainable_with_resources = tune.with_resources(
    train_model, resources = {"cpu": 4, "gpu": 1}
  )     
tuner = tune.Tuner(
            trainable_with_resources,
            param_space=configs,
            tune_config=tune.TuneConfig(
                metric='valid_ic',
                mode='max',
                scheduler=ASHAScheduler()),
            run_config=RunConfig(
                log_to_file=(f"ray_stdout.log", "ray_stderr.log"),
                storage_path=f'{log_dir}/raytune_results', 
                name="test_experiment")
        )
        
    results = tuner.fit()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by matthewdeng** [comment]
Hi could you share a full repro script?

**Comment by luyuhengCN** [comment]
Thanks for your quick feedback. I have solved this problem recently. It might be triggered by the memory error due to the dataset I input was very large (~ 40G). I used the 'tune.with_parameters' to wrapper the trainable module with the static dataset, and found the bug gone. I hope it could give you some ideas. As the bug is gone, so I closed the issue. 

Best,
Yuheng.

**Comment by Phirefly9** [comment]
Sorry to reopen this but @luyuhengCN is there any chance you were operating 2 jobs at a time using the same storage path?  I'm running into this now, and looking to recreate, and as far as I can tell from our runs that is the current similarity between people hitting it

**Comment by dylanprins** [comment]
@Phirefly9 I'm running into the same issue. And yes it happens when we run multiple tune runs at the same time. Still this shouldn't be a problem right? I want that all my runs go to the same path. How can we fix this issue? :)

**Comment by Phirefly9** [comment]
my current hypothesis is that recently ray/rllib made some changes that made it a lot more difficult to use a shared filesystem

1. _temp_dir will now collide on a shared file system, it is not 100% required to change the _temp_dir `per training run` or else any instances of a ray cluster will collide.  if you are in a situation like me using an HPC the ray init on a node will look into the _temp_dir, see the `current_session` file, and then attempt to connect to an existing ray cluster, hanging and eventually crashing.  this is very not ideal
2. this issue, I think what's happening is that rllib is making  `<storage_path>/.tmp_generator` instead of saving .tmp_genenerator in a location specific to a job, as `<storage_path>` is shared between any running jobs, this can collide between multiple runs, causing incorrect data for the first job, and a race condition for the second

**Comment by Phirefly9** [comment]
yup you're basically just avoiding the race condition by doing that, it can still happen just with a low % chance
