### ISSUE TITLE
[Data] `Dataset.union` might error if you use `preserve_options`

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#41524]
### What happened + What you expected to happen

I tried `Dataset.union` with `preserve_options`, but got an `AssertionError`.

```
Traceback (most recent call last):                                                                                                       
  File "/Users/balaji/Documents/GitHub/ray/repro.py", line 6, in <module>
    ray.data.range(10000000).union(ray.data.range(100000), ray.data.range(1)).take_all()
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/dataset.py", line 2459, in take_all
    for row in self.iter_rows():
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/iterator.py", line 225, in _wrapped_iterator
    for batch in batch_iterable:
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/iterator.py", line 183, in _create_iterator
    for batch in iterator:
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/block_batching/iter_batches.py", line 176, in iter_batches
    next_batch = next(async_batch_iter)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/util.py", line 855, in make_async_gen
    raise next_item
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/util.py", line 832, in execute_computation
    for item in fn(thread_safe_generator):
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/block_batching/iter_batches.py", line 167, in _async_iter_batches
    yield from extract_data_from_batch(batch_iter)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/block_batching/util.py", line 210, in extract_data_from_batch
    for batch in batch_iter:
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/block_batching/iter_batches.py", line 306, in restore_original_order
    for batch in batch_iter:
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/block_batching/iter_batches.py", line 218, in threadpool_computations_format_collate
    yield from formatted_batch_iter
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/block_batching/util.py", line 158, in format_batches
    for batch in block_iter:
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/block_batching/util.py", line 117, in blocks_to_batches
    for block in block_iter:
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/block_batching/util.py", line 54, in resolve_block_refs
    for block_ref in block_ref_iter:
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/block_batching/iter_batches.py", line 254, in prefetch_batches_locally
    for block_ref, metadata in block_ref_iter:
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/util.py", line 812, in __next__
    return next(self.it)
           ^^^^^^^^^^^^^
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/execution/legacy_compat.py", line 54, in execute_to_legacy_block_iterator
    for bundle in bundle_iter:
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/execution/interfaces/executor.py", line 37, in __next__
    return self.get_next()
           ^^^^^^^^^^^^^^^
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/execution/streaming_executor.py", line 143, in get_next
    item = self._outer._output_node.get_output_blocking(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/execution/streaming_executor_state.py", line 270, in get_output_blocking
    raise self._exception
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/execution/streaming_executor.py", line 210, in run
    while self._scheduling_loop_step(self._topology) and not self._shutdown:
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/execution/streaming_executor.py", line 297, in _scheduling_loop_step
    update_operator_states(topology)
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/execution/streaming_executor_state.py", line 499, in update_operator_states
    op.all_inputs_done()
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/execution/operators/union_operator.py", line 88, in all_inputs_done
    assert len(input_buffer) == 0, (
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Input at index 2 still has 20 blocks remaining.
```

### Versions / Dependencies

42c8e0bd3c52fe9036a57dbba4b3bd9e3829075d

### Reproduction script

```python
import ray
from ray.data.context import DataContext

DataContext.get_current().execution_options.preserve_order = True
ds = (
    ray.data.range(10000000).union(ray.data.range(100000), ray.data.range(1)).take_all()
)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by bveeramani** [comment]
The issue is that `UnionOperator.inputs_done` assumes that task are completed in the order of their indices:

https://github.com/ray-project/ray/blob/42c8e0bd3c52fe9036a57dbba4b3bd9e3829075d/python/ray/data/_internal/execution/operators/union_operator.py#L67-L81

**Comment by scottjlee** [comment]
Have not gotten a chance to work on this yet due to other priorities, but would be happy to help shepherd a PR if you're willing to open one! I think it should be relatively straightforward based on Balaji's investigation above
