### ISSUE TITLE
[RLlib] Value error while running DQN

### ISSUE THREAD

**Issue by ManojGadam** [ray-project/ray#41559]
### What happened + What you expected to happen

When I am running DQN with my custom environment and model I am running into below error. I am returning a numpy array from the environment.

2023-12-01 15:10:46,510	ERROR tune_controller.py:1383 -- Trial task failed for trial DQN_graphenv_c0eac_00000
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 2563, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::DQN.train() (pid=2285, ip=172.28.0.12, actor_id=405d1e93450ed02ff6e7967701000000, repr=DQN)
  File "/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/trainable.py", line 342, in train
    raise skipped from exception_cause(skipped)
  File "/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/trainable.py", line 339, in train
    result = self.step()
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/algorithms/algorithm.py", line 853, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/algorithms/algorithm.py", line 2854, in _run_one_training_iteration
    results = self.training_step()
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/algorithms/dqn/dqn.py", line 404, in training_step
    new_sample_batch = synchronous_parallel_sample(
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/execution/rollout_ops.py", line 85, in synchronous_parallel_sample
    sample_batches = worker_set.foreach_worker(
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/worker_set.py", line 680, in foreach_worker
    handle_remote_call_result_errors(remote_results, self._ignore_worker_failures)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/worker_set.py", line 76, in handle_remote_call_result_errors
    raise r.get()
ray.exceptions.RayTaskError(ValueError): ray::RolloutWorker.apply() (pid=2357, ip=172.28.0.12, actor_id=abf634025efc2b91f8a8501f01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f2f226074f0>)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/utils/actor_manager.py", line 185, in apply
    raise e
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/utils/actor_manager.py", line 176, in apply
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/execution/rollout_ops.py", line 86, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/rollout_worker.py", line 696, in sample
    batches = [self.input_reader.next()]
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/sampler.py", line 92, in next
    batches = [self.get_data()]
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/env_runner_v2.py", line 344, in run
    outputs = self.step()
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/env_runner_v2.py", line 370, in step
    active_envs, to_eval, outputs = self._process_observations(
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/env_runner_v2.py", line 699, in _process_observations
    sample_batch = self._try_build_truncated_episode_multi_agent_batch(
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/env_runner_v2.py", line 1000, in _try_build_truncated_episode_multi_agent_batch
    episode.postprocess_episode(batch_builder=batch_builder, is_done=False)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/episode_v2.py", line 277, in postprocess_episode
    pre_batch = collector.build_for_training(policy.view_requirements)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/collectors/agent_collector.py", line 436, in build_for_training
    self._cache_in_np(np_data, data_col)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/collectors/agent_collector.py", line 613, in _cache_in_np
    cache_dict[key] = [_to_float_np_array(d) for d in self.buffers[key]]
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/collectors/agent_collector.py", line 613, in <listcomp>
    cache_dict[key] = [_to_float_np_array(d) for d in self.buffers[key]]
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/collectors/agent_collector.py", line 34, in _to_float_np_array
    arr = np.array(v)
ValueError: could not broadcast input array from shape (2,6) into shape (2,)

### Versions / Dependencies

Ray (2.8.1)
Gymnasium (0.29.1)

### Reproduction script

env_name = "graphenv"
 register_env(env_name, lambda config: GraphEnv(config))
env_name = "graphenv"
    register_env(env_name, lambda config: GraphEnv(config))
    run_config = DQNConfig()
    run_config = (
        run_config
        .resources(num_gpus=args.num_gpus)
        .framework("torch") #use tf2 for tensorflow and torch for pytorch
        .rollouts(num_rollout_workers=args.num_workers,
                  rollout_fragment_length=1)
        .environment(env=env_name,
                     env_config={"state": state,
                                 "max_num_children": N,
                                 "episode_steps":300000
                                 },
                  )
        .training(lr=args.lr,
                  train_batch_size=1,
                  model={"custom_model": custom_model ,
                         "custom_model_config": custom_model_config,
                         "fcnet_hiddens":[4],
                         "fcnet_activation":"relu",
                         "vf_share_layers":False,
                         "_disable_preprocessor_api":True,
                         "framestack":False,
                         },
                  dueling=False,
                  )
        .evaluation(evaluation_config={"explore": True},
                    evaluation_interval=1,
                    evaluation_duration=100,
                  )
        .debugging(log_level=args.log_level)
        .experimental(_disable_preprocessor_api=True,_disable_initialize_loss_from_dummy_batch=True)
    )
    stop = {
        "training_iteration": args.stop_iters,
        "timesteps_total": args.stop_timesteps,
        "episode_reward_mean": args.stop_reward,
    }

    tune.run(
        args.run,
        config=run_config.to_dict(),
        stop=stop,
    )

This is my neural network

class MySequential(TorchModelV2,nn.Module):

    def __init__(self, 
         obs_space, action_space, num_outputs, model_config,name,**kwargs
        ):
         self.num_outputs = 1
         TorchModelV2.__init__(self,obs_space=obs_space, action_space=action_space, num_outputs=1, model_config=model_config,name=name)
         nn.Module.__init__(self)
         self.embed_model = EmbedModel(num_layers=2,embed_dim=16,device=0,activation=F.relu,seed=11)#change seed
         self.eval_model = EvalModel(embed_dim=16,hidden_layer_size=8,device=0,activation=F.relu,seed=11)
         self.num_outputs = 1
    #At the beginning neural network creates a dummy batch filled with zeros to test the setup. 
    
    def forward(self, input_dict, state, seq_lens): #inputs - 1*1 ,3*3
        input = self.convertInput(input_dict['obs'])
        input_dict['obs'].pop('indices', None)
        input_dict['obs'].pop('values', None)
        embed = self.embed_model(input[1],input[0])
        eval = self.eval_model(embed).squeeze(0)
        #self._last_batch_size = 4 #change this
        return eval,state #[] is used as state 
    
    
    def convertInput(self,sol):
        N = sol['pst'].shape[1]
        sol['pst'] = torch.unsqueeze(sol['pst'], dim=0)
        indices = sol['indices'][0]
        values = sol['values'][0]
        adjacency_matrix = torch.sparse_coo_tensor(indices=indices,values=values,size = (N,N))
       
        return (sol['pst'],adjacency_matrix)

### Issue Severity

High: It blocks me from completing my task.

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
