### ISSUE TITLE
Ray Tune Out of memory when I using the 'tune.with_parameters'

### ISSUE THREAD

**Issue by luyuhengCN** [ray-project/ray#41575]
### What happened + What you expected to happen

I came across a problem of out-of-memory when I used the Ray tune with my model. I used the tune.with_parameters to wrap my dataset into the trainable module. The dataset is about 20G (My machine has a max memory of 160G). But ray tune reported the out-of-memory and stopped the training process when I ran 8 parameter search tasks in parallel. I'm a bit confused about the usage of the memory because the input dataset would not duplicate 8 times in my view. I wonder if there is something wrong with my usage of ray tune.

Bug report:
Traceback (most recent call last):
  File "/n10dat01/yhlu/anaconda3/envs/pytorch_py3.9/lib/python3.9/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/n10dat01/yhlu/anaconda3/envs/pytorch_py3.9/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/n10dat01/yhlu/anaconda3/envs/pytorch_py3.9/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/n10dat01/yhlu/anaconda3/envs/pytorch_py3.9/lib/python3.9/site-packages/ray/_private/worker.py", line 2565, in get
    raise value
ray.exceptions.OutOfMemoryError: Task was killed due to the node running low on memory.

Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. Set max_restarts and max_task_retries to enable retry when the task crashes due to OOM. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.

### Versions / Dependencies

python=3.9.18
ray=2.8.0
pytorch=1.13.1
cuda=11.6
CentOS7

### Reproduction script

def train_model(config, train_factor=None, train_target=None, 
                validate_factor=None, validate_target=None, 
                test_factor=None, test_target=None):
        
        model = TabNetRegressor(
        input_dim=input_size,
        n_steps=n_steps)
        model.fit(
        train_factor, train_target,
        eval_set=[(test_factor, test_target), (validate_factor, validate_target)],)

trainable_with_resources = tune.with_resources(
        tune.with_parameters(train_model, 
                             train_factor=train_factor, 
                             train_target=train_target, 
                             validate_factor=validate_factor, 
                             validate_target=validate_target, 
                             test_factor=test_factor,
                             test_target=test_target),
        resources = {"gpu": 0.125}
        )

tuner = tune.Tuner(
            trainable_with_resources,
            param_space=configs,)

### Issue Severity

High: It blocks me from completing my task.

**Comment by luyuhengCN** [comment]
Thanks for your reply! I checked my code and I found  the reason!
