### ISSUE TITLE
how to scale up number of agent in multi-agent environment

### ISSUE THREAD

**Issue by nyz1001** [ray-project/ray#4161]
I want to execute /flow/examples/rllib/multiagent_exps
When the av agent is one, it works well. However, increasing the number of av agents to two or more causes this problem.
How can I run on more than two agent?

============error log================

Loading configuration... done.
Success.
Loading configuration... done.
WARNING:ray.services:Failed to start the UI, you may need to run 'pip install jupyter'.
WARNING:ray.worker:WARNING: Falling back to serializing objects of type <class 'numpy.dtype'> by using pickle. This may be inefficient.
Loading configuration... done.
Success.
 Starting SUMO on port 54684
Loading configuration... done.
2019-02-26 11:35:43,951	INFO policy_evaluator.py:262 -- Creating policy evaluation worker 0 on CPU (please ignore any CUDA init errors)
2019-02-26 11:35:43.952871: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
/Users/nam/anaconda3/envs/flow/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Loading configuration... done.
Success.
 Starting SUMO on port 54686
Loading configuration... done.
Loading configuration... done.
Success.
 Starting SUMO on port 54687
Loading configuration... done.
2019-02-26 11:35:57,202	INFO policy_evaluator.py:262 -- Creating policy evaluation worker 1 on CPU (please ignore any CUDA init errors)
2019-02-26 11:35:57.203855: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-02-26 11:35:57,429	INFO policy_evaluator.py:262 -- Creating policy evaluation worker 2 on CPU (please ignore any CUDA init errors)
2019-02-26 11:35:57.430915: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
/Users/nam/anaconda3/envs/flow/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
/Users/nam/anaconda3/envs/flow/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
ERROR:ray.tune.trial_runner:Error processing event.
Traceback (most recent call last):
  File "/Users/nam/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 261, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/Users/nam/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 211, in fetch_result
    result = ray.get(trial_future[0])
  File "/Users/nam/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 2386, in get
    raise value
ray.worker.RayTaskError: ray_PPOAgent:train() (pid=40763, host=YOUNG-WOOui-MacBookPro.local)
  File "/Users/nam/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/agent.py", line 279, in train
    result = Trainable.train(self)
  File "/Users/nam/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/trainable.py", line 146, in train
    result = self._train()
  File "/Users/nam/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/ppo/ppo.py", line 101, in _train
    fetches = self.optimizer.step()
  File "/Users/nam/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/optimizers/sync_samples_optimizer.py", line 48, in step
    e.sample.remote() for e in self.remote_evaluators
ray.worker.RayTaskError: ray_PolicyEvaluator:sample() (pid=40765, host=YOUNG-WOOui-MacBookPro.local)
  File "/Users/nam/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 368, in sample
    batches = [self.input_reader.next()]
  File "/Users/nam/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/offline/input_reader.py", line 25, in next
    batches = [self.sampler.get_data()]
  File "/Users/nam/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 64, in get_data
    item = next(self.rollout_provider)
  File "/Users/nam/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 282, in _env_runner
    async_vector_env.send_actions(actions_to_send)
  File "/Users/nam/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/env/async_vector_env.py", line 298, in send_actions
    obs, rewards, dones, infos = env.step(agent_dict)
  File "/Users/nam/flow/flow/multiagent_envs/multiagent_env.py", line 85, in step
    self.apply_rl_actions(rl_actions)
  File "/Users/nam/flow/flow/multiagent_envs/multiagent_env.py", line 291, in apply_rl_actions
    self._apply_rl_actions(clipped_actions)
  File "/Users/nam/flow/flow/multiagent_envs/loop/wave_attenuation.py", line 91, in _apply_rl_actions
    self.k.vehicle.apply_acceleration(rl_ids, accel)
  File "/Users/nam/flow/flow/core/kernel/vehicle/traci.py", line 816, in apply_acceleration
    next_vel = max([this_vel + acc[i] * self.sim_step, 0])
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by ericl** [comment]
cc @eugenevinitsky

**Comment by eugenevinitsky** [comment]
Hi @owoo919 sorry to hear about this issue! I've moved it over to the Flow repo where someone should be able to respond to it better.

**Comment by pnp91** [comment]
Is there any solution for the above issue, because i am facing the same issue now @owoo919  @eugenevinitsky @ericl
