### ISSUE TITLE
BentoML Ray RpcError : Sent message larger than max

### ISSUE THREAD

**Issue by BaptisteLoquette** [ray-project/ray#41657]
### What happened + What you expected to happen

Hi, I use bentoml, the bento service is a simple BERT. I saw there was a bentoml.ray feature, I tried it. But got an error : 

`ray.exceptions.RpcError: Sent message larger than max (891627385 vs. 536870912)`

**Full Traceback** : 
```Traceback (most recent call last):
  File "/Users/bapt/Library/Python/3.9/lib/python/site-packages/ray/serve/scripts.py", line 518, in run
    handle = serve.run(app, host=host, port=port)
  File "/Users/bapt/Library/Python/3.9/lib/python/site-packages/ray/serve/api.py", line 574, in run
    client.deploy_application(
  File "/Users/bapt/Library/Python/3.9/lib/python/site-packages/ray/serve/_private/client.py", line 47, in check
    return f(self, *args, **kwargs)
  File "/Users/bapt/Library/Python/3.9/lib/python/site-packages/ray/serve/_private/client.py", line 328, in deploy_application
    ray.get(self._controller.deploy_application.remote(name, deployment_args_list))
  File "/Users/bapt/Library/Python/3.9/lib/python/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/Users/bapt/Library/Python/3.9/lib/python/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/bapt/Library/Python/3.9/lib/python/site-packages/ray/_private/worker.py", line 2547, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(KVStoreError): ray::ServeController.deploy_application() (pid=22400, ip=127.0.0.1, actor_id=8ba6ca15ce5103975af7741b01000000, repr=<ray.serve.controller.ServeController object at 0x10ff676d0>)
ray.exceptions.RpcError: Sent message larger than max (891627385 vs. 536870912)

During handling of the above exception, another exception occurred:

ray::ServeController.deploy_application() (pid=22400, ip=127.0.0.1, actor_id=8ba6ca15ce5103975af7741b01000000, repr=<ray.serve.controller.ServeController object at 0x10ff676d0>)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Users/bapt/Library/Python/3.9/lib/python/site-packages/ray/serve/controller.py", line 649, in deploy_application
    self.application_state_manager.apply_deployment_args(name, deployment_args_list)
  File "/Users/bapt/Library/Python/3.9/lib/python/site-packages/ray/serve/_private/application_state.py", line 751, in apply_deployment_args
    self._application_states[name].deploy(deployment_infos)
  File "/Users/bapt/Library/Python/3.9/lib/python/site-packages/ray/serve/_private/application_state.py", line 317, in deploy
    self._set_target_state(
  File "/Users/bapt/Library/Python/3.9/lib/python/site-packages/ray/serve/_private/application_state.py", line 229, in _set_target_state
    self._save_checkpoint_func(writeahead_checkpoints={self._name: target_state})
  File "/Users/bapt/Library/Python/3.9/lib/python/site-packages/ray/serve/_private/application_state.py", line 872, in _save_checkpoint_func
    self._kv_store.put(
  File "/Users/bapt/Library/Python/3.9/lib/python/site-packages/ray/serve/_private/storage/kv_store.py", line 68, in put
    raise KVStoreError(e.rpc_code)
ray.serve._private.storage.kv_store.KVStoreError: 8```

### Versions / Dependencies

MacOS 13.2.1
Python 3.9.6
Ray 2.7.0 (tried also 2.7.1) there's a problem with bentoml when using ≥2.8.0
bentoml 1.1.10

### Reproduction script

```
import bentoml

classifier = bentoml.ray.deployment(
  'sentiment_classifier:latest',
)
```

Then : `serve run bento_ray:classifier`

### Issue Severity

None

**Comment by anyscalesam** [comment]
@BaptisteLoquette  can you follow up with bentoml; we are not involved in maintaining bentoml's ray libs?

**Comment by kachadx** [comment]
怎么解决的

**Comment by rsong0606** [comment]
Exactly the same issue above, can someone explain how to solve this??
