### ISSUE TITLE
[Core] Extra maximum recursion depth + cloudpickle serialization error layers being raised

### ISSUE THREAD

**Issue by justinvyu** [ray-project/ray#41837]
### What happened + What you expected to happen

When there's a SYSTEM_ERROR like below, the original error gets shown correctly, but then there are 2 more layers talking about some maximum recursion depth being exceeded and some serialization error.

```
SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None. Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1670, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1770, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1676, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1616, in ray._raylet.execute_task.function_executor
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/worker_group.py", line 33, in __execute
    raise skipped from exception_cause(skipped)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 118, in discard_return_wrapper
    train_func(*args, **kwargs)
  File "/tmp/tmp5xyzm78r", line 381, in train_func
  File "/tmp/ray/session_2023-11-26_18-50-56_192888_2602/runtime_resources/pip/2fbc391b69d0ddcfd11a3c64ac92b3353c46f74c/virtualenv/lib/python3.9/site-packages/transformers/trainer.py", line 1543, in train
    return inner_training_loop(
  File "/tmp/ray/session_2023-11-26_18-50-56_192888_2602/runtime_resources/pip/2fbc391b69d0ddcfd11a3c64ac92b3353c46f74c/virtualenv/lib/python3.9/site-packages/transformers/trainer.py", line 1807, in _inner_training_loop
    self.deepspeed.step()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 2133, in step
    self._take_model_step(lr_kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 2039, in _take_model_step
    self.optimizer.step()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 1948, in step
    if self._overflow_check_and_loss_scale_update():
  File "/home/ray/anaconda3/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 1896, in _overflow_check_and_loss_scale_update
    self._update_scale(self.overflow)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 2249, in _update_scale
    self.loss_scaler.update_scale(has_overflow)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 175, in update_scale
    raise Exception(
Exception: Current loss scale already at minimum - cannot decrease scale anymore. Exiting run.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 733, in dump
    return Pickler.dump(self, obj)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 826, in reducer_override
    if sys.version_info[:2] < (3, 7) and _is_parametrized_type_hint(
RecursionError: maximum recursion depth exceeded in comparison

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 2068, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1964, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 1618, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1619, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1857, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 949, in ray._raylet.store_task_errors
  File "python/ray/_raylet.pyx", line 4226, in ray._raylet.CoreWorker.store_task_outputs
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/serialization.py", line 494, in serialize
    return self._serialize_to_msgpack(value)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/serialization.py", line 449, in _serialize_to_msgpack
    value = value.to_bytes()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/exceptions.py", line 32, in to_bytes
    serialized_exception=pickle.dumps(self),
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 88, in dumps
    cp.dump(obj)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 739, in dump
    raise pickle.PicklingError(msg) from e
_pickle.PicklingError: Could not pickle object as excessively deep recursion required.
```

### Versions / Dependencies

2.8, 2.9

### Reproduction script

```python
import pytorch_lightning
from ray.train.torch import TorchTrainer
from ray.train import ScalingConfig

def train_func(config):
    raise Exception
    pytorch_lightning

trainer = TorchTrainer(train_func, scaling_config=ScalingConfig(num_workers=1))
trainer.fit()
```

Examples:

https://buildkite.com/ray-project/postmerge/builds/1855#018c1abe-8c2b-4b58-84f0-0a2590b68170

### Issue Severity

Low: It annoys or frustrates me.

**Comment by justinvyu** [comment]
cc @rkooo567

**Comment by rynewang** [comment]
This should no longer happen since latest Ray already updated cloudpickle and no longer has _is_parametrized_type_hint.

**Comment by rynewang** [comment]
Still some mystery:

```
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 826, in reducer_override
    if sys.version_info[:2] < (3, 7) and _is_parametrized_type_hint(
```

The python is obviously 3.9 so the boolean after `and` should not run...?

**Comment by justinvyu** [comment]
Fixed by https://github.com/ray-project/ray/pull/43952
