### ISSUE TITLE
ray.data.Dataset.iter_tf_batches() change the length of binary type

### ISSUE THREAD

**Issue by spinezhang** [ray-project/ray#41856]
### What happened + What you expected to happen

I'm working on distributed image training based on Ray framework, ray version is 2.8.1, it works fine for pytorch. But when I try to use same data source (ray.data.Dataset from DeltalLake table), it cannot work probably due to the image binary data is changed in iter_tf_batches(). But if I change to use iter_batches(), it works fine.
The source data is torchvision CIFAR10 dataset, each picture is in 32*32*3 format and 3072 bytes. I load them into ray.data.Dataset, then use tf.data.Dataset.from_generator() to convert and transform to tensor, the problem is that some of pictures data size is changed and failed to transform. 
For easy to duplicate the bug, I use the same data source and create ray.data.Dataset from local torchvision file in following reproduction script.

Error message is:

```
python ray_iter_tf_batches_bug.py
2023-12-13 13:26:52,244	INFO worker.py:1489 -- Connecting to existing Ray cluster at address: 127.0.0.1:6379...
2023-12-13 13:26:52,249	INFO worker.py:1664 -- Connected to Ray cluster. View the dashboard at 127.0.0.1:8265 
2023-12-13 13:26:52,787	INFO tune.py:595 -- [output] This will use the new output engine with verbosity 1. To disable the new output and use the legacy output engine, set the environment variable RAY_AIR_NEW_OUTPUT=0. For more information, please see https://github.com/ray-project/ray/issues/36949

View detailed results here: /tmp/ray/TensorflowTrainer_2023-12-13_13-26-52
To visualize your results with TensorBoard, run: `tensorboard --logdir /Users/spine/ray_results/TensorflowTrainer_2023-12-13_13-26-52`

Training started with configuration:
╭───────────────────────────────────────╮
│ Training config                       │
├───────────────────────────────────────┤
│ train_loop_config/batch_size       64 │
│ train_loop_config/epochs            3 │
│ train_loop_config/num_workers       4 │
│ train_loop_config/use_gpu       False │
╰───────────────────────────────────────╯
(TensorflowTrainer pid=14734) Starting distributed worker processes: ['14736 (127.0.0.1)', '14737 (127.0.0.1)', '14738 (127.0.0.1)', '14739 (127.0.0.1)']
(SplitCoordinator pid=14741) Auto configuring locality_with_output=['753796c049dfe347798b2e347fcf75e5c56eb6d54e26a4f212522618', '753796c049dfe347798b2e347fcf75e5c56eb6d54e26a4f212522618', '753796c049dfe347798b2e347fcf75e5c56eb6d54e26a4f212522618', '753796c049dfe347798b2e347fcf75e5c56eb6d54e26a4f212522618']
(RayTrainWorker pid=14738) Epoch 1/3
(SplitCoordinator pid=14740) Executing DAG InputDataBuffer[Input] -> OutputSplitter[split(4, equal=True)]                                                                                                                                      
(SplitCoordinator pid=14740) Execution config: ExecutionOptions(resource_limits=ExecutionResources(cpu=None, gpu=None, object_store_memory=None), locality_with_output=['753796c049dfe347798b2e347fcf75e5c56eb6d54e26a4f212522618', '753796c049dfe347798b2e347fcf75e5c56eb6d54e26a4f212522618', '753796c049dfe347798b2e347fcf75e5c56eb6d54e26a4f212522618', '753796c049dfe347798b2e347fcf75e5c56eb6d54e26a4f212522618'], preserve_order=False, actor_locality_enabled=True, verbose_progress=False)
(SplitCoordinator pid=14740) Tip: For detailed progress reporting, run `ray.data.DataContext.get_current().execution_options.verbose_progress = True`
(RayTrainWorker pid=14737) 2023-12-13 13:27:01.472746: W tensorflow/core/framework/op_kernel.cc:1827] INVALID_ARGUMENT: ValueError: cannot reshape array of size 3065 into shape (32,32,3)
(RayTrainWorker pid=14737) Traceback (most recent call last):
(RayTrainWorker pid=14737) 
(RayTrainWorker pid=14737)   File "/Users/spine/conda/envs/tensor/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 270, in __call__
(RayTrainWorker pid=14737)     ret = func(*args)
(RayTrainWorker pid=14737) 
(RayTrainWorker pid=14737)   File "/Users/spine/conda/envs/tensor/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 643, in wrapper
(RayTrainWorker pid=14737)     return func(*args, **kwargs)
(RayTrainWorker pid=14737) 
(RayTrainWorker pid=14737)   File "/Users/spine/conda/envs/tensor/lib/python3.10/site-packages/tensorflow/python/data/ops/from_generator_op.py", line 198, in generator_py_func
(RayTrainWorker pid=14737)     values = next(generator_state.get_iterator(iterator_id))
(RayTrainWorker pid=14737) 
(RayTrainWorker pid=14737)   File "/Volumes/work/VM/disk1/raydemo/ray_iter_tf_batches_bug.py", line 79, in to_tensor_iterator
(RayTrainWorker pid=14737)     images = tf.convert_to_tensor(list(map(lambda x: image_transform(x.numpy()), batch['image'])))
(RayTrainWorker pid=14737) 
(RayTrainWorker pid=14737)   File "/Volumes/work/VM/disk1/raydemo/ray_iter_tf_batches_bug.py", line 79, in <lambda>
(RayTrainWorker pid=14737)     images = tf.convert_to_tensor(list(map(lambda x: image_transform(x.numpy()), batch['image'])))
(RayTrainWorker pid=14737) 
(RayTrainWorker pid=14737)   File "/Volumes/work/VM/disk1/raydemo/ray_iter_tf_batches_bug.py", line 70, in image_transform
(RayTrainWorker pid=14737)     image = image.reshape(32, 32, 3)
(RayTrainWorker pid=14737) 
(RayTrainWorker pid=14737) ValueError: cannot reshape array of size 3065 into shape (32,32,3)
(RayTrainWorker pid=14737) 
(RayTrainWorker pid=14737) 
```

### Versions / Dependencies

ray version: 2.8.1
TensorFlow: tensorflow-macos          2.13.0
Numpy: 1.23.2 
pyarrow: 14.0.1

### Reproduction script

```
import os

import pickle
import numpy as np
import ray
import pyarrow as pa
from ray import train
from ray.air import ScalingConfig, RunConfig, CheckpointConfig
from torchvision import datasets

import tensorflow as tf
from ray.train.tensorflow import TensorflowTrainer, prepare_dataset_shard
from keras import layers, Sequential


class CnnTensorModel(Sequential):
    def __init__(self, num_classes=10):
        super().__init__([
            layers.Conv2D(32, (3, 3), padding='same', activation='relu', input_shape=(32, 32, 3)),
            layers.BatchNormalization(),

            layers.Conv2D(32, (3, 3), padding='same', activation='relu'),
            layers.BatchNormalization(),
            layers.MaxPooling2D((2, 2)),

            layers.Conv2D(64, (3, 3), padding='same', activation='relu'),
            layers.BatchNormalization(),
            layers.MaxPooling2D((2, 2)),

            layers.Conv2D(128, (3, 3), padding='same', activation='relu'),
            layers.BatchNormalization(),
            layers.MaxPooling2D((2, 2)),

            layers.Flatten(),
            layers.Dropout(0.2),

            # Hidden layer
            layers.Dense(1024, activation='relu'),
            layers.Dropout(0.2),

            layers.Dense(num_classes, activation='softmax')
        ], name='cnn')

        self.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


def torchvision_ray_dataset(path, is_train=True):
    if is_train:
        file_list = [f"data_batch_{i + 1}" for i in range(5)]
    else:
        file_list = ["test_batch"]

    images = []
    labels = []
    for file_name in file_list:
        file_path = os.path.join(path, file_name)
        with open(file_path, 'rb') as f:
            entry = pickle.load(f, encoding='latin1')
            images.extend(map(lambda x: x.tobytes(), entry['data']))
            if 'labels' in entry:
                labels.extend(entry['labels'])
            f.close()
    pa_table = pa.table([images, labels], names=["image", "label"])
    return ray.data.from_arrow(pa_table)


def to_tf_dataset(dataset, batch_size):
    def image_transform(pic):
        image = np.array([np.frombuffer(pic, dtype=np.uint8)]).astype(np.float32) / 255.0
        image = image.reshape(32, 32, 3)
        return image

    def to_tensor_iterator():
        # !!! FATAL, iter_tf_batches has critical bug, somtimes it will change the bytes array size, this cause
        # ImageDataBuilder.image_transform() transpose array failed.

        for batch in dataset.iter_tf_batches(batch_size=batch_size):
        # for batch in dataset.iter_batches(batch_size=batch_size):
            images = tf.convert_to_tensor(list(map(lambda x: image_transform(x.numpy()), batch['image'])))
            # images = tf.convert_to_tensor(list(map(lambda x: image_transform(x), batch['image'])))
            images.set_shape((None, 32, 32, 3))
            label = tf.cast(tf.expand_dims(batch["label"], 1), tf.int64)
            yield images, label

    output_signature = (tf.TensorSpec(shape=(None, 32, 32, 3), dtype=tf.float32), tf.TensorSpec(shape=(None, 1), dtype=tf.int64))
    tf_dataset = tf.data.Dataset.from_generator(to_tensor_iterator, output_signature=output_signature)
    return prepare_dataset_shard(tf_dataset)


def train_loop_func(config):
    strategy = tf.distribute.MultiWorkerMirroredStrategy()

    results = {}
    with strategy.scope():
        model = CnnTensorModel(num_classes=10)
        train_dataset = train.get_dataset_shard("train")
        test_dataset = train.get_dataset_shard("test")
        train_tf_dataset = to_tf_dataset(dataset=train_dataset, batch_size=config["batch_size"])
        test_tf_dataset = to_tf_dataset(dataset=test_dataset, batch_size=config["batch_size"])

        history = model.fit(train_tf_dataset, validation_data=test_tf_dataset, epochs=config["epochs"])
        results = history.history
    return results


def ray_train_tf(train_dataset, test_dataset):
    scaling_config = ScalingConfig(num_workers=4, use_gpu=False)
    train_config = {"use_gpu": False, "epochs": 3, "batch_size": 64, "num_workers": 4}

    trainer = TensorflowTrainer(
        train_loop_per_worker=train_loop_func,
        train_loop_config=train_config,
        scaling_config=scaling_config,
        run_config=RunConfig(storage_path='/tmp/ray'),
        datasets={'train': train_dataset, 'test': test_dataset}
    )

    return trainer.fit()


if __name__ == "__main__":
    # In my project, the data is stored in delta spark, and I use DeltaTable and read_parquet to create ray.data.Dataset
    # For easy to duplicate the bug, I use the same data source and create ray.data.Dataset from local torchvision file (my
    # project support both pytorch and tensorflow framework).
    root_path = os.getcwd()
    data_path = os.path.join(root_path, "cifar-10-batches-py")
    if not os.path.exists(data_path):
        datasets.CIFAR10(root=root_path, train=True, download=True)
    train_data = torchvision_ray_dataset(data_path, is_train=True)
    test_data = torchvision_ray_dataset(data_path, is_train=False)
    result = ray_train_tf(train_data, test_data)
    print(result)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by raulchen** [comment]
@spinezhang your script works well for me with latest Ray + PyArrow 14.0.1. It may have been fixed. Closing this issue. If you still see it with the latest Ray, feel free to reopen.
