### ISSUE TITLE
Install ray[all] but faced with an error

### ISSUE THREAD

**Issue by Crer-lu** [ray-project/ray#42065]
### What happened + What you expected to happen

  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmp826n_87u get_requires_for_build_wheel /tmp/tmp0ee78ofv
       cwd: /tmp/pip-install-qx861h9x/gpustat
  Complete output (59 lines):
  running egg_info
  writing gpustat.egg-info/PKG-INFO
  writing dependency_links to gpustat.egg-info/dependency_links.txt
  writing entry points to gpustat.egg-info/entry_points.txt
  writing requirements to gpustat.egg-info/requires.txt
  writing top-level names to gpustat.egg-info/top_level.txt
  listing git files failed - pretending there aren't any
  Traceback (most recent call last):
    File "/tmp/tmp826n_87u", line 280, in <module>
      main()
    File "/tmp/tmp826n_87u", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmp826n_87u", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/usr/local/lib/python3.8/dist-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/usr/local/lib/python3.8/dist-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/usr/local/lib/python3.8/dist-packages/setuptools/build_meta.py", line 482, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/usr/local/lib/python3.8/dist-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 101, in <module>
    File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 973, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 992, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/dist-packages/setuptools/command/egg_info.py", line 308, in run
      self.find_sources()
    File "/usr/local/lib/python3.8/dist-packages/setuptools/command/egg_info.py", line 316, in find_sources
      mm.run()
    File "/usr/local/lib/python3.8/dist-packages/setuptools/command/egg_info.py", line 560, in run
      self.add_defaults()
    File "/usr/local/lib/python3.8/dist-packages/setuptools/command/egg_info.py", line 600, in add_defaults
      rcfiles = list(walk_revctrl())
    File "/usr/local/lib/python3.8/dist-packages/setuptools/command/sdist.py", line 20, in walk_revctrl
      for item in ep.load()(dirname):
    File "/usr/local/lib/python3.8/dist-packages/setuptools_scm/integration.py", line 95, in find_files
      command = ep.load()
    File "/usr/local/lib/python3.8/dist-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
      module = import_module(match.group('module'))
    File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
  ModuleNotFoundError: No module named 'setuptools_scm._file_finders'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmp826n_87u get_requires_for_build_wheel /tmp/tmp0ee78ofv Check the logs for full command output.

### Versions / Dependencies

python 3.8
Ubuntu 20.04.6 LTS

### Reproduction script

pip install -U "ray[all]" -i https://pypi.douban.com/simple

### Issue Severity

High: It blocks me from completing my task.

**Comment by anyscalesam** [comment]
@Crer-lu is this off the latest nightly wheel only? are you able to repro with either latest stable ray29?
