### ISSUE TITLE
[Core] get_all_modules too eager / Ray fails due to missing module "async_timeout"

### ISSUE THREAD

**Issue by dongreenberg** [ray-project/ray#42120]
### What happened + What you expected to happen

There seems to be an issue either with a missing dependency, or some kind of overly strict dependency checking to start the dashboard, or both.

I just updated to Python 3.11, and updated Ray accordingly. It immediately failed when I tried to use it locally. I opened a python interpreter to try `import ray; ray.put(5)`, and saw this failure:
```
(raylet) [2023-12-28 05:07:55,580 E 52187 15810217] (raylet) agent_manager.cc:135: The raylet exited immediately because the Ray agent failed. The raylet fate shares with the agent. This can happen because the Ray agent was unexpectedly killed or failed. Agent can fail when
(raylet) - The version of `grpcio` doesn't follow Ray's requirement. Agent can segfault with the incorrect `grpcio` version. Check the grpcio version `pip freeze | grep grpcio`.
(raylet) - The agent failed to start because of unexpected error or port conflict. Read the log `cat /tmp/ray/session_latest/logs/dashboard_agent.log`. You can find the log file structure here https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure.
(raylet) - The agent is killed by the OS (e.g., out of memory).
```

When I look at the dashboard log I see this:

```
cat /tmp/ray/session_latest/logs/dashboard_agent.log
2023-12-28 05:07:55,164	INFO agent.py:121 -- Parent pid is 52187
2023-12-28 05:07:55,165	INFO agent.py:147 -- Dashboard agent grpc address: 127.0.0.1:64444
2023-12-28 05:07:55,167	INFO utils.py:112 -- Get all modules by type: DashboardAgentModule
2023-12-28 05:07:55,518	INFO utils.py:123 -- Module ray.dashboard.modules.test.test_agent cannot be loaded because we cannot import all dependencies. Install this module using `pip install 'ray[default]'` for the full dashboard functionality. Error: No module named 'async_timeout'
2023-12-28 05:07:55,518	INFO utils.py:130 -- Although `pip install 'ray[default]'` is downloaded, module couldn't be imported`
2023-12-28 05:07:55,519	ERROR agent.py:562 -- Agent is working abnormally. It will exit immediately.
Traceback (most recent call last):
  File "/Users/donny/miniconda3/envs/runhouse/lib/python3.11/site-packages/ray/dashboard/agent.py", line 560, in <module>
    loop.run_until_complete(agent.run())
  File "/Users/donny/miniconda3/envs/runhouse/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/donny/miniconda3/envs/runhouse/lib/python3.11/site-packages/ray/dashboard/agent.py", line 293, in run
    modules = self._load_modules()
              ^^^^^^^^^^^^^^^^^^^^
  File "/Users/donny/miniconda3/envs/runhouse/lib/python3.11/site-packages/ray/dashboard/agent.py", line 172, in _load_modules
    agent_cls_list = dashboard_utils.get_all_modules(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/donny/miniconda3/envs/runhouse/lib/python3.11/site-packages/ray/dashboard/utils.py", line 134, in get_all_modules
    raise e
  File "/Users/donny/miniconda3/envs/runhouse/lib/python3.11/site-packages/ray/dashboard/utils.py", line 121, in get_all_modules
    importlib.import_module(name)
  File "/Users/donny/miniconda3/envs/runhouse/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/donny/miniconda3/envs/runhouse/lib/python3.11/site-packages/ray/dashboard/modules/test/test_agent.py", line 6, in <module>
    import ray.dashboard.modules.test.test_utils as test_utils
  File "/Users/donny/miniconda3/envs/runhouse/lib/python3.11/site-packages/ray/dashboard/modules/test/test_utils.py", line 3, in <module>
    import async_timeout
ModuleNotFoundError: No module named 'async_timeout'
```

When I install async_timeout, ray works again. The strange thing is that this module only appears to be used minimally inside Ray, [only in a couple tests](https://github.com/search?q=repo%3Aray-project%2Fray%20async_timeout&type=code) that I am not running. So I don't see why the dashboard would fail here, other than attempting to collect the modules too eagerly with this `get_all_modules`.

### Versions / Dependencies

Ray 2.6.3
Python 3.11.4
conda 23.11.0
OS X
### Reproduction script

```
pip uninstall -y async_timeout
python -c "import ray; ray.put(5)"
```

### Issue Severity

None

**Comment by jjyao** [comment]
This issue has been fixed in the latest Ray version 2.9.0.
