### ISSUE TITLE
[<Ray component: Core] benchmark run failure for pytorch follow the guide 

### ISSUE THREAD

**Issue by gaowayne** [ray-project/ray#42136]
### What happened + What you expected to happen

I follow this https://docs.ray.io/en/latest/train/benchmarks.html
I run below python workloads/torch_benchmark.py run --num-runs 3 --num-epochs 20 --num-workers 4 --cpus-per-worker 8
then I got below error even I specify the RAY_ADDRESS
```
dcg@oq1:/mnt/nvme1n1/ray/release/air_tests/air_benchmarks$ export RAY_ADDRESS="127.0.0.1:8265"
dcg@oq1:/mnt/nvme1n1/ray/release/air_tests/air_benchmarks$ python3 workloads/torch_benchmark.py run --num-runs 3 --num-epochs 20 --num-workers 4 --cpus-per-worker 8
2023-12-31 02:05:37,612 INFO worker.py:1405 -- Using address 127.0.0.1:8265 set in the environment variable RAY_ADDRESS
2023-12-31 02:05:37,612 INFO worker.py:1540 -- Connecting to existing Ray cluster at address: 10.74.40.10:8265...
Traceback (most recent call last):
  File "/home/dcg/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 1680, in init
    _global_node = ray._private.node.Node(
  File "/home/dcg/.local/lib/python3.10/site-packages/ray/_private/node.py", line 153, in __init__
    self._init_gcs_client()
  File "/home/dcg/.local/lib/python3.10/site-packages/ray/_private/node.py", line 730, in _init_gcs_client
    raise RuntimeError(
RuntimeError: Failed to connect to GCS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/nvme1n1/ray/release/air_tests/air_benchmarks/workloads/torch_benchmark.py", line 599, in <module>
    main()
  File "/mnt/nvme1n1/ray/release/air_tests/air_benchmarks/workloads/torch_benchmark.py", line 595, in main
    return cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/nvme1n1/ray/release/air_tests/air_benchmarks/workloads/torch_benchmark.py", line 433, in run
    ray.init("auto")
  File "/home/dcg/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/dcg/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 1696, in init
    raise ConnectionError
ConnectionError

```

### Versions / Dependencies

github latest version

### Reproduction script

I follow this https://docs.ray.io/en/latest/train/benchmarks.html
I run below python workloads/torch_benchmark.py run --num-runs 3 --num-epochs 20 --num-workers 4 --cpus-per-worker 8
then I got below error even I specify the RAY_ADDRESS
```
dcg@oq1:/mnt/nvme1n1/ray/release/air_tests/air_benchmarks$ export RAY_ADDRESS="127.0.0.1:8265"
dcg@oq1:/mnt/nvme1n1/ray/release/air_tests/air_benchmarks$ python3 workloads/torch_benchmark.py run --num-runs 3 --num-epochs 20 --num-workers 4 --cpus-per-worker 8
2023-12-31 02:05:37,612 INFO worker.py:1405 -- Using address 127.0.0.1:8265 set in the environment variable RAY_ADDRESS
2023-12-31 02:05:37,612 INFO worker.py:1540 -- Connecting to existing Ray cluster at address: 10.74.40.10:8265...
Traceback (most recent call last):
  File "/home/dcg/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 1680, in init
    _global_node = ray._private.node.Node(
  File "/home/dcg/.local/lib/python3.10/site-packages/ray/_private/node.py", line 153, in __init__
    self._init_gcs_client()
  File "/home/dcg/.local/lib/python3.10/site-packages/ray/_private/node.py", line 730, in _init_gcs_client
    raise RuntimeError(
RuntimeError: Failed to connect to GCS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/nvme1n1/ray/release/air_tests/air_benchmarks/workloads/torch_benchmark.py", line 599, in <module>
    main()
  File "/mnt/nvme1n1/ray/release/air_tests/air_benchmarks/workloads/torch_benchmark.py", line 595, in main
    return cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/nvme1n1/ray/release/air_tests/air_benchmarks/workloads/torch_benchmark.py", line 433, in run
    ray.init("auto")
  File "/home/dcg/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/dcg/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 1696, in init
    raise ConnectionError
ConnectionError

```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by stephanie-wang** [comment]
Can you check if there is indeed a Ray server running at "127.0.0.1:8265"? Otherwise would be helpful to get the output of `ray logs` to see why it wasn't able to connect.

**Comment by gaowayne** [comment]
> Can you check if there is indeed a Ray server running at "127.0.0.1:8265"? Otherwise would be helpful to get the output of `ray logs` to see why it wasn't able to connect.

I am sure I did not run another ray server. maybe let us fix orginal issue. if I just run this benchmark with latest code download. I see below error.
```
dcg@oq1:/mnt/nvme1n1/ray/release/air_tests/air_benchmarks$ python3 workloads/torch_benchmark.py run --num-runs 3 --num-epochs 20 --num-workers 4 --cpus-per-worker 8
Traceback (most recent call last):
  File "/mnt/nvme1n1/ray/release/air_tests/air_benchmarks/workloads/torch_benchmark.py", line 599, in <module>
    main()
  File "/mnt/nvme1n1/ray/release/air_tests/air_benchmarks/workloads/torch_benchmark.py", line 595, in main
    return cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/nvme1n1/ray/release/air_tests/air_benchmarks/workloads/torch_benchmark.py", line 433, in run
    ray.init("auto")
  File "/home/dcg/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/dcg/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 1537, in init
    bootstrap_address = services.canonicalize_bootstrap_address(address, _temp_dir)
  File "/home/dcg/.local/lib/python3.10/site-packages/ray/_private/services.py", line 530, in canonicalize_bootstrap_address
    addr = get_ray_address_from_environment(addr, temp_dir)
  File "/home/dcg/.local/lib/python3.10/site-packages/ray/_private/services.py", line 423, in get_ray_address_from_environment
    raise ConnectionError(
ConnectionError: Could not find any running Ray instance. Please specify the one to connect to by setting `--address` flag or `RAY_ADDRESS` environment variable.
dcg@oq1:/mnt/nvme1n1/ray/release/air_tests/air_benchmarks$ 
```
if I run ray logs cluster, I see this error:
```
dcg@oq1:~$ ray logs cluster
Usage: ray logs cluster [OPTIONS] [GLOB_FILTER]
Try 'ray logs cluster --help' for help.

Error: Could not find any running Ray instance. Please specify the one to connect to by setting the `--address` flag or `RAY_ADDRESS` environment variable.
dcg@oq1:~$ 
```

this is just example benchmark, I suppose it should run without problem

**Comment by gaowayne** [comment]
this problem still exist, I just update Ray to nightly build then run this benchmark, it will failed.
```
root@oq1:/mnt/nvme1n1/pfray/ray/release/air_tests/air_benchmarks# python workloads/torch_benchmark.py run --num-runs 3 --num-epochs 20 --num-workers 4 --cpus-per-worker 8
Traceback (most recent call last):
  File "/mnt/nvme1n1/pfray/ray/release/air_tests/air_benchmarks/workloads/torch_benchmark.py", line 581, in <module>
    main()
  File "/mnt/nvme1n1/pfray/ray/release/air_tests/air_benchmarks/workloads/torch_benchmark.py", line 577, in main
    return cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/nvme1n1/pfray/ray/release/air_tests/air_benchmarks/workloads/torch_benchmark.py", line 415, in run
    ray.init("auto")
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 1572, in init
    bootstrap_address = services.canonicalize_bootstrap_address(address, _temp_dir)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/services.py", line 530, in canonicalize_bootstrap_address
    addr = get_ray_address_from_environment(addr, temp_dir)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/services.py", line 423, in get_ray_address_from_environment
    raise ConnectionError(
ConnectionError: Could not find any running Ray instance. Please specify the one to connect to by setting `--address` flag or `RAY_ADDRESS` environment variable.
root@oq1:/mnt/nvme1n1/pfray/ray/release/air_tests/air_benchmarks# 
```
but I can run python workloads/pytorch_training_e2e.py --data-size-gb=1 with great result. why?
