### ISSUE TITLE
Test failure in stress_tests.py, couldn't start Redis.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#423]
I've seen the following test failure fairly frequently. The error happens in the test

```
python test/stress_tests.py
```

And the error will look like the following.

```python
======================================================================
ERROR: testNondeterministicTask (__main__.ReconstructionTestsMultinode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/stress_tests.py", line 160, in setUp
    driver_mode=ray.SILENT_MODE)
  File "/usr/local/lib/python2.7/dist-packages/ray-0.0.1-py2.7.egg/ray/worker.py", line 973, in _init
    num_gpus=num_gpus)
  File "/usr/local/lib/python2.7/dist-packages/ray-0.0.1-py2.7.egg/ray/services.py", line 1046, in start_ray_head
    num_gpus=num_gpus)
  File "/usr/local/lib/python2.7/dist-packages/ray-0.0.1-py2.7.egg/ray/services.py", line 790, in start_ray_processes
    cleanup=cleanup)
  File "/usr/local/lib/python2.7/dist-packages/ray-0.0.1-py2.7.egg/ray/services.py", line 301, in start_redis
    raise Exception("Couldn't start Redis.")
Exception: Couldn't start Redis.
```

Note that this happens in a variety of tests within `stress_tests.py`.

This is taken from https://s3.amazonaws.com/archive.travis-ci.org/jobs/217453528/log.txt, and the output for the relevant test was the following:

```
testNondeterministicTask (__main__.ReconstructionTestsMultinode) ... 59178
[INFO] (/home/travis/build/ray-project/ray/src/plasma/plasma_store.cc:865) Allowing the Plasma store to use up to 0.25GB of memory.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[INFO] (/home/travis/build/ray-project/ray/src/plasma/plasma_store.cc:865) Allowing the Plasma store to use up to 0.25GB of memory.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[INFO] (/home/travis/build/ray-project/ray/src/plasma/plasma_store.cc:865) Allowing the Plasma store to use up to 0.25GB of memory.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[INFO] (/home/travis/build/ray-project/ray/src/plasma/plasma_store.cc:865) Allowing the Plasma store to use up to 0.25GB of memory.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
6300:M 01 Apr 06:11:14.215 # Creating Server TCP listening socket *:59178: bind: Address already in use
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
[WARN] (/home/travis/build/ray-project/ray/src/common/state/redis.cc:100) Failed to connect to Redis, retrying.
ERROR
```

**Comment by robertnishihara** [comment]
Haven't seen this in a while.
