### ISSUE TITLE
[serve] GET rest api fails when there are autoscaling deployments

### ISSUE THREAD

**Issue by zcin** [ray-project/ray#42319]
### What happened + What you expected to happen

The REST api json-serializes the response from the controller `get_serve_instance_details()`. For autoscaling deployments, their details contains a bytes object which is the `serialized_policy_def` which is part of the autoscaling config. This bytes object fails to serialize in the REST api. This affects `serve status` and `serve config` because they go through the rest api.

### Versions / Dependencies

baad921b9131e1768bfb15c11e4372b0284a1af6

### Reproduction script

Deploy an autoscaling application.
Output of `serve status`:
```
Traceback (most recent call last):
  File "/Users/cindyz/miniforge3/envs/ray/bin/serve", line 33, in <module>
    sys.exit(load_entry_point('ray', 'console_scripts', 'serve')())
  File "/Users/cindyz/miniforge3/envs/ray/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cindyz/miniforge3/envs/ray/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/cindyz/miniforge3/envs/ray/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cindyz/miniforge3/envs/ray/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cindyz/miniforge3/envs/ray/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/cindyz/ray/python/ray/serve/scripts.py", line 637, in status
    **ServeSubmissionClient(address).get_serve_details()
  File "/Users/cindyz/ray/python/ray/dashboard/modules/serve/sdk.py", line 72, in get_serve_details
    self._raise_error(response)
  File "/Users/cindyz/ray/python/ray/dashboard/modules/dashboard_sdk.py", line 283, in _raise_error
    raise RuntimeError(
RuntimeError: Request failed with status code 500: Traceback (most recent call last):
  File "/Users/cindyz/ray/python/ray/dashboard/optional_utils.py", line 291, in decorator
    return await f(self, *args, **kwargs)
  File "/Users/cindyz/ray/python/ray/dashboard/modules/serve/serve_rest_api_impl.py", line 61, in check
    return await func(self, *args, **kwargs)
  File "/Users/cindyz/ray/python/ray/dashboard/modules/serve/serve_rest_api_impl.py", line 137, in get_serve_instance_details
    text=json.dumps(details),
  File "/Users/cindyz/miniforge3/envs/ray/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Users/cindyz/miniforge3/envs/ray/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/cindyz/miniforge3/envs/ray/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/cindyz/miniforge3/envs/ray/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

### Issue Severity

None

**Comment by sihanwang41** [comment]
@zcin , is this 2.9 issue or master?

**Comment by GeneDer** [comment]
@sihanwang41 This is in master only. It's related to a PR from me merged on Monday
