### ISSUE TITLE
Unable to deploy service after changing dashboard port

### ISSUE THREAD

**Issue by zhangch-ss** [ray-project/ray#42324]
### What happened + What you expected to happen

Use ray start --head --dashboard-host=0.0.0.0 --dashboard-port=8088 to start the ray cluster. Deploy the serve service, serve deploy config.yaml, and get the following error:

Traceback (most recent call last):
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/root/miniconda3/envs/lavis/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/miniconda3/envs/lavis/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/root/miniconda3/envs/lavis/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5918451a90>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8265): Max retries exceeded with url: /api/ray/version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5918451a90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 264, in _check_connection_and_version_with_url
    r = self._do_request("GET", url)
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 308, in _do_request
    return requests.request(
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8265): Max retries exceeded with url: /api/ray/version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5918451a90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/lavis/bin/serve", line 8, in <module>
    sys.exit(cli())
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/ray/serve/scripts.py", line 622, in status
    **ServeSubmissionClient(address).get_serve_details()
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/ray/dashboard/modules/serve/sdk.py", line 61, in __init__
    self._check_connection_and_version_with_url(
  File "/root/miniconda3/envs/lavis/lib/python3.8/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 280, in _check_connection_and_version_with_url
    raise ConnectionError(
ConnectionError: Failed to connect to Ray at address: http://localhost:8265.

### Versions / Dependencies

ray 2.9.0
Python 3.8.18
Linux Ubuntu

### Reproduction script

ray start --head --dashboard-host=0.0.0.0 --dashboard-port=8088

serve deploy config.yaml

config.yaml，![image](https://github.com/ray-project/ray/assets/57099533/21ab26c1-29ae-45b8-bcb6-c41a9324192a)

### Issue Severity

None

**Comment by sihanwang41** [comment]
Hi @zhangch-ss , can you try add `--address=` argument with `serve run`? https://docs.ray.io/en/latest/serve/api/index.html#serve-run
