### ISSUE TITLE
[data] TypeError: ‘NoneType’ object is not callable error from ray data `map_batches`

### ISSUE THREAD

**Issue by arunppsg** [ray-project/ray#42382]
### What happened + What you expected to happen

Observing a `TypeError` after completion of `map_batches` in ray data.
```py
Exception ignored in: <function Dataset.__del__ at 0x2aad7d3a0>
Traceback (most recent call last):
  File "/Users/arun/Applications/miniconda3/envs/dc/lib/python3.9/site-packages/ray/data/dataset.py", line 5148, in __del__
TypeError: 'NoneType' object is not callable
```

The job runs successfully, but it throws the above error which I am not able to catch as well. I think the error is specific to macOS because I was not able to reproduce the error in a linux machine.

### Versions / Dependencies

Python version: 3.9.17
Ray version: 2.9.0
OS: macOS 13.5 (M1 Chip)

### Reproduction script

Steps to reproduce:
1. Install deepchem (`pip install deepchem`)
2. Run the following code snippet:
```py
import deepchem as dc
import os
import ray

from typing import Dict, Any, Iterable, Optional, List
from functools import partial

# prepare data
import csv

with open('smiles.csv', 'w', newline='') as csvfile:
    fieldnames = ['smiles', 'logp']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

    writer.writeheader()
    for i in range(1000):
        writer.writerow({'smiles': 'Cc1[nH]ccc1C(=O)N[C@@H](C)CNC(=O)c1cccc2[nH]ccc21', 'logp': 2})

ray.init(num_cpus=4)

def featurize(row: Dict[str, Any],
              featurizer,
              x='smiles',
              y='logp') -> Dict[str, Any]:
    return row


featurize_batches = partial(featurize, featurizer=dc.feat.CircularFingerprint())

# Featurizing a dataset
ds = ray.data.read_csv('smiles.csv').map_batches(featurize_batches)

# Writing a dataset to disk
ds.write_parquet('data-dir')

for i, batch in enumerate(ds.iter_batches()):
    print (i)

ray.shutdown()
```

The above code throws the following traceback:
```py
No normalization for AvgIpc. Feature removed!
Skipped loading some Jax models, missing a dependency. No module named 'jax'
2024-01-13 10:37:27,611	INFO worker.py:1715 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
2024-01-13 10:37:28,878	INFO set_read_parallelism.py:115 -- Using autodetected parallelism=8 for stage ReadCSV to satisfy parallelism at least twice the available number of CPUs (4).
2024-01-13 10:37:28,878	INFO set_read_parallelism.py:122 -- To satisfy the requested parallelism of 8, each read task output is split into 8 smaller blocks.
2024-01-13 10:37:28,878	INFO streaming_executor.py:112 -- Executing DAG InputDataBuffer[Input] -> TaskPoolMapOperator[ReadCSV] -> TaskPoolMapOperator[MapBatches(partial)->Write]
2024-01-13 10:37:28,879	INFO streaming_executor.py:113 -- Execution config: ExecutionOptions(resource_limits=ExecutionResources(cpu=None, gpu=None, object_store_memory=None), exclude_resources=ExecutionResources(cpu=0, gpu=0, object_store_memory=0), locality_with_output=False, preserve_order=False, actor_locality_enabled=True, verbose_progress=False)
2024-01-13 10:37:28,880	INFO streaming_executor.py:115 -- Tip: For detailed progress reporting, run `ray.data.DataContext.get_current().execution_options.verbose_progress = True`
(MapBatches(partial)->Write pid=1989) No normalization for AvgIpc. Feature removed!
(MapBatches(partial)->Write pid=1989) WARNING:tensorflow:From /Users/arun/Applications/miniconda3/envs/dc/lib/python3.9/site-packages/tensorflow/python/util/deprecation.py:576: calling function (from tensorflow.python.eager.polymorphic_function.polymorphic_function) with experimental_relax_shapes is deprecated and will be removed in a future version.
(MapBatches(partial)->Write pid=1989) Instructions for updating:                
(MapBatches(partial)->Write pid=1989) experimental_relax_shapes is deprecated, use reduce_retracing instead
2024-01-13 10:37:36,650 WARNING plan.py:588 -- Warning: The Ray cluster currently does not have any available CPUs. The Dataset job will hang unless more CPUs are freed up. A common reason is that cluster resources are used by Actors or Tune trials; see the following link for more details: https://docs.ray.io/en/latest/data/data-internals.html#ray-data-and-tune
2024-01-13 10:37:36,656	INFO set_read_parallelism.py:115 -- Using autodetected parallelism=8 for stage ReadCSV to satisfy parallelism at least twice the available number of CPUs (4).
2024-01-13 10:37:36,656	INFO set_read_parallelism.py:122 -- To satisfy the requested parallelism of 8, each read task output is split into 8 smaller blocks.
2024-01-13 10:37:36,656	INFO streaming_executor.py:112 -- Executing DAG InputDataBuffer[Input] -> TaskPoolMapOperator[ReadCSV] -> TaskPoolMapOperator[MapBatches(partial)]
2024-01-13 10:37:36,657	INFO streaming_executor.py:113 -- Execution config: ExecutionOptions(resource_limits=ExecutionResources(cpu=None, gpu=None, object_store_memory=None), exclude_resources=ExecutionResources(cpu=0, gpu=0, object_store_memory=0), locality_with_output=False, preserve_order=False, actor_locality_enabled=True, verbose_progress=False)
2024-01-13 10:37:36,657	INFO streaming_executor.py:115 -- Tip: For detailed progress reporting, run `ray.data.DataContext.get_current().execution_options.verbose_progress = True`
(MapBatches(partial)->Write pid=1989) Skipped loading some Jax models, missing a dependency. No module named 'jax'
(MapBatches(partial)->Write pid=1990) No normalization for AvgIpc. Feature removed! [repeated 3x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
Running: 0.0/4.0 CPU, 0.0/0.0 GPU, 0.06 MiB/386.43 MiB object_store_memory:   0%/Users/arun/Applications/miniconda3/envs/dc/lib/python3.9/site-packages/ray/data/_internal/arrow_block.py:148: FutureWarning: promote has been superseded by mode='default'.
  return transform_pyarrow.concat(tables)
0                                                                               
1                                                                               
2
3
(MapBatches(partial)->Write pid=1990) WARNING:tensorflow:From /Users/arun/Applications/miniconda3/envs/dc/lib/python3.9/site-packages/tensorflow/python/util/deprecation.py:576: calling function (from tensorflow.python.eager.polymorphic_function.polymorphic_function) with experimental_relax_shapes is deprecated and will be removed in a future version. [repeated 3x across cluster]
(MapBatches(partial)->Write pid=1990) Instructions for updating: [repeated 3x across cluster]
(MapBatches(partial)->Write pid=1990) experimental_relax_shapes is deprecated, use reduce_retracing instead [repeated 3x across cluster]
(MapBatches(partial)->Write pid=1990) Skipped loading some Jax models, missing a dependency. No module named 'jax' [repeated 3x across cluster]
Exception ignored in: <function Dataset.__del__ at 0x2ac5019d0>
Traceback (most recent call last):
  File "/Users/arun/Applications/miniconda3/envs/dc/lib/python3.9/site-packages/ray/data/dataset.py", line 5148, in __del__
TypeError: 'NoneType' object is not callable
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by bveeramani** [comment]
Hey @arunppsg, thanks for opening this! Would you mind sharing `smiles.csv` so that we can reproduce this? Or, could you reproduce this with publicly available data?

**Comment by bveeramani** [comment]
Thanks! Was able to narrow it down to this reproduction:

```python
import deepchem as dc  # For some reason I need this to reproduce the error.

import ray

ray.init(num_cpus=4)

ds = ray.data.read_csv("smiles.csv").map_batches(lambda batch: batch)

for i, batch in enumerate(ds.iter_batches()):
    print(i)

ray.shutdown()
```

**Comment by bveeramani** [comment]
Figured out the issue:
https://github.com/ray-project/ray/blob/3f7f1b52c840d6780fd89ef9bc125ff96eb68e52/python/ray/data/dataset.py#L5182-L5184

`ray` becomes `None` between the `ray is not None` and `ray.is_initialized()` evaluations. So, `ray.is_initialized()` raises a `TypeError`. You can confirm this behavior by making the following change:

```python
        if ray is not None:
            time.sleep(1)
            print(ray)
            if ray.is_initialized():
                self._current_executor.shutdown()
```

```
<module None from None>
```

You can't catch the error because the error happens as Python is quitting.

**Comment by arunppsg** [comment]
Just curious, how does python quit when ray is still not None?

**Comment by bveeramani** [comment]
Not honestly sure. I know `__del__` is fragile, and it can lead to some janky interactions.

**Comment by MaoZiming** [comment]
I am having the same error on a linux machine. Is there a workaround to this?

**Comment by bveeramani** [comment]
@MaoZiming no workaround that I'm aware of, but I'll try to add a fix for the next release.
