### ISSUE TITLE
[rlllib] IMPALA - miss decompression for SampleBatch when not using replay buffer

### ISSUE THREAD

**Issue by Seventeen17** [ray-project/ray#4247]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:  source
- **Ray version**: 0.6.3
- **Python version**: 2.7.5
- **Exact command to reproduce**:
```
pong-impala-fast:
    env: PongNoFrameskip-v4
    run: IMPALA
    config:
        sample_batch_size: 50
        train_batch_size: 1000
        num_workers: 128
        num_envs_per_worker: 5
        broadcast_interval: 5
        max_sample_requests_in_flight_per_worker: 1
        num_data_loader_buffers: 4
        num_gpus: 2
        compress_observations: True
        model:
          dim: 42
```

### Describe the problem

IMAPLA with `AsyncSamplesOptimizer` only decompresses observations when using replay buffer. So error raised if we set `compress_observations=True`  to reduce communication overhead, but not use `ReplayBuffer` to decompress them in `sample` function.
### Source code / logs

```
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/ray/tune/trial_runner.py", line 378, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/opt/conda/lib/python2.7/site-packages/ray/tune/ray_trial_executor.py", line 228, in fetch_result
    result = ray.get(trial_future[0])
  File "/opt/conda/lib/python2.7/site-packages/ray/worker.py", line 2132, in get
    raise value
RayTaskError: [36mray_worker[39m (pid=405, host=h04f07309.nt12)
  File "/opt/conda/lib/python2.7/site-packages/ray/rllib/agents/agent.py", line 284, in train
    result = Trainable.train(self)
  File "/opt/conda/lib/python2.7/site-packages/ray/tune/trainable.py", line 151, in train
    result = self._train()
  File "/opt/conda/lib/python2.7/site-packages/ray/rllib/agents/impala/impala.py", line 116, in _train
    self.optimizer.step()
  File "/opt/conda/lib/python2.7/site-packages/ray/rllib/optimizers/async_samples_optimizer.py", line 115, in step
    sample_timesteps, train_timesteps = self._step()
  File "/opt/conda/lib/python2.7/site-packages/ray/rllib/optimizers/async_samples_optimizer.py", line 164, in _step
    self.sample_tasks.completed_prefetch()):
  File "/opt/conda/lib/python2.7/site-packages/ray/rllib/optimizers/async_samples_optimizer.py", line 213, in _augment_with_replay
    sample_batch = ray.get(sample_batch)
RayTaskError: [36mray_worker[39m (pid=453, host=b05d01103.nt12)
  File "/opt/conda/lib/python2.7/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 402, in sample
    batch["new_obs"] = [pack(o) for o in batch["new_obs"]]
  File "/opt/conda/lib/python2.7/site-packages/ray/rllib/evaluation/sample_batch.py", line 223, in __getitem__
    return self.data[key]
KeyError: 'new_obs'


Traceback (most recent call last):
  File "custom_train.py", line 34, in <module>
    "compress_observations": True,
  File "/opt/conda/lib/python2.7/site-packages/ray/tune/tune.py", line 189, in run_experiments
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [IMPALA_PongNoFrameskip-v4_0])
```

It seems that `obs` and `new_obs` only be unpacked/decompressed in `sample` function of `ReplayBuffer`, and compress happens with `compress_observations=True` which is a common configuration for `Agent`. Does that means any other agents without `ReplayBuffer` can't use lz4 compression? 
Did I misunderstand？
Thanks!

@adoda 
@xutianming

**Comment by ericl** [comment]
Yeah, this is currently not supported. One issue is that decompression is relatively expensive, so it must be offloaded onto another actor. It cannot be simply decompressed on the learner thread or it will be a bottleneck (since decompression is ~1GB/s).

**Comment by ericl** [comment]
This will be fixed by https://github.com/ray-project/ray/pull/4324
