### ISSUE TITLE
[<Ray component: Core|RLlib|etc...>] Inite state of attention_net.py is empty

### ISSUE THREAD

**Issue by fulacse** [ray-project/ray#42569]
### What happened + What you expected to happen

len(state) is 0, so:
/home/tian/anaconda3/bin/conda run -n super-mario-go --no-capture-output python /tmp/pycharm_project_250/rende.py 
/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/ray/data/__init__.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources._vendor.packaging.version import parse as parse_version
/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:103: DeprecationWarning: DeprecationWarning: local mode is an experimental feature that is no longer maintained and will be removed in the future.For debugging consider using Ray debugger. 
  return func(*args, **kwargs)
2024-01-22 15:51:55,039	INFO worker.py:1724 -- Started a local Ray instance.
/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py:483: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
`UnifiedLogger` will be removed in Ray 2.7.
  return UnifiedLogger(config, logdir, loggers=None)
/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/ray/tune/logger/unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
The `JsonLogger interface is deprecated in favor of the `ray.tune.json.JsonLoggerCallback` interface and will be removed in Ray 2.7.
  self._loggers.append(cls(self.config, self.logdir, self.trial))
/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/ray/tune/logger/unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
The `CSVLogger interface is deprecated in favor of the `ray.tune.csv.CSVLoggerCallback` interface and will be removed in Ray 2.7.
  self._loggers.append(cls(self.config, self.logdir, self.trial))
/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/ray/tune/logger/unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
The `TBXLogger interface is deprecated in favor of the `ray.tune.tensorboardx.TBXLoggerCallback` interface and will be removed in Ray 2.7.
  self._loggers.append(cls(self.config, self.logdir, self.trial))
/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/gym/envs/registration.py:593: UserWarning: WARN: The environment SuperMarioBrosRandomStages-v0 is out of date. You should consider upgrading to version `v3`.
  logger.warn(
/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/gymnasium/utils/passive_env_checker.py:164: UserWarning: WARN: The obs returned by the `reset()` method was expecting numpy array dtype to be uint8, actual type: float32
  logger.warn(
/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/gymnasium/utils/passive_env_checker.py:188: UserWarning: WARN: The obs returned by the `reset()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")
/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/shimmy/openai_gym_compatibility.py:231: UserWarning: WARN: Gym v21 environment do not accept options as a reset parameter, options={}
  warn(
/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:227: DeprecationWarning: WARN: Core environment is written in old step API which returns one bool instead of two. It is recommended to rewrite the environment with new step API. 
  logger.deprecation(
/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(done, (bool, np.bool8)):
/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/gymnasium/utils/passive_env_checker.py:164: UserWarning: WARN: The obs returned by the `step()` method was expecting numpy array dtype to be uint8, actual type: float32
  logger.warn(
/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/gymnasium/utils/passive_env_checker.py:188: UserWarning: WARN: The obs returned by the `step()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")
2024-01-22 15:52:02,297	WARNING deprecation.py:50 -- DeprecationWarning: `ray.rllib.models.torch.attention_net.AttentionWrapper` has been deprecated. This will raise an error in the future!
2024-01-22 15:52:02,515	WARNING env_runner_v2.py:297 -- Could not import gymnasium.envs.classic_control.rendering! Try `pip install gymnasium[all]`.
2024-01-22 15:52:02,516	WARNING util.py:62 -- Install gputil for GPU system monitoring.
2024-01-22 15:52:02,696	INFO trainable.py:585 -- Restored on 192.168.1.53 from checkpoint: Checkpoint(filesystem=local, path=/home/tian/AIGamme/super-mario-go/trained/PPO_2024-01-21_20-16-12/PPO_super_mario_8b465_00000_0_2024-01-21_20-16-14/checkpoint_000022)
Traceback (most recent call last):
  File "/tmp/pycharm_project_250/rende.py", line 48, in <module>
    action, _, _ = policy.compute_actions(observation)  # agent policy that uses the observation and info
  File "/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/ray/rllib/policy/torch_policy_v2.py", line 606, in compute_actions
    return self._compute_action_helper(
  File "/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/ray/rllib/utils/threading.py", line 24, in wrapper
    return func(self, *a, **k)
  File "/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/ray/rllib/policy/torch_policy_v2.py", line 1293, in _compute_action_helper
    dist_inputs, state_out = self.model(input_dict, state_batches, seq_lens)
  File "/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/ray/rllib/models/modelv2.py", line 263, in __call__
    res = self.forward(restored, state or [], seq_lens)
  File "/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/ray/rllib/models/torch/attention_net.py", line 440, in forward
    self._features, memory_outs = self.gtrxl(input_dict, state, seq_lens)
  File "/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/ray/rllib/models/modelv2.py", line 263, in __call__
    res = self.forward(restored, state or [], seq_lens)
  File "/home/tian/anaconda3/envs/super-mario-go/lib/python3.8/site-packages/ray/rllib/models/torch/attention_net.py", line 223, in forward
    all_out = self.layers[i](all_out, memory=state[i // 2])
IndexError: list index out of range
ERROR conda.cli.main_run:execute(49): `conda run python /tmp/pycharm_project_250/rende.py` failed. (See above for error)

Process finished with exit code 1

### Versions / Dependencies

[requirements.txt](https://github.com/ray-project/ray/files/14011676/requirements.txt)

### Reproduction script

import numpy as np
import ray
from ray.rllib.algorithms.ppo import PPOConfig
from ray.tune.registry import register_env

from env import env_creator

ray.init(local_mode=True)

# custom env and model
register_env("super_mario", env_creator)

config = PPOConfig()
# Update the config object.
config = config.training(use_critic=True, use_gae=True, lambda_=0.98, sgd_minibatch_size=512, num_sgd_iter=8,
                         shuffle_sequences=True, vf_loss_coeff=1, entropy_coeff=0.01, clip_param=0.3,
                         vf_clip_param=float('inf'), grad_clip=None, use_kl_loss=True, kl_coeff=0.2, kl_target=0.01,
                         model={
                             "conv_filters": [[32, [3, 3], 1], [64, [3, 3], 1], [128, [3, 3], 1], [256, [3, 3], 1], ],
                             "conv_activation": "relu", "use_attention": True, "attention_num_transformer_units": 2,
                             "attention_dim": 512, "attention_num_heads": 8, "attention_head_dim": 64,
                             "attention_memory_inference": 50, "attention_memory_training": 50,
                             "attention_position_wise_mlp_dim": 512, "attention_init_gru_gate_bias": 2.0,
                             "attention_use_n_prev_actions": 0, "attention_use_n_prev_rewards": 0, }, )
# Set the config object's env.
config = config.environment(env="super_mario", render_env=True)
# Speed up
config = config.resources(num_gpus=0)
config = config.rollouts(num_rollout_workers=0)

# Re-build a fresh algorithm.
ppo = config.build()

# Restore the old (checkpointed) state.
ppo.restore(
    "/home/tian/AIGamme/super-mario-go/trained/PPO_2024-01-21_20-16-12/PPO_super_mario_8b465_00000_0_2024-01-21_20-16-14/checkpoint_000022")

# Get policy
policy = ppo.get_policy()

# render
env = env_creator(None)
observation, _ = env.reset()

for _ in range(5000):
    # env.render()
    observation = np.expand_dims(observation, axis=0)
    action, _, _ = policy.compute_actions(observation)  # agent policy that uses the observation and info
    observation, reward, terminated, _, info = env.step(action[0])

    if terminated:
        observation, _ = env.reset()

env.close()

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
