### ISSUE TITLE
tune.with_parameters() throws resource exhaustion exception 

### ISSUE THREAD

**Issue by jakemdaly** [ray-project/ray#42590]
### What happened + What you expected to happen

My training data is large and takes some time to load, so I first instantiate it and then pass it to `tune.with_parameters()` so that it can be re-used on each tuning run without having to re-initialize it. However when I do this, I still get a gRPC resource limit error as below. 

```
Exception has occurred: TuneError       (note: full exception trace is shown but execution is paused at: <module>)
The Ray Tune run failed. Please inspect the previous error messages for a cause. After fixing the issue, you can restart the run from scratch or continue this run. To continue this run, you can use `tuner = Tuner.restore("C:/Users/<user>/ray_results/train_2024-01-22_15-37-02", trainable=...)`.
  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\site-packages\ray\tune\experiment\experiment.py", line 149, in __init__
    self._run_identifier = Experiment.register_if_needed(run)
  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\site-packages\ray\tune\experiment\experiment.py", line 345, in register_if_needed
    register_trainable(name, run_object)
  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\site-packages\ray\tune\registry.py", line 112, in register_trainable
    _global_registry.register(TRAINABLE_CLASS, name, trainable)
  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\site-packages\ray\tune\registry.py", line 239, in register
    self.flush_values()
  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\site-packages\ray\tune\registry.py", line 277, in flush_values
    _internal_kv_put(
  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\site-packages\ray\experimental\internal_kv.py", line 94, in _internal_kv_put
    return global_gcs_client.internal_kv_put(key, value, overwrite, namespace) == 0
  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\site-packages\python\ray\_raylet.pyx", line 2611, in ray._raylet._auto_reconnect.wrapper
  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\site-packages\python\ray\_raylet.pyx", line 2588, in ray._raylet._auto_reconnect.wrapper
  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\site-packages\python\ray\_raylet.pyx", line 2725, in ray._raylet.GcsClient.internal_kv_put
  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\site-packages\python\ray\_raylet.pyx", line 580, in ray._raylet.check_status
ray.exceptions.RpcError: Sent message larger than max (904860198 vs. 536870912)

During handling of the above exception, another exception occurred:

  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\site-packages\ray\tune\tuner.py", line 381, in fit
    return self._local_tuner.fit()
  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\site-packages\ray\tune\impl\tuner_internal.py", line 509, in fit
    analysis = self._fit_internal(trainable, param_space)
  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\site-packages\ray\tune\impl\tuner_internal.py", line 628, in _fit_internal
    analysis = run(
  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\site-packages\ray\tune\tune.py", line 772, in run
    experiments[i] = Experiment(
  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\site-packages\ray\tune\experiment\experiment.py", line 152, in __init__
    raise TuneError(
ray.tune.error.TuneError: The Trainable/training function is too large for grpc resource limit. Check that its definition is not implicitly capturing a large array or other object in scope. Tip: use tune.with_parameters() to put large objects in the Ray object store. 
Original exception: Traceback (most recent call last):
  File "C:\Users\<user>\Miniconda3\envs\py10pip\lib\site-packages\ray\tune\experiment\experiment.py", line 149, in __init__
    self._run_identifier = Experiment.register_if_needed(run)
  File "C:\Users\<user>\Miniconda3\envs\py10pip\lib\site-packages\ray\tune\experiment\experiment.py", line 345, in register_if_needed
    register_trainable(name, run_object)
  File "C:\Users\<user>\Miniconda3\envs\py10pip\lib\site-packages\ray\tune\registry.py", line 112, in register_trainable
    _global_registry.register(TRAINABLE_CLASS, name, trainable)
  File "C:\Users\<user>\Miniconda3\envs\py10pip\lib\site-packages\ray\tune\registry.py", line 239, in register
    self.flush_values()
  File "C:\Users\<user>\Miniconda3\envs\py10pip\lib\site-packages\ray\tune\registry.py", line 277, in flush_values
    _internal_kv_put(
  File "C:\Users\<user>\Miniconda3\envs\py10pip\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\<user>\Miniconda3\envs\py10pip\lib\site-packages\ray\experimental\internal_kv.py", line 94, in _internal_kv_put
    return global_gcs_client.internal_kv_put(key, value, overwrite, namespace) == 0
  File "python\ray\_raylet.pyx", line 2611, in ray._raylet._auto_reconnect.wrapper
  File "python\ray\_raylet.pyx", line 2588, in ray._raylet._auto_reconnect.wrapper
  File "python\ray\_raylet.pyx", line 2725, in ray._raylet.GcsClient.internal_kv_put
  File "python\ray\_raylet.pyx", line 580, in ray._raylet.check_status
ray.exceptions.RpcError: Sent message larger than max (904860198 vs. 536870912)


The above exception was the direct cause of the following exception:

  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\site-packages\ray\tune\tuner.py", line 383, in fit
    raise TuneError(
  File "C:\Users\<user>\Documents\GitHub\SCML\scml\instsched\sc\tune.py", line 46, in main
    results = tuner.fit()
  File "C:\Users\<user>\Documents\GitHub\SCML\scml\instsched\sc\tune.py", line 199, in <module> (Current frame)
    main(f)
  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\<user>\Miniconda3\envs\py10pip\Lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
ray.tune.error.TuneError: The Ray Tune run failed. Please inspect the previous error messages for a cause. After fixing the issue, you can restart the run from scratch or continue this run. To continue this run, you can use `tuner = Tuner.restore("C:/Users/<user>/ray_results/train_2024-01-22_15-37-02", trainable=...)`.
```

### Versions / Dependencies

```
Python 3.10.0
ray 2.9.1
```

### Reproduction script

To reproduce, instantiate a large torch dataset or other (mines around 2 GB), and pass to `tune.with_parameters()`

```

    tuner = tune.Tuner(
        tune.with_parameters(
                train_func,
                dataset=dataset
        ),
        tune_config=tune.TuneConfig(
            metric=METRIC,
            mode=METRICMODE,
            scheduler=scheduler,
            num_samples = 1, 
            reuse_actors=False
        ),
        run_config=air.RunConfig(
            local_dir=perf_dir
        ),
        param_space=config,
    )
```
and `train_func` is like so:
```
def train_func(config=dict(), dataset=None):
    ...
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by woshiyyya** [comment]
Hi @jakemdaly , I think this is a limitation of gRPC. When you are passing a large dataset through train_func arguments, ray internally serialize the dataset and ship it to the remote worker nodes. I am afraid it won't be faster than initialize a new dataset on each worker from scratch.

My suggestion is to define a dataset initialization function, and call this function at the beginning of your training function. This will get around the gRPC limit issue and also may accelerate your training.
