### ISSUE TITLE
[<Ray : Core>] ray.exceptions.RpcError: Method not found!

### ISSUE THREAD

**Issue by robinsonmhj** [ray-project/ray#42721]
### What happened + What you expected to happen

when I submit a job to a remote ray cluster, the server where I submit the job is NOT part of the ray cluster. Here is the stack trace 

`RAY_ADDRESS=$RAY_HEAD_SERVICE_HOST":"$RAY_HEAD_SERVICE_PORT ray job submit --working-dir abc/ -- python script.py 
2024-01-25 19:21:35,055 ERROR utils.py:1403 -- Internal KV Get failed
Traceback (most recent call last):
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/_private/utils.py", line 1395, in internal_kv_get_with_retry
    result = gcs_client.internal_kv_get(key, namespace)
  File "python/ray/_raylet.pyx", line 2143, in ray._raylet._auto_reconnect.wrapper
  File "python/ray/_raylet.pyx", line 2120, in ray._raylet._auto_reconnect.wrapper
  File "python/ray/_raylet.pyx", line 2185, in ray._raylet.GcsClient.internal_kv_get
  File "python/ray/_raylet.pyx", line 410, in ray._raylet.check_status
ray.exceptions.RpcError: Method not found!
2024-01-25 19:21:37,058 ERROR utils.py:1403 -- Internal KV Get failed
Traceback (most recent call last):
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/_private/utils.py", line 1395, in internal_kv_get_with_retry
    result = gcs_client.internal_kv_get(key, namespace)
  File "python/ray/_raylet.pyx", line 2143, in ray._raylet._auto_reconnect.wrapper
  File "python/ray/_raylet.pyx", line 2120, in ray._raylet._auto_reconnect.wrapper
  File "python/ray/_raylet.pyx", line 2185, in ray._raylet.GcsClient.internal_kv_get
  File "python/ray/_raylet.pyx", line 410, in ray._raylet.check_status
ray.exceptions.RpcError: Method not found!
2024-01-25 19:21:39,062 ERROR utils.py:1403 -- Internal KV Get failed
Traceback (most recent call last):
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/_private/utils.py", line 1395, in internal_kv_get_with_retry
    result = gcs_client.internal_kv_get(key, namespace)
  File "python/ray/_raylet.pyx", line 2143, in ray._raylet._auto_reconnect.wrapper
  File "python/ray/_raylet.pyx", line 2120, in ray._raylet._auto_reconnect.wrapper
  File "python/ray/_raylet.pyx", line 2185, in ray._raylet.GcsClient.internal_kv_get
  File "python/ray/_raylet.pyx", line 410, in ray._raylet.check_status
ray.exceptions.RpcError: Method not found!
2024-01-25 19:21:41,064 ERROR utils.py:1403 -- Internal KV Get failed
Traceback (most recent call last):
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/_private/utils.py", line 1395, in internal_kv_get_with_retry
    result = gcs_client.internal_kv_get(key, namespace)
  File "python/ray/_raylet.pyx", line 2143, in ray._raylet._auto_reconnect.wrapper
  File "python/ray/_raylet.pyx", line 2120, in ray._raylet._auto_reconnect.wrapper
  File "python/ray/_raylet.pyx", line 2185, in ray._raylet.GcsClient.internal_kv_get
  File "python/ray/_raylet.pyx", line 410, in ray._raylet.check_status
ray.exceptions.RpcError: Method not found!`

When I submit the job I should get hellow world. The code in script.py is 

```
import ray

@ray.remote
def hello_world():
    return "hello world"

ray.init()
print(ray.get(hello_world.remote()))
```

There is no issue when I run it locally(start a local ray cluster)

### Versions / Dependencies

ray 2.7.3/2.8.0/2.9.1

### Reproduction script

1. create a ray cluster
2. submit a job using the command below(make sure that the server where you submit the job is NOT part of the cluster)
`RAY_ADDRESS=$RAY_HEAD_SERVICE_HOST":"$RAY_HEAD_SERVICE_PORT ray job submit --working-dir abc/ -- python script.py 

### Issue Severity

High: It blocks me from completing my task.

**Comment by architkulkarni** [comment]
Can you try putting `http://` at the front of `$RAY_HEAD_SERVICE_HOST` if it's not already there?

**Comment by robinsonmhj** [comment]
different error after I put http

`
RAY_ADDRESS=http://$RAY_HEAD_SERVICE_HOST":"$RAY_HEAD_SERVICE_PORT ray job submit --working-dir deepspeed_distributed_inference/ -- python script.py

Traceback (most recent call last):
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/conda/envs/ray/lib/python3.10/http/client.py", line 1368, in getresponse
    response.begin()
  File "/opt/conda/envs/ray/lib/python3.10/http/client.py", line 317, in begin
    version, status, reason = self._read_status()
  File "/opt/conda/envs/ray/lib/python3.10/http/client.py", line 299, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ÿÿÿ@@@?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/conda/envs/ray/lib/python3.10/http/client.py", line 1368, in getresponse
    response.begin()
  File "/opt/conda/envs/ray/lib/python3.10/http/client.py", line 317, in begin
    version, status, reason = self._read_status()
  File "/opt/conda/envs/ray/lib/python3.10/http/client.py", line 299, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('\x00\x00\x1e\x04\x00\x00\x00\x00\x00\x00\x03\x7fÿÿÿ\x00\x04\x00@\x00\x00\x00\x05\x00@\x00\x00\x00\x06\x00\x00@\x00þ\x03\x00\x00\x00\x01\x00\x00\x04\x08\x00\x00\x00\x00\x00\x00?\x00\x01'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 262, in _check_connection_and_version_with_url
    r = self._do_request("GET", url)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 303, in _do_request
    return requests.request(
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('\x00\x00\x1e\x04\x00\x00\x00\x00\x00\x00\x03\x7fÿÿÿ\x00\x04\x00@\x00\x00\x00\x05\x00@\x00\x00\x00\x06\x00\x00@\x00þ\x03\x00\x00\x00\x01\x00\x00\x04\x08\x00\x00\x00\x00\x00\x00?\x00\x01'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/ray/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/scripts/scripts.py", line 2474, in main
    return cli()
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/dashboard/modules/job/cli_utils.py", line 44, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/autoscaler/_private/cli_logger.py", line 856, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/dashboard/modules/job/cli.py", line 221, in submit
    client = _get_sdk_client(address, create_cluster_if_needed=True, verify=verify)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/dashboard/modules/job/cli.py", line 25, in _get_sdk_client
    client = JobSubmissionClient(address, create_cluster_if_needed, verify=verify)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/dashboard/modules/job/sdk.py", line 110, in __init__
    self._check_connection_and_version(
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 248, in _check_connection_and_version
    self._check_connection_and_version_with_url(min_version, version_error_message)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 278, in _check_connection_and_version_with_url
    raise ConnectionError(
ConnectionError: Failed to connect to Ray at address: http://ray-65b2f4c4cc4ca35014390915-ray-client.compute.svc.cluster.local:10001
`

**Comment by architkulkarni** [comment]
Oh, can you try port `8265`? Port `10001` is used for Ray Client, while `8265` is used for the Ray Jobs API

**Comment by robinsonmhj** [comment]
same error, see it below
```
RAY_ADDRESS="http://10.68.112.234:8265" ray job submit --working-dir deepspeed_distributed_inference/ -- python script.py
Traceback (most recent call last):
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/conda/envs/ray/lib/python3.10/http/client.py", line 1368, in getresponse
    response.begin()
  File "/opt/conda/envs/ray/lib/python3.10/http/client.py", line 317, in begin
    version, status, reason = self._read_status()
  File "/opt/conda/envs/ray/lib/python3.10/http/client.py", line 286, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/conda/envs/ray/lib/python3.10/http/client.py", line 1368, in getresponse
    response.begin()
  File "/opt/conda/envs/ray/lib/python3.10/http/client.py", line 317, in begin
    version, status, reason = self._read_status()
  File "/opt/conda/envs/ray/lib/python3.10/http/client.py", line 286, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 262, in _check_connection_and_version_with_url
    r = self._do_request("GET", url)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 303, in _do_request
    return requests.request(
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/ray/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/scripts/scripts.py", line 2474, in main
    return cli()
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/dashboard/modules/job/cli_utils.py", line 44, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/autoscaler/_private/cli_logger.py", line 856, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/dashboard/modules/job/cli.py", line 221, in submit
    client = _get_sdk_client(address, create_cluster_if_needed=True, verify=verify)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/dashboard/modules/job/cli.py", line 25, in _get_sdk_client
    client = JobSubmissionClient(address, create_cluster_if_needed, verify=verify)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/dashboard/modules/job/sdk.py", line 110, in __init__
    self._check_connection_and_version(
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 248, in _check_connection_and_version
    self._check_connection_and_version_with_url(min_version, version_error_message)
  File "/opt/conda/envs/ray/lib/python3.10/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 278, in _check_connection_and_version_with_url
    raise ConnectionError(
ConnectionError: Failed to connect to Ray at address: http://10.68.112.234:8265.
```

**Comment by robinsonmhj** [comment]
In our environment, we are using dns, using host name works fine.
