### ISSUE TITLE
[RLlib] - Using new `SingleAgentEnvRunner` with `"MeanStdFilter"` results in error.

### ISSUE THREAD

**Issue by simonsays1980** [ray-project/ray#42772]
### What happened + What you expected to happen

# What happened

Using the new `SingleAgentEnvRunner` with the `MeanStdFilter` resulted in an error: 

```
Traceback (most recent call last):
  File "/home/simon/git-projects/experiments/.venv-3-11-0/lib/python3.11/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
             ^^^^^^^^^^^^^^^
  File "/home/simon/git-projects/experiments/.venv-3-11-0/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/simon/git-projects/experiments/.venv-3-11-0/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/git-projects/experiments/.venv-3-11-0/lib/python3.11/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::PPO.train() (pid=513252, ip=192.168.1.111, actor_id=09f1ac7874004ae681f1c2a501000000, repr=PPO)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/git-projects/experiments/.venv-3-11-0/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 342, in train
    raise skipped from exception_cause(skipped)
  File "/home/simon/git-projects/experiments/.venv-3-11-0/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 339, in train
    result = self.step()
             ^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/git-projects/experiments/.venv-3-11-0/lib/python3.11/site-packages/ray/rllib/algorithms/algorithm.py", line 868, in step
    self._sync_filters_if_needed(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/git-projects/experiments/.venv-3-11-0/lib/python3.11/site-packages/ray/rllib/algorithms/algorithm.py", line 2579, in _sync_filters_if_needed
    central_worker.filters,
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SingleAgentEnvRunner' object has no attribute 'filters'
```
# What you expected to happen
Either the new runner uses the corresponding connector for mean-std-filtering or that the `MeanStdFilter` was used. 

### Versions / Dependencies

Ray 2.9.1
Python 3.11.0
Fedora 37

### Reproduction script

Use any RLlib example with ``SingleAgentEnvRunner` and `MeanStdFilter`.

### Issue Severity

High: It blocks me from completing my task.

**Comment by simonsays1980** [comment]
This is solved with the new connector `MeanStdFilter`.
