### ISSUE TITLE
Running rayproject/examples on kubernetes

### ISSUE THREAD

**Issue by konstantinmiller** [ray-project/ray#4293]
I'm trying to run the latest version of the `rayproject/examples` container on k8s, using `worker.yaml` and `head.yaml` from the repository. I'm following the documentation here: https://ray.readthedocs.io/en/latest/deploy-on-kubernetes.html.

While I can start the container locally, deployment to k8s fails, and produces the logs below.

Could you please help me understand if that's a problem with ray or a problem with my cluster?

```
Using IP address 172.23.2.28 for this node.
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-03-07_09-49-04_1/logs.
Waiting for redis server at 127.0.0.1:6379 to respond...
Waiting for redis server at 127.0.0.1:6380 to respond...
Starting Redis shard with 10.0 GB max memory.
Waiting for redis server at 127.0.0.1:6381 to respond...
Starting Redis shard with 10.0 GB max memory.
WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
Starting the Plasma object store with 0.429496729 GB memory using /tmp.
I0307 09:49:05.047255    26 store.cc:994] Allowing the Plasma store to use up to 0.429497GB of memory.
I0307 09:49:05.047801    26 store.cc:1024] Starting object store with directory /tmp and huge page support disabled

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui.ipynb?token=2dc56245c4d046a468e4e5458b9d2dbb5ae9dda078353ffe
======================================================================

{'redis_address': '172.23.2.28:6379', 'object_store_address': '/tmp/ray/session_2019-03-07_09-49-04_1/sockets/plasma_store', 'webui_url': 'http://localhost:8888/notebooks/ray_ui.ipynb?token=2dc56245c4d046a468e4e5458b9d2dbb5ae9dda078353ffe', 'node_ip_address': '172.23.2.28', 'raylet_socket_name': '/tmp/ray/session_2019-03-07_09-49-04_1/sockets/raylet'}

Started Ray on this node. You can add additional nodes to the cluster by calling

    ray start --redis-address 172.23.2.28:6379

from the node you wish to add. You can connect a driver to the cluster from Python by running

    import ray
    ray.init(redis_address="172.23.2.28:6379")

If you have trouble connecting from a different machine, check that your firewall is configured properly. If you wish to terminate the processes that have been started, run

    ray stop
Traceback (most recent call last):
  File "/ray/python/ray/workers/default_worker.py", line 9, in <module>
    import ray
  File "/ray/python/ray/__init__.py", line 54, in <module>
    from ray.worker import (error_info, init, connect, disconnect, get, put, wait,
  File "/ray/python/ray/worker.py", line 26, in <module>
    import ray.experimental.state as state
EOFError: EOF read where object expected
*** Aborted at 1551952158 (unix time) try "date -d @1551952158" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 24 (TID 0x7f4e39276740) from PID 0; stack trace: ***
    @     0x7f4e38e4f390 (unknown)
    @           0x4a12e1 sdscatlen
    @           0x49efe0 __redisAppendCommand
    @           0x49c8da __redisAsyncCommand
    @           0x49d1d8 redisvAsyncCommand
    @           0x49d29a redisAsyncCommand
    @           0x4865e0 ray::gcs::RedisContext::RunAsync()
Traceback (most recent call last):
  File "/ray/python/ray/monitor.py", line 388, in <module>
        @           0x47bbb7 ray::gcs::Table<>::Add()
redis_client, ray_constants.MONITOR_DIED_ERROR, message)
  File "/ray/python/ray/utils.py", line 112, in push_error_to_driver_through_redis
    ray.gcs_utils.TablePubsub.ERROR_INFO, driver_id, error_data)
  File "/opt/conda/lib/python2.7/site-packages/redis/client.py", line 760, in execute_command
    @           0x493e01 ray::raylet::Monitor::Tick()
    connection.send_command(*args)
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 172.23.2.28:6379. Connection refused.
    @           0x495575 _ZN5boost4asio6detail12wait_handlerIZN3ray6raylet7Monitor4TickEvEUlRKNS_6system10error_codeEE_E11do_completeEPvPNS1_19scheduler_operationES9_m
    @           0x44fc38 boost::asio::detail::scheduler::run()
    @           0x44ac97 main
    @     0x7f4e384fc830 __libc_start_main
    @           0x44c2c9 _start
    @                0x0 (unknown)
Traceback (most recent call last):
  File "/ray/python/ray/workers/default_worker.py", line 87, in <module>
    ray.worker.connect(ray_params, info, mode=ray.WORKER_MODE)
  File "/ray/python/ray/worker.py", line 1841, in connect
    driver_id=None)
  File "/ray/python/ray/utils.py", line 112, in push_error_to_driver_through_redis
    ray.gcs_utils.TablePubsub.ERROR_INFO, driver_id, error_data)
  File "/ray/python/ray/utils.py", line 441, in _wrapper
    return orig_attr(*args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/redis/client.py", line 760, in execute_command
    Traceback (most recent call last):
  File "/ray/python/ray/workers/default_worker.py", line 87, in <module>
    ray.worker.connect(ray_params, info, mode=ray.WORKER_MODE)
  File "/ray/python/ray/worker.py", line 1841, in connect
connection.send_command(*args)
    driver_id=None)
  File "/ray/python/ray/utils.py", line 112, in push_error_to_driver_through_redis
    ray.gcs_utils.TablePubsub.ERROR_INFO, driver_id, error_data)
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 619, in send_command
  File "/ray/python/ray/utils.py", line 441, in _wrapper
    return orig_attr(*args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/redis/client.py", line 760, in execute_command
    self.send_packed_command(self.pack_command(*args))
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 498, in connect
        raise ConnectionError(self._error_message(e))
connection.send_command(*args)
redis.exceptions  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 619, in send_command
.ConnectionError: Error 111 connecting to 172.23.2.28:6379. Connection refused.
    self.send_packed_command(self.pack_command(*args))
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 172.23.2.28:6379. Connection refused.
Traceback (most recent call last):
  File "/ray/python/ray/workers/default_worker.py", line 87, in <module>
    ray.worker.connect(ray_params, info, mode=ray.WORKER_MODE)
  File "/ray/python/ray/worker.py", line 1841, in connect
    driver_id=None)
  File "/ray/python/ray/utils.py", line 112, in push_error_to_driver_through_redis
    ray.gcs_utils.TablePubsub.ERROR_INFO, driver_id, error_data)
  File "/ray/python/ray/utils.py", line 441, in _wrapper
    return orig_attr(*args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/redis/client.py", line 760, in execute_command
    connection.send_command(*args)
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 172.23.2.28:6379. Connection refused.
Traceback (most recent call last):
  File "/ray/python/ray/workers/default_worker.py", line 87, in <module>
    ray.worker.connect(ray_params, info, mode=ray.WORKER_MODE)
  File "/ray/python/ray/worker.py", line 1841, in connect
    driver_id=None)
  File "/ray/python/ray/utils.py", line 112, in push_error_to_driver_through_redis
    ray.gcs_utils.TablePubsub.ERROR_INFO, driver_id, error_data)
  File "/ray/python/ray/utils.py", line 441, in _wrapper
    return orig_attr(*args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/redis/client.py", line 760, in execute_command
    connection.send_command(*args)
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 172.23.2.28:6379. Connection refused.
Traceback (most recent call last):
  File "/ray/python/ray/workers/default_worker.py", line 87, in <module>
    ray.worker.connect(ray_params, info, mode=ray.WORKER_MODE)
  File "/ray/python/ray/worker.py", line 1841, in connect
    driver_id=None)
  File "/ray/python/ray/utils.py", line 112, in push_error_to_driver_through_redis
    ray.gcs_utils.TablePubsub.ERROR_INFO, driver_id, error_data)
  File "/ray/python/ray/utils.py", line 441, in _wrapper
    return orig_attr(*args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/redis/client.py", line 760, in execute_command
    connection.send_command(*args)
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 172.23.2.28:6379. Connection refused.
Traceback (most recent call last):
  File "/ray/python/ray/workers/default_worker.py", line 87, in <module>
    ray.worker.connect(ray_params, info, mode=ray.WORKER_MODE)
  File "/ray/python/ray/worker.py", line 1841, in connect
    driver_id=None)
  File "/ray/python/ray/utils.py", line 112, in push_error_to_driver_through_redis
    ray.gcs_utils.TablePubsub.ERROR_INFO, driver_id, error_data)
  File "/ray/python/ray/utils.py", line 441, in _wrapper
    return orig_attr(*args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/redis/client.py", line 760, in execute_command
    connection.send_command(*args)
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 172.23.2.28:6379. Connection refused.
Traceback (most recent call last):
  File "/ray/python/ray/workers/default_worker.py", line 87, in <module>
    ray.worker.connect(ray_params, info, mode=ray.WORKER_MODE)
  File "/ray/python/ray/worker.py", line 1841, in connect
    driver_id=None)
  File "/ray/python/ray/utils.py", line 112, in push_error_to_driver_through_redis
    ray.gcs_utils.TablePubsub.ERROR_INFO, driver_id, error_data)
  File "/ray/python/ray/utils.py", line 441, in _wrapper
    return orig_attr(*args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/redis/client.py", line 760, in execute_command
    connection.send_command(*args)
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 172.23.2.28:6379. Connection refused.
Traceback (most recent call last):
  File "/ray/python/ray/workers/default_worker.py", line 87, in <module>
    ray.worker.connect(ray_params, info, mode=ray.WORKER_MODE)
  File "/ray/python/ray/worker.py", line 1841, in connect
    driver_id=None)
  File "/ray/python/ray/utils.py", line 112, in push_error_to_driver_through_redis
    ray.gcs_utils.TablePubsub.ERROR_INFO, driver_id, error_data)
  File "/ray/python/ray/utils.py", line 441, in _wrapper
    return orig_attr(*args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/redis/client.py", line 760, in execute_command
    connection.send_command(*args)
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 172.23.2.28:6379. Connection refused.
```

**Comment by konstantinmiller** [comment]
It looks like the problem only occurs, when I specify two redis shards, as in the example `head.yaml`:
```
ray start --head --redis-port=6379 --redis-shard-ports=6380,6381 --object-manager-port=12345 --node-manager-port=12346 --node-ip-address=$MY_POD_IP --block
```

When specifying only one shard port, the problem doesn't occur:
```
ray start --head --redis-port=6379 --redis-shard-ports=6380 --object-manager-port=12345 --node-manager-port=12346 --node-ip-address=$MY_POD_IP --block
```

**Comment by konstantinmiller** [comment]
Not sure if it's related but when I try to start the worker, I'm getting `Connection to IPC socket failed` like that:
```
Waiting for redis server at 172.23.26.155:6379 to respond...
Using IP address 172.23.9.39 for this node.
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-03-07_19-42-59_1/logs.
WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
Starting the Plasma object store with 0.107374182 GB memory using /tmp.
I0307 19:42:59.117547    12 store.cc:994] Allowing the Plasma store to use up to 0.107374GB of memory.
I0307 19:42:59.117993    12 store.cc:1024] Starting object store with directory /tmp and huge page support disabled
{'webui_url': '', 'node_ip_address': '172.23.9.39', 'redis_address': u'172.23.26.155:6379', 'redis_shards': ['172.23.26.155:6380'], 'object_store_address': '/tmp/ray/session_2019-03-07_19-42-59_1/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2019-03-07_19-42-59_1/sockets/raylet'}

Started Ray on this node. If you wish to terminate the processes that have been started, run

    ray stop
WARNING: Logging before InitGoogleLogging() is written to STDERR
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0307 19:43:06.553805    37 io.cc:167] Connection to IPC socket failed for pathname /tmp/ray/session_2019-03-07_19-42-59_1/sockets/plasma_store, retrying 50 more times
E0307 19:43:06.553805    36 io.cc:167] Connection to IPC socket failed for pathname /tmp/ray/session_2019-03-07_19-42-59_1/sockets/plasma_store, retrying 50 more times
E0307 19:43:06.654002    37 io.cc:167] Connection to IPC socket failed for pathname /tmp/ray/session_2019-03-07_19-42-59_1/sockets/plasma_store, retrying 49 more times
E0307 19:43:06.654002    36 io.cc:167] Connection to IPC socket failed for pathname /tmp/ray/session_2019-03-07_19-42-59_1/sockets/plasma_store, retrying 49 more times
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0307 19:43:06.662905    35 io.cc:167] Connection to IPC socket failed for pathname /tmp/ray/session_2019-03-07_19-42-59_1/sockets/plasma_store, retrying 50 more times
E0307 19:43:06.754149    37 io.cc:167] Connection to IPC socket failed for pathname /tmp/ray/session_2019-03-07_19-42-59_1/sockets/plasma_store, retrying 48 more times
E0307 19:43:06.754149    36 io.cc:167] Connection to IPC socket failed for pathname /tmp/ray/session_2019-03-07_19-42-59_1/sockets/plasma_store, retrying 48 more times
E0307 19:43:06.763059    35 io.cc:167] Connection to IPC socket failed for pathname /tmp/ray/session_2019-03-07_19-42-59_1/sockets/plasma_store, retrying 49 more times
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0307 19:43:06.765553    38 io.cc:167] Connection to IPC socket failed for pathname /tmp/ray/session_2019-03-07_19-42-59_1/sockets/plasma_store, retrying 50 more times
E0307 19:43:06.854337    36 io.cc:167] Connection to IPC socket failed for pathname /tmp/ray/session_2019-03-07_19-42-59_1/sockets/plasma_store, retrying 47 more times
E0307 19:43:06.854348    37 io.cc:167] Connection to IPC socket failed for pathname /tmp/ray/session_2019-03-07_19-42-59_1/sockets/plasma_store, retrying 47 more times
```

**Comment by konstantinmiller** [comment]
It seems that the issue was our k8s configuration. It requires each pod to specify memory requests and memory limits, which isn't happening in the example.
