### ISSUE TITLE
[<Ray component: core>] build from source code guide is out of date

### ISSUE THREAD

**Issue by gaowayne** [ray-project/ray#43093]
### What happened + What you expected to happen

check below build error
```
dcg@oq1:/mnt/nvme1n1/pfray/ray$ bazel build -c fastbuild //:*
DEBUG: /mnt/nvme1n1/pfray/ray/bazel/ray_deps_setup.bzl:67:14: No implicit mirrors used because urls were explicitly provided
DEBUG: /mnt/nvme1n1/pfray/ray/bazel/ray_deps_setup.bzl:67:14: No implicit mirrors used because urls were explicitly provided
ERROR: Traceback (most recent call last):
        File "/mnt/nvme1n1/pfray/ray/WORKSPACE", line 25, column 15, in <toplevel>
                versions.check(minimum_bazel_version = "5.4.1")
        File "/home/dcg/.cache/bazel/_bazel_dcg/86c0b2da2f7232f44660b8e2d43c00fd/external/bazel_skylib/lib/versions.bzl", line 105, column 13, in _check_bazel_version
                fail("Current Bazel version is {}; expected at least {}".format(
Error in fail: Current Bazel version is 3.5.1- (@non-git); expected at least 5.4.1
ERROR: error loading package '': Encountered error while reading extension file 'defs.bzl': no such package '@python3_9//': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.091s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
dcg@oq1:/mnt/nvme1n1/pfray/ray$ bazel build -c fastbuild //:all
DEBUG: /mnt/nvme1n1/pfray/ray/bazel/ray_deps_setup.bzl:67:14: No implicit mirrors used because urls were explicitly provided
DEBUG: /mnt/nvme1n1/pfray/ray/bazel/ray_deps_setup.bzl:67:14: No implicit mirrors used because urls were explicitly provided
ERROR: Traceback (most recent call last):
        File "/mnt/nvme1n1/pfray/ray/WORKSPACE", line 25, column 15, in <toplevel>
                versions.check(minimum_bazel_version = "5.4.1")
        File "/home/dcg/.cache/bazel/_bazel_dcg/86c0b2da2f7232f44660b8e2d43c00fd/external/bazel_skylib/lib/versions.bzl", line 105, column 13, in _check_bazel_version
                fail("Current Bazel version is {}; expected at least {}".format(
Error in fail: Current Bazel version is 3.5.1- (@non-git); expected at least 5.4.1
ERROR: error loading package '': Encountered error while reading extension file 'defs.bzl': no such package '@python3_9//': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.077s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

### Versions / Dependencies

here is commit ID I reproduce the issue on ubuntu22.04
```
commit 8ac130c91cfc68e446e6a272cc11688b8e7034e4 (HEAD -> master, origin/master, origin/HEAD)
Author: Edward Oakes <ed.nmi.oakes@gmail.com>
Date:   Sat Feb 10 06:40:49 2024 -0800

    [serve] Record ongoing requests metric directly instead of periodically (#43061)
    
    ---------
    
    Signed-off-by: Edward Oakes <ed.nmi.oakes@gmail.com>
```

### Reproduction script

bazel build -c fastbuild //:all

### Issue Severity

None

**Comment by gaowayne** [comment]
I tried build C++ code only, but looks like go_sdk download is hanging
```
dcg@oq1:/mnt/nvme1n1/pfray/ray/cpp$ bazel build //cpp:libray_api.so
Starting local Bazel server and connecting to it...
DEBUG: /mnt/nvme1n1/pfray/ray/bazel/ray_deps_setup.bzl:67:14: No implicit mirrors used because urls were explicitly provided
DEBUG: /mnt/nvme1n1/pfray/ray/bazel/ray_deps_setup.bzl:67:14: No implicit mirrors used because urls were explicitly provided
Analyzing: target //cpp:libray_api.so (42 packages loaded, 9 targets configured)
    Fetching @go_sdk; Downloading and extracting Go toolchain 12s
^C
Analyzing: target //cpp:libray_api.so (42 packages loaded, 9 targets configured)
    Fetching @go_sdk; Downloading and extracting Go toolchain 16s
^C
INFO: Repository go_sdk instantiated at:
  /mnt/nvme1n1/pfray/ray/WORKSPACE:17:16: in <toplevel>
  /home/dcg/.cache/bazel/_bazel_dcg/86c0b2da2f7232f44660b8e2d43c00fd/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:56:27: in grpc_extra_deps
  /home/dcg/.cache/bazel/_bazel_dcg/86c0b2da2f7232f44660b8e2d43c00fd/external/io_bazel_rules_go/go/private/sdk.bzl:453:28: in go_register_toolchains
  /home/dcg/.cache/bazel/_bazel_dcg/86c0b2da2f7232f44660b8e2d43c00fd/external/io_bazel_rules_go/go/private/sdk.bzl:129:21: in go_download_sdk
Repository rule _go_download_sdk defined at:
  /home/dcg/.cache/bazel/_bazel_dcg/86c0b2da2f7232f44660b8e2d43c00fd/external/io_bazel_rules_go/go/private/sdk.bzl:116:35: in <toplevel>
ERROR: An error occurred during the fetch of repository 'go_sdk':
   Traceback (most recent call last):
        File "/home/dcg/.cache/bazel/_bazel_dcg/86c0b2da2f7232f44660b8e2d43c00fd/external/io_bazel_rules_go/go/private/sdk.bzl", line 100, column 16, in _go_download_sdk_impl
                _remote_sdk(ctx, [url.format(filename) for url in ctx.attr.urls], ctx.attr.strip_prefix, sha256)
        File "/home/dcg/.cache/bazel/_bazel_dcg/86c0b2da2f7232f44660b8e2d43c00fd/external/io_bazel_rules_go/go/private/sdk.bzl", line 189, column 21, in _remote_sdk
                ctx.download(
Error in download: java.io.IOException: thread interrupted
ERROR: /mnt/nvme1n1/pfray/ray/WORKSPACE:17:16: fetching _go_download_sdk rule //external:go_sdk: Traceback (most recent call last):
        File "/home/dcg/.cache/bazel/_bazel_dcg/86c0b2da2f7232f44660b8e2d43c00fd/external/io_bazel_rules_go/go/private/sdk.bzl", line 100, column 16, in _go_download_sdk_impl
                _remote_sdk(ctx, [url.format(filename) for url in ctx.attr.urls], ctx.attr.strip_prefix, sha256)
        File "/home/dcg/.cache/bazel/_bazel_dcg/86c0b2da2f7232f44660b8e2d43c00fd/external/io_bazel_rules_go/go/private/sdk.bzl", line 189, column 21, in _remote_sdk
                ctx.download(
Error in download: java.io.IOException: thread interrupted
ERROR: build interrupted
INFO: Elapsed time: 20.982s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (42 packages loaded, 9 targets configured)
dcg@oq1:/mnt/nvme1n1/pfray/ray/cpp$ 
```

**Comment by ruisearch42** [comment]
@gaowayne The error message complains the bazel version is too low:

```
Error in fail: Current Bazel version is 3.5.1- (@non-git); expected at least 5.4.1
```

Can you double check the bazel is installed from the official script ci/env/install-bazel.sh , or does it already exist on your system?

**Comment by gaowayne** [comment]
> @gaowayne The error message complains the bazel version is too low:
> 
> ```
> Error in fail: Current Bazel version is 3.5.1- (@non-git); expected at least 5.4.1
> ```
> 
> Can you double check the bazel is installed from the official script ci/env/install-bazel.sh , or does it already exist on your system?

the enviroment is reinstalled. I will check again. 
now I use FedoraOS to build I met below error to install python depends
```
(myenv) [root@cassiopeia ray]# pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl
ERROR: ray-3.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl is not a supported wheel on this platform.
```
(myenv) [root@cassiopeia ray]# cat /etc/release-os
cat: /etc/release-os: No such file or directory
(myenv) [root@cassiopeia ray]# cat /etc/os-release
NAME="Fedora Linux"
VERSION="37 (Server Edition)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Linux 37 (Server Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f37/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
SUPPORT_END=2023-12-05
VARIANT="Server Edition"
VARIANT_ID=server

**Comment by gaowayne** [comment]
@ruisearch42 buddy, I managed install bazel6.4, now previous error gone, I saw new error below
```
(base) [root@cassiopeia ray]# bazel build -c fastbuild //:*
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
DEBUG: /mnt/nvme1n1/pfray/ray/bazel/ray_deps_setup.bzl:67:14: No implicit mirrors used because urls were explicitly provided
DEBUG: /mnt/nvme1n1/pfray/ray/bazel/ray_deps_setup.bzl:67:14: No implicit mirrors used because urls were explicitly provided
ERROR: /root/.cache/bazel/_bazel_root/86c0b2da2f7232f44660b8e2d43c00fd/external/bazel_tools/platforms/BUILD:89:6: in alias rule @bazel_tools//platforms:windows: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
ERROR: /root/.cache/bazel/_bazel_root/86c0b2da2f7232f44660b8e2d43c00fd/external/bazel_tools/platforms/BUILD:89:6: Analysis of target '@bazel_tools//platforms:windows' failed
ERROR: /root/.cache/bazel/_bazel_root/86c0b2da2f7232f44660b8e2d43c00fd/external/com_github_google_flatbuffers/BUILD:74:10: While resolving toolchains for target @com_github_google_flatbuffers//:flatc: invalid registered toolchain '@bazel_skylib//toolchains/unittest:cmd_toolchain': 
ERROR: Analysis of target '//:ray/raylet/format/node_manager_generated.h' failed; build aborted: 
INFO: Elapsed time: 35.111s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (61 packages loaded, 1438 targets configured)
```

**Comment by ruisearch42** [comment]
> @ruisearch42 also if I change a little code in C++, then I want to replace the module installed in my node, and do one round performance testing, can I just replace binary file? is there any guide for this?

I think yoiu can just ran `bazel build`: https://docs.ray.io/en/latest/ray-contribute/development.html#fast-debug-and-optimized-builds

**Comment by dstrodtman** [comment]
Closing as resolved. The contributor guide now references Bazel 7.5.0 via bazelisk (`ci/env/install-bazel.sh`). If a current build-from-source step is unclear, please open a fresh issue against the contributor docs.

Context: docs-team triage of the OSS docs issue backlog.
