### ISSUE TITLE
RayTaskError in my Trainable class.

### ISSUE THREAD

**Issue by HAPAVAN22** [ray-project/ray#43137]
### What happened + What you expected to happen

I am facing the following error : RayTaskError(AttributeError): ray::TrainALL.train(). TrainALL is a Trainable class and contains the logic to train the model.

logs: 
2024-02-14 00:18:05,398	ERROR tune_controller.py:1374 -- Trial task failed for trial TrainALL_4c552_00000
Traceback (most recent call last):
  File "C:\Users\hapav\anaconda3\lib\site-packages\ray\air\execution\_internal\event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "C:\Users\hapav\anaconda3\lib\site-packages\ray\_private\auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\hapav\anaconda3\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\hapav\anaconda3\lib\site-packages\ray\_private\worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::TrainALL.train() (pid=35968, ip=127.0.0.1, actor_id=a40ed1244b3633a795d5b82f01000000, repr=<__main__.TrainALL object at 0x000001E6F5BBE4F0>)
  File "python\ray\_raylet.pyx", line 1813, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1754, in ray._raylet.execute_task.function_executor
  File "C:\Users\hapav\anaconda3\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\hapav\anaconda3\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hapav\anaconda3\lib\site-packages\ray\tune\trainable\trainable.py", line 342, in train
    raise skipped from exception_cause(skipped)
  File "C:\Users\hapav\anaconda3\lib\site-packages\ray\tune\trainable\trainable.py", line 339, in train
    result = self.step()
  File "C:\Users\hapav\anaconda3\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)

### Versions / Dependencies

-

### Reproduction script

-

### Issue Severity

High: It blocks me from completing my task.

**Comment by woshiyyya** [comment]
Hi @HAPAVAN22 Can you share the full stack trace with us? Also it'd be better to have a reproducible script.
