### ISSUE TITLE
Ray Core quickstart example fails with GPUs ("RuntimeError: Found no NVIDIA driver on your system.")

### ISSUE THREAD

**Issue by jaanphare** [ray-project/ray#43145]
### What happened + What you expected to happen

Thank you for making Ray! We are successfully able to run Ray Tune jobs on CPUs and set up autoscaling, but are blocked on running on GPU due to the quickstart example not working. Might be missing something basic. 

We are running the quickstart example from https://docs.ray.io/en/latest/cluster/running-applications/job-submission/quickstart.html

`print(ray.cluster_resources())` correctly shows the available worker nodes and GPU accelerators on the AWS g5.xlarge instance: 

```
{'memory': 20050532762.0, 'GPU': 2.0, 'object_store_memory': 8142993407.0, 'accelerator_type:A10G': 2.0, 'CPU': 8.0, 'node:10.0.1.225': 1.0, 'node:10.0.1.37': 1.0, 'node:__internal_head__': 1.0}
```

However, running the below example results in an error, `RuntimeError: Found no NVIDIA driver on your system.`.

To debug we have tried:
* `os.environ["CUDA_VISIBLE_DEVICES"]` results in an error that the environment variable is not set
* `torch.cuda.is_available()` returns False
* we are unable to launch jobs that require GPUs based on the quickstart example
* we ran `ray attach` to ssh into the head node, and `ssh -i ray_bootstrap_key.pem ubuntu@IP` to ssh into the worker nodes, and successfully checked that CUDA_VISIBLE_DEVICES is set correctly, and we were able to execute PyTorch scripts that require GPUs on worker nodes using the available NVIDIA A10 GPU accelerators.
* we use `- pip install flash-attn==2.5.1.post1 --no-build-isolation` as one of the `worker_setup_commands` in the ray cluster configuration, and this installs successfully (and we can ssh into worker nodes and use flash attention there)
* ray tune (running on CPU) is able to see the logical GPU devices and prints out `Logical resource usage: 0/8 CPUs, 0/2 GPUs (0.0/2.0 accelerator_type:A10G)`

cc @tymorphare @niels-phare @jnewman-phare

### Versions / Dependencies

Docker image: `rayproject/ray-ml:latest-py39-cu118`
g5.xlarge AWS nodes for head and workers. 

Started with:

```
# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --dashboard-host=0.0.0.0 --num-gpus=1

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076 --num-gpus=1
```

### Reproduction script

```
import ray
import torch 
import os

@ray.remote(num_cpus=1, num_gpus=1)
def hello_world():
    print("hello world")
    print(torch.zeros(1, device=torch.device("cuda")))

# Automatically connect to the running Ray cluster.
ray.init()
print(ray.cluster_resources())
print('PyTorch torch.cuda.is_available():', torch.cuda.is_available())
print("GPU ids: {}".format(ray.get_runtime_context().get_accelerator_ids()["GPU"]))
# print("CUDA_VISIBLE_DEVICES: {}".format(os.environ["CUDA_VISIBLE_DEVICES"]))
print(ray.get(hello_world.remote()))
```

Results in:

```
ray job submit --address http://localhost:8265 --working-dir . -- CUDA_VISIBLE_DEVICES=0 python ray_quickstart_example_gpu.py
Job submission server address: http://localhost:8265
2024-02-13 17:05:13,882 INFO dashboard_sdk.py:338 -- Uploading package gcs://_ray_pkg_0fea79c9f8aaa0eb.zip.
2024-02-13 17:05:13,883 INFO packaging.py:530 -- Creating a file package for local directory '.'.

-------------------------------------------------------
Job 'raysubmit_8LDEdxYDsfCcrsTW' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_8LDEdxYDsfCcrsTW
  Query the status of the job:
    ray job status raysubmit_8LDEdxYDsfCcrsTW
  Request the job to be stopped:
    ray job stop raysubmit_8LDEdxYDsfCcrsTW

Tailing logs until the job exits (disable with --no-wait):
2024-02-13 14:05:16,161 INFO worker.py:1405 -- Using address 10.0.1.37:6379 set in the environment variable RAY_ADDRESS
2024-02-13 14:05:16,161 INFO worker.py:1540 -- Connecting to existing Ray cluster at address: 10.0.1.37:6379...
2024-02-13 14:05:16,168 INFO worker.py:1715 -- Connected to Ray cluster. View the dashboard at 10.0.1.37:8265 
{'memory': 20050532762.0, 'node:10.0.1.225': 1.0, 'GPU': 2.0, 'CPU': 8.0, 'object_store_memory': 8142993407.0, 'accelerator_type:A10G': 2.0, 'node:10.0.1.37': 1.0, 'node:__internal_head__': 1.0}
PyTorch torch.cuda.is_available(): False
GPU ids: []
(hello_world pid=6062) hello world
Traceback (most recent call last):
  File "/tmp/ray/session_2024-02-13_12-45-19_602661_1349/runtime_resources/working_dir_files/_ray_pkg_0fea79c9f8aaa0eb/ray_quickstart_example_gpu.py", line 17, in <module>
    print(ray.get(hello_world.remote()))
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::hello_world() (pid=6062, ip=10.0.1.37)
  File "/tmp/ray/session_2024-02-13_12-45-19_602661_1349/runtime_resources/working_dir_files/_ray_pkg_0fea79c9f8aaa0eb/ray_quickstart_example_gpu.py", line 9, in hello_world
    print(torch.zeros(1, device=torch.device("cuda")))
  File "/home/ray/anaconda3/lib/python3.9/site-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

---------------------------------------
Job 'raysubmit_8LDEdxYDsfCcrsTW' failed
---------------------------------------

Status message: Job entrypoint command failed with exit code 1, last available logs (truncated to 20,000 chars):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::hello_world() (pid=6062, ip=10.0.1.37)
  File "/tmp/ray/session_2024-02-13_12-45-19_602661_1349/runtime_resources/working_dir_files/_ray_pkg_0fea79c9f8aaa0eb/ray_quickstart_example_gpu.py", line 9, in hello_world
    print(torch.zeros(1, device=torch.device("cuda")))
  File "/home/ray/anaconda3/lib/python3.9/site-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by jaanphare** [comment]
Fixed this by switching to a different AMI - was using the NVIDIA base deep learning AMI (ami-041855406987a648b). 

Switching to the Amazon OSS AMI from January 2024 solved this issue (ami-07252019da3a8acc8).

Not sure if Ray is able to throw errors for incompatible AMIs? 

Posted here in case others also spend inordinate amounts of time debugging this :)

https://forums.developer.nvidia.com/t/nvidia-base-ami-does-not-work-with-ray-on-aws-gpus/282861
