### ISSUE TITLE
Torch utils - TypeError when converting np.ndarray. in torch.as_tensor

### ISSUE THREAD

**Issue by frazierprime** [ray-project/ray#43362]
### What happened + What you expected to happen

Observing some odd behavior when attempting to run a distributed training function. See below for full stack trace.

Full Stack Trace:
```
RayTaskError(TypeError)                   Traceback (most recent call last)
RayTaskError(TypeError): ray::TrainTrainable.train() (pid=854, ip=10.198.17.180, actor_id=804b08bc95845abc054fcfba0f000000, repr=TorchTrainer)
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 400, in train
    raise skipped from exception_cause(skipped)
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/train/_internal/utils.py", line 54, in check_for_failure
    ray.get(object_ref)
ray.exceptions.RayTaskError(TypeError): ray::_RayTrainWorker__execute.get_next() (pid=906, ip=10.198.17.180, actor_id=ec9481c4f8ba8ebde753c0d50f000000, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x7f3c078ee4a0>)
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/train/_internal/worker_group.py", line 33, in __execute
    raise skipped from exception_cause(skipped)
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/train/_internal/utils.py", line 129, in discard_return_wrapper
    train_func(*args, **kwargs)
  File "/tmp/ipykernel_10225/3473735046.py", line 111, in trainer_init_per_worker
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/transformers/trainer.py", line 1543, in train
    return inner_training_loop(
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/transformers/trainer.py", line 1765, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 34, in fetch
    data.append(next(self.dataset_iter))
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/data/iterator.py", line 229, in _create_iterator
    for batch in iterator:
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 176, in iter_batches
    next_batch = next(async_batch_iter)
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/data/_internal/util.py", line 769, in make_async_gen
    raise next_item
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/data/_internal/util.py", line 746, in execute_computation
    for item in fn(thread_safe_generator):
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 167, in _async_iter_batches
    yield from extract_data_from_batch(batch_iter)
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/data/_internal/block_batching/util.py", line 206, in extract_data_from_batch
    for batch in batch_iter:
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 306, in restore_original_order
    for batch in batch_iter:
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/data/_internal/block_batching/util.py", line 199, in finalize_batches
    for batch in batch_iter:
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/data/_internal/util.py", line 769, in make_async_gen
    raise next_item
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/data/_internal/util.py", line 746, in execute_computation
    for item in fn(thread_safe_generator):
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/data/_internal/block_batching/iter_batches.py", line 218, in threadpool_computations_format_collate
    yield from formatted_batch_iter
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/data/_internal/block_batching/util.py", line 177, in collate
    collated_batch = collate_fn(batch.data)
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/data/iterator.py", line 406, in collate_fn
    return convert_ndarray_batch_to_torch_tensor_batch(
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/air/_internal/torch_utils.py", line 240, in convert_ndarray_batch_to_torch_tensor_batch
    batch = {
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/air/_internal/torch_utils.py", line 241, in <dictcomp>
    col_name: convert_ndarray_to_torch_tensor(
  File "/tmp/ray/session_2024-02-21_13-09-01_124375_18/runtime_resources/conda/f0cdd7a729cbfca5edf56039cac2d2783fb686dd/lib/python3.10/site-packages/ray/air/_internal/torch_utils.py", line 209, in convert_ndarray_to_torch_tensor
    return torch.as_tensor(ndarray, dtype=dtype, device=device)
TypeError: can't convert np.ndarray of type numpy.str_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
```

### Versions / Dependencies

Ray cluster version: 2.7.0
Ray SDK version: 2.7.0

PIP dependencies:
    "pip": [
        "datasets==2.12.0",
        "evaluate==0.4.0",
        "accelerate==0.16.0",
        "transformers==4.26.0",
        "torch==1.13.0",
        "deepspeed==0.9.2",
        "ipython==8.14.0",
        "pandas==2.1.4",
        "numpy==1.25.2",
        "huggingface-hub==0.18.0"
    ]

### Reproduction script

This notebook should reproduce the issue:
https://github.com/ray-project/ray/blob/f64e66bc5dc00669a063717508ab4f5f1282a446/doc/source/train/examples/deepspeed/dolly_v2_deepspeed_instruction_fine_tuning.ipynb

### Issue Severity

None

**Comment by woshiyyya** [comment]
Hi @frazierprime, seems that you have a column with string datatype in the `ray_datasets `, which is not able to convert to torch tensor.
