### ISSUE TITLE
[Rllib] KeyError: 'vf_preds' when training using new API stack

### ISSUE THREAD

**Issue by grizzlybearg** [ray-project/ray#43460]
### What happened + What you expected to happen

When training with PPO or APPO in the new API stack, I always get this error causing the workers to faile:

> (RolloutWorker pid=40453) 2024-02-27 16:08:30,295       ERROR actor_manager.py:182 -- Worker exception, recreating: 'vf_preds'
(RolloutWorker pid=40453) Traceback (most recent call last):
(RolloutWorker pid=40453)   File "/opt/conda/envs/nuvoenv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py", line 178, in apply
(RolloutWorker pid=40453)     return func(self, *args, **kwargs)
(RolloutWorker pid=40453)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RolloutWorker pid=40453)   File "/opt/conda/envs/nuvoenv/lib/python3.11/site-packages/ray/rllib/execution/rollout_ops.py", line 84, in <lambda>
(RolloutWorker pid=40453)     lambda w: w.sample(), local_worker=False, healthy_only=True
(RolloutWorker pid=40453)               ^^^^^^^^^^
(RolloutWorker pid=40453)   File "/opt/conda/envs/nuvoenv/lib/python3.11/site-packages/ray/util/tracing/tracing_helper.py", line 467, in _resume_span
(RolloutWorker pid=40453)     return method(self, *_args, **_kwargs)
(RolloutWorker pid=40453)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RolloutWorker pid=40453)   File "/opt/conda/envs/nuvoenv/lib/python3.11/site-packages/ray/rllib/evaluation/rollout_worker.py", line 694, in sample
(RolloutWorker pid=40453)     batches = [self.input_reader.next()]
(RolloutWorker pid=40453)                ^^^^^^^^^^^^^^^^^^^^^^^^
(RolloutWorker pid=40453)   File "/opt/conda/envs/nuvoenv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py", line 91, in next
(RolloutWorker pid=40453)     batches = [self.get_data()]
(RolloutWorker pid=40453)                ^^^^^^^^^^^^^^^
(RolloutWorker pid=40453)   File "/opt/conda/envs/nuvoenv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py", line 276, in get_data
(RolloutWorker pid=40453)     item = next(self._env_runner)
(RolloutWorker pid=40453)            ^^^^^^^^^^^^^^^^^^^^^^
(RolloutWorker pid=40453)   File "/opt/conda/envs/nuvoenv/lib/python3.11/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 344, in run
(RolloutWorker pid=40453)     outputs = self.step()
(RolloutWorker pid=40453)               ^^^^^^^^^^^
(RolloutWorker pid=40453)   File "/opt/conda/envs/nuvoenv/lib/python3.11/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 370, in step
(RolloutWorker pid=40453)     active_envs, to_eval, outputs = self._process_observations(
(RolloutWorker pid=40453)                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RolloutWorker pid=40453)   File "/opt/conda/envs/nuvoenv/lib/python3.11/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 688, in _process_observations
(RolloutWorker pid=40453)     self._handle_done_episode(
(RolloutWorker pid=40453)   File "/opt/conda/envs/nuvoenv/lib/python3.11/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 838, in _handle_done_episode
(RolloutWorker pid=40453)     self._build_done_episode(env_id, is_done, outputs)
(RolloutWorker pid=40453)   File "/opt/conda/envs/nuvoenv/lib/python3.11/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 727, in _build_done_episode
(RolloutWorker pid=40453)     episode.postprocess_episode(
(RolloutWorker pid=40453)   File "/opt/conda/envs/nuvoenv/lib/python3.11/site-packages/ray/rllib/evaluation/episode_v2.py", line 322, in postprocess_episode
(RolloutWorker pid=40453)     post_batch = policy.postprocess_trajectory(post_batch, other_batches, self)
(RolloutWorker pid=40453)                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RolloutWorker pid=40453)   File "/opt/conda/envs/nuvoenv/lib/python3.11/site-packages/ray/rllib/algorithms/ppo/ppo_torch_policy.py", line 215, in postprocess_trajectory
(RolloutWorker pid=40453)     return compute_gae_for_sample_batch(
(RolloutWorker pid=40453)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RolloutWorker pid=40453)   File "/opt/conda/envs/nuvoenv/lib/python3.11/site-packages/ray/rllib/evaluation/postprocessing.py", line 188, in compute_gae_for_sample_batch
(RolloutWorker pid=40453)     sample_batch = compute_bootstrap_value(sample_batch, policy)
(RolloutWorker pid=40453)                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RolloutWorker pid=40453)   File "/opt/conda/envs/nuvoenv/lib/python3.11/site-packages/ray/rllib/evaluation/postprocessing.py", line 302, in compute_bootstrap_value
(RolloutWorker pid=40453)     vf_preds = np.array(sample_batch[SampleBatch.VF_PREDS])
(RolloutWorker pid=40453)                         ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
(RolloutWorker pid=40453)   File "/opt/conda/envs/nuvoenv/lib/python3.11/site-packages/ray/rllib/policy/sample_batch.py", line 963, in __getitem__
(RolloutWorker pid=40453)     value = dict.__getitem__(self, key)
(RolloutWorker pid=40453)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RolloutWorker pid=40453) KeyError: 'vf_preds'

### Versions / Dependencies

Python 3.11
Ray 2.7, 2.8, 2.9

### Reproduction script

`
config.environment(env=StatelessCartPole).resources(
      num_gpus=int(os.environ.get("RLLIB_NUM_GPUS", "0"))
  ).framework("torch").reporting(min_time_s_per_iteration=0.1).training(
      model={
          "use_lstm": True,
          "lstm_cell_size": 32,
          "lstm_use_prev_action": True,
          "lstm_use_prev_reward": True,
      }
  )

  config.training(num_sgd_iter=5, vf_loss_coeff=0.0001, train_batch_size=512)
  config.model["vf_share_layers"] = True

  stop = {
      "training_iteration": 100,
      "timesteps_total": 100000,
      "episode_reward_mean": 1000,
  }

  tuner = tune.Tuner(
      args.run,
      param_space=config.to_dict(),
      run_config=air.RunConfig(
          stop=stop,
      ),
  )
  results = tuner.fit()

`

### Issue Severity

High: It blocks me from completing my task.

**Comment by wszzyer** [comment]
I'm facing the same problem. Anyone could answer thie question for me? Thanks a lot.
