### ISSUE TITLE
Updated WORKSPACE with new version of rules_python , but bazel build is still taking older version

### ISSUE THREAD

**Issue by modassarrana89** [ray-project/ray#43550]
### What happened + What you expected to happen

Currently Ray WORKSPACE is actually loading rules_python of bazel ( version 0.21.0 ) . rules_python 0.31.0 has changes for s390x architecture , so i am updating it in the WORKSPACE. Even after update , bazel build still points to old version only.

```
[root@m1305001 ray]# git diff WORKSPACE 
diff --git a/WORKSPACE b/WORKSPACE
index 2283b4aaf8..1ee491fef5 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -32,9 +32,9 @@ hedron_compile_commands_setup()
 
 http_archive(
     name = "rules_python",
-    sha256 = "94750828b18044533e98a129003b6a68001204038dc4749f40b195b24c38f49f",
-    strip_prefix = "rules_python-0.21.0",
-    url = "https://github.com/bazelbuild/rules_python/releases/download/0.21.0/rules_python-0.21.0.tar.gz",
+    sha256 = "c68bdc4fbec25de5b5493b8819cfc877c4ea299c0dcb15c244c5a00208cde311",
+    strip_prefix = "rules_python-0.31.0",
+    url = "https://github.com/bazelbuild/rules_python/releases/download/0.31.0/rules_python-0.31.0.tar.gz",
 )
 ``` 

### Versions / Dependencies

Dependency on s390x hardware to reproduce

### Reproduction script

Just updated rules_python version in WORKSPACE & re-run bazel build command
```
[root@m1305001 ray]# git diff WORKSPACE 
diff --git a/WORKSPACE b/WORKSPACE
index 2283b4aaf8..1ee491fef5 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -32,9 +32,9 @@ hedron_compile_commands_setup()
 
 http_archive(
     name = "rules_python",
-    sha256 = "94750828b18044533e98a129003b6a68001204038dc4749f40b195b24c38f49f",
-    strip_prefix = "rules_python-0.21.0",
-    url = "https://github.com/bazelbuild/rules_python/releases/download/0.21.0/rules_python-0.21.0.tar.gz",
+    sha256 = "c68bdc4fbec25de5b5493b8819cfc877c4ea299c0dcb15c244c5a00208cde311",
+    strip_prefix = "rules_python-0.31.0",
+    url = "https://github.com/bazelbuild/rules_python/releases/download/0.31.0/rules_python-0.31.0.tar.gz",
 )
 ```

### Issue Severity

Major

**Comment by aslonnie** [comment]
both bazel and `rules_python` are upgraded.

**Comment by modassarrana89** [comment]
Bazel build is failing ```
[root@amq01 ray]# bazel build ...
INFO: Repository python3_9 instantiated at:
  /root/temp/ray/WORKSPACE:51:27: in <toplevel>
  /root/.cache/bazel/_bazel_root/1f0b8cd78cb67accb3c506c2ebff5ba8/external/rules_python/python/repositories.bzl:296:34: in python_register_toolchains
Repository rule resolved_interpreter_os_alias defined at:
  /root/.cache/bazel/_bazel_root/1f0b8cd78cb67accb3c506c2ebff5ba8/external/rules_python/python/private/toolchains_repo.bzl:123:48: in <toplevel>
ERROR: An error occurred during the fetch of repository 'python3_9':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/1f0b8cd78cb67accb3c506c2ebff5ba8/external/rules_python/python/private/toolchains_repo.bzl", line 81, column 13, in _resolved_interpreter_os_alias_impl
                fail("No platform declared for host OS {} on arch {}".format(os_name, arch))
Error in fail: No platform declared for host OS linux on arch s390x
ERROR: /root/temp/ray/WORKSPACE:51:27: fetching resolved_interpreter_os_alias rule //external:python3_9: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/1f0b8cd78cb67accb3c506c2ebff5ba8/external/rules_python/python/private/toolchains_repo.bzl", line 81, column 13, in _resolved_interpreter_os_alias_impl
                fail("No platform declared for host OS {} on arch {}".format(os_name, arch))
Error in fail: No platform declared for host OS linux on arch s390x
ERROR: Error computing the main repository mapping: no such package '@python3_9//': No platform declared for host OS linux on arch s390x
Loading: 
```

**Comment by Sunidhi-Gaonkar1** [comment]
Hi @aslonnie , Facing the same issue while building ray on ppc64le architecure, even after updating rules_python to 0.31.0. Any pointers will be helpful.Thank you.

**Comment by aslonnie** [comment]
yeah.. I think it is still using an older version of python rules. it is currently shadowed (by some other bazel imports that indirectly imported python rule), and when it is moved up, many builds will fail

https://github.com/ray-project/ray/pull/47260
https://buildkite.com/ray-project/microcheck/builds/4448

0.31.0 actually requires running as non-root user to build, which means we need to convert all the root user operations on CI to non-root, which will be quite some work.

**Comment by Sunidhi-Gaonkar1** [comment]
Hi @aslonnie , We need the changes done in https://github.com/ray-project/ray/pull/47260 , Can you please let us know if you are planning to merge it?

**Comment by aslonnie** [comment]
> Can you please let us know if you are planning to merge it?

it does not work right now. I am not sure how deep is the rabbit hole.
