### ISSUE TITLE
Service discovery calls failing during deploys

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#43685]
We have seen multiple instances where the service discovery calls from the global control plane fail unexpectedly during a deployment because the internal API pod (on the service discovery path) restarts:

```
Traceback (most recent call last): File "/app/product_image.binary.runfiles/product/backend/server/services/lb_manager/cluster_manager_client.py", line 119, in get_cluster_states self.cloud_id, self.organization_id File "/usr/local/lib/python3.7/contextlib.py", line 170, in __aenter__ return await self.gen.__anext__() File "/app/product_image.binary.runfiles/product/backend/server/common/clients/grpc/client.py", line 349, in admin_zone_cluster_manager_client disable_wake=disable_wake, File "/usr/local/lib/python3.7/contextlib.py", line 170, in __aenter__ return await self.gen.__anext__() File "/app/product_image.binary.runfiles/product/backend/server/common/clients/grpc/client.py", line 457, in _compose_az_secure_channel cloud_id, disable_wake File "/app/product_image.binary.runfiles/product/backend/server/common/clients/grpc/client.py", line 123, in get_cluster_manager_internal_ingress_hostname raise_exception, File "/app/product_image.binary.runfiles/product/backend/server/common/clients/grpc/client.py", line 79, in _service_discovery_with_flag response = await service_discovery_request(service, cloud_id, disable_wake) File "/app/product_image.binary.runfiles/product/backend/server/common/clients/grpc/client.py", line 242, in service_discovery_request service_discovery_request, timeout=30 File "/app/product_image.binary.runfiles/py_deps_grpcio/site-packages/grpc/aio/_interceptor.py", line 464, in __await__ response = yield from call.__await__() File "/app/product_image.binary.runfiles/py_deps_grpcio/site-packages/grpc/aio/_call.py", line 308, in __await__ self._cython_call._status, grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with: status = StatusCode.UNAVAILABLE details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:172.20.157.46:5001: Failed to connect to remote host: Connection refused" debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:172.20.157.46:5001: Failed to connect to remote host: Connection refused {grpc_status:14, created_time:"2024-03-04T20:12:56.370476581+00:00"}" > The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/app/product_image.binary.runfiles/product/backend/server/services/actors/service_reconciler.py", line 557, in _reconcile_cloud cloud_status = await cm.apply(plan) File "/app/product_image.binary.runfiles/product/backend/server/services/lb_manager/aws/aws_alb_manager.py", line 217, in apply self.cluster_manager_client, service_goals File "/app/product_image.binary.runfiles/product/backend/server/services/lb_manager/shared/status_util.py", line 57, in gather_service_replica_status cluster_id_to_status = await cluster_state_provider.get_cluster_states(cluster_ids) File "/app/product_image.binary.runfiles/product/backend/server/services/lb_manager/cluster_manager_client.py", line 136, in get_cluster_states ) from e backend.server.common.clients.exceptions.GrpcClientError: Failed to fetch cluster status
```

There is only one replica of the internal API pod, so to avoid this we need to replicate it.

**Comment by shomilj** [comment]
We should also deploy the internal API before deploying the API -- so that if the internal API doesn't come up for whatever reason the API can hold onto the in-memory cache of resolved service discovery instead of waking up & failing.

cc @aslonnie (we will need some deployment ordering on the global control plane deploy path)
