### ISSUE TITLE
Log monitor issue

### ISSUE THREAD

**Issue by markgoodhead** [ray-project/ray#4382]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.6.4
- **Python version**: 3.7

### Describe the problem
When running a Tune experiment from the autoscaler from time to time I get the following error:

```
2019-03-15 15:48:49,381	ERROR worker.py:1752 -- The log monitor on node ip-10-2-247-245 failed with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/longshotsyndicate/ray/python/ray/log_monitor.py", line 268, in <module>
    log_monitor.run()
  File "/home/ubuntu/longshotsyndicate/ray/python/ray/log_monitor.py", line 219, in run
    anything_published = self.check_log_files_and_publish_updates()
  File "/home/ubuntu/longshotsyndicate/ray/python/ray/log_monitor.py", line 175, in check_log_files_and_publish_updates
    next_line = file_info.file_handle.readline()
  File "/home/ubuntu/conda/envs/venv/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 0: unexpected end of data
```

**Comment by robertnishihara** [comment]
@markgoodhead thanks for reporting this. I'm currently unable to reproduce this. I tried

```python
import ray

ray.init()

@ray.remote
def f():
    print("\xc2")

f.remote()
```

in Python 3.7.

This prints

```
(pid=60142) Â
```

Any ideas for how to reproduce this?

**Comment by markgoodhead** [comment]
It might be quite hard to reproduce - it happened when running a very large cluster (84 boxes, ~6k cores) and was sporadic and infrequent over many jobs so quite possibly some load edge case. I also don't get when running locally for small jobs. I was hoping the error trace alone might be enough

**Comment by robertnishihara** [comment]
Related to https://stackoverflow.com/questions/35028683/python3-unicodedecodeerror-with-readlines-method.

Ok, I'm not 100% sure how the issue arises, but I can artificially reproduce it by doing something like

```python
# Open some worker file.
f = open('/tmp/ray/session_2019-03-20_19-.../logs/worker-f46537658....out', 'wb')

f.write(b'\xe5abc\nline2\nline3\n')
f.write(b'\xe5abc\nline2\nline3\n')
f.write(b'\xe5abc\nline2\nline3\n')
f.flush()
```

**Comment by marlonjan** [comment]
Hi, having the same issue here. Also sporadic and infrequent over many jobs.

Kind regards,
Marlon

**Comment by chunyang-wen** [comment]
Same here. Just locally setup 1 ps 2 workers. It failed

```python
2019-08-15 17:59:46,342	ERROR worker.py:1678 -- The log monitor on node XXX.local failed with the following error:
Traceback (most recent call last):
  File "/Users/XXX/tools/ray-ps-env/ray-ps-env/lib/python3.6/site-packages/ray/log_monitor.py", line 268, in <module>
    log_monitor.run()
  File "/Users/XXX/tools/ray-ps-env/ray-ps-env/lib/python3.6/site-packages/ray/log_monitor.py", line 219, in run
    anything_published = self.check_log_files_and_publish_updates()
  File "/Users/XXX/tools/ray-ps-env/ray-ps-env/lib/python3.6/site-packages/ray/log_monitor.py", line 175, in check_log_files_and_publish_updates
    next_line = file_info.file_handle.readline()
  File "/Users/XXX/tools/ray-ps-env/ray-ps-env/bin/../lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 22: invalid continuation byte
```

**Comment by robertnishihara** [comment]
@marlonjan and @chunyang-wen thanks for reporting this. I'd like to get this fixed soon. Does anyone have a consistent way of reproducing the issue? That will make it substantially easier to debug.
