### ISSUE TITLE
[Tune|Air|Train] `wandb` errors out with `PB2` scheduler 

### ISSUE THREAD

**Issue by simonsays1980** [ray-project/ray#43855]
### What happened + What you expected to happen

# What happened

I ran a hyperparameter search with `PB2` using `tune` and `rllib`. I logged results with `wandb` using the `WandbLoggerCallback`. The experiement was run on GCP using the `2.10.0.d8b3d6-py39-gpu` image. While `PB2` worked seemlessly, the `wandb` logging errored out quite early in the experiment (iteration 14 of 500) with the following error:

```python
2024-03-09 04:02:33,890	WARNING syncer.py:406 -- Last sync command failed with the following error:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/syncer.py", line 404, in _launch_sync_process
    self.wait()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/syncer.py", line 474, in wait
    raise e
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/syncer.py", line 472, in wait
    self._sync_process.wait(timeout=timeout or self.sync_timeout)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/syncer.py", line 173, in wait
    raise exception
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/syncer.py", line 136, in entrypoint
    result = self._fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/storage.py", line 212, in _upload_to_fs_path
    _pyarrow_fs_copy_files(local_path, fs_path, destination_filesystem=fs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/storage.py", line 110, in _pyarrow_fs_copy_files
    return pyarrow.fs.copy_files(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pyarrow/fs.py", line 269, in copy_files
    _copy_files_selector(source_fs, source_sel,
  File "pyarrow/_fs.pyx", line 1616, in pyarrow._fs._copy_files_selector
  File "pyarrow/error.pxi", line 113, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file '/tmp/ray/session_2024-03-09_03-41-15_467742_274/artifacts/2024-03-09_03-44-00/pco_with_pb2_hps_search/driver_artifacts/pco_ant_velocity_gym_v1_52603_00001_1_2024-03-09_03-44-02/wandb/latest-run/files/wandb-metadata.json'. Detail: [errno 2] No such file or directory
```
Could this may be related to `PB2` pausing and restarting runs? At least in `wandb` I see only 14 iterations in the runs. Is there maybe a config parameter for `wandb` that should be used when using a hyperparameter search scheduler in Ray (s.th. like `resume="must``?

# What you expected to happen
That `wandb` logs for each of the 10 runs I have the iterations in sequence (from 1 - 500) and does not error out. Basically, that all necessary information for logging is available to `wandb` when using a scheduler in Ray `tune` and that not the user has to figure out, if another `wandb` configuration needs to be used with a scheduler.   

### Versions / Dependencies

Ubuntu 20.0
Python 3.9
Ray Image 2.10.0.d8b3d6-py39-gpu`

### Reproduction script

```python
import random

from ray.air.integrations.wandb import WandbLoggerCallback
from ray import train, tune

from ray.rllib.algorithms.ppo.ppo import PPOConfig
from ray.rllib.connectors.env_to_module.mean_std_filter import MeanStdFilter
from ray.rllib.env.single_agent_env_runner import SingleAgentEnvRunner
from ray.tune.schedulers.pb2 import PB2


pb2_scheduler = PB2(
    time_attr="training_iteration",
    metric="episode_reward_mean",
    mode="max",
    perturbation_interval=15,
    # Copy bottom % with top % weights.
    quantile_fraction=0.25,
    hyperparam_bounds={
        "lr": [1e-5, 1e-3],
        "gamma": [0.95, 0.99],
        "lambda": [0.9, 1.0],
        "entropy_coeff": [0.0, 1e-5],
        "clip_param": [0.1, 0.4],
        "vf_loss_coeff": [0.01, 1.0],
    },
)

config = (
    PPOConfig()
    .environment(
        env="CartPole-v1",
    )
    .framework(
        framework="torch",
    )
    .rollouts(
        rollout_fragment_length=10000,
        num_envs_per_worker=1,
        num_rollout_workers=2,
        ignore_worker_failures=True,
        recreate_failed_workers=True,
        env_runner_cls=SingleAgentEnvRunner,
        env_to_module_connector=(lambda env: MeanStdFilter(multi_agent=False)),
    )
    .resources(
        num_gpus_per_learner_worker=0.2,
    )
    .experimental(
        _enable_new_api_stack=True,
    )
    .reporting(
        metrics_num_episodes_for_smoothing=50,
    )
    .training(
        lr=tune.sample_from(lambda spec: random.uniform(1e-5, 1e-2)),
        gamma=tune.sample_from(lambda spec: random.uniform(0.95, 0.99)),
        lambda_=tune.sample_from(lambda spec: random.uniform(0.9, 1.0)),
        entropy_coeff=tune.sample_from(lambda spec: random.uniform(0.0, 1e-5)),
        use_kl_loss=True,
        kl_target=0.02,
        clip_param=tune.sample_from(lambda spec: random.uniform(0.1, 0.4)),
        vf_clip_param=float("inf"),
        vf_loss_coeff=tune.sample_from(lambda spec: random.uniform(0.01, 1.0)),
        train_batch_size_per_learner=20000,
        mini_batch_size_per_learner=64,
        num_sgd_iter=10,
        model={
            "fcnet_activation": "tanh",
            "fcnet_hiddens": [64, 64],
        },
    )
    .debugging(
        log_level="DEBUG",
        seed=0
    )
)

if tune.Tuner.can_restore(path="gs://ray-results-2022-09-01/"):

    tuner = tune.Tuner.restore(
        path="gs://ray-results-2022-09-01/",
        trainable="PPO",
        param_space=config,
        resume_errored=True,
        resume_unfinished=True,
    )

else:
    tuner = tune.Tuner(
        "PPO",
        param_space=config,
        tune_config=tune.TuneConfig(
            num_samples=10,
            scheduler=pb2_scheduler,
        ),
        run_config=train.RunConfig(
            storage_path="gs://ray-results-2022-09-01/",
            sync_config=train.SyncConfig(
                # Note, Cloud Storage defines the biggest costs.
                # Less frequent syncing might work here to save costs.
                sync_period=600,
            ),
            checkpoint_config=train.CheckpointConfig(
                checkpoint_at_end=True,
                # These settings also intend to save Cloud Storage costs.
                checkpoint_frequency=5,
                num_to_keep=5,
            ),
            stop={"training_iteration": 500},
            name="ppo_with_pb2_hps_search",
            callbacks=[
                WandbLoggerCallback(
                    api_key_file="data/wandb/wandb_api_key.txt",
                    project="rllib-ppo",
                    log_config=True,
                )
            ],
        ),
    )

tuner.fit()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by justinvyu** [comment]
@simonsays1980 Does this error get logged happen very consistently throughout the run? I'm thinking this might be a race condition of wandb deleting some file, while that file is trying to be synced to cloud storage.

Does the run eventually succeed? The syncing should get retried throughout the run.

**Comment by simonsays1980** [comment]
> @simonsays1980 Does this error get logged happen very consistently throughout the run? I'm thinking this might be a race condition of wandb deleting some file, while that file is trying to be synced to cloud storage.
> 
> Does the run eventually succeed? The syncing should get retried throughout the run.

Hi @justinvyu thanks for taking a look. It does get logged consistently during the run. I later had to stop because of  many `_QueueActor`s and `WandBActor`s started and stopped again - it looked like a mess. Regrettably I have no worker logs stored. I think it should be reproducable given the cluster YAML and the run script. The runs did not succeed because of these stopping and restarting actions. This took away the memory (156GB) and left no space for the runs - I got a OOM.
