### ISSUE TITLE
[serve] Calling `.result()` multiple times on Deployment Response will fail

### ISSUE THREAD

**Issue by zcin** [ray-project/ray#43879]
### What happened + What you expected to happen

I started a Serve application and sent a request to it through a `DeploymentHandle`. Calling `.result()` the first time on the `DeploymentResponse` object gives me the correct result, but calling `.result()` second time gives me an error.

### Versions / Dependencies

master 01c8059aacf82e5330325855c78b0abd2dc31b29

### Reproduction script

Serve application:
```
from ray import serve

@serve.deployment
class Hello:
    def __call__(self):
        return {"x": "y"}


h = Hello.bind()
```

Calling the application:
```
>>> h = serve.get_app_handle("default")
>>> ref = h.remote()
>>> ref
<ray.serve.handle.DeploymentResponse object at 0x12a1805e0>
>>> ref.result()
{'x': 'y'}
>>> ref.result()
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 465, in ray._raylet.ObjectRefGenerator._next_sync
  File "python/ray/_raylet.pyx", line 5012, in ray._raylet.CoreWorker.try_read_next_object_ref_stream
  File "python/ray/_raylet.pyx", line 568, in ray._raylet.check_status
ray.exceptions.ObjectRefStreamEndOfStreamError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cindyz/ray/python/ray/serve/handle.py", line 486, in result
    obj_ref = self._to_object_ref_sync(
  File "/Users/cindyz/ray/python/ray/serve/handle.py", line 526, in _to_object_ref_sync
    return self._to_object_ref_or_gen_sync(
  File "/Users/cindyz/ray/python/ray/serve/handle.py", line 347, in _to_object_ref_or_gen_sync
    obj_ref_or_gen = obj_ref_or_gen._next_sync(
  File "python/ray/_raylet.pyx", line 483, in ray._raylet.ObjectRefGenerator._next_sync
StopIteration
```

### Issue Severity

None

**Comment by edoakes** [comment]
This is a regression from Ray 2.9 (introduced by my routing changes)

**Comment by edoakes** [comment]
Re-open until cherry pick

**Comment by khluu** [comment]
I just merged cherry pick in @edoakes
