### ISSUE TITLE
FastAPI serialization issues when using FastAPI and Faststream with Ray Serve

### ISSUE THREAD

**Issue by simonChoi034** [ray-project/ray#44074]
### What happened + What you expected to happen

I am having serialization issue when I am including Faststream into my existing fastapi app and ray deployment

Error:
```
Traceback (most recent call last):
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ray/_private/serialization.py", line 65, in pickle_dumps
    return pickle.dumps(obj)
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 89, in dumps
    cp.dump(obj)
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 734, in dump
    return Pickler.dump(self, obj)
TypeError: 'NoneType' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/share/user/simon.choi/.virtualenv/ray_testing/bin/serve", line 8, in <module>
    sys.exit(cli())
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ray/serve/scripts.py", line 440, in run
    import_attr(import_path), args_dict
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ray/_private/utils.py", line 1182, in import_attr
    module = importlib.import_module(module_name)
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/simon/ray_test/src/./main.py", line 6, in <module>
    from deployments import *
  File "/home/simon/ray_test/src/./deployments/__init__.py", line 1, in <module>
    from deployments.api_server import APIServer
  File "/home/simon/ray_test/src/./deployments/api_server.py", line 45, in <module>
    class APIServer:
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ray/serve/api.py", line 231, in decorator
    pickle_dumps(app, error_msg="Failed to serialize the FastAPI app.")
  File "/home/simon/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ray/_private/serialization.py", line 70, in pickle_dumps
    raise TypeError(msg) from e
TypeError: Failed to serialize the FastAPI app.:
================================================================================
Checking Serializability of <fastapi.applications.FastAPI object at 0x7fe97adb63b0>
================================================================================
!!! FAIL serialization: 'NoneType' object is not callable
    Serializing 'add_api_route' <bound method FastAPI.add_api_route of <fastapi.applications.FastAPI object at 0x7fe97adb63b0>>...
    !!! FAIL serialization: 'NoneType' object is not callable
        Serializing '__func__' <function FastAPI.add_api_route at 0x7fe9cd5585e0>...
    WARNING: Did not find non-serializable object in <bound method FastAPI.add_api_route of <fastapi.applications.FastAPI object at 0x7fe97adb63b0>>. This may be an oversight.
================================================================================
Variable: 

        FailTuple(add_api_route [obj=<bound method FastAPI.add_api_route of <fastapi.applications.FastAPI object at 0x7fe97adb63b0>>, parent=<fastapi.applications.FastAPI object at 0x7fe97adb63b0>])

was found to be non-serializable. There may be multiple other undetected variables that were non-serializable. 
Consider either removing the instantiation/imports of these variables or moving the instantiation into the scope of the function/class. 
================================================================================
Check https://docs.ray.io/en/master/ray-core/objects/serialization.html#troubleshooting for more information.
If you have any suggestions on how to improve this error message, please reach out to the Ray developers on github.com/ray-project/ray/issues/
================================================================================
```

### Versions / Dependencies

ray                       2.9.3
fastapi                   0.105.0
faststream                0.4.7

### Reproduction script

```
from ray import serve
from fastapi import FastAPI
from faststream.rabbit.fastapi import RabbitRouter

rabbitmq_router = RabbitRouter(host="localhost", login="admin", password="password")
app = FastAPI(lifespan=rabbitmq_router.lifespan_context)
app.include_router(rabbitmq_router)

@serve.deployment(name="api_server")
@serve.ingress(app)
class APIServer:
    def __init__(self) -> None:
         pass

    @rabbitmq_router.subscriber("test")
    @rabbitmq_router.publisher("output")
    async def testing(self):
        ...
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by abrarsheikh** [comment]
this should now be possible factory pattern in fastapi
```python
from ray import serve
from fastapi import FastAPI
from faststream.rabbit.fastapi import RabbitRouter

def create_app():
    rabbitmq_router = RabbitRouter(host="localhost")
    app = FastAPI(lifespan=rabbitmq_router.lifespan_context)
    app.include_router(rabbitmq_router)

    @rabbitmq_router.subscriber("test")
    @rabbitmq_router.publisher("output")
    async def testing():
        pass
    return app

@serve.deployment(name="api_server")
@serve.ingress(create_app)
class APIServer:
    def __init__(self) -> None:
         pass


app = APIServer.bind()
serve.run(app)

```
