### ISSUE TITLE
[Core] Dead named actor returned by get_actor

### ISSUE THREAD

**Issue by jobh** [ray-project/ray#44083]
### What happened + What you expected to happen

When requesting an actor in a tight loop (using the `get_if_exists` option), I sometimes get a dead actor returned.

It looks like there may by a race condition where the actor can be looked up by name even if its reference count has dropped to zero.

I did some simple instrumentation around the `get_if_exists` handling in `actor.py`, and the failure happens exactly when `get_actor(...)` succeeds, i.e. it picks up the previous actor instance instead of creating a new.

```
  Traceback (most recent call last):
  File "/home/jobh/src/simula/transact/Reference_route_service/test_ray_lock.py", line 20, in <module>
    test_lock()
  File "/home/jobh/src/simula/transact/Reference_route_service/test_ray_lock.py", line 15, in test_lock
    ray.get(actor.release.remote())
  File "/home/jobh/mambaforge/envs/transact/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/jobh/mambaforge/envs/transact/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/jobh/mambaforge/envs/transact/lib/python3.10/site-packages/ray/_private/worker.py", line 2626, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
        class_name: LockActor
        actor_id: f41165a4b8f1cca43c60623001000000
        pid: 1728191
        name: test
        namespace: locks
        ip: 172.16.0.146
The actor is dead because all references to the actor were removed.
```

Possibly related:
- #41324
- #14923

### Versions / Dependencies

Ray 2.9.3
Python 3.10.10
Ubuntu 23.10

### Reproduction script

Reproducer. It is timing dependent, for me it fails to reproduce if I remove the (unused) numpy import.

```
import asyncio

import numpy as np
import ray


@ray.remote(namespace="locks", num_cpus=0)
class LockActor:
    def release(self):
        ...


def test_lock():
    actor = LockActor.options(name="test", get_if_exists=True).remote()
    ray.get(actor.release.remote())


ray.init()
for i in range(100):
    test_lock()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jobh** [comment]
A simpler/more reliable reproducer:
```
import ray


@ray.remote
class Actor:
    def act(self):
        ...


ray.init()
for i in range(100):
    actor = Actor.options(name="test", namespace="test", get_if_exists=True).remote()
    ray.get(actor.act.remote())
    del actor
```
