### ISSUE TITLE
[Core] when working with gradio,  ray task worker died unexpected

### ISSUE THREAD

**Issue by zzhangpurdue** [ray-project/ray#44109]
### What happened + What you expected to happen

In a gradio demo,  there are two different buttons that trigger two functions, which will call the same ray task function.
Clicking the button A to send request could get through the ray task function, while the rest of requests whichever the request come from will cause `(raylet) A worker died or was killed while executing a task by an unexpected system error.`

Good part is Raylet will restart a new pid for the ray task function.
The detail error log is shown below.

```
(step pid=49869) Traceback (most recent call last):
(step pid=49869)   File "python/ray/_raylet.pyx", line 2206, in ray._raylet.task_execution_handler
(step pid=49869)   File "python/ray/_raylet.pyx", line 2036, in ray._raylet.execute_task_with_cancellation_handler
(step pid=49869) AttributeError: 'Worker' object has no attribute 'core_worker'
(step pid=49869) During handling of the above exception, another exception occurred:
(step pid=49869) Traceback (most recent call last):
(step pid=49869)   File "python/ray/_raylet.pyx", line 2245, in ray._raylet.task_execution_handler
(step pid=49869)   File "/Users/zhicheng/repo/maas-agent/venv/lib/python3.10/site-packages/ray/_private/utils.py", line 178, in push_error_to_driver
(step pid=49869)     worker.core_worker.push_error(job_id, error_type, message, time.time())
(step pid=49869) AttributeError: 'Worker' object has no attribute 'core_worker'
(step pid=49869) Exception ignored in: 'ray._raylet.task_execution_handler'
(step pid=49869) Traceback (most recent call last):
(step pid=49869)   File "python/ray/_raylet.pyx", line 2245, in ray._raylet.task_execution_handler
(step pid=49869)   File "/Users/zhicheng/repo/maas-agent/venv/lib/python3.10/site-packages/ray/_private/utils.py", line 178, in push_error_to_driver
(step pid=49869)     worker.core_worker.push_error(job_id, error_type, message, time.time())
(step pid=49869) AttributeError: 'Worker' object has no attribute 'core_worker'
(raylet) A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 9a2c6bbaf9b0a8f9c81e186e5ffeca5bdc1b664201000000 Worker ID: 8f8c6ba7a9492afe20c8d6c0f10ce50d69a33822dfc1bf62e17aa815 Node ID: 01b84f00a997edb323fc2919ca7cf08a45c7f5a3a2fee70a9d019d83 Worker IP address: 127.0.0.1 Worker port: 54200 Worker PID: 49869 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
(step pid=49869) [2024-03-18 19:53:08,438 C 49869 557096] direct_actor_transport.cc:205:  Check failed: objects_valid 
(step pid=49869) *** StackTrace Information ***
(step pid=49869) 0   _raylet.so                          0x0000000121354921 _ZN3raylsERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEERKNS_10StackTraceE + 65 ray::operator<<()
(step pid=49869) 1   _raylet.so                          0x000000012137fe52 _ZN3ray13SpdLogMessage5FlushEv + 114 ray::SpdLogMessage::Flush()
(step pid=49869) 2   _raylet.so                          0x000000012137fd22 _ZN3ray13SpdLogMessageD2Ev + 18 ray::SpdLogMessage::~SpdLogMessage()
(step pid=49869) 3   _raylet.so                          0x00000001213584ef _ZN3ray6RayLogD2Ev + 47 ray::RayLog::~RayLog()
(step pid=49869) 4   _raylet.so                          0x00000001209f4642 _ZNSt3__1L8__invokeIRZN3ray4core28CoreWorkerDirectTaskReceiver10HandleTaskERKNS1_3rpc15PushTaskRequestEPNS4_13PushTaskReplyENS_8functionIFvNS1_6StatusENSA_IFvvEEESD_EEEE3$_0JSF_EEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSI_DpOSJ_ + 5410 std::__1::__invoke<>()
(step pid=49869) 5   _raylet.so                          0x00000001209cf38e _ZN3ray4core14InboundRequest6AcceptEv + 110 ray::core::InboundRequest::Accept()
(step pid=49869) 6   _raylet.so                          0x0000000120a11332 _ZN3ray4core21NormalSchedulingQueue16ScheduleRequestsEv + 306 ray::core::NormalSchedulingQueue::ScheduleRequests()
(step pid=49869) 7   _raylet.so                          0x0000000120c67372 _ZN12EventTracker15RecordExecutionERKNSt3__18functionIFvvEEENS0_10shared_ptrI11StatsHandleEE + 258 EventTracker::RecordExecution()
(step pid=49869) 8   _raylet.so                          0x0000000120c615a0 _ZNSt3__110__function6__funcIZN23instrumented_io_context4postENS_8functionIFvvEEENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEExE3$_0NS9_ISC_EES4_EclEv + 48 std::__1::__function::__func<>::operator()()
(step pid=49869) 9   _raylet.so                          0x0000000120c60ed7 _ZN5boost4asio6detail18completion_handlerINSt3__18functionIFvvEEENS0_10io_context19basic_executor_typeINS3_9allocatorIvEELm0EEEE11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm + 167 boost::asio::detail::completion_handler<>::do_complete()
(step pid=49869) 10  _raylet.so                          0x00000001214af215 _ZN5boost4asio6detail9scheduler10do_run_oneERNS1_27conditionally_enabled_mutex11scoped_lockERNS1_21scheduler_thread_infoERKNS_6system10error_codeE + 725 boost::asio::detail::scheduler::do_run_one()
(step pid=49869) 11  _raylet.so                          0x00000001214a3101 _ZN5boost4asio6detail9scheduler3runERNS_6system10error_codeE + 289 boost::asio::detail::scheduler::run()
(step pid=49869) 12  _raylet.so                          0x00000001214a2f94 _ZN5boost4asio10io_context3runEv + 36 boost::asio::io_context::run()
(step pid=49869) 13  _raylet.so                          0x0000000120895819 _ZN3ray4core10CoreWorker20RunTaskExecutionLoopEv + 217 ray::core::CoreWorker::RunTaskExecutionLoop()
(step pid=49869) 14  _raylet.so                          0x00000001209544a6 _ZN3ray4core21CoreWorkerProcessImpl26RunWorkerTaskExecutionLoopEv + 310 ray::core::CoreWorkerProcessImpl::RunWorkerTaskExecutionLoop()
(step pid=49869) 15  _raylet.so                          0x0000000120954339 _ZN3ray4core17CoreWorkerProcess20RunTaskExecutionLoopEv + 25 ray::core::CoreWorkerProcess::RunTaskExecutionLoop()
(step pid=49869) 16  _raylet.so                          0x000000012076ae23 _ZL50__pyx_pw_3ray_7_raylet_10CoreWorker_7run_task_loopP7_objectS0_ + 19 __pyx_pw_3ray_7_raylet_10CoreWorker_7run_task_loop()
(step pid=49869) 17  python3.10                          0x000000010aea9b57 method_vectorcall_NOARGS + 135 method_vectorcall_NOARGS
(step pid=49869) 18  python3.10                          0x000000010af8e0bc call_function + 428 call_function
(step pid=49869) 19  python3.10                          0x000000010af8b142 _PyEval_EvalFrameDefault + 27922 _PyEval_EvalFrameDefault
(step pid=49869) 20  python3.10                          0x000000010af84301 _PyEval_Vector + 145 _PyEval_Vector
(step pid=49869) 21  python3.10                          0x000000010af8e0bc call_function + 428 call_function
(step pid=49869) 22  python3.10                          0x000000010af8b142 _PyEval_EvalFrameDefault + 27922 _PyEval_EvalFrameDefault
(step pid=49869) 23  python3.10                          0x000000010af84301 _PyEval_Vector + 145 _PyEval_Vector
(step pid=49869) 24  python3.10                          0x000000010af84251 PyEval_EvalCode + 129 PyEval_EvalCode
(step pid=49869) 25  python3.10                          0x000000010afd793b _PyRun_SimpleFileObject + 875 _PyRun_SimpleFileObject
(step pid=49869) 26  python3.10                          0x000000010afd73ee _PyRun_AnyFileObject + 126 _PyRun_AnyFileObject
(step pid=49869) 27  python3.10                          0x000000010aff809b Py_RunMain + 2075 Py_RunMain
(step pid=49869) 28  python3.10                          0x000000010aff85a3 pymain_main + 403 pymain_main
(step pid=49869) 29  python3.10                          0x000000010aff85fb Py_BytesMain + 43 Py_BytesMain
(step pid=49869) 30  dyld                                0x00007ff803e14386 start + 1942 start
```

### Versions / Dependencies

ray==2.9.3
grpcio==-1.62.1

### Reproduction script

It's hard to abstract a reproducing script at this moment, if could anyone find any clue from the error log would be great.

Else, I have a demo to reproduce it at `https://github.com/modelscope/modelscope-agent/blob/multi-agent/demo/demo_multi_roles_chat_room.ipynb`.   

Thanks.

### Issue Severity

High: It blocks me from completing my task.

**Comment by jjyao** [comment]
Hi @zzhangpurdue I cannot open that notebook.

**Comment by denadai2** [comment]
@zzhangpurdue could you update the notebook?
