### ISSUE TITLE
[RLlib] ValueError when environment returning torch tensor

### ISSUE THREAD

**Issue by TooSchoolForCool** [ray-project/ray#44243]
### What happened + What you expected to happen

The ray agent collector raise ValueError when the env.step() returning torch tensor. There is no error raised when I changing the returns to np.arrray. 

I am wondering does RLlib currently support environment returning torch.Tensor?

The error message is as follows:
```bash
Traceback (most recent call last):
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::PPO.train() (pid=179178, ip=10.1.101.233, actor_id=9bffa6d68cdf9499cf2d97db01000000, repr=PPO)
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 342, in train
    raise skipped from exception_cause(skipped)
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 339, in train
    result = self.step()
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 852, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 3042, in _run_one_training_iteration
    results = self.training_step()
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/algorithms/ppo/ppo.py", line 407, in training_step
    train_batch = synchronous_parallel_sample(
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/execution/rollout_ops.py", line 80, in synchronous_parallel_sample
    sample_batches = [worker_set.local_worker().sample()]
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 694, in sample
    batches = [self.input_reader.next()]
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/evaluation/sampler.py", line 91, in next
    batches = [self.get_data()]
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/evaluation/sampler.py", line 276, in get_data
    item = next(self._env_runner)
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 344, in run
    outputs = self.step()
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 370, in step
    active_envs, to_eval, outputs = self._process_observations(
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 637, in _process_observations
    processed = policy.agent_connectors(acd_list)
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/connectors/agent/pipeline.py", line 41, in __call__
    ret = c(ret)
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/connectors/connector.py", line 265, in __call__
    return [self.transform(d) for d in acd_list]
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/connectors/connector.py", line 265, in <listcomp>
    return [self.transform(d) for d in acd_list]
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/connectors/agent/view_requirement.py", line 118, in transform
    sample_batch = agent_collector.build_for_inference()
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/evaluation/collectors/agent_collector.py", line 366, in build_for_inference
    self._cache_in_np(np_data, data_col)
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/evaluation/collectors/agent_collector.py", line 613, in _cache_in_np
    cache_dict[key] = [_to_float_np_array(d) for d in self.buffers[key]]
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/evaluation/collectors/agent_collector.py", line 613, in <listcomp>
    cache_dict[key] = [_to_float_np_array(d) for d in self.buffers[key]]
  File "/home/zeyu/.virtualenvs/ml-robo/lib/python3.10/site-packages/ray/rllib/evaluation/collectors/agent_collector.py", line 33, in _to_float_np_array
    raise ValueError(torch.is_tensor(v[0]))
ValueError: True
```

### Versions / Dependencies

- ray 2.9.3
- python 3.10

### Reproduction script

Refers to [this issue](https://github.com/ray-project/ray/issues/34199). 

### Issue Severity

High: It blocks me from completing my task.

**Comment by simonsays1980** [comment]
@TooSchoolForCool Thanks for raising this issue. Any reason why you need to use such an old Ray version?
