### ISSUE TITLE
Issues when using with eventlet

### ISSUE THREAD

**Issue by danielrs** [ray-project/ray#4424]
There seems to be an issue when trying to use ray in an application that uses `eventlet`. How to reproduce:

```python
import eventlet
eventlet.monkey_patch()
import ray
ray.init(redis_address="localhost:6379")
```

Traceback:

```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    ray.init(redis_address="localhost:6379")
  File "/Users/danielrs/test/venv/lib/python3.6/site-packages/ray/worker.py", line 1532, in init
    load_code_from_local=load_code_from_local)
  File "/Users/danielrs/test/venv/lib/python3.6/site-packages/ray/worker.py", line 1977, in connect
    driver_task._serialized_raylet_task())
  File "/Users/danielrs/test/venv/lib/python3.6/site-packages/ray/experimental/state.py", line 200, in _execute_command
    return client.execute_command(*args)
  File "/Users/danielrs/test/venv/lib/python3.6/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/Users/danielrs/test/venv/lib/python3.6/site-packages/redis/connection.py", line 994, in get_connection
    connection.connect()
  File "/Users/danielrs/test/venv/lib/python3.6/site-packages/redis/connection.py", line 492, in connect
    sock = self._connect()
  File "/Users/danielrs/test/venv/lib/python3.6/site-packages/redis/connection.py", line 520, in _connect
    socket.SOCK_STREAM):
  File "/Users/danielrs/test/venv/lib/python3.6/site-packages/eventlet/support/greendns.py", line 517, in getaddrinfo
    qname, addrs = _getaddrinfo_lookup(host, family, flags)
  File "/Users/danielrs/test/venv/lib/python3.6/site-packages/eventlet/support/greendns.py", line 479, in _getaddrinfo_lookup
    answer = resolve(host, qfamily, False, use_network=use_network)
  File "/Users/danielrs/test/venv/lib/python3.6/site-packages/eventlet/support/greendns.py", line 425, in resolve
    use_network=use_network)
  File "/Users/danielrs/test/venv/lib/python3.6/site-packages/eventlet/support/greendns.py", line 380, in query
    return end()
  File "/Users/danielrs/test/venv/lib/python3.6/site-packages/eventlet/support/greendns.py", line 359, in end
    raise result[1]
  File "/Users/danielrs/test/venv/lib/python3.6/site-packages/eventlet/support/greendns.py", line 340, in step
    a = fun(*args, **kwargs)
  File "/Users/danielrs/test/venv/lib/python3.6/site-packages/dns/resolver.py", line 858, in query
    if qname.is_absolute():
AttributeError: 'bytes' object has no attribute 'is_absolute'
```

`pip freeze`:

```
attrs==19.1.0
Click==7.0
colorama==0.4.1
dnspython==1.16.0
eventlet==0.24.1
filelock==3.0.10
flatbuffers==1.10
funcsigs==1.0.2
greenlet==0.4.15
monotonic==1.5
more-itertools==6.0.0
numpy==1.16.2
pluggy==0.9.0
py==1.8.0
pytest==4.3.1
PyYAML==5.1
ray==0.6.4
redis==3.2.1
six==1.12.0
typing==3.6.6
```

Bug could be in the Redis package, but it seems to be working fine with eventlet by itself.

**Comment by robertnishihara** [comment]
Like you suggested, I can reproduce this issue with

```python
import eventlet
eventlet.monkey_patch()
import redis
redis.StrictRedis()
```

What does `eventlet` do?

The error I get is

```
Traceback (most recent call last):
  File "/Users/rnishihara/anaconda3/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/rnishihara/anaconda3/lib/python3.6/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/rnishihara/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/rnishihara/anaconda3/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/Users/rnishihara/anaconda3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 480, in mainloop
    self.interact()
  File "/Users/rnishihara/anaconda3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 463, in interact
    code = self.prompt_for_code()
  File "/Users/rnishihara/anaconda3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 376, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/Users/rnishihara/anaconda3/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 415, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/Users/rnishihara/anaconda3/lib/python3.6/site-packages/prompt_toolkit/eventloop/posix.py", line 91, in run
    self.add_reader(stdin, read_from_stdin)
  File "/Users/rnishihara/anaconda3/lib/python3.6/site-packages/prompt_toolkit/eventloop/posix.py", line 275, in add_reader
    self.selector.register(fd)
  File "/Users/rnishihara/anaconda3/lib/python3.6/site-packages/prompt_toolkit/eventloop/select.py", line 75, in register
    sel.register(fd)
  File "/Users/rnishihara/anaconda3/lib/python3.6/site-packages/prompt_toolkit/eventloop/select.py", line 130, in register
    self._sel.register(fd, selectors.EVENT_READ, None)
  File "/Users/rnishihara/anaconda3/lib/python3.6/selectors.py", line 539, in register
    kev = select.kevent(key.fd, select.KQ_FILTER_READ,
AttributeError: module 'select' has no attribute 'kevent'
```

**Comment by danielrs** [comment]
The issue is being fixed here:
https://github.com/andymccurdy/redis-py/issues/1136
