### ISSUE TITLE
[RLlib] Attribute error when trying to compute action after training Multi Agent PPO with new New API Stack

### ISSUE THREAD

**Issue by Dr-IceCream** [ray-project/ray#44475]
### What happened + What you expected to happen

After training Multi Agent PPO with new New API Stack under the guidance of [ how-to-use-the-new-api-stack](https://docs.ray.io/en/latest/rllib/rllib-new-api-stack.html#how-to-use-the-new-api-stack)
I tried to compute actions:
```
    saved_algorithm = Algorithm.from_checkpoint(
        checkpoint=algorithm_path,
        policy_ids={"controlled_vehicle_0", "controlled_vehicle_1"},
        policy_mapping_fn=lambda agent_id, episode, **kwargs: f"controlled_vehicle_{agent_id}",
    )
    print("saved_algorithm type:", type(saved_algorithm))
    # Evaluate the model
    obs, info = env.reset()
    print("obs:", obs)
    actions = {}
    for agent_id, agent_obs in obs.items():
        policy_id = f"controlled_vehicle_{agent_id}"
        action = saved_algorithm.get_policy(policy_id).compute_single_action(agent_obs)
        actions[agent_id] = action
    print("action", actions)
```
but I get the error message: 

> AttributeError: 'MultiAgentEnvRunner' object has no attribute 'get_policy'

I also tried some other way like:
`action = saved_algorithm.compute_single_action(agent_obs, policy_id)`
but still get the same error message: AttributeError: 'MultiAgentEnvRunner' object has no attribute 'get_policy'.
I have seen a similar issue in #40312, are these two issues the same?

detailed error message are as follows:

> Traceback (most recent call last):
>   File "test_evaluate.py", line 151, in <module>
>     evaluate_agent(saved_algorithm, env)
>   File "test_evaluate.py", line 112, in evaluate_agent
>     action = saved_algorithm.get_policy(policy_id).compute_single_action(agent_obs)
>   File "C:\Users\Ice Cream\miniconda3\envs\env_highway\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
>     return method(self, *_args, **_kwargs)
>   File "C:\Users\Ice Cream\miniconda3\envs\env_highway\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 2051, in get_policy
>     return self.workers.local_worker().get_policy(policy_id)
> AttributeError: 'MultiAgentEnvRunner' object has no attribute 'get_policy'

and before I call this method, I also printed the relevant info, this part looks normal:
> saved_algorithm type: <class 'ray.rllib.algorithms.ppo.ppo.PPO'>
> saved_algorithm.get_config() <ray.rllib.algorithms.ppo.ppo.PPOConfig object at 0x0000014B0E4D4370>

through the code:
```
    print("saved_algorithm type:", type(saved_algorithm))
    print("saved_algorithm.get_config()",saved_algorithm.get_config())
```

### Versions / Dependencies

Ray 2.10.0
Python 3.8.18
Windows11

### Reproduction script

the code used for training is as follows:
```
    register_env("ray_dict_highway_env", create_env)
    config = (
        PPOConfig().environment(env="ray_dict_highway_env")
        .experimental(_enable_new_api_stack=True)
        .rollouts(env_runner_cls=MultiAgentEnvRunner)
        .resources(
            num_learner_workers=0,
            num_gpus_per_learner_worker=1,
            num_cpus_for_local_worker=1,
        )
        .training(model={"uses_new_env_runners": True})
        .multi_agent(
            policies={
                "controlled_vehicle_0",
                "controlled_vehicle_1"
            },
            policy_mapping_fn=lambda agent_id, episode, **kwargs: f"controlled_vehicle_{agent_id}",
        )
        .framework("torch")
    )
    current_script_directory = os.path.dirname(os.path.abspath(__file__))
    ray_result_path = os.path.join(current_script_directory, folder_path, "ray_results")
    tuner = tune.Tuner(
        "PPO",
        run_config=RunConfig(
            storage_path=ray_result_path,
            name="2-agent-PPO",
            stop={"timesteps_total": 5e5}
        ),
        param_space=config.to_dict() 
    )
    results = tuner.fit()
```
And the code for loading checkpoints:
```
algorithm_path = r"D:\DRL_Project\DRL_highway\experiments\hw-fast-ma-dict-v0_rllib-mappo\2024-04-01_01-28\ray_results\2-agent-PPO\PPO_ray_dict_highway_env_1c7ab_00000_0_2024-04-01_01-28-38\checkpoint_000000"
saved_algorithm = Algorithm.from_checkpoint(
        checkpoint=algorithm_path,
        policy_ids={"controlled_vehicle_0", "controlled_vehicle_1"},
        policy_mapping_fn=lambda agent_id, episode, **kwargs: f"controlled_vehicle_{agent_id}",
    )
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by Dr-IceCream** [comment]
It seems I have initially solved this issue by referring to the solutions in #40312 and the comments in the ray.rllib.core.rl_module code.
using the following code repalcing the original code:
```
# Evaluate the model
obs, info = env.reset()
print("obs:", obs)
actions = {}
for agent_id, agent_obs in obs.items():
    # Determine the policy ID for the current agent using the policy mapping function
    policy_id = f"controlled_vehicle_{agent_id}"
    # Compute actions for each agent
    rl_module = saved_algorithm.get_module(policy_id)
    fwd_ins = {"obs": torch.Tensor([agent_obs])}
    fwd_outputs = rl_module.forward_inference(fwd_ins)
    action_dist_class = rl_module.get_inference_action_dist_cls()
    action_dist = action_dist_class.from_logits(
        fwd_outputs["action_dist_inputs"]
    )
    action = action_dist.sample()[0].numpy()
    actions[agent_id] = action
# actions = saved_algorithm.compute_actions(obs)
print("actions: ", actions)
```
and the output is as follows:

> actions:  {0: array(4, dtype=int64), 1: array(3, dtype=int64)}

it seems to be right.

but I still wonder why can't directly use the `saved_algorithm.get_policy(policy_id).compute_single_action(agent_obs)` or `saved_algorithm.compute_single_action(agent_obs, policy_id)` for action computing.

**Comment by sortiz-hub** [comment]
I am facing a similar issue with the SingleAgentEnvRunner - see screeenshot attached.

![issue](https://github.com/ray-project/ray/assets/63668386/33e6492e-618b-48ba-b5d9-c1b21ece4d45)

**Comment by vilmire** [comment]
i dont know why this issue is p2. should be p0

**Comment by grizzlybearg** [comment]
This issue is still persistent. Hey @simonsays1980 @sven1977. Is there any plan to fix this?

**Comment by adadelta** [comment]
I'm unfortunately having this issue too:

`ppo_agents = Algorithm.from_checkpoint(checkpoint=checkpoint_path)
actions = ppo_agents.compute_actions(observations=observations)
`

Results in:

`AttributeError: 'MultiAgentEnvRunner' object has no attribute 'get_policy'`

Since we've had a similar P1 issue, should this be upgraded? @simonsays1980 @sven1977

**Comment by ipsec** [comment]
Same error here.
I'm unable to use a trained model.

**Comment by lrsheldon** [comment]
I am also seeing this error in both PPO and SAC. Is there a recommended workaround or stable commit to rollback to?

**Comment by AlizargarDeu** [comment]
I see this error in my singleAgent too.  not any solution for this? 🙄

**Comment by AlizargarDeu** [comment]
I have found a solution for this. I changed the action call method(according to this @https://docs.ray.io/en/master/rllib/rllib-training.html)

**Comment by The3DWizard** [comment]
There does not seem to be any incentive to fix this, as this part of the code is labelled "OldAPIStack". I am going to try to export the model using torch directly. It would probably still be nice to have some convenience function in the Algorithm class to do the export directly.

**Comment by itwasabhi** [comment]
Seeing the same issue. 

Additionally,`Algorithm.from_checkpiont(checkpoint)` gives me a `AttributeError: 'Checkpoint' object has no attribute 'as_posix'` whereas `Algorithm.from_checkpoint(checkpoint.path)` does not.

**Comment by The3DWizard** [comment]
Unfortunately I have not been able to use torch.onnx export methods so far to export the model. I need dictionary inputs for my model and I have not found a way to use the onnx export methods with dictionary input. So the situation is a bit frustrating right now. Hope I find a solution soon. Any help is appreciated as I cannot export my model right now.

**Comment by The3DWizard** [comment]
> Unfortunately I have not been able to use torch.onnx export methods so far to export the model. I need dictionary inputs for my model and I have not found a way to use the onnx export methods with dictionary input. So the situation is a bit frustrating right now. Hope I find a solution soon. Any help is appreciated as I cannot export my model right now.

Update: I was able to export my model using `torch.onnx.export` using `Algorithm.get_module`, which is part of the new api stack. The key was to use a dictionary input in the form of {{key1: value1, key2: value2, ...}, {}} for the `args` argument of the `export` function (note the second, in my case empty, dictionary). It is also important to account for batch size in your values passed via the dictionary. Here is an example that shows my use case:

```
rl_module_player_white = algo.get_module("policy_white")
batch_size = 1
dummy_input = ({
    "obs": torch.tensor(
        np.array(
            [[np.random.randint(0, n) for n in game_state_multi_discrete_sizes] for _ in range(batch_size)]
        ),
        dtype=torch.float32,
    ),
    "action_mask": torch.tensor(
        np.random.randint(0, 2, (batch_size, action_space_length)), dtype=torch.float32
    ),
}, {})
torch.onnx.export(
    rl_module_player_white,               # The model to export
    dummy_input,             # Dummy input for tracing
    "./export_white/model.onnx",               # Output path
    export_params=True,      # Store parameters in the model file
    opset_version=17,        # ONNX version
    do_constant_folding=True,# Optimize constant expressions
    input_names=["obs", "action_mask"],   # Names for model inputs
    output_names=["embeddings", "output"], # Names for model outputs
)
```

**Comment by cleversonahum** [comment]
I am facing the same error with Ray RLlib versions 2.40.0 and 2.40.1. Is there any news about that? I can use the RL module approach, but the Algorithm seems simpler and straightforward.

**Comment by AlizargarDeu** [comment]
@simonsays1980 
@sven1977 

the problem still persist(AttributeError: 'SingleAgentEnvRunner' object has no attribute 'get_policy')
There isn't still any reliable fix for that??

**Comment by vahidqo** [comment]
Having the same problem. No intention to solve it?!

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-41-63145b682dfe>](https://localhost:8080/#) in <cell line: 0>()
     15         if not done[agent_id]:
     16             # Access the policy for the agent
---> 17             policy = algo.get_policy(f"policy_{agent_id[-1]}")
     18             # Compute the action using the policy
     19             actions[agent_id] = policy.compute_single_action(obs_i)

[/usr/local/lib/python3.11/dist-packages/ray/rllib/algorithms/algorithm.py](https://localhost:8080/#) in get_policy(self, policy_id)
   2107             policy_id: ID of the policy to return.
   2108         """
-> 2109         return self.env_runner.get_policy(policy_id)
   2110 
   2111     @PublicAPI

AttributeError: 'MultiAgentEnvRunner' object has no attribute 'get_policy'`

**Comment by AdithyaRaman** [comment]
> I found a solution for this. I changed the action call method (according to this: https://docs.ray.io/en/master/rllib/rllib-training.html) as below:
> 
> from ray.rllib.core.rl_module import RLModule
> 
> 
> # Create only the neural network (RLModule) from our checkpoint.
>   rl_module = RLModule.from_checkpoint(
>       pathlib.Path(best_checkpoint) / "learner_group" / "learner" / "rl_module"
>   )["default_policy"
> for call action:
> 
>   while not terminated and not truncated:
>         env.render()
>         # Compute the next action from a batch (B=1) of observations.
>         torch_obs_batch = torch.from_numpy(np.array([obs]))
>         action_logits = rl_module.forward_inference({"obs": torch_obs_batch})[
>             "action_dist_inputs"
>        [ ]
>         # The default RLModule used here produces action logits (from which
>         # we'll have to sample an action or use the max-likelihood one).
>         action = torch.argmax(action_logits[0]).numpy()
>         obs, reward, terminated, truncated, info = env.step(action)
>         episode_return += reward](https://github.com/ray-project/ray/issues/44475)


HI @AlizargarDeu :
My saved checkpoint directory does not seem to have a learner_group subdirectory. Is that something that needs to be specified while saving the checkpoints?


Also @simonsays1980 : Is it possible to update the issue to p0. Being unable to use a trained model on the latest stable version of RLlib should imo be getting a higher priority.

**Comment by AlizargarDeu** [comment]
Hi @AdithyaRaman 
No, actually when you use New API stack these will be created automatically  in saved training directory , somewhere in your temp directory. It is as below:
root>temp> chekpoint_tmp...> env_runners , lerner_group ....When you give the saved directory, it will be loaded accordingly.

**Comment by notjacobjun** [comment]
Running into this issue as well on the new api stack, so imo +1 that this priority should be bumped up to P0 as well

**Comment by sebastian-cao** [comment]
Same question here, but I have a new idea to solve it.
Restore trained model, and add some output in environment, after that contrinue to train one times. 😵‍💫😵‍💫😵‍💫

**Comment by alexhasenclever** [comment]
> After several hours of staring at the screen, I figured it out. The output was a Gaussian distribution with mean and standard deviation for both the action spaces. Hence the 2x the number of values

Hello @AdithyaRaman,

could you please share the code you used to extract the gaussian distribution tensor, and how you converted it into an action that the env can understand?
I tried the following code below, but the agent is not behaving as expected.

`import pathlib
import torch
import numpy as np
import ray
from ray.tune.registry import register_env
from raylib.custom_env import SimpleEnv
from ray.rllib.core.rl_module import RLModule
from torch.distributions import Normal



# Initialize Ray
ray.init(ignore_reinit_error=True)

# Register the environment
register_env("my_custom_env", lambda config: SimpleEnv())

# Define the checkpoint directory
checkpoint_dir = "/models_sac_1"  

# Load the RLModule  from the checkpoint
rl_module = RLModule.from_checkpoint(
    pathlib.Path(checkpoint_dir) / "learner_group" / "learner" / "rl_module"
)["default_policy"]

# Test the agent in the environment
env = SimpleEnv()
obs, _ = env.reset()

done = False
truncated = False
total_reward = 0

# Run the agent in the environment
while not (done or truncated):
    env.render()  # Render the environment

    # Compute the next action using the RLModule
    torch_obs_batch = torch.from_numpy(np.array([obs])).to(torch.float32)  # Ensure dtype is float32
    action_logits = rl_module.forward_inference({"obs": torch_obs_batch})  # Perform inference
    action_dist_inputs = action_logits['action_dist_inputs']
    log_std, mean = torch.chunk(action_dist_inputs, 2, dim=-1)

# Convert log_std to std
    std = torch.exp(log_std)

# Sample action from the Gaussian distribution
    action = mean + std * torch.randn_like(std)

    print(action)
    action_np = action.detach().cpu().numpy() # This will be the vector for the env.step() function

    obs, reward, done, truncated, info = env.step(action_np[0])  # Take the step in the environment
    total_reward += reward

print(f"Total reward: {total_reward}")

# Clean up
ray.shutdown()
`

During training, the agent performed very well, and always reached it's destination, so I assume that the problem is not my reward function. Thank you very much for your time!

Regards

**Comment by sebastian-cao** [comment]
> Does that really work? I have been looking for viable work-arounds.

yes, it really works, continue to train one time and get the result.😵‍💫

**Comment by AlizargarDeu** [comment]
Hello @AdithyaRaman 
could you please help me ? I got an awful problem, when I use your script.
Is there any better contact way? I mean not here. my email address is : alizargarian@gmail.com
It would be pleaser if you help me . Thanks a lot

**Comment by kolcker** [comment]
Hello @sven1977, @simonsays1980, 
I have the same issue as described almost a year ago.
I'm restoring model policy as provided in example: 
```
rl_module = RLModule.from_checkpoint(
    pathlib.Path(checkpoint_dir) / "learner_group" / "learner" / "rl_module"
)["default_policy"]
```
Unfortunately, I have the same result as described below. The quality of the restored model is much weaker even on data that I used for training.

> but when I used a similar code approach to conduct multiple episode evaluations, the results were significantly worse compared to the training outcomes reported during training: episode_len_mean dropped from about 29 to 7, and episode_reward_mean decreased from about 42 to 10. After recording the videos, it was also evident that the agent indeed had its own strategy π, but the performance was relatively poor. I suspect that the specific steps I used to calculate actions directly through the rl_module might differ from those actually used during training, but I am not clear on the specific steps for action calculation used during training. Therefore, I would like to ask if I might have indeed done something wrong in this part?
> and I still wonder why can't directly use the `saved_algorithm.get_policy(policy_id).compute_single_action(agent_obs)` or `saved_algorithm.compute_single_action(agent_obs, policy_id)` for action computing? or does this mean that this invocation will have a new syntax in the new API stack.

Is it possible to increase the priority of this issue **up to P0**? Or provide an official workaround for the correct model/policy procedure of loading it from the checkpoint?

Thanks in advance. Looking for your feedback.

**Comment by simonsays1980** [comment]
@Dr-IceCream thanks for raising this issue and apologies for the late reply. I am sorry that you and other users are running into problems when using a trained policy in inference. 

First, we need to distinguish - as has already been pointed out by @AlizargarDeu - between the old api stack (which will be deprecated soon) and the new API stack. The former uses the `Policy` class while the latter uses the `RLModule`. We highly recommend to go for the new API stack. 

As the issue first reported by @Dr-IceCream is about the new API stack I will try (as there is no repro) to answer to this issue. The new API stack has no `get_policy` and no `compute_actions/compute_single_action` instead we need to load the module via `Algorithm.get_module` (but this only returns a single policy not a `MultiRLModule`, but at best load the `RLModule` checkpoint directly as shown by some users here (e.g. @alexhasenclever ): 

```python
from ray.rllib.core import (
    COMPONENT_ENV_RUNNER,
    COMPONENT_ENV_TO_MODULE_CONNECTOR,
    COMPONENT_MODULE_TO_ENV_CONNECTOR,
    COMPONENT_LEARNER_GROUP,
    COMPONENT_LEARNER,
    COMPONENT_RL_MODULE,
    DEFAULT_MODULE_ID,
)
from ray.rllib.core.rl_module.rl_module import RLModule


# Create RLModule from a checkpoint.
    rl_module = RLModule.from_checkpoint(
        os.path.join(
            checkpoint.path, # (or directly a string path to the checkpoint dir)
            COMPONENT_LEARNER_GROUP,
            COMPONENT_LEARNER,
            COMPONENT_RL_MODULE,
            DEFAULT_MODULE_ID,
        )
    )
```

This will get you an `RLModule` in the single-agent case and a `MultiRLModule` in the multi-agent case. Now this module can be called via `rl_module.forward_inference` to produce actions. 

The important part is now: RLlib uses pre- and post-processing of data. For the pre-processing (converting for example to a multi-agent batch and applying observation filters (like e.g. `MeanStdFilter`) the `EnvToModulePipeline` is used and for the post-processing the `ModuleToEnvPipeline` is used. Specifically, if you used stateful filters in training like the `MeanStdFilter` the preprocessing needs to be applied in inference to avoid diverging results. The post-processing includes also the action sampling (e.g. mean and log-std logits are used to sample from a Gaussian). These pipelines need RLlib's `SingleAgentEpisode` or `MultiAgentEpisode` to be used. 

`EnvToModulePipeline` and `ModuleToEnvPipeline` are both stored in the checkpoint, too and can be loaded as follows:
```python
from ray.rllib.connectors.env_to_module import EnvToModulePipeline
from ray.rllib.connectors.module_to_env import ModuleToEnvPipeline

# Load the env-to-module pipeline for pre-processing.
env_to_module = EnvToModulePipeline.from_checkpoint(
        os.path.join(
            best_result.checkpoint.path,
            COMPONENT_ENV_RUNNER,
            COMPONENT_ENV_TO_MODULE_CONNECTOR,
        )
    )

# Load the module-to-env pipeline for post-processing.
module_to_env = ModuleToEnvPipeline.from_checkpoint(
        os.path.join(
            best_result.checkpoint.path,
            COMPONENT_ENV_RUNNER,
            COMPONENT_MODULE_TO_ENV_CONNECTOR,
        )
    )
```

Here is an example that uses the `RLModule` checkpoint and the pipeline checkpoints together with our `SingleAgentEpisode` in inference: https://github.com/ray-project/ray/blob/master/rllib/examples/inference/policy_inference_after_training_w_connector.py

I hope this helps you @Dr-IceCream and the other users in the future use of RLlib.

**Comment by yevhen-reksilier** [comment]
That's very sad RLLib has plenty of examples about training agents, but a **single** example of inference after training - [policy_inference_after_training_w_connector.py](https://github.com/ray-project/ray/blob/master/rllib/examples/inference/policy_inference_after_training_w_connector.py] ). All other examples show the training only with no usage

@simonsays1980, your comment really helps, would be so kind to explain it further?

You said that after loading `RLModule.from_checkpoint` we would get RLModule in the single-agent case and a MultiRLModule in the multi-agent case that can be further used as `rl_module.forward_inference` to produce actions.

I am trying this suggestion for checking the waterworld - the basic RLLib example at [pettingzoo_parameter_sharing](https://github.com/ray-project/ray/blob/master/rllib/examples/multi_agent/pettingzoo_parameter_sharing.py). 
so what I've done:
1. loaded the `RLModule.from_checkpoint` (got the instance of `DefaultPPOTorchRLModule`)
2. as per your suggestion loaded `EnvToModulePipeline.from_checkpoint`
3. as per your suggestion loaded `ModuleToEnvPipeline.from_checkpoint`
4. created instance of the waterworld original environment `env = waterworld_v4.env(render_mode="human")`
5. now, making the instance of the MultiAgentEpisode
```
episode = MultiAgentEpisode(
        observations=[{agent: env.observe(agent) for agent in env.agents}],
        observation_space={agent: env.observation_space(agent) for agent in env.agents}, # another question - why it is defined as Optional[gym.Space] but only works when it is a AgentIDs dict...probably documentation problem
        action_space={agent: env.action_space(agent) for agent in env.agents},
        terminateds={agent: False for agent in env.agents},
        truncateds={agent: False for agent in env.agents}
)
```
6. reset the env and called 
```
episode.add_env_reset(
        observations={ag: env.observe(ag) for ag in env.agents},
        infos={},
)
```

but when calling the pipeline
```
env_to_module(
        episodes=[episode],
        rl_module=rl_module,
        explore=False,
        shared_data={},
)
```
there is an error saying 

>     File "...\ray\rllib\connectors\common\agent_to_module_mapping.py", line 180, in __call__
>     if rl_module is not None and column in rl_module:
>                                      ^^^^^^^^^^^^^^^^^^^
>     TypeError: argument of type 'DefaultPPOTorchRLModule' is not iterable


is there any other trick or specific classes hierarchy that should be used?
