### ISSUE TITLE
[Dashboard] Dashboard pollutes logs using Prometheus client that fails to write into `/tmp`

### ISSUE THREAD

**Issue by alexeykudinkin** [ray-project/ray#44498]
### What happened + What you expected to happen

Seeing a lot of failures in the `dashboard.log` like below (making it to grow really large):

```
2024-04-04 13:12:18,772 ERROR http_server_head.py:193 -- Error emitting api metrics: [Errno 13] Permission denied: '/tmp/prometheus_multiproc_dir/histogram_316.db'
Traceback (most recent call last):
  File "/home/ray/virtualenv/lib/python3.10/site-packages/ray/dashboard/http_server_head.py", line 179, in metrics_middleware
    self.metrics.metrics_request_duration.labels(
  File "/usr/local/lib/python3.10/dist-packages/prometheus_client/metrics.py", line 168, in labels
    self._metrics[labelvalues] = self.__class__(
  File "/usr/local/lib/python3.10/dist-packages/prometheus_client/metrics.py", line 509, in __init__
    super(Histogram, self).__init__(
  File "/usr/local/lib/python3.10/dist-packages/prometheus_client/metrics.py", line 116, in __init__
    self._metric_init()
  File "/usr/local/lib/python3.10/dist-packages/prometheus_client/metrics.py", line 537, in _metric_init
    self._sum = values.ValueClass(self._type, self._name, self._name + '_sum', self._labelnames, self._labelvalues)
  File "/usr/local/lib/python3.10/dist-packages/prometheus_client/values.py", line 56, in __init__
    self.__reset()
  File "/usr/local/lib/python3.10/dist-packages/prometheus_client/values.py", line 70, in __reset
    files[file_prefix] = MmapedDict(filename)
  File "/usr/local/lib/python3.10/dist-packages/prometheus_client/mmap_dict.py", line 61, in __init__
    self._f = open(filename, 'rb' if read_mode else 'a+b')
PermissionError: [Errno 13] Permission denied: '/tmp/prometheus_multiproc_dir/histogram_316.db'
```

### Versions / Dependencies

2.9

### Reproduction script

N/A

### Issue Severity

Low: It annoys or frustrates me.

**Comment by alexeykudinkin** [comment]
This has been caused by accidentally setting up `PROMETHEUS_MULTIPROC_DIR` env var was leading us to use wrong `MultiProcessValue` metric class:

```
Looking at the code seems like we're falling down this branch into MultiProcessValue which we should not:

def get_value_class():
    # Should we enable multi-process mode?
    # This needs to be chosen before the first metric is constructed,
    # and as that may be in some arbitrary library the user/admin has
    # no control over we use an environment variable.
    if 'prometheus_multiproc_dir' in os.environ or 'PROMETHEUS_MULTIPROC_DIR' in os.environ:
        return MultiProcessValue()
    else:
        return MutexValue
```
