### ISSUE TITLE
[<Ray component: Core|RLlib|etc...>] PPO reset_config() AttributeError: 'dict' object has no attribute '_enable_new_api_stack'

### ISSUE THREAD

**Issue by edmund735** [ray-project/ray#44506]
### What happened + What you expected to happen

After implementing the reset_config() method for PPO and running PB2 on a custom environment, it gives this error: 

[36m(PPO pid=2962936)[0m Checkpoint successfully created at: Checkpoint(filesystem=local, path=/home/ray_results/PPO_2024-04-05_16-44-29/PPO_Trading-v0_4caab_00013_13_clip_param=0.2000,entropy_coeff=0.0001,gamma=0.9990,grad_clip=0.8000,kl_coeff=2.0000,kl_target=0.020_2024-04-05_16-44-30/checkpoint_000001)
2024-04-05 17:07:56,609	ERROR tune_controller.py:1374 -- Trial task failed for trial PPO_Trading-v0_4caab_00012
Traceback (most recent call last):
  File "/home/.conda/envs/.../lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/home/.conda/.../seniorthesis/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/.conda/envs/.../lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/.conda/envs/.../lib/python3.10/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): [36mray::PPO.restore()[39m (pid=2962936, ip=172.21.1.18, actor_id=6a11ddd599cbb631d74be14201000000, repr=PPO)
  File "/home/.conda/envs/.../lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 577, in restore
    self.load_checkpoint(checkpoint_dir)
  File "/home/.conda/envs/.../lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 2343, in load_checkpoint
    if self.config._enable_new_api_stack:
AttributeError: 'dict' object has no attribute '_enable_new_api_stack'

If I disable reuse_actors = False when running PB2, this error doesn't show up, so I assume that maybe I don't have a correct implementation of reset_config? I added it under the `class PPO(Algorithm):` under the ray library in my conda env:

def reset_config(self, new_config):
        self.config = new_config
        return True

### Versions / Dependencies

python=Python 3.10.14
ray-rllib=2.9.3

### Reproduction script

The PPO class:
class PPO(Algorithm):
    ...
    def reset_config(self, new_config):
        self.config = new_config
        self.config._enable_new_api_stack = new_config._enable_new_api_stack
        return True

script:
import ray
from ray import train, tune
from ray.tune.tuner import Tuner
from ray.tune.registry import register_env
# from ray.rllib.algorithms.ppo import PPOConfig
from ray.rllib.algorithms.ppo import PPO
from ray.tune.schedulers.pb2 import PB2
import argparse
import os

import numpy as np
import pandas as pd

# Postprocess the perturbed config to ensure it's still valid.
def explore(config):
    # Ensure we collect enough timesteps to do sgd.
    if config["train_batch_size"] < config["sgd_minibatch_size"] * 2:
        config["train_batch_size"] = config["sgd_minibatch_size"] * 2
    # Ensure we run at least one sgd iter.
    config["train_batch_size"] = int(config["train_batch_size"])
    return config

pb2 = PB2(
        time_attr="timesteps_total",
        metric="episode_reward_mean",
        mode="max",
        perturbation_interval=50000,
        # Specifies the hyperparam search space
        hyperparam_bounds={
            'gamma': [0.9, 0.9999],
            'lambda_': [0.8, 1.0],
            'kl_coeff': [0.3, 2.0],
            'kl_target': [0.001, 0.1],
            'sgd_minibatch_size': [8, 2048],
            'num_sgd_iter': [1, 20],
            'vf_loss_coeff': [0, 1],
            'entropy_coeff': [1e-8, 0.1],
            'clip_param': [0.1, 0.5],
            'lr': [1e-5, 1],
            'train_batch_size': [2048, 65536],
            'vf_clip_param': [1, 10],
            'grad_clip': [0.3, 5],
        },
        quantile_fraction=0.25,  # copy bottom % with top %
        custom_explore_fn = explore,
    )

    tuner = Tuner(
        trainable = PPO,
        param_space = {
            'env': 'Pendulum-v1,
            'model': {'free_log_std': True},
            'horizon': 100, # length of MDP
            'gamma': tune.choice([0.9, 0.95, 0.98, 0.99, 0.995, 0.999, 0.9999]),
            'lambda_': tune.choice([0.8, 0.9, 0.92, 0.95, 0.98, 0.99, 1.0]),
            'kl_coeff': tune.choice([0.3, 0.5, 1, 1.5, 2.0]),
            'kl_target': tune.choice([0.1, 0.05, 0.03, 0.02, 0.01, 0.005, 0.001]),
            'sgd_minibatch_size': tune.choice([8, 16, 32, 64, 128, 256, 512, 1024, 2048]),
            'num_sgd_iter': tune.choice([1, 5, 10, 20]),
            'vf_loss_coeff': tune.uniform(0, 1),
            'entropy_coeff': tune.loguniform(1e-8, 0.1),
            'clip_param': tune.choice([0.1, 0.2, 0.3, 0.4, 0.5]),
            'lr': tune.loguniform(1e-5, 1),
            'train_batch_size': tune.choice([2048, 4096, 8192, 16384, 32768, 65536]),
            'vf_clip_param': tune.choice([1, 2, 3, 5, 10]),
            'grad_clip': tune.choice([0.3, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 2, 5]),
        },
        tune_config=tune.TuneConfig(
            num_samples=10, # number of trials
            scheduler=pb2,
            reuse_actors=True,
            ),
        run_config=train.RunConfig(
            name='test',
            ),
    )
    results = tuner.fit()

    print("best hyperparameters: ", results.get_best_result().config)

### Issue Severity

High: It blocks me from completing my task.

**Comment by edmund735** [comment]
Any updates on this?

**Comment by simonsays1980** [comment]
@edmund735 thanks for filing this issue. We are moving to a new API stack these times and the `_enable_new_api_stack` is a key to signal, if the new or old stack should be used. This has to be part of the configuration - which is usually of type `AlgorithmConfig` and not `dict` as in your case of the example. You can take a look at our examples (e.g. https://github.com/ray-project/ray/blob/master/rllib/examples/_old_api_stack/complex_struct_space.py). The `AlgorithmConfig`  takes care of all needed keys. 

In addition, when using the new stack (at best in the actual ray release) the `api_stack` method should be used to enable the new api stack (see here for an example: https://github.com/ray-project/ray/blob/cf7a09daa201c92d71cffa9f4a8e0afe45ab0475/rllib/utils/test_utils.py#L1370).

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
