### ISSUE TITLE
Ray installation in Azure fail for timeout

### ISSUE THREAD

**Issue by EnricoBeltramo** [ray-project/ray#44525]
### What happened + What you expected to happen

I followed this tutorial:
https://docs.ray.io/en/latest/cluster/vms/user-guides/launching-clusters/azure.html#start-ray-with-the-ray-cluster-launcher)

The installation work fine, but at the end fail to connect to cluster: 
Timeout, server 52.169.211.183 not responding.
    SSH still not available (SSH command failed.), retrying in 5 seconds.
  New status: update-failed
  !!!
  Full traceback: Traceback (most recent call last):
  File "F:\ProgramData\anaconda3\envs\inventio-server-quick-anomaly-py310-env-dev\lib\site-packages\ray\autoscaler\_private\updater.py", line 159, in run
    self.do_update()
  File "F:\ProgramData\anaconda3\envs\inventio-server-quick-anomaly-py310-env-dev\lib\site-packages\ray\autoscaler\_private\updater.py", line 336, in do_update
    self.wait_ready(deadline)
  File "F:\ProgramData\anaconda3\envs\inventio-server-quick-anomaly-py310-env-dev\lib\site-packages\ray\autoscaler\_private\updater.py", line 279, in wait_ready
    raise Exception("wait_ready timeout exceeded.")
Exception: wait_ready timeout exceeded.

  Error message: wait_ready timeout exceeded.
  !!!

### Versions / Dependencies

OS: win
Python: 3.8
Ray: 2.10.0

### Reproduction script

ray up example-gpu-docker.yaml

example-gpu-docker.yaml attached as example-gpu-docker.txt

[example-gpu-docker.txt](https://github.com/ray-project/ray/files/14893182/example-gpu-docker.txt)

### Issue Severity

High: It blocks me from completing my task.

**Comment by anyscalesam** [comment]
can you try on latest Ray?

**Comment by mattip** [comment]
Closing. Please reopen or open a new issue if there is more feedback.
