### ISSUE TITLE
[release-test] `single_node_oom.aws_1712366943` failed

### ISSUE THREAD

**Issue by fishbone** [ray-project/ray#44574]
https://buildkite.com/ray-project/release/builds/12870#018eb9b1-7fbf-47c8-9614-ddb215121271	

```
(raylet) Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.
Traceback (most recent call last):
  File "/tmp/ray/session_2024-04-07_10-59-32_032714_77/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_single_node_oom_aws_wadkuianls__anyscale_pkg_cfd4f431649e94dd10fa0dac95565e46/stress_tests/test_parallel_tasks_memory_pressure.py", line 72, in <module>
    results = [ray.get(ref) for ref in task_refs]
  File "/tmp/ray/session_2024-04-07_10-59-32_032714_77/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_single_node_oom_aws_wadkuianls__anyscale_pkg_cfd4f431649e94dd10fa0dac95565e46/stress_tests/test_parallel_tasks_memory_pressure.py", line 72, in <listcomp>
    results = [ray.get(ref) for ref in task_refs]
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/worker.py", line 2633, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/worker.py", line 866, in get_objects
    raise value
ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
Subprocess return code: 1
[INFO 2024-04-07 11:07:43,579] anyscale_job_wrapper.py: 190  Process 633 exited with return code 1.
```

The test seems exit, but with error code.

**Comment by stephanie-wang** [comment]
Closed by #44745.
