### ISSUE TITLE
Error when running Resnet example on GPU machine.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#446]
I'm seeing the following error when I run

```bash
python ray/examples/resnet/resnet_main.py --eval_dir=/tmp/resnet-model/eval --train_data_path=data/cifar-10-batches-bin/data_batch* --eval_data_path=data/cifar-10-batches-bin/test_batch.bin --dataset=cifar10 --num_gpus=1
```

```
rkn@c81:/data/rkn$ python ray/examples/resnet/resnet_main.py --eval_dir=/tmp/resnet-model/eval --train_data_path=data/cifar-10-batches-bin/data_batch* --eval_data_path=data/cifar-10-batches-bin/test_batch.bin --dataset=cifar10 --num_gpus=1
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Waiting for redis server at 127.0.0.1:29018 to respond...
Starting local scheduler with 48 CPUs and 1 GPUs.
Failed to start polymer.
The log files for tensorboard are stored at ip 169.229.49.181.
Starting computation.
Remote function compute_steps failed with:

Traceback (most recent call last):
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/data/rkn/anaconda3/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_1_random_shuffle_queue' is closed and has insufficient elements (requested 128, current size 0)
	 [[Node: random_shuffle_queue_DequeueMany = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](random_shuffle_queue, random_shuffle_queue_DequeueMany/n/_2785)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/rkn/ray/python/ray/worker.py", line 1847, in process_task
    worker.actors[task.actor_id().id()], *arguments)
  File "ray/examples/resnet/resnet_main.py", line 86, in compute_steps
    self.model.variables.sess.run(self.model.train_op)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_1_random_shuffle_queue' is closed and has insufficient elements (requested 128, current size 0)
	 [[Node: random_shuffle_queue_DequeueMany = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](random_shuffle_queue, random_shuffle_queue_DequeueMany/n/_2785)]]

Caused by op 'random_shuffle_queue_DequeueMany', defined at:
  File "/data/rkn/ray/python/ray/workers/default_worker.py", line 61, in <module>
    ray.worker.main_loop()
  File "/data/rkn/ray/python/ray/worker.py", line 1925, in main_loop
    process_task(task)
  File "/data/rkn/ray/python/ray/worker.py", line 1847, in process_task
    worker.actors[task.actor_id().id()], *arguments)
  File "ray/examples/resnet/resnet_main.py", line 69, in __init__
    images, labels = cifar_input.build_input([total_images, data[3]], hps.batch_size, dataset, True)
  File "/data/rkn/ray/examples/resnet/cifar_input.py", line 96, in build_input
    images, labels = example_queue.dequeue_many(batch_size)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 458, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1310, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): RandomShuffleQueue '_1_random_shuffle_queue' is closed and has insufficient elements (requested 128, current size 0)
	 [[Node: random_shuffle_queue_DequeueMany = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](random_shuffle_queue, random_shuffle_queue_DequeueMany/n/_2785)]]



You can inspect errors by running

    ray.error_info()

If this driver is hanging, start a new one with

    ray.init(redis_address="127.0.0.1:29018")

Traceback (most recent call last):
  File "ray/examples/resnet/resnet_main.py", line 190, in <module>
    tf.app.run()
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "ray/examples/resnet/resnet_main.py", line 187, in main
    train()
  File "ray/examples/resnet/resnet_main.py", line 177, in train
    all_weights = ray.get([actor.compute_steps(weight_id) for actor in train_actors])
  File "/data/rkn/ray/python/ray/worker.py", line 1662, in get
    raise RayGetError(object_ids[i], value)
ray.worker.RayGetError: Could not get objectid ObjectID(8a2ca98b3ef16b3b77b07eccb172edb8e6830a34). It was created by remote function compute_steps which failed with:

Remote function compute_steps failed with:

Traceback (most recent call last):
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/data/rkn/anaconda3/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_1_random_shuffle_queue' is closed and has insufficient elements (requested 128, current size 0)
	 [[Node: random_shuffle_queue_DequeueMany = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](random_shuffle_queue, random_shuffle_queue_DequeueMany/n/_2785)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/rkn/ray/python/ray/worker.py", line 1847, in process_task
    worker.actors[task.actor_id().id()], *arguments)
  File "ray/examples/resnet/resnet_main.py", line 86, in compute_steps
    self.model.variables.sess.run(self.model.train_op)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_1_random_shuffle_queue' is closed and has insufficient elements (requested 128, current size 0)
	 [[Node: random_shuffle_queue_DequeueMany = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](random_shuffle_queue, random_shuffle_queue_DequeueMany/n/_2785)]]

Caused by op 'random_shuffle_queue_DequeueMany', defined at:
  File "/data/rkn/ray/python/ray/workers/default_worker.py", line 61, in <module>
    ray.worker.main_loop()
  File "/data/rkn/ray/python/ray/worker.py", line 1925, in main_loop
    process_task(task)
  File "/data/rkn/ray/python/ray/worker.py", line 1847, in process_task
    worker.actors[task.actor_id().id()], *arguments)
  File "ray/examples/resnet/resnet_main.py", line 69, in __init__
    images, labels = cifar_input.build_input([total_images, data[3]], hps.batch_size, dataset, True)
  File "/data/rkn/ray/examples/resnet/cifar_input.py", line 96, in build_input
    images, labels = example_queue.dequeue_many(batch_size)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 458, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1310, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/data/rkn/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): RandomShuffleQueue '_1_random_shuffle_queue' is closed and has insufficient elements (requested 128, current size 0)
	 [[Node: random_shuffle_queue_DequeueMany = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](random_shuffle_queue, random_shuffle_queue_DequeueMany/n/_2785)]]
```

**Comment by robertnishihara** [comment]
@Wapaul1 have you seen this before?

**Comment by robertnishihara** [comment]
This should be fixed now. E.g., by #960.
