### ISSUE TITLE
[Job]  Job Submission broken in Python 3.10 Windows

### ISSUE THREAD

**Issue by n30111** [ray-project/ray#44625]
### What happened + What you expected to happen

I'm using the example given in the Ray docs, to run the ray job on Windows platform. But throws the error related to unsupported `preexec_fn` on windows platform.

```
Job submission server address: http://127.0.0.1:8265

---------------------------------------
Job 'raysubmit_XugCFgLjDpCiRgFw' failed
---------------------------------------

Status message: Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\\lib\site-packages\ray\dashboard\modules\job\job_manager.py", line 413, in run
    child_process = self._exec_entrypoint(log_path)
  File "C:\ProgramData\miniconda3\envs\\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\ProgramData\miniconda3\envs\\lib\site-packages\ray\dashboard\modules\job\job_manager.py", line 229, in _exec_entrypoint
    child_process = subprocess.Popen(
  File "C:\ProgramData\miniconda3\envs\\lib\subprocess.py", line 789, in __init__
    raise ValueError("preexec_fn is not supported on Windows "
ValueError: preexec_fn is not supported on Windows platforms
```

### Versions / Dependencies

Ray2.10, Python 3.10, Windows 10

### Reproduction script

```
# script.py
import ray

@ray.remote
def hello_world():
    return "hello world"

ray.init()
print(ray.get(hello_world.remote()))
```

```
from ray.job_submission import JobSubmissionClient

# If using a remote cluster, replace 127.0.0.1 with the head node's IP address.
client = JobSubmissionClient("http://127.0.0.1:8265")
job_id = client.submit_job(
    # Entrypoint shell command to execute
    entrypoint="python script.py",
    # Path to the local directory that contains the script.py file
    runtime_env={"working_dir": "./"}
)
print(job_id)
```

```
ray job status <job_id>
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by rynewang** [comment]
Regression from https://github.com/ray-project/ray/pull/45116. We need to do conditional: if is windows, don't set it

**Comment by rynewang** [comment]
Already fixed in https://github.com/ray-project/ray/pull/44632
