### ISSUE TITLE
[RayCore]Can’t connect to ray cluster when passing `runtime_env` to `ray.init`

### ISSUE THREAD

**Issue by pengye91** [ray-project/ray#44757]
### What happened + What you expected to happen

Hi team,

when I tried to connect to an existing cluster without a `runtime_env` parameter, it works fine.

but when I tried to pass a `runtime_env` to the cluster, it will hang forever and raise the error:

```
ConnectionAbortedError: Initialization failure from server:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/util/client/server/proxier.py", line 704, in Datapath
    if not self.proxy_manager.start_specific_server(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/util/client/server/proxier.py", line 305, in start_specific_server
    serialized_runtime_env_context = self._create_runtime_env(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/util/client/server/proxier.py", line 281, in _create_runtime_env
    raise TimeoutError(
TimeoutError: GetOrCreateRuntimeEnv request failed after 5 attempts. Last exception: HTTP Error 503: Service Unavailable
```

the code I'm using is just:
```
In [1]: import ray

In [2]: ray.init(address="ray://localhost:10001", runtime_env={"pip": ["emoji"]})
```

the head log is like:

```
12024-04-15 02:38:37,429	INFO server.py:885 -- Starting Ray Client server on 0.0.0.0:10001, args Namespace(address='240.52.20.253:6379', host='0.0.0.0', mode='proxy', port=10001, redis_password=None, runtime_env_agent_address='http://240.52.20.253:50805')

22024-04-15 02:40:49,943	INFO proxier.py:696 -- New data connection from client a56378b6ab814ecbb066279448514367: 
32024-04-15 02:40:49,952	INFO proxier.py:223 -- Increasing runtime env reference for ray_client_server_23000.Serialized runtime env is {"_ray_commit": "9be5a16e3ccad0710bba08d0f75e9ff774ae6880", "pip": {"packages": ["emoji"], "pip_check": false}}.
42024-04-15 02:41:49,001	WARNING proxier.py:270 -- GetOrCreateRuntimeEnv request failed: HTTP Error 503: Service Unavailable. Retrying after 0.5s. 5 retries remaining.
52024-04-15 02:42:49,001	WARNING proxier.py:270 -- GetOrCreateRuntimeEnv request failed: HTTP Error 503: Service Unavailable. Retrying after 1.0s. 4 retries remaining.
62024-04-15 02:43:50,001	WARNING proxier.py:270 -- GetOrCreateRuntimeEnv request failed: HTTP Error 503: Service Unavailable. Retrying after 2.0s. 3 retries remaining.
72024-04-15 02:44:52,001	WARNING proxier.py:270 -- GetOrCreateRuntimeEnv request failed: HTTP Error 503: Service Unavailable. Retrying after 4.0s. 2 retries remaining.
82024-04-15 02:45:56,002	WARNING proxier.py:270 -- GetOrCreateRuntimeEnv request failed: HTTP Error 503: Service Unavailable. Retrying after 8.0s. 1 retries remaining.
92024-04-15 02:47:04,001	WARNING proxier.py:270 -- GetOrCreateRuntimeEnv request failed: HTTP Error 503: Service Unavailable. Retrying after 16.0s. 0 retries remaining.
102024-04-15 02:47:50,016	INFO proxier.py:768 -- a56378b6ab814ecbb066279448514367 last started stream at 1713174049.9413047. Current stream started at 1713174049.9413047.
```

I digged a little bit in the source code and found it may because I'm using a proxy to connect to the internet, but I've already added the IP CIDR `240.52.0.0/16` to my environment variable: `no_proxy` and `NO_PROXY`, I'm not sure but it seems not working. 

and I also tried the same code but through Job API, and it works:
```
ray job submit --address="http://localhost:8265" --runtime-env-json='{"pip": ["emoji"]}' -- python test_ray_job.py
Job submission server address: http://localhost:8265

-------------------------------------------------------
Job 'raysubmit_gZuVtxj2Uc8H4q1G' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_gZuVtxj2Uc8H4q1G
  Query the status of the job:
    ray job status raysubmit_gZuVtxj2Uc8H4q1G
  Request the job to be stopped:
    ray job stop raysubmit_gZuVtxj2Uc8H4q1G
```

can you help to check what should I do to make it work?

thank you.

### Versions / Dependencies

I’m running ray cluster on K8S (EKS) using KubeRay Operator.

The image for the cluster is rayproject/ray:2.9.0

Python version is 3.8.18

### Reproduction script

```
import ray

ray.init("ray://localhost:10001", runtime_env={"pip": ["emoji"]})
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by jjyao** [comment]
Hi @pengye91 ray client is not encouraged to run Ray application at this point. Can you use ray job submission instead?

**Comment by eternalphane** [comment]
I'm encountering the same issue running `test_runtime_env.py::test_decorator_complex` in CI with `*_PROXY` env vars. I can confirm that both `no_proxy` and `NO_PROXY` is not working, since all the requests to runtime env agent are recorded in my proxy server's log.

<details>
<summary>Test output</summary>

```log
(.venv.3.9) nonroot@31781aaecec6:~/ray$ python -m pytest python/ray/tests/test_runtime_env.py::test_decorator_complex -v -s
/home/nonroot/ray/.venv.3.9/lib/python3.9/site-packages/pytest_virtualenv.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import working_set
Test session starts (platform: linux, Python 3.9.22, pytest 7.4.4, pytest-sugar 0.9.5)
cachedir: .pytest_cache
rootdir: /home/nonroot/ray
configfile: pytest.ini
plugins: asyncio-0.17.0, lazy-fixture-0.6.3, anyio-3.7.1, forked-1.4.0, sphinx-0.5.1.dev0, virtualenv-1.7.0, aiohttp-0.3.0, httpserver-1.0.6, rerunfailures-11.1.2, shutil-1.7.0, timeout-2.1.0, docker-tools-3.1.3, sugar-0.9.5
timeout: 180.0s
timeout method: signal
timeout func_only: False
collecting ... worker_path=/home/nonroot/ray/python/ray/_private/workers/default_worker.py, setup_worker_path=/home/nonroot/ray/python/ray/_private/workers/setup_worker.py

2025-06-28 22:06:30,120 INFO utils.py:128 -- Overwriting previous Ray address (10.4.0.253:60444). Running ray.init() on this node will now connect to the new instance at 10.4.0.253:47689. To override this behavior, pass address=10.4.0.253:60444 to ray.init().
2025-06-28 22:06:30,128 INFO client_builder.py:244 -- Passing the following kwargs to ray.init() on the server: log_to_driver

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ Timeout +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stack of Thread-10 (140371157817088) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nonroot/ray/.venv.3.9/lib/python3.9/site-packages/grpc/_channel.py", line 276, in consume_request_iterator
    request = next(request_iterator)
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/queue.py", line 171, in get
    self.not_empty.wait()
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stack of Thread-9 (140371166209792) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nonroot/ray/.venv.3.9/lib/python3.9/site-packages/grpc/_channel.py", line 276, in consume_request_iterator
    request = next(request_iterator)
  File "/home/nonroot/ray/python/ray/util/client/dataclient.py", line 247, in _requests
    req = self.request_queue.get()

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stack of Thread-8 (140371174602496) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nonroot/ray/.venv.3.9/lib/python3.9/site-packages/grpc/_channel.py", line 1751, in channel_spin
    event = state.channel.next_call_event()

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stack of Thread-7 (140371182995200) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nonroot/ray/python/ray/util/client/logsclient.py", line 67, in _log_main
    for record in log_stream:
  File "/home/nonroot/ray/.venv.3.9/lib/python3.9/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
  File "/home/nonroot/ray/.venv.3.9/lib/python3.9/site-packages/grpc/_channel.py", line 960, in _next
    _common.wait(self._state.condition.wait, _response_ready)
  File "/home/nonroot/ray/.venv.3.9/lib/python3.9/site-packages/grpc/_common.py", line 156, in wait
    _wait_once(wait_fn, MAXIMUM_WAIT_TIMEOUT, spin_cb)
  File "/home/nonroot/ray/.venv.3.9/lib/python3.9/site-packages/grpc/_common.py", line 116, in _wait_once
    wait_fn(timeout=timeout)
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stack of ray_client_streaming_rpc (140371191387904) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nonroot/ray/python/ray/util/client/dataclient.py", line 273, in _data_main
    for response in resp_stream:
  File "/home/nonroot/ray/.venv.3.9/lib/python3.9/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
  File "/home/nonroot/ray/.venv.3.9/lib/python3.9/site-packages/grpc/_channel.py", line 960, in _next
    _common.wait(self._state.condition.wait, _response_ready)
  File "/home/nonroot/ray/.venv.3.9/lib/python3.9/site-packages/grpc/_common.py", line 156, in wait
    _wait_once(wait_fn, MAXIMUM_WAIT_TIMEOUT, spin_cb)
  File "/home/nonroot/ray/.venv.3.9/lib/python3.9/site-packages/grpc/_common.py", line 116, in _wait_once
    wait_fn(timeout=timeout)
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stack of Thread-1 (140371199780608) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/nonroot/.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nonroot/ray/.venv.3.9/lib/python3.9/site-packages/grpc/_channel.py", line 1942, in _poll_connectivity
    event = channel.watch_connectivity_state(

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ Timeout +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― test_decorator_complex[ray_client-dict] ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

start_cluster = (<ray.cluster_utils.Cluster object at 0x7fab743e9c70>, 'ray://localhost:10004'), runtime_env_class = <class 'dict'>

    @pytest.mark.parametrize("runtime_env_class", [dict, RuntimeEnv])
    def test_decorator_complex(start_cluster, runtime_env_class):
        cluster, address = start_cluster
        runtime_env_for_init = runtime_env_class(env_vars={"foo": "job"})
>       ray.init(address, runtime_env=runtime_env_for_init)

python/ray/tests/test_runtime_env.py:234:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
python/ray/_private/client_mode_hook.py:103: in wrapper
    return func(*args, **kwargs)
python/ray/_private/worker.py:1545: in init
    ctx = builder.connect()
python/ray/client_builder.py:175: in connect
    client_info_dict = ray.util.client_connect.connect(
python/ray/util/client_connect.py:55: in connect
    conn = ray.connect(
python/ray/util/client/__init__.py:233: in connect
    conn = self.get_context().connect(*args, **kw_args)
python/ray/util/client/__init__.py:97: in connect
    self.client_worker._server_init(job_config, ray_init_kwargs)
python/ray/util/client/worker.py:852: in _server_init
    response = self.data_client.Init(
python/ray/util/client/dataclient.py:519: in Init
    resp = self._blocking_send(datareq)
python/ray/util/client/dataclient.py:457: in _blocking_send
    self.cv.wait_for(lambda: req_id in self.ready_data or self._in_shutdown)
../.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py:347: in wait_for
    self.wait(waittime)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Condition(<unlocked _thread.lock object at 0x7fab701aa7e0>, 0)>, timeout = None

    def wait(self, timeout=None):
        """Wait until notified or until a timeout occurs.

        If the calling thread has not acquired the lock when this method is
        called, a RuntimeError is raised.

        This method releases the underlying lock, and then blocks until it is
        awakened by a notify() or notify_all() call for the same condition
        variable in another thread, or until the optional timeout occurs. Once
        awakened or timed out, it re-acquires the lock and returns.

        When the timeout argument is present and not None, it should be a
        floating point number specifying a timeout for the operation in seconds
        (or fractions thereof).

        When the underlying lock is an RLock, it is not released using its
        release() method, since this may not actually unlock the lock when it
        was acquired multiple times recursively. Instead, an internal interface
        of the RLock class is used, which really unlocks it even when it has
        been recursively acquired several times. Another internal interface is
        then used to restore the recursion level when the lock is reacquired.

        """
        if not self._is_owned():
            raise RuntimeError("cannot wait on un-acquired lock")
        waiter = _allocate_lock()
        waiter.acquire()
        self._waiters.append(waiter)
        saved_state = self._release_save()
        gotit = False
        try:    # restore state no matter what (e.g., KeyboardInterrupt)
            if timeout is None:
>               waiter.acquire()
E               Failed: Timeout >180.0s

../.local/share/uv/python/cpython-3.9.22-linux-x86_64-gnu/lib/python3.9/threading.py:312: Failed

Log channel is reconnecting. Logs produced while the connection was down can be found on the head node of the cluster in `ray_client_server_[port].out`
2025-06-28 22:09:29,488 WARNING dataclient.py:403 -- Encountered connection issues in the data channel. Attempting to reconnect.
 python/ray/tests/test_runtime_env.py::test_decorator_complex[ray_client-dict] ⨯                                                                                                                                                                                                                                                                                            25% ██▌       WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1751119769.496368   48438 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
I0000 00:00:1751119769.631803   48438 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
I0000 00:00:1751119769.638931   48438 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
worker_path=/home/nonroot/ray/python/ray/_private/workers/default_worker.py, setup_worker_path=/home/nonroot/ray/python/ray/_private/workers/setup_worker.py

I0000 00:00:1751119770.360398   48438 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
I0000 00:00:1751119770.386368   48438 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
I0000 00:00:1751119771.402519   48438 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
2025-06-28 22:09:31,410 INFO client_builder.py:244 -- Passing the following kwargs to ray.init() on the server: log_to_driver


――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― test_decorator_complex[ray_client-RuntimeEnv] ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

start_cluster = (<ray.cluster_utils.Cluster object at 0x7fab701b0220>, 'ray://localhost:10004'), runtime_env_class = <class 'ray.runtime_env.runtime_env.RuntimeEnv'>

    @pytest.mark.parametrize("runtime_env_class", [dict, RuntimeEnv])
    def test_decorator_complex(start_cluster, runtime_env_class):
        cluster, address = start_cluster
        runtime_env_for_init = runtime_env_class(env_vars={"foo": "job"})
>       ray.init(address, runtime_env=runtime_env_for_init)

python/ray/tests/test_runtime_env.py:234:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
python/ray/_private/client_mode_hook.py:103: in wrapper
    return func(*args, **kwargs)
python/ray/_private/worker.py:1545: in init
    ctx = builder.connect()
python/ray/client_builder.py:175: in connect
    client_info_dict = ray.util.client_connect.connect(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

conn_str = 'localhost:10004', secure = False, metadata = None, connection_retries = 3, job_config = <ray.job_config.JobConfig object at 0x7fab702dfe20>, namespace = None

    @Deprecated(
        message="Use ray.init(ray://<head_node_ip_address>:<ray_client_server_port>) "
        "instead. See detailed usage at {}.".format(
            f"https://docs.ray.io/en/{get_ray_doc_version()}/ray-core/package-ref.html#ray-init"  # noqa: E501
        )
    )
    def connect(
        conn_str: str,
        secure: bool = False,
        metadata: List[Tuple[str, str]] = None,
        connection_retries: int = 3,
        job_config: JobConfig = None,
        namespace: str = None,
        *,
        ignore_version: bool = False,
        _credentials: Optional["grpc.ChannelCredentials"] = None,  # noqa: F821
        ray_init_kwargs: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        if ray.is_connected():
            ignore_reinit_error = ray_init_kwargs.get("ignore_reinit_error", False)
            if ignore_reinit_error:
                logger.info(
                    "Calling ray.init() again after it has already been called. "
                    "Reusing the existing Ray client connection."
                )
                return ray.get_context().client_worker.connection_info()
>           raise RuntimeError(
                "Ray Client is already connected. Maybe you called "
                'ray.init("ray://<address>") twice by accident?'
            )
E           RuntimeError: Ray Client is already connected. Maybe you called ray.init("ray://<address>") twice by accident?

python/ray/util/client_connect.py:42: RuntimeError

 python/ray/tests/test_runtime_env.py::test_decorator_complex[ray_client-RuntimeEnv] ⨯                                                                                                                                                                                                                                                                                      50% █████     I0000 00:00:1751119772.687316   48438 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
I0000 00:00:1751119772.818877   48438 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
I0000 00:00:1751119772.826121   48438 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
worker_path=/home/nonroot/ray/python/ray/_private/workers/default_worker.py, setup_worker_path=/home/nonroot/ray/python/ray/_private/workers/setup_worker.py

I0000 00:00:1751119773.546068   48438 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
I0000 00:00:1751119773.553118   48438 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
2025-06-28 22:09:34,671 INFO worker.py:1660 -- Connecting to existing Ray cluster at address: 10.4.0.253:46416...
2025-06-28 22:09:34,677 INFO worker.py:1843 -- Connected to Ray cluster. View the dashboard at 127.0.0.1:8265

 python/ray/tests/test_runtime_env.py::test_decorator_complex[no_ray_client-dict] ✓                                                                                                                                                                                                                                                                                         75% ███████▌  I0000 00:00:1751119779.736698   48438 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
I0000 00:00:1751119779.870254   48438 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
I0000 00:00:1751119779.879059   48438 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
worker_path=/home/nonroot/ray/python/ray/_private/workers/default_worker.py, setup_worker_path=/home/nonroot/ray/python/ray/_private/workers/setup_worker.py

I0000 00:00:1751119780.599238   48438 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
I0000 00:00:1751119780.607999   48438 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
2025-06-28 22:09:41,725 INFO worker.py:1660 -- Connecting to existing Ray cluster at address: 10.4.0.253:48549...
2025-06-28 22:09:41,730 INFO worker.py:1843 -- Connected to Ray cluster. View the dashboard at 127.0.0.1:8265

 python/ray/tests/test_runtime_env.py::test_decorator_complex[no_ray_client-RuntimeEnv] ✓                                                                                                                                                                                                                                                                                  100% ██████████
================================================================================================================================================================================ short test summary info =================================================================================================================================================================================
FAILED python/ray/tests/test_runtime_env.py::test_decorator_complex[ray_client-dict] - Failed: Timeout >180.0s
FAILED python/ray/tests/test_runtime_env.py::test_decorator_complex[ray_client-RuntimeEnv] - RuntimeError: Ray Client is already connected. Maybe you called ray.init("ray://<address>") twice by accident?

Results (198.78s):
       2 passed
       2 failed
         - python/ray/tests/test_runtime_env.py:230 test_decorator_complex[ray_client-dict]
         - python/ray/tests/test_runtime_env.py:230 test_decorator_complex[ray_client-RuntimeEnv]
```
</details>

**Edit**: It seems that `urllib.request` does not support IP-CIDRs in `NO_PROXY`. Maybe we should manually call `monkeypatch.setenv('NO_PROXY', '*')` in the fixture for each `test_runtime_env_*` test case?
