### ISSUE TITLE
Restore issue and Segmentation fault

### ISSUE THREAD

**Issue by aGiant** [ray-project/ray#4481]
### System information
- **Ubuntu 18.04**:
- **Ray installed from pip install -U Ray**:
- **Ray version current released**:
- **Python version 3.7**:
- **agent.restore()**:

### Tested trained model just on one same set but two results:

Trained model:
episode_reward_max: 4953.908495018565
episode_reward_mean: 261.6792498747267
episode_reward_min: -1126.165714394932

Repeat test (restoring saved model) on same set for 1000 times to identify overfitting, but all rewards were  same and the last test was:
---------------------- 993 ------------------------
reward:  -0.10815198149368939
---------------------- 994 ------------------------
reward:  -0.10815198149368939
---------------------- 995 ------------------------
reward:  -0.10815198149368939
---------------------- 996 ------------------------
reward:  -0.10815198149368939
---------------------- 997 ------------------------
reward:  -0.10815198149368939
---------------------- 998 ------------------------
reward:  -0.10815198149368939
---------------------- 999 ------------------------
reward:  -0.10815198149368939
### Source code / logs

```
agent.restore("agents_sc/APEX_DDPG/checkpoint_167/checkpoint-167")
env.reset()
obs = env.reset()
env.max_step = 1000
done = False
action = np.zeros_like(env.action_space.sample())
prev_action = action
info = {}
for i in range(1000):
   action = agent.compute_action(obs)
   obs, reward, done, info = env.step(action)
    prev_reward = reward
    prev_action = action
    print("----------------------", i, "------------------------")
    print("reward: ", reward)
```

Last time I reported some findings about changed output of LSTM model but somehow was ignored. This restoring seemed to be similar as last one. 

By the way, I updated the tensorflow but still got the error of (pid=11611) Fatal Python error: Segmentation fault.

**Comment by ericl** [comment]
Can you provide a reproduction script?

**Comment by aGiant** [comment]
Sorry, the database is local. Above codes were used for restoring saved model
```
       if i % 2 == 0:
           checkpoint = agent.save("agents_sc/APEX_DDPG/")
```

More error came out:
TypeError: _init() got an unexpected keyword argument 'max_weight_sync_delay'

after del config['optimizer']['max_weight_sync_delay']:

TypeError: _init() got an unexpected keyword argument 'num_replay_buffer_shards'

Just calle APEX DQN:
```
config_apex = dqn.apex.APEX_DEFAULT_CONFIG.copy()
config_ddqn = dqn.apex.DQN_CONFIG.copy()
config = merge_dicts(config_apex, config_ddqn)
agent = dqn.apex.DQNAgent(config=config, env="my_env")
```

**Comment by aGiant** [comment]
More errors but for APEX DDGP during training:
```
Traceback (most recent call last):
  File "/home/llu/c7_triangle/train_apex_DDPG.py", line 89, in <module>
    result = agent.train()
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 293, in train
    result = Trainable.train(self)
  File "/home/llu/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 150, in train
    result = self._train()
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/agents/dqn/dqn.py", line 258, in _train
    self.optimizer.step()
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/optimizers/async_replay_optimizer.py", line 118, in step
    sample_timesteps, train_timesteps = self._step()
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/optimizers/async_replay_optimizer.py", line 215, in _step
    samples = ray.get(replay)
  File "/home/llu/.local/lib/python3.6/site-packages/ray/worker.py", line 2288, in get
    raise value
ray.exceptions.UnreconstructableError: Object 01000000ad29d4991a57ee7cf462d1d0cf9e968e is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-03-27 15:48:28,535	ERROR worker.py:1752 -- The task with ID 0000000088e52a17440c1da34f6b173a9e18a4c6 is a driver task and so the object created by ray.put could not be reconstructed.
2019-03-27 15:48:30,523	ERROR worker.py:1689 -- Possible unhandled error from worker: ray_ReplayActor:add_batch() (pid=8205, host=llu-System)
ray.exceptions.UnreconstructableError: Object 01000000d34135e3e17323f8e27e9322b20025e9 is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-03-27 15:48:30,523	ERROR worker.py:1689 -- Possible unhandled error from worker: ray_ReplayActor:add_batch() (pid=8205, host=llu-System)
ray.exceptions.UnreconstructableError: Object 01000000ecd6af32621b5282b5052c2091e9b0aa is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-03-27 15:48:31,523	ERROR worker.py:1689 -- Possible unhandled error from worker: ray_ReplayActor:add_batch() (pid=8205, host=llu-System)
ray.exceptions.UnreconstructableError: Object 01000000402fc3b2b10fdf8366bbf3158a1d8a32 is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-03-27 15:48:31,524	ERROR worker.py:1689 -- Possible unhandled error from worker: ray_ReplayActor:add_batch() (pid=8205, host=llu-System)
ray.exceptions.UnreconstructableError: Object 01000000d08292e841b0a92ebe5a47b0ad0aa91e is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-03-27 15:48:31,524	ERROR worker.py:1689 -- Possible unhandled error from worker: ray_ReplayActor:add_batch() (pid=8205, host=llu-System)
ray.exceptions.UnreconstructableError: Object 01000000a4269690dc0a7691d04610d4823dfab5 is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-03-27 15:48:31,524	ERROR worker.py:1689 -- Possible unhandled error from worker: ray_ReplayActor:add_batch() (pid=8205, host=llu-System)
ray.exceptions.UnreconstructableError: Object 01000000c673d4adf205625aafd5ce2057c6af73 is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-03-27 15:48:31,524	ERROR worker.py:1689 -- Possible unhandled error from worker: ray_ReplayActor:add_batch() (pid=8205, host=llu-System)
ray.exceptions.UnreconstructableError: Object 01000000aa86a6644ffe78a11ba603af2ed62975 is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-03-27 15:48:31,524	ERROR worker.py:1689 -- Possible unhandled error from worker: ray_ReplayActor:add_batch() (pid=8205, host=llu-System)
ray.exceptions.UnreconstructableError: Object 01000000adb2418ed4083690e506c7e34c8d4e96 is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-03-27 15:48:31,524	ERROR worker.py:1689 -- Possible unhandled error from worker: ray_ReplayActor:add_batch() (pid=8205, host=llu-System)
ray.exceptions.UnreconstructableError: Object 0100000050761e5710f98867267ecb547cb8ef2d is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-03-27 15:48:31,524	ERROR worker.py:1689 -- Possible unhandled error from worker: ray_ReplayActor:add_batch() (pid=8205, host=llu-System)
ray.exceptions.UnreconstructableError: Object 01000000fb7e04d6f9407a47cdc89c215d1d68b1 is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-03-27 15:48:31,524	ERROR worker.py:1689 -- Possible unhandled error from worker: ray_ReplayActor:add_batch() (pid=8205, host=llu-System)
ray.exceptions.UnreconstructableError: Object 01000000e9e76deac86ce378b808f5c123f148db is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-03-27 15:48:31,524	ERROR worker.py:1689 -- Possible unhandled error from worker: ray_ReplayActor:add_batch() (pid=8205, host=llu-System)
ray.exceptions.UnreconstructableError: Object 010000006e025cf35ade40be5d86f56643c85a4b is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-03-27 15:48:31,524	ERROR worker.py:1689 -- Possible unhandled error from worker: ray_ReplayActor:add_batch() (pid=8205, host=llu-System)
ray.exceptions.UnreconstructableError: Object 0100000008b6d6257a8509e5e37baad09dbe8e7a is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-03-27 15:48:31,524	ERROR worker.py:1689 -- Possible unhandled error from worker: ray_ReplayActor:add_batch() (pid=8205, host=llu-System)
ray.exceptions.UnreconstructableError: Object 010000008b6d8dfcbf6b6d0f50eed8dc176ff677 is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-03-27 15:48:31,524	ERROR worker.py:1689 -- Possible unhandled error from worker: ray_ReplayActor:add_batch() (pid=8205, host=llu-System)
ray.exceptions.UnreconstructableError: Object 01000000c63a87aa49a206eb0f9163076f91ba7c is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-03-27 15:48:31,524	ERROR worker.py:1689 -- Possible unhandled error from worker: ray_ReplayActor:add_batch() (pid=8205, host=llu-System)
ray.exceptions.UnreconstructableError: Object 0100000092a695d2c4e7f7b641a2de94576997de is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-03-27 15:48:31,524	ERROR worker.py:1689 -- Possible unhandled error from worker: ray_ReplayActor:add_batch() (pid=8205, host=llu-System)
ray.exceptions.UnreconstructableError: Object 0100000035938bb8c1745083d56afcdb86f0a56d is lost (either evicted or explicitly deleted) and cannot be reconstructed.

```

**Comment by ericl** [comment]
Can you provide a reproduction script that uses a standard gym env?

**Comment by aGiant** [comment]
We did not use gym env. All data values are numeric arrays saved in redis database.

**Comment by ericl** [comment]
Ok, but it's not going to be possible to diagnose this without a
reproduction case that doesn't use such a database.

**Comment by snownus** [comment]
@ericl, similar issues when I run some experiments. the log is:
`Possible unhandled error from worker: ^[[36mray_RayModel:restore_from_object()`

**Comment by mimoralea** [comment]
@aGiant did you get to the bottom of this issue? I'm having the same `UnreconstructableError`.

**Comment by richardliaw** [comment]
Can you try making your object store memory significantly larger?

**Comment by mimoralea** [comment]
@richardliaw I "fixed it" by moving to a 2-nights-old nightly.

I have 5 servers and installed rllib on one of them 2 nigths ago, then installed it on the remaining servers last night. These remaining 4 servers were throwing this error. I did a `rsync -av <from working server ray package> <not working server ray package>` and things just work now.

I was able to inspect the diff and the changes were related to the datastore.

That being said, I'll be happy to install the current nightly and give it try. I'm new to ray/rllib, my init is the default `ray.init()`. The servers I can test it on have 128GB or 1T RAM, and both 56 processors. 

What should I replace `ray.init()` with?

**Comment by mimoralea** [comment]
In fact, here is the diff:

```
136a137
>                 is_direct_call=None,
157a159,160
>         if is_direct_call is None:
>             is_direct_call = False
165,166c168,172
<             list_args = ray.signature.flatten_args(self._function_signature,
<                                                    args, kwargs)
---
>             if not args and not kwargs and not self._function_signature:
>                 list_args = []
>             else:
>                 list_args = ray.signature.flatten_args(
>                     self._function_signature, args, kwargs)
175c181
<                     resources)
---
>                     is_direct_call, resources)
Common subdirectories: ./envs/xxx/lib/python3.6/site-packages/ray/rllib and ./envs/xxx/lib/python3.6/site-packages/ray-bk/rllib
Common subdirectories: ./envs/xxx/lib/python3.6/site-packages/ray/scripts and ./envs/xxx/lib/python3.6/site-packages/ray-bk/scripts
diff ./envs/xxx/lib/python3.6/site-packages/ray/serialization.py ./envs/xxx/lib/python3.6/site-packages/ray-bk/serialization.py
160,161c160
<                 if isinstance(obj,
<                               ray.ObjectID) and obj.is_direct_actor_type():
---
>                 if isinstance(obj, ray.ObjectID) and obj.is_direct_call_type():
194,195c193
<                 if isinstance(obj,
<                               ray.ObjectID) and obj.is_direct_actor_type():
---
>                 if isinstance(obj, ray.ObjectID) and obj.is_direct_call_type():
diff ./envs/xxx/lib/python3.6/site-packages/ray/services.py ./envs/xxx/lib/python3.6/site-packages/ray-bk/services.py
155a156
>         "node_manager_port": relevant_client["NodeManagerPort"]
1047a1049
>                  node_manager_port,
1055d1056
<                  node_manager_port=None,
1070a1072,1073
>         node_manager_port(int): The port to use for the node manager. This must
>             not be 0.
1081,1082d1083
<         node_manager_port: The port to use for the node manager. If this is
<             None, then the node manager will choose its own port.
1100a1102,1104
>     # The caller must provide a node manager port so that we can correctly
>     # populate the command to start a worker.
>     assert node_manager_port is not None and node_manager_port != 0
1139a1144
>                             "--node-manager-port={} "
1145,1146c1150,1151
<                                 plasma_store_name, raylet_name, redis_address,
<                                 temp_dir))
---
>                                 node_manager_port, plasma_store_name,
>                                 raylet_name, redis_address, temp_dir))
1154,1157d1158
<     # If the node manager port is None, then use 0 to cause the node manager
<     # to choose its own port.
<     if node_manager_port is None:
<         node_manager_port = 0
diff ./envs/xxx/lib/python3.6/site-packages/ray/signature.py ./envs/xxx/lib/python3.6/site-packages/ray-bk/signature.py
10d9
< import ray
138,143d136
< 
<     for obj in args:
<         if isinstance(obj, ray.ObjectID) and obj.is_direct_actor_type():
<             raise NotImplementedError(
<                 "Objects produced by direct actor calls cannot be "
<                 "passed to other tasks as arguments.")
Common subdirectories: ./envs/xxx/lib/python3.6/site-packages/ray/tests and ./envs/xxx/lib/python3.6/site-packages/ray-bk/tests
Common subdirectories: ./envs/xxx/lib/python3.6/site-packages/ray/tune and ./envs/xxx/lib/python3.6/site-packages/ray-bk/tune
diff ./envs/xxx/lib/python3.6/site-packages/ray/worker.py ./envs/xxx/lib/python3.6/site-packages/ray-bk/worker.py
1217a1218
>         node.node_manager_port,
Common subdirectories: ./envs/xxx/lib/python3.6/site-packages/ray/workers and ./envs/xxx/lib/python3.6/site-packages/ray-bk/workers
```
