### ISSUE TITLE
[Doc] Python 3.12 `docs` env has conflicts with `..scripts/format.sh`

### ISSUE THREAD

**Issue by hongpeng-guo** [ray-project/ray#44903]
### Description

Currently, when building the Ray document (accessible at https://docs.ray.io/en/master/ray-contribute/docs.html), a docs environment is created using `python=3.12`. However, this environment conflicts with the requirements needed to execute `../scripts/format.sh`, a crucial script that must run prior to any document PR submission. Consequently, this issue poses a potential obstacle to updating the documentation. The corresponding error message is detailed below.

A workaround solution is to build the docs environment using `python=3.11`, which works for me.

```
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/docs/bin/flake8", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/anaconda3/envs/docs/lib/python3.12/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/opt/homebrew/anaconda3/envs/docs/lib/python3.12/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/opt/homebrew/anaconda3/envs/docs/lib/python3.12/site-packages/flake8/main/application.py", line 350, in _run
    self.initialize(argv)
  File "/opt/homebrew/anaconda3/envs/docs/lib/python3.12/site-packages/flake8/main/application.py", line 330, in initialize
    self.find_plugins(config_finder)
  File "/opt/homebrew/anaconda3/envs/docs/lib/python3.12/site-packages/flake8/main/application.py", line 153, in find_plugins
    self.check_plugins = plugin_manager.Checkers(local_plugins.extension)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/docs/lib/python3.12/site-packages/flake8/plugins/manager.py", line 356, in __init__
    self.manager = PluginManager(
                   ^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/docs/lib/python3.12/site-packages/flake8/plugins/manager.py", line 238, in __init__
    self._load_entrypoint_plugins()
  File "/opt/homebrew/anaconda3/envs/docs/lib/python3.12/site-packages/flake8/plugins/manager.py", line 254, in _load_entrypoint_plugins
    eps = importlib_metadata.entry_points().get(self.namespace, ())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'
```

**Comment by matthewdeng** [comment]
cc @angelinalg @peytondmurray it looks like we use Python 3.9 in CI, and 3.11 in readthedocs: https://github.com/ray-project/ray/blob/ba340b797d22cac3de6ffacd21446fb4f813eb4e/.readthedocs.yaml#L12

**Comment by peytondmurray** [comment]
While this might work in the short term, having coupled dependencies like this is not a sustainable long term strategy. We should not need to be using the same environment to lint (i.e. call `format.sh`) as for building the docs; they're two separate jobs. This is also one of the main reasons I started pushing for us to use `pre-commit` instead of rolling our own lint system with `format.sh`.

There are legitimate reasons to be using Python 3.12 for building docs, including performance optimizations and better error messaging among other things, and active support for 3.11 has already ended three weeks ago. IMO the real issue at hand is moving away from `format.sh` though I know that will involve some work, (but a relatively small amount, I feel).
