### ISSUE TITLE
[Core] `py-spy` profiling initiated from the Ray Dashboard fails if `sudo` is not installed

### ISSUE THREAD

**Issue by JoshKarpel** [ray-project/ray#44904]
### What happened + What you expected to happen

If `sudo` is not installed, and you try to generate a flamegraph via the dashboard, you get this error message:
```
{
  "result": false,
  "msg": "Traceback (most recent call last):\n  File \"/app/virtualenv/lib/python3.10/site-packages/ray/dashboard/optional_utils.py\", line 94, in _handler_route\n    return await handler(bind_info.instance, req)\n  File \"/app/virtualenv/lib/python3.10/site-packages/ray/dashboard/modules/reporter/reporter_head.py\", line 456, in cpu_profile\n    reply = await reporter_stub.CpuProfiling(\n  File \"/app/virtualenv/lib/python3.10/site-packages/grpc/aio/_call.py\", line 318, in __await__\n    raise _create_rpc_error(\ngrpc.aio._call.AioRpcError: \u003CAioRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNKNOWN\n\tdetails = \"Unexpected \u003Cclass 'FileNotFoundError'\u003E: [Errno 2] No such file or directory: 'sudo'\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"Unexpected \u003Cclass \\'FileNotFoundError\\'\u003E: [Errno 2] No such file or directory: \\'sudo\\'\", grpc_status:2, created_time:\"2024-04-22T17:03:52.055815957+00:00\"}\"\n\u003E\n",
  "data": {

  }
} 
```

I've traced this back to https://github.com/ray-project/ray/blob/43a37c67abacaaf403f2176e5f1655ff472399a8/dashboard/modules/reporter/profile_manager.py#L61-L72 , which doesn't handle the case where the `sudo` executable doesn't exist.

Here's what it looks like without the RPC wrapper:
```
$ python -m asyncio
>>> import asyncio
>>> import subprocess
>>> await asyncio.create_subprocess_exec("sudo", "-n", "true", stdout=subprocess.PIPE, stderr=subprocess.PIPE)
Traceback (most recent call last):
  File "/opt/ml/python_3.10.6/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/opt/ml/python_3.10.6/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File "/opt/ml/python_3.10.6/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/opt/ml/python_3.10.6/lib/python3.10/asyncio/base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/opt/ml/python_3.10.6/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/opt/ml/python_3.10.6/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/opt/ml/python_3.10.6/lib/python3.10/asyncio/unix_events.py", line 799, in _start
    self._proc = subprocess.Popen(
  File "/opt/ml/python_3.10.6/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/ml/python_3.10.6/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sudo'
```

Given the comment indicating that this function is establishing if we *can* use `sudo`, it seems that it would be safe to have this function catch the `FileNotFoundError` and return `False`.

I'd be happy to make this change.

### Versions / Dependencies

Ray 2.9.3
Python 3.10

### Reproduction script

See above

### Issue Severity

Low: It annoys or frustrates me.

**Comment by brycehuang30** [comment]
The issue is fixed in this [PR](https://github.com/ray-project/ray/pull/43857)

**Comment by JoshKarpel** [comment]
Hah, my bad! Should have checked to see if there was already a PR for this. Is that PR ready to merge? If so I can close mine and this issue.

**Comment by brycehuang30** [comment]
No worries! Thanks for discovering issue and posting fix. I think that PR is ready for merge :)
