### ISSUE TITLE
[rllib] Bug report: examples codes (multiagent_cartpole.py) incompatible with ray-0.6.5

### ISSUE THREAD

**Issue by PengZhenghao** [ray-project/ray#4525]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Mojave 10.14.1
- **Ray installed from (source or binary)**: 
- **Ray version**:
- **Python version**: 3.6
- **Exact command to reproduce**:

### Source code / logs

I find that using the stable version of Ray 0.6.5, which installed by pip install, error happen when run the `multiagent_cartpole.py`. When I install the latest version of Ray, namely the ray-0.7.0.dev2, by using the `pip install [wheel link]`, everything work well!

I notice that your guys updated the RLlib and made some changes recently. I think probably some incompatible codes are in them.

Here's the error message:

```
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/8 CPUs, 0/0 GPUs
Memory usage on this node: 9.6/17.2 GB

2019-03-31 16:51:54,691	WARNING worker.py:330 -- WARNING: Falling back to serializing objects of type <class 'numpy.dtype'> by using pickle. This may be inefficient.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 3/8 CPUs, 0/0 GPUs
Memory usage on this node: 9.7/17.2 GB
Result logdir: /Users/pengzhenghao/ray_results/PPO
Number of trials: 1 ({'RUNNING': 1})
RUNNING trials:
 - PPO_multi_cartpole_0:	RUNNING

2019-03-31 16:52:06,455	ERROR trial_runner.py:460 -- Error processing event.
**Traceback (most recent call last):
  File "/Users/pengzhenghao/anaconda3/envs/dev/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 409, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/Users/pengzhenghao/anaconda3/envs/dev/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 314, in fetch_result
    result = ray.get(trial_future[0])
  File "/Users/pengzhenghao/anaconda3/envs/dev/lib/python3.6/site-packages/ray/worker.py", line 2316, in get
    raise value
ray.exceptions.RayTaskError: ray_PPOAgent:train() (pid=32493, host=PengZhenghao)
  File "/Users/pengzhenghao/anaconda3/envs/dev/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 276, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/Users/pengzhenghao/anaconda3/envs/dev/lib/python3.6/site-packages/ray/tune/trainable.py", line 88, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/Users/pengzhenghao/anaconda3/envs/dev/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 373, in _setup
    self._init()
  File "/Users/pengzhenghao/anaconda3/envs/dev/lib/python3.6/site-packages/ray/rllib/agents/ppo/ppo.py", line 77, in _init
    self.env_creator, self._policy_graph)
  File "/Users/pengzhenghao/anaconda3/envs/dev/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 506, in make_local_evaluator
    extra_config or {}))
  File "/Users/pengzhenghao/anaconda3/envs/dev/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 714, in _make_evaluator
    async_remote_worker_envs=config["async_remote_worker_envs"])
  File "/Users/pengzhenghao/anaconda3/envs/dev/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 270, in __init__
    policy_dict = _validate_and_canonicalize(policy_graph, self.env)
  File "/Users/pengzhenghao/anaconda3/envs/dev/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 679, in _validate_and_canonicalize
    if not issubclass(v[0], PolicyGraph):
TypeError: issubclass() arg 1 must be a class**

2019-03-31 16:52:06,458	INFO ray_trial_executor.py:178 -- Destroying actor for trial PPO_multi_cartpole_0. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/8 CPUs, 0/0 GPUs
Memory usage on this node: 10.1/17.2 GB
Result logdir: /Users/pengzhenghao/ray_results/PPO
Number of trials: 1 ({'ERROR': 1})
ERROR trials:
 - PPO_multi_cartpole_0:	ERROR, 1 failures: /Users/pengzhenghao/ray_results/PPO/PPO_multi_cartpole_0_2019-03-31_16-51-546mhp003l/error_2019-03-31_16-52-06.txt

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/8 CPUs, 0/0 GPUs
Memory usage on this node: 10.1/17.2 GB
Result logdir: /Users/pengzhenghao/ray_results/PPO
Number of trials: 1 ({'ERROR': 1})
ERROR trials:
 - PPO_multi_cartpole_0:	ERROR, 1 failures: /Users/pengzhenghao/ray_results/PPO/PPO_multi_cartpole_0_2019-03-31_16-51-546mhp003l/error_2019-03-31_16-52-06.txt

**Traceback (most recent call last):
  File "/Users/pengzhenghao/Desktop/ray/python/ray/rllib/examples/multiagent_cartpole.py", line 113, in <module>
    lambda agent_id: random.choice(policy_ids)),
  File "/Users/pengzhenghao/anaconda3/envs/dev/lib/python3.6/site-packages/ray/tune/tune.py", line 253, in run
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_multi_cartpole_0])**
(pid=32493) 2019-03-31 16:52:06,429	INFO ppo.py:167 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
(pid=32493) 2019-03-31 16:52:06,429	WARNING ppo.py:172 -- FYI: By default, the value function will not share layers with the policy model ('vf_share_layers': False).

Process finished with exit code 1
```

**Comment by ericl** [comment]
Hey @PengZhenghao , I think this is expected since the examples point to the master branch. If you switch to the previous example versions, it will work for 0.6.5.

**Comment by PengZhenghao** [comment]
Thanks for replying, then let's close this issue and leave information for those who search related error.

> Hey @PengZhenghao , I think this is expected since the examples point to the master branch. If you switch to the previous example versions, it will work for 0.6.5.
