### ISSUE TITLE
Instructions in installation.rst to build ray from source do not work

### ISSUE THREAD

**Issue by FedericoFontana** [ray-project/ray#4550]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: source
- **Ray version**: master branch
- **Python version**: 3.6.7
- **Exact command to reproduce**: As indicated in [installation.rst](https://github.com/ray-project/ray/blob/master/doc/source/installation.rst):
```
sudo apt-get update
sudo apt-get install -y build-essential curl unzip psmisc python
pip install cython==0.29.0
git clone https://github.com/ray-project/ray.git
ray/ci/travis/install-bazel.sh
cd ray/python
# The following command is the once which fails.
pip install -e . --verbose  # Add --user if you see a permission denied error.

# ERROR:
subprocess.CalledProcessError: Command '['../build.sh', '-p', '/home/federico/Desktop/ray/.venv/bin/python3']' returned non-zero exit status 127.

# I've also tried with the following, but I still get the same error:
pip install git+https://github.com/ray-project/ray.git#subdirectory=python
```

### Describe the problem
I know how to fix issue #4440  and I would like to send my first pull request as a way to say thank you to the authors and maintainers of `ray`. In my mind, steps would be:
1. Follow steps above in installation.rst
2. Run tests using the latest code in the master branch.
3. Fix bug #4440.
4. Send pull request.

However, I'm stuck at step 1. due to the error above. Note this probably related TODO in [setup.py](https://github.com/ray-project/ray/blob/master/python/setup.py#L69).

### Source code / logs
Both the following commands
```
$ pip install -e . --verbose
$ pip install git+https://github.com/ray-project/ray.git#subdirectory=python
```
return the same error

```
    [Federico]: omitting previous logs, no errors or warnings to report.
    Target directory /tmp/pip-req-build-53xlelru/python/ray/pyarrow_files/pyarrow already exists. Specify --upgrade to force replacement.
    Target directory /tmp/pip-req-build-53xlelru/python/ray/pyarrow_files/numpy-1.16.2.dist-info already exists. Specify --upgrade to force replacement.
    Target directory /tmp/pip-req-build-53xlelru/python/ray/pyarrow_files/six-1.12.0.dist-info already exists. Specify --upgrade to force replacement.
    Target directory /tmp/pip-req-build-53xlelru/python/ray/pyarrow_files/six.py already exists. Specify --upgrade to force replacement.
    Target directory /tmp/pip-req-build-53xlelru/python/ray/pyarrow_files/__pycache__ already exists. Specify --upgrade to force replacement.
    Target directory /tmp/pip-req-build-53xlelru/python/ray/pyarrow_files/pyarrow-0.12.0.RAY.dist-info already exists. Specify --upgrade to force replacement.
    Target directory /tmp/pip-req-build-53xlelru/python/ray/pyarrow_files/numpy already exists. Specify --upgrade to force replacement.
    Target directory /tmp/pip-req-build-53xlelru/python/ray/pyarrow_files/bin already exists. Specify --upgrade to force replacement.
    + export PYTHON_BIN_PATH=/home/federico/Desktop/ray/.venv/bin/python3
    + PYTHON_BIN_PATH=/home/federico/Desktop/ray/.venv/bin/python3
    + '[' NO == YES ']'
    + '[' YES == YES ']'
    + bazel build //:ray_pkg --verbose_failures
    ../build.sh: line 109: bazel: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-53xlelru/python/setup.py", line 183, in <module>
        license="Apache 2.0")
      File "/home/federico/Desktop/ray/.venv/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/federico/Desktop/ray/.venv/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-53xlelru/python/setup.py", line 74, in run
        subprocess.check_call(command)
      File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '-p', '/home/federico/Desktop/ray/.venv/bin/python3']' returned non-zero exit status 127.
    
    ----------------------------------------
Command "/home/federico/Desktop/ray/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-53xlelru/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-mfatupdw/install-record.txt --single-version-externally-managed --compile --install-headers /home/federico/Desktop/ray/.venv/include/site/python3.6/ray" failed with error code 1 in /tmp/pip-req-build-53xlelru/python

```

**Comment by ericl** [comment]
Hm, I'm not sure why venv is crashing, but for RLlib changes you fortunately don't have to build all of RLlib: this script lets you just symlink the code to a pip installed ray:

https://ray.readthedocs.io/en/latest/rllib-dev.html#development-install

**Comment by ericl** [comment]
`    ../build.sh: line 109: bazel: command not found`

Ah seems like it requires http://bazel.io/ to be installed.

**Comment by pcmoritz** [comment]
I think the problem here is that after `ray/ci/travis/install-bazel.sh` run sucessfully, you need to make sure the binary landed in a place that is in the path and log out of the shell to refresh the environment variables
