### ISSUE TITLE
[Dashboard] Ray crashes when querying jobs 

### ISSUE THREAD

**Issue by AlexCuadron** [ray-project/ray#45583]
### What happened + What you expected to happen

2024-05-28 06:40:46,677 INFO api.py:67 -- (3.0 / 24 seconds) Waiting for the response from the API server address 
2024-05-28 06:40:49,670 INFO api.py:67 -- (6.0 / 24 seconds) Waiting for the response from the API server address 
Usage: ray list [OPTIONS] {actors|jobs|placement-
                groups|nodes|workers|tasks|objects|runtime-envs|cluster-
                events}
Try 'ray list --help' for help.

```
Error: API server internal error. See dashboard.log file for more details. Error: Traceback (most recent call last):
  File "/home/alex/miniconda3/envs/x/lib/python3.10/site-packages/ray/dashboard/optional_utils.py", line 94, in _handler_route
    return await handler(bind_info.instance, req)
  File "/home/alex/miniconda3/envs/x/lib/python3.10/site-packages/ray/dashboard/modules/state/state_head.py", line 115, in async_wrapper
    ret = await func(self, *args, **kwargs)
  File "/home/alex/miniconda3/envs/x/lib/python3.10/site-packages/ray/dashboard/modules/state/state_head.py", line 297, in list_jobs
    result = await self._state_api.list_jobs(option=self._options_from_req(req))
  File "/home/alex/miniconda3/envs/x/lib/python3.10/site-packages/ray/dashboard/state_aggregator.py", line 387, in list_jobs
    result = await self._client.get_job_info(timeout=option.timeout)
  File "/home/alex/miniconda3/envs/x/lib/python3.10/site-packages/ray/util/state/state_manager.py", line 363, in get_job_info
    submission_jobs = [
  File "/home/alex/miniconda3/envs/x/lib/python3.10/site-packages/ray/util/state/state_manager.py", line 365, in <listcomp>
    **dataclasses.asdict(job),
  File "/home/alex/miniconda3/envs/x/lib/python3.10/dataclasses.py", line 1237, in asdict
    raise TypeError("asdict() should be called on dataclass instances")
TypeError: asdict() should be called on dataclass instances
```

### Versions / Dependencies

       _,met$$$$$gg.          alex@storage-v0
    ,g$$$$$$$$$$$$$$$P.       ------------------------------------ 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 12 (bookworm) x86_64 
 ,$$P'              `$$$.     Host: Google Compute Engine 
',$$P       ,ggs.     `$$b:   Kernel: 6.1.0-21-cloud-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 1 day, 1 hour, 32 mins 
 $$P      d$'     ,    $$P    Packages: 484 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.2.15 
 $$;      Y$b._   _,d$P'      Terminal: /dev/pts/0 
 Y$$.    `.`"Y$$$$P"'         CPU: Intel Xeon (2) @ 2.200GHz 
 `$$b      "-.__              Memory: 1501MiB / 3928MiB 
  `Y$$
   `Y$$.                                              
     `$$b.                                            
       `Y$$b.
          `"Y$b._
              `"""

### Reproduction script

ray list jobs --limit 1000 | grep whatever (I have 800 jobs on ray atm)

### Issue Severity

Low: It annoys or frustrates me.

**Comment by brycehuang30** [comment]
To clarify a bit, it seems that ray list jobs is crashing. Which Ray version and Python version are you using?
