### ISSUE TITLE
[Data] Decimal types cannot be read back properly

### ISSUE THREAD

**Issue by vladosby** [ray-project/ray#45801]
### What happened + What you expected to happen

I have code that reads parquet data using ray data, then split data by some rules and write it back using ray data.

Please see the code of writing data:
```
import ray
import s3fs


@ray.remote
def splitter_step():
    fs = s3fs.S3FileSystem(
        key='key',
        secret='secret',
        client_kwargs={"endpoint_url": 'url'}
    )

    bucket = 'bucket'
    dataset = ray.data.read_parquet(filesystem=fs, paths=[f'{bucket}/path'])
    splitter = Splitter(config)

    X_train, X_val, X_test, y_train, y_val, y_test = splitter.split_data(dataset.to_pandas())

    ray.data.from_pandas(X_train).write_parquet(filesystem=fs, path=f'{bucket}/X_train/')
    ray.data.from_pandas(X_val).write_parquet(filesystem=fs, path=f'{bucket}/X_val/')
    ray.data.from_pandas(X_test).write_parquet(filesystem=fs, path=f'{bucket}/X_test/')
    ray.data.from_pandas(y_train.to_frame()).write_parquet(filesystem=fs, path=f'{bucket}/y_train/')
    ray.data.from_pandas(y_val.to_frame()).write_parquet(filesystem=fs, path=f'{bucket}/y_val/')
    ray.data.from_pandas(y_test.to_frame()).write_parquet(filesystem=fs, path=f'{bucket}/y_test/')

    return "done"

print(ray.get(splitter_step.remote()))
```

Then I have next step, that read this data:
```
import ray
import s3fs

ray.init()

@ray.remote
def read_data():
    fs = s3fs.S3FileSystem(
        key='key',
        secret='secret',
        client_kwargs={'endpoint_url': 'url'}
    )

    bucket = 'bucket'
    print('schema')
    print(ray.data.read_parquet(filesystem=fs, paths=[f'{bucket}/X_train/']).schema)
    print('schema')
    X_train = ray.data.read_parquet(filesystem=fs, paths=[f'{bucket}/X_train/']).to_pandas()

    return 'done'

print(ray.get(read_data.remote()))
```

And this read code fails already on reading schema with following errors:
```
[2m[36m(pid=1905766) [0mParquet Files Sample 0:  50%  | 1/2 [00:01<00:01,  1.27s/it]Traceback (most recent call last):
  File "/tmp/ray/session_2024-06-03_01-01-09_618274_8/runtime_resources/working_dir_files/_ray_pkg_90d2c8b35af7beb0/03_xgboots_tune.py", line 281, in <module>
    print(ray.get(bayesian_optimisation_step.remote()))
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ArrowInvalid): [36mray::bayesian_optimisation_step()[39m (pid=1905766)
  File "/tmp/ray/session_2024-06-03_01-01-09_618274_8/runtime_resources/working_dir_files/_ray_pkg_90d2c8b35af7beb0/03_xgboots_tune.py", line 227, in bayesian_optimisation_step
    print(ray.data.read_parquet(filesystem=fs, paths=[f'{input_path}/X_train/']).schema)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/read_api.py", line 695, in read_parquet
    datasource = ParquetDatasource(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/datasource/parquet_datasource.py", line 296, in __init__
    self._encoding_ratio = self._estimate_files_encoding_ratio()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/datasource/parquet_datasource.py", line 447, in _estimate_files_encoding_ratio
    sample_ratios = sample_bar.fetch_until_complete(futures)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/progress_bar.py", line 93, in fetch_until_complete
    for ref, result in zip(done, ray.get(done)):
ray.exceptions.RayTaskError(ArrowInvalid): [36mray::_sample_fragment()[39m (pid=1905896)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/datasource/parquet_datasource.py", line 569, in _sample_fragment
    batch = next(batches)
  File "pyarrow/_dataset.pyx", line 3769, in _iterator
  File "pyarrow/_dataset.pyx", line 3387, in pyarrow._dataset.TaggedRecordBatchIterator.__next__
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Decimal value does not fit in precision 6
```

Expected result that data written by ray, can be read by ray.

### Versions / Dependencies

python==3.9.18
ray[all]==2.9.0
s3fs==2024.6.0
scikit-learn==1.2.2
pyarrow==16.1.0
pandas==2.1.4

### Reproduction script

Please see in the description

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by scottjlee** [comment]
Hi @vladosby, is there any reason you are not using the Ray Data native `read_parquet()` method for reading back the files?

By the way, you shouldn't need to use `splitter_step` and `read_data ` as remote and run with `ray.get()`, you can simply call the functions. You can find an end to end example in [our docs](https://docs.ray.io/en/latest/data/batch_inference.html) for best practices on how to use Ray Data.

**Comment by vladosby** [comment]
Hi @scottjlee,
As you can see I use `read_parquet()` method, please look for a code like this: `ray.data.read_parquet(filesystem=fs, paths=[f'{bucket}/X_train/'])`.

As I got the main issue is with Decimal type and how PyArrow works with it. I solved it using some workaround:

```
def cast_decimal_columns_to_float(df: pd.DataFrame) -> pd.DataFrame:
    for column in df.columns:
        if type(df[column].iloc[0]) is Decimal:
            df[column] = df[column].astype(float)
    return df
    
dataset = ray.data.read_parquet(filesystem=fs, paths=[input_path]).map_batches(cast_decimal_columns_to_float,
                                                                                                batch_format="pandas")
```

What I do not understand is that I can work with data, write to file storage, but I cannot read it back. For read and write I was using Ray Data.

**Comment by scottjlee** [comment]
Thanks, sorry I missed that code earlier, I see it now.
I noticed you are on a pretty old version of Ray, could you try upgrading to latest version, and see if the error still persists? We had some major updates regarding internal block types, which may resolve the issue.

**Comment by vladosby** [comment]
I cannot read full amount of data locally to check, on cluster I have outdated version 2.9.0 and if my DevOps team will update cluster, I will recheck and reply.

**Comment by vladosby** [comment]
With ray 2.32 and python 11 it fails with following error:
```
[36mray::splitter_step2()[39m (pid=2227, ip=10.165.153.34)
File "/tmp/ray/session_2024-07-19_00-53-35_333408_8/runtime_resources/working_dir_files/_ray_pkg_e78e71a933cd42a3/01_split_data.py", line 102, in splitter_step2
 train_ds.write_parquet(filesystem=fs, path=f'{output_path}/train/')
File "/home/ray/anaconda3/lib/python3.11/site-packages/ray/data/dataset.py", line 2717, in write_parquet
 self.write_datasink(
File "/home/ray/anaconda3/lib/python3.11/site-packages/ray/data/dataset.py", line 3541, in write_datasink
 self._write_ds = Dataset(plan, logical_plan).materialize()
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ray/anaconda3/lib/python3.11/site-packages/ray/data/dataset.py", line 4499, in materialize
 copy._plan.execute()
File "/home/ray/anaconda3/lib/python3.11/site-packages/ray/data/exceptions.py", line 86, in handle_trace
 raise e.with_traceback(None) from SystemException()
ray.exceptions.RayTaskError(ValueError): [36mray::MapBatches(partial)->Write()[39m (pid=2575, ip=10.165.153.34)
 for b_out in map_transformer.apply_transform(iter(blocks), ctx):
File "/home/ray/anaconda3/lib/python3.11/site-packages/ray/data/_internal/execution/operators/map_transformer.py", line 253, in __call__
 yield from self._block_fn(input, ctx)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ray/anaconda3/lib/python3.11/site-packages/ray/data/_internal/planner/plan_write_op.py", line 26, in fn
 write_result = datasink_or_legacy_datasource.write(blocks, ctx)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ray/anaconda3/lib/python3.11/site-packages/ray/data/_internal/datasource/parquet_datasink.py", line 78, in write
 call_with_retry(
File "/home/ray/anaconda3/lib/python3.11/site-packages/ray/data/_internal/util.py", line 986, in call_with_retry
 raise e from None
File "/home/ray/anaconda3/lib/python3.11/site-packages/ray/data/_internal/util.py", line 973, in call_with_retry
 return f()
 ^^^
File "/home/ray/anaconda3/lib/python3.11/site-packages/ray/data/_internal/datasource/parquet_datasink.py", line 75, in write_blocks_to_path
 writer.write_table(table)
File "/tmp/ray/session_2024-07-19_00-53-35_333408_8/runtime_resources/pip/67ed3896d6e32145926ae83a34249f338249df34/virtualenv/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 1094, in write_table
 raise ValueError(msg)
ValueError: Table schema does not match schema used to create file:
```

**Comment by scottjlee** [comment]
Got it, what is the schema of the underlying files being read into Ray Data? 

It looks like the error is coming from Arrow side, related to metadata. Likely we have some Ray Data internal code which needs to correctly update this metdata https://github.com/apache/arrow/issues/2805

**Comment by vladosby** [comment]
This is schema:
`
 Schema <bound method Dataset.schema of Dataset(
    num_rows=9300000,
    schema={
       a: string,
       aa: date32[day],
       aaa: int64,
       aaaa: int64,
       aaaaa: int64,
       aaaaaa: int64,
       q: decimal128(18, 4),
       qq: decimal128(18, 4),
       qqq: int64,
       qqqq: int64,
       qqqqq: int64,
       qqqqqq: int64,
       qqqqqqq: int64,
       qqqqqqqq: int64,
       qqqqqqqqq: int64,
       w1: int64,
       w2: int64,
       w3: int64,
       w4: int64,
       w5: int64,
       w6: int64,
       w7: int64,
       w8: int64,
       w9: int64,
       w10: int64,
       w11: int64,
       w12: int64,
       w13: int64,
       w14: int64,
       w15: int64,
       w16: int64,
       w17: int64,
       w18: int64,
       w19: int64,
       w20: int64,
       w21: int64,
       w22: int64,
       w23: int64,
       w24: int64,
       w25: int64,
       w26: int64,
       w27: int64,
       w28: int64,
       w29: int64,
       c: double,
       qw: double,
       w: double,
       ww: int64,
       wwwww: double,
       www: int64,
       wwwwww: int64,
       v11: int64,
       v2: int64,
       v3: int64,
       v4: int64,
       v5: int64,
       v6: int64,
       v7: int64,
       v8: int64,
       v9: int64,
       v10: int64,
       v11: int64,
       v12: int64,
       v13: int64,
       v14: int64,
       v15: int64,
       v16: int64,
       v17: int64,
       v18: int64,
       v19: int64,
       v20: int64,
       v21: int64,
       v22: int64,
       v23: int64,
       v24: int64,
       v25: int64,
       v26: int64,
       v27: int64,
       v28: int64,
       v29: int64,
       v: double,
       vv: double,
       vvv: double,
       vvvv: int64,
       vvvvv: double,
       vvvvvv: int64,
       vvvvvvv: int64,
       g1: int64,
       g2: int64,
       g3: int64,
       g4: int64,
       g5: int64,
       g6: int64,
       g7: int64,
       g8: int64,
       g9: int64,
       g10: int64,
       g11: int64,
       g12: int64,
       g13: int64,
       g14: int64,
       g15: int64,
       g16: int64,
       g17: int64,
       g18: int64,
       g19: int64,
       g20: int64,
       g21: int64,
       g22: int64,
       g23: int64,
       g24: int64,
       g25: int64,
       g26: int64,
       g27: int64,
       g28: int64,
       g29: int64,
       g: double,
       gg: double,
       ggg: double,
       gggg: int64,
       ggggg: double,
       gggggg: int64,
       ggggggg: int64,
       gggg1: decimal128(18, 4),
       gggg2: decimal128(18, 4),
       gggg3: decimal128(18, 4),
       gggg4: decimal128(18, 4),
       gggg5: decimal128(18, 4),
       gggg6: decimal128(18, 4),
       gggg7: decimal128(18, 4),
       gggg8: decimal128(18, 4),
       gggg9: decimal128(18, 4),
       gggg10: decimal128(18, 4),
       gggg11: decimal128(18, 4),
       gggg12: decimal128(18, 4),
       gggg13: decimal128(18, 4),
       gggg14: decimal128(18, 4),
       gggg15: decimal128(18, 4),
       gggg16: decimal128(18, 4),
       gggg17: decimal128(18, 4),
       gggg18: decimal128(18, 4),
       gggg19: decimal128(18, 4),
       gggg20: decimal128(18, 4),
       gggg21: decimal128(18, 4),
       gggg22: decimal128(18, 4),
       gggg23: decimal128(18, 4),
       gggg24: decimal128(18, 4),
       gggg25: decimal128(18, 4),
       gggg26: decimal128(18, 4),
       gggg27: decimal128(18, 4),
       gggg28: decimal128(18, 4),
       gggg29: decimal128(18, 4),
       bg: decimal128(22, 8),
       bbbggg: double,
       bbgg: double,
       aaaqqq: decimal128(28, 4),
       ffr: double,
       rrff: decimal128(18, 4),
       gt: decimal128(18, 4),
       lt_gggg1: decimal128(18, 4),
       lt_gggg2: decimal128(18, 4),
       lt_gggg3: decimal128(18, 4),
       lt_gggg4: decimal128(18, 4),
       lt_gggg5: decimal128(18, 4),
       lt_gggg6: decimal128(18, 4),
       lt_gggg7: decimal128(18, 4),
       lt_gggg8: decimal128(18, 4),
       lt_gggg9: decimal128(18, 4),
       lt_gggg10: decimal128(18, 4),
       lt_gggg11: decimal128(18, 4),
       lt_gggg12: decimal128(18, 4),
       lt_gggg13: decimal128(18, 4),
       lt_gggg14: decimal128(18, 4),
       lt_gggg15: decimal128(18, 4),
       lt_gggg16: decimal128(18, 4),
       lt_gggg17: decimal128(18, 4),
       lt_gggg18: decimal128(18, 4),
       lt_gggg19: decimal128(18, 4),
       lt_gggg20: decimal128(18, 4),
       lt_gggg21: decimal128(18, 4),
       lt_gggg22: decimal128(18, 4),
       lt_gggg23: decimal128(18, 4),
       lt_gggg24: decimal128(18, 4),
       lt_gggg25: decimal128(18, 4),
       lt_gggg26: decimal128(18, 4),
       lt_gggg27: decimal128(18, 4),
       lt_gggg28: decimal128(18, 4),
       lt_gggg29: decimal128(18, 4),
       z: decimal128(22, 8),
       zz: double,
       zzz: double,
       zzzz: decimal128(28, 4),
       zzzzzz: double,
       zzzzzzz: decimal128(18, 4),
       zzzzzzzz: decimal128(18, 4),
       z1: int64,
       z2: int64,
       z3: int64,
       z4: int64,
       z5: int64,
       z6: int64,
       z7: int64,
       z8: int64,
       z9: int64,
       z10: int64,
       z11: int64,
       z12: int64,
       z13: int64,
       z14: int64,
       z15: int64,
       z16: int64,
       z17: int64,
       z18: int64,
       z19: int64,
       z20: int64,
       z21: int64,
       z22: int64,
       z23: int64,
       z24: int64,
       z25: int64,
       z26: int64,
       z27: int64,
       z28: int64,
       z29: int64,
       e: double,
       ee: double,
       eee: double,
       eeee: int64,
       eeeee: double,
       eeeeee: int64,
       eeeeeee: int64,
       e1: int64,
       e2: int64,
       e3: int64,
       e4: int64,
       e5: int64,
       e6: int64,
       e7: int64,
       e8: int64,
       e9: int64,
       e10: int64,
       e11: int64,
       e12: int64,
       e13: int64,
       e14: int64,
       e15: int64,
       e16: int64,
       e17: int64,
       e18: int64,
       e19: int64,
       e20: int64,
       e21: int64,
       e22: int64,
       e23: int64,
       e24: int64,
       e25: int64,
       e26: int64,
       e27: int64,
       e28: int64,
       e29: int64,
       t: double,
       tt: double,
       ttt: double,
       tttt: int64,
       ttttt: double,
       tttttt: int64,
       ttttttt: int64,
       t1: int64,
       t2: int64,
       t3: int64,
       t4: int64,
       t5: int64,
       t6: int64,
       t7: int64,
       t8: int64,
       t9: int64,
       t10: int64,
       t11: int64,
       t12: int64,
       t13: int64,
       t14: int64,
       t15: int64,
       t16: int64,
       t17: int64,
       t18: int64,
       t19: int64,
       t20: int64,
       t21: int64,
       t22: int64,
       t23: int64,
       t24: int64,
       t25: int64,
       t26: int64,
       t27: int64,
       t28: int64,
       t29: int64,
       t30: double,
       t31: double,
       t32: double,
       t33: int64,
       t34: double,
       t34: int64,
       t36: int64,
       v1: int64,
       v2: int64,
       v3: int64,
       v4: int64,
       v5: int64,
       v6: int64,
       v7: int64,
       v8: int64,
       v9: int64,
       v10: int64,
       v11: int64,
       v12: int64,
       v13: int64,
       v14: int64,
       v15: int64,
       v16: int64,
       v17: int64,
       v18: int64,
       v19: int64,
       v20: int64,
       v21: int64,
       v22: int64,
       v23: int64,
       v24: int64,
       v25: int64,
       v26: int64,
       v27: int64,
       v28: int64,
       v29: int64,
       v30: double,
       v31: double,
       v32: double,
       v33: int64,
       v34: double,
       v35: int64,
       v36: int64,
       x: int64,
       xx: int64,
       xxx: int64,
       xxxx: int64,
       xxxxx: int64,
       xxxxxx: int64,
       xxxxxxx: int64,
       xxxxxxxx: int64,
       xxxxxxxxx: int64,
       x0: int64,
       x1: int64,
       x2: int64,
       x3: int64,
       x4: int64,
       x5: int64,
       x6: int64,
       x7: int64,
       x8: int64,
       x9: int64,
       x10: int64,
       x11: int64,
       x12: int64,
       x13: int64,
       x14: int64,
       x15: int64,
       x16: int64,
       x17: int64,
       x18: int64,
       x19: int64,
       x120: double,
       x121: double,
       x122: double,
       x113: int64,
       x124: double,
       x154: int64,
       x156: int64,
       p1: int64,
       p2: int64,
       p3: int64,
       p4: int64,
       p5: int64,
       p6: int64,
       p7: int64,
       p8: int64,
       p9: int64,
       p10: int64,
       p11: int64,
       p12: int64,
       p13: int64,
       p14: int64,
       p15: int64,
       p16: int64,
       p17: int64,
       p18: int64,
       p19: int64,
       p20: int64,
       p21: int64,
       p22: int64,
       p23: int64,
       p24: int64,
       p25: int64,
       p26: int64,
       p27: int64,
       p28: int64,
       p29: int64,
       p: double,
       ppp: double,
       ppppp: double,
       pppppp: int64,
       pppppppp: double,
       pp: int64,
       pppppppppp: int64,
       o1: int64,
       o2: int64,
       o3: int64,
       o4: int64,
       o5: int64,
       o6: int64,
       o7: int64,
       o8: int64,
       o9: int64,
       o10: int64,
       o11: int64,
       o12: int64,
       o13: int64,
       o14: int64,
       o15: int64,
       o16: int64,
       o17: int64,
       o18: int64,
       o19: int64,
       o20: int64,
       o21: int64,
       o22: int64,
       o23: int64,
       o24: int64,
       o25: int64,
       o26: int64,
       o27: int64,
       o28: int64,
       o29: int64,
       o: double,
       oo: int64,
       ooo: double,
       oooo: double,
       ooooo: double,
       oooooo: double,
       ooooooo: double,
       oooooooo: double,
       ooooooooo: double,
       oooooooooo: double,
       ooooooooooo: double,
       oooooooooooo: double,
       ooooooooooooo: double,
       oooooooooooooo: double,
       ooooooooooooooo: double,
       oooooooooooooooo: double,
       ooooooooooooooooo: double,
       iiiiiiiiiiiiiiiii: decimal128(38, 20),
       iiiiiiiiiiiiiiii: decimal128(38, 20),
       iiiiiiiiiiiiiii: double,
       iiiiiiiiiiiiii: double,
       iiiiiiiiiiiii: double,
       iiiiiiiiiiii: double,
       iiiiiiiiii: double,
       iiiiiiiii: double,1
       iiiiiiii: int64,
       iiiiiii: bool,
       iiiiii: int32,
       iiiii: date32[day]
    }
`

Probably yes, the initial data is computed by Spark, Ray Data reads it without errors and later it fails with this error. Error as I got it related to Decimal types.
