### ISSUE TITLE
Ray remote subprocess not recognizing Openai Gym environment registration

### ISSUE THREAD

**Issue by p-morais** [ray-project/ray#4591]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 18.04
- **Ray installed from (source or binary)**:
Binary
- **Ray version**:
0.6.5
- **Python version**:
3.7.1

### Describe the problem
Ray isn't recognizing the execution context for a worker the way I assume it should. I have a custom gym environment "gym_cassie" which is registered with openai gym, but this code doesn't work:

```python
import time
from functools import partial
import ray
import gym
import gym_cassie

@ray.remote
def worker(fn):
    env = fn()
    env.render()
    time.sleep(100)

env_fn = partial(gym.make, "Cassie-walking-v0")

ray.init()
ray.get([worker.remote(env_fn)])
```

I get the error ```gym.error.UnregisteredEnv: No registered env with id: Cassie-v0```. If I put "import gym_cassie" in the body of worker() like so:
```python
@ray.remote
def worker(fn):
    import gym_cassie
    env = fn()
    env.render()
    time.sleep(100)
```

it works though, which seems to imply that how ray handles parallelism breaks openai gym environment registration.

The same code using mp.Process() instead of Ray.get() works, so I assume this isn't intended behavior?

### Source code / logs
Here's the output and traceback:

```
2019-04-09 17:17:39,357	WARNING worker.py:1406 -- WARNING: Not updating worker name since `setproctitle` is not installed. Install this with `pip install setproctitle` (or ray[debug]) to enable monitoring of worker processes.
2019-04-09 17:17:39,358	INFO node.py:423 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-04-09_17-17-39_44500/logs.
2019-04-09 17:17:39,463	INFO services.py:363 -- Waiting for redis server at 127.0.0.1:36477 to respond...
2019-04-09 17:17:39,573	INFO services.py:363 -- Waiting for redis server at 127.0.0.1:34757 to respond...
2019-04-09 17:17:39,575	INFO services.py:760 -- Starting Redis shard with 10.0 GB max memory.
2019-04-09 17:17:39,588	WARNING services.py:1236 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
2019-04-09 17:17:39,588	INFO services.py:1384 -- Starting the Plasma object store with 20.0 GB memory using /dev/shm.
2019-04-09 17:17:40,809	WARNING worker.py:330 -- WARNING: Falling back to serializing objects of type <class 'functools.partial'> by using pickle. This may be inefficient.
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    ray.get([worker.remote(env_fn)])
  File "/home/beast/anaconda3/envs/rl/lib/python3.7/site-packages/ray/worker.py", line 2307, in get
    raise value
ray.exceptions.RayTaskError: ray_worker (pid=44572, host=beast)
KeyError: 'Cassie-walking-v0'

During handling of the above exception, another exception occurred:

ray_worker (pid=44572, host=beast)
  File "test.py", line 8, in worker
    env = fn()
  File "/home/beast/anaconda3/envs/rl/lib/python3.7/site-packages/gym/envs/registration.py", line 183, in make
    return registry.make(id, **kwargs)
  File "/home/beast/anaconda3/envs/rl/lib/python3.7/site-packages/gym/envs/registration.py", line 124, in make
    spec = self.spec(path)
  File "/home/beast/anaconda3/envs/rl/lib/python3.7/site-packages/gym/envs/registration.py", line 169, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: Cassie-walking-v0
```

**Comment by ericl** [comment]
https://ray.readthedocs.io/en/latest/rllib-env.html

^^ The gym registry is not compatible with Ray. Instead, always use the registration flows documented above to ensure Ray workers can access the environment.

**Comment by p-morais** [comment]
Ah, thank you for the prompt reply. I hadn’t thought to look in the RLlib documentation. I’ll close this issue now. 

For future reference though, what is it about the Ray backend that is incompatible with the gym registry? It’s kind of surprising to me.

**Comment by ericl** [comment]
I'm surprised multiprocessing works, actually, since the registry is not shared across processes. It could be gym is doing something specific for compatibility there...
