### ISSUE TITLE
[CORE]  ValueError: invalid attr name 'num_fds' filling dashboard_agent.log

### ISSUE THREAD

**Issue by OpenCoderX** [ray-project/ray#46187]
### What happened + What you expected to happen

While troubleshooting a call to ray.get which is hanging I noticed the dashboard_agent.log is being filled with "ValueError: invalid attr name 'num_fds'"

```
ERROR reporter_agent.py:1245 -- Error publishing node physical stats.
Traceback (most recent call last):
  File "C:\Users\user\.virtualenvs\projectx-Pa_ObYkn\Lib\site-packages\ray\dashboard\modules\reporter\reporter_agent.py", line 1225, in _perform_iteration
    stats = self._get_all_stats()
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\projectx-Pa_ObYkn\Lib\site-packages\ray\dashboard\modules\reporter\reporter_agent.py", line 748, in _get_all_stats
    "raylet": self._get_raylet(),
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\projectx-Pa_ObYkn\Lib\site-packages\ray\dashboard\modules\reporter\reporter_agent.py", line 667, in _get_raylet
    return raylet_proc.as_dict(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\projectx-Pa_ObYkn\Lib\site-packages\ray\thirdparty_files\psutil\__init__.py", line 546, in as_dict
    raise ValueError(msg)
ValueError: invalid attr name 'num_fds'
```

### Versions / Dependencies

- windows
- 2.30.0

### Reproduction script

unknown what exactly caused the  error

### Issue Severity

Low: It annoys or frustrates me.

**Comment by jjyao** [comment]
This is fixed by #46329
