### ISSUE TITLE
[Ray-Clusters] Azure Cluster Autoscaler failing to start worker nodes when using non-spot instances.

### ISSUE THREAD

**Issue by MKLepium** [ray-project/ray#46198]
### What happened + What you expected to happen

When spinning up workers in a ray cluster using the autoscaler the creation will fail and it will keep trying to initiate new virtual machines and in the process spin up public ip's and network interfaces until the limit is reached.

In the last version the following example with neither priority nor billing profile option set works as intended.

```
# optionally set priority to use Spot instances
#priority: Spot
# set a maximum price for spot instances if desired
#billingProfile:
#    maxPrice: -1
```

When running with the new latest version, I run into the following Issue:
(This is a log of the monitor.log from the headnode)

```
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/autoscaler/_private/node_launcher.py", line 113, in _launch_node
    created_nodes = self.provider.create_node_with_resources_and_labels(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/autoscaler/node_provider.py", line 152, in create_node_with_resources_and_labels
    return self.create_node(node_config, tags, count)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/autoscaler/_private/_azure/node_provider.py", line 247, in create_node
    self._create_node(node_config, tags, count)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/autoscaler/_private/_azure/node_provider.py", line 300, in _create_node
    create_or_update(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/azure/core/polling/_poller.py", line 270, in wait
    raise self._exception  # type: ignore
  File "/home/ray/anaconda3/lib/python3.9/site-packages/azure/core/polling/_poller.py", line 185, in _start
    self._polling_method.run()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/azure/core/polling/base_polling.py", line 772, in run
    raise HttpResponseError(response=self._pipeline_response.http_response, error=err) from err
azure.core.exceptions.HttpResponseError: (DeploymentFailed) At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.
Code: DeploymentFailed
Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.
Exception Details:	(BadRequest) {
	  "error": {
	    "code": (BadRequest) {
	  "error": {
	    "code": "InvalidParameter",
	    "message": "Eviction policy can be set only on Azure Spot Virtual Machines. For more information, see http://aka.ms/AzureSpot/errormessages.",
	    "target": "billingProfile"
	  }
	}
```

To clarify: This happens when the head node tries to spin up worker nodes.

The current workaround for me is just to use the older version for the head image 
Instead of:
head_image: "rayproject/ray-ml:latest-cpu"
Use:
head_image: "rayproject/ray-ml:2.24.0-cpu'

### Versions / Dependencies

The new Version of the rayproject/ray-ml - latest-cpu. I assume it was build with the new version of 2.30 of ray.

### Reproduction script

I used the example azure-full script but disabled the priority option to NOT request spot instances. (I have not tested if it still crashes if you request spot instances)
Simply run the start command: `ray up -y azure-full.yaml` And wait for the autoscaler to attempt to start a VM.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by MKLepium** [comment]
After looking into it:
Commit e38e576 introduced the evictionPolicy.
However as you can tell from the log output this can only be set if spot instances are used. So for situations where someone is not using spot instances, azure returns an error and the start of the worker node fails.

**Comment by MKLepium** [comment]
Option 1 (bad option):
Remove the option to set eviction Policies 
Option 2 (good option):
do something like:
```
if parameters["properties"]["parameters"].get("priority", {}).get("value") == "spot":
    parameters["properties"]["parameters"].pop("evictionPolicy", None)
```

In the https://github.com/MKLepium/ray/blob/master/python/ray/autoscaler/_private/_azure/node_provider.py
If I have the time I will test and spin up a PR.

**Comment by MKLepium** [comment]
Quick test case that my code functionally works 

```
def test_function(parameters):
    if parameters["properties"]["parameters"].get("priority", {}).get("value") == "spot":
        parameters["properties"]["parameters"].pop("evictionPolicy", None)
    return parameters

# Define a sample parameters dictionary
parameters_with_spot_priority = {
    "properties": {
        "parameters": {
            "priority": {"value": "spot"},
            "evictionPolicy": "Deallocate"
        }
    }
}

parameters_without_spot_priority = {
    "properties": {
        "parameters": {
            "priority": {"value": "regular"},
            "evictionPolicy": "Deallocate"
        }
    }
}

# Test case where priority is "spot"
print("Before (spot):", parameters_with_spot_priority)
result_spot = test_function(parameters_with_spot_priority)
print("After (spot):", result_spot)

# Test case where priority is not "spot"
print("Before (regular):", parameters_without_spot_priority)
result_regular = test_function(parameters_without_spot_priority)
print("After (regular):", result_regular)
```

```
Before (spot): {'properties': {'parameters': {'priority': {'value': 'spot'}, 'evictionPolicy': 'Deallocate'}}}
After (spot): {'properties': {'parameters': {'priority': {'value': 'spot'}}}}
Before (regular): {'properties': {'parameters': {'priority': {'value': 'regular'}, 'evictionPolicy': 'Deallocate'}}}
After (regular): {'properties': {'parameters': {'priority': {'value': 'regular'}, 'evictionPolicy': 'Deallocate'}}}

```
