### ISSUE TITLE
[ConnectionError: ray client connection timeout] 

### ISSUE THREAD

**Issue by LIUKAI0815** [ray-project/ray#46733]
### What happened + What you expected to happen

import ray
ray.init("ray://10.157.148.2:6379")

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1721616648.778070 1602194 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/util/client/worker.py:253: UserWarning: Ray Client connection timed out. Ensure that the Ray Client port on the head node is reachable from your local machine. See https://docs.ray.io/en/latest/cluster/ray-client.html#step-2-check-ports for more information.
  warnings.warn(
Traceback (most recent call last):
  File "/home/ubuntu/xiyou/modelpipeline/classify/ra_client.py", line 2, in <module>
    ray.init("ray://10.157.148.2:6379")
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/_private/worker.py", line 1485, in init
    ctx = builder.connect()
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/client_builder.py", line 175, in connect
    client_info_dict = ray.util.client_connect.connect(
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/util/client_connect.py", line 55, in connect
    conn = ray.connect(
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/util/client/__init__.py", line 233, in connect
    conn = self.get_context().connect(*args, **kw_args)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/util/client/__init__.py", line 89, in connect
    self.client_worker = Worker(
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/util/client/worker.py", line 139, in __init__
    self._connect_channel()
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/util/client/worker.py", line 260, in _connect_channel
    raise ConnectionError("ray client connection timeout")
ConnectionError: ray client connection timeou

### Versions / Dependencies

ray                               2.32.0
Python                         3.10.14

### Reproduction script

import ray
ray.init("ray://10.157.148.2:6379")

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1721616648.778070 1602194 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/util/client/worker.py:253: UserWarning: Ray Client connection timed out. Ensure that the Ray Client port on the head node is reachable from your local machine. See https://docs.ray.io/en/latest/cluster/ray-client.html#step-2-check-ports for more information.
  warnings.warn(
Traceback (most recent call last):
  File "/home/ubuntu/xiyou/modelpipeline/classify/ra_client.py", line 2, in <module>
    ray.init("ray://10.157.148.2:6379")
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/_private/worker.py", line 1485, in init
    ctx = builder.connect()
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/client_builder.py", line 175, in connect
    client_info_dict = ray.util.client_connect.connect(
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/util/client_connect.py", line 55, in connect
    conn = ray.connect(
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/util/client/__init__.py", line 233, in connect
    conn = self.get_context().connect(*args, **kw_args)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/util/client/__init__.py", line 89, in connect
    self.client_worker = Worker(
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/util/client/worker.py", line 139, in __init__
    self._connect_channel()
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/ray/util/client/worker.py", line 260, in _connect_channel
    raise ConnectionError("ray client connection timeout")
ConnectionError: ray client connection timeou

### Issue Severity

High: It blocks me from completing my task.

**Comment by jjyao** [comment]
Hi @LIUKAI0815, do you have the ray client server running on the remote cluster? Also Ray client is not recommended for running Ray applications. You should use Ray job submission instead.
