### ISSUE TITLE
[Core\aDAG] AttributeError: 'Worker' object has no attribute 'core_worker' upon destruction

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#46796]
### What happened + What you expected to happen

```
2024-07-24 23:46:13,852 INFO compiled_dag_node.py:1242 -- Tearing down compiled DAG
Exception ignored in: <function RayGPUExecutor.__del__ at 0x76b9206320d0>
Traceback (most recent call last):
  File "/home/ray/default/vllm/vllm/executor/ray_gpu_executor.py", line 397, in __del__
    self.forward_dag.teardown()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/dag/compiled_dag_node.py", line 1442, in teardown
    monitor.teardown(wait=True)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/dag/compiled_dag_node.py", line 1244, in teardown
    outer._dag_submitter.close()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/experimental/channel/common.py", line 383, in close
    self._output_channel.close()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/experimental/channel/shared_memory_channel.py", line 628, in close
    channel.close()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/experimental/channel/shared_memory_channel.py", line 507, in close
    self._worker.core_worker.experimental_channel_set_error(self._writer_ref)
AttributeError: 'Worker' object has no attribute 'core_worker'
```

Happened when using aDAG + vLLM integration + tp 2 + benchmark_throughput.py in a10g instance

### Versions / Dependencies

nightly

### Reproduction script

n/a

### Issue Severity

None

**Comment by Bye-legumes** [comment]
Maybe we need to add check? https://github.com/ray-project/ray/pull/47227 may solve this?
