### ISSUE TITLE
Initialization of remote logdir fails to correctly expand user directory

### ISSUE THREAD

**Issue by goshaQ** [ray-project/ray#4698]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: Binary
- **Ray version**: 0.6.6
- **Python version**: 3.7.3
- **Exact command to reproduce**:

### Describe the problem

When ray is initialized with specified `redis_address`, i.e. in distributed setup, the remote logdir is incorrectly determined. By default, Tune writes result files into `~/ray_results`, however it causes a problem if the result files need to be stored on another machine with different user directory.

For example, I have on my computer user directory `/home/gosha` and on another computer (provided by university) I have user directory `/home/gemelyanov`.  In the stack trace below you can see that the permission error occurs on another computer when Tune attempts to create the logdir in non-existent user directory. 

### Source code / logs

```
2019-04-25 13:32:43,033	INFO ray_trial_executor.py:180 -- Destroying actor for trial DQN_SUMOEnv-v0_0. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
(pid=21073, ip=<remote-computer-ip>) LOGDIR /home/gosha/ray_results/agent_dqn/DQN_SUMOEnv-v0_0_2019-04-25_13-32-38e20cvzum
2019-04-25 13:32:43,047	INFO trial_runner.py:531 -- Attempting to recover trial state from last checkpoint.
2019-04-25 13:32:44,166	ERROR trial_runner.py:494 -- Error processing event.
Traceback (most recent call last):
  File "/home/gosha/workspace/anaconda3/envs/tensorflow/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 443, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/gosha/workspace/anaconda3/envs/tensorflow/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 316, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/gosha/workspace/anaconda3/envs/tensorflow/lib/python3.7/site-packages/ray/worker.py", line 2193, in get
    raise value
ray.exceptions.RayTaskError: ray_worker (pid=21078, host=IU-stand01)
  File "/home/gemelyanov/workspace/anaconda3/envs/tensorflow/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 293, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/gemelyanov/workspace/anaconda3/envs/tensorflow/lib/python3.7/site-packages/ray/tune/trainable.py", line 70, in __init__
    self._result_logger = logger_creator(self.config)
  File "/home/gosha/workspace/anaconda3/envs/tensorflow/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 100, in logger_creator
  File "/home/gemelyanov/workspace/anaconda3/envs/tensorflow/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/gemelyanov/workspace/anaconda3/envs/tensorflow/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/gemelyanov/workspace/anaconda3/envs/tensorflow/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/gemelyanov/workspace/anaconda3/envs/tensorflow/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/gosha'
```

**Comment by neychev** [comment]
Seems as a copy of #4326

**Comment by goshaQ** [comment]
Indeed. I will close this issue as a duplicate of #4326 .
