### ISSUE TITLE
[core][adag] 1F1B pipeline schedule hangs even without NCCL ops

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#47039]
### What happened + What you expected to happen

1F1B is expected to hang right now because of a NCCL deadlock, which should be addressed by #46911. However, [this script](https://gist.github.com/stephanie-wang/7a80d96e55b1245349588de165190f7d) should also produce a 1F1B schedule and it seems to hang even without TorchTensorType annotations. It executes a `fwd` task on all workers for the first batch, and then throws a timeout error:
```
(Worker pid=690168) fwd 2 0
(Worker pid=690166) fwd 0 0
(Worker pid=690167) fwd 1 0
(Worker pid=690169) fwd 3 0
Traceback (most recent call last):
  File "/home/swang/ray/1f1b.py", line 68, in <module>
    ray.get(dag.execute(*range(NUM_MICROBATCHES)))
  File "/home/swang/anaconda3/envs/ray-wheel-310/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/swang/anaconda3/envs/ray-wheel-310/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/swang/anaconda3/envs/ray-wheel-310/lib/python3.10/site-packages/ray/_private/worker.py", line 2646, in get
    return object_refs.get(timeout=timeout)
  File "/home/swang/anaconda3/envs/ray-wheel-310/lib/python3.10/site-packages/ray/experimental/compiled_dag_ref.py", line 90, in get
    return_vals = self._dag._execute_until(self._execution_index, timeout)
  File "/home/swang/anaconda3/envs/ray-wheel-310/lib/python3.10/site-packages/ray/dag/compiled_dag_node.py", line 1387, in _execute_until
    return self._dag_output_fetcher.read(timeout)
  File "/home/swang/anaconda3/envs/ray-wheel-310/lib/python3.10/site-packages/ray/experimental/channel/common.py", line 279, in read
    outputs = self._read_list(timeout)
  File "/home/swang/anaconda3/envs/ray-wheel-310/lib/python3.10/site-packages/ray/experimental/channel/common.py", line 301, in _read_list
    results.append(c.read(timeout))
  File "/home/swang/anaconda3/envs/ray-wheel-310/lib/python3.10/site-packages/ray/experimental/channel/shared_memory_channel.py", line 597, in read
    return self._channel_dict[actor_id].read(timeout)
  File "/home/swang/anaconda3/envs/ray-wheel-310/lib/python3.10/site-packages/ray/experimental/channel/shared_memory_channel.py", line 454, in read
    ret = self._worker.get_objects(
  File "/home/swang/anaconda3/envs/ray-wheel-310/lib/python3.10/site-packages/ray/_private/worker.py", line 848, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 3511, in ray._raylet.CoreWorker.get_objects

  File "python/ray/includes/common.pxi", line 102, in ray._raylet.check_status
ray.exceptions.RayChannelTimeoutError: System error: Timed out waiting for object available to read.
```

### Versions / Dependencies

3.0dev

### Reproduction script

https://gist.github.com/stephanie-wang/7a80d96e55b1245349588de165190f7d

### Issue Severity

None

**Comment by stephanie-wang** [comment]
This is the same as #47041.
