### ISSUE TITLE
Freeing up memory does not work

### ISSUE THREAD

**Issue by hlbkin** [ray-project/ray#4708]
Python 3.6.7, ray 0.6.6

Im using custom memory freeing (because I iterate over datasets throughout the process)

``` task_dataset_object_id = pin_in_object_store(dataset)
object_id = get_object_id_from_transformed_object_id(task_dataset_object_id)

def get_object_id_from_transformed_object_id(transformed_object_id: str):
    """
    This function casts the sring representation of ray ObjectID to native ObjectID instance that can be passed to
    the `ray.internal.free` function.

    Parameters
    ----------
    transformed_object_id: str
        Object id in format returned by `ray.tune.util.pin_in_object_store` function.

    Returns
    -------
    object_id: ray.ObjectID
        Original `ray.ObjectID` instance.
    """
    from ray import ObjectID
    from ray.tune.util import PINNED_OBJECT_PREFIX
    without_prefix = transformed_object_id[len(PINNED_OBJECT_PREFIX):]
    object_id = ObjectID(base64.b64decode(without_prefix))
    return object_id

""" fitting process"""

ray.internal.free([object_id])

``` and then other datasets in the loop

However, I still get memory error

``` Traceback (most recent call last):
File "/home/yhgtemp/PycharmProjects/reportingandanalysis/autoreporting/PredictionTasks/ShortTermVolFXO/FXOProductionFit.py", line 275, in <module>
obj.train_all_models("192.168.14.240:6379", local_mode=False)
File "/home/yhgtemp/PycharmProjects/reportingandanalysis/autoreporting/PredictionTasks/ShortTermVolFXO/FXOProductionFit.py", line 139, in train_all_models
task_dataset_object_id = pin_in_object_store(with_currency_pair_vars_dataset)
File "/home/yhgtemp/anaconda3/envs/py3_prod/lib/python3.6/site-packages/ray/tune/util.py", line 27, in pin_in_object_store
obj_id = ray.put(_to_pinnable(obj))
File "/home/yhgtemp/anaconda3/envs/py3_prod/lib/python3.6/site-packages/ray/worker.py", line 2216, in put
worker.put_object(object_id, value)
File "/home/yhgtemp/anaconda3/envs/py3_prod/lib/python3.6/site-packages/ray/worker.py", line 375, in put_object
self.store_and_register(object_id, value)
File "/home/yhgtemp/anaconda3/envs/py3_prod/lib/python3.6/site-packages/ray/worker.py", line 309, in store_and_register
self.task_driver_id))
File "/home/yhgtemp/anaconda3/envs/py3_prod/lib/python3.6/site-packages/ray/utils.py", line 475, in _wrapper
return orig_attr(*args, **kwargs)
File "pyarrow/_plasma.pyx", line 497, in pyarrow._plasma.PlasmaClient.put
File "pyarrow/_plasma.pyx", line 327, in pyarrow._plasma.PlasmaClient.create
File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.PlasmaStoreFull: object does not fit in the plasma store ```

**Comment by ericl** [comment]
This is probably since the `_pinned_objects` field in tune/util.py still has a python reference to the object. The object is queued for deletion but can't actually be freed until the python reference count drops to zero.

**Comment by robertnishihara** [comment]
What is the object store size? And how much memory should be required to run your application?

Can you share a minimal example that reproduces the issue?

**Comment by edoakes** [comment]
Stale - please open new issue if still relevant
