### ISSUE TITLE
Building from source fails 

### ISSUE THREAD

**Issue by sfilipi** [ray-project/ray#4719]
I cloned the repo, and building is not succeeding. 

### System information
- **Ubuntu 18.04.1 LTS**:
- **Python 3.6.5** 
(although it seems like the installation scripts are making use of 2.7 ?
I have aliased python to python3 )
- ray/python$ pip install -e . --verbose
- setupTools is installed: setuptools-41.0.1

### Traceback
    Collecting numpy>=1.14 (from pyarrow==0.12.0.RAY)
      Using cached https://files.pythonhosted.org/packages/e1/72/179a78b565ecf01fe98dab6417581d30acac15c2d93c49f93169ebea99b1/numpy-1.16.3-cp27-cp27mu-manylinux1_x86_64.whl
    Installing collected packages: six, enum34, futures, numpy, pyarrow
    Exception:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
        status = self.run(options, args)
      File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 360, in run
        prefix=options.prefix_path,
      File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
        **kwargs
      File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
        self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
      File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
        isolated=self.isolated,
      File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 247, in move_wheel_files
        prefix=prefix,
      File "/usr/lib/python2.7/dist-packages/pip/locations.py", line 153, in distutils_scheme
        i.finalize_options()
      File "/usr/lib/python2.7/distutils/command/install.py", line 289, in finalize_options
        raise DistutilsOptionError("can't combine user with prefix, "
     DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
     Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/c/Code/Ray/ray/python/setup.py", line 183, in <module>
        license="Apache 2.0")
      File "/home/sefilipi/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/sefilipi/.local/lib/python2.7/site-packages/setuptools/command/develop.py", line 38, in 
     run
        self.install_for_development()
      File "/home/sefilipi/.local/lib/python2.7/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/mnt/c/Code/Ray/ray/python/setup.py", line 74, in run
        subprocess.check_call(command)
      File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '-p', '/usr/bin/python']' returned non-zero exit status 2
    Cleaning up...
    Command "/usr/bin/python -c "import setuptools, 
    tokenize;__file__='/mnt/c/Code/Ray/ray/python/setup.py';f=getattr(tokenize, 'open', open) 
    (__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop 
    --no-deps --user --prefix=" failed with error code 1 in /mnt/c/Code/Ray/ray/python/
    Exception information:
    Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
    File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
    File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
    File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 845, in install
    install_options, global_options, prefix=prefix)
    File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1007, in install_editable
    show_stdout=False)
    File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 725, in call_subprocess
     % (command_desc, proc.returncode, cwd))
    InstallationError: Command "/usr/bin/python -c "import setuptools, 
    tokenize;__file__='/mnt/c/Code/Ray/ray/python/setup.py';f=getattr(tokenize, 'open', open) 
    (__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop - 
    -no-deps --user --prefix=" failed with error code 1 in /mnt/c/Code/Ray/ray/python/

**Comment by robertnishihara** [comment]
There might have been an error earlier on in the installation. Can you include the full output?

Also, what does `which bazel` output?

**Comment by sfilipi** [comment]
bazel is installed in my home folder:

     which bazel
    /home/sefilipi/bin/bazel

I have numpy installed, but in the logs there are references to wheel files in .exe format. 

https://files.pythonhosted.org/packages/40/11/087b97fa8ee850ec7922d294cdd5ccb400a0f4f23bdf19eb22677813bd3e/numpy-1.6.2.win32-py3.1.exe#sha256=039f0f076420fbcda81fbe011b162358d85484628ebec574fb99f2bbf3cad688 (from https://pypi.org/simple/numpy/); unsupported archive format: .exe
[install2.log](https://github.com/ray-project/ray/files/3133905/install2.log)

idk if the above is caused because Ubuntu is actually installed on the Linux subsystem, on Windows 10. I'll try on an Ubuntu VM, to compare. 

Does it look right that it is trying to use python 2.7, when I have python mapped to python3 (3.6.5 installed)?

**Comment by sfilipi** [comment]
[install2.log](https://github.com/ray-project/ray/files/3133909/install2.log)

**Comment by robertnishihara** [comment]
It looks like the Ray repository lives in the Windows file system, is that right? Can you try cloning the Ray repository on the Ubuntu file system and see if compilation works in that setting?

**Comment by sfilipi** [comment]
I moved to using anaconda with a Python 3.5 environment, and it is all building/installing/running the tests in the WSL. 

The info on #3059 helped. 

@robertnishihara leaving the issue open, in case you want to keep it around for further investigation; I am all set, thanks for the help.

**Comment by robertnishihara** [comment]
Great to hear! I’ll close this for now since I think the original issue will be difficult to track down.
