### ISSUE TITLE
[ADAG] ADAG failed to print the stack trace of an errored actor method.

### ISSUE THREAD

**Issue by woshiyyya** [ray-project/ray#47285]
### What happened + What you expected to happen

<img width="555" alt="Screenshot 2024-08-22 at 2 25 33 PM" src="https://github.com/user-attachments/assets/1feb3ab7-516e-4a2b-84d7-2a7263078c2c">

When running above ADAG, the fwd method raised an error (cuda device mismatch error). We didn't see the stack trace in the terminal logs, instead we saw a timeout error of a shared memory channel.

```
Traceback (most recent call last):
  File "/home/ray/default/test.py", line 288, in <module>
    print(ray.get(dag.execute((rand_images, rand_text))))
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/worker.py", line 2648, in get
    return object_refs.get(timeout=timeout)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/experimental/compiled_dag_ref.py", line 90, in get
    return_vals = self._dag._execute_until(self._execution_index, timeout)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dag/compiled_dag_node.py", line 1577, in _execute_until
    return self._dag_output_fetcher.read(timeout)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/experimental/channel/common.py", line 279, in read
    outputs = self._read_list(timeout)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/experimental/channel/common.py", line 301, in _read_list
    results.append(c.read(timeout))
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/experimental/channel/shared_memory_channel.py", line 597, in read
    return self._channel_dict[actor_id].read(timeout)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/experimental/channel/shared_memory_channel.py", line 454, in read
    ret = self._worker.get_objects(
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/worker.py", line 848, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 3510, in ray._raylet.CoreWorker.get_objects
  File "python/ray/includes/common.pxi", line 102, in ray._raylet.check_status
ray.exceptions.RayChannelTimeoutError: System error: Timed out waiting for object available to read.
```

The current workaround is to manually add a try-catch logic in the actor method, and actively print the stack trace.

### Versions / Dependencies

nightly

### Reproduction script

Repro Workspace: https://console.anyscale-staging.com/o/anyscale-internal/workspaces/expwrk_7su56wvlifxjiqr9751642xrlr/ses_hpyd5beaq86plk4j8e534x3bu2

Code: https://gist.github.com/woshiyyya/b0b5fd0666a54e7890e727a647be3cbe

```
pip install open_clip_torch
RAY_ADAG_ENABLE_DETECT_DEADLOCK=0 python test.py
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by ruisearch42** [comment]
@kevin85421 The solution is to forbid leaf node which is already done, and this can be closed?

**Comment by kevin85421** [comment]
@ruisearch42 I checked the repro gist, and it is different from the figure in the issue description. There are no leaf nodes in the gist.
