### ISSUE TITLE
Not able to use HyperOpt

### ISSUE THREAD

**Issue by harshpatel1242** [ray-project/ray#47416]
### What happened + What you expected to happen

`Traceback (most recent call last):
  File "/home/terrylica/Projects/Cluster_Based/src/pt.py", line 105, in <module>
    search_alg = HyperOptSearch(
                 ^^^^^^^^^^^^^^^
  File "/home/terrylica/Projects/Cluster_Based/env_for_cluster/lib/python3.12/site-packages/ray/tune/search/hyperopt/hyperopt_search.py", line 163, in __init__
    hpo is not None`

### Versions / Dependencies

Latest version

### Reproduction script

from ray.tune.search.hyperopt import HyperOptSearch
search_alg = HyperOptSearch(
    metric="cumulative_return",
    mode="max")

### Issue Severity

High: It blocks me from completing my task.

**Comment by safersephy** [comment]
having the same problem on ray 2.40.0
