### ISSUE TITLE
[rllib] test_avail_actions_qmix.py is blocking Jenkins tests

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#4742]
```
2019-05-03 00:05:04,062	INFO sampler.py:308 -- Raw obs from env: { 0: { 'group_1': [ { 'action_mask': np.ndarray((10,), dtype=int64, min=0.0, max=1.0, mean=0.1),
                      'obs': 0}]},
  1: { 'group_1': [ { 'action_mask': np.ndarray((10,), dtype=int64, min=0.0, max=1.0, mean=0.1),
                      'obs': 0}]},
  2: { 'group_1': [ { 'action_mask': np.ndarray((10,), dtype=int64, min=0.0, max=1.0, mean=0.1),
                      'obs': 0}]},
  3: { 'group_1': [ { 'action_mask': np.ndarray((10,), dtype=int64, min=0.0, max=1.0, mean=0.1),
                      'obs': 0}]},
  4: { 'group_1': [ { 'action_mask': np.ndarray((10,), dtype=int64, min=0.0, max=1.0, mean=0.1),
                      'obs': 0}]}}
2019-05-03 00:05:04,064	INFO sampler.py:309 -- Info return from env: { 0: { 'group_1': { }},
  1: { 'group_1': { }},
  2: { 'group_1': { }},
  3: { 'group_1': { }},
  4: { 'group_1': { }}}
2019-05-03 00:05:04,064	INFO sampler.py:407 -- Preprocessed obs: np.ndarray((13,), dtype=float64, min=0.0, max=1.0, mean=0.154)
2019-05-03 00:05:04,065	INFO sampler.py:411 -- Filtered obs: np.ndarray((13,), dtype=float64, min=0.0, max=1.0, mean=0.154)
2019-05-03 00:05:04,074	INFO sampler.py:525 -- Inputs to compute_actions():

{ 'default_policy': [ { 'data': { 'agent_id': 'group_1',
                                  'env_id': 0,
                                  'info': { },
                                  'obs': np.ndarray((13,), dtype=float64, min=0.0, max=1.0, mean=0.154),
                                  'prev_action': np.ndarray((1,), dtype=int64, min=0.0, max=0.0, mean=0.0),
                                  'prev_reward': 0.0,
                                  'rnn_state': [ np.ndarray((1, 64), dtype=float32, min=0.0, max=0.0, mean=0.0)]},
                        'type': 'PolicyEvalData'},
                      { 'data': { 'agent_id': 'group_1',
                                  'env_id': 1,
                                  'info': { },
                                  'obs': np.ndarray((13,), dtype=float64, min=0.0, max=1.0, mean=0.154),
                                  'prev_action': np.ndarray((1,), dtype=int64, min=0.0, max=0.0, mean=0.0),
                                  'prev_reward': 0.0,
                                  'rnn_state': [ np.ndarray((1, 64), dtype=float32, min=0.0, max=0.0, mean=0.0)]},
                        'type': 'PolicyEvalData'},
                      { 'data': { 'agent_id': 'group_1',
                                  'env_id': 2,
                                  'info': { },
                                  'obs': np.ndarray((13,), dtype=float64, min=0.0, max=1.0, mean=0.154),
                                  'prev_action': np.ndarray((1,), dtype=int64, min=0.0, max=0.0, mean=0.0),
                                  'prev_reward': 0.0,
                                  'rnn_state': [ np.ndarray((1, 64), dtype=float32, min=0.0, max=0.0, mean=0.0)]},
                        'type': 'PolicyEvalData'},
                      { 'data': { 'agent_id': 'group_1',
                                  'env_id': 3,
                                  'info': { },
                                  'obs': np.ndarray((13,), dtype=float64, min=0.0, max=1.0, mean=0.154),
                                  'prev_action': np.ndarray((1,), dtype=int64, min=0.0, max=0.0, mean=0.0),
                                  'prev_reward': 0.0,
                                  'rnn_state': [ np.ndarray((1, 64), dtype=float32, min=0.0, max=0.0, mean=0.0)]},
                        'type': 'PolicyEvalData'},
                      { 'data': { 'agent_id': 'group_1',
                                  'env_id': 4,
                                  'info': { },
                                  'obs': np.ndarray((13,), dtype=float64, min=0.0, max=1.0, mean=0.154),
                                  'prev_action': np.ndarray((1,), dtype=int64, min=0.0, max=0.0, mean=0.0),
                                  'prev_reward': 0.0,
                                  'rnn_state': [ np.ndarray((1, 64), dtype=float32, min=0.0, max=0.0, mean=0.0)]},
                        'type': 'PolicyEvalData'}]}

2019-05-03 00:05:04,114	INFO sampler.py:552 -- Outputs of compute_actions():

{ 'default_policy': ( { 'data': { 'batches': [ np.ndarray((5,), dtype=int64, min=3.0, max=3.0, mean=3.0)]},
                        'type': 'TupleActions'},
                      [ np.ndarray((5, 1, 64), dtype=float32, min=-0.276, max=0.187, mean=0.003)],
                      { })}

2019-05-03 00:05:04,292	INFO sample_batch_builder.py:161 -- Trajectory fragment after postprocess_trajectory():

{ 'group_1': { 'data': { 'actions': np.ndarray((21, 1), dtype=int64, min=3.0, max=3.0, mean=3.0),
                         'agent_index': np.ndarray((21,), dtype=int64, min=0.0, max=0.0, mean=0.0),
                         'dones': np.ndarray((21,), dtype=bool, min=0.0, max=1.0, mean=0.048),
                         'eps_id': np.ndarray((21,), dtype=int64, min=32309652.0, max=32309652.0, mean=32309652.0),
                         'infos': np.ndarray((21,), dtype=object, head={'_group_rewards': [1]}),
                         'new_obs': np.ndarray((21, 13), dtype=float32, min=0.0, max=1.0, mean=0.154),
                         'obs': np.ndarray((21, 13), dtype=float32, min=0.0, max=1.0, mean=0.154),
                         'prev_actions': np.ndarray((21, 1), dtype=int64, min=0.0, max=3.0, mean=2.857),
                         'prev_rewards': np.ndarray((21,), dtype=float32, min=0.0, max=1.0, mean=0.952),
                         'rewards': np.ndarray((21,), dtype=int64, min=1.0, max=1.0, mean=1.0),
                         'state_in_0': np.ndarray((21, 1, 64), dtype=float32, min=-0.446, max=0.452, mean=-0.003),
                         'state_out_0': np.ndarray((21, 1, 64), dtype=float32, min=-0.446, max=0.453, mean=-0.003),
                         't': np.ndarray((21,), dtype=int64, min=0.0, max=20.0, mean=10.0),
                         'unroll_id': np.ndarray((21,), dtype=int64, min=0.0, max=0.0, mean=0.0)},
               'type': 'SampleBatch'}}

2019-05-03 00:05:04,298	INFO policy_evaluator.py:474 -- Completed sample batch:

{ 'data': { 'actions': np.ndarray((21, 1), dtype=int64, min=3.0, max=3.0, mean=3.0),
            'agent_index': np.ndarray((21,), dtype=int64, min=0.0, max=0.0, mean=0.0),
            'dones': np.ndarray((21,), dtype=bool, min=0.0, max=1.0, mean=0.048),
            'eps_id': np.ndarray((21,), dtype=int64, min=32309652.0, max=32309652.0, mean=32309652.0),
            'infos': np.ndarray((21,), dtype=object, head={'_group_rewards': [1]}),
            'new_obs': np.ndarray((21, 13), dtype=float32, min=0.0, max=1.0, mean=0.154),
            'obs': np.ndarray((21, 13), dtype=float32, min=0.0, max=1.0, mean=0.154),
            'prev_actions': np.ndarray((21, 1), dtype=int64, min=0.0, max=3.0, mean=2.857),
            'prev_rewards': np.ndarray((21,), dtype=float32, min=0.0, max=1.0, mean=0.952),
            'rewards': np.ndarray((21,), dtype=int64, min=1.0, max=1.0, mean=1.0),
            'state_in_0': np.ndarray((21, 1, 64), dtype=float32, min=-0.446, max=0.452, mean=-0.003),
            'state_out_0': np.ndarray((21, 1, 64), dtype=float32, min=-0.446, max=0.453, mean=-0.003),
            't': np.ndarray((21,), dtype=int64, min=0.0, max=20.0, mean=10.0),
            'unroll_id': np.ndarray((21,), dtype=int64, min=0.0, max=0.0, mean=0.0)},
  'type': 'SampleBatch'}

2019-05-03 00:05:04,914	INFO policy_evaluator.py:564 -- Training on concatenated sample batches:

{ 'count': 42,
  'policy_batches': { 'default_policy': { 'data': { 'actions': np.ndarray((42, 1), dtype=int64, min=3.0, max=3.0, mean=3.0),
                                                    'agent_index': np.ndarray((42,), dtype=int64, min=0.0, max=0.0, mean=0.0),
                                                    'dones': np.ndarray((42,), dtype=bool, min=0.0, max=1.0, mean=0.048),
                                                    'eps_id': np.ndarray((42,), dtype=int64, min=269763381.0, max=803002603.0, mean=536382992.0),
                                                    'infos': np.ndarray((42,), dtype=object, head={'_group_rewards': [1]}),
                                                    'new_obs': np.ndarray((42, 13), dtype=float32, min=0.0, max=1.0, mean=0.154),
                                                    'obs': np.ndarray((42, 13), dtype=float32, min=0.0, max=1.0, mean=0.154),
                                                    'prev_actions': np.ndarray((42, 1), dtype=int64, min=0.0, max=3.0, mean=2.857),
                                                    'prev_rewards': np.ndarray((42,), dtype=float32, min=0.0, max=1.0, mean=0.952),
                                                    'rewards': np.ndarray((42,), dtype=int64, min=1.0, max=1.0, mean=1.0),
                                                    'state_in_0': np.ndarray((42, 1, 64), dtype=float32, min=-0.446, max=0.452, mean=-0.003),
                                                    'state_out_0': np.ndarray((42, 1, 64), dtype=float32, min=-0.446, max=0.453, mean=-0.003),
                                                    't': np.ndarray((42,), dtype=int64, min=0.0, max=20.0, mean=10.0),
                                                    'unroll_id': np.ndarray((42,), dtype=int64, min=3.0, max=3.0, mean=3.0)},
                                          'type': 'SampleBatch'}},
  'type': 'MultiAgentBatch'}

Traceback (most recent call last):
  File "/ray/python/ray/rllib/tests/test_avail_actions_qmix.py", line 68, in <module>
    agent.train()  # OK if it doesn't trip the action assertion error
  File "/ray/python/ray/rllib/agents/trainer.py", line 352, in train
    raise e
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [2, 21, 1, 10]], which is output 0 of SliceBackward, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

**Comment by richardliaw** [comment]
cc @ericl

**Comment by ericl** [comment]
Uh, was the torch version upgraded or something? I don't think this code has otherwise changed recently.

**Comment by richardliaw** [comment]
I don't think we changed torch but also think we don't pin torch..

**Comment by ericl** [comment]
I fixed this in https://github.com/ray-project/ray/pull/4735 by adding a `mac_out.clone()` op. It seems a torch upgrade changed the semantics of some op to not clone.
