### ISSUE TITLE
[core][aDAG] Bad error message upon shutdown when aDAG actors are owned

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#47599]
### What happened + What you expected to happen

as you see below, when aDAG actors are owned by another actor, and if it doesn't properly teardown them, there are bad error messages such as
```
(SDXLModelParallel pid=212978) Using blocking ray.get inside async actor. This blocks the event loop. Please use `await` on object ref with asyncio.gather if you want to yield execution to the event loop instead.
(SDXLModelParallel pid=212978) Creating NCCL group 2da864f7-d791-4819-af7f-1c3dc57698f2 on actors: [Actor(RefinerModelActor, 5803728403d160f5bfcb410601000000), Actor(BaseModelActor, 0169c2ea9a058abbe3f8157a01000000)]
(SDXLModelParallel pid=212978) NCCL group initialized.
(RefinerModelActor pid=213039) /home/ubuntu/sang-dev/ray/python/ray/experimental/channel/serialization_context.py:115: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:206.)
(RefinerModelActor pid=213039)   cpu_tensor = torch.from_numpy(np_array)
(SDXLModelParallel pid=212978) Tearing down compiled DAG
(SDXLModelParallel pid=212978) Cancelling compiled worker on actor: Actor(RefinerModelActor, 5803728403d160f5bfcb410601000000)
(SDXLModelParallel pid=212978) Cancelling compiled worker on actor: Actor(BaseModelActor, 0169c2ea9a058abbe3f8157a01000000)
(SDXLModelParallel pid=212978) Error cancelling worker task
(SDXLModelParallel pid=212978) Traceback (most recent call last):
(SDXLModelParallel pid=212978)   File "/home/ubuntu/sang-dev/ray/python/ray/dag/compiled_dag_node.py", line 1866, in run
(SDXLModelParallel pid=212978)     ray.get(list(outer.worker_task_refs.values()))
(SDXLModelParallel pid=212978)   File "/home/ubuntu/sang-dev/ray/python/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
(SDXLModelParallel pid=212978)     return fn(*args, **kwargs)
(SDXLModelParallel pid=212978)   File "/home/ubuntu/sang-dev/ray/python/ray/_private/client_mode_hook.py", line 103, in wrapper
(SDXLModelParallel pid=212978)     return func(*args, **kwargs)
(SDXLModelParallel pid=212978)   File "/home/ubuntu/sang-dev/ray/python/ray/_private/worker.py", line 2664, in get
(SDXLModelParallel pid=212978)     values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
(SDXLModelParallel pid=212978)   File "/home/ubuntu/sang-dev/ray/python/ray/_private/worker.py", line 873, in get_objects
(SDXLModelParallel pid=212978)     raise value
(SDXLModelParallel pid=212978) ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
(SDXLModelParallel pid=212978) 	class_name: BaseModelActor
(SDXLModelParallel pid=212978) 	actor_id: 0169c2ea9a058abbe3f8157a01000000
(SDXLModelParallel pid=212978) 	pid: 213038
(SDXLModelParallel pid=212978) 	namespace: 6b6e8639-5027-438b-adb3-9f4c2760a9be
(SDXLModelParallel pid=212978) 	ip: 172.31.14.211
(SDXLModelParallel pid=212978) The actor is dead because its owner has died. Owner Id: 56eafb30de59323bfb106de740c8e169fa6eae1587c8c683ce54ca71 Owner Ip address: 172.31.14.211 Owner worker exit type: SYSTEM_ERROR Worker exit detail: Owner's node has crashed.
(SDXLModelParallel pid=212978) 
(SDXLModelParallel pid=212978) During handling of the above exception, another exception occurred:
(SDXLModelParallel pid=212978) 
(SDXLModelParallel pid=212978) Traceback (most recent call last):
(SDXLModelParallel pid=212978)   File "/home/ubuntu/sang-dev/ray/python/ray/dag/compiled_dag_node.py", line 1851, in teardown
(SDXLModelParallel pid=212978)     ray.get(cancel_ref, timeout=30)
(SDXLModelParallel pid=212978)   File "/home/ubuntu/sang-dev/ray/python/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
(SDXLModelParallel pid=212978)     return fn(*args, **kwargs)
(SDXLModelParallel pid=212978)   File "/home/ubuntu/sang-dev/ray/python/ray/_private/client_mode_hook.py", line 103, in wrapper
(SDXLModelParallel pid=212978)     return func(*args, **kwargs)
(SDXLModelParallel pid=212978)   File "/home/ubuntu/sang-dev/ray/python/ray/_private/worker.py", line 2664, in get
(SDXLModelParallel pid=212978)     values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
(SDXLModelParallel pid=212978)   File "/home/ubuntu/sang-dev/ray/python/ray/_private/worker.py", line 873, in get_objects
(SDXLModelParallel pid=212978)     raise value
(SDXLModelParallel pid=212978) ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
(SDXLModelParallel pid=212978) 	class_name: BaseModelActor
(SDXLModelParallel pid=212978) 	actor_id: 0169c2ea9a058abbe3f8157a01000000
(SDXLModelParallel pid=212978) 	pid: 213038
(SDXLModelParallel pid=212978) 	namespace: 6b6e8639-5027-438b-adb3-9f4c2760a9be
(SDXLModelParallel pid=212978) 	ip: 172.31.14.211
(SDXLModelParallel pid=212978) The actor is dead because its owner has died. Owner Id: 56eafb30de59323bfb106de740c8e169fa6eae1587c8c683ce54ca71 Owner Ip address: 172.31.14.211 Owner worker exit type: SYSTEM_ERROR Worker exit detail: Owner's node has crashed.
```

this needs to be fixed

### Versions / Dependencies

master

### Reproduction script

```python3
import logging
import time
from io import BytesIO
from typing import Dict

import torch
from ray.dag import InputNode
# from diffusers import DiffusionPipeline
# from PIL import Image

import ray
from ray.experimental.channel.torch_tensor_type import TorchTensorType
# from ray import serve

# Number of inference steps (more steps means higher quality but longer runtime).
NUM_INFERENCE_STEPS = 40
# The split of steps to run on the base vs. refiner models.
DENOISING_SPLIT = 0.8

@ray.remote(num_gpus=1)
class BaseModelActor:
    def __init__(self):
        # self._model = _load_diffusion_pipeline(
        #     "stabilityai/stable-diffusion-xl-base-1.0"
        # ).to("cuda")
        pass

    def predict(self, prompt: str) -> torch.Tensor:
        return torch.tensor([1], device="cpu")


@ray.remote(num_gpus=1)
class RefinerModelActor:
    def __init__(self):
        pass

    def predict(self, prompt: str, image: torch.Tensor):
        image = image.to("cuda")
        return image

@ray.remote
class SDXLModelParallel:
    def __init__(self):
        self._base_actor = BaseModelActor.remote()
        self._refiner_actor = RefinerModelActor.remote()

        with InputNode() as prompt:
            dag = self._refiner_actor.predict.bind(
                prompt,
                self._base_actor.predict.bind(
                    prompt,
                ).with_type_hint(TorchTensorType(transport="nccl")),
            )

        self._adag = dag.experimental_compile(
            enable_asyncio=True,
            _execution_timeout=120,
        )

    async def call(self, prompt: str) -> bytes:
        ref = await self._adag.execute_async(prompt)

        return await ref

from ray.cluster_utils import Cluster

c = Cluster()
c.add_node(num_cpus=2, num_gpus=2)
ray.init()
# c.add_node(num_cpus=1, num_gpus=1)
parallel = SDXLModelParallel.remote()
ray.get(parallel.call.remote("abc"))

```

### Issue Severity

None

**Comment by Bye-legumes** [comment]
HI, I cannot reproduce this and it can run without errors.
