### ISSUE TITLE
[UI] When a Ray worker node dies, it makes Ray dashboard "cluster" page and "logs" page broken

### ISSUE THREAD

**Issue by WeichenXu123** [ray-project/ray#47668]
### What happened + What you expected to happen

When a Ray worker node dies, it makes Ray dashboard "cluster" page and "logs" page broken

Normal "cluster page" containing dead node should be like:
<img width="833" alt="image" src="https://github.com/user-attachments/assets/2131f498-a0be-4219-a7a7-832f38bf4123">

But now it becomes:
<img width="1038" alt="image" src="https://github.com/user-attachments/assets/18196774-d196-493f-9a10-1cf0c2e1af12">

and when Ray worker node dies, "logs" page is completely broken and show nothing.

### Versions / Dependencies

This bug is introduced in Ray nightly build version , Ray 2.35 version is good.

### Reproduction script

1. install Ray nightly build version
2. start a Ray head node like:
```
ray start --head --node-ip-address=127.0.0.1 --port 9988 --dashboard-host=0.0.0.0
```
3. start a Ray worker node like:
```
ray start --address 127.0.0.1:9988 --block &
```
4. Find the Ray worker node processes group, and kill (-9) all processes in the group
```
ps -ef|grep "ray start --address 127.0.0.1:9988"  # Get process id of "ray start --address 127.0.0.1:9988" command
kill -9 -{xxx} # kill the process **group** of id printed in above command
```
5. Wait a few seconds, Open Ray dashboard cluster page. error occurs.

Checking `nodes?view=summary` request response, it got error like:

```
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8ac7e00d-2d10-430a-b39d-ad4447d3a5ed/lib/python3.11/site-packages/ray/dashboard/optional_utils.py", line 224, in _update_cache
    response = task.result()
               ^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8ac7e00d-2d10-430a-b39d-ad4447d3a5ed/lib/python3.11/site-packages/ray/dashboard/modules/node/node_head.py", line 364, in get_all_nodes
    all_node_summary, nodes_logical_resources = await asyncio.gather(
                                                ^^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8ac7e00d-2d10-430a-b39d-ad4447d3a5ed/lib/python3.11/site-packages/ray/dashboard/datacenter.py", line 171, in get_all_node_summary
    return [
           ^
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8ac7e00d-2d10-430a-b39d-ad4447d3a5ed/lib/python3.11/site-packages/ray/dashboard/datacenter.py", line 172, in <listcomp>
    await DataOrganizer.get_node_info(node_id, get_summary=True)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8ac7e00d-2d10-430a-b39d-ad4447d3a5ed/lib/python3.11/site-packages/ray/dashboard/datacenter.py", line 150, in get_node_info
    node_info["status"] = node["stateSnapshot"]["state"]
                          ~~~~^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8ac7e00d-2d10-430a-b39d-ad4447d3a5ed/lib/python3.11/site-packages/ray/dashboard/utils.py", line 435, in __getitem__
    proxy = self._proxy[item] = make_immutable(self._dict[item])
                                               ~~~~~~~~~~^^^^^^
KeyError: 'stateSnapshot'
```

### Issue Severity

None

**Comment by WeichenXu123** [comment]
CC @rkooo567 any ideas ?

**Comment by rkooo567** [comment]
can you share the console log when this happens? Also cc @alanwguo @nikitavemuri

**Comment by WeichenXu123** [comment]
> can you share the console log when this happens? Also cc @alanwguo @nikitavemuri

which log file do you need ? console log shows nothing abnormal.

**Comment by rkooo567** [comment]
I meant the UI log page (assuming there must be an exception there? )

**Comment by WeichenXu123** [comment]
> I meant the UI log page (assuming there must be an exception there? )

no..  nothing displayed, it turns out to be an blank page

**Comment by WeichenXu123** [comment]
This is the console error when loading "logs" page. @rkooo567 any insights ?
<img width="823" alt="image" src="https://github.com/user-attachments/assets/cad06bd3-9159-4eab-8ccf-67e4c1e5bbeb">

**Comment by WeichenXu123** [comment]
This is the error when loading "cluster" page:
<img width="791" alt="image" src="https://github.com/user-attachments/assets/b9eef222-5a16-4622-adb7-d171dfce7841">

**Comment by WeichenXu123** [comment]
@rkooo567 
The HTTP request `nodes?view=summary` failed with error:

```
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8ac7e00d-2d10-430a-b39d-ad4447d3a5ed/lib/python3.11/site-packages/ray/dashboard/optional_utils.py", line 224, in _update_cache
    response = task.result()
               ^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8ac7e00d-2d10-430a-b39d-ad4447d3a5ed/lib/python3.11/site-packages/ray/dashboard/modules/node/node_head.py", line 364, in get_all_nodes
    all_node_summary, nodes_logical_resources = await asyncio.gather(
                                                ^^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8ac7e00d-2d10-430a-b39d-ad4447d3a5ed/lib/python3.11/site-packages/ray/dashboard/datacenter.py", line 171, in get_all_node_summary
    return [
           ^
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8ac7e00d-2d10-430a-b39d-ad4447d3a5ed/lib/python3.11/site-packages/ray/dashboard/datacenter.py", line 172, in <listcomp>
    await DataOrganizer.get_node_info(node_id, get_summary=True)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8ac7e00d-2d10-430a-b39d-ad4447d3a5ed/lib/python3.11/site-packages/ray/dashboard/datacenter.py", line 150, in get_node_info
    node_info["status"] = node["stateSnapshot"]["state"]
                          ~~~~^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8ac7e00d-2d10-430a-b39d-ad4447d3a5ed/lib/python3.11/site-packages/ray/dashboard/utils.py", line 435, in __getitem__
    proxy = self._proxy[item] = make_immutable(self._dict[item])
                                               ~~~~~~~~~~^^^^^^
KeyError: 'stateSnapshot'

```

**Comment by WeichenXu123** [comment]
@anyscalesam  Who should we assign this bug to ? thanks! This is a critical bug I think.

**Comment by jjyao** [comment]
@rynewang it's likely due to the recent dashboard optimizations.

**Comment by jjyao** [comment]
I think it's due to https://github.com/ray-project/ray/pull/47367
