### ISSUE TITLE
[Data] `asyncio` event loop mismatch when using async actors with `map_batches`

### ISSUE THREAD

**Issue by scottjlee** [ray-project/ray#47734]
### What happened + What you expected to happen

When using async actors with `map_batches()` and Python 3.9, this error occurs:
```
RuntimeError: Task <Task pending name='Task-2' coro=<_generate_transform_fn_for_async_map_batches.<locals>.transform_fn.<locals>.process_batch() running at /home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/planner/plan_udf_map_op.py:327> cb=[as_completed.<locals>._on_completion() at /home/ray/anaconda3/lib/python3.9/asyncio/tasks.py:598]> got Future <Future pending> attached to a different loop
```

With Python 3.11, the error does not occur. It's likely because Python 3.11 introduced [multiple improvements to asyncio](https://docs.python.org/3/whatsnew/3.11.html#asyncio), and we need to improve the way we handle the event loop so it works with previous versions of Python.

Currently, the workaround is to use Python 3.11+.

### Versions / Dependencies

Python 3.9, ray 2.35

### Reproduction script

```
async def task_yield(row):
        return row

    class AsyncActor:
        def __init__(self):
            pass

        async def __call__(self, batch):
            rows = [{"id": np.array([i])} for i in batch["id"]]
            tasks = [asyncio.create_task(task_yield(row)) for row in rows]
            for task in tasks:
                yield await task

    n = 8
    ds = ray.data.range(n, override_num_blocks=n)
    ds = ds.map_batches(
        AsyncActor,
        batch_size=n,
        compute=ray.data.ActorPoolStrategy(size=1, max_tasks_in_flight_per_actor=n),
        concurrency=1,
        max_concurrency=n,
    )

    output = ds.take_all()
    expected_output = [{"id": i} for i in range(n)]
    # Because all tasks are submitted almost simultaneously,
    # the output order may be different compared to the original input.
    assert len(output) == len(expected_output), (len(output), len(expected_output))
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by comaniac** [comment]
I've investigated the problem and found a fix. The root cause seems that Ray Data async actor context creates a new event loop even if the UDF `__init__` function already creates one. Here is the script:

```python
import asyncio
import ray

class Runner:
    def __init__(self):
        # self.loop = asyncio.get_event_loop()
        self.queue = asyncio.Queue()#loop=self.loop)
        for _ in range(10):
            self.queue.put_nowait(True)
        print("Runner is initialized", flush=True)

    async def _process(self, val, idx):
        await self.queue.get()
        await asyncio.sleep(0.1)
        self.queue.put_nowait(True)
        return val, idx

    async def start_generate_async(self, batch):
        tasks = []
        print(f"Batch with size {len(batch['id'])}")
        for idx, val in enumerate(batch["id"]):
            tasks.append(
                asyncio.create_task(self._process(val, idx)) #
            )
        return tasks

    async def call_async(self, batch):
        tasks = await self.start_generate_async(batch)
        for t in asyncio.as_completed(tasks): #
            val, idx = await t
            yield {"val": [val], "idx": [idx]}

    async def __call__(self, batch):
        async for x in self.call_async(batch):
            yield x


ray.init()
dataset = ray.data.range(100).repartition(1)
dataset = dataset.map_batches(
    Runner,
    zero_copy_batch=True,
    concurrency=(1, 1),
    batch_size=None,
)
dataset = dataset.materialize()
print(dataset.take(10))
```

Running this script in Python 3.9 with Ray 2.36.0 results in the following error

```
Traceback (most recent call last):
  File "/home/ray/default/temp/test_ray_data_event_loop.py", line 47, in <module>
    dataset = dataset.materialize()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/dataset.py", line 4642, in materialize
    copy._plan.execute()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/exceptions.py", line 89, in handle_trace
    raise e.with_traceback(None) from SystemException()
ray.exceptions.RayTaskError(RuntimeError): ray::MapBatches(Runner)() (pid=80730, ip=10.0.93.61, actor_id=0ab7393fe1ab55dd6f3146da37000000, repr=MapWorker(MapBatches(Runner)))
    yield from _map_task(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 461, in _map_task
    for b_out in map_transformer.apply_transform(iter(blocks), ctx):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_transformer.py", line 392, in __call__
    for data in iter:
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_transformer.py", line 134, in _udf_timed_iter
    output = next(input)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_transformer.py", line 236, in __call__
    yield from self._batch_fn(input, ctx)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/planner/plan_udf_map_op.py", line 359, in transform_fn
    raise out_batch
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/data/_internal/planner/plan_udf_map_op.py", line 329, in process_batch
    async for output_batch in output_batch_iterator:
  File "/home/ray/default/temp/test_ray_data_event_loop.py", line 35, in __call__
    async for x in self.call_async(batch):
  File "/home/ray/default/temp/test_ray_data_event_loop.py", line 31, in call_async
    val, idx = await t
  File "/home/ray/anaconda3/lib/python3.9/asyncio/tasks.py", line 611, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/ray/default/temp/test_ray_data_event_loop.py", line 14, in _process
    await self.queue.get()
  File "/home/ray/anaconda3/lib/python3.9/asyncio/queues.py", line 166, in get
    await getter
RuntimeError: Task <Task pending name='Task-13' coro=<Runner._process() running at /home/ray/default/temp/test_ray_data_event_loop.py:14> cb=[as_completed.<locals>._on_completion() at /home/ray/anaconda3/lib/python3.9/asyncio/tasks.py:598]> got Future <Future pending> attached to a different loop
```

One fix is using existing event loop in `ray/data/_internal/planner/plan_udf_map_op.py`:

```python
from ray._private.utils import get_or_create_event_loop

class _MapActorContext:
    ...

    def _init_async(self):
        # Only used for callable class with async generator `__call__` method.
        # loop = asyncio.new_event_loop()
        loop = get_or_create_event_loop() # <-- Do not create a new event loop if there's one.

        def run_loop():
            asyncio.set_event_loop(loop)
            loop.run_forever()

        thread = Thread(target=run_loop)
        thread.start()
        self.udf_map_asyncio_loop = loop
        self.udf_map_asyncio_thread = thread
```

Meanwhile, it's still not clear to me why `async.new_event_loop()` works in Python 3.11...
