### ISSUE TITLE
[tune] Fail to run tune with pytorch

### ISSUE THREAD

**Issue by Qin-J** [ray-project/ray#4786]
### System information
- **OS Platform and Distribution **: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version **: 0.6.5
- **Python version **: 3.6

### Describe the problem

I am trying to use ray with pytorch following the example of bayesopt_example.py provided by tune. Note that the bayesopt_example.py can run successively. 
I used the function-based API and reporter was conducted within my function.

But, I got a tune error:

### Source code

def trainable_main(config,reporter):    
      args = arg_parse()
      vars(args).update(config)
      .....(run my model)
      reporter(neg_mean_loss=neg_mean_loss)

if __name__ == "__main__":
 
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--smoke-test", action="store_true", help="Finish quickly for testing")
    args, _ = parser.parse_known_args()
    ray.shutdown()
    ray.init()

    space = {"lr": (0.0001, 0.01), "dropout": (0.1, 0.9)}

    config = {
        "num_samples": 10 if args.smoke_test else 10,
        "stop": {
            "training_iteration": 2
        },
        "resources_per_trial": {
                "cpu": 0,
                "gpu": 1
        }
    }
    algo = BayesOptSearch(
        space,
        max_concurrent=4,
        reward_attr="neg_mean_loss",
        utility_kwargs={
            "kind": "ucb",
            "kappa": 2.5,
            "xi": 0.0
        })
    scheduler = AsyncHyperBandScheduler(reward_attr="neg_mean_loss")
    run(trainable_main,
        name="my_exp",
        search_alg=algo,
        scheduler=scheduler,
        **config)
### error log

2019-05-15 10:31:53,733 WARNING worker.py:1337 -- WARNING: Not updating worker name since `setproctitle` is not installed. Install this with `pip install setproctitle` (or ray[debug]) to enable monitoring of worker processes.
2019-05-15 10:31:53,734 INFO node.py:469 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-05-15_10-31-53_2668/logs.
2019-05-15 10:31:53,889 INFO services.py:407 -- Waiting for redis server at 127.0.0.1:41813 to respond...
2019-05-15 10:31:54,079 INFO services.py:407 -- Waiting for redis server at 127.0.0.1:22652 to respond...
2019-05-15 10:31:54,087 INFO services.py:804 -- Starting Redis shard with 6.74 GB max memory.
2019-05-15 10:31:54,230 INFO node.py:483 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-05-15_10-31-53_2668/logs.
2019-05-15 10:31:54,231 INFO services.py:1427 -- Starting the Plasma object store with 10.11 GB memory using /dev/shm.
2019-05-15 10:31:54,690 INFO tune.py:60 -- Tip: to resume incomplete experiments, pass resume='prompt' or resume=True to run()
2019-05-15 10:31:54,692 INFO tune.py:211 -- Starting a new experiment.
== Status ==
Using AsyncHyperBand: num_stopped=0
Bracket: Iter 90.000: None | Iter 30.000: None | Iter 10.000: None
Bracket: Iter 90.000: None | Iter 30.000: None
Bracket: Iter 90.000: None
Resources requested: 0/8 CPUs, 0/1 GPUs
Memory usage on this node: 12.7/33.7 GB

== Status ==
Using AsyncHyperBand: num_stopped=0
Bracket: Iter 90.000: None | Iter 30.000: None | Iter 10.000: None
Bracket: Iter 90.000: None | Iter 30.000: None
Bracket: Iter 90.000: None
Resources requested: 0/8 CPUs, 1/1 GPUs
Memory usage on this node: 12.7/33.7 GB
Result logdir: /home/qinjian/ray_results/my_exp
Number of trials: 4 ({'RUNNING': 1, 'PENDING': 3})
PENDING trials:
 - trainable_main_2_dropout=0.10009,lr=0.0030931:       PENDING
 - trainable_main_3_dropout=0.2174,lr=0.0010142:        PENDING
 - trainable_main_4_dropout=0.24901,lr=0.0035211:       PENDING
RUNNING trials:
 - trainable_main_1_dropout=0.43362,lr=0.0072312:       RUNNING

(pid=10879) usage: default_worker.py [-h] [--dataset DATASET] [--bmname BMNAME]
(pid=10879)                          [--pkl PKL_FNAME] [--assign-ratio ASSIGN_RATIO]
(pid=10879)                          [--num-pool NUM_POOL] [--linkpred]
(pid=10879)                          [--datadir DATADIR] [--logdir LOGDIR] [--cuda CUDA]
(pid=10879)                          [--max-nodes MAX_NODES] [--lr LR] [--clip CLIP]
(pid=10879)                          [--batch-size BATCH_SIZE] [--epochs NUM_EPOCHS]
(pid=10879)                          [--train-ratio TRAIN_RATIO]
(pid=10879)                          [--num_workers NUM_WORKERS] [--feature FEATURE_TYPE]
(pid=10879)                          [--input-dim INPUT_DIM] [--hidden-dim HIDDEN_DIM]
(pid=10879)                          [--output-dim OUTPUT_DIM] [--num-classes NUM_CLASSES]
(pid=10879)                          [--num-gc-layers NUM_GC_LAYERS] [--nobn]
(pid=10879)                          [--dropout DROPOUT] [--nobias] [--method METHOD]
(pid=10879)                          [--name-suffix NAME_SUFFIX]
(pid=10879) default_worker.py: error: unrecognized arguments: --node-ip-address=172.20.10.7 --object-store-name=/tmp/ray/session_2019-05-15_10-31-53_2668/sockets/plasma_store --raylet-name=/tmp/ray/session_2019-05-15_10-31-53_2668/sockets/raylet --redis-address=172.20.10.7:41813 --temp-dir=/tmp/ray/session_2019-05-15_10-31-53_2668
2019-05-15 10:31:57,573 ERROR trial_runner.py:494 -- Error processing event.
Traceback (most recent call last):
  File "/home/qinjian/anaconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 443, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/qinjian/anaconda3/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 315, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/qinjian/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 2193, in get
    raise value
ray.exceptions.RayTaskError: ray_worker (pid=10879, host=qinjian-MS-7A72)
  File "/home/qinjian/anaconda3/lib/python3.6/site-packages/ray/tune/trainable.py", line 151, in train
    result = self._train()
  File "/home/qinjian/anaconda3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 203, in _train
    ("Wrapped function ran until completion without reporting "
ray.tune.error.TuneError: Wrapped function ran until completion without reporting results or raising an exception.

**Comment by richardliaw** [comment]
Can you move the `arg_parse()` out of the function?

```
args = arg_parse()

def trainable_main(config,reporter):
    vars(args).update(config)
    .....(run my model)
    reporter(neg_mean_loss=neg_mean_loss)

**Comment by Qin-J** [comment]
> Can you move the `arg_parse()` out of the function?
> 
> ```
> args = arg_parse()
> 
> def trainable_main(config,reporter):
>     vars(args).update(config)
>     .....(run my model)
>     reporter(neg_mean_loss=neg_mean_loss)
> ```



> Can you move the `arg_parse()` out of the function?
> 
> ```
> args = arg_parse()
> 
> def trainable_main(config,reporter):
>     vars(args).update(config)
>     .....(run my model)
>     reporter(neg_mean_loss=neg_mean_loss)
> ```

Ok, it can work after moving the arg_parse() out of the function. Thanks a lot.

**Comment by Qin-J** [comment]
Hi, it can work when I move the arg_parse() out of the function. 
But I got another tune error as follow:

(pid=26176) Method: base
(pid=26176) Epoch:  0
(pid=26176) Avg loss:  tensor(0.8411, device='cuda:0', grad_fn=<DivBackward0>) ; epoch time:  2.4136500358581543
(pid=26176) Train  accuracy: 0.8671875 merge accuracy: 0.860655737704918
(pid=26176) Validation  accuracy: 0.8333333333333334 merge accuracy: 0.8333333333333334
(pid=26176) Best val result:  {'epoch': 0, 'loss': tensor(0.8411, device='cuda:0', grad_fn=<DivBackward0>), 'acc': 0.8333333333333334, 'merge_acc': 0.8333333333333334}
(pid=26176) Epoch:  1
(pid=26176) Avg loss:  tensor(0.3534, device='cuda:0', grad_fn=<DivBackward0>) ; epoch time:  2.402681350708008
(pid=26176) Train  accuracy: 0.9609375 merge accuracy: 0.9672131147540983
2019-05-16 23:51:32,562 ERROR trial_runner.py:494 -- Error processing event.
Traceback (most recent call last):
  File "/home/qinjian/anaconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 460, in _process_trial
    trial.trial_id, result=result)
  File "/home/qinjian/anaconda3/lib/python3.6/site-packages/ray/tune/suggest/bayesopt.py", line 88, in on_trial_complete
    target=result[self._reward_attr])
  File "/home/qinjian/anaconda3/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 104, in register
    self._space.register(params, target)
  File "/home/qinjian/anaconda3/lib/python3.6/site-packages/bayes_opt/target_space.py", line 161, in register
    raise KeyError('Data point {} is not unique'.format(x))
KeyError: 'Data point [9.e-01 1.e-04] is not unique'
2019-05-16 23:51:32,563 INFO ray_trial_executor.py:179 -- Destroying actor for trial TRAIN_FN_7_dropout=0.9,lr=0.0001. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
Result for TRAIN_FN_7_dropout=0.9,lr=0.0001:
  date: 2019-05-16_23-51-32
  done: false
  experiment_id: 5706cf77df7b45e988c56272b04e11df
  hostname: qinjian-MS-7A72
  iterations_since_restore: 1
  neg_mean_loss: -0.7224830917874396
  node_ip: 172.20.10.7
  pid: 26176
  time_since_restore: 92.93172073364258
  time_this_iter_s: 92.93172073364258
  time_total_s: 92.93172073364258
  timestamp: 1558021892
  timesteps_since_restore: 0
  training_iteration: 1
  
== Status ==
Using AsyncHyperBand: num_stopped=0
Bracket: Iter 90.000: None | Iter 30.000: None | Iter 10.000: None
Bracket: Iter 90.000: None | Iter 30.000: None
Bracket: Iter 90.000: None
Resources requested: 0/8 CPUs, 1/1 GPUs
Memory usage on this node: 13.5/33.7 GB
Result logdir: /home/qinjian/ray_results/my_exp
Number of trials: 10 ({'TERMINATED': 6, 'RUNNING': 1, 'PENDING': 3})
PENDING trials:
 - TRAIN_FN_8_dropout=0.9,lr=0.0001:    PENDING
 - TRAIN_FN_9_dropout=0.69429,lr=0.0001:        PENDING
 - TRAIN_FN_10_dropout=0.69424,lr=0.01: PENDING
RUNNING trials:
 - TRAIN_FN_7_dropout=0.9,lr=0.0001:    RUNNING, [0 CPUs, 1 GPUs], [pid=26176], 92 s, 1 iter
TERMINATED trials:
 - TRAIN_FN_1_dropout=0.43362,lr=0.0072312:     TERMINATED, [0 CPUs, 1 GPUs], [pid=26177], 98 s, 1 iter
 - TRAIN_FN_2_dropout=0.10009,lr=0.0030931:     TERMINATED, [0 CPUs, 1 GPUs], [pid=26178], 92 s, 1 iter
 - TRAIN_FN_3_dropout=0.2174,lr=0.0010142:      TERMINATED, [0 CPUs, 1 GPUs], [pid=26179], 95 s, 1 iter
 - TRAIN_FN_4_dropout=0.24901,lr=0.0035211:     TERMINATED, [0 CPUs, 1 GPUs], [pid=26174], 94 s, 1 iter
 - TRAIN_FN_5_dropout=0.9,lr=0.0001:    TERMINATED, [0 CPUs, 1 GPUs], [pid=26266], 92 s, 1 iter
 - TRAIN_FN_6_dropout=0.1,lr=0.01:      TERMINATED, [0 CPUs, 1 GPUs], [pid=26175], 93 s, 1 iter

(pid=26176) Validation  accuracy: 0.7777777777777778 merge accuracy: 0.7777777777777778
(pid=26176) Best val result:  {'epoch': 0, 'loss': tensor(0.8411, device='cuda:0', grad_fn=<DivBackward0>), 'acc': 0.8333333333333334, 'merge_acc': 0.8333333333333334}
(pid=26176) final acc is 0.722483 , final merge acc is 0.716667
(pid=26173) CUDA 0
Traceback (most recent call last):

  File "<ipython-input-32-2f568d114ad4>", line 1, in <module>
    runfile('/media/qinjian/8f01f63b-1d1f-498f-8f5e-a21eefef8758/code/graph_convolutional_network/diffpool-master/train_fmridata_tune_hyperparams.py', wdir='/media/qinjian/8f01f63b-1d1f-498f-8f5e-a21eefef8758/code/graph_convolutional_network/diffpool-master', post_mortem=True)

  File "/home/qinjian/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "/home/qinjian/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/media/qinjian/8f01f63b-1d1f-498f-8f5e-a21eefef8758/code/graph_convolutional_network/diffpool-master/train_fmridata_tune_hyperparams.py", line 636, in <module>
    **config)

  File "/home/qinjian/anaconda3/lib/python3.6/site-packages/ray/tune/tune.py", line 235, in run
    runner.step()

  File "/home/qinjian/anaconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 273, in step
    self._process_events()  # blocking

  File "/home/qinjian/anaconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 437, in _process_events
    trial = self.trial_executor.get_next_available_trial()  # blocking

  File "/home/qinjian/anaconda3/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 291, in get_next_available_trial
    [result_id], _ = ray.wait(shuffled_results)

  File "/home/qinjian/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 2313, in wait
    worker.current_task_id,

  File "python/ray/_raylet.pyx", line 268, in ray._raylet.RayletClient.wait

  File "python/ray/_raylet.pyx", line 59, in ray._raylet.check_status

Exception: [RayletClient] Raylet connection closed.

**Comment by richardliaw** [comment]
This looks like a BayesOpt error. Can you try taking a look if there's any
issues listed on the package issue tracker?

**Comment by richardliaw** [comment]
Closing this issue because looks like the error is a BayesOpt error "KeyError: 'Data point [9.e-01 1.e-04] is not unique'".
