### ISSUE TITLE
[RLlib] ModuleNotFoundError: No module named 'numpy._core.numeric'

### ISSUE THREAD

**Issue by fridary** [ray-project/ray#48053]
### What happened + What you expected to happen

The problem is about numpy version when I do checkpoints restore on model. On numpy>=2.0.0 works, but on numpy<2.0.0 this error.
How to fix for numpy v1 latest that is 1.26.4? Here it says https://github.com/ray-project/ray/blob/master/python/requirements.txt numpy>=1.20, but it works only >=2.0.0. I can not use >=2.0.0, because of a lot of another libs that load my script are on 1.26.4
```
Traceback (most recent call last):
  File "/Users/fridary/Library/Mobile Documents/com~apple~CloudDocs/python/test3.py", line 94, in <module>
    main()
  File "/Users/fridary/Library/Mobile Documents/com~apple~CloudDocs/python/test3.py", line 85, in main
    my_new_ppo.restore("temp/ray_checkpoint")
  File "/Users/fridary/miniforge3/envs/test/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 575, in restore
    self.load_checkpoint(checkpoint_dir)
  File "/Users/fridary/miniforge3/envs/test/lib/python3.11/site-packages/ray/rllib/algorithms/algorithm.py", line 2763, in load_checkpoint
    checkpoint_data = Algorithm._checkpoint_info_to_algorithm_state(checkpoint_info)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fridary/miniforge3/envs/test/lib/python3.11/site-packages/ray/rllib/algorithms/algorithm.py", line 3522, in _checkpoint_info_to_algorithm_state
    worker_state["policy_states"][pid] = pickle.load(f)
                                         ^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'numpy._core.numeric'
```

### Versions / Dependencies

OS: Ubuntu
Python: 3.11.9
ray: 2.37.0 (pip install ray[rllib])
numpy: 1.26.4

### Reproduction script

```python
from ray.rllib.algorithms.algorithm import Algorithm
my_new_ppo = Algorithm.from_checkpoint("temp/ray_checkpoint")
```
OR the same error:
```python
select_env = "stock-v1"
register_env(select_env, lambda config: TestEnv())

config = (
    PPOConfig()
    .framework("torch")
    .api_stack(
        enable_rl_module_and_learner=False,
        enable_env_runner_and_connector_v2=False,
    )
    .environment(
        env=select_env,
    )
)

my_new_ppo = config.build()
my_new_ppo.restore("temp/ray_checkpoint")
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by fridary** [comment]
Hello. So it's unfixed?
