### ISSUE TITLE
Error starting cluster on 0.7.0

### ISSUE THREAD

**Issue by jheffez** [ray-project/ray#4811]
I'm a newbie to ray. Getting the error below while starting a new cluster.
Running ubuntu 18, python 3.6.8
Installed the latest 0.7 code via `pip install  https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.7.0-cp36-cp36m-manylinux1_x86_64.whl
`

settings.yaml:
cluster_name: default
min_workers: 0
max_workers: 0
initial_workers: 0
autoscaling_mode: default
docker:
            image: ""
                container_name: ""
target_utilization_fraction: 0.8
idle_timeout_minutes: 5
provider:
  type: local
  head_ip: 10.0.0.20
  worker_ips: []
auth:
  ssh_user: YOUR_USERNAME
  ssh_private_key: ~/.ssh/id_rsa
head_node: {}
worker_nodes: {}
file_mounts: {}
setup_commands: []
head_setup_commands: []
worker_setup_commands: []
setup_commands:
  - source activate ray && pip install -U ray
head_start_ray_commands:
  - source activate ray && ray stop
  - source activate ray && ulimit -c unlimited && ray start --head --redis-port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml
worker_start_ray_commands:
  - source activate ray && ray stop
  - source activate ray && ray start --redis-address=$RAY_HEAD_IP:6379

`(tf2) root@BONGO:/home/jake/py/files# ray up settings.yaml
/home/jake/py/tf2/lib/python3.6/site-packages/ray/autoscaler/commands.py:38: YAMLLoadWarning: calling yaml.l
oad() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/
load for full details.
  config = yaml.load(open(config_file).read())
/home/jake/py/tf2/lib/python3.6/site-packages/ray/autoscaler/node_provider.py:115: YAMLLoadWarning: calling
yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyam
l.org/load for full details.
  defaults = yaml.load(f)
2019-05-17 11:44:23,030 INFO node_provider.py:34 -- ClusterState: Loaded cluster state: {'10.0.0.20': {'tags
': {'ray-node-type': 'head', 'ray-launch-config': '5a0ccc99d6349f2fb9699284ae2a3547c548975f', 'ray-node-name
': 'ray-default-head'}, 'state': 'running'}}
2019-05-17 11:44:23,031 INFO node_provider.py:59 -- ClusterState: Writing cluster state: {'10.0.0.20': {'tag
s': {'ray-node-type': 'head', 'ray-launch-config': '5a0ccc99d6349f2fb9699284ae2a3547c548975f', 'ray-node-nam
e': 'ray-default-head'}, 'state': 'running'}}
This will restart cluster services [y/N]: y
2019-05-17 11:44:32,617 INFO commands.py:202 -- get_or_create_head_node: Updating files on head node...
Traceback (most recent call last):
  File "/home/jake/py/tf2/bin/ray", line 10, in <module>
    sys.exit(main())
  File "/home/jake/py/tf2/lib/python3.6/site-packages/ray/scripts/scripts.py", line 771, in main
    return cli()
  File "/home/jake/py/tf2/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jake/py/tf2/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jake/py/tf2/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jake/py/tf2/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jake/py/tf2/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jake/py/tf2/lib/python3.6/site-packages/ray/scripts/scripts.py", line 462, in create_or_update    no_restart, restart_only, yes, cluster_name)
  File "/home/jake/py/tf2/lib/python3.6/site-packages/ray/autoscaler/commands.py", line 47, in create_or_update_cluster
    override_cluster_name)
  File "/home/jake/py/tf2/lib/python3.6/site-packages/ray/autoscaler/commands.py", line 241, in get_or_create_head_node
    initialization_commands=config["initialization_commands"],
KeyError: 'initialization_commands'`

**Comment by robertnishihara** [comment]
I don't think this should be necessary, but can you try adding a line like `initialization_commands: []` to your config?

**Comment by jheffez** [comment]
@robertnishihara, that fixed the issue. Thanks.
