### ISSUE TITLE
Unable to connect a node

### ISSUE THREAD

**Issue by jheffez** [ray-project/ray#4818]
Running `ray.init(redis_address="10.0.0.4:6379")` errors:
`WARNING services.py:142 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?`

PC1 is the head. PC2 is the node where I run the python code. I am able to see both PC1 node and PC2 on the webgui. Also ran telnet from PC2 to PC1 on ports 6379, 6380, 12345, 12346, all respond. Using latest ray 0.7.0, Python 3.6.8, ubuntu 18 - firewall disabled.

PC1(head): 
(tf2) root@ubuntu1:/home/jake/py# `ray start --head --redis-port=6379 --redis-shard-ports=6380  --node-manager-port=12345 --object-manager-port=12346 --include-webui`

2019-05-18 15:22:56,027 INFO scripts.py:289 -- Using IP address 10.0.0.4 for this node.
2019-05-18 15:22:56,028 INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-05-18_15-22-56_027885_17361/logs.
2019-05-18 15:22:56,144 INFO services.py:409 -- Waiting for redis server at 127.0.0.1:6379 to respond...
2019-05-18 15:22:56,282 INFO services.py:409 -- Waiting for redis server at 127.0.0.1:6380 to respond...
2019-05-18 15:22:56,293 INFO services.py:806 -- Starting Redis shard with 0.41 GB max memory.

==============================================================
View the dashboard at http://10.0.0.4:8080/?token=9883889860827cdd1b266d44bb9860cb5678e8b237f37aa===================

2019-05-18 15:22:56,558 INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-05-18_15-22-56_027885_17361/logs.
2019-05-18 15:22:56,560 INFO services.py:1442 -- Starting the Plasma object store with 0.62 GB memory using /dev/shm.
2019-05-18 15:22:56,602 INFO scripts.py:319 --
Started Ray on this node. You can add additional nodes to the cluster by calling

    ray start --redis-address 10.0.0.4:6379

from the node you wish to add. You can connect a driver to the cluster from Python by running

    import ray
    ray.init(redis_address="10.0.0.4:6379")

PC2:
(tf2) root@Meshy:/home/jake/py/files# `ray start --redis-address 10.0.0.4:6379`
2019-05-18 15:56:50,917 INFO services.py:409 -- Waiting for redis server at 10.0.0.4:6379 to respond...
2019-05-18 15:56:50,949 INFO scripts.py:363 -- Using IP address 10.0.0.50 for this node.
2019-05-18 15:56:50,968 INFO node.py:511 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-05-18_15-22-56_027885_17361/logs.
2019-05-18 15:56:50,974 INFO services.py:1441 -- Starting the Plasma object store with 1.25 GB memory using /dev/shm.
2019-05-18 15:56:51,099 INFO scripts.py:371 --
Started Ray on this node. If you wish to terminate the processes that have been started, run

    ray stop
(tf2) root@Meshy:/home/jake/py/files# python
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init(redis_address="10.0.0.4:6379")
2019-05-18 15:57:37,358 WARNING services.py:142 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2019-05-18 15:57:38,367 WARNING services.py:142 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2019-05-18 15:57:39,386 WARNING services.py:142 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2019-05-18 15:57:40,399 WARNING services.py:142 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2019-05-18 15:57:41,413 WARNING services.py:142 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jake/py/tf2/lib/python3.6/site-packages/ray/worker.py", line 1446, in init
    ray_params, head=False, shutdown_at_exit=False, connect_only=True)
  File "/home/jake/py/tf2/lib/python3.6/site-packages/ray/node.py", line 120, in __init__
    redis_password=self.redis_password)
  File "/home/jake/py/tf2/lib/python3.6/site-packages/ray/services.py", line 135, in get_address_info_from_redis
    redis_address, node_ip_address, redis_password=redis_password)
  File "/home/jake/py/tf2/lib/python3.6/site-packages/ray/services.py", line 119, in get_address_info_from_redis_helper
    "Redis has started but no raylets have registered yet.")
Exception: Redis has started but no raylets have registered yet.

**Comment by jheffez** [comment]
After some spending a day it seems networking related. Was using Windows 10 with Ubuntu running via WSL. After installing 2 Vmware VM's was able to cluster and run a simple task. 
I wish there was a simpler way. If the agent nodes when they come up do networking verification pass. I can attest that will save lots of time trying to figure out where the issue is..
