### ISSUE TITLE
Error starting node: The argument None must be a bytes object

### ISSUE THREAD

**Issue by jarlva** [ray-project/ray#4830]
Running the command: `ray start --redis-address <ip>:6379`
running on local Windows 10 WS/ubuntu/Python 3.6.7/Ray 0.7.0

Error:
`2019-05-21 12:36:33,246 INFO services.py:409 -- Waiting for redis server at 78.141.11.11:6379 to respond...
2019-05-21 12:36:33,598 INFO scripts.py:363 -- Using IP address 10.0.0.20 for this node.
Traceback (most recent call last):
  File "/home/jake/py/conda/bin/ray", line 10, in <module>
    sys.exit(main())
  File "/home/jake/py/conda/lib/python3.6/site-packages/ray/scripts/scripts.py", line 771, in main
    return cli()
  File "/home/jake/py/conda/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jake/py/conda/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jake/py/conda/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jake/py/conda/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jake/py/conda/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jake/py/conda/lib/python3.6/site-packages/ray/scripts/scripts.py", line 370, in start
    node = ray.node.Node(ray_params, head=False, shutdown_at_exit=False)
  File "/home/jake/py/conda/lib/python3.6/site-packages/ray/node.py", line 102, in __init__
    redis_client.get("session_name"))
  File "/home/jake/py/conda/lib/python3.6/site-packages/ray/utils.py", line 177, in decode
    "The argument {} must be a bytes object.".format(byte_str))
ValueError: The argument None must be a bytes object.`

**Comment by robertnishihara** [comment]
What address are you using for `<ip>`? Also, did you run `ray start --head --redis-port=6379`? If so, what was the output from that command?

**Comment by jheffez** [comment]
It's the head's IP. 
Today I tried again after rebooting Windows and the error is gone. What I do notice a lot  though, on Windows WSL/ubuntu when I run `ray start --redis-address` all seems fine but the node does not even registers on the remote head webgui. Windows/WSL can only run Ray locally.

What I'm trying to say is that `ray start --redis-address` thinks all is fine when it's not. It could definitely use network/sanity checks at startup to avoid falls positives. 

```

(base) jake@BONGO:/mnt/c/Users/Jake$ ray start --redis-address 78.141.207.129:6379
2019-05-23 10:11:08,051 INFO services.py:409 -- Waiting for redis server at 78.141.207.129:6379 to respond...
2019-05-23 10:11:08,370 INFO scripts.py:363 -- Using IP address 10.0.0.20 for this node.
2019-05-23 10:11:08,934 INFO node.py:511 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-05-23_09-44-57_372914_1039/logs.
2019-05-23 10:11:08,947 INFO services.py:1441 -- Starting the Plasma object store with 2.55 GB memory using /dev/shm.
2019-05-23 10:11:09,145 INFO scripts.py:371 --
Started Ray on this node. If you wish to terminate the processes that have been started, run

    ray stop
```
