### ISSUE TITLE
[Ray Train]  Ray is not graceful shut down after training

### ISSUE THREAD

**Issue by lxmanutd** [ray-project/ray#48441]
### What happened + What you expected to happen

1. Using pytorch+ray+multiworker, after training finished, ray is not gracefully shutdown and EOFError reported, and seems this issue is not permenant and occured occasionally.
2. What expected to happen: no EOFFrror reported after training finished.
3. logs:
(RayTrainWorker pid=232258, ip=10.222.41.165) tempfile.TemporaryDirectory(): /tmp/tmpo5ea8via
(RayTrainWorker pid=232258, ip=10.222.41.165) saving checkpoint: epoch: 9
Test Epoch 9: 100%|██████████| 313/313 [00:01<00:00, 201.86it/s]
(RayTrainWorker pid=232258, ip=10.222.41.165) Checkpoint successfully created at: Checkpoint(filesystem=local, path=/data/mlops/training/saves/llama3-8b/lora/pytorch/TorchTrainer_2024-10-29_11-09-45/TorchTrainer_433bd_00000_0_2024-10-29_11-09-51/checkpoint_000002)
Test Epoch 9:  94%|█████████▍| 295/313 [00:01<00:00, 205.95it/s]
(RayTrainWorker pid=249147, ip=10.222.41.168) tempfile.TemporaryDirectory(): /tmp/tmpv892rykk
(RayTrainWorker pid=249147, ip=10.222.41.168) saving checkpoint: epoch: 9
(RayTrainWorker pid=249147, ip=10.222.41.168) _get_session().report
(RayTrainWorker pid=249147, ip=10.222.41.168) checkpoint is: Checkpoint(filesystem=local, path=/tmp/tmpv892rykk)
(RayTrainWorker pid=249147, ip=10.222.41.168) self.current_checkpoint_index: 2
(RayTrainWorker pid=249147, ip=10.222.41.168) create_dir: /data/mlops/training/saves/llama3-8b/lora/pytorch/TorchTrainer_2024-10-29_11-09-45/TorchTrainer_433bd_00000_0_2024-10-29_11-09-51/checkpoint_000002
(RayTrainWorker pid=249147, ip=10.222.41.168) _pyarrow_fs_copy_files.
(RayTrainWorker pid=249147, ip=10.222.41.168) _pyarrow_fs_copy_files done!
(RayTrainWorker pid=249147, ip=10.222.41.168) persisted_checkpoint is: Checkpoint(filesystem=local, path=/data/mlops/training/saves/llama3-8b/lora/pytorch/TorchTrainer_2024-10-29_11-09-45/TorchTrainer_433bd_00000_0_2024-10-29_11-09-51/checkpoint_000002)
(RayTrainWorker pid=249147, ip=10.222.41.168) _TrainingResult is: TrainingResult(checkpoint=Checkpoint(filesystem=local, path=/data/mlops/training/saves/llama3-8b/lora/pytorch/TorchTrainer_2024-10-29_11-09-45/TorchTrainer_433bd_00000_0_2024-10-29_11-09-51/checkpoint_000002), metrics={'loss': 0.3230949372653169, 'accuracy': 0.8788, 'timestamp': 1730171464, 'checkpoint_dir_name': 'checkpoint_000002'})
Test Epoch 9: 100%|██████████| 313/313 [00:01<00:00, 211.03it/s]
(RayTrainWorker pid=249147, ip=10.222.41.168) Copying checkpoint files to storage path:
(RayTrainWorker pid=249147, ip=10.222.41.168) (<pyarrow._fs.LocalFileSystem object at 0xfff97dd3ccf0>, /tmp/tmpv892rykk) -> (<pyarrow._fs.LocalFileSystem object at 0xfff9fa54d3b0>, /data/mlops/training/saves/llama3-8b/lora/pytorch/TorchTrainer_2024-10-29_11-09-45/TorchTrainer_433bd_00000_0_2024-10-29_11-09-51/checkpoint_000002)
(RayTrainWorker pid=249147, ip=10.222.41.168) Checkpoint successfully created at: Checkpoint(filesystem=local, path=/data/mlops/training/saves/llama3-8b/lora/pytorch/TorchTrainer_2024-10-29_11-09-45/TorchTrainer_433bd_00000_0_2024-10-29_11-09-51/checkpoint_000002)
(RayTrainWorker pid=221255, ip=10.222.16.35) tempfile.TemporaryDirectory(): /tmp/tmpe_yf5inj
(RayTrainWorker pid=221255, ip=10.222.16.35) saving checkpoint: epoch: 9
Test Epoch 9: 100%|██████████| 313/313 [00:01<00:00, 202.36it/s]
(RayTrainWorker pid=221255, ip=10.222.16.35) Checkpoint successfully created at: Checkpoint(filesystem=local, path=/data/mlops/training/saves/llama3-8b/lora/pytorch/TorchTrainer_2024-10-29_11-09-45/TorchTrainer_433bd_00000_0_2024-10-29_11-09-51/checkpoint_000002)
(TunerInternal pid=393094) 
(TunerInternal pid=393094) Training finished iteration 3 at 2024-10-29 11:11:04. Total running time: 1min 13s
(TunerInternal pid=393094) ╭─────────────────────────────────────────╮
(TunerInternal pid=393094) │ Training result                         │
(TunerInternal pid=393094) ├─────────────────────────────────────────┤
(TunerInternal pid=393094) │ checkpoint_dir_name   checkpoint_000002 │
(TunerInternal pid=393094) │ time_this_iter_s               14.27219 │
(TunerInternal pid=393094) │ time_total_s                   66.14097 │
(TunerInternal pid=393094) │ training_iteration                    3 │
(TunerInternal pid=393094) │ accuracy                          0.882 │
(TunerInternal pid=393094) │ loss                            0.34504 │
(TunerInternal pid=393094) ╰─────────────────────────────────────────╯
(TunerInternal pid=393094) Training saved a checkpoint for iteration 3 at: (local)/data/mlops/training/saves/llama3-8b/lora/pytorch/TorchTrainer_2024-10-29_11-09-45/TorchTrainer_433bd_00000_0_2024-10-29_11-09-51/checkpoint_000002
(RayTrainWorker pid=240648, ip=10.222.16.33) tempfile.TemporaryDirectory(): /tmp/tmpzfp2nsh_
(RayTrainWorker pid=240648, ip=10.222.16.33) saving checkpoint: epoch: 9
Test Epoch 9: 100%|██████████| 313/313 [00:01<00:00, 206.81it/s]
(RayTrainWorker pid=240648, ip=10.222.16.33) Checkpoint successfully created at: Checkpoint(filesystem=local, path=/data/mlops/training/saves/llama3-8b/lora/pytorch/TorchTrainer_2024-10-29_11-09-45/TorchTrainer_433bd_00000_0_2024-10-29_11-09-51/checkpoint_000002)
(TunerInternal pid=393094) 
(TunerInternal pid=393094) Training completed after 3 iterations at 2024-10-29 11:11:05. Total running time: 1min 14s
(TunerInternal pid=393094) 
(TunerInternal pid=393094) Wrote the latest version of all result files and experiment state to '/data/mlops/training/saves/llama3-8b/lora/pytorch/TorchTrainer_2024-10-29_11-09-45' in 0.0057s.
Training result: Result(
  metrics={'loss': 0.34504203209593987, 'accuracy': 0.882},
  path='/data/mlops/training/saves/llama3-8b/lora/pytorch/TorchTrainer_2024-10-29_11-09-45/TorchTrainer_433bd_00000_0_2024-10-29_11-09-51',
  filesystem='local',
  checkpoint=Checkpoint(filesystem=local, path=/data/mlops/training/saves/llama3-8b/lora/pytorch/TorchTrainer_2024-10-29_11-09-45/TorchTrainer_433bd_00000_0_2024-10-29_11-09-51/checkpoint_000002)
)
(RayTrainWorker pid=240648, ip=10.222.16.33) Process ForkServerProcess-7:
(RayTrainWorker pid=240648, ip=10.222.16.33) Process ForkServerProcess-6:
(RayTrainWorker pid=240648, ip=10.222.16.33) Process ForkServerProcess-5:
(RayTrainWorker pid=240648, ip=10.222.16.33) Process ForkServerProcess-4:
(RayTrainWorker pid=240648, ip=10.222.16.33) Process ForkServerProcess-8:
(RayTrainWorker pid=240648, ip=10.222.16.33) Process ForkServerProcess-3:
(RayTrainWorker pid=240648, ip=10.222.16.33) Process ForkServerProcess-2:
(RayTrainWorker pid=240648, ip=10.222.16.33) Process ForkServerProcess-9:
(RayTrainWorker pid=240648, ip=10.222.16.33) Traceback (most recent call last):
(RayTrainWorker pid=240648, ip=10.222.16.33) Traceback (most recent call last):
(RayTrainWorker pid=240648, ip=10.222.16.33) Traceback (most recent call last):
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
(RayTrainWorker pid=240648, ip=10.222.16.33)     self.run()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 108, in run
(RayTrainWorker pid=240648, ip=10.222.16.33)     self._target(*self._args, **self._kwargs)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 65, in wrapper
(RayTrainWorker pid=240648, ip=10.222.16.33)     raise exp
(RayTrainWorker pid=240648, ip=10.222.16.33) Traceback (most recent call last):
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 62, in wrapper
(RayTrainWorker pid=240648, ip=10.222.16.33)     func(*args, **kwargs)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
(RayTrainWorker pid=240648, ip=10.222.16.33)     self.run()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 262, in task_distribute
(RayTrainWorker pid=240648, ip=10.222.16.33)     key, func_name, detail = resource_proxy[TASK_QUEUE].get()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 108, in run
(RayTrainWorker pid=240648, ip=10.222.16.33)     self._target(*self._args, **self._kwargs)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "<string>", line 2, in get
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 65, in wrapper
(RayTrainWorker pid=240648, ip=10.222.16.33)     raise exp
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
(RayTrainWorker pid=240648, ip=10.222.16.33)     kind, result = conn.recv()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
(RayTrainWorker pid=240648, ip=10.222.16.33)     self.run()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 62, in wrapper
(RayTrainWorker pid=240648, ip=10.222.16.33)     func(*args, **kwargs)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 250, in recv
(RayTrainWorker pid=240648, ip=10.222.16.33)     buf = self._recv_bytes()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 108, in run
(RayTrainWorker pid=240648, ip=10.222.16.33)     self._target(*self._args, **self._kwargs)
(RayTrainWorker pid=240648, ip=10.222.16.33) Traceback (most recent call last):
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 262, in task_distribute
(RayTrainWorker pid=240648, ip=10.222.16.33)     key, func_name, detail = resource_proxy[TASK_QUEUE].get()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
(RayTrainWorker pid=240648, ip=10.222.16.33)     buf = self._recv(4)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 65, in wrapper
(RayTrainWorker pid=240648, ip=10.222.16.33)     raise exp
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
(RayTrainWorker pid=240648, ip=10.222.16.33)     self.run()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "<string>", line 2, in get
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
(RayTrainWorker pid=240648, ip=10.222.16.33)     raise EOFError
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 62, in wrapper
(RayTrainWorker pid=240648, ip=10.222.16.33)     func(*args, **kwargs)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 108, in run
(RayTrainWorker pid=240648, ip=10.222.16.33)     self._target(*self._args, **self._kwargs)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
(RayTrainWorker pid=240648, ip=10.222.16.33)     kind, result = conn.recv()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 262, in task_distribute
(RayTrainWorker pid=240648, ip=10.222.16.33)     key, func_name, detail = resource_proxy[TASK_QUEUE].get()
(RayTrainWorker pid=240648, ip=10.222.16.33) EOFError
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 65, in wrapper
(RayTrainWorker pid=240648, ip=10.222.16.33)     raise exp
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 250, in recv
(RayTrainWorker pid=240648, ip=10.222.16.33)     buf = self._recv_bytes()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "<string>", line 2, in get
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 62, in wrapper
(RayTrainWorker pid=240648, ip=10.222.16.33)     func(*args, **kwargs)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
(RayTrainWorker pid=240648, ip=10.222.16.33)     buf = self._recv(4)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
(RayTrainWorker pid=240648, ip=10.222.16.33)     self.run()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
(RayTrainWorker pid=240648, ip=10.222.16.33)     kind, result = conn.recv()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 262, in task_distribute
(RayTrainWorker pid=240648, ip=10.222.16.33)     key, func_name, detail = resource_proxy[TASK_QUEUE].get()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
(RayTrainWorker pid=240648, ip=10.222.16.33)     raise EOFError
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 108, in run
(RayTrainWorker pid=240648, ip=10.222.16.33)     self._target(*self._args, **self._kwargs)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 250, in recv
(RayTrainWorker pid=240648, ip=10.222.16.33)     buf = self._recv_bytes()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "<string>", line 2, in get
(RayTrainWorker pid=240648, ip=10.222.16.33) EOFError
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 65, in wrapper
(RayTrainWorker pid=240648, ip=10.222.16.33)     raise exp
(RayTrainWorker pid=240648, ip=10.222.16.33) Traceback (most recent call last):
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
(RayTrainWorker pid=240648, ip=10.222.16.33)     buf = self._recv(4)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
(RayTrainWorker pid=240648, ip=10.222.16.33)     kind, result = conn.recv()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 62, in wrapper
(RayTrainWorker pid=240648, ip=10.222.16.33)     func(*args, **kwargs)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
(RayTrainWorker pid=240648, ip=10.222.16.33)     raise EOFError
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 250, in recv
(RayTrainWorker pid=240648, ip=10.222.16.33)     buf = self._recv_bytes()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 262, in task_distribute
(RayTrainWorker pid=240648, ip=10.222.16.33)     key, func_name, detail = resource_proxy[TASK_QUEUE].get()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
(RayTrainWorker pid=240648, ip=10.222.16.33)     buf = self._recv(4)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "<string>", line 2, in get
(RayTrainWorker pid=240648, ip=10.222.16.33) EOFError
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
(RayTrainWorker pid=240648, ip=10.222.16.33)     raise EOFError
(RayTrainWorker pid=240648, ip=10.222.16.33) Traceback (most recent call last):
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
(RayTrainWorker pid=240648, ip=10.222.16.33)     kind, result = conn.recv()
(RayTrainWorker pid=240648, ip=10.222.16.33) Traceback (most recent call last):
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 250, in recv
(RayTrainWorker pid=240648, ip=10.222.16.33)     buf = self._recv_bytes()
(RayTrainWorker pid=240648, ip=10.222.16.33) EOFError
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
(RayTrainWorker pid=240648, ip=10.222.16.33)     self.run()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
(RayTrainWorker pid=240648, ip=10.222.16.33)     buf = self._recv(4)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 108, in run
(RayTrainWorker pid=240648, ip=10.222.16.33)     self._target(*self._args, **self._kwargs)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
(RayTrainWorker pid=240648, ip=10.222.16.33)     raise EOFError
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 65, in wrapper
(RayTrainWorker pid=240648, ip=10.222.16.33)     raise exp
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 62, in wrapper
(RayTrainWorker pid=240648, ip=10.222.16.33)     func(*args, **kwargs)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 262, in task_distribute
(RayTrainWorker pid=240648, ip=10.222.16.33)     key, func_name, detail = resource_proxy[TASK_QUEUE].get()
(RayTrainWorker pid=240648, ip=10.222.16.33) EOFError
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
(RayTrainWorker pid=240648, ip=10.222.16.33)     self.run()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "<string>", line 2, in get
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 108, in run
(RayTrainWorker pid=240648, ip=10.222.16.33)     self._target(*self._args, **self._kwargs)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
(RayTrainWorker pid=240648, ip=10.222.16.33)     kind, result = conn.recv()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
(RayTrainWorker pid=240648, ip=10.222.16.33)     self.run()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 65, in wrapper
(RayTrainWorker pid=240648, ip=10.222.16.33)     raise exp
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 250, in recv
(RayTrainWorker pid=240648, ip=10.222.16.33)     buf = self._recv_bytes()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 108, in run
(RayTrainWorker pid=240648, ip=10.222.16.33)     self._target(*self._args, **self._kwargs)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 62, in wrapper
(RayTrainWorker pid=240648, ip=10.222.16.33)     func(*args, **kwargs)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
(RayTrainWorker pid=240648, ip=10.222.16.33)     buf = self._recv(4)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 65, in wrapper
(RayTrainWorker pid=240648, ip=10.222.16.33)     raise exp
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 262, in task_distribute
(RayTrainWorker pid=240648, ip=10.222.16.33)     key, func_name, detail = resource_proxy[TASK_QUEUE].get()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
(RayTrainWorker pid=240648, ip=10.222.16.33)     raise EOFError
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 62, in wrapper
(RayTrainWorker pid=240648, ip=10.222.16.33)     func(*args, **kwargs)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "<string>", line 2, in get
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 262, in task_distribute
(RayTrainWorker pid=240648, ip=10.222.16.33)     key, func_name, detail = resource_proxy[TASK_QUEUE].get()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
(RayTrainWorker pid=240648, ip=10.222.16.33)     kind, result = conn.recv()
(RayTrainWorker pid=240648, ip=10.222.16.33) EOFError
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "<string>", line 2, in get
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 250, in recv
(RayTrainWorker pid=240648, ip=10.222.16.33)     buf = self._recv_bytes()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
(RayTrainWorker pid=240648, ip=10.222.16.33)     kind, result = conn.recv()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
(RayTrainWorker pid=240648, ip=10.222.16.33)     buf = self._recv(4)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 250, in recv
(RayTrainWorker pid=240648, ip=10.222.16.33)     buf = self._recv_bytes()
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
(RayTrainWorker pid=240648, ip=10.222.16.33)     raise EOFError
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
(RayTrainWorker pid=240648, ip=10.222.16.33)     buf = self._recv(4)
(RayTrainWorker pid=240648, ip=10.222.16.33)   File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
(RayTrainWorker pid=240648, ip=10.222.16.33)     raise EOFError
(RayTrainWorker pid=240648, ip=10.222.16.33) EOFError

### Versions / Dependencies

- Ray, version 2.37.0
- Platform: Linux-4.19.90-2107.6.0.0192.8.oe1.bclinux.aarch64-aarch64-with-glibc2.35
- Python version: 3.10.14
- PyTorch version: 2.1.0 (NPU)
- Transformers version: 4.44.2
- NPU type: Ascend910B2
- CANN version: 8.0.RC3.alpha001

### Reproduction script

import os
from typing import Dict

import torch
from filelock import FileLock
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.transforms import Normalize, ToTensor
from tqdm import tqdm

import ray.train
from ray.train import ScalingConfig
from ray.train.torch import TorchTrainer, TorchConfig

def get_dataloaders(batch_size):
    # Transform to normalize the input images
    transform = transforms.Compose([ToTensor(), Normalize((0.5,), (0.5,))])

    with FileLock(os.path.expanduser("~/data.lock")):
        # Download training data from open datasets
        training_data = datasets.FashionMNIST(
            root="~/data",
            train=True,
            download=True,
            transform=transform,
        )

        # Download test data from open datasets
        test_data = datasets.FashionMNIST(
            root="~/data",
            train=False,
            download=True,
            transform=transform,
        )

    # Create data loaders
    train_dataloader = DataLoader(training_data, batch_size=batch_size, shuffle=True)
    test_dataloader = DataLoader(test_data, batch_size=batch_size)

    return train_dataloader, test_dataloader

# Model Definition
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28 * 28, 512),
            nn.ReLU(),
            nn.Dropout(0.25),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Dropout(0.25),
            nn.Linear(512, 10),
            nn.ReLU(),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

def train_func_per_worker(config: Dict):
    lr = config["lr"]
    epochs = config["epochs"]
    batch_size = config["batch_size_per_worker"]

    # Get dataloaders inside the worker training function
    train_dataloader, test_dataloader = get_dataloaders(batch_size=batch_size)

    # [1] Prepare Dataloader for distributed training
    # Shard the datasets among workers and move batches to the correct device
    # =======================================================================
    train_dataloader = ray.train.torch.prepare_data_loader(train_dataloader)
    test_dataloader = ray.train.torch.prepare_data_loader(test_dataloader)

    model = NeuralNetwork()

    # [2] Prepare and wrap your model with DistributedDataParallel
    # Move the model to the correct GPU/CPU device
    # ============================================================
    model = ray.train.torch.prepare_model(model)

    loss_fn = nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=lr, momentum=0.9)

    # Model training loop
    for epoch in range(epochs):
        print_worker_info(epoch)
        if ray.train.get_context().get_world_size() > 1:
            # Required for the distributed sampler to shuffle properly across epochs.
            train_dataloader.sampler.set_epoch(epoch)

        model.train()
        for X, y in tqdm(train_dataloader, desc=f"Train Epoch {epoch}"):
            pred = model(X)
            loss = loss_fn(pred, y)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

        model.eval()
        test_loss, num_correct, num_total = 0, 0, 0
        with torch.no_grad():
            for X, y in tqdm(test_dataloader, desc=f"Test Epoch {epoch}"):
                pred = model(X)
                loss = loss_fn(pred, y)

                test_loss += loss.item()
                num_total += y.shape[0]
                num_correct += (pred.argmax(1) == y).sum().item()

        test_loss /= len(test_dataloader)
        accuracy = num_correct / num_total

        # [3] Report metrics to Ray Train
        # ===============================
        ray.train.report(metrics={"loss": test_loss, "accuracy": accuracy})

def train_fashion_mnist(num_workers=2, use_gpu=False):
    global_batch_size = 32

    train_config = {
        "lr": 1e-3,
        "epochs": 10,
        "batch_size_per_worker": global_batch_size // num_workers,
    }

    # Configure computation resources
    torch_config = TorchConfig(backend="hccl", timeout_s=18000)
    scaling_config = ScalingConfig(num_workers=num_workers, resources_per_worker={"NPU":2})

    # Initialize a Ray TorchTrainer
    trainer = TorchTrainer(
        train_loop_per_worker=train_func_per_worker,
        train_loop_config=train_config,
        torch_config=torch_config,
        scaling_config=scaling_config,
    )

    # [4] Start distributed training
    # Run `train_func_per_worker` on all workers
    # =============================================
    result = trainer.fit()
    print(f"Training result: {result}")

def print_worker_info(epoch):
    context = ray.train.get_context()
    print("start to train epoch :", epoch)
    world_size = context.get_world_size()
    print("world_size is:", world_size)
    world_rank = context.get_world_rank()
    print("world_rank is:", world_rank)
    node_rank = context.get_node_rank()
    print("node_rank is:", node_rank)
    local_rank = context.get_local_rank()
    print("local_rank is:", local_rank)

if __name__ == "__main__":
    train_fashion_mnist(num_workers=4, use_gpu=True)

### Issue Severity

High: It blocks me from completing my task.

**Comment by lxmanutd** [comment]
@jcotant1, could you please help to check this issue first since it blocks us to use ray for integration? Thanks a lot

**Comment by jcotant1** [comment]
Hey @lxmanutd - sure thing, thanks for following up. Looping in the current and upcoming Train on-calls @hongpeng-guo @justinvyu

**Comment by justinvyu** [comment]
@lxmanutd Could you provide some more context on what these shutdown errors are? They seem to be internal code snippets that are trying to run some cleanup on function exit?

(RayTrainWorker pid=240648, ip=10.222.16.33) File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 65, in wrapper
