### ISSUE TITLE
[Core] Long-running cluster ends up with lots of JobSupervisor actors in the DEPENDENCIES_UNREADY state 

### ISSUE THREAD

**Issue by jfaust-fy** [ray-project/ray#48452]
### What happened + What you expected to happen

We have some long-running Ray clusters that we submit jobs to via the Job Submission API. Occasionally, we see jobs start to take longer than they should, with the overhead being in job submission itself. If I look at the Actors list in these situations, I see:
![image](https://github.com/user-attachments/assets/bbda7218-8479-484a-bb64-977be65611c7)
Note the 76 `JobSupervisor` actors in the `DEPENDENCIES_UNREADY` state.
In this screenshot the cluster has been running for 1 month.

### Versions / Dependencies

Ray 2.24
Python 3.11
Ubuntu 20.04

### Reproduction script

I'm not sure how to create a repro script for this - the cluster it just happened on had been running for 1 month.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jjyao** [comment]
Hi @jfaust-fy so it's not that the JobSupervisor is stuck at DEPENDENCIES_UNREADY state right? Eventually it will become RUNNING (after 30s+)?

**Comment by jfaust-fy** [comment]
We continue to hit this periodically - most recently when looking into it, I saw a few of these from failed jobs when the issue is happening:
```
Failed to start supervisor actor 1737053605678:vycstjlt: 'There was timeout in registering an actor. It is probably because GCS server is dead or there's a high load there.'. Full traceback:
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.11.9/lib/python3.11/site-packages/ray/dashboard/modules/job/job_manager.py", line 543, in submit_job
    ).remote(submission_id, entrypoint, metadata or {}, self._gcs_address)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyenv/versions/3.11.9/lib/python3.11/site-packages/ray/actor.py", line 833, in remote
    return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyenv/versions/3.11.9/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/pyenv/versions/3.11.9/lib/python3.11/site-packages/ray/util/tracing/tracing_helper.py", line 388, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyenv/versions/3.11.9/lib/python3.11/site-packages/ray/actor.py", line 1164, in _remote
    actor_id = worker.core_worker.create_actor(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python/ray/_raylet.pyx", line 4085, in ray._raylet.CoreWorker.create_actor
  File "python/ray/_raylet.pyx", line 4129, in ray._raylet.CoreWorker.create_actor
  File "python/ray/_raylet.pyx", line 573, in ray._raylet.check_status
ray.exceptions.GetTimeoutError: There was timeout in registering an actor. It is probably because GCS server is dead or there's a high load there.
```
