### ISSUE TITLE
[rllib] multiagent_cartpole bug with policy dict

### ISSUE THREAD

**Issue by lazhangRC** [ray-project/ray#4848]
### System information
- **OS Platform and Distribution: Mac OS X 10.12.6 (Sierra)**
- **Ray installed from binary**
- **Ray version 0.7.0**
- **Python version 3.7.1**
- **Exact command to reproduce: `python multiagent_cartpole.py`**

### Describe the problem
Running the `multiagent_cartpole.py` gives the following issue: 

> ValueError: Could not find policy for agent: agent policy id `policy_1` not in policy map keys dict_keys(['default_policy']).

Changing `multiagent_cartpole.py:108` 
from: `"policies": policies,`
 to: `"policy_graphs": policies,` 
seems to fix the issue

**Comment by ericl** [comment]
I think you need to upgrade your rllib version here. It's unfortunate the example was not backwards compatible, maybe it should still use the old policy_graphs config.

**Comment by lazhangRC** [comment]
Thank you for the response. I installed the most recent version of rllib today.

**Comment by ericl** [comment]
That's different from latest right?
https://ray.readthedocs.io/en/latest/installation.html

Since the example is from master, you need the latest wheels.

**Comment by lazhangRC** [comment]
Okay. I tried the latest wheel for MacOS Python 3.7 (ray 0.7.0.dev2).

FYI I'm getting a new issue running `multiagent_cartpole.py`.
`tf = try_import_tf()` fails with:
ImportError: cannot import name 'try_import_tf' from 'ray.rllib.utils'

**Comment by ericl** [comment]
Could it be your python repo is out of sync with the installed ray you're running? You can check to see what  directory ray is using with `ray.__file__`. You should also be able to find try_import_tf in the utils/__init__.py file.

**Comment by josjo80** [comment]
Having the same problem and I installed ray with the latest wheels.
Below is a more comprehensive trace stack but not whole thing (it's long):
```== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/16 CPUs, 0/4 GPUs
Memory usage on this node: 4.2/134.8 GB
Result logdir: /home/johnson/ray_results/PPO
Number of trials: 1 ({'ERROR': 1})
ERROR trials:
 - PPO_multi_cartpole_0:        ERROR, 1 failures: /home/johnson/ray_results/PPO/PPO_multi_cartpole_0_2019-06-27_22-32-15zjei16zf/error_2019-06-27_22-32-26.txt

(pid=21028) ray.exceptions.RayTaskError: ray_PolicyEvaluator:sample() (pid=21066, host=cassini)
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 440, in sample
(pid=21028)     batches = [self.input_reader.next()]
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 60, in next
(pid=21028)     batches = [self.get_data()]
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 101, in get_data
(pid=21028)     item = next(self.rollout_provider)
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 317, in _env_runner
(pid=21028)     soft_horizon)
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 405, in _process_observations
(pid=21028)     policy_id).transform(raw_obs)
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 650, in _get_or_raise
(pid=21028)     "in policy map keys {}.".format(policy_id, mapping.keys()))
(pid=21028) ValueError: Could not find policy for agent: agent policy id `policy_1` not in policy map keys dict_keys(['default_policy']).
(pid=21028)
(pid=21028)
(pid=21028) During handling of the above exception, another exception occurred:
(pid=21028)
(pid=21028) Traceback (most recent call last):
Traceback (most recent call last):
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 743, in _try_recover
  File "multiagent_cartpole.py", line 111, in <module>
(pid=21028)     ray_get_and_free(obj_id)
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/utils/memory.py", line 33, in ray_get_and_free
(pid=21028)     result = ray.get(object_ids)
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/worker.py", line 2197, in get
(pid=21028)     raise value
(pid=21028) ray.exceptions.RayTaskError: ray_PolicyEvaluator:sample_with_count() (pid=21070, host=cassini)
    lambda agent_id: random.choice(policy_ids)),
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 490, in sample_with_count
  File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/tune/tune.py", line 265, in run
(pid=21028)     batch = self.sample()
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 440, in sample
(pid=21028)     batches = [self.input_reader.next()]
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 60, in next
(pid=21028)     batches = [self.get_data()]
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 101, in get_data
    raise TuneError("Trials did not complete", errored_trials)
(pid=21028)     item = next(self.rollout_provider)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_multi_cartpole_0])
(pid=21028) StopIteration
(pid=21028)
(pid=21028) 2019-06-27 22:32:26,032     ERROR trainer.py:747 -- Blacklisting worker 2
(pid=21028) Traceback (most recent call last):
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 340, in train
(pid=21028)     result = Trainable.train(self)
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/tune/trainable.py", line 151, in train
(pid=21028)     result = self._train()
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/agents/ppo/ppo.py", line 110, in _train
(pid=21028)     fetches = self.optimizer.step()
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 131, in step
(pid=21028)     self.num_envs_per_worker, self.train_batch_size)
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/optimizers/rollout.py", line 29, in collect_samples
(pid=21028)     next_sample = ray_get_and_free(fut_sample)
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/utils/memory.py", line 33, in ray_get_and_free
(pid=21028)     result = ray.get(object_ids)
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/worker.py", line 2197, in get
(pid=21028)     raise value
(pid=21028) ray.exceptions.RayTaskError: ray_PolicyEvaluator:sample() (pid=21066, host=cassini)
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 440, in sample
(pid=21028)     batches = [self.input_reader.next()]
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 60, in next
(pid=21028)     batches = [self.get_data()]
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 101, in get_data
(pid=21028)     item = next(self.rollout_provider)
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 317, in _env_runner
(pid=21028)     soft_horizon)
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 405, in _process_observations
(pid=21028)     policy_id).transform(raw_obs)
(pid=21028)   File "/home/johnson/miniconda3/envs/rlenv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 650, in _get_or_raise
(pid=21028)     "in policy map keys {}.".format(policy_id, mapping.keys()))
(pid=21028) ValueError: Could not find policy for agent: agent policy id `policy_1` not in policy map keys dict_keys(['default_policy']).```
