### ISSUE TITLE
Ray does not work on Jupyter Notebook/Lab

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#4852]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac
- **Ray installed from (source or binary)**: 0.7 pip
- **Ray version**:
- **Python version**: 3.7
- **Exact command to reproduce**:

### Describe the problem

```
import numpy as np

import ray
from ray import tune
ray.shutdown()
ray.init()


@ray.remote
def train_evaluate():
    np.array(1)

ray.get(train_evaluate.remote())
```

If you run this in a notebook, you get 
```
2019-05-24 01:12:26,824	WARNING worker.py:1341 -- WARNING: Not updating worker name since `setproctitle` is not installed. Install this with `pip install setproctitle` (or ray[debug]) to enable monitoring of worker processes.
2019-05-24 01:12:26,826	INFO node.py:497 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-05-24_01-12-26_825886_4573/logs.
2019-05-24 01:12:26,943	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:20468 to respond...
2019-05-24 01:12:27,062	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:48641 to respond...
2019-05-24 01:12:27,067	INFO services.py:806 -- Starting Redis shard with 3.44 GB max memory.
2019-05-24 01:12:27,094	INFO node.py:511 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-05-24_01-12-26_825886_4573/logs.
2019-05-24 01:12:27,097	INFO services.py:1441 -- Starting the Plasma object store with 5.15 GB memory using /tmp.
2019-05-24 01:12:28,107	ERROR worker.py:1678 -- Traceback (most recent call last):
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 920, in _process_task
    self._store_outputs_in_object_store(return_object_ids, outputs)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 831, in _store_outputs_in_object_store
    self.put_object(object_ids[i], outputs[i])
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 383, in put_object
    self.store_and_register(object_id, value)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 317, in store_and_register
    self.task_driver_id))
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 246, in get_serialization_context
    _initialize_serialization(driver_id)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1151, in _initialize_serialization
    serialization_context = pyarrow.default_serialization_context()
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py", line 326, in default_serialization_context
    register_default_serialization_handlers(context)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py", line 321, in register_default_serialization_handlers
    _register_custom_pandas_handlers(serialization_context)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py", line 129, in _register_custom_pandas_handlers
    import pandas as pd
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat.numpy import *
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/pandas/compat/__init__.py", line 446, in <module>
    import typing
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/typing.py", line 1356, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/typing.py", line 1004, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 98, in <module>
    ray.worker.global_worker.main_loop()
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1042, in main_loop
    self._wait_for_and_process_task(task)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 993, in _wait_for_and_process_task
    self._process_task(task, execution_info)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 924, in _process_task
    ray.utils.format_error_message(traceback.format_exc()))
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 933, in _handle_process_task_failure
    self._store_outputs_in_object_store(return_object_ids, failure_objects)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 831, in _store_outputs_in_object_store
    self.put_object(object_ids[i], outputs[i])
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 383, in put_object
    self.store_and_register(object_id, value)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 317, in store_and_register
    self.task_driver_id))
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 246, in get_serialization_context
    _initialize_serialization(driver_id)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1151, in _initialize_serialization
    serialization_context = pyarrow.default_serialization_context()
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py", line 326, in default_serialization_context
    register_default_serialization_handlers(context)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py", line 321, in register_default_serialization_handlers
    _register_custom_pandas_handlers(serialization_context)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py", line 129, in _register_custom_pandas_handlers
    import pandas as pd
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat.numpy import *
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/pandas/compat/__init__.py", line 446, in <module>
    import typing
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/typing.py", line 1356, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/typing.py", line 1004, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'

  This error is unexpected and should not have happened. Somehow a worker
  crashed in an unanticipated way causing the main_loop to throw an exception,
  which is being caught in "python/ray/workers/default_worker.py".
  
2019-05-24 01:12:28,111	ERROR worker.py:1678 -- A worker died or was killed while executing task 00000000fe2a5efb1fd5bff37d7cb5e04a6f3d63.
```

**Comment by richardliaw** [comment]
cc @pcmoritz

**Comment by robertnishihara** [comment]
My guess is you have multiple versions of Ray installed and they're getting mixed together somehow. If you do `ray.__version__` and `import sys; sys.version_info` in the notebook, do you get the result that you expect?

**Comment by richardliaw** [comment]
Hm, looks like the versions are right. 

However, seems to work fine on Ubuntu, so it's possible that it's a problem unique to my setup.

**Comment by pcmoritz** [comment]
Can you try to do `pip uninstall typing`? That solved the same error in the past for me. It happens if the pip typing module is installed in python 3.7.
