### ISSUE TITLE
"You must feed a value for placeholder tensor" error

### ISSUE THREAD

**Issue by yarik1988** [ray-project/ray#4865]
Hello! I'm trying to use RLlib with tensorflow 2.0 and I have a sample code which is supposed  to train an agent on Cartpole-v0 environment

```python
from __future__ import absolute_import, division, print_function, unicode_literals
import ray
import ray.rllib.agents.dqn as dqn
from ray.rllib.models import ModelCatalog, Model
from ray.tune.registry import register_env
import gym
import tensorflow as tf
from tensorflow.keras import layers, Sequential

class CartpoleModel(Model):
    def _build_layers_v2(self, input_dict, num_outputs, options):
        self.model = Sequential()
        self.model.add(layers.Dense(4, name='l1', activation='relu',batch_input_shape=(None,4)))
        self.model.add(layers.Dense(10, name='l2', activation='relu'))
        self.model.add(layers.Dense(10, name='l3', activation='relu'))
        self.model.add(layers.Dense(10, name='l4', activation='relu'))
        self.model.add(layers.Dense(2, name='l5', activation='relu'))
        return self.model.get_layer("l5").output, self.model.get_layer("l4").output



ray.init()
ModelCatalog.register_custom_model("CartpoleModel", CartpoleModel)
CartpoleEnv = gym.make('CartPole-v0')
register_env("CP", lambda _:CartpoleEnv)

trainer = dqn.DQNTrainer(env="CP", config={
    "model": {"custom_model": "CartpoleModel"},
})

print(trainer.train())`
```
And the error appears as 
```
2019-05-25 20:51:45,992	ERROR tf_run_builder.py:51 -- Error fetching: [<tf.Tensor 'default_policy/cond/Merge:0' shape=(?,) dtype=int64>, {'q_values': <tf.Tensor 'default_policy/q_func/add:0' shape=(?, 2) dtype=float32>}], feed_dict={<tf.Tensor 'default_policy/stochastic:0' shape=() dtype=bool>: True, <tf.Tensor 'default_policy/eps:0' shape=() dtype=float32>: 1.0, <tf.Tensor 'default_policy/Placeholder:0' shape=(?, 4) dtype=float32>: [array([-0.0187199 ,  0.03046412, -0.0374948 , -0.02966113])], <tf.Tensor 'default_policy/q_func/PlaceholderWithDefault:0' shape=() dtype=bool>: False}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1320, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1408, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'default_policy/q_func/l1_input' with dtype float and shape [?,4]
	 [[{{node default_policy/q_func/l1_input}}]]
```
My system is Ubuntu 18.04.2 LTS, python 3.6, tensorflow 2.0.
I installed ray from sources a couple of days ago, because current pip version still have some tf 2.0 incompatibilities

**Comment by yarik1988** [comment]
Interestingly, with a default model (with commented line  "model": {"custom_model": "CartpoleModel"}, ) all is working. So the problem is in my model, but I can't figure out where is the bug

**Comment by yarik1988** [comment]
Solved :) It was needed to manually add InputLayer
```python
class CartpoleModel(Model):
    def _build_layers_v2(self, input_dict, num_outputs, options):
        self.model = Sequential()
        self.model.add(layers.InputLayer(input_tensor=input_dict["obs"], input_shape=(4,)))
        self.model.add(layers.Dense(4, name='l1', activation='relu'))
        self.model.add(layers.Dense(10, name='l2', activation='relu'))
        self.model.add(layers.Dense(10, name='l3', activation='relu'))
        self.model.add(layers.Dense(10, name='l4', activation='relu'))
        self.model.add(layers.Dense(2, name='l5', activation='relu'))
        return self.model.get_layer("l5").output, self.model.get_layer("l4").output
```

**Comment by yarik1988** [comment]
It will be good to add my updated code to examples, because there is no tensorflow 2.0 examples currently
