### ISSUE TITLE
[CORE] importing ray closes logging handlers, breaking custom logging 

### ISSUE THREAD

**Issue by Liquidmasl** [ray-project/ray#48846]
### What happened + What you expected to happen

I am debugging for 2 days now why our Loki logging handler will not log some lines. 

I think I understand now that ray is removing all logging handlers and just.. readding (?) these?
```
Handler.__init__ <class 'ray._private.log.PlainRayHandler'>
Handler.__init__ <class 'logging._StderrHandler'>
Handler.__init__ <class 'logging.StreamHandler'>
```

Meaning the handler that is responsible for sending our logs to our logging server just disappears. I have not figured out why this happens. 

I added a debug print in `logging.Handerl.__init__` and `logging.Handler.close`, this is what i get:

```
Handler.close <class 'processing.intern_depend.cirq_logger.loki_logger.CustomLokiHandler'>
Handler.close <class 'processing.intern_depend.cirq_logger.loki_logger.CustomLokiQueueHandler'>
Handler.close <class 'logging.StreamHandler'>
Handler.close <class 'logging.NullHandler'>
Handler.close <class 'logging.NullHandler'>
Handler.close <class 'logging.StreamHandler'>
Handler.close <class 'logging.NullHandler'>
Handler.close <class 'logging._StderrHandler'>
Handler.__init__ <class 'ray._private.log.PlainRayHandler'>
Handler.__init__ <class 'logging._StderrHandler'>
Handler.__init__ <class 'logging.StreamHandler'>
```  

So my loki handler is just... gone. And that without any notice, I just noticed that logs are missing on the server.

When I debug into the close method I see in the call stack that is being triggered by `generate_logging_config()` in `ray/private/_log` and it seams it is called always from `ray/__init__.py` in line 7

The only thing i can do is ensure that i ALWAYS import ray before i initialize my logging. 
a little change in linter configuration can lead to the ray import slipping below the logger initialization, silently shutting of our custom logger. 

I think this is quite the severe issue! And it was a very hard and strange issue to find. 

(might be related to https://github.com/ray-project/ray/issues/22312 ?)

After more trial and error I am even more confused. Using a queue handler, or another custom handler, it still works, even though apparently the handlers are closed. 
but when the custom handler has some custom shut down or `close()` code. stuff breaks. 
The 'minimal' reproducer is not so minimal, but it manages to reproduce without any libraries. 

### Versions / Dependencies

Windows 11
Ray 2.39
Python 3.11

### Reproduction script

import logging
import queue
import threading
import time
from logging.handlers import QueueHandler
from logging.handlers import QueueListener

root_logger = logging.getLogger()
root_logger.setLevel(logging.DEBUG)

class CustomQueueHandler(QueueHandler):
    """This handler automatically creates listener and `LokiHandler` to handle logs queue."""

    def __init__(self, queue, **kwargs):
        """Create new logger handler with the specified queue and kwargs for the `LokiHandler`."""
        super().__init__(queue)
        self.custom_handler = BatchHandler(**kwargs)  # noqa: WPS110
        self.listener = QueueListener(self.queue, self.custom_handler)
        self.listener.start()

    def close(self):
        self.listener.stop()
        self.custom_handler.stop()
        super().close()

    def flush(self):
        self.custom_handler.flush()
        super().flush()

class BatchHandler(logging.Handler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.lock = threading.Lock()
        self.last_handle_time = time.time()
        self.stop_flag = False
        self.batch = []
        self.thread = threading.Thread(target=self._monitor)
        self.thread.daemon = True
        self.thread.start()

    def handle(self, record):
        with self.lock:
            self.batch.append(record)
            print(self.batch)

    def _monitor(self):
        while True:
            try:
                if len(self.batch) > 3:
                    self.handle_batch()

                if time.time() - self.last_handle_time > 2:
                    self.handle_batch()

                if self.stop_flag:
                    self.handle_batch()
                    break

                time.sleep(1)
            except queue.Empty:
                pass

    def handle_batch(self):

        with self.lock:
            b = self.batch
            self.batch = []

        for i, record in enumerate(b):
            print(f'{i}: {record.msg}')

    def stop(self):
        self.stop_flag = True
        self.thread.join()

q = queue.Queue()
root_logger.addHandler(CustomQueueHandler(q))

root_logger.info('I will be printed 1')

import ray # everthing AFTER this import will not be handled/printed. Moving the import before the handler is set, everthing is printed.

root_logger.info('I will be missing when this is below the ray import ')
logging.getLogger('some.other.logger').info('I will also be missing if i am below the ray import.')

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by alexeykudinkin** [comment]
This is a duplicate of https://github.com/ray-project/ray/issues/48732

**Comment by kevin85421** [comment]
I tested it manually. I have already been fixed. Close this issue.

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/79786a3b-7712-46d2-88e0-8aa52bea4ffa" />

**Comment by alexeykudinkin** [comment]
> In which version? in what branch? where has this been fixed?
I still have this issue on 2.40.0 in my production code (in linux docker environments) and also with the reproducer (on windows)

@Liquidmasl have you checked the PR attached to the issue this marked as a duplicate of? 

It hasn't been released yet and should be available in 2.41. Please circle back if issue isn't resolved for you in 2.41 (or on master)

**Comment by Liquidmasl** [comment]
> [@Liquidmasl](https://github.com/Liquidmasl) have you checked the PR attached to the issue this marked as a duplicate of?
I did, but it also references commits that are about that error that dont seam to be merged yet, thought that might be relevant.

> It hasn't been released yet and should be available in 2.41
Thank you! that was the information i was missing. 

as this
> I tested it manually. I have already been fixed. Close this issue.
wasnt actually mentioning anything about the version it has been tested with, so I assumed the current released version. Which lead to me to removing the workarounds I built, which lead to missing log messages again, which then motivated me trying the reproducer again, which then again lead me back here to write my follow up.
So for the future I will remember that issues are closed when there are fixed somewhere, not when they are fixed on the released version. It would be super helpful though if issues get closed with a mentionen to a revision or pr or just a notion of "not relesed yet will be in x.x"

Anyway, thanks and sorry for the bother.

**Comment by Liquidmasl** [comment]
> Please circle back if issue isn't resolved for you in 2.41

Here am I circling back!

I am on 2.42 now and still have this issue, although it changed a bit...

It works a lot better now, but when I try to read a .parquet file with modin, modin tries to import from_pandas_refs at some point (
```py
from ray.data import from_pandas_refs
```
which then, a few frames further, calls `configure_logging()` which then again a few frames further shuts down my handler...

![Image](https://github.com/user-attachments/assets/65279d7d-3d67-4956-bbcc-0c1349b0c065)

**Comment by jjyao** [comment]
@alexeykudinkin I think it's now a data logging configure issue cc @omatthew98 since it only happens with `from ray.data import from_pandas_refs`

**Comment by richardliaw** [comment]
I took a look at this @omatthew98. Basically it looks like the custom handlers are being stopped unintentionally. It seems to happen exactly in this part of the code:

```python
Traceback (most recent call last):
  File "/Users/rliaw/dev/ray/python/ray/data/_test.py", line 118, in <module>
    from ray.data import from_pandas_refs  # but this still does break it! Every log after this line will be missing!
  File "/Users/rliaw/miniconda3/envs/oss/lib/python3.10/site-packages/ray/data/__init__.py", line 74, in <module>
    configure_logging()
  File "/Users/rliaw/miniconda3/envs/oss/lib/python3.10/site-packages/ray/data/_internal/logging.py", line 176, in configure_logging
    logging.config.dictConfig(config)
  File "/Users/rliaw/miniconda3/envs/oss/lib/python3.10/logging/config.py", line 811, in dictConfig
    dictConfigClass(config).configure()
  File "/Users/rliaw/miniconda3/envs/oss/lib/python3.10/logging/config.py", line 538, in configure
    _clearExistingHandlers()
  File "/Users/rliaw/miniconda3/envs/oss/lib/python3.10/logging/config.py", line 275, in _clearExistingHandlers
    logging.shutdown(logging._handlerList[:])
```

I'd recommend adopting something similar to what is done on Core side if possible.

**Comment by richardliaw** [comment]
Also labeling as P1 because it should be fixed in a couple weeks (but not without workaround).

**Comment by Liquidmasl** [comment]
thanks, although given the last tag, i am 90% sure I tested this on a linux docker image, but I might be mistaken

**Comment by Liquidmasl** [comment]
hey again, this is not a windows issue, as i am running this in docker.
(I gave up on ray on windows, is it just keeps crashing for me) 

Is there news on this? I still have to juggle my imports to not lose logs, which makes the codebase quite a bit more smelly
