### ISSUE TITLE
[<Ray component: Python|runtime_env]Pip install `whl` file faliure when a job reruns in the same cluster

### ISSUE THREAD

**Issue by BetterLevi** [ray-project/ray#49059]
## What happend
If a job is using customized `whl` file in python modules, it runs successfully for the first time submit. But, if it run again in the same cluster, will show error like:
```
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/runtime_env/agent/runtime_env_agent.py", line 393, in _create_runtime_env_with_retry
    runtime_env_context = await asyncio.wait_for(
  File "/home/ray/anaconda3/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/runtime_env/agent/runtime_env_agent.py", line 354, in _setup_runtime_env
    await create_for_plugin_if_needed(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/runtime_env/plugin.py", line 254, in create_for_plugin_if_needed
    size_bytes = await plugin.create(uri, runtime_env, context, logger=logger)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/runtime_env/py_modules.py", line 199, in create
    await install_wheel_package(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 928, in install_wheel_package
    Path(wheel_uri).unlink()
  File "/home/ray/anaconda3/lib/python3.9/pathlib.py", line 1354, in unlink
    self._accessor.unlink(self)
IsADirectoryError: [Errno 21] Is a directory: '/tmp/ray/session_2024-12-03_17-39-06_344571_9/runtime_resources/py_modules_files/method-1.0-py3-none-any'
```

## What expected

I found there is a bug when handling the python modules. The *[download_and_unpack_package](https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/py_modules.py#L203)* will return a directory path if the `whl` package has been installed before(*[see detail](https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/packaging.py#L681)*). So the *[wheel uri](https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/py_modules.py#L208C22-L208C23)* will be incorrect when do pip install command.

### Versions / Dependencies

ALL

### Reproduction script

1. create a Ray cluster
2. submit job with a customized python module with `whl` file
3. submit the job again

### Issue Severity

None

**Comment by jjyao** [comment]
@BetterLevi willing to submit a fix PR? :)

**Comment by BetterLevi** [comment]
Thanks for replying @jjyao sure, would like to discuss with you about the solution.

I think the method *[download_and_unpack_package](https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/packaging.py#L681)* returns a path to the local dir that contains unpacked package files EXCEPT the *[whl file](https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/packaging.py#L828)*

My solution is when do the *[directory existing check](https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/packaging.py#L725)*, need to exclude the *whl file type*.  So I'd suggest adding:
```
if local_dir.exists() and pkg_file.suffix == ".whl":
```
to make sure the *whl file* will be downloaded again and then return the right file path.

What do you think?

**Comment by tczekajlo** [comment]
Hey, I've run into the same issue, but with Ray Serve. Is there any chance to move forward with a PR?
