### ISSUE TITLE
[Data] Transient Parquet Fragment Serialization Error

### ISSUE THREAD

**Issue by ivanthewebber** [ray-project/ray#49082]
### What happened + What you expected to happen

I am attempting to read Parquet data from ADLS Gen 2 storage using Ray, but I am getting a transient error with no code change.

For example, all of the `read_parquet` lines will either succeed or fail each time I restart the Python interpreter/debugger. I have experimented with changing the order of path variations, mixing in calls to `pa.parquet.read_table`, or recreating the `fss` and credential but it seems to be a transient issue with no sure trigger or resolution.
```python
import adlfs
from azure.identity import DefaultAzureCredential
import ray.data
import pyarrow as pa
fss = adlfs.AzureBlobFileSystem(account_name="my_account", credential=DefaultAzureCredential(), anon=False)
paths = ['abfs://my_container/multi_city/my/path/split=Split1/part=1.parquet']
ray.data.read_parquet(paths, filesystem=fss).count()
paths = ['abfs:/my_container/multi_city/my/path/split=Split1/part=1.parquet']
ray.data.read_parquet(paths, filesystem=fss).count()
paths = ['abfs://my_container@my_account.dfs.core.windows.net/multi_city/my/path/split=Split1/part=1.parquet']
ray.data.read_parquet(paths, filesystem=fss).count()
paths = ['abfs:/my_container@my_account.dfs.core.windows.net/multi_city/my/path/split=Split1/part=1.parquet']
ray.data.read_parquet(paths, filesystem=fss).count()
paths = ['abfs://my_container@my_account/multi_city/my/path/split=Split1/part=1.parquet']
ray.data.read_parquet(paths, filesystem=fss).count()
paths = ['abfs:/my_container@my_account/multi_city/my/path/split=Split1/part=1.parquet']
ray.data.read_parquet(paths, filesystem=fss).count()
```

Notably, reading without Ray (paths starting with `'abfs://'` to avoid `FileNotFoundError`) always works:
```python
len(pa.parquet.read_table(paths, filesystem=fss))
```

The error message is:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ray\data\read_api.py", line 750, in read_parquet
    datasource = ParquetDatasource(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ray\data\_internal\datasource\parquet_datasource.py", line 296, in __init__
    self._pq_fragments = [SerializedFragment(p) for p in pq_ds.fragments]
    self._data = cloudpickle.dumps(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ray\cloudpickle\cloudpickle.py", line 1479, in dumps
    cp.dump(obj)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ray\cloudpickle\cloudpickle.py", line 1245, in dump
    return super().dump(obj)
           ^^^^^^^^^^^^^^^^^
TypeError: cannot pickle '_thread.RLock' object
>>> paths = ['abfs://my_container@my_account.dfs.core.windows.net/multi_city/my/path/split=Split1/part=1.parquet']
```

### Versions / Dependencies

Name: adlfs
Version: 2024.7.0
Summary: Access Azure Datalake Gen1 with fsspec and dask
Home-page: 
Author: 
Author-email: 
License: BSD
Location: C:\Users\ivwebber\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires: aiohttp, azure-core, azure-datalake-store, azure-identity, azure-storage-blob, fsspec
Required-by: 

Name: ray
Version: 2.39.0
Summary: Ray provides a simple, universal API for building distributed applications.
Home-page: https://github.com/ray-project/ray
Author: Ray Team
Author-email: ray-dev@googlegroups.com
License: Apache 2.0
Location: C:\Users\ivwebber\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires: aiosignal, click, filelock, frozenlist, jsonschema, msgpack, packaging, protobuf, pyyaml, requests
Required-by: mapsai-ludi-common

Name: pyarrow
Version: 17.0.0
Summary: Python library for Apache Arrow
Home-page: https://arrow.apache.org/
Author: 
Author-email: 
License: Apache Software License
Location: C:\Users\ivwebber\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires: numpy
Required-by: datasets, mapsai-ludi-common

### Reproduction script

import adlfs
from azure.identity import DefaultAzureCredential
import ray.data
import pyarrow as pa
fss = adlfs.AzureBlobFileSystem(account_name="my_account", credential=DefaultAzureCredential())
paths = ['abfs://my_container@my_account.dfs.core.windows.net/multi_city/my/path/split=Split1/part=1.parquet']
ray.data.read_parquet(paths, filesystem=fss).count()
# run repeatedly; once it starts failing go to lunch and it will probably work once before starting to fail again but randomly work

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ivanthewebber** [comment]
Possibly related: #41125

**Comment by ivanthewebber** [comment]
I notice that there is also an error only reported with the program exits when I run the replication on the Python shell:
```sh
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\weakref.py", line 666, in _exitfunc
    f()
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\fsspec\asyn.py", line 103, in sync      
    raise return_result
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\fsspec\asyn.py", line 56, in _runner    
    result[0] = await coro
                ^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\adlfs\utils.py", line 78, in close_credential
    await file_obj.credential.close()
TypeError: object NoneType can't be used in 'await' expression
```

Also, I tried the fix as mentioned in #41125 and got this error:
```shell
>>> ray.data.read_parquet(paths, storage_options={'account_name': 'myaccount', 'anon': False}).count()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ray\data\read_api.py", line 750, in read_parquet
    datasource = ParquetDatasource(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ray\data\_internal\datasource\parquet_datasource.py", line 197, in __init__
    paths, filesystem = _resolve_paths_and_filesystem(paths, filesystem)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
107, in _resolve_paths_and_filesystem
    resolved_filesystem, resolved_path = _resolve_filesystem_and_path(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarrow\fs.py", line 179, in _resolve_filesystem_and_path
    filesystem, path = FileSystem.from_uri(path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow\\_fs.pyx", line 477, in pyarrow._fs.FileSystem.from_uri
  File "pyarrow\\error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: Got Azure Blob File System URI but Arrow compiled without Azure Blob File System support
```

**Comment by richardliaw** [comment]
#41125 seems promising...

unfortunately this is a bit hard for us to dig into due to Windows; i'd be curious to know if you see the same issue on Linux.
