### ISSUE TITLE
[Core] Job Incorrectly Reported as Success with Subreaper Enabled

### ISSUE THREAD

**Issue by ryansun96** [ray-project/ray#49119]
### What happened + What you expected to happen

When RAY_kill_child_processes_on_worker_exit_with_raylet_subreaper=true, if actor creation task fails, the job is still reported as successful.

Expected the job to fail. Logs below:

```
Job submission server address: http://127.0.0.1:8265
2024-12-06 01:41:42,110 INFO dashboard_sdk.py:338 -- Uploading package gcs://_ray_pkg_ea75f6d2c5e89698.zip.
2024-12-06 01:41:42,111 INFO packaging.py:601 -- Creating a file package for local module '.'.
-------------------------------------------------------
Job 'raysubmit_d9QW6nj2PycERu9K' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_d9QW6nj2PycERu9K
  Query the status of the job:
    ray job status raysubmit_d9QW6nj2PycERu9K
  Request the job to be stopped:
    ray job stop raysubmit_d9QW6nj2PycERu9K

Tailing logs until the job exits (disable with --no-wait):
2024-12-06 01:41:42,175 INFO job_manager.py:530 -- Runtime env is setting up.
2024-12-06 01:41:43,879 INFO worker.py:1496 -- Using address 127.0.0.1:6379 set in the environment variable RAY_ADDRESS
2024-12-06 01:41:43,883 INFO worker.py:1636 -- Connecting to existing Ray cluster at address: 127.0.0.1:6379...
2024-12-06 01:41:43,896 INFO worker.py:1812 -- Connected to Ray cluster. View the dashboard at http://127.0.0.1:8265 
(TestActor pid=297901) Exception raised in creation task: The actor died because of an error raised in its creation task, ray::TestActor:TestActor.__init__() (pid=297901, ip=127.0.0.1, actor_id=9a5fcbd0d11aa077e79ec4e204000000, repr=<TestExtractor.TestActor object at 0x7faeb7276d90>)
(TestActor pid=297901)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(TestActor pid=297901)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(TestActor pid=297901)   File "/tmp/ray/session_2024-12-06_01-35-21_883032_287054/runtime_resources/working_dir_files/_ray_pkg_ea75f6d2c5e89698/test.py", line 6, in __init__
(TestActor pid=297901)     raise NotImplementedError
(TestActor pid=297901) NotImplementedError
Traceback (most recent call last):
  File "/tmp/ray/session_2024-12-06_01-35-21_883032_287054/runtime_resources/working_dir_files/_ray_pkg_ea75f6d2c5e89698/test.py", line 20, in <module>
    results = ray.get(this_actor_ret)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/pyenv/versions/3.11.1/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/pyenv/versions/3.11.1/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/pyenv/versions/3.11.1/lib/python3.11/site-packages/ray/_private/worker.py", line 2755, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/pyenv/versions/3.11.1/lib/python3.11/site-packages/ray/_private/worker.py", line 908, in get_objects
    raise value
ray.exceptions.ActorDiedError: The actor died because of an error raised in its creation task, ray::TestActor:TestActor.__init__() (pid=297901, ip=127.0.0.1, actor_id=9a5fcbd0d11aa077e79ec4e204000000, repr=<TestExtractor.TestActor object at 0x7faeb7276d90>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2024-12-06_01-35-21_883032_287054/runtime_resources/working_dir_files/_ray_pkg_ea75f6d2c5e89698/test.py", line 6, in __init__
    raise NotImplementedError
NotImplementedError

------------------------------------------
Job 'raysubmit_d9QW6nj2PycERu9K' succeeded
------------------------------------------
```

### Versions / Dependencies

ray[default]: 2.40.0
Python: 3.11.1
Debian GNU/Linux 11 (bullseye)

### Reproduction script

```py
# test.py
import ray

@ray.remote
class TestActor:
    def __init__(self):
        raise NotImplementedError
    def start(self):
        pass

this_actor = TestActor.remote()
this_actor_ret = this_actor.start.remote()
results = ray.get(this_actor_ret)
```

```bash
export RAY_kill_child_processes_on_worker_exit_with_raylet_subreaper=true
ray start --head --include-dashboard=true
ray job submit --working-dir . -- python test.py
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by jjyao** [comment]
@rynewang can you take a look since you implemented the subreaper feature.
