### ISSUE TITLE
[data] empty dataset repartition cause exception

### ISSUE THREAD

**Issue by Jay-ju** [ray-project/ray#49215]
### What happened + What you expected to happen
```
    update_operator_states(topology)
  File "/data00/code/ray/python/ray/data/_internal/execution/streaming_executor_state.py", line 517, in update_operator_states
    op.all_inputs_done()
  File "/data00/code/ray/python/ray/data/_internal/execution/operators/base_physical_operator.py", line 104, in all_inputs_done
    self._output_buffer, self._stats = self._bulk_fn(self._input_buffer, ctx)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data00/code/ray/python/ray/data/_internal/planner/repartition.py", line 78, in split_repartition_fn
    return scheduler.execute(refs, num_outputs, ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data00/code/ray/python/ray/data/_internal/planner/exchange/split_repartition_task_scheduler.py", line 92, in execute
    reduce_block_refs, reduce_metadata = zip(*reduce_return)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)
ray.data.exceptions.SystemException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data00/code/dataset_identity/learn/ray_repartition.py", line 5, in <module>
    ds.take_all()
  File "/data00/code/ray/python/ray/data/dataset.py", line 2714, in take_all
    for row in self.iter_rows():
  File "/data00/code/ray/python/ray/data/iterator.py", line 213, in _wrapped_iterator
    for batch in batch_iterable:
  File "/data00/code/ray/python/ray/data/iterator.py", line 154, in _create_iterator
    ) = self._to_ref_bundle_iterator()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data00/code/ray/python/ray/data/_internal/iterator/iterator_impl.py", line 28, in _to_ref_bundle_iterator
    ref_bundles_iterator, stats, executor = ds._plan.execute_to_iterator()
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data00/code/ray/python/ray/data/exceptions.py", line 89, in handle_trace
    raise e.with_traceback(None) from SystemException()
ValueError: not enough values to unpack (expected 2, got 0)
```
### Versions / Dependencies

lastest version

### Reproduction script

```
import ray

ray.init()
ds = ray.data.from_items([]).repartition(10)
ds.take_all()

```

### Issue Severity

None

**Comment by richardliaw** [comment]
Noted on the PR, but reposting here -- don't think the behavior makes sense. Thanks!
