### ISSUE TITLE
[data] Arrow -> Numpy -> Arrow has unstable type conversions

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#49261]
### What happened + What you expected to happen

This might be inevitable since Pyarrow has more expressive types than Pandas, but when converting a Pyarrow type to Numpy / pandas, type information can be lost. 

This message will be raised:
```
(MapBatches(mapper) pid=12099) Failed to convert column 'messages' into pyarrow array due to: Error converting data to Arrow: column: 'messages', shape: (1,), dtype: object, data: [array([{'role': 'system', 'content': 'You are a helpful assistant that extracts information about a person in json.'}],
```

Eventually it does fall-back to pickle, but may be a source of user confusion/error/misunderstanding.

### Versions / Dependencies

master

### Reproduction script

`_test.jsonl`:

```json
{"messages":[{"role":"system","content":"You are a helpful assistant that extracts information about a person in json."}]}
{"messages":[{"role":"system","content":"You are a helpful assistant that extracts information about a person in json."}]}
```
script

```
import ray

ds = ray.data.read_json("./_test.jsonl")
ds = ds.random_sample(1)

def mapper(batch):
    return batch

ds = ds.map_batches(mapper, batch_size=1, concurrency=1)
```

Underneath the hood, this happens

```
import ray

ds = ray.data.read_json("./_test.jsonl")
ds = ds.random_sample(1)

def mapper(batch):
    from ray.data.block import BlockAccessor
    print(batch.schema)
    res = BlockAccessor.for_block(batch).to_numpy()
    print(len(res), list(res.values())[0].dtype)
    block = BlockAccessor.for_block(batch).batch_to_block(res)
    print(block.schema)
    return batch

ds = ds.map_batches(mapper, batch_size=1, concurrency=1, batch_format="pyarrow")
df = ds.to_pandas()
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by Bye-legumes** [comment]
There are no problem on 2.39 but it happens on 2.40. let me check which commit

**Comment by Bye-legumes** [comment]
It's related to https://github.com/ray-project/ray/commit/b5934e54c446fd4f5c28cf9b848c402f9a044357 this commit.

**Comment by richardliaw** [comment]
@alexeykudinkin could you take a look and let me know what you think?

**Comment by Bye-legumes** [comment]
The problem is this line, https://github.com/ray-project/ray/blob/836b4d2deefbc606ace49ccb9b8b3c48fa4bdb8d/python/ray/air/util/tensor_extensions/arrow.py#L1038 when it's string numpy, the dtype is object, while `from_numpy_dtype` can not accept object as input. If it's numpy string, the original dtype is 'U' and it can be used for from_numpy_dtype.
```
>>> a = np.array(["asdasd", "123123"])
>>> 
>>> a
array(['asdasd', '123123'], dtype='<U6')
```
so I can safe to call pd_type = pa.from_numpy_dtype(dtype). While I the array of numpy dtype is object, a.astype(object), we cannot call from_numpy_dtype with the error above. @richardliaw @alexeykudinkin

**Comment by alexeykudinkin** [comment]
This is happening b/c of Arrow not able to decode Numpy's object representation back into Arrow-native format. 

It does however fallback to ArrowPythonObjectType fallback and doesn't fail the pipeline (see the output)

```
2025-03-18 10:38:40,367	INFO streaming_executor.py:109 -- Execution plan of Dataset: InputDataBuffer[Input] -> TaskPoolMapOperator[ListFiles] -> TaskPoolMapOperator[ReadFiles] -> TaskPoolMapOperator[MapBatches(random_sample)] -> LimitOperator[limit=1]
✔️  Dataset execution finished in 0.45 seconds: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.00/1.00 [00:00<00:00, 2.25 row/s]
- ListFiles: Tasks: 0; Queued blocks: 0; Resources: 0.0 CPU, 0.0B object store: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.00/1.00 [00:00<00:00, 2.27 row/s]
- ReadFiles: Tasks: 0; Queued blocks: 0; Resources: 0.0 CPU, 0.0B object store: : 2.00 row [00:00, 4.54 row/s]
- MapBatches(random_sample): Tasks: 0; Queued blocks: 0; Resources: 0.0 CPU, 0.0B object store: : 2.00 row [00:00, 4.54 row/s]
- limit=1: Tasks: 0; Queued blocks: 0; Resources: 0.0 CPU, 95.0B object store: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.00/1.00 [00:00<00:00, 2.27 row/s]
Column    Type
------    ----
messages  list<item: struct<role: string, content: string>>
2025-03-18 10:38:40,821 INFO dataset.py:2809 -- Tip: Use `take_batch()` instead of `take() / show()` to return records in pandas or numpy batch format.
2025-03-18 10:38:40,823	INFO streaming_executor.py:108 -- Starting execution of Dataset. Full logs are in /tmp/ray/session_2025-03-18_10-38-38_768180_43609/logs/ray-data
2025-03-18 10:38:40,823	INFO streaming_executor.py:109 -- Execution plan of Dataset: InputDataBuffer[Input] -> TaskPoolMapOperator[ListFiles] -> TaskPoolMapOperator[ReadFiles] -> TaskPoolMapOperator[MapBatches(random_sample)] -> TaskPoolMapOperator[MapBatches(mapper)] -> LimitOperator[limit=2]
(MapBatches(mapper) pid=43627) Failed to convert column 'messages' into pyarrow array due to: Error converting data to Arrow: column: 'messages', shape: (1,), dtype: object, data: [array([{'role': 'system', 'content': 'You are a helpful assistant that extracts information about a person in json.'}],
(MapBatches(mapper) pid=43627)        dtype=object)     ...; falling back to serialize as pickled python objects
(MapBatches(mapper) pid=43627) Traceback (most recent call last):
(MapBatches(mapper) pid=43627)   File "/Users/ak/code/anyscale/runtime/python/ray/air/util/tensor_extensions/arrow.py", line 734, in from_numpy
(MapBatches(mapper) pid=43627)     return cls._from_numpy(arr)
(MapBatches(mapper) pid=43627)            ^^^^^^^^^^^^^^^^^^^^
(MapBatches(mapper) pid=43627)   File "/Users/ak/code/anyscale/runtime/python/ray/air/util/tensor_extensions/arrow.py", line 753, in _from_numpy
(MapBatches(mapper) pid=43627)     return ArrowVariableShapedTensorArray.from_numpy(arr)
(MapBatches(mapper) pid=43627)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(MapBatches(mapper) pid=43627)   File "/Users/ak/code/anyscale/runtime/python/ray/air/util/tensor_extensions/arrow.py", line 1179, in from_numpy
(MapBatches(mapper) pid=43627)     pa_dtype = pa.from_numpy_dtype(dtype)
(MapBatches(mapper) pid=43627)                ^^^^^^^^^^^^^^^^^^^^^^^^^^
(MapBatches(mapper) pid=43627)   File "pyarrow/types.pxi", line 5709, in pyarrow.lib.from_numpy_dtype
✔️  Dataset execution finished in 0.03 seconds: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.00/2.00 [00:00<00:00, 68.5 row/s]
(MapBatches(mapper) pid=43627)   File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
- ListFiles: Tasks: 0; Queued blocks: 0; Resources: 0.0 CPU, 0.0B object store: : 1.00 row [00:00, 37.3 row/s]
(MapBatches(mapper) pid=43627)   File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status00, 37.3 row/s]
- ReadFiles: Tasks: 0; Queued blocks: 0; Resources: 0.0 CPU, 0.0B object store: : 2.00 row [00:00, 74.0 row/s]
- MapBatches(random_sample): Tasks: 0; Queued blocks: 0; Resources: 0.0 CPU, 0.0B object store: : 2.00 row [00:00, 73.4 row/s]
(MapBatches(mapper) pid=43627) pyarrow.lib.ArrowNotImplementedError: Unsupported numpy type 17:00, 74.1 row/s]
- MapBatches(mapper): Tasks: 0; Queued blocks: 0; Resources: 0.0 CPU, 0.0B object store: : 2.00 row [00:00, 72.8 row/s]
(MapBatches(mapper) pid=43627)
- limit=2: Tasks: 0; Queued blocks: 0; Resources: 0.0 CPU, 530.0B object store: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.00/2.00 [00:00<00:00, 72.3 row/s]
(MapBatches(mapper) pid=43627) The above exception was the direct cause of the following exception:
(MapBatches(mapper) pid=43627)  Queued blocks: 0; Resources: 0.0 CPU, 0.0B object store: : 2.00 row [00:00, 72.9 row/s]
(MapBatches(mapper) pid=43627) Traceback (most recent call last):
(MapBatches(mapper) pid=43627)   File "/Users/ak/code/anyscale/runtime/python/ray/air/util/tensor_extensions/arrow.py", line 127, in convert_to_pyarrow_array
(MapBatches(mapper) pid=43627)     return ArrowTensorArray.from_numpy(ct store: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.00/2.00 [00:00<00:00, 72.5 row/s]
(MapBatches(mapper) pid=43627)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(MapBatches(mapper) pid=43627)   File "/Users/ak/code/anyscale/runtime/python/ray/air/util/tensor_extensions/arrow.py", line 740, in from_numpy
(MapBatches(mapper) pid=43627)     raise ArrowConversionError(data_str) from e
(MapBatches(mapper) pid=43627) ray.air.util.tensor_extensions.arrow.ArrowConversionError: Error converting data to Arrow: column: 'messages', shape: (1,), dtype: object, data: [array([{'role': 'system', 'content': 'You are a helpful assistant that extracts information about a person in json.'}],
(MapBatches(mapper) pid=43627)        dtype=object)     ...
{'messages': array([{'role': 'system', 'content': 'You are a helpful assistant that extracts information about a person in json.'}],
      dtype=object)}
{'messages': array([{'role': 'system', 'content': 'You are a helpful assistant that extracts information about a person in json.'}],
      dtype=object)}
```

**Comment by rbavery** [comment]
I'm getting a similar error. even though my types are built in python ints or numpy ints (I tried both), Ray converts these to object dtype when I use from_items.

```
print(patch_slices)

[{'band': (np.int64(0), np.int64(3)),
  'time': (np.int64(0), np.int64(1)),
  'y': (np.int64(0), np.int64(4096)),
  'x': (np.int64(0), np.int64(4096))},

...
```
the schema says it should be int64, but the schema doesn't match the type Ray internal converts the values to, object type numpy arrays
```
dataset = ray.data.from_items(patch_slices)
dataset.schema()
```
```
Column  Type
------  ----
band    list<item: int64>
time    list<item: int64>
y       list<item: int64>
x       list<item: int64>
```
this makes it so I can't use the result to subset an XarrayDataset, which requires integer values

```
x = dataset.take_batch(1)
ds[x] # fails
```

**Comment by alexeykudinkin** [comment]
Tracking in https://github.com/ray-project/ray/issues/59445
