### ISSUE TITLE
Failed to create actor. You set the async flag, but the actor does not have any coroutine functions.

### ISSUE THREAD

**Issue by btakita** [ray-project/ray#49285]
### What happened + What you expected to happen

I'm moving Python code to Cython. I created a wrapper Python Actor class for the Cython implementation methods. When staring the process, I got an error:

```
Failed to create actor. You set the async flag, but the actor does not have any coroutine functions.
```

I'm not sure how to create a reproduction. I'm unable to locate what code is failing. Could you help me by telling me where to look for the code that is raising this exception?

Full console output

```
2024-12-16 11:23:51,590: MainThread:Task-4: root:INFO: MainHub#terminate:begin
2024-12-16 11:23:51,593: MainThread:Task-4: root:ERROR: The actor died because of an error raised in its creation task, ray::BlendLipsyncActor:BlendLipsyncActor.__init__() (pid=2858809, ip=192.168.0.157, actor_id=b2f1d85c0def2fdb860609f901000000, repr=<lib.worker.blend_lipsync.FunctionActorManager._create_fake_actor_class.<locals>.TemporaryActor object at 0x7c3bbd95fa70>)
ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
        class_name: TemporaryActor
        actor_id: b2f1d85c0def2fdb860609f901000000
Failed to create actor. You set the async flag, but the actor does not have any coroutine functions.
2024-12-16 11:23:51,593: MainThread:Task-4: root:INFO: MainHub#terminate:end, dur=3.64ms
Traceback (most recent call last):
  File "/home/brian/work/project/livekit/agent/run_lib.py", line 40, in main
    run_app(opts, onstart=onstart)
  File "logtools.py", line 154, in logtools.LogWrap.log_begin_end.wraps.wrapper
  File "/home/brian/work/project/livekit/agent/lib/livekit_fork/cli.py", line 194, in run_app
    cli()
  File "/home/brian/work/project/livekit/agent/.venv-3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brian/work/project/livekit/agent/.venv-3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/brian/work/project/livekit/agent/.venv-3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brian/work/project/livekit/agent/.venv-3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brian/work/project/livekit/agent/.venv-3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brian/work/project/livekit/agent/lib/livekit_fork/cli.py", line 73, in start
    run_worker(args, onstart)
  File "logtools.py", line 154, in logtools.LogWrap.log_begin_end.wraps.wrapper
  File "/home/brian/work/project/livekit/agent/lib/livekit_fork/cli.py", line 257, in run_worker
    loop.run_until_complete(onstart(args))
  File "/home/brian/.pyenv/versions/3.12.7/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/brian/work/project/livekit/agent/run_lib.py", line 121, in onstart
    await main_hub.ready()
  File "logtools.py", line 217, in awrapper
  File "logtools.py", line 214, in logtools.LogWrap.log_begin_end_except.wraps.awrapper
  File "/home/brian/work/project/livekit/agent/lib/worker/main.py", line 26, in ready
    await asyncio.gather(
  File "/home/brian/.pyenv/versions/3.12.7/lib/python3.12/asyncio/tasks.py", line 684, in _wrap_awaitable
    return await awaitable
           ^^^^^^^^^^^^^^^
ray.exceptions.ActorDiedError: The actor died because of an error raised in its creation task, ray::BlendLipsyncActor:BlendLipsyncActor.__init__()(pid=2858809, ip=192.168.0.157, actor_id=b2f1d85c0def2fdb860609f901000000, repr=<lib.worker.blend_lipsync.FunctionActorManager._create_fake_actor_class.<locals>.TemporaryActor object at 0x7c3bbd95fa70>)
ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
        class_name: TemporaryActor
        actor_id: b2f1d85c0def2fdb860609f901000000
Failed to create actor. You set the async flag, but the actor does not have any coroutine functions.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/brian/work/project/livekit/agent/run.py", line 8, in <module>
    __main__()
  File "/home/brian/work/project/livekit/agent/run.py", line 6, in __main__
    run_lib.main()
  File "/home/brian/work/project/livekit/agent/run_lib.py", line 48, in main
    asyncio.run(main_hub.terminate())
  File "/home/brian/.pyenv/versions/3.12.7/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/brian/.pyenv/versions/3.12.7/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brian/.pyenv/versions/3.12.7/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "logtools.py", line 217, in awrapper
  File "logtools.py", line 214, in logtools.LogWrap.log_begin_end_except.wraps.awrapper
  File "/home/brian/work/project/livekit/agent/lib/worker/main.py", line 56, in terminate
    await asyncio.gather(
  File "/home/brian/.pyenv/versions/3.12.7/lib/python3.12/asyncio/tasks.py", line 684, in _wrap_awaitable
    return await awaitable
           ^^^^^^^^^^^^^^^
ray.exceptions.ActorDiedError: The actor died because of an error raised in its creation task, ray::BlendLipsyncActor:BlendLipsyncActor.__init__()(pid=2858809, ip=192.168.0.157, actor_id=b2f1d85c0def2fdb860609f901000000, repr=<lib.worker.blend_lipsync.FunctionActorManager._create_fake_actor_class.<locals>.TemporaryActor object at 0x7c3bbd95fa70>)
ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
        class_name: TemporaryActor
        actor_id: b2f1d85c0def2fdb860609f901000000
Failed to create actor. You set the async flag, but the actor does not have any coroutine functions.
```

### Versions / Dependencies

```
ray[data]==2.40.0
Python 3.12.7
Linux 6.12.4-zen1-1-zen
```

### Reproduction script

I'm not sure how to create a reproduction. I'm unable to locate what code is failing. Could you help me by telling me where to look for the code that is raising this exception?

I'll follow up with a proper reproduction or at least a smoking gun.

### Issue Severity

High: It blocks me from completing my task.

**Comment by btakita** [comment]
Note that it worked when `CyBlendLipsyncActor` is implemented in pure Python. But the error occurs when it's implemented in Cython with a stub.

**Comment by btakita** [comment]
I did a Google search & found
- https://github.com/ray-project/ray/blob/master/python/ray/_raylet.pyx#L1794-L1796
- https://github.com/ray-project/ray/issues/49146

**Comment by btakita** [comment]
I added a test for `has_async_methods` & it returns True.

```py
if __name__ == "__main__":

    def __main2__() -> None:
        from ray._raylet import has_async_methods

        print(f"has_async_methods(BlendLipsyncActor)={has_async_methods(BlendLipsyncActor)}")

__main2__()
```

```
has_async_methods(BlendLipsyncActor)=True
```

**Comment by btakita** [comment]
There was an upstream exception. However the exception is not logged. See https://github.com/ray-project/ray/blob/master/python/ray/_private/function_manager.py#L648-L658

**Comment by jjyao** [comment]
@btakita is my understanding right that you fixed the issue by moviung the import into the __init__ method. What we need to fix here is to make sure the right error message is surfaced to the user: i.e. `ModuleNotFoundError: No module named 'cy_blend_lipsync'`

**Comment by btakita** [comment]
@jjyao Yes. The original error needs to be printed in the logs.

**Comment by Dreamunk** [comment]
Great issue! I also encountered this problem
