### ISSUE TITLE
Unable to get ray.init() to work on a private cluster 

### ISSUE THREAD

**Issue by derasaria** [ray-project/ray#4936]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**:binary
- **Ray version**: 0.7.0
- **Python version**:3.5.2
- **Exact command to reproduce**: ray.init(redis_address='localhost:6379')

### Describe the problem

I am trying to set up ray on a small cluster and was following the instructions in the documentation [here](https://ray.readthedocs.io/en/latest/using-ray-on-a-cluster.html#deploying-ray-on-a-cluster).  Currently I am trying to run this for two nodes. If that succeeds I can add more nodes to the ray cluster. I ran the two commands mentioned in the link 
`ray start --head --redis-port=6379` on the head node and 
`ray start --redis-address=<redis-address>` on the worker node where the redis-address is the address shown after running the first command. 
Now, when I try initializing ray using the command `ray.init(redis_address="localhost:6379")`  I get an IPC connection error.  
![image](https://user-images.githubusercontent.com/45571618/58975799-af667c80-877a-11e9-9f3e-1c538dc324d0.png)

I guess this is something similar to the error on #3670 but I am not passing `object_store_memory` when initializing ray. My plasma object store is started with 5.01 GB memory by default. Is there an issue with memory here? 

### Source code / logs
 
The following error files may be of help. I could not make sense of what they meant. 
log_monitor.err
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ray/log_monitor.py", line 278, in <module>
    raise e
  File "/usr/local/lib/python3.5/dist-packages/ray/log_monitor.py", line 268, in <module>
    log_monitor.run()
  File "/usr/local/lib/python3.5/dist-packages/ray/log_monitor.py", line 219, in run
    anything_published = self.check_log_files_and_publish_updates()
  File "/usr/local/lib/python3.5/dist-packages/ray/log_monitor.py", line 175, in check_log_files_and_publish_updates
    next_line = file_info.file_handle.readline()
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 24: invalid start byte
```
plasma_store.err
```
external/plasma/cpp/src/plasma/store.cc:1100: Allowing the Plasma store to use up to 5.01099GB of memory.
external/plasma/cpp/src/plasma/store.cc:1127: Starting object store with directory /dev/shm and huge page support disabled
```

**Comment by robertnishihara** [comment]
Can you check if the plasma store on that machine is running? E.g., do `ps aux | grep plasma_store` and see what comes up.

Also, check the logs under `/tmp/ray/session_*/logs/*` and see if it looks like the plasma store or some other process has died. That might indicate what's going wrong.

**Comment by derasaria** [comment]
Thank you for your help. The issue was related to permission issues for non-privileged user. 

Now, I am able to run the command `ray.init(redis_address="localhost:6379")` on the head node but I cannot initalize ray on the worker node by running the command `ray.init(redis_address="<redis-address>")` where `<redis-address>` is the address I get when I started ray on the head node. 

I get the following error when running the command on `ray.init(redis_address="<redis-address>")` on the worker node.
```
2019-06-10 11:01:48,362 WARNING services.py:142 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2019-06-10 11:01:49,366 WARNING services.py:142 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2019-06-10 11:01:50,369 WARNING services.py:142 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2019-06-10 11:01:51,372 WARNING services.py:142 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2019-06-10 11:01:52,376 WARNING services.py:142 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/ray/worker.py", line 1446, in init
    ray_params, head=False, shutdown_at_exit=False, connect_only=True)
  File "/usr/local/lib/python3.5/dist-packages/ray/node.py", line 120, in __init__
    redis_password=self.redis_password)
  File "/usr/local/lib/python3.5/dist-packages/ray/services.py", line 135, in get_address_info_from_redis
    redis_address, node_ip_address, redis_password=redis_password)
  File "/usr/local/lib/python3.5/dist-packages/ray/services.py", line 119, in get_address_info_from_redis_helper
    "Redis has started but no raylets have registered yet.")
Exception: Redis has started but no raylets have registered yet.
```

I checked the log files on the worker node. 
The log from raylet.err file are below
```
I0610 10:30:42.474882 37234 stats.h:48] Succeeded to initialize stats: exporter address is 127.0.0.1:8888
W0610 10:32:49.724805 37234 redis_context.cc:190] Failed to connect to Redis, retrying.
W0610 10:34:57.084784 37234 redis_context.cc:190] Failed to connect to Redis, retrying.
W0610 10:37:04.444782 37234 redis_context.cc:190] Failed to connect to Redis, retrying.
W0610 10:39:11.804782 37234 redis_context.cc:190] Failed to connect to Redis, retrying.
W0610 10:41:19.164767 37234 redis_context.cc:190] Failed to connect to Redis, retrying.
W0610 10:43:26.524811 37234 redis_context.cc:190] Failed to connect to Redis, retrying.
W0610 10:45:33.884795 37234 redis_context.cc:190] Failed to connect to Redis, retrying.
W0610 10:47:41.244812 37234 redis_context.cc:190] Failed to connect to Redis, retrying.
W0610 10:49:48.604790 37234 redis_context.cc:190] Failed to connect to Redis, retrying.
W0610 10:51:55.964752 37234 redis_context.cc:190] Failed to connect to Redis, retrying.
```
Is it possible that the worker is not being able to communicate with the head node in some way?

**Comment by Romit-Maulik** [comment]
@derasaria I am curious what you utilized to solve this problem. I am facing the same issue where I am able to start Ray on 1 head and multiple workers but running rllib causes this error and the subsequent crash.
