### ISSUE TITLE
Tuple observation is failing to pass self.check_shape() in TupleFlatteningPreprocessor.transform()

### ISSUE THREAD

**Issue by roireshef** [ray-project/ray#4952]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.1 LTS
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.8.0-dev1 (current master branch)
- **Python version**: 3.6.7
- **Exact command to reproduce**: (just create any environment that has gym.spaces.Tuple observation space)

### Describe the problem
Tuple observation is failing to pass self.check_shape() in TupleFlatteningPreprocessor.transform()

TupleFlatteningPreprocessor.transform(..., observation) gets an observation of type np.ndarray, and sends it to self.check_shape(observation) that expects a tuple (since TupleFlatteningPreprocessor is only used when the env.observation_space is a gym.spaces.Tuple).

### Source code / logs

```
Traceback (most recent call last):
  File "/snap/pycharm-community/132/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/snap/pycharm-community/132/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-community/132/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/132/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/roi/code/Sandbox/flow_rl_framework/zipper_merge_rllib_main2.py", line 65, in <module>
    result = trainer.train()
  File "/home/roi/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 354, in train
    raise e
  File "/home/roi/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 340, in train
    result = Trainable.train(self)
  File "/home/roi/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 151, in train
    result = self._train()
  File "/home/roi/.local/lib/python3.6/site-packages/ray/rllib/agents/pg/pg.py", line 57, in _train
    self.optimizer.step()
  File "/home/roi/.local/lib/python3.6/site-packages/ray/rllib/optimizers/sync_samples_optimizer.py", line 58, in step
    samples.append(self.local_evaluator.sample())
  File "/home/roi/.local/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 440, in sample
    batches = [self.input_reader.next()]
  File "/home/roi/.local/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 60, in next
    batches = [self.get_data()]
  File "/home/roi/.local/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 101, in get_data
    item = next(self.rollout_provider)
  File "/home/roi/.local/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 317, in _env_runner
    soft_horizon)
  File "/home/roi/.local/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 405, in _process_observations
    policy_id).transform(raw_obs)
  File "/home/roi/.local/lib/python3.6/site-packages/ray/rllib/models/preprocessors.py", line 196, in transform
    self.check_shape(observation)
  File "/home/roi/.local/lib/python3.6/site-packages/ray/rllib/models/preprocessors.py", line 61, in check_shape
    self._obs_space, observation)
ValueError: ('Observation outside expected value range', Tuple(Box(3,), Box(1,), Box(10, 3), Box(2,)), array([array([0.69477439, 9.98484492, 0.09984845]), array([3]),
       array([[ 0.64849671,  0.64837028, -0.50265307],
       [ 0.26294763,  0.63082092,  0.12815474],
       [ 0.        ,  0.74881082, -0.0008589 ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]]),
       array([107.98,  20.  ])], dtype=object))
```

I followed this up with inspecting the observation argument in TupleFlatteningPreprocessor.transform(observation), and it appears to be a np.ndarray as can be seen above.

**Comment by Tabbi7** [comment]
I have the same problem when performing some experiments in Flow, especially with merge and bottleneck environments. We're in 2020. How to solve this?

**Comment by roireshef** [comment]
@Tabbi7 - that should have already been solved in newer Ray versions. the merge and bottleneck environments should work OOTB for you. Aren't they?
