### ISSUE TITLE
Fatal Python error: Bus error

### ISSUE THREAD

**Issue by NikEyX** [ray-project/ray#4989]
I keep on getting "Fatal Python error: Bus error" at random times in my code. I can't figure out what the problem is. Size of object store makes no difference. Currently I'm using `ray.init(object_store_memory=int(30.0 * 1e9), redis_max_memory=int(10.0 * 1e9))`. Tried it with ray version 0.7.1 and 0.8.0.dev0

```
(pid=4496) Fatal Python error: Bus error
(pid=4496) 
(pid=4496) Stack (most recent call first):
(pid=4496)   File "/home/xx/miniconda3/lib/python3.7/site-packages/ray/utils.py", line 479 in _wrapper
(pid=4496)   File "/home/xx/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 317 in store_and_register
(pid=4496)   File "/home/xx/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 383 in put_object
(pid=4496)   File "/home/xx/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 2219 in put
(pid=4496)   File "/home/xx/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 636 in submit_task
(pid=4496)   File "/home/xx/miniconda3/lib/python3.7/site-packages/ray/actor.py", line 554 in _actor_method_call
(pid=4496)   File "/home/xx/miniconda3/lib/python3.7/site-packages/ray/actor.py", line 164 in invocation
(pid=4496)   File "/home/xx/miniconda3/lib/python3.7/site-packages/ray/actor.py", line 170 in _remote
(pid=4496)   File "/home/xx/miniconda3/lib/python3.7/site-packages/ray/actor.py", line 149 in remote
(pid=4496)   File "ddqnPong6.py", line 395 in PlayEpisode
(pid=4496)   File "/home/xx/miniconda3/lib/python3.7/site-packages/ray/function_manager.py", line 792 in actor_method_executor
(pid=4496)   File "/home/xx/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 898 in _process_task
(pid=4496)   File "/home/xx/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 993 in _wait_for_and_process_task
(pid=4496)   File "/home/xx/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1042 in main_loop
(pid=4496)   File "/home/xx/miniconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 98 in <module>
(pid=4581) Traceback (most recent call last):
(pid=4581)   File "/home/xx/miniconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 98, in <module>
(pid=4581)     ray.worker.global_worker.main_loop()
(pid=4581)   File "/home/xx/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1041, in main_loop
(pid=4581)     task = self._get_next_task_from_raylet()
(pid=4581)   File "/home/xx/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1024, in _get_next_task_from_raylet
(pid=4581)     task = self.raylet_client.get_task()
(pid=4581)   File "python/ray/_raylet.pyx", line 245, in ray._raylet.RayletClient.get_task
(pid=4581)   File "python/ray/_raylet.pyx", line 60, in ray._raylet.check_status
(pid=4581) Exception: [RayletClient] Raylet connection closed.
(pid=4581) 
(pid=4581) During handling of the above exception, another exception occurred:
```

What could be going on?

**Comment by pcmoritz** [comment]
Hey NikEyX,

Do you have a way for us to reproduce it? An EC2 AMI would be perfect!

The only instance where I have seen a "Bus error" was when the memory
mapped file created by the object store was larger than the underlying file
system. How large is the filesystem in your case? (probably /dev/shm or
/tmp, it is printed after ray.init).

Best,
Philipp.

**Comment by NikEyX** [comment]
Omg, this was it! Not enough disk space. Can't believe I missed that. Thanks!!!
