### ISSUE TITLE
BipedalWalker-v2 errors

### ISSUE THREAD

**Issue by bionicles** [ray-project/ray#5001]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **Ray installed from (source or binary)**: pip
- **Ray version**: 0.7.1
- **Python version**: 3.6.8
- **Exact command to reproduce**: 

### Describe the problem
Seems like BipedalWalker-v2 doesn't work well with rllib algorithms.  There are various issues depending on the algorithm. The algorithms do work on CartPole and Atari on this rig. Other continuous envs seem to work OK

### Source code / logs
ppo:
```
import ray
from ray import tune

ray.init(num_gpus=1)
tune.run(
    "PPO",
    config={
        "env": "BipedalWalker-v2",
        "num_gpus": 1,
        "num_workers": 11,
        "lr": tune.grid_search([0.01, 0.001, 0.0001])
    },
)
```
[error_2019-06-19_12-45-00.txt](https://github.com/ray-project/ray/files/3307121/error_2019-06-19_12-45-00.txt)

impala 
```
Traceback (most recent call last):
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 436, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 323, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/worker.py", line 2189, in get
    raise value
ray.exceptions.RayTaskError: [36mray_worker[39m (pid=27691, host=bion-1070)
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 354, in train
    raise e
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 340, in train
    result = Trainable.train(self)
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/tune/trainable.py", line 151, in train
    result = self._train()
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/rllib/agents/impala/impala.py", line 155, in _train
    self.optimizer.step()
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/rllib/optimizers/async_samples_optimizer.py", line 132, in step
    assert self.learner.is_alive()
AssertionError
```

apex:
```
Traceback (most recent call last):
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 436, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 323, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/worker.py", line 2189, in get
    raise value
ray.exceptions.RayTaskError: [36mray_worker[39m (pid=847, host=bion-1070)
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 311, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/tune/trainable.py", line 88, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 424, in _setup
    self._init(self.config, self.env_creator)
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/rllib/agents/dqn/dqn.py", line 200, in _init
    env_creator, self._policy)
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 622, in make_local_evaluator
    extra_config or {}))
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 847, in _make_evaluator
    _fake_sampler=config.get("_fake_sampler", False))
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 321, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 727, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/rllib/agents/dqn/dqn_policy.py", line 354, in __init__
    action_space))
ray.rllib.utils.error.UnsupportedSpaceException: Action space Box(4,) is not supported for DQN.
```

APPO:
```
Traceback (most recent call last):
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 436, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 323, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/worker.py", line 2189, in get
    raise value
ray.exceptions.RayTaskError: [36mray_worker[39m (pid=2806, host=bion-1070)
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 354, in train
    raise e
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 340, in train
    result = Trainable.train(self)
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/tune/trainable.py", line 151, in train
    result = self._train()
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/rllib/agents/impala/impala.py", line 155, in _train
    self.optimizer.step()
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/ray/rllib/optimizers/async_samples_optimizer.py", line 132, in step
    assert self.learner.is_alive()
AssertionError
```

**Comment by bionicles** [comment]
sometimes the first trial fails right away then the second will run for a while. i'll let it run and see if the 2nd trial has different error

**Comment by ericl** [comment]
Are there known good hyperparameters for this environment you could try?

The crashing isn't expected though.

**Comment by thavlik** [comment]
I'm getting this with APPO on all trials.

```
2020-02-14 23:52:03,990	ERROR trial_runner.py:494 -- Trial APPO_MidconEnv_a25a2536: Error processing event.
Traceback (most recent call last):
  File "/ray/python/ray/tune/trial_runner.py", line 437, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/ray/python/ray/tune/ray_trial_executor.py", line 377, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/ray/python/ray/worker.py", line 1516, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): ray::APPO.train() (pid=246, ip=172.17.0.2)
  File "python/ray/_raylet.pyx", line 458, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 431, in function_executor
  File "/ray/python/ray/rllib/agents/trainer.py", line 472, in train
    raise e
  File "/ray/python/ray/rllib/agents/trainer.py", line 458, in train
    result = Trainable.train(self)
  File "/ray/python/ray/tune/trainable.py", line 254, in train
    result = self._train()
  File "/ray/python/ray/rllib/agents/trainer_template.py", line 122, in _train
    fetches = self.optimizer.step()
  File "/ray/python/ray/rllib/optimizers/async_samples_optimizer.py", line 129, in step
    assert self.learner.is_alive()
AssertionError
```

**Comment by pengzhenghao** [comment]
I found A2C / A3C / IMPALA performing bad in BipedalWalker-v2 (not only bad performance, but in most cases errors occur!)

It seems the environment is really incompatible with RLLib
