### ISSUE TITLE
ValueError: The argument None must be a bytes object.

### ISSUE THREAD

**Issue by LuckyHouse** [ray-project/ray#5119]
### System information
- Linux Ubuntu 19.04
- Ray installed from (conda env ==>pip):
- Ray version:0.72
- Python version:3.7.3

### Describe the problem
init problem with redis

### Source code / logs
import ray
ray.init(redis_address="xxxxxxxxxxx:xxxx",redis_password="xxxx")

errors:
Traceback (most recent call last):
  File "/home/hao/.vscode/extensions/ms-python.python-2019.6.22090/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/hao/.vscode/extensions/ms-python.python-2019.6.22090/pythonFiles/lib/python/ptvsd/__main__.py", line 434, in main
    run()
  File "/home/hao/.vscode/extensions/ms-python.python-2019.6.22090/pythonFiles/lib/python/ptvsd/__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/hao/miniconda3/envs/ray/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/hao/miniconda3/envs/ray/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/hao/miniconda3/envs/ray/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hao/ShengDongAi_Py/audio_server/test.py", line 2, in <module>
    ray.init(redis_address="xxxxxxx",redis_password="xxxx")
  File "/home/hao/miniconda3/envs/ray/lib/python3.7/site-packages/ray/worker.py", line 1442, in init
    ray_params, head=False, shutdown_at_exit=False, connect_only=True)
  File "/home/hao/miniconda3/envs/ray/lib/python3.7/site-packages/ray/node.py", line 102, in __init__
    redis_client.get("session_name"))
  File "/home/hao/miniconda3/envs/ray/lib/python3.7/site-packages/ray/utils.py", line 178, in decode
    "The argument {} must be a bytes object.".format(byte_str))
ValueError: The argument None must be a bytes object.

**Comment by jovany-wang** [comment]
Could you use `redis-cli` to check whether the redis-server has the key `session_name`?

**Comment by ehknight** [comment]
I'm having this problem too — I think what happens is:

1. Worker node starts
2. Head node starts
3. Worker node connect to head node
4. Worker tries to get `session_name` from the head node, resulting in the error above ([line](https://github.com/ray-project/ray/blob/dcd6d4949ca296b584f7090fb2249ae7a07b3e8f/python/ray/node.py#L101))
5. Head node sets `session_name` ([line](https://github.com/ray-project/ray/blob/dcd6d4949ca296b584f7090fb2249ae7a07b3e8f/python/ray/node.py#L145))

I was able to ameliorate this problem by adding a delay (the worker node waits for a while before trying to connect to the head node) so that the head node has time to set `session_name`. Maybe it would make sense for the worker node to try a couple times to get `session_name` before timing out?

**Comment by jovany-wang** [comment]
@ehknight  @LuckyHouse 
Could you please try to apply this patch and then test it? https://github.com/ray-project/ray/pull/4977

**Comment by LuckyHouse** [comment]
It seems not work.

Traceback (most recent call last):
  File "/home/hao/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/hao/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/__main__.py", line 434, in main
    run()
  File "/home/hao/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/hao/miniconda3/envs/ray/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/hao/miniconda3/envs/ray/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/hao/miniconda3/envs/ray/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hao/ShengDongAi_Py/audio_server/test.py", line 2, in <module>
    ray.init(redis_address="xxxxxxxx",redis_password="xxxx")
  File "/home/hao/miniconda3/envs/ray/lib/python3.7/site-packages/ray/worker.py", line 1442, in init
    ray_params, head=False, shutdown_at_exit=False, connect_only=True)
  File "/home/hao/miniconda3/envs/ray/lib/python3.7/site-packages/ray/node.py", line 101, in __init__
    self._wait_until_gcs_ready(redis_client)
  File "/home/hao/miniconda3/envs/ray/lib/python3.7/site-packages/ray/node.py", line 197, in _wait_until_gcs_ready
    raise Exception("Couldn't find GCS_READY flag!")
Exception: Couldn't find GCS_READY flag!

**Comment by LuckyHouse** [comment]
In Celery,i can start a worker through  'celery -A tasks worker --loglevel=info'.
How to start a worker in Ray  through 'init'?Or is it a  missunderstanding  of Ray?

**Comment by henryliu00** [comment]
> I'm having this problem too — I think what happens is:
> 
>     1. Worker node starts
> 
>     2. Head node starts
> 
>     3. Worker node connect to head node
> 
>     4. Worker tries to get `session_name` from the head node, resulting in the error above ([line](https://github.com/ray-project/ray/blob/dcd6d4949ca296b584f7090fb2249ae7a07b3e8f/python/ray/node.py#L101))
> 
>     5. Head node sets `session_name` ([line](https://github.com/ray-project/ray/blob/dcd6d4949ca296b584f7090fb2249ae7a07b3e8f/python/ray/node.py#L145))
> 
> 
> I was able to ameliorate this problem by adding a delay (the worker node waits for a while before trying to connect to the head node) so that the head node has time to set `session_name`. Maybe it would make sense for the worker node to try a couple times to get `session_name` before timing out?

@ehknight Could you please describe a little more detail about how you add the delay? I meet the same problem and I add `time.sleep` before this ([line](https://github.com/ray-project/ray/blob/dcd6d4949ca296b584f7090fb2249ae7a07b3e8f/python/ray/node.py#L100)) which didn't seem to help.

**Comment by jovany-wang** [comment]
> Exception: Couldn't find GCS_READY flag!


I guess your head node is not able to be started.

Could you please verity it?

**Comment by pengzhenghao** [comment]
I meet the same issue. I prevent the error by adding delay between the launching of nodes. For me, 15 seconds is not enough while 30 seconds can prevent this issue. 

Pseudo code looks like:

```
start head node
sleep 30 seconds

for each worker_node:
    start worker_node
    sleep 30 seconds
```

**Comment by richardliaw** [comment]
@pengzhenghao does this still happen on 1.0?
