### ISSUE TITLE
fail to run python3 custom_env.py on docker

### ISSUE THREAD

**Issue by zhaokang1228** [ray-project/ray#5122]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **Ray installed from (source or binary)**:binary
- **Ray version**:0.7.1
- **Python version**:3.5
- **Docker container from**:ray-project/deploy  images

 ` python3 custom_env.py` 
### Describe the problem

python3 from   apt-get  install python3-dev python3-pip
modoles from  pip3 install ...

**logs error:**
1. raise NotImplementedError
2.During handling of the above exception, another exception occurred:
    .....
  RuntimeError: Improper nesting of variable_scope.
3. AssertionError: Nesting violated for default stack of <class 'tensorflow.python.framework.ops.Graph'> objects

### Source code / logs

```
root@aeeedecda7a0:/ray/python/ray/rllib/examples# python3 custom_env.py 
WARNING: Logging before flag parsing goes to stderr.
W0705 06:47:51.971030 140309773559552 deprecation.py:323] From /usr/local/lib/python3.5/dist-packages/tensorflow/python/compat/v2_compat.py:61: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2019-07-05 06:47:52,310	INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-07-05_06-47-52_310723_4544/logs.
2019-07-05 06:47:52,419	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:17989 to respond...
2019-07-05 06:47:52,545	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:39626 to respond...
2019-07-05 06:47:52,549	INFO services.py:806 -- Starting Redis shard with 3.35 GB max memory.
2019-07-05 06:47:52,582	INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-07-05_06-47-52_310723_4544/logs.
2019-07-05 06:47:52,583	WARNING services.py:1323 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
2019-07-05 06:47:52,583	INFO services.py:1446 -- Starting the Plasma object store with 5.03 GB memory using /tmp.
2019-07-05 06:47:52,754	INFO tune.py:61 -- Tip: to resume incomplete experiments, pass resume='prompt' or resume=True to run()
2019-07-05 06:47:52,754	INFO tune.py:233 -- Starting a new experiment.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/8 CPUs, 0/0 GPUs
Memory usage on this node: 7.8/16.8 GB

2019-07-05 06:47:52,799	WARNING signature.py:108 -- The function with_updates has a **kwargs argument, which is currently not supported.
W0705 06:47:52.809562 140309773559552 deprecation_wrapper.py:119] From /usr/local/lib/python3.5/dist-packages/ray/tune/logger.py:136: The name tf.VERSION is deprecated. Please use tf.version.VERSION instead.

W0705 06:47:52.809955 140309773559552 deprecation_wrapper.py:119] From /usr/local/lib/python3.5/dist-packages/ray/tune/logger.py:141: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

2019-07-05 06:47:52,921	WARNING util.py:64 -- The `start_trial` operation took 0.13225626945495605 seconds to complete, which may be a performance bottleneck.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 2/8 CPUs, 0/0 GPUs
Memory usage on this node: 7.9/16.8 GB
Result logdir: /root/ray_results/PPO
Number of trials: 3 ({'PENDING': 2, 'RUNNING': 1})
PENDING trials:
 - PPO_SimpleCorridor_1_lr=0.0001:	PENDING
 - PPO_SimpleCorridor_2_lr=1e-06:	PENDING
RUNNING trials:
 - PPO_SimpleCorridor_0_lr=0.01:	RUNNING

2019-07-05 06:47:52,959	WARNING signature.py:108 -- The function with_updates has a **kwargs argument, which is currently not supported.
2019-07-05 06:47:53,037	WARNING signature.py:108 -- The function with_updates has a **kwargs argument, which is currently not supported.
(pid=4581) WARNING: Logging before flag parsing goes to stderr.
(pid=4581) W0705 06:47:55.105258 140405602789120 deprecation.py:323] From /usr/local/lib/python3.5/dist-packages/tensorflow/python/compat/v2_compat.py:61: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=4581) Instructions for updating:
(pid=4581) non-resource variables are not supported in the long term
(pid=4585) WARNING: Logging before flag parsing goes to stderr.
(pid=4585) W0705 06:47:55.127769 139960058849024 deprecation.py:323] From /usr/local/lib/python3.5/dist-packages/tensorflow/python/compat/v2_compat.py:61: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=4585) Instructions for updating:
(pid=4585) non-resource variables are not supported in the long term
(pid=4582) WARNING: Logging before flag parsing goes to stderr.
(pid=4582) W0705 06:47:55.177614 139621209581312 deprecation.py:323] From /usr/local/lib/python3.5/dist-packages/tensorflow/python/compat/v2_compat.py:61: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=4582) Instructions for updating:
(pid=4582) non-resource variables are not supported in the long term
(pid=4581) 2019-07-05 06:47:55,491	WARNING ppo.py:151 -- FYI: By default, the value function will not share layers with the policy model ('vf_share_layers': False).
(pid=4581) 2019-07-05 06:47:55,492	INFO rollout_worker.py:301 -- Creating policy evaluation worker 0 on CPU (please ignore any CUDA init errors)
(pid=4581) 2019-07-05 06:47:55.492595: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
(pid=4581) 2019-07-05 06:47:55.515063: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3591675000 Hz
(pid=4581) 2019-07-05 06:47:55.515514: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x546b4e0 executing computations on platform Host. Devices:
(pid=4581) 2019-07-05 06:47:55.515549: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
(pid=4581) W0705 06:47:55.522660 140405602789120 deprecation.py:323] From /usr/local/lib/python3.5/dist-packages/ray/rllib/models/fcnet.py:37: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
(pid=4581) Instructions for updating:
(pid=4581) Use keras.layers.dense instead.
2019-07-05 06:47:55,534	ERROR trial_runner.py:487 -- Error processing event.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ray/tune/trial_runner.py", line 436, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/usr/local/lib/python3.5/dist-packages/ray/tune/ray_trial_executor.py", line 323, in fetch_result
    result = ray.get(trial_future[0])
  File "/usr/local/lib/python3.5/dist-packages/ray/worker.py", line 2195, in get
    raise value
ray.exceptions.RayTaskError: ray_PPO:train() (pid=4581, host=aeeedecda7a0)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/models/model.py", line 85, in __init__
    restored, num_outputs, options)
  File "custom_env.py", line 61, in _build_layers_v2
    options)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/models/model.py", line 88, in __init__
    input_dict["obs"], num_outputs, options)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/models/fcnet.py", line 46, in _build_layers
    return output, last_layer
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 6524, in __exit__
    self._name_scope.__exit__(type_arg, value_arg, traceback_arg)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 4322, in name_scope
    yield "" if new_stack is None else new_stack + "/"
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/models/fcnet.py", line 37, in _build_layers
    name=label)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/core.py", line 187, in dense
    _reuse=reuse)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/core.py", line 110, in __init__
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/core.py", line 984, in __init__
    activity_regularizer=regularizers.get(activity_regularizer), **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 220, in __init__
    with vs.variable_scope(scope) as captured_scope:
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 2226, in __enter__
    self._graph_context_manager.__exit__(*sys.exc_info())
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5652, in get_controller
    yield g
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5459, in get_controller
    yield default
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5652, in get_controller
    yield g
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/context.py", line 530, in _mode
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5652, in get_controller
    yield g
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/models/model.py", line 85, in __init__
    restored, num_outputs, options)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/models/model.py", line 137, in _build_layers_v2
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

ray_PPO:train() (pid=4581, host=aeeedecda7a0)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/evaluation/rollout_worker.py", line 715, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/policy/tf_policy_template.py", line 128, in __init__
    obs_include_prev_action_reward=obs_include_prev_action_reward)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/policy/dynamic_tf_policy.py", line 139, in __init__
    seq_lens=existing_seq_lens)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/models/catalog.py", line 228, in get_model
    seq_lens)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/models/catalog.py", line 259, in _get_model
    seq_lens=seq_lens)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/models/model.py", line 88, in __init__
    input_dict["obs"], num_outputs, options)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/models/model.py", line 104, in _build_layers
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

ray_PPO:train() (pid=4581, host=aeeedecda7a0)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5459, in get_controller
    yield default
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5652, in get_controller
    yield g
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/context.py", line 530, in _mode
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5652, in get_controller
    yield g
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/agents/trainer.py", line 438, in _setup
    self._init(self.config, self.env_creator)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/agents/trainer_template.py", line 106, in _init
    self.config["num_workers"])
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/agents/trainer.py", line 483, in _make_workers
    logdir=self.logdir)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/evaluation/worker_set.py", line 64, in __init__
    RolloutWorker, env_creator, policy, 0, self._local_config)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/evaluation/worker_set.py", line 214, in _make_worker
    _fake_sampler=config.get("_fake_sampler", False))
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/evaluation/rollout_worker.py", line 311, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5652, in get_controller
    yield g
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5459, in get_controller
    yield default
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5652, in get_controller
    yield g
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/context.py", line 530, in _mode
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5652, in get_controller
    yield g
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/evaluation/rollout_worker.py", line 311, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5459, in get_controller
    yield default
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/evaluation/rollout_worker.py", line 311, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/evaluation/rollout_worker.py", line 715, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 2349, in __exit__
    traceback_arg)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 1932, in __exit__
    raise RuntimeError("Improper nesting of variable_scope.")
RuntimeError: Improper nesting of variable_scope.

During handling of the above exception, another exception occurred:

ray_PPO:train() (pid=4581, host=aeeedecda7a0)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/agents/trainer_template.py", line 87, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/agents/trainer.py", line 323, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/usr/local/lib/python3.5/dist-packages/ray/tune/trainable.py", line 87, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/agents/trainer.py", line 455, in _setup
    self.evaluation_metrics = self._evaluate()
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5652, in get_controller
    yield g
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5467, in get_controller
    type(default))
AssertionError: Nesting violated for default stack of <class 'tensorflow.python.framework.ops.Graph'> objects

2019-07-05 06:47:55,537	INFO ray_trial_executor.py:187 -- Destroying actor for trial PPO_SimpleCorridor_1_lr=0.0001. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2019-07-05 06:47:55,637	ERROR trial_runner.py:487 -- Error processing event.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ray/tune/trial_runner.py", line 436, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/usr/local/lib/python3.5/dist-packages/ray/tune/ray_trial_executor.py", line 323, in fetch_result
    result = ray.get(trial_future[0])
  File "/usr/local/lib/python3.5/dist-packages/ray/worker.py", line 2195, in get
    raise value
ray.exceptions.RayTaskError: ray_PPO:train() (pid=4585, host=aeeedecda7a0)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/models/model.py", line 85, in __init__
    restored, num_outputs, options)
  File "custom_env.py", line 61, in _build_layers_v2
    options)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/models/model.py", line 88, in __init__
    input_dict["obs"], num_outputs, options)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/models/fcnet.py", line 46, in _build_layers
    return output, last_layer
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 6524, in __exit__
    self._name_scope.__exit__(type_arg, value_arg, traceback_arg)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 4322, in name_scope
    yield "" if new_stack is None else new_stack + "/"
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/models/fcnet.py", line 37, in _build_layers
    name=label)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/core.py", line 187, in dense
    _reuse=reuse)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/core.py", line 110, in __init__
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/core.py", line 984, in __init__
    activity_regularizer=regularizers.get(activity_regularizer), **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 220, in __init__
    with vs.variable_scope(scope) as captured_scope:
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 2226, in __enter__
    self._graph_context_manager.__exit__(*sys.exc_info())
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5652, in get_controller
    yield g
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5459, in get_controller
    yield default
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5652, in get_controller
    yield g
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/context.py", line 530, in _mode
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5652, in get_controller
    yield g
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/models/model.py", line 85, in __init__
    restored, num_outputs, options)
  File "/usr/local/lib/python3.5/dist-packages/ray/rllib/models/model.py", line 137, in _build_layers_v2
    raise NotImplementedError
NotImplementedError
......
......
......
......
2019-07-05 06:47:55,677	INFO ray_trial_executor.py:187 -- Destroying actor for trial PPO_SimpleCorridor_2_lr=1e-06. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
(pid=4582) 2019-07-05 06:47:55,650	WARNING ppo.py:151 -- FYI: By default, the value function will not share layers with the policy model ('vf_share_layers': False).
(pid=4582) 2019-07-05 06:47:55,651	INFO rollout_worker.py:301 -- Creating policy evaluation worker 0 on CPU (please ignore any CUDA init errors)
(pid=4582) 2019-07-05 06:47:55.652088: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
(pid=4582) 2019-07-05 06:47:55.659176: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3591675000 Hz
(pid=4582) 2019-07-05 06:47:55.659484: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x6551d00 executing computations on platform Host. Devices:
(pid=4582) 2019-07-05 06:47:55.659511: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
(pid=4582) W0705 06:47:55.666308 139621209581312 deprecation.py:323] From /usr/local/lib/python3.5/dist-packages/ray/rllib/models/fcnet.py:37: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
(pid=4582) Instructions for updating:
(pid=4582) Use keras.layers.dense instead.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/8 CPUs, 0/0 GPUs
Memory usage on this node: 8.6/16.8 GB
Result logdir: /root/ray_results/PPO
Number of trials: 3 ({'ERROR': 3})
ERROR trials:
 - PPO_SimpleCorridor_0_lr=0.01:	ERROR, 1 failures: /root/ray_results/PPO/PPO_SimpleCorridor_0_lr=0.01_2019-07-05_06-47-52ppk_76me/error_2019-07-05_06-47-55.txt
 - PPO_SimpleCorridor_1_lr=0.0001:	ERROR, 1 failures: /root/ray_results/PPO/PPO_SimpleCorridor_1_lr=0.0001_2019-07-05_06-47-52fvy25pj7/error_2019-07-05_06-47-55.txt
 - PPO_SimpleCorridor_2_lr=1e-06:	ERROR, 1 failures: /root/ray_results/PPO/PPO_SimpleCorridor_2_lr=1e-06_2019-07-05_06-47-53dr8u1kio/error_2019-07-05_06-47-55.txt

Traceback (most recent call last):
  File "custom_env.py", line 83, in <module>
    "corridor_length": 5,
  File "/usr/local/lib/python3.5/dist-packages/ray/tune/tune.py", line 273, in run
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_SimpleCorridor_0_lr=0.01, PPO_SimpleCorridor_1_lr=0.0001, PPO_SimpleCorridor_2_lr=1e-06])

```

**Comment by ericl** [comment]
Can you try that latest wheels? I think this is an issue introduced with TF1.14 (or you can also try downgrading TensorFlow).

**Comment by zhaokang1228** [comment]
> Can you try that latest wheels? I think this is an issue introduced with TF1.14 (or you can also try downgrading TensorFlow).
> 
> The master version of RLlib has a workaround for this bug.

Thank you! I try downgrading Tensorflow,then it is successful！
