### ISSUE TITLE
Segfault in ray.get

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#519]
The following script seems to crash in ray.get:

```python
# The goal of this exercise is to combine a handful of lessons in a single
# example and to get some practice parallelizing serial code. In this exercise,
# we create a neural network and a gym environment and use the network to do
# some rollouts (that is, we use the neural net to choose actions to take in
# the environment). However, all of the rollouts are done serially.
#
# EXERCISE: Change this code to do rollouts in parallel by making an actor that
# creates both the "env" object and the "policy" object in its constructor. The
# "rollout" function should then be a method of the actor class.

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import psutil
import ray
import tensorflow as tf
import time

from ray_tutorial.reinforce.env import BatchedEnv
from ray_tutorial.reinforce.policy import ProximalPolicyLoss
from ray_tutorial.reinforce.filter import MeanStdFilter
from ray_tutorial.reinforce.rollout import rollouts, add_advantage_values

from ray_tutorial.reinforce.env import (NoPreprocessor, AtariRamPreprocessor,
                                        AtariPixelPreprocessor)
from ray_tutorial.reinforce.models.fc_net import fc_net
from ray_tutorial.reinforce.models.vision_net import vision_net

config = {"kl_coeff": 0.2,
          "num_sgd_iter": 30,
          "sgd_stepsize": 5e-5,
          "sgd_batchsize": 128,
          "entropy_coeff": 0.0,
          "clip_param": 0.3,
          "kl_target": 0.01,
          "timesteps_per_batch": 40000}


if __name__ == "__main__":
  ray.init(num_cpus=4, redirect_output=True)

  # For a more interesting example, try this with the following values. Note
  # that this will require installing gym with the atari environments. You'll
  # probably want to use a smaller batchsize for this.
  #
  #     name = "Pong-v0"
  #     preprocessor = AtariPixelPreprocessor()

  name = "CartPole-v0"
  batchsize = 100
  preprocessor = NoPreprocessor()
  gamma = 0.995
  lam = 1.0
  horizon = 2000

  @ray.actor
  class Agent(object):
    def __init__(self, name, batchsize, config):
      preprocessor = NoPreprocessor()
      self.env = BatchedEnv(name, batchsize, preprocessor=preprocessor)
      with tf.Graph().as_default():
        self.sess = tf.Session()
        if preprocessor.shape is None:
          preprocessor.shape = self.env.observation_space.shape
        self.policy = ProximalPolicyLoss(self.env.observation_space, self.env.action_space,
                                         preprocessor, config, self.sess)
        self.observation_filter = MeanStdFilter(preprocessor.shape, clip=None)
        self.reward_filter = MeanStdFilter((), clip=None)
        self.sess.run(tf.global_variables_initializer())
    def rollout(self):
      # Collect some rollouts.
      trajectory = rollouts(self.policy, self.env, horizon, self.observation_filter,
                            self.reward_filter)
      add_advantage_values(trajectory, gamma, lam, self.reward_filter)
      print(trajectory)
      return trajectory

  # Create a simulator environment. This is a wrapper containing a batch of gym
  # environments. The simulator can be simulated with "env.step(action)", which
  # is called within the "rollouts" function below.
  #env = BatchedEnv(name, batchsize, preprocessor=preprocessor)

  # Create a neural net policy. Note that we create the neural net inside its
  # own graph. This can help avoid variable name collisions. It shouldn't
  # matter in this example, but if you create a neural net inside of a remote
  # function, and multiple tasks execute that remote function on the same
  # worker, then this can lead to variable name collisions.
  #with tf.Graph().as_default():
  #  sess = tf.Session()
  #  if preprocessor.shape is None:
  #    preprocessor.shape = env.observation_space.shape
  #  policy = ProximalPolicyLoss(env.observation_space, env.action_space,
  #                              preprocessor, config, sess)
  #  observation_filter = MeanStdFilter(preprocessor.shape, clip=None)
  #  reward_filter = MeanStdFilter((), clip=None)
  #  sess.run(tf.global_variables_initializer())

  # Note that directly making this function a remote function will give a
  # pickling error. That happens because when we define a remote function, we
  # pickle the function definition and ship the definition to the workers.
  # However, this function uses "policy", which is a TensorFlow neural net, and
  # TensorFlow often cannot be pickled. This could be addressed by constructing
  # "policy" within the rollout function, but in this case it's better to
  # create an actor that creates the policy in its constructor (so that we can
  # reuse the policy between multiple calls to "rollout").
  #def rollout():
    # Collect some rollouts.
  #  trajectory = rollouts(policy, env, horizon, observation_filter,
  #                        reward_filter)
  #  add_advantage_values(trajectory, gamma, lam, reward_filter)
  #  return trajectory

  # Do some rollouts to make sure that all of the neural nets have been
  # constructed. This isn't relevant for the serial code, but when we create
  # the neural nets in the background using actors, we don't want the time to
  # create the actors to interfere with the timing measurement below. Make sure
  # that this code uses all of the actors.

  start_time = time.time()

  # Do some rollouts serially. These should be done in parallel.
  #collected_rollouts = [rollout() for _ in range(20)]
  agent = Agent(name, batchsize, config)

  
  collected_rollouts = [agent.rollout() for _ in range(20)]
  collected_rollouts = ray.get(collected_rollouts)

  end_time = time.time()
  duration = end_time - start_time

  expected_duration = np.ceil(20 / psutil.cpu_count()) * 0.5
  assert duration < expected_duration, ("Rollouts took {} seconds. This is "
                                        "too slow.".format(duration))

  print("Success! The example took {} seconds.".format(duration))
```

**Comment by pcmoritz** [comment]
Backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
__atomic_add_dispatch (__val=1, __mem=0x29)
    at /usr/include/c++/4.8/ext/atomicity.h:96
96	      __atomic_add(__mem, __val);
(gdb) bt
#0  __atomic_add_dispatch (__val=1, __mem=0x29)
    at /usr/include/c++/4.8/ext/atomicity.h:96
#1  _M_add_ref_copy (this=0x21)
    at /usr/include/c++/4.8/bits/shared_ptr_base.h:131
#2  __shared_count (__r=..., this=0x7fffffffba28)
    at /usr/include/c++/4.8/bits/shared_ptr_base.h:553
#3  __shared_ptr (this=0x7fffffffba20)
    at /usr/include/c++/4.8/bits/shared_ptr_base.h:779
#4  shared_ptr (this=0x7fffffffba20)
    at /usr/include/c++/4.8/bits/shared_ptr.h:103
#5  arrow::UnionArray::child (this=0x2ed3f08, pos=<optimized out>)
    at /home/pcmoritz/tmp/tmp/tmp/ray/src/numbuf/thirdparty/arrow/cpp/src/arrow/array.cc:427
#6  0x00007fffe649da8d in numbuf::DeserializeList(std::shared_ptr<arrow::Array>, int, int, _object*, std::vector<std::shared_ptr<arrow::Tensor>, std::allocator<std::shared_ptr<arrow::Tensor> > > const&, _object**) ()
   from /home/pcmoritz/anaconda3/lib/python3.5/site-packages/ray-0.0.1-py3.5.egg/ray/core/src/numbuf/libnumbuf.so
#7  0x00007fffe649be9a in numbuf::get_value(std::shared_ptr<arrow::Array>, int, int, _object*, std::vector<std::shared_ptr<arrow::Tensor>, std::allocator<std::shared_ptr<arrow::Tensor> > > const&, _object**) ()
   from /home/pcmoritz/anaconda3/lib/python3.5/site-packages/ray-0.0.1-py3.5.egg/ray/core/src/numbuf/libnumbuf.so
```

**Comment by robertnishihara** [comment]
The script works for me. Is this on the master branch?

**Comment by pcmoritz** [comment]
This is in the master rebased on the tip of arrow, so it doesn't affect the current master but needs to be fixed.

**Comment by robertnishihara** [comment]
Do you have a simpler script for reproducing it? E.g., it should be reproducible by just putting and getting the relevant object, right?

**Comment by pcmoritz** [comment]
More tests show that the problem was introduced in

https://github.com/apache/arrow/commit/a94c03a02f1da8fa61ac86ba2d6c5e91d29c5767
