### ISSUE TITLE
Supporting Dict observations for custom models in a MultiAgentEnvironment

### ISSUE THREAD

**Issue by mdkozlowski** [ray-project/ray#5212]
I'm using a custom model that makes use of an action mask to zero out invalid action probabilities. For this, I'm using an observation space that's a spaces.Dict with keys ["action_mask", "real_obs"].
When returning the observations and rewards on each environment step, I get the error:

```Traceback (most recent call last):
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 365, in train
    raise e
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 354, in train
    result = Trainable.train(self)
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 162, in train
    result = self._train()
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 126, in _train
    fetches = self.optimizer.step()
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 132, in step
    self.num_envs_per_worker, self.train_batch_size)
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/optimizers/rollout.py", line 29, in collect_samples
    next_sample = ray_get_and_free(fut_sample)
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/memory.py", line 33, in ray_get_and_free
    result = ray.get(object_ids)
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 2214, in get
    raise value
ray.exceptions.RayTaskError: ray_RolloutWorker:sample() (pid=25318, host=pop-os)
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 432, in sample
    batches = [self.input_reader.next()]
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 60, in next
    batches = [self.get_data()]
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 101, in get_data
    item = next(self.rollout_provider)
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 338, in _env_runner
    base_env.send_actions(actions_to_send)
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/env/base_env.py", line 390, in send_actions
    "{} vs {}".format(obs.keys(), rewards.keys()))
ValueError: Key set for obs and rewards must be the same: dict_keys(['real_obs', 'action_mask']) vs dict_keys(['team1', 'team2'])
```

Here is an example script:
```python
import gym.spaces as spaces
import numpy as np
from ray.rllib.env.multi_agent_env import MultiAgentEnv
from model.MaskedFCModel import MaskedActionsLSTM
from ray.tune.logger import pretty_print
from ray.rllib.utils import try_import_tf
from ray.rllib.agents.ppo import PPOTrainer
from ray.rllib.models import ModelCatalog
import ray

class StubbedEnv(MultiAgentEnv):
	def __init__(self, env_config):
		self.current_round = 0
		self.action_space = spaces.Discrete(5)
		self.observation_space = spaces.Dict(
			{	"real_obs": spaces.Box(low=-1, high=1, shape=(100,), dtype=np.float),
				"action_mask": spaces.Box(0, 1, shape=(5, ))
			})

	def reset(self):
		self.current_round = 0
		return {"team1": self.observation_space.sample(), "team2": self.observation_space.sample()}

	def step(self, action):
		self.current_round += 1

		action_mask = {"team1": np.random.choice(2, 5), "team2": np.random.choice(2, 5)}
		real_obs = {"team1": self.observation_space.sample(), "team2": self.observation_space.sample()}
		obs = {"real_obs": real_obs, "action_mask": action_mask}

		#obs = {"team1": {
		#		"real_obs": self.observation_space.sample(),
		#		"action_mask": np.random.choice(2, 5)
		#	},
		#	"team2": {
		#		"real_obs": self.observation_space.sample(),
		#		"action_mask": np.random.choice(2, 5)
		#	}}

		if self.current_round == 50:
			done = {"team1": True, "team2": True, "__all__": True}
		else:
			done = {"team1": False, "team2": False, "__all__": False}

		if np.random.random() >= 0.5:
			rewards = {"team1": 1, "team2": 1}
		else:
			rewards = {"team1": 0, "team2": 0}

		return obs, rewards, done, {}

tf = try_import_tf()

ray.init(num_cpus=1, num_gpus=0)

single_env = StubbedEnv({})
obs_space = single_env.observation_space
act_space = single_env.action_space

ModelCatalog.register_custom_model("MaskedActionsLSTM", MaskedActionsLSTM)

policies = {
	"team1": (None, obs_space, act_space, {}),
	"team2": (None, obs_space, act_space, {})
}

trainer = PPOTrainer(env=StubbedEnv, config={
	"env_config": {},
	"model": {
		"custom_model": "MaskedActionsLSTM",
		"custom_options": {
			"fcnet_hiddens": [128, 128],
			"lstm_cell_size": 256,
		},
		"state_shape": [256, 256],
	},
	"multiagent": {
		"policies": policies,
		"policy_mapping_fn": lambda agent_id: "team1",
		"policies_to_train": ["team1"]
	},
	"observation_filter": "NoFilter",
	"num_gpus": 0,
	"num_workers": 1,
	"use_gae": False,
	"batch_mode": "complete_episodes"
})

for idx in range(10):
	print("== Iteration", idx, "==")
	pretty_print(trainer.train())
```
The custom model using action masks used is: https://github.com/ray-project/ray/issues/5148
In my script I have two variations for ordering the observation dict: `{team1: {real_obs,action_mask}, {real_obs,action_mask}}` vs `{real_obs: {team1,team2}, action_mask: {team1,team2}}`. In the second case the error is:
```
Traceback (most recent call last):
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 365, in train
    raise e
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 354, in train
    result = Trainable.train(self)
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 162, in train
    result = self._train()
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 126, in _train
    fetches = self.optimizer.step()
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 132, in step
    self.num_envs_per_worker, self.train_batch_size)
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/optimizers/rollout.py", line 29, in collect_samples
    next_sample = ray_get_and_free(fut_sample)
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/memory.py", line 33, in ray_get_and_free
    result = ray.get(object_ids)
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 2214, in get
    raise value
ray.exceptions.RayTaskError: ray_RolloutWorker:sample() (pid=16622, host=pop-os)
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 432, in sample
    batches = [self.input_reader.next()]
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 60, in next
    batches = [self.get_data()]
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 101, in get_data
    item = next(self.rollout_provider)
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 317, in _env_runner
    soft_horizon)
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 405, in _process_observations
    policy_id).transform(raw_obs)
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py", line 231, in transform
    self.write(observation, array, 0)
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py", line 241, in write
    p.write(o, array, offset)
  File "/home/marcin/anaconda3/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py", line 172, in write
    observation, copy=False).ravel()
TypeError: float() argument must be a string or a number, not 'collections.OrderedDict'
```

**Comment by ericl** [comment]
{"team1": {"real_obs": ..., "action_mask": ...}, "team2": {"real_obs": ..., "action_mask": ...}} is the correct one, does that not work?

**Comment by mdkozlowski** [comment]
My mistake, that code results in that second exception in my original post.

**Comment by ericl** [comment]
This works:
```
		obs = {"team1": self.observation_space.sample(),
		       "team2": self.observation_space.sample()}
```
