### ISSUE TITLE
[rllib] Slow env raises learner queue timeout

### ISSUE THREAD

**Issue by antoine-galataud** [ray-project/ray#5260]
### System information
- **OS Platform and Distribution**: Ubuntu 16.04, Ubuntu 18.04
- **Ray installed from**: tested with both source and binary
- **Ray version**: 0.8.0-dev2 (source), 0.7.2 (binary)
- **Python version**: 3.6

### Describe the problem

I started to work on a problem that involves very slow envs: to give an idea, mean_env_wait_ms is around 20000ms. The reason for that is each time step requires a full run from an external, resource intensive simulation.
Unless setting train_batch_size and sample_batch_size to low values (<64), I usually get the following error:

```
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
     self.run()
   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/optimizers/aso_learner.py", line 48, in run
     self.step()
   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/optimizers/aso_learner.py", line 52, in step
     batch, _ = self.minibatch_buffer.get()
   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/optimizers/aso_minibatch_buffer.py", line 38, in get
     self.buffers[self.idx] = self.inqueue.get(timeout=300.0)
   File "/home/ubuntu/anaconda3/lib/python3.6/queue.py", line 172, in get
     raise Empty
 queue.Empty
```

Timeout value has already been increased recently (https://github.com/ray-project/ray/issues/4536). Also a recent bug fix helped to get rid of another exception (https://github.com/ray-project/ray/issues/5198, fixed in source).

Anyway, not sure it requires a change in current implementation, so any advice/tips on how to overcome this (and generally on how to deal with slow envs) much appreciated.

**Comment by ericl** [comment]
Does it make sense to make this timeout configurable?

**Comment by antoine-galataud** [comment]
`AsyncReplayOptimizer` has a different way to deal with this: the learner thread queue has no timeout thus blocks until an item is available. Why such difference with `AsyncSamplesOptimizer`?
