### ISSUE TITLE
Ray install fails on Ubuntu 16,by pip install -e . --verbose

### ISSUE THREAD

**Issue by zhaokang1228** [ray-project/ray#5305]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **Ray installed from (source or binary)**: null
- **Ray version**: null
- **Python version**:3.6.2
- **Exact command to reproduce**:

```
conda install libgcc

git clone https://github.com/ray-project/ray.git

# Install Bazel.
ray/ci/travis/install-bazel.sh

cd ray/python
pip install -e . --verbose 

```

### Describe the problem

I am  using Anaconda.Failed to install ray.

### Source code / logs
**error logs:**
```

(py36) kangkang@kangkang-Vostro-3900:~/ray/python$ pip install -e . --verbose
Created temporary directory: /tmp/pip-ephem-wheel-cache-cnu3fcx_
Created temporary directory: /tmp/pip-req-tracker-wo4yxtzh
Created requirements tracker '/tmp/pip-req-tracker-wo4yxtzh'
Created temporary directory: /tmp/pip-install-0ph02138
Obtaining file:///home/kangkang/ray111/python
  Added file:///home/kangkang/ray111/python to build tracker '/tmp/pip-req-tracker-wo4yxtzh'
    Running setup.py (path:/home/kangkang/ray111/python/setup.py) egg_info for package from file:///home/kangkang/ray111/python
    Running command python setup.py egg_info
    running egg_info
    writing ray.egg-info/PKG-INFO
    writing dependency_links to ray.egg-info/dependency_links.txt
    writing entry points to ray.egg-info/entry_points.txt
    writing requirements to ray.egg-info/requires.txt
    writing top-level names to ray.egg-info/top_level.txt
    reading manifest file 'ray.egg-info/SOURCES.txt'
    writing manifest file 'ray.egg-info/SOURCES.txt'
  Source in /home/kangkang/ray111/python has version 0.8.0.dev2, which satisfies requirement ray==0.8.0.dev2 from file:///home/kangkang/ray111/python
  Removed ray==0.8.0.dev2 from file:///home/kangkang/ray111/python from build tracker '/tmp/pip-req-tracker-wo4yxtzh'
Requirement already satisfied: numpy>=1.14 in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from ray==0.8.0.dev2) (1.17.0)
Requirement already satisfied: filelock in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from ray==0.8.0.dev2) (3.0.12)
Requirement already satisfied: funcsigs in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from ray==0.8.0.dev2) (1.0.2)
Requirement already satisfied: click in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from ray==0.8.0.dev2) (7.0)
Requirement already satisfied: colorama in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from ray==0.8.0.dev2) (0.4.1)
Requirement already satisfied: pytest in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from ray==0.8.0.dev2) (5.0.1)
Requirement already satisfied: pyyaml in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from ray==0.8.0.dev2) (5.1.1)
Requirement already satisfied: redis in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from ray==0.8.0.dev2) (3.3.0)
Requirement already satisfied: six>=1.0.0 in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from ray==0.8.0.dev2) (1.12.0)
Requirement already satisfied: protobuf>=3.8.0 in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from ray==0.8.0.dev2) (3.9.0)
Requirement already satisfied: atomicwrites>=1.0 in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from pytest->ray==0.8.0.dev2) (1.3.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from pytest->ray==0.8.0.dev2) (0.12.0)
Requirement already satisfied: importlib-metadata>=0.12 in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from pytest->ray==0.8.0.dev2) (0.19)
Requirement already satisfied: packaging in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from pytest->ray==0.8.0.dev2) (19.0)
Requirement already satisfied: attrs>=17.4.0 in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from pytest->ray==0.8.0.dev2) (19.1.0)
Requirement already satisfied: py>=1.5.0 in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from pytest->ray==0.8.0.dev2) (1.8.0)
Requirement already satisfied: more-itertools>=4.0.0 in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from pytest->ray==0.8.0.dev2) (7.2.0)
Requirement already satisfied: wcwidth in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from pytest->ray==0.8.0.dev2) (0.1.7)
Requirement already satisfied: setuptools in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from protobuf>=3.8.0->ray==0.8.0.dev2) (41.0.1)
Requirement already satisfied: zipp>=0.5 in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from importlib-metadata>=0.12->pytest->ray==0.8.0.dev2) (0.5.2)
Requirement already satisfied: pyparsing>=2.0.2 in /home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages (from packaging->pytest->ray==0.8.0.dev2) (2.4.1.1)
Installing collected packages: ray
  Running setup.py develop for ray
    Running command /home/kangkang/anaconda3/envs/py36/bin/python -c 'import setuptools, tokenize;__file__='"'"'/home/kangkang/ray111/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing ray.egg-info/PKG-INFO
    writing dependency_links to ray.egg-info/dependency_links.txt
    writing entry points to ray.egg-info/entry_points.txt
    writing requirements to ray.egg-info/requires.txt
    writing top-level names to ray.egg-info/top_level.txt
    reading manifest file 'ray.egg-info/SOURCES.txt'
    writing manifest file 'ray.egg-info/SOURCES.txt'
    running build_ext
    + set -e
    +++ dirname ../build.sh
    ++ cd ..
    ++ pwd
    + ROOT_DIR=/home/kangkang/ray111
    ++ uname
    + unamestr=Linux
    + [[ Linux == \L\i\n\u\x ]]
    + PARALLEL=1
    + RAY_BUILD_PYTHON=YES
    + RAY_BUILD_JAVA=NO
    + PYTHON_EXECUTABLE=
    + BUILD_DIR=
    + [[ 2 -gt 0 ]]
    + key=-p
    + case $key in
    + PYTHON_EXECUTABLE=/home/kangkang/anaconda3/envs/py36/bin/python
    + shift
    + shift
    + [[ 0 -gt 0 ]]
    + [[ -z /home/kangkang/anaconda3/envs/py36/bin/python ]]
    + echo 'Using Python executable /home/kangkang/anaconda3/envs/py36/bin/python.'
    Using Python executable /home/kangkang/anaconda3/envs/py36/bin/python.
    ++ PATH=/home/kangkang/anaconda3/envs/py36/bin:/opt/ros/kinetic/bin:/home/kangkang/anaconda3/bin:/home/kangkang/bin:/home/kangkang/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/kangkang/.bazel/bin
    ++ which bazel
    + BAZEL_EXECUTABLE=/home/kangkang/bin/bazel
    + echo 'Using Bazel executable /home/kangkang/bin/bazel.'
    Using Bazel executable /home/kangkang/bin/bazel.
    + RAY_BUILD_PYTHON=YES
    + RAY_BUILD_JAVA=NO
    + bash /home/kangkang/ray111/setup_thirdparty.sh /home/kangkang/anaconda3/envs/py36/bin/python
    + set -e
    +++ dirname /home/kangkang/ray111/setup_thirdparty.sh
    ++ cd /home/kangkang/ray111
    ++ pwd
    + ROOT_DIR=/home/kangkang/ray111
    + [[ -z /home/kangkang/anaconda3/envs/py36/bin/python ]]
    + PYTHON_EXECUTABLE=/home/kangkang/anaconda3/envs/py36/bin/python
    + echo 'Using Python executable /home/kangkang/anaconda3/envs/py36/bin/python.'
    Using Python executable /home/kangkang/anaconda3/envs/py36/bin/python.
    + RAY_BUILD_PYTHON=YES
    + RAY_BUILD_JAVA=NO
    + /home/kangkang/ray111/thirdparty/scripts/setup.sh /home/kangkang/anaconda3/envs/py36/bin/python
    + set -e
    +++ dirname /home/kangkang/ray111/thirdparty/scripts/setup.sh
    ++ cd /home/kangkang/ray111/thirdparty/scripts
    ++ pwd
    + TP_SCRIPT_DIR=/home/kangkang/ray111/thirdparty/scripts
    + TP_DIR=/home/kangkang/ray111/thirdparty/scripts/..
    + mkdir -p /home/kangkang/ray111/thirdparty/scripts/../build
    + mkdir -p /home/kangkang/ray111/thirdparty/scripts/../pkg
    + [[ -z /home/kangkang/anaconda3/envs/py36/bin/python ]]
    + PYTHON_EXECUTABLE=/home/kangkang/anaconda3/envs/py36/bin/python
    + echo 'Using Python executable /home/kangkang/anaconda3/envs/py36/bin/python.'
    Using Python executable /home/kangkang/anaconda3/envs/py36/bin/python.
    + [[ NO == \Y\E\S ]]
    + [[ YES == \Y\E\S ]]
    + echo 'Python library will be built.'
    Python library will be built.
    ++ uname
    + unamestr=Linux
    + bash /home/kangkang/ray111/thirdparty/scripts/build_modin.sh /home/kangkang/anaconda3/envs/py36/bin/python
    + set -e
    + [[ -z /home/kangkang/anaconda3/envs/py36/bin/python ]]
    + PYTHON_EXECUTABLE=/home/kangkang/anaconda3/envs/py36/bin/python
    ++ /home/kangkang/anaconda3/envs/py36/bin/python -c 'import sys; print(sys.version_info[0])'
    + PYTHON_VERSION=3
    +++ dirname /home/kangkang/ray111/thirdparty/scripts/build_modin.sh
    ++ cd /home/kangkang/ray111/thirdparty/scripts
    ++ pwd
    + TP_DIR=/home/kangkang/ray111/thirdparty/scripts/../
    + MODIN_VERSION=0.5.0
    + MODIN_WHEELS_FNAME=modin-0.5.0-py3-none-any.whl
    + MODIN_WHEELS_URL=https://github.com/modin-project/modin/releases/download/v0.5.0/
    + pushd /home/kangkang/ray111/thirdparty/scripts/..//../python/ray/
    ~/ray111/python/ray ~/ray111/python
    + rm -rf modin
    + mkdir modin
    + pushd modin
    ~/ray111/python/ray/modin ~/ray111/python/ray ~/ray111/python
    + curl -kL https://github.com/modin-project/modin/releases/download/v0.5.0/modin-0.5.0-py3-none-any.whl -o modin-0.5.0-py3-none-any.whl
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100   619    0   619    0     0    494      0 --:--:--  0:00:01 --:--:--   494
    100  208k  100  208k    0     0  25929      0  0:00:08  0:00:08 --:--:-- 43280
    + unzip modin-0.5.0-py3-none-any.whl
    Archive:  modin-0.5.0-py3-none-any.whl
      inflating: modin/__init__.py
      inflating: modin/error_message.py
      inflating: modin/backends/__init__.py
      inflating: modin/backends/base/__init__.py
      inflating: modin/backends/base/query_compiler.py
      inflating: modin/backends/pandas/__init__.py
      inflating: modin/backends/pandas/query_compiler.py
      inflating: modin/backends/pyarrow/__init__.py
      inflating: modin/backends/pyarrow/query_compiler.py
      inflating: modin/data_management/__init__.py
      inflating: modin/data_management/factories.py
      inflating: modin/data_management/utils.py
      inflating: modin/engines/__init__.py
      inflating: modin/engines/base/__init__.py
      inflating: modin/engines/base/io.py
      inflating: modin/engines/base/frame/__init__.py
      inflating: modin/engines/base/frame/axis_partition.py
      inflating: modin/engines/base/frame/partition.py
      inflating: modin/engines/base/frame/partition_manager.py
      inflating: modin/engines/base/series/__init__.py
      inflating: modin/engines/dask/__init__.py
      inflating: modin/engines/dask/pandas_on_dask_delayed/__init__.py
      inflating: modin/engines/dask/pandas_on_dask_delayed/io.py
      inflating: modin/engines/dask/pandas_on_dask_delayed/frame/__init__.py
      inflating: modin/engines/dask/pandas_on_dask_delayed/frame/axis_partition.py
      inflating: modin/engines/dask/pandas_on_dask_delayed/frame/partition.py
      inflating: modin/engines/dask/pandas_on_dask_delayed/frame/partition_manager.py
      inflating: modin/engines/dask/pandas_on_dask_delayed/series/__init__.py
      inflating: modin/engines/python/__init__.py
      inflating: modin/engines/python/pandas_on_python/__init__.py
      inflating: modin/engines/python/pandas_on_python/io.py
      inflating: modin/engines/python/pandas_on_python/frame/__init__.py
      inflating: modin/engines/python/pandas_on_python/frame/axis_partition.py
      inflating: modin/engines/python/pandas_on_python/frame/partition.py
      inflating: modin/engines/python/pandas_on_python/frame/partition_manager.py
      inflating: modin/engines/python/pandas_on_python/series/__init__.py
      inflating: modin/engines/ray/__init__.py
      inflating: modin/engines/ray/utils.py
      inflating: modin/engines/ray/generic/__init__.py
      inflating: modin/engines/ray/generic/io.py
      inflating: modin/engines/ray/generic/frame/__init__.py
      inflating: modin/engines/ray/generic/frame/partition_manager.py
      inflating: modin/engines/ray/generic/series/__init__.py
      inflating: modin/engines/ray/pandas_on_ray/__init__.py
      inflating: modin/engines/ray/pandas_on_ray/io.py
      inflating: modin/engines/ray/pandas_on_ray/frame/__init__.py
      inflating: modin/engines/ray/pandas_on_ray/frame/axis_partition.py
      inflating: modin/engines/ray/pandas_on_ray/frame/partition.py
      inflating: modin/engines/ray/pandas_on_ray/frame/partition_manager.py
      inflating: modin/engines/ray/pandas_on_ray/series/__init__.py
      inflating: modin/experimental/__init__.py
      inflating: modin/experimental/engines/__init__.py
      inflating: modin/experimental/engines/pandas_on_ray/__init__.py
      inflating: modin/experimental/engines/pandas_on_ray/io_exp.py
      inflating: modin/experimental/engines/pandas_on_ray/sql.py
      inflating: modin/experimental/engines/pyarrow_on_ray/__init__.py
      inflating: modin/experimental/engines/pyarrow_on_ray/io.py
      inflating: modin/experimental/engines/pyarrow_on_ray/frame/__init__.py
      inflating: modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py
      inflating: modin/experimental/engines/pyarrow_on_ray/frame/partition.py
      inflating: modin/experimental/engines/pyarrow_on_ray/frame/partition_manager.py
      inflating: modin/experimental/engines/pyarrow_on_ray/series/__init__.py
      inflating: modin/experimental/pandas/__init__.py
      inflating: modin/experimental/pandas/io_exp.py
      inflating: modin/pandas/__init__.py
      inflating: modin/pandas/base.py
      inflating: modin/pandas/concat.py
      inflating: modin/pandas/dataframe.py
      inflating: modin/pandas/datetimes.py
      inflating: modin/pandas/general.py
      inflating: modin/pandas/groupby.py
      inflating: modin/pandas/indexing.py
      inflating: modin/pandas/io.py
      inflating: modin/pandas/iterator.py
      inflating: modin/pandas/plotting.py
      inflating: modin/pandas/reshape.py
      inflating: modin/pandas/series.py
      inflating: modin/pandas/utils.py
      inflating: modin/pandas/index/__init__.py
      inflating: modin/pandas/index/partitioned_index.py
      inflating: modin/pandas/test/__init__.py
      inflating: modin/pandas/test/test_api.py
      inflating: modin/pandas/test/test_concat.py
      inflating: modin/pandas/test/test_dataframe.py
      inflating: modin/pandas/test/test_general.py
      inflating: modin/pandas/test/test_groupby.py
      inflating: modin/pandas/test/test_io.py
      inflating: modin/pandas/test/test_reshape.py
      inflating: modin/pandas/test/test_series.py
      inflating: modin/pandas/test/utils.py
      inflating: modin/sql/__init__.py
      inflating: modin/sql/connection.py
      inflating: modin-0.5.0.dist-info/LICENSE
      inflating: modin-0.5.0.dist-info/METADATA
      inflating: modin-0.5.0.dist-info/WHEEL
      inflating: modin-0.5.0.dist-info/top_level.txt
      inflating: modin-0.5.0.dist-info/RECORD
    + rm modin-0.5.0-py3-none-any.whl
    + popd
    ~/ray111/python/ray ~/ray111/python
    + popd
    ~/ray111/python
    + BUILD_DIR=/home/kangkang/ray111/build/
    + '[' '!' -d /home/kangkang/ray111/build/ ']'
    + pushd /home/kangkang/ray111/build/
    ~/ray111/build ~/ray111/python
    + /home/kangkang/anaconda3/envs/py36/bin/python -m pip install --target=/home/kangkang/ray111/python/ray/pyarrow_files pyarrow==0.14.0.RAY --find-links https://s3-us-west-2.amazonaws.com/arrow-wheels/50f14adecbb83228599a2dc57859e4ecbe054b92/index.html
    Looking in links: https://s3-us-west-2.amazonaws.com/arrow-wheels/50f14adecbb83228599a2dc57859e4ecbe054b92/index.html
    Collecting pyarrow==0.14.0.RAY
      Using cached https://s3-us-west-2.amazonaws.com/arrow-wheels/50f14adecbb83228599a2dc57859e4ecbe054b92/pyarrow-0.14.0.RAY-cp36-cp36m-manylinux1_x86_64.whl
    Collecting numpy>=1.14 (from pyarrow==0.14.0.RAY)
      Using cached https://files.pythonhosted.org/packages/19/b9/bda9781f0a74b90ebd2e046fde1196182900bd4a8e1ea503d3ffebc50e7c/numpy-1.17.0-cp36-cp36m-manylinux1_x86_64.whl
    Collecting six>=1.0.0 (from pyarrow==0.14.0.RAY)
      Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
    Installing collected packages: numpy, six, pyarrow
    Successfully installed numpy-1.17.0 pyarrow-0.14.0.RAY six-1.12.0
    WARNING: Target directory /home/kangkang/ray111/python/ray/pyarrow_files/numpy-1.17.0.dist-info already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /home/kangkang/ray111/python/ray/pyarrow_files/six-1.12.0.dist-info already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /home/kangkang/ray111/python/ray/pyarrow_files/numpy already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /home/kangkang/ray111/python/ray/pyarrow_files/pyarrow-0.14.0.RAY.dist-info already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /home/kangkang/ray111/python/ray/pyarrow_files/pyarrow already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /home/kangkang/ray111/python/ray/pyarrow_files/six.py already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /home/kangkang/ray111/python/ray/pyarrow_files/__pycache__ already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /home/kangkang/ray111/python/ray/pyarrow_files/bin already exists. Specify --upgrade to force replacement.
    + export PYTHON_BIN_PATH=/home/kangkang/anaconda3/envs/py36/bin/python
    + PYTHON_BIN_PATH=/home/kangkang/anaconda3/envs/py36/bin/python
    + '[' NO == YES ']'
    + '[' YES == YES ']'
    + /home/kangkang/bin/bazel build //:ray_pkg --verbose_failures
    Loading:
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    INFO: Call stack for the definition of repository 'com_github_grpc_grpc' which is a http_archive (rule definition at /home/kangkang/.cache/bazel/_bazel_kangkang/fdad53fb984a5da787cbcfc382e0fe17/external/bazel_tools/tools/build_defs/repo/http.bzl:229:16):
     - /home/kangkang/ray111/bazel/ray_deps_setup.bzl:105:5
     - /home/kangkang/ray111/WORKSPACE:5:1
    ERROR: An error occurred during the fetch of repository 'com_github_grpc_grpc':
       java.io.IOException: Error downloading [https://github.com/grpc/grpc/archive/76a381869413834692b8ed305fbe923c0f9c4472.tar.gz] to /home/kangkang/.cache/bazel/_bazel_kangkang/fdad53fb984a5da787cbcfc382e0fe17/external/com_github_grpc_grpc/76a381869413834692b8ed305fbe923c0f9c4472.tar.gz: Premature EOF
    DEBUG: Rule 'com_github_nelhage_rules_boost' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556014830 +0800"
    DEBUG: Rule 'com_github_jupp0r_prometheus_cpp' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "d0c773da8af3db99c543dd0413f4427d835170eddfd517bfeba104236a8d2c07"
    DEBUG: Rule 'com_github_checkstyle_java' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1552542575 +0800"
    ERROR: error loading package '': in /home/kangkang/ray111/bazel/ray_deps_build_all.bzl: Encountered error while reading extension file 'bazel/grpc_deps.bzl': no such package '@com_github_grpc_grpc//bazel': java.io.IOException: Error downloading [https://github.com/grpc/grpc/archive/76a381869413834692b8ed305fbe923c0f9c4472.tar.gz] to /home/kangkang/.cache/bazel/_bazel_kangkang/fdad53fb984a5da787cbcfc382e0fe17/external/com_github_grpc_grpc/76a381869413834692b8ed305fbe923c0f9c4472.tar.gz: Premature EOF
    ERROR: error loading package '': in /home/kangkang/ray111/bazel/ray_deps_build_all.bzl: Encountered error while reading extension file 'bazel/grpc_deps.bzl': no such package '@com_github_grpc_grpc//bazel': java.io.IOException: Error downloading [https://github.com/grpc/grpc/archive/76a381869413834692b8ed305fbe923c0f9c4472.tar.gz] to /home/kangkang/.cache/bazel/_bazel_kangkang/fdad53fb984a5da787cbcfc382e0fe17/external/com_github_grpc_grpc/76a381869413834692b8ed305fbe923c0f9c4472.tar.gz: Premature EOF
    INFO: Elapsed time: 482.420s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (0 packages loaded)
    FAILED: Build did NOT complete successfully (0 packages loaded)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/kangkang/ray111/python/setup.py", line 180, in <module>
        license="Apache 2.0")
      File "/home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/kangkang/anaconda3/envs/py36/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/kangkang/anaconda3/envs/py36/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/kangkang/anaconda3/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/home/kangkang/anaconda3/envs/py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/kangkang/anaconda3/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/kangkang/ray111/python/setup.py", line 73, in run
        subprocess.check_call(command)
      File "/home/kangkang/anaconda3/envs/py36/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '-p', '/home/kangkang/anaconda3/envs/py36/bin/python']' returned non-zero exit status 1.
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-wo4yxtzh'
ERROR: Command "/home/kangkang/anaconda3/envs/py36/bin/python -c 'import setuptools, tokenize;__file__='"'"'/home/kangkang/ray111/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" failed with error code 1 in /home/kangkang/ray111/python/
Exception information:
Traceback (most recent call last):
  File "/home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 910, in install
    install_options, global_options, prefix=prefix,
  File "/home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 766, in install_editable
    cwd=self.setup_py_dir,
  File "/home/kangkang/anaconda3/envs/py36/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/home/kangkang/anaconda3/envs/py36/bin/python -c 'import setuptools, tokenize;__file__='"'"'/home/kangkang/ray111/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" failed with error code 1 in /home/kangkang/ray111/python/

```

**Comment by jovany-wang** [comment]
Seems that failed to download `grpc`.

Could you attempt to  add a proxy to speed it up?

**Comment by zhaokang1228** [comment]
> Seems that failed to download `grpc`.
> 
> Could you attempt to add a proxy to speed it up?

Is there any other way? I don't have a proxy available now.
Or ，how to install  the latest wheels snapshot  offline without a network?

**Comment by zhaokang1228** [comment]
https://ray.readthedocs.io/en/latest/installation.html#trying-snapshots-from-master

No need to pip install -e .; just pip install the wheel
