### ISSUE TITLE
Unable to export non-default multiagent policy

### ISSUE THREAD

**Issue by martinstuder** [ray-project/ray#5339]
### System information
- **OS Platform and Distribution**: Linux Manjaro 18.0.4
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.2
- **Python version**: 3.6.9
- **Exact command to reproduce**:

```
run_experiments({
        "test": {
            "run": "PPO",
            "env": "molotow",
            "stop": {
                "training_iteration": 1000,
            },
            "config": {
                'gamma': 0.995,
                'lambda': 0.95,
                'kl_coeff': 1.0,
                'entropy_coeff': 0.0,
                'batch_mode': 'complete_episodes',
                "num_workers": 11,
                "num_gpus": 1,
                "num_sgd_iter": 20,
                "lr": 3e-4,
                "train_batch_size": 65536,
                "sgd_minibatch_size": 4096,
                "log_level": "INFO",
                "observation_filter": "NoFilter",
                "vf_share_layers": True,
                "clip_rewards": False,
                "multiagent": {
                    "policy_graphs": {
                        "my_policy": create_policy(...)
                    },
                    "policy_mapping_fn": tune.function(lambda agent_id: "my_policy")
                }
            },
            "checkpoint_freq": 100,
            "checkpoint_at_end": True,
            "keep_checkpoints_num": 10,
            "export_formats": [ExportFormat.CHECKPOINT, ExportFormat.MODEL]
        }
    })
```

### Describe the problem

Attempting to export the model by specifying `"export_formats": [ExportFormat.CHECKPOINT, ExportFormat.MODEL]` in the above config fails with

```
2019-08-01 10:22:26,181	ERROR trial_runner.py:487 -- Error processing event.
Traceback (most recent call last):
  File "/home/mstuder/.local/share/virtualenvs/molotow-mvyZpHe_/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 481, in _process_trial
    self.trial_executor.export_trial_if_needed(trial)
  File "/home/mstuder/.local/share/virtualenvs/molotow-mvyZpHe_/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 563, in export_trial_if_needed
    trial.runner.export_model.remote(trial.export_formats))
  File "/home/mstuder/.local/share/virtualenvs/molotow-mvyZpHe_/lib/python3.6/site-packages/ray/worker.py", line 2195, in get
    raise value
ray.exceptions.RayTaskError: ray_worker (pid=7385, host=falcon)
  File "/home/mstuder/.local/share/virtualenvs/molotow-mvyZpHe_/lib/python3.6/site-packages/ray/tune/trainable.py", line 366, in export_model
    return self._export_model(export_formats, export_dir)
  File "/home/mstuder/.local/share/virtualenvs/molotow-mvyZpHe_/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 758, in _export_model
    self.export_policy_checkpoint(path)
  File "/home/mstuder/.local/share/virtualenvs/molotow-mvyZpHe_/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 663, in export_policy_checkpoint
    export_dir, filename_prefix, policy_id)
  File "/home/mstuder/.local/share/virtualenvs/molotow-mvyZpHe_/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 686, in export_policy_checkpoint
    self.policy_map[policy_id].export_checkpoint(export_dir,
KeyError: 'default_policy'
```
It looks like `Trainer._export_model(...)` only supports exporting a policy named `default_policy`. Indeed, by naming the policy in the above config `default_policy` the export seems to work just fine.

**Comment by JVillella** [comment]
Dealing with this as well, but in my case I can't work around it. For multi-agent training using several policies - since I can't name them both `default_policy` - there's no way to checkpoint learning.
