### ISSUE TITLE
Cannot rollout APEX (dqn) Unknown config parameter `local_evaluator_tf_session_args` 

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#5359]
I can't see to play the checkpoint made via APEX (dqn).

Here is my script:
```
rllib rollout apex/checkpoint_51/checkpoint-51 --run APEX --env BreakoutNoFrameskip-v4 --steps 10000
```
and here is the error:

```
2019-08-02 16:52:27,807	ERROR log_sync.py:34 -- Log sync requires cluster to be setup with `ray up`.
Traceback (most recent call last):
  File "/Users/andriy/miniconda3/bin/rllib", line 10, in <module>
    sys.exit(cli())
  File "/Users/andriy/miniconda3/lib/python3.7/site-packages/ray/rllib/scripts.py", line 40, in cli
    rollout.run(options, rollout_parser)
  File "/Users/andriy/miniconda3/lib/python3.7/site-packages/ray/rllib/rollout.py", line 103, in run
    agent = cls(env=args.env, config=config)
  File "/Users/andriy/miniconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 87, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/Users/andriy/miniconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 328, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/Users/andriy/miniconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 99, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/Users/andriy/miniconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 429, in _setup
    self._allow_unknown_subkeys)
  File "/Users/andriy/miniconda3/lib/python3.7/site-packages/ray/tune/util.py", line 172, in deep_update
    raise Exception("Unknown config parameter `{}` ".format(k))
Exception: Unknown config parameter `local_evaluator_tf_session_args` 
```

**Comment by ericl** [comment]
I think this is because you're using a checkpoint saved from an older version of rllib. We don't guarantee compatibility there.

**Comment by drozzy** [comment]
YES! You were right.
Thank you so much!
