### ISSUE TITLE
Distributed hyper parameter Search is not working

### ISSUE THREAD

**Issue by KaleabTessera** [ray-project/ray#5362]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**: Installed using pip.
- **Ray version**: 0.7.2
- **Python version**: 3.7

### Describe the problem
Distributed hyper parameter search does not work. I am working on a cluster of computers and using slurm to manage running these nodes. When I run the commands specified below, the same hyperparameters are used by each node. E.g node 1 and node 2 both test the same parameters specified by the tune.grid_search params. Please assist.

### I have done the following:
1. On Head nodes:
```
ray start --head --redis-port=6379
```
2. On other nodes:
```
ray start --redis-address=HEAD_HOSTNAME:6379
```
```
ray.init(redis_address='HEAD_HOSTNAME:6379')
```
3. I followed this tutorial - https://ray.readthedocs.io/en/latest/tune-distributed.html. 
4. Used slurm to run my experiments.
```
srun python main.py --num-experiments 10 --epochs 10 --head 10.100.14.4:6379
```

##### Head Node
```
2019-08-03 15:19:02,878 INFO scripts.py:289 -- Using IP address 10.100.14.4 for this node.
2019-08-03 15:19:02,879 INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-08-03_15-19-02_878618_30580/logs.
2019-08-03 15:19:02,989 INFO services.py:409 -- Waiting for redis server at 127.0.0.1:6379 to respond...
2019-08-03 15:19:03,135 INFO services.py:409 -- Waiting for redis server at 127.0.0.1:61011 to respond...
2019-08-03 15:19:03,140 INFO services.py:806 -- Starting Redis shard with 3.35 GB max memory.
2019-08-03 15:19:03,160 INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-08-03_15-19-02_878618_30580/logs.
2019-08-03 15:19:03,163 INFO services.py:1446 -- Starting the Plasma object store with 5.02 GB memory using /dev/shm.
2019-08-03 15:19:03,193 INFO scripts.py:319 --
Started Ray on this node. You can add additional nodes to the cluster by calling

    ray start --redis-address 10.100.14.4:6379

from the node you wish to add. You can connect a driver to the cluster from Python by running

    import ray
    ray.init(redis_address="10.100.14.4:6379")

If you have trouble connecting from a different machine, check that your firewall is configured properly. If you wish to terminate the processes that have been started, run

    ray stop
```
##### On other Nodes:
```
2019-08-03 15:20:20,179 INFO services.py:409 -- Waiting for redis server at 10.100.14.4:6379 to respond...
2019-08-03 15:20:20,191 INFO scripts.py:363 -- Using IP address 10.100.14.8 for this node.
2019-08-03 15:20:20,217 INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-08-03_15-19-02_878618_30580/logs.
2019-08-03 15:20:20,218 INFO services.py:1446 -- Starting the Plasma object store with 5.02 GB memory using /dev/shm.
2019-08-03 15:20:20,254 INFO scripts.py:371 --
Started Ray on this node. If you wish to terminate the processes that have been started, run

    ray stop
2019-08-03 15:20:23,992 INFO tune.py:61 -- Tip: to resume incomplete experiments, pass resume='prompt' or resume=True to run()
2019-08-03 15:20:23,993 INFO tune.py:233 -- Starting a new experiment.
2019-08-03 15:20:23,994 INFO tune.py:61 -- Tip: to resume incomplete experiments, pass resume='prompt' or resume=True to run()
2019-08-03 15:20:23,994 INFO tune.py:61 -- Tip: to resume incomplete experiments, pass resume='prompt' or resume=True to run()
2019-08-03 15:20:23,994 INFO tune.py:233 -- Starting a new experiment.
2019-08-03 15:20:23,994 INFO tune.py:233 -- Starting a new experiment.
2019-08-03 15:20:23,996 INFO tune.py:61 -- Tip: to resume incomplete experiments, pass resume='prompt' or resume=True to run()
2019-08-03 15:20:23,996 INFO tune.py:233 -- Starting a new experiment.
2019-08-03 15:20:27,376 WARNING logger.py:139 -- Couldn't import TensorFlow - disabling TensorBoard logging.
2019-08-03 15:20:27,376 WARNING logger.py:233 -- Could not instantiate <class 'ray.tune.logger.TFLogger'> - skipping.
2019-08-03 15:20:27,381 WARNING logger.py:139 -- Couldn't import TensorFlow - disabling TensorBoard logging.
2019-08-03 15:20:27,381 WARNING logger.py:233 -- Could not instantiate <class 'ray.tune.logger.TFLogger'> - skipping.
2019-08-03 15:20:27,448 WARNING logger.py:139 -- Couldn't import TensorFlow - disabling TensorBoard logging.
2019-08-03 15:20:27,449 WARNING logger.py:233 -- Could not instantiate <class 'ray.tune.logger.TFLogger'> - skipping.
2019-08-03 15:20:27,485 WARNING logger.py:139 -- Couldn't import TensorFlow - disabling TensorBoard logging.
2019-08-03 15:20:27,485 WARNING logger.py:233 -- Could not instantiate <class 'ray.tune.logger.TFLogger'> - skipping.
2019-08-03 15:20:27,493 ERROR trial_runner.py:291 -- Trial Runner checkpointing failed.
Traceback (most recent call last):
  File "/home-mscluster/tkaleab/anaconda3/envs/research-dense-vs-sparse/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 289, in step
    self.checkpoint()
  File "/home-mscluster/tkaleab/anaconda3/envs/research-dense-vs-sparse/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 188, in checkpoint
    TrialRunner.CKPT_FILE_TMPL.format(self._session_str)))
FileNotFoundError: [Errno 2] No such file or directory: '/home-mscluster/tkaleab/ray_results/quick-start/.tmp_checkpoint' -> '/home-mscluster/tkaleab/ray_results/quick-start/experiment_state-2019-08$
2019-08-03 15:20:27,528 WARNING logger.py:139 -- Couldn't import TensorFlow - disabling TensorBoard logging.
2019-08-03 15:20:27,528 WARNING logger.py:233 -- Could not instantiate <class 'ray.tune.logger.TFLogger'> - skipping.
2019-08-03 15:20:27,534 WARNING logger.py:139 -- Couldn't import TensorFlow - disabling TensorBoard logging.
2019-08-03 15:20:27,534 WARNING logger.py:233 -- Could not instantiate <class 'ray.tune.logger.TFLogger'> - skipping.
2019-08-03 15:20:27,573 WARNING util.py:64 -- The `experiment_checkpoint` operation took 0.10909414291381836 seconds to complete, which may be a performance bottleneck.

```
#### Source Code
```
args = parser.parse_args()
    if(args.head):
        ray.init(redis_address=args.head)
    else:
        ray.init()
    sched = AsyncHyperBandScheduler(
        time_attr="training_iteration", metric="accuracy")

    if(args.search_strategy == "grid"):
        density = [tune.grid_search(density_range_formatted)]
        n_hiden_layers = tune.grid_search(n_hiden_layers_range)
    else:
        # Random sample from uniform dist
        density = np.random.uniform(0, 1.0, args.num_hidden_layers)
        train_set_size = 1

    all_trials = tune.run(
        run_train_test,
        name="quick-start",
        stop={"accuracy": 98},
        resources_per_trial={
            "cpu": 2,
            "gpu": int(not args.no_cuda)
        },
        scheduler=sched,
        verbose=1,
        config={
            "search_strategy": args.search_strategy,
            "batch_size": args.batch_size,
            "test_batch_size": args.test_batch_size,
            "nn_type": args.nn_type,
            "epochs": args.epochs,
            "lr": args.lr,
            "momentum": args.momentum,
            "no_cuda": args.no_cuda,
            "random_seeds": args.random_seeds,
            "max_active_weights": args.max_active_weights,
            "has_hidden_layer": args.has_hidden_layer,
            "num_experiments": args.num_experiments,
            "train_set_size": train_set_size,
            "log_on_comet": args.log_on_comet,
            "density": density,
            "num_hidden_layers": n_hiden_layers,
            "hidden_size": args.hidden_size,
            "save_model": args.save_model,
            "density_type": args.density_type
        }
    )
```

**Comment by richardliaw** [comment]
Thanks for opening this issue @KaleabTessera !

You only need to run the python script on the head, so after ray start on all of the workers, you don’t run any python scripts on the workers.

Maybe try `if not args.head, sys.exit`? This makes sure the workers don’t run.

BTW we only recently pushed the tune distributed docs, so there’s some parts that may be unclear - sorry about that. Let us know what you’d change.

**Comment by KaleabTessera** [comment]
Thanks for the prompt reply @richardliaw !

So just to confirm, I need to:
1. `ray start --head --redis-port=6379` on the head node.
2. `ray start --redis-address=HEAD_HOSTNAME:6379` && `ray.init(redis_address='HEAD_HOSTNAME:6379')` &&
`if not args.head, sys.exit` (to make sure workers only run if they receive head node param) on worker nodes.
3. Python script on head node. 

Can I run 1 & 3 before 2? I need them to run together because once I run the batch script, I am not sure if I can access the head node to run 3.

**Comment by richardliaw** [comment]
Oh, you just need to do the following:

1. `ray start --head --redis-port=6379`, `python script.py` on the head node
2. `ray start --redis-address=HEAD_HOSTNAME:6379` on other nodes, no python script needed.

The nice thing about ray is that you don't need to run the script on other nodes.
(I said the `sys.exit` because I didn't know if you could avoid running them on the other nodes).

Let me know if that makes sense!

**Comment by richardliaw** [comment]
I'll close this issue for now (and have updated the docs #5403). @KaleabTessera feel free to reopen if you still run into issues/have any questions!
