### ISSUE TITLE
Raylet misses heartbeats and dies — core dumped with "Check failed: erased == 1 "

### ISSUE THREAD

**Issue by ehknight** [ray-project/ray#5363]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu
- **Ray installed from (source or binary)**: Wheel
- **Ray version**: 0.8.0 (dev3)
- **Python version**: 3.6
- **Exact command to reproduce**:

### Describe the problem
I am running a stressful multi-node job using Ray, and after a couple hours of training, a node drops out of the cluster after missing too many heartbeats. A couple hours later, another node drops out.

Since the code is part of an ongoing project, I can't post it publicly. However, it might be helpful to know that there are two stateful actors, one called ReplayServer (referenced in the traceback below), which are frequently queried. I'd be more than happy to provide more logs or to run jobs with suggested changes and report back.

Any help or potential quick-and-dirty workarounds would be greatly appreciated! Thank you.

### Source code / logs
**Driver logs**
```
(Job runs normally for a couple hours)

2019-08-03 09:58:24,196	ERROR worker.py:1713 -- The node with client ID 6a16415bb1baa3dc2e753af42ab73ff900d87222 has been marked dead because the monitor has missed too many heartbeats from it.
2019-08-03 09:58:29,320	ERROR worker.py:1653 -- Possible unhandled error from worker: [36mray_ReplayServer:update_id()[39m (pid=10306, host=aaa-ray-cpu-worker--79411--002)
<traceback redacted>
    return ray_get_and_free(obj_id)
  File "/opt/conda/lib/python3.6/site-packages/ray/rllib/utils/memory.py", line 33, in ray_get_and_free
    result = ray.get(object_ids)
ray.exceptions.UnreconstructableError: Object 63f2eb23293920ff8e5950cc6905239b9bf6ffff is lost (either evicted or explicitly deleted) and cannot be reconstructed.

(Followed by a number of other UnreconstructableErrors)
```
Another thing of note: the following message is repeated a couple times when training begins. It happens hours before the crash though, and does not seem to impact running, up until the crash.
```
2019-08-03 06:27:37,945	ERROR worker.py:1713 -- This worker was asked to execute a function that it does not have registered. You may have to restart Ray.
```
However, right after the crash, we get the message again (after things are presumably reconstructed):
```
2019-08-03 09:59:01,461	ERROR worker.py:1713 -- This worker was asked to execute a function that it does not have registered. You may have to restart Ray.
```

**raylet.err on dead node**
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0803 06:25:42.209446 10233 stats.h:48] Succeeded to initialize stats: exporter address is 127.0.0.1:8888
I0803 06:25:42.213696 10233 redis_gcs_client.cc:145] RedisGcsClient::Connect finished with status OK
I0803 06:25:42.215800 10233 grpc_server.cc:36] ObjectManager server started, listening on 0.0.0.0:37351
I0803 06:25:42.233659 10233 grpc_server.cc:36] NodeManager server started, listening on 0.0.0.0:37205
I0803 06:25:42.234040 10233 grpc_server.cc:36] Raylet server started, listening on unix:///tmp/ray/session_2019-08-03_06-25-40_220803_4140/sockets/raylet
W0803 06:34:13.936645 10233 node_manager.cc:301] Last heartbeat was sent 681 ms ago 
W0803 06:34:34.127275 10233 node_manager.cc:301] Last heartbeat was sent 717 ms ago 
W0803 06:34:44.210914 10233 node_manager.cc:301] Last heartbeat was sent 767 ms ago 
W0803 06:35:24.500370 10233 node_manager.cc:301] Last heartbeat was sent 804 ms ago 
W0803 06:35:34.365236 10233 node_manager.cc:301] Last heartbeat was sent 650 ms ago 
W0803 06:35:41.629631 10233 node_manager.cc:379] GetObjectManagerProfileInfo handler took 436 ms.
W0803 06:35:57.623556 10233 node_manager.cc:301] Last heartbeat was sent 611 ms ago 
W0803 06:36:14.451664 10233 node_manager.cc:301] Last heartbeat was sent 529 ms ago 

(many other heartbeats)

W0803 09:57:02.003321 10233 node_manager.cc:301] Last heartbeat was sent 731 ms ago 
W0803 09:57:11.904124 10233 node_manager.cc:301] Last heartbeat was sent 588 ms ago 
W0803 09:57:42.104930 10233 node_manager.cc:301] Last heartbeat was sent 725 ms ago 
F0803 09:57:54.269484 10233 scheduling_queue.cc:398]  Check failed: erased == 1 
*** Check failure stack trace: ***
*** Aborted at 1564826274 (unix time) try "date -d @1564826274" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x27f9) received by PID 10233 (TID 0x7fcbc4af57c0) from PID 10233; stack trace: ***
    @     0x7fcbc46de390 (unknown)
    @     0x7fcbc3885428 gsignal
    @     0x7fcbc388702a abort
    @           0x71b829 google::logging_fail()
    @           0x71d55a google::LogMessage::Fail()
    @           0x71e863 google::LogMessage::SendToLog()
    @           0x71d282 google::LogMessage::Flush()
    @           0x71d471 google::LogMessage::~LogMessage()
    @           0x54d6e2 ray::RayLog::~RayLog()
    @           0x48c1fa ray::raylet::SchedulingQueue::RemoveBlockedTaskId()
    @           0x475503 ray::raylet::NodeManager::HandleTaskUnblocked()
    @           0x475d45 ray::raylet::NodeManager::HandleNotifyUnblockedRequest()
    @           0x434b46 _ZN5boost4asio6detail18completion_handlerIZN3ray3rpc14ServerCallImplINS4_20RayletServiceHandlerENS4_22NotifyUnblockedRequestENS4_20NotifyUnblockedReplyEE13HandleRequestEvEUlvE_E11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm
    @           0x42539d boost::asio::detail::scheduler::run()
    @           0x40f7a0 main
    @     0x7fcbc3870830 __libc_start_main
    @           0x41ff71 (unknown)
```

**plasma_store.err on dead node**
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0803 06:25:42.201635 10232 store.cc:1122] Allowing the Plasma store to use up to 64GB of memory.
I0803 06:25:42.201709 10232 store.cc:1149] Starting object store with directory /tmp and huge page support disabled
W0803 06:25:42.201725 10232 store.cc:1166] System memory request exceeds memory available in /tmp. The request is for 64000000000 bytes, and the amount available is 48663801446 bytes. You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
I0803 10:08:50.970991 10232 store.cc:721] Disconnecting client on fd 9
I0803 10:08:51.124953 10232 store.cc:721] Disconnecting client on fd 54
I0803 10:08:51.143673 10232 store.cc:721] Disconnecting client on fd 46
I0803 10:08:51.148792 10232 store.cc:721] Disconnecting client on fd 22
I0803 10:08:51.153379 10232 store.cc:721] Disconnecting client on fd 48
I0803 10:08:51.171540 10232 store.cc:721] Disconnecting client on fd 251

(Followed by a number of other disconnecting clients)
```

**reporter.err on dead node**
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/psutil/_common.py", line 342, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/psutil/_pslinux.py", line 1513, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/psutil/_common.py", line 345, in wrapper
    return fun(self)
  File "/opt/conda/lib/python3.6/site-packages/psutil/_pslinux.py", line 1559, in _parse_stat_file
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/opt/conda/lib/python3.6/site-packages/psutil/_common.py", line 587, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/84132/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/ray/reporter.py", line 176, in run
    self.perform_iteration()
  File "/opt/conda/lib/python3.6/site-packages/ray/reporter.py", line 165, in perform_iteration
    stats = self.get_all_stats()
  File "/opt/conda/lib/python3.6/site-packages/ray/reporter.py", line 156, in get_all_stats
    "workers": self.get_workers(),
  File "/opt/conda/lib/python3.6/site-packages/ray/reporter.py", line 131, in get_workers
    ]) for x in psutil.process_iter() if running_worker(x.name())
  File "/opt/conda/lib/python3.6/site-packages/ray/reporter.py", line 131, in <listcomp>
    ]) for x in psutil.process_iter() if running_worker(x.name())
  File "/opt/conda/lib/python3.6/site-packages/psutil/__init__.py", line 730, in name
    name = self._proc.name()
  File "/opt/conda/lib/python3.6/site-packages/psutil/_pslinux.py", line 1513, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/psutil/_pslinux.py", line 1611, in name
    name = self._parse_stat_file()['name']
  File "/opt/conda/lib/python3.6/site-packages/psutil/_pslinux.py", line 1524, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=84132)
```

**Comment by simon-mo** [comment]
Thanks for the issue. Yes the master branch is not yet stable. Especially after some refactoring of the internals. I have seen something like this during stress testing. 

However, can you try using the latest stable version? The 0.7.3 should be able to handle stressful workload. 

```
pip uninstall ray 
pip install ray
```

Thanks!

**Comment by ehknight** [comment]
Thanks @simon-mo! I'll try it out and reopen the issue if the errors crop up again.
