### ISSUE TITLE
Cluster issue, raylet failing on node: what():  bind: Address already in use

### ISSUE THREAD

**Issue by Deathn0t** [ray-project/ray#5399]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: SUSE Linux Enterprise Server 12 SP3
- **Ray installed from (source or binary)**: binary (pip install ray)
- **Ray version**: 0.7.3
- **Python version**: Python 3.6.6 |Anaconda, Inc.|
- **Exact command to reproduce**:

file: `create_ray_cluster.sh`
```
#!/bin/sh
#COBALT -A datascience
#COBALT -n 2
#COBALT -q debug-flat-quad
#COBALT -t 30

module unload trackdeps
module unload darshan
module unload xalt
# export MPICH_GNI_FORK_MODE=FULLCOPY # otherwise, fork() causes segfaults above 1024 nodes
export PMI_NO_FORK=1 # otherwise, mpi4py-enabled Python apps with custom signal handlers do not respond to sigterm
export KMP_AFFINITY=disabled # this can affect on-node scaling (test this)

# Required for Click_ to work: https://click.palletsprojects.com/en/7.x/python3/
export LC_ALL=C.UTF-8
export LANG=C.UTF-8

# Activate good python environment
source /projects/datascience/regele/dh-opt/bin/activate

# deactivate core dump (comment for debug)
ulimit -c 0

# Start cluster
aprun -n $COBALT_JOBSIZE -N 1  python /projects/datascience/regele/tuning-scripts/m1/go_ray.py
```

file `go_ray.py`
```
#!/usr/bin/env python
import os
import subprocess
import json
import socket
import signal
import logging
logging.basicConfig(
        filename='app.log',
        format='%(asctime)s | %(message)s',
        datefmt='%m/%d/%Y %I:%M:%S %p',
        level=logging.INFO)

import psutil
import ray
import time
from mpi4py import MPI

from redis.exceptions import ConnectionError

# opening ports as suggested in: https://github.com/ray-project/ray/issues/4393
REDIS_PORT          = 17650
REDIS_SHARD_PORTS   = 17651
NODE_MANAGER_PORT   = 12345
OBJECT_MANAGER_PORT = 12346

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

# EXIT

def on_exit(signum, stack):
    ray_stop()

def ray_stop():
    with open('stop.out', 'wb') as fp:
        subprocess.run(
            "ray stop",
            shell=True,
            check=True,
            stdout=fp,
            stderr=subprocess.STDOUT
        )

signal.signal(signal.SIGINT, on_exit)
signal.signal(signal.SIGTERM, on_exit)

# ...

def run_ray_head(head_ip):
    #--redis-shard-ports={REDIS_SHARD_PORTS} \
    #--node-manager-port={NODE_MANAGER_PORT} \
    #--object-manager-port={OBJECT_MANAGER_PORT}',
    with open('ray.log.head', 'wb') as fp:
        subprocess.run(
            f'ray start --head \
                    --node-ip-address={head_ip} \
                    --temp-dir=/projects/datascience/regele/ray/ \
                    --redis-port={REDIS_PORT}',
            shell=True,
            check=True,
            stdout=fp,
            stderr=subprocess.STDOUT
        )


def run_ray_worker(head_redis_address):
    #--node-manager-port={NODE_MANAGER_PORT} \
    #--object-manager-port={OBJECT_MANAGER_PORT}',
    with open(f'ray.log.{rank}', 'wb') as fp:
        subprocess.run(
            f'ray start --redis-address={head_redis_address} \
                    --temp-dir=/projects/datascience/regele/ray/',
            shell=True,
            check=True,
            stdout=fp,
            stderr=subprocess.STDOUT
        )

def fetch_ip():
    addrs_kind = "ipogif0"

    addrs = [
        x.address for k, v in psutil.net_if_addrs().items() if k == addrs_kind
                  for x in v if x.family == socket.AddressFamily.AF_INET
            ]

    return addrs[0]


@ray.remote
def calc(*args):
    res = sum(args)
    #with open('res.txt', 'w+') as f:
    #f.write(f'[{time.time()}]: {res}')
    return res

def master():
    head_ip = fetch_ip()
    if head_ip is None:
        raise RuntimeError("could not fetch head_ip")

    logging.info('Ready to run ray head')

    run_ray_head(head_ip)

    head_redis_address = f'{head_ip}:{REDIS_PORT}'

    logging.info(f'Head started at: {head_redis_address}')

    logging.info(f'Ready to broadcast head_redis_address: {head_redis_address}')

    head_redis_address = comm.bcast(head_redis_address, root=0)

    logging.info('Broadcast done...')

    logging.info('Waiting for workers to start...')

    comm.barrier() # waiting for ray_workers to start

    logging.info('Workers are all running!')

    logging.info('Ready to start driver!')

    driver(head_redis_address)

    comm.barrier() # waiting for driver to end
    ray.stop()

def driver(head_redis_address):
    logging.info(f'Starting driver, wants to connect to head at: {head_redis_address}')
    infos = None
    while infos is None: # Raylets can take some time to register
        try:
            infos = ray.init(redis_address=head_redis_address)
            logging.info(infos)
        except ConnectionError:
            logging.info('Quitting driver start-up...', exc_info=True)
            return
        except Exception as e:
            logging.info('Failed to init driver... sleeping for 1sec...', exc_info=True)
            time.sleep(1)

    logging.info(f'Driver started on: {fetch_ip()}')

    val_id = [calc.remote(*[i for i in range(10)]) for _ in range(10)]
    res = ray.get(val_id)
    logging.info(f'res: {str(res)}')

    # with open('ytopt.out', 'wb') as fp:
    #     logging.info("about to run ytopt subprocess...")
    #     # os.system(f'python -m ytopt.search.ambs --evaluator ray --redis-address {redis_address} --problem ytopt.benchmark.ackley.problem.Problem')
    #     subprocess.run(
    #        f'python -m ytopt.search.ambs --evaluator ray --redis-address {"localhost"} --problem ytopt.benchmark.ackley.problem.Problem',
    #        shell=True,
    #        stdout=fp,
    #        stderr=subprocess.STDOUT,
    #        check=True,
    #     )
    #     logging.info("ytopt subprocess is finished. exiting.")


def worker(run_driver=False):
    head_redis_address = None

    logging.info('Waiting for broadcast...')
    head_redis_address = comm.bcast(head_redis_address, root=0)
    logging.info(f'Broadcast done... received head_redis_address= {head_redis_address}')

    logging.info(f"Worker on rank {rank} will connect to head-redis-address={head_redis_address}")
    run_ray_worker(head_redis_address)

    comm.barrier() # waiting for all workers to start

    #if run_driver:
    #    driver(head_redis_address)

    comm.barrier() # waiting for driver to finish
    ray_stop()

if __name__ == "__main__":
    if rank == 0:
        logging.info(f'CPU count: ({psutil.cpu_count()}, logical=True); ({psutil.cpu_count(logical=False)}, logical=False)')
        master()
    else: worker(rank==1)
```

### Describe the problem

I am trying to launch a Ray cluster on a XC40 system (Theta at ALCF) with the corresponding `ifconfig`:

```
ipogif0   Link encap:Ethernet  HWaddr 00:01:01:00:13:78
          inet addr:10.128.15.23  Mask:255.252.0.0
          UP RUNNING NOARP  MTU:65520  Metric:1
          RX packets:325540 errors:0 dropped:0 overruns:0 frame:0
          TX packets:322757 errors:0 dropped:2 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:4082902158 (3893.7 Mb)  TX bytes:115661864 (110.3 Mb)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:252437 errors:0 dropped:0 overruns:0 frame:0
          TX packets:252437 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:29708651 (28.3 Mb)  TX bytes:29708651 (28.3 Mb)

rsip      Link encap:IPIP Tunnel  HWaddr
          inet addr:10.236.16.120  P-t-P:10.236.16.120  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP  MTU:9020  Metric:1
          RX packets:8139 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9031 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:2251842 (2.1 Mb)  TX bytes:881684 (861.0 Kb)
```

It looks like the driver connects to the RAY-HEAD, but then the remote call res doesn't come up.
The RAY-HEAD on the worker are starting fin according to these outputs:

Outputs: `ray.log.head`
```
2019-08-07 22:06:24,471	INFO scripts.py:289 -- Using IP address 10.128.0.1 for this node.
2019-08-07 22:06:24,488	INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /projects/datascience/regele/ray/session_2019-08-07_22-06-24_473880_192087/logs.
2019-08-07 22:06:24,663	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:17650 to respond...
2019-08-07 22:06:25,668	INFO services.py:414 -- Failed to connect to the redis server, retrying.
2019-08-07 22:06:25,669	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:17650 to respond...
2019-08-07 22:06:25,849	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:41369 to respond...
2019-08-07 22:06:25,856	INFO services.py:809 -- Starting Redis shard with 10.0 GB max memory.
2019-08-07 22:06:26,004	INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /projects/datascience/regele/ray/session_2019-08-07_22-06-24_473880_192087/logs.
2019-08-07 22:06:26,032	WARNING services.py:1301 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
2019-08-07 22:06:26,034	INFO services.py:1475 -- Starting the Plasma object store with 20.0 GB memory using /dev/shm.
2019-08-07 22:06:26,328	INFO scripts.py:319 --
Started Ray on this node. You can add additional nodes to the cluster by calling

    ray start --redis-address 10.128.0.1:17650

from the node you wish to add. You can connect a driver to the cluster from Python by running

    import ray
    ray.init(redis_address="10.128.0.1:17650")

If you have trouble connecting from a different machine, check that your firewall is configured properly. If you wish to terminate the processes that have been started, run

    ray stop
```

Outputs: `ray.log.1`
```
2019-08-07 22:06:35,957	INFO services.py:409 -- Waiting for redis server at 10.128.0.1:17650 to respond...
2019-08-07 22:06:35,971	INFO scripts.py:363 -- Using IP address 10.128.0.2 for this node.
2019-08-07 22:06:35,989	INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /projects/datascience/regele/ray/session_2019-08-07_22-06-24_473880_192087/logs.
2019-08-07 22:06:35,999	WARNING services.py:1301 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
2019-08-07 22:06:36,001	INFO services.py:1475 -- Starting the Plasma object store with 20.0 GB memory using /dev/shm.
2019-08-07 22:06:36,204	INFO scripts.py:371 --
Started Ray on this node. If you wish to terminate the processes that have been started, run

    ray stop
```

The following output also show up:
```
(pid=205641) WARNING: Logging before InitGoogleLogging() is written to STDERR
(pid=205641) E0807 22:27:04.944134 205641 raylet_client.cc:113] Retrying to connect to socket for pathname /projects/datascience/regele/ray/session_2019-08-07_22-06-24_473880_192087/sockets/raylet (num_attempts = 1, num_retries = 5)
(pid=205641) E0807 22:27:05.444831 205641 raylet_client.cc:113] Retrying to connect to socket for pathname /projects/datascience/regele/ray/session_2019-08-07_22-06-24_473880_192087/sockets/raylet (num_attempts = 2, num_retries = 5)
(pid=205641) E0807 22:27:05.945356 205641 raylet_client.cc:113] Retrying to connect to socket for pathname /projects/datascience/regele/ray/session_2019-08-07_22-06-24_473880_192087/sockets/raylet (num_attempts = 3, num_retries = 5)
(pid=205641) E0807 22:27:06.445899 205641 raylet_client.cc:113] Retrying to connect to socket for pathname /projects/datascience/regele/ray/session_2019-08-07_22-06-24_473880_192087/sockets/raylet (num_attempts = 4, num_retries = 5)
(pid=205641) F0807 22:27:06.946276 205641 raylet_client.cc:122] Could not connect to socket /projects/datascience/regele/ray/session_2019-08-07_22-06-24_473880_192087/sockets/raylet
(pid=205641) *** Check failure stack trace: ***
(pid=205641) Fatal Python error: Aborted
(pid=205641)
(pid=205641) Stack (most recent call first):
(pid=205641)   File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/worker.py", line 1952 in connect
(pid=205641)   File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/workers/default_worker.py", line 84 in <module>
```

and the `logs` folder get full of `worker-*.err` and `worker-*out` files, some containing:
```
cat: '22:36': No such file or directory
Ray worker pid: 192359
2019-08-07 22:36:27,291	ERROR import_thread.py:89 -- ImportThread: Connection closed by server.
```

others containing:
```
Ray worker pid: 205712
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0807 22:28:29.579651 205712 raylet_client.cc:113] Retrying to connect to socket for pathname /projects/datascience/regele/ray/session_2019-08-07_22-06-24_473880_192087/sockets/raylet (num_attempts = 1, num_retries = 5)
E0807 22:28:30.080186 205712 raylet_client.cc:113] Retrying to connect to socket for pathname /projects/datascience/regele/ray/session_2019-08-07_22-06-24_473880_192087/sockets/raylet (num_attempts = 2, num_retries = 5)
E0807 22:28:30.580513 205712 raylet_client.cc:113] Retrying to connect to socket for pathname /projects/datascience/regele/ray/session_2019-08-07_22-06-24_473880_192087/sockets/raylet (num_attempts = 3, num_retries = 5)
E0807 22:28:31.080816 205712 raylet_client.cc:113] Retrying to connect to socket for pathname /projects/datascience/regele/ray/session_2019-08-07_22-06-24_473880_192087/sockets/raylet (num_attempts = 4, num_retries = 5)
F0807 22:28:31.603488 205712 raylet_client.cc:122] Could not connect to socket /projects/datascience/regele/ray/session_2019-08-07_22-06-24_473880_192087/sockets/raylet
*** Check failure stack trace: ***
Fatal Python error: Aborted

Stack (most recent call first):
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/worker.py", line 1952 in connect
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/workers/default_worker.py", line 84 in <module>
```
### Source code / logs
Logs from `go_ray.py`
```
08/07/2019 10:06:18 PM | Waiting for broadcast...
08/07/2019 10:06:18 PM | CPU count: (256, logical=True); (64, logical=False)
08/07/2019 10:06:19 PM | Ready to run ray head
08/07/2019 10:06:30 PM | Head started at: 10.128.0.1:17650
08/07/2019 10:06:30 PM | Ready to broadcast head_redis_address: 10.128.0.1:17650
08/07/2019 10:06:30 PM | Broadcast done...
08/07/2019 10:06:30 PM | Waiting for workers to start...
08/07/2019 10:06:31 PM | Broadcast done... received head_redis_address= 10.128.0.1:17650
08/07/2019 10:06:31 PM | Worker on rank 1 will connect to head-redis-address=10.128.0.1:17650
08/07/2019 10:06:45 PM | Workers are all running!
08/07/2019 10:06:45 PM | Ready to start driver!
08/07/2019 10:06:45 PM | Starting driver, wants to connect to head at: 10.128.0.1:17650
08/07/2019 10:06:56 PM | Failed to init driver... sleeping for 1sec...
Traceback (most recent call last):
  File "/projects/datascience/regele/tuning-scripts/m1/go_ray.py", line 135, in driver
    infos = ray.init(redis_address=head_redis_address)
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/worker.py", line 1478, in init
    ray_params, head=False, shutdown_at_exit=False, connect_only=True)
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/node.py", line 120, in __init__
    redis_password=self.redis_password)
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/services.py", line 135, in get_address_info_from_redis
    redis_address, node_ip_address, redis_password=redis_password)
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/services.py", line 107, in get_address_info_from_redis_helper
    "Redis has started but no raylets have registered yet.")
Exception: Redis has started but no raylets have registered yet.
08/07/2019 10:07:10 PM | Failed to init driver... sleeping for 1sec...
Traceback (most recent call last):
  File "/projects/datascience/regele/tuning-scripts/m1/go_ray.py", line 135, in driver
    infos = ray.init(redis_address=head_redis_address)
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/worker.py", line 1478, in init
    ray_params, head=False, shutdown_at_exit=False, connect_only=True)
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/node.py", line 120, in __init__
    redis_password=self.redis_password)
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/services.py", line 135, in get_address_info_from_redis
    redis_address, node_ip_address, redis_password=redis_password)
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/services.py", line 107, in get_address_info_from_redis_helper
    "Redis has started but no raylets have registered yet.")
Exception: Redis has started but no raylets have registered yet.
08/07/2019 10:07:19 PM | Failed to init driver... sleeping for 1sec...
Traceback (most recent call last):
  File "/projects/datascience/regele/tuning-scripts/m1/go_ray.py", line 135, in driver
    infos = ray.init(redis_address=head_redis_address)
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/worker.py", line 1478, in init
    ray_params, head=False, shutdown_at_exit=False, connect_only=True)
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/node.py", line 120, in __init__
    redis_password=self.redis_password)
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/services.py", line 135, in get_address_info_from_redis
    redis_address, node_ip_address, redis_password=redis_password)
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/services.py", line 107, in get_address_info_from_redis_helper
    "Redis has started but no raylets have registered yet.")
Exception: Redis has started but no raylets have registered yet.
08/07/2019 10:07:28 PM | Failed to init driver... sleeping for 1sec...
Traceback (most recent call last):
  File "/projects/datascience/regele/tuning-scripts/m1/go_ray.py", line 135, in driver
    infos = ray.init(redis_address=head_redis_address)
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/worker.py", line 1478, in init
    ray_params, head=False, shutdown_at_exit=False, connect_only=True)
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/node.py", line 120, in __init__
    redis_password=self.redis_password)
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/services.py", line 135, in get_address_info_from_redis
    redis_address, node_ip_address, redis_password=redis_password)
  File "/lus/theta-fs0/projects/datascience/regele/dh-opt/lib/python3.6/site-packages/ray/services.py", line 107, in get_address_info_from_redis_helper
    "Redis has started but no raylets have registered yet.")
Exception: Redis has started but no raylets have registered yet.
08/07/2019 10:07:46 PM | {'node_ip_address': '10.128.0.1', 'redis_address': '10.128.0.1:17650', 'object_store_address': '/projects/datascience/regele/ray/session_2019-08-07_22-06-24_473880_192087/sockets/plasma_store', 'raylet_socket_name': '/projects/datascience/regele/ray/session_2019-08-07_22-06-24_473880_192087/sockets/raylet', 'webui_url': None, 'session_dir': '/projects/datascience/regele/ray/session_2019-08-07_22-06-24_473880_192087'}
08/07/2019 10:07:46 PM | Driver started on: 10.128.0.1
```
Ray Logs from `raylet.err`
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0807 22:06:26.546187 192168 stats.h:48] Succeeded to initialize stats: exporter address is 127.0.0.1:8888
I0807 22:06:26.557938 192168 redis_gcs_client.cc:145] RedisGcsClient::Connect finished with status OK
I0807 22:06:26.707922 192168 grpc_server.cc:26] ObjectManager server started, listening on port 9498.
I0807 22:07:33.715948 192168 grpc_server.cc:26] NodeManager server started, listening on port 9507.
W0807 22:07:45.424173 192168 node_manager.cc:304] Last heartbeat was sent 523 ms ago
W0807 22:07:51.318817 192168 client_connection.cc:343] [worker]ProcessMessage with type SubmitTask took 192 ms.
W0807 22:07:51.501329 192168 node_manager.cc:304] Last heartbeat was sent 3888 ms ago
W0807 22:07:52.457985 192168 node_manager.cc:304] Last heartbeat was sent 957 ms ago
W0807 22:08:01.625538 192168 node_manager.cc:304] Last heartbeat was sent 3929 ms ago
W0807 22:08:11.787827 192168 node_manager.cc:304] Last heartbeat was sent 4077 ms ago
W0807 22:08:21.919335 192168 node_manager.cc:304] Last heartbeat was sent 4160 ms ago
W0807 22:08:31.852483 192168 node_manager.cc:304] Last heartbeat was sent 4020 ms ago
W0807 22:08:41.718832 192168 node_manager.cc:304] Last heartbeat was sent 3816 ms ago
W0807 22:08:51.620678 192168 node_manager.cc:304] Last heartbeat was sent 3634 ms ago
W0807 22:09:01.630930 192168 node_manager.cc:304] Last heartbeat was sent 3495 ms ago
W0807 22:09:11.701689 192168 node_manager.cc:304] Last heartbeat was sent 3487 ms ago
W0807 22:09:21.767391 192168 node_manager.cc:304] Last heartbeat was sent 3529 ms ago
W0807 22:09:31.949584 192168 node_manager.cc:304] Last heartbeat was sent 3617 ms ago
W0807 22:09:41.274279 192168 node_manager.cc:304] Last heartbeat was sent 2876 ms ago
...
```

Ray Logs from `raylet.1.err`
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0807 22:06:36.149560 205487 stats.h:48] Succeeded to initialize stats: exporter address is 127.0.0.1:8888
I0807 22:06:36.174944 205487 redis_gcs_client.cc:145] RedisGcsClient::Connect finished with status OK
I0807 22:06:36.290738 205487 grpc_server.cc:26] ObjectManager server started, listening on port 11891.
I0807 22:07:43.105118 205487 grpc_server.cc:26] NodeManager server started, listening on port 11897.
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  bind: Address already in use
*** Aborted at 1565215667 (unix time) try "date -d @1565215667" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x836d000322af) received by PID 205487 (TID 0x2aaaaac9b900) from PID 205487; stack trace: ***
    @     0x2aaaaacdfc10 (unknown)
    @     0x2aaaab425f67 __GI_raise
    @     0x2aaaab42733a __GI_abort
    @     0x2aaaaabe13df __gnu_cxx::__verbose_terminate_handler()
    @     0x2aaaaabdfb16 __cxxabiv1::__terminate()
    @     0x2aaaaabdfb4c std::terminate()
    @     0x2aaaaabdfd28 __cxa_throw
    @           0x426ffc boost::throw_exception<>()
    @           0x4270ce boost::asio::detail::do_throw_error()
    @           0x438b67 ray::raylet::Raylet::Raylet()
    @           0x40f6ff main
    @     0x2aaaab411725 __libc_start_main
    @           0x4207d1 (unknown)
```

**Comment by Deathn0t** [comment]
I was setting the `--temp-dir` to the disk to catch the logs of all nodes but sockets are also created here and are using the same names for all nodes, hence with 2 workers I was having a conflict over the same sockets.

**Comment by joshua-cogliati-inl** [comment]
Hm, are you saying that --temp-dir causes this? (Unfortunately for me I get basically no logs without --temp-dir), and when I do use --temp-dir (ray 1.9.2 fyi) I get the errors like:
```
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  bind: Address already in use
```

**Comment by joshua-cogliati-inl** [comment]
Still in ray 1.12:
```
[2022-05-10 13:08:57,887 I 237815 237844] (raylet) dlmalloc.cc:154: create_and_mmap_buffer(57472843784, /dev/shm/plasmaXXXXXX)
[2022-05-10 13:08:57,892 E 237815 237844] (raylet) logging.cc:325: *** SIGABRT received at time=1652209737 on cpu 25 ***
[2022-05-10 13:08:57,892 E 237815 237844] (raylet) logging.cc:325: PC: @     0x7fffec833387  (unknown)  raise
[2022-05-10 13:08:57,892 E 237815 237844] (raylet) logging.cc:325:     @     0x7fffed6d6630   67121448  (unknown)
[2022-05-10 13:08:57,892 E 237815 237844] (raylet) logging.cc:325:     @ 0x6c61207373657264  (unknown)  (unknown)

terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  bind: Address already in use
*** SIGABRT received at time=1652209737 on cpu 25 ***
PC: @     0x7fffec833387  (unknown)  raise
    @     0x7fffed6d6630   67121448  (unknown)
    @ 0x6c61207373657264  (unknown)  (unknown)
[2022-05-10 13:08:57,892 E 237815 237844] (raylet) logging.cc:325: *** SIGABRT received at time=1652209737 on cpu 25 ***
[2022-05-10 13:08:57,892 E 237815 237844] (raylet) logging.cc:325: PC: @     0x7fffec833387  (unknown)  raise
[2022-05-10 13:08:57,892 E 237815 237844] (raylet) logging.cc:325:     @     0x7fffed6d6630   67121448  (unknown)
[2022-05-10 13:08:57,892 E 237815 237844] (raylet) logging.cc:325:     @ 0x6c61207373657264  (unknown)  (unknown)
```

**Comment by joshua-cogliati-inl** [comment]
An interesting point is that it doesn't kill all the raylets, just some of them.  For example, with the above one, it kill 2 out of 5 raylet workers.

**Comment by joshua-cogliati-inl** [comment]
@Deathn0t I am not sure why you closed this issue, it still seems to be a problem.  Thanks.

**Comment by joshua-cogliati-inl** [comment]
Possibly this could be solved by adding `--log-dir` to the arguments that `ray start` takes.  (It is available already for `raylet`) This would let people use choose what directory to use for log files without changing what directory is used for the sockets.
