### ISSUE TITLE
"Input matrix not invertible" error in SAC

### ISSUE THREAD

**Issue by annaluo676** [ray-project/ray#5568]
### System information
- **OS Platform and Distribution**: Ubuntu 16.04.5
- **Ray installed from (source or binary)**: Source
- **Ray version**: 0.7.4
- **Python version**: 3.7.3
- **Exact command to reproduce**: 

### Describe the problem
Algorithm: SAC
Environment: Customized environment

I'm trying to use SAC in Ray 0.7.4 with an environment that worked with A3C. The training stopped with an error `tensorflow.python.framework.errors_impl.InvalidArgumentError: Input matrix is not invertible.` Action is coninuous and between 0 and some fixed value (say, 10000). I've noticed that the outputs of `compute_actions()` is out of range and giving inf. values. 

`{ 'default_policy': ( np.ndarray((1, 1), dtype=float32, min=4.0562666736584153e+37, max=4.0562666736584153e+37, mean=4.0562666736584153e+37),
  [],
 { 'action_logp': np.ndarray((1,), dtype=float32, min=12.393, max=12.393, mean=12.393),
'action_prob': np.ndarray((1,), dtype=float32, min=241148.328, max=241148.328, mean=241148.328)})}`

Tried 1) Change the action space to [0, 1]; 2) clip manually by `np.clip()` in env step function. Got the same error.

### Source code / logs
```
2019-08-28 18:36:20,049	INFO trainer.py:333 -- Executing eagerly
2019-08-28 18:36:20,140	WARNING logger.py:255 -- Could not instantiate <class 'ray.tune.logger.TFLogger'> - skipping.
2019-08-28 18:36:20,231	INFO catalog.py:363 -- Using custom preprocessor my_prep
I0828 18:36:20.237390 140185563031296 train.py:43] obs_space shape before pre-processing: (31326,)
Traceback (most recent call last):
  File "train.py", line 171, in <module>
    agent = _get_dict_agent(args['run'])(env="ENVNAME", config=final_config, logger_creator=_logger_func)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 90, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 363, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 99, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 483, in _setup
    self._init(self.config, self.env_creator)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 109, in _init
    self.config["num_workers"])
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 528, in _make_workers
    logdir=self.logdir)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 64, in __init__
    RolloutWorker, env_creator, policy, 0, self._local_config)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 220, in _make_worker
    _fake_sampler=config.get("_fake_sampler", False))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 353, in __init__
    policy_dict, policy_config)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 764, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/rllib/policy/eager_tf_policy.py", line 112, in __init__
    self._initialize_loss_with_dummy_batch()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/rllib/policy/eager_tf_policy.py", line 354, in _initialize_loss_with_dummy_batch
    dummy_batch.get(SampleBatch.PREV_REWARDS))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/rllib/policy/eager_tf_policy.py", line 186, in compute_actions
    self.action_space, self.config)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/sac/sac_policy.py", line 113, in build_action_output
    model_out, deterministic=False)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/sac/sac_model.py", line 179, in get_policy_output
    log_pis = action_distribution.log_prob(actions)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/distributions/distribution.py", line 866, in log_prob
    return self._call_log_prob(value, name, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/distributions/distribution.py", line 848, in _call_log_prob
    return self._log_prob(value, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py", line 408, in _log_prob
    y, x, ildj, event_ndims, **distribution_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py", line 420, in _finish_log_prob_for_one_fiber
    log_prob = self.distribution.log_prob(x, **distribution_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/distributions/distribution.py", line 866, in log_prob
    return self._call_log_prob(value, name, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/distributions/distribution.py", line 848, in _call_log_prob
    return self._log_prob(value, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/internal/distribution_util.py", line 2094, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/distributions/mvn_linear_operator.py", line 210, in _log_prob
    return super(MultivariateNormalLinearOperator, self)._log_prob(x)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py", line 401, in _log_prob
    x = self.bijector.inverse(y, **bijector_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/bijectors/bijector.py", line 977, in inverse
    return self._call_inverse(y, name, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/bijectors/bijector.py", line 949, in _call_inverse
    mapping = mapping.merge(x=self._inverse(y, **kwargs))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/bijectors/affine_linear_operator.py", line 160, in _inverse
    x = self.scale.solvevec(x, adjoint=self.adjoint)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/linalg/linear_operator.py", line 866, in solvevec
    return self._solvevec(rhs, adjoint=adjoint)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/linalg/linear_operator.py", line 816, in _solvevec
    solution_mat = self.solve(rhs_mat, adjoint=adjoint)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/linalg/linear_operator.py", line 811, in solve
    return self._solve(rhs, adjoint=adjoint, adjoint_arg=adjoint_arg)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/linalg/linear_operator_lower_triangular.py", line 207, in _solve
    self._tril, rhs, lower=True, adjoint=adjoint)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/linalg/linear_operator_util.py", line 290, in matrix_triangular_solve_with_broadcast
    adjoint=adjoint and still_need_to_transpose)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_linalg_ops.py", line 1867, in matrix_triangular_solve
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input matrix is not invertible. [Op:MatrixTriangularSolve]
```

Config comes from [Ray SAC doc](https://ray.readthedocs.io/en/latest/rllib-algorithms.html?highlight=sac#soft-actor-critic-sac) with minor modifications.

`
'config': {'eager': True, 'twin_q': True, 'use_state_preprocessor': False, 'policy': 'GaussianLatentSpacePolicy', 'Q_model': {'hidden_activation': 'relu'}, 'policy_model': {'hidden_activation': 'relu'}, 'tau': 0.0005, 'target_entropy': 'auto', 'no_done_at_end': True, 'n_step': 1, 'timesteps_per_iteration': 1000, 'exploration_enabled': True, 'buffer_size': 1000000, 'prioritized_replay': False, 'prioritized_replay_alpha': 0.6, 'prioritized_replay_beta': 0.4, 'beta_annealing_fraction': 0.2, 'final_prioritized_replay_beta': 0.4, 'compress_observations': False, 'optimization': {'actor_learning_rate': 0.0003, 'critic_learning_rate': 0.0003, 'entropy_learning_rate': 0.0003}, 'grad_norm_clipping': None, 'learning_starts': 1500, 'sample_batch_size': 256, 'train_batch_size': 256, 'target_network_update_freq': 0, 'model': {'custom_preprocessor': 'my_prep'}, 'callbacks': {'on_episode_start': 'on_episode_start', 'on_episode_step': 'on_episode_step', 'on_episode_end': 'on_episode_end'}}
`

**Comment by annaluo676** [comment]
@ericl Sorry for the late reply. The action space issue was actually in the environment, and SAC agent is able to train after the fix. However, I'm still getting the above mentioned error "stochastically". The agent usually trained smoothly for the first couple of iterations, then the "Input matrix is not invertible" popped up. Was there a reason not to add a small number to prevent this, similart to https://github.com/openai/spinningup/blob/2e0eff9bd019c317af908b72c056a33f14626602/spinup/algos/sac/core.py#L25?

**Comment by ericl** [comment]
Hm, https://github.com/rail-berkeley/softlearning/tree/master/softlearning doesn't have this I believe, or it seems like it is defined in tensorflow-probability only: https://github.com/rail-berkeley/softlearning/blob/7bbfcdba8ad6efd56811df946718c3f175f25499/softlearning/policies/gaussian_policy.py

**Comment by annaluo676** [comment]
I guess my confusion comes from the fact that the output range for log_std is already clipped to avoid the actions too random / deterministic (https://github.com/rail-berkeley/softlearning/blob/7bbfcdba8ad6efd56811df946718c3f175f25499/softlearning/policies/gaussian_policy.py#L76), so inverting the diagonal matrix shouldn't be a problem. Any ideas?

**Comment by annaluo676** [comment]
Hi @ericl, I've created a dummy env to replicate the error:
```
class DummyEnv_V2(gym.Env):

    def __init__(self, g=10.0):
        self.max_speed=8
        self.max_torque=2.
        self.obs_dim = 100
        self.high = np.full(self.obs_dim, self.max_speed)
        self.action_space = spaces.Box(low=-self.max_torque, high=self.max_torque, shape=(1,), dtype=np.float32)
        self.observation_space = spaces.Box(low=-self.high, high=self.high, dtype=np.float32)

    def step(self,u):
        costs = -1
        return self._get_obs(), -costs, False, {}

    def reset(self):
        return self._get_obs()

    def _get_obs(self):
        return np.random.uniform(low=-self.high, high=self.high, size=(self.obs_dim,))
```
with configuration
```
sac_test = with_common_config({
    "eager": True,
    "soft_horizon": True,
    "metrics_smoothing_episodes": 10
})
```

The environment is modifed upon Pendulum-v0, with a larger observation space (100 vs. 3). `agent_test = SACTrainer(env="DummyEnv_V2", config=sac_test)` throws out the Input matrix error (full log [here](https://docs.google.com/document/d/1OMmevHTK0z3aEQq1Mr0yKDyl-sM0SxCXh-5jOqOfItA/edit?usp=sharing)). It seems that the implementation utilizes `tfp.bijectors` with tanh transformation and that doesn't work when the observation space is high.

**Comment by ericl** [comment]
@annaluo676 thanks for the repro, it seems to be since we did not define bounds on the observation space, which caused the policy to emit NaNs since it was being passed dummy observations with very large values during policy initialization.

Try this fix out? https://github.com/ray-project/ray/pull/5826/files

**Comment by annaluo676** [comment]
Yes, the patch works. Thanks!

Closing this issue.
