### ISSUE TITLE
[rllib] Serving GPU trained IMPALA model in CPU machine raises an error.

### ISSUE THREAD

**Issue by haje01** [ray-project/ray#5574]
### System information
- **OS Platform and Distribution**: Mac OS X 10.14.6
- **Ray installed from**: Binary
- **Ray version**: 0.8.0-dev3
- **Python version**: 3.6
- **Exact command to reproduce**: 

### Describe the problem
- I trained Atari Breakout using IMPALA in GPU(g3.16xlarge) head + CPU(m5.16xlarge) worker.
- The training config file was almost identical with `tuned_examples/pong-impala-fast.yaml` except `env` changed to `BreakoutNoFrameskip-v4` and `checkpoint_freq` option inserted.
- After training was done, I rsynced down checkpoints and try to run it in my notebook(which is CPU only Mac) with following command:

`rllib rollout --run IMPALA IMPALA_BreakoutNoFrameskip-v4_0_2019-08-29_06-16-059e1nm1hh/checkpoint_65/checkpoint-65`

- which causes folling error:

```
2019-08-29 16:47:50,335	INFO resource_spec.py:205 -- Starting Ray with 3.47 GiB memory available for workers and up to 1.76 GiB for objects. You can adjust these settings with ray.remote(memory=<bytes>, object_store_memory=<bytes>).
2019-08-29 16:47:51,117	INFO trainer.py:336 -- Tip: set 'eager': true or the --eager flag to enable TensorFlow eager execution
Traceback (most recent call last):
  File "/Users/haje01/.pyenv/versions/ml2/bin/rllib", line 10, in <module>
    sys.exit(cli())
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/ray/rllib/scripts.py", line 40, in cli
    rollout.run(options, rollout_parser)
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/ray/rllib/rollout.py", line 103, in run
    agent = cls(env=args.env, config=config)
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 90, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 363, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/ray/tune/trainable.py", line 99, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 483, in _setup
    self._init(self.config, self.env_creator)
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 106, in _init
    self.workers = make_workers(self, env_creator, policy, config)
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/ray/rllib/agents/impala/impala.py", line 105, in defer_make_workers
    return trainer._make_workers(env_creator, policy, config, 0)
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 528, in _make_workers
    logdir=self.logdir)
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 64, in __init__
    RolloutWorker, env_creator, policy, 0, self._local_config)
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 220, in _make_worker
    _fake_sampler=config.get("_fake_sampler", False))
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 350, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 764, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/ray/rllib/policy/tf_policy_template.py", line 143, in __init__
    obs_include_prev_action_reward=obs_include_prev_action_reward)
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/ray/rllib/policy/dynamic_tf_policy.py", line 140, in __init__
    framework="tf")
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/ray/rllib/models/catalog.py", line 320, in get_model_v2
    name, **model_kwargs)
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/ray/rllib/models/tf/visionnet_v2.py", line 100, in __init__
    self.base_model = tf.keras.Model(inputs, [conv_out, value_out])
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 121, in __init__
    super(Model, self).__init__(*args, **kwargs)
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 81, in __init__
    self._init_graph_network(*args, **kwargs)
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/tensorflow/python/training/checkpointable/base.py", line 442, in _method_wrapper
    method(self, *args, **kwargs)
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 177, in _init_graph_network
    self._validate_graph_inputs_and_outputs()
  File "/Users/haje01/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1673, in _validate_graph_inputs_and_outputs
    '(thus holding past layer metadata). Found: ' + str(x))
ValueError: Output tensors to a Model must be the output of a TensorFlow `Layer` (thus holding past layer metadata). Found: Tensor("default_policy/value_out/BiasAdd:0", shape=(?, 1), dtype=float32)
```

Any ideas?

**Comment by ericl** [comment]
Try upgrading to TF1.14? The Ray version must also be the same across both machines.

**Comment by haje01** [comment]
It works! Thank you :-)
