### ISSUE TITLE
rllib cannot run eager with tensorflow2.0-rc0

### ISSUE THREAD

**Issue by idthanm** [ray-project/ray#5621]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **Ray installed from (source or binary)**:binary
- **Ray version**:ray-0.8.0.dev4
- **Python version**:python37
- **Exact command to reproduce**:rllib train --run=DQN --env=CartPole-v0 --eager

### Describe the problem
 I cannot run the simple command  with eager while i use tensorflow2.0-rc0: rllib train --run=DQN --env=CartPole-v0 --eager.

### Source code / logs

(pid=3259) 2019-09-03 23:56:25,208	INFO trainer.py:336 -- Executing eagerly
2019-09-03 23:56:25,250	ERROR trial_runner.py:552 -- Error processing event.
Traceback (most recent call last):
  File "/home/yang/Software/anaconda3/envs/tf2/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 498, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/yang/Software/anaconda3/envs/tf2/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 347, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/yang/Software/anaconda3/envs/tf2/lib/python3.7/site-packages/ray/worker.py", line 2340, in get
    raise value
ray.exceptions.RayTaskError: ray_worker (pid=3259, host=yang-XPS-15-9570)
  File "/home/yang/Software/anaconda3/envs/tf2/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 90, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/yang/Software/anaconda3/envs/tf2/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 366, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/yang/Software/anaconda3/envs/tf2/lib/python3.7/site-packages/ray/tune/trainable.py", line 99, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/yang/Software/anaconda3/envs/tf2/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 486, in _setup
    self._init(self.config, self.env_creator)
  File "/home/yang/Software/anaconda3/envs/tf2/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 109, in _init
    self.config["num_workers"])
  File "/home/yang/Software/anaconda3/envs/tf2/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 531, in _make_workers
    logdir=self.logdir)
  File "/home/yang/Software/anaconda3/envs/tf2/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 64, in __init__
    RolloutWorker, env_creator, policy, 0, self._local_config)
  File "/home/yang/Software/anaconda3/envs/tf2/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 220, in _make_worker
    _fake_sampler=config.get("_fake_sampler", False))
  File "/home/yang/Software/anaconda3/envs/tf2/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 351, in __init__
    policy_dict, policy_config)
  File "/home/yang/Software/anaconda3/envs/tf2/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 762, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/home/yang/Software/anaconda3/envs/tf2/lib/python3.7/site-packages/ray/rllib/policy/eager_tf_policy.py", line 88, in __init__
    config)
  File "/home/yang/Software/anaconda3/envs/tf2/lib/python3.7/site-packages/ray/rllib/agents/dqn/dqn_policy.py", line 218, in build_q_model
    parameter_noise=config["parameter_noise"])
  File "/home/yang/Software/anaconda3/envs/tf2/lib/python3.7/site-packages/ray/rllib/models/catalog.py", line 320, in get_model_v2
    name, **model_kwargs)
  File "/home/yang/Software/anaconda3/envs/tf2/lib/python3.7/site-packages/ray/rllib/agents/dqn/distributional_q_model.py", line 157, in __init__
    store = tfc.eager.EagerVariableStore()
AttributeError: module 'tensorflow.contrib' has no attribute 'eager'

**Comment by ericl** [comment]
Hmm, there seems to be catch-22 here, even if we use TF1 compat we need to use EagerVariableStore for variable scope to work properly. However EagerVariableStore is not present in TF2 at all since contrib is not present, so it can't be backwards compatible with V1 code even in v1 compat mode.

So the only way to use eager with DQN is to downgrade to TF1.14.

cc @gehring you see any other way out of this? I suppose we could also try to completely remove var_scope from distributional_q_model.

**Comment by gehring** [comment]
@ericl That's an annoying one! I knew that `tf.contrib` was going away but I didn't expect it do be removed from the `tf.compat.v1` package. I can think of two solutions which would not require changing distributional_q_model.

1.  We replace the use of `EagerVariableStore` with our own barebone implementation based off of [`tf.variable_creator_scope`](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/variable_creator_scope) which is present in both compat v1 and v2.
2. We modify RLlib's compat wrapper to make use of `tf.make_template` which is still present in `tf.compat.v1` to manage both variable scopes and variable "store".

Since we already have somethings that works for managing variable scopes, I think the path of least resistance would be option 1). Though the advantage of option 2) is that it would raise an exception if a user is in eager/v2 + compat mode and doesn't respect the variable scope approach for variable re-use (i.e., using the `tf.Variable` constructor directly).

See the current implementation of a [`VariableHolder`](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/eager/wrap_function.py#L43) class for  how to implement option 1). You could probably do it in half as many lines if you are just interested in catching variables.

Otherwise, the "cleanest" solution but most expensive solution that comes to mind would be to refactor how we handle graph mode such that everything uses the eager backend, implementing graph mode compatibility through by wrapping call with something like `tf.defun` or`tf.function` (which handle capturing variables).

**Comment by ericl** [comment]
Upon further investigation, it seems to have moved to python.ops package, which can be imported in either TF2 or TF1 in compat mode.

@idthanm try the patch out?

**Comment by idthanm** [comment]
@ericl Thanks, ericl. It works now. I found you also import tensorflow.contrib in /rllib/agents/ddpg, maybe that needs to fix too.
btw, it seems that eager mode is much more inefficient than graph mode (in the simple DQN cartpole, at least 5x).
Thanks a lot anyway.

**Comment by ericl** [comment]
Yep, I've also found eager to be quite slow. It's especially bad for small
batch sizes or for inference path. For larger models, and disabling eager
on the rollout workers, it is almost as fast as graph mode.
