### ISSUE TITLE
Error when running Ray, "no usable temporary directory".

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#571]
When running the `ray/examples/evolution_strategies/evolution_strategies.py` on a cluster, I saw this error pushed to the driver.

```
Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/actor.py", line 75, in fetch_and_register_actor
    unpickled_class = pickling.loads(pickled_class)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 717, in subimport
    __import__(name)
  File "/home/ubuntu/ray/examples/evolution_strategies/policies.py", line 11, in <module>
    import h5py
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py", line 60, in <module>
    from .tests import run_tests
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/h5py/tests/__init__.py", line 13, in <module>
    from .common import ut
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/h5py/tests/common.py", line 39, in <module>
    testfile, fname = tempfile.mkstemp(unichr(0x03b7))
  File "/home/ubuntu/anaconda3/lib/python3.6/tempfile.py", line 335, in mkstemp
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
  File "/home/ubuntu/anaconda3/lib/python3.6/tempfile.py", line 130, in _sanitize_params
    dir = gettempdir()
  File "/home/ubuntu/anaconda3/lib/python3.6/tempfile.py", line 296, in gettempdir
    tempdir = _get_default_tempdir()
  File "/home/ubuntu/anaconda3/lib/python3.6/tempfile.py", line 231, in _get_default_tempdir
    dirlist)
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/home/ubuntu']
```

Suggesting that the actor couldn't be unpickled.

**Comment by robertnishihara** [comment]
The problem was that some earlier experiments had caused the local scheduler on one of the machines to enter a state in which it repeatedly retried certain redis commands. 

This caused the file `/tmp/raylogs/local_scheduler_0-083115.err` to fill up with lines like

```
[WARN] (/home/ubuntu/ray/src/common/state/table.cc:85) retrying operation local_scheduler_table_send_info, retry_count = -1
```

and ultimately to take up several gigabytes of disk.

So there wasn't any disk left on the machine, and that caused commands like

```python
import tempfile
tempfile.gettempdir()
```

to fail on that machine.

Removing the excessively large logfiles solved the problem. This is related to #526.
