### ISSUE TITLE
"The ray.global_state API cannot be used before ray.init has been called" when using local_mode

### ISSUE THREAD

**Issue by nicofirst1** [ray-project/ray#5721]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Mojave, version 10.14.6
- **Ray installed from (source or binary)**: source
- **Ray version**:  0.6.1
- **Python version**: 3.6
- **Exact command to reproduce**: 
`ray.init(num_cpus=1, local_mode=True)`

### Describe the problem

When trying to use the local_mode in *ray.init()* I get 
`Exception: The ray.global_state API cannot be used before ray.init has been called.`

### Source code / logs

Traceback:
```
Traceback (most recent call last):
  File "/anaconda3/envs/dmas/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-e74da222fb8f>", line 3, in <module>
    runfile('/Users/oblintosh/Desktop/dmas/FlowMas/Tutorials/3_GridMapCustomRL.py', wdir='/Users/oblintosh/Desktop/dmas/FlowMas/Tutorials')
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/oblintosh/Desktop/dmas/FlowMas/Tutorials/3_GridMapCustomRL.py", line 164, in <module>
    trials = run_experiments(experiment_params)
  File "/anaconda3/envs/dmas/lib/python3.6/site-packages/ray/tune/tune.py", line 102, in run_experiments
    trial_executor=trial_executor)
  File "/anaconda3/envs/dmas/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 80, in __init__
    RayTrialExecutor(queue_trials=queue_trials)
  File "/anaconda3/envs/dmas/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 33, in __init__
    self._update_avail_resources()
  File "/anaconda3/envs/dmas/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 227, in _update_avail_resources
    resources = ray.global_state.cluster_resources()
  File "/anaconda3/envs/dmas/lib/python3.6/site-packages/ray/experimental/state.py", line 765, in cluster_resources
    clients = self.client_table()
  File "/anaconda3/envs/dmas/lib/python3.6/site-packages/ray/experimental/state.py", line 329, in client_table
    self._check_connected()
  File "/anaconda3/envs/dmas/lib/python3.6/site-packages/ray/experimental/state.py", line 46, in _check_connected
    raise Exception("The ray.global_state API cannot be used before "
Exception: The ray.global_state API cannot be used before ray.init has been called.
```

Code:
```
ray.init(num_cpus=N_CPUS, local_mode=True)

# defining dictionary for the experiment
experiment_params = dict(

    run="PPO",  # must be the same as the default config
    env=gym_name,
    config={**config},
    checkpoint_freq=20,
    checkpoint_at_end=True,
    max_failures=999,
    stop={"training_iteration": 200, },  # stop conditions

)

# weird thing the function wats
experiment_params = {params["exp_tag"]: experiment_params}

# running the experiment
trials = run_experiments(experiment_params)
```

**Comment by richardliaw** [comment]
Can you update to `ray==0.7.4`?

**Comment by nicofirst1** [comment]
This worked for me! Thanks alot
