### ISSUE TITLE
[rllib] Callbacks should be wrapped in tune.function

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#5797]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 10.14.5
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.4
- **Python version**: 3.7.3
- **Exact command to reproduce**: N/A

### Describe the problem
If you try to build a callback based off the example in https://github.com/ray-project/ray/blob/master/rllib/examples/custom_metrics_and_callbacks.py you receive an error. Wrapping the callbacks in tune.function in the config resolves this. 

### Source code / logs

Traceback (most recent call last):
  File "examples/rllib/multiagent_exps/multiagent_bottleneck.py", line 308, in <module>
    run(**exp_dict, queue_trials=False)
  File "/Users/eugenevinitsky/anaconda3/envs/cdc_bottlenecks/lib/python3.7/site-packages/ray/tune/tune.py", line 244, in run
    runner.step()
  File "/Users/eugenevinitsky/anaconda3/envs/cdc_bottlenecks/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 323, in step
    next_trial = self._get_next_trial()  # blocking
  File "/Users/eugenevinitsky/anaconda3/envs/cdc_bottlenecks/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 486, in _get_next_trial
    self._update_trial_queue(blocking=wait_for_trial)
  File "/Users/eugenevinitsky/anaconda3/envs/cdc_bottlenecks/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 634, in _update_trial_queue
    trials = self._search_alg.next_trials()
  File "/Users/eugenevinitsky/anaconda3/envs/cdc_bottlenecks/lib/python3.7/site-packages/ray/tune/suggest/basic_variant.py", line 57, in next_trials
    trials = list(self._trial_generator)
  File "/Users/eugenevinitsky/anaconda3/envs/cdc_bottlenecks/lib/python3.7/site-packages/ray/tune/suggest/basic_variant.py", line 78, in _generate_trials
    for resolved_vars, spec in generate_variants(unresolved_spec):
  File "/Users/eugenevinitsky/anaconda3/envs/cdc_bottlenecks/lib/python3.7/site-packages/ray/tune/suggest/variant_generator.py", line 43, in generate_variants
    for resolved_vars, spec in _generate_variants(unresolved_spec):
  File "/Users/eugenevinitsky/anaconda3/envs/cdc_bottlenecks/lib/python3.7/site-packages/ray/tune/suggest/variant_generator.py", line 108, in _generate_variants
    unresolved = _unresolved_values(spec)
  File "/Users/eugenevinitsky/anaconda3/envs/cdc_bottlenecks/lib/python3.7/site-packages/ray/tune/suggest/variant_generator.py", line 245, in _unresolved_values
    for (path, value) in _unresolved_values(v).items():
  File "/Users/eugenevinitsky/anaconda3/envs/cdc_bottlenecks/lib/python3.7/site-packages/ray/tune/suggest/variant_generator.py", line 245, in _unresolved_values
    for (path, value) in _unresolved_values(v).items():
  File "/Users/eugenevinitsky/anaconda3/envs/cdc_bottlenecks/lib/python3.7/site-packages/ray/tune/suggest/variant_generator.py", line 240, in _unresolved_values
    resolved, v = _try_resolve(v)
  File "/Users/eugenevinitsky/anaconda3/envs/cdc_bottlenecks/lib/python3.7/site-packages/ray/tune/suggest/variant_generator.py", line 217, in _try_resolve
    "{}".format(v))
DeprecationWarning: Function values are ambiguous in Tune configuations. Either wrap the function with `tune.function(func)` to specify a function literal, or `tune.sample_from(func)` to tell Tune to sample values from the function during variant generation: <function on_episode_end at 0x7ff039c85048>

**Comment by richardliaw** [comment]
I think this is now addressed.
