### ISSUE TITLE
issues with starting ray

### ISSUE THREAD

**Issue by shreyagu** [ray-project/ray#5811]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.14.6
- **Ray installed from (source or binary)**: source
- **Ray version**: ray 0.7.5
- **Python version**:python 3.6.9
- **Exact command to reproduce**:

### Describe the problem
I'm not able to start ray with the command: `ray start --redis-address *********:6379` please help me figure this out.

### Source code / logs

```

2019-10-01 17:21:39,261	INFO scripts.py:381 -- Using IP address 172.31.38.63 for this node.
2019-10-01 17:21:39,264	INFO resource_spec.py:205 -- Starting Ray with 0.1 GiB memory available for workers and up to 0.05 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
Traceback (most recent call last):
  File "/usr/local/bin/ray", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ray/scripts/scripts.py", line 805, in main
    return cli()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ray/scripts/scripts.py", line 388, in start
    node = ray.node.Node(ray_params, head=False, shutdown_at_exit=block)
  File "/usr/local/lib/python3.6/dist-packages/ray/node.py", line 156, in __init__
    self.start_ray_processes()
  File "/usr/local/lib/python3.6/dist-packages/ray/node.py", line 584, in start_ray_processes
    self.start_plasma_store()
  File "/usr/local/lib/python3.6/dist-packages/ray/node.py", line 486, in start_plasma_store
    plasma_store_socket_name=self._plasma_store_socket_name)
  File "/usr/local/lib/python3.6/dist-packages/ray/services.py", line 1360, in start_plasma_store
    ray_constants.OBJECT_STORE_MINIMUM_MEMORY_BYTES))
ValueError: Attempting to cap object store memory usage at 57641779 bytes, but the minimum allowed is 78643200 bytes.
```

**Comment by JAMMFam** [comment]
Nice!

**Comment by shreyagu** [comment]
@richardliaw  @robertnishihara  @ericl Can someone please help me understand this?

**Comment by shreyagu** [comment]
@richardliaw  @robertnishihara  @ericl  @pcmoritz

**Comment by robertnishihara** [comment]
@shreyagu how much memory does the machine have?

Also, since you are passing in `--redis-address` does this mean you already started Ray with `ray start --head` successfully?

Can you try doing `import ray; ray.init()` in Python and share what that outputs?

**Comment by shreyagu** [comment]
Instance type
t2.micro, RAM: 1GB

When i try `ray up` this is what happens: 

```ray up ML-test.yaml
This will create a new cluster [y/N]: y
2019-10-15 16:37:15,015    INFO commands.py:198 --
get_or_create_head_node: Launching new head node...
2019-10-15 16:37:15,015    INFO node_provider.py:224 -- NodeProvider:
calling create_instances with subnet-37b9196d (count=1).
2019-10-15 16:37:16,176    INFO node_provider.py:238 -- NodeProvider:
Created instance [id=i-0b85bd01a56ecf2e5, name=pending, info=pending]
2019-10-15 16:37:16,322    INFO commands.py:211 --
get_or_create_head_node: Updating files on head node...
2019-10-15 16:37:16,323    INFO updater.py:140 -- NodeUpdater:
i-0b85bd01a56ecf2e5: Updating to fd34f5b8108dc366e612a860fcedf10442219353
2019-10-15 16:37:16,323    INFO updater.py:96 -- NodeUpdater: Waiting
for IP of i-0b85bd01a56ecf2e5...
2019-10-15 16:37:16,462    INFO log_timer.py:21 -- AWSNodeProvider: Set
tag ray-node-status=waiting-for-ssh on ['i-0b85bd01a56ecf2e5']
[LogTimer=139ms]
2019-10-15 16:37:26,469    INFO updater.py:96 -- NodeUpdater: Waiting
for IP of i-0b85bd01a56ecf2e5...
2019-10-15 16:37:36,555    INFO updater.py:96 -- NodeUpdater: Waiting
for IP of i-0b85bd01a56ecf2e5...
2019-10-15 16:37:46,626    INFO updater.py:96 -- NodeUpdater: Waiting
for IP of i-0b85bd01a56ecf2e5...
2019-10-15 16:37:46,746    INFO log_timer.py:21 -- NodeUpdater:
i-0b85bd01a56ecf2e5: Got IP [LogTimer=30423ms]
2019-10-15 16:37:46,765    INFO updater.py:167 -- NodeUpdater:
i-0b85bd01a56ecf2e5: Waiting for SSH...
2019-10-15 16:37:46,766    INFO updater.py:282 -- NodeUpdater: Running
uptime on 54.162.234.188...
ssh: connect to host 54.162.234.188 port 22: Connection timed out
2019-10-15 16:37:56,793    INFO updater.py:282 -- NodeUpdater: Running
uptime on 54.162.234.188...
ssh: connect to host 54.162.234.188 port 22: Connection timed out
2019-10-15 16:38:06,823    INFO updater.py:282 -- NodeUpdater: Running
uptime on 54.162.234.188...
ssh: connect to host 54.162.234.188 port 22: Connection refused
2019-10-15 16:38:12,841    INFO updater.py:282 -- NodeUpdater: Running
uptime on 54.162.234.188...
Warning: Permanently added '54.162.234.188' (ECDSA) to the list of known
hosts.
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
  23:38:14 up 0 min,  0 users,  load average: 0.72, 0.16, 0.05
2019-10-15 16:38:14,509    INFO log_timer.py:21 -- NodeUpdater:
i-0b85bd01a56ecf2e5: Got SSH [LogTimer=27743ms]
2019-10-15 16:38:14,511    INFO updater.py:282 -- NodeUpdater: Running
mkdir -p ~ on 54.162.234.188...
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2019-10-15 16:38:14,662    INFO updater.py:245 -- NodeUpdater:
i-0b85bd01a56ecf2e5: Syncing
/home/rajmund/.ssh/ray-autoscaler_us-east-1.pem to
~/ray_bootstrap_key.pem...
2019-10-15 16:38:14,697    INFO log_timer.py:21 -- AWSNodeProvider: Set
tag ray-node-status=syncing-files on ['i-0b85bd01a56ecf2e5']
[LogTimer=188ms]
sending incremental file list

sent 85 bytes  received 12 bytes  194.00 bytes/sec
total size is 1,692  speedup is 17.44
2019-10-15 16:38:14,751    INFO log_timer.py:21 -- NodeUpdater
i-0b85bd01a56ecf2e5: Synced
/home/rajmund/.ssh/ray-autoscaler_us-east-1.pem to
~/ray_bootstrap_key.pem [LogTimer=240ms]
2019-10-15 16:38:14,751    INFO updater.py:282 -- NodeUpdater: Running
mkdir -p ~ on 54.162.234.188...
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2019-10-15 16:38:14,993    INFO updater.py:245 -- NodeUpdater:
i-0b85bd01a56ecf2e5: Syncing /tmp/ray-bootstrap-re_4xns4 to
~/ray_bootstrap_config.yaml...
sending incremental file list
ray-bootstrap-re_4xns4

sent 122 bytes  received 53 bytes  116.67 bytes/sec
total size is 1,880  speedup is 10.74
2019-10-15 16:38:15,142    INFO log_timer.py:21 -- NodeUpdater
i-0b85bd01a56ecf2e5: Synced /tmp/ray-bootstrap-re_4xns4 to
~/ray_bootstrap_config.yaml [LogTimer=390ms]
2019-10-15 16:38:15,142    INFO log_timer.py:21 -- NodeUpdater:
i-0b85bd01a56ecf2e5: Initialization commands completed [LogTimer=0ms]
2019-10-15 16:38:15,142    INFO updater.py:282 -- NodeUpdater: Running
sudo pip install --upgrade pip on 54.162.234.188...
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2019-10-15 16:38:19,808    INFO log_timer.py:21 -- AWSNodeProvider: Set
tag ray-node-status=setting-up on ['i-0b85bd01a56ecf2e5'] [LogTimer=110ms]
WARNING: The directory '/home/ubuntu/.cache/pip/http' or its parent
directory is not owned by the current user and the cache has been
disabled. Please check the permissions and owner of that directory. If
executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/ubuntu/.cache/pip' or its parent directory
is not owned by the current user and caching wheels has been disabled.
check the permissions and owner of that directory. If executing pip with
sudo, you may want sudo's -H flag.
Collecting pip
   Downloading
https://files.pythonhosted.org/packages/4a/08/6ca123073af4ebc4c5488a5bc8a010ac57aa39ce4d3c8a931ad504de4185/pip-19.3-py2.py3-none-any.whl
(1.4MB)
Installing collected packages: pip
   Found existing installation: pip 19.2.3
     Uninstalling pip-19.2.3:
       Successfully uninstalled pip-19.2.3
Successfully installed pip-19.3
2019-10-15 16:38:27,163    INFO updater.py:282 -- NodeUpdater: Running
sudo pip install ray on 54.162.234.188...
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
WARNING: The directory '/home/ubuntu/.cache/pip/http' or its parent
directory is not owned by the current user and the cache has been
disabled. Please check the permissions and owner of that directory. If
executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/ubuntu/.cache/pip' or its parent directory
is not owned by the current user and caching wheels has been disabled.
check the permissions and owner of that directory. If executing pip with
sudo, you may want sudo's -H flag.
Collecting ray
   Downloading
https://files.pythonhosted.org/packages/9b/e7/37a7f8dc2b1f96c760a3950d8bb5a3f14066f1699f5d004f0f6462d880c9/ray-0.7.5-cp36-cp36m-manylinux1_x86_64.whl
(74.9MB)
Requirement already satisfied: six>=1.0.0 in
/usr/local/lib/python3.6/dist-packages (from ray) (1.12.0)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages
(from ray) (3.11)
Requirement already satisfied: numpy>=1.14 in
/usr/local/lib/python3.6/dist-packages (from ray) (1.17.2)
Collecting colorama
   Downloading
https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Requirement already satisfied: protobuf>=3.8.0 in
/usr/local/lib/python3.6/dist-packages (from ray) (3.9.1)
Collecting redis>=3.3.2
   Downloading
https://files.pythonhosted.org/packages/32/ae/28613a62eea0d53d3db3147f8715f90da07667e99baeedf1010eb400f8c0/redis-3.3.11-py2.py3-none-any.whl
(66kB)
Collecting funcsigs
   Downloading
https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting click
   Downloading
https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
(81kB)
Collecting pytest
   Downloading
https://files.pythonhosted.org/packages/0c/91/d68f68ce54cd3e8afa1ef73ea1ad44df2438521b64c0820e5fd9b9f13b7d/pytest-5.2.1-py3-none-any.whl
(226kB)
Collecting jsonschema
   Downloading
https://files.pythonhosted.org/packages/ce/6c/888d7c3c1fce3974c88a01a6bc553528c99d3586e098eee23e8383dd11c3/jsonschema-3.1.1-py2.py3-none-any.whl
(56kB)
Requirement already satisfied: filelock in
/usr/local/lib/python3.6/dist-packages (from ray) (3.0.12)
Requirement already satisfied: setuptools in
/usr/local/lib/python3.6/dist-packages (from protobuf>=3.8.0->ray) (41.2.0)
Collecting atomicwrites>=1.0
   Downloading
https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl
Collecting packaging
   Downloading
https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
Collecting importlib-metadata>=0.12; python_version < "3.8"
   Downloading
https://files.pythonhosted.org/packages/f6/d2/40b3fa882147719744e6aa50ac39cf7a22a913cbcba86a0371176c425a3b/importlib_metadata-0.23-py2.py3-none-any.whl
Collecting attrs>=17.4.0
   Downloading
https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting pluggy<1.0,>=0.12
   Downloading
https://files.pythonhosted.org/packages/92/c7/48439f7d5fd6bddb4c04b850bb862b42e3e2b98570040dfaf68aedd8114b/pluggy-0.13.0-py2.py3-none-any.whl
Collecting wcwidth
   Downloading
https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting py>=1.5.0
   Downloading
https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl
(83kB)
Collecting more-itertools>=4.0.0
   Downloading
https://files.pythonhosted.org/packages/45/dc/3241eef99eb45f1def35cf93af35d1cf9ef4c0991792583b8f33ea41b092/more_itertools-7.2.0-py3-none-any.whl
(57kB)
Processing
./.cache/pip/wheels/bb/46/00/6d471ef0b813e3621f0abe6cb723c20d529d39a061de3f7c51/pyrsistent-0.15.4-cp36-cp36m-linux_x86_64.whl
Collecting pyparsing>=2.0.2
   Downloading
https://files.pythonhosted.org/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-none-any.whl
(65kB)
Collecting zipp>=0.5
   Downloading
https://files.pythonhosted.org/packages/74/3d/1ee25a26411ba0401b43c6376d2316a71addcc72ef8690b101b4ea56d76a/zipp-0.6.0-py2.py3-none-any.whl
Installing collected packages: colorama, redis, funcsigs, click,
atomicwrites, pyparsing, packaging, more-itertools, zipp,
importlib-metadata, attrs, pluggy, wcwidth, py, pytest, pyrsistent,
jsonschema, ray
Successfully installed atomicwrites-1.3.0 attrs-19.3.0 click-7.0
colorama-0.4.1 funcsigs-1.0.2 importlib-metadata-0.23 jsonschema-3.1.1
more-itertools-7.2.0 packaging-19.2 pluggy-0.13.0 py-1.8.0
pyparsing-2.4.2 pyrsistent-0.15.4 pytest-5.2.1 ray-0.7.5 redis-3.3.11
wcwidth-0.1.7 zipp-0.6.0
2019-10-15 16:38:52,832    INFO updater.py:282 -- NodeUpdater: Running
sudo apt-get install htop on 54.162.234.188...
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
   htop
0 upgraded, 1 newly installed, 0 to remove and 36 not upgraded.
Need to get 76.4 kB of archives.
After this operation, 215 kB of additional disk space will be used.
Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu
xenial-updates/universe amd64 htop amd64 2.0.1-1ubuntu1 [76.4 kB]
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs
shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Fetched 76.4 kB in 0s (5,460 kB/s)
Selecting previously unselected package htop.
(Reading database ... 89274 files and directories currently installed.)
Preparing to unpack .../htop_2.0.1-1ubuntu1_amd64.deb ...
Unpacking htop (2.0.1-1ubuntu1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up htop (2.0.1-1ubuntu1) ...
2019-10-15 16:39:08,823    INFO updater.py:282 -- NodeUpdater: Running
sudo pip install psutil on 54.162.234.188...
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
WARNING: The directory '/home/ubuntu/.cache/pip/http' or its parent
directory is not owned by the current user and the cache has been
disabled. Please check the permissions and owner of that directory. If
executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/ubuntu/.cache/pip' or its parent directory
is not owned by the current user and caching wheels has been disabled.
check the permissions and owner of that directory. If executing pip with
sudo, you may want sudo's -H flag.
Processing
./.cache/pip/wheels/90/7e/74/bb640d77775e6b6a78bcc3120f9fea4d2a28b2706de1cff37d/psutil-5.6.3-cp36-cp36m-linux_x86_64.whl
Installing collected packages: psutil
Successfully installed psutil-5.6.3
2019-10-15 16:39:11,764    INFO updater.py:282 -- NodeUpdater: Running
sudo pip install boto3==1.4.8 on 54.162.234.188...
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
WARNING: The directory '/home/ubuntu/.cache/pip/http' or its parent
directory is not owned by the current user and the cache has been
disabled. Please check the permissions and owner of that directory. If
executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/ubuntu/.cache/pip' or its parent directory
is not owned by the current user and caching wheels has been disabled.
check the permissions and owner of that directory. If executing pip with
sudo, you may want sudo's -H flag.
Collecting boto3==1.4.8
   Downloading
https://files.pythonhosted.org/packages/7d/09/66fef826fb13a2cee74a1df56c269d2794a90ece49c3b77113b733e4b91d/boto3-1.4.8-py2.py3-none-any.whl
(128kB)
Collecting s3transfer<0.2.0,>=0.1.10
   Downloading
https://files.pythonhosted.org/packages/d7/14/2a0004d487464d120c9fb85313a75cd3d71a7506955be458eebfe19a6b1d/s3transfer-0.1.13-py2.py3-none-any.whl
(59kB)
Collecting botocore<1.9.0,>=1.8.0
   Downloading
https://files.pythonhosted.org/packages/5a/9f/c74178afb86983446a4aea1f308272f6e92a96dd7b6efd086eb50241b10c/botocore-1.8.50-py2.py3-none-any.whl
(4.1MB)
Collecting jmespath<1.0.0,>=0.7.1
   Downloading
https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1
   Downloading
https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
(226kB)
Collecting docutils>=0.10
   Downloading
https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
(547kB)
Requirement already satisfied: six>=1.5 in
/usr/local/lib/python3.6/dist-packages (from
python-dateutil<3.0.0,>=2.1->botocore<1.9.0,>=1.8.0->boto3==1.4.8) (1.12.0)
Installing collected packages: python-dateutil, jmespath, docutils,
botocore, s3transfer, boto3
Successfully installed boto3-1.4.8 botocore-1.8.50 docutils-0.15.2
jmespath-0.9.4 python-dateutil-2.8.0 s3transfer-0.1.13
2019-10-15 16:39:15,266    INFO updater.py:282 -- NodeUpdater: Running
sudo ray stop on 54.162.234.188...
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2019-10-15 16:39:22,933    INFO updater.py:282 -- NodeUpdater: Running
sudo ulimit -n 65536; sudo ray start --head --redis-port=6379
--object-manager-port=8076
--autoscaling-config=~/ray_bootstrap_config.yaml on 54.162.234.188...
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
sudo: ulimit: command not found
2019-10-15 23:39:23,733    INFO scripts.py:307 -- Using IP address
172.31.46.199 for this node.
2019-10-15 23:39:23,734    INFO resource_spec.py:205 -- Starting Ray
with 0.1 GiB memory available for workers and up to 0.05 GiB for
objects. You can adjust these settings with ray.init(memory=<bytes>,
object_store_memory=<bytes>).
Traceback (most recent call last):
   File "/usr/local/bin/ray", line 8, in <module>
     sys.exit(main())
   File "/usr/local/lib/python3.6/dist-packages/ray/scripts/scripts.py",
line 805, in main
     return cli()
   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line
764, in __call__
     return self.main(*args, **kwargs)
   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line
717, in main
     rv = self.invoke(ctx)
   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line
1137, in invoke
     return _process_result(sub_ctx.command.invoke(sub_ctx))
   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line
956, in invoke
     return ctx.invoke(self.callback, **ctx.params)
   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line
555, in invoke
     return callback(*args, **kwargs)
   File "/usr/local/lib/python3.6/dist-packages/ray/scripts/scripts.py",
line 318, in start
     node = ray.node.Node(ray_params, head=True, shutdown_at_exit=block)
   File "/usr/local/lib/python3.6/dist-packages/ray/node.py", line 156,
in __init__
     self.start_ray_processes()
   File "/usr/local/lib/python3.6/dist-packages/ray/node.py", line 584,
in start_ray_processes
     self.start_plasma_store()
   File "/usr/local/lib/python3.6/dist-packages/ray/node.py", line 486,
in start_plasma_store
     plasma_store_socket_name=self._plasma_store_socket_name)
   File "/usr/local/lib/python3.6/dist-packages/ray/services.py", line
1360, in start_plasma_store
     ray_constants.OBJECT_STORE_MINIMUM_MEMORY_BYTES))
ValueError: Attempting to cap object store memory usage at 53302886
bytes, but the minimum allowed is 78643200 bytes.
2019-10-15 16:39:24,190    INFO log_timer.py:21 -- NodeUpdater:
i-0b85bd01a56ecf2e5: Setup commands completed [LogTimer=69048ms]
2019-10-15 16:39:24,190    INFO log_timer.py:21 -- NodeUpdater:
i-0b85bd01a56ecf2e5: Applied config
fd34f5b8108dc366e612a860fcedf10442219353 [LogTimer=127867ms]
2019-10-15 16:39:24,190    ERROR updater.py:152 -- NodeUpdater:
i-0b85bd01a56ecf2e5: Error updating (Exit Status 1) ssh -i
/home/rajmund/.ssh/ray-autoscaler_us-east-1.pem -o ConnectTimeout=120s
-o StrictHostKeyChecking=no -o ControlMaster=auto -o
ControlPath=/tmp/ray_ssh_18a3dbcd7f/0d1813f94f/%C -o ControlPersist=10s
ubuntu@54.162.234.188 bash --login -c -i 'true && source ~/.bashrc &&
export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && sudo ulimit -n 65536;
sudo ray start --head --redis-port=6379 --object-manager-port=8076
--autoscaling-config=~/ray_bootstrap_config.yaml'
Exception in thread Thread-2:
Traceback (most recent call last):
   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
     self.run()
   File
"/usr/local/lib/python3.6/dist-packages/ray/autoscaler/updater.py", line
155, in run
     raise e
   File
"/usr/local/lib/python3.6/dist-packages/ray/autoscaler/updater.py", line
144, in run
     self.do_update()
   File
"/usr/local/lib/python3.6/dist-packages/ray/autoscaler/updater.py", line
240, in do_update
     self.ssh_cmd(cmd, exit_on_fail=self.exit_on_update_fail)
   File
"/usr/local/lib/python3.6/dist-packages/ray/autoscaler/updater.py", line
308, in ssh_cmd
     stderr=redirect or sys.stderr)
   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
     raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh', '-i',
'/home/rajmund/.ssh/ray-autoscaler_us-east-1.pem', '-o',
'ConnectTimeout=120s', '-o', 'StrictHostKeyChecking=no', '-o',
'ControlMaster=auto', '-o',
'ControlPath=/tmp/ray_ssh_18a3dbcd7f/0d1813f94f/%C', '-o',
'ControlPersist=10s', 'ubuntu@54.162.234.188', "bash --login -c -i 'true
&& source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore &&
sudo ulimit -n 65536; sudo ray start --head --redis-port=6379
--object-manager-port=8076
--autoscaling-config=~/ray_bootstrap_config.yaml'"]' returned non-zero
exit status 1.

2019-10-15 16:39:24,306    INFO log_timer.py:21 -- AWSNodeProvider: Set
tag ray-node-status=update-failed on ['i-0b85bd01a56ecf2e5']
[LogTimer=115ms]
2019-10-15 16:39:24,323    ERROR commands.py:267 --
get_or_create_head_node: Updating 54.162.234.188 failed```

**Comment by shreyagu** [comment]
This is what i get when i run `ray --head`

```
sudo: ulimit: command not found

2019-10-15 23:39:23,733    INFO scripts.py:307 -- Using IP address
172.31.46.199 for this node.

2019-10-15 23:39:23,734    INFO resource_spec.py:205 -- Starting Ray
with 0.1 GiB memory available for workers and up to 0.05 GiB for
objects. You can adjust these settings with ray.init(memory=<bytes>,
object_store_memory=<bytes>).

Traceback (most recent call last):

   File "/usr/local/bin/ray", line 8, in <module>

     sys.exit(main())

   File "/usr/local/lib/python3.6/dist-packages/ray/scripts/scripts.py",
line 805, in main

     return cli()

   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line
764, in __call__

     return self.main(*args, **kwargs)

   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line
717, in main

     rv = self.invoke(ctx)

   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line
1137, in invoke

     return _process_result(sub_ctx.command.invoke(sub_ctx))

   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line
956, in invoke

     return ctx.invoke(self.callback, **ctx.params)

   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line
555, in invoke

     return callback(*args, **kwargs)

   File "/usr/local/lib/python3.6/dist-packages/ray/scripts/scripts.py",
line 318, in start

     node = ray.node.Node(ray_params, head=True, shutdown_at_exit=block)

   File "/usr/local/lib/python3.6/dist-packages/ray/node.py", line 156,
in __init__

     self.start_ray_processes()

   File "/usr/local/lib/python3.6/dist-packages/ray/node.py", line 584,
in start_ray_processes

     self.start_plasma_store()

   File "/usr/local/lib/python3.6/dist-packages/ray/node.py", line 486,
in start_plasma_store

     plasma_store_socket_name=self._plasma_store_socket_name)

   File "/usr/local/lib/python3.6/dist-packages/ray/services.py", line
1360, in start_plasma_store

     ray_constants.OBJECT_STORE_MINIMUM_MEMORY_BYTES))

ValueError: Attempting to cap object store memory usage at 53302886
bytes, but the minimum allowed is 78643200 bytes.

2019-10-15 16:39:24,190    INFO log_timer.py:21 -- NodeUpdater:
i-0b85bd01a56ecf2e5: Setup commands completed [LogTimer=69048ms]

2019-10-15 16:39:24,190    INFO log_timer.py:21 -- NodeUpdater:
i-0b85bd01a56ecf2e5: Applied config
fd34f5b8108dc366e612a860fcedf10442219353 [LogTimer=127867ms]

2019-10-15 16:39:24,190    ERROR updater.py:152 -- NodeUpdater:
i-0b85bd01a56ecf2e5: Error updating (Exit Status 1) ssh -i
/home/rajmund/.ssh/ray-autoscaler_us-east-1.pem -o ConnectTimeout=120s
-o StrictHostKeyChecking=no -o ControlMaster=auto -o
ControlPath=/tmp/ray_ssh_18a3dbcd7f/0d1813f94f/%C -o ControlPersist=10s
ubuntu@54.162.234.188 bash --login -c -i 'true && source ~/.bashrc &&
export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && sudo ulimit -n 65536;
sudo ray start --head --redis-port=6379 --object-manager-port=8076
--autoscaling-config=~/ray_bootstrap_config.yaml'

Exception in thread Thread-2:

Traceback (most recent call last):

   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner

     self.run()

   File
"/usr/local/lib/python3.6/dist-packages/ray/autoscaler/updater.py", line
155, in run

     raise e

   File
"/usr/local/lib/python3.6/dist-packages/ray/autoscaler/updater.py", line
144, in run

     self.do_update()

   File
"/usr/local/lib/python3.6/dist-packages/ray/autoscaler/updater.py", line
240, in do_update

     self.ssh_cmd(cmd, exit_on_fail=self.exit_on_update_fail)

   File
"/usr/local/lib/python3.6/dist-packages/ray/autoscaler/updater.py", line
308, in ssh_cmd

     stderr=redirect or sys.stderr)

   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call

     raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['ssh', '-i',
'/home/rajmund/.ssh/ray-autoscaler_us-east-1.pem', '-o',
'ConnectTimeout=120s', '-o', 'StrictHostKeyChecking=no', '-o',
'ControlMaster=auto', '-o',
'ControlPath=/tmp/ray_ssh_18a3dbcd7f/0d1813f94f/%C', '-o',
'ControlPersist=10s', 'ubuntu@54.162.234.188', "bash --login -c -i 'true
&& source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore &&
sudo ulimit -n 65536; sudo ray start --head --redis-port=6379
--object-manager-port=8076
--autoscaling-config=~/ray_bootstrap_config.yaml'"]' returned non-zero
exit status 1.



2019-10-15 16:39:24,306    INFO log_timer.py:21 -- AWSNodeProvider: Set
tag ray-node-status=update-failed on ['i-0b85bd01a56ecf2e5']
[LogTimer=115ms]

2019-10-15 16:39:24,323    ERROR commands.py:267 --
get_or_create_head_node: Upda```

**Comment by shreyagu** [comment]
@robertnishihara  @ericl @richardliaw can someone please help?

**Comment by edoakes** [comment]
@shreyagu what OS distribution are you running on? Looks like it failed because `ulimit` wasn't found - can you remove the `ulimit` command in the head and worker start ray commands in the config?

Also, it looks like it failed to start because your machine doesn't have enough memory. Could you try running on a machine with at least ~8GiB of memory?
