### ISSUE TITLE
[autoscaler] GCP headnode fails on startup sometimes

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#5829]
```
  Traceback (most recent call last):
    File "experiments/references/launch/ray/ray_sac.py", line 193, in <module>
      docker_variant=dict(),
    File "/home/steven/res/railrl-private/railrl/launchers/ray/launcher.py", line 21, in launch_experiment
      *args, **kwargs)
    File "/home/steven/res/railrl-private/railrl/launchers/ray/remote_launch.py", line 235, in launch_remote_experiment
      port_forward=None)
    File "/home/steven/miniconda3/envs/railrl-env-4/lib/python3.5/site-packages/ray/autoscaler/commands.py", line 344, in exec_cluster
      config, config_file, override_cluster_name, create_if_needed=start)
    File "/home/steven/miniconda3/envs/railrl-env-4/lib/python3.5/site-packages/ray/autoscaler/commands.py", line 528, in _get_head_node
      override_cluster_name=override_cluster_name)
    File "/home/steven/miniconda3/envs/railrl-env-4/lib/python3.5/site-packages/ray/autoscaler/commands.py", line 205, in get_or_create_head_node
      assert len(nodes) == 1, "Failed to create head node."
```

**Comment by richardliaw** [comment]
This might be just a AWS issue resolved a long time ago.
