### ISSUE TITLE
Better error message for ray.exceptions.RayWorkerError

### ISSUE THREAD

**Issue by devin-petersohn** [ray-project/ray#5840]
### Describe the problem

Users who shut down their python environment before all computation has completed will see the following error: 

```
ray.exceptions.RayWorkerError: The worker died unexpectedly while executing this task.
```
This makes it seem like there was a system error, and has caused some problems for Modin users https://github.com/modin-project/modin/issues/820

This is prevalent in python scripts when the user does not do anything with the result of the computation. A better error message would help the user understand what the issue actually is.

### Source code / logs

Traceback:

```
Traceback (most recent call last):
File "train_models.py", line 38, in
df_train, df_test = create_features(target, project_path)
File "/sleuth_hrz/sleuth_hrz_models/notebooks/unsupervised_codes/Asurion_auto_ML/preprocess.py", line 98, in create_features
df = df.drop_duplicates()
File "/opt/conda/envs/sleuth_hrz/lib/python3.5/site-packages/modin/pandas/dataframe.py", line 184, in drop_duplicates
subset=subset, keep=keep, inplace=inplace
File "/opt/conda/envs/sleuth_hrz/lib/python3.5/site-packages/modin/pandas/base.py", line 1055, in drop_duplicates
duplicates = self.duplicated(keep=keep, **kwargs)
File "/opt/conda/envs/sleuth_hrz/lib/python3.5/site-packages/modin/pandas/dataframe.py", line 197, in duplicated
return super(DataFrame, self).duplicated(subset=subset, keep=keep)
File "/opt/conda/envs/sleuth_hrz/lib/python3.5/site-packages/modin/pandas/base.py", line 1060, in duplicated
return self._default_to_pandas("duplicated", keep=keep, **kwargs)
File "/opt/conda/envs/sleuth_hrz/lib/python3.5/site-packages/modin/pandas/base.py", line 216, in _default_to_pandas
self._to_pandas(), *args, **kwargs
File "/opt/conda/envs/sleuth_hrz/lib/python3.5/site-packages/modin/pandas/dataframe.py", line 2203, in _to_pandas
return self._query_compiler.to_pandas()
File "/opt/conda/envs/sleuth_hrz/lib/python3.5/site-packages/modin/backends/pandas/query_compiler.py", line 52, in to_pandas
return self._modin_frame.to_pandas()
File "/opt/conda/envs/sleuth_hrz/lib/python3.5/site-packages/modin/engines/base/frame/data.py", line 1121, in to_pandas
df = self._frame_mgr_cls.to_pandas(self._partitions)
File "/opt/conda/envs/sleuth_hrz/lib/python3.5/site-packages/modin/engines/base/frame/partition_manager.py", line 264, in to_pandas
retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]
File "/opt/conda/envs/sleuth_hrz/lib/python3.5/site-packages/modin/engines/base/frame/partition_manager.py", line 264, in
retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]
File "/opt/conda/envs/sleuth_hrz/lib/python3.5/site-packages/modin/engines/base/frame/partition_manager.py", line 264, in
retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]
File "/opt/conda/envs/sleuth_hrz/lib/python3.5/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 81, in to_pandas
dataframe = self.get()
File "/opt/conda/envs/sleuth_hrz/lib/python3.5/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 33, in get
return ray.get(self.oid)
File "/opt/conda/envs/sleuth_hrz/lib/python3.5/site-packages/ray/worker.py", line 2247, in get
raise value
ray.exceptions.RayWorkerError: The worker died unexpectedly while executing this task.
```

**Comment by richardliaw** [comment]
What do you mean by "shut down their python environment"?

**Comment by devin-petersohn** [comment]
In the case that they are running in a script, the asynchrony can cause ray to shut down before the end of all computation in the script. More details can be found in the issue linked above.

**Comment by scottsun94** [comment]
I believe the worker death error has been improved. Shall we close this? @rkooo567

**Comment by rkooo567** [comment]
I think we improved this a lot, but the task error message is probably still not 100% working. However, we are tracking that here. https://github.com/ray-project/ray/issues/27947 here, so I will close this as duplicate
