### ISSUE TITLE
RayTaskError doesn't subclass original exception correctly

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#5862]
### System information
- **Ray version**: 0.7.5

### Describe the problem
I'm not exactly sure what's going on, but it looks like some issue with recreating the original exception. The original exception here is a `ray.exceptions.UnreconstructableError`, but it fails when trying to print the exception because there is no `self.object_id`.

### Source code / logs
```python
import numpy as np
import ray
ray.init(object_store_memory=1e9)

@ray.remote
def f(x):
    return x

# Trigger unreconstructable object error.
x = [f.remote(np.ones(int(1e7))) for _ in range(10)]
ray.get(x[0])
```

This results in:
```
Traceback (most recent call last):
  File "/Users/swang/ray/python/ray/worker.py", line 2121, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(UnreconstructableError): <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "error.py", line 11, in <module>
    ray.get(x[0])
  File "/Users/swang/ray/python/ray/worker.py", line 2131, in get
    return values
  File "python/ray/includes/libcoreworker.pxi", line 32, in ray._raylet.ProfileEvent.__exit__
    "value": str(value),
  File "/Users/swang/ray/python/ray/exceptions.py", line 155, in __str__
    self.object_id.hex(),
AttributeError: 'RayTaskError(UnreconstructableError)' object has no attribute 'object_id'
2019-10-08 10:35:18,456 WARNING worker.py:1619 -- The task with ID ffffffffffffffffffff01000000 is a driver task and so the object created by ray.put could not be reconstructed.
```

It looks like it's related to # #5799.

**Comment by ericl** [comment]
I have this in some other pr:

```
diff --git a/python/ray/exceptions.py b/python/ray/exceptions.py
index ba0c2e5d6..680cb5aac 100644
--- a/python/ray/exceptions.py
+++ b/python/ray/exceptions.py
@@ -56,6 +56,9 @@ class RayTaskError(RayError):
         if issubclass(RayTaskError, self.cause_cls):
             return self  # already satisfied
 
+        if issubclass(RayError, self.cause_cls):
+            return self  # don't try to wrap ray internal errors
+
         class cls(self.cause_cls, RayTaskError):
             def __init__(self, function_name, traceback_str, cause_cls, pid,
                          host):
```

**Comment by ericl** [comment]
@stephanie-wang try out https://github.com/ray-project/ray/compare/master...ericl:no-wrap?expand=1 ? For some reason your example doesn't fail for me.
