### ISSUE TITLE
Custom Head and Worker Name Tag in cluster.yaml (AWS)

### ISSUE THREAD

**Issue by dekromp** [ray-project/ray#5895]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mojave 10.14.6
**Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.5
- **Python version**: 3.6
- **Exact command to reproduce**:

```
head_node:
    ...
    TagSpecifications:
        - ResourceType: "instance"
          Tags:
            # Assigning the Name key causes an error with ray.
            - Key: Name
              Value: myname
```
### Describe the problem
Hi,
is it possible to set the instance Name Tag when ray is spinnnig up head and worker nodes on AWS EC2? Using the boto3 API in the `cluster.yaml` file  as shown in the snippet above causes an error:

```
Traceback (most recent call last):
  File "/Users/denis/anaconda2/envs/dev-p36/bin/ray", line 10, in <module>
    sys.exit(main())
  File "/Users/denis/anaconda2/envs/dev-p36/lib/python3.6/site-packages/ray/scripts/scripts.py", line 805, in main
    return cli()
  File "/Users/denis/anaconda2/envs/dev-p36/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/denis/anaconda2/envs/dev-p36/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/denis/anaconda2/envs/dev-p36/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/denis/anaconda2/envs/dev-p36/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/denis/anaconda2/envs/dev-p36/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/denis/anaconda2/envs/dev-p36/lib/python3.6/site-packages/ray/scripts/scripts.py", line 492, in create_or_update
    no_restart, restart_only, yes, cluster_name)
  File "/Users/denis/anaconda2/envs/dev-p36/lib/python3.6/site-packages/ray/autoscaler/commands.py", line 47, in create_or_update_cluster
    override_cluster_name)
  File "/Users/denis/anaconda2/envs/dev-p36/lib/python3.6/site-packages/ray/autoscaler/commands.py", line 205, in get_or_create_head_node
    assert len(nodes) == 1, "Failed to create head node."

```

**Comment by richardliaw** [comment]
Right now this is not possible because the autoscaler depends on tags for node identification. See `ray/python/ray/autoscaler/tags.py` for where these tags are set.

Curious - why do you want to change the tag name?

**Comment by dekromp** [comment]
Hi Richard,
thanks for the quick response. We have naming conventions for our EC2 instances so we can associate resources to people and projects (we use a bunch of other tags, too). In addition, we have bots that "deal" with instances that do not follow these conventions.

**Comment by vtomenko** [comment]
We have similar use case and ability to specify custom tags is important.
