### ISSUE TITLE
 ValueError: ctypes objects containing pointers cannot be pickled

### ISSUE THREAD

**Issue by lunasdejavu** [ray-project/ray#5933]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: pip
- **Ray version**:0.7.5
- **Python version**:3.6
- **Exact command to reproduce**:

### Describe the problem

I am trying to run a classification by caffe and a objectdetection by python darknet(something with pyc) the darknet code is from 
most of the codes are for darknet  the main functions are the classifcation() and recognition() 
```
def sample(probs):
    s = sum(probs)
    probs = [a//s for a in probs]
    r = random.uniform(0, 1)
    for i in range(len(probs)):
        r = r - probs[i]
        if r <= 0:
            return i
    return len(probs)-1

def c_array(ctype, values):
    arr = (ctype*len(values))()
    arr[:] = values
    return arr

class BOX(Structure):
    _fields_ = [("x", c_float),
                ("y", c_float),
                ("w", c_float),
                ("h", c_float)]

class DETECTION(Structure):
    _fields_ = [("bbox", BOX),
                ("classes", c_int),
                ("prob", POINTER(c_float)),
                ("mask", POINTER(c_float)),
                ("objectness", c_float),
                ("sort_class", c_int)]
class IMAGE(Structure):
    _fields_ = [("w", c_int),
                ("h", c_int),
                ("c", c_int),
                ("data", POINTER(c_float))]

class METADATA(Structure):
    _fields_ = [("classes", c_int),
                ("names", POINTER(c_char_p))]
    lib = CDLL("/data/workspace/willy_sung/py_darknet/darknet/libdarknet.so", RTLD_GLOBAL)
lib.network_width.argtypes = [c_void_p]
lib.network_width.restype = c_int
lib.network_height.argtypes = [c_void_p]
lib.network_height.restype = c_int

predict = lib.network_predict
predict.argtypes = [c_void_p, POINTER(c_float)]
predict.restype = POINTER(c_float)

set_gpu = lib.cuda_set_device
set_gpu.argtypes = [c_int]
make_image = lib.make_image
make_image.argtypes = [c_int, c_int, c_int]
make_image.restype = IMAGE

get_network_boxes = lib.get_network_boxes
get_network_boxes.argtypes = [c_void_p, c_int, c_int, c_float, c_float, POINTER(c_int), c_int, POINTER(c_int)]
get_network_boxes.restype = POINTER(DETECTION)

make_network_boxes = lib.make_network_boxes
make_network_boxes.argtypes = [c_void_p]
make_network_boxes.restype = POINTER(DETECTION)

free_detections = lib.free_detections
free_detections.argtypes = [POINTER(DETECTION), c_int]

free_ptrs = lib.free_ptrs
free_ptrs.argtypes = [POINTER(c_void_p), c_int]

network_predict = lib.network_predict
network_predict.argtypes = [c_void_p, POINTER(c_float)]

reset_rnn = lib.reset_rnn
reset_rnn.argtypes = [c_void_p]

load_net = lib.load_network
load_net.argtypes = [c_char_p, c_char_p, c_int]
load_net.restype = c_void_p

do_nms_obj = lib.do_nms_obj
do_nms_obj.argtypes = [POINTER(DETECTION), c_int, c_int, c_float]

do_nms_sort = lib.do_nms_sort
do_nms_sort.argtypes = [POINTER(DETECTION), c_int, c_int, c_float]

free_image = lib.free_image
free_image.argtypes = [IMAGE]

letterbox_image = lib.letterbox_image
letterbox_image.argtypes = [IMAGE, c_int, c_int]
letterbox_image.restype = IMAGE

load_meta = lib.get_metadata
lib.get_metadata.argtypes = [c_char_p]
lib.get_metadata.restype = METADATA

load_image = lib.load_image_color
load_image.argtypes = [c_char_p, c_int, c_int]
load_image.restype = IMAGE

rgbgr_image = lib.rgbgr_image
rgbgr_image.argtypes = [IMAGE]

predict_image = lib.network_predict_image
predict_image.argtypes = [c_void_p, IMAGE]
predict_image.restype = POINTER(c_float)

net = load_net(bytes(net_path, encoding='utf-8'), bytes(weight_path, encoding='utf-8'), 0)
meta = load_meta(b"/data/workspace/willy_sung/darknet/cfgs_darknet/lpr_obj.data")
caffe.set_mode_gpu();
caffe.set_device(0); 

net_classification = caffe.Net(net_file_classification,caffe_model_classfication,caffe.TEST) 
def recognition_single(net, meta, image, thresh=.5, hier_thresh=.5, nms=.45):
    im = load_image(bytes(image, encoding='utf-8'), 0, 0)
    num = c_int(0)
    pnum = pointer(num)
    predicted_name = []
    predict_image(net, im)
    dets = get_network_boxes(net, im.w, im.h, thresh, hier_thresh, None, 0, pnum)
    num = pnum[0]
    if (nms): do_nms_obj(dets, num, meta.classes, nms);

    res = []
    for j in range(num):
        for i in range(meta.classes):
            if dets[j].prob[i] > 0:
                b = dets[j].bbox
                res.append((meta.names[i], dets[j].prob[i], (b.x, b.y, b.w, b.h)))
    res = sorted(res, key=lambda x: -x[1])
    rr= sorted(res, key=lambda x: x[2][0])
    for j in range(len(rr)):
        predicted_name.append(rr[j][0].decode("utf-8"))
    name = ''.join(predicted_name)
    
    free_image(im)
    free_detections(dets, num)
    return name

@ray.remote
def classification(lp_imgs):
    fmts=[]
    for lp_img in lp_imgs:
        img = cv2.cvtColor(lp_img, cv2.COLOR_BGR2RGB)
        img = preprocess(lp_img, CLS_W, CLS_H)
        img = img.astype(np.float32)
        img = img.transpose((2, 0, 1))
        net_classification.blobs['data'].data[...] = img
        out = net_classification.forward()
        fmt = np.argmax(out['prob'])
        fmts.append(fmt)
    return fmts
@ray.remote
def recognition(len_lps):
    lp_names=[]
    for i in range(len_lps):
        name = recognition_single(net, meta, 'wtest' + str(i)+ '.jpg')
        lp_names.append(name)
    return lp_names
```
```
            result_ids= []
            result_ids.append(recognition.remote(len(LPs)))
            result_ids.append(classification.remote(LPs))
            results = ray.get(result_ids)
```

### Source code / logs

the logs shows

```
2019-10-16 17:21:38,242 INFO resource_spec.py:205 -- Starting Ray with 20.85 GiB memory available for workers and up to 10.43 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
Traceback (most recent call last):
  File "lp_evaluation_3.py", line 639, in <module>
    main()
  File "lp_evaluation_3.py", line 616, in main
    result_ids.append(recognition.remote(len(LPs)))
  File "/usr/local/lib/python3.6/dist-packages/ray/remote_function.py", line 85, in _remote_proxy
    return self._remote(args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ray/remote_function.py", line 129, in _remote
    worker.function_actor_manager.export(self)
  File "/usr/local/lib/python3.6/dist-packages/ray/function_manager.py", line 347, in export
    self._do_export(remote_function)
  File "/usr/local/lib/python3.6/dist-packages/ray/function_manager.py", line 358, in _do_export
    pickled_function = pickle.dumps(function)
  File "/usr/local/lib/python3.6/dist-packages/ray/cloudpickle/cloudpickle.py", line 1123, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python3.6/dist-packages/ray/cloudpickle/cloudpickle.py", line 482, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.6/dist-packages/ray/cloudpickle/cloudpickle.py", line 556, in save_function
    return self.save_function_tuple(obj)
  File "/usr/local/lib/python3.6/dist-packages/ray/cloudpickle/cloudpickle.py", line 756, in save_function_tuple
    save(state)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.6/dist-packages/ray/cloudpickle/cloudpickle.py", line 556, in save_function
    return self.save_function_tuple(obj)
  File "/usr/local/lib/python3.6/dist-packages/ray/cloudpickle/cloudpickle.py", line 756, in save_function_tuple
    save(state)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib/python3.6/pickle.py", line 496, in save
    rv = reduce(self.proto)
ValueError: ctypes objects containing pointers cannot be pickled
```
so that I want to know how to save this error

**Comment by ganlinzhang** [comment]
hello，I have the same problem，did you solve this problem？ thanks！

**Comment by lunasdejavu** [comment]
> hello，I have the same problem，did you solve this problem？ thanks！
no

**Comment by falsemail** [comment]
hello，I have the same problem，did you solve this problem？ thanks！
no

**Comment by idiotic-bird** [comment]
hello，I have the same problem，did you solve this problem？ thanks！
no

**Comment by genspire** [comment]
I believe this part of the documentation helps with the above issue: https://docs.ray.io/en/stable/serialization.html
The idea being that Ray is using cloudpickle to serialize function results which are not of a supported type.

**Comment by mxuran** [comment]
I tried to use tune on my own code and also had this problem. My code contains c++ and I haven't found a solution yet.
