### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'vmstat'

### ISSUE THREAD

**Issue by tatianafrank** [ray-project/ray#5935]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian GNU/Linux 9
- **Ray installed from (source or binary)**:
- **Ray version**: 0.75
- **Python version**: 3.5.3
- **Exact command to reproduce**: ray.init

### Describe the problem
Im running Ray in a docker image using Poetry and getting a vmstat error after ray.init() so I installed psutil using pip but im still getting the error. If I do pip list i see i have psutil (5.6.3) installed. I pasted the full stack trace below. 

### Source code / logs
```2019-10-16 16:07:50,443 WARNING worker.py:1426 -- WARNING: Not updating worker name since `setproctitle` is not installed. Install this with `pip install setproctitle` (or ray[debug]) to enable monitoring of worker processes.
[2019-10-16 16:07:50,482] ERROR in app: Exception on /ray [GET]
Traceback (most recent call last):
  File "/home/python/.cache/pypoetry/virtualenvs/w3-search-sandbox-org-ray-test-py3.5/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/python/.cache/pypoetry/virtualenvs/w3-search-sandbox-org-ray-test-py3.5/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/python/.cache/pypoetry/virtualenvs/w3-search-sandbox-org-ray-test-py3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python/.cache/pypoetry/virtualenvs/w3-search-sandbox-org-ray-test-py3.5/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/python/.cache/pypoetry/virtualenvs/w3-search-sandbox-org-ray-test-py3.5/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/python/.cache/pypoetry/virtualenvs/w3-search-sandbox-org-ray-test-py3.5/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/python/app/w3_search_sandbox_org_ray_test/__init__.py", line 18, in ray
    return ray_pipe.main()
  File "/home/python/app/w3_search_sandbox_org_ray_test/ray_pipe.py", line 23, in main
    ray.init()
  File "/home/python/.cache/pypoetry/virtualenvs/w3-search-sandbox-org-ray-test-py3.5/lib/python3.5/site-packages/ray/worker.py", line 1483, in init
    head=True, shutdown_at_exit=False, ray_params=ray_params)
  File "/home/python/.cache/pypoetry/virtualenvs/w3-search-sandbox-org-ray-test-py3.5/lib/python3.5/site-packages/ray/node.py", line 149, in __init__
    self.start_head_processes()
  File "/home/python/.cache/pypoetry/virtualenvs/w3-search-sandbox-org-ray-test-py3.5/lib/python3.5/site-packages/ray/node.py", line 571, in start_head_processes
    self.start_redis()
  File "/home/python/.cache/pypoetry/virtualenvs/w3-search-sandbox-org-ray-test-py3.5/lib/python3.5/site-packages/ray/node.py", line 419, in start_redis
    self.get_resource_spec(),
  File "/home/python/.cache/pypoetry/virtualenvs/w3-search-sandbox-org-ray-test-py3.5/lib/python3.5/site-packages/ray/node.py", line 240, in get_resource_spec
    self._ray_params.redis_max_memory).resolve(is_head=self.head)
  File "/home/python/.cache/pypoetry/virtualenvs/w3-search-sandbox-org-ray-test-py3.5/lib/python3.5/site-packages/ray/resource_spec.py", line 151, in resolve
    system_memory = ray.utils.get_system_memory()
  File "/home/python/.cache/pypoetry/virtualenvs/w3-search-sandbox-org-ray-test-py3.5/lib/python3.5/site-packages/ray/utils.py", line 427, in get_system_memory
    memory_in_bytes = vmstat("total memory") * bytes_in_kilobyte
  File "/home/python/.cache/pypoetry/virtualenvs/w3-search-sandbox-org-ray-test-py3.5/lib/python3.5/site-packages/ray/utils.py", line 370, in vmstat
    out = subprocess.check_output(["vmstat", "-s"])
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'vmstat'```

**Comment by tatianafrank** [comment]
Ok resolved this by installing psutil differently

**Comment by CaioMS2000** [comment]
> Ok resolved this by installing psutil differently

and how was it ? i'm having the same error message

**Comment by CaioMS2000** [comment]
> @CaioMS2000 were you able to resolve it?
> 

It was so long ago that I don't remember what happened or what I had done
