### ISSUE TITLE
TypeError: can't pickle CudnnModule objects

### ISSUE THREAD

**Issue by che85** [ray-project/ray#5947]
When trying to wrap my existing pytorch code, I am getting the following error message:

I am using NVIDIA apex library for supporting mixed precision training. I turned mixed-precision off for testing ray and I am still getting the error. 

```
2019-10-18 09:42:19,876 INFO resource_spec.py:205 -- Starting Ray with 20.02 GiB memory available for workers and up to 10.01 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ray/tune/tune.py", line 196, in run
    run_identifier = Experiment._register_if_needed(run_or_experiment)
  File "/usr/local/lib/python3.6/site-packages/ray/tune/experiment.py", line 170, in _register_if_needed
    register_trainable(name, run_object)
  File "/usr/local/lib/python3.6/site-packages/ray/tune/registry.py", line 52, in register_trainable
    _global_registry.register(TRAINABLE_CLASS, name, trainable)
  File "/usr/local/lib/python3.6/site-packages/ray/tune/registry.py", line 91, in register
    self._to_flush[(category, key)] = pickle.dumps(value)
  File "/usr/local/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle.py", line 1123, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle.py", line 482, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib64/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/usr/lib64/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle.py", line 875, in save_global
    self.save_dynamic_class(obj)
  File "/usr/local/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle.py", line 686, in save_dynamic_class
    save(clsdict)
  File "/usr/lib64/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib64/python3.6/pickle.py", line 852, in _batch_setitems
    save(v)
  File "/usr/lib64/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle.py", line 556, in save_function
    return self.save_function_tuple(obj)
  File "/usr/local/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle.py", line 756, in save_function_tuple
    save(state)
  File "/usr/lib64/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib64/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib64/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python3.6/pickle.py", line 781, in save_list
    self._batch_appends(obj)
  File "/usr/lib64/python3.6/pickle.py", line 808, in _batch_appends
    save(tmp[0])
  File "/usr/lib64/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle.py", line 556, in save_function
    return self.save_function_tuple(obj)
  File "/usr/local/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle.py", line 756, in save_function_tuple
    save(state)
  File "/usr/lib64/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib64/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib64/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python3.6/pickle.py", line 781, in save_list
    self._batch_appends(obj)
  File "/usr/lib64/python3.6/pickle.py", line 805, in _batch_appends
    save(x)
  File "/usr/lib64/python3.6/pickle.py", line 496, in save
    rv = reduce(self.proto)
TypeError: can't pickle CudnnModule objects

Process finished with exit code 1
```

**ray version 0.7.5**

When turning off mixed precision and setting `torch.backends.cudnn.enabled = False`, training works. Is CuDNN not supported by ray?

Thank you,
Christian Herz

**Comment by che85** [comment]
I tested again. Mixed precision works. 

only if I use either one
```
torch.backends.cudnn.enabled = True
```
or 
```
torch.backends.cudnn.enabled = False
```

it fails to pickle.

**Comment by richardliaw** [comment]
Can you try moving the cudnn call into your trainable?

**Comment by youngwoo-yoon** [comment]
I encountered the same error. In my case, calling torch.backends.cudnn.version() in a trainable function was the problem. The training runs well with GPUs after removing that.

**Comment by robogast** [comment]
As I referenced in https://github.com/ray-project/ray/issues/8569
If I replace
```python
torch.backends.cudnn.benchmark = True
```
with
```python
eval('setattr(torch.backends.cudnn, "benchmark", True)')
```
Pickling works, and I assume benchmarking still works at runtime (although I haven't checked this.)

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
