### ISSUE TITLE
ray.tune with pytorch: only uses 1 of 2 GPUs

### ISSUE THREAD

**Issue by zaaaap** [ray-project/ray#5952]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.5
- **Python version**: 3.7.4
- **Exact command to reproduce**: slightly modified version of the original ray.tune pytorch example:

```
# Original Code here:
# https://github.com/pytorch/examples/blob/master/mnist/main.py
from __future__ import print_function

import os
import torch
import torch.optim as optim

import ray
from ray import tune
from ray.tune.schedulers import FIFOScheduler
from ray.tune.examples.mnist_pytorch import (train, test, get_data_loaders,
                                             ConvNet)

# Change these values if you want the training to run quicker or slower.
EPOCH_SIZE = 512
TEST_SIZE = 256

# Training settings
# Below comments are for documentation purposes only.
# yapf: disable
# __trainable_example_begin__
class TrainMNIST(tune.Trainable):
    def _setup(self, config):
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        print(f'CUDA device used: {torch.cuda.current_device()}')
        self.train_loader, self.test_loader = get_data_loaders()
        self.model = ConvNet().to(self.device)
        self.optimizer = optim.SGD(
            self.model.parameters(),
            lr=config.get("lr", 0.01),
            momentum=config.get("momentum", 0.9))

    def _train(self):
        train(
            self.model, self.optimizer, self.train_loader, device=self.device)
        acc = test(self.model, self.test_loader, self.device)
        return {"mean_accuracy": acc}

    def _save(self, checkpoint_dir):
        checkpoint_path = os.path.join(checkpoint_dir, "model.pth")
        torch.save(self.model.state_dict(), checkpoint_path)
        return checkpoint_path

    def _restore(self, checkpoint_path):
        self.model.load_state_dict(torch.load(checkpoint_path))


# __trainable_example_end__
# yapf: enable

if __name__ == "__main__":
    ray.init()
    sched = FIFOScheduler()
    analysis = tune.run(
        TrainMNIST,
        scheduler=sched,
        stop={
            "training_iteration": 100,
        },
        resources_per_trial={
            "cpu": 3,
            "gpu": 1
        },
        num_samples=3,
        checkpoint_at_end=True,
        checkpoint_freq=3,
        config={
            "lr": tune.uniform(0.001, 0.1),
            "momentum": tune.uniform(0.1, 0.9),
        })
```

### Describe the problem
The scheduler runs 2 experiments concurrently, but assigns both to the same GPU. I verified this with `print(f'CUDA device used: {torch.cuda.current_device()}')` in `_setup()`, which always prints device `0`.  
  

`ray.cluster_resources` gives me this: `{'CPU': 16.0, 'memory': 425.0, 'GPU': 2.0, 'object_store_memory': 171.0}`, so ray. tune should be able to use 2 GPUs. Any suggestions?  
   

Other versions are:
pytorch 1.3.0
CUDA 9.2

### Source code / logs
-

**Comment by richardliaw** [comment]
Hey @zaaaap, I think this is a misleading function from pytorch (https://discuss.pytorch.org/t/torch-cuda-current-device-always-return-0/26530/4). Can you try printing `os.environ["CUDA_VISIBLE_DEVICES"]`?

**Comment by zaaaap** [comment]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "some/folder/anaconda3/envs/myenv/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
```

**Comment by zaaaap** [comment]
Problem solved, there was none. I was confused by the output always being `0`. Just checked with `watch nvidia-smi` and it clearly shows that both GPUs are running 1 trainable each. Thanks anyways!
