### ISSUE TITLE
Odd core worker errors in ObjectId.__dealloc__

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#5981]
When running `rllib train --run=A3C --env=CartPole-v0 --eager --trace --config='{"log_level": "ERROR"}' --stop='{"training_iteration": 0}' --num-samples=5` on master you sometimes get:

```
(pid=13278) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=13278) Error in sys.excepthook:
(pid=13278) Traceback (most recent call last):
(pid=13278)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=13278)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=13278) TypeError: 'NoneType' object is not callable
(pid=13278) 
(pid=13278) Original exception was:
(pid=13278) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=13278) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=13278) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=13278) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=13278) Error in sys.excepthook:
(pid=13278) Traceback (most recent call last):
(pid=13278)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=13278)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=13278) TypeError: 'NoneType' object is not callable
(pid=13278) 
```

cc @edoakes

**Comment by ericl** [comment]
Followed by
```
*** Aborted at 1571813194 (unix time) try "date -d @1571813194" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x88) received by PID 13239 (TID 0x7f1c0d226700) from PID 136; stack trace: ***
    @     0x7f1c17d8bf20 (unknown)
    @     0x7f1c15633b91 __redisAsyncCommand
    @     0x7f1c1563451e redisvAsyncCommand
    @     0x7f1c155da1a6 ray::gcs::RedisAsyncContext::RedisAsyncCommand()
    @     0x7f1c156272bc ray::gcs::RedisContext::RunAsync<>()
    @     0x7f1c1562c8d2 ray::gcs::Log<>::Append()
    @     0x7f1c1560d305 ray::gcs::ProfileTable::AddProfileEventBatch()
    @     0x7f1c15520d42 ray::worker::Profiler::FlushEvents()
    @     0x7f1c1551feb1 boost::asio::detail::wait_handler<>::do_complete()
    @     0x7f1c155144a9 boost::asio::detail::scheduler::run()
    @     0x7f1c155146b1 ray::CoreWorker::StartIOService()
    @     0x7f1c14b8566f (unknown)
    @     0x7f1c17b356db start_thread
    @     0x7f1c17e6e88f clone
zsh: segmentation fault  ./train.py --run=A3C --env=CartPole-v0 --eager --trace   --num-samples=5
```

cc @richardliaw
