### ISSUE TITLE
Importing a saved model after tunning 

### ISSUE THREAD

**Issue by graciofilipe** [ray-project/ray#6046]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Mojave 10.14.6
- **Ray installed from (source or binary)**: pip install ray[rllib]
- **Ray version**: ray==0.7.6
- **Python version**: Python 3.7.4
- **Exact command to reproduce**:
```

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import gym
from ray.rllib.models import ModelCatalog
from ray.rllib.models.tf.tf_modelv2 import TFModelV2
from ray.rllib.models.tf.fcnet_v2 import FullyConnectedNetwork
from gym import spaces

import ray
from ray import tune
from ray.rllib.utils import try_import_tf
from ray.tune import grid_search

import ray.rllib.agents.ppo as ppo

tf = try_import_tf()


class Maze44(gym.Env):

    def __init__(self, env_config):
        #print('initing')
        self.end_state = np.array([5, 5])
        self.start_state = np.array([0, 0])
        self.current_state = np.array([0, 0])
        self.action_space = spaces.Discrete(4)
        self.observation_space = spaces.Box(low=np.array([0, 0]), high=np.array([5, 5]), dtype=np.float32)

    def get_reward(self):
        #print('getting reward')
        if (self.current_state == self.end_state).all():
            return 1
        else:
            return -1

    def get_state(self):
        #print('getting state')
        return self.current_state

    def step(self, action):
        self.take_action(action)
        reward = self.get_reward()
        obs = self.get_state()
        episode_over = (self.current_state == self.end_state).all()
        if episode_over:
            self.reset()
        return obs, reward, episode_over, {}

    def take_action(self, action):
        #print('taking action')
        if action == 0:
            # up
            self.current_state[1] = np.min([self.current_state[1] + 1, 5])
        if action == 1:
            # down
            self.current_state[1] = np.max([self.current_state[1] - 1, 0])
        if action == 2:
            # left
            self.current_state[0] = np.max([self.current_state[0] - 1, 0])
        if action == 3:
            # right
            self.current_state[0] = np.min([self.current_state[0] + 1, 5])

    def reset(self):
        self.current_state = np.array([0, 0])
        return np.array([0, 0])



class CustomModel(TFModelV2):
    """Example of a custom model that just delegates to a fc-net."""

    def __init__(self, obs_space, action_space, num_outputs, model_config,
                 name):
        super(CustomModel, self).__init__(obs_space, action_space, num_outputs,
                                          model_config, name)
        self.model = FullyConnectedNetwork(obs_space, action_space,
                                           num_outputs, model_config, name)
        self.register_variables(self.model.variables())

    def forward(self, input_dict, state, seq_lens):
        return self.model.forward(input_dict, state, seq_lens)

    def value_function(self):
        return self.model.value_function()


if __name__ == "__main__":
    # Can also register the env creator function explicitly with:
    # register_env("corridor", lambda config: SimpleCorridor(config))
    ray.init()
    ModelCatalog.register_custom_model("my_model", CustomModel)
    tunned = tune.run(
        "PPO",
        stop={
            "timesteps_total": 10000,
        },
        config={
            "eager": True,
            "env": Maze44,  # or "corridor" if registered above
            "model": {
                "custom_model": "my_model",
            },
            "vf_share_layers": True,
            "lr": grid_search([1e-2, 1e-6]),  # try different lrs
            "num_workers": 1,  # parallelism
            "env_config": {}
        },
        checkpoint_at_end=True
    )

    config = ppo.DEFAULT_CONFIG.copy()
    trainer = ppo.PPOTrainer(config=config, env=Maze44)
    best_log = tunned.get_best_logdir('episode_reward_mean')
    best_log += '/checkpoint_3/checkpoint-3' # please excuse the hard coding
    trainer.restore(best_log)

```

And the Trace (excluding the training logs): 

```
Traceback (most recent call last):
  File "ray_library/custom_env_exp.py", line 127, in <module>
    trainer.restore(best_log)
  File "/Users/filipe.gracio/projects/RL_book/.venv/lib/python3.7/site-packages/ray/tune/trainable.py", line 353, in restore
    self._restore(checkpoint_path)
  File "/Users/filipe.gracio/projects/RL_book/.venv/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 528, in _restore
    self.__setstate__(extra_data)
  File "/Users/filipe.gracio/projects/RL_book/.venv/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 161, in __setstate__
    Trainer.__setstate__(self, state)
  File "/Users/filipe.gracio/projects/RL_book/.venv/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 824, in __setstate__
    self.workers.local_worker().restore(state["worker"])
  File "/Users/filipe.gracio/projects/RL_book/.venv/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 710, in restore
    self.policy_map[pid].set_state(state)
  File "/Users/filipe.gracio/projects/RL_book/.venv/lib/python3.7/site-packages/ray/rllib/policy/policy.py", line 250, in set_state
    self.set_weights(state)
  File "/Users/filipe.gracio/projects/RL_book/.venv/lib/python3.7/site-packages/ray/rllib/policy/tf_policy.py", line 260, in set_weights
    return self._variables.set_flat(weights)
  File "/Users/filipe.gracio/projects/RL_book/.venv/lib/python3.7/site-packages/ray/experimental/tf_utils.py", line 153, in set_flat
    arrays = unflatten(new_weights, shapes)
  File "/Users/filipe.gracio/projects/RL_book/.venv/lib/python3.7/site-packages/ray/experimental/tf_utils.py", line 18, in unflatten
    array = vector[i:(i + size)].reshape(shape)
AttributeError: 'list' object has no attribute 'reshape'
```

**Comment by graciofilipe** [comment]
I'll add the pip freeze of the python venv: 

`
absl-py==0.8.1
appnope==0.1.0
astor==0.8.0
atari-py==0.2.6
atomicwrites==1.3.0
attrs==19.3.0
backcall==0.1.0
certifi==2019.9.11
chardet==3.0.4
Click==7.0
cloudpickle==1.2.2
colorama==0.4.1
decorator==4.4.1
filelock==3.0.12
funcsigs==1.0.2
future==0.18.1
gast==0.2.2
google-pasta==0.1.7
grpcio==1.24.3
gym==0.15.3
h5py==2.10.0
idna==2.8
importlib-metadata==0.23
ipdb==0.12.2
ipython==7.9.0
ipython-genutils==0.2.0
jedi==0.15.1
jsonschema==3.1.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
lz4==2.2.1
Markdown==3.1.1
more-itertools==7.2.0
numpy==1.17.3
opencv-python==4.1.1.26
opencv-python-headless==4.1.1.26
opt-einsum==3.1.0
packaging==19.2
pandas==0.25.2
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.2.1
pluggy==0.13.0
prompt-toolkit==2.0.10
protobuf==3.10.0
psutil==5.6.3
ptyprocess==0.6.0
py==1.8.0
py-spy==0.3.0
pyglet==1.3.2
Pygments==2.4.2
pyparsing==2.4.2
pyrsistent==0.15.5
pytest==5.2.2
python-dateutil==2.8.0
pytz==2019.3
PyYAML==5.1.2
ray==0.7.6
redis==3.3.11
requests==2.22.0
scipy==1.3.1
setproctitle==1.1.10
six==1.12.0
tensorboard==2.0.0
tensorflow==2.0.0
tensorflow-estimator==2.0.1
termcolor==1.1.0
tqdm==4.36.1
traitlets==4.3.3
urllib3==1.25.6
wcwidth==0.1.7
Werkzeug==0.16.0
wrapt==1.11.2
zipp==0.6.0
`

**Comment by arunavo4** [comment]
@graciofilipe I think the best way to restore a saved model is to use the `Rollout.py` script that's provided in the library.
You can also customize it according to your needs.

Also, best way to checkpoint is to use the tune parameters

`tune.run(DQNTrainer,
         checkpoint_freq=10,
         checkpoint_at_end=True,
         config={.......})`
