### ISSUE TITLE
 Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True'

### ISSUE THREAD

**Issue by lunasdejavu** [ray-project/ray#6047]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **Ray installed from (source or binary)**: pip
- **Ray version**:0.7.5
- **Python version**:3.6.9
- **Exact command to reproduce**:

### Describe the problem

I am modifying a project which makes the fake license plate and the jsonfiles contains the coordinates of every characters.  the main architecture is very simple ,which just call a class GenPlate_foreign and its member function( genBatch) to generate license plate images and points in a for loop. I use ray in the for loop of genBatch , generate and genPlateString like exercise 2
But I met an error like this:

```
2019-10-30 17:28:09,378 INFO resource_spec.py:205 -- Starting Ray with 7.81 GiB memory available for workers and up to 3.91 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2019-10-30 17:28:11,803 WARNING worker.py:363 -- WARNING: Pickling the class <class 'Font'> failed, so we are using pickle and only registering the class locally.
2019-10-30 17:28:11,821 WARNING worker.py:479 -- WARNING: Serializing the class <class 'GenPlate_foreign.GenPlate_foreign'> failed, falling back to cloudpickle.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 469, in _try_store_and_register
    self.store_and_register(object_id, value)
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 325, in store_and_register
    pyarrow.serialize(value, serialization_context),
  File "pyarrow/serialization.pxi", line 358, in pyarrow.lib.serialize
  File "pyarrow/serialization.pxi", line 150, in pyarrow.lib.SerializationContext._serialize_callback
  File "/usr/local/lib/python3.6/dist-packages/ray/cloudpickle/cloudpickle.py", line 1123, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python3.6/dist-packages/ray/cloudpickle/cloudpickle.py", line 482, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/usr/lib/python3.6/pickle.py", line 496, in save
    rv = reduce(self.proto)
TypeError: can't pickle Font objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "genplate.py", line 122, in <module>
    main()
  File "genplate.py", line 79, in main
    strs, imgs, points = G.genBatch(args.amount, 2, range(31, 65), (720, 480))
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 199, in genBatch
    plateStr_id = self.genPlateString.remote(self,5)
  File "/usr/local/lib/python3.6/dist-packages/ray/remote_function.py", line 85, in _remote_proxy
    return self._remote(args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ray/remote_function.py", line 165, in _remote
    return invocation(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ray/remote_function.py", line 155, in invocation
    resources=resources)
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 657, in submit_task
    args_for_raylet.append(put(arg))
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 2387, in put
    worker.put_object(object_id, value)
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 401, in put_object
    self._try_store_and_register(object_id, value)
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 480, in _try_store_and_register
    self.store_and_register(object_id, value)
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 325, in store_and_register
    pyarrow.serialize(value, serialization_context),
  File "pyarrow/serialization.pxi", line 358, in pyarrow.lib.serialize
  File "pyarrow/serialization.pxi", line 150, in pyarrow.lib.SerializationContext._serialize_callback
  File "/usr/local/lib/python3.6/dist-packages/ray/cloudpickle/cloudpickle.py", line 1123, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python3.6/dist-packages/ray/cloudpickle/cloudpickle.py", line 482, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/usr/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib/python3.6/pickle.py", line 496, in save
    rv = reduce(self.proto)
TypeError: can't pickle Font objects
2019-10-30 17:28:12,037 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,038 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,080 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,091 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,123 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,123 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,165 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,166 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,188 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,199 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,210 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,211 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,274 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,274 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,275 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,275 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,276 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,276 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,297 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,297 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,298 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,308 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,329 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,340 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,352 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,353 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,375 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

2019-10-30 17:28:12,386 WARNING worker.py:1779 -- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 138, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/data/workspace/willy_sung/QQ/gen_fake_plate/GenPlate_foreign.py", line 8, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1436, in init
    raise Exception("Perhaps you called ray.init twice by accident? "
Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

```

### Source code / logs

the code is in two files :
genplate.py
```
import os
import re
from GenPlate_NewVer import *
from GenPlate_OldVer import *
from GenPlate_jun import *
from GenPlate_foreign import *
import matplotlib.pyplot as plt
import argparse
import json
import ray

def str2bool(v):
    if v.lower() in ('yes', 'true', 't', 'y', '1'):
        return True
    elif v.lower() in ('no', 'false', 'f', 'n', '0'):
        return False
    else:
        raise argparse.ArgumentTypeError('Boolean value expected.')
def main():
    parser = argparse.ArgumentParser(description='Use this script to generate plate. EX: python3 genplate.py --amount=20 --output=/data/datasets/fake_plate_font --version=old')
    # parser.add_argument('--model', required=True,
    #                     help='Path to a binary file of model contains trained weights. ')
    parser.add_argument('--amount', type=int, default=40,
                        help='Amount of test data generated. ')
    # parser.add_argument('--input', help='Path to input image or video file. ')
    parser.add_argument('--output', help='Path to output image. ')
    parser.add_argument('--json', type=str2bool, default=False, help='Create the image info. for LabelMe. ')
    parser.add_argument('--show', type=str2bool, default=False, help='Show the images. ')
    parser.add_argument('--version', default='new', help='Plate version. (old, new, jun, foreign)')

    args = parser.parse_args(

    if args.version == 'new':
        G = GenPlate_foreign("/data/workspace/willy_sung/QQ/gen_fake_plate/font/kaiu_plate.ttf", "./font/ChePai_old.ttf", "./road")
        strs, imgs, points = G.genBatch(args.amount, 2, range(31, 65), (720, 480))

```
GenPlate_foreign.py
```
from PIL import Image
from PIL import ImageFont
import os
from common import*
from io import BytesIO
import ray
PLATE_BG_COLOR = [(100, 100, 255), (214, 143, 63), (0, 242, 255)]
ray.init()
class GenPlate_foreign:
    def __init__(self, fontCh_file, fontEng_path_file, NoPlates):
        self.plate_height = 160
        self.plate_width = 380
        self.font_height = 130
        self.font_width = 50
        self.ch_font_height = 120
        self.ch_font_width = 100

        self.dash_size = (10, 10)
        self.text_component = (1, 4)
        with open(fontCh_file, "rb") as f:
            font_bytes = BytesIO(f.read())
        self.fontC = ImageFont.truetype(font_bytes, 120, 0)
        with open(fontEng_path_file, "rb") as f1:
            font_bytes = BytesIO(f1.read())
        self.fontE = ImageFont.truetype(font_bytes, 120, 0)
        # self.fontC = ImageFont.truetype(fontCh_file, 120, 0)
        # self.fontE = ImageFont.truetype(fontEng_path_file, 120, 0)

        # below value will be updated in generate()
        self.bg_type = -1
        self.bg_color = (-1, -1, -1)
        self.ft_color = (-1, -1, -1)

        # load all background image
        bg_path = "./images/foreign.bmp"
        img = cv2.imread(bg_path)
        self.scale_size = (img.shape[1] / self.plate_width, img.shape[0] / self.plate_height)
        img = cv2.resize(img, (self.plate_width, self.plate_height))
        self.bgs = img

        self.smu = cv2.imread("./images/smu2.jpg")
        self.noplates_path = []
        for parent, parent_folder, filenames in os.walk(NoPlates):
            for filename in filenames:
                path = parent + "/" + filename
                self.noplates_path.append(path)

    def GenCh_(self, f, val, color, font_width, font_height):
        img = Image.new("RGB", (130, 130), (255, 255, 255))
        draw = ImageDraw.Draw(img)
        draw.text((0, 0), val, color, font=f)
        # cv2.imshow("ch", np.array(img))
        # cv2.waitKey(0)
        img = img.resize((font_width, font_height))
        A = np.array(img)
        # cv2.imshow("ch", A)
        return A

    def draw(self, val):
        img = np.array(Image.new("RGB", (self.plate_width, self.plate_height), (255, 255, 255)))

        color = COLOR_TYPE['black']

        str_length = len(val)

        gap = 15  # diatance between top and font
        base = 15
        font_gap = 0

        seg_front = self.text_component[0]
        seg_rear = self.text_component[1]

        points = []
        # eng font
        for i in range(seg_front):
            img[gap + 7:gap + 7 + self.ch_font_height, base:base + self.ch_font_width] = self.GenCh_(self.fontC, val[i], color, self.ch_font_width, self.ch_font_height)
            
            points.append([(base, gap),
                           (base + self.font_width, gap),
                           (base + self.font_width, gap + self.font_height),
                           (base, gap + self.font_height)])
            base += self.font_width + font_gap

            # cv2.imshow("1", img)
            # cv2.waitKey(0)

        # num font
        base += 90  # shift bacause the '-'
        for i in range(seg_rear):
            img[gap:gap + self.font_height, base:base + self.font_width] = GenEng(self.fontE, val[i + seg_front], color, self.font_width, self.font_height)
            points.append([(base, gap),
                           (base + self.font_width, gap),
                           (base + self.font_width, gap + self.font_height),
                           (base, gap + self.font_height)])
            base += self.font_width + font_gap

            # cv2.imshow("1", img)
            # cv2.waitKey(0)

        # img = (255 - img)  # inverse

        # ttt = np.copy(img)
        # for j in range(len(points)):
        #     ttt = draw_points(ttt, points[j])
        # cv2.imshow('img', img)
        # cv2.waitKey(0)
        return img, points

    def genBackground(self):
        bg = np.copy(self.bgs)
        bg[np.where((bg == [100, 100, 255]).all(axis=2))] = self.bg_color
        return bg
    @ray.remote
    def generate(self, text, img_size):
        self.bg_color = PLATE_BG_COLOR[r(3)]
        self.ft_color = (255, 255, 255)
        # print(self.bg_type, BG_FT_TYPE[self.bg_type], self.bg_color, self.ft_color)

        fg, points = self.draw(text)
        # cv2.imshow("fg", fg)
        # cv2.waitKey(0)
        bg = self.genBackground()
        # cv2.imshow("bg", bg)
        # cv2.waitKey(0)
        com = cv2.bitwise_and(fg, bg)


        # cv2.imshow("r", com)
        # cv2.waitKey(0)
        com, points = rot(com, r(60) - 30, com.shape, 30, points)
        com, points = rotRandrom(com, 10, (com.shape[1], com.shape[0]), points)
        com, points = random_position(com, points)

        # random add 
        #if r(2) is 1:
        #    com = AddSmudginess(com, self.smu)

        com = tfactor(com)
        com, points = random_envirment(com, self.noplates_path, points)
        com = AddGauss(com, 1 + r(2))
        com = addNoise(com)

        # show points
        # ttt = np.copy(com)
        # for i in range(len(points)):
        #     ttt = draw_points(ttt, points[i], 'line')
        # cv2.imshow('ttt', ttt)
        # cv2.waitKey(0)

        # cv2.imshow("r", com)
        # cv2.waitKey(0)
        img2, new_points = Resize(com, points, img_size)

        return img2, new_points
    @ray.remote
    def genPlateString(self, val):
        plateStr = ""
        seg_front = self.text_component[0]

        for cpos in range(val):
            if cpos == 0:
                plateStr += chars[35 + r(2)]
            else:
                plateStr += chars[r(10)]  # number

        return plateStr
    

    def Resize(img, img_size):
        scale_size = (img.shape[1] / img_size[0], img.shape[0] / img_size[1])
        img2 = cv2.resize(img, img_size)
        new_points = []
        for strs in points:
            pt_tmp = []
            for pt in strs:
                x = int(pt[0] / scale_size[0])
                if x > img.shape[1]:
                    x = img.shape[1]
                elif x < 0:
                    x = 0
                y = int(pt[1] / scale_size[1])
                if y > img.shape[0]:
                    y = img.shape[0]
                elif y < 0:
                    y = 0
                pt_tmp.append((x, y))
            new_points.append(pt_tmp)
        return img2, new_points

    # img_size is (w, h)
    def genBatch(self, batchSize, pos, charRange, img_size, text_len=-1, transpose=False, color_code='BGR'):
        plateStrs = []
        plateImgs = []
        platePoints = []
        plateStrs_ids = []
        plateImg_ids = []
        platePoints_ids = []
        for i in range(batchSize):
            plateStr_id = self.genPlateString.remote(self,5)
            img_id, points_id = self.generate.remote(self,plateStr, img_size)

            # if transpose is True:
            #     img = img.transpose(1, 0, 2)

            # if color_code is 'GRAY':
            #     img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
            # elif color_code is 'RGB':
            #     img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

            # filename = os.path.join(outputPath, plateStr + ".jpg")
            plateImg_ids.append(img_id)
            plateStrs_ids.append(plateStr_id)
            platePoints_ids.append(points_id)
            # print(filename)
            # cv2.imwrite(filename, img)
            # cv2.imshow(plateStr, img)
            # cv2.waitKey(0)
        plateStrs = ray.get(plateStrs_ids)
        plateImgs = ray.get(plateImg_ids)
        platePoints = ray.get(platePoints_ids)
        return plateStrs, plateImgs, platePoints
```

**Comment by datalee** [comment]
me too？how to solve？
