### ISSUE TITLE
[tune] Unable to get mnist_pytorch.py example working on multigpu

### ISSUE THREAD

**Issue by samarth-b** [ray-project/ray#6064]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux 
- **Ray installed from (source or binary)**:  binary
- **Ray version**: 0.7.6
- **Python version**: 3.5.2
- **Exact command to reproduce**: python mnist_pytorch.py --cuda 1

I am trying to run the mnist_pytorch.py example in multi-gpu setting, where CUDA_VISIBLE_DEVICES=0,1,2,3. Through the documentation says ray automatically checks available gpus, it always double allocates. All jobs exit with:

`RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable`

### Source code / logs
python mnist_pytorch.py --cuda 1 (no changes to code)

How can I ensure that the scheduler utilizes all the available resources?

**Comment by richardliaw** [comment]
Can you provide some output or logs?

**Comment by samarth-b** [comment]
Sure. Please see below:

context: 
`$echo $CUDA_VISIBLE_DEVICES`
`5,2,6,3`

torch.__version__ == 1.0.1post2

> cat  /u/samarthb/ray_results/exp/train_mnist_4_lr=3.0949e-07,momentum=0.8314_2019-11-01_09-58-25qyi54edw/error_2019-11-01_09-58-28.txt
Traceback (most recent call last):
  File "/u/samarthb/py3/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 515, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/u/samarthb/py3/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 351, in fetch_result
    result = ray.get(trial_future[0])
  File "/u/samarthb/py3/lib/python3.5/site-packages/ray/worker.py", line 2121, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): ray_WrappedTrackFunc:train() (pid=7767, host=dccxc271)
  File "/u/samarthb/py3/lib/python3.5/site-packages/ray/tune/trainable.py", line 176, in train
    result = self._train()
  File "/u/samarthb/py3/lib/python3.5/site-packages/ray/tune/function_runner.py", line 199, in _train
    self._report_thread_runner_error(block=True)
  File "/u/samarthb/py3/lib/python3.5/site-packages/ray/tune/function_runner.py", line 242, in _report_thread_runner_error
    .format(err_tb_str)))
ray.tune.error.TuneError: Trial raised an exception. Traceback:
ray_WrappedTrackFunc:train() (pid=7767, host=dccxc271)
  File "/u/samarthb/py3/lib/python3.5/site-packages/ray/tune/function_runner.py", line 97, in run
    self._entrypoint()
  File "/u/samarthb/py3/lib/python3.5/site-packages/ray/tune/function_runner.py", line 145, in entrypoint
    return self._trainable_func(config, self._status_reporter)
  File "/u/samarthb/py3/lib/python3.5/site-packages/ray/tune/function_runner.py", line 271, in _trainable_func
    output = train_func(config)
  File "mnist_pytorch.py", line 103, in train_mnist
    model = ConvNet().to(device)
  File "/u/samarthb/py3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/u/samarthb/py3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/u/samarthb/py3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/u/samarthb/py3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 379, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable

**Comment by richardliaw** [comment]
Thanks! What is “device”?

**Comment by samarth-b** [comment]
here is the full error log: https://gist.github.com/samarth-b/7a408ee6c9ba7ecaf4de13806243054c
the script is exactly same as: https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mnist_pytorch.py

my changes was just changed --cuda to default True
`device = torch.device("cuda" if use_cuda else "cpu")`
I also tried `device = torch.device("cuda:0" if use_cuda else "cpu")` 

Thanks a lot for your help.

**Comment by richardliaw** [comment]
What version of PyTorch are you on? It looks like the issue is that PyTorch is leaving some zombie process state when the process is terminated. 

One fix is to catch the runtime error from `ConvNet().to(device)`, sleep for 5 seconds, and retry.

**Comment by richardliaw** [comment]
Maybe this is related? https://github.com/pytorch/pytorch/issues/22259

**Comment by samarth-b** [comment]
> What version of PyTorch are you on? It looks like the issue is that PyTorch is leaving some zombie process state when the process is terminated.

pytorch version 1.0.1post2, what do you recommend?

> I haven't seen this happen in a couple of years.

:(

> One fix is to catch the runtime error from `ConvNet().to(device)`, sleep for 5 seconds, and retry. The other fix may be simply to update PyTorch.

Adding sleep didnt help. `nvidia-smi` shows ghost processes of `ray_WrappedTrackFunc:__ray_terminate__()` that didnt get terminated. Will try with upgraded pytorch.

> Maybe this is related? pytorch/pytorch#22259
Mostly likely yes, will upgrade nvidia drivers and pytorch to check.

**Comment by richardliaw** [comment]
OK let me know; I've been on pytorch 1.2.

**Comment by samarth-b** [comment]
It works on pytorch 1.3.0.

**Comment by richardliaw** [comment]
Thanks! Can you close if this is resolved?
