### ISSUE TITLE
DQN type mismatch in QLoss.__init__ when eager == True and num_atoms > 1

### ISSUE THREAD

**Issue by carlbalmer** [ray-project/ray#6081]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.3 LTS
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.6
- **Python version**: 3.7.4
- **Exact command to reproduce**:
```
from ray import tune
from ray.rllib.agents.dqn import DQNTrainer

tune.run(DQNTrainer, config={
    "env": "CartPole-v0",
    "num_atoms": 51,
    "eager": True
})
```
### Describe the problem
The `weights` in `train_batch` are of type `float64` instead of `float32`.
Im not sure where you would need to change this? In the replay memory? or in the SymcReplayOptimizer?

### Source code / logs
```
2019-11-04 12:48:59,830	ERROR trial_runner.py:569 -- Error processing event.
Traceback (most recent call last):
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 515, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 351, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/ray/worker.py", line 2121, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(InvalidArgumentError): ray_DQN:train() (pid=18924, host=carl-1070)
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 421, in train
    raise e
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 407, in train
    result = Trainable.train(self)
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/ray/tune/trainable.py", line 176, in train
    result = self._train()
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 129, in _train
    fetches = self.optimizer.step()
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/optimizers/sync_replay_optimizer.py", line 142, in step
    self._optimize()
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/optimizers/sync_replay_optimizer.py", line 170, in _optimize
    info_dict = self.workers.local_worker().learn_on_batch(samples)
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 607, in learn_on_batch
    info_out[pid] = policy.learn_on_batch(batch)
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/policy/eager_tf_policy.py", line 60, in _func
    return func(*args, **kwargs)
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/policy/eager_tf_policy.py", line 68, in _func
    out = func(*args, **kwargs)
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/policy/eager_tf_policy.py", line 274, in learn_on_batch
    grads_and_vars, stats = self._compute_gradients(samples)
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/policy/eager_tf_policy.py", line 401, in _compute_gradients
    loss = loss_fn(self, self.model, self.dist_class, samples)
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/agents/dqn/dqn_policy.py", line 352, in build_q_losses
    config["num_atoms"], config["v_min"], config["v_max"])
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/agents/dqn/dqn_policy.py", line 85, in __init__
    self.loss = tf.reduce_mean(self.td_error * importance_weights)
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 899, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 1206, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 6698, in mul
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:Mul] name: mul/
```

**Comment by ericl** [comment]
Seems like we might need some cast operation in eager mode. Do you want to try fixing it?

**Comment by carlbalmer** [comment]
Sure! Do you have some pointers on where this could be caused? Im currently looking at `build_eager_tf_policy()` & `_initialize_loss_with_dummy_batch()`

**Comment by ericl** [comment]
I think you can start with 
```
  File "/home/carl/miniconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/agents/dqn/dqn_policy.py", line 85, in __init__
    self.loss = tf.reduce_mean(self.td_error * importance_weights)
```

and perhaps trace back to see where the float64 comes from and do the cast early. It could be originating from some place in dummy loss init as you point out.
