### ISSUE TITLE
Asynchronously launching Ray job without blocking via ray.get or ray.wait fails

### ISSUE THREAD

**Issue by hokiegeek2** [ray-project/ray#6083]
### System information
- **OS Platform and Distribution (Linux Ubuntu 16.04)**:
- **Ray installed from (binary)**:
- **Ray version**: 0.7.5
- **Python version**: 3.6.4
- **Exact command to reproduce**:

### Describe the problem
When I wait for the result to be returned from Ray within the calling Python thread (code within the if self.wait block below) I get the expected result.

```
            '''
            If wait is true, wait and loop until a return value is available. If wait is 
            false, simply return the ObjectID for later retrieval
            '''
            if self.wait:
                results = ray.get(execId)
                while results is None:
                    self.logger.debug('Waiting for execute result, pausing 5 seconds')
                    time.sleep(5)
                    results = ray.get(execId)
                return results
            else:
                self.logger.debug('Not waiting, returning the execId {}'.format(execId)
                return execId
```
If, however, I set self.wait to False and therefore return the ObjectID and attempt to retrieve the result of the analytic from another Python process, it fails every time with the following message:

```
[RayArrowParams] Line 352 DEBUG: Initializing ray client with rayAddress: localhost:6379
[RayLauncher] Line 198 DEBUG: Opened connection to Ray server
[RayLauncher] Line 231 DEBUG: ObjectID ObjectID(bafdde0f38efeed78be90400000000c001000000) registered in Plasma Object Store
[RayLauncher] Line 245 DEBUG: Not waiting, returning the execId ObjectID(bafdde0f38efeed78be90400000000c001000000)
[RayLauncher] Line 368 DEBUG: Closed connection to the remote Ray server
[RayLauncher] Line 198 DEBUG: Opened connection to Ray server
2019-11-04 11:35:58,669	WARNING worker.py:416 -- Local object store memory usage:
num clients with quota: 0
quota map size: 0
pinned quota map size: 0
allocated bytes: 243429
allocation limit: 500000000
pinned bytes: 0
(global lru) capacity: 500000000
(global lru) used: 0.0486858%
(global lru) num objects: 4
(global lru) num evictions: 0
(global lru) bytes evicted: 0

[RayLauncher] Line 368 DEBUG: Closed connection to the remote Ray server
```
In addition, the following error is thrown, indicating that the Ray task is never scheduled. This would explain why I am getting the above error:
```
Backend MacOSX is interactive backend. Turning interactive mode on.
[2m[36m(pid=10763)[0m Traceback (most recent call last):
[2m[36m(pid=10763)[0m   File "/Users/hokiegeek2/miniconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 98, in <module>
[2m[36m(pid=10763)[0m     ray.worker.global_worker.main_loop()
[2m[36m(pid=10763)[0m   File "/Users/hokiegeek2/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1118, in main_loop
[2m[36m(pid=10763)[0m     task = self._get_next_task_from_raylet()
[2m[36m(pid=10763)[0m   File "/Users/hokiegeek2/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1101, in _get_next_task_from_raylet
[2m[36m(pid=10763)[0m     task = self.raylet_client.get_task()
[2m[36m(pid=10763)[0m   File "python/ray/_raylet.pyx", line 291, in ray._raylet.RayletClient.get_task
[2m[36m(pid=10763)[0m   File "python/ray/_raylet.pyx", line 98, in ray._raylet.check_status
[2m[36m(pid=10763)[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Raylet connection closed.
[2m[36m(pid=10763)[0m 
[2m[36m(pid=10763)[0m During handling of the above exception, another exception occurred:
[2m[36m(pid=10763)[0m 
[2m[36m(pid=10763)[0m Traceback (most recent call last):
[2m[36m(pid=10763)[0m   File "/Users/hokiegeek2/miniconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 105, in <module>
[2m[36m(pid=10763)[0m     job_id=None)
[2m[36m(pid=10763)[0m   File "/Users/hokiegeek2/miniconda3/lib/python3.7/site-packages/ray/utils.py", line 67, in push_error_to_driver
[2m[36m(pid=10763)[0m     worker.raylet_client.push_error(job_id, error_type, message, time.time())
[2m[36m(pid=10763)[0m   File "python/ray/_raylet.pyx", line 327, in ray._raylet.RayletClient.push_error
[2m[36m(pid=10763)[0m   File "python/ray/_raylet.pyx", line 98, in ray._raylet.check_status
[2m[36m(pid=10763)[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Connection closed unexpectedly.
[2m[36m(pid=10762)[0m Traceback (most recent call last):
[2m[36m(pid=10762)[0m   File "/Users/hokiegeek2/miniconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 98, in <module>
[2m[36m(pid=10762)[0m     ray.worker.global_worker.main_loop()
[2m[36m(pid=10762)[0m   File "/Users/hokiegeek2/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1118, in main_loop
[2m[36m(pid=10762)[0m     task = self._get_next_task_from_raylet()
[2m[36m(pid=10762)[0m   File "/Users/hokiegeek2/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1101, in _get_next_task_from_raylet
[2m[36m(pid=10762)[0m     task = self.raylet_client.get_task()
[2m[36m(pid=10762)[0m   File "python/ray/_raylet.pyx", line 291, in ray._raylet.RayletClient.get_task
[2m[36m(pid=10762)[0m   File "python/ray/_raylet.pyx", line 98, in ray._raylet.check_status
[2m[36m(pid=10762)[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Raylet connection closed.
[2m[36m(pid=10762)[0m 
[2m[36m(pid=10762)[0m During handling of the above exception, another exception occurred:
[2m[36m(pid=10762)[0m 
[2m[36m(pid=10762)[0m Traceback (most recent call last):
[2m[36m(pid=10762)[0m   File "/Users/hokiegeek2/miniconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 105, in <module>
[2m[36m(pid=10762)[0m     job_id=None)
[2m[36m(pid=10762)[0m   File "/Users/hokiegeek2/miniconda3/lib/python3.7/site-packages/ray/utils.py", line 67, in push_error_to_driver
[2m[36m(pid=10762)[0m     worker.raylet_client.push_error(job_id, error_type, message, time.time())
[2m[36m(pid=10762)[0m   File "python/ray/_raylet.pyx", line 327, in ray._raylet.RayletClient.push_error
[2m[36m(pid=10762)[0m   File "python/ray/_raylet.pyx", line 98, in ray._raylet.check_status
[2m[36m(pid=10762)[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Connection closed unexpectedly.
[2m[36m(pid=10761)[0m Traceback (most recent call last):
[2m[36m(pid=10761)[0m   File "/Users/hokiegeek2/miniconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 98, in <module>
[2m[36m(pid=10761)[0m     ray.worker.global_worker.main_loop()
[2m[36m(pid=10761)[0m   File "/Users/hokiegeek2/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1118, in main_loop
[2m[36m(pid=10761)[0m     task = self._get_next_task_from_raylet()
[2m[36m(pid=10761)[0m   File "/Users/hokiegeek2/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1101, in _get_next_task_from_raylet
[2m[36m(pid=10761)[0m     task = self.raylet_client.get_task()
[2m[36m(pid=10761)[0m   File "python/ray/_raylet.pyx", line 291, in ray._raylet.RayletClient.get_task
[2m[36m(pid=10761)[0m   File "python/ray/_raylet.pyx", line 98, in ray._raylet.check_status
[2m[36m(pid=10761)[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Raylet connection closed.
[2m[36m(pid=10761)[0m 
[2m[36m(pid=10761)[0m During handling of the above exception, another exception occurred:
[2m[36m(pid=10761)[0m 
[2m[36m(pid=10761)[0m Traceback (most recent call last):
[2m[36m(pid=10761)[0m   File "/Users/hokiegeek2/miniconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 105, in <module>
[2m[36m(pid=10761)[0m     job_id=None)
[2m[36m(pid=10761)[0m   File "/Users/hokiegeek2/miniconda3/lib/python3.7/site-packages/ray/utils.py", line 67, in push_error_to_driver
[2m[36m(pid=10761)[0m     worker.raylet_client.push_error(job_id, error_type, message, time.time())
[2m[36m(pid=10761)[0m   File "python/ray/_raylet.pyx", line 327, in ray._raylet.RayletClient.push_error
[2m[36m(pid=10761)[0m   File "python/ray/_raylet.pyx", line 98, in ray._raylet.check_status
[2m[36m(pid=10761)[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Connection closed unexpectedly.
2019-11-04 12:33:11,304	ERROR worker.py:1781 -- listen_error_messages_raylet: Connection closed by server.
2019-11-04 12:33:11,305	ERROR import_thread.py:89 -- ImportThread: Connection closed by server.
2019-11-04 12:33:11,305	ERROR worker.py:1681 -- print_logs: Connection closed by server.
```
Is it possible to pass the ObjectID to another process and retrieve from Ray? More specifically, is it possible to do a "fire and forget until later" remote method invocation where the code is not blocking?

**Comment by ericl** [comment]
By default all the tasks of a job should be killed when the driver exits. If you want to share tasks across drivers I think it can be done by running the tasks from a detached actor (not 100% sure it will work): https://ray.readthedocs.io/en/latest/advanced.html#detached-actors

Might be easier to instead run your entire workflow inside a single job.

**Comment by hokiegeek2** [comment]
> By default all the tasks of a job should be killed when the driver exits. If you want to share tasks across drivers I think it can be done by running the tasks from a detached actor (not 100% sure it will work): https://ray.readthedocs.io/en/latest/advanced.html#detached-actors
> 
> Might be easier to instead run your entire workflow inside a single job.

Cool, yeah, makes sense, this is pretty much what I need, will give it a shot--thanks!
