### ISSUE TITLE
Apex crashes with custom Env

### ISSUE THREAD

**Issue by arunavo4** [ray-project/ray#6124]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.8.0.dev6
- **Python version**: 3.6.8 
- **Exact command to reproduce**: Source code provided below.

### Describe the problem

Ray workers crash soon after executing the first iter. 

The contents of the error file dumped by ray.
```
`Traceback (most recent call last):
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 438, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 354, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/worker.py", line 1950, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: [36mray_APEX:train()[39m (pid=6711, ip=192.168.1.35)
  File "python/ray/_raylet.pyx", line 581, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 563, in ray._raylet.execute_task.function_executor
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 418, in train
    raise e
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 407, in train
    result = Trainable.train(self)
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 176, in train
    result = self._train()
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 129, in _train
    fetches = self.optimizer.step()
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/rllib/optimizers/async_replay_optimizer.py", line 142, in step
    sample_timesteps, train_timesteps = self._step()
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/rllib/optimizers/async_replay_optimizer.py", line 245, in _step
    samples = ray_get_and_free(replay)
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/rllib/utils/memory.py", line 33, in ray_get_and_free
    result = ray.get(object_ids)
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.`
```

### Source code / logs

Source file: `apex.py`

```
from collections import deque

import gym
import numpy as np
from gym.spaces import Discrete, Box

import ray
from ray import tune
from ray.rllib.agents.dqn import ApexTrainer
from ray.rllib.models import ModelCatalog
from ray.rllib.agents.dqn.distributional_q_model import DistributionalQModel
from ray.rllib.models.tf.visionnet_v1 import _get_filter_config
from ray.rllib.models.tf.misc import normc_initializer, get_activation_fn
from ray.rllib.utils import try_import_tf

tf = try_import_tf()

class SimpleEnv(gym.Env):

    def __init__(self, config):
        self.k = 4
        self.frames = deque([], maxlen=self.k)
        self.action_space = Discrete(3)
        self.observation_space = Box(low=0, high=255, shape=(84, 84, self.k),
                                     dtype=np.uint8)

    def reset(self):
        ob = np.ones([84, 84], dtype=np.uint8)
        for _ in range(self.k):
            self.frames.append(ob)
        return self._get_ob()

    def _get_ob(self):
        assert len(self.frames) == self.k
        obs = np.ones([84, 84, 4], dtype=np.uint8)
        for i in range(4):
            obs[:, :, i] = self.frames[i]
        return obs

    def step(self, action):
        assert action in [0, 1, 2], action
        if action == 0:
            reward = 0
        elif action == 1:
            reward = 0.5
        elif action == 2:
            reward = 1
        else:
            reward = -1
        done = True if reward == 2 else False
        return self._get_ob(), reward, done, {}


# ============== Nature CNN Model ==================

class VisionNetwork(DistributionalQModel):
    """Generic vision network implemented in DistributionalQModel API."""

    def __init__(self, obs_space, action_space, num_outputs, model_config,
                 name, **kw):
        super(VisionNetwork, self).__init__(
            obs_space, action_space, num_outputs, model_config, name, **kw)

        activation = get_activation_fn(model_config.get("conv_activation"))
        filters = model_config.get("conv_filters")
        if not filters:
            filters = _get_filter_config(obs_space.shape)
        no_final_linear = model_config.get("no_final_linear")
        vf_share_layers = model_config.get("vf_share_layers")

        inputs = tf.keras.layers.Input(
            shape=obs_space.shape, name="observations")
        last_layer = inputs

        # Build the action layers
        for i, (out_size, kernel, stride) in enumerate(filters[:-1], 1):
            last_layer = tf.keras.layers.Conv2D(
                out_size,
                kernel,
                strides=(stride, stride),
                activation=activation,
                padding="same",
                name="conv{}".format(i))(last_layer)
        out_size, kernel, stride = filters[-1]
        if no_final_linear:
            # the last layer is adjusted to be of size num_outputs
            last_layer = tf.keras.layers.Conv2D(
                num_outputs,
                kernel,
                strides=(stride, stride),
                activation=activation,
                padding="valid",
                name="conv_out")(last_layer)
            conv_out = last_layer
        else:
            last_layer = tf.keras.layers.Conv2D(
                out_size,
                kernel,
                strides=(stride, stride),
                activation=activation,
                padding="valid",
                name="conv{}".format(i + 1))(last_layer)
            conv_out = tf.keras.layers.Conv2D(
                num_outputs, [1, 1],
                activation=None,
                padding="same",
                name="conv_out")(last_layer)

        # Build the value layers
        if vf_share_layers:
            last_layer = tf.keras.layers.Lambda(
                lambda x: tf.squeeze(x, axis=[1, 2]))(last_layer)
            value_out = tf.keras.layers.Dense(
                1,
                name="value_out",
                activation=None,
                kernel_initializer=normc_initializer(0.01))(last_layer)
        else:
            # build a parallel set of hidden layers for the value net
            last_layer = inputs
            for i, (out_size, kernel, stride) in enumerate(filters[:-1], 1):
                last_layer = tf.keras.layers.Conv2D(
                    out_size,
                    kernel,
                    strides=(stride, stride),
                    activation=activation,
                    padding="same",
                    name="conv_value_{}".format(i))(last_layer)
            out_size, kernel, stride = filters[-1]
            last_layer = tf.keras.layers.Conv2D(
                out_size,
                kernel,
                strides=(stride, stride),
                activation=activation,
                padding="valid",
                name="conv_value_{}".format(i + 1))(last_layer)
            last_layer = tf.keras.layers.Conv2D(
                1, [1, 1],
                activation=None,
                padding="same",
                name="conv_value_out")(last_layer)
            value_out = tf.keras.layers.Lambda(
                lambda x: tf.squeeze(x, axis=[1, 2]))(last_layer)

        self.base_model = tf.keras.Model(inputs, [conv_out, value_out])
        self.register_variables(self.base_model.variables)

    def forward(self, input_dict, state, seq_lens):
        # explicit cast to float32 needed in eager
        model_out, self._value_out = self.base_model(
            tf.cast(input_dict["obs"], tf.float32))
        return tf.squeeze(model_out, axis=[1, 2]), state

    def value_function(self):
        return tf.reshape(self._value_out, [-1])


ModelCatalog.register_custom_model("NatureCNN", VisionNetwork)

ray.init(memory=10000000000,
         object_store_memory=5000000000,
         redis_max_memory=2000000000,
         driver_object_store_memory=2000000000)

tune.run(ApexTrainer,
         checkpoint_freq=10,  # iterations
         checkpoint_at_end=True,
         config={"env": SimpleEnv,
                 "model": {
                     "custom_model": "NatureCNN"
                 },
                 "double_q": False,
                 "dueling": False,
                 "num_atoms": 1,
                 "noisy": False,
                 "n_step": 3,
                 "lr": .0001,
                 "adam_epsilon": .00015,
                 "hiddens": [512],
                 "buffer_size": 1000000,
                 "schedule_max_timesteps": 2000000,
                 "exploration_final_eps": 0.01,
                 "exploration_fraction": .1,
                 "prioritized_replay_alpha": 0.5,
                 "beta_annealing_fraction": 1.0,
                 "final_prioritized_replay_beta": 1.0,
                 "num_gpus": 0,
                 "num_workers": 4,
                 "num_envs_per_worker": 4,
                 "sample_batch_size": 20,
                 "train_batch_size": 512,
                 "per_worker_exploration": True,
                 "worker_side_prioritization": True,
                 "target_network_update_freq": 50000,
                 "timesteps_per_iteration": 25000,
                 "env_config": {
                     "enable_env_logging": False,
                     "look_back_window_size": 375 * 10,
                     "observation_window": 84,
                     "frame_stack_size": 4,
                 },
                 })  # "eager": True for eager execution

```

**Comment by arunavo4** [comment]
Also, I can confirm that the same Env works with DQN and Rainbow DQN parameters.

**Comment by ericl** [comment]
I got up to iteration 5 with no signs of crashing:
```
== Status ==
Memory usage on this node: 13.7/15.4 GiB
Using FIFO scheduling algorithm.
Resources requested: 5/8 CPUs, 0/0 GPUs, 0.0/9.28 GiB heap, 0.0/3.17 GiB objects
Number of trials: 1 ({'RUNNING': 1})
Result logdir: /home/eric/ray_results/APEX
+-------------------------+----------+-----------+--------+------------------+-------------+----------+
| Trial name              | status   | loc       |   iter |   total time (s) |   timesteps |   reward |
|-------------------------+----------+-----------+--------+------------------+-------------+----------|
| APEX_SimpleEnv_b8011850 | RUNNING  | pid=10356 |      5 |          154.839 |      135920 |      nan |
+-------------------------+----------+-----------+--------+------------------+-------------+----------+
```

It could be a system specific issue like not enough memory. Check the logs dir to see if you can figure out why the actor crashed?

**Comment by arunavo4** [comment]
Ok i will look more into it but i have 32 GB of ram and 12 cores avail. So i don't think that's a problem

**Comment by arunavo4** [comment]
@ericl I tried all other variations of RL Algos from DQN to IMPALA and Apex, and whenever I Try to use more than One worker this similar worker failure problem starts to show up, sometimes I can go 100k steps or 500k and then there  is a worker failure sometimes it happens at 10k, I have a Custom Env that takes about 83 ms to get the next observation. Can that be a problem? I can't figure it out. The only thing I have figured out is that it happens only in multiple worker's scenario.

Here is the Error that appears:
```
`2019-11-13 13:38:23,481	WARNING worker.py:1382 -- A worker died or was killed while executing task afaa80d1842e2524966b01000000.
2019-11-13 13:38:23,682	ERROR trial_runner.py:492 -- Error processing event.
Traceback (most recent call last):
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 438, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 354, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/worker.py", line 1950, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray_DQN:train() (pid=2747, ip=192.168.1.34)
  File "python/ray/_raylet.pyx", line 581, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 563, in ray._raylet.execute_task.function_executor
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 418, in train
    raise e
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 407, in train
    result = Trainable.train(self)
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 176, in train
    result = self._train()
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 129, in _train
    fetches = self.optimizer.step()
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/rllib/optimizers/sync_replay_optimizer.py", line 120, in step
    for e in self.workers.remote_workers()
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/rllib/utils/memory.py", line 33, in ray_get_and_free
    result = ray.get(object_ids)
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
2019-11-13 13:38:23,686	INFO trial_runner.py:538 -- Attempting to recover trial state from last checkpoint.
(pid=2747) 2019-11-13 13:38:23,679	INFO trainer.py:415 -- Worker crashed during call to train(). To attempt to continue training without the failed worker, set `'ignore_worker_failures': True`.
(pid=2740) 2019-11-13 13:38:23,710	INFO trainer.py:345 -- Tip: set 'eager': true or the --eager flag to enable TensorFlow eager execution
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Error in sys.excepthook:
(pid=2747) Traceback (most recent call last):
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=2747)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
(pid=2747) TypeError: 'NoneType' object is not callable
(pid=2747) 
(pid=2747) Original exception was:
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2747) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2747) AttributeError: 'NoneType' object has no attribute 'worker'
2019-11-13 13:38:28,751	WARNING util.py:133 -- The `get_current_ip` operation took 5.048964977264404 seconds to complete, which may be a performance bottleneck.
(pid=2740) 2019-11-13 13:38:28,718	INFO rollout_worker.py:768 -- Built policy map: {'default_policy': <ray.rllib.policy.tf_policy_template.DQNTFPolicy object at 0x7ef89e3f98d0>}
(pid=2740) 2019-11-13 13:38:28,718	INFO rollout_worker.py:769 -- Built preprocessor map: {'default_policy': <ray.rllib.models.preprocessors.NoPreprocessor object at 0x7ef89e3f9860>}
(pid=2740) 2019-11-13 13:38:28,718	INFO rollout_worker.py:370 -- Built filter map: {'default_policy': <ray.rllib.utils.filter.NoFilter object at 0x7ef89e476860>}
(pid=2740) 2019-11-13 13:38:28,749	WARNING trainable.py:131 -- Getting current IP.
2019-11-13 13:38:28,851	WARNING util.py:133 -- The `process_trial` operation took 5.169489860534668 seconds to complete, which may be a performance bottleneck.
`
```

**Comment by arunavo4** [comment]
What is the max time that the main thread can wait for a worker to respond? before it considers it a failure?

```
`(pid=2740) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2740) Exception ignored in: 'ray._raylet.ObjectID.__dealloc__'
(pid=2740) AttributeError: 'NoneType' object has no attribute 'worker'
(pid=2750) 2019-11-13 13:43:55,339	INFO rollout_worker.py:768 -- Built policy map: {'default_policy': <ray.rllib.policy.tf_policy_template.DQNTFPolicy object at 0x7ef89e3fa940>}
(pid=2750) 2019-11-13 13:43:55,339	INFO rollout_worker.py:769 -- Built preprocessor map: {'default_policy': <ray.rllib.models.preprocessors.NoPreprocessor object at 0x7ef89e3fa898>}
(pid=2750) 2019-11-13 13:43:55,339	INFO rollout_worker.py:370 -- Built filter map: {'default_policy': <ray.rllib.utils.filter.NoFilter object at 0x7ef89e3fa748>}
2019-11-13 13:43:55,369	WARNING util.py:133 -- The `get_current_ip` operation took 5.216813802719116 seconds to complete, which may be a performance bottleneck.
(pid=2750) 2019-11-13 13:43:55,369	WARNING trainable.py:131 -- Getting current IP.
2019-11-13 13:43:55,591	WARNING util.py:133 -- The `process_trial` operation took 5.45711874961853 seconds to complete, which may be a performance bottleneck.
`
```

**Comment by arunavo4** [comment]
Now I even cannot run Single process DQN, The crashes are pretty random, all mostly resulting in this error:

```
`2019-11-13 21:31:17,773	WARNING util.py:133 -- The `get_current_ip` operation took 70.26138949394226 seconds to complete, which may be a performance bottleneck.
(pid=2982) 2019-11-13 21:31:17,770	INFO rollout_worker.py:768 -- Built policy map: {'default_policy': <ray.rllib.policy.tf_policy_template.DQNTFPolicy object at 0x7ef9bbd98be0>}
(pid=2982) 2019-11-13 21:31:17,771	INFO rollout_worker.py:769 -- Built preprocessor map: {'default_policy': <ray.rllib.models.preprocessors.NoPreprocessor object at 0x7ef9bbd98b38>}
(pid=2982) 2019-11-13 21:31:17,771	INFO rollout_worker.py:370 -- Built filter map: {'default_policy': <ray.rllib.utils.filter.NoFilter object at 0x7ef9bbd989e8>}
(pid=2982) 2019-11-13 21:31:17,773	WARNING trainable.py:131 -- Getting current IP.
2019-11-13 21:31:17,855	WARNING util.py:133 -- The `process_failed_trial` operation took 70.35559439659119 seconds to complete, which may be a performance bottleneck.
`
```

**Comment by arunavo4** [comment]
OK, it seems to be a local issue with my system. It runs perfectly in the cloud.
