### ISSUE TITLE
TypeError: Cannot create a consistent method resolution

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#6200]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.4
- **Python version**: 3.5
- **Exact command to reproduce**: N/A

### Describe the problem
Our rllib run errors out with the attached log. We're totally unclear what this means. Sometimes it errors out immediately, sometimes after 10 or so iterations. 

### Source code / logs

Traceback (most recent call last):
  File "/home/ubuntu/venvs/robot_env/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 515, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/ubuntu/venvs/robot_env/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 351, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/ubuntu/venvs/robot_env/lib/python3.5/site-packages/ray/worker.py", line 2121, in get
    raise value.as_instanceof_cause()
  File "/home/ubuntu/venvs/robot_env/lib/python3.5/site-packages/ray/exceptions.py", line 62, in as_instanceof_cause
    class cls(RayTaskError, self.cause_cls):
TypeError: Cannot create a consistent method resolution
order (MRO) for bases RayTaskError(ServiceException), RayTaskError

**Comment by richardliaw** [comment]
cc @edoakes

**Comment by ericl** [comment]
Hmm this is Ray messing up trying to create an error message and creating an invalid py class.... however, I thought this was fixed. Does it also happen on latest?

**Comment by eugenevinitsky** [comment]
Oh, don't know if this happens on latest. Will check; thanks!
