### ISSUE TITLE
AttributeErrors with gym monitor

### ISSUE THREAD

**Issue by SubaMoorthy** [ray-project/ray#6292]
- **OS Platform and Distribution - Ubuntu 16.04
- **Ray installed from - binary
- **Ray version**: 0.7.2
- **Python version**: 3.6.2
- **Exact command to reproduce**: ray start --head --redis-port= --redis-shard-ports=, --object-manager-port= --node-manager-port= --node-ip-address=

I have a docker image for ray[rllib]==0.7.2 + tensorflow==1.13.1. When I add "monitor":True option to the cartpole example in https://github.com/ray-project/ray/blob/5d7afe8092f5521a8faa8cdfc916dcd9a5848023/rllib/examples/cartpole_lstm.py, I run into AttributeError: module 'gym' has no attribute 'wrappers'. Here is my stack trace, 
Traceback (most recent call last):
  File "/azureml-envs/azureml_e84a46469847cc1f1df0e02ea8c7ba33/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 515, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/azureml-envs/azureml_e84a46469847cc1f1df0e02ea8c7ba33/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 351, in fetch_result
    result = ray.get(trial_future[0])
  File "/azureml-envs/azureml_e84a46469847cc1f1df0e02ea8c7ba33/lib/python3.6/site-packages/ray/worker.py", line 2121, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError):[36mray_IMPALA:train()[39m (pid=238, host=aa57825b38a548f4be43c9204319a112000000)
  File "/azureml-envs/azureml_e84a46469847cc1f1df0e02ea8c7ba33/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 90, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/azureml-envs/azureml_e84a46469847cc1f1df0e02ea8c7ba33/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 372, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/azureml-envs/azureml_e84a46469847cc1f1df0e02ea8c7ba33/lib/python3.6/site-packages/ray/tune/trainable.py", line 96, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/azureml-envs/azureml_e84a46469847cc1f1df0e02ea8c7ba33/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 492, in _setup
    self._init(self.config, self.env_creator)
  File "/azureml-envs/azureml_e84a46469847cc1f1df0e02ea8c7ba33/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 106, in _init
    self.workers = make_workers(self, env_creator, policy, config)
  File "/azureml-envs/azureml_e84a46469847cc1f1df0e02ea8c7ba33/lib/python3.6/site-packages/ray/rllib/agents/impala/impala.py", line 105, in defer_make_workers
    return trainer._make_workers(env_creator, policy, config, 0)
  File "/azureml-envs/azureml_e84a46469847cc1f1df0e02ea8c7ba33/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 537, in _make_workers
    logdir=self.logdir)
  File "/azureml-envs/azureml_e84a46469847cc1f1df0e02ea8c7ba33/lib/python3.6/site-packages/ray/rllib/evaluation/worker_set.py", line 64, in __init__
    RolloutWorker, env_creator, policy, 0, self._local_config)
  File "/azureml-envs/azureml_e84a46469847cc1f1df0e02ea8c7ba33/lib/python3.6/site-packages/ray/rllib/evaluation/worker_set.py", line 220, in _make_worker
    _fake_sampler=config.get("_fake_sampler", False))
  File "/azureml-envs/azureml_e84a46469847cc1f1df0e02ea8c7ba33/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 302, in __init__
    self.env = wrap(self.env)
  File "/azureml-envs/azureml_e84a46469847cc1f1df0e02ea8c7ba33/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 299, in wrap
    env = gym.wrappers.Monitor(env, monitor_path, resume=True)
AttributeError: module 'gym' has no attribute 'wrappers'

With the same image, I am able to get videos for the following example, 
import ray
import ray.tune as tune

if __name__ == "__main__":
    ray.init(redis_address = 'localhost:6379')
    
    tune.run("IMPALA",   
             config={
                 "env": "PongNoFrameskip-v4",
                 "num_gpus": 0,
                 "num_workers": 1,
                 "monitor": True
             },
             local_dir='./logs') 
			 
Is there a difference between monitors for custom environments and gym environments?

**Comment by ericl** [comment]
I think this broke due to a gym upgrade. Can you try out https://github.com/ray-project/ray/pull/6293 ?
