### ISSUE TITLE
Atari-Apex crashes

### ISSUE THREAD

**Issue by arunavo4** [ray-project/ray#6318]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04 LTS
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.5
- **Python version**: 3.6
- **Exact command to reproduce**: Code provided below

### Describe the problem

So at first, I thought it was a problem with my Custom Env, then I tried with Atari and there was the same problem. I have only wrapped the Vision Model provided in the lib with `DistributionalQModel` There are no issues with DQN, But running Apex crashes with error:

```
`2019-11-30 09:31:09,935	WARNING worker.py:1779 -- A worker died or was killed while executing task 2b8e6c9e80aae7fadf1501000000.
2019-11-30 09:31:09,937	ERROR trial_runner.py:560 -- Error processing event.
Traceback (most recent call last):
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 506, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 347, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/worker.py", line 2349, in get
    raise value
ray.exceptions.RayTaskError: ray_APEX:train() (pid=18746, host=skywalker)
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 417, in train
    raise e
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 406, in train
    result = Trainable.train(self)
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 176, in train
    result = self._train()
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 129, in _train
    fetches = self.optimizer.step()
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/rllib/optimizers/async_replay_optimizer.py", line 142, in step
    sample_timesteps, train_timesteps = self._step()
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/rllib/optimizers/async_replay_optimizer.py", line 245, in _step
    samples = ray_get_and_free(replay)
  File "/home/skywalker/.local/lib/python3.6/site-packages/ray/rllib/utils/memory.py", line 33, in ray_get_and_free
    result = ray.get(object_ids)
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.

2019-11-30 09:31:09,940	INFO trial_runner.py:597 -- Attempting to recover trial state from last checkpoint.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 5/12 CPUs, 1/1 GPUs, 0.0/15.19 GiB heap, 0.0/5.22 GiB objects
Memory usage on this node: 18.0/31.4 GiB
Result logdir: /home/skywalker/ray_results/APEX
Number of trials: 1 ({'RUNNING': 1})
RUNNING trials:
 - APEX_BreakoutNoFrameskip-v4_0:	RUNNING, 1 failures: /home/skywalker/ray_results/APEX/APEX_BreakoutNoFrameskip-v4_0_2019-11-30_09-29-34kbalq7bx/error_2019-11-30_09-31-09.txt, [5 CPUs, 1 GPUs], [pid=18746], 60 s, 2 iter, 84640 ts, 1.9 rew

(pid=18746) 2019-11-30 09:31:09,931	INFO trainer.py:414 -- Worker crashed during call to train(). To attempt to continue training without the failed worker, set `'ignore_worker_failures': True`.
(pid=18747) 2019-11-30 09:31:09,958	INFO trainer.py:344 -- Tip: set 'eager': true or the --eager flag to enable TensorFlow eager execution
(pid=18747) 2019-11-30 09:31:14,684	INFO rollout_worker.py:768 -- Built policy map: {'default_policy': <ray.rllib.policy.tf_policy_template.DQNTFPolicy object at 0x7ef90b709588>}
(pid=18747) 2019-11-30 09:31:14,685	INFO rollout_worker.py:769 -- Built preprocessor map: {'default_policy': <ray.rllib.models.preprocessors.NoPreprocessor object at 0x7ef90b7094e0>}
(pid=18747) 2019-11-30 09:31:14,685	INFO rollout_worker.py:370 -- Built filter map: {'default_policy': <ray.rllib.utils.filter.NoFilter object at 0x7ef90b709390>}
(pid=18747) 2019-11-30 09:31:14,806	INFO actors.py:106 -- Trying to create 4 colocated actors
(pid=raylet) Traceback (most recent call last):
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/ray/workers/default_worker.py", line 8, in <module>
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/ray/__init__.py", line 13, in <module>
(pid=raylet)   File "python/ray/_raylet.pyx", line 55, in init ray._raylet
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/ray/utils.py", line 19, in <module>
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/ray/gcs_utils.py", line 5, in <module>
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/ray/core/generated/gcs_pb2.py", line 7, in <module>
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/google/protobuf/__init__.py", line 37, in <module>
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 83, in <module>
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 275, in <module>
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 373, in Specifier
(pid=raylet)   File "/usr/lib/python3.6/re.py", line 233, in compile
(pid=raylet)   File "/usr/lib/python3.6/re.py", line 301, in _compile
(pid=raylet)   File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
(pid=raylet)   File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
(pid=raylet)   File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
(pid=raylet)   File "/usr/lib/python3.6/sre_parse.py", line 765, in _parse
(pid=raylet)   File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
(pid=raylet)   File "/usr/lib/python3.6/sre_parse.py", line 768, in _parse
(pid=raylet) sre_constants.error: missing ), unterminated subpattern at position 2772 (line -11148246, column 13)
(pid=raylet) Error in sys.excepthook:
(pid=raylet) Traceback (most recent call last):
(pid=raylet)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
(pid=raylet)   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 26, in enabled
(pid=raylet) OverflowError: signed integer is greater than maximum
(pid=raylet) 
(pid=raylet) Original exception was:
(pid=raylet) Traceback (most recent call last):
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/ray/workers/default_worker.py", line 8, in <module>
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/ray/__init__.py", line 13, in <module>
(pid=raylet)   File "python/ray/_raylet.pyx", line 55, in init ray._raylet
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/ray/utils.py", line 19, in <module>
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/ray/gcs_utils.py", line 5, in <module>
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/ray/core/generated/gcs_pb2.py", line 7, in <module>
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/google/protobuf/__init__.py", line 37, in <module>
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 83, in <module>
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 275, in <module>
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 373, in Specifier
(pid=raylet)   File "/usr/lib/python3.6/re.py", line 233, in compile
(pid=raylet)   File "/usr/lib/python3.6/re.py", line 301, in _compile
(pid=raylet)   File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
(pid=raylet)   File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
(pid=raylet)   File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
(pid=raylet)   File "/usr/lib/python3.6/sre_parse.py", line 765, in _parse
(pid=raylet)   File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
(pid=raylet)   File "/usr/lib/python3.6/sre_parse.py", line 768, in _parse
(pid=raylet) sre_constants.error: missing ), unterminated subpattern at position 2772 (line -11148246, column 13)
(pid=raylet) Traceback (most recent call last):
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/ray/workers/default_worker.py", line 8, in <module>
(pid=raylet)     import ray
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/ray/__init__.py", line 105, in <module>
(pid=raylet)     import ray.projects  # noqa: E402
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/ray/projects/__init__.py", line 5, in <module>
(pid=raylet)     from ray.projects.projects import ProjectDefinition
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/ray/projects/projects.py", line 7, in <module>
(pid=raylet)     import jsonschema
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/jsonschema/__init__.py", line 31, in <module>
(pid=raylet)     import importlib_metadata
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 15, in <module>
(pid=raylet)     from ._compat import (
(pid=raylet)   File "/home/skywalker/.local/lib/python3.6/site-packages/importlib_metadata/_compat.py", line 11, in <module>
(pid=raylet)     from configparser import ConfigParser
(pid=raylet)   File "/usr/lib/python3.6/configparser.py", line 559, in <module>
(pid=raylet)     class RawConfigParser(MutableMapping):
(pid=raylet)   File "/usr/lib/python3.6/configparser.py", line 593, in RawConfigParser
(pid=raylet)     OPTCRE_NV = re.compile(_OPT_NV_TMPL.format(delim="=|:"), re.VERBOSE)
(pid=raylet)   File "/usr/lib/python3.6/re.py", line 233, in compile
(pid=raylet)     return _compile(pattern, flags)
(pid=raylet)   File "/usr/lib/python3.6/re.py", line 301, in _compile
(pid=raylet)     p = sre_compile.compile(pattern, flags)
(pid=raylet)   File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
(pid=raylet)     p = sre_parse.parse(p, flags)
(pid=raylet)   File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
(pid=raylet)     p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
(pid=raylet)   File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
(pid=raylet)     not nested and not items))
(pid=raylet)   File "/usr/lib/python3.6/sre_parse.py", line 765, in _parse
(pid=raylet)     p = _parse_sub(source, state, sub_verbose, nested + 1)
(pid=raylet)   File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
(pid=raylet)     not nested and not items))
(pid=raylet)   File "/usr/lib/python3.6/sre_parse.py", line 616, in _parse
(pid=raylet)     source.tell() - here + len(this))
(pid=raylet) sre_constants.error: nothing to repeat at position 21 (line 2, column 21)`
```

### Source code / logs

Here's the Code:
```
`from ray import tune
from ray.rllib.agents.dqn import ApexTrainer
from ray.rllib.models import ModelCatalog
from ray.rllib.utils import try_import_tf
from ray.rllib.agents.dqn.distributional_q_model import DistributionalQModel
from ray.rllib.models.tf.misc import normc_initializer, get_activation_fn
from ray.rllib.models.tf.visionnet_v1 import _get_filter_config

tf = try_import_tf()

# ============== Nature CNN Model ==================

class VisionNetwork(DistributionalQModel):
    """Generic vision network implemented in DistributionalQModel API."""

    def __init__(self, obs_space, action_space, num_outputs, model_config,
                 name, **kw):
        super(VisionNetwork, self).__init__(
            obs_space, action_space, num_outputs, model_config, name, **kw)

        activation = get_activation_fn(model_config.get("conv_activation"))
        filters = model_config.get("conv_filters")
        if not filters:
            filters = _get_filter_config(obs_space.shape)
        no_final_linear = model_config.get("no_final_linear")
        vf_share_layers = model_config.get("vf_share_layers")

        inputs = tf.keras.layers.Input(
            shape=obs_space.shape, name="observations")
        last_layer = inputs

        # Build the action layers
        for i, (out_size, kernel, stride) in enumerate(filters[:-1], 1):
            last_layer = tf.keras.layers.Conv2D(
                out_size,
                kernel,
                strides=(stride, stride),
                activation=activation,
                padding="same",
                name="conv{}".format(i))(last_layer)
        out_size, kernel, stride = filters[-1]
        if no_final_linear:
            # the last layer is adjusted to be of size num_outputs
            last_layer = tf.keras.layers.Conv2D(
                num_outputs,
                kernel,
                strides=(stride, stride),
                activation=activation,
                padding="valid",
                name="conv_out")(last_layer)
            conv_out = last_layer
        else:
            last_layer = tf.keras.layers.Conv2D(
                out_size,
                kernel,
                strides=(stride, stride),
                activation=activation,
                padding="valid",
                name="conv{}".format(i + 1))(last_layer)
            conv_out = tf.keras.layers.Conv2D(
                num_outputs, [1, 1],
                activation=None,
                padding="same",
                name="conv_out")(last_layer)

        # Build the value layers
        if vf_share_layers:
            last_layer = tf.keras.layers.Lambda(
                lambda x: tf.squeeze(x, axis=[1, 2]))(last_layer)
            value_out = tf.keras.layers.Dense(
                1,
                name="value_out",
                activation=None,
                kernel_initializer=normc_initializer(0.01))(last_layer)
        else:
            # build a parallel set of hidden layers for the value net
            last_layer = inputs
            for i, (out_size, kernel, stride) in enumerate(filters[:-1], 1):
                last_layer = tf.keras.layers.Conv2D(
                    out_size,
                    kernel,
                    strides=(stride, stride),
                    activation=activation,
                    padding="same",
                    name="conv_value_{}".format(i))(last_layer)
            out_size, kernel, stride = filters[-1]
            last_layer = tf.keras.layers.Conv2D(
                out_size,
                kernel,
                strides=(stride, stride),
                activation=activation,
                padding="valid",
                name="conv_value_{}".format(i + 1))(last_layer)
            last_layer = tf.keras.layers.Conv2D(
                1, [1, 1],
                activation=None,
                padding="same",
                name="conv_value_out")(last_layer)
            value_out = tf.keras.layers.Lambda(
                lambda x: tf.squeeze(x, axis=[1, 2]))(last_layer)

        self.base_model = tf.keras.Model(inputs, [conv_out, value_out])
        self.register_variables(self.base_model.variables)

    def forward(self, input_dict, state, seq_lens):
        # explicit cast to float32 needed in eager
        model_out, self._value_out = self.base_model(
            tf.cast(input_dict["obs"], tf.float32))
        return tf.squeeze(model_out, axis=[1, 2]), state

    def value_function(self):
        return tf.reshape(self._value_out, [-1])


ModelCatalog.register_custom_model("NatureCNN", VisionNetwork)
tune.run(ApexTrainer,
         checkpoint_freq=10,  # iterations
         checkpoint_at_end=True,
         config={"env": "BreakoutNoFrameskip-v4",
                 "model": {
                     "custom_model": "NatureCNN"
                 },
                 "double_q": False,
                 "dueling": False,
                 "num_atoms": 1,
                 "noisy": False,
                 "n_step": 3,
                 "lr": .0001,
                 "adam_epsilon": .00015,
                 "hiddens": [512],
                 "buffer_size": 1000000,
                 "schedule_max_timesteps": 10000000,
                 "exploration_final_eps": 0.01,
                 "exploration_fraction": .1,
                 "prioritized_replay_alpha": 0.5,
                 "beta_annealing_fraction": 1.0,
                 "final_prioritized_replay_beta": 1.0,
                 "num_gpus": 1,
                 "num_workers": 4,
                 "num_envs_per_worker": 2,
                 "sample_batch_size": 20,
                 "train_batch_size": 512,
                 "per_worker_exploration": True,
                 "worker_side_prioritization": True,
                 "target_network_update_freq": 50000,
                 "timesteps_per_iteration": 25000,
                 "env_config": {
                     "enable_env_logging": False,
                     "look_back_window_size": 375 * 10,
                     "observation_window": 84,
                     "frame_stack_size": 4,
                 },
                 })  # "eager": True for eager execution
`
```

**Comment by arunavo4** [comment]
OK, it seems to be a local issue with my system. It runs perfectly in the cloud.
