### ISSUE TITLE
ValueError: Unexpected config key when running example-full.yaml

### ISSUE THREAD

**Issue by shreyaspotnis** [ray-project/ray#6327]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Catalina 10.15.1
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.6
- **Python version**: 3.7.4
- **Exact command to reproduce**: ray up ray/python/ray/autoscaler/aws/example-full.yaml

### Describe the problem

When following instructions to get Automatic Cluster Setup working, I run into ValueError: Unexpected config key `pull_before_run` not in ['image', 'container_name', 'run_options', 'head_image', 'head_run_options', 'worker_image', 'worker_run_options']

Commenting out the pull_before_run line in https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/aws/example-full.yaml seems to resolve the issue

### Source code / logs

Traceback (most recent call last):
  File "/Users/shreyas/.local/share/virtualenvs/hello_ray-OF5hkI_m/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/Users/shreyas/.local/share/virtualenvs/hello_ray-OF5hkI_m/lib/python3.7/site-packages/ray/scripts/scripts.py", line 808, in main
    return cli()
  File "/Users/shreyas/.local/share/virtualenvs/hello_ray-OF5hkI_m/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/shreyas/.local/share/virtualenvs/hello_ray-OF5hkI_m/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/shreyas/.local/share/virtualenvs/hello_ray-OF5hkI_m/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shreyas/.local/share/virtualenvs/hello_ray-OF5hkI_m/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/shreyas/.local/share/virtualenvs/hello_ray-OF5hkI_m/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/shreyas/.local/share/virtualenvs/hello_ray-OF5hkI_m/lib/python3.7/site-packages/ray/scripts/scripts.py", line 486, in create_or_update
    no_restart, restart_only, yes, cluster_name)
  File "/Users/shreyas/.local/share/virtualenvs/hello_ray-OF5hkI_m/lib/python3.7/site-packages/ray/autoscaler/commands.py", line 45, in create_or_update_cluster
    config = _bootstrap_config(config)
  File "/Users/shreyas/.local/share/virtualenvs/hello_ray-OF5hkI_m/lib/python3.7/site-packages/ray/autoscaler/commands.py", line 59, in _bootstrap_config
    validate_config(config)
  File "/Users/shreyas/.local/share/virtualenvs/hello_ray-OF5hkI_m/lib/python3.7/site-packages/ray/autoscaler/autoscaler.py", line 824, in validate_config
    check_extraneous(config, schema)
  File "/Users/shreyas/.local/share/virtualenvs/hello_ray-OF5hkI_m/lib/python3.7/site-packages/ray/autoscaler/autoscaler.py", line 815, in check_extraneous
    check_extraneous(config[k], v)
  File "/Users/shreyas/.local/share/virtualenvs/hello_ray-OF5hkI_m/lib/python3.7/site-packages/ray/autoscaler/autoscaler.py", line 802, in check_extraneous
    k, list(schema.keys())))
ValueError: Unexpected config key `pull_before_run` not in ['image', 'container_name', 'run_options', 'head_image', 'head_run_options', 'worker_image', 'worker_run_options']

**Comment by richardliaw** [comment]
Can you update to the latest version of Ray? https://ray.readthedocs.io/en/latest/installation.html

**Comment by mstrofbass** [comment]
> Can you update to the latest pip wheel of Ray? https://ray.readthedocs.io/en/latest/installation.html

This worked for me.
