### ISSUE TITLE
[tune] TuneBOHB - metric KeyError

### ISSUE THREAD

**Issue by flowersw** [ray-project/ray#6343]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX - 10.14.6
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.6
- **Python version**: 3.6.7
- **Exact command to reproduce**:

```
    from ray.tune.util import pin_in_object_store, get_pinned_object
    
    X_train_pin = pin_in_object_store(X_train)
    X_test_pin = pin_in_object_store(X_test)
    y_train_pin = pin_in_object_store(y_train)
    y_test_pin = pin_in_object_store(y_test)


 
    def XGBCallback(env):
        tune.track.log(**dict(env.evaluation_result_list))
 
 
    def train_aren(config):
        train_set = xgb.DMatrix(get_pinned_object(X_train_pin), label=get_pinned_object(y_train_pin))
        test_set = xgb.DMatrix(get_pinned_object(X_test_pin), label=get_pinned_object(y_test_pin))
        bst = xgb.train(
            config, train_set, evals=[(test_set, "eval")], callbacks=[XGBCallback])
        preds = bst.predict(test_set)
        pred_labels = np.rint(preds)
        tune.track.log(
            mean_accuracy=sklearn.metrics.roc_auc_score(get_pinned_object(y_test_pin), pred_labels),
            done=True)
 
 
    # Calculate the class imbalance ratio (used for scale_pos_weight)
    counts = train_data[target].value_counts()
    pct = counts[0] / counts[1]
 

    # Try out bohb
    import ConfigSpace as CS
    config_space = CS.ConfigurationSpace()
    config_space.add_hyperparameter(
        CS.CategoricalHyperparameter(
            name='booster', choices=['gbtree']))
    config_space.add_hyperparameter(
        CS.UniformFloatHyperparameter('colsample_bytree', lower=1e-8, upper=1))
    config_space.add_hyperparameter(
        CS.UniformFloatHyperparameter('colsample_bylevel', lower=1e-8, upper=1))
    config_space.add_hyperparameter(
        CS.UniformFloatHyperparameter('colsample_bynode', lower=1e-8, upper=1))
    config_space.add_hyperparameter(
        CS.UniformFloatHyperparameter('eta', lower=1e-4, upper=1e-1))
    config_space.add_hyperparameter(
        CS.UniformFloatHyperparameter('gamma', lower=1e-8, upper=1))
    config_space.add_hyperparameter(
        CS.CategoricalHyperparameter(
            name='grow_policy', choices=['depthwise', 'lossguide']))
    config_space.add_hyperparameter(
        CS.UniformIntegerHyperparameter(name='max_depth', lower=2, upper=7))
    config_space.add_hyperparameter(
        CS.UniformIntegerHyperparameter('min_child_weight', lower=1, upper=10))
    config_space.add_hyperparameter(
        CS.UniformIntegerHyperparameter('n_estimators', lower=1, upper=500))
    config_space.add_hyperparameter(
        CS.CategoricalHyperparameter(
            name='n_jobs', choices=[-1]))
    config_space.add_hyperparameter(
        CS.UniformIntegerHyperparameter('num_parallel_tree', lower=1, upper=9))
    config_space.add_hyperparameter(
        CS.CategoricalHyperparameter(
            name='objective', choices=["binary:logistic"]))
    config_space.add_hyperparameter(
        CS.UniformFloatHyperparameter('reg_alpha', lower=1e-8, upper=20))
    config_space.add_hyperparameter(
        CS.UniformFloatHyperparameter('reg_lambda', lower=1e-8, upper=20))
    config_space.add_hyperparameter(
        CS.CategoricalHyperparameter(
            name='scale_pos_weight', choices=[pct]))
    config_space.add_hyperparameter(
        CS.CategoricalHyperparameter(
            name='seed', choices=[27]))
    config_space.add_hyperparameter(
        CS.UniformFloatHyperparameter('subsample', lower=1e-8, upper=1))
    config_space.add_hyperparameter(
        CS.CategoricalHyperparameter(
            name='verbosity', choices=[1]))

    
    from ray.tune.suggest import TuneBOHB
    algo = TuneBOHB(
        config_space, max_concurrent=2, metric='mean_accuracy', mode='max')
    
    from ray.tune.schedulers import HyperBandForBOHB
    bohb = HyperBandForBOHB(
        time_attr='training_iteration',
        metric='mean_accuracy',
        mode='max',
        max_t=100)
    
    analysis = tune.run(train_aren, scheduler=bohb, search_alg=algo,
        num_samples=10,
        resources_per_trial={"cpu": 6},
        max_failures=10,
        reuse_actors=True,
        checkpoint_at_end=True)
```

### Describe the problem
I seem to be unable to effectively pass in an eval metric, via the functional API, using BOHB. I'm not sure where eval-error is coming from - clearly my attempt to pass in a different eval metric is not working.

### Source code / logs

```(pid=6892) [0]	eval-error:0.198569

2019-12-03 07:01:32,885	ERROR trial_runner.py:569 -- Error processing event.
Traceback (most recent call last):
  File "/usr/local/anaconda/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 541, in _process_trial
    flat_result)
  File "/usr/local/anaconda/lib/python3.6/site-packages/ray/tune/suggest/bohb.py", line 103, in on_trial_result
    hbs_wrapper = self.to_wrapper(trial_id, result)
  File "/usr/local/anaconda/lib/python3.6/site-packages/ray/tune/suggest/bohb.py", line 118, in to_wrapper
    return _BOHBJobWrapper(self._metric_op * result[self.metric],
KeyError: 'mean_accuracy'
```

**Comment by flowersw** [comment]
I just followed the example in the docs: https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/bohb_example.py and created a similar Trainable class and it seems to work now!
