### ISSUE TITLE
Pip install ray fails with "No distributions at all found for ray" on Ubuntu 14.04.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#639]
I created a new Ubuntu 14.04 instance and ran the following commands.

```
sudo apt-get update
sudo apt-get install python-pip
```

Then running `pip install ray` fails with

```
> pip install ray
Downloading/unpacking ray
  Could not find any downloads that satisfy the requirement ray
Cleaning up...
No distributions at all found for ray
Storing debug log for failure in /home/ubuntu/.pip/pip.log
```

Inspecting the log gives

```
> cat /home/ubuntu/.pip/pip.log
------------------------------------------------------------
/usr/bin/pip run on Mon Jun  5 05:02:02 2017
Downloading/unpacking ray
  Getting page https://pypi.python.org/simple/ray/
  URLs to search for versions for ray:
  * https://pypi.python.org/simple/ray/
  Analyzing links from page https://pypi.python.org/simple/ray/
    Skipping https://pypi.python.org/packages/07/4a/d86a8dfab8a8f1e738bfd27ac08a710f172442a9e2d4140714240c92f6ee/ray-0.1.1-cp35-cp35m-macosx_10_6_intel.whl#md5=b75b0a9a43eabd1e084ddf84b54464f9 (from https://pypi.python.org/simple/ray/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/09/a8/63df068d56248bc9c598f3ea7f84d4cd89e8206c11432efbfc54b68533b2/ray-0.1.1-cp27-cp27m-macosx_10_6_intel.whl#md5=6d2c3841011c6276740719695677acab (from https://pypi.python.org/simple/ray/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/0d/98/d881eb00427eeb03085438cc7caceed59720d26f48e86f0bdb7aa7792ec6/ray-0.1.1-cp27-cp27mu-manylinux1_x86_64.whl#md5=8d4fa0c82c453569afd6666dbf7c3840 (from https://pypi.python.org/simple/ray/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/20/96/a9ac079450cc8dc14cbb27bab0b7d8965b0e122e402399afe000e8c74875/ray-0.1.1-cp36-cp36m-manylinux1_x86_64.whl#md5=fe5a9ad4948254f45cfcb3b596a04ac9 (from https://pypi.python.org/simple/ray/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/4f/d8/26104b87ae00eb978485f888b7b556668493a5b63cbd7320237a56c6cb8e/ray-0.1.1-cp33-cp33m-manylinux1_x86_64.whl#md5=75aa85c4db15561d2093404c826ef457 (from https://pypi.python.org/simple/ray/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/af/c2/b1979f89e4c0e8389245b6f9021e17c108efcc8824170bfbc4f10ac3034e/ray-0.1.1-cp36-cp36m-macosx_10_6_intel.whl#md5=ee3a97d13bc48d8d264ff1600aeeee8b (from https://pypi.python.org/simple/ray/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/b5/25/4e9de239b34137f404d997409cf62068c4e17b108bfd94d8b795a0412175/ray-0.1.1-cp34-cp34m-manylinux1_x86_64.whl#md5=47606ab01d858e754edf41f8599feea3 (from https://pypi.python.org/simple/ray/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/c3/b0/c3b6d7d1bfbee99321a2263aebe8191ae5a61368f70e1210a4ec80c6fbef/ray-0.1.1-cp35-cp35m-manylinux1_x86_64.whl#md5=3e15bc024d556e74b8fc4f8de40a0eff (from https://pypi.python.org/simple/ray/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/c4/b8/d031849006050325657f8c6f86e8135f939a96aea00c2c313f4b0568bbea/ray-0.1.1-cp34-cp34m-macosx_10_6_intel.whl#md5=bdd72071767d0da884bdc511b0633dd1 (from https://pypi.python.org/simple/ray/) because it is not compatible with this Python
  Could not find any downloads that satisfy the requirement ray
Cleaning up...
  Removing temporary dir /tmp/pip_build_ubuntu...
No distributions at all found for ray
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for ray
```

**Comment by robertnishihara** [comment]
It may be that the version of pip is outdated.

```
> pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
```

After doing

```
> sudo pip install -U pip
> pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
> sudo pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

Then doing the following almost succeeds.

```
> sudo pip install ray
Collecting ray
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading ray-0.1.1-cp27-cp27mu-manylinux1_x86_64.whl (8.2MB)
    100% |████████████████████████████████| 8.2MB 167kB/s 
Collecting redis (from ray)
  Downloading redis-2.10.5-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 10.1MB/s 
Requirement already satisfied: colorama in /usr/lib/python2.7/dist-packages (from ray)
Collecting flatbuffers (from ray)
  Downloading flatbuffers-2015.12.22.1-py2.py3-none-any.whl
Collecting cloudpickle>=0.2.2 (from ray)
  Downloading cloudpickle-0.3.1-py2.py3-none-any.whl
Collecting numpy (from ray)
  Downloading numpy-1.12.1-cp27-cp27mu-manylinux1_x86_64.whl (16.5MB)
    100% |████████████████████████████████| 16.5MB 83kB/s 
Collecting psutil (from ray)
  Downloading psutil-5.2.2.tar.gz (348kB)
    100% |████████████████████████████████| 358kB 3.8MB/s 
Collecting funcsigs (from ray)
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Collecting click (from ray)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 7.8MB/s 
Installing collected packages: redis, flatbuffers, cloudpickle, numpy, psutil, funcsigs, click, ray
  Running setup.py install for psutil ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Ut7r_3/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Ls09Vf-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-2.7/psutil
    creating build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/runner.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-2.7/psutil/tests
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/psutil
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=522 -DPSUTIL_LINUX=1 -I/usr/include/python2.7 -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o
    psutil/_psutil_linux.c:12:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Ut7r_3/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Ls09Vf-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Ut7r_3/psutil/
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

This is fixed by the following.

```
sudo apt-get install python-dev
```

Then `sudo pip install ray` succeeds.
