### ISSUE TITLE
Actor definition needs Actor(object).

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#650]
The following code does not work on Python 2 but works on Python 3. 

```
import ray
ray.init()

@ray.remote
class Outer():
    def __init__(self):
        pass
```
Error thrown:
```
Traceback (most recent call last):
  File "/Users/rliaw/miniconda2/envs/py2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/rliaw/miniconda2/envs/py2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/rliaw/miniconda2/envs/py2/lib/python2.7/site-packages/ray/worker.py", line 1166, in import_thread
    worker.fetch_and_register_actor(key, worker)
  File "/Users/rliaw/miniconda2/envs/py2/lib/python2.7/site-packages/ray/actor.py", line 86, in fetch_and_register_actor
    worker.actors[actor_id_str] = unpickled_class.__new__(unpickled_class)
AttributeError: class Class has no attribute '__new__'
```

**Comment by robertnishihara** [comment]
Do we want to support old-style classes?

We should certainly give a better error message.

**Comment by pcmoritz** [comment]
Better error message: Yes! I tagged it with "help wanted" as it looks like a low hanging fruit that would be perfect for somebody to look into to contribute to the project.
