### ISSUE TITLE
Serialization is 20% slower from 0.7.6 -> 0.7.7

### ISSUE THREAD

**Issue by devin-petersohn** [ray-project/ray#6551]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 0.7.7, 0.8

*Does the problem occur on the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html)?* Unsure

Modin is seeing ~20% performance regression from 0.7.3, and ~30% regression in 0.8.

### Reproduction

```python
import os
os.environ["MODIN_ENGINE"] = "ray"
import modin.pandas as pd
%time df = pd.read_csv("file.csv")
```

File can be created by:

```python
import numpy as np
import modin.pandas as pd
pd.DataFrame(np.random.randint(0, 100, size=(2**20, 2**8))).add_prefix("col").to_csv("file.csv", index=False)
```

**Comment by zplizzi** [comment]
I actually see an even more significant performance regression on my reinforcement learning (APEX-ish) project. On 0.7.6, I got ~2000fps training performance. On 0.8.0, I get ~800fps with otherwise the exact same code and system. Unfortunately I don't have an easy way to package it up for y'all to look at, although I could try to put something together if it would be really helpful to have a reproduction.

**Comment by ericl** [comment]
@zplizzi is this multi-node? I think I might know what's going on in that case.

**Comment by ericl** [comment]
@devin-petersohn is it possible to isolate this to a benchmark script that does not have external dependencies? That way, we can fix it and check it into the perf tests to avoid regressions in the future.

**Comment by devin-petersohn** [comment]
I tried for a bit to reproduce without pandas, but was unable. Here are the timelines and screenshots of the timelines:

0.7.3:
![Screen Shot 2019-12-19 at 5 05 45 PM](https://user-images.githubusercontent.com/10732128/71221578-f84ad200-2281-11ea-8bf2-f0383bbff9a1.png)

0.8.0:
![Screen Shot 2019-12-19 at 5 06 00 PM](https://user-images.githubusercontent.com/10732128/71221586-fed94980-2281-11ea-99ce-ef09f9467a5b.png)


Timelines (they are JSON but uploaded as text because GitHub)
[t_0_7_3.txt](https://github.com/ray-project/ray/files/3986233/t_0_7_3.txt)
[t_0_8_0.txt](https://github.com/ray-project/ray/files/3986234/t_0_8_0.txt)

>Btw, can you make sure you have numpy==1.16 installed or higher? 
numpy version is 1.17.4

**Comment by ericl** [comment]
Thanks, it looks like there is this extra deserialization step that wasn't there before... Also, the runtime itself is a bit slower.

Couple more questions:
- Could you try on 0.8.0 with RAY_FORCE_DIRECT=0 and see what the delta is?
- For the 0.7.7 regression, could you do a quick git bisect against master to see when the slowdown first started? You can find the wheels here (listed by git hash) (https://s3.console.aws.amazon.com/s3/buckets/ray-wheels/master/?region=us-west-2&tab=overview), so you can just pip install -U <wheel url> for each of the master commits.

**Comment by devin-petersohn** [comment]
>Could you try on 0.8.0 with RAY_FORCE_DIRECT=0 and see what the delta is?

6.45s with `RAY_FORCE_DIRECT=0`, 7.5s without changing flag

>For the 0.7.7 regression, could you do a quick git bisect against master to see when the slowdown first started?

That is too much for me to do. I have a long backlog for Modin that I need to get done.

**Comment by ericl** [comment]
I got

```
>>> import modin.pandas as pd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eric/.local/lib/python3.6/site-packages/modin/pandas/__init__.py", line 212, in <module>
    initialize_ray()
  File "/home/eric/.local/lib/python3.6/site-packages/modin/pandas/__init__.py", line 173, in initialize_ray
    logging_level=100,
  File "/home/eric/Desktop/ray/python/ray/worker.py", line 736, in init
    ray_params=ray_params)
  File "/home/eric/Desktop/ray/python/ray/node.py", line 168, in __init__
    self.start_head_processes()
  File "/home/eric/Desktop/ray/python/ray/node.py", line 593, in start_head_processes
    self.start_redis()
  File "/home/eric/Desktop/ray/python/ray/node.py", line 440, in start_redis
    self.get_resource_spec(),
  File "/home/eric/Desktop/ray/python/ray/node.py", line 231, in get_resource_spec
    self._ray_params.redis_max_memory).resolve(is_head=self.head)
  File "/home/eric/Desktop/ray/python/ray/resource_spec.py", line 206, in resolve
    int(100 * (memory / system_memory))))
ValueError: After taking into account object store and redis memory usage, the amount of memory on this node available for tasks and actors (-0.65 GB) is less than -3% of total. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
```

when I tried to run the second command to produce the CSV (I also had to comment out the Ray version check in modin). I'm guessing modin is forcing memory settings, is there a way to override it?

**Comment by devin-petersohn** [comment]
Try this:

```python
import os
os.environ["MODIN_ENGINE"] = "ray"
import ray
ray.init()
import modin.pandas as pd
%time df = pd.read_csv("file.csv")
```

**Comment by ericl** [comment]
I did some timing and (with a slightly smaller file since the above was too big), I get about the same time for both RAY_FORCE_DIRECT options after a few tries. So maybe only regression is due to the pickle5 serialization change in 0.7.7.

**Comment by zplizzi** [comment]
Mine is not multi-node, although there are about 8 actors running on the
machine.

**Comment by ericl** [comment]
@zplizzi interesting, I didn't see any APEX slowdown with 0.7.7->0.8.0 (actually it got about 20% faster). Could you provide a repro script with some standard benchmark env?

**Comment by zplizzi** [comment]
Actually, the issue seems to be the 0.7.6->0.7.7 transition. On 0.7.6, I get 2000fps. On 0.7.7, 800fps, and on 0.7.8, 800fps. It does seem to be bottlenecking in bulk data transfer in and out of a replay buffer, so it probably has to do with the serialization changes you mentioned?

**Comment by zplizzi** [comment]
Here's an example which partially reproduces the issue (sorry for the low quality code, just hacked a bunch of stuff together): https://gist.github.com/zplizzi/b84f0bb0f659dc31963265c5cb9924fe

On 0.7.6, it averages ~2600 fps, and on 0.7.7 around ~1900. 

I'm not sure why the perf impact is even more amplified in my actual full project, but I would guess the root cause is the same.

**Comment by robertnishihara** [comment]
@devin-petersohn @pcmoritz @ericl as @ericl suggests, if the slow down is happening with Python 3.6 and 3.7 but not with Python 3.5, then it's probably due to the pickle5 change. Do we see a change in performance of `ray.put(pandas_df)` for large dataframes between Python 3.5 and 3.6?

**Comment by ericl** [comment]
Running the test script, I can confirm the regression is from 0.7.6->0.7.7, and not 0.8.0. This points to the bottleneck being pickle5.

```
> ray==0.8.0
907.3642488242835
1377.472110130667
1526.0924844528545
1551.4695082011556
1486.8413696076925
average over last four == 1485 (baseline)

> ray==0.7.7
862.4451994733868
1280.4840697147702
1409.8463817059303
1567.7306924337024
1499.2307739136354
average over last four == 1438 (within 5% of baseline)

> ray==0.7.6
1123.1070510175537
1739.043648441102
1970.2117206095018
1900.342306686771
1860.3043053079655
average over last four == 1867 (25% faster than baseline)
```

When I commented out the pack/unpack compression code, perf increased to ~3000fps for 0.8.0 and ~4200 qps for 0.7.6.

**Comment by ericl** [comment]
@suquark

**Comment by ericl** [comment]
@suquark

**Comment by suquark** [comment]
hmmm, it's very strange that the deserialization time is so significant in the timeline. l'll look into it

**Comment by edoakes** [comment]
@suquark any progress on this?

**Comment by roireshef** [comment]
@suquark , what's the solution here? Should we disable compression?

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
