### ISSUE TITLE
[streaming]there is a bug when the operator key_by()'s parameter is a function

### ISSUE THREAD

**Issue by ancrs** [ray-project/ray#6730]
### What is the problem?
OS: ubuntu 18.04
Python version: 3.6
Ray version: ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.whl

there is a bug when the operator key_by()'s parameter is a function
when run wordcount.py in ray/streaming/python/examples, an error happen, the error tracestack showed below

```shell
2020-01-07 16:12:19,165	WARNING services.py:1007 -- Failed to start the reporter. The reporter requires 'pip install psutil'.
2020-01-07 16:12:19,335	INFO streaming.py:103 -- Generating 1 actors of type OpType.Source...
2020-01-07 16:12:19,344	INFO streaming.py:103 -- Generating 2 actors of type OpType.FlatMap...
2020-01-07 16:12:19,387	INFO streaming.py:103 -- Generating 2 actors of type OpType.KeyBy...
2020-01-07 16:12:19,418	INFO streaming.py:103 -- Generating 2 actors of type OpType.Sum...
2020-01-07 16:12:19,442	INFO streaming.py:103 -- Generating 2 actors of type OpType.Inspect...
2020-01-07 16:12:19,465	INFO streaming.py:353 -- init...
Traceback (most recent call last):
  File "wordcount.py", line 104, in <module>
    env_handle = env.execute()  # Deploys and executes the dataflow
  File "/home/parallels/env3.6/lib/python3.6/site-packages/ray/streaming/streaming.py", line 359, in execute
    assert ray.get(wait) is True
  File "/home/parallels/env3.6/lib/python3.6/site-packages/ray/worker.py", line 1486, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray_worker (pid=18575, ip=10.211.55.4)
  File "python/ray/_raylet.pyx", line 643, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 623, in function_executor
  File "/home/parallels/env3.6/lib/python3.6/site-packages/ray/streaming/jobworker.py", line 48, in init
    env = pickle.loads(env)
AttributeError: Can't get attribute 'key_selector' on <module '__main__' from '/home/parallels/env3.6/lib/python3.6/site-packages/ray/workers/default_worker.py'>
```

### Reproduction (REQUIRED)

use [wordcount.py](https://github.com/ray-project/ray/blob/master/streaming/python/examples/wordcount.py) could reproduction this probelem

And I thought, this problem was caused by `pickle`, if use `cloudpickle` instead, this problem will be solved.  

[jobwork.py](https://github.com/ray-project/ray/blob/master/streaming/python/jobworker.py#L48)
[streaming.py](https://github.com/ray-project/ray/blob/master/streaming/python/streaming.py#L357)

change this two line of code from `pickle` to `cloudpickle` will solve the problem, I have verified.

- [*] I have verified my script runs in a clean environment and reproduces the issue.
- [*] I have verified the issue also occurs with the [latest wheels]

**Comment by chaokunyang** [comment]
@ancrs , thanks for this issue. For serialization `function` to be executed on remote hosts, `cloudpickle` should be used. We are rewritten streaming python api, new api won't have this issue. Please take a look at #6755 .

**Comment by chaokunyang** [comment]
@ancrs Could you please submit a PR for change `pickle` to `cloudpickle`?

**Comment by edoakes** [comment]
@ancrs any update on this?

**Comment by ashione** [comment]
@ancrs this issue will be closed if no more comments about exceptions.
