### ISSUE TITLE
Rllib rollout.py errors out with KeyError: 'trainer_state'

### ISSUE THREAD

**Issue by w601sxs** [ray-project/ray#6786]
### What is the problem?

With the attached test model, rollout.py fails. Upon checking, we found that the step that fauls is the `agent.restore` step that is reading the pickle file.  Any help is appreciated! 

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version 0.8.0
python 3.6
TF 2.0 (or 1.18, didn't matter)

### Full trace

`2020-01-13 23:34:11,000	WARNING worker.py:673 -- WARNING: Not updating worker name since `setproctitle` is not installed. Install this with `pip install setproctitle` (or ray[debug]) to enable monitoring of worker processes.
2020-01-13 23:34:11,001	WARNING services.py:597 -- setpgrp failed, processes may not be cleaned up properly: [Errno 1] Operation not permitted.
2020-01-13 23:34:11,001	INFO resource_spec.py:216 -- Starting Ray with 32.52 GiB memory available for workers and up to 16.27 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-01-13 23:34:11,372	INFO trainer.py:371 -- Tip: set 'eager': true or the --eager flag to enable TensorFlow eager execution
2020-01-13 23:34:11,387	INFO trainer.py:512 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
2020-01-13 23:34:32,339	INFO trainable.py:102 -- _setup took 20.957 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2020-01-13 23:34:32,339	WARNING util.py:45 -- Install gputil for GPU system monitoring.
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/bin/rllib", line 8, in <module>
    sys.exit(cli())
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/scripts.py", line 40, in cli
    rollout.run(options, rollout_parser)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/rollout.py", line 258, in run
    agent.restore(args.checkpoint)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/tune/trainable.py", line 341, in restore
    self._restore(checkpoint_path)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 559, in _restore
    self.__setstate__(extra_data)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 162, in __setstate__
    self.state = state["trainer_state"].copy()
KeyError: 'trainer_state'`

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no 
external library dependencies** (i.e., use fake or mock data / environments):

Test Model:
[testmodel (1).zip](https://github.com/ray-project/ray/files/4056859/testmodel.1.zip)

pip install ray[rllib]
pip install box2d-py

`
from ray.rllib.agents.registry import get_agent_class

cls = get_agent_class('PPO')

import ray
ray.init()

agent = cls(env='LunarLander-v2')

agent.restore('./testmodel/checkpoint_1/checkpoint-1')
`
If we cannot run your script, we cannot fix your issue.

- [ Yes ] I have verified my script runs in a clean environment and reproduces the issue.
- [ Yes ] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by gml16** [comment]
I had the same problem and solved it by adding the key `trainer_state` to the checkpoint.

```
def update_checkpoint_for_rollout(checkpoint_path):
    with open(checkpoint_path, "rb") as f:
        extra_data = pickle.load(f)
    if not "trainer_state" in extra_data:
        extra_data["trainer_state"] = {}
        with open(checkpoint_path, 'wb') as f:
            pickle.dump(extra_data, f)
```

Now you can just call `update_checkpoint_for_rollout('./testmodel/checkpoint_1/checkpoint-1')` in your example before restoring and it should work.

This is quite an old issue but I hope it can help anyone who's struggling with it.

**Comment by avnishn** [comment]
Going to go ahead and close this issue as it is likely stale.
