### ISSUE TITLE
[autoscaler] 503 Internal error when when starting workers on google cloud

### ISSUE THREAD

**Issue by carlbalmer** [ray-project/ray#6790]
Is any body else suddenly getting an 503 Internal error response when trying to start workers on the google cloud?

*Ray version and other system information (Python version, TensorFlow version, OS):*
0.8.0

Without changing any cluster configuration the head node suddenly was not stating any workers.
Investigating with `ray monitor` shows the error listed below.
This is happening on multiple google cloud projects and regions with the example-minimal.yaml  and has been persisting over 2 days.

```
2020-01-14 12:02:28,145 INFO autoscaler.py:737 -- StandardAutoscaler: 0/1 target nodes (0 pending) (bringup=True)
2020-01-14 12:02:28,146 INFO autoscaler.py:738 -- LoadMetrics: MostDelayedHeartbeats={'10.156.0.2': 0.3882584571838379}, NodeIdleSeconds=Min=868 Mean=868 Max=868, NumNodesConnected=1, NumNodesUsed=0.0, ResourceUsage=0.0/2.0 CPU, 0.0 GiB/0.84 GiB memory, 0.0/1.0 node:10.156.0.2, 0.0 GiB/0.26 GiB object_store_memory, TimeSinceLastHeartbeat=Min=0 Mean=0 Max=0
2020-01-14 12:02:28,146 INFO autoscaler.py:726 -- StandardAutoscaler: Queue 1 new nodes for launch
2020-01-14 12:02:28,152 INFO autoscaler.py:355 -- NodeLauncher0: Got 1 nodes to launch.
2020-01-14 12:02:28,414 INFO autoscaler.py:737 -- StandardAutoscaler: 0/1 target nodes (1 pending) (bringup=True)
2020-01-14 12:02:28,420 INFO autoscaler.py:738 -- LoadMetrics: MostDelayedHeartbeats={'10.156.0.2': 0.662731409072876}, NodeIdleSeconds=Min=869 Mean=869 Max=869, NumNodesConnected=1, NumNodesUsed=0.0, ResourceUsage=0.0/2.0 CPU, 0.0 GiB/0.84 GiB memory, 0.0/1.0 node:10.156.0.2, 0.0 GiB/0.26 GiB object_store_memory, TimeSinceLastHeartbeat=Min=0 Mean=0 Max=0
2020-01-14 12:02:28,725 INFO autoscaler.py:355 -- NodeLauncher0: Launching 1 nodes.
2020-01-14 12:02:29,362 ERROR autoscaler.py:349 -- Launch failed
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 347, in run
    self._launch_node(config, count)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 337, in _launch_node
    }, count)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/autoscaler/gcp/node_provider.py", line 198, in create_node
    })).execute() for i in range(count)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/autoscaler/gcp/node_provider.py", line 198, in <listcomp>
    })).execute() for i in range(count)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/googleapiclient/http.py", line 851, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 503 when requesting https://compute.googleapis.com/compute/v1/projects/hanabi-ma-thesis/zones/europe-west3-a/instances?alt=json returned "Internal error. Please try again or contact Google Support. (Code: '59C185DB35BF1.47B00DE.100602FE')">
2020-01-14 12:02:33,243 INFO autoscaler.py:737 -- StandardAutoscaler: 0/1 target nodes (0 pending) (bringup=True)
```

**Comment by mstrofbass** [comment]
I'm getting the same error but have nothing more useful to contribute.

**Comment by carlbalmer** [comment]
It is now suddenly working again. So it probably was a server side problem.
