### ISSUE TITLE
pip install from source requires --editable/-e flag

### ISSUE THREAD

**Issue by dHannasch** [ray-project/ray#6845]
### Describe your feature request

pip install from source fails:
```
$ pip install .
Created temporary directory: /tmp/pip-ephem-wheel-cache-xmjn4z3r
Created temporary directory: /tmp/pip-req-tracker-flbc6alc
Created requirements tracker '/tmp/pip-req-tracker-flbc6alc'
Created temporary directory: /tmp/pip-install-cvmhx7qb
Processing $SRC_DIR/python
  Created temporary directory: /tmp/pip-req-build-e3xj1kq7
  Added file://$SRC_DIR/python to build tracker '/tmp/pip-req-tracker-flbc6alc'
    Running command python setup.py egg_info
    Running setup.py (path:/tmp/pip-req-build-e3xj1kq7/setup.py) egg_info for package from file://$SRC_DIR/python
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-e3xj1kq7/setup.py", line 191, in <module>
        long_description=open("../README.rst").read(),
    FileNotFoundError: [Errno 2] No such file or directory: '../README.rst'
```
Of course, it does work with the --editable/-e flag.
(The instructions at https://ray.readthedocs.io/en/latest/installation.html#install-ray correctly include -e, but don't clarify that it's not just a convenience to allow editing the code locally. They certainly don't mention what will happen if -e is left off.)

Ideally ray would be installable normally, without the flag. That would require necessary non-source-code files to be marked for inclusion in the package. There are many ways to do that --- a MANIFEST.in file is arguably the simplest, while setuptools-scm is more complicated to set up but easier to maintain. (https://github.com/ionelmc/cookiecutter-pylibrary allows either.)

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
