### ISSUE TITLE
[tune], [rllib] Tune grid_search errors if you use an RLlib trainer

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#6847]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* Ray 0.8.0, python 3.6.5, TF 2.0.0, Mac

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

```
import ray
from ray.rllib.agents.ppo.ppo_policy import PPOTFPolicy
from ray.rllib.agents.ppo.ppo import DEFAULT_CONFIG

from ray.tune import run as run_tune
from ray.tune.registry import register_env

import gym
from ray import tune
from ray.rllib.agents.ppo import PPOTrainer
from gym.spaces import Box
import numpy as np

class DummyEnv(gym.Env):
    """Simple env in which the policy learns to repeat a previous observation
    token after a given delay."""

    def __init__(self):
        self.observation_space = Box(low=-1, high=1, shape=(2,))
        self.action_space = Box(low=-1, high=1, shape=(2,))
        self.step_num = 0

    def reset(self):
        self.step_num = 0.0
        return np.zeros(2)

    def step(self, action):
        self.step_num += 1
        if self.step_num > 100:
            done = {'__all__': True}
        else:
            done = {'__all__': False}
        return np.zeros(2), 100, done, {}


if __name__ == '__main__':
    env = DummyEnv()
    config = DEFAULT_CONFIG
    config['train_batch_size'] = 500
    config['lr'] = tune.grid_search([1e-2, 1e-3])

    config['env'] = 'DummyEnv'
    env_creator = lambda config: DummyEnv()
    register_env('DummyEnv', env_creator)

    exp_dict = {
        'name': 'ProofOfConcept',
        'run_or_experiment': PPOTrainer,
        'stop': {
            'training_iteration': 100
        },
        'config': config,
    }

    ray.init(local_mode=True)
    run_tune(**exp_dict, queue_trials=False)
```

**Comment by eugenevinitsky** [comment]
If you swap out PPOTrainer with 'PPO' everything works fine.

**Comment by eugenevinitsky** [comment]
This is the error btw:
```
2020-01-19 13:55:41,216	ERROR ray_trial_executor.py:249 -- Trial PPO_2_lr=5e-05: Unexpected error starting runner.
Traceback (most recent call last):
  File "/Users/eugenevinitsky/anaconda3/envs/sim2real/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 240, in start_trial
    self._start_trial(trial, checkpoint)
  File "/Users/eugenevinitsky/anaconda3/envs/sim2real/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 180, in _start_trial
    or trial.has_checkpoint()))
  File "/Users/eugenevinitsky/anaconda3/envs/sim2real/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 130, in _setup_remote_runner
    return cls.remote(**kwargs)
  File "/Users/eugenevinitsky/anaconda3/envs/sim2real/lib/python3.6/site-packages/ray/actor.py", line 329, in remote
    return self._remote(args=args, kwargs=kwargs)
  File "/Users/eugenevinitsky/anaconda3/envs/sim2real/lib/python3.6/site-packages/ray/actor.py", line 471, in _remote
    *copy.deepcopy(args), **copy.deepcopy(kwargs))
  File "/Users/eugenevinitsky/anaconda3/envs/sim2real/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 83, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/Users/eugenevinitsky/anaconda3/envs/sim2real/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 404, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/Users/eugenevinitsky/anaconda3/envs/sim2real/lib/python3.6/site-packages/ray/tune/trainable.py", line 172, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/Users/eugenevinitsky/anaconda3/envs/sim2real/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 510, in _setup
    self._allow_unknown_subkeys)
  File "/Users/eugenevinitsky/anaconda3/envs/sim2real/lib/python3.6/site-packages/ray/tune/utils/util.py", line 168, in deep_update
    deep_update(original[k], value, new_keys_allowed, [])
  File "/Users/eugenevinitsky/anaconda3/envs/sim2real/lib/python3.6/site-packages/ray/tune/utils/util.py", line 160, in deep_update
    for k, value in new_dict.items():
AttributeError: 'float' object has no attribute 'items'
```

**Comment by richardliaw** [comment]
The error here is due to a weird self-mutation of the default config. the fix should be 
```
if __name__ == '__main__':
    env = DummyEnv()
    config = DEFAULT_CONFIG.copy()
    config['train_batch_size'] = 500

**Comment by eugenevinitsky** [comment]
Oh nice, thanks!

**Comment by roireshef** [comment]
I think I managed to find an elegant solution to that. Please check https://github.com/ray-project/ray/pull/6940
