### ISSUE TITLE
Error when trying to run gcp cluster

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#6881]
If I use the full example (https://github.com/ray-project/ray/blob/d2c6457832c96ff92b5e02771c1e9be58d9d19c3/python/ray/autoscaler/gcp/example-full.yaml) provided with gcp then my cluster creation fails at:

```
bin:/home/ubuntu/anaconda3/envs/tensorflow_p36/bin:/home/ubuntu/anaconda3/bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/home/ubuntu/anaconda3/envs/tensorflow_p36/bin:/home/ubuntu/anaconda3/bin:/home/ubuntu/anaconda3/envs/tensorflow_p36/bin:/home/ubuntu/anaconda3/bin:/home/ubuntu/anaconda3/envs/tensorflow_p36/bin:/home/ubuntu/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/.bazel/bin
    ++ which bazel
    + BAZEL_EXECUTABLE=
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ubuntu/ray/python/setup.py", line 213, in <module>
        license="Apache 2.0")
      File "/home/ubuntu/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/ubuntu/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/ubuntu/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/setuptools/command/develop.py", line 134, in install_for_development
        self.run_command('build_ext')
      File "/home/ubuntu/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/ubuntu/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/ubuntu/ray/python/setup.py", line 102, in run
        subprocess.check_call(command)
      File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '-p', '/home/ubuntu/anaconda3/bin/python']' returned non-zero exit status 1.
Cleaning up...
Exception information:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pip/req/req_install.py", line 845, in install
    install_options, global_options, prefix=prefix)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pip/req/req_install.py", line 1007, in install_editable
    show_stdout=False)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/home/ubuntu/anaconda3/bin/python -c "import setuptools, tokenize;__file__='/home/ubuntu/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/ubuntu/ray/python/
Command "/home/ubuntu/anaconda3/bin/python -c "import setuptools, tokenize;__file__='/home/ubuntu/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/ubuntu/ray/python/
You are using pip version 9.0.1, however version 20.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
2020-01-21 13:52:35,819 INFO log_timer.py:21 -- NodeUpdater: ray-default-head-887afe3a: Setup commands completed [LogTimer=12458ms]
2020-01-21 13:52:35,819 INFO log_timer.py:21 -- NodeUpdater: ray-default-head-887afe3a: Applied config fe4a545edab8bb2f7cf1b8aba1453e25e3ba73f9 [LogTimer=34679ms]
2020-01-21 13:52:35,819 ERROR updater.py:342 -- NodeUpdater: ray-default-head-887afe3a: Error updating (Exit Status 1) ssh -i /Users/andriy/.ssh/ray-autoscaler_gcp_us-west1_andriy_ubuntu.pem -o ConnectTimeout=120s -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_19b68cc2fb/c21f969b5f/%C -o ControlPersist=10s ubuntu@35.247.31.82 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && cd ~/ray/python && pip install -e . --verbose'
2020-01-21 13:52:35,828 INFO discovery.py:867 -- URL being requested: GET https://compute.googleapis.com/compute/v1/projects/andriy/zones/us-west1-a/instances?filter=%28%28status+%3D+STAGING%29+OR+%28status+%3D+RUNNING%29+OR+%28status+%3D+PROVISIONING%29%29+AND+%28labels.ray-cluster-name+%3D+default%29&alt=json
2020-01-21 13:52:36,030 INFO discovery.py:867 -- URL being requested: POST https://compute.googleapis.com/compute/v1/projects/andriy/zones/us-west1-a/instances/ray-default-head-887afe3a/setLabels?alt=json
2020-01-21 13:52:37,321 INFO node_provider.py:26 -- wait_for_compute_zone_operation: Waiting for operation operation-1579632756066-59caae94d0835-e9b105fe-646f5c5e to finish...
2020-01-21 13:52:37,323 INFO discovery.py:867 -- URL being requested: GET https://compute.googleapis.com/compute/v1/projects/andriy/zones/us-west1-a/operations/operation-1579632756066-59caae94d0835-e9b105fe-646f5c5e?alt=json
2020-01-21 13:52:42,538 INFO discovery.py:867 -- URL being requested: GET https://compute.googleapis.com/compute/v1/projects/andriy/zones/us-west1-a/operations/operation-1579632756066-59caae94d0835-e9b105fe-646f5c5e?alt=json
2020-01-21 13:52:42,732 INFO node_provider.py:37 -- wait_for_compute_zone_operation: Operation operation-1579632756066-59caae94d0835-e9b105fe-646f5c5e finished.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/projectname/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/opt/miniconda3/envs/projectname/lib/python3.7/site-packages/ray/autoscaler/updater.py", line 345, in run
    raise e
  File "/opt/miniconda3/envs/projectname/lib/python3.7/site-packages/ray/autoscaler/updater.py", line 335, in run
    self.do_update()
  File "/opt/miniconda3/envs/projectname/lib/python3.7/site-packages/ray/autoscaler/updater.py", line 424, in do_update
    self.cmd_runner.run(cmd)
  File "/opt/miniconda3/envs/projectname/lib/python3.7/site-packages/ray/autoscaler/updater.py", line 256, in run
    self.process_runner.check_call(final_cmd)
  File "/opt/miniconda3/envs/projectname/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh', '-i', '/Users/andriy/.ssh/ray-autoscaler_gcp_us-west1_andriy_ubuntu.pem', '-o', 'ConnectTimeout=120s', '-o', 'StrictHostKeyChecking=no', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/tmp/ray_ssh_19b68cc2fb/c21f969b5f/%C', '-o', 'ControlPersist=10s', 'ubuntu@35.247.31.82', 'bash', '--login', '-c', '-i', "'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && cd ~/ray/python && pip install -e . --verbose'"]' returned non-zero exit status 1.

2020-01-21 13:52:42,754 INFO discovery.py:867 -- URL being requested: GET https://compute.googleapis.com/compute/v1/projects/andriy/zones/us-west1-a/instances?filter=%28%28labels.ray-node-type+%3D+head%29%29+AND+%28%28status+%3D+STAGING%29+OR+%28status+%3D+RUNNING%29+OR+%28status+%3D+PROVISIONING%29%29+AND+%28labels.ray-cluster-name+%3D+default%29&alt=json
2020-01-21 13:52:42,959 ERROR commands.py:279 -- get_or_create_head_node: Updating 35.247.31.82 failed
```

**Comment by richardliaw** [comment]
You're trying to build ray; is it possible to avoid that? Maybe just install a wheel and use `ray/python/ray/setup-dev.py`?

**Comment by drozzy** [comment]
No idea, but I tried AWS script and it worked it seems.

I'll keep digging, thanks.
