### ISSUE TITLE
Ray.init() crashes when Ray installed from pip, gives error "could not connect to socket".

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#696]
System:
- Ubuntu 16.04 desktop with 31GB memory and 12 cores.
- Python 2.7.12 (the system Python)
- Ray 0.1.1 (installed via pip)

Running the following fails.

```python
import ray
ray.init()
```

The output is 

```
user@ubuntu:~$ ipython
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import ray

In [2]: ray.init()
17746:M 25 Jun 14:33:45.958 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
17746:M 25 Jun 14:33:45.958 # Server started, Redis version 3.9.102
17746:M 25 Jun 14:33:45.959 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
17746:M 25 Jun 14:33:45.959 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
Waiting for redis server at 127.0.0.1:26592 to respond...
17750:M 25 Jun 14:33:46.059 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
17750:M 25 Jun 14:33:46.059 # Server started, Redis version 3.9.102
17750:M 25 Jun 14:33:46.059 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
17750:M 25 Jun 14:33:46.059 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
Waiting for redis server at 127.0.0.1:22512 to respond...
Allowing the Plasma store to use up to 13.4597GB of memory.
Connection to socket failed for pathname /tmp/plasma_store91700744
Starting local scheduler with 12 CPUs and 0 GPUs.
Connection to socket failed for pathname /tmp/plasma_store91700744
Connection to socket failed for pathname /tmp/plasma_store91700744
Could not connect to socket /tmp/plasma_store91700744
Could not connect to socket /tmp/plasma_store91700744
Could not connect to socket /tmp/plasma_store91700744
user@ubuntu:~$ [WARN] (/ray/src/global_scheduler/global_scheduler.cc:414) Missed too many heartbeats from local scheduler, marking as dead.
WARNING:root:Removed local_scheduler, client ID 3bd98b30a464964f69df98d9b6ccdfbb23babb16
```

Note the line about the local scheduler being removed is printed in the background after Ray has already crashed.

Strangely, if I build Ray from source (at the same commit), the problem doesn't happen. This seems to only happen when I install Ray with pip.

This is probably the same problem reported in the comment https://github.com/ray-project/ray/pull/628#issuecomment-306431756.

**Comment by robertnishihara** [comment]
Starting the plasma store on its own with

```
./python/ray/core/src/plasma/plasma_store \
    -s /tmp/s1 \
    -m 1000000000
```

crashes with

```
Allowing the Plasma store to use up to 1GB of memory.
Illegal instruction (core dumped)
```

Starting the plasma store in GDB gives the following backtrace.

```
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./core/src/plasma/plasma_store...done.
(gdb) run -s /tmp/s1 -m 1000000000
Starting program: /home/user/.local/lib/python2.7/site-packages/ray/core/src/plasma/plasma_store -s /tmp/s1 -m 1000000000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Allowing the Plasma store to use up to 1GB of memory.

Program received signal SIGILL, Illegal instruction.
0x00000000004257d8 in dlmalloc_set_footprint_limit ()
(gdb) bt
#0  0x00000000004257d8 in dlmalloc_set_footprint_limit ()
#1  0x000000000040b20b in main ()
(gdb)
```

So it looks like something is going wrong with dlmalloc and the way we are building wheels.

cc @rshin.

**Comment by robertnishihara** [comment]
The core problem appears to have been the use of the `-mtune` and `-march` compiler flags.

After removing those (on top of the 0.1.1 release) and rebuilding the Linux Python 2.7 wheel, the problem seems to have gone away.

Note that we will still need to build new wheels and push them to pip in order to address this problem.

**Comment by pcmoritz** [comment]
Just to provide a bit more of context on this: If mtune/march are "native", the compiler will apply optimizations and use instructions that are specific to the architecture/cpu model of the machine that Ray has been built. For building the wheels this is not what we want, because the resulting binaries should run on a variety of different machines; we should try to understand the performance implications of these optimizations better and figure out flags that work on a wide variety of modern machines (like using SSE is probably fine, and it might make the memcopy a bunch faster).

If the user runs Ray on a set of homogenous machines and wants maximum performance, building Ray from source with mtune/march as "native" is a very reasonable thing to do.

**Comment by rshin** [comment]
I believe x86-64 mandates SSE2 and all earlier extensions. I would have guessed that Ray is not going to benefit too much from using the newer instructions, since they are mostly for SIMD computations. You may also want to avoid using -O3 over -O2 unless concrete benchmarks show that it is better; my understanding is that the optimizations it enables will only sometimes increase performance and often make it somewhat worse, because they increase code size.

**Comment by robertnishihara** [comment]
Ok, I just pushed new wheels to PyPI (after #700), so this problem should be fixed now.
