### ISSUE TITLE
Problem with deploying on slurm

### ISSUE THREAD

**Issue by Hailey-Liu** [ray-project/ray#6978]
Hello all, 

I encounter the following error when try to run the [slurm example](https://ray.readthedocs.io/en/latest/deploying-on-slurm.html) on a cluster managed by slurm. 

Ray version: 0.8.1
Python version: 3.7.5

```
Traceback (most recent call last):
  File "/home/hliu46/.conda/envs/NP_DL/bin/ray", line 5, in <module>
    from ray.scripts.scripts import main
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/__init__.py", line 104, in <module>
    from ray.worker import (
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/worker.py", line 494, in <module>
srun: error: bhc0007: task 0: Exited with exit code 1
    global_worker = Worker()
srun: Terminating job step 11420439.1
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/worker.py", line 120, in __init__
    self.original_gpu_ids = ray.utils.get_cuda_visible_devices()
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/utils.py", line 274, in get_cuda_visible_devices
    return [int(i) for i in gpu_ids_str.split(",")]
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/utils.py", line 274, in <listcomp>
    return [int(i) for i in gpu_ids_str.split(",")]
ValueError: invalid literal for int() with base 10: 'NoDevFiles'
Traceback (most recent call last):
  File "/home/hliu46/.conda/envs/NP_DL/bin/ray", line 5, in <module>
    from ray.scripts.scripts import main
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/__init__.py", line 104, in <module>
    from ray.worker import (
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/worker.py", line 494, in <module>
    global_worker = Worker()
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/worker.py", line 120, in __init__
    self.original_gpu_ids = ray.utils.get_cuda_visible_devices()
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/utils.py", line 274, in get_cuda_visible_devices
    return [int(i) for i in gpu_ids_str.split(",")]
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/utils.py", line 274, in <listcomp>
    return [int(i) for i in gpu_ids_str.split(",")]
ValueError: invalid literal for int() with base 10: 'NoDevFiles'
srun: error: bhc0008: task 0: Exited with exit code 1
srun: Terminating job step 11420439.2
slurmstepd: error: task/cgroup: unable to add task[pid=458] to memory cg '(null)'
Traceback (most recent call last):
  File "/home/hliu46/.conda/envs/NP_DL/bin/ray", line 5, in <module>
    from ray.scripts.scripts import main
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/__init__.py", line 104, in <module>
    from ray.worker import (
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/worker.py", line 494, in <module>
    global_worker = Worker()
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/worker.py", line 120, in __init__
    self.original_gpu_ids = ray.utils.get_cuda_visible_devices()
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/utils.py", line 274, in get_cuda_visible_devices
    return [int(i) for i in gpu_ids_str.split(",")]
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/utils.py", line 274, in <listcomp>
    return [int(i) for i in gpu_ids_str.split(",")]
ValueError: invalid literal for int() with base 10: 'NoDevFiles'
srun: error: bhc0009: task 0: Exited with exit code 1
srun: Terminating job step 11420439.3
Traceback (most recent call last):
  File "trainer.py", line 6, in <module>
    import ray
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/__init__.py", line 104, in <module>
    from ray.worker import (
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/worker.py", line 494, in <module>
    global_worker = Worker()
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/worker.py", line 120, in __init__
    self.original_gpu_ids = ray.utils.get_cuda_visible_devices()
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/utils.py", line 274, in get_cuda_visible_devices
    return [int(i) for i in gpu_ids_str.split(",")]
  File "/home/hliu46/.conda/envs/NP_DL/lib/python3.7/site-packages/ray/utils.py", line 274, in <listcomp>
    return [int(i) for i in gpu_ids_str.split(",")]
ValueError: invalid literal for int() with base 10: 'NoDevFiles'
```

**Comment by antonwnk** [comment]
The error seems to be SLURM-related, specifically, the CUDA_VISIBLE_DEVICES variable looks like it's being set to 'NoDevFiles'.
These came up when googling for it: [[1]](https://bugs.schedmd.com/show_bug.cgi?id=2626), [[2]](https://www.cs.vu.nl/das/gpu.shtml), [[3]](https://serverfault.com/questions/685258/why-does-requesting-gpus-as-a-generic-resource-on-a-cluster-running-slurm-with-t) - hope it's helpful.

**Comment by Hailey-Liu** [comment]
I just solved this question. I did a couple of things and I am not sure which one solves it.

- reinstall Ray with the Latest Snapshots (Nightlies)
- extend the sleep time from 5s to 30s in this [slurm example](https://ray.readthedocs.io/en/latest/deploying-on-slurm.html)
- add `#SBATCH --time=0-10:00:00` (add time limit otherwise I received time limit error)
