### ISSUE TITLE
Building from source fails on pyarrow setup

### ISSUE THREAD

**Issue by roireshef** [ray-project/ray#7001]
### What is the problem?

Trying to install ray from source by running "pip install" (no conda nor virtualenv, on plain Ubuntu) fails while building with the following exception:
```
    + /usr/bin/python3 -m pip install -q --target=/home/roi/code/ray/python/ray/pyarrow_files pyarrow==0.14.0.RAY --find-links https://s3-us-west-2.amazonaws.com/arrow-wheels/3a11193d9530fe8ec7fdb98057f853b708f6f6ae/index.html
    Exception:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
        status = self.run(options, args)
      File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
        prefix=options.prefix_path,
      File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
        **kwargs
      File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
        self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
      File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
        isolated=self.isolated,
      File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
        prefix=prefix,
      File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
        i.finalize_options()
      File "/usr/lib/python3.6/distutils/command/install.py", line 274, in finalize_options
        raise DistutilsOptionError("can't combine user with prefix, "
    distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
```

This issue is probably a pip abuse (trying to use both _--user_ (implicitly?) and _--target_ (explicitly) flags) discussed in [here](https://askubuntu.com/questions/924564/installing-python-packages-using-pip)

### This issue can be circumvented by running the following installation manually:
`/usr/bin/python3 -m pip install --system --target=_**<ray_dir>**_/python/ray/pyarrow_files pyarrow==0.14.0.RAY --find-links https://s3-us-west-2.amazonaws.com/arrow-wheels/3a11193d9530fe8ec7fdb98057f853b708f6f6ae/index.html`

then running:
```
export SKIP_PYARROW_INSTALL=1
pip install -e . --verbose --system
```

**But this probably should taken into account in setup.py to allow a more seamless installation.**

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ubuntu version: Ubuntu 18.04.1 LTS (bionic)
Python version:  3.6.8

### Reproduction (REQUIRED)
```
# Install Ray.
cd ray/python
pip install -e . --verbose  # Add --user if you see a permission denied error.
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by ijrsvt** [comment]
This should be fixed now. Pyarrow is removed from master and will be in the next release.
@simon-mo

**Comment by mvphilip** [comment]
This same problem happens to me. I can file another issue if required. I have identical OS and python
spec as original filer and also not using conda or virtual env. I am installing as user however.

I cloned the repo and I'm running:

pip3 install -e . --verbose --user 

The same error (can't combine user with prefix, exec_prefix/home, or install_(plat)base) happens:

    Exception:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
        status = self.run(options, args)
      File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
        prefix=options.prefix_path,
      File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
        **kwargs
      File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
        self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
      File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
        isolated=self.isolated,
      File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
        prefix=prefix,
      File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
        i.finalize_options()
      File "/usr/lib/python3.6/distutils/command/install.py", line 274, in finalize_options
        raise DistutilsOptionError("can't combine user with prefix, "
    distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base

.....
    subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', '-q', '--target=/home/mvp/Dev/ray/python/ray/thirdparty_files', 'psutil', 'setproctitle==1.1.10']' returned non-zero exit status 2.


thanks,

-mp

**Comment by ijrsvt** [comment]
@mvphilip Could you open a new issue instead?
