### ISSUE TITLE
Test failure in jenkins tests "psutil.NoSuchProcess process no longer exists".

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#712]
I sometimes see errors like the following in the jenkins tests.

```python
Traceback (most recent call last):
  File "/ray/test/jenkins_tests/multi_node_tests/remove_driver_test.py", line 264, in <module>
    cleanup_driver(redis_address, driver_index)
  File "/ray/test/jenkins_tests/multi_node_tests/remove_driver_test.py", line 225, in cleanup_driver
    wait_for_pid_to_exit(pid)
  File "/opt/conda/lib/python2.7/site-packages/ray-0.1.2-py2.7-linux-x86_64.egg/ray/test/test_utils.py", line 130, in wait_for_pid_to_exit
    if not _pid_alive(pid):
  File "/opt/conda/lib/python2.7/site-packages/ray-0.1.2-py2.7-linux-x86_64.egg/ray/test/test_utils.py", line 121, in _pid_alive
    if psutil.Process(pid).status() == psutil.STATUS_ZOMBIE:
  File "/opt/conda/lib/python2.7/site-packages/psutil/__init__.py", line 627, in status
    return self._proc.status()
  File "/opt/conda/lib/python2.7/site-packages/psutil/_pslinux.py", line 968, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=22)
```

The error can be seen in the following log file https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/1164/console.

The following error from https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/1185/console is possibly related.

```python
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/ray-0.1.2-py2.7-linux-x86_64.egg/ray/actor.py", line 82, in fetch_and_register_actor
    unpickled_class = pickle.loads(pickled_class)
  File "/opt/conda/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/opt/conda/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/opt/conda/lib/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
  File "/opt/conda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 840, in subimport
    __import__(name)
  File "/opt/conda/lib/python2.7/site-packages/gym/__init__.py", line 48, in <module>
    sanity_check_dependencies()
  File "/opt/conda/lib/python2.7/site-packages/gym/__init__.py", line 17, in sanity_check_dependencies
    import requests
  File "/opt/conda/lib/python2.7/site-packages/requests/__init__.py", line 63, in <module>
    from . import utils
  File "/opt/conda/lib/python2.7/site-packages/requests/utils.py", line 42, in <module>
    if platform.system() == 'Windows':
  File "/opt/conda/lib/python2.7/platform.py", line 1263, in system
    return uname()[0]
  File "/opt/conda/lib/python2.7/platform.py", line 1230, in uname
    processor = _syscmd_uname('-p','')
  File "/opt/conda/lib/python2.7/platform.py", line 965, in _syscmd_uname
    rc = f.close()
IOError: [Errno 10] No child processes
```

The issue may be related to the fact that workers are created by forking the local scheduler, and the local scheduler changes the `SIGCHLD` handler. Signal handlers shouldn't survive a call to `execvp`, but https://stackoverflow.com/questions/2333637/is-it-possible-to-signal-handler-to-survive-after-exec makes it seem like `SIGCHLD` may be an exception.

The connection between the error message and the `SIGCHLD` handler is suggested by https://github.com/tornadoweb/tornado/issues/1160.

**Comment by robertnishihara** [comment]
After experimenting with the issue in #745 (which is fixed by #713), I think this #713 really does address this issue, so I'm closing the issue.
