### ISSUE TITLE
[RLlib] Cannot rollout ES after training.

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#7136]
Using ray 0.8.1. 

Having trained an agent with ES:
```
rllib train --run=ES --env=LunarLander-v2 --checkpoint-freq=10
```

I can't play it. (It works with PPO).

Executing this:
```
rllib rollout checkpoint_50/checkpoint-50 --run ES --env LunarLander-v2 --steps 600
```
results in:
```
2020-02-12 05:41:30,922 INFO trainable.py:423 -- Current state after restoring: {'_iteration': 50, '_timesteps_total': 16979666, '_time_total': 2578.4048051834106, '_episodes_total': None}
Traceback (most recent call last):
  File "/home/andriy/miniconda3/envs/myproj/bin/rllib", line 8, in <module>
    sys.exit(cli())
  File "/home/andriy/miniconda3/envs/myproj/lib/python3.7/site-packages/ray/rllib/scripts.py", line 36, in cli
    rollout.run(options, rollout_parser)
  File "/home/andriy/miniconda3/envs/myproj/lib/python3.7/site-packages/ray/rllib/rollout.py", line 265, in run
    args.no_render, args.monitor)
  File "/home/andriy/miniconda3/envs/myproj/lib/python3.7/site-packages/ray/rllib/rollout.py", line 364, in rollout
    prev_action=prev_actions[agent_id],
  File "/home/andriy/miniconda3/envs/myproj/lib/python3.7/site-packages/ray/rllib/rollout.py", line 272, in __missing__
    self[key] = value = self.default_factory(key)
  File "/home/andriy/miniconda3/envs/myproj/lib/python3.7/site-packages/ray/rllib/rollout.py", line 340, in <lambda>
    lambda agent_id: action_init[mapping_cache[agent_id]])
NameError: free variable 'action_init' referenced before assignment in enclosing scope
```

**Comment by sven1977** [comment]
I'll take a look.

**Comment by sven1977** [comment]
Thanks for filing this issue @drozzy!
This PR fixes the problem. It was a bug in our rollout.py script affecting all agents (ARS as well) that do not have a `self.workers` property.

https://github.com/ray-project/ray/pull/7444

Closing this issue.
