### ISSUE TITLE
A3C example fails with "FileNotFoundError: [Errno 2] No such file or directory".

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#714]
If I run the following (using Python 3)

```
python python/ray/rllib/a3c/example.py
```

It fails with

```python
Traceback (most recent call last):
  File "python/ray/rllib/a3c/example.py", line 30, in <module>
    a3c = A3C(args.environment, config)
  File "/Users/rkn/Workspace/ray/python/ray/rllib/a3c/a3c.py", line 87, in __init__
    Algorithm.__init__(self, env_name, config)
  File "/Users/rkn/Workspace/ray/python/ray/rllib/common.py", line 41, in __init__
    dir="/tmp/ray")
  File "/Users/rkn/anaconda3/lib/python3.6/tempfile.py", line 368, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/PongDeterministic-v3_A3C_2017-07-07_17-08-28f49y6ar0'
```

With Python 2, the error is similar.

```python
Traceback (most recent call last):
  File "/ray/python/ray/rllib/a3c/example.py", line 30, in <module>
    a3c = A3C(args.environment, config)
  File "/opt/conda/lib/python2.7/site-packages/ray-0.1.2-py2.7-linux-x86_64.egg/ray/rllib/a3c/a3c.py", line 87, in __init__
    Algorithm.__init__(self, env_name, config)
  File "/opt/conda/lib/python2.7/site-packages/ray-0.1.2-py2.7-linux-x86_64.egg/ray/rllib/common.py", line 41, in __init__
    dir="/tmp/ray")
  File "/opt/conda/lib/python2.7/tempfile.py", line 339, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 2] No such file or directory: '/tmp/ray/PongDeterministic-v3_A3C_2017-07-05_23-01-28syKEz4'
```

It looks like the problem is that we are calling 

```python
    self.logdir = tempfile.mkdtemp(
        prefix="{}_{}_{}".format(
            env_name,
            self.__class__.__name__,
            datetime.today().strftime("%Y-%m-%d_%H-%M-%S")),
        dir="/tmp/ray")
```

but the directory `/tmp/ray` does not exist.

Looks like this was introduced in #706.

cc @ericl

**Comment by robertnishihara** [comment]
Fixed by #715.
