### ISSUE TITLE
[Travis] ci/travis/install-ray.sh fails sometimes.

### ISSUE THREAD

**Issue by sven1977** [ray-project/ray#7141]
We are getting this in our Travis builds sometimes (different jobs), when ci/travis/install-ray.sh is run. Seems to happen randomly, occasionally in different jobs:

```
Installed /home/travis/.local/lib/python3.6/site-packages/aiohttp-4.0.0a1-py3.6-linux-x86_64.egg
2548Searching for py-spy>=0.2.0
2549Reading https://pypi.org/simple/py-spy/
2550Downloading https://files.pythonhosted.org/packages/4f/a2/ebd4e717eba57a8192834497411822c5ec8597287f50c4ec034d1cfe47b1/py_spy-0.3.2-py2.py3-none-manylinux1_x86_64.whl#sha256=888d0906be1f79c9669e7df608979f70aa75609631a0c2a0ffc7b3ab03a5efaa
2551Best match: py-spy 0.3.2
2552Processing py_spy-0.3.2-py2.py3-none-manylinux1_x86_64.whl
2553Installing py_spy-0.3.2-py2.py3-none-manylinux1_x86_64.whl to /home/travis/.local/lib/python3.6/site-packages
2554Adding py-spy 0.3.2 to easy-install.pth file
2555Traceback (most recent call last):
2556  File "setup.py", line 222, in <module>
2557    license="Apache 2.0")
2558  File "/home/travis/miniconda/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
2559    return distutils.core.setup(**attrs)
2560  File "/home/travis/miniconda/lib/python3.6/distutils/core.py", line 148, in setup
2561    dist.run_commands()
2562  File "/home/travis/miniconda/lib/python3.6/distutils/dist.py", line 955, in run_commands
2563    self.run_command(cmd)
2564  File "/home/travis/miniconda/lib/python3.6/distutils/dist.py", line 974, in run_command
2565    cmd_obj.run()
2566  File "/home/travis/miniconda/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
2567    self.do_egg_install()
2568  File "/home/travis/miniconda/lib/python3.6/site-packages/setuptools/command/install.py", line 117, in do_egg_install
2569    cmd.run(show_deprecation=False)
2570  File "/home/travis/miniconda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 425, in run
2571    self.easy_install(spec, not self.no_deps)
2572  File "/home/travis/miniconda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 668, in easy_install
2573    return self.install_item(None, spec, tmpdir, deps, True)
2574  File "/home/travis/miniconda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 715, in install_item
2575    self.process_distribution(spec, dist, deps)
2576  File "/home/travis/miniconda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 760, in process_distribution
2577    [requirement], self.local_index, self.easy_install
2578  File "/home/travis/miniconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
2579    replace_conflicting=replace_conflicting
2580  File "/home/travis/miniconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1066, in best_match
2581    return self.obtain(req, installer)
2582  File "/home/travis/miniconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1078, in obtain
2583    return installer(requirement)
2584  File "/home/travis/miniconda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 687, in easy_install
2585    return self.install_item(spec, dist.location, tmpdir, deps)
2586  File "/home/travis/miniconda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 715, in install_item
2587    self.process_distribution(spec, dist, deps)
2588  File "/home/travis/miniconda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 740, in process_distribution
2589    self.install_egg_scripts(dist)
2590  File "/home/travis/miniconda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 614, in install_egg_scripts
2591    dist.get_metadata('scripts/' + script_name)
2592  File "/home/travis/miniconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1425, in get_metadata
2593    return value.decode('utf-8')
2594UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 24: invalid start byte in scripts/py-spy file at path: /home/travis/.local/lib/python3.6/site-packages/py_spy-0.3.2-py3.6-linux-x86_64.egg/EGG-INFO/scripts/py-spy
(edited
```

e.g. this build:
https://travis-ci.com/ray-project/ray/jobs/286434928

**Comment by simon-mo** [comment]
I will fix this in travis soon. Just in case anyone end up here while debugging, please use
```
pip install ...
```
instead of 
```
python setup.py ...
```
because pip handle binaries images correctly while the `setup.py` execution falsely parse the binary shared object as text data.
