### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by perara** [ray-project/ray#7169]
### What is the problem?
When running experiments across a local cluster (docker) I experience "Too many open files". Running on a relatively large cluster (96*6 cpus)
The first error i experience is:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py", line 239, in start_trial
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py", line 177, in _start_trial
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py", line 75, in _setup_remote_runner
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/trial.py", line 275, in init_logger
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/logger.py", line 400, in __init__
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/logger.py", line 41, in __init__
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/logger.py", line 413, in _init
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/syncer.py", line 269, in get_node_syncer
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/syncer.py", line 138, in __init__
  File "/usr/local/lib/python3.6/dist-packages/ray/services.py", line 282, in get_node_ip_address
  File "/usr/lib/python3.6/socket.py", line 144, in __init__
OSError: [Errno 24] Too many open files
```
Then the application finally exits with: 
```
Traceback (most recent call last):
  File "/workspace/run.py", line 124, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/tune.py", line 388, in run_experiments
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/tune.py", line 303, in run
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/progress_reporter.py", line 71, in report
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/progress_reporter.py", line 83, in memory_debug_str
  File "/usr/local/lib/python3.6/dist-packages/psutil/__init__.py", line 2089, in virtual_memory
  File "/usr/local/lib/python3.6/dist-packages/psutil/_pslinux.py", line 387, in virtual_memory
  File "/usr/local/lib/python3.6/dist-packages/psutil/_common.py", line 587, in open_binary
OSError: [Errno 24] Too many open files: '/proc/meminfo'
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
**Ray**: 0.8.1
**Docker**: ulimit
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 6186284
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 500000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 6186284
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
dict(
        num_workers=1,
        num_envs_per_worker=4,
        num_gpus=0,
        eager=False,
        log_level="ERROR"
 )
```

Where I submit 280 trials (Experiments) via the `tune.run_experiments` function

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
Hm... what if you try turning off log_sync? i.e., in `tune.run`, try setting `sync_to_driver=False`

**Comment by vadimq** [comment]
I had this error and it didn't reproduce with `sync_to_driver=False` (Ray 0.8.3).
