### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'executing_eagerly'

### ISSUE THREAD

**Issue by parthjaggi** [ray-project/ray#7219]
### What is the problem?
On running the command: `rllib train --run=PPO --env=CartPole-v0`

I get the error:
`Traceback (most recent call last):
  File "/home/parth/miniconda3/envs/pyrl/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 424, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/parth/miniconda3/envs/pyrl/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 377, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/parth/miniconda3/envs/pyrl/lib/python3.6/site-packages/ray/worker.py", line 1492, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::PPO.__init__() (pid=24675, ip=192.168.15.107)
  File "python/ray/_raylet.pyx", line 630, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 637, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 638, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 643, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 623, in function_executor
  File "/home/parth/miniconda3/envs/pyrl/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 83, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/parth/miniconda3/envs/pyrl/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 369, in __init__
    if tf and not tf.executing_eagerly():
AttributeError: module 'tensorflow' has no attribute 'executing_eagerly'`

While on changing the command to:
`rllib train --run=PPO --env=CartPole-v0 --eager`
Error changes to:
`AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'`

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version: 0.8.1
Python version: 3.6.10
TensorFlow version: 1.4
OS: Ubuntu 16.04

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
`rllib train --run=PPO --env=CartPole-v0`
`rllib train --run=PPO --env=CartPole-v0 --eager`

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
Are you on TF 1.4? or 1.14? 

If 1.4, please upgrade to 1.14 or above.

**Comment by parthjaggi** [comment]
I am on version: 1.4.1
1. Isn't the 1.4.1 after the 1.15 version?

Also due to my PC being compatible with cuda80 only, this is the latest tensorflow version I can use.
https://miro.medium.com/max/812/1*la5vGjrIwpB4XqDL0FzXxw.png
2. Any workaround to this?

**Comment by parthjaggi** [comment]
I have also tried this using PyTorch version: 1.0.0.
For that I get the following error:
`def sequence_mask(lengths, maxlen, dtype=torch.bool):
AttributeError: module 'torch' has no attribute 'bool'`

Is it possible to use rllib with this version of Pytorch?
Where can I find the version list of TensorFlow and Pytorch that rllib supports?
Thanks.

**Comment by gjoliver** [comment]
closing due to inactivity.
