### ISSUE TITLE
[rllib] Export model failure for TupleActions

### ISSUE THREAD

**Issue by kepricon** [ray-project/ray#7231]
### What is the problem?
I wanted to export a model which has tuple actions.
But I got the `AttributeError: 'TupleActions' object has no attribute 'dtype'` error message while exporting TF model.

*Ray version and other system information (Python version, TensorFlow version, OS):*
OS: Ubuntu 16.04
Python: 3.7
Ray: 0.7.6(also tested with 0.8.1)
TF: 1.13.1(also tested with 1.15.0)

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

I started from https://github.com/ray-project/ray/blob/master/rllib/examples/autoregressive_action_dist.py example
and my script is https://gist.github.com/kepricon/e3d7ffc7eeb1dd1e8193451d7535c02a
I just added `"training_iteration": 5` to quick test export model and added 3 lines(`local_dir`, `checkpoint_at_end`, `export_formats`) at the very end of run config

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by kepricon** [comment]
```
2020-02-19 16:43:34,830	ERROR trial_runner.py:569 -- Error processing event.
Traceback (most recent call last):
  File "/home/kepricon/rescale/conda8/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 563, in _process_trial
    self.trial_executor.export_trial_if_needed(trial)
  File "/home/kepricon/rescale/conda8/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 626, in export_trial_if_needed
    trial.runner.export_model.remote(trial.export_formats))
  File "/home/kepricon/rescale/conda8/lib/python3.7/site-packages/ray/worker.py", line 2121, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray_worker (pid=28565, host=kepricon-G751JL)
  File "/home/kepricon/rescale/conda8/lib/python3.7/site-packages/ray/tune/trainable.py", line 404, in export_model
    return self._export_model(export_formats, export_dir)
  File "/home/kepricon/rescale/conda8/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 810, in _export_model
    self.export_policy_model(path)
  File "/home/kepricon/rescale/conda8/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 690, in export_policy_model
    self.workers.local_worker().export_policy_model(export_dir, policy_id)
  File "/home/kepricon/rescale/conda8/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 718, in export_policy_model
    self.policy_map[policy_id].export_model(export_dir)
  File "/home/kepricon/rescale/conda8/lib/python3.7/site-packages/ray/rllib/policy/tf_policy.py", line 267, in export_model
    signature_def_map = self._build_signature_def()
  File "/home/kepricon/rescale/conda8/lib/python3.7/site-packages/ray/rllib/policy/tf_policy.py", line 407, in _build_signature_def
    tf.saved_model.utils.build_tensor_info(self._sampler)
  File "/home/kepricon/rescale/conda8/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/kepricon/rescale/conda8/lib/python3.7/site-packages/tensorflow/python/saved_model/utils_impl.py", line 58, in build_tensor_info
    dtype=dtypes.as_dtype(tensor.dtype).as_datatype_enum,
AttributeError: 'TupleActions' object has no attribute 'dtype'
```

this is a stack trace for the above error

**Comment by kepricon** [comment]
https://github.com/ray-project/ray/issues/5593#issuecomment-534620856
looks like this guy modified tf_policy.py to stack tuple tensors

**Comment by sven1977** [comment]
Update: This bug is on my TODO list for next week.

**Comment by sven1977** [comment]
PR is out. Waiting only for test results and merging. Will keep this open until confirmed.
https://github.com/ray-project/ray/pull/7333

**Comment by kepricon** [comment]
thank you @sven1977 
do you happen to have a snapshot whl file?

**Comment by kepricon** [comment]
https://ray.readthedocs.io/en/latest/installation.html#latest-snapshots-nightlies

if i install the latest snapshot whl from above link, will it contain the change?
