### ISSUE TITLE
Extract the value of a learner for each timestep in each episode of each iteration

### ISSUE THREAD

**Issue by acxz** [ray-project/ray#7353]
### What is your question?

I would like to plot the estimated value of my network, but I cannot seem to extract it. I can currently get the `vf_loss` per iteration via the logged `result.json` file, but I would like to get the `value` at each timestep for each episode of the iteration, instead of the total `vf_loss`. I feel like this is possible and simple, but I can't seem to find it and log it at all.

**Comment by ericl** [comment]
The value function at each timestep happens to be already recorded via this fetch: https://github.com/ray-project/ray/blob/master/rllib/agents/a3c/a3c_tf_policy.py#L70

You can save this data by specifying "output": "/path/to/save/experiences" in your config, which will dump all the data to that directory.

**Comment by acxz** [comment]
Thank you for the quick response, I will give it a go and let you know how it goes!

**Comment by acxz** [comment]
@ericl So I added `"output" : "/home/apatel435/ray_output"` to my config when I call `ray.run` but I ran into the following error: 

<details>
  <summary>Error</summary>
  
  ```
Failure # 1 (occurred at 2020-02-27_16-09-46)
Traceback (most recent call last):
  File "/home/apatel435/.adt/venv-adt/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 426, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/apatel435/.adt/venv-adt/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 378, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/apatel435/.adt/venv-adt/lib/python3.6/site-packages/ray/worker.py", line 1457, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): [36mray::PPO.train()[39m (pid=7119, ip=10.108.21.69)
  File "python/ray/_raylet.pyx", line 636, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 619, in ray._raylet.execute_task.function_executor
  File "/home/apatel435/.adt/venv-adt/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 444, in train
    raise e
  File "/home/apatel435/.adt/venv-adt/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 433, in train
    result = Trainable.train(self)
  File "/home/apatel435/.adt/venv-adt/lib/python3.6/site-packages/ray/tune/trainable.py", line 176, in train
    result = self._train()
  File "/home/apatel435/.adt/venv-adt/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 129, in _train
    fetches = self.optimizer.step()
  File "/home/apatel435/.adt/venv-adt/lib/python3.6/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 140, in step
    self.num_envs_per_worker, self.train_batch_size)
  File "/home/apatel435/.adt/venv-adt/lib/python3.6/site-packages/ray/rllib/optimizers/rollout.py", line 29, in collect_samples
    next_sample = ray_get_and_free(fut_sample)
  File "/home/apatel435/.adt/venv-adt/lib/python3.6/site-packages/ray/rllib/utils/memory.py", line 33, in ray_get_and_free
    result = ray.get(object_ids)
ray.exceptions.RayTaskError(TypeError): [36mray::RolloutWorker.sample()[39m (pid=7117, ip=10.108.21.69)
  File "python/ray/_raylet.pyx", line 636, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 619, in ray._raylet.execute_task.function_executor
  File "/home/apatel435/.adt/venv-adt/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 493, in sample
    self.output_writer.write(batch)
  File "/home/apatel435/.adt/venv-adt/lib/python3.6/site-packages/ray/rllib/offline/json_writer.py", line 68, in write
    data = _to_json(sample_batch, self.compress_columns)
  File "/home/apatel435/.adt/venv-adt/lib/python3.6/site-packages/ray/rllib/offline/json_writer.py", line 125, in _to_json
    return json.dumps(out)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'int64' is not JSON serializable
  ```
</details>

Note: I am on Ray version 0.8.

**Comment by ericl** [comment]
Could you try with the latest wheels? The following worked for me (Ray latest, TF 2.0):

./train.py --run=PPO  --env=CartPole-v0 --config='{"output": "/tmp/ppo"}'

**Comment by acxz** [comment]
Sorry for getting back to you so late. I tried on the latest wheels and I was able to see the output. I also tried on 0.8.0 and TF v1.14.0 (my current setup) and it worked fine. I think I must be understanding something wrong in parsing the input in my codebase. Thanks for your help!
