### ISSUE TITLE
[RLlib] Failed to train BipedalWalker-v2 using A3C, A2C and IMPALA

### ISSUE THREAD

**Issue by pengzhenghao** [ray-project/ray#7415]
### What is your question?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray: 0.8.2
TensorFlow: 2.1.0
Python: 3.7

It's quite embarrassing that I failed to train BipedalWalker-v2 agents using A2C, A3C and IMPALA algorithms. This is quite strange because PPO, ES, ARS, TD3 can successfully train agents in this environment.

The most common result of training is:

1. Agent returns `nan` and lead to error in the environment: `AssertionError: r.LengthSquared() > 0.0f`
2. Agent's performance never grows up and always stuck to a extremely low reward ~-130.

## Naive A3C
For example, a naive A3C testing via ` rllib train --run A3C --env BipedalWalker-v2 --config '{"num_gpus": 0.2}' --num-samples 5` lead to the following result:

```
== Status ==
Memory usage on this node: 142.4/754.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 15/72 CPUs, 1.0/8 GPUs, 0.0/651.07 GiB heap, 0.0/12.84 GiB objects
Result logdir: /home/XX/ray_results/default
Number of trials: 5 (5 RUNNING)
+-------------------------------+----------+--------------------+----------+------------------+--------+--------+
| Trial name                    | status   | loc                |   reward |   total time (s) |     ts |   iter |
|-------------------------------+----------+--------------------+----------+------------------+--------+--------|
| A3C_BipedalWalker-v2_0d90a28e | RUNNING  | 192.168.205.2:6464 | -129.151 |          424.591 | 359000 |     78 |
| A3C_BipedalWalker-v2_0d910cc4 | RUNNING  | 192.168.205.2:6426 | -127.957 |          428.488 | 364000 |     78 |
| A3C_BipedalWalker-v2_0d915e0e | RUNNING  | 192.168.205.2:6440 | -127.364 |          423.493 | 350000 |     75 |
| A3C_BipedalWalker-v2_0d91a080 | RUNNING  | 192.168.205.2:6429 | -137.948 |          423.429 | 356000 |     76 |
| A3C_BipedalWalker-v2_0d91e07c | RUNNING  | 192.168.205.2:6483 | -137.732 |          422.496 | 360000 |     77 |
+-------------------------------+----------+--------------------+----------+------------------+--------+--------+
```

## A3C with low entropy coefficient
What's worse, by changing the entropy coefficient, the A3C directly fails: `train --run A3C --env BipedalWalker-v2 --config '{"num_gpus": 0.2, "entropy_coeff":0.001}' --num-samples 5`

```
== Status ==
Memory usage on this node: 117.7/754.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 3/72 CPUs, 0.2/8 GPUs, 0.0/632.76 GiB heap, 0.0/12.84 GiB objects
Result logdir: /home/XX/ray_results/default
Number of trials: 5 (1 RUNNING, 4 ERROR)
+-------------------------------+----------+---------------------+----------+------------------+--------+--------+
| Trial name                    | status   | loc                 |   reward |   total time (s) |     ts |   iter |
|-------------------------------+----------+---------------------+----------+------------------+--------+--------|
| A3C_BipedalWalker-v2_9d00662e | RUNNING  | 192.168.205.2:24223 | -110.779 |         111.151  | 111000 |     20 |
| A3C_BipedalWalker-v2_9d00df64 | ERROR    |                     | -116.997 |          27.037  |  23000 |      5 |
| A3C_BipedalWalker-v2_9d012fc8 | ERROR    |                     | -119.268 |          28.067  |  22000 |      5 |
| A3C_BipedalWalker-v2_9d0183e2 | ERROR    |                     | -115.612 |          16.8185 |  11000 |      3 |
| A3C_BipedalWalker-v2_9d035712 | ERROR    |                     | -158.153 |          50.745  |  47000 |      9 |
+-------------------------------+----------+---------------------+----------+------------------+--------+--------+
Number of errored trials: 4
+-------------------------------+--------------+--------------------------------------------------------------------------------------------------------+
| Trial name                    |   # failures | error file                                                                                             |
|-------------------------------+--------------+--------------------------------------------------------------------------------------------------------|
| A3C_BipedalWalker-v2_9d00df64 |            1 | /home/XX/ray_results/default/A3C_BipedalWalker-v2_9d00df64_1_2020-03-03_14-52-577td3k0eh/error.txt |
| A3C_BipedalWalker-v2_9d012fc8 |            1 | /home/XX/ray_results/default/A3C_BipedalWalker-v2_9d012fc8_2_2020-03-03_14-52-57fd1s00q8/error.txt |
| A3C_BipedalWalker-v2_9d0183e2 |            1 | /home/XX/ray_results/default/A3C_BipedalWalker-v2_9d0183e2_3_2020-03-03_14-52-57j7vw0iq5/error.txt |
| A3C_BipedalWalker-v2_9d035712 |            1 | /home/XX/ray_results/default/A3C_BipedalWalker-v2_9d035712_4_2020-03-03_14-52-57gfea30kq/error.txt |
+-------------------------------+--------------+--------------------------------------------------------------------------------------------------------+
```
The error, I assert, is lead to the nan passed into the environment. The complete error message is:

```
Failure # 1 (occurred at 2020-03-03_14-54-00)
Traceback (most recent call last):
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 459, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 377, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/worker.py", line 1504, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): ray::A3C.train() (pid=24239, ip=192.168.205.2)
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 430, in ray._raylet.execute_task.function_executor
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 494, in train
    raise e
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 483, in train
    result = Trainable.train(self)
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/tune/trainable.py", line 254, in train
    result = self._train()
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 133, in _train
    fetches = self.optimizer.step()
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/rllib/optimizers/async_gradients_optimizer.py", line 56, in step
    gradient, info = ray_get_and_free(future)
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/rllib/utils/memory.py", line 29, in ray_get_and_free
    result = ray.get(object_ids)
ray.exceptions.RayTaskError(AssertionError): ray::RolloutWorker.sample() (pid=24252, ip=192.168.205.2)
  File "python/ray/_raylet.pyx", line 440, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 441, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 319, in ray._raylet.deserialize_args
ray.exceptions.RayTaskError: ray::RolloutWorker.sample() (pid=24252, ip=192.168.205.2)
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 430, in ray._raylet.execute_task.function_executor
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 488, in sample
    batches = [self.input_reader.next()]
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 52, in next
    batches = [self.get_data()]
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 202, in get_data
    raise rollout
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 169, in run
    raise e
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 166, in run
    self._run()
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 189, in _run
    item = next(rollout_provider)
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 336, in _env_runner
    base_env.send_actions(actions_to_send)
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/rllib/env/base_env.py", line 328, in send_actions
    self.vector_env.vector_step(action_vector)
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/ray/rllib/env/vector_env.py", line 106, in vector_step
    obs, r, done, info = self.envs[i].step(actions[i])
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/gym/wrappers/time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/sunhao/anaconda3/envs/pzh/lib/python3.7/site-packages/gym/envs/box2d/bipedal_walker.py", line 405, in step
    self.world.RayCast(self.lidar[i], self.lidar[i].p1, self.lidar[i].p2)
AssertionError: r.LengthSquared() > 0.0f
```

## Naive A2C

A2C via `rllib train --run A2C --env BipedalWalker-v2 --config '{"num_gpus": 0.2}' --num-samples 5` leads to:
```
== Status ==
Memory usage on this node: 142.4/754.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 15/72 CPUs, 1.0/8 GPUs, 0.0/638.13 GiB heap, 0.0/12.84 GiB objects
Result logdir: /home/XX/ray_results/default
Number of trials: 5 (5 RUNNING)
+-------------------------------+----------+--------------------+----------+------------------+--------+--------+
| Trial name                    | status   | loc                |   reward |   total time (s) |     ts |   iter |
|-------------------------------+----------+--------------------+----------+------------------+--------+--------|
| A2C_BipedalWalker-v2_1054cf86 | RUNNING  | 192.168.205.2:7539 | -121.611 |          413.508 | 480200 |     41 |
| A2C_BipedalWalker-v2_105530ca | RUNNING  | 192.168.205.2:7563 | -130.369 |          413.483 | 479800 |     41 |
| A2C_BipedalWalker-v2_1055698c | RUNNING  | 192.168.205.2:7554 | -135.07  |          413.309 | 483000 |     41 |
| A2C_BipedalWalker-v2_10559ede | RUNNING  | 192.168.205.2:7546 | -140.756 |          423.838 | 494000 |     42 |
| A2C_BipedalWalker-v2_1055f370 | RUNNING  | 192.168.205.2:7575 | -123.048 |          413.951 | 481000 |     41 |
+-------------------------------+----------+--------------------+----------+------------------+--------+--------+
```

## Naive IMPALA
` rllib train --run IMPALA --env BipedalWalker-v2 --config '{"num_gpus": 0.2}' --num-samples 5`

```
== Status ==
Memory usage on this node: 122.3/754.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 15/72 CPUs, 1.0/8 GPUs, 0.0/651.07 GiB heap, 0.0/12.84 GiB objects
Result logdir: /home/XX/ray_results/default
Number of trials: 5 (5 RUNNING)
+----------------------------------+----------+---------------------+----------+------------------+--------+--------+
| Trial name                       | status   | loc                 |   reward |   total time (s) |     ts |   iter |
|----------------------------------+----------+---------------------+----------+------------------+--------+--------|
| IMPALA_BipedalWalker-v2_72a0066e | RUNNING  | 192.168.205.2:20870 | -129.727 |          568.376 | 920500 |     56 |
| IMPALA_BipedalWalker-v2_72a088be | RUNNING  | 192.168.205.2:20862 | -125.752 |          568.29  | 906500 |     56 |
| IMPALA_BipedalWalker-v2_72a0d81e | RUNNING  | 192.168.205.2:20853 | -123.571 |          578.13  | 952500 |     57 |
| IMPALA_BipedalWalker-v2_72a124ea | RUNNING  | 192.168.205.2:20886 | -132.907 |          568.345 | 918000 |     56 |
| IMPALA_BipedalWalker-v2_72a163f6 | RUNNING  | 192.168.205.2:20860 | -136.814 |          567.959 | 910500 |     56 |
+----------------------------------+----------+---------------------+----------+------------------+--------+--------+
```

## PPO Baseline

As a baseline, we can see that PPO is really learning and the performance is growing.

` rllib train --run PPO --env BipedalWalker-v2 --config '{"num_gpus": 0.2}' --num-samples 5`

```
== Status ==
Memory usage on this node: 99.5/754.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 15/72 CPUs, 1.0/1 GPUs, 0.0/631.15 GiB heap, 0.0/12.84 GiB objects
Result logdir: /home/sunhao/ray_results/default
Number of trials: 5 (5 RUNNING)
+-------------------------------+----------+---------------------+----------+------------------+--------+--------+
| Trial name                    | status   | loc                 |   reward |   total time (s) |     ts |   iter |
|-------------------------------+----------+---------------------+----------+------------------+--------+--------|
| PPO_BipedalWalker-v2_60795da4 | RUNNING  | 192.168.205.2:31840 | -85.8755 |          403.63  | 228000 |     57 |
| PPO_BipedalWalker-v2_6079d586 | RUNNING  | 192.168.205.2:31859 | -28.1547 |          402.136 | 224000 |     56 |
| PPO_BipedalWalker-v2_607a2ce8 | RUNNING  | 192.168.205.2:31880 | -94.1684 |          399.274 | 220000 |     55 |
| PPO_BipedalWalker-v2_607a7234 | RUNNING  | 192.168.205.2:31842 | -41.8211 |          402.068 | 224000 |     56 |
| PPO_BipedalWalker-v2_607abafa | RUNNING  | 192.168.205.2:31850 | -47.3418 |          406.6   | 228000 |     57 |
+-------------------------------+----------+---------------------+----------+------------------+--------+--------+
```

Note:
1. I tried lots of different hyper param setting and the outcome are always within the two possible results.
2. I trained agents for long time (+10 hours), and the performance is not growing at all. The experiments shown here are only the illustration.

**Comment by sven1977** [comment]
Assigning myself. I had some problems with IMPALA as well on Atari yesterday. Seems not right. Will take a look.

**Comment by pengzhenghao** [comment]
I am not sure whether this is related to advantage normalization, because I found all three algorithms do not have this property. I will try to make a comparison on this.

**Comment by pengzhenghao** [comment]
## Advantage Normalization helps A2C!

Adding advantage normalization really help A2C to improve performance drastically. What I do is to modify the `make_policy_optimizer` when building the trainer:

```python
def choose_policy_optimizer_modified(workers, config):
    if config["microbatch_size"]:
        raise ValueError()
    else:
        return SyncSamplesOptimizer(
            workers,
            train_batch_size=config["train_batch_size"],
            standardize_fields=["advantages"]  # <<== Here!
        )
```

```
== Status ==
Memory usage on this node: 141.1/754.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 15/72 CPUs, 1.0/8 GPUs, 0.0/650.83 GiB heap, 0.0/12.84 GiB objects
Result logdir: /home/XX/ray_results/ANA2C
Number of trials: 5 (5 RUNNING)
+---------------------------------+----------+---------------------+----------+------------------+--------+--------+
| Trial name                      | status   | loc                 |   reward |   total time (s) |     ts |   iter |
|---------------------------------+----------+---------------------+----------+------------------+--------+--------|
| ANA2C_BipedalWalker-v2_3cad6880 | RUNNING  | 192.168.205.2:56602 | -94.02   |          675.991 | 782000 |     67 |
| ANA2C_BipedalWalker-v2_3cadde6e | RUNNING  | 192.168.205.2:56582 | -67.6097 |          666.135 | 775600 |     66 |
| ANA2C_BipedalWalker-v2_3cae1fe6 | RUNNING  | 192.168.205.2:56594 | -25.3112 |          665.924 | 772000 |     66 |
| ANA2C_BipedalWalker-v2_3cae5c0e | RUNNING  | 192.168.205.2:56616 | -53.1793 |          665.745 | 774200 |     66 |
| ANA2C_BipedalWalker-v2_3cae97e6 | RUNNING  | 192.168.205.2:56583 | -26.5799 |          665.415 | 777200 |     66 |
+---------------------------------+----------+---------------------+----------+------------------+--------+--------+
```

**Comment by pengzhenghao** [comment]
## Advantage Normalization helps A3C!

```python
def modified_postprocess(policy, sample_batch, other_batches, episode):
    post_batch = postprocess_advantages(
        policy, sample_batch, other_batches, episode)
    array = post_batch["advantages"]
    post_batch["advantages"] = (array - array.mean()) / max(1e-4, array.std())
    return post_batch


def get_policy_class_modified(config):
    if config["use_pytorch"]:
        raise NotImplementedError()
    else:
        return ANA3CTFPolicy


ANA3CTFPolicy = A3CTFPolicy.with_updates(
    name="ANA3CTFPolicy",
    postprocess_fn=modified_postprocess
)

ANA3CTrainer = A3CTrainer.with_updates(
    name="ANA3C",
    default_policy=ANA3CTFPolicy,
    get_policy_class=get_policy_class_modified
)
```

```
== Status ==
Memory usage on this node: 119.3/754.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 15/72 CPUs, 1.0/1 GPUs, 0.0/650.98 GiB heap, 0.0/12.84 GiB objects
Result logdir: /home/sunhao/ray_results/ANA3C
Number of trials: 5 (5 RUNNING)
+---------------------------------+----------+---------------------+-----------+------------------+--------+--------+
| Trial name                      | status   | loc                 |    reward |   total time (s) |     ts |   iter |
|---------------------------------+----------+---------------------+-----------+------------------+--------+--------|
| ANA3C_BipedalWalker-v2_b3f934e4 | RUNNING  | 192.168.205.2:61681 |  -83.3885 |          576.307 | 521000 |    104 |
| ANA3C_BipedalWalker-v2_b3fb8140 | RUNNING  | 192.168.205.2:61627 | -101.417  |          571.604 | 517000 |    103 |
| ANA3C_BipedalWalker-v2_b3fdcd10 | RUNNING  | 192.168.205.2:61672 | -103.524  |          571.981 | 519000 |    102 |
| ANA3C_BipedalWalker-v2_b401a7dc | RUNNING  | 192.168.205.2:61639 |  -25.7807 |          571.57  | 503000 |    106 |
| ANA3C_BipedalWalker-v2_b40640da | RUNNING  | 192.168.205.2:61630 |  -96.1564 |          572.628 | 512000 |    106 |
+---------------------------------+----------+---------------------+-----------+------------------+--------+--------+
```

**Comment by pengzhenghao** [comment]
I have added advantage normalization to all three algorithms. But unfortunately after a long time running the performance is still extremely bad and `AssertionError: r.LengthSquared() > 0.0f` error always happen. 

I am not sure what causes the `nan` in the action. The bug on RLLib or the bug on the environment output (say the nan reward), or maybe some special config on the hyper param.

**Comment by sven1977** [comment]
Hmm, I do have to add though that all A2C/A3C/IMPALA are known to not perform well on the continuous actions domain. SAC is definitely the recommended algo for these cases.
I'll give it a try either way and report back ...

**Comment by pengzhenghao** [comment]
The A3C are still not working in latest 0.8.5... My gym is 0.17.1 Try to run the following codes:

```
rllib train --run A3C --env BipedalWalker-v3 --config '{"num_gpus": 0.2, "entropy_coeff":0.001}' --num-samples 5
```

A3C raise error very quickly.

On the other hand, A2C and IMPALA would not raise error. But they also can't get improvement even trained for sufficient time.

```
rllib train --run IMPALA --env BipedalWalker-v3 --config '{"num_gpus": 0.2}' --num-samples 5
rllib train --run A2C --env BipedalWalker-v3 --config '{"num_gpus": 0.2}' --num-samples 5
```

IMPALA can not provide improvement in 300k steps (for all 5 trials) and the reward goes to -130.

A2C gets -120 reward in 300k steps.

As a comparison, running PPO `rllib train --run PPO --env BipedalWalker-v3 --config '{"num_gpus": 0.2}' --num-samples 5` gives the following performance

```
== Status ==
Memory usage on this node: 21.7/503.8 GiB
Using FIFO scheduling algorithm.
Resources requested: 15/32 CPUs, 1.0/4 GPUs, 0.0/328.96 GiB heap, 0.0/100.0 GiB objects
Result logdir: /home/zhpeng/ray_results/default
Number of trials: 5 (5 RUNNING)
+----------------------------+----------+------------------+--------+------------------+--------+-----------+
| Trial name                 | status   | loc              |   iter |   total time (s) |     ts |    reward |
|----------------------------+----------+------------------+--------+------------------+--------+-----------|
| PPO_BipedalWalker-v3_00000 | RUNNING  | 10.1.72.24:30710 |     75 |          741.955 | 300000 | -84.219   |
| PPO_BipedalWalker-v3_00001 | RUNNING  | 10.1.72.24:30704 |     75 |          750.991 | 300000 |  48.8314  |
| PPO_BipedalWalker-v3_00002 | RUNNING  | 10.1.72.24:30712 |     75 |          745.067 | 300000 |   5.39394 |
| PPO_BipedalWalker-v3_00003 | RUNNING  | 10.1.72.24:30690 |     74 |          743.756 | 296000 |  34.7678  |
| PPO_BipedalWalker-v3_00004 | RUNNING  | 10.1.72.24:30717 |     75 |          742.038 | 300000 | 116.168   |
+----------------------------+----------+------------------+--------+------------------+--------+-----------+
```

I think the difference is not caused by the sample efficiency of different algos.
