### ISSUE TITLE
[tune] TBXLogger fails with tuple argument; how to disable?

### ISSUE THREAD

**Issue by 1Reinier** [ray-project/ray#7435]
Hyperopt provides some hyper parameters in tuple from, which is not supported bij TBX.
```python-traceback
Traceback (most recent call last):
  File "/root/tune.py", line 96, in <module>
    queue_trials=True)
  File "/opt/conda/lib/python3.6/site-packages/ray/tune/tune.py", line 324, in run
    runner.step()
  File "/opt/conda/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 335, in step
    self._process_events()  # blocking
  File "/opt/conda/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 432, in _process_events
    self._process_trial_save(trial)
  File "/opt/conda/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 545, in _process_trial_save
    self._execute_action(trial, decision)
  File "/opt/conda/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 595, in _execute_action
    self.trial_executor.stop_trial(trial)
  File "/opt/conda/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 263, in stop_trial
    trial, error=error, error_msg=error_msg, stop_logger=stop_logger)
  File "/opt/conda/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 204, in _stop_trial
    trial.close_logger()
  File "/opt/conda/lib/python3.6/site-packages/ray/tune/trial.py", line 315, in close_logger
    self.result_logger.close()
  File "/opt/conda/lib/python3.6/site-packages/ray/tune/logger.py", line 305, in close
    _logger.close()
  File "/opt/conda/lib/python3.6/site-packages/ray/tune/logger.py", line 233, in close
    self._try_log_hparams(self.last_result)
  File "/opt/conda/lib/python3.6/site-packages/ray/tune/logger.py", line 244, in _try_log_hparams
    hparam_dict=scrubbed_params, metric_dict=result)
  File "/opt/conda/lib/python3.6/site-packages/tensorboardX/summary.py", line 102, in hparams
    v = make_np(v)[0]
  File "/opt/conda/lib/python3.6/site-packages/tensorboardX/x2num.py", line 34, in make_np
    'Got {}, but expected numpy array or torch tensor.'.format(type(x)))
NotImplementedError: Got <class 'tuple'>, but expected numpy array or torch tensor.
```
How can I disable TBX logging?

**Comment by richardliaw** [comment]
You can disable all loggers via `tune.run(loggers=None)`. You may want to keep the CSVLogger and JSONLogger just in case, and you can do that with 
```python
from ray.tune.loggers import CSVLogger, JSONLogger
tune.run(loggers=[CSVLogger, JSONLogger])
```

(this may have typos but information should be available in the loggers section of the docs)

hope that helps!

**Comment by richardliaw** [comment]
Closing for now. Let me know if this issue still exists on master.
