### ISSUE TITLE
[rllib,tune] Evolution Strategies env_config does not contain rllib metadata such as worker_index

### ISSUE THREAD

**Issue by davebiagioni** [ray-project/ray#7440]
### What is the problem?

The `env_config` for the Evolution Strategies algorithm is not augmented with rllib metadata such as `worker_index`, presumable because it is not wrapped in an `EnvContext` by tune under the hood (?).  This means that ES doesn't conform to this example in the documentation on configuring environments:
[https://ray.readthedocs.io/en/latest/rllib-env.html#configuring-environments](https://ray.readthedocs.io/en/latest/rllib-env.html#configuring-environments)

At a minimum it would be great to call out any algorithms that do not conform so the user isn't re-discovering this issue on their own.  Thanks in advance for any help or suggestions!

### Reproduction (REQUIRED)

PPO Example that WORKS:

```python
import random
import numpy as np

import gym
from gym import spaces

import ray
from ray import tune
from ray.tune.registry import register_env


class TestEnv(gym.Env):
    """Deterministic bandit problem, reward = -action with probability 1."""
    def __init__(self, env_config):
        print(env_config.worker_index)
        self.action_space = spaces.Box(low=0.0, high=1.0, shape=(1,))
        self.observation_space = spaces.Box(low=0.0, high=1.0, shape=(1,))
    def reset(self):
        return self.get_obs()
    def step(self, action):
        print("action: {}".format(action))
        return self.get_obs(), -action[0], True, {}
    def get_obs(self):
        return [random.random()]

ray.init()
register_env("testenv", lambda config: TestEnv(config))
tune.run(
    "PPO",
    config={
        "env": "testenv",
        "num_workers": 2
    }
)
```

Simply changing "PPO" to "ES" in `tune.run` leads to the following error:

```
2020-03-03 22:23:48,946	INFO resource_spec.py:212 -- Starting Ray with 5.22 GiB memory available for workers and up to 2.62 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-03-03 22:23:49,306	INFO services.py:1078 -- View the Ray dashboard at localhost:8265
== Status ==
Memory usage on this node: 8.7/16.0 GiB
Using FIFO scheduling algorithm.
Resources requested: 3/4 CPUs, 0/0 GPUs, 0.0/5.22 GiB heap, 0.0/1.76 GiB objects
Result logdir: /Users/dbiagion/ray_results/ES
Number of trials: 1 (1 RUNNING)
+---------------------+----------+-------+
| Trial name          | status   | loc   |
|---------------------+----------+-------|
| ES_testenv_56b425f8 | RUNNING  |       |
+---------------------+----------+-------+


2020-03-03 22:23:56,604	ERROR trial_runner.py:513 -- Trial ES_testenv_56b425f8: Error processing event.
Traceback (most recent call last):
  File "/Users/dbiagion/anaconda3/envs/carla-rllib-py3.7/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 459, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/Users/dbiagion/anaconda3/envs/carla-rllib-py3.7/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 377, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/Users/dbiagion/anaconda3/envs/carla-rllib-py3.7/lib/python3.7/site-packages/ray/worker.py", line 1504, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::ESTrainer.__init__() (pid=72755, ip=192.168.0.2)
  File "python/ray/_raylet.pyx", line 437, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 450, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 430, in ray._raylet.execute_task.function_executor
  File "/Users/dbiagion/anaconda3/envs/carla-rllib-py3.7/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 447, in __init__
    super().__init__(config, logger_creator)
  File "/Users/dbiagion/anaconda3/envs/carla-rllib-py3.7/lib/python3.7/site-packages/ray/tune/trainable.py", line 172, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/Users/dbiagion/anaconda3/envs/carla-rllib-py3.7/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 591, in _setup
    self._init(self.config, self.env_creator)
  File "/Users/dbiagion/anaconda3/envs/carla-rllib-py3.7/lib/python3.7/site-packages/ray/rllib/agents/es/es.py", line 179, in _init
    env = env_creator(config["env_config"])
  File "test_env_config.py", line 27, in <lambda>
    register_env("testenv", lambda config: TestEnv(config))
  File "test_env_config.py", line 15, in __init__
    print(env_config.worker_index)
AttributeError: 'dict' object has no attribute 'worker_index'
== Status ==
Memory usage on this node: 8.8/16.0 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/4 CPUs, 0/0 GPUs, 0.0/5.22 GiB heap, 0.0/1.76 GiB objects
Result logdir: /Users/dbiagion/ray_results/ES
Number of trials: 1 (1 ERROR)
+---------------------+----------+-------+
| Trial name          | status   | loc   |
|---------------------+----------+-------|
| ES_testenv_56b425f8 | ERROR    |       |
+---------------------+----------+-------+
Number of errored trials: 1
+---------------------+--------------+--------------------------------------------------------------------------------------------+
| Trial name          |   # failures | error file                                                                                 |
|---------------------+--------------+--------------------------------------------------------------------------------------------|
| ES_testenv_56b425f8 |            1 | /Users/dbiagion/ray_results/ES/ES_testenv_56b425f8_0_2020-03-03_22-23-53t9qn2ab_/error.txt |
+---------------------+--------------+--------------------------------------------------------------------------------------------+

Traceback (most recent call last):
  File "test_env_config.py", line 32, in <module>
    "num_workers": 2
  File "/Users/dbiagion/anaconda3/envs/carla-rllib-py3.7/lib/python3.7/site-packages/ray/tune/tune.py", line 345, in run
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [ES_testenv_56b425f8])
(pid=72755) 2020-03-03 22:23:56,596	INFO trainer.py:420 -- Tip: set 'eager': true or the --eager flag to enable TensorFlow eager execution
(pid=72755) 2020-03-03 22:23:56,597	INFO trainer.py:580 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
```

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by sven1977** [comment]
This is fixed in this PR: https://github.com/ray-project/ray/pull/7560
The reason was that ES is using its own Worker class, which would not create an EnvContext object as `env_config` and instead pass the plain `env_config` (as dict) to the `env_creator`.

Closing this issue.

**Comment by davebiagioni** [comment]
Thank you!!
