### ISSUE TITLE
Error when using tensorflow contrib in a remote function.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#745]
The following example fails on Ubuntu (using Python 2, I haven't tested Python 3) with Ray 0.1.2.

```python
import ray

ray.init()

@ray.remote
def f():
    import tensorflow.contrib

f.remote()
```

The error is

```
Traceback (most recent call last):
  File "<ipython-input-1-113f92a4d4d0>", line 7, in f
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/__
    from tensorflow.contrib import factorization
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/fa
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/fa
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/le
    from tensorflow.contrib.learn.python.learn import *
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/le
    from tensorflow.contrib.learn.python.learn import *
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/le
    from tensorflow.contrib.learn.python.learn import estimators
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/le
    from tensorflow.contrib.learn.python.learn.estimators.base import TensorFlow
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/le
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/le
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/ll
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_d
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/le
    import dask.dataframe as dd
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/dask/dataframe/__init
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/dask/dataframe/core.p
    import pandas as pd
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/pandas/__init__.py", 
    from pandas.core.api import *
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/pandas/core/api.py", 
    from pandas.core.groupby import Grouper
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/pandas/core/groupby.p
    from pandas.core.index import (Index, MultiIndex,
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/pandas/core/index.py"
    from pandas.core.indexes.api import *
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/pandas/core/indexes/a
    from pandas.core.indexes.base import (Index, _new_Index,  # noqa
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/pandas/core/indexes/b
    from pandas.core.ops import _comp_method_OBJECT_ARRAY
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/pandas/core/ops.py", 
    import pandas.core.computation.expressions as expressions
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/pandas/core/computati
    import numexpr as ne
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/numexpr/__init__.py",
    from numexpr.tests import test, print_versions
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/numexpr/tests/__init_
    from numexpr.tests.test_numexpr import test, print_versions
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/numexpr/tests/test_nu
    class test_evaluate(TestCase):
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/numexpr/tests/test_nu
    if 'sparc' not in platform.machine():
  File "/home/ubuntu/anaconda2/lib/python2.7/platform.py", line 1302, in machine
    return uname()[4]
  File "/home/ubuntu/anaconda2/lib/python2.7/platform.py", line 1232, in uname
    processor = _syscmd_uname('-p','')
  File "/home/ubuntu/anaconda2/lib/python2.7/platform.py", line 967, in _syscmd_
    rc = f.close()
IOError: [Errno 10] No child processes
```

Note that the error here looks similar to the error in #712, and indeed, I believe this has already been fixed on the master by #713.

Note that a similar error came up in the evolution strategies example in https://github.com/ray-project/ray/pull/719#issuecomment-315670979.

**Comment by robertnishihara** [comment]
Closing because this should be fixed in the current master (by #713), but the problem will still arise for now in the version of Ray that is pip installed (0.1.2).
