### ISSUE TITLE
[tune] Population based training for Mask RCNN - Actor died and unable to restore

### ISSUE THREAD

**Issue by Lakshmisekar** [ray-project/ray#7465]
Python version - 3.6.9
Ray version - 0.7.6
Tensorflow version - 1.10.0

**Background**: I am doing population based training (PBT) for the Mask RCNN with two configs (learning rate and gradient clipping norm. I have four trials (single set of hyperparameter trainings) running in parallel. Here is the goal is minimize the loss, when it see a good trial with a minimum loss it makes the checkpoints (ray objects). When there is trial with more loss then it perturbs from the good one. This is all happening in correct way. Say fitModel_0_GRADIENT_CLIP_NORM=2.0,LEARNING_RATE=0.0001 started well and the training went over 34 iterations (log below showing 34 iteration)

```
== Status ==
PopulationBasedTraining: 7 checkpoints, 2 perturbs
Resources requested: 32/36 CPUs, 8/8 GPUs, 0.0/625.0 GiB heap, 0.0/43.12 GiB objects
Memory usage on this node: 67.6/503.8 GiB
Result logdir: /scratch1/lnatu/training_project/Mask_RCNN/logs/Tuneexp_randomseed0/allupd_pbt_experiment_8gpu_25cpu
Number of trials: 4 ({'RUNNING': 4})
RUNNING trials:
 - **fitModel_0_GRADIENT_CLIP_NORM=2.0,LEARNING_RATE=0.0001@perturbed[GRADIENT_CLIP_NORM=2.0,LEARNING_RATE=0.01048]:                RUNNING, [8 CPUs, 2 GPUs], [pid=24192], 23996 s, 34 iter**
 - fitModel_1_GRADIENT_CLIP_NORM=3.0,LEARNING_RATE=0.0001@perturbed[GRADIENT_CLIP_NORM=3.0,LEARNING_RATE=0.008384]:                RUNNING, [8 CPUs, 2 GPUs], [pid=22606], 24083 s, 35 iter
 - fitModel_2_GRADIENT_CLIP_NORM=2.0,LEARNING_RATE=0.01:             RUNNING, [8 CPUs, 2 GPUs], [pid=22580], 12872 s, 18 iter
 - fitModel_3_GRADIENT_CLIP_NORM=3.0,LEARNING_RATE=0.01:             RUNNING, [8 CPUs, 2 GPUs], [pid=22583], 14962 s, 21 iter
```
 
Then there was some issue and I see the following that ray couldn’t restore the trial from the checkpoint and the actor died.
 
```
_2020-03-04 22:39:31,069              ERROR ray_trial_executor.py:213 -- Error starting runner for Trial fitModel_0_GRADIENT_CLIP_NORM=2.0,LEARNING_RATE=0.0001@perturbed[GRADIENT_CLIP_NORM=2.0,LEARNING_RATE=0.01048]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/trial_runner.py", line 556, in _process_trial
    trial, force=result.get(SHOULD_CHECKPOINT, False))
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/trial_runner.py", line 595, in _checkpoint_trial_if_needed
    self.trial_executor.save(trial, storage=Checkpoint.DISK)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py", line 559, in save
    trial.runner.save.remote())
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 2123, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task._
 
_During handling of the above exception, another exception occurred:_
 
_Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py", line 211, in start_trial
    self._start_trial(trial, checkpoint)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py", line 148, in _start_trial
    str(trial)))
**RuntimeError: Restore from checkpoint failed for Trial fitModel_0_GRADIENT_CLIP_NORM=2.0,LEARNING_RATE=0.0001@perturbed[GRADIENT_CLIP_NORM=2.0,LEARNING_RATE=0.01048].
2020-03-04 22:39:33,248              INFO ray_trial_executor.py:224 -- Trying to start runner for Trial fitModel_0_GRADIENT_CLIP_NORM=2.0,LEARNING_RATE=0.0001@perturbed[GRADIENT_CLIP_NORM=2.0,LEARNING_RATE=0.01048] without checkpoint.**
```
 
Then the trial was again starting from first iteration. If there is an error, ray is supposed to restore the trial from previous checkpoint, if not the training is starting from first iteration and just looping instead of going forward.
 
```
== Status ==
PopulationBasedTraining: 8 checkpoints, 2 perturbs
Resources requested: 32/36 CPUs, 8/8 GPUs, 0.0/625.0 GiB heap, 0.0/43.12 GiB objects
Memory usage on this node: 65.8/503.8 GiB
Result logdir: /scratch1/lnatu/training_project/Mask_RCNN/logs/Tuneexp_randomseed0/allupd_pbt_experiment_8gpu_25cpu
Number of trials: 4 ({'RUNNING': 4})
RUNNING trials:
 - **fitModel_0_GRADIENT_CLIP_NORM=2.0,LEARNING_RATE=0.0001@perturbed[GRADIENT_CLIP_NORM=2.0,LEARNING_RATE=0.01048]:                RUNNING, 2 failures: /scratch1/lnatu/training_project/Mask_RCNN/logs/Tuneexp_randomseed0/allupd_pbt_experiment_8gpu_25cpu/fitModel_0_GRADIENT_CLIP_NORM=2.0,LEARNING_RATE=0.0001_2020-03-04_14-41-313mp1sljg/error_2020-03-04_22-39-33.txt, [8 CPUs, 2 GPUs], [pid=22602], 748 s, 1 iter**
 - fitModel_1_GRADIENT_CLIP_NORM=3.0,LEARNING_RATE=0.0001@perturbed[GRADIENT_CLIP_NORM=3.0,LEARNING_RATE=0.008384]:                RUNNING, [8 CPUs, 2 GPUs], [pid=22606], 27020 s, 39 iter
 - fitModel_2_GRADIENT_CLIP_NORM=2.0,LEARNING_RATE=0.01:             RUNNING, [8 CPUs, 2 GPUs], [pid=22580], 15071 s, 21 iter
 - fitModel_3_GRADIENT_CLIP_NORM=3.0,LEARNING_RATE=0.01:             RUNNING, [8 CPUs, 2 GPUs], [pid=22583], 15736 s, 22 iter
```

**Comment by richardliaw** [comment]
Can you try upgrading to the latest Ray version?

**Comment by utke1** [comment]
The immediate problem is that the network implementation doesn't play with the newer numpy version required by the latest Ray.  We have not yet observed the problem outside of this particular training scenario.

**Comment by amogkam** [comment]
@utke1 were you able to fix this problem? I'm going to close this for now, but feel free to open it again if this is still an issue.
