### ISSUE TITLE
[rllib] how to find bottlenecks?

### ISSUE THREAD

**Issue by yannbouteiller** [ray-project/ray#7527]
Hello,

I am currently trying APEX (with default config dict except config["compress_observations"]=False) on a simple environment that should be fast to step. I use a SLURM cluster (compute candada - calcul quebec) with a node of 40 CPUs and 4 GPUs.

However, the algorithm is apparently under-using the ressources a lot: GPU usage is 0% and all RolloutWorkers seem to be using less than 4% CPU each. Also, an iteration takes 70s although I believe it is supposed to take 30 by default?

The output of the train() function is the following:

> custom_metrics: {}
> date: 2020-03-09_23-46-35
> done: false
> episode_len_mean: 136.72395833333334
> episode_reward_max: 356.90820089174656
> episode_reward_mean: 80.9300610009045
> episode_reward_min: 3.599999999999999
> episodes_this_iter: 192
> episodes_total: 7550
> experiment_id: 8efef92ad7bc412cb1025014027b8cce
> hostname: blg4102.int.ets1.calculquebec.ca
> info:
>   exploration_infos:
>   - 1.0
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   - 0.019999999552965164
>   learner:
>     default_policy:
>       cur_lr: 0.0005000000237487257
>       max_q: 3.419372320175171
>       mean_q: 2.206883192062378
>       mean_td_error: 0.10297185182571411
>       min_q: -0.050455763936042786
>       model: {}
>   learner_queue:
>     size_count: 5057
>     size_mean: 2.3
>     size_quantiles:
>     - 0.0
>     - 0.0
>     - 0.0
>     - 8.100000000000001
>     - 13.0
>     size_std: 3.5397740040855714
>   num_samples_dropped: 229
>   num_steps_sampled: 483250
>   num_steps_trained: 446464
>   num_target_updates: 0
>   num_weight_syncs: 1199
>   replay_shard_0:
>     add_batch_time_ms: 2.845
>     policy_default_policy:
>       added_count: 117950
>       est_size_bytes: 32672150
>       num_entries: 117950
>       sampled_count: 114688
>     replay_time_ms: 926.329
>     update_priorities_time_ms: 2410.944
>   sample_throughput: 483.927
>   train_throughput: 198.216
> iterations_since_restore: 19
> node_ip: 10.70.14.2
> num_healthy_workers: 32
> off_policy_estimator: {}
> perf:
>   cpu_util_percent: 2.639130434782609
>   gpu_util_percent0: 0.0
>   gpu_util_percent1: 0.0
>   gpu_util_percent2: 0.0
>   gpu_util_percent3: 0.0
>   ram_util_percent: 14.760869565217394
>   vram_util_percent0: 0.01955445544554456
>   vram_util_percent1: 0.01955445544554456
>   vram_util_percent2: 0.01955445544554456
>   vram_util_percent3: 0.01955445544554456
> pid: 188296
> policy_reward_max: {}
> policy_reward_mean: {}
> policy_reward_min: {}
> sampler_perf:
>   mean_env_wait_ms: 0.2685339118590942
>   mean_inference_ms: 74.63701378739843
>   mean_processing_ms: 4.5610071777665055
> time_since_restore: 1629.1816799640656
> time_this_iter_s: 68.47089767456055
> time_total_s: 1629.1816799640656
> timestamp: 1583811995
> timesteps_since_restore: 483250
> timesteps_this_iter: 25400
> timesteps_total: 483250
> training_iteration: 19

How can I find the bottleneck in this system, please?

Best regards,
Yann

Ray version: 0.8.2

**Comment by ericl** [comment]
> mean_inference_ms: 74.63701378739843

This seems to indicate model inference is the bottleneck (this is done on CPUs in the rollout workers). 70 millis seems like quite a lot, is your model very large?

**Comment by yannbouteiller** [comment]
Hi @ericl , thank you for your answer.

Actually no, I am using the default FC model, this is a very simple environment with a small observation space. However, I think the issue is more with how compute canada works. I tried to run the following in command line:

```bash
rllib train --run=APEX --env=PongNoFrameskip-v4
```

And I got this error:

> 2020-03-10 14:44:35,519	ERROR trial_runner.py:513 -- Trial APEX_PongNoFrameskip-v4_0c23ec04: Error processing event.
> Traceback (most recent call last):
>   File "/scratch/yannbout/miniconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 459, in _process_trial
>     result = self.trial_executor.fetch_result(trial)
>   File "/scratch/yannbout/miniconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 377, in fetch_result
>     result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
>   File "/scratch/yannbout/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1504, in get
>     raise value.as_instanceof_cause()
> ray.exceptions.RayTaskError(RuntimeError): ray::APEX.__init__() (pid=29673, ip=10.70.14.4)
>   File "python/ray/_raylet.pyx", line 437, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 450, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 430, in ray._raylet.execute_task.function_executor
>   File "/scratch/yannbout/miniconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 86, in __init__
>     Trainer.__init__(self, config, env, logger_creator)
>   File "/scratch/yannbout/miniconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 447, in __init__
>     super().__init__(config, logger_creator)
>   File "/scratch/yannbout/miniconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 172, in __init__
>     self._setup(copy.deepcopy(self.config))
>   File "/scratch/yannbout/miniconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 591, in _setup
>     self._init(self.config, self.env_creator)
>   File "/scratch/yannbout/miniconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 102, in _init
>     self.workers = make_workers(self, env_creator, policy, config)
>   File "/scratch/yannbout/miniconda3/lib/python3.7/site-packages/ray/rllib/agents/dqn/apex.py", line 37, in defer_make_workers
>     return trainer._make_workers(env_creator, policy, config, 0)
>   File "/scratch/yannbout/miniconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 658, in _make_workers
>     logdir=self.logdir)
>   File "/scratch/yannbout/miniconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 60, in __init__
>     RolloutWorker, env_creator, policy, 0, self._local_config)
>   File "/scratch/yannbout/miniconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 262, in _make_worker
>     _fake_sampler=config.get("_fake_sampler", False))
>   File "/scratch/yannbout/miniconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 365, in __init__
>     "GPUs were assigned to this worker by Ray, but "
> RuntimeError: GPUs were assigned to this worker by Ray, but TensorFlow reports GPU acceleration is disabled. This could be due to a bad CUDA or TF installation.
> == Status ==
> Memory usage on this node: 14.1/187.4 GiB
> Using FIFO scheduling algorithm.
> Resources requested: 0/40 CPUs, 0/4 GPUs, 0.0/157.13 GiB heap, 0.0/12.84 GiB objects
> Result logdir: /home/yannbout/ray_results/default
> Number of trials: 1 (1 ERROR)
> +----------------------------------+----------+-------+
> | Trial name                       | status   | loc   |
> |----------------------------------+----------+-------|
> | APEX_PongNoFrameskip-v4_0c23ec04 | ERROR    |       |
> +----------------------------------+----------+-------+
> Number of errored trials: 1
> +----------------------------------+--------------+-------------------------------------------------------------------------------------------------------------+
> | Trial name                       |   # failures | error file                                                                                                  |
> |----------------------------------+--------------+-------------------------------------------------------------------------------------------------------------|
> | APEX_PongNoFrameskip-v4_0c23ec04 |            1 | /home/yannbout/ray_results/default/APEX_PongNoFrameskip-v4_0c23ec04_0_2020-03-10_14-43-34axfowibu/error.txt |
> +----------------------------------+--------------+-------------------------------------------------------------------------------------------------------------+
> 
> == Status ==
> Memory usage on this node: 14.1/187.4 GiB
> Using FIFO scheduling algorithm.
> Resources requested: 0/40 CPUs, 0/4 GPUs, 0.0/157.13 GiB heap, 0.0/12.84 GiB objects
> Result logdir: /home/yannbout/ray_results/default
> Number of trials: 1 (1 ERROR)
> +----------------------------------+----------+-------+
> | Trial name                       | status   | loc   |
> |----------------------------------+----------+-------|
> | APEX_PongNoFrameskip-v4_0c23ec04 | ERROR    |       |
> +----------------------------------+----------+-------+
> Number of errored trials: 1
> +----------------------------------+--------------+-------------------------------------------------------------------------------------------------------------+
> | Trial name                       |   # failures | error file                                                                                                  |
> |----------------------------------+--------------+-------------------------------------------------------------------------------------------------------------|
> | APEX_PongNoFrameskip-v4_0c23ec04 |            1 | /home/yannbout/ray_results/default/APEX_PongNoFrameskip-v4_0c23ec04_0_2020-03-10_14-43-34axfowibu/error.txt |
> +----------------------------------+--------------+-------------------------------------------------------------------------------------------------------------+
> 
> Traceback (most recent call last):
>   File "/scratch/yannbout/miniconda3/bin/rllib", line 8, in <module>
>     sys.exit(cli())
>   File "/scratch/yannbout/miniconda3/lib/python3.7/site-packages/ray/rllib/scripts.py", line 34, in cli
>     train.run(options, train_parser)
>   File "/scratch/yannbout/miniconda3/lib/python3.7/site-packages/ray/rllib/train.py", line 212, in run
>     concurrent=True)
>   File "/scratch/yannbout/miniconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 412, in run_experiments
>     return_trials=True)
>   File "/scratch/yannbout/miniconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 345, in run
>     raise TuneError("Trials did not complete", errored_trials)
> ray.tune.error.TuneError: ('Trials did not complete', [APEX_PongNoFrameskip-v4_0c23ec04])
> ^C
> [1]+  Exit 1                  rllib train --run=APEX --env=PongNoFrameskip-v4

Maybe this is linked to my bottleneck when I call

```python
trainer = agents.dqn.ApexTrainer(env="my_env", config=config)
# (...)
trainer.train()
```
?

Also on ray.init() I get failure to connect to the redis server 3-4 times before it successfully connects.

**Comment by ericl** [comment]
> RuntimeError: GPUs were assigned to this worker by Ray, but TensorFlow reports GPU acceleration is disabled. This could be due to a bad CUDA or TF installation.

^ I think this is the relevant message. It's probably a installation issue -- does TF have GPU acceleration outside Ray?

**Comment by yannbouteiller** [comment]
Yes, there was an installation problem indeed. I fixed this, but this was unrelated to the initial bottleneck (oddly, the trainer.train() function was running even with the broken TF installation)

Now tensorflow is installed correctly and the command line works, but I still get the same very slow performance with huge under-usage of resources, both when executing my training script and when running

```python
rllib train --run=APEX --env=PongNoFrameskip-v4
```
in command line. Only the GPU usage is now 0.0005%, 0.0%, 0.0%, 0.0% instead of 0.0% everywhere (I use the default so only 1 GPU is used)

The 40 CPU cores are 2 x Intel Gold 6148 Skylake @ 2.4 GHz, and the default FC model is used for an observation space:
```python
Dict({
'1': spaces.Box(low=0.0, high=1.0, shape=(5,)),
'2': spaces.Box(low=0.0, high=1.0, shape=(5,))
})
```
and an action space:
```python
Discrete(6)
```

This doesn't explain this inference bottleneck, does it?
Also why is the training iteration twice as long as it is supposed to be?

I really have a hard time finding the bottlenecks with rllib, these time metrics are useful but not really sufficient imo. With the way I am using compute canada right now I would expect the bottleneck to be more in network communications, but that is a really wild guess.

**Comment by Bam4d** [comment]
I'm also facing an inference bottleneck running IMPALA on Skylake Intel Gold 6142. even when pushing inference onto GPUs its still super slow, So i *think* there may be some sort of resource contention?

Here's 4 similar jobs, 3 of which (the slow ones) are running on 8 `6142` cores (seperated with linux cgroups). The super fast one is running on a i7 6800K (orange line). (all configured for cpu inference on 8 workers with 5 envs per worker). As you can see the i7 is running significantly faster inference than the others. 
![image](https://user-images.githubusercontent.com/1370765/112064336-b4b4d700-8b5a-11eb-89d6-af9078dbb777.png)

In total, i get about 5x the sample rate on my desktop PC at home than using a cluster. Are there known issues with xeon gold cores and rllib? I'd think possibly there is a memory bottleneck or some sort of contention, but it would be great to know how to debug this incase there's something i can do in config to fix this.

Thanks

**Comment by Bam4d** [comment]
@yannbouteiller did you try setting the following environment variables? I gained a huge (10x) speedup with these, due to the fact that RLLib spawns seperate processes for inference in per-environment in things like APEX/IMPALA. having the following vairables set to >1 will cause num_workers*NUM_THREADS to be spawned across the multiple processes which wreaks havoc with mkl/blas etc.

```
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export OMP_NUM_THREADS=1
```

**Comment by Rohan138** [comment]
Closing due to inactivity; we merged configurations for OMP_NUM_THREADS in https://github.com/ray-project/ray/issues/7287. If regressions occur, please feel free to open a new issue.
