### ISSUE TITLE
Recursion with pickling in ray.init with py3.5

### ISSUE THREAD

**Issue by yncxcw** [ray-project/ray#7605]
### What is the problem?
I got the following error when running following code:

```python
import ray
ray.init()
```
```
Traceback (most recent call last):
  File "ran_test.py", line 2, in <module>
    ray.init()
  File "/home/weich/.local/lib/python3.5/site-packages/ray/worker.py", line 805, in init
    if _internal_config else {})
  File "/home/weich/.local/lib/python3.5/site-packages/ray/worker.py", line 1259, in connect
    worker.put_object(1, object_id=temporary_object_id)
  File "/home/weich/.local/lib/python3.5/site-packages/ray/worker.py", line 272, in put_object
    serialized_value = self.get_serialization_context().serialize(value)
  File "/home/weich/.local/lib/python3.5/site-packages/ray/serialization.py", line 353, in serialize
    value, protocol=5, buffer_callback=writer.buffer_callback)
  File "/home/weich/.local/lib/python3.5/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 72, in dumps
    cp.dump(obj)
  File "/home/weich/.local/lib/python3.5/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 624, in dump
    raise pickle.PicklingError(msg)
pickle5.pickle.PicklingError: Could not pickle object as excessively deep recursion required.*Ray version and other system information (Python version, TensorFlow version, OS):*
```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Install ray:
```
pip3 install ray
```
Run:
```python
import ray
ray.init()
```

ray version: 0.8.2
python version:  3.5.2

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
Can you please try this on the latest wheels?

**Comment by yncxcw** [comment]
Just tried, it is still broken for me. It worked for my pip2 Install (0.8.0), but not for pip3 install (0.8.2). Maybe a bug for 0.8.2 ?

**Comment by richardliaw** [comment]
Hm, can you try on python3.7 too? `ray.init` works fine on my local machine (and also clean VMs on AWS)

**Comment by yncxcw** [comment]
@richardliaw it worked on python3.7, must be a bug for python3.5 (maybe from some dependencies). Thank you all for the help

**Comment by huntcoder** [comment]
there is a same problem in my computer.
ubuntu 16.04/python3.5/Redis server v=3.0.6

**Comment by gkostkowski** [comment]
I experienced same behavior, with python3.5 and ubuntu16.04

**Comment by stefanbschneider** [comment]
Same here on WSL with Python 3.5.2 and Ray 0.8.5

**Comment by richardliaw** [comment]
cc @suquark

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
