### ISSUE TITLE
[rllib]  execution error of rllib train and rollout of a custom MultiAgentEnv

### ISSUE THREAD

**Issue by suprmat95** [ray-project/ray#7659]
Hello everyone,
I wrote my custom MultiAgentEnv 
`class StockTradingMultiAgent(MultiAgentEnv):` 

I tried to train it by code using tune and by `trainer.train()` and it works correctly. 

But now I want to do some analysis using an environment trained executing a defined number of steps.
So I registered my environment with the id _StockMultiAgent-v0_ . 
So I executed the command:
`rllib train --run PPO --env StockMultiAgent-v0` 
but I got this  error 
> Failure # 1 (occurred at 2020-03-19_13-57-33)
Traceback (most recent call last):
  File "/Users/matteo/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 459, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/Users/matteo/anaconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 377, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/Users/matteo/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1504, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): [36mray::PPO.__init__()[39m (pid=1164, ip=172.20.10.4)
  File "python/ray/_raylet.pyx", line 437, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 450, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 430, in ray._raylet.execute_task.function_executor
  File "/Users/matteo/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 86, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/Users/matteo/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 447, in __init__
    super().__init__(config, logger_creator)
  File "/Users/matteo/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 172, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/Users/matteo/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 591, in _setup
    self._init(self.config, self.env_creator)
  File "/Users/matteo/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 105, in _init
    self.config["num_workers"])
  File "/Users/matteo/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 658, in _make_workers
    logdir=self.logdir)
  File "/Users/matteo/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 60, in __init__
    RolloutWorker, env_creator, policy, 0, self._local_config)
  File "/Users/matteo/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 262, in _make_worker
    _fake_sampler=config.get("_fake_sampler", False))
  File "/Users/matteo/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 282, in __init__
    self.env = _validate_env(env_creator(env_context))
  File "/Users/matteo/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 549, in <lambda>
    self.env_creator = lambda env_config: gym.make(env)
  File "/Users/matteo/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py", line 142, in make
    return registry.make(id, **kwargs)
  File "/Users/matteo/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py", line 87, in make
    env = spec.make(**kwargs)
  File "/Users/matteo/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py", line 62, in make
    env.unwrapped.spec = selAttributeError: 'StockTradingMultiAgent' object has no attribute 'unwrapped'
I have to implement the unwrapped attribute? what it means?

I also tried to execute rllib rollout starting by a checkpoint previously generated by code, but I also got errors. 

Do you have any idea?

Thanks,
Matteo

**Comment by ericl** [comment]
You can't use the gym registry to register custom envs (and they cannot be passed via --run from the command line). See: https://ray.readthedocs.io/en/latest/rllib-env.html#configuring-environments

**Comment by suprmat95** [comment]
Thank you for your answer. Can you suggest me how to do the rollout of my custom environment?
Because I understand how to train it but not how to run it after train.

**Comment by ericl** [comment]
Uncomment this line here to register your custom env: https://github.com/ray-project/ray/blob/master/rllib/rollout.py#L33

**Comment by suprmat95** [comment]
Really thank you, now it's work!
