### ISSUE TITLE
Memory monitor errors in asyncio mode

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#7684]
### What is the problem?
In asyncio, the callstack cannot be retrieved via `inspect.currentframe` because it will error 

```
Exception ignored in: 'ray._raylet.get_py_stack'
Traceback (most recent call last):
  File "/Users/simonmo/miniconda3/lib/python3.6/inspect.py", line 1497, in currentframe
    return sys._getframe(1) if hasattr(sys, "_getframe") else None
ValueError: call stack is not deep enough
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Doc example https://ray.readthedocs.io/en/latest/async_api.html#asyncio-concurrency-for-actors

*Run this in IPython*

```python
import ray
import asyncio
ray.init()

@ray.remote
class AsyncActor:
    # multiple invocation of this method can be running in
    # the event loop at the same time
    async def run_concurrent(self):
        print("started")
        await asyncio.sleep(2) # concurrent workload here
        print("finished")

actor = AsyncActor.remote()

# regular ray.get
ray.get([actor.run_concurrent.remote() for _ in range(4)])

# async ray.get
await actor.run_concurrent.remote()
```

Observe
```
2020-03-21 00:14:42,634	INFO resource_spec.py:212 -- Starting Ray with 23.39 GiB memory available for workers and up to 11.71 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-03-21 00:14:42,987	INFO services.py:1123 -- View the Ray dashboard at localhost:8265
(pid=88430) started
(pid=88430) started
(pid=88430) started
(pid=88430) started
(pid=88430) finished
(pid=88430) finished
(pid=88430) finished
(pid=88430) finished
(pid=88430) started
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/miniconda3/lib/python3.6/inspect.py in currentframe()
   1495 def currentframe():
   1496     """Return the frame of the caller or None if this is not possible."""
-> 1497     return sys._getframe(1) if hasattr(sys, "_getframe") else None
   1498
   1499 def stack(context=1):

ValueError: call stack is not deep enough
Exception ignored in: 'ray._raylet.get_py_stack'
Traceback (most recent call last):
  File "/Users/simonmo/miniconda3/lib/python3.6/inspect.py", line 1497, in currentframe
    return sys._getframe(1) if hasattr(sys, "_getframe") else None
ValueError: call stack is not deep enough
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by simon-mo** [comment]
Seems to be a cython bug https://github.com/cython/cython/issues/2735

**Comment by simon-mo** [comment]
It's known limitation https://cython.readthedocs.io/en/latest/src/userguide/limitations.html#stack-frames, cython code doesn't generate stack frames so when we get_py_stack is called with cython code it failes.

**Comment by simon-mo** [comment]
get_py_stack seems to be called during during asyncio object id integration in cython, in particular the following three functions where we invoked raw `ObjectID` constructor:

https://github.com/ray-project/ray/blob/a7a5d172b1802202be7461f4b74cffe4f6d2a63e/python/ray/_raylet.pyx#L529-L541

https://github.com/ray-project/ray/blob/a7a5d172b1802202be7461f4b74cffe4f6d2a63e/python/ray/_raylet.pyx#L1168-L1188

https://github.com/ray-project/ray/blob/a7a5d172b1802202be7461f4b74cffe4f6d2a63e/python/ray/_raylet.pyx#L1189-L1197

(there also exists similar invocation in `_raylet.pyx` for serializing actor handles, and a helper method)

@stephanie-wang does `ObjectID` construction here invoke ref counting mechanism? If so, what part of the asyncio-object id integration should be changed.

**Comment by simon-mo** [comment]
also cc @ericl
