### ISSUE TITLE
image processing on an image from the webcam

### ISSUE THREAD

**Issue by Mahmoud3zzat** [ray-project/ray#7762]
### Hello,
** I wanna making process on an image from webcam faster,
after trying ray for save frames from the webcam as a test and have error **

`    
    num_cpus = psutil.cpu_count(logical=False)

    @ray.remote(num_cpus=num_cpus)
    def worker(frame):
        imgname = datetime.datetime.fromtimestamp(
            time.time()).strftime('%Y%m%d%H%M%S.%f')
        cv2.imwrite(imgname + ".png", frame)

    def main():
        cap = video.VideoStream(src=0).start()
        while True:
            time.sleep(0.05)
            image = cap.read()
            frame = ray.put(image)
            result_ids = [worker.remote(frame) for i in range(8)]
            results = ray.get(result_ids)
            cv2.imshow("image", image)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break
        cv2.destroyAllWindows()
        cap.stop()
    if __name__ == '__main__':
        main()
`
> Traceback (most recent call last):
  File "/Desktop/test/sts.py", line 41, in <module>
    main()
  File "/Desktop/test/sts.py", line 28, in main
    frame = ray.put(image)
  File "/home/m/.virtualenvs/dl4cv/lib/python3.6/site-packages/ray/worker.py", line 1530, in put
    worker.check_connected()
  File "/home/m/.virtualenvs/dl4cv/lib/python3.6/site-packages/ray/worker.py", line 211, in check_connected
    raise RayConnectionError("Ray has not been started yet. You can "
ray.exceptions.RayConnectionError: Ray has not been started yet. You can start Ray with 'ray.init()'.
FATAL: exception not rethrown
Aborted (core dumped)

**### that`s my first time using ray, and need to make it multiprocessing in the worker to image processing and deep learning problem**

**Comment by Mahmoud3zzat** [comment]
update I solved the error and saving the images 
by adding 
ray.init()    #:D 
now, trying to make a multiprocess and add a deep learning detector any advice in code ????
