### ISSUE TITLE
[Dashboard] Only async functions are allowed as web-handlers

### ISSUE THREAD

**Issue by ConeyLiu** [ray-project/ray#7763]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

Ray: master branch
ray.init() got the following errors:
```
In [3]: 2020-03-27 10:51:44,870 WARNING worker.py:1072 -- The dashboard on node xyliu failed to start with the following error:
Traceback (most recent call last):
  File "/home/lxy/git_repository/ray/python/ray/dashboard/dashboard_main.py", line 64, in main
    redis_password=redis_password)
  File "/home/lxy/miniconda3/envs/ray/lib/python3.6/site-packages/ray-0.9.0.dev0-py3.6-linux-x86_64.egg/ray/dashboard/dashboard.py", line 528, in __init__
    self.app.router.add_get("/{_}", route_handler.get_forbidden)
  File "/home/lxy/miniconda3/envs/ray/lib/python3.6/site-packages/aiohttp-4.0.0a1-py3.6-linux-x86_64.egg/aiohttp/web_urldispatcher.py", line 1069, in add_get
    resource.add_route(hdrs.METH_HEAD, handler, **kwargs)
  File "/home/lxy/miniconda3/envs/ray/lib/python3.6/site-packages/aiohttp-4.0.0a1-py3.6-linux-x86_64.egg/aiohttp/web_urldispatcher.py", line 294, in add_route
    expect_handler=expect_handler)
  File "/home/lxy/miniconda3/envs/ray/lib/python3.6/site-packages/aiohttp-4.0.0a1-py3.6-linux-x86_64.egg/aiohttp/web_urldispatcher.py", line 817, in __init__
    resource=resource)
  File "/home/lxy/miniconda3/envs/ray/lib/python3.6/site-packages/aiohttp-4.0.0a1-py3.6-linux-x86_64.egg/aiohttp/web_urldispatcher.py", line 144, in __init__
    ", got {!r}".format(handler))
TypeError: Only async functions are allowed as web-handlers , got <bound method DashboardRouteHandler.get_forbidden of <ray.dashboard.dashboard.DashboardRouteHandler object at 0x7fe03ae24da0>>
```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
This will fix the issue https://github.com/ray-project/ray/pull/7764. 

I think some aiohttp versions only allows async definition for web-handler.

**Comment by mitchellstern** [comment]
This was fixed by @rkooo567 in https://github.com/ray-project/ray/pull/7766.
