### ISSUE TITLE
`load_code_from_local` is broken?

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#7777]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* Latest, Linux

### Reproduction (REQUIRED)

This just breaks

```
import numpy as np
import time
import ray
import ray.tune
import ray.tune.track

ray.init(ignore_reinit_error=True,
    memory=2000 * 1024 * 1024,
    object_store_memory=200 * 1024 * 1024,
    driver_object_store_memory=100 * 1024 * 1024,
    load_code_from_local=True
)
    
def somefun(config):
    ray.tune.track.log(something=0, test="asdf")
    return res

ray.tune.run(somefun)
```

Here is the error raised:

```
020-03-27 19:46:58,007	WARNING worker.py:1081 -- Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/function_manager.py", line 443, in _load_actor_class_from_local
    actor_class = getattr(module, class_name)
AttributeError: module 'ray.tune.function_runner' has no attribute 'WrappedTrackFunc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 505, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 342, in ray._raylet.execute_task
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/function_manager.py", line 393, in load_actor_class
    job_id, actor_creation_function_descriptor)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/function_manager.py", line 452, in _load_actor_class_from_local
    class_name))
RuntimeError: Actor WrappedTrackFunc failed to be imported from local code.
An unexpected internal error occurred while the worker was executing a task.
2020-03-27 19:46:58,008	WARNING worker.py:1081 -- A worker died or was killed while executing task ffffffffffffffffa1651cc50100.
2020-03-27 19:46:58,009	ERROR trial_runner.py:513 -- Trial somefun_00000: Error processing event.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 459, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 377, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 1516, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
```

Is this being used correctly? Otherwise, the error seems to be misleading.

cc @jovany-wang 

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by jovany-wang** [comment]
FYI @fyrestone

**Comment by fyrestone** [comment]
The `load_code_from_local` may never worked for `ray.tune`, because `ray.tune` always wraps a python function to class `WrappedTrackFunc`, and `WrappedTrackFunc` is a dynamic generated class defined in a function which can't be loaded from source.

**Comment by richardliaw** [comment]
Can we please raise a better error message?
