### ISSUE TITLE
The first Tune tutorial is not working on Linux 5.3 &  Conda 4.8.3

### ISSUE THREAD

**Issue by pranasblk** [ray-project/ray#7801]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

- Python 3.6
- Linux 5.3
- Conda 4.8.3

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Reproduction using https://ray.readthedocs.io/en/latest/tune.html

- `pip install 'ray[tune]' torch torchvision`
- jupyter notebook:
-- `from ray import tune
from ray.tune.examples.mnist_pytorch import get_data_loaders, ConvNet, train, tes`
-- `def train_mnist(config):
    train_loader, test_loader = get_data_loaders()
    model = ConvNet()
    optimizer = optim.SGD(model.parameters(), lr=config["lr"])
    for i in range(10):
        train(model, optimizer, train_loader)
        acc = test(model, test_loader)
        tune.track.log(mean_accuracy=acc)`
-- `analysis = tune.run(
    train_mnist, config={"lr": tune.grid_search([0.001, 0.01, 0.1])})

print("Best config: ", analysis.get_best_config(metric="mean_accuracy"))` 

Result: `2020-03-30 10:51:35,413	ERROR trial_runner.py:512 -- Trial train_mnist_00000: Error processing event.
Traceback (most recent call last):
  File "/home/pranas/miniconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 458, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/pranas/miniconda3/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 381, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/pranas/miniconda3/lib/python3.6/site-packages/ray/worker.py", line 1502, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): ray::WrappedTrackFunc.train() (pid=26546, ip=192.168.20.201)
  File "python/ray/_raylet.pyx", line 445, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 423, in ray._raylet.execute_task.function_executor
  File "/home/pranas/miniconda3/lib/python3.6/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/home/pranas/miniconda3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 216, in _train
    self._report_thread_runner_error(block=True)
  File "/home/pranas/miniconda3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 259, in _report_thread_runner_error
    .format(err_tb_str)))
ray.tune.error.TuneError: Trial raised an exception. Traceback:
ray::WrappedTrackFunc.train() (pid=26546, ip=192.168.20.201)
  File "/home/pranas/miniconda3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 110, in run
    self._entrypoint()
  File "/home/pranas/miniconda3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 162, in entrypoint
    return self._trainable_func(config, self._status_reporter)
  File "/home/pranas/miniconda3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 288, in _trainable_func
    output = train_func(config)
  File "<ipython-input-2-258978b36b85>", line 4, in train_mnist
NameError: name 'optim' is not defined`

If we cannot run your script, we cannot fix your issue.

- [v] I have verified my script runs in a clean environment and reproduces the issue.
Ray has been installed exactly as specified.

- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).
Did not try to deviate from the tutorian in a single bit.

**Comment by richardliaw** [comment]
You missed the first line of the tutorial, where we import `optim`:

```python
import torch.optim as optim
from ray import tune
from ray.tune.examples.mnist_pytorch import get_data_loaders, ConvNet, train, test

...
```

**Comment by pranasblk** [comment]
My sencere applogies. User error - confirmed!
