### ISSUE TITLE
"Lost reference to actor" when returning actor handle from actor

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#7815]
### What is the problem?

When returning an actor handle from an actor, if an actor method is invoked on the returned handle without storing the handle in a local variable, the call fails with `RuntimeError: Lost reference to actor`.

This seems to be related to the `hardref` logic in the internal `ActorMethod` class - if I hardcode `hardref` to `True`, I don't see the issue.

### Reproduction (REQUIRED)

```python
import ray
ray.init()

@ray.remote
class Child:
    def echo(self, arg):
        return arg

@ray.remote
class Parent:
    def __init__(self):
        self.child = Child.remote()

    def get_child(self):
        return [self.child]

parent = Parent.remote()
child = ray.get(parent.get_child.remote())[0]
assert ray.get(child.echo.remote("hello")) == "hello" # Succeeds.
del child

assert ray.get(ray.get(
    parent.get_child.remote())[0].echo.remote("hello")) == "hello" # Fails!
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by edoakes** [comment]
@ericl could you take a look at this?

**Comment by ericl** [comment]
Looks like Python is deleting the actor object before the method could be run. A quick fix would be to make deserialized actor handles always return hard refs, though that would then cause a GC problem for those handles.

**Comment by matiasdahl** [comment]
Below is another example that also gives the "RuntimeError: Lost reference to actor'-error"-error:

```python
import ray

ray.init(num_cpus=2, ignore_reinit_error=True)

@ray.remote(num_cpus=1)
class Foo:        
    def get_value(self):
        return 123

print("* The below works ..")
for _ in range(30):
    actor = Foo.remote()
    assert ray.get(actor.get_value.remote()) == 123

print("* Running command that fails with 'RuntimeError: Lost reference to actor'-error")
print(Foo.remote().get_value.remote())

print("* Done")
```

The full error message is below (running the code inside docker, Ubuntu 20.04, Python 3.8.10 on a linux system):

```
2021-07-18 08:41:25,460 INFO services.py:1272 -- View the Ray dashboard at http://127.0.0.1:8265
2021-07-18 08:41:25,461 WARNING services.py:1730 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
* The below works ..
* Running command that fails with 'RuntimeError: Lost reference to actor'-error
Traceback (most recent call last):
  File "/app/demo.py", line 16, in <module>
    print(Foo.remote().get_value.remote())
  File "/usr/local/lib/python3.8/dist-packages/ray/actor.py", line 115, in remote
    return self._remote(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/util/tracing/tracing_helper.py", line 403, in _start_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/actor.py", line 157, in _remote
    return invocation(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/actor.py", line 145, in invocation
    raise RuntimeError("Lost reference to actor")
RuntimeError: Lost reference to actor
Exception ignored in: <function ActorHandle.__del__ at 0x7f3bf4d62550>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ray/actor.py", line 823, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
```

The last four lines of the error message seem to disappear if one remove the for loop from the example.

**Comment by wuisawesome** [comment]
Bumping the priority of this issue up since it's a quite surprising, and we're hitting it in production. 

The easy mitigation is to always do 

```
actor_handle = ray.get_actor(...)
ray.get(actor_handle.foo.remote())
```

on separate lines.

@scv119 feel free to adjust priority, just retriaging this since it's quite old and our triage process has changed.

**Comment by msingh00** [comment]
what is the status of this?   I am running into this also...My code looks like the line mentioned above:

`print(Foo.remote().get_value.remote())`

Is the solution to not do this and assign the actor instantiation to a local variable?

**Comment by sebastiandero** [comment]
:(

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
