### ISSUE TITLE
[rllib] Preprocessor check_shape fails on negative values

### ISSUE THREAD

**Issue by lennardsnoeks** [ray-project/ray#7834]
### What is your question?

This is my observation space:

        observation_space = spaces.Tuple((
            spaces.Box(low=-55, high=55, shape=(2,)),
            spaces.Box(low=-55, high=55, shape=(3, 21)),
            spaces.Box(low=-55, high=55, shape=(3, 21))
        ))
        
        initial_value = -54
        distances1 = [initial_value] * 21        
        distances2 = [initial_value] * 21

Each array in the second and third box are initialized with values -54, and filled according to distances found in my environment. Sometimes the error occurs immediately (mostly with when initial_value is set to higher negative values like -54), and sometimes it happens after some steps have been taken (mostly with lower negative values like -1). 

This error does not occur when the initial_value parameter is non-negative (0 or higher).  When I run the observation_space.contains(obs) method myself, True is returned for the observation given in this error:

>   File "/home/lennard/anaconda3/envs/env1/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py", line 197, in transform
    self.check_shape(observation)
  File "/home/lennard/anaconda3/envs/env1/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py", line 61, in check_shape
    self._obs_space, observation)
ValueError: ('Observation outside expected value range', Tuple(Box(2,), Box(3, 21), Box(3, 21)), [array([33.,  0.]), array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0],
       [-54, -54, -54, -54, -54, -54, -54, -54, -54, -54, -54, -54, -54,
        -54, -54, -54, -54, -54, -54, -54, -54]]), array([[ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [14.2, 14.2, 14.8, 15.8,  6.4,  6.6, 24. , 31. , 37.4,  8.4, 13.6,
        36. ,  3.8, 31. , 24. , 10. , 17.4, 15.8, 14.8, 14.2, 14.2]])])
Traceback (most recent call last):
  File "/home/lennard/DRL_Crowd_Simulation/crowd-sim-RL/simulations/multi_agent_training_PS.py", line 177, in <module>
    main()
  File "/home/lennard/DRL_Crowd_Simulation/crowd-sim-RL/simulations/multi_agent_training_PS.py", line 29, in main
    train(sim_state, checkpoint)
  File "/home/lennard/DRL_Crowd_Simulation/crowd-sim-RL/simulations/multi_agent_training_PS.py", line 166, in train
    run("DDPG", name=name, checkpoint_freq=checkpoint_freq, stop=stop, config=config)
  File "/home/lennard/anaconda3/envs/env1/lib/python3.7/site-packages/ray/tune/tune.py", line 345, in run
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [DDPG_multi_agent_env_5f939306])

The weird thing is that I cannot seem to replicate this behavior in a simpler environment for a reproduction script. Wanted to ask what could maybe cause this cause it's breaking my head.

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray v0.8.2
also happens in the latest wheels
python v3.7.4

**Comment by lennardsnoeks** [comment]
Needs some further investigation, closing until then. May have been related to something else.
