### ISSUE TITLE
[rllib] ValueError: Reward should be finite scalar, got nan (<class 'float'>)

### ISSUE THREAD

**Issue by devinbarry** [ray-project/ray#7853]
### What is the problem?

IMPALA with MountainCarContinuous-v0 crashes with the above error. There may be other setups that cause the same issue.

Its the same issue reported [here](https://github.com/ray-project/ray/issues/5604). I made a comment on this ticket a few weeks ago, but was told to make a new ticket for it, so here it is:

```
ray.exceptions.RayTaskError(StopIteration): ray::RolloutWorker.sample_with_count() (pid=22945, ip=10.30.30.100)
(pid=22950)   File "python/ray/_raylet.pyx", line 445, in ray._raylet.execute_task
(pid=22950)   File "python/ray/_raylet.pyx", line 423, in ray._raylet.execute_task.function_executor
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 539, in sample_with_count
(pid=22950)     batch = self.sample()
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 492, in sample
(pid=22950)     batches = [self.input_reader.next()]
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 53, in next
(pid=22950)     batches = [self.get_data()]
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 96, in get_data
(pid=22950)     item = next(self.rollout_provider)
(pid=22950) StopIteration
(pid=22950) 2020-04-01 13:29:33,780	ERROR trainer.py:965 -- Blacklisting worker 14
(pid=22950) Traceback (most recent call last):
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 491, in train
(pid=22950)     result = Trainable.train(self)
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/tune/trainable.py", line 261, in train
(pid=22950)     result = self._train()
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 154, in _train
(pid=22950)     fetches = self.optimizer.step()
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/rllib/optimizers/async_samples_optimizer.py", line 132, in step
(pid=22950)     sample_timesteps, train_timesteps = self._step()
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/rllib/optimizers/async_samples_optimizer.py", line 174, in _step
(pid=22950)     for train_batch in self.aggregator.iter_train_batches():
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/rllib/optimizers/aso_aggregator.py", line 116, in iter_train_batches
(pid=22950)     blocking_wait=True, max_yield=max_yield)):
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/rllib/optimizers/aso_aggregator.py", line 169, in _augment_with_replay
(pid=22950)     sample_batch = ray_get_and_free(sample_batch)
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/rllib/utils/memory.py", line 29, in ray_get_and_free
(pid=22950)     result = ray.get(object_ids)
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/worker.py", line 1502, in get
(pid=22950)     raise value.as_instanceof_cause()
(pid=22950) ray.exceptions.RayTaskError(ValueError): ray::RolloutWorker.sample() (pid=22924, ip=10.30.30.100)
(pid=22950)   File "python/ray/_raylet.pyx", line 445, in ray._raylet.execute_task
(pid=22950)   File "python/ray/_raylet.pyx", line 423, in ray._raylet.execute_task.function_executor
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 492, in sample
(pid=22950)     batches = [self.input_reader.next()]
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 53, in next
(pid=22950)     batches = [self.get_data()]
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 96, in get_data
(pid=22950)     item = next(self.rollout_provider)
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 359, in _env_runner
(pid=22950)     base_env.send_actions(actions_to_send)
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/rllib/env/base_env.py", line 328, in send_actions
(pid=22950)     self.vector_env.vector_step(action_vector)
(pid=22950)   File "/home/axion/anaconda3/envs/training/lib/python3.7/site-packages/ray/rllib/env/vector_env.py", line 110, in vector_step
(pid=22950)     r, type(r)))
(pid=22950) ValueError: Reward should be finite scalar, got nan (<class 'float'>)
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python 3.7.7 on Ubuntu 19.04
Also Python 3.7 running inside Docker (both Debian 10 and Ubuntu 18.04 images)
Ray 0.8.3 and earlier versions at least to 0.8.1
Also on the latest nightly version
Tensorflow==2.1.0

### Reproduction (REQUIRED)

This one using AsyncHyperBandScheduler crashes almost immediately
https://gist.github.com/devinbarry/d15dcb4b3d418dcc5d1ad1fb9c44ae44

This one just doing regular training crashes after between 10 and 60 iterations. Just keep running it and it will definitely crash. It never doesn't crash.
https://gist.github.com/devinbarry/1cc0c5aefff77b82e0dcf1e3a295b9a2

I should point out my main training workstation has 32 cores and 1 GPU so CPU and GPU are normally set to 32 and 1 respectively.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by Francesco-Sovrano** [comment]
Dear,

the bug is hard to reproduce because it is caused by numerical issues that happen only when the underlying neural network learns parameters that are too big for a DiagGaussian action distribution. More precisely, if you go at line 227 of  rllib/models/tf/tf_action_dist.py you can see that if log_std is too big (es. > 64) then the predicted action will be a NaN. What is missing is the following line of code `log_std = tf.clip_by_value(log_std, MIN_LOG_NN_OUTPUT, MAX_LOG_NN_OUTPUT)` inserted at least one line before line 227. The same issue is also in torch_action_dist.py .
I tried to push the fix but apparently nobody has seen it. This is an important fix.
Regards,

FS
