### ISSUE TITLE
Auto retrieve redis ip/port on slurm deployment

### ISSUE THREAD

**Issue by zpymyyn** [ray-project/ray#7872]
Hi all,
Following the deployment on slurm instructions, I can get the ray head and workers initiated. 
However, it always failed to receive the respond from redis server right when the script starts to run, like this: 
   ```
Waiting for redis server at 127.0.0.1:64584 to respond
Traceback (most recent call last):
  File "/my-envs/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/my-envs/lib/python3.6/site-packages/redis/connection.py", line 511, in _connect
    socket.SOCK_STREAM):
  File "/my-envs/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
   ...skip
  File "/my-envs/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to 128.214.XX.XX:6379:64584. Name or service not known.
```
And the port after `127.0.0.1` is different every time.

I'm guessing it's because the cluster nodes use dynamic redis port thus there needs a way to auto retrieve the redis port and deploy ray.
Thanks.

**Comment by zpymyyn** [comment]
Ok, seems @deanwampler has mentioned this [issue](https://github.com/ray-project/ray/issues/6573#issuecomment-596100398) in #6573
