### ISSUE TITLE
Tune PPO Policy Fails: "Only TF Graph Policies are supported with multi-gpu"

### ISSUE THREAD

**Issue by rtolsma** [ray-project/ray#7991]
Running ray 0.8.4.

I have a simple multi-agent setup:

```python
if __name__ == "__main__":
    args = parser.parse_args()

    # Simple environment with 4 independent cartpole entities
    register_env("myenv", lambda _: MyEnv())
    test = MyEnv()
    obs_space = test.observation_space
    act_space = test.action_space
    tune.run(
        "PPO",
        stop={"training_iteration": args.num_iters},
        config={
            "env": "myenv",
            "multiagent": {
                "policies": {
                    "learned_policy": (None, obs_space, act_space, {}),
                    "random": (RandomPolicy, obs_space, act_space, {}),
                },  
                "policy_mapping_fn": (
                    lambda agent_id: {1:"learned_policy", 2:"random"}[agent_id]),
            },      
        },  
    )   


```

but when I run this I get the error

```
Traceback (most recent call last):
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 381, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/worker.py", line 1513, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::PPO.__init__() (pid=29677, ip=192.168.1.25)
  File "python/ray/_raylet.pyx", line 414, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 450, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 90, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 455, in __init__
    super().__init__(config, logger_creator)
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/tune/trainable.py", line 174, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 596, in _setup
    self._init(self.config, self.env_creator)
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 129, in _init
    self.optimizer = make_policy_optimizer(self.workers, config)
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/agents/ppo/ppo.py", line 95, in choose_policy_optimizer
    shuffle_sequences=config["shuffle_sequences"])
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 99, in __init__
    "Only TF graph policies are supported with multi-GPU. "
ValueError: Only TF graph policies are supported with multi-GPU. Try setting `simple_optimizer=True` instead.

```

I added the "simple_optimizer:True" to it, but that just gave me a new error

```
Traceback (most recent call last):
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 381, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/worker.py", line 1513, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(NotImplementedError): ray::PPO.train() (pid=29866, ip=192.168.1.25)
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 505, in train
    raise e
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 491, in train
    result = Trainable.train(self)
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 150, in _train
    fetches = self.optimizer.step()
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/optimizers/sync_samples_optimizer.py", line 48, in step
    weights = ray.put(self.workers.local_worker().get_weights())
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 548, in get_weights
    for pid, policy in self.policy_map.items() if pid in policies
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 548, in <dictcomp>
    for pid, policy in self.policy_map.items() if pid in policies
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/policy/policy.py", line 265, in get_weights
    raise NotImplementedError
NotImplementedError

```

For reference, switching out "PPO" with "PG" made things work fine, but others like "SAC" and "APPO" gave me the same difficulties. Does anyone have any idea on how to fix this? Thanks in advance!

Also, as an aside, is there documentation on what all the string abbreviations for the Trainables are? I can't seem to find it anywhere

**Comment by ericl** [comment]
Probably it's just your `RandomPolicy` doesn't implement get_weights()... fix would be to return None there and also add a no-op set_weights().

**Comment by rtolsma** [comment]
> Probably it's just your `RandomPolicy` doesn't implement get_weights()... fix would be to return None there and also add a no-op set_weights().

Thanks so muc! That was definitely an issue. One more question, though, I added those methods to my RandomPolicy class as follows:

```python
class RandomPolicy(Policy):
    """Hand-coded policy that returns random actions."""

    def compute_actions(self,
                        obs_batch,
                        state_batches=None,
                        prev_action_batch=None,
                        prev_reward_batch=None,
                        info_batch=None,
                        episodes=None,
                        **kwargs):
        """Compute actions on a batch of observations."""
        return [self.action_space.sample() for _ in obs_batch], [], {}

    def get_weights(self):
        return None

    def set_weights(self, weights):
        pass

    def learn_on_batch(self, samples):
        """No learning."""
        return {}
```

and then ran the run.tune with "PPO" and "simple_optimizer":True as the warnings suggested. Now, I'm getting a different error though,


```
Traceback (most recent call last):
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 381, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/worker.py", line 1513, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(KeyError): ray::PPO.train() (pid=14608, ip=192.168.1.25)
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 505, in train
    raise e
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 491, in train
    result = Trainable.train(self)
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 150, in _train
    fetches = self.optimizer.step()
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/optimizers/sync_samples_optimizer.py", line 71, in step
    self.standardize_fields)
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/utils/sgd.py", line 107, in do_minibatch_sgd
    batch[field] = standardized(batch[field])
  File "/home/ryan/anaconda3/envs/dorsa/lib/python3.7/site-packages/ray/rllib/policy/sample_batch.py", line 188, in __getitem__
    return self.data[key]
KeyError: 'advantages'
```

Do you have any ideas on what might be causing this? I apologize if these are dumb questions, I've been looking at the source code and documentation but can't find/understand how to fix this

**Comment by ericl** [comment]
I think this one is since PPO is trying to optimize the RandomPolicy still, and since it isn't a PPO policy it is missing some necessary fetches.

You can fix this by setting `policies_to_train: ["learned_policy"]` only.

**Comment by rtolsma** [comment]
> I think this one is since PPO is trying to optimize the RandomPolicy still, and since it isn't a PPO policy it is missing some necessary fetches.
> 
> You can fix this by setting `policies_to_train: ["learned_policy"]` only.

Thank you so much, that worked perfectly! I don't know why this was taking so long to figure out, I feel like the documentation/examples were a little obtuse about the inheritance structure of policies, but this helped me get up to speed

**Comment by nicofirst1** [comment]
Running ray 0.8.4.
I am using the exact same RandomPolicy as @rtolsma with the following PPO configuration :
```
"batch_mode": "complete_episodes",
"lr": 3e-4,
"lambda": .95,
"gamma": .998,
"entropy_coeff": 0.01,
"kl_coeff": 1.0,
"clip_param": 0.2,
"use_critic": True,
"use_gae": True,
"grad_clip": 5,
```
But I'm getting the same error anyway
```

/usr/local/anaconda3/envs/ww/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
2020-05-13 19:00:01,001	ERROR ray_trial_executor.py:252 -- Trial PPO_EvaluationWrapper_2e08eb26: Unexpected error starting runner.
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/ww/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 243, in start_trial
    self._start_trial(trial, checkpoint)
  File "/usr/local/anaconda3/envs/ww/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 181, in _start_trial
    runner = self._setup_remote_runner(trial, reuse_allowed)
  File "/usr/local/anaconda3/envs/ww/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 134, in _setup_remote_runner
    return cls.remote(**kwargs)
  File "/usr/local/anaconda3/envs/ww/lib/python3.7/site-packages/ray/actor.py", line 379, in remote
    return self._remote(args=args, kwargs=kwargs)
  File "/usr/local/anaconda3/envs/ww/lib/python3.7/site-packages/ray/actor.py", line 514, in _remote
    *copy.deepcopy(args), **copy.deepcopy(kwargs))
  File "/usr/local/anaconda3/envs/ww/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 90, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/usr/local/anaconda3/envs/ww/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 455, in __init__
    super().__init__(config, logger_creator)
  File "/usr/local/anaconda3/envs/ww/lib/python3.7/site-packages/ray/tune/trainable.py", line 174, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/usr/local/anaconda3/envs/ww/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 596, in _setup
    self._init(self.config, self.env_creator)
  File "/usr/local/anaconda3/envs/ww/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 129, in _init
    self.optimizer = make_policy_optimizer(self.workers, config)
  File "/usr/local/anaconda3/envs/ww/lib/python3.7/site-packages/ray/rllib/agents/ppo/ppo.py", line 95, in choose_policy_optimizer
    shuffle_sequences=config["shuffle_sequences"])
  File "/usr/local/anaconda3/envs/ww/lib/python3.7/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 99, in __init__
    "Only TF graph policies are supported with multi-GPU. "
ValueError: Only TF graph policies are supported with multi-GPU. Try setting `simple_optimizer=True` instead.
```
