### ISSUE TITLE
[sgd] dcgan.py needs a better reference to mnist_cnn.pt

### ISSUE THREAD

**Issue by PovelikinRostislav** [ray-project/ray#8002]
### What is the problem?
`dcgan.py` sample identifies classification model path as following:
```
"classification_model_path": os.path.join(
            os.path.dirname(ray.__file__),
            "util/sgd/torch/examples/mnist_cnn.pt")
```
But Ray doesn't have samples in the package. In case I just want to run the sample using pre-installed ray from pip, I got the following error:
```
$ python dcgan.py --num-workers 44
2020-04-13 16:32:44,305 INFO resource_spec.py:204 -- Starting Ray with 120.21 GiB memory available for workers and up to 55.52 GiB for objects. You can adjust these settings with ray.init(me
mory=<bytes>, object_store_memory=<bytes>).
2020-04-13 16:32:44,732 INFO services.py:1146 -- View the Ray dashboard at localhost:8265
Traceback (most recent call last):
  File "dcgan.py", line 283, in <module>
    trainer = train_example(
  File "dcgan.py", line 236, in train_example
    trainer = TorchTrainer(
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/util/sgd/torch/torch_trainer.py", line 233, in __init__
    self._start_workers(self.max_replicas)
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/util/sgd/torch/torch_trainer.py", line 320, in _start_workers
    self.local_worker.setup(address, 0, num_workers)
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/util/sgd/torch/distributed_torch_runner.py", line 46, in setup
    self._setup_training()
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/util/sgd/torch/distributed_torch_runner.py", line 92, in _setup_training
    self.training_operator = self.training_operator_cls(
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/util/sgd/torch/training_operator.py", line 96, in __init__
    self.setup(config)
  File "dcgan.py", line 136, in setup
    torch.load(config["classification_model_path"]))
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/torch/serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/util/sgd/torch/examples/mnist_cnn.pt'
2020-04-13 16:32:49,606 ERROR worker.py:1011 -- Possible unhandled error from worker: ray::DistributedTorchRunner.setup() (pid=67029, ip=10.125.21.189)
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/util/sgd/torch/distributed_torch_runner.py", line 46, in setup
    self._setup_training()
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/util/sgd/torch/distributed_torch_runner.py", line 92, in _setup_training
    self.training_operator = self.training_operator_cls(
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/util/sgd/torch/training_operator.py", line 96, in __init__
    self.setup(config)
  File "dcgan.py", line 136, in setup
    torch.load(config["classification_model_path"]))
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/torch/serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/util/sgd/torch/examples/mnist_cnn.pt'
```
*Ray version and other system information (Python version, TensorFlow version, OS):*
ray 0.8.4,
Ubuntu 18.04,
Torch 1.4.0
### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
`python dcgan.py` from `./ray/python/ray/util/sgd/torch/examples` directory of the repo
If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
@PovelikinRostislav Thanks for opening this issue! The solution to this is just to download it from Git rather than packaging it with Ray.

I can get to this later this week, but feel free to push a PR!
