### ISSUE TITLE
CMake error on ubuntu 14.04

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#803]
Starting with a vanilla ubuntu 14.04 image on ec2:

```
wget https://repo.continuum.io/archive/Anaconda3-4.4.0-Linux-x86_64.sh
bash Anaconda3-4.4.0-Linux-x86_64.sh

sudo apt-get update
sudo apt-get install -y cmake pkg-config build-essential autoconf curl libtool libboost-all-dev unzip git
pip install numpy cloudpickle funcsigs click colorama psutil redis flatbuffers
conda install libgcc

git clone https://github.com/ray-project/ray.git
cd ray/python
python setup.py install
```

first gives

```
HEAD is now at dca5d96... ARROW-1275: [C++] Deafult Snappy static lib suffix updated to "_static"
+ bash /home/ubuntu/ray/src/thirdparty/build_thirdparty.sh /home/ubuntu/anaconda3/bin/python
+ set -e
+++ dirname /home/ubuntu/ray/src/thirdparty/build_thirdparty.sh
++ cd /home/ubuntu/ray/src/thirdparty
++ pwd
+ TP_DIR=/home/ubuntu/ray/src/thirdparty
+ [[ -z /home/ubuntu/anaconda3/bin/python ]]
+ PYTHON_EXECUTABLE=/home/ubuntu/anaconda3/bin/python
+ echo 'Using Python executable /home/ubuntu/anaconda3/bin/python.'
Using Python executable /home/ubuntu/anaconda3/bin/python.
++ uname
+ unamestr=Linux
+ [[ Linux == \L\i\n\u\x ]]
++ nproc
+ PARALLEL=8
+ echo 'building arrow'
building arrow
+ cd /home/ubuntu/ray/src/thirdparty/arrow/cpp
+ mkdir -p /home/ubuntu/ray/src/thirdparty/arrow/cpp/build
+ cd /home/ubuntu/ray/src/thirdparty/arrow/cpp/build
+ export ARROW_HOME=/home/ubuntu/ray/src/thirdparty/arrow/cpp/build/cpp-install
+ ARROW_HOME=/home/ubuntu/ray/src/thirdparty/arrow/cpp/build/cpp-install
+ cmake -DCMAKE_BUILD_TYPE=Release '-DCMAKE_C_FLAGS=-g -O3' '-DCMAKE_CXX_FLAGS=-g -O3' -DCMAKE_INSTALL_PREFIX=/home/ubuntu/ray/src/thirdparty/arrow/cpp/build/cpp-install -DARROW_BUILD_TESTS=off -DARROW_HDFS=on -DARROW_PYTHON=on -DARROW_PLASMA=on -DPLASMA_PYTHON=on -DARROW_JEMALLOC=off -DARROW_WITH_BROTLI=off -DARROW_WITH_LZ4=off -DARROW_WITH_SNAPPY=off -DARROW_WITH_ZLIB=off -DARROW_WITH_ZSTD=off ..
CMake Error at CMakeLists.txt:18 (cmake_minimum_required):
  CMake 3.2 or higher is required.  You are running version 2.8.12.2


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    subprocess.check_call(["../build.sh", sys.executable])
  File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../build.sh', '/home/ubuntu/anaconda3/bin/python']' returned non-zero exit status 1.
```

and after upgrading cmake:

```
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:george-edison55/cmake-3.x
sudo apt-get update
sudo apt-get upgrade
```

we get

```
Selected compiler gcc 4.8.4
-- Build output directory: /home/ubuntu/ray/src/thirdparty/arrow/python/build/temp.linux-x86_64-3.6/debug/
-- Found PythonInterp: /home/ubuntu/anaconda3/bin/python (found version "3.6.1") 
-- Searching for Python libs in /home/ubuntu/anaconda3/lib64;/home/ubuntu/anaconda3/lib;/home/ubuntu/anaconda3/lib/python3.6/config-3.6m-x86_64-linux-gnu
-- Looking for python3.6m
-- Found Python lib /home/ubuntu/anaconda3/lib/libpython3.6m.so
-- Found PythonLibs: /home/ubuntu/anaconda3/lib/libpython3.6m.so
-- Found NumPy: version "1.12.1" /home/ubuntu/anaconda3/lib/python3.6/site-packages/numpy/core/include
-- Found Cython: /home/ubuntu/anaconda3/bin/cython  
-- Searching for Python libs in /home/ubuntu/anaconda3/lib64;/home/ubuntu/anaconda3/lib;/home/ubuntu/anaconda3/lib/python3.6/config-3.6m-x86_64-linux-gnu
-- Looking for python3.6m
-- Found Python lib /home/ubuntu/anaconda3/lib/libpython3.6m.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'arrow'
--   found arrow, version 0.6.0-SNAPSHOT
CMake Error at cmake_modules/FindArrow.cmake:32 (pkg_get_variable):
  Unknown CMake command "pkg_get_variable".
Call Stack (most recent call first):
  CMakeLists.txt:157 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/ray/src/thirdparty/arrow/python/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/ray/src/thirdparty/arrow/python/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
error: command 'cmake' failed with exit status 1
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    subprocess.check_call(["../build.sh", sys.executable])
  File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../build.sh', '/home/ubuntu/anaconda3/bin/python']' returned non-zero exit status 1.
```

**Comment by xhochy** [comment]
I would advise to install cmake either via pip (linux only!) or conda, these source will give you a very recent version and you use them anyways for other dependencies.

**Comment by pcmoritz** [comment]
Thanks, that's a good solution! Another possible fix I was thinking about is to make sure that ARROW_HOME is set so we don't need pkg_get_variable; that would probably make it work with cmake 3.2. Supporting 2.8 is probably out of the question.
