### ISSUE TITLE
Redis has started but no raylets have registered yet.

### ISSUE THREAD

**Issue by lizelive** [ray-project/ray#8152]
I started a  ray cluster `ray start --head --redis-port=6379`
I connect to in from my jupyter notebook using `ray.init(address='auto', redis_password='5241590000000000')`

Then i try to add an aditional node to the cluster using `ray.init(address='10.0.0.4:6379', redis_password='5241590000000000')`

But get `Redis has started but no raylets have registered yet.` See bellow for full log.

It works when started from the command line.
Thanks! 

*ray 0.8.3, Ubuntu 16.04.6 LTS*

Full output:
```
2020-04-23 20:12:43,199	WARNING worker.py:792 -- When connecting to an existing cluster, _internal_config must match the cluster's _internal_config.
2020-04-23 20:12:43,208	WARNING services.py:183 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2020-04-23 20:12:44,213	WARNING services.py:183 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2020-04-23 20:12:45,218	WARNING services.py:183 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2020-04-23 20:12:46,223	WARNING services.py:183 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2020-04-23 20:12:47,227	WARNING services.py:183 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?


The experiment failed. Finalizing run...
Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 0.17613768577575684 seconds
Starting the daemon thread to refresh tokens in background for process with pid = 138
Traceback (most recent call last):
  File "node.py", line 2, in <module>
    ray.init(address='10.0.0.4:6379', redis_password='5241590000000000')
  File "/azureml-envs/azureml_4f5506ddd0f6ef8dca81d6df2a7ac40d/lib/python3.6/site-packages/ray/worker.py", line 809, in init
    connect_only=True)
  File "/azureml-envs/azureml_4f5506ddd0f6ef8dca81d6df2a7ac40d/lib/python3.6/site-packages/ray/node.py", line 125, in __init__
    redis_password=self.redis_password)
  File "/azureml-envs/azureml_4f5506ddd0f6ef8dca81d6df2a7ac40d/lib/python3.6/site-packages/ray/services.py", line 176, in get_address_info_from_redis
    redis_address, node_ip_address, redis_password=redis_password)
  File "/azureml-envs/azureml_4f5506ddd0f6ef8dca81d6df2a7ac40d/lib/python3.6/site-packages/ray/services.py", line 159, in get_address_info_from_redis_helper
    "Redis has started but no raylets have registered yet.")
RuntimeError: Redis has started but no raylets have registered yet.
```

**Comment by lizelive** [comment]
simlar to #5437 but im pretty sure my networking is configured correctly.

**Comment by maxgillett** [comment]
Any insight into how to fix this? On the worker node, I'm using openconnect/ocproxy to set up a VPN connection that redirects SSH traffic to the head node to another `ssh-port` port on `localhost`, and then SSHing to the head node by running `ssh -L 0.0.0.0:redis-port:localhost:redis-port -p ssh-port user@headnode`. I can call `ray start --address=localhost:redis-port` with no issue, but in both cases (command line and python `ray.init` call) the worker node doesn't show up in the head's available resources. Unfortunately I can't make the head node a public IP.

**Comment by lizelive** [comment]
is this issue still problem in 1.0?

**Comment by Chickenmarkus** [comment]
> is this issue still problem in 1.0?
Yes, it is.

```
$ docker run --name head -d -it rayproject/ray ray start --head --block
e452d51da9c0961bc180aefd1dfea2ee9081f2c60f856f1f132101a9d95f690f
$ docker logs head
Local node IP: 172.17.0.2
2020-12-21 10:02:48,918 INFO services.py:1092 -- View the Ray dashboard at http://localhost:8265
2020-12-21 10:02:48,920 WARNING services.py:1560 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='172.17.0.2:6379' --redis-password='5241590000000000'

  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='5241590000000000')

  If connection fails, check your firewall settings and network configuration.

  To terminate the Ray runtime, run
    ray stop

$ docker run --rm -it rayproject/ray
(base) root@28a7ebee46f3:/# python -c "import ray; ray.init(address='172.17.0.2:6379')"
2020-12-21 10:10:21,974 INFO worker.py:651 -- Connecting to existing Ray cluster at address: 172.17.0.2:6379
2020-12-21 10:10:21,990 WARNING services.py:202 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2020-12-21 10:10:22,999 WARNING services.py:202 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2020-12-21 10:10:24,009 WARNING services.py:202 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2020-12-21 10:10:25,020 WARNING services.py:202 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2020-12-21 10:10:26,031 WARNING services.py:202 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 759, in init
    connect_only=True)
  File "/root/anaconda3/lib/python3.7/site-packages/ray/node.py", line 163, in __init__
    redis_password=self.redis_password))
  File "/root/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 195, in get_address_info_from_redis
    redis_address, node_ip_address, redis_password=redis_password)
  File "/root/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 178, in get_address_info_from_redis_helper
    "Redis has started but no raylets have registered yet.")
RuntimeError: Redis has started but no raylets have registered yet.
```

Contrary, the cmdline works:

```
root@587f2b85b776:/# ray start --address 172.17.0.2:6379
Local node IP: 172.17.0.4
2020-12-21 10:11:27,562 WARNING services.py:1560 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.

--------------------
Ray runtime started.
--------------------

To terminate the Ray runtime, run
  ray stop
root@587f2b85b776:/# python -c "import ray; ray.init(address='auto')"    2020-12-21 10:14:23,615 INFO worker.py:651 -- Connecting to existing Ray cluster at address: 172.17.0.2:6379
```

The version of ray inside the container is _1.0.1.post1_.

**Comment by gefei456** [comment]
I meet the same issues.
