### ISSUE TITLE
[tune] AttributeError: 'EnumTypeWrapper' object has no attribute 'DATA_TYPE_FLOAT64'

### ISSUE THREAD

**Issue by nyxynyx** [ray-project/ray#8155]
### AttributeError: 'EnumTypeWrapper' object has no attribute 'DATA_TYPE_FLOAT64'  when running a simple Ray Tune example

When I ran the simple example as shown

```
import torch.optim as optim
import ray
from ray import tune
from ray.tune.examples.mnist_pytorch import get_data_loaders, ConvNet, train, test

def train_mnist(config):

    train_loader, test_loader = get_data_loaders()
    model = ConvNet()
    optimizer = optim.SGD(model.parameters(), lr=config["lr"])
    for i in range(10):
        train(model, optimizer, train_loader)
        acc = test(model, test_loader)
        tune.track.log(mean_accuracy=acc)

if __name__ == '__main__':
    ray.init()
    analysis = tune.run(
        train_mnist,
        config={
            "lr": tune.grid_search([0.1, 0.01]),
        }
    )
```

I get the following error after one of the trials has been completed:

> AttributeError: 'EnumTypeWrapper' object has no attribute 'DATA_TYPE_FLOAT64'

Any ideas how we can solve this? 

Thank you!

-----

```
$ conda list | grep -i tensorboardx
tensorboardx              2.0                      pypi_0    pypi
```

**Full Error**

```
2020-04-23 20:05:20,072	ERROR trial_runner.py:521 -- Trial train_mnist_00001: Error processing event.
Traceback (most recent call last):
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 519, in _process_trial
    self._execute_action(trial, decision)
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 604, in _execute_action
    self.trial_executor.stop_trial(trial)
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 267, in stop_trial
    trial, error=error, error_msg=error_msg, stop_logger=stop_logger)
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 208, in _stop_trial
    trial.close_logger()
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/trial.py", line 354, in close_logger
    self.result_logger.close()
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/logger.py", line 326, in close
    _logger.close()
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/logger.py", line 248, in close
    self._try_log_hparams(scrubbed_result)
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/logger.py", line 260, in _try_log_hparams
    hparam_dict=scrubbed_params, metric_dict=result)
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/tensorboardX/summary.py", line 104, in hparams
    hps.append(HParamInfo(name=k, type=DataType.DATA_TYPE_FLOAT64))
AttributeError: 'EnumTypeWrapper' object has no attribute 'DATA_TYPE_FLOAT64'
Traceback (most recent call last):
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 519, in _process_trial
    self._execute_action(trial, decision)
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 604, in _execute_action
    self.trial_executor.stop_trial(trial)
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 267, in stop_trial
    trial, error=error, error_msg=error_msg, stop_logger=stop_logger)
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 208, in _stop_trial
    trial.close_logger()
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/trial.py", line 354, in close_logger
    self.result_logger.close()
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/logger.py", line 326, in close
    _logger.close()
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/logger.py", line 248, in close
    self._try_log_hparams(scrubbed_result)
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/logger.py", line 260, in _try_log_hparams
    hparam_dict=scrubbed_params, metric_dict=result)
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/tensorboardX/summary.py", line 104, in hparams
    hps.append(HParamInfo(name=k, type=DataType.DATA_TYPE_FLOAT64))
AttributeError: 'EnumTypeWrapper' object has no attribute 'DATA_TYPE_FLOAT64'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/foobar/test.py", line 21, in <module>
    "lr": tune.grid_search([0.1, 0.01]),
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/tune.py", line 321, in run
    runner.step()
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 339, in step
    self._process_events()  # blocking
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 452, in _process_events
    self._process_trial(trial)
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 522, in _process_trial
    self._process_trial_failure(trial, traceback.format_exc())
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 589, in _process_trial_failure
    trial, error=True, error_msg=error_msg)
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 267, in stop_trial
    trial, error=error, error_msg=error_msg, stop_logger=stop_logger)
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 208, in _stop_trial
    trial.close_logger()
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/trial.py", line 354, in close_logger
    self.result_logger.close()
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/logger.py", line 326, in close
    _logger.close()
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/logger.py", line 248, in close
    self._try_log_hparams(scrubbed_result)
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/ray/tune/logger.py", line 260, in _try_log_hparams
    hparam_dict=scrubbed_params, metric_dict=result)
  File "/opt/anaconda3/envs/helloworld/lib/python3.7/site-packages/tensorboardX/summary.py", line 104, in hparams
    hps.append(HParamInfo(name=k, type=DataType.DATA_TYPE_FLOAT64))
AttributeError: 'EnumTypeWrapper' object has no attribute 'DATA_TYPE_FLOAT64'

Process finished with exit code 1
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

- ray 0.8.4
- Python 3.7.3
- Pytorch 1.4.0
- Ubuntu 18.04

**Comment by richardliaw** [comment]
Hm, I've never seen this before.  What does your config look like?

And can you raise this on the TensorboardX github?

**Comment by nyxynyx** [comment]
@richardliaw Here's the output of `conda list`. Will be great if you notice something odd with the installed packages.

Will try raising this issue over there.

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
aiohttp                   3.6.2                    pypi_0    pypi
arrow-cpp                 0.13.0           py37h117bdfb_0  
asn1crypto                1.3.0                    py37_0  
async-timeout             3.0.1                    pypi_0    pypi
attrs                     19.3.0                   pypi_0    pypi
beautifulsoup4            4.9.0                    pypi_0    pypi
blas                      1.0                         mkl  
blosc                     1.16.3               hd408876_0  
boost-cpp                 1.67.0               h14c3975_4  
bottleneck                1.3.1            py37hdd07704_0  
brotli                    1.0.7                he6710b0_0  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.1.1                      0  
certifi                   2020.4.5.1               py37_0  
cffi                      1.14.0           py37h2e261b9_0  
chardet                   3.0.4                 py37_1003  
click                     7.1.1                    pypi_0    pypi
colorama                  0.4.3                    pypi_0    pypi
cryptography              2.8              py37h1ba5d50_0  
cudatoolkit               10.2.89              hfd86e86_0  
cycler                    0.10.0                   py37_0  
dbus                      1.13.12              h746ee38_0  
double-conversion         3.1.5                he6710b0_1  
expat                     2.2.6                he6710b0_0  
fastparquet               0.3.3            py37hc1659b7_0    conda-forge
filelock                  3.0.12                   pypi_0    pypi
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_1  
gflags                    2.2.2                he6710b0_0  
glib                      2.63.1               h5a9c865_0  
glog                      0.4.0                he6710b0_0  
google                    2.0.3                    pypi_0    pypi
grpcio                    1.27.2                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.9.0            py37h7918eee_0  
hdf5                      1.10.4               hb1b8bf9_0  
icu                       58.2                 h9c2bf20_1  
idna                      2.9                        py_1  
importlib-metadata        1.6.0                    pypi_0    pypi
intel-openmp              2020.0                      166  
joblib                    0.14.1                     py_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                    pypi_0    pypi
kiwisolver                1.1.0            py37he6710b0_0  
libboost                  1.67.0               h46d08c1_4  
libedit                   3.1.20181209         hc058e9b_0  
libevent                  2.1.8                h1ba5d50_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.6.0                hdbcaa40_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                hea5a465_1  
llvmlite                  0.32.0           py37hd408876_0  
lz4-c                     1.8.1.2              h14c3975_0  
lzo                       2.10                 h7b6447c_2  
matplotlib                3.1.1            py37h5429711_0  
mkl                       2020.0                      166  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.15           py37ha843d7b_0  
mkl_random                1.1.0            py37hd6b4f25_0  
mock                      4.0.1                      py_1  
multidict                 4.7.5                    pypi_0    pypi
ncurses                   6.2                  he6710b0_0  
ninja                     1.9.0            py37hfd86e86_0  
numba                     0.49.0           py37h0573a6f_0  
numexpr                   2.7.1            py37h423224d_0  
numpy                     1.18.1           py37h4f9e942_0  
numpy-base                1.18.1           py37hde5b4d6_1  
olefile                   0.46                     py37_0  
openssl                   1.1.1g               h7b6447c_0  
pandas                    0.25.3           py37he6710b0_0  
pcre                      8.43                 he6710b0_0  
pillow                    7.0.0            py37hb39fc2d_0  
pip                       20.0.2                   py37_1  
protobuf                  3.11.3                   pypi_0    pypi
py-spy                    0.3.3                    pypi_0    pypi
pyarrow                   0.13.0           py37he6710b0_0  
pycparser                 2.20                       py_0  
pyopenssl                 19.1.0                   py37_0  
pyparsing                 2.4.6                      py_0  
pyqt                      5.9.2            py37h05f1152_2  
pyrsistent                0.16.0                   pypi_0    pypi
pysocks                   1.7.1                    py37_0  
pytables                  3.6.1            py37h71ec239_0  
python                    3.7.3                h0371630_0  
python-dateutil           2.8.1                      py_0  
python-snappy             0.5.4            py37he6710b0_0  
pytorch                   1.5.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
pytz                      2019.3                     py_0  
pyyaml                    5.3.1                    pypi_0    pypi
qt                        5.9.7                h5867ecd_1  
ray                       0.8.4                    pypi_0    pypi
re2                       2019.08.01           he6710b0_0  
readline                  7.0                  h7b6447c_5  
redis                     3.4.1                    pypi_0    pypi
requests                  2.23.0                   py37_0  
scikit-learn              0.22.1           py37hd81dba3_0  
scipy                     1.4.1            py37h0b6359f_0  
setuptools                46.1.3                   py37_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.14.0                   py37_0  
snappy                    1.1.7                hbae5bb6_3  
soupsieve                 2.0                      pypi_0    pypi
sqlalchemy                1.3.11           py37h7b6447c_0  
sqlite                    3.31.1               h62c20be_1  
tabulate                  0.8.7                    pypi_0    pypi
tbb                       2020.0               hfd86e86_0  
tensorboardx              2.0                      pypi_0    pypi
thrift                    0.11.0           py37hf484d3e_0  
thrift-cpp                0.11.0               h02b749d_3  
tk                        8.6.8                hbc83047_0  
torchvision               0.6.0                py37_cu102    pytorch
tornado                   6.0.4            py37h7b6447c_1  
urllib3                   1.25.8                   py37_0  
wheel                     0.34.2                   py37_0  
wrapt                     1.11.2           py37h7b6447c_0  
xz                        5.2.5                h7b6447c_0  
yarl                      1.4.2                    pypi_0    pypi
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  
```

**Comment by richardliaw** [comment]
Hm, yeah no idea. For now, you can turn off the TensorboardX Logger:

```
from ray.tune.logger import CSVLogger, JsonLogger

tune.run(..., loggers=(CSVLogger, JsonLogger))
```
