### ISSUE TITLE
Actor with name WrappedTrackFunc failed to be imported

### ISSUE THREAD

**Issue by yfche** [ray-project/ray#8204]
Hi, I am strictly following a Tune example with codes here ([https://colab.research.google.com/github/ray-project/tutorial/blob/master/tune_exercises/exercise_1_basics.ipynb#scrollTo=Cx0z45VuplTo]) on a local desktop (iOS system), and I constantly run into the following error messages:

```
---------------------------------------------------------------------------
TuneError                                 Traceback (most recent call last)
<ipython-input-7-0a5fa82d8884> in <module>()
     17 get_ipython().system(' rm -rf ~/ray_results/tune_iris')
     18 
---> 19 analysis = tune.run(tune_iris, verbose=1, config=hyperparameter_space, num_samples=num_samples)
     20 
     21 assert len(analysis.trials) == 20, "Did you set the correct number of samples?"

/anaconda3/lib/python3.6/site-packages/ray/tune/tune.py in run(run_or_experiment, name, stop, config, resources_per_trial, num_samples, local_dir, upload_dir, trial_name_creator, loggers, sync_to_cloud, sync_to_driver, checkpoint_freq, checkpoint_at_end, sync_on_checkpoint, keep_checkpoints_num, checkpoint_score_attr, global_checkpoint_period, export_formats, max_failures, fail_fast, restore, search_alg, scheduler, with_server, server_port, verbose, progress_reporter, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial, return_trials, ray_auto_init)
    340     if incomplete_trials:
    341         if raise_on_failed_trial:
--> 342             raise TuneError("Trials did not complete", incomplete_trials)
    343         else:
    344             logger.error("Trials did not complete: %s", incomplete_trials)

TuneError: ('Trials did not complete', [tune_iris_00000, tune_iris_00001, tune_iris_00002, tune_iris_00003, tune_iris_00004, tune_iris_00005, tune_iris_00006, tune_iris_00007, tune_iris_00008, tune_iris_00009, tune_iris_00010, tune_iris_00011, tune_iris_00012, tune_iris_00013, tune_iris_00014, tune_iris_00015, tune_iris_00016, tune_iris_00017, tune_iris_00018, tune_iris_00019])`

If I open the local error.txt file under each trial folder, the error messages are as below:

`Failure # 1 (occurred at 2020-04-27_16-45-04)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/anaconda3/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 381, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 1513, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::TemporaryActor.__init__()[39m (pid=83862, ip=18.21.221.154)
  File "python/ray/_raylet.pyx", line 414, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 450, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
RuntimeError: The actor with name WrappedTrackFunc failed to be imported, and so cannot execute this method.
```

I tried to search for solutions online, and the underlying reason is unclear. Here I am pasting the installed packages and their versions on my machine. Could anyone point out how may I resolve this issue with the WrappedTrackFunc actor? Thanks.

```dhcp-18-21-221-154:~ yfche$ pip3 list
Package                            Version   
---------------------------------- ----------
-eras                              2.1.5     
absl-py                            0.8.0     
aiohttp                            3.6.2     
alabaster                          0.7.10    
anaconda-client                    1.6.9     
anaconda-navigator                 1.7.0     
anaconda-project                   0.8.2     
appnope                            0.1.0     
appscript                          1.0.1     
asn1crypto                         0.24.0    
astor                              0.6.2     
astroid                            1.6.1     
astropy                            2.0.3     
async-timeout                      3.0.1     
atomicwrites                       1.3.0     
attrs                              17.4.0    
Babel                              2.5.3     
backports.shutil-get-terminal-size 1.0.0     
beautifulsoup4                     4.6.0     
bitarray                           0.8.1     
bkcharts                           0.2       
blaze                              0.11.3    
bleach                             1.5.0     
bokeh                              0.12.13   
boto                               2.48.0    
Bottleneck                         1.2.1     
cachetools                         4.1.0     
certifi                            2019.11.28
cffi                               1.11.4    
chardet                            3.0.4     
click                              6.7       
cloudpickle                        0.5.2     
clyent                             1.2.2     
colorama                           0.3.9     
conda                              4.4.10    
conda-build                        3.4.1     
conda-verify                       2.0.0     
contextlib2                        0.5.5     
cryptography                       2.1.4     
cycler                             0.10.0    
Cython                             0.27.3    
cytoolz                            0.9.0     
dask                               0.16.1    
datashape                          0.5.4     
decorator                          4.4.2     
distributed                        1.20.2    
docutils                           0.14      
entrypoints                        0.2.3     
et-xmlfile                         1.0.1     
fastcache                          1.0.2     
fda                                0.1       
filelock                           2.0.13    
Flask                              0.12.2    
Flask-Cors                         3.0.3     
future                             0.18.2    
gast                               0.2.2     
gevent                             1.2.2     
glob2                              0.6       
gmpy2                              2.0.8     
google                             2.0.3     
google-auth                        1.14.0    
google-auth-oauthlib               0.4.1     
google-pasta                       0.1.7     
gpflow                             1.5.0     
greenlet                           0.4.12    
grpcio                             1.28.1    
h5py                               2.10.0    
heapdict                           1.0.0     
html5lib                           0.9999999 
hyperopt                           0.2.4     
idna                               2.6       
idna-ssl                           1.1.0     
imageio                            2.2.0     
imagesize                          0.7.1     
importlib-metadata                 1.4.0     
ipykernel                          5.1.4     
ipython                            6.2.1     
ipython-genutils                   0.2.0     
ipywidgets                         7.1.1     
isort                              4.2.15    
itsdangerous                       0.24      
jdcal                              1.3       
jedi                               0.11.1    
Jinja2                             2.10      
jsonschema                         2.6.0     
jupyter                            1.0.0     
jupyter-client                     5.3.3     
jupyter-console                    5.2.0     
jupyter-core                       4.4.0     
jupyterlab                         0.31.5    
jupyterlab-launcher                0.10.2    
Keras                              2.3.1     
Keras-Applications                 1.0.8     
Keras-Preprocessing                1.1.0     
keyring                            21.1.0    
kiwisolver                         1.1.0     
lazy-object-proxy                  1.3.1     
llvmlite                           0.21.0    
locket                             0.2.0     
lxml                               4.1.1     
Markdown                           2.6.11    
MarkupSafe                         1.0       
matplotlib                         3.1.1     
mccabe                             0.6.1     
mistune                            0.8.3     
more-itertools                     8.0.2     
mpmath                             1.0.0     
msgpack-python                     0.5.1     
multidict                          4.7.5     
multipledispatch                   0.4.9     
navigator-updater                  0.1.0     
nbconvert                          5.3.1     
nbformat                           4.4.0     
networkx                           2.4       
nltk                               3.2.5     
nose                               1.3.7     
notebook                           5.4.0     
numba                              0.36.2    
numexpr                            2.6.4     
numpy                              1.17.2    
numpydoc                           0.7.0     
oauthlib                           3.1.0     
odo                                0.5.1     
olefile                            0.45.1    
openpyxl                           2.4.10    
opt-einsum                         3.2.0     
packaging                          16.8      
pandas                             0.22.0    
pandocfilters                      1.4.2     
parso                              0.1.1     
partd                              0.3.8     
path.py                            10.5      
pathlib2                           2.3.0     
patsy                              0.5.0     
pep8                               1.7.1     
pexpect                            4.3.1     
pickleshare                        0.7.4     
Pillow                             5.0.0     
pip                                20.0.2    
pkginfo                            1.4.1     
pluggy                             0.13.0    
ply                                3.10      
prompt-toolkit                     1.0.15    
protobuf                           3.9.1     
psutil                             5.4.3     
ptyprocess                         0.5.2     
py                                 1.5.2     
py-spy                             0.3.3     
pyasn1                             0.4.8     
pyasn1-modules                     0.2.8     
pycodestyle                        2.3.1     
pycosat                            0.6.3     
pycparser                          2.18      
pycrypto                           2.6.1     
pycurl                             7.43.0.1  
pyDOE                              0.3.8     
pydot                              1.4.1     
pyflakes                           1.6.0     
Pygments                           2.2.0     
pylint                             1.8.2     
pymc3                              3.7       
pyodbc                             4.0.22    
pyOpenSSL                          17.5.0    
pyparsing                          2.2.0     
PySocks                            1.6.7     
pytest                             5.1.2     
python-dateutil                    2.6.1     
pytz                               2017.3    
PyWavelets                         0.5.2     
PyYAML                             3.12      
pyzmq                              17.0.0    
QtAwesome                          0.6.0     
qtconsole                          4.3.1     
QtPy                               1.9.0     
ray                                0.8.4     
rdata                              0.2.1     
redis                              3.4.1     
requests                           2.23.0    
requests-oauthlib                  1.3.0     
rope                               0.10.7    
rpy2                               3.0.1     
rsa                                4.0       
ruamel-yaml                        0.15.35   
scikit-datasets                    0.1.25    
scikit-image                       0.13.1    
scikit-learn                       0.19.1    
scipy                              1.4.1     
seaborn                            0.8.1     
Send2Trash                         1.4.2     
setuptools                         46.1.3    
simplegeneric                      0.8.1     
singledispatch                     3.4.0.3   
six                                1.14.0    
sklearn                            0.0       
snowballstemmer                    1.2.1     
sortedcollections                  0.5.3     
sortedcontainers                   1.5.9     
Sphinx                             1.6.6     
sphinxcontrib-websupport           1.0.1     
spyder                             3.3.6     
spyder-kernels                     0.5.2     
SQLAlchemy                         1.2.1     
statsmodels                        0.8.0     
sympy                              1.1.1     
tables                             3.4.2     
tabulate                           0.8.7     
tblib                              1.3.2     
tensorboard                        2.1.1     
tensorboardX                       2.0       
tensorflow                         2.1.0     
tensorflow-estimator               2.1.0     
termcolor                          1.1.0     
terminado                          0.8.1     
testpath                           0.3.1     
Theano                             1.0.4     
toolz                              0.9.0     
torch                              1.4.0     
torchvision                        0.5.0     
tornado                            4.5.3     
tqdm                               4.35.0    
traitlets                          4.3.2     
typing                             3.6.2     
typing-extensions                  3.7.4.2   
unicodecsv                         0.14.1    
urllib3                            1.22      
wcwidth                            0.1.7     
webencodings                       0.5.1     
Werkzeug                           0.14.1    
wheel                              0.34.2    
widgetsnbextension                 3.1.0     
wrapt                              1.11.2    
wurlitzer                          2.0.0     
xarray                             0.12.1    
xlrd                               1.1.0     
XlsxWriter                         1.0.2     
xlwings                            0.11.5    
xlwt                               1.2.0     
yarl                               1.4.2     
zict                               0.1.3     
zipp                               0.6.0     `

**Comment by richardliaw** [comment]
Before `tune.run`, can you try:

```
ray.shutdown()
tune.run(...
```

**Comment by yfche** [comment]
> Before `tune.run`, can you try:
> 
> ```
> ray.shutdown()
> tune.run(...
> ```

Hi thanks for the attention. Yes I called `ray.shutdown()` right before calling `tune.run(...`. The errors persist.

**Comment by richardliaw** [comment]
If anyone runs into this problem, it'd be great to see the ray logs: `/tmp/ray/session_latest/logs`
