### ISSUE TITLE
[rllib] Error while trying to use get_model_v2 to make vision net

### ISSUE THREAD

**Issue by Camq543** [ray-project/ray#8214]
When I try to create a convolutional network using get_model_v2, I get an error on line 96 of visionnet_v2.py, which is the call to tf.squeeze() while building the final layer of the value network. The error I get says that it's trying to squeeze on a dimension >1 but can only squeeze on a  dimension of 1. I'm not sure if this is an error in the rllib code or if I'm doing something wrong. Please help me out

Below is the error traceback:

 Traceback (most recent call last):
  File "/home/cameron/.conda/envs/pcgrl/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1607, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Can not squeeze dim[1], expected a dimension of 1, got 26 for 'lambda/Squeeze' (op: 'Squeeze') with input shapes: [?,26,26,1].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 89, in <module>
    model = models.catalog.ModelCatalog.get_model_v2(env(env_config).observation_space,env(env_config).action_space,32,model_config,name="my_model")
  File "/home/cameron/.conda/envs/pcgrl/lib/python3.6/site-packages/ray/rllib/models/catalog.py", line 348, in get_model_v2
    name, **model_kwargs)
  File "/home/cameron/.conda/envs/pcgrl/lib/python3.6/site-packages/ray/rllib/models/tf/visionnet_v2.py", line 97, in __init__
    lambda x: tf.squeeze(x, axis=[1, 2]))(last_layer)
  File "/home/cameron/.conda/envs/pcgrl/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 854, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/cameron/.conda/envs/pcgrl/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/core.py", line 789, in call
    return self.function(inputs, **arguments)
  File "/home/cameron/.conda/envs/pcgrl/lib/python3.6/site-packages/ray/rllib/models/tf/visionnet_v2.py", line 97, in <lambda>
    lambda x: tf.squeeze(x, axis=[1, 2]))(last_layer)
  File "/home/cameron/.conda/envs/pcgrl/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/cameron/.conda/envs/pcgrl/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/cameron/.conda/envs/pcgrl/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 3651, in squeeze
    return gen_array_ops.squeeze(input, axis, name)
  File "/home/cameron/.conda/envs/pcgrl/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 10069, in squeeze
    "Squeeze", input=input, squeeze_dims=axis, name=name)
  File "/home/cameron/.conda/envs/pcgrl/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/cameron/.conda/envs/pcgrl/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/cameron/.conda/envs/pcgrl/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/cameron/.conda/envs/pcgrl/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/cameron/.conda/envs/pcgrl/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1770, in __init__
    control_input_ops)
  File "/home/cameron/.conda/envs/pcgrl/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Can not squeeze dim[1], expected a dimension of 1, got 26 for 'lambda/Squeeze' (op: 'Squeeze') with input shapes: [?,26,26,1].

**Comment by sven1977** [comment]
Hmm, could you check, whether you have the version of `visionnet_v2.py`, where we set data_format="channels_last" in all `tf.keras.layers.Conv2D` calls? Which ray version/commit are you running?

**Comment by Camq543** [comment]
That was not in my `visionnet_v2.py` file. I tried adding that into the `Conv2d` calls, but got the same error, but I assume other updates were made to the library so just adding that line may not fix the issue. I am running the version of ray that is currently installable through pip for python 3.6. I believe the version num is 0.8.4.
