### ISSUE TITLE
[rllib] Replay buffer compression fails

### ISSUE THREAD

**Issue by royf** [ray-project/ray#8262]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray: 0.8.4
Python: 3.8.2
OS: macOS 10.15.4
cloudpickle: 1.3.0

### Reproduction (REQUIRED)

```python
import ray
import tensorflow as tf
import torch
from ray import tune
from ray.rllib.agents.trainer import with_common_config
from ray.rllib.agents.trainer_template import build_trainer
from ray.rllib.optimizers import SyncReplayOptimizer
from ray.rllib.policy.tf_policy_template import build_tf_policy
from ray.rllib.policy.torch_policy_template import build_torch_policy


def example_tf_loss_fn(_policy, model, _dist_class, _train_batch):
    return tf.reduce_sum(model.variables()[0] * 0.)


ExampleTFPolicy = build_tf_policy(
    name="ExampleTFPolicy",
    loss_fn=example_tf_loss_fn,
)


def example_torch_loss_fn(_policy, _model, _dist_class, _train_batch):
    return torch.tensor(0., requires_grad=True)


ExampleTorchPolicy = build_torch_policy(
    name="ExampleTorchPolicy",
    loss_fn=example_torch_loss_fn,
)

DEFAULT_CONFIG = with_common_config({
    "use_pytorch": True,
    "num_workers": 1,
})


def make_policy_optimizer(workers, _config):
    return SyncReplayOptimizer(workers, prioritized_replay=False)


ExampleTrainer = build_trainer(
    name="Example",
    default_policy=ExampleTorchPolicy,
    default_config=DEFAULT_CONFIG,
    make_policy_optimizer=make_policy_optimizer,
)

if __name__ == "__main__":
    ray.init()
    tune.run(
        ExampleTrainer,
        config={
            "env": "CartPole-v1",
        })
```

The same also fails for `default_policy=ExampleTFPolicy`, but not for `num_workers=2` (with either TF or Torch).

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ericl** [comment]
What's the error? It seems to run for me up to 70k timesteps. Maybe `pip install ray[rllib]` or `pip install lz4`?

**Comment by royf** [comment]
I did install with `pip install ray[rllib]`, and lz4 version 3.0.2 was installed as a dependency.

The error is:

```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/example/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/usr/local/Caskroom/miniconda/base/envs/example/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 381, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/usr/local/Caskroom/miniconda/base/envs/example/lib/python3.8/site-packages/ray/worker.py", line 1513, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::Example.train() (pid=20624, ip=192.168.1.2)
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
  File "/usr/local/Caskroom/miniconda/base/envs/example/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 505, in train
    raise e
  File "/usr/local/Caskroom/miniconda/base/envs/example/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 491, in train
    result = Trainable.train(self)
  File "/usr/local/Caskroom/miniconda/base/envs/example/lib/python3.8/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/usr/local/Caskroom/miniconda/base/envs/example/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 150, in _train
    fetches = self.optimizer.step()
  File "/usr/local/Caskroom/miniconda/base/envs/example/lib/python3.8/site-packages/ray/rllib/optimizers/sync_replay_optimizer.py", line 139, in step
    self._optimize()
  File "/usr/local/Caskroom/miniconda/base/envs/example/lib/python3.8/site-packages/ray/rllib/optimizers/sync_replay_optimizer.py", line 159, in _optimize
    samples = self._replay()
  File "/usr/local/Caskroom/miniconda/base/envs/example/lib/python3.8/site-packages/ray/rllib/optimizers/sync_replay_optimizer.py", line 202, in _replay
    dones) = replay_buffer.sample_with_idxes(idxes)
  File "/usr/local/Caskroom/miniconda/base/envs/example/lib/python3.8/site-packages/ray/rllib/optimizers/replay_buffer.py", line 74, in sample_with_idxes
    return self._encode_sample(idxes)
  File "/usr/local/Caskroom/miniconda/base/envs/example/lib/python3.8/site-packages/ray/rllib/optimizers/replay_buffer.py", line 58, in _encode_sample
    obses_t.append(np.array(unpack_if_needed(obs_t), copy=False))
  File "/usr/local/Caskroom/miniconda/base/envs/example/lib/python3.8/site-packages/ray/rllib/utils/compression.py", line 57, in unpack_if_needed
    data = unpack(data)
  File "/usr/local/Caskroom/miniconda/base/envs/example/lib/python3.8/site-packages/ray/rllib/utils/compression.py", line 50, in unpack
    data = pickle.loads(data)
  File "/usr/local/Caskroom/miniconda/base/envs/example/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 420, in _numpy_frombuffer
    array.setflags(write=isinstance(buffer, bytearray) or not buffer.readonly)
AttributeError: 'bytes' object has no attribute 'readonly'
```

But it seems the problem is not in `pickle.loads`, it's earlier in `pickle.dumps`.

**Comment by ericl** [comment]
Oh weird, maybe this is a Python 3.8 pickling issue? cc @pcmoritz @suquark if you've seen anything like this

**Comment by royf** [comment]
I can confirm that I don't see this issue in a Python 3.7 environment.

**Comment by JamieMair** [comment]
I am having the same issue on my machine using the code above (modified to use the tensorflow policy). I am also having the issue with my own, different code. The trace is:

`raceback (most recent call last):
  File "/home/jamie/anaconda3/envs/excursionrl/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/jamie/anaconda3/envs/excursionrl/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 431, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/jamie/anaconda3/envs/excursionrl/lib/python3.8/site-packages/ray/worker.py", line 1515, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): [36mray::Example.train()[39m (pid=2206, ip=192.168.0.24)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 417, in ray._raylet.execute_task.function_executor
  File "/home/jamie/anaconda3/envs/excursionrl/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 498, in train
    raise e
  File "/home/jamie/anaconda3/envs/excursionrl/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 484, in train
    result = Trainable.train(self)
  File "/home/jamie/anaconda3/envs/excursionrl/lib/python3.8/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/home/jamie/anaconda3/envs/excursionrl/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 151, in _train
    fetches = self.optimizer.step()
  File "/home/jamie/anaconda3/envs/excursionrl/lib/python3.8/site-packages/ray/rllib/optimizers/sync_replay_optimizer.py", line 146, in step
    self._optimize()
  File "/home/jamie/anaconda3/envs/excursionrl/lib/python3.8/site-packages/ray/rllib/optimizers/sync_replay_optimizer.py", line 172, in _optimize
    samples = self._replay()
  File "/home/jamie/anaconda3/envs/excursionrl/lib/python3.8/site-packages/ray/rllib/optimizers/sync_replay_optimizer.py", line 220, in _replay
    dones) = replay_buffer.sample_with_idxes(idxes)
  File "/home/jamie/anaconda3/envs/excursionrl/lib/python3.8/site-packages/ray/rllib/optimizers/replay_buffer.py", line 74, in sample_with_idxes
    return self._encode_sample(idxes)
  File "/home/jamie/anaconda3/envs/excursionrl/lib/python3.8/site-packages/ray/rllib/optimizers/replay_buffer.py", line 58, in _encode_sample
    obses_t.append(np.array(unpack_if_needed(obs_t), copy=False))
  File "/home/jamie/anaconda3/envs/excursionrl/lib/python3.8/site-packages/ray/rllib/utils/compression.py", line 57, in unpack_if_needed
    data = unpack(data)
  File "/home/jamie/anaconda3/envs/excursionrl/lib/python3.8/site-packages/ray/rllib/utils/compression.py", line 50, in unpack
    data = pickle.loads(data)
  File "/home/jamie/anaconda3/envs/excursionrl/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 420, in _numpy_frombuffer
    array.setflags(write=isinstance(buffer, bytearray) or not buffer.readonly)
AttributeError: 'bytes' object has no attribute 'readonly'`

I am using python 3.8 on Linux.
