### ISSUE TITLE
[rrlib] "pause" individual agents in multi-agent env

### ISSUE THREAD

**Issue by OnTheRicky** [ray-project/ray#8294]
### What is your question?

I have a custom multi-agent environment where there is always the same number of agents interacting with the environment. An individual agent can take an action to take a break for a fixed time period, and then returns (this creates a dynamic where the other agents are still interacting with the environment without the paused agent). For the "paused" time however, the agent should not receive any observations or rewards. If I try sending no observations and rewards I get the same error as #4526

Is there any other workaround here?

**Comment by ericl** [comment]
Can you be more specific about the error? You should be able to simply send no observations and rewards for the agent while it is inactive, as long as you didn't send done for it.

**Comment by OnTheRicky** [comment]
Hi @ericl, the error I got was the exact same as #4256. 
In the step where the agent sends the "pause action", I was returning a done along with the reward. 

From the reading I've done it's unclear whether I need to send a done with the reward to indicate "an episode end" for an agent. 
If I don't return the done and the reward, how do updates get treated?
Especially unclear in terms of discounting the reward if I simply stop sendings rewards and observations.

**Comment by ericl** [comment]
If you need to set done, to cut the reward propagation at the point, then consider deleting the agent and creating a new one with a different agent_id.

**Comment by OnTheRicky** [comment]
I believe this is working for me, but could you please confirm if the following logic is the correct way of doing this: 

1. At current step, receive agent action to pause and do the following:
- return done
- return reward for last action
- return final state observation
2. At following step:
- delete agent, sending no obs, rewards, dones, infos
3. At step to resume:
- create new agent, with new agent_id
- step as normal

I'm currently running into issues where I have two workers training four agents and every now and then I get a key error where an agent_id isn't available because it's been deleted, but somehow in the step loop it's being used in indexing my dicts.

**Comment by ericl** [comment]
That should work. Can you post the full error traces please?

**Comment by OnTheRicky** [comment]
Here is the error trace for what happens when I follow the procedure as set out above. 
I don't know if it is because I'm running on two workers, that one deletes the agent and the other still somehow has the agent in the action_dict?

> 2020-05-08 16:47:44,278 INFO trainer.py:499 -- Worker crashed during call to train(). To attempt to continue training without the failed worker, set `'ignore_worker_failures': True`.
Traceback (most recent call last):
  File "test_rllib_fc_maintenance.py", line 53, in <module>
    print(pretty_print(ppo_trainer.train()))
  File "/usr/local/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 502, in train
    raise e
  File "/usr/local/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 491, in train
    result = Trainable.train(self)
  File "/usr/local/lib/python3.7/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/usr/local/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 150, in _train
    fetches = self.optimizer.step()
  File "/usr/local/lib/python3.7/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 139, in step
    self.train_batch_size)
  File "/usr/local/lib/python3.7/site-packages/ray/rllib/optimizers/rollout.py", line 25, in collect_samples
    next_sample = ray_get_and_free(fut_sample)
  File "/usr/local/lib/python3.7/site-packages/ray/rllib/utils/memory.py", line 29, in ray_get_and_free
    result = ray.get(object_ids)
  File "/usr/local/lib/python3.7/site-packages/ray/worker.py", line 1513, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(KeyError): ray::RolloutWorker.sample() (pid=19286, ip=192.168.1.8)
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
  File "/usr/local/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 492, in sample
    batches = [self.input_reader.next()]
  File "/usr/local/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 53, in next
    batches = [self.get_data()]
  File "/usr/local/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 96, in get_data
    item = next(self.rollout_provider)
  File "/usr/local/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 367, in _env_runner
    base_env.send_actions(actions_to_send)
  File "/usr/local/lib/python3.7/site-packages/ray/rllib/env/base_env.py", line 378, in send_actions
    obs, rewards, dones, infos = env.step(agent_dict)
  File "/Users/rpjludeke/Documents/dev/rllib/phm_env/envs/phm_env_maintenance.py", line 73, in step
    elif self.dones[agent] and time_step < time_remaining: 
KeyError: 'agent_518'

**Comment by OnTheRicky** [comment]
I had the other issue wrong, it's #4526
