### ISSUE TITLE
Error when using numba with ray

### ISSUE THREAD

**Issue by hmania** [ray-project/ray#831]
Running the following code from the command line gives the error message 

```
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:155) Killed worker pid 40767 which hadn't started yet.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ray/worker.py", line 1117, in fetch_and_register_remote_function
    function = pickle.loads(serialized_function)
  File "/home/ubuntu/anaconda2/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/home/ubuntu/anaconda2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/ubuntu/anaconda2/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/home/ubuntu/anaconda2/lib/python2.7/pickle.py", line 1130, in find_class
    __import__(module)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/numba/__init__.py", line 9, in <module>
    from . import config, errors, runtests, types
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/numba/config.py", line 232, in <module>
    _env_reloader = _EnvReloader()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/numba/config.py", line 68, in __init__
    self.reset()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/numba/config.py", line 72, in reset
    self.update(force=True)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/numba/config.py", line 84, in update
    self.process_environ(new_environ) 
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/numba/config.py", line 183, in process_environ
    ENABLE_AVX = _readenv("NUMBA_ENABLE_AVX", int, avx_default)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/numba/config.py", line 92, in _readenv
    return default() if callable(default) else default
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/numba/config.py", line 169, in avx_default
    if not _os_supports_avx():
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/numba/config.py", line 47, in _os_supports_avx
    or platform.machine() not in ('i386', 'i586', 'i686', 'x86_64')):
  File "/home/ubuntu/anaconda2/lib/python2.7/platform.py", line 1300, in machine
    return uname()[4]
  File "/home/ubuntu/anaconda2/lib/python2.7/platform.py", line 1230, in uname
    processor = _syscmd_uname('-p','')
  File "/home/ubuntu/anaconda2/lib/python2.7/platform.py", line 965, in _syscmd_uname
    rc = f.close()
IOError: [Errno 10] No child processes

```

```python
from numba import jit
import ray
import sys

def main(argv):

    ray.init()
    print "Ray init"

    print ray.get(f.remote())

    print ray.get(f.remote())

    print ray.get(f.remote())

    return

@jit(nopython=True)
def g():
    return 1 + 1

@ray.remote
def f():

    return g()

if __name__ == "__main__":
    main(sys.argv[1:])

```

**Comment by pcmoritz** [comment]
This seems to be the same as https://github.com/ray-project/ray/issues/745 and seems to be fixed on the latest master

**Comment by robertnishihara** [comment]
Ok, if you do `pip install -U ray` and get the latest version then it should work now.
