### ISSUE TITLE
[tune] How to save the ax and ray.tune search progress for the next training session?

### ISSUE THREAD

**Issue by showgood163** [ray-project/ray#8312]
### What is your question?
I'm using `tune.Trainable` and `tune.run` to search hyparams, like https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mnist_pytorch_trainable.py.

I want to save the hyparam search progress for another training session since my search space is so large and I don't want to waste any experiments.

And here are my questions:
1. What do I need to save? ax.client is a must, but what about ray.tune part? Maybe the scheduler?
2. How to save ax.client and ray.tune related things using `tune.run` or through other mechanism?

Thanks!

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.8.4, Python 3.8.2, Pytorch 1.5.0, arch linux

**Comment by richardliaw** [comment]
For saving hyperparameter search progress, I think you can just save `ax.client`. 

I think you should be able to use https://ax.dev/tutorials/gpei_hartmann_service.html#7.-Save-/-reload-optimization-to-JSON-/-SQL

```
ax_client.save_to_json_file()  # For custom filepath, pass `filepath` argument.
```
and for restore:
```
restored_ax_client = AxClient.load_from_json_file()  # For custom filepath, pass `filepath` argument.
```

and feed it back into the AxSearch module.

**Comment by showgood163** [comment]
Thanks for the comments!

I'm actually using the following code snippets for this:
```
while (True):
    try:
      tune.run(...)
    except:
      # don't know how to debug, just save
      ax_client.save_to_json_file(ax_file)
    ax_client.save_to_json_file(ax_file)
```

However, I find this snipped rather bloated. Is there a hook or something to save the progress immediately after the result update is happened?

**Comment by rherman9** [comment]
Hey, I'm also having troubles resuming progress while using AxSearch algorithm. 

When my tune experiment suddenly stops I can resume the experiment through: `resume=False` parameter in the tune.run function and the trials continue, however when a trial finishes I get the following errors:

```Traceback (most recent call last):
  File "/home/office/anaconda3/envs/py37/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 486, in _process_trial
    trial.trial_id, result=flat_result)
  File "/home/office/anaconda3/envs/py37/lib/python3.7/site-packages/ray/tune/suggest/suggestion.py", line 280, in on_trial_complete
    trial_id=trial_id, result=result, error=error)
  File "/home/office/anaconda3/envs/py37/lib/python3.7/site-packages/ray/tune/suggest/ax.py", line 98, in on_trial_complete
    self._process_result(trial_id, result)
  File "/home/office/anaconda3/envs/py37/lib/python3.7/site-packages/ray/tune/suggest/ax.py", line 102, in _process_result
    ax_trial_index = self._live_trial_mapping[trial_id]
KeyError: '4875d75a'

Traceback (most recent call last):
  File "/home/office/anaconda3/envs/py37/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 486, in _process_trial
    trial.trial_id, result=flat_result)
  File "/home/office/anaconda3/envs/py37/lib/python3.7/site-packages/ray/tune/suggest/suggestion.py", line 280, in on_trial_complete
    trial_id=trial_id, result=result, error=error)
  File "/home/office/anaconda3/envs/py37/lib/python3.7/site-packages/ray/tune/suggest/ax.py", line 98, in on_trial_complete
    self._process_result(trial_id, result)
  File "/home/office/anaconda3/envs/py37/lib/python3.7/site-packages/ray/tune/suggest/ax.py", line 102, in _process_result
    ax_trial_index = self._live_trial_mapping[trial_id]
KeyError: '4875d75a'
```

This only happens when I resume the trial.

**Any idea what the fix to this could be?**

**Comment by richardliaw** [comment]
I think this is now fixed on master.

**Comment by xiangdal** [comment]
I'm experiencing the same issue on release 1.6.0 with `SkOptSearch` as the optimizer.

**Comment by richardliaw** [comment]
@xiangdal can you open a new issue?

**Comment by xiangdal** [comment]
sure!
