### ISSUE TITLE
Tune error for PyTorch model

### ISSUE THREAD

**Issue by papilloncode** [ray-project/ray#8383]
### Error trying to use tube for hyperparameter tuning for a PyTorch model?

*Python version: 3.7.0, Torch version: 1.1.0.post2, Ray version 0.8.5, MacOS :*
 
Hi all,

It's the first time I am trying to use Tune for my PyTorch model. My model itself is running OK however when I tried to use Tune I got the following: 

`    def train_model(N_EPOCHS):
    

    for epoch in range(N_EPOCHS):

        start_time = time.time()
        optimizer = optim.Adam(model.parameters(), lr=config["lr"]) 
        train_loss, train_acc = train(model, train_loader, optimizer, criterion)
        valid_loss, valid_acc = evaluate(model, valid_iterator, criterion)
    
        end_time = time.time()

        epoch_mins, epoch_secs = epoch_time(start_time, end_time)
        tune.track.log(mean_accuracy=train_acc)
        print(f'Epoch: {epoch+1:02} | Epoch Time: {epoch_mins}m {epoch_secs}s')
        print(f'\tTrain Loss: {train_loss:.3f} | Train Acc: {train_acc*100:.2f}%')
        print(f'\t Val. Loss: {valid_loss:.3f} |  Val. Acc: {valid_acc*100:.2f}%')`

`analysis = tune.run(
    train_model,
    config={"lr": tune.grid_search([0.0005, 0.01])})`

 The Error I got

`2020-05-09 11:48:33,921	ERROR logger.py:196 -- pip install 'ray[tune]' to see TensorBoard files.
2020-05-09 11:48:33,924	WARNING logger.py:328 -- Could not instantiate TBXLogger: No module named 'tensorboardX'.
2020-05-09 11:48:34,395	WARNING worker.py:1090 -- Warning: The actor WrappedTrackFunc has size 17993759 when pickled. It will be stored in Redis, which could cause memory issues. This may mean that its definition uses a large array or other object.
2020-05-09 11:48:35,946	ERROR trial_runner.py:519 -- Trial train_model_00001: Error processing event.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 431, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/worker.py", line 1515, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): ray::WrappedTrackFunc.train() (pid=1591, ip=192.168.1.5)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 417, in ray._raylet.execute_task.function_executor
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/tune/function_runner.py", line 216, in _train
    self._report_thread_runner_error(block=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/tune/function_runner.py", line 259, in _report_thread_runner_error
    .format(err_tb_str)))
ray.tune.error.TuneError: Trial raised an exception. Traceback:
ray::WrappedTrackFunc.train() (pid=1591, ip=192.168.1.5)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/tune/function_runner.py", line 110, in run
    self._entrypoint()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/tune/function_runner.py", line 162, in entrypoint
    return self._trainable_func(config, self._status_reporter)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/tune/function_runner.py", line 288, in _trainable_func
    output = train_func(config)
  File "<ipython-input-56-b9344418465c>", line 4, in train_model
TypeError: 'dict' object cannot be interpreted as an integer
2020-05-09 11:48:35,959	ERROR trial_runner.py:519 -- Trial train_model_00000: Error processing event.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 431, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/worker.py", line 1515, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): ray::WrappedTrackFunc.train() (pid=1593, ip=192.168.1.5)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 417, in ray._raylet.execute_task.function_executor
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/tune/function_runner.py", line 216, in _train
    self._report_thread_runner_error(block=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/tune/function_runner.py", line 259, in _report_thread_runner_error
    .format(err_tb_str)))
ray.tune.error.TuneError: Trial raised an exception. Traceback:
ray::WrappedTrackFunc.train() (pid=1593, ip=192.168.1.5)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/tune/function_runner.py", line 110, in run
    self._entrypoint()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/tune/function_runner.py", line 162, in entrypoint
    return self._trainable_func(config, self._status_reporter)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/tune/function_runner.py", line 288, in _trainable_func
    output = train_func(config)
  File "<ipython-input-56-b9344418465c>", line 4, in train_model
TypeError: 'dict' object cannot be interpreted as an integer`

**Comment by richardliaw** [comment]
I think the typo is:

```
def train_model(config):  # Change this to config.
	for epoch in range(N_EPOCHS):
	
	    start_time = time.time()
	    optimizer = optim.Adam(model.parameters(), lr=config["lr"]) 
	    train_loss, train_acc = train(model, train_loader, optimizer, criterion)
	    valid_loss, valid_acc = evaluate(model, valid_iterator, criterion)
	
	    end_time = time.time()
	
	    epoch_mins, epoch_secs = epoch_time(start_time, end_time)
	    tune.track.log(mean_accuracy=train_acc)
	    print(f'Epoch: {epoch+1:02} | Epoch Time: {epoch_mins}m {epoch_secs}s')
	    print(f'\tTrain Loss: {train_loss:.3f} | Train Acc: {train_acc*100:.2f}%')
	    print(f'\t Val. Loss: {valid_loss:.3f} |  Val. Acc: {valid_acc*100:.2f}%')`
