### ISSUE TITLE
Error while shutting down Ray

### ISSUE THREAD

**Issue by mehrdadn** [ray-project/ray#8385]
### What is the problem?

I believe this problem has existed for a long time; currently I'm reproducing it on the latest master (`93138e6`) using Python 3.7 (miniconda) on Ubuntu.

### Reproduction (REQUIRED)

Create `python/test.py`:

```
import errno
import os
import subprocess
import sys
import time

import ray

if sys.platform == "win32":
    import _winapi

def _pid_alive(pid):
    try:
        os.kill(pid, 0)
        return True
    except OSError:
        return False

def wait_for_pid_to_exit(pid, timeout=5):
    start_time = time.time()
    while time.time() - start_time < timeout:
        if not _pid_alive(pid):
            return
        time.sleep(1.0 / 60)
    raise subprocess.TimeoutExpired("Timed out while waiting for process {} to exit.".format(pid), timeout)

@ray.remote(max_calls=1, max_retries=0)
def hello():
    return os.getpid()

def test():
    ray.init(num_cpus=1, memory=1<<28, object_store_memory=1<<27)

    wait_for_pid_to_exit(ray.get(hello.remote()))

def main():
    test()

if __name__ == '__main__':
    raise SystemExit(main() or 0)
```

Now `cd python && pip install -e .` and run the code to get this:

```
$ cd python && GLOG_logtostderr=1 GLOG_minloglevel=1 RAY_BACKEND_LOG_LEVEL=warning python3 -u test.py
2020-05-09 04:56:41,356 INFO resource_spec.py:212 -- Starting Ray with 0.24 GiB memory available for workers and up to 0.12 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
29555:C 09 May 2020 04:56:41.361 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
29555:C 09 May 2020 04:56:41.361 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=29555, just started
29555:C 09 May 2020 04:56:41.361 # Configuration loaded
29555:M 09 May 2020 04:56:41.362 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
29555:M 09 May 2020 04:56:41.362 # Server initialized
29555:M 09 May 2020 04:56:41.362 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
29555:M 09 May 2020 04:56:41.362 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
29559:C 09 May 2020 04:56:41.466 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
29559:C 09 May 2020 04:56:41.466 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=29559, just started
29559:C 09 May 2020 04:56:41.466 # Configuration loaded
29559:M 09 May 2020 04:56:41.467 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
29559:M 09 May 2020 04:56:41.467 # Server initialized
29559:M 09 May 2020 04:56:41.467 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
29559:M 09 May 2020 04:56:41.467 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
2020-05-09 04:56:41,636 INFO services.py:1170 -- View the Ray dashboard at localhost:8265
Ray worker pid: 29592
Ray worker pid: 29592
W0509 04:56:42.045264 29592 reference_count.cc:196] Tried to decrease ref count for nonexistent object ID: 34f0e641eb6beb92a5cbdc0f9ee9000800000000
W0509 04:56:42.177042 29554 reference_count.cc:196] Tried to decrease ref count for nonexistent object ID: 11b96a4925d347c2668febfe90f6000800000000
======== Running on http://localhost:8265 ========
(Press CTRL+C to quit)
29555:signal-handler (1589025402) Received SIGTERM scheduling shutdown...
29555:M 09 May 2020 04:56:42.965 # User requested shutdown...
29555:M 09 May 2020 04:56:42.965 # Redis is now ready to exit, bye bye...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "~/miniconda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "~/ray/python/ray/dashboard/dashboard.py", line 789, in run
    for x in p.listen():
  File "~/miniconda/lib/python3.7/site-packages/redis/client.py", line 3285, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "~/miniconda/lib/python3.7/site-packages/redis/client.py", line 3185, in parse_response
    response = self._execute(conn, conn.read_response)
  File "~/miniconda/lib/python3.7/site-packages/redis/client.py", line 3159, in _execute
    return command(*args, **kwargs)
  File "~/miniconda/lib/python3.7/site-packages/redis/connection.py", line 700, in read_response
    response = self._parser.read_response()
  File "~/miniconda/lib/python3.7/site-packages/redis/connection.py", line 310, in read_response
    response = self._buffer.readline()
  File "~/miniconda/lib/python3.7/site-packages/redis/connection.py", line 242, in readline
    self._read_from_socket()
  File "~/miniconda/lib/python3.7/site-packages/redis/connection.py", line 187, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

29559:signal-handler (1589025402) Received SIGTERM scheduling shutdown...
29559:M 09 May 2020 04:56:42.973 # User requested shutdown...
29559:M 09 May 2020 04:56:42.973 # Redis is now ready to exit, bye bye...
*** Aborted at 1589025402 (unix time) try "date -d @1589025402" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGTERM (@0x3e900007372) received by PID 29563 (TID 0x7ff6a1424800) from PID 29554; stack trace: ***
    @     0x7ff6a08da890 (unknown)
    @     0x7ff6a01d8bb7 epoll_wait
    @     0x55fe47f41384 boost::asio::detail::epoll_reactor::run()
    @     0x55fe47f441f9 boost::asio::detail::scheduler::do_run_one()
    @     0x55fe47f3ec62 boost::asio::detail::scheduler::run()
    @     0x55fe47f3eafc boost::asio::io_context::run()
    @     0x55fe47c0e7f7 ray::gcs::GcsServer::Start()
    @     0x55fe47c08de2 main
    @     0x7ff6a00d8b97 __libc_start_main
    @     0x55fe47c084aa _start
Traceback (most recent call last):
  File "~/ray/python/ray/dashboard/dashboard.py", line 957, in run
    node_manager_pb2.GetNodeStatsRequest(), timeout=2)
  File "~/miniconda/lib/python3.7/site-packages/grpc/_channel.py", line 824, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "~/miniconda/lib/python3.7/site-packages/grpc/_channel.py", line 726, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1589025403.351872679","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1589025403.351870172","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
>
Traceback (most recent call last):
  File "~/ray/python/ray/dashboard/dashboard.py", line 957, in run
    node_manager_pb2.GetNodeStatsRequest(), timeout=2)
  File "~/miniconda/lib/python3.7/site-packages/grpc/_channel.py", line 824, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "~/miniconda/lib/python3.7/site-packages/grpc/_channel.py", line 726, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1589025403.351872679","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1589025403.351870172","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
>
Exception in thread Thread-2:
Traceback (most recent call last):
  File "~/miniconda/lib/python3.7/site-packages/redis/connection.py", line 1079, in get_connection
    if connection.can_read():
  File "~/miniconda/lib/python3.7/site-packages/redis/connection.py", line 695, in can_read
    return self._parser.can_read(timeout)
  File "~/miniconda/lib/python3.7/site-packages/redis/connection.py", line 307, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "~/miniconda/lib/python3.7/site-packages/redis/connection.py", line 217, in can_read
    raise_on_timeout=False)
  File "~/miniconda/lib/python3.7/site-packages/redis/connection.py", line 187, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/miniconda/lib/python3.7/site-packages/redis/connection.py", line 539, in connect
    sock = self._connect()
  File "~/miniconda/lib/python3.7/site-packages/redis/connection.py", line 596, in _connect
    raise err
  File "~/miniconda/lib/python3.7/site-packages/redis/connection.py", line 584, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/miniconda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "~/ray/python/ray/dashboard/dashboard.py", line 971, in run
    self._update_nodes()
  File "~/ray/python/ray/dashboard/dashboard.py", line 860, in _update_nodes
    self.nodes = ray.nodes()
  File "~/ray/python/ray/state.py", line 1008, in nodes
    return state.client_table()
  File "~/ray/python/ray/state.py", line 379, in client_table
    client_table = _parse_client_table(self.redis_client)
  File "~/ray/python/ray/state.py", line 31, in _parse_client_table
    NIL_CLIENT_ID)
  File "~/miniconda/lib/python3.7/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "~/miniconda/lib/python3.7/site-packages/redis/connection.py", line 1083, in get_connection
    connection.connect()
  File "~/miniconda/lib/python3.7/site-packages/redis/connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 172.31.9.85:19311. Connection refused.
```

Note that the errors and stack traces can vary (depending on during which call Redis terminates), and the C++ error may or may not appear, but there should be no error at all.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
I guess some of components still try to access the worker that is killed by os.kill?

**Comment by mustafaKus** [comment]
Hello, Is there any progress on this?

I have tried to implement ray.tune into our company codebase and I am getting the same error. After everything is running, I am getting this instead of closing the processes healthily.

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
