### ISSUE TITLE
[raySGD] Error when increasing the number of replicas (Without GPUs)

### ISSUE THREAD

**Issue by SanjiAp** [ray-project/ray#8444]
```
trainer1 = TorchTrainer(
    model_creator=model_creator,
    data_creator=data_creator,
    optimizer_creator=optimizer_creator,
    loss_creator=torch.nn.MSELoss,
    num_workers=2,
    use_gpu=False,
    config={"batch_size": 64})

 ray.init()
stats = trainer1.train()
```
I am running above code on a machine with no GPUs. 
I want to run above code on CPU based machine.
So I am getting the following error : 
### When using with pytorch 
```
2020-05-13 18:03:41,188 INFO resource_spec.py:212 -- Starting Ray with 157.67 GiB memory available for workers and up to 71.58 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-05-13 18:03:41,570 INFO services.py:1170 -- View the Ray dashboard at localhost:8266
Traceback (most recent call last):
  File "torch_trainer.py", line 32, in <module>
    config={"batch_size": 64})
  File "/home/amey/anaconda3/envs/lib/python3.6/site-packages/ray/util/sgd/torch/torch_trainer.py", line 274, in __init__
    self._start_workers(self.max_replicas)
  File "/home/amey/anaconda3/envs/lib/python3.6/site-packages/ray/util/sgd/torch/torch_trainer.py", line 373, in _start_workers
    self.local_worker.setup_ddp_and_operator()
  File "/home/amey/anaconda3/envs/lib/python3.6/site-packages/ray/util/sgd/torch/distributed_torch_runner.py", line 94, in setup_ddp_and_operator
    for model in self.models
  File "/home/amey/anaconda3/envs/lib/python3.6/site-packages/ray/util/sgd/torch/distributed_torch_runner.py", line 94, in <listcomp>
    for model in self.models
  File "/home/amey/anaconda3/envs/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 189, in __init__
    output_device = device_ids[0]
IndexError: list index out of range
2020-05-13 18:03:44,019 ERROR worker.py:1030 -- Possible unhandled error from worker: ray::DistributedTorchRunner.setup_ddp_and_operator() (pid=2610, ip=192.168.140.49)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 417, in ray._raylet.execute_task.function_executor
  File "/home/amey/anaconda3/envs/lib/python3.6/site-packages/ray/util/sgd/torch/distributed_torch_runner.py", line 94, in setup_ddp_and_operator
    for model in self.models
  File "/home/amey/anaconda3/envs/lib/python3.6/site-packages/ray/util/sgd/torch/distributed_torch_runner.py", line 94, in <listcomp>
    for model in self.models
  File "/home/amey/anaconda3/envs/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 189, in __init__
    output_device = device_ids[0]
IndexError: list index out of range
```

-------------------------------------------------------------------------------------------------
### When using with tensorflow:

```
def train_example(num_replicas=1, batch_size=128, use_gpu=False):
    trainer = TFTrainer(
        model_creator=simple_model,
        data_creator=simple_dataset,
        num_replicas=num_replicas,
        use_gpu=use_gpu,
        verbose=True,
        config=create_config(batch_size))

    # model baseline performance
    start_stats = trainer.validate()
    print(start_stats)
    start = time.time()
    # train for 2 epochs
```

```
id=1723) W0514 16:06:19.146158 139689939883840 distribute_coordinator.py:825] `eval_fn` is not passed in. The `worker_fn` will be used if an "evaluator" task exists in the cluster.
(pid=1723) W0514 16:06:19.146368 139689939883840 distribute_coordinator.py:829] `eval_strategy` is not passed in. No distribution strategy will be used for evaluation.
(pid=1723) 2020-05-14 16:06:19.163638: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:434] In AUTO-mode, and switching to DATA-based sharding, instead of FILE-based sharding as we cannot find appropriate reader dataset op(s) to shard. Error: Found an unshardable source dataset: name: "TensorSliceDataset/_2"
(pid=1723) op: "TensorSliceDataset"
(pid=1723) input: "Placeholder/_0"
(pid=1723) input: "Placeholder/_1"
(pid=1723) attr {
(pid=1723)   key: "Toutput_types"
(pid=1723)   value {
(pid=1723)     list {
(pid=1723)       type: DT_DOUBLE
(pid=1723)       type: DT_DOUBLE
(pid=1723)     }
(pid=1723)   }
(pid=1723) }
(pid=1723) attr {
(pid=1723)   key: "output_shapes"
(pid=1723)   value {
(pid=1723)     list {
(pid=1723)       shape {
(pid=1723)         dim {
(pid=1723)           size: 1
(pid=1723)         }
(pid=1723)       }
(pid=1723)       shape {
(pid=1723)         dim {
(pid=1723)           size: 1
(pid=1723)         }
(pid=1723)       }
(pid=1723)     }
(pid=1723)   }
(pid=1723) }
(pid=1723)





Versions used
Ray : 0.8.5
Python : 3.6.7
TF : 2.2.0
OS : CentOS Linux 7
```

**Comment by robertnishihara** [comment]
@richardliaw

**Comment by amogkam** [comment]
We have now deprecated Ray SGD and have replaced with with [Ray Train](https://docs.ray.io/en/latest/train/train.html) which provides a more flexible API for distributed deep learning training on Ray! 

With Ray Train, this issue should be resolved!
