### ISSUE TITLE
EvolutionStrategies algorithm doesn't run on Pong-v0.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#847]
This occurs on both Ubuntu 16 and MacOS (I tried Anaconda Python 3).

EvolutionStrategies can be run on Pong with the following command.

```
python ray/python/ray/rllib/train.py --alg=EvolutionStrategies --env=Pong-v0
```

This fails very quickly with the following error.

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/home/ubuntu/anaconda3/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Can not squeeze dim[1], expected a dimension of 1, got 18 for 'GenericPolicy/vision_net/Squeeze' (op: 'Squeeze') with input shapes: [?,18,11,6].
```

The error can be reproduced more easily as follows.

```python
import gym
from ray.rllib.models import ModelCatalog
import tensorflow as tf

env = gym.make("Pong-v0")

inputs = tf.placeholder(tf.float32, [None] + list(env.observation_space.shape))

ModelCatalog.get_model(inputs, env.action_space.n)
```

cc @ericl

**Comment by ericl** [comment]
Will take a look

**Comment by ericl** [comment]
https://github.com/ray-project/ray/pull/848 should fix this
