### ISSUE TITLE
[rllib] Rainbow DQN fails when `noisy` parameter is True. Asks to register variables.

### ISSUE THREAD

**Issue by AnanthHari** [ray-project/ray#8544]
### What is the problem?
Ray version: 0.9.0.dev0 (the latest nightly wheel)
Python version: 3.7.6
OS: Ubuntu 18.04

I wanted to run DQN method with the improvements in the Rainbow paper included. I tried setting parameters as mentioned in this [comment on issue #7035](https://github.com/ray-project/ray/issues/7035#issuecomment-582006834).

### Reproduction (REQUIRED)
Here is the script (`test_rainbow_dqn.py`) I used to reproduce the issue on a dummy environment.
```
import numpy as np
import ray
from ray import tune
from ray.tune.registry import register_env
import gym.spaces
from ray.rllib.env.multi_agent_env import MultiAgentEnv
from ray.rllib.utils import try_import_tf
from ray.rllib.models.tf.tf_modelv2 import TFModelV2
from ray.rllib.models import ModelCatalog

tf = try_import_tf()


class MyEnv(MultiAgentEnv):
    def __init__(self):
        self.num_agents = 2
        self.agent_ids = list(range(self.num_agents))
        self.action_space_dict = dict(
            zip(self.agent_ids, [gym.spaces.Discrete(2)] * self.num_agents))
        self.observation_space_dict = dict(zip(self.agent_ids, [
            gym.spaces.Box(low=0, high=1, shape=(1,))] * self.num_agents))
    
    def reset(self):
        return {agent_id: np.array([0]) for agent_id in self.agent_ids}
    
    def step(self, action):
        obs_dict = {agent_id: np.array([0]) for agent_id in self.agent_ids}
        rewards_dict = {agent_id: 0 for agent_id in self.agent_ids}
        done_dict = {agent_id: True for agent_id in self.agent_ids}
        done_dict['__all__'] = True
        info_dict = {agent_id: {} for agent_id in self.agent_ids}
        return obs_dict, rewards_dict, done_dict, info_dict


class MLPModelV2(TFModelV2):
    def __init__(self, obs_space, action_space, num_outputs, model_config,
                 name="my_model"):
        super().__init__(obs_space, action_space, num_outputs, model_config,
                         name)
        # Simplified to one layer.
        input = tf.keras.layers.Input(obs_space.shape, dtype=obs_space.dtype)
        output = tf.keras.layers.Dense(num_outputs, activation=None)
        self.base_model = tf.keras.models.Sequential([input, output])
        self.register_variables(self.base_model.variables)

    def forward(self, input_dict, state, seq_lens):
        return self.base_model(input_dict["obs"]), []


if __name__ == "__main__":
    ray.init()
    ModelCatalog.register_custom_model("MLPModel", MLPModelV2)

    def env_creator(args):
        return MyEnv()
    
    env = env_creator(1)
    register_env("TestEnv", env_creator)
    obs_space = env.observation_space_dict[0]
    act_space = env.action_space_dict[0]

    def gen_policy(i):
        config = {
            "model": {
                "custom_model": "MLPModel",
            },
            "gamma": 0.99,
        }
        return (None, obs_space, act_space, config)

    policies = {"policy_0": gen_policy(0)}
    policy_ids = list(policies.keys())

    # Rainbow DQN
    tune.run(
        "DQN",
        stop={"episodes_total": 60000},
        checkpoint_freq=10,
        config={
    
            # Enviroment specific
            "env": "TestEnv",
    
            # General
            "log_level": "ERROR",
            "num_gpus": 1,
            "num_workers": 8,
            "num_envs_per_worker": 8,
            "learning_starts": 1000,
            "buffer_size": int(1e5),
            "compress_observations": True,
            "sample_batch_size": 20,
            "train_batch_size": 512,
            "gamma": .99,
    
            # Method specific
            "num_atoms": 51,
            "dueling": True,
            "double_q": True,
            "n_step": 2,
            "batch_mode": "complete_episodes",
            "prioritized_replay": True,

            # alternative 1
            "noisy": True,
            # alternative 2
            #"parameter_noise": True,
    
            "multiagent": {
                "policies": policies,
                "policy_mapping_fn": (
                    lambda agent_id: policy_ids[0]),
            },
        },
    )
```

There are two alternatives suggested in the comment mentioned above:
Use the parameter: (a) `"noisy":True` OR (b) `"parameter_noise": True`.

Using option (b): I could successfully run `test_rainbow_dqn.py` without any errors.

However, when I used option (a), I got the following error:
```
Failure # 1 (occurred at 2020-05-21_22-57-14)
Traceback (most recent call last):
  File "/home/ananth/miniconda3/envs/rllib_dev/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/ananth/miniconda3/envs/rllib_dev/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 430, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/ananth/miniconda3/envs/rllib_dev/lib/python3.7/site-packages/ray/worker.py", line 1522, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ^[[36mray::DQN.train()^[[39m (pid=15418, ip=129.2.189.146)
  File "python/ray/_raylet.pyx", line 421, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 456, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 460, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 414, in ray._raylet.execute_task.function_executor
  File "/home/ananth/miniconda3/envs/rllib_dev/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 90, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/ananth/miniconda3/envs/rllib_dev/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 450, in __init__
    super().__init__(config, logger_creator)
  File "/home/ananth/miniconda3/envs/rllib_dev/lib/python3.7/site-packages/ray/tune/trainable.py", line 174, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/ananth/miniconda3/envs/rllib_dev/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 593, in _setup
    self._init(self.config, self.env_creator)
  File "/home/ananth/miniconda3/envs/rllib_dev/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 115, in _init
    self.config["num_workers"])
  File "/home/ananth/miniconda3/envs/rllib_dev/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 664, in _make_workers
    logdir=self.logdir)
  File "/home/ananth/miniconda3/envs/rllib_dev/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 59, in __init__
    RolloutWorker, env_creator, policy, 0, self._local_config)
  File "/home/ananth/miniconda3/envs/rllib_dev/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 282, in _make_worker
    extra_python_environs=extra_python_environs)
  File "/home/ananth/miniconda3/envs/rllib_dev/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 378, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/home/ananth/miniconda3/envs/rllib_dev/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 930, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/home/ananth/miniconda3/envs/rllib_dev/lib/python3.7/site-packages/ray/rllib/policy/tf_policy_template.py", line 143, in __init__
    obs_include_prev_action_reward=obs_include_prev_action_reward)
  File "/home/ananth/miniconda3/envs/rllib_dev/lib/python3.7/site-packages/ray/rllib/policy/dynamic_tf_policy.py", line 156, in __init__
    self.model = make_model(self, obs_space, action_space, config)
  File "/home/ananth/miniconda3/envs/rllib_dev/lib/python3.7/site-packages/ray/rllib/agents/dqn/dqn_tf_policy.py", line 160, in build_q_model
    or config["exploration_config"]["type"] == "ParameterNoise")
  File "/home/ananth/miniconda3/envs/rllib_dev/lib/python3.7/site-packages/ray/rllib/models/catalog.py", line 337, in get_model_v2
    registered))
ValueError: It looks like variables {<tf.Variable 'policy_0/q_func/state_value/dueling_hidden_0_sigma_b:0' shape=(256,) dtype=float32_ref>, <tf.Variable 'policy_0/q_func/action_value/hidden_0_sigma_w:0' shape=(256, 256) dtype=float32_ref>, <tf.Variable 'policy_0/q_func/action_value/hidden_0_fc_w:0' shape=(256, 256) dtype=float32_ref>, <tf.Variable 'policy_0/q_func/state_value/dueling_hidden_0_sigma_w:0' shape=(256, 256) dtype=float32_ref>, <tf.Variable 'policy_0/q_func/state_value/dueling_output_sigma_w:0' shape=(256, 51) dtype=float32_ref>, <tf.Variable 'policy_0/q_func/action_value/hidden_0_sigma_b:0' shape=(256,) dtype=float32_ref>, <tf.Variable 'policy_0/q_func/state_value/dueling_output_sigma_b:0' shape=(51,) dtype=float32_ref>, <tf.Variable 'policy_0/q_func/state_value/dueling_output_fc_w:0' shape=(256, 51) dtype=float32_ref>, <tf.Variable 'policy_0/q_func/action_value/hidden_0_fc_b:0' shape=(256,) dtype=float32_ref>, <tf.Variable 'policy_0/q_func/action_value/output_sigma_w:0' shape=(256, 102) dtype=float32_ref>, <tf.Variable 'policy_0/q_func/action_value/output_fc_b:0' shape=(102,) dtype=float32_ref>, <tf.Variable 'policy_0/q_func/state_value/dueling_hidden_0_fc_b:0' shape=(256,) dtype=float32_ref>, <tf.Variable 'policy_0/q_func/action_value/output_sigma_b:0' shape=(102,) dtype=float32_ref>, <tf.Variable 'policy_0/q_func/action_value/output_fc_w:0' shape=(256, 102) dtype=float32_ref>, <tf.Variable 'policy_0/q_func/state_value/dueling_hidden_0_fc_w:0' shape=(256, 256) dtype=float32_ref>, <tf.Variable 'policy_0/q_func/state_value/dueling_output_fc_b:0' shape=(51,) dtype=float32_ref>} were created as part of <ray.rllib.models.catalog.MLPModelV2_as_DistributionalQTFModel object at 0x7f443af5af50> but does not appear in model.variables() ({<tf.Variable 'policy_0/dense/kernel:0' shape=(1, 256) dtype=float32>, <tf.Variable 'policy_0/dense/bias:0' shape=(256,) dtype=float32>}). Did you forget to call model.register_variables() on the variables in question?

```

Thanks for your help!

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by justinkterry** [comment]
@sven1977 do you have any idea what the problem here is?

**Comment by ejmejm** [comment]
I'm also getting this error. I'm guessing the issue is just as listed, it looks like the the parameters that are added to the model are not being registered. I'm not sure if there is a way to manually register them, but either way it seems like it would make sense for that to be automated.

**Comment by ejmejm** [comment]
I've found the problem and implemented a simple solution on my local branch. The issue was that there is a bug with either TF or Keras such that the created noisy variables are not tracked, so the following 2 lines ([here](https://github.com/ray-project/ray/blob/master/rllib/agents/dqn/distributional_q_tf_model.py#L196) and [here](https://github.com/ray-project/ray/blob/master/rllib/agents/dqn/distributional_q_tf_model.py#L201)) that should return the noisy variables instead return empty lists and are not registered with the model.

I solved this by explicitly tracking the new variables with a list and registering the variables from that list. I will make a pull to fix the bug if I have time, but I would need to set up the environment and write tests as I haven't developed on this project before. So if anyone wants to do the ~5 line fix before me please feel free to.

**Comment by justinkterry** [comment]
Make a PR for your code without tests and I'll deal with tests

**Comment by kaixin96** [comment]
I met the same problem when using a custom model. One workaround I found is to explicitly pass `CustomModel` class to `default_model` argument in `ModelCatalog.get_model_v2()`. By default, `ray.rllib.agents.dqn.dqn_tf_policy.build_q_model` calls `ModelCatalog.get_model_v2()` with `default_model=None`.

**Comment by dvVenuto** [comment]
I am having this same issue with a custom model.  It is still returning None when calling ModelCatalog.get_model_v2().
