### ISSUE TITLE
Submit jobs to ray using celery.

### ISSUE THREAD

**Issue by terodea** [ray-project/ray#8610]
#### How to submit jobs to ray using celery
I've tried implementing a toy example for it. Below is the code for it.
```python
from celery import Celery, signals
import logging
import ray
celery = Celery('tasks', broker='redis://localhost:6379/0', backend='redis://localhost')
@celery.task
def add(value):
    ray.init()
    to = remote_chain_function.remote(value)
    return to


@ray.remote
def remote_chain_function(value):
    return value + 1
```

Error:
```
[2020-05-25 00:21:07,473: ERROR/ForkPoolWorker-5] Task mytasks.add[4a2f6fba-4f1b-4a77-95a0-0ee3c488a927] raised unexpected: AttributeError("'LoggingProxy' object has no attribute 'fileno'",)
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 382, in trace_task
R = retval = fun(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 641, in __protected_call__
return self.run(*args, **kwargs)
File "/home/akshay/Desktop/mytasks.py", line 15, in add
ray.init()
File "/home/akshay/.local/lib/python3.5/site-packages/ray/worker.py", line 1453, in init
driver_id=driver_id)
File "/home/akshay/.local/lib/python3.5/site-packages/ray/worker.py", line 1716, in connect
faulthandler.enable(all_threads=False)
AttributeError: 'LoggingProxy' object has no attribute 'fileno'
```
I've also tried with starting the ray and celery on same node and removed ray.init() from the code. But nothing seeems to work
Use this to start ray 
```bash
ray start --head --port=6379
```
Code goes like thsi

```python
from celery import Celery, signals
import logging
import ray
celery = Celery('tasks', broker='redis://localhost:6379/0', backend='redis://localhost')
@celery.task
def add(value):
    to = remote_chain_function.remote(value)
    return to


@ray.remote
def remote_chain_function(value):
    return value + 1
```

```
[2020-05-26 16:35:41,675: INFO/MainProcess] Connected to redis://localhost:6379//
[2020-05-26 16:35:41,684: INFO/MainProcess] mingle: searching for neighbors
[2020-05-26 16:35:42,705: INFO/MainProcess] mingle: all alone
[2020-05-26 16:35:42,713: INFO/MainProcess] celery@xflow ready.
[2020-05-26 16:35:51,539: INFO/MainProcess] Received task: mytasks.add[0174a3e6-722c-4a73-ac2a-b3a47cddd7ce]  
[2020-05-26 16:35:51,545: ERROR/ForkPoolWorker-8] Task mytasks.add[0174a3e6-722c-4a73-ac2a-b3a47cddd7ce] raised unexpected: RayConnectionError("Ray has not been started yet. You can start Ray with 'ray.init()'.",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/akshay/Desktop/mytasks.py", line 16, in add
    to = remote_chain_function.remote(value)
  File "/home/akshay/.local/lib/python3.6/site-packages/ray/remote_function.py", line 81, in _remote_proxy
    return self._remote(args=args, kwargs=kwargs)
  File "/home/akshay/.local/lib/python3.6/site-packages/ray/remote_function.py", line 116, in _remote
    worker.check_connected()
  File "/home/akshay/.local/lib/python3.6/site-packages/ray/worker.py", line 257, in check_connected
    raise RayConnectionError("Ray has not been started yet. You can "
ray.worker.RayConnectionError: Ray has not been started yet. You can start Ray with 'ray.init()'.
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python3.6.10
Ray 0.7.2
Ubuntu 16.04

**Comment by rkooo567** [comment]
Thanks for posting this here! I will try out the same thing this weekends and let you know how it goes. Please ping me one more time if I don't get back to you by next week (I can forget about it because of other priorities). 

Also, would you be able to use the newer version of Ray? (since I will try to make it work with the latest version)

**Comment by terodea** [comment]
I've tried it on the latest version I'm still getting the same error.

**Comment by rkooo567** [comment]
I spent some time to look at this issue, and it looks like the problem is from celery. Here is a related issue. https://github.com/celery/celery/issues/928

Celery basically wraps the stdout to their own wrapper, LoggingProxy, and this is not compatible to our code here. https://github.com/ray-project/ray/blob/d8a081a185271cf9fa352f7ae2c93abdbef6858a/python/ray/worker.py#L1138

As an example, this will be broken with the same error although you don't use Ray.
```python3
from celery import Celery, signals
import logging
import ray
celery = Celery('tasks', broker='redis://localhost:6379/0', backend='redis://localhost')

@celery.task
def add(value):
    import faulthandler
    faulthandler.enable(all_threads=False)
    return 3

result = add.delay(4)
print(result.ready())
```

The solution is to remove the usage of fault handler manually.
https://github.com/ray-project/ray/blob/d8a081a185271cf9fa352f7ae2c93abdbef6858a/python/ray/worker.py#L1138

and rebuild Ray following this. https://docs.ray.io/en/latest/development.html#compilation

I am not sure if there's a way to not configure LoggingProxy in celery. If it is possible, this could be a solution too. 

After I rebuilt the project I could make it run successfully.

I first ran 
`ray start --head`.
And I ran this script.
```python3
from celery import Celery, signals
import logging
import ray
celery = Celery('tasks', broker='redis://localhost:6379/0', backend='redis://localhost')

@celery.task
def add(value):
    @ray.remote
    def remote_chain_function(value):
        return value + 1
    ray.init(address='auto')
    to = ray.get(remote_chain_function.remote(value))
    return to

result = add.delay(4)
print(result.ready())
```

Logs
```
 -------------- celery@SangBins-MBP.attlocal.net v4.4.2 (cliffs)
--- ***** ----- 
-- ******* ---- Darwin-19.4.0-x86_64-i386-64bit 2020-05-31 12:19:49
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x101aa9650
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost/
- *** --- * --- .> concurrency: 16 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . celery_queue.add

[2020-05-31 12:19:50,437: INFO/MainProcess] Connected to redis://localhost:6379/0
[2020-05-31 12:19:50,450: INFO/MainProcess] mingle: searching for neighbors
[2020-05-31 12:19:51,460: INFO/MainProcess] mingle: all alone
[2020-05-31 12:19:51,481: INFO/MainProcess] celery@SangBins-MBP.attlocal.net ready.
[2020-05-31 12:19:51,596: INFO/MainProcess] Received task: celery_queue.add[88243c46-4761-4349-83fd-c84bedb578f9]  
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0531 12:19:51.634101  1580 106298816 global_state_accessor.cc:25] Redis server address = 192.168.1.82:56033, is test flag = 0
I0531 12:19:51.635701  1580 106298816 redis_client.cc:141] RedisClient connected.
I0531 12:19:51.637811  1580 106298816 redis_gcs_client.cc:88] RedisGcsClient Connected.
I0531 12:19:51.638792  1580 106298816 service_based_gcs_client.cc:74] ServiceBasedGcsClient Connected.
[2020-05-31 12:19:51,672: INFO/ForkPoolWorker-15] Task celery_queue.add[88243c46-4761-4349-83fd-c84bedb578f9] succeeded in 0.07361922500000029s: 5
^C
worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
```

**Comment by terodea** [comment]
Awesome ! Thanks for taking out some time and helping out.

**Comment by afparsons** [comment]
Is there any way as of 2021-11-01 to make this work without compiling Ray?

I'm simply trying to set a periodic Celery task to check whether or not some Ray Serve Deployments exist.

**Comment by tanmaychimurkar** [comment]
@NumberChiffre Thanks for your response. I am also facing the same issue, but instead of Celery, I am using Apache Airflow: https://airflow.apache.org/docs/apache-airflow/stable/index.html

My whole training pipeline in Ray rllib is working correctly without the Airflow integration, but with Airflow I am facing the same issue as mentioned by @terodea. Any idea on how I can solve this issue with Apache Airflow?
