### ISSUE TITLE
Restoring from checkpoint on different machine

### ISSUE THREAD

**Issue by jangkj09** [ray-project/ray#8622]
### What is your question?
I trained a model on one machine and I am able to load and restore properly from a saved checkpoint on that machine. When I copied over the checkpoint and try to restore and execute on a different machine, I get the following error:

```
Traceback (most recent call last):
  File "test_rllib_model.py", line 77, in <module>
    test_agent.restore(checkpoint_path)
  File "/home/mlab/rl_dev/lib/python3.6/site-packages/ray/tune/trainable.py", line 417, in restore
    self._restore(checkpoint_path)
  File "/home/mlab/rl_dev/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 639, in _restore
    self.__setstate__(extra_data)
  File "/home/mlab/rl_dev/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 192, in __setstate__
    Trainer.__setstate__(self, state)
  File "/home/mlab/rl_dev/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 1070, in __setstate__
    self.optimizer.restore(state["optimizer"])
AttributeError: 'NoneType' object has no attribute 'restore'
```
Am I missing some files or something? I've copied over all the files in the checkpoint directory and also the `params.pkl` and `params.json` file. 
I'm creating a trainer instance and restoring from the checkpoint. 

*Ray version and other system information (Python version, TensorFlow version, OS):*

**Comment by sven1977** [comment]
Maybe the ray versions are different on the two machines? Could you post your specs?

**Comment by jangkj09** [comment]
Yes, that solved the problem. On one machine I had the stable 0.8.5 and on the other I had 0.9.0.dev0
Re-installing with 0.8.5 resolved the problem. 

I don't know if this exists somewhere in the docs, but it would be helpful to indicate this difference more explicitly. I spent over an hour trying to debug what was going on. Thanks!
