### ISSUE TITLE
[Autoscaler] K8s Error on First `ray up`

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#8678]
### What is the problem?
```
$ ray up python/ray/autoscaler/kubernetes/example-full.yaml
2020-05-29 13:42:03,922 INFO config.py:65 -- KubernetesNodeProvider: using existing namespace 'ray'
2020-05-29 13:42:03,926 INFO config.py:94 -- KubernetesNodeProvider: using existing autoscaler_service_account 'autoscaler'
2020-05-29 13:42:03,945 INFO config.py:120 -- KubernetesNodeProvider: using existing autoscaler_role 'autoscaler'
2020-05-29 13:42:03,948 INFO config.py:153 -- KubernetesNodeProvider: using existing autoscaler_role_binding 'autoscaler'
2020-05-29 13:42:03,954 INFO config.py:186 -- KubernetesNodeProvider: updating existing service 'ray-head'
2020-05-29 13:42:03,978 INFO config.py:186 -- KubernetesNodeProvider: updating existing service 'ray-workers'
This will create a new cluster [y/N]: y
2020-05-29 13:42:05,845 INFO commands.py:202 -- get_or_create_head_node: Launching new head node...
2020-05-29 13:42:05,845 INFO node_provider.py:78 -- KubernetesNodeProvider: calling create_namespaced_pod (count=1).
2020-05-29 13:42:05,875 INFO commands.py:222 -- get_or_create_head_node: Updating files on head node...
2020-05-29 13:42:05,876 INFO updater.py:341 -- NodeUpdater: ray-head-hvj98: Updating to 5431afd4447d4a1d05b060e89e6dec6b7f712dbc
2020-05-29 13:42:05,901 INFO log_timer.py:17 -- NodeUpdater: ray-head-hvj98: Applied config 5431afd4447d4a1d05b060e89e6dec6b7f712dbc [LogTimer=25ms]
2020-05-29 13:42:05,901 ERROR updater.py:352 -- NodeUpdater: ray-head-hvj98: Error updating (409)
Reason: Conflict
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Fri, 29 May 2020 20:42:05 GMT', 'Content-Length': '312'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on pods \"ray-head-hvj98\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"ray-head-hvj98","kind":"pods"},"code":409}


Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/simonmo/miniconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/simonmo/Desktop/ray/ray/python/ray/autoscaler/updater.py", line 355, in run
    raise e
  File "/Users/simonmo/Desktop/ray/ray/python/ray/autoscaler/updater.py", line 345, in run
    self.do_update()
  File "/Users/simonmo/Desktop/ray/ray/python/ray/autoscaler/updater.py", line 408, in do_update
    self.node_id, {TAG_RAY_NODE_STATUS: STATUS_WAITING_FOR_SSH})
  File "/Users/simonmo/Desktop/ray/ray/python/ray/autoscaler/kubernetes/node_provider.py", line 67, in set_node_tags
    core_api().patch_namespaced_pod(node_id, self.namespace, pod)
  File "/Users/simonmo/miniconda3/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 15470, in patch_namespaced_pod
    (data) = self.patch_namespaced_pod_with_http_info(name, namespace, body, **kwargs)
  File "/Users/simonmo/miniconda3/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 15570, in patch_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/Users/simonmo/miniconda3/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/Users/simonmo/miniconda3/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/Users/simonmo/miniconda3/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 393, in request
    body=body)
  File "/Users/simonmo/miniconda3/lib/python3.6/site-packages/kubernetes/client/rest.py", line 286, in PATCH
    body=body)
  File "/Users/simonmo/miniconda3/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (409)
Reason: Conflict
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Fri, 29 May 2020 20:42:05 GMT', 'Content-Length': '312'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on pods \"ray-head-hvj98\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"ray-head-hvj98","kind":"pods"},"code":409}



2020-05-29 13:42:05,936 ERROR commands.py:285 -- get_or_create_head_node: Updating None failed
```

### Workaround
Run it the second time should fix it.
```
$ ray up python/ray/autoscaler/kubernetes/example-full.yaml
This will restart cluster services [y/N]: y
2020-05-29 13:42:19,881 INFO commands.py:222 -- get_or_create_head_node: Updating files on head node...
2020-05-29 13:42:19,882 INFO updater.py:341 -- NodeUpdater: ray-head-hvj98: Updating to 6ea2feab00f30460906c316306a6667be1c13997
2020-05-29 13:42:19,898 INFO updater.py:383 -- NodeUpdater: ray-head-hvj98: Waiting for remote shell...
2020-05-29 13:42:19,908 INFO updater.py:79 -- NodeUpdater: ray-head-hvj98: Running uptime...
error: unable to upgrade connection: container not found ("ray-node")
2020-05-29 13:42:25,780 INFO updater.py:79 -- NodeUpdater: ray-head-hvj98: Running uptime...
error: unable to upgrade connection: container not found ("ray-node")
2020-05-29 13:42:30,890 INFO updater.py:79 -- NodeUpdater: ray-head-hvj98: Running uptime...
```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

- Make sure there isn't a cached yaml file. 

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by simon-mo** [comment]
@edoakes

**Comment by edoakes** [comment]
@simon-mo if you do ray down and then ray up with a new config what happens? I think this might be because I had the same cluster already running on our shared cluster.

**Comment by simon-mo** [comment]
I used a local k8s cluster provided by docker. It's a clean environment. If I do ray down and ray up again, the same things happen.

**Comment by simon-mo** [comment]
Weird. It doesn't appear on microk8s on ubuntu; could just be a mac docker issue.

**Comment by artiship** [comment]
I just got the same issue, ray version is 0.8.6

```
# ray up ray-k8s-cluster.yaml
2020-07-01 19:57:38,465	INFO commands.py:54 -- Using cached config at /tmp/ray-config-94dc1b7372c98eefd805e69fd2cf7a3d4c392606
This will restart cluster services [y/N]: y
2020-07-01 19:57:40,263	INFO commands.py:237 -- get_or_create_head_node: Updating files on head node...
2020-07-01 19:57:40,265	INFO updater.py:336 -- NodeUpdater: ray-head-x9vhz: Updating to b064dcb75573a52d1fc699eac38242c880264d24
2020-07-01 19:57:40,275	INFO updater.py:380 -- NodeUpdater: ray-head-x9vhz: Waiting for remote shell...
2020-07-01 19:57:40,279	INFO updater.py:78 -- NodeUpdater: ray-head-x9vhz: Running uptime...
error: unable to upgrade connection: container not found ("ray-node")
2020-07-01 19:57:45,427	INFO updater.py:78 -- NodeUpdater: ray-head-x9vhz: Running uptime...
error: unable to upgrade connection: container not found ("ray-node")
2020-07-01 19:57:50,562	INFO updater.py:78 -- NodeUpdater: ray-head-x9vhz: Running uptime...
```

**Comment by simon-mo** [comment]
Can you try running `kubectl get pods -n ray` and paste the output here while the "final two lines repeated every five or six seconds"?

**Comment by doctorcolossus** [comment]
```
$ kubectl get pods -n ray
NAME             READY   STATUS    RESTARTS   AGE
ray-head-kflbp   1/1     Running   0          65m
```

**Comment by doctorcolossus** [comment]
I guess that this state indicates success, right? If so, maybe the `error: unable to upgrade connection: container not found` should be changed to a warning. And although it's not terrible to have to start it twice, it could probably make other people's lives easier if we could figure out how to make it work on the first run.
