### ISSUE TITLE
rllib  run PG algorithm on offline dataset pose KeyError: 'advantages'

### ISSUE THREAD

**Issue by tinymindxxx** [ray-project/ray#8681]
### What is your question?

*Ray version and other system information (Python version, TensorFlow version, OS):*

rayversion: 0.8.5
os: macos catalina

When I run PG algorithm on offline dataset, it breakdown with “KeyError: 'advantages'”
scripts are belows：
```shell
rllib train --run=PG --env=Breakout-v0 --config='{
        "input": "~/work/data/processed_data/breakout_offline",
        "input_evaluation": [],
        "explore": false}'

```
and the error likes this.
```shell
2020-05-30 10:06:16,847	ERROR trial_runner.py:519 -- Trial PG_Breakout-v0_00000: Error processing event.
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 431, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1515, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(KeyError): ray::PG.train() (pid=61578, ip=10.78.100.38)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 417, in ray._raylet.execute_task.function_executor
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 498, in train
    raise e
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 484, in train
    result = Trainable.train(self)
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 142, in _train
    return self._train_exec_impl()
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 177, in _train_exec_impl
    res = next(self.train_exec_impl)
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 634, in __next__
    return next(self.built_iterator)
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 644, in apply_foreach
    for item in it:
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 685, in apply_filter
    for item in it:
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 685, in apply_filter
    for item in it:
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/util/iter.py", line 652, in apply_foreach
    result = fn(item)
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/execution/train_ops.py", line 42, in __call__
    info = self.workers.local_worker().learn_on_batch(batch)
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 653, in learn_on_batch
    samples)
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/policy/tf_policy.py", line 344, in learn_on_batch
    fetches = self._build_learn_on_batch(builder, postprocessed_batch)
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/policy/tf_policy.py", line 613, in _build_learn_on_batch
    self._get_loss_inputs_dict(postprocessed_batch, shuffle=False))
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/policy/tf_policy.py", line 655, in _get_loss_inputs_dict
    feed_dict[ph] = batch[k]
  File "/opt/anaconda3/lib/python3.7/site-packages/ray/rllib/policy/sample_batch.py", line 193, in __getitem__
    return self.data[key]
KeyError: 'advantages'
```

**Comment by tinymindxxx** [comment]
It seems that the postprocess_fn is not called during rolloutworkers handle the data.

**Comment by tinymindxxx** [comment]
need set postprocess_inputs=True when handling offline dataset.
