### ISSUE TITLE
【rllib】how to use files in tuned_examples？

### ISSUE THREAD

**Issue by Glaucus-2G** [ray-project/ray#8699]
When I use files in /tuned_examples/ppo ,it went wrong. For example, I input ‘rllib train -f atari-ppo.yaml’，and the contents of the yaml file are as follows：
atari-ppo:
    env:
        grid_search:
            - BreakoutNoFrameskip-v4
            - BeamRiderNoFrameskip-v4
            - QbertNoFrameskip-v4
            - SpaceInvadersNoFrameskip-v4
    run: PPO
    config:
        # Works for both torch and tf.
        framework: torch
        lambda: 0.95
        kl_coeff: 0.5
        clip_rewards: True
        clip_param: 0.1
        vf_clip_param: 10.0
        entropy_coeff: 0.01
        train_batch_size: 5000
        rollout_fragment_length: 100
        sgd_minibatch_size: 500
        num_sgd_iter: 10
        num_workers: 10
        num_envs_per_worker: 5
        batch_mode: truncate_episodes
        observation_filter: NoFilter
        vf_share_layers: true
        num_gpus: 1

The feedback is as follows:
2020-06-01 10:28:08,496	ERROR trial_runner.py:519 -- Trial PPO_QbertNoFrameskip-v4_00002: Error processing event.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 431, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/opt/conda/lib/python3.7/site-packages/ray/worker.py", line 1515, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::PPO.train() (pid=12880, ip=10.11.0.10)
  File "python/ray/_raylet.pyx", line 424, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 462, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 417, in ray._raylet.execute_task.function_executor
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 90, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 448, in __init__
    super().__init__(config, logger_creator)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trainable.py", line 174, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 554, in _setup
    config)
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 921, in merge_trainer_configs
    cls._override_all_subkeys_if_type_changes)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/utils/util.py", line 181, in deep_update
    raise Exception("Unknown config parameter `{}` ".format(k))
Exception: Unknown config parameter `framework`
2020-06-01 10:28:09,672	ERROR trial_runner.py:519 -- Trial PPO_SpaceInvadersNoFrameskip-v4_00003: Error processing event.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 431, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/opt/conda/lib/python3.7/site-packages/ray/worker.py", line 1515, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::PPO.train() (pid=12869, ip=10.11.0.10)
  File "python/ray/_raylet.pyx", line 424, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 462, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 417, in ray._raylet.execute_task.function_executor
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 90, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 448, in __init__
    super().__init__(config, logger_creator)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trainable.py", line 174, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 554, in _setup
    config)
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 921, in merge_trainer_configs
    cls._override_all_subkeys_if_type_changes)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/utils/util.py", line 181, in deep_update
    raise Exception("Unknown config parameter `{}` ".format(k))
Exception: Unknown config parameter `framework`

Why there is a problem with the framework in config？Do I need to update ray？

I run this in docker container.
ray 0.8.5
torch 1.5.0
python 3.7.7

Thank you for your help！

**Comment by ericl** [comment]
Try installing the latest wheels (see ray docs) (or use older versions of those files).

**Comment by Glaucus-2G** [comment]
> Try installing the latest wheels (see ray docs) (or use older versions of those files).

OK, Thank you!

**Comment by Glaucus-2G** [comment]
I update ray0.9.0.dev and the problem has been solved

**Comment by Glaucus-2G** [comment]
> Try installing the latest wheels (see ray docs) (or use older versions of those files).

I have set up  a ray cluster(k8s and autoscaler). There are a ray-head node and three ray-worker nodes. I have updated ray to version0.9.0dev0 in these nodes. Now I run atari-ppo.yaml in ray-head node, it also reports “Unknown config parameter framework”.  

Is my understanding about autoscaler wrong？
What  should I do to run atari-ppo.yaml in ray cluster(k8s)？

Thank you for your help！

**Comment by Glaucus-2G** [comment]
I'm sorry not to reply at soon.

I have read all codes about the environment and tried again and again.  It turns out that there is a circular reference.

If someone also wants to encapsulate a complex environment which you are not familiar with, please take environment as a black box.  

Finally, thank you for your help
