### ISSUE TITLE
Docker + AWS hanging at "Set tag..." for autoscaler

### ISSUE THREAD

**Issue by richardrl** [ray-project/ray#8830]
### What is the problem?
Using latest version of Ray (0.9.0.dev0)

### Reproduction (REQUIRED)
If we take the example AWS configuration YAML, given [here](https://docs.ray.io/en/master/autoscaling.html?highlight=docker) (under AWS header) and simply change line 26 and 27 to use an actual Docker image:
[example_full.zip](https://github.com/ray-project/ray/files/4744002/example_full.zip)

Running any commands with the autoscaler hangs and eventually fails:
```
ray up config/example_full.yaml 
2020-06-08 01:13:10,526 INFO config.py:143 -- _configure_iam_role: Role not specified for head node, using arn:aws:iam::<redacted>:instance-profile/ray-autoscaler-v1
2020-06-08 01:13:11,089 INFO config.py:194 -- _configure_key_pair: KeyName not specified for nodes, using ray-autoscaler_us-west-2
2020-06-08 01:13:11,365 INFO config.py:235 -- _configure_subnet: SubnetIds not specified for head node, using [('subnet-<redacted>', 'us-west-2b'), ('subnet-<redacted>', 'us-west-2a')]
2020-06-08 01:13:11,366 INFO config.py:241 -- _configure_subnet: SubnetId not specified for workers, using [('subnet-<redacted>', 'us-west-2b'), ('subnet-<redacted>', 'us-west-2a')]
2020-06-08 01:13:11,725 INFO config.py:261 -- _configure_security_group: SecurityGroupIds not specified for head node, using ray-autoscaler-default (sg-<redacted>)
2020-06-08 01:13:11,725 INFO config.py:268 -- _configure_security_group: SecurityGroupIds not specified for workers, using ray-autoscaler-default (sg-<redacted>)
This will restart cluster services [y/N]: y
2020-06-08 01:13:15,214 INFO commands.py:238 -- get_or_create_head_node: Updating files on head node...
2020-06-08 01:13:15,215 INFO updater.py:379 -- NodeUpdater: i-<redacted>: Updating to <redacted>
2020-06-08 01:13:15,216 INFO updater.py:423 -- NodeUpdater: i-<redacted>: Waiting for remote shell...
2020-06-08 01:13:15,422 INFO log_timer.py:22 -- AWSNodeProvider: Set tag ray-node-status=waiting-for-ssh on ['i-<redacted>
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/richard/improbable/ray/python/ray/autoscaler/updater.py", line 383, in run
    self.do_update()
  File "/home/richard/improbable/ray/python/ray/autoscaler/updater.py", line 450, in do_update
    self.wait_ready(deadline)
  File "/home/richard/improbable/ray/python/ray/autoscaler/updater.py", line 444, in wait_ready
    assert False, "Unable to connect to node"
AssertionError: Unable to connect to node

2020-06-08 01:11:59,679 ERROR commands.py:304 -- get_or_create_head_node: Updating <redacted> failed
2020-06-08 01:11:59,701 INFO log_timer.py:22 -- AWSNodeProvider: Set tag ray-node-status=update-failed on ['i-<redacted>']  [LogTimer=333ms]

```

If I remove the Docker image and name on line 26 and line 27, the YAML file **succeeds** for any ray up / attach / submit etc. command.

(Related, it would be nice if we piped out more verbose error messages about why errors like this occur when using the autoscaler.)

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardrl** [comment]
Where is the code that first starts the Docker image? 

I am running into issues where the Docker image is not run with tty. 

I can manually add the run command in "initialization_commands: []" but I'm guessing the below is a bug... If someone explains how Ray team wants the Docker setup to work (which file we run "docker run ..." in I can do a PR.

```
(pb_venv) richard@richard-desktop:~/improbable/<redacted>$ ray submit --docker config/example_full.yaml <redacted>/torch/train_ray.py 
2020-06-08 02:03:06,388 INFO commands.py:54 -- Using cached config at /tmp/ray-config-e82fb02128a816538f2a0dc5e8abcfdf5dd594a5
2020-06-08 02:03:07,123 INFO updater.py:485 -- NodeUpdater: i-<redacted>: Syncing <redacted>/torch/train_ray.py to ~/train_ray.py...
2020-06-08 02:03:07,617 INFO updater.py:200 -- NodeUpdater: i-<redacted>: Waiting for IP...
2020-06-08 02:03:07,617 INFO log_timer.py:22 -- NodeUpdater: i-<redacted>: Got IP  [LogTimer=493ms]
sending incremental file list
train_ray.py

sent 2,525 bytes  received 35 bytes  1,024.00 bytes/sec
total size is 8,257  speedup is 3.23
2020-06-08 02:03:09,475 INFO updater.py:253 -- NodeUpdater: i-<redacted>: Running docker cp ~/train_ray.py ray_docker:`docker exec ray_docker env | grep HOME | cut -d'=' -f2`/train_ray.py on 34.208.67.2...
2020-06-08 02:03:09,476 INFO updater.py:254 -- Begin remote output from <redacted>
Error: No such container: ray_docker
Error: No such container:path: ray_docker:/
Shared connection to <redacted> closed.
Error: SSH command Failed. See above for the output from the failure.

```

**Comment by ijrsvt** [comment]
Just to confirm, if you run `docker container ls` it does not show anything?

**Comment by richardrl** [comment]
Commit daf1ee13da9da96d99fe112970ee01b1f372f360  does not solve the issue.

```
Shared connection to 127.0.0.1 closed.
2020-06-09 00:58:18,716 INFO updater.py:254 -- NodeUpdater: localhost: Running docker cp /home/richard/<code>:/home/richard/<code>/ on 127.0.0.1...
2020-06-09 00:58:18,716 INFO updater.py:255 -- Begin remote output from 127.0.0.1
Error: No such container:path: <code>:/home/richard

```

**Comment by ijrsvt** [comment]
What happens if you include the `--start` flag for `ray submit`.

**Comment by snmhaines** [comment]
I realize that this issue is closed, but the thread is the most recent and relevant that I could find to the problem that I am having, so I am asking for help.  
I was successfully running an EC2 cluster using Ray last year, and recently attempted to start one up again with the same configuration, but updated release.  
Firstly, I encountered the redis_address deprecation warning, so I changed my ray.init argument to (address="auto"), and the head_ and worker_start_ray_commands to those in a recent version of the example-full.yaml config' (see attached).  
Now, when trying to bring ray up, I am getting an error very similar to the one above:-

```
bash: no job control in this shell
Error: no such option: --port
2020-06-29 17:24:37,025	INFO log_timer.py:17 -- NodeUpdater: i-08ab35ed68fbb942a: Ray start commands completed [LogTimer=2355ms]
2020-06-29 17:24:37,026	INFO log_timer.py:17 -- NodeUpdater: i-08ab35ed68fbb942a: Applied config ebfab67c94259a0ba4df6381d5cf2410fa5ef49b [LogTimer=38656ms]
2020-06-29 17:24:37,026	ERROR updater.py:348 -- NodeUpdater: i-08ab35ed68fbb942a: Error updating (Exit Status 2) ssh -i /home/haines/.ssh/ray-key2_us-east-1.pem -o ConnectTimeout=120s -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_98734ce2b6/2ebd7d2a8f/%C -o ControlPersist=10s -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 ubuntu@54.210.118.84 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && ulimit -n 65536; ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/haines/Projects/VF83/Ray_Cloud/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 351, in run
    raise e
  File "/home/haines/Projects/VF83/Ray_Cloud/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 341, in run
    self.do_update()
  File "/home/haines/Projects/VF83/Ray_Cloud/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 434, in do_update
    self.cmd_runner.run(cmd)
  File "/home/haines/Projects/VF83/Ray_Cloud/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 263, in run
    self.process_runner.check_call(final_cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh', '-i', '/home/haines/.ssh/ray-key2_us-east-1.pem', '-o', 'ConnectTimeout=120s', '-o', 'StrictHostKeyChecking=no', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/tmp/ray_ssh_98734ce2b6/2ebd7d2a8f/%C', '-o', 'ControlPersist=10s', '-o', 'IdentitiesOnly=yes', '-o', 'ExitOnForwardFailure=yes', '-o', 'ServerAliveInterval=5', '-o', 'ServerAliveCountMax=3', 'ubuntu@54.210.118.84', 'bash', '--login', '-c', '-i', "'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && ulimit -n 65536; ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml'"]' returned non-zero exit status 2.

2020-06-29 17:24:37,170	ERROR commands.py:285 -- get_or_create_head_node: Updating 54.210.118.84 failed
2020-06-29 17:24:37,184	INFO log_timer.py:17 -- AWSNodeProvider: Set tag ray-node-status=update-failed on ['i-08ab35ed68fbb942a'] [LogTimer=157ms]
```
The head node starts OK, but not the worker.  Is there something else that needs changing in order to substitute the redis address?

[ray_conf.txt](https://github.com/ray-project/ray/files/4848130/ray_conf.txt)

**Comment by ijrsvt** [comment]
@snmhaines What if you try using `--redis-port` instead of `--port`?

**Comment by snmhaines** [comment]
Thanks for the quick reply Ian.  I reverted to my previous config, which has ulimit -n 65536; ray start --redis-address=$RAY_HEAD_IP:6379 --object-manager-port=8076 ... as the start_ray_commands, and the cluster started OK. 
I was going to check whether ray.init(redis_address=<redaddress>+":6379") still produces a warning for initialization in Python, but have run into a new problem on getting ray up:-

```
Collecting py-spy>=0.2.0 (from ray)
  Downloading https://files.pythonhosted.org/packages/8e/a7/ab45c9ee3c4654edda3efbd6b8e2fa4962226718a7e3e3be6e3926bf3617/py_spy-0.3.3-py2.py3-none-manylinux1_x86_64.whl (2.9MB)
Collecting grpcio (from ray)
  Downloading https://files.pythonhosted.org/packages/5e/29/1bd649737e427a6bb850174293b4f2b72ab80dd49462142db9b81e1e5c7b/grpcio-1.30.0.tar.gz (19.7MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9x_z6x8v/grpcio/setup.py", line 196, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-build-9x_z6x8v/grpcio/setup.py", line 156, in check_linker_need_libatomic
        stderr=PIPE)
      File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cc': 'cc'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9x_z6x8v/grpcio/
You are using pip version 9.0.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
2020-06-30 16:52:10,251	INFO log_timer.py:17 -- NodeUpdater: i-0dcaa2c55fbf456bd: Setup commands completed [LogTimer=97821ms]
2020-06-30 16:52:10,251	INFO log_timer.py:17 -- NodeUpdater: i-0dcaa2c55fbf456bd: Applied config 3c0845120a75432975eabe3c3f52bc4599173c4f [LogTimer=166507ms]
2020-06-30 16:52:10,252	ERROR updater.py:348 -- NodeUpdater: i-0dcaa2c55fbf456bd: Error updating (Exit Status 1) ssh -i /home/haines/.ssh/ray-key2_us-east-1.pem -o ConnectTimeout=120s -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_98734ce2b6/2ebd7d2a8f/%C -o ControlPersist=10s -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 ubuntu@34.229.85.7 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && pip install ray'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/haines/Projects/VF83/Ray_Cloud/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 351, in run
    raise e
  File "/home/haines/Projects/VF83/Ray_Cloud/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 341, in run
    self.do_update()
  File "/home/haines/Projects/VF83/Ray_Cloud/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 430, in do_update
    self.cmd_runner.run(cmd)
  File "/home/haines/Projects/VF83/Ray_Cloud/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 263, in run
    self.process_runner.check_call(final_cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh', '-i', '/home/haines/.ssh/ray-key2_us-east-1.pem', '-o', 'ConnectTimeout=120s', '-o', 'StrictHostKeyChecking=no', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/tmp/ray_ssh_98734ce2b6/2ebd7d2a8f/%C', '-o', 'ControlPersist=10s', '-o', 'IdentitiesOnly=yes', '-o', 'ExitOnForwardFailure=yes', '-o', 'ServerAliveInterval=5', '-o', 'ServerAliveCountMax=3', 'ubuntu@34.229.85.7', 'bash', '--login', '-c', '-i', "'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && pip install ray'"]' returned non-zero exit status 1.

2020-06-30 16:52:10,774	ERROR commands.py:285 -- get_or_create_head_node: Updating 34.229.85.7 failed
2020-06-30 16:52:10,797	INFO log_timer.py:17 -- AWSNodeProvider: Set tag ray-node-status=update-failed on ['i-0dcaa2c55fbf456bd'] [LogTimer=545ms]

``` 
The head node starts, but not the worker.  I can log into the former, but it seems that the Python3 installation isn't completing, and  
subsequent setup_commands in the config are not being executed (eg. boto3 is not being loaded).  The difficult thing is that this was working this morning.  Any ideas?

**Comment by ijrsvt** [comment]
Try adding  `pip install --upgrade pip` to your setup commands before `pip install ray`. It just looks like the AMI you are using has an old version of pip and that is tripping up GRPC installation.

**Comment by snmhaines** [comment]
Thanks again, that did the trick.  However, there is now a run-time error which, I believe, is an incompatibility between installed versions of numpy and scipy:-
```
Traceback (most recent call last):
  File "Big_Data_Gen.py", line 4, in <module>
    import scipy.signal as sig
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/scipy/signal/__init__.py", line 305, in <module>
    from .filter_design import *
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/scipy/signal/filter_design.py", line 19, in <module>
    from scipy._lib._numpy_compat import polyvalfromroots
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/scipy/_lib/_numpy_compat.py", line 10, in <module>
    from numpy.testing.nosetester import import_nose
ModuleNotFoundError: No module named 'numpy.testing.nosetester'
```
I assume that both packages are installed, along with Ray, by Anaconda3 (5.0.1), so I am puzzled as to why there is any mis-match.  I could try explicitly installing other versions of both until the disparity disappears, but I am worried that that will just cause an avalanche of incompatibilities elsewhere.
Yours,
Steven Haines

**Comment by richardliaw** [comment]
What if you did:
`ray.init(address=redadd+":6379")`

**Comment by snmhaines** [comment]
Thanks Richard; that worked.  It seems that I was over-thinking the implications of the change.
