### ISSUE TITLE
ResNet example only creates one actor for training when GPUs are not being used.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#893]
cc @xc9

**Comment by robertnishihara** [comment]
Apparently changing the ResNet example to use multiple actors in the CPU case leads to the following error.

That is, changing the line https://github.com/ray-project/ray/blob/deca29a7eb147f1e3e90f266c2448850dfe3e6b5/examples/resnet/resnet_main.py#L215 to create a list of 6 actors instead of 1 gives the following error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 1771, in process_task
    worker.actors[task.actor_id().id()], *arguments)
  File "ray/examples/resnet/resnet_main.py", line 170, in accuracy
    model.labels])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
InvalidArgumentError: Nan in summary histogram for: unit_3_2/sub2/bn2/unit_3_2/sub2/bn2/moving_variance
	 [[Node: unit_3_2/sub2/bn2/unit_3_2/sub2/bn2/moving_variance = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](unit_3_2/sub2/bn2/unit_3_2/sub2/bn2/moving_variance/tag, unit_3_2/sub2/bn2/moving_variance/read)]]

Caused by op u'unit_3_2/sub2/bn2/unit_3_2/sub2/bn2/moving_variance', defined at:
  File "/usr/local/lib/python2.7/dist-packages/ray/workers/default_worker.py", line 61, in <module>
    ray.worker.main_loop()
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 1838, in main_loop
    process_task(task)
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 1771, in process_task
    worker.actors[task.actor_id().id()], *arguments)
  File "ray/examples/resnet/resnet_main.py", line 144, in _init_
    self.model.build_graph()
  File "/home/ubuntu/ray/examples/resnet/resnet_model.py", line 49, in build_graph
    self._build_model()
  File "/home/ubuntu/ray/examples/resnet/resnet_model.py", line 102, in _build_model
    False)
  File "/home/ubuntu/ray/examples/resnet/resnet_model.py", line 207, in _residual
    x = self._batch_norm('bn2', x)
  File "/home/ubuntu/ray/examples/resnet/resnet_model.py", line 181, in _batch_norm
    tf.summary.histogram(variance.op.name, variance)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/summary.py", line 221, in histogram
    tag=scope.rstrip('/'), values=values, name=scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_logging_ops.py", line 131, in _histogram_summary
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in _init_
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Nan in summary histogram for: unit_3_2/sub2/bn2/unit_3_2/sub2/bn2/moving_variance
	 [[Node: unit_3_2/sub2/bn2/unit_3_2/sub2/bn2/moving_variance = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](unit_3_2/sub2/bn2/unit_3_2/sub2/bn2/moving_variance/tag, unit_3_2/sub2/bn2/moving_variance/read)]]



You can inspect errors by running

    ray.error_info()

If this driver is hanging, start a new one with

    ray.init(redis_address="172.31.20.128:6379")
```

@Wapaul1 any idea about this?

**Comment by edoakes** [comment]
Stale - please open new issue if still relevant
