### ISSUE TITLE
"ray timeline" command fails when RAY_ADDRESS is set

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#8951]
```
ray start --head --redis-port=6379
```

```
RAY_ADDRESS=localhost:6379 ray timeline
```

This fails with

```
2020-06-15 13:40:51,876	INFO scripts.py:926 -- Connecting to Ray instance at 192.168.1.104:6379.
Traceback (most recent call last):
  File "/Users/rkn/opt/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1028, in main
    return cli()
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 927, in timeline
    ray.init(address=address)
  File "/Users/rkn/opt/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 680, in init
    "Cannot use both the RAY_ADDRESS environment variable and "
RuntimeError: Cannot use both the RAY_ADDRESS environment variable and the address argument of ray.init simultaneously. If you use RAY_ADDRESS to connect to a specific Ray cluster, please call ray.init() or ray.init(address="auto") on the driver.
```

**Comment by scottsun94** [comment]
cc: @rkooo567 @alanwguo

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
