### ISSUE TITLE
[rllib]Program Failed to feed inputs to the model after running 10 iterations

### ISSUE THREAD

**Issue by kakakflo22thy** [ray-project/ray#8961]
### What is the problem?

* Ray version  0.8.5
* tensorflow-gpu  1.15.2   
* python 3.6.8
* Linux version 4.18.9-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)) #1 SMP Thu Sep 20 09:04:54 EDT 2018

I rewrite the td3(ddpg) agent in rillib by adding a new VAE network and a cost network(set FLAG False so it's not used yet) to the model and supplementing vae_loss and cost_loss(also not used yet) to actor_critic_loss accordingly.
It seems to vae network fail to update and Program failed after 10 iterations with following info:

> Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'default_policy/model_out' with dtype float and shape [?,11]
         [[{{node default_policy/model_out}}]]

> Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ray/rllib/utils/tf_run_builder.py", line 44, in get
    self.feed_dict, os.environ.get("TF_TIMELINE_DIR"))
  File "/usr/local/lib/python3.6/site-packages/ray/rllib/utils/tf_run_builder.py", line 89, in run_timeline
    fetches = sess.run(ops, feed_dict=feed_dict)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'default_policy/model_out' with dtype float and shape [?,11]
         [[node default_policy/model_out (defined at /usr/local/lib64/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

> Original stack trace for 'default_policy/model_out':
  File "tune_vae.py", line 86, in <module>
    'log_level':'INFO',
  File "/usr/local/lib/python3.6/site-packages/ray/tune/tune.py", line 325, in run
    runner.step()
  File "/usr/local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 337, in step
    self.trial_executor.start_trial(next_trial)
  File "/usr/local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 295, in start_trial
    self._start_trial(trial, checkpoint, train=train)
  File "/usr/local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 233, in _start_trial
    runner = self._setup_remote_runner(trial, reuse_allowed)
  File "/usr/local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 185, in _setup_remote_runner
    return cls.remote(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/ray/actor.py", line 378, in remote
    return self._remote(args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.6/site-packages/ray/actor.py", line 556, in _remote
    extension_data=str(actor_method_cpu))
  File "/usr/local/lib/python3.6/site-packages/ray/function_manager.py", line 559, in actor_method_executor
    method_returns = method(actor, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 90, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/usr/local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 448, in __init__
    super().__init__(config, logger_creator)
  File "/usr/local/lib/python3.6/site-packages/ray/tune/trainable.py", line 174, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/usr/local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 591, in _setup
    self._init(self.config, self.env_creator)
  File "/usr/local/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 117, in _init
    self.config["num_workers"])
  File "/usr/local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 662, in _make_workers
    logdir=self.logdir)
  File "/usr/local/lib/python3.6/site-packages/ray/rllib/evaluation/worker_set.py", line 61, in __init__
    RolloutWorker, env_creator, policy, 0, self._local_config)
  File "/usr/local/lib/python3.6/site-packages/ray/rllib/evaluation/worker_set.py", line 279, in _make_worker
    extra_python_environs=extra_python_environs)
  File "/usr/local/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 376, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/usr/local/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 859, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/usr/local/lib/python3.6/site-packages/ray/rllib/policy/tf_policy_template.py", line 143, in __init__
    obs_include_prev_action_reward=obs_include_prev_action_reward)
  File "/usr/local/lib/python3.6/site-packages/ray/rllib/policy/dynamic_tf_policy.py", line 156, in __init__
    self.model = make_model(self, obs_space, action_space, config)
  File "/home/yinzexia/Ray_VAEMMD/vaemmd_tf_policy.py", line 89, in build_vae_models
    "ParameterNoise"),
  File "/usr/local/lib/python3.6/site-packages/ray/rllib/models/catalog.py", line 347, in get_model_v2
    name, **model_kwargs)
  File "/home/yinzexia/Ray_VAEMMD/vaemmd_tf_model.py", line 62, in __init__
    shape=(num_outputs, ), name="model_out")
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/keras/engine/input_layer.py", line 265, in Input
    input_layer = InputLayer(**input_layer_config)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/keras/engine/input_layer.py", line 126, in __init__
    ragged=ragged)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 1051, in placeholder
    x = array_ops.placeholder(dtype, shape=shape, name=name)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 2619, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 6669, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

> E0616 11:34:01.409554  1668 core_worker.cc:1069] Pushed Error with JobID: 0100 of type: task with message: ray::TD3VAE.train() (pid=1668, ip=10.220.176.237)
File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'default_policy/model_out' with dtype float and shape [?,11]
         [[{{node default_policy/model_out}}]]

### Reproduction (REQUIRED)
Please check  the attachments for script details and run file tune_vae.py
[vae_td3.zip](https://github.com/ray-project/ray/files/4784293/vae_td3.zip)

- [√] I have verified my script runs in a clean environment and reproduces the issue.
- [√] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by kakakflo22thy** [comment]
I think this is a Version problem and my colleague also encountered the same problem. I rewrote my code in version 0.8.4 and this bug is gone.
