### ISSUE TITLE
[rllib] an example from README.md fails wihout tensorflow

### ISSUE THREAD

**Issue by slitvinov** [ray-project/ray#9018]
An example from README.md fails if tensorflow is not installed (I have python 3.8.3 and ray is from the latest wheel):

~~~
$ cat tune.py
import gym
from gym.spaces import Discrete, Box
from ray import tune

class SimpleCorridor(gym.Env):
    def __init__(self, config):
        self.end_pos = config["corridor_length"]
        self.cur_pos = 0
        self.action_space = Discrete(2)
        self.observation_space = Box(0.0, self.end_pos, shape=(1, ))

    def reset(self):
        self.cur_pos = 0
        return [self.cur_pos]

    def step(self, action):
        if action == 0 and self.cur_pos > 0:
            self.cur_pos -= 1
        elif action == 1:
            self.cur_pos += 1
        done = self.cur_pos >= self.end_pos
        return [self.cur_pos], 1 if done else 0, done, {}

tune.run(
    "PPO",
    config={
        "env": SimpleCorridor,
        "num_workers": 4,
        "env_config": {"corridor_length": 5}})```
~~~

~~~
$ python3 tune.py 
2020-06-18 22:11:42,889	INFO resource_spec.py:204 -- Starting Ray with 1.71 GiB memory available for workers and up to 0.87 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-06-18 22:11:43,360	INFO services.py:1176 -- View the Ray dashboard at localhost:8265
(pid=raylet) I0618 22:11:43.414299  2998  2998 store_runner.cc:44] Allowing the Plasma store to use up to 0.938435GB of memory.
(pid=raylet) I0618 22:11:43.414342  2998  2998 store_runner.cc:58] Starting object store with directory /dev/shm and huge page support disabled
(pid=raylet) E0618 22:11:43.415125  2998  2998 io.cc:212] Connection to IPC socket failed for pathname /tmp/ray/session_2020-06-18_22-11-42_887550_2978/sockets/plasma_store, retrying 300 more times
(pid=raylet) I0618 22:11:43.516335  2998  2998 grpc_server.cc:74] ObjectManager server started, listening on port 41405.
(pid=raylet) I0618 22:11:43.553181  2998  2998 node_manager.cc:166] Initializing NodeManager with ID 0508131e363757a3653d4cb70f84546c3a39e15e
(pid=raylet) I0618 22:11:43.553709  2998  2998 grpc_server.cc:74] NodeManager server started, listening on port 63158.
(pid=raylet) I0618 22:11:43.558928  2998  2998 service_based_accessor.cc:731] Received notification for node id = 0508131e363757a3653d4cb70f84546c3a39e15e, IsAlive = 1
(pid=raylet) I0618 22:11:43.560137  2998  2998 service_based_accessor.cc:731] Received notification for node id = 0508131e363757a3653d4cb70f84546c3a39e15e, IsAlive = 1
== Status ==
Memory usage on this node: 1.5/3.7 GiB
Using FIFO scheduling algorithm.
Resources requested: 2/4 CPUs, 0/0 GPUs, 0.0/1.71 GiB heap, 0.0/0.59 GiB objects
Result logdir: /home/lisergey/ray_results/PPO
Number of trials: 1 (1 RUNNING)
+--------------------------------+----------+-------+
| Trial name                     | status   | loc   |
|--------------------------------+----------+-------|
| PPO_SimpleCorridor_ef53e_00000 | RUNNING  |       |
+--------------------------------+----------+-------+


2020-06-18 22:11:47,864	ERROR trial_runner.py:524 -- Trial PPO_SimpleCorridor_ef53e_00000: Error processing event.
Traceback (most recent call last):
  File "/home/lisergey/.local/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 472, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/lisergey/.local/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 430, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/lisergey/.local/lib/python3.8/site-packages/ray/worker.py", line 1474, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ImportError): ray::PPO.train() (pid=3022, ip=192.168.0.171)
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 442, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 445, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 400, in ray._raylet.execute_task.function_executor
  File "/home/lisergey/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 90, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/lisergey/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 463, in __init__
    super().__init__(config, logger_creator)
  File "/home/lisergey/.local/lib/python3.8/site-packages/ray/tune/trainable.py", line 231, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/lisergey/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 636, in _setup
    self._init(self.config, self.env_creator)
  File "/home/lisergey/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 113, in _init
    self.workers = self._make_workers(env_creator, self._policy,
  File "/home/lisergey/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 704, in _make_workers
    return WorkerSet(
  File "/home/lisergey/.local/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 59, in __init__
    self._local_worker = self._make_worker(
  File "/home/lisergey/.local/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 246, in _make_worker
    worker = cls(
  File "/home/lisergey/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 366, in __init__
    raise ImportError("Could not import tensorflow")
ImportError: Could not import tensorflow
== Status ==
Memory usage on this node: 1.6/3.7 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/4 CPUs, 0/0 GPUs, 0.0/1.71 GiB heap, 0.0/0.59 GiB objects
Result logdir: /home/lisergey/ray_results/PPO
Number of trials: 1 (1 ERROR)
+--------------------------------+----------+-------+
| Trial name                     | status   | loc   |
|--------------------------------+----------+-------|
| PPO_SimpleCorridor_ef53e_00000 | ERROR    |       |
+--------------------------------+----------+-------+
Number of errored trials: 1
+--------------------------------+--------------+-------------------------------------------------------------------------------------------+
| Trial name                     |   # failures | error file                                                                                |
|--------------------------------+--------------+-------------------------------------------------------------------------------------------|
| PPO_SimpleCorridor_ef53e_00000 |            1 | /home/lisergey/ray_results/PPO/PPO_SimpleCorridor_0_2020-06-18_22-11-46w_ki980o/error.txt |
+--------------------------------+--------------+-------------------------------------------------------------------------------------------+

Traceback (most recent call last):
  File "tune.py", line 26, in <module>
    tune.run(
  File "/home/lisergey/.local/lib/python3.8/site-packages/ray/tune/tune.py", line 356, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_SimpleCorridor_ef53e_00000])
(pid=raylet) I0618 22:11:47.873847  2998  3008 store.cc:733] Disconnecting client on fd 57
(pid=3022) 2020-06-18 22:11:47,853	INFO trainer.py:623 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=3022) /home/lisergey/.local/lib/python3.8/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
(pid=3022)   warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
~~~

**Comment by richardliaw** [comment]
This should work with tensorflow installed right?

**Comment by slitvinov** [comment]
I cannot install TensorFlow. I want to use ray because it is framework agnostic and some work was done recently:<br/>
https://github.com/ray-project/ray/issues/4717

I am a bit surprised the first example fails given TensorFlow is not listed as install dependency. Is there an option to prefer PyTorch?
