### ISSUE TITLE
[rllib] Unable to use custom_model_config parameter

### ISSUE THREAD

**Issue by ivallesp** [ray-project/ray#9040]
Hi everyone,

I am trying to run a tune process which requires passing-in some parameters to my custom model class. For that, I am first registering my model, adding the `custom_model` parameter and  the `custom_model_config` one. When I don't add the last param everything works well, but when I add it I get an error saying that this parameter is not recognized as a valid parameter. Please find below my reproducible snipped and the error I get. Am I doing something wrong? I hope someone can help me!

**Ray version = 0.8.5 | Tensorflow version = 2.2.0 | Python version = 3.6.9 | System = Ubuntu 4.15.0-1052-aws**

```
import ray
from ray import tune
from ray.rllib.models import ModelCatalog
from ray.rllib.models.tf.tf_modelv2 import TFModelV2
from ray.rllib.utils.framework import try_import_tf

tf = try_import_tf()


class MyKerasModel(TFModelV2):
    """Custom model for policy gradient algorithms."""

    def __init__(self, obs_space, action_space, num_outputs, model_config, name):
        super(MyKerasModel, self).__init__(
            obs_space, action_space, num_outputs, model_config, name
        )
        layer_size = model_config["custom_model_config"]["layer_size"]
        self.inputs = tf.keras.layers.Input(shape=obs_space.shape, name="observations")
        layer_1 = tf.keras.layers.Dense(
            layer_size,
            name="my_layer1",
            activation=tf.nn.relu,
        )(self.inputs)
        layer_out = tf.keras.layers.Dense(
            num_outputs,
            name="my_out",
            activation=None,
        )(layer_1)
        value_out = tf.keras.layers.Dense(
            1,
            name="value_out",
            activation=None,
        )(layer_1)
        self.base_model = tf.keras.Model(self.inputs, [layer_out, value_out])
        self.register_variables(self.base_model.variables)

    def forward(self, input_dict, state, seq_lens):
        model_out, self._value_out = self.base_model(input_dict["obs"])
        return model_out, state

    def value_function(self):
        return tf.reshape(self._value_out, [-1])

    def metrics(self):
        return {"foo": tf.constant(42.0)}


if __name__ == "__main__":
    ray.init(num_cpus=4)
    ModelCatalog.register_custom_model("keras_model", MyKerasModel)

    tune.run(
        "PPO",
        stop={"episode_reward_mean": 200},
        config={
            "log_level": "INFO",
            "env": "CartPole-v0",
            "num_gpus": 0,
            "model": {
                "custom_model": "keras_model",
                "custom_model_config": {"layer_size": tune.grid_search([128, 256])},
            },
        },
    )
```
 
The error I get

```
Traceback (most recent call last):                                                                                                                
  File "/data/project/.venv/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial                        
    result = self.trial_executor.fetch_result(trial)                                                                                              
  File "/data/project/.venv/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 431, in fetch_result                    
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)                                                                                        
  File "/data/project/.venv/lib/python3.6/site-packages/ray/worker.py", line 1515, in get                                             
    raise value.as_instanceof_cause()                                                                                                             
ray.exceptions.RayTaskError: ray::PPO.train() (pid=20322, ip=172.31.48.190)                                                                       
  File "python/ray/_raylet.pyx", line 424, in ray._raylet.execute_task                                                                            
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task                                                                            
  File "python/ray/_raylet.pyx", line 462, in ray._raylet.execute_task                                                                            
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task                                                                            
  File "python/ray/_raylet.pyx", line 417, in ray._raylet.execute_task.function_executor                                                          
  File "/data/project/.venv/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 90, in __init__                   
    Trainer.__init__(self, config, env, logger_creator)                                                                                           
  File "/data/project/.venv/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 448, in __init__                           
    super().__init__(config, logger_creator)                                                                                                      
  File "/data/project/.venv/lib/python3.6/site-packages/ray/tune/trainable.py", line 174, in __init__                                 
    self._setup(copy.deepcopy(self.config))                                                                                                       
  File "/data/project/.venv/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 591, in _setup                             
    self._init(self.config, self.env_creator)                                                                                                     
  File "/data/project/.venv/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 117, in _init                     
    self.config["num_workers"])                                                                                                                   
  File "/data/project/.venv/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 662, in _make_workers                      
    logdir=self.logdir)                                                                                                                           
  File "/data/project/.venv/lib/python3.6/site-packages/ray/rllib/evaluation/worker_set.py", line 61, in __init__                     
    RolloutWorker, env_creator, policy, 0, self._local_config)                                                                                    
  File "/data/project/.venv/lib/python3.6/site-packages/ray/rllib/evaluation/worker_set.py", line 279, in _make_worker                
    extra_python_environs=extra_python_environs)                                                                                                  
  File "/data/project/.venv/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 376, in __init__                
    self._build_policy_map(policy_dict, policy_config)                                                                                            
  File "/data/project/.venv/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 836, in _build_policy_map       
    obs_space, merged_conf.get("model"))
  File "/data/project/.venv/lib/python3.6/site-packages/ray/rllib/models/catalog.py", line 388, in get_preprocessor_for_space
    k, list(MODEL_DEFAULTS)))
Exception: Unknown config key `custom_model_config`, all keys: ['conv_filters', 'conv_activation', 'fcnet_activation', 'fcnet_hiddens', 'free_log_
std', 'no_final_linear', 'vf_share_layers', 'use_lstm', 'max_seq_len', 'lstm_cell_size', 'lstm_use_prev_action_reward', 'state_shape', 'framestack
', 'dim', 'grayscale', 'zero_mean', 'custom_model', 'custom_action_dist', 'custom_options', 'custom_preprocessor']
```

**Comment by ivallesp** [comment]
Ok I've traced the issue and it is due to the fact that in the latest release in PyPi, the `models/catalog.py` file has that key missing in the `MODEL_CATALOG` dictionary. I see it was fixed in #0422e9 23 days ago, as you can see here: https://github.com/ray-project/ray/blob/a734f77757287abb479ac180e64b25a6182d8fdb/rllib/models/catalog.py#L86

Can you please tell me when this will be officially release so that I can update ray using pip? Thanks in advance
