### ISSUE TITLE
[rllib] Error when exporting multiple policies not named default_policy

### ISSUE THREAD

**Issue by rpandya922** [ray-project/ray#9041]
### What is the problem?
When trying to export models with multiple policies specified using `export_formats=` in `tune.run()`, the programs gives this error about not having a policy named `default_policy`:
```
Traceback (most recent call last):
  File "multiagent_checkpointing.py", line 79, in <module>
    export_formats=[ExportFormat.CHECKPOINT, ExportFormat.MODEL],
  File "/home/ravi/.local/lib/python3.6/site-packages/ray/tune/tune.py", line 321, in run
    runner.step()
  File "/home/ravi/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 339, in step
    self._process_events()  # blocking
  File "/home/ravi/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 440, in _process_events
    self._process_trial_save(trial)
  File "/home/ravi/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 553, in _process_trial_save
    self._execute_action(trial, decision)
  File "/home/ravi/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 603, in _execute_action
    self.trial_executor.export_trial_if_needed(trial)
  File "/home/ravi/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 646, in export_trial_if_needed
    DEFAULT_GET_TIMEOUT)
  File "/home/ravi/.local/lib/python3.6/site-packages/ray/worker.py", line 1513, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(KeyError): ray::QMIX.export_model() (pid=4764, ip=10.0.2.15)
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
  File "/home/ravi/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 487, in export_model
    return self._export_model(export_formats, export_dir)
  File "/home/ravi/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 1019, in _export_model
    self.export_policy_checkpoint(path)
  File "/home/ravi/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 869, in export_policy_checkpoint
    export_dir, filename_prefix, policy_id)
  File "/home/ravi/.local/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 796, in export_policy_checkpoint
    self.policy_map[policy_id].export_checkpoint(export_dir,
KeyError: 'default_policy'
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
OS: Ubuntu 18.04.4 LTS
python==3.6.9
torch==1.5.0
ray==0.8.4
tensorflow==1.14.0

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
```
from gym.spaces import Tuple, Discrete, Box, Dict
import ray
from ray import tune
from ray.tune.registry import register_env
from ray.rllib.env.multi_agent_env import MultiAgentEnv
from ray.rllib.agents.qmix import QMixTrainer
from ray.rllib.agents.qmix.qmix_policy import QMixTorchPolicy
import numpy as np
from ray.tune.trial import ExportFormat


class TestEnv(MultiAgentEnv):
    def __init__(self, config):
        self.n_agents = len(config["agents"])
        self.agents = config["agents"]
        self.observation_space = Box(low=np.array([0, 0]), high=np.array([1, 1]))
        self.obs_size = 2
        self.action_space = Discrete(3)

    def step(self, actions):
        obs_n = {}
        reward_n = {}
        done_n = {}
        info_n = {}

        for agent in self.agents:
            obs_n[agent] = {"obs": self.observation_space.sample()}
            reward_n[agent] = np.random.rand()
            done_n[agent] = True
            info_n[agent] = {}

        done_n["__all__"] = True
        return obs_n, reward_n, done_n, info_n

    def reset(self):
        return {agent: {"obs": np.zeros(self.obs_size)} for agent in self.agents}


def env_creator(args):
    env = TestEnv(args)

    grouping = {"group_1": ["0", "1"], "group_2": ["2", "3"]}

    return env.with_agent_groups(grouping)


ray.init()
register_env("grouped_test", env_creator)

env_config = {"agents": ["0", "1", "2", "3"]}

env = TestEnv(config=env_config)
obs_space = env.observation_space
act_space = env.action_space

obs_space = Tuple([Dict({"obs": obs_space}) for _ in range(2)])
act_space = Tuple([act_space for _ in range(2)])

config = {
    "multiagent": {
        "policies": {
            "group_1": (QMixTorchPolicy, obs_space, act_space, {}),
            "group_2": (QMixTorchPolicy, obs_space, act_space, {}),
        },
        "policy_mapping_fn": lambda agent_id: agent_id,
    },
    "mixer": "qmix",
    "env": "grouped_test",
    "env_config": env_config,
    "num_workers": 0,
    "timesteps_per_iteration": 2,
}
stop = {"timesteps_total": 5}
tune.run(
    "QMIX",
    config=config,
    stop=stop,
    checkpoint_at_end=True,
    export_formats=[ExportFormat.CHECKPOINT, ExportFormat.MODEL],
)
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by JianmingTONG** [comment]
Hi, is there any progress on this problem?
