### ISSUE TITLE
Pickler.dump raises `NoneType object is not callable`

### ISSUE THREAD

**Issue by PonteIneptique** [ray-project/ray#9098]
Hi !

### What is your question?

Pretty sure it's not a bug, and just me not understanding the API/documentation. If you look at my class [there](https://github.com/PonteIneptique/pie/blob/3bfb8b7587b82fb273d6f106a71c5d75c2805c2b/pie/scripts/tune.py#L69), as soon as I start training, and apparently before the class is setup, I get a Pickler issue. I have no idea why, it looks to me like I followed exactly the examples in the doc. Would you have any pointer for me ? 

I have tried commenting out parts, whatever I do I always encounter the issue...

Thanks in advance :)

```pythontb
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/pie/scripts/tune.py", line 196, in <module>
    resources_per_trial={"gpu": 1}
  File "~/env/lib/python3.7/site-packages/ray/tune/tune.py", line 247, in run
    run_identifier = Experiment.register_if_needed(exp)
  File "~/env/lib/python3.7/site-packages/ray/tune/experiment.py", line 203, in register_if_needed
    register_trainable(name, run_object)
  File "~/env/lib/python3.7/site-packages/ray/tune/registry.py", line 70, in register_trainable
    _global_registry.register(TRAINABLE_CLASS, name, trainable)
  File "~/env/lib/python3.7/site-packages/ray/tune/registry.py", line 112, in register
    self._to_flush[(category, key)] = pickle.dumps(value)
  File "~/env/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 72, in dumps
    cp.dump(obj)
  File "~/env/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 617, in dump
    return Pickler.dump(self, obj)
TypeError: 'NoneType' object is not callable
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

- Python: 3.7
- PyTorch 1.3.1
- Ubuntu 18.04

**Comment by richardliaw** [comment]
This looks like a bug on our side - cc @suquark who worked on serialization

**Comment by PonteIneptique** [comment]
Small note: I tried the last two or three bugfix version (x.y.z the z here). I have not access to this right now so I can't confirm the exact version.

**Comment by suquark** [comment]
@PonteIneptique Hi, when I run your script, I received errors like:

```
(pie) ➜ pie git:(3bfb8b7) python pie/scripts/tune.py
Traceback (most recent call last):
  File "/Users/siyuan/Code/tests/pie/pie/settings.py", line 126, in settings_from_file
    with open(config_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pie/scripts/tune.py", line 169, in <module>
    settings = settings_from_file(args.config_path)
  File "/Users/siyuan/Code/tests/pie/pie/settings.py", line 130, in settings_from_file
    "Couldn't read config file: %s. Exception: %s" % (config_path, str(e)))
ValueError: Couldn't read config file: config.json. Exception: [Errno 2] No such file or directory: 'config.json'
```

could you point that what is the proper way to run your script (and the required `config.json`)?

PS: I did not setup the package though, because I assume I can execute it correctly without a setup by looking into the codebase. I can setup it if it is necessary to reproduce the bug.

**Comment by PonteIneptique** [comment]
Hey !
Thanks for the answer !
Actually, I think you could run it by commenting things out, specifically https://github.com/PonteIneptique/pie/blob/3bfb8b7587b82fb273d6f106a71c5d75c2805c2b/pie/scripts/tune.py#L169

Because, from what I remember, it breaks before the `_setup()` method is called.

**Comment by suquark** [comment]
sorry, I cannot trigger the error before `env_setup`:

```
(pie) ➜ pie git:(3bfb8b7) ✗ python pie/scripts/tune.py
2020-06-25 13:35:48,092	INFO resource_spec.py:212 -- Starting Ray with 3.91 GiB memory available for workers and up to 1.96 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-06-25 13:35:48,311	WARNING services.py:923 -- Redis failed to start, retrying now.
2020-06-25 13:35:48,505	INFO services.py:1165 -- View the Ray dashboard at localhost:8265
Using seed: 133609
Traceback (most recent call last):
  File "pie/scripts/tune.py", line 190, in <module>
    env_setup()
  File "pie/scripts/tune.py", line 48, in env_setup
    if settings.verbose:
NameError: name 'settings' is not defined
```

I am using Python 3.6.9 + ray 0.8.5 under macOS.

However, I find something suspicious from your pervious error message:

```
 File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/pie/scripts/tune.py", line 196, in <module>
    resources_per_trial={"gpu": 1}
```

it seems that the module was not loaded in a normal way (likely executed by runpy). From my past experience, this might break serialization tools like cloudpickle that used by Ray, because couldpickle could fail to locate the class you specified. One workaround is to move your class definition to another file that can be clearly imported by python (e.g. import pie.xxx.xxx).

**Comment by sheetalsatheesh** [comment]
![rayband](https://user-images.githubusercontent.com/110782111/194838571-9e64d006-9dca-40e3-b73b-6942827868fc.jpg)
Hello,
I am facing the same issue while using Hyperband using ray-tune. Could you please let me know if you have found a solution for this?

**Comment by richardliaw** [comment]
@sheetalsatheesh please post a new issue with a reproducible script for us to run!

**Comment by aksh-gupta** [comment]
@sheetalsatheesh Did you find the cause for this?

**Comment by medram** [comment]
I've got the same issue while using native Python `pickle`, somehow the class object that I pass to be dumped raise the same error:
```python
from pydantic import BaseModel

class ChatRoom(BaseModel):
    	uuid: str
	chat: Chat
	db: Optional[VectorStore]
	agent: Optional[AgentExecutor]

chat_room = ChatRoom(...)

pickle.dumps(chat_room)
# output error: TypeError: 'NoneType' object is not callable
```
Please does anyone have a solution for this?
