### ISSUE TITLE
[rllib] Atari DQN action IndexError

### ISSUE THREAD

**Issue by juliusfrost** [ray-project/ray#9274]
### What is the problem?

I get an IndexError when using tune to run DQN on atari. See error below.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.8.6, Python 3.6, CentOS Linux 7, PyTorch 1.3

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
git clone https://github.com/juliusfrost/rllib-tune-atari.git
cd rllib-tune-atari
pip install -r requirements.txt
python train.py --algo dqn
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

Error:
```
2020-06-29 16:53:34,822	INFO resource_spec.py:212 -- Starting Ray with 120.02 GiB memory available for workers and up to 55.43 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-06-29 16:53:35,114	WARNING services.py:923 -- Redis failed to start, retrying now.
2020-06-29 16:53:36,482	INFO services.py:1165 -- View the Ray dashboard at [1m[32mlocalhost:8265[39m[22m
2020-06-29 16:54:49,395	ERROR trial_runner.py:520 -- Trial DQN_BreakoutNoFrameskip-v4_bad0f_00000: Error processing event.
Traceback (most recent call last):
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 468, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 430, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/worker.py", line 1474, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(IndexError): [36mray::DQN.train()[39m (pid=128941, ip=192.168.20.67)
  File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 400, in ray._raylet.execute_task.function_executor
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 500, in train
    raise e
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 486, in train
    result = Trainable.train(self)
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 132, in _train
    return self._train_exec_impl()
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 170, in _train_exec_impl
    res = next(self.train_exec_impl)
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/util/iter.py", line 731, in __next__
    return next(self.built_iterator)
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/util/iter.py", line 814, in apply_filter
    for item in it:
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/util/iter.py", line 814, in apply_filter
    for item in it:
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/util/iter.py", line 814, in apply_filter
    for item in it:
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/util/iter.py", line 1047, in build_union
    item = next(it)
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/util/iter.py", line 731, in __next__
    return next(self.built_iterator)
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/rllib/execution/rollout_ops.py", line 70, in sampler
    yield workers.local_worker().sample()
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 528, in sample
    batches = [self.input_reader.next()]
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 59, in next
    batches = [self.get_data()]
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 164, in get_data
    item = next(self.rollout_provider)
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 518, in _env_runner
    base_env.send_actions(actions_to_send)
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/rllib/env/base_env.py", line 329, in send_actions
    self.vector_env.vector_step(action_vector)
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/rllib/env/vector_env.py", line 136, in vector_step
    obs, r, done, info = self.envs[i].step(actions[i])
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/rllib/env/atari_wrappers.py", line 249, in step
    ob, reward, done, info = self.env.step(action)
  File "<env-dir>/ray/lib/python3.6/site-packages/gym/core.py", line 261, in step
    observation, reward, done, info = self.env.step(action)
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/rllib/env/atari_wrappers.py", line 138, in step
    return self.env.step(ac)
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/rllib/env/atari_wrappers.py", line 151, in step
    obs, reward, done, info = self.env.step(action)
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/rllib/env/atari_wrappers.py", line 192, in step
    obs, reward, done, info = self.env.step(action)
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/rllib/env/atari_wrappers.py", line 106, in step
    return self.env.step(ac)
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/rllib/env/atari_wrappers.py", line 58, in step
    obs, rew, done, info = self.env.step(action)
  File "<env-dir>/ray/lib/python3.6/site-packages/gym/wrappers/time_limit.py", line 16, in step
    observation, reward, done, info = self.env.step(action)
  File "<env-dir>/ray/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 113, in step
    action = self._action_set[a]
IndexError: index 193 is out of bounds for axis 0 with size 4
== Status ==
Memory usage on this node: 4.7/187.2 GiB
Using FIFO scheduling algorithm.
Resources requested: 1/28 CPUs, 0.2/1 GPUs, 0.0/120.02 GiB heap, 0.0/38.23 GiB objects
Result logdir: <project-dir>/results/DQN-Atari
Number of trials: 1 (1 RUNNING)
+----------------------------------------+----------+-------+
| Trial name                             | status   | loc   |
|----------------------------------------+----------+-------|
| DQN_BreakoutNoFrameskip-v4_bad0f_00000 | RUNNING  |       |
+----------------------------------------+----------+-------+


[2m[36m(pid=128941)[0m 2020-06-29 16:54:38,921	WARNING deprecation.py:30 -- DeprecationWarning: `sample_batch_size` has been deprecated. Use `rollout_fragment_length` instead. This will raise an error in the future!
[2m[36m(pid=128941)[0m 2020-06-29 16:54:38,921	WARNING deprecation.py:30 -- DeprecationWarning: `use_pytorch` has been deprecated. Use `framework=torch` instead. This will raise an error in the future!
[2m[36m(pid=128941)[0m 2020-06-29 16:54:38,921	INFO trainer.py:612 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
[2m[36m(pid=128941)[0m 2020-06-29 16:54:38,921	WARNING deprecation.py:30 -- DeprecationWarning: `schedule_max_timesteps` has been deprecated. Use `exploration_config.epsilon_timesteps AND prioritized_replay_beta_annealing_timesteps` instead. This will raise an error in the future!
[2m[36m(pid=128941)[0m 2020-06-29 16:54:38,921	WARNING deprecation.py:30 -- DeprecationWarning: `exploration_final_eps` has been deprecated. Use `exploration_config.final_epsilon` instead. This will raise an error in the future!
[2m[36m(pid=128941)[0m 2020-06-29 16:54:38,921	WARNING deprecation.py:30 -- DeprecationWarning: `exploration_fraction` has been deprecated. Use `exploration_config.epsilon_timesteps` instead. This will raise an error in the future!
[2m[36m(pid=128941)[0m 2020-06-29 16:54:38,921	WARNING deprecation.py:30 -- DeprecationWarning: `beta_annealing_fraction (decimal)` has been deprecated. Use `prioritized_replay_beta_annealing_timesteps (int)` instead. This will raise an error in the future!
== Status ==
Memory usage on this node: 7.6/187.2 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/28 CPUs, 0.0/1 GPUs, 0.0/120.02 GiB heap, 0.0/38.23 GiB objects
Result logdir: <project-dir>/results/DQN-Atari
Number of trials: 1 (1 ERROR)
+----------------------------------------+----------+-------+
| Trial name                             | status   | loc   |
|----------------------------------------+----------+-------|
| DQN_BreakoutNoFrameskip-v4_bad0f_00000 | ERROR    |       |
+----------------------------------------+----------+-------+
Number of errored trials: 1
+----------------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------+
| Trial name                             |   # failures | error file                                                                                                                 |
|----------------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------|
| DQN_BreakoutNoFrameskip-v4_bad0f_00000 |            1 | <project-dir>/results/DQN-Atari/DQN_BreakoutNoFrameskip-v4_0_2020-06-29_16-54-31fis76hnn/error.txt |
+----------------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------+

== Status ==
Memory usage on this node: 7.6/187.2 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/28 CPUs, 0.0/1 GPUs, 0.0/120.02 GiB heap, 0.0/38.23 GiB objects
Result logdir: <project-dir>/results/DQN-Atari
Number of trials: 1 (1 ERROR)
+----------------------------------------+----------+-------+
| Trial name                             | status   | loc   |
|----------------------------------------+----------+-------|
| DQN_BreakoutNoFrameskip-v4_bad0f_00000 | ERROR    |       |
+----------------------------------------+----------+-------+
Number of errored trials: 1
+----------------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------+
| Trial name                             |   # failures | error file                                                                                                                 |
|----------------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------|
| DQN_BreakoutNoFrameskip-v4_bad0f_00000 |            1 | <project-dir>/results/DQN-Atari/DQN_BreakoutNoFrameskip-v4_0_2020-06-29_16-54-31fis76hnn/error.txt |
+----------------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------+

Traceback (most recent call last):
  File "train_dqn.py", line 60, in <module>
    main()
  File "train_dqn.py", line 54, in main
    'use_pytorch': True
  File "<env-dir>/ray/lib/python3.6/site-packages/ray/tune/tune.py", line 349, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [DQN_BreakoutNoFrameskip-v4_bad0f_00000])
```

**Comment by rkooo567** [comment]
cc @sven1977
