### ISSUE TITLE
Help Installing Ray on NVIDIA Jetson TX2

### ISSUE THREAD

**Issue by AashinShazar** [ray-project/ray#9308]
I was just wondering if anyone had a guide to install ray on a NVIDIA Jetson TX2. It features an aarch64 system architecture so I'm unable to get away with a simple pip install.

I've stumbled across this guide [https://gist.github.com/yunqu/bdbe9c34b883398bf97cf5361db63171](url) but not having any luck installing Ray. I've managed to install bazel on the system but I'm unable to proceed when I reach the py-spy installation requirement. 

Has anyone had any luck in these past few months in installing ray on this board?

**Comment by rkooo567** [comment]
cc @mehrdadn ?

**Comment by mehrdadn** [comment]
I don't really know the issue, but if `py-spy` is the obstacle, it might be worth trying to remove it? You can remove the requirement from `setup.py` and then let it proceed and see what happens. (It'd be nice if you also post the actual errors that you encounter by the way.)

**Comment by evanthomas** [comment]
I'm having multiple problems trying to build on a jetson nano.

1. `npm ci` is not a thing
2. the bazel install script silently fails. I manually installed 3.5.0 (there doesn't seem to an arm64 version of 3.2.0)
3. py-spy is not a thing either, so I just removed the dependency
4. After all that it, sill fails with:

```
    ERROR: Command errored out with exit status 1:
     command: /home/evan/.virtualenvs/tf2.2b/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/evan/ray/python/setup.py'"'"'; __file__='"'"'/home/evan/ray/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/evan/ray/python/
    Complete output (55 lines):
    running develop
    running egg_info
    writing ray.egg-info/PKG-INFO
    writing dependency_links to ray.egg-info/dependency_links.txt
    writing entry points to ray.egg-info/entry_points.txt
    writing requirements to ray.egg-info/requires.txt
    writing top-level names to ray.egg-info/top_level.txt
    reading manifest file 'ray.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    /home/evan/.virtualenvs/tf2.2b/lib/python3.6/site-packages/setuptools/dist.py:679: UserWarning: Module Cython was already imported from /home/evan/.virtualenvs/tf2.2b/lib/python3.6/site-packages/Cython/__init__.py, but /home/evan/ray/python/.eggs/Cython-0.29.21-py3.6.egg is being added to sys.path
      pkg_resources.working_set.add(dist, replace=True)
    /home/evan/.virtualenvs/tf2.2b/lib/python3.6/site-packages/setuptools/dist.py:679: UserWarning: Module cython was already imported from /home/evan/.virtualenvs/tf2.2b/lib/python3.6/site-packages/cython.py, but /home/evan/ray/python/.eggs/Cython-0.29.21-py3.6.egg is being added to sys.path
      pkg_resources.working_set.add(dist, replace=True)
    warning: no files found matching 'ray/python/ray/autoscaler/ray-schema.json'
    writing manifest file 'ray.egg-info/SOURCES.txt'
    running build_ext
    WARNING: Target directory /home/evan/ray/python/ray/thirdparty_files/psutil already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /home/evan/ray/python/ray/thirdparty_files/setproctitle.cpython-36m-aarch64-linux-gnu.so already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /home/evan/ray/python/ray/thirdparty_files/setproctitle-1.1.10.dist-info already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /home/evan/ray/python/ray/thirdparty_files/psutil-5.7.2.dist-info already exists. Specify --upgrade to force replacement.
    Starting local Bazel server and connecting to it...
    INFO: Reading rc options for 'build' from /home/evan/ray/.bazelrc:
      'build' options: --enable_platform_specific_config --action_env=PATH --compilation_mode=opt --experimental_ui_deduplicate --per_file_copt=\.pb\.cc$@-w --per_file_copt=-\.(asm|S)$,external/.*@-w --per_file_copt=-\.(asm|S)$,external/com_github_grpc_grpc/.*@-DGRPC_BAZEL_BUILD --http_timeout_scaling=5.0 --verbose_failures
    ERROR: --experimental_ui_deduplicate :: Unrecognized option: --experimental_ui_deduplicate
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/evan/ray/python/setup.py", line 468, in <module>
        license="Apache 2.0") if __name__ == "__main__" else None
      File "/home/evan/.virtualenvs/tf2.2b/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/evan/.virtualenvs/tf2.2b/lib/python3.6/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/evan/.virtualenvs/tf2.2b/lib/python3.6/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/evan/ray/python/setup.py", line 432, in run
        return pip_run(self)
      File "/home/evan/ray/python/setup.py", line 341, in pip_run
        build(True, BUILD_JAVA)
      File "/home/evan/ray/python/setup.py", line 301, in build
        env=bazel_env)
      File "/home/evan/ray/python/setup.py", line 184, in bazel_invoke
        result = invoker([cmd] + cmdline, *args, **kwargs)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/evan/.bazel/bin/bazel', 'build', '--verbose_failures', '--', '//:ray_pkg']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/evan/.virtualenvs/tf2.2b/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/evan/ray/python/setup.py'"'"'; __file__='"'"'/home/evan/ray/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

Of course, this might be because of my other hacks.
