### ISSUE TITLE
[rllib] Cannot detect pybullet environments.

### ISSUE THREAD

**Issue by KarlXing** [ray-project/ray#9309]
### Pybullet Environments Cannot Be Detected By Ray/rllib

Hi, I'm trying to use rllib to train pybullet games. My environment is ray 0.8.4, ubuntu 16.04, Pytorch  1.2.0. It seems that ray cannot detect these games and said the game was not registered. But I can make the gym environment outside ray within the same script. I attached a simple code to show what's wrong. Could someone help with this? Thanks!!

```
import ray
from ray.rllib.agents.ppo import PPOTrainer
from ray.tune.registry import register_env
import gym
import pybullet_envs

env = gym.make('HumanoidBulletEnv-v0')
print("Made Successfully")

class MyEnv(gym.Env):
    def __init__(self, env_config):
        self.env = gym.make('HumanoidBulletEnv-v0')
        self.action_space = self.env.action_space
        self.observation_space = self.env.observation_space

    def reset(self):
        obs = self.env.reset()
        return obs

    def step(self, action):
        action = self.action_space.high * action
        obs, reward, done, info = self.env.step(action)
        return obs, reward, done, info

register_env("myenv", lambda config: MyEnv(config))


def main():
    ray.init()    
    trainer = PPOTrainer(env="myenv", config={
        "use_pytorch": True,
        })

    for i in range(100):
        trainer.train()

    trainer.stop()

if __name__ == '__main__':
    main()
```

When I run the code, the environment outside ray could be made successfully and 'Made Successfully' was printed. But then I get the error that 

```
Traceback (most recent call last):
  File "pybullet_train.py", line 44, in <module>
    main()
  File "pybullet_train.py", line 39, in main
    trainer.train()
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 502, in train
    raise e
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 491, in train
    result = Trainable.train(self)
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 150, in _train
    fetches = self.optimizer.step()
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/ray/rllib/optimizers/sync_samples_optimizer.py", line 59, in step
    for e in self.workers.remote_workers()
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/memory.py", line 29, in ray_get_and_free
    result = ray.get(object_ids)
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1513, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(UnregisteredEnv): ray::RolloutWorker.__init__() (pid=8430, ip=192.168.1.8)
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py", line 118, in spec
    return self.env_specs[id]
KeyError: 'HumanoidBulletEnv-v0'

During handling of the above exception, another exception occurred:

ray::RolloutWorker.__init__() (pid=8430, ip=192.168.1.8)
  File "python/ray/_raylet.pyx", line 414, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 414, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 414, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 450, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 287, in __init__
    self.env = _validate_env(env_creator(env_context))
  File "pybullet_train.py", line 27, in <lambda>
    register_env("myenv", lambda config: MyEnv(config))
  File "pybullet_train.py", line 14, in __init__
    self.env = gym.make('HumanoidBulletEnv-v0')
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py", line 142, in make
    return registry.make(id, **kwargs)
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py", line 86, in make
    spec = self.spec(path)
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py", line 128, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: HumanoidBulletEnv-v0
```

I know 'import pybullet_envs' will register the environments in gym. It looked like rollout workers didn't detect these environments. Could someone tell me how to solve this? Thank you!

**Comment by ericl** [comment]
Can you try moving the import into the constructor for your class? The problem is the import only applies locally and not on the Ray workers.

**Comment by KarlXing** [comment]
Great! Importing pybullet_envs inside MyEnv class works. Thank you for the quick reply.

**Comment by Glaucus-2G** [comment]
> Great! Importing pybullet_envs inside MyEnv class works. Thank you for the quick reply.


Could you show me your codes? I am learning how to use it! Thank you!

**Comment by Glaucus-2G** [comment]
> > Great! Importing pybullet_envs inside MyEnv class works. Thank you for the quick reply.

> Could you show me your codes? I am learning how to use it! Thank you!

I think I have got it.  Thank you!
