### ISSUE TITLE
ray: 'SerializationContext' object has no attribute 'core_worker'

### ISSUE THREAD

**Issue by sytelus** [ray-project/ray#9408]
### What is the problem?

Ray version: 0.8.6 on Ubuntu 18, Python 3.6

I'm getting following error for a short program directly copied from the tutorial:

```
(base) ~/.../archai$ /home/shitals/anaconda3/bin/python /home/shitals/GitHubSrc/archai/scripts/misc/ray_test.py
2020-07-10 10:52:41,983 INFO resource_spec.py:212 -- Starting Ray with 33.98 GiB memory available for workers and up to 17.01 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-07-10 10:52:42,201 WARNING services.py:923 -- Redis failed to start, retrying now.
2020-07-10 10:52:42,493 INFO services.py:1165 -- View the Ray dashboard at localhost:8265
2020-07-10 10:52:58,619 ERROR worker.py:987 -- Possible unhandled error from worker: ray::__main__.do_some_work() (pid=25094, ip=10.0.0.204)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 241, in _deserialize_msgpack_data
    _python_deserializer)
  File "python/ray/includes/serialization.pxi", line 180, in ray._raylet.MessagePackSerializer.loads
  File "msgpack/_unpacker.pyx", line 161, in msgpack._unpacker.unpackb
TypeError: unpackb() got an unexpected keyword argument 'strict_map_key'

During handling of the above exception, another exception occurred:

ray::__main__.do_some_work() (pid=25094, ip=10.0.0.204)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 312, in deserialize_objects
    self._deserialize_object(data, metadata, object_id))
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 252, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 243, in _deserialize_msgpack_data
    raise DeserializationError()
ray.serialization.DeserializationError

During handling of the above exception, another exception occurred:

ray::__main__.do_some_work() (pid=25094, ip=10.0.0.204)
  File "python/ray/_raylet.pyx", line 410, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 427, in ray._raylet.execute_task
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 331, in deserialize_objects
    job_id=self.worker.current_job_id)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/utils.py", line 91, in push_error_to_driver
    worker.core_worker.push_error(job_id, error_type, message, time.time())
AttributeError: 'SerializationContext' object has no attribute 'core_worker'
2020-07-10 10:52:58,620 ERROR worker.py:987 -- Possible unhandled error from worker: ray::__main__.do_some_work() (pid=25095, ip=10.0.0.204)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 241, in _deserialize_msgpack_data
    _python_deserializer)
  File "python/ray/includes/serialization.pxi", line 180, in ray._raylet.MessagePackSerializer.loads
  File "msgpack/_unpacker.pyx", line 161, in msgpack._unpacker.unpackb
TypeError: unpackb() got an unexpected keyword argument 'strict_map_key'

During handling of the above exception, another exception occurred:

ray::__main__.do_some_work() (pid=25095, ip=10.0.0.204)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 312, in deserialize_objects
    self._deserialize_object(data, metadata, object_id))
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 252, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 243, in _deserialize_msgpack_data
    raise DeserializationError()
ray.serialization.DeserializationError

During handling of the above exception, another exception occurred:

ray::__main__.do_some_work() (pid=25095, ip=10.0.0.204)
  File "python/ray/_raylet.pyx", line 410, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 427, in ray._raylet.execute_task
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 331, in deserialize_objects
    job_id=self.worker.current_job_id)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/utils.py", line 91, in push_error_to_driver
    worker.core_worker.push_error(job_id, error_type, message, time.time())
AttributeError: 'SerializationContext' object has no attribute 'core_worker'
2020-07-10 10:52:58,620 ERROR worker.py:987 -- Possible unhandled error from worker: ray::__main__.do_some_work() (pid=25093, ip=10.0.0.204)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 241, in _deserialize_msgpack_data
    _python_deserializer)
  File "python/ray/includes/serialization.pxi", line 180, in ray._raylet.MessagePackSerializer.loads
  File "msgpack/_unpacker.pyx", line 161, in msgpack._unpacker.unpackb
TypeError: unpackb() got an unexpected keyword argument 'strict_map_key'

During handling of the above exception, another exception occurred:

ray::__main__.do_some_work() (pid=25093, ip=10.0.0.204)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 312, in deserialize_objects
    self._deserialize_object(data, metadata, object_id))
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 252, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 243, in _deserialize_msgpack_data
    raise DeserializationError()
ray.serialization.DeserializationError

During handling of the above exception, another exception occurred:

ray::__main__.do_some_work() (pid=25093, ip=10.0.0.204)
  File "python/ray/_raylet.pyx", line 410, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 427, in ray._raylet.execute_task
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 331, in deserialize_objects
    job_id=self.worker.current_job_id)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/utils.py", line 91, in push_error_to_driver
    worker.core_worker.push_error(job_id, error_type, message, time.time())
AttributeError: 'SerializationContext' object has no attribute 'core_worker'
2020-07-10 10:52:58,620 ERROR worker.py:987 -- Possible unhandled error from worker: ray::__main__.do_some_work() (pid=25096, ip=10.0.0.204)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 241, in _deserialize_msgpack_data
    _python_deserializer)
  File "python/ray/includes/serialization.pxi", line 180, in ray._raylet.MessagePackSerializer.loads
  File "msgpack/_unpacker.pyx", line 161, in msgpack._unpacker.unpackb
TypeError: unpackb() got an unexpected keyword argument 'strict_map_key'

During handling of the above exception, another exception occurred:

ray::__main__.do_some_work() (pid=25096, ip=10.0.0.204)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 312, in deserialize_objects
    self._deserialize_object(data, metadata, object_id))
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 252, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 243, in _deserialize_msgpack_data
    raise DeserializationError()
ray.serialization.DeserializationError

During handling of the above exception, another exception occurred:

ray::__main__.do_some_work() (pid=25096, ip=10.0.0.204)
  File "python/ray/_raylet.pyx", line 410, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 427, in ray._raylet.execute_task
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 331, in deserialize_objects
    job_id=self.worker.current_job_id)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/utils.py", line 91, in push_error_to_driver
    worker.core_worker.push_error(job_id, error_type, message, time.time())
AttributeError: 'SerializationContext' object has no attribute 'core_worker'
Traceback (most recent call last):
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 241, in _deserialize_msgpack_data
    _python_deserializer)
  File "python/ray/includes/serialization.pxi", line 180, in ray._raylet.MessagePackSerializer.loads
  File "msgpack/_unpacker.pyx", line 161, in msgpack._unpacker.unpackb
TypeError: unpackb() got an unexpected keyword argument 'strict_map_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 312, in deserialize_objects
    self._deserialize_object(data, metadata, object_id))
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 271, in _deserialize_object
    obj = self._deserialize_msgpack_data(data, metadata)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 243, in _deserialize_msgpack_data
    raise DeserializationError()
ray.serialization.DeserializationError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shitals/GitHubSrc/archai/scripts/misc/ray_test.py", line 21, in <module>
    r = ray.get(done_id[0])
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 1467, in get
    values = worker.get_objects(object_ids, timeout=timeout)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 306, in get_objects
    return self.deserialize_objects(data_metadata_pairs, object_ids)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 281, in deserialize_objects
    return context.deserialize_objects(data_metadata_pairs, object_ids)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/serialization.py", line 331, in deserialize_objects
    job_id=self.worker.current_job_id)
  File "/home/shitals/anaconda3/lib/python3.6/site-packages/ray/utils.py", line 91, in push_error_to_driver
    worker.core_worker.push_error(job_id, error_type, message, time.time())
AttributeError: 'SerializationContext' object has no attribute 'core_worker'
```

### Reproduction (REQUIRED)

Script to reproduce:

```
import time
import random
import ray

ray.init(num_cpus = 4)

@ray.remote
def do_some_work(x):
    time.sleep(random.uniform(0, 4)) # Replace this with work you need to do.
    return x

def process_incremental(sum, result):
    time.sleep(1) # Replace this with some processing code.
    return sum + result

start = time.time()
result_ids = [do_some_work.remote(x) for x in range(4)]
sum = 0
while len(result_ids):
    done_id, result_ids = ray.wait(result_ids)
    r = ray.get(done_id[0])
    sum = process_incremental(sum, r)
print("duration =", time.time() - start, "\nresult = ", sum)
```

- [ X] I have verified my script runs in a clean environment and reproduces the issue.
- [ X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by sytelus** [comment]
Update:

I ran `conda update conda` and that has fixed this error. My guess is that there was some dependency mismatch. May be ray package forgot to include minimum version number for that dependency?

**Comment by rkooo567** [comment]
We have a msgpack version constraint ("msgpack >= 0.6.0, < 2.0.0"). I guess there were some weird dependency resolution, but it is hard to know what it is.

**Comment by fsafaei** [comment]
I have the same issue, and updating conda does not help, unfortunately.

**Comment by rominf** [comment]
For me, upgrading to `msgpack=1.0.1` helped:
```$ pip install -U msgpack                                                        
Requirement already satisfied: msgpack in /home/conceptnet/conceptnet5_virtualenv/lib/python3.7/site-packages (1.0.0)       
Collecting msgpack                                                                                                                                                      
  Using cached msgpack-1.0.1-cp37-cp37m-manylinux2010_x86_64.whl (273 kB)  
Installing collected packages: msgpack                                              
  Attempting uninstall: msgpack                                                     
    Found existing installation: msgpack 1.0.0                                                                                                                          
    Uninstalling msgpack-1.0.0:                                                     
      Successfully uninstalled msgpack-1.0.0                      
Successfully installed msgpack-1.0.1
```

**Comment by rusiaaman** [comment]
Similar error, downgrading msgpack from 1.0.4 to 1.0.1 helped

```RaySystemError: System error: 
traceback: Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 201, in _deserialize_msgpack_data
    obj = MessagePackSerializer.loads(msgpack_data, _python_deserializer)
  File "python/ray/includes/serialization.pxi", line 191, in ray._raylet.MessagePackSerializer.loads
  File "python/ray/includes/serialization.pxi", line 192, in ray._raylet.MessagePackSerializer.loads
  File "msgpack/_unpacker.pyx", line 161, in msgpack._unpacker.unpackb
TypeError: unpackb() got an unexpected keyword argument 'strict_map_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 340, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 237, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 203, in _deserialize_msgpack_data
    raise DeserializationError()
ray.serialization.DeserializationError
```
