### ISSUE TITLE
Specify network interface to use / RuntimeError: Redis has started but no raylets have registered yet.

### ISSUE THREAD

**Issue by jkbe** [ray-project/ray#9456]
First off: I'm not exactly sure if this is a bug or a missing feature and whether maybe this is more about general OS configuration and not about Ray. 

### What is the problem?

I'm running Ray on a cluster of nodes where each node has two network interfaces, WLAN and LAN. The nodes are connected to the internet through one router over WLAN and connected with each other via LAN. For running Ray, I want the nodes to use the LAN interface (for smaller latency and higher network speed). However, the nodes can also communicate with each other over WLAN through the router and this is the route that Ray seems to prefer for communication. I can't get Ray to use the LAN network interface, even when explicitly specifying the local LAN IP addresses through `--node-ip-address`. I've also tried to turn off WLAN on the master node from where I start my script in an attempt to force the cluster to use LAN but no success either.

Raspbian GNU/Linux 10 (buster)
Python 3.7.3
Ray 0.8.6

### Reproduction

node1 has the local IP address `169.254.204.39` and node2 has `169.254.61.32`. Both of them can be pinged successfully from each other.

test.py
```
import ray
import time

ray.init(
    address='169.254.204.39:6379',  # changing this to 'auto' leads to the same error message
    ignore_reinit_error=True,
    webui_host='0.0.0.0',
    redis_password='5241590000000000'
)

@ray.remote
def f(i):
    time.sleep(1)
    return i

futures = [f.remote(i) for i in range(4)]
print(ray.get(futures))
```

- On node1: `ray start --head --port=6379 --node-ip-address='169.254.204.39'`
- On node2: `ray start --address='169.254.204.39:6379' --redis-password='5241590000000000' --node-ip-address='169.254.61.32'`
- On node1: `python3 test.py` prints:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0714 00:04:16.108295 10646 10646 global_state_accessor.cc:25] Redis server address = 169.254.204.39:6379, is test flag = 0
I0714 00:04:16.110410 10646 10646 redis_client.cc:141] RedisClient connected.
I0714 00:04:16.119617 10646 10646 redis_gcs_client.cc:88] RedisGcsClient Connected.
I0714 00:04:16.121834 10646 10646 service_based_gcs_client.cc:75] ServiceBasedGcsClient Connected.
2020-07-14 00:04:16,128	WARNING services.py:216 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
I0714 00:04:17.132067 10646 10646 global_state_accessor.cc:25] Redis server address = 169.254.204.39:6379, is test flag = 0
I0714 00:04:17.134346 10646 10646 redis_client.cc:141] RedisClient connected.
I0714 00:04:17.134692 10646 10646 redis_gcs_client.cc:88] RedisGcsClient Connected.
I0714 00:04:17.136186 10646 10646 service_based_gcs_client.cc:75] ServiceBasedGcsClient Connected.
2020-07-14 00:04:17,144	WARNING services.py:216 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
I0714 00:04:18.149408 10646 10646 global_state_accessor.cc:25] Redis server address = 169.254.204.39:6379, is test flag = 0
I0714 00:04:18.151854 10646 10646 redis_client.cc:141] RedisClient connected.
I0714 00:04:18.151934 10646 10646 redis_gcs_client.cc:88] RedisGcsClient Connected.
I0714 00:04:18.153203 10646 10646 service_based_gcs_client.cc:75] ServiceBasedGcsClient Connected.
2020-07-14 00:04:18,159	WARNING services.py:216 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
I0714 00:04:19.162681 10646 10646 global_state_accessor.cc:25] Redis server address = 169.254.204.39:6379, is test flag = 0
I0714 00:04:19.164664 10646 10646 redis_client.cc:141] RedisClient connected.
I0714 00:04:19.164728 10646 10646 redis_gcs_client.cc:88] RedisGcsClient Connected.
I0714 00:04:19.165938 10646 10646 service_based_gcs_client.cc:75] ServiceBasedGcsClient Connected.
2020-07-14 00:04:19,173	WARNING services.py:216 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
I0714 00:04:20.176661 10646 10646 global_state_accessor.cc:25] Redis server address = 169.254.204.39:6379, is test flag = 0
I0714 00:04:20.178596 10646 10646 redis_client.cc:141] RedisClient connected.
I0714 00:04:20.178660 10646 10646 redis_gcs_client.cc:88] RedisGcsClient Connected.
I0714 00:04:20.179823 10646 10646 service_based_gcs_client.cc:75] ServiceBasedGcsClient Connected.
2020-07-14 00:04:20,187	WARNING services.py:216 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
I0714 00:04:21.190459 10646 10646 global_state_accessor.cc:25] Redis server address = 169.254.204.39:6379, is test flag = 0
I0714 00:04:21.192633 10646 10646 redis_client.cc:141] RedisClient connected.
I0714 00:04:21.192703 10646 10646 redis_gcs_client.cc:88] RedisGcsClient Connected.
I0714 00:04:21.193975 10646 10646 service_based_gcs_client.cc:75] ServiceBasedGcsClient Connected.
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    redis_password='5241590000000000'
  File "/home/pi/.local/lib/python3.7/site-packages/ray/worker.py", line 785, in init
    connect_only=True)
  File "/home/pi/.local/lib/python3.7/site-packages/ray/node.py", line 141, in __init__
    redis_password=self.redis_password)
  File "/home/pi/.local/lib/python3.7/site-packages/ray/services.py", line 209, in get_address_info_from_redis
    redis_address, node_ip_address, redis_password=redis_password)
  File "/home/pi/.local/lib/python3.7/site-packages/ray/services.py", line 192, in get_address_info_from_redis_helper
    "Redis has started but no raylets have registered yet.")
RuntimeError: Redis has started but no raylets have registered yet.
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by guizhiyi** [comment]
Have you solved this problem? I have the same problem

**Comment by jakob-ed** [comment]
No, unfortunately we haven’t found a fix / workaround yet

**Comment by guizhiyi** [comment]
Have you tried #5437? It seems to be the solution. I tried, but the external address is not available. I don't know what went wrong. If you solve it, please tell me the solution.

**Comment by guizhiyi** [comment]
I use Ray version: 0.6.4, and use  'ray start --head --redis-port=6379 --redis-shard-ports=6380  --node-manager-port=12345 --object-manager-port=12346'. 
It works!!!!

**Comment by jakob-ed** [comment]
Hi @guizhiyi I'm glad you solved your problem but I'm not seeing how this solves the problem I encountered. You're not setting `--node-ip-address` anywhere in your `start` command so how do you know that the correct interface is used?

**Comment by guhaishuo** [comment]
I also have this problem when using Ray version:0.8.6. 
After changing to version:0.8.2, it works...

**Comment by nirandaperera** [comment]
@guhaishuo I am having the same issue in my local cluster. I tried downgrading to 0.8.2. But I am still having the issue, unfortunately...

**Comment by jack2nb** [comment]
ray.nodes()

[{'NodeID': '92cb9ab7ce0b377ca9d87ab718783a42c4034241',
  'Alive': True,
  'NodeManagerAddress': '192.168.2.23',
  'NodeManagerHostname': 'BF-202004231919',
  'NodeManagerPort': 58881,
  'ObjectManagerPort': 55495,
  'ObjectStoreSocketName': 'tcp://127.0.0.1:63652',
  'RayletSocketName': 'tcp://127.0.0.1:62371',
  'alive': True,
  'Resources': {'node:192.168.2.23': 1.0,
   'CPU': 8.0,
   'object_store_memory': 82.0,
   'memory': 239.0}}]

**Comment by jack2nb** [comment]
'RayletSocketName': 'tcp://127.0.0.1:62371',   
？？？'RayletSocketName': 'tcp://0.0.0.0:62371',

**Comment by jack2nb** [comment]
[{'NodeID': 'eb050733b3e3f2ea2a744a93315b7f2e9b964885',
  'Alive': True,
  'NodeManagerAddress': '192.168.2.24',
  'NodeManagerHostname': 'jack-virtual-machine',
  'NodeManagerPort': 64750,
  'ObjectManagerPort': 46145,
  'ObjectStoreSocketName': '/tmp/ray/session_2021-01-16_10-16-46_273950_16576/sockets/plasma_store',
  'RayletSocketName': '/tmp/ray/session_2021-01-16_10-16-46_273950_16576/sockets/raylet',
  'MetricsExportPort': 51187,
  'alive': True,
  'Resources': {'memory': 58.0,
   'object_store_memory': 20.0,
   'CPU': 8.0,
   'node:192.168.2.24': 1.0}}]


RayletSocketName  is local

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
