### ISSUE TITLE
[ray][tune] Ray does not make GPU available to Trainables 

### ISSUE THREAD

**Issue by Hadrien-Cornier** [ray-project/ray#9503]
### What is the problem?

I initialize ray with a GPU and assign the GPU to trials in the tune.run() call but Torch sees no GPU when the Trainable is created.

**Environment :** 
Python : 3.6.9
Cuda : Cuda compilation tools, release 10.0, V10.0.130
Torch  : '1.5.1'
Ray : '0.9.0.dev0'
OS : 
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```python
import ray
from ray import tune
import torch
ray.init(num_cpus=1, num_gpus=1)

class DummyClass(tune.Trainable):

    def setup(self, config):
        assert torch.cuda.is_available(), "No GPU visible"

if __name__ == "__main__" :
    config = {}
    asha_scheduler = tune.schedulers.ASHAScheduler()
    analysis = tune.run(DummyClass,
                        name="bug",
                        resources_per_trial={
                            "cpu": 1,
                            "gpu": 1},
                        num_samples=1,
                        scheduler=asha_scheduler,
                        config=config,
                        fail_fast = True) 
```

This produces the following error message : 

```
2020-07-15 09:35:03,159	ERROR trial_runner.py:523 -- Trial DummyClass_21670_00000: Error processing event.
Traceback (most recent call last):
  File "/home/hadrien/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 471, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/hadrien/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 430, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/hadrien/.local/lib/python3.6/site-packages/ray/worker.py", line 1519, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): ray::DummyClass.train() (pid=64296, ip=172.16.5.202)
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 467, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 471, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 472, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 425, in ray._raylet.execute_task.function_executor
  File "/home/hadrien/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 232, in __init__
    self.setup(copy.deepcopy(self.config))
  File "test_ray_bug.py", line 50, in setup
    assert torch.cuda.is_available(), "No GPU visible"
AssertionError: No GPU visible

```

If we cannot run your script, we cannot fix your issue.

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by amogkam** [comment]
Hi @Hadrien-Cornier, what does `torch.cuda.is_available()` print out when just try it on the Python interpreter?

**Comment by Hadrien-Cornier** [comment]
> Hi @Hadrien-Cornier, what does `torch.cuda.is_available()` print out when just try it on the Python interpreter?

It prints False, thanks for the help. I will reinstall pytorch.

**Comment by amogkam** [comment]
It looks like torch 1.5 only supports CUDA 10.1/10.2, not 10.0: https://github.com/pytorch/pytorch/issues/37320. You can either upgrade Cuda or downgrade to torch 1.4.
