### ISSUE TITLE
example for the ray tune cannot run

### ISSUE THREAD

**Issue by LLT1** [ray-project/ray#9605]
### examples in the ray tune cannot run
*I run the following tune examples from the office page: https://github.com/ray-project/ray/tree/master/python/ray/tune/examples, however, nothing is work but the example for the ppo: pbt_ppo_example.py.

The error reports :

2020-07-21 14:59:36,060	ERROR trial_runner.py:520 -- Trial MyTrainableClass_bc1ca907: Error processing event.
Traceback (most recent call last):
  File "/home/anaconda3/envs/Ray_tune/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 468, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/anaconda3/envs/Ray_tune/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 430, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/anaconda3/envs/Ray_tune/lib/python3.7/site-packages/ray/worker.py", line 1474, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(NotImplementedError): ray::MyTrainableClass.train() (pid=14255, ip=10.1.20.10)
  File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 400, in ray._raylet.execute_task.function_executor
  File "/home/anaconda3/envs/Ray_tune/lib/python3.7/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/home/anaconda3/envs/Ray_tune/lib/python3.7/site-packages/ray/tune/trainable.py", line 586, in _train
    raise NotImplementedError
NotImplementedError
Traceback (most recent call last):
  File "/home/PycharmProjects/raytune_1/BOHB_test.py", line 66, in <module>
    stop={"training_iteration": 100})
  File "/home/anaconda3/envs/Ray_tune/lib/python3.7/site-packages/ray/tune/tune.py", line 349, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [MyTrainableClass_bc1ca8f2, MyTrainableClass_bc1ca8f3, MyTrainableClass_bc1ca8f4, MyTrainableClass_bc1ca8f5, MyTrainableClass_bc1ca8fb, MyTrainableClass_bc1ca8fe, MyTrainableClass_bc1ca901, MyTrainableClass_bc1ca904, MyTrainableClass_bc1ca907, MyTrainableClass_bc1ca90a])

*Ray version: 0.86, and other system information (Python version 3.7.7, TensorFlow version: 2.1.0, Pytorch version:1.5.1):*

**Comment by richardliaw** [comment]
Can you post your code? Specifically, it looks like you did not implement the Trainable interface correctly

**Comment by nscotto** [comment]
I am having the same issue running the [tf_mnist_example](https://docs.ray.io/en/master/tune/examples/tf_mnist_example.html) (the code is in the link).

**Comment by richardliaw** [comment]
@nscotto and @LLT1 can you try viewing the examples on the latest Ray release branch?

https://github.com/ray-project/ray/tree/releases/0.8.6

We changed some APIs between master and the last pip release. The above branch should have all of the correct examples.

**Comment by richardliaw** [comment]
Alternatively you can install the latest nightly wheels https://ray.readthedocs.io/en/master/installation.html and view documentation from the `master` branch.

**Comment by LLT1** [comment]
> @nscotto and @LLT1 can you try viewing the examples on the latest Ray release branch?
> 
> https://github.com/ray-project/ray/tree/releases/0.8.6
> 
> We changed some APIs between master and the last pip release. The above branch should have all of the correct examples.

@richardliaw  Thx! They works!

**Comment by nscotto** [comment]
Is there any example using tune?
The examples I found are the ones in [doc/examples/doc_code](https://github.com/ray-project/ray/tree/releases/0.8.6/doc/examples/doc_code), only a tf_example.py and torch_example.py that don't use tune.

**Comment by richardliaw** [comment]
Yep!
https://github.com/ray-project/ray/tree/releases/0.8.6/python/ray/tune/examples

**Comment by nscotto** [comment]
Perfect, thank you!
