### ISSUE TITLE
[dashboard] Hide the 'FileNotFound' stacktrace

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#9620]
### What is the problem?
```
WARNING:ray.worker:The dashboard on node DESKTOP-KBV1GE9 failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ray\dashboard/dashboard.py", line 960, in <module>
    metrics_export_address=metrics_export_address)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ray\dashboard/dashboard.py", line 513, in __init__
    build_dir = setup_static_dir(self.app)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ray\dashboard/dashboard.py", line 414, in setup_static_dir
    "&& npm run build)", build_dir)
FileNotFoundError: [Errno 2] Dashboard build directory not found. If installing from source, please follow the additional steps required to build the dashboard(cd python/ray/dashboard/client && npm ci && npm run build): 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\dashboard\\client/build'

```

When wrapping Ray in a higher level library, users will see this for whatever reason, even though they probably are not interacting with Ray. See https://github.com/ray-project/tune-sklearn/issues/50

This can be unfriendly to other developers, and we should probably just log the message rather than the trace.

cc @mfitton

**Comment by richardliaw** [comment]
cc @mehrdadn (windows specific it seems?)

**Comment by mehrdadn** [comment]
The dashboard isn't working on Windows, so this is why it only appears on Windows in normal operation. But the message isn't inherently platform-specific. I don't think we should be raising an error regardless if the dashboard isn't needed, but I've brought this up before and others have preferred the error to stay, so I'm not sure what to do. I do have the following diff that I sometimes use locally, but it's probably not ideal to commit:

```
+        traceback_str = traceback_str.splitlines()[-1]
-        message = ("The dashboard on node {} failed with the following "
+        message = ("The dashboard on node {} failed with the following "
-                   "error:\n{}".format(platform.node(), traceback_str))
+                   "error: {}".format(platform.node(), traceback_str))
```

**Comment by richardliaw** [comment]
@mehrdadn can you dm me the prior conversation? I'd like to push to get this error hidden (at least for Windows)
