### ISSUE TITLE
[util.multiprocessing] Support generators

### ISSUE THREAD

**Issue by icaropires** [ray-project/ray#9712]
### Describe your feature request
Currently `util.multiprocessing.Pool` methods (like `imap`) don't support generators because of the `cannot pickle 'generator' object` error. I've also tried to use `util.iter` but it fails because `util.multiprocessing` needs the length of the iterable:
https://github.com/ray-project/ray/blob/54a0d8b69ef74856e18c5f5b732a3420ab8a7f32/python/ray/util/multiprocessing/pool.py#L186-L190

I think this would be a very useful if supported

**Comment by richardliaw** [comment]
Thanks for opening this issue! Normal multiprocessing doesn't work on this either right?

Can you provide a reproduction script where this works on generic Python multiprocessing but not Ray?

**Comment by icaropires** [comment]
@richardliaw using just generic Python multiprocessing, it works. Maybe this should be considered a bug :thinking: :

### Script with generic Python multiprocessing
``` python
from multiprocessing import Pool


def f(x):
    return x + 10


generator = (i for i in range(100000))
with Pool() as pool:
   result = list(pool.imap_unordered(
       f, generator, chunksize=100,
    ))

print(result[:10])
``` 
#### Output
`[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]`

### Script with Ray multiprocessing

``` python
from ray.util.multiprocessing import Pool


def f(x):
    return x + 10


generator = (i for i in range(100000))
with Pool() as pool:
   result = list(pool.imap_unordered(
       f, generator, chunksize=100,
    ))

print(result[:10])
```
#### Output
```
2020-07-31 18:49:48,111	INFO resource_spec.py:204 -- Starting Ray with 5.52 GiB memory available for workers and up to 2.77 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-07-31 18:49:48,328	WARNING services.py:923 -- Redis failed to start, retrying now.
2020-07-31 18:49:48,524	INFO services.py:1163 -- View the Ray dashboard at localhost:8265
Traceback (most recent call last):
  File "a.py", line 10, in <module>
    result = list(pool.imap_unordered(
  File "/home/icaro/Desktop/pdf2dataset/env/lib64/python3.8/site-packages/ray/util/multiprocessing/pool.py", line 631, in imap_unordered
    return UnorderedIMapIterator(self, func, iterable, chunksize=chunksize)
  File "/home/icaro/Desktop/pdf2dataset/env/lib64/python3.8/site-packages/ray/util/multiprocessing/pool.py", line 196, in __init__
    self._submit_next_chunk()
  File "/home/icaro/Desktop/pdf2dataset/env/lib64/python3.8/site-packages/ray/util/multiprocessing/pool.py", line 204, in _submit_next_chunk
    new_chunk_id = self._pool._submit_chunk(self._func, self._iterator,
  File "/home/icaro/Desktop/pdf2dataset/env/lib64/python3.8/site-packages/ray/util/multiprocessing/pool.py", line 492, in _submit_chunk
    return self._run_batch(actor_index, func, chunk)
  File "/home/icaro/Desktop/pdf2dataset/env/lib64/python3.8/site-packages/ray/util/multiprocessing/pool.py", line 414, in _run_batch
    object_id = actor.run_batch.remote(func, batch)
  File "/home/icaro/Desktop/pdf2dataset/env/lib64/python3.8/site-packages/ray/actor.py", line 101, in remote
    return self._remote(args, kwargs)
  File "/home/icaro/Desktop/pdf2dataset/env/lib64/python3.8/site-packages/ray/actor.py", line 121, in _remote
    return invocation(args, kwargs)
  File "/home/icaro/Desktop/pdf2dataset/env/lib64/python3.8/site-packages/ray/actor.py", line 111, in invocation
    return actor._actor_method_call(
  File "/home/icaro/Desktop/pdf2dataset/env/lib64/python3.8/site-packages/ray/actor.py", line 716, in _actor_method_call
    object_ids = worker.core_worker.submit_actor_task(
  File "python/ray/_raylet.pyx", line 946, in ray._raylet.CoreWorker.submit_actor_task
  File "python/ray/_raylet.pyx", line 952, in ray._raylet.CoreWorker.submit_actor_task
  File "python/ray/_raylet.pyx", line 276, in ray._raylet.prepare_args
  File "/home/icaro/Desktop/pdf2dataset/env/lib64/python3.8/site-packages/ray/serialization.py", line 396, in serialize
    return self._serialize_to_msgpack(metadata, value)
  File "/home/icaro/Desktop/pdf2dataset/env/lib64/python3.8/site-packages/ray/serialization.py", line 368, in _serialize_to_msgpack
    self._serialize_to_pickle5(metadata, python_objects)
  File "/home/icaro/Desktop/pdf2dataset/env/lib64/python3.8/site-packages/ray/serialization.py", line 348, in _serialize_to_pickle5
    raise e
  File "/home/icaro/Desktop/pdf2dataset/env/lib64/python3.8/site-packages/ray/serialization.py", line 344, in _serialize_to_pickle5
    inband = pickle.dumps(
  File "/home/icaro/Desktop/pdf2dataset/env/lib64/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 70, in dumps
    cp.dump(obj)
  File "/home/icaro/Desktop/pdf2dataset/env/lib64/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 656, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'generator' object
```
### Environment
**ray version:** 0.8.6
**python version:** 3.8.3

**Comment by proteos** [comment]
I'd love to see this resolved. Will this be addressed?
P.S. Alternatively, I'd love to know what is the preferred way to work with generators that my code receives. Shall I unpack items first and then somehow feed into my remote function?

**Comment by cszhu** [comment]
Hello! This P3 issue has seen no activity in at least a year. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
