### ISSUE TITLE
Trials did not complete

### ISSUE THREAD

**Issue by guoxuxu** [ray-project/ray#9750]
tune
### Describe your feature request
Can we know which line in our code file triggers "Trials did not complete" Error?
Don't know where to edit when everything is wrapped

**Comment by stefanbschneider** [comment]
If you scroll up in your logs, there should be the full error trace.

**Comment by guoxuxu** [comment]
Thank you very much!

**Comment by zzcNEU** [comment]
> If you scroll up in your logs, there should be the full error trace.

Hello, I just run the examples Python examples/attention_net.py.
But,
![image](https://user-images.githubusercontent.com/38434094/92733021-c64a4480-f3a9-11ea-9a57-7299c64befa8.png)

**Comment by stefanbschneider** [comment]
Did you scroll up and/or check the error file for the cause of the error?

**Comment by zzcNEU** [comment]
Yes, I find the error.txt.
![image](https://user-images.githubusercontent.com/38434094/92745939-6194e700-f3b5-11ea-9d7b-2d7797b95911.png)

**Comment by guoxuxu** [comment]
I think the error is raised with TensorFlow. It warns that your input data (data type, and shape) is incorrect

**Comment by loretoparisi** [comment]
@stefanbschneider I think to have a similar error.

this is my full stack trace

```
env: CUDA_VISIBLE_DEVICES=0
/home/ec2-user/SageMaker/music-trees
Global seed set to 42
/home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:64: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  INST_TAXONOMY = yaml.load(fhandle)
/home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:72: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  MIXING_COEFFICIENTS = yaml.load(fhandle)
Global seed set to 42
2021-11-25:14:29:28,109 INFO     [seed.py:54] Global seed set to 42
2021-11-25:14:29:28,267 INFO     [tune.py:748] Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2021-11-25 14:29:30,629	WARNING experiment.py:272 -- No name detected on trainable. Using DEFAULT.
2021-11-25 14:29:30,629	INFO registry.py:70 -- Detected unknown callable for trainable. Converting to class.
(pid=27090) Global seed set to 42
(pid=27090) /home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:64: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
(pid=27090)   INST_TAXONOMY = yaml.load(fhandle)
(pid=27090) /home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:72: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
(pid=27090)   MIXING_COEFFICIENTS = yaml.load(fhandle)
(pid=27090) Global seed set to 42
(pid=27090) 2021-11-25:14:29:34,481 INFO     [seed.py:54] Global seed set to 42
== Status ==
Current time: 2021-11-25 14:29:30 (running for 00:00:00.15)
Memory usage on this node: 3.9/15.4 GiB
Using AsyncHyperBand: num_stopped=0
Bracket: Iter 60000.000: None
Resources requested: 1.0/4 CPUs, 1.0/1 GPUs, 0.0/7.41 GiB heap, 0.0/3.71 GiB objects (0.0/1.0 accelerator_type:T4)
Result logdir: /home/ec2-user/SageMaker/music-trees/runs/height-v1-11.25.2021/height-v1
Number of trials: 5/5 (4 PENDING, 1 RUNNING)
+---------------------+----------+---------------------+----------+
| Trial name          | status   | loc                 |   height |
|---------------------+----------+---------------------+----------|
| DEFAULT_1a159_00000 | RUNNING  | xxx.xxx.xxx.xxx:27090 |        4 |
| DEFAULT_1a159_00001 | PENDING  |                     |        2 |
| DEFAULT_1a159_00002 | PENDING  |                     |        0 |
| DEFAULT_1a159_00003 | PENDING  |                     |        3 |
| DEFAULT_1a159_00004 | PENDING  |                     |        1 |
+---------------------+----------+---------------------+----------+

...

Traceback (most recent call last):
  File "music_trees/search.py", line 161, in <module>
    run_experiment(exp)
  File "music_trees/search.py", line 134, in run_experiment
    progress_reporter=reporter)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/tune/tune.py", line 624, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [DEFAULT_1a159_00000, DEFAULT_1a159_00001, DEFAULT_1a159_00002, DEFAULT_1a159_00003, DEFAULT_1a159_00004])

...

2021-11-25 14:29:34,848	ERROR trial_runner.py:924 -- Trial DEFAULT_1a159_00000: Error processing event.
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 890, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 788, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/worker.py", line 1625, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): ray::ImplicitFunc.train_buffered() (pid=27090, ip=xxx.xxx.xxx.xxx, repr=<types.ImplicitFunc object at 0x7fd9bf71bf28>)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/tune/trainable.py", line 224, in train_buffered
    result = self.train()
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/tune/trainable.py", line 283, in train
    result = self.step()
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 381, in step
    self._report_thread_runner_error(block=True)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 529, in _report_thread_runner_error
    ("Trial raised an exception. Traceback:\n{}".format(err_tb_str)
ray.tune.error.TuneError: Trial raised an exception. Traceback:
ray::ImplicitFunc.train_buffered() (pid=27090, ip=xxx.xxxx.xxx.xxx, repr=<types.ImplicitFunc object at 0x7fd9bf71bf28>)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 262, in run
    self._entrypoint()
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 331, in entrypoint
    self._status_reporter.get_checkpoint())
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 599, in _trainable_func
    output = fn()
  File "music_trees/search.py", line 110, in run_trial
    return mt.train.train(hparams, use_ray=True)
  File "/home/ec2-user/SageMaker/music-trees/music_trees/train.py", line 113, in train
    trainer.fit(task, datamodule=datamodule)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 471, in fit
    self.call_setup_hook(model)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1070, in call_setup_hook
    self.datamodule.setup(stage_name)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pytorch_lightning/core/datamodule.py", line 92, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/ec2-user/SageMaker/music-trees/music_trees/data.py", line 313, in setup
    **self.tr_kwargs)
  File "/home/ec2-user/SageMaker/music-trees/music_trees/data.py", line 90, in __init__
    self.files = self._load_files(name, partition)
  File "/home/ec2-user/SageMaker/music-trees/music_trees/data.py", line 144, in _load_files
    assert len(new_records) > 0
AssertionError
Result for DEFAULT_1a159_00000:
  date: 2021-11-25_14-29-34
  experiment_id: 7d8bf6c62b2c4205b523603c1f17b0d9
  hostname: ip-xxx-xxx-xxx-xxx
  node_ip: xxx.xxx.xxx.xxx
  pid: 27090
  timestamp: 1637850574
  trial_id: 1a159_00000
  
(pid=27090) GPU available: True, used: True
(pid=27090) 2021-11-25:14:29:34,807 INFO     [distributed.py:54] GPU available: True, used: True
(pid=27090) TPU available: None, using: 0 TPU cores
(pid=27090) 2021-11-25:14:29:34,807 INFO     [distributed.py:54] TPU available: None, using: 0 TPU cores
(pid=27090) Using native 16bit precision.
(pid=27090) 2021-11-25:14:29:34,807 INFO     [accelerator_connector.py:331] Using native 16bit precision.
(pid=27090) 2021-11-25:14:29:34,811 INFO     [data.py:125] loading files
0it [00:00, ?it/s]0) 
0it [00:00, ?it/s]0) 
0it [00:00, ?it/s]0) 
0it [00:00, ?it/s]0) 
0it [00:00, ?it/s]0) 
0it [00:00, ?it/s]0) 
0it [00:00, ?it/s]0) 

...

(pid=27090) 2021-11-25:14:29:34,833 INFO     [data.py:131] done
(pid=27090) 2021-11-25 14:29:34,833	ERROR function_runner.py:268 -- Runner Thread raised error.
(pid=27090) Traceback (most recent call last):
(pid=27090)   File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 262, in run
(pid=27090)     self._entrypoint()
(pid=27090)   File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 331, in entrypoint
(pid=27090)     self._status_reporter.get_checkpoint())
(pid=27090)   File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/util/tracing/tracing_helper.py", line 451, in _resume_span
(pid=27090)     return method(self, *_args, **_kwargs)
(pid=27090)   File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 599, in _trainable_func
(pid=27090)     output = fn()
(pid=27090)   File "music_trees/search.py", line 110, in run_trial
(pid=27090)     return mt.train.train(hparams, use_ray=True)
(pid=27090)   File "/home/ec2-user/SageMaker/music-trees/music_trees/train.py", line 113, in train
(pid=27090)     trainer.fit(task, datamodule=datamodule)
(pid=27090)   File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 471, in fit
(pid=27090)     self.call_setup_hook(model)
(pid=27090)   File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1070, in call_setup_hook
(pid=27090)     self.datamodule.setup(stage_name)
(pid=27090)   File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pytorch_lightning/core/datamodule.py", line 92, in wrapped_fn
(pid=27090)     return fn(*args, **kwargs)
(pid=27090)   File "/home/ec2-user/SageMaker/music-trees/music_trees/data.py", line 313, in setup
(pid=27090)     **self.tr_kwargs)
(pid=27090)   File "/home/ec2-user/SageMaker/music-trees/music_trees/data.py", line 90, in __init__
(pid=27090)     self.files = self._load_files(name, partition)
(pid=27090)   File "/home/ec2-user/SageMaker/music-trees/music_trees/data.py", line 144, in _load_files
(pid=27090)     assert len(new_records) > 0
(pid=27090) AssertionError
(pid=27090) Exception in thread Thread-2:
(pid=27090) Traceback (most recent call last):
(pid=27090)   File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
(pid=27090)     self.run()
(pid=27090)   File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 281, in run
(pid=27090)     raise e
(pid=27090)   File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 262, in run
(pid=27090)     self._entrypoint()
(pid=27090)   File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 331, in entrypoint
(pid=27090)     self._status_reporter.get_checkpoint())
(pid=27090)   File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/util/tracing/tracing_helper.py", line 451, in _resume_span
(pid=27090)     return method(self, *_args, **_kwargs)
(pid=27090)   File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/tune/function_runner.py", line 599, in _trainable_func
(pid=27090)     output = fn()
(pid=27090)   File "music_trees/search.py", line 110, in run_trial
(pid=27090)     return mt.train.train(hparams, use_ray=True)
(pid=27090)   File "/home/ec2-user/SageMaker/music-trees/music_trees/train.py", line 113, in train
(pid=27090)     trainer.fit(task, datamodule=datamodule)
(pid=27090)   File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 471, in fit
(pid=27090)     self.call_setup_hook(model)
(pid=27090)   File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1070, in call_setup_hook
(pid=27090)     self.datamodule.setup(stage_name)
(pid=27090)   File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pytorch_lightning/core/datamodule.py", line 92, in wrapped_fn
(pid=27090)     return fn(*args, **kwargs)
(pid=27090)   File "/home/ec2-user/SageMaker/music-trees/music_trees/data.py", line 313, in setup
(pid=27090)     **self.tr_kwargs)
(pid=27090)   File "/home/ec2-user/SageMaker/music-trees/music_trees/data.py", line 90, in __init__
(pid=27090)     self.files = self._load_files(name, partition)
(pid=27090)   File "/home/ec2-user/SageMaker/music-trees/music_trees/data.py", line 144, in _load_files
(pid=27090)     assert len(new_records) > 0
(pid=27090) AssertionError
(pid=27090) 
(pid=27089) Global seed set to 42
(pid=27089) /home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:64: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
(pid=27089)   INST_TAXONOMY = yaml.load(fhandle)
(pid=27089) /home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:72: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
(pid=27089)   MIXING_COEFFICIENTS = yaml.load(fhandle)
(pid=27089) Global seed set to 42
(pid=27089) 2021-11-25:14:29:38,493 INFO     [seed.py:54] Global seed set to 42
== Status ==
Current time: 2021-11-25 14:29:35 (running for 00:00:05.20)
Memory usage on this node: 3.9/15.4 GiB
Using AsyncHyperBand: num_stopped=0
Bracket: Iter 60000.000: None
Resources requested: 1.0/4 CPUs, 1.0/1 GPUs, 0.0/7.41 GiB heap, 0.0/3.71 GiB objects (0.0/1.0 accelerator_type:T4)
Result logdir: /home/ec2-user/SageMaker/music-trees/runs/height-v1-11.25.2021/height-v1
Number of trials: 5/5 (1 ERROR, 3 PENDING, 1 RUNNING)
+---------------------+----------+---------------------+----------+
| Trial name          | status   | loc                 |   height |
|---------------------+----------+---------------------+----------|
| DEFAULT_1a159_00001 | RUNNING  | xxx.xxx.xxx.xxx:27089 |        2 |
| DEFAULT_1a159_00002 | PENDING  |                     |        0 |
| DEFAULT_1a159_00003 | PENDING  |                     |        3 |
| DEFAULT_1a159_00004 | PENDING  |                     |        1 |
| DEFAULT_1a159_00000 | ERROR    | xxx.xxx.xxx.xxx8:27090 |        4 |
+---------------------+----------+---------------------+----------+
Number of errored trials: 1
+---------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------+
| Trial name          |   # failures | error file                                                                                                                            |
|---------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------|
| DEFAULT_1a159_00000 |            1 | /home/ec2-user/SageMaker/music-trees/runs/height-v1-11.25.2021/height-v1/DEFAULT_1a159_00000_0_height=4_2021-11-25_14-29-30/error.txt |
+---------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------+
...
```

**Comment by stefanbschneider** [comment]
@loretoparisi Hi, the `TuneError` with `Trials did not complete` just indicates that something else went wrong while running tune. Tune is not causing the error itself.

If you look at your error trace, it seems like the root cause is here:
```
File "/home/ec2-user/SageMaker/music-trees/music_trees/data.py", line 144, in _load_files
    assert len(new_records) > 0
```

So corresponding to the code here: https://github.com/hugofloresgarcia/music-trees/blob/main/music_trees/data.py#L144

To me, it seems like there is something wrong with the records in `files.items()` (a few lines above), such that the loop does not add any entries to the `new_recods`  list, ultimately raising the `AssertionError`.
So this should be completely unrelated to Ray Tune.

**Comment by loretoparisi** [comment]
Thanks you @stefanbschneider for details and checking the code, in fact it seems so, first time I was using ray, so it was difficult to dig into this logging. Thanks a lot again.
