### ISSUE TITLE
[rllib] Observation_space cannot be passed to Preprocessor 

### ISSUE THREAD

**Issue by anguyenbus** [ray-project/ray#9810]
rllib
### What is your question?

Hi, I dont know why Observation from my observation_space cannot be passed into the Trainer.

This is my observation_space:

```
self.obs_x = spaces.Box(low=-3,
                                high=3, 
                                shape=(self.batch_size, self.embed_dim),
                                dtype=np.float64)
        
self.obs_x_b = spaces.Box(low=-3,
                                  high=3,
                                  shape=(self.batch_size, self.m_groups*self.heads),
                                  dtype=np.float64)
        
self.observation_space = spaces.Tuple([self.obs_x, self.obs_x_b])
```

Action_space
self.action_space = spaces.Discrete(16)

config = DEFAULT_CONFIG.copy()
config["num_gpus"] = 1
config["num_workers"] = 1
config["eager"] = False
config["log_level"] = "INFO"
config["monitor"] = True
config["num_cpus_per_worker"] = 1
config["use_pytorch"] = 1
config["framework"] = 'torch'
config["sample_batch_size"] = 300
trainer = SACTrainer(config=config, env="MyEnv")

```
*Ray version and other system information (Python version, TensorFlow version, OS):*
RayTaskError(ValueError)                  Traceback (most recent call last)
<ipython-input-13-9634065d661e> in <module>()
----> 1 trainer.train()
      2 pdb.set_trace()

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/rllib/agents/trainer.py in train(self)
    495                         "continue training without the failed worker, set "
    496                         "`'ignore_worker_failures': True`.")
--> 497                     raise e
    498             except Exception as e:
    499                 time.sleep(0.5)  # allow logs messages to propagate

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/rllib/agents/trainer.py in train(self)
    484         for _ in range(1 + MAX_WORKER_FAILURE_RETRIES):
    485             try:
--> 486                 result = Trainable.train(self)
    487             except RayError as e:
    488                 if self.config["ignore_worker_failures"]:

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/tune/trainable.py in train(self)
    259         """
    260         start = time.time()
--> 261         result = self._train()
    262         assert isinstance(result, dict), "_train() needs to return a dict."
    263 

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py in _train(self)
    130         def _train(self):
    131             if self.train_exec_impl:
--> 132                 return self._train_exec_impl()
    133 
    134             if before_train_step:

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py in _train_exec_impl(self)
    168 
    169         def _train_exec_impl(self):
--> 170             res = next(self.train_exec_impl)
    171             return res
    172 

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/util/iter.py in __next__(self)
    729     def __next__(self):
    730         self._build_once()
--> 731         return next(self.built_iterator)
    732 
    733     def __str__(self):

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/util/iter.py in apply_foreach(it)
    742 
    743             def apply_foreach(it):
--> 744                 for item in it:
    745                     if isinstance(item, _NextValueNotReady):
    746                         yield item

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/util/iter.py in apply_filter(it)
    812     def filter(self, fn: Callable[[T], bool]) -> "LocalIterator[T]":
    813         def apply_filter(it):
--> 814             for item in it:
    815                 with self._metrics_context():
    816                     if isinstance(item, _NextValueNotReady) or fn(item):

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/util/iter.py in apply_filter(it)
    812     def filter(self, fn: Callable[[T], bool]) -> "LocalIterator[T]":
    813         def apply_filter(it):
--> 814             for item in it:
    815                 with self._metrics_context():
    816                     if isinstance(item, _NextValueNotReady) or fn(item):

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/util/iter.py in apply_foreach(it)
    742 
    743             def apply_foreach(it):
--> 744                 for item in it:
    745                     if isinstance(item, _NextValueNotReady):
    746                         yield item

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/util/iter.py in apply_filter(it)
    812     def filter(self, fn: Callable[[T], bool]) -> "LocalIterator[T]":
    813         def apply_filter(it):
--> 814             for item in it:
    815                 with self._metrics_context():
    816                     if isinstance(item, _NextValueNotReady) or fn(item):

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/util/iter.py in build_union(timeout)
   1045                     try:
   1046                         for _ in range(max_pull):
-> 1047                             item = next(it)
   1048                             if isinstance(item, _NextValueNotReady):
   1049                                 if timeout is not None:

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/util/iter.py in __next__(self)
    729     def __next__(self):
    730         self._build_once()
--> 731         return next(self.built_iterator)
    732 
    733     def __str__(self):

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/util/iter.py in apply_foreach(it)
    742 
    743             def apply_foreach(it):
--> 744                 for item in it:
    745                     if isinstance(item, _NextValueNotReady):
    746                         yield item

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/util/iter.py in apply_foreach(it)
    742 
    743             def apply_foreach(it):
--> 744                 for item in it:
    745                     if isinstance(item, _NextValueNotReady):
    746                         yield item

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/util/iter.py in apply_foreach(it)
    742 
    743             def apply_foreach(it):
--> 744                 for item in it:
    745                     if isinstance(item, _NextValueNotReady):
    746                         yield item

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/util/iter.py in apply_foreach(it)
    742 
    743             def apply_foreach(it):
--> 744                 for item in it:
    745                     if isinstance(item, _NextValueNotReady):
    746                         yield item

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/util/iter.py in base_iterator(timeout)
    443             while active:
    444                 try:
--> 445                     yield ray.get(futures, timeout=timeout)
    446                     futures = [a.par_iter_next.remote() for a in active]
    447                     # Always yield after each round of gets with timeout.

~/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/worker.py in get(object_ids, timeout)
   1472                     worker.core_worker.dump_object_store_memory_usage()
   1473                 if isinstance(value, RayTaskError):
-> 1474                     raise value.as_instanceof_cause()
   1475                 else:
   1476                     raise value

RayTaskError(ValueError): ray::RolloutWorker.par_iter_next() (pid=31556, ip=192.168.2.9)
  File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 400, in ray._raylet.execute_task.function_executor
  File "/home/incubator/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/util/iter.py", line 1125, in par_iter_next
    return next(self.local_it)
  File "/home/incubator/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 263, in gen_rollouts
    yield self.sample()
  File "/home/incubator/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 528, in sample
    batches = [self.input_reader.next()]
  File "/home/incubator/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 59, in next
    batches = [self.get_data()]
  File "/home/incubator/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 164, in get_data
    item = next(self.rollout_provider)
  File "/home/incubator/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 489, in _env_runner
    observation_fn=observation_fn)
  File "/home/incubator/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 641, in _process_observations
    policy_id).transform(raw_obs)
  File "/home/incubator/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/rllib/models/preprocessors.py", line 199, in transform
    self.check_shape(observation)
  File "/home/incubator/anaconda3/envs/rsm-rl/lib/python3.6/site-packages/ray/rllib/models/preprocessors.py", line 62, in check_shape
    self._obs_space, observation)
ValueError: ('Observation outside expected value range', Tuple(Box(31, 100), Box(31, 120)), None)
```

**Comment by sven1977** [comment]
Could you post a simple repro script that we can just copy and debug with?

**Comment by anguyenbus** [comment]
> Could you post a simple repro script that we can just copy and debug with?

https://github.com/anguyenbus/testing_repro Thank you, I have created a repro repo here with the requirements file.
