### ISSUE TITLE
[autoscaler]Error when using the new logger

### ISSUE THREAD

**Issue by allenyin55** [ray-project/ray#9948]
### What is the problem?

This cluster.yaml used to work

```yaml
cluster_name: test_cluster
max_workers: 0
min_workers: 0
provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a
setup_commands:
  - 'echo ''{"cli_token": "some-token"}'' > /tmp/test'
  - 'pip install ray[all] || true'
auth:
    ssh_user: ubuntu
```
With the new CLI logger in autoscaler, I'm getting this error when running `ray up cluster.yaml`

```
Error executing: unmatched '{' in format spec

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/allenyin/anaconda3/lib/python3.7/site-packages/ray/autoscaler/updater.py", line 74, in run
    self.do_update()
  File "/Users/allenyin/anaconda3/lib/python3.7/site-packages/ray/autoscaler/updater.py", line 285, in do_update
    cmd_to_print, _numbered=("()", i, total))
  File "/Users/allenyin/anaconda3/lib/python3.7/site-packages/ray/autoscaler/cli_logger.py", line 323, in print
    self._print(_format_msg(msg, *args, **kwargs))
  File "/Users/allenyin/anaconda3/lib/python3.7/site-packages/ray/autoscaler/cli_logger.py", line 96, in _format_msg
    return numbering_str + msg.format(*args, **kwargs) + tags_str
ValueError: unmatched '{' in format spec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/allenyin/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/allenyin/anaconda3/lib/python3.7/site-packages/ray/autoscaler/updater.py", line 95, in run
    cli_logger.error(str(e))  # todo: handle this better somehow?
  File "/Users/allenyin/anaconda3/lib/python3.7/site-packages/ray/autoscaler/cli_logger.py", line 316, in error
    self._print(_format_msg(cf.red(msg), *args, **kwargs))
  File "/Users/allenyin/anaconda3/lib/python3.7/site-packages/ray/autoscaler/cli_logger.py", line 96, in _format_msg
    return numbering_str + msg.format(*args, **kwargs) + tags_str
ValueError: expected '}' before end of string
```

*Ray version and other system information (Python version, TensorFlow version, OS): ray from this commit dba999b6f61cb30237d821aa86691a15ff10e15b, python 3.7.4, macos 10.15.5

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by allenyin55** [comment]
cc: @richardliaw
